### ISSUE TITLE
Offer V8 startup snapshots

### ISSUE THREAD

**Issue by janbiedermann** [arangodb/arangodb#10017]
I would like to use very large amounts of javascript code within the database context in any place the execution of javascript is allowed. For that i would like to be able to make those very large amounts of javascript code available as modules and be able to load them into arango somehow. For performance, it would be perfect if i could initialize the various js contexts used within arango with that large amounts of code, so that that code doesn't have to be evaluated for each execution over an over again.

For FOXXES that is not a problem, as i can ship that large amounts of code within a FOXX.

But for any other way to execute javascript, Tasks, etc., that is a problem. There was a way to make modules available by using the _modules collection, but that is deprecated.

I require a new way.

**Comment by Simran-B** [comment]
The best solution would likely be to use a [custom V8 startup snapshot](https://v8.dev/blog/custom-startup-snapshots). I'm not sure if this is possible to create and use with an official build/package, or if it would require a custom ArangoDB build.

**Comment by dothebart** [comment]
Please note that this most probably will only be possible with the V8 version that the current arangodb devel version ships.

**Comment by janbiedermann** [comment]
Thanks for you comments! I was hoping for a way that would work in Oasis in the long term.
Maybe a API endpoint to ship said assets, which would notify all v8 instances to shut down asap and instantiate again with the new assets, across the cluster. A custom V8 snapshot will do for the moment.

**Comment by janbiedermann** [comment]
i no longer use arangodb
