### ISSUE TITLE
Unable to Save keys with different Charset

### ISSUE THREAD

**Issue by samueldedavid** [arangodb/arangodb#10031]
Hi I am using spring data with arangodb . My model has id name of String with 
 `@Id `
when I try to save , it works only for strings that have English alphabets but when I save something value as  

> Åf

 it throws
` Response: 400, Error: 1221 - illegal document key exception`. 
I have to save these names in the database as is so I do not want to change them .Is there any other way to fix this issue. Is there a way to solve this problem ..??

**Comment by jsteemann** [comment]
This is a expected, as there are restrictions for what characters can be used in document keys.
Please refer to https://www.arangodb.com/docs/stable/data-modeling-naming-conventions-document-keys.html for details.
