### ISSUE TITLE
High Memory usage on load 

### ISSUE THREAD

**Issue by mahesth** [arangodb/arangodb#10044]
Hi, 

I am facing out of memory issue frequently due to high memory usage by arango

Below are my environment configuration 

* __ArangoDB Version__:        3.2.18
* __Storage Engine__:            MMFiles 
* __Deployment Mode__:       Single Server 
* __Deployment Strategy__:   ArangoDB Starter 
* __Infrastructure__:               Own
* __Operating System__:        CentOS Linux
* __Total RAM __:       32Gb.
* __Used Package__:             CentOS Linux

## Component, Query & Data

__Affected feature__:

Memory Usage, Query Execution

__Problem__:

While starting arangod service on startup, it continues to use **93% of the RAM memory** all the time. So while executing long running queries, it crashes due to out of memory. 

Below is the attached for the memory usage. 

![image](https://user-images.githubusercontent.com/25684319/65220274-fe40e380-dad7-11e9-82e6-05fbea16e87e.png)

**For Example:** 

We have a long running query which runs for around 70 seconds and has 500K data, if more such queries executed in parallel, it will run out of memory and it got crashed. 

Also when arangod restarted , we were unable to find the crash dumps. 

__Expected result__:

Not Crash

**__ Is there any ways to reduce the memory usage ? and where can we find the Crash dumps ?**

**Note:** 

We cant disable server statistics and Foxx as we depend on it heavily. 

Thanks,
Maheswaran

**Comment by graetzer** [comment]
are you really using ArangoDB 3.2.18 ? 
If you upgrade to at least 3.4 you should be able to use `stream` query cursors, this might help you.

**Comment by mahesth** [comment]
Hi @graetzer 

Thanks for your response. 

Yes we are using 3.2.18. 
The issue we were facing is not with the query execution time, but with the idle memory usage by Arango. It always occupied 89 to 93% of RAM memory as soon as all our collections are loaded (No Traffic in the DB). 

**Will upgrading to 3.4 would reduce the RAM usage by Arango ?**

**Also, is there anywhere we can find the crash dump ? (Both older and latest version of Arango) ?**

Thanks,
Maheswaran

**Comment by graetzer** [comment]
hm yes thats sounds typical problem with the MMFiles engine. You might consider removing indexes or move to the rocksdb engine.
The stream cursors would make your queries use less memory while they run.

**Comment by graetzer** [comment]
Coredumps probably need to be enabled on your machine, systemd sometimes copies them somwehere else.

**Comment by OmarAyo** [comment]
Hi @mahesth 

You are on ArangoDB version 3.2 that is out of support since March 31, 2019 (see EOL announcement: https://www.arangodb.com/eol-notice/) 

We suggest you upgrade to 3.5 that is our current GA, we also suggest you changing your storage engine to RocksDB to be able to use some useful rocksdb option to limit the memory usage

Best,

**Comment by OmarAyo** [comment]
Hi @mahesth 

Did you have the chance to read our previous messages ? Please provide an update

Best

**Comment by maxkernbach** [comment]
Hi @mahesth,

Since we have not heard back from you recently I am closing this ticket now.

Please feel free to reopen it by adding a comment.
