### ISSUE TITLE
How to define Views in the Web-Interface?

### ISSUE THREAD

**Issue by qohelet** [arangodb/arangodb#10052]
## My Environment

* __ArangoDB Version__:        3.4.1
* __Storage Engine__:             RocksDB 
* __Deployment Mode__:       Single Server 
* __Deployment Strategy__:   Manual Start in Docker
* __Operating System__:        Ubuntu 18.04
* __Disks in use__:        HDD
* __Used Package__:              Ubuntu

## Component, Query & Data

__Affected feature__:
Web-Interface

__Problem__:
I'm not sure if Views are very close to the equivalent in SQL-Databases (and if I can use them as Vertex-Collections for Graphs) but I'm so far not able to successfully create one which is actually doing anything.

Creating a view in the Web-Interface just gives me access to a JSON-definition, but I wouldn't know how to put the AQL-Command for it. 

Couldn't find much information to that in the official documentation. What would be the easiest way to create a simple view showing all documents with a certain attribute?

Edit:
I have tried to create one according to these tutorials:

- https://www.arangodb.com/tutorials/tutorial-node-js/
- https://www.alibabacloud.com/blog/using-arangodb-within-a-nodejs-app_594908
- https://www.arangodb.com/docs/stable/arangosearch-examples.html

```
> db = new Database({'url': 'http://testserver.intranet.at:8112', 'database': 'MyTestDB', 'username': 'root',     'password': 'rootpassword'});
Database {
  _connection:
   Connection {
     config:
      { url: 'http://testserver.intranet.at:8112',
        databaseName: '_system',
        arangoVersion: 30000,
        retryConnection: false,
        database: 'MyTestDB',
        username: 'root',
        password: 'rootpassword',
        agentOptions: [Object],
        headers: [Object] },
     arangoMajor: 3,
     _baseUrl:
      Url {
        protocol: 'http:',
        slashes: true,
        host: 'testserver.intranet.at:8112',
        port: '8112',
        hostname: 'testserver.intranet.at.at',
        hash: null,
        search: null,
        query: null,
        pathname: '/',
        path: '/',
        href: 'http:/testserver.intranet.at:8112/' },
     _request: [Function: request],
     _databasePath: '/_db/_system',
     promisify: [Function],
     retryOptions:
      { forever: false, retries: 0, minTimeout: 5000, randomize: true } },
  _api:
   Route {
     _connection:
      Connection {
        config: [Object],
        arangoMajor: 3,
        _baseUrl: [Url],
        _request: [Function: request],
        _databasePath: '/_db/_system',
        promisify: [Function],
        retryOptions: [Object] },
     _path: '/_api',
     _headers: undefined },
  name: '_system' }

> v0 = db._createView("ExampleView", "arangosearch", {});
Thrown:
TypeError: db._createView is not a function
> 

```

**Comment by graetzer** [comment]
views are currently only supported as materialized views for arangosearch

**Comment by graetzer** [comment]
https://www.arangodb.com/docs/3.4/views-arango-search-getting-started.html

**Comment by qohelet** [comment]
Still it's just not working, I'm not sure what exactly is the problem but I'm unable to create anything useful.
I updated my original post to the JS I used. From the Python-Driver I couldn't find anything related to Views

**Comment by graetzer** [comment]
You are using the node.js driver, you are using the documentation for the arangodb shell. 
For the arangojs docs see https://www.arangodb.com/docs/stable/drivers/js-reference-view-manipulation.html

**Comment by qohelet** [comment]
I'm actually using pyArango and avoid any kind of JS as a good as I can. Took me a while to find the [correct page](https://python-driver-for-arangodb.readthedocs.io/en/master/view.html) there as it's not using any AQL.

But is there any development on the View-Feature? Using AQL-defined views like collections would be a practical feature

**Comment by dothebart** [comment]
Hi, 
AQL is strictly only a DML (Data modification language) - while creating views is a DDL (Data Definition Language) operation. So, no - this will not change in the future.

**Comment by Simran-B** [comment]
BTW. the more recent ArangoSearch documentation is here:
https://www.arangodb.com/docs/stable/arangosearch.html

**Comment by dothebart** [comment]
Closing this question as answered.

Please note that [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/)  is available.
