### ISSUE TITLE
Graphs are not Sync

### ISSUE THREAD

**Issue by sh0umik** [arangodb/arangodb#10051]
* __ArangoDB Version__:        3.5.0
* __Storage Engine__:             RocksDB
* __Deployment Mode__:        Master/Slave
* __Deployment Strategy__:    ArangoDB Starter in Docker
* __Configuration__:                default
* __Infrastructure__:                VULTR
* __Operating System__:         Ubuntu 18.04
* __Total RAM in your machine__:   4Gb
* __Disks in use__:        SSD
* __Used Package__:     Docker - official Docker library

__Affected feature__: Master/Slave Replication 

## Steps to reproduce

1. I have started two docker container running arangodb 3.5.0  
2. I followed the guide [here](https://www.arangodb.com/docs/stable/administration-master-slave-replication-applier.html) to start replication and used default parameter. (just changed to credential and ip,port)
3. **Everything synced except for GRAPHS** in slave.

__Problem__:

Is this common for Master/Slave replication ?

__Expected result__:

GRAPHS should also be synced in slave

**Comment by maxkernbach** [comment]
Hi @sh0umik,

Sorry for the late reply.

Since you used the default parameters, I assume you also used **includeSystem: false.** If this parameter is set to **false**, it is expected that graphs are not replicated. Setting **includeSystem** to **true** enables the replication of system collections (such as **_graphs**).

This is documented at the same page you linked in your initial post:

> The includeSystem attribute controls whether changes to system collections (such as _graphs or _users) should be applied. If set to true, changes in these collections will be replicated, otherwise, they will not be replicated. It is often not necessary to replicate data from system collections, especially because it may lead to confusion on the slave because the slave needs to have its own system collections in order to start and keep operational.

**Comment by sh0umik** [comment]
Thank you setting `includeSystem ` to true solves the problem. Also how can I convert a Slave Replicator to Master. Just want to Free the slave and use it as Master. Is it recommended ?

**Comment by maxkernbach** [comment]
Hi @sh0umik,

Sure swapping the Slave and Master can be done. Just make sure to stop the all write operations on your Master such that Master and Slave are in sync. Then you can stop the replication with the applier and start a new replication from your old Master that is using your old Slave as an endpoint.

For details on how to use the replication applier, please have a look at the link below:
https://www.arangodb.com/docs/3.4/administration-master-slave-replication-applier.html

**Comment by OmarAyo** [comment]
Hi @sh0umik 

I am closing this ticket as I see that maxkernbach has already answered you

Feel free to reopen this ticket in case you would like to discuss more this topic

Best

**Comment by sh0umik** [comment]
I got the answer i was looking for. Thx a lot.
