### ISSUE TITLE
how to get all count when limit

### ISSUE THREAD

**Issue by iamyinweijianGH** [arangodb/arangodb#10054]
## My Environment

* __ArangoDB Version__:         3.5
* __Storage Engine__:             RocksDB 
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:        
* __Total RAM in your machine__:        
* __Disks in use__:        
* __Used Package__:              

## Component, Query & Data

__Affected feature__:

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. 
2. 
3. 

__Problem__:
IN JAVA
```
@Query(FOR v,e,p IN 1..999999999 OUTBOUND  @id @@collection
FILTER xx(multiple codition)
LMIT 0,100)
```
i want to get all count, how to do?thanks
__Expected result__:

**Comment by iamyinweijianGH** [comment]
```
@Query(" FOR v,e,p IN 1..999999999 OUTBOUND  @id @@collection " +
            " FILTER condition"
            " LIMIT @page,@limit RETURN v")
    @QueryOptions(count = true, fullCount = true)
    ArangoCursor<UserGP> listGraph2(@BindVars Map<String, Object> bindvars);
```
can not get all count but limit count

**Comment by iamyinweijianGH** [comment]
oh, it worked, is my wrong

**Comment by iamyinweijianGH** [comment]
when i add 
`SORT`
like
```
@Query(" FOR v,e,p IN 1..999999999 OUTBOUND  @id @@collection " +
            " FILTER condition
           " SORT xxx " +
            " LIMIT @page,@limit RETURN v")
    @QueryOptions(fullCount = true)
    ArangoCursor<UserGP> listGraph2(@BindVars Map<String, Object> bindvars);
```

is not work..

**Comment by aveiros** [comment]
pass the rule `-sort-limit` on the query for now

there will be a fix soon for this

**Comment by iamyinweijianGH** [comment]
i put 
`SORT`
after 
`LIMIT`
worked....
