### ISSUE TITLE
"_fishbowl" collection not accessible and cannot be dropped on an ArangoDB Cluster envrionment

### ISSUE THREAD

**Issue by fdsg-tk** [arangodb/arangodb#10064]
## My Environment

* __ArangoDB Version__:        3.3.23
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   Manual Start 
* __Configuration__:              
* __Infrastructure__:               own
* __Operating System__:        CentOS 7.6
* __Total RAM in your machine__:        16GB
* __Disks in use__:        HDD RAID5
* __Used Package__:              RPM

## Component, Query & Data

__Size of your Dataset on disk__: < 1GB

__Replication Factor & Number of Shards (Cluster only)__:
_fishbowl collection is a _system collection with default settings:
replication factor 1, number of shards 1

## Steps to reproduce
This issue only affects all members of a single ArangoDB Cluster (therefore, reproduction on a fresh installed Cluster is not possible):
arangosh> col = db._fishbowl;
arangosh> col.count();

__Problem__:
* no output for _systems database and one of 3 custom databases on one affected cluster.
* truncate/drop not possible: ArangoError 1473: unable to truncate collection (dropping is forbidden): '_fishbowl' 
* only dump of (empty) collection is possible by arangodump, import by arangorestore is failing too with error message: ArangoError 1473: unable to truncate collection (dropping is forbidden): '_fishbowl' 

__Expected result__:
* show content of collection (even it is empty)
* show indexs of collection
* be able to truncate/drop collection

**Comment by jsteemann** [comment]
Can you try dropping the collection from the arangosh via
```
db._drop('_fishbowl', { isSystem: true });
```
If that works, it can be recreated properly via the command:
```
db._create('_fishbowl', { isSystem: true, distributeShardsLike: '_graphs' });
```

**Comment by fdsg-tk** [comment]
Yes, I was able to drop the Collection and have recreated a new working empty one.
Thanks a lot!
