### ISSUE TITLE
how to save edge in transaction?

### ISSUE THREAD

**Issue by iamyinweijianGH** [arangodb/arangodb#10089]
## My Environment

* __ArangoDB Version__:        3.5
* __Storage Engine__:             RocksDB 
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:        
* __Total RAM in your machine__:        
* __Disks in use__:        
* __Used Package__:              

## Component, Query & Data

__Affected feature__:

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

IN Java

```
@Data
public class user {

    @Id
    private String id;
    private String nickname;
    @Relations(edges = userOf.class, lazy = true)
    private Collection<UserOf> childs;
}
```

```
@Data
public class userOf {
    @Id
    private String id;
    @From
    private UserGP from;
    @To
    private UserGP to;
}
```
**When**
```
Map<String, Object> parameters = new MapBuilder()
                .put("u1", new User(xxxxxxxxx))
                .put("u2", new User(xxxxxxxxx))
                .get();


        ArangoDatabase db = operations.driver().db("xxx");
        TransactionOptions options = new TransactionOptions().params(parameters).writeCollections("user");
        String action = "function (params) { "
                + "const db = require('@arangodb').db; "
                + "db.user.save(params.u1);"
		+ "db.user.save(params.u2);"
                + "}";
        String transaction = db.transaction(action, String.class, options);
```

it work. But when i save **edge**, it fail, code like follow:

```
Map<String, Object> parameters = new MapBuilder()
                .put("uf", new userOf(xxxxxxxxx))
                .get();


        ArangoDatabase db = operations.driver().db("xxx");
        TransactionOptions options = new TransactionOptions().params(parameters).writeCollections("userOf");
        String action = "function (params) { "
                + "const db = require('@arangodb').db; "
		+ "db.userOf.save(params.uf);" // -----edge
                + "}";
        String transaction = db.transaction(action, String.class, options);
```
it show me : **com.arangodb.ArangoDBException: Response: 400, Error: 1233 - edge attribute missing or invalid**
__Problem__:

how to fix id and how to save the edge easily like **user** collection
__Expected result__:

thanks

**Comment by iamyinweijianGH** [comment]
when : db.userOf.save({ "_from":"user/1", "_to": "user/111111", "_key": "111111"});
it work, but too cumbersome , because i have to change bean to json

**Comment by HsbcJone** [comment]
I have the same problem. I suspect a bug in version 3.5

**Comment by rashtao** [comment]
The problem happens because the annotations `@Id`, `@From` and `@To` are only processed by Spring Data ArangoDB and not by the driver directly. When you call `operations.driver()` you are accessing the driver directly.

If you want Spring Data ArangoDB to serialize your entity, before passing them to the driver methods, you can inject `ArangoConverter` and call `arangoConverter.write(entity)`.

Furthermore to debug similar problems I suggest you enabling debug logging, so you could see the effective payload of your requests.

**Comment by dothebart** [comment]
Closing with the availability of [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/)
