### ISSUE TITLE
Extremely slow updates, plus timeouts cause future errors in query

### ISSUE THREAD

**Issue by rocketraman** [arangodb/arangodb#10097]
## My Environment

* __ArangoDB Version__:        3.4.7
* __Storage Engine__:             RocksDB
* __Deployment Mode__:        Cluster
* __Deployment Strategy__:    Kubernetes
* __Configuration__:                3 agents, 2 coords, 3 db servers
* __Infrastructure__:                Azure
* __Operating System__:        Ubuntu 18.04 nodes on Kubernetes 1.12.7
* __Total RAM in your machine__:        32Gb per node
* __Disks in use__:                 SSD
* __Used Package__:             Docker - official Docker library

## Component, Query & Data

__Affected feature__:
Database nodes

__AQL query (if applicable)__:
```
FOR f in files UPDATE f WITH { metadata: {} } IN files OPTIONS {exclusive: true}
```

__AQL explain (if applicable)__:
```
Query String:
 FOR f in files UPDATE f WITH { metadata: {} } IN files OPTIONS {exclusive: true}

Execution plan:
 Id   NodeType                  Site     Est.   Comment
  1   SingletonNode             DBS         1   * ROOT
  3   CalculationNode           DBS         1     - LET #3 = { "metadata" : { } }   /* json expression */   /* const assignment */
  2   EnumerateCollectionNode   DBS   6147458     - FOR f IN files   /* full collection scan, 1 shard(s) */
 11   RemoteNode                COOR  6147458       - REMOTE
 12   GatherNode                COOR  6147458       - GATHER 
  5   DistributeNode            COOR  6147458       - DISTRIBUTE  /* create keys: false, variable: f */
  6   RemoteNode                DBS   6147458       - REMOTE
  4   UpdateNode                DBS         0       - UPDATE f WITH #3 IN files 
  7   RemoteNode                COOR        0       - REMOTE
  8   GatherNode                COOR        0       - GATHER 

Indexes used:
 By   Type      Collection   Unique   Sparse   Selectivity   Fields       Ranges
  4   primary   files        true     false       100.00 %   [ `_key` ]   f

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   remove-data-modification-out-variables
  3   patch-update-statements
  4   distribute-in-cluster
  5   scatter-in-cluster
  6   remove-unnecessary-remote-scatter

Write query options:
 Option                   Value
 ignoreErrors             false
 waitForSync              false
 nullMeansRemove          false
 mergeObjects             true
 ignoreDocumentNotFound   false
 readCompleteInput        false
 useIsRestore             false
 consultAqlWriteFilter    false
 exclusive                true
 overwrite                false
 ignoreRevs               true
```

__Dataset__:
A bit over 6M rows in one collection, containing relatively small documents of about 512 bytes each.

__Size of your Dataset on disk__:
```
/ # du -ksh /var/lib/arangodb3
15.3G   /var/lib/arangodb3
```

__Replication Factor & Number of Shards (Cluster only)__:
Replication factor: 3
Shards: 1

## Steps to reproduce

1. Load 6M+ records into a collection.
2. Execute an update query that simply adds an empty object field to every row.
3. After the timeout, execute it again and notice the different error.

__Problem__:

The collections has a bit over 6M rows, as you can see in the explain plan.

There seems to be two problems here. The first is that this update query is so darn slow, even with exclusive turned on. I mean, I understand updating 6M rows is gonna take some time, but I don't see why it is taking so long that it is timing out with the default timeout / ttl settings. I never experienced any similar issue with traditional databases or MongoDB.

The second problem is that, once the timeout occurs, the database state is actually corrupted somehow, in such a way that submitting the same query fails in a different way -- with a timeout with the leader database optimizing the query plan, as opposed to running the query itself.

The first timeout received:

```
Operation aborted.
JavaScript exception in file '/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js' at 99,7: ArangoError 2000: Request timeout
!      throw error;
!      ^
stacktrace: ArangoError: Request timeout
    at Object.exports.checkRequestResult (/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js:97:21)
    at ArangoStatement.execute (/usr/share/arangodb3/js/client/modules/@arangodb/arango-statement.js:171:12)
    at Proxy.ArangoDatabase._query (/usr/share/arangodb3/js/client/modules/@arangodb/arango-database.js:946:42)
    at <shell command>:1:4
```

and then after that timeout is received, then the database times out while optimizing plan:

```
JavaScript exception in file '/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js' at 99,7: ArangoError 1457: AQL: timeout, cluster node: 'PRMR-eb3e1eb9-f705-46ce-b4a3-e9197c0ca770', endpoint: 'tcp://arangodb-db-1.arangodb-dbs.default.svc.cluster.local:8529', error: 'timeout in cluster operation' (while optimizing plan)
!      throw error;
!      ^
stacktrace: ArangoError: AQL: timeout, cluster node: 'PRMR-eb3e1eb9-f705-46ce-b4a3-e9197c0ca770', endpoint: 'tcp://arangodb-db-1.arangodb-dbs.default.svc.cluster.local:8529', error: 'timeout in cluster operation' (while optimizing plan)
    at Object.exports.checkRequestResult (/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js:97:21)
    at ArangoStatement.execute (/usr/share/arangodb3/js/client/modules/@arangodb/arango-statement.js:171:12)
    at Proxy.ArangoDatabase._query (/usr/share/arangodb3/js/client/modules/@arangodb/arango-database.js:946:42)
    at <shell command>:1:4
```

__Expected result__:

I would expect this query to not time out with the default settings. If it does timeout, I would not expect the database state to change in a way that causes different problems with future queries.

**Comment by graetzer** [comment]
Try setting the intermediateCommitCount option to something like 1024.

**Comment by graetzer** [comment]
See this page for an example: https://www.arangodb.com/docs/stable/aql/invocation-with-arangosh.html#setting-options

**Comment by rocketraman** [comment]
@graetzer Still timing out even with `intermediateCommitCount` set to 1024.

**Comment by graetzer** [comment]
so I suspect that your query is actually still running. Can you check in the UI?
 What times out is the request from the `arangosh` CLI which is just 1200 seconds

**Comment by graetzer** [comment]
you may increase that by running the shell with `arangosh --server.request-timeout 12000`

**Comment by rocketraman** [comment]
Something has got to be wrong here, right? The running queries tab in the UI shows that this query has been running for more than 2 days.

![image](https://user-images.githubusercontent.com/53049/65812651-d1f02b80-e197-11e9-86b4-2e63d08f732a.png)

**Comment by rocketraman** [comment]
Also, I am unable to kill the query.

```
var queries = require("org/arangodb/aql/queries");
queries.kill("187788");
```

returns code 200, but the query continues.

**Comment by rocketraman** [comment]
The query did eventually get killed, but I'm still trying to understand why it takes so long in the first place.

**Comment by rocketraman** [comment]
I haven't encountered the issue again, so closing for now.
