### ISSUE TITLE
Memory for index & datafiles not being freed after documents delete

### ISSUE THREAD

**Issue by roman1720** [arangodb/arangodb#10112]
## My Environment

* __ArangoDB Version__:        3.4.7
* __Storage Engine__:             MMFiles
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   ArangoDB Starter
* __Infrastructure__:               host in vmware
* __Operating System__:        Debian 9
* __Total RAM in your machine__:        32GB
* __Disks in use__:        HDD
* __Used Package__:             .deb

We periodically insert and delete datasets in database. I run into two problems:

1) Index memory is not being freed, but it's less problem, because it's reused later
2) Datafiles are not compacted and slowly fills diskspace

I tried following replication:

Insert 40M of documents, 4 sets of 10M.

for i in 1..10000000
insert {set: 1, i: i} into foo

repeat for set 2, 3, 4.

First set values - alive: 868MB, datafiles: 836MB, index: 472MB
All four sets values - alive: 3.51GB, datafiles: 3.49GB, index: 1.07GB

Now I delete set 1, 2, 3.

Alive: 880MB, datafiles 2.76, index 1.07GB

And again insert three set 1, 2, 3:

Alive 3.51GB, datafiles: 5.41GB, index 1.07GB

And detele again set 1, 2, 3:

Alive 880MB, datafiles: 4.69GB, index: 667MB

I tried to force compaction with following settings:

[compaction]
min-small-data-file-size = 131072000

Number of files was reduced from 134 to 27, but datafiles size is still 4.71GB.

I don't understand this behavior:

1) Why index memory is not freed even after deletion of 3/4 of documents
2) How to force arango to do better compaction, otherwise it will slowly grow and fill all disk space

I'm attaching file with screenshots from my test. 

Thank you

Roman

[arango_memory.docx](https://github.com/arangodb/arangodb/files/3671450/arango_memory.docx)

**Comment by ObiWahn** [comment]
Hi,
to inspect the disk-space issue there are some commands you could try the following commands:

- `db.<collection>.figures()` will give you information about the number and size of datafiles
- `require("internal").wal.flush(true, true)` moves data from WAL to journal
- `db.<collection>.rotate()` should close the current data-file and make it compactable
- with `db.<collection>.compact()` you can force a compaction

Note:
- Things in the WAL do not get compacted
- only complete (read-only) data-files get compacted
- deleting writes data! Therefore will increase the amount of data temporarily (until compacted)

If you provide us with the output of above commands and an additional `ls -lisah` in the database directory we could discuss the findings. I case you would provide us with the type of indexes used or best with a complete test script, then somebody could try to reproduce your problems locally.

**Comment by OmarAyo** [comment]
Hi @roman1720 

Did you have the chance to read ObiWahn's message ?

Please provide an update

Best,

**Comment by roman1720** [comment]
Hi, thank you for help. So we can start with this:

db._createDatabase('foo');
db._useDatabase('foo');
db._createDocumentCollection('foo');
db._query('for i in 1..10000000 insert {set: 1, i: i} into foo');
db._query('for i in 1..10000000 insert {set: 2, i: i} into foo');
db._query('for i in 1..10000000 insert {set: 3, i: i} into foo');
db._query('for i in 1..10000000 insert {set: 4, i: i} into foo');
db._query('for f in foo filter f.set == 1 remove f in foo');
db._query('for f in foo filter f.set == 2 remove f in foo');
db._query('for f in foo filter f.set == 3 remove f in foo');
require("internal").wal.flush(true, true);
db.foo.rotate();
db.foo.compact();

For indexes, I didn't create any extra, just watch system index on _key.

Number are same as above in my previous post. 

1) There was some compaction performed, but still datafiles are 3x bigger then they were when first set was inserted. Why is compaction so ineffective? When I will continue with inserting and deleting sets it will grow until it will fill whole disk.
2) Index size is 2x bigger then when first set was created. When I unload and load collection again index size drops to it's original size. Why indexes are not freed as should be? They can eat then considerable amount of memory.

**Comment by dothebart** [comment]
Hi, 
please note that ArangoDB 3.4 is EOLed. With the recently released [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) support for the MMFiles storage engine has been dropped. 
Please migrate your data over into a rocksdb installation.
