### ISSUE TITLE
write-write conflict 

### ISSUE THREAD

**Issue by Fruchtgummi** [arangodb/arangodb#10138]
## My Environment

* __ArangoDB Version__:        3.5.0
* __Storage Engine__:            RocksDB
* __Deployment Mode__:       Cluster 
* __Deployment Strategy__:   Kubernetes 
* __Configuration__:             3x Cordinatoren, 3x DB Servers
* __Infrastructure__:               AWS (3x t3.medium nodes)

* __Disks in use__:        SSD 

## Component, Query & Data

__Affected feature__:
GO-Driver, GoLang

__Replication Factor & Number of Shards (Cluster only)__:
 min 2, max 5

## Steps to reproduce

When writing the session by refresh expired time. Under certain circumstances it may happen that the requests "set session new" can not be processed because of too fast a page break.
So the next request is made on the same record and the previous one is not finished yet.

latency issues? 

The cluster runs slower than a single-server, and the app that communicates with the Arango cluster is a separate cluster.

Should I take the main-app with me to the Arangocluster?

Error:

"AQL: Error message received from cluster node 'PRMR-sbosa6ad': write-write conflict (while executing)"

**Comment by OmarAyo** [comment]
Hi @Fruchtgummi 

We invite you have a look at this page [here](https://www.arangodb.com/docs/stable/transactions-locking-and-isolation.html#locking) that  is describing the issue you are facing

As suggested there you can use the `exclusive` option to guarantee to have write-in sequential mode.

You can refer to this [link](https://www.arangodb.com/docs/stable/aql/operations-replace.html#setting-query-options) to set the exclusive option 

Let us know if this helps,

Best

**Comment by OmarAyo** [comment]
HI @Fruchtgummi,

I am sending this message to check if you had the chance to read my previous message

Best,

**Comment by OmarAyo** [comment]
Hi @Fruchtgummi 

We have not heard back from you recently, I am closing this ticket now - you can reopen it at any time by commenting

Best
