### ISSUE TITLE
Invalid Query Crashes ArangoDB

### ISSUE THREAD

**Issue by jbw3** [arangodb/arangodb#10158]
## My Environment

* __ArangoDB Version__:        3.5.0
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Operating System__:        Windows 10
* __Total RAM in your machine__:        32 GB
* __Disks in use__:        SSD

## Component, Query & Data

__Affected feature__: AQL query

__AQL query__:
FOR x IN OUTBOUND "" GRAPH "MyGraph" RETURN x

__Dataset__:
The dataset does not seem to matter. I can reproduce the crash with a simple graph of 3 nodes connected in a chain.

__Problem__:
The ArangoDB server crashes when the above query is run. The problem is that the start node is an empty string which, of course, is invalid but still shouldn't crash the server.

**Comment by jsteemann** [comment]
@jbw3: reproduced it in 3.5 with an empty graph. Doesn't seem to happen in 3.4.x.

**Comment by jsteemann** [comment]
Fixed via the above PRs. Fix is expected to land in 3.5.2.

**Comment by maxkernbach** [comment]
Hi @jbw3,

Version 3.5.3, which includes a fix for ths issue, has been released.

From the [Changelog](https://github.com/arangodb/arangodb/blob/660ff994dbfa994a18fe921481f591b878b51619/CHANGELOG#L149):

> 
> * Fixed issue #10158: Invalid Query Crashes ArangoDB.
> 
>   This fixes traversal queries that are run on a static empty start vertex
>   string.

Please find the latest release in the [download section](https://www.arangodb.com/download-major/).
