### ISSUE TITLE
Coodinators and DB-Servers crash by requests.

### ISSUE THREAD

**Issue by Fruchtgummi** [arangodb/arangodb#10160]
## My Environment

* __ArangoDB Version__:        3.5.0
* __Storage Engine__:            RocksDB
* __Deployment Mode__:       Cluster 
* __Deployment Strategy__:   Kubernetes 
* __Configuration__:             3x Cordinatoren, 3x DB Servers
* __Infrastructure__:               AWS (3x t3.medium nodes)

* __Disks in use__:        SSD 

## Component, Query & Data

__Affected feature__:
GO-Driver, GoLang

__Replication Factor & Number of Shards (Cluster only)__:
 min 2, max 5

The Coodinators and DB-Servers crash at querys whose request generates too much data. 
Pods are automatically recreated, of course.

Kubectl give me not information from pods whose stats Terminating is. I want to know what happens.

How can I debug this?

**Comment by OmarAyo** [comment]
Hi @Fruchtgummi 

It is hard to find logs without any external logging, hence implementing external logging will be helpful in this case

We can suggest elk/efk, but there are a lot of solutions - for small instances, it can be promtail + loki, for big k8s clusters it can be efk/elk stack

Best,

**Comment by OmarAyo** [comment]
Hi @Fruchtgummi,

I am sending this message to check if you had the chance to read my previous message

Best,

**Comment by OmarAyo** [comment]
Hi @Fruchtgummi 

We have not heard back from you recently, I am closing this ticket now - you can reopen it at any time by commenting

Best
