### ISSUE TITLE
Does ArangoDB have a  official  ArangoDB .NET Client ?

### ISSUE THREAD

**Issue by czs1993** [arangodb/arangodb#10202]
I didn't find ArangoDB. NET Client from the ArangoDB Home page, where the official ArangoDB . NET Client for development?

**Comment by maxkernbach** [comment]
Hi @czs1993,

We currently do not have an "official" ArangoDB driver for .NET ("official" here meaning a driver being maintained by ArangoDB the company).

There already is an open ticket https://github.com/arangodb/arangodb/issues/2992 that is requesting the support of it. Therefore I am closing this ticket as duplicate, please continue the discussion in the referenced ticket.

Thanks
