### ISSUE TITLE
FEAT REQUEST - Allow create database permission without _system permission

### ISSUE THREAD

**Issue by cboothe** [arangodb/arangodb#10214]
## My Environment

* __ArangoDB Version__:        3.4.8
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server

## Component, Query & Data

__Affected feature__:
Permissions

Add a Database * permissions with a read/write administrate option

I want to give a user permissions to create their own databases but not have system level access to create their own users or delete databases they don't own.

**Comment by dothebart** [comment]
Hi, you probably could do this via a foxx service. However, its not possible out of the box.

**Comment by dothebart** [comment]
Closing as solved; 

Please note that [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) is available.
