### ISSUE TITLE
ArangoDB AQL timeout error 2000 (Javascript error in arangosh.js)

### ISSUE THREAD

**Issue by gitman23** [arangodb/arangodb#10256]
## My Environment

* __ArangoDB Version__:   3.3.5.1     
* __Storage Engine__:         RocksDB 6.2.0    
* __Deployment Mode__:   Single Server    
* __Deployment Strategy__:  Manual Start 
* __Configuration__:      endpoint = tcp://0.0.0.0:8529         
* __Infrastructure__:     own          
* __Operating System__:   Ubuntu 18.04     
* __Total RAM in your machine__:    256Gb    
* __Disks in use__:   HDD     
* __Used Package__:   arangodb3_3.5.1-1_amd64.deb    community version        

## Component, Query & Data

__Affected feature__:
AQL via arangosh

__AQL query (if applicable)__:
LET alist = ( RETURN FLATTEN( FOR doc IN collectA RETURN doc.strA[\*\*].strB.address[\*\*] )) FOR adr IN alist[0] INSERT {\'_key\': adr, \'address\': adr} IN collectB OPTIONS { ignoreErrors: true, exclusive: true }

__AQL explain (if applicable)__:
I have a collection collectB with > 100M alphanumeric number entries and a few million are still missing. So I pull the data from another collection collectA and write it into collectB. The ignore error option is in order to cope with double entry errors (because most entries already exist)

__Dataset__:

__Size of your Dataset on disk__:

about 500GB

## Steps to reproduce

1. Run the provided AQL code on a collection with many alphanumeric entries
2. Wait for appr. 20 minutes (probably depending on server capacity?)

__Problem__:

Running the AQL in arangosh I end always after appr. 20 minutes in an ArangoError 2000 which should not occur according to the manual. Additionally arangodb isn't reacting for a while afterwards and my webmin isn't reachable until a new server start (coincidence?). I have a stable solution doing same with cursors and smaller batches but it would need months to finish so I hope to get it with this AQL approach like below managed much faster. May be there are too many connections and I can influence it with a configuration in arango or Ubuntu? Here the error message:

```
127.0.0.1:8529@mydatab> db._query('LET alist = ( RETURN FLATTEN( FOR doc IN collectA RETURN doc.strA[\*\*].strB.address[\*\*] )) FOR adr IN alist[0] INSERT {\'_key\': adr, \'address\': adr} IN collectB OPTIONS { ignoreErrors: true, exclusive: true } ')
JavaScript exception in file '/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js' at 99,7: ArangoError 2000: Request timeout
!      throw error;
!      ^
stacktrace: ArangoError: Request timeout
    at Object.exports.checkRequestResult (/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js:97:21)
    at ArangoStatement.execute (/usr/share/arangodb3/js/client/modules/@arangodb/arango-statement.js:172:12)
    at Proxy.ArangoDatabase._query (/usr/share/arangodb3/js/client/modules/@arangodb/arango-database.js:954:45)
    at <shell command>:1:4
```

__Expected result__:
query running until end

Appreciate help on the error or as well performance tips for me as AQL beginner. 
Thank you!

**Comment by graetzer** [comment]
perhaps rewrite the query first:
```js
FOR doc1 IN collectA 
  LET docs = FLATTEN(doc.strA[**].strB.address[**])
  FOR adr IN docs
    INSERT {'_key': adr, 'address': adr} IN collectB OPTIONS { ignoreErrors: true, exclusive: true }
```

Otherwise: The timeout is on the client so the query is probably still running. I would also suggest to set the *intermediateCommitCount* to 1000

See https://www.arangodb.com/docs/devel/aql/invocation-with-arangosh.html

**Comment by OmarAyo** [comment]
Hi @gitman23 

Did you have the chance to read graetzer's earilier message ?

Best

**Comment by OmarAyo** [comment]
Hi @gitman23 

We didn't hear back from you recently, I am going to close this ticket now

In case this issue persists, just comment and we will reopen it again

Best
