### ISSUE TITLE
Query: Expecting type Array or Object (while executing)

### ISSUE THREAD

**Issue by sh0umik** [arangodb/arangodb#10270]
## My Environment

* __ArangoDB Version__:        3.5.0
* __Storage Engine__:             RocksDB 
* __Deployment Mode__:        Single Server
* __Deployment Strategy__:   Manual Start in Docker 
* __Configuration__:               Docker default
* __Infrastructure__:               own 
* __Operating System__:        Ubuntu 18.04
* __Total RAM in your machine__:        4Gb
* __Disks in use__:        SSD
* __Used Package__:             Docker - official Docker library | other

## Component, Query & Data

__Affected feature__:
AQL query using web interface and with golang driver

__AQL query (if applicable)__:

```
let chat = DOCUMENT('chat', '12f34')
return MERGE(chat, { followers : (
	FOR follow in chat.followers
		LET user = DOCUMENT('user', follow.user.id)
		LET merged = MERGE(follow, {user: {
			id : user.id,
			name : user.name,
			picture : user.picture
		}})
		return merged
)})

```

__Dataset__:
https://gist.github.com/sh0umik/c0e5bc7cb6759e939bb6bd3b800c7169

__Size of your Dataset on disk__:
2-4 documents

__Replication Factor & Number of Shards (Cluster only)__:
None

## Steps to reproduce

1. The query works if the key is found in `chat` collection
2. If i change the key id OR if i enter an id which is not in the collection then i get the error 

__Problem__:

```
Query: Expecting type Array or Object (while executing) (exception location: /work/ArangoDB/arangod/RestHandler/RestCursorHandler.cpp:279). Please report this error to arangodb.com
C
```

__Expected result__:

null

**Comment by jsteemann** [comment]
It is not possible in AQL to iterate over a non-array using a `FOR` loop.

So actually the behavior (the query aborting is intended here), but the error message is not.
The error message should actually be "collection or array expected as operand to FOR loop; you provided a value of type ...", with error code 1563. It seems that due to some internal changes in 3.5 this error message got lost and the totally generic "internal error" was used.

The above PR fixes that for 3.5.2, so the old behavior will be back.
Still it will not be possible to iterate over a non-array using a `FOR` loop.

**Comment by sh0umik** [comment]
What is the solution here? for a valid/existing document the query works but if the document is not found then i should get null in return right. Because the query is valid!. 

Can you suggest any other way to achieve the exact result where i won't get error if key does not exists?

**Comment by jsteemann** [comment]
You could adjust the first two lines of the query as follows:
```
let doc = DOCUMENT('chat', '1234') 
let chat = doc ? doc : { followers: [] }
return MERGE(chat, { followers : (
	FOR follow in chat.followers
		LET user = DOCUMENT('user', follow.user.id)
		LET merged = MERGE(follow, {user: {
			id : user.id,
			name : user.name,
			picture : user.picture
		}})
		return merged
)})
```
This will work as long as each existing document in `chat` has a `followers` attribute which is an array. If not, then the query can be adjusted accordingly, e.g.
```
let doc = DOCUMENT('chat', '1234') 
let followers = doc.followers ? doc.followers : []
return MERGE(chat, { followers : (
	FOR follow in followers
		LET user = DOCUMENT('user', follow.user.id)
		LET merged = MERGE(follow, {user: {
			id : user.id,
			name : user.name,
			picture : user.picture
		}})
		return merged
)})
```

**Comment by sh0umik** [comment]
I tried your solution. The Type Error has gone but I am getting a warning..

My Query : 
```
let doc = DOCUMENT('chat', 'id-not-available') 
let followers = doc.followers ? doc.followers : []
return MERGE(doc, { followers : (
	FOR follow in followers
		LET user = DOCUMENT('user', follow.user.id)
		LET merged = MERGE(follow, {user: {
			id : user.id,
			name : user.name,
			picture : user.picture
		}})
		return merged
)})
```

Now I am getting this message 

```
Warnings:

[1542], 'invalid argument type in call to function 'MERGE()''

Result:

[
  null
]
```

**Comment by jsteemann** [comment]
You can avoid that by using something like `doc ? doc : {})`. Just use the ternary operator as required.

**Comment by maxkernbach** [comment]
Hi @sh0umik,

Version 3.5.3, which includes an improved error message output for the given query, has been released.
In case the suggested query modification did not help, please reply to the latest comment and we would be glad to investigate.

Please find the latest release in the [download section](https://www.arangodb.com/download-major/).
