### ISSUE TITLE
Raspberry Pi install problem

### ISSUE THREAD

**Issue by legikaloz** [arangodb/arangodb#1028]
I'm trying to install ArangoDB on a Raspberry Pi, and the following error occurs:
[....] Starting arango database server: arangod/usr/sbin/arangod: error while loading shared libraries: libicui18n.so.52: cannot open shared object file: No such file or directory
[FAIL] database version check failed, maybe need to run 'upgrade'? ... failed!
invoke-rc.d: initscript arangodb, action "start" failed.

Tried to install 2.1.2, 2.2.3 rc1, 2.2.3 too.
OS: Raspbian, fresh install + all update installed

**Comment by Kunal-Vyas** [comment]
Sorry, but what's the fix? I am seeing same issue on Jessie Lite

**Comment by dothebart** [comment]
did you try to compile yourselves? or did you try to install the arangodb packages?

**Comment by Kunal-Vyas** [comment]
I tried installing the Raspberry package available in the downloads, v2.7.3. I will try compiling later today when I get a chance.
