### ISSUE TITLE
Possible memory leak in foxx services (how to troubleshoot this?)

### ISSUE THREAD

**Issue by soualid** [arangodb/arangodb#10338]
Hello, we are using multiple ArangoDB instances (3.4.8 serie) in a master / slaves setup and our master is restarting every ~14 days because it becomes unresponsive. 

Systems graphs shows that the memory consumption is increasing until a plateau (with memory usage % depending on the `--rocksdb.block-cache-size` option value) on both masters and slaves. The slaves live like that for months without any problem, which seems to indicate that the memory is reallocated succesfully, but when it reaches this state, the master becomes unresponsive after 2 or 3 days, and is restarted by our cluster orchestrator  (actually apache mesos) because its healthcheck fails, causing a downtime time of ~30s during the process restart.

Since the exact same workloads are executed on both master and slaves, with the exception of Foxx services, I guess that there is a memory leak somewhere here, and I wonder how we could identify or workaround these.

Do you think `--javascript.v8-contexts-max-invocations` or `--javascript.v8-contexts-max-age` could help in freeing this memory?

Many thanks in advance!

**Comment by maxkernbach** [comment]
Hi @soualid,

Adjusting the settings `--javascript.v8-contexts-max-invocations` or `--javascript.v8-contexts-max-age` seems sensible, did you already give it a try?

**Comment by soualid** [comment]
Hello,

I just did, by setting `--javascript.v8-contexts-max-invocations 10` since the default value of `--javascript.v8-contexts-max-age` (60 seconds) seems valid for our workload. 

Actually, I think we never have a break of 60 seconds without any call to our master database, which makes me hope for better memory graphs on our master database by forcing garbage collection of V8 contexts every 10th invocations.

Since we do not have this problem on slave databases, the problem, which could be a memory leak, may be in foxx services or queues management since these are the only differences between master and slaves workload (same hardware, same datas, same read queries, same writes through asynchronous synchronisation).

I'll give you the result of this change in 5 to 7 days. Thanks!

**Comment by dothebart** [comment]
Hi, can you also track the isolates memory usage by polling 
https://www.arangodb.com/docs/stable/http/administration-and-monitoring.html?origin_team=T03HM2BGZ#statistics and storing these values to a file? (The swagger view in the webinterface (Support -> RestAPI -> Administration -> GET /_admin/statistics is a bit better in the visualisation) Interesting is `server->V8Context` - especialy the (not yet) documented `memory` array.

You shouldb maybe be able to see whether you have some aspects of the garbage collection not working for you.

**Comment by soualid** [comment]
Actually I just disabled statistics on our master with the hope that it may fix the leak we are experiencing but I will re enable it during the next restart. I'll update this ticket with the informations I'll gather there. Thanks!

**Comment by dothebart** [comment]
you don't have to. This call just gives you current now states, the V8 stats won't even be stored.

**Comment by soualid** [comment]
It seems that this endpoint is returning an error if statistics are disabled with startup options, even for those which are not stored, but I'll definitely have a closer looks on these stats as soon as I have a window to re-enable the stats on this master database.

Thanks!

```
curl -X GET "https://xxx.xxx.xxx/_db/xxx/_admin/statistics" -H  "accept: application/json" -H  "Authorization: bearer xxx" --silent | jq
{
  "error": true,
  "errorMessage": "statistics not enabled",
  "code": 404,
  "errorNum": 36
}
```

**Comment by jsteemann** [comment]
For info, from 3.4.9 and 3.5.1 onwards we have a startup option `--server.statistics-history` can be used to turn off storing the statistics in the database, even when `--server.statistics` is enabled. So this will allow to access the statistics API but not pay the price for storing the statistics in the database.
That doesn't help for the version you are currently using, but it may be an option in the future.

**Comment by soualid** [comment]
Quick update: usage of `--javascript.v8-contexts-max-invocations` seems to have solved the issue: the arangod process is using all its allocated memory for 2 days now without performance impact nor crash. But we'll be totally sure of that after a few more days in production. I'll close this ticket then. Many thanks for your insights.

**Comment by dothebart** [comment]
Ok, thanks. You're not using foxx Queues, right? 
can you share any insights, whether `globals` has remaining entries of values which are not garbage collected?

**Comment by soualid** [comment]
We are using foxx queues a lot. 🙂 

What do you mean by `globals`? It doesn't seem to be something returned by the `statistics` endpoint, how could I get this information? 

Again, it seems that `--javascript.v8-contexts-max-invocations` seems to fix our initial problem, since our master database is totally stable at its cap memory level for a few days now, I will be able to confirm this in something like a week (ie. if the master is stable for more than ~10 days after these change, it will definitely mean that the problem is solved by forcing the garbage collections of v8 contexts).

Anyway, if it has any value, here are the actual values returned by the `statistics` endpoint on this database:

```
{
  "time": 1574344881.1003783,
  "enabled": true,
  "system": {
    "minorPageFaults": 380155324,
    "majorPageFaults": 0,
    "userTime": 177917.77,
    "systemTime": 210535.9,
    "numberOfThreads": 104,
    "residentSize": 48267272192,
    "residentSizePercent": 0.05958964204764984,
    "virtualSize": 151137415168
  },
  "client": {
    "httpConnections": 21,
    "connectionTime": {
      "sum": 0,
      "count": 0,
      "counts": [
        0,
        0,
        0,
        0
      ]
    },
    "totalTime": {
      "sum": 292405.9495520592,
      "count": 3744400,
      "counts": [
        394149,
        2086501,
        1063931,
        80243,
        45082,
        3970,
        70524
      ]
    },
    "requestTime": {
      "sum": 279680.92700219154,
      "count": 3744400,
      "counts": [
        655589,
        1849117,
        1041339,
        85137,
        39031,
        3677,
        70510
      ]
    },
    "queueTime": {
      "sum": 0,
      "count": 0,
      "counts": [
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    },
    "ioTime": {
      "sum": 12725.02254986763,
      "count": 3744400,
      "counts": [
        3439764,
        303087,
        1462,
        70,
        16,
        1,
        0
      ]
    },
    "bytesSent": {
      "sum": 36156388319,
      "count": 3744400,
      "counts": [
        73674,
        1432046,
        451466,
        739353,
        441729,
        606132
      ]
    },
    "bytesReceived": {
      "sum": 1672078431,
      "count": 3744400,
      "counts": [
        714596,
        2902660,
        119377,
        6001,
        765,
        1001
      ]
    }
  },
  "http": {
    "requestsTotal": 3744528,
    "requestsAsync": 13,
    "requestsGet": 949200,
    "requestsHead": 1,
    "requestsPost": 459962,
    "requestsPut": 2335362,
    "requestsPatch": 3,
    "requestsDelete": 0,
    "requestsOptions": 0,
    "requestsOther": 0
  },
  "server": {
    "uptime": 168481.24362969398,
    "physicalMemory": 809994330112,
    "v8Context": {
      "available": 8,
      "busy": 3,
      "dirty": 0,
      "free": 5,
      "max": 144,
      "memory": [
        {
          "contextId": 0,
          "tMax": 1574344869.247152,
          "countOfTimes": 2,
          "heapMax": 31472720,
          "heapMin": 29920896
        },
        {
          "contextId": 3658,
          "tMax": 1574344873.5856442,
          "countOfTimes": 1,
          "heapMax": 57966424,
          "heapMin": 56945888
        },
        {
          "contextId": 3662,
          "tMax": 1574344858.6992137,
          "countOfTimes": 0,
          "heapMax": 62401424,
          "heapMin": 51567288
        },
        {
          "contextId": 3663,
          "tMax": 1574344858.8641644,
          "countOfTimes": 10,
          "heapMax": 31498216,
          "heapMin": 0
        },
        {
          "contextId": 3666,
          "tMax": 1574344858.8665195,
          "countOfTimes": 14,
          "heapMax": 35439112,
          "heapMin": 0
        },
        {
          "contextId": 3667,
          "tMax": 1574344858.8686037,
          "countOfTimes": 14,
          "heapMax": 39266480,
          "heapMin": 0
        },
        {
          "contextId": 3664,
          "tMax": 1574344858.880338,
          "countOfTimes": 10,
          "heapMax": 31761064,
          "heapMin": 0
        },
        {
          "contextId": 3665,
          "tMax": 1574344858.8681386,
          "countOfTimes": 10,
          "heapMax": 31772328,
          "heapMin": 0
        }
      ]
    },
    "threads": {
      "scheduler-threads": 14,
      "in-progress": 11,
      "queued": 11,
      "current-fifo1": 0,
      "fifo1-size": 1048576,
      "current-fifo2": 0,
      "fifo2-size": 4096,
      "current-fifo3": 0,
      "fifo3-size": 4096
    }
  },
  "error": false,
  "code": 200
}
```

I'll update this ticket in a few days, with, I hope, the confirmation of these good news!

**Comment by soualid** [comment]
It's now 15 days since the last restart triggered by an OOM, I am happy to confirm that `--javascript.v8-contexts-max-invocations` was the last tuning we needed to obtain a super stable master databases! Thanks and keep up the good work, you're doing amazingly great!
