### ISSUE TITLE
Aardvark: If arangod crashes during a query, UI hangs forever

### ISSUE THREAD

**Issue by CoDEmanX** [arangodb/arangodb#1035]
I queried a single document with a lot of nested data and arangod.exe crashed (insufficient RAM?!).

The query was submitted from the AQL editor in the web interface, which then awaited a callback - but never got anything back. In this state, the entire interface is locked and can't be used (I wanted to copy the query I wrote to clipboard but couldn't interact with the UI at all).

The web interface should be fault tolerant and not just hang up. Maybe WebWorkers can help.

**Comment by hkernbach** [comment]
You have a progress window for requests to the server now. If the server should crash, you simply can close the progress window and continue interacting with the interface.
