### ISSUE TITLE
Ctrl + C closes Arango Shell

### ISSUE THREAD

**Issue by CoDEmanX** [arangodb/arangodb#1036]
While tinkering with arangosh, I realized that if I try to abort a command with <kbd>Ctrl</kbd><kbd>C</kbd>, it simply shuts down the shell.

I expected it to only stop the current query / result printing (which can last long if your documents contain thousands of nested properties) and continue with REPL, so that I can go back to my previous command and alter them.

I also tried <kbd>Esc</kbd>, but it doesn't do anything.

My suggestion: make <kbd>Ctrl</kbd><kbd>C</kbd> abort the current action, but not close arangosh. If necessary, bind <kbd>Esc</kbd> instead to kill the shell immediately.

**Comment by pluma** [comment]
This seems to have been fixed in devel.

**Comment by bubnenkoff** [comment]
In 2.6 or 2.7 branch?

**Comment by dothebart** [comment]
its going to become available in 2.7

**Comment by jsteemann** [comment]
Closing because available since 2.7.

**Comment by CoDEmanX** [comment]
Hm, Ctrl+C sends ^C but also shuts down arangosh immediately (still). Ctrl+D just terminates it. Custom devel build of today.

> arangosh [_system]> ^C
> Uf wiederluege! Na shledanou! Auf Wiedersehen! Bye Bye! Adiau! ¡Hasta luego! Au
>revoir!
>
>Arrivederci! ???????! Tot ziens! Adjö! ??? t? epa??de??! ????? ?? ????????! Até
>Breve!
> arangosh [_system]>

**Comment by jsteemann** [comment]
CTRL+C will close the shell immediately if no command is running.
When pressing CTRL+C while a command is running, it will terminate the command first:
```
arangosh [_system]> while (1);
^Ccommand locally aborted

arangosh [_system]> 
```
However, the above behavior was only implemented for Linux and MacOS. For Windows, there was no signal handler in place, so CTRL-C just terminated the ArangoShell. I fixed that just now.

**Comment by CoDEmanX** [comment]
Thanks, it works with your example. It can't be used to abort a query (or at least the waiting for a result) however, it will wait for the query to complete before it "aborts".

**Comment by jsteemann** [comment]
It can only send a "kill" instruction to the V8 context. If that V8 context is executing some non-V8 code (via C++ bindings), then the "kill" will have an effect only when the non-V8 code returns control to V8.
In case a query was started from the ArangoShell, the execution likely waits inside a `select()` (Windows) or `poll()` (other OSes) system call, which will not care about CTRL-C being pressed. 

A potential fix for this would be poll/select only for shorter periods, and periodically check for an abort. This would not abort the server-side query however, just the client. To abort the server-side query, we would need to send an extra "kill query" request to the server (and in addition need to know the currently executing query's id, which we don't have present.
Alternatively, we would make the shell sends an asynchronous request to the server, and perdiodically check for server-side completion of the operation. This however will make all operations that currently issue one HTTP request require at least two HTTP request, so I dislike it.
