### ISSUE TITLE
Upsert throws 404 Not Found

### ISSUE THREAD

**Issue by darkfrog26** [arangodb/arangodb#10367]
## My Environment

* __ArangoDB Version__:        3.5.1
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Ubuntu service
* __Operating System__:        Ubuntu 18.04
* __Total RAM in your machine__:        128GB
* __Disks in use__:        SSD
* __Used Package__:              Ubuntu .deb

## Component, Query & Data

__Affected feature__: AQL

## Steps to reproduce

Here is my exact request / response log:

```
Path: /_db/courio/_api/document/linkPreviews?silent=false&waitForSync=false&returnNew=false&returnOld=false&overwrite=true (Method: POST, Status: HttpResponseStatus(404: Not Found)),
Request: {
  "_key" : "edXADfd3985u4DWCD7hUc4vx4rxO6UxO",
  "url" : "https://docs.google.com/presentation/d/17nFIwCyf2Kz-Ao5HGnmvNZ74L8eSKA2C2Qdaoe-47OM/edit?usp=sharing",
  "title" : "https://docs.google.com/presentation/d/17nFIwCyf2Kz-Ao5HGnmvNZ74L8eSKA2C2Qdaoe-47OM/edit?usp=sharing",
  "created" : 1572718316556,
  "modified" : 1572718316556,
  "_id" : "linkPreviews/edXADfd3985u4DWCD7hUc4vx4rxO6UxO"
}
Response: {"code":404,"error":true,"errorMessage":"document not found","errorNum":1202}
```
__Problem__:
This seems to occur related to concurrency when upserting multiple records to the same collection at the same time.  In the example above (which has happened multiple times across multiple collections, but inconsistently), I'm running a reprocessing operation that is running against thousands of messages in 8 concurrent threads. After this error I checked the database and that `id` does not exist in the database.

For more discussion on this specific issue, see the conversation on Slack: https://arangodb-community.slack.com/archives/C1R1A2TFC/p1572721011011100

__Expected result__: Successful upsert

**Comment by darkfrog26** [comment]
Here's the index information:
![Screenshot from 2019-11-05 08-36-17](https://user-images.githubusercontent.com/877534/68216959-69227d00-ffa7-11e9-8b1c-55d7c89d4c1d.png)

**Comment by darkfrog26** [comment]
Almost two months have passed and I haven't really seen any activity on this.  I still see this occur from time to time but most recently it's been `412` error instead:

> Error while attempting to save session (URL: https://da3c99e1bfb4.arangodb.cloud:8529/_db/courio/_api/document/sessions?silent=false&waitForSync=false&returnNew=false&returnOld=false&overwrite=true (Method: POST, Status: HttpResponseStatus(412: Precondition Failed)),
> Request: {
> "_key" : "B7wnqCoB284YpwJN1aHrS0bSSZPmkLTY",
> "_id" : "sessions/B7wnqCoB284YpwJN1aHrS0bSSZPmkLTY",
> "userId" : "users/AknwpKpT8BYyeBcvZbo0GI6XDkyPEhQt",
> "aliasId" : "aliases/I5qZllXgchIJpKWPCuBBYxoeJFf739dd",
> "created" : 1577978477520,
> "modified" : 1577978477520
> },
> Response: {"error":true,"code":412,"errorNum":1200,"errorMessage":"precondition failed","_id":"sessions/unknown","_key":"unknown","_rev":"0"}

**Comment by graetzer** [comment]
Are you sureIt doesn’t occur due to concurrently using the same document ? 
Maybe try locking the collection exclusively? There is a new option called `—rocksdb.exclusive-writes` to get thebserialized behaviour

**Comment by darkfrog26** [comment]
@graetzer, well, it seems as though this only occurs when the upsert doesn't already have the document and has to create it.  It's possible that more than one request is attempting to get it at the same time though. I'll look into the exclusive writes to see if that helps.

**Comment by dothebart** [comment]
Hi, 
@darkfrog26 did you succeed with @graetzer s sugestion? Can we close this?

**Comment by darkfrog26** [comment]
I refactored the code and I haven't seen it appear again. Go ahead and close this and I'll open another ticket if I see this again.

**Comment by dothebart** [comment]
attaching i.e. a pcap of the incident could probably help. Thanks.
