### ISSUE TITLE
exception while inserting document into arangosearch

### ISSUE THREAD

**Issue by ablbi** [arangodb/arangodb#10375]
we have a collection for simple document (4-5 String properties) but with millions of entries. A View is defined for the collection analyzing the property "name". While importing entries for the collection through java client API we sometimes get the exception:

```
com.arangodb.ArangoDBException: Response: 500, Error: 4 - caught exception while inserting document into arangosearch link '250453995', revision '1647443475199688705': Failed to create file, path: _27789.cs
```

name of the .cs file changes with each exception. File is not created, document is not inserted. This is not regularly and not reproducable with the same document. For example with 10 mio inserts I get this error about 250 times for different documents.

## View definition
```json
{
  "cleanupIntervalStep": 2,
  "commitIntervalMsec": 1000,
  "consolidationIntervalMsec": 10000,
  "globallyUniqueId": "h52CB42EAE71E/59472846",
  "links": {
    "SupplierObj": {
      "analyzers": [
        "identity"
      ],
      "fields": {
        "name": {
          "analyzers": [
            "text_de"
          ]
        }
      },
      "includeAllFields": true,
      "storeValues": "id",
      "trackListPositions": false
    }
  },
  "consolidationPolicy": {
    "type": "tier",
    "segmentsBytesFloor": 2097152,
    "segmentsBytesMax": 5368709120,
    "segmentsMax": 10,
    "segmentsMin": 1,
    "minScore": 0
  },
  "id": "59472846",
  "primarySort": [],
  "type": "arangosearch",
  "writebufferActive": 0,
  "writebufferIdle": 64,
  "writebufferSizeMax": 33554432
}
```

## My Environment

* __ArangoDB Version__:        3.5.1
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Windows service
* __Configuration__:               default
* __Infrastructure__:               Windows x64
* __Operating System__:        Windows Server 2016 Datacenter
* __Total RAM in your machine__:        32Gb
* __Disks in use__:        SSDs
* __Used Package__:              Windows Zip package

## Component, Query & Data

__Dataset__:
{
  "supplierKey": "ARANGO_SUPPLIER",
  "supplierArticle": "3768",
  "articleKey": 979999999,
  "name": "Arango",
  "type": "main",
}

**Comment by OmarAyo** [comment]
Hi @ablbi 

Would you attach the followings:
- the arangod logs 
- an example of how you are importing such documents 

Best,

**Comment by ablbi** [comment]
I rerun the test and stopped with the first exception. arangod.log attached
[arangod.log](https://github.com/arangodb/arangodb/files/3821710/arangod.log)

Code for importing is wrapped by some kind of entity framework to model our business objects, but at the end all goes through:
```java
	private void insertOrUpdate(BaseDocument document, Map<String, Object> data)
	{
		document.getProperties().putAll( data);
		ArangoCollection c = collection();
		if( document.getId() == null)
			c.insertDocument( document);
		else
			c.updateDocument( document.getKey(), document);
	}
```

**Comment by dothebart** [comment]
Hi, 
the view is just there for working with ready existing documents. 
You have to write the documents into the respective collections that you created the view upon. 
Sorry for the late reply; Please note that [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/)
