### ISSUE TITLE
Can not connect typescript with arangodb

### ISSUE THREAD

**Issue by DardanHaliti** [arangodb/arangodb#10406]
## My Environment

* __ArangoDB Version__:        3.5.2(the latest i think)
* __Storage Engine__:             
* __Deployment Mode__:       Single Server 
* __Deployment Strategy__:   Docker
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:        Ubuntu 18.04 
* __Total RAM in your machine__:        8GB
* __Disks in use__:        256GB
* __Used Package__:              

__Problem__:
I haveused:
```
docker pull arangodb
docker run -e ARANGO_ROOT_PASSWORD=root -p 8529:8529 -d arangodb
```
Now arango is running and i can access the web interface from 0.0.0.0:8529 and 127.0.0.1:8529,
I have the following code  in typescript:
```
import {Database} from "arangojs";
let db = new Database({
  url:"http://0.0.0.0:8529",//127.0.0.1:8529
  loadBalancingStrategy:"NONE" 
})
db.useBasicAuth('root', 'root');	

db.useDatabase('DBPIT');
db.createDatabase('DBPIT');
```
the Error message is:
```
UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:8529
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
(node:25) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

```
For both cases I have the same error using localhost:8529 or 0.0.0.0:8529
__Expected result__:
To work the connection...

**Comment by DardanHaliti** [comment]
Hi. Do i need to have arangodb preinstalled or is the docker image enough?

**Comment by maxkernbach** [comment]
Hi @DardanHaliti,

I was not able to reproduce this issue. The error `connect ECONNREFUSED 127.0.0.1:8529
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)` only occurs when there is no ArangoDB instance running on the specified port. Using the same docker command and connection script you provided, I was able to connect to the ArangoDB instance and create a database. Are you executing the typescript code from the same machine where your docker instance is running?

In addition, I noticed that you are using `db.createDatabase('DBPIT');` after `db.useDatabase('DBPIT');`. This seems to be a typo.

**Comment by DardanHaliti** [comment]
> Hi @DardanHaliti,
> 
> I was not able to reproduce this issue. The error `connect ECONNREFUSED 127.0.0.1:8529 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)` only occurs when there is no ArangoDB instance running on the specified port. Using the same docker command and connection script you provided, I was able to connect to the ArangoDB instance and create a database. Are you executing the typescript code from the same machine where your docker instance is running?
> 
> In addition, I noticed that you are using `db.createDatabase('DBPIT');` after `db.useDatabase('DBPIT');`. This seems to be a typo.

```
CONTAINER ID        IMAGE                                                              COMMAND                   CREATED             STATUS              PORTS                                      NAMES
c4f4024f5041        arangodb                                                           "/entrypoint.sh aran…"    24 minutes ago      Up 24 minutes       0.0.0.0:8529->8529/tcp                     busy_moser
aa57b0d696cb        arangodb                                                           "/entrypoint.sh aran…"    24 minutes ago      Up 24 minutes       8529/tcp                                   arangodb-instance
```
Those are the arangodb container in docker but i dont know what is the problem...
*I saw the typo and i removed it but still. How to make sure that `only occurs when there is no ArangoDB instance running on the specified port.` is running on the  specific port?
`Are you executing the typescript code from the same machine where your docker instance is running?` - Yes on the same machine.

**Comment by dothebart** [comment]
`0.0.0.0` is the broadcast bind ip. 
You have to use the actual IP of your machine or the loopback address if you're on the same machine.
