### ISSUE TITLE
Docs for some Foxx controller features

### ISSUE THREAD

**Issue by myguidingstar** [arangodb/arangodb#1040]
I see this in Changlog for 2.2.3

> * added `around` for Foxx controller

but can't find the doc for that anywhere

Also, I can't find doc for the `next` argument which is used in https://github.com/triAGENS/ArangoDB/blob/master/js/server/modules/org/arangodb/foxx/format_middleware.js#L39

**Comment by razvanphp** [comment]
I found other 2 (summary and notes):
https://github.com/arangodb/arango-cms/blob/master/cms.js#L29

**Comment by moonglum** [comment]
summary and notes are internal :smile:

**Comment by pluma** [comment]
@moonglum is it? The docs mention the auto-magical summary comments, though. See https://docs.arangodb.com/Foxx/Develop/Controller.html
