### ISSUE TITLE
when update edge vertex, error:AQL: Error message received from cluster node 'PRMR-ce3b3175-19b0-4f7f-a175-563bdec55076': edge attribute missing or invalid (while executing)

### ISSUE THREAD

**Issue by Thebigwind** [arangodb/arangodb#10445]
```
LET oldid = (FOR m IN `metas` FILTER m.key == "lu-8" AND m.value == "" AND m.uid == 0 RETURN m._id)   
FOR m IN `metas` FILTER m.key == "lu" AND m.value == "" AND m.uid == 0   
  FOR n IN  `vol3-reverse-file-metamap` FILTER n._from IN oldid    
     UPDATE n WITH {_from:m._from, vertex:m._key} IN `vol3-reverse-file-metamap`
//Query: AQL: Error message received from cluster node 'PRMR-ce3b3175-19b0-4f7f-a175-563bdec55076': edge attribute missing or invalid (while executing)
```

**Comment by jsteemann** [comment]
When updating an edge, any data in the `_from` or `_to` attributes must be syntactically valid. That means these attributes must be strings consisting of the collection name, a forward slash, plus the document key (e.g. `testcollection/testkey1234`).

I can't see from the above query what data is contained in `m._from` when the query is run, but I guess that for a least one document in `metas` there is either no `_from` attribute or it does not conform to the above-mentioned requirements.

**Comment by Thebigwind** [comment]
> When updating an edge, any data in the `_from` or `_to` attributes must be syntactically valid. That means these attributes must be strings consisting of the collection name, a forward slash, plus the document key (e.g. `testcollection/testkey1234`).
> 
> I can't see from the above query what data is contained in `m._from` when the query is run, but I guess that for a least one document in `metas` there is either no `_from` attribute or it does not conform to the above-mentioned requirements.

the detail is here:
`/*
 aql: FOR m IN `metas` FILTER m.key == "lu-8" AND m.value == "" AND m.uid == 0 RETURN m._id
result: 
[
  "metas/536205335"
]

aql:FOR m IN `metas` FILTER m.key == "lu" AND m.value == "" AND m.uid == 0 return m
result:
[
  {
    "_key": "536201520",
    "_id": "metas/536201520",
    "_rev": "_ZkxYZI6---",
    "black_list": [],
    "ctime": 1573784284,
    "key": "lu",
    "mode": 2,
    "uid": 0,
    "value": "",
    "white_list": []
  }
]

aql: FOR n IN  `vol3-reverse-file-metamap` FILTER n._from == "metas/536205335" return n  //the IN oldid 
result:
[
  {
    "_key": "536205838",
    "_id": "vol3-reverse-file-metamap/536205838",
    "_from": "metas/536205335",
    "_to": "vol3-files/11110000-0000-0000-0000-000000039233",
    "_rev": "_Zk2c3zu---",
    "ctime": 1573805549,
    "vertex": "536205335"
  }
]

now need update _from -> "metas/536201520" , vertex -> 536201520 
*/
`
I will  try to use insert and remove to replace.


LET oldid = (FOR m IN `metas` FILTER m.key == "lu-8" AND m.value == "" AND m.uid == 0 RETURN m._id)   
FOR m IN `metas` FILTER m.key == "lu" AND m.value == "" AND m.uid == 0   
  FOR n IN  `vol3-reverse-file-metamap` FILTER n._from IN oldid    
     UPDATE n WITH {_from:m._id, vertex:m._key} IN `vol3-reverse-file-metamap`

query: AQL: Error message received from cluster node 'PRMR-ce3b3175-19b0-4f7f-a175-563bdec55076': must not change the value of a shard key attribute (while executing)
```
I will try to use insert and remove to replace update,  it return success, like this.
`db._query('LET oldid = (FOR m IN `metas` FILTER m.key == "lu-8" AND m.value == "" AND m.uid == 0 RETURN m._id)   
FOR m IN `metas` FILTER m.key == "lu" AND m.value == "" AND m.uid == 0   
  FOR n IN  `vol3-reverse-file-metamap` FILTER n._from IN oldid    
     INSERT {_from:m._id, _to:n._to, vertex:m._key} INTO `vol3-reverse-file-metamap`
')


db._query('LET oldid = (FOR m IN `metas` FILTER m.key == "lu-8" AND m.value == "" AND m.uid == 0 RETURN m._id)   
FOR m IN `metas` FILTER m.key == "lu" AND m.value == "" AND m.uid == 0   
  FOR n IN  `vol3-reverse-file-metamap` FILTER n._from IN oldid    
     REMOVE n IN `vol3-reverse-file-metamap`')`

**Comment by jsteemann** [comment]
I think the problem is that in the original query

> FOR m IN metas FILTER m.key == "lu" AND m.value == "" AND m.uid == 0
> FOR n IN vol3-reverse-file-metamap FILTER n._from IN oldid
> UPDATE n WITH {_from:m._from, vertex:m._key} IN vol3-reverse-file-metamap

you are trying to write the value of `m._from` into the `_from` attribute value of the edge collection.
But that particular document does not seem to have a `_from` attribute:
```
{
  "_key": "536201520",
  "_id": "metas/536201520",
  "_rev": "_ZkxYZI6---",
  "black_list": [],
  "ctime": 1573784284,
  "key": "lu",
  "mode": 2,
  "uid": 0,
  "value": "",
  "white_list": []
}
```
That means the original error seems justified.

Now regarding to the next error:

> query: AQL: Error message received from cluster node 'PRMR-ce3b3175-19b0-4f7f-a175-563bdec55076': must not change the value of a shard key attribute (while executing)

I can't see by what attribute(s) the edge collection is sharded, but updating the values of any shard key attribute with a different value is disallowed in ArangoDB. That means either the sharding has to be adjusted or the shard key attributes must not be updated.

Or, as you seem to have tried yourself, removing the existing edges and reinserting them with different shard key values should also work.

**Comment by Thebigwind** [comment]
> I can't see by what attribute(s) the edge collection is sharded, but updating the values of any shard key attribute with a different value is disallowed in ArangoDB. That means either the sharding has to be adjusted or the shard key attributes must not be updated.
> 
> Or, as you seem to have tried yourself, removing the existing edges and reinserting them with different shard key values should also work.

thanks

**Comment by OmarAyo** [comment]
Hi @Thebigwind 

I am sending this message to check if we are al set with this ticket - is there anything related you want to discuss ?

**Comment by OmarAyo** [comment]
Hi @Thebigwind 

We haven't heard back from you recently, therefore I am going to close this ticket now

Feel free to reopen it by adding a comment

Best,
