### ISSUE TITLE
Charging problem

### ISSUE THREAD

**Issue by ITBOX-ITBOY** [arangodb/arangodb#10455]
Our arangodb, if I use it in business, will I charge

**Comment by dothebart** [comment]
Hi, 
ArangoDB Community edition comes free of charge. Depending on your business needs, you may want to consider one of our Subscriptions.

A comparison of Community and Enterprise and the different subscriptions can be found here:
https://www.arangodb.com/subscriptions/

**Comment by OmarAyo** [comment]
Hi @ITBOX-ITBOY 

Did you find dothebart's message useful ?

Best,

**Comment by ITBOX-ITBOY** [comment]
It works for me

**Comment by ITBOX-ITBOY** [comment]
@OmarAyo It works for me
