### ISSUE TITLE
execute selection only in ui

### ISSUE THREAD

**Issue by basaran** [arangodb/arangodb#10451]
## My Environment

* __ArangoDB Version__:        3.5.2
* __Storage Engine__:              RocksDB
* __Deployment Mode__:       Single Server
* __Operating System__:        5.3.6-1-MANJARO
* __Total RAM in your machine__:        8GB
* __Disks in use__:        SSD
* __Used Package__:              Aur

## Component, Query & Data

__Problem__:
When building, testing, mocking queries in the UI, there is no way to execute parts of AQL.

__Expected result__:
It will be helpful while building queries if command + enter looks for a selection/highlight of AQL in the editor pane before executing the entire region.

**Comment by OmarAyo** [comment]
@hkernbach FYI

**Comment by Simran-B** [comment]
It is already possible to execute just the selected text in the Query Editor with `Ctrl/Cmd`+`Alt`+`Enter`

![image](https://user-images.githubusercontent.com/7819991/74933923-65472900-53e5-11ea-9c28-597c1c123540.png)

**Comment by maxkernbach** [comment]
Hi @basaran,

did you have a chance to check Simran's previous reply?
As explained, it is already possible to execute just the selected text in the Query Editor with Ctrl/Cmd+Alt+Enter.

**Comment by hkernbach** [comment]
Also if you click here: 
![image](https://user-images.githubusercontent.com/1244163/76428031-6dbfcd80-63ad-11ea-9f28-db90ab2b4afa.png)
(left-bottom area of the Web UI)

You're getting a list of all supported shortcuts. 
![image](https://user-images.githubusercontent.com/1244163/76428078-7fa17080-63ad-11ea-8582-8d6b428a9bc5.png)

**Comment by Simran-B** [comment]
Added the missing shortcuts to the docs and converted from list to table:
https://deploy-preview-368--zealous-morse-14392b.netlify.com/docs/3.6/programs-web-interface-aql-editor.html#aql-editor-shortcuts
