### ISSUE TITLE
Insert request stuck for more than 15 minutes

### ISSUE THREAD

**Issue by nkanand4** [arangodb/arangodb#10463]
## My Environment

* __ArangoDB Version__:        3.3.3
* __Storage Engine__:             mmfiles
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   systemd start
* __Configuration__:               mmfiles, Linux version 4.15.0-1051-aws (buildd@lgw01-amd64-005) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) #53-Ubuntu SMP, ArangoDB 3.3.3 [linux] 64bit, using jemalloc, VPack 0.1.30, RocksDB 5.6.0, ICU 58.1, V8 5.7.492.77, OpenSSL 1.0.1 14 Mar 2012
* __Infrastructure__:               AWS
* __Operating System__:        Ubuntu 18.04
* __Total RAM in your machine__:        4.0GiB
* __Disks in use__:        50GB SSD
* __Used Package__:              Debian or Ubuntu .deb

## Component, Query & Data

__Affected feature__:
with arangojs driver

__AQL query (if applicable)__:
'INSERT @row INTO inventory RETURN NEW', bind vars: {"row":{"_from":"warehouses/2550626","_to":"customer_products/4660815","inventoryDate":1573952781992}}

__AQL explain (if applicable)__:
N/A

__Dataset__:
{"_from":"warehouses/2550626","_to":"customer_products/4660815","inventoryDate":1573952781992}

__Size of your Dataset on disk__:
1700 edges

__Replication Factor & Number of Shards (Cluster only)__:
Single instance only

## Steps to reproduce

1. Multiple insert requests to the same collection were in progress.
2. It goes back to normal after sometime.
3. Totally random when this issue arises.

__Problem__:
Some of the single row insert queries are taking as long as 15 minutes or more.

__Expected result__:
The query should fails within a shorter time duration.
<img width="1270" alt="Screen Shot 2019-11-18 at 7 50 04 AM" src="https://user-images.githubusercontent.com/667996/69067549-18b01400-09d8-11ea-923a-a00c86af3547.png">
<img width="1270" alt="Screen Shot 2019-11-18 at 7 49 25 AM" src="https://user-images.githubusercontent.com/667996/69067551-18b01400-09d8-11ea-9e53-5a7a041b80ac.png">

**Comment by dothebart** [comment]
Hi, 
with MMFiles you've got a write lock on collections, so the performance on inserts boils down to the maximum throughput of your disk. 

See this blogpost series on how to measure and tune the throughput of your system:
https://www.arangodb.com/2017/10/performance-analysis-pyarango-usage-scenarios/

**Comment by nkanand4** [comment]
Are you suggesting the disk was stuck for 15 minutes? Is there a way to have a circuit breaker in the driver configuration, so that I can handle it from single place.

**Comment by dothebart** [comment]
you can get in a situation, where reads block writes for a longer time. You should tune your throughput. More memory may help (caching), but if you outdo your disk i/o you end up being blocked. NB, 3.3.24 is out since  2019-08 - please upgrade first.

**Comment by nkanand4** [comment]
Unfortunately, I had run into more frequent deadlocks on 3.3.16 and 3.3.21 and made the decision to rollback to 3.3.3, which had been more stable for past 2 years in production.

**Comment by dothebart** [comment]
Ok, 
so my recommendation remains. Do load tests as I advised above. find KPIs for 3.3.3 and the later versions, find out whats the bottleneck. 
I won't be able to help you with a hopelessly outdated version.

**Comment by OmarAyo** [comment]
Hi @nkanand4,

Did you find the bottleneck as dothebart was suggesting ?

We strongly suggest you upgrade to our latest ArangoDB Versions as 3.3 is going to be declared EOL soon - see here: https://www.arangodb.com/eol-notice/

Best,

**Comment by OmarAyo** [comment]
Hi @nkanand4,

We haven't heard back from you recently, therefore I am closing this ticket now

Feel free to reopen it at any time

Best,
