### ISSUE TITLE
Ghosts Node

### ISSUE THREAD

**Issue by citarf** [arangodb/arangodb#10487]
## My Environment

* __ArangoDB Version__:     3.5.1   
* __Storage Engine__:        RocksDB     
* __Deployment Mode__:     Cluster  
* __Deployment Strategy__:  Manual Start 
* __Configuration__:               
* __Infrastructure__:       own        
* __Operating System__:    Debian 9    
* __Total RAM in your machine__:    16Gb * 6    
* __Disks in use__:    1To * 6    
* __Used Package__:       .deb       

__Problem__: I have an issue with 2 ghosts node dbserver. I can't delete them with the API or with the web UI. 
I tried to follow instructions in the documentation with Coordinator shutdown ...
The ghosts nodes are a duplicate version of up dbserver. We can see below two dbserver on the same machine. 

![image](https://user-images.githubusercontent.com/8773429/69247370-9a579b80-0baa-11ea-95ef-0a7473c5fefa.png)

**Comment by citarf** [comment]
any solution for remove this ghosts nodes without erase cluster ?

**Comment by Simran-B** [comment]
You can try https://github.com/arangodb/debug-scripts and post the `analyze` result here. It might give some more insight into the issue.

**Comment by maxkernbach** [comment]
Hi @citarf,

Did you have a chance to run the debug-script with task `analyze` as suggested?
This will most likely detect the ghost nodes and suggest to run the cleanup task `remove-dead-primaries` in order to remove those.

**Comment by OmarAyo** [comment]
Hi @citarf 

We haven't heard back from you recently, I am closing this ticket now.
Feel free to reopen it at any time by adding an new comment
Best,
