### ISSUE TITLE
Docs: EPUB contains many blank pages

### ISSUE THREAD

**Issue by CoDEmanX** [arangodb/arangodb#1049]
I downloaded the EPUB docs to use them on my smartphone or ebook reader and wondered why it loads so slow. Then I realized that all sections start with a blank page, so there was simply nothing to show.

This is especially annoying because there the table of contents links to these blank pages, so it looks as if it takes ages to navigate to the desired page and render it, but in fact it's empty and the content you are interested in is on the next page.

BTW: the default font should be the same as in the online docs IMO, so Open Sans.

**Comment by CoDEmanX** [comment]
Works great, and my preferred Android reading app PocketBook appears to work on Lollipop without major issues since the last update.

**Comment by 13abylon** [comment]
Thats great to hear. I'm happy the issue is solved and it works fine on your Android :)
