### ISSUE TITLE
Function PRUNE not support not equal ???

### ISSUE THREAD

**Issue by iamyinweijianGH** [arangodb/arangodb#10494]
## My Environment

* __ArangoDB Version__:        3.5.0
* __Storage Engine__:             
* __Deployment Mode__:       
* __Deployment Strategy__:   
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:        
* __Total RAM in your machine__:        
* __Disks in use__:        
* __Used Package__:              

## Component, Query & Data

__Affected feature__:

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. 
2. 
3. 

__Problem__:
```
FOR v,e.p IN 1..99 OUT xx xxx
PRUNE  v.xx  != 5
RETURN v
```
it can not find anything,but
```
FOR v,e.p IN 1..99 OUT xx xxx
PRUNE  (v.xx < 4 OR v.xx > 6) // v.xx(Integer)
RETURN v
```
it work!!!
__Expected result__:
```
FOR v,e.p IN 1..99 OUT xx xxx
PRUNE  v.xx != 5
RETURN v
```
can find something what i expect！

**Comment by jsteemann** [comment]
`PRUNE` is supposed to support `==` and `!=`.

I just tried it myself with 3.5 and was not able to reproduce the problem. Here is my setup:
```js
db._create("xx"); /* vertices */
db.xx.insert([ 
  { "_key" : "1", "xx" : 5 }, 
  { "_key" : "2", "xx" : 5 }, 
  { "_key" : "3", "xx" : 5 } 
]);

db._createEdgeCollection("xxx"); /* edges */
db.xxx.insert([
  { "_key" : "6930234", "_from" : "xx/1", "_to" : "xx/2" }, 
  { "_key" : "6930241", "_from" : "xx/2", "_to" : "xx/3" }, 
  { "_key" : "6930243", "_from" : "xx/1", "_to" : "xx/3" } 
]);
```
Now, the query:
```
FOR v,e,p IN 1..99 OUTBOUND 'xx/1' xxx PRUNE  v.xx != 5 RETURN v
[ 
  { 
    "_key" : "2", 
    "_id" : "xx/2", 
    "_rev" : "_Zmxkom---_", 
    "xx" : 5 
  }, 
  { 
    "_key" : "3", 
    "_id" : "xx/3", 
    "_rev" : "_ZmxkqU6--_", 
    "xx" : 5 
  }, 
  { 
    "_key" : "3", 
    "_id" : "xx/3", 
    "_rev" : "_ZmxkqU6--_", 
    "xx" : 5 
  } 
]
```
Seems to be just fine for me.

When I update a few vertices to have an `xx` value `!= 5`, then the result changes as expected:
```js
db.xx.update("1", { xx : 4 });
```
```
FOR v,e,p IN 1..99 OUTBOUND 'xx/1' xxx PRUNE  v.xx != 5 RETURN v
(empty result set)
```

Some other changes:
```js
db.xx.update("1", { xx : 5 });
db.xx.update("2", { xx : 4 });
```
```
FOR v,e,p IN 1..99 OUTBOUND 'xx/1' xxx PRUNE  v.xx != 5 RETURN v
[ 
  { 
    "_key" : "2", 
    "_id" : "xx/2", 
    "_rev" : "_Zmxlu0q--_", 
    "xx" : 4 
  }, 
  { 
    "_key" : "3", 
    "_id" : "xx/3", 
    "_rev" : "_ZmxkqU6--_", 
    "xx" : 5 
  } 
]
```
So I can't reproduce the problem.

If you continue running into issues, please provide an example dataset and the exact queries that don't work (the above queries contain typos, so they will not work without modification).

**Comment by iamyinweijianGH** [comment]
thanks, i try it again

**Comment by iamyinweijianGH** [comment]
ok,it is right, is my error

**Comment by jsteemann** [comment]
Thanks for confirming.
