### ISSUE TITLE
Arangosh: add info whether server is running in service or user mode?

### ISSUE THREAD

**Issue by CoDEmanX** [arangodb/arangodb#1051]
I just tried to run `arangod.exe` in user-mode but the cmd closed immediately (could it be *paused* somehow?). I then ran it in a command prompt to see the error message - *database is locked*.

I simply forgot that I installed the arango daemon as service on that computer and had to show processes of all users in Task Manager in order to see the executable.

It would be nice if `arangosh.exe` told something about the mode the server is running in, like

> Welcome to arangosh 2.2.2 [win64]. Copyright (c) triAGENS GmbH
Using Google V8 3.16.14 JavaScript engine, READLINE linenoise, ICU 52.1
Connected to ArangoDB 'tcp://localhost:8529' version: 2.2.2, database: '_system'
, username: 'root', **running in service-mode**

**Comment by dothebart** [comment]
Fatal error messages are now written to the windows eventlog. Does this fix this incident also?

**Comment by CoDEmanX** [comment]
Well, I wouldn't had checked the Windows log in the described case. My request is to add additional info about the modus operandi to the client.

**Comment by dothebart** [comment]
given the multithreadded nature of arangod I don't see any good way to wait for the user to acknowledge the panic and stop the other threads from continuing to work - so its probably not going to change.

**Comment by jsteemann** [comment]
Wasn't the question about being able to show the server operation mode in the ArangoShell?
That means, there should be an API that returns whether the server is running as a Windows service or something else?

**Comment by jsteemann** [comment]
Added 6959f9f63b6cfd55a25bd7b40db04484b31bb380 in devel.
This will make the ArangoShell now print either `service` or `standalone` when it connects.

**Comment by CoDEmanX** [comment]
That's right Jan. Thanks for implementing!
