### ISSUE TITLE
Docker image for Raspberry Pi

### ISSUE THREAD

**Issue by aleklisi** [arangodb/arangodb#10516]
## My Environment

* __ArangoDB Version__:        Latest
* __Storage Engine__:             Any
* __Deployment Mode__:       all
* __Deployment Strategy__:   Manual Start in Docker or ArangoDB Starter in Docker
* __Configuration__:               single instance
* __Infrastructure__:               own
* __Operating System__:        Raspbian
* __Total RAM in your machine__:        0.5GB to 4 GB depending on model
* __Disks in use__:       SD card 
* __Used Package__:              Docker - official Docker library

## Steps to reproduce
```
pi@raspberrypi:~ $ docker run -p 8529:8529 arangodb/arangodb
standard_init_linux.go:211: exec user process caused "exec format error"
```

__Problem__:

The docker image does not work.

__Expected result__:
As a user I want have a docker image for Raspberry Pi (ARM).

**Comment by dothebart** [comment]
Hi, 
this issue is already being discussed over at
https://github.com/arangodb/arangodb-docker/issues/53
So I will close this as duplicate. 
Please note that default Raspii uses ARMv6 which is not possible to support because of the V8 javascript engine.
