### ISSUE TITLE
Internal Server error when iterating over null

### ISSUE THREAD

**Issue by ysmu** [arangodb/arangodb#10559]
## My Environment

* __ArangoDB Version__:        3.5.1
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               Single Server
* __Infrastructure__:               own
* __Operating System__:        Windows 10
* __Total RAM in your machine__:        32GB
* __Disks in use__:        SSD
* __Used Package__:              Windows Official

## Component, Query & Data

__Affected feature__:
AQL

__AQL query (if applicable)__:
```
FOR a IN [{"a": 1}]
    FOR c IN a.b
        RETURN 1
```

## Steps to reproduce

1. Execute the above query and observe the following response from ArangoDB:
```json
{
    "code": 500,
    "error": true,
    "errorMessage": "Expecting type Array or Object (while executing) (exception location: C:\\vm02-windows\\oskar\\work\\ArangoDB\\arangod\\RestHandler\\RestCursorHandler.cpp:283). Please report this error to arangodb.com",
    "errorNum": 4
}
```

__Problem__ & __Expected result__:
While the query itself is invalid (instead of just `a.b` I should have used `NOT_NULL(a.b, [])`, I was expecting a 400 Bad request as opposed to a 500 Internal Server Error.

**Comment by jsteemann** [comment]
This looks similar to #10270.

**Comment by ysmu** [comment]
This looks like the same issue. Sorry for the duplicate. Closing in favor of #10270.
