### ISSUE TITLE
Allow arangodump to backup _jobs and _queues

### ISSUE THREAD

**Issue by monotykamary** [arangodb/arangodb#10558]
## My Environment

* __ArangoDB Version__:        3.5.2
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               N/A
* __Infrastructure__:               Own
* __Operating System__:        Ubuntu 18.04
* __Total RAM in your machine__:        12GB
* __Disks in use__:        HDD
* __Used Package__:              Ubuntu .deb

## Component, Query & Data

__Affected feature__:  arangodump

__Problem__: When arangodump is run with `--include-system-collections`, `_analyzers, _appbundles, _apps, _aqlfunctions, _graphs, _modules` are dumped, but not `_jobs` or `_queues`. We would like to be able to back them up for logging purposes.

__Expected result__: Include `_jobs` and `_queues` to dump in `--include-system-collections` or as another cli option.

**Comment by OmarAyo** [comment]
I verified the behavior, we are discussing internally

**Comment by OmarAyo** [comment]
fixed with https://github.com/arangodb/arangodb/pull/10968

**Comment by maxkernbach** [comment]
Hi @monotykamary,

Version 3.5.5, which includes a fix for this issue, has been released.

From the [Changelog](https://github.com/arangodb/arangodb/blob/69a307b8c03aa23abbac7a9a65a21001b6ea4fce/CHANGELOG#L105):

> 
> * Include collections "_queues" and "_jobs" in dumps created by arangodump
>   in case the option `--include-system-collections` was set to true. Previously
>   these collections were always excluded from dumps.

Please find the latest release in the [download section](https://www.arangodb.com/download/).
