### ISSUE TITLE
Missing doc for javascript module "crypto"

### ISSUE THREAD

**Issue by myguidingstar** [arangodb/arangodb#1055]
There's not documentation generated for "crypto" module yet.
I tried to read the source and came up with some questions:
 - what algorithms can `crypto.hmac` accept?
 - what are these functions and what do they do? `crypto.createNonce`, `crypto.checkAndMarkNonce` and `crypto.constantEquals`

**Comment by jsteemann** [comment]
Documentation for `require("org/arangodb/crypto")` is still missing. @13abylon : can this be added soon?

**Comment by pluma** [comment]
Preliminary documentation for the module has been added in the development version of 3.0.
