### ISSUE TITLE
Query: Expecting type Array or Object (while executing) (exception location: /Users/jenkins/hw18-mac/oskar/work/ArangoDB/arangod/RestHandler/RestCursorHandler.cpp:279).

### ISSUE THREAD

**Issue by jimizai** [arangodb/arangodb#10569]
## My Environment

* __ArangoDB Version__:   3.5.0     
* __Storage Engine__:    RocksDB        
* __Deployment Mode__:       
* __Deployment Strategy__:   
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:        
* __Total RAM in your machine__:        
* __Disks in use__:        
* __Used Package__:              

## Component, Query & Data

__Affected feature__:

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

FOR x IN good
    LET data = IS_LIST(good.attrs)
        ? (FOR t IN good.attrs RETURN DOCUMENT(t))
        : DOCUMENT(good.attrs)
    RETURN data

__Problem__: I want to use FOR in the IS_LIST

__Expected result__:

**Comment by graetzer** [comment]
this needs infomation to reproduce

**Comment by dothebart** [comment]
is `good.attrs` an array or an object?
This exception is often thrown if a `for` can't work with its input.

**Comment by jimizai** [comment]
good.attrs can be  a string or an Array ， I want to iterate if it's an array if it's not an array I want return DOCUMENT(id)

**Comment by dothebart** [comment]
The ternary operator can only completely switch execution paths if its operand is known at query parse time.
Else both paths will allways be executed. 
This could be done if you first pick a list of documents that may be iterated, and then sub-iterate in a second sub-query.

**Comment by jimizai** [comment]
I just started to learn aql. Can you tell me how to write it

**Comment by dothebart** [comment]
```
let subs = (FOR x IN good FILTER IS_LIST(good.attrs) return x)
let retdocs = (FOR y IN subs FOR t IN y.attrs RETURN DOCUMENT(t)))
let plainDocs =  (FOR z IN good FILTER NOT IS_LIST(z.attrs) RETURN DOCUMENT(z.attrs))
RETURN join(retdocs, plainDocs)
```

However, you'd probably want to have some more filter expressions in place before; try using explain in the UI.

**Comment by jimizai** [comment]
Thank u ,it's help me a lot

**Comment by maxkernbach** [comment]
Hi @jimizai,

Do you have any further questions, can we close this ticket?

**Comment by jimizai** [comment]
Ok @maxkernbach

**Comment by Simran-B** [comment]
@jimizai The ternary operator is unnecessary, you can simply cast `attrs` to an array and use a second FOR loop to flatten the result:

```
FOR x IN good
    FOR doc IN DOCUMENT(TO_ARRAY(x.attrs))
        RETURN doc
```
