### ISSUE TITLE
ArangoDB not notarized on MacOS

### ISSUE THREAD

**Issue by larssvensby** [arangodb/arangodb#10561]
## My Environment

* __ArangoDB Version__:        3.5.2
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:                Single Server
* __Infrastructure__:                own
* __Operating System__:        MacOS 10.15.1
* __Total RAM in your machine__:        16GB
* __Disks in use__:        SSD
* __Used Package__:              MacOS Official

## Component, Query & Data

__Affected feature__:
Installation

## Steps to reproduce

1. Install arangodb3-3.5.2.x86_64.dmg
2. Execute the installed ArangoDB3-CLI.app

__Problem__:
MacOS reports in an popup:
> “ArangoDB3-CLI” can’t be opened because Apple cannot check it for malicious software.

Only option is "OK" which quits.

Checking with `spctl -a -vv -t install ArangoDB3-CLI.app` reports
> ArangoDB3-CLI.app: rejected
source=Unnotarized Developer ID
origin=Developer ID Application: ArangoDB GmbH (W7UC4UQXPV)

__Expected result__:
ArangoDB notarized.

**Comment by dothebart** [comment]
Hi, 
yes, this is on our prio-List. But for the time being I can only advise to use the homebrew package.

**Comment by dothebart** [comment]
This was already discussed here: https://github.com/arangodb/arangodb/issues/9633 but didn't happen so far.

**Comment by dothebart** [comment]
Meanwhile our DMG's are notarized.
Please note that [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) is available.
Closing.
