### ISSUE TITLE
Array index/Hash index/SkipLIst index Compatible use optimization

### ISSUE THREAD

**Issue by psoKnight** [arangodb/arangodb#10570]
Hello, sir:
    We use the index as follows：
        `update_time` -> skiplist index
        `special_info[*].t` -> hash index
        `is_special` -> hash index
Our database collection personnel_info currently stores more than 200 million data. As shown below, but if we only use update_time with skiplist index and is_special with hash index at the same time, it looks so fast. And on the other side, we use update_time with skiplist index , special_info[*].t with hash index and is_special with hash index, the query is slow. What happened？How can I add indexes？
![test 01](https://user-images.githubusercontent.com/57337123/69787438-7ffb6e80-11f7-11ea-8dc6-ff034ed5f976.png)
![test 02](https://user-images.githubusercontent.com/57337123/69787440-80940500-11f7-11ea-9e75-a6704c97eb1c.png)

**Comment by graetzer** [comment]
check the query explain output to get more information

**Comment by psoKnight** [comment]
Dear sir：
    We took a closer look at the “explain”print， but why not use skiplist index.If it is convenient, I would like to ask how to optimize?
    As shown :
![2019-11-28_205645](https://user-images.githubusercontent.com/57337123/69808600-d336e680-1222-11ea-884e-1546451d7952.png)
    Thx.
@graetzer

**Comment by dothebart** [comment]
If you're using the rocksdb storage engine, skiplist & hash index basically are the same. Or do you use MMFiles?

**Comment by Simran-B** [comment]
If I understand correctly, you want both indexes to be utilized (one for filtering, one for sorting), but this isn't possible. A combined skiplist index `is_special,special_info[*].t,update_time` might help but could be huge in size. I think a View with a primarySort order would be the better option in this case.

https://www.arangodb.com/docs/stable/arangosearch.html

**Comment by psoKnight** [comment]
It‘s rocksdb. @dothebart

**Comment by psoKnight** [comment]
”MMFiles‘’ does not meet our overall project needs.Thx. @ @dothebart

**Comment by graetzer** [comment]
it is currently not possible to use two indexes at the same time for FILTER and sort. You need to use a combined index. Also the selectivity is quite low, maybe adding a field will help here

**Comment by psoKnight** [comment]
Thx. I will try it.@Simran-B

**Comment by psoKnight** [comment]
Thx. @graetzer

**Comment by OmarAyo** [comment]
Hi @psoKnight 

Did you have the chance to try out what was suggested before, did you find it useful ?

Best,

**Comment by OmarAyo** [comment]
Hi @psoKnight,

We haven't heard back from you recently, therefore I am closing this ticket now

Feel free to reopen at any time,

Best
