### ISSUE TITLE
AQL : How to query for perform full join for multiple collections ??

### ISSUE THREAD

**Issue by SAM-wq** [arangodb/arangodb#10575]
###  **My Environment**

- ArangoDB Version: 3.5.2(the latest i think)
- Storage Engine:RocksDB
- Deployment Mode:Single Server
- Deployment Strategy: Manual Start
- Infrastructure:own
- Operating System: Ubuntu 16.04
- Total RAM in your machine: 8GB
- Disks in use: 256GB

__Problem__:
I have 3 collection and i have to perform full join using aql,how to query for full join ?? 
          
    collection 1 :[
    		        { id :1 , Attr1:"abc" },
    		        { id :2 , Attr1:"asc" },
    		        { id :4 , Attr1:"def" },
    		        { id :5 , Attr1:"xyz" }
    		      ]
    		    
    collection 2 :[
    		        { id :1 , Attr2: true },
    		        { id :2 , Attr2: false },
    		        { id :3,  Attr2: true },
    		        { id :6 , Attr2: true }
    		      ]
    		         				  
    collection 3 :[
    		        { id :1 , Attr3: "jack" },
    		        { id :3 , Attr3: "ryan" },
    		        { id :4 , Attr3: "sam" },
    		        { id :7 , Attr3: "rick" }
    		      ]		
			         				  
__Expected result__:

	[		  
		{ id :1 , Attr1:"abc" , Attr2: true , Attr3: "jack" },     				  
		{ id :2 , Attr1:"asc" , Attr2: false },
		{ id :3,  Attr2: true , Attr3: "ryan" },
		{ id :4 , Attr1:"def" , Attr3: "sam" },
		{ id :5 , Attr1:"xyz" },
		{ id :6 , Attr2: true },
		{ id :7 , Attr3: "rick" }
	]

**Comment by dothebart** [comment]
pls have a look at https://www.arangodb.com/docs/stable/aql/examples-join.html

**Comment by SAM-wq** [comment]
@dothebart Thank you for responce.
