### ISSUE TITLE
WAL compaction doesn't work after extensive delete

### ISSUE THREAD

**Issue by roman1720** [arangodb/arangodb#10587]
## My Environment

* __ArangoDB Version__:        3.4.8
* __Storage Engine__:             MMFiles
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   debian service
* __Infrastructure__:               vmware
* __Operating System__:        debian9
* __Total RAM in your machine__:      32GB
* __Disks in use__:        HDD disk array
* __Used Package__:              debian .deb

## Component, Query & Data

__Affected feature__:
WAL compaction

__AQL query (if applicable)__:
for t in vCachedTable
remove t in vCachedTable

__Dataset__:
dataset has 28GB (dump)

__Size of your Dataset on disk__:
18GB

## Steps to reproduce

1) Bigger dataset, one big collection (in our case vCachedTable has 8.3GB)
2) Run concurrent delete queries for different collections, I did 5 at same time
3) I'm not sure if it has some impact, but during delete from vCachedTable which took 4067.77s I tried run same query which ended on write lock

timed out after 900 s waiting for write-lock on collection 'vCachedTable'

and also several queries which tried to get read-lock 

timed out after 900 s waiting for read-lock on collection 'vCachedTable'

__Problem__:
After all queries finished, WAL log is not compacted. All journal files have 5.3GB. vCachedTable info says there are uncollected entries and one reference. Something blocks collection from being compacted. There are no running queries. It's in this state over night and still same.

__Expected result__:
WAL log compacted to usual state cca 400MB

![image](https://user-images.githubusercontent.com/13378043/69860678-0dda6680-1297-11ea-8ded-989b70c42bd0.png)

**Comment by roman1720** [comment]
I checked what's arango doing (our app is disabled on this machine) and since then, journal is still growing (no idea why, as there are no queries running and no data manipulation.

>root@dev18:/var/lib/arangodb3/journals# ls -la
total 5898264
drwxr-xr-x 2 arangodb arangodb    20480 Dec  9 11:26 .
drwx------ 5 arangodb arangodb     4096 Nov 28 14:14 ..
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 14:13 logfile-1121372241.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 14:13 logfile-1121451852.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 14:13 logfile-1121642713.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 14:13 logfile-1121769392.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 14:13 logfile-1121895948.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 14:13 logfile-1122076566.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 14:13 logfile-1122206661.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 14:13 logfile-1122322839.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 14:13 logfile-1122461830.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 14:13 logfile-1122655810.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:32 logfile-1122865891.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:32 logfile-1123051073.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:32 logfile-1123231791.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:32 logfile-1123878679.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:32 logfile-1124564826.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:32 logfile-1125242966.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:32 logfile-1125991782.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:32 logfile-1126663097.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:32 logfile-1127319783.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:32 logfile-1128050423.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:32 logfile-1128741722.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:33 logfile-1129432902.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:33 logfile-1130117736.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:33 logfile-1130803453.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:33 logfile-1131490846.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:33 logfile-1132187212.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:33 logfile-1132889375.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:33 logfile-1133611349.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:33 logfile-1134321781.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:33 logfile-1135043588.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:33 logfile-1135667603.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:33 logfile-1136384822.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:33 logfile-1137124490.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:33 logfile-1137762268.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:33 logfile-1138482732.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:33 logfile-1139218035.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:34 logfile-1139895009.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:34 logfile-1140525044.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:34 logfile-1141213009.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:34 logfile-1141917720.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:34 logfile-1142554557.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:34 logfile-1143248507.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:34 logfile-1143963260.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:34 logfile-1144593113.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:34 logfile-1145314897.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:34 logfile-1145950020.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:34 logfile-1146656770.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:34 logfile-1147312549.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:35 logfile-1148025658.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:35 logfile-1148698707.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:35 logfile-1149325145.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:35 logfile-1150034331.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:37 logfile-1150718348.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:37 logfile-1151280220.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:37 logfile-1151810459.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:37 logfile-1152353607.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:37 logfile-1152881957.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:37 logfile-1153411006.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:37 logfile-1153952019.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:38 logfile-1154468853.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:38 logfile-1155012875.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:38 logfile-1155536267.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:38 logfile-1156058933.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:38 logfile-1156576629.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:38 logfile-1157112581.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:38 logfile-1157656140.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:39 logfile-1158166764.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:39 logfile-1158695522.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:42 logfile-1159222325.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:43 logfile-1159751183.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:43 logfile-1160286347.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:43 logfile-1160817153.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:51 logfile-1161360278.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 16:58 logfile-1161887583.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:03 logfile-1162508482.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:05 logfile-1162949152.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:06 logfile-1163478419.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:07 logfile-1164012057.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:10 logfile-1164550759.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:11 logfile-1165097939.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:11 logfile-1165619663.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:12 logfile-1166155572.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:13 logfile-1166701410.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:13 logfile-1167241421.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:14 logfile-1167791402.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:14 logfile-1168332421.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:15 logfile-1168880688.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:16 logfile-1169431817.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:16 logfile-1169972734.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:17 logfile-1170519303.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:17 logfile-1171069916.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:18 logfile-1171621573.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:18 logfile-1172170520.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:19 logfile-1172718546.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:19 logfile-1173271739.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:20 logfile-1173828461.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:20 logfile-1174384392.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:21 logfile-1174932476.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:21 logfile-1175490082.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:22 logfile-1176046167.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:22 logfile-1176603671.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:23 logfile-1177175209.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:23 logfile-1177732402.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:24 logfile-1178293973.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:25 logfile-1178862690.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:26 logfile-1179434052.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:27 logfile-1180007774.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:27 logfile-1180550690.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:28 logfile-1181073029.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:28 logfile-1181597449.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:29 logfile-1182120693.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:29 logfile-1182648859.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:29 logfile-1183173966.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:30 logfile-1183696782.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:30 logfile-1184229482.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:30 logfile-1184741462.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:30 logfile-1185276324.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:31 logfile-1185792772.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:31 logfile-1186328616.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:31 logfile-1186851114.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:31 logfile-1187371816.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:31 logfile-1187891535.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:32 logfile-1188418658.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:32 logfile-1188935723.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:32 logfile-1189463836.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:32 logfile-1190004647.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:32 logfile-1190523501.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:32 logfile-1191041134.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:33 logfile-1191566987.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:33 logfile-1192092335.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:33 logfile-1192615642.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:33 logfile-1193145617.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:33 logfile-1193665208.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:34 logfile-1194177587.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:34 logfile-1194710926.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:34 logfile-1195242056.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:34 logfile-1195772419.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:34 logfile-1196282254.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:35 logfile-1196812912.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:35 logfile-1197323790.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:35 logfile-1197860326.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:35 logfile-1198391613.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:35 logfile-1198904789.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:36 logfile-1199433177.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:36 logfile-1199945496.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:36 logfile-1200484887.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:36 logfile-1200996139.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:36 logfile-1201536318.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:36 logfile-1202049061.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:37 logfile-1202581916.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:37 logfile-1203100014.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:37 logfile-1203615467.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:37 logfile-1204157472.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:37 logfile-1204681871.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:38 logfile-1205205777.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:38 logfile-1205727302.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:38 logfile-1206243597.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:38 logfile-1206768884.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:38 logfile-1207296915.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:38 logfile-1207823345.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:39 logfile-1208355553.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:39 logfile-1208863618.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:39 logfile-1209395695.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 17:39 logfile-1209918782.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 28 18:18 logfile-1210453592.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 29 20:10 logfile-1210968328.db
-rw-r----- 1 arangodb arangodb 33554432 Nov 30 23:10 logfile-1211484323.db
-rw-r----- 1 arangodb arangodb 33554432 Dec  2 02:09 logfile-1211999134.db
-rw-r----- 1 arangodb arangodb 33554432 Dec  3 05:08 logfile-1212351795.db
-rw-r----- 1 arangodb arangodb 33554432 Dec  4 08:09 logfile-1212664149.db
-rw-r----- 1 arangodb arangodb 33554432 Dec  5 11:08 logfile-1212976611.db
-rw-r----- 1 arangodb arangodb 33554432 Dec  6 13:58 logfile-1213288780.db
-rw-r----- 1 arangodb arangodb 33554432 Dec  6 13:58 logfile-1213601216.db
-rw-r----- 1 arangodb arangodb 33554432 Dec  6 13:58 logfile-1213913601.db
-rw-r----- 1 arangodb arangodb 33554432 Dec  6 13:58 logfile-1214254071.db
-rw-r----- 1 arangodb arangodb 33554432 Dec  7 16:57 logfile-1214780902.db
-rw-r----- 1 arangodb arangodb 33554432 Dec  8 19:58 logfile-1215298458.db
-rw-r----- 1 arangodb arangodb 33554432 Dec  9 13:23 logfile-1215619977.db
-rw-r----- 1 arangodb arangodb 33554432 Dec  7 16:57 logfile-1215922647.db
-rw-r----- 1 arangodb arangodb 33554432 Dec  8 19:58 logfile-1216225433.db

**Comment by dothebart** [comment]
Hi, 
Please note that we have recently fixed an issue of compaction not happening. 
However, ArangoDB 3.4 is EOLed - so this fix is not available in this release series. 

Please note that [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) is available.
