### ISSUE TITLE
Using primary index on edge collection doesn't work until reloading the collection

### ISSUE THREAD

**Issue by gurisko** [arangodb/arangodb#10582]
## My Environment

* __ArangoDB Version__:        3.4.8
* __Storage Engine__:             MMFiles
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   ArangoDB Starter
* __Configuration__:               single server
* __Infrastructure__:               local
* __Operating System__:        Debian 9
* __Total RAM in your machine__:        8GB
* __Disks in use__:        HDD
* __Used Package__:              Debian or Ubuntu .deb

## Component, Query & Data

__Statement__:
I can't reproduce the issue at the moment. However, the issue occurred on a customer image and one of our dev images. Both were fixed by unloading and loading a collection because there was no time to any deep investigation.

__Affected feature__:
AQL.

__AQL query (if applicable)__:
This would return an empty array:
```
FOR r IN collection
   FILTER r._from == "value"
   RETURN r
```
However, the following query would return an array with multiple elements:
```
FOR r IN collection
   FILTER r._from LIKE "value"
   RETURN r
```

** `collection` is an edge collection

__AQL explain (if applicable)__:
No explain available anymore. But the 1st query used [_from, _to] index, while the 2nd used full iteration.

__Dataset__:
custom

__Problem__:
The 1st query doesn't work despite the 2nd works. Unloading and loading the collection "fixes" the primary index. Both queries work as expected after the load.

**Comment by jsteemann** [comment]
I can't think of any obvious reasons why the in-memory index wouldn't be in sync with the underlying collection data. This is especially true as in MMFiles there is no extra caching layer in-between the two which could be outdated.
If inserting into the index didn't work for some reason, the entire `insert`/`update`/`replace` operations should have failed and returned an error. It should not be the case that there is data present in the collection but not indexed via the edge index.

Did you observe any warnings/errors/log messages prior to the query not returning any data, which indicate there have been any problems?

**Comment by gurisko** [comment]
We just reproduced it again (no idea how). And this is the log from starting the database:
```
2019-12-02T07:10:24Z [1090] INFO ArangoDB 3.4.8 [linux] 64bit, using jemalloc, build tags/v3.4.8-0-g0952837c2a, VPack 0.1.33, RocksDB 5.16.0, ICU 58.1, V8 5.7.492.77, OpenSSL 1.1.0k  28 May 2019
2019-12-02T07:10:28Z [1090] INFO detected operating system: Linux version 4.9.0-11-amd64 (debian-kernel@lists.debian.org) (gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) ) #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11)
2019-12-02T07:10:28Z [1090] INFO {authentication} Jwt secret not specified, generating...
2019-12-02T07:10:28Z [1090] INFO using storage engine mmfiles
2019-12-02T07:10:28Z [1090] INFO {cluster} Starting up with role SINGLE
2019-12-02T07:10:28Z [1090] INFO {syscall} file-descriptors (nofiles) hard limit is 131072, soft limit is 131072
2019-12-02T07:10:28Z [1090] WARNING {threads} --server.threads (64) is more than eight times the number of cores (4), this might overload the server
2019-12-02T07:10:29Z [1090] INFO {authentication} Authentication is turned off, authentication for unix sockets is turned on
2019-12-02T07:10:29Z [1090] WARNING found existing lockfile '/var/lib/arangodb3/LOCK' of previous process with pid 1015, but that process seems to be dead already
2019-12-02T07:10:43Z [1090] INFO {engines} running WAL recovery (1 logfiles)
2019-12-02T07:10:43Z [1090] INFO {engines} replaying WAL logfile '/var/lib/arangodb3/journals/logfile-197261774.db' (1 of 1)
2019-12-02T07:11:36Z [1090] INFO {engines} WAL recovery finished successfully
2019-12-02T07:11:36Z [1090] INFO {engines} DB recovery finished successfully
2019-12-02T07:11:40Z [1090] INFO using endpoint 'http+tcp://0.0.0.0:8529' for non-encrypted requests
2019-12-02T07:11:41Z [1090] INFO ArangoDB (version 3.4.8 [linux]) is ready for business. Have fun!
```
We didn't find anything suspicious.

**Comment by jsteemann** [comment]
Thanks for sharing the logs. I don't think the warnings in the logs have anything to do with the problem.
(the one warning just indicates that the server was restarted after a crash or at least unclean shutdown, the other warning is about the `_apps` collection which is not the collection in question here).

**Comment by gurisko** [comment]
I will try to get back to you with more logs. But this is all I have for now.

**Comment by jsteemann** [comment]
If this happens again, can you try gathering the following information?
```js
c = db._collection("collection"); /* use actual collection name here */
db._explain('FOR r IN @@collection FILTER r._from == "value" RETURN r', { '@collection': c.name() });
print("count:", c.count());
print("figures:", c.figures());
print("indexes", c.getIndexes(true));
```
Thanks!

**Comment by gurisko** [comment]
#### Execution Plan
```
{ plan:
   { nodes:
      [ { type: 'SingletonNode',
          dependencies: [],
          id: 1,
          estimatedCost: 1,
          estimatedNrItems: 1 },
        { type: 'IndexNode',
          dependencies: [ 1 ],
          id: 6,
          estimatedCost: 1.98,
          estimatedNrItems: 1,
          outVariable: { id: 0, name: 'r' },
          projections: [],
          producesResult: true,
          database: 'nimpee',
          collection: 'eLink',
          satellite: false,
          needsGatherNodeSort: false,
          indexCoversProjections: false,
          indexes:
           [ { id: '1',
               type: 'edge',
               fields: [ '_from', '_to' ],
               selectivityEstimate: 1,
               unique: false,
               sparse: false } ],
          condition:
           { type: 'n-ary or',
             typeID: 63,
             subNodes:
              [ { type: 'n-ary and',
                  typeID: 62,
                  subNodes:
                   [ { type: 'compare ==',
                       typeID: 25,
                       excludesNull: false,
                       subNodes:
                        [ { type: 'attribute access',
                            typeID: 35,
                            name: '_from',
                            subNodes: [ { type: 'reference', typeID: 45, name: 'r', id: 0 } ] },
                          { type: 'value',
                            typeID: 40,
                            value: 'vDevice/193163012',
                            vType: 'string',
                            vTypeID: 4 } ] } ] } ] },
          sorted: true,
          ascending: true,
          reverse: false,
          evalFCalls: true,
          limit: 0 },
        { type: 'ReturnNode',
          dependencies: [ 6 ],
          id: 5,
          estimatedCost: 2.98,
          estimatedNrItems: 1,
          inVariable: { id: 0, name: 'r' },
          count: true } ],
     rules:
      [ 'use-indexes',
        'remove-filter-covered-by-index',
        'remove-unnecessary-calculations-2' ],
     collections: [ { name: 'eLink', type: 'read' } ],
     variables: [ { id: 2, name: '1' }, { id: 0, name: 'r' } ],
     estimatedCost: 2.98,
     estimatedNrItems: 1,
     initialize: true,
     isModificationQuery: false },
  cacheable: true,
  warnings: [],
  stats: { rulesExecuted: 34, rulesSkipped: 0, plansCreated: 1 },
  error: false,
  code: 200 }
```

#### Count
```
{ error: false,
  code: 200,
  waitForSync: false,
  type: 3,
  statusString: 'loaded',
  status: 3,
  id: '167109211',
  doCompact: true,
  count: 6120,
  journalSize: 33554432,
  indexBuckets: 8,
  globallyUniqueId: 'h19CD9F8BCAD3/167109211',
  isVolatile: false,
  isSystem: false,
  keyOptions:
   { allowUserKeys: true,
     type: 'traditional',
     lastValue: 197371378 },
  name: 'eLink' }
```

#### Figures
```
{ error: false,
  code: 200,
  waitForSync: false,
  type: 3,
  statusString: 'loaded',
  status: 3,
  name: 'eLink',
  id: '167109211',
  globallyUniqueId: 'h19CD9F8BCAD3/167109211',
  isVolatile: false,
  doCompact: true,
  count: 6120,
  journalSize: 33554432,
  figures:
   { indexes: { count: 3, size: 770624 },
     documentReferences: 0,
     waitingFor: '-',
     alive: { count: 6120, size: 2012056 },
     dead: { count: 70, size: 23768, deletion: 4187 },
     compactionStatus:
      { message: 'skipped compaction because collection has no datafiles',
        time: '2019-12-03T07:47:28Z',
        count: 0,
        filesCombined: 0,
        bytesRead: 0,
        bytesWritten: 0 },
     datafiles: { count: 0, fileSize: 0 },
     journals: { count: 1, fileSize: 33554432 },
     compactors: { count: 0, fileSize: 0 },
     revisions: { count: 6120, size: 418368 },
     lastTick: 197372264,
     uncollectedLogfileEntries: 0 },
  indexBuckets: 8,
  isSystem: false,
  keyOptions:
   { allowUserKeys: true,
     type: 'traditional',
     lastValue: 197371378 } }
```
#### Indexes
```
[ { fields: [ '_key' ],
    id: 'eLink/0',
    selectivityEstimate: 1,
    sparse: false,
    type: 'primary',
    unique: true },
  { fields: [ '_from', '_to' ],
    id: 'eLink/1',
    selectivityEstimate: 1,
    sparse: false,
    type: 'edge',
    unique: false },
  { deduplicate: true,
    fields: [ '_ci', 'type' ],
    id: 'eLink/198183392',
    selectivityEstimate: 0.0014705882352941176,
    sparse: false,
    type: 'hash',
    unique: false } ]
```

**Comment by jsteemann** [comment]
Thanks for the info.
I was actually hoping for the output of `print("indexes", c.getIndexes(true));`, as executed from the arangosh. This would have shown some more index details (i.e. for each index it would have shown the number of items inside the index - comparing this to the count value of the collection would have shown if there is an obvious problem).
Is it possible to gather these values using arangosh next time it happens? 
Thanks!

**Comment by OmarAyo** [comment]
Hi @gurisko 

Did you have the chance to read jsteemann's latest message ? If yes can you provide the requested values via arangosh

Best

**Comment by gurisko** [comment]
@OmarAyo Yes I did, but as for now, I am unable to reproduce the issue. I am sure it will pop out again soon, and I will update the thread.

**Comment by gurisko** [comment]
@OmarAyo @jsteemann This is the output my colleague managed to get from ArangoDB v3.5.3 (the same deployment as in the first comment) https://gist.github.com/gurisko/e311e2196a1c1b665c36d00475d6b96c

**Comment by jsteemann** [comment]
According to the [output from the `figures` command](https://gist.github.com/gurisko/e311e2196a1c1b665c36d00475d6b96c), it looks like there were 5068 documents in the collection, and also in the primary index.
However, the secondary indexes of the collection, i.e. the edge index plus the user-defined hash index, only contained 0 documents. This makes the index contents inconsistent, as the secondary indexes should contain the same amount of documents as the primary index (at least for non-sparse indexes as it is the case here). 
The obvious workaround to get everything back in sync is indeed to unload the collection and load/access it again. This will rebuild the in-memory secondary indexes so everything should be back in sync. However, this is obviously a workaround for a bug.

I am wondering what kind of write operations are performed on the underlying collection `eLink`. If we can rule out certain operations that may make finding the root cause a bit easier. Do you happen to know which of the following operations are executed on the collection in question under normal conditions?
- [ ] client driver/arangosh-based remove operation (single key)
- [ ] client driver/arangosh-based update operation (single key)
- [ ] client driver/arangosh-based replace operation (single key)
- [ ] client driver/arangosh-based insert operation (single key)
- [ ] client driver/arangosh-based remove operation (with an array of documents/keys)
- [ ] client driver/arangosh-based update operation (with an array of documents)
- [ ] client driver/arangosh-based remove operation (with an array of documents)
- [ ] client driver/arangosh-based insert operation (with an array of documents)
- [ ] client driver/arangosh-based truncate operation
- [ ] client driver/arangosh-based load/unload operation
- [ ] JavaScript transactions
- [ ] AQL REMOVE
- [ ] AQL UPDATE
- [ ] AQL REPLACE
- [ ] AQL INSERT

**Comment by jsteemann** [comment]
I didn't find any obvious issues in the index code, so I am still wondering what could be causing the problem. I have created a PR https://github.com/arangodb/arangodb/pull/11049 that adds extra error logging in case things go wrong, plus more assertions. I have started a PR run and hope it shows something interesting.

**Comment by jsteemann** [comment]
Also looks similar to the issue reported in #10572 and #10573

**Comment by gurisko** [comment]
This is 5 years old and it uses MMFiles. Closing
