### ISSUE TITLE
invalid argument type in call to function 'IS_SAME_COLLECTION()

### ISSUE THREAD

**Issue by ELARCHA** [arangodb/arangodb#10593]
When i use a AQL query in JAVA that contains 'IS_SAME_COLLECTION() function i have this warning **"invalid argument type in call to function 'IS_SAME_COLLECTION()"**

This an example of my query :
```
  @Query(" WITH user, user_group, org_client,client, product,  " +
          "      for user in user filter user._id == CONCAT('user/',@userId) " +
          "      FOR client IN 1..5 OUTBOUND user " +
          "      user_to_user_group, principal_access,client_graph " +
          "      FILTER IS_SAME_COLLECTION('client', client) " +
          "      let org_client_Key=(FOR cpg IN 1..1 inBOUND client client_graph return cpg._key) " +
          "     return merge(client,{groupId:org_client_Key[0]})")
  List<Client> findAllClientByUser(@Param("userId") String userId);
```

## My Environment

* __ArangoDB Version__:        3.3
* __spring boot Version__:        2

**Comment by Simran-B** [comment]
`client` should be the current vertex document in the traversal, which should have an `_id` attribute. However, should an edge point to a non-existing vertex then it would be `null` instead and issue a warning if used as second argument for `IS_SAME_COLLECTION()`.

You may add the following above the other FILTER to diagnose it:

    FILTER WARN(IS_OBJECT(client) AND IS_STRING(client._id), CONCAT("2nd argument to IS_SAME_COLLECTION() invalid, client = ", JSON_STRINGIFY(client)))

**Comment by ELARCHA** [comment]
Thank you @Simran-B  ,
I try to filter but always  i have this warning dispute the query return the results i want just ignore this warning .

**Comment by Simran-B** [comment]
Can you share a minimal example dataset which can be used to reproduce the issue on our end?

**Comment by ELARCHA** [comment]
The above exemple produce always the warning

**Comment by Simran-B** [comment]
Your example is only the query, but the dataset to reproduce it is missing (the collections user, user_group, org_client,client, product, user_to_user_group, principal_access,client_graph )

**Comment by ELARCHA** [comment]
user : collection (id,username,password)
user_group: collection (id,groupName)
user_to_user_group: edge (user;user_group)
principal_access : edge (user_group , (org_client or client))
org_client: organisation client
client : (id,name)
client_graph: graph (orgclient,client,produit)
produit :( id,name)

**NB** : sometimes client without orgClient

**Comment by Simran-B** [comment]
Thanks for the description of the document structure, but this is insufficient to reproduce the problem. We need the actual data for that, especially in such a case because there could be invalid edges or other things off with your dataset, which cannot be diagnosed from a meta description of the data.

**Comment by ELARCHA** [comment]
I was describe all collections there is no other edges that all what you want such us information ?

**Comment by dothebart** [comment]
Hi, 
@Simran-B was asking for enough information to reproduce this issue locally, and the information is still missing. 
Anyways, ArangoDB 3.3 is EOL. Please upgrade to [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) and if the issue persists open a new issue.
