### ISSUE TITLE
arangosearch: primarySort in view cannot be set via .properties

### ISSUE THREAD

**Issue by admtech** [arangodb/arangodb#10594]
## My Environment

* __ArangoDB Version__: 3.5.2      
* __Storage Engine__: RocksDB            
* __Deployment Mode__:  Single Server     
* __Deployment Strategy__:  ArangoDB Starter 
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__: Ubuntu 18.04.3 LTS       
* __Total RAM in your machine__:   12Gb     
* __Disks in use__:   SSD     
* __Used Package__:   Ubuntu .deb           

## Component, Query & Data

__Affected feature__: views, arangosearch, arangosh, ArangoDB web interface

__Dataset__:

```
[ 
  { 
    "_key" : "11083", 
    "_id" : "test/11083", 
    "_rev" : "_ZpPKb02--_", 
    "last_name" : "Mueller", 
    "first_name" : "Thomas" 
  }, 
  { 
    "_key" : "11461", 
    "_id" : "test/11461", 
    "_rev" : "_ZpPSLVG--_", 
    "last_name" : "Meier", 
    "first_name" : "Klaus" 
  }, 
  { 
    "_key" : "16095", 
    "_id" : "test/16095", 
    "_rev" : "_ZpRPjGq--_", 
    "first_name" : "Willi", 
    "last_name" : "Hase" 
  }, 
  { 
    "_key" : "16132", 
    "_id" : "test/16132", 
    "_rev" : "_ZpRQSxG--_", 
    "first_name" : "Simon", 
    "last_name" : "Bond" 
  } 
]
```

## Steps to reproduce
1. Create a View with sort via arangosh

db._createView("search_with_sort","arangosearch",{ primarySort:[{field:"last_name",direction:"asc"}]})

2. Create links in View via properties

db.search_with_sort.properties({links: {test: { includeAllFields: true, fields: { first_name: { analyzers:['text_de']},last_name: { analyzers:['text_de']}}}}})

Both works.

3. Now, change/update the primarySort with properties:

db.search_with_sort.properties({primarySort:[{field:"first_name",direction:"desc"},{field:"last_name",direction:"desc"}]})

__Problem__:
primarySort did not change

```
{ 
  "cleanupIntervalStep" : 2, 
  "commitIntervalMsec" : 1000, 
  "consolidationIntervalMsec" : 10000, 
  "consolidationPolicy" : { 
    "type" : "tier", 
    "segmentsBytesFloor" : 2097152, 
    "segmentsBytesMax" : 5368709120, 
    "segmentsMax" : 10, 
    "segmentsMin" : 1, 
    "minScore" : 0 
  }, 
  "primarySort" : [ 
    { 
      "field" : "last_name", 
      "asc" : true 
    } 
  ], 
  "writebufferActive" : 0, 
  "writebufferIdle" : 64, 
  "writebufferSizeMax" : 33554432, 
  "links" : { 
    "test" : { 
      "analyzers" : [ 
        "identity" 
      ], 
      "fields" : { 
        "last_name" : { 
          "analyzers" : [ 
            "text_de" 
          ] 
        }, 
        "first_name" : { 
          "analyzers" : [ 
            "text_de" 
          ] 
        } 
      }, 
      "includeAllFields" : true, 
      "storeValues" : "none", 
      "trackListPositions" : false 
    } 
  } 
}
```

__Expected result__:

```
  "primarySort" : [ 
    { 
      "field" : "fist_name", 
      "desc" : true 
    },
    { 
      "field" : "last_name", 
      "desc" : true 
    }  
  ], 

```
The same behavior can be found if you create a view without "primarySort". After that it is no longer possible to change this "primarySort" via .properties.

The behavior can also be found in the ArangoDB web interface. You can't change or update the "primarySort" in "Views" via "Tree" or "code".

**Comment by admtech** [comment]
oh, I just found a statement about this in the release note:

> Note that the primarySort option is immutable: it can not be changed after View creation. It is therefore not possible to configure it through the Web UI. The View needs to be created via the HTTP or JavaScript API (arangosh) to set it.

This should be mentioned in the official documentation and not only in the release notes. So it's not a bug at the moment, but should be different in the future. So you can change "primarySort" with .properties. As long as a hint should appear, otherwise it confuses the users nevertheless very much. It is then a feature request :-)

**Comment by Simran-B** [comment]
Aside from the release notes:
https://www.arangodb.com/docs/stable/release-notes-new-features35.html#sorted-index

… it is mentioned three more times in the documentation:

![image](https://user-images.githubusercontent.com/7819991/69876849-f1ebba80-12c0-11ea-89c9-f9954ccea7a9.png)
https://www.arangodb.com/docs/stable/arangosearch-views.html#view-properties

![image](https://user-images.githubusercontent.com/7819991/69876917-134ca680-12c1-11ea-842e-77470ade9060.png)
https://www.arangodb.com/docs/stable/arangosearch-views.html#primary-sort-order

![image](https://user-images.githubusercontent.com/7819991/69876972-35462900-12c1-11ea-9761-7c3d8811294d.png)
https://www.arangodb.com/docs/stable/release-notes-known-issues35.html#arangosearch

**Comment by admtech** [comment]
I'm sticking with it, it's for newbies to hide. I watched the documentary on the view and then tried it out. It would have been better if this hint appeared in the shell. But there is no hint at all. So you start to look for the error, but you don't know exactly what you're looking for. 
In general I understood it now.
