### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by jimizai** [arangodb/arangodb#10600]
## My Environment

* __ArangoDB Version__:  3.5.2      
* __Storage Engine__:     roksdb        
* __Deployment Mode__:       
* __Deployment Strategy__:   
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:        
* __Total RAM in your machine__:        
* __Disks in use__:        
* __Used Package__:              

## Component, Query & Data

__Affected feature__:

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce
Yesterday I deployed the arango on the docker, And today I use docker ps find this: fatal error: runtime: out of memory, And I checked the top find arangoDB use 50%+ memory. I kown that my machine configuration is very poor but I just did nothing .I restarted the docker And  only provide a temporary solution to this.
memory 2GB

**Comment by Simran-B** [comment]
2 GB of memory is very little to work with for the database system. You can take a look here to reduce the memory usage:

https://www.arangodb.com/docs/stable/tutorials-reduce-memory-footprint.html

**Comment by OmarAyo** [comment]
Hi @jimizai 

Did you have the chance to read Simran's message ? Was it useful for you ?

Let us know

Best,

**Comment by OmarAyo** [comment]
Hi @jimizai 

We haven't heard back from you recently therefore I am closing this ticket now

Feel free to reopen it at any time

Best,
