### ISSUE TITLE
Incorrect results using Arango Search/View after restart

### ISSUE THREAD

**Issue by robhopkins-gl** [arangodb/arangodb#10605]
## My Environment

* __ArangoDB Version__:        3.5.0
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Kubernetes (minikube)
* __Configuration__:               
* __Infrastructure__:               own
* __Operating System__:        Ubuntu 18.04
* __Total RAM in your machine__:        32Gb.
* __Disks in use__:        SSD
* __Used Package__:            

## Component, Query & Data

__Affected feature__:
Arango search/view

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1.  Start minikube and install arangodb as a Single server.
2.  Create a db with collections and a search view.
3.  Stop minikube.
4.  Start minikube.

__Problem__:
After restarting minikube, the search view does not use new data added to the linked collections.

__Expected result__:
The search view to work after restart using new data in linked collections.

**Comment by dothebart** [comment]
Hi, 
please note that views are `eventually consistent` https://www.arangodb.com/docs/3.7/arangosearch-views.html - and that they may take some time to catch up. 
Views store their Data alongside with the regular database files, they should be persisted in storage volumes?
