### ISSUE TITLE
Opinions about Foxx application export feature

### ISSUE THREAD

**Issue by myguidingstar** [arangodb/arangodb#1060]
IMO current ad hoc implementation/API of Foxx application export is quite dangerous due to lack of dependency management.
We encourage developers to share reusable application portions. But when more people adopt it, the current api (that only requires an app to specify a target app's mount point) may cause complexity.
Let's say some situations:
- A sys admin whose job is to maintain the DB. He/she has no idea what the apps have in their source code. Or maybe he/she is able to read code, but there are simply too many of them. How can he/she know whether unmounting an app may cause some other apps to stop working?
- App A depends on app B. B's mount point must be hard coded in A's source code. If B needs to change its mount point then A 's source code has to be modified. That's insane!
- App B comes to a new version and there's no clear way for app A to know if B's API may no longer work in app A. Because there's no version.

Any ideas?

**Comment by pluma** [comment]
This has been implemented in devel.
