### ISSUE TITLE
Multigraph vizualization improvement in Graph Viewer

### ISSUE THREAD

**Issue by anatoly21** [arangodb/arangodb#10639]
## My Environment

* __ArangoDB Version__:        3.5.1
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start in Docker
* __Configuration__:               
* __Infrastructure__:               AWS
* __Operating System__:        Ubuntu 18.04
* __Total RAM in your machine__:       8GB
* __Disks in use__:        SD
* __Used Package__:             Docker - official Docker library

## Component, Query & Data

__Affected feature__: graph visualization in Graph Viewer

__Problem__: Parallel edges between pair of nodes are rendered as coincident even if "Curve" edge type is specified 

__Expected result__: Parallel edges between pair of nodes are rendered as distinct curves when  "Curve" edge type is specified

**Comment by maxkernbach** [comment]
Hi @anatoly21,

The same feature was already requested in issue https://github.com/arangodb/arangodb/issues/2527, therefore I am closing this issue as a duplicate. 

Please continue further discussion on this topic in the referenced issue.
