### ISSUE TITLE
AQL-  expected join possible in Arangodb ??

### ISSUE THREAD

**Issue by SAM-wq** [arangodb/arangodb#10667]
###  **My Environment**

- ArangoDB Version: 3.5.2(the latest i think)
- Storage Engine:RocksDB
- Deployment Mode:Single Server
- Deployment Strategy: Manual Start
- Infrastructure:own
- Operating System: Ubuntu 16.04
- Total RAM in your machine: 8GB
- Disks in use: 256GB

__Problem__:
I have 2 collection and i have to perform join and want expected result is that possible in Arangodb ?? 
          
```
collection 1 :[
    		    { id :1 , name: "jack" },
    		    { id :2 , name: "ryan" },
    		    { id :3 , name: "sam" },
    		    { id :4 , name: "rick" },
    		    { id :5 , name: "jackie" },
    		    { id :6 , name: "roman" },
    		    { id :7 , name: "soul" },
    		    { id :8 , name: "brad" }
    	      ]	 
```
 
```
collection 2 :[
    		     { id :1 ,age:12 ,standard: 5 },
    		     { id :5 ,age:14 ,standard: 7 },
    		     { id :7,age:15 ,standard: 8 }
    	      ]

```
			         				  
__Expected result__:
```
[
        { id :1 , name: "jack",standard: 5  },
    	{ id :2 , name: "ryan",standard: 5  },
    	{ id :3 , name: "sam" ,standard: 5 },
    	{ id :4 , name: "rick",standard: 5  },
    	{ id :5 , name: "jackie",standard: 7  },
    	{ id :6 , name: "roman",standard: 7  },
    	{ id :7 , name: "soul",standard: 8  },
    	{ id :8 , name: "brad",standard: 8  }
]
```

**Comment by Simran-B** [comment]
Hey @SAM-wq, your example of collection 2 is either incomplete or this isn't actually a join. In your expected result, it looks like you want to join collection 1 and 2 by `id`, but the result of your example data would be:

```js
FOR doc IN coll1
    LET doc2 = FIRST(
        FOR d IN coll2 FILTER d.id == doc.id LIMIT 1 RETURN KEEP(d, "standard")
    ) || {} // Fallback for MERGE() if attribute is missing
    LET merged = MERGE(doc, doc2)
    RETURN KEEP(merged, ATTRIBUTES(merged, true))

[
  { "id": 1, "name": "jack", "standard": 5 },
  { "id": 2, "name": "ryan" },
  { "id": 3, "name": "sam" },
  { "id": 4, "name": "rick" },
  { "id": 5, "name": "jackie", "standard": 7 },
  { "id": 6, "name": "roman" },
  { "id": 7, "name": "soul", "standard": 8 },
  { "id": 8, "name": "brad" }
]
```

There is no guarantee about the order here.

It looks like you want the last `standard` value to be re-used if there is none for the current `id` in collection 2. There are some ideas for a future version of ArangoDB to allow you to access a previous value, but for now this might be a workaround:

```js
For doc IN coll1
    FOR doc2 IN coll2
        FILTER doc2.id <= doc.id
        COLLECT d = doc AGGREGATE max = MAX(doc2.id)
        SORT d.id
        LET merged = MERGE(d, { standard: FIRST(FOR doc2 IN coll2 FILTER doc2.id == max LIMIT 1 RETURN doc2.standard)})
        RETURN KEEP(merged, ATTRIBUTES(merged, true))

[
  { "id": 1, "name": "jack", "standard": 5 },
  { "id": 2, "name": "ryan", "standard": 5 },
  { "id": 3, "name": "sam", "standard": 5 },
  { "id": 4, "name": "rick", "standard": 5 },
  { "id": 5, "name": "jackie", "standard": 7 },
  { "id": 6, "name": "roman", "standard": 7 },
  { "id": 7, "name": "soul", "standard": 8 },
  { "id": 8, "name": "brad", "standard": 8 }
]
```

I tested a few corner cases and couldn't find any problems yet:
- duplicate ids in collection 1 get the same standard value
- with an id 0 in collection 1 and no corresponding entry in collection 2 but one with -4 instead works as expected (the standard value of the -4 entry is looked up for the id 0 document)
- standard values do not need to be strictly increasing numbers
- skipped ids in collection 1 do not cause any issues

**Comment by OmarAyo** [comment]
Hi @SAM-wq 

Did you find Simran's message useful ?

Best
