### ISSUE TITLE
Find edges between two vertices in general-graph

### ISSUE THREAD

**Issue by mchacki** [arangodb/arangodb#1066]
A feature request issued at the googlegroup:

An easy way to find all edges between two given vertices in a graph should be implemented.

**Comment by jan-zajic** [comment]
+1 for this, if it's still not implemented.

**Comment by mchacki** [comment]
Oh just an update on this one:
Having 2.8 released you can now easily do the following AQL:

    FOR target, edge IN OUTBOUND "v/1" GRAPH "graph" FILTER target._id == "v/2" RETURN edge

Which will give you all edges of graph `graph` starting in `v/1` and ending in `v/2`, all accessible via `edge`.
NOTE: OUTBOUND can be replaced by INBOUND or ANY for different directions.
