### ISSUE TITLE
Wrong link or abandoned driver in documentation

### ISSUE THREAD

**Issue by ArsProgramma** [arangodb/arangodb#10677]
Visiting this site:
https://www.arangodb.com/arangodb-drivers/

and selecting Microsoft .NET
tells us there's a driver named "arangoclient.net".
However when visiting the link it takes us to 
https://kuechenmayer.sevcom.de/
a site selling kitchens and stuff for kitchens.
This should be fixed or removed.

**Comment by ObiWahn** [comment]
https://github.com/ra0o0f/arangoclient.net/

I think this should be the correct repo. Unfortunately it is a bit outdated as well.

**Comment by Simran-B** [comment]
Thank you for bringing this up, I updated the link to point to the GitHub repository.

**Comment by dothebart** [comment]
hi @ra0o0f - can you give this a check? the github repository also lists that name in the README

**Comment by ra0o0f** [comment]
thank you @dothebart, link is now removed from README

**Comment by dothebart** [comment]
thanks.
