### ISSUE TITLE
Unique edge relations in general graph

### ISSUE THREAD

**Issue by mchacki** [arangodb/arangodb#1067]
Discussable:
It might be a good idea to have dedicated relations in the general-graph module that allow a restriction of at most one edge per pair of vertices in the same edge collection.
This allows to uniquely identify the connecting edge and store all relevent information in this edge.
The proposed restriction would look the following way (assume `graph` to be a general-graph and `uniqueEdge` to be a relation having this restriction)

````
arangosh> graph.uniqueEdge.save("v/1", "v/2", {});
true
arangosh> graph.uniqueEdge.save("v/1", "v/2", {other: "data"});
Error in Graph Module: Unique Edge Constraint violated.
````

**Comment by dothebart** [comment]
ArangoDB 3.0 can actually create additional indices. This will however cost more memory.
