### ISSUE TITLE
Add 'raw' link to swagger ui so that the raw swagger json can easily be retrieved

### ISSUE THREAD

**Issue by seanmikalson** [arangodb/arangodb#1069]
Raw swagger can be used to generate client sdks for many languages so it is helpful to expose this link to easily give developers this capability.

**Comment by visualjeff** [comment]
FYI: Raw link is gone again from the Pet demo.

**Comment by jsteemann** [comment]
I think it is still available, but it is now named "Download API" (should be on the right in the **Links** section) after clicking on an app in the **Applications** tab.

**Comment by mchacki** [comment]
Which version of ArangoDB are you using?
In my 2.4. both links are available:
![swaggerdocumentation](https://cloud.githubusercontent.com/assets/2317920/6124012/c5a6efee-b109-11e4-9853-23b6a18e2713.png)

**Comment by codebude** [comment]
Having a look at http://petstore.swagger.io/#/pet - I think it's missing again. Can't find any "raw" or "Download API" link.

**Comment by hkernbach** [comment]
![image](https://cloud.githubusercontent.com/assets/1244163/16108713/207ceecc-33a5-11e6-8b2b-0e32835e012b.png)

The "Download API" Link moved to "SHOW JSON". I've attached a screenshot.
