### ISSUE TITLE
Support for Cluster Maintenance / readonly mode

### ISSUE THREAD

**Issue by CoDEmanX** [arangodb/arangodb#1070]
According to the [docs](https://docs.arangodb.com/Arangodump/README.html), _arangodump_ locks the (entire?) database during the export, as long as a single instance of the server is used. There is no locking for clusters however:

> However, as opposed to the single instance situation, this operation does not lock the data in the cluster and can therefore not guarantee to dump a consistent snapshot if writing operations happen during the dump operation! That is, it is recommended not to perform any data modifying operations on the cluster whilst arangodump is running.

I wonder if there's some kind of maintenance mode one can turn on temporarily to take a consistent snapshot from a cluster, or for other purposes. This could either be a setting to allow read access only, or to buffer write commands for a certain amount of time and apply them once the maintenance mode is switched off again.

**Comment by dothebart** [comment]
For traditional backups (i.e. arangodump) there is no such lock. Instead, a snapshot is taken. Writes can then go only while the database is dumped, without modifying the data in the snapshot. The dump is consistent on a single server.
For a cluster, the dump is consistent for each individual DB-Server, but not for the entire cluster.
Hot backup will acquire a write lock to ensure all pending transactions get finished, then do the backups and release the lock. So it will create consistent backup both in single server and in the cluster case.
