### ISSUE TITLE
union key

### ISSUE THREAD

**Issue by wqxcloud** [arangodb/arangodb#10710]
Is this database has union key? for example : key  is studentId  and teacherId

**Comment by Simran-B** [comment]
The primary index is always a single attribute `_key`. This can not be changed. However, you can create secondary indexes over multiple fields (also known as compound indexes) and enable the uniqueness option to ensure that any combination of attribute values will only ever be allowed once in the collection.

**Comment by OmarAyo** [comment]
Hi @wqxcloud 

Did you find Simran's reply useful - is there anything else you want to clarify 

Best,

**Comment by OmarAyo** [comment]
Hi @wqxcloud 

It has been a while we have not heard back from you, therefore I am closing this ticket now

Feel free to reopen it by adding a new comment 

Best,
