### ISSUE TITLE
Uninstaller: keeps executables if they are running

### ISSUE THREAD

**Issue by CoDEmanX** [arangodb/arangodb#1071]
If you uninstall ArangoDB, `var\` is kept (as it should), but also `bin\` and all executables inside which are currently running (at least on Windows 7).

It would be nice if the uninstaller prompted whether it should shutdown / close the running processes and then remove the executables entirely.

**Comment by dothebart** [comment]
This should be fixed with the 2.5.1 installer; @CoDEmanX can you revalidate that?

**Comment by CoDEmanX** [comment]
There's an error dialog popping up, that tells me executable X is not writable and whether I'd like to abort, retry or ignore. So I guess it's fine, a running server in the background won't go unnoticed.
