### ISSUE TITLE
Wrong docs count in ArangoDB Web interface

### ISSUE THREAD

**Issue by deiks** [arangodb/arangodb#10725]
## My Environment

* __ArangoDB Version__:        3.5.3
* __Storage Engine__:             RocksDB
* __Used Package__:              Debian

## Steps to reproduce

1. Create two collections, first empty and second with some records in it
2. Switch to collection with records to preview data, on bottom left you can see total records in collection
3. Switch to empty collection

__Problem__:

Is shows total records of previously viewed collection.

__Expected result__:

It should show 0 docs.

**Comment by maxkernbach** [comment]
Hi @deiks,

Thanks for reporting this issue. It is easily reproducible using the steps you reported.

**Comment by maxkernbach** [comment]
Hi @deiks,

Version 3.5.4, which includes a fix for this issue, has just been released.

From the [Changelog](https://github.com/arangodb/arangodb/blob/bc452c29550a4733913249a8840f2ecbf557c603/CHANGELOG#L33):
> * Fixed issue #10725: Wrong document count shown inside an empty collection in
  the web UI.

Please find the latest release in the [download section](https://www.arangodb.com/download/).
