### ISSUE TITLE
Installer: Path too long on installation (warning/error)

### ISSUE THREAD

**Issue by CoDEmanX** [arangodb/arangodb#1073]
The 2.2.6 windows 64bit installer threw a warning at me, that the path would be too long.

I assume it's the environment variable `Path`, which is indeed quite long (1,534 characters).

But since I'm able to extend the content of this variable manually, I wonder why the installer isn't able to append something.

**Comment by freddy961** [comment]
Hey you should try LongPathTool for this problem..

**Comment by CoDEmanX** [comment]
Just want to inform you, that it's still present in 2.5.1 setup.

**Comment by CoDEmanX** [comment]
This is a known issue of NSIS:
https://github.com/dynamorio/drmemory/issues/1029
http://nsis.sourceforge.net/Environmental_Variables:_append,_prepend,_and_remove_entries

There is a special build with long string support:
http://nsis.sourceforge.net/Special_Builds

**Comment by dothebart** [comment]
We tried replacing the dlls with those from the site; The result was that the installer would crash on start.

**Comment by CoDEmanX** [comment]
Any idea why that happened @dothebart?
The path too long-exception is a really ugly problem of NSIS, I see it often during installations...
Could this specific operation be carried out by own code instead?

**Comment by gamicklisafisher** [comment]
Yo should try "Long Path Tool" to handle path too long exception.

**Comment by dothebart** [comment]
@gamicklisafisher do you have any hints on how to use it from nsis? do you have a faq for this?

**Comment by Simran-B** [comment]
I found the following two native code snippets, that are said to circumvent NSIS' string length limitation:

- https://www.smartmontools.org/browser/trunk/smartmontools/os_win32/installer.nsi?rev=4110#L636
- http://stackoverflow.com/a/31342128/2044940

**Comment by dothebart** [comment]
I also now know what caused the installer crashes: we have NSIS plugins which are compiled with old compilers; this doesn't work with the alpha NSIS and causes crashes. 
We need to recompile these plugins in order to use the prerelease NSIS.

**Comment by fceller** [comment]
We switch to a flat directory structure as a workaround.

**Comment by Bearbite** [comment]
Same problem here when I try to install the Client Tools 3.7.11 to Win 10 64bit from the NSIS package.
The installer said: Your PATH environment variable is already too long. The installer is unable to add ArangoDB to it.
Then the installer is stoped without an error code but at approx half of the installation process.
