### ISSUE TITLE
Maximum string value size?

### ISSUE THREAD

**Issue by MrCreosote** [arangodb/arangodb#10754]
This is a question, not a bug report / feature request.

I've been trying to find whether there's a maximum size for string values (e.g., not `_key`s) in ArangoDB, but I can't find anything in the documentation, via Google, or in the issues here. I would think there's some limit - can you tell me what it is if so?

Thanks!

**Comment by jsteemann** [comment]
Database names and collection names have built-in limits of 64 characters. Document keys can be 254 characters long.
Arbitrary string values inside documents have no size limitation, but a few things effectively restrict them:
* when any value is used in a JavaScript context (e.g. via Foxx or any other operation that invokes JavaScript), there is a string size limit of 256MB. This limit affects all JavaScript strings when using the V8 engine (as ArangoDB does). Strings are also used when doing stuff such as `JSON.stringify(...)` from inside JavaScript.
* data type size. We use 4 byte types (e.g.) `uint32_t` in a few places to store sizes. This effectively limits string size to 4 GB
* the RocksDB library also has some limitations for string lengths (for keys and values), and I guess the limit there is actually lower (2 GB??).
* data of transactions is buffered in memory until committed. The overall size of a transaction may also not exceed the limits above.
* huge strings will be slow to parse and copy around, so even if things work properly, using huge strings for attribute names and values will slow down things considerably.
