### ISSUE TITLE
Using external party as authentication service (Auth0 or firebase auth)

### ISSUE THREAD

**Issue by Marnix-IxD** [arangodb/arangodb#10769]
## My Environment

* __ArangoDB Version__:   3.5.3
* __Storage Engine__:    RocksDB
* __Deployment Mode__:    Single server
* __Deployment Strategy__:   Manual start
* __Configuration__:   Most basic install setup
* __Infrastructure__:    Own laptop
* __Operating System__:   Windows 10
* __Total RAM in your machine__:        20Gb
* __Disks in use__:    SSD
* __Used Package__:   Windows Enterprise Edition

## Component, Query & Data

__Desired feature__:
User + session provisioning for arangoDB using authentication methods outside of arangoDB itself. Like for example Auth0 or firebase auth.

## The issue

1. Create a front-end app, with authentication using for example Auth0 / firebase auth, these services return a user with a possibility to get a JWT for that user to your front-end, something that seems to be possible with FOXX microservices too. 
Following instructions on https://github.com/firebase/firebaseui-web quickly sets up this authentication. And you can also extend the JWT with custom claims.

2. I currently have no clue for continuing from this point, I mean I could create a Firebase function that calls a service of my arangoDB environment, store the administrator credentials as as secret on my firebase environment, which allows for creating the user and could possibly return a Bearer Auth token or something, but well that means I can only do this on a real environment which brings around significant hosting costs for something that still requires lots of development and therefor having to constantly deploy to a real environment to test any authenticated parts of my app will be troublesome. 

The other idea I had was setting up a FOXX service, but due to limitations of asynchronous code executing I wasn't sure it would be a massive bottleneck, and other than that authentication and JWT validation is complex so I really don't want to try and invent it for FOXX services.

3. So yeah i'm basically looking for a way to validate a JWT provided by another service.  Comparable to: https://docs.hasura.io/1.0/graphql/manual/auth/authentication/jwt.html

__Problem__:
I've been searching with Google and through the arangoDB docs to find examples on how to do authentication outside of arangoDB using for example a service like auth0 or firebase auth. Make sure that same user account exists in arangoDB and start up a database session with arangoDB based on the JWT token provided by Auth0 or firebase, with possibly extra custom claims. Perhaps someone has done something like this already, or knows documentation that I should look at.

__Expected result__:
Allow for passing JWT to arangoDB with extra details in the custom claims and allow for validating that in a FOXX microservice or at database authentication levels. Using a reference to the key that the JWT has been encrypted with, something like: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com

Anyway, I hope I've been clear enough and someone is able to provide some suggestions / ideas on how to tackle this challenge.

**Comment by KrishnaPG** [comment]
Facing the same issue and looking for information. @Marnix-IxD were you able to solve it? What was the solution?

**Comment by pluma** [comment]
ArangoDB has some support for handling JWT but only supports HMAC-SHA, not encryption: https://www.arangodb.com/docs/stable/appendix-java-script-modules-crypto.html#json-web-tokens-jwt

There's also a module for performing HTTP requests in your Foxx service: https://www.arangodb.com/docs/stable/appendix-java-script-modules-request.html
