### ISSUE TITLE
Query optimization, possible memory leak

### ISSUE THREAD

**Issue by alexander-belikov** [arangodb/arangodb#10776]
## My Environment

* __ArangoDB Version__:       3.4.7
* __Storage Engine__:            RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   ArangoDB Starter
* __Configuration__:               
* __Infrastructure__:               AWS
* __Operating System__:        Ubuntu 16.04
* __Total RAM in your machine__:     32Gb
* __Disks in use__:       HDD/ Elastic
* __Used Package__:    Debian or Ubuntu .deb

__arangod.conf__:
```
[database]
directory = /mnt/data/arango_data


[server]
endpoint = tcp://127.0.0.1:8529
storage-engine = rocksdb

authentication = true 

statistics = false

uid = arangodb


[javascript]
startup-directory = /usr/share/arangodb3/js
app-path = /var/lib/arangodb3-apps

[log]
level = info
file = /var/log/arangodb3/arangod.log

[cluster]

[rocksdb]

block-cache-size = 2576980377  # 15% RAM
total-write-buffer-size = 2576980377  # 15% RAM
enforce-block-cache-size-limit = true

[cache]
size = 2576980377 # 15% RAM

[query]
cache-mode = on
memory-limit = 2576980377 # 15% RAM
```
## Component, Query & Data

__AQL query (if applicable)__:
```
FOR pub IN publications
    LET first = (FOR c IN 1 INBOUND pub publications_publications_edges RETURN c._id)
    FILTER LENGTH(first) > 0
    LET second = (FOR c IN 2 INBOUND pub publications_publications_edges RETURN DISTINCT c._id)
    LET result = {{'pub': pub._key, na: LENGTH(first), 
                    nb: LENGTH(second), f: LENGTH(second)/LENGTH(first)}}
    FILTER result.f > 5.0
    SORT result.f DESC
    LIMIT 100
    RETURN result
```
__Dataset__:
 26M vertices publications and 69M edges publications_publications_edges

__Size of your Dataset on disk__:
no sure how to check that: before import into Arango gzipped csv with edges is 0.6Gb

__Problem__:
Query with the LIMIT of 1M  overflows 16Gb of RAM, so I introduced custom values for 
when block-cache-size,  total-write-buffer-size, [cache] size, memory-limit in arangod.conf.
Experimentally I found that when they are set 15% of 16 Gb the memory usage goes up to 90% and a query with the LIMIT of 10M results in 
`AQL: query would use more memory than allowed (while executing)`

__Expected result__:
Successful completion of the query.

__Details__:
I'm running queries using python-arango (5.2.1)

**Comment by maxkernbach** [comment]
Hi @alexander-belikov,

It seems that the memory consumption of your query exceeds the set value of `query.memory-limit`.

In order to reduce the query memory usage, you could try to use [Streaming AQL Cursors](https://www.arangodb.com/docs/stable/release-notes-new-features34.html#streaming-aql-cursors).

> AQL query cursors created by client applications traditionally executed an AQL query, and built up the entire query result in memory. Once the query completed, the results were sent back to the client application in chunks of configurable size.
> 
> This approach was a good fit for the MMFiles engine with its collection-level locks, and usually smaller-than-RAM query results. For the RocksDB engine with its document-level locks and lock-free reads and potentially huge query results, this approach does not always fit.
> 
> ArangoDB 3.4 allows to optionally execute AQL queries initiated via the cursor API in a streaming fashion. The query result will then be calculated on the fly, and results are sent back to the client application as soon as they become available on the server, even if the query has not yet completed.
> 
> This is especially useful for queries that produce big result sets (e.g. FOR doc IN collection RETURN doc for big collections). Such queries will take very long to complete without streaming, because the entire query result will be computed first and stored in memory. Executing such queries in non-streaming fashion may lead to client applications timing out before receiving the first chunk of data from the server. Additionally, creating a huge query result set on the server may make it run out of memory, which is also undesired. Creating a streaming cursor for such queries will solve both problems.

Streaming can be enabled on a per-query basis by setting the `stream` attribute in the request to the [cursor API](https://www.arangodb.com/docs/3.4/http/aql-query-cursor-accessing-cursors.html#create-cursor) at endpoint `/_api/cursor`.

**Comment by alexander-belikov** [comment]
Thank you for the reply @maxkernbach ! 
Actually in my queries I have already been using stream=True option in aql.execute of python-arango package : https://github.com/joowani/python-arango/blob/a9a465abd60ba80a6a09b6856cf3127a010991b4/arango/aql.py#L142

My expectation is that in a query like mine with FILTER and LIMIT the answer would potentially be truncated dynamically by FILTER and LIMIT contructs, but if it is first computer in full and only then truncated that might explain the problem somewhat. 
Any advice?

**Comment by maxkernbach** [comment]
Hi @alexander-belikov,

The [**Early pruning of non-matching documents**](https://www.arangodb.com/docs/stable/release-notes-new-features36.html#aql) AQL feature, which was introduced in 3.6, might also help in this case.

> Previously, AQL queries with filter conditions that could not be satisfied by any index required all documents to be copied from the storage engine into the AQL scope in order to be fed into the filter.
> ArangoDB 3.6 adds an optimizer rule move-filters-into-enumerate which allows applying the filter condition directly while scanning the documents, so copying of any documents that don’t match the filter condition can be avoided.

Could you check if you are still facing this issue with the latest version 3.6.1?

**Comment by Simran-B** [comment]
Hi @alexander-belikov,
did you have a chance to try the latest 3.6 version to see if the various AQL optimizations help your case?

**Comment by maxkernbach** [comment]
Hi @alexander-belikov,

Since we have not heard back from you in a while, I am closing this ticket.

In case the AQL improvements of latest 3.6 did not help, please comment and we would be glad to investigate this issue.
