### ISSUE TITLE
arangosearch error creating index from definition: failed to load column

### ISSUE THREAD

**Issue by elifriedman** [arangodb/arangodb#10792]
## My Environment

* __ArangoDB Version__:        3.5.3
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start (using systemd)
* __Configuration__:               default settings
* __Infrastructure__:               own
* __Operating System__:        Ubuntu 18.04.3
* __Total RAM in your machine__:        380GB
* __Disks in use__:        SSD
* __Used Package__:              Debian

## Component, Query & Data

__Affected feature__:
ArangoSearch

__Size of your Dataset on disk__:
500GB

## Steps to reproduce
Unknown

__Problem__:

After a database restart, we're getting an error while loading our arangosearch view:

```
2020-01-05T12:35:53Z [3038] ERROR [2885b] {engines} error creating index from definition '
{\n  "primarySort" : [\n  ],\n  "analyzerDefinitions" : [\n    {\n      "name" : "dot_delim",\n      "type" : "delimiter",\n      "properties" : {\n        "delimiter" : "."\n      },\n      "features" : [\n        "position",\n        "norm",\n        "frequency"\n      ]\n    },\n    {\n      "name" : "slash_delim",\n      "type" : "delimiter",\n      "properties" : {\n        "delimiter" : "/"\n      },\n      "features" : [\n        "position",\n        "norm",\n        "frequency"\n      ]\n    },\n    {\n      "name" : "time_delim",\n      "type" : "delimiter",\n      "properties" : {\n        "delimiter" : "T."\n      },\n      "features" : [\n        "position",\n        "norm",\n        "frequency"\n      ]\n    },\n    {\n      "name" : "identity",\n      "type" : "identity",\n      "properties" : {\n      },\n      "features" : [\n        "norm",\n        "frequency"\n      ]\n    }\n  ],\n  "analyzers" : [\n    "identity"\n  ],\n  "fields" : {\n    "timestamp" : {\n      "analyzers" : [\n        "identity",\n        "time_delim"\n      ]\n    },\n    "object_id" : {\n    },\n    "master_proto" : {\n    },\n    "url" : {\n      "analyzers" : [\n        "identity",\n        "dot_delim"\n      ]\n    },\n    "app_proto" : {\n    },\n    "filename" : {\n      "analyzers" : [\n        "identity",\n        "slash_delim",\n        "dot_delim"\n      ]\n    }\n  },\n  "includeAllFields" : false,\n  "trackListPositions" : false,\n  "storeValues" : "none",\n  "id" : "3054617084",\n  "type" : "arangosearch",\n  "view" : "h27D87C09E9A5/3054617083",\n  "objectId" : "3054617086"\n}
': Failed to load column id=0, got invalid properties=125
```

which I assume means that something in the view column properties is corrupted.

We have a backup of the database from a week ago, so we tried to copy the old version of the `arangodb3/databases/database-#########/arangosearch-#########_##########/` folder to our main copy, but we're getting the same error when we restart.

Any way we can either recover the view or create a new view definition and connect it to our backup data, without having to rebuild the whole view?

**Comment by Simran-B** [comment]
@gnusi Are you aware of any bugs that could have caused this? Possibly fixed in newer versions?
