### ISSUE TITLE
Does ArangoSearch support custom analyzer

### ISSUE THREAD

**Issue by jimizai** [arangodb/arangodb#10791]
Dose ArangoSearch support custom analyzer like elasticsearch ?
The analyzer would be better if it could be written in JavaScript

**Comment by dothebart** [comment]
Hi, 
YES! with [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) we added support for custom analyzers.

**Comment by jimizai** [comment]
Thank you. I have been waiting for this feature for a long time
