### ISSUE TITLE
[3.6] expecting 'Object', got: none while handling: UPDATE or REPLACE

### ISSUE THREAD

**Issue by coronabytes** [arangodb/arangodb#10804]
## My Environment

* __ArangoDB Version__:        3.6.0
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               
* __Infrastructure__:               Laptop
* __Operating System__:        Windows 10
* __Total RAM in your machine__:        32Gb
* __Disks in use__:        SSD
* __Used Package__:             Windows

## Component, Query & Data

__Affected feature__:
AQL Update Query

__AQL query (if applicable)__:

```
FOR project IN AProject
FILTER project.Active == true
//LIMIT 70
//LIMIT 70, 100
LET scopedUsage = (
  FOR activity IN AActivity
    FILTER activity.ProjectKey == project._key && activity.Active == true
    COLLECT pkey = activity.ProjectKey, scope = activity.Scope
    AGGREGATE money = SUM(activity.Duration * activity.Rate), time = SUM(activity.Duration)
    RETURN {
        Scope: scope,
        Money: money,
        Time: time
    }
)

//RETURN { _key: project._key, Used: scopedUsage } 
//01c0b724-926a-4557-96e4-30f327767d95	[]
//03906af9-c6eb-4294-84e5-aa3b008d6ab5	[{"Scope":"external","Money":2035.68,"Time":47},{"Scope":"internal","Money":410,"Time":56.25}]
// 134 entries in total

//UPDATE { _key: project._key, Used: null } IN AProject // works
UPDATE { _key: project._key, Used: scopedUsage } IN AProject // ERROR expecting 'Object', got: none while handling: UPDATE or REPLACE (while executing)
//UPDATE { _key: project._key, Used: [] } IN AProject // works
//UPDATE { _key: project._key, Used: [{"Scope":"external","Money":2035.68,"Time":47},{"Scope":"internal","Money":410,"Time":56.25}] } IN AProject // works
```

__AQL explain (if applicable)__:

```
Execution plan:
 Id   NodeType                   Est.   Comment
  1   SingletonNode                 1   * ROOT
  2   EnumerateCollectionNode     135     - FOR project IN AProject   /* full collection scan */   FILTER (project.`Active` == true)   /* early pruning */
 22   SubqueryStartNode           135       - LET scopedUsage = ( /* subquery begin */
 20   IndexNode                 47385         - FOR activity IN AActivity   /* hash index scan, projections: `Rate`, `Active`, `Duration`, `ProjectKey`, `Scope` */    FILTER (activity.`Active` == true)   /* early pruning */   
  9   CalculationNode           47385           - LET #15 = activity.`ProjectKey`   /* attribute expression */   /* collections used: activity : AActivity */
 10   CalculationNode           47385           - LET #17 = activity.`Scope`   /* attribute expression */   /* collections used: activity : AActivity */
 11   CalculationNode           47385           - LET #19 = (activity.`Duration` * activity.`Rate`)   /* simple expression */   /* collections used: activity : AActivity */
 12   CalculationNode           47385           - LET #21 = activity.`Duration`   /* attribute expression */   /* collections used: activity : AActivity */
 13   CollectNode               37908           - COLLECT pkey = #15, scope = #17 AGGREGATE money = SUM(#19), time = SUM(#21)   /* sorted */
 14   CalculationNode           37908           - LET #23 = { "Scope" : scope, "Money" : money, "Time" : time }   /* simple expression */
 23   SubqueryEndNode           37908       - RETURN  #23 ) /* subquery end */
 17   CalculationNode           37908       - LET #25 = { "_key" : project.`_key`, "Used" : scopedUsage }   /* simple expression */   /* collections used: project : AProject */
 18   UpdateNode                    0       - UPDATE #25 IN AProject 

Indexes used:
 By   Name                      Type      Collection   Unique   Sparse   Selectivity   Fields                      Ranges
 20   idx_1655166839731257344   hash      AActivity    false    false         2.01 %   [ `ProjectKey`, `Scope` ]   (activity.`ProjectKey` == project.`_key`)
 18   primary                   primary   AProject     true     false       100.00 %   [ `_key` ]                  #25

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   move-calculations-up-2
  4   move-filters-up-2
  5   remove-data-modification-out-variables
  6   use-indexes
  7   remove-filter-covered-by-index
  8   use-index-for-sort
  9   reduce-extraction-to-projection
 10   move-filters-into-enumerate
 11   splice-subqueries

Write query options:
 Option                   Value
 ignoreErrors             false
 waitForSync              false
 nullMeansRemove          false
 mergeObjects             true
 ignoreDocumentNotFound   false
 readCompleteInput        true
 useIsRestore             false
 consultAqlWriteFilter    false
 exclusive                false
 overwrite                false
 ignoreRevs               true

```

__Problem__:
Query ran just fine in 3.5, however in 3.6 produces "expecting 'Object', got: none while handling: UPDATE or REPLACE (while executing)"

Interesting fact: it runs when I split the query size in 2 with
LIMIT 70
LIMIT 70, 100

Total entries is 134 projects
it also works with the commented out update statements

**Comment by markuspf** [comment]
Can you try running the query with subquery splicing disabled, i.e. using `{ optimizer: { rules: [ "-splice-subqueries" ] } }`? This should work as a work-around for your issue.

The `LIMIT` split helps likely because `LIMIT` statements have the same effect (they disable subquery splicing).

A fix should appear in the next (minor) release.

**Comment by coronabytes** [comment]
Yes, disabling splice-subqueries allows the query to run.

**Comment by epluribusunix** [comment]
I am also seeing this error, but with an update, not just a query:
```
LET tenMin = (10 * 60 * 1000)
LET now = DATE_NOW()
FOR a IN Computers
    FILTER (a.cached || 0) < (now - tenMin)
    LIMIT 100
    LET tags = (
        FOR tt IN TagTypes
            FOR v,e IN INBOUND SHORTEST_PATH a TO tt
                GRAPH 'Tagging_graph'
                FILTER IS_SAME_COLLECTION(v, 'TagValues')
                RETURN v._id
    )
    LET u = {
        _key: a._key,
        tags: tags,
        cached: DATE_NOW()
    }
    UPDATE u IN Computers OPTIONS { optimizer: { rules: [ "-splice-subqueries" ] } }
```
Changing the upper `LIMIT` to 10, there is no error, but almost anything higher returns the `expecting 'Object', got: none...` message.  No change in behavior by adding options to the update statement.

However, removing the `UPDATE` and returning `u` will not return an error, no matter what size the `LIMIT` is.

**Comment by coronabytes** [comment]
This issue was already concering an UPDATE....

Specifying OPTIONS { optimizer: { rules: [ "-splice-subqueries" ] } } in the AQL did not work for me either. I had to to modify my driver to deliver the "Extra" json options.

There is a cmd line parameter though. (--query.optimizer-rules "-splice-subqueries")

**Comment by jsteemann** [comment]
@coronabytes : just to confirm this, AQL query optimizer rules cannot be turned off from within an AQL query string (i.e. using the `OPTIONS` directive. 

It is supported to turn them off when passing the options as an extra parameter to the query/cursor REST API at https://www.arangodb.com/docs/stable/http/aql-query-cursor-accessing-cursors.html#create-cursor, or by setting a command-line option at server startup as you said.

**Comment by epluribusunix** [comment]
Sorry!  I didn't see the un-commented `UPDATE` line in the original post.  (attention to detail... FTW!)

But thank you @coronabytes and @jsteemann for the tip about how to apply the fix.

**Comment by maxkernbach** [comment]
Hi @coronabytes and @epluribusunix,

Version 3.6.1, which includes a fix for the reported bug has just been released.
In case the issue persists, please comment and we will reopen this ticket.

Please find the latest release in the [download section](https://www.arangodb.com/download/).
