### ISSUE TITLE
Can not use 'in' operator in traveling aql .

### ISSUE THREAD

**Issue by TsaiQi** [arangodb/arangodb#10803]
## My Environment

* __ArangoDB Version__:        
* __Storage Engine__:             
* __Deployment Mode__:       
* __Deployment Strategy__:   
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:        
* __Total RAM in your machine__:        
* __Disks in use__:        
* __Used Package__:              

## Component, Query & Data

__Affected feature__:

__AQL query (if applicable)__:
```
//section 1
with DOC
let x = (
  for v,e,p in 2 outbound 'DOC/0' EDGE
    filter p.edges[1]._to == 'DOC/1'
    return p.vertices[1]._id
)
//section 2
for v,e,p in 2 outbound 'DOC/3' EDGE
  filter p.edges[1]._to in x // <--
  return p.vertices[1]._id
```

__AQL explain (if applicable)__:

__Dataset__:

// This dataset information is not the practical using dataset (huge size) but for descripting the issue. I am not sure wether this problem is related to the size of dataset .

// collection DOC
[
{_id:'DOC/0'},
{_id:'DOC/1'},
{_id:'DOC/2'},
{_id:'DOC/3'},
{_id:'DOC/4'},
{_id:'DOC/5'},
{_id:'DOC/6'},
{_id:'DOC/7'},
{_id:'DOC/8'},
{_id:'DOC/9'}
]

// edge EDGE
[
{_id:'EDGE/0',_from:'DOC/0',_to:'DOC/5'},
{_id:'EDGE/1',_from:'DOC/0',_to:'DOC/6'},
{_id:'EDGE/2',_from:'DOC/5',_to:'DOC/1'},
{_id:'EDGE/3',_from:'DOC/3',_to:'DOC/7'},
{_id:'EDGE/4',_from:'DOC/3',_to:'DOC/8'},
{_id:'EDGE/5',_from:'DOC/3',_to:'DOC/9'},
{_id:'EDGE/6',_from:'DOC/7',_to:'DOC/5'},
{_id:'EDGE/7',_from:'DOC/8',_to:'DOC/5'},
{_id:'EDGE/8',_from:'DOC/9',_to:'DOC/6'}
]

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. 
2. 
3. 

__Problem__:
The AQL is executed correctly, but the returned array is empty.  If I execute section 1 separately I can get array x with its size more than 1. If I copy one of values in array x  (example as 'DOC/5' with index 0 ) and replace the filter condition 'in x ' with 'in ["DOC/5"]' or '== x[0]' , I can get correct result (not empty). But it can not work when using 'in x'.

For given dataset here , the correct result should be ['DOC/7','DOC/8'] and x is ['DOC/5'].

__Expected result__:
Correct result that not empty like use " == x[0]".
For given dataset here , the correct result should be ['DOC/7','DOC/8'] and x is ['DOC/5'].

**Comment by Simran-B** [comment]
Please provide a dataset that reproduces the problem.

What strikes me is that you use a min/max traversal depth of 2 in both cases, but you return the vertex ID from depth 1, whereas the filter condition tests the edge at depth 2. Is that really what you want to do?

```
//section 1
with DOC
let x = (
  for v,e,p in 2 outbound 'DOC/0' EDGE
    filter p.edges[0]._to == 'DOC/1' (first edge)
    return p.vertices[2]._id // 'DOC/2'? (p.vertices[0] is the start vertex 'DOC/0')
)
//section 2
for v,e,p in 2 outbound 'DOC/3' EDGE
  filter p.edges[ /* ? */ ]._to in x // which of the two edges do you mean to filter on?
  return p.vertices[2]._id
```

**Comment by OmarAyo** [comment]
Hi @TsaiQi,

Did you have the chance to read Simran-B's message ?

Best,

**Comment by TsaiQi** [comment]
> Please provide a dataset that reproduces the problem.
> 
> What strikes me is that you use a min/max traversal depth of 2 in both cases, but you return the vertex ID from depth 1, whereas the filter condition tests the edge at depth 2. Is that really what you want to do?
> 
> ```
> //section 1
> with DOC
> let x = (
>   for v,e,p in 2 outbound 'DOC/0' EDGE
>     filter p.edges[0]._to == 'DOC/1' (first edge)
>     return p.vertices[2]._id // 'DOC/2'? (p.vertices[0] is the start vertex 'DOC/0')
> )
> //section 2
> for v,e,p in 2 outbound 'DOC/3' EDGE
>   filter p.edges[ /* ? */ ]._to in x // which of the two edges do you mean to filter on?
>   return p.vertices[2]._id
> ```
I update my issue and give the dataset related to the AQL .But the AQL in your comment is wrong (maybe you see it before my first update) .

The correct AQL is as following:

//section 1
with DOC
let x = (
  for v,e,p in 2 outbound 'DOC/0' EDGE
    filter p.edges[1]._to == 'DOC/1' // the second edge (EDGE/2)
    return p.vertices[1]._id // the second vertice (DOC/5)
)
//section 2
for v,e,p in 2 outbound 'DOC/3' EDGE
  filter p.edges[1]._to in x //  x == ['DOC/5'] 
  return p.vertices[1]._id // the second vertice (['DOC/7','DOC/8'])

**Comment by Simran-B** [comment]
So this is what your dataset looks like? @TsaiQi 
```
(DOC/0) --[EDGE/?]--> (DOC/5) --[EDGE/2]--> (DOC/1)
(DOC/3) --[EDGE/?]--> (DOC/7) --[EDGE/?]--> (DOC/5)
(DOC/3) --[EDGE/?]--> (DOC/8) --[EDGE/?]--> (DOC/5)
```

**Comment by TsaiQi** [comment]
> So this is what your dataset looks like? @TsaiQi
> 
> ```
> (DOC/0) --[EDGE/?]--> (DOC/5) --[EDGE/2]--> (DOC/1)
> (DOC/3) --[EDGE/?]--> (DOC/7) --[EDGE/?]--> (DOC/5)
> (DOC/3) --[EDGE/?]--> (DOC/8) --[EDGE/?]--> (DOC/5)
> ```

Yes , but the AQL return an empty array .

**Comment by Simran-B** [comment]
I created a document collection `DOC` and an edge collection `EDGE`, then ran the following AQL queries:

```
for d in [
{_key:'0'},
{_key:'1'},
{_key:'2'},
{_key:'3'},
{_key:'4'},
{_key:'5'},
{_key:'6'},
{_key:'7'},
{_key:'8'},
{_key:'9'}
] insert d into DOC
```

```
for d in [
{_key:'0',_from:'DOC/0',_to:'DOC/5'},
{_key:'1',_from:'DOC/0',_to:'DOC/6'},
{_key:'2',_from:'DOC/5',_to:'DOC/1'},
{_key:'3',_from:'DOC/3',_to:'DOC/7'},
{_key:'4',_from:'DOC/3',_to:'DOC/8'},
{_key:'5',_from:'DOC/3',_to:'DOC/9'},
{_key:'6',_from:'DOC/7',_to:'DOC/5'},
{_key:'7',_from:'DOC/8',_to:'DOC/5'},
{_key:'8',_from:'DOC/9',_to:'DOC/6'}
] insert d into EDGE
```

Note that I modified your provided dataset example to use a `_key` attribute, not an `_id` which will be ignored.

In the graph viewer I verified that everything is connected correctly by creating a named graph:

![image](https://user-images.githubusercontent.com/7819991/74340547-62758400-4da6-11ea-850c-9f8c9b9ec59b.png)

After clicking the "Fetch full graph" button:

![image](https://user-images.githubusercontent.com/7819991/74340134-ac119f00-4da5-11ea-97f2-10a197affe43.png)

Then I ran your query:

```js
with DOC
let x = (
for v,e,p in 2 outbound 'DOC/0' EDGE
filter p.edges[1]._to == 'DOC/1' // the second edge (EDGE/2)
return p.vertices[1]._id // the second vertex (DOC/5)
)
for v,e,p in 2 outbound 'DOC/3' EDGE
filter p.edges[1]._to in x // x == ['DOC/5']
return p.vertices[1]._id // the second vertex (['DOC/7','DOC/8'])
```

It returns the expected result (DOC 7 and 8):

![image](https://user-images.githubusercontent.com/7819991/74340405-20e4d900-4da6-11ea-8a86-8705c6e6832d.png)

I used a single server instance of ArangoDB v3.6.1 under Windows for my test.

@TsaiQi Please check that your vertices and edges have the correct `_key` values. If they do, please let me know which ArangoDB version you are using and in what deployment type and under what OS. Give the latest 3.6.1 a try and see if the problem still occurs there.

**Comment by maxkernbach** [comment]
Hi @TsaiQi,

Did you have a chance to read Simran's latest reply?

> Please check that your vertices and edges have the correct _key values. If they do, please let me know which ArangoDB version you are using and in what deployment type and under what OS. Give the latest 3.6.1 a try and see if the problem still occurs there.

**Comment by maxkernbach** [comment]
Hi @TsaiQi,

Since we have not heard back from you recently, I am closing this issue for now.
Feel free to reopen this ticket if needed.
