### ISSUE TITLE
After upgrade from 3.5.3 to 3.6.0 ArangoDB often restart after several minutes

### ISSUE THREAD

**Issue by sonyarianto** [arangodb/arangodb#10845]
## My Environment

* __ArangoDB Version__:       3.6.0 (from 3.5.3 in-place upgrade)
* __Storage Engine__:             Rocks DB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   systemctl start arangodb3
* __Configuration__:               nothing special
* __Infrastructure__:               own (bare metal)
* __Operating System__:        CentOS Linux release 7.7.1908 (Core)
* __Total RAM in your machine__:        24GB
* __Disks in use__:        HDD
* __Used Package__:              default repository

## Steps to reproduce

I upgrade from 3.5.3 to 3.6.0 with inplace upgrade. I change the yum repo definitions from 35 to 36. Stop ArangoDB and do yum update, it will update to ArangoDB 3.6.0 and I start with systemctl start arangodb3

__Problem__:
I notice several minutes (around 3 minutes) server will restart and it happen on every around 3-5 minutes. I check log but I can't found any useful information to report. On the log only there is something like LOCK from previous PID that already dead.

__Expected result__:
Should be normal and smooth like my previous 3.5.3

My Workaround now is:
- I downgrade from 3.6.0 to 3.5.3 and now run smooth again
- But the database is already upgraded to 3.6.0 so on the log I see something that mention database version difference, but so far the server running well.

Please help :)

**Comment by arloliu** [comment]
Met this problem today.
Any sub queries will cause arangodb process crash with no error log.
Only log appears is the LOCK pid from previous after restart arangodb.

**Comment by sonyarianto** [comment]
@arloliu so do you have solution for 3.6.0? I am downgrade to 3.5.3 and that problem gone.

**Comment by jsteemann** [comment]
@arloliu : thanks for adding this. You are stating that "Any sub queries" will cause ArangoDB to crash. Is it possible to share a bit more details here, e.g. a few example query strings plus the setup you are using (single server/cluster, community/enterprise version, operating system, docker/kubernetes etc.)? 
Thanks in advance!

**Comment by sonyarianto** [comment]
@jsteemann where to look for detailed log? I want to investigate this as well, is changing log level can help?

@arloliu Do you run sub-query via ArangoDB Web UI or from application?

**Comment by jsteemann** [comment]
@sonyarianto : if you get arangod to crash, there will likely not be any log messages available that would help with analyzing the crashes. A crash is unintended, so likely no logging will be involved here.

If the issue is actually subquery-related, what may help is to turn off certain subquery processing globally. This can be done by adding a startup option for single servers or coordinators. 
The arangod option is `--query.optimizer-rules "-splice-subqueries"`, the equivalent option for the arangodb starter is `--coordinators.query.optimizer-rules="-splice-subqueries".

**Comment by arloliu** [comment]
> @jsteemann where to look for detailed log? I want to investigate this as well, is changing log level can help?
> 
> @arloliu Do you run sub-query via ArangoDB Web UI or from application?

I run sub-query in application via arangojs driver. AQL query without sub query seems fine,
and some sub-queries make arangodb crash. But I haven't found the pattern yet.

**Comment by jsteemann** [comment]
@arloliu : is there any chance of sharing at least the query strings of some of the subqueries?

In addition, the issue may be mitigated by doing this (temporarily):

> If the issue is actually subquery-related, what may help is to turn off certain subquery processing globally. This can be done by adding a startup option for single servers or coordinators.
The arangod option is --query.optimizer-rules "-splice-subqueries", the equivalent option for the arangodb starter is `--coordinators.query.optimizer-rules="-splice-subqueries".

**Comment by jsteemann** [comment]
@sonyarianto : this switch only affects subqueries, and it switches the subquery execution back to the 3.5 way. This will have an effect on the performance, but the subquery performance should be on par with 3.5 then. That optimizer rule was supposed to speed up subqueries compared to 3.5, but it seems to have an issue that is currently investigated. To be on the safe side, it can be turned off temporarily, meaning that subqueries will be executed in the same way they were in 3.5.

**Comment by sonyarianto** [comment]
@jsteemann that's great answer and I am happy. Thanks.
In addition to my crash case, I upgrade from 3.5.3 to 3.6.0 several days ago and I didn't notice the crash until I saw when I access my website (that using ArangoDB as database) and it intermittently output blank, but when I refresh again it normal again, I thought because of internet or the PHP itself. Then someday I open ArangoDB Web UI to check some data and there I got often lost connection error, and then I checked on log and it seems the ArangoDB is often restarted and no detail info about the crash.

My application is based on PHP (latest version 7.4.x) and connect to ArangoDB using php-arangodb library via composer and I always update it using the latest version. On php-arangodb I always use the AQL statement to query to database, not using the ORM style.

In addition to subquery, I am not using subquery that "too advanced", maybe just ordinary sub-query based on many simple example on the ArangoDB docs.

some of my aql is like below:
```
FOR ps IN table_name
													  FILTER 
													  ps.slug == @slug &&
													  ps._key == @key &&
													  ps.is_active == 1
													  RETURN
					                                  { "source_id": ps.source_id,
														"story_source": 
														( RETURN 
														  KEEP(DOCUMENT(CONCAT("story_sources/", ps.source_id)), 
														       "_key", 
														       "name", 
														       "slug")
														)[0],
														"title": ps.title,
														"link": ps.link,
														"published_datetime_utc": ps.published_datetime_utc,
														"short_content": ps.short_content,
														"image": ps.image,
														"slug": ps.slug,
														"key": ps._key
													  }
```

Thanks i advance

**Comment by sonyarianto** [comment]
@jsteemann 
So in my setting on CentOS service to start the ArangoDB I will add like this? Just to make sure.
```
ExecStart=/usr/bin/numactl --interleave=all /usr/sbin/arangod --pid-file /var/run/arangodb3/arangod.pid --temp.path /var/tmp/arangodb3 --log.foreground-tty true --query.optimizer-rules "-splice-subqueries"
```
correct me if Iam wrong.

**Comment by jsteemann** [comment]
@sonyarianto : that command looks good!

**Comment by jsteemann** [comment]
Looking at the query in https://github.com/arangodb/arangodb/issues/10845#issuecomment-575547509, I don't think this is causing crashes. I tried the query myself on a local dataset, and it worked fine. Additionally, that query doesn't use the subquery-splicing optimization that we suspect is the source of crashes.
Are there other queries containing subqueries that could be the source of the problem?

**Comment by sonyarianto** [comment]
@jsteemann ic ic, I don't have any other query that seems have problem and I am become more curious. OK tonight or tommorow I will try to upgrade to 3.6.0 with that new option and see how it behave directly on production. I am afraid that other than sub-query also produce this crash.

@arloliu if you send sample query that make the crash would be lovely.

**Comment by jsteemann** [comment]
@sonyarianto : thanks. Fingers crossed it doesn't crash anymore in 3.6.0 with the option enabled!

**Comment by dbenesj** [comment]
@jsteemann I am facing the same problem. By simplifying AQL more and more I end up with following query that crashes ArangoDB when submitted from Web UI:
```
LET results = (
  FOR p IN crash_test
  SEARCH ANALYZER(p.name IN ["test"], 'text_en')
  SORT BM25(p) DESC
  RETURN p
)

FOR p IN results
  LET validFrom = (
    RETURN IS_NULL(p.valid_from) ? 0 : p.valid_from
  )
  LET validTo = (
    RETURN IS_NULL(p.valid_to) ? 253370764800000 : p.valid_to
  )
  LET inactive = (
    RETURN (validFrom[0] > 1579279781654 || validTo[0] < 1579279781654)
  )

  //following one crashes
  RETURN (inactive[0]) ? MERGE(p, {"inactive": true } ) : p
  //following runs fine
  //RETURN p
  //RETURN MERGE(p, {"inactive": true })
```
view `crash_test` is defined as follows (just one link added everything else is default):
```
{
  "writebufferIdle": 64,
  "writebufferSizeMax": 33554432,
  "consolidationPolicy": {
    "type": "tier",
    "segmentsBytesFloor": 2097152,
    "segmentsBytesMax": 5368709120,
    "segmentsMax": 10,
    "segmentsMin": 1,
    "minScore": 0
  },
  "primarySort": [],
  "globallyUniqueId": "hB87DF0A6BD19/27052693",
  "id": "27052693",
  "writebufferActive": 0,
  "consolidationIntervalMsec": 10000,
  "cleanupIntervalStep": 2,
  "commitIntervalMsec": 1000,
  "links": {
    "crash_collection": {
      "analyzers": [
        "identity"
      ],
      "fields": {
        "name": {
          "analyzers": [
            "text_en",
            "identity"
          ]
        }
      },
      "includeAllFields": false,
      "storeValues": "none",
      "trackListPositions": false
    }
  },
  "type": "arangosearch"
}
```
collection `crash_collection` contains only one very simple document:
```
{
  "name": "test"
}
```

**Comment by sonyarianto** [comment]
@jsteemann bad luck for me, I already try to upgrade from 3.5.3 to 3.6.0 with option `--query.optimizer-rules "-splice-subqueries"` but still my ArangoDB crash several times. I think I will stick with 3.5 family for the time being until.... I don't know.

**Comment by jsteemann** [comment]
@sonyarianto : yes, bad luck... Sorry for that. But I was already suspecting something else than the above query you posted to be the problem cause. The query above doesn't use the subquery optimization, so it's either a different query triggering the problem or something else. If you turned off subquery optimizations entirely at startup, it's potentially something totally different.

**Comment by jsteemann** [comment]
@dbenesj : thanks for supplying this query. I can reproduce the issue locally. Investigating...

**Comment by jsteemann** [comment]
@dbenesj : I created a bugfix PR for your specific issue: https://github.com/arangodb/arangodb/pull/10923
The problem occurred when there was a view in the query plus there were extra subqueries that did not include FOR loops themselves.
By the way, instead of writing
```
  LET inactive = (
    RETURN (validFrom[0] > 1579279781654 || validTo[0] < 1579279781654)
  )
```
and later filtering/testing on `inactive[0]`, you could simply write
```
  LET inactive = (validFrom[0] > 1579279781654 || validTo[0] < 1579279781654)
```
and then filter/test the value of `inactive`. This will also make the query more efficient.

**Comment by OmarAyo** [comment]
Hi @sonyarianto 

Would it be possible for you to generate a core dump by following these instructions:
- https://github.com/arangodb/arangodb/blob/devel/README_maintainers.md#debugging

Best,

**Comment by sonyarianto** [comment]
@OmarAyo thanks for the core dump way. I need to take time to try this. Thank you very much.

**Comment by sonyarianto** [comment]
@jsteemann just to tell you, today I upgrade from 3.5.3 to 3.5.4 and it run smoothly on production. Sweet. Thank you.

**Comment by dbenesj** [comment]
@jsteemann Thank you very much for the fix and also tips how to improve queries :+1: 

I have found one more case where it was crashing ArangoDB 3.6 (3.5 is running fine) and just want to make sure it is the same case that is being fixed.
```
LET all_results = (
  FOR doc IN crash_collection
    RETURN doc
)
LET results_to_return = (
  FOR doc2 IN all_results
    SORT doc2._key
    LIMIT 0,20
    LET doc2_with_active_indicator = (
      LET has_active_link  = (
        FOR doc3 IN crash_collection3
          FILTER doc3._from == doc2._id AND DATE_TIMESTAMP(doc3.start) <= DATE_NOW() AND HAS(doc3,"end") == false
          RETURN 1
      )
      RETURN MERGE(doc2, {"_isActive": (TO_BOOL(LENGTH(has_active_link) >= 1)) } )
    )[0]
    RETURN doc2_with_active_indicator
)

RETURN {"results":results_to_return}
```
`crash_collection` is a document collection and `crash_collection3` is edge collection, both are empty

**Comment by jsteemann** [comment]
@dbenesj : Thanks for providing the query. I just tried it and found that it works in the current `3.6` branch, but crashes with `v3.6.0` as you reported. The issue was fixed in the `3.6` branch via commit https://github.com/arangodb/arangodb/commit/917b91c061890b9cbba7679dc975042f9324d7eb.
The fix will be included in `v3.6.1`.

**Comment by sonyarianto** [comment]
@jsteemann @OmarAyo 
Hi Jan, today I upgrade from 3.5.4 to 3.6.1 and seems VERY OK using splice subqueries active :) No crash so far like before on 3.6.0. I am very happy. Good job ArangoDB team :)

So I will close this issue now.

**Comment by dbenesj** [comment]
Thank you for fixes!
I can also confirm, that version 3.6.1 is running solid when our application is querying it
