### ISSUE TITLE
WebUI - Clicking an edge in the graph view does not open the circle menu

### ISSUE THREAD

**Issue by jspitz-git** [arangodb/arangodb#10863]
## My Environment

* __ArangoDB Version__:        3.6.0
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Windows service
* __Configuration__:               nothing special
* __Infrastructure__:               own
* __Operating System__:        Windows 10
* __Total RAM in your machine__:        16 GB
* __Disks in use__:        HDD
* __Used Package__:              Official server installation package (ArangoDB3-3.6.0_win64.exe)

## Component, Query & Data

__Affected feature__:
Web interface

## Steps to reproduce

1. Create the simpliest graph consisting of two vertices and one edge.
2. Open the graph view of the graph.
3. Click the edge.

__Problem__:
The circle menu enabling editing or deleting the edge does not appear.

__Expected result__:
Appearing of the menu enabling editing or deleting the edge. It worked in the 3.5.3 version.

**Comment by maxkernbach** [comment]
Hi @jspitz-git,

Thanks for reporting this bug. It is easy to reproduce with the reported steps.

**Comment by maxkernbach** [comment]
Hi @jspitz-git,

Version 3.6.4, which includes a fix for this issue, has been released.

From the [Changelog](https://github.com/arangodb/arangodb/blob/25e711db88b5f43915cf61b2e895fe9e86b35051/CHANGELOG#L84):

> Fixed ability to edit graph edge in Graph Viewer of web UI.

Please find the latest release in the [download section](https://www.arangodb.com/download/).
