### ISSUE TITLE
arangod based binaries lack product version info and icon on Windows

### ISSUE THREAD

**Issue by Simran-B** [arangodb/arangodb#10867]
In the 3.6.0 Windows package, the client-tools have version information + icon, but the arangod based binaries do not:

![image](https://user-images.githubusercontent.com/7819991/72284312-f8e84580-3640-11ea-8428-68206ac79efd.png)

![image](https://user-images.githubusercontent.com/7819991/72284467-4fee1a80-3641-11ea-9d20-2290ff5571d7.png) ![image](https://user-images.githubusercontent.com/7819991/72284477-57152880-3641-11ea-8f48-49c0c32b5af9.png)

(Starter is neither arangod nor arangosh based, but also has no icon and product information.)

```cmake
if (MSVC AND NOT(SKIP_PACKAGING))
  generate_product_version(ProductVersionFiles
    NAME arangod
    FILE_DESCRIPTION ${ARANGODB_FRIENDLY_STRING}
    ICON ${ARANGO_ICON}
    VERSION_MAJOR ${CPACK_PACKAGE_VERSION_MAJOR}
    VERSION_MINOR ${CPACK_PACKAGE_VERSION_MINOR}
    VERSION_PATCH ${CPACK_PACKAGE_VERSION_PATCH}
    VERSION_REVISION ${BUILD_ID}
  )
endif ()

# ...

add_library(arangoserver STATIC
  ${LIB_ARANGOSERVER_SOURCES}
  ${ADDITIONAL_LIB_ARANGOSERVER_SOURCES}
  ${ProductVersionFiles} # <----------------
)

# ...

add_executable(${BIN_ARANGOD}
  RestServer/arangod.cpp
)
```

https://github.com/arangodb/arangodb/blob/devel/arangod/CMakeLists.txt#L787

```cmake
if (MSVC AND NOT(SKIP_PACKAGING))
  generate_product_version(ProductVersionFiles_arangosh
    NAME arangosh
    FILE_DESCRIPTION ${ARANGOSH_FRIENDLY_STRING}
    ICON ${ARANGO_ICON}
    VERSION_MAJOR ${CPACK_PACKAGE_VERSION_MAJOR}
    VERSION_MINOR ${CPACK_PACKAGE_VERSION_MINOR}
    VERSION_PATCH ${CPACK_PACKAGE_VERSION_PATCH}
    VERSION_REVISION ${BUILD_ID}
  )
endif ()

add_executable(${BIN_ARANGOSH}
  ${ProductVersionFiles_arangosh} # <-----------------
  # ...
)
```

https://github.com/arangodb/arangodb/blob/devel/arangosh/CMakeLists.txt#L392

The reason could simply be that the product version files are added in the wrong place, to the server library instead of the executable.

**Comment by Simran-B** [comment]
Fixed for me with a tiny change: https://github.com/arangodb/arangodb/pull/10868

![image](https://user-images.githubusercontent.com/7819991/72296089-1f19df80-3659-11ea-9ac7-f4b95a29554d.png)

![image](https://user-images.githubusercontent.com/7819991/72296103-280ab100-3659-11ea-8bf9-2e4ba5e6f921.png)

**Comment by dothebart** [comment]
this probably broke when splitting arangod - should be right for all arangosh/* binaries? Please backport to the branches - discuss with @KVS85

**Comment by Simran-B** [comment]
The client tools have their icons and product info (I compared the NSIS code between arangod and arangosh to fix the server). arangoinspect and foxx-manager use the arangosh description, but that should be okay:

![image](https://user-images.githubusercontent.com/7819991/72423949-76b56980-3785-11ea-991f-166455ed1e0a.png)

**Comment by Simran-B** [comment]
Was fixed back in January for
- 3.4 https://github.com/arangodb/arangodb/pull/10881
- 3.5 https://github.com/arangodb/arangodb/pull/10880
- 3.6 https://github.com/arangodb/arangodb/pull/10868
- devel https://github.com/arangodb/arangodb/pull/10869
