### ISSUE TITLE
expired apt signing key

### ISSUE THREAD

**Issue by vkunz** [arangodb/arangodb#1088]
Hi,

the current apt signing key (1024D/1C42E360) expired a couple days ago (expired: 2014-11-03).

As a consequence, apt refuses to read the repository index file.

Please consider repackaging/resigning the repository/package.

vkunz

**Comment by millette** [comment]
Has the pgp key expired again?

Arrango was already installed, aptitude complained about an expired key.

I fetched and added https://www.arangodb.com/repositories/arangodb31/Debian_8.0/Release.key again (extract below):

```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v2

mQINBFVtxt4BEAC4fnctqB2hfUi5SYzqeY3GOxo5Mj5jmqaxxNamO+qbsJpLarAn
JnA2+TuH+HOdsZeqFHX1dVL0cmxgEq1Lm+vHgHVj/99O/KF/zCktLlk1qh20/3Qf
...
wye+UAO89hOjHlVerdfwUzQleewCLC2PWnd6QcBJVpHU9K6TDUe+E3n4US9R2bPp
eY60c0UBI3e1V9jpwGFp4Kel/usbaV+DpV6etF0+tIJsxgEEFTDHOA==
=7TM0
-----END PGP PUBLIC KEY BLOCK-----
```

Still getting this error:
> W: Erreur de GPG : http://www.arangodb.com  Release : Les signatures suivantes ne sont pas valables : KEYEXPIRED 1484090025

**Comment by vkunz** [comment]
hi,

I imported said key into a fresh truststore, and according to gpg this key expires on 2019-06-01.

Maybe another key has expired?

While checking my own apt keys, I found one expired on 2017-01-10:
4497 DA50 FBD0 158C CFD1  996C EE61 1E13 1C42 E360

Maybe apt is complaining about this one?

vkunz

**Comment by millette** [comment]
Probably something I'm doing wrong. I tried to delete (apt-key del ...) the expired key, but it outputs "OK" whatever keyid I give it, so I'm not sure it's working. I'm not currently using arango so for now I removed the apt/sources.list.d/FILE to get rid of the warning. I'm not used to manually dealing with package keys.
