### ISSUE TITLE
Query that worked in 3.5/3.4 does not work in 3.6

### ISSUE THREAD

**Issue by dvzubarev** [arangodb/arangodb#10907]
## My Environment

* __ArangoDB Version__:        3.6.0
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               nothing special
* __Infrastructure__:               own
* __Operating System__:        Debian 10
* __Total RAM in your machine__:        32Gb.
* __Disks in use__:        SSD
* __Used Package__:       Debian or Ubuntu .deb

## Component, Query & Data

__Affected feature__:
 AQL query using web interface 

__AQL query (if applicable)__:  Please see Debug Package: https://yadi.sk/d/V11EhzApPN1QOA

## Steps to reproduce

1. Execute the query from Debug Package

__Problem__:
AQL: collection or array expected as operand to FOR loop; you provided a value of type 'none'

__Expected result__:
The same query works on the same collection using arangodb 3.5.3 and 3.4.7

__Notes__:
If I change the order of sub-queries (`tuples` and `temps`), than the whole query works.

**Comment by hkernbach** [comment]
@dvzubarev It would be awesome if you could also supply a small (anonymised) dataset, so we're able to reproduce your issue faster. Many thanks in advance!

**Comment by dvzubarev** [comment]
I can reproduce the issue on this dataset: https://yadi.sk/d/WRuz9IdYFMvt_w

**Comment by hkernbach** [comment]
Thank you very much! We already had found a similar problem and double-checked with your query and dataset. That issue is already fixed in our repository and will be officially fixed in the upcoming  3.6.1 release. 

If you're more interested in technical insights. The PR that solved your issue is:
https://github.com/arangodb/arangodb/pull/10889
