### ISSUE TITLE
Foxx wont load joi from arango

### ISSUE THREAD

**Issue by DaveM2011** [arangodb/arangodb#10946]
## My Environment

* __ArangoDB Version__: 3.6.0
* __Storage Engine__:  RocksDB 
* __Deployment Mode__: Single Server
* __Deployment Strategy__:  Manual Start in Docker
* __Configuration__: Not applicable
* __Infrastructure__: own
* __Operating System__: Ubuntu 19.04
* __Total RAM in your machine__:  4gb
* __Disks in use__: SSD
* __Used Package__:  Docker - official Docker library

## Component, Query & Data

__Affected feature__: Foxx

## Steps to reproduce
I wouldnt know how to reproduce this issue

__Problem__:
Service "/api" encountered an error while being mounted @ main.js:4:13
2020-01-21T15:17:51Z [1] ERROR [24213]   2 | const { db } = require('@arangodb')
2020-01-21T15:17:51Z [1] ERROR [24213]   3 | const fs = require('fs')
2020-01-21T15:17:51Z [1] ERROR [24213] > 4 | const joi = require('joi')
2020-01-21T15:17:51Z [1] ERROR [24213]     |             ^
2020-01-21T15:17:51Z [1] ERROR [24213]   5 | const dd = require('dedent')
2020-01-21T15:17:51Z [1] ERROR [24213]   6 | const crypt = require('@arangodb/crypto')
2020-01-21T15:17:51Z [1] ERROR [24213]   7 | const createRouter = require('@arangodb/foxx/router') 
2020-01-21T15:17:51Z [1] ERROR [24213] 
2020-01-21T15:17:51Z [1] ERROR [24213] via ArangoError: failed to invoke module
2020-01-21T15:17:51Z [1] ERROR [24213] Reason: ArangoError 2: No such file or directory
2020-01-21T15:17:51Z [1] ERROR [24213] File: /var/lib/arangodb3-apps/_db/insider/api/APP/node_modules/joi/lib/index.js

__Expected result__:
I dont have joi installed in node_modules it should load from arango its totally confusing me

**Comment by DaveM2011** [comment]
On my local copy version 3.5.3 works fine just not on our docker server

**Comment by Simran-B** [comment]
I can't reproduce the problem using `docker run -e ARANGO_NO_AUTH=1 -p 8529:8529 -d arangodb:3.6.0`

My `index.js` of a demo Foxx service:

```js
'use strict'
const { db } = require("@arangodb")
const fs = require("fs")
const joi = require("joi")
const dd = require("dedent")
const crypt = require("@arangodb/crypto")
const createRouter = require("@arangodb/foxx/router")

const router = createRouter()

const modelIntArray = joi.array().required().items(joi.number().integer())
router.post("sum", (req, res) => {
    res.send({
        input: req.body,
        output: req.body.reduce((a, b) => a + b)
    })
})
.body(modelIntArray)
.response(
    joi.object({
        input: modelIntArray,
        output: joi.number().integer()
    }),
    "Input and output of calculation"
)
.error(400, "Invalid input?")
.summary("Adds up integers")
.description("Calculates a sum of an integer array")

router.use("/", module.context.createDocumentationRouter())

module.context.use(router)
```

![image](https://user-images.githubusercontent.com/7819991/74958283-fed40200-5408-11ea-8b1f-ca9efd5875cd.png)

Please share your Docker command and Foxx service (or a simplified version of it which reproduces the problem).

**Comment by maxkernbach** [comment]
Hi @DaveM2011,

Did you have a chance to read Simran's reply?

As requested, could you please share your Docker command and Foxx service (or a simplified version of it which reproduces the problem)?

**Comment by maxkernbach** [comment]
Hi @DaveM2011,

Since we have not heard back from you recently, I am closing this issue for now.
Feel free to reopen this ticket if needed.
