### ISSUE TITLE
[SOLVED] Kubernetes cluster fails to deploy

### ISSUE THREAD

**Issue by marvin-hansen** [arangodb/arangodb#10951]
[SOLVED] This was a namespace issue, solution in the comment.

[Update]: There is a [known issue ](https://github.com/arangodb/kube-arangodb/issues/223#issuecomment-421364461)that kubectl cannot deploy to any other name-space than default with the only workaround of using Helm charts. Investigating this right now, but clearly, this must be documented in the official manual.
 

Trying to deploy arango to my GKE cluster by following the insructions from the manual:

https://www.arangodb.com/docs/stable/tutorials-kubernetes.html#installing-kube-arangodb

# What I did:

## Installed manifests, latest version 0.4.2 

`
kubectl apply -f https://raw.githubusercontent.com/arangodb/kube-arangodb/0.4.2/manifests/arango-crd.yaml
kubectl apply -f https://raw.githubusercontent.com/arangodb/kube-arangodb/0.4.2/manifests/arango-deployment.yaml

kubectl apply -f https://raw.githubusercontent.com/arangodb/kube-arangodb/0.4.2/manifests/arango-storage.yaml
kubectl apply -f https://raw.githubusercontent.com/arangodb/kube-arangodb/0.4.2/manifests/arango-deployment-replication.yaml
`

## Verified operator pods 

`get pods --all-namespaces`

> NAMESPACE     NAME                                                        READY   STATUS    RESTARTS   AGE
default       arango-deployment-operator-dfd5b7c99-gqds2                  1/1     Running   0          46m
default       arango-deployment-operator-dfd5b7c99-wflmn                  1/1     Running   0          46m
default       arango-deployment-replication-operator-67f6954c9-4ch8g      1/1     Running   0          46m
default       arango-deployment-replication-operator-67f6954c9-t2jnv      1/1     Running   0          46m
default       arango-storage-operator-7f7cb85dcc-gwrhj                    1/1     Running   0          32m
default       arango-storage-operator-7f7cb85dcc-tbnrc                    1/1     Running   0          32m

## Wrote cluster config 

> apiVersion: "database.arangodb.com/v1alpha"
kind: "ArangoDeployment"
metadata:
  name: cluster
spec:
  mode: cluster
  dbservers:
    count: 3
  coordinators:
    count: 2

## Deployed cluster config 

`
kubectl apply -f cluster.yaml
`

## Inspected deployment:

`
kubectl describe arango cluster
`

Resulted, as expected in:

>  {"apiVersion":"database.arangodb.com/v1alpha","kind":"ArangoDeployment","metadata":{"annotations":{},"na
me":"cluster","namespace":"web"},"...
API Version:  database.arangodb.com/v1
Kind:         ArangoDeployment
Metadata:
  Creation Timestamp:  2020-01-22T11:26:11Z
  Generation:          1
  Resource Version:    30208839
  Self Link:           /apis/database.arangodb.com/v1/namespaces/web/arangodeployments/cluster
  UID:                 fdcdb85d-3d09-11ea-ba0d-42010a9400b8
Spec:
  Coordinators:
    Count:  2
  Dbservers:
    Count:  3
  Mode:     cluster
Events:     <none>

## Inspected pods: NO PODS(!)

`
kubectl get pods --selector=arango_deployment=cluster
`
> No resources found.

`kubectl get service cluster`
> Error from server (NotFound): services "cluster" not found

And indeed, there are no pods, anywhere in the cluster. 

Btw, the exact same happened with the single-server config.

The operators are in the default namespace but the deployment in the default web namespace. 

Is it required to deploy the DB to the same namespace as the operators, and if so how?

Is this a bug, a feature, or is there something I don't know?

**Comment by marvin-hansen** [comment]
As suspected, this was a namespaces issue. The *correct* installations steps for using a custom namespace are the following:

Assume the namespace is "web"

> 
helm install arangodb-crd --namespace=web https://github.com/arangodb/kube-arangodb/releases/download/0.4.2/kube-arangodb-crd-0.4.2.tgz

helm install arangodb --namespace=web https://github.com/arangodb/kube-arangodb/releases/download/0.4.2/kube-arangodb-0.4.2.tgz

// To use `ArangoLocalStorage`, set field `operator.features.storage` to true
helm install arangodb-storage --namespace=web https://github.com/arangodb/kube-arangodb/releases/download/0.4.2/kube-arangodb-0.4.2.tgz --set "operator.features.storage=true"


 `helm list` 
> 
NAME                    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
arangodb                web             1               2020-01-22 13:39:35.381836 +0100 CET    deployed        kube-arangodb-0.4.2     3.5.0
arangodb-crd            web             1               2020-01-22 13:42:23.2707416 +0100 CET   deployed        kube-arangodb-crd-0.4.2 3.5.0
arangodb-storage        web             1               2020-01-22 13:40:17.9582408 +0100 CET   deployed        kube-arangodb-0.4.2     3.5.0

`kubectl apply -f cluster.yaml --namespace=web`
> .. created

`kubectl describe arango cluster`

> *very long list of settings* 

Now, all pods are there!

**Comment by marvin-hansen** [comment]
Would it be possible to update the kubernetes tutorial by mentioning upfront that, for using a custom name, only Helm Charts can be used? 

I wasted about an hour for solving a complete non-issue....


https://www.arangodb.com/docs/stable/tutorials-kubernetes.html

**Comment by OmarAyo** [comment]
@Simran-B FYI
