### ISSUE TITLE
Please support openCypher-style MATCH

### ISSUE THREAD

**Issue by bionicles** [arangodb/arangodb#10965]
To match patterns in graphs and enable Graph Aided Search as a startup engineer, I want to be able to use openCypher-style MATCH commands in ArangoDB because this would simplify complex imperative query

FOR ... 
    FILTER 
    FILTER
    FILTER 
    FILTER

Into a simple declarative one liner like

MATCH (a:User $JSON1)-[b:Researches $JSON2]->(c:Disease $JSON3)

Since Arango supports JSON this could be actually much better implementation than Neo4j’s version because we could use the data we normally use instead of flattening and serializing stuff. 

ArangoDB is superior to Neo4j in many ways (JSON, Foxx C++, Apache2.0) except for the lack of an explicit declarative MATCH command in openCypher which helps us find patterns in graphs. I realize this has been discussed and closed before but I wish we could revisit this because openCypher has Apache2.0 license so there’s no legal issue around using this syntax and it would make AQL queries a lot more fun to write (and it’s better for the Graph community if we standardize around a query syntax)

FOR is still useful for long traversals but it requires to know a starting point which may only be known relative to other things, so to emulate MATCH requires multiple lines of filtering

Just curious because I’ve been agonizing lately over what graph db to use because I really like ArangoDB but I also really like Cypher MATCH statement, and if this were possible in AQL then it would be an easy choice to use Arango

**Comment by dothebart** [comment]
Hi, 
thanks for your interesting input. 
as @ifcologne [pointed out](https://github.com/arangodb/arangodb/issues/9632#issuecomment-524765125) we are participating in the discussions about the [GQL standard](https://www.gqlstandards.org/). 

So _if_ the AQL graph syntax is going to be changed, we will be heading in that direction.

Please note that [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) with many more graph features is available.

**Comment by villesau** [comment]
Based on the timeline the standard comes earliest in about two years, and it's not even set to stone: https://www.gqlstandards.org/what-is-a-gql-standard 

Any chance to consider cypher or similar syntax in the mean time @dothebart? I believe that lack of cypher like syntax is probably one of the biggest blockers for adopting Arango. It's just so much more intuitive. It took like 5 min to learn cypher, but it's a whole different game with AQL. What I understood from gql standard, it will probably borrow a lot from cypher anyways.

**Comment by maxresdefault** [comment]
@villesau I agree, Cypher support would sell me completely on Arangodb as I've used it before and found it very intuitive. I'm currently evaluating AQL and I can't say it's as intuitive or self-describing as Cypher.

**Comment by villesau** [comment]
@maxresdefault Same. I gave up evaluating Arango due to the syntax. After all, I need to produce customer value and ship instead of just trying to understand the syntax. And it multiplies based on the amount of developers. The one which feels more intuitive wins.

**Comment by Schelling1989** [comment]
+1, please

**Comment by antonio-castellon** [comment]
+1

**Comment by mattjperez** [comment]
An update for those following, according to the [possible timeline for GQL standard](https://www.gqlstandards.org/what-is-a-gql-standard), we can hope for official standardization about 2 years from now (Q2 2024).

**Comment by psytron** [comment]
+1 to @bionicles original post , summed it up perfectly. The one liner is brilliant.

**Comment by psytron** [comment]
> @maxresdefault Same. I gave up evaluating Arango due to the syntax. After all, I need to produce customer value and ship instead of just trying to understand every nuance of the syntax. And it multiplies based on the amount of developers. The one which feels more intuitive wins.
> 
> If Arango would have supported similar syntax, it would have been an obvious choice.

100% +1

**Comment by antonio-castellon** [comment]
my two cents to expand the usage of Arangodb on my clients for the next projects:
- Implementation of OpenCypher ( from developer perspective working with graphs is going to be more powerful in ArangoDB if OpenCypher is implemented, in other case we cannot select ArangoDB if the main goal is to work and create easy features like MERGE, CREATE ..not only MATCH)
- Inclusion Arangodb as "RDS" inside Amazon (The client is always pushing to reduce the knowledge debt on devops and the maintenance of the backups and recovery plans are always a big point for them)

It's a pity that my current clients is forcing us to use Neptune because the points above,
Best regards
Antonio



-

**Comment by mojerro** [comment]
@dothebart Hi, will you reopen it again, we really need it!  😄

**Comment by dehuy69** [comment]
Our project only using ArangoDB as a NoSQL database. Cypher is intuitive.
