### ISSUE TITLE
Question: Disjoint subgraphs in ArangoDB AQL

### ISSUE THREAD

**Issue by rcbop** [arangodb/arangodb#10991]
This is just a repost of the following S.O. question here: https://stackoverflow.com/questions/59719564/disjoint-subgraphs-in-arangodb-aql

Given a graph database I have an actors vetices collection that has edges connecting it to a scenes vertices collection.

I'm having trouble creating a query where I can select all the disjoint subgraphs, that is: given subgraphs A and B in the database, there's no edge (OUTBOUND or INBOUND) connecting sub-graph A to sub-graph B.

From this AQL:
```bash
FOR actor IN actors
FOR v, e, p IN 1..1 ANY actor._id acts_in_scenes
    RETURN e
```

I can get the following graph result as in the uploaded image, the result that I want is a list of lists containing all of the vertexes inside disjoint subgraphs (both actors and scenes). Examples were circled in red.

![expected-result](https://i.stack.imgur.com/9u5NG.png)

I've made several attempts using subqueries and collects, I think the best result up to this point is the query bellow, but still it's just returning me scenes:

```bash
FOR actor IN actors
    LET sub_result = (FOR v, e, p IN 1..1 ANY actor._id acts_in_scenes RETURN DISTINCT v._id) // this just returns me scenes
    FILTER LENGTH(sub_result) > 0
    RETURN DISTINCT sub_result
```

So by increasing the depth to 5 (1..5) in the graph traversal subquery and now I can get actors vertices. Now the problem is when checking the result json, I can see repeated scene keys on the groups, this should not be possible if this result would represent the disjoint sub-graphs:

```bash
FOR actor IN actors
    LET sub_result = (
        FOR v, e, p IN 1..5 ANY actor._id acts_in_scenes 
        SORT v._id
        RETURN DISTINCT v._id
    )
    FILTER LENGTH(sub_result) > 0
    SORT COUNT(sub_result) DESC
    RETURN DISTINCT { 'count': COUNT(sub_result), result: sub_result }
```

I had to solve this by creating a graph on the application side using [networkx](https://networkx.github.io/) library and using the [nx.connected_components()](https://networkx.github.io/documentation/networkx-1.10/reference/generated/networkx.algorithms.components.connected.connected_components.html) function. But I really wish I could solve this by using just the graph features of the database, since it adds complexity to the application and mandates me to create a graph in memory on the app side.

**Comment by Simran-B** [comment]
Related: https://github.com/arangodb/arangodb/issues/4062
With Pregel it's possible to compute the disjoint subgraphs, but it requires two edges per connection (for both direction), see above issue.

**Comment by Simran-B** [comment]
In v3.7, a new Pregel algorithm `wcc` for finding Weakly Connected Components was added:

https://www.arangodb.com/docs/stable/release-notes-new-features37.html#pregel

**Comment by Vuanhtien96** [comment]
how to visualize your data? i try my best but i don't have any toturial in detail to create a graph
