### ISSUE TITLE
Tabular/CSV result view in AQL Editor

### ISSUE THREAD

**Issue by minnownoir** [arangodb/arangodb#1101]
As a developer/analyst, I would like to be able to transform JSON results to CSV so that I can send them as tables over email or dump them into Excel for quick ad-hoc reporting.  

Right now, this can only be accomplished through the use of external tools or web sites (e.g., ttp://konklone.io/json/, http://csvkit.readthedocs.org/en/latest/scripts/sql2csv.html).  Obviously, this works better for flat result sets, so people wouldn't use it for hierarchical result sets.  

This could be accomplished by adding a button or tab for displaying the results in a text field in CSV format.  The existing Download button could also then be modified to send the results in CSV, not JSON, format to the browser when the user wants CSV.  The transformation code be native or use the utility referenced above.  (This should be an offline capability, not something that requires internet access to work.)

Thanks

**Comment by baslr** [comment]
@minnownoir do you mean something like this https://youtu.be/l9IWLOO4cBE?

**Comment by Simran-B** [comment]
@baslr: Probably. How (and when) does it work though?

**Comment by baslr** [comment]
@Simran-B, it works with every resultset thats an array of objects. It collects all keys from every object.
https://github.com/DUOUNO/ArangoDB-view/blob/5521f2faf0c2f8c8ce0eb5a5321d7855ef11eca3/src/src/aql/aqlController.js#L217
You can try it out.

**Comment by minnownoir** [comment]
Looks like a good start.  The main functional requirements would be the
ability to copy and paste into email (formatting in Outlook is okay)  for
dissemination or into Excel for building charts.

Thanks!

**Comment by baslr** [comment]
Hi @minnownoir,
I have added a button to copy the result as CSV into the clipboard. https://www.youtube.com/watch?v=1Y-654DKlJo

**Comment by minnownoir** [comment]
Looks good. Thanks so much for doing this.

**Comment by hkernbach** [comment]
We will support tabular and graph output in the upcoming release.
