### ISSUE TITLE
Questions on Foxx management HTTP REST API (Multipart/form-data)

### ISSUE THREAD

**Issue by joowani** [arangodb/arangodb#11045]
## My Environment

* __ArangoDB Version__:        3.6.1
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:  Manual Start in Docker
* __Infrastructure__:               Own
* __Operating System__:        Windows 10
* __Total RAM in your machine__:       16 GB
* __Disks in use__:        SSD
* __Used Package__:              Docker

## Component, Query & Data

__Affected feature__: Foxx

## Steps to reproduce

1. Install a simple test [Foxx service zip bundle](https://github.com/arangodb/arangodb/files/4148779/service.zip) using the [POST HTTP API](https://www.arangodb.com/docs/stable/http/foxx-management.html#install-new-service) (multipart form, application/zip format).
2. Update (or replace) the Foxx service using the same zip bundle via [PATCH HTTP API](https://www.arangodb.com/docs/stable/http/foxx-management.html#upgrade-service) or [PUT HTTP API](https://www.arangodb.com/docs/stable/http/foxx-management.html#replace-service) (again multipart form, application/zip format).
3. Refer to [this ticket](https://github.com/joowani/python-arango/issues/120#issuecomment-579553800) to see the example Python code snippet I am using.

__Problem__:
There are two questions:

1. ~~The POST API request works and the Foxx service is installed successfully. But the update and replace API requests using the same zip bundle return HTTP 405 (Method Not Allowed). I don't know if this is by design or if it is a bug.~~

2. The "configuration" and "dependencies" fields do not seem to have an effect when using multipart form format. Are these fields only honored in JSON format?

Also, it would be nice if the HTTP documentation on Foxx management API includes examples for different formats.

EDIT: Removed question 1 as that was an error on my part.

**Comment by pluma** [comment]
This works for me. Arangojs also uses multipart. Here's an example payload:

```
----MultipartBoundary775575849169
Content-Disposition: form-data; name="configuration"

{"hello":123}
----MultipartBoundary775575849169
Content-Disposition: form-data; name="dependencies"

{}
----MultipartBoundary775575849169
Content-Disposition: form-data; name="source"; filename="2020830-4187-9xp3cm.ji0dd.zip"
Content-Type: application/zip

PK<snip>
----MultipartBoundary775575849169--
```

Note that the `configuration` and `dependencies` fields are transmitted as regular fields, not "files", i.e. they lack a filename disposition and don't have a content-type header. Maybe that's the cause of your problem?

**Comment by Simran-B** [comment]
@joowani Was pluma's comment helpful?

**Comment by joowani** [comment]
Hi @Simran-B,

Yes it was. Thank you!
