### ISSUE TITLE
K SHORTEST PATHS returns strange result

### ISSUE THREAD

**Issue by agorobtsov** [arangodb/arangodb#11053]
## My Environment

* __ArangoDB Version__:        3.6.1
* __Storage Engine__:             RocksDB 
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:              
* __Infrastructure__:                own 
* __Operating System__:         Windows 10
* __Total RAM in your machine__:       16Gb. 
* __Disks in use__:        SSD 

## Component, Query & Data

__Affected feature__:
K_SHORTEST_PATH via AQL

__AQL query (if applicable)__:
```
FOR p IN ANY K_SHORTEST_PATHS 'network_elements/6399371' TO 'network_elements/6403910'
    links
    OPTIONS {
        weightAttribute: 'capacity_range1_weight',
        defaultWeight: 10000
    }
    LIMIT 1
RETURN p
```

__AQL explain (if applicable)__:
```
Query String (224 chars, cacheable: true):
 FOR p IN ANY K_SHORTEST_PATHS 'network_elements/6399371' TO 'network_elements/6403910'
     links
     OPTIONS {
         weightAttribute: 'capacity_range1_weight',
         defaultWeight: 10000
     }
     LIMIT 1
 RETURN p

Execution plan:
 Id   NodeType                            Est.   Comment
  1   SingletonNode                          1   * ROOT
  2   KShortestPathsNode   1638400000000000000     - FOR p  /* path */ IN ANY K_SHORTEST_PATHS 'network_elements/6399371' /* startnode */ TO 'network_elements/6403910' /* targetnode */ links
  3   LimitNode                              1     - LIMIT 0, 1
  4   ReturnNode                             1     - RETURN p

Indexes used:
 none

k shortest paths on graphs:
 Id   Vertex collections   Edge collections
  2                        links              

Optimization rules applied:
 none
```

__Dataset__:

[dataset.zip](https://github.com/arangodb/arangodb/files/4170133/dataset.zip)

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. 
2. 
3. 

__Problem__:
returned result is 
edges	vertices	weight
[]	[{"_key":"6399296","_id":"network_elements/6399296","_rev":"_a_5Ah7a--C","name":"Core Network Element#4100","id":4100,"type":"Core","status":"In Service","partId":4}]	0

There are no edges and just one node.

__Expected result__:
Full path including all edges and nodes from path.
Seems like issue https://github.com/arangodb/arangodb/issues/10949 was not carefully checked. Please take a look with priority. K_SHORTEST_PATHS doesn't work at all for my cases.

**Comment by joerg84** [comment]
Thanks, we are checking this

**Comment by markuspf** [comment]
The fix for issue #10949 was only merged into the `3.6` branch after `3.6.1` (release commit for 3.6.1 https://github.com/arangodb/arangodb/commit/e223097deafe99e8a8bd3a7476011a527f809ace merge commit for the bugfix https://github.com/arangodb/arangodb/commit/2002d3835595b7916f0c2f5279be04e4081ee2a4). 

Issue #10949 as well as the one described here are both fixed in the `3.6` branch and the `devel` branch, hence fixes will appear with `3.6.2` and `3.7`

**Comment by agorobtsov** [comment]
Hi @markuspf But there is comment https://github.com/arangodb/arangodb/issues/10949#issuecomment-580361591
Is this comment wrong?

**Comment by markuspf** [comment]
Yes that comment is, unfortunately, not correct. As the commit history shows the fix did not make it into the `3.6.1` release, apologies.

**Comment by agorobtsov** [comment]
Thanks for the explanation. Issue can be closed

**Comment by maxkernbach** [comment]
Hi @agorobtsov,

Sorry for the confusion about the bug-fix version.
ArangoDB version 3.6.2, which includes the fix, has just been released.
