### ISSUE TITLE
Display query time in aardvark's AQL editor

### ISSUE THREAD

**Issue by ThomasWeiss** [arangodb/arangodb#1112]
I think that many people use aardvark's AQL editor to debug/benchmark/optimize AQL queries. In such context, it would be very helpful to display the execution time of the query being submitted.

**Comment by nlac** [comment]
Until then, copy and run it into your browser's console, then start the AQL query :-)

```javascript
(function() {
var t, state, foo = function() {
	var started = $("#progressPlaceholder").css("display") == "block";
	var finished = $(".active #result-switch").length;	
	if (!state && started) {
		t = (new Date()).getTime();
		state = "started";
		console.info("query started");
	} else if (state == "started" && finished) {
		console.info("query finished, elapsed: ", (new Date()).getTime() - t , "ms");
		return;
	}
	setTimeout(foo,1);
}; foo();
})();
```

**Comment by hkernbach** [comment]
Feature added: devel-branch. Will be part of the the upcoming release.
8cd57c3c68d3dae412403f5d0f823088eb4ba940
