### ISSUE TITLE
Missing collections after restore a dump with arangorestore

### ISSUE THREAD

**Issue by pstrehle** [arangodb/arangodb#11138]
## My Environment

* __ArangoDB Version__:        3.6.1 
* __Storage Engine__:             RocksDB 
* __Deployment Mode__:       Cluster 
* __Deployment Strategy__:   ArangoDB Starter in Docker 
* __Configuration__:               3 DB-Server, 3 Agents, 3 Coordinator 
* __Infrastructure__:               own 
* __Operating System__:        Centos7 
* __Total RAM in your machine__:        16GB (per node) 

## Component, Query & Data

__Affected feature__: arangorestore

__Size of your Dataset on disk__: 

The dump is currently 304 collections.     
With only several MBs of data.  

__Replication Factor & Number of Shards (Cluster only)__: 1 & 1

## Steps to reproduce

1. docker exec $(docker ps -q --filter="NAME=adb-coordinator*") arangorestore --input-directory datahub_backup/${latest_backup} --server.database datahub --server.username root

__Problem__:  
Collections are missing after restore the a dump with `arangorestore` on one coordinator.   
All collections are correctly dumped with `arangodump`, but doing a `arangorestore` doesn't restore all collections in the dump.  
It are always the same collections that can't be restored. 

Comparing the structure-files of those dumped collections that didn't work and some that did work, didn't show any differences aswell. 

Dumping with `--dump-data false` results in the same behavior.   
 
If restoring just a single collection with the `-collection`-flag, nothing happens as well:   
```
2020-02-12T12:47:28Z [3683] INFO [6d69f] {restore} # Dispatched 0 job(s), using 2 worker(s)
2020-02-12T12:47:28Z [3683] INFO [a66e1] {restore} Processed 0 collection(s) in 0.616218 s, read 0 byte(s) from datafiles, sent 0 data batch(es) of 0 byte(s) total size
```

The weird thing:  
If restore the dump from a local arangodb-instance, with the `--server.endpoint`-flag, on to one of the coordinators, the dump is restored without any missing collection.

We already had two discussions in the slack-channel, which resulted in the suggestion posting this here.
https://arangodb-community.slack.com/archives/C07NV9NAH/p1581501191376600
https://arangodb-community.slack.com/archives/C07NV9NAH/p1581501493378700

If you need some example-dumps we would require a safe location where we could upload some of them.

**Comment by OmarAyo** [comment]
Hi @pstrehle,

You can send us a message to hackers@arangodb.com (this ML is not public) and attach the dump in that email. This way we can try to reproduce and find the root cause. Please reference the number of this issue in your email.

Best

**Comment by dothebart** [comment]
Hi, 
we haven't heard back from you recently. Please get back to us, if the problem persists.

Please note [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) is available.

**Comment by belqit** [comment]
`systemctl restart arangodb3` worked for me

**Comment by belqit** [comment]
my user didn't have enough permissions to see collections
