### ISSUE TITLE
3.6.1 version (centos7): http-proxy can't pass delete method req.body to foxx

### ISSUE THREAD

**Issue by wg20170107** [arangodb/arangodb#11137]
## My Environment

* __ArangoDB Version__:        3.6.1
* __Storage Engine__:             
* __Deployment Mode__:       
* __Deployment Strategy__:   
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:        contos7
* __Total RAM in your machine__:        
* __Disks in use__:        
* __Used Package__:              

## Component, Query & Data

__Affected feature__:

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. 
2. 
3. 

__Problem__:
old version is ok, 3.6.1 version have this problem (test on two centos mechines), other method (like post) is ok.

__Expected result__:

**Comment by Simran-B** [comment]
Looks like the problem was discovered by someone else as well and already fixed for v3.6.2 / devel:
#11097 #11119

**Comment by wg20170107** [comment]
when does 3.6.2 can provide?

**Comment by dothebart** [comment]
In the next weeks. 
If you want a binary with that fix now, you can try the nightlies that we ship via docker:
`docker pull arangodb/arangodb-preview:3.6-nightly`

**Comment by maxkernbach** [comment]
Hi @wg20170107,

Version 3.6.2, which includes a fix for this issue, has just been released.

Please find the latest version at the links below:
- https://www.arangodb.com/download/
- https://download.arangodb.com/arangodb36/
