### ISSUE TITLE
authentication problem with 2.3.0 update from 2.2.7

### ISSUE THREAD

**Issue by antokara** [arangodb/arangodb#1116]
After yum update and arango upgrade, I can't log in through the Web UI or the Arangosh and use my old databases with the old credentials.

restart of service does not fix it but:

If I disable the authentication, then using arangosh create new accounts or recrete the old ones,
I can login sucessfuly with any account but only once. After that one login, all subsequent authentications fail.

Another thing to note is that with authentication enabled, if I $arangosh (as root with empty password). when I try to >db._useDatabase("myOldDb"); I get ArangoError 401: Unauthorized.

Did not find anything helpful / out of the ordinary in any of the two logs ("/var/log/arangodb/arangod.log.daemon" or "/var/log/arangodb/arangod.log").

At the moment in order to work I have to disable the authentication (which isn't quite the workaround).

System Information:
CentOS 6.6

$arangod --version
architecture: 64bit
build-date: 2014-11-18 18:12:36
icu-version: 52.1
libev-version: 4.11
maintainer-mode: false
openssl-version: OpenSSL 1.0.0-fips 29 Mar 2010
server-version: 2.3.0
sizeof int: 4
sizeof void*: 8
v8-version: 3.16.14

_update: just tried creating a new db and new user for it. that works as it should.
*_update2: after many service restarts and tests, I found an acceptable solution: if I create a new user with a different username than the old one, it works. Still, the old accounts behavior is erratic.

(keep it at least as a solution, in case other people find themselves in the same spot as me)

**Comment by fangspeen** [comment]
I'm currently experiencing the same or similar issue - after installing 3.0.4 on windows

Unfortunately this is my first time I'm actually trying to use arango so I don't know much of anything yet.

I may have installed a previous version - in fact I think I did but never got around to playing with it.

**Comment by dothebart** [comment]
You should have provided the root password during the setup procedure, if you didn't, it should be empty. Since this ticket is way old, please leave it buried, and if your problem persists open a new one with a bit more detailed description what you did and trying to do and what failed.

**Comment by fangspeen** [comment]
Thanks - it seems that us the problem :
The installer does not apply the password I specified. Blank password works.
