### ISSUE TITLE
I got a problem with arango search function

### ISSUE THREAD

**Issue by s506795003** [arangodb/arangodb#11171]
I test with arango 3.5.3 in win10.

**Comment by s506795003** [comment]
I try arango search instead of filter. But it shows me no collection or view found in my database. like this.
![image](https://user-images.githubusercontent.com/49777984/75351844-bd999180-58e3-11ea-850b-b1cda8912b87.png)

**Comment by s506795003** [comment]
Actually, I got one named qianwan with document form. I think I am in a wrong place with using search situation. could you give me some suggestion. 
![image](https://user-images.githubusercontent.com/49777984/75351927-e02baa80-58e3-11ea-8165-9c376e0f7200.png)

**Comment by Simran-B** [comment]
You can not just substitute `FILTER` by `SEARCH` in queries, you have to create a View with a distinct name first. Then add at least one collection link. https://www.arangodb.com/docs/stable/arangosearch.html
