### ISSUE TITLE
Arango Search does not support LIKE operator

### ISSUE THREAD

**Issue by cskru** [arangodb/arangodb#11176]
## My Environment

* __ArangoDB Version__:       3.6.1

Arango Search does not seem to support LIKE operator.  
Other supported operators are working fine.  

Tried this AQL:  
```aql
FOR s IN searchView
SEARCH s.name LIKE "somesubstring"
RETURN s
```  
But it gives an error saying:  

> Query: AQL: not implemented: Unable to evaluate loop variable 's' as a
> part of ArangoSearch noncompliant expression
> 'LIKE([$0.name,"somesubstring"])' (exception location:
> C:\vm04-windows\oskar\work\ArangoDB\arangod\IResearch\IResearchExpressionContext.cpp:62)
> (while executing) (exception location:
> C:\vm04-windows\oskar\work\ArangoDB\arangod\RestHandler\RestCursorHandler.cpp:298)

Referred this: https://www.arangodb.com/docs/3.6/aql/operations-search.html  
Other supported operators are working fine.

How do we achieve this in Arango search view?  
LIKE operator or mimicking the same behavior in Arango Search View

**Comment by maxkernbach** [comment]
Hi @cskru,

Alpha2 of ArangoDB 3.7, which includes multiple ArangoSearch improvements including **Wildcard search with LIKE**, has just been released.

**ArangoSearch wildcard and fuzzy search**

*  Wildcard search with LIKE
*  N-Gram based fuzzy search
*  Enhanced phrase and proximity search

**ArangoSearch View optimizations**

*  Improved late document materialization for Views with stored values
*  Covering Views (fulfilling requests using View indexes without touching the storage engine)
*  Improved SIMD-based index format for much faster queries

You can find all details in the [Alpha2 post](https://www.arangodb.com/2020/03/alpha-2-arangodb-3-7/) and check out the [interactive tutorial for Arangosearch](https://www.arangodb.com/arangodb-training-center/search/arangosearch-tutorial-3-7/).
