### ISSUE TITLE
Can you provide complete docker command example

### ISSUE THREAD

**Issue by wg20170107** [arangodb/arangodb#11179]
## My Environment

* __ArangoDB Version__:        3.6
* __Storage Engine__:             
* __Deployment Mode__:       
* __Deployment Strategy__:   
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:        
* __Total RAM in your machine__:        
* __Disks in use__:        
* __Used Package__:              

## Component, Query & Data

__Affected feature__:

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. 
2. 
3. 

__Problem__:
can you provide complete docker command example？
like:
docker run -e ARANGO_ROOT_PASSWORD=xxx -p 172.27.1.22:8530:8529 arangodb/arangodb arangod --server.endpoint tcp://0.0.0.0:8529
include: -v /mnt/test:/var/lib/arangodb3 
I don't be familiar with docker.
thank you!

__Expected result__:

**Comment by wg20170107** [comment]
like:
-v /mnt/test:/var/lib/arangodb3
-v /mnt/test2:/var/lib/arangodb3-apps
is above right?

**Comment by wg20170107** [comment]
/etc/arangodb3
need config -v?
like:
-v /mnt/test3:/etc/arangodb3

**Comment by Coderayush13** [comment]
i  wnat to work on this issue

**Comment by dothebart** [comment]
we try to keep https://hub.docker.com/_/arangodb accurate with the basic documentation. 
You can as well use the arangodb starter to launch docker containers: https://www.arangodb.com/docs/stable/deployment-cluster-using-the-starter.html#using-the-arangodb-starter-in-docker
