### ISSUE TITLE
db._isSystem() returns true for a non-system DB

### ISSUE THREAD

**Issue by mohamed-barakat** [arangodb/arangodb#11243]
## My Environment

* __ArangoDB Version__:        3.6.0
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:        MacOS 10.15.3
* __Total RAM in your machine__:        64Gb.
* __Disks in use__:        SSD
* __Used Package__:              homebrew

## Component, Query & Data

__Affected feature__: arangosh

__AQL query (if applicable)__: db._isSystem()

__AQL explain (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

I get
```
127.0.0.1:8529@example> db._isSystem();
true
```

__Problem__: The DB `example` is definitely not the *_system* database.

__Expected result__:
```
127.0.0.1:8529@example> db._isSystem();
false
```

**Comment by jsteemann** [comment]
Bugfix PR: https://github.com/arangodb/arangodb/pull/11507
