### ISSUE TITLE
User Defined Function not working when invoked within FOR statement in cluster mode

### ISSUE THREAD

**Issue by mikestaub** [arangodb/arangodb#11271]
## My Environment

* __ArangoDB Version__: 3.6.1       
* __Storage Engine__: RocksDB             
* __Deployment Mode__: Cluster      
* __Deployment Strategy__: Manual Start in Docker  
* __Configuration__: single shard, replicationFactor=3              
* __Infrastructure__: own              
* __Operating System__: MacOS 10.15.3, Docker 2.2.0.4       
* __Total RAM in your machine__: 16Gb       
* __Disks in use__: 1       
* __Used Package__: official docker             

## Component, Query & Data

__Affected feature__:
User defined functions

__AQL query (if applicable)__:
```
FOR u in users
  LET test = TEST::UTILS::MYFUNC()
  RETURN u
```

__AQL explain (if applicable)__:
```
Query String (81 chars, cacheable: false):
 FOR u in users
     LET test = ( TEST::UTILS::MYFUNC() )
     RETURN u

Execution plan:
 Id   NodeType                  Site  Est.   Comment
  1   SingletonNode             DBS      1   * ROOT
  2   EnumerateCollectionNode   DBS      3     - FOR u IN users   /* full collection scan, 1 shard(s) */
  7   RemoteNode                COOR     3       - REMOTE
  8   GatherNode                COOR     3       - GATHER 
  3   CalculationNode           COOR     3       - LET test = TEST::UTILS::MYFUNC()   /* user-defined function */   /* simple expression */
  4   ReturnNode                COOR     3       - RETURN u

Indexes used:
 none

Functions used:
 Name                               Deterministic   Cacheable   Uses V8
 TEST::UTILS::MYFUNC   false           false       true   

Optimization rules applied:
 Id   RuleName
  1   scatter-in-cluster
  2   remove-unnecessary-remote-scatter
```

__Dataset__:
simple documents

__Size of your Dataset on disk__:
1mb

__Replication Factor & Number of Shards (Cluster only)__:
replicationFactor=3 shards=1

## Steps to reproduce

1. create a database with replicationFactor=3 and writeConcern=3
1. create a collection with settings ( replicationFactor=3, writeConcern=3, waitForSync=false )
1. create one or more records in users collection
2. create a simple UDF with this body `function myFunc() {
  return true;
}`
3. execute the AQL query as seen above

__Problem__:
```
ArangoError: AQL: illegal AQL transaction state

(exception location: /work/ArangoDB/arangod/Cluster/ClusterTrxMethods.cpp:400). 

Please report this error to arangodb.com 

(while optimizing plan)
at ArangoStatement.execute (/usr/share/arangodb3/js/server/modules/@arangodb/arango-statement.js:84:16) 
at ArangoDatabase._query (/usr/share/arangodb3/js/server/modules/@arangodb/arango-database.js:102:45) 
at SimpleQueryAll.execute (/usr/share/arangodb3/js/server/modules/@arangodb/simple-query.js:95:42) 
at SimpleQueryAll.SimpleQuery.toArray (/usr/share/arangodb3/js/common/modules/@arangodb/simple-query-common.js:171:8) 
at ArangoCollection.toArray (/usr/share/arangodb3/js/server/modules/@arangodb/arango-collection.js:93:23) 
at reloadUserFunctions (/usr/share/arangodb3/js/server/modules/@arangodb/aql.js:82:5) 
at exports.FCALL_USER (/usr/share/arangodb3/js/server/modules/@arangodb/aql.js:168:5) (exception location: /work/ArangoDB/arangod/Aql/V8Executor.cpp:91).

Please report this error to arangodb.com (while executing) 
(exception location: /work/ArangoDB/arangod/RestHandler/RestCursorHandler.cpp:298).
```

__Expected result__:
a list of all documents in users collection

**Comment by dothebart** [comment]
Hi, 
from what I see here I got the suspcion that you're trying to load documents from the database within the UDF - this is not supported.

UDFs may only work with the data they get through parameters.

**Comment by mikestaub** [comment]
Is this only true in cluster mode? I am using a UDF that loads a document by _key from a collection and it was working in 3.4.0 when I was running on a single instance. Now that same UDF is throwing the error I linked above.

**Comment by dothebart** [comment]
Hi, 
it may have been working previously, but it was allways documented as not supported before: https://www.arangodb.com/docs/stable/aql/extending-conventions.html
You may need to use the AQL [`DOCUMENT()`](https://www.arangodb.com/docs/stable/aql/functions-miscellaneous.html#document) function before invoking the UDF to fetch the document, and pass it in as an argument.

**Comment by mikestaub** [comment]
Ok thanks for clarifying!
