### ISSUE TITLE
v3.6.2 requires openssl 1.1.1d when 1.1.1e is available

### ISSUE THREAD

**Issue by dalu** [arangodb/arangodb#11313]
## My Environment

* __ArangoDB Version__:        3.6.2
* __Operating System__:        Archlinux
* __Used Package__:              aur

## Steps to reproduce

1. compile v3.6.2 with openssl 1.1.1e installed
2. 
3. 

__Problem__:

```
-- Found OpenSSL: /usr/lib/libcrypto.so (found version "1.1.1e")  
CMake Error at CMakeLists.txt:1088 (message):
  Wrong OpenSSL version was found: 1.1.1e! Required version: 1.1.1d!
```

__Expected result__:

Not requiring an older SSL Version when a newer variant one of the same version is present.

**Comment by dothebart** [comment]
unless you specify `-DUSE_STRICT_OPENSSL=Off` as cmake option the exact version is required.

**Comment by dalu** [comment]
Ok I'll refernce this issue to the maintainer then
