### ISSUE TITLE
TTL Index Expire column missing

### ISSUE THREAD

**Issue by exosiscrypto** [arangodb/arangodb#11337]
## My Environment

* __ArangoDB Version__:      3.6.21

__Affected feature__:
web interface

__Problem__:
After TTL Index creation the web interface doesn't  show any information about the expire time we used

**Comment by maxkernbach** [comment]
Hi @exosiscrypto,

Thanks for reporting. As you mentioned the expire time for a TTL index is not shown in the UI.

As a workaround, you can execute `db.<collection-name>.indexes()` from `arangosh`.

Example:
```
127.0.0.1:8529@_system> db.TTL_col.indexes()
[ 
  { 
    "fields" : [ 
      "_key" 
    ], 
    "id" : "TTL_col/0", 
    "name" : "primary", 
    "selectivityEstimate" : 1, 
    "sparse" : false, 
    "type" : "primary", 
    "unique" : true 
  }, 
  { 
    "expireAfter" : 5, 
    "fields" : [ 
      "test" 
    ], 
    "id" : "TTL_col/4039962", 
    "inBackground" : false, 
    "name" : "TTL_index", 
    "selectivityEstimate" : 1, 
    "sparse" : true, 
    "type" : "ttl", 
    "unique" : false 
  } 
]
```

The `expireAfter` field shows the expire time of the created TTL index.

**Comment by exosiscrypto** [comment]
Yes thanks for that info
I am aware of that option available in arangosh 
But UI will be easy to access for sometimes, so if this feature implemented it will help lot

**Comment by maxkernbach** [comment]
Hi @exosiscrypto,

The GA release of 3.7, which adds the missing functionality to the UI, is available by now.

From the [Changelog](https://github.com/arangodb/arangodb/blob/0b1dd33b70031512b54a992f63ff481e96235a64/CHANGELOG#L884):

> * Show some index details in index overview of the web interface, e.g. the
>   `minLength` attribute for fulltext indexes or the `expireAfter` attribute for
>   TTL indexes.

Please find the latest release in the [download section](https://www.arangodb.com/download/).
