### ISSUE TITLE
Cannot apply primarySort in Aardvark console

### ISSUE THREAD

**Issue by oliverhausler** [arangodb/arangodb#11359]
## My Environment

* __ArangoDB Version__:        3.6.2
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Infrastructure__:               own
* __Operating System__:        MacOS

## Component, Query & Data

__Affected feature__:
AQL query using web interface

## Steps to reproduce

1. Create a collection with an index on a field.
2. Create a view with a `primarySort` set to the indexed field.
3. Apply in web console.

__Problem__:

Not persisted.

__Expected result__:

Persisted.

**Comment by oliverhausler** [comment]
[Screen Recording 2020-03-31 at 14.24.19.mov.zip](https://github.com/arangodb/arangodb/files/4410938/Screen.Recording.2020-03-31.at.14.24.19.mov.zip)

**Comment by maxkernbach** [comment]
Hi @oliverhausler,

The `primarySort` can not be configured through the Web UI as stated in our [documentation](https://www.arangodb.com/docs/stable/arangosearch-views.html#primary-sort-order):

> Note that the primarySort option is immutable: it can not be changed after View creation. It is therefore not possible to configure it through the Web UI. The View needs to be created via the HTTP or JavaScript API (arangosh) to set it.

You can find an example on how to setup the `primarySort` option in the View creation in our [Youtube tutorial](https://www.youtube.com/watch?time_continue=223&v=bKeKzexInm0&feature=emb_logo).
