### ISSUE TITLE
Can not restore datas to cluster

### ISSUE THREAD

**Issue by oneminute** [arangodb/arangodb#1136]
I set up a cluster in multi mechine mode. And when i restore data from old version in normal mode it can not run well. As following: 

```
oneminutembp:shells liuxiang$ arangorestore --server.endpoint tcp://192.168.0.132:8531 --server.username root --server.password xxxxxx --server.database iwant_debug --create-collection true --import-data true --input-directory "dump"
Server version: 2.3.1
Connected to ArangoDB 'tcp://192.168.0.132:8531
Re-creating collection 'ACCOUNTS_COLLECTION'...
Processed 0 collection(s), read 0 byte(s) from datafiles, sent 0 batch(es)
got invalid response from server: Could not connect
oneminutembp:shells liuxiang$ 
```

When re-creating the first collection, cmd was blocked and after a while I got the error message as "Could not connect".

**Comment by Dashue** [comment]
Just bumped into the same scenario, more elaboration on the approach needed to be taken would be appreciated
