### ISSUE TITLE
LOCK file is not cleaned after server crash

### ISSUE THREAD

**Issue by amitabak-MA** [arangodb/arangodb#11387]
## My Environment

* __ArangoDB Version__: 3.6.0 community edition         
* __Storage Engine__:     RocksDB        
* __Deployment Mode__:  single      
* __Deployment Strategy__:   Manual Start 
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:      Mac 10.15.4   
* __Total RAM in your machine__:      16GB   
* __Disks in use__:    SSD    
* __Used Package__:              

## Component, Query & Data

__Affected feature__: AQL query

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. 
2. 
3. 

__Problem__: LOCK file remains after server restart due to long running query. As result the next insert fails due to:
```
failed to read/write lockfile, please check the file permissions of the lockfile '/usr/local/var/lib/arangodb3/LOCK
```

__Expected result__: server restart should start afresh LOCK file

**Comment by amitabak-MA** [comment]
Upgraded using brew to 3.6.2_1
Same thing happens when calling 
sudo /usr/local/Cellar/arangodb/3.6.2_1/sbin/arangod
I see both the 
/usr/local/var/lib/arangodb3/LOCK
and the /usr/local/var/lib/arangodb3/engine-rocksdb/LOCK

**Comment by OmarAyo** [comment]
Hi @amitabak-MA 

Can you please manually remove the following LOCK files (you may need to be sudo) and try to restart the server again:
- `/usr/local/var/lib/arangodb3/LOCK`
- `/usr/local/var/lib/arangodb3/engine-rocksdb/LOCK`

Best

**Comment by OmarAyo** [comment]
Hi @amitabak-MA,

This ticket is being closed as inactive due to the date of the last activity on it.

If you believe this was done in error, please comment or create a new issue.
