### ISSUE TITLE
Not able to install enterprise version (3.6)  using documentation

### ISSUE THREAD

**Issue by gopalkalabe** [arangodb/arangodb#11405]
I am following the link for installing enterprise  version of Arangodb.

https://www.arangodb.com/download-arangodb-enterprise/ for CentOS

```
cd /etc/yum.repos.d/
curl -OL https://download.arangodb.com/arangodb36/RPM/arangodb.repo
yum -y install arangodb3e-3.6.2
```
I  am getting error:
```
"No package arangodb3e-3.6.2 available."
```
Any idea?

**Comment by OmarAyo** [comment]
Hi @gopalkalabe,

Thanks for reporting this, would you kindly send us an email to hackers@arangodb.com so we can provide you with the correct procedure
 
We will also fix the snippet bug reporting the wrong url 

Best,

**Comment by maxkernbach** [comment]
Hi @gopalkalabe,

Thanks again for reporting.
This ticket is being closed since the installation instructions have been fixed by now.
