### ISSUE TITLE
FormatMiddleware behaviour when there's information from url and header

### ISSUE THREAD

**Issue by stackmagic** [arangodb/arangodb#1143]
From: https://docs.arangodb.com/Foxx/FoxxOptional.html

> To determine the format of the request it checks the URL and then the accept header. If one of them gives a format or both give the same, the format is set. If the formats are not the same, an error is raised.

IMO, it'd be better to not raise an error if there is conflicting information and always have the information from the url override the accept header. The reason being quick and dirty testing/tinkering in the browser  (where you can choose the url but you can't set any headers) during development of a controller.

**Comment by pluma** [comment]
FormatMiddleware has been removed.
