### ISSUE TITLE
Upgrade to 3.6.2, now cannot start

### ISSUE THREAD

**Issue by imtrobin** [arangodb/arangodb#11442]
## My Environment

* __ArangoDB Version__:        3..6.2
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Infrastructure__:                own
* __Operating System__:        Centos 

Hi. I upgraded from 3.4.x to 3.6.2 via  yum, it is successful but I cannot start it

```
[root@localhost etc]# sudo yum install arangodb3
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 *snip**
Package arangodb3-3.6.2-1.0.x86_64 already installed and latest version
Nothing to do
[root@localhost etc]# sudo systemctl enable arangodb3
Failed to execute operation: No such file or directory
```

**Comment by dothebart** [comment]
Please note that you should upgrade to 3.5 inbetween. 
If the service file is missing, you may want to download it from here: 
https://github.com/arangodb/oskar/blob/master/rpm/3.6/arangodb3.service

**Comment by imtrobin** [comment]
I moved it, and now it has File Exist error
```
cp arangodb3.service /etc/systemd/system
[root@localhost arangodb3]# sudo systemctl enable arangodb3
Failed to execute operation: File exists
[root@localhost arangodb3]# sudo systemctl start arangodb3
Failed to start arangodb3.service: Unit not found.
```

**Comment by dothebart** [comment]
Hi, 
have you been able to figure this out?
