### ISSUE TITLE
Some rocksdb options are missing

### ISSUE THREAD

**Issue by dvzubarev** [arangodb/arangodb#11447]
Hi, it is not a bug report, but a feature request. I didn't find how to change such rocksdb options as `target_file_size_base` and `target_file_size_multiplier` from rocksdb [wiki](https://github.com/facebook/rocksdb/wiki/RocksDB-Tuning-Guide).
I store in arangodb quite large records and as a result there are many files (all of size ~65MB) created by rocksdb.  Eventually it can lead to `Error: Too many open files` ( [link](https://github.com/facebook/rocksdb/issues/4089)). So I wanted to minimize the amount of files by incresing its base size and multiplier. Is it possible to add these options to arangodb like `max_bytes_for_level_base`.

**Comment by jsteemann** [comment]
The extra options are exposed via PR #11468. The PR is supposed to land in ArangoDB 3.7.

**Comment by jsteemann** [comment]
PR just got merged into devel, which will eventually be released as 3.7 GA.

**Comment by Simran-B** [comment]
Available from v3.7.1 on.
