### ISSUE TITLE
After recovery agency, the db server and coordinator meet error "ERROR [92522] {agencycomm} Cannot find an agency persisted in RAFT 8|"

### ISSUE THREAD

**Issue by bonniechen1119** [arangodb/arangodb#11484]
## My Environment

* __ArangoDB Version__:        3.6.2
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   ArangoDB Starter
* __Configuration__:               Three Agency, Two DB Server and One coordinator in different server
* __Infrastructure__:              own 
* __Operating System__:        Centos

## Steps to reproduce

1. ArangoDB Starter start three agency in three server
2. ```arangod --server.endpoint tcp://0.0.0.0:8529 --cluster.my-address tcp://x.x.x.x:8529 --cluster.my-role COORDINATOR --server.jwt-secret-keyfile arangodb.secret --cluster.agency-endpoint tcp://x.x.x.x:8531 --cluster.agency-endpoint tcp://x.x.x.x:8531 --cluster.agency-endpoint tcp://x.x.x.x:8531 --database.directory /var/lib/arangodb3/coordinator start a coordinator```
3. ```arangod --server.endpoint tcp://0.0.0.0:8530 --cluster.my-address tcp://x.x.x.x:8530 --cluster.my-role DBSERVER  --server.jwt-secret-keyfile arangodb.secret --cluster.agency-endpoint tcp://x.x.x.x:8531 --cluster.agency-endpoint tcp://x.x.x.x:8531 --cluster.agency-endpoint tcp://x.x.x.x:8531 --database.directory /var/lib/arangodb3/dbserver start two db servers```
4. And one day one of agency is shutdown and unable to restart we setup another server to recovery(https://www.arangodb.com/docs/devel/administration-starter-recovery.html )
5. After new agency up successfully, we find db server and coordinator meet error
__Problem__:
```
After recovery failed agency, db server and coordinator meet error, error is "ERROR [92522] {agencycomm} Cannot find an agency persisted in RAFT 8|""
```
__Expected result__:
No error

**Comment by OmarAyo** [comment]
Hi @bonniechen1119,

Can you please attach all the logs from all the servers (agents, dbservers and coordinators) along with the starter logs (usually called `arangodb.log`)

Also, can you please attach the commands you use for starting the agents 

Thanks,

**Comment by maxkernbach** [comment]
Hi @bonniechen1119,

This ticket is being closed as inactive due to the date of the last activity on it.

If you believe this was done in error, please comment or create a new issue.
