### ISSUE TITLE
non system databse return isSystem == true

### ISSUE THREAD

**Issue by SisMaker** [arangodb/arangodb#11493]
## My Environment

* __ArangoDB Version__:  3.6.2      
* __Storage Engine__:  RocksDB           
* __Deployment Mode__:   Single Server    
* __Deployment Strategy__:  ArangoDB Starter 
* __Configuration__:  notable server settings             
* __Infrastructure__:  own              
* __Operating System__: centos       
* __Total RAM in your machine__:   10Gb     
* __Disks in use__:  SSD      
* __Used Package__:   RedHat .rpm           

## Component, Query & Data

__Affected feature__: 

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. 
2. 
3. 

__Problem__: i create a new database name "newtest1" and i have connect this datebase,
then i use http API(GET /_api/database/current) get return 'isSystem == true '

__Expected result__: isSystem == false

**Comment by OmarAyo** [comment]
Similar behaviour reported in https://github.com/arangodb/arangodb/issues/11243

**Comment by SisMaker** [comment]
thanks
