### ISSUE TITLE
Full search for Ukraine language

### ISSUE THREAD

**Issue by menesty** [arangodb/arangodb#11528]
I want to know how to use fulltext index for Ukrainian language? If not how it can be add, search in documentation but did not found how to connect dictionary like in postgresql
Thanks for answer

**Comment by Simran-B** [comment]
Hi @menesty,
what exactly do you want to achieve? Case-insensitive, word-based search using the normal full-text index type? With stopword removal, or what would be the dictionary for?

Tokenization into words and case conversion is provided by ICU, but I'm unsure whether the ICU data file we currently ship contains Ukrainian (`uk`). Also see https://github.com/arangodb/arangodb/issues/7111

The full-text index uses the server language, i.e. the ICU processing is based on that language. The language can be set on startup with `--default-language uk`. Give it a try and see if things like `FOR doc IN coll SORT doc.attr RETURN doc.attr` sorts Ukrainian strings correctly. If it doesn't then the ICU data file is probably missing Ukrainian.

ArangoSearch, our advanced full-text search engine, depends on ICU as well. So does the Ukrainian support for tokenization and case conversion. It does not take the language rules regarding the lexicographic order into account in queries like `SEARCH doc.attr > "..."` however. Stopword removal is possible, but stemming is not available as the Snowball stemmer does not support Ukrainian. Russian is supported, but not sure if it's applicable to Ukrainian text in a meaningful way.

**Comment by Simran-B** [comment]
Hi @menesty,
we haven't heard from you in a while. I'm closing the ticket for now, but feel free to re-open with some more information.
