### ISSUE TITLE
TTL Index does not work with long millisecond timestamps

### ISSUE THREAD

**Issue by mok-liee** [arangodb/arangodb#11522]
## My Environment

* __ArangoDB Version__:        3.6.0
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               nothing special
* __Infrastructure__:               own
* __Operating System__:        Debian 9.12
* __Total RAM in your machine__:        16Gb
* __Disks in use__:        HDD
* __Used Package__:              Debian or Ubuntu .deb

## Component, Query & Data

__Affected feature__:
TTL Indexes

__Problem__:
{timestamp: 1588257810} work,
{timestamp: 1588257810000} work not

__Expected result__:
{timestamp: 1588257810} work,
{timestamp: 1588257810000} work

**Comment by mpoeter** [comment]
Yes, this is clearly stated in the [documentation](https://www.arangodb.com/docs/3.6/indexing-ttl.html):
> The numeric date time values for the index attribute need to be specified **in seconds** since January 1st 1970 (Unix timestamp).

If you want to use timestamps with milliseconds you can use ISO formatted datetime strings.

**Comment by mok-liee** [comment]
Ahhh, nice. I only looked at the HTTP API for creating index and there was no hint. But i think its okay. Thank you!
