### ISSUE TITLE
AQL: key is interpreted as literal in RETURN {attr: val}

### ISSUE THREAD

**Issue by CoDEmanX** [arangodb/arangodb#1152]
Minimal example:

```
FOR attr IN ["titel", "jahr"]
    FOR doc IN fo
        RETURN {attr: doc[attr]}
```

Invalid JSON will be returned, with every key being `"attr": ...`, it should be `"titel"` and `"jahr"`.

To be interpreted as string literal, one would use `RETURN {"attr": ...}`.

Workaround: `RETURN ZIP([attr], [...])`

**Comment by jsteemann** [comment]
Thanks for the pointer. I used that as an inspiration to implement a prototype for AQL, too:
http://jsteemann.github.io/blog/2015/02/03/using-dynamic-attribute-names-in-aql/

Note that this has not been committed yet, but it seems to work in general and might be a good way to go ahead.
