### ISSUE TITLE
a filter with "*" is very slow.

### ISSUE THREAD

**Issue by liuxiong888** [arangodb/arangodb#11562]
Dear  Jan,you can use the test DB I send to u last time:

## My Environment

* __ArangoDB Version__:    3.6.3.1-1     
* __Storage Engine__:         RocksDB   
* __Deployment Mode__:   Single Server    
* __Deployment Strategy__:    Manual Start   
* __Configuration__:             
* __Infrastructure__:       own
* __Operating System__:    centos7  
* __Total RAM in your machine__:    8GB
* __Disks in use__:      15G/50G
* __Used Package__:              none
## Component, Query & Data  QUERY

__Affected feature__:
A filter  y.name="*" is VERY SLOW,but
a filter  y.name="鸿庆" or any string else is normal  

__AQL query (if applicable)__:
let tmp = (for r in my_gpro_gResource
           filter r.gcId =="1596176426" and r.resourceType == 2 and r.status == 1 return r._key) 
           
let xx =(for p in my_gpro_persons
    filter p.treeKey in tmp    and (p.dynastic == 1) 
     return p
    )
for y in xx
     filter    y.name == "*" 
  return y 
 

__AQL explain (if applicable)__: search dcoument name == "*"

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. set y.name="*"   time cost 6s~80s
2. set y.name="X" ,time cost 20ms
3 we save the result with out filter to a static document , then the cost of  y.name="*"  is also change to [20ms.] 

__Problem__:
WHY？

__Expected result__:
Should the same

**Comment by jsteemann** [comment]
If an index is present on the `name` attribute in `my_gpro_persons`, it should be used to find all index entries with the specified name.

If searching for `*` is then way slower than searching for other strings, e.g. `鸿庆`, I guess this is due to many more documents existing with a `name` attribute of `*` than with a name attribute of `鸿庆`.

You can try this by checking the number of matches for the given search strings, i.e.
``` 
FOR y IN my_gpro_persons FILTER y.name == "*" COLLECT WITH COUNT INTO l RETURN l
``` 
and
``` 
FOR y IN my_gpro_persons FILTER y.name == "鸿庆" COLLECT WITH COUNT INTO l RETURN l
```
If the former query returns a lot more documents than the second, then it needs to process a lot more documents, even though it can find the documents via the index.
The query still needs to do all post-filtering on the documents returned via the index, because there are further conditions such as `p.treeKey in tmp and (p.dynastic == 1)`.

**Comment by liuxiong888** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Dear JanThing is no so simple.Of course the * sting is a little more than some sting else.But the total result data set is only 140 without filter. There are  about 4 is * So Add a filter of yname==“*”  should not take so much more time (more than 100 times) .I wish you can test the case on our database ,The backup server is still there. 
    
         
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                liux
                            
                    
                        
                            
                                    liux@qingtime.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 05/8/2020 14:46，Jan<notifications@github.com> wrote： 




If an index is present on the name attribute in my_gpro_persons, it should be used to find all index entries with the specified name.

If searching for * is then way slower than searching for other strings, e.g. 鸿庆, I guess this is due to many more documents existing with a name attribute of * than with a name attribute of 鸿庆.

You can try this by checking the number of matches for the given search strings, i.e.

FOR y IN my_gpro_persons FILTER y.name == "*" COLLECT WITH COUNT INTO l RETURN l



and

FOR y IN my_gpro_persons FILTER y.name == "鸿庆" COLLECT WITH COUNT INTO l RETURN l



If the former query returns a lot more documents than the second, then it needs to process a lot more documents, even though it can find the documents via the index.

The query still needs to do all post-filtering on the documents returned via the index, because there are further conditions such as p.treeKey in tmp and (p.dynastic == 1).



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by jsteemann** [comment]
I tried the following queries on an older backup:

* `FOR y IN my_gpro_persons COLLECT WITH COUNT INTO l RETURN l`. This returns 10047620. So there are around 10 M docs in the collection in total.
* `FOR y IN my_gpro_persons FILTER y.name == "*" COLLECT WITH COUNT INTO l RETURN l`: this returns 551264, so there are 550 K docs with `name == "*"`.
* `FOR y IN my_gpro_persons FILTER y.name == "鸿庆" COLLECT WITH COUNT INTO l RETURN l`. This returns 111, so there are only 111 docs with `name == "鸿庆"`.

This explains why searching for "*" is so much slower than searching for "鸿庆".
Both queries will use the index on "name", but the former one will process 550 K documents and apply the other filters on it, and the latter one will only have to do it for 111 documents. So it has to process 5000 times less documents.

**Comment by liuxiong888** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Dear Jan   Even there much more rows with  * in original table , but as you see .The filter result only has 140 ,then we add the filter of yname=“*”   So  It still very slow is very confuse for us.
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                liux
                            
                    
                        
                            
                                    liux@qingtime.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 05/8/2020 16:58，Jan<notifications@github.com> wrote： 




I tried the following queries on an older backup:



FOR y IN my_gpro_persons COLLECT WITH COUNT INTO l RETURN l. This returns 10047620. So there are around 10 M docs in the collection in total.

FOR y IN my_gpro_persons FILTER y.name == "*" COLLECT WITH COUNT INTO l RETURN l: this returns 551264, so there are 550 K docs with name == "*".

FOR y IN my_gpro_persons FILTER y.name == "鸿庆" COLLECT WITH COUNT INTO l RETURN l. This returns 111, so there are only 111 docs with name == "鸿庆".



This explains why searching for "*" is so much slower than searching for "鸿庆".

Both queries will use the index on "name", but the former one will process 550 K documents and apply the other filters on it, and the latter one will only have to do it for 111 documents. So it has to process 5000 times less documents.



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by jsteemann** [comment]
It does not matter how many results are in the final result, but how many documents the query needs to process.

Here is a detailed example, using the profile output.
**Searching for "鸿庆"**:
```
Query String (258 chars, cacheable: false):
 let tmp = (for r in my_gpro_gResource filter r.gcId =="1596176426" and r.resourceType == 2 and 
 r.status == 1 return r._key)  let xx =(for p in my_gpro_persons filter p.treeKey in tmp and 
 (p.dynastic == 1) return p ) for y in xx filter y.name == "鸿庆" return y

Execution plan:
 Id   NodeType            Calls   Items   Runtime [s]   Comment
  1   SingletonNode           1       1       0.00001   * ROOT
 22   SubqueryStartNode       1       2       0.00002     - LET tmp = ( /* subquery begin */
 20   IndexNode               1       3       0.00045       - FOR r IN my_gpro_gResource   /* hash index scan, projections: `_key`, `resourceType`, `status` */    FILTER ((r.`resourceType` == 2) && (r.`status` == 1))   /* early pruning */   
  6   CalculationNode         1       3       0.00002         - LET #11 = r.`_key`   /* attribute expression */   /* collections used: r : my_gpro_gResource */
 23   SubqueryEndNode         1       1       0.00002     - RETURN  #11 ) /* subquery end */
 19   IndexNode               1     111       0.02178     - FOR y IN my_gpro_persons   /* hash index scan */    
 11   CalculationNode         1     111       0.00033       - LET #17 = ((y.`treeKey` in tmp) && (y.`dynastic` == 1))   /* simple expression */   /* collections used: y : my_gpro_persons */
 12   FilterNode              1       0       0.00009       - FILTER #17
 18   ReturnNode              1       0       0.00000       - RETURN y

Indexes used:
 By   Name            Type   Collection          Unique   Sparse   Selectivity   Fields       Ranges
 20   idx_31767023    hash   my_gpro_gResource   false    false        13.46 %   [ `gcId` ]   (r.`gcId` == "1596176426")
 19   idx_560401812   hash   my_gpro_persons     false    false        71.53 %   [ `name` ]   (y.`name` == "鸿庆")

Query Statistics:
 Writes Exec   Writes Ign   Scan Full   Scan Index   Filtered   Exec Time [s]
           0            0           0          113        111         0.02514
```
**Searching for "*"**:
```
Query String (257 chars, cacheable: false):
 let tmp = (for r in my_gpro_gResource
 filter r.gcId =="1596176426" and r.resourceType == 2 and r.status == 1 return r._key)
 let xx =(for p in my_gpro_persons
 filter p.treeKey in tmp and (p.dynastic == 1)
 return p
 )
 for y in xx
 filter y.name == "*"
 return y

Execution plan:
 Id   NodeType            Calls    Items   Runtime [s]   Comment
  1   SingletonNode           1        1       0.00001   * ROOT
 22   SubqueryStartNode       1        2       0.00001     - LET tmp = ( /* subquery begin */
 20   IndexNode               1        3       0.00045       - FOR r IN my_gpro_gResource   /* hash index scan, projections: `_key`, `resourceType`, `status` */    FILTER ((r.`resourceType` == 2) && (r.`status` == 1))   /* early pruning */   
  6   CalculationNode         1        3       0.00002         - LET #11 = r.`_key`   /* attribute expression */   /* collections used: r : my_gpro_gResource */
 23   SubqueryEndNode         1        1       0.00002     - RETURN  #11 ) /* subquery end */
 19   IndexNode             552   551264       1.30473     - FOR y IN my_gpro_persons   /* hash index scan */    
 11   CalculationNode       552   551264       0.26558       - LET #17 = ((y.`treeKey` in tmp) && (y.`dynastic` == 1))   /* simple expression */   /* collections used: y : my_gpro_persons */
 12   FilterNode              1        0       0.09198       - FILTER #17
 18   ReturnNode              1        0       0.00000       - RETURN y

Indexes used:
 By   Name            Type   Collection          Unique   Sparse   Selectivity   Fields       Ranges
 20   idx_31767023    hash   my_gpro_gResource   false    false        13.46 %   [ `gcId` ]   (r.`gcId` == "1596176426")
 19   idx_560401812   hash   my_gpro_persons     false    false        71.53 %   [ `name` ]   (y.`name` == "*")

Query Statistics:
 Writes Exec   Writes Ign   Scan Full   Scan Index   Filtered   Exec Time [s]
           0            0           0       551266     551264         1.66458
```
As you can see, both queries use the same index on "name".
However, the query for "鸿庆" will find 113 documents in the index, and the query for "*" will find 551266, so 5000 times more documents.
And then, the query for " 鸿庆" will apply the filter condition `((y.treeKey in tmp) && (y.dynastic == 1))` to just 113 documents, whereas the query for "*" will apply it on 551266 documents. This is computationally more expensive, because it is 5000 times more work.

**Comment by maxkernbach** [comment]
Hi @liuxiong888,

Did you have a chance to check jsteemann's latest message?
