### ISSUE TITLE
AQL IF ELSE branch

### ISSUE THREAD

**Issue by imtrobin** [arangodb/arangodb#11575]
* __ArangoDB Version__:       3.6.2

Hi, Is there a IF to branch in AQL? I know there is a ternary operator but that doesn't cut it. I'm doing

```
LET id =( FOR x in XXX
                FILTER blah
               RETURN x)
I want to check if id is null, RETURN {} , else do more logic
```

**Comment by dothebart** [comment]
AQL supports the tenary operator:
https://www.arangodb.com/docs/stable/aql/operators.html#ternary-operator
Please note that both branches /may/ be executed.

**Comment by imtrobin** [comment]
It's ok, I got a workaround with ignoreErrors.

**Comment by imtrobin** [comment]
I just realize ignoreErrors is not the way to go, as it will hide write conflicts. I'm not sure how the ternary operator can help here.

AQL
```
LET id =( FOR d in docs
                FILTER d.attribute == "yes"
                LIMIT 1
               RETURN d)

// IF D is not null, I want to run update, not throw
 Update id with { ''other':'xxx'} in d
return id
```

**Comment by dothebart** [comment]
maybe `UPSERT` can do what you intend to? 
https://www.arangodb.com/docs/stable/aql/data-queries.html#data-modification-queries

**Comment by imtrobin** [comment]
hmm, not really seeing how upsert can help.

**Comment by Simran-B** [comment]
Can't you just do `FILTER LENGTH(id) > 0 UPDATE ...`?

**Comment by vasandharaj** [comment]
> 
> 
> Can't you just do `FILTER LENGTH(id) > 0 UPDATE ...`?

Filter worked like charm @Simran-B  thanks a lot :)
