### ISSUE TITLE
Possible memory leak ?

### ISSUE THREAD

**Issue by zz123happy** [arangodb/arangodb#11577]
## My Environment

* __ArangoDB Version__:       3.6.2  
* __Storage Engine__:             RocksDB 
* __Deployment Mode__:       Cluster 
* __Deployment Strategy__:   Manual Start in Docker 
* __Configuration__:      some important configs          
```
[server]
statistics = false

[rocksdb]
total-write-buffer-size = 1073741824
use-direct-reads = true
write-buffer-size = 67108864
max-write-buffer-number = 15
min-write-buffer-number-to-merge = 2
table-block-size = 4096
enforce-block-cache-size-limit = true
block-cache-size = 77309411328

[cache]
size = 17179869184
```
* __Infrastructure__:               own 
* __Operating System__:        CentOS Linux release 7.3.1611 (Core) 
* __Total RAM in your machine__:        128G 
* __Disks in use__:        SSD 
* __Used Package__:     CentOS and arangodb/arangodb:3.6.2         

## Component, Query & Data

__Affected feature__:

java driver version 6.6.1

__AQL query (if applicable)__:

a SQL like `FOR v, e, p IN 2..2 OUTBOUND @user GRAPH 'graph'...... return  ...`

__Size of your Dataset on disk__:

about 2TiB 

__Replication Factor & Number of Shards (Cluster only)__:

 1 Replication 16 Shards

## Steps to reproduce

1.  start a cluster with 3 gency 4 dbserver and 4 coordinator
2. import the users_relation data and restart the dbsever
3. only query with the aql for sometime, the memory used by arangodb is always rising...

__Problem__:
![image](https://user-images.githubusercontent.com/10650762/81543541-c826db80-93a8-11ea-96e1-67cd2f1c27ea.png)

![image](https://user-images.githubusercontent.com/10650762/81543931-5b601100-93a9-11ea-91ed-192f62d42863.png)

point out in one picture
![image](https://user-images.githubusercontent.com/10650762/81543289-6ebeac80-93a8-11ea-87bc-2984cda8efa3.png)

I have set the block cache to 12Gi ,the problem coming sooner.

![image](https://user-images.githubusercontent.com/10650762/81544358-fe188f80-93a9-11ea-9563-31aa368d7c40.png)

Ram used will reach 99% over time, is there some memory leak in arangodb? I have seen some issues and set /proc/sys/vm/overcommit_memory to 0 and close the statistics, but it did not work.

__Expected result__:
find the problem. Thanks.

**Comment by maxkernbach** [comment]
Hi @zz123happy,

1. Is the memory usage only increasing while the stated AQL graph traversal query is running or also while the system is idle?
2. How long does the traversal query run and how big are the involved collections?

FYI: You can set the available memory in the docker container via the environment variable [`ARANGODB_OVERRIDE_DETECTED_TOTAL_MEMORY`](https://www.arangodb.com/docs/stable/programs-arangod-env-vars.html), which has been introduced in version 3.6.3.

**Comment by zz123happy** [comment]
Hi @maxkernbach 
  1. The memory usage only increasing while the stated AQL graph traversal query is running
  2. It runs about 400ms, the ruturn collection about 6KB

**Comment by maxkernbach** [comment]
Hi @zz123happy,

Thanks for your reply.

Just to be sure: Do you run exactly the same query every time or e.g. change the bind parameter `@user` between the query runs? I am asking this since involving different edges for each run would explain the growth of the edge cache.

Would it be possible to rerun your test with a much smaller edge cache (for example `--cache.size 2000000000` in order to set it to 2 GB) and monitor the memory usage once again?

**Comment by zz123happy** [comment]
Hi @maxkernbach

Thanks very much for your reply.

1. The '@user' changes every times.
2. I will do it later.

**Comment by zz123happy** [comment]
Hi @maxkernbach

I have seen some configs about rocksdb, refer: https://github.com/facebook/rocksdb/wiki/Write-Buffer-Manager , I have set the cache_index_and_filter_blocks to 'true' (cache_index_and_filter_blocks_with_high_priority, pin_top_level_index_and_filter is also set to true) and recompiled from source. I restart the dbserver with block-cache-size set to 48G, now the memory is limit to about 74G  from a week.
![image](https://user-images.githubusercontent.com/10650762/82542821-30ce3f00-9b85-11ea-921d-41d7c5d5ae05.png)

I think if we can add some config from arangodb to control the config.

**Comment by dothebart** [comment]
Hi, 
Arangodb 3.7.2 with these new options is available for download.
for details please see:
https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/
