### ISSUE TITLE
Transactions don't lock or block

### ISSUE THREAD

**Issue by imtrobin** [arangodb/arangodb#11589]
* __ArangoDB Version__:       3.6.2

I'm testing transactions like so

```
Action
   db.TestCollection.Update (id, attribute: "CHANGED FROM TRANSACTION")
   db._query (LET s = SLEEP (10) FOR d in collection return d)  // sleep, the FOR does nothing
Collections
  Write  TestCollection
```

When the above is running and waiting on SLEEP, I use the arango Query browser to update TestCollection immediately

From browser
```
  if (db.TestCollection.attribute == "New")   // pseudo code
      db.TestCollection.Update (id, attribute: "CHANGED FROM BROWSER")

```
Both methods return fine, and the final attribute is CHANGED FROM TRANSACTION

1.  When the browser query is run, I switched to see the collection if the attributes changed to CHANGED FROM BROWSER. Nope, it didn't.

So the Update Failed, but it reports as success. I was expecting it to fail when the transaction is locking it.

2. 2nd problem. The code changes  the attribute and SLEEP, but it does not write the value until 10 seconds is up, therefore the browser query is able to attribute still as "New", and proceed to update. I would expect the Update from the transaction to take place immediately, not at the end.

Is above behavior intended?

**Comment by Simran-B** [comment]
Hi @imtrobin,
please help me to understand what you are trying to test.

- What kind of transaction do you use? JS or Stream Transactions?
- Can you share the actual code of the transactions instead of pseudo-code? (You may anonymize it)
- How do you run the transactions? The ArangoDB Web UI doesn't support running either type of transaction.
- How does your dataset look like, or rather the documents you try to update?

**Comment by imtrobin** [comment]
I'm using JS. the structure is bit more compilcated, but here it is

```
class Cluster // stoed in ClusterCollection
{
   public Dictionary <string,string> Resources; // contains id from Resource
} 
class Resource // stored in ResourceCollection
{
    public string State =  "Available"
}
```
So I find an available Resource from ResourceCollection in Cluster.Resources, and change its state

Transaction
``` 
Action = $"function ()
{ 
 const db = require ('@arangodb').db;
 const resourcesID = Object.keys (db.ClusterCollection.document ('{clusterID}').Resources);
 var resourceAvailableID =  null;
 for (var i = 0; i < resourcesID.length; ++i)
 {
     const m = db.ResourceCollection.document (resourcesID [i])
     if (m.State == 'Available')
     {
         resourceAvailableID = resourcesID [i];
         break;
     }
 }
  if (null != resourceAvailableID)
 {
     db.ResourceCollection.update (resourceAvailableID, {{State : 'ChangedFromTransaction'}});
     // simulate delay
     //Problem the Update is not done until sleep is complete, AQL write can succeed but don't report error
     db._query ('LET s = SLEEP (10) FOR d in ResourceCollection RETURN d');
     return resourceAvailableID;
 }
 return '';
}",
Collections = new PostTransactionRequestCollections
{
    Read    = new [] { "ClusterCollection" },
    Write   = new [] { "ResourceCollection" }
}
```

While I'm running this, I also execute the same above in AQL (from browser, but the state is ChangedFromBrowser)  without the SLEEP.  I just put 1 resource as "Available", so both the transaction and AQL operates of same document.

Since transaction modifies first, but did not apply the UPDATE until the SLEEP is complete, the AQL version finds the same document and modifies it.

Order of operation
1. Run transaction
2. Transaction UPDATE is done, sleep for 10 secs
3. Run AQL (same without sleep)
4. Both finds and returns the same document ID, final state is ChangedFromTransaction

**Comment by Simran-B** [comment]
Not entirely sure, but I think you describe a lost update situation. What you probably want to do is to set `ignoreRevs` to `false` so that either query aborts with precondition failed:
https://www.arangodb.com/docs/3.6/data-modeling-operational-factors.html#ensuring-consistent-atomic-updates

**Comment by imtrobin** [comment]
I took a look at that, but that's not an good option for me, as it means I need to read the document before I can update it. Imagine if its an IOT device that sends status via update periodically to arangodb, it does not need to read the data

What I would like is a BLOCK, like I describe here [11576](https://github.com/arangodb/arangodb/issues/11576), I will put the details here

So the whole thing is like a semaphore (Monitor in c#), where the other thread waits

Thread One
id = Find available Resource ResourceCollection
(BLOCK document id)
Update document id
(RELEAESE BLOCK document id)

Thread Two (From IOT)
(BLOCK document id)
Update document id
(RELEASE BLOCK document id)

Instead of failing , it will block until it becomes available (or timeout). I also realized that once I use transaction, I have to do transaction on everything , or I will get conflicts like 
[9702](https://github.com/arangodb/arangodb/issues/9702)

**Comment by Simran-B** [comment]
> I need to read the document before I can update it

What do you mean? It's for the case that you read the document from the server some time ago, and want to write back changes but ensure that the document wasn't changed by someone else in the meantime. If you didn't read the document, then you don't have its _rev and the scenario doesn't apply.

There is no need to block and release the document to update it, the update is always atomic. However, if two or more concurrent writes occur to the same document, then a write-write conflict error will be returned for all but one of the requests. I have yet to test this, but I think that RocksDB actually waits for a bit before it aborts the concurrent requests with this error (1000ms, `--rocksdb.transaction-lock-timeout`). If all you want is a way to fire & forget requests and don't need access to the previous values of the document, but just update some attributes, then the upcoming insert-update in v3.7 should work for you:

https://www.arangodb.com/docs/devel/release-notes-new-features37.html#insert-update-and-insert-ignore

**Comment by Simran-B** [comment]
Using a collection `test` with a blank document with _key `"foo"` and AQL queries via curl, it doesn't look like increasing `--rocksdb.transaction-lock-timeout` helps to to avoid write-write conflicts.

```bash
# In case of docker container, run this first: apk add curl coreutils
date +"%T.%3N"
{
  curl -d '{"query": "LET s = SLEEP(3) UPDATE \"foo\" WITH { attribute: \"QUERY 1\" } IN test RETURN NEW" }' http://localhost:8529/_api/cursor
  echo
  date +"%T.%3N"
} &

{
  sleep 1s
  curl -d '{"query": "UPDATE \"foo\" WITH { attribute: \"QUERY 2\" } IN test RETURN NEW" }' http://localhost:8529/_api/cursor
  echo
  date +"%T.%3N"
} &
wait
```

After one second:
`{"result":[{"_key":"foo","_id":"test/foo",,"attribute":"QUERY 2"}], ... ,"error":false,"code":201}`

Two seconds later:
`{"code":409,"error":true,"errorMessage":"AQL: write-write conflict (while executing)","errorNum":1200}`

The timeout was set to 8000ms.

Also tried JS transactions but with the same result, except that QUERY 2 returns a code 200 instead of 201:

```bash
date +"%T.%3N"
{
  curl -d '{"collections": {"write": ["test"]}, "action": "function(){ var db = require(\"@arangodb\").db; return db._query(`LET s = SLEEP(3) UPDATE \"foo\" WITH { attribute: \"QUERY 1\" } IN test RETURN NEW`) }" }' http://localhost:8529/_api/transaction
  echo
  date +"%T.%3N"
} &

{
  sleep 1s
  curl -d '{"collections": {"write": ["test"]}, "action": "function(){ var db = require(\"@arangodb\").db; return db._query(`UPDATE \"foo\" WITH { attribute: \"QUERY 2\" } IN test RETURN NEW`) }" }' http://localhost:8529/_api/transaction
  echo
  date +"%T.%3N"
} &
wait
```
