### ISSUE TITLE
Documentation error?

### ISSUE THREAD

**Issue by oliverhausler** [arangodb/arangodb#11599]
https://www.arangodb.com/docs/stable/administration-cluster.html#replacingremoving-a-db-server states:

> The requirement for this operation is that no collection in any of the databases has a `replicationFactor` greater or equal to the current number of DB-Servers minus one.

Shouldn't this be 

"(...) `replicationFactor` greater to the current number of DB-Servers minus one."?

If we have 4 servers and want to retire one, a `replicationFactor` or `3` should work, or not?

**Comment by Simran-B** [comment]
Hi @oliverhausler,
you are right, `or equal` needs to be removed. Corrected & clarified by https://github.com/arangodb/docs/pull/436

Thanks for reporting!
