### ISSUE TITLE
V8 update for 2.4?

### ISSUE THREAD

**Issue by CoDEmanX** [arangodb/arangodb#1160]
A V8 update is scheduled for 2.4 xmas release according to the roadmap. Which version will it be, and which harmony features will be available?

I'm particularly interested template strings, which allow for multi-line string literals in backticks without end-of-line escaping:

```
`a long
multi-line string`

"the current"\
"way to go"
```

It would allow for nicely formatted AQL query strings in JavaScript files.

**Comment by CoDEmanX** [comment]
@pluma: filed report https://github.com/arangodb/aqbjs/issues/5

@jsteemann: thanks for checking. I asked some V8 guys and they told me template string are available in the yet unstable 3.31. According to them, an upgrade from 3.29 to 3.31 shouldn't be much pain - I hope you will update V8 in ArangoDB to 3.31+ as it becomes stable.

Rest parameters, the spread operator and destructuring assignments aren't coded as of now, although there's some work going on. It appears to be rather difficult whatsoever to implement these ES6 features and I wouldn't expect them to be available in V8 any time soon.

**Comment by jsteemann** [comment]
@CoDEmanX : interesting, thanks for sharing the info.
