### ISSUE TITLE
@arangodb JS references

### ISSUE THREAD

**Issue by David-Lor** [arangodb/arangodb#11631]
While developing a Foxx microservice for ArangoDB, it would be useful to have the `@arangodb` package references. Does an installable package exist somewhere?

**Comment by Simran-B** [comment]
Hi @David-Lor,
what do you mean by "package references"? Something like TypeScript type definitions?

There is an overview over the ArangoDB-specific modules here:
https://www.arangodb.com/docs/stable/appendix-java-script-modules.html#arangodb-specific-modules

You can find the code here:
https://github.com/arangodb/arangodb/tree/devel/js/client/modules/%40arangodb
https://github.com/arangodb/arangodb/tree/devel/js/common/modules/%40arangodb
https://github.com/arangodb/arangodb/tree/devel/js/server/modules/%40arangodb

**Comment by David-Lor** [comment]
@Simran-B Yeah, something like TS types (or vanilla hinting, if that's a thing), so we can have hints for the methods while writing code for microservices.

For example, on JS (not TS) the package "joi" has the "@types/joi" package which provide such a thing for it:
![imagen](https://user-images.githubusercontent.com/17401854/82240486-ccb83a80-993a-11ea-8686-d6e2038d8612.png)

**Comment by David-Lor** [comment]
I just found the package [@types/arangodb](https://www.npmjs.com/package/@types/arangodb), which provides such a thing (i wasn't aware about these "@types" packages on JS).
