### ISSUE TITLE
UI inconsistent: Document browser shows "No documents" but also "63 doc(s)" and pagination

### ISSUE THREAD

**Issue by oliverhausler** [arangodb/arangodb#11636]
3.6.2

The UI is inconsistent. For example, displaying a collection shows me there are documents (and there are) but I don't see them. Reloading a few times helps, sometimes. Just by looking at the UI I can tell events are not properly handled as older events are not canceled and will surface at a later point, when navigating too fast, leaving state a mess.

![Screen Shot 2020-05-18 at 09 49 59](https://user-images.githubusercontent.com/8090341/82220972-5b05cf80-98ed-11ea-9b8e-5c7202b4ffd7.png)

**Comment by maxkernbach** [comment]
Hi @oliverhausler,

Which browser are you currently using? Could you check whether the problem persists when using a different browser?

In addition, could you please execute the following `arangosh` commands multiple times and check if the output is consistent?

- `db.items.toArray()`
- `db.items.count()`

This will help us to understand if this issue is only affecting the UI.

**Comment by oliverhausler** [comment]
I don't think it's browser dependent.

- Chrome Version 81.0.4044.138 (Official Build) (64-bit)
- same problem occurs in webkit (Safari/Mac)

_Will post Arangoshell later._

**Comment by oliverhausler** [comment]
Consistent:

![image](https://user-images.githubusercontent.com/8090341/82493290-b682b980-9ab5-11ea-9d7f-00aa669e4d86.png)

**Comment by lnogol** [comment]
Likely related - I see this in the console quite often `Failed to load resource: net::ERR_HTTP2_PROTOCOL_ERROR`

**Comment by dothebart** [comment]
hm, at least ArangoDB 3.6 doesn't have HTTP2 - @lnogol do you use an alpha / preview release?

**Comment by lnogol** [comment]
@dothebart no, `3.6.2`

I did find a solution, though. I disabled HTTP2 in NGINX and disabled CloudFlare proxying (as it also uses HTTP2) and voila, the UI is consistent

it only works when the full chain is HTTP1.1, nothing HTTP2 can be in the way

- browser -> nginx (HTTP1.1) -> coordinator (HTTP1.1) **works**
- browser -> CF (HTTP2) -> nginx (HTTP1.1) -> coordinator (HTTP1.1) **ERR_HTTP2_PROTOCOL_ERROR**
- browser -> CF (HTTP2) -> nginx (HTTP2) -> coordinator (HTTP1.1)  **ERR_HTTP2_PROTOCOL_ERROR**

according to https://stackoverflow.com/questions/58215104/whats-the-neterr-http2-protocol-error-about, it can happen for multiple reasons. the browser error is too obscure

**Comment by oliverhausler** [comment]
I assume 3.7 solves the issue as it apparently does http/2. When is the ETA for 3.7?

**Comment by oliverhausler** [comment]
@maxkernbach You may want to remove the "Waiting for user reply" tag. Should be solved.

**Comment by dothebart** [comment]
Hi, ArangoDB Alpha 2 including HTTP2 support has been anounced at: 
https://www.arangodb.com/2020/03/alpha-2-arangodb-3-7/
So you can try out the HTTP2 support using these; thanks @lnogol for clarifying, if its working with 3.7 we may document it for older versions and close this. 

@oliverhausler  We expect 3.7 to be ready by Q3.

**Comment by Simran-B** [comment]
Added a known issues entry for 3.6 just in case: https://github.com/arangodb/docs/pull/526

**Comment by erkaperka** [comment]
Hey,

I was researching a similar (possibly the very same?) issue yesterday. Just adding a comment on this issue should someone else, just like I did, end up here via a Google search looking for solutions – best-case scenario, it might help others in the same situation! 😊

<hr>

I have recently put ArangoDB (and its web UI) behind a [Cloudflare Tunnel](https://www.cloudflare.com/products/tunnel/) protected by [Cloudflare Access](https://www.cloudflare.com/products/zero-trust/access/). Everything appeared to be working fine and as expected, up until I came across the mismatch between "number of documents" and the empty listing of documents. Queries executed via the 'queries' page in the web UI were also not going through successfully.

Completely baffled by all of this - *why does it work fine without Cloudflare, even when proxied by **other** similar proxy services such as ngrok* - I nailed it down to this specific request, to begin with:

![image](https://user-images.githubusercontent.com/382783/160225017-d84a7736-f9ed-4033-a753-099cb821f26c.png)

<img width="504" alt="image" src="https://user-images.githubusercontent.com/382783/160225061-42987a03-2a44-4304-b63e-a16aacebee0d.png">

The error message understandably made no sense to me at that stage, but after some time and research, I managed to figure out that it **appears** to be there as a result of two things combined:

1) Cloudflare is adding a `transfer-encoding: chunked` header when proxying some requests (which, I guess, in a way makes sense as that is okay in line with the HTTP/1.1 specs).

2) ArangoDB does not accept chunked `transfer-encoding` headers. (ref [1](https://www.arangodb.com/docs/stable/http/general.html#:~:text=ArangoDB%20doesn%E2%80%99t%20support%20POST%20with%20Transfer%2DEncoding%3A%20chunked%20which%20forbids%20the%20Content%2DLength%20header%20above.) & [2](https://github.com/arangodb/arangodb/issues/4886#:~:text=In%20order%20to%20make%20use%20of%20ArangoDB%2C%20please%20make%20sure%20the%20HTTP%20clients%20in%20use%20are%20not%20using%20chunked%20transfer%20encoding.), with a more detailed explanation as to why not [here](https://github.com/arangodb/arangodb/issues/4886#issuecomment-376816593)) - I *feel*, although I am winging it a bit here as this is not what I am best at, that this would also explain the `net::ERR_HTTP2_PROTOCOL_ERROR` error mentioned previously in this issue as the header is not compliant with HTTP2. I have not looked into this in detail to be able to confirm anything, but it *does not sound unreasonable* to me that CF (or for that matter, reverse proxies in general) gets "confused" when HTTP/1.1 servers do not fully comply with the specs.

**Nonetheless: the easiest solution at this stage then?** Have Cloudflare disable chunked encoding, either by specifying so in your configuration file (see [this guide](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/configuration-file/ingress/#disablechunkedencoding) in their docs) or directly via the command line:

<pre>
$ cloudflared tunnel --url localhost:8529 <b>--no-chunked-encoding</b> run your-tunnel-slug
</pre>

Cheers!
