### ISSUE TITLE
Add ability to document body responses to FoxxController HTTP methods

### ISSUE THREAD

**Issue by seanmikalson** [arangodb/arangodb#1164]
There is no way currently to document the json responses for FoxxController HTTP methods and as a result, when the swagger documentation is generated, no information is provided as to what fields/data will be returned. The swagger code gen expects response classes or responses to be documented, and will not generate client sdks if this documentation is missing.

There should be the ability to document responses to HTTP requests in a similar way as how incoming JSON bodies are documented.

**Comment by pluma** [comment]
Fixed via FOTF.
