### ISSUE TITLE
arangodb 3.6.3.1 Compile error

### ISSUE THREAD

**Issue by Neverstop** [arangodb/arangodb#11651]
## My Environment

* __ArangoDB Version__:        3.6.3.1
* __Storage Engine__:             RocksDB

__Problem__: 
I tried to compile the source code of 3.6.3.1, but found the following error. I am using gcc7.3.0:
/root/arangodb-3.6.3.1/arangod/Aql/InputAqlItemRow.h:65:41: error: temporary of non-literal type ‘arangodb::aql::SharedAqlItemBlockPtr’ in a constant expression
       : _block(nullptr), _baseIndex(0) {}
                                         ^
In file included from /root/arangodb-3.6.3.1/arangod/Aql/InputAqlItemRow.h:29:0,
                 from /root/arangodb-3.6.3.1/arangod/IResearch/IResearchExpressionContext.h:28,
                 from /root/arangodb-3.6.3.1/arangod/IResearch/ExpressionFilter.h:28,
                 from /root/arangodb-3.6.3.1/arangod/IResearch/ExpressionFilter.cpp:24:
/root/arangodb-3.6.3.1/arangod/Aql/SharedAqlItemBlockPtr.h:32:7: note: ‘arangodb::aql::SharedAqlItemBlockPtr’ is not literal because:
 class SharedAqlItemBlockPtr {
       ^~~~~~~~~~~~~~~~~~~~~
/root/arangodb-3.6.3.1/arangod/Aql/SharedAqlItemBlockPtr.h:32:7: note:   ‘arangodb::aql::SharedAqlItemBlockPtr’ has a non-trivial destructor

Deleted the constexpr of the constructor in file InputAqlItemRow.h and succeeded
Is it the version of gcc I am using?

__Expected result__:

**Comment by dothebart** [comment]
https://github.com/arangodb/arangodb/blob/v3.6.3.1/VERSIONS has all the versions that were used for our binaries.

**Comment by jsteemann** [comment]
@Neverstop : we are internally building our binaries with g++ 9.2 and 9.3, which are known to work well.
Older versions of g++ lack support of some of the c++17 features we use, so things may not compile there.
IIRC, g++ 8.2 was also very capable and likely still works, but g++ 7 is likely too old already.

**Comment by Simran-B** [comment]
The problem seems to be solved, thus closing the ticket.
