### ISSUE TITLE
arangodb 3.6.3.1 cmake error

### ISSUE THREAD

**Issue by Neverstop** [arangodb/arangodb#11681]
## My Environment

* __ArangoDB Version__:        3.6.3.1

__Problem__: 
Here are my steps:
1. Unzip the source package
2.mkdir build; cd build
3.cmake -USE_OPTIMIZE_FOR_ARCHITECTURE=On -DASM_OPTIMIZATIONS=0 -DUSE_FAILURE_TESTS=Off -DUSE_JEMALLOC=Off -DBASE_C_FLAGS="-fstack-protector-all -fPIE" -DBASE_CXX_FLAGS="-fstack-protector-all -fPIE" -DBASE_LD_FLAGS="-Wl,-z,now -pie" -DVERBOSE=On ..

errors:
-building for git revision:
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Backtrace_LIBRARY (ADVANCED)
    linked by target "iresearch-static" in directory /root/arangodb-3.6.3.1/3rdParty/iresearch/core
    linked by target "arango" in directory /root/arangodb-3.6.3.1/lib
    linked by target "arangoimport" in directory /root/arangodb-3.6.3.1/arangosh
    linked by target "arangorestore" in directory /root/arangodb-3.6.3.1/arangosh
    linked by target "arangovpack" in directory /root/arangodb-3.6.3.1/arangosh
    linked by target "arangoexport" in directory /root/arangodb-3.6.3.1/arangosh
    linked by target "arangodump" in directory /root/arangodb-3.6.3.1/arangosh
    linked by target "arango_shell" in directory /root/arangodb-3.6.3.1/arangosh
    linked by target "arangobench" in directory /root/arangodb-3.6.3.1/arangosh
    linked by target "arangosh" in directory /root/arangodb-3.6.3.1/arangosh

-Configuring incomplete, errors occurred!
See also "/root/arangodb-3.6.3.1/build/CMakeFiles/CMakeOutput.log".
See also "/root/arangodb-3.6.3.1/build/CMakeFiles/CMakeError.log".

If I don't add -pie in BASE_LD_FLAGS, it will succeed...
But the company has requirements to meet safe compilation options.
Thanks for the help~~ 
__Expected result__:

**Comment by KVS85** [comment]
@Neverstop you need to have [backtrace](https://www.man7.org/linux/man-pages/man3/backtrace.3.html) library being installed (even if `-DUSE_BACKTRACE=Off` which is by default).

If you are at Ubuntu it could be installed through `libc6-dev` package. In case of CenOS `compat-glibc-*` packages are required.

**Comment by Neverstop** [comment]
I compile on ubuntu, I have installed libc6-dev
uname -a ：Linux kwephisprb05240 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:32:18 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux

apt install libc6-dev：
Reading package lists... Done
Building dependency tree
Reading state information... Done
libc6-dev is already the newest version (2.27-3ubuntu1)

**Comment by Simran-B** [comment]
@Neverstop What version of GCC do you use?

**Comment by Neverstop** [comment]
gcc:9.3.0  cmake:3.10.2

**Comment by KVS85** [comment]
@Neverstop can you please move `-pie` to `-DCMAKE_EXE_LINKER_FLAGS`?

**Comment by Neverstop** [comment]
still error，i figure it out with the following command,move -pie to BASE_FLAG:
cmake -DUSE_BACKTRACE=Off -USE_OPTIMIZE_FOR_ARCHITECTURE=On -DASM_OPTIMIZATIONS=0 -DUSE_FAILURE_TESTS=Off -DUSE_JEMALLOC=Off -DBASE_C_FLAGS="-mtune=generic -fstack-protector-all -fPIE -pie" -DBASE_CXX_FLAGS="-mtune=generic -fstack-protector-all -fPIE -pie" -DBASE_LD_FLAGS="-Wl,-z,now" -DVERBOSE=On ..

and specify -fPIE  in the following file:
./3rdParty/V8/v7.1.302.28/gypfiles/standalone.gypi:line 762
./3rdParty/V8/v7.1.302.28/third_party/icu/icu.gyp:line 388

make -j12
and make succeed.thank you for helping me
