### ISSUE TITLE
Unable access coordinator and call health api return "service unavailable due to startup or maintenance mode"

### ISSUE THREAD

**Issue by bonniechen1119** [arangodb/arangodb#11689]
## My Environment

* __ArangoDB Version__:       3.6.2
* __Storage Engine__:            RocksDB
* __Deployment Mode__:      Cluster
* __Deployment Strategy__:   ArangoDB Starter
* __Configuration__:              Three Agency, three DB Server and three coordinator in different server
* __Infrastructure__:             own
* __Operating System__:        Centos

## Steps to reproduce

1. Setup cluster and the cluster health is green
2. Create database and import datas

__Problem__:
Suddenly the COORDINATOR fail, and the get /_admin/cluster/health return 503 error messase is service unavailable due to startup or maintenance mode
and then check the log, log display:
2020-05-26T12:29:25Z [21653] WARNING [e1807] {v8} giving up waiting for unused V8 context after 60.000000 s
2020-05-26T12:29:26Z [21653] ERROR [a235e] {threads} scheduler loop caught exception: unable to acquire V8 context in time
__Expected result__:
get the cluster health

**Comment by Simran-B** [comment]
Hi @bonniechen1119,

how do you import your data? What size and format is the dataset?

Can you share any additional logs?

**Comment by bonniechen1119** [comment]
We use spark import our data, format is json
I check the agency and db server it seem no error log and check coordinator trace log, it display error ,please check  attachment
[arangodb.log](https://github.com/arangodb/arangodb/files/4693084/arangodb.log)

**Comment by Simran-B** [comment]
Hi @bonniechen1119,
there's nothing that would help to track the problem down in the log unfortunately. Can you provide more information please?

- What are the hardware specs (CPU, amount of memory, storage medium etc.)?
- What's the average size in bytes per document in JSON format that you try to import?
- How many documents in total? In parallel?
- If you take the JSON which appears to make the server go into maintenance mode if imported through Spark, can you import it with arangoimport successfully or does that also trigger that problem?
- Can you share your configuration and the minimal code and data needed to reproduce the problem?

Thanks

**Comment by Simran-B** [comment]
Hi @bonniechen1119,
as we have too little information I am closing the issue for now. Please feel free to re-open with additional info.
