### ISSUE TITLE
Question about the arangodb memory consumption

### ISSUE THREAD

**Issue by telco2011** [arangodb/arangodb#11719]
## My Environment

* __ArangoDB Version__:        3.6.0, 3.3.23
* __Storage Engine__:             RocksDB for 3.6.0 / MMFiles for 3.3.23
* __Deployment Mode__:        Single Server in a docker container in both cases
* __Deployment Strategy__:   Using docker compose.
* __Configuration__:               server settings
* __Infrastructure__:               own
* __Operating System__:        Ubuntu 16.04.6 LTS
* __Total RAM in your machine__:        64GB but the docker container that use arangodb 3.6.0 is limited to 15GB
* __Disks in use__:        SSD
* __Used Package__:              Docker - official Docker library

__Problem__: I am using ArangoDB with docker compose. I am using the version 3.3 but I want to migrate to 3.6. At this moment, I have both version running in a machine with 64GB but if I run the `docker stats` command, I can see that the ArangoDB 3.6 is using a huge amount of memory comparing it with version 3.3. For this reason, I have had to limit the container memory to 15GB not to saturated the machine memory. This is the result of the `docker stats`:

| CONTAINER ID |     NAME     | CPU %  | MEM USAGE / LIMIT   | MEM %  | NET I/O        | BLOCK I/O       | PIDS |
|:------------:|:------------:|--------|---------------------|--------|----------------|-----------------|------|
| b31bae35674d | arangodb-3-6 | 10.55% | 14.53GiB / 14.65GiB | 99.21% | 2.4GB / 4.01GB | 7.68GB / 32.2GB | 58   |
| 8e6151634839 | arangodb-3-3 | 1.19%  | 1.853GiB / 62.88GiB | 2.95%  | 21.4GB / 518GB | 2.3GB / 5.38GB  | 78   |

As you can see, the arangodb 3.3 is using almost 2GB meanwhile arangodb 3.6 is using all the 15GB. Both databases are doing the same thing, they store the same data and they are queried by the same services with the same queries.

__Question__: Is it possible to configure the arangodb 3.6 not to use lots of memory? Is there any configuration to optimize this comsumption?

**Comment by dothebart** [comment]
Please have a look at: 
https://www.arangodb.com/docs/stable/tutorials-reduce-memory-footprint.html
and:
https://www.arangodb.com/docs/stable/programs-arangod-env-vars.html

**Comment by telco2011** [comment]
Thanks for the information. I’ve used the second one link to configure the docker containers and now, the memory behavior is better.
