### ISSUE TITLE
foxx-manager exit codes

### ISSUE THREAD

**Issue by stackmagic** [arangodb/arangodb#1175]
Where can I find the exit values of foxx-manager? I'd like to script my (re)deployment and want to be sure my own exit values don't interfere with whatever foxx-manager uses.

I think this should be documented somewhere (for other commandline tools too). And/Or having a range of safe exit values that aren't used by any arango cli tool would useful too for people writing scripts.

If you could point out the place(s) or patterns to grep for in the source I'd be quite happy already

**Comment by neunhoef** [comment]
foxx-manager uses the "--javascript.execute" command line option to execute a single command and then terminate. I think it would be good to implement this: if that command throws an exception with an error code this error code is reflected in the exit code of the arangosh executable. Then foxx-manager script could report the error as well. I do not really know how difficult this.

**Comment by dothebart** [comment]
fixed by 7780b48539718a59bcec00a82788dd9712dfe853
