### ISSUE TITLE
Translate with csv import not working

### ISSUE THREAD

**Issue by dijbi** [arangodb/arangodb#11765]
## My Environment

* __ArangoDB Version__:        3.6.2 
* __Storage Engine__:             RocksDB 
* __Deployment Mode__:       Single Server on localhost
* __Used Package__:               Windows 10

## Component, Query & Data

__Affected feature__:
Import in csv
__Dataset__:

Simple CSV file with ; separator (file converted from Excel by opening it in notepad and saving it with utf8 format) : 
id;Label;Label_Fr
tree@root;Root Tree; Tronc
tree@1;First Leaf;Première feuille ééoeàù

command 
arangoimport.exe --server.username root --type csv --collection "t" --server.database "Test" --separator ";"  --translate "id=_key" --file ".\test.csv"

__Problem__:
Error with translation while importing a simple csv.
can not translate id to _key 

__Expected result__:
id converted to _key, since it respects [the key convention ](https://www.arangodb.com/docs/stable/data-modeling-naming-conventions-document-keys.html)

**Comment by Simran-B** [comment]
Works as expected for me:

![image](https://user-images.githubusercontent.com/7819991/83779310-110e3f00-a68c-11ea-946c-dc1798276f93.png)

Can you check in VS Code whether the file has a byte order mark or not?

![image](https://user-images.githubusercontent.com/7819991/83779795-add0dc80-a68c-11ea-8c93-a2e236fa0327.png)

If it says `UTF-8 with BOM` in the bottom right corner, then click on it, `Save with Encoding` and select `UTF-8`.

A BOM won't be stripped and will become part of the first column like `{BOM}id`, and the translation will subsequently fail to map it to _key.

**Comment by dijbi** [comment]
BINGO !

BTW (if i did search correctly), there's not much on encoding in the arangoimport part of the documentation.  [A fix to add to the docs ?](https://github.com/arangodb/docs/blob/master/3.6/programs-arangoimport-details.md)

**Comment by Simran-B** [comment]
Great! As far as I can tell, the only supported encoding is UTF-8 without BOM. I already created an internal ticket to warn about byte order marks and unsupported encodings, but will make sure to document what's currently supported as well.
