### ISSUE TITLE
<question>How to check arangodb status

### ISSUE THREAD

**Issue by la6803** [arangodb/arangodb#11782]
## My Environment

* __ArangoDB Version__:        3.6
* __Storage Engine__:             RocksDB
* __Deployment Mode__:      Cluster
* __Deployment Strategy__:   ArangoDB Starter
* __Configuration__:               I started on one server1 using the "arangodb --starter.mode=cluster --starter.data-dir=/my/directory/dir/arangotest2 --all.cluster.min-replication-factor=3" code.
The rest of the servers started using the "arangodb --starter.mode=cluster --starter.data-dir=/my/directory/dir/arangotest2 --starter.join server1" code.

* __Infrastructure__:               
* __Operating System__:        Centos
* __Total RAM in your machine__:        
* __Disks in use__:        SSD | HDD
* __Used Package__:             RedHat .rpm 

## Component, Query & Data

__Affected feature__:

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__: replication factor=3

## Steps to reproduce

1. 
2. 
3. 

__Problem__:

__Expected result__:
I have clustered 3 servers in arangodb. To make sure these three servers are working, you need to check the cluster status in your code. How to check?
Is there a way to do it without accessing the shell?

**Comment by maxkernbach** [comment]
Hi @la6803,

You can check the Cluster health from the UI as shown in the screenshot below. There is a **HEALTH** status on the top right and further details in the **NODES** tab.

![image](https://user-images.githubusercontent.com/9152640/83866799-a6f7a780-a728-11ea-9171-fc5b0fa294be.png)

Another way is to [monitor the cluster health](https://www.arangodb.com/docs/stable/http/cluster-health.html#queries-the-health-of-cluster-for-monitoring) via the HTTP API.

Hope this helps

**Comment by la6803** [comment]
Thank you, but I have to check with [https://www.arangodb.com/docs/stable/http/cluster-health.html#queries-the-health-of-cluster-for-monitoring](url) 
이 문서를 확인했지만 "GET /_admin/cluster/health" 이 명령어를 어떤 형식으로 써야 하는지 모르겠습니다. arangosh에 접속하여 코드를 실행해야 합니까?

**Comment by la6803** [comment]
curl -X GET http://localhost:8529/_db/_system/_open/health.json --dump -
