### ISSUE TITLE
unable to get fullCount in the AQL response

### ISSUE THREAD

**Issue by RohanKumbhar1** [arangodb/arangodb#11828]
I'm trying to get fullcount in the result but its not working below is the AQL i'm using

1. FOR prod IN products 
OPTIONS { fullCount:true}
 LIMIT 1
 RETURN prod

2.FOR prod IN products 
OPTIONS { count:true}
 LIMIT 1
 RETURN prod

please help to get the total count of results with help of AQL

**Comment by Simran-B** [comment]
Hi @RohanKumbhar1,
the only available options in a `FOR … OPTIONS` construct are `indexHint` and `forceIndexHint`: https://www.arangodb.com/docs/stable/aql/operations-for.html#options

`count` and `fullCount` cannot be set in AQL. They are options that can be set for a cursor:
https://www.arangodb.com/docs/stable/http/aql-query-cursor-accessing-cursors.html

In Arangosh:
https://www.arangodb.com/docs/stable/aql/invocation-with-arangosh.html#counting-with-a-cursor
https://www.arangodb.com/docs/stable/aql/invocation-with-arangosh.html#setting-options

With arangojs:
http://arangodb.github.io/arangojs/7.0.0-preview.1/classes/_database_.database.html#query
http://arangodb.github.io/arangojs/7.0.0-preview.1/modules/_database_.html#queryoptions

To return the total amount of documents in a collection in AQL, you can do:
`RETURN LENGTH(products)`

If you want to apply filters and count the amount of documents in AQL, you could do:
```js
FOR prod IN products
  FILTER prod.type == "foobar"
  COLLECT WITH COUNT INTO count
  RETURN count
```
Note that you cannot use a LIMIT in this case.

**Comment by Simran-B** [comment]
Closing this ticket as answered. Feel free to re-open if you have more questions regarding the fullCount option.
