### ISSUE TITLE
HTTP/REST error code in case of badly encoded json

### ISSUE THREAD

**Issue by stackmagic** [arangodb/arangodb#1184]
When I send some Umlaute without encoding them to the Rest Interface, I get an `1227 invalid document type` from ArangoDB. The [Documentation](https://docs.arangodb.com/ErrorCodes/README.html) says "Will be raised when there is an attempt to create a document with an invalid type", which is doubly misleading IMO because I was patching a pre-existing document and the actual problem was the bad encoding.

```
PATCH /_db/beerdb/_api/document/germany/cologne?waitForSync=false HTTP/1.1
Host: localhost:8529
Content-Length: 26
Content-Type: application/x-www-form-urlencoded

{"name":{"de":"Kölsch"}}

400 Bad Request
Server: ArangoDB
Connection: Keep-Alive
Content-Type: application/json; charset=utf-8
Content-Length: 80

{"error":true,"errorMessage":"invalid document type","code":400,"errorNum":1227}
```

When I run it trough apache commons-lang's StringEscapeUtils.escapeJavascript, I get `K\u00F6lsch` for the value and all is well.

**Comment by bubnenkoff** [comment]
@jsteemann is it same issue? http://stackoverflow.com/questions/37027066/vibed-cant-send-data-to-arangodb-invalid-document-type

**Comment by Simran-B** [comment]
@bubnenkoff: the links is invalid?!

**Comment by bubnenkoff** [comment]
@Simran-B http://stackoverflow.com/questions/37034311/arangodb-cant-send-request-with-curl
