### ISSUE TITLE
Arangosh: clearing of characters broken (backspace / delete keys)

### ISSUE THREAD

**Issue by CoDEmanX** [arangodb/arangodb#1187]
1. If you hit backspace with no character entered, `arangosh [...]> ` disappears, and re-appears if you type something in
2. If you delete characters and the code wraps to a 2nd line past the length of the string<br>`arangosh [...]> `, the last character won't be cleared and will thus appear as many times as you hit <kbd>Backspace</kbd> / <kbd>Del</kbd>. The superfluous chars are removed as soon as the line length drops low enough (around character 80 of the entered code).

http://youtu.be/LxQ0zg-fOoY

Windows 8.1,
ArangoDB 2.3.1

**Comment by CoDEmanX** [comment]
Found a few command line parsers:

http://tclap.sourceforge.net/
http://www.busybox.net/about.html (was claimed to contain cmd parsing capabilities incl. utf-8 support)
http://www.boost.org/doc/libs/1_57_0/doc/html/program_options.html
http://thrysoee.dk/editline/

**Comment by jsteemann** [comment]
The command-line parsing is not the problem I think (that would be about picking about start parameters). What we are after is some readline-like functionality, with ideally identical semantics AND support for Windows. An idea would be to look at what node and the mysql client use on Windows.

**Comment by CoDEmanX** [comment]
Good thinking, NodeJS even has REPL if you start it without parameters and worked fine for me on Windows so far!

**Comment by jsteemann** [comment]
NodeJS uses libuv for all its console I/O and printing. The Windows part of it is a 2000+ line file solely for the tty parts.
MySQL client uses conio on Windows, and some hand-crafted read/write functions for the REPL.

So there seems to be no drop-in replacement for readline as Windows and Non-Windows tty handling is very different.

**Comment by fceller** [comment]
Fixed in 2.4.2

**Comment by fceller** [comment]
There still is an issue with the history. Sometimes the line is garbled. I. e. first a "5 line command", then a "2 line command". Scrolling in the history breaks the output.
