### ISSUE TITLE
Foxx Manifest: Shared mount points

### ISSUE THREAD

**Issue by stackmagic** [arangodb/arangodb#1189]
(from #1170) It would be nice to be able to mix and match controllers with the same url prefix.

    "controllers": {
        "/houses": "controllers/houses.js",
        "/owners": "controllers/owners.js"
    }

The above exposes the houses.js as /houses and owners.js as /owners.

This of course won't work, the last write wins:

    "controllers": {
        "/": "controllers/houses.js",
        "/": "controllers/owners.js"
    }

One way to do this could be:

    "controllers": {
        "/": [
              "controllers/houses.js",
            , "controllers/owners.js"
        ],
        "/admin": [
              "controllers/houses.js",
            , "controllers/owners.js"
        ]
    }

In this case it would probably also make sense to check for conflicts in mount points. If both controllers in the example had a handler with the same path like "/hello/:id" then an error should be thrown during startup of the foxx app.

**Comment by pluma** [comment]
Note that you can have multiple controllers but they have to be in the same file (it's not possible to import controllers because of the magical comments).

**Comment by pluma** [comment]
Fixed via FOTF.
