### ISSUE TITLE
Rocksdb returns compaction error after using arangoimport over 500 json files

### ISSUE THREAD

**Issue by loredra** [arangodb/arangodb#11905]
## My Environment

* __ArangoDB Version__:        3.6.2
* __Storage Engine__:            RocksDB 
* __Deployment Mode__:       Single Server 
* __Deployment Strategy__:   Manual Start >
* __Operating System__:       Ubuntu 18.04
* __Total RAM in your machine__:       e.g. 64Gb. If
* __Disks in use__:        SSD nvme
* __Used Package__:              Ubuntu .deb

## Component, Query & Data

__Dataset__:
10 millions docs. Around 250GB in json

## Steps to reproduce

1. Clean install of arango
2. Do an loop arangoimport over 500 files each around 400MB, sometimes there are duplicate _key
3. After around 5,6 millions successfully imported, the error happen

__Problem__:
from arangoimport log: 
1. No space left on device while appending to... "some sst file name"( And this sst files does not exist on file system)

from arangolog
1. Compaction error from rocksdb. Database set to read-only
2. Background settings sync failed
3. All operation after return no space left on device pointing to an non-existing .sst. Cannot drop or delete, have to clean install for arango to work again.

__Expected result__:
When compaction goes wrong, at least restarting arango should clean it up.

__Some context__:
1. The point in which the compaction error happens differs from each run. Sometimes it is at about 6 millions, sometimes 8 millions.
2. The import script
```
for files
do
arangoimport --file "$file" --threads 1 --type json --collection "A" --batch-size 805306360 --on-duplicate "ignore" --server.database "test" --server.password "password"
done
```

**Comment by Simran-B** [comment]
Hi @loredra,
what sticks out to me is **No space left on device**. Can you confirm that the drive was actually full? If so, then errors are expected. If there was plenty of space left, then it might be a different problem (did the creation of the .sst fail for some reason?).

**Comment by loredra** [comment]
@Simran-B 
Sorry for the late reply, it was actually out of disk problem. It seemed that when arangodb does compaction, it used additional disk space. After compaction is done, the disk goes down. It means that at the time we see the error, the disk space appear to be not full yet, thus we incorrectly attribute this one to arango internal error.

**Comment by dothebart** [comment]
performance may change once your memory shortens, https://www.arangodb.com/docs/stable/tutorials-reduce-memory-footprint.html demonstrates how rocksdb behaves in the background. 
Please note that a huge batch size may result in large memory chunks needing to be allocated in the server to process it, so this is a setting you definitely want to tune. You also may want to (if you didn't already do) separate storage paths from the import data and the database itself.
