### ISSUE TITLE
Foxx Controller: exposing the actual request url

### ISSUE THREAD

**Issue by stackmagic** [arangodb/arangodb#1191]
(from #1170) 

> My background is Java and the 'requirements' regarding url info etc. is probably the same for all 'appservers' and apps deployed in them. I think Arango Foxx apps are equal in that regard to a Java Webapp on say, a Jetty: There's an applicationContext and several Servlets/Controllers.
> 
> This is a [nice overview](http://theholyjava.wordpress.com/2014/03/24/httpservletrequest-requesturirequesturlcontextpathservletpathpathinfoquerystring/) of the information available:
> 
>     URL METHODS BREAKDOWN (JavaEE 6):
>     - requestURL  = http://localhost:8080/myapp/users/profile.xhtml
>     - requestURI  = /myapp/users/profile.xhtml = contextPath + servletPath + pathInfo
>     - contextPath = /myapp = the first segment after hostname (unless the app runs and the root app with context /)
>     - servletPath = /users/profile.xhtml (part after contextPath to the servlet that handled the request)
>     - pathInfo    = null (what remains after servletPath up to the queryString; would return '/dummy' if the url was '.../profile.xhtml/dummy?id=007')
>     - queryString = id=007
> 
> * [java servlet request object](http://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html)
> * [java servlet context object](http://docs.oracle.com/javaee/6/api/index.html?javax/servlet/http/HttpServletRequest.html)
> 
> For the moment, I could live with using something like [URI.js](https://github.com/medialize/URI.js) but for that I'd need access to the full request url and I couldn't find that anywhere either.
> 
> My impression is, that handling of this kind of information is a bit of a patchwork *or* I haven't yet found the piece of documentation that explains this.
> 
> For a more generic solution, I'd suggest finding a global strategy on how to expose this information in a coherent and complete way so the user can do anything he wants with the request url. This information should be part of the request object so a before/after/around also has access to it, which is where I actually need it.

Thinking about this some more, I would like to have something along the lines of the handlers having access to essentially the full url that was used for the request, not as a single string but as an object on the request that contains all the components that make up the request. 

The components I see at the moment and their sources are:

* proto (`req.headers["x-forwarded-proto"] || req.protocol`) -- :+1:
* host (`req.headers["x-forwarded-host"]  || req.headers.host`) -- :+1:
* port (`req.headers["x-forwarded-host"]  || req.headers.host`) -- :+1:
* application mount point relative to root (`applicationContext.baseUrl`) -- :+1:
* controller mount point within application (`controller.urlPrefix` only if it was used when constructing the controller) -- :+1: / :x:
* handler mount point within controller -- :x:
* effective url used that invoked the handler (path without query params) -- :x:
* path info (if this is even supported by foxx. this would be `/app/ctrl/handler/<param>/<pathinfo1>/<pathinfo2>` when a handler was created with `/handler/:param`) -- :x:

So parts of the information is available and all that's missing is a wrapper/helper on the request to make access to it easier. For the rest, I don't know where to find the information.

**Comment by pluma** [comment]
Note to self:

Given a route `/qux/:baz/*` in a controller at `/bar` of an app mounted at `/foo` in a database `mydb` on a server listening on `localhost:8529` (HTTP), an absolute URL would look like this:

`http://localhost:8529/_db/mydb/foo/bar/qux/hello/world/etc?x=y`

with the following parts (in devel):

* **applicationContext.mount**: `/foo`
* **req.absoluteUrl()**: `http://localhost:8529/_db/mydb/foo/bar/qux/hello/world/etc?x=y`
* **req.database**: `mydb`
* **req.url**: `/foo/bar/qux/hello/world/etc?x=y`
* **req.path()**: `/bar/qux/hello/world/etc`
* **req.suffix**: `['world', 'etc']`
* **req.prefix**: `/qux/hello`
* **req.urlParameters.baz**: `hello`

**Comment by pluma** [comment]
Fixed via FOTF.
