### ISSUE TITLE
Cannot install arangodb and arangodb-client at the same time

### ISSUE THREAD

**Issue by F21** [arangodb/arangodb#1192]
I am using ansible to install arangodb using the Ubuntu apt repo here on Ubuntu Server 14.10 64-bit: https://www.arangodb.com/download

If I do:

```
sudo apt-get install arangodb arangodb-client
```

the installation fails, because both arangodb and arangodb-client's installers are trying to write to foxx.conf and terminates each other.

**Comment by obadasemary** [comment]
in 2.4.3 i can`t install arangodb and arangodb-client at the same time on ubuntu

**Comment by dothebart** [comment]
@obadasemary thats the intended behaviour - the client package is only there for machines where you don't want to install the server. The server package also contains the client. So the fix here basically is, that the package manager won't let you do this, rather than complaining about duplicate files during installation.

**Comment by obadasemary** [comment]
ok 
now after i install it 

i have this problem 

2015-02-10T12:25:30Z [11649] FATAL cannot start server: database directory is locked
More error details may be provided in the logfile '/var/log/arangodb/arangod.log'

**Comment by dothebart** [comment]
Is locked -> another arangod is already running.
stop it by issuing
sudo /etc/init.d/arangodb stop
start it by issuing 
sudo /etc/init.d/arangodb start

check for evenualy running arangods by issuing
ps -eaf |grep arangodb
or check for its active ports by issuing
sudo netstat -aplnt |grep arangodb

**Comment by obadasemary** [comment]
ok thank you 
it start now :+1:
