### ISSUE TITLE
 Is there an operation log for this？

### ISSUE THREAD

**Issue by liuzjccc** [arangodb/arangodb#11925]
Is there an operation log for this？Some data had been deleted, but I don't know who do it.Now I want to find the operation log that it can help me to know why the data lose.

**Comment by Simran-B** [comment]
Such logging including the user name who carried out an operation is available with the Auditing feature in the Enterprise Edition:
https://www.arangodb.com/docs/stable/security-auditing.html

**Comment by liuzjccc** [comment]
What you said is the access log.

**Comment by liuzjccc** [comment]
What I want is the operation log.

**Comment by Simran-B** [comment]
Not sure what your definition is of access vs. operation, but I would consider e.g. the creation of a database as operation, which is covered in by the auditing feature. Other then that, there is the regular logging, but if the respective log level for the relevant log topic wasn't set by the time the data was deleted, then there is no log information to determine who it was to my best knowledge. You might consider the write-ahead log an operation log, but it doesn't contain user information but only modification operations and they are managed by the storage engine.

**Comment by liuzjccc** [comment]
Where can I see the pre-write log you mentioned?

**Comment by Simran-B** [comment]
In case you use the RocksDB engine, you have to consult the RocksDB documentation:
https://github.com/facebook/rocksdb/wiki/Write-Ahead-Log

**Comment by liuzjccc** [comment]
Does ArangoDB have that log？

**Comment by Simran-B** [comment]
It's at the core of RocksDB, so I suppose that RocksDB as integrated into ArangoDB writes to its own WAL, but where to find the files (given they still exist) and how to interpret them is on you.

**Comment by dothebart** [comment]
https://en.wikipedia.org/wiki/Write-ahead_logging - its not human readable - Its a name for a core database technology to optimize on disk writing to minimize seek times etc.
