### ISSUE TITLE
How to recover data before Arango

### ISSUE THREAD

**Issue by Gotothistour** [arangodb/arangodb#11920]
Today, because of the misoperation, the Arango set was deleted. Then, I restored the database to the state of the previous day (because of the tension). Now the problem is, if I lost the data of the previous day, can I find the previous data (I find a log file, which contains_ Key does not exist in the current database collection),

## My Environment

* __ArangoDB Version__:       3.6.4-1
* __Storage Engine__:            RocksDB 
* __Deployment Mode__:     Single Server
* __Deployment Strategy__:   
* __Configuration__:               
* __Infrastructure__:               own 
* __Operating System__:       debian 10 amd64
* __Total RAM in your machine__:      10
* __Disks in use__:   SSD 40G  HDD 10G
* __Used Package__:               Debian 

## Steps to reproduce

1. I Drop MY Collection
2. I restore my databse ( the previous day  backup)
3. I lost this day data,now i want find it(i find a log file, which contains_ Key does not exist in the current database collection)

__Problem__:can i  find this day  data?

**Comment by Simran-B** [comment]
I'm afraid there is no way to bring back the lost data. Server log files contain very little information which one could use to reconstruct data. Even the Enterprise Edition auditing feature doesn't log the exact document mutations. The write-ahead logs have more information, but they are handled by RocksDB and are in a binary form that you cannot really decipher as a human. Chances are also that they were removed/compacted already some time after the deletion of the database(?).
