### ISSUE TITLE
Install arango db on Windows 10

### ISSUE THREAD

**Issue by srikanthRamanan** [arangodb/arangodb#11930]
## My Environment

* __ArangoDB Version__:        
* __Storage Engine__:             
* __Deployment Mode__:       
* __Deployment Strategy__:   
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:        
* __Total RAM in your machine__:        
* __Disks in use__:        
* __Used Package__:              

## Component, Query & Data

__Affected feature__:

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. 
2. 
3. 

__Problem__:

__Expected result__:

**Comment by srikanthRamanan** [comment]
Can anyone guide me through the downloading of arango db on Windows 10

**Comment by dothebart** [comment]
please have a look at 
https://www.arangodb.com/download-major/windows/

Cheers, 
Willi

**Comment by Simran-B** [comment]
Please include a description of the exact problem you face and a list of steps that you took, thanks.

**Comment by srikanthRamanan** [comment]
Hello everyone!!
I am a beginner in ArangoDB and not able to follow the instructions provided  in the official ArangoDB website in order to install ArangoDB on my laptop.
i have also downloaded the community version and i am clueless about the installation
i have also looked up in the internet for the same but was not able to find a suitable solution
i would be glad if anyone of you could run me through this process.
please let me know if there is anything that needs to be installed in order to run ArangoDB :))

ArangoDB Version:3.6.4
Operating System:Windows 10 64 bit
Total RAM in your machine:8 GB
Disks in use: C drive only one

**Comment by Simran-B** [comment]
What exactly are you struggling with?
It should only be a matter of downloading https://download.arangodb.com/arangodb36/Community/Windows/ArangoDB3-3.6.4_win64.exe, double-clicking it and then you step through the installer.

**Comment by srikanthRamanan** [comment]
Thank you very much for the download link. i think i downloaded the wrong version or so and i was facing a lot of issues as well
and now i am able to fully make use of Arango DB
Thanks Once again  and cheers
Stay Safe :)
