### ISSUE TITLE
Fulltext Index on Lists and Objects?

### ISSUE THREAD

**Issue by stackmagic** [arangodb/arangodb#1195]
I added a fulltext index on an object and it doesn't seem to do anything. Does the index support objects and lists? I'm also not sure if and when the index is built. Do I need to re-import the data for the index to be populated?

Here's a simple example of data like I store it:

```
{
    "name": {
        "de": "Bier",
        "en": "Beer"
    }
}
```

I would then create an index on `name` to index them and would query like this:

```
return FULLTEXT(objects, 'name', 'Bee')
```

But I always get an empty result.  Querying with the field `name.en` results in an error: `[1571] in function 'FULLTEXT()': no suitable fulltext index found for fulltext query on 'objects' (while executing)`

**Comment by jsteemann** [comment]
I just committed a few changes in `devel` (2.6) that make the fulltext index also include text values that are contained in direct sub-objects of the index attribute.

Previous versions of ArangoDB only indexed the attribute value if it was a string. Sub-attributes of the index attribute were ignored when fulltext-indexing.

Now, if the index attribute value is an object, the object's values will each be included in the fulltext index if they are strings. If the index attribute value is an array, the array's values will each be included in the fulltext index if they are strings.

For example, with a fulltext index present on the `translations` attribute, the following text values will now be indexed:

     var c = db._create("example");
     c.ensureFulltextIndex("translations");
     c.insert({ translations: { en: "fox", de: "Fuchs", fr: "renard", ru: "лиса" } });
     c.insert({ translations: "Fox is the English translation of the German word Fuchs" });
     c.insert({ translations: [ "ArangoDB", "document", "database", "Foxx" ] });

     c.fulltext("translations", "лиса").toArray();       // returns only first document
     c.fulltext("translations", "Fox").toArray();        // returns first and second documents
     c.fulltext("translations", "prefix:Fox").toArray(); // returns all three documents
