### ISSUE TITLE
System apps not shown, import error

### ISSUE THREAD

**Issue by Metamist** [arangodb/arangodb#1203]
Apps that are said to come with ArangoDB are not shown nor do they exist in my WebUI. Reinstalling does not fix it.
Also getting an import error when trying to import from github
http://pastebin.com/qE2aszXq

**Comment by jsteemann** [comment]
It looks like the temporary directory of arangod is not writeable for arangod.
Can you check what the temporary directory is and if it is writeable by the user (uid) or group (gid) that runs arangod?

**Comment by pluma** [comment]
@mchacki could you look into why the system apps don't show up in the new install app dialog? Some system apps (users, sessions, etc) need to be user-mountable.

**Comment by mchacki** [comment]
I will look into it.

**Comment by mchacki** [comment]
The system apps have been added to the App Store. and should now be visible.
@Metamist have you checked if there is problem with writablity of the temporary directory?
