### ISSUE TITLE
Cannot restore database from backups (server becomes read-only, activefailover setup)

### ISSUE THREAD

**Issue by amorroxic** [arangodb/arangodb#12138]
## My Environment

* __ArangoDB Version__:        3.4.10
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Active Failover 
* __Deployment Strategy__:   ArangoDB Starter 
* __Configuration__:               3 VMs
* __Infrastructure__:               Azure and own
* __Operating System__:        Centos 7 / Ubuntu 18.04
* __Total RAM in your machine__:        64GB / vm
* __Disks in use__:        SSDK
* __Used Package__:              .deb | .rpm 

I cannot restore the databases from backups, always had this problem - at times it was succeeding on Ubuntu, it fails every time on Centos now. 

```
arangorestore --server.username "<db-user>" --server.database "<db-name>" --input-directory "backup/" --overwrite true --batch-size 65535
```

It always fails with this message (triggered after about 1 minute, some objects get restored, some not):
```
2020-07-06T13:31:19Z [5177] ERROR {restore} Error while restoring data into collection '<collection>': got invalid response from server: HTTP 403: 'read only: server is in read-only mode' while executing 'restoring payload' with this payload: ''

2020-07-06T13:31:20Z [5177] ERROR {restore} got invalid response from server: HTTP 403: 'read only: server is in read-only mode' while executing 'restoring payload' with this payload: ''
```

Cluster was started with the ArangoDB starter like so

**vm1**
```
sudo /usr/bin/arangodb --starter.address=ip1 --starter.data-dir=/var/lib/arangodb/cluster --starter.join=ip1,ip2,ip3 --server.storage-engine=rocksdb --starter.mode=activefailover
```

**vm2**
```
sudo /usr/bin/arangodb --starter.address=ip2 --starter.data-dir=/var/lib/arangodb/cluster --starter.join=ip1,ip2,ip3 --server.storage-engine=rocksdb --starter.mode=activefailover
```

**vm3**
```
sudo /usr/bin/arangodb --starter.address=ip3 --starter.data-dir=/var/lib/arangodb/cluster --starter.join=ip1,ip2,ip3 --server.storage-engine=rocksdb --starter.mode=activefailover
```
Is there anything I can do? Someone please chime in if you happen to have any insights, blocked by db restoration with absolutely no idea on what to do next, there's no error I'm aware of which could explain this. 

Many thanks in advance!

**Comment by dothebart** [comment]
please note that ArangoDB 3.4 is EOL: 
https://www.arangodb.com/eol-notice/
Numerous improvements have been made to the replication code in the 3.5 release cycle. Please upgrade.

**Comment by Simran-B** [comment]
@amorroxic Can you try to restore the dump into a 3.6 setup and report whether the error occurs there still?
