### ISSUE TITLE
create or return document by example

### ISSUE THREAD

**Issue by sleepycat** [arangodb/arangodb#1216]
I think a method similar to the [find_or_create](http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-find_or_create_by) method in Ruby on Rails would be a good addition to AQL.
Its a really useful method because I don't have to worry about whether the document exists or about accidentially creating duplicate documents.

I had suggested this on the Google group a while back and originally was thinking of something like this:
```
 db._query('RETURN FIND_OR_INSERT(@@collection, @example)', {'@collection': "vertices", example: {foo: 'bar'}}).
[ 
  { 
    "_id" : "vertices/28690394539", 
    "_key" : "28690394539", 
    "_rev" : "28690394539", 
    "foo" : "bar" 
  } 
]
```
In that example, if a document is found that matches the provided example, it is returned. Otherwise a new document is created and returned.

Now that AQL is doing INSERTs with the new pseudo-values I am not sure the above approach feels quite right, but I still think there needs to be a way to conditionally create a document by example in a single AQL query.

It feels like this should be possible with existing AQL, but I've played a little and can't get it working. This is what I feel like I should be able to write:
```
arangosh [test]> db._query('LET foo = (FOR i IN vertices FILTER i == @example RETURN i) IS_OBJECT(foo) ? RETURN foo : INSERT @example IN vertices RETURN NEW',{example: {foo: "bar"}}).toArray()
JavaScript exception in file '/usr/share/arangodb/js/client/modules/org/arangodb/arangosh.js' at 104,11: [ArangoError 1501: syntax error, unexpected identifier near 'IS_OBJECT(foo) ? RETURN foo : IN...' at position 1:61 (while parsing)]
!    throw new ArangoError(requestResult);
```
That feels a little verbose... and a little non-obvious for people starting out, but it makes sense.

Any thoughts on what the right thing might be here?

**Comment by jsteemann** [comment]
A *find-or-create* operation cannot be represented in current AQL. 
There are a few reasons for this:
* the `INSERT` statement needs to be top-level. It cannot be nested inside a `LET` or be part of an expression.
* an `INSERT` will either insert a document and return it or, on duplicate key, not insert it and either fail or ignore the document (depending on statement configuration).
* `INSERT` will not look for existing documents with the same attributes, however, it will fail when there are unique-key violations.

So I think *find-or-create* really needs to be a special, separate AQL operation. Or, if not a special operation, it will require extensions to current AQL. Here is an imagined way to express a *find-or-create* in a future AQL:
```
FOR i IN 1..10
  LET docs = (
    FOR doc IN docs
      FILTER doc.value == i 
      LIMIT 1
      RETURN x
  )
  INSERT { value: i, whatever: "something" } IN docs IF LENGTH(docs) == 0
  RETURN LENGTH(docs) == 0 ? NEW : docs[0]
```
The currently missing features in the above query are conditional statements (the `IF`) and arbitrary expressions in any statements following the `INSERT`. I am not sure if it can be done like this, but both features would make sense on their own and would help to express several other patterns, too.

**Comment by jsteemann** [comment]
Since 2.6 there is an `UPSERT` command. It should support the *find-or-create* idiom like this:
```
UPSERT { foo: "bar" } INSERT { foo: "bar" } UPDATE { } RETURN NEW
```
This will insert the document if it does not exist and update it with nothing if it already exists.
In the end, it will return the new version of the document, which is the just-inserted document in the case of `INSERT`, or the umodified document in case of `UPDATE`.
