### ISSUE TITLE
GRAPH_TRAVERSAL: Question or Feature Request

### ISSUE THREAD

**Issue by clintwood** [arangodb/arangodb#1217]
I use graphs a lot from AQL!  One of the things I find myself doing often is using the GRAPH_TRAVERSAL in AQL to find all **_leaf_** vertices for a given start vertex.

Is there an easy way to do this?
For me this usually requires post filtering on the results or if the depth of all leaf vertices is known then by setting the minDepth and maxDepth options... but this does not work well for arbitrary depth graphs or leaf vertices with arbitrary document types...

If there is no easy way to solve this use case then I'd like to propose a
***Feature Request: negative values for minDepth & maxDepth to specify depth from leaf vertices***
as shown below:

Given a graph with vertices (obviously with edges between them) like:
```
start - A - B - C - D
      \ A - F - P
```
using options `{minDepth: -1, maxDepth: -1}` should yield vertices D & P
using options `{minDepth: -2, maxDepth: -3}` should yield vertices C, B & F, A
etc.

This is similar in concept to the JavaScript Array.prototype.slice function.

**Comment by clintwood** [comment]
Having a quick scan through the code it appears that a slight logic/filter change to [maxDepthFilter](https://github.com/triAGENS/ArangoDB/blob/cb9c7bad42509d27615867f1e90d78760ce61f23/js/common/modules/org/arangodb/graph/traversal.js#L576) and [minDepthFilter](https://github.com/triAGENS/ArangoDB/blob/cb9c7bad42509d27615867f1e90d78760ce61f23/js/common/modules/org/arangodb/graph/traversal.js#L586) (and some changes to [bounds checks](minDepthFilter) prior to these functions) could enable this _feature_.

**Comment by mchacki** [comment]
Hi, i also like this idea. Leafs are intresting for many use cases.
I think with your investigation you are right, these will be the places to be modified.
I personally do not think it is too much of an effort to enable it.

**Comment by clintwood** [comment]
Awesome!
One implementation issue I see is that the filter functions `max/minDepth` are called as the `path.vertices` are being built which means it may be difficult to do this without knowing the final `path.vertices.length` up front... But then I'm really not that familiar with this codebase...

**Comment by jsteemann** [comment]
I would like the feature, too. But I am not sure about a potential implementation.
The filters are executed before a vertex is visited (in pre-order traversal) and before the expander function has determined the in- or outgoing connections for the vertex. At this point, there is no way to determine whether the vertex is a leaf node, or how long the path will become. So filtering here with a regular filter and using minDepth / maxDepth will probably not work.

After thinking a bit about this for some time, I have the following suggestion, but I am not sure if it is any good:
* leave `filter` and `expander` functions as they are
* introduce an optional `expandVisitor` function that will be invoked if present and when the connecting edges of a vertex are defined. At this point it is known if a vertex does have further connections are not. If not, then we have found a leaf node and know the path length.

I have put together a small example using that uses the [World graph](https://docs.arangodb.com/Traversals/ExampleData.html). Here's how I would invoke it: https://gist.github.com/jsteemann/c9157c89fe0812639869
And here's the required modification for the depth-first traversal: https://gist.github.com/jsteemann/9b38fe2daec31168639d
Note that in my example, I am not using the regular `visitor` to produce the result, but only the new `expandVisitor` function. In my example, the function prints out something, but it could also assemble the results that should be returned. 

Note that this is not a full implementation. It cannot be used in breadth-first or from AQL. It's just a basic idea with request for comments.

**Comment by clintwood** [comment]
@jsteemann, the `expandVisitor` sounds like a good solution!  As per my post, agreed that `minDepth / maxDepth` would not work...

I'm assuming `expandVisitor` would be usable from AQL via `options` (like `followEdges`, `filterVertices`, etc.)?

**Comment by jsteemann** [comment]
Just another idea that @mchacki had: do not use a separate visitor (like the expandVisitor), but pass the connections determined by the expander function to the visitor function as an optional argument. This way everything could be done with a single visitor function (that could determine the leave nodes or anything else). If this is the way to go, then we would make this available from AQL via specifying user functions as visitor.

**Comment by clintwood** [comment]
@jsteemann, @mchacki, ok great, would be nice to have this feature... If I get to figure out how to do this I will post a gist...

**Comment by jsteemann** [comment]
I think we first need to do something in the traversal code to made this work. I think I can give it a try tonight.

**Comment by clintwood** [comment]
Great... I haven't time to look at it yet...

**Comment by jsteemann** [comment]
It should now be possible to use a custom AQL function as a visitor.
I have also added a new traversal order `preorder-expander` that passes the connecting edges into the visitor function. This should allow returning only leaf nodes, though there isn't yet a built-in, ready-to-go function to do it. I might extend this in the course of the next days and write some examples.

**Comment by clintwood** [comment]
Awesome... is there a win x64 nightly build?

**Comment by jsteemann** [comment]
Not yet. 
But currently it looks like the changes will not be intrusive so I can hopefully backport them into 2.4.

**Comment by clintwood** [comment]
Even better!  Thanks @jsteemann!

**Comment by clintwood** [comment]
@jsteemann, [Thanks for great post on this custom visitor extension!!!](http://jsteemann.github.io/blog/2015/01/28/using-custom-visitors-in-aql-graph-traversals/)

**Comment by jsteemann** [comment]
Thanks. It is now merged into 2.4, too, so it can be included in 2.4.2.
