### ISSUE TITLE
Install arangodb cluster is too difficult

### ISSUE THREAD

**Issue by max-yue** [arangodb/arangodb#12183]
Let's say I have the following three machines:
10.170.74.23 master
10.170.74.18 slave
10.170.74.12 slave

How can I deploy arangodb with docker ?

I have tried this, and failed. 
https://github.com/arangodb/arangodb/issues/12095#issuecomment-654769697

**Comment by dothebart** [comment]
please lets continue on that issue, since you put all your information in there already. 
Usually we should have one issue that actually is an issue and not hop topics.
