### ISSUE TITLE
GRAPH_TRAVERSAL_TREE: Why nested results?

### ISSUE THREAD

**Issue by clintwood** [arangodb/arangodb#1218]
When using the above graph operation why do the results come back nested in 3 levels of an array?
i.e.:
```
[
  [
    [
      { /* result object */}
    ]
  ]
]
```
I'm finding I do `return GRAPH_TRAVERSAL_TREE(...)[0][0]` sometimes...

**Comment by fceller** [comment]
@mchacki is this a feature or a bug?

**Comment by dothebart** [comment]
the GRAPH_TRAVERSAL functions are removed with ArangoDB 3.0

Find out about how to migrate them to the new traverser: https://docs.arangodb.com/devel/AQL/Graphs/Traversals.html

ArangoDB RC2 is available for download via: https://www.arangodb.com/download-preview/

**Comment by Haadka** [comment]
Hi, I am finding it hardly impossible to get the nested results in GRAPH_TRAVERSAL_TREE. Yes for me it was a feature.

My end goal is to have something similar to the Graph UI in arangoDb dashboard. There you start with a vertex, then you have a nested result where the children of the root JSON payload are the immediate vertexes. Each of them in return will have a child property with again another set of vertices.

I can not see how that can be achieved with the API in 3.x


can you help please
