### ISSUE TITLE
Poor performance of arrangodb on simple AQL query

### ISSUE THREAD

**Issue by volodymyr-koval-vitech** [arangodb/arangodb#12191]
## My Environment

* __ArangoDB Version__: 3.4.9 Community Edition
* __Storage Engine__: RocksDB
* __Deployment Mode__:   Single Server 
* __Deployment Strategy__:  Manual start
* __Configuration__: vCPU 2
* __Infrastructure__: AWS - t2.medium
* __Operating System__: Centos 7
* __Total RAM in your machine__: 4Gb 
* __Disks in use__:  DataVolume 100Gb with IOPS=5000   
* __Used Package__: rpm

## Component, Query & Data

__Affected feature__:
AQL query using web interface

__AQL query (if applicable)__:
`FOR d IN Document FILTER d.dataSetId == '4336520' RETURN d._key`

__AQL explain (if applicable)__:
```
Query String (63 chars, cacheable: false):
 FOR d IN Document FILTER d.dataSetId == '4336520' RETURN d._key

Execution plan:
 Id   NodeType          Calls   Items   Runtime [s]   Comment
  1   SingletonNode         1       1       0.00000   * ROOT
  7   IndexNode            21   20126     250.27828     - FOR d IN Document   /* persistent index scan, projections: `_key` */
  5   CalculationNode      21   20126       0.00642       - LET #3 = d.`_key`   /* attribute expression */   /* collections used: d : Document */
  6   ReturnNode           21   20126       0.00007       - RETURN #3

Indexes used:
 By   Type         Collection   Unique   Sparse   Selectivity   Fields            Ranges
  7   persistent   Document     false    false         0.01 %   [ `dataSetId` ]   (d.`dataSetId` == "4336520")

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   move-calculations-up-2
  4   move-filters-up-2
  5   use-indexes
  6   remove-filter-covered-by-index
  7   remove-unnecessary-calculations-2
  8   reduce-extraction-to-projection

Query Statistics:
 Writes Exec   Writes Ign   Scan Full   Scan Index   Filtered   Exec Time [s]
           0            0           0        20126          0       250.28706

Query Profile:
 Query Stage           Duration [s]
 initializing               0.00000
 parsing                    0.00005
 optimizing ast             0.00001
 loading collections        0.00001
 instantiating plan         0.00002
 optimizing plan            0.00014
 executing                250.28671
 finalizing                 0.00012
```

__Dataset__:
```
{
  "name": "SOME NAME",
  "dataSetId": "4336520",
  "createdAt": "2020-07-07T12:52:01Z",
  "metaData": {
    "setid": "2bdc3116-75c6-4ff2-b7f5-c38f52691878",
    "splVersion": "1",
    "publishedDate": "Jul 06, 2020",
    "title": "some title",
    "genericMedicine": "SENNOSIDES",
    "effectiveTime": "2020-07-02T00:00:00Z",
    "documentCode": {
      "name": "HUMAN OTC DRUG LABEL",
      "code": "34390-5",
      "codeSystem": "2.16.840.1.113883.6.1"
    },
    "manufacturedProduct": {
      "name": "VALUMEDS  NATURAL LAXATIVE",
      "suffix": "",
      "fullName": "VALUMEDS  NATURAL LAXATIVE",
      "code": "68210-4101",
      "codeSystem": "2.16.840.1.113883.6.69"
    },
    "ingredientSubstance": [
      {
        "name": "SENNOSIDES",
        "code": "3FYP5M0IJX",
        "codeSystem": "2.16.840.1.113883.4.9",
        "classCode": "ACTIB"
      }
    ]
  },
  "html": "<!DOCTYPE html PUBLIC \"-\">\n<html> \n </html>"
}
```

__Size of your Dataset on disk__:
~60Gb

__Problem__:
AQL took 250s to scan 20k documents. Index for dataSetId field is defined. What can be wrong in configuration or in my query

__Expected result__:
AQL took up to 5s to execute.

**Comment by dothebart** [comment]
The index has a _verry_ bad selectivity:
```
Indexes used:
 By   Type         Collection   Unique   Sparse   Selectivity   Fields            Ranges
  7   persistent   Document     false    false         0.01 %   [ `dataSetId` ]   (d.`dataSetId` == "4336520")
```
this means grabbing items from it will probably give you many items, your `dataSetId` is probably not very unique, hence the index doesn't give you a good performance.

**Comment by dothebart** [comment]
also please note that you're using an EOLed version: https://www.arangodb.com/eol-notice/

**Comment by manwithsteelnerves** [comment]
> probably not very unique

Can you please share how to have better selectivity value?

**Comment by dothebart** [comment]
you probably have many documents where `dataSetId`are similar. Hence its not a good criteria to distinguish documents - hence bad selectivity.

**Comment by manwithsteelnerves** [comment]
So do you mean overlapped dataSetId values leads to large number of matching documents in-turn leading to poor performance? Does applying a limit for the results to be returned won't help?

Also, its very common to index on a similar values attribute (for ex: sortKey). Anything i'm missing?
For ex: Players scores table can have gameMode which is repetitive and won't be unique. If performance won't be good for those, I see it a big concern. Can you please clarify?

**Comment by volodymyr-koval-vitech** [comment]
After deep and detailed investigation it was identified that size of document in collection affect performance drastically. Our documents has stored pictures coded in BASE64 format. 

Moving out fields which are used for searching to separate collection without pictures increased performance to acceptable level.

Closing issue.

**Comment by dothebart** [comment]
Ok, probably the big documents poison your block cache: 
https://www.arangodb.com/docs/stable/tutorials-reduce-memory-footprint.html
Can you give estimates on document sizes avg/min/max before / after?
