### ISSUE TITLE
Same queries in the long run some of these take a huge time

### ISSUE THREAD

**Issue by effesessa** [arangodb/arangodb#12190]
## My Environment

* __ArangoDB Version__:        3.6.2
* __Storage Engine__:             RocksDB
* __Deployment Mode__:      Cluster
* __Deployment Strategy__:   Kubernetes
* __Configuration__: 

    dbservers: 3
    coordinators: 3
    agents: 3
    shards: 3
    replicationFactor:3

    __or__

    dbservers: 6
    coordinators: 6
    agents: 3
    shards: 6
    replicationFactor: 3
* __Infrastructure__:               Azure
* __Total RAM in your machine__:        16GB for each k8s node (nodepool 3 node)
* __Disks in use__:        SSD Azure Disks 8GB for each dbserver
* __Used Package__:     Docker - official Docker library

## Component, Query & Data

__AQL query (if applicable)__:
`UPSERT { textBlockKey: "bar5RT43g443c54v53Bry743r89fZ..." } INSERT {...} UPDATE {...} in textBlock RETURN NEW._id`
__or__
`UPSERT {uri: "wasb://..........fileName.extension} INSERT {...} UPDATE {...} in document RETURN NEW._id`

in insert and update 10-15 metadata are inserted / updated as numbers or small strings 

__Replication Factor & Number of Shards (Cluster only)__:
All collections have replicationFactor=3 and numberOfShards like dbservers as mentioned before in the configuration.

__Problem__:
In parallel 8 clients write on arangodb. The problem is that it is a very long process (It can take dozen of hours, but this regardless of arangodb because we perform processes on the content of the physical document). We have document (document collection) -> documentHasTextBlock (edge collection) -> textBlock (document collection). If we process 1000 documents of variable size we will have 1000 upsert document + (upsert documentHasTextBlock + upsert textBlock so n * n) where n can be the number of textBlocks extracted from the document. N of the times for a single document can be 10000-20000 (textBlocks). So as you can imagine it is a long process. The problem is that in the long run the same identical queries that take 0.1 - 0.2s start to use "some of these" 90-250s (And sometimes it fails Response: 500, Error: 1457 - AQL: timeout in cluster operation (while optimizing plan)) while others take the same as before 0.1-0.2 s What could be the problem?

also it happens that some node fails for a few seconds. How can I see the reason the node falls out?

Second question, do you benefit by increasing coordinators? 
How many clients can a coordinator manage in parallel?

Thanks for your support!

**Comment by dothebart** [comment]
Hi, 
Please upgrade to 3.6.5, and report back whether the problems persist.

**Comment by Simran-B** [comment]
@effesessa Can you please try the latest 3.6 release and see if this is still a problem?

**Comment by effesessa** [comment]
I set memory in ArangoDeployment to 18GB for each dbserver. 
I set some parameters about rocksdb buffer.
Fixed.

**Comment by Simran-B** [comment]
@effesessa Am I correct to assume that you followed graetzer's suggestions given in https://github.com/arangodb/arangodb/issues/12311#issuecomment-673408056?
