### ISSUE TITLE
Question: Where to find the docs on document filtering using web interface

### ISSUE THREAD

**Issue by AceTheWiz** [arangodb/arangodb#12212]
__Problem__:
I can't find any documentation on the document filtering feature of the Web Interface (Aardvark)

**Comment by Simran-B** [comment]
Hi @AceTheWiz,
we don't have much documentation on the Web UI. It should be mostly self-explanatory, but looks like the document filtering isn't. What exactly do you want to achieve or struggle with?

A common problem is that if you want to filter by `_key` and the value is comprised of digits only, then you need to wrap the number in double-quote marks like `"123"` to indicate that it is supposed to be a string - which the document key always is. Comparing it to a number will not match any document.

**Comment by dothebart** [comment]
https://github.com/arangodb/arangodb/issues/2388 - discussed here.

**Comment by AceTheWiz** [comment]
Sorry, I should have given more info.

I think I was trying to filter on a text field by providing a specific word.
In other words, I wanted to filter all records which had the word "product" in the ```Name``` field.
I tried all the usual "SQL" like filtering methods. e.g. ```Name LIKE|IN "%product%"```

**Comment by Simran-B** [comment]
Assuming that `Name` is a top level attribute and has a string value, setting the comparison mode to `LIKE` and using `product` as search phrase should match documents like `{"Name": "Great product!"}`.

The Web UI wraps the search phrase you enter with `%` automatically, so no need to explicitly write `%product%`.

Note that the query that is issued internally uses the `LIKE` operator.
It is case-sensitive, so `product` won't match `{"Name": "Product"}`, but only `"Product"` will!

**Comment by Simran-B** [comment]
@AceTheWiz Does my last comment answer your questions or do you still have issues filtering in the Web UI?
