### ISSUE TITLE
Missing icon in admin interface

### ISSUE THREAD

**Issue by tbo** [arangodb/arangodb#1221]
The "select2x2.png" icon cannot be found. The following error message is displayed instead:
```
cannot find file '/Applications/ArangoDB.app/Contents/Resources/opt/arangodb/share/arangodb/js/apps/system/aardvark/frontend/img/select2x2.png'
```
It is used in the application generation dialog.

**Comment by hkernbach** [comment]
I can confirm the error. An image was missing if a higher resolution display was used. Now fixed in devel.  Will also be fixed in the next App Store release.
