### ISSUE TITLE
question about document() in transactions / [object ShapedJson] / [object Object]

### ISSUE THREAD

**Issue by baslr** [arangodb/arangodb#1223]
Hi,

when it is possible to modify objects that were returned with `db.myCollection.document()`?

I have one case where objects are not mutable but in other collections I can modify objects.

The one that is not mutable is a `[object ShapedJson]`

**Comment by jsteemann** [comment]
I guess you are referring to the server-side version of `db.myCollection.document()` and not the arangosh version.

When this method (or other server-side methods) returns an `[object ShapedJson]` this means produces a very light-weight JavaScript object that contains an internal pointer to where the document data are actually stored in memory or on disk. Especially this is not a full-blown copy of the document's complete data. 

When such an object's property is accessed, this will invoke an accessor function. For example, accessing `doc.name` of such object will call a C++ function behind the scenes to fetch the actual value for the property `name`. When a property is written to this will also trigger an accessor function. This accessor function will first copy all property values into the object's own properties, and then discard the pointer to the data in memory. From this point on, the accessor functions will not do anything special, so the object will behave like a normal object.

All of this is done for performance reasons. It often allows saving the creation of big JavaScript objects that contains lots of data. For example, if all that's needed from a document is a single property, fully constructing the document as a JavaScript object have a high overhead (CPU time for processing plus later V8 garbage collection).

Here's an example:
```js
var ShapedJson = require("org/arangodb").ShapedJson;
// fetches document from collection into a JavaScript object
var doc = db.test.any(); 

// check if the document object is a shaped object
// returns true for shaped objects, false otherwise
doc instanceof ShapedJson; 

// invokes the property read accessor. returns property value by-value
doc.name; 

// invokes the property write accessor. will copy document data into the JavaScript object once
// and store the value in the property as requested
doc.name = "test"; 

// doc will now behave like a regular object 
doc.foo = "bar"; 
```

There is one gotcha though with such objects: the accessor functions are only invoked when accessing top-level properties. When accessing nested properties, the accessor will only be called for the top-level property, which will then return the requested property's value. Accessing a sub-property of this returned property however does not have a reference to the original object.

Here's an example:
```js
// create an object with a nested property
db.test.save({ name: { first: "Jan" } });
doc;
{ 
  "_id" : "test/2056013422404", 
  "_rev" : "2056013422404", 
  "_key" : "2056013422404", 
  "name" : { 
    "first" : "Jan" 
  } 
}

// now modify the nested property
doc.name.first = "test";
doc;
{ 
  "_id" : "test/2056013422404", 
  "_rev" : "2056013422404", 
  "_key" : "2056013422404", 
  "name" : { 
    "first" : "Jan"  /* oops */
  } 
}
```
So what happened here? The statement `doc.name.first = "test"` calls the read-accessor for property `name` first. This produces an object `{"name":"Jan"}` whose property `first` is modifed directly afterwards. But the object `{"name":"Jan"}` is a temporary object and not the same (===) object as `doc.name`. This is why updating the nested property effectively failed.

There is no way to detect this in a read-accessor unfortunately. It does not have any idea about what will be done with the returned object. So this case cannot be tracked/trapped in the accessor.

A workaround for this problem would be to clone the object in the user code if the document is going to be modified. This will make all modification safe. The cloning can also be made conditional for cases when the object is an instance of `ShapedJson` or when nested properties are to be accessed. Cloning is not required when the object is no `ShapedJson` or when only top-level properties are accessed.

By the way, and I hope this answers your initial question, only those documents that are stored in a collection's datafile will be returned as `ShapedJson`. The documents that are still in the write-ahead-log will always be returned as regular JavaScript objects, as they are not yet shaped and the optimization would not work. However, when a document is transfered from the write-ahead-log to the collection's datafile cannot be safely predicted by an application, so the same document can be returned in one way or the other. The only safe way is to check if the object is an instance of `ShapedJson` as above.

So far, we have come up with the following suggestions to fix the problem, but none of them can be considered good:
* when read-accessing a property, copy the document's data into the JavaScript object (the same way as a write-accessor currently does). However, as in almost all cases at least one property is read, this would disable the ShapedJson optimization completely, and would require all documents to be fully constructed when being handed out to JavaScript. Obviously, this is not ideal.
* let the end user decide if he/she wants a potentially shaped object or a regular JavaScript object in return. This would be explicit and give the user full control, but the changes would be massive as there are so many methods that can return documents. I think this cannot be done in the near future.

Any further suggestions are welcome!

**Comment by baslr** [comment]
Hi Jan,

first thanks for this really good explanation. It helped me a lot to understand the behavior.
Yes I referred to the transaction that can be invoked via the http API.

For me this isn't a real problem that has to be fixed. You just have to know this "pitfall".

My suggestion would be to have a "Good to know" or something like this in the for new users section in the documentation to mention these "specialties". (if there are any more,  in my case there is the uft8 normalization thing ;) )

**Comment by jsteemann** [comment]
Totally agree!

**Comment by jsteemann** [comment]
@13abylon : can you take over and put this into the docs in the appropriate place?
