### ISSUE TITLE
Web UI on 3.6.5: 404 error on adding new index

### ISSUE THREAD

**Issue by sonyarianto** [arangodb/arangodb#12248]
## My Environment

* __ArangoDB Version__:        3.6.5 (just upgrade from 3.6.4)
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   CentOS 7 standard deployment
* __Infrastructure__:               own
* __Operating System__:        CentOS 7
* __Total RAM in your machine__:        24GB
* __Disks in use__:        HDD
* __Used Package__:              SUSE or RedHat .rpm

## Steps to reproduce

1. I have a collection, let's say my_collection
2. I have 10 data/document on it
3. No index yet
4. I start to add index on it, let say slug for slug attribute (persistent index)
5. Index successfuly created (green indicator on the bottom screen)
6. But after that appear the red indicator on the bottom screen says 404: Not Found

__Problem__:
Read above. Maybe visual bug?

__Expected result__:
Should be no 404 error.

![Screenshot from 2020-07-19 18-30-51](https://user-images.githubusercontent.com/333051/87873756-2fd35580-c9ee-11ea-8020-48e3b7104158.png)

**Comment by jsteemann** [comment]
Thanks for reporting this bug. The issue should be fixed via the above PRs, and the bugfix should become part of 3.6.6.

**Comment by sonyarianto** [comment]
Thank you @jsteemann
