### ISSUE TITLE
Passwords exist in the source code.

### ISSUE THREAD

**Issue by Neverstop** [arangodb/arangodb#12289]
## My Environment

* __ArangoDB Version__:       3.6.3.1
__Problem__:
The following file contains hardcoded passwords. What are the application scenarios of these hardcoded passwords? Are there any security problems? 
share\arangodb3\js\client\modules\@arangodb\testsuites\dump.js  {"Line":467}
share\arangodb3\js\client\modules\@arangodb\testsuites\dump.js | {"Line":472}
share\arangodb3\js\client\modules\@arangodb\user-helper.js | {"Line":147}
share\arangodb3\js\client\modules\@arangodb\user-helper.js | {"Line":180}
share\arangodb3\js\client\modules\@arangodb\testsuites\dump.js | {"Line":467}
share\arangodb3\js\client\modules\@arangodb\testsuites\dump.js | {"Line":472}
share\arangodb3\js\client\modules\@arangodb\user-helper.js | {"Line":147}
share\arangodb3\js\client\modules\@arangodb\user-helper.js | {"Line":180}

__Expected result__:

**Comment by dothebart** [comment]
Hi, 
these files in question are part of the integration testing suites. So they will start a server with that password, and then work with it.

They aren't required for the regular installation, however the CI also uses an at least partly regular installation, hence its probably challenging to remove them from distribution packages.

**Comment by Neverstop** [comment]
> Hi,
> these files in question are part of the integration testing suites. So they will start a server with that password, and then work with it.
> 
> They aren't required for the regular installation, however the CI also uses an at least partly regular installation, hence its probably challenging to remove them from distribution packages.

thx ！
