### ISSUE TITLE
Arango collection truncate leads to the View links to be lost (on shutdown/reboot)

### ISSUE THREAD

**Issue by aveiros** [arangodb/arangodb#12280]
## My Environment

* __ArangoDB Version__:        3.5.3
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Infrastructure__:               own
* __Operating System__:        CentOS
* __Total RAM in your machine__:        64GB
* __Used Package__:              .rpm

## Component, Query & Data

__Affected feature__:
Arango Search Views

__AQL query (if applicable)__:
n/a

__Dataset__:
I had some data. But might occur on empty collections as well.

## Steps to reproduce

1. Create Collection
2. Create View (make sure links section links to collection from 1)
3. Insert some documents on the Collection
4. Truncate Collection
5. Shutdown and Restart Arango

__Problem__:
Links section not present.

__Expected result__:
Links section to be present.

**Comment by Simran-B** [comment]
The ArangoSearch team took notice of the problem and will look into it.

**Comment by maxkernbach** [comment]
Closing as fixed with 3.5.6 and 3.7.2.



From the Changelog:

>     Fixed internal issue #742: Add tick storage in index meta payload for
>     ArangoSearch view links after collection truncate operation.
