### ISSUE TITLE
lost collections and documents after update

### ISSUE THREAD

**Issue by antokara** [arangodb/arangodb#1229]
System is CentOS release 6.6 (Final) 64 bit

Not sure how helpful this issue can be,
but perhaps it might "click" something...

I did a yum update from arango 2.4.0 -> 2.4.1
the service was running when I issued the update -as always, 
then as usual, after the update was complete, I started the service.

To my surprise around 5 collections were gone and some documents from other collections as well.
All these collections were sync on disk true by default on all operations.

While the update was happening, no operations were pending on the database.
Also, no disk corruption has occurred.

It is the first time I encounter an issue with ArangoDB during/post update.
One more reason why we should dump all databases before an update...

**Comment by antokara** [comment]
Here is the /var/log/arangodb/arangod.log the day of the update
http://pastebin.com/c7TGCDms

and the /var/log/arangodb/arangod.log.daemon had only these two lines on day of update...
```
2015-01-28T09:29:55Z [28882] INFO child 28883 died of natural causes, exit status 9
2015-01-28T09:33:24Z [9215] INFO changed working directory for child process to '/var/tmp'
```

**Comment by dothebart** [comment]
hm, to be able to proceed here we would need a complete copy of database directory, plus the name of the collections that missing.

**Comment by antokara** [comment]
Unfortunately I did not keep track of the missing collections, I just restored everything to get back to an operational state. If the problem occurs in the future I will try to copy the "corrupted" database directory and provide more information.

I guess this issue should be closed since it can't be more helpful.
Thanks!

**Comment by dothebart** [comment]
ok, Reopen if you find the situation again. 
the stage before & after the upgrade would be usefull.
