### ISSUE TITLE
bug xor feature in AQL: LENGTH(null) == 4

### ISSUE THREAD

**Issue by ThorstenFuehring** [arangodb/arangodb#1231]
I came accross a behaviour which I find a bit strange: The query 

    FOR x in [null] RETURN { "x" : x, "length": LENGTH(x) } 

returns: `[  { "x": null, "length": 4 }]`.

The description says: "LENGTH(array): Returns the length (number of array elements) of array. If array is an object / document, returns the number of attribute keys of the document, regardless of their values." 

`null` is not an array for sure, neither would I expect it to be a document with any attribute keys Therefore, I would expect the result to be `[  { "x": null, "length": 0 } ]`.

Maybe there is some hidden type casting/conversion from the value `null` to the string `"null"` before the length is computed?

I'm running 2.4.0 beta and 2.4.1 on Windows 7 (64bit) and Windows Server 2008 R2

**Comment by fceller** [comment]
It is a feature - but the documentation is incomplete. It should read:

If array is neither an array nor an object, than it is converted into a string and the string length is returned.

**Comment by CoDEmanX** [comment]
Can't this lead to hard to track down follow-up errors? I would actually expect it to return 0 if it's `null` or `undefined` - which are very possible results of sub-queries etc. (typos, missing attributes, failed functions, ...). Implicit casting can do a lot of harm.

**Comment by ThorstenFuehring** [comment]
It was this kind of hard to track error CoDEmanX mentioned which lead me to the reported finding.

I agree that the conversion to string for items other than objects and arrays makes sense: but *if and only if* there is some kind of value which can be reasonably converted. Another exception is I/O where you need something to denote a `null` value.

I do not agree with the concept of converting a `null` value to the string value `"null"` because a `null` value denotes the *absence* of any meaningfull value. This is especially true in the schema-free ArangoDB where you get a `null` value whenever you query an attribute which is not set.

**Comment by fceller** [comment]
The manual describes the behaviour for array / object / string, but not for null (or boolean or number). So I agree, that null should better be interpreted as "empty" and therefore LENGTH(null) = 0. I would also define LENGTH(true), LENGTH(false) and LENGTH(number) as 0. For number there is no easy way to determine the number of characters because of rounding issues and "e" notation.

**Comment by jsteemann** [comment]
Any non-array/non-object value passed into `LENGTH()` will be converted into its string presentation, and then the string length will be determined and returned. The to-string value of `null` in AQL is `"null"`, so the return value is 4.

This is in line with some other languages, e.g. JavaScript and PHP. 
I know `null` has a different meaning in other languages and also in SQL, but in SQL `LENGTH(null)` would likely produce `null`, too and not `0`.

So I think there is not a single "right" answer for the question *what is the length of null?*.

**Comment by razvanphp** [comment]
+1

really strange, at least in the example from my bug, when you want to check a subfield of a document for existence. In PHP, we have `empty` function, that checks all cases, if it's 0, null, empty array, empty string etc.

**Comment by fceller** [comment]
Yes, that behaviour is currently: LENGTH(list) returns the length of the list, LENGTH(obj) returns the number of attributes, LENGTH(x) returns the length of string representation of x - which is not what one expects for null.

We propose the following change:

LENGTH(x) return

the number of characters if x is a string
the length of the list if x is a list
the number of attributes if x is a object
0 if x is null
0 if x is false
1 if x is true
the number of characters of the string representation if x is a number

However, as this is a break change we want to change it in 2.6.

**Comment by razvanphp** [comment]
Seems logical to me :+1:

**Comment by jsteemann** [comment]
"fixed" (i.e. changed) in devel/2.6 as proposed by @fceller .
Cannot backport this into 2.5 because it is not downwards-compatible and a change in behavior.

**Comment by jsteemann** [comment]
In devel/2.6, `LENGTH(null)` is now `0`.
