### ISSUE TITLE
Issue with starting arango process after the pod restart.

### ISSUE THREAD

**Issue by yogeshbidari** [arangodb/arangodb#12318]
## My Environment

* __ArangoDB Version__:           3.3.8
* __Storage Engine__:             RocksDB
* __Deployment Mode__:            Single Server
* __Deployment Strategy__:        Kubernetes 
* __Infrastructure__:             GKE
* __Operating System__:           debian
* __Total RAM in your machine__:  120GB 
* __Disks in use__:               SSD

## Component, Query & Data

__Size of your Dataset on disk__:
4-5GB

__Problem__:
After Arango pod got restarted because of OOM kill/any reason, the new pod comes up. 
The arango process in new pod doesn't startup even the pod shows healthy. Attempts to start the process, but goes to infinite loop.
Not able to access even web interface. 

Lot of logs for the below query:
```WARNING {queries} slow query: '\n    FOR item IN @value0\n    UPSERT {mount: item[0]}\n    INSERT item[1]\n    REPLACE item[1]\n    IN @@value1\n  ', bind vars: {"@value1":"_apps","value0":[["/_admin/aardvark",{"id":"/_admin/aardvark","mount":"/_admin/aardvark","options":{"configuration":{},"dependencies":{},"development":false}}],["/_api/foxx",{"id":"/_api/foxx","mount":"/_api/foxx","options":{"configuration":{},"dependencies":{},"development":false}}],["/_api/gharial",{"id":"/_api/gharial","mount":"/_api/gharial","options":{"configuration":{},"dependencies":{},"development":false}}]]}, took: 18.644045 s```

__Expected result__:
Whenever pod restarts/OOM kill the pod, new pod should come up and arango process/UI has to be accessible.

**Comment by dothebart** [comment]
Hi, 
Please note that ArangoDB 3.3 has run out of support. 
Please upgrade to at least ArangoDB 3.5 and report back whether the issue persists. 
see https://www.arangodb.com/eol-notice/ for details.

**Comment by yogeshbidari** [comment]
Hi @dothebart ,
Currently we are using arango 3.3.8 in our environment, in order to upgrade to 3.5 it may take sometime  from our end as it may involves some testing and procedures to be followed before upgrade. 
Please let us know is there any way we can fix this issue, as it is affecting current environment.

**Comment by dothebart** [comment]
Hi, 
the only hint I can give you is to update to at least 3.3.25, since many bugs have been fixed in that release series. 
Closing this as "wont' fix".
