### ISSUE TITLE
Index issue on edges collection

### ISSUE THREAD

**Issue by razbenya** [arangodb/arangodb#12333]
## My Environment

* __ArangoDB Version__:        3.5.2 
* __Storage Engine__:             RocksDB 
* __Deployment Mode__:     Cluster  
* __Deployment Strategy__:  Kubernetes ArangoDeployment 
* __Configuration__:     3 agents ,3 dbservers ,3 coordinators          
* __Infrastructure__:       AWS        

## Component, Query & Data

__Affected feature__: AQL query using web interface or java driver

__Problem__: fetching from edges collection using _from index is sometimes producing results with missing data

my aql with index:
![arangodb_with_index](https://user-images.githubusercontent.com/22798855/88901841-03270580-d25a-11ea-9a52-5f0dee08cc74.JPG)

my aql without index
![arangodb_without_index](https://user-images.githubusercontent.com/22798855/88901863-0c17d700-d25a-11ea-828a-29fc93d4885f.JPG)

**Comment by jsteemann** [comment]
This looks similar to issue #11303, which was fixed in release 3.5.5.1:
From the 3.5.5.1 CHANGELOG entry:
``` 
v3.5.5.1 (2020-05-08)
---------------------

* Fixed issue #11303: The result data of filter operation on edge document with
  _from or _to field ALWAYS miss some data on version 3.6.2.

  This bug could have led to some edges from a RocksDB edge index not being 
  returned when a non-traversal edge lookup was done in an AQL query in an inner 
  FOR loop. Whether or not edges were withheld depended on whether edges were
  located within the same prefix domain.
```
If you are running version 3.5.2 then an update should fix this.

**Comment by jsteemann** [comment]
Other than that, `==` and `like` in theory _can_ return different results, because they are not equivalent operations.
This will at least be the case if the `like` pattern contains any wildcard characters, such as `%` or `_`.

**Comment by razbenya** [comment]
As you can see I am using the like without any wildcard characters so its equivalent to ==

I will try to update.

**Comment by Simran-B** [comment]
@razbenya Did you have a chance to upgrade and test if a more recent server version has the problem fixed?

**Comment by razbenya** [comment]
Not yet, I will update sometimes this week.

**Comment by Simran-B** [comment]
@razbenya Did you have a chance to upgrade to a more recent version?

**Comment by razbenya** [comment]
Updated to 3.6.5, the bug is not preproduced for now

**Comment by dothebart** [comment]
Ok, closing as solved then.
