### ISSUE TITLE
601 - superfluous URL suffices?

### ISSUE THREAD

**Issue by CoDEmanX** [arangodb/arangodb#1234]
I just stumbled upon this error code in the docs, but have no idea what it means.

It doesn't seem to be raised anywhere in the code, but still, how would such an URL look like?

**Comment by jsteemann** [comment]
It is actually used as an error code, e.g. when executing this command:

```
curl -X GET http://127.0.0.1:8529/_api/document/foo/bar/baz --dump -
HTTP/1.1 400 Bad Request
Server: ArangoDB
Connection: Keep-Alive
Content-Type: application/json; charset=utf-8
Content-Length: 160

{"error":true,"errorMessage":"expecting GET \/_api\/document\/<document-handle> or GET \/_api\/document?collection=<collection-name>","code":400,"errorNum":601}
```
There are other places that use this error code, too:
* arangod/RestHandler/RestDocumentHandler.cpp: retrieving/saving documents
* arangod/RestHandler/RestEdgeHandler.cpp: retrieving/saving edges
* arangod/RestHandler/RestImportHandler.cpp: importing data
* arangod/RestHandler/RestReplicationHandler.cpp: replication control

**Comment by CoDEmanX** [comment]
So it can be interpreted as "extra arguments in request". The word "suffices" confused me, I believe it should be "suffixes" ("satisfies" vs. "additions at the end")

**Comment by pluma** [comment]
You are right, it should be "suffixes". The use of "suffices" throughout the docs is probably a case of hypercorrection (via "index" -> "indices").
