### ISSUE TITLE
Reverse DATE_FORMAT() feature?

### ISSUE THREAD

**Issue by Phillips126** [arangodb/arangodb#12343]
I'm working with a dataset that I've inherited and it stores dates in a:   `"%dd-%mmm-%yy"` (31-Jul-20) format.  Does ArangoDB have a built-in method of converting non ISO-8601 strings into a timestamp for date comparisons?

I can format a date into this string using `DATE_FORMAT(item.date, "%dd-%mmm-%yy")`. 
Is there a way in AQL to convert this string into a timestamp?

I'm looking to filter all entries between two dates (timestamps) and cant find a way to convert this stored value.

Thanks!

**Comment by Phillips126** [comment]
On second thought, I'm going to retroactively convert all stored dates to use ISO 8601.  Standards are set and used for a reason.  I'll format the date on the client side to appease executives.  

Perhaps an "UNFORMAT" feature would be cool to have someday but I'm going to fix this now before it becomes a bigger problem down the road.

**Comment by jsteemann** [comment]
There is no built-in way to convert arbitrary date formats into the expected date format, but it should work with a bit of string massaging in AQL as follows:

```
/* input value */
LET input = '31-Jul-20' 

/* parse day, month and year values */
LET day = TO_NUMBER(SUBSTRING(input, 0, 2)) 
LET month = TRANSLATE(LOWER(SUBSTRING(input, 3, 3)), { jan: 1, feb: 2, mar: 3, apr: 4, may: 5, jun: 6, jul: 7, aug: 8, sep: 9, oct: 10, nov: 11, dec: 12 }) 
LET year = TO_NUMBER(SUBSTRING(input, 7, 2)) 
LET fullyear = year <= 20 ? year + 2000 : year + 1900 

/* return an ISO8601 date-time string */
RETURN DATE_ISO8601(fullyear, month, day)
```

Obviously this makes a few assumptions about the input values, namely that day and year values are always 2 digits long, and that year values above 20 are for years 19xx and not 20xx. If these assumptions hold, then it hopefully works.
