### ISSUE TITLE
arangosh compact Arangoerror 404

### ISSUE THREAD

**Issue by scientes** [arangodb/arangodb#12349]
## My Environment

* __ArangoDB Version__:        3.6.5
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single server
* __Deployment Strategy__:   Manual Start in Docker
* __Configuration__:               docker compose with arangodb:latest
* __Infrastructure__:               own
* __Operating System__:        Ubuntu 18.04 (server), Win 10(client)
* __Total RAM in your machine__:        8gb
* __Disks in use__:        NVME SSD
* __Used Package__:    arangodb:latest         

## Component, Query & Data

__Affected feature__:
arangosh

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:
1:
db.artikel2.figures():
```
{
  "indexes" : {
    "count" : 9,
    "size" : 17822560
  },
  "documentsSize" : 37499800,
  "cacheInUse" : false,
  "cacheSize" : 0,
  "cacheUsage" : 0
}
```
2:
db.dataset2.figures():
```
{
  "indexes" : {
    "count" : 4,
    "size" : 0
  },
  "documentsSize" : 0,
  "cacheInUse" : false,
  "cacheSize" : 0,
  "cacheUsage" : 0
}
```

__Size of your Dataset on disk__:
1:1M entries deleted 6k entries left (2gb)
2: 1M entries deleted, no entries left, approx size deleted 70gb (i didnt expect everything to get deleted, due to this being done by a script of mine.) If I had known, I'd truncated.

## Steps to reproduce

1. 
2. 
3. 

__Problem__:
Due to requests being slow after deletion a manual compaction was tried to run via:
db.<collection>.compact(); via arangosh version3.6.4 
```
db.artikel2.compact();
JavaScript exception in file 'c:\Users\<redacted>\AppData\Local\ArangoDB3-client 3.6.4\share\arangodb3\js\client\modules\@arangodb\arangosh.js' at 99,7: ArangoError 404: expecting one of the actions 'load', 'unload', 'truncate', 'properties', 'compact', 'rename', 'loadIndexesIntoMemory'
!      throw error;
!      ^
stacktrace: ArangoError: expecting one of the actions 'load', 'unload', 'truncate', 'properties', 'compact', 'rename', 'loadIndexesIntoMemory'
    at Object.exports.checkRequestResult (c:\Users\<redacted>\AppData\Local\ArangoDB3-client 3.6.4\share\arangodb3\js\client\modules\@arangodb\arangosh.js:97:21)
    at ArangoCollection.compact (c:\Users\<redacted>\AppData\Local\ArangoDB3-client 3.6.4\share\arangodb3\js\client\modules\@arangodb\arango-collection.js:580:12)
    at <shell command>:1:14
```
same error on all other collections.

**Comment by jsteemann** [comment]
Fixed via the above PRs.
Bugfix expected to land in 3.6.6.

**Comment by jsteemann** [comment]
Looks like the compact operation actually is executed server-side, but always answered with the error message you are receiving.

**Comment by scientes** [comment]
thanks!
