### ISSUE TITLE
Arangorestore fails with renamed collections.

### ISSUE THREAD

**Issue by ggendel** [arangodb/arangodb#12359]
## My Environment

* __ArangoDB Version__: 3.5.5.1        
* __Storage Engine__:  RocksDB           
* __Deployment Mode__:  Single Server     
* __Deployment Strategy__:   Manual Start 
* __Configuration__:   Stock            
* __Infrastructure__:   Own            
* __Operating System__:  Centos 7      
* __Total RAM in your machine__:  32 Gb       
* __Disks in use__:  SSD      
* __Used Package__:   yum from ArangoDB repository           

## Component, Query & Data

__Affected feature__: Renaming collection and/or arangodbrestore

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. Create collections pmlibtype and pmvartype.
2. Rename collection pmlibtype to pmlibspec
3. Rename collection pmvartype to pmlibtype

__Problem__:
There seems to be a problem if the globalId of a collection matches another collection name.  Renaming a collection does not change it's primary key's globalid value. This manifested itself as a problem in the foxx app where it couldn't identify an object correctly.  When debugging this problem, we found we couldn't restore from the dump. The fix was to correct the globalid in the structure.json files before restoring.  Since we can't delete a primary key, patching the dump seemed the only solution.

arangorestore produces this error:

2020-07-31T18:00:16Z [256] INFO [94913] {restore} # Loading data into document collection 'pmlibtype', data size: 2031 byte(s)
2020-07-31T18:00:16Z [256] ERROR [d5d06] {restore} Error while creating indexes for collection 'pmlibspec': got invalid response from server: HTTP 404: 'collection or view not found' while executing 'restoring indexes' with this payload: '{"indexes":[{"id":"233","type":"hash","name":"idx_233","fields":["name"],"unique":true,"sparse":false,"deduplicate":true}],"parameters":{"allowUserKeys":true,"cacheEnabled":false,"cid":"672","deleted":false,"globallyUniqueId":"pmlibtype","id":"672","isSmart":false,"isSystem":false,"keyOptions":{"allowUserKeys":true,"type":"traditional","lastValue":88595600},"minReplicationFactor":1,"name":"pmlibspec","numberOfShards":1,"planId":"230","replicationFactor":1,"shardKeys":["_key"],"shards":{},"status":3,"type":2,"version":7,"waitForSync":false}}'
2020-07-31T18:00:16Z [256] INFO [6ae09] {restore} # Successfully restored document collection 'pmlibtype'
2020-07-31T18:00:16Z [256] ERROR [cb69f] {restore} got invalid response from server: HTTP 404: 'collection or view not found' while executing 'restoring indexes' with this payload: '{"indexes":[{"id":"233","type":"hash","name":"idx_233","fields":["name"],"unique":true,"sparse":false,"deduplicate":true}],"parameters":{"allowUserKeys":true,"cacheEnabled":false,"cid":"672","deleted":false,"globallyUniqueId":"pmlibtype","id":"672","isSmart":false,"isSystem":false,"keyOptions":{"allowUserKeys":true,"type":"traditional","lastValue":88595600},"minReplicationFactor":1,"name":"pmlibspec","numberOfShards":1,"planId":"230","replicationFactor":1,"shardKeys":["_key"],"shards":{},"status":3,"type":2,"version":7,"waitForSync":false}}'
2020-07-31T18:00:16Z [256] INFO [a66e1] {restore} Processed 5 collection(s) in 0.220987 s, read 11186 byte(s) from datafiles, sent 4 data batch(es) of 11182 byte(s) total size

__Expected result__:
No error

**Comment by maxkernbach** [comment]
Hi @ggendel,

I am wondering how the collections were created in the first place since the `globallyUniqueId` value generally does not match the collection name.

Did you specify any non default server options or parameters at collection creation that lead to this behaviour?

**Comment by ggendel** [comment]
We create the collections programmatically.  We read the application schema in  a JSON file and then use db._create(collection) for ones that don't exist,  We subsequently add the specified indexes.

**Comment by Simran-B** [comment]
@ggendel Can you share example code which shows how you perform these operations?

The globallyUniqueId does look odd indeed, it is normally more like "h32E0BA8688FC/70471".

**Comment by ggendel** [comment]
@Simran-B This is probably more than you want and less than you need.  Here are the functions that turn the JSON schema into collections.  There is a second piece that recognizes changes to an existing schema and applies them.  Let me know if you need that as well.  The "obliterate" option was used for early development to start from a clean slate.  It is no longer used.  Feel free to critique the code as it was created early in my javascript and ArangoDB foray.

`function createCollections(obliterate) {
  // noinspection Annotator
  const collections = db._collections();
  const existing = {};
  for (let i = collections.length; i--;) {
    existing[collections[i].name()] = collections[i];
  }
  for (let table in schema.tables) {
    if (schema.tables.hasOwnProperty(table)) {
      if (obliterate && existing.hasOwnProperty(table)) {
        // noinspection Annotator
        db._drop(table);
      }
      if (obliterate || !existing.hasOwnProperty(table)) {
        db._create(table);
      }
      // Create any indexes:
      const attributes = schema.tables[table].attributes;
      for (let attr in attributes) {
        if (attributes.hasOwnProperty(attr)) {
          if (attributes[attr].index) {
            const index = {type: "hash", fields: [attr]};
            if (attributes[attr].unique) {
              index.unique = true;
            }
            // noinspection Annotator
            db[table].ensureIndex(index);
          }
        }
      }
      if (schema.tables[table].hasOwnProperty('options')) {
        // noinspection Annotator
        if (schema.tables[table].options.flush) {
          db[table].truncate();
        }
      }
    }
  }
  // Initial population of collections
  let initial;
  try {
    // noinspection JSFileReferences
    initial = require('../lib/PmInitial');
    for (let type in initial) {
      if (initial.hasOwnProperty(type)) {
        const table = schema.types[type].table;
        for (let i of initial[type]) {
          i['type'] = type;
          // noinspection Annotator
          db._query(`UPSERT {name:"${i['name']}"} INSERT ${JSON.stringify(i)} UPDATE ${JSON.stringify(i)} IN ${table}`);
        }
      }
    }
  }
  catch(e) {
    console.warn(e);
  }
  return existing;
}

function createGraph(obliterate, existing) {
  // Build a object to table map so we can generate the appropriate
  // edge definitions to these instead of objects.
  const tableMap = {};
  let model, table, info;
  for (let object in schema.types) {
    if (schema.types.hasOwnProperty(object)) {
      table = schema.types[object].table;
      if (table) {
        tableMap[object] = table;
      }
    }
  }
  const edges = {};
  for (model in schema.types) {
    if (schema.types.hasOwnProperty(model)) {
      model = schema.types[model];
      if (model.hasOwnProperty('links') && model.hasOwnProperty('table')) {
        for (let link in model.links) {
          if (!model.links.hasOwnProperty(link)) {
            continue;
          }
          if (!model.links[link].hasOwnProperty('to')) {
            continue;
          }
          const toList = model.links[link].to;
          if (toList.length === 0) {
            continue;
          }
          const edgeName = 'pm_' + link;
          if (edges.hasOwnProperty(edgeName)) {
            info = edges[edgeName];
          }
          else {
            info = {};
          }
          table = model.table;
          if (!info.hasOwnProperty(table)) {
            info[table] = true;
          }
          for (let k = toList.length; k--;) {
            const to = toList[k];
            if (tableMap.hasOwnProperty(to)) {
              table = tableMap[to];
              if (!info.hasOwnProperty(table)) {
                info[table] = true;
              }
            }
            edges[edgeName] = info;
          }
        }
      }
    }
  }
  // Turn the edge list into edge definitions.
  const definitions = [];
  for (model in edges) {
    if (edges.hasOwnProperty(model)) {
      if (obliterate && existing.hasOwnProperty(model)) {
        // noinspection Annotator
        db._drop(model);
      }
      const tables = [];
      for (table in edges[model]) {
        if (edges[model].hasOwnProperty(table)) {
          tables.push(table);
        }
      }
      // Note: for bi-directional traversals we need to include all
      // tables on the from and to lists.
      definitions.push({
        collection: model,
        from: tables,
        to: tables
      });
    }
  }
  // noinspection Annotator
  const graphs = db._graphs.toArray();
  for (model in graphs) {
    if (graphs.hasOwnProperty(model)) {
      model = graphs[model];
      // noinspection Annotator
      if (model._key === globals.graph) {
        // noinspection Annotator
        graph._drop(globals.graph);
        break;
      }
    }
  }
  // noinspection Annotator
  graph._create(globals.graph, definitions);
}
`

**Comment by ggendel** [comment]
Sorry, hit wrong button

**Comment by maxkernbach** [comment]
Hi @ggendel,

Is it possible that the collections were created with an older version, that set "globallyUniqueID" to its collection name? In case you create new collections with your current version (3.5.5), is "globallyUniqueID" still set to the collection name?

**Comment by ggendel** [comment]
This is very possible.  Our production setups were originally on 3.1.  It was after the 3.5 upgrade process that we saw this problem.

**Comment by Simran-B** [comment]
@ggendel Can you clarify whether you upgraded in-place (switching out the server binary and upgrading the collection data) like 3.1 -> 3.2 -> 3.3 -> 3.4 -> 3.5 or 3.1 -> 3.5? Or did you dump it from 3.1 and restore it in 3.5?

**Comment by ggendel** [comment]
I'm pretty sure we did an arangodump and then arangorestore after upgrading the server.  I finally convinced the IT support team that we needed to upgrade ArangoDB but they didn't want to roll through installing each major version so they used the dump->restore method to skip the steps.  If this is a no-no then I need to let them know to prevent future issues.

**Comment by Simran-B** [comment]
Thanks, dump & restore is the recommended procedure and nothing should be wrong with it. Upgrading in place should also be fine as long as no minor versions are skipped (3.2-3.4), as subsequent versions might not account for certain legacy update requirements.

Assuming that a dump was used, I can only guess that there's some problem with 3.1 which led to the collection name "globallyUniqueID".

**Comment by ggendel** [comment]
Thanks.  Since we have a workaround and don't expect new installations to have this issue, I'll consider this closed.
