### ISSUE TITLE
Use of two controllers in Foxx shows problem in generation of Swagger docs

### ISSUE THREAD

**Issue by StatLaw** [arangodb/arangodb#1235]
When using two controllers in a Foxx application, the documentation associated with the first controller somehow leaks into the Swagger doc with respect to the second.

I've verified this behaviour using a test application in 2.4.1 and 2.4.2. Here is the screenshot:

![2015-02-06_1189x1048](https://cloud.githubusercontent.com/assets/10876819/6074574/7ef944aa-adb9-11e4-9147-8d794e394b3c.png)

The text under /step2 appears (unintentionally) to be the first sentence of the text of the get method of /step1. Based on the documentation in controllers/step2.js it should actually read "Process post."

The code for this test app is available in my repository: https://github.com/StatLaw/arangodb.git

**Comment by mchacki** [comment]
Hi,
thanks a lot for reporting this. And for creating the minimal example.
I can reproduce it and start bug hunting.
I will keep you informed.

**Comment by mchacki** [comment]
I fixed this bug in 2.4 and the upcomming 2.5.

**Comment by StatLaw** [comment]
Excellent. Thank you.
