### ISSUE TITLE
Upgrading Foxx app turn it into development mode

### ISSUE THREAD

**Issue by joserwan** [arangodb/arangodb#12363]
## My Environment

* __ArangoDB Version__:        3.6.5 (arangodb3_3.6.5-1_amd64.deb)
* __Storage Engine__:             RocksDB
* __Deployment Mode__:         Single Server
* __Deployment Strategy__:    ArangoDB Starter in Docker
* __Configuration__:               
* __Infrastructure__:               Ubuntu / Docker
* __Operating System__:        Ubuntu 20.04
* __Total RAM in your machine__:        8G
* __Disks in use__:        HDD
* __Used Package__:            Docker - official Docker library

## Component, Query & Data

__Affected feature__:
Foxx-CLI

## Steps to reproduce

1. foxx upgrade -D test-projections -v /dependencies

__Problem__:

I installed my foxx app in production mode. Whe I upgrade it, it turns to development mode.

__Expected result__:

Stay in production mode

@pluma

**Comment by pluma** [comment]
I've observed the behavior in 3.7 as well and was able to confirm both `foxx-cli` and `arangojs` correctly set `development=false`, so I believe this to be a bug in the Foxx HTTP API or the server-side `foxx/manager.js`.
