### ISSUE TITLE
Are multiple bodyParams allowed in Foxx route?

### ISSUE THREAD

**Issue by a-s-o** [arangodb/arangodb#1237]
Hello,

I am trying to do as follows in a Foxx controller: 
```
   controller
      .post('/', function (req, res) {
         var document= Collection.save( req.params('document') );
         res.json(document.forClient());
         
         Activities.save({
             label: 'createdDocument',
             _from: req.params('user'),
            _to: document.get('_id')
         });
      })
      .bodyParam('document', {
         description: 'Document being created',
         type: DocumentModel
      })
      .bodyParam('user', {
         description: 'ID of user that created the document',
         type: joi.string().required()
      });
```
I have `rootElement` set to true in the `manifest.json`

The error I am getting is:
```
2015-02-07T21:41:06Z [1396] ERROR TypeError: Cannot read property 'toJSONSchema' of undefined
2015-02-07T21:41:06Z [1396] ERROR   at [object Object].extend.bodyParam (c:/Program Files/ArangoDB 2.4.2/share/arangodb/js/server/modules/org/arangodb/foxx/request_context.js:485:80)
```
Is there an alternative way of getting additional attributes in the body of the request?

**Comment by newoga** [comment]
@a-s-o:

A request only has a single body. In your example, it looks like you are trying to document query parameters (not the body) since you are calling `req.params('document')` and `req.params('user')`. In that case, use the `.queryParam()` instead of `.bodyParam()` to appropriately document the query parameters. 

The documentation spells it out pretty well here: https://docs.arangodb.com/Foxx/FoxxController.html

**Comment by pluma** [comment]
I can not reproduce this problem in the current development version. The problem was probably fixed during the changes to Foxx in the upcoming 2.5 release:

```js
var MyModel = require('org/arangodb/foxx').Model.extend({
  schema: {y: joi.number().integer()}
});

var ctx = controller.post("/multiple-bodies", function (req, res) {
  res.json({
    one: req.params('one'),
    two: req.params('two').forClient()
  });
});
ctx.rootElement = true; // override manifest for testing
ctx
.bodyParam('one', {type: joi.object().keys({x: joi.string()}), description: 'the data'})
.bodyParam('two', {type: MyModel, description: 'the model'});
```

Note that the API explorer doesn't handle multiple body parameters properly, though.

**Comment by a-s-o** [comment]
Okay, thanks for checking.
