### ISSUE TITLE
Foxx App keeps asking for password

### ISSUE THREAD

**Issue by rotatingJazz** [arangodb/arangodb#1240]
`ArangoDB 2.4.3` on Ubuntu

I am trying to follow this cookbook: https://docs.arangodb.com/cookbook/FoxxFirstSteps.html

The server is set up with authentication being enabled. I have enabled the dev-app mode via the config file, restarted the server.

I log in to the web interface as a **non-root** user, go to the Applications tab and creat a new one. The application then lists up on the page. 

I go to the provided directory, create the todos.js file inside the controllers directory and adjust the manifest file accordingly.

Then (still logged in as that user), click on the new application. The application page tries to load but I am asked for Basic Auth credentials.

The problem is that neither that user's credentials work, nor the root's. So, in practice, I can't really access the app. Am I missing something or is it a bug?

**Comment by mchacki** [comment]
Hi @rotatingJazz 

i am not able to reproduce this bug, i am pretty sure you do not miss something but it is some strange browser behaviour we do not react to yet. (All browsers handle Authentication differently ;( )

So i could need a bit more information:
1) Which browser are you using to access the WebInterface
2) Which Operating System are you using? (Windows, Mac or any Linux?)
3) Are you working inside the _system database or have you switched to another one?

**Comment by rotatingJazz** [comment]
Hi @mchacki 

Thank you for looking into this!

1) Opera Next (I will try with another browser and update the issue)
2) It's another database, not `_system`, owned by the non-rot user
3) Yes but I had also tried it by opening the web interface in "private mode" with one tab

One other thing that may (or not) be relevant, because I host multiple versions on the same machine using `Docker`, I make them bind to `localhost` and use `nginx` to as a reverse proxy to have the interface served under subdomains. To eliminate the possibility of `nginx` doing anything funky, I will create a new instance, bind it to the public ip and test it directly (so there would be nothing in between the browser and `arangodb`). I 'll have it done tonight and update the issue.

**Comment by mchacki** [comment]
Hi @rotatingJazz ,

i managed to reproduce your behaviour, it seems nginx is not doing anything funky.
We have alrady fixed this issue in 2.4 branch, as a side effect of sth. else (the documentation was loaded from _system always).
It will be included in 2.4.4 and 2.5

If you want to patch your own arangodb edit the file:
`js/apps/system/aardvark/frontend/js/templates/applicationDetailView.ejs`

and change the line 41:
`<iframe src="/_db/<%= app.attributes.db%>/_admin/aardvark/standalone.html#application/documentation/<%= app.attributes._key %>" name="Documentation"></iframe>`
to
`<iframe src="/_db/<%=db%>/_admin/aardvark/standalone.html#application/documentation/<%= app.attributes._key %>" name="Documentation"></iframe>`

**Comment by rotatingJazz** [comment]
@mchacki Superb! :beer: It works perfectly, thank you very much!
