### ISSUE TITLE
FULLTEXT search doesn't work correctly for "NOT" logic

### ISSUE THREAD

**Issue by volodymyr-koval-vitech** [arangodb/arangodb#12408]
## My Environment

ArangoDB Version: 3.4.9 Community Edition
Storage Engine: RocksDB
Deployment Mode: Single Server
Deployment Strategy: Manual start
Configuration: vCPU 2
Infrastructure: AWS - t2.medium
Operating System: Centos 7
Total RAM in your machine: 4Gb
Disks in use: DataVolume 100Gb with IOPS=5000
Used Package: rpm

## Component, Query & Data

__Affected feature__:
AQL query using web interface

__AQL query (if applicable)__:
FOR doc IN FULLTEXT(Metadata, "manufacturedProduct.fullName", "-Alcohol")
    FILTER doc.dataSetId == '4551568'
    RETURN {key: doc._key, name: doc.documentCode.name, manufactor: doc.manufacturedProduct.fullName}

__AQL explain (if applicable)__:
```
Query String (215 chars, cacheable: false):
 FOR doc IN FULLTEXT(Metadata, "manufacturedProduct.fullName", "-Alcohol")
     FILTER doc.dataSetId == '4551568'
     RETURN {key: doc._key, name: doc.documentCode.name, manufactor: 
 doc.manufacturedProduct.fullName}

Execution plan:
 Id   NodeType            Est.   Comment
  1   SingletonNode          1   * ROOT
  8   IndexNode         125788     - FOR doc IN Metadata   /* fulltext index scan, projections: `documentCode`, `_key`, `manufacturedProduct`, `dataSetId` */
  4   CalculationNode   125788       - LET #3 = (doc.`dataSetId` == "4551568")   /* simple expression */   /* collections used: doc : Metadata */
  5   FilterNode        125788       - FILTER #3
  6   CalculationNode   125788       - LET #5 = { "key" : doc.`_key`, "name" : doc.`documentCode`.`name`, "manufactor" : doc.`manufacturedProduct`.`fullName` }   /* simple expression */   /* collections used: doc : Metadata */
  7   ReturnNode        125788       - RETURN #5

Indexes used:
 By   Type       Collection   Unique   Sparse   Selectivity   Fields                               Ranges
  8   fulltext   Metadata     false    true             n/a   [ `manufacturedProduct.fullName` ]   FULLTEXT("Metadata", "manufacturedProduct.fullName", "-Alcohol")

Optimization rules applied:
 Id   RuleName
  1   replace-function-with-index
  2   inline-subqueries
  3   move-calculations-up
  4   move-filters-up
  5   move-calculations-up-2
  6   move-filters-up-2
  7   reduce-extraction-to-projection
```

__Dataset__:
```
{
  "manufacturedProduct": {
    "code": "55319-805",
    "codeSystem": "2.16.840.1.113883.6.69",
    "fullName": "Family Wellness Sterile Alcohol",
    "name": "Family Wellness Sterile Alcohol",
    "suffix": ""
  }
},
{
  "manufacturedProduct": {
    "code": "0615-7695",
    "codeSystem": "2.16.840.1.113883.6.69",
    "fullName": "Fexofenodine Hydrochloride",
    "name": "Fexofenodine Hydrochloride",
    "suffix": ""
  }
}
```

__Size of your Dataset on disk__:
60Gb

## Steps to reproduce

1. Execute provided query

__Problem__:
ArangoDB returning full collection

__Expected result__:
ArangoDB will return only documents which doesn't have "Alcohol" word

**Comment by Simran-B** [comment]
The NOT examples in the documentation always start with a search term that you want to find, then exclude another term:
https://www.arangodb.com/docs/stable/aql/functions-fulltext.html
Only excluding terms without selecting any might not be supported, but is apparently silently accepted, which isn't good.
As an alternative, you could look into ArangoSearch.

**Comment by volodymyr-koval-vitech** [comment]
Thank you for your response.
