### ISSUE TITLE
Question about arangod log rotation

### ISSUE THREAD

**Issue by shabtaisharon** [arangodb/arangodb#12419]
## My Environment

* __ArangoDB Version__:        3.6.3 Community Edition
* __Storage Engine__:             RocksDB
* __Deployment Strategy__:   Manual Start

## Component, Query & Data

__Affected feature__: logs

I couldn't find any way to force `arangod` logs to rotate, the preferred way is by size, I've tried to look in `./arangod --help`.

Is there something I'm missing?

Thanks,
Sharon

**Comment by jsteemann** [comment]
arangod itself doesn't have any option to rotate its logs automatically.
Normally, log rotation is triggered by an external process, such as logrotated. Basically one needs to tell logrotate.d to send a specific signal (SIGHUP) to arangod. arangod will then flush its logs and open a new one.

Example configuration (with placeholders in it) can be found here:
https://github.com/arangodb/arangodb/tree/3.6/Installation/logrotate.d

**Comment by shabtaisharon** [comment]
Thank you @jsteemann i'll take a look at that and come back here if i have questions

**Comment by jsteemann** [comment]
It is also possible that these files are actually installed when an ArangoDB release package gets installed. 
Log configuration seems to depend on whether systemd or sysv init is used. Unfortunately I am not an expert in either, so I can't tell you where to check if the configuration files are actually installed :cry:

**Comment by shabtaisharon** [comment]
from you answer i get it that arangod doesn't have a build-in option for log rotation :(

**Comment by jsteemann** [comment]
@shabtaisharon : that is true.
arangod will not rotate its logs by itself, neither based on elapsed time nor on logfile size.
It _can_ be sent a signal to tell it to rotate its logs though. But that signal needs to be sent by some other process (e.g. logrotated, systemd).

**Comment by shabtaisharon** [comment]
Follow up questions: 
What is the signal?
Do I need to enable it?
How many logs will it save?

**Comment by jsteemann** [comment]
The signal is SIGHUP.
It can be sent to a process from bash via the `kill` command.
For example, if you have a single _arangod_ process running (and the `pidof` command exists) you could do:
```
kill -SIGHUP `pidof arangod`
```
You can also send signals from various programming languages if preferred.
Sending the signal to the arangod process will make it close its current logfile and start a new one, so the old logfile can be moved away/compressed/removed (whatever is the intention).
The arangod receiving the signal should log something like
```
2020-08-12T21:46:48Z [173982] INFO [33eae] hangup received, about to reopen logfile
2020-08-12T21:46:48Z [173982] INFO [23db2] hangup received, reopened logfile
```
whenever it receives a SIGHUP signal.

**Comment by shabtaisharon** [comment]
Thank you very much! That is very helpful information 🥇

**Comment by dothebart** [comment]
This explains how logrotation is intended to work on Linux:
https://www.tecmint.com/install-logrotate-to-manage-log-rotation-in-linux/
ArangoDB is expected to fit into that machinery by doing what `SIG_HUP` is intended to do.

**Comment by shabtaisharon** [comment]
Thank you @dothebart, do you by any chance have information for windows base install?

**Comment by dothebart** [comment]
Windows is inferior in so many ways. The windows eventlog is just another example, continuing to signal handling, as the OS only has limited support for some signals.

**Comment by dothebart** [comment]
closing as "won't fix" since its not easily possible on windows.
