### ISSUE TITLE
Foxx named route / reverse routing

### ISSUE THREAD

**Issue by newoga** [arangodb/arangodb#1242]
It would be cool from within a FoxxController to be able to:
(1) Define a name for a particular route, and 
(2) From the named route, be able to re-build (reverse route) the url by passing the name of the route and an object. For example:

```js

var url = require('org/arangodb/some_path_to_url_function').url;

app.get('app.task.get', '/tasks/:key', function (req, res) {
  var task = tasks.findByKey(req.params('key'));
  res.json({
    id: task.get('_key'),
    href: url('app.task.get', task), // output: http://host:8529/tasks/12312904
    name: task.get('name'),...
  });
});
```

Or 

```js

var url = require('org/arangodb/some_path_to_url_function').url;

app.get('/tasks/:key', function (req, res) {
  var task = tasks.findByKey(req.params('key'));
  res.json({
    id: task.get('_key'),
    href: url('app.task.get', task), // output: http://host:8529/tasks/12312904
    name: task.get('name'),...
  });
}).name('app.task.get');
```

A few considerations/concerns to implementing this:
1. How to handle passing in a model object vs a standard javscript object into the url function. Normally these libraries pass in a standard javascript object, but it would be nice to pass in a model object and it would still know how to use the `.get()` methods and work properly.
2. Where to specify the route name? Even though the first option might be cleaner and closer to how other frameworks work, the second option would be backwards compatible so i'm leaning towards that one.
3. Should url return a relative path based on string that is passed in to the corresponding get, post, put, del method or should it return absolute? 

Any thoughts?

**Comment by pluma** [comment]
CC'ing @mchacki @moonglum @fceller 

This is something I've thought about before as it would drastically simplify app-internal redirects and URL references.

How does the ongoing effort to re-write Foxx's routing affect this?

**Comment by pluma** [comment]
Moving this back to the backlog for now, probably 3.x.

**Comment by pluma** [comment]
Fixed via FOTF.
