### ISSUE TITLE
Arangosh, how do I bring it up in Terminal? Can't find it.

### ISSUE THREAD

**Issue by rusty53** [arangodb/arangodb#12435]
## My Environment

* __ArangoDB Version__:      3.6.5
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               Normal
* __Infrastructure__:               Own
* __Operating System__:        MacOS 10.15.6
* __Total RAM in your machine__:        16GB
* __Disks in use__:        SSD
* __Used Package__:              --

## Component, Query & Data

__Affected feature__:
arangsosh

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. 
2. 
3. 

__Problem__:
Accessing arangosh prompt

__Expected result__:

**Comment by dothebart** [comment]
if you use the MacOS DMG-Installer, you should have a wrapper script called `arangosh`  under the mountpoint of the DMG-image `/Arangodb3-CLI.app/Contents/Resources` . Other files will be kept in`~/opt/arangodb/...`.

**Comment by rusty53** [comment]
Thank you. I believe I used the MacOS DMG installer. Even when I show hidden files, the only thing that appears in Finder under Applications is Arangodb3-CLI.app. There are no files under that that I can see. I was expecting to see /Contents/Resources there, but don't see them. When I do a search for them in Finder, even with the hidden files shown, nothing appears.

**Comment by dothebart** [comment]
Hi, 
DMG stands for DiskiMaGe; hence when you click it, and move the icon over, your mac will mount it. 
if you open the terminal and type `mount` it should enlist the mountpoint.

**Comment by rusty53** [comment]
Thanks. I located the "Contents" folder when I hovered the Arango icon. Since the Contents folder disappears when I move the icon into the Applications icon, I decided to save the Contents folder in Applications so I could get to the arangosh. Will that cause any problems if I copy it anew anytime I upgrade ArangoDB app? I am not able to open the arangosh by opening Terminal and typing in "mount". It does appear I can open arangosh by going to it in the Contents folder I copied and opening arangosh with the Terminal app. The only problem is that it asks for a password and when I enter it, I get error message. That is the same password that gives me access to my databases via my browser. Given the latter, I am going to back burner trying to do anything in arangosh for the time being. Thank you again for your help.

**Comment by dothebart** [comment]
do you have utf-8 signs or umlauts in your password? 
I think we fixed the shell-script wrappers to properly handle blanks in passwords - you need to have them wrapped in quotes.

**Comment by rusty53** [comment]
Thanks. I will check password.

**Comment by rusty53** [comment]
My password contains one * and one #, neither of which are at beginning of password.

**Comment by dothebart** [comment]
hm, `#` is the starting of a comment in the shell - unless you quote it or escape it. That could be the problem when specifying it at the commandline - but should work if you use the dialog for it.

**Comment by Simran-B** [comment]
@rusty53 Did you have a chance to try a password without `#` or escape it?

**Comment by rusty53** [comment]
Thanks for the follow up, Simran. Not yet, will let you know.

**Comment by rusty53** [comment]
Hi Simran.

I changed the arangod.conf to “false” for authentication.

I noticed I have three files title “arangod.conf” (that doesn’t seem right).

I changed all to “false”.

Now when I run, I go right into my root without the opportunity to set a password.

Rusty.

**Comment by rusty53** [comment]
I changed the arangod.conf to “true” but I get a “Login failed” when I try to insert new password.
Rusty

**Comment by dothebart** [comment]
you should be able to stop the installation, and use `arangodb-secure-installation` to set a new password.

**Comment by rusty53** [comment]
Thank you. Will try it.

**Comment by Simran-B** [comment]
I downloaded `arangodb3-3.6.5.x86_64.dmg`, clicked it to mount it, accepted the license and dragged ArangoDB3-CLI.app over to Applications to install it. Then I launched the app, which prompted for the storage engine (auto, rocksdb, mmfiles). After that it printed the following in a terminal:

```
ArangoDB server has been started

The database directory is located at
   '/Users/<username>/Library/ArangoDB/opt/arangodb/var/lib/arangodb3'

The log file is located at
   '/Users/<username>/Library/ArangoDB/opt/arangodb/var/log/arangodb3/arangod.log'

You can access the server using a browser at 'http://127.0.0.1:8529/'
or start the ArangoDB shell
   '/Applications/ArangoDB3-CLI.app/Contents/Resources/arangosh'

Switching to log-file now, closing this window will NOT stop the server.
```

Running `/Applications/ArangoDB3-CLI.app/Contents/Resources/arangosh` gets me into the ArangoShell. Even a password like `␣␣#*//?!` (␣ = space) that I set via the Web UI works in the shell.

`ps x | grep "arangod"` reveals the command that the app uses to start the server:

`/Applications/ArangoDB3-CLI.app/Contents/Resources/opt/arangodb/sbin/arangod -c /Users/<username>/Library/ArangoDB-etc/arangod.conf -c /Users/<username>/Library/ArangoDB-etc//arangod.conf --daemon --pid-file /var/tmp/arangod.pid`

So the relevant server configuration file is `~/Library/ArangoDB-etc/arangod.conf` (hard link, i.e. same file: `/System/Volumes/Data/Users/<username>/Library/ArangoDB-etc/arangodb3/arangod.conf`)

I'm not sure what the matter is with the other configuration files:
- `/Users/<username>/Library/ArangoDB-etc/arangodb3/arangod.conf`
- `/Users/<username>/Library/ArangoDB-etc/arangod.conf-e`

I suppose the correct way to restart the server is to determine the PID (`ps x | grep "arangod"`), `kill <PID>` and clicking the app to start the server again. Configuration changes should then take effect.

My attempt to reset the root password using `arango-secure-installation` was also successful:
- Stop server
- `/Applications/ArangoDB3-CLI.app/Contents/Resources/arango-secure-installation`
- Enter new password twice
- Launch app to start server

Note that if you change the server endpoint in the config, the app will still open `http://127.0.0.1:8529` in the browser. You will have to adjust e.g. the port number to access the Web UI. Should there be a secondary server instance, e.g. managed via homebrew, then you might access the wrong instance by accident.

**Comment by Simran-B** [comment]
In case of a homebrew installation, the binaries are installed to:
- `/usr/local/opt/arangodb/sbin` (server, init and secure installation binaries)
- `/usr/local/opt/arangodb/bin` (client tools, including the starter)

`brew install arangodb` reported:

```
An empty password has been set. Please change it by executing
  /usr/local/opt/arangodb/sbin/arango-secure-installation

To have launchd start arangodb now and restart at login:
  brew services start arangodb
Or, if you don't want/need a background service you can just run:
  /usr/local/opt/arangodb/sbin/arangod
```

<details><summary>About certificates (openssl dependency)</summary>
<pre><code>A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl@1.1/certs

and run
  /usr/local/opt/openssl@1.1/bin/c_rehash

openssl@1.1 is keg-only, which means it was not symlinked into /usr/local,
because macOS provides LibreSSL.

If you need to have openssl@1.1 first in your PATH run:
  echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> ~/.profile

For compilers to find openssl@1.1 you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"</code></pre></details>

I was able to set the password with spaces etc. using `/usr/local/opt/arangodb/sbin/arango-secure-installation` without problems.

After `brew services start arangodb`, `brew services list` reports:

```
Name     Status  User   Plist
arangodb started Simran /Users/<username>/Library/LaunchAgents/homebrew.mxcl.arangodb.plist
```

The following paths all reference the same server config file of the homebrew installation:
- `/usr/local/etc/arangodb3/arangod.conf`
- `/usr/local/Cellar/arangodb/3.7.2-1/etc/arangodb3/arangod.conf`
- `/System/Volumes/Data/usr/local/etc/arangodb3/arangod.conf`
- `/System/Volumes/Data/usr/local/Cellar/arangodb/3.7.2-1/etc/arangodb3/arangod.conf`
