### ISSUE TITLE
Logs flooded with warnings about missed statistics

### ISSUE THREAD

**Issue by srusskih** [arangodb/arangodb#12451]
## My Environment

* __ArangoDB Version__:        3.1.19
* __Storage Engine__:             MMFiles
* __Deployment Mode__:        Single Server
* __Deployment Strategy__:   Manual Start in Docker
* __Configuration__:              -
* __Infrastructure__:               Google VM
* __Operating System__:        debian:jessie
* __Used Package__:              arangodb3-3.1.19-1-amd64.deb

__Problem__:

Logs are flooded (periodically) with 

```
2020-08-18T07:41:54Z [1] WARNING did not find required statistics for datafile 1085029351
```

What can be the reason?

**Comment by dothebart** [comment]
Hi, 
please note that ArangoDB 3.1 is no longer supported. 
See https://www.arangodb.com/subscriptions/ for details.
Closing as "won't fix"

**Comment by srusskih** [comment]
@dothebart thank. will consider about this.
