### ISSUE TITLE
Default Config file for packaged install incorrect

### ISSUE THREAD

**Issue by LongLiveCHIEF** [arangodb/arangodb#1246]
The docs say that the default config directory is:

    /usr/local/etc/arangodb/arangod.conf

However, having installed from the downloadable .rpm from the downloads page (for RHEL 6), the directory does not exist.

Actually, none of the stated default install directories exist.

**Comment by fceller** [comment]
Yes, you are right. This directory is valid for MacOSX, but not valid. Need to update the documentation.

**Comment by LongLiveCHIEF** [comment]
Thanks Frank! I think I've found that it's `/etc/arangodb`.  Quick Question, what's the difference between `arangob.conf` and `arangod.conf`?

If I start with `/etc/init.d/arangodb start`, will it use any configs specified in `/etc/arangob.conf`, and the other conf is for when arango is run as a daemon?

**Comment by fceller** [comment]
The config files correspond to the executables:

- arangod: the database server
- arangob: a benchmark tool
- arangosh: the shell
...

/etc/init.d/arangodb will start the server arangod, therefore it will only use `arangod.conf`. Independent of the daemon mode: arangod will always use arangod.conf.

**Comment by LongLiveCHIEF** [comment]
gotcha. Thanks!

**Comment by dwba** [comment]
I want to move arangodb databases (system & userdbs) from default location to another drive/folder. Tried moving database folders and changing 2 pointers in arangod.conf.  Appears to work for system database but can no longer see user databases.  Am I missing something?
