### ISSUE TITLE
/_api/import#json

### ISSUE THREAD

**Issue by sweeneki** [arangodb/arangodb#12475]
## My Environment

* __ArangoDB Version__:        3.6.4
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               
* __Infrastructure__:               own
* __Operating System__:        MacOS 10.13.4
* __Total RAM in your machine__:        256Gb
* __Disks in use__:        SSD
* __Used Package__:              other

## Component, Query & Data

__Affected feature__:
Swagger API using web interface

__AQL explain (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. http:/x:8529/_db/yyyy/_api/import#json?type=auto&collection=COLLECTTION_NAME&overwrite=true
2. 
3. 

__Problem__:
Swagger interface seems to have swapped the order of the type=auto&collection=COLLECTTION_NAME
should be (my guess): collection=COLLECTTION_NAME&type=auto
i.e. the 'collection' parameter should come before the 'type' parameter.
Code | Details
-- | --
400 | Error: Bad Request

{
  "code": 400,
  "error": true,
  "errorMessage": "'collection' is missing, expecting /_api/import?collection=<identifier>",
  "errorNum": 1204
}

__Expected result__:

clean import

**Comment by dothebart** [comment]
Hi, 
OpenAPI/Swagger doesn't allow for several sets of documentation for one API route. 
the `#json` was added as a workaround - please remove it while using the API.

**Comment by Simran-B** [comment]
OpenAPI v3 does support composition though. I'll evaluate if we can use that to get rid of these anchor hacks.

**Comment by sweeneki** [comment]
Thanks Gents. I was able to use the terminal commands instead.

Regards

Kieran
