### ISSUE TITLE
debian init script problems

### ISSUE THREAD

**Issue by razvanphp** [arangodb/arangodb#1247]
I identified two problems with the wheezy init script, we are using the latest version 2.4.3.

First one is that it is not checking if it is run by root, so a lot of nasty access denied errors appear instead.
````
msg: rm: cannot remove `/var/run/arangodb/arangod.pid': Permission denied
chown: changing ownership of `/var/run/arangodb': Operation not permitted
chown: changing ownership of `/var/log/arangodb/arangod.log.daemon': Operation not permitted
chown: changing ownership of `/var/log/arangodb/arangod.log': Operation not permitted
chown: changing ownership of `/var/log/arangodb': Operation not permitted
chown: changing ownership of `/var/lib/arangodb/LOCK': Operation not permitted
chown: changing ownership of `/var/lib/arangodb/databases/database-608967855395/collection-608970149155/journal-608970542371.db': Operation not permitted
chown: changing ownership of `/var/lib/arangodb/databases/database-608967855395/collection-608970149155/parameter.json': Operation not permitted
....
````

Second, is that sometimes the database is still locked when restarting the service, so it cannot start without a sleep:
````
2015-02-16T16:11:24Z [16806] ERROR database is locked, please check the lock file '/var/lib/arangodb/LOCK'
2015-02-16T16:11:24Z [16806] FATAL cannot start server: database directory is locked
````

This can also be seen in the ansible script [here](https://github.com/stackmagic/ansible-arangodb/blob/master/defaults/main.yml#L17)

**Comment by fceller** [comment]
We need to test this when 2.5.0 beta3 is out.

**Comment by razvanphp** [comment]
Thank you! What about 2.4?

**Comment by fceller** [comment]
If it works, I will cherry-pick it.

**Comment by fceller** [comment]
@razvanphp could test if it works with

https://www.arangodb.com/download-beta

**Comment by razvanphp** [comment]
We can't test beta right now, since we are about to deploy 2.4 in production and we need similiar staging environment, but I just replaced the whole init script in our 2.4 installation and it looks good.

The only thing is that it takes a lot of time to restart, and the display says arangod instead of dots I guess:
````
$ sudo /etc/init.d/arangodb restart
[ ok ] Stopping arango database server: arangod.
[....] Waiting for shutdown: arangod arangod arangod arangod arangod arangod arangod arangod arangod arangod arangod arangod arangod arangod arangod arangod arangod arangod arangod arangod arangod arangod arangod arangod arangod arangod ara[ ok arangod arangod arangod.
[ ok ] Starting arango database server: arangod.
````

**Comment by fceller** [comment]
@razvanphp perfect, I will merge the init scripts to 2.4 soon.

While shutting down ArangoDB flushes the WAL file. This might take a while.

**Comment by fceller** [comment]
@razvanphp we have a list of companies using ArangoDB in production (www.arangodb.com at the end). It would be awesome if you could contact info (at) arangodb.com

**Comment by razvanphp** [comment]
Our teams already met I guess, we had a presentation from you in Hamburg few weeks ago :) If everything goes OK in production today, of course we would love our logo there.

About the output while waiting, I would still use dots each 2 secs like mysql does `. . . . . ` instead of $NAME, because it looks like an error at first.

**Comment by fceller** [comment]
I see. It was not obvious from your github account :-)

Will change to dots.
