### ISSUE TITLE
tinkerpop stack

### ISSUE THREAD

**Issue by p1tz** [arangodb/arangodb#1249]
I am currently evaluating graph databases because the death of the titan database.

I am lookup from a java perspective and I am wondering why support for the tinkerpop stack is deprecated (https://docs.arangodb.com/Blueprint-Graphs/Blueprint-Graphs/README.html)?

Are there any plans to reimplement it? Is it gone for good? The reason is, we will not switch the database to some propriety query language/interface, because we already adhere to the well-established tinkerpop thing.

**Comment by p1tz** [comment]
also, are there any options to do full graph analytics, meaning, the whole graph (like map-reduce)?

**Comment by CoDEmanX** [comment]
Regarding graph traversal: Pregel is on the roadmap

https://www.arangodb.com/2014/11/18/intro-pregel-module

**Comment by fceller** [comment]
We are switch to a different graph API and are adapting the TinkerPop2 adaptor to it.

However, it is unclear if we will support TinkerPop3. With the acquisition of Auerlius people, it is unclear to me what direction the project will take.

Some thing are very complex in TinkerPop3 (like the property model). ArangoDB supports arbitrary documents with lists, while TinkerPop3 tries to emulate something similar allow properties with the name. This does not well to the clean document / graph model. It is becoming unclear, how to efficiently implement this - without mapping the whole graph into the TinkerPop3 server.

Therefore we decided to write a more general graph module for ArangoDB in Javascript.

**Comment by p1tz** [comment]
thank you for your time and clarification :)

I'd rather shoot myself and my whole team in the head than switch to javascript on the server side. If there are no other options I will look into switching to another standard, but as I said, I don't want to invest into writing an abstraction which still ties me into some particular produt because of exactly what happened to the aurelius people (still congratulations to them).

**Comment by fceller** [comment]
I agree, if you are a Java company, then switch to Javascript will not be an option.

On the other hand, I currently do not see an alternative. TP2 is too limited, the data model of TP3 is currently to strange to be used (IMHO).

It would be interesting to hear, if you find a standard which fits your needs.
