### ISSUE TITLE
Readonly mode for non users

### ISSUE THREAD

**Issue by nathraQ** [arangodb/arangodb#1250]
I know this is mentioned in the faqs, but the "all-or-nothing fashion" is really a bummer. Please add a readonly mode for non-users and a CRUD mode for users. As this would make it a fully working backend for small projects. Anything like assigning documents only to specific user or so would be an icing on top for a further away future

**Comment by fceller** [comment]
Collection Level security is on the road-map.

Document Level security could be simulated using Foxx, https://www.arangodb.com/foxx for an intro

**Comment by akki** [comment]
Hi

Is this about read-only access to for particular users? That would be great feature in my opinion and me (and my team) would definitely want to leverage such a thing?

Can you please point me out on how I can achieve this (or how this feature could land up in the repository)?

Thanks

**Comment by dothebart** [comment]
We're pleased to anounce that ArangoDB 3.2 containing finer grained Access controls.

You now can create users that have read only access to parts of the systems. 
In doubt please create a `public`-user with read only permissions.

Closing.
