### ISSUE TITLE
Truncate Collection from Shell Script

### ISSUE THREAD

**Issue by qohelet** [arangodb/arangodb#12529]
## My Environment

* __ArangoDB Version__:        3.5.0
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   ArangoDB Starter in Docker
* __Infrastructure__:               own 
* __Operating System__:        Ubuntu 18.04 
* __Used Package__:              Debian or Ubuntu .deb

## Component, Query & Data

__Affected feature__:
arangosh

__Problem__:
I'm trying to automate a procedure which includes to truncate a specific collection in a database and afterwards fill it with a new set of data.

The filling can easily be done with arangoimport, but how would I write a shell script which truncates a specific collection in a database?

**Comment by Simran-B** [comment]
You can use the HTTP API, e.g. with Curl or via a driver:
https://www.arangodb.com/docs/stable/http/collection-creating.html#truncate-collection

Or you may use arangosh:

- `arangosh --javascript.execute path/to/file.js`
- `arangosh --javascript.execute-string "..."`

The command would be something like `db._truncate("collname");`
See https://www.arangodb.com/docs/stable/data-modeling-collections-database-methods.html#truncate

If you execute a JavaScript file, then you may want to use `print(...)` to return something to the terminal from which you execute the command. Otherwise it will print nothing.

**Comment by qohelet** [comment]
> You can use the HTTP API, e.g. with Curl or via a driver:
https://www.arangodb.com/docs/stable/http/collection-creating.html#truncate-collection

I have seen this, but frankly I don't understand how the authentication is done.

> Or you may use arangosh:

    arangosh --javascript.execute path/to/file.js
    arangosh --javascript.execute-string "..."

That's what I'm trying:
`arangosh --javascript.execute-string \
        "db._useDatabase('testDB');db.mycol.truncate(); " \
        --log.level debug --server.endpoint tcp://XXX.YYY.ZZZ.1:8529 --server.username username --server.password password --server.database testDB --server.authentication true
`
Returns this:
```
2020-08-26T13:19:39Z [31089] DEBUG {config} found config file '/etc/arangodb3/arangosh.conf'
2020-08-26T13:19:39Z [31089] DEBUG {config} loading '/etc/arangodb3/arangosh.conf'
2020-08-26T13:19:39Z [31089] DEBUG [f6e04] {config} using default language ''
2020-08-26T13:19:39Z [31089] ERROR [979b9] JavaScript exception in file '/usr/share/arangodb3/js/client/modules/@arangodb/arango-database.js' at 1075,7: ArangoError 1228: database not found\n!      throw err;\n!      ^\nstacktrace: ArangoError: database not found\n    at Object.exports.checkRequestResult (/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js:97:21)\n    at Proxy.ArangoDatabase._queryProperties (/usr/share/arangodb3/js/client/modules/@arangodb/arango-database.js:493:14)\n    at Proxy.ArangoDatabase._useDatabase (/usr/share/arangodb3/js/client/modules/@arangodb/arango-database.js:1069:10)\n    at (command-line):1:4\n
```

It does seem like a wrong database is chosen, but the other commands work fine (also I can connect with arangosh using this commands):
`arangoimport --file "mycol.arango.json" --type json --collection "mycol" --batch-size 33554432 --server.endpoint tcp://XXX.YYY.ZZZ.1:8529 --server.username username --server.password password --server.database testDB --server.authentication true`

**Comment by qohelet** [comment]
I'm sorry, my bad. The name of the database was "testDBs". Everything works as it's supposed to.
