### ISSUE TITLE
out of heap hemory in V8 (Ineffective mark-compacts near heap limit)

### ISSUE THREAD

**Issue by caozku** [arangodb/arangodb#12544]
## My Environment

* __ArangoDB Version__:        3.6.3-1 community
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               16G memory 100G harddisk
* __Infrastructure__:               
* __Operating System__:        centos 7.6
* __Total RAM in your machine__:        16GB
* __Disks in use__:        100G
* __Used Package__:              

## Component, Query & Data

__Affected feature__:

__AQL query (if applicable)__:
```


```
__AQL explain (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

20GB

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. 
2. 
3. 

__Problem__:
export data using aql in foxx; many geneaolgy success; only one fail, this one has 40K node, not the most.

__Expected result__:
how deal with this problem.

**Comment by Simran-B** [comment]
What is the approximate size of the failing request/response? V8 has a hard upper limit for string length, which is 1GB I believe (but there might be a lower default setting), and you might hit it when the reply is serialized to JSON.

**Comment by Simran-B** [comment]
@caozku Can you provide some more information please?
