### ISSUE TITLE
Too slow when traverse nodes

### ISSUE THREAD

**Issue by max-yue** [arangodb/arangodb#12551]
python code: for node in node_col, this statement is too slow since it requests all nodes with full node features in the database. How can we make it fast, such as specify the features we want?

**Comment by Simran-B** [comment]
Hi @max-yue,
we are not sure whether your example is meant to be AQL or Python code and how/what you want to query for. Can you describe your example dataset and desired outcome please?

**Comment by Simran-B** [comment]
@max-yue Can you provide for information with an example query and dataset please?

**Comment by max-yue** [comment]
Already solved using aql, thanks.
