### ISSUE TITLE
 Compilation failed on ARM, CentOS 7

### ISSUE THREAD

**Issue by liuwenzhi0318** [arangodb/arangodb#12555]
steps：

  mkdir -p build
  cd build
  cmake .. -DCMAKE_BUILD_TYPE=Release
  make -j4

problem：
![image](https://user-images.githubusercontent.com/37536326/91550968-ffbb9280-e95b-11ea-8549-4c7a4b5034a7.png)

**Comment by liuwenzhi0318** [comment]
Finally, execute make and report the following error

**Comment by liuwenzhi0318** [comment]
supplement ： centos7.6   gcc5.4  cmake3.15.3   openssl1.1.1

**Comment by dothebart** [comment]
Hi, 
You need at least GCC 9 for latest arangodbs. 
We use static builds with libmusl; The alpine build containers that bring these tools can be found here: 
https://github.com/arangodb/oskar/tree/master/containers

**Comment by liuwenzhi0318** [comment]
> 嗨，
> 您至少需要GCC 9才能安装最新的arangodb。
> 我们在libmusl中使用静态版本；可以在这里找到带来这些工具的高山构建容器：[https](https://github.com/arangodb/oskar/tree/master/containers) :
> [//github.com/arangodb/oskar/tree/master/containers](https://github.com/arangodb/oskar/tree/master/containers)


hello
Use as follows，This problem occurs
https://github.com/arangodb/oskar/tree/master/containers/buildUbuntu4.docker
![image](https://user-images.githubusercontent.com/37536326/91790800-2de2f000-ec44-11ea-95af-1a474113d1dc.png)


Request assistance

**Comment by dothebart** [comment]
Hi, 
the actual error is much above; please re-run make and cut'n'paste the error. 
Hint: you don't need a screenshot, just put tripple-backticks around the text you paste - ` 
like 
```
this
```

**Comment by liuwenzhi0318** [comment]
> Hi,
> the actual error is much above; please re-run make and cut'n'paste the error.
> Hint: you don't need a screenshot, just put tripple-backticks around the text you paste - `
> like
> 
> ```
> this
> ```

In file included from ../../../../3rdParty/V8/v7.9.317/../v7.9.317/src/snapshot/embedded/embedded-file-writer.cc:5:
../../../../3rdParty/V8/v7.9.317/../v7.9.317/src/snapshot/embedded/embedded-file-writer.h:28:7: warning: 'class v8::internal::EmbeddedFileWriterInterface' has virtual functions and accessible non-virtual destructor [-Wnon-virtual-dtor]
   28 | class EmbeddedFileWriterInterface {
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../3rdParty/V8/v7.9.317/../v7.9.317/src/snapshot/embedded/embedded-file-writer.h:55:7: warning: base class 'class v8::internal::EmbeddedFileWriterInterface' has accessible non-virtual destructor [-Wnon-virtual-dtor]
   55 | class EmbeddedFileWriter : public EmbeddedFileWriterInterface {
      |       ^~~~~~~~~~~~~~~~~~
../../../../3rdParty/V8/v7.9.317/../v7.9.317/src/snapshot/embedded/embedded-file-writer.h:55:7: warning: 'class v8::internal::EmbeddedFileWriter' has virtual functions and accessible non-virtual destructor [-Wnon-virtual-dtor]
In file included from ../../../../3rdParty/V8/v7.9.317/../v7.9.317/src/snapshot/mksnapshot.cc:16:
../../../../3rdParty/V8/v7.9.317/../v7.9.317/src/snapshot/embedded/embedded-file-writer.h:28:7: warning: 'class v8::internal::EmbeddedFileWriterInterface' has virtual functions and accessible non-virtual destructor [-Wnon-virtual-dtor]
   28 | class EmbeddedFileWriterInterface {
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../3rdParty/V8/v7.9.317/../v7.9.317/src/snapshot/embedded/embedded-file-writer.h:55:7: warning: base class 'class v8::internal::EmbeddedFileWriterInterface' has accessible non-virtual destructor [-Wnon-virtual-dtor]
   55 | class EmbeddedFileWriter : public EmbeddedFileWriterInterface {
      |       ^~~~~~~~~~~~~~~~~~
../../../../3rdParty/V8/v7.9.317/../v7.9.317/src/snapshot/embedded/embedded-file-writer.h:55:7: warning: 'class v8::internal::EmbeddedFileWriter' has virtual functions and accessible non-virtual destructor [-Wnon-virtual-dtor]
  LINK(target) /root/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/mksnapshot
  TOUCH fcf4bc5560c5ebd918bb4fa39879f42ca902cc99..intermediate
  ACTION generating: "/root/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/icuuc/geni/snapshot.cc" ../v7.9.317/src/snapshot/embedded/embedded-empty.cc fcf4bc5560c5ebd918bb4fa39879f42ca902cc99..intermediate
  CXX(target) /root/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_snapshot/../v7.9.317/src/init/setup-isolate-deserialize.o
  CXX(target) /root/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_snapshot/../gypfiles/extras-libraries.o
  CXX(target) /root/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_snapshot/geni/snapshot.o
  CXX(target) /root/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_snapshot/../v7.9.317/src/snapshot/embedded/embedded-empty.o
  AR(target) /root/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/../gypfiles/libv8_snapshot.a
[ 14%] No install step for 'v8_build'
[ 14%] Completed 'v8_build'
[ 14%] Built target v8_build
make: *** [Makefile:152: all] Error 2

**Comment by liuwenzhi0318** [comment]
supplement：
My server is ARM Architecture，
Because the official package or mirror does not support the ARM architecture，

So, I have been trying to compile on an ARM machine, and then it has been unsuccessful to compile

**Comment by dothebart** [comment]
Hi, 
yes, ARM is not official supported. For V8 you need at least an ARM v7 host (afaik) so default Raspian won't work at all.

Whats been failing on you here is the V8 compilation, its probably having a `-WError` in some of the ARM flags in the gyp files, hence the compilation aborts. 

You can find out how CMake invokes gyp here:
  https://github.com/arangodb/arangodb/blob/devel/3rdParty/V8/CMakeLists.txt#L425

The gyp control files (similar function to CMakeLists.txt) that control these compiler flags are here:
https://github.com/arangodb/arangodb/tree/devel/3rdParty/V8/gypfiles
They could also have linux/arm specific cases, most probably there `-Werror` needs to be removed. 

The branching into the gyp created makefiles can be inspected by running `make V=1 VERBOSE=1`.

**Comment by dothebart** [comment]
Hi, 
I'm closing this as solved. 
If any more questions arise, please let us know.
