### ISSUE TITLE
agency binary not found

### ISSUE THREAD

**Issue by oneminute** [arangodb/arangodb#1256]
When I launch a cluster on OS X with ArangoDB-CLI 2.4.3 using k.launch(). It return the errorMessage "agency binary not found at '/Applications/ArangoDB-CLI.app/Contents/MacOS/opt/arangodb/bin/etcd-arango".
And I do not found etcd-arango in that path.

**Comment by fceller** [comment]
It seems the etcd got lost. Will check.

**Comment by fceller** [comment]
@oneminute can you please test with 2.4.4 (which will be released today)

**Comment by oneminute** [comment]
OK, I'm trying.

**Comment by oneminute** [comment]
It worked very well in cluster mode.
