### ISSUE TITLE
TimeZone conversion

### ISSUE THREAD

**Issue by coronabytes** [arangodb/arangodb#12566]
Feature request for timezone conversion.

We store alot of activities (starttime, endtime) in UTC in our database. Now as the product matures customers kinda want their reports evaluated in local time. While activities can be converted on the client side without problem - aggregations like 
COLLECT day = DATE_TRUNC(x.Start, 'day') cannot.
We'd require some sort of COLLECT day = DATE_TRUNC(DATE_FROMUTC(x.Start, 'W. Europe Standard Time'), 'day') 

Now a single utc offset like +1 would be easy, however we'd require this function to calculate historical daylight saving times.

For performance reasons we'd probably materialize day_local as a 'shadow property' for the 'default' customer timezone.
But also need the ability to recalculate on-the-fly for dynamic timezone parameters.

Hint: Operation Systems have different timezone names (W. Europe Standard Time for example exists only on Windows) a uniform way to address them (but dont forget daylight savings) would be nice.

**Comment by coronabytes** [comment]
Hi,
after quick research boost (already a arangodb dependency) can do this "somewhat"
and there is https://github.com/HowardHinnant/date for full support of the IANA TimeZone Database

TZ DB would need to be bundled with arangodb / or use the operating system one

Offset to DATE_TRUNC is not useful, we could just use DATE_ADD() 
(however correct daylight saving next to impossible - for germany / switzerland we could probably do it)

I see no way to implement this as a UDF in javascript
 - dump tz db as json...

**Comment by dothebart** [comment]
The current implementation already uses the Howard Hinnant implementation - see the Link in my post. 
So if you want to make an implementation sugestion feel free to open a pullrequest using it.

**Comment by coronabytes** [comment]
Haven't touched C++ in years, but somehow got it using the tz part of hinnant.
Basically I just need an AQL function wrapping maked_zoned and I still propose:

DATE_FROMUTC( arango_datetime_utc, target_timezone_string)

Alternatives:
DATE_MAKEZONED(arango_datetime_utc, target_timezone_string)
DATE_MAKEZONED(arango_datetime, source_timezone_string, target_timezone_string)

(it seems you only like one underscore...)

and for you to include the iana tz database https://www.iana.org/time-zones
plus for windows https://raw.githubusercontent.com/unicode-org/cldr/master/common/supplemental/windowsZones.xml

Snippet:
```
auto now = system_clock::now();
std::cout << now << " UTC\n";
std::cout << make_zoned("Europe/Berlin", now) << '\n';

auto winter_utc = sys_days{2020_y/3/10} + 12h;
auto summer_utc = sys_days{2020_y/4/10} + 12h;

auto winter_berlin = make_zoned("Europe/Berlin", winter_utc);
auto summer_berlin = make_zoned("Europe/Berlin", summer_utc);

std::cout << format("%Y-%m-%dT%H:%M:%S", winter_berlin) << '\n';
std::cout << format("%Y-%m-%dT%H:%M:%S", summer_berlin) << '\n';
```

Output:
```
2020-09-04 04:06:44.9994505 UTC
2020-09-04 06:06:44.9994505 CEST
2020-03-10T13:00:00
2020-04-10T14:00:00
```

Im unsure if the output format for arango should be

2020-03-10T13:00:00
2020-03-10T13:00:00.000Z
or even 
2020-03-10T13:00:00 CET (not sortable?)

**Comment by Simran-B** [comment]
Related: #1630

**Comment by coronabytes** [comment]
I tried implementing this myself and while adding AQL functions is easy enough the std::chrono conversion to hinnants date format and back is not (for me atleast - damn template madness)

Even then u'd probably never accept my pull request, since quite alot of stuff needs to happen.
But let me share what I found so far:

- New AQL Function DATE_ZONED (t.b.d)
  - parameter : utc timestamp, target timezone string, (optional) source timezone - default UTC
  - convert timestamp with make_zoned
  - return time value
- Somewhere in the startup code set_install needs to be exeuted
  - set_install(BASEPATH+ '/etc/arangodb3')
- Setup needs to modified to include folder /etc/arangodb3/tzdata with content
  - https://www.iana.org/time-zones (data package)
  - https://raw.githubusercontent.com/unicode-org/cldr/master/common/supplemental/windowsZones.xml
- Using the OS supplied tzdata is not recommended since
  - non existant on Windows
  - 'broken' on MacOS  (Leap seconds missing before 10.5?)
  - Linux should be fine however
- Also update hinnant date lib your version is like 3 years old

**Comment by dothebart** [comment]
Hey, thats good news. 
We'd well accept a PR if: 
- a signed CLA is available https://www.arangodb.com/community/
- a good set of tests is available for the new functionality - https://github.com/arangodb/arangodb/blob/devel/tests/js/server/aql/aql-functions-date.js
- and it would be nice if an accompanying PR to https://github.com/arangodb/docs/tree/master/3.8 adds documentation to the new functions

Else I wouldn't have hinted this.

**Comment by coronabytes** [comment]
Good news everyone,
Got it working in branch https://github.com/coronabytes/arangodb/tree/timezones

However, I'd like to make a deal:
I'll sign the CLA and make a "minimal" pull request and you guys just take what you need and fill in the rest. (tests, docs, ...)

I had to do horrible things with the tz.cpp in cmake (which I never used before)
and had to update "date" to 3.0.0 which fixed my code but broke DATE_DAYOFWEEK which I then fixed to my best understanding.

Also no clue where in your codebase to call set_install or how to copy the tzdata folder to output (probably cmake)

**Comment by dothebart** [comment]
probably the handling of the ICU data can be taken as cut'n'paste example.
- https://github.com/arangodb/arangodb/blob/devel/3rdParty/V8/CMakeLists.txt#L464 creates the locations for the ICU data. You would probably do similar in the 3rdparty CmakeLists.txt. 
- https://github.com/arangodb/arangodb/blob/devel/cmake/ArangoDBInstall.cmake#L244 is then responsible for translating the paths and doing the actual install. 
- https://github.com/arangodb/arangodb/blob/devel/lib/Basics/directories.h.in is responsible for transporting the default location cmake -> c++
- https://github.com/arangodb/arangodb/blob/devel/lib/ApplicationFeatures/LanguageFeature.cpp is then responsible for locating and loading the file at program start. 

Though that linux distributions keep it in `/etc/` I'd rather put it into `/usr/share/arangodb3` - all the same as the ICU data.

**Comment by dothebart** [comment]
Closing this as solved since 
https://github.com/arangodb/arangodb/pull/12646 
has been merged. 
Thanks again for the contribution and the good discussions around the topic. 

Further 
https://github.com/arangodb/arangodb/issues/12680
will be used to discuss the way ahead into future changes.
