### ISSUE TITLE
ArangoDB 3.6.5 is much slower (>20m) using SORT in queries than ArangoDB 3.4.9 (<1s)

### ISSUE THREAD

**Issue by amorroxic** [arangodb/arangodb#12577]
## My Environment

* __ArangoDB Version__:        3.6.5 
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   ArangoDB Starter
* __Configuration__:               5VMs
* __Infrastructure__:               Azure
* __Operating System__:        Centos 7.5
* __Total RAM in your machine__:        64GB RAM each
* __Disks in use__:        SSD
* __Used Package__:              SUSE or RedHat .rpm

## Component, Query & Data

__Affected feature__:

It's really fast on ArangoDB 3.4.9 (<1s) and really slow on ArangoDB 3.6.5 (>20minutes)

__AQL query (if applicable)__:
```
 FOR doc IN my_collection
   FILTER doc.one_hash_prop == "my_value"
   SORT doc.last_updated desc
   LIMIT 0, 10
   RETURN doc._key

```
__AQL explain and/or profile (if applicable)__:

3.4.9 (producing fast responses)
```
Execution plan:
 Id   NodeType          Est.   Comment
  1   SingletonNode        1   * ROOT
 10   IndexNode         1464     - FOR doc IN my_collection   /* hash index scan, projections: `_key`, `last_updated` */
  5   CalculationNode   1464       - LET #3 = doc.`last_updated`   /* attribute expression */   /* collections used: doc : my_collection */
  6   SortNode          1464       - SORT #3 DESC
  7   LimitNode           10       - LIMIT 0, 10
  8   CalculationNode     10       - LET #5 = doc.`_key`   /* attribute expression */   /* collections used: doc : my_collection */
  9   ReturnNode          10       - RETURN #5

Indexes used:
 By   Type   Collection   Unique   Sparse   Selectivity   Fields        Ranges
 10   hash   my_collection      false    true          0.07 %   [ `one_hash_prop` ]   (doc.`one_hash_prop` == "my_value")

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   move-calculations-up-2
  4   move-filters-up-2
  5   use-indexes
  6   remove-filter-covered-by-index
  7   remove-unnecessary-calculations-2
  8   reduce-extraction-to-projection
```

3.6.5 (very slow query)

```

Execution plan:
 Id   NodeType          Site  Est.   Comment
  1   SingletonNode     DBS      1   * ROOT
  9   IndexNode         DBS   1464     - FOR doc IN my_collection   /* hash index scan, 1 shard(s) */    
  5   CalculationNode   DBS   1464       - LET #3 = doc.`last_updated`   /* attribute expression */   /* collections used: doc : my_collection */
  6   SortNode          DBS   1464       - SORT #3 DESC   /* sorting strategy: standard */
 12   RemoteNode        COOR  1464       - REMOTE
 13   GatherNode        COOR  1464       - GATHER 
  7   LimitNode         COOR    10       - LIMIT 0, 10
  8   ReturnNode        COOR    10       - RETURN doc

Indexes used:
 By   Name       Type   Collection   Unique   Sparse   Selectivity   Fields        Ranges
  9   idx_9769   hash   my_collection      false    true          0.07 %   [ `one_hash_prop` ]   (doc.`one_hash_prop` == "my_value")

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   move-calculations-up-2
  4   move-filters-up-2
  5   use-indexes
  6   remove-filter-covered-by-index
  7   remove-unnecessary-calculations-2
  8   scatter-in-cluster
  9   distribute-filtercalc-to-cluster
 10   distribute-sort-to-cluster
 11   remove-unnecessary-remote-scatter

```

__Dataset__:

300M objects

__Size of your Dataset on disk__:

80GB

__Replication Factor & Number of Shards (Cluster only)__:

replication factor 1

## Steps to reproduce

run this query on ArangoDB 3.4.9 and ArangoDB 3.6.5. Set up indexes for one_hash_prop (hash) and last_updated (skiplist). For ADB 3.6.9 the indexes are both "persistent index"

```
 FOR doc IN my_collection
   FILTER doc.one_hash_prop == "my_value"
   SORT doc.last_updated desc
   LIMIT 0, 10
   RETURN doc._key
```

__Problem__:

ArangoDB 3.6.5 is _much_ slower (timeout) while using SORT than ArangoDB 3.4.9

__Expected result__:

Query response < 20s

**Comment by dothebart** [comment]
Hi, 
you're switching from single server to cluster, right? 
Why did you choose this? Does your data exceed one instance? Or should you better choose an active failover setup ( https://www.arangodb.com/docs/stable/tutorials-starter.html#starting-a-resilient-single-server-pair ) to be resilient to instance failures?

**Comment by goedderz** [comment]
As @dothebart hinted, comparing a single server with a cluster does not make a lot of sense.

However, judging from the explain output, it should not take that long. Could you share a profile of the slow query, too?

**Comment by amorroxic** [comment]
The fast query (adb 3.4.9) was an active-failover setup (3vms) and the slow query (adb 3.6.5) is performed against a normal ArangoDB cluster (5vms). The query in question I was attaching to the issue:
```
 FOR doc IN my_collection
   FILTER doc.one_hash_prop == "my_value"
   SORT doc.last_updated desc
   LIMIT 0, 10
   RETURN doc._key
```
(you also have the explain output in my first post).  Many thanks for looking into this.

**Comment by goedderz** [comment]
And could you share a profile of that query as well, or even better a debug dump?

To create a debug dump you can use the _Create Debug Package_ button in the query tab of the Webinterface.

If you can't share that, you can create a profile by using the button with the same name in the Webinterface, or run `db._profileQuery` (instead of, but like, `db._query` or `db._explain`).

**Comment by goedderz** [comment]
Hi @amorroxic,

I've tried to reproduce your problem on 3.6.5, but couldn't. I've set up a cluster with 300M documents, and always get an answer in a few ms.

I've got a few questions to try and narrow the problem down.

First, in the query you've shown you `RETURN doc.key`. In the profile of 3.6.5 you've shown, you `RETURN doc` instead. Could you verify that the problem occurs with `RETURN doc.key` as well? This is very unlikely to make a difference here, but I'd like to rule it out.

Second, also just to rule it out: Did you use
* the exact same dataset, and
* the same parameters (i.e. in `FILTER doc.one_hash_prop == "my_value"`, was `"my_value"` the same)?

How do other queries behave? For example

```
 FOR doc IN my_collection
   LIMIT 0, 10
   RETURN doc._key
```
and
```
 FOR doc IN my_collection
   FILTER doc.one_hash_prop == "my_value"
   LIMIT 0, 10
   RETURN doc._key
```

would be of interest.

Thank you for your patience!

Best,

Tobias

**Comment by maxkernbach** [comment]
Hi @amorroxic,

Did you have a chance to check goedderz's latest comment?

**Comment by maxkernbach** [comment]
Hi @amorroxic,

I am closing this issue for now since we were not able to reproduce it and haven't heard back from you in a while.
In case you still face this problem, please share the requested information.
