### ISSUE TITLE
ArangoDb can't stop

### ISSUE THREAD

**Issue by charity1475** [arangodb/arangodb#12600]
## My Environment

* __ArangoDB Version__:        
* __Storage Engine__:             
* __Deployment Mode__:       
* __Deployment Strategy__:   
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:        
* __Total RAM in your machine__:        
* __Disks in use__:        
* __Used Package__:              

## Component, Query & Data

__Affected feature__:

__AQL query (if applicable)__:
```


```
__AQL explain and/or profile (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. 
2. 
3. 

__Problem__:

__Expected result__:

**Comment by charity1475** [comment]
$arangodb stop
2020-09-04T09:10:43+03:00 |FATA| Failed to shutdown starter component=arangodb error="Post http://127.0.0.1:8528/shutdown: dial tcp 127.0.0.1:8528: connect: connection refused"

I need to stop the server but i can't .

**Comment by giannisgrigorakos** [comment]
I think that you can use `sudo systemctl stop arangodb3` and then you can check if it has stopped with `sudo systemctl status arangodb3`.
