### ISSUE TITLE
How to use Arangodb as an in memory db.

### ISSUE THREAD

**Issue by giannisgrigorakos** [arangodb/arangodb#12607]
## My Environment 

* __ArangoDB Version__:        3.7.2
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   ArangoDB Starter
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:        Ubuntu 16.04
* __Total RAM in your machine__:        4Gb
* __Disks in use__:         HDD
* __Used Package__:               Debian or Ubuntu .deb 

__Problem__:
This is not a problem per se. I want to use Arangodb as an in memory database with no persistence. Because I have the 3.7.2 version the MMFiles are removed so I only have the RocksDB for database engine. Is there a way to configure RocksDB to save the data only in memory (ram) and not persist them to disk?

__Expected result__:
-

**Comment by dothebart** [comment]
Hi, 
the MMFiles storage engine also wasn't in memory only -  the indices were built up in memory on startup.
we explain how the rocksdb block caches work in this Article: https://www.arangodb.com/docs/stable/tutorials-reduce-memory-footprint.html

**Comment by nickb937** [comment]
If you truly want everything in RAM, then create a tmpfs mount point somewhere and set your ArangoDB data directory to write directly to that mount point.

**Comment by Simran-B** [comment]
As a side note, in 3.6 and older there was an option to create volatile collection in the MMFiles storage engine:

> isVolatile: If true then the collection data is kept in-memory only and not made persistent. Unloading the collection will cause the collection data to be discarded. Stopping or re-starting the server will also cause full loss of data in the collection. Setting this option will make the resulting collection be slightly faster than regular collections because ArangoDB does not enforce any synchronization to disk and does not calculate any CRC checksums for datafiles (as there are no datafiles). This option should therefore be used for cache-type collections only, and not for data that cannot be re-created otherwise. (The default is false) This option is meaningful for the MMFiles storage engine only.

https://www.arangodb.com/docs/stable/http/collection-creating.html

**Comment by giannisgrigorakos** [comment]
Thank you for your time and your recommendations. This "issue" can close from my side. Keep up the good work guys! Cheers!
