### ISSUE TITLE
Weird LTRIM function bugs

### ISSUE THREAD

**Issue by sh0umik** [arangodb/arangodb#12614]
## My Environment

* __ArangoDB Version__:        3.6.3-1
* __Storage Engine__:             RocksDB
* __Deployment Mode__:        Single Server
* __Deployment Strategy__:   Manual Start in Docker 
* __Configuration__:               default
* __Infrastructure__:               AWS
* __Operating System__:        Ubuntu 18.04
* __Total RAM in your machine__:   4GB
* __Disks in use__:        SSD
* __Used Package__:   Docker - official Docker library

## Component, Query & Data

__Affected feature__:
AQL query using web interface with drive

__AQL query (if applicable)__:
```
LET ids = ['ee94074e-34f6-47f8-a97e-cc11a344c71b']
FOR x in question_groups_edges
    LET question_id = LTRIM(x._from, "questions/")
    LET group_id = LTRIM(x._to, "groups/")
	FILTER CONTAINS(ids, question_id)
	//COLLECT id = question_id  into groups = DOCUMENT(groups, group_id)
RETURN {
    x : x,
    question_id : question_id
}
```
__AQL explain and/or profile (if applicable)__:
This is the output
```
[
  {
    "x": {
      "_key": "619ce215-10a3-412e-97f0-785b008ec251",
      "_id": "question_groups_edges/619ce215-10a3-412e-97f0-785b008ec251",
      "_from": "questions/ee94074e-34f6-47f8-a97e-cc11a344c71b",
      "_to": "groups/781586186",
      "_rev": "_bFII5ey---",
      "relation": "has_many",
      "from": "question",
      "to": "group",
      "created_at": "2020-09-09T17:05:41Z"
    },
    "question_id": "94074e-34f6-47f8-a97e-cc11a344c71b"
  }
]
```
As you can see `ee` is missing in front of the question_id. I Left trimmed just `questions/` part but its trimming `questions/ee` ?? why is that. Later on i solved `LTRIM(x._from, "questions/")` with `SPLIT(x._from, "questions/")[1]` 

The funny thing is, this type of behavior happens randomly. 

__Expected result__:

```
[
  {
    "x": {
      "_key": "619ce215-10a3-412e-97f0-785b008ec251",
      "_id": "question_groups_edges/619ce215-10a3-412e-97f0-785b008ec251",
      "_from": "questions/ee94074e-34f6-47f8-a97e-cc11a344c71b",
      "_to": "groups/781586186",
      "_rev": "_bFII5ey---",
      "relation": "has_many",
      "from": "question",
      "to": "group",
      "created_at": "2020-09-09T17:05:41Z"
    },
    "question_id": "ee94074e-34f6-47f8-a97e-cc11a344c71b"
  }
]
```

If I put it simply ..,

```
RETURN LTRIM("questions/ee94074e-34f6-47f8-a97e-cc11a344c71b", "questions/")
```
returns 

```
94074e-34f6-47f8-a97e-cc11a344c71b
```

**Comment by Simran-B** [comment]
The second parameter specifies the **characters** that should be removed from the string, so `LTRIM(..., "questions/")` will strip any `/`, `e`, `i`, `n`, `o`, `q`, `s`, `t` and `u` from the left-hand side of the string.

While there is no function to remove a prefix, it is possible to achieve this with e.g. `SPLIT(x._from, "/")[1]`. However, the recommended way to get the collection name or document key from a document identifier is to use [PARSE_IDENTIFIER()](https://www.arangodb.com/docs/stable/aql/functions-document.html#parse_identifier):

```js
LET question_id = PARSE_IDENTIFIER(x._from).key
LET group_id = PARSE_IDENTIFIER(x._to).key
```

Here's what I would have written for the aggregation:

```js
LET ids = ['ee94074e-34f6-47f8-a97e-cc11a344c71b'][* RETURN CONCAT('questions/', CURRENT)]
FOR x in question_groups_edges
    LET question_id = x._from
    LET group_id = x._to
    FILTER question_id IN ids
    COLLECT id = question_id INTO groups = DOCUMENT(group_id)
    RETURN {
        question_id: PARSE_IDENTIFIER(id).key,
        groups
    }
```

This will utilize the edge index for the FILTER operation.

**Comment by sh0umik** [comment]
`PARSE_IDENTIFIER` solves the problem. Greate explanation.
