### ISSUE TITLE
Precompiled queries

### ISSUE THREAD

**Issue by curtdept** [arangodb/arangodb#12623]
We execute a large number of the same query with shifting params and its been observed most of the query time is listed as compilation (which I suspect includes other stuff). It would be good to cache and reuse a high hit rate (in our case it can be > 3k rps against a >40M doc collection) query plan or precompile it somehow and statistically refresh it.

**Comment by dothebart** [comment]
Hi, 
Closing this as a duplicate of https://github.com/arangodb/arangodb/issues/6999
