### ISSUE TITLE
ERROR {libiresearch} Failed to remove path

### ISSUE THREAD

**Issue by coronabytes** [arangodb/arangodb#12628]
## My Environment

* __ArangoDB Version__:        3.7.2
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Windows Service
* __Configuration__:               
* __Infrastructure__:               own
* __Operating System__:        Windows Server 2016
* __Total RAM in your machine__:        8
* __Disks in use__:        SSD Storage
* __Used Package__:      ZIP install

## Component, Query & Data

__Affected feature__:
Core

ArangoDB 3.7.1 and 3.7.2 spam this in the windows eventlog multiple times per second:

2020-09-10T13:22:04Z [2216] ERROR {libiresearch} Failed to remove path: 'C:\Projekte\arango\var\lib\arangodb3\databases\database-2524349\arangosearch-13927768_36293001\_201.cs', error 32
C:\vm02-windows\oskar\work\ArangoDB\3rdParty\iresearch\core\utils\file_utils.cpp
bool __cdecl iresearch::file_utils::remove(const wchar_t *) noexcept
1172

The file name varies and cannot be deleted manually with windows explorer due file in use.
I already deleted the files and restarted the server - they'll just get recreated and the spam starts again.
Is it possible you are trying to delete files which are still in use (under windows)?

![log](https://user-images.githubusercontent.com/7018968/92738898-a5b7c580-f37c-11ea-86b5-c1401860bcd1.PNG)

**Comment by dothebart** [comment]
Hi, 
this occurs to be an issue that should have been fixed meanwhile, but didn't make it on time for 3.7.2. 
I'm tagging this 3.7.3 therefore.

**Comment by Simran-B** [comment]
@gnusi Can you confirm that it will be fixed in 3.7.3 (in this case for Windows)?

Internal reference of a similar issue (same error message except the error code 2 vs. 32): https://arangodb.atlassian.net/browse/ES-691

**Comment by gnusi** [comment]
@Simran-B https://arangodb.atlassian.net/browse/ES-691 is completely unrelated, I think yes, 3.7.3 should contain a fix this.

**Comment by coronabytes** [comment]
Any release date for 3.7.3?
It's ~200 errors per second. I doubt thats good for performance...

**Comment by gnusi** [comment]
@coronabytes you can set log level for "libiresearch" topic to FATAL

**Comment by maxkernbach** [comment]
Hi @coronabytes,

Version 3.7.3, which includes a fix for this issue, has just been released.

Could you please upgrade and let us know whether the reported error still appears in the logs?

**Comment by coronabytes** [comment]
Hi @maxkernbach,

Yes error does not occur anymore with 3.7.3 and
level = libiresearch=fatal 
removed
