### ISSUE TITLE
Compilation error on devel branch

### ISSUE THREAD

**Issue by Arikill** [arangodb/arangodb#12647]
## My Environment

* __ArangoDB Version__:       self-compiled devel branch 
* __Storage Engine__:             RocksDB 
* __Deployment Mode__:       
* __Deployment Strategy__:   
* __Configuration__:               
* __Infrastructure__:               AWS
* __Operating System__:        Ubuntu 18.04
* __Total RAM in your machine__:        32Gb
* __Disks in use__:       SSD 
* __Used Package__:              

## Component, Query & Data

__Affected feature__:

__AQL query (if applicable)__:
```


```
__AQL explain and/or profile (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. Followed steps on https://www.arangodb.com/docs/stable/installation-compiling-debian.html
2. penultimate step: cmake -DCMAKE_C_COMPILER=/opt/bin/gcc -DCMAKE_CXX_COMPILER=/opt/bin/g++ ..
3. then: make

__Problem__:
[ 68%] Building CXX object arangod/CMakeFiles/arango_aql.dir/Aql/RestAqlHandler.cpp.o
/home/ubuntu/gitRepos/arangodb/arangod/Aql/RestAqlHandler.cpp: In static member function ‘static arangodb::ResultT< AqlExecuteCall > AqlExecuteCall::fromVelocyPack({anonymous}::VPackSlice)’:
/home/ubuntu/gitRepos/arangodb/arangod/Aql/RestAqlHandler.cpp:563:8: error: ‘callStack.std::vector< arangodb::aql::AqlCallList >::< anonymous >.std::_Vector_base< arangodb::aql::AqlCallList, std::allocator< arangodb::aql::AqlCallList > >::_M_impl.std::_Vector_base< arangodb::aql::AqlCallList, std::allocator< arangodb::aql::AqlCallList > >::_Vector_impl::< anonymous >.std::_Vector_base< arangodb::aql::AqlCallList, std::allocator< arangodb::aql::AqlCallList > >::_Vector_impl_data::_M_start’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  563 |   auto callStack = std::optional< AqlCallStack >{};
      |        ^~~~~~~~~
cc1plus: all warnings being treated as errors
arangod/CMakeFiles/arango_aql.dir/build.make:1765: recipe for target 'arangod/CMakeFiles/arango_aql.dir/Aql/RestAqlHandler.cpp.o' failed
make[2]: *** [arangod/CMakeFiles/arango_aql.dir/Aql/RestAqlHandler.cpp.o] Error 1
CMakeFiles/Makefile2:6687: recipe for target 'arangod/CMakeFiles/arango_aql.dir/all' failed
make[1]: *** [arangod/CMakeFiles/arango_aql.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

__Expected result__:

**Comment by jsteemann** [comment]
It is very likely that the compiler version used is too old to compile ArangoDB. Compiling devel requires g++9.3, but I guess Ubuntu 18 ships with an older version of g++.
Can you try compiling with a more recent compiler, probably there are backports for g++ 9 for Ubunut 18 as well.
Thanks!

**Comment by wajda** [comment]
I run into the same problem, trying to compile the latest 'devel'.
Compiling on Fedora 32, g++ 10.2.1

```shell
[wajda@alex-xps build]$ uname -a
Linux alex-xps 5.8.10-200.fc32.x86_64 #1 SMP Thu Sep 17 16:48:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

[wajda@alex-xps build]$ g++ --version
g++ (GCC) 10.2.1 20200723 (Red Hat 10.2.1-1)

```

**Comment by jsteemann** [comment]
I am aware of that devel doesn't compile properly with older compilers. g++ 7 is known to not work, and probably even g++ 8 does not work. g++ 9.3 will definitely work, because that is the compiler we use in our CI for every devel build.
I think that there are also still some issues compiling devel with g++ 10, which haven't been sorted out yet.

**Comment by maxkernbach** [comment]
Hi @wajda,

Did you have a chance to read jsteemann's latest comment?
Have you been able to build successfully with g++ 9.3?

**Comment by wajda** [comment]
Thanks for the info. Yes, I understands and sorry I forgot to reply. I don't have any host with g++ 9.3 to try, so I switched to a docker build. I think the ticket should be closed.
