### ISSUE TITLE
arangod crashed with SIGSEGV

### ISSUE THREAD

**Issue by sleepycat** [arangodb/arangodb#1265]
I'm not sure what exactly is going on, but Arangod has crashed twice, each time while I was running a query with COLLECT. 
This is the query that brought it down last:
```
db._query('FOR vertex IN vertices FILTER vertex.type == "listing" COLLECT listings = vertex WITH COUNT INTO count RETURN listings').toArray()
```
The Ubuntu apport bug reporter shows the error as "arangod crashed with SIGSEGV" and has a field called SegvReason which says "reading NULL VMA".

Arango seems to restart itself with no problems and after reconnecting with arangosh the same query works fine.

I'm running Ubuntu 14.0.4.1 amd64 and Arango 2.4.4

I realize this is not much to go on... is there some other information that would help narrow things down?

**Comment by jsteemann** [comment]
Thanks for reporting this.
The issue has been fixed in 2.4, 2.5 and devel (previous versions not affected).
