### ISSUE TITLE
Feature request: Manage UDFs with 1 source file 

### ISSUE THREAD

**Issue by WaelKarkoub** [arangodb/arangodb#12661]
It would be cool to be able to manage all the UDFs using 1 source file, as opposed to managing multiple js files unless there's a workaround I am not aware of.

**Comment by dothebart** [comment]
hm, what does actually stop you to upload UDFs from one source file one by one?

**Comment by WaelKarkoub** [comment]
It doesn't really stop me from uploading one by one, just better file management and workflow, especially for CI/CD.

**Comment by dothebart** [comment]
can you please edit your initial post, and describe how a desired workflow would look in contrast to the already existing one?

**Comment by Simran-B** [comment]
UDFs are not file based, the server stores function strings which it evaluates when you call the registered functions in AQL. So I'm not sure if I understand the request. You can already write an arangosh script which registers multiple UDFs and inline all code.

**Comment by Simran-B** [comment]
@WaelKarkoub As the UDF system isn't file based at all and because you can write a script which registers any amount of UDFs, I'm closing this as won't fix.
