### ISSUE TITLE
aql / http api - update root object ignores mergeObjects:false

### ISSUE THREAD

**Issue by baslr** [arangodb/arangodb#1267]
The document:
```
{
  _key: 123
   a : 4
}
```
aql:
```
FOR t IN test
FILTER t._key == '123'
UPDATE t WITH {} IN test OPTIONS { mergeObjects: false }
```
does not remove `a:4`

If its intended this should be documented:

```
mergeObjects:false does not apply for the document root.
```

**Comment by jsteemann** [comment]
If you want to wipe all existing attributes, then there is `REPLACE`.
`UPDATE` will really update the individual attributes in the object specified after the `WITH` clause. It works on a per-attribute basis, and in the above example, it won't update any attribute as none was specified. So it is intended.

I have added the `documentation` label for this issue so the docs can be updated if non-appropriate.

**Comment by 13abylon** [comment]
From the documentation: 
"The REPLACE keyword can be used to completely replace documents in a collection."

"An update operation will only update the attributes specified in document and leave other attributes untouched"

In my opinion that should be enough! :)

**Comment by ifcologne** [comment]
To get rid of attributes in an update operation, set them to null and provide the keepNull option:

FOR t IN test
FILTER t._key == '123'
UPDATE t WITH { t: null } IN test OPTIONS { keepNull: false }
