### ISSUE TITLE
SIGSEGV on installation 3.7.2-1

### ISSUE THREAD

**Issue by tarun-wadhwa-mmt** [arangodb/arangodb#12683]
## My Environment

* __ArangoDB Version__:        3.7.2-1
* __Storage Engine__:            RocksDB
* __Deployment Mode__:       Single Server, Cluster
* __Deployment Strategy__:   Manual Start , ArangoDB Starter
* __Infrastructure__:               own
* __Operating System__:        Centos 7
* __Total RAM in your machine__:        2 machines of 8GB 2 core configuration
* __Disks in use__:        SSD
* __Used Package__:              rpm

## Component, Query & Data

__Affected feature__:

Installation. Basically setting up DBserver

## Steps to reproduce

1. Ran this command to setup DBServer after running agency - 
`arangod --server.authentication=false --server.endpoint tcp://0.0.0.0:8530 --cluster.my-address tcp://m_dvp_arangodb_1.mmt.mmt:8530 --cluster.my-role COORDINATOR --cluster.agency-endpoint tcp://m_dvp_arangodb_1.mmt.mmt:8531`

__Problem__: We have a 2 node cluster wherein we tried setting up arango db in cluster mode with agency size = 1
I am able to run agency service with the command mentioned [here](https://www.arangodb.com/docs/stable/deployment-cluster-manual-start.html) . While trying to setup DBServer, i get SIGSEGV fault

`FATAL [a7902] {crash} ArangoDB 3.7.2-1 [linux], thread 0 caught unexpected signal 11 (SIGSEGV) accessing address 0x00000000000000b8: signal handler invoked`

Full stack trace - 
```
2020-09-22T09:18:05Z [17098] INFO [e52b0] ArangoDB 3.7.2-1 [linux] 64bit, using jemalloc, build tags/v3.7.2.1-0-g2c56dec4b2c-dirty, VPack 0.1.33, RocksDB 6.8.0, ICU 64.2, V8 7.9.317, OpenSSL 1.1.1g  21 Apr 2020
2020-09-22T09:18:05Z [17098] INFO [75ddc] detected operating system: Linux version 3.10.0-1062.12.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) ) #1 SMP Tue Feb 4 23:02:59 UTC 2020
2020-09-22T09:18:05Z [17098] INFO [25362] {memory} Available physical memory: 7937110016 bytes, available cores: 2
2020-09-22T09:18:05Z [17098] INFO [43396] {authentication} Jwt secret not specified, generating...
2020-09-22T09:18:05Z [17098] INFO [4a3fc] using storage engine rocksdb
2020-09-22T09:18:05Z [17098] INFO [3bb7d] {cluster} Starting up with role COORDINATOR
2020-09-22T09:18:05Z [17098] FATAL [a7902] {crash} ArangoDB 3.7.2-1 [linux], thread 0 caught unexpected signal 11 (SIGSEGV) accessing address 0x00000000000000b8: signal handler invoked
2020-09-22T09:18:05Z [17098] INFO [308c3] {crash} frame 1 [0x00007fe7ff25e24d] *no symbol name available for this frame
2020-09-22T09:18:05Z [17098] INFO [308c3] {crash} frame 2 [0x00007fe8021ee795] *no symbol name available for this frame
2020-09-22T09:18:05Z [17098] INFO [ded81] {crash} available physical memory: 7937110016, rss usage: 54677504, vsz usage: 182829056, threads: 6
Segmentation fault
```
Verified this even with Arango Starter. Getting the same exception

**Comment by dothebart** [comment]
Hi, can you please add the startup commands for all processes that you run to get into this?

**Comment by tarun-wadhwa-mmt** [comment]
This is the command for starting agency - 

```
arangod --server.endpoint tcp://0.0.0.0:8531 --agency.my-address tcp://m_dvp_arangodb_1.mmt.mmt:8531 --server.authentication false --agency.activate true --agency.size 1 --agency.supervision true --database.directory /opt/arango/data/agency
```

**Comment by dothebart** [comment]
*all* processes pls. Does `m_dvp_arangodb_1.mmt.mmt` resolve properly?

**Comment by tarun-wadhwa-mmt** [comment]
Yes m_dvp_arangodb_1.mmt.mmt is resolving properly !! 
I was trying to start this is on very first server. The above command was used for starting agency and then was starting dbserver when i encountered this error.. There isn't any other process which I started. 

I am following this doc like i mentioned - https://www.arangodb.com/docs/stable/deployment-cluster-manual-start.html
In Multiple-Instances section, it is asking to start individual processes on each node !! Am i missing something?

**Comment by dothebart** [comment]
I'm running the 3 of them like this: 
```
arangod --server.endpoint tcp://0.0.0.0:8531 --agency.my-address tcp://192.168.178.88:8531 --server.authentication false --agency.activate true --agency.size 1 --agency.supervision true --database.directory /tmp//agency


  arangod --server.authentication=false --server.endpoint tcp://0.0.0.0:8530 --cluster.my-address tcp://192.168.178.88:8530 --cluster.my-role COORDINATOR --cluster.agency-endpoint tcp://192.168.178.88:8531

arangod --server.authentication=false --server.endpoint tcp://0.0.0.0:8532 --cluster.my-address tcp://192.168.178.88:8532 --cluster.my-role DBSERVER --cluster.agency-endpoint tcp://192.168.178.88:8531 /tmp/dbserver12
```
no crash?

**Comment by tarun-wadhwa-mmt** [comment]
Are you running the latest arangodb version only? 3.7.2-1?

**Comment by tarun-wadhwa-mmt** [comment]
Got the issue  !! 
It is causing trouble with hostnames (m_dvp_arangodb_1.mmt.mmt) !! When i replaced it with ip it worked fine. Have confirmed that it is resolving fine. Seems some internal logic resolving ips is causing sigsegv

**Comment by dothebart** [comment]
ok, great - thanks. that narrows down whats required to reproduce this. 
Is the resolved IP connectable from the host itself? is it ipv4 or 6?

**Comment by tarun-wadhwa-mmt** [comment]
> Is the resolved IP connectable from the host itself?

I didn't quite understand the question. To explain the scenario better, m_dvp_arangodb_1.mmt.mmt is just an FQDN pointing to machine's IP. This is resolving fine from all AWS nodes. We generally use this approach for setting up cluster system as this skips the need of hardcoding IPs in cluster. 


> is it ipv4 or 6?

Both nodes have ipv4 IP addresses

**Comment by dothebart** [comment]
Hi, 
can you upgrade to 3.7.3 and check back whether you still can reproduce this issue? 
With 3.7.3 we added a way to add the base-pointer for the running process to the logfile, since ASLR basically makes outputting the pointers in the logfile contain values that you can't use to resolve functions later on anymore ( the logfile output of your very first post)

**Comment by Simran-B** [comment]
@tarun-wadhwa-mmt Did you have a chance to upgrade to 3.7.3 and see if that solves the issue?
