### ISSUE TITLE
Support for JSONata for json document transformation in AQL

### ISSUE THREAD

**Issue by damooo** [arangodb/arangodb#12681]
[JSONata](https://jsonata.org/) an embeddable Turing-complete expression language designed to extract and manipulate values from JSON documents. It would be great if it is supported natively in AQL.

products like [IBM app connect](https://www.ibm.com/cloud/app-connect), [elastic.io](elastic.io), etc. uses it in production. And it is lightweight, with low surface area.

**Comment by dothebart** [comment]
Hi, 
from the video on the page:
```json
phone : {
 "number": [
123,
235
]}

phone[0].number == 123
```
which imho is completely counter intuitive and directly conflicts with what AQL would do to achieve this: 
```
phone.number[0] == 123
```
AQL leans on the syntax of Javascript and other Languages, JSONata obviously doesn't. Else it wouldn't be `&` to concatenate string, which usually is used for bitwise or logic operators. 

Hence this is a clear "Won't fix".

**Comment by goedderz** [comment]
JSONata shares some nice features that you can also do in AQL with [array inline expressions](https://www.arangodb.com/docs/stable/aql/advanced-array-operators.html#inline-expressions). Though it is arguably more powerful in some aspects as well. But as @dothebart noted, it would not make much sense to integrate JSONata directly, as its syntax clashes with existing syntactical features in AQL.

**Comment by damooo** [comment]
@dothebart 

just thought JSONata will give compact way to do declarative transformations over a doc. Yes we can use AQL as such. 

@goedderz on syntax, thought that, instead of supporting it as part of AQL syntax, it may be implemented as a function like `JSONATA(doc, expression)`, to compactly evaluate such transformations.

**Comment by dothebart** [comment]
Well, at the time being there only seems to be a `.js` implementation? You could most probably already use this inside of a [User defined function](https://www.arangodb.com/docs/stable/aql/extending.html) without any further ArangoDB change.
