### ISSUE TITLE
Graph management in Java driver?

### ISSUE THREAD

**Issue by chrylis** [arangodb/arangodb#12688]
The [current docs](https://www.arangodb.com/docs/stable/drivers/java-reference-graph.html) (3.7 as of right now) indicate that it's possible to create a new graph definition from the Java API, but not to execute many of the [graph-management operations](https://www.arangodb.com/docs/stable/graphs-general-graphs-management.html), particularly the "modify a graph definition at runtime". I'm writing a Java application and would like to manage my structural changes from the Java code, but I don't see a means to (for example) define a new edge type.

Does the Java driver not have parity with the JavaScript interface? If not, I'd like to request availability.

**Comment by rashtao** [comment]
Thanks for asking, the documentation you linked is outdated and we are in the process of removing it in favor of the reference  [Javadoc](http://arangodb.github.io/arangodb-java-driver).

You can find [here](http://arangodb.github.io/arangodb-java-driver/javadoc-6_7/com/arangodb/ArangoGraph.html) the related graph management operations.

**Comment by maxkernbach** [comment]
Hi @chrylis,

Did rashtao's comment solve your question?
