### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by bumian** [arangodb/arangodb#12696]
I tried to start arangod,but have an error,  
2020-09-24T05:55:20Z [5748] FATAL failed to lock the database directory using '/var/lib/arangodb3/LOCK': system error

please help

**Comment by bumian** [comment]
![image](https://user-images.githubusercontent.com/29867399/94107372-eb41bb80-fe6f-11ea-85df-bc052dcfa404.png)

**Comment by dothebart** [comment]
Hi, 
maybe the file is not owned by the user if you started the database as root once?
Try inspecting the file using `ls -l /var/lib/arangodb3/LOCK`

**Comment by maxkernbach** [comment]
Hi @bumian,

In addition, which ArangoDB version and OS are you using?

**Comment by maxkernbach** [comment]
Hi @bumian,

I am closing this issue for now since we haven't heard back from you in a while.
In case you still face this problem, please share the requested information.
