### ISSUE TITLE
Feature request: exclude option for arangodump to exclude specific collection(s)

### ISSUE THREAD

**Issue by santo74** [arangodb/arangodb#12712]
Using arangodump it's currently only possible to dump either all collections in a database or specific collections by specifying "--collection", but in my case for example I want to export all collections except one.
Therefore it would be nice if there was an "exclude" option to specify one or more collections to exclude from the dump, similar to how the "--collection" option works, but in reverse.

**Comment by hkernbach** [comment]
Will close this ticket. Duplicate to: https://github.com/arangodb/arangodb/issues/16346
