### ISSUE TITLE
What is the recommended procedure to restart ArangoDB cluster nodes? 

### ISSUE THREAD

**Issue by ohsp123-arango** [arangodb/arangodb#12713]
## My Environment

* __ArangoDB Version__:     3.7.2   
* __Storage Engine__:        RocksDB     
* __Deployment Mode__:     CLuster  
* __Deployment Strategy__:  ArangoDB Starter 
* __Configuration__:        3 nodes cluster       
* __Infrastructure__:          own     
* __Operating System__:     RHEL 8.2   
* __Total RAM in your machine__:   32Gb     
* __Disks in use__:     HDD   
* __Used Package__:       RedHat .rpm       

## Component, Query & Data

__Affected feature__:

Cluster

__AQL query (if applicable)__:
```


```
__AQL explain and/or profile (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

80Mb

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1.  dump db
2.  restarted one cluster node and one by one.
3.  found my database gone and had to restore from arangodump.  

__Problem__:
every time I need to restart cluster nodes, I should get dump and restore it when the cluster maintenance done.

__Expected result__:
I need to get back my database under the cluster environment even after restart cluster nodes for maintenance reason.

**Comment by dothebart** [comment]
please have a look at: 
https://www.arangodb.com/docs/3.7/upgrading.html and https://www.arangodb.com/docs/3.7/upgrading-general-info.html
a run with `--upgrade` may be required: https://www.arangodb.com/docs/3.7/programs-arangod-cluster.html#upgrade

**Comment by Simran-B** [comment]
@ohsp123-arango Was dothebart's reply helpful or do you need more information?
