### ISSUE TITLE
Arangodb 2.5 - model schema not updated in test interface

### ISSUE THREAD

**Issue by diegogub** [arangodb/arangodb#1271]
Hello,  
I'm starting a foxx app with the new arangodb 2.5. It' really great! I think I found a little bug, when I change my model schema, it's not updated into the test interface. I attach an screenshot.
Thanks!
Diego
![model](https://cloud.githubusercontent.com/assets/2489012/6631838/61b0e3cc-c90b-11e4-94e3-ccb1e5e03e09.png)

**Comment by mchacki** [comment]
Hi Thanks for reporting this i will have a look at it now.

**Comment by mchacki** [comment]
Thanks a lot for reporting this. In my tests i was lucky enough not to hit this bug
