### ISSUE TITLE
Arango sending unexpected network traffic 

### ISSUE THREAD

**Issue by roman1720** [arangodb/arangodb#12714]
When arangosh is started, arango starts to communicate to these addresses:

104.26.0.87
104.26.1.87
172.67.74.126

I can't find in the documentation what it is. How can it be disabled?

**Comment by gurisko** [comment]
As per help from slack - it seems that those are version checks. You can disable it by using `--quiet` command when opening `arangosh` [[docs](https://www.arangodb.com/docs/stable/programs-arangosh-options.html)]
