### ISSUE TITLE
[3.7] Unable to access FOXX's built-in graphiql Interface

### ISSUE THREAD

**Issue by Supytalp** [arangodb/arangodb#12729]
## My Environment

* __ArangoDB Version__:        3.7.2
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start in Docker
* __Configuration__:               Nothing in particular
* __Infrastructure__:               Own
* __Operating System__:        MacOS 10.15.3
* __Total RAM in your machine__:        8
* __Disks in use__:        SSD
* __Used Package__:              Docker - official Docker library

## Component, Query & Data

__Affected feature__:
Foxx - GraphiQL interface

## Steps to reproduce

1. Create an ArangoDB 3.7 instance
2. Deploy a FOXX service (The demo `https://github.com/arangodb-foxx/demo-graphql` for example)
3. Try to access the graphiql interface

__Problem__:

I was experimenting with the FOXX services on ADB 3.6.6, and decided to try ADB 3.7.2.
On the 3.6.6 version, I could access a built-in graphiql interface at `localhost:8529/_db/<DATABASE>/<MOUNT_POINT>`, or through the FOXX service interface with the "Show Interface" button.
Now, on the 3.7.* versions, this endpoint is unaccessible and the button stays grey at all time.

Did something change regarding the build-in graphiql interface with the 3.7 release ?

**Comment by pluma** [comment]
The button stays gray unless there's a GET route on `/` relative to the service's mount point.

Try accessing the URL directly via the browser address bar.

**Comment by Supytalp** [comment]
I deployed the demo FOXX service on the `_system` database, on the `/test` mountpoint.
Trying to access `http://localhost:8529/_db/_system/test/` returns:
```
{
  "errors": [
    {
      "message": "Must provide query string"
    }
  ]
}
```

**Comment by pluma** [comment]
There seems to be a bug in 3.7 resulting in the `accept` header being dropped from the request object. This prevents graphqli from working correctly, among other things.

**Comment by pluma** [comment]
Root cause seems to be #12734.

**Comment by Supytalp** [comment]
This new issue did a better job at documenting the problem:

https://github.com/arangodb/arangodb/issues/12734

**Comment by pluma** [comment]
I'm closing this as duplicate since the problem goes away when the accept header is present and the other issue is specifically about the accept header having vanished in 3.7.
