### ISSUE TITLE
Accept header is missing from http requests 

### ISSUE THREAD

**Issue by simcha** [arangodb/arangodb#12734]
## My Environment

* __ArangoDB Version__:        3.7.2
* __Storage Engine__:             RocksDB 
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   ArangoDB Starter in Docker | Kubernetes 
* __Configuration__:               any
* __Infrastructure__:               AWS | own 
* __Operating System__:        Ubuntu 20.04
* __Total RAM in your machine__:        16GB
* __Disks in use__:        SSD 
* __Used Package__:            Docker - official 

## Component, Query & Data

__Affected feature__: GraphiQL GUI

## Steps to reproduce

1. Install GraphQL demo app https://github.com/arangodb-foxx/demo-graphql
2. Try to access GraphQL  service GraphiQL the button is gray

__Problem__:
Graphiql interface stopped working and it is giving me "'Must provide query string'" error in json. 
The demo graphql app has the same error. 
The real problem is that __req.headers__ is missing "Accept" header and makes req.accept(['json', 'html']) to always return 'json' as accept library takes null for '*'. 
Here you can see the json message in upper part `JSON.stringify(req.headers)` and actual Accept part of headers in lower right.
![Screenshot from 2020-09-29 13-51-19](https://user-images.githubusercontent.com/53755/94684235-0c9b1f80-0328-11eb-8e0b-bfdf0a05c303.png)

__Expected result__:
in Point 2. one should be able to click on green button and see GraphiQL GUI. And in foxx code one should be able to get "Accept" header.

**Comment by Simran-B** [comment]
@pluma What's the status here? Any update?

**Comment by dothebart** [comment]
the C++ protocol implementation pulls out these headers on constant request object members. These need to be re-syntesized in the V8 callgates.

**Comment by maxkernbach** [comment]
Hi @simcha,

This issue is fixed via https://github.com/arangodb/arangodb/pull/13068 in version 3.7.5.
Thanks again for reporting, the GraphQL service interface is now accessible as expected.
