### ISSUE TITLE
"None of your Coordinators is reachable" while clustering multiple servers (arangodb v2.5)

### ISSUE THREAD

**Issue by nlac** [arangodb/arangodb#1273]
Hi guys,
i faced some problem when tried to setup an 1 coordinator + 2 dbserver clustering, each server runs on separate virtual machine/ip in a vpn, all ports are enabled. All machine runs Ubuntu 14.04, all arangodb instances has its own IP set in arangod.log as `endpoint = tcp://ip.of.the.machine:8529` and set the first two cluster option to "no".
Given that i can reach each machine's web interface, i tried to configure the cluster from the coordinator's web UI (192.168.2.85), running the web UI from my local windows machine, also in the vpn.
Could you pls check the screenshots and remarks i've taken during the process:

Configuring:
![image](https://cloud.githubusercontent.com/assets/1221191/6638599/fbee28f6-c987-11e4-9c29-ae5ccc3688d3.png)

[Launch Cluster] responded:
![image](https://cloud.githubusercontent.com/assets/1221191/6638646/6e15b1ec-c988-11e4-8117-f9f193594f8c.png)

On Chrome dev panel, captured some GET requests "http://192.168.2.85:8530/_admin/aardvark/cluster/Coordinators" resulted an "500" error code and a response: `{"error":true,"code":500,"errorNum":500,"errorMessage":"A runtime error occurred while executing an action: TypeError: Cannot read property 'all' of null TypeError: Cannot read property 'all' of null\n  at buildRouting (/usr/share/arangodb/js/server/modules/org/arangodb/actions.js:1106:18)\n  at Object.routeRequest (/usr/share/arangodb/js/server/modules/org/arangodb/actions.js:1239:7)\n  at Function.actions.defineHttp.callback (/usr/share/arangodb/js/actions/api-system.js:51:15)\n"`

On 192.168.2.85, /var/log/arangodb/arangod.log, found that could be related:
`2015-03-13T12:33:38Z [12392] INFO Starting server Claus
2015-03-13T12:34:10Z [12392] INFO Could not talk to endpoint tcp://192.168.2.85:8530, giving up.
2015-03-13T12:34:16Z [12392] ERROR bootstrapping DB servers failed: Could not connect to 'tcp://192.168.2.85:8530' 'connect() failed with #111 - Connection refused'`

Could you give me some hints what kind of network (or other) problem should i look for?

Thanks!

**Comment by nlac** [comment]
Another info, after got the message "None of your Coordinators is reachable ...", checking the services on the Coordinator's system got that:

![image](https://cloud.githubusercontent.com/assets/1221191/6662774/d1108db0-cbbf-11e4-8a5f-a534ed31313f.png)

May that 0.0.0.0 be the issue? If that is, what action should i take to get an real IP there?

**Comment by fceller** [comment]
@nlac "0.0.0.0" is fine, it will bind to all interfaces. Can you check if there is a firewall?

I. e. go to machine 192.168.2.85 and check if you can reach 192.168.2.88 on port 8530 (or port 8529 for the dispatcher)?

    telnet 192.168.2.88 8530

should show something like "connected".

**Comment by nlac** [comment]
Thanks Frank, 
just tried all the below, all connected:
telnet 192.168.2.88 8530 from 85
telnet 192.168.2.89 8530 from 85
telnet 192.168.2.85 8529 from 88
telnet 192.168.2.85 8530 from 88

Today i've find an interesting workaround: if i've checked the "coordinator" checkbox for the two dbServers (so having 3 coordinators and 2 dbServers on 3 machines), the cluster launches!

![image](https://cloud.githubusercontent.com/assets/1221191/6689923/906f49b4-ccbd-11e4-9013-f7d4d79ccb19.png)

But it doesn't explain for me why the original scenario fails.

**Comment by nlac** [comment]
In the meantime, let me ask is that load on the cluster normal, with the scenario above? (no app is communicating with the cluster, the only app uses it is the ardwaark gui)

![image](https://cloud.githubusercontent.com/assets/1221191/7137851/c30ddf6a-e2bc-11e4-9a16-50bedcea50ce.png)

On one data node (Pavel) there are 25-30 request/sec..

**Comment by nlac** [comment]
Finally i found the possible reason of the issue: there were some zombie arango processes stuck on the nodes. After i killed those, i was able to start the cluster in a 1 coordinator + 2 dbserver form on 3 nodes. 
Unfortunately other issues came up with the cluster, i close this one and will start another.

**Comment by saliormoon** [comment]
how to kill the processes？Please give me some help, thanks.

**Comment by dothebart** [comment]
don't hijack old tickets. open a new one and describe your environment, what you did, what you tried to do and whats happening and how you revalidated it.

**Comment by saliormoon** [comment]
I also have a question. When I have built a cluster with one  coordinator and one DB Server, there is agecny1 in the directory: /etc/arangodb3/ (coordinator), but  agency1 and agency2 in the directory: /etc/arangodb3(DB Server1), is it right? Why agency1 has appeared twice in the different places and how do we know the cluster bulit seccessfully and how to use the cluster?
could you please help me? Thanks very much.
