### ISSUE TITLE
https://docs.arangodb.com include jquery local, not from jquery cdn

### ISSUE THREAD

**Issue by baslr** [arangodb/arangodb#1275]
Chrome Reports:
"Ihre Verbindung zu docs.arangodb.com ist durch moderne Kryptografie verschlüsselt. Diese Seite enthält jedoch andere, nicht sichere Ressourcen. Diese Ressourcen können während der Übertragung von anderen Nutzern angezeigt und von Angreifern bearbeitet werden, die das Layout der Seite verändern."

The connection is encrypted but some resources are delivered via http.

**Comment by jsteemann** [comment]
Fixed the link: @13abylon : please rebuild the docs because otherwise jquery is blocked and the site is not functional if jquery is used.

**Comment by 13abylon** [comment]
Docs are rebuild and jquery isn't blocked anymore. Thanks for fixing!
