### ISSUE TITLE
Arango Replication struck

### ISSUE THREAD

**Issue by ImSajeed** [arangodb/arangodb#12775]
ArangoDB Version: 3.4
Storage Engine : RocksDB
Deployment Mode: Single Server
Deployment Strategy : Manual Start
Infrastructure: AWS
Operating System: Ubuntu 16.04
Total RAM in your machine: 32Gb.

Tried setting up replication using the below commands

require("@arangodb/replication").setupReplication({
  endpoint: "tcp://master.domain.org:8529",
  username: "myuser",
  password: "mypasswd",
  verbose: false,
  includeSystem: false,
  incremental: true,
  autoResync: true
});

require("@arangodb/replication").sync({
  endpoint: "tcp://master.domain.org:8529",
  username: "root",
  password: "secret",
  includeSystem: true
});

both ways i'm getting below issue

![image](https://user-images.githubusercontent.com/22313972/95039293-fe654e80-06ed-11eb-87c3-7b5650b26f23.png)

**Comment by ImSajeed** [comment]
@jsteemann please help on this

**Comment by dothebart** [comment]
Hi, 
please note that [Arangodb 3.4 is EOL](https://www.arangodb.com/eol-notice/) Please upgrade to a more recent version.
