### ISSUE TITLE
Edge fails validation if additionalProperties: false

### ISSUE THREAD

**Issue by tasop-rsconnect** [arangodb/arangodb#12778]
## My Environment

* __ArangoDB Version__:        3.7.2-1
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Daemon
* __Infrastructure__:               AWS
* __Operating System__:        Ubuntu 20.04
* __Total RAM in your machine__:        2GB
* __Disks in use__:        SSD
* __Used Package__:              Debian or Ubuntu .deb

## Component, Query & Data

__Affected feature__:
Schema validation

## Steps to reproduce

1. Create edge collection
2. Add schema to disallow additional properties
3. Attempt to add document to edge collection

__Problem__:
Adding a schema to validate on an edge collection with `"additionalProperties": false` causes collection to fail validation on any insert or update.

For example, this schema rule:
```
{
  "message": "test",
  "level": "strict",
  "rule": {
    "type": "object",
    "additionalProperties": false
  }
}
```

causes an insert or update with empty contents (other than _from, _to etc.) to fail (`{}`).

The same happens if at least one property is required, and that property is present in the document to be inserted.

However, setting `additionalProperties` to `true` or a schema instead of `false` works as expected: Documents pass validation if their properties fit that schema and fail otherwise.

This seems to only affect Edge collections. Regular collections with `"additionalProperties": false` behave as expected.

__Expected result__:
The document should be allowed, as it does fit the given schema.

**Comment by maxkernbach** [comment]
Hi @tasop-rsconnect,

Thanks for your report. This issue is reproducible with a 3.7.3 single server as described.

From `arangosh`:
```
127.0.0.1:8529@_system> var schema = {     "message": "test",     "level": "strict",     "rule": {       "type": "object",       "additionalProperties": false     } };

127.0.0.1:8529@_system> db._createEdgeCollection("schemaEdgeCollection", { "schema": schema });
[ArangoCollection 57480047, "schemaEdgeCollection" (type edge, status loaded)]

127.0.0.1:8529@_system> db._query('INSERT { _from: "a/b", _to: "b/c"} INTO schemaEdgeCollection')
JavaScript exception in file '/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js' at 99,7: ArangoError 1620: AQL: test (while executing)
!      throw error;
!      ^
stacktrace: ArangoError: AQL: test (while executing)
    at Object.exports.checkRequestResult (/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js:97:21)
    at ArangoStatement.execute (/usr/share/arangodb3/js/client/modules/@arangodb/arango-statement.js:172:12)
    at Proxy.ArangoDatabase._query (/usr/share/arangodb3/js/client/modules/@arangodb/arango-database.js:957:45)
    at <shell command>:1:4
```

When creating a document collection (instead of an edge collection) with `"additionalProperties": false`, the insert of an empty document succeeds.
