### ISSUE TITLE
`foxx-manager install` deletes local source file

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangodb#1279]
`foxx-manager --server.disable-authentication false install /tmp/funkytown.zip /funkytown` deletes /tmp/funkytown.zip. It even deletes it if the install fails, for example due to an auth failure.

Only tested with 2.5 on Ubuntu.

**Comment by mchacki** [comment]
Thanks a lot for reporting.
Fixed it a minute ago. Will be contained in 2.5.1

**Comment by pekeler** [comment]
:)
