### ISSUE TITLE
TTL index not working alongside a persistent index on the same attribute

### ISSUE THREAD

**Issue by Jirka-Mayer** [arangodb/arangodb#12807]
## My Environment

* __ArangoDB Version__:        3.6.0 | 3.7.2
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   ArangoDB Starter in Docker
* __Configuration__:               default
* __Infrastructure__:               own
* __Operating System__:        Ubuntu 18.04
* __Total RAM in your machine__:        8GB
* __Disks in use__:        SSD
* __Used Package__:              Docker - official

## Component, Query & Data

__Affected feature__: TTL index

## Steps to reproduce

1. Start ArangoDB 3.7.2 instance in docker:

```sh
docker run --rm -it -e ARANGO_NO_AUTH=1 -p 8529:8529 arangodb:3.7.2
```

> First encountered on `arangodb:3.6`, same behaviour.

2. Create a collection called `my_collection`:

```sh
curl \
    -X POST \
    -d '{"name": "my_collection", "type": 2}' \
    http://localhost:8529/_db/_system/_api/collection
```

3. Create a TTL index on the `time` attribute with `0s` expiration:

```sh
curl \
    -X POST \
    -d '{"type": "ttl", "fields": ["time"], "expireAfter": 0}' \
    http://localhost:8529/_db/_system/_api/index?collection=my_collection
```

4. Create a persistent index on the `time` attribute:

```sh
curl \
    -X POST \
    -d '{"type": "persistent", "fields": ["time"], "unique": false, "sparse": false}' \
    http://localhost:8529/_db/_system/_api/index?collection=my_collection
```

5. Insert `15` documents into the collection (via Aardvark):

```
LET hourAgo = DATE_SUBTRACT(DATE_NOW(), 1, "hour")
FOR i IN 1..15
    INSERT {
        time: DATE_ADD(hourAgo, i, "minutes") // bug occurs even without this spacing apart
    } INTO my_collection
```

__Problem__:
The inserted documents will not be deleted (not even after 15 minutes).

__Expected result__:
The documents should be deleted by the TTL index within 30 seconds.

## Additional observations

- Deleting the persistent index causes the documents to be deleted during the next TTL tick.
- **If the collection contains 14 or less documents, they get deleted as expected during a TTL tick.** If 15 or more, they will not be deleted. This threshold might be hardware dependant. If you struggle to reproduce the bug, try creating more documents.

**Comment by Simran-B** [comment]
@Jirka-Mayer Can you please try version 3.7.3 and see if the problem is fixed?

**Comment by Jirka-Mayer** [comment]
@Simran-B Perfect, it works now. Thanks a lot!
