### ISSUE TITLE
AQL Replace statement with autoCreate option

### ISSUE THREAD

**Issue by kevinprotoss** [arangodb/arangodb#1280]
Hi,

Is it possible to automatically create a document during `update` or `replace` if this document is not found by given `_key` or given filter statement? I can not find this feature in the documentation.

If it's not possible so far, is it possible to implement this feature in the future, such as providing an option `autoCreate`, or something else

Best regards,
Kevin

**Comment by fceller** [comment]
Hi Kevin, can you read our minds? An upsert or findOrCreate is currently indeed missing. But Jan has just begun to implement it. It is expected to by available in 2.5.2.

**Comment by kevinprotoss** [comment]
That's great. Thanks for your answer.

**Comment by razvanphp** [comment]
+1

Today I just used this:
````javascript
if (repository.collection.exists(key)) {
    // byId + replace
} else {
    // new + save
}
````
but I was thinking that there is a race condition in this case, when it might fail. I hope the implementation takes care of this as an atomic operation.

**Comment by CoDEmanX** [comment]
So this would be a replacert(), like upsert() for inserts?

**Comment by jsteemann** [comment]
@razvanphp : the following code will work fine when there is no concurrent access to the collection:

```js
if (repository.collection.exists(key)) {
    // byId + replace
} else {
    // new + save
}
```
But as you pointed out it will be problematic when there are concurrent write accesses to the collection. The upsert method we're working on will be atomic. And it covers both update and replace. As you can also update with `{ }` in case the document exists, it also covers the findOrCreate idiom.

**Comment by razvanphp** [comment]
As a suggestion, `exists` method should also be included in the Repository.

It is strange that `byId` throws an exception when document is not found instead of just returning null, but at least in this case you could check beforehand without accessing the (private) collection of the repo directly, as in my previous example.

**Comment by pluma** [comment]
I've added the exists method in devel and 2.5, see 142182d.

**Comment by jsteemann** [comment]
I think the original issue is covered by the new `UPSERT` operation in 2.6. I have written a short introduction about this feature a while ago:
http://jsteemann.github.io/blog/2015/03/27/preview-of-the-upsert-command/

**Comment by jsteemann** [comment]
Closing as done.
