### ISSUE TITLE
Installation via Package Manager on CentOS 7 fails with 404 not found

### ISSUE THREAD

**Issue by m4ik7i** [arangodb/arangodb#12808]
## My Environment

* __ArangoDB Version__: 3.6.x | 3.7.x
* __Operating System__: CentOS 7.7.1908
* __Used Package__: SUSE or RedHat .rpm

## Component, Query & Data

__Affected feature__: Installation

## Steps to reproduce

1.  Download https://download.arangodb.com/arangodb37/RPM/arangodb.repo to `/etc/yum.repos.d/` while referencing https://www.arangodb.com/download-major/centos/
2.  Execute `yum -y install arangodb3-3.7.2`

__Problem__:

Installation fails with 404 not found.

https://download.arangodb.com/arangodb37/RPM/arangodb.repo
```
[arangodb]
name=ArangoDB Project
type=rpm-md
baseurl=https://download.arangodb.com/arangodb37-1/RPM
gpgcheck=1
gpgkey=https://download.arangodb.com/arangodb37-1/RPM/repodata/repomd.xml.key
enabled=1
```
https://download.arangodb.com/arangodb36/RPM/arangodb.repo
```
[arangodb]
name=ArangoDB Project
type=rpm-md
baseurl=https://download.arangodb.com/arangodb36-1/RPM
gpgcheck=1
gpgkey=https://download.arangodb.com/arangodb36-1/RPM/repodata/repomd.xml.key
enabled=1
```
https://download.arangodb.com/arangodb37-1/RPM and https://download.arangodb.com/arangodb36-1/RPM do not exist.

__Expected result__:

Installation will succeed.

**Comment by dothebart** [comment]
confirmed - arangodb.repo contains an incorrect URL.

**Comment by Simran-B** [comment]
@dothebart @KVS85 Any update?

**Comment by KVS85** [comment]
@Simran-B it was fixed.
