### ISSUE TITLE
JavaScript code needs access to env variables

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangodb#1281]
to follow up on http://stackoverflow.com/questions/29133229/access-environment-variables-from-foxx
@dothebart

**Comment by dothebart** [comment]
implemented with 7190fb879d826e69f7b4c34f24a2f4f8e448c648, 9ec243eef477f3c84be631dc702dadfabd4e9a69 and 185429767742791f21eb19f83638859adddf1d90

Will be visible in the node like fashion
process.env[]

**Comment by pekeler** [comment]
:)

**Comment by pekeler** [comment]
This has the 2.5 milestone but it doesn't work for me (using 2.5.3). Now I see the commits have the 2.6 tag. Please release this soon :)

**Comment by fceller** [comment]
A preview is available:

https://www.arangodb.com/download-preview/

Can you check, that it works as expected?

**Comment by pekeler** [comment]
@fceller works as expected using arangodb-2.6.0a2 on a CentOS 7 vm. Is there an ETA for 2.6 beta and final? => christian@pekeler.org if you want to be off the record.

**Comment by fceller** [comment]
We plan to release 2.6 next week - if all tests go well.

**Comment by pekeler** [comment]
@fceller is there a new ETA for 2.6?

**Comment by fceller** [comment]
We have fixed most of the bugs discovered. There is one open issue left, which are currently trying to fix.
