### ISSUE TITLE
Session storage in Foxx Services

### ISSUE THREAD

**Issue by thierry-github** [arangodb/arangodb#12828]
## My Environment

* __ArangoDB Version__3.5.0:        

__Problem__:

I.m trying tu se session storage in a foxx service but i still have an issue when i try to mount the service.
The issue is : 
 
[24213] at sessionMiddleware (c:\Program Files\ArangoDB3 3.5.0\usr\share\arangodb3\js\server\modules\@arangodb\foxx\sessions\index.js:42:3)

[24213] via AssertionError: No session storage specified

Followiing the documenation, Foxx Code is :

```const createRouter = require("@arangodb/foxx/router");
const joi = require('joi');

const sessionsMiddleware = require('@arangodb/foxx/sessions');

const router = createRouter();
const sessions = sessionsMiddleware({
    storage: module.context.collection('session'),
    transport: "cookie"
  });

  module.context.use(sessions);
  module.context.use(router)

router.post("auth", (req, res) => ...```


I have a document collection named "session" 

Is it something in doing wrong ?

**Comment by thierry-github** [comment]
Found the problem !

**Comment by dothebart** [comment]
Hi, 
for the shake of sanity Please share the answer to your question.

https://xkcd.com/979/
