### ISSUE TITLE
Geo WITHIN_RECTANGLE for nested lat/lng

### ISSUE THREAD

**Issue by amines713** [arangodb/arangodb#1282]
The WITHIN_RECTANGLE function only seems to work if the geo index is not on a nested attribute. When the lattitude and longitude are nested inside a "location" attribute, NEAR and WITHIN work, but WITHIN_RECTANGLE fails.

--- un-nested lattitude and longitude ---

JSH> db._create('geo1')
==> [ArangoCollection 239708486365, "geo1" (type document, status loaded)]

JSH> db.geo1.ensureGeoIndex('lat', 'lng')
==> { 
  "id" : "geo1/239716809437", 
  "type" : "geo2", 
  "unique" : false, 
  "sparse" : true, 
  "constraint" : false, 
  "ignoreNull" : true, 
  "fields" : [ 
    "lat", 
    "lng" 
  ], 
  "isNewlyCreated" : true, 
  "error" : false, 
  "code" : 201 
}

JSH> db.geo1.save({lat: 2, lng: 2})
==> { 
  "error" : false, 
  "_id" : "geo1/239721069277", 
  "_rev" : "239721069277", 
  "_key" : "239721069277" 
}

JSH> db.geo1.near(0, 0).toArray()
==> [ 
  { 
    "_id" : "geo1/239721069277", 
    "_key" : "239721069277", 
    "_rev" : "239721069277", 
    "lat" : 2, 
    "lng" : 2 
  } 
]

JSH> db.geo1.within(0, 0, 1000000).toArray()
==> [ 
  { 
    "_id" : "geo1/239721069277", 
    "_key" : "239721069277", 
    "_rev" : "239721069277", 
    "lat" : 2, 
    "lng" : 2 
  } 
]

JSH> db.geo1.withinRectangle(0, 0, 5, 5).toArray()
==> [ 
  { 
    "_id" : "geo1/239721069277", 
    "_key" : "239721069277", 
    "_rev" : "239721069277", 
    "lat" : 2, 
    "lng" : 2 
  } 
]

--- Nested lattitude and longitude ---

JSH> db._create('geo2')
==> [ArangoCollection 239727033053, "geo2" (type document, status loaded)]

JSH> db.geo2.ensureGeoIndex('location.lat', 'location.lng')
==> { 
  "id" : "geo2/239735945949", 
  "type" : "geo2", 
  "unique" : false, 
  "sparse" : true, 
  "constraint" : false, 
  "ignoreNull" : true, 
  "fields" : [ 
    "location.lat", 
    "location.lng" 
  ], 
  "isNewlyCreated" : true, 
  "error" : false, 
  "code" : 201 
}

JSH> db.geo2.save({location: {lat: 2, lng: 2}})
==> { 
  "error" : false, 
  "_id" : "geo2/239733914333", 
  "_rev" : "239733914333", 
  "_key" : "239733914333" 
}

JSH> db.geo2.near(0, 0).toArray()
==> [ 
  { 
    "_id" : "geo2/239733914333", 
    "_key" : "239733914333", 
    "_rev" : "239733914333", 
    "location" : { 
      "lat" : 2, 
      "lng" : 2 
    } 
  } 
]

JSH> db.geo2.within(0, 0, 1000000).toArray()
==> [ 
  { 
    "_id" : "geo2/239733914333", 
    "_key" : "239733914333", 
    "_rev" : "239733914333", 
    "location" : { 
      "lat" : 2, 
      "lng" : 2 
    } 
  } 
]

JSH> db.geo2.withinRectangle(0, 0, 5, 5).toArray()
==> [ ]

**Comment by jsteemann** [comment]
Indeed, it didn't seem to work with nested attributes.
Should be fixed now in 2.4.7, 2.5.2 and devel.
