### ISSUE TITLE
Question: Determine presence of additional query results using LIMIT but without fullCount?

### ISSUE THREAD

**Issue by dvstans** [arangodb/arangodb#12829]
For an AQL query with a LIMIT, is there a simple way to determine if additional results are present beyond the limit but without using the full count option? The use case is for running complex (expensive) queries on very large collections/views where full counting would be too costly - but knowing additional results are available would permit incremental paging. I can work around this by simply specify a limit +1 and truncating the results myself, but I thought I'd ask if there was a cleaner method. Thanks!

**Comment by goedderz** [comment]
Adding 1 to the limit is the right thing to do in that case.

**Comment by maxkernbach** [comment]
Hi @dvstans,

Can we consider this issue resolved?

**Comment by dvstans** [comment]
Yes, this is resolved. Thanks!
