### ISSUE TITLE
How to get the nodes and edges of the graph using AQL Without start from the root.

### ISSUE THREAD

**Issue by Wathsara** [arangodb/arangodb#12836]
Assume I have graph A→B, B→C, C→D, D->E, E->F , G->H, D->F and D->G

Now I wrote the below query to my graph to get the paths for the max depth 3 starts from the A.
`FOR v,e,p IN 1..3 ANY 'A' GRAPH 'graph' RETURN distinct p`
This will return `A→B, B→C, C→D`,

Now I have a usecase of getting the vertices and edges (or paths) from depth 3 to 4 of above graph start from the vertex D to get the result `D->E, D->F , D->G`

Is there a possible way of writing a query for this without getting all the paths again from 1..4

**Comment by goedderz** [comment]
Hi @Wathsara!

I'm not totally sure I understand what you're trying to achieve.

For one thing, from what I understand, it sounds like you're looking for the `OPTION { uniqueVertices: "global", bfs: true }`, and want to omit the `DISTINCT`. See https://www.arangodb.com/docs/stable/aql/graphs-traversals.html for details.

Secondly, I do not quite get this:

> Is there a possible way of writing a query for this without getting all the paths again from 1..4

I assume passing `3..4` as depth does not get you the desired results. Can you explain in more detail what result you need?

On a side note, it would make more sense to ask such a question on either StackOverflow or in our community slack, the Github issues are for bug reports..

Best,

Tobias

**Comment by Wathsara** [comment]
@goedderz Thank you for the reply and let me explain further with the diagram below

![Arango-Issue](https://user-images.githubusercontent.com/31571237/95807778-9be10380-0d28-11eb-9df2-15daa2c8ffbd.png)


For the Above graph If I write the query `FOR v,e,p IN 1..3 ANY 'A' GRAPH 'graph' RETURN distinct p` (**depth is 3, I started from A**)
This will return `A→B, B→C, B->I, I>J, C→D`

Now my usecase is to get the vertices and edges (or paths) from depth **3 to 4** of above graph start from the vertex D to get the result D->E, D->F , D->G
If I pass like **3..4** then it will return the `D->H, D->E, D->G and J->K` and **I dont want this J->k path to be retuned**

**Comment by goedderz** [comment]
@Wathsara In this example, you could either start an OUTBOUND traversal from D, instead of from A. Or you could add a `FILTER p.vertices[3]._key == 'D'` (or something similar) right after the traversal. Though the latter will internally still need to iterate all the other paths, so the first variant will be faster.

**Comment by Wathsara** [comment]
@goedderz Thank you and it warks for me.

**Comment by Chaitanyasrini** [comment]
bokachoda query kahan hai be? land bsdwala
