### ISSUE TITLE
Unique Hash Index can't have null field value?

### ISSUE THREAD

**Issue by terrybleger** [arangodb/arangodb#1283]
I've got [ArangoError 1210: cannot create document, unique constraint violated] after I upgraded to v2.5.1. I've never had this problem before with null value.

So my question is, is v2.4.4 would be the last version that doesn't have that behaviour?
If yes, then since I can't upgrade to higher version this would be goodbye for me to arangodb.
if no, what other options that I can do?

**Comment by terrybleger** [comment]
I just read the change log. So, in order to allow null values the index must be set as sparse now? I assume that this should be the fix.

**Comment by jsteemann** [comment]
Exactly. The index should be declared sparse, otherwise the `null` value will count as a regular value and can occur only once.
