### ISSUE TITLE
Usage of a `LET` variable in a `FILTER` prevent usage of underlying indexes

### ISSUE THREAD

**Issue by soualid** [arangodb/arangodb#12845]
Hello,

Using latest 3.5.x and 3.4.x series, a (yet constant) `LET` variable in a `FILTER` clause prevent usage of underlying indexes by the engine.

Ie: 

```
LET test = document("test/123")
return LENGTH(FOR c IN demo FILTER c.reference == test._key RETURN 1)
```

Will not use an index on `reference` in the collection `demo` while the following query will use the same index:

```
return LENGTH(FOR c IN demo FILTER c.reference == '123' RETURN 1)
```

I guess the engine discard the index because the `test` variable could change (even if it doesn't), is there a way to declare this variable constant to let the engine keep benefit from the index on the `reference` field of the `demo` collection in this case?

I can provide a SSCCE if needed.

Many thanks in advance.

**Comment by goedderz** [comment]
Hi @soualid, thanks for the report.

Note that 3.4 is EOL: https://www.arangodb.com/eol-notice/.

I cannot reproduce your problem with 3.5.6. Which exact version are you using?

```
Query String (86 chars, cacheable: false):
 LET doc = DOCUMENT('col/139')
 RETURN LENGTH(FOR d IN col FILTER d.i == doc.i RETURN d)

Execution plan:
 Id   NodeType          Est.   Comment
  1   SingletonNode        1   * ROOT
  2   CalculationNode      1     - LET doc = DOCUMENT("col/139")   /* simple expression */
  8   SubqueryNode         1     - LET #2 = ...   /* subquery */
  3   SingletonNode        1       * ROOT
 11   CalculationNode      1         - LET #8 = true   /* json expression */   /* const assignment */
 12   IndexNode            1         - FOR d IN col   /* persistent index scan, scan only */
  7   ReturnNode           1           - RETURN #8
  9   CalculationNode      1     - LET #6 = LENGTH(#2)   /* simple expression */
 10   ReturnNode           1     - RETURN #6

Indexes used:
 By   Name                      Type         Collection   Unique   Sparse   Selectivity   Fields    Ranges
 12   idx_1680424634026033152   persistent   col          false    false       100.00 %   [ `i` ]   (d.`i` == doc.`i`)
```

Best,

Tobias

**Comment by soualid** [comment]
Thanks Tobias, I tested this behaviour under 3.5.5-1.

I will check under 3.5.6 right now and give feedback here afterward.

**Comment by soualid** [comment]
I am reproducing the issue under 3.5.6, I create a SSCCE.

**Comment by soualid** [comment]
Here it is, but it doesn't reproduce the issue. I think it is related to indexes migration from older version of the engine, I'm checking this out, the good news is that a freshly created collection and indexes handle correctly this use case.

```
db._useDatabase('_system')
db._dropDatabase('repro')
db._createDatabase('repro')
db._useDatabase('repro')
db._drop('reproCollection')
db._createDocumentCollection('reproCollection')
db.reproCollection.ensureIndex({fields:['reference.id'], type: 'hash', unique: false})
db.reproCollection.insert([
  {
    "reference": {"id": 123}
  },
  {
    "reference": {"id": 123}
  },
  {
    "reference": {"id": 456}
  }
])
db._drop('reproAnotherCollection')
db._createDocumentCollection('reproAnotherCollection')
db.reproCollection.insert([{
	_key: "123"
}])
db._explain(`LET doc = DOCUMENT('reproAnotherCollection/123')
FOR r IN reproCollection FILTER r.reference.id == doc._key
RETURN r`)
```

Properly use the index: 

```
Query String (116 chars, cacheable: false):
 LET doc = DOCUMENT('reproAnotherCollection/123')
 FOR r IN reproCollection FILTER r.reference.id == doc._key
 RETURN r

Execution plan:
 Id   NodeType          Est.   Comment
  1   SingletonNode        1   * ROOT
  2   CalculationNode      1     - LET doc = DOCUMENT("reproAnotherCollection/123")   /* simple expression */
  7   IndexNode            1     - FOR r IN reproCollection   /* hash index scan */
  6   ReturnNode           1       - RETURN r

Indexes used:
 By   Name                      Type   Collection        Unique   Sparse   Selectivity   Fields               Ranges
  7   idx_1680433618798772224   hash   reproCollection   false    false        75.00 %   [ `reference.id` ]   (r.`reference`.`id` == doc.`_key`)

Functions used:
 Name       Deterministic   Cacheable   Uses V8
 DOCUMENT   false           false       false  

Optimization rules applied:
 Id   RuleName
  1   use-indexes
  2   remove-filter-covered-by-index
  3   remove-unnecessary-calculations-2
```

**Comment by soualid** [comment]
I can confirm that recreated the index solve the issue, it was migrated from previous versions of ArangoDB and was still a `hash` index and not a `persistent` one.

Maybe the `--database.auto-upgrade` procedure should take care of this and force index migration / recreation?

**Comment by dothebart** [comment]
Hi, 
in the rocksdb storage engine `hash`/`skiplist` are only aliases for `persistent`; Support for the mmfiles-Storage-engine has been dropped with ArangoDB 3.7

**Comment by soualid** [comment]
Hi @dothebart I have no clue on how this happened on this database (even if we do have changed the storage engine from mmfiles to rocksdb when migrating from 2.x to 3.x years ago).

Maybe the index was corrupted somehow (but I don't explain why it was used when not using a `LET` variable).

Anyway, recreating the index solved the issue, which is now always a pleasure now that they can be created in the background. 😄
