### ISSUE TITLE
syntax error, unexpected $undefined near '@_to RETURN obj

### ISSUE THREAD

**Issue by diefans** [arangodb/arangodb#1285]
I don't know if this is intended, but when a bind var name starts with an underscore ``_`` in a cursor query, I get the following error:

```
{
    "code": 400,
    "error": true,
    "errorMessage": "syntax error, unexpected $undefined near '@_to RETURN obj' at position 1:45 (while parsing)",
    "errorNum": 1501
}
```

my query looks like this:
```
curl http://localhost:8529/_db/default/_api/cursor -d '{"query": "FOR obj IN @@collection FILTER obj.`_to` == @_to RETURN obj", "bindVars": {"@collection": "describes", "_to": "SemanticRoot/23122170121"}}'
```

**Comment by jsteemann** [comment]
Looks like the bind parameter name starting with an underscore (`_`) is causing the parse error.
The flex rule for matching bind parameters currently is:
```
@@?[a-zA-Z0-9][a-zA-Z0-9_]*
```

Changing the parameter name from `@_to` to `@to` should thus work.
I'll look into whether the rule can be adjusted so leading underscores will work, too.

**Comment by jsteemann** [comment]
Changed in 2.5.2 and devel.

**Comment by diefans** [comment]
wow! I am very impressed...
