### ISSUE TITLE
Potential bug in UPDATE AQL query

### ISSUE THREAD

**Issue by inzanez** [arangodb/arangodb#12858]
## My Environment

* __ArangoDB Version__:        Docker, 3.7.2
* __Storage Engine__:            RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:  Kubernetes

## Component, Query & Data

__Affected feature__:
AQL query

## Steps to reproduce

```
1. Create a collection 'persons'
2. INSERT { _key: "1", first: "Ned", last: "Stark", full: "" } INTO persons
3. INSERT { _key: "2", first: "Jaime", last: "Lannister", full: "" } INTO persons
4. FOR p in persons UPDATE { _key: "1" } WITH { full: "empty" } IN persons
5. FOR p in persons UPDATE { _key: "2" } WITH { full: CONCAT(p.first, " ", p.last) } in persons
```

From the documentation, I would expect that the property 'full' of the persons entry with _key "2" will be "Jaime Lannister". But it's actually "Ned Stark". So it seems that ArangoDB is caching something from the previous query and using it on the next. Maybe my caching theory gets more clear when looking at this:

```
1. Create a collection called groups
2. INSERT { _key: "1", name: "Admins", users: ["u1","u2","u3","u4"] } INTO groups
3. INSERT { _key: "2", name: "Users", users: ["u1"] } INTO groups
4. FOR g in groups
5. UPDATE { _key: "1" } WITH { users: REMOVE_VALUE(g.users, "u4") } IN groups

```

Reading the documentation, I would expect to have the group "Admins" contain "u1", "u2", "u3" after these queries. But it will just contain "u1". So it seems that the "REMOVE_VALUE" is taking "g.users" from the previous command (in 3.) as a baseline, removing "u4" from ["u1"], which will obviously result in only having ["u1"] as the final result.

The only way around that is to use a FILTER statement before the UPDATE in the FOR loop. This is fine, but I think it's not the behavior I would expect from reading the documentation, as the samples to update a specific document do not make use of the FILTER statement.

**Comment by goedderz** [comment]
Hi @inzanez!

The problem is the following:

```
FOR p in persons
UPDATE { _key: "2" } WITH { full: CONCAT(p.first, " ", p.last) } in persons
```
This query means, iterate over all persons, and every time update the same one (matching `{_key: "2"}`).

If you want to update a single document, either write a stand-alone `UPDATE` statement. Or filter the appropriate document in the FOR loop like

```
FOR p IN persons
FILTER p._key == "2"
UPDATE p WITH { full: CONCAT(p.first, " ", p.last) } IN persons
```
.

The examples you're probably referring to in the documentation update *all* documents, not just one, e.g.:
```
FOR u IN users
  UPDATE { name: CONCAT(u.firstName, " ", u.lastName) } IN users
```

HTH!

Best,

Tobias

**Comment by inzanez** [comment]
@goedderz 
Oh, I see. That's a misunderstanding on my end then, thinking that inserting the key would be acting as a filter. Many thanks for clarification! So updating a single entity using some of it's own values always requires FOR && FILTER.
