### ISSUE TITLE
How to get the depth of the vertice in graph traversal.

### ISSUE THREAD

**Issue by Wathsara** [arangodb/arangodb#12860]
I have a use case of **getting the depth(level) of the vertex(node)** when running AQL query for graph traversal

![Graph](https://user-images.githubusercontent.com/31571237/96016237-2418f300-0e66-11eb-9771-459b37cf1d32.png)

For the above graph, I write a graph traversal query to return the vertices
`FOR v,e,p IN 1..3 ANY 'A' GRAPH 'graph' RETURN distinct v`

I want to return the vertices tho the depth

**Example**
```
[
  {
    "_key": "A",
    "depth": 0
  },
  {
     "_key": "B",
    "depth": 1
  },
  {
     "_key": "C",
    "depth": 2
  },
 {
     "_key": "I",
    "depth": 2
  },
  {
     "_key": "D",
    "depth": 3
  },
  {
     "_key": "J",
    "depth": 3
  },
]
```
**Is there a way to get the depth or the level of th vetex using the AQL?.**

**Comment by goedderz** [comment]
Hi @Wathsara!

As I already [mentioned in your last issue](https://github.com/arangodb/arangodb/issues/12836#issuecomment-707043025), please ask questions on StackOverflow or in our [Slack Community](https://slack.arangodb.com/).

You can get the current depth e.g. with `LENGTH(p.vertices)`.

Best,

Tobias
