### ISSUE TITLE
arangod.log: communication error: 'connection was locally canceled'

### ISSUE THREAD

**Issue by mathsyouth** [arangodb/arangodb#12876]
## My Environment

* __ArangoDB Version__:        3.6.7-1
* __Storage Engine__:             RocksDB
* __Deployment Mode__:        Cluster
* __Deployment Strategy__:   ArangoDB Starter
* __Configuration__:              3 machines
* __Infrastructure__:               own
* __Operating System__:        CentOS 7.3
* __Total RAM in your machine__:        64Gb each
* __Disks in use__:        HDD

## Component, Query & Data

__Affected feature__:
slow query

__AQL query (if applicable)__:

__AQL explain and/or profile (if applicable)__:

__Problem__:

If I run a long time AQL query which will take time more than 1 hour,  then there is an error message in one of coordinator's arangod.log:

```
[21741] ERROR [abcdf] {communication} communication error: 'Connection was locally canceled'
[21741] WARNING [8d035] {aql} During AQL query shutdown: Query ID 2543 not found server: PRMR-21448c66-85a9-471e-b706-3799a3a9afcf
[21741] WARNING [8bcee] {queries} slow query: '......', bind_vars: {....}, database: test, user: test,
 took: 3630.278753s
```

There is also another error  message in one of dbserver's arangod.log:

```
[21720] ERROR [baef6] {aql} Timeout waiting for query 14279
[21720] INFO [88857] {cluster} Server CRDN-55575f8f6-da43-40cc-28c4-dadfa134vff rebooted, aborting its old jobs now.
[21720] ERROR [abcdf] {communication} communication error: 'Connection reset by perr'
[21720] INFO [88857] {cluster} Server CRDN-55575f8f6-da43-40cc-28c4-dadfa134vff rebooted, aborting its old jobs now.
[21720] WARNINg [8d035] {aql} During AQL query shutdown: Query ID 10021478 not found on server: CRDN-55575f8f6-da43-40cc-28c4-dadfa134vff rebooted
```

By the way, how could I understand the log for arangodb services? For example, what does the string  containing 5 chars in [] mean? How could I recognize the id for each service?  

__Expected result__:

A lone time AQL query could be executed successfully.

**Comment by dothebart** [comment]
`[8d035] ` is used to isolate the place where the log line was emitted - https://github.com/arangodb/arangodb/blob/3.6-no-scheduler-fix/arangod/Aql/RemoteExecutor.cpp#L376 in this case.

**Comment by Simran-B** [comment]
@mathsyouth is it possible that the Coordinator runs out of memory while during query execution? Can you check whether memory consumption increases up to the installed amount of memory before it reboots?

**Comment by mathsyouth** [comment]
@Simran-B How could I check whether memory consumption increases up to the installed amount of memory before it reboots?

**Comment by Simran-B** [comment]
The simplest way would probably to run `top` in a shell on the Coordinator and check the memory usage per process.

**Comment by Simran-B** [comment]
@mathsyouth Did you have a chance to check the RAM usage?

**Comment by mathsyouth** [comment]
@Simran-B I have logged the RAM usage every 3 seconds and verified that you are right. When the error happened, the RAM usage is about 99%.

**Comment by dothebart** [comment]
Hi, 
You could revisit your queries using `explain` and `profile` to see the number of documents that are transfered up to the coordinator, in order to find measures to apply filters that can be pushed out to the DB-Servers. 
Do you have any queries in special that cause the situation? or is it just that there is more application load that the system can maintain?
