### ISSUE TITLE
Error message: 'Unable to connect'

### ISSUE THREAD

**Issue by wanghao14** [arangodb/arangodb#12871]
## My Environment

* __ArangoDB Version__:        3.7.2
* __Storage Engine__:             auto 
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start in Docker
* __Configuration__:               cluster setup details, notable server settings, etc
* __Infrastructure__:               own
* __Operating System__:        Ubuntu 18.04
* __Total RAM in your machine__:       32Gb
* __Disks in use__:        SSD
* __Used Package__:              Debian or Ubuntu .deb

## Steps to reproduce

1.  Install arangodb3.7.2 under docker
2. start arangodb and the error occurs

__Problem__:
type "arangosh" in terminal while the following error occurs:
```
Command-line history will be persisted when the shell is exited. You can use `--console.history false` to turn this off
Could not connect to endpoint 'tcp://127.0.0.1:8529', database: '_system', username: 'root'
Error message: 'Unable to connect'
```

__Expected result__:

**Comment by dothebart** [comment]
Hi, 
you need to specify the matching `--server.endpoint` `tcp://IP:port` ; Docker will give the container an IP. 
in `docker ps` you will see the `ports` If you've got `0.0.0.0:8529->8529/tcp` your command should work.

**Comment by wanghao14** [comment]
@dothebart Thanks for your reply! I have used "arangosh --server.endpoint tcp://0.0.0.0:9000"(the port is 9000 set for the docker) to start while a new error occurs:
`Error message: 'not authorized to execute this request'`

**Comment by dothebart** [comment]
`0.0.0.0` is the broadcast bind-ip - you can't talk to it. 
It tells the server to bind all IPs that are in range. However, inside the docker container there may be only different. 
Please try the pupblic IP of your machine.

**Comment by wanghao14** [comment]
@dothebart For the sake of security, our server does not open public IP. So I created an new container while binding the port as you suggest: 
![image](https://user-images.githubusercontent.com/31157833/96443002-898e2a80-123e-11eb-9256-fc331dc2ece7.png)

After installing and starting arangodb, the same error occurs again:
```
Could not connect to endpoint 'tcp://127.0.0.1:8529', database: '_system', username: 'root'
Error message: 'Unable to connect'
```

**Comment by dothebart** [comment]
please try the public IP anyways. 
Most probably you need to use docker networks in order for the service not being able to be seen from the outside.

**Comment by Simran-B** [comment]
@wanghao14 have you had a chance to try dothebart's suggestion?
