### ISSUE TITLE
Outdated Joi version included

### ISSUE THREAD

**Issue by razvanphp** [arangodb/arangodb#1288]
Hey,

Today I came across this bug, hapijs/joi#518, that is fixed in Joi version 5.0.2, but not included with the latest ArangoDB (that includes Joi 4.9.0). 

The same test script throws the exception:
````javascript
var Joi = require('joi');
Joi.validate('2014-12-02T11:00:20.000Z', Joi.date().iso().required());
````

**Comment by pluma** [comment]
The devel branch (which 2.6 will be based on) is at `6.0.8` at the moment (as of 1d5bc53 via #1266). As `6.x` and `5.x` are both major version updates, I don't think it's a good idea to update joi in a patch release for ArangoDB 2.4 or 2.5.

If you need a different version, you can try installing your own version of joi locally in your Foxx app (just `npm install joi` inside your app folder and make sure to include the `node_modules` folder in the app bundle). I'm using 6.0.x in a Foxx app myself and haven't run into any compatibility problems.
