### ISSUE TITLE
Foxx models from DB contain ShapedJSON artefact

### ISSUE THREAD

**Issue by pluma** [arangodb/arangodb#1289]
See the discussion in #1284. Apparently `_.clone` is a bit too eager and copies inherited methods as well.

**Comment by pluma** [comment]
@fceller are we planning another patch release for 2.4? I've added the fix to the 2.4.8 changelog in the 2.4 branch, but I'm not sure whether a 2.4.8 is planned at the moment.

I also added the fix to 2.5 and devel with the 2.5.2 target.

**Comment by razvanphp** [comment]
Thank you for the fast fix.

What I don't understand, is why this happens only sometimes, and only for some collection. Also after one save with this "attribute" removed, that particular document is ok for all future requests.

**Comment by pluma** [comment]
No idea why it only happens for *some* collections. I was able to replicate the bug passing a raw document directly to the Foxx.Model constructor. The culprit seems to be underscore's `clone` method, which for some reason copied the prototype's `_PRINT` method.

The code triggering this bug only runs if you pass a raw document directly to the constructor (as Foxx.Repository do) iff the model has no schema. Maybe the difference between the collections is that you only have schemas defined for some of the models and not all of them?

**Comment by pluma** [comment]
I've found an even simpler fix: make `ShapedJson#_PRINT` non-enumerable so `_.clone` (and its friends) don't see it. I've updated the three branches accordingly.

**Comment by razvanphp** [comment]
Very strange, I tested it again, that specific repository has no model, so no schema. If I create a new document inside this collection and try to replace it, the _PRINT function is not there. The same with a document that has it, I can delete that property before replace, and then that document will not trigger the error again. The same if I save the document once in the web interface.

I also tested your new fix with non-enumerable and I can confirm the bug is gone.

**Comment by pluma** [comment]
Yes, the problem only occurs if the model is created by `_.clone`'ing or `_.extend`ing a ShapedJson object. Those objects are intended to be an implementation detail and only exist for performance reasons. Also, as @jsteemann pointed out to me, not all documents loaded from the database are returned as ShapedJson objects (e.g. if you read a document you just inserted, it may come back as a regular object instead). But as I said, it's an implementation detail that shouldn't be noticeable in the first place.
