### ISSUE TITLE
remote 'foxx-manager upgrade app_path_or_zip_file' fails

### ISSUE THREAD

**Issue by agomezalvic** [arangodb/arangodb#1292]
Hello,

Running windows 2.5.0 arangodb server (Windows 7 Professional 64 bits).
Client computer is Windows 8.1 PRO 64 bits, with ArangoDb 2.5.1 64 bits (although testing with same version of server in client gives the same error)
Remote arangodb has authetication enabled, both on _system and actual database used to deploy foxx application.

When trying to upgrade an already installed foxx application on remote server it fails with error "<path> must be a valid directory name".

* actual parameters of the cmd are:
`cmd> foxx-manager --server.endpoint tcp://192.168.192.42:8529 --server.database mydb --server.password mypwd upgrade %TEMP%\updated.zip /myappmountpoint`

* uninstalling foxx app from the command line is ok:
`cmd> foxx-manager --server.endpoint tcp://192.168.192.42:8529 --server.database mydb --server.password mypwd uninstall /myappmountpoint`

* re-installing it with same zip file is also ok:
`cmd> foxx-manager --server.endpoint tcp://192.168.192.42:8529 --server.database mydb --server.password mypwd install %TEMP%\updated.zip /myappmountpoint`

We have checked temp directories in both server and client machine, assuring everybody has permissions to downloads, uploads, app and zip folders, but not sure if that was the issue.

any hints?
thanks

**Comment by dothebart** [comment]
Can you try to have a look at the logfile of arangod so we can find out whether this is in arangosh/foxmanager or the server itself?
Most probably you should also see this error in the windows eventlog (if)

**Comment by agomezalvic** [comment]
Hello dothebart,

arangod logfile show nothing (at least i cant find anything that points to a problem on the server).
also windows eventlog show nothing about this.
logfile is being generated with default options.

I have tried to inspect tcp data sent/received comparing install vs upgrade, and it seems that foxmanager does not send the zipped file to the server (install does), but can not asure this 100% since i'm too new to arango ;).

(with arangosh we get same result as with foxxmanager)

**Comment by dothebart** [comment]
ah, 2.5.0 on the server, 2.5.1 on the client - misread that. 
2.5.1 has lots of windows polishing - the eventlog too.
if you copy the zip file to the current directory where you call arangosh - does it fix the issue?

**Comment by agomezalvic** [comment]
i'm now upgrading server to 2.5.1
will report in some minutes, just see

**Comment by agomezalvic** [comment]
sadly after upgrading server to 2.5.1 problem remains...
now:
- client 2.5.1
- server 2.5.1
foxxmanager install local_zip_o_folder /mountpoint   is ok
foxxmanager upgrade local_zip_o_folder /mountpoint   fails

have re-checked arangod.log (now with 2.5.1 server) and windows eventlog, nothing there

**Comment by dothebart** [comment]
Ok, problem confirmed & reproduced; its a windows only problem that somehow didn't occur on our windows CI; fix will be part of the next release 2.5.2

**Comment by agomezalvic** [comment]
thankyou !!!

**Comment by agomezalvic** [comment]
any news about this, did it got resolved with 2.5.2?
did see nothing in 2.5.2 changelog about this (can not upgrade to 2.5.2 at the moment, at least not before a few days).
thanks in advance

**Comment by dothebart** [comment]
The fix is part of 2.5.3

**Comment by agomezalvic** [comment]
Have just upgraded my system to 2.5.3 (Windows x64 binaries, both client PC and server PC) and the problem persists.
I guess that the problem fixed is not really the one reported.
Can this be re-opened?

To get in touch, the problem is that we can not upgrade (via foxx-manager cmd line) a foxx application on our development ArangoDb server from neither of our personal development computers.

We try to do that with the following command line:
`cmd> foxx-manager --server.endpoint tcp://192.168.192.42:8529 --server.database mydb --server.password mypwd upgrade updated.zip /myappmountpoint`

Thanks in advance, Arango is awesome!!!

**Comment by dothebart** [comment]
Ok, the error message is not helpfull at all. 
Running the server in console mode with debug log gave the real failure; adding the path to the zip file fixed the incident.
running it with ``` .\updated.zip ``` instead of ```updated.zip``` fixes the incident for me.

**Comment by agomezalvic** [comment]
Hello,

I have tried using `.\updated.zip` as stated, but had the same error.

Even used full path (although local to foxx-manager binary computer), and i'm not sure what do you mean when talking about `path has to be relative to the running arangod server`, `updated.zip` and `.\updated.zip` are both relative, on the other hand, how can i tell from client computer what the full path will be on remote computer (arangod server)?

I'm a bit confused, `install` command gives no error at all with exactly the same parameters.

Sorry if i can not able to describe all the details you would need.

What can i do to help you in finding the real problem? I would do whatever you need.

Thanks

**Comment by mchacki** [comment]
Hi,

i think we first have to clarify some things ;)

First: the install command of foxx manager is designed to work with absolute or relative paths on the machine you execute it. You do not need to know anything about the server, which actually could be running on a different OS). However we often use the servers-console internally which lead to the confusion with @dothebart comment ;)

Second: It can only recognize paths starting with one of the following in windows (C could be any drive as well):
```
C:\
.\
\
..\
```

This means the correct command for you should be

`cmd> foxx-manager --server.endpoint tcp://192.168.192.42:8529 --server.database mydb --server.password mypwd upgrade .\updated.zip /myappmountpoint`

However there is a bug in the upgrade procedure which actually did not handle local files...
Sorry for the inconvenience i will fix it in a second.

**Comment by mchacki** [comment]
Should now be fixed in 2.5 and level and will be included in the next releases.

**Comment by dothebart** [comment]
On 05/12/15 02:29, Michael Hackstein wrote:
>
> Should now be fixed in 2.5 and level and will be included in the next 
> releases.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/arangodb/arangodb/issues/1292#issuecomment-101081155>.
>
Computa sagt naain:

willi@bruecklinux:~/src/devel$ git checkout 
js/client/modules/org/arangodb/foxx/manager.js
willi@bruecklinux:~/src/devel$ git pull --all
willi@bruecklinux:~/src/devel$ bin/foxx-manager  --server.database 
_system upgrade v1.2.1.zip /blarg
<path> must be a valid directory name



POST /_db/_system/_admin/foxx/upgrade HTTP/1.1.
Host: 127.0.0.1.
Connection: Keep-Alive.
User-Agent: ArangoDB.
Accept-Encoding: deflate.
Authorization: Basic cm9vdDo=.
Content-Length: 72.
.
{"appInfo":"v1.2.1.zip","mount":"/blarg","options":{"configuration":{}}}
#
T 127.0.0.1:8529 -> 127.0.0.1:35388 [AP]
HTTP/1.1 400 Bad Request.
Server: ArangoDB.
Connection: Keep-Alive.
Content-Type: application/json; charset=utf-8.
Content-Length: 94.
.
{"error":true,"code":400,"errorNum":10,"errorMessage":"<path> must be a 
valid directory name"}

**Comment by dothebart** [comment]
Still not resolved; reproducible on linux. The zip is not uploaded to the server, but a path passed on from foxx-manager to arangod.

**Comment by dothebart** [comment]
#eeb7d82e625b1ecd344bfa24a733fa4b2a99859f finally resolves this issue for me; @agomezalvic  can you try to replace your js/client/modules/org/arangodb/foxx/manager.js by https://raw.githubusercontent.com/arangodb/arangodb/2.5/js/client/modules/org/arangodb/foxx/manager.js ?

**Comment by agomezalvic** [comment]
Hi,

I'll try it a bit later (now have some meetings...).
Should i replace client computer only, only server one or both?

thanks.

**Comment by dothebart** [comment]
its for the foxx manager client; so on which ever computer you run it, replace that file.

**Comment by agomezalvic** [comment]
Perfect @dothebart
I finllay could test it from client computer and upgrade completed successfully.

thanks!!!

**Comment by dothebart** [comment]
fixed with 2.5.5
