### ISSUE TITLE
arangoimport ignoring --translate in large tsv file

### ISSUE THREAD

**Issue by puppriss** [arangodb/arangodb#12938]
## My Environment

* __ArangoDB Version__:        3.5.3
* __Operating System__:        Windows 10
* __Total RAM in your machine__:        16Gb

## Component, Query & Data

__Affected feature__:
arangoimport

__Dataset__:
available for download from http://www.catalogueoflife.org/DCA_Export/index.php
I downloaded complete data for plants (top level group=Plantae)
The main file is taxa.txt, a tsv file with 1.2M rows
I want the 1st column, taxonID, to be used as the document _key

__Size of your Dataset on disk__:
tsv file is 430MB

## Steps to reproduce

import the file...
arangoimport --file "taxa.txt" --translate "taxonID=_key" --server.database species --collection col_taxa --create-collection --type tsv

__Problem__:
The import appears to work fine and in good time, however, the --translate option is ignored with no messages displayed. When I view the collection, taxonID is a normal attribute and _key is auto-generated. I tried renaming the header column to taxonid to avoid case issues and even _key, but neither worked. 

**IMPORTANT NOTE**, it *DID* work as expected when I split out the first 300 rows into a separate file. 

So, why does it not work on the larger file?

__Expected result__:
I expect taxonID to be used as the _key, or to display a meaningful warning/error message if it's not possible

**Comment by Simran-B** [comment]
I only tried this with the 3.7.3 Docker image, but I think I see the problem: taxa.txt has a byte order mark (BOM), which ArangoDB doesn't understand:

`EF BB BF 74 61 78 6F 6E 49 44 ï»¿taxonID`

It is interpreted as part of the first column name, which happens to be `taxonID`. The attribute ends up as `\ufefftaxonID`, and thus `--translate` doesn't match it.

Please remove the first three bytes from the source file. I would recommend a hex editor (e.g. HxD) but as this is text data it should also be okay to use Visual Studio Code for instance to re-save it without BOM. Then retry the import and let me know if it helped.

**Comment by puppriss** [comment]
Ah yes, that's the issue. That's why it worked when I created a smaller separate file because it was saved with different encoding. FYI, I was using Notepad++ but I think HxD could be useful in future.

Many thanks for the help - much appreciated
