### ISSUE TITLE
Frequent disconnect and Crash

### ISSUE THREAD

**Issue by dagarwal82** [arangodb/arangodb#1293]
![1](https://cloud.githubusercontent.com/assets/1272570/6945440/bddddd4c-d867-11e4-85b1-9410f3c7cf88.png)
![2](https://cloud.githubusercontent.com/assets/1272570/6945441/bddde3e6-d867-11e4-90ec-32843377ecb4.png)

I have been testing large number data on arangodb. I am seeing a frequent disconnect while making ssl connections and finally getting the arangodb application crash.

1) I attached 2 images. You can see it's trying to establish the ssl connection in 1.png . It succeeds only few times.
2) In 2.png after the last message the app got crashed.
3) I also get consistent msg "Shutdown handler called, but no handler is known for task"
4) Sometimes before crash I get this : "2015-03-31T20:26:46Z [4344] ERROR Unhandled exception: -1073741819 - will crash now.  Even though I am running it on a 8GB machine.

**Comment by fceller** [comment]
You are on a Windows machine? Which version of Windows and ArangoDB are you using?

**Comment by dagarwal82** [comment]
Windows Server 2012 R2
8GB RAM
64Bit
2 Core CPU

ArangoDB -> arango 2.5.1

**Comment by dagarwal82** [comment]
Hey fceller,

Is there any update on this.

**Comment by fceller** [comment]
My colleague is currently trying to setup a test environment in Azure.

**Comment by dagarwal82** [comment]
I did a fresh installation and I don't see the ssl disconnect problem anymore. Also, the most of the crashes are happening because of the high memory utilization. Most of the memory was taken by foxxlog, it had millions of entry. Once I started truncating the foxxlog (db._foxxlog.truncate()) memory utilization is decreased dramatically.

**Comment by fceller** [comment]
Strange, what kind of messages are logged in this collection? Millions seems way too many. Are these messages from your Foxx app?

**Comment by dagarwal82** [comment]
Yes. my foxx app was using console.log. I have disabled all the logs. But
from the functionality point of view arangodb may choose not to keep all
the logs in memory. Most of the logs (95%) are :

{
    "_id" : "_foxxlog/8497830242595",
    "_rev" : "8497830242595",
    "_key" : "8497830242595",
    "levelNum" : 0,
    "time" : 1428618532057,
    "mount" : "/evc",
    "level" : "INFO",
    "message" : "ERROR:[ArangoError 1200: conflict]"
  },


On Fri, Apr 10, 2015 at 10:20 AM, Frank Celler <notifications@github.com>
wrote:

> Strange, what kind of messages are logged in this collection? Millions
> seems way too many. Are these messages from your Foxx app?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arangodb/arangodb/issues/1293#issuecomment-91573420>.
>



-- 
Deepak Agarwal
9501190044

**Comment by fceller** [comment]
That is indeed a lot of unnecessary stuff. Are these entry produced by your application?

It should be possible to restrict the number of entry by defining a cap constraint:

db._foxxlog.ensureCapConstraint(1000)

**Comment by fceller** [comment]
@dagarwal82 have you tried a cap constraint? Has this solved the issue?

**Comment by fceller** [comment]
We have also upgraded V8, which fixed some issues under Windows.
