### ISSUE TITLE
Load balancing issue between DB servers on k8s cluster

### ISSUE THREAD

**Issue by razbenya** [arangodb/arangodb#12936]
## My Environment

* __ArangoDB Version__:    3.6.5    
* __Storage Engine__:      RocksDB        
* __Deployment Mode__:   Cluster     
* __Deployment Strategy__:   Kubernetes operator 1.0.6 
* __Configuration__:       3 agents ,4 dbservers ,3 coordinators         
* __Infrastructure__:    AWS           

I performed some load tests on writings data into my cluster and I found out that one of the DB servers in my cluster is not working like the others
according to the metrics the RAM and CPU of that DB server was low in compare to the others during the load, 
and after writing 27GB of data, my DB servers disk use was: 13GB, 9GB, 4.5GB, 0.5GB.

I tried with 3 db servers as well  and saw that 2 are working and 1 is not. 

Any ideas?

**Comment by curtdept** [comment]
Check your shard distribution, if its anything like man, shards can collect up on instances and wont automatically redistribute.

**Comment by razbenya** [comment]
Thanks I will check
