### ISSUE TITLE
Documentation broken

### ISSUE THREAD

**Issue by F21** [arangodb/arangodb#1294]
The documentation appears to be broken. For example the replication docs link here, but the page is broken: https://docs.arangodb.com/Replication/README.html

**Comment by diegogub** [comment]
Try with: https://docs.arangodb.com/Replication/index.html

**Comment by OlafRadicke** [comment]
the link to the First Steps in ArangoDB ist broken too.  (https://docs.arangodb.com/FirstSteps/README.html)

**Comment by fceller** [comment]
The new gitbook generates "index.html" instead of "README.html". I've added a symbolic link.
