### ISSUE TITLE
Unique index fails for case insensitive data

### ISSUE THREAD

**Issue by sudhish-ps** [arangodb/arangodb#12952]
## My Environment

* __ArangoDB Version__:        3.6.5
* __Storage Engine__:             
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:    Manual Start 
* __Configuration__:               
* __Infrastructure__:               On-premise
* __Operating System__:        Windows 10
* __Total RAM in your machine__:       16GB
* __Disks in use__:        HDD
* __Used Package__:              

## Component, Query & Data

__Affected feature__:
Unique index creation is not supporting case insensitive validation.
For e.g. a collection to store user details with email fields as unique.
But we can insert document as below and the unique constraint fails.
Document 1 : {"name": "Abcdefg","email":"abcdefg@xyz.com"}
Document 2 : {"name": "Hijklmnop","email":"ABcdefG@xyz.com"}

__Dataset__:
Document 1 : {"name": "Abcdefg","email":"abcdefg@xyz.com"}
Document 2 : {"name": "Hijklmnop","email":"ABcdefG@xyz.com"}

## Steps to reproduce

1. Create a simple collection to save user details with attribute name and email address 
2. Insert first document with email "abcdefg@xyz.com"
3. Insert second document with email "ABCDEFG@xyz.com" 

__Problem__:

The unique constraint validation fails, only reason is email is case insensitive.

__Expected result__:

Unique validation should trigger with case insensitive data also.

**Comment by dothebart** [comment]
Hi, 
There already is a ticket about function based indices, which is obvously what one would want here: https://github.com/arangodb/arangodb/issues/1501 hence I'm closing this as duplicate.

**Comment by sudhish-ps** [comment]
@dothebart , is this function based indexes is already available or its waiting for release.
If available which version onwards ?.

**Comment by dothebart** [comment]
Hi, 
no, its not yet available. 
If you need a working solution now, duplicate the field, and normalize it before saving the documents into arangodb.
