### ISSUE TITLE
missing release artifact for 3.7.3.1?

### ISSUE THREAD

**Issue by chenrui333** [arangodb/arangodb#12961]
👋 I can see the release tag for v3.7.3.1, but the release artifact is not found on `https://download.arangodb.com/Source/index.html`

**Comment by dothebart** [comment]
Hi,
the release process looks as the following:

- set the tag
- build binaries
- run QA on them
- decide on publification date (maybe marketing wants to do something...)
- once its like that, publish; create PR to the docker library for _/arangodb, upload docker container to arangodb/arangodb
- create PR for homebrew (if newes release)

There may be internal releases that are not shared; you will not find them on the regular download pages, i.e. if we see that we need an urgent fix for Oasis or another enterprise customer that shouldn't wait for the regular release process.

However, if a release is published to the broader public, the PR to the docker library is created, and will be applied some hours later.
So there is no need to create an own PR.

**Comment by Simran-B** [comment]
That link only has ArangoDB releases up to version 3.4, so pretty obsolete. For 3.7 you should have a look here instead:
https://download.arangodb.com/arangodb37/index.html

**Comment by akrush24** [comment]
Where is artifacts for 3.7.3.1? Not here: https://download.arangodb.com/arangodb37/index.html

**Comment by dothebart** [comment]
which files are you looking for especialy? depinding on the target this may also be `3.7.3-1`.

**Comment by maxkernbach** [comment]
@akrush24 Did you have a chance to read dothebart's latest comment?
