### ISSUE TITLE
Sorted query by nested fields

### ISSUE THREAD

**Issue by romanmosienco** [arangodb/arangodb#12971]
## My Environment

* __ArangoDB Version__:        3.3.2 
* __Deployment Mode__:       Single Server 
* __Deployment Strategy__:   ArangoDB Starter in Docker
* __Operating System__:        Ubuntu 20.04
* __Total RAM in your machine__:        8Gb
* __Disks in use__:        SSD 
* __Used Package__:              Debian or Ubuntu .deb

__Problem__:
Can I make sorted AQL by nested fields?
Example:
for i in collection sort i.data.name limit 1, 10 return i

**Comment by dothebart** [comment]
Hi, 
please note that Arangodb 3.3 is out of Maintainance. Please upgrade to a supported version.

**Comment by romanmosienco** [comment]
Hello, thank you. Update fixed that issue. Sort already works with nested fields.

**Comment by dothebart** [comment]
Ok, great. 
Please remember to allways at least upgrade to the latest patch-version of one minor release before reporting bugs.
