### ISSUE TITLE
arangodb web ui do not have logs menu option

### ISSUE THREAD

**Issue by weiklr** [arangodb/arangodb#12974]
Hi,

I realize the arangodb web ui do not have logs menu option. Is it because it's only available in enterprise edition only? I'm using the community edition btw

## My Environment

* __ArangoDB Version__:       3.7.3 community edition
* __Storage Engine__:            RocksDB
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   ArangoDB Starter in Docker
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:        RHEL7
* __Total RAM in your machine__:        
* __Disks in use__:        
* __Used Package__:              

## Component, Query & Data

__Affected feature__:
web interface

## Steps to reproduce

1.  start arangodb starter in docker in cluster mode.
2.  navigate to arango web ui and login as root, choose "_system" database
3.  no "Logs" under sub menu

__Problem__: no "Logs" under sub menu in arangodb web ui

__Expected result__: I should see the Logs menu option

**Comment by dothebart** [comment]
Hi, 
the `Logs` feature is only available in single server deployments, regardless of cummunity/enterprise.
