### ISSUE TITLE
Bulk import if data already exists

### ISSUE THREAD

**Issue by kevinprotoss** [arangodb/arangodb#1298]
Hello,

I used bulk import for uploading quantity data for once, but I found it doesn't work if some data already exist.

```
{ [ArangoError: cannot create document, unique constraint violated]
  message: 'cannot create document, unique constraint violated',
  errorNum: 1210,
  code: 409,
  stack: 'ArangoError: cannot create document, unique constraint violated\n    at new ArangoError (/Invend/server_arango/node_modules/arangojs/lib/error.js:12:13)\n    at Request._callback (/Invend/server_arango/node_modules/arangojs/lib/connection.js:75:25)\n    at Request.self.callback (/Invend/server_arango/node_modules/request/request.js:360:22)\n    at Request.emit (events.js:110:17)\n    at Request.<anonymous> (/Invend/server_arango/node_modules/request/request.js:1202:14)\n    at Request.emit (events.js:129:20)\n    at IncomingMessage.<anonymous> (/Invend/server_arango/node_modules/request/request.js:1150:12)\n    at IncomingMessage.emit (events.js:129:20)\n    at _stream_readable.js:908:16\n    at process._tickCallback (node.js:355:11)' }
```
I believe this bulk import method should use your new upsert method as well, shouldn't it? #1280 
Or the bulk import is only designed for creating, not for updating?

Bg,
Kevin

**Comment by jsteemann** [comment]
Yes, bulk imports are actually performing inserts, and they will fail when there are unique constraint violations. Currently bulk imports are not meant for updating existing documents, or, insert or update depending on whether a document already exists.

**Comment by kevinprotoss** [comment]
Is this feature possible in the future? Or any other methods? I'd like to insert or update bulk data.

**Comment by neunhoef** [comment]
What do you exactly mean with "this feature"? Currently, if you have a document with 
  "_key": "xyz"
(say) in the collection and then import another one with the same _key, you always get a unique constraint violation. What we could offer relatively easily is that in that case the old revision is replaced or even updated with the newly imported document. If this is what you need we could implement an additional switch for arangoimp.
If you do not specify _key in your documents to import, then the new documents have to count as new documents and get new unique _key entries automatically generated. Should they now violate a unique constraint defined by a secondary (user defined) index, then there is no sensible thing the imported could possibly do. Therefore this would be a case in which we cannot really help.

**Comment by kevinprotoss** [comment]
Hello,

well I mean import document with given `_key`. Suppose a bulk of data which have definite `_key` in the json file. I'd like to create or update them all together.

Do you think whether this case is possible?

I believe the second one you mentioned is completely correct. DB should always throws error for case of unique constraint. 

Best regards,
Kevin

**Comment by neunhoef** [comment]
OK, I will see what we can do, this is a reasonable request and should not be a very difficult feature. I leave this one open for now.

**Comment by neunhoef** [comment]
See also
  http://stackoverflow.com/questions/29105660/arangodb-aql-update-single-object-in
-embedded-array/29124327#29124327
(just for reference).

**Comment by jsteemann** [comment]
The feature has been implemented in devel.

This change extends the HTTP REST API for bulk imports as follows:

When documents are imported and the `_key` attribute is specified for them, the import can be used for inserting and updating/replacing documents. Previously, the import could be used for inserting new documents only, and re-inserting a document with an existing would have failed with a *unique key constraint violated* error.

The above behavior is still the default. However, the API now allows controlling the behavior in case of a unique key constraint error via the optional URL parameter `onDuplicate`.   

This parameter can have one of the following values:

* `error`: when a unique key constraint error occurs, do not import or update the document but report an error. This is the default.
* `update`: when a unique key constraint error occurs, try to (partially) update the existing document with the data specified in the import. This may still fail if the document would violate secondary unique indexes. Only the attributes present in the import data will be updated and other attributes already present will be preserved. The number of updated documents will be reported in the `updated` attribute of the HTTP API result.
* `replace`: when a unique key constraint error occurs, try to fully replace the existing document with the data specified in the import. This may still fail if the document would violate secondary unique indexes. The number of replaced documents will be reported in the `updated` attribute of the HTTP API result.
* `ignore`: when a unique key constraint error occurs, ignore this error. There will be no insert, update or replace for the particular document. Ignored documents will be reported separately in the `ignored` attribute of the HTTP API result. 

The result of the HTTP import API will now contain the attributes `ignored` and `updated`, which contain the number of ignored and updated documents respectively. These attributes will contain a value of zero unless the `onDuplicate` URL parameter is set to either `update` or `replace` (in this case the `updated` attribute may contain non-zero values) or `ignore` (in this case the `ignored` attribute may contain a non-zero value).

In the devel branch, arangoimp also has a command-line option `--on-duplicate` which can have one of the values `error`, `update`, `replace`, `ignore`. The default value is `error`.
