### ISSUE TITLE
Crash using the primary sort on a view

### ISSUE THREAD

**Issue by bakjos** [arangodb/arangodb#12995]
## My Environment

* __ArangoDB Version__:        3.7.2/3.7.3
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               default
* __Infrastructure__:               Own
* __Operating System__:        OSX 10.15.7
* __Total RAM in your machine__:        16 GB
* __Disks in use__:        SSD
* __Used Package__:             None

## Component, Query & Data

__Affected feature__: AQL query using web interface / HTTP API

__AQL query (if applicable)__:
```
FOR r IN observation_full_content SEARCH ANALYZER( PHRASE(r._json,@content),"text_en")
FILTER (r._tenant == @tenant) AND HAS(r,"_version")
SORT r._tenant, r._resource_type, r._key
LIMIT 50 
RETURN DISTINCT  {resource_type: r._resource_type, id: r._key,  version: r._version, updated_at: r._updated_at}
```

__Dataset__:
Starting with an empty database and creating a view named observation_full_content with _tenant, 

__Size of your Dataset on disk__: 0

## Steps to reproduce

1. Create a collection named observation with a pesistent index on ._tenant, _resource_type, _key, _updated_at 
2. Create an arango search view with a primary sort on the same fields: ._tenant, _resource_type, _key, _updated_at
```
{
  "writebufferIdle": 64,
  "type": "arangosearch",
  "primarySortCompression": "lz4",
  "links": {
    "observation": {
      "analyzers": [
        "identity"
      ],
      "fields": {
        "_json": {
          "analyzers": [
            "text_en"
          ]
        }
      },
      "includeAllFields": false,
      "storeValues": "none",
      "trackListPositions": false
    }
  },
  "primarySort": [
    {
      "field": "_tenant",
      "asc": true
    },
    {
      "field": "_resource_type",
      "asc": true
    },
    {
      "field": "_key",
      "asc": true
    },
   {
      "field": "_updated_at",
      "asc": true
    }
  ],
  "writebufferSizeMax": 33554432,
  "consolidationPolicy": {
    "type": "tier",
    "segmentsBytesFloor": 2097152,
    "segmentsBytesMax": 5368709120,
    "segmentsMax": 10,
    "segmentsMin": 1,
    "minScore": 0
  },
  "cleanupIntervalStep": 2,
  "commitIntervalMsec": 1000,
  "storedValues": [],
  "id": "33679",
  "globallyUniqueId": "hC9DD9F9722CE/33679",
  "writebufferActive": 0,
  "consolidationIntervalMsec": 10000
}
``` 
3. Try to execute/explain the query from above

__Problem__: The server crashed with 
```
2020-11-05T15:21:29Z [79056] FATAL [a7902] {crash} ArangoDB 3.7.2 [darwin], thread 6 caught unexpected signal 11 (SIGSEGV) accessing address 0xffffffffffffffea: signal handler invoked
2020-11-05T15:21:29Z [79056] INFO [ded81] {crash} available physical memory: 8589934592, rss usage: 193302528, vsz usage: 5742145536, threads: 41
```

__Expected result__: The actual plan using the sort indexes

**Comment by gnusi** [comment]
@bakjos Thank you for reporting the issue, we can confirm a bug and will fix it soon. We'll keep you posted.
