### ISSUE TITLE
unintended errors in documentation examples

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangodb#1299]
version 2.5.1
in chapters 8 and 13.1.

**Comment by pluma** [comment]
@13abylon Some of the arangosh output contains error messages.

**Comment by 13abylon** [comment]
Yes, something went wrong with the build of the documentation. This will be fixed.

Thanks for reporting!

**Comment by 13abylon** [comment]
The examples are fixed and the documentation is up to date. Thanks again!

**Comment by pekeler** [comment]
:)
