### ISSUE TITLE
declared value(long) is not saving correctly!

### ISSUE THREAD

**Issue by Likqez** [arangodb/arangodb#13000]
## My Environment

* __ArangoDB Version__:        3.6.4/3.7.2-1
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start in Docker
* __Infrastructure__:               own
* __Operating System__:        Debian Buster
* __Used Package__:             Docker - official Docker library

## Component, Query & Data

__Affected feature__:

AQL query using web interface

__Dataset__:

```
{
"role": 673556478107320300
}
```

## Steps to reproduce

1.  Update the above Dataset in the Arango Documentviewer. Set ``673556478107320320`` as the new value for ``role``
2.  Click save and go back to the collection view.
3. Click on the previous updated Document, and check if the new value is still applied.

__Problem__:
Whenever I try to UPDATE the value of ``role`` to ``673556478107320320`` and save it. Wether its with the Interface or as AQL Query, the long is not getting saved, or more getting set to this value here: ``673556478107320300``. I tried it on serveral instances, its save to say that none of my software is changing the value back.

__Expected result__:
To seemlessly save the document, with the value not getting changed later.

**Comment by dothebart** [comment]
Hi, 
Numbers in JSON have a maximal number of digits: https://www.tutorialspoint.com/json/json_data_types.htm
If you need more digits, you need to save the number as string.

**Comment by Likqez** [comment]
Sad noises :c But okay, thanks :)
