### ISSUE TITLE
How Do I Specify the Library for Arangodb Running?

### ISSUE THREAD

**Issue by Neverstop** [arangodb/arangodb#13002]
* __ArangoDB Version__:       3.6.3.1
* __Storage Engine__:             RocksDB
* __Deployment Mode__:      Cluster
* __Deployment Strategy__:   Manual Start         
* __Configuration__:                Three services are deployed on each host. agency primary coordinator
![image](https://user-images.githubusercontent.com/7472542/98540045-43ba0480-22c8-11eb-894a-4b0979ac06a7.png)

* __Infrastructure__:               
* __Operating System__:        Linux host
* __Total RAM in your machine__:       16G
* __Disks in use__:        
* __Used Package__:              

__Problem__:

How Do I Specify the Library for Arangodb Running?
For example: libssl.so.1.1      libcrypto.so.1.1
Because the version of the library I use conflicts with that of the OS process.

By the way, are there any problems with my deployment strategy?
how much memory size is required.？ 16 GB memory overflows after the service is started.

thanks for help~

**Comment by dothebart** [comment]
Hi, 
the ArangoDB executeables are statically linked, you can't replace the linked in openssl library.
It also won't pick libraries from the OS. 
Instead of the GLIBC [libmusl](https://musl.libc.org/) is used.
Please note that you should always upgrade to the latest patch version of minor releases - 3.6.5 at the time being in your case.

**Comment by Neverstop** [comment]
> Hi,
> the ArangoDB executeables are statically linked, you can't replace the linked in openssl library.
> It also won't pick libraries from the OS.
> Instead of the GLIBC [libmusl](https://musl.libc.org/) is used.
> Please note that you should always upgrade to the latest patch version of minor releases - 3.6.8 at the time being in your case.

But when I run the service, it will reference the OS library file.
![image](https://user-images.githubusercontent.com/7472542/98622792-49a1fb00-2345-11eb-8d3a-4dec683e662d.png)

The binary tool arangod I used was compiled by myself. this is my CMake order:
cmake -DUSE_BACKTRACE=Off -DOPENSSL_ROOT_DIR=$PROJECT_DIR/build/$OPENSSL -DOPENSSL_CRYPTO_LIBRARIES=$PROJECT_DIR/build/$OPENSSL -DUSE_OPTIMIZE_FOR_ARCHITECTURE=On -DASM_OPTIMIZATIONS=0 -DUSE_FAILURE_TESTS=Off -DUSE_JEMALLOC=Off -DBASE_C_FLAGS="-mtune=generic -fstack-protector-all -fPIE -pie" -DBASE_CXX_FLAGS="-mtune=generic -fstack-protector-all -fPIE -pie" -DBASE_LD_FLAGS="-Wl,-z,now" -DVERBOSE=On ..

by the way, What problems can be solved by upgrading to 3.6.8?

**Comment by dothebart** [comment]
if you don't use static linking, your build-host needs to be the same operating system as the target host. 
https://github.com/arangodb/arangodb/blob/3.6/CHANGELOG has the list of the problems solved. 

the scripts we use to build the static binaries can be found in: https://github.com/arangodb/oskar/

Dynamic linked binaries may use LD_LIBRARY_PATH to modify the library path they're run from - see https://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html for details.

May I ask for the reason you compile arangodb on your own?

**Comment by Neverstop** [comment]
Because it's the company's request~

I have another question.  Is 16 GB memory not enough?
I'm going to expand memory now, but I'm still confused.

**Comment by dothebart** [comment]
for compiling? depends on your parallelity `-j` - linking C++ is quiet memory intense - switching to the GOLD linker may improve the situation.

**Comment by Neverstop** [comment]
> for compiling? depends on your parallelity `-j` - linking C++ is quiet memory intense - switching to the GOLD linker may improve the situation.

Not compile but running. 
![image](https://user-images.githubusercontent.com/7472542/98673926-079fa600-2393-11eb-8580-e157dc09930c.png)

**Comment by dothebart** [comment]
please have a look at https://www.arangodb.com/docs/stable/tutorials-reduce-memory-footprint.html - it explains how to reduce this, and what the actual tradeoffs are.

**Comment by Neverstop** [comment]
I expanded the memory to 32 gigabytes.  the operating system still overflowed. 
After the primary process is started, all the memory is occupied in less than one minute.
Does any module in there apply for unlimited memory?

**Comment by dothebart** [comment]
do you meanwhile run the latest 3.6 series?

**Comment by Neverstop** [comment]
No, I'm getting ready to upgrade now

**Comment by Neverstop** [comment]
thanks for your help
After the upgrade to 3.6.9, the memory overflow problem does not occur.
