### ISSUE TITLE
Make arangodump not fail if directory exists but is empty

### ISSUE THREAD

**Issue by F21** [arangodb/arangodb#1300]
I am currently working on an ArangoDB source for [sebastianfeldmann/phpbu](https://github.com/sebastianfeldmann/phpbu) to allow easy automated backups.

The problem is that phpbu allows users to define where the backups will be placed and will need to first create the destination folder for the backup. This creates a problem because `arangodump` will see that the destination folder exist and fail.

I propose that we change the behaviour of `arangodump` so that it does not fail if the destination folder exists but is empty. This allow us to not have to use `--overwrite` which can be dangerous.

**Comment by neunhoef** [comment]
I think this is a good idea. I believe that nobody can possibly be disturbed by an empty directory being filled when he did an arangodump.
It would be cool if ArangoDB would be one of the targets of  sebastianfeldmann/phpbu .
If you send a pull request we can quickly approve it.

**Comment by F21** [comment]
I am currently working on an arangodump target for phpbu (just waiting on https://github.com/sebastianfeldmann/phpbu/issues/9#issuecomment-90824423).

**Comment by jsteemann** [comment]
Fixed in 2.5 and devel.
