### ISSUE TITLE
The regular expression operator =~ is not working

### ISSUE THREAD

**Issue by sudhish-ps** [arangodb/arangodb#13012]
## My Environment

* __ArangoDB Version__:        3.6.5
* __Storage Engine__:            
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:              
* __Infrastructure__:               own
* __Operating System__:        Ubuntu 20.04
* __Total RAM in your machine__:  16GB
* __Disks in use__:        HDD
* __Used Package__:              

## Component, Query & Data

__Affected feature__:
AQL query with regular expression pattern in filter

__AQL query (if applicable)__:
FOR doc IN employee
  FILTER doc.name =~ /test-PP/i
  RETURN doc
  

```
__AQL explain and/or profile (if applicable)__:
AQL query is generated by ArangoDB query parser with filter for a document, which searches data in name attributes with case insensitive


__Dataset__:
{
"name":"test-PP",
"email":"abcd@xyz.com"
}

## Steps to reproduce

1.Created above document in a collection 
2. Generated AQL query and executed using ArangoJS
3. No result set

__Problem__:

The operator =~ for regular expression filter is not working and returning the result

__Expected result__:

The operator =~ should compare the test with the left operand fields against the right operand regular expression and generate the result.

**Comment by goedderz** [comment]
Hi @sudhish-ps,

AQL does not use delimiters for Regexes like Perl or sed do, just regular strings. See the documentation for details and examples: https://www.arangodb.com/docs/stable/aql/operators.html#comparison-operators and https://www.arangodb.com/docs/stable/aql/functions-string.html#regex_test.

So try rewriting your query as follows:

```
FOR doc IN employee
FILTER REGEX_TEST(doc.name, "test-PP", true)
RETURN doc
```

Best regards

Tobias

**Comment by sudhish-ps** [comment]
Hi @goedderz ,

How this condition can represent through query string for above data;
http://localhost/employee?name=test-pp/i  ?

**Comment by goedderz** [comment]
Hi @sudhish-ps,

sorry, I do not understand your question. Can you describe more precisely what you're looking for? Your example looks like you do not need regular expressions at all, but just an equality lookup like:

```
FOR doc IN employee
FILTER doc.name = "test-PP"
RETURN doc
```

**Comment by sudhish-ps** [comment]
In short, I want to use the operator =~ or !~ for comparison like below
FOR doc IN employee
FILTER doc.name =~ "test-*"
RETURN doc
Is it possible ? or this operators are not enough to do comparison with such regular expression ?

**Comment by goedderz** [comment]
Note that a `*` is **not** a wildcard in regular expressions, but allows for an arbitrary number of repetitions of the previous atom. The regex `test-*` matches `test`, `test-`, `test--`, `test---`, and so on, which is probably not what you want.

Also regexes look for partial matches, so e.g. `"footestfoo" =~ "test"` would be true. Use the anchors `^` and `$` for complete matches.

So try `^test-.*$` instead.

And please have a more thorough look at our documentation, or some regex tutorial.
