### ISSUE TITLE
ArangoDB Windows Installation

### ISSUE THREAD

**Issue by hkernbach** [arangodb/arangodb#1301]
When installing ArangoDB and enabling the checkbox "Create desktop shortcut", no shortcut is created.

Used Setup-File: ArangoDB-2.5.1-win64.exe
Tested on Windows 2012 R2

**Comment by fceller** [comment]
@hkernbach @hkernbach does this problem still exist in 2.5.5?

**Comment by dothebart** [comment]
not yet worked on - as NSIS fuzzing requires time.
