### ISSUE TITLE
ArangoJS Driver: Cannot inject variables to AQL query to construct dynamic filters.

### ISSUE THREAD

**Issue by codewithpatelo** [arangodb/arangodb#13016]
## My Environment

* __ArangoDB Version__:        3.6.3-1
* __Storage Engine__:            RocksDB 
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   I run arangodb3 with systemd
* __Configuration__:              Default
* __Infrastructure__:              Own local computer
* __Operating System__:       elementary OS 5.1.4 Hera (Built on Ubuntu 18.04.4 LTS)
* __Total RAM in your machine__:       3,9 GB memory
* __Disks in use__:       46% in use 
* __Used Package__:    Debian or Ubuntu .deb 

## Component, Query & Data

__Affected feature__:
AQL query with ArangoJS driver.

__AQL query (if applicable)__:
```
FOR R in orans_requests
  FOR E IN orans_employees
    FOR I in orans_requests_info
      FOR C IN orans_countries
      FILTER R.req_emp_nbr == E.emp_nbr
    FILTER R.req_req_inf_nbr == I.req_inf_nbr
  FILTER I.req_inf_ctry_cd == C.ctry_cd

  LET X = MERGE(C,E,I,R) FILTER R.req_nbr == ${request_nbr}

  RETURN {
  req_emp_nbr: X.req_emp_nbr,
  emp_nm: X.emp_nm,
  emp_lst_nm: X.emp_lst_nm,
  emp_cd: X.emp_cd,
  req_inf_acct_nbr: X.req_inf_acct_nbr,

  }

```

## Steps to reproduce

1. In a moleculer service (REST API) make a method for the corresponding AQL
2. Try inserting a dynamic filter with ${}
3. Make an API Call to that method.

__Problem__:
I'm building a Moleculer/Nodejs API with ArangoDB as db base and ArangoJS as the driver. AQL works fine without variables put on them but if you insert variables (in this case **${request_nbr}**) it will not return the requested document. I tried turning variable to different formats (Example: To Number) and it didn't work.

__Expected result__:
Returning the corresponding document on collection depending the value of the variable so you can have dynamic filters in the API based on parameters sent by user.

When I don't use variables it returns:
![image](https://user-images.githubusercontent.com/16574952/98718231-ee83fe80-236c-11eb-8929-87014524d0ef.png)

But when I do...

![image](https://user-images.githubusercontent.com/16574952/98718601-64886580-236d-11eb-971e-e39b079c21d8.png)

The array is empty.

The code for the API method is like this:

```
from an async function where parameters are query params
...
//HERE IT GETS THE QUERY PARAMETER
   let request_nbr = cxt.query.request_nbr;
    try {
// HERE RUNS THE QUERY WITH THE PARAMETER ON IT
      cursor = await db.query(
        aql`FOR R in orans_requests
  FOR E IN orans_employees
    FOR I in orans_requests_info
      FOR C IN orans_countries
      FILTER R.req_emp_nbr == E.emp_nbr
    FILTER R.req_req_inf_nbr == I.req_inf_nbr
  FILTER I.req_inf_ctry_cd == C.ctry_cd

  LET X = MERGE(C,E,I,R) FILTER R.req_nbr == ${request_nbr}

  RETURN {
  req_emp_nbr: X.req_emp_nbr,
  emp_nm: X.emp_nm,
  emp_lst_nm: X.emp_lst_nm,
  emp_cd: X.emp_cd,
  req_inf_acct_nbr: X.req_inf_acct_nbr,

  }
`,
      );
      logger.info(context);
      return await cursor._result;
    }
```

**Comment by Simran-B** [comment]
Can you clarify what data type `cxt.query.request_nbr` is? Is it a number? And is the stored attribute `req_nbr` also a number in ArangoDB? What if you substitute `${request_nbr}` with `2826`, does it match the expected document?

**Comment by codewithpatelo** [comment]
> Can you clarify what data type `cxt.query.request_nbr` is? Is it a number? And is the stored attribute `req_nbr` also a number in ArangoDB? What if you substitute `${request_nbr}` with `2826`, does it match the expected document?

Good question, I might not made it clear. ${request_nbr} is a four-digit integer number (like 2826). When I replace ${request_nbr} with 2826 (as a number not a string) it works as supposed. I also tried replacing ${request_nbr} with ${Number(request_nbr)} but it also didn't work. I also tried to do it at declaration level but didn't work as well. (Example let request_nbr = Number(cxt.query.request_nbr)).

**Comment by codewithpatelo** [comment]
Solved guys.

While turning the query parameter to number at declaration level in fact worked, there was a small syntax mistake in that try.

**Comment by Simran-B** [comment]
Great, thanks for the feedback!
