### ISSUE TITLE
Cannot findout all edges with `==` and `in` operator

### ISSUE THREAD

**Issue by yangqinj** [arangodb/arangodb#13011]
## My Environment

* __ArangoDB Version__:        3.5.0
* __Storage Engine__:            RocksDB  
* __Deployment Mode__:       Cluster 
* __Deployment Strategy__:   Manual Start
* __Configuration__:               coordinator, primary and agency use their own configuration.
* __Infrastructure__:               
* __Operating System__:        CentOS_7.4
* __Total RAM in your machine__:       16U32G 
* __Disks in use__:        
* __Used Package__:              

## Component, Query & Data
__Replication Factor & Number of Shards (Cluster only)__:

We have one collection and one graph. The collection has 2 replications and 6 shards in `_key`; the graph has 1 replication and 6 shards in `_key`.

__Problem__:
I use the  AQL to find out edges but got different number of elements with the given `_from`:
```
# This AQL with `==` operator only returns 6 elements
FOR edge IN graph_name
FILTER edge._from =="graph_name/61e36713e43a8a8db147bba63e0bf975"
RETURN {'vertex': edge.vertex, 'from': edge._from, 'to': edge._to}

# This AQL with `IN` operator also only returns 6 elements
FOR edge IN graph_name
FILTER edge._from IN ["graph_name/61e36713e43a8a8db147bba63e0bf975"]
RETURN {'vertex': edge.vertex, 'from': edge._from, 'to': edge._to}

# But this AQL with `LIKE` operator can return all 8 elements
FOR edge IN graph_name
FILTER edge._from LIKE "graph_name/61e36713e43a8a8db147bba63e0bf975"
RETURN {'vertex': edge.vertex, 'from': edge._from, 'to': edge._to}
```

I have checked that `_from` of the 8 elements are all "graph_name/61e36713e43a8a8db147bba63e0bf975".

**Comment by goedderz** [comment]
Hi @yangqinj,

would you be so kind as to try again with a more recent version first? At least with 3.5.6, which should be the most recent 3.5 release. Note that there are also already 3.6 and 3.7 branches, with 3.6.8 and 3.7.3 being the most recent versions, respectively.

Best regards,

Tobias

**Comment by yangqinj** [comment]
It's not easy to try other version because the cluster is our produce environment and it seems we don't encounter the same problem at our test environment (also 3.5.0 version). We're trying to reproduce the problem at the test environment now. 

Besides, I tried the AQL with `==` operator at the produce environment just now, and now it can filter out all  8 elements. It's so strange and the data has not been changed.....

**Comment by yangqinj** [comment]
@goedderz  Did you encountered this kind problem? Is it a known issue?

**Comment by goedderz** [comment]
> Is it a known issue?

I don't know, but there are hundreds of changes from 3.5.0 to 3.5.6 alone, and even more between the minor versions (to 3.6 and 3.7). I really recommend always upgrading to the latest patch version at least. Not just because of the problem you've described here, but because there are lots of other bugs fixed as well.

**Comment by yangqinj** [comment]
Thanks for your advice! But I still worry that the problem still cannot be solved by upgrading. It will cost lots of time and effort to upgrade......

**Comment by jsteemann** [comment]
There is a known issue which looks related, and was fixed in version 3.5.5.1, released on May 8th 2020.
I can't tell which version you are currently running, but the issue states 3.5.0.
In this case an upgrade could indeed help.

**Comment by yangqinj** [comment]
@jsteemann Thank you a lot for the reply!!! I will try upgrade the version to 3.7.3 and check whether the problem still exists. Thanks again for your quick reply and useful advice @jsteemann @goedderz 👍

**Comment by Simran-B** [comment]
Closing as we consider it fixed in more recent versions. Feel free to reopen should the problem still occur in 3.5.5.1 or later.
