### ISSUE TITLE
Query execution is taking too long on multiple joins

### ISSUE THREAD

**Issue by codewithpatelo** [arangodb/arangodb#13010]
## My Environment

* __ArangoDB Version__:        3.6.3-1
* __Storage Engine__:            I assume RocksDB 
* __Deployment Mode__:       Single Instance Deployment
* __Deployment Strategy__:   I run arangodb3 with systemd
* __Configuration__:              Default
* __Infrastructure__:              Own local computer
* __Operating System__:       elementary OS 5.1.4 Hera (Built on Ubuntu 18.04.4 LTS)
* __Total RAM in your machine__:       3,9 GB memory
* __Disks in use__:       46% in use 
* __Used Package__:    Debian or Ubuntu .deb 

## Component, Query & Data

__Affected feature__:
AQL Queries

__AQL query (if applicable)__:
```
FOR R in orans_requests 
  FOR I in orans_requests_info 
    FOR E IN orans_employees
      FOR C IN orans_countries 
      FILTER C.ctry_cd == I.req_inf_ctry_cd
    FILTER E.emp_nbr == R.req_emp_nbr
  FILTER I.req_inf_nbr == R.req_req_inf_nbr
    
  LET X = MERGE(C,E,I,R) FILTER X.ctry_cd == "MX" SORT X.req_inf_dt LIMIT 10

  RETURN X
```

__AQL explain and/or profile (if applicable)__:

![image](https://user-images.githubusercontent.com/16574952/98616180-0317b680-22db-11eb-89bd-aedb0d1de1f4.png)
![image](https://user-images.githubusercontent.com/16574952/98616199-0f9c0f00-22db-11eb-96bf-9e6eaa538428.png)

__Dataset__:
There are 4 different collections used.

One for employees 
![image](https://user-images.githubusercontent.com/16574952/98617452-ca2d1100-22dd-11eb-8fe5-ba7fb16c770e.png)
(Changed data but structure is the one in the pic)

One for countries
![image](https://user-images.githubusercontent.com/16574952/98616326-57bb3180-22db-11eb-897f-5d2f0acec9d1.png)

One for client applications
![image](https://user-images.githubusercontent.com/16574952/98616524-b8e30500-22db-11eb-9ecf-146fc5d1be7e.png)

And another one for specific information on those applications
![image](https://user-images.githubusercontent.com/16574952/98616475-9ea92700-22db-11eb-9eff-39dd48cc95e2.png)
(I changed the data as a random example)

__Size of your Dataset on disk__:
The size of the dump for the whole 4 collections used is 4.8 MB compressed. 

## Steps to reproduce

1. Go to Arango Web UI logged with corresponding database
2. Insert referenced query
3. Execute

__Problem__:
The query is taking more than 100 seconds to process each time is executed.

__Expected result__:
Execution in less than a minute as the query will be used several times or a more efficient/performative way to get the same data using AQL.

**Comment by goedderz** [comment]
Hi @codewithpatelo!

You need to add indexes so this can be executed more efficiently. Have a look at https://www.arangodb.com/docs/stable/indexing.html for details. For example, add `["req_inf_ctry_cd"]` to `orans_requests_info`, and similarly for the other collection/attribute combinations that should allow for an efficient lookup.

You can add indexes in the web interface, in arangosh, or with the driver of your choice.

HTH and best regards,

Tobias

**Comment by codewithpatelo** [comment]
Thanks! I'll try that.

**Comment by codewithpatelo** [comment]
After reading the documentation, I'm not sure if you are suggesting making an edge index for each collection connection, separate persistent non-sparsy indexes for each field for each collection or a persistent non-sparsy index with all connectable attributes for each collection. Which one do you recommend?

**Comment by codewithpatelo** [comment]
For instance, I created an index in each collection with all nbr/cds fields and now the query is running at 7 seconds (before was +100 seconds). Massive improvement yet, it seems from all indexes it is only using one while based on the filters of the query it could use more.
![image](https://user-images.githubusercontent.com/16574952/98709800-9e536f00-2361-11eb-8042-43525a2aa658.png)

**Comment by dothebart** [comment]
you should allways create the indices in a way that they reduce the dataset to be fetched as much as possible. 
In doubt, try running counts etc. on your dataset to get good estimates.

**Comment by goedderz** [comment]
> For instance, I created an index in each collection with all nbr/cds fields and now the query is running at 7 seconds (before was +100 seconds). Massive improvement yet, it seems from all indexes it is only using one while based on the filters of the query it could use more.
> ![image](https://user-images.githubusercontent.com/16574952/98709800-9e536f00-2361-11eb-8042-43525a2aa658.png)

You created combined indexes. That'd be useful if you're filter multiple attributes in the same collection, as in `FOR d IN orans_requests_info FILTER d.req_inf_nbr == @foo AND d.req_inf_req_nbr == @bar AND d.req_inf_emp_nbr == @baz AND ...`. However, while the combined index `["req_inf_nbr", "req_inf_req_nbr", ...]` can be used for the condition `FILTER d.req_inf_nbr == @foo` alone, too, it *cannot* be used for `FILTER d.req_inf_req_nbr == @foo` alone.

For starters, just create default indexes, each with only the one attribute that's needed in that collection.

You can read https://www.arangodb.com/2018/02/indexes-types-arangodb-part-1/ for some background information.

**Comment by codewithpatelo** [comment]
> > For instance, I created an index in each collection with all nbr/cds fields and now the query is running at 7 seconds (before was +100 seconds). Massive improvement yet, it seems from all indexes it is only using one while based on the filters of the query it could use more.
> > ![image](https://user-images.githubusercontent.com/16574952/98709800-9e536f00-2361-11eb-8042-43525a2aa658.png)
> 
> You created combined indexes. That'd be useful if you'd be filtering multiple attributes in the same collection, as in `FOR d IN orans_requests_info FILTER d.req_inf_nbr == @foo AND d.req_inf_req_nbr == @bar AND d.req_inf_emp_nbr == @baz AND ...`. However, while the combined index `["req_inf_nbr", "req_inf_req_nbr", ...]` can be used for the condition `FILTER d.req_inf_nbr == @foo` alone, too, it _cannot_ be used for `FILTER d.req_inf_req_nbr == @foo` alone.
> 
> For starters, just create default indexes, each with only the one attribute that's needed in that collection.
> 
> You can read https://www.arangodb.com/2018/02/indexes-types-arangodb-part-1/ for some background information.

Alright. I can see. I tried with persistent non-sparsy indexes for the individual fields and it worked. Now it's taking one second to process. Thanks!

**Comment by goedderz** [comment]
You're welcome!
