### ISSUE TITLE
Can't use Joi.array.items method in Foxx

### ISSUE THREAD

**Issue by lovedder** [arangodb/arangodb#1304]
When I try to use Joi.array.items in my Foxx model I get: TypeError: undefined is not a function.

**Comment by pluma** [comment]
The version of joi bundled with 2.5 and earlier is a bit out of date. The method `items` used to be called `includes`.

An updated version will be shipped with 2.6.

In the meantime, if you need features not supported by the older version of joi, you can just install the module locally in your Foxx app (go to your Foxx app's folder and `npm install joi`).
