### ISSUE TITLE
Expiration of jwt auth token

### ISSUE THREAD

**Issue by TuminD** [arangodb/arangodb#13048]
## My Environment

* __ArangoDB Version__:        3.6.7-1
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Cluster (3 servers)
* __Deployment Strategy__:   ArangoDB Starter

__Problem__:
I've setup arango cluster health monitoring in our monitoring system using Arango REST API.
Monitoring invokes GET requests to /_db/_system/_admin/cluster/health - with JWT authentication
But one day it got response "401 Unauthorized"

Found out that jwt auth token has expired:
"Please note that the JWT will expire after 1 month and needs to be updated"
https://www.arangodb.com/docs/stable/http/general.html#user-jwt-token

So, how to use jwt auth token for monitoring or is there way to generate token without expiration ?

**Comment by neunhoef** [comment]
I think you can simply generate a token without expiration date. See https://www.arangodb.com/docs/stable/http/general.html#superuser-jwt-token

**Comment by neunhoef** [comment]
Just use the `arangodb` executable for this as described here: https://www.arangodb.com/docs/stable/programs-starter-security.html#using-authentication-tokens

**Comment by TuminD** [comment]
neunhoef, thank you!
