### ISSUE TITLE
Join is extremely slow

### ISSUE THREAD

**Issue by webmake** [arangodb/arangodb#13046]
## My Environment

* __ArangoDB Version__:        3.7.3
* __Operating System__:        Ubuntu 20.04
* __Total RAM in your machine__:        32Gb + 32Gb swap
* __Disks in use__:        SSD

## Component, Query & Data
__AQL query__:
```
FOR a IN identities
  FOR b IN identities
    FILTER a.ip == b.ip AND a.id != b.id
    INSERT {_from: a._id, _to: b._id} IN ips 

```
__AQL explain and/or profile__:
```
Query String (128 chars, cacheable: false):
 FOR a IN identities
   FOR b IN identities
     FILTER a.ip == b.ip AND a.id != b.id
     INSERT {_from: a._id, _to: b._id} IN ips 

Execution plan:
 Id   NodeType                        Est.   Comment
  1   SingletonNode                      1   * ROOT
  3   EnumerateCollectionNode        87260     - FOR b IN identities   /* full collection scan, projections: `_id`, `id`, `ip` */
  2   EnumerateCollectionNode   7614307600       - FOR a IN identities   /* full collection scan, projections: `_id`, `ip`, `id` */
  4   CalculationNode           7614307600         - LET #3 = ((a.`ip` == b.`ip`) && (a.`id` != b.`id`))   /* simple expression */   /* collections used: a : identities, b : identities */
  5   FilterNode                7614307600         - FILTER #3
  6   CalculationNode           7614307600         - LET #5 = { "_from" : a.`_id`, "_to" : b.`_id` }   /* simple expression */   /* collections used: a : identities, b : identities */
  7   InsertNode                         0         - INSERT #5 IN ips 

Indexes used:
 none

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   interchange-adjacent-enumerations
  4   move-calculations-up-2
  5   move-filters-up-2
  6   remove-data-modification-out-variables
  7   reduce-extraction-to-projection

Write query options:
 Option                   Value
 waitForSync              false
 skipDocumentValidation   false
 keepNull                 true
 mergeObjects             true
 ignoreRevs               true
 isRestore                false
 ignoreErrors             false
 ignoreDocumentNotFound   false
 readCompleteInput        false
 consultAqlWriteFilter    false
 exclusive                false
 nullMeansRemove          false
```
Index:
![image](https://user-images.githubusercontent.com/5016464/99242542-072a6380-2808-11eb-9489-af5d339dc668.png)

__Dataset__:
List containing ips
ex:
{user_id: 123,ip: "127.0.0.1", user_agent:"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"}
87260 elements

__Problem__:
It executes very long time, to insert, because join result is 7614307600 =87260 x 87260. 
Am I doing it in wrong way? I was planned to join multiple attributes, like user agent with user agent, etc, but now I see ip with ip attribute takes so long to generate.
![image](https://user-images.githubusercontent.com/5016464/99244619-fc250280-280a-11eb-9751-cf7ddc35f735.png)

**Comment by dothebart** [comment]
`EnumerateCollectionNode` is a full-collection scan. you should strive to reduce the number of documents to be processed by using an index. A reduced document count will improve the performance.

**Comment by webmake** [comment]
But I made index, following:
![image](https://user-images.githubusercontent.com/5016464/99247503-b3bc1380-280f-11eb-9c43-4ff5abc412f5.png)

**Comment by webmake** [comment]
Should I manually create edges and import, instead of quering in arangodb?

**Comment by dothebart** [comment]
sparse indices aren't able to be used for all filtering operations. 
don't all your fields contain an `ip` attribute? maybe better first normalize that?

**Comment by webmake** [comment]
I imported whole database from mysql, and trying with arangodb make relations, ip->ip, user_agent->user_agent, product->product, and so on to make clustering map.
I can prepare csv with nodes, but I hoped that in arangodb I can make joins, like in neo4j.. but it seems that very in efficient in arangodb, while I looping twice within same collection. So maybe I am missing another approach to join with edges

**Comment by dothebart** [comment]
well, how else do you get the cross-product of a collection? Self joins without index support are expensive by nature, regardless which RDBMS you use or which syntax you use to demand the respective RDBMS to compare each document with any other of the collection or table?

**Comment by webmake** [comment]
I compared those 2level loop in php, it worked only on 1cpu at 100% cpu, and it finished after 4192.7294900417 s, while arangodb still looping, with multithreading, 200-400% cpu..

**Comment by dothebart** [comment]
Again.

Unless index lookup isn't working, it needs to cross compare all documents. 

If you can't get that easily working, calculating the edges outside of arangodb will get you faster to your goal, in terms of implementation and calculation.

**Comment by Simran-B** [comment]
How many documents have an `ip` value and how many don't have this attribute or an explicitly `null` value?
If most documents have it, then don't tick the **Sparse** option and the index will be utilized.
A sparse index is not eligible unless you prove that there are no null values, like so:

```js
FOR a IN identities
  FOR b IN identities
    FILTER a.ip != null AND b.ip != null AND a.ip == b.ip AND a.id != b.id
    INSERT {_from: a._id, _to: b._id} IN ips 
```
This will utilize the sparse index on field `ip`.

**Comment by Queatz** [comment]
You'll also want an index on `id` if that is the column imported from mysql.

**Comment by webmake** [comment]
Thanks for all, I solved by creating externally on php edges, as it is the best solution to create relations outside arangodb..

**Comment by Simran-B** [comment]
> You'll also want an index on `id` if that is the column imported from mysql.

@Queatz That will not help here, because the condition is a negation.
