### ISSUE TITLE
AQL Query Performance Problem

### ISSUE THREAD

**Issue by Neverstop** [arangodb/arangodb#13059]
## My Environment

* __ArangoDB Version__:        3.6
* __Storage Engine__:             RocksDB 
* __Deployment Mode__:       Cluster 
* __Deployment Strategy__:   Manual Start 
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:        Linux
* __Total RAM in your machine__:        32Gb

__AQL query (if applicable)__:

FOR node IN rec_nodes FILTER (node.count < 3 AND node.type == ‘user’)) 
SORT node.count ASC 
LIMIT 124,125 
RETURN DISTINCT node

```
__AQL explain and/or profile (if applicable)__:
Query String (159 chars, cacheable: true):
 FOR node IN rec_nodes FILTER (node.count < @var5827040693413024 AND (node.type == 
 @var5827040693419730)) SORT node.count ASC LIMIT 124,125 RETURN DISTINCT node

Execution plan:
 Id   NodeType        Site   Est.   Comment
  1   SingletonNode   DBS       1   * ROOT
 11   IndexNode       DBS   55733     - FOR node IN rec_nodes   /* persistent index scan, 1 shard(s) */    FILTER (node.`type` == "'user'")   /* early pruning */   
 15   RemoteNode      COOR  55733       - REMOTE
 16   GatherNode      COOR  55733       - GATHER 
  7   LimitNode       COOR    125       - LIMIT 124, 125
  9   CollectNode     COOR    100       - COLLECT #7 = node   /* distinct */
 10   ReturnNode      COOR    100       - RETURN #7

Indexes used:
 By   Name                      Type         Collection   Unique   Sparse   Selectivity   Fields        Ranges
 11   idx_1683608284615933952   persistent   rec_nodes    false    false         0.01 %   [ `count` ]   (node.`count` < 3)

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   remove-unnecessary-calculations
  4   move-calculations-up-2
  5   move-filters-up-2
  6   use-indexes
  7   remove-filter-covered-by-index
  8   use-index-for-sort
  9   remove-unnecessary-calculations-2
 10   scatter-in-cluster
 11   distribute-filtercalc-to-cluster
 12   remove-unnecessary-remote-scatter
 13   move-filters-into-enumerate


__Problem__:
That's my index：
db.rec_nodes.ensureIndex({type:"persistent", fields:["type"], unique: false})
db.rec_nodes.ensureIndex({type:"persistent", fields:["count"], unique: false})

Can the query performance of the AQL be improved?

**Comment by dothebart** [comment]
Hi, 
you can not use multiple indices in one collection access.
[Hence you need one index that covers both fields.](https://www.arangodb.com/docs/stable/indexing-working-with-indexes.html#listing-all-indexes-of-a-collection)
Specifying the field with the higher selectivity (more different values) will yield better results.

**Comment by Neverstop** [comment]
can not use multiple indices in one collection， exclude the key index?

Can I do that：
db.rec_nodes.ensureIndex({type:"persistent", fields:["type"， "count"], unique: false})

If I do this, specify the type separately.
Is index retrieval still possible?

thanks for your help  👍

**Comment by dothebart** [comment]
the key index is no exclusion here. Explain will show you that only one index is used - if you have one collection access. 
The above format should show in `explain` that this index is prefered above the ones you already got.

**Comment by Neverstop** [comment]
thanks for help~
