### ISSUE TITLE
ArangoDB Windows Services Management

### ISSUE THREAD

**Issue by hkernbach** [arangodb/arangodb#1307]
When stopping arangodb instance, a error message appears:

![error_msg_win](https://cloud.githubusercontent.com/assets/1244163/7088757/aa11ba50-df96-11e4-9b74-ba3c3a7ab36d.png)

Used Version:
Windows Server 2012 R2 Datacenter
ArangoDB Version 2.5.1 (exe-installer as service)

**Comment by dothebart** [comment]
couldn't reproduce this on the azure machine; install went flawless, web-page opened.
