### ISSUE TITLE
multi-model Query process

### ISSUE THREAD

**Issue by LilyQahh0208** [arangodb/arangodb#13079]
How does multi-model query processing work?How can queries across models be implemented？Can someone tell me some technical details？

**Comment by Simran-B** [comment]
Short answer: it just works. ArangoDB was designed to support different data models with a single query language from the very beginning. A lot of the complexity that makes this possible is hidden on the surface for ease of use. For example, every record is a JSON object to the user, regardless of the data model.

You can write queries in AQL that retrieve documents based on their ID, which would be a key-value style lookup (the ID being the key and the whole document being that value). If you filter by attribute values, return a subset of stored attributes, compute new attributes or append values to an array in a document, then you are using the document data model. Creating and using edge collections e.g. by doing AQL traversals means that you use the graph data model. You can perform a graph traversal in a subquery and then use that result to iterate over and filter a collections, as well as lookup extra information by key - such a query would involve all three major data models.

Does this answer your question or do you want to know more, e.g. about how the query or storage engine work?

**Comment by maxkernbach** [comment]
Hi @LilyQahh0208,

Did you have a chance to read Simran-B's previous comment? Was it helpful?
