### ISSUE TITLE
Tune query optimizer rules at server level

### ISSUE THREAD

**Issue by matcho** [arangodb/arangodb#13098]
## My Environment

* __ArangoDB Version__:        3.7.3
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   systemd
* __Infrastructure__:               own
* __Operating System__:        Ubuntu 18.04.5 LTS
* __Total RAM in your machine__:        32Gb.
* __Disks in use__:        HDD
* __Used Package__:            Debian or Ubuntu .deb

## This is just a question

Is it possible to tune (disable or force) query optimization rules server-wide, for ex. in `arangod.conf` ? This would be very useful when multiple client libraries, shell users… are accessing the same server.

Context: we're having issues with the new `splice-subqueries` rule that led to a performance drop between 3.4 and 3.7, and we'd like to easily be able to run test sets with and without this optimizer rule − another ticket will follow about this.

Thank you for any advice, or if you plan to integrate this some day.

Greetings,
Mathias

**Comment by jsteemann** [comment]
In 3.7 there is the `--query.optimizer-rules` startup option:

https://github.com/arangodb/arangodb/blob/3.7/CHANGELOG#L2101-L2111

This can also be used via arangod.conf.

**Comment by matcho** [comment]
Great, thank you so much, I totally missed that !
