### ISSUE TITLE
Array functions UNION_DISTINCT and INTERSECT - invalid argument count

### ISSUE THREAD

**Issue by davidmw** [arangodb/arangodb#13103]
## My Environment

* __ArangoDB Version__:       3.7.3
* __Storage Engine__:            RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Infrastructure__:               AWS
* __Operating System__:        Ubuntu 20.04
* __Total RAM in your machine__:      
* __Disks in use__:                  SSD 
* __Used Package__:               Ubuntu .deb 

## Component, Query & Data

__Affected feature__:
AQL query using web interface and arangosh

__AQL query (if applicable)__:
```
LET outerside = (FOR j IN 1..65537
        LET mini = (FOR year IN (1900+RAND() * 100)..(1900+RAND() * 100)
            RETURN year )
        RETURN mini )

RETURN APPLY( "UNION_DISTINCT", outerside 
```

__AQL explain and/or profile (if applicable)__:
EXPLAIN in 3.7.3:
```
Query String (202 chars, cacheable: false):
 LET outerside = (FOR j IN 1..65537
         LET mini = (FOR year IN (1900+RAND() * 100)..(1900+RAND() * 100)
             RETURN year )
         RETURN mini )
 RETURN APPLY( "UNION_DISTINCT", outerside )
 
Execution plan:
 Id   NodeType               Est.   Comment
  1   SingletonNode             1   * ROOT
 14   SubqueryStartNode         1     - LET outerside = ( /* subquery begin */
  3   CalculationNode           1       - LET #8 = 1 .. 65537   /* range */   /* simple expression */
  4   EnumerateListNode     65537       - FOR j IN #8   /* list iteration */
 16   SubqueryStartNode     65537         - LET mini = ( /* subquery begin */
  6   CalculationNode       65537           - LET #10 = (1900 + (RAND() * 100)) .. (1900 + (RAND() * 100))   /* range */   /* simple expression */
  7   EnumerateListNode   6553700           - FOR year IN #10   /* list iteration */
 17   SubqueryEndNode     6553700             - RETURN  year ) /* subquery end */
 15   SubqueryEndNode     6553700         - RETURN  mini ) /* subquery end */
 12   CalculationNode     6553700     - LET #12 = APPLY("UNION_DISTINCT", outerside)   /* simple expression */
 13   ReturnNode          6553700     - RETURN #12

Indexes used:
 none

Functions used:
 Name    Deterministic   Cacheable   Uses V8
 RAND    false           false       false  
 APPLY   false           false       false  

Optimization rules applied:
 Id   RuleName
  1   splice-subqueries
```

EXPLAIN in 3.3.12
```
Query string:
 LET outerside = (FOR j IN 1..65537
         LET mini = (FOR year IN (1900+RAND() * 100)..(1900+RAND() * 100)
             RETURN year )
         RETURN mini )
 RETURN APPLY( "UNION_DISTINCT", outerside )

Execution plan:
 Id   NodeType             Est.   Comment
  1   SingletonNode           1   * ROOT
 11   SubqueryNode            1     - LET outerside = ...   /* subquery */
  2   SingletonNode           1       * ROOT
  3   CalculationNode         1         - LET #8 = 1 .. 65537   /* range */   /* simple expression */
  4   EnumerateListNode   65537         - FOR j IN #8   /* list iteration */
  9   SubqueryNode        65537           - LET mini = ...   /* subquery */
  5   SingletonNode           1             * ROOT
  6   CalculationNode         1               - LET #10 = (1900 + (RAND() * 100)) .. (1900 + (RAND() * 100))   /* range */   /* simple expression */
  7   EnumerateListNode     100               - FOR year IN #10   /* list iteration */
  8   ReturnNode            100                 - RETURN year
 10   ReturnNode          65537           - RETURN mini
 12   CalculationNode         1     - LET #12 = APPLY("UNION_DISTINCT", outerside)   /* v8 expression */
 13   ReturnNode              1     - RETURN #12

Indexes used:
 none

Optimization rules applied:
 none
```

__Problem__:

We have a database configuration script that is run to import data, establish relationships, and to precompute +8000 complex queries that we can regard as static to eliminate runtime delays. Script runs fine in 3.3.12 and fails in 3.7.3.  Both the old and new systems are running RocksDB.

The problem has been traced to array functions like UNION_DISTINCT and INTERSECTION failing due to argument count exceeding 65536. The AQL query above creates 65537 arrays - it functions on 3.3.12 and fails on 3.7.3.  Version 3.3.12 seems to have no argument count limit but can fail spectacularly (server rebooted) after running out of memory at 100k+.

The real query is iterating collections in the outer loops and LIMIT is not useful to break this into chunks. 

__Expected result__:

Update documentation to indicate argument upper limit change.  If this value is configurable, provide instructions.

**Comment by goedderz** [comment]
Hi @davidmw,

thanks, this should probably be added to our documentation.

If it helps, you can rewrite your query like this:

```
RETURN (
  FOR j IN 1..65537
    FOR year IN (1900+RAND() * 100)..(1900+RAND() * 100)
      RETURN DISTINCT year
)
```

This produces the same results, is more efficient, and doesn't have the limit.

It'd be a little bit better even to use

```
FOR j IN 1..65537
  FOR year IN (1900+RAND() * 100)..(1900+RAND() * 100)
    RETURN DISTINCT year
```

, but that changes the form of the result slightly, from e.g. `[ [ 1915, 1916, ... ] ]` to `[ 1915, 1916, ... ]`.

If you need to be more flexible, you can also use `COLLECT` instead of `RETURN DISTINCT`.

HTH

Tobias

**Comment by davidmw** [comment]
Thanks much Tobias. You got me looking for solutions not so dependant on UNION_DISTINCT. I've employed FLATTEN and SORTED_UNIQUE with good result.

```
LET arrayArray = [ [2, 3], [3, 1, 3, 5], [4, 8, 0, 3] ]

//RETURN APPLY( "UNION_DISTINCT", arrayArray )
RETURN SORTED_UNIQUE( FLATTEN( arrayArray ) )
```

**Comment by goedderz** [comment]
Glad I could help!

Note that usually the high-level operations of AQL (like COLLECT) are better suited to process large numbers of documents than AQL functions, so I'd generally still recommend COLLECT (or RETURN DISTINCT) over SORTED_UNIQUE. But if it works well for you, it is, of course, fine. :)
