### ISSUE TITLE
Documentation: Example is not worked for my

### ISSUE THREAD

**Issue by OlafRadicke** [arangodb/arangodb#1310]
Hi!

I experimented with the HTTP/REST-API of arangodb. For tests I used this docker container: https://registry.hub.docker.com/u/frodenas/arangodb/

When I did the command from the documentation (https://github.com/arangodb/arangodb/blob/devel/Documentation/Examples/RestDatabaseCreate.generated) to create a new database, I`ve got no answer from the server:. the comand come not back. It was hanging up:

>  curl -v -u arango:IFFr60y13oxMkdhc -X POST --data-binary @- --dump - http://fuerth.fritz.box:8529/_api/database

I tried some variation but nothing worked:

>  curl -u arango:IFFr60y13oxMkdhc -X POST -d '{ name: "networkcookbook", users: [{  username: "arango", passwd: "IFFr60y13oxMkdhc", active: "true"}] }' http://fuerth.fritz.box:8529/_api/database
> {"error":true,"code":400,"errorNum":400,"errorMessage":"bad parameter"}

and...

> curl -u arango:IFFr60y13oxMkdhc -X POST -d '{ name: "networkcookbook",  username: "arango", passwd: "IFFr60y13oxMkdhc", active: "true" }' http://fuerth.fritz.box:8529/_api/database 
> {"error":true,"code":400,"errorNum":400,"errorMessage":"bad parameter"}

and...

> curl -u arango:IFFr60y13oxMkdhc -X POST -d '{ name: "networkcookbook"}' http://fuerth.fritz.box:8529/_api/database
> {"error":true,"code":400,"errorNum":400,"errorMessage":"bad parameter"}

Is my understanding wrong? Is the documentation wrong? Or is the software broken?

**Comment by OlafRadicke** [comment]
Now I found a way, but it's different of the documentation:

>  curl -u arango:IFFr60y13oxMkdhc -X POST -d '{ "name": "networkcookbook", "users": [{  "username": "cookadmin", "passwd": "IFFr60y13oxMkdhc", "active": "true"}] }' http://fuerth.fritz.box:8529/_api/database
> {"result":true,"error":false,"code":201}

And the next issue is:

> curl -u arango:IFFr60y13oxMkdhc --dump - http://fuerth.fritz.box:8529/_api/database/networkcookbook
> HTTP/1.1 400 Bad Request
> Server: ArangoDB
> Connection: Keep-Alive
> Content-Type: application/json; charset=utf-8
> Content-Length: 71
>
> {"error":true,"code":400,"errorNum":400,"errorMessage":"bad parameter"}

Other try:

> curl -u arango:IFFr60y13oxMkdhc --dump - http://fuerth.fritz.box:8529/_api/databases/networkcookbook
> HTTP/1.1 404 Not Found
> Server: ArangoDB
> Connection: Keep-Alive
> Content-Type: application/json; charset=utf-8
> Content-Length: 103
> 
> {"error":true,"code":404,"errorNum":404,"errorMessage":"unknown path '_api/databases/networkcookbook'"}

Other try:

> curl -u arango:IFFr60y13oxMkdhc --dump -d '{ "name":"networkcookbook"}' http://fuerth.fritz.box:8529/_api/database
> curl: (6) Could not resolve host:  "name"
{"result":["_system","networkcookbook","newrestdb","restdb","testdb"],"error":false,"code":200}

How can I get more information about my new database? I can't fount this in the documentation?

**Comment by neunhoef** [comment]
As far as I know this container image has ArangoDB 2.2 and the published documentation is for V 2.5.

Am 12. April 2015 10:39:33 MESZ, schrieb Olaf Radicke <notifications@github.com>:

**Comment by fceller** [comment]
BTW there is 2.5 available as arangodb/arangodb.

If i do the command from the documentation (https://github.com/arangodb/arangodb/blob/devel/Documentation/Examples/RestDatabaseCreate.generated) to create a new database, i gen no answer from the server:. The comannd cam not back. It's hang up:

    curl -v -u arango:IFFr60y13oxMkdhc -X POST --data-binary @- --dump - http://fuerth.fritz.box:8529/_api/database


"@-" means that you have to enter some more data because your are using a POST request. In the example the additional data is 

    shell> curl -X POST --data-binary @- --dump - http://localhost:8529/_api/database
    {"name":"example"}

So you have to type in the curl command, press RETURN, type in the

    {"name":"example"}

and press CONTROL-D (or CONTROL-Z on Windows).

**Comment by OlafRadicke** [comment]
It is version 2.2.4:

> curl -u arango:IFFr60y13oxMkdhc --dump - http://fuerth.fritz.box:8529/_api/version
> HTTP/1.1 200 OK
> Server: ArangoDB
> Connection: Keep-Alive
> Content-Type: application/json; charset=utf-8
> Content-Length: 37
>
> {"server":"arango","version":"2.2.4"}

in the documentation chaper "HTTP Interface for Databases" section "Address of a Database" it is written:

> Actual URLs in the context of mydb could look like this:
> http://localhost:8529/_db/mydb/_api/version

but it's wrong. For my it's the url http://localhost:8529/_api/version

I use the ebook form of the documentation and there has no version in the title. In the chapter "What's new?"  it's talk a bout 2.5. Okay but i can'd find note about  in (It is version 2.2.4:

> curl -u arango:IFFr60y13oxMkdhc --dump - http://fuerth.fritz.box:8529/_api/version
> HTTP/1.1 200 OK
> Server: ArangoDB
> Connection: Keep-Alive
> Content-Type: application/json; charset=utf-8
> Content-Length: 37
>
> {"server":"arango","version":"2.2.4"}

It is version 2.2.4:

> curl -u arango:IFFr60y13oxMkdhc --dump - http://fuerth.fritz.box:8529/_api/version
> HTTP/1.1 200 OK
> Server: ArangoDB
> Connection: Keep-Alive
> Content-Type: application/json; charset=utf-8
> Content-Length: 37
>
> {"server":"arango","version":"2.2.4"}

in the documentation chaper "HTTP Interface for Databases" section "Address of a Database" it is written:

> Actual URLs in the context of mydb could look like this:
> http://localhost:8529/_db/mydb/_api/version

but it's wrong. For my it's the url http://localhost:8529/_api/version

I use the ebook form of the documentation and there has no version in the title. In the chapter "What's new?"  it's talk a bout 2.5. Okay but i can't find in the changelog  (https://github.com/arangodb/arangodb/blob/devel/CHANGELOG) a note about biger redesign of the HTTP-/REST-API. Is the docker container arangodb/arangodb recommended?

**Comment by neunhoef** [comment]
I am one of the developers of ArangoDB. We publish the docker container arangodb/arangodb ourselves (see download page) and we will always keep it updated with releases. In that sense we recommend it.
You are right, the online version of the manual should state the version it refers to. I will see to it that this is changed.

**Comment by OlafRadicke** [comment]
Now I have run the docker image arangodb/arangodb and here is my feedback:

1.) On site https://registry.hub.docker.com/u/arangodb/arangodb/ I miss a note about the password. No password is not the best option, I think. Remember the MongoDB-Disaster (http://www.heise.de/security/meldung/Studenten-entdecken-Tausende-offene-Firmen-Datenbanken-im-Internet-2545183.html). frodenas/arangodb can show you a better way, in my ace.

2.) On the docker site I can't found the Dockerfile or a link to the sources. So I can't modify the Dockerfile for my use case.

3.) Now I have checked my bash script once more, but the commands in the documentation are not running also. 

here is my code:

> #!/bin/bash
> PASSWORD="IFFr60y13oxMkdhc"
> DBUSER="arango"
> DBSERVER="http://fuerth.fritz.box:8529"
> DATABASE="networkcookbook"
>
> curl -v -u ${DBUSER}:${PASSWORD} -X POST --data-binary @- --dump - ${DBSERVER}/_api/database;
> {"name":"${DATABASE}"};

The script is topping and the prompt don´t come back.

**Comment by fceller** [comment]
2.) The link to the dockerfile has been added to the README:

https://registry.hub.docker.com/u/arangodb/arangodb/

**Comment by fceller** [comment]
1) added a frobnas like passwd generator

**Comment by fceller** [comment]
3) normally the documentation contains a "HERE" but this seems to missing. @13abylon can you check why there are no "HERE" markers on for example

  https://docs.arangodb.com/HttpDocument/WorkingWithDocuments.html

**Comment by fceller** [comment]
1 & 2 are available in the alpha version of 2.6

**Comment by fceller** [comment]
@13abylon any progress on that matter?

**Comment by CoDEmanX** [comment]
> I use the ebook form of the documentation and there has no version in the title.

I noticed this too a few times when I used the epub on smartphone or eBook reader. It would be better if the title was ArangoDB Manual vX.X, and the version and build date should be mentioned on the first page.

**Comment by bubnenkoff** [comment]
Same issue with vibed.org when I am trying to get info about DB:
import vibe.d;
import vibe.core.log;
import vibe.http.client;
import vibe.stream.operations;

void main()
{
		requestHTTP("http://127.0.0.1:8529/",
		//requestHTTP("http://ya.ru",
		(scope req) {
			req.method = HTTPMethod.POST;
			//req.writeJsonBody(["name": "My Name"]);
		},
		(scope res) {
			logInfo("Response: %s", res.bodyReader.readAllUTF8());
		}
	);

Response: {"error":true,"code":400,"errorNum":400,"errorMessage":"bad parameter"}

**Comment by bubnenkoff** [comment]
Could anybody help me? http://stackoverflow.com/questions/31775804/cant-do-test-query-to-arangodb-with-curl

look like curl command hang up

**Comment by jsteemann** [comment]
Question by @bubnenkoff is answered on StackOverflow

**Comment by OlafRadicke** [comment]
So, the answer on stackoverflow show me, that the documentation can be better. 

The way over EOF (https://github.com/arangodb/arangodb/commit/8c65abd0c0bf4cf925b0d836f9589f61713990d8#diff-70c548d5ceda2672058536b377c9320d) okay for my. 

The way with echo and pip is not nice.

But using flag --data-binary and the kickout of '-@' is the best readability way, i think.

**Comment by bubnenkoff** [comment]
I still have problems...
Can I do query like: 
db._query({ "collection": "cars", "skip": 0, "limit" : 1 }) ? Is it's right syntax?

for me work only query in style:
db._query("FOR i IN cars RETURN i.name")

**Comment by dothebart** [comment]
_query() has one mandatory argument: the AQL-query string. It has a second optional argument vector: the options.

**Comment by CoDEmanX** [comment]
@bubnenkoff: you are confusing `/_api/simple/all` of the HTTP interface with `db._query()` of the JS interface.

`{"collection": "cars", "skip": 0, "limit": 1}` is the JSON payload required for a HTTP PUT for the URL `http://host:port/_db/database-name/_api/simple/all`:

```
echo {"collection": "cars", "skip": 0, "limit": 1} | curl -X PUT --data-binary @- http://localhost:8529/_db/test/_api/simple/all
```

To do the same with `db._query()`, you would use AQL and bind parameters:

```
db._query("FOR doc IN @@collection LIMIT 1 RETURN doc", {"@collection": "cars"})
```

BTW: Don't confuse `db._query()` and `/_api/query/`, the latter parses an AQL query and returns an AST, whereas the former returns a query cursor to retrieve documents.
