### ISSUE TITLE
Fulltext search not working on values with underscore or dots

### ISSUE THREAD

**Issue by stdob** [arangodb/arangodb#13138]
## My Environment

* __ArangoDB Version__:        3.7.3, Docker, Ubuntu 20.04

## Query & Data

__AQL query__:
```
FOR doc IN FULLTEXT("test", "type", "problem")
  COLLECT code = doc.type
  RETURN code
```

__Collection__, __Dataset__ & __Indexes__:
```
const test = db.collection("test");

test.ensureIndex({ type : "fulltext", fields: ["type"] });

test.import([
  { type: "problem_show" },
  { type: "problem_graded" },
  { type: "edx.grades.problem.submitted" }
])
```

## Steps to reproduce

1. Create collection, indexes and add data
2. Run AQL query

__Problem__: The query will return only one value:
```
[
  "edx.grades.problem.submitted"
]
```

__Expected result__: But it is expected to return three values (or more - all types that contain **problem**):
```
[
  "edx.grades.problem.submitted",
  "problem_graded",
  "problem_show"
]
```
The number of types including **problem** is unknown in advance.

**Comment by gnusi** [comment]
@stdob that's due to dots are considered as delimiters. Please consider using Arangosearch instead of full-text index.

**Comment by Simran-B** [comment]
Do you want to search for full words (e.g. problem, graded, show), prefixes of these words (probl, grad, sho) or for suffixes / arbitrary substrings (oble, rade, how)?

**Comment by stdob** [comment]
@Simran-B 
> Do you want to search for full words (e.g. problem, graded, show), prefixes of these words (probl, grad, sho) or for suffixes / arbitrary substrings (oble, rade, how)?

I have many types of events. In different situations, I need to search either by different parts of a word or the whole word. For example, these different search options:

- problem
- problem_graded
- submitted
- edx.grades

and etc.

**Comment by stdob** [comment]
@gnusi 
> @stdob that's due to dots are considered as delimiters. Please consider using Arangosearch instead of full-text index.

Ok, thanks, I'll try.

**Comment by Simran-B** [comment]
Based on your description, you should probably combine an n-gram Analyzer with a View to enable index-accelerated substring matching. That will keep all characters as-is, unlike the tokenizing Analyzers such as `text_en`. Just make sure you set the `streamType` to `utf8`: https://www.arangodb.com/docs/stable/arangosearch-analyzers.html#n-gram

**Comment by maxkernbach** [comment]
Hi @stdob,

Did you already have a chance to test the suggestions?

**Comment by stdob** [comment]
Hi @maxkernbach,

I try. Unfortunately, I cannot understand how to set `streamType` to `utf8` and use `n-gram` by the advice of [@Simran-B](https://github.com/arangodb/arangodb/issues/13138#issuecomment-747064050).

I think I need to dig into the documentation ))

> Did you already have a chance to test the suggestions?

**Comment by Simran-B** [comment]
Create a trigram Analyzer in arangosh:

```js
var analyzers = require("@arangodb/analyzers");
analyzers.save("trigrams", "ngram", { min: 3, max: 3, preserveOriginal: false, streamType: "utf8" }, ["frequency", "norm", "position"]);
```

Example of tokens it produces:

```js
db._query(`RETURN TOKENS("edx.grades", "trigrams")`);
/* result:
[
  [
    "edx",
    "dx.",
    "x.g",
    ".gr",
    "gra",
    "rad",
    "ade",
    "des"
  ]
]
*/
```

It's fairly difficult to get this to work in the way you want however. I would actually recommend something else on second thought, even if it's slower:

`SEARCH LIKE(doc.field, "%phras_")`, where `%` stands for zero or more arbitrary characters and `_` for a single wildcard character. To search for the substring `_gra` you need to escape the underscore, i.e. `\\_gra` in the Web UI or `\\\\_gra` in arangosh. In your View, make sure that the field is indexed somehow, the identity Analyzer suffices. This ensures that the term dictionary required for the LIKE() search is generated internally.

**Comment by stdob** [comment]
@Simran-B 

Thanks for the example. I will experiment further. 

Of course, it's a pity that everything is not so simple (as in the same neo4j). 

I think that issue can be closed.
