### ISSUE TITLE
Can't activate Web Interface

### ISSUE THREAD

**Issue by codewithpatelo** [arangodb/arangodb#13131]
## My Environment

* __ArangoDB Version__:        Version 0.14.15, build e32307e, Go go1.13.6
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Arangodb as a systemd service on host network
* __Infrastructure__:               AWS EC2 t2.medium
* __Operating System__:        Amazon Linux
* __Total RAM in your machine__:        4GB
* __Disks in use__:        Around 4 GBs
* __Used Package__:             yum

## Component, Query & Data

__Affected feature__:
Arango Web Interface

## Steps to reproduce

1. Install arangodb on those specs
2.  Run arangodb
3.  Enter to http://AWSipofEC2instance:8529 and nothing happens (Even with security groups configured for this port).

__Problem__:

Can't access to Arango server built-in web interface. (The rest works fine).

__Expected result__:
Going to http://AWSipofEC2instance:8529 and be approached with the web interface login.

**Comment by dothebart** [comment]
Hi, 
did you make sure that you can resolve this DNS-Entry from the host your webbrowser runs on? Else you need to look up the IP on the remote host, and use this in your browser.

**Comment by codewithpatelo** [comment]
> Hi,
> did you make sure that you can resolve this DNS-Entry from the host your webbrowser runs on? Else you need to look up the IP on the remote host, and use this in your browser.

The EC2 instance I'm using it is not attached to any domain in particular so I'm directly trying to reach the web interface via its public IP. The security groups of this instance are set in such a way that the port 8529 is opened, so even in any device I should be able to get there. (Other ports opened work fine, ex 3000 which I use for some front-end).

I already set up another EC2 instance with arango, and for some reason there works fine (same security group configuration-- even stricter), so I was wondering if there a part of arangod config that is disabling the web interface.

**Comment by dothebart** [comment]
You can use `telnet` or `netcat` to check whether you're able to talk to the process inside at all and can rule out any possible workarounds inside the big browser thing that obstruct your view to the error. 

If you can establish the connection, i.e. proxy configurations in your browser may be whats in your way? 
 
Tcp-Traceroute can also be used to check for connectivity on ports.

**Comment by codewithpatelo** [comment]
![image](https://user-images.githubusercontent.com/16574952/100917083-6d281380-34b5-11eb-8f22-856ab8319486.png) output of netstat -alnpt

![image](https://user-images.githubusercontent.com/16574952/100917660-343c6e80-34b6-11eb-92f2-c8e573b2a794.png)
 output of nc -v -n theipofawsinstance 8529

I use in fact the exactly the same security groups of another instance which I can log-in to the web interface of Arango.

**Comment by codewithpatelo** [comment]
Solution:

You have to configure arangod's endpoint to your server api, available networks or hostname.

`Sudo /etc/arangodb3`
`Sudo nano arangod.conf`

Then set tcp://0.0.0.0:8529 as endpoints (available networks for host).

Then restart arangodb3 service (`sudo systemctl restart arangodb3`).

Worked for me that way.

**Comment by dothebart** [comment]
Thanks for providing the solution you found - no Denver Coder in this issue ;)
