### ISSUE TITLE
maxRuntime does not really kill certain queries

### ISSUE THREAD

**Issue by matcho** [arangodb/arangodb#13141]
## My Environment

* __ArangoDB Version__:        3.7.3
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   systemd
* __Infrastructure__:               own
* __Operating System__:        Ubuntu 20.04.1 LTS
* __Total RAM in your machine__:        64Gb.
* __Disks in use__:        SSD
* __Used Package__:            Debian or Ubuntu .deb

## Component, Query & Data

__Affected feature__:
AQL query with arangosh, using `maxRuntime` option

__AQL query__:
```
FOR q IN queries FILTER q._couchdoc RETURN q._key
```
__AQL explain__:
```
 FOR q IN queries FILTER q._couchdoc RETURN q._key

Execution plan:
 Id   NodeType                       Est.   Comment
  1   SingletonNode                     1   * ROOT
  2   EnumerateCollectionNode   260323174     - FOR q IN queries   /* full collection scan, projections: `_key`, `_couchdoc` */   FILTER q.`_couchdoc`   /* early pruning */
  5   CalculationNode           260323174       - LET #3 = q.`_key`   /* attribute expression */   /* collections used: q : queries */
  6   ReturnNode                260323174       - RETURN #3

Indexes used:
 none

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   move-calculations-up-2
  4   move-filters-up-2
  5   reduce-extraction-to-projection
  6   move-filters-into-enumerate
```

__Dataset__:
A collection of ~260 millions docs, with no index on the field that is filtered in this query; this is on purpose, to test `maxRuntime` option.

__Size of your Dataset on disk__:
~350 GB for this collection

## Steps to reproduce

1. try the example given in #6146 : query is killed after 5s, as expected
```
127.0.0.1:8529@mydb> db._query("LET x = SLEEP(10) RETURN 1", {} /*bind*/, { maxRuntime : 5} /*options*/);
JavaScript exception in file '/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js' at 99,7: ArangoError 1500: AQL: query killed (while executing)
!      throw error;
!      ^
stacktrace: ArangoError: AQL: query killed (while executing)
    at Object.exports.checkRequestResult (/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js:97:21)
    at ArangoStatement.execute (/usr/share/arangodb3/js/client/modules/@arangodb/arango-statement.js:172:12)
    at Proxy.ArangoDatabase._query (/usr/share/arangodb3/js/client/modules/@arangodb/arango-database.js:957:45)
    at <shell command>:1:4
```
2. try the same syntax, with the query described above : shell does not return, have to Ctrl+C
```
127.0.0.1:8529@mydb> db._query("FOR q IN queries FILTER q._couchdoc RETURN q._key", {} /*bind*/, { maxRuntime : 5} /*options*/);

^Ccommand locally aborted
```
3. check running queries on the server, query above is still running (although in "killed" state)
```
127.0.0.1:8529@mydb> require("@arangodb/aql/queries").current();
[ 
{ 
    "id" : "13297514267", 
    "database" : "mydb", 
    "user" : "mydb", 
    "query" : "FOR q IN queries FILTER q._couchdoc RETURN q._key", 
    "bindVars" : { 
    }, 
    "started" : "2020-12-04T09:36:21Z", 
    "runTime" : 3488.4404474500043, 
    "state" : "killed", 
    "stream" : false 
  }
]
```

__Problem__:
The query executed here is voluntarily a "naïve" query. We would like to use `maxRuntime` option precisely to prevent potential slow queries, in case our application code erroneously generates a query without index for example, in order to avoid heavy load on the server.

The query does not stop but is marked as "killed". I guess the `maxRuntime` option worked and triggered a "kill" signal. But as the query is actually not removed from the list, I guess it is still generating load ?

Does the "kill" fails because a query can only be killed between to steps of the execution plan ? This would make the `maxRuntime` option far less useful, at least in our case…

__Expected result__:
The query is almost instantly killed and removed from currently running queries list.

Thank you for any advice,
All the best,

Mathias

**Comment by goedderz** [comment]
Hi @matcho,

first note a query will not be killed instantly, this is expected behaviour, as documented under [Limiting query runtime](https://www.arangodb.com/docs/stable/programs-arangod-query.html#limiting-query-runtime). Rather it will be checked at certain points whether the query was killed, and then aborted.

That being said, it should usually still happen very fast, and I think it should in this case as well. I can reproduce it and will see how to fix it.

If you need a workaround, turn off the optimizer rule `move-filters-into-enumerate`, i.e. pass `{maxRuntime: 5, optimizer: {rules: ['-move-filters-into-enumerate']}}` as options.

Tobias

**Comment by matcho** [comment]
Hi @goedderz 

The optimizer trick works, thank you very much ! This is great news.

Does disabling `move-filters-into-enumerate` has performance impact ?

Thanks,
Mathias

**Comment by goedderz** [comment]
Hi @matcho,

yes, it does, the query has to do more work of copying documents around. The query will execute slower without it.

Best

Tobias

**Comment by goedderz** [comment]
Hi @matcho,

just fyi: We have a working fix that is already merge into our development branch. I don't yet know whether the fix will make it into v3.7.5, or will only make it until v3.7.6.

**Comment by maxkernbach** [comment]
Hi @matcho,

In the meantime version 3.7.6, which includes a fix for this issue, has been released.

From the [Changelog](https://github.com/arangodb/arangodb/blob/c1870605e02b73f6d45f6e5431a6e2a610f098a2/CHANGELOG#L112):

> * Add an AQL query kill check during early pruning. Fixes issue #13141.

In case your query still can't be properly killed, please comment.

**Comment by matcho** [comment]
It works ! Amazing <3

**Comment by matcho** [comment]
And… oops :/ actually it does not. I forgot to remove `move-filters-into-enumerate` :( Deeply sorry for this !

Same problem as before: query is in "killed" state but does not terminate.

**Comment by maxkernbach** [comment]
Oh, that is unfortunate, but thanks for letting us know.

@goedderz FYI

**Comment by goedderz** [comment]
@matcho can you please verify that you tried this with v3.7.6? Is the query the same, does it not terminate at all, and is it still the case that after disabling the rule `move-filters-into-enumerate` it behaves as expected?

**Comment by matcho** [comment]
@goedderz Checked, most of what you said is true : v3.7.6, same query, behaves as expected when disabling `move-filters-into-enumerate`.

Regarding "does not terminate at all", actually I don't know because this query takes a very long time to complete… I ran it in arangosh and waited for it to say something, and it eventually said "query timeout" in the shell (maybe after 1h, didn't check the settings). When I looked at the query state after this, the query had disappeared. Hard to say if it was killed by the timeout, or killed before, due to the "killed state" it had since the 20 first seconds and the query entering another stage of execution maybe ? I'll try to take a closer look.

Another info that might be interesting is: when running the same query (filter on a non-indexed field, return keys) on a smaller but still large collection (9M docs), query is killed as expected ! I can post more details about that if you wish.

Here's exactly what happened with the usual query:

```
                                       _     
  __ _ _ __ __ _ _ __   __ _  ___  ___| |__  
 / _` | '__/ _` | '_ \ / _` |/ _ \/ __| '_ \ 
| (_| | | | (_| | | | | (_| | (_) \__ \ | | |
 \__,_|_|  \__,_|_| |_|\__, |\___/|___/_| |_|
                       |___/                 

arangosh (ArangoDB 3.7.6 [linux] 64bit, using jemalloc, build tags/v3.7.6-0-g780ac0e127, VPack 0.1.33, RocksDB 6.8.0, ICU 64.2, V8 7.9.317, OpenSSL 1.1.1i  8 Dec 2020)
Copyright (c) ArangoDB GmbH

Command-line history will be persisted when the shell is exited. You can use `--console.history false` to turn this off
Connected to ArangoDB 'http+tcp://127.0.0.1:8529, version: 3.7.6 [SINGLE, server], database: 'mydb', username: 'myuser'

Type 'tutorial' for a tutorial or 'help' to see common examples

127.0.0.1:8529@mydb> db._query("FOR q IN queries FILTER q._couchdoc RETURN q._key", {}, { maxRuntime : 20 });
```
Command does not return after around 40s so Ctrl+C
```
^Ccommand locally aborted


127.0.0.1:8529@mydb> require("@arangodb/aql/queries").current();
[ 
  { 
    "id" : "13726330074", 
    "database" : "mydb", 
    "user" : "mydb", 
    "query" : "FOR q IN queries FILTER q._couchdoc RETURN q._key", 
    "bindVars" : { 
    }, 
    "started" : "2021-01-15T10:32:55Z", 
    "runTime" : 40.910242664998805, 
    "state" : "killed", 
    "stream" : false 
  } 
]

127.0.0.1:8529@mydb> db._query("FOR q IN queries FILTER q._couchdoc RETURN q._key", {}, { maxRuntime : 20, optimizer: {rules: ['-move-filters-into-enumerate']} });
JavaScript exception in file '/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js' at 99,7: ArangoError 1500: AQL: query killed (while executing)
!      throw error;
!      ^
stacktrace: ArangoError: AQL: query killed (while executing)
    at Object.exports.checkRequestResult (/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js:97:21)
    at ArangoStatement.execute (/usr/share/arangodb3/js/client/modules/@arangodb/arango-statement.js:172:12)
    at Proxy.ArangoDatabase._query (/usr/share/arangodb3/js/client/modules/@arangodb/arango-database.js:957:45)
    at <shell command>:1:4


127.0.0.1:8529@mydb> require("@arangodb/aql/queries").current();
[ 
  { 
    "id" : "13726330074", 
    "database" : "mydb", 
    "user" : "mydb", 
    "query" : "FOR q IN queries FILTER q._couchdoc RETURN q._key", 
    "bindVars" : { 
    }, 
    "started" : "2021-01-15T10:32:55Z", 
    "runTime" : 120.8928715029997, 
    "state" : "killed", 
    "stream" : false 
  } 
]

127.0.0.1:8529@mydb>
```

The "ArangoError 1500: AQL: query killed (while executing)" happened exactly after 20s as expected.

Thank you very much for following this case.
All the best,
Mathias

**Comment by goedderz** [comment]
Hi @matcho,

thanks for your help!

> Another info that might be interesting is: when running the same query (filter on a non-indexed field, return keys) on a smaller but still large collection (9M docs), query is killed as expected ! I can post more details about that if you wish.

That is indeed helpful. It seems to indicate that the fix worked, but doesn't address all cases. I have an idea where to look and will keep you posted.

Best,

Tobias

**Comment by goedderz** [comment]
Hi @matcho,

I've added a small change that should hopefully fix the remaining case as well: https://github.com/arangodb/arangodb/pull/13527

It will most probably make it into 3.7.8.

Best,

Tobias

**Comment by matcho** [comment]
Hi @goedderz 

Thanks a lot, looking forward to try it !

Mathias

**Comment by matcho** [comment]
Hi @goedderz 

Just installed v3.7.9, and it works. For real. Thank you so much !

```
localhost:8529@mydb> db._query("FOR q IN queries FILTER q._couchdoc RETURN q._key", {}, { maxRuntime : 20 });
JavaScript exception in file '/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js' at 99,7: ArangoError 1500: AQL: query killed (while executing)
!      throw error;
!      ^
stacktrace: ArangoError: AQL: query killed (while executing)
    at Object.exports.checkRequestResult (/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js:97:21)
    at ArangoStatement.execute (/usr/share/arangodb3/js/client/modules/@arangodb/arango-statement.js:172:12)
    at Proxy.ArangoDatabase._query (/usr/share/arangodb3/js/client/modules/@arangodb/arango-database.js:957:45)
    at <shell command>:1:4


localhost:8529@mydb> 
localhost:8529@mydb> 
localhost:8529@mydb> require("@arangodb/aql/queries").current();
[ ]

localhost:8529@mydb>
```

All the best,
Mathias

**Comment by goedderz** [comment]
I'm glad we could resolve this. Thanks for your help!

Best,

Tobias
