### ISSUE TITLE
Critical. Arangodb RocksDB producing way too many temporal files. How do I limit this?

### ISSUE THREAD

**Issue by codewithpatelo** [arangodb/arangodb#13154]
## My Environment

* __ArangoDB Version__:        3.7.3
* __Storage Engine__:             RocksDB  rocksdb-version: 6.8.0
* __Deployment Mode__:       Single server

* __Infrastructure__:               AWS EC2 t2.large
* __Operating System__:        Amazon Linux
* __Total RAM in your machine__:        8gb
* __Disks in use__:        Well, it got dangerously to 100%,. More than 40gbs in dbtmp files.
* __Used Package__:          yum

## Component, Query & Data

__Affected feature__:
ArangoDB RocksDB

__Size of your Dataset on disk__:
The compressed dump is around 32M.

## Steps to reproduce

1. Install arangodb at AWS EC2 instance (t2.large)
2.  Configure arangod to connect to endpoint from another EC2 instance (t2.medium)
3.  Configure backup script to dump db twice a day.
4.  Get the script running via crontab

__Problem__:
I run the exactly same backup script at two instances. One who host the db (around 15 gbs disk volume space) and another one who connects to that host to do that backups as it has much more space. (+40gbs).

I got surprised when the instance with larger volume got suddenly and dangerously fulled.

Backup script:
![image](https://user-images.githubusercontent.com/16574952/101336939-d0b99480-3859-11eb-8139-ac2feaf7acfb.png)

Crontab config:
![image](https://user-images.githubusercontent.com/16574952/101336828-aff13f00-3859-11eb-93aa-676665a23ad1.png)

The output of the script is a tar file which is around 32M each.

![image](https://user-images.githubusercontent.com/16574952/101337570-97355900-385a-11eb-81ec-3c27575d2e37.png)

So, given that (A) both instances are doing twice backups in a day but only one get full (and rarely the one with massively much more space) and (B) the dump isn't that big to full such space it doesn't add up that the dump is the problem.

When I used `df -h` the disk got **100% full** (+40gbs), but the application running is no way that big. So I used `sudo du -sh /var` to find where was that massive amount of data generated.

By iterating ls and sudo du... I got to discover that the problem was in directory /var/lib/arangodb3/engine-rocksdb

And the files causing the problem were **dbtmp** ones. **How do I prevent RockDB to overload my volume with these files? Is there any specific configuration?**

__Expected result__:
Getting RockDB configured to prevent generating tmps files when surpassing certain threshold of disk usage.

**Comment by dothebart** [comment]
Hi, 
please note that rocksdb does a "compaction" where it puts those files together. This compaction *requires (!) additional (!) diskspace* in order to work, since it will grab still needed data from the old files, and combine it into a new one. 

If you want to reduce write / erase / update load on the DB, you could disable the statistics of the server. https://www.arangodb.com/docs/stable/tutorials-reduce-memory-footprint.html#statistics (this will disable the graphs that you see on the login screen in the webinterface)

The only way to manually trigger the rocksdb compaction is atm to truncate a collection. So you could use this to trigger a compaction before you do the backup.

**Comment by codewithpatelo** [comment]
I see, I'll definitely try with that. However, I'm surprised that I only got the problem in one the instances for some reason (and it was the one with larger volume)  but not the other even if I used RockDB default's configuration. Maybe it was a different v of RDB?

**Comment by dothebart** [comment]
I think we had different issues that hinted that the compaction wasn't invoked frequently enough under some circumstances; Hence it was added to `truncate`.

**Comment by codewithpatelo** [comment]
I don't know whether is useful for the diagnosis, but apart from the dbtmp files I've seen .logs file making up space.

**Comment by Simran-B** [comment]
We introduced a method in the JS API fairly recently to start a compaction manually:
https://www.arangodb.com/docs/stable/data-modeling-databases-working-with.html#compact

**Comment by codewithpatelo** [comment]
> We introduced a method in the JS API fairly recently to start a compaction manually:
> https://www.arangodb.com/docs/stable/data-modeling-databases-working-with.html#compact

I use arangojs in the API of the application. How and when should I use the compact function?

**Comment by maxkernbach** [comment]
Hi @codewithpatelo,

For now, could you please try to run the compaction once manually via `arangosh` and let us know whether this reduces the size?

**Comment by maxkernbach** [comment]
Hi @codewithpatelo,

Are you still facing this issue, did you have a chance to run the compaction manually?

**Comment by Simran-B** [comment]
Possibly related to #13100 (but the other issue is about Windows).

**Comment by codewithpatelo** [comment]
I don't have this issue anymore. I think I reinstalled arangodb back then and it worked.

**Comment by dothebart** [comment]
if the issue re-arises please post the output of:
```
lsof |grep arangod
```
Usually this should only show the database files, which *can* be many.
