### ISSUE TITLE
Batch imports behave unexpectedly with ongoing streaming transaction

### ISSUE THREAD

**Issue by robross0606** [arangodb/arangodb#13159]
## My Environment

* __ArangoDB Version__:        3.7.3
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   ArangoDB Starter in Docker
* __Configuration__:               N/A
* __Infrastructure__:               Docker Desktop
* __Operating System__:        WSL2 on Windows 10
* __Total RAM in your machine__:        24GB in WSL2 container
* __Disks in use__:        SSD
* __Used Package__:              Docker - official Docker library

## Component, Query & Data

__Affected feature__:
Transactions and batch imports through ArangoJS driver.

## Steps to reproduce

1. Start a streaming transaction.
2. Create a source document inside the streaming transaction.
3. Create a target document inside the streaming transaction.
4. Import 3 edges between the two endpoint documents. This should be outside the transaction because import calls are supposedly not transactional.
5. Abort the transaction.
6. Manually look at the database content.

__Problem__:
I would expect the edge import to fail because the referenced `_from` and `_to` documents were not committed prior to creating the edges outside the transaction. In fact, they were never committed and instead aborted.  What happens instead is the activity "succeeds". What is left in the database is 0 documents and 3 edges. The documents were rolled back while the edges were left. Even if I abort the transaction _before_ importing the edges, this succeeds and points to bogus endpoints that do not exist.  This is even true with the `waitForSync` option enabled.  However, if I just try to create edges without ever creating the endpoint documents, the edge import fails with an error `edge attribute missing or invalid`.  So Arango appears appears to somehow consider the transactional documents because clearly they're validating against IDs to some degree. 

__Expected result__:
I would expect the import itself to fail because those documents were not committed prior to creating the edges outside the transaction. In fact, they were never committed and instead aborted.

**Comment by robross0606** [comment]
Or is there just no validation at all on `_from` and `_to` IDs for edge imports?

**Comment by goedderz** [comment]
Unless you're using the gharial API, there are no checks done for edges whether the vertices exist or not. It is only checked that both `_from` and `_to` are there, and are in the right format. So it sounds like maybe you're not setting those correctly, if you don't create the vertices first. Maybe you're taking the auto-generated keys from the documents, which are just empty in that case?

**Comment by robross0606** [comment]
Yes, I realized later yesterday that there is no validation and the keys had a bogus character in them.
