### ISSUE TITLE
Is it possible to execute a LEFT join query in Arangodb's AQL?

### ISSUE THREAD

**Issue by codewithpatelo** [arangodb/arangodb#13150]
## My Environment

* __ArangoDB Version__:        Version 0.14.15, build e32307e, Go go1.13.6
* __Storage Engine__:           Single Server
* __Deployment Mode__:       Arangodb as a systemd service on host network
* __Deployment Strategy__:   AWS EC2 t2.large

## Component, Query & Data

__Affected feature__:
AQL

__AQL query (if applicable)__:
```
FOR A in employees_admins
  FOR E in employees
   FOR R in regions
    FOR C in countries
   FILTER A.emp_rgn_adm_emp_nbr == E.emp_nbr 
  FILTER A.emp_rgn_adm_rgn_cd == R.region_cd
   FILTER C.ctry_cd == A.emp_rgn_adm_ctry_cd 

LET X = MERGE (A,E,R,C) SORT E.emp_lst_nm DESC RETURN X 

```

 

__Problem__:

When I use merge all joins are INNER joins, but I need some of them to be LEFT joins. I don't know how to do it with AQL.

Ex: 
```
FOR A in employees_admins
  FOR E in employees
   FOR R in regions
    FOR C in countries
   FILTER A.emp_rgn_adm_emp_nbr == E.emp_nbr (Should be INNER JOIN)
  FILTER A.emp_rgn_adm_rgn_cd == R.region_cd (Should be LEFT JOIN)
   FILTER C.ctry_cd == A.emp_rgn_adm_ctry_cd (Should be LEFT JOIN)

LET X = MERGE (A,E,R,C) SORT E.emp_lst_nm  DESC RETURN X 
```

**Comment by codewithpatelo** [comment]
I think I solved it by doing:

FOR A in employees_admins
  FOR E in employees
   FOR R in regions
    FOR C in countries
   FILTER A.emp_rgn_adm_emp_nbr == E.emp_nbr 
  FILTER A.emp_rgn_adm_rgn_cd == R.region_cd || C.ctry_cd == A.emp_rgn_adm_ctry_cd 

LET X = MERGE (A,E,R,C) SORT X.emp_lst_nm DESC RETURN X

**Comment by codewithpatelo** [comment]
Definitive solution:

```
FOR A in employees_admins
  FOR E in employees
   FOR R in regions
    FOR C in countries
   FILTER A.emp_rgn_adm_emp_nbr == E.emp_nbr 
  FILTER A.emp_rgn_adm_rgn_cd == R.region_cd || C.ctry_cd == A.emp_rgn_adm_ctry_cd 

LET X = MERGE (A,E,R,C) FILTER X.ctry_cd == X.emp_ctry_cd SORT X.emp_lst_nm DESC RETURN X
```

**Comment by codewithpatelo** [comment]
Well, I actually almost go it. I got the result query I wanted except there are unnecessary registries. What I need is to set some constrain in which emp_rgn_adm_nbr can't have any duplicates. How do I do that?

![image](https://user-images.githubusercontent.com/16574952/101268313-4cbfb980-3740-11eb-9dc8-ae9fcf2963eb.png)

**Comment by dothebart** [comment]
Hi, did you try collect?

**Comment by Simran-B** [comment]
If entire "rows" are identical, then you may also use `RETURN DISTINCT`.

**Comment by codewithpatelo** [comment]
> Hi, did you try collect?

Could you please provide an example?

**Comment by codewithpatelo** [comment]
> If entire "rows" are identical, then you may also use `RETURN DISTINCT`.

I tried with RETURN DISTINCT, the problem with that aql function is that I can only use it with a single collection's value but not for various merge values where I can specified which one should be the one with no-duplicates constrains.

https://www.arangodb.com/2015/07/return-distinct-in-aql/

As @dothebart said before, COLLECT seems appropriate, but I'm unsure how to write the right syntax of it for my query requirements.

**Comment by Simran-B** [comment]
`RETURN DISTINCT` can be used for any single value. This can also be an object/document:

```
FOR doc IN coll
  FOR doc2 IN coll
    FOR doc3 IN coll
        RETURN DISTINCT doc
```

It returns each document once, e.g. 2 documents if there are 2 documents in coll. Without DISTINCT it would return each document 4 times, 8 in total.

You should be able to do this:

```
FOR A in employees_admins
  FOR E in employees
    FOR R in regions
      FOR C in countries
        FILTER A.emp_rgn_adm_emp_nbr == E.emp_nbr
        FILTER A.emp_rgn_adm_rgn_cd == R.region_cd || C.ctry_cd == A.emp_rgn_adm_ctry_cd
        LET X = MERGE (A,E,R,C) FILTER (X.emp_rgn_adm_rgn_cd == X.ctry_rgn_cd || X.ctry_rgn_cd == X.region_cd) && ((!X.emp_rgn_adm_rgn_cd && X.emp_rgn_adm_ctry_cd) || (X.emp_rgn_adm_rgn_cd && !X.emp_rgn_adm_ctry_cd))
        RETURN DISTINCT X
```

If there's more query after LET X that prevents a RETURN operation, then you can turn this part into a subquery, like:

```
LET x = ( FOR A in employees_admins ... RETURN DISTINCT X)
...
RETURN x
```

Assuming that each row of the intermediate result is identical, COLLECT would be pretty straightforward:

```
LET X = ...
COLLECT x = X
RETURN x
```

**Comment by maxkernbach** [comment]
Hi @codewithpatelo,

Did you have a chance to check Simran-B's previous comment?
