### ISSUE TITLE
Version '2.5.2' for 'arangodb:i386' was not found

### ISSUE THREAD

**Issue by sbakiu** [arangodb/arangodb#1317]
I am getting `Version '2.5.2' for 'arangodb:i386' was not found` error when downloading ArangoDB for Ubuntu 14.04.

**Comment by jsteemann** [comment]
How are you downloading that package? 

I just tried it manually by going to the website (https://www.arangodb.com/download/, **Download** tab), selecting Ubuntu and then downloading the 14.04 package for i386. This seems to download fine.

Here's the direct link for the package:
https://www.arangodb.com/repositories/arangodb2/xUbuntu_14.04/i386/arangodb_2.5.2_i386.deb

Did you try to install it by another other means?

**Comment by sbakiu** [comment]
I was trying to use `apt-get`

**Comment by jsteemann** [comment]
I can see the i386 version of 2.5.2 is online so I am a bit surprised it doesn't download.
Can you confirm the `sources.list` on your system is up-to-date? The file `/etc/apt/sources.list.d/arangodb.list` should contain the following line:
```
deb https://www.arangodb.com/repositories/arangodb2/xUbuntu_14.04/ /
```

**Comment by sbakiu** [comment]
Now it is working. I cannot really tell what was happening on Friday but today it seems to be fine. I will close the issue.

**Comment by jsteemann** [comment]
Maybe it wasn't there on Friday and the version got uploaded by now. I really don't know, but I am glad it works now.
