### ISSUE TITLE
Schema validation fails if inserting document with null

### ISSUE THREAD

**Issue by SimonasTr** [arangodb/arangodb#13173]
## Schema rules:
```
{'rule': {'properties': {'test_field': {'type': 'string'}},
          'level': 'strict',
          'message': 'SchemaValidationError - test_col'}
```

## Insert query
```
// Does not work
INSERT {
  '_key': '1234',
  'test_field':  null
} INTO test_col OPTIONS { keepNull: false }

// Does work
INSERT {
  '_key': '1234'
} INTO test_col OPTIONS { keepNull: false }
```

## Steps to reproduce

1.  Define schema for some collection with some field, e.g. `string` type.
2.  Try to insert document that has null in the field into that collection (set option to keepNull = False)
3.  Enjoy error.

__Problem__:
keepNull does not seem to work when schema validation is set.

__Expected result__:
null value keys are ignore and the document is successfully inserted.

Am I missing something?

**Comment by jsteemann** [comment]
`keepNull` only has an effect for UPDATE operations (plus, to be precise, for INSERT operations with `OPTIONS { overwriteMode: "update" }` set - that option will turn the insert operation into an update operation in case the target `_key` already exists).

Outside of UPDATE operations, specifying the `keepNull` is ignored and has no effect.
