### ISSUE TITLE
Geo index is not used when GEO_DISTANCE is compared with a stored value

### ISSUE THREAD

**Issue by AntoineAA** [arangodb/arangodb#13185]
## My Environment

* __ArangoDB Version__:        3.7.3
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:    systemd
* __Configuration__:               `optimizer-rules = -splice-subqueries` in arangod.conf
* __Infrastructure__:               own
* __Operating System__:        Ubuntu 18.04
* __Total RAM in your machine__:        126Gb
* __Disks in use__:        HDD
* __Used Package__:              Debian or Ubuntu .deb

## Component, Query & Data

__Affected feature__:
AQL query using web interface (index not used)

__AQL query (if applicable)__:
Query 1
```
for m in z_monitoring
    for c in m.polygons
    	 for o in z_obs
    	    filter GEO_DISTANCE([c.lon, c.lat], [o.geoloc.lon, o.geoloc.lat]) < c.radius
    	       collect with count into c return c
```

Query 2
```
for m in z_monitoring
    for c in m.polygons
    	 for o in z_obs
    	    filter GEO_DISTANCE([c.lon, c.lat], [o.geoloc.lon, o.geoloc.lat]) < 100000
    	       collect with count into c return c
```
__AQL explain and/or profile (if applicable)__:
Query 1
```
Query String (199 chars, cacheable: true):
 for m in z_monitoring
     for c in m.polygons
     	 for o in z_obs
     	    filter GEO_DISTANCE([c.lon, c.lat], [o.geoloc.lon, o.geoloc.lat]) < c.radius
     	       collect with count into c return c

Execution plan:
 Id   NodeType                       Est.   Comment
  1   SingletonNode                     1   * ROOT
  2   EnumerateCollectionNode           1     - FOR m IN z_monitoring   /* full collection scan, projections: `polygons` */
  3   CalculationNode                   1       - LET #4 = m.`polygons`   /* attribute expression */   /* collections used: m : z_monitoring */
  4   EnumerateListNode               100       - FOR c IN #4   /* list iteration */
  5   EnumerateCollectionNode   297818200         - FOR o IN z_obs   /* full collection scan, projections: `geoloc` */
  6   CalculationNode           297818200           - LET #6 = (c.`radius` > GEO_DISTANCE([ c.`lon`, c.`lat` ], [ o.`geoloc`.`lon`, o.`geoloc`.`lat` ]))   /* simple expression */   /* collections used: o : z_obs */
  7   FilterNode                297818200           - FILTER #6
  8   CollectNode                       1           - COLLECT  WITH COUNT INTO c   /* count */
  9   ReturnNode                        1           - RETURN c

Indexes used:
 none

Functions used:
 Name           Deterministic   Cacheable   Uses V8
 GEO_DISTANCE   true            true        false  

Optimization rules applied:
 Id   RuleName
  1   reduce-extraction-to-projection
```

Query 2
```
Query String (197 chars, cacheable: true):
 for m in z_monitoring
     for c in m.polygons
     	 for o in z_obs
     	    filter GEO_DISTANCE([c.lon, c.lat], [o.geoloc.lon, o.geoloc.lat]) < 100000
     	       collect with count into c return c

Execution plan:
 Id   NodeType                       Est.   Comment
  1   SingletonNode                     1   * ROOT
  2   EnumerateCollectionNode           1     - FOR m IN z_monitoring   /* full collection scan, projections: `polygons` */
  3   CalculationNode                   1       - LET #4 = m.`polygons`   /* attribute expression */   /* collections used: m : z_monitoring */
  4   EnumerateListNode               100       - FOR c IN #4   /* list iteration */
 10   IndexNode                 297818200         - FOR o IN z_obs   /* geo index scan, scan only */    
  8   CollectNode                       1           - COLLECT  WITH COUNT INTO c   /* count */
  9   ReturnNode                        1           - RETURN c

Indexes used:
 By   Name              Type   Collection   Unique   Sparse   Selectivity   Fields                           Ranges
 10   idx_11016982078   geo    z_obs        false    true             n/a   [ `geoloc.lat`, `geoloc.lon` ]   (GEO_DISTANCE([ c.`lon`, c.`lat` ], [ o.`geoloc`.`lon`, o.`geoloc`.`lat` ]) < 100000)

Optimization rules applied:
 Id   RuleName
  1   geo-index-optimizer
  2   remove-unnecessary-calculations-2
  3   reduce-extraction-to-projection
```

__Dataset__:
Example documents (45,000,000 documents, 18,000,000 with lat/lon):
```
{
	"geoloc": {
		"lat": 43.6517076,
		"lon": 3.8620017,
		"altitude": 92,
		"accuracy": null
	},
	...
},
{
	"geoloc": null,
	...
}
{
	"geoloc": {
		"lat": null,
		"lon": null,
		"altitude": null,
		"accuracy": null,
		"locality": "at home"
	},
	...
}
```

## Steps to reproduce

1. Explain `Query1` (using `GEO_DISTANCE() < c.radius`)
2. Explain `Query2` (using `GEO_DISTANCE() < 100000`)

__Problem__: the geo index is not used in `Query1`. I tried to cast the radius with `TO_NUMBER`, the index is still not used.

__Expected result__: the geo index is used

**Comment by AntoineAA** [comment]
Hello ArangoDB team,

Sorry to have closed and then reopened the issue.
During the tests, it worked again (because I set the comparison value as an integer), but at the end it doesn't work with a variable.

Best regards,

**Comment by AntoineAA** [comment]
If it helps:

```
for m in z_monitoring
	for c in m.polygons
		let radius = ROUND(TO_NUMBER(c.radius))
		return radius
```
```
[
	70247,
	76355
]
```

In the next example, the index is used, but the request returns `0`:
```
for m in z_monitoring
	for c in m.polygons
		let radius = ROUND(TO_NUMBER(c.radius))
		for o in z_obs
			filter GEO_DISTANCE([c.lon, c.lat], [o.geoloc.lon, o.geoloc.lat]) < radius
			collect with count into c return c
```

If I use the greatest radius value `76355`, it returns `9414`:
```
for m in z_monitoring
	for c in m.polygons
		let radius = ROUND(TO_NUMBER(c.radius))
		for o in z_obs
			filter GEO_DISTANCE([c.lon, c.lat], [o.geoloc.lon, o.geoloc.lat]) < 76355
			collect with count into c return c
```

**Comment by Simran-B** [comment]
If you use a stored value as radius, then a full collection scan will be required to retrieve that value before the distance can be calculated. I assume that the geo index will not be eligible if the radius is dynamic. `FILTER GEO_DISTANCE(...) < NOOPT(76355)` will probably not return the expected number anymore too. If no index can be used, I would still expect the query to arrive at the correct result, albeit slower. So this might actually be a bug.

**Comment by AntoineAA** [comment]
Not sure to understand. Do you mean that it's not possible to use geo index with this query? : 
```
for m in z_monitoring
    for c in m.polygons
    	 for o in z_obs
    	    filter GEO_DISTANCE([c.lon, c.lat], [o.geoloc.lon, o.geoloc.lat]) < c.radius
    	       collect with count into c return c
```

**Comment by Simran-B** [comment]
The value of `c.radius` is not known at query compile time but only at run time, because it comes from storage (it is dynamic). The optimizer doesn't recognize that it could still use the geo index, as long as the document reference is from an outer loop. I consider this a feature request.

What's the result of this query?

```
for m in z_monitoring
	for c in m.polygons
		for o in z_obs
			filter GEO_DISTANCE([c.lon, c.lat], [o.geoloc.lon, o.geoloc.lat]) < NOEVAL(76355)
			collect with count into c return c
```

Does it return the same value as without `NOEVAL()` or not? If it returns a different number, then I would consider that a potential bug.

**Comment by AntoineAA** [comment]
```
for m in z_monitoring
	for c in m.polygons
		for o in z_obs
			filter GEO_DISTANCE([c.lon, c.lat], [o.geoloc.lon, o.geoloc.lat]) < NOEVAL(76355)
			collect with count into c return c
```
Indexes use: none

Result:
```
Warnings:

[10], 'in function 'GEO_DISTANCE()': Invalid coordinate pair'
[10], 'in function 'GEO_DISTANCE()': Invalid coordinate pair'
[10], 'in function 'GEO_DISTANCE()': Invalid coordinate pair'
[10], 'in function 'GEO_DISTANCE()': Invalid coordinate pair'
[10], 'in function 'GEO_DISTANCE()': Invalid coordinate pair'
[10], 'in function 'GEO_DISTANCE()': Invalid coordinate pair'
[10], 'in function 'GEO_DISTANCE()': Invalid coordinate pair'
[10], 'in function 'GEO_DISTANCE()': Invalid coordinate pair'
[10], 'in function 'GEO_DISTANCE()': Invalid coordinate pair'
[10], 'in function 'GEO_DISTANCE()': Invalid coordinate pair'

Result:

[
  2794402
]
```
If I add `filter o.geoloc.lon and o.geoloc.lat`:

Indexes used: none and `9414` as result

**Comment by Simran-B** [comment]
Thanks, with the additional filter it matches the number that you mentioned in https://github.com/arangodb/arangodb/issues/13185#issuecomment-741873567, which seems like a good sign. I guess the warnings are raised because GEO_DISTANCE() receives `null` for documents without `geoloc.lon` and `geoloc.lat`. It's a bit strange though that this doesn't appear to be the case for your original query.

@goedderz was so kind to check the optimizer code and found out that the geo index rule only supports expressions that are values or variable references. It does not support attribute accesses like `c.radius` so far. A workaround could be to assign the attribute to a variable:

```js
for m in z_monitoring
    for c in m.polygons
        let radius = c.radius
        let tmp = NOOPT(radius) // prevent optimizer from substituting radius with r.radius if it's only used once
    	 for o in z_obs
    	    filter GEO_DISTANCE([c.lon, c.lat], [o.geoloc.lon, o.geoloc.lat]) < radius
    	       collect with count into c return c
```

However, it doesn't return anything in 3.7 when a geo index is present. It does return something if there is no index. In a 3.8.devel maintainers build, I found an assertion failure: `max->type == aql::NODE_TYPE_VALUE`. Looks like the geo index doesn't support/resolve variable references to values.

**Comment by Simran-B** [comment]
@AntoineAA We confirmed that the optimizer only supports numbers. It also accepts references (variables), but this isn't actually implemented. #13196 restricts it to numbers. In a future step, we would like to add support for references and attribute access and enable the geo index optimization for your example query, but this will take some time.

**Comment by AntoineAA** [comment]
Ok, thank you!
