### ISSUE TITLE
Question:  Search/Filter All Values?

### ISSUE THREAD

**Issue by Phillips126** [arangodb/arangodb#13188]
Is it possible to perform an  `ArangoSearch` or `Filter` on all document values without specifying the key?
Preferably with partial matches (ex:  Searching `at` would return `at`, `cat`, `attack`)

I know I can do this, specifying which keys to check:
```
FOR item IN items
    FILTER 
        CONTAINS(item.name, @searchValue) OR 
        CONTAINS(item.jobtitle, @searchValue) OR 
        CONTAINS(item.department, @searchValue)
    RETURN item
```

But is there a way to perform simple query like:
```
FOR item IN items
    FILTER CONTAINS(item.[*], @searchValue)
    RETURN item
```

I believe I could use something like this, but it only works for exact matches:
```
FOR item IN items
    FILTER VALUES(item) ANY == @searchValue
    RETURN item
```

I am building an internal ticketing system for our company and each ticket may have a slightly different schema.  I'd like to be able to have a general "everything" search, without specifying every potential key in the query.

Is this possible?

**Comment by Simran-B** [comment]
This is currently not possible unless you maintain an additional field with all the text in it, which you can then index and search. There is no support for virtual fields yet, but it's on our radar (with no ETA).

For top-level attributes only you could try:

```js
FOR item IN items
  FILTER LENGTH(FOR v IN VALUES(item) FILTER CONTAINS(v, @@searchValue) RETURN true)
  RETURN item
```

It will obviously have no index acceleration.

**Comment by Phillips126** [comment]
@Simran-B Appreciate the response.  Given that my documents are small, I'll include the fields to take advantage of that index acceleration.  There is no reason to sacrifice performance for laziness on my part.

**Comment by mdgilene** [comment]
Sorry for digging this up from the grave, but are there any plans to support this type of querying? Coming from one of my other projects which used Elasticsearch doing this was relatively trivial.

```json
{
  "match": {
    "metadata.*": {
      "query": "quick brown fox"
    }
  }
}
```

Having to store the entire contents of all of these fields (especially in our case where the content of the `metadata` object is largely user provided seems like a significant waste of space. You also lose the ability to do additional things such as knowing which field matched the query and highlighting.

**Comment by Simran-B** [comment]
There are no plans to support searching all document attributes using a wildcard for the attribute key due to performance concerns and because it would be difficult to integrate with other features that work on a per-field basis (scoring, highlighting, etc.). You can index all fields with `includeAllFields: true` at the top-level but you need to specify the attribute key/field when searching.
