### ISSUE TITLE
cut 'n' paste to arangosh with MobaXterm not working properly

### ISSUE THREAD

**Issue by wangweidonghb** [arangodb/arangodb#13192]
![image](https://user-images.githubusercontent.com/59814379/101740190-79d6e800-3b03-11eb-9d22-e6c1d71a6d10.png)
After pasting a batch of commands to arangosh, they cannot be executed normally, How to resolve it?

**Comment by wangweidonghb** [comment]
![image](https://user-images.githubusercontent.com/59814379/101740443-c7ebeb80-3b03-11eb-838f-fbff1e23abbf.png)

**Comment by dothebart** [comment]
Hi, it seems there are some characters missing in the paste? Sometimes pasting large chunks of text may have side effects with the terminal program.
It seems that the text isn't ended properly, hence the js-statement doesn't end? So were they in the original text you pasted?

Sometimes a remote shell may also be less reliable to large text paste chunks, hence running an arangosh locally may improve the situation.

Please note that you can also use `--javascript.execute` to specify a javascript file that should be executed in arangosh, see https://www.arangodb.com/docs/stable/programs-arangosh-details.html#using-arangosh-via-unix-shebang-mechanisms for details. This should bring you reliable to your desired instructions being executed; you can also add error handling for even more better reliability.

**Comment by wangweidonghb** [comment]
> Hi, it seems there are some characters missing in the paste? Sometimes pasting large chunks of text may have side effects with the terminal program.
> It seems that the text isn't ended properly, hence the js-statement doesn't end? So were they in the original text you pasted?
> 
> Sometimes a remote shell may also be less reliable to large text paste chunks, hence running an arangosh locally may improve the situation.
> 
> Please note that you can also use `--javascript.execute` to specify a javascript file that should be executed in arangosh, see https://www.arangodb.com/docs/stable/programs-arangosh-details.html#using-arangosh-via-unix-shebang-mechanisms for details. This should bring you reliable to your desired instructions being executed; you can also add error handling for even more better reliability.

Thanks for your replay. When I execute the commands with --javascript.execute in a js file, it can execute normally.  when copy the commands from js file and pass them to arangosh ,  problem occurred and display the content in the screenshot above

**Comment by dothebart** [comment]
Hi, 
as stated, cut'n'paste can be unreliable under certain circumstances. 
Can you please add information about which terminals / ssh / whatever has been in the game here?

**Comment by wangweidonghb** [comment]
> Hi,
> as stated, cut'n'paste can be unreliable under certain circumstances.
> Can you please add information about which terminals / ssh / whatever has been in the game here?

Of course.
![image](https://user-images.githubusercontent.com/59814379/101757681-6a12d000-3b12-11eb-8459-a3ab9cf0ea62.png)
This is the version information of sh, what other information do you want to check ?

**Comment by dothebart** [comment]
list your complete environment please. All components / programms involved in the flow.

**Comment by wangweidonghb** [comment]
> list your complete environment please. All components / programms involved in the flow.

OS info:
![image](https://user-images.githubusercontent.com/59814379/101760869-697c3880-3b16-11eb-927f-dc91838b6e76.png)
The others are useless, oh yes, I used ar's graph module to create vertices and edges
![image](https://user-images.githubusercontent.com/59814379/101761496-31292a00-3b17-11eb-9148-71f7ab937728.png)
![image](https://user-images.githubusercontent.com/59814379/101761546-3d14ec00-3b17-11eb-868d-edebc24bde08.png)

**Comment by wangweidonghb** [comment]
![image](https://user-images.githubusercontent.com/59814379/101761831-97ae4800-3b17-11eb-8bc5-f2bbb7e6bb4c.png)

**Comment by dothebart** [comment]
again: which terminal emulator?

**Comment by wangweidonghb** [comment]
> again: which terminal emulator?

Do you mean the ssh connection tool ? like secureCRT?   I use the ssh client is : MobaXterm

**Comment by wangweidonghb** [comment]
> again: which terminal emulator?



> again: which terminal emulator?

**Comment by wangweidonghb** [comment]
> again: which terminal emulator?

I think I find the problem according to your hint, It is the ssh client problem. When I use the secureCRT, the passed batch commands can be executed normally in arangosh.

Thank you very much for your help!

**Comment by dothebart** [comment]
Hi, 
thanks for confirming, glad I could help.
