### ISSUE TITLE
Does arango support PITR(Point In Time Recovery)?

### ISSUE THREAD

**Issue by yogeshbidari** [arangodb/arangodb#13197]
## My Environment

* __ArangoDB Version__:        3.3.8
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Kubernetes
* __Configuration__:               
* __Infrastructure__:               GKE
* __Operating System__:        
* __Total RAM in your machine__:        
* __Disks in use__:        
* __Used Package__:              Docker - official Docker library

## Component, Query & Data

__Affected feature__:
Does arango support PITR(Point In Time Recovery) ?
If yes, what version it supports?

We are using WAL files and trying to restore to some point in time before the data corruption/deletion.
Is this can be achieved by arango? we see similar kind of setup such as PITR in Mongo and Postgres.

**Comment by maxkernbach** [comment]
Hi @yogeshbidari,

PITR is provided by [Hot Backups](https://www.arangodb.com/docs/stable/backup-restore.html#hot-backups), which were introduced in: v3.5.1.
Please note that Hot Backups are only available in the Enterprise Edition.



> - **Point in Time Recovery**
> 
> One of the great advantages of the method is the consistent snapshot nature. It gives the operator of the database the ability to persist a true and complete time freeze at near zero impact on the ongoing operation. The recovery is easy and restores the entire ArangoDB installation to a desired snapshot.
> 
> Apart from the ability of creating such snapshots it offers a great and easy to use opportunity to experiment with ArangoDB with a means to protect against data loss or corruption.
>
