### ISSUE TITLE
Ubuntu 15.04 repository

### ISSUE THREAD

**Issue by F21** [arangodb/arangodb#1319]
It would be awesome if a repository for Ubuntu 15.04 can be built. Using the binaries from 14.10 didn't allow the server to start using `sudo service arangodb start`. I think this is because 15.04 changed their init system to systemd and that broke things.

**Comment by jsteemann** [comment]
Our build service is now able to build Ubuntu 15.04 packages, and I think we will add 15.04 to our builds soon. I cannot give a definitive date now, but we'll be working on it.

**Comment by legikaloz** [comment]
The Ubuntu 15.05 repo is available, I've successfully installed arangodb from Ubuntu 15.04 repo today: https://www.arangodb.com/repositories/arangodb2/xUbuntu_15.04/

**Comment by jsteemann** [comment]
Thanks for confirming. I'll close this issue then.
