### ISSUE TITLE
Cannot get windows installation to set windows PATH variable

### ISSUE THREAD

**Issue by sereeena** [arangodb/arangodb#13191]
## My Environment

* __ArangoDB Version__:        3.7.1
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Windows installer silent installation
* __Configuration__:               
* __Infrastructure__:               own
* __Operating System__:        Windows 10
* __Total RAM in your machine__:        
* __Disks in use__:        
* __Used Package__:              

## Component, Query & Data

__Affected feature__:

Installation with unattended silent install options /PATH not working

__AQL query (if applicable)__:
```


```
__AQL explain and/or profile (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. Running ArangoDB3-3.7.1_win64.exe /S /PASSWORD=passwordstr /INSTALL_SCOPE_ALL=1 /PATH=1 /DESKTOPICON=0
2. ArangoDB is correctly installed as a service and started, but the system environment variables PATH does not include the arangodb installation bin directory.
3. 

__Problem__:
I want the arangodb executables (arangodump/arangorestore) in the PATH, and they are not. The AddToPath variable is set to 1 as you can see from the screenshot of the registry but it hasn't been added to PATH. 
Am I missing something?

![arango](https://user-images.githubusercontent.com/13515255/101733694-279bc400-3b0f-11eb-897c-308444f7df80.png)

__Expected result__:

**Comment by dothebart** [comment]
Hi, 
since there are certain situations in which NSIS will fail to modify the path in systems, can you please confirm whether it works on your specific system when installing interactively or not?

**Comment by sereeena** [comment]
Hi,
I just tried and it also doesn't work attempting to add to path in interactive mode. Which situations does it fail to modify the path? I have tried it (interactive) on a VirtualBox VM running Windows 10 Home, and a normal desktop machine running Windows 10 Pro.

Let me know what further information you might need?
Thanks!

**Comment by dothebart** [comment]
Hi, 
- if the path is to long, NSIS fails to do so. (from what I see in your screenshot, I wouldn't assume that? ) 
- if the permissions of the installer process aren't right, it may be disallowed to do so by the system?

**Comment by sereeena** [comment]
Hi,

The installs were using default settings, so path is c:\Program Files\ArangoDB3 3.7.1 and are run by administrator users, so don't think those are the problems.

I just tried it with the v3.7.2 installer and it is exactly the same (and I can't see any useful output in the log window before it becomes inaccessible unfortunately)

**Comment by Simran-B** [comment]
I tried the interactive 3.7.3 installer, it installed without warnings but did not add to PATH. It used to show a message box if it went wrong, e.g. because of > 1024 characters (NSIS limitation).
