### ISSUE TITLE
The README file in this repo has a bad link - [404:NotFound] - "Foxx"

### ISSUE THREAD

**Issue by MrCull** [arangodb/arangodb#13210]
## My Environment
n/a

## Component, Query & Data
n/a

## Steps to reproduce

The markup version of the readme that is displayed for the main page in this repo contains the following link:

“Foxx”
Status code [404:NotFound] - Link: https://www.arangodb.com/foxx

__Problem__:
bad link

__Expected result__:
working link

**Extra**

This bad link was found by a tool I recently created as part of an new experimental hobby project: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder

Re-check this Repo via: http://githubreadmechecker.com/Home/Search?SingleRepoUri=https%3a%2f%2fgithub.com%2farangodb%2farangodb
Check all Repos for this GitHub account: http://githubreadmechecker.com/Home/Search?User=arangodb

--

I (a human) verified that this link is broken and have manually logged this Issue (i.e. this Issue has not been created by a bot).
If this has been in any way helpful then please consider giving the above Repo a Star.

If you have any feedback on the information provided here, or on the tool itself, then please feel free to share your thoughts and pass on the feedback, or log an “Issue”.

**Comment by Simran-B** [comment]
Thanks, I updated the links: https://github.com/arangodb/arangodb/commit/e4670baa640922473bf65152ff960609fe5f2f55

We recently updated our website and are still in the process of fixing broken links and setting up redirects. The Foxx link in particular redirects to the new URL now.
