### ISSUE TITLE
generalGraphDistanceTo2 not working anymore

### ISSUE THREAD

**Issue by dothebart** [arangodb/arangodb#1321]
While closely watching the results of the documentation samples this was uncovered:
The Documentation snippet named generalGraphDistanceTo2 from the file js/server/modules/org/arangodb/aql.js: 

    arangosh> var examples = require("org/arangodb/graph-examples/example-graph.js");
    arangosh> var g = examples.loadGraph("routeplanner");
    arangosh> db._query("FOR e IN GRAPH_DISTANCE_TO("
    ........> + "'routeplanner', [{_id: 'germanCity/Cologne'},{_id: 'germanCity/Hamburg'}], " +
    ........> "'frenchCity/Lyon', " +
    ........> "{weight : 'distance'}) RETURN [e.startVertex, e.vertex._id, e.distance]"
    ........> ).toArray();

would return this with arangodb 2.5x:

    [
      [
        "germanCity/Cologne",
        "frenchCity/Lyon",
        700
      ],
      [
        "germanCity/Hamburg",
        "frenchCity/Lyon",
        1200
      ]
    ]

ArangoDB 2.6 will return this:

    [
      [
        "germanCity/Cologne",
        null,
        700
      ],
      [
        "germanCity/Hamburg",
        null,
        1200
      ]
    ]

**Comment by mchacki** [comment]
It should now be fixed alongside with some other issues rooted in the same reason.
