### ISSUE TITLE
Can't pipe output of command line tools on Windows (arangodump/arangorestore)

### ISSUE THREAD

**Issue by sereeena** [arangodb/arangodb#13225]
## My Environment

* __ArangoDB Version__:       3.7.1 
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:        Windows 10
* __Total RAM in your machine__:        
* __Disks in use__:        
* __Used Package__:              

## Component, Query & Data

__Affected feature__:

Calling arangodump and arangorestore on Windows works but piping the output gives no output at all. 
Writing software that calls these processes on windows can't get any information/output on progress or success of these calls.
I am using golang and want to use pipes because arangorestore is potentially a long running process and I want to get the output in real time while arangorestore is still running. I believe this has nothing to do with any language used to call the cmd line tools, see steps to reproduce below.

__AQL query (if applicable)__:
```


```
__AQL explain and/or profile (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. Open a cmd prompt (as administrator) on windows in the bin directory eg c:\Program Files\ArangoDB3 3.7.1\usr\bin
2. arangodump.exe --server.database "TestDB" --server.endpoint "ssl://localhost:8529" --overwrite "true" --server.password "passwordhere" --output-directory "c:\Temp\Backup" **this works and output appears in cmd prompt**
3. arangodump.exe --server.database "TestDB" --server.endpoint "ssl://localhost:8529" --overwrite "true" --server.password "passwordhere" --output-directory "c:\Temp\Backup" > c:\Temp\dump.txt **the output file is empty**

__Problem__:
Step 2 works, but if you try step 3 to pipe the output anywhere, despite the process succeeding there is no output.

__Expected result__:
The output should appear in the file. I can't understand why this is so, it is not permissions related, I am running the cmd prompt as an administrator. I have tried turning my firewall off, not running any anti-virus. Does anyone have any ideas how to get this to work, so I can run the tools from my software?
(Note this is only a problem in Windows, the same steps work perfectly as expected in Linux)

**Comment by dothebart** [comment]
Hi, 
all the tools have a detection whether they talk to an interactive shell or not. This detection can be circumvented by `--log.foreground-tty true`. If you want to disable Queueing of messages, and see them right away specify `--log.force-direct true`.
For more related Information on commandline arguments please see https://www.arangodb.com/docs/stable/programs.html .

**Comment by sereeena** [comment]
Hi,
Thank you, --log.foreground-tty does force the output so it can be piped. I wasn't aware the tools did not output to non-interactive shells which is what occurs when the process is spawned on windows. (It didn't do this on linux which is what confused me).

Closing this issue, cheers.
