### ISSUE TITLE
Unclear error with LEVENSHTEIN_MATCH

### ISSUE THREAD

**Issue by leny** [arangodb/arangodb#13226]
## My Environment

* __ArangoDB Version__:        3.7.5
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start in Docker
* __Configuration__:               nothing specific
* __Infrastructure__:               AWS - but issue is currently in local dev env
* __Operating System__:        Ubuntu 20.04
* __Total RAM in your machine__:        16Gb.
* __Disks in use__:        SSD
* __Used Package__:    Docker - official Docker library

## Component, Query & Data

__Affected feature__: I have an unclear error while running the next query, which seems, according to the docs, correct: `Query: AQL: collection or view not found: juniors (while instantiating plan)`

__AQL query (if applicable)__:
```
FOR junior IN juniors
    SEARCH LEVENSHTEIN_MATCH(junior.firstname, @firstname, 2, false)
        OR LEVENSHTEIN_MATCH(junior.lastname, @lastname, 2, false)
    SORT BM25(junior) DESC
    RETURN junior
```

__Dataset__:
The `juniors` collection exists (±1200 docs), and have two fulltext indexes on `firstname` and `lastname`. Never had issue before, making queries & modifications to the collection without problem.
Just wanted to implement a "fuzzy search" to help reducing duplicates while encoding people in the collection (complex process on our side).

* * *

Thanks in advance!

**Comment by dothebart** [comment]
you probably [wanted to create a view](https://www.arangodb.com/docs/stable/arangosearch.html) and use that in this query? 
so you would name the view juniors_view, and use that in this context?

**Comment by leny** [comment]
Ok, my bad, I understood the feature completely wrong, haha.
Thanks for your help, and sorry for the useless issue.

**Comment by dothebart** [comment]
no issue is useless - it in doubt shows a missing link in the documentation. Which way did you go?
