### ISSUE TITLE
strange AQL result ArangoDb 2.5.2

### ISSUE THREAD

**Issue by diegogub** [arangodb/arangodb#1322]
Hello,
I'm having quite an strange result with a query. I attach some screenshots.
![screen shot 2015-04-27 at 8 09 13 pm](https://cloud.githubusercontent.com/assets/2489012/7359817/af3efcf0-ed19-11e4-9df6-97fef2ce8cc8.png)
![screen shot 2015-04-27 at 8 09 25 pm](https://cloud.githubusercontent.com/assets/2489012/7359819/b19ad9b0-ed19-11e4-8e93-b272b754b0d2.png)
![screen shot 2015-04-27 at 8 09 35 pm](https://cloud.githubusercontent.com/assets/2489012/7359821/b3f35dae-ed19-11e4-9e90-9c6b9a41ca33.png)

Which is the problem with the query? Thanks

**Comment by diegogub** [comment]
I notice that removing skiplist indexes solve the problem, but I don't see why it should not work. Thanks.

**Comment by jsteemann** [comment]
This was indeed a bug when querying a unique, multi-attribute skiplist index with just a prefix of the index attributes and an equality condition. It is fixed now in devel, 2.5 (2.5.3) and 2.4 (2.4.8).

**Comment by diegogub** [comment]
:)
