### ISSUE TITLE
[3.7.5] Windows Server 2016 SetThreadDescription

### ISSUE THREAD

**Issue by coronabytes** [arangodb/arangodb#13238]
## My Environment

* __ArangoDB Version__:        3.7.5
* __Storage Engine__:             RocksDB
* __Deployment Mode__:      Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:              
* __Infrastructure__:               own
* __Operating System__:        Windows Server 2016
* __Total RAM in your machine__:        8GB
* __Disks in use__:        SSD
* __Used Package__:              ZIP

![Error](https://user-images.githubusercontent.com/7018968/102386609-8c539480-3fcf-11eb-8d47-4d98fc6ad7d3.PNG)
![Windows](https://user-images.githubusercontent.com/7018968/102387523-c5d8cf80-3fd0-11eb-9f06-a51b6a6d8bd3.PNG)

3.7.5 no longer works on Windows Server 2016. Thats a rather breaking change for a patch version update....
Works on Windows 10 though
Reverted back to 3.7.3

Did you change the msvc compiler / sdk / target for 3.7.5?

**Comment by dothebart** [comment]
Hi, 
thanks for letting us know. 
The function isn't available to statically linked binaries on WS 2016 - We're searching for a solution.

**Comment by Dronplane** [comment]
Hi @coronabytes !  We made this API loading dynamic and only if host supports it.

**Comment by maxkernbach** [comment]
Hi @coronabytes,

In the meantime version 3.7.6, which includes a fix for this issue, has been released.

From the [Changelog](https://github.com/arangodb/arangodb/blob/c1870605e02b73f6d45f6e5431a6e2a610f098a2/CHANGELOG#L51):

> * Fixed issue #13238 Thread naming API on Windows are now used only if
>   available in KERNEL32.DLL

Installing ArangoDB 3.7.6 should work as expected on Windows Server 2016. If this is not the case, please let us know.
