### ISSUE TITLE
Foxx model schema validations

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangodb#1325]
I keep running into problems with my models’ schemas and I’m starting to believe now that the default way a generated Foxx app handles the schemas can only work for the simplest of use cases.

Problem 1: model.set() doesn’t catch validation problems if the schema defines attributes based on the value of other attributes like:
```
foo: Joi.string(),
bar: Joi.string().when(‘foo’, {is: ‘baz’, then: Joi.required()})
```
Now if the controller action gets called with {foo: ’baz’, bar: null}, nothing will catch that the model is invalid due to bar being null.

I guess set() could validate the whole schema instead of just the attribute being set, but that feels pretty wasteful.

Problem 2: For any non-trivial document that, for example, has private values (hidden from API consumers) and stores computed values, validating the internal model is fundamentally different from validating parameters to the controller actions.

For example, a private, internal attribute I might want to define as `Joi.number().integer().min(3).max(15).required().default(7)` and be able to rely on all documents having valid values for that attribute. My API user, on the other hand, should never get or set that attribute (because it’s internal/private).

Controller POST and PUT methods are creating a model from the raw parameters, and then validate that model. In my example, the PUT method would overwrite my document’s private attribute with the default value 7 which is obviously wrong.

Problem 3: One would want to implement a merge-patch controller action that is somewhat consistent with the post/put actions. But then one couldn’t even define any parameters as required() in the schema. (see also #1324).

Proposal that would address some problems:
- The model’s schema should be considered an internal description of documents stored in ArangoDB.
- Models get a validate() method that by default performs the schema validation but can be overwritten to also perform additional programmatic validations that can’t be described with a Joi schema (for example the requirement that an integer attribute should always have even values).
- The repository becomes responsible for invoking validations. Every repository method that creates or updates a document should first invoke the model’s validate() method and stop with an error if the model is invalid. So even repository.updateByExample() needs to instantiate every document as a model, update the model, validate it, and then save it to the document. Yes, this might be unrealistic if many documents would be involved. But I’d argue that raw updates that bypass validations should not be the repository’s responsibility.
- Model.set() doesn’t do any validation. If anybody wants to know if a model is still valid, they should call the new validate() method directly.
- Controller actions don’t perform any validation on the bodyParam. Only type conversions. This may require forking of Joi because I don’t think it can be used purely for type conversions.

Unsolved problem: if the schema uses alternative types for an attribute based on the value of a private attribute, how could the controller do the type conversion? For example:

```
foo: Joi.string(), // private/internal attribute
bar: Joi.alternatives().when(‘foo’, { is: 1, then: Joi.string(), otherwise: Joi.number() })
```

I realize this proposal is incompatible with the current Foxx implementation.

I’d love to hear what others are thinking about this.

**Comment by pluma** [comment]
I agree that the current implementation has its problems.

Personally I'm unhappy with the repository/model architecture altogether and would instead prefer just dealing with fancy collections-with-schemas and plain objects. In practice validation seems to be a concern of the context (i.e. how data is used) rather than the data itself, other than "computed values", models don't seem to bring anything interesting to the table.

**Comment by pekeler** [comment]
I still kind of like the idea of models as a place for my businessy logic, constants, etc. And I like having a Repository - but I wish the repository was purely a repository of models (replaceById(), replaceByExample(),  updateByID(), updateByExample() are not model related, and update() has a weird signature and does too much).

**Comment by pluma** [comment]
Just a head's up: we'll likely replace the Foxx Model/Repository structure with something less complicated in 3.x, but I'll keep this issue open as a reference point.

**Comment by pluma** [comment]
This is made redundant by the Foxx rewrite for 3.0.
