### ISSUE TITLE
problem running tests

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangodb#1326]
I wanted to try out the latest devel version (on OS X 10.10.3):
```
make setup
./configure --host=x86_64-apple-darwin --target=x86_64-apple-darwin --enable-relative
make
./bin/arangod -c etc/relative/arangod.conf --server.endpoint tcp://127.0.0.1:8529 /tmp/database-dir
```
so far so good, but then `make unittests` results in
```
./bin/arangod --configuration ./etc/arangodb/arangod.conf --help 1> /dev/null || false
2015-05-03T18:35:07Z [46983] ERROR cannot parse config file './etc/arangodb/arangod.conf': file not found
2015-05-03T18:35:07Z [46983] FATAL cannot parse command line arguments
make: *** [unittests-config] Error 1
```

Did I do anything wrong?

**Comment by fceller** [comment]
Seems like the config file is not created. Have to check.

**Comment by fceller** [comment]
The target causes the conf file to be named arangodx86_64-apple-darwin-.conf

**Comment by pekeler** [comment]
Seems like all the .conf files need to be renamed
```
for file in etc/arangodb/*x86_64-apple-darwin-.conf; do cp "$file" "${file%x86_64-apple-darwin-.conf}.conf"; done
```
Now it works for me. Thanks!

**Comment by pekeler** [comment]
https://docs.arangodb.com/Installing/Compiling.html should probably mention this.

**Comment by fceller** [comment]
Ok, you need to add

   --program-suffix=""

as well. Then it should work.

**Comment by fceller** [comment]
Add hint to the documentation.
