### ISSUE TITLE
Minor typo in the AQL docs

### ISSUE THREAD

**Issue by amjadorfali** [arangodb/arangodb#13296]
Hello, this is just a minor typo in the arango AQL docs, the typo is instead of **this/it** it's written **is**. 
Thank you all for your hard work and the very well-written documentation 🚀 , one of the best I've ever read. ❤️ 

![Screen Shot 2020-12-23 at 6 52 11 PM](https://user-images.githubusercontent.com/69120545/103019748-f9c37000-454f-11eb-8b69-5bb28c85e78e.png)

**Comment by Simran-B** [comment]
@amjadorfali Thank you for the kind words and for letting us know about the typo. It's fixed by https://github.com/arangodb/docs/pull/602 and will be published some time after the holidays.

**Comment by amjadorfali** [comment]
Thank you for your email.
Have a happy holiday!

Best Regards,
Amjad Orfali.
