### ISSUE TITLE
arangodb in index

### ISSUE THREAD

**Issue by Neverstop** [arangodb/arangodb#13335]
## My Environment

* __ArangoDB Version__:        3.6.9
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Cluster 
* __Deployment Strategy__:    Manual Start
* __Operating System__:        Linux x86
* __Total RAM in your machine__:        64

__AQL query (if applicable)__:
```
for node in rec_behavior_edge
filter node._to in ['rec_music_node/5c4a4ec2-8968-4c7d-bf99-bc38a0511bef', 'rec_music_node/6ec127f0-84ad-4095-ba78-97c9bd2d607c']
return node
```

__AQL explain and/or profile (if applicable)__:
```
Query String (171 chars, cacheable: true):
 for node in rec_behavior_edge
 filter node._to in ['rec_music_node/5c4a4ec2-8968-4c7d-bf99-bc38a0511bef', 
 'rec_music_node/6ec127f0-84ad-4095-ba78-97c9bd2d607c']
 return node

Execution plan:
 Id   NodeType        Site  Est.   Comment
  1   SingletonNode   DBS      1   * ROOT
  6   IndexNode       DBS      1     - FOR node IN rec_behavior_edge   /* edge index scan, 5 shard(s) */    
  9   RemoteNode      COOR     1       - REMOTE
 10   GatherNode      COOR     1       - GATHER   /* parallel */
  5   ReturnNode      COOR     1       - RETURN node

Indexes used:
 By   Name   Type   Collection          Unique   Sparse   Selectivity   Fields      Ranges
  6   edge   edge   rec_behavior_edge   false    false        96.14 %   [ `_to` ]   (node.`_to` in [ "rec_music_node/5c4a4ec2-8968-4c7d-bf99-bc38a0511bef", "rec_music_node/6ec127f0-84ad-4095-ba78-97c9bd2d607c" ])

Optimization rules applied:
 Id   RuleName
  1   use-indexes
  2   remove-filter-covered-by-index
  3   remove-unnecessary-calculations-2
  4   scatter-in-cluster
  5   remove-unnecessary-remote-scatter
  6   parallelize-gather
```
__Problem__:

The number of arrays in an arangodb in query array exceeds the value of this parameter. The index will not be used.
Is there a restriction?

**Comment by dothebart** [comment]
Hi, 
have you considered putting in that array as a bind value?

**Comment by Neverstop** [comment]
Actually, that's how I use it.
I'm just a little concerned about performance, so I'm asking.

**Comment by Simran-B** [comment]
@Neverstop I'm not sure if I understand the problem. Are you afraid that the `FILTER <id> IN [ ... ]` doesn't scale if the array is very large? I don't see a reason why it would stop using the edge index at some point.

**Comment by Neverstop** [comment]
@Simran-B 
I see.
I'm asking because I compared with the MySQL database.
https://dba.stackexchange.com/questions/174945/mysql-not-using-index-on-large-where-in-clause
Thanks for the help.

**Comment by dothebart** [comment]
ArangoDB uses selectivity estimates on indices to decide whether they could play a useful game in the Query or not. 
Selectivity describes the number of document a FILTER would possibly be able to insulate on an index.
So if the selectivity of the index worsens over time by adding many similar documents into it, the decision may work out in favor of another plan.

**Comment by Neverstop** [comment]
I see. Thank you.
