### ISSUE TITLE
cmake for source install on macOS 10.15.6 fails

### ISSUE THREAD

**Issue by metanomi** [arangodb/arangodb#13349]
## My Environment

* __ArangoDB Version__:        3.8.0-devel
* __Operating System__:        macOS 10.15.6

## Component, Query & Data

__Affected feature__:
Installation

## Steps to reproduce

1. git clone git://github.com/arangodb/arangodb.git
2. cd arrangodb
3. cmake -DOPENSSL_ROOT_DIR=$(brew --prefix openssl) -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15

__Problem__:
```
CMake Error at CMakeLists.txt:1065 (message):
  expecting OPENSSL_ in /Users/terence.bodola/arangodb/VERSIONS
```

and that's because TARGET_OS is unset

but tracing it back this is because DARWIN is unset, but this is because APPLE is unset, and that happens here:

```
project(arangodb3 LANGUAGES CXX C ASM VERSION ${ARANGODB_VERSION_MAJOR}.${ARANGODB_VERSION_MINOR})
```

in CMakeLists.txt ...if I print debug it like
```
message(STATUS "<1> APPLE?: ${APPLE}")

# ------------------------------------------------------------------------------
#
# ------------------------------------------------------------------------------

if (WIN32)
  project(arangodb3 LANGUAGES CXX C VERSION ${ARANGODB_VERSION_MAJOR}.${ARANGODB_VERSION_MINOR})
else ()
  project(arangodb3 LANGUAGES CXX C ASM VERSION ${ARANGODB_VERSION_MAJOR}.${ARANGODB_VERSION_MINOR})
endif ()

message(STATUS "<2> APPLE?: ${APPLE}")
```

I get
```
-- <1> APPLE?: 1
-- <2> APPLE?:
```

__Expected result__:
successful configure

**Comment by dothebart** [comment]
will compiling via https://github.com/Homebrew/homebrew-core/blob/master/Formula/arangodb.rb work?

**Comment by maxkernbach** [comment]
Hi @metanomi,

Did you manage to compile with homebrew?
