### ISSUE TITLE
Whether FreeBSD will be supported in the future？

### ISSUE THREAD

**Issue by SisMaker** [arangodb/arangodb#13357]
Arangodb is currently not officially supported for building on FreeBSD, will it be in the future?

**Comment by dothebart** [comment]
Hi, 
no, we currently don't plan to support freebsd officially - this simply isn't possible by CI and Manpower. 
However, MacOS support is there; so it should work *mostly*. 
This is the homebrew formular to build arangodb:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/arangodb.rb
and if you want to contribute patches to fix compilation etc. we can support you here or in slack to get it working, and incooperate them via PR.

**Comment by ykla** [comment]
+1 please support It.

**Comment by dothebart** [comment]
so if nobody wants to volunteer, I will close this now.
