### ISSUE TITLE
Network Error When i trying from react-native 

### ISSUE THREAD

**Issue by subbareddyandr** [arangodb/arangodb#13369]
When i try to use get & post methods for the first time it's working As expected after some time

when i retry to open app all requests getting Network issue

**Using -**
-ArangoDB as Back end - apisauce as httpClient from react-native

**Versions of Libraries :**

 "apisauce": "^2.0.1",
 "react-native": "0.63.2",

**Sample Code**

<code>
const apiClient = create({
        baseUrl :"https://{testing.me}:8529/_db/testingdb/"
  });

  apiClient.get("getPosts").then(res=>{
      // 
   })
</code>

**response**
<code>
{"config": {"adapter": [Function xhrAdapter], "baseURL": "https://{testing.me:8529}/_db/testingDb/", "data": undefined, "headers": {"Accept": "application/json"}, "maxBodyLength": -1, "maxContentLength": -1, "method": "get", "params": {}, "timeout": 0, "transformRequest": [[Function transformRequest]], "transformResponse": [[Function transformResponse]], "url": "getPosts", "validateStatus": [Function validateStatus], "xsrfCookieName": "XSRF-TOKEN", "xsrfHeaderName": "X-XSRF-TOKEN"}, "data": null, "duration": 12644, "headers": null, "ok": false, "originalError": [Error: Network Error], "problem": "NETWORK_ERROR", "status": null}
</code>

How can i solve this problem ?

Thanks in advance

**Comment by dothebart** [comment]
it fails to connect arango? so maybe `{testing.me}` isn't resolveable - better use an IP?

**Comment by subbareddyandr** [comment]
> it fails to connect arango? so maybe `{testing.me}` isn't resolveable - better use an IP?
by using ip also getting same issue

**Comment by dothebart** [comment]
did you check which ip is bound by arangod? `netstat -lnpt` - if its 0.0.0.0 you should be able to connect it from outside (if not firewall) if `127.0.0.1` it will only be reacheable from the very machine. Also a firewall could block access. 
Usually telnet is a simple tool to check connectivity.

**Comment by maxkernbach** [comment]
Hi @subbareddyandr,

did you have a chance to read dothebart's latest message?

**Comment by Simran-B** [comment]
@subbareddyandr Did you check which IP is bound by arangod as dothebart suggested?
