### ISSUE TITLE
Disk throttling / latency during heavy queries since 3.7

### ISSUE THREAD

**Issue by matcho** [arangodb/arangodb#13364]
## My Environment

* __ArangoDB Version__:        3.7.3
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Infrastructure__:               own
* __Operating System__:        Ubuntu 18.04
* __Total RAM in your machine__:       256GB
* __Disks in use__:        RAID 10 of HDD
* __Used Package__:              Ubuntu .deb

## Component, Query & Data

__Affected feature__:
Queries

__AQL query (if applicable)__:
Any query that has to read a large dataset (hundreds of millions of docs), doesn't use any index, and runs for a long time (> 1 hour)

__Dataset__:
280M docs in the collection concerned

__Size of your Dataset on disk__:
~700G

## Steps to reproduce

1. Run a few (maybe 5) heavy queries as described above on a very large collection, on a production machine simultaneously undergoing a regular load 
2. Disk IOs grow fast (not that surprising) and cause large read latency and write latency, which impact the whole machine
3. Wait for queries to end, latencies are back to normal

__Problem__:
Although the situation in itself is not that strange (you read a lot, you get latency), it didn't happen before we update from 3.4 to 3.7. We used to run many heavy queries at a time, which never caused any remarkable latency, and just took a necessary long time to complete, which was totally fine. The hardware did not change and the machine was not restarted, only arangod was restarted due to update to 3.7.

__Expected result__:
No disk throttling even when heavy queries are performed, or maybe some way to tune / limit disk usage ?

Thank you for any advice,
All the best,
Mathias

**Comment by Simran-B** [comment]
@matcho Can you share the actual query? Does it involve subqueries? How long did the query take with version 3.4?

**Comment by matcho** [comment]
Unfortunately I don't remember what exactly were those queries, but at least 2 of them (running simultaneously by mistake ! − I know…) were very close to this:
```
FOR q IN queries
    FILTER q.missing != NULL
    RETURN q._key
```
Knowing that collection `queries` has 280M docs and result length was expected to be max. 1M

Unfortunately as well, we have no track of how long it took with v3.4 as we had not run such queries for a long time, but the time to complete (around 2 hours) was not shocking regarding what we expected. Was it faster I can't tell…

Sorry for all the mysteries around this !

Thank you,
Mathias

**Comment by matcho** [comment]
Did not happen for a long time, seems fixed.
