### ISSUE TITLE
WARNING [d728e] {queries} slow query: 'FOR s in @@collection FILTER s.time >= @start SORT s.time DESC LIMIT 1 RETURN s', bind vars: {"@collection":"_statisticsRaw","start":1.6104420926415126e+9}, took: 180.218119 s, loading took: 2.703094 s

### ISSUE THREAD

**Issue by caozku** [arangodb/arangodb#13360]
## My Environment

* __ArangoDB Version__:        
* __Storage Engine__:             
* __Deployment Mode__:       
* __Deployment Strategy__:   
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:        
* __Total RAM in your machine__:        
* __Disks in use__:        
* __Used Package__:              

## Component, Query & Data

__Affected feature__:

__AQL query (if applicable)__:
```


```
__AQL explain and/or profile (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. 
2. 
3. 

__Problem__:

__Expected result__:

**Comment by dothebart** [comment]
Hi. 
Without any additional information I can only close this issue.

**Comment by Simran-B** [comment]
@caozku Please provide the ArangoDB version, operating system, selected storage engine and when this warning occurs. Until this information is missing we cannot help unfortunately. Please re-open when you updated the initial post.
