### ISSUE TITLE
arangodb will restart as soon as a log switch occurs,why?

### ISSUE THREAD

**Issue by caozku** [arangodb/arangodb#13375]
## My Environment

* __ArangoDB Version__:        <3.6.2>
* __Storage Engine__:             < RocksDB>
* __Deployment Mode__:       
* __Deployment Strategy__:   
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:        
* __Total RAM in your machine__:        
* __Disks in use__:        
* __Used Package__:              

## Component, Query & Data

__Affected feature__:

__AQL query (if applicable)__:
```


```
__AQL explain and/or profile (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. 
2. 
3. 

__Problem__:

__Expected result__:

**Comment by maxkernbach** [comment]
Hi @caozku,

Please add the missing information of the issue template (especially OS, deployment mode, file system).

Do you use any non-default startup options? Also, do you mean that the restart always happens when the logfiles rotate? What is the path of the log file location?

**Comment by caozku** [comment]
Operating System is centos7.I didn't use any non-default startup options.The log is arangodb's system log.The path is "/var/log/arangodb3/"

**Comment by dothebart** [comment]
Hi, did you upgrade to the latest 3.6 version as @maxkernbach told you?

**Comment by Simran-B** [comment]
@caozku Any success with the latest 3.6 version?

**Comment by maxkernbach** [comment]
Hi @caozku,

Could you please provide more details as requested earlier? Otherwise it is difficult to investigate this issue.
