### ISSUE TITLE
database status always is inactive

### ISSUE THREAD

**Issue by realdog** [arangodb/arangodb#1338]
I created the "db1" database. I do notice, that it says "inactive" on its icon, while _system says "active",....what's that mean, how to  change it ...... 
system: mac os
arangodb version: 2.5.4
There is a issue is same  question.........https://github.com/arangodb/arangodb/issues/832

**Comment by jsteemann** [comment]
As far as I can see, the "active" / "inactive" tagging in the web interface is only used for indicating the currently selected database. The currently selected database is marked "active", and all others are marked "inactive". Apart from that, the labeling doesn't mean anything. I think it's confusing and will check if we can remove the labeling easily.

**Comment by hkernbach** [comment]
I agree to Jan, it is just confusing. The "active"/"inactive" label is now gone. e4f7a571df27a8fd7ece2a19fe923ecb119fdf4f
