### ISSUE TITLE
Compilation fails with GCC 5.1

### ISSUE THREAD

**Issue by sleepycat** [arangodb/arangodb#1339]
Arango, or more specifically, the version of V8 that it bundles fails to compile under gcc 5.1:
```
../src/bignum.cc: In member function ‘void v8::internal::Bignum::AssignDecimalString(v8::internal::Vector<const char>)’:
../src/bignum.cc:82:6: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
 void Bignum::AssignDecimalString(Vector<const char> value) {
      ^
  CXX(target) /home/mike/projects/arangodb_pkg-git/src/arangodb/3rdParty/V8-3.31.74.1/out/x64.release/obj.target/v8_base/src/compiler/js-context-specialization.o
  CXX(target) /home/mike/projects/arangodb_pkg-git/src/arangodb/3rdParty/V8-3.31.74.1/out/x64.release/obj.target/v8_base/src/compiler/js-generic-lowering.o
cc1plus: all warnings being treated as errors
tools/gyp/v8_base.target.x64.release.mk:451: recipe for target '/home/mike/projects/arangodb_pkg-git/src/arangodb/3rdParty/V8-3.31.74.1/out/x64.release/obj.target/v8_base/src/bignum.o' failed
make[2]: *** [/home/mike/projects/arangodb_pkg-git/src/arangodb/3rdParty/V8-3.31.74.1/out/x64.release/obj.target/v8_base/src/bignum.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/mike/projects/arangodb_pkg-git/src/arangodb/3rdParty/V8-3.31.74.1/out'
Makefile:293: recipe for target 'x64.release' failed
make[1]: *** [x64.release] Error 2
make[1]: Leaving directory '/home/mike/projects/arangodb_pkg-git/src/arangodb/3rdParty/V8-3.31.74.1'
Makefile:9650: recipe for target '.v8-build-64' failed
make: *** [.v8-build-64] Error 2
```

```
mike@longshot> gcc -v                                                                                           ~/projects/arangodb_pkg-git
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-unknown-linux-gnu/5.1.0/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: /build/gcc/src/gcc-5-20150519/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --disable-multilib --disable-werror --enable-checking=release --with-default-libstdcxx-abi=c++98
Thread model: posix
gcc version 5.1.0 (GCC)
```

**Comment by dothebart** [comment]
can you please post which configure options you use, an what the configure passes down to V8?
Over here the v8 build configures like that in the make process:
--------------------------------------------------------------------------------
BUILDING V8
--------------------------------------------------------------------------------

cd ./3rdParty/V8-3.31.74.1 \
  && make \
        CFLAGS="-O2 -g " \
        CXXFLAGS="-O2 -g " \
        CC="gcc" \
        CC.host="gcc" \
        CXX="g++" \
        CXX.host="g++" \
        LINK="g++" \
        GYPFLAGS="-Dstandalone_static_library=1" \
        library=static strictaliasing=off snapshot=off werror=no x64.release

**Comment by dothebart** [comment]
I've updated the 3rdParty/Makefile.v8; If you want to retry it, please replace it with the most recent version ( https://raw.githubusercontent.com/arangodb/arangodb/devel/3rdParty/Makefile.v8 ) and re-run make setup, and the rest of your compile process.

**Comment by sleepycat** [comment]
I pulled devel and compiling again and it compiles fine. I just get a warning now:

```
../src/bignum.cc: In member function ‘void v8::internal::Bignum::AssignDecimalString(v8::internal::Vector<const char>)’:
../src/bignum.cc:82:6: warning: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Wstrict-overflow]
```

**Comment by dothebart** [comment]
Ok, great. Closing as resolved.

**Comment by AthonyLi** [comment]
**### cd ./3rdParty/V8-4.3.61 \
	    export GYPFLAGS="-Dstandalone_static_library=1 -Dlinux_use_bundled_gold=0 -Dlinux_use_gold_flags=0" \
	  && make \
		CC="gcc" \
		CC.host="gcc" \
		CXX="g++" \
		CXX.host="g++" \
		LINK="g++" \
		CFLAGS="-O0 -ggdb -DV8_TARGET_ARCH_X64 -DENABLE_GDB_JIT_INTERFACE -DV8_DEPRECATION_WARNINGS -DV8_I18N_SUPPORT -DGTEST_HAS_POSIX_RE=0 -DGTEST_LANG_CXX11=0 -DUNIT_TEST -DGTEST_HAS_RTTI=0 -DENABLE_DISASSEMBLER -DV8_ENABLE_CHECKS -DOBJECT_PRINT -DVERIFY_HEAP -DDEBUG -DENABLE_EXTRA_CHECKS -DENABLE_HANDLE_ZAPPING -DOPTIMIZED_DEBUG  " \
		CXXFLAGS="-O0 -ggdb -DV8_TARGET_ARCH_X64 -DENABLE_GDB_JIT_INTERFACE -DV8_DEPRECATION_WARNINGS -DV8_I18N_SUPPORT -DGTEST_HAS_POSIX_RE=0 -DGTEST_LANG_CXX11=0 -DUNIT_TEST -DGTEST_HAS_RTTI=0 -DENABLE_DISASSEMBLER -DV8_ENABLE_CHECKS -DOBJECT_PRINT -DVERIFY_HEAP -DDEBUG -DENABLE_EXTRA_CHECKS -DENABLE_HANDLE_ZAPPING -DOPTIMIZED_DEBUG  " \
		debug=on v8_optimized_debug=0 v8_enable_backtrace=on \
		library=static strictaliasing=off snapshot=off werror=no x64.debug**


this is my v8 build configures,
and make fault is :
make[1]: Entering directory `/home/hewei/arangodb-2.8/3rdParty/V8-4.3.61'
make[2]: Entering directory `/home/hewei/arangodb-2.8/3rdParty/V8-4.3.61/out'
  LINK(target) /home/hewei/arangodb-2.8/3rdParty/V8-4.3.61/out/x64.debug/shell
collect2: fatal error: cannot find 'ld'
compilation terminated.

@dothebart    can you help me ?

**Comment by jsteemann** [comment]
@AthonyLi : can you run `make V=1` and show its output?
Additionally, can you run `which ld`, as it seems the ld binary cannot be found by the make process.

**Comment by AthonyLi** [comment]
@jsteemann ：
[hewei@localhost arangodb-2.8]$ make v=1

--------------------------------------------------------------------------------
BUILDING V8
--------------------------------------------------------------------------------

cd ./3rdParty/V8-4.3.61 \
	  export GYPFLAGS="-Dstandalone_static_library=1 -Dlinux_use_bundled_gold=0 -Dlinux_use_gold_flags=0" \
	  && make \
		CC="gcc" \
		CC.host="gcc" \
		CXX="g++" \
		CXX.host="g++" \
		LINK="g++" \
		CFLAGS="-O0 -ggdb -DV8_TARGET_ARCH_X64 -DENABLE_GDB_JIT_INTERFACE -DV8_DEPRECATION_WARNINGS -DV8_I18N_SUPPORT -DGTEST_HAS_POSIX_RE=0 -DGTEST_LANG_CXX11=0 -DUNIT_TEST -DGTEST_HAS_RTTI=0 -DENABLE_DISASSEMBLER -DV8_ENABLE_CHECKS -DOBJECT_PRINT -DVERIFY_HEAP -DDEBUG -DENABLE_EXTRA_CHECKS -DENABLE_HANDLE_ZAPPING -DOPTIMIZED_DEBUG  " \
		CXXFLAGS="-O0 -ggdb -DV8_TARGET_ARCH_X64 -DENABLE_GDB_JIT_INTERFACE -DV8_DEPRECATION_WARNINGS -DV8_I18N_SUPPORT -DGTEST_HAS_POSIX_RE=0 -DGTEST_LANG_CXX11=0 -DUNIT_TEST -DGTEST_HAS_RTTI=0 -DENABLE_DISASSEMBLER -DV8_ENABLE_CHECKS -DOBJECT_PRINT -DVERIFY_HEAP -DDEBUG -DENABLE_EXTRA_CHECKS -DENABLE_HANDLE_ZAPPING -DOPTIMIZED_DEBUG  " \
		debug=on v8_optimized_debug=0 v8_enable_backtrace=on \
		library=static strictaliasing=off snapshot=off werror=no x64.debug
make[1]: Entering directory `/home/hewei/arangodb-2.8/3rdParty/V8-4.3.61'
make[2]: Entering directory `/home/hewei/arangodb-2.8/3rdParty/V8-4.3.61/out'
  LINK(target) /home/hewei/arangodb-2.8/3rdParty/V8-4.3.61/out/x64.debug/shell
collect2: fatal error: cannot find 'ld'
compilation terminated.
make[2]: *** [/home/hewei/arangodb-2.8/3rdParty/V8-4.3.61/out/x64.debug/shell] Error 1
make[2]: Leaving directory `/home/hewei/arangodb-2.8/3rdParty/V8-4.3.61/out'
make[1]: *** [x64.debug] Error 2
make[1]: Leaving directory `/home/hewei/arangodb-2.8/3rdParty/V8-4.3.61'
make: *** [.v8-build-64] Error 2

[hewei@localhost arangodb-2.8]$ which ld
/usr/local/bin/ld
These errors, always say can not find ‘ld'  ， Looking forward to you can help me to solve it!

**Comment by dothebart** [comment]
ok, its not passing the verbose into the V8 build. Try it like that:
```
cd /home/hewei/arangodb-2.8/3rdParty/V8-4.3.61/out
make VERBOSE=1 V=1
```
and

**Comment by AthonyLi** [comment]
@dothebart  ：Are you sure it's make here? Here make is wrong.
[hewei@localhost out]$ make VERBOSE=1 V=1
make: *** No targets specified and no makefile found.  Stop.

**Comment by dothebart** [comment]
hm, maybe one layer up? try to find `Makefile`s that could be right. maybe its in  an x64 subdirectory.

**Comment by AthonyLi** [comment]
Well, I have found the path make VERBOSE = 1 V = 1 then the following mistakes, I create a soft link settled, but appeared the following questions:

make[1]: /home/lilinyang/download/arangodb-2.8/3rdParty/V8-4.3.61/third_party/llvm-build/Release+Asserts/bin/clang++: Command not found
make[1]: *** [/home/lilinyang/download/arangodb-2.8/3rdParty/V8-4.3.61/out/ia32.release/obj.target/v8_base/src/accessors.o] Error 127
make[1]: Leaving directory `/home/lilinyang/download/arangodb-2.8/3rdParty/V8-4.3.61/out'
make: *** [ia32.release] Error 2

Well, this problem is solved, comes a new problem: [ question 2 ]
error: unknown warning option '-Wno-format-pedantic' [-Werror,-Wunknown-warning-option]

**Comment by AthonyLi** [comment]
@dothebart

**Comment by jsteemann** [comment]
@AthonyLi : it seems like the last `make` run hasn't picked up any of your settings. It looks like it's building with clang whereas in your original post (https://github.com/arangodb/arangodb/issues/1339#issuecomment-231258619) it looked like it had configured to use g++ for building. Additionally, it looks like it tried to build the 32 bit version of v8, which is probably not right.

Can you try reverting the build and re-running it via the following commands?
```
rm -f .v8-build-64 .zlib-build-64 .libev-build-64
(cd 3rdParty/V8-4.3.61 && make clean)
make clean
export CC="gcc"
export CXX="g++"
export CFLAGS="-O3"
export CXXFLAGS="-O3"
make setup
./configure <your options here>
make
```
That will build using g++, which obviously needs to be installed on the system. Before building, please make sure the tools are installed by running the following commands in the shell (each of which should print the path to the binary):
```
which gcc
which g++
which ld
```
If you plan to build with a different compiler, you need to adjust the CC and CXX environment variables.

**Comment by dothebart** [comment]
Quoting `3rdParty/V8-4.3.61/build/standalone.gypi `:

```
    'conditions':[
      ['(clang==1 or host_clang==1) and OS!="win"', {
        # This is here so that all files get recompiled after a clang roll and
        # when turning clang on or off.
        # (defines are passed via the command line, and build systems rebuild
        # things when their commandline changes). Nothing should ever read this
        # define.
        'defines': ['CR_CLANG_REVISION=<!(<(DEPTH)/tools/clang/scripts/update.sh --print-revision)'],
        'cflags+': [
          '-Wno-format-pedantic',
        ],
      }],
    ],
```
It seems that V8 expects a CLANG that knows this parameter (= is newer than the one you have) You could remove that section, to see whether a new compile attempt of V8 is successfull.

In my last attempt to compile ArangoDB 2.8 in a RHEL6 / Centos 6 chroot on a Debian machine I did:
```
# Initialize the chroot and install the required packages:
apt-get install yum rpm python-m2crypto
mkdir -p /var/tmp/centos/var/lib/rpm
wget http://mirror.centos.org/centos/6/os/x86_64/Packages/nss-softokn-freebl-3.14.3-23.el6_7.x86_64.rpm
rpm --root /var/tmp/centos --initdb
rpm -ivh --force-debian --nodeps --root /var/tmp/centos centos-release*rpm
rpm -ivh --force-debian --nodeps --root /var/tmp/centos nss-softokn-freebl-3.14.3-23.el6_7.x86_64.rpm 
#now the basic chroot is setup, install the basic packages required to compile ArangoDB:
yum --installroot /var/tmp/centos/ install yum
yum --installroot /var/tmp/centos/ -y install tar wget bzip2
yum --installroot /var/tmp/centos/ -y --nogpgcheck install devtoolset-3-gcc devtoolset-3-gcc-c++
yum --installroot /var/tmp/centos/ -y install centos-release-scl-rh
#Now enter the chroot to start compiling
chroot /var/tmp/centos
# This prepares the environment to use the gcc 3 toolset:
scl enable devtoolset-3 bash
wget https://www.arangodb.com/repositories/Source/ArangoDB-2.8.10.tar.bz2
tar -xvjf ArangoDB-2.8.10.tar.bz2
cd ArangoDB-2.8.10
# I wanted a debug enabled ArangoDB:
export CFLAGS='-O0 -ggdb'; export CXXFLAGS='-O0 -ggdb';./configure
make
#Obviously something went wrong with gyp too, I did:
cd 3rdParty/V8-4.3.61/
export GYPFLAGS="-Dstandalone_static_library=1 -Dlinux_use_bundled_gold=0 -Dlinux_use_gold_flags=0" 
make                 CC="gcc"                 CC.host="gcc"                 CXX="g++"                 CXX.host="g++"                 LINK="g++"                 CFLAGS="-O3 -fomit-frame-pointer -g  "                 CXXFLAGS="-O3 -fomit-frame-pointer -g  "                 library=static strictaliasing=off snapshot=off werror=no x64.release
#back to the main ArangoDB source tree:
cd ../../
make
```

**Comment by AthonyLi** [comment]
@dothebart  
I according to your steps：
    cd 3rdParty/V8-4.3.61/
    export GYPFLAGS="-Dstandalone_static_library=1 -Dlinux_use_bundled_gold=0 
                                   -Dlinux_use_gold_flags=0" 
    make  CC="gcc"  CC.host="gcc"  CXX="g++"  CXX.host="g++"  LINK="g++" 
              CFLAGS="-O3 -fomit-frame-pointer -g  "  CXXFLAGS="-O3 -fomit-frame-pointer -g  "        
              library=static strictaliasing=off snapshot=off werror=no x64.release

appeared the following error：
    gcc: error: unrecognized command line option '-03'
    make[1]: *** [/home/lilinyang/download/arangodb-2.8.10/ArangoDB-2.8.10/3rdParty/V8- 
                    4.3.61/out/x64.release/obj.target/icui18n/third_party/icu/source/i18n/decContext.o] Error 1
    make[1]:   Leaving directory  
                   `/home/lilinyang/download/arangodb2.8.10/ArangoDB-.8.10/3rdParty/V8-4.3.61/out'
    make: *** [x64.release] Error 2

**Comment by AthonyLi** [comment]
@jsteemann 
I‘m try to revert the build as your commands，and appearing error：C++ compiler cannot create executables

**Comment by AthonyLi** [comment]
@dothebart  @jsteemann  

Thank you, I feel should be arangodb before download the source code is wrong, lead to a lot of mistakes, I downloaded @ dothebart to the source code There are only two mistakes, then solved successful, thank you very much

--------------------------------------------------------------------------------
BUILDING etcd
--------------------------------------------------------------------------------

cd ./3rdParty/etcd && ./build
cp ./3rdParty/etcd/bin/etcd ./bin/etcd-arango
strip ./bin/etcd-arango

--------------------------------------------------------------------------------
BUILD etcd FINISHED
--------------------------------------------------------------------------------

make[1]: Leaving directory `/home/lilinyang/download/arangodb-2.8.10/ArangoDB-2.8.10'

**Comment by dothebart** [comment]
Great! Nice you got it working.
