### ISSUE TITLE
Can not set inBackground option in View

### ISSUE THREAD

**Issue by AntoineAA** [arangodb/arangodb#13414]
## My Environment

* __ArangoDB Version__:       3.7.3
* __Storage Engine__:             RocksDB
* __Deployment Mode__:      Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               
* __Infrastructure__:               own
* __Operating System__:       18.04
* __Total RAM in your machine__:       16Gb
* __Disks in use__:        HDD
* __Used Package__:              Debian or Ubuntu .deb

## Component, Query & Data

__Affected feature__:
Update ArangoDB View using web interface.

__Dataset__:
View based on one collection with 790M documents.
Example: 
```
{
    "_key": "10674927",
    "_id": "z_users/10674927",
    "_rev": "_XGBeK----_",
    "email": "***",
    "username": "***",
    "firstname": "***",
    "lastname": "***",
    "date_created": 1530501829979,
    "date_updated": 1530501829979,
    "roles": [
      "ROLE_MUSER"
    ],
    "enabled": true,
    "unsubscribed": false,
    "password": "***",
    "salt": "***",
    "computed": {
      "displayed_name": "***"
    }
}
```

## Steps to reproduce

1. Create the view using web interface.
2. Update the view using web interface and add `inBackground: true`:
```
{
  "writebufferIdle": 64,
  "type": "arangosearch",
  "writebufferSizeMax": 33554432,
  "consolidationPolicy": {
    "type": "tier",
    "segmentsBytesFloor": 2097152,
    "segmentsBytesMax": 5368709120,
    "segmentsMax": 10,
    "segmentsMin": 1,
    "minScore": 0
  },
  "primarySort": [],
  "globallyUniqueId": "hC9B524A1A5B3/13368217362",
  "id": "13368217362",
  "storedValues": [],
  "writebufferActive": 0,
  "consolidationIntervalMsec": 10000,
  "cleanupIntervalStep": 2,
  "commitIntervalMsec": 1000,
  "links": {
    "z_users": {
      "analyzers": [
        "text_en"
      ],
      "fields": {
        "username": {},
        "firstname": {}
      },
      "includeAllFields": true,
      "storeValues": "none",
      "trackListPositions": false,
      "inBackground": true
    }
  },
  "primarySortCompression": "lz4"
}
```
3. The document is updated but the option is not set.
4. SEARCH operations work, but there is a lock while indexing.

__Problem__:
I can't set the `inBackground: true` option.

__Expected result__:
Set `inBackground` option to `true`.

**Comment by AntoineAA** [comment]
Edit: the `inBackground` is not kept in the document while reopening it:
```
"links": {
    "z_users": {
      "analyzers": [
        "text_en"
      ],
      "fields": {
        "username": {},
        "firstname": {}
      },
      "includeAllFields": true,
      "storeValues": "none",
      "trackListPositions": false
    }
```

**Comment by Simran-B** [comment]
It is expected that the option "vanishes". It is a one-off option that is not persisted in the View definition. This this also the case with regular collection indexes.

Indexing should take place in background if you set `inBackground: true` when you add the link "z_users". First adding the link, then updating the View with `inBackground: true` might be ignored. Any change to a link should re-build the internal index, as it is immutable. But since `inBackground` is not a View property, it might not count as a change.

**Comment by AntoineAA** [comment]
Hello,

If I want to be able to use `inBackground` option, do I have to add it when I add the link?

Are these steps correct?

- Create the view
- Edit the view and add the link on `z_users` collection with `inBackground: true`
- Save the view

**Comment by Simran-B** [comment]
Sorry for the delay, yes setting the inBackground attribute when adding a link should do the trick.

**Comment by maxkernbach** [comment]
Hi @AntoineAA,

does the latest suggestion work?

**Comment by AntoineAA** [comment]
Hi,
Sorry for the delay.
It works, thank you!
