### ISSUE TITLE
Devel documentation - problems with line breaks etc.?

### ISSUE THREAD

**Issue by CoDEmanX** [arangodb/arangodb#1342]
I just spotted several occurrences of `<<EOF` and `EOF` in the example requests, and there seem to be some line breaks missing. Here's an example:

https://docs.arangodb.com/devel/HttpTransaction/index.html

Seems like a programmtic error in the docs generation process to me.

**Comment by fceller** [comment]
Do you refer to

﻿shell> curl -X POST --data-binary @- --dump - http://localhost:8529/_api/transaction <<EOF
{ 
  "collections" : { 
    "read" : "products" 
  }, 
  "action" : "function () { throw 'doh!'; }" 
}
EOF

This is actually an example, that you can past into your bash (including the <<EOF & EOF) to run CURL.

**Comment by CoDEmanX** [comment]
I see, so curl supports a HEREDOC-like syntax (PHP), so you can post large payload text until the defined end marker is found in the stream, which may contain line breaks.

The "missing" line breaks are not actually missing, it's rather a compacted function string, since I looked specifically at a transaction example. Riddle solved!

**Comment by dothebart** [comment]
well, not completely. the HERE documents in this case are actually implemented by your shell. 
<< redirects them into curls stdin. 
The previous way of doing the examples didn't work in some environments.
(well, this one actually doesn't work in cmd.exe doh')
