### ISSUE TITLE
Debian/Ubuntu production grade cluster configuration

### ISSUE THREAD

**Issue by NetwarSystem** [arangodb/arangodb#13421]
I am relatively new to Arango and have one instance running in production, on Ubuntu 20.04 with Enterprise 3.7.6. This will become a companion to Elasticsearch and I want to get it running as a cluster of three systems. The lack of examples in this area is truly mystifying.

I know about the example with three starter based cluster members, works fine for testing on my workstation, what I need are an arangodb.conf and and an arangodb3.service that shows how to get systems to talk to each other. My current config can be seen here:

https://gist.github.com/NetwarSystem/b9ef044b0fd87c99363cd31ec96c9deb

When I start Arango, I see only port tcp/8529 open. I've just started looking at arangod --help and I see a lot of options for both agency and cluster. I don't want to sit here spending hours trying various permutations of options to see which one finally yields something that will restart gracefully when a system is rebooted.

**Comment by dothebart** [comment]
Hi, 
Thats why we created the arangostarter, so it does all the work for you? 
The other rather more up to date way would be to use k8s and the operator to take care of this?
Most other users tend to use (if not the above two) docker-compose.yml files.

**Comment by NetwarSystem** [comment]
Arangostarter is just for learning, not for production, right?

I just want some combination of arangodb.conf and/or arangodb3e.service such that when Arango machines restart they wake up looking to join their cluster. Is it normal for cluster builders to wrap arangostarter with their own systemd service files? I can do that, but it seems ... awkward.

We don't have k8s or Docker in production, would take something very compelling for me to introduce that added complexity to our current environment.

So nobody just has a blog post or Gist that shows full working config files??

**Comment by dothebart** [comment]
Hi, 
the starter is absolutely meant to be used in production too
However, all packaged deployments by default are meant to be single server deployments - the starter came a bit later, and wasn't yet added to the debian packages - this can happen sooner or later. 
The advantage of the k8s is that it can better handle failure situation, where new pods should be started.

**Comment by NetwarSystem** [comment]
So I just do what is needed with the starter, then wrap it in a systemd service? That almost seems too easy :-)

I like the notion of containers, but I cringe every time I look at IP addressing on a machine set up to run them. My system isn't big enough (yet) to need orchestration. Maybe one day, if we keep growing as we have been.

Thanks, closing this.
