### ISSUE TITLE
Graph simple traversal very slowly

### ISSUE THREAD

**Issue by shiwxyz** [arangodb/arangodb#13429]
## My Environment

* __ArangoDB Version__:        3.4.5
* __Storage Engine__:             RocksDB 
* __Deployment Mode__:       Single Server 
* __Deployment Strategy__:    Manual Start in Docker
* __Configuration__:               default
* __Infrastructure__:               own
* __Operating System__:        
* __Total RAM in your machine__:        270GB
* __Disks in use__:        HDD
* __Used Package__:     Docker - official Docker library

## Component, Query & Data

__Affected feature__:
AQL query

__AQL query (if applicable)__:
```
FOR v, e, p IN 1..1 ANY 'matrix_archive_core/PERSON_4630462646930375299' matrix_relationship_dynamic_edge_core
 FILTER e.relType == 'peer'
 RETURN {"vertex": v, "edge": e}
```
__AQL explain and/or profile (if applicable)__:
Query String:
``` FOR v, e, p IN 1..1 ANY 'matrix_archive_core/PERSON_4628102529383661569' 
 matrix_relationship_dynamic_edge_core
  FILTER e.relType == 'peer'
  RETURN {"vertex": v, "edge": e}

Execution plan:
 Id   NodeType          Est.   Comment
  1   SingletonNode        1   * ROOT
  2   TraversalNode        2     - FOR v  /* vertex */, e  /* edge */ IN 1..1  /* min..maxPathDepth */ ANY 'matrix_archive_core/PERSON_4628102529383661569' /* startnode */  matrix_relationship_dynamic_edge_core
  3   CalculationNode      2       - LET #5 = (e.`relType` == "peer")   /* simple expression */
  4   FilterNode           2       - FILTER #5
  5   CalculationNode      2       - LET #7 = { "vertex" : v, "edge" : e }   /* simple expression */
  6   ReturnNode           2       - RETURN #7

Indexes used:
 By   Type   Collection                              Unique   Sparse   Selectivity   Fields        Ranges
  2   edge   matrix_relationship_dynamic_edge_core   false    false            n/a   [ `_to` ]     base INBOUND
  2   edge   matrix_relationship_dynamic_edge_core   false    false            n/a   [ `_from` ]   base OUTBOUND

Traversals on graphs:
 Id  Depth  Vertex collections  Edge collections                       Options                                  Filter / Prune Conditions
 2   1..1                       matrix_relationship_dynamic_edge_core  uniqueVertices: none, uniqueEdges: path                           

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   move-calculations-up-2
  4   move-filters-up-2
  5   optimize-traversals
```
__Dataset__:
Vertex with id "PERSON_4628102529383661569" has a little over 1k edges. 

Size of your Dataset on disk:
5,000,000 vertices and 300,000,000 edges

__Replication Factor & Number of Shards (Cluster only)__:
Vertex and edge replication factor is 0

## Steps to reproduce

1. 
2. 
3. 

__Problem__:
when I query this aql,it spent over 20 seconds to return the result!It is too slowly!
And I try to find the same problem,but I can't find it!
The first method:
So I try to add the hash index for the 'relType' by arangoshell,and I do it.
Then I try to query again,and see the explain,however,the index of the 'relType' is invalid!
The second method:
I try to query the edge which contain 'relType == peer',not query all the graph!
I think it will return the result quickly,however it is also slowly!

When I find the solution,I found the memory of arango is high almost take up the total memory 90%,it is crazy.
I don't know what the problem to cause this!And I restart the arango,the memory decrease obviously！

__Expected result__:

**Comment by dothebart** [comment]
Hi, Please note that ArangoDB 3.4 is EOLed since 6 months now. 
Please upgrade to a later Version, and report back whether the problem persists.

**Comment by Simran-B** [comment]
Apart from using a more recent version, you may want to try vertex-centric indices:
- https://www.arangodb.com/docs/stable/indexing-index-basics.html#vertex-centric-indexes
- https://www.arangodb.com/docs/devel/indexing-vertex-centric.html
Adding indexes to `relType` alone won't help, as the edge index is used for the traversal. Only vertex-centric indices as a specialization of an edge index are suitable to speed up traversals.

**Comment by shiwxyz** [comment]
Hi,Simran,thank you for your reply!I found that index of 'relType' is invalid for my traversal!I think the path of the graph traversal is the vertex-centric indices,and it was valid!Maybe my solution misleading you!
The question is why a simple AQL take so much time to query!
I've decreased the data these days,the size of all collections is about 50,000,000,is still query slowly!
And then I restart arango,after 1days ago,the memory of arango increase quickly,and can't relase!
I don't know how to solve this problem although I have decrease the data!
I will appreciate that you can help me!

**Comment by shiwxyz** [comment]
![image](https://user-images.githubusercontent.com/44423210/106360200-28ecae80-6352-11eb-8f49-c8d2e593a8b8.png)
Simran,look this image,the memory decrease whenI resart the arango,however a few days later the memory increased to the same level  as before the restart!My program is to claer the data and then insert everyday!

**Comment by dothebart** [comment]
Hi, which version of arangodb are you running now?

**Comment by shiwxyz** [comment]
Hi,dothebart!I still use 3.4.5 because the ArangoDB was intalled in production environment.
 I try to migrate the data of ArangoDB to SSD and test the traversal performance!
I think the poor traversal performance is related to the hardware!
When I traverse after insert,is very quickly,the data maybe  stored in the buffer cache.And after a few hours later,is slowly,the data maybe flush to the disk.

**Comment by dothebart** [comment]
closing as EOL.

**Comment by dothebart** [comment]
Please have a look at
https://www.arangodb.com/2017/10/performance-analysis-pyarango-usage-scenarios/ about doing benchmarks. 
https://www.arangodb.com/docs/stable/tutorials-reduce-memory-footprint.html explains how the rocksdb block cache etc. works. 
Please note that details may be different for older versions.
