### ISSUE TITLE
brew formula is out of date

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangodb#1343]
https://github.com/Homebrew/homebrew/blob/master/Library/Formula/arangodb.rb

**Comment by fceller** [comment]
https://github.com/Homebrew/homebrew/pull/40123

**Comment by pekeler** [comment]
Thanks!

**Comment by pekeler** [comment]
Looks like Homebrew is behind again (2.5.5).

**Comment by fceller** [comment]
https://github.com/Homebrew/homebrew/pull/40346

**Comment by pekeler** [comment]
Thanks!

**Comment by pekeler** [comment]
2.8.7 please :)

**Comment by fceller** [comment]
Sorry, homebrew changed it structure. Pull request is now opened in current repo.
