### ISSUE TITLE
Arangosearch with Python

### ISSUE THREAD

**Issue by couleurwest** [arangodb/arangodb#13457]
I restart on Arango but time is not my friend.
I use arango with python (python-arango), I create views, it works but not with python. I have no values ​​going down. I'm lost

**Comment by dothebart** [comment]
Hi, 
looking at https://python-driver-for-arangodb.readthedocs.io/en/master/view.html - whats missing?

**Comment by couleurwest** [comment]
Thx.

It's ok i forget to initialzed the only collection i need... all... just the one
