### ISSUE TITLE
 [23309] ERROR [405f9] duplicate entry for collection name

### ISSUE THREAD

**Issue by spoh-ally** [arangodb/arangodb#13454]
## My Environment

* __ArangoDB Version__:        3.7.2
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   ArangoDB Starter 
* __Configuration__:               3 nodes clustered
* __Infrastructure__:               physical servers
* __Operating System__:        RHEL 8.1
* __Total RAM in your machine__:        
* __Disks in use__:        
* __Used Package__:              

## Component, Query & Data

__Affected feature__:

__AQL query (if applicable)__:
```


```
__AQL explain and/or profile (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. restarted cluster with `arabgod --starter.join=<IP1>:8528,<IP2>:8528,<IP3>:8528 --auth.jwt-secret=secert.jwt` command to reset db connections
2. cannot start one of three cluster nodes with some errors, including collection name duplication, etc.

__Problem__:
cannot start one of three cluster node with these errors,

[23309] ERROR [405f9] duplicate entry for collection name 's12010684'. collection id 16010048 has same name as already added collection 14010063
[23309] ERROR [8d427] {engines} error while opening database: duplicate entry for collection name 's12010684'. collection id 16010048 has same name as already added collection 14010063

__Expected result__:

**Comment by Simran-B** [comment]
Was the cluster running and shut down normally? Is there any chance that a second collection with the same name was created while the cluster health was not okay, e.g. during a network partition? Can you share the server logs?

What was the configuration like, what replication factors and number of shards?

It would be great to get an agency dump or insight into what the current state is like. If only one of the nodes cannot join, could you try to add a fresh node (new database folder)?

**Comment by spoh-ally** [comment]
Hi Sirman,

The server doesn't have any event when I restart the cluster with Arango Starter (arangodb --starter.data-dir=<Dir> --sterter.join=<IP1>:8528,<IP2>:8528,<IP3>:8528 --auth.jwt-secret=<jwtfile name>) 
the replication factor is 1 and when I tried to with a new database folder with arangodb Starter, it says 'ArangoDB Starter listening on 0.0.0.0:8528" and nothing happen.

**Comment by spoh-ally** [comment]
Hello,
Can I get some advice on how I can shut down the Arango cluster safely? I usually kill the Arangodb PID, like 'kill 1234', to test its availability. And use 'arangodb --starter.join=xxxxx:8528,yyyy:8528,zzzz:8528 --auth.jwt-secrete=jwt.sec' to make it alive.
And what happens if I shut down one of three cluster nodes by force? I think it should work even though they lost one of three nodes because it's clustered, right?
Thank you

**Comment by fceller** [comment]
Hi @spoh-ally ,

I will provide instructions through JIRA,

best Frank

**Comment by maxkernbach** [comment]
Data corruption resolved through JIRA by joining a new starter with the two running nodes.
