### ISSUE TITLE
advanced debug information for User Functions

### ISSUE THREAD

**Issue by antokara** [arangodb/arangodb#1345]
It would be really useful some (optionally enabled for performance) advanced debug information to be provided if possible when a warning/error occurs inside a user function when called.

at the moment the output I get is:

Warnings:
[1583], 'in function 'MYNAMESPACE::MYFUNCTION()': user function runtime error: TypeError: undefined is not a function'

which unfortunately does not indicate the line or some other position indicator of the problem that just occurred making the debug process really difficult in anything other than tiny functions...

**Comment by jsteemann** [comment]
The error message now contains a stack trace with positions local to the function code. 
The change has been pushed to devel, and will be included in the next 2.6 release.
