### ISSUE TITLE
3 cluster is not able to work while one node is down

### ISSUE THREAD

**Issue by NewClarence** [arangodb/arangodb#13451]
## My Environment

* __ArangoDB Version__:        3.3.22
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   ArangoDB Starter
* __Configuration__:               3 Nodes. Each Node having Agent,coordinator and DBServer
* __Infrastructure__:               own
* __Operating System__:       Red Hat Enterprise Linux Server release 7.4 (Maipo)
* __Total RAM in your machine__:        32Gb
* __Disks in use__:        HDD
* __Used Package__:              SUSE or RedHat .rpm

## Component, Query & Data

__Size of your Dataset on disk__:
respectively 40GB、44GB and 53GB in 3 Nodes

__Replication Factor & Number of Shards (Cluster only)__:
2 and 9

## Steps to reproduce

1. kill all processes, including Agent, Coordinator and DBServer in the first node, the remain two nodes stay alive and **the cluster is able to work**.
2. after the Replication Factor stays complete synchronization, kill all processes in the second node, including Agent, Coordinator and DBServer, the remain two nodes stay alive and **the cluster is able to work**.
3. after the Replication Factor stays complete synchronization, kill all processes in the third node, including Agent, Coordinator and DBServer, the remain two nodes stay alive and **the cluster is not able to work**.

__Problem__:
1. cluster is not able to work while one node is down
2. the leader shards in down node can't move to the follower shards in alive nodes
3. one possible reason is that there is a job in cluster blocking follow-up shard-moving

__Expected result__:
is there a method that can kill the job in cluster?

**Comment by dothebart** [comment]
Hi, 
please note that ArangoDB 3.3 isn't maintained anymore - see https://www.arangodb.com/subscriptions/end-of-life-notice/ for details. 
Please upgrade to a more recent version of ArangoDB and revalidate whether this issue still persists.

**Comment by Simran-B** [comment]
The cluster should continue to operate in principle. It's unclear why this is not the case for the third node. Can you check the replication factors of all collections, including system collections?

**Comment by liuxinq** [comment]
> Hi,
> please note that ArangoDB 3.3 isn't maintained anymore - see https://www.arangodb.com/subscriptions/end-of-life-notice/ for details.
> Please upgrade to a more recent version of ArangoDB and revalidate whether this issue still persists.

Thanks for your reply. Weeks ago, I had upgraded to 3.6.10, but the issue still reproduce. By the way, the same job in upgraded cluster is still blocking follow-up jobs, such as moving shards.

**Comment by liuxinq** [comment]
> The cluster should continue to operate in principle. It's unclear why this is not the case for the third node. Can you check the replication factors of all collections, including system collections?

Thanks for your reply. I'm sure that it doesn't include system collections. That's because of that I just set 2 replication factors for non-system collections.

**Comment by maxkernbach** [comment]
Hi @liuxinq,

Are you still facing this problem? In case you can reproduce the issue by getting the cluster into an unresponsive state, would it be possible to create an agency dump of this cluster state?

An agency dump can be produced following the steps in our documentation:
https://www.arangodb.com/docs/stable/troubleshooting-cluster-agency-dump.html

**Comment by Simran-B** [comment]
@liuxinq Can you provide an Agency dump as max described?
