### ISSUE TITLE
POST /_api/database returns HTTP 400

### ISSUE THREAD

**Issue by jchristn** [arangodb/arangodb#13460]
## My Environment

* __ArangoDB Version__:        3.7.6
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               Basic install on my laptop
* __Infrastructure__:               Own
* __Operating System__:        Windows 10
* __Total RAM in your machine__:        16GB
* __Disks in use__:        SSD
* __Used Package__:              Windows NSIS package

## Component, Query & Data

__Affected feature__: RESTful API

__AQL query (if applicable)__:
```
n/a
```
__AQL explain and/or profile (if applicable)__:
n/a

__Dataset__:
n/a

__Size of your Dataset on disk__:
n/a

__Replication Factor & Number of Shards (Cluster only)__:
n/a

## Steps to reproduce

Each time I ```POST``` to ```/_api/database```, it returns:
```
{
    "code": 400,
    "error": true,
    "errorMessage": "Permission denied",
    "errorNum": 2
}
```
It does this even though the database and associated users are actually created by the call.  I'm using the ```root``` account and basic auth.

Example:

1) GET /_api/database
```
{
    "error": false,
    "code": 200,
    "result": [
        "_system"
    ]
}
```

2) GET /_api/user
```
{
    "error": false,
    "code": 200,
    "result": [
        {
            "user": "root",
            "active": true,
            "extra": {}
        }
    ]
}
```

3) POST /_api/database
```
Request body:
{
    "name": "mydatabase",
    "options": {
        "sharing": "flexible",
        "replicationFactor": 3
    },
    "users": [
        {
            "username": "mydatabase",
            "passwd": "mydatabase",
            "active": true            
        }
    ]
}
Response:
{
    "code": 400,
    "error": true,
    "errorMessage": "Permission denied",
    "errorNum": 2
}
```

4) GET /_api/database (again)
```
{
    "error": false,
    "code": 200,
    "result": [
        "_system",
        "mydatabase"
    ]
}
```

5) GET /_api/user (again)
```
{
    "error": false,
    "code": 200,
    "result": [
        {
            "user": "root",
            "active": true,
            "extra": {}
        },
        {
            "user": "mydatabase",
            "active": true,
            "extra": {}
        }
    ]
}
```

__Problem__:

HTTP 400 status returned, even though the database and users are actually created.

This creates problems when integrating into a project because the code thinks the request failed.

__Expected result__:

HTTP 200/OK or 201/Created.

**Comment by cw00dw0rd** [comment]
I wasn't able to reproduce this on Windows 10 with ArangoDB 3.7.5 - works as expected for me.
I have exported the postman collection I used (remove the .txt extension and update the password). 

I have received that issue if for some reason the request was sent multiple times or when trying to perform some action with the database before it is ready.

Are you using a driver or how are you making these requests?

[ArangoDB.postman_collection.json.txt](https://github.com/arangodb/arangodb/files/5919664/ArangoDB.postman_collection.json.txt)

**Comment by jchristn** [comment]
Hi @cw00dw0rd I was using Postman as well.  I've attached the collection I was using here.  
[ArangoDB.postman_collection.json.txt](https://github.com/arangodb/arangodb/files/5920230/ArangoDB.postman_collection.json.txt)

Downloading yours to take a look.  Thanks for getting back to me.

**Comment by jchristn** [comment]
Note: I had ```username``` in the request body.  When I change it to ```user```, I get back the expected response.  

I'm not sure if the documentation is incorrect: https://www.arangodb.com/docs/stable/http/database-database-management.html

Specifically:
```
A JSON object with these properties is required:

name: Has to contain a valid database name.

options: Optional object which can contain the following attributes:

sharding: The sharding method to use for new collections in this database. Valid values are: “”, “flexible”, or “single”. The first two are equivalent. (cluster only)

replicationFactor: Default replication factor for new collections created in this database. Special values include “satellite”, which will replicate the collection to every DB-Server (Enterprise Edition only), and 1, which disables replication. (cluster only)

writeConcern: Default write concern for new collections created in this database. It determines how many copies of each shard are required to be in sync on the different DB-Servers. If there are less then these many copies in the cluster a shard will refuse to write. Writes to shards with enough up-to-date copies will succeed at the same time however. The value of writeConcern can not be larger than replicationFactor. (cluster only)

users: Has to be an array of user objects to initially create for the new database. User information will not be changed for users that already exist. If users is not specified or does not contain any users, a default user root will be created with an empty string password. This ensures that the new database will be accessible after it is created. Each user object can contain the following attributes:

username: Login name of the user to be created.  <<<<<<<<<

passwd: The user password as a string. If not specified, it will default to an empty string.

active: A flag indicating whether the user account should be activated or not. The default value is true. If set to false, the user won’t be able to log into the database. The default is true.

extra: A JSON object with extra user information. It is used by the web interface to store graph viewer settings and saved queries. Should not be set or modified by end users, as custom attributes will not be preserved.
```

**Comment by cw00dw0rd** [comment]
If I send a request with the following body, it works as expected:
```
{
    "name": "mydatabase",
    "options": {
        "sharing": "flexible",
        "replicationFactor": 3
    },
    "users": [
        {
            "user": "mydatabase",
            "passwd": "mydatabase",
            "active": true            
        }
    ]
}
```

The documentation appears to be correct in that it accepts `username.` However, I tested just using `user` as you mentioned and found that it also works with that field. It does not take any other options for that field, though, only `username` and `user.`

**Comment by jchristn** [comment]
Well, I don't know what's happening.  I deleted everything (databases, graphs, users, collections, etc), and it's just working fine.  Not sure why it happened, or if there was some remnant there before.  I'll close this out and re-open if it happens again.  Thanks for your help.
