### ISSUE TITLE
AQL & Transactions - possible?

### ISSUE THREAD

**Issue by clintwood** [arangodb/arangodb#1346]
Is it possible to execute one or more AQL (modification) queries (as one or more `db._query(...)` statements from within the `"action":` attribute function passed via the transaction HTTP API?

My understanding is that it is only possible to execute a single data modification AQL query at a time via either `db_query(...)` function or the HTTP API which means it is difficult (impossible?) to achieve transactions that span AQL data modification queries.

What would be great is the ability to execute more than one AQL data modification query within a single query to said APIs (my assumption is that an AQL query is wrapped in a transaction)

Can someone explain how this can be achieved if at all?

**Comment by dothebart** [comment]
I started out a little different. I've loaded the graph data like this
    arangosh [_system]> require("internal").load("/local/home/me/ArangoDB-Data/Graphs/IMDB/import.js")

After waiting for a while, I now can see the graph (by default with two nodes) in the graph viewer.
Did you Follow
https://www.arangodb.com/2013/11/visualize-graphs-screencast/
?

**Comment by jsteemann** [comment]
@clintwood: When executed in isolation, `db._query()` will issue a single AQL query in a transactional fashion.
When using the HTTP API for transactions (or the server-side `db._executeTransaction() function, it is possible to execute more than one AQL query inside, still with transactional capabilities, e.g.
```js
db._executeTransaction({
  collections: { 
    write: [ "foo", "bar" ]
  },
  action: function () {
    var db = require("org/arangodb").db;
    db._query("FOR doc IN foo FILTER doc.value == 23 REMOVE doc._key IN foo");
    db._query("FOR doc IN bar FILTER doc.value == 42 REMOVE doc._key IN bar");
  }
});
```
Note that the union of all used collections from all AQL queries will need to be specified in the `collections` attribute of the transaction then.

**Comment by clintwood** [comment]
@jsteemann, that is excellent news!

One further question,  Is there any way or any plans to support executing multiple AQL queries directly within an AQL script? e.g. (HTTP API):
```
{
  "query": "FOR doc IN foo FILTER doc.value == 23 REMOVE doc._key IN foo;" +
           "FOR doc IN bar FILTER doc.value == 42 REMOVE doc._key IN bar;"
}
```
This would obviously be within the context of a single transaction.

**Comment by jsteemann** [comment]
@clintwood: putting multitple AQL queries into one query string will currently not work. AQL will choke on the semicolon and abort parsing there.
Though this may be supported in the future. We have some ideas for improved transaction handling, but I cannot tell you when these plans will be accomplished and what the exact outcome will be. This is still too vague at the moment so I don't want to make any false promises yet.

**Comment by clintwood** [comment]
All good... thanks for your quick response and ArangoDB.

**Comment by ixxie** [comment]
Does the ArangoDB team have an update on whether AQL native transactions are in the roadmap in the foreseeable future?

**Comment by Simran-B** [comment]
Another transaction API was added in 3.5:
> Stream Transaction API: Perform multi-document transactions with individual begin and commit / abort commands using the new HTTP endpoints or via a supported driver.

https://www.arangodb.com/docs/stable/http/transaction-stream-transaction.html
