### ISSUE TITLE
arangorestore: create database if not exists

### ISSUE THREAD

**Issue by legikaloz** [arangodb/arangodb#1347]
After a fresh database install I've to create the target database manually before using arangorestore. Please create the database if not exists.

**Comment by jsteemann** [comment]
*arangorestore* now provides the option `--create-database <bool>`.

Setting this option to `true` will create the target database if it does not exist. When creating the target database, the username and passwords passed to arangorestore will be used to create an initial user for the new database.

The default value for the option is `false`.
