### ISSUE TITLE
arangodump into client packages?

### ISSUE THREAD

**Issue by legikaloz** [arangodb/arangodb#1348]
It would be grat to create a dump from a client, where only arangodb-client package installed.

**Comment by jsteemann** [comment]
Makes perfect sense.
I have added the `arangoimp`, `arangodump`, `arangorestore` and `arangob` client programs to the *arangodb-client* package. If the builds complete successfully, the next 2.6 *arangodb-client* package will contain them all.

**Comment by legikaloz** [comment]
:thumbsup:

**Comment by jsteemann** [comment]
Builds look good so far: https://build.opensuse.org/package/show/home:fceller:unstable/arangodb-2.6
