### ISSUE TITLE
Error handling in generated Foxx apps

### ISSUE THREAD

**Issue by fceller** [arangodb/arangodb#1349]
The generated Foxx app only generates an error handling for "delete", But not for the other methods.

**Comment by jsteemann** [comment]
Seems that something the following is missing in foxx/templates/controller.js.tmpl for other HTTP methods, e.g. when HTTP GETting a non-existing model:

```js
.errorResponse(ArangoError, 404, 'The <%= modelInstance %> could not be found');
```

Additionally, requests that trigger joi validation errors are returned with HTTP response code 200, but it's probably better if they returned HTTP 400 instead.

**Comment by pluma** [comment]
I've added the missing `errorResponse`s.

The validation doesn't currently seem to be used by the generator at all, though, but that's a different issue.
