### ISSUE TITLE
Web UI accessible from diffrent directory

### ISSUE THREAD

**Issue by Likqez** [arangodb/arangodb#13501]
## My Environment

* __ArangoDB Version__:         3.7.6
* __Deployment Strategy__:    Manual Start in Docker 
* __Used Package__:                Docker - official Docker library

__Problem__:
I want the Web GUI to be accessible from `test.example.com/arango`. Some time ago, I had it working on `arango.example.com` using nginx as reverse proxy. But now I can't figure out how to access from an extra directory, since arango throws me this:
`{"error":true,"code":404,"errorNum":404,"errorMessage":"unknown path '/arango/_db/_system/_admin/aardvark/index.html'"}`
I already tried to rewrite in nginx directly, but without success.

Would be awesome if someone could help me out :)

**Comment by Likqez** [comment]
Does anyone have any ideas? I searched for a feature like Jenkins, who implemented a Prefix which can be specified and then used by the internal web server but did not find anything. Please add this to TODO so custom solutions are possible.

**Comment by Simran-B** [comment]
Related requests:
- https://github.com/arangodb/arangodb/issues/8176
- https://github.com/arangodb/kube-arangodb/issues/589

**Comment by Likqez** [comment]
I tried setting the nginx configuration like in #1558 with the use of ``--frontend.proxy-request-check true``. But seems as it's not working fine. I am still getting redirected to example.com/_db/...

I think the problem is the configuration change. 
Furthermore, I am using Arango in a Docker Stack, and used the above stated parameter like this ``command: --frontend.proxy-request-check true``.

May you advise me how to change the configuration in my environment?

**Comment by Likqez** [comment]
I tried again using the X-Script-Name Header, which resulted in the following error:

`curl -v -H "X-Script-Name: /arango" http://5.xxx.xxx.217:8529/arango
*   Trying 5.xxx.xxx.217
* TCP_NODELAY set
* Connected to 5.xxx.xxx.217 5.xxx.xxx.217) port 8529 (#0)
> GET /arango HTTP/1.1
> Host: 5.xxx.xxx.217:8529
> User-Agent: curl/7.55.1
> Accept: */*
> X-Script-Name: /arango
>
< HTTP/1.1 404 Not Found
< X-Content-Type-Options: nosniff
< Server: ArangoDB
< Connection: Keep-Alive
< Content-Type: application/json; charset=utf-8
< Content-Length: 80
<
{"error":true,"code":404,"errorNum":404,"errorMessage":"unknown path '/arango'"}* Connection #0 to host5.xxx.xxx.217 left intact`

This was tested with `--frontend.proxy-request-check false`.

**Comment by Likqez** [comment]
I'm going to close this issue because it is basically the same as #8176.

**Comment by vanthome** [comment]
I'm using ArangoDB in a docker image. How can I set the proxy related properties then?
For example Kibana from Elasticsearch has a config setting for this called `SERVER_BASEPATH`.

**Comment by ZombaL85** [comment]
> I'm using ArangoDB in a docker image. How can I set the proxy related properties then? For example Kibana from Elasticsearch has a config setting for this called `SERVER_BASEPATH`.
@vanthome 
Have You solve this issue ?
