### ISSUE TITLE
Foxx model returns attribute for EventEmitter

### ISSUE THREAD

**Issue by fceller** [arangodb/arangodb#1350]
Generating a trivial foxx and then using PUT results in:

{
  "attributes": {
    "first_name": "Notorious",
    "last_name": "BIG",
    "_id": "spyke_test_users/1093677929681",
    "_rev": "1100639618060",
    "_oldRev": "1100615500812",
    "_key": "1093677929681"
   },
  "isValid": false,
  "errors": {
    "_oldRev": {
      "name": "ValidationError",
      "details": [
        {
          "message": "value is not allowed",
          "path": "value",
          "type": "any.unknown"
        }
      ],
      "_object": "1100615500812"
    }
  },
  "domain": null,
  "_events": {},
  "_maxListeners": 10
}

**Comment by jsteemann** [comment]
Due to Foxx.model` inheriting properties from `EventEmitter` (which has attributes `domain`, `_event`, `_maxListeners`).

**Comment by pluma** [comment]
Yes, the model shouldn't be passed to the response directly, ever. That's what the serialization methods are for.

Is this a bug in the generator templates?
