### ISSUE TITLE
Not allowed to start variable name with an underscore

### ISSUE THREAD

**Issue by 153957** [arangodb/arangodb#13513]
## My Environment

* __ArangoDB Version__:  3.7.5
* __Storage Engine__:   RocksDB
* __Deployment Mode__:  Single server (Docker image)
* __Deployment Strategy__: ArangoDB Starter in Docker
* __Configuration__:  n/a
* __Infrastructure__: n/a
* __Operating System__: n/a
* __Total RAM in your machine__:  n/a
* __Disks in use__: n/a
* __Used Package__: n/a

## Component, Query & Data

__Affected feature__:
ArangoDB returns an error when I perform a query containing a variable whos name starts with an underscore.

> If a variable name starts with the underscore character, the underscore must be followed by least one letter (a-z or A-Z) or digit (0-9).
– https://www.arangodb.com/docs/stable/aql/fundamentals-syntax.html#variable-names

__AQL query (if applicable)__:
```
LET _foo = [1,2,3]

RETURN {_foo}
```
__AQL explain and/or profile (if applicable)__:

`Query: AQL: variable name '_foo' has an invalid format (while parsing)`

## Steps to reproduce

1. Run the above AQL query

__Problem__:
The variable name starting with an underscore is not allowed.

__Expected result__:
That this would be an allowed naming scheme for variable names.

**Comment by Simran-B** [comment]
The statement in the documentation appears to be wrong. I can reproduce the error even in version 2.8. Waiting for a reply from engineering what the reason is for not allowing leading underscores.

**Comment by Simran-B** [comment]
3.9 will allow leading underscores. For 3.8 and older we adjusted the documentation: https://github.com/arangodb/docs/pull/689

**Comment by maxkernbach** [comment]
Hi @153957,

the [GA release of ArangoDB 3.9](https://www.arangodb.com/2022/02/introducing-arangodb-3-9-further-powering-graph-at-scale/), which allows leading underscores, is available.

[Updated 3.9 documentation](https://www.arangodb.com/docs/stable/aql/fundamentals-syntax.html#variable-names):

> If a variable name starts with one or multiple underscore characters, the underscore(s) must be followed by least one letter (a-z or A-Z).

[Updated 3.7/3.8 documentation](https://www.arangodb.com/docs/3.8/aql/fundamentals-syntax.html#variable-names):
>  A variable name must not start with a number or underscore.
