### ISSUE TITLE
C# .NET core driver & Importing models

### ISSUE THREAD

**Issue by weedkiller** [arangodb/arangodb#13515]
Hello, I dont see a C# driver, how do I use it with C#, 

- [ ] How to modeling/`importing` data & schema from MS Sql Server
- [ ] Does it a have a client for  monitoring/management
- [ ] How can I store time series events

**Comment by dothebart** [comment]
regarding the c# driver please see https://github.com/arangodb/arangodb/issues/2992

Document stores usually require a different data layout than SQL - no denormalization possible. Hence many design decisions will probably look different than in a SQL environment. 

regarding monitoring you've got several options: 
 - https://www.arangodb.com/docs/stable/http/administration-and-monitoring-metrics.html#metrics-api can be used for prometheus integration
 - https://www.arangodb.com/docs/stable/http/administration-and-monitoring.html#statistics can be used for getting similar metrics in json format
 
In currently available stable releases there is no support for time series datatypes.
