### ISSUE TITLE
Reload TLS may be masking errors

### ISSUE THREAD

**Issue by ignacionr** [arangodb/arangodb#13525]
## My Environment

* __ArangoDB Version__:        self-compiled devel branch
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:  Manual Start
* __Configuration__:             
* __Infrastructure__:              own
* __Operating System__:     Ubuntu 20.04
* __Total RAM in your machine__:  32Gb
* __Disks in use__:        SSD
* __Used Package__:    other

## Component, Query & Data

__Affected feature__:
server

__AQL query (if applicable)__:

__AQL explain and/or profile (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. force TLS restart
2. if errors occur, they will not be reported

__Problem__:
the fail bit is interpreted backwards in https://github.com/arangodb/arangodb/blob/devel/arangod/GeneralServer/GeneralServerFeature.cpp#L298

__Expected result__:
as per the code comment, the last error should be returned (not the last ok)

**Comment by ignacionr** [comment]
This is just from reading the code, it seems line https://github.com/arangodb/arangodb/blob/devel/arangod/GeneralServer/GeneralServerFeature.cpp#L298 shoudl read only fail() instead of !fail().

**Comment by dothebart** [comment]
https://github.com/arangodb/arangodb/pull/13529 is what you meant?

**Comment by ignacionr** [comment]
Thank you! This was my first read at the code so I wasn't completely sure as to propose a PR. Great response time, you rock!

**Comment by dothebart** [comment]
heh, its not that often that you get a bugreport with the exact source line ;-) so, this one was easy. 
The fix will be in 3.7.8 - as 3.7.7 was just released.

**Comment by Simran-B** [comment]
v3.7.9 which includes the fix was released.
