### ISSUE TITLE
support Apple ARM M1 architecture

### ISSUE THREAD

**Issue by mikestaub** [arangodb/arangodb#13559]
## My Environment

* __ArangoDB Version__:  3.7.7      
* __Storage Engine__:   RocksDB          
* __Deployment Mode__:   Single Server    
* __Deployment Strategy__:  Manual Start in Docker 
* __Configuration__:   ARM CPU            
* __Infrastructure__:   Macbook ( M1 chip )            
* __Operating System__:  MacOS 11.2.1      
* __Total RAM in your machine__:   16gb     
* __Disks in use__:   SSD     
* __Used Package__:  main docker image            

## Steps to reproduce

1. `docker run -e ARANGO_RANDOM_ROOT_PASSWORD=1 -d --name arangodb-instance arangodb`
2. `docker: no matching manifest for linux/arm64/v8 in the manifest list entries.`

__Problem__:

The container exits with the following logs when run manually:

```
Initializing database...Hang on...
qemu: uncaught target signal 4 (Illegal instruction) - core dumped
ArangoDB didn't start correctly during init
cat: can't open '/tmp/init-log': No such file or directory
```

**Comment by mikestaub** [comment]
closing in favor of: https://github.com/arangodb/arangodb-docker/issues/53

**Comment by harisb2012** [comment]
Does this work under Rosetta 2?

**Comment by dothebart** [comment]
Hi, 
yes, ArangoDB should work under the amd64-emulatation.
