### ISSUE TITLE
Redundant code

### ISSUE THREAD

**Issue by bamforp** [arangodb/arangodb#1355]
In arangodb/foxx/sessions.js, isn't the if statement around line 177 redundant given line 169?

    if (!opts.cookie.name) {
      opts.cookie.name = 'sid';
    } else if (typeof opts.cookie.name !== 'string') {
      throw new Error('Cookie name must be a string or empty.');
    }
    if (opts.cookie.secret && typeof opts.cookie.secret !== 'string') {
      throw new Error('Cookie secret must be a string or empty.');
    }
    if (!opts.cookie.name) {
      opts.cookie.name = 'sid';
    }

**Comment by jsteemann** [comment]
@bamforp : yes, looks like the second occurrence is superfluous.
@pluma: can you verify this and remove it the latter occurrence? Thx!

**Comment by pluma** [comment]
Well spotted. Thanks.
