### ISSUE TITLE
old post references very old github js driver implementation

### ISSUE THREAD

**Issue by MarcWeber** [arangodb/arangodb#1357]
Searching for "nodejs" shows this old post:
https://www.arangodb.com/2012/07/arangodb-for-nodejs/

The problem is that https://github.com/arangodb/arangojs is the official js driver now.
If you follow the github link given in that old post you'll have to follow 3 redirects to find the current one by accident.

**Comment by pluma** [comment]
Strictly speaking https://github.com/kaerus-component/arango is still maintained by kaerus and available on NPM as `arango`, so it's just one redirect (from kaerus/arango-client to kaerus-component/arango).

The official JS driver now indeed lives at https://github.com/arangodb/arangojs though.

We should probably edit the post to point new users at a more recent post about the current official JS driver, though.

**Comment by MarcWeber** [comment]
The Readme says:

    NOTE: This repo is now officially maintained by the developers of ArangoDB @https://github.com/triAGENS/ArangoDB-JavaScript.

Thus maybe some clarification about the differences should be added to both/either projects then. Thus this issue is about the homepage and both README files.

**Comment by 13abylon** [comment]
The blogpost is updated and now there is note leading to the new nodejs driver. Thanks for reporting!

**Comment by pluma** [comment]
I've made a PR to kaerus' project to update the reference.

A quick history lesson to explain the current situation:

1. kaerus originally wrote the first ArangoDB JS driver, which is called `arango` (v1.x) on NPM and first resided at kaerus/arango-client and then kaerus-component/arango.
2. He later joined forces with the ArangoDB team and created an official fork, which was called `arangojs` (v2.x) on NPM and resides in the triAGENS/ArangoDB-JavaScript repo.
3. As far as I know, kaerus is still actively developing the original `arango` driver (last release was six months ago) at kaerus-component/arango and as `arango` on NPM.
4. Around September last year we (the ArangoDB team) decided to re-implement the JavaScript driver from scratch at arangodb/arangojs. This driver became the new `arangojs` (v3.x) on NPM.

The two drivers are architecturally very different.

**Comment by pluma** [comment]
I'm closing this for now. It's up to kaerus to update the README of his driver if he wants to.

**Comment by andelo** [comment]
done! 
Thanks for clearing up on the history. I'm _not_ working on the js-component anylonger since I've abandoned ArangoDB in favour of postgreSQL.
