### ISSUE TITLE
LIMIT offset/count values from bind variable (array)?

### ISSUE THREAD

**Issue by Phillips126** [arangodb/arangodb#13574]
## My Environment

* __ArangoDB Version__:        3.7.3
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Operating System__:        Ubuntu 20.04
* __Total RAM in your machine__:        256GB
* __Disks in use__:        SSD

## Component, Query & Data

__Affected feature__:
AQL Query

__AQL query (if applicable)__:
This is a very contrived example, but it shows my question:
```
FOR item IN @items
    FOR i IN 1..100
        LIMIT item.quantity
        RETURN i
```
Here is the bind variables used:
```
{
  "items": [
    {
      "part_number": "000555",
      "quantity": 5
    }
  ]
}
```

__AQL explain and/or profile (if applicable)__:
I receive the following error when attempting to use this query:
```Query: AQL: LIMIT offset/count values must be constant numeric values (while instantiating plan)```

## Steps to reproduce

1. Run the above query with using the above bind variables.

__Problem__:

The example above is very contrived, but it shows an issue that I was encountering while trying to build my API.  The actual query that I am working on loops through an array of items, filters the data by a few parameters and then returns a number of records limited by the value present in the loop - this value can be different for each iteration.

Providing a value such as `5` as a bind variable works perfectly fine, but when using the value from an array it throws an error.  

__Expected result__:

For the example above, I would have expected the result to look like:
```
[
  [
    1,
    2,
    3,
    4,
    5
  ]
]
```

__Question__:

This is likely by design, and there is likely no way that I can perform this exact query - but are there any alternative solutions you'd recommend?

**Comment by goedderz** [comment]
There seems to be a misconception here. The LIMIT is not applied to a specific loop, but to its whole input.

The LIMIT arguments have to be known at compile time, and that's by design.

You could write it like this instead, I guess that's what you mean:
```
FOR item IN @items
    FOR i IN 1..item.quantity
        RETURN i
```

**Comment by Phillips126** [comment]
Thank you for clearing that up, I wrongfully assumed that LIMIT could be applied in other ways.  Your alternative solution will likely work for me.  Thanks again.
