### ISSUE TITLE
Question,How to use  search with languages Polish and Ukrainian

### ISSUE THREAD

**Issue by menesty** [arangodb/arangodb#13576]
Have a. question, in support languages, cant found Polish and Ukrainian - how I can add it -  or how to search using full-text search for these languages.
Thanks

**Comment by dothebart** [comment]
Hi, 
Please refer to [this ticket about adding stemmers etc.](https://github.com/arangodb/arangodb/issues/4838)

**Comment by dothebart** [comment]
closing as solved duplicate
