### ISSUE TITLE
deleting foxx app in aardvark fails if corresponding files don't exist

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangodb#1358]
This happened to me a couple of times now: I have a foxx-app and just moved or deleted the corresponding folder in my filesystem, and then I go to aardvark to also delete the app there. That fails. The browser's console reports `TypeError: null is not an object (evaluating 'o.consumes')` and arangod logs `Cannot compute Foxx application routes: [ArangoError 14: file not found:`

At this point I have to recreate the app's folder to be able to delete the app.

I think aardvark should allow me to delete apps even if they don't exist in the filesystem anymore.

**Comment by jsteemann** [comment]
:+1 I ran into the same problem a few times.

**Comment by pluma** [comment]
Yeah, I noticed this as well when I forgot to wipe the db after wiping the local files.

**Comment by fceller** [comment]
@pluma has this been fixed in 2.7.0?
