### ISSUE TITLE
Arango 2.5.5 windows installer(64) bit crashes on start

### ISSUE THREAD

**Issue by benj-Jansen** [arangodb/arangodb#1359]
Hi,

ArangoDB-2.5.5-win64.exe crashes on startup. Cant install it.
Tried for Windows 7, 8.1 and Server 2012 R2 
Best,

**Comment by weinberger** [comment]
@benj-Jansen can you try if the XCOPY Installation works?

**Comment by benj-Jansen** [comment]
The XCOPY Installation works properly, thanks!

**Comment by dothebart** [comment]
The windows installer was combined with a broken version of NSIS; re-did and reuploaded, all fine now.
