### ISSUE TITLE
foxx-manager help

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangodb#1360]
I find it a bit unusual that foxx-manager has `help` and `--help`. It would be helpful if `--help` told me about `help`.

`help` prints a link to https://docs.arangodb.com/FoxxManager/README.html which isn't valid.

**Comment by jsteemann** [comment]
Thanks, I have fixed the invalid link in 2.5 & devel.

Regarding `--help` and `help`: 
`foxx-manager` is actually an arangosh which executes a specific start script. `--help` is intercepted in arangosh (and the other tools) relatively early, even before bootstrapping V8 and executing the start script. `--help` will simply enumerate the command-line options for the binary (arangosh), dump then and abort. Up to this point, it won't know that it is used as `foxx-manager`.
So there is not much that can be done, apart from checking for the program name and printing a hard-coded program-specific string.
