### ISSUE TITLE
foxx-manager replace doesn't invoke teardown/setup

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangodb#1362]

**Comment by pluma** [comment]
Aardvark doesn't have an option for running the setup after replace either.

**Comment by pekeler** [comment]
from `foxx-manager help`
```
 replace            replaces an installed Foxx application
                    WARNING: this action will remove application data if the application implements teardown!

```

**Comment by pluma** [comment]
If it's never done this although the help says otherwise, I'd be in favour of making it optional in both aardvark and foxx-manager, for both teardown and setup individually.

**Comment by pekeler** [comment]
Other than the option, would there be any difference between `replace` and `upgrade`?

Background: my deployment script used to use `replace` (I don't remember why). Then I saw the help, temporarily panicked, and quickly changed my script to use `upgrade`. Now I can't imagine a use-case where I'd want to use `replace`. Could always just use `uninstall` follow by `install`.

**Comment by pluma** [comment]
Frankly, I'm not sure. I think they're equivalent at this point due to changes in Foxx internals. I'll ask around and see whether we can remove one of the two and just add the teardown/setup as optional flags.

**Comment by fceller** [comment]
@pluma can we close this?

**Comment by pluma** [comment]
@fceller I think we still need to make a decision about `replace` vs `upgrade` and whether to simply drop one of them and make them synonyms.

**Comment by pekeler** [comment]
The recent rename of the foxx app 'users' to 'users-local' made think about this again. If I was new to foxx-manager, I'd think I'd have to use `replace` instead of `upgrade` because I want to replace an app at a mount point with a different app (without running tear down in this case).

And continuing that line of thought, `upgrade` shouldn't require the app's name as an argument. All I should need to do is `foxx-manager upgrade /users` to upgrade whatever app is at that mount point to the latest version.

**Comment by pluma** [comment]
@pekeler for that upgrade to work the services would need to "remember" where they came from. Right now that's only relevant at install time and the service has no recollection of whether it was installed from a repo or zip file.

**Comment by pluma** [comment]
Closing in favour of https://github.com/arangodb/foxx-cli
