### ISSUE TITLE
create DB from command line

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangodb#1363]
Is there a way from the command line to create a new database? I.e. not using aardvark or arangosh. If not, please consider this a feature request :)

**Comment by jsteemann** [comment]
If you were thinking about bash, then the following command should do it:
`curl -X POST http://127.0.0.1:8529/_db/_system/_api/database --data '{"name":"myDatabase"}'`

If you can can use arangosh but don't want to use it interactively, you could use
`echo 'db._createDatabase("myDatabase");' | arangosh`

I am not sure if that helps.

**Comment by pekeler** [comment]
Thanks @jsteemann - that help. I still think a dedicated cmd-line tool like foxx-manager would be nice, but I'm going to close this for now.

**Comment by wesleymilan** [comment]
+1
