### ISSUE TITLE
double click in docs on aardvark

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangodb#1364]
Double clicking on or near fields/values of a document in aardvark is creating a new field:value pair. I *really* dislike this feature because, often times, I want to copy some text which I do by double-click-drag (to select on word boundaries) or triple-clicking (to select the whole line).

**Comment by pluma** [comment]
I agree, this has caught me before.

@mchacki any chance we can disable that feature in the editor plugin?

**Comment by pekeler** [comment]
Thanks!

**Comment by CoDEmanX** [comment]
Another issue I discovered today is, that Ctrl+T won't open a new browser tab but is caught by the editor as well and seems to move a single character to the right...

**Comment by pluma** [comment]
@CoDEmanX you mean it swaps two characters? I think that's intentional. You can still open a new tab by unfocusing the editor first.

**Comment by CoDEmanX** [comment]
Yeah it's a feature, but the key binding is unfortunate. Plus I wonder when you actually need this kind of functionality. Copy, paste and arrow shortcuts are well known and not much slower for the rare occasion of character shifting...

**Comment by pluma** [comment]
I'm guessing it's influenced by Sublime Text 2 or some other editor that shares the key binding. I don't mind either way. @mchacki Do you think the Ctrl+T shortcut is genuinely useful or should we remove it?

**Comment by pekeler** [comment]
I haven't noticed it with Aardvark, but am generally annoyed when cmd-t doesn't work as expected due the the active website.
