### ISSUE TITLE
Fix frontend tests

### ISSUE THREAD

**Issue by pluma** [arangodb/arangodb#1366]
The frontend tests are utterly broken, in part due to the outdated sass linter.

We should sort this out sooner rather than later.

**Comment by hkernbach** [comment]
+1, also we could think about newer technologies like e.g. jest (https://facebook.github.io/jest/)

**Comment by pluma** [comment]
I'm not entirely sure about jest (the mock-by-default approach is a bit extreme), but it is probably worth a look.

**Comment by dothebart** [comment]
need to write. closing.

**Comment by pluma** [comment]
We actually got rid of the existing test suite as they were beyond hope at this point and provided no meaningful guarantees whatsoever.
