### ISSUE TITLE
Installing ArangoDb silently, with all the settings by default. How?

### ISSUE THREAD

**Issue by GildedHonour** [arangodb/arangodb#13689]
For Ubuntu 21.x, or Debian 9. And MacOS as well.

I want to install ArangoDb silently, via a bash script, so that a user won't have to specify password, nor select any other settings at all. With all the default settings.

How to do that?

When I download and run a *.deb file, or when I try to install it via "apt install ...", installation process doesn't go silenty as it'lll ask 4 questions: create a new passowrd, whether or not make backups, which engine....

**Comment by dothebart** [comment]
have a look at the old docker scripts, they used to do exactly that: https://github.com/arangodb/arangodb-docker/blob/official/Dockerfile33.local

**Comment by GildedHonour** [comment]
Is there a standard, easier way? For instance, on Arch Linux in Aur, it's installed, from a deb package, without these commands:

```
echo arangodb3 arangodb3/password password test | debconf-set-selections) && \
    (echo arangodb3 arangodb3/password_again password test | debconf-set-selections) && \
    DEBIAN_FRONTEND="noninteractive" 
```
somehow.

**Comment by dothebart** [comment]
else use the tarball?
