### ISSUE TITLE
2.6.0 alpha 3 Swagger interface not working

### ISSUE THREAD

**Issue by bamforp** [arangodb/arangodb#1368]
When opening Foxx app I get the following in the API Swagger window.

{"error":true,"code":404,"errorNum":404,"errorMessage":"unknown path '/_admin/aardvark/foxxes/docs/index.html?mount=%2FmySessions'"}

**Comment by pluma** [comment]
This sounds awfully familiar: https://github.com/arangodb/arangodb/issues/1327#issuecomment-106365414

@fceller can you look into this?

**Comment by fceller** [comment]
@bamforp which operating system / package did you use?

**Comment by bamforp** [comment]
I am running Win64 on Windows 7 Pro.

I have 2.5.4 and 2.6.0-apha3 on my PC and I have observed that if I launch arangod.exe in the 2.5.4 directory, it actually loads the 2.6.0 database.

**Comment by fceller** [comment]
@dothebart can you check this under Windows?

**Comment by dothebart** [comment]
Sorry, I'm also unable to reproduce this.
I've tried the following:
Applications->Add Applications; Installed Itzpapalotl from the store with the mountpoint to /blarg
Click that Foxx, get the Documentation - no error.
Can you elaborate your way to the error in a bit deeper detail?

**Comment by pluma** [comment]
@dothebart I'm fairly certain this error can only be reproduced by upgrading from an earlier version. I don't expect it to be reproducible with a fresh 2.6 install.

**Comment by nlac** [comment]
Actually it can be reproduced with a fresh xcopy install of v2.6 final. Created a video about installing a fresh copy and adding a "new app": http://nlacsoft.net/public/arango/creating_app_arangodb2.6.avi
(Windows 8.1)

**Comment by dothebart** [comment]
ok, Now I got it. Create a new app was the key. @pluma its definitely broken on windows without upgrade, breaks on a fresh install.

**Comment by pluma** [comment]
I don't know how to change what goes in the packages but at least the HTML files are missing there. @fceller maybe?

**Comment by fceller** [comment]
@dothebart please add them to the CMakeFile

**Comment by pluma** [comment]
For the record, the entire `assets` folder should be in the package.

**Comment by aconran** [comment]
Just ran into this on 2.6.0 for OS X. Any easy way to get an updated version?

**Comment by fceller** [comment]
Yes, we will release 2.6.1 soon.

**Comment by dothebart** [comment]
you can however download the missing files here: https://github.com/arangodb/arangodb/tree/devel/js/server/assets/swagger (you have to keep the directory layout)
