### ISSUE TITLE
Fairly bad error in docs

### ISSUE THREAD

**Issue by Back-io** [arangodb/arangodb#1372]
https://docs.arangodb.com/Traversals/UsingTraversalObjects.html

It refers to a fifth parameter being passed to the `.visitor` function called `connections`, but it is in fact called `connected`.

**Comment by jsteemann** [comment]
I am not sure I understand.
The docs say this about the function signature for a visitor function:
> visitor: function (config, result, vertex, path, connections) { ... }

I think the name of the fifth parameter here is relevant for documentation purposes mainly.
When a custom visitor function is actually used, the parameter can be given any name, as long as it is used consistently inside the function.
For example, the following visitor will work as well (as long as the config's `order` attribute is set to `preorder-expander`, which is the only situation that will populate the fifth parameter when the visitor is called):
```js
config.visitor = function (config, result, vertex, path, foobar) {
  if (foobar && foobar.length === 0) {
    require("internal").print("found a leaf-node: ", vertex);
  }
}
```
Or am I getting something wrong?

**Comment by Back-io** [comment]
Yes, but when using this through the HTTP API (I'm the node.js driver), you don't specify the function signature, only the body in a string, so the parameter names are fixed.

**Comment by jsteemann** [comment]
Ok, got it. Makes sense.
I will adjust the docs for this.

**Comment by jsteemann** [comment]
Fixes for the documentation have been pushed and will become available when the documentation is re-generated.
