### ISSUE TITLE
Docs: Parts of sentences in wrong places on HTTP API pages?

### ISSUE THREAD

**Issue by CoDEmanX** [arangodb/arangodb#1374]
For example, the following half sentence:

>  returns all documents of a collection near a given location

is between the example code of *Simple range query* and the next headline *Find documents near a coordinate*, but shouldn't it be below that next headline (or even further down that section)?

https://docs.arangodb.com/devel/HttpSimpleQuery/index.html

Current and devel docs (2.5/2.6)

**Comment by pluma** [comment]
Yes, the order seems wrong. I think that part of the documentation is generated.

**Comment by dothebart** [comment]
I fixed that in the documentation rework without knowing this bug - closing it now ;-)
