### ISSUE TITLE
Docs: SORT null not mentioned

### ISSUE THREAD

**Issue by CoDEmanX** [arangodb/arangodb#1375]
[Jan mentioned][1] that

> If a query uses the hash method for a COLLECT but the sort order of the COLLECT result is irrelevant to the user, the user can provide a hint to the optimizer to remove the post-COLLECT sort.
> This can be achieved by simplying appending a **SORT null** to the original COLLECT statement. 

This option is not mentioned [in the docs][2].

[1]: https://jsteemann.github.io/blog/2015/04/22/collecting-with-a-hash-table/
[2]: https://docs.arangodb.com/devel/Aql/Operations.html#sort

**Comment by jsteemann** [comment]
It was mentioned in the docs briefly already, but I think mentioning it another time won't do any harm:

https://github.com/arangodb/arangodb/commit/f82689f146f2447a5d69b7f3c757ecdb8fb7cc43#diff-9000fbbb21446a10612743a5eccce18dL422

Do you have any further suggestion for where to mention the `SORT null`?

**Comment by CoDEmanX** [comment]
Okay. I think this should do it. I wonder however, if the documentation needs consolidation to put all the information about a specific function or feature in a single place...

**Comment by jsteemann** [comment]
@13abylon : what do you think of an AQL documentation makeover?
