### ISSUE TITLE
Cannot install ArangoDB 3.7.10 on Windows

### ISSUE THREAD

**Issue by CBlinguland** [arangodb/arangodb#13763]
## My Environment

* __ArangoDB Version__:        
* __Storage Engine__:           
* __Deployment Mode__: 
* __Deployment Strategy__: 
* __Configuration__:             
* __Infrastructure__:             
* __Operating System__:  Windows 10
* __Total RAM in your machine__: 
* __Disks in use__: 
* __Used Package__:

## Component, Query & Data

__Affected feature__:
Installation

__AQL query (if applicable)__:
```


```
__AQL explain and/or profile (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. 
2. 
3. 

__Problem__:
I uninstalled ArangoDB 3.7.9 and installed 3.7.10 afterwards.
Start of installation was as always. At the end of installation an error is shown.
It says, my PATH is already too long and it could not add ArangoDB to the path.

After confirming the dialog, the installer window shows text like "instalaltion done". After finish the installer there is no ArangoDB installed :-(

Currently my PATH has about 880 characters. There seems to be a standard limit at 2047 bytes/chars for PATH?
Reinstalling ArangoDB 3.7.9 works without problems.

__Expected result__:
Installation finishs without errors and gives me ArangoDB.

**Comment by dothebart** [comment]
Hi, 
this is a long standing limitation of NSIS, and I fear that nothing much can be done about this :-/

**Comment by CBlinguland** [comment]
Hi,

not having any knowledge about NSIS and windows installer I assume a bug because:
- my PATH not exceeding the limit
- in registry I set a flag to allow longer PATH - without an effect
- Installing the older previous version ArangoDB 3.7.9 was no problem - I assume it will add to the PATH to

After the failed installation I didn't find any entries in the event log - don't know if windows would generate log entries regarding PATH.

The label "Analyzing" is set, so I hope it can be fixed in near future

But thanks for ArangoDB in general :-)

**Comment by dothebart** [comment]
well, if you want to take a look yourselves:
https://github.com/arangodb/arangodb/blob/devel/Installation/Windows/Plugins/AddToPath.nsh#L61
Thats probably the text you saw in that popup, right?
Btw, you can easily untick the checkbox and do the path handling on your own, if you want to...

**Comment by CBlinguland** [comment]
Yes that was the text the popup showed.

Will try to install ArangoDB 3.7.10 on not often used Windows 10 installation. Doing this I will remember to look for the checkbox you mentioned.

Thanks for the support

**Comment by Simran-B** [comment]
I came across this blog post recently:
https://devblogs.microsoft.com/oldnewthing/20100203-00/?p=15083

My takeaway is that the practical limit is 2048 characters (if the Environment registry key is modified), but that the total length of **all** environment variables could also play a role. Is the total length above 32k on your system by any chance?

I guess NSIS doesn't add the 3.7.9 path again if it's already in the PATH? That would explain why installing this version works, but not 3.7.10.

**Comment by CBlinguland** [comment]
@Simran-B The content of "Path" was about 880 characters, so it is far away of the 2048 chars limit.
I installed ArangoDB 3.7.9 CE and 3.7.10 CE on a little use Windows 1ß installation. There wasn't ArangoDb installed before.
For both ArangoDB-Versions there where no problems/error reported by the installer, using the standard options.

But after installation I could not find an ArangoDb-specific entry in the "Path", as if the Arango-Path was never be added.

I remember that I always update some pathes manually in the window environment vars - this was working till 3.7.9 inclusive.
So getting the installer error in 3.7.10 it seems that there was an improvement in the version: It tries to set the path really but fails.

Currently i could not check and test due to no access to my working laptop..

Maybe the uninstaller sometimes/never removed the "Path"-entry? The new arangodb installation are always done in a directory containing the current Arango version - so the old "Path" must be removed and a the new one added.

i don't know if the install checks the existing PATH-definitions. If so it should check the existing pathes if starting with "Arango" or so. One could check it out by removing Arango from PATH manually and try installation again.
I would try it if i am in office someday ...

**Comment by CBlinguland** [comment]
@Simran-B Last friday I installed ArangoDB 3.7.10 CE again on windows. I did it as before with the standard installation options and it worked without problems. The "Path" was not added but the installer didn't fail like described in this report.
The only difference I am aware of is, that I installed some windows updates before reinstallation.

So there seems to be no problem - maybe you close this.

Thanks for your support!

**Comment by Simran-B** [comment]
> it worked without problems

That's strange because we are not aware of any changes from our side. Maybe it was an OS problem, who knows. The installer is still supposed to add ArangoDB to the PATH env var, however. We need to check that.

> The content of "Path" was about 880 characters, so it is far away of the 2048 chars limit.

You are on the safe side there, but I wonder if the lengths of all environment variables (not just PATH) summed up is below 32k characters, which is apparently also a limitation on Windows.

Var | Value | Length
---|---|---
ComSpec | C:\Windows\system32\cmd.exe | 27
DriverData | C:\Windows\System32\Drivers\DriverData | 38
OS | Windows_NT | 10
Path | C:\Python38\;C:\Python38\Scripts;... | 33+

The total length would be 108+ here I suppose, although I'm not sure if the variable names themselves also contribute and whether the stored or expanded paths are counted.

**Comment by dothebart** [comment]
Hi, 
we have found a way to fix this issue using an external library - fixed by https://github.com/arangodb/arangodb/pull/14870 - latest ArangoDB releases should not show this issue anymore.
