### ISSUE TITLE
307 temporary redirect while doing internal redirection

### ISSUE THREAD

**Issue by omarsmak** [arangodb/arangodb#1379]
I am testing of way to do URL redirection within Foxx. All requests should bound to an entry Foxx endpoint, from there it will be redirected to the appropriate Foxx endpoints. I managed to get it work by using 'actions.redirectRequest', here is an example for what I am doing:
```javascript
(function() {
    const Foxx = require('org/arangodb/foxx');
    const actions = require('org/arangodb/actions');
    const app = new Foxx.Controller(applicationContext);
    const console = require('console');


    app.get('/getre/*', function(req, res){
    	//console.log(actions.redirectRequest);
    	///console.log(req.params("test"));
        var url_string = req.url.toString();
    	console.log(url_string.split('/getre'));
    	actions.redirectRequest(req, res, {
    		destination: "/another-foxx-app/user/omarsmak"
    	});
    });
})();
```

Somehow this works perfectly using cURL, but while initiating the request from the browser, this would fall with '307 temporary redirect'. As far as I know the alternative URL should be included in the headers but it doesn't happen in this case since the redirection is happing from Foxx app level. 

If you guys have an idea on how to go around this issue, it would be great to share :)

Thanks

**Comment by jsteemann** [comment]
When calling HTTP GET `/getre` on the app, I can see an HTTP 307 response code and a `Location` header pointing to the new direction.
If your browser behaves differently, it might have have cached the response the URL and probably return a stale result? Can you trying clearing browser caches?

**Comment by jsteemann** [comment]
Looking into what you have shown me offline, I think this works as expected, with the `307` response code being issues properly by the server. Can this issue be closed?

**Comment by omarsmak** [comment]
Yep sure. Thanks and sorry for confusion

**Comment by jsteemann** [comment]
No worries.
