### ISSUE TITLE
Save Binary ([]byte) is null

### ISSUE THREAD

**Issue by Fruchtgummi** [arangodb/arangodb#13793]
I want save a dataset []byte() on ArangoDB with AQL. The saved object is "null".

```
query += `
            FOR d IN users
            FILTER (d._key == @Key)
            UPDATE d WITH { 
            TestData:{
                    test: @byte
            },
    } IN system_users`

    bindVars := map[string]interface{}{
        "byte":      mystruct.bytedata, //[]byte
        "key": 1234567,
        
    }

    cursor, err := arangodb.Db.Query(ctx, query, bindVars)

    if err != nil {
        fmt.Println(err)
    }

    defer cursor.Close()
```
If i use the none-aql function CreateDocument(), then is saved variable as binary []byte. What is the Problem in the BindVars?

**Comment by dothebart** [comment]
can you please add which driver you do use here?

**Comment by Fruchtgummi** [comment]
The official go driver!

https://github.com/arangodb/go-driver

**Comment by Simran-B** [comment]
Not that familiar with Go, but here's what I tried:

_go.mod_

```go
module test

go 1.12

require (
    github.com/arangodb/go-velocypack v0.0.0-20200318135517-5af53c29c67e
)
```

_test.go_

```go
package main

import (
	"fmt"
    velocypack "github.com/arangodb/go-velocypack"
)

func main() {
	body := make([]byte, 1)
	data, _ := velocypack.Marshal(body)
	fmt.Println(data)
}
```

```
> go mod download github.com/arangodb/go-velocypack
> go run test.go
c00100
```

That hex string represents a VelocyPack payload, a 1-byte long blob that consists of a binary zero.

With `var body []byte` and `var body interface{}` the result is `18` instead, a VelocyPack `null`.

While you can store and retrieve arbitrary VelocyPack data via the Document API, AQL does not support non-JSON data types such as blobs. You end up with `null` instead as far as I can tell.

**Comment by Fruchtgummi** [comment]
Yes, I use the driver with VST. The driver API with the col.createdocument function writes binary to the database. AQL can not do that! Unfortunately this is of no use to me, if I want to update to a record, col.updatedocument can only update by specifying the document key (_key). If I want to update according to other criteria, I have to resort to AQL. 

Of course I can put the binary type into a Base64, but for this process I have to use a different structure in GO and this is suboptimal from the point of view with developing with GO, especially if you want to develop typed.

Either one adapts AQL or the API function updatedocument/s gets more possibilities.

**Comment by Simran-B** [comment]
While VelocyPack supports non-JSON data types, ArangoDB really doesn't.
While it may be possible to get non-JSON data into ArangoDB and store it, there is no proper way to get it back without losses.
At least if you fetch data back with a client that only speaks JSON or want to use the web UI, which also uses the JSON APIs.
To overcome the limitation of the JSON type system, we would have to move away from JSON APIs, for all clients.
In addition, several operations are undefined when run on unexpected datatypes, e.g. `RETURN <blob> / 2`.

I'm closing this issue because there is already a feature request for proper blob support: #107
