### ISSUE TITLE
EDGES() in 2.6.0

### ISSUE THREAD

**Issue by F21** [arangodb/arangodb#1381]
I just upgraded from 2.5.4 to 2.6.0 and `NEIGHBORS()` seems to have changed.

The old behavior has changed as per the `CHANGELOG`. However, if I replace it with `EDGES()`:
```
EDGES(<vertexCollection>, <edgeCollection>, <vertex>, <direction>, <example>, {includeVertices: true})
```

I get an error saying the number of parameters is wrong: `[1541] invalid number of arguments for function 'EDGES()', expected number of arguments: minimum: 3, maximum: 5 (while parsing)`

OS is Ubuntu 14.10 64-bit and ArangoDB was installed using the apt repositories.

docs.arangodb.org also does not shed any light on this.

**Comment by fceller** [comment]
Seems to be a bug. Will investigate.

**Comment by fceller** [comment]
The signature of EDGES is

```
EDGES(edgecollection, startvertex, direction, edgeexamples)
```
You do not need to specify a vertexcollection. This is a BUG in the CHANGELOG.

```
arangosh [_system]> db._query("return EDGES(friendship, 'users/me', 'outbound', {}, {includeVertices: true})").toArray()
[ 
  [ 
    { 
      "edge" : { 
        "_id" : "friendship/35515570", 
        "_from" : "users/me", 
        "_to" : "users/you", 
        "_rev" : "69987506", 
        "_key" : "35515570", 
        "block" : false 
      }, 
      "vertex" : { 
        "_id" : "users/me", 
        "_rev" : "34794674", 
        "_key" : "me" 
      } 
    } 
  ] 
]
```
