### ISSUE TITLE
If has a good tools to analysis logs and then get the performance issue of arangodb cluster

### ISSUE THREAD

**Issue by bonniechen1119** [arangodb/arangodb#13820]
## My Environment

* __ArangoDB Version__:        3.4.3
* __Storage Engine__:             RocksDB
* __Deployment Mode__:        Cluster
* __Deployment Strategy__:    ArangoDB Starter
* __Configuration__:               5 nodes with 4cpu 32memory
* __Infrastructure__:               AWS
* __Operating System__:        Linux2
* __Total RAM in your machine__:        32Gb
* __Disks in use__:        SSD
* __Used Package__:               RedHat .rpm

## Component, Query & Data

__Affected feature__:
with driver

__AQL query (if applicable)__:
```


```
__AQL explain and/or profile (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. We want to collect arangodb logs and do some analysis for example we can send logs to ELK and display query details in kibana, if it has any good experience to this
2. 
3. 

__Problem__:
We want to collect arangodb logs and do some analysis for example we can send logs to ELK and display query details in kibana, if it has any good experience to this

__Expected result__:
Has a good tools to analysis logs and then get the performance issue of arangodb cluster

**Comment by Simran-B** [comment]
The recent ArangoDB versions come with an endpoint for many different metrics in Prometheus format. You would need to upgrade to get this feature.
https://www.arangodb.com/docs/stable/http/administration-and-monitoring-metrics.html

For individual queries you may use query profiling to better under how it performs and where potential bottlenecks are. There should be a button for that in the Web UI, but there is also a REST endpoint:
https://www.arangodb.com/docs/stable/aql/execution-and-performance-query-profiler.html

It's a bit dated, but you might also want to take a look at this blog series:
https://www.arangodb.com/2017/09/performance-analysis-using-pyarango/

**Comment by Simran-B** [comment]
@bonniechen1119 Was my reply helpful or do you have further questions?
