### ISSUE TITLE
Any Regex function on the server side of ArangoDB

### ISSUE THREAD

**Issue by kevinprotoss** [arangodb/arangodb#1382]
Hi,

Does anyone know whether ArangoDB has a function like `REGEX` for matching value with regex pattern?
In MongoDB, there is a keyword `$regex` for doing this, but I did not find anything similar in ArangoDB. Can anyone told me how can I achieve this? or per other methods? 

As I know, I can register a custom function by using `aqlfunctions.register`. However I do not thinks it's the best way for our deployment. Any other idea?

Thanks,

Bg,
Kevin

**Comment by dothebart** [comment]
we currently have wildcard matching with LIKE, CONTAINS for a fulltext search, and SUBSTRING.
Since REGEX requires a lot of computational ovehead, we didn't implement this so far.

For shure, a js function would be a one liner.

**Comment by kevinprotoss** [comment]
but how about some regex like this?

/^admin[^/]*$/
/^admin([^/]*/)(.*)$/

Is it possible to use `LIKE` for this use case?

**Comment by dothebart** [comment]
admin_ -> will match admin followed by one char
admin_/% -> will match admin followed by one char, then a '/' and then any number of chars
So, not a complete replacement for your regex, but similar.

**Comment by CoDEmanX** [comment]
Have a look at the implementation of LIKE(): it essentially takes a string with sql-style wildcards, constructs a JS regular expression and creates a `new RegExp(...)`. It is then used for matching.
So a custom AQL function will work. RegExp and modifiers need to be passed as string, `/exp/i` directly in a query won't work, use the alternative way instead:
    new RegExp(expString, modString)
Also see https://github.com/arangodb/arangodb/issues/1033

**Comment by kevinprotoss** [comment]
@CoDEmanX 

Well, user custom AQL function is always possible of course. Still one question is, why such `REGEX` function can not be a default function in kernel of ArangoDB? Just because of performance?

**Comment by CoDEmanX** [comment]
Well, it costs time to either integrate an existing library or write an own one and it appears to be of use for a small amount of users only.
And I'm not sure if it's worth to use a C/C++ implementation over JS' native one in terms of performance, see https://github.com/nodejs/io.js/pull/1457#issuecomment-97693648
Either way, it's probably an expensive operation. If backtracking isn't required, a faster lib might speed it up nonetheless, see this extensive article: https://swtch.com/~rsc/regexp/regexp1.html

**Comment by kevinprotoss** [comment]
OK.

btw, if no `REGEX` is provided by ArangoDB kernel, it means I'll miss the power of `index`, right?

**Comment by dothebart** [comment]
neither will be able to use an index, LIKE nor your to build REGEX.
There are plans to continue migrating the functions to C++ so no V8 data objects have to be instanciated; A Regex function would then probably use the http://www.cplusplus.com/reference/regex/ regular expressions, and one has to know that there are lots of regex dialects and a .js regex would probably have to be rewritten on an upgrade.
Regarding the Index, maybe you can add another property to your documents which you can pre-filter for that extract?

**Comment by kevinprotoss** [comment]
Ah, understand. I will consider your suggestion about additional property for custom REGEX

**Comment by CoDEmanX** [comment]
A specially designed regex engine could utilize indexes, but only for certain expressions and with a lot of effort in terms of programming. Such an effort is probably not justified, unless your business depends on it (but if it does, you should question your data structure).
What do you want to query for in particular? Any exemplary regex you can share?

**Comment by CoDEmanX** [comment]
My statement about LIKE() creating a JavaScript RegExp is no longer true. It's using C RegExp now. It could be exposed to the user as REGEX(input, pattern, flags). Two more interesting features would be substitution and replacement (`\1: \2`).

**Comment by dothebart** [comment]
ArangoDB 3.0 introduces [REGEX_TEST](https://docs.arangodb.com/3.0/AQL/Functions/String.html#regextest) - so I think we can close this now.

ArangoDB 3.0 RC2 is available through: https://www.arangodb.com/download-preview/
