### ISSUE TITLE
[longitude, latitude]-order coordinates requested for WITHIN and NEAR functions 

### ISSUE THREAD

**Issue by kkdd** [arangodb/arangodb#1384]
I appreciate it if AQL WITHIN and NEAR functions would have the syntax of [longitude, latitude]-order coordinates as follows:

```
FOR d in
WITHIN(collection, [longitude, latitude], true, radius, "distance")
RETURN d
```

Because my database has a [longitude, latitude]-order coordinates field:

```
arangosh > db.collection.ensureGeoIndex("coordinates", true);
{ 
  "id" : "example/37582275", 
  "type" : "geo1", 
  "fields" : [ 
    "coordinates" 
  ], 
  "geoJson" : true, 
  "constraint" : false, 
  "unique" : false, 
  "ignoreNull" : true, 
  "sparse" : true, 
  "isNewlyCreated" : true, 
  "code" : 201 
}
```

**Comment by kkdd** [comment]
Do you have a plan to switch to [longitude, latitude]-order geo-coordinates or not?
At this time, as far as I know,
- [longitude, latitude]-order: OpenLayers, MapboxGL, KML, GeoJSON, PostGIS, MongoDB, MySQL,
- [latitude, longitude]-order: Leaflet, Google Maps API, ArangoDB.

**Comment by dothebart** [comment]
to be precise, you have to count ArangoDB in both lists. The former format is known as Geo-Json, which is used if you set the GeoJson attribute to true when you ceate the index. 
However, this doesn't affect the sequence of the function arguments in AQL.

**Comment by kkdd** [comment]
IS_IN_POLYGON(polygon_right_hand, point_right_hand, true) is right-hand-system ready, where point_right_hand = [lon, lat]; polygon_right_hand = [[lon_1, lat_1], [lon_2, lat_2], ...].

But, the following aren't:
 NEAR(collection_right_hand, point_right_hand, true, limit, distancename),
 WITHIN(collection_right_hand, point_right_hand, true, radius, distancename),
 WITHIN_RECTANGLE(collection_right_hand, point_right_hand_1, true, point_right_hand_2, true),
where collection_right_hand is indexed by db.collection.ensureGeoIndex("coordinates", true).

**Comment by Simran-B** [comment]
Related read: http://www.macwright.org/lonlat/
