### ISSUE TITLE
Need guidance on implementing active failover handling logic in python-arango, Python driver for ArangoDB.

### ISSUE THREAD

**Issue by joowani** [arangodb/arangodb#13860]
## My Environment

* __ArangoDB Version__:        3.7.x
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Active Failover
* __Deployment Strategy__:   ArangoDB Starter | ArangoDB Starter in Docker
* __Operating System__:        Windows 10

Hello! I'm trying to add support for active failover in my Python ArangoDB driver [python-arango](https://github.com/joowani/python-arango) and I'd like some guidance. I was looking at arangojs to see the implementation but I thought it'd be easier to just ask here.

This is what I've gathered so far. Assuming ArangoDB server is running in active failover mode:
- Case 1: When user initializes the client and sets `allow-dirty-read` to `False`:
    - During client init, call `/_api/cluster/endpoints` to confirm the leader endpoint and direct all API requests to it.
    - If the user makes a request to a follower (the client should discourage this), the follower should return 503, in which case the client redirects the API request to the leader endpoint (X-Arango-Endpoint) in the 503 response.
    - If `X-Arango-Potential-Dirty-Read` response header is set to True, raise an exception client side.
    - Periodically call  `/_api/cluster/endpoints` to keep the leader endpoint up-to-date.
    - Do not allow `round-robin` and `random` load balancing strategies.
- Case 2: When user initializes the client and sets **allow-dirty-read** to `True`:
    - During client init, call `/_api/cluster/endpoints` to confirm the leader endpoint and direct all API requests to it.
    - If the user makes a request to a follower, the follower should succeed. Nothing for the client to do here.
    - If `X-Arango-Potential-Dirty-Read` response header is set to True, that's ok. Nothing for the client to do here.
    - Periodically call  `/_api/cluster/endpoints` to keep the leader endpoint up-to-date.
    - Allow all load balancing strategies.
 
My questions:
1. Is the above correct? Is there a better strategy?
2. I would like to avoid having the client spin up any threads or separate processes for periodical checking of endpoints. Is there a way to know at the time of making a request that a leader switch has happened so the client can call  `/_api/cluster/endpoints` lazily?
3. Do you recommend arangodb starter for testing this?
4. How can I trigger a failover leader switch (again for testing)?

Thank you.

**Comment by joerg84** [comment]
@joowani Happy to connect via slack/email and schedule a short session.
FYI @rajivsam

**Comment by neunhoef** [comment]
Hi @joowani,
let me first answer your concrete questions:
  1. I think your strategy is good, I do not see any improvement. Note that in case 2 only **read requests** to followers will succeed! And in case 1 I would never expect that you will see the header "X-Arango-Potential-Dirty-Read" when reading from the leader. If a failover happens, you either get no response or a 503 from the old leader.
  2. Yes. You can simply stick to the same endpoint and once you get no response or a 503 response you can try `/_api/cluster/endpoints` again and find the new leader. In case of a 503 response there is even an HTTP header to tell you the new leader, namely `X-Arango-Endpoint` will contain the new endpoint of the new leader, so you might get away without calling `/_api/cluster/endpoints` in this case. Note however, this does not work if there is no response and then you probably need the old list of endpoints from when the client was initialized to move on.
  3. Yes, I think starter is the right tool to test this. Note that the starter is contained in each Docker image we release, so you can do things like do `docker run -it --rm --net=host arangodb/arangodb sh` and execute one or multiple starters **in that Docker container**, for example, I just tested this with these three command lines in the Docker container:
```
arangodb --starter.mode=activefailover
arangodb --starter.mode=activefailover --starter.port=9528 --starter.join 127.0.0.1:8528
arangodb --starter.mode=activefailover --starter.port=10528 --starter.join 127.0.0.1:8528
```
You can probably automate this by mounting a script into the container. But even without Docker, the same approach works with local processes, you only have to make sure that the starter and arangod are installed. Note that this setup actually starts 3 dbservers, but you can add `--cluster.start-single=false` to one of them, and then you get the normal 3 agents, 2 dbservers setup.

 4. If you have three starters running like in the above example, you can simply kill one `arangodb` starter process and it will shut down its agent and dbserver, this will automatically lead to a failover. You can then bring back the starter process with the same command. I think this is probably the easiest. If you leave the starter running, then it will automatically fire up the dbserver again if you shut down that and there will probably not be a failover.

I hope this helps, let us know if you run into any trouble.

**Comment by joowani** [comment]
Hi @neunhoef,

Thank you for the detailed answer. It was very helpful. 

One follow-up question on point 2, what would a "no response" mean exactly in HTTP context? Are there any specific clues (other than the 503) that the client can use? For example, does it mean a response was returned (vs. a timeout) but without a response body?

Best

**Comment by dothebart** [comment]
Please also note that I added this hook to the arangodb source to invoke driver tests for ArangoDB developers. 

I've implemented a sample wrapper here: https://github.com/ArangoDB-Community/pyArango/pull/194

this way arangodb developers can easily invoke tests on their development systems. This is also able to launch active failover as a SUT for the tests.

**Comment by joowani** [comment]
Ok I'll look into it thanks @dothebart

**Comment by Simran-B** [comment]
@joowani Can we close this issue or is there anything to discuss here instead of over other channels?

**Comment by joowani** [comment]
This can be closed. Thanks!
