### ISSUE TITLE
How to retrieve server version of running ArangoDB ? Via AQL and/or when connecting

### ISSUE THREAD

**Issue by nvdnkpr** [arangodb/arangodb#1386]
I'm currently updating my loopback-connector for ArangoDB (https://github.com/nvdnkpr/loopback-connector-arangodb/tree/feature-%231-InitialVersion). In order to keep it backward compatible for e.g. 2.5, I need a possibility to retrieve the server version. either globally when connecting or by AQL or any other call to the API.

Background:
When Arango switched to 2.4, the returning of documents enabled me to write AQL-only methods, which also enabled the connector to provide a general usable  ```query```method for custom AQL.
Only Upsert (aka UpdateOrCreate) needed a workaround, but even that helped to create a ```transaction``` method for custom, transactional queries. (In the case of Update or Create I then created two AQL Statement for both ```UPDATE```  and ```CREATE``` and run the in a transaction).

With the upcoming ```UPSERT``` command in 2.6, running this workaround gets obsolete. I can now run that as a single UPSERT query in AQL. But in order to keep the connector backwards compatible to 2.4 and 2.5 I'll have to which version I am on.

**Comment by jsteemann** [comment]
You can query the server version via an HTTP GET request to the `/_api/version` endpoint:
`curl -X GET http://127.0.0.1:8529/_api/version`
for a 2.6 this should return something like the following:
`{"server":"arango","version":"2.6.0-beta4"}`
I am obviously using 2.6.0 beta4. The general version number format is x.y.z, with an optional dash and a string after it.

**Comment by nvdnkpr** [comment]
Cool thanks

**Comment by CoDEmanX** [comment]
`_api/version` returns the necessary information, see https://docs.arangodb.com/HttpMiscellaneousFunctions/index.html
