### ISSUE TITLE
Show Foxx app README.md in admin frontend if available

### ISSUE THREAD

**Issue by dothebart** [arangodb/arangodb#1389]
Its common practice to have a helpfull README.md in foxx apps. 
However, there is no way to read it in the UI.
There should especially be a way to add more text in the config dialogues, so one can elaborate better what the config values are about.

**Comment by dothebart** [comment]
https://github.com/evilstreak/markdown-js ?

**Comment by pluma** [comment]
Fixed in 7ae548a6a27cf7a91ce0bab971f681eaa28e50a5.
