### ISSUE TITLE
build fails on AArch64, Fedora 33 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [arangodb/arangodb#13893]
(base) [jw@cn05 build]$ make VERBOSE=1 -j1
...
make[2]: Entering directory '/data/jw/arangodb/build'
[ 12%] Building CXX object 3rdParty/velocypack/CMakeFiles/velocypack.dir/src/asm-utf8check.cpp.o
cd /data/jw/arangodb/build/3rdParty/velocypack && /usr/bin/c++ -DARANGODB_BITS=64 -DARANGODB_HAVE_JEMALLOC=1 -DARANGODB_HAVE_LIBUNWIND=1 -DARANGODB_OPENSSL_VERSION=\"1.1.1j\" -DARANGODB_USE_GOOGLE_TESTS=1 -DASM_OPTIMIZATIONS=0 -DASM_OPTIMIZATIONS=1 -DBOOST_ALL_NO_LIB=1 -DBOOST_UUID_RANDOM_PROVIDER_FORCE_POSIX=1 -DNDEBUG -DNROCKSDB_THREAD_STATUS -DOPENSSL_NO_SSL2 -DOPENSSL_VERSION_MAJOR=1 -DOPENSSL_VERSION_MINOR=1 -DROCKSDB_SUPPORT_THREAD_LOCAL -DVELOCYPACK_XXHASH=1 -I/data/jw/arangodb/build -I/data/jw/arangodb/build/lib -I/data/jw/arangodb/arangod -I/data/jw/arangodb/lib -I/data/jw/arangodb/3rdParty/velocypack/src -I/data/jw/arangodb/3rdParty/velocypack/include -isystem /data/jw/arangodb/build/3rdParty/libunwind/v1.5/include -isystem /data/jw/arangodb/build/3rdParty/jemalloc/include -Wall -Wextra -Wno-unused-parameter -Wno-deprecated-declarations     -std=c++17 -Wsuggest-override -Wnon-virtual-dtor -Wall -Wextra -g0 -O3 -fomit-frame-pointer -Wall -Wextra -O3 -fomit-frame-pointer -fPIC -std=c++17 -o CMakeFiles/velocypack.dir/src/asm-utf8check.cpp.o -c /data/jw/arangodb/3rdParty/velocypack/src/asm-utf8check.cpp
<command-line>: warning: "ASM_OPTIMIZATIONS" redefined
<command-line>: note: this is the location of the previous definition
/data/jw/arangodb/3rdParty/velocypack/src/asm-utf8check.cpp:28:10: fatal error: x86intrin.h: No such file or directory
   28 | #include <x86intrin.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [3rdParty/velocypack/CMakeFiles/velocypack.dir/build.make:368: 3rdParty/velocypack/CMakeFiles/velocypack.dir/src/asm-utf8check.cpp.o] Error 1
make[2]: Leaving directory '/data/jw/arangodb/build'
make[1]: *** [CMakeFiles/Makefile2:1868: 3rdParty/velocypack/CMakeFiles/velocypack.dir/all] Error 2
make[1]: Leaving directory '/data/jw/arangodb/build'
make: *** [Makefile:171: all] Error 2
(base) [jw@cn05 build]$

**Comment by dothebart** [comment]
Hi, 
Please have a look at https://github.com/arangodb/arangodb-docker/issues/53
Please also note that AArch64 isn't officially supported yet.

**Comment by Simran-B** [comment]
@LutzWeischerFujitsu Does dothebart's reply answer the question?

**Comment by LutzWeischerFujitsu** [comment]
Agree to close this issue for the time being, with the hope to be informed when AArch64 is supported, pointing to aws Graviton2 and Apple Silicon, too.
