### ISSUE TITLE
Web UI management of arrango features in .NET

### ISSUE THREAD

**Issue by weedkiller** [arangodb/arangodb#13906]
Hello, how do we manage the DB from a web UI from a super admins perpective if we have tennants etc.

Back up db
restart
Restore
Move DB to new server

**Comment by dothebart** [comment]
Hi are you talking about controlling the Hotbackup enterprise feature? 
The interface is documented at https://www.arangodb.com/docs/stable/http/hot-backup.html . 
On linux the server will restart internally without changing the PID. 
Please note that `upload` and `download` is seen from the perspective of the database server.

**Comment by weedkiller** [comment]
yes, but a .NET native interface for DB management

**Comment by dothebart** [comment]
Drivers can implement this interface, i.e. the the go driver does it like this:
```
func (c *clientBackup) Create(ctx context.Context, opt *BackupCreateOptions) (BackupID, BackupCreateResponse, error) {
	req, err := c.conn.NewRequest("POST", "_admin/backup/create")
```
