### ISSUE TITLE
ArangoDB API : Identity 4 Authorization Implementation Not Working 

### ISSUE THREAD

**Issue by kotishwerreddy** [arangodb/arangodb#13914]
Hello Folks,

i'm unable to authenticate the arangodb api with identity server 4 

tried like below, suggest me if any corrections

![image](https://user-images.githubusercontent.com/42269745/113722862-70a30400-970e-11eb-9794-1556de1a49f7.png)

**Comment by kotishwerreddy** [comment]
below was the code snippet :


const createOAuth2Client = require('@arangodb/foxx/oauth2');



profileRouter.get('/api/profile/getauthlog/:token', async (req, res) => {
    try {
        const token = req.pathParams.token;
        const oauth2 = createOAuth2Client({
            authEndpoint: 'https://<Domine>/connect/authorize',
            tokenEndpoint: 'https://<Domine>/connect/token',
            activeUserEndpoint: 'https://<Domine>/connect/userinfo',
            clientId: 'clientid',
            clientSecret: '2bb80d537b1da3e38bd30361aa855686bde0eacd7162fef6a25fe97bf527a25b'
        });
        const userData = oauth2.fetchActiveUser(token);
        res.status(201).send(JSON.stringify(userData));

    } catch (e) {
        res.status(400).send("ERROR " + e);
    }
});

**Comment by Simran-B** [comment]
What's the specific error message that you get, or how else does it fail?

**Comment by Simran-B** [comment]
@kotishwerreddy Can you provide more details please?
