### ISSUE TITLE
Foxx POST Parameters - Model Schema toggling problem

### ISSUE THREAD

**Issue by agreif** [arangodb/arangodb#1394]
toggling between "Model" and "Model Shema" does not work right...

reproducing steps:
- created a new foxx app, that generated the API.
- click on POST
- the last Parameters column shows the sample model, and the "Model" is greyed out
- click on "Model Schema" --->>> nothing happens
- clicking on "Model" --->>> shows the schema

seems that always the other link is activated as expected

hanks,
Alex.

**Comment by agreif** [comment]
seems to be the same on PUT and PATCH

**Comment by pluma** [comment]
That seems to be a bug in Swagger itself. The labels are mixed up (the markup itself indicates that they should be labelled the other way around).
