### ISSUE TITLE
Graph edges not returned completely

### ISSUE THREAD

**Issue by sbakiu** [arangodb/arangodb#1396]
In queries like:
`FOR i IN GRAPH_EDGES ('GraphName', null, {}) return i`
it is returned only the edge handle. This prevents me from filtering based on other attributes stored in graph edges. This issue started for me after updating to v2.6.1.

**Comment by mchacki** [comment]
in 2.6 we have updated the API for GRAPH_EDGES to allow some performance tweaking.
The default return format of GRAPH_EDGES is one of the things we have changed.
Therefore we have added a new option `includeData` to trigger if the JSON should be build up or only _id handles should be passed around (which is in most cases sufficient for further traversals and a lot faster especially if the documents are large).


So to fix your query the following should be enough:

```
FOR i IN GRAPH_EDGES ('GraphName', null, {includeData: true}) return i
                                         ^^^^^^^^^^^^^^^^^^^^
```

**Comment by sbakiu** [comment]
Thanks @mchacki for the quick reply

**Comment by CoDEmanX** [comment]
It's not a bug, it's a feature: #1354

@mchacki: The breaking changes are somewhat hidden...
https://docs.arangodb.com/Upgrading/UpgradingChanges26.html#aql-graph-functions
... I would expect them rather in *2. Whats new* than in *1. Installing*. People don't seem to find these important notes.
