### ISSUE TITLE
Question - using indexes in complex query

### ISSUE THREAD

**Issue by Minstel** [arangodb/arangodb#13980]
## My Environment

* __ArangoDB Version__:      ArangoDB 3.7.10 [linux] 64bit
* __Storage Engine__:           RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:        
* __Total RAM in your machine__:        
* __Disks in use__:        
* __Used Package__:              

## Component, Query & Data

__Affected feature__:
Using indexes in complex query

__AQL query (if applicable)__:
```
let result = (
    for record in test_group
    collect hash = record.sha256 into records_by_hash
    let groups = {
        hash,
        grouped: (
            for item in records_by_hash
            sort item.date
            limit 3
            return item
        )
    }
    for item in groups.grouped
        return item
)
return result

```
__AQL explain and/or profile (if applicable)__:

```
Query String (343 chars, cacheable: true):
 let result = (
     for record in test_group
     collect hash = record.sha256 into records_by_hash
     let groups = {
         hash,
         grouped: (
             for item in records_by_hash
             sort item.date
             limit 3
             return item
         )
     }
     for item in groups.grouped
         return item
 )
 return result

Execution plan:
 Id   NodeType            Est.   Comment
  1   SingletonNode          1   * ROOT
 21   SubqueryStartNode      1     - LET result = ( /* subquery begin */
 20   IndexNode              4       - FOR record IN test_group   /* persistent index scan */    
  4   CalculationNode        4         - LET #11 = record.`sha256`   /* attribute expression */   /* collections used: record : test_group */
  5   CollectNode            4         - COLLECT hash = #11 INTO records_by_hash KEEP record   /* sorted */
 23   SubqueryStartNode      4         - LET #4 = ( /* subquery begin */
  7   EnumerateListNode    400           - FOR item IN records_by_hash   /* list iteration */
  8   CalculationNode      400             - LET #13 = item.`date`   /* attribute expression */
  9   SortNode             400             - SORT #13 ASC   /* sorting strategy: constrained heap */
 10   LimitNode              3             - LIMIT 0, 3
 24   SubqueryEndNode        4             - RETURN  item ) /* subquery end */
 15   EnumerateListNode    400         - FOR item IN #4   /* list iteration */
 22   SubqueryEndNode        1           - RETURN  item ) /* subquery end */
 18   ReturnNode             1     - RETURN result

Indexes used:
 By   Name     Type         Collection   Unique   Sparse   Selectivity   Fields         Ranges
 20   sha256   persistent   test_group   false    false        50.00 %   [ `sha256` ]   *

Optimization rules applied:
 Id   RuleName
  1   simplify-conditions
  2   move-calculations-up
  3   remove-unnecessary-calculations
  4   use-indexes
  5   use-index-for-sort
  6   sort-limit
  7   splice-subqueries
```

__Dataset__:
A single collection have records with fields:
- `sha256`
- `date`
- possibly some other fields

Single field indexes for both fields, 2-fields indexes for them too.

__Size of your Dataset on disk__:
Does not matter

__Problem__:
In this query I try to sort and limit records in each group of grouped data and in the end ungroup them to use result list further.

In `Optimization rules applied` block you can see `use-index-for-sort`. But in `Indexes used` block only `sha256` index is listed. So it seems that index is not used for sorting.

__Expected result__:
Index for `date` field should be used for sorting. It seems that nothing prevents to use compound index here, that covers both fields `sha256` and `date`, but it doesn't work. Maybe there's another way to construct query to achieve the same result?

**Comment by rivet351** [comment]
Hi Minstel,
Have you look at using index hints? We used this for similar issues:
https://www.arangodb.com/learn/development/index-hints-named-indices/

**Comment by Minstel** [comment]
@rivet351 Ah, that looks like the needed solution) Thanks a lot, I'll try it.
But why `use-index-for-sort` is included into `Optimization rules applied`, if index is not really used?

**Comment by goedderz** [comment]
It is applied: The COLLECT is instantiated as a sorted collect, which needs its input to be sorted. So usually, there'd have to be a SORT in front of the COLLECT, which is omitted by `use-index-for-sort`.

**Comment by Minstel** [comment]
@goedderz I do not entirely understand you, specifically this phrase: 
> there'd have to be a SORT in front of the COLLECT, which is omitted by use-index-for-sort

What do you mean by ommited? First you say that index is applyed and then you said that sorting is ommited.
Or you mean that `use-index-for-sort` automatically sorts data for `COLLECT` to obtain sorted input?
But what index is used for this, how to check this?

I intentionally use sort separately for each group as this way it should do less comparisons.
Although I also tryed to use it before collect, but explain output was the same concerning sorting index.

**Comment by goedderz** [comment]
> Or you mean that use-index-for-sort automatically sorts data for COLLECT to obtain sorted input?

Exactly.

> But what index is used for this, how to check this?

The only one in use: `sha256`. Note this line:

```
 20   IndexNode              4       - FOR record IN test_group   /* persistent index scan */    
```

This `FOR` scans the index `sha256`, and emits rows ordered by that field. That's why an additional `SORT record.sha256` before the `COLLECT` would be redundant, and thus `use-index-for-sort` removed that `SORT` node.

**Comment by Simran-B** [comment]
@Minstel Is your question answered?
