### ISSUE TITLE
Homebrew Update

### ISSUE THREAD

**Issue by terrybleger** [arangodb/arangodb#1398]
Hi,

Every time ArangoDB release a new version, I'll always get notification either via web console or arangosh and like bugging me to update.

But the problem is the homebrew version update will always get late release about maybe 1 week than the other releases. This is kinda sad.

**Comment by fceller** [comment]
The last step is a manual one. What you can do, is use the repository "fceller/homebrew" in addition to "homebrew". The version there is updated as soon as the other releases are build.
