### ISSUE TITLE
AQL-Queries are not saved in web frontend

### ISSUE THREAD

**Issue by crs-** [arangodb/arangodb#1399]
Hi,
if I save a new AQL query in the AQL editor in the web frontend the query appears first in the My Queries tab and also in the drop down list. But when I reload the web frontend both (the My Queries tab and drop down list) are empty.
Tested with Firefox (Cyberfox v. 38.0.6), Opera v. 30 and ArangoDB v. 2.6.1

**Comment by jsteemann** [comment]
Probably related to #1402, and should be fixed in 2.6.3.
