### ISSUE TITLE
arangodb is creating continuous files in journals folder which is causing the space to be full on disk

### ISSUE THREAD

**Issue by vaibhavgupta18** [arangodb/arangodb#14009]
[##](url) My Environment

* __ArangoDB Version__:        3.3.16
* __Storage Engine__:             MMFiles
* __Deployment Mode__:       Single Server
* __Configuration__:               
* __Infrastructure__:               AWS
* __Operating System__:        Ubuntu 
* __Disks in use__:        900 GB

## Component, Query & Data

__Affected feature__:
arangodb server filesystem full

after restart it releases the space  but again occupies the space 
unable to create new WAL reserve logfile: filesystem full
unable to create logfile: filesystem full

![image](https://user-images.githubusercontent.com/82778460/115158758-6c32ff80-a0ad-11eb-8644-ce5cbf06c168.png)

**Comment by Simran-B** [comment]
Hi @vaibhavgupta18,
3.3, as well as 3.4 and 3.5, are end of life. The problem sounds very similar to #13100, however. Therefore, you could try to disable statistics and see if that helps to reduce the amount of data written to disk during idle time.

**Comment by Simran-B** [comment]
A difference to #13100 that I didn't notice initially is that you are using MMFiles and not RocksDB. I'm not sure if the problem with ever-growing log files can happen with MMFiles too. Anyway, 3.3 has long reached End of Life. Therefore, I'm closing this issue,
