### ISSUE TITLE
GEO_DISTANCE returns null for mis-typed data

### ISSUE THREAD

**Issue by hethcox** [arangodb/arangodb#14012]
## My Environment

* 3.7.5:        
* __Storage Engine__:             
* Single Server:       
* docker:   
* none:               
* local):               
* macOS:        
* 16GB:        
* SSD:        
* official Docker:              

## Component, Query & Data

AQL (in foxx):

__AQL query (if applicable)__:
```
FOR feature IN worldAmenities
            LET d = GEO_DISTANCE(center, feature.geometry)
            FILTER d <= radius
            FILTER feature.properties.amenity == 'restaurant'
            RETURN feature

```
__AQL explain and/or profile (if applicable)__:

(all records)

Collection of GeoJSON:

<20MB:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. Execution of AQL always returns all records
2. 
3. 

We mis-imported our GeoJSON data load and the lat/lng values got encoded at strings. That was our mistake. GEO_DISTANCE returns null when evaluated because the feature.geometry is wrong. I think this should be an error since the input values are wrong.

**Comment by Simran-B** [comment]
Hi @hethcox,

the GEO_DISTANCE() function issues a warning in fact:

![image](https://user-images.githubusercontent.com/7819991/117211665-9ac51000-adf9-11eb-8ccd-30df86eaeb11.png)

`curl -sS --data '{"query":"RETURN GEO_DISTANCE(GEO_POINT(1,2), {type:\"Point\",coordinates:[\"3\",\"4\"]})"}' http://localhost:8529/_api/cursor | jq`
```json
{
  "result": [
    null
  ],
  "hasMore": false,
  "cached": false,
  "extra": {
    "warnings": [
      {
        "code": 10,
        "message": "in function 'GEO_DISTANCE()': bad parameter"
      }
    ],
    "stats": {
      "writesExecuted": 0,
      "writesIgnored": 0,
      "scannedFull": 0,
      "scannedIndex": 0,
      "filtered": 0,
      "httpRequests": 0,
      "executionTime": 0.0005123191513121128,
      "peakMemoryUsage": 3329
    }
  },
  "error": false,
  "code": 201
}
```

You can enable the query option `failOnWarning` to turn the warning into an error that aborts the query:

`curl -sS --data '{"query":"RETURN NOEVAL(GEO_DISTANCE(GEO_POINT(1,2), {type:\"Point\",coordinates:[\"2\",\"3\"]}))","options":{"failOnWarning":true}}' http://localhost:9929/_api/cursor | jq`

```json
{
  "code": 400,
  "error": true,
  "errorMessage": "AQL: in function 'GEO_DISTANCE()': bad parameter (while executing)",
  "errorNum": 10
}
```

**Comment by Simran-B** [comment]
@hethcox Does above reply answer your question?

**Comment by hethcox** [comment]
Hi @Simran-B ,
Thank you for the explanation. I don't have the mis-formatted data anymore to try this out. I don't remember seeing the warning, but I believe you. Regarding your explanation, I understand why you don't want to error out the query for bad data. It is unfortunate that in my context (null < radius) returned all values.

**Comment by Simran-B** [comment]
Yeah, that's unfortunate. We probably won't change the behavior, so the only recommendation here is to keep an eye out for AQL warnings.
