### ISSUE TITLE
FATAL cannot raise the file descriptor limit

### ISSUE THREAD

**Issue by razvanphp** [arangodb/arangodb#1401]
Configuration option `descriptors-minimum` just fails if the value is bigger than 1024 (which is the default anyway) with the following errors message:

```
2015-07-03T13:04:39 [13197] FATAL cannot raise the file descriptor limit to 32768: Operation not permitted
```

I solved this by adding the value again to the init script:
```
ulimit -n 32768
```

If this is the solution you are ok with, we should merge this into the init script and add a mention about it in the documentation.

The smart way would be if the server can do this on his own on startup, but donno if it's possible.

**Comment by fceller** [comment]
We added this to the init script.
