### ISSUE TITLE
Query export in web frontend not working

### ISSUE THREAD

**Issue by crs-** [arangodb/arangodb#1402]
Hi, if I try to export the saved queries in the web frontend of ArangoDB v. 2.6.2 my browser shows the following error message:
"Cyberfox can't find the file at http://192.168.1.25:8529/_db/MyDB/_admin/aardvark/query/download/undefined"

**Comment by jsteemann** [comment]
Code is fixed in 2.6 and devel now. Still need to rebuild the compiled frontend files using grunt.

**Comment by jsteemann** [comment]
Thanks. Should be fixed in 2.6.3 (next release version).
