### ISSUE TITLE
Firefox issues with doc

### ISSUE THREAD

**Issue by sarasfox** [arangodb/arangodb#1405]
Lot of thing and dis paring in the left side menu this is not the case in chrome.  This is breaking subcategory very badly. I am running FireFox 38.0

**Comment by 13abylon** [comment]
Sorry for the late reply. 

Could you make a screenshot of the problem? And which OS do you use?

**Comment by sarasfox** [comment]
I was making silly issue switched the key and token

**Comment by sarasfox** [comment]
shit that was not the email i though i was repling to opps i will start a
new issue and add sreen shot happly

**Comment by sarasfox** [comment]
![scent](https://cloud.githubusercontent.com/assets/4380660/8807244/6f70e338-2f98-11e5-890a-a46a758b44e5.jpg)
sorry about the email i was expecting mail form hipchat had for got about this but here is the screen shot

**Comment by CoDEmanX** [comment]
I'm pretty sure this is a known gitbook issue:
https://github.com/GitbookIO/gitbook/issues/783
Try to clear the search filter until everything is showing again.

**Comment by pluma** [comment]
I concur with @CoDEmanX. The search filter seems to be cached and can get stuck.

@sarasfox Can you confirm that clearing the search filter solves the issue?

**Comment by sarasfox** [comment]
Yes it does that's odd as was not using search

**Comment by 13abylon** [comment]
Yes, it's a known bug. Clearing the search filter will help!
