### ISSUE TITLE
Unable to use primary index in a filter with OR

### ISSUE THREAD

**Issue by ysmu** [arangodb/arangodb#14052]
## My Environment

* __ArangoDB Version__:        3.7.10
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               Default
* __Infrastructure__:               Own
* __Operating System__:        Windows 10
* __Total RAM in your machine__:        32Gb
* __Disks in use__:        HDD
* __Used Package__:              Official Windows installer

## Steps to reproduce

I have a collection `items` with about half a million documents, and I'm noticing some performance degradation with the following query:
```
FOR doc IN items
    FILTER doc._key IN @keys || doc.groupId IN @groupIds
    RETURN doc
```
The profiler shows that it was using the index on `groupIds`. I wanted to see if using the primary index would be more efficient, and was surprised I can't do the following:
```
FOR doc IN items
    OPTIONS {indexHint: "primary", "forceIndexHint": true}
    FILTER doc._key IN @keys || doc.groupId IN @groupIds
    RETURN doc
```
due to 
`Query: AQL: could not use index hint to serve query; {"indexHint":{"forced":true,"type":"simple","hint":["primary"]}} (while optimizing plan)`

As a sanity check, I removed the `||` condition, and it works fine:
```
FOR doc IN items
    OPTIONS {indexHint: "primary", "forceIndexHint": true}
    FILTER doc._key IN @keys
    RETURN doc
```

**Is there a reason why I can't force the use of the primary index in the second query?**

Right now, I'm working around the issue with the following AQL:
```
LET docs_by_id = (
    FOR doc IN items
        FILTER doc._key IN @keys
        RETURN doc
)
LET docs_by_group = (
    FOR doc IN items
        FILTER doc.groupId IN @groupIds
        RETURN doc
)
RETURN UNION_DISTINCT(docs_by_id, docs_by_group)
```
This is uses both indexes (primary and index on groupIds) and is significantly (almost 10x) faster than the first query. I remember reading somewhere ArangoDB can't utilize more than one index for a single `FOR` query, but is it something that can be improved (i.e. with an optimizer rule)? We have a lot of queries like this and I'm not sure if I should rewrite all of them into this format.

I don't see an issue with the performance of `UNION_DISTINCT`, but I wonder if we can get a more performant variation where we only do `DISTINCT` on `_id`, maybe something called `UNION_DISTINCT_DOC`

On an extended note, I would also love to be able to use index with union-ed collections:
```
FOR doc IN UNION(collection1, collection2, collection3)
    FILTER doc._id IN @ids
    RETURN doc
```
Like the workaround above, I had to expand the query into three `FOR` blocks, and do a `UNION` at the end (We also have a lot of these).

**Comment by jsteemann** [comment]
@ymsu: it looks like index hints currently work per FOR node, and if there are two subconditions on different indexes, then the optimizer will try to enforce the same hint for both indexes. Which in this case simply does not work because for one condition the primary index is needed and for the other a different index is required.
That said, the sub-optimal index selection is reported for version 3.7.10, but a change to improve index selection has been release with 3.7.11. Is it possible to recheck if the original query performs any better with 3.7.11? Thanks!

**Comment by ysmu** [comment]
With 3.7.11 I'm seeing significant performance improvements and that the FOR node is using both indexes. This shows that my previous understanding that a FOR node can only utilize one index is wrong, which is great. Thank you!

**Comment by Simran-B** [comment]
> my previous understanding that a FOR node can only utilize one index is wrong

Not quite. If you AND-combine conditions then only a single index can be utilized. There is no index intersection that would allow using both indexes. So `FILTER doc._key IN @keys && doc.groupId IN @groupIds` will only use one index.

This does not apply to OR-combined conditions, however. Multiple indexes can be utilized independently in this case.

I created an internal ticket about the problem of forcing the primary index with OR-combined conditions that require different indexes: https://arangodb.atlassian.net/browse/BTS-398

**Comment by ysmu** [comment]
> This does not apply to OR-combined conditions, however. Multiple indexes can be utilized independently in this case.

That I understand. I _thought_ it wasn't able to utilize multiple indexes due to limitations of AQL's execution engine, but am glad to be wrong 😃
