### ISSUE TITLE
graph._neighbors broken in 2.6

### ISSUE THREAD

**Issue by carlverge** [arangodb/arangodb#1407]
It looks like graph._neighbors is broken in the 2.6 train, it will return a list of nulls (though the number of results appears to be correct). This can also be seen in the generated 2.6 docs (https://docs.arangodb.com/General-Graphs/Functions.html). Example below, the same calls work in 2.5. Should also be noted that the AQL GRAPH_NEIGHBOURS call does work in 2.6.

```
arangosh [llama]> map._neighbors("node/102538965872", {direction:"inbound"})
[
  null,
  null,
  null,
  null
]
```

```
map._vertices("node/102538965872").edges().toArray()
[
  "parent/102540735344",
  "parent/102542111600",
  "parent/102541652848",
  "parent/102541194096"
]
```

**Comment by mchacki** [comment]
Thanks a lot for spotting it. The fix will be included in the next release.

Fix will be included in the next 2.6 bugfix release.
