### ISSUE TITLE
AQL: Corruption: bad block type (while executing)

### ISSUE THREAD

**Issue by Dan-Do** [arangodb/arangodb#14078]
## My Environment

arangosh (ArangoDB 3.7.10 [linux] 64bit, using jemalloc, build tags/v3.7.10-0-g1bb10a05e3, VPack 0.1.33, RocksDB 6.8.0, ICU 64.2, V8 7.9.317, OpenSSL 1.1.1j  16 Feb 2021)

## Component, Query & Data

__Affected feature__:

AQL using both web interface and arangosh

__AQL query (if applicable)__:
```
FOR p IN user_comment_thread FILTER (LIKE(p.content, "%hdd%", true) OR LIKE(p.content, "%ssd%", true)) LIMIT 0,999 RETURN p
```
__AQL explain and/or profile (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

This collection has 1,214,714 edge(s). I can browse some pages on web interface (first, last, some random pages). Ex:
http://localhost:8529/_db/mydb/_admin/aardvark/index.html#collection/user_comment_thread/documents/1

__Replication Factor & Number of Shards (Cluster only)__:

[SINGLE, server]

## Steps to reproduce
Not applicable.

__Problem__:
```
JavaScript exception in file '/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js' at 99,7: ArangoError 1100: AQL: Corruption: bad block type (while executing)
!      throw error;
!      ^
stacktrace: ArangoError: AQL: Corruption: bad block type (while executing)
    at Object.exports.checkRequestResult (/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js:97:21)
    at ArangoStatement.execute (/usr/share/arangodb3/js/client/modules/@arangodb/arango-statement.js:172:12)
    at Proxy.ArangoDatabase._query (/usr/share/arangodb3/js/client/modules/@arangodb/arango-database.js:957:45)
    at <shell command>:1:4
```
__Expected result__:
Should execute the query and return result normally.

**Comment by Simran-B** [comment]
@Dan-Do  I tried to reproduce the problem with a crude dataset:

`FOR i IN 1..1200000 INSERT {_from:CONCAT("missing/", i), _to:CONCAT("missing/", i+10000),_key:CONCAT(i), content: CONCAT_SEPARATOR(" ", RANDOM_TOKEN(RAND()*10), RAND() > 0.5 ? "HDD" : "SSD", RANDOM_TOKEN(RAND()*20)) } IN user_comment_thread`

The query works just fine, however. Could you dump the data, restore it into a fresh ArangoDB instance and check if it also occurs there? If yes, can you share the dump so that we can investigate this more closely?

**Comment by Dan-Do** [comment]
@Simran-B I used arangodump then arangorestore to a dataset called test. The query executes ok. Tried again this query with old dataset, still error.
If you need more information, let me know.

**Comment by Simran-B** [comment]
The error is raised if there is a problem while reading data from the storage engine. It looks like a corruption of the on-disk data in RocksDB. It's unclear how it got into this state. It could be a hardware or software problem.

What's interesting is that arangodump succeeded and that the restored database appears to be fine. arangorestore creates a new copy / new instance of the data, so if only one file is corrupted somehow, the restored values might be in another one without the problem. So it is possible that the restored version works while the original does not.

Can you check whether all data is complete and correct in the restored database? If so, then you may want to consider dumping and restoring your actual database to get rid of the corrupted block.

**Comment by Dan-Do** [comment]
Unfortunately it's impossible to check all data, so I will use the new dump database. BTW, can I change the name of database from `test` to `correct_name`?

**Comment by Dan-Do** [comment]
I have another issue, may be related to this. When using web interface to create a new db, I had this error:
`DB: Invalid Parameters: Corruption: block checksum mismatch: expected 2994428931, got 1826416128  in /var/lib/arangodb3/engine-rocksdb/027530.sst offset 46367847 size 9334`

**Comment by Simran-B** [comment]
Renaming databases is not possible, unfortunately. You could set up a second ArangoDB instance and restore the dump into that fresh instance using the same database name, then switch over to that instance.

To compare the documents that are stored in both instances or databases, you could use one of the drivers and do the comparison on the client-side. You should probably sort the documents by primary key and use a streaming cursor for that, e.g. `FOR doc IN coll SORT doc._key RETURN doc` and the cursor with the option `stream: true`.

**Comment by Dan-Do** [comment]
Thanks @Simran-B for the answer. I am going to close this issue.
