### ISSUE TITLE
AND returns unwanted document

### ISSUE THREAD

**Issue by pfu3tz** [arangodb/arangodb#14071]
## My Environment

* __ArangoDB Version__:        3.7.8
* __Storage Engine__:             RocksDB 6.8.9
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               -
* __Infrastructure__:               Own
* __Operating System__:        Ubuntu 18.04.5 LTS
* __Total RAM in your machine__:        16 GB
* __Disks in use__:        SSD
* __Used Package__:              Ubuntu .deb

## Component, Query & Data

__Affected feature__:
arangosh, but was originally detected with Java driver version 6.9.0

__AQL script__:
```
db._dropDatabase("testing")
db._createDatabase("testing")
db._useDatabase("testing")
db._create("t1")//1ms
db._create("t2")//1ms
db._query("INSERT { c0: 'text'} IN t1")//0ms
db._query("INSERT { c0: 'othertext'} IN t2")//0ms
db._query("INSERT { c0: 'text'} IN t2")//0ms
db.t2.ensureIndex({type: "hash", fields: [ "c0" ]});//1ms

print("Tests:")
print("The AND")
db._query("FOR rt1 IN t1 FOR rt2 IN t2 FILTER (rt2.c0 > rt2.c0) AND (rt1.c0 > rt2.c0) RETURN rt1")
print("One part of the AND")
db._query("FOR rt1 IN t1 FOR rt2 IN t2 FILTER (rt2.c0 > rt2.c0) RETURN rt1")
print("The other part of the AND")
db._query("FOR rt1 IN t1 FOR rt2 IN t2 FILTER (rt1.c0 > rt2.c0) RETURN rt1")

```
__AQL explain and/or profile (of the AND)__:

```
Query String (85 chars, cacheable: true):
 FOR rt1 IN t1 FOR rt2 IN t2 FILTER (rt2.c0 > rt2.c0) AND (rt1.c0 > rt2.c0) RETURN rt1

Execution plan:
 Id   NodeType                  Est.   Comment
  1   SingletonNode                1   * ROOT
  2   EnumerateCollectionNode      1     - FOR rt1 IN t1   /* full collection scan */
  7   IndexNode                    1       - FOR rt2 IN t2   /* hash index scan, index only, projections: c0 */    
  8   CalculationNode              1         - LET #2 = (rt1.c0 > rt2.c0)   /* simple expression */   /* collections used: rt1 : t1, rt2 : t2 */
  5   FilterNode                   1         - FILTER #2
  6   ReturnNode                   1         - RETURN rt1

Indexes used:
 By   Name                      Type   Collection   Unique   Sparse   Selectivity   Fields     Ranges
  7   idx_1698095946475241472   hash   t2           false    false       100.00 %   [ c0 ]   (rt1.c0 > rt2.c0)

Optimization rules applied:
 Id   RuleName
  1   use-indexes
  2   remove-filter-covered-by-index
  3   reduce-extraction-to-projection

```

## Steps to reproduce
The AQL query script above should reproduce the issue, maybe even on the latest version.

__Problem__:
The script consists of 3 queries. The first is an AND query of the other two expressions. When looking at the results of these last two, we should expect the AND to return no document at all, because (rt2.c0 > rt2.c0) does not evaluate to TRUE for any document. But when I execute the AND query I still get a document.

_Note_:
I really tried to make this simpler, but as far as I know, it is necessary to have three documents at least, as well as, the index to reproduce this issue.

__Expected result__:
The AND query should not return any document.

**Comment by Simran-B** [comment]
I can confirm that
- `rt1.c0 > rt2.c0` matches `"c0" : "text"`
- `rt2.c0 > rt2.c0` does not match anything
- `rt2.c0 > rt2.c0 AND rt1.c0 > rt2.c0` matches `"c0" : "text"` even though it should not
- `NOEVAL(rt2.c0 > rt2.c0) AND rt1.c0 > rt2.c0` does not match anything as expected

I narrowed the problem down to an optimizer rule:

`db._explain("FOR rt1 IN t1 FOR rt2 IN t2 FILTER rt2.c0 > rt2.c0 AND rt1.c0 > rt2.c0 RETURN rt1")`

```js
Execution plan:
 Id   NodeType                  Est.   Comment
  1   SingletonNode                1   * ROOT
  2   EnumerateCollectionNode      1     - FOR rt1 IN t1   /* full collection scan */
  7   IndexNode                    1       - FOR rt2 IN t2   /* hash index scan, index only, projections: `c0` */
  8   CalculationNode              1         - LET #2 = (rt1.`c0` > rt2.`c0`)   /* simple expression */   /* collections used: rt1 : t1, rt2 : t2 */
  5   FilterNode                   1         - FILTER #2
  6   ReturnNode                   1         - RETURN rt1

Indexes used:
 By   Name                      Type   Collection   Unique   Sparse   Selectivity   Fields     Ranges
  7   idx_1698316603326726144   hash   t2           false    false       100.00 %   [ `c0` ]   (rt1.`c0` > rt2.`c0`)

Optimization rules applied:
 Id   RuleName
  1   use-indexes
  2   remove-filter-covered-by-index
  3   reduce-extraction-to-projection

72 rule(s) executed, 2 plan(s) created
```

`db._explain("FOR rt1 IN t1 FOR rt2 IN t2 FILTER rt2.c0 > rt2.c0 AND rt1.c0 > rt2.c0 RETURN rt1", {}, {optimizer:{rules:["-remove-filter-covered-by-index"]}})`

```js
Execution plan:
 Id   NodeType                  Est.   Comment
  1   SingletonNode                1   * ROOT
  2   EnumerateCollectionNode      1     - FOR rt1 IN t1   /* full collection scan */
  7   IndexNode                    1       - FOR rt2 IN t2   /* hash index scan, index only, projections: `c0` */
  4   CalculationNode              1         - LET #2 = ((rt2.`c0` > rt2.`c0`) && (rt1.`c0` > rt2.`c0`))   /* simple expression */   /* collections used: rt2 : t2, rt1 : t1 */
  5   FilterNode                   1         - FILTER #2
  6   ReturnNode                   1         - RETURN rt1

Indexes used:
 By   Name                      Type   Collection   Unique   Sparse   Selectivity   Fields     Ranges
  7   idx_1698316603326726144   hash   t2           false    false       100.00 %   [ `c0` ]   (rt1.`c0` > rt2.`c0`)

Optimization rules applied:
 Id   RuleName
  1   use-indexes
  2   reduce-extraction-to-projection

69 rule(s) executed, 2 plan(s) created
```

`` (rt2.`c0` > rt2.`c0`) `` is removed by the optimizer rule `remove-filter-covered-by-index` even though it does have an effect.

**Comment by Simran-B** [comment]
@maxkernbach Can you check whether #14035 included in 3.7.11 happens to fix this?

**Comment by maxkernbach** [comment]
@Simran-B I checked 3.7.11, but this fix does not seem to help here.

`` (rt2.`c0` > rt2.`c0`) `` is still removed by the optimizer rule `remove-filter-covered-by-index` even though it does have an effect.

**Comment by Simran-B** [comment]
I created an internal ticket https://arangodb.atlassian.net/browse/BTS-400

**Comment by Simran-B** [comment]
The problem does not appear to occur anymore in 3.7.12 and 3.8.0 seems fine as well. @pfu3tz can you upgrade to the latest 3.7 version (currently 3.7.13) and check it on your end? It appears as though an unrelated bug fix resolved the issue.

**Comment by pfu3tz** [comment]
Tested it on my side with v3.8.0 and looks good.
Thanks guys
