### ISSUE TITLE
Document by Id with Integer

### ISSUE THREAD

**Issue by seijikun** [arangodb/arangodb#1408]
In ArangoDB 2.6.2, using something like the following to retrieve a document by its id:
```
var x = 133713374242
var person = personRepository.byId( x );
```
results in the Error:
```
[ArangoError 1503: TypeError: expecting string ID for <startVertex> (while executing)]
```

Using something like the following in AQL, however, simply returns null without any error:
```
RETURN DOCUMENT(person, 133713374242)
```

It took me quite some time to figure out what was going on (in both cases). Is there a reason, why integer is not allowed as an argument for `byId()` if only the key-part of the id is given?
I took the code from the example [here (pathParam)](https://docs.arangodb.com/Foxx/Develop/Controller.html#pathparam) - where id is validated with Joi's integer() -  but when I want to use this id-parameter, I always have to call `toString()` on it.

**Comment by CoDEmanX** [comment]
`_key` is actually a string property, and never an integer, even if it's "123585712", so it's somewhat expectable.

> A document handle uniquely identifies a document in the database. It is a string and consists of the collection's name and the document key (_key attribute) separated by /.

https://docs.arangodb.com/Documents/index.html

I'm not sure if implicit casting to string could be problematic under certain circumstances...

**Comment by pluma** [comment]
You're right, the Foxx documentation is misleading. It should not make any assumptions about the format of the keys and just use joi.string.
