### ISSUE TITLE
Primary index is not used when filtering on doc._key

### ISSUE THREAD

**Issue by AntoineAA** [arangodb/arangodb#14099]
## My Environment

* __ArangoDB Version__:        3.7.10
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               
* __Infrastructure__:               own
* __Operating System__:        Ubuntu 18.04
* __Total RAM in your machine__:         128Gb
* __Disks in use__:        HDD
* __Used Package__:              Ubuntu .deb
* 
## Component, Query & Data

__Affected feature__:
AQL query using web interface | arangosh | with driver

__AQL query (if applicable)__:
```
for v in votes
	filter v.user_id == '100585386'
	filter !v.generated
	filter v.type == "determination"
	for o in observations
		filter o._key == v.observation_id
		filter o.author.id != '100585386'
		filter o.computed.valid == true
		filter o.computed.current_name != o.submitted.name
		filter v.value == o.computed.current_name
		collect with count into c return c

```
__AQL explain and/or profile (if applicable)__:
```
Query String (367 chars, cacheable: true):
 for v in votes
 	filter v.user_id == '100585386'
 	filter !v.generated
 	filter v.type == "determination"
 	for o in observations
 		filter o._key == v.observation_id
 		filter o.author.id != '100585386'
 		filter o.computed.valid == true
 		filter o.computed.current_name != o.submitted.name
 		filter v.value == o.computed.current_name
 		collect with count into c return c
 

Execution plan:
 Id   NodeType          Est.   Comment
  1   SingletonNode        1   * ROOT
 23   IndexNode            3     - FOR v IN votes   /* hash index scan, projections: `value`, `observation_id`, `generated` */    FILTER ! v.`generated`   /* early pruning */   
 22   IndexNode            3       - FOR o IN observations   /* hash index scan, projections: `submitted`, `computed`, `_key`, `author` */    
 10   CalculationNode      3         - LET #9 = ((o.`_key` == v.`observation_id`) && ((o.`author`.`id` != "100585386") && (o.`computed`.`current_name` != o.`submitted`.`name`)))   /* simple expression */   /* collections used: o : observations, v : votes */
 11   FilterNode           3         - FILTER #9
 20   CollectNode          1         - COLLECT  WITH COUNT INTO c   /* count */
 21   ReturnNode           1         - RETURN c

Indexes used:
 By   Name              Type   Collection     Unique   Sparse   Selectivity   Fields                                          Ranges
 23   idx_10220207381   hash   votes          false    false        31.94 %   [ `user_id`, `type` ]                           ((v.`user_id` == "100585386") && (v.`type` == "determination"))
 22   idx_49033         hash   observations   false    false        60.05 %   [ `computed.valid`, `computed.current_name` ]   ((o.`computed`.`valid` == true) && (v.`value` == o.`computed`.`current_name`))

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   move-calculations-up-2
  4   move-filters-up-2
  5   use-indexes
  6   remove-filter-covered-by-index
  7   remove-unnecessary-calculations-2
  8   fuse-filters
  9   reduce-extraction-to-projection
 10   move-filters-into-enumerate
```

## Steps to reproduce

1. Run the query.

__Problem__: The primary index is not used.

__Expected result__: The primary index is used.

Note : if I replace `filter v.value == o.computed.current_name` (to force the use of the primary index) by
```
let tmp = CONCAT(o.computed.current_name, '')
filter v.value == tmp
```
the request takes 400ms to execute instead of 180s.

Thank you for your help.
All the best,

**Comment by AntoineAA** [comment]
PS: on our test environment, the primary index is used while running the original AQL query.
```
Indexes used:
 By   Name              Type      Collection   Unique   Sparse   Selectivity   Fields                  Ranges
 26   idx_11017027969   hash      z_votes      false    false         7.00 %   [ `user_id`, `type` ]   ((v.`user_id` == "100585386") && (v.`type` == "determination"))
 25   primary           primary   z_obs        true     false       100.00 %   [ `_key` ]              (o.`_key` == v.`observation_id`)

```

**Comment by jsteemann** [comment]
@AntoineAA : I remember having worked on improving the index selection internals recently.
The change was done via PR https://github.com/arangodb/arangodb/pull/13687, which was merged into 3.7 via commit 70821bcde4ac15714709d40aadc40a8c11bd9e4d about a month ago. The change was triggered by Github issue https://github.com/arangodb/arangodb/issues/13665.

I just checked and found that the particular commit should be in tag v3.7.11, which fortunately was released by now. It came out just yesterday.

So could you check if with 3.7.11 the index selection has got better for this particular query?

**Comment by AntoineAA** [comment]
@jsteemann this issue is happening on our production server, we can't shut down our services during the spring. For now, I will change the AQL query as in my second message to work around the problem.

Tank you for your reply.
I will keep you informed as soon as we have updated to version 3.7.11

**Comment by jsteemann** [comment]
Ok, thanks. potentially it is also possible to use an index hint to force usage of the primary index here. I haven't tried it right now, but just wanted to mention the possibility of using something like
```
FOR doc IN collection OPTIONS {indexHint: "primary", forceIndexHint: true }
  FILTER doc._key == ...
  FILTER ... /*other filters*/
  ...

**Comment by AntoineAA** [comment]
ok, I'll try it!

**Comment by Simran-B** [comment]
Interestingly, there appear to be cases in which the primary index cannot be forced with an index hint: #14052

**Comment by jsteemann** [comment]
@Simran-B : yes, looks like. I think in #14052 this happens because the index hints currently work per FOR node, and if there are two subconditions on different indexes, then the optimizer will try to enforce the same hint for both indexes. Which in this case simply does not work because for one condition the primary index is needed and for the other a different index is required.
That said, ticket #14052 is for 3.7.10, and a change to improve index selection has been release with 3.7.11. That means the original problem in #14052 may already be fixed with 3.7.11.

**Comment by Simran-B** [comment]
@AntoineAA Did you have a chance to upgrade and check whether the index choice is better in 3.7.11, or if you can at least force the use of the primary index as jsteemann suggested?

**Comment by AntoineAA** [comment]
Hi,

Sorry for the late reply.
I can't upgrade to 3.7.11 for the moment but I forced the use of the index by modifying the request and it works.

**Comment by dothebart** [comment]
Ok, will close this now. 
If it re-occurs we can re-open.
