### ISSUE TITLE
Question: UI additions to simplify replication and sharding?

### ISSUE THREAD

**Issue by Dashue** [arangodb/arangodb#1412]
Are there any UI changes on the roadmap to bring the ease of replication and sharding on par with RethinkDb? I'm having a hard time getting an understanding of how to do replication and sharding in using ArangoDb and at the same time "it's just too easy" in RethinkDb, would love for it to be easier.

Thanks

**Comment by diegogub** [comment]
+1

**Comment by weinberger** [comment]
Yes, they are. We are rebuild our cluster management based on Apache Mesos at the moment. It would be helpful to hear what exactly made the RethinkDB way better in your eyes.

**Comment by Dashue** [comment]
The easy way of configuring sharding and replication from their ui.
"This is how many shards and replicas you currently have"
"Press here to reconfigure"

I understand that the underlying implementation details might restrict the functionality of configuration. For example if I understand it correctly ArangoDb does only support configuring shards upon collection creation and cannot be changed.

Hope that helps

**Comment by weinberger** [comment]
1st part: I got it.

2nd part: At the moment you are right. But based on our new cluster management we will build all the missing stuff. Please, give us a little bit more time.

**Comment by nlac** [comment]
+1 for mentioning RethinkDB way how does it provide sharding. I think many of us can't wait to see the new cluster management, with more better sharding and high availability. Keep up the good work!

**Comment by ericfiala** [comment]
@weinberger , you mentioned "We are rebuild our cluster management based on Apache Mesos at the moment" 
Does this mean that Arangodb cluster mode would require Mesos master / slaves + Zookeeper quorum?  Seems like many extra dependencies, and java heaps :(

**Comment by CoDEmanX** [comment]
Java! _\*shudders\*_

**Comment by weinberger** [comment]
That's unfortunately true and you can be sure it was a hard decision for us ;) But I think you should have a look at the bigger picture. Systems like Mesos, and more will come, are the future of data centers. It's makes not really sense that every backend software will contain its own cluster management. In this case I mean the lower cluster management. Is a node up or not, how I can get back a node, where can I get a new node and so on. All above that should be application specific and will be.
