### ISSUE TITLE
ArangoSearch: SEARCH NGRAM_MATCH() not matching document

### ISSUE THREAD

**Issue by ysmu** [arangodb/arangodb#14123]
## My Environment

* __ArangoDB Version__:        3.7.11
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               Default
* __Infrastructure__:               Own
* __Operating System__:        Windows 10
* __Total RAM in your machine__:        32Gb
* __Disks in use__:        SSD
* __Used Package__:              Official Windows installer

## Problem

With `doc.name` equals to `"abcdef"`, I can't get seem to get `SEARCH NGRAM_MATCH(doc.name, "abcdef", 1, "bigram")` to return true. This is my first time playing around with ArangoSearch, so please let me know if I'm doing something dumb. 

## Steps to reproduce

Full repro script follows:
```py
#!/usr/bin/env python3
import arango


def setup(db):
    db.delete_view('test_view', ignore_missing=True)
    db.delete_analyzer('bigram', ignore_missing=True)
    db.delete_collection('test_data', ignore_missing=True)

    # Create collection and insert data.
    c = db.create_collection('test_data')
    c.insert({'name': 'abcdef'})

    # Create analyzer: n-gram for 1-2 items
    db.create_analyzer(
        name='bigram',
        analyzer_type='ngram',
        properties={
            'min': 1,
            'max': 2,
            'preserveOriginal': False,
            'streamType': 'utf8'
        },
        features=['position', 'frequency'],
    )

    # Create ArangoSearch View.
    db.create_arangosearch_view(
        name='test_view',
        properties={
            'links': {
                'test_data': {
                    'includeAllFields': True,
                    'fields': {
                        'name': {
                            'analyzers': ['bigram']
                        }
                    }
                },
            }
        }
    )


client = arango.ArangoClient()
db = client.db('test')
setup(db)

# Wait for our document to show up in the view.
while True:
    results = list(db.aql.execute("""\
        FOR doc IN test_view
            FILTER doc.name == "abcdef"
            RETURN true
        """))
    if results:
        break


# Try matching doc.name with "abcdef" for 3 different thresholds. Since doc.name is exactly "abcdef", I am expecting a
# match for all three thresholds.
for threshold in [1, 0.6, 0.5]:
    results = list(db.aql.execute(f"""\
        FOR doc IN test_view
            SEARCH NGRAM_MATCH(doc.name, "abcdef", {threshold}, "bigram")
            RETURN true
        """))
    print(f'Result from "SEARCH NGRAM_MATCH(doc.name, "abcdef", {threshold})": {results}')


# Using FILER somehow works.
results = list(db.aql.execute("""\
    FOR doc IN test_view
        FILTER NGRAM_MATCH(doc.name, "abcdef", 1, "bigram")
        RETURN true
    """))
print(f'Result from "FILTER NGRAM_MATCH(doc.name, "abcdef", 1)": {results}')


# It also works in SEARCH when I'm matching a constant.
results = list(db.aql.execute("""\
    FOR doc IN test_view
        SEARCH NGRAM_MATCH("abcdef", "abcdef", 1, "bigram")
        RETURN true
    """))
print(f'Result from "SEARCH NGRAM_MATCH("abcdef", "abcdef", 1)": {results}')

```
Output:
```
Result from "SEARCH NGRAM_MATCH(doc.name, "abcdef", 1)": []
Result from "SEARCH NGRAM_MATCH(doc.name, "abcdef", 0.6)": []
Result from "SEARCH NGRAM_MATCH(doc.name, "abcdef", 0.5)": [True]
Result from "FILTER NGRAM_MATCH(doc.name, "abcdef", 1)": [True]
Result from "SEARCH NGRAM_MATCH("abcdef", "abcdef", 1)": [True]
```

**Comment by Simran-B** [comment]
Hi @ysmu,
this does not seem right, but I need to check with the ArangoSearch team. I created an internal ticket https://arangodb.atlassian.net/browse/BTS-399

**Comment by ysmu** [comment]
Thanks @Simran-B. Do you have an update on this issue?

**Comment by dothebart** [comment]
Hi, 
please note that the community subscription doesn't contain any SLA. 
Please see https://www.arangodb.com/subscriptions/ for more details.

**Comment by Simran-B** [comment]
@ysmu While not ideal, it is expected. Our docs state:

> It is recommended to use an Analyzer of type ngram with preserveOriginal: false and min equal to max

It’s actually more of a requirement. With min != max, the Analyzer produces more than one n-gram per position, but internally we do not check for more than one match per position before we move on to the next n-gram. The score is calculated based on the number of matches divided by the total amount of n-grams.

Input: `abcdef`

Position 0: `a`, `ab`
Position 1: `b`, `bc`
Position 2: `c`, `cd`
Position 3: `d`, `de`
Position 4: `e`, `ef`
Position 5: `f`

6 matched (second n-grams not counted)
11 in total
6 / 11 = 0.5454...

I will address the documentation issue to make it clearer that the Analyzer is expected to have min == max.

**Comment by ysmu** [comment]
Thanks for the clarifications. Is it possible to modify the behavior to check for more than one match at each position? I'd like to use n-grams 1-2 because it allows me to prune data by relevance (character matches and neighborhood/proximity matches). I suppose I can try to make do with two `NGRAM_MATCH()` in the `SEARCH` expression.

Is there a reason to why `SEARCH NGRAM_MATCH("abcdef", "abcdef", 1)` worked?

**Comment by Simran-B** [comment]
There is currently no plan to modify the behavior, but the issue is tracked internally and the Search team is aware.

I guess it works with two string literals because it hits a different code path that actually checks all n-grams.

**Comment by hkernbach** [comment]
The documentation has been updated - to be more precise, in this specific case. Currently, this feature works as intended. Therefore, this ticket will be closed.
