### ISSUE TITLE
ArangoDB Starter Upgrade from 3.6.9 to 3.7.10 failed with message to use --database.auto-upgrade true

### ISSUE THREAD

**Issue by garyhampson** [arangodb/arangodb#14138]
## My Environment

* __ArangoDB Version__:        3.6.9
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   ArangoDB Starter
* __Configuration__:               
```
[myuser@myserver arangodb3]$ more arangodb3cluster.service 
[Unit]
Description=Run the ArangoDB Starter
After=network.target

[Service]
Restart=on-failure
EnvironmentFile=/etc/arangodb3/arangodb.cluster.env
ExecStart=/usr/bin/arangodb \
    --starter.address=${PRIVATEIP} \
    --starter.data-dir=${DATADIR} \
    --starter.join=${STARTERENDPOINTS} \
    --server.storage-engine=rocksdb 
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=arango
TimeoutStopSec=60

[Install]
WantedBy=multi-user.target


[myuser@myserver arangodb3]$ more /etc/arangodb3/arangodb.cluster.env   
DATADIR=/var/lib/arangodb3/cluster
PRIVATEIP=10.241.4.7
STARTERENDPOINTS=10.241.4.7,10.241.4.8,10.241.4.9
```
* __Infrastructure__:               Azure 
* __Operating System__:        Linux (centos 7.8.2003)
* __Total RAM in your machine__:        Standard D8 v3 (8 vcpus, 32 GiB memory) x 3 nodes
* __Disks in use__:        SSD - 30GB OS Disk, 2TB Data Disk
* __Used Package__:              RedHat .rpm 

## Component, Query & Data

__Affected feature__:
Major version upgrade

__AQL query (if applicable)__:
```
N/A

```
__AQL explain and/or profile (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:
Dataset is 200GB

__Replication Factor & Number of Shards (Cluster only)__:
Replication Factor = 2

## Steps to reproduce
The upgrade process fails even before trying to run the `arangodb upgrade` command:

#RUN THIS ON ALL CLUSTER NODES, ONE AT A TIME
```
sudo su
rundate="$(date +%Y%m%d)"
sed -i.$rundate 's/exclude=arango/#exclude=arango/' /etc/yum.conf
mv /etc/yum.repos.d/arangodb.repo /etc/yum.repos.d/arangodb.repo.$(date +'%Y%m%d')
touch /etc/yum.repos.d/arangodb.repo
echo "[arangodb]
name=ArangoDB Project
type=rpm-md
baseurl=https://download.arangodb.com/arangodb37/RPM
gpgcheck=1
gpgkey=https://download.arangodb.com/arangodb37/RPM/repodata/repomd.xml.key
enabled=1" >> /etc/yum.repos.d/arangodb.repo
yum clean all
yum install arangodb3-3.7.10-1.0 -y
sed -i 's/Restart=on-failure/#Restart=on-failure/' /usr/lib/systemd/system/arangodb3cluster.service
sed -i 's/#KillMode=process/KillMode=process/' /usr/lib/systemd/system/arangodb3cluster.service
systemctl daemon-reload
systemctl status arangodb3cluster.service -l
kill -9 $(ps -C arangodb -fww --no-headers | awk '{print $2}')
systemctl status arangodb3cluster.service
systemctl start arangodb3cluster.service
systemctl status arangodb3cluster.service -l
```
​
#RUN THIS ON A SINGLE CLUSTER NODE TO UPGRADE THE ENTIRE CLUSTER
```
arangodb upgrade --starter.endpoint=http://$(ifconfig|grep inet |awk '{print $2}' | head -1):8528
```

#RUN THIS ON ALL CLUSTER NODES, ONE AT A TIME
```
sed -i 's/#Restart=on-failure/Restart=on-failure/' /usr/lib/systemd/system/arangodb3cluster.service
sed -i 's/KillMode=process/#KillMode=process/' /usr/lib/systemd/system/arangodb3cluster.service
systemctl daemon-reload
systemctl restart arangodb3cluster.service
sed -i 's/#exclude=arango/exclude=arango/' /etc/yum.conf
```

__Problem__:
```
May 01 04:55:14 myserver arango[7999]: 2021-05-01T04:55:14Z [8151] ERROR [3bc7f] {startup} Database directory version (30609) is lower than current version (30710).
May 01 04:55:14 myserver arango[7999]: 2021-05-01T04:55:14Z [8151] ERROR [ebca0] {startup} ----------------------------------------------------------------------
May 01 04:55:14 myserver arango[7999]: 2021-05-01T04:55:14Z [8151] ERROR [24e3c] {startup} It seems like you have upgraded the ArangoDB binary.
May 01 04:55:14 myserver arango[7999]: 2021-05-01T04:55:14Z [8151] ERROR [8bcec] {startup} If this is what you wanted to do, please restart with the
May 01 04:55:14 myserver arango[7999]: 2021-05-01T04:55:14Z [8151] ERROR [b0360] {startup}   --database.auto-upgrade true
May 01 04:55:14 myserver arango[7999]: 2021-05-01T04:55:14Z [8151] ERROR [13414] {startup} option to upgrade the data in the database directory.
May 01 04:55:14 myserver arango[7999]: 2021-05-01T04:55:14Z [8151] ERROR [24bd1] {startup} ----------------------------------------------------------------------'
May 01 04:55:14 myserver arango[7999]: 2021-05-01T04:55:14Z [8151] ERROR [1c156] Database '_system' needs upgrade. Please start the server with --database.auto-upgrade
May 01 04:55:14 myserver arango[7999]: 2021-05-01T04:55:14Z [8151] FATAL [2eb08] Database '_system' upgrade failed (bad parameter). Please inspect the logs from the upgrade procedure and try starting the server again.
```

__Expected result__:

Successful upgrade of Arango.

__Version prior to binary install__:
```
[myuser@myserver arangodb3]$ arangod --version
3.6.9

architecture: 64bit
arm: false
asan: false
asm-crc32: true
assertions: false
avx2: false
boost-version: 1.71.0
build-date: 2020-11-05 22:34:41
build-repository: tags/v3.6.9-0-ged28e43e5d5
compiler: gcc [9.2.0]
cplusplus: 201703
curl-version: libcurl/7.66.0 OpenSSL/1.1.1g
debug: false
endianness: little
failure-tests: false
fd-client-event-handler: poll
fd-setsize: 1024
full-version-string: ArangoDB 3.6.9 [linux] 64bit, using jemalloc, build tags/v3.6.9-0-ged28e43e5d5, VPack 0.1.33, RocksDB 6.2.0, ICU 58.1, V8 7.1.302.28, OpenSSL 1.1.1g  21 Apr 2020
icu-version: 58.1
ipo: true
iresearch-version: 1.0.0.0
jemalloc: true
license: community
maintainer-mode: false
ndebug: true
openssl-version-compile-time: OpenSSL 1.1.1g  21 Apr 2020
openssl-version-run-time: OpenSSL 1.1.1g  21 Apr 2020
optimization-flags: -march=westmere -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mno-sse4a -mno-avx -mno-fma -mno-bmi2 -mno-avx2 -mno-xop -mno-fma4 -mno-avx512f -mno-avx512vl -mno-avx512pf -mno-avx512er -mno-avx512cd -mno-avx512dq -mno-avx512bw -mno-avx512ifma -mno-avx512vbmi
pic: 2
pie: 2
platform: linux
reactor-type: epoll
rocksdb-version: 6.2.0
server-version: 3.6.9
sizeof int: 4
sizeof long: 8
sizeof void*: 8
sse42: true
tsan: false
unaligned-access: true
v8-version: 7.1.302.28
vpack-version: 0.1.33
zlib-version: 1.2.11
```

__Version after binary install__:
```
[myuser@myserver arangodb3]$ arangod --version
3.7.10

architecture: 64bit
arm: false
asan: false
asm-crc32: true
assertions: false
avx2: false
boost-version: 1.71.0
build-date: 2021-03-14 15:55:30
build-repository: tags/v3.7.10-0-g1bb10a05e3
compiler: gcc [9.3.0]
cplusplus: 201703
curl-version: none
debug: false
endianness: little
failure-tests: false
fd-client-event-handler: poll
fd-setsize: 1024
full-version-string: ArangoDB 3.7.10 [linux] 64bit, using jemalloc, build tags/v3.7.10-0-g1bb10a05e3, VPack 0.1.33, RocksDB 6.8.0, ICU 64.2, V8 7.9.317, OpenSSL 1.1.1j  16 Feb 2021
icu-version: 64.2
ipo: true
iresearch-version: 1.0.0.0
jemalloc: true
libunwind: true
license: community
maintainer-mode: false
ndebug: true
openssl-version-compile-time: OpenSSL 1.1.1j  16 Feb 2021
openssl-version-run-time: OpenSSL 1.1.1j  16 Feb 2021
optimization-flags: -march=westmere -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mno-sse4a -mno-avx -mno-fma -mno-bmi2 -mno-avx2 -mno-xop -mno-fma4 -mno-avx512f -mno-avx512vl -mno-avx512pf -mno-avx512er -mno-avx512cd -mno-avx512dq -mno-avx512bw -mno-avx512ifma -mno-avx512vbmi
pic: 2
pie: 2
platform: linux
reactor-type: epoll
rocksdb-version: 6.8.0
server-version: 3.7.10
sizeof int: 4
sizeof long: 8
sizeof void*: 8
sse42: true
tsan: false
unaligned-access: true
v8-version: 7.9.317
vpack-version: 0.1.33
zlib-version: 1.2.11
```

**Comment by garyhampson** [comment]
We've tried following all the necessary steps found in the [documentation](https://www.arangodb.com/docs/stable/upgrading-starter.html) in our bash script above.

**Comment by garyhampson** [comment]
Also, as an fyi: When we upgraded our Dev and Staging environments, we didn't run into this issue. This may be due to their being on version 3.6.12 and not 3.6.9 like our Production environments, however. We will attempt in a sandbox environment, an upgrade from 3.6.9 to 3.6.12 and then finally to 3.7.10 to see if we can upgrade successfully.

**Comment by dothebart** [comment]
Hi, 
the best tested (and thus to be preferred ) upgrade path would be to first upgrade to the latest patch release of a minor version, and after that do the minor version upgrade
(so first => 3.6.12, then latest 3.7.x)
This is a known to be fixed issue with the starter, 3.6.12 should have the latest starter version with that fix (hence you probably didn't see it in your other environments)

You can fix the situation by manually running the upgrade command once.

**Comment by garyhampson** [comment]
@dothebart - Do you have the issue number for the known issue with the starter that you reference?

We will attempt 3.6.9 => 3.6.13 => 3.7.10. If any further issues arise, we'll note them here. If no issues, I'll set this issue to closed.

**Comment by garyhampson** [comment]
@dothebart - We are able to successfully upgrade our sandbox environment from 3.6.9 to 3.6.13, but we get the same error message going from 3.6.13 to 3.7.10:

`May 05 23:35:00 dev-eastus-arangodb1 arango[791]: 2021-05-05T23:35:00Z [942] ERROR [3bc7f] {startup} Database directory version (30613) is lower than current version (30710).
May 05 23:35:00 dev-eastus-arangodb1 arango[791]: 2021-05-05T23:35:00Z [942] ERROR [ebca0] {startup} ----------------------------------------------------------------------
May 05 23:35:00 dev-eastus-arangodb1 arango[791]: 2021-05-05T23:35:00Z [942] ERROR [24e3c] {startup} It seems like you have upgraded the ArangoDB binary.
May 05 23:35:00 dev-eastus-arangodb1 arango[791]: 2021-05-05T23:35:00Z [942] ERROR [8bcec] {startup} If this is what you wanted to do, please restart with the
May 05 23:35:00 dev-eastus-arangodb1 arango[791]: 2021-05-05T23:35:00Z [942] ERROR [b0360] {startup}   --database.auto-upgrade true
May 05 23:35:00 dev-eastus-arangodb1 arango[791]: 2021-05-05T23:35:00Z [942] ERROR [13414] {startup} option to upgrade the data in the database directory.
May 05 23:35:00 dev-eastus-arangodb1 arango[791]: 2021-05-05T23:35:00Z [942] ERROR [24bd1] {startup} ----------------------------------------------------------------------'
May 05 23:35:00 dev-eastus-arangodb1 arango[791]: 2021-05-05T23:35:00Z [942] ERROR [1c156] Database '_system' needs upgrade. Please start the server with --database.auto-upgrade
May 05 23:35:00 dev-eastus-arangodb1 arango[791]: 2021-05-05T23:35:00Z [942] FATAL [2eb08] Database '_system' upgrade failed (bad parameter). Please inspect the logs from the upgrade procedure and try start
May 05 23:35:00 dev-eastus-arangodb1 arango[791]: ## End of agent log component=arangodb`

**Comment by dothebart** [comment]
ok, whats the reason that arangod exits with during the upgrade? please have a look at the last PID's output just before the upgrade.

**Comment by garyhampson** [comment]
The process throws those errors even before we get a chance to run this:
```
arangodb upgrade --starter.endpoint=http://$(ifconfig|grep inet |awk '{print $2}' | head -1):8528

```

These errors are happening after we install the new binaries and restart the arangodb3cluster.service.

**Comment by garyhampson** [comment]
Here are the journal logs for each server, showing the successful upgrade from 3.6.9 to 3.6.13 and the subsequent failure upgrading to 3.7.10:
[server3.txt](https://github.com/arangodb/arangodb/files/6435420/server3.txt)
[server2.txt](https://github.com/arangodb/arangodb/files/6435421/server2.txt)
[server1.txt](https://github.com/arangodb/arangodb/files/6435422/server1.txt)

**Comment by garyhampson** [comment]
@Simran-B The labels `2 Fixed` or `Waiting User Reply` have been applied erroneously. This issue is neither of those two statuses.

**Comment by Simran-B** [comment]
It looks like the upgrade is incomplete after a glance at the logs, as the data files are still on the 3.6.13 format. What's strange is that the starter logs seem to miss some events, such as the start of the upgrade from 3.6 to 3.7. Any idea what the reason could be for that?

server3.txt:
- Created plan to upgrade from [3.6.13] to [3.6.13] component=arangodb
- Finished upgrading dbserver component=arangodb
- Finished upgrading coordinator component=arangodb
- Upgrade plan has finished successfully component=arangodb

server2.txt:
- not a single occurrence of "upgrade" in the log file

server1.txt:
- no occurrence of "upgrade" except in the error message that says that the data file format isn't on 3.7.10 yet

**Comment by garyhampson** [comment]
No idea. Going from 3.6.9 to 3.6.13 throws no errors, and even then, I only see one server out of the three having those upgrade plan messages in the log files. After I install the 3.7.10 binaries, and before I run arangodb upgrade, I get those error messages I mentioned above.

**Comment by garyhampson** [comment]
I'd be willing to hop on a Zoom with an engineer to show them exactly the steps I'm running and for them to see the state of the cluster nodes and the output of any logs.

**Comment by garyhampson** [comment]
Any update on this?

**Comment by kvahed** [comment]
@garyhampson I acknowledge 2 things:
* Your process is precisely as the documentation suggests the upgrade
* The `kill -9`, which is supposed to solely kill the `starter` process leaving eveything else running for the proper upgrade kills all child processes
I will get back to you with a solution

**Comment by kvahed** [comment]
@garyhampson The issue seems to be that when you change the `Killmode` for the upgrade process to `process`, it is not honored by systemd on RedHat and it's sub processes are killed. I am trying to figure out, why that is.

**Comment by garyhampson** [comment]
Hi @kvahed - When I use this procedure to upgrade to a newer minor version (say 3.6.12 to 3.6.13), I don't have any issue with the `KillMode` switch.

**Comment by kvahed** [comment]
Hi @garyhampson, that is because the file formats have not changed between 3.6.12 and 3.6.13. ;)

**Comment by kvahed** [comment]
I had a typo on my side. So Forget all that I claimed regarding the kill mode not being appreciated. You are missing the `KillMode` parameter in your systemd script. When you add it to be default - like so: `#KillMode=process` - your upgrade will work.

**Comment by maxkernbach** [comment]
Hi @garyhampson,

Can you confirm that the upgrade from 3.6.13 to 3.7.10 succeeds once `KillMode=process` (without leading #) is present in the `systemd` script of all cluster nodes?

**Comment by garyhampson** [comment]
Hello,

Yes, I can confirm. That was an unknown difference in our build scripts where our non-prod systems had the KillMode parameter in the cluster service systemd unit file (likely added manually) but our prod systems and any newly built systems didn’t. Since adding that to our build scripts, we’ve been able to launch v3.6.13 clusters and upgrade to v3.7.11 successfully.

Kind regards,

Gary Hampson
________________________________
