### ISSUE TITLE
RangeError: Invalid string length on large traversal

### ISSUE THREAD

**Issue by hfaran** [arangodb/arangodb#1415]
Hello,

### Issue

This issue is related to #1352. In our case, when performing a particularly large traversal using `_api/traversal` (in our case, it is an outbound traversal from a vertex that has 500~1200 edges), it seems that the response is too large and the V8 worker performing the serialization throws a `RangeError: Invalid string length` and is unable to return the response.

### Possible Solutions

There a few ways I can think of working around this:

1. Allowing transformations/filtering on returned vertices as a way of reducing the response size
    * For example, having the vertices only return their `_key` instead of the entire body, which would significantly reduce the response size for us
    * This **might** be currently possible by providing a `visitor` function to the `_api/traversal` body but I'm unsure of this from [the docs](https://docs.arangodb.com/HttpTraversal/index.html).
2. Allowing pagination from the traversal query using `LIMIT` (such as can be done with queries) or something similar so that the traversal result can be retrieved over several responses that are successfully serializable.
3. Configuring V8 with a higher limit
    * I don't know if this is possible at all with V8 :/
    * 256MB does seem a little small though; it's curious why this is the set limit. And that we are hitting it with a traversal with just over a thousand vertices is especially limiting.

Thanks in advance for your help with this. :smiley:

**Comment by jsteemann** [comment]
This is a built-in limit of V8, so I think it can't be increased. 
It's likely that the error happens during serialization of the result to a JSON string, and if so, I think the only way to get rid of it is to create a smaller result. Using a visitor function is possible in a traversal.

The visitor function has a signature of `void visitor (config, result, vertex, path, connected)`. That means its return value will be ignored, but it can modify the `result` variable which is passed by reference.

A simple example for using a visitor to return only the ids of the visited vertices is below:
```bash
curl -X POST http://127.0.0.1:8529/_api/traversal \
  --data '{"startVertex":"test/myStartVertex","edgeCollection":"myEdgeCollection","direction":"outbound","visitor":"result.visited.vertices.push(vertex._id)"}'
```

**Comment by hfaran** [comment]
Thanks for the response @jsteemann. I guess the `visitor` function is what I'm looking for then so I'll give that a go in a few days!

That being said, for a longer term solution, is pagination something you'd consider adding to the `_api/traversal` endpoint? Even though in this case I don't need the entirety of the >256MB response so I can cut it down to make it fit, it's entirely possible that at one point someone might and they don't have the option of just making the a more limited query to get a smaller result.
One **could** always do something like just fetch IDs of vertices and then fetch the documents  individually if further data is required but this seems like it would be quite a lot more expensive than a batch fetch of data from the single query. I'd love to hear your thoughts on the matter.

**Comment by jsteemann** [comment]
We're currently investigating building traversal functionality with pagination (i.e. skip & limit). This is not finished yet, and I cannot provide any sensible timings, but we're looking into it already.

**Comment by hfaran** [comment]
So it seems that for now, I'm able to sidestep the problem by using a custom visitor function! If you'd like you can close this issue, unless you want to keep it open for the pagination discussion of course.

Cheers!
