### ISSUE TITLE
How to build rpm and deb packages for modified ArangoDB

### ISSUE THREAD

**Issue by abelyaevskiy** [arangodb/arangodb#1417]
Hi!

I use custom modified ArangoDB and need to create rpm and deb packages for x86_64. How can I build these packages?

**Comment by dothebart** [comment]
Oh, a new hardware architecture? ;-)
First of all, ArangoDB is an opensource Project and lives from the feedback and submissions from its community; Could you elaborate a little more why the existing packages don't suit your needs, and what you changed?
We use openSUSE Build Service to build our packages; Thus you can use [OSC](https://en.opensuse.org/openSUSE:OSC) to fetch the contents of the packaging informations from [the fceller repository on openSUSE Build Service](https://build.opensuse.org/package/show/home:fceller:version2/arangodb-2.6?rev=5)

**Comment by abelyaevskiy** [comment]
Hi! 

Fixed! Thank you! 

In our team we extend ArangoDBs with custom module for indexing. So, we really need to rebuild modified ArangoDB's packages.

In Gnumakefile I see cpak usage for packanging for other architectures.

Can we use cpack for build rpm and deb packages in the ArangoDB? Why do you not use cpak fot packaging?

**Comment by dothebart** [comment]
yes, cpack is used in some cases (windows, macosx, debian/ARM). However it has not been tested or optimized whether it produces proper rpms or .debs for other situations. OBS simply was there first, and the most easiest way to get a reproducible environment with multiple os'es to build on.

As mentioned before, [contributions are welcome](https://www.arangodb.com/community/#contribute).

**Comment by abelyaevskiy** [comment]
Hi! Thanks! We started to think in our team about contributions. We will try to prepare docs for build without open build server.
