### ISSUE TITLE
Graph lists vertices from other graphs as its own

### ISSUE THREAD

**Issue by mikub** [arangodb/arangodb#1418]
Hi,
If there are two graph using the same collection, **all** vertices from that collection are being returned when querying for one graph's vertices regardless what graph they belong to.
This happens in 2.5.5, haven't tested it yet in 2.6.
E.g. 
if there are two graphs capturing two relationship say 
graph 1: `Person -> Person `
graph 2: `Person -> Item`
then even when different vertices are added to each graph via the `save` method, vertices from **both** graphs are returned when I call
`FOR e IN GRAPH_VERTICES(@graph,{})RETURN e`
for **one** of them. I would say this is not expected behavior - only vertices from specified graph should be returned.
Example - see below that when i create two graphs (`myGraph1` and `myGraph2`) that share a collection (`person`) and add a **1** vertex to each graph, when querying for GRAPH_VERTICES for `myGraph1` graph I get **2** vertices returned - even the one that belongs to the other graph:
```javascript
arangosh [_system]> var graph = graph_module._create("myGraph1");
arangosh [_system]> graph._addVertexCollection("person");
arangosh [_system]> graph._extendEdgeDefinitions(graph_module._relation("isFriend", ["person"], ["person"]));
arangosh [_system]> graph.person.save({name:"John", _key:"John"});
{
  "error" : false,
  "_id" : "person/John",
  "_rev" : "153669675299",
  "_key" : "John"
}
arangosh [_system]> graph = graph_module._create("myGraph2");
[ Graph myGraph2 EdgeDefinitions: [ ] VertexCollections: [ ] ]
arangosh [_system]> graph
[ Graph myGraph2 EdgeDefinitions: [ ] VertexCollections: [ ] ]
arangosh [_system]> graph._addVertexCollection("person");
arangosh [_system]> graph._extendEdgeDefinitions(graph_module._relation("isFriend", ["person"], ["person"]));
arangosh [_system]> graph.person.save({name:"Yoko", _key:"Yoko"});
{
  "error" : false,
  "_id" : "person/Yoko",
  "_rev" : "153679571235",
  "_key" : "Yoko"
}
arangosh [_system]> db._query("FOR e IN GRAPH_VERTICES(@graph,{})RETURN e",{"graph":"myGraph1"}).toArray();
[
  {
    "_id" : "person/John",
    "_key" : "John",
    "_rev" : "153669675299",
    "name" : "John"
  },
  {
    "_id" : "person/Yoko",
    "_key" : "Yoko",
    "_rev" : "153679571235",
    "name" : "Yoko"
  }
]
arangosh [_system]>
```

**Comment by mchacki** [comment]
Hi @mikub 
this behavior is intended by our design.
To give you a short overview on the ideas:
In ArangoDB the data is stored in several collections, which might be Document- or Edge-Collections. These collections do not know anything about the graphs you define. Using the general-graph module just adds an additional layer on top of these collections and combines several of them into one graph. You can now use the graph name to access all of these collections at once, still without the Collections knowing anything about it.

Example
```
arangosh [_system]> var graph = graph_module._create("myGraph1");
arangosh [_system]> graph._addVertexCollection("person");
arangosh [_system]> graph._extendEdgeDefinitions(graph_module._relation("isFriend", ["person"], ["person"]));
```

Takes the collections `person` and `isFriend` and defines them as a graph called `myGraph1`. So whatever is stored in these collections will be part of the graph now.

The idea we have in mind is to reuse the same collections (for instance the user-base) in several graphs. This actually includes shared data. And allows to define several let's call it `views` on the dataset defined through the graphs.

What your use case right now is that all graphs should be independent and should have independent collections. This could be achieved by using different collection names for each graph (e.g. prefix them by the graph name). Or create different databases (see https://docs.arangodb.com/Databases/index.html) for each graph.
