### ISSUE TITLE
RETURN REMOVEINTERNAL requested

### ISSUE THREAD

**Issue by kkdd** [arangodb/arangodb#1419]
I hope the introduction of ```RETURN REMOVEINTERNAL``` in AQL:

```
FOR u IN users
  FILTER u.type == "newbie" && u.active == true
  RETURN REMOVEINTERNAL u
```

**Comment by CoDEmanX** [comment]
2nd argument of `ATTRIBUTES()` is `removeInternal`, set it to true to only return user attributes and combine it with `KEEP()`:

```
FOR u IN users
...
RETURN KEEP(u, ATTRIBUTES(doc, True))
```

https://docs.arangodb.com/Aql/DocumentFunctions.html

**Comment by kkdd** [comment]
Thank you for giving me your instruction:```KEEP(u, ATTRIBUTES(u, True))``` for realizing ```REMOVEINTERNAL doc```.

And ```UNSET(u, ['_id', '_key', '_rev'])``` may work well, too.

**Comment by CoDEmanX** [comment]
Note that you'll need to add `'_to'`, `'_from'` and in future possibly more attribute keys to your list if you wanna use `UNSET()`.

**Comment by jsteemann** [comment]
@CoDEmanX :+1:
