### ISSUE TITLE
Foxx validation error response 400 vs 422

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangodb#1420]
Before ArangoDB 2.6, validation errors in the bodyParam used to result in a response of HTTP 422. Now the response is HTTP 400.

Why was that changed?

I prefer 422 because it allows me to show an appropriate error message in my client.

**Comment by pluma** [comment]
Fixed in devel.

**Comment by pluma** [comment]
Context: http://www.restpatterns.org/HTTP_Status_Codes/422_-_Unprocessable_Entity

**Comment by pekeler** [comment]
Thanks!
