### ISSUE TITLE
ArangoDB compiling for --enable-maintainer-mode use flags -g -O2

### ISSUE THREAD

**Issue by abelyaevskiy** [arangodb/arangodb#1421]
Hi!

I configure ArangoDB with command `./configure --enable-relative --enable-maintainer-mode` and see in logs following flags usage `configure: CXXFLAGS: -std=c++11 -g -O2 -std=c++11  -Wall -Winit-self -Wno-long-long -Wno-variadic-macros -Woverloaded-virtual -Wstrict-null-sentinel -pthread ` and `configure: CFLAGS: -std=gnu90 -g -O2  -Wall -Winit-self -Wno-long-long -Wno-variadic-macros -Wshadow -Wstrict-prototypes -Wdeclaration-after-statement -pthread`. 

Could you please clarify following issues
1. Is it ok to use simultaneously flags `-g` and `-O2`?
2. Shoud we remove double usage of `-std=c++11`?

**Comment by jsteemann** [comment]
Re 1:
I think it's ok to use `-g -O2` simultaneously. `-O2` will optimize a few things that will make debugging harder, but at least it is far better than when omitting `-g` completely.
If desired, you can still set your own `CXXFLAGS` and use `-Og` or other optimization levels that provide a better debugging experience. For example:

```
export CFLAGS="-g -Og"
export CXXFLAGS="-g -Og"
./configure --enable-relative --enable-maintainer-mode
make
```

Re 2: 
it's quite common to see such repeated arguments for compiler invocation. Not that it would look nice, but specifying `-std=c++11` multiple times shouldn't do any harm.

**Comment by abelyaevskiy** [comment]
Thanks!
