### ISSUE TITLE
Documentation on mobile devices bogus

### ISSUE THREAD

**Issue by CoDEmanX** [arangodb/arangodb#1422]
Former versions of the docs worked okay on small screens, but the current version has a flaw: the toolbar buttons such as hamburger icon, search etc. do not react to clicks, possibly because they are overlapped by other elements that don't fit on narrow screens. It is barely usable like this on my smartphone.

![img_20150731_004851](https://cloud.githubusercontent.com/assets/1309249/8997161/86748a98-371e-11e5-9a37-cd56c559bfec.jpg)

**Comment by hkernbach** [comment]
Fixed in the current and upcoming versions.

**Comment by CoDEmanX** [comment]
Thank you so much, it works far better than ever before on both desktop and mobile!

There's no search in case of the desktop version however, whereas there's a custom Google search (which kinda fixes the former search problem) on my smartphone in the header next to the ArangoDB logo.

**Comment by hkernbach** [comment]
There is also a search box for the desktop version. You maybe have to delete your cache. If u have installed an ad blocker, this could also be the reason (because its a google based search).

**Comment by CoDEmanX** [comment]
Your right, it was Ghostery that blocked Google AJAX Search API and Google Custom Search, thanks again!
