### ISSUE TITLE
Unicode support in _keys

### ISSUE THREAD

**Issue by damooo** [arangodb/arangodb#14228]
It is unfortunate that arango doesn't support unicode utf8 strings in _keys.
With this restriction alone it creates asymmetry with ascii slugs and unicode slugs, if we decided to use _key as slugs, and entity's primary key. 

It is not possible to use _keys as slugs if we want urls like `wiki/అనుసంధానం`, etc. we have to resolve to custom methods, which feels hacky considering fact that edges have `_from` and `_to` s set to `_id` field, not any custom field.

If performance is the reason to only allow ASCII, There can be explicit opt-in to use utf-8 _keys in collections at the time of collection creation. Considering nice properties of utf-8, which collabarates greatly with sorting, binary-search, random-access, etc.. It may not be that much of a performance overhead with that opt-in.

related #14227

**Comment by dothebart** [comment]
Closing as won't fix. se #14227 for a full detailed explanation.
