### ISSUE TITLE
updated roadmap

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangodb#1423]
After hearing about Meteor and Mesos, I'd be interested in seeing an update to https://www.arangodb.com/roadmap/ to get an idea of the project's priorities for the next few releases.

Or how about replacing that page with a public board on trello.com? One column for 2.7, one for 2.8, and a "future". http://blog.trello.com/going-public-roadmapping-with-a-public-trello-board/

**Comment by CoDEmanX** [comment]
+1, there's only a bunch of ideas for future versions, but nothing concrete for 2.7 yet. Would like to hear about MeteorJS too (#1376).

**Comment by pluma** [comment]
We're evaluating our internal tools at the moment and Trello is definitely on the list. If we embrace Trello for our internal coordination I think moving the roadmap to Trello would be a great next step.

**Comment by kefirchik** [comment]
I would suggest GitHub issues as the source of truth and [Waffle.io](https://waffle.io/arangodb/arangodb) as a board utility to manage them :wink:

**Comment by pekeler** [comment]
@kefirchik Github issues are too low-level.

**Comment by kefirchik** [comment]
@pekeler folks from [reactioncommerce](https://waffle.io/reactioncommerce/reaction) using issues for every kind of stuff, and the board looks very good. I think it's not a problem, issues can be used for anything imho

**Comment by kefirchik** [comment]
Actually I am posting from Waffle, it has nice live search and well integrated with GitHub.

There many kind of roadmaps already created as a git repo and managed this way: [nkola/pothole-hunter-tracker](https://waffle.io/nkola/pothole-hunter-tracker) or [ckan/ideas-and-roadmap](https://waffle.io/ckan/ideas-and-roadmap)

**Comment by dothebart** [comment]
We will retain the current mood of our information policy.
The website will contain a rough roadmap.

If you're interested in details, we will stay in touch via [Google Groups](https://groups.google.com/forum/#!forum/arangodb), weekly newsletter that you can subscribe to via the arangodb.com popup in the lower right; or if you like it realtime via [slack](https://slack.arangodb.com)
