### ISSUE TITLE
Arango shell should not processing arrows pushing on keyboard

### ISSUE THREAD

**Issue by bubnenkoff** [arangodb/arangodb#1424]
When I am working with Arango from shell I often use autocomplete if command like:
db._useDa[Tab] 
 db._useDatabase()

but after command is autocompleted I need to write DB name. So I am pushing arrow on keyboard ("<-")  to move cursor inside brackets. But arango react on it, like I push Enter button, so I am getting error, and need push keyboard arrow (UP) and then move cursor inside brackets.

OS: Windows 7.

**Comment by jsteemann** [comment]
Thanks for the hint. I just submitted a fix for this. Should be included in the next regular release.

**Comment by jsteemann** [comment]
Fixed in 2.6.4.
