### ISSUE TITLE
Foxx: use of extensible schemas with joi

### ISSUE THREAD

**Issue by dariosalvi78** [arangodb/arangodb#1425]
Hi,
I am evaluating if using Foxx is wise idea.
It is certainly interesting, and also the use of joi can make a lot of sense.
Nevertheless, there are scenarios where the data to be posted can be semi-structured (that's mainly why one would choose nosql in first place, right?). I have seen that joi allows extra fields than the ones in the schema, using the "allowUnknown" flag, but I can't find a way to make it work in Foxx.

**Comment by pluma** [comment]
You're right. These aren't supported by Foxx at the moment. I've actually run into this myself.

There doesn't seem to be any way to store these flags on a schema so we'll probably have to bolt them on via `meta` but we've already done that with the other flags. I'll look into adding support for these in the next minor release.

**Comment by pluma** [comment]
The validation now respects the options set using the `.options()` method of the joi schema.

e.g. `joi.object().options({allowUnknown: true})`

**Comment by dariosalvi78** [comment]
thanks !
