### ISSUE TITLE
Foxx Manager CLI should provide usage examples for commands

### ISSUE THREAD

**Issue by pluma** [arangodb/arangodb#1429]
Currently it's not at all obvious what the arguments for certain commands of the Foxx Manager CLI should look like. Ideally every command that takes arguments should at least provide a usage example.

Via #1427.

**Comment by pluma** [comment]
I'll look into this further when I'm in office tomorrow.

Ideally foxx-manager should support a more detailed help command, e.g.:

```sh
$ foxx-manager help set-dependencies
Usage: foxx-manager set-dependencies mountpoint alias1=mountpoint1 alias2=mountpoint2 ...
Some more detailed description goes here.
```

**Comment by pekeler** [comment]
:+1:

**Comment by fceller** [comment]
@pluma has this been solved?

**Comment by pluma** [comment]
@fceller Not that I know of.

**Comment by pluma** [comment]
Closing in favour of https://github.com/arangodb/foxx-cli
