### ISSUE TITLE
Foxx Manager CLI commands should fail if the arguments are malformed

### ISSUE THREAD

**Issue by pluma** [arangodb/arangodb#1430]
Some commands take JSON arguments, some take keyword arguments. It's easy to mix them up and succeed because the invalid arguments are ignored.

We might also want to consider switching to POSIX-style arguments instead (rewrite everything?).

Via #1427.

**Comment by fceller** [comment]
@pluma has this been solved?

**Comment by pluma** [comment]
@fceller Nope.

**Comment by dothebart** [comment]
fixed by 7780b48539718a59bcec00a82788dd9712dfe853

**Comment by dothebart** [comment]
This is done in i.e. scripts/unittest.js (which was also working with a json parameter before) 
```
   if (argv.length >= 3) {
     try {
       if (argv[2].slice(0,1) === '{') {
         options = JSON.parse(argv[2]);
       }
       else {
         options = internal.parseArgv(argv, 2);
       }
     }
     catch (x) {
       print("failed to parse the json options: " + x.message);
       return -1;
     }
   }
   options.jsonReply = true;
```

which maintains backwards compatibility with the json format on parameter#2

**Comment by pluma** [comment]
Possibly related: https://github.com/arangodb/arangodb/issues/1625

**Comment by pluma** [comment]
Closing in favour of https://github.com/arangodb/foxx-cli
