### ISSUE TITLE
scss-lint fixes

### ISSUE THREAD

**Issue by mchacki** [arangodb/arangodb#1433]
Our internal scss-lint tests are failing with many errors. Does not have any effect on functionality but causes tests to report errors.

**Comment by pluma** [comment]
Most of the errors seem to be caused by an outdated or broken implementation of scss in the linter. We should make sure the version the linter uses is close enough to the version we use elsewhere.

**Comment by mchacki** [comment]
I updated the linter to newest version, this throws 970 errors in devel

**Comment by pluma** [comment]
... sweet?

**Comment by hkernbach** [comment]
done.
