### ISSUE TITLE
Graph inserts are slow

### ISSUE THREAD

**Issue by keotic** [arangodb/arangodb#14333]
## My Environment

* __ArangoDB Version__:       3.7.11  docker
* __Storage Engine__:            RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:  Manual Start in Docker (image: arangodb/arangodb)
* __Configuration__:               Docker image default
* __Infrastructure__:              Bare metal
* __Operating System__:        MacOS
* __Total RAM in your machine__:      14Gb for docker 
* __Disks in use__:       SSD
* __Used Package__:    Docker - official Docker library 

Inserting graph edges and nodes via python-arango client seems slow relative to other DB's
Batches of 5000 edges can take up to few seconds to insert (edge has only 1 float property)

Code we use for inserts:
batch_db = db.begin_batch_execution(return_result=False)
graph = batch_db.graph(graph_name)
for edge in edges_payload:
    graph.insert_edge(collection=collection_name, edge=edge, silent=True, sync=False)
batch_db.commit()

Are we doing something wrong or such insert rates are expected?

**Comment by dothebart** [comment]
using the graph API to create graph nodes will validate edges & vertices against the graph definition, and make sure you don't have dangling edges. 
So the graph import in this case does much more than just writing documents. 
If you know your data *is* persistent, you can first create the graph, and then go without these checks and use arangoimport to import vertices and edges (in this sequence)

**Comment by keotic** [comment]
Thanks, we see major speedups by this method
