### ISSUE TITLE
Aardvark: Collection settings toggles broken?

### ISSUE THREAD

**Issue by CoDEmanX** [arangodb/arangodb#1435]
If I'm on the the Collections tab and open the settings, most of the options do not react on clicks or me back to the dashboard, **if I click on the square or circle of the widgets**. Clicking on the text seems to work reliably.

Happens in Firefox as well as Chrome, ArangoDB 2.6.4:

http://youtu.be/DKxaGe0O5G8

**Comment by jsteemann** [comment]
Fixed in 2.6 and devel with @mchacki (thx!)

**Comment by jsteemann** [comment]
Fix will be contained in next 2.6 release.
