### ISSUE TITLE
org/arangodb/request advertises deflate without supporting it

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangodb#1436]
When making a request
```
var request = require('org/arangodb/request');
request.post('http://localhost:4567/fun.json', {
  json: true,
  body: {what: 'ever'},
  headers: {'accept': 'application/json', 'content-type': 'application/json'}
});
```
the http request includes the header `Accept-Encoding: deflate`. Now if the server actually responds with `content-encoding : deflate`, the body doesn't get deflated.

Workaround: overwrite the accept-encoding header in the request
```
var request = require('org/arangodb/request');
request.post('http://localhost:4567/fun.json', {
  json: true,
  body: {what: 'ever'},
  headers: {'accept': 'application/json', 'content-type': 'application/json', 'Accept-Encoding': ''}
});
```

**Comment by pekeler** [comment]
Looking at the source, I'm also confused by https://github.com/arangodb/arangodb/blob/devel/js/common/modules/org/arangodb/request.js#L55 which only continues if the encoding is present, but the following line defaults to UTF-8 if the encoding isn't present.

**Comment by dothebart** [comment]
JSON is UTF-8 by definition - so thats the reason to default to it. Will have a look at the compression.

**Comment by pluma** [comment]
@pekeler Setting the encoding explicitly to null (rather than leaving it as undefined) will return a buffer of binary data. That distinction is intentional to avoid conflicts with actual string encoding names (`"binary"` implies a string of ones and zeros).

**Comment by pluma** [comment]
@jsteemann the request module doesn't add any special handling for deflate so I suspect that this stems from `internal.download`. Could it be that when `returnBodyAsBuffer` is set to `true` the function skips the deflate logic and returns the raw server response?

**Comment by jsteemann** [comment]
The `accept-encoding: deflate` header is added by lib/SimpleHttpClient/SimpleHttpClient.cpp unconditionally. This should be fixed so it becomes optional.

Additionally, I think when the response was deflated but also encoded with chunked encoding, it came back compressed and wasn't inflated properly. That should be fixed by https://github.com/arangodb/arangodb/commit/1d8e373cc49ac8750a35e968655e2fd8d9441a0f.

**Comment by jsteemann** [comment]
Fixed in devel. The request module does not send the header `Accept-Encoding: deflate` automatically anymore, from 2.7 on. If client applications desire to send this header, they can add it manually (but are not forced to use it any longer).
