### ISSUE TITLE
Simple Edge Filtering too slow

### ISSUE THREAD

**Issue by ud803** [arangodb/arangodb#14365]
## My Environment

* __ArangoDB Version__:   3.7.11 Community Edition
* __Storage Engine__:  RocksDB
* __Deployment Mode__:  Single Server
* __Deployment Strategy__:  Manual Service Start
* __Configuration__:  Default
* __Infrastructure__: AWS r4 large (16GB Ram, 2 vCPU)
* __Operating System__:  Ubuntu 18.04
* __Total RAM in your machine__:  16GB
* __Disks in use__:  128 SSD
* __Used Package__: ubuntu apt install

## Component, Query & Data

__Affected feature__:
AQL query using web interface

__AQL query (if applicable)__:
```
LET start_date = 1619830800 //2021-05-01-00
LET end_date = 1620169200 //2021-05-04-23

FOR e IN view_content
    FILTER e.timestamp >= start_date
    AND e.timestamp <= end_date
    
    RETURN e
```

__AQL explain and/or profile (if applicable)__:
Execution plan:
 Id   NodeType        Calls    Items   Runtime [s]   Comment
  1   SingletonNode       1        1       0.00001   * ROOT
  8   IndexNode         475   474139       3.43973     - FOR e IN view_content   /* hash index scan */    
  7   ReturnNode        475   474139       0.05960       - RETURN e

Indexes used:
 By   Name                      Type   Collection     Unique   Sparse   Selectivity   Fields                Ranges
  8   idx_1702518320463347712   hash   view_content   false    false        47.97 %   [ `timestamp` ]   ((e.`timestamp` >= 1619830800) && (e.`timestamp` <= 1620169200))

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   remove-unnecessary-calculations
  3   use-indexes
  4   remove-filter-covered-by-index
  5   remove-unnecessary-calculations-2

Query Statistics:
 Writes Exec   Writes Ign   Scan Full   Scan Index   Filtered   Exec Time [s]
           0            0           0       474139          0         3.50084

Query Profile:
 Query Stage           Duration [s]
 initializing               0.00000
 parsing                    0.00008
 optimizing ast             0.00001
 loading collections        0.00001
 instantiating plan         0.00004
 optimizing plan            0.00025
 executing                  3.50029
 finalizing                 0.00015

__Dataset__:
"view_content" Collection is like below. It consists of about 5 Million documents. 
For above AQL, It's about 470 K documents.
 
{
  "date": "2021-05-01-05",
  "timestamp": 1619812815,
  "referrer": "",
  "location": "http://www.naver.com"
}

hash index on timestamp / selectivity 51% / unique false / sparse false 
persistent on timestamp / selectivity 51% / unique false / sparse false 

__Problem__:
Hi, I'm running a single server arango db, and implementing a simple query.

For edges described above, I want to filter it out by "timestamp" field, which is indexed field.

But simple filtering takes about 3.5 seconds to execute though it's only about 470K documents in the collection.

Can anyone help on performance tuning?

**Comment by dothebart** [comment]
Given the size of your document (they do look all similar?) more RAM is most probably not going to help the situation; does your query benefit from some warmup runs? Will memory usage aproach the available RAM? 

The Query Plan as you posted it will do two database accesses per document: 
- the index lookup
- fetching the actual document

You could probably get rid of the later by using [projections](https://www.arangodb.com/docs/stable/aql/examples-projections-and-filters.html#projections) to attributes which are covered by the index your filter is using;
Hence alter / re-create the index you've currently got on your timestamp to also cover i.e. location, and then build the return document from the projection: 
```
RETURN {
 "timestamp": e.timestamp,
 "location": e.location
}
```

**Comment by ud803** [comment]
Thanks for your reply, dothebart :)
btw,
1) What is warmup run?
2) The instance is running only ArangoDB. So other processes will not interrupt. By default, arango consumes about 40% of memory though it's not consuming any queries. When running the query above, one of vCPU soars to 100%, and memory usage doesn't change at all :( Is it normal?
3) And how does projection impact performance even though the filtering is already done and projection step is done later? Any documents I can refer to?

And for your solution, yes it helped!

changing the query to below improved the performance from 14 secs to 2.3 secs.
 
```
LET start_date = 1619830800 //2021-05-01-00
LET end_date = 1622502000 //2021-05-31-23
FOR e IN view_content
    FILTER e.timestamp >= start_date
    AND e.timestamp <= end_date

    RETURN e.timestamp
```

But actually, my original query was like below. But it doesn't get performance benefit even if I change "COUNT(1)" to "COUNT(e.timestamp") 
 ```
LET start_date = 1619830800 //2021-05-01-00
LET end_date = 1622502000 //2021-05-31-23
FOR e IN view_content
    FILTER e.rtk_timestamp >= start_date
    AND e.rtk_timestamp <= end_date

    COLLECT content_id = e._to
    AGGREGATE cnt = COUNT(1)
    RETURN {
        content_id,
        cnt
    }
```

Is there any suggestions?

**Comment by dothebart** [comment]
"cold" means that the database is freshly started with all data already present on disk. Hence it has no caches filled etc. 
If you do a performance test, you usually want to know the possible values in real life - hence a data set which is actively worked on. 

This is usually called "warmup", and achieved by running some queries so the database has had a look at the documents and indices you plan to work with. 

The indices have the indexed verbatim values from the documents that you index. Hence using the projection of the values instead of the full document results in the value from the index being used instead of the document being loaded from disk / cache. 

So, if you have an Index, that has the values you intend to sort by, plus the most required attribute[s] you intend to query, projections can (at the cost of a little more disk space) save ArangoDB from having to look up your document after the index lookup.


Your latest query may benefit from specifying options: https://www.arangodb.com/docs/stable/aql/operations-collect.html#setting-collect-options

**Comment by ud803** [comment]
Thanks dothebart, 

I'm implementing your solution and have another questions.

```
// Query 1.     --- 32secs
LET start_date = 1619830800 //2021-05-01-00
LET end_date = 1622502000 //2021-05-31-23
FOR e IN view_content // 29secs here. /* persistent index scan, projections: `_to`, `timestamp` */
    FILTER e.timestamp >= start_date
    AND e.timestamp <= end_date
    
    COLLECT content_id = e._to INTO groups
    RETURN {
        content_id,
        a : LENGTH(groups)
    }

// Query 2.     --- 31secs
LET start_date = 1619830800 //2021-05-01-00
LET end_date = 1622502000 //2021-05-31-23
FOR e IN view_content // 29secs here. /* persistent index scan, projections: `_to`, `timestamp` */
    FILTER e.timestamp >= start_date
    AND e.timestamp <= end_date
    
    COLLECT content_id = e._to INTO groups = e.timestamp
    RETURN {
        content_id,
        a : LENGTH(groups)
    }

// Query 3.   --- 31 secs
FOR e IN view_content  // 29secs here. /* persistent index scan, projections: `_to`, `timestamp` */
    FILTER e.timestamp >= start_date
    AND e.timestamp <= end_date
    
    COLLECT content_id = e._to
    AGGREGATE cnt = COUNT(1)
    
    RETURN {
        content_id,
        cnt
    }
```

I have tried several approaches, and have curiosities among the queries.

For query 1, I used the whole 'group' variable, so I'm not getting benefit from using indexes. 

So I tried query 2, which deletes obsolete variables and keeps only the indexed 'timestamp' variable, however it doesn't work. Execution time is the same as query 1. What could be the problem? What am I missing here..?

**Comment by ud803** [comment]
Modifications for my answer, there was a mistake. You can ignore the upper reply. sorry.

I made compound index on ['timestamp', '_to'] and it raised selectivity upto 98%.

Below query with index only on ['timestamp'] succeeded in 17 secs.
And with compound index on ['timestamp', '_to'], it succeeded in 4 secs.
```
// Query 1
LET start_date = 1619830800 //2021-05-01-00
LET end_date = 1622502000 //2021-05-31-23

FOR e IN view_content
    FILTER e.timestamp >= start_date
    AND e.timestamp <= end_date
    
    COLLECT content_id = e._to
    AGGREGATE cnt = COUNT(1)
    
    RETURN {
        content_id,
        cnt
    }
```

But still, with the same compound index, below query succeeded in 17 secs again.
```
//Query 2
LET start_date = 1619830800 //2021-05-01-00
LET end_date = 1622502000 //2021-05-31-23

FOR e IN view_content
    FILTER e.timestamp >= start_date
    AND e.timestamp <= end_date
    
    COLLECT content_id = e._to INTO groups = e.timestamp

    RETURN {
        content_id,
        a : LENGTH(groups)
    }
```

What would be the reason for this difference? Though I got rid of obsolete variables in query 2.

**Comment by dothebart** [comment]
I think you should enable sorting for the collect, since you will have many buckets? (see my link, the options part) 
The Profiling will probably also tell more.

**Comment by ud803** [comment]
Well, the `OPTIONS { method : "sorted" }` resulted in 14 secs.

But still, I could get enormous performance gains through your replies :) 

Really appreciate your help dothebart. Thanks.

I'm closing the issue now.

**Comment by dothebart** [comment]
You're welcome. have fun with ArangoDB.
