### ISSUE TITLE
ARM64 Ubuntu 20.04 Build error: arangodb/3rdParty/V8/v7.9.317/arm64.release/obj.target/../gypfiles/libv8_nosnapshot.a: No such file or directory

### ISSUE THREAD

**Issue by manjo-git** [arangodb/arangodb#14372]
## My Environment

* __ArangoDB Version__:        self-compiled devel branch
* __Operating System__:        Ubuntu 20.04
* __Used Package__:              git clone

## Component, Query & Data

__Problem__:
Compiling the tip of the tree on ARM64 system I get the following error. 

 CXX(target) /home/ubuntu/arangodb/3rdParty/V8/v7.9.317/arm64.release/obj.target/mksnapshot/../v7.9.317/src/snapshot/mksnapshot.o
make[3]: Circular /home/ubuntu/arangodb/3rdParty/V8/v7.9.317/arm64.release/mksnapshot <- /home/ubuntu/arangodb/3rdParty/V8/v7.9.317/arm64.release/obj.target/../gypfiles/libv8_nosnapshot.a dependency dropped.
  LINK(target) /home/ubuntu/arangodb/3rdParty/V8/v7.9.317/arm64.release/mksnapshot
**c++: error: /home/ubuntu/arangodb/3rdParty/V8/v7.9.317/arm64.release/obj.target/../gypfiles/libv8_nosnapshot.a: No such file or directory**
make[3]: *** [../gypfiles/mksnapshot.target.arm64.release.mk:284: /home/ubuntu/arangodb/3rdParty/V8/v7.9.317/arm64.release/mksnapshot] Error 1
make[2]: *** [3rdParty/V8/CMakeFiles/v8_build.dir/build.make:112: 3rdParty/V8/v8_build-prefix/src/v8_build-stamp/v8_build-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:1420: 3rdParty/V8/CMakeFiles/v8_build.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

**Comment by Simran-B** [comment]
Closing as duplicate. See above link and also #12555 and #13559.
