### ISSUE TITLE
org/arangodb/request should process body regardless of status

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangodb#1437]
Currently, the response's body is only returned if the status is 2xx. I think the body should be returned no matter what the status is.

I need to call an api which can return status 500 and then has a more detailed error message in the body. Using org/arangodb/request I have no idea what the reason for the 500 is. When using https://github.com/request/request with node.js, I get access to the body (and found out that the reason for the 500 was an invalid api key).

**Comment by pekeler** [comment]
I see that `internal.download()` at https://github.com/arangodb/arangodb/blob/devel/lib/V8/v8-utils.cpp#L583 already supports `returnBodyOnError` as an option. So wouldn't we just have to expose this option through request() by adding
```javascript
  if (is.existy(req.returnBodyOnError)) {
    options.returnBodyOnError = req.returnBodyOnError;
  }
```
before https://github.com/arangodb/arangodb/blob/devel/js/common/modules/org/arangodb/request.js#L160

**Comment by fceller** [comment]
@pluma has this been fixed in 2.7?

**Comment by pluma** [comment]
This change will land in 2.8 as it makes sense to change the default behaviour rather than simply expose the option.

**Comment by pekeler** [comment]
Thanks
