### ISSUE TITLE
Domain name setup for DB

### ISSUE THREAD

**Issue by avinash1422** [arangodb/arangodb#14388]
## My Environment

* __ArangoDB Version__:     3.7.3

React Native.

When i am trying with Domain name (https://{testsite.me}:8529/
API getting failed. but when i try with ip address it's working
We are using React native(Mobile app) & arangodb foxx framework for API
how to use domain instead of IP

for web application it is working with domain name, but mobile app it's not working with domain but works with ip address.

can you please suggest.

**Comment by dothebart** [comment]
Hi, 
if you only just configured the DNS, you may see that it takes some time for the information to spread.
Its also sometimes that mobile providers do special things like proxies etc. for their networks. 
In general I'd advise that its a good idea to use foxx services via http forwarding in the webserver under the matching locations.

**Comment by dothebart** [comment]
closing as solved.
