### ISSUE TITLE
Feature Request: Allow for raw JSON logging to log.output

### ISSUE THREAD

**Issue by Calrain** [arangodb/arangodb#14396]
## My Environment

* __ArangoDB Version__:        3.7.10
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start in Docker and Kubernetes

__Problem__:
When running ArangoDB, it is sometimes necessary to have an external log aggregator (such as GCP Logging services) to ingest log data from the container ArangoDB is running in, parse that log data, and then present it for further use in dashboards / consumers.

When automatically importing log data into an external log aggregator, it's preferable to export the data in JSON format, as that makes the data richer and more valuable in the logging engine.

Some logging tools (such as GCP Logging services) will look at the output from the container, and if it can parse to JSON, it will take it as JSON output, but if it cannot, it ingests it as plain text.

If plain text, this means it becomes more difficult to extract valuable information from the log, as it has to be REGEX'ed or manually modified to become JSON data through third party proceses.

### Key use case
The key use of this in my work is that I have Foxx jobs running on polled intervals, and they are processing data from queues.

To log and report on the depth of jobs in each queue, and performance statistics etc, it's necessary to log detailed data out that a log parser will pick up and then render to a third party dashboard.

Being able to display complex JSON objects, and not have to implement manual log formatting would make it much easier to integrate third party log aggregators.

I'm sure there are other ways to solve this, I just put down below two possible strawman ways to do it.

__Expected result__:
I would like to have the ability render log data in JSON format, rather than the text format that it is now.

For example:
If in Foxx I run this command:
```
let logData = {
  foo: "bar",
  counter: 1,
  check: true,
}
console.log(logData);
```

Then I receive this log output:
`2021-06-24T02:11:02Z [1] INFO [99d80] {"foo":"bar","counter":1,"check":true}`

When a log parser reads the above line, it does not parse to JSON so it imports it as raw text.

### Possible solution 1
One solution is to set a daemon level setting that modifies all log output.

For example, add `--log.format` as an arangod option with the options of `text` and `json` where the `text` option operates as is (and is the default value), but the `json` format just wraps the line in JSON.

An example of `console.log` output while the `--log.format` is in `json` format could be:
```
let logData = {
  foo: "bar",
  counter: 1,
  check: true,
}
console.log(logData);
```
`{"time":"2021-06-24T02:11:02Z", "topic": 1, "level": "INFO", "pid": "99d80", "output": {"foo":"bar","counter":1,"check":true}}`

### Possible solution 2
Another option is to add the ability to log as JSON in the Console Module, something like:
`console.json(myObject)`
...and this automatically formats the full log output line in JSON.

An example of using something like `console.json` could be:
```
let logData = {
  foo: "bar",
  counter: 1,
  check: true,
}
console.json(logData);
```
`{"time":"2021-06-24T02:11:02Z", "topic": 1, "level": "INFO", "pid": "99d80", "output": {"foo":"bar","counter":1,"check":true}}"`

The key is that the log line ends up being a full JSON object, and can be directly parsed.

Thanks for considering!

**Comment by dothebart** [comment]
hi, 
did you already have a look at [the 3.8 changelog](https://www.arangodb.com/docs/3.8/release-notes-new-features38.html#logging) - how does that line up to your expectations?

**Comment by Calrain** [comment]
Oh, that looks great, I wasn't aware of it.

This means the whole line is valid json, without any prefix/suffix data that would affect automatic parsing?

If so, then I'll wait for 3.8 to release.

Thanks

**Comment by Simran-B** [comment]
Yes, the whole log line will be a JSON object like this (I enabled some extra log options here):

`{"time":"2021-06-24T10:16:05Z","prefix":"$>","pid":303,"tid":0,"thread":"main","role":"S","level":"INFO","file":"BootstrapFeature.cpp","line":381,"function":"start","topic":"general","id":"cf3f4","hostname":"--log.request-parameters","message":"ArangoDB (version 3.9.0-devel enterprise [linux]) is ready for business. Have fun!"}`

**Comment by Calrain** [comment]
Fantastic, that's perfect, thanks so much.

Do you have a best guess date when 3.8 is released?

Great work!

**Comment by Simran-B** [comment]
There is no exact date, but it's going to be very soon.
