### ISSUE TITLE
Building issues on Windows (V8, Python 3.x and others)

### ISSUE THREAD

**Issue by CoDEmanX** [arangodb/arangodb#1440]
Quoting a recipe from the cookbook:

> Either version 2.x or 3.x (excluding 3.4) should work - it's used to run V8s GYP. Make sure you add python.exe to your path environment variable; Restarting your running shell may be necessary.

I'm not sure why 3.4 is excluded, but 3.x in general supposed to work. It seems that if 3.x is installed and added to PATH environment variable, V8 compilation fails because of a syntax error:

    import sys; print sys.byteorder

`print` is a function in Python 3 and requires parentheses.

Is there a way to make gyp use `ArangoDB\3rdParty\V8-4.3.61\third_party\python_26\python.exe` instead of a local Python installation?

**Comment by dothebart** [comment]
you have to adjust your PATH environment so it first fetches that.

**Comment by CoDEmanX** [comment]
Yeah, that's what I did, but now `python` in cmd will start a 2.x Python - I'm working with 3.x myself however. Could the path var be temporarily overwritten by the make script to fetch the included 2.6 Python automatically?

There cookbook recipe should be corrected accordingly (either remove the part about 3.x being supported, or remove Python as dependency entirely if the build scripts are modified to use the included Python binary).

**Comment by dothebart** [comment]
v8-build.bat already does: 


echo %CMD%

cd V8-%V8_VERSION%

.\third_party\python_26\python.exe build\gyp_v8 %CMD%

cd build

so if you follow the cookbook, ( https://docs.arangodb.com/cookbook/CompilingUnderWindows.html ) and ran make -f Makefile.v8-windows ?

**Comment by CoDEmanX** [comment]
I tried `make -f Makefile.v8-windows` but it failed. Possibly file permission issue: https://github.com/arangodb/arangodb-windows-libraries/issues/1. I'm not sure if it would had worked after `takeown` and `icacls`, but I compiled the solution in Visual Studio.

I think the problem is that the initial call to gyp is done using the bundled python, but if gyp itself tries to create subprocesses, it probably picks the Python found in `%PATH%`. This should be fixable by changing the environment variable temporarily:

    set PATH=.\third_party\python_26\;%PATH%

The Python path must come first to take precedence.

**Comment by dothebart** [comment]
can you revalidate whether this fixes your problem?

**Comment by CoDEmanX** [comment]
I changed `v8-build.bat` to look like:

    cd V8-%V8_VERSION%

    set PATH=%~dp0V8-%V8_VERSION%\third_party\python_26;%PATH%

    .\third_party\python_26\python.exe build\gyp_v8 %CMD%

If no Python is in `%PATH%`, the command `python` fails. If a 3.x Python is in `%PATH%`, a SyntaxError is raised. Both errors disappear if `PATH` is modified like shown above.

These are the erros I'm still getting for `make -f Makefile.v8-windows` in cygwin bash:
```
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu erm”glichen, mssen Sie den Schalter "/m" hinzufgen.
Der Buildvorgang wurde am 17.08.2015 17:27:23 gestartet.
Projekt "D:\Projekte\ArangoDB\3rdParty\V8-4.3.61\build\All.sln" auf Knoten "1", v8 Ziel(e).
ValidateSolutionConfiguration:
  Die Projektmappenkonfiguration "Debug|x64" wird erstellt.
D:\Projekte\ArangoDB\3rdParty\V8-4.3.61\build\All.sln.metaproj : error MSB4057: Das Ziel "v8" ist im Projekt nicht vorhanden. [D:\Projekte\ArangoDB\3rdParty\V8-4.3.61\build\All.sln]
Die Erstellung des Projekts "D:\Projekte\ArangoDB\3rdParty\V8-4.3.61\build\All.sln" ist abgeschlossen, v8 Ziel(e) -- FEHLER.

Fehler beim Buildvorgang.

"D:\Projekte\ArangoDB\3rdParty\V8-4.3.61\build\All.sln" (v8 Ziel) (1) ->
  D:\Projekte\ArangoDB\3rdParty\V8-4.3.61\build\All.sln.metaproj : error MSB4057: Das Ziel "v8" ist im Projekt nicht vorhanden. [D:\Projekte\ArangoDB\3rdParty\V8-4.3.61\build\All.sln]

    0 Warnung(en)
    1 Fehler

Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu erm”glichen, mssen Sie den Schalter "/m" hinzufgen.
Der Buildvorgang wurde am 17.08.2015 17:27:23 gestartet.
Projekt "D:\Projekte\ArangoDB\3rdParty\V8-4.3.61\build\All.sln" auf Knoten "1", v8_libbase Ziel(e).
ValidateSolutionConfiguration:
  Die Projektmappenkonfiguration "Debug|x64" wird erstellt.
D:\Projekte\ArangoDB\3rdParty\V8-4.3.61\build\All.sln.metaproj : error MSB4057: Das Ziel "v8_libbase" ist im Projekt nicht vorhanden. [D:\Projekte\ArangoDB\3rdParty\V8-4.3.61\build\All.sln]
Die Erstellung des Projekts "D:\Projekte\ArangoDB\3rdParty\V8-4.3.61\build\All.sln" ist abgeschlossen, v8_libbase Ziel(e) -- FEHLER.

Fehler beim Buildvorgang.

"D:\Projekte\ArangoDB\3rdParty\V8-4.3.61\build\All.sln" (v8_libbase Ziel) (1) ->
  D:\Projekte\ArangoDB\3rdParty\V8-4.3.61\build\All.sln.metaproj : error MSB4057: Das Ziel "v8_libbase" ist im Projekt nicht vorhanden. [D:\Projekte\ArangoDB\3rdParty\V8-4.3.61\build\All.sln]

    0 Warnung(en)
    1 Fehler

Verstrichene Zeit 00:00:00.05
Microsoft (R)-Buildmodul, Version 12.0.30110.0
[Microsoft .NET Framework, Version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu erm”glichen, mssen Sie den Schalter "/m" hinzufgen.
Der Buildvorgang wurde am 17.08.2015 17:27:23 gestartet.
Projekt "D:\Projekte\ArangoDB\3rdParty\V8-4.3.61\build\All.sln" auf Knoten "1", v8_libplatform Ziel(e).
ValidateSolutionConfiguration:
  Die Projektmappenkonfiguration "Debug|x64" wird erstellt.
D:\Projekte\ArangoDB\3rdParty\V8-4.3.61\build\All.sln.metaproj : error MSB4057: Das Ziel "v8_libplatform" ist im Projekt nicht vorhanden. [D:\Projekte\ArangoDB\3rdParty\V8-4.3.61\build\All.sln]
Die Erstellung des Projekts "D:\Projekte\ArangoDB\3rdParty\V8-4.3.61\build\All.sln" ist abgeschlossen, v8_libplatform Ziel(e) -- FEHLER.

Fehler beim Buildvorgang.

"D:\Projekte\ArangoDB\3rdParty\V8-4.3.61\build\All.sln" (v8_libplatform Ziel) (1) ->
  D:\Projekte\ArangoDB\3rdParty\V8-4.3.61\build\All.sln.metaproj : error MSB4057: Das Ziel "v8_libplatform" ist im Projekt nicht vorhanden. [D:\Projekte\ArangoDB\3rdParty\V8-4.3.61\build\All.sln]

    0 Warnung(en)
    1 Fehler
```

Several messages are printed to stderr about files not found by the system, full log:
http://pastebin.com/0iHQwwJ7 (look for "Das System kann die angegebene Datei nicht finden.")

The subsequent `make -f Makefile.v8-windows install` fails cause of permission denied again (it seems the compilation scripts set weird permissions on files). Admin shell does not solve the issue, I need to reset file permissions for the entire V8 build folder (as admin):

    takeown /F V8-4.3.61/build /R
    icacls V8-4.3.61\build\ /T /C /Q /reset

After that, the following copy command fails:

    cp -a V8-4.3.61/build/Debug32/lib/*.lib ../WindowsLibraries/32/lib/Debug
    cp: der Aufruf von stat für "V8-4.3.61/build/Debug32/lib/*.lib" ist nicht möglich: No such file or directory
    Makefile.v8-windows:40: recipe for target 'install_bits' failed

It's simply looking for the wrong directory, the 32bit libs are in `build/Debug/` (or another part of the script forgot to add the bitness to the path). The release libs are in `Release32` and `Release64` however. I think it's the missing `%SUFFIX%` for 32bit builds:

    build32:
    	./v8-build.bat x86 ia32 Win32 32

I think there should be an additional `32` for all 32 bit targets:

```
build64:
	./v8-build.bat x86_amd64 x64 x64 64 

build32:
	./v8-build.bat x86 ia32 Win32 32 32


clean: clean32 clean64

clean64:
	./v8-clean.bat cmd x86_amd64 x64 x64 64

clean32:
	./v8-clean.bat x86 ia32 Win32 32 32


distclean: distclean32 distclean64

distclean64:
	./v8-distclean.bat x86_amd64 x64 x64 64

distclean32:
	./v8-distclean.bat x86 ia32 Win32 32 32
```

**Comment by CoDEmanX** [comment]
`Makefile.v8-windows` misses to create `RelWithDebInfo` directory, it should look like this:
```
install_bits:
	mkdir -p ../WindowsLibraries/$(BITS)/lib
	mkdir -p ../WindowsLibraries/$(BITS)/lib/RelWithDebInfo
```

`make pack-win*` copies `icudt54l.dat` to `ArangoDB\share\arangodb`, where `arangod.exe` expects it. The cookbook recipe is wrong about the name (`icudt52l.dat`) and the place (next to executable), the server will not start if you do so. I can't find that file in official 2.6.4 btw., do you compile it into the binaries?

If you have admin privileges, you don't need to copy WindowsBinaries, just create a symlink:

    ArangoDB>mklink /D WindowsBinaries ..\arangodb-windows-libraries\WindowsBinaries

The file permission issues drive me crazy still, dunno if the cygwin environment itself causes this... Or is this the root of all evil?

    find ../WindowsLibraries -type f -exec chmod a+r {} \;
    find ../WindowsLibraries -type d -exec chmod a+rx {} \; 

Still no clue why v8* doesn't build via msbuild command, the projects DO exist in solution file and build fine in VS. Couldn't find anything useful on the web. `msbuild v8_libbase.vcxproj ...` without specifying a project sort of works, not sure if it builds the same stuff twice however (or just dependencies?).

**Comment by CoDEmanX** [comment]
Another issue: the build scripts seem to copy some import js files to `\share\arangodb\js\js`, instead of `\share\arangodb\js`. This will make server init fail.

**Comment by dothebart** [comment]
We had permission problems since we run jenkins and the build job via ssh. You get sort of `mostly` the same user (but not its admin privileges) as if you log in via the GUI-shell. Lets hope that after it took Microsoft 30 years to find out telnet/ssh acess to a wintendo could be a usefull thing these problems are solved for us sooner or later.

However, if you run cygwin as the same user as you currently are, the chmod shouldn't do anything problematic for you.

v8-build.bat only accepts 4 parameters. i've added some indention to make it more readable. Parameter #4 becomes SUFFIX.

The arangodb sln's are completely disjunct to the V8 ones, they simply expect to find the library dependencies in the WindowsLibraries folder - therefore the arango vsd can't build it (as it complains)

Do you still use 32bit windows?

**Comment by CoDEmanX** [comment]
> However, if you run cygwin as the same user as you currently are, the chmod shouldn't do anything problematic for you.

I removed both repos, added `filemode = false` to core section of git config and checked out both again, then tried to build from scratch. The same permission issues occur, although I'm running everything with my user account (unless cygwin uses a different?! Not sure how to check /change it).

I was able to continue v8 building by resetting permissions, but annoyingly, the final `make pack-win64` failed regardless of permission resets, and also if I start cygwin from an admin she'll... (It fails at copying the js folder)

> v8-build.bat only accepts 4 parameters

True, must have been a problem related to another issue that led to an unrenamed Release folder. 

> The arangodb sln's are completely disjunct to the V8 ones, they simply expect to find the library dependencies in the WindowsLibraries folder - therefore the arango vsd can't build it (as it complains)

Okay, I don't really understand what you mean. Can you show me how the msbuild command should look like to build v8_*.libs? Or do I need another symlink?

The error confuses me because i can see the v8 projects in the solution and it builds in VS, but not in console (`msbuild solutionFile /t:v8_lib ...`)

Windows 64 only for sure.

**Comment by dothebart** [comment]
the Arangodb solution files only know about that the v8-files have to exist.
They don't know how to invoke the V8-solution files:

    jenkins@meschenich /cygdrive/c/b/workspace/CONTINUOUS_BUILD__DEVEL__Windows_VisualStudio_cmake
    $ find WindowsLibraries/ |grep v8
    ...
    WindowsLibraries/64/include/v8-debug.h
    WindowsLibraries/64/include/v8-platform.h
    WindowsLibraries/64/include/v8-profiler.h
    WindowsLibraries/64/include/v8-testing.h
    WindowsLibraries/64/include/v8-util.h
    WindowsLibraries/64/include/v8-version.h
    WindowsLibraries/64/include/v8.h
    WindowsLibraries/64/include/v8config.h
    WindowsLibraries/64/lib/Debug/v8_base.lib
    WindowsLibraries/64/lib/Debug/v8_base.pdb
    WindowsLibraries/64/lib/Debug/v8_libbase.lib
    WindowsLibraries/64/lib/Debug/v8_libbase.pdb
    WindowsLibraries/64/lib/Debug/v8_libplatform.lib
    WindowsLibraries/64/lib/Debug/v8_libplatform.pdb
    WindowsLibraries/64/lib/Debug/v8_nosnapshot.lib
    WindowsLibraries/64/lib/Debug/v8_nosnapshot.pdb
    WindowsLibraries/64/lib/RelWithDebInfo/v8_base.lib
    WindowsLibraries/64/lib/RelWithDebInfo/v8_base.pdb
    WindowsLibraries/64/lib/RelWithDebInfo/v8_libbase.lib
    WindowsLibraries/64/lib/RelWithDebInfo/v8_libbase.pdb
    WindowsLibraries/64/lib/RelWithDebInfo/v8_libplatform.lib
    WindowsLibraries/64/lib/RelWithDebInfo/v8_libplatform.pdb
    WindowsLibraries/64/lib/RelWithDebInfo/v8_nosnapshot.lib
    WindowsLibraries/64/lib/RelWithDebInfo/v8_nosnapshot.pdb

**Comment by CoDEmanX** [comment]
But `msbuild` is invoked by `v8-build.bat`, and the solution file is `arangodb\3rdParty\V8-4.3.61\build\all.sln`?!

```
msbuild All.sln /t:v8 /p:Configuration=Debug /p:Platform=%MSPLATFORM%
msbuild All.sln /t:v8_libbase /p:Configuration=Debug /p:Platform=%MSPLATFORM%
msbuild All.sln /t:v8_libplatform /p:Configuration=Debug /p:Platform=%MSPLATFORM%
```

I also tried `msbuild` manually on cmd for `arangodb\3rdParty\V8-4.3.61\tools\gyp\v8.sln`, but same problem. It does not recognize any of the v8 targets/projects.

Do you use different build scripts internally? What is your cmake version?

**Comment by CoDEmanX** [comment]
Regarding premissions: I added `chmod` to `file-copy-js.sh` and it seems to fix permissions for the final `make pack-win64`:

     chmod a+r "${FROM}"
     test -d "${DIR}" || mkdir -p "${DIR}"

Permissions shouldn't be set/changed in the first place still.

All 4 windows sh scripts require Unix-style line endings, or they will raise syntax errors.

Any idea why it copies some js to the wrong folder?

**Comment by dothebart** [comment]
do I get you right, that the copy will fail on your system, if the .js file isn't chmodd'ed before?

**Comment by CoDEmanX** [comment]
Yeah, the packing task fails because it can't access certain files and `js\actions\api-aqlfunction.js` happens to be the first. I added chmod to the sh script to fix permissions, so that they become accessible again and can be copied. But then, some end up in the wrong path.

I might have a found a solution to the permission issue, will need to do a clean build however. In cygwin's `etc\fstab`, it's possible to set option `noacl`, which should prevent it from creating a new permission set for every new file, and give default permissions instead.

Hm, is it possible to change language to English? Sometimes that might be helpful. Note that I use a Dreamspark version. IIRC I had the choice between an English and a German ISO, so one possibly lacks the other language...

**Comment by CoDEmanX** [comment]
Okay so here's a fix that should resolve the v8 build issues:
https://dl.dropboxusercontent.com/u/39101475/BugReports/gyp_build_fix.diff

It forces gyp to create flat solutions, which will make `msbuild /t:v8*` work with VS 2013 Ultimate (and possibly other versions too).

`.gitattributes` is supposed to prevent git from changing line endings on Windows from LF to CRLF. It breaks .sh scripts.

Sorry for not making this a PR, but git hates me. I tried to pull from origin, but it created lots of merge conflicts I was unable to resolve (didn't even touch those files).

**Comment by CoDEmanX** [comment]
So, I finally figured out the `js/js` problem. Turns out, the [fix for js file packing](https://github.com/arangodb/arangodb/commit/fdbe6abf528d9a88a37babca4544f5cce9c66b32) was actually broken. See my PR, *Fix target path for js files*:

https://github.com/arangodb/arangodb/pull/1448/commits

I believe that sorts out all my build problems. I'll do another clean build for both 32 and 64 bits and see if it works out.

**Comment by dothebart** [comment]
Ok, thanks. merged. closing.
