### ISSUE TITLE
How is the internal state of arangodb obtained, based on /_admin/metrics？

### ISSUE THREAD

**Issue by lliony** [arangodb/arangodb#14403]
## My Environment

* __ArangoDB Version__:        
* __Storage Engine__:             
* __Deployment Mode__:       
* __Deployment Strategy__:   
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:        
* __Total RAM in your machine__:        
* __Disks in use__:        
* __Used Package__:              

## Component, Query & Data

__Affected feature__:

__AQL query (if applicable)__:
```


```
__AQL explain and/or profile (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. 
2. 
3. 

__Problem__:

__Expected result__:

**Comment by dothebart** [comment]
Its a mix: 
 - accessing `/proc` (or the windows counterport)
 - polling internal counters
 - polling rocksdb counters

**Comment by lliony** [comment]
> Its a mix:
> 
> * accessing `/proc` (or the windows counterport)
> * polling internal counters
> * polling rocksdb counters

I can't find this information in the official documentation for version 3.7

**Comment by dothebart** [comment]
The implementation and the documentation has been reworked for 3.8 to be much more extensive.
However, I don't think the data source of the gauge is documented, since nobody has asked for this so far.
