### ISSUE TITLE
Arangodump overwrites collections when they have the same name but different capitalization

### ISSUE THREAD

**Issue by ropeladder** [arangodb/arangodb#1441]
When I try to backup database using arangodump in Windows and I have two collections that have the same name with different capitalizations (e.g. "MyCollection" and "mycollection"), the backup will overwrite one collection with the other.

Presumably this is caused by the Windows filesystem being case agnostic.

**Comment by CoDEmanX** [comment]
Probably, which is a big minus in this case... Maybe some kind of hash could be added as suffix?
"MyCollection_7ced93ab" and "mycollection_d3d726f5"

**Comment by dothebart** [comment]
yes, regular windows filesystems ignore capitalisation. do you use fat? or ntfs?

**Comment by ropeladder** [comment]
I'm using NTFS.

**Comment by dothebart** [comment]
fixed with 86496bb0fdb8a0cbf967623d3897dbf197cc2eb5 - will be available with the next major release.

**Comment by jsteemann** [comment]
Fixed in devel.
