### ISSUE TITLE
Object literal simplificatin does not support pseudo-variables NEW and OLD

### ISSUE THREAD

**Issue by CoDEmanX** [arangodb/arangodb#1445]
Tested the [new abbreviated syntax](https://www.arangodb.com/2015/07/aql-object-literal-simplification/) in 2.7.0-devel and realized that `NEW` and `OLD` are not supported:

    UPDATE doc WITH {foo: "bar"} IN coll
    RETURN {OLD, NEW}

> unknown variable 'use of unknown variable 'OLD' in object literal near ', NEW }' at position 1:166' (while parsing)

Workaround:

    LET OLD = OLD
    LET NEW = NEW
    RETURN {OLD, NEW}

**Comment by jsteemann** [comment]
fixed in devel.
