### ISSUE TITLE
arangosh fails when provided with complex passwords in --server.password argument.

### ISSUE THREAD

**Issue by AtomicNicos** [arangodb/arangodb#14457]
## My Environment

* __ArangoDB Version__:  3.7.12
* __Storage Engine__: RocksDB
* __Deployment Mode__: Single Server
* __Deployment Strategy__:   Manual Start in Docker (docker-compose)
* __Configuration__: N/A
* __Infrastructure__: localhost
* __Operating System__: Windows 10 / Docker
* __Total RAM in your machine__:     64Gb
* __Disks in use__: 1TB nvme, .5 Tb SSD, 2 * 2 Tb HDD, 1 * 2 Tb SSD
* __Used Package__: arangodb:latest on Docker

## Component, Query & Data

__Affected feature__: arangosh

__AQL query (if applicable)__: N/A
__AQL explain and/or profile (if applicable)__: N/A
__Dataset__: N/A
__Size of your Dataset on disk__: N/A
__Replication Factor & Number of Shards (Cluster only)__: N/A

## Steps to reproduce

1. Create persistence machine: `docker run -d --name problem-arangodb-persistence -v /data tianon/true`
2. Create persistence machine: `docker run -d --name witness-arangodb-persistence -v /data tianon/true`
3. Create arango image: `docker run -e ARANGO_ROOT_PASSWORD=".ca8)+QR=i*c-]eM4g^:9A#y8z~t.@^@" --name problem-arangodb -p 8529:8529 --volumes-from problem-arangodb-persistence -d arangodb`
4. Create witness arango image: `docker run -e ARANGO_ROOT_PASSWORD="testtest" --name witness-arangodb -p 8530:8529 --volumes-from witness-arangodb-persistence -d arangodb`

5. On `problem-arangodb`: Run `arangosh --server.username root --server.password ".ca8)+QR=i*c-]eM4g^:9A#y8z~t.@^@"`
6. On `witness-arangodb`: Run `arangosh --server.username root --server.password "testtest"`

__Problem__:
On `problem-arangodb`: 
```
Command-line history will be persisted when the shell is exited. You can use `--console.history false` to turn this off
Could not connect to endpoint 'tcp://127.0.0.1:8529', database: '_system', username: 'root'
Error message: 'not authorized to execute this request'
```
![image](https://user-images.githubusercontent.com/18284503/124401100-e4fa3d00-dd27-11eb-9407-ea4a7ffa43e7.png)

On `witness-arangodb`:
```
Command-line history will be persisted when the shell is exited. You can use `--console.history false` to turn this off
Connected to ArangoDB 'http+tcp://127.0.0.1:8529, version: 3.7.12 [SINGLE, server], database: '_system', username: 'root'
```
![image](https://user-images.githubusercontent.com/18284503/124401177-20950700-dd28-11eb-9929-c3ab1919f1b8.png)

*Apparently arangosh cannot handle complicated passwords with symbols*

__Expected result__:
`problem-arangodb` would behave like `witness-arangodb`.

**Comment by dothebart** [comment]
the password can be reduced to `.@^` to reproduce this issue.

**Comment by dothebart** [comment]
hm, its not a bug, its a feature:
```
# ./bin/arangosh --log.hostname 'a@abc@' --javascript.execute-string "print(require('internal').options()['log.hostname'])"
a
# abc=123 ./bin/arangosh --log.hostname 'a@abc@' --javascript.execute-string "print(require('internal').options()['log.hostname'])"
a123
```
whether this makes sense in passwords could be questioned.

**Comment by dothebart** [comment]
we however do have two issues here which will be worked on with BTS-515 : 

- only  [A-Za-z_0-9] must be allowed between @'s, else an exception should be thrown
- one should be able to escape @'s by using double-@@. 

@AtomicNicos you probably now know how to work around your issue using the `PASSWORD` environment variable? (see last post)

**Comment by AtomicNicos** [comment]
I get why it happens, but for a password field that makes no sense in the context of arg parsing. Is this a "feature" of the C++ arg parser? 

Because otherwise instead of making the symbols not allowed in general and requiring an escape rule, you could just take the password string as it is without throwing it through a parser.

Let's be honest, if we wanted to use an environment variable we could just use it the normal way we use env variables (ie. `$abc`)

**Comment by Simran-B** [comment]
Every startup option supports substitution using the `@var@` syntax. This is not limited to startup options you supply via command-line arguments, but also works in configuration files.

Another possible reason for this feature is to have a consistent way across OSes and terminals to interpolate environment variable values. On Windows it's `%var%` in cmd.exe, but `$Env:var` in PowerShell for instance.

By the way: `arangosh --server.username root --server.password ".ca8)+QR=i*c-]eM4g^:9A#y8z~t.@@^@@"` (with at signs doubled) should already work in current versions of ArangoDB.

**Comment by AtomicNicos** [comment]
Warning issued in docs, closing issue.
