### ISSUE TITLE
Question: is it possible to get Graphs / Collections creation timestamps

### ISSUE THREAD

**Issue by keotic** [arangodb/arangodb#14482]
General question regardless of the DB version.
We want to know how 'old' is a graph / collection, even if it is empty.
Is there a record of the creation time somewhere? didn't find it on the collections / graphs properties

**Comment by Simran-B** [comment]
This metadata is not tracked. Audit logs from an Enterprise Edition could answer your question, but I suppose you don't have such logs.

If there is at least one document in the respective collection, you can get the document with the lowest timestamp in its revision for a minimum age of the collection:

```js
FOR doc IN coll
  SORT doc._rev
  LIMIT 1
  RETURN DECODE_REV(doc._rev).date
```

**Comment by keotic** [comment]
@Simran-B Thanks, getting the date of rev will do
