### ISSUE TITLE
Aardvark 2.7: UI suggestions

### ISSUE THREAD

**Issue by CoDEmanX** [arangodb/arangodb#1449]
I had the chance to have a look at the new Aardvark 2.7x design and want to give some feedback. The new, lighter look makes it feel unfamiliar, but I think I like it :+1: 

1. The red for query errors seems to a bit too intense, it should look more like the Clear button.
2. The query error messages aren't readable unless hovered, the color needs to be changed to some darker tone.

    ![aardvark1](https://cloud.githubusercontent.com/assets/1309249/9373783/95798b9e-46ee-11e5-9682-ca1def2bc11c.png)
3. Feature request: query errors should be clickable and either transfer you to a reference page, or display the meaning of the error code somehow inline (tooltip, popup, ?)
4. The colorful, original ArangoDB logo is now in the top left corner, but where did the name go?<br>
    [The text should be included][1].
5. Radio buttons and checkboxes are merely merely distinguishable, I prefer square checkboxes to clearly communicate the different behavior compared to radio buttons.

    ![aardvark2](https://cloud.githubusercontent.com/assets/1309249/9373784/957a3c6a-46ee-11e5-8f5d-d3f91693fef4.png)

Great job at PPP™ by the way! (Pong Progress Popup)

[1]: https://www.arangodb.com/wp-content/themes/arangodb-wp-theme/images/logos/arangodb_logo2.png

**Comment by hkernbach** [comment]
Thank you for your feedback.

1. The red color is now smoother. 
2. Query messages are now readable. 
3. If detailed error information is available, a tooltip icon will be rendered.
4. We've changed the logo to a smaller one in order to save room. 
5. Checkboxes are now displayed as squares.
