### ISSUE TITLE
Contains type search with LIKE function for special characters(@) using text_en analyzer

### ISSUE THREAD

**Issue by PriyavKaneria** [arangodb/arangodb#14506]
## My Environment

* __ArangoDB Version__:        3.7.12
* __Storage Engine__:             
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:        Windows 10
* __Total RAM in your machine__:        8 GB
* __Disks in use__:        
* __Used Package__:              

## Component, Query & Data

__Affected feature__:
Searching for emails with special characters like @

__AQL query (if applicable)__:
```
Working - FOR doc IN profile_view SEARCH ANALYZER(doc.email LIKE "%gmail%", "text_en") RETURN doc
Not Working - FOR doc IN profile_view SEARCH ANALYZER(doc.email LIKE "%_gmail%", "text_en") RETURN doc

```
__AQL explain and/or profile (if applicable)__:
Explain: 
```
Query String (88 chars, cacheable: true):
 FOR doc IN profile_view SEARCH ANALYZER(doc.email LIKE "%_gmail%", "text_en") RETURN doc

Execution plan:
 Id   NodeType            Est.   Comment
  1   SingletonNode          1   * ROOT
  2   EnumerateViewNode      2     - FOR doc IN profile_view SEARCH ANALYZER(LIKE(doc.`email`, "%_gmail%"), "text_en")   /* view query */
  3   ReturnNode             2       - RETURN doc

Indexes used:
 none

Optimization rules applied:
 Id   RuleName
  1   handle-arangosearch-views
```
Profile:
```
Query String (88 chars, cacheable: false):
 FOR doc IN profile_view SEARCH ANALYZER(doc.email LIKE "%_gmail%", "text_en") RETURN doc

Execution plan:
 Id   NodeType            Calls   Items   Runtime [s]   Comment
  1   SingletonNode           1       1       0.00002   * ROOT
  2   EnumerateViewNode       1       0       0.01031     - FOR doc IN profile_view SEARCH ANALYZER(LIKE(doc.`email`, "%_gmail%"), "text_en")   /* view query */
  3   ReturnNode              1       0       0.00002       - RETURN doc

Indexes used:
 none

Optimization rules applied:
 Id   RuleName
  1   handle-arangosearch-views

Query Statistics:
 Writes Exec   Writes Ign   Scan Full   Scan Index   Filtered   Exec Time [s]
           0            0           0            0          0         0.01196

Query Profile:
 Query Stage           Duration [s]
 initializing               0.00001
 parsing                    0.00018
 optimizing ast             0.00002
 loading collections        0.00003
 instantiating plan         0.00003
 optimizing plan            0.00023
 executing                  0.01039
 finalizing                 0.00104

```
__Dataset__:
The vertex-collection account in profile_view contains this data:
```
[
	{
		"_key": "priyavkkaneria+2@gmail.com",
		"_id": "account/priyavkkaneria+2@gmail.com",
		"_rev": "_ciObwXi--_",
		"email": "priyavkkaneria+2@gmail.com"
	},
	{
		"_key": "priyavkkaneria@gmail.com",
		"_id": "account/priyavkkaneria@gmail.com",
		"_rev": "_col5FDC---",
		"email": "priyavkkaneria@gmail.com"
	}
]

```

## Steps to reproduce

1. Make a vertex collection with above data
2. Make a view with text_en analyzer for email
3. Run the AQL query

__Problem__:
As the [documentation](https://www.arangodb.com/docs/stable/aql/functions-string.html#like) for `LIKE` function mentions,
We can use % for variable characters so %...% is equivalent to a contains search. For special characters like `@`, we should be able to use `_`, or `\\@` but neither of them work. I tried all number of `\` from 1 to 8 but none work. How can I do a contains like search with special characters with text_en? Or is any other analyzer to be used for the same?

__Expected result__:
Both the vertexes should be returned in the output as such
```
[
	{
		"_key": "priyavkkaneria+2@gmail.com",
		"_id": "account/priyavkkaneria+2@gmail.com",
		"_rev": "_ciObwXi--_",
		"email": "priyavkkaneria+2@gmail.com"
	},
	{
		"_key": "priyavkkaneria@gmail.com",
		"_id": "account/priyavkkaneria@gmail.com",
		"_rev": "_col5FDC---",
		"email": "priyavkkaneria@gmail.com"
	}
]
```

**Comment by Simran-B** [comment]
The `@` character has no special meaning to the `LIKE` function and does not require escaping. However, `` ANALYZER(LIKE(doc.`email`, "%_gmail%"), "text_en") `` is not going to work, because the emails are tokenized by the `text_en` Analyzer as follows:

```js
LET emails = [
  "priyavkkaneria+2@gmail.com",
  "priyavkkaneria@gmail.com"
]
RETURN TOKENS(emails, "text_en")
```

```json
[
  [
    [
      "priyavkkaneria",
      "2",
      "gmail",
      "com"
    ],
    [
      "priyavkkaneria",
      "gmail",
      "com"
    ]
  ]
]
```

`+`, `@`, `.` etc. are word boundaries just like whitespace that all `text` Analyzers use to split the text into individual tokens, and these characters are discarded. You will have to use a non-tokenizing Analyzer. The `identity` Analyzer is sufficient but is case-sensitive. You can use a custom `norm` Analyzer for case-insensitive search.

**Comment by PriyavKaneria** [comment]
Understood! Cool
