### ISSUE TITLE
Nested Transaction Error with removeByExample

### ISSUE THREAD

**Issue by carlverge** [arangodb/arangodb#1451]
Hey,

Similar to issue #1099 , I'm trying to use removeByExample in a transaction context, however this throws an HTTP 400 nested transactions detected. Testing this against 2.6.5. Is this known/intended behaviour? Right now I'm just iterating over objects and deleting them one by one.

Thanks,
Carl

**Comment by dothebart** [comment]
Confirmed. Fix would be to internally invoke AQL. Currently this can only be worked around using AQL from outside.

**Comment by jsteemann** [comment]
The issue has been fixed in devel, so it will be included in the next 2.7 release.
