### ISSUE TITLE
Arango Foxx Prometheus metrics

### ISSUE THREAD

**Issue by woodytec** [arangodb/arangodb#14510]
## My Environment

* __ArangoDB Version__:  3.7.10      
* __Storage Engine__:     RocksDB         
* __Deployment Mode__:   Single Server  + Leader/Follower ("Master/Slave")  
* __Deployment Strategy__:  Manual Start 
* __Configuration__:               
* __Infrastructure__:     own           
* __Operating System__:   Windows 10 / Windows Server 2016     
* __Total RAM in your machine__:    16Gb    
* __Disks in use__:       SSD          
* __Used Package__:      ArangoDB for Windows Zip package        

## Component, Query & Data

__Affected feature__: Foxx 

## Steps to reproduce

__Problem__:
Hi,

We built a foxx service, and we wanted to expose prometheus metrics specific to this service (number of requests per route, execution time per collection, ...). 

Our problem is that foxx microservices are stateless, so we can't have metrics that stay on requests (they get reset to 0 every time), and using arangodb to store the information is not a good idea given the amount of requests and frequency. 

Is there a way to do it ? 

Regards

__Expected result__:

**Comment by tomdavidson** [comment]
You could stand up a push gateway. Services running in Foxx push the metrics to the intermediary where Prometheus can scrap it. https://prometheus.io/docs/practices/pushing/
