### ISSUE TITLE
No precompiled package for TravisCI ArangoDb 2.6.5

### ISSUE THREAD

**Issue by aurelijusb** [arangodb/arangodb#1454]
http://www.arangodb.com/repositories/travisCI/setup_arangodb_2.6.sh script generates:
```
https://www.arangodb.com/repositories/travisCI/ArangoDB-2.6.5.tar.gz
```
But only 2.6.4 version exists:
https://www.arangodb.com/repositories/travisCI/ArangoDB-2.6.4.tar.gz

Also https://www.arangodb.com/repositories/travisCI/ArangoDB-2.6.tar.gz has size of 0 bytes.

It would be good to be able to test against newest stable version.

**Comment by fceller** [comment]
Package is uploading.
