### ISSUE TITLE
Unable to compile 3.7.13 on either Linux (AMD Zen 3) or macOS (M1 Rosetta2)

### ISSUE THREAD

**Issue by lloesche** [arangodb/arangodb#14545]
## My Environment

* __ArangoDB Version__:        3.7.13
* __Operating System__:        Debian Testing (g++ 10.2.1-6) & macOS 11.4 Apple clang version 12.0.5 (clang-1205.0.22.11)
* __Total RAM in your machine__:        128 GB & 16 GB

## Steps to reproduce

1. On a fresh minimal Debian testing system follow the steps to install build requirements at [https://www.arangodb.com/docs/stable/installation-compiling-debian.html](https://www.arangodb.com/docs/stable/installation-compiling-debian.html)
2.  Instead of downloading from Git I download the latest stable release source tarball at [https://download.arangodb.com/Source/ArangoDB-3.7.13.tar.bz2](https://download.arangodb.com/Source/ArangoDB-3.7.13.tar.bz2)
3. generating build config using `cmake .. -DCMAKE_INSTALL_PREFIX="$install_dir"`
4. `make`

__Problem__:
```
...
...
/home/builder/src/arangodb/3rdParty/s2geometry/dfefe0c/src/s2/util/math/mathutil.h: At global scope:
/home/builder/src/arangodb/3rdParty/s2geometry/dfefe0c/src/s2/util/math/mathutil.h:168:53: error: specialization of ‘static IntOut MathUtil::Round(FloatIn) [with IntOut = int; FloatIn = double]’ after instantiation
  168 | inline int32 MathUtil::Round<int32, double>(double x) {
...
...
```

Using g++ version:
```
builder@core1 ~ $ g++ --version
g++ (Debian 10.2.1-6) 10.2.1 20210110
```

I tried the same on macOS adding cmake arg `-DCMAKE_OSX_DEPLOYMENT_TARGET=10.11`:
```
...
...
/Users/builder/src/arangodb/3rdParty/s2geometry/dfefe0c/src/s2/util/math/mathutil.h:168:24: error: explicit specialization of 'Round<int, double>' after instantiation
inline int32 MathUtil::Round<int32, double>(double x) {                       ^
...
...
```

Using default Xcode clang:
```
builder@microair ~ % g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.5 (clang-1205.0.22.11)
Target: x86_64-apple-darwin20.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

__Expected result__:
Should compile without error.

**Comment by mpoeter** [comment]
What is your CPU architecture? I stumbled over the same issue with my Ryzen CPU, because it was not recognized correctly and so tried to compile some fallback code path in the s2 library for CPUs that do not support SSE2.

**Comment by lloesche** [comment]
The Linux machine is a `AMD Ryzen 9 5950X 16-Core Processor` the Mac is an M1 Macbook Air using `arch -x86_64` to run the compile in x86 mode using Rosetta 2. I'll retry my build on an Intel system.

**Comment by lloesche** [comment]
I can confirm, the build succeeded on a `Intel(R) Xeon(R) CPU @ 2.20GHz` machine but what baffled me more is it also compiled fine on an older `AMD EPYC 7281 16-Core Processor`. Which is Zen 1 architecture. I guess it might be old enough for the 3rd party library to detect it correctly.

**Comment by mpoeter** [comment]
@lloesche yes, there should only be a problem with CPUs that are _too new_ (not sure which exact architecture Rosetta emulates though). In particular, support for Zen 3 architecture has only been added to the 3.8 cmake config.

**Comment by lloesche** [comment]
> not sure which exact architecture Rosetta emulates though

@mpoeter any way for me to find out? Like, do you have a code snippet of the current detection code that I can compile and run inside Rosetta that spits out whatever it thinks it detects?
Or if you can point me to where the code is I should be able to find my way around.

I was able to compile latest master of `s2geometry` standalone on all platforms. On the Zen 3 Ryzen as well as the M1 Macbook in arm64 as well as x86_64 mode under Rosetta.

I just tried to build latest ArangoDB devel branch and got the same error as before.

**Comment by mpoeter** [comment]
Strange, the latest devel branch works for me on my Zen 3 CPU. The relevant code is in `cmake/OptimizeForArchitecture.cmake`. The problem is not the `s2geometry` library but the compiler arguments. Well the problem actually _is_ in the library since the code path for non-SSE2 CPUs is broken, but that is only triggered because the compiler config not setup correctly.

**Comment by lloesche** [comment]
> Strange, the latest devel branch works for me on my Zen 3 CPU.

I should have clarified, I tried to build latest ArangoDB devel branch on my M1 Macbook in x86 mode under Rosetta and that failed with the same error. I did not retry on the server.

**Comment by dothebart** [comment]
Rosetta doesn't have emulation for i.e. avx, which is why we  discarded the aproach to use M1 machines for the CI.

**Comment by lloesche** [comment]
@dothebart that makes sense, thanks for clarifying.
