### ISSUE TITLE
Docs: make example fails, missing rule?!

### ISSUE THREAD

**Issue by CoDEmanX** [arangodb/arangodb#1455]
`make examples` in root dir of repo should generate (missing) examples:

https://github.com/arangodb/arangodb/blob/master/README_maintainers.md#generate

There is no rule `examples` in `GNUmakefile` however. Did it vanish? Or is it somewhere else to be found?

**Comment by CoDEmanX** [comment]
Okay, so there's a `Makefile.files` in `Documentation/`, which reports "nothing to do for target examples" if you run `make examples`, but it does something on `make -f Makefile.files examples`. `@srcdir@` is not defined however and will make a Python script fail.

If I replace all occurrences of `@srcdir@` and `@builddir@` by `$(srcdir)` / `$(builddir)` and specify these paramterers on command line, then the Python script is run. I'm stopped again by another make error: No rule to build `start-server`. This seems to be defined in `Unittests/Makefile.unittests`, but cannot be found by the other make script.

Is there some magic to make this work? Some additional steps to take?

**Comment by dothebart** [comment]
As I tried to explain for you on friday, make examples depends on `configure` having run successfully - since `Documentation/Makefile.files` is included by `Makefile.in` which is processed by `configure` to produce `Makefile`. 
It is not part of the cmake generated build infrastructure.
I haven't tried it yet with cygwin, but you probably need to install mingw in order to make configure happy.

**Comment by CoDEmanX** [comment]
I added a couple Cygwin packages related to autoconf / configure, but not mingw. Maybe that will help. (mingw was already available on my host, but Cygwin might need its own version).

Still wondering if I need to run e.g. `make pack-win64-relative`, `configure something?` or `make setup` before `make examples` will work?

**Comment by dothebart** [comment]
make setup will re-create configure and all Makefile.in files.
in the end make examples is not that complicated at all, you could also run it by hand. 
the python line can be cut'n'pasted, and you probably want to go the way of having a running arangod to generate your examples - so you need the else-branch.

**Comment by CoDEmanX** [comment]
Okay, I'll try again back home. Maybe with http://www.gnu.org/software/libtool/libtool.html added to Cygwin to make configure work.

A little shell script would probably do, which does the steps manually as you suggested. I wonder if the following is correct however:

	python @srcdir@/Documentation/Scripts/generateExamples.py \
		--output-dir @builddir@/Documentation/Examples \

https://github.com/arangodb/arangodb/blob/devel/Documentation/Makefile.files#L65

`@builddir@/Documentation/...` looks like builddir should be the path to the repository root, but if you look further down the script, `@builddir@/bin/arangosh \` seems like `@builddir@` should actually be a build folder, which contains `bin/arangosh`. But that can't be in repository root, it's rather `arangodb/Build64/...`.
