### ISSUE TITLE
Template String Processor for AQL (ES6/7)

### ISSUE THREAD

**Issue by tracker1** [arangodb/arangodb#1457]
It would be pretty cool to see a template string processor (ES6) for turning AQL statements into parameterized queries...

for example:

```js
//es7 async method, db.aql returns promise
async function UpdateGodFatherEntries(godfather) {
  return await (db.aql`
    FOR p In Persons
    FILTER myfunctions::mustPayTax(p)
    LET distance = LENGTH(
      SHORTEST_PATH(Persons, Friends, p, ${godfather}, 'any')
    )
    FOR c IN Cities
      FILTER p.zip == c.zip
      UPDATE p WITH {taxPaid: p.taxPaid * c.discount * distance}
        IN Persons
  `);
}
```

by making `db.aql` follow ES6 Template string processing conventions, and return a Promise to resolve, you can then take the parameter being injected `${godfather}` and give it an index based entry as a parameterized query (such as `@p0`).

See [mssql-ng](https://github.com/tracker1/mssql-ng/blob/master/src/query/index.js) for example... (NOTE: the method I'm linking to is wrapped and exposed with the template parsing bits, but gets passed the instance to use for the real query.)

**Comment by CoDEmanX** [comment]
Wouldn't that defeat the purpose of bind parameters?

Just for fun:

	let aql = function(strings, ...values){
		let result = "";
	 
		for(let i = 0; i < strings.length; i++){
			result += strings[i];
			if(i < values.length){
				if (typeof values[i] == "string" && values[i].includes("-")){
					result += "`" + values[i] + "`";
				} else {
					result += values[i];
				}
			}
		}
		return result;
	};

	let coll = "name-with-dashes",
		max = 10;
		
	console.log(aql`
		FOR doc IN ${coll}
			LIMIT ${max}
			RETURN doc`
	)

	/* Firefox:
	FOR doc IN `name-with-dashes`
		LIMIT 10
		RETURN doc
	*/

**Comment by dothebart** [comment]
basically its [Bind parameters](https://docs.arangodb.com/cookbook/AvoidingInjection.html) and [promises in the client libraries](https://github.com/arangodb/arangojs) you're asking for? I don't see the point and therefore will close this now.

**Comment by tracker1** [comment]
@CoDEmanX @dothebart it basically would inline named parameters... @p0, @p1, so parameterized queries would happen... this would combine with a promisified result...   If you look at the code I posted, it's actually injecting parameter names into the query text, and adding them as a separate parameter transparently.

The syntax itself is cleaner (via templates) than separating the parameters as an options object for binding.   For details, see the articles below... you are not injecting raw values.. you are injecting parameter keys, and then running a parameter based queries.

http://ivc.com/blog/better-sql-strings-in-node-js/
http://ivc.com/blog/better-sql-strings-in-io-js-nodejs-part-2/

I went a step farther with mssql-ng to allow for explicit naming as well as output parameter injection.  That said, the end user code winds up being a lot cleaner this way.

**Comment by jsteemann** [comment]
I think @tracker1 is right. Using tagged template strings will work and will be safe. Implementing this in JS in ArangoShell and probably arangojs shouldn't do any harm.

**Comment by jsteemann** [comment]
@tracker1: I just added a template string generator function `aqlQuery` for generating AQL queries. It can be used from the ArangoShell, arangod (e.g. from inside Foxx actions) and the web interface. The change is currently contained in the devel branch, so it will become regularly available in 2.7.

Here's how it can be used:
```js
var name = 'test';                                                                                      
var query = aqlQuery`FOR u IN users FILTER u.name == ${name} RETURN u._key`;
db._query(query);
```
Internally, `aqlQuery` will use regular bind parameters. 
It will return an object with the query string and the actual bind parameter values separated, so it is safe to use (i.e. no parameter injection that can change the meaning of queries). Its result can be passed into the `db._query()` function directly, as shown above.

We can't use ES7 async/await yet. This is not supported by the V8 version we're currently using.

**Comment by tracker1** [comment]
@jsteemann You don't need to do anything other than return a promise for async/await to work in, for example node via babel. :-)  Assuming `db._query(...)` returns a promise... 

I was only thinking that it might be worthwhile to have a method on a connection instance that returned the promise directly... hence the `db.aql` suggestion, so as not to conflict with the existing query method.

Thanks for taking the time on this... my main driver is that template processing seems to be a nicer interface for handling procedural queries (sql/aql/cql etc) from inside JS.

**Comment by jsteemann** [comment]
@tracker1: I know, but ArangoShell and arangod (where I did the changes) are not based on node.js, and all the other operations in them are not Promise-based. Nor will promises be handled and resolved in current ArangoShell and arangod. They are simply not based on the async/non-blocking idiom.

It's completely different for node.js-based drivers of course, but that was not the scope of my work.

**Comment by tracker1** [comment]
@jsteemann understood, made the same request for the arrangojs client, since that was my original intent... though it's probably still useful in the arangoshell, etc.

**Comment by jsteemann** [comment]
Yes, I think it's also pretty useful in ArangoShell / arangod. Thanks for suggesting it!
