### ISSUE TITLE
[3.8.0] aardvark switching navpoints quickly causes react error

### ISSUE THREAD

**Issue by coronabytes** [arangodb/arangodb#14574]
## My Environment

* __ArangoDB Version__:        3.8.0
* __Deployment Mode__:       Single Server
* __Infrastructure__:               Own
* __Operating System__:        Ubuntu 20.04
* __Total RAM in your machine__:        8GB
* __Disks in use__:        SSD
* __Used Package__:              Ubuntu .deb

## Component, Query & Data

__Affected feature__:
Aardvark

## Steps to reproduce

1.  Switch Navpoints rather quickly (Queries, Dashboard, Logs, ...)
2. At least ten times

__Problem__:

After switching navigation entries a react error is thrown and the app becomes unresponsive

```
  | t.unmountComponentAtNode | @ | react-dom.production.min.js:7367
-- | -- | -- | --
  | execute | @ | router.js:111
  | (anonymous) | @ | backbone.js:1769
  | (anonymous) | @ | backbone.js:2025
  | Lt | @ | some.js:13
  | loadUrl | @ | backbone.js:2023
  | navigate | @ | backbone.js:2083
  | navigate | @ | backbone.js:1784
  | navigateByTab | @ | navigationView.js:159
  | dispatch | @ | jquery.js:4668
  | m.handle | @ | jquery.js:4488

</span></div><!--EndFragment-->
</body>
</html>
```

![React](https://user-images.githubusercontent.com/7018968/127746848-69726068-7c11-47e0-b7a2-2fd1d7f2d668.PNG)

**Comment by MDAlFattah** [comment]
Greetings @coronabytes,
Thank you for your kind insight into the Logs revisit the issue. Our developer team already addressed this issue and you may track the progress of the respective PR below which will also be included in the upcoming 3.8.1 release.

[Fixed LogsView re-visit issue](https://github.com/arangodb/arangodb/pull/14519)

**Comment by maxkernbach** [comment]
Hi @coronabytes,

Version 3.8.1, which includes the stated fix, has just been released.
Could you please upgrade and let us know whether the UI works as expected?

**Comment by coronabytes** [comment]
yes works now as expected
