### ISSUE TITLE
K_SHORTEST_PATH. Query execution time significantly increased for all versions starting with 3.6.4

### ISSUE THREAD

**Issue by amfedoseev** [arangodb/arangodb#14581]
## My Environment

* __ArangoDB Version__:        3.6.4-3.8.0
* __Storage Engine__:             RocksDB
* __Deployment Mode__:        Single Server
* __Deployment Strategy__:   ArangoDB Starter
* __Infrastructure__:               own
* __Operating System__:        CentOS Linux, 7.5.1804
* __Total RAM in your machine__:        280GB
* __Disks in use__:        SSD

## Component, Query & Data

__AQL query (if applicable)__:
```
FOR a IN nodes 
      FILTER a._key == '28241030'
 FOR d IN nodes
      FILTER d._key == '18767018'
FOR path IN OUTBOUND K_SHORTEST_PATHS a TO d
GRAPH 'test' 
 LIMIT 5
 RETURN path
```
__AQL explain and/or profile (if applicable)__:
```
Query String (361 chars, cacheable: false):
                     FOR a IN nodes 
                             FILTER a._key == '28241030'
                         FOR d IN nodes
                             FILTER d._key == '18767018'
                         FOR path IN OUTBOUND K_SHORTEST_PATHS a TO d
                         GRAPH 'test' 
                         LIMIT 5
                         RETURN path

Execution plan:
 Id   NodeType             Calls   Items   Runtime [s]   Comment
  1   SingletonNode            1       1       0.00000   * ROOT
 12   IndexNode                1       1       0.00047     - FOR a IN nodes   /* primary index scan */    
 11   IndexNode                1       1       0.00062       - FOR d IN nodes   /* primary index scan */    
  8   KShortestPathsNode       1       5     223.54239         - FOR path  /* path */ IN OUTBOUND K_SHORTEST_PATHS a /* startnode */ TO d /* targetnode */ GRAPH 'test'
  9   LimitNode                1       5       0.00001         - LIMIT 0, 5
 10   ReturnNode               1       5       0.00000         - RETURN path

Indexes used:
 By   Name      Type      Collection   Unique   Sparse   Selectivity   Fields       Ranges
 12   primary   primary   nodes        true     false       100.00 %   [ `_key` ]   (a.`_key` == "28241030")
 11   primary   primary   nodes        true     false       100.00 %   [ `_key` ]   (d.`_key` == "18767018")

k shortest paths on graphs:
 Id   Vertex collections   Edge collections
  8   nodes                links              

Optimization rules applied:
 Id   RuleName
  1   use-indexes
  2   remove-filter-covered-by-index
  3   remove-unnecessary-calculations-2

Query Statistics:
 Writes Exec   Writes Ign   Scan Full   Scan Index   Filtered   Exec Time [s]
           0            0           0            2          0       224.76955

Query Profile:
 Query Stage           Duration [s]
 initializing               0.00000
 parsing                    0.00068
 optimizing ast             0.00001
 loading collections        0.00000
 instantiating plan         0.00007
 optimizing plan            0.00030
 executing                223.54353
 finalizing                 1.22492
```
__Dataset__:
Test dataset example is available on google drive with the following link
https://drive.google.com/file/d/1SltyH_qkqtp6q3FIQvsKHCAx4EGGIJpP/view

__Size of your Dataset on disk__:
9.5GB

## Steps to reproduce

1. Run ArangoDB Starter (any versions among 3.6.4 and 3.8.0)
2. Create database with name **test**
3. Restore databases from the attached file 
4. Create Graph with name **test**
5. Execute the query above 

__Problem__:
Time execution of K_SHORTEST_PATHS query in comparison with previous version (f. ex. 3.6.3) significantly increased
(appx 200 seconds now vs 5 seconds before) despite the usage of the same query, dataset and environment.

**Comment by maxkernbach** [comment]
Hi @amfedoseev,

Version 3.6.4 includes the following [fix](https://github.com/arangodb/arangodb/blob/41ac91b2eca790ae668b06f10580ee1c39ab194a/CHANGELOG#L1379) for `K_SHORTEST_PATHS`:

> * Fixed issue #10371: For k-shortest-paths queries on certain graphs a condition
  to abort search was too eager and hence missed the shortest path between two
  vertices and returned a longer one.

It seems like this condition had no impact on your graph since in both versions 3.6.3 and 3.6.4+ the same result is returned. Aborting the search early as in 3.6.3 will reduce the execution time significantly. Still, generally speaking `K_SHORTEST_PATHS` was not properly working in 3.6.3 and it could happen that a shortest path was missed.
