### ISSUE TITLE
IS_NULL(@x) isn't recognized as a constant expression

### ISSUE THREAD

**Issue by wajda** [arangodb/arangodb#14592]
## My Environment

* __ArangoDB Version__:  3.8.0      
* __Storage Engine__:   RocksDB          
* __Deployment Mode__:   Single server    
* __Deployment Strategy__:   Manual 
* __Configuration__:   all defaults             
* __Infrastructure__:  localhost             
* __Operating System__:   Fedora 34     
* __Total RAM in your machine__:   32     
* __Disks in use__:  SSD      
* __Used Package__:    RPM          

## Component, Query & Data

__Affected feature__: AQL

__AQL query (if applicable)__:
```
FOR p IN progress
    FILTER IS_NULL(42) OR p._created <= 1597223295580
    RETURN p
```
__AQL explain and/or profile (if applicable)__:

```
Query String (84 chars, cacheable: true):
 FOR p IN progress
     FILTER IS_NULL(42) OR p._created <= 1597223295580
     RETURN p

Execution plan:
 Id   NodeType                    Est.   Comment
  1   SingletonNode                  1   * ROOT
  2   EnumerateCollectionNode   112121     - FOR p IN progress   /* full collection scan */   FILTER ((42 == null) || (p.`_created` <= 1597223295580))   /* early pruning */
  5   ReturnNode                112121       - RETURN p

Indexes used:
 none

Optimization rules applied:
 Id   RuleName
  1   move-filters-into-enumerate

Optimization rules with highest execution times:
 RuleName                                    Duration [s]
 use-indexes                                      0.00002
 reduce-extraction-to-projection                  0.00000
 move-filters-into-enumerate                      0.00000
 remove-filter-covered-by-index                   0.00000
 remove-filter-covered-by-traversal               0.00000

41 rule(s) executed, 1 plan(s) created
```

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. 
2. 
3. 

__Problem__:

There is a persistent index on the field `progress._created`, but it is not used in the query above. However it is used when the expression `IS_NULL(42)` is removed or is replaced with the equivalent `!42` or `false`

![image](https://user-images.githubusercontent.com/795479/128396892-aba251f2-15c1-484e-8e8c-81dc5d95f816.png)

```
FOR p IN progress
    FILTER !(42) OR p._created <= 1597223295580
    RETURN p
```

```
Query String (78 chars, cacheable: true):
 FOR p IN progress
     FILTER !(42) OR p._created <= 1597223295580
     RETURN p

Execution plan:
 Id   NodeType          Est.   Comment
  1   SingletonNode        1   * ROOT
  6   IndexNode       112121     - FOR p IN progress   /* persistent index scan */    
  5   ReturnNode      112121       - RETURN p

Indexes used:
 By   Name                      Type         Collection   Unique   Sparse   Selectivity   Fields           Ranges
  6   idx_1706538285530087424   persistent   progress     false    false        99.91 %   [ `_created` ]   (p.`_created` <= 1597223295580)

Optimization rules applied:
 Id   RuleName
  1   use-indexes
  2   remove-filter-covered-by-index
  3   remove-unnecessary-calculations-2

Optimization rules with highest execution times:
 RuleName                                    Duration [s]
 use-indexes                                      0.00004
 remove-filter-covered-by-index                   0.00001
 remove-unnecessary-calculations-2                0.00000
 reduce-extraction-to-projection                  0.00000
 replace-function-with-index                      0.00000

41 rule(s) executed, 1 plan(s) created
```

__Expected result__:

_Index scan_ to be used in both queries.

**Comment by wajda** [comment]
I see the `move-filters-into-enumerate` optimization is applied for the first query. But in fact this optimization makes the query to perform slower that the variant with the index scan. Why is it?

**Comment by mpoeter** [comment]
Obviously `IS_NULL(42)` is a constant expression that always evaluates to false, but apparently the optimizer fails to recognize this and therefore is not able to apply the index. The `move-filters-into-enumerate` optimization performs the filter as part of the enumeration instead of a separate calculation node. This should be faster (try disabling this rule), but we still have to perform a full collection scan which is slower than if we could utilize the index.

The lack of recognizing `IS_NULL(42)` as a constant expression is certainly something that we could improve, but the query seems quite contrived. Did you experience the same problem in a more realistic query?

**Comment by wajda** [comment]
Thanks Manuel,

> The lack of recognizing `IS_NULL(42)` as a constant expression is certainly something that we could improve

> Instead of `IS_NULL` you could try comparing with null (e.g., `42 == null` )

Indeed, replacing `IS_NULL(@x)` with `@x == null` made the difference.
Quite surprisingly this seemingly equivalent change resulted in the full collection turned into the index scan and about 14 times query speed up :)

**Comment by mpoeter** [comment]
It seems that the optimizer translates `IS_NULL(42)` into `42 == null`, but does not perform another pass that would translate that expression to false.

**Comment by jsteemann** [comment]
Fixed by the above PRs.

**Comment by maxkernbach** [comment]
Hi @wajda,

Both versions 3.7.14 and 3.8.1, which include a fix for this issue, have been released.
Could you please upgrade and let us know whether your initial query works as expected?

**Comment by wajda** [comment]
Yes, it works perfect now! Thank you very much!
