### ISSUE TITLE
AQL UPDATE in a loop fails to concat and counts up instead

### ISSUE THREAD

**Issue by CoDEmanX** [arangodb/arangodb#1460]
Query 1:

    INSERT {_key: "A", text: "foo"} INTO test
    RETURN NEW

Result 1:

    [
      {
        "text": "foo",
        "_id": "test/A",
        "_rev": "435016317360",
        "_key": "A"
      }
    ]

Query 2:

    LET doc = DOCUMENT("test/A")
    FOR i IN 1..100
        UPDATE doc WITH {text: CONCAT(doc.text, TO_STRING(i))} IN test
        RETURN NEW

Result 2:

    [
      {
        "text": "foo1",
        "_id": "test/A",
        "_rev": "435037157808",
        "_key": "A"
      },
      {
        "text": "foo2",
        "_id": "test/A",
        "_rev": "435037354416",
        "_key": "A"
      },
      {
        "text": "foo3",
        "_id": "test/A",
        "_rev": "435037485488",
        "_key": "A"
      },
      {
        "text": "foo4",
        "_id": "test/A",
        "_rev": "435037616560",
        "_key": "A"
      }, ...

Both queries are valid and complete without errors or warnings. The result is not as expected however, `text` should be `foo12345678910111213...` at the end. Instead, `1` is appended in the first round, then continuously incremented despite the explicit type cast to string.

Similar behavior is exhibit if the attribute is an array and an element appended. If the to-to-concated object is a string like "x", then it's appended exactly once.

None of the query options and `NOOPT(PASSTHRU(...))` make a difference.

v2.7.0-devel as of a few days ago.

**Comment by mchacki** [comment]
Well i think this behavior is actually intended.
Lets analyst your query:
1) Load the document from the store and store it in doc (now doc will contain text: "foo")
2) Iterate i from 1 to 100
  * For each i take the thing you have in hand called "doc" (No reading from collection instructed here)
  * Append i to doc.text (which ist still text: "foo")
  * Contact the collection and update a document with the same identifier as "doc" with the content of doc.

To achieve would you would like to do you will have to move the access to the collection inside the for loop:

```
FOR i IN 1..100
    LET doc = DOCUMENT("test/A")
    UPDATE doc WITH {text: CONCAT(doc.text, TO_STRING(i))} IN test
    RETURN NEW
```

**Comment by CoDEmanX** [comment]
Good catch, but I actually tried some other constellations too:

	FOR i IN 1..100
		UPDATE "A" WITH {text: CONCAT(DOCUMENT("test/A").text, i)} IN test
		RETURN NEW
	//////////////////////////////////////////////////////////
	LET doc = DOCUMENT("test/A")
	FOR i IN 1..100
		LET doc2 = DOCUMENT("test/A")
		LET t = doc2.text
		UPDATE doc WITH {text: CONCAT(t, TO_STRING(i))} IN test
		RETURN NEW
	//////////////////////////////////////////////////////////
	FOR i IN 1..100
		LET doc = DOCUMENT("test/A")
		LET t = CONCAT(doc.text, TO_STRING(i))
		UPDATE doc WITH {text: t} IN test
		RETURN NEW
	//////////////////////////////////////////////////////////
	LET docs = (
		FOR i IN 1..100
			RETURN [DOCUMENT("test/A"), TO_STRING(i)]
	)
	FOR doc IN docs
		LET t = CONCAT(doc[0].text, doc[1])
		UPDATE doc[0] WITH {text: t} IN test
		RETURN NEW

Result is always the same!

**Comment by CoDEmanX** [comment]
What works is:

    UPDATE "A" WITH {text: CONCAT(DOCUMENT("test/A").text, FOR i IN 1..100 RETURN i)} IN test
    RETURN NEW

It looks as though every attempt to modify the same document in a loop is doomed to fail.

**Comment by Simran-B** [comment]
Shouldn't these two queries behave the same?

```js
FOR i IN 1..2
    UPDATE DOCUMENT("test/A") WITH {text: CONCAT(DOCUMENT("test/A").text, "-", i)} IN test
```

```js
UPDATE DOCUMENT("test/A") WITH {text: CONCAT(DOCUMENT("test/A").text, "-", 1)} IN test
UPDATE DOCUMENT("test/A") WITH {text: CONCAT(DOCUMENT("test/A").text, "-", 2)} IN test
```

The latter fails because of "access after data-modification (while optimizing ast)", but the former does not. I think it should though. It sort of overwrites the change of the first UPDATE in the second UPDATE (only a local change at that point?), and only the second change will survive. Paradoxically,  the previous change is visible in the pseudo variable OLD of the first UPDATE (`RETURN {OLD, NEW}`).
