### ISSUE TITLE
How to compact a collection size

### ISSUE THREAD

**Issue by spoh-ally** [arangodb/arangodb#14623]
## My Environment

* __ArangoDB Version__:         3.6.12
* __Storage Engine__:              RocksDB
* __Deployment Mode__:        Cluster
* __Deployment Strategy__:    ArangoDB Starter
* __Configuration__:                3 nodes cluster
* __Infrastructure__:                owned RHEL VMs
* __Operating System__:         RHEL 8.2
* __Total RAM in your machine__:         32GB each nodes
* __Disks in use__:         SATA
* __Used Package__:               RedfHat .rpm

## Component, Query & Data

__Affected feature__:
 

__AQL query (if applicable)__:
```


```
__AQL explain and/or profile (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:
 7GB

__Replication Factor & Number of Shards (Cluster only)__:
replication factor: 3

## Steps to reproduce

1. deleted data results from the application and found the data size didn't shrink
2. run arangosh and tried to compact the collections - col.compact();
3. but got the message saying "Cannot read property 'compact' of undefined"

__Problem__:
cannot control the growing size of Database...almost 90% full

__Expected result__:
should be deleted all outdated documents and get recover the database spaces

**Comment by Simran-B** [comment]
Assuming that your collection is called `col` and that you use the correct database already (`db._useDatabase('dbname');`), then this should work: `db.col.compact();`

You can also trigger the compaction for all databases with `db._compact();`

**Comment by ohsp123-arango** [comment]
Thanks but still I have another issue, JavaScript exception. Could you advise me ?

127.0.0.1:8529@_system> db._compact();
JavaScript exception in file '/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js' at 99,7: ArangoError 11: compaction is only allowed for superusers
!      throw error;
!      ^
stacktrace: ArangoError: compaction is only allowed for superusers
    at Object.exports.checkRequestResult (/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js:97:21)
    at Proxy.ArangoDatabase._compact (/usr/share/arangodb3/js/client/modules/@arangodb/arango-database.js:277:12)
    at <shell command>:1:4


127.0.0.1:8529@_system> db._useDatabase('Dev');
true

127.0.0.1:8529@Dev> db.col.compact();
JavaScript exception: TypeError: Cannot read property 'compact' of undefined
!db.col.compact();
!       ^
stacktrace: TypeError: Cannot read property 'compact' of undefined
    at <shell command>:1:8

**Comment by Simran-B** [comment]
It looks like there is no collection `col` in the database `Dev`. You can list the collections with `db._collections()`.

> compaction is only allowed for superusers

You'll need to connect to the server as the superuser. I assume you use a JWT secret for arangod?

**Comment by dothebart** [comment]
closing as solved.
