### ISSUE TITLE
arangorestore taking couple of days to restore complete data

### ISSUE THREAD

**Issue by yogeshbidari** [arangodb/arangodb#14634]
## My Environment

* __ArangoDB Version__:        3.3.8 
* __Storage Engine__:             RocksDB 
* __Deployment Mode__:       single server 
* __Deployment Strategy__:   Kubernetes 
* __Infrastructure__:               GKE 
* __Operating System__:        debian 9
* __Total RAM in your machine__:        180GB 
* __Disks in use__:        SSD
* __Used Package__:             Docker 

## Component, Query & Data

__Affected feature__:

Arangorestore

__Dataset__:

__Size of your Dataset on disk__:

80GB

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. Take backup of arangodb using arangodump 
2. restore using arangorestore

__Problem__:
The arangorestore is taking more than 2 days(48hrs) to restore around 80GB of data.

__Expected result__:
arangorestore should take less time.
Any process or method can we use to speedup the restore process?

**Comment by Simran-B** [comment]
ArangoDB 3.3 is not supported anymore since November 15th, 2019. Newer versions feature a `--threads` option and other improvements. Please upgrade to at least 3.7, as support for 3.6 ends this month.
