### ISSUE TITLE
On replicant node journal logfile grow unbounded

### ISSUE THREAD

**Issue by ericfiala** [arangodb/arangodb#1465]
We have issue where on replicant node /var/lib/arangodb/journals does not appear to be purging files.  
The only way that we've seen these disappear is with two cycles of arango stop / start , on the second start, I see the files disappear.

On the master node, the same logs seemed to be getting purged.

Have I misconfigured my cluster, or has some behavior changed with 2.6.x ?  We did not notice this in prior versions.

**Comment by jsteemann** [comment]
Which exact version is the server running on? And are you using the cluster or a *regular* ArangoDB with replication? 
Can you also provide the more details about the non-purged files from the server that is not purging? It looks like this affects the files in the `journal` directory, but to be sure, can you run the command `find /var/lib/arangodb/journals -type f` and share its output here? Finally, what is the configuration value for `--wal.historic-logfiles` on that server? The default value is 10, meaning the server will keep at least 10 logfiles as its backlog (plus it will have some active ones which will be currently written to).

**Comment by ericfiala** [comment]
- arangodb-2.6.3-6.1.x86_64 on Centos 6
- Regular not cluster
- Output for
find /var/lib/arangodb/journals -type f
/var/lib/arangodb/journals/logfile-2634828435423.db
/var/lib/arangodb/journals/logfile-2648803200991.db
/var/lib/arangodb/journals/logfile-2649487724511.db
/var/lib/arangodb/journals/logfile-2634154987487.db
/var/lib/arangodb/journals/logfile-2579630502527.db
[... snip 194 files total...]
/var/lib/arangodb/journals/logfile-2625298124767.db
/var/lib/arangodb/journals/logfile-2647431073759.db
/var/lib/arangodb/journals/logfile-2579973321343.db
/var/lib/arangodb/journals/logfile-2647265071071.db
/var/lib/arangodb/journals/logfile-2632455114719.db
/var/lib/arangodb/journals/logfile-2639074906079.db

- wal.historic-logfiles I am not specifying (so, default, 10 - which is closer to what I'm seeing on the master, but not on this replicant)

Thanks

**Comment by ericfiala** [comment]
The number of files still grows, unbounded 

find /var/lib/arangodb/journals -type f | wc -l
289

How should we proceed?

**Comment by jsteemann** [comment]
I wasn't able to reproduce the issue here. I have therefore added a some diagnostic functions for this in the 2.6 branch. These will become available in 2.6.8 and may help find the root cause. We plan to create 2.6.8 this week, so hopefully that will reveal the source of the problem. I'll post here when 2.6.8 is available.

**Comment by jsteemann** [comment]
ArangoDB 2.6.8 is available for download now. Can you recheck with this version if the problem persists? 

If yes, can you issue the following commands on the command-line?
```
curl -X GET http://127.0.0.1:8529/_admin/wal/transactions && echo
curl -X GET http://127.0.0.1:8529/_api/replication/logger-tick-ranges && echo
```
Note that IP address and port in the above URLs should be those of the replication node. Can you repeat these commands a few times with a few minutes delay in between? I think that will help collect enough diagnostic information to find the problem cause. Thanks!

**Comment by ericfiala** [comment]
I still encounter this problem.  Now I am running arangodb-2.6.8-13.1.x86_64

Below is the output for the curl commands, with 10 minute intervals.

Note that I have two sets of master / replicant, both with pretty much the same data... only one of the replicant sets is exhibiting this behaviour (the other is consistently keeping about 15 files, and purging off the oldest.)

{"runningTransactions":3131,"minLastCollected":"2511506684576","minLastSealed":"2702374517408","error":false,"code":200}
[{"datafile":"/var/lib/arangodb/journals/logfile-2421937394059.db","status":"collected","tickMin":2447973994891,"tickMax":2460504019339},{"datafile":"/var/lib/arangodb/journals/logfile-2421937459595.db","status":"collected","tickMin":2460504412555,"tickMax":2473062355339},{"datafile":"/var/lib/arangodb/journals/logfile-2435443970443.db","status":"collected","tickMin":2473062683019,"tickMax":2485592445323},{"datafile":"/var/lib/arangodb/journals/logfile-2447974257035.db","status":"collected","tickMin":2485592773003,"tickMax":2498123059595},{"datafile":"/var/lib/arangodb/journals/logfile-2460504674699.db","status":"collected","tickMin":2498123387275,"tickMax":2510653149579},{"datafile":"/var/lib/arangodb/journals/logfile-2473062748555.db","status":"collected","tickMin":2510653477259,"tickMax":2511506166155},{"datafile":"/var/lib/arangodb/journals/logfile-2511506553504.db","status":"collected","tickMin":2511507208864,"tickMax":2695026293408},{"datafile":"/var/lib/arangodb/journals/logfile-2511506619040.db","status":"collected","tickMin":2695026490016,"tickMax":2698704566944},{"datafile":"/var/lib/arangodb/journals/logfile-2511506684576.db","status":"collected","tickMin":2698704763552,"tickMax":2702373862048},{"datafile":"/var/lib/arangodb/journals/logfile-2511506750112.db","status":"collected","tickMin":2702374255264,"tickMax":2705951799968},{"datafile":"/var/lib/arangodb/journals/logfile-2695026621088.db","status":"collected","tickMin":2705952193184,"tickMax":2708724759200},{"datafile":"/var/lib/arangodb/journals/logfile-2698704894624.db","status":"collected","tickMin":2708724955808,"tickMax":2711124949664},{"datafile":"/var/lib/arangodb/journals/logfile-2702374517408.db","status":"collected","tickMin":2711125146272,"tickMax":2711523932832},{"datafile":"/var/lib/arangodb/journals/logfile-2713588836733.db","status":"sealed","tickMin":2713588967805,"tickMax":2719464335741},{"datafile":"/var/lib/arangodb/journals/logfile-2713592572285.db","status":"sealed","tickMin":2719464532349,"tickMax":2721725983101},{"datafile":"/var/lib/arangodb/journals/logfile-2713592637821.db","status":"sealed","tickMin":2721726179709,"tickMax":2723962399101},{"datafile":"/var/lib/arangodb/journals/logfile-2713592703357.db","status":"sealed","tickMin":2723962595709,"tickMax":2726176991613},{"datafile":"/var/lib/arangodb/journals/logfile-2719464663421.db","status":"sealed","tickMin":2726177188221,"tickMax":2728340466045},{"datafile":"/var/lib/arangodb/journals/logfile-2721726310781.db","status":"sealed","tickMin":2728340728189,"tickMax":2730570197373},{"datafile":"/var/lib/arangodb/journals/logfile-2723962726781.db","status":"sealed","tickMin":2730570459517,"tickMax":2732675082621},{"datafile":"/var/lib/arangodb/journals/logfile-2726177319293.db","status":"sealed","tickMin":2732675279229,"tickMax":2734741367165},{"datafile":"/var/lib/arangodb/journals/logfile-2728341055869.db","status":"sealed","tickMin":2734741563773,"tickMax":2736792054141},{"datafile":"/var/lib/arangodb/journals/logfile-2730570787197.db","status":"sealed","tickMin":2736792250749,"tickMax":2738838350205},{"datafile":"/var/lib/arangodb/journals/logfile-2732675410301.db","status":"sealed","tickMin":2738838546813,"tickMax":2740864395645},{"datafile":"/var/lib/arangodb/journals/logfile-2734741694845.db","status":"sealed","tickMin":2740864592253,"tickMax":2742909643133},{"datafile":"/var/lib/arangodb/journals/logfile-2736792381821.db","status":"sealed","tickMin":2742909839741,"tickMax":2744934967677},{"datafile":"/var/lib/arangodb/journals/logfile-2738838677885.db","status":"sealed","tickMin":2744935164285,"tickMax":2746978052477},{"datafile":"/var/lib/arangodb/journals/logfile-2740864723325.db","status":"sealed","tickMin":2746978249085,"tickMax":2749023234429},{"datafile":"/var/lib/arangodb/journals/logfile-2742909970813.db","status":"sealed","tickMin":2749023431037,"tickMax":2751048690045},{"datafile":"/var/lib/arangodb/journals/logfile-2744935295357.db","status":"sealed","tickMin":2751048886653,"tickMax":2753092102525},{"datafile":"/var/lib/arangodb/journals/logfile-2746978380157.db","status":"sealed","tickMin":2753092299133,"tickMax":2755117099389},{"datafile":"/var/lib/arangodb/journals/logfile-2749023562109.db","status":"sealed","tickMin":2755117295997,"tickMax":2757162281341},{"datafile":"/var/lib/arangodb/journals/logfile-2751049017725.db","status":"sealed","tickMin":2757162609021,"tickMax":2759191406973},{"datafile":"/var/lib/arangodb/journals/logfile-2753092430205.db","status":"open","tickMin":2759191734653,"tickMax":2760769972605}]


[ 10 minutes later ]

{"runningTransactions":3131,"minLastCollected":"2511506684576","minLastSealed":"2702374517408","error":false,"code":200}
[{"datafile":"/var/lib/arangodb/journals/logfile-2421937394059.db","status":"collected","tickMin":2447973994891,"tickMax":2460504019339},{"datafile":"/var/lib/arangodb/journals/logfile-2421937459595.db","status":"collected","tickMin":2460504412555,"tickMax":2473062355339},{"datafile":"/var/lib/arangodb/journals/logfile-2435443970443.db","status":"collected","tickMin":2473062683019,"tickMax":2485592445323},{"datafile":"/var/lib/arangodb/journals/logfile-2447974257035.db","status":"collected","tickMin":2485592773003,"tickMax":2498123059595},{"datafile":"/var/lib/arangodb/journals/logfile-2460504674699.db","status":"collected","tickMin":2498123387275,"tickMax":2510653149579},{"datafile":"/var/lib/arangodb/journals/logfile-2473062748555.db","status":"collected","tickMin":2510653477259,"tickMax":2511506166155},{"datafile":"/var/lib/arangodb/journals/logfile-2511506553504.db","status":"collected","tickMin":2511507208864,"tickMax":2695026293408},{"datafile":"/var/lib/arangodb/journals/logfile-2511506619040.db","status":"collected","tickMin":2695026490016,"tickMax":2698704566944},{"datafile":"/var/lib/arangodb/journals/logfile-2511506684576.db","status":"collected","tickMin":2698704763552,"tickMax":2702373862048},{"datafile":"/var/lib/arangodb/journals/logfile-2511506750112.db","status":"collected","tickMin":2702374255264,"tickMax":2705951799968},{"datafile":"/var/lib/arangodb/journals/logfile-2695026621088.db","status":"collected","tickMin":2705952193184,"tickMax":2708724759200},{"datafile":"/var/lib/arangodb/journals/logfile-2698704894624.db","status":"collected","tickMin":2708724955808,"tickMax":2711124949664},{"datafile":"/var/lib/arangodb/journals/logfile-2702374517408.db","status":"collected","tickMin":2711125146272,"tickMax":2711523932832},{"datafile":"/var/lib/arangodb/journals/logfile-2713588836733.db","status":"sealed","tickMin":2713588967805,"tickMax":2719464335741},{"datafile":"/var/lib/arangodb/journals/logfile-2713592572285.db","status":"sealed","tickMin":2719464532349,"tickMax":2721725983101},{"datafile":"/var/lib/arangodb/journals/logfile-2713592637821.db","status":"sealed","tickMin":2721726179709,"tickMax":2723962399101},{"datafile":"/var/lib/arangodb/journals/logfile-2713592703357.db","status":"sealed","tickMin":2723962595709,"tickMax":2726176991613},{"datafile":"/var/lib/arangodb/journals/logfile-2719464663421.db","status":"sealed","tickMin":2726177188221,"tickMax":2728340466045},{"datafile":"/var/lib/arangodb/journals/logfile-2721726310781.db","status":"sealed","tickMin":2728340728189,"tickMax":2730570197373},{"datafile":"/var/lib/arangodb/journals/logfile-2723962726781.db","status":"sealed","tickMin":2730570459517,"tickMax":2732675082621},{"datafile":"/var/lib/arangodb/journals/logfile-2726177319293.db","status":"sealed","tickMin":2732675279229,"tickMax":2734741367165},{"datafile":"/var/lib/arangodb/journals/logfile-2728341055869.db","status":"sealed","tickMin":2734741563773,"tickMax":2736792054141},{"datafile":"/var/lib/arangodb/journals/logfile-2730570787197.db","status":"sealed","tickMin":2736792250749,"tickMax":2738838350205},{"datafile":"/var/lib/arangodb/journals/logfile-2732675410301.db","status":"sealed","tickMin":2738838546813,"tickMax":2740864395645},{"datafile":"/var/lib/arangodb/journals/logfile-2734741694845.db","status":"sealed","tickMin":2740864592253,"tickMax":2742909643133},{"datafile":"/var/lib/arangodb/journals/logfile-2736792381821.db","status":"sealed","tickMin":2742909839741,"tickMax":2744934967677},{"datafile":"/var/lib/arangodb/journals/logfile-2738838677885.db","status":"sealed","tickMin":2744935164285,"tickMax":2746978052477},{"datafile":"/var/lib/arangodb/journals/logfile-2740864723325.db","status":"sealed","tickMin":2746978249085,"tickMax":2749023234429},{"datafile":"/var/lib/arangodb/journals/logfile-2742909970813.db","status":"sealed","tickMin":2749023431037,"tickMax":2751048690045},{"datafile":"/var/lib/arangodb/journals/logfile-2744935295357.db","status":"sealed","tickMin":2751048886653,"tickMax":2753092102525},{"datafile":"/var/lib/arangodb/journals/logfile-2746978380157.db","status":"sealed","tickMin":2753092299133,"tickMax":2755117099389},{"datafile":"/var/lib/arangodb/journals/logfile-2749023562109.db","status":"sealed","tickMin":2755117295997,"tickMax":2757162281341},{"datafile":"/var/lib/arangodb/journals/logfile-2751049017725.db","status":"sealed","tickMin":2757162609021,"tickMax":2759191406973},{"datafile":"/var/lib/arangodb/journals/logfile-2753092430205.db","status":"open","tickMin":2759191734653,"tickMax":2760788060541}]

**Comment by jsteemann** [comment]
I have investigated the code for the logfile collector, and there are four situations in which it won't remove a collected logfile:
* the data in the logfile are still used by running transactions. this is not the case according to the data you posted.
* data from a logfile are being streamed to a slave. if you don't have other slaves connected to a slave, then we can rule out this option, too.
*  if the collector still has to apply operations from the logfile, it will try to get a lock on the collection. it will give up if it cannot instantly get this lock. in this case it won't make any immediate progress. the expectation however is that it will eventually get the lock and make progress later.
* if the collector cannot carry out the operations contained in a logfile. in this case you should see an error or a warning in ArangoDB's log.

Can you confirm there are no other slaves connected to the slave that exhibits the problem and that there are tno errors/warnings in the logs? Then it's probably the third option, that the collector can't get the lock and doesn't make any progress.
You mentioned that there are two slaves, out of which only one has the problem. are these slaves connected to the same master, are configured identically and have about the same hardware specs? Or is there any notable difference between the slave instances?

**Comment by dothebart** [comment]
@ericfiala have you been able to revalidate whether this is fixed with 2.7?

**Comment by ericfiala** [comment]
We we just working through other blocking factors.
We should be ready to upgrade the problem environment once https://github.com/arangodb/arangodb/issues/1592 is available in bugfix.

Will update.

**Comment by dothebart** [comment]
#1592 was part of 2.7.2

**Comment by pekeler** [comment]
@dothebart there've been necessary changes for #1592 since 2.7.2 (https://github.com/arangodb/arangodb/commit/f781440392957f128ca47dcdb5e65ec58b38c25e). I'm eagerly waiting for 2.7.3.

**Comment by fceller** [comment]
@pekeler 2.7.3 is now available for download

**Comment by ericfiala** [comment]
the original reported issue is no longer happening after upgrade to arangodb-2.7.3-18.1.x86_64 and running for 5 days.  The number of journal files is no longer growing unbounded.
