### ISSUE TITLE
Replication stopped working after changing AF instance and upgrading

### ISSUE THREAD

**Issue by mtzonev** [arangodb/arangodb#14698]
## My Environment

* __ArangoDB Version__:        3.7.14
* __Storage Engine__:             RocksDB 
* __Deployment Mode__:       Active Failover
* __Deployment Strategy__:   Manual Start
* __Configuration__:               1 agency, 2 single instances with enabled replication
* __Infrastructure__:               AWS 
* __Operating System__:        Ubuntu 20.04
* __Total RAM in your machine__:        15GB each
* __Disks in use__:        SSD
* __Used Package__:              Ubuntu .deb

## Component, Query & Data

__Affected feature__:
Replication

## Steps to reproduce

1. Change one of the single instances
2. Upgrade to latest version
3. ??? (I'm not sure if this is reproducible but that's what I did)

__Problem__:
I had to replace one of the instances (in this case it happened to be the follower at the time) for a new one. While doing so I noticed there was a newer version (3.7.14) so I upgraded all three instances from to it from 3.7.11. I first detached the old instance that was going to retire from the AF environment, upgraded it and cloned it. Then I upgraded the Agency and the Leader, in this order. The AF cluster was running back to normal with just the Leader in place. I attached the new Follower to it - I saw it appear in the Replication section of the web UI on the Leader so it gets detected correctly but looking at it's log file it appears the replication is failing with this message `HTTP 401: Unauthorized - {"error":true,"errorNum":11,"errorMessage":"not authorized to execute this request","code":401}`. I disabled authentication on both instances and the Follower started replicating and synced fully with the Leader. Re-enabling authentication on the Leader triggers the same error on the Follower. Technically it's not a problem to leave it like that as the cluster is running in a closed network but I'm annoyed that it was working before and now it doesn't. I had similar issues when I first set up the AF configuration a while ago but back then cycling through disabled/enabled authentication got it working eventually (or at least that's what I did and it fixed itself so I assumed that was the cause) but now it appears that's not enough.

__Expected result__:
Follower to correctly replicate from the Leader with authentication enabled on both instances.

**Comment by Simran-B** [comment]
@mtzonev Can you share the configuration of the nodes?

**Comment by mtzonev** [comment]
Sorry for the delayed reply, I was away.

Below are the configurations files of each instance and the agency. I've removed the default stuff that is commented out and only left the active values. I've replaced the IPs with placeholders but I made sure the original values were correct and matching before I masked them out.

**Instance 2 (Leader)**
```
[database]
directory = /var/lib/arangodb3/single

[server]
endpoint = tcp://[::]:8529
storage-engine = auto

authentication = false

statistics = true

uid = arangodb

[javascript]
startup-directory = /usr/share/arangodb3/js
app-path = /var/lib/arangodb3-apps

[log]
level = info
file = /var/log/arangodb3/arangod.log

[cluster]
my-address = tcp://INSTANCE_2_IP:8529
my-role = SINGLE
agency-endpoint = tcp://AGENCY_IP:8531

[replication]
automatic-failover = true
```

**Instance 3 (Follower)**
```
[database]
directory = /var/lib/arangodb3/single

[server]
endpoint = tcp://[::]:8529
storage-engine = auto

authentication = false

statistics = true

uid = arangodb

[javascript]
startup-directory = /usr/share/arangodb3/js
app-path = /var/lib/arangodb3-apps

[log]
level = info
file = /var/log/arangodb3/arangod.log

[cluster]
my-address = tcp://INSTANCE_3_IP:8529
my-role = SINGLE
agency-endpoint = tcp://AGENCY_IP:8531

[replication]
automatic-failover = true
```

**Agency**
```
[database]
directory = /data/arangodb3/agency

[server]
endpoint = tcp://[::]:8531
storage-engine = auto

authentication = false

statistics = true

uid = arangodb

[javascript]
startup-directory = /usr/share/arangodb3/js
app-path = /var/lib/arangodb3-apps

[log]
level = info
file = /var/log/arangodb3/arangod.log

[cluster]
my-role = AGENT

[agency]
my-address = tcp://AGENCY_IP:8531
size = 1
supervision = true
supervision-grace-period = 15
activate = true
endpoint = tcp://AGENCY_IP:8531
```
Right now I've disabled authentication everywhere but as soon as I enable it on the active lead the follower starts throwing the authentication error. Both instances are identical - the follower is a clone of the leader with only the IP changed in its config.

The exact same configuration was somehow working previously with enabled authentication, just one of the instances was a different machine (INSTANCE_1 which is now winding down and no longer used but has the exact same configuration and has been replaced by INSTANCE_3).

**Comment by mtzonev** [comment]
@Simran-B Did you ever had the chance to take a look at this?

**Comment by mtzonev** [comment]
I forgot to update this. I got it working in the end. The way to correctly pass the JWT secret via the configuration file is as follows:

```
[server]
authentication = true
jwt-secret = YOU_SECRET_HERE
```
This needs to be set on all instances - both agencies and singles.

Everything else in the snippets above is correct. I still have no idea how the original replication worked without this, maybe something changed between updates.
