### ISSUE TITLE
document() vs documents() parameters (_key and _id)

### ISSUE THREAD

**Issue by lewisdiamond** [arangodb/arangodb#1471]
document() takes either _key or _id while documents() takes only _key

The behavior of both should be the same, i.e. they both should take either _key or _id.

Furthermore, maybe you could deprecate 'documents()' and check the argument in document(), if it's an array, fetch all of them (not sure about the immutability).

**Comment by CoDEmanX** [comment]
I believe it's on purpose, because all documents must be in same collection.

**Comment by lewisdiamond** [comment]
That's find for `db._document()`, it should be the entire _id. `db.col.document()` has to be in the given collection but still accepts full _id.

**Comment by jsteemann** [comment]
I agree, `db.col.documents()` should also accept an array of documents `_id` values and not just an array of document `_key` values.

**Comment by jsteemann** [comment]
Fixed in devel.
