### ISSUE TITLE
Fatal error in ../src/runtime/runtime-typedarray.cc

### ISSUE THREAD

**Issue by allumbra** [arangodb/arangodb#1474]
I was iterating on a foxx api when I got this error.  Reverting my code and restarting hasn't helped unwedge Arangodb.  Any hints on how to recover?

Output in console:

# Fatal error in ../src/runtime/runtime-typedarray.cc, line 65
# CHECK(V8::ArrayBufferAllocator() != NULL) failed
#

==== C stack trace ===============================

#
# Fatal error in ../src/runtime/runtime-typedarray.cc, line 65
# CHECK(V8::ArrayBufferAllocator() != NULL) failed
#

==== C stack trace ===============================

 1: (0x108b0d000)1   ???                                 0x0000000108b0d000 0x0 + 4440772608

**Comment by allumbra** [comment]
The above console output is generated when refreshing the foxx app api page in the web console.  
http://localhost:8529/_db/ref/_admin/aardvark/standalone.html#applications/%2Fref

In the browser I see this message:

fetching resource list: http://localhost:8529/_db/ref/_admin/aardvark/foxxes/docs/swagger.json?mount=%2Fref

**Comment by allumbra** [comment]
This is version 2.6.7 running on osx

**Comment by jsteemann** [comment]
Cannot reproduce this myself, but added a potential fix that sets the `ArrayBufferAllocator` for V8.

**Comment by jsteemann** [comment]
Fix will be contained in 2.6.8.

**Comment by allumbra** [comment]
Reproducing the C stack trace:
I found out that I can reproduce the issue with including this line in my controller
`var zip = new require('node-zip')();`

This of course does not work in foxx - because of differences between foxx require and standard node require format.

When I specify the path like so:
`var zip = new require('node_modules/node-zip/lib/nodezip.js')();`

then I get a more typical error (regarding npm libs with dependencies)- which I still haven't discovered how to get around:

`2015-09-08T16:30:47Z [61961] ERROR [ArangoError 3100: cannot locate module
2015-09-08T16:30:47Z [61961] ERROR Path: jszip]
2015-09-08T16:30:47Z [61961] ERROR   at [object Object].Module.require (/Applications/ArangoDB-CLI.app/Contents/MacOS/opt/arangodb/share/arangodb/js/common/bootstrap/modules.js:1214:13)
2015-09-08T16:30:47Z [61961] ERROR   at args.require (/Applications/ArangoDB-CLI.app/Contents/MacOS/opt/arangodb/share/arangodb/js/common/bootstrap/modules.js:1367:21)
2015-09-08T16:30:47Z [61961] ERROR   at /Users/bcorliss/arangodb/apps/_db/ref/ref/APP/node_modules/node-zip/lib/nodezip.js:2:13
2`
....

**Comment by allumbra** [comment]
And...I found a write up regarding why I can't simply require just any node module.  Not sure if this explanation is somewhere to be found in the docs - but if it is - I missed it.
From http://jsteemann.github.io/blog/2015/08/01/how-v8-is-used-in-arangodb/
> Usage of modules

Both node.js and ArangoDB can load code at runtime so it can be organized into modules or libraries. In both, extra JavaScript modules can be loaded using the require function.

There is often confusion about whether node.js modules can be used in ArangoDB. This is probably because the answer is “it depends!”.

node.js packages can be written in JavaScript but they can also compile to native code using C++. The latter can be used to extend the functionality of node.js with features that JavaScript alone wouldn’t be capable of. Such modules however often heavily depend on a specific V8 version (so do not necessarily compile in a node.js version with a different version of V8) and often rely on node.js internals.

ArangoDB can load modules that are written in pure JavaScript. Modules that depend on non-JavaScript functionality (such as native modules for node.js) or modules that rely on node.js internals cannot be loaded in ArangoDB. As a rule of thumb, any module will run in ArangoDB that is implemented in pure JavaScript, does not access global variables and only requires other modules that obey the same restrictions.

ArangoDB also uses several externally maintained JavaScript-only libraries, such as underscore.js. This module will run everywhere because it conforms to the mentioned restrictions.

ArangoDB also uses several other modules that are maintained on npm.js. An example module is AQB, a query builder for AQL. It is written in pure JavaScript too, so it can be used from a node.js application and from within ArangoDB. If there is an updated version of this module, we use npm to install it in a subdirectory of ArangoDB. As per npm convention, the node.js modules shipped with ArangoDB reside in a directory named node_modules. Probably this is what caused some of the confusion.

**Comment by allumbra** [comment]
In case others are reading - the docs regarding this topic are not in the foxx section but here:
https://docs.arangodb.com/ModuleJavaScript/index.html

**Comment by jsteemann** [comment]
ArangoDB 2.6.8 is available for download. Can you check with this version if the problem persists? Thanks.
