### ISSUE TITLE
Arangob overwrites existing collection and leaves benchmark collection behind

### ISSUE THREAD

**Issue by CoDEmanX** [arangodb/arangodb#1475]
The optional `--collection` parameter can be used to specify the name of the collection for a benchmark. If a collection with that name exists in _system database already, it will be overridden without warning!

Furthermore, when the benchmark has finished, the collection used for the benchmark is kept in the _system database. It should be removed, shouldn't it?

**Comment by jsteemann** [comment]
It is intentionally left in there, because probably you want to use the data after the benchmark for further tests, or for inspections.
