### ISSUE TITLE
Add support for http-proxies to the simple http client

### ISSUE THREAD

**Issue by dothebart** [arangodb/arangodb#1477]
i.e. foxx-manager may fail if it has to pull apps via an http proxy. 
Its unclear how and when to support proxies, we most probably don't want to do this in the cluster case.

**Comment by CoDEmanX** [comment]
It needs a cluster case condition, consequently (alliterations are awesome!) :tada:

**Comment by jsteemann** [comment]
@CoDEmanX : so we should add some cluster case condition check code?

**Comment by CoDEmanX** [comment]
Confirmed! :smile:

**Comment by dothebart** [comment]
in certain situations it may not be feasible to directly access the outside world from foxx-manager or foxx services.
Several things should be considered herefore:
It should be either configurable via environment variables:
    export https_proxy=http://xx.xx.xx.xx:port
    export https_proxy=xx.xx.xx.xx:port
    export HTTPS_PROXY=http://xx.xx.xx.xx:port
    export HTTPS_PROXY=xx.xx.xx.xx:port
Or via regular configuration options.

A proxy request is different in two ways from a regular HTTP-request:
  - it connects the proxy host instead of the host in the URL
  - the GET/POST/... command not only contains the file URL, but the complete URL as its shown in the browsers location bar including http/https

This should only apply to non-cluster requests.

**Comment by pluma** [comment]
I'm closing this issue as our current plans are to replace foxx-manager with a standalone tool and the original problem that prompted this suggestion no longer exists (the foxx store will now only be refreshed when it is actually used rather than on every install).
