### ISSUE TITLE
Please mention projection & co. in Doc chapter 12.2 - Returning documents

### ISSUE THREAD

**Issue by legikaloz** [arangodb/arangodb#1480]
There is a nice blog post from Jan about returning OLD and NEW values from data modification queries, but the doc misses these possibilities.
http://jsteemann.github.io/blog/2015/03/27/improvements-for-data-modification-queries/

**Comment by jsteemann** [comment]
Thanks for the info. Have added the subsections to the documentation.
The changes will be merged back into the 2.7 branch with the stable release of 2.7.

**Comment by dothebart** [comment]
can be inspected in our nightly documentation builds: https://docs.arangodb.com/devel/
