### ISSUE TITLE
Arangorestore doesn't check content-type header before parsing server reply, misreacts to HTML output

### ISSUE THREAD

**Issue by givtnl** [arangodb/arangodb#14827]
## My Environment

* __ArangoDB Version__:        3.6.1 / 3.7.14 / 3.8.1
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   Kubernetes 
* __Configuration__:               Three instances of each behind Ingress
* __Infrastructure__:               DigitalOcean Kubernetes
* __Operating System__:        N/A
* __Total RAM in your machine__:  24 GiB
* __Disks in use__:        SDD
* __Used Package__:              Official Docker

## Component, Query & Data

__Affected feature__:
arangodump and aranogrestore

## Steps to reproduce

1. Dump data with arangodump from single instance running in Docker on Ubuntu 16.04
./arangodump --server.endpoint http+ssl://<server-url>:443 --server.authentication true --all-databases --output-directory dump --server.username root 
2. Restore data with arangorestore to cluster
arangorestore --server.endpoint http+ssl://<cluster-url>:443 --server.authentication true --all-databases --input-directory dump --server.username root --overwrite true --create-database --overwrite --log.level "debug"
3. 4 out of 5 collections are restored. The collection that isn't restored is the only collection that uses a "custom" _key wich is a string.

__Problem__:
For every version tried, the restore stops with Error "Expecting digit". 

__Expected result__:
Full restore successful. I'm expecting that this custom _key has something to do with it.

**Comment by givtnl** [comment]
This is the collection that fails
[data.zip](https://github.com/arangodb/arangodb/files/7235149/data.zip)

**Comment by givtnl** [comment]
I did some digging myself with lldb and I saw that the Parser (velocypack/src/Parser.cpp) is instantiated with a buffer "<html>\r\n<head><title>413 Request Entity Too Large</title></head>\r\n<body>\r\n<center><h1>413 Request Entity Too Large</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"

It seems like there's a bug somewhere where arangorestore is trying to parse the reply it received from the server. I will continue digging, but I just want to add that playing with the batch-size parameter doesn't help ...

**Comment by givtnl** [comment]
The 413 reply was from the nginx Ingress that is in front of the Kubernetes Arango Cluster.
After increasing the body size of the nginx Ingress, everything worked.
https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#custom-max-body-size

**Comment by dothebart** [comment]
Reopening, since arangorestore has to look for content-type headers to provide propper error messages to the end user.

**Comment by dothebart** [comment]
fixed by https://github.com/arangodb/arangodb/pull/14906
