### ISSUE TITLE
link in documentation broken

### ISSUE THREAD

**Issue by fceller** [arangodb/arangodb#1483]
See https://docs.arangodb.com/devel/GeneralHttp/index.html#cross_origin_resource_sharing_(cors

The link (see Cross Origin Resource Sharing requests_requests)) is broken.

**Comment by CoDEmanX** [comment]
Also, the markdown looks broken a little further down (literal asterisks again...)

`usage of the ArangoDB API (i.e. /_api/**) and the admin interface (i.e. /_admin/**) with HTTP authentication.`

**Comment by dothebart** [comment]
fixed by 5e259f4d14cbea4e94f2a906a84a17faa65fc375
