### ISSUE TITLE
How do you create a collection idempotently?

### ISSUE THREAD

**Issue by Qix-** [arangodb/arangodb#14835]
Getting a collection that doesn't exist will fail, but it also seems that `db.createCollection()` called on an existing collection will also fail.

In the case of a total datacenter recovery, or in a new datacenter initialization, or a migration, or whatever, there will be many services attempting to self-heal and bring the collections up to date, which might include creating (new) collections.

In Mongo, there was no difference between a "created" and "missing" collection. If you inserted a document into a "missing" collection, the collection was created automatically. This made writing fault-tolerant services trivial, at least in that regard (Mongo has a slew of other problems though).

However, in Arango, this is seemingly difficult/impossible to do correctly. I understand that there are different types of collections so automatic creation isn't really an option, but how are you supposed to go about doing this?

Creating collections manually isn't an option.

**Comment by Qix-** [comment]
@pluma Perhaps I'm mistaken but the JS client can absolutely do various things to improve this story:

- Standardize error codes
- Provide idempotent methods for creating collections
- Provide idempotent methods for creating indexes

**Comment by pluma** [comment]
The JS driver intentionally matches the HTTP API very closely and there is no atomic way to "upsert" collections. Creating indexes is already idempotent (which is why the method is called "ensureIndex" rather than "createIndex") because this is how the HTTP API works. Anything the JS driver could do by conditionally calling different HTTP API endpoints can be done in your application by calling different JS driver methods.

Changing which errors are returned by the HTTP API is out of scope for the JS driver. Re-implementing CLI tools like `arangorestore` is out of scope for the JS driver. You explicitly asked about changing the security features of ArangoDB itself, which is also out of scope for the JS driver.

**Comment by dothebart** [comment]
You should probably use a schema evolution tool like https://github.com/deusdat/arangomigo ? 
There also is: https://github.com/sleepycat/arango-tools

And tbh I really don't think that collections should be created on the fly during the application life cycle.

**Comment by Qix-** [comment]
> And tbh I really don't think that collections should be created on the fly during the application life cycle.

Why?

**Comment by dothebart** [comment]
Why? because of for security reasons and determineability of performance you don't want DDL operations during regular application requests.

To ensure graph integrity you also want to have the graph definition set before operating on them.

**Comment by Qix-** [comment]
> because of for security reasons

Which reasons? I fail to see how this is a security concern.

> determineability of performance

I don't see how an initial step to ensure the proper collections exist is a performance concern.

> To ensure graph integrity you also want to have the graph definition set before operating on them.

Right, this is the problem - without the ability to create collections properly at application boot time it requires an infrastructure script creates them when recovering from a failure or as a first-boot situation - or worse, during migrations. Doing this properly is a lot of extra overhead and thus a lot of extra surface area for failures or misconfiguration.

*That* is the real security concern.

> In order to optimize queries (like which shortcuts it may take, which indices it may use, which resources it must block) the schema has to be fixed by the time you run data operation.

Where is this performance concern documented? This isn't made clear on the Arango website unless I'm misunderstanding you.

**Comment by dothebart** [comment]
please have a look at:
https://www.arangodb.com/docs/stable/aql/execution-and-performance-optimizer.html

ArangoDB is built on the premise that data structures to work with exist at query parse time.

**Comment by dothebart** [comment]
Closing as answered.

**Comment by Qix-** [comment]
:shrug: No problem, I wasn't going to change any minds I don't think. Thanks for the response either way.

**Comment by dothebart** [comment]
I'm sorry, its simply not possible with arangodb's nature.
