### ISSUE TITLE
How to recover corrupt documents after upgrade to 3.7.15 and hard reset

### ISSUE THREAD

**Issue by brunoaduarte** [arangodb/arangodb#14846]
## My Environment

(ArangoDB 3.7.15 [linux] 64bit, using jemalloc, build tags/v3.7.15-0-gde9c21a1c7, VPack 0.1.33, RocksDB 6.8.0, ICU 64.2, V8 7.9.317, OpenSSL 1.1.1l  24 Aug 2021)

* __ArangoDB Version__:        3.7.15
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   ArangoDB Starter
* __Configuration__:               ----
* __Infrastructure__:               AWS
* __Operating System__:        Ubuntu 20.04
* __Total RAM in your machine__:        96 GB
* __Disks in use__:        SSD
* __Used Package__:              Ubuntu

Hello, I've accidentally corrupted my arango database today after doing the 3.7.15 upgrade.

After the restart, queries were acumulating and taking too long, so i tried to kill arangod service by doing

`sudo systemctl stop arangodb3`

but it didn't worked, stayed like that for a couple of minutes, so i killed the process

`kill -9 pid`

Now seems I have a corrupt database with some missing documents.
My spring application fails to query the data

`Oct 01 08:30:13 ip-172-31-72-80 sudo[3190]: com.arangodb.ArangoDBException: Response: 404, Error: 1202 - document not found`

And when I try to manually load the record from the database I can find it in the index

![00](https://user-images.githubusercontent.com/5354345/135591401-8c98d430-25a6-4c6d-87f3-f1ef58fce96e.png)

But when I click it , it says document not found

![01](https://user-images.githubusercontent.com/5354345/135591461-80dce4f1-1b72-4ea1-8a52-53f96627ff26.png)

I even tried replacing the document with a forced query

```
INSERT
{"_class":"com.model.Account","_id":"accounts/3356956195","_key":"3356956195","_rev":"_c908ORS---","createdAt":"2021-02-04T09:09:30.386Z"}
IN accounts
OPTIONS { overwrite: true,  overwriteMode: "replace"}
```

But also get error

`Query: AQL: NotFound: (while executing)`

Is there anyway to fix this ?
I need to remove the record from the index, so I can reinsert it.

**Comment by dothebart** [comment]
maybe manually deleting it via the `Documents` `DELETE` API in the swagger UI works? https://www.arangodb.com/docs/stable/http/

**Comment by brunoaduarte** [comment]
> maybe manually deleting it via the `Documents` `DELETE` API in the swagger UI works? https://www.arangodb.com/docs/stable/http/

Didn't worked...

`curl -X DELETE "http://localhost:8529/_db/database/_api/document/accounts/3356956195" -H "accept: application/json" -H "Authorization: bearer xxxxxxxxxxx"`

```
{
  "code": 404,
  "error": true,
  "errorMessage": "document not found",
  "errorNum": 1202
}
```

**Comment by brunoaduarte** [comment]
The solution was to dump the whole database and then restore it.

Thanks for the reply @dothebart
