### ISSUE TITLE
web interface issues

### ISSUE THREAD

**Issue by jsteemann** [arangodb/arangodb#1485]
When clicking the gears icon in the 2.7 web interface, the design looks broken, at least in Firefox 40.
See attached screenshot. The problem exists when clicking the gears icon in the **Collections** tab and all the other tabs.

![web-interface](https://cloud.githubusercontent.com/assets/1423118/9844727/08ee04c0-5ac6-11e5-8a14-9d4987c9cce2.png)

**Comment by CoDEmanX** [comment]
Same in Chrome 47. Looks to me like there's a CSS style missing to disable the default list bulletins.
