### ISSUE TITLE
viewing stats page in Aardvark seems broken for non-system DBs

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangodb#1487]
Viewing stats on `http://localhost:8529/_db/_system/_admin/aardvark/standalone.html` seems to work fine. However, if I switch to my other DB at `http://localhost:8529/_db/myotherdb/_admin/aardvark/standalone.html`, I'm seeing a 403 Error in the JS console for `http://localhost:8529/_db/myotherdb/_api/database` and the page seems to render the data from _system.

If I go to `http://localhost:8529/_db/myotherdb/_admin/aardvark/standalone.html` first, the stats page is blank.

This is with v2.6.8.

**Comment by dothebart** [comment]
@hkernbach is reproducible for one database on my system, not for all. if you fail to reproduce, connect me.

**Comment by hkernbach** [comment]
We've found the problem, it should be fixed in the current devel branch. Please confirm.
