### ISSUE TITLE
[Bug] Wrong execution plan - swapping inner with outer loops

### ISSUE THREAD

**Issue by konsultaner** [arangodb/arangodb#14875]
## My Environment

* __ArangoDB Version__:        Tested in 3.4.8, 3.7.3 and 3.8.1
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Operating System__:        Windows 10

## Component, Query & Data

__Affected feature__:
AQL query

__AQL query (if applicable)__:
```
FOR pathVertex IN UNION(["a","b"], ["c"])
FOR a IN Edge
    FILTER a._from == "test"
    LIMIT 1
    RETURN MERGE(DOCUMENT(a._to),{level:pathVertex})

```
__AQL explain and/or profile (if applicable)__:
```
Execution plan:
 Id   NodeType            Est.   Comment
  1   SingletonNode          1   * ROOT
  2   CalculationNode        1     - LET #2 = [ "a", "b", "c" ]   /* json expression */   /* const assignment */
 10   IndexNode              1     - FOR a IN Edge /* hash index scan, projections: `_to` */    
  3   EnumerateListNode      3       - FOR pathVertex IN #2   /* list iteration */
  7   LimitNode              1         - LIMIT 0, 1
  8   CalculationNode        1         - LET #6 = MERGE(DOCUMENT(a.`_to`), { "level" : pathVertex })   /* simple expression */   /* collections used: a : HasPlannedDish */
  9   ReturnNode             1         - RETURN #6
```

__Problem__:

The inner and outer loop are swapped! This is wrong and kills my query result randomly, depending on what element is found in the collection the first.

I found out that this is only the case if I use an edge collection and an index is selected:

```
Indexes used:
 By   Name   Type   Collection   Unique   Sparse   Selectivity   Fields        Ranges
 10   edge   edge   Edge false    false        24.00 %   [ `_from` ]   (a.`_from` == "test")
```

__Expected result__:
```
Execution plan:
 Id   NodeType            Est.   Comment
  1   SingletonNode          1   * ROOT
  2   CalculationNode        1     - LET #2 = [ "a", "b", "c" ]   /* json expression */   /* const assignment */
  3   EnumerateListNode      3     - FOR pathVertex IN #2   /* list iteration */
 10   IndexNode              1       - FOR a IN Edge /* hash index scan, projections: `_to` */    
  7   LimitNode              1         - LIMIT 0, 1
  8   CalculationNode        1         - LET #6 = MERGE(DOCUMENT(a.`_to`), { "level" : pathVertex })   /* simple expression */   /* collections used: a : HasPlannedDish */
  9   ReturnNode             1         - RETURN #6
```

**Comment by mpoeter** [comment]
You have a limit of one, but no sorting criterion, so there are no guarantees about which will be the first edge you get. I don't see how swapping the loops changes anything. Can you elaborate what exactly you are trying to achieve?

**Comment by konsultaner** [comment]
@mpoeter  I reduced the complexity of the original query to make it easy to understand, but I did a mistake. I reduced it too much. I'll try to make a better reproducer. With simple queries aql does what it should do.

**Comment by konsultaner** [comment]
I must have done something wrong... sorry
