### ISSUE TITLE
aardvark navigation bar broken when browser not wide enough

### ISSUE THREAD

**Issue by dothebart** [arangodb/arangodb#1488]
When the browser is half of my screen wide, the menubar next to the fruit doesn't render. Instead just a single dropdown is shown. Screen Resolution is: 1920x1200

**Comment by hkernbach** [comment]
What is half of your screen? I assume 1920, so maybe 960px. The navigation bar is compacted when screen size is below 799px. With a screen size below that value, the bar transforms to a select dropdown. But that is not a bug. There is just too less space to render it the normal way.

**Comment by hkernbach** [comment]
Cannot reproduce this exact behaviour. Anyway: I've lowered the min-width media settings a bit. So it could fit to your display again.
