### ISSUE TITLE
Out of memory situation during batch import

### ISSUE THREAD

**Issue by zopyx** [arangodb/arangodb#1491]
I am currently evaluating ArangoDB 2.67 (x64, 8 core, 8 GB RAM).

I am using the following Python script for doing batch insert operations

https://gist.github.com/zopyx/491c8be4b842da81be0d

After 65 iterations I received the following error from the backend. Although
the test is pretty artificial I would expect to be able to store an arbitrary amount
of batches with a constant insertion time. Insertion time per batch of 500k 
documents is about 5 seconds (which is fine) but I have also seen batch insertion
times going up to 50 seconds for a 500K batch.

65 6.13208007812
Traceback (most recent call last):
  File "test.py", line 23, in <module>
    coll.import_documents(docs)
  File "/home/ajung/src/python-arango/arango/collection.py", line 590, in import_documents
    raise DocumentsImportError(res)
arango.exceptions.DocumentsImportError: HTTP Method: post, URL: http://localhost:8529/_db/my_database/_api/import, HTTP Status Code: 500, Server Error Number: 4, Error Message: failed with error: out of memory

**Comment by weinberger** [comment]
ArangoDB is a mostly memory database.

https://www.arangodb.com/faq/#what-are-the-server-requirements-for-arangodb

Mostly memory from our point of view means that your working set should fit in RAM. As we use memory mapped files for the datafile, but normal memory for the indexes you need a correctly configured swap partition if your data set for the indexes is greater than your RAM. I assume that is the reason for the occurred error. At least this was the case, when I reproduced your test.

We think a mostly memory approach fits for a lot use cases but we observe also other use cases. This is the reason why we will also provide a plug-able storage engine in one of the next releases. Right now we evaluate possible solutions.
