### ISSUE TITLE
Suggestion: travisCI/setup_arangodb_2.6.sh: include timeout

### ISSUE THREAD

**Issue by aurelijusb** [arangodb/arangodb#1492]
Could not found repository for http://www.arangodb.com/repositories/travisCI/setup_arangodb_2.6.sh, so writing here.

**Problem**:
* When testing authentication it is very easy to loop TravisCI build forever.
* With `disable-authentication false` option `curl -s 'http://127.0.0.1:8529/_api/version' ` will never be successful, because version API also needs authentication.

**Possible solutions**
* Include timeout/retry count.
* Include authentication header.

**Context/examples**:
* https://travis-ci.org/aurelijusb/scarango/jobs/80304034#L4681
* https://github.com/aurelijusb/scarango/blob/master/src/test/travis/arangodb.sh#L54

**Comment by jsteemann** [comment]
The TravisCI setup scripts we ship start arangod with option `--server.disable-authentication true`, so this will become an issue only when the TravisCI scripts are locally modified for own test setups.
But I think including the timeout and the authentication header does no harm, so I will add this to the setup script soon. Thanks!

**Comment by jsteemann** [comment]
http://www.arangodb.com/repositories/travisCI/setup_arangodb_2.6.sh and http://www.arangodb.com/repositories/travisCI/setup_arangodb_2.7.sh have been updated accordingly.
