### ISSUE TITLE
A config property to disable auto-inference of `WITH` statement

### ISSUE THREAD

**Issue by wajda** [arangodb/arangodb#14927]
## My Environment

* __ArangoDB Version__:        3.8.1
* __Storage Engine__:             RocksDB

## Component, Query & Data

__Affected feature__: AQL

__Problem__:
Currently the keyword `WITH` is only required in a cluster-mode, as the [documentation](https://www.arangodb.com/docs/stable/aql/operations-with.html#usage) says:
> With RocksDB as storage engine, the WITH operation is only required if you use a cluster deployment and only for AQL queries that dynamically read from vertex collections as part of graph traversals.

The problem is that often the development machines or even CI environments don't run a cluster ArangoDB setup, but production ones do. Thus when developers forget to properly declare a collection in a `WITH` statement after making a modification to the AQL, it's very easy for the error to pass all automated tests on the dev environment and sneak into the production or pre-production environment where ArangoDB is actually running in a cluster mode.

__Expected result__:

It would very useful to have a config property to disable auto inference of the `WITH` statement, so that an AQL with an incorrect `WITH` declaration would fail consistently regardless of the ArangoDB deployment - cluster or non-cluster.

**Comment by dothebart** [comment]
Since the PR has been merged a while back, closing this as solved.
