### ISSUE TITLE
How do i compile arangodb to arm cpu?

### ISSUE THREAD

**Issue by DylanLyu** [arangodb/arangodb#1493]
How do i compile arangodb to arm cpu?
I tried all the methods on the site, have not compile into arm CPU
How to compile to ARM???

**Comment by dothebart** [comment]
Since the ARM-port is more or less here for development purposes only and requires propper alignment settings in the proc filesystem to work, are you shure that running it on an android is feasible in first place?

In general, we build these packages using cmake, which invoked via
make pack-arm
(in GNUmakefile)

**Comment by DylanLyu** [comment]
yes,It is run in the android platform
How can I do?

**Comment by dothebart** [comment]
ah, sorry. you first need to go into the 3rdParty directory, and run
make -f Makefile.v8-arm
make -f Makefile.libev-arm
make -f Makefile.zlib-arm
to compile the required dependencies.

**Comment by DylanLyu** [comment]
i try but this error
[3rdParty]$ make -f Makefile.v8-arm
mkdir -p ../ArmLibraries/lib
mkdir -p ../ArmLibraries/include/unicode
cp -a V8-4.1.0.27/out/arm.release/obj.target/tools/gyp/*.a ../ArmLibraries/lib
cp: V8-4.1.0.27/out/arm.release/obj.target/tools/gyp/*.a: No such file or directory
make: *** [install] Error 1

**Comment by dothebart** [comment]
ups. sorry once more. Its 
make -f Makefile.v8
then
make -f Makefile.v8-arm install

**Comment by DylanLyu** [comment]
oops!!this error

[3rdParty]$ make -f Makefile.v8
Makefile.v8:15: *** missing separator.  Stop.

**Comment by CoDEmanX** [comment]
Probably a white-space issue, see here:
http://stackoverflow.com/questions/16931770/makefile4-missing-separator-stop
http://stackoverflow.com/questions/10097193/error-in-make-command-makefile18-missing-separator-stop

**Comment by dothebart** [comment]
you need to use gnu-make.

**Comment by DylanLyu** [comment]
oops!!! i try debian linx but is error

root@debian:~/ArangoDB-2.6.8/3rdParty# make -f Makefile.v8
Makefile.v8:15: *** missing separator (did you mean TAB instead of 8 spaces?).  Stop.

**Comment by dothebart** [comment]
oops. I'm messing up the Windows and the ARM build - Usualy the jenkins does most of that for us these days, forgive me the confusion.
For ARM, you need configure & make to build V8, I've fixed the cookbook receipe.

**Comment by DylanLyu** [comment]
i try cookbook build ArangoDB but error

[ArangoDB-2.6.8]$ cd 3rdParty; make -f Makefile.v8-arm install
mkdir -p ../ArmLibraries/lib
mkdir -p ../ArmLibraries/include/unicode
cp -a V8-4.1.0.27/out/arm.release/obj.target/tools/gyp/*.a ../ArmLibraries/lib
cp: V8-4.1.0.27/out/arm.release/obj.target/tools/gyp/*.a: No such file or directory
make: *** [install] Error 1

**Comment by dothebart** [comment]
Sorry, I got distracted during compiling. (it takes a while and other tasks steal the priority) 
this step requires a complete configure/make to be completed in advance so the V8 has its files in `3rdParty/V8*/out/` else you will see these errors for the files missing.

**Comment by fceller** [comment]
@DylanLyu did you mange to compile? We also provide a package for Debian 8 on ARM:

   https://www.arangodb.com/download/

under raspberry

**Comment by 007huangliang** [comment]
Hi Experts:

Can you please help me on same issue? I am trying to compile on Ubuntu 14.04 with gcc/g++ 5.4 
Arango DB version is 2.8.11

Cmd I used:
./configure --host=x86_64 --build=arm-linux

Then try to get each lib:
jianjun@ubuntu:3rdParty$ make -f Makefile.zlib-arm 
mkdir -p ../ArmLibraries/include
mkdir -p ../ArmLibraries/lib
cp zlib-1.2.7/*.h ../ArmLibraries/include
cp zlib-1.2.7/*.a ../ArmLibraries/lib
cp: cannot stat ‘zlib-1.2.7/*.a’: No such file or directory
make: *** [install] Error 1
jianjun@ubuntu:3rdParty$ make -f Makefile.
Makefile.etcd        Makefile.libev-arm   Makefile.v8-windows
Makefile.libev       Makefile.v8          Makefile.zlib
Makefile.libev~      Makefile.v8-arm      Makefile.zlib-arm
jianjun@ubuntu:3rdParty$ make -f Makefile.v8
Makefile.v8          Makefile.v8-arm      Makefile.v8-windows
jianjun@ubuntu:3rdParty$ make -f Makefile.v8
Makefile.v8          Makefile.v8-arm      Makefile.v8-windows
jianjun@ubuntu:3rdParty$ make -f Makefile.v8-arm 
Makefile.v8-arm:5: *** commands commence before first target.  Stop.

Any ideas?

Thanks
