### ISSUE TITLE
Enable gzip compression on foxx service

### ISSUE THREAD

**Issue by patchimou** [arangodb/arangodb#14935]
## My Environment

* __ArangoDB Version__:        3.8.0

## Component, Query & Data

__Affected feature__:
Foxx

__Problem__:
I would like to send/receive compressed data on my foxx service.
For now I tried to send compressed data from my service but I haven't succeeded.
I tried:
 - setting headers before sending the response: `res.setHeader('Content-Encoding', 'gzip').send(result)` but I always end up with incorrect header check (tried with postman)
 - installing compression middleware and do 
 ```
const router = createRouter();
router.use(compression());
```
but even with just adding the node_modules containing the compression package, I end up with 
`ReferenceError: URL is not defined`.

Is it possible to do this compression ? And if it is, how can I achieve this ?

**Comment by patchimou** [comment]
> did you send the accept-encoding header with deflate / gzip ? 

Yes, actually postman put automatically the header `Accept-Encoding` with value `gzip, deflate, br`. I tried with only `gzip`, even with `*`, and still have the issue

**Comment by vcirizasodexo** [comment]
@dothebart Do you know if this issue has a chance of happening in ArangoDB Oasis?

**Comment by dothebart** [comment]
The PR was merged, this will be part of ArangoDB 3.10; closing.

**Comment by patchimou** [comment]
I'm reopening the issue.
I've updated my DB to version 3.10.6 and none of my initial solution is working.
Do you have an example on how to do this compression ?

Using compression library gives me the following error:
```
at SyntheticResponse.write (/var/lib/arangodb3-apps/_db/dev/arango-rest-service/APP/node_modules/compression/index.js:84:14)
via TypeError: this._implicitHeader is not a function
```

**Comment by dothebart** [comment]
one big problem is, that the zipping module doesn't have proper error reporting. So it may swallow i.e.  permission errors etc. and you only get a final error message.
This is not easy fixeable :-(
