### ISSUE TITLE
Don't show Foxx documentation for services without controllers

### ISSUE THREAD

**Issue by fceller** [arangodb/arangodb#1494]
When installing a Foxx util (e.g. `users-local`), the service page in aardvark shows

> Info
> Documentation for this service is not yet configured.

because there are no routes.

In this case it should simply show the README instead and not show the API docs at all.

**Comment by fceller** [comment]
The "swagger" service has a controller, but also shows this message.

**Comment by hkernbach** [comment]
Bug fixed. Readme is now rendered first if no documentation is available. Toggle button is disabled if no documentation is available.
