### ISSUE TITLE
The collections management of arangodb's web admin system does not support paginating

### ISSUE THREAD

**Issue by ageeye-cn** [arangodb/arangodb#14944]
## My Environment

* __ArangoDB Version__:        3.7.6
* __Deployment Mode__:       Single Server

My Arangodb database has over 1000 collections.The number of collections will be even larger in the future.The collections management of arangodb's web admin system does not support paginating.

**Comment by dothebart** [comment]
yes, thats a valid request, however, you're not the first to whish this, hence closing as duplicate of https://github.com/arangodb/arangodb/issues/9264
