### ISSUE TITLE
Optional configs log errors when set via aardvark

### ISSUE THREAD

**Issue by pluma** [arangodb/arangodb#1495]
If a Foxx service has optional configs, errors are logged for each optional config omitted during configuration. As these fields are optional, they shouldn't result in any messages.

This bug seems to exist in 2.6 as well.

**Comment by fceller** [comment]
Is this bug still present in 2.7?

**Comment by pluma** [comment]
I don't think this has been fixed yet. If it has, we should backport the necessary changes. If not, we still need to fix it in 2.8 (and then backport to 2.7 and maybe 2.6).

**Comment by pluma** [comment]
Confirmed in devel.

**Comment by pluma** [comment]
I have backported the fix to the 2.7 and 2.6 branches and adjusted the CHANGELOG in all three branches.

**Comment by dothebart** [comment]
do we need to adjust documentation here?

**Comment by pluma** [comment]
I don't see how this issue affects the documentation. The bug was that false error messages would show up in the log, the behaviour itself was never affected.
