### ISSUE TITLE
custom joi not working anymore

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangodb#1496]
For the longest time, my Foxx app had it's own (newer) version of joi. It was working perfectly until yesterday and I can't figure out what broke it. Not reverting my code, nor switching back to older versions of ArangoDB, nor installing older versions of joi gets it back into a working state.

It starts of with `ArangoError 3100: cannot locate module`, followed by several `ArangoError 3103: failed to invoke module`. Details: https://gist.github.com/pekeler/48edd2efadcd59fca0ce

Note: it's not a big deal because the version of joi included with the latest ArangoDB is recent enough for my needs, but I'd like to understand what's going on here.

**Comment by dothebart** [comment]
Can you retry with the arangodb 2.7 alpha? We recently fixed exactly those problems about error reporting when loading foxx modules so you should see the original error too instead of only 'cannot load module'

**Comment by jsteemann** [comment]
It looks like the isemail validator requires the `dns` module, at least it tries to include it.
It seems to be coming from here: `./foxx/_db/myapp/myapp/APP/node_modules/joi/node_modules/isemail/lib/isemail.js)`. Can you check whether that actually requires a module named `dns` and if it is there in any JavaScript file?

**Comment by pekeler** [comment]
Thanks @jsteemann - I think I understand now:

- ArangoDB does not have a dns module, node does https://nodejs.org/api/dns.html
- one of joi's dependency is `"isemail": "1.x.x"` (since joi 4.6.0 from June 2014)
- isemail used to lazy require('dns') only when needed until v1.1.1
- as of isemail v1.1.2 (September 12, 2015), it is always requiring dns, and therefore breaking in ArangoDB
- this wouldn't happen if I used https://docs.npmjs.com/cli/shrinkwrap

I guess you'll run into the same problem next time you'll build a new version of ArangoDB in an environment that doesn't already have joi with the older version of isemail installed. It would npm-install joi which would get the latest isemail which would break all Foxx apps.

@dothebart : I'll report back once I've had the chance to play with 2.7.

**Comment by jsteemann** [comment]
@pekeler : thanks for the note about `isemail`!

**Comment by pluma** [comment]
@pekeler I'll add a stub module to make isemail happy. Of course actual validation via DNS will still fail but as far as I can see that is entirely optional.

**Comment by pekeler** [comment]
@pluma thanks for adding the stub! You might also want to consider shrink-wrapping `js/node/package.json` to prevent similar problems in the future.
(depending on a new version of joi was still a left over from using ArangoDB 2.5 which bundled a too old version of joi - I know I can get rid of it now)

**Comment by pluma** [comment]
The dns stub has landed in devel via the require-sanity branch (along with stubs for most other missing modules).

I'm still not sure why you needed to run `npm install` in ArangoDB itself. We should look into using npm shrinkwrap the next time we bump our deps, but for now I would consider this issue resolved.
