### ISSUE TITLE
Documentation: SUBSECTIONs not resolved in PDF / ePUB

### ISSUE THREAD

**Issue by CoDEmanX** [arangodb/arangodb#1497]
Everything looks fine here:
https://docs.arangodb.com/devel/NewFeatures/NewFeatures27.html

But if you look at the PDF or ePUB, you'll see that a lot of `!SUBSECTION` markers aren't returned into headlines, some are however.

![subsection_not_resolved](https://cloud.githubusercontent.com/assets/1309249/9933237/e62fb916-5d49-11e5-9861-5f840745de5f.png)

Markup looks okay, so not sure what is causing this:
https://github.com/arangodb/arangodb/blob/devel/Documentation/Books/Users/NewFeatures/NewFeatures27.mdpp

**Comment by dothebart** [comment]
thanks for spotting.

**Comment by dothebart** [comment]
oh, the gitmirror delay caught me in the act. now its fixed, fresh pdf online.

**Comment by CoDEmanX** [comment]
It's fixed (thanks!), but there's another issue with the title: the version reads `vdevel`, but should be `2.6.0-devel` or `2.7.0-devel`. Online docs also affected.

**Comment by CoDEmanX** [comment]
The process module docs look pretty empty, is that intentional?
https://docs.arangodb.com/devel/ModuleProcess/index.html
