### ISSUE TITLE
Could not connect to endpoint 'tcp://127.0.0.1:8529', database: '_system', username: 'root'

### ISSUE THREAD

**Issue by vijaya-lakshmi-venkatraman** [arangodb/arangodb#14984]
## My Environment

* __ArangoDB Version__: 3.8.1       
* __Storage Engine__:  RocksDB           
* __Operating System__:  Linux 

## Component, Query & Data

__Affected feature__: arangosh

## Steps to reproduce

1. Build image
2. Create instance `docker run -e ARANGO_RANDOM_ROOT_PASSWORD=1 -d --name arangodb-instance arangodb`
3. Execute `docker run -it arangodb arangosh`

Reference : https://hub.docker.com/_/arangodb/

__Problem__:
Could not connect to endpoint 'tcp://127.0.0.1:8529', database: '_system', username: 'root'
Error message: 'Unable to connect'

__Expected result__:
DB should be connected

**Comment by vijaya-lakshmi-venkatraman** [comment]
I see the below error in the docker logs:
WARNING [ba733] {syscall} cannot raise the file descriptors limit to 8192: Invalid argument
WARNING [ba733] {syscall} cannot raise the file descriptors limit to 65535: Invalid argument

**Comment by sivaramsk** [comment]
docker ulimits should be set at the service level - refer https://docs.docker.com/engine/reference/commandline/dockerd/#default-ulimit-settings

**Comment by vijaya-lakshmi-venkatraman** [comment]
Closing this issue as image v3.7.15 is successfully creating a container
