### ISSUE TITLE
where are stored the queries (like views)

### ISSUE THREAD

**Issue by juanremi** [arangodb/arangodb#15018]
Hi, 

i dump all my databases and when i mount the new server and restore the backups, i didnt see my saved queries

where are stored and how can i read these queries and export them and restore too

thanks

**Comment by juanremi** [comment]
In the old server:
web dashboard > queries > export queries 

In the new server:
web dashboard > queries > import queries 

but, this chould be performed via cli?

**Comment by dothebart** [comment]
did you dump / restore with [include-system-collections](https://www.arangodb.com/docs/stable/programs-arangodump-options.html) ?

**Comment by dothebart** [comment]
so we have solved this successfully?
