### ISSUE TITLE
How to Stop ArangoDB server from commandline or from C# application

### ISSUE THREAD

**Issue by sachindu** [arangodb/arangodb#15016]
Killing the arangoDb process is leading to corrupt DB .. so i do not want to use windows process.Kill()

I am starting arangodb with using following code :

 Process arangoDBProcess = null;

           string arangoDBPath = System.IO.Path.Combine(ApplicationArangoPath, @"usr\bin\arangod.exe");
            if (System.IO.File.Exists(arangoDBPath))
            {
                try
                {
                    // Start the ng serve process using npm start
                    arangoDBProcess = new Process
                    {
                        StartInfo = new ProcessStartInfo
                        {
                            FileName = arangoDBPath,
                            UseShellExecute = false,
                            CreateNoWindow = true
                        }
                    };
                    // Start process

                    arangoDBProcess.Start();

**Comment by mpoeter** [comment]
On Linux you usually send SIGTERM to the process; on Windows this is roughly equivalent to terminating a process with Ctrl-C. However, sending Ctrl-C to another process programmatically is unfortunately a bit more complex. See this blog post for an example: https://blog.codetitans.pl/post/sending-ctrl-c-signal-to-another-application-on-windows/

**Comment by dothebart** [comment]
please note that you also can use HTTP with `DELETE /_admin/shutdown` to trigger a proper shutdown. 

[We should have it documented in the admin section](https://www.arangodb.com/docs/stable/http/administration-and-monitoring.html), [However, its only noted in the release notes](https://www.arangodb.com/docs/stable/release-notes-upgrading-changes30.html#administration-apis)
