### ISSUE TITLE
Is serverless MacrometaDB using Arango structure?

### ISSUE THREAD

**Issue by doorkey** [arangodb/arangodb#15017]
Macrometa API and documentation look exactly like ArangoDB. Does that mean we can port to Macrometa without rewriting our APIs?

Any news on the Serverless instance of Arango? :) Thank you so much

**Comment by dothebart** [comment]
I don't know the Macrometa API and documentation; Could it be that they use [SwaggerUI](https://swagger.io/tools/swagger-ui/) for their REST API description as we do?
However, its an http based API.

**Comment by dothebart** [comment]
closing as answered.
