### ISSUE TITLE
index base on function or expression, index on multiple fields

### ISSUE THREAD

**Issue by ra0o0f** [arangodb/arangodb#1501]
hello

since ArangoDB uses json to store documents, developers can model their data more complex than column oriented databases. this brings problems of indexing the complex data structure.

ArangoDB have several index types that address this problem, how about adding an index that is based on an expressioin which also can returns multiple index records output:

``` javascript
//an example would be:
db.messages.ensureExpressionIndex("indexId",function(m){
return m.files.map(f=>f.fileKey)
.concat(m.images.map(i=>i.imageKey))
.concat([m.defaultImage]);
});

// query like
for m in messages
// this will use index
filter ['files/123','images/549'] in index("indexId")
// this wont
and m.creation > '2015-1-1...'
```

it can be used for fulltext search #484 and lists #278 
with this developers can model their data without worrying about how to query it fast

if you are interested there is function-based-indexes that oracle uses for index base on expression, it seems the optimizer can guess to use which index base on query
https://oracle-base.com/articles/8i/function-based-indexes

thanks for your great product

**Comment by dothebart** [comment]
We're currently working on indexing array items. This however will not be ready until the 2.7 release.

**Comment by CoDEmanX** [comment]
If I understand correctly, an array index `attr[*]` will place every element of `attr` in the index individually:

    {attr: [1, 2]} // doc1
    {attr: [3, 4, 5]} // doc2
    // index contains: 1, 2, 3, 4, 5 (as opposed to [1,2] and [3,4,5])

It gets more interesting however, if the indexed array contains objects. An array index `attr[*].subattr` would index the `subattr` values of every element in `attr` individually:

    {attr: {subattr: 1, other: "foo", yesno: true}}
    {attr: {subattr: 2, other: "bar", yesno: false}}
    // index contains: 1, 2

I wonder what would happen for the following two indexes however:

1. `attr[*]` on above documents - will it ignore the nested objects, or will it index **all** their attribute values? (index: 1, foo, true, 2, bar, false)
2. Will it be supported to create combined array indexes à la `attr[*].subattr, attr[*].other`, so on a subset of the nested objects' attributes? (index: 1, foo, 2, bar)

**Comment by jsteemann** [comment]
Re 1: an index on `attr[*]` should ignore this document `{attr: {subattr: 1, other: "foo", yesno: true}}` because the `[*]` will ignore all attributes that are not arrays. However, it should be possible to create an index on nested properties, e.g. `attr[*].subattr`.
Re 2: the plan is to support this.

Please note that work on the array indexes is still ongoing and not yet finished. The 2.7 release will not contain them, because there is already the 2.7 branch and the feature is "too big" to merge it back into a stable branch when implementation is finished.

**Comment by CoDEmanX** [comment]
Correction: above documents should had looked like the following:

```js
{ attr: [ {subattr: 1, other: "foo", yesno: true}, {subattr: 2, other: "bar"} ] }
{ attr: [ {subattr: 3, other: "baz", yesno: false} ] }
// array index attr[*]: 1, foo, true, 2, bar, 3, baz, false
// array index attr[*].subattr, attr[*].other: 1, foo, 2, other, 3, baz
```

so objects nested in arrays. Nonetheless, combined indexes on object attributes without surrounding array are just as useful.

**Comment by baslr** [comment]
👍 for the expression / function based index creation. I think it doesn't need another index to perform the value modification before the value is indexed.

**Comment by Simran-B** [comment]
Related: https://stackoverflow.com/questions/44731372/computed-field-in-arangodb

**Comment by dothebart** [comment]
With ArangoDB 3.10 we relaesed (Computed values](https://www.arangodb.com/docs/stable/data-modeling-documents-computed-values.html] which can as well be indexed.
So this implements this feature request. 
Sorry for putting together this issue and that feature so late in the release cycle ;)
