### ISSUE TITLE
Does arangodb setup dpkg trigger on apt-get install ?

### ISSUE THREAD

**Issue by dagarwal82** [arangodb/arangodb#1504]
Hello, 

I have arangodb installed and running fine. I am now trying to use apt-get install pstack (or any other program) it fails with "Setting up arangodb (2.6.2) ...
 * Starting arango database server arangod                                                                                                                                                   2015-09-21T20:49:27Z [11915] FATAL cannot start server: database directory is locked
More error details may be provided in the logfile '/var/log/arangodb/arangod.log'
 * database version check failed, maybe need to run 'upgrade'?
invoke-rc.d: initscript arangodb, action "start" failed.
dpkg: error processing package arangodb (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 arangodb
E: Sub-process /usr/bin/dpkg returned an error code (1)
"

Does arangodb setup dpkg triggers ?

**Comment by dothebart** [comment]
In case of installing a newer arangodb version it is intended that `--upgrade` has to be run by hand. You may eventualy want to prepare such an upgrade by doing a lvm snapshot or triggering a backup.

After that you can finish the setup like that:
Stop arangodb again, and use 

    dpkg --pending --configure 

to re-invoke the config scripts. After that the package database will have set the arangodb package to configured, and will not invoke it unless you upgrade to the next arangodb version (again).
