### ISSUE TITLE
API endpoint for healthcheck

### ISSUE THREAD

**Issue by razvanphp** [arangodb/arangodb#1506]
Hello,

As we want to include arangodb in our monitoring solution, we need a HTTP endpoint to check the health of the server. I was thinking we can use the `/_api/version` endpoint, but unfortunately it is (strangely) tied to one database, and it requires basic auth, something that I would avoid providing to a monitoring tool.

Is there another endpoint that I can use? Or maybe this version one can be opened and made server global? I would guess this is needed by the future cluster features too.

Thank you!

**Comment by hkernbach** [comment]
+1

**Comment by pekeler** [comment]
How about the opposite approach: have ArangoDB emit a remote heartbeat. If the heartbeat stops, you know something is wrong. You could automatically monitor the heartbeat with a watchdog timer such as [WDT.io](https://wdt.io/). No need to expose a new API endpoint, no worries about authorization.

I just created a foxx-app to do that: https://github.com/pekeler/foxx-heartbeat

This could possibly be improved by only emitting the heartbeat if the latest document in the statistics collection looks healthy.

**Comment by jsteemann** [comment]
I think the best would be to allow user-definable Foxx apps to be installed under URL prefix `/_open`, which will not require authentication. A user-definable Foxx app can then return any data relevant for monitoring **without** authentication. Which data is returned is then up to the person that writes the Foxx app.
Alternatively, we could provide a default route underneath `/_open` which would simply return static data (e.g. `{"ok":true}` so the caller can just be sure the server responds, but it shouldn't give away any sensitive data obviously.

**Comment by jsteemann** [comment]
There seems to be a simple way to achieve this in 2.6 & before:
By inserting a document into the `_routing` collection it is possible to add new routes. If the route path starts with `/_open/`, then it will be unauthenticated. For example, the following insert statement will create a route that returns a static JSON document when calling URL part `/_open/health.json`:
```js
db._routing.save({ "url": "/_open/health.json", content: { body: '{"ok":true}' } });
```
This route will be registered in the database the statement is executed, so when registered in the `_system` database and the checks are for 127.0.0.1, the monitoring command would be
```
curl -X GET http://127.0.0.1:8529/_db/_system/_open/health.json --dump -
```

**Comment by jsteemann** [comment]
Just added in devel branch that Foxx applications can be installed underneath `/_open/`, so now any Foxx app can be installed there that returns customized-data for monitoring purposes, without requiring authentication.

**Comment by jsteemann** [comment]
Are the above suggestions sufficient? If yes, we should close this issue.
