### ISSUE TITLE
Graph doesn't connect all nodes

### ISSUE THREAD

**Issue by dothebart** [arangodb/arangodb#1509]
Load the example social example graph:

    var examples = require("org/arangodb/graph-examples/example-graph.js");
    var graph = examples.loadGraph("social");

Open the Graphviewer, Its 4 edges, and 4 vertices.
However, a random subset of the nodes and their connections is shown on each reload.

Sometimes one of the girls is disconnected but displayed, sometimes only one girl and two guys are shown.

**Comment by hkernbach** [comment]
there seems to be a bug regarding outbound/any relations. We have to discuss.

**Comment by hkernbach** [comment]
feature request. https://github.com/arangodb/arangodb/issues/1542
