### ISSUE TITLE
Fix bug in the user app's storage in resolve function

### ISSUE THREAD

**Issue by easyping** [arangodb/arangodb#1510]
When registering users on the users.Create came in routine storage of error "Can not read property 'get' of null." 
This I have resolved by an extension of if.
js / apps / system / _system / users / APP / storage.js line 34:
instead 
    if (user.get! ('_ key'))
Now 
   if (user === null || user.get! ('_ key'))

**Comment by jsteemann** [comment]
Thanks. Fixed in devel & 2.6 (2.7 will be fixed automatically & eventually when the devel branch is merged back into it).
