### ISSUE TITLE
GRAPH_SHORTEST_PATH does not return all shortest paths

### ISSUE THREAD

**Issue by dylanclewis** [arangodb/arangodb#1511]
The documentation for this function states: "The GRAPH_SHORTEST_PATH function returns all shortest paths of a graph." I have a very simple graph with four vertices where there are two paths of distance 2 from the first to the fourth vertex and I only ever get one path returned. I have tried this with and without a weight property where the weights were equal and I always only get one path returned.

This is the query used:

FOR e in GRAPH_SHORTEST_PATH("ratingGraph",
			"rahasya_users/TestAverageTrustedConnectionRatings1",
			"rahasya_users/TestAverageTrustedConnectionRatings4",
			{
				direction : "outbound",
				edgeCollectionRestriction: "rahasya_ratings",
				startVertexCollectionRestriction: "rahasya_users",
				endVertexCollectionRestriction: "rahasya_users",
				weight: "rating"
			})
			RETURN e

The vertices:

[{"_id":"rahasya_users/TestAverageTrustedConnectionRatings1","_key":"TestAverageTrustedConnectionRatings1","_rev":"78627903","lat":0,"lon":0,"olat":0,"olon":0,"quality":0,"updated":0,"radius":0,"systemrating":0,"minvis":0,"nick":"TestAverageTrustedConnectionRatings1"},{"_id":"rahasya_users/TestAverageTrustedConnectionRatings2","_key":"TestAverageTrustedConnectionRatings2","_rev":"78890047","lat":0,"lon":0,"olat":0,"olon":0,"quality":0,"updated":0,"radius":0,"systemrating":0,"minvis":0,"nick":"TestAverageTrustedConnectionRatings2"},{"_id":"rahasya_users/TestAverageTrustedConnectionRatings3","_key":"TestAverageTrustedConnectionRatings3","_rev":"79152191","lat":0,"lon":0,"olat":0,"olon":0,"quality":0,"updated":0,"radius":0,"systemrating":0,"minvis":0,"nick":"TestAverageTrustedConnectionRatings3"},{"_id":"rahasya_users/TestAverageTrustedConnectionRatings4","_key":"TestAverageTrustedConnectionRatings4","_rev":"79414335","lat":0,"lon":0,"olat":0,"olon":0,"quality":0,"updated":0,"radius":0,"systemrating":0,"minvis":0,"nick":"TestAverageTrustedConnectionRatings4"}]

The edges:

[{"_id":"rahasya_ratings/80135231","_key":"80135231","_rev":"80135231","_from":"rahasya_users/TestAverageTrustedConnectionRatings1","_to":"rahasya_users/TestAverageTrustedConnectionRatings2","rating":0.91},{"_id":"rahasya_ratings/80528447","_key":"80528447","_rev":"80528447","_from":"rahasya_users/TestAverageTrustedConnectionRatings1","_to":"rahasya_users/TestAverageTrustedConnectionRatings3","rating":0.91},{"_id":"rahasya_ratings/80921663","_key":"80921663","_rev":"89572415","_from":"rahasya_users/TestAverageTrustedConnectionRatings2","_to":"rahasya_users/TestAverageTrustedConnectionRatings4","rating":0.4},{"_id":"rahasya_ratings/81314879","_key":"81314879","_rev":"81314879","_from":"rahasya_users/TestAverageTrustedConnectionRatings3","_to":"rahasya_users/TestAverageTrustedConnectionRatings4","rating":0.4}]

**Comment by dothebart** [comment]
The behaviour of this has changed with 2.6 for performance reasons: https://docs.arangodb.com/Upgrading/UpgradingChanges26.html 
You're right, the Documentation doesn't reflect this properly.

**Comment by dylanclewis** [comment]
Is there an alternative you can suggest where I can get all shortest paths, not just the first that is found?

**Comment by dylanclewis** [comment]
I would also like to comment that the result is structured incorrectly for a single path result as it uses a two dimensional array for the edges. Only a single dimensional array would be needed for a single path result.

**Comment by dothebart** [comment]
Yes, thats intentional, since if you change the grammer of an interface, all the clients need to be adjusted and evenually handle two structural ways.
The way its now an old client will work with the new output without changes.

**Comment by mchacki** [comment]
@dylanclewis The result format with Array of Array is due to the fact, that GRAPH_SHORTEST_PATH can get a set of vertices as start and as endpoints (either as Array or as example object).

So we can f.e. execute:
```
GRAPH_SHORTEST_PATH("graph", {root: true}, {leaf: true})
```

Which will compute all shortest path between all root-nodes and all leaf-nodes. This will result in a two dimensional array, one for every root --> leaf combination.
If there is exactly one root and one leaf in the graph (by accident) it would be unpredictable for the client if this would now return a single dimensional array, which would indeed be enough.

Right now there is not yet an easy alternative for multiple shortest paths, but i like the idea and will add an issue to allow a flag in SHORTEST_PATH computation to calculate more than one path.

**Comment by dylanclewis** [comment]
@mchacki Thanks for the reply, I do need reminding every now and then that the example parameter has many forms and can return multiple results.
