### ISSUE TITLE
Arrango DB - Power BI connector throws 503 error 

### ISSUE THREAD

**Issue by chaitanya2593** [arangodb/arangodb#15116]
## My Environment

* __ArangoDB Version__:        
* __Infrastructure__:               Power BI Oct 2021 release 
* __Operating System__:         Windows 10 
* __Total RAM in your machine__:       16Gb. 

We have been using the Arrango DB for a while. As per the recent requirement, we are developing Dashboards Power BI. As per the instructions in the Power Bi - Arrango DB interaction Guide we have created connectors and are able to access the data. But after certain days(roughly 30 days of usage) when we are receiving the error "(503): Service Unavailable" when trying to connect to the Connector. We tried creating a new connector but after a few days, we have encountered a similar issue.

We are unable to understand the root cause for the issue. For working with dashboards we can create new connectors but it is quite not easy to update the data source in all the dashboards. We are not sure if the issue linked with Powe Bi releases

FYI:: we also have tried re-creating the connector with the same configuration of an issue connector. But still, we get 503 error

## Steps to reproduce

1. Create a Power Bi Connector - Arrango connector and configure it with the Power BI desktop app.
2. After usage for close to 30 days one should face the "(503): Service Unavailable" 
3. Even though a new connector  with the same configuration is created the issue still exists

Thanks in advance and please let me know if you need any information from our end.

**Comment by chaitanya2593** [comment]
Recently we are able to find solve this problem. The root cause of the issue is the change in the name of the collections, the code of the connector checks the existence of all the collections defined in the list and if the collection is missing then we get the 503 Service unavailable. So even a small change in the collection name spelling (even the case) might trigger this error.

**Comment by dothebart** [comment]
Hi, 
thanks for comming back to us.
