### ISSUE TITLE
ArangoDB Cluster Problem

### ISSUE THREAD

**Issue by Madmancj** [arangodb/arangodb#1512]
Hi,
Recently i was trying to setup a development cluster on my local machine, and suddenly as soon as i try to create a cluster through web interface, i get this error stating "Error while creating the cluster, Unauthorized".
Why is it saying unauthorized?

**Comment by dothebart** [comment]
did you change your database? Some operations are only possible as long as you're in the _system database.

**Comment by Madmancj** [comment]
I have multiple databases. But clustering is done on _system database only.

Also i was able to build the cluster the first time, but it kept asking for username and password repeatedly with title "Coordinator User invalid", and is not accepting the default username and password.

**Comment by fceller** [comment]
@Madmancj were you able to solve this issue or is it still open?

**Comment by Madmancj** [comment]
It was showing problems on multiple database. However it worked well with just one database.
I will check the same for 2.7.0
Thanks.
