### ISSUE TITLE
Array variant not valid for all comparison operators in AQL statement

### ISSUE THREAD

**Issue by Moortiii** [arangodb/arangodb#15128]
## My Environment

* __ArangoDB Version__: 3.7.2
* __Storage Engine__: RocksDB
* __Deployment Mode__: Single Server
* __Deployment Strategy__: Manual Start in Docker
* __Configuration__:   Not relevant
* __Infrastructure__:   Not relevant
* __Operating System__:  Debian 10
* __Total RAM in your machine__:  32Gb
* __Disks in use__: 1TB SSD
*  __Used Package__:   Not relevant.

## Component, Query & Data

__Affected feature__:

Array comparison operators for AQL statements.

__AQL query (if applicable)__:
```
RETURN ["192.168.0.1", "192.168.0.2", "10.0.0.1"] ANY LIKE "192.168.0.%"
```
__AQL explain and/or profile (if applicable)__:

Not applicable (or possible, due to crash).

__Dataset__:

Not relevant, can be reproduced without data in the database.

__Size of your Dataset on disk__:

Not relevant.

__Replication Factor & Number of Shards (Cluster only)__:

Not relevant.

## Steps to reproduce

1. Navigate to the query console on an ArangoDB instance
2. Create a query as listed above with `FILTER ANY/NONE/ALL LIKE`

__Problem__:

The search is unable to be executed, reported as invalid syntax.

__Expected result__:

The search should be executed, since the docs do not specify any exceptions for which comparison operators the array variants can be prefixed with.

__Further notes__:

Based on my own testing it appears that `ANY/ALL/NONE` cannot be used with `=~`, `!~` nor `LIKE`.

I spoke to `tobias.arangodb` on the Slack channel which says this might be an oversight. If it is intentional, the documentation should be updated to reflect which operators can be prefixed with an _array variant_.

The syntax of such a statement is also up for debate. See the use cases below.

_Similar to how `ANY IN` works_:

```javascript
// In a FILTER scenario we could replicate this using multiple statements
RETURN ["192.168.0.1", "192.168.0.2", "10.0.0.1"] ANY LIKE ["192.168.0.%", "10.0.0.%"]
```

_Similar to how `ANY ==` works_:

```javascript
// Since RHS expects a single value, we would need multiple FILTER statements to make this work
RETURN ["192.168.0.1", "192.168.0.2", "10.0.0.1"] ANY LIKE "192.168.0.%"
RETURN ["192.168.0.1", "192.168.0.2", "10.0.0.1"] ANY LIKE "10.0.0.%"
```

**Comment by dothebart** [comment]
Hi,
ArangoDB 3.7.15 is available for download; Please upgrade to that version, and check back whether the issue persists.

**Comment by Simran-B** [comment]
Basically a duplicate of https://github.com/arangodb/arangodb/issues/10372

**Comment by Moortiii** [comment]
Thanks for the link. I do think the documentation should be updated to reflect this seeing as it's been a known issue since November 2019 - I'll see if I can't carve out some time to do it myself.
