### ISSUE TITLE
V8 upgrade to 4.7

### ISSUE THREAD

**Issue by CoDEmanX** [arangodb/arangodb#1513]
I took a look at the [API change log of V8](https://docs.google.com/document/d/1g8JFi8T_oAE_7uAri7Njtig7fKaPDfotU6huOa1alds) and spotted a couple breaking changes that appear to affect ArangoDB:

- Allow for accessing an ArrayBuffer contents without externlizing it

        fast_buffer->SetIndexedPropertiesToExternalArrayData(

    https://codereview.chromium.org/1092923002/diff/1/src/api.cc#oldcode4282

- Deprecate IdleNotification

        bool rc = isolate->IdleNotification(idleTimeInMs);

- Remove support for malloc'd typed arrays (?)

        v8::V8::SetArrayBufferAllocator(&_bufferAllocator);

- Deprecate v8::Handle

- Deprecate Isolate::New without parameters

Some of them seem to require quite some work. On the plus side, there are many more ECMA2015 features in v4.7. There are also performance improvements, but not sure how much can be gained by a finer grained GC in ArangoDB. The main purpose is apparently real-time rendering in Blink/Chrome. MSVS2015 support is apparently just a change to gyp as of now to suppress warnings.

[Custom Snapshots](http://v8project.blogspot.de/2015/09/custom-startup-snapshots.html) (supported since 4.3) will not be of any use if I understand correctly, because there's only a single Isolate per server-instance (and not on a per-query basis).

**Comment by dothebart** [comment]
Regarding the custom snapshots: the server has a fixed set of isolates; they're built on startup and filled with all the initialization and library code (which takes quiet a while). An AQL query or a FOXX-route fetches one of them from the pool (if required).

**Comment by jsteemann** [comment]
We'll be affected by Isolate::New() without parameters. This can be fixed easily however, by passing v8::CreateParams to this function.
We'll also be affected by v8::Handle being deprecated. But presumably this change is easy. All 9xx occurrences can be changed to v8::Local instead. This looks like simple search & replace.
The ArrayBufferAllocator stuff seems to have been moved from a platform-wide thing into an Isolate-specific setting. I think it's now set via an Isolate's CreateParams, but this needs validation.
It looks like the two existing IdleNotification methods were replaced with a unified IdleNotificationDeadline. That change should be simple.

That leaves the SetIndexedPropertiesToExternalArrayData and friends as the **presumably** only change that require more effort. 
Plus all the unknowns of course.

**Comment by CoDEmanX** [comment]
Just a small update: Chrome 46 became stable a week ago, and V8 4.7 has been released too: http://v8project.blogspot.de/2015/10/v8-release-47.html
Thus, stable Chrome 47 / V8 4.7 can be expected in the first weeks of January.

**Comment by CoDEmanX** [comment]
Chrome 47 turned stable, making V8 4.7.80.23 the currently latest, stable version.
https://omahaproxy.appspot.com

Rest parameters and destructuring will be available in 4.8 without flags.

**Comment by dothebart** [comment]
yup currently struggling on the buffers...

**Comment by dsonet** [comment]
Is it possible to integrate with [FibJS](http://fibjs.org/en/index.html) ?

> Fibjs is an application server framework bassed on Google V8 Javascript engine. Fibjs, as distinct from node.js, uses fiber to deal with multiplex of V8 engine. By reconstruct with lots of C++ components, heavy operations of consume much CPU time are devolved to background threads, which will release threads of V8 engine and compete for concurrent time.
Since it has very good performance.

**Comment by dothebart** [comment]
Yes, it could have been a good resource too, we finished the upgrade now by simply removing fastbuffers, since they were only used internally its transparent to the users that they're gone.

I'll close this now, it will be available with ArangoDB 3.0

**Comment by Simran-B** [comment]
@dsonet: JavaScript in a Arango needs to run synchronous and multi-threaded. I'm not sure as what FibJS qualifies. Sounds like it uses more than a single thread, at least for some stuff (background threads), but I don't think Arango would gain anything from a coroutine architecture. Not to mention how much work it would be to integrate FIbJS.

In Arango, small JavaScript pieces are supposed to be run a lot, e.g. as part of a query (custom user function). They shouldn't laster longer than a couple milliseconds each. NodeJS and FibJS are not focussed on short-lived script snippets as far as I understand. They are good for long-lasting operations though, but we don't really need/want that in a database. Make sure to check out the discussion [why Arango doesn't embed Node](https://groups.google.com/d/topic/arangodb/h5a-71H4LUM/discussion).

BTW: Most Promise libraries for Node are based on Fibers AFAIK, which makes FibJS look less unique.

**Comment by dsonet** [comment]
Hi, @Simran-B , but foxx runs as the same role as FibJS right? Also FibJS is sync & none-blocking naturally underlying.  And I don't think the node module Fiber runs the same way.
