### ISSUE TITLE
ArangoDB Production Cluster Problem

### ISSUE THREAD

**Issue by Madmancj** [arangodb/arangodb#1514]
Hi,
I have been trying to set up an ArangoDB production cluster. The cluster is starting fine. But then it got stuck in an infinite loop with a message, "waiting for a dbserver to show up".
What could have gone wrong?

**Comment by dothebart** [comment]
Depending on your machine hardware and resources used by other components in your system (browse, mailclient, etc.) launching the cluster may take longer then the webinterface anticipated.
Please wait some more time, and reload the interface.
