### ISSUE TITLE
Cluster webinterface misbehaviours

### ISSUE THREAD

**Issue by dothebart** [arangodb/arangodb#1515]
1) cluster start
If the cluster start takes too long, an error screen is shown. This error screen neither tells the user that if the system is still working (-> using cpu) it may take a little longer, nor will it flip into 'working' state once a late start finalizes.
2) cluster restart
The main arangod is shut down, and thus it shuts down the whole cluster. The browser window remains open, it flips to the error screen (as it should). After restarting the main server, the webif continues polling to all instances, and keeps the error screen, since all backend servers are down. If one presses f5, a screen shows up that allows to restart the cluster. The webinterface should switch to that screen automatically.
3) fault tolerance Coordinators
If several coordinators are there, the webif will round robin poll the coordinators. Thus if one coordinator is gone, it will flip from 'broken' to 'working' back and forth.

**The display text should be changed from:**

None of your Coordinators is reachable. However your DBServers are still running. This might be a network problem.
Please check the your network connection to the following servers:
    
If none of these servers is reachable they are either located behind a firewall and not accessable to the outside, or there is a network disconnection.
    
If at least of these servers is reachable the coordinator potentially crashed, please have a look in the log files. In this case you can shutdown the cluster and relaunch it again.
    
If you want to file a bug, please use our issue tracker. Or feel free to ask a question on our google group. 

**To this text:**:

Your cluster Coordinators are not (yet) reachable. The DBServer processes are still active. They may still be in their startup phase, or network connectivity may be unavailable
Please check the your network connection to the following servers:
    
If your system is still very active, startup may take some more time.
If none of these servers is reachable they are either located behind a firewall and not accessable to the outside, or there is a network disconnection.
    
If none of the above is true, consult the server logfiles for more error informations.

**Comment by hkernbach** [comment]
Changed text and fixed 2: 
https://github.com/arangodb/arangodb/commit/74bca104e5d80e68efb1d6c3d9398a2845c6d915
