### ISSUE TITLE
[QUESTION] AQL FILTER optimized away, how do I write this query?

### ISSUE THREAD

**Issue by Phillips126** [arangodb/arangodb#15161]
## My Environment

* __ArangoDB Version__:  3.7.3 
* __Storage Engine__:  RocksDB
* __Deployment Mode__:  Single Server
* __Deployment Strategy__:  Manual Start 
* __Infrastructure__:  own
* __Operating System__:  Ubuntu 20.04
* __Total RAM in your machine__:  256GB
* __Disks in use__:  SSD 

## Component, Query & Data

__Affected feature__:
AQL query

__AQL query (if applicable)__:
The application in development is an internal product ordering tool.  When items are ordered, the product is added to the users personal inventory.  When product is reported as used (filling out web form), the product is subtracted from the users inventory (documents still exist, just marked as "consumed").  

When a user reports used product, the web application sends JSON to my web server which handles the AQL.
JSON used (confidential information replaced/removed):

```
{
    "fields": {
        "consultant_id": "users/6192508",
        "consultant": {
	    "email": "<users email>",
            "first_name": "<users first name>",
	    "last_name": "<users last name>"
	},
	"consumed": [
	    {
		"ordered": 1637082888153,
		"orderID": "orders/27609614",
		"part_number": "031350",
	        "owner": "users/6192508",
		"quantity": "2",
		"lot_number": "819721"
            },
	    {
		"ordered": 1637082888153,
		"orderID": "orders/27609614",
		"part_number": "031350",
		"owner": "users/6192508",
		"quantity": "4",
		"lot_number": "819718"
            },
	    ..... // etc.
	]
    }
}
```

My AQL is expected to loop through all of the consumed product from the JSON and change the product in the users inventory from "In Stock" to "Consumed" (with some other information provided as well that I am omitting).

_I'll add some comments to work through my logic - which is clearly flawed but I am stumped._

```
// Loop through the "consumed" array from the provided JSON.

FOR i IN 0..LENGTH(@fields.consumed) - 1
    
    // Find the users inventory items that match the items reported in the [ i ] index of the JSON array.
    // NOTE:  I am filtering for "In Stock" status, with the idea that items updated in the bottom "quantity" loop
    //        would be removed from the inventory found in the next inventory lookup.

    LET inventory = (
        FOR product IN products
            FILTER product.orderID == @fields.consumed[i].orderID
            FILTER product.owner == @fields.consultant_id
            FILTER product.part_number == @fields.consumed[i].part_number
            FILTER product.status == "In Stock"
            RETURN product
    )
    
    // Loop through the quantity reported in JSON, mark the items as "consumed".

    FOR x IN 0..@fields.consumed[i].quantity - 1
        UPDATE inventory[x] WITH {status: "Consumed" } IN products
```

__Dataset__:
The "products" in the products collection are simply stored as:

```
{
  "created": 1617903428424,
  "orderID": "orders/27609614",
  "part_number": "031350",
  "owner": "users/6192508",
  "status": "In Stock",
  "recieved": 1618231499586
}
```

## Steps to reproduce

1. Insert several "products" in the products collection.
2. Run the above query with the above bind variables.

__Problem__:

The bottom loop that updates each record appears to be overwriting the same "product" in the products collection.  Unless I am overlooking something, this appears to indicate that the "In Stock" filter is not being re-examined in each iteration of the loop causing the same list of products to appear in the users inventory despite being updated?

__Expected result__:

I expected that each iteration of the top FOR loop would yield different/smaller results for the users inventory.  If the product was marked "consumed" in the bottom loop, these items would be filtered out.

**Comment by mpoeter** [comment]
An AQL query is executed transactionally on a _snapshot_ of the DB's state from the time the query was started. Read operations in the query will observe the state _from the snapshot_. This means, that any writes you perform as part of the query _cannot_ be observed by the query itself.

Consider the following query: `FOR d IN docs INSERT {} INTO docs`
If `docs` was non-empty, this query would iterate over all documents and for each one insert yet another document into `docs`. But if we would observe our own writes, this would degenerate to an endless loop.

The only exception to this is UPSERT, for which the implicit subquery for the search expression _does_ observe writes performed by the same query, so that you can update documents that where inserted by previous iterations. So you could theoretically rewrite your query to use UPSERT instead, but it still feels a bit hacky. I would rather suggest to use a streaming transaction and implement this on the client as part of the business logic.

**Comment by Phillips126** [comment]
Thank you for your explanation, this makes perfect sense.  I'll come up with a workaround.
