### ISSUE TITLE
Arangodb Sharding Issue

### ISSUE THREAD

**Issue by chetan92** [arangodb/arangodb#1516]
I am using Arangodb cluster in two hosts (say host 'A' and host 'B'). I made both of them as coordinator and DBServer . Lets say my configurations are:
Host A: IP1 port 8530 (coordinator port 8531)
Host B: IP2 port 8530 (coordinator port 8531)
Now i have 2 apps listening to host 'A' and host 'B' respectively (on port 8531). Suppose Host 'A' coordinator goes down then app 'A' stops listening while app 'B' is working fine.
How can i make app 'A' to listen to Host 'B' if Host 'A' is down and vice versa?

**Comment by dothebart** [comment]
Usually you do this using [IP Adress takeover](http://www.ultramonkey.org/3/ip_address_takeover.html). 
However, you have to make shure that your apps are available on both coordinators. 
This can be achieved by putting the apps/ directory on a shared or mirrored fiesystem between the tho hosts, or monitoring the apss folder with [FAM)[http://www.linuxfromscratch.org/blfs/view/6.1/general/fam.html) and use that to trigger an [RSYNC](https://en.wikipedia.org/wiki/Rsync) to update the second host..

**Comment by CoDEmanX** [comment]
It's actually "sure" ;)
[/grammarnazi]

**Comment by dothebart** [comment]
*gna* gotta get that into my head.

**Comment by fceller** [comment]
Also see http://stackoverflow.com/questions/32886319/arangodb-sharding-issue/33079527#33079527
