### ISSUE TITLE
Index for nested property causes limit to return empty result

### ISSUE THREAD

**Issue by jeff-pang** [arangodb/arangodb#1520]
The query returns empty result when a skiplist index Summary.LastScanEpochTime is added to the "test" collection

FOR doc IN test FILTER doc.Summary.LastScanEpochTime >= 1428585236 limit 1,2 return doc

sample dataset https://gist.github.com/jeff-pang/fa876afbe41d427adace

**Comment by jsteemann** [comment]
This got recently fixed in version 2.6.9.

**Comment by jsteemann** [comment]
I can confirm the query works with 2.6.9 and produces the two documents as expected.
