### ISSUE TITLE
Heavy queries not cancelled when client dies

### ISSUE THREAD

**Issue by d1g1t4l** [arangodb/arangodb#1523]
I am using 2.6.8. When I use arangosh to make a heavy query (a cross product that involves millions of nodes) and press control+c before it returns the query seems to keep executing on the server (arangod continues to use 100% CPU for a while). Intuitively I would expect the query to get cancelled when the tcp connection dies. Is the observed behavior intentional? Is there any way to cancel such queries?

**Comment by CoDEmanX** [comment]
AFAIK it's expected behavior, although I agree that it makes sense to abort the query on the server immediately, if no client will ever receive it anyway.

You can explicitly kill queries, see https://docs.arangodb.com/HttpAqlQuery/index.html#killing-queries

**Comment by fceller** [comment]
@d1g1t4l in principle, we could kill non-modifying queries, if the client dies. However, AQL statements that modify data (insert, update, delete), should keep running, even if the clients dies.

@CoDEmanX already pointed out, how to cancel requires, using the HTTP interface.

Using `arangosh`:

```
arangosh [_system]> var q = require("org/arangodb/aql/queries");

arangosh [_system]> q.current()
[ 
  { 
    "id" : "11", 
    "query" : "RETURN SLEEP(10000)", 
    "started" : "2015-10-12T08:53:46Z", 
    "runTime" : 21.18801784515381 
  } 
]

arangosh [_system]> q.kill("11");
{ 
  "code" : 200 
}

arangosh [_system]> q.current()
[ ]
```
