### ISSUE TITLE
Creating graph/edge model in ArangoDb FOXX app

### ISSUE THREAD

**Issue by realdog** [arangodb/arangodb#1524]
Can somebody help me with following issue. I'm writing custom FOXX app in ArangoDB and I need to create graph/edge model file,but i can't find out any document about it

**Comment by fceller** [comment]
@pluma what is currently "the way" to do it? Directly use the "db" object?

**Comment by pluma** [comment]
You could create a regular Model for your edges with `_to` and `_from` attributes. If you are using 2.6 or newer, the repository's `save` method will handle saving to edge collections correctly.

For graphs there is no special support in Foxx itself, so you'd probably just use the regular API (`org/arangodb/general-graph` I think).

**Comment by realdog** [comment]
@fceller  @pluma  thank you very much:)
