### ISSUE TITLE
Feature request: trigger collection compaction via HTTP REST API

### ISSUE THREAD

**Issue by matcho** [arangodb/arangodb#15246]
## My Environment

* __ArangoDB Version__:        3.8.3
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Leader/Follower ("Master/Slave")
* __Deployment Strategy__:   systemd
* __Infrastructure__:               own
* __Operating System__:        Ubuntu 20.04
* __Total RAM in your machine__:        256 GB
* __Disks in use__:        SSD
* __Used Package__:              Ubuntu .deb

## Component, Query & Data

__Affected feature__:
HTTP API

__Problem__:
This is a question / feature request. Could it be possible to trigger background compaction on a single collection (not on the whole database) via HTTP REST API ?

This could be useful to periodically compact ever-growing collections, as a workaround for #14237

See also https://github.com/arangodb/arangojs/issues/630

Thanks a lot for your consideration.

Greetings,
Mathias

**Comment by dothebart** [comment]
Hi, 
I'm sorry, but the compaction is part of the RocksDB core ArangoDB is built on top of. 
However, RocksDB doesn't know about the scope of collections; all it has is binary documents with an ID;
So while this had been possible with MMFiles, where a collection would map a set of files, its not possible with RocksDB anymore. 

However, it seems that other people have improved their system performance by more frequently invoking the compaction, maybe that could also improve your situation?
We're still looking for a more good trigger for the compaction than wall clock, however, we didn't find any yet.

**Comment by matcho** [comment]
Hi, thanks for your answer.

Actually it's possible to trigger compaction for a single collection via arangosh using`db.collection_name.compact();` so one could expect that this procedure can be triggered using HTTP API too.

Frequently invoking the compaction is exactly what we would like to do, hoping to achieve it through a cronjob-scheduled Arangojs script, but only for the collection that grows endlessly.

We would prefer to avoid writing a shell script that calls `arangosh` then `.compact()`, but if this is the only way we might consider doing this anyway.

Thanks for any advice

**Comment by dothebart** [comment]
have a look at the documentation: 
https://www.arangodb.com/docs/stable/data-modeling-databases-working-with.html#compact

**Comment by dothebart** [comment]
I've tagged other tickets that are discussing issues around the compaction as well.

**Comment by dothebart** [comment]
nb, arangosh *only* talks to arangod via the [http API](https://www.arangodb.com/docs/stable/http/administration-and-monitoring.html#compact-the-entire-database-system-data) ; You can also explore these via the swagger interface in the UI, which will also give you a curl command.

**Comment by matcho** [comment]
I believe this potentially adresses the feature request : https://github.com/arangodb/arangojs/pull/756

**Comment by pluma** [comment]
@Zyqsempai This is relevant to what we talked about at the drivers sync. The route seems to exist but is undocumented.

**Comment by matcho** [comment]
Closing as the route exists, maybe still deserves to be documented.
