### ISSUE TITLE
Split apt repos into branches

### ISSUE THREAD

**Issue by F21** [arangodb/arangodb#1526]
I am currently using `2.6.9` installed using the apt repo on Ubuntu. I am happy with `2.6` and would like to use that branch for patch fixes in the mean time.

Because all binaries no matter how old or new are all published to the `/` apt-repo, if I do `apt-get dist-upgrade`, it asks me to upgrade to `2.7.0`, which I do not want.

I propose that the apt repos be split into different versions like elasticsearch:
```
http://packages.elastic.co/elasticsearch/1.7/debian stable main
http://packages.elastic.co/elasticsearch/1.8/debian stable main
http://packages.elastic.co/elasticsearch/1.9/debian stable main
```

This way, we can set up our servers to use a certain branch of arangodb and easily receive patch fixes.

**Comment by fceller** [comment]
Please follow the instruction in

    http://blog.backslasher.net/my-pinning-guidelines.html

to pin a major / minor version.

We only split repositories at major versions (1.x.x, 2.x.x, 3.x.x).
