### ISSUE TITLE
Enable ES6 by default

### ISSUE THREAD

**Issue by TwinTailsX** [arangodb/arangodb#1527]
Hi, any plans to enable all ES6 features by default or possibility to have a permanent config option? (allowing to just run arangod with a double click)

**Comment by CoDEmanX** [comment]
On Windows you could simply create a shortcut with start up options...

Once the ES2015 features are stable in V8, they should become available by default in Arango, as soon as that v8 version has been integrated. Chrome is currently behind the release calendar and it will take a while until v47 is released I'm afraid. But as soon as it is, a sub version of v8 v4.7 will become stable as well and I hope it will make it into Arango 2.8

**Comment by fceller** [comment]
You can edit the arangod.conf and/or arangosh.conf file and add (for example):

    [javascript]
    v8-options = --use_strict

**Comment by TwinTailsX** [comment]
Cool, thanks!
