### ISSUE TITLE
How to install @arangodb/foxx ? 

### ISSUE THREAD

**Issue by raphael10-collab** [arangodb/arangodb#15272]
How to install @arangodb/foxx ?
I'm not finding it :   https://www.npmjs.com/search?q=%40arangodb

**Comment by dothebart** [comment]
Foxx is the .js framework available inside of arangodb.
You can't use it within nodejs. 
Please have a look at https://www.arangodb.com/docs/stable/foxx.html for more details.

**Comment by raphael10-collab** [comment]
Thank you!!!
