### ISSUE TITLE
Using index both for FILTER and SORT

### ISSUE THREAD

**Issue by Minstel** [arangodb/arangodb#15281]
## My Environment

* __ArangoDB Version__:        3.8.1
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start in Docker
* __Operating System__:        Ubuntu 20.04

## Component, Query & Data

__Affected feature__:
AQL query

__AQL query (if applicable)__:
```
FOR item IN test
FILTER item._key IN ['a', 'b']
SORT item.foo
RETURN item
```

__AQL explain and/or profile (if applicable)__:
```
Query String (73 chars, cacheable: false):
 FOR item in test
 FILTER item._key IN ['a', 'b']
 SORT item.foo
 RETURN item

Execution plan:
 Id   NodeType          Calls   Items   Runtime [s]   Comment
  1   SingletonNode         1       1       0.00003   * ROOT
  8   IndexNode             1       2       0.00014     - FOR item IN test   /* persistent index scan */    
  5   CalculationNode       1       2       0.00002       - LET #3 = item.`foo`   /* attribute expression */   /* collections used: item : test */
  6   SortNode              1       2       0.00002       - SORT #3 ASC   /* sorting strategy: standard */
  7   ReturnNode            1       2       0.00001       - RETURN item

Indexes used:
 By   Name      Type         Collection   Unique   Sparse   Selectivity   Fields              Ranges
  8   key_foo   persistent   test         true     false       100.00 %   [ `_key`, `foo` ]   (item.`_key` IN [ "a", "b" ])

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   move-calculations-up-2
  4   move-filters-up-2
  5   use-indexes
  6   remove-filter-covered-by-index
  7   remove-unnecessary-calculations-2

Query Statistics:
 Writes Exec   Writes Ign   Scan Full   Scan Index   Filtered   Peak Mem [b]   Exec Time [s]
           0            0           0            2          0          32768         0.00103

Query Profile:
 Query Stage           Duration [s]
 initializing               0.00001
 parsing                    0.00007
 optimizing ast             0.00001
 loading collections        0.00001
 instantiating plan         0.00003
 optimizing plan            0.00065
 executing                  0.00024
 finalizing                 0.00004
```

__Dataset__:
```
{'_key': 'a', 'foo': 'foo1'},
{'_key': 'b', 'foo': 'foo2'}
```

## Steps to reproduce

1. Create compound index on fields `_key` and `foo`
2. Execute query

__Problem__:
Index is only used for IN filtering, but it is not used for sorting.

__Expected result__:
Compound index should be used both for filtering and sorting.

## Comment
This is actually quite disturbing issue, because it prevents fetching really complex data, where we first determine records to fetch using some complex conditions, and then we need to fetch them, sorting by any field(s).

**Comment by dothebart** [comment]
if you have documents with these attributes:

| _key | foo |
|--------|------|
| a       | 2   |
| a       | 3   |
| b       | 1   |

the documents would come out in exactly that sequence, if you would choose indexed sorting here. 
I guess thats not what you want in the end?

**Comment by Minstel** [comment]
@dothebart I do not really understand what you mean. 

That's just the imaginary data. I need this to work for millions of records, where the query should:
- filter records by primary key using IN condition
- sort obtained records in that same query by one or multiple fields

Both steps should use index.

**Comment by Minstel** [comment]
@dothebart In more general case sorting should use index with any type of filter, the way it works in MySql. I guess I should've named issue to reflect this general case... 

Without this functionality ArangoDB use cases are very limited, as it seems to me.

**Comment by dothebart** [comment]
The table represents the sorting returned by an index on `_key`, `foo`. This sample of 3 can easily be extended to more entries, it was just there to document the issue.

So while it will probably give you a more sorted base (and hence less effort to sort it more) it still will only be able to give you a sort order by [`_key`] or [`_key`, `foo`]. 

ArangoDB doesn't implement intersecting of indices.

**Comment by Minstel** [comment]
@dothebart Will it in future?

**Comment by Minstel** [comment]
@dothebart Ok, thank you. Will this be implemented in future? I mean:
- if a compound index exists
- we filter on a left hand side of index
- do the sorting on the rest index fields
- then this index is used for both filter and sorting

**Comment by mpoeter** [comment]
@Minstel you generally cannot use the same index to filter by one attribute and sort by another one. Suppose we have an index on `[_key, foo]` and the following data:
| _key | foo |
|--------|------|
| a       | 2   |
| b       | 1   |
| c       | 3   |

Then the index consists of a sorted list of pairs: `(a, 2), (b, 1), (c, 3)`.

If you would filter by `_key == a`, then this index could (and should) be used for sorting on `foo`, because this condition is a _prefix_ of the index (`_key` is the first attribute in the index and we are filtering for _a single_ key). However, `_key IN [a, b]` is _not_ a prefix and can therefore _not_ be used for sorting on `foo` (it would produce the documents `a, b` _in that order_, which obviously does not match the order on `foo`).

**Comment by Minstel** [comment]
@mpoeter 
> generally cannot use

That sounds strange because it works, say, in mongo.
Anyway, using index for filter + sorting in arango does not work not only for IN filter, but for any filter. So I'm asking if that will be implemented.

**Comment by mpoeter** [comment]
I should have been more precise - you can use an index to filter on some keys and sort on others, _iff_ the filter uses _equality_ and the keys are a prefix of the index keys.

And the same restriction is also true for MongoDB (see [Sort and Non-prefix Subset of an Index](https://docs.mongodb.com/manual/tutorial/sort-results-with-indexes/#sort-and-non-prefix-subset-of-an-index)):
> An index can support sort operations on a non-prefix subset of the index key pattern. To do so, the query must include equality conditions on all the prefix keys that precede the sort keys. [...]
If the query does __not__ specify an equality condition on an index prefix that precedes or overlaps with the sort specification, the operation will __not__ efficiently use the index.

**Comment by Minstel** [comment]
@mpoeter  Well, getting `explain` statements for queries with `in` and sorting shows that index is fully used in mongo. As it is in MySql, if I remember correctly. Besides, it seems to me that `in` is an equality condition under the hood:)

Maybe I'm writing smth weird, of course. But it seems to me that it's just impossible that index was not used in such case.
But I understand from your words that you do not see it being implemented in ArangoDb, so I'm closing this issue.

**Comment by mpoeter** [comment]
Well, an `in` operation is an equality condition for _multiple_ values, so the subranges _for each individual value_ would be ordered by the second condition, but there would be no _total_ order based on the second condition. Instead, the result would be ordered by the first and the second condition (exactly in the order in which the attributes are defined in the index).

I very much doubt that Mongo or MySql do this any different, but I would be curious to see the explain outputs that you mentioned! I don't say that we cannot/will not implement some improvements to our indexes or how they are used. It's just that I don't think that what you are requesting is actually not possible in that way.
