### ISSUE TITLE
Confusion in query.fromVertices API in graph AQL

### ISSUE THREAD

**Issue by apuravchauhan** [arangodb/arangodb#1531]
http://stackoverflow.com/questions/33184266/understanding-query-fromvertices-api-in-arangodb-graph-module

Can someone shed some light on this. Is it a bug?

**Comment by dothebart** [comment]
yes, its actually a missbehaviour.

**Comment by dothebart** [comment]
fixed with 30be20224e0aab78f279212e4f62e3ea22c5c7f2 - the actual result will be visible in https://docs.arangodb.com/devel/GeneralGraphs/FluentAQLInterface.html in the next minutes.
