### ISSUE TITLE
Does the foxx application need connection pool?

### ISSUE THREAD

**Issue by realdog** [arangodb/arangodb#1533]
When i need connect database ,i create db object and excute query ......i want to know, do I need to consider efficiency problem（for example: connection pool。。。）

**Comment by dothebart** [comment]
Since a foxx service runs inside of the database, you don't need a connection pool there.

If your application can build a connection pool to arangodb and your foxx, thats probably good for performance, since establishing tcp/ip connections is expensive.

**Comment by razvanphp** [comment]
.. or maybe think about enabling keep-alive.

**Comment by dothebart** [comment]
The mentioned documentation will become available here:
https://docs.arangodb.com/devel/Foxx/Production/Productionmode.html
https://docs.arangodb.com/devel/GeneralHttp/index.html

**Comment by p30arena** [comment]
It's good to include Web Sockets for the next major release!

**Comment by pluma** [comment]
@p30arena I'm not sure how your comment is related to this issue.

I think you're looking for https://github.com/arangodb/arangodb/issues/602
