### ISSUE TITLE
Graph viewer default vertex grouping by unevident similarity  

### ISSUE THREAD

**Issue by abelyaevskiy** [arangodb/arangodb#1535]
Hi!

I have graph (multi collection graph). When I open it for given vertex I see some strange default vertex grouping
![strange grouping](https://cloud.githubusercontent.com/assets/1597145/10642276/844fa282-7825-11e5-8afd-75c7b62e8b3c.JPG)

I do not setup vertex grouping and also all group items have same name "Similar Nodes"
![similar nodes and no grouping](https://cloud.githubusercontent.com/assets/1597145/10642360/f396c094-7825-11e5-9ef4-52452c3148c0.JPG)

Could anyone describe such default similar node group functionality? Which metric does used for similarity measurement?

I use Arango 2.5.4

Nodes looks quite different (I show below 2 nodes from one group):
 * one doc
```javascript
{
  "_id": "AdventureWorks2014/PurchaseOrderHeader",
  "_rev": "464771997",
  "_key": "PurchaseOrderHeader",
  "tableSize": "544",
  "tableUsedSize": "496",
  "tableUnusedSize": "48",
  "Name": "PurchaseOrderHeader",
  "tableName": "PurchaseOrderHeader",
  "location": "10.69.2.95",
  "source": "AdventureWorks2014",
  "provider": "System.Data.SqlClient",
  "tableDescription": "General purchase order information. See PurchaseOrderDetail.",
  "tableCreatedDate": "17.07.2014 16:11:15",
  "tableModifiedDate": "17.07.2014 16:11:39",
  "PrimaryKeyColumns": [
    "PurchaseOrderID"
  ],
  "Fields": [
    "PurchaseOrderID",
    "RevisionNumber",
    "Status",
    "EmployeeID",
    "VendorID",
    "ShipMethodID",
    "OrderDate",
    "ShipDate",
    "SubTotal",
    "TaxAmt",
    "Freight",
    "TotalDue",
    "ModifiedDate"
  ]
}
```
* another one
```javascript
{
  "_id": "AdventureWorks2014/PersonCreditCard",
  "_rev": "455072669",
  "_key": "PersonCreditCard",
  "tableSize": "584",
  "tableUsedSize": "496",
  "tableUnusedSize": "88",
  "Name": "PersonCreditCard",
  "tableName": "PersonCreditCard",
  "location": "10.69.2.95",
  "source": "AdventureWorks2014",
  "provider": "System.Data.SqlClient",
  "tableDescription": "Cross-reference table mapping people to their credit card information in the CreditCard table. ",
  "tableCreatedDate": "17.07.2014 16:11:15",
  "tableModifiedDate": "17.07.2014 16:11:39",
  "Fields": [
    "BusinessEntityID",
    "CreditCardID",
    "ModifiedDate"
  ],
  "PrimaryKeyColumns": [
    "BusinessEntityID",
    "CreditCardID"
  ]
}
```

**Comment by hkernbach** [comment]
The grouping of vertices is happening because of browser performance issues. An example is: When there are lots of relations between a single node and a million nodes and the browser would render all of them, the browser would crash or react very slow. But I understand that our choosen default value for visual grouping is not good for every use case. We'll add a configurable interface in the graph viewer soon.

**Comment by hkernbach** [comment]
Feature request: https://github.com/arangodb/arangodb/issues/1544
