### ISSUE TITLE
Graph adding edges in the UI doesn't work

### ISSUE THREAD

**Issue by dothebart** [arangodb/arangodb#1540]
Load the city navigator example graph.
press + in the iconbar to add a new edge.
A popup appears that allows you to select the collection.
after pressing `select` the popup vanishes, and nothing more happenes. Sometimes you get an error notification in the upper right.

Found while trying to reproduce: https://groups.google.com/forum/#!msg/arangodb/u0Wi31_uddA/-ME9_GfBCwAJ
I can't tell if I'm doing something wrong... I have made a graph, filtered by attribute and can see vertices but all the action buttons except "Drag a node" do nothing.

Right-click actions work fine.

Trying to create an edge logs a
400 (Bad request)

error to console.

Tried chrome 46 & IE 11

**Comment by jsteemann** [comment]
If reproducible, can you send the HTTP transfer that produces the HTTP 400 error? Firebug or Chrome will happily provide these details, i.e. HTTP request & responst headers and POST bodies. Looking at these data will potentially help figuring out why there is an error. Thanks!

**Comment by TwinTailsX** [comment]
Request: 
```
POST /_db/test/_api/gharial/graphtest/edge/communityMemberLinks HTTP/1.1
Host: 127.0.0.1:8529
Connection: keep-alive
Content-Length: 59
Accept: application/json, text/javascript, */*; q=0.01
Origin: http://127.0.0.1:8529
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36
Content-Type: application/json
DNT: 1
Referer: http://127.0.0.1:8529/_db/test/_admin/aardvark/standalone.html
Accept-Encoding: gzip, deflate
Accept-Language: en,en-US;q=0.8,en-GB;q=0.6
```

Response:
```
HTTP/1.1 400 Bad Request
Access-Control-Allow-Credentials: true
Server: ArangoDB
Access-Control-Allow-Origin: http://127.0.0.1:8529
Access-Control-Expose-Headers: etag, content-encoding, content-length, location, server, x-arango-errors, x-arango-async-id
Content-Type: application/json
Connection: Keep-Alive
Content-Length: 71
```

Post body:
```
{"_from":"communities/5405168983","_to":"users/5401367895"}
```

**Comment by dothebart** [comment]
ok, so if you click on `collections` you have three collections: `communities`, `users` and an edge collection `communityMemberLinks`?

In `communities` you should be able to find a document where  `_key` is `5405168983`
and in `users` there should be a document with  `_key` being  `5401367895`?

if you check the `System` hook in the gear-menu, you should see a `_graphs` collection, where your `graphtest` - graphdescription is pointing to these three collections?

Do you see any errors in the errorlog of arangod?

**Comment by jsteemann** [comment]
The problem seems to be that a graph definition contains "fromCollections" and "toCollections", and edges can only be created starting at a collection from the "fromCollections" set, and ending in a collection present in the "toCollections" set.
An HTTP 400 error will be thrown if an attempt is made in the graph viewer to create an edge starting at one of the "toCollections", or if the edge ends in one of the "fromCollections".
To avoid this, the vertex collections in question have to be added to both the "fromCollections" and the "toCollections" in the graph definition.

**Comment by TwinTailsX** [comment]
@dothebart yes, yes, yes and no

Can confirm that creating edges in the direction of the definition works. I think a visual notification might be helpful here, even if just to serve as a reminder.

**Comment by jsteemann** [comment]
I agree having some visual indication that adding the edge does not work would make sense (and probably an error message showing the reason e.g. `cannot add edge because it would violate directions specified in graph definition` or alike).

**Comment by hkernbach** [comment]
Added notifications for graphs.
https://github.com/arangodb/arangodb/commit/cb03ac85812ccdcab2c867d119fcabab6484ba89
https://github.com/arangodb/arangodb/commit/4940c80d88a8dda03126c273fead37eced1ddbd5
