### ISSUE TITLE
How to disable http interface?

### ISSUE THREAD

**Issue by realdog** [arangodb/arangodb#1541]
When i run arangodb in my server, I need disable the http interface,I don't want to use 'server.disable-authentication' ....and ....how to do ?

**Comment by dothebart** [comment]
In general, its not easy possible to disable the Interface. However, the recommended way is to restrict the access to it:
https://docs.arangodb.com/GeneralHttp/index.html#Authentication

You could also remove the route to it from the _routing system collection:

    db._query("FOR route IN _routing FILTER route.url == '/_admin/html' REMOVE route in _routing");
    db._query("FOR route IN _routing FILTER route.url == '/_admin/html/index.html' REMOVE route in _routing");
    db._query("FOR route IN _routing FILTER route.url == '/' REMOVE route in _routing");

and delete the app reference:

    db._query("FOR app IN _apps FILTER app.mount == '/_admin/aardvark' REMOVE route in _routing");

These may however be recreated on update.

**Comment by realdog** [comment]
@dothebart     I really appreciate your help.

**Comment by dothebart** [comment]
Did this work out for you so we can close it?
