### ISSUE TITLE
Unhelpful information on error codes page

### ISSUE THREAD

**Issue by bitboxx** [arangodb/arangodb#15426]
## My Environment

* __ArangoDB Version__: Latest: 3.10

__Problem__: This help page or error code [1208 - ERROR_ARANGO_ILLEGAL_NAME](https://www.arangodb.com/docs/devel/appendix-error-codes.html#1208) is not helpful.

![image](https://user-images.githubusercontent.com/2608523/147557442-daa2728f-aa3a-41a9-9d8e-b00b403f9b80.png)

__Expected result__: The description should be informative, explaining what an illegal name is, and what it should be (legal one).

**Comment by Simran-B** [comment]
This error is thrown under different conditions, which explains the generic description. It is raised if a database, collection, or View name is invalid. There are different rules for database and data source (collection/View) names: https://www.arangodb.com/docs/stable/data-modeling-naming-conventions.html

An interesting corner is if an AQL query tries to return a string literal in ticks that doesn't refer to a variable, thus being interpreted as a data source name, but that name being forbidden. Typically, you would see a "variable, collection, or View not found" error of there's neither a variable nor a data source by that name.
