### ISSUE TITLE
GRAPH_EDGE very slow performance

### ISSUE THREAD

**Issue by roman1720** [arangodb/arangodb#1543]
Hi, GRAPH_EDGE function performance seems to be very slow.

graph query:

for intL2 in vIntL2
  for e in GRAPH_EDGES('network', intL2, { edgeCollectionRestriction: "eDevIntL2"})
    return e

It takes around 2s to finish (there are only tens of vertices and edges in db)

join query:

for intL2 in vIntL2
  for e in eDevIntL2
    filter intL2._id==e._to
      return e._id

It takes around 0.02s to finish.

**Comment by mchacki** [comment]
Thank you for spotting this.
We are aware that some of the graph features are not yet optimized (mostly due to communication overhead between the Core and V8, which is currently reduced).
We have an improved version almost ready for 2.8 which should have similar performance than the join query.
I think this will close this issue.

**Comment by roman1720** [comment]
Thanks. Any idea when 2.8 will be out? I'm not really happy with rewriting all of our queries to joins, so if it will be released in foreseeable future, I will wait and live with slow queries.

**Comment by weinberger** [comment]
We really hope end of November, but not totally sure now.

**Comment by roman1720** [comment]
ok, thanks

**Comment by roman1720** [comment]
I found another problem with GRAPH_EDGE. It can choke whole database. Let's have two scripts.

Script 1) inserts 100 entries per 1s

function task() {
  console.log(Date());
  var count = 100;
  while (count > 0) {
    ar.query(`insert {status:'trace',count:` + count + `} in vIntL3`);
    count--;
  }
}

setInterval(() => {
  return task();
}, 1000);

Script 2) runs query with GRAPH_EDGES every 100ms

function task() {
  console.log(Date());
  ar.query(`
    for intL3 in vIntL3
      filter length(GRAPH_EDGES('network', intL3, { edgeCollectionRestriction: "eDevIntL3" }))==0 && intL3.status=="trace"
      update intL3 with {status: "ready"} in vIntL3
    `);
}

setInterval(() => {
  return task();
}, 100);

Now when script 1) runs alone, it works as expected and entries are inserted. But when both scripts runs concurrently there are almost no entries inserted. Will this 2.8 fix?

**Comment by dothebart** [comment]
Sorry to not have come back to this in a timely manner, the re-open fell through the raster.
I tried to reproduce this and couldn't see anything problematic. 
Did you add any indices on vIntL3? like the status field? Else you're doing full table scans there all the time, which probably won't be fast. 

ps:
The ArangoDB 2.8 graph traversal documentation can be found here: https://docs.arangodb.com/devel/Graphs/ and (linked in there) in special https://docs.arangodb.com/devel/Aql/GraphTraversals.html

**Comment by roman1720** [comment]
Hi, thanks for getting back to this, but it was problem in 2.7, I checked it in 2.8 and after GRAPH_ functions now being fast, it's no longer an issue and works correctly.
