### ISSUE TITLE
ArangoDB Does Not Compile With Python 3.10

### ISSUE THREAD

**Issue by kapilpipaliya** [arangodb/arangodb#15448]
## My Environment

* __ArangoDB Version__:        Github master
* __Operating System__:        Arch Linux
* __Used Package__:              Python 3.10

__Problem__:
ArangoDB doesn't compile with Python 3.10,  It compile with Python 3.9 successfully.

__Expected result__:
ArangoDB should compile with Python 3.10

**Comment by dothebart** [comment]
please post the actual error message.

**Comment by goedderz** [comment]
@kapilpipaliya I've opened PR that should fix that: https://github.com/arangodb/arangodb/pull/15502
It's not merged to the [devel](https://github.com/arangodb/arangodb/tree/devel) branch yet, but you can checkout the branch [build/allow-building-with-python-3.10](https://github.com/arangodb/arangodb/tree/build/allow-building-with-python-3.10) to try it out. Or just wait until it's merged.

**Comment by kapilpipaliya** [comment]
Thanks! This PR solved the issue. now arangodb successfully compiled with pyhon 3.10
