### ISSUE TITLE
Downloading whole database as JSON

### ISSUE THREAD

**Issue by Madmancj** [arangodb/arangodb#1545]
Recently i was trying to replicate my arangodb database into multiple machine.
But i couldn't find any option to download whole database as JSON.
However there are options to download each collection but downloading the whole database would be much easier, instead of downloading all 100 collections one by one.

Thanks in advance.

**Comment by jsteemann** [comment]
Have you tried the arangodump binary that is shipped with ArangoDB? You can re-import the dump it produces with the arangorestore binary that's also shipped with ArangoDB.

**Comment by dothebart** [comment]
Even better: you can use [Replication](https://docs.arangodb.com/Replication/index.html) to let a secondary arangodb sync to a primary. The [Example setup chapter](https://docs.arangodb.com/Replication/ExampleSetup.html)
