### ISSUE TITLE
Nodejs Tutorial -- AQL insert example

### ISSUE THREAD

**Issue by Conaws** [arangodb/arangodb#1548]
https://www.arangodb.com/tutorial-node-js/#aql-insert

The query builder example for insert a document is the same code as in fetch all documents example

**Comment by jsteemann** [comment]
Confirmed: the example code for the section "Insert a document with query builder" at the bottom of the page does only query the documents from the database, and does not show an insert case.

The following code on the page should be fixed so it actually shows an insert operation:
```js
mydb.query(qb.for("x").in("firstCollection").return("x._key"), function(err, cursor) {
   ...
});
```

**Comment by jsteemann** [comment]
Should be fixed now. Thanks for pointing at this.
