### ISSUE TITLE
disc usage 20x higher for search views after update from 3.6.1 to 3.8.4 

### ISSUE THREAD

**Issue by sebastian-nehrdich** [arangodb/arangodb#15486]
## My Environment

* __ArangoDB Version__:   3.8.4 
* __Storage Engine__:        RocksDB 
* __Deployment Mode__:  Single Server 
* __Deployment Strategy__:  Manual Start in Docker
* __Operating System__:       Ubuntu 18.04
* __Total RAM in your machine__:  16gb
* __Disks in use__:   HDD
* __Used Package__:  
* 

I recent updated my docker images of arangodb to 3.8.4 and rebuilt the entire database at that time. After the update, the disc usage for the search indicies under "_data/databases/database-201" has been multiplied by the factor 20 (previously it was ~500mb per view, now it is ~10gb). I haven't touched any of the code of the search views, the update is all I made. I can delete and rebuild the search indicies but the issue with their high disc usage remains.   
I build the search indicies with the following properties:
`{
    "cleanupIntervalStep": 0,
    "links": {
        COLLECTION_SEARCH_INDEX_TIB: {
            "analyzers": [TIBETAN_ANALYZER],
            "fields": {"search_string_precise": {"analyzers": [TIBETAN_ANALYZER]}},
        }
    },
    "includeAllFields": True,
    "storeValues": "none",
    "trackListPositions": False,
}`
The analyzer looks like this:
`db.create_analyzer(
        name=TIBETAN_ANALYZER,
        analyzer_type="text",
        properties={
            "locale": "en.utf-8",
            "stopwords": [],
            "accent": False,
            "stemming": False,
        },
        features=["position", "norm", "frequency"],
    )`

**Comment by dothebart** [comment]
Hi, 
please note that `cleanupIntervalStep` in view definition turns off cleanup procedure; did you add it after the upgrade?

**Comment by maxkernbach** [comment]
Hi @sebastian-nehrdich,

as mentioned in the previous reply setting `"cleanupIntervalStep": 0` will remove the cleanup procedure. Unused files in the ArangoSearch data directory will remain, which explains the high disk usage. By default, those unused files are removed after 2 commits (`"cleanupIntervalStep": 2`).

In case you still observe higher disk usage of your search view when using `"cleanupIntervalStep": 2`, please comment or open a new issue.
