### ISSUE TITLE
SORT does not work properly for big numbers

### ISSUE THREAD

**Issue by brunoaduarte** [arangodb/arangodb#15484]
Wrong result
```
FOR e IN entries SORT e._key DESC RETURN e
```
<html>
<body>

key | createdAt 
-- | --
9998982860 | 2022-01-08T07:30:36.250Z
9998982461 | 2022-01-08T07:30:34.237Z
9998959158 | 2022-01-08T07:28:23.412Z
9998958450 | 2022-01-08T07:28:20.537Z
9998612854 | 2022-01-08T06:53:25.435Z
9998612412 | 2022-01-08T06:53:23.295Z

</body>
</html>

But if I sort using the date field the result is correct
```
FOR e IN entries SORT e.createdAt DESC RETURN e
```

<html>
<body>

key | createdAt 
-- | --
10005348142 | 2022-01-08T14:05:32.465Z
10005343399 | 2022-01-08T14:05:18.925Z
10005022508 | 2022-01-08T13:49:55.769Z
10005021582 | 2022-01-08T13:49:53.342Z
10004910226 | 2022-01-08T13:44:20.110Z
10004909290 | 2022-01-08T13:44:17.465Z
10004717552 | 2022-01-08T13:35:04.660Z
10004716686 | 2022-01-08T13:35:02.451Z
10004644491 | 2022-01-08T13:31:30.456Z
10004642043 | 2022-01-08T13:31:22.978Z
9998982860 | 2022-01-08T07:30:36.250Z
9998982461 | 2022-01-08T07:30:34.237Z
9998959158 | 2022-01-08T07:28:23.412Z
9998958450 | 2022-01-08T07:28:20.537Z
9998612854 | 2022-01-08T06:53:25.435Z
9998612412 | 2022-01-08T06:53:23.295Z

</body>
</html>

**Comment by mpoeter** [comment]
@brunoaduarte Please note that the `_key` is a _string_, not a number. Therefore the sorting is done alphanumerically.

**Comment by brunoaduarte** [comment]
> @brunoaduarte Please note that the `_key` is a _string_, not a number. Therefore the sorting is done alphanumerically.

Ok @mpoeter . Is there a workaround to sort and filter it like number?
```
FOR e IN entries FILTER e._key < 10004644491 SORT e.createdAt DESC RETURN e
```
So I can run this for example?

**Comment by mpoeter** [comment]
You could use `FILTER TO_NUMBER(e._key) < 10004644491`, but this would not use any indexes.

Can you explain what exactly you are trying to do? Please try to describe the underlying root problem - perhaps use the [five whys](https://en.wikipedia.org/wiki/Five_whys) to get to that.

**Comment by brunoaduarte** [comment]
> You could use `FILTER TO_NUMBER(e._key) < 10004644491`, but this would not use any indexes.
> 
> Can you explain what exactly you are trying to do? Please try to describe the underlying root problem - perhaps use the [five whys](https://en.wikipedia.org/wiki/Five_whys) to get to that.

Thanks, that works for me. Not using the index in this filter is not a problem since the values are already filtered from a previous query that I run...

I need to filter entries older than the specified _key, but I cannot use the loggedAt field because currently the user sends the _key as parameter to the controller.
