### ISSUE TITLE
SKIP is not implemented in AQL

### ISSUE THREAD

**Issue by wgwine** [arangodb/arangodb#1549]
Please close this and respond if I am wrong. I am trying to do pagination, but the only example of skip is in the arangosh, and the AQL query fails using SKIP.
```
FOR article IN FULLTEXT(Articles, "Body", "balloon") LIMIT 10 SKIP 10 RETURN article
```

**Comment by jsteemann** [comment]
There is no extra `SKIP` keyword to skip documents. Skipping documents can be achieved by using `LIMIT` with two parameters, e.g.
```
FOR article IN FULLTEXT(Articles, "Body", "balloon") LIMIT 10, 20 RETURN article
```
The first value is the number of documents to skip, the second one is the number of documents to return at most. The above example will skip 10 documents and return up to 20 (provided the result set before skipping had at least 30 documents).
