### ISSUE TITLE
CSV ARANGOIMPORT AND QUERY PROBLEM

### ISSUE THREAD

**Issue by cr00589** [arangodb/arangodb#15507]
## My Environment

* __ArangoDB Version__:        
* __Storage Engine__:             
* __Deployment Mode__:       
* __Deployment Strategy__:   
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:        
* __Total RAM in your machine__:        
* __Disks in use__:        
* __Used Package__:              

## Component, Query & Data

__Affected feature__:

__AQL query (if applicable)__:
```


```
__AQL explain and/or profile (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce
1.
2.
3. 

__Problem__:
1) Devo creare un nuovo Database con il file CSV avente i seguenti campi:

APPLICATION-SUC, OP-SUC, WS-SUC, JOB-SUC, APPLICATION-PRED, OP-PRED ,WS-PRED, JOB-PRED
A0AH00P1#0000#00,3,W449,A0AH00P1,A0AH00P1#0000#00,NONR,1,START
A0AH00P1#0000#00,255,NONR,END,A0AH00P1#0000#00,W449,3,A0AH00P1

Dove A0AH00P1#0000#00,3,W449,A0AH00P1------>Link _to  Successor------->A0AH00P1#0000#00,NONR,1,START
Ci sono circa 70.000 righe nel foglio EXCEL

2)Dopo mi occorre una query da eseguire in Arangodb per ottenere tutti i successori da un vertice iniziale ad uno finale.
Esempio: A vertice iniziale D vertice finale
Risultato A->B->C->D, con i seguenti campi A0AH00P1#0000#00,A0AH00P1 e A0AH00P1#0000#00,START (prima e ultima colonna del foglio EXCEL)

__Expected result__:

Chiedo scusa se non scrivo in Inglese, ma non lo so parlare bene, ringrazio tutti coloro che vorranno darmi una risposta per risolvere il problema, sono alle prime armi con i database e chiedo cortesemente aiuto a chi è più esperto, ancora grazie a tutti per il possibile aiuto.

**Comment by dothebart** [comment]
english please.

**Comment by maxkernbach** [comment]
Hi @cr00589,

In case you are still facing a problem, please open a new issue in English and fill out the environment template.
Based on automated translation, it seems as you might look for [k Paths](https://www.arangodb.com/docs/stable/aql/graphs-k-paths.html), which will return all paths between any _startVertex_ and _targetVertex_ in your graph.
