### ISSUE TITLE
Any way to config compression / to pass additional options to RocksDB?

### ISSUE THREAD

**Issue by d4h0** [arangodb/arangodb#15516]
Hi,

RocksDB [offers several options to configure how data is compressed](https://github.com/facebook/rocksdb/wiki/Compression). Unfortunately, ArangoDB only [makes one option available to users](https://www.arangodb.com/docs/3.8/programs-arangod-rocksdb.html).

Is there any other way to configure how RocksDB compresses data?

If not: Is there any chance, that more RocksDB options could be added to ArangoDB?

**Comment by dothebart** [comment]
More recent versions of ArangoDB meanwhile offer this option: https://docs.arangodb.com/3.11/components/arangodb-server/options/#--rocksdbcompression-type
