### ISSUE TITLE
OSX build is broken?

### ISSUE THREAD

**Issue by OlivierSohn** [arangodb/arangodb#15535]
Hello,

When running the `make` command on OSX (Mac OS Monterey 12.1) I see this error:

```
[  4%] Performing build step for 'v8_build'
  LIBTOOL-STATIC /Users/Olivier/dev/arangodbbuild/3rdParty/V8/v7.9.317/x64.release/libicui18n.a
Traceback (most recent call last):
  File "./gyp-mac-tool", line 720, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./gyp-mac-tool", line 30, in main
    exit_code = executor.Dispatch(args)
  File "./gyp-mac-tool", line 45, in Dispatch
    return getattr(self, method)(*args[1:])
  File "./gyp-mac-tool", line 274, in ExecFilterLibtool
    if not libtool_re.match(line) and not libtool_re5.match(line):
TypeError: cannot use a string pattern on a bytes-like object
make[3]: *** [/Users/Olivier/dev/arangodbbuild/3rdParty/V8/v7.9.317/x64.release/libicui18n.a] Error 1
make[2]: *** [3rdParty/V8/v8_build-prefix/src/v8_build-stamp/v8_build-build] Error 2
make[1]: *** [3rdParty/V8/CMakeFiles/v8_build.dir/all] Error 2
make: *** [all] Error 2
```

This is how I ran cmake:
```
export CMAKE_OSX_DEPLOYMENT_TARGET=12.1
export MACOSX_DEPLOYMENT_TARGET=12.1
export OPENSSL_ROOT_DIR=`brew --prefix openssl@1.1`
cmake -S ./arangodb -B ./arangodbbuild
```

Anybody else seeing this error or knows how to fix it?
Thanks!

**Comment by OlivierSohn** [comment]
After some googling of the error message I found that it might be because I have python 3 and gyp only works with python 2. I'll try with python 2 and report whether that fixed the problem.

**Comment by OlivierSohn** [comment]
I installed python2 using homebrew, then added this alias:

```
alias python=/usr/local/opt/python@2/bin/python
```

and reran the cmake command then the make command and see the same error.

**Comment by OlivierSohn** [comment]
After removing more folders that contained python3 from the `PATH`, and setting `PYTHONPATH` to `/Library/Python/2.7/site-packages` the error above was fixed. I'll close this issue then, and wait for the build to complete.

**Comment by dothebart** [comment]
please note that python3 is supported, but not 3.10 in any released version, which you probably had.

**Comment by OlivierSohn** [comment]
@dothebart I was using the HEAD of yesterday's master, and my python 3 version is :

```
(base) Oliviers-iMac:hs.hamazed Olivier$ python --version
Python 3.8.5
```
