### ISSUE TITLE
No default root user?

### ISSUE THREAD

**Issue by chris-martin** [arangodb/arangodb#1559]
The [FAQ](https://www.arangodb.com/faq/) says:

> By default, ArangoDB comes with a user “root” that has a password of “” (empty string).

I ran the `arangodb/arangodb:2.7.0` docker image and tried to log in as that user, but it doesn't seem to work.

![arango](https://cloud.githubusercontent.com/assets/399718/10898832/942d2b7c-819c-11e5-9735-e45f8a247c97.png)

**Comment by chris-martin** [comment]
I just switched from `arangodb/arangodb:2.7.0` to `arangodb:2.7.0`, and the latter works without prompting to log in.

**Comment by ifcologne** [comment]
If you use the arangodb/arangodb repository, the password will be generated and printed to the terminal.

    Status: Downloaded newer image for arangodb/arangodb:2.7.0
    
    starting ArangoDB in stand-alone mode
    creating initial user, please wait ...
    2015-11-04T09:34:38Z [15] INFO permanently changing the gid to 999
    2015-11-04T09:34:38Z [15] INFO permanently changing the uid to 999
    ========================================================================
    ArangoDB User: "root"
    ArangoDB Password: "X7GFlFfFn1OTpmvD"
    ========================================================================
    2015-11-04T09:34:48Z [49] INFO permanently changing the gid to 999
