### ISSUE TITLE
Arangodb2.7 AQL - "logical or" in filter statement not covered by query optimizer?

### ISSUE THREAD

**Issue by benjJansen** [arangodb/arangodb#1560]
Hi,
im currently experiencing performance issues with the following query:
```
for c in Col filter c.url == "test.com" || c.name=="tester" return c.name
```
Collection Col contains appr. 2mio documents and url/name have a non-unique hash index on it.

The runtime of this query is >3secs

if i rewrite the query into : 
```
let urlRes=(for c in Col filter c.url=="test.com" return c.name)
let nameRes=(for c in Col filter c.name=="tester" return c.name)
let test =append(urlRes,nameRes,true)
for t in test
    return t
```
which is kind of an aquivalent query, the runtime is ~0.02secs(which is awesome btw)
Might not be the most optimized query, i just wanted to test it.

Is the "logical or" not suitable inside the filter statement? its just a quality of life improvement for me, but would be interesting to know if i maybe am using it wrong in the first place or if theres a bug in the query optimizer or sth like that.

Thanks in advance.

**Comment by dothebart** [comment]
Yes, this is a known issue; currently released ArangoDB versions can't utilize indices for or-combined filter conditions (and thus will do more or less a full collection scan).
The next stable release, 2.8, will be able to fill this gap.

**Comment by benjJansen** [comment]
awesome, looking forward to 2.8.  thanks for the fast response

**Comment by jsteemann** [comment]
To confirm, here's such query's execution plan from 2.7 (not using indexes because of the `OR`):
```
Query string:
 FOR c IN Col FILTER c.url == 'test23.com' || c.name == 'tester45943' RETURN c.name

Execution plan:
 Id   NodeType                     Est.   Comment
  1   SingletonNode                   1   * ROOT
  2   EnumerateCollectionNode   2000000     - FOR c IN Col   /* full collection scan */
  3   CalculationNode           2000000       - LET #1 = c.`url` == "test23.com" || c.`name` == "tester45943"   /* simple expression */   /* collections used: c : Col */
  4   FilterNode                2000000       - FILTER #1
  5   CalculationNode           2000000       - LET #3 = c.`name`   /* attribute expression */   /* collections used: c : Col */
  6   ReturnNode                2000000       - RETURN #3

Indexes used:
 none
```

Here's the one from 2.8 / devel:
```
Query string:
 FOR c IN Col FILTER c.url == 'test23.com' || c.name == 'tester45943' RETURN c.name

Execution plan:
 Id   NodeType          Est.   Comment
  1   SingletonNode        1   * ROOT
  7   IndexNode            2     - FOR c IN Col   /* hash index scan, hash index scan */
  3   CalculationNode      2     - LET #1 = c.`url` == "test23.com" || c.`name` == "tester45943"   /* simple expression */   /* collections used: c : Col */
  4   FilterNode           2     - FILTER #1
  5   CalculationNode      2     - LET #3 = c.`name`   /* attribute expression */   /* collections used: c : Col */
  6   ReturnNode           2     - RETURN #3

Indexes used:
 By   Type   Collection   Unique   Sparse   Selectivity   Fields       Ranges
  7   hash   Col          false    false       100.00 %   [ `url` ]    c.`url` == "test23.com"
  7   hash   Col          false    false       100.00 %   [ `name` ]   c.`name` == "tester45943"
```

The query takes 3.59 seconds in 2.7 on my test data (roughly 2 M documents), and 0.00037 seconds in 2.8 on the same dataset. So yes, 2.8 will fix this.
