### ISSUE TITLE
Same document in more than one collection?

### ISSUE THREAD

**Issue by miguel-porto** [arangodb/arangodb#1561]
Hello,
I just thought it would be useful, for indexing purposes, to be able to have a document belonging to more than one collection (or allowing nested collections), although I understand that this changes the present concept of collection.
Imagine I have several collections which share some attribute. Sometimes I want to fetch documents from one collection only by some particular index of that collection; but other times I want to fetch documents from all of them together, and in this case I would like to have an index on the attribute they all share. The alternative now is to use GRAPH_VERTICES to fetch documents from multiple collections, but that doesn't use an index and it's fairly slow when compared with the FOR v IN collection FILTER by some index...
Or is there another alternative I'm not aware of, to speed up such queries?
Aplogies if this is not the right place to put this question.
All the best,

**Comment by dothebart** [comment]
2.8 is going to bring faster graph operations - However these performance gains are going to be not using V8-related and better handling of filters during the traversals.
You can also fetch documents from other collections referencing them by an ID in a subquery.
have a look at [howto combine edge indices](https://docs.arangodb.com/cookbook/JoinsInAQL.html#using-edge-collections) and the AQL examples, especially [the join section](https://docs.arangodb.com/AqlExamples/Join.html)

**Comment by miguel-porto** [comment]
Thanks, I think the faster graph operations will be the way to solve this because there I can filter vertices by an array of collections, instead of only a single one as in FOR. I wonder if specifying a vertex collection restriction in the graph operation will be as fast as using the FOR v IN collection. If both approaches will be interchangeable in terms of speed, perfect.
The subquery logic is not what I'm looking for in my case, I think, cause it's not a kind of hierarchical data model.
Thanks!
