### ISSUE TITLE
Request hangs when asking for the job result of a document's HEAD request

### ISSUE THREAD

**Issue by Darkheir** [arangodb/arangodb#15639]
## My Environment

* __ArangoDB Version__:        3.8.5
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Docker official image

## Component, Query & Data

__Affected feature__: HTTP Job requests

When creating a job for a HEAD requests to read the headers of a document it is impossible to get the results of the job

## Steps to reproduce

1. Send an async request to get the HEAD of an **existing document**:
    -  `curl --header "x-arango-async: store" -I http://127.0.0.1:8529/_db/test/_api/document/test/foo` 
2. The job appears as done
    - `curl  http://127.0.0.1:8529/_db/test/_api/job/{job_id}` => `200`
3.  When retrieving the result the query never returns
    - `curl -X PUT http://127.0.0.1:8529/_db/test/_api/job/{job_id}` => Runs indefinitely

__Problem__:
The query hangs forever.

__Expected result__:

The query should return with the appropriate headers, no body is expected

__Additional information__:

There is no issue when the document is not found

**Comment by joowani** [comment]
Any update on this issue?

**Comment by HarryCordewener** [comment]
I too would love an update on this.
