### ISSUE TITLE
Build linker issue on macOS 12

### ISSUE THREAD

**Issue by essandess** [arangodb/arangodb#15636]
I'm trying to build a MacPorts port of `arangodb`. Please see https://github.com/macports/macports-ports/pull/13812

Using the standard `cmake` build I'm hitting a link error on macOS 12 that looks like undefined symbols within the `arangodb` compiled objects (log attached).

May I please request some help to make sure that the `cmake` system is providing the correct `-L` or other flags for this build?

Build error:
```
cd /opt/local/var/macports/build/_opt_local_ports_databases_arangodb/arangodb/work/build/3rdParty/boost && /opt/local/bin/ccache /opt/local/bin/ccache /opt/local/bin/clang++-mp-12 -DARANGODB_BITS=64 -DARANGODB_OPENSSL_VERSION=\"1.1.1l\" -DARANGODB_USE_IPO=1 -DASM_OPTIMIZATIONS=1 -DBOOST_ALL_NO_LIB=1 -DBOOST_LOCALE_NO_WINAPI_BACKEND=1 -DBOOST_LOCALE_WITH_ICU=1 -DBOOST_SYSTEM_STATIC_LINK=1 -DBOOST_UUID_RANDOM_PROVIDER_FORCE_POSIX=1 -DNDEBUG -DNROCKSDB_THREAD_STATUS -DOPENSSL_NO_SSL2 -DOPENSSL_VERSION_MAJOR=1 -DOPENSSL_VERSION_MINOR=1 -DROCKSDB_SUPPORT_THREAD_LOCAL -I/opt/local/var/macports/build/_opt_local_ports_databases_arangodb/arangodb/work/build -I/opt/local/var/macports/build/_opt_local_ports_databases_arangodb/arangodb/work/build/lib -I/opt/local/var/macports/build/_opt_local_ports_databases_arangodb/arangodb/work/arangodb-3.8.5/arangod -I/opt/local/var/macports/build/_opt_local_ports_databases_arangodb/arangodb/work/arangodb-3.8.5/lib -I/opt/local/libexec/openssl11/include -isystem /opt/local/var/macports/build/_opt_local_ports_databases_arangodb/arangodb/work/arangodb-3.8.5/3rdParty/V8/v7.9.317/third_party/icu/source/common -isystem /opt/local/var/macports/build/_opt_local_ports_databases_arangodb/arangodb/work/arangodb-3.8.5/3rdParty/V8/v7.9.317/third_party/icu/source/i18n -isystem /opt/local/var/macports/build/_opt_local_ports_databases_arangodb/arangodb/work/arangodb-3.8.5/3rdParty/V8/v7.9.317/third_party/icu/source/io -isystem /opt/local/var/macports/build/_opt_local_ports_databases_arangodb/arangodb/work/arangodb-3.8.5/3rdParty/boost/1.71.0 -Wall -Wextra -Wno-unused-parameter -Wno-deprecated-declarations -march=skylake-avx512 -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mavx -mfma -mbmi2 -mavx2 -mavx512f -mavx512vl -mavx512cd -mavx512dq -mavx512bw -mno-sse4a -mno-xop -mno-fma4 -mno-avx512pf -mno-avx512er -mno-avx512ifma -mno-avx512vbmi  -pipe -I/opt/local/libexec/open
ssl11/include -I/opt/local/libexec/boost/1.71/include -Os -I/opt/local/var/macports/build/_opt_local_ports_databases_arangodb/arangodb/work/arangodb-3.8.5/3rdParty/iresearch/external/absl -DNDEBUG -I/opt/local/libexec/openssl11/include -I/opt/local/libexec/boost/1.71/include -isystem/opt/local/include -stdlib=libc++ -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -pipe -I/opt/local/libexec/openssl11/include -I/opt/local/libexec/boost/1.71/include -Os -I/opt/local/var/macports/build/_opt_local_ports_databases_arangodb/arangodb/work/arangodb-3.8.5/3rdParty/iresearch/external/absl -DNDEBUG -I/opt/local/libexec/openssl11/include -I/opt/local/libexec/boost/1.71/include -isystem/opt/local/include -stdlib=libc++ -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -std=c++17 -stdlib=libc++ -mmacosx-version-min=12.0  -Wno-range-loop-analysis -g0 -O3 -fomit-frame-pointer -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -mmacosx-version-min=12.0   -Wno-deprecated-declarations -std=gnu++17 -MD -MT 3rdParty/boost/CMakeFiles/boost_locale.dir/1.71.0/libs/locale/src/shared/format.cpp.o -MF CMakeFiles/boost_locale.dir/1.71.0/libs/locale/src/shared/format.cpp.o.d -o CMakeFiles/boost_locale.dir/1.71.0/libs/locale/src/shared/format.cpp.o -c /opt/local/var/macports/build/_opt_local_ports_databases_arangodb/arangodb/work/arangodb-3.8.5/3rdParty/boost/1.71.0/libs/locale/src/shared/format.cpp
:info:build undef: __ZTVN8arangodb13ConfigFeatureE
:info:build undef: __ZN8arangodb19ArangoGlobalContextC1EiPPcPKc 
:info:build undef: __ZN8arangodb19ArangoGlobalContext10installHupEv 
:info:build undef: __ZN8arangodb20application_features17ApplicationServerC1ENSt3__110shared_ptrINS_7options14ProgramOptionsEEEPKc
:info:build undef: __ZN8arangodb13ConfigFeatureC1ERNS_20application_features17ApplicationServerERKNSt3__112basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEESC_
:info:build undef: __ZN8arangodb13LoggerFeatureC1ERNS_20application_features17ApplicationServerEb
:info:build undef: __ZN8arangodb18ShellColorsFeatureC1ERNS_20application_features17ApplicationServerE
:info:build undef: __ZTIN8arangodb15ShutdownFeatureE
:info:build undef: __ZN8arangodb14VersionFeatureC1ERNS_20application_features17ApplicationServerE
:info:build undef: __ZN8arangodb19ArangoGlobalContext4exitEi
…
:info:build undef: __ZN8arangodb20application_features18ApplicationFeature7prepareEv
:info:build undef: __ZN8arangodb20application_features18ApplicationFeatureC2ERNS0_17ApplicationServerERKNSt3__112basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEE
:info:build Undefined symbols for architecture x86_64:
```

Build log:
[main.log.zip](https://github.com/arangodb/arangodb/files/7964195/main.log.zip)

**Comment by dothebart** [comment]
Please note that for the time being we only can support Homebrew as build target on MacOS. 

you can probably use llvm-cxxfilt to make these missing symbols to c++ names and search which binaries the linker is missing here. 

Once you've found the C++ file containing that code, you can search for the object file in your compile directory, and whether its in that linker command. (or some .a file which is linked into this)

It can also be that the sequence of files isn't right. Afaik linking is done left to right, hence the sequence of libs, objects is important. So while something may leave an unresolved symbol, that has to be provided by later loaded objects / libs. 
For that reason it may even be, that files / libs are mentioned several times, so later comming files may use symbols from them.

**Comment by essandess** [comment]
> Please note that for the time being we only can support Homebrew as build target on MacOS.

This appears to be a macOS issue for `arangodb`, not a Homebrew or MacPorts issue.

Would you please post or link to the build commands that are supposed to work for [v3.8.5](https://github.com/arangodb/arangodb/releases/tag/v3.8.5) on macOS (with `openssl` 1.1 installed)? I've looked, but do not see any instructions in obvious place like https://github.com/arangodb/arangodb/tree/devel/Installation/homebrew or the comments of https://github.com/arangodb/arangodb/blob/devel/CMakeLists.txt.

If I have a working build on macOS, it's easy to write a MacPorts Portfile for it.

The issue is that a standard `cmake` build fails on macOS, at least macOS 12.

**Comment by dothebart** [comment]
Devel:
```
cmake -DUSE_FAILURE_TESTS=On -DDEBUG_SYNC_REPLICATION=On -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUSE_MAINTAINER_MODE=On -DUSE_ENTERPRISE=Off -DUSE_JEMALLOC=Off -DCMAKE_SKIP_RPATH=On -DPACKAGING=Bundle -DPACKAGE_TARGET_DIR=/Users/jenkins/vm10-mac/oskar/work -DOPENSSL_USE_STATIC_LIBS=On -DOPENSSL_ROOT_DIR=/Users/jenkins/vm10-mac/oskar/work/openssl/openssl-1.1.1m/build/release/no-shared -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 -DUSE_STRICT_OPENSSL_VERSION=On -DCMAKE_CXX_COMPILER=/usr/local/opt/ccache/libexec/clang++ -DCMAKE_C_COMPILER=/usr/local/opt/ccache/libexec/clang -DUSE_CCACHE=Off -DTARGET_ARCHITECTURE=sandy-bridge
```
3.9: 
```
cmake -DUSE_FAILURE_TESTS=On -DDEBUG_SYNC_REPLICATION=On -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUSE_MAINTAINER_MODE=On -DUSE_ENTERPRISE=Off -DUSE_JEMALLOC=Off -DCMAKE_SKIP_RPATH=On -DPACKAGING=Bundle -DPACKAGE_TARGET_DIR=/Users/jenkins/hw36-mac/oskar/work -DOPENSSL_USE_STATIC_LIBS=On -DOPENSSL_ROOT_DIR=/Users/jenkins/hw36-mac/oskar/work/openssl/openssl-1.1.1m/build/release/no-shared -DCMAKE_OSX_DEPLOYMENT_TARGET=10.14 -DUSE_STRICT_OPENSSL_VERSION=On -DCMAKE_CXX_COMPILER=/usr/local/opt/ccache/libexec/clang++ -DCMAKE_C_COMPILER=/usr/local/opt/ccache/libexec/clang -DUSE_CCACHE=Off -DTARGET_ARCHITECTURE=sandy-bridge
```

Yes, it could well be that macos 12 is not yet supported as build host.

**Comment by essandess** [comment]
Thanks! I have a [working MacPorts build](https://github.com/macports/macports-ports/pull/13812) now. I just needed to remove a load library from `LDFLAGS`.

Also, I believe I see an issue with the `cmake` build system: the `_SYSCONFDIR_` directory is incorrectly transposed with `etc` and `PREFIX` when the file `build/lib/Basics/directories.h` is created. The correct path (using MacPorts's default `PREFIX`) should be `/opt/local/etc/arangodb3`, but the `#define` statement says `/etc/opt/local/arangodb3`.

Please let me know if you'd like me to generate a separate issue.

See: https://github.com/macports/macports-ports/pull/13812/files#r798124004

**Comment by dothebart** [comment]
hm, you put in all those ccache things, but specify `-DUSE_CCACHE=Off` ?

**Comment by dothebart** [comment]
please note that the 3.8.5 release has been withdrawn, please go back to 3.8.4 or follow later release anouncements.

**Comment by essandess** [comment]
Thanks again.

> hm, you put in all those ccache things, but specify `-DUSE_CCACHE=Off` ?


Yes, the 3rdParty dependencies still use `ccache`, so that appears to be necessary.

> Will specifying `SYSCONFDIR` help? https://github.com/arangodb/arangodb/blob/devel/cmake/GNUInstallDirs.cmake

No,  `SYSCONFDIR`  is already set to `etc`. The issue is that it's being transposed somewhere with `CMAKE_INSTALL_PREFIX`.

**Comment by dothebart** [comment]
try overriding sysconfdir's calculation with the real value you'd prefer it to be.

**Comment by essandess** [comment]
`arangodb` is now in MacPorts: https://ports.macports.org/port/arangodb/

Thanks again for your help.

**Comment by dothebart** [comment]
great! Meanwhile 3.8.5.1 is available if you may want to upgrade?

**Comment by dothebart** [comment]
another note; 
You're missing the ArangoDB-Starter (which is why you've added the go-dependency):
```
  # the ArangoStarter is in a separate github repository;
  # it is used to easily start single server and clusters
  # with a unified CLI
  resource "starter" do
    url "https://github.com/arangodb-helper/arangodb.git",
        tag:      "0.15.3",
        revision: "814f8be9e5cc613a63ac1dc161b879ccb7ec23e0"
  end

  def install
    ENV["MACOSX_DEPLOYMENT_TARGET"] = MacOS.version if OS.mac?

    resource("starter").stage do
      ENV["GO111MODULE"] = "on"
      ENV["DOCKERCLI"] = ""
      ldflags = %W[
        -s -w
        -X main.projectVersion=#{resource("starter").version}
        -X main.projectBuild=#{Utils.git_head}
      ]
      system "go", "build", *std_go_args(ldflags: ldflags), "github.com/arangodb-helper/arangodb"
    end
```
(quoting the homebrew formular)

**Comment by dothebart** [comment]
We no longer support native Mac server Binaries. 
For the use on M1 machines linux-ARM-Docker containers are available.
