### ISSUE TITLE
Question: return data only from index

### ISSUE THREAD

**Issue by Minstel** [arangodb/arangodb#15635]
Sorry, but I can not find an answer to this simple question in docs.
If collection is filtered by index and only fields used in index are returned (not all fields of index, to be precise), is return data taken from index or looked up in documents?

**Comment by dothebart** [comment]
Hi, 
You're probably searching for the google term "projections"
https://www.arangodb.com/2018/05/data-retrieval-performance-optimizations-in-arangodb-3-3-9/
explains them in detail at the time they were new.

**Comment by Minstel** [comment]
@dothebart Great, thanks) Yeah, I didn't know the meaning of this term.
