### ISSUE TITLE
Support for bindvalues in the AQL-editor

### ISSUE THREAD

**Issue by dothebart** [arangodb/arangodb#1563]
The AQL-editor is valued for its interactive query editing.
However, when copying the query from the editor into an application one would want to use bind values there.
Therefore there is no easy way to use the AQL-editor for production queries, bind values have to be replaced, and re-inserted.

submitted via http://stackoverflow.com/questions/33543318/how-to-use-bind-variables-in-the-arangodb-aql-editor-in-the-web-interface

**Comment by hkernbach** [comment]
added in devel. will be available in 2.8
