### ISSUE TITLE
TRAVERSAL and GRAPH_TRAVERSAL documentation inconsistencies

### ISSUE THREAD

**Issue by stefan-hausmann** [arangodb/arangodb#1566]
Having read the wonderful blogpost http://jsteemann.github.io/blog/2015/01/28/using-custom-visitors-in-aql-graph-traversals/ about using custom visitors when doing graph traversals, I stumbled upon the different documentation parts for the TRAVERSAL (see https://docs.arangodb.com/Aql/GraphFunctions.html) and GRAPH_TRAVERSAL (see https://docs.arangodb.com/Aql/GraphOperations.html) AQL functions.

Seems a lot of the options that can be used with and that are documented for TRAVERSAL can also be used with the GRAPH_TRAVERSAL function, but aren't documented there, e.g.
- visitor
- visitorReturnsResults
- data
- followEdges
- ...

Would it be feasible to simply copy the documentation parts for these options over to the GRAPH_TRAVERSAL documentation section to make clear they can be used with GRAPH_TRAVERSAL, too?
Or are these options not officially supported there?

Additionally, it would be helpful to add links between GraphFunctions and GraphOperations as it is not clear at the first sight that there exist two different types of graph-related traversal functions that can be used.

I'm not sure wether or how this ticket here is related to #1019

**Comment by dothebart** [comment]
I already started out the [toplevel Graphs chapter](https://docs.arangodb.com/Graphs/index.html) to offer a better entrance into ArangoDBs graphing features. For shure we will find more places to improve the documentation ;-)

**Comment by dothebart** [comment]
With ArangoDB 3.0 the traverser has grown up and now can handle all situations the GRAPH_ * - functions used to do. Therefore the documentation is now much more persistent and less irretating.

The Graph overview documentation as introduced with ArangoDB 2.8 continues to be in the Manual: https://docs.arangodb.com/devel/Manual/Graphs/index.html

And the AQL documentation now holds the pattern matching traversals introduced with ArangoDB 2.8 plus the new way of doing shortest path traversals: https://docs.arangodb.com/devel/AQL/Graphs/index.html

We will add notes to the existing blog posts, that this documentation is outdated.

Give the 3.0 RC a shot - we're eager to get feedback.
I'm closing this issue now.
