### ISSUE TITLE
Function for graph pattern matching

### ISSUE THREAD

**Issue by miguel-porto** [arangodb/arangodb#1567]
Hi,
I really miss a graph pattern matching function, something like a "regex" but for graph patterns. Something like the syntax used in Cypher for patterns. Imagine for example:

    FOR path in GRAPH_PATTERN(
    (a:collectionA)-[b:collectionB{current:true}]->(v:collectionA)<-[c:collectionB]-(),(v)<-[]-()
    ) RETURN {path.v,path.b}

This would return an array of vertices of collection A (and the respective 'b' edge) which would have three incoming edges, one of collection B (with the current attribute set to true and coming from a vertex of collection A), other from collection B, and other from any collection.

I hope I made my idea clear. This would greatly simplify querying the graphs for a given pattern. While this is currently possible in AQL, it's quite cumbersome to write.
Cheers,
Miguel

**Comment by dothebart** [comment]
We're currently working hard to get new features into reality - with a bit of luck you may get a nice x-mas present ;-)

**Comment by CoDEmanX** [comment]
Hm... I think I saw some unit test that used some nifty new AQL graph querying syntax, but couldn't find it again - and therefore believed it must've been a dream. Maybe it was real after all &nbsp; ![w00t](https://cloud.githubusercontent.com/assets/1309249/11116638/344c155c-8934-11e5-95e8-244bb5a5d43b.gif)

**Comment by miguel-porto** [comment]
Looking forward to the new version!!
You've been doing a great job with ArangoDB, by the way.

**Comment by CoDEmanX** [comment]
That's the test I mentioned:
https://github.com/arangodb/arangodb/blob/JHMH/js/common/tests/aql-graph-cypher-comparision-spec.js#L127

**Comment by miguel-porto** [comment]
This does look great!!! Greater than what I would ever dare to ask!

**Comment by dothebart** [comment]
ArangoDB 2.8 in beta now. The devel documentation for this is available at https://docs.arangodb.com/devel/Aql/GraphTraversals.html ; Please note that it (devel) already contains a modification in the samples that will not work with the 2.8 beta, the you have to replace the require `@arangodb` to look like `org/arangodb`.

**Comment by miguel-porto** [comment]
Looks powerful, although I did not try it yet. From a first glimpse, I only note that these traversals require one starting node only, but frequently we don't want to traverse from a given node, but to find a given pattern in the whole graph. This would need one to nest the traversal FOR inside another FOR iterating over all nodes. I wonder if this nesting could have any negative impact on the query optimizer... wouldn't it be better, from an optimization point of view, to allow the traversal to work without a starting node (e.g. by specifying a (an array of) collection(s) as the "starting node")?

**Comment by dothebart** [comment]
You can exactly do that: make the starting point a variable. For shure you will get one traversal per value of the variable. See [this example combining traversals with geo queries](https://docs.arangodb.com/devel/AqlExamples/CombiningGraphTraversals.html)

**Comment by gvelesandro** [comment]
I don't think this issue should be closed. The current (2.8) implemtation doesn't offer a pattern based path matching option. For example, there is no simple way to articulate the following pattern in AQL:

Find two friends (a and b) whose ancestors (up to 5 steps) are A and B where A._id is 1 and B._id is 2. 

This pattern requires a one-step friendship to be stitched to n-step ancestor paths on both ends, where both A and B end points are constrained.  

In comparison, such a pattern can be easily defined in Neo4J.

**Comment by weinberger** [comment]
I just saw this. With our new pattern matching such a query would looks like this:

**Comment by mchacki** [comment]
Hi i think you can get the pattern you have described in the following way:
Assuming you have a vertex collection `persons` holding all the people.
And two edge collections `friends` (for friend relations, direction does not matter here) and `parents` (for parent relations say the direction here is mother -> daughter)

Then the AQL to receive two friends `a` and `b` with the ancestors `c` and `d` having `c._key == 1` and `d._key == 2`  looks like this:

    FOR a IN 1..5 OUTBOUND 'person/1' parents // Identify the friend a having an ancestor c
      FOR b IN 1 ANY a friends // Identify that a and b are direct friends
        FOR d IN 1..5 INBOUND b parents // go the ancestor tree upwards to find ancestors of b
          FILTER d._key == '2'  // Only let through those having the ancestor d
            RETURN {a, b} // Gotcha

**Comment by gvelesandro** [comment]
Thanks @mchacki.  I am unable to make this query to work with a `0..5` step assumption on the `ancestor` traverse.  In other words,  this variation of your query causes an exception:

```
FOR a IN 0..5 OUTBOUND 'person/1' parents 
  FOR b IN 1 ANY a friends 
    FOR d IN 0..5 INBOUND b parents 
      FILTER d._key == '2'  
        RETURN {a, b} 
```

Am I overlooking something obvious?

**Comment by baslr** [comment]
@gvelesandro you cant use 0.. see #1711 (AQL new traversal syntax - minDepth 0)

**Comment by gvelesandro** [comment]
Thanks @baslr. Is there a workaround for the query above? Our use case requires a constraint to be imposed on the 'friend' or his 'ancestors'.

**Comment by baslr** [comment]
https://github.com/arangodb/arangodb/issues/1711#issue-132023598

you could use the TRAVERSAL ALQ function https://docs.arangodb.com/Aql/GraphFunctions.html

**Comment by CoDEmanX** [comment]
Note that all graph functions were removed in 3.0, but 0..5 is now possible.
