### ISSUE TITLE
VPack error: Array structure is invalid

### ISSUE THREAD

**Issue by JensForstmann** [arangodb/arangodb#15682]
## My Environment

* __ArangoDB Version__: 3.8.3 / 3.8.4
* __Deployment Mode__: Cluster / Single Server
* __Deployment Strategy__: Kubernetes / Manual Start
* __Configuration__: 3 nodes (3 coordinators, 3 db servers, 3 agents)
* __Infrastructure__: Azure Kubernetes Services
* __Operating System__: Ubuntu 18.04 / Windows 11
* __Total RAM in your machine__: 16gb per node / 32gb on windows
* __Disks in use__: ssd node os + SSDs for persistence
* __Used Package__: Docker - official Docker library / Zip package from arangodb.com

## Component, Query & Data

__Affected feature__:
HTTP API Transaction: `/_api/transaction` with [arangox](https://github.com/ArangoDB-Community/arangox) and [velocy_pack](https://github.com/ArangoDB-Community/velocy_pack) (Elixir project)

__Example code__:
This example will reproduce the error
```elixir
defmodule VPE do
  require Logger

  def run do
    options = [
      endpoints: "http://127.0.0.1:8529",
      username: "root",
      password: "",
      pool_size: 1,
      show_sensitive_data_on_connection_error: true
    ]

    {:ok, conn} = Arangox.start_link(options)

    body = %{
      "action" => "function (){return true;}",
      "params" => %{
        "changes" => [
          %{
            "nodeType" => "C",
            "operationType" => "V",
            "nodeId" => "00000000-0000-0000-0000-000000000000",
            "value" => %{
              "createdBy" => "00000000-0000-0000-0000-000000000000",
              "createdAt" => 1_234_567_890_123,
              "updatedBy" => "00000000-0000-0000-0000-000000000000",
              "updatedAt" => 1_234_567_890_123,
              "state" => "XXXXXXXX",
              "name" => "XXX",
              "hidden" => true
            }
          }
        ]
      },
      "collections" => %{}
    }

    response = Arangox.post(conn, "/_api/transaction", body)

    Logger.debug(inspect(response, pretty: true))
  end
end
```

## Steps to reproduce

1. Unzip windows server zip
2. Start server
3. Run elixir example code above (or use this reproduction repo: https://github.com/JensForstmann/velocy-pack-error)

__Problem__:

Server is responding with an error:

```
[info]  {:error,
 %Arangox.Error{
   endpoint: "http://127.0.0.1:8529",
   error_num: 4,
   message: "VPack error: Array structure is invalid (exception location: D:\\hw15-windows\\oskar\\work\\ArangoDB\\arangod\\GeneralServer\\RestHandler.cpp:514). Please report this error to arangodb.com",
   status: 500
 }}
```

__Expected result__:

Server accepting the transaction:

```
[info]  {:ok,
 %Arangox.Response{
   body: %{"code" => 200, "error" => false, "result" => true},
   headers: %{},
   status: 200
 }}
```

**Comment by JensForstmann** [comment]
Not sure if this is a server side issue... or a client side ([velocy_pack elixir lib](https://github.com/ArangoDB-Community/velocy_pack)) one. But since the server responded with the error to report it to arangodb.com I opened the issue here. Hope that was okay

**Comment by mpoeter** [comment]
@JensForstmann thank you for the report! I would assume that it is more likely an issue in the Elixir `velocy_pack` implementation, but I can check both sides anyway. :)

**Comment by mpoeter** [comment]
Yes, I am the original author of the velocy_pack lib. :) I have just pushed a fix for the encoder. Will ask @suazithustra to create a new release.

**Comment by suazithustra** [comment]
on it

**Comment by JensForstmann** [comment]
🎉

@suazithustra Thanks for the new release

and thanks @mpoeter for the fix
