### ISSUE TITLE
foxx: console.log warn error debug doesn't work

### ISSUE THREAD

**Issue by realdog** [arangodb/arangodb#1570]
I don't know why the console doesn't work
I can't find anything in log file
```
 controller.post('/find', function (req, res) {
    var collection = Account_repo.collection.name();
    var username = req.parameters.user.username;
    var password = req.parameters.user.password;
    //var password = req.parameters.password;
    console.debug("-------------------------------------------------");
    console.debug("%s", collection);  
    console.debug("%s", username);
    console.debug("%s", password);
    //console.log(password);
    //return res.json({username:"test1"});
    return res.json(
      db._query(searchQuery, {
        '@collection':collection,
        'username': username
      }).toArray()
    );  
      
    //res.json({username: "test"});
  }).bodyParam('user', {
    type: joi.object().keys({
      username: joi.string(),
      password: joi.string()
    }), 
    description: 'The Account you want to find'
  });
```

**Comment by realdog** [comment]
it's ok....i write this code, and worked
```
var console = require("console");  
console.log(username);
```

**Comment by dothebart** [comment]
Yes, you're right. I'll add that to ... https://docs.arangodb.com/devel/Foxx/Develop/Console.html

**Comment by pluma** [comment]
@dothebart Don't.

The problem is that the Foxx console doesn't log anything to the arangod log and there isn't currently a UI for querying the `_foxxlog` collection.

@fceller What is the right approach here? Should we deprecate the functionality and restore the global console object in Foxx? Should we pass all Foxx console logging to the global console? Should we create a web interface and be more explicit about this behaviour?

**Comment by pekeler** [comment]
Yes please: global console for logging to stdout and call that _foxxlog thingy something else.

**Comment by pluma** [comment]
@fceller we should probably use the global console in ArangoDB 3.0 again. We can still provide the Foxx console via import. Your call.

**Comment by pluma** [comment]
The Foxx console has been modified to also log to the global console by default.
