### ISSUE TITLE
How to know the result of update 

### ISSUE THREAD

**Issue by realdog** [arangodb/arangodb#1572]
I wrote the code ,i want to know the result of update,but the 'results' is undefined, i want to know how many recorders has be updated....
```
  Repository.prototype.updatePassword = Foxx.createQuery({
    query: 'for user IN watchdog_account filter user.username == @username update user with {password: @password} in watchdog_account',
    params: ['username', 'password'],
    transform: function(results){
      var console = require("console");   
      console.log(results);
    }
  });
```

**Comment by CoDEmanX** [comment]
Have a look here about the pseudo-variables OLD and NEW:
https://docs.arangodb.com/Aql/DataModification.html#using-old-and-new-in-the-same-query

**Comment by realdog** [comment]
@CoDEmanX Thank u very much. But when i update 10000 recorders....the results....so large

**Comment by dothebart** [comment]
curerntly the statistics aren't available via the `Foxx.createQuery()`. however, `db._query()` has them:
```
var a = db._query("FOR u IN _users RETURN u")
a.getExtra()
{ 
  "stats" : { 
    "writesExecuted" : 0, 
    "writesIgnored" : 0, 
    "scannedFull" : 110, 
    "scannedIndex" : 0, 
    "filtered" : 0 
  }, 
  "warnings" : [ ] 
}
```

**Comment by pluma** [comment]
Foxx.createQuery is too high-level. Just use db._query instead.
