### ISSUE TITLE
Anybody can help me ?I want know how many records has been changed (or  by delete) by using createQuery( update delete ....etc...)

### ISSUE THREAD

**Issue by realdog** [arangodb/arangodb#1573]
I defined a repository in my foxx,but i don't know how to do ......i just want to know how may records has been changed or deleted....thanks
```
  Repository.prototype.updatePassword = Foxx.createQuery({
    query: 'for user IN watchdog_comment filter user.id == @id update user with {content: @content} in watchdog_comment',
    params: ['id', 'content']
  });
```

**Comment by CoDEmanX** [comment]
The HTTP API can optionally return a count, but I don't know if it can return the count without returning the actual documents that changed:
https://docs.arangodb.com/HttpAqlQueryCursor/AccessingCursors.html

**Comment by realdog** [comment]
what should i do ? @fceller @dothebart @pluma @hkernbach

**Comment by dothebart** [comment]
hm, if you use the db._query() you will get a cursor. on the cursor you then cat call `getExtra()` which gives you :
```js
a=db._query("for u in _users return u");
a.getExtra()
{ 
  "stats" : { 
    "writesExecuted" : 0, 
    "writesIgnored" : 0, 
    "scannedFull" : 1, 
    "scannedIndex" : 0, 
    "filtered" : 0 
  }, 
  "warnings" : [ ] 
}
```

https://docs.arangodb.com/Upgrading/UpgradingChanges23.html
hopefully foxx has wrapped that @pluma?

**Comment by jsteemann** [comment]
@realdog @dothebart @pluma It seems that the query generated and run via `Foxx.Repository.createQuery()` only returns the raw results, but no result meta data, such as the number of modified documents. I think this should be added because it's not an exotic use case.

However, the following code will do this (inside or outside of Foxx):
```js
var db = require("org/arangodb").db; 
// set bind parameter values
var bindParameters = { "key": "someId", "@collection" : "_users" };
// set query string
var query = db._query("FOR doc IN @@collection FILTER doc._key != @key RETURN doc", bindParameters);
// run query
var result = query.toArray();
// get statistics
var stats = query.getExtra();

// print results
require("console").log(result, stats);
```

**Comment by pluma** [comment]
The `Foxx.createQuery` function is intended as a high-level wrapper around `db._query` and does not expose the underlying result object directly.

The documentation should be updated with a reference to `db._query` and why you may want to chose one over the other. We should also probably rethink this feature for 3.0 as I think the distinction is not very easy to understand.

**Comment by realdog** [comment]
@pluma thank u very much

**Comment by realdog** [comment]
@pluma  I  put the code into 'repository' ， but not into controller......beacuse i think..... maby ............its more efficient....
