### ISSUE TITLE
Removing document does not remove connected edges

### ISSUE THREAD

**Issue by specimen151** [arangodb/arangodb#1575]
Hi
I don't know if this is a bug or a feature request, but somehow it felt wrong. On the page https://www.arangodb.com/key-features/ it states that there should be consistency.

I created two vertices/documents and an edge between them. Looked it up in the web-based graph editor, and everything looked fine. Then I deleted one of the documents via an `AQL REMOVE IN` statement (how about `REMOVE FROM`? reads better).

After the operation, I expect either to get an error that there are edges connected to the document (like foreign keys in SQL) or to have the edge deleted automatically. (An option to choose auto-delete vs. exception would be nice.)

The result was neither - the edge is still there in my edge collection pointing to a non-existing (deleted) document.

**Comment by dothebart** [comment]
we added an explanation for this just some days ago - have a look at: https://docs.arangodb.com/devel/Aql/GraphFunctions.html#graph-consistency

**Comment by specimen151** [comment]
Is this available via AQL? I get the feeling that AQL is lacking compared to the JavaScript API, is this correct?

**Comment by dothebart** [comment]
the described graph functionality is available in AQL, but is implemented partially in Javascript.
Version 2.8 will bring more native implementations of graph traversals to AQL.

**Comment by webgini** [comment]
sdsdsadsad

**Comment by ilearnio** [comment]
@dothebart The link is no longer working. Where can I find this section in v3 docs?

**Comment by ilearnio** [comment]
I eventually found it https://docs.arangodb.com/2.8/Aql/GraphFunctions.html#graph-consistency but it doesn't explains how to remove a document together with it's related edges.

I found a way to do that in 2 queries. Is it correct or maybe there is some better way?

```js
db._query(aql`
  FOR s IN ${subtitlesEdges}
    FILTER s._to == ${_id}
    REMOVE s IN ${subtitlesEdges}
`)

subtitlesCollection.remove({ _key })
```

**Comment by dothebart** [comment]
its not yet implemented in AQL. I guess http://stackoverflow.com/questions/35074545/safe-removal-of-vertexes-in-arangodb-using-ids is a followup of this ticket, which shows some examples of howto achieve this.

This won't work if you reference a vertex from another graph.

**Comment by baslr** [comment]
@ilearnio 
I would prefer a custom transaction. Because then I know got all xor nothing.
Your approach isn't consistent.
Currently AQL cant remove documents from multiple collection. `Each REMOVE operation is restricted to a single collection`

**Comment by ilearnio** [comment]
@baslr good point. I'll wrap it into a transaction. Thanks for hint

**Comment by amarjeetanandsingh** [comment]
Hi @dothebart 
Any implementation for golang driver to auto remove edges on document deletion?

**Comment by dothebart** [comment]
Hi @amarjeetanandsingh, you should use the graph API to remove vertices, which then will in term invoke the server API that will take care of connected edges.
