### ISSUE TITLE
require behaves in surprising ways

### ISSUE THREAD

**Issue by pluma** [arangodb/arangodb#1577]
Basically, we copied node's `node_module` logic so `require` now walks the entire tree before giving up and attempting to interpret global module names as relative paths.

e.g.

1. Install ArangoDB in the home directory (or a subdirectory therein).
2. npm install a module (e.g. [lol](https://www.npmjs.com/package/lol)) in your home directory
3. Add a JS file with the same name to your Foxx app
4. Try to require the file as a global name (e.g. `require("lol")`)
5. The module from the node_modules folder in your home directory will be loaded

**Comment by pluma** [comment]
Let's also make sure require does the right thing for Foxx services. The require cache is likely global, not service-specific at the moment.

**Comment by pluma** [comment]
I can't reproduce this problem anymore. Have we accidentally fixed this?

**Comment by jsteemann** [comment]
* create a file named `test.js` that contains broken JavaScript code.
* put that file into `~/node_modules`
* start arangod from `~/ArangoDB/` (or some other subdirectory directly below `~`)
* run `make unittests-shell-client` to produce the error

**Comment by pluma** [comment]
This should no longer be happening now.
