### ISSUE TITLE
Create sample graphs from the Webinterface

### ISSUE THREAD

**Issue by dothebart** [arangodb/arangodb#1578]
Please modify the graph generation dialog to offer a new tab to load the sample graphs from the documentation into the current ArangoDB instance, so the user can have a better head start on using the graph editor.

The current mention in the documentation:
https://docs.arangodb.com/devel/Graphs/

describes to load them this way from arangosh
```
arangosh> var examples = require("org/arangodb/graph-examples/example-graph.js");
arangosh> var g = examples.loadGraph("knows_graph");
```

We currently have 3 example graphs: `knows_graph`, `social`, `routeplanner`

Next some screenshots about working with these graphs can then better explain [the graph viewer in the documentation](https://docs.arangodb.com/devel/WebInterface/index.html#graphs-tab) .

**Comment by dothebart** [comment]
maybe creating some screenshots working with these graphs can then better explain the graph viewer.

**Comment by hkernbach** [comment]
added in branch: JHMH
