### ISSUE TITLE
Please Please give .tar compiled version for arangodb like mongodb. 

### ISSUE THREAD

**Issue by webgini** [arangodb/arangodb#1580]
Hello , i am trying to understand the filesystem and all the programs and file associated with arangodb , but i don't know where you guys have stored it using .deb package , it is becoming more less controlled , and thats why is it very less likely that i am going to use. please make compiled .tar version which includes all the files and programs , so , i can do all the work easily and manually , with full control. trust me , people needs it for better exploration and control. thank you in advance guys.

**Comment by dothebart** [comment]
you probably know that you can simply use [alien -t](https://wiki.debian.org/Alien) to generate tarballs from .debs? 
The clear advantage of .debs (or rpms) are that they will manage dependencies and stop you from running into subtle bugs from libraries having wrong symbols etc.
They also manage stuff like adding users, registering init scripts, setting file permissions and doing a good cleanup on removal.
Its rather heading in the different direction, users want complete VM images (that maintain an easy upgrade paths) or automated meta scripts like the docker library that will install ArangoDB.
They're all very good reason why most of the Linux world evolved from Slackwares system of simply rolling out tarballs.

**Comment by neunhoef** [comment]
With the installed .deb file you can do
    dpkg -L arangodb
to see all installed files.
You can even do
    dpkg --info <.deb file>
(if I remember correctly) without installing it. And finally, a .deb is just a cpio archive containing a .tar.gz and some more stuff, as far as I remember.

**Comment by dothebart** [comment]
More short:
`ar vx arangodb_*_amd64.deb`

gives you: `data.tar.gz`
