### ISSUE TITLE
Aborting query execution in the WebUI should actually cancel the query on the server

### ISSUE THREAD

**Issue by dothebart** [arangodb/arangodb#1582]
as mentioned in #1571 the Aardvark webui uses synchroneous REST calls to send AQL-queries to the server.
Therefore the <cancel> button will just abort the HTTP request waiting for the server reply with the result, the Query will continue to be executed on the server.
Since the webui didn't get a response, it can't know the Query ID and thus not attempt to cancel its execution on the server.

Using [Asynchroneous execution on the server](https://docs.arangodb.com/HttpAsyncResultsManagement/index.html) this can be achieved. 
The webinterface then can react to the cancel button by sending a [cancel operation](https://docs.arangodb.com/HttpAsyncResultsManagement/index.html#cancel-async-job) to the server.
To fetch the actual results of the query [it has to poll for them](https://docs.arangodb.com/HttpAsyncResultsManagement/index.html#return-result-of-an-async-job).

**Comment by hkernbach** [comment]
added into devel branch.
ffbf9d57e8823de6cae09dd075b388c98604f1b1
