### ISSUE TITLE
3.9.0 sporadically database not found error

### ISSUE THREAD

**Issue by coronabytes** [arangodb/arangodb#15826]
## My Environment

* __ArangoDB Version__:        3.9.0
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               
* __Infrastructure__:               VM
* __Operating System__:        Ubuntu 20.04
* __Total RAM in your machine__:        8GB
* __Disks in use__:        SSD
* __Used Package__:              Ubuntu .deb

## Component, Query & Data

__Affected feature__:

__Problem__:
Since the 3.9.0 update, our arango server on ubuntu sometimes claims database not found and all queries fail.
After a server restart all works fine for some hours and then it begins failing again.

Some poeple claim somtimes it resolves itself without a restart (investigating)

No info whatsoever in the arango logs

update:
downgraded to 3.8.6 and restored backup - no error so far

the application logs are full of arango errors with the following message
"not authorized to execute this request"
errorNum 11

using jwt auth
was there some change 3.8 to 3.9?
like access token timeout?

```
 Revive startup parameter `--server.session-timeout` to control the timeout for
  web interface sessions and other sessions that are based on JWTs created by
  the `/_open/auth` API.

  This PR also changes the default session timeout for web interface sessions to
  one hour. Older versions of ArangoDB had longer session timeouts.
```

so not only web sessions but all jwt sessions?

**Comment by coronabytes** [comment]
found an issue with the refresh jwt logic in my driver.
probably never had an application running longer than 30days...

**Comment by dothebart** [comment]
good, thanks!
