### ISSUE TITLE
Web interface 2.7 - logo for edge collections ?

### ISSUE THREAD

**Issue by kibarda** [arangodb/arangodb#1586]
the logo image for edge collections seems to have disappeared in web interface 2.7. ( ubuntu 14.04)

**Comment by hkernbach** [comment]
Could you please provide some more information? Couldn't reproduce this issue. I've installed ArangoDB 2.7.1 with Ubuntu Package Manager on Ubuntu 14.04. (https://www.arangodb.com/download/ - arangodb_2.7.1_amd64.deb (49 MByte)). Maybe it could help to clear your browser cache. 

![image](https://cloud.githubusercontent.com/assets/1244163/11376647/33c23c1c-92e2-11e5-931e-f6ceadf0c252.png)

**Comment by kibarda** [comment]
It was still on 2.7.0. 
I've installed 2.7.1 on another machine and it is OK.  
I guess I can close this ...
