### ISSUE TITLE
Docs should clarify that ArangoDB IDs are strings

### ISSUE THREAD

**Issue by pluma** [arangodb/arangodb#1587]
ArangoDB keys are arbitrary strings even though the automagically generated ones are typically numeric. This can be misleading for beginners (see #1408).

**Comment by jsteemann** [comment]
Is this sufficient? https://github.com/arangodb/arangodb/commit/a27f7faa32b3d7a2f8d273b0eb0f81a453eb279e

**Comment by pluma** [comment]
See my comment. Other than that lgtm :shipit:

**Comment by jsteemann** [comment]
:+1:
