### ISSUE TITLE
Documentation: Drop a graph - dropCollections attribute

### ISSUE THREAD

**Issue by hkernbach** [arangodb/arangodb#1588]
Currently the dropCollection URL parameter is listed under query parameter. This is a mistake. Please add "dropCollections" to url parameter. 

![image](https://cloud.githubusercontent.com/assets/1244163/11372857/e91e48fc-92cf-11e5-8370-157c119326fd.png)

**Comment by jsteemann** [comment]
There is a distinction between URL and query parameters:
* the *URL parameters* are part of the base URL (i.e. in front of the `?`)
* the *query parameters* are parameters that are part of the query string (i.e. behind the `?`)

**Comment by pluma** [comment]
Do we explain the distinction between URL parameters, query parameters and (I presume) body parameters in the intro of the HTTP docs? Otherwise we should probably do so to avoid confusion.

**Comment by jsteemann** [comment]
Probably not, but I don't think that too many explanations will improve the situation.
Apart from that, we should *URL parameters* to *path parameters* because that's what they are.

**Comment by pluma** [comment]
Yes, that would likely help.

**Comment by pluma** [comment]
I've disambiguated "URL parameter" wherever it appeared: 7538d713336e29aa16af191a326f08f0cc8005d7

**Comment by hkernbach** [comment]
also added the dropCollection attribute to the documentation example 8a6942a2996ba6ce555cdfbb8e7e90419e11e4d9
