### ISSUE TITLE
can't connect to arangodb from a different machine

### ISSUE THREAD

**Issue by Moubassher** [arangodb/arangodb#15894]
## My Environment

* __ArangoDB Version__:        3.9.0
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:  Manual Start
* __Configuration__:               
* __Infrastructure__:               none - using my own machine.
* __Operating System__:        Windows 10
* __Total RAM in your machine__:        8 GB
* __Disks in use__: HDD on both machines.
* __Used Package__:              zip package.

## Component, Query & Data

__Affected feature__:
arangosh

## Steps to reproduce

1. download arangodb community edition on two machines (manually, using the zip package).
2. run the server daemon on one machine.
3. from the command-line, run a command like:
arangosh  --server.endpoint tcp:/[ip.address]:8529 --server.username root --server.database dbName --server.authentication false

Notes: 
1. I get the IP address from the command ipconfig/ all (same as the one I get from websites that show your ip address).
2. I can connect to localhost, no problem. As well as to my machine using my IP address obtained using the method above.
3. I disabled the firewall altogether and allowed all inbound and outbound connections momentarily to see if this was a firewall issue. Didn't work.
4. I tried turning authentication on and off (from the command the shell is started with and config of arangodb); same result: unable to connect.

__Problem__:
remote machine says: "unable to connect".

__Expected result__:
connecting to my arangoDB server process.

**Comment by dothebart** [comment]
Hi, 
by default arangodb will only bind localhost (127.0.0.1) which is only available on that verry machine.
You need to edit the `etc/arangod.conf` and change this line:
```
endpoint = tcp://127.0.0.1:8529
```
to
```
endpoint = tcp://0.0.0.0:8529
```
and afterwards start/stop the arangodb service:
```
sc stop arangodb
sc start arangodb
```

**Comment by Moubassher** [comment]
@dothebart, hello. I forgot to say that I changed the config of arangod.exe frequently to what my IP address is before launching it. Changing the endpoint to 0.0.0.0 would not connect, but after some research, it turned out this might be a connection problem. As in, I'm using a mobile broadband connection whose upload is not that great. Pretty sure this is the problem, so I wonder if I should close the issue.
