### ISSUE TITLE
AQL filter doc "IN" json misbehave

### ISSUE THREAD

**Issue by roman1720** [arangodb/arangodb#1589]
Sample collection:

db._create("foo");
db.foo.save({"foo":"foo1","bar":"bar1"});
db.foo.save({"foo":"foo2","bar":"bar2"});
db.foo.save({"foo":"foo3","bar":"bar3"});
db.foo.save({"foo":"foo4","bar":"bar4"});
db.foo.save({"foo":"foo5","bar":"bar5"});
db.foo.save({"foo":"foo6","bar":"bar6"});
db.foo.save({"foo":"foo7","bar":"bar7"});
db.foo.save({"foo":"foo8","bar":"bar8"});
db.foo.save({"foo":"foo9","bar":"bar9"});
db.foo.save({"foo":"foo10","bar":"bar10"});

This query returns only 9 documents instead of 10:

let l=(
for foo in foo 
  filter {foo:foo.foo,bar:foo.bar} in [
{"foo":"foo1","bar":"bar1"},
{"foo":"foo2","bar":"bar2"},
{"foo":"foo3","bar":"bar3"},
{"foo":"foo4","bar":"bar4"},
{"foo":"foo5","bar":"bar5"},
{"foo":"foo6","bar":"bar6"},
{"foo":"foo7","bar":"bar7"},
{"foo":"foo8","bar":"bar8"},
{"foo":"foo9","bar":"bar9"},
{"foo":"foo10","bar":"bar10"}]
    return foo)
return length(l)

If I rewrite query it returns 10 as it should:

let l=(
for bar in [
{"foo":"foo1","bar":"bar1"},
{"foo":"foo2","bar":"bar2"},
{"foo":"foo3","bar":"bar3"},
{"foo":"foo4","bar":"bar4"},
{"foo":"foo5","bar":"bar5"},
{"foo":"foo6","bar":"bar6"},
{"foo":"foo7","bar":"bar7"},
{"foo":"foo8","bar":"bar8"},
{"foo":"foo9","bar":"bar9"},
{"foo":"foo10","bar":"bar10"}]
for foo in foo
  filter bar.foo==foo.foo && bar.bar==foo.bar
    return foo)
return length(l)

**Comment by jsteemann** [comment]
Fixed in 2.6, 2.7 and devel.
