### ISSUE TITLE
Feature request: Improve the Graph Viewer

### ISSUE THREAD

**Issue by specimen151** [arangodb/arangodb#1590]
I hope this is the right forum: The graph viewer seems very limited.

I'd like to quickly find a vertex (which I can do with the filter, but a dedicated search would also be nice), and then see all nearby vertices. The way it works now (2.7.1) is that I can filter to find my vertex, but there is no way to reset the filter, when I try, then some completely different vertices are shown.

I'd like to find my vertex, and then explore the graph from there (click on a vertex to show all connections, and which labels are on the edges etc, maybe filter on a specific edge type or properties on the edges etc). To really work with and understand the data.

**Comment by dothebart** [comment]
Yes, the graph viewer has some room for improvements. @hkernbach is currently working on it collecting ideas. Thanks for the feedback.

**Comment by hkernbach** [comment]
We are now collecting all issues regarding the graph viewer in a new ticket: #1595
