### ISSUE TITLE
PDF manual not searchable

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangodb#1591]
https://docs.arangodb.com/manual.pdf must be rendered weirdly because I can't do simple text searches in that document.

**Comment by dothebart** [comment]
Hm, WFM? When opened in Iceweasel the embedded pdf browser works with ctrl+f? 
In general, we use [gitbook with calibre for this](https://github.com/arangodb/arangodb/blob/devel/README_maintainers.md#documentation) if you know howto make it work better, comments welcome ;-)

The gitbook config aside of the regular html in tree build is like that:

```
cat > Documentation/Books/Users/book.json <<EOF
{
  "gitbook": ">=2.0.0",
  "title": "ArangoDB ${VERSION_NUMBER} Documentation",
  "author": "ArangoDB GmbH",
  "description": "Official manual for ArangoDB - the multi-model NoSQL database",
  "plugins": ["toggle-chapters","piwik","addcssjs"],
  "pluginsConfig": {
      "piwik": {
          "URL": "www.arangodb.com/piwik/",
      "siteId": 12
      },
      "addcssjs": {
          "js": ["styles/header.js"],
          "css": ["styles/header.css"] 
      }
  },
  "pdf": {
    "fontSize": 12,
    "toc": true,
    "margin": {
      "right": 60,
      "left": 60,
      "top": 35,
      "bottom": 35
    }
  },
  "styles": {
    "website": "styles/website.css"
  }
}
EOF
```

and then build it with:

    gitbook pdf

**Comment by CoDEmanX** [comment]
What do you use as PDF viewer?

Searching works fine the following (tried "Foxx" as seach phrase):

- Windows 8.1, 64bit
  - Adobe Acrobat v11.0.07
  - Foxit Reader Portable v7.2.2.929
  - Firefox v42.0 (PDF.js, through local apache server)
  - Chrome v49.0.2572.0 (Canary)
- Android 6.0 running on Nexus 5
  - PocketBook v1.18.11488
  - Google Drive (PDF Viewer) v2.3.453.15.35
  - Dropbox (PDF Viewer) v3.0.4.8

It **does not work** in the Adobe Acrobat app for Android, v15.3!
It searches for 2 minutes, then reports "nothing found".

**Comment by pekeler** [comment]
I'm on a mac and have that problem with the built-in Preview app. When double clicking a word, it just selects a character instead of the word.

Testing this with Google Chrome which uses a different PDF viewer, I can search text. But he highlighted result looks funky.

**Comment by pekeler** [comment]
Looks like gitbook is just not very good. https://www.gitbook.com/download/pdf/book/maomaotwiter/gitbook-sample has the same problem.

**Comment by CoDEmanX** [comment]
I don't think it's gitbook's fault, it's rather [ebook-convert](http://manual.calibre-ebook.com/cli/ebook-convert.html) (part of Calibre) that is to blame. It is used to turn the markup/markdown into PDF.

Can you please try the following 3 PDFs? I optimized/archived them using Adobe Acrobat:
https://drive.google.com/folderview?id=0B4i9nvp7_qCsbzE4ZVF3TkMtWVk&usp=sharing

**Comment by pekeler** [comment]
@CoDEmanX all three PDFs have the same problem.

**Comment by pekeler** [comment]
Another problem is that copying text from the PDF doesn't work either. Seems to be a bunch of weird glyphs instead of normal text.

**Comment by CoDEmanX** [comment]
Well, selection making is always strange in PDFs, but that's normal and can be technically explained - PDFs are printing instructions after all. Text isn't stored in paragraphs yada yada. I can select and copy text just fine however, on Windows and Android. I can't select a headline and surrounding text in any PDF viewer though. Furthermore, Chrome draws rectangles around every single letter, which looks odd, but it works. Adobe Acrobat on Android didn't let me select anything, it might not support this operation.

Since the optimized PDFs didn't work either, I wonder if it's just your PDF viewer software or OS which is broken... Can you confirm that there are in fact PDFs that don't exhibit these problems?

**Comment by pekeler** [comment]
Oh yeah, I'm reading PDFs all the time. Search, select, and copy work fine in other docs.

I just tested on my iPad and it also can't search text in the arango docs.

After some googling, it seems that the calibre's output requires unicode cmaps which are not supported by Apple. And it seems the creator of calibre has no interest in supporting mac users.

**Comment by dothebart** [comment]
@pekeler maybe you want to report the findings in a bug on gitbook? Maybe they have a better lever on calibre?

**Comment by dothebart** [comment]
I've added [a tarball for the generated html documentation](https://docs.arangodb.com/documentation.tar.gz). So can grab & grep through it when working offline.
