### ISSUE TITLE
Consider making Persistent Index case insensitive

### ISSUE THREAD

**Issue by JDelladecimas** [arangodb/arangodb#15920]
## My Environment

* __ArangoDB Version__:        3.8
* __Deployment Mode__:       OASIS
* __Deployment Strategy__:   
* __Configuration__:               
* __Infrastructure__:               Azure
* __Operating System__:        Ubuntu 20.04 | Windows 10 
* __Total RAM in your machine__:        
* __Disks in use__:        
* __Used Package__:           

## Component, Query & Data
Collection that uses Persistent Index to apply unique constraint over 2 Properties

__Affected feature__:

__AQL query (if applicable)__:
N/A

__Dataset__:

__Size of your Dataset on disk__:
N/A

## Steps to reproduce

1. Create a Persistent Index on a Collection
2. Unique: true
3. Add 2 properties ( Name, Category)
4. Create a document with { Name: "Test", Category: "aCategory" }
5. Create another document with { Name: "test", Category: "aCategory" }
6. Second document is created

__Problem__:
If you follow the steps to reproduce, I can create documents that have the same properties, but with different case.

__Expected result__:
We want to enforce uniqueness on 2 properties regardless of case, and it would be preferable to have the database enforce this.
Would you consider adding a boolean option to ignore or not case sensitivity. 
eg
notCaseSensitive: true // true by default as this is the current behaviour

**Comment by dothebart** [comment]
Hi, 

the most easiest way to achieve what you want is to create a copy of the field you want to look up and modify it accordingly. 

The other (more powerfull) option may be to use ArangoSearch Views.
