### ISSUE TITLE
Feature request: AQL arithmetic exponentiation operator

### ISSUE THREAD

**Issue by baslr** [arangodb/arangodb#1593]
I suggest a arithmetic exponentiation operator for AQL.
`**` seems the common operator today.
https://en.wikipedia.org/wiki/Exponentiation#In_programming_languages

Example:
```
RETURN 5 ** 5 // returns 25
```
Would be nice to see this in a future release.

**Comment by CoDEmanX** [comment]
`5 ^5 = 3125` but valid point.

Alternatively, `POW(5, 5)` could be added as [numeric function](https://docs.arangodb.com/Aql/NumericFunctions.html).

What is also missing is rounding to integer towards zero. It's very easy to do in JavaScript: `-0.9 | 0`

input value | round towards zero | round to nearest | floor | ceil
---|---|---|---|---
-0.9 | 0 | -1 | -1 | -0
-0.1 | 0 | -0 | -1 | -0
0.1 | 0 | 0 | 0 | 1
0.9 | 0 | 1 | 0 | 1

Built-in support for integer divisions might be of use for some as well.

**Comment by jsteemann** [comment]
@baslr, @CoDEmanX : providing some mechanism for exponentation and rounding towards zero sounds like good ideas.

**Comment by pluma** [comment]
Keep in mind that the exponentiation operator will be added in a future version of EcmaScript, so it's probably a good idea to maintain compatibility with that syntax-wise (the ES proposal uses `**`).

**Comment by CoDEmanX** [comment]
... and they copied it from Python :P

**Comment by baslr** [comment]
@CoDEmanX, obvious 5 ^ 5 is 3125; my fault.

**Comment by jsteemann** [comment]
Adding a new AQL operator is much more complex than an AQL function, so I added exponentiation as an AQL function `POW()`. 
devel/2.8 do have it from now on and it can be tried there.

**Comment by CoDEmanX** [comment]
Rounding towards zero is actually possible with FLOOR() and CEIL() combined with the ternary operator `? :`:

```js
FOR v IN [-0.9, -0.1, 0.1, 0.9]
    RETURN {
        input: v,
        output: v >= 0 ? FLOOR(v) : CEIL(v)
    }
```
Do we need a dedicated [TRUNC()](http://www.cplusplus.com/reference/cmath/trunc/) then?

**Comment by jsteemann** [comment]
A round-to-zero function would be simple to implement in core ArangoDB, but also simple to implement on user-side, either as a user-defined AQL function in JavaScript or via the ternary operator (preferred) as you mentioned above. 
My preference is therefore to not put this functionality into the core, but allow users to implement it themselves via a simple AQL expression if necessary.

**Comment by dsonet** [comment]
@jsteemann Agree, don't need to add a new function since we already can achieve it in an easy way.

**Comment by jsteemann** [comment]
Ok, so let's close this issue.
