### ISSUE TITLE
Unable to configure  Ingress rules with Arango DB in the kubernetes cluster.

### ISSUE THREAD

**Issue by venkatbatthula** [arangodb/arangodb#15940]
## My Environment

* __ArangoDB Version__:        3.8.6 or 3.9.0
* __Deployment Mode__:       Single server
* __Deployment Strategy__:   Kubernetes
* __Configuration__:               
* __Infrastructure__:               AWS
* __Operating System__:        Ubuntu 20.04
* __Total RAM in your machine__:      32Gb. 
* __Disks in use__:        HDD
* __Used Package__:              

## Component, Query & Data

__Affected feature__:
Foxx

__AQL query (if applicable)__:
```


```
__AQL explain and/or profile (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. deploy the Arango DB application in the Kubernetes cluster
2.  setup the Ingress rule ( apiVersion: extensions/v1beta1
          kind: Ingress
          metadata:
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
              kubernetes.io/ingress.class: nginx
              nginx.ingress.kubernetes.io/enable-global-auth: "false"
              nginx.ingress.kubernetes.io/rewrite-target: /$2
            name: dataops-ingress
            namespace: cndataops
          spec:
            rules:
            - host: xyz.com
              http:
                paths:
                - backend:
                    serviceName: <my-service-name>
                    servicePort: 8529
                  path: /_db(/|$)(.*)$)
3. 

__Problem__:
{"error":true,"errorNum":11,"errorMessage":"not authorized to execute this request","code":401}

__Expected result__:
https://xxxxxxxx.com/_db/_system/_admin/aardvark/index.html#login
Login Page appear on the screen.

**Comment by dothebart** [comment]
Hi, if this issue is still relevant, please re-open it at https://github.com/arangodb/kube-arangodb .
