### ISSUE TITLE
DOCUMENT("") fails with illegal document key

### ISSUE THREAD

**Issue by flusflas** [arangodb/arangodb#15943]
## My Environment

* __ArangoDB Version__:        3.8.1
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:    Kubernetes
* __Configuration__:               3 nodes cluster (3 coordinators, 3 agents and 3 DB-Servers)
* __Infrastructure__:               Azure

## Component, Query & Data

__Affected feature__:
AQL query using web interface, driver...

__AQL query (if applicable)__:
```
RETURN DOCUMENT ("")
```

__AQL explain and/or profile (if applicable)__:
Error executing query: `Query: AQL: illegal document key (while executing)`

__Size of your Dataset on disk__:
Empty database (no collections)

__Replication Factor & Number of Shards (Cluster only)__:
ArangoDB Kubernetes Operator with 3 clusters (3 coordinators, 3 agents and 3 DB-Servers).

## Steps to reproduce

**Edit**: simply running the query `RETURN DOCUMENT("")` in any multi-node ArangoDB.

I cannot reproduce the error locally running a single-instance ArangoDB. Included debug package: [debugDump.zip](https://github.com/arangodb/arangodb/files/8288556/debugDump.zip)

__Problem__:
The function `DOCUMENT("")` with an empty string argument fails at execution with `Query: AQL: illegal document key (while executing)` error.

__Expected result__:
The query should return `null`.

**Comment by Simran-B** [comment]
This is the expected behavior as far as I can tell. An empty string as document key is invalid:

> The key must be at least 1 byte and at most 254 bytes long. Empty keys are disallowed when specified [...]

https://www.arangodb.com/docs/stable/data-modeling-naming-conventions-document-keys.html

The [documentation](https://www.arangodb.com/docs/stable/aql/functions-miscellaneous.html#document) doesn't cover this case explicitly, it only states that a document handle is expected and that `null` is returned if a document can't be found, but not that an invalid key raises an error. That's something that should be improved.

**Comment by flusflas** [comment]
Thanks Simran. That's weird, because using ArangoDB from a Docker container, `DOCUMENT("")` returns `null`. And actually, it makes sense to me. Why trying to recover a document with an empty key would raise an error and using `DOCUMENT("this_key_does_not_exist")` or `DOCUMENT(null)` would return null?

I understand that an empty string is an invalid key, but I think it's useful to return `null` using `DOCUMENT("")` to support fields with empty references, instead of forcing to use `null` or to omit the field. Or maybe an option to handle as a silent error.

Anyway, I'm curious and concerned about why using ArangoDB in Docker behaves differently as using it in cluster mode (same version). It makes my unit tests to pass but the service fails when it is deployed, so I'm not very confident with my tests anymore.

**Comment by flusflas** [comment]
Taking a really quick look at the code for the `DOCUMENT()` function, I still think that the error shouldn't be raised when using and empty string as the document ID. Every call to `getDocumentByIdentifier()` is made with the `ignoreError` parameter set to `true`.

https://github.com/arangodb/arangodb/blob/5260c13b4016d4ad0ce0e5bce45af1cf7db88687/arangod/Aql/Functions.cpp#L6833-L6918

Using an empty string as identifier and `ignoreError = true`, my guess is that `getDocumentByIdentifier()` should return in line 885 without raising any errors:

https://github.com/arangodb/arangodb/blob/5260c13b4016d4ad0ce0e5bce45af1cf7db88687/arangod/Aql/Functions.cpp#L866-L921

As I said, is only a guess (the code is huge and my C++ is quite rusty), but it would confirm the behavior I see using ArangoDB in a Docker container (no cluster mode).

**Comment by Simran-B** [comment]
On second thought, I agree that the behavior is strange. A document key must be at least 1 byte long but violating any of the other rules doesn't appear to raise an error. I would expect a complaint whenever a document handle is invalid, including passing a valid document key but no other arguments (i.e. missing the collection name).

Whether an error should be raised at all is debatable. I do see a benefit in distinguishing the two cases of a document not being found and invalid information supplied to the function. Maybe a warning for the latter case would be better?

The error being raised in cluster but not single server seems like an unintentional inconsistency. This might be the line of code that throws it:

https://github.com/arangodb/arangodb/blob/f39d3bb40a3ef61515d731053d103097a89dbfc3/arangod/Transaction/Methods.cpp#L745-L747

I don't see why it behaves differently depending on the deployment mode, however.

**Comment by flusflas** [comment]
I just tried to reproduce this error using a deployment in ArangoDB Oasis. The version used was 3.8.6, and I used all the possible configurations for the deployment.

First, I used these configurations with replication factor = 3:

| Model   | Nodes memory | Nodes CPU | Nodes disk | Support plan |
|---------|--------------|-----------|--------------|---------------|
| Sharded | 3 × 4 GB     | General   | 3 × 10 GB (DP30) | Basic        |


| Model   | Nodes memory | Nodes CPU | Nodes disk | Support plan |
|---------|--------------|-----------|--------------|---------------|
| OneShard | 3 × 4 GB     | General   | 3 × 10 GB (DP30) | Basic        |

In any database I created (no need to create any collection or data), the query `RETURN DOCUMENT("")` raised an error (`Query: AQL: illegal document key (while executing)`). Executing the same query with any other (non-existing) document ID, it simply returned `null`(e.g. `RETURN DOCUMENT("a")`).

Then I used the Developer (beta) configuration, with replication factor = 1. My guess was that this type of deployment should behave similarly to running ArangoDB in single-instance Docker container.

| Model   | Nodes memory | Nodes CPU | Nodes disk | Support plan |
|---------|--------------|-----------|--------------|---------------|
| Developer (beta) | 3 GB     | General   | 10 GB (DP30) | Basic        |

This time, no error was raised executing `RETURN DOCUMENT("")`.

It seems clear that these behaviors are inconsistent.

**Comment by flusflas** [comment]
Is there any news on this? The issue is tagged as a question, but I think this behavior is a bug.

**Comment by PriyankaGupta1705** [comment]
Wanted to ask the same question. Is this fixed or any update on this?
