### ISSUE TITLE
GraphViewer improvements

### ISSUE THREAD

**Issue by hkernbach** [arangodb/arangodb#1595]
To maintain an overview of the last requests regarding the graph viewer, we'll collect them here: 
https://github.com/arangodb/arangodb/issues/980, https://github.com/arangodb/arangodb/issues/1410, https://github.com/arangodb/arangodb/issues/1544, https://github.com/arangodb/arangodb/issues/1590

Here is a list of whishes for the ArangoDB Graph Viewer created through Github/StackOverflow tickets by users:

AQL:
- [x] Display a graph using AQL
- Run AQL to filter the graph 
  - show nearby (not affected vertices/edges) (optional)

Filter:
- Quickly find a Vertex (also implemented filters), but also add a dedicated search
  - Then explore the graph from there, add visual styling (labels, colors) and append then a filter. 
- [x] Reset of a filter not working as expected
- [x] Filter also sub attributes (phone_number.code)
- [x] Filter shows only one result, not all. 

Grouping: 
- The users should be able to set the grouping parameter of nodes. At the moment there is only a default value, which may confuse the users when grouping is done without an explanation (performance reasons).

Visual:
- [] [x] Custom color schemes and some default settings
- [x] Coloring by collections (edges)
- [x] Coloring by attribute value
- [x] Thickness / Style (Dotted, Shaping) of edges by edge collection
- [x] Labels (vertices / edges)
  - [x] Using name of edge-collection as edge label (e.g. isFollowing)
  - [x] Label source by collection (edge)
  - Node shape-style by collection
  - Node image representation by attribute URL (e.g. URL to avatar) by collection
- Customize appearance:
  - [x] Highlight Nodes / Edges

General: 
- [x] Optimize usability
  - [x] Save settings for a graph representation (label attribute, number of vertices, colors, etc.)
  - [x] Reduce/deactivate animations
  - [x] Optimize edit view
  - [x] Delete edges in graph view
  - [x] Fix expand/collapse of a branch

- [x] Easy way to display a graph
  - [x] Intelligent labels (not 180 degree rotated)

**Comment by CoDEmanX** [comment]
Some ideas:
- WebGL based viewer (with fallback to Canvas) for better performance: hundred thousands of nodes can be shown simultaneously if shaders are used. An existing library like [Pixi.js](http://www.pixijs.com/) could be used, or something self-made similar to [grapher](http://engineering.ayasdi.com/2015/01/09/converting-a-d3-visualization-to-webgl-how-and-why/).
- Graph traversal visualization: select one or multiple start vertices and step through the traversal (color-code visited vertices and edges, maybe also count how the number of visits)
- Faster in-line editing of vertex and edge documents: no distinction between a view and an edit mode at all or more streamlined (click to enter edit mode for instance), maybe use some animation to transition from node to rectangle to document editor.
- high-level view of cluster distribution: indicate what server documents are on

**Comment by dothebart** [comment]
by @disharmonized
It would be very handy to have ability to pin vertexes in graph viewer in Web Interface (they just kind of floating in fluid now).
I am using ArangoDB v.2.8.7.

**Comment by hkernbach** [comment]
Closing this issue now. 3.1 will come with a new Graph Viewer.
