### ISSUE TITLE
Aardvark: Use apropriate prefixes for large byte sizes

### ISSUE THREAD

**Issue by pluma** [arangodb/arangodb#1597]
Via #1596 

> as a suggestion, can you please change all values of `Size` from the figures tab shown in the screenshot above, so that the right unit is calculated for each row, z.B. MB, GB, TB, since our data is often above 1000 MB and it gets harder to spot anomalies like the one in this ticket.

Maybe the exact size in bytes (no prefix) could additionally be shown as a tooltip (HTML title attribute)?

**Comment by CoDEmanX** [comment]
:+1: 
Gibibyte etc. should be used (1024 based), not Gigabyte (1000), although I prefer GB over GiB for Gibigyte.

**Comment by pluma** [comment]
If we use the base 2^10 prefixes we should use the proper abbreviations (i.e. Mi, Gi, etc). Anything else just creates unnecessary confusion.

But as for 2^10 vs 10^3 I have no skin in the game. @fceller do we have any internal conventions for this? We seem to use 2^10 with the 10^3 prefixes on the download page so we might want to make sure whatever we use is used somewhat consistently.

**Comment by baslr** [comment]
I just can remember my PR #1261
I vote for `k as Kilo (10^3), KiB as Kibi (2^10)`
For example OS X uses the correct SI prefixes Windows does not.

**Comment by hkernbach** [comment]
We just took a library to do the web interface calc for us: http://filesizejs.com/

**Comment by mbaesler** [comment]
Hm, does not look correct to me:
```
filesize(1024)
"1 kB"
filesize(1000)
"1000 B"
filesize(10000)
"9.77 kB"
filesize(1024*1024)
"1 MB"
filesize(1024*1024*1024)
"1 GB"
filesize(1000*1000*1000)
"953.67 MB"
filesize(10*1000*1000*1000)
"9.31 GB"
```

**Comment by CoDEmanX** [comment]
Well, it does not use the correct SI prefixes it seems, 1 MB should be 1 MiB etc.
That should be a simple fix to this line:
https://github.com/avoidwork/filesize.js/blob/master/lib/filesize.js#L17

**Comment by pluma** [comment]
Personally I prefer pretty-bytes, although that doesn't support base-2:

https://github.com/sindresorhus/pretty-bytes/tree/v1.0.4
