### ISSUE TITLE
Documentation: custom expander example

### ISSUE THREAD

**Issue by kibarda** [arangodb/arangodb#1601]
(currently on 2.7.2 )
from this example in https://docs.arangodb.com/Traversals/UsingTraversalObjects.html

`var config = {
  ...
  expander: function (config, vertex, path) {
    var connected = [ ];
    var datasource = config.datasource;
    datasource.getInEdges(vertex._id).forEach(function (edge) {
      if (Math.random() >= 0.5) {
        connected.push({ edge: edge, vertex: (edge._from) });
      }
    });
    return connected;
  } 
};`

not sure about this, but I had problem to get this to work: 
- 'getInEdges' probably do not accept  vertex._id  as input but the vertex itself . 
- 'connected' to take vertex and not its id (edge._from) ?

**Comment by dothebart** [comment]
ArangoDB 3.0 RC2 is out (https://www.arangodb.com/download-preview/) with brand new Traversals:

https://docs.arangodb.com/cookbook/AQL/MigratingGraphFunctionsTo3.html
https://docs.arangodb.com/cookbook/AQL/MigratingEdgeFunctionsTo3.html
https://docs.arangodb.com/cookbook/AQL/MigratingMeasurementsTo3.html

**Comment by dothebart** [comment]
Meanwhile all usecases using the old way has been removed; thus closing this.
