### ISSUE TITLE
Replication of index created in background blocks other replicated operations

### ISSUE THREAD

**Issue by matcho** [arangodb/arangodb#16022]
## My Environment

* __ArangoDB Version__:        3.8.3
* __Deployment Mode__:       Leader/Follower ("Master/Slave")
* __Deployment Strategy__:   systemd
* __Infrastructure__:               own
* __Operating System__:        Ubuntu 20.04
* __Total RAM in your machine__:        256GB on both machines
* __Disks in use__:        SSD (leader) / HDD (follower)
* __Used Package__:              Ubuntu .deb

## Component, Query & Data

__Affected feature__:
Replication / index creation

__Dataset__:
Specifically one collection with 500M+ documents

__Size of your Dataset on disk__:
1.5T

## Steps to reproduce

1. Trigger realtime replication between 2 machines, wait for it to successfully batch-copy existing data and get to the realtime part
2. Create an index on some large collection of the leader, ticking "createInBackground" option
3. Add / update docs in any collection on the leader: they are not replicated to the follower until index creation is finished on the follower
4. Wait a few hours in this case, because collection is *very* large; replication fills the gap and goes on as expected

__Problem__:
As the index is explicitly created in background in order not to freeze the database, one could expect that the follower does not freeze either.

While I understand that index creation is probably considered a step / a tick of the replication process, and as such, no further tick is processed until this one completes, it still feels counter-intuitive, and can break a production setup if both machines are needed to be up-to-date at any time, and index creation takes a long time.

__Expected result__:
Continue to replicate writes while the index is being created in background on the follower

Thank you very much for considering this request,
Mathias

**Comment by matcho** [comment]
One option, although less convenient, would be to be able to create the index on the replicate first (in background), then on the leader.

But when doing so, index creation on leader still triggers an index creation on the replicate, even though an identical index already exists. So the problem is still here, and the replicate ends up with 2 identical indexes.

**Comment by dothebart** [comment]
Hi, 
Leader follower replication will not be supported with the reworked replication protocol which is going to replace the current replication.
Hence this is a definite `won't fix` - I will close this.

**Comment by matcho** [comment]
Thanks for your answer. Is there already a roadmap / preview / documentation stub for the new replication protocol, so that we have a glimpse of what it will look like ?

**Comment by dothebart** [comment]
current devel nightly have it, and you can enable it.
I don't know about the documentation.
