### ISSUE TITLE
2.8beta1 array index not working

### ISSUE THREAD

**Issue by roman1720** [arangodb/arangodb#1603]
Hi example data:

db.vIntL3.save({name:"Ethernet 0/0", ip:["1.1.1.1","1.1.1.2","1.1.1.3"]});
db.vIntL3.save({name:"Ethernet 0/1", ip:["2.2.2.1","2.2.2.2","2.2.2.3"]});
db.vIntL3.save({name:"Ethernet 0/2", ip:["3.3.3.1","3.3.3.2","3.3.3.3"]});

db.vIntL2.save({name:"Ethernet 0/0", neiIP:"1.1.1.2"});
db.vIntL2.save({name:"Ethernet 0/2", neiIP:"3.3.3.1"});

Now when I run following query:

for intL2 in vIntL2
  for intL3 in vIntL3
    filter intL2.neiIP in intL3.ip
      return intL2.neiIP

I get expected result:

[
  "1.1.1.2",
  "3.3.3.1"
]

But when I apply array index:

db.vIntL3.ensureIndex({ type: "hash", fields: [ "ip[*]" ] });

then I get no result:

Warnings:

[1563], 'in function 'UNIQUE()': array expected'
[1563], 'in function 'UNIQUE()': array expected'

Result:

[]

Simpler query works with index:

for intL3 in vIntL3
  filter "1.1.1.1" in intL3.ip
    return intL3

**Comment by jsteemann** [comment]
Thanks for the report. It's fixed in 2.8 and devel branches now.
