### ISSUE TITLE
2.8beta1 array index gets collection stuck

### ISSUE THREAD

**Issue by roman1720** [arangodb/arangodb#1606]
Hi, example data:

arangosh [_system]> db.vIntL3.toArray();
[
  {
    "name" : "Ethernet 0/0",
    "ip" : [
      {
        "primary" : 1,
        "ip" : "1.1.1.1"
      },
      {
        "ip" : "1.1.1.2"
      },
      {
        "ip" : "1.1.1.3"
      }
    ],
    "_id" : "vIntL3/461532423951",
    "_rev" : "461532423951",
    "_key" : "461532423951"
  },
  {
    "name" : "Ethernet 0/1",
    "ip" : [
      {
        "primary" : 1,
        "ip" : "2.2.2.1"
      },
      {
        "ip" : "2.2.2.2"
      },
      {
        "ip" : "3.3.3.3"
      }
    ],
    "_id" : "vIntL3/461532620559",
    "_rev" : "461532620559",
    "_key" : "461532620559"
  }
]

Now I try to apply following array index:

db.vIntL3.ensureIndex({ type: "hash", fields: [ "ip[0].ip" ] });
JavaScript exception in file '/usr/share/arangodb/js/client/modules/org/arangodb/arangosh.js' at 104,13: [ArangoError 1220: parser failed: parser failed]
!      throw new ArangoError(requestResult);
!            ^
stacktrace: Error
    at Object.exports.checkRequestResult (/usr/share/arangodb/js/client/modules/org/arangodb/arangosh.js:104:13)
    at ArangoCollection.ensureIndex (/usr/share/arangodb/js/client/modules/org/arangodb/arango-collection.js:756:12)
    at <shell command>:1:11

I don't know if such a index is supported (I have aql where I want to filter based only on first array element), but collection is stuck, I can't print collection, show indexes etc.

arangosh [_system]> db.vIntL3.toArray();

Prompt is stuck now. I have to restart database to get collection to work again.

**Comment by jsteemann** [comment]
Thanks for reporting this. It's fixed in 2.8 and devel now.
