### ISSUE TITLE
2.8beta1 for in EDGE not working

### ISSUE THREAD

**Issue by roman1720** [arangodb/arangodb#1607]
Hi following AQL works in 2.7 and doesn't in 2.8beta1

for intL2 in vIntL2
  for cdp in EDGES(eCdp, intL2, "inbound")
    return cdp

Query: array expected as operand to FOR loop (while executing)

**Comment by jsteemann** [comment]
Confirmed there is an issue in case the second parameter to `EDGES` is an array.

**Comment by mchacki** [comment]
Thank you very much for Spotting it.
It is now fixed in devel and 2.8.
