### ISSUE TITLE
Could I download 32bit ver. installer for Windows?

### ISSUE THREAD

**Issue by ovrmrw** [arangodb/arangodb#1609]
I could found just "ArangoDB-2.7.2-win64.exe" on the download page.
Could I download 32bit version?

**Comment by CoDEmanX** [comment]
There is no official 32bit build, because the 32bit support was dropped. It still compiles though:
https://groups.google.com/forum/#!topic/arangodb/skOQIMavLbk

**Comment by ovrmrw** [comment]
@CoDEmanX I see, thanks :)
