### ISSUE TITLE
A collection rename is not propagated in Graph definition

### ISSUE THREAD

**Issue by kibarda** [arangodb/arangodb#1610]
(on v2.7.2)
When one renames a collection, the name is changed in  _to, _from in edges collections but not in   Graph definition (in the Web Interface.)
Moreover changing the Graph definition after a collection rename is not possible.

**Comment by jsteemann** [comment]
Fixed in 2.8 and devel. When a collection is renamed now, then the collection name will be renamed in the `_graphs` collection as devel.
