### ISSUE TITLE
migrating from linux to windows

### ISSUE THREAD

**Issue by geekygnr** [arangodb/arangodb#1614]
I am developing an application on a Linux VM with arangodb but I need to migrate the entire database over to a windows machine.

I have done a dump of the data in the linux vm. I looked over the files and have seen the data for the database inside them.

The only problem is when I try to run a restore on the windows machine it will create the database and create the collections but it won't import the data. As far as I can tell there are no errors it just isn't reading the data files.

Any thoughts?

**Comment by jsteemann** [comment]
A few question:
* do the dump files actually contain data in the `filename_hash.data.json` files or are these empty? And does the JSON in the data files contain the expected data?
* are you using the same ArangoDB version for restore that you used when creating the dump?

**Comment by geekygnr** [comment]
The files are not empty but they appear to be missing information. Some of my documents had objects in them and they are not appearing in the dump but there is some base data.

Both windows and ubuntu are running 2.7.2

**Comment by geekygnr** [comment]
I just did a test import of the data in ubuntu and it works fine. It included all information including the objects inside the documents that I did not see in the .data.json file.

**Comment by jsteemann** [comment]
When the documents and subobjects are imported in Ubuntu, then the .data.json files seem to be complete and correct.
I just tried dumping and restoring and did not encounter any problems. Is there anything special about the collection, the data etc.? Is it possible to share the files (.data.json and .structure.json) for one of the collections that didn't work on restore? That may help reproducing the problem.

**Comment by geekygnr** [comment]
I found the bug.

The problem is EOL encodings. I ran `unix2dos *` in the directory arangodump created and then used those files to import in windows and everything worked.

This project is all proprietary so I can't share the data. If you are still having problems tracking down the bug let me know and I will see if I can create some sample data in my spare time.

**Comment by CoDEmanX** [comment]
The line endings are Unix style (0x0A / LF) if I create a dump on Windows (2.8 beta), and it re-imports fine. If I manually change it to Windows line endings (0x0D0A / CR LF), it still works. If I change it to Mac line endings however (0x0D / CR), an error is raised:

> ArangoError 600: invalid JSON object

What's funny: if you add a line at the end with two spaces and a line break, the same error occurs. If it's only one space and a line break, then it works as long as Unix line breaks are used. With Windows line breaks, it also raises that error if it's only a single space and a line break.

I can't get it to fail silently with my very simple test data however. @geekygnr: can you create some test data and check if that also fails to import on Windows?

**Comment by geekygnr** [comment]
@CoDEmanX I will see what I can do, it will take me a couple days at least to get to it.

**Comment by jsteemann** [comment]
arangodump should always write data using Unix line-breaks (i.e. `\n`), regardless of the platform. There shouldn't be Windows line-breaks in the files it generates.

arangorestore should split lines in its input files using Unix line-breaks again. This is hard-coded and not platform-dependent. It may fail when there a Windows line-breaks contained in the dump, I have to try it. 

I wonder how Windows line-breaks made it into the dump files. Is it possible the dump files were manually edited so a Windows command/editor put `\r\n` line breaks into them?

**Comment by CoDEmanX** [comment]
Hm, but why can I import Windows line breaks just fine, no matter how they got into the dump files? What does is depend on to fail?

**Comment by dothebart** [comment]
whitespace at the end of the json is ignored - so the additional \r isn't evaluated. 
If a dataset occurs that reproduces this failure feel free to reopen this bug; Please search it for stray linebreaks, or send the dump to verify.
