### ISSUE TITLE
Compound Unique Index

### ISSUE THREAD

**Issue by alxxyz** [arangodb/arangodb#16151]
Add support for compound index as in MongoDB https://www.mongodb.com/docs/manual/core/index-compound/

Basically it is an index on multiple fields, for example we want to have unique a combination of some fields.

**Comment by mpoeter** [comment]
It might not be immediately clear since the expression "compound" is not used in the ArangoDB documentation, but you can already create indexes covering multiple fields in ArangoDB. See https://www.arangodb.com/docs/3.9/indexing-index-basics.html#indexing-attributes-and-sub-attributes

**Comment by alxxyz** [comment]
It doesn't work in this case
```
@Edge(value = "roles")
public class Role{
    @Id
    private String id;

    @From
    private Actor actor;

    @To
    private Movie movie;
}

@Document
public class Movie movie{
    @Id
    private String id;

    private String name;
}

@Document
public class Actor actor{
    @Id
    private String id;
     
    private String name;
}
```

```
db.roles.ensureIndex({ type: "persistent", fields: [ "actor", "movie" ], unique: true })
```

When I try to save second movie for the same user I get the error
```
Response: 409, Error: 1210 - AQL: unique constraint violated - in index idx_1730726459385839616 of type persistent over 'actor, movie';
```

https://github.com/arangodb/spring-data/issues/235

**Comment by alxxyz** [comment]
As I understand from the article I need to use `_from` and `_to`

```
db.roles.ensureIndex({ type: "persistent", fields: [ "_from", "_to" ], unique: true })
```

**Comment by mpoeter** [comment]
I am not familiar with this Java library and its annotations, but I would assume that `@From` and `@To` map to the edge internal `_from`, `_to` attributes. So yes, you should create an index with the fields `[ "_from", "_to" ]`.

**Comment by Simran-B** [comment]
Also see https://www.arangodb.com/docs/stable/indexing-index-basics.html#ensuring-uniqueness-of-relations-in-edge-collections
