### ISSUE TITLE
[Research question] Index implementation details 

### ISSUE THREAD

**Issue by 3bst0r** [arangodb/arangodb#16176]
Hello, 

I am interested in the implementation details of ArangoDB indexes for a thesis I am writing. I have some questions and I hope somebody can answer them. I am only interested in the current stable version that uses RocksDB as its storage engine.

- With the RocksDB storage engine, are there really any actual hash indexes involved anymore or is the only trace left the name "hash", that was left there for compatibility reasons? I see conflicting statements in the docs, I find "The primary index can be used for range queries and sorting as persistent indexes are sorted." (https://www.arangodb.com/docs/stable/indexing-index-basics.html) and then "For each collection there is always the primary index which is a hash index for the document key (_key attribute)."(https://www.arangodb.com/docs/stable/http/indexes.html). Further, this blog post: https://www.arangodb.com/2018/02/indexes-types-arangodb-part-1/ states that the "hash" type is only an alias now.

- What is the data structure used for the "persistent" index type? Is it an LSM-tree provided by RocksDB or are there any other datastructures involved?

Thank you for your time.

**Comment by dothebart** [comment]
Hi, 
Hash / skiplist / persistent indices are a remaint from the mmfiles storage engine which has been decommissioned a while back. 
Hence these are mere leftovers easing users their DDL-Operations. 

https://github.com/arangodb/arangodb/blob/devel/arangod/RocksDBEngine/RocksDBVPackIndex.cpp
is the base implementation for these indices.

**Comment by 3bst0r** [comment]
Hi,

Thanks for your quick response and answer. How would you characterize the RocksDBVPackIndex in terms of datastructure, i.e. is it a B-tree, a LSM-tree or something else?

**Comment by dothebart** [comment]
All index values are internally stored in RocksDB. RocksDB uses an LSM tree as its underlying storage model.

**Comment by 3bst0r** [comment]
Sorry, I have one follow-up question: what is the cardinality of the relationship between ArangoDB indexes and RocksDB databases? I.e., is there one RocksDB database (i.e., one LSM tree) per ArangoDB database that holds all data and indexes or is there one RocksDB database per ArangoDB collection or is there one RocksDB index per ArangoDB index, etc.

**Comment by dothebart** [comment]
An arangodb instance maps to one rocksdb database. 
Different rocksdb column families are used to separate different types of entries, like documents, index entries, ...
