### ISSUE TITLE
Cannot login on aardvark from Chrome

### ISSUE THREAD

**Issue by razvanphp** [arangodb/arangodb#1619]
This is really strange, it happens only for 2 colleagues of ours, not for me, but at least this is what he gets in the console:
```
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
```
Version 2.7.2

**Comment by hkernbach** [comment]
Hm. Cannot reproduce on my machine with ArangoDB 2.7.2 and current chrome browser (Version 47.0.2526.106 (64-bit)). Are there any special characteristic in their systems? The synchronous XMLHttpRequest warning has nothing to do with the problem described above.

**Comment by dothebart** [comment]
@razvanphp can you provide a sniff of such a non-ssl'ed session? Can you provide a little more information which browers are used in this situation? (version, plugins, os, etc?)

**Comment by dothebart** [comment]
Can't reproduce, Please reopen if more information can be provided.
