### ISSUE TITLE
2.8beta2 deb

### ISSUE THREAD

**Issue by roman1720** [arangodb/arangodb#1620]
Hi could you please release 2.8beta2 deb for Debian 8?

And can you reopen https://github.com/arangodb/arangodb/issues/1583 I added comment there, it's not fixed yet.

Thanks

Roman

**Comment by fceller** [comment]
@roman1720 Beta2 is now available for download: https://www.arangodb.com/download-preview/

**Comment by roman1720** [comment]
Thank you
