### ISSUE TITLE
Feature request: Slow Query Log

### ISSUE THREAD

**Issue by roman1720** [arangodb/arangodb#1621]
Hi it would be nice to have similar feature as Slow Query Log in Mysql.

**Comment by CoDEmanX** [comment]
That was actually added in 2.4.5:
https://www.arangodb.com/2015/03/version-2-4-5-with-slow-query-tracking/

**Comment by roman1720** [comment]
Aha, thanks, sorry I didn't find it. But I can't figure it out. I run this example command from documentation:

FOR sleepLoooong IN 1..5 LET sleepLoooonger = SLEEP(1000) RETURN sleepLoooong

I can see it in GUI Active queries, it runs for very long time. But nothing shows in Slow tab. Also queries.slow(); shows nothing. queries.properties(); shows that it's enabled.

Also I can't find if it's possible to log slow queries to file.

**Comment by jsteemann** [comment]
The query will be logged in the slow query log when it's finished. Before that, its total execution time is still unknown.

**Comment by roman1720** [comment]
Got it thanks.
