### ISSUE TITLE
timeout in cluster operation 

### ISSUE THREAD

**Issue by ohsp123-arango** [arangodb/arangodb#16229]
## My Environment

* __ArangoDB Version__:        Enterprise 3.7.2 
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   Manual Start
* __Configuration__:               three clustered hosts
* __Infrastructure__:               own 
* __Operating System__:        REHL 8.1
* __Total RAM in your machine__:         32GB each hosts
* __Disks in use__:         HDD 
* __Used Package__:               RedHat .rpm

## Component, Query & Data

__Affected feature__:
 arangodb starter

__AQL query (if applicable)__:
```


```
__AQL explain and/or profile (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:
 5TB

__Replication Factor & Number of Shards (Cluster only)__:
 1

## Steps to reproduce

1. start ArangoDB cluster 
2. try to access Database through the Prophet Application
3. it returns 'POST operation to ArangoDB server 10.172.30.xxx failed with: Internal Server Error, timeout in cluster operation. Waiting 100ms before ... 

__Problem__: We see the error message ''POST operation to ArangoDB server 10.172.30.xxx failed with: Internal Server Error, timeout in cluster operation. Waiting 100ms before ...' and the strange thing is that this problem gone away on its own one or two days later. - I mean it's working again without any specific actions.

__Expected result__: ArangoDB should be accessible without any timeout error.

**Comment by dothebart** [comment]
Hi, 
Please note that ArangoDB 3.7.16 is available for Download. Please upgrade and try this.
Please report enterprise issues via Jira.

**Comment by ohsp123-arango** [comment]
Thank you
