### ISSUE TITLE
Foxx Generate App Location

### ISSUE THREAD

**Issue by gphein** [arangodb/arangodb#1625]
Issue originally tagged and posted on stackoverflow:
http://stackoverflow.com/questions/34348898/how-to-change-the-arangodb-foxx-app-generate-location

In short, --javascript.app-path does not appear to be recognized.

**Comment by dothebart** [comment]
hm, wfm?

`arangod /tmp/1112  --javascript.app-path /tmp/testjs`

<install the itzpapalotl service through the webinterface>

    find /tmp/testjs
    /tmp/testjs
    /tmp/testjs/_db
    /tmp/testjs/_db/testdb
    /tmp/testjs/_db/_system
    /tmp/testjs/_db/_system/testfoxx
    /tmp/testjs/_db/_system/testfoxx/APP
    /tmp/testjs/_db/_system/testfoxx/APP/itzpapalotl.js
    /tmp/testjs/_db/_system/testfoxx/APP/LICENSE
    /tmp/testjs/_db/_system/testfoxx/APP/manifest.json
    /tmp/testjs/_db/_system/testfoxx/APP/README.md
    /tmp/testjs/_db/mydb


`
    find /tmp/1112/
    /tmp/1112/
    /tmp/1112/LOCK
    /tmp/1112/SERVER
    /tmp/1112/databases
    /tmp/1112/databases/database-88858
    /tmp/1112/databases/database-88858/collection-13840230
    ....
`

`find js |grep -i testfox` -> empty result

**Comment by pluma** [comment]
@gphein Are you passing the option to arangod (the server) or foxx-manager (the CLI)?

The option is only valid for the server and not part of the CLI.

**Comment by dothebart** [comment]
@gphein did this work for you? if yes, can you mark the (modified) answer of @pluma on stackoverflow as accepted?

**Comment by gphein** [comment]
Thanks for the information. I was passing the argument to the foxx-manager. I thought the the option was per foxx app installation, but just being able to redirect the server is fine.
