### ISSUE TITLE
AQL date handling is always UTC-based

### ISSUE THREAD

**Issue by jsteemann** [arangodb/arangodb#1630]
All AQL date functions work on UTC dates. All incoming date values will be converted into timezone-less UTC values, and all further date operations are run on these values.

This may be counter-intuitive to users. For example, `DATE_HOUR(date)` is supposed to return the hour part of the given date. If there's a timezone offset, e.g. `RETURN DATE_HOUR('2015-12-18T23:00:00-06:00')`, `DATE_HOUR()` will return `5` (for the value's UTC equivalent `2015-12-19T05:00:00Z`) and not `23` as is probably expected.

There is no way to turn this on or off, so working with timezone-adjusted dates may be troublesome.

I have created [a patch](https://gist.github.com/jsteemann/bb93dcf01cdfaba38265) that would adjust this behavior by taking the specified timezone of a date value into account, so the date functions behave like working on non-UTC date values.

With the patch, `RETURN DATE_HOUR('2015-12-18T23:00:00-06:00')` will return `23` with the patch and not `5` as before.
The problem with the patch is that it is not backwards-compatible to the current (<= 2.8) behavior.
If the UTC-based behavior is required, one would need to explicitly write `RETURN DATE_HOUR(DATE_ISO8601('2015-12-18T23:00:00-06:00'))`, which will first translate the date into `2015-12-19T05:00:00Z` and then extract the hour part (`5`) from it. This is more explicit and allows for more control, but it's more typing for users favoring the UTC-behavior and also not downwards-compatible.

Any suggestions?

**Comment by pekeler** [comment]
> All AQL date functions work on UTC dates.

Good!

> Any suggestions?

Keep it this way. Running servers in anything but UTC is crazy and I wouldn't spend any time accommodating that. Maybe just add a reminder somewhere on Aardvark's AQL editor "all times in UTC".

http://yellerapp.com/posts/2015-01-12-the-worst-server-setup-you-can-make.html

**Comment by jsteemann** [comment]
@pekeler: thanks for the suggestion. 
To be clear, I was not thinking about changing the server's locale nor server configuration nor anything else outside some dedicated AQL date functions. And only for those date values that contain a timezone offset that is unequal to `Z` or `0:00`.
 
All date values that don't contain a timezone offset or that have an explicit `Z` or `+0:00` timezone value would not be affected by this.
An alternative would be to keep the existing behavior for the AQL date functions and expose the non-UTC date behavior via an extra parameter, which could also default to false (e.g. `function DATE_HOUR(value, honorTimezone = false)`) or via extra functions, e.g. `DATE_HOUR_LOCAL(hour)` (non-UTC) and `DATE_HOUR(hour)` (UTC-based).

**Comment by jsteemann** [comment]
@pekeler: good read by the way. I have been haunted by timezone bugs for a few years myself while I was maintaining an app that **was** configured to use UTC in the database and everywhere. But then came end users that demanded display and entering local time values. That already caused lots of issues, so I am not taking this lightly.

**Comment by dothebart** [comment]
filed via http://stackoverflow.com/questions/34076851/arangodb-is-date-aql-function

**Comment by CoDEmanX** [comment]
`DATE_FORMAT()` could be extended to offer a third parameter to use local time. It would essentially skip the internal conversion to a Date object and instead use `IS_DATESTRING()` to verify it's syntactically a date, then do the substringing it already does. One would need to specify a format string of course, which may be inconvenient if one wants e.g. hours, minutes and seconds as individual components. Moreover, what if the input date is numeric and what if the format string contains the placeholders week, quarter or leapyear (they can't be taken from an ISO date string)?

`DATE_*_LOCAL()` would be much cleaner, but also add quite a lot more date functions with a narrow scope. We might wanna reconsider the date handling and perhaps add moment.js after all (it comes with features like timezone -> timezone conversion), or move it entirely to C++ and use e.g. boost for all the date and time computations (faster, but also more work to implement and perhaps not as feature rich as moment.js).

**Comment by pluma** [comment]
Just FYI: if you are using Foxx/JS the [timezone](https://www.npmjs.com/package/timezone) package can be used to do sane timezone conversions in JS.

Personally I think it's a bad idea to have AQL handle timezone conversion as you generally want your data to be normalized/sanitized before it ends up in the database but maybe that's just me.

**Comment by dothebart** [comment]
Closing this as solved; the Implementation by @coronabytes will be in ArangoDB 3.8 
Further discussions about support for timezones in other functions will be led in https://github.com/arangodb/arangodb/issues/12680
