### ISSUE TITLE
How does string comparison work?

### ISSUE THREAD

**Issue by ysmu** [arangodb/arangodb#16319]
## My Environment

ArangoDB Version: 3.9.1
Deployment Mode: Single Server
Deployment Strategy: Manual Start in Docker
Configuration: Default
Infrastructure: own
Operating System: Windows
Total RAM in your machine: 32Gb
Disks in use: HDD
Used Package: official Docker library

## Component, Query & Data

AQL
```
RETURN "?" > "0"
```
Result
```
[
  false
]
```

__Question__:

I'm not sure if this is a bug or an expected behavior. Does AQL implement its own character order for comparison? I was expecting `"?" > "0"` to return `true` since `?` has a higher ASCII value than `0`.

For context I store incomplete dates in the `YYYY-MM-DD` format, where if a part is not known it is filled with `?`. So I can have a date like `????-05-01`. I was hoping that this date can after `2022-01-01` after `SORT ASC`.

**Comment by Simran-B** [comment]
Strings are sorted and compared using ICU. The order depends on the selected server language (`--icu-language` or `--default-language` respectively).

https://www.arangodb.com/docs/stable/programs-arangod-general.html#default-language

**Comment by ysmu** [comment]
Do you know if there is a way to tell ICU to order the characters by their ASCII values?

**Comment by ysmu** [comment]
I played around on https://icu4c-demos.unicode.org/icu-bin/collation.html and I don't see a way to do this. It looks like I'll have to find a workaround from my end. Thank you for your response!
