### ISSUE TITLE
Is there any way to partial update inner arrays

### ISSUE THREAD

**Issue by codem4ster** [arangodb/arangodb#1633]
This is the case:
for p in auth_permissions
update p with {roles[2]: {name:"admin"}} in auth_permissions
return NEW

I want to update the name of the 3rd row of roles to "admin" in auth_permissions, is there any way to do this in arangodb?

**Comment by pluma** [comment]
The easiest way to do this is probably by using the [AQL functions `UNION` and `SLICE`](https://docs.arangodb.com/Aql/ArrayFunctions.html):

```
FOR p IN auth_permissions
UPDATE p WITH {
  roles: UNION(
    SLICE(p.roles, 0, 2),
    [{name: 'admin'}],
    SLICE(p.roles, 3)
  )
} IN auth_permissions
RETURN NEW
```

If you need to keep existing properties of the object, you could also use [`MERGE`](https://docs.arangodb.com/Aql/DocumentFunctions.html) in the second argument to `UNION` above like so:

```
[MERGE(p.roles[2], {name: 'admin'})]
```

**Comment by kibarda** [comment]
In quite a similar situation, I've used the following query: 

where:
- the array attribute ('subitems') is created if non existent
- the new subitem values are merged with existing ones if any. 
- the subitem may be created or updated in different positions in the array: 0 -> Length(array)+1

FOR item IN myColl
FILTER item._key == "someKey" 
LET newItem = {"subid":"15d05ce5a7f6","name":"subitem1"}
LET itemPos = 1
LET updatedArr = HAS(item, "subitems")   
?
(
   LET arrLength = LENGTH(item.subitems)
   LET updItem = ( itemPos < arrLength) ? MERGE(item["subitems"][itemPos], newItem) : newItem
   LET updatedArr1 = (itemPos>0) ? UNION(SLICE(item["subitems"], 0, itemPos),[updItem]) : [updItem]
   LET  updatedArr2 = (itemPos+1 < arrLength) ? UNION(updatedArr1, SLICE(item["subitems"], itemPos+1)) : updatedArr1
   RETURN updatedArr2
) 
:  
 [[newItem]] 
UPDATE item WITH {"subitems": updatedArr[0]} IN myColl
RETURN NEW

**Comment by narenderv7** [comment]
I've also had similar problem. I have a document like the following
```
{
 _key:1234,
  list: {1:[], 2: [], 3: [] }
}
```

I want to update some parts `list.1 or list.2`, How can I do this? I did try like this query `UPDATE '1234' with {list.2: ['test 1', 'test 2']}` but it's not working. `list[1] or list["1"] is also not working`

**Comment by mpoeter** [comment]
@narenderv7 in you example `list` is an object, so you have to use something like this:
`UPDATE '1234' WITH {list: {2: ['test 1', 'test 2']}} IN <collection>`

**Comment by narenderv7** [comment]
@mpoeter Thanks for you replay. It worked.
