### ISSUE TITLE
there are some error  when i use LIKE in AQL

### ISSUE THREAD

**Issue by realdog** [arangodb/arangodb#1634]
When i use AQL for search some data, i Wrote this code in my Foxx application:
```
    Repository.prototype.search = Foxx.createQuery({
    query: " FOR doc IN docs FILTER LIKE(doc.content_for_search, '%@somekey%', true) limit @offset, @count RETURN doc",
    params: ['somekey', 'offset', 'count'],
    transform: function(results) {
      return results;
    }
  }); 
```

But ,when i test the code,there some error ..............
```
[888] ERROR [ArangoError 1552: bind parameter 'somekey' was not declared in the query (while parsing)]
```

What should i do?

**Comment by realdog** [comment]
I change the code .....
```
    Repository.prototype.search = Foxx.createQuery({
    query: " FOR doc IN docs FILTER LIKE(doc.content_for_search,  @somekey, true) limit @offset, @count RETURN doc",
    params: ['somekey', 'offset', 'count'],
    transform: function(results) {
      return results;
    }
  }); 
```
And past the string ('%some word'') to the param (@somekey) ....the code  worked.....

**Comment by jsteemann** [comment]
Bind parameters should not be used inside AQL strings. 
For example, `'%@somekey%'` will not work or at least not do what you probably expect. It would be replaced with `'%"whatever-value-there-is-for-the-somekey-parameter"%'` (note the inner quotes).
Using only bind parameters will ensure that there will be no injection and no changing of the meaning of queries, but if they are mixed with regular strings (as in `"%@somekey%"`) you're defeating their purpose again.

If you want to use a bind parameter as a function call parameter, use it like you did in the second example (`FILTER LIKE(doc.content_for_search,  @somekey, true)`) and assemble the value for `somekey` client-side by pre- and appending the `%` characters there.

**Comment by realdog** [comment]
Thank you very much . @jsteemann

**Comment by dothebart** [comment]
added hint to https://docs.arangodb.com/devel/Aql/Basics.html#bind_parameters
