### ISSUE TITLE
AQL doesn't work by using update

### ISSUE THREAD

**Issue by realdog** [arangodb/arangodb#1636]
This AQL doesn't work, i don't know what's wrong with the code
```
 for message in messages update message with {content_for_search: message.title  + message.content } in messages
```

**Comment by jsteemann** [comment]
The error message would be helpful. Without it, I can only guess what's going wrong.
When I run this query, it parses well with 2.8, so no parse error. However, the expression `message.title + message.content` looks suspicious: the `+` in AQL is an arithmetic operator. `title` and `content` sound like if they contain strings. If you're after string concatenation, you may rather use the `CONCAT()` function like this:

`{ content_for_search: CONCAT(message.title, message.content) }`

**Comment by dothebart** [comment]
no feedback.
