### ISSUE TITLE
Create user using AQL?

### ISSUE THREAD

**Issue by OZoneGuy** [arangodb/arangodb#16362]
I know you can manage users using the HTTP interface, but is there a way to manage users using AQL? I want it to be part of the migration script, which mainly uses AQL to apply. I couldn't find anything in the documentation.

**Comment by dothebart** [comment]
Hi, 
Its not advised to bypass the API, but its possible. 
If you know what you're doing and have privileged access using JWT you can access the `_users` collection in the `_system` database.

**Comment by OZoneGuy** [comment]
That's inconvenient... I am trying to create the user as part of the DB migration... Any good way of automatically creating the user and giving it access to the database?

**Comment by Simran-B** [comment]
You can use the [JavaScript API](https://www.arangodb.com/docs/devel/administration-managing-users-in-arangosh.html) via arangosh or with a Foxx service, the HTTP API, or any driver that wraps the [user management API](https://www.arangodb.com/docs/devel/http/user-management.html)
