### ISSUE TITLE
Routes fail with code 3100 when using module document controllers with partially overlapping paths

### ISSUE THREAD

**Issue by gphein** [arangodb/arangodb#1638]
Two routes, /root/A and /root/A/B, use controllers defined in module documents with paths /A and /A/B, respectively. The configuration is structured similar to the below. From the arango shell I can issue this command successfully:  `arango.GET('/_db/mydb/A')` but I receive a **3100 error** when issuing command `arango.GET('/_db/mydb/A/B')`.

If I change module path /A/B to /C (and update the related controller reference) and nothing else then the call to `arango.GET('/_db/mydb/A/B')` runs successfully. After some experimentation, I believe there may be an issue with resolution logic for content stored in the _modules collection.

db._routing.toArray()
`{ url:  {   match: /A }, action: {  controller: A } },`
`{ url:  {   match: /A/B }, action: {  controller: A/B } }`

db._modules.toArray()
`{ path: /A,  content: "..." },`
`{ path: /A/B, content: "..." }`

**Comment by dothebart** [comment]
You have to specify the `_routing.action.controller` as documented in:
https://docs.arangodb.com/ArangoActions/Modifying.html#writing_dynamic_action_handlers
to match whach you specified in `_modules.path` (note that there is a leading '/' here)

Routing: 
`path: "/db:/A/B"`

Modules:
`controller: "db://A/B`

**Comment by gphein** [comment]
Thanks for your response. 

I recall that example, and maybe I just missed it, but the documentation doesn't discuss the role of the "db:" prefix so I assumed it was part of the authors semantics. Is there documentation available discussing the effect of the prefix and when it is truly required? I dont think it's in the section on require() lookup logic.

https://docs.arangodb.com/ModuleJavaScript/index.html#require

And just to be a bit more of a pain, shouldn't the "Routing" and "Modules" label in the above response be switched?

**Comment by dothebart** [comment]
a) Yes, the database lookup of modules isn't documented very well. I will add that. In general we urge users to rather use foxx services, since they handle lots of stuff for you automatically - like collection names, moun paths etc.

b) Yes, you're right, swapped ;-)

**Comment by dothebart** [comment]
To make it more clear, please don't build new applications using this; I will add a remark that this is deprecated; therefore I will not improve the module documentation how to use it.

**Comment by gphein** [comment]
Sorry, what is deprecated? Assuming your comment meant manually creating routes is not advised the documentation makes clear that foxx is the intended way to develop a service on top of arango so that's fine. But, I'm not sure what is the connection to the documentation?

In the use case I posted above I was using routes outside foxx, but using modules to recycle business logic is really convenient so if the "db" prefix is needed to load correctly I guess I don't really know why that shouldn't be documented.

**Comment by dothebart** [comment]
- Routing is there to dispatch requests. this for shure will remain as it is.
 - Foxx services are deployed to the [javascript.app-path](https://docs.arangodb.com/Foxx/Develop/Folder.html) directly in your filesystem, where you can also add your custom code and modules.
 - The db:// prefix is here to load javascript modules from the `_modules` collection. This is whats going to be deprecated.
Sorry for being unprecise.

**Comment by gphein** [comment]
Great. Thanks for the information and for your help.
