### ISSUE TITLE
FYI: A better coroutine lib and IO framework to replace boost::asio

### ISSUE THREAD

**Issue by beef9999** [arangodb/arangodb#16397]
https://github.com/alibaba/PhotonLibOS

**Comment by dothebart** [comment]
Hi, 
is there any http/2 integration existing? we're currently using https://nghttp2.org/documentation/nghttp.1.html

**Comment by beef9999** [comment]
It doesn't support HTTP 2.0 at this moment.

But as far as I know, the most significant change of 2.0 is that it can send/receive HTTP frames out-of-order. Suppose you have a coroutine lib, your thread won't be blocked any more, so the out-of-order thing becomes not vital any more, from the performance perspective.

**Comment by dothebart** [comment]
as noted, nghttp2 is a lib that we use on top of boost::asio, could it be converted for PhotonLib? If yes, do you have plans to do so?

**Comment by beef9999** [comment]
What I can do now is just create a 'FYI' issue at their repo as well... Hopefully they are willing to do the integration.

**Comment by dothebart** [comment]
Thanks for letting us know! I've sugested it to our product management board, maybe we will give it a testdrive after the 3.10 release cycle. 
btw, its LICENSE file reads: `Copyright [yyyy] [name of copyright owner]` maybe they should fix that ;-)

**Comment by beef9999** [comment]
I thought the `Copyright [yyyy] [name of copyright owner]` part belongs to the APPENDIX of that LICENSE file ...
