### ISSUE TITLE
Arangosh not connecting to end point tcp:127.0.0.1:8529

### ISSUE THREAD

**Issue by bkramesh64** [arangodb/arangodb#16398]
## My Environment

* __ArangoDB Version__:        
* __Deployment Mode__:       
* __Deployment Strategy__:   
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:        
* __Total RAM in your machine__:        
* __Disks in use__:        
* __Used Package__:              

## Component, Query & Data

__Affected feature__:

__AQL query (if applicable)__:
```


```
__AQL explain and/or profile (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. 
2. 
3. 

__Problem__:
I have setup arangodb CLI for macosx and it shows a fatal error unable to initialize rockDB engine IO error.  However the web browser comes on and with root and empty password defaults to _system db.

Need your help to resolve arangosh not connecting to end point tcp:[127.0.0.1:8529](http://127.0.0.1:8529/)  database:'_system',username :'root'.

I am trying to use arangoimport.  This is on my mac os bigsur ver 11.4 running on macbook pro.

__Expected result__:
resolve rockdb engine io error.  arangosh gets connected to endpoint 127.0.0.1:8529

**Comment by dothebart** [comment]
just add `--server.password ''` to the commandline arguments?
whats the complete error message of rocksdb?

**Comment by bkramesh64** [comment]
Hi
I have a strange issue when I  execute arangodb cli it brings up the webserver without asking for login. it directly goes into
the _system database and I see all the collections, databases..  When I try to change _system db , the login shows databases as 1,2,3.. and not sure from where it came.  I donot see _system in the login.  not sure of this behavior.. Appreciate your inputs

**Comment by bkramesh64** [comment]
Sorry I wanted to know how we could get arangoimport to connect to oasis end point using CLI. By default it connects to 127.0.0.1:8529..

**Comment by bkramesh64** [comment]
Sorry, it was my mistake . I was changing the root user password and had not saved it. It works very well.

**Comment by dothebart** [comment]
Ok, great. 

you've probably launched arangod with [--server.authentication false](https://www.arangodb.com/docs/stable/programs-arangod-options.html#server) on your local attempt - this will disable authentification. 

Regarding Oasis, please use its associated isuse tracker if future problems occur. 

We can probably close this issue as solved now?

**Comment by bkramesh64** [comment]
Thanks Wilfried for this support. It worked. can you help provide  input on
how to import csv .

Regards
Ramesh
