### ISSUE TITLE
Documentation: uncertainty around graph typology names

### ISSUE THREAD

**Issue by kibarda** [arangodb/arangodb#1644]
in the documentation there seems to be some uncertainty around the names of the types of graph.
One can find: general graph, managed graph, named graph, loosely-structured graph, unmanaged graph, ...

For the documentation consistency it would be better to stick to one name for each type.

**Comment by dothebart** [comment]
`general graph` is the name of the javascript module. `managed` and `named` graphs are synonymous - we should choose one. `loosely-structured` and `unmanaged` graphs are also synonymous; we should unify that too. 
In general the future points to the AQL-graph traversals that will be introduced with 2.8, `general graph` will remain for management purposes.

**Comment by kibarda** [comment]
For *managed/named, loosely/unmanaged* :  I can change the documentation  when a decision is made, just tell me.  ( I would choose managed/unmanaged; I think that naming conveys more meaning)    

For *general graph* as the JS module: I've got the feeling there is either too much or not enough information. As a user, do I really need to know about the name of this module ? ( If yes: does it mean I can extend it, or modify it in some way thanks to some stable code/api ? are there other JS modules I should know about ? etc.. ) 
The devel version you mentioned seems to points to another meaning for *general graph*, hence my confusion...  

Also: the graph terminology should be in the glossary. 

Cheers,

**Comment by dothebart** [comment]
Yes, you're absolutely right. I'll start add some more info to the glossary; This should also solve @geekygnr s understanding troubles in #1529

**Comment by dothebart** [comment]
ok, took a while since it got interefered with 3.0 preparations. https://docs.arangodb.com/devel/Graphs/index.htm now holds the reworked startingpoint for graphs. All other sub-chapters with graph explanation now only contains a reference there, all local 'whats a graph explanations' were removed. We also have a new section explaining graphs to SQL users.

**Comment by dothebart** [comment]
Will be available with non-devel with the 2.8 release. Closing now - feel free to reopen if the current state still has more similar problems.

**Comment by kibarda** [comment]
in https://docs.arangodb.com/devel/Aql/GraphFunctions.html  the expression 'general purpose traversal' is used. (2x)   
This is somewhat confusing, as it sound related to the general graph module...  
A better name maybe ?

**Comment by CoDEmanX** [comment]
"Generic traversal", or just "traversal"?

**Comment by dothebart** [comment]
Updated the documentation with the changes.
