### ISSUE TITLE
Growl/Toast in AQL not showing latest result

### ISSUE THREAD

**Issue by m0ppers** [arangodb/arangodb#1645]
The UI will show a growl/toast whenever I make a syntax error in the AQL editor. When I don't dismiss the growl, edit the AQL and resent it and produce a new error then the old error will still be shown. When I dismiss the old error the new (relevant) error is shown.

I think it should dismiss any undismissed error automatically whenever I submit a new query so I will only see relevant errors.

**Comment by hkernbach** [comment]
fixed.

**Comment by Simran-B** [comment]
I think a query that did not raise any errors should dismiss a still open error growl from an earlier query.

**Comment by hkernbach** [comment]
@Simran-B added :+1:
