### ISSUE TITLE
TOKENS() returns wrong items

### ISSUE THREAD

**Issue by DougGarno55** [arangodb/arangodb#16450]
## My Environment

* __ArangoDB Version__:       3.9.2
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               
* __Infrastructure__:               local
* __Operating System__:         MacOS 10.15.7
* __Total RAM in your machine__:        8Gb
* __Disks in use__:        SSD 250Gb total, 51Gb available
* __Used Package__:     MacOS arangodb3e-3.9.2.x86_64.dmg

## Component, Query & Data

__Affected feature__: AQL query using web interface

__AQL query (if applicable)__:
```
RETURN TOKENS("Apple new line fore californiae", "text_en")
```
__AQL explain and/or profile (if applicable)__:
```
Query String (60 chars, cacheable: true):
 RETURN TOKENS("Apple new line fore californiae", "text_en") 

Execution plan:
 Id   NodeType          Est.   Comment
  1   SingletonNode        1   * ROOT
  2   CalculationNode      1     - LET #0 = [ "appl", "new", "line", "fore", "california" ]   /* json expression */   /* const assignment */
  3   ReturnNode           1     - RETURN #0

Indexes used:
 none

Optimization rules applied:
 none

Optimization rules with highest execution times:
 RuleName                                    Duration [s]
 use-indexes                                      0.00000
 move-calculations-up                             0.00000
 replace-function-with-index                      0.00000
 splice-subqueries                                0.00000
 optimize-count                                   0.00000

40 rule(s) executed, 1 plan(s) created
```
## Steps to reproduce

1.  RETURN TOKENS("Apple new line fore californiae", "text_en")

__Problem__:

Tokens within a string that ends with the letter "e" may not return the proper text.
Example: RETURN TOKENS("Apple new line fore californiae", "text_en")
Returns:
[
  [
    "appl",
    "new",
    "line",
    "fore",
    "california"
  ]
]

__Expected result__:
[
  [
    "apple",
    "new",
    "line",
    "fore",
    "californiae"
  ]
]

**Comment by Simran-B** [comment]
This behavior is correct. The built-in `text_en` Analyzer has stemming enabled, and what you observe is the stemmer reducing tokens to the word stems. You can create a custom Analyzer with stemming disabled and use that instead. See the second example here: https://www.arangodb.com/docs/stable/analyzers.html#text

**Comment by DougGarno55** [comment]
Okay, thanks.  Never heard of "stemming" before.
The examples are for using the shell, what about AQL?

**Comment by DougGarno55** [comment]
Close this issue, I found how to create an Analyzer in the web interface.

**Comment by Simran-B** [comment]
You can't create Analyzers with AQL, only via arangosh or the [HTTP API](https://www.arangodb.com/docs/stable/http/analyzers.html), since 3.9.0 also in the web interface. You can use the Analyzer in AQL afterwards, of course.
