### ISSUE TITLE
Foxx tests not always showing proper stacktraces

### ISSUE THREAD

**Issue by pluma** [arangodb/arangodb#1655]
If a Foxx test throws an error the stacktrace sometimes doesn't show up in the frontend.

See https://groups.google.com/forum/#!msg/arangodb/FdgXktB3X94/5oa_2C2kBwAJ

**Comment by hkernbach** [comment]
@pluma any progress here?

**Comment by pluma** [comment]
I'm closing this as I'm unable to reproduce this behaviour in 3.x and there were other problems with Mocha that have been fixed in the latest devel, 3.1 and 3.0 branches.

If someone can find a way to reproduce this bug in >3.1rc3, feel free to re-open the issue.
