### ISSUE TITLE
aardvark asks for basic auth when cookie is invalid

### ISSUE THREAD

**Issue by razvanphp** [arangodb/arangodb#1656]
I have this in 2.8, but it happens also in 2.7.

For example after a server restart or an upgrade, the logged in cookies are in my browser, and the webinterface pops up basic auth login 5 times, instead of giving me the possibility to login again via cookie (form).

I think you can reproduce this by deleting your session manually while logged in. I fixed it by deleting those cookies, and then I'm correctly redirected back to the login screen.

**Comment by hkernbach** [comment]
This issue should be gone. We're now JSON Web Tokens for authentication.
