### ISSUE TITLE
Ubuntu arangodb-apps folder set to 0700

### ISSUE THREAD

**Issue by geekygnr** [arangodb/arangodb#1667]
Hello,

Firstly, I am loving all the support I have gotten thus far about arangodb. Thank you all so much.

I have found a small issue that is more of a nuisance than a real problem.

I am using ubuntu 14.04 and every time I restart the arangodb service it changes the permissions of /var/lib/arangodb-apps to 0700

Which means for me to access the foxx application I am developing I need to first change the permission of that folder.

Like I said not a big deal, I changed /etc/init.d/arangodb to not do that any more.

Just thought I should let you guys know.

Cheers

**Comment by fceller** [comment]
@geekygnr Thanks for reporting. I'll need to check the install script of the RPM if we can do better.

**Comment by pluma** [comment]
I can confirm it has always been this way (or at least since very early 2.x).

This may have previously not been a problem because apps running in development mode were installed in a different location.

**Comment by pekeler** [comment]
I might be wrong, but I believe this changed with 2.7. These folders used to be group-readable and changed permissions would survive restarts. We actually had to change our deployment script which used to depend on being able to copy files out of this folder.

**Comment by pluma** [comment]
Hm... it could be that the exact permissions changed but I'm pretty sure I've encountered the permission reset itself at least as early as 2.4 (maybe even 2.3).

**Comment by dothebart** [comment]
the 0700 is the proper value for production use (security..) - which is what packages should be made for by default.
If you want to do foxx service development isn't it more practical to configure it to some compfortable directory in first place like: (`/etc/arangodb/arangod.conf`)

    [javascript]
    app-path = /home/myuser/public_arangoapp/

or similar?

**Comment by pluma** [comment]
@dothebart should it bulldoze the file permissions on ever restart, though? This can probably be argued either way, but I think the issue is about the app folder's permissions being enforced on each restart rather than the permissions themselves.

**Comment by geekygnr** [comment]
If this is the case I think I am more confused about what the "Set Development Mode" button does. If I make a new app and push that button I expect to be able to start development.

The project I am on has been so fast and furious I have had to go by the seat of my pants and probably miss some key things like the arangod.conf configuration option.

That being said perhaps this brings up question of documentation. I was using the Foxx in 10 minutes tutorial. Option 2 on https://www.arangodb.com/tutorial-foxx/#developing seems a little misleading.

**Comment by pluma** [comment]
@geekygnr the development mode just means the service/app will be "reloaded" (i.e. files from the filesystem being executed instead of reusing the executed code) every time you access a route. It doesn't affect the files on the filesystem -- it actually works the other way around.
