### ISSUE TITLE
LTRIM removes additional characters 

### ISSUE THREAD

**Issue by ChristyGKrishnan** [arangodb/arangodb#16725]
## My Environment

ArangoDB Version: 3.8.0
Storage Engine: RocksDB
Deployment Mode: Single Server
Deployment Strategy: Manual Start
Infrastructure: own
Operating System: Ubuntu 20.04 |
Used Package: Debian or Ubuntu .deb

__AQL query (if applicable)__:
```
RETURN LTRIM("document/ee1234","document/")

gives result as 1234 instead of ee1234

```
__AQL explain and/or profile (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. 
2. 
3. 

__Problem__:
Character 'e' is removed after /  when LTRIM is used 

__Expected result__:

**Comment by Simran-B** [comment]
The behavior is correct, the function removes all specified **characters** from the left-hand side of the string:

https://www.arangodb.com/docs/stable/aql/functions-string.html#ltrim

`document/` contains an `e` but no digits, therefore, all characters up to the second e get removed.

The correct way of getting a document key from a document ID is to use `PARSE_IDENTIFIER("document/ee1234").key`:

https://www.arangodb.com/docs/stable/aql/functions-document.html#parse_identifier

**Comment by ChristyGKrishnan** [comment]
RETURN LTRIM("document/eeeeeeeeeabcdef","document/")

**Comment by mpoeter** [comment]
@ChristyGKrishnan I think the documentation is pretty clear:
> `LTRIM(value, chars) → strippedString`
>
>Return the string value with whitespace stripped from the start only.
>
>To strip from the end only, see [RTRIM()](https://www.arangodb.com/docs/stable/aql/functions-string.html#rtrim).
>To strip both sides, see [TRIM()](https://www.arangodb.com/docs/stable/aql/functions-string.html#trim).
>
> *    **value** (string): a string
> *    **chars** (string, optional): override the characters that should be removed from the string. It defaults to \r\n \t (i.e. 0x0d, 0x0a, >0x20 and 0x09).
> *    returns *strippedString* (string): value without chars at the left-hand side
>
>**Examples**
>    `LTRIM("foo bar") // "foo bar"`
>    `LTRIM("  foo bar  ") // "foo bar  "`
>    `LTRIM("--==[foo-bar]==--", "-=[]") // "foo-bar]==--"`

By default (if no second argument is specified) LTRIM removes whitespace characters, but you can override the set of characters to be removed as shown in the last example. Therefore `LTRIM("document/eeeeeeeeeabcdef","document/")` is equivalent to `LTRIM("document/eeeeeeeeeabcdef", "/cdemnotu")`. The second argument should not be seen as a "string", but as a "set of characters" (the order is irrelevant).

**Comment by ChristyGKrishnan** [comment]
oh, okay. 
Got it
