### ISSUE TITLE
Extending AQL clarifications

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangodb#1673]
Following up on #1664, https://docs.arangodb.com/AqlExtending/Conventions.html should mention 

- something about strict mode (are my functions automatically in strict mode, or can I declare them to be in strict mode?)
- does the suggested purity of the functions extend to the arguments, i.e. is it OK to do this

```JavaScript
function MYSTUFF::ADD_TIMESTAMP(hash) {
  hash.timestamp = new Date().getTime();
  return hash;
}
```

or should we treat the args as immutable and do something like this

```JavaScript
function MYSTUFF::ADD_TIMESTAMP(hash) {
  return Object.assign({}, hash, {timestamp: new Date().getTime()});
}
```

**Comment by jsteemann** [comment]
Documentation extended accordingly.

**Comment by pekeler** [comment]
Thanks!
