### ISSUE TITLE
Accessing a nested field doesn't work as expected if you add a filter to the query

### ISSUE THREAD

**Issue by shaharido1** [arangodb/arangodb#16747]
## My Environment

* __ArangoDB Version__:       3.7.2 
* __Deployment Mode__:       Single Server 
* __Deployment Strategy__:   Manual Start 
* __Infrastructure__:               Azure

Accessing a nested field doesn't work as expected if you add a filter to the query:
bind param: {field: "nested.nesting"}

this query works:
```
For x in y
      return x.@field
```
![image](https://user-images.githubusercontent.com/22857289/183904625-b189921b-72ad-448b-b3ca-1de2700bc0d0.png)

this query works:
```
For x in y
      filter x.otherField
      return x.nested.nesting
```
![image](https://user-images.githubusercontent.com/22857289/183905030-41b257b9-379a-42b0-bb84-9acaa0d0bc8c.png)

this query works as well:
bind param: {fieldA: 'nested', fieldB: 'nesting'}
```
For x in y
      filter x.otherField
      return x.@fieldA.fieldB
```
![image](https://user-images.githubusercontent.com/22857289/183905153-64e1dcf7-2823-4404-a0a7-c20f025e1a46.png)

but this query returns null
```
For x in y
      filter x.otherField
      return x.@field
```
![image](https://user-images.githubusercontent.com/22857289/183904519-2d73b20c-ef6c-47df-a1b9-460453198080.png)

**Comment by dothebart** [comment]
Hi, 
[Please note that ArangoDB 3.7 is EOL](https://www.arangodb.com/subscriptions/end-of-life-notice/)
Please note that you're running a very old version of 3.7 - the last version released was 3.7.18 which may already contain a fix for your issue.
Please upgrade to ArangoDB 3.8 if the issue still persists and report back.

**Comment by Simran-B** [comment]
If I understand your examples correctly, then what you want to do is this:

```js
FOR doc IN identities
  RETURN doc.@property
```
with the following bind variable:

```json
{ "property": ["properties", "email"] }
```

The see second half of this section: 
https://www.arangodb.com/docs/stable/aql/fundamentals-bind-parameters.html#nested-attributes

And also these ancient release notes: 
https://www.arangodb.com/docs/stable/release-notes-upgrading-changes30.html#attribute-names-and-parameters

**Comment by shaharido1** [comment]
Thank you! Missed that part in the doc!
