### ISSUE TITLE
Web Interface: Error reporting could be improved on data change

### ISSUE THREAD

**Issue by kibarda** [arangodb/arangodb#1676]
on Arango Web interface 2.7.3: 

on insert or update of  a document in CODE mode , if there is a mistake in the data  
like:    {A: "quotesMistake""}   
when one click on the save button the only error feedback is the red background for half a second. 

It would be nice to have another (persistent) notification somewhere.

**Comment by hkernbach** [comment]
We've added this feature already in our newest release.
