### ISSUE TITLE
Support reactive/live queries

### ISSUE THREAD

**Issue by jwarkentin** [arangodb/arangodb#1682]
I hope this isn't a duplicate. I couldn't find anything else on this. It would be incredibly useful if ArangoDB supported some form of live query like [RethinkDB](https://rethinkdb.com/blog/realtime-web/) (excellent coverage of considerations in that post) or OrientDB ([here](http://orientdb.com/livequery/) and [here](http://orientdb.com/docs/2.1/Live-Query.html)). I saw the concept was mentioned in [this](https://github.com/arangodb/arangodb/issues/602#issuecomment-138869059) comment (under 'Server-sent events' heading) on another ArangoDB issue and I think it is worth more focused consideration.

I'm still new to ArangoDB and trying to figure out how to build a realtime app with it. Is there currently at least some way to know when a resource has been updated so I know to query for the updates or do I have to resort to polling right now?

**Comment by pekeler** [comment]
There's #602. I'm also polling right now and would like a more elegant solution to update my client.

**Comment by jwarkentin** [comment]
That's the issue I linked to. From reading that it seemed like it wasn't specifically about the live query feature which is why I created a separate issue for it. Perhaps I'm wrong though.

**Comment by juodumas** [comment]
Something like http://docs.couchdb.org/en/latest/api/database/changes.html with long polling support would be nice.

**Comment by dothebart** [comment]
As @pekeler already pointed out, except for using the marketing names of rethinkdb, this topic is already handled in #602; therefore closing. If some information is missing there, feel free to comment.
