### ISSUE TITLE
Traversal with mixed outbound/inbound

### ISSUE THREAD

**Issue by miguel-porto** [arangodb/arangodb#1683]
Congrats on releasing 2.8!!
I started playing with native traversals. I have just an improvement suggestion: one could specify direction on a per-edge-collection basis. It is common that I need to traverse edge collection A and B both outbound, but in another query, I need to traverse edge collection A outbound but edge collection B inbound. Imagine something like:
FOR v,e,p IN 1..4 'taxent/3010706975127' exists_in OUTBOUND, part_of INBOUND RETURN p

Best!
Miguel

**Comment by miguel-porto** [comment]
This would be very convenient in graphs where a type of edge is always bidirectional, while the others are not. The workaround I'm using now is to add two edges in opposite directions in these cases, but that's not very straightforward to manage.

**Comment by mchacki** [comment]
I totally agree with you and i am already implementing it ;)

**Comment by miguel-porto** [comment]
:-) thank you! Looking forward to it!

**Comment by miguel-porto** [comment]
This was fast! :-)
This will simplify a lot the queries in my case!

**Comment by mchacki** [comment]
You are welcome.
To give some short introduction to the new feature:
```
FOR v,e,p IN 1..4 OUTBOUND 'taxent/3010706975127' exists_in, INBOUND part_of RETURN p
```

The first (and already known) OUTBOUND defines the default direction in the traversal.
The second INBOUND overrides this direction only for the `part_of` collection.
`exists_in` has no own direction so it uses default.
=> Follow exists_in as OUTBOUND and part_of as INBOUND.

All collections can have their own direction if you like and you can combine them arbitrarily OUTBOUND,INBOUND and ANY are allowed to be used at all places.

**Comment by miguel-porto** [comment]
Excellent! Thank you very much.
It seems to me that this feature greatly improves the potential and flexibility of the native traversals; this was the missing piece. Now they are really flexible.
