### ISSUE TITLE
Filtering with function in native traversal does not work in some cases

### ISSUE THREAD

**Issue by miguel-porto** [arangodb/arangodb#1684]
I wonder if this is a bug.
This works:
```
FOR v,e,p IN 1..100 OUTBOUND 'taxent/3010706975127' EXISTS_IN,PART_OF
LET col=PARSE_IDENTIFIER(p.edges[0]._id).collection
FILTER col=='EXISTS_IN'
RETURN p
```

But this does not work, albeit equivalent:
```
FOR v,e,p IN 1..100 OUTBOUND 'taxent/3010706975127' EXISTS_IN,PART_OF
FILTER PARSE_IDENTIFIER(p.edges[0]._id).collection=='EXISTS_IN'
RETURN p
```

But curiously this does work:
```
FOR v,e,p IN 1..100 OUTBOUND 'taxent/3010706975127' EXISTS_IN,PART_OF
FILTER (PARSE_IDENTIFIER(p.edges[0]._id).collection=='EXISTS_IN')==true
RETURN p
```

This seems to happen only in filtering traversals, but I did not test everything.

**Comment by mchacki** [comment]
Hi can confirm that this is broken. seems to be true for all functions. I will look into it. Thank you very much for reporting it.

**Comment by miguel-porto** [comment]
Thank you!
BTW, I think it doesn't make much sense that to know a collection to which a document belongs, we must call a function. That doesn't allow optimizations like in this case. The collection should be an intrinsic property of the documents readily accessible, thereby allowing query optimizations, IMHO.

**Comment by mchacki** [comment]
hi @miguel-porto ,
i totally agree with you. This function was not really necessary unit the new Pattern Matching / Graph Traversal features and we are going to add it asap. The plan is that the query optimizer knows this special function for optimization.

**Comment by miguel-porto** [comment]
Yes that's true, this became only important for the new native traversals... thanks, all the best!
