### ISSUE TITLE
Metrics refactoring suggestion

### ISSUE THREAD

**Issue by BulbaWarrior** [arangodb/arangodb#16859]
__Problem__:
Current state of exported metrics does not allow for flexible monitoring solutions.

__Examples__:
##### arangodb_http_request_statistics_http_<method>_requests_total:
Currently there's a separate metric for each http method. Such solution forces to manually type out each metric in queries which greatly increases code duplication (we can also make queries like ```{__name__=~"arangodb_http_request_statistics_http_.*_requests_total" }```, but it's still not very nice).
The metric would make much more sense if http method became a label, i.e ```arangodb_http_request_statistics_http_requests_total{method="delete"}```

##### *_percent metrics
It's generally better to return absolute values and their thresholds if known. This reduces the amount of computation on the server and allows for more informative dashobards in grafana. A more concrete example:
###### arangodb_network_request_duration_as_percentage_of_timeout
Splittng this metric into `arangodb_network_request_duration` and `arangodb_network_request_timeout` benefits observability and the percentage can be easily calculated.

##### Histograms are too aggregated
Suppose you wanted to find out most frequent slow query. Related metric is `arangodb_aql_slow_query_time`, but it only allows to get information about __all__ existing queries. It would be nice to have a label `query` containing the body of the query.

**Comment by MBkkt** [comment]
> Currently there's a separate metric for each http method. Such solution forces to manually type out each metric in queries which greatly increases code duplication (we can also make queries like {__name__=~"arangodb_http_request_statistics_http_.*_requests_total" }, but it's still not very nice).
The metric would make much more sense if http method became a label, i.e arangodb_http_request_statistics_http_requests_total{method="delete"}

Only if sometimes we create metrics v3.

> arangodb_network_request_duration_as_percentage_of_timeout
Splittng this metric into arangodb_network_request_duration and arangodb_network_request_timeout benefits observability and the percentage can be easily calculated.

Good point, but we still need old metrics for backward compatibility.


> Histograms are too aggregated
Suppose you wanted to find out most frequent slow query. Related metric is arangodb_aql_slow_query_time, but it only allows to get information about all existing queries. It would be nice to have a label query containing the body of the query.

I don't think it's useful. 
You can have a million queries, also query lifetime can be short. 
So we don't need to monitoring them

**Comment by MBkkt** [comment]
Feel free to reopen if have some questions
