### ISSUE TITLE
Better errors when collections fail to load due to size

### ISSUE THREAD

**Issue by juodumas** [arangodb/arangodb#1685]
After looking through the [FAQ](https://www.arangodb.com/faq/) I wanted to see how much RAM ArangoDB actual needs.

For this I have extracted https://s3.amazonaws.com/nosql-sample-data/arangodb-2.6.tar.bz2 on an Ubuntu trusty VM with 4GB RAM, but `arangod` crashed on `db._collection('relations').load()` with `Aborted (core dumped)`. I am attaching the `Vagrantfile` used to spin up the VM and a trace log of the above run in [files.zip](https://github.com/arangodb/arangodb/files/106519/files.zip).

Surprisingly there was no such problem with the `profiles` collection even with 1GB of RAM.

I used these commands in the VM to extract the sample data after downloading `arangodb-2.6.tar.bz2` to the same directory as the `Vagrantfile`:

```
sudo -s
service arangodb stop
cd /var/lib/arangodb
rm -fr *
tar --strip-components=2  --exclude="*.txt" -axvf /vagrant/arangodb-2.6.tar.bz2
arangod --uid arangodb --gid arangodb --upgrade
arangod --uid arangodb --gid arangodb
```

Then in another terminal:

```
arangosh
db._collection('relations').load()
```

**Comment by dothebart** [comment]
The pokec dataset is big, and https://www.arangodb.com/2015/10/benchmark-postgresql-mongodb-arangodb/ speaks clear language about the system requirements. Have a look at the comparison:
https://www.arangodb.com/wp-content/uploads/2015/09/table_v2071.png
which also mentions the memory requirements needed for this dataset.

**Comment by juodumas** [comment]
Still, it would expect ArangoDB to tell me about the problem, not
crash.

**Comment by pluma** [comment]
It would probably be nice if ArangoDB recognized that the data set is too large and bailed with a clear warning message.

**Comment by dothebart** [comment]
Meanwhile with Arangodb 3.2 availability we support RocksDB as a storage Backend, which behaves better with low memory systems. 
Closing this now.
