### ISSUE TITLE
2.7.5 for Homebrew

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangodb#1687]
Can we please get a 2.7.5 build for Homebrew?
https://github.com/Homebrew/homebrew/commits/master/Library/Formula/arangodb.rb

**Comment by fceller** [comment]
I have no idea how to do it. As far as I know I can only push the newest. Or is there a trick?

**Comment by pekeler** [comment]
Oh. Maybe it's possible using a combination of `git push --force` and `git reset --hard` but I'm no git expert. Might not be worth the effort.

**Comment by dothebart** [comment]
We will try whether we can go the tap route:
https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/brew-tap.md

we will then probably have something like:
    brew tap arangodb-homebrew/arangodb275
    brew install arangod275
to install maintenance versions via macports.

**Comment by pekeler** [comment]
Please don't bother if I'm the only one who requested this.

**Comment by dothebart** [comment]
Ok, since homebrew is rather used on development systems, and you still can use other means of installation to get the old maintainance version, we will stop the effort on this and close it now.
