### ISSUE TITLE
Could backups include more information?

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangodb#1695]
On my dev machine...

```
// using 2.7.3
arangodump --include-system-collections true --output-directory system-dump
arangodump --include-system-collections true --output-directory my-dump --server.database mydb
// upgraded to 2.8.0
// downgraded to 2.7.3
rm -rf db/databases/*
arangorestore --create-database true --include-system-collections true --input-directory system-dump
arangorestore --create-database true --include-system-collections true --input-directory my-dump --server.database mydb
```

Now I still need to

1) re-enter dependencies of my services
2) re-configure my services
3) re-set my app to be in dev mode
4) re-create the queue

Can't all these things be included in the backup, so I don't need to do them manually?

Btw. I remember having to do 1, 2, and 3, but 4 seems new. Bug?

**Comment by pluma** [comment]
For context: the dependencies and configuration (and other settings like dev mode) should be included in the `_apps` system collection, the queues etc also exist in system collections. I'm guessing that `--include-system-collections` doesn't actually include these collections or doesn't correctly import them. These system collections are also "special" in that they're created on first use (as far as I can tell), so maybe there's something fishy going on with that.

**Comment by pekeler** [comment]
Yeah, after restarting arangod for the second time after arangorestore, the queue magically appeared.

**Comment by pekeler** [comment]
I'm struggling with this issue again as I'm trying to set up a new system from a backup. May I suggest that this is a more important issue than "quality of life".

When my production server burned down and I'm struggling to set up the replacement from a backup, things like missing queues should not bog me down.

**Comment by fceller** [comment]
@pekeler agreed, we should find a solution for that.

**Comment by jsteemann** [comment]
@pekeler: is the main problem that system collections are not included in the backup by default, or is there anything else (e.g. filesystem code of Foxx applications)?

**Comment by pekeler** [comment]
I'd like the backup to include queues, service dependencies, and service configs. Basically, everything that's in the DB should be in the backup (when using `--include-system-collections true`).

Including the Foxx apps themselves is not absolutely necessary because most users probably understand that the underlying JS of the Foxx apps is not data. However, it would be a *very* nice improvement to include them as well. Then all we'd have to do is install vanilla ArangoDB, restore the backup, and then everything would be ready to go and behave exactly like the original where the backup was made.

**Comment by dothebart** [comment]
probably `--full` simply should give you everything you need to get one db saved and restored, right?

**Comment by Simran-B** [comment]
There seems to be a demand for an option to dump **all** databases as well.

**Comment by dothebart** [comment]
Arangodump supports `--all-databases` - https://www.arangodb.com/docs/devel/programs-arangodump-options.html closing as solved.
