### ISSUE TITLE
foxx: bug xor feature: cant catch route '/' | avoid 307 on '/' to index.html

### ISSUE THREAD

**Issue by baslr** [arangodb/arangodb#1698]
Hi,

is it possible to tell foxx not to redirect `/` calls to `index.html` or catch route `/`?

I tried 

```javascript
// controllers/test.js

var Foxx = require("org/arangodb/foxx");
var publicController = new Foxx.Controller(applicationContext);

controller.get('/', function (req, res) {
  res.json({a:'/'});
});

controller.get('/*', function (req, res) {
  res.json({a:'/*'});
});

// manifest
  "controllers": {
    "/": "controllers/test.js"
  }
```

but
```
http://127.0.0.1:8529/_db/_system/view -> 307 to index.html ->
{"a":"/*"}

http://127.0.0.1:8529/_db/_system/view/ -> 307 to index.html ->
{"a":"/*"}


http://127.0.0.1:8529/_db/_system/view/a ->
{"a":"/*"}
```

thanks for help.

**Comment by mchacki** [comment]
Hi this can be done with the defaultDocument switch in `manifest.json`

    {
        "controllers": {
          "/": "controllers/test.js"
       }
      "defaultDocument": ""
    }

This is default to `index.html` and can be overwritten with any other file/route. To disable it just set it to empty-string

**Comment by baslr** [comment]
Hi Michael,

thanks for your help. It works.

**Comment by mchacki** [comment]
you are welcome
