### ISSUE TITLE
web interface - After selecting a database, lose menu option to manage databases

### ISSUE THREAD

**Issue by yehosef** [arangodb/arangodb#1699]
When I choose a database to work with from the top menu, I no longer have the link for "manage databases" to add another one. Using Chrome on OSX using homebrew installed 2.8.1.  Clicking on the logo takes me back to what seems like the starting page - but the menus are still wrong.

Also - the Tools menu has "Logs" from the start dashboard  but loses this when looking at a database.

**Comment by jsteemann** [comment]
This is intentional. Managing databases and inspecting the logs is only possible from within the `_system` database. So after switching to another database, these menu items will be gone. Switching back to `_system` will bring them back.

**Comment by yehosef** [comment]
Thanks for the explanation - I understand more of why it works this way. 

But I think it's bad user experience.  How could I have guessed this?  I spent several minutes trying to figure out how to do this and took the trouble to fill in a bug report. All you have to do is have the link there and make that an implicit change to the _system database. 

Please reconsider.
