### ISSUE TITLE
Installation on OpenSuse Leap 42 requires libtcmalloc4

### ISSUE THREAD

**Issue by zopyx** [arangodb/arangodb#1703]
zypper install libtcmalloc4

is needed for the installation of the OpenLeap 42.1

**Comment by fceller** [comment]
Strange. Normally the dependencies are automatically generated. I'll try to disable tcmalloc on Leap for the moment.

**Comment by andreasstieger** [comment]
What are the dependencies generated just now?

**Comment by dothebart** [comment]
we disabled tcmalloc for 2.8.2: 
https://build.opensuse.org/package/rdiff/home:fceller:version2/arangodb-2.8?linkrev=base&rev=19
saadly the minor release wiped the old tarball at http://download.opensuse.org/repositories/home:/fceller:/version2/openSUSE_Leap_42.1/x86_64/ 

However, the earlier one:
rpm -qpR ./arangodb-2.7.6-21.1.x86_64.rpm
...
libtcmalloc.so.4()(64bit)

**Comment by andreasstieger** [comment]
This capability is provided by said package and that package alone.

    $ zypper search -s --provides --match-exact "libtcmalloc.so.4()(64bit)"
    Loading repository data...
    Reading installed packages...
    
    S | Name         | Type    | Version | Arch   | Repository           
    --+--------------+---------+---------+--------+----------------------
      | libtcmalloc4 | package | 2.4-3.3 | x86_64 | Main Repository (OSS)


    $ zypper info --provides libtcmalloc4
    Loading repository data...
    Reading installed packages...
    
    
    Information for package libtcmalloc4:
    -------------------------------------
    Repository: Main Repository (OSS)
    Name: libtcmalloc4
    Version: 2.4-3.3
    Arch: x86_64
    Vendor: openSUSE
    Installed: No
    Status: not installed
    Installed Size: 1.3 MiB
    Summary: Thread-caching malloc library
    Description: 
      This subpackage contains a library with optimized thread-caching
      malloc().
    Provides:
      libtcmalloc_minimal.so.4()(64bit)
      libtcmalloc.so.4()(64bit)
      libtcmalloc_and_profiler.so.4()(64bit)
      libtcmalloc_debug.so.4()(64bit)
      libtcmalloc_minimal_debug.so.4()(64bit)
      libtcmalloc4 == 2.4-3.3
      libtcmalloc4(x86-64) == 2.4-3.3


User must have installed ignoring dependencies. So of course the package is required, but since it is required by arangodb correctly I do not see an issue here unless the reporter can demonstrate that it is.

**Comment by dothebart** [comment]
meanwhile whith ArangoDB 3.0 neither ArangoDB nor go are a dependency anymore. We now use jemalloc, which is linked in static. So we can close this issue now.
