### ISSUE TITLE
Allow ticks as escape character to avoid backslash escapes inside of template strings in JS?

### ISSUE THREAD

**Issue by CoDEmanX** [arangodb/arangodb#1705]
If you don't want to use the AQL query builder in JavaScript, you can still embed plain AQL queries in your JS code. There are multiple options how to do multi-line strings for that, but the most convenient way in ECMA2015 times is probably to use template strings:

```js
let query = `some
multi-line
string`
```

If you got collection names which conflict with AQL keywords, they need to be wrapped in backticks. Not allowed:

```js
FOR f IN filter
  RETURN f.sort
```

Valid:

```js
FOR f IN `filter` 
  RETURN f.`sort`
```

Backticks are also used for template strings in JS, which means, you can't do this:

```js
let query = `
FOR f IN `filter` 
  RETURN f.`sort`
`
```

You need to do:

```js
let query = `
FOR f IN \`filter\` 
  RETURN f.\`sort\`
`
```

... which is not very pretty. If Arango supported forward ticks instead, or in addition, it could become:

```js
let query = `
FOR f IN ´filter´ 
  RETURN f.´sort´
`
```

Please discuss!

**Comment by jsteemann** [comment]
@CoDEmanX : the devel branch supports the usage of forward ticks as an alternative. Can you give it a try and check whether it's any helpful?

**Comment by Simran-B** [comment]
Works! @pluma and me believe it's useful, even if it's limited to JS users.

We actually wonder if forward ticks have meaning in any programming language, or if they are a neglected character...
