### ISSUE TITLE
Make upgrade notification less intrusive

### ISSUE THREAD

**Issue by m0ppers** [arangodb/arangodb#1706]
When starting in cluster mode the upgrade dialog should probably be disabled. It implies that it is possible (which it is not).

**Comment by pekeler** [comment]
Not just in cluster mode. That modal in Aardvark is annoying. I'd much rather have some passive display somewhere on the side.

**Comment by baslr** [comment]
![bildschirmfoto 2016-02-12 um 10 20 44](https://cloud.githubusercontent.com/assets/1494154/13002902/61e72a98-d172-11e5-9dc8-0067214dcf81.png)

**Comment by pluma** [comment]
@baslr Or even just highlight (bold) the version and change the icon to indicate a call-to-action. It could also distinguish between bugfix and minor/major releases with the icon and the highlight colour.

**Comment by hkernbach** [comment]
thanks for all of your feedback. it is changed in current branch devel and will not bother you anymore ;)
