### ISSUE TITLE
Web Interface: make system tables read-only ?

### ISSUE THREAD

**Issue by kibarda** [arangodb/arangodb#1709]
hey!

(on 2.8)
i've tried to change a User Defined function directly in _aqlfunctions in webinterface. 
Not a good idea  apparently as it seems to work inconsistently.
I guess some system tables should be made read-only in the Web Interface.

Cheers,
jm

**Comment by baslr** [comment]
Hi kibarda,

to change userfunction you have to use the interface. https://docs.arangodb.com/2.8/HttpAqlUserFunctions/index.html
`All user functions managed through this interface will be stored in the system collection _aqlfunctions. Documents in this collection should not be accessed directly, but only via the dedicated interfaces.`

**Comment by kibarda** [comment]
I've added this statement in AqlExtending/Conventions, was missing there. 
Anyway, I still believe this table should be made read-only.

**Comment by dothebart** [comment]
Yes, the webinterface should definitely try to stop the user from leaving the intended path. If not completely prohibit, then show a warning that this collection shouldn't be modified.

**Comment by pluma** [comment]
The system collections are hidden by default. Are there any system collections which *are* perfectly safe to edit? Having them hidden behind a flag already serves as a deterrent.

**Comment by hkernbach** [comment]
@pluma: also was my thought

**Comment by pluma** [comment]
Maybe we could show some kind of indicator when working inside a system collection? There's not much you can do other than warn people.

**Comment by hkernbach** [comment]
Added a warning message when saving a system collection.
