### ISSUE TITLE
AQL new traversal syntax - minDepth 0

### ISSUE THREAD

**Issue by specimen151** [arangodb/arangodb#1711]
I've noticed a difference between the old TRAVERSAL syntax and the new INBOUND/OUTBOUND/ANY syntax, which I propose a small change to (humbly of course).

    for u in traversal(cells, cellTree, 'cells/ABCRoot', 'inbound', {maxDepth:5})
    return u.vertex

    for u in 1..5  INBOUND 'cells/ABCRoot' cellTree
    return u

The first traversal will include the start vertex, while the second traversal starts directly at the children at level 1.

It would be nice in many situations to include the start vertex, so I wouldn't need to manually select it using for + filter, just to get that single one, and then an APPEND or UNION.

This could be done by allowing a minDepth of 0. A small change, keeping the syntax and the semantics of the syntax. This also makes it possible to replace more TRAVERSAL() with the new syntax.

**Comment by CoDEmanX** [comment]
I think I ran in this too and ended up using the third parameter, the path, like

for u, e, path in 1..5  ...

because it had the entire path from start to finish and the first element was the start vertex, not the first child.

**Comment by dothebart** [comment]
Yes, I see your point. We have been discussing about that internaly.
Initially in Beta1 we allowed 0..n, but wouldn't return [0] either. We changed the query parser to only accept 1, to make the query persistant to the result.
We're still in discussion whether & when to implement this; Marking it as feature request.

**Comment by baslr** [comment]
@dothebart why not include the starting vertex?
With 'to make the query persistant to the result' you mean another start vertex that lead to the same result (with 1..n but with 0..n result !same)?

**Comment by dothebart** [comment]
To make it clear, the implementation during earlier development would also not return you the 0'th node. So if it wouldn't error you `0..` you would have gotten a result that doesn't actually match the query. Thats what I meant by making it persistent.

I also saw the [necessity to provide the 0'th vertex](http://stackoverflow.com/questions/33165581/is-it-possible-to-show-search-result-in-graph-viewer). However, its a non trivial implement it, so we may see it after the 3.0x release cycle, but not for 3.0. The SO issue also show a way to work around the limitation.

**Comment by dothebart** [comment]
you can download and try ArangoDB 3.0 RC2 via https://www.arangodb.com/download-preview/
Its got the ability to output the traverser start node. It will pair it with a `null` edge, since you don't have an edge pointing to it, so you can better work with arrays.
