### ISSUE TITLE
Image upload

### ISSUE THREAD

**Issue by AmmarMohamed** [arangodb/arangodb#1712]
I have a problem ,when I made upload that upload the image with metadata then the image not open, when I delete the metadata the image is open successful , I use Foxx 
I need a solution for this problem.
thanks.

**Comment by jsteemann** [comment]
Can you provide a bit more context please? What exactly are you storing, and what exactly is not working? Is there any error message etc.?

**Comment by dothebart** [comment]
@AmmarMohamed any feedback? or can we close this issue?
