### ISSUE TITLE
Graph module using incorrect collections

### ISSUE THREAD

**Issue by Ascerta** [arangodb/arangodb#1714]
When building a graph via a Foxx script, collections from a different database are used.

I have two databases set up 'dev', 'live'

Both have a copy of the same Foxx app running. I have a script that sets up and migrates the graph structure. 

Running the Foxx script first on the 'live' database results in a correctly constructed graph. 

If I then run the same script in the 'dev' Foxx app a graph is constructed but it references collections from the 'live' database. Graph names and collections have the same name.

New collections are added correctly so it would appeal the graph_module isn't using the correct database. Construction using the web ui works correctly.

Sample of the migration Foxx script:

`var db = require("org/arangodb").db;
var graph_module = require("org/arangodb/general-graph");

graph_module._create('mygraph');

var boardioGraph = graph_module._graph('mygraph');
        createCollection("people");
        boardioGraph._addVertexCollection("people");
`

**Comment by hkernbach** [comment]
Solved?

**Comment by Ascerta** [comment]
No, sorry I double submitted
