### ISSUE TITLE
Graph module using incorrect collections

### ISSUE THREAD

**Issue by Ascerta** [arangodb/arangodb#1715]
When building a graph via a Foxx script in a database that isn't _system, collections aren't referenced correctly.

I have two databases set up 'dev', 'live'

Both have a copy of the same Foxx app running. I have a script that sets up and migrates the graph structure. 

Running the Foxx script first on the 'live' database results in a correctly constructed graph. 

If I then run the same script in the 'dev' Foxx app a graph is constructed but it references collections from the 'live' database. Graph names and collections have the same name.

--Edit: I've just cleaned and rerun the entire process and even if I only run the migration script in one database, if it's not _system the graph construction is still broken. 

New collections are added correctly so it would appeal the graph_module isn't using the correct database. Construction using the web ui works correctly.

Sample of the migration Foxx script:

`var db = require("org/arangodb").db;
var graph_module = require("org/arangodb/general-graph");

graph_module._create('mygraph');

var boardioGraph = graph_module._graph('mygraph');
        createCollection("people");
        boardioGraph._addVertexCollection("people");
`

**Comment by Ascerta** [comment]
Further to this. Now whenever I try to create a graph with the same name it always says it's empty. Creating a new graph with exactly the same collections but using a different name results in a working graph.

**Comment by Ascerta** [comment]
I think I've managed to reproduce the fault via the Web UI:

Create two new databases: dba, dbb (user: root, no password)

Switch to dba:
Create 3 collections: people(vertex), cats(vertex), pets(edge)
Create a new graph called root with an edge definition: pets, from: people, to: cats - add vertex collections: people, cats

Switch to dbb 
Create 3 collections: people(vertex), cats(vertex), pets(edge)
Create a new graph called root with an edge definition: pets, from: people, to: cats- add vertex collections: people, cats

Add a new document to 'people' in dbb
It shows up in dbb 'root' (graph) as expected

Switch to dba and the collections are empty but the graph is showing data from dbb's collections

If you then delete all of the graphs and collections from both databases and then recreate it just in dba the graph still won't populate from the correct collections. You have to chose a different graph name.

**Comment by dothebart** [comment]
Ok, I tried the following: 
(arangosh: )
    var examples = require("org/arangodb/graph-examples/example-graph.js");
    db._createDatabase("test1")
    db._useDatabase("test1")
    examples.loadGraph("knows_graph");

Then to have a difference, remove Eve from the graph:
    db._query("LET keys = (FOR v, e IN 1..1 ANY 'persons/eve' GRAPH 'knows_graph' REMOVE e._key IN knows) REMOVE 'eve' IN persons")

    db._useDatabase("_system")
    db._createDatabase("test1")
    db._useDatabase("test1")
    examples.loadGraph("knows_graph");

Then I used foxx generator to create a test service, I replaced the GET route:

    controller.get('/', function (req, res) {
       res.json(require("internal").db.knows.toArray());
    });

so it outputs the `knows` collection from within the foxx context.
I downloaded the foxx, and re-installed it on the other database.

I Installed it on the test2 database, and also tried, and in one case I got the knows collection with, and in the other case without eve.

**Comment by Ascerta** [comment]
@dothebart that's fantastic. Thanks for double checking. I repeated what you did and can confirm it works as it should. 

The problem seems to be with the Graph Viewer in aardvark - if there are two graphs with the same name it seems to maintain the state of the previous one you were viewing. I was checking the graph was created by using the viewer and that was saying it's empty.

**Comment by dothebart** [comment]
ok, so if you master reload your browser (ctrl+shift+f5 or ctrl+shift+r) that is fixed? 
The graph viewer currently remembers some things in the browser local storage; maybe it needs to add the database in the game there too. In the end it should persist / retrieve stuff from arangodb itself. @hkernbach, could you have a look at the browser local storage?

**Comment by hkernbach** [comment]
Should be fixed now (devel). Could you check?
