### ISSUE TITLE
Foxx generator should offer creating edge collections

### ISSUE THREAD

**Issue by AmmarMohamed** [arangodb/arangodb#1718]
When i Install Service the default collection type is document ,But i need to create Edge collection didn't  find the edge type when i Install Service.
pleas help me quickly.    

![arango](https://cloud.githubusercontent.com/assets/13071857/12942369/173c5990-cfe3-11e5-9be2-00250fa60cca.PNG)

**Comment by baslr** [comment]
Hi,

at Collections: you specify only the names.
You have to navigate to `APP/scripts/setup.js`

and change `db._create(collectionName);` to `db._create(collectionName, {}, 'edge');`

**Comment by AmmarMohamed** [comment]
i chenge the db._create(collectionName); to db._create(collectionName, {}, 'edge'); 
but the collection didn't change

**Comment by dothebart** [comment]
You have to re-deploy your FOXX service in order to have the setup routine be called. If you want to do this with your current installation, you will have to do this by hand in arangosh: 

db._createEdgeCollection('<foxxroute>collectionname')


Note: I altered the title so this can be integrated in future versions.

**Comment by pluma** [comment]
Hi @AmmarMohamed,

you're right, the generator currently only lets you generate document collections. It would probably be useful to be able to add edge collections as well. These would probably need different templates as the API of edge collections is slightly different (e.g. `save` needs an explicit `_to` and `_from`).

@hkernbach this change would require some changes to code that is being rewritten as part of the FOTF effort.

**Comment by pluma** [comment]
It's in FOTF now.

**Comment by pluma** [comment]
Fixed via FOTF.
