### ISSUE TITLE
How to do Fulltext search on the below Document with ArangoDB?

### ISSUE THREAD

**Issue by ansarihaseb** [arangodb/arangodb#1719]
{
  "rootElement": {
    "names": {
      "name": [
        "Haseb",
        "Anil",
        "Ajinkya",
        {
          "city": "mumbai",
          "state": "maharashtra",
          "job": {
            "second": "bosch",
            "first": "infosys"
          }
        }
      ]
    },
    "places": {
      "place": {
        "origin": "INDIA",
        "current": "GERMANY"
      }
    }
  }
}

If I had the document like the above example and I want to search the value like "mumbai" or "infosys" then how would I do the indexing and search for the same. Help would highly be appreciated. Thanks in advance :)

**Comment by dothebart** [comment]
closing as duplicate. http://stackoverflow.com/questions/35322859/how-to-do-fulltext-search-on-the-below-document-with-arangodb/35323834#35323834
