### ISSUE TITLE
Manual: Google Custom Search should only return results for the same manual version 

### ISSUE THREAD

**Issue by thurt** [arangodb/arangodb#1720]
I am using arangodb manual at https://docs.arangodb.com/2.7/
When I used the Google Custom search from this address I received pages labelled for version 2.8.

**Comment by hkernbach** [comment]
With the current implementation it is not easy to realise the desired behaviour.

**Comment by dothebart** [comment]
this will be handled as part of the later created #1721 during the 3.0 release cycle. Closing this one as duplicate therefore; thanks for the suggestion.
