### ISSUE TITLE
ArangoDB 3.9.3 community version macOS build no longer starts on macOS 11.7

### ISSUE THREAD

**Issue by jlangch** [arangodb/arangodb#17213]
## My Environment

* __ArangoDB Version__:        3.9.3, official macOS DMG package
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               plain config as created by DMG installer
* __Infrastructure__:              MacBook Pro 2017, Quad-Core Intel Core i7 
* __Operating System__:       MacOS 11.7
* __Total RAM in your machine__:        16Gb
* __Disks in use__:        SD
* __Used Package__:              DMG package from https://download.arangodb.com/arangodb39/Community/MacOSX/

## Component, Query & Data

__Affected feature__: Installation, server does not start and leaves no log file

## Steps to reproduce

1. Download the official 3.9.3 DMG package from https://download.arangodb.com/arangodb39/Community/MacOSX/
2. Install the DMG package
3. Manually start the ArangoDB3-CLI.app

__Problem__:  The ArangoDB server does not start and does not leave a log file!

Only if the server is started manually from a command line shell 

```
arangod \
     -c $HOME/Library/ArangoDB-etc/arangod.conf \
     --daemon \
     --pid-file /var/tmp/arangod.pid
```
     
an error is printed to stdout:

```
dyld: Library not loaded: /usr/local/opt/llvm@13/lib/libc++.1.dylib
  Referenced from: /Applications/ArangoDB3-CLI.app/Contents/Resources/opt/arangodb/sbin/arangod
  Reason: image not found
Abort trap: 6
```

Obviously, the LLVM 13 lib 'libc++.1.dylib' is not available.

ArangoDB 3.9.2 and older versions just run fine, because they are based on LLVM 11.

What is the suggested procedure to install ArangoDB 3.9.3 on MacOS without LLVM 13 libs?

Installing the missing llvm@13 libs with Homebrew does not work either. After installing LLVM 13 with Homebrew I run into a code signing problem:

```
code signature in (/usr/local/opt/llvm@13/lib/libc++.1.dylib) not valid for use in 
process using Library Validation: mapped file has no cdhash, completely unsigned? 
Code has to be at least ad-hoc signed.
```

**Comment by dothebart** [comment]
Thanks for reporting, this indeed slipped through. The binaries should have been static (hence carrying the compiler runtime inside of them)
We're fixing this.

**Comment by jlangch** [comment]
Hi,

do you have any news or plans on this issue?

thanks

**Comment by dothebart** [comment]
Hi, 
It seems that homebrew insists on using a compiler which we can not support. 
Please use the binaries via arangodb.com or prefereable a docker container.

**Comment by jlangch** [comment]
Hi,

I am sorry for the late answer, but I was on ski holiday.

I am not using Homebrew for installing packages. As mentioned above, I use the official ArangoDB MacOSX DMG from https://download.arangodb.com/arangodb310/Community/MacOSX/index.html

Just gave a try to the 3.10.3 Package and it works.

Got a "ArangoDB 3.10.3 [darwin] 64bit, using build tags/v3.10.3-0-ge475801e2fe" message from the log

I will give a try to the 3.9.8 package as well, but 3.10.3 is perfect. I will go anyway with the most recent version

Thanks a lot for working on the issue

**Comment by dothebart** [comment]
thanks for confirming.
