### ISSUE TITLE
Manual: provide easy way to switch between versions

### ISSUE THREAD

**Issue by pluma** [arangodb/arangodb#1721]
@CoDEmanX pointed out that the [Python documentation](https://docs.python.org) has a version dropdown to quickly switch between different versions of the documentation (and stay in the same chapter if it exists in both versions).

Currently the discoverability of the ability to switch between versions of the docs is practically nil (especially if you get used to go straight to docs.arangodb.com and forget about arangodb.com/documentation). Maybe we could also have an automatic redirect from docs.arangodb.com to docs.arangodb.com/<latest-stable-version> -- that should also help with googleability ("cool URIs don't change" -- unlike ours whenever a new version adds/removes a chapter).

**Comment by dothebart** [comment]
you can do docs.arangodb.com/2.8/
etc.

**Comment by pluma** [comment]
Yes. A UI for that would be nice. That's what this ticket is about. Humans don't manipulate URLs :wink:

**Comment by Simran-B** [comment]
We have a version dropdown meanwhile. It is a manual process to add new versions, but it works for now.
