### ISSUE TITLE
Manual: needs clarification on collection.toArray

### ISSUE THREAD

**Issue by thurt** [arangodb/arangodb#1725]
https://docs.arangodb.com/Documents/DocumentMethods.html
> collection.toArray()
> Converts the collection into an array of documents. **Never use this call in a production environment.**

The bolded statement above needs *why* clarification. 

I'm guessing this is simply a precaution that applies only to *large* collections.

**Comment by pluma** [comment]
I'm guessing so as well. It may also be especially slow in a cluster.

You should probably use `collection.all()` instead as this returns a cursor (along with all optimizations that may entail, such as being able to work with one document at a time via `cursor.next()`). And obviously if you don't strictly need *all* documents you should just fetch the ones you're actually interested in.

**Comment by thurt** [comment]
**Re optimizations:** does this mean that there is a difference between invoking `collection.all().toArray()` vs. `collection.toArray()` ? I assumed they were synonymous, excepting that `collection.all()` allows possible addition of cursor methods before calling `toArray()`

**Comment by pluma** [comment]
@thurt I actually don't know. But with a cursor you don't have to load everything into JS at once and can actually iterate over it one document at a time, so there's definitely a difference between `all()` and `toArray()` itself.

**Comment by thurt** [comment]
@pluma I was able to check `db.collection.all` vs. `db.collection.toArray` from arangosh~
```javascript
// db.collection.all
function () {
  return new SimpleQueryAll(this);
}

// db.collection.toArray
function () {
  return this.all().toArray();
}
```
So `collection.all().toArray()` is equivalent to `collection.toArray()`

Thanks also for explaining some of these things at level 1. I am just starting to understand the advantages of cursors & AQL :+1:

**Comment by dothebart** [comment]
ArangoDB builds up the cursor in ram to reduce locking time on the collection. Therefore depending on the number of documents in the collection this will require a lot of resources - it will basically be an in memory copy of the collection.

**Comment by dothebart** [comment]
Closing via b53108036e2eb6e94385a632ac4af2025708e6d9 

ArangoDB 3.0.0 RC2 is available for download now via https://www.arangodb.com/download-preview/
