### ISSUE TITLE
Aardvark collection filtering is sticky across collections (bug)

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangodb#1727]
Using 2.8.1:

1) click on collections
2) select collection A
3) see all A documents (paginated)
4) click on collections
5) select collection B
6) use filter to find one particular B document
7) click on collections
8) select collection A
9) wonder why there are no A documents displayed

Now I either have to reload the page, or "reset" the filter to see my A documents.

**Comment by hkernbach** [comment]
Thanks. Fixed in devel.
