### ISSUE TITLE
feature request: AQL CONTAINS function for arrays

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangodb#1728]
Right now, I need to do something like

```
INTERSECTION(UNIQUE(myArray), [mySearchValue]) == [mySearchValue]
```

I'd prefer something like this (for consistency with the CONTAINS function for String)

```
CONTAINS(myArray, mySearchValue)
```

**Comment by Simran-B** [comment]
There you go:

`yourArray ANY == yourSearchValue`

Jan implemented the array operators ALL, ANY and NONE 10 days ago (available in devel branch). Have a look here: #1629

**Comment by pekeler** [comment]
Oh cool. Thanks!
