### ISSUE TITLE
Reload configuration without interrupting service / change config at runtime

### ISSUE THREAD

**Issue by matcho** [arangodb/arangodb#17281]
## My Environment

* __ArangoDB Version__:       3.8.7
* __Deployment Mode__:       Leader/Follower
* __Deployment Strategy__:   systemd
* __Infrastructure__:               own
* __Operating System__:        Ubuntu 20.04
* __Total RAM in your machine__:        256GB
* __Disks in use__:        SSD
* __Used Package__:             Ubuntu .deb

## Component, Query & Data

__Affected feature__:
Configuration options

Hello,

We recently ran into some OOM issue that made us want to change `memory-limit` and `global-memory-limit` configuration options.
It seems that ArangoDB has to be restarted for those configuration changes (set in `/etc/arangodb3/arangod.conf`) to take effect, which induces a service interruption that, although quick, is problematic in a work-heavy production context.

From the documentation, it seems that configuration options cannot be defined at runtime (except cache related ones).

Is there any way to change those options without interrupting the service ? Maybe some kind of `reload` command, or POSIX signal to send ?

Thank you very much,
Greetings,

Mathias

**Comment by dothebart** [comment]
Hi, 
for high availability you would use setups like ArangoDB Clusters or Active Failover; There you then can restart the instances one by one.

**Comment by matcho** [comment]
Hi, thank you for the quick answer. Indeed, Active Failover mode is something that we missed for some reason, and are now looking at seriously. Let's go for this one, then :)

Thanks again
Mathias
