### ISSUE TITLE
Nginx cannot access to arangodb unix socket

### ISSUE THREAD

**Issue by Mirzaev228** [arangodb/arangodb#17302]
## My Environment

* __ArangoDB Version__:        Version 0.15.5, build 7832707, Go go1.17.13 (sudo arangodb --version)
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start (ubuntu systemd generated service)
* __Operating System__:        Ubuntu 22.04.1 LTS    
* __Total RAM in your machine__:        4Gb
* __Disks in use__:        SSD
* __Used Package__:              Debian or Ubuntu .deb

## Component, Query & Data

__Affected feature__: Installation

__Problem__:

hello everyone

i set endpoint to unix socket in default /var/run/arangodb3 folder
![изображение](https://user-images.githubusercontent.com/21334019/194698698-4444606f-7fea-4c2c-8aa8-d3224897de33.png)

is created succesfully
![изображение](https://user-images.githubusercontent.com/21334019/194698729-d7453241-0aad-4973-b217-3336b1241b05.png)

i make a simple nginx config
![изображение](https://user-images.githubusercontent.com/21334019/194698877-0d2e02b1-ae47-4fc8-bdcf-519d9cf959fd.png)

and get error
2022/10/08 18:49:49 [crit] 14235#0: *1 connect() to unix:/var/run/arangodb3/arango.sock failed (13: Permission denied) while connecting to upstream, client: 172.70.123.59, server: adb.mirzaev.sexy, request: "GET /_db/_system/_admin/aardvark/index.html HTTP/2.0", upstream: "http://unix:/var/run/arangodb3/arango.sock:/_db/_system/_admin/aardvark/index.html", host: "adb.mirzaev.sexy"

if i run command: "sudo chmod g+w /var/run/arangodb3/arango.sock", everything works fine, but after "service arangodb3 restart" the socket file recreates with default flags

www-data added to arangodb group

__Expected result__:
Nginx proxy to arangodb web interface on subdomain adb (adb.domain.zone)

**Comment by dothebart** [comment]
An easy workaround could probably be to have `/var/run/arangodb3` to be g+S for www-data

**Comment by Mirzaev228** [comment]
### SOLUTION

add parameter "--daemon true" and write this to /usr/lib/systemd/system/arangodb3.service:
`ExecStartPost=/usr/bin/env chmod 0775 -R /var/run/arangodb3`

![изображение](https://user-images.githubusercontent.com/21334019/194885912-19854262-0d1c-49ec-8c6e-60b0163bcd51.png)

### RESULT
![изображение](https://user-images.githubusercontent.com/21334019/194886027-d668edb1-6e30-4866-8231-d19d5aea35e3.png)
