### ISSUE TITLE
Improvements for Slow Query Log

### ISSUE THREAD

**Issue by razvanphp** [arangodb/arangodb#1732]
To make this even more useful on the web interface, please add an AJAX refresh button, as refreshing the whole page takes too long, and this make it very hard to catch active queries.

Also, if would be good to somehow include the bind parameters values too, since some queries are slow only with specific parameters, so it's hard to debug them.

Thank you!

**Comment by CoDEmanX** [comment]
Does it also take long if you click the tab "active" or "slow" respectively?

**Comment by razvanphp** [comment]
Hmm, ok, this is embarrassing, but I had no idea that this triggers an update. Maybe we can close this, or keep it only for the bind params.

PS: maybe an icon added to the tabs? hint? I'm just thinking about usability of new users, I'm educated now.

**Comment by CoDEmanX** [comment]
Don't be embarrassed, I figured this out myself just a day ago xD

From an UX perspective, there should be a dedicated refresh button, because it's not apparent that you can click on the tabs to update. Maybe even automatically update?

**Comment by hkernbach** [comment]
We'll implement something with automatically updates I guess. I'll track the bind param request in a new ticket.

**Comment by hkernbach** [comment]
Added auto update of query management view in current devel branch.

**Comment by razvanphp** [comment]
How often does it happen? Is it still possible to click on tabs for faster reload so that we can catch nasty queries?

**Comment by hkernbach** [comment]
Every 2 seconds. Yes, the 'old tab way' is still possible.
