### ISSUE TITLE
Arangodump not dumping graphs

### ISSUE THREAD

**Issue by jdgamsterdam** [arangodb/arangodb#17323]
## My Environment

* __ArangoDB Version__:        3.10
* __Deployment Mode__:       Docker 
* __Deployment Strategy__:    ArangoDB Starter in Docker 
* __Configuration__:              
* __Infrastructure__:            own 
* __Operating System__:        Windows 10
* __Total RAM in your machine__: 16Gb. Server, 100GB Client 
* __Disks in use__:       SSD 
* __Used Package__:            Docker - official Docker library

## Component, Query & Data

__Affected feature__:
Arangodump and arangorestore
## Steps to reproduce

1. Create Database with nodes and edges
2. Create a graph either interactively or programatically
3.  Arangodump the database
4.  Delete the database
5. Arangorestore the database
6. Everything is there except for the Graph
7
__Problem__:

__Expected result__:

**Comment by dothebart** [comment]
Hi, 
to dump graph structures as well you need to dump system collections as well:
```
--include-system-collections true
```

**Comment by Simran-B** [comment]
@jdgamsterdam Did dothebart's suggestion solve the problem for you?

**Comment by jdgamsterdam** [comment]
Yes. That was the issue.  Works great.  You need to have the same flag in ArangoRestore as well.  The only thing it does not seem to dump (that I can see) are Queries that you create on the site.  The interface for running and analyzing the queries is great.  The interface for saving and updating them (online) is a bit weird sometimes.  I make it a point to save all queries off-line.

**Comment by Simran-B** [comment]
Saved queries are stored in the _users collection, which is handled differently than any other collection. This is mainly because restoring a dump should normally not overwrite the user accounts and their permissions. I think what you see is a side-effect of that. Feel free to open a separate issue for that, maybe also with a suggestion how the UI could be improved.
