### ISSUE TITLE
Homebrew install not working Mac OS X 10.10.5

### ISSUE THREAD

**Issue by asmaloney** [arangodb/arangodb#1735]
Trying to install latest arangodb (2.8.2) via homebrew.

```
$ brew install arangodb
Error: arangodb cannot be built with any available compilers.
To install this formula, you may need to:
  brew install gcc
```

My gcc/llvm/clang is the latest provided by Apple.

```
$ which gcc
/usr/bin/gcc

$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

**Comment by baslr** [comment]
also #1730

**Comment by baslr** [comment]
I compile ArangoDB with
```
git clone https://github.com/arangodb/arangodb arangodb-build
cd arangodb-build
git checkout v2.8.2
make distclean
make setup
./configure --with-openssl-inc=/opt/local/include/ --with-openssl-lib=/opt/local/
make V=1 -j 8

/arangodb-build/bin/arangod --version
architecture: 64bit
build-date: 2016-02-15 03:38:35
configure:  './configure' '--with-openssl-inc=/opt/local/include/' '--with-openssl-lib=/opt/local/lib/'
fd-client-event-handler: poll
fd-setsize: 1024
icu-version: 54.1
libev-version: 4.11
maintainer-mode: false
openssl-version: OpenSSL 1.0.2f  28 Jan 2016
repository-version: tags/v2.8.2-0-g82a9f56163d6009c3e873725e26a97f31917e3cf
server-version: 2.8.2
sizeof int: 4
sizeof void*: 8
tcmalloc: false
v8-version: 4.3.61

gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.4.0
Thread model: posix
```

@asmaloney can you run `brew install -v arangodb`

**Comment by asmaloney** [comment]
Gives me the same thing:

```
$ brew install -v arangodb
Error: arangodb cannot be built with any available compilers.
To install this formula, you may need to:
  brew install gcc
```

**Comment by baslr** [comment]
and `brew install gcc` doesn't fix it?

**Comment by asmaloney** [comment]
I'm not prepared to install another compiler just for this.  It should compile with the standard Apple-provided compiler.

**Comment by neunhoef** [comment]
Unfortunately, we found out that the compiler/libs combination Apple ships with the latest Xcode on El Capitano is basically unusable. Performance of ArangoDB in many situations goes down by a factor of 7 or so. Therefore we have put in the error in that case. ArangoDB builds fine, but is horribly slow with the Apple compiler. I hope this explains our reasoning.

**Comment by asmaloney** [comment]
I'm not running El Capitan.  I'm on 10.10.5.  Is it the same compiler?

For my use-case I don't really care about the speed.  I need it to develop and test in very early stages of development - tens of documents.  Can't you just make it a big warning in homebrew that it's slow and let me use it anyways?

**Comment by baslr** [comment]
Its the same version. `Apple LLVM version 7.0.2 (clang-700.1.81)` for 10.10 and 10.11.

**Comment by asmaloney** [comment]
It doesn't work on my laptop (Mac OS X 10.9.5) either.

```
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
```

I've never run into software that refuses to compile on Mac OS X with the default compilers.  I guess I'll have to rethink my plans.

**Comment by kvahed** [comment]
@asmaloney have you been able to solve the problem for yourself yet? We can certainly guide you through the build process. It's kind of odd though. This should really work out of the box.

**Comment by kvahed** [comment]
Oops. Synchronicity.

**Comment by kvahed** [comment]
You will be able to compile with that compiler. We use a couple of Macs. Let's go about this a little more verbosely. Are you trying homebrew on the second machine too?

**Comment by asmaloney** [comment]
Yes I am.  I want to use homebrew for simplicity's sake.  I could figure out how to do it all "by hand", but I'd rather not.  Like everyone else I have 1001 other things to manage :-)

**Comment by kvahed** [comment]
Let me get back to you. Any thing I should know trying to reproduce what you've tried?

**Comment by asmaloney** [comment]
I just tried my 10.10 machine and it compiled 2.8.1 using homebrew.  Looks like the 2.8.2 homebrew formula was reverted by Mike McQuaid earlier today.

Looking at the current formula though I see this:

```
fails_with :clang do
    build 600
    cause "Fails with compile errors"
  end
```

I would expect to see that message when I try to install it, but I don't.

I also see SHAs listed in the `bottle` section, so maybe I can just install the binaries?

Thanks!

**Comment by kvahed** [comment]
So I just ran through the complete homebrew and arangodb installation. It's not gonna be particularly helpful to you though. It just ran through like a treat:
`kvahed@kvmbp ~> /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/Library/...
/usr/local/share/man/man1/brew.1
==> The following directories will be made group writable:
/usr/local/.
/usr/local/bin
==> The following directories will have their owner set to kvahed:
/usr/local/.
/usr/local/bin
==> The following directories will have their group set to admin:
/usr/local/.
/usr/local/bin

Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /bin/chmod g+rwx /usr/local/. /usr/local/bin
Password:
==> /usr/bin/sudo /usr/sbin/chown kvahed /usr/local/. /usr/local/bin
==> /usr/bin/sudo /usr/bin/chgrp admin /usr/local/. /usr/local/bin
==> /usr/bin/sudo /bin/mkdir /Library/Caches/Homebrew
==> /usr/bin/sudo /bin/chmod g+rwx /Library/Caches/Homebrew
==> /usr/bin/sudo /usr/sbin/chown kvahed /Library/Caches/Homebrew
==> Downloading and installing Homebrew...
remote: Counting objects: 4025, done.
remote: Compressing objects: 100% (3871/3871), done.
remote: Total 4025 (delta 35), reused 2110 (delta 23), pack-reused 0
Receiving objects: 100% (4025/4025), 3.31 MiB | 1.80 MiB/s, done.
Resolving deltas: 100% (35/35), done.
From https://github.com/Homebrew/homebrew
 * [new branch]      master     -> origin/master
HEAD is now at a551330 roundup: add 0.0.5 bottle.
==> Installation successful!
==> Next steps
Run `brew help` to get started
kvahed@kvmbp ~> brew install arangodb
==> Installing dependencies for arangodb: openssl
==> Installing arangodb dependency: openssl
==> Downloading https://homebrew.bintray.com/bottles/openssl-1.0.2f.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring openssl-1.0.2f.el_capitan.bottle.tar.gz
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl/certs

and run
  /usr/local/opt/openssl/bin/c_rehash

This formula is keg-only, which means it was not symlinked into /usr/local.

Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include

==> Summary
🍺  /usr/local/Cellar/openssl/1.0.2f: 466 files, 11.9M
==> Installing arangodb
==> Downloading https://homebrew.bintray.com/bottles/arangodb-2.8.1.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring arangodb-2.8.1.el_capitan.bottle.tar.gz
==> /usr/local/Cellar/arangodb/2.8.1/sbin/arangod --upgrade --log.file -
==> Caveats
To have launchd start arangodb at login:
  ln -sfv /usr/local/opt/arangodb/*.plist ~/Library/LaunchAgents
Then to load arangodb now:
  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.arangodb.plist
Or, if you don't want/need launchctl, you can just run:
  /usr/local/opt/arangodb/sbin/arangod --log.file -
==> Summary
🍺  /usr/local/Cellar/arangodb/2.8.1: 3,350 files, 156.4M
kvahed@kvmbp ~> /usr/local/sbin/arango
arango-dfdb  arangod      
kvahed@kvmbp ~> /usr/local/sbin/arangod 
2016-02-15T20:16:50Z [60243] INFO file-descriptors (nofiles) new hard limit is -1, new soft limit is 1024
2016-02-15T20:16:50Z [60243] INFO ArangoDB 2.8.1 [darwin] 64bit, using ICU 54.1, V8 4.3.61, OpenSSL 1.0.2f  28 Jan 2016
2016-02-15T20:16:50Z [60243] INFO using default language 'en'
2016-02-15T20:16:50Z [60243] INFO loaded database '_system' from '/usr/local/var/lib/arangodb/databases/database-95063'
2016-02-15T20:16:50Z [60243] INFO running WAL recovery (1 logfiles)
2016-02-15T20:16:50Z [60243] INFO replaying WAL logfile '/usr/local/var/lib/arangodb/journals/logfile-160599.db' (1 of 1)
2016-02-15T20:16:51Z [60243] INFO WAL recovery finished successfully
2016-02-15T20:16:51Z [60243] INFO using endpoint 'tcp://127.0.0.1:8529' for non-encrypted requests
2016-02-15T20:16:51Z [60243] INFO using default API compatibility: 20800
2016-02-15T20:16:51Z [60243] INFO JavaScript using startup '/usr/local/Cellar/arangodb/2.8.1/share/arangodb/js', application '/usr/local/var/lib/arangodb-apps'
2016-02-15T20:16:52Z [60243] INFO In database '_system': Database is up-to-date (20801/prod/standalone/existing)
2016-02-15T20:16:55Z [60243] INFO Please note that a new bugfix version '2.8.2' is available
2016-02-15T20:16:55Z [60243] INFO file-descriptors (nofiles) hard limit is -1, soft limit is 1024
2016-02-15T20:16:55Z [60243] INFO Authentication is turned off
2016-02-15T20:16:55Z [60243] INFO ArangoDB (version 2.8.1 [darwin]) is ready for business. Have fun!
^C2016-02-15T20:17:02Z [60243] INFO control-c received, beginning shut down sequence
2016-02-15T20:17:06Z [60243] INFO ArangoDB has been shut down
kvahed@kvmbp ~> 
`

**Comment by asmaloney** [comment]
OK - so that's 2.8.1 on 10.11?  Since the 2.8.2 formula was reverted I would expect that to work.  (I don't see what compiler is being used though.)

**Comment by asmaloney** [comment]
Another piece of the puzzle.  My setup will not use the binary "bottles" and will always compile from source because my homebrew is not in the standard location.

```
If available, bottled binaries will be used by default except under the following conditions:
   ...
   • Homebrew is installed to a prefix other than the standard /usr/local (although some bottles support this)
```

It looks like, from what you posted above, homebrew installed the binary from the bottle and did not build it anyways.  You would have to use the `--build-from-source` option.

**Comment by dothebart** [comment]
we refuse to compile with CLANG due to #1692 - apple broke their compilers. We still have to investigate for the in detail cause for this, but since there are working compilers available, we switched to that.

**Comment by asmaloney** [comment]
:+1: Thank you whoever modified the homebrew formula!  It now allows the use of Apple's clang compiler and gives a reasonable warning to the user.
