### ISSUE TITLE
Query freezes when using the new AQL traversals

### ISSUE THREAD

**Issue by solher** [arangodb/arangodb#1737]
I'm experiencing a pretty big issue here.

Basically, I have a graph of entities linked by entityRights, and I want to get all the entities on which the current user has read permissions.

Before the new traversal system, I used that AQL query:
```
FOR e IN REMOVE_NTH(TRAVERSAL(entities, entityRights, @userID, 'outbound', {followEdges: [{'read': true}]}), 0)
FILTER e.vertex._id == 'entities/role5'
RETURN DISTINCT e.vertex
```

Then, I migrated it to the new traversals and got (which is much cleaner):
```
FOR v, e IN 1..10 OUTBOUND @userID entityRights
FILTER e.read == true
FILTER v._id == 'entities/role5'
RETURN DISTINCT v
```

90% of the time, everything works fine. But sometimes, the last one hangs and completely freezes the database. I can see it in the query manager, it never ends.
When it freezes, I have to kill -9 the DB and if I relaunch it and try again the exact same query, it works perfectly.
I wrote a script to run concurrently multiple of these queries to see if I can get the issue again (that's what my app does when it happens) but it never happens.
So, it seems to me that the problem might appears when some writes are done at the same time these queries run (that's what my app does when it happens).

I had to roll back all my AQL traversals migrations to the old queries to be sure there would not be problems anymore. Everything is fine again.

Are there any precautions to take when using the new traversals ?

Thank you

**Comment by mchacki** [comment]
Hi @solher,

i try to reproduce your situation and need some more information please:
1) Which version of ArangoDB are you using?
2) could you give me an example of the modification query that runs in parallel to the AQL traversal?
3) Are there any collections other than `entities` connected with edges in `entityRights`? If so, how many?
4) If 3) is not `NO` from which collection is the `@userID`?

best
Michael

**Comment by solher** [comment]
1) I tried with 2.8.0, 2.8.1 and 2.8.2.
2) I tried to remove the more queries I could to isolate the issue and it seems to occur when I run:
```json
   {
      "collections": {
        "read": [],
        "write": [
          "entities",
          "entityRights"
        ]
      },
      "action": "function() {
        var db = require('internal').db;
        var userID = 'users/admin';
        var entities = db._query(aqlQuery `LET removed = ( FOR e IN entities FILTER e._key IN ['usradminorg1'] FOR r IN entityRights FILTER r.ownedBy == ${userID} \u0026\u0026 r._to == e._id \u0026\u0026 r.read == true REMOVE r IN entityRights RETURN DISTINCT e ) FOR e IN removed REMOVE e IN entities RETURN OLD`).toArray();
        db._query(aqlQuery `FOR e IN entities FILTER e._key IN ['usradminorg1'] FOR r IN entityRights FILTER r.grantedTo == ${userID} \u0026\u0026 r._to == e._id \u0026\u0026 r.read == true REMOVE r IN entityRights RETURN OLD`).toArray();
        return entities;
    }"
    }
}
```

Then concurrently:

```json
    {
      "query": "FOR v, e IN 1..3 OUTBOUND @userID entityRights FILTER e.read == true FILTER v._id == 'entities/E2lGteam2' RETURN DISTINCT v",
      "bindVars": {
        "userID": "users/admin"
      }
    }
```
```json
    {
      "query": "FOR v, e IN 1..3 OUTBOUND @userID entityRights FILTER e.read == true FILTER v._id == 'entities/R2AHteam1' RETURN DISTINCT v",
      "bindVars": {
        "userID": "users/admin"
      }
    }
```
```json
    {
      "collections": {
        "read": [],
        "write": [
          "entities",
          "entityRights"
        ]
      },
      "action": "function() {
        var db = require('internal').db;
        var now = '2016-02-16T20:26:48.90364563Z';
        var entityID = 'entities/E2lGteam2';
        var userID = 'users/admin';
        var newEntities = [{
            '_key': 'iJwWrole2',
            'type': 'entityTypes/400'
        }];
        var entities = db._query(aqlQuery `FOR a IN ${newEntities} UPSERT { '_key': a._key } INSERT a UPDATE a IN entities RETURN NEW`).toArray();
        db._query(aqlQuery `FOR a IN ${entities} INSERT { 'created': ${now}, 'lastUpdated': ${now}, '_from': ${entityID}, '_to': a._id, 'ownedBy': ${userID}, 'read': true, 'write': true } IN entityRights`).toArray();
        return entities;
    }"
    }
```
```json
    {
      "collections": {
        "read": [],
        "write": [
          "entities",
          "entityRights"
        ]
      },
      "action": "function() {
        var db = require('internal').db;
        var now = '2016-02-16T20:26:48.909444152Z';
        var entityID = 'entities/R2AHteam1';
        var userID = 'users/admin';
        var newEntities = [{
            '_key': '6wmhrole1',
            'type': 'entityTypes/400'
        }];
        var entities = db._query(aqlQuery `FOR a IN ${newEntities} UPSERT { '_key': a._key } INSERT a UPDATE a IN entities RETURN NEW`).toArray();
        db._query(aqlQuery `FOR a IN ${entities} INSERT { 'created': ${now}, 'lastUpdated': ${now}, '_from': ${entityID}, '_to': a._id, 'ownedBy': ${userID}, 'read': true, 'write': true } IN entityRights`).toArray();
        return entities;
    }"
    }
```

3) Yes, `entityRights` can be connected with `entities` and `users`.
4) Exactly. In fact I remove the current user from the result and keep the rest.

**Comment by solher** [comment]
Oh and something new occured: after a 16 minutes hang, I got a "lock timeout" error.

**Comment by solher** [comment]
BTW, I just found out about the `min depth` option of the `TRAVERSAL` function. Will be much better :)

**Comment by solher** [comment]
BTW, I just found out about the `minDepth` option of the `TRAVERSAL` function. Will be much better :)

**Comment by mchacki** [comment]
Hi thank you very much for the detailed information, this will help me debug it.

The "lock timeout" error is actually intended if you get into a dead-lock situation to recover the system.

**Comment by mchacki** [comment]
Short update: I managed to reproduce the deadlock situation on my machine.
Now we track it down!

**Comment by mchacki** [comment]
Could you try this again with the newest version of 2.8 (2.8.4) ?
We have fixed a potential deadlock in this area. On my machine i did not run into this situation any more.

**Comment by solher** [comment]
It seems to be fixed ! Thanks a lot :+1: 
And by the way, you didn't lie about the new traversal API in Barcelona, it is truly very good ! ;)

**Comment by mchacki** [comment]
Thanks for the feedback ;)
Glad you like it.

**Comment by solher** [comment]
Ok I had to rollback to the old traversal API again because it seems that, even if there is no deadlock anymore, the perfs under heavy loads seems very bad with the new one.
I've got some queries taking almost 5 minutes to complete when I have no problems with the old one (20 seconds max).

Do you see any reasons why it would do that or should I investigate more ?

**Comment by solher** [comment]
In fact, I think it has nothing to do with it.
I don't know why but suddently, certain transactions are just really slow.
