### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by specimen151** [arangodb/arangodb#1738]
Several times now, I get a message that Arango Server has crashed. The crash has happened when I'm away, and is the first thing I see when I log on to the PC. Since this is on my developer machine, there should not have been any activity.

Unfortunately, I don't have much information.
`Unhandled exception at 0x0000000076ED3072 (ntdll.dll) in arangod.exe: 0xC0000005: Access violation reading location 0x000000004AB70028.`

It never happened on 2.7. I'm running 2.8.2. 
Setup is Windows 7 Ultimate SP1, 8GB, 64bit, via remote desktop. Small data size.

**Comment by dothebart** [comment]
Hi, We're currently investigating on this. It seems to happen during the garbage collection in V8. 
If you can obtain [crashdumps using procdump](https://github.com/arangodb/arangodb/blob/devel/README_maintainers.md#coredump-generation) this could be usefull.

**Comment by specimen151** [comment]
I'll try that the next time it happens, and send it to you.

**Comment by dothebart** [comment]
procdump needs to be running in advance of the crash monitoring that special process. Its not as easy in general *nix'es where you simply turn on core dumps and are set...

**Comment by specimen151** [comment]
Monitoring now, expect to have something tomorrow. In the meantime, procdump is already reporting:

    [14:36:44] Exception: E06D7363.?AVException@basics@triagens@@

But the process is still running. Getting this every time I refresh my page (webpage).

**Comment by dothebart** [comment]
yes, these are general exceptions that are used in the the program flow. As long as they're caught, everything is fine ;-)

**Comment by specimen151** [comment]
I haven't had any crashes yet - could be that the procdump is making it work, but if/when it crashes I'll be sure to upload the crashdump.

**Comment by dothebart** [comment]
procdump attaches itself as a debugger to the process. So it could for shure alter runtime behaviour. 
Did you upgrade to 2.8.3 already?

**Comment by specimen151** [comment]
No I haven't upgraded yet.

It's a little cumbersome because it installs in a new location every time
(based on the version number) and thus I must recreate shortcuts etc.
having such a frequent upgrade cycle, this could have been more streamlined
(at least within the same major x.y version).

tor. 25. feb. 2016 kl. 15.54 skrev Wilfried Goesgens <
notifications@github.com>:

**Comment by dothebart** [comment]
since most of us are only experienced in operating large scale *nix environments with deployments etc (LHFS makes it realy easy ;-) . We are keen on feedback on our windows installer. How should it behave? where should it put/expect files?

**Comment by specimen151** [comment]
Still no crash w. debugger attached. Just to update.

**Comment by dothebart** [comment]
for 2.8.5 we fixed another possible incident which may occur. It would be good if you can look out at the windows eventlog for messages saying: 'out-of-memory' which is what this fix should do in some cases.

In general, should we close this issue now?

**Comment by specimen151** [comment]
I agree we close it. Haven't experienced the crash for some time, and will
not report it again until I try with the newest version.
man. 14. mar. 2016 kl. 22.39 skrev Wilfried Goesgens <
notifications@github.com>:

> for 2.8.5 we fixed another possible incident which may occur. It would be
> good if you can look out at the windows eventlog for messages saying:
> 'out-of-memory' which is what this fix should do in some cases.
>
> In general, should we close this issue now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arangodb/arangodb/issues/1738#issuecomment-196532027>.
>
-- 
Mvh
Jens Petter Abrahamsen
