### ISSUE TITLE
Query continues running after client disconnects

### ISSUE THREAD

**Issue by shift-evgeny** [arangodb/arangodb#1741]
Same set-up and query as for #1740. After the client application times out or is killed the query on the server continues running, seemingly forever (at least for over an hour). It can be seen in the web interface on the Query Management page ("FOR doc IN @@collection RETURN doc").

The server should kill a query that does not modify data when the client has disconnects, since the results will never be read. Or perhaps it should kill it if the client does not read any results for some time.

The current behaviour means it's very easy to use up the server's RAM by trying a few "heavy" queries and cancelling them (from the user's point of view). In my case the server used over 12 GB RAM for a database that only took 2.7 GB on disk and this RAM usage was slowly increasing.

**Comment by shift-evgeny** [comment]
Additionally, even when I try to kill the query from the web UI, this takes a while (the server uses a lot of during that time) and there is no feedback to the user. Reloading the page shows that the query is still running, so it appears that the kill request didn't work. It's only by monitoring the server's CPU usage that I can guess that something is happening. The query should be killed quickly. If this is not possible, there should be some feedback to the user to indicate that it's in the process of being killed.

**Comment by dothebart** [comment]
Queries currently can only abort when they reach cancelation points so they terminate themselves cooperatively. If you machine already starts swapping or runs in tight loops inbetween those cancelation points, it will take a while until the query can abort excecution.

RAM usage may increase if a huge result set has to be prepared. The most common user error, to create unexpectedly large result sets, is to do a [join](https://docs.arangodb.com/AqlExamples/Join.html) using a non existant attribute. The result will then contain each pair possible from both sides of the join.

**Comment by shift-evgeny** [comment]
I'm not sure exactly what a "cancellation point" is - it's mentioned in the docs, but I can't find an explanation. Anyway, the primary issue that (as far as I understand) a query doesn't abort automatically when the client has disconnected, which can happen very easily. The secondary (less important) issue is that when cancelling from the UI it appears like the "kill" button didn't actually do anything.

The memory usage is probably a third issue. In this case it was a simple select of all documents from one collection, no joins, so I don't know why it would take that much. In fact, if I try the same query again (without killing the first one) arangod.exe private bytes goes over 24 GB!

**Comment by dothebart** [comment]
As noted in #1740 - the result has to be built up in server RAM.

The memory usage will improve with ArangoDB 3.0, but the result still has to be built up.

Future versions may be able not to build up the whole result in ram, but we don't have an ETA on this yet.

**Comment by shift-evgeny** [comment]
OK, that answers my question from #1740, thanks.

To be clear, this issue is not about memory usage, it's about cancelling the query.

**Comment by dothebart** [comment]
For ArangoDB we are currently working on introducing a better way to administrate, visualize & cancel queries.

**Comment by razvanphp** [comment]
+1 for this.

There is the case when I write a stupid query let's say, server stops responding because it's a modification query, and I can't kill it because arangosh is not responding, nor the webinterface, so I don't know the query id to kill. Please take this into consideration too.

**Comment by fceller** [comment]
Queries can now be canceled in the Front-End
