### ISSUE TITLE
Proprietary license files

### ISSUE THREAD

**Issue by johan-rodriguez** [arangodb/arangodb#17435]
My question is related to licensing. 

Most of the repository is under Apache-2.0 open source license, however, the files below has a proprietary license.

../utils/generateExamples.py
../tests/js/common/aql/aql-arangosearch-offset-info-community.js
../tests/IResearch/IResearchFilterMinHashMatchTest.cpp
../tests/IResearch/IResearchFilterNestedTest.cpp
../arangod/IResearch/IResearchDataStoreMeta.h

Is this expected? Can they be modified to be Apache-2.0 also or Do I need to get a proprietary license instead in order to use the DB?

**Comment by jsteemann** [comment]
@johan-rodriguez : I guess that the bottommost 4 of the 5 files you listed can be offered under an Apache 2.0 license. From my understanding, the wrong license header text has been used for these. But it has to be confirmed with colleagues first. I will ping them in our Slack to sort it out.
Cannot say much about the Python file yet, but would think it could be relicensed.

**Comment by jsteemann** [comment]
Fixed via https://github.com/arangodb/arangodb/pull/17437.

**Comment by johan-rodriguez** [comment]
Thank you guys
