### ISSUE TITLE
GEO_CONTAINS behaves differently with less precision

### ISSUE THREAD

**Issue by genert** [arangodb/arangodb#17485]
## My Environment

* __ArangoDB Version__:        3.10.0
* __Deployment Mode__:       Single Server 
* __Deployment Strategy__:   Docker
* __Configuration__:               
* __Infrastructure__:              On-premise
* __Operating System__:       MacOS 13.0
* __Total RAM in your machine__:      64GB (MacBook Pro 16" Apple M1 Max)
* __Disks in use__:        SSD
* __Used Package__:    Docker

## Component, Query & Data

__Affected feature__:

[**GEO_CONTAINS** AQL function](https://www.arangodb.com/docs/stable/aql/functions-geo.html#geo_contains)

__AQL query (if applicable)__:
```
WITH events
FOR e IN events
    FILTER GEO_CONTAINS( {
        "type": "Polygon",
        "coordinates": [
          [
            [
              24.743952,
              59.436789
            ],
            [
              24.743952,
              59.441999
            ],
            [
              24.754449,
              59.441999
            ],
            [
              24.754449,
              59.436789
            ],
            [
              24.743952,
              59.436789
            ]
          ]
        ]
      }, e.location)
    RETURN e.location

```
__AQL explain and/or profile (if applicable)__:

__Dataset__:

**events** collection with the following data:

```
{
  "title": "test event with location",
  "location": {
    "type": "Point",
    "coordinates": [
      24.750137329101562,
      59.43931579589844
    ],
    "properties": {
      "zoom": 11
    }
  },
}
```

## Steps to reproduce

Query the event with the following precision:
```
WITH events
FOR e IN events
    FILTER GEO_CONTAINS( {
        "type": "Polygon",
        "coordinates": [
          [
            [
              24.74389969390228,
              59.441914343792746
            ],
            [
              24.74389969390228,
              59.43699338551801
            ],
            [
              24.754407217831385,
              59.43699338551801
            ],
            [
              24.754407217831385,
              59.441914343792746
            ],
            [
              24.74389969390228,
              59.441914343792746
            ]
          ]
        ]
      }, e.location)
    RETURN e.location
  ```
The event is found, now let's query with less precision even though the polygon is almost identical:
```
WITH events
FOR e IN events
    FILTER GEO_CONTAINS( {
        "type": "Polygon",
        "coordinates": [
          [
            [
              24.743952,
              59.436789
            ],
            [
              24.743952,
              59.441999
            ],
            [
              24.754449,
              59.441999
            ],
            [
              24.754449,
              59.436789
            ],
            [
              24.743952,
              59.436789
            ]
          ]
        ]
      }, e.location)
    RETURN e.location
```
The event is not found.

__Problem__:

GEO_CONTAINS behaves differently with less precision even though Polygons are the same.

__Expected result__:

GEO_CONTAINS must behave the same regardless of lesser precision.

--

<img width="1476" alt="Screenshot 2022-11-02 at 11 29 24" src="https://user-images.githubusercontent.com/1218788/199457648-be0e6b44-06d4-4821-88a7-bd4c19225731.png">

Here are the polygon boxes used in queries.
https://geojson.io/#map=14.72/59.43777/24.74688
```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "coordinates": [
          [
            [
              24.74389969390228,
              59.441914343792746
            ],
            [
              24.74389969390228,
              59.43699338551801
            ],
            [
              24.754407217831385,
              59.43699338551801
            ],
            [
              24.754407217831385,
              59.441914343792746
            ],
            [
              24.74389969390228,
              59.441914343792746
            ]
          ]
        ],
        "type": "Polygon"
      }
    },
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              24.743952,
              59.436789
            ],
            [
              24.743952,
              59.441999
            ],
            [
              24.754449,
              59.441999
            ],
            [
              24.754449,
              59.436789
            ],
            [
              24.743952,
              59.436789
            ]
          ]
        ]
      }
    }
  ]
}
```

**Comment by klaytaybai** [comment]
It doesn’t seem like the issue is necessarily due to using less precision in the polygon.  Taking digits off the original coordinates still works.  I was able to reproduce the issue with the second polygon.  This is a big concern for me too.

**Comment by Simran-B** [comment]
The interpretation of polygons changed regarding the winding but lines are also geodesic now, which can change results.
See https://www.arangodb.com/docs/stable/indexing-geo.html#geojson-interpretation for details.

Starting from v3.10.10, the web interface correctly displays polygons with geodesic lines. However, it only displays the polygon lines and doesn't fill the area the polygon covers currently, so you cannot see what is interior and exterior.
