### ISSUE TITLE
Arangosearch view is not updated atomically after an arangodb document update or transaction

### ISSUE THREAD

**Issue by sfialok31** [arangodb/arangodb#17482]
## My Environment

* __ArangoDB Version__:        3.9.0
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               --rocksdb.write-buffer-size=268435456 --rocksdb.level0-stop-trigger=1024 --javascript.v8-contexts=12 --javascript.v8-contexts-minimum=4 --rocksdb.max-write-buffer-number=4 --rocksdb.total-write-buffer-size=0 --cache.size 500111222 --rocksdb.block-cache-size 500111222 --rocksdb.enforce-block-cache-size-limit true
* __Infrastructure__:               own
* __Operating System__:        MacOS 11.6
* __Total RAM in your machine__:        32GB

## Component, Query & Data
ArangoSearch

__Affected feature__:
ArangoSearch

__Problem__:

I am updating a document in a collection on which I have created an arangosearch view.
In a separate program, I am repeatedly checking the presence of that document in the arangosearch view with an arango SEARCH query (every 200ms, I fire that query).
I notice that, momentarily after the update, the document is not found (even though it should be because I am updating a separate field in the document that should not effect the SEARCH query).
And the next moment after that (after another 200ms), the document reappears.

It looks like arangodb is processing update as a "remove + insert" and that these two operations do not seem to be atomic in terms of when they become visible to search queries.

Is this the expected behaviour or is this a bug?

The documentation mentions that the arangosearch view is eventually consistent, and in the "Views Reference", it also mentions that "Once a 'commit' operation is complete (for arangosearch views) all documents added/removed prior to the start of the 'commit' operation will be reflected by queries invoked in subsequent ArangoDB transactions".

So, it looks like the effect of an update (or an arangodb transaction as a whole), would become visible in arango search queries eventually and atomically. Am I understanding it correctly?

Thanks.

**Comment by sfialok8** [comment]
Could someone please take a look at this?
Thank you.

**Comment by sfialok31** [comment]
Could someone please take a look at this?
Thank you.

**Comment by MBkkt** [comment]
Known issue it fixed in 3.9.5 for views without primary sort
For views with primary sort, we also have fix, but it will be available only for devel, 3.10, 3.10.2, 3.9.6

**Comment by trieder83** [comment]
We are currently on 3.9.9 suffer badly on this issue!
Is this bug still open or solved with 3.11?  (did not find any note on the release notes)

**Comment by MBkkt** [comment]
Yep, it fixed for 3.11

**Comment by dothebart** [comment]
The fix to this issue was part of a larger change set hence it won't appear in 3.9 & 3.10 backports. 
Please upgrade to 3.11 for the fix.
Closing this as fixed.
