### ISSUE TITLE
Slow Query API should provide bind parameters, webui should display them

### ISSUE THREAD

**Issue by hkernbach** [arangodb/arangodb#1751]
Slow Query API should return the bind parameters. Also the frontend has to implement those changes then. 

via #1732

**Comment by dothebart** [comment]
@hkernbach the backend now can do this. Functionality should be added to webinterface too.

**Comment by hkernbach** [comment]
Implemented in PR: https://github.com/arangodb/arangodb/pull/2975

**Comment by jsteemann** [comment]
3.2.1 adds bind parameters to the list of slow & currently running AQL queries, and also to the web interface.

**Comment by jsteemann** [comment]
3.2.1 has been released and is [available for download](https://www.arangodb.com/download-major/).
