### ISSUE TITLE
@types/arangodb doesn't support `db._create(name, {keyOptions: {type: "padded"}})` 

### ISSUE THREAD

**Issue by strazto** [arangodb/arangodb#17524]
## My Environment

* __ArangoDB Version__:        3.9.4
* __@types/arangodb version: `"@types/arangodb": "^3.5.13",`

## Component, Query & Data

__Affected feature__:
This is actually an issue with definitively typed's typings but I'm unsure if that's where I should raise it.

Essentially, trying to run `db._create("colname", {keyOptions: {type: "padded"}})` will give you a typeerror in vscode.

I think that the typings are just fairly out of date

## Steps to reproduce

```ts
import { db } from '@arangodb'

// ...

db._create("collection_1",  {keyOptions: {type: "padded"}});

```
__Problem__:

The vscode message may be found below:

```json
[{
	"owner": "typescript",
	"code": "2322",
	"severity": 8,
	"message": "Type '\"padded\"' is not assignable to type 'KeyGeneratorType'.",
	"source": "ts",
	"relatedInformation": [
		{
			"startLineNumber": 473,
			"startColumn": 13,
			"endLineNumber": 473,
			"endColumn": 17,
			"message": "The expected type comes from property 'type' which is declared here on type '{ type?: KeyGeneratorType; allowUserKeys?: boolean; increment?: number; offset?: number; }'",
			"resource": ".../node_modules/@types/arangodb/index.d.ts"
		}
	]
}]
```

```
The expected type comes from property 'type' which is declared here on type '{ type?: KeyGeneratorType; allowUserKeys?: boolean; increment?: number; offset?: number; }'
```

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/arangodb/index.d.ts#L94

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3750e4f3adb22e64fa2d59042b1b9bcf5cbe9a59/types/arangodb/index.d.ts#L472-L473

__Expected result__:

From https://www.arangodb.com/docs/3.9/data-modeling-collections-database-methods.html#create :

> type: specifies the type of the key generator. The currently available generators are traditional, autoincrement, uuid and padded. 

Any of the literals should be accepted

**Comment by Simran-B** [comment]
The typings are not officially maintained by ArangoDB, but thank you for opening a PR on DefinitelyTyped to add the missing key generator types. I'll also ping @pluma on Slack so that he can take a look.
