### ISSUE TITLE
Swagger UI document-handle not working

### ISSUE THREAD

**Issue by rossmills99** [arangodb/arangodb#1752]
When I use the "try it out" feature from the Swagger UI page, any API requests involving document-handle as a route parameter seem to fail.

When I try the same requests from CURL or another tool, they work fine.

When I look at the feedback in the Swagger UI, I see the request URL reported as e.g.:

http://localhost:8529/_api/document/MyDocuments%2F239208769827

Notice the slash "/" has been URL encoded.  Is it possible this has anything to do with the problem?

I found a possibly related old issue but it is so old I figured it would be worth creating a new one: https://github.com/arangodb/arangodb/issues/1077

**Comment by dothebart** [comment]
can you sniff and revalidate whether its still that one? #1077 is still not fixed.

**Comment by hkernbach** [comment]
GET is working. POST is the problem:

swagger is building the post param to: 
http://localhost:8529/_api/document/bla%2Fbla

instead of:
http://localhost:8529/_api/document/bla/bla

**Comment by pluma** [comment]
Fixed via 23893ec.
