### ISSUE TITLE
Arangojs and data mod. query bug

### ISSUE THREAD

**Issue by roman1720** [arangodb/arangodb#1754]
Hi, I'm hitting some strange bug with arangojs and data modification update query (arango 2.8.1, arangojs 4.3.0, debian 8). I have vTask collection with hundreds of documents. One affected document is this one:

Document before update:
{"attemptCount":0,"hostname":"","mac":"","status":"run","ip":"172.22.30.1"}

Now in node.js I run following query (db.query method):

FOR task IN vTask
FILTER task.ip in ["172.22.30.1"]
UPDATE task WITH {"status": "error", "status2": "foo", "hostname": "bar"} IN vTask

and the document after query:

{"attemptCount":0,"hostname":"bar","mac":"","status":"run","status2":"foo","ip":"172.22.30.1"}

As you can see status is not changed! New property is added (status2) and another existing property is modified (hostname).

When I break my code just before the update query, and manually run query on web, then status to error is correctly updated.

When I modify query (== instead of IN, in my js code, just for this one document)

FOR task IN vTask
FILTER task.ip == "172.22.30.1"
UPDATE task WITH {"status": "error", "status2": "foo", "hostname": "bar"} IN vTask

then result is correct and status is updated:

{"attemptCount":0,"hostname":"bar","mac":"","status":"error","status2":"foo","ip":"172.22.30.1"}

For other documents with another IP address, update works correctly (IN operator), either having single or multiple IP in array, example:

FOR task IN vTask
FILTER task.ip in ["10.154.254.1"]
UPDATE task WITH {"status": "error", "status2": "foo", "hostname": "bar"} IN vTask

result

{"attemptCount":0,"hostname":"bar","mac":"","status":"error","status2":"foo","ip":"10.154.254.1"}

or 

FOR task IN vTask
FILTER task.ip in ["10.154.255.49", "10.154.49.49", "10.154.149.49", "10.154.255.49"]
UPDATE task WITH {"status": "ok", "status2": "foo", "hostname": "bar"} IN vTask

{"attemptCount":0,"hostname":"bar","mac":"","status":"ok","status2":"foo","ip":"10.154.255.49"}

I'm starting always with all truncated collections, and for IP 172.22.30.1 it happens always. So I have it now reproducible in my lab. Unfortunately, I tried to create simple reproducible example for you with no luck. 

I tried to drop all indexes also, but it didn't help.

Any ideas what can cause this? Or how to troubleshoot it?

Thanks

Roman

**Comment by dothebart** [comment]
hm, that sounds misterious.
Does this only happen if you filter only for a single ip? 

Does it also happen, if you use bind values like this:

    db._query('FOR task IN vTask FILTER task.ip in @iprange UPDATE task WITH {"status": "error", "status2": "foo", "hostname": "bar"} IN vTask', {iprange: ["172.22.30.1"])

If you `RETURN` the updated document, does it also show the incorrectly modified document:

    db._query('FOR task IN vTask FILTER task.ip in @iprange UPDATE task WITH {"status": "error", "status2": "foo", "hostname": "bar"} IN vTask RETURN NEW', {iprange: ["172.22.30.1"]})

Can you sniff the database connection for further analysis?

**Comment by roman1720** [comment]
It makes me crazy :) 

Does this only happen if you filter only for a single ip?
It happens for more documents, but whole running time for my app is around 30 minuts. This particular IP occurs at the beginning (after one minute or so), and consistently.

For query with bind values.... I wanted to confirm that it doesn't help and state is always run, but I tried it several times and in one try state was correctly set to error. Even more mysterious...

When I return new doc, it always has correct value state=error. I tried for bind query and for IN query without bind, for exmple:

_result=[attemptCount=0, hostname=bar, mac=, status=error, status2=foo, ip=172.22.30.1, _id=vTask/4370529101510, _rev=4370533689030, _key=4370529101510]

Yes I can do sniff. You mean to catch network traffic with wireshark and then analyse http api communication?

**Comment by roman1720** [comment]
I tried after first update with AQL add another update (so to try it update with another method):

c.update(task, {attemptCount: errCount, status: "extraset", status2: "extraset"});

result in db:

{"attemptCount":1,"hostname":"bar","mac":"","status":"run","ip":"172.22.30.1","status2":"extraset"}

status property is ignored.

After app finishes, there is 10376 documents in vTask collection. All are correctly updated, except two documents. I have another collection which uses same mechanism with status property and there is totally 2875 documents, and one was left status:run

{"status":"run","prefix":"172.23.1.0/24","hops":["10.0.10.254","172.23.1.1"]}

It seems to me that problem is with property name "status" but together with some special conditions.

**Comment by jsteemann** [comment]
If the updates (AQL or non-AQL) work for other documents in the same collection, then the problem likely has to do with that one or two specific documents. Is it possible to share the datafiles of that particular collection so we can try to reproduce it with the same data?

**Comment by roman1720** [comment]
Sniffing database connection was great idea, seeing all queries going to db helped us to solve problem. Problem was with multiple processes concurrent access. Another process was rewriting this value (under very special circumstances, totally unexpected). Sorry for taking your time, at least I learned new way of troubleshooting.
