### ISSUE TITLE
3.6.5 Arangodb Memory keeps increasing

### ISSUE THREAD

**Issue by zhaiwanpeng711** [arangodb/arangodb#17541]
## My Environment

* __ArangoDB Version__:        3.6.5
* __Deployment Mode__:        Single Server | Leader/Follower ("Master/Slave") 
* __Deployment Strategy__:  Manual Start
* __Configuration__:               
[server]
authentication = true
endpoint = tcp://[::]:18119
storage-engine = rocksdb
[log]
level = DEBUG
[rocksdb]
debug-logging=true
write-buffer-size=128000000
max-write-buffer-number=10
total-write-buffer-size=1000000000
dynamic-level-bytes=false
[block-cache-size=512000000]
enforce-block-cache-size-limit=true
[cache]
size=256000000

* __Infrastructure__:               own 
* __Operating System__:       Centos 7.6
* __Total RAM in your machine__:        32Gb
* __Disks in use__:        SSD
* __Used Package__:             

## Steps to reproduce

1. The memory usage for the night after the restart is 6.9 GB
![img_v2_5047617a-a3a6-4efa-b3a6-19376158801g](https://user-images.githubusercontent.com/31246452/200557943-f2f30ad0-3ee7-416c-b649-2b9917270655.jpg)

2.System environment variable Settings
![image](https://user-images.githubusercontent.com/31246452/200558686-592638ad-6997-476c-b28d-c1c6f0411b87.png)

3. The database disk backup is occupied 347mb
![image](https://user-images.githubusercontent.com/31246452/200558940-521237aa-b1a5-45c7-84fe-2795f5c9fd72.png)

__Problem__: 
Why is the arangodb server continually increasing the memory usage, and adding the official memory reduction configuration has no effect?

__Expected result__:

Provides effective solutions to limit memory growth

**Comment by dothebart** [comment]
Hi, 
Please note that ArangoDB 3.6 has been EOL'ed for quiet a while now. 
Please upgrade to ArangoDB 3.8.x at least and if the issue persists reopen this ticket.
