### ISSUE TITLE
Query by example - document property in array

### ISSUE THREAD

**Issue by Kurtas** [arangodb/arangodb#1756]
Hello, 

 I have following document structure:
```
{
name: 'test',
ipList: [
 {mask: 30, net: '10.41.129.168/30', ip: '10.41.129.169', type: 'primary'},
 {mask: 30, net: '10.41.113.24/30', ip: '10.41.113.25', type: 'primary'}
]
}
```
How I can test (the best performance) if exists a document with specified ``` net ``` attribute

I tried ```db.test.firstExample({ipList.net : '10.41.129.168/30'})``` and I got ```SyntaxError``` but it should work according to the documentation  ... see https://docs.arangodb.com/Documents/DocumentMethods.html and look for ``` { a.c : 1 }```

I also tried 
```
db.test.firstExample("ipList[*].net", '10.41.129.168/30');
db.test.firstExample("ipList.net", '10.41.129.168/30');
```
but both return null

Is there any way how to search a document if property is in array?

**Comment by dothebart** [comment]
As you already found out the document interface is a bit simple minded. The recommended way of doing this is using AQL with array indices (ArangoDB 2.8 onwards):

    FOR x IN test FILTER '10.41.129.168/30' IN x.ipList[*].net RETURN x

Create the array index like this:

    db.test.ensureIndex({ type: "skiplist", fields: ["ipList[*].net"]})

Check back the index is utilized:

    db._explain(`FOR x IN test FILTER '10.41.129.168/30' IN x.ipList[*].net RETURN x`)
    Query string:
     FOR x IN test FILTER '10.41.129.168/30' IN x.ipList[*].net RETURN x
    
    Execution plan:
     Id   NodeType        Est.   Comment
      1   SingletonNode      1   * ROOT
      6   IndexNode          1     - FOR x IN test   /* skiplist index scan */
      5   ReturnNode         1       - RETURN x
    
    Indexes used:
     By   Type       Collection   Unique   Sparse   Selectivity   Fields                Ranges
      6   skiplist   test      false    false            n/a   [ `ipList[*].net` ]   (("10.41.129.168/30" in x.`ipList`[*].`net`))
    
    Optimization rules applied:
     Id   RuleName
      1   use-indexes
      2   remove-filter-covered-by-index
