### ISSUE TITLE
Unhandled exception: c000001d at address 00007ff6f0b4fdf9 in thread 37f0 arangodb

### ISSUE THREAD

**Issue by arunvenkat1911** [arangodb/arangodb#17572]
HI, 

We tried to insert 5 million rows to arango db. 
The db crashed and it is not not restrating.
I can see this error in log file
"Unhandled exception: c000001d at address 00007ff6f0b4fdf9 in thread 37f0 arangodb" 

Please help us with the solution. 

Arun,

**Comment by mpoeter** [comment]
Hi @arunvenkat1911,

c000001d is the exception code for "illegal instruction".
Which arangodb version are you running and on which hardware (exact CPU model; virtual machine environment if any).

**Comment by arunvenkat1911** [comment]
Version - 3.10.0 Community Edition
CPU model: 
Common KVM processor 2.20 GHz
Memory : 30 GB
CPU 4 core
OS: windows server 2022 Standard 64 bit
It is a Virtual machine environment, not physical machine.

**Comment by mpoeter** [comment]
Please note that 3.9 and 3.10 target the Intel Sandy Bridge architecture. In particular they use AVX and other instructions introduced with Sandy Bridge. In a virtual environment you have to ensure that the according instruction sets are enabled for the virtual CPU.

**Comment by dothebart** [comment]
We have meanwhile Released ArangoDB 3.10.11; If the issue still persists please report back. 
Closing for now.
