### ISSUE TITLE
Using variables with upsert

### ISSUE THREAD

**Issue by sleepycat** [arangodb/arangodb#1758]
I having been playing around with inserting some data and noticed that UPSERT and INSERT seem to operate a little differently:
```javascript
arangosh [test]> db._query(`FOR doc IN [{fizz: "buzz"}, {foo: "bar"}] INSERT doc IN vertices RETURN NEW`).toArray()
[ 
  { 
    "fizz" : "buzz", 
    "_id" : "vertices/1165480123453", 
    "_rev" : "1165480123453", 
    "_key" : "1165480123453" 
  }, 
  { 
    "foo" : "bar", 
    "_id" : "vertices/1165480320061", 
    "_rev" : "1165480320061", 
    "_key" : "1165480320061" 
  } 
]

```

But UPSERT seems not to like variables:

```javascript
arangosh [test]> db._query(`FOR doc IN [{fizz: "buzz"}, {foo: "bar"}] UPSERT doc INSERT doc UPDATE {} IN vertices RETURN NEW`).toArray()
JavaScript exception in file '/usr/share/arangodb/js/client/modules/org/arangodb/arangosh.js' at 104,13: [ArangoError 1501: expecting object literal or bind parameter for example (while parsing)]
!      throw new ArangoError(requestResult);
!            ^
stacktrace: Error
    at Object.exports.checkRequestResult (/usr/share/arangodb/js/client/modules/org/arangodb/arangosh.js:104:13)
    at ArangoStatement.execute (/usr/share/arangodb/js/client/modules/org/arangodb/arango-statement.js:186:12)
    at ArangoDatabase._query (/usr/share/arangodb/js/client/modules/org/arangodb/arango-database.js:826:42)
    at <shell command>:1:4
```

It feels reasonable to expect the UPSERT to work like that when the INSERT does.
Any thoughts on supporting this type of stuff in the future?

**Comment by baslr** [comment]
I run in the same issue. You also need to declare the update. Also when it does nothing.

```
FOR doc IN [{fizz: "buzz"}, {foo: "bar"}]
INSERT doc 
UPDATE {}
IN vertices  RETURN NEW`
```

**Comment by sleepycat** [comment]
I considered that approach. In then end it was reasonable to just switch to INSERT rather than UPSERT.  It feels like consistent behaviour for *SERT would be good.

**Comment by dothebart** [comment]
The reason why we can't support variables in there is the following:

The document to upsert has to be looked up in the collection, for which a filter condition is created. To be able to do so, the UPSERT has to know from the start what to do. 

You could have a glance under the hood using the `explain` command:

    db._explain(`UPSERT {name: 'test'} INSERT {name: 'test', foo: 'bar'} UPDATE {} IN user RETURN { _key: NEW._key, old: OLD }`)
    Query string:
     UPSERT {name: 'test'} INSERT {name: 'test', foo: 'bar'} UPDATE {} IN user RETURN { _key: NEW._key, 
     old: OLD }
    
    Execution plan:
     Id   NodeType                  Est.   Comment
      1   SingletonNode                1   * ROOT
      8   SubqueryNode                 1     - LET #3 = ...   /* subquery */
      2   SingletonNode                1       * ROOT
      3   EnumerateCollectionNode      3         - FOR #1 IN user   /* full collection scan */
      4   CalculationNode              3           - LET #6 = (#1.`name` == "test")   /* simple expression */
      5   FilterNode                   3           - FILTER #6
      6   LimitNode                    1           - LIMIT 0, 1
      7   ReturnNode                   1           - RETURN #1
      9   CalculationNode              1     - LET $OLD = #3[0]   /* simple expression */
     11   CalculationNode              1     - LET #10 = { }   /* json expression */   /* const assignment */
     10   CalculationNode              1     - LET #8 = { "name" : "test", "foo" : "bar" }   /* json expression */   /* const assignment */
     12   UpsertNode                   1     - UPSERT $OLD INSERT #8 UPDATE #10 IN user
     13   CalculationNode              1     - LET #12 = { "_key" : $NEW.`_key`, "old" : $OLD }   /* simple expression */
     14   ReturnNode                   1     - RETURN #12
    
    Indexes used:
     none
    
    Optimization rules applied:
     Id   RuleName
      1   move-calculations-up
      2   move-calculations-up-2
      3   remove-data-modification-out-variables
      4   move-calculations-down
    
    Write query options:
     Option                   Value
     ignoreErrors             false
     waitForSync              false
     nullMeansRemove          false
     mergeObjects             true
     ignoreDocumentNotFound   false
     readCompleteInput        false

However, Bindvalues are supported.

**Comment by dothebart** [comment]
@sleepycat did this clarify this issue? could we close it?

**Comment by sleepycat** [comment]
Yes it did. Thanks.
