### ISSUE TITLE
FOXX Controller file support nested files

### ISSUE THREAD

**Issue by riverdusty** [arangodb/arangodb#1759]
Hi

Since controller files get quite large, I'd like to see a feature where I can nest files in my controller.
For example, I could have a controller that simply has `include: puts.js` and/or `includes: gets.js`.
Or a more JS version like, `loadFile() / includeFile() / loadScript() / includeScript()`.
That would make code management a lot easier during development and code management.

Thanks

**Comment by pluma** [comment]
Controllers will be replaced with Routers in 3.0: https://github.com/arangodb/arangodb/pull/1612

These Routers behave more like the routers you may know from node's express framework, i.e. they allow arbitrarily nesting routers inside other routers. Unlike controllers they can also be exported and imported, allowing you to move them into their own files as necessary.

e.g.

```
const createRouter = require('@arangodb/foxx/router');
const sub1 = createRouter();
const sub2 = createRouter();
const ext = createRouter();

module.context.use('/a', sub1); // mount the router at the given path
sub1.use('/b', sub2); // mount one router inside another
module.context.use(ext); // or just mount it directly

sub1.get('/hello', /* ... */); // will live at /a/hello
sub2.get('/world', /* ... */); // will live at /a/b/world
ext.get('/bananas', /* ... */); // will live at /bananas
```

**Comment by pluma** [comment]
I'll leave this issue open until the FOTF branch implementing the new Foxx API is merged into devel.

**Comment by pluma** [comment]
Fixed via FOTF.
