### ISSUE TITLE
Upgrade ArangoDB

### ISSUE THREAD

**Issue by spoh-ally** [arangodb/arangodb#17605]
## My Environment

* __ArangoDB Version__:        3.6.12
* __Deployment Mode__:       cluster
* __Deployment Strategy__:   
* __Configuration__:               3 nodes cluster
* __Infrastructure__:               own
* __Operating System__:        RHEL 8.2
* __Total RAM in your machine__:        32Gb each
* __Disks in use__:        
* __Used Package__:               RedHat RPM

## Component, Query & Data

__Affected feature__:

__AQL query (if applicable)__:
```


```
__AQL explain and/or profile (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1.  deleted old version (3.6.12) binaries with "rpm -e [package name]"
2. installed new version (3.7.2) binaries with "rpm -ivh [package name]"
3. started cluster with starter.join and starter.data-dir etc.

__Problem__:
2022-11-17T17:46:01+09:00 |INFO| ## Start of agent log
	2022-11-17T08:46:00Z [49408] ERROR [24bd1] {startup} ----------------------------------------------------------------------'
	2022-11-17T08:46:00Z [49408] ERROR [1c156] Database '_system' needs upgrade. Please start the server with --database.auto-upgrade
	2022-11-17T08:46:00Z [49408] FATAL [2eb08] Database '_system' upgrade failed (bad parameter). Please inspect the logs from the upgrade procedure and try starting the server again.

__Expected result__:

**Comment by spoh-ally** [comment]
Could anyone advise me how I can upgrade '_system' database starting with --database.auto-upgrade ? I only uninstall/installed binaries of ArangoDB with RedHat RPM package (from 3.6.12 to 3.7.2)

**Comment by mpoeter** [comment]
Did you have a look at the documentation?
https://www.arangodb.com/docs/stable/upgrading.html

**Comment by dothebart** [comment]
Leave all nodes running. 
First you upgrade the agents one by one. then the DB-Servers, then the coordinators. 
https://github.com/arangodb/release-test-automation/blob/main/release_tester/arangodb/starter/deployments/cluster.py#L196 implements this for our windows release tests - see the parameters added above the usual parameters for reference.

**Comment by spoh-ally** [comment]
Hi all.
![20221118_151646_12](https://user-images.githubusercontent.com/78084950/202634306-f446321a-7911-4c51-bc4b-533a1ac06e54.jpg)
I tried to upgrade it but don't know how I can install new version binaries. I have RedHat rpm package.
Please advise me

**Comment by spoh-ally** [comment]
![confliction](https://user-images.githubusercontent.com/78084950/202634806-fc6f86a2-c775-417f-8593-d3056c16ba17.jpg)
I've tried to install;; new version binaries but it makes some conflictions. Please help me.

**Comment by dothebart** [comment]
you need to use `rpm -U` to tell it to replace an existing package.

**Comment by Simran-B** [comment]
What storage engine does your deployment use? If it's MMFiles, then you can't do an in-place upgrade of your database directory.

**Comment by spoh-ally** [comment]
> What storage engine does your deployment use? If it's MMFiles, then you can't do an in-place upgrade of your database directory.

I'm using Rocksdb engine and I think I have upgraded during the cluster was working, which I didn't know the in-place upgrade is available option. Anyway thanks for all of your kind advices.
