### ISSUE TITLE
The variable in limit

### ISSUE THREAD

**Issue by Kurtas** [arangodb/arangodb#1760]
Hello, 

 why I can't use a variable in a limit? Is it a bug?
```
let test = 10
for t in someCollection
limit 0, test
return t
```

**Comment by jsteemann** [comment]
`LIMIT` does not support arbitrary expressions for its operands. The values must be known at query compile time, that means only number literals or bind parameters are allowed as operands for the `LIMIT` operation (see https://github.com/arangodb/arangodb/issues/1011).
That means if you need to inject numeric values for `LIMIT` from the outside, you may use a bind parameter.

**Comment by Kurtas** [comment]
hmm, binding works thanks. 
It would be nice to be able to use a dynamic value from the query
