### ISSUE TITLE
Path problems 

### ISSUE THREAD

**Issue by AmmarMohamed** [arangodb/arangodb#1761]
when i change the path of the post request that return error and maybe run another cod 

the message  error is "unknown path '/ammar/user/loggg'"

**Comment by dothebart** [comment]
By default arangodb only implements exact matches to the APIs. You can use URL-Arguments in foxx to implement unsharp matches. If you want to implement pattern matching in URLs, to do for example meta refresh, actions can do this: https://docs.arangodb.com/ArangoActions/HtmlExample.html More generaly you should rather make it a query parameter.

**Comment by AmmarMohamed** [comment]
I solved this problem by restart the service in the windows and always need to restart the service with any change in the path

**Comment by dothebart** [comment]
ah, you edited the config file and were wondering whether the changes have effect?

**Comment by AmmarMohamed** [comment]
are you mean the edite the manifest file??

**Comment by dothebart** [comment]
No, I was talking about the etc/arangod.conf file which is only loaded & parsed at service start time.

Foxx services (in development mode) should rather find out themselves. 

I'd like to understand which trap you ran into, so we can eventually protect others from that - thats the reason why I want to find out though you solved your problem for yourselves ;-)

**Comment by AmmarMohamed** [comment]
Thank You >> I solve the problem
