### ISSUE TITLE
How can I make all fulltext index to be kept in main memory permamently ?

### ISSUE THREAD

**Issue by ansarihaseb** [arangodb/arangodb#1762]
In arango raw data are stored as a physical file system and indexes are partially(frequently used indexes) stored in main memory and some, which are not in frequent use, in physical storage. I want to design arango in such a way that all the indexes that I'll create or already created must always be there in main memory permanently. Mostly it will be fulltext index or sometimes hash index. How can I achieve it ?

**Comment by ansarihaseb** [comment]
@dothebart

**Comment by baslr** [comment]
`Derived data (indices, etc.) is stored in the main memory only.` [ArangoDB.com](https://www.arangodb.com/2012/03/avocadodb-memory-management-and-consistency/)

`which are not in frequent use, in physical storage` I guess this is done by the OS. See [Paging](https://en.wikipedia.org/wiki/Paging)
On GNU / Linux you can do `echo 0 > /proc/sys/vm/swappiness` [The kernel will swap only to avoid an out of memory condition](https://en.wikipedia.org/wiki/Swappiness) [[2]](http://unix.stackexchange.com/questions/10214/how-to-set-per-process-swapiness-for-linux#10227)

**Comment by ansarihaseb** [comment]
yes but what about the indexes which are not in frequent use ? where the arango saves these indexes ? If in physical I want to store these non-frequent indexes in the main memory

**Comment by baslr** [comment]
All Indexes are store in ram. If the size of indexes > size ram then the OS has to swap pages from ram to swap.
As of 2.8 indexes are volatile and recomputed when ArangoDB starts and stored only in ram.
In a future version of ArangoDB also indexes are persistent (to reduce startup time and drop recomputing). [ArangoDB roadmap](https://www.arangodb.com/roadmap/)

**Comment by dothebart** [comment]
Indexes are built up when collections are loaded. If you unload a collection you can temporarily reduce the memory footprint. However, this will be at the cost of re-building the index when re-loading the collection. 

This is why we call ArangoDB as _mostly in memory_. You should therefore dimension your hardware acoordingly to the amount of your data and the number of indices you use.

We don't have an ETA for persistent indices yet.
