### ISSUE TITLE
Error: unrecognized flag --harmony_destructuring

### ISSUE THREAD

**Issue by lvarayut** [arangodb/arangodb#1763]
I'm writing a Foxx service using ES6. I executed `node --v8-options | ag "in progress"` to get all available harmony flags:

```bash
  --harmony_modules (enable "harmony modules" (in progress))
  --harmony_regexps (enable "harmony regular expression extensions" (in progress))
  --harmony_proxies (enable "harmony proxies" (in progress))
  --harmony_sloppy_function (enable "harmony sloppy function block scoping" (in progress))
  --harmony_sloppy_let (enable "harmony let in sloppy mode" (in progress))
  --harmony_unicode_regexps (enable "harmony unicode regexps" (in progress))
  --harmony_reflect (enable "harmony Reflect API" (in progress))
  --harmony_destructuring (enable "harmony destructuring" (in progress))
  --harmony_default_parameters (enable "harmony default parameters" (in progress))
  --harmony_sharedarraybuffer (enable "harmony sharedarraybuffer" (in progress))
  --harmony_atomics (enable "harmony atomics" (in progress))
  --harmony_simd (enable "harmony simd" (in progress))
```

Then, I ran ` arangod --javascript.v8-options="--harmony --harmony_arrow_functions --harmony_destructuring"` in order to launch a server supporting those flags. However, I got the error, `Error: unrecognized flag --harmony_destructuring`. Not quite sure why it's doesn't work. My node version is v5.6.0.

**Comment by dothebart** [comment]
While ArangoDB uses V8 as node does, it doesn't use the same version (see #1513 )

Use the corrosponding call to V8 to find out the supported options:

arangod --javascript.v8-options="--help" /tmp/dummydatabase

**Comment by lvarayut** [comment]
Thanks for your response. Is there any timeline that you're going to integrate the latest version of Node? Or, could you give some suggestions on the current best option I could do to write ES6 in Foxx?

**Comment by Simran-B** [comment]
ArangoDB doesn't use Node. It embeds V8 like Node does.

There were a lot of breaking changes in V8 since v4.3.61 (which ArangoDB
uses), which makes it rather difficult to update. But work is in progress
to make that upgrade happen. Chances are good, that ArangoDB 3.0 will
feature a much newer V8.

Note that destructing hasn't landed in a stable V8 yet. It should arrive
soon though with the next major Chrome release (which will mark the point
of a stable V8 4.9).

Your best option is a transpiler like BabelJS at the moment I guess.

**Comment by lvarayut** [comment]
Ok. Thanks @Simran-B.

**Comment by dothebart** [comment]
hi @lvarayut, meanwhile we released ArangoDB 3 with V8 5.0; As you're the author of https://lvarayut.github.io/relay-fullstack/ - have you seen this question on stackoverflow? http://stackoverflow.com/questions/38158327/arangodb-foxx-with-relay-framework
Maybe @pluma and you could write a cookbook about how to combine foxx and relay fullstack?

**Comment by lvarayut** [comment]
@dothebart, Thanks for asking. That would be great to have the cookbook. Where would you like to create a cookbook?

**Comment by Simran-B** [comment]
The cookbook repository is here:
https://github.com/arangodb/cookbook 

And it is hosted here:
https://docs.arangodb.com/latest/cookbook

**Comment by lvarayut** [comment]
I'm very busy this month. Will check it out asap.
