### ISSUE TITLE
The webinterface should display the correct query time

### ISSUE THREAD

**Issue by dothebart** [arangodb/arangodb#1765]
Since 2.8 we [run queries async](https://docs.arangodb.com/GeneralHttp/index.html#blocking-vs-nonblocking-http-requests) from the AQL editor so users are able to cancel this query later on.

The first HTTP call instanciates the query on the server, and sends a second call to poll for the result instantly.
If the result is not ready within that timeframe, the webinterface polls in 500 ms intervals.
-> Thus query times displayed are either in the 20ms range (the two http requests) or > 500ms. 

The fix should be [that the client requests statistics from the server (currently available via `getExtra()` in the client](https://docs.arangodb.com/Aql/Invoke.html). The server will in future deliver a cumulative time also, not just the fragments of the query phases. The webinterface should then display this cummulative time.

Thanks to @lewisdiamond for reporting this.

**Comment by jsteemann** [comment]
Fixed in 2.8.5. The query execution time displayed is now the server-side query execution time, excluding HTTP transfer and excluding front-end sleep time.
