### ISSUE TITLE
[Feature Request] `DATE_ADD()` with optional timezone

### ISSUE THREAD

**Issue by konsultaner** [arangodb/arangodb#17673]
At the moment it takes some conversions to securly add a day to a date that is not UTC. This query shows what I mean:

```AQL
RETURN {
    a: DATE_LOCALTOUTC(DATE_ADD(DATE_TIMESTAMP(DATE_UTCTOLOCAL(1561932000000, 'Europe/Berlin')),200,'d'), 'Europe/Berlin'),
    b: DATE_ADD(1561932000000,200,'d')
}
```

This returns 2 different values due to day light saving is changing the timezone offset:

```AQL
[
  {
    "a": "2020-01-16T23:00:00.000Z",
    "b": "2020-01-16T22:00:00.000Z"
  }
]
```

It would be great to just do this:

```AQL
RETURN {
    a: DATE_ADD(1561932000000,200,'d','Europe/Berlin'),
    b: DATE_ADD(1561932000000,200,'d')
}
```

and get

```AQL
[
  {
    "a": "2020-01-16T23:00:00.000Z", // or "2020-01-17T00:00:00.000+01:00"
    "b": "2020-01-16T22:00:00.000Z"
  }
]
```

**Comment by konsultaner** [comment]
I want to write a PR to this issue. There are 2 options to make this work.

1. Only add a `timezone` to each method like `DATE_ADD(date, 1, 'd', 'Europe/Berlin')`
2. Add the `timezone` to the query options like this
   ```JSON
   { 
      "query" : "RETURN DATE_ADD(1511132400000, 1, 'd')", 
      "options" : { 
        "timezone" : "Europe/Berlin"
      } 
   }
   ```
4. both, where the in-query declaration is dominant
   ```JSON
   { 
      "query" : "RETURN DATE_ADD(1511132400000, 1, 'd', 'Asia/Bangkok')", 
      "options" : { 
        "timezone" : "Europe/Berlin"
      } 
   }
   ```

That may result in the following method overload examples:

``` AQL
DATE_ADD(date, 'P1D') // Add one year
DATE_ADD(date, 'P1D', 'Europe/Berlin')  // Add one year assuming date is in timezone 'Europe/Berlin'
DATE_ADD(date, 1, 'd') // Add one year
DATE_ADD(date, 1, 'd', 'Europe/Berlin') // Add one year assuming date is in timezone 'Europe/Berlin'
```

There is one issue:

Since `DATE_ADD` also accepts `string` dates it might be confusing, that a UTC time string is another timezone. Also the result will be a UTC time string, even though it would be calculated in a given timezone.

**Comment by jsteemann** [comment]
Specifying a timezone in the query options looks a bit strange to me and would prohibit the valid use case of calculating multiple date/times with different timezones in the same query.
I think the timezone should to be an additional optional parameter to all date/time functions that should get timezone support. Alternatively, we could also add dedicated timezone-aware date/time variations of the existing date/time functions with modified call signatures (timezone parameter needs to go somewhere).

**Comment by konsultaner** [comment]
@jsteemann I wanted to actually contribute and write the code. I just wanted to know what you think is the best solution.

> Specifying a timezone in the query options looks a bit strange to me and would prohibit the valid use case of calculating multiple date/times with different timezones in the same query.

My thoughts on that were, that the query option only holds the default timezone and if a `DATE_`-function with a timezone parameter is called, the functions parameter will be used instead of the default one. But this is just an idea. If you don't like the idea, I'd just go with something like this:

```AQL
DATE_ADD(date, 'P1D', 'Europe/Berlin')
```

> I think the timezone should to be an additional optional parameter to all date/time functions that should get timezone support. Alternatively, we could also add dedicated timezone-aware date/time variations of the existing date/time functions with modified call signatures (timezone parameter needs to go somewhere).

The following functions may have a timezone:

[DATE_DAYOFWEEK()](https://www.arangodb.com/docs/stable/aql/functions-date.html#date_dayofweek)
[DATE_YEAR()](https://www.arangodb.com/docs/stable/aql/functions-date.html#date_year)
[DATE_MONTH()](https://www.arangodb.com/docs/stable/aql/functions-date.html#date_month)
[DATE_DAY()](https://www.arangodb.com/docs/stable/aql/functions-date.html#date_day)
[DATE_HOUR()](https://www.arangodb.com/docs/stable/aql/functions-date.html#date_hour)
[DATE_MINUTE()](https://www.arangodb.com/docs/stable/aql/functions-date.html#date_minute)
[DATE_SECOND()](https://www.arangodb.com/docs/stable/aql/functions-date.html#date_second)
[DATE_MILLISECOND()](https://www.arangodb.com/docs/stable/aql/functions-date.html#date_millisecond)
[DATE_DAYOFYEAR()](https://www.arangodb.com/docs/stable/aql/functions-date.html#date_dayofyear)
[DATE_ISOWEEK()](https://www.arangodb.com/docs/stable/aql/functions-date.html#date_isoweek)
[DATE_LEAPYEAR()](https://www.arangodb.com/docs/stable/aql/functions-date.html#date_leapyear)
[DATE_QUARTER()](https://www.arangodb.com/docs/stable/aql/functions-date.html#date_quarter)
[DATE_DAYS_IN_MONTH()](https://www.arangodb.com/docs/stable/aql/functions-date.html#date_days_in_month)
[DATE_TRUNC()](https://www.arangodb.com/docs/stable/aql/functions-date.html#date_trunc)
[DATE_ROUND()](https://www.arangodb.com/docs/stable/aql/functions-date.html#date_round)
[DATE_FORMAT()](https://www.arangodb.com/docs/stable/aql/functions-date.html#date_format)
[DATE_ADD()](https://www.arangodb.com/docs/stable/aql/functions-date.html#date_add)
[DATE_SUBTRACT()](https://www.arangodb.com/docs/stable/aql/functions-date.html#date_subtract)
[DATE_DIFF()](https://www.arangodb.com/docs/stable/aql/functions-date.html#date_diff)
[DATE_COMPARE()](https://www.arangodb.com/docs/stable/aql/functions-date.html#date_compare)

Most of them could take an optional parameter. The only problem would be:

[DATE_DIFF()](https://www.arangodb.com/docs/stable/aql/functions-date.html#date_diff)
[DATE_COMPARE()](https://www.arangodb.com/docs/stable/aql/functions-date.html#date_compare)

They already have an optional parameter, so for compatibility reasons the timezone would have to be added as last parameter. IMO that would be ok. What do you think?

Wouldn't having extra timezone aware functions kind of overload the date function section?

DATE_DAYOFWEEK_TIMEZONED()
DATE_YEAR_TIMEZONED()
DATE_MONTH_TIMEZONED()
DATE_DAY_TIMEZONED()
DATE_HOUR_TIMEZONED()
DATE_MINUTE_TIMEZONED()
DATE_SECOND_TIMEZONED()
DATE_MILLISECOND_TIMEZONED()
DATE_DAYOFYEAR_TIMEZONED()
DATE_ISOWEEK_TIMEZONED()
DATE_LEAPYEAR_TIMEZONED()
DATE_QUARTER_TIMEZONED()
DATE_DAYS_IN_MONTH_TIMEZONED()
DATE_TRUNC_TIMEZONED()
DATE_ROUND_TIMEZONED()
DATE_FORMAT_TIMEZONED()
DATE_ADD_TIMEZONED()
DATE_SUBTRACT_TIMEZONED()
DATE_DIFF_TIMEZONED()
DATE_COMPARE_TIMEZONED()

**Comment by konsultaner** [comment]
Hi @jsteemann my PR is more than 6 months old. Will it have a chance to get into a release any time?

**Comment by markuspf** [comment]
Many thanks for your contribution and apologies for it not receiving the attention that it deserved sooner. We have just merged it to devel.
