### ISSUE TITLE
Missing confirmation message in AQL editor

### ISSUE THREAD

**Issue by mindplay-dk** [arangodb/arangodb#1768]
The Query tab in the AQL editor (of the web interface) gives no confirmation message for successful queries - an error message from a previous query remains visible, which is quite confusing.

The red error message should probably disappear and get replaced with a green confirmation message - possibly with some basic stats, like execution time and number of records affected.

**Comment by baslr** [comment]
Hi, there working on it `new query view better error handling` 60b81c84b0358e2b3ac3e43354c5d691649bfdc3

**Comment by dothebart** [comment]
Moving this to #1693 so we have one place to collect this.

**Comment by hkernbach** [comment]
Thank you for your contribution. We're currently doing a complete redesign of the aql editor. We will consider your suggestions.
