### ISSUE TITLE
Body request 

### ISSUE THREAD

**Issue by AmmarMohamed** [arangodb/arangodb#1769]
When i made request and put an empty element like {
  "_key": "string",
  "eMail": "string@yahoo.com",
  "firstName": "string",
  "gender": "string",
  "lastName": "ghj",
  "phone": ""
}

the foxx made exception without deal with this element

**Comment by jsteemann** [comment]
What is the exception, and what does the handler for the called route do?

**Comment by dothebart** [comment]
Closing because of missing feedback.
