### ISSUE TITLE
What a fucking disgrace is this database

### ISSUE THREAD

**Issue by cobra2k5** [arangodb/arangodb#17708]
NO SUPPORT

PIECE OF SHIT

Who is the motherfucker who invented this piece of crap.

For anyone who is considering using this piece of shit. JUST DON'T ! Go for NEO4J or MongoDB

**Comment by neunhoef** [comment]
We do not approve of the sort of language used in this issue and therefore consider it as spam and close it (as of company policy). We always try to respond to all sensible support requests, but resources are limited, and our paying customers get preferred service.
