### ISSUE TITLE
Error compiling: SSL: SSLv3_method not found?

### ISSUE THREAD

**Issue by markasoftware** [arangodb/arangodb#1773]
Here's the error I'm getting:

```
lib/Basics/ssl-helper.cpp:59:14: error: use of undeclared identifier 'SSLv3_method'; did you mean 'SSLv23_method'?
meth = SSLv3_method();
^~~~~~~~~~~~
SSLv23_method
/usr/include/openssl/ssl.h:2360:19: note: 'SSLv23_method' declared here
const SSL_METHOD *SSLv23_method(void); /* Negotiate highest available SSL/TLS
```
This is when attempting to install from the arangodb package in the Arch Linux AUR. I've tried with both clang and gcc, and get effectively the same error message.

**Comment by markasoftware** [comment]
Sorry, the original error message I posted was incomplete. Fixed it.

**Comment by asaaki** [comment]
This seems to be an issue with latest OpenSSL version (1.0.2.g).
Happens on Arch Linux after update of the openssl package.

**Comment by asaaki** [comment]
The problem seems to be that the maintainers of the openssl package in Arch Linux decided to disable SSLv3 completely:
https://projects.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/openssl&id=4b82ed4285c7cb76caf6d75a015c5a7542c625d1

**Comment by markasoftware** [comment]
@asaaki Thank You! Rolling back openssl to 1.0.2.f (released in January) worked, and I successfully built the package. I'm still going to leave this issue open, however, because this is still a big issue that affects all Arch Linux users who keep openssl up-to-date.

**Comment by asaaki** [comment]
@markasoftware This is totally fine (leaving open), since rolling back won't be a long-term solution. There is also a reason, why new versions are released. :smile: So, I hope this issue can and will be addressed somehow.

**Comment by dothebart** [comment]
This will be part of the 2.8.5 Release, which is currently compiling. We expect the process to be ready later today.
