### ISSUE TITLE
Build issue with clang 15

### ISSUE THREAD

**Issue by ChrisAtArango** [arangodb/arangodb#17754]
## My Environment

* __ArangoDB Version__:        devel
* __Deployment Mode__:       N/A
* __Deployment Strategy__:  N/A
* __Configuration__:               N/A
* __Infrastructure__:               N/A
* __Operating System__:        MacOS 13.0.1
* __Total RAM in your machine__:        32 GB
* __Disks in use__:       N/A
* __Used Package__:              openssl installed via homebrew

## Component, Query & Data

__Affected feature__:

__AQL query (if applicable)__:
```


```
__AQL explain and/or profile (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. Clone devel 
2. cmake .. -DOPENSSL_ROOT_DIR=/opt/homebrew/Cellar/openssl@1.1/1.1.1s/ -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13 -DCMAKE_BUILD_TYPE=Debug -DUSE_OPTIMIZE_FOR_ARCHITECTURE=On -DCMAKE_C_COMPILER=/opt/homebrew/opt/llvm/bin/clang -DCMAKE_CXX_COMPILER=/opt/homebrew/opt/llvm/bin/clang++
3. make LDFLAGS="-L/opt/homebrew/opt/llvm/lib/c++ -Wl,-rpath,/opt/homebrew/opt/llvm/lib/c++" CPPFLAGS="-I/opt/homebrew/opt/llvm/include" (per homebrew instructions to use the bundled libraries and header files)
4. Build fails with the following error message:

```
<path>/lib/Zip/zip.cpp:1464:15: error: variable 'bBreak' set but not used [-Werror,-Wunused-but-set-variable]
          int bBreak = 0;
              ^
1 error generated.
```
__Problem__:

See above. clang version is 15.0.6.

__Expected result__:
Clean build. Additional info can be provided - just let me know.

**Comment by dothebart** [comment]
please see https://github.com/arangodb/arangodb/issues/17754 for the supported toolchain. closing this as duplicate.

**Comment by ChrisAtArango** [comment]
Using brew to install the CB via local source compilation doesn't solve the initial issue of having a build for a playground at your disposal on this platform :-). 

After some digging in the brew formula for the corresponding keg in addition to some other black magic (cf. caveats below), here's what now works for me on an MBP 18,3 with an M1 Pro (but should work across all Apple Silicon plattforms:

1. Clone the Github repo as per documentation
2. Create a build directory for cmake
3. The correct cmake invocation is 
`cmake .. --compile-no-warning-as-error -DOPENSSL_ROOT_DIR=/opt/homebrew/opt/openssl@1.1 -DCMAKE_OSX_DEPLOYMENT_TARGET=13 -DBUILD_TESTING=OFF -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=Debug -DUSE_GOOGLE_TESTS=OFF -DUSE_JEMALLOC=OFF -DUSE_MAINTAINER_MODE=OFF -DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -DCMAKE_C_COMPILER=/opt/homebrew/opt/llvm/bin/clang -DCMAKE_CXX_COMPILER=/opt/homebrew/opt/llvm/bin/clang++ -DCMAKE_CXX_FLAGS=-w -DCMAKE_CFLAGS=-w -DBOOST_NO_CXX98_FUNCTION_BASE=1`
4. `make -j$(sysctl machdep.cpu.logical_per_package | cut -d' ' -f2)` to utilise all available cores for the build

Caveats:

- The above assumes a newer cmake (>= 3.24) as per homebrew spec / installation (if you're using homebrew and upgrade regularly this shouldn't be an issue)
- I only tried this on Ventura, Monterey should work as well (don't forget to change `CMAKE_OSX_DEPLOYMENT_TARGET` to reflect this and double check the  correctness of the SDK symlink in `/Library/Developer/CommandLineTools/SDKs` ).
- clang version should be >= 15 as the Apple-supplied one (which you install with the xcode command line tools) is version 14 and will not work, hence the compiler definitions in the cmake invocation above.
