### ISSUE TITLE
Build issue on Apple Silicon with gcc 11/12

### ISSUE THREAD

**Issue by ChrisAtArango** [arangodb/arangodb#17752]
## My Environment

* __ArangoDB Version__:        devel
* __Deployment Mode__:       N/A
* __Deployment Strategy__:  N/A
* __Configuration__:               N/A
* __Infrastructure__:               N/A
* __Operating System__:        MacOS 13.0.1
* __Total RAM in your machine__:        32 GB
* __Disks in use__:       N/A
* __Used Package__:              openssl installed via homebrew

## Component, Query & Data

__Affected feature__:

__AQL query (if applicable)__:
```


```
__AQL explain and/or profile (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. Clone devel branch from github
2.  cmake .. -DOPENSSL_ROOT_DIR=/opt/homebrew/Cellar/openssl@1.1/1.1.1s/ -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13 -DCMAKE_BUILD_TYPE=Debug -DUSE_OPTIMIZE_FOR_ARCHITECTURE=On -DCMAKE_C_COMPILER=/opt/homebrew/bin/gcc-11 -DCMAKE_CXX_COMPILER=/opt/homebrew/bin/g++-11
3. Build fails with 
```
../../../../3rdParty/V8/v7.9.317/../v7.9.317/src/codegen/interface-descriptors.h:409:18: error: expected identifier before ',' token
  409 |     ##__VA_ARGS__,                                        \
      |                  ^

```
__Problem__:

See above. Can be reproduced with gcc 11.3.0 and  12.2.0.

__Expected result__:

Clean build. Additional info can be provided - just let me know.

**Comment by dothebart** [comment]
Hi, 
please see https://github.com/Homebrew/homebrew-core/pull/115397 about supported MacOS builds and the supported toolchain.
