### ISSUE TITLE
build in debian in aarch64(arm64v8): No install step for 'v8_build', make Error 2

### ISSUE THREAD

**Issue by Sugar1990** [arangodb/arangodb#17756]
## My Environment

* __ArangoDB Version__:        3.10.1
* __Infrastructure__:               own
* __Operating System__:        Build in docker (image: debian:bullseye), container run in PC YHKYLIN-OS (4.19.90-17.ky10.aarch64)
* __Total RAM in your machine__:        256GB   

__Problem__:
run steps as in webpage (https://www.arangodb.com/docs/stable/installation-compiling-debian.html), cmake command: "cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUSE_MAINTAINER_MODE=off -DUSE_OPTIMIZE_FOR_ARCHITECTURE=On -DUSE_GOOGLE_TESTS=off", cmake success, after command "make -j64", Error:

__Expected result__:
[ 14%] No install step for 'v8_build'
[ 14%] Completed 'v8_build'
[ 14%] Built target v8_build
make: *** [Makefile:171: all] Error 2

__Logs__:
... ...
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/growable-fixed-array-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/internal-coverage-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/iterator-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/math-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/object-fromentries-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/object-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/proxy-constructor-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/proxy-delete-property-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/proxy-get-property-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/proxy-get-prototype-of-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/proxy-has-property-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/proxy-is-extensible-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/proxy-prevent-extensions-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/proxy-revocable-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/proxy-revoke-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/proxy-set-property-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/proxy-set-prototype-of-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/proxy-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/reflect-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/regexp-exec-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/regexp-match-all-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/regexp-match-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/regexp-replace-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/regexp-search-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/regexp-source-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/regexp-split-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/regexp-test-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/regexp-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/string-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/string-endswith-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/string-html-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/string-iterator-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/string-pad-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/string-repeat-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/string-slice-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/string-startswith-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/string-substring-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/torque-internal-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/typed-array-createtypedarray-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/typed-array-every-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/typed-array-filter-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/typed-array-find-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/typed-array-findindex-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/typed-array-foreach-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/typed-array-reduce-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/typed-array-reduceright-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/typed-array-slice-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/typed-array-some-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/typed-array-subarray-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/builtins/typed-array-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/third_party/v8/builtins/array-sort-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/test/torque/test-torque-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/../v7.9.317/src/objects/intl-objects-tq-csa.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/../v7.9.317/src/builtins/arm64/builtins-arm64.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_initializers/gen/torque-output-root/torque-generated/exported-macros-assembler-tq.o
  AR(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/../gypfiles/libv8_nosnapshot.a
  TOUCH /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/../gypfiles/v8_compiler_for_mksnapshot.stamp
  AR(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/../gypfiles/libv8_base_without_compiler.a
  TOUCH /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/../gypfiles/v8_base.stamp
  AR(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/../gypfiles/libv8_initializers.a
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/mksnapshot/../v7.9.317/src/snapshot/embedded/embedded-file-writer.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/mksnapshot/../v7.9.317/src/snapshot/mksnapshot.o
  LINK(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/mksnapshot
  TOUCH fcf4bc5560c5ebd918bb4fa39879f42ca902cc99..intermediate
  ACTION generating: "/usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/icuuc/geni/snapshot.cc" ../v7.9.317/src/snapshot/embedded/embedded-empty.cc fcf4bc5560c5ebd918bb4fa39879f42ca902cc99..intermediate
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_snapshot/../v7.9.317/src/init/setup-isolate-deserialize.o
  CXX(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/v8_snapshot/geni/snapshot.o
  AR(target) /usr/src/arangodb/build/3rdParty/V8/v7.9.317/arm64.release/obj.target/../gypfiles/libv8_snapshot.a
[ 14%] No install step for 'v8_build'
[ 14%] Completed 'v8_build'
[ 14%] Built target v8_build
make: *** [Makefile:171: all] Error 2

**Comment by Sugar1990** [comment]
I have tried image from docker hub: arangodb:3.10.1 and arm64v8/arangodb;3.10.1, arangodb/ubuntubuildarangodb5-aarch64:latest, otherwise, run a container by image Centos:8.4, rpm install arangodb3-3.10.1-1.0.aarch64.rpm (from https://download.arangodb.com/) just a few hours before. These operations all run in PC YHKYLIN-OS (4.19.90-17.ky10.aarch64), and results are all 
"
Initializing root user...Hang on...
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
terminate called without an active exception
Aborted (core dumped)
"

**Comment by dothebart** [comment]
I'm sorry, but the actual error is still missing from your first post. can you re-run make after this error and post the hopefully less verbose build log?

`Unsupported system page size` seems to be a jemalloc error. I can find it in other ARM related issues; however, I don't find a solution in them.
Its this code which reads the configure output: 
```
        long result = sysconf(_SC_PAGESIZE);
        if (result == -1) {
                return LG_PAGE;
        }
        return (size_t)result;
```
I don't see how this could be working on other machines.
Can you please name your hardware a little bit more detailed?

**Comment by Sugar1990** [comment]
Firstly, thank you dothebart for reply. These is some info from 'proc/cpuinfo'
```
...
processor	: 63
model name	: Phytium,FT-2000+/64
BogoMIPS	: 100.00
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x70
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0x662
CPU revision	: 2
```
could you get some useful info?

**Comment by dothebart** [comment]
hm, our system is a `Neoverse N1`; is there a good source for Phytium machines outside of china?

can you try to build a minimal c- file printing you the `sysconf(_SC_PAGESIZE);` https://man7.org/linux/man-pages/man3/sysconf.3.html ?

**Comment by Sugar1990** [comment]
> 
I code a c-file as 
```
    printf("The number of processors configured is :%ld\n", sysconf(_SC_NPROCESSORS_CONF));
    printf("The number of processors currently online (available) is :%ld\n", sysconf(_SC_NPROCESSORS_ONLN));
    printf ("The pagesize: %ld\n", sysconf(_SC_PAGESIZE));  
    printf ("The number of pages: %ld\n", sysconf(_SC_PHYS_PAGES));  
    printf ("The number of available pages: %ld\n", sysconf(_SC_AVPHYS_PAGES)); 
    printf ("The memory size: %lld MB\n", (long long)sysconf(_SC_PAGESIZE) * (long long)sysconf(_SC_PHYS_PAGES) / ONE_MB );  
    printf ("The number of files max opened:: %ld\n", sysconf(_SC_OPEN_MAX));  
    printf("The number of ticks per second: %ld\n", sysconf(_SC_CLK_TCK));  
    printf ("The max length of host name: %ld\n", sysconf(_SC_HOST_NAME_MAX));  
    printf ("The max length of login name: %ld\n", sysconf(_SC_LOGIN_NAME_MAX)); 
```
and printing info after build as 
``` 
The number of processors configured is :64
The number of processors currently online (available) is :64
The pagesize: 65536
The number of pages: 4154776
The number of available pages: 2060735
The memory size: 259673 MB
The number of files max opened:: 1048576
The number of ticks per second: 100
The max length of host name: 64
The max length of login name: 256
```

**Comment by dothebart** [comment]
hm, `The pagesize: 4096` on my amd64 machine; 65k sounds a bit like maxint aka `result == -1`?

**Comment by Sugar1990** [comment]
> Unsupported system page size

Maybe, I got it. I read a webpage about 
```
3 common page sizes
4096 4k
16384 16K
65536 64k
It is compiled on 4K environment and cannot be run on 16 and 64, The opposite is true.
To avoid problems, it is recommended to compile on 64K machines
```
so, I think the point is ```The pagesize: 4096 on my amd64 machine``` different from 65536 on my machine.
Now, maybe we found the problem, can we solve it, could you build on a 65k pagesize arm64v8(aarch64) machine, output docker image or deb/rpm file?

**Comment by dothebart** [comment]
how's that controlled? by boot parameter? Is there a way to do this on AWS ARM machines? If yes, which?

**Comment by Sugar1990** [comment]
> how's that controlled? by boot parameter? Is there a way to do this on AWS ARM machines? If yes, which?

In my mind, memory pagesize is controlled by OS, so could you get a aarch64 OS with pagesize 64K, such as YHKYLIN-OS (4.19.90-17.ky10.aarch64)?

**Comment by dothebart** [comment]
hm, it seems that its a kernel compile time option: https://unix.stackexchange.com/questions/80725/change-the-size-of-my-memory-pages can you revalidate whether this is configured to 65k or set in your environment?

**Comment by Sugar1990** [comment]
> hm, it seems that its a kernel compile time option: https://unix.stackexchange.com/questions/80725/change-the-size-of-my-memory-pages can you revalidate whether this is configured to 65k or set in your environment?

Oh, I'm sorry. But now, it's seem that arangodb cannot be built in 64k arm64v8 PC, could you consider to solve the problem in next version or near future.

**Comment by Sugar1990** [comment]
> it seems to fail currently because of testsystem availability; the CI would need to do this as well. I see that with 256G one may want this. So again, where to buy such a thing?

I bought a server from Pyhtium Technology Co., maybe you can connect to Pyhtium agents, This is Pyhtium homepage, https://phytium.com.cn/en/

**Comment by dothebart** [comment]
can you post your kernel config so we can see which configuration it has around these memory paging mechanisms?

**Comment by dothebart** [comment]
I think the `.config` file in this directory contains what we want to know and whats required to compile a kernel like yours.

**Comment by Sugar1990** [comment]
> ls /usr/src/kernels/4.19.90-17.ky10.aarch64/ -a

I get the ```.config``` file, I upload file to a repository ```https://github.com/Sugar1990/4.19.90-17.ky10.aarch64```, would you get it?

**Comment by dothebart** [comment]
yes, thanks. will have a look at the settings.

**Comment by dothebart** [comment]
Please work with upstream jemalloc on a fix, we won't be able to maintain this within ArangoDBs domain. 
Will close this bug now as "won't fix", if a later version of jemalloc will work for you please notify us.

**Comment by dothebart** [comment]
Related: https://github.com/arangodb/arangodb/issues/22177
