### ISSUE TITLE
Alpinelinux package

### ISSUE THREAD

**Issue by yvann** [arangodb/arangodb#1775]
Hello everybody,

I'd like to know if someone's working on an Alpinelinux package ?

Alpinelinux is a very lightweight linux distribution used a lot in the docker ecosytem. https://www.alpinelinux.org/

Thanks for your help

**Comment by dothebart** [comment]
No, nobody is currently working on this. 

We have been looking at this, but didn't have time for this yet, so contributions are very welcome.
One Note: we've been working heavily on our cmake based build system and are dropping autoconf support with 3.0 (currently already done in git devel). 

I would therefore suggest you base your work on current git devel and not V2.8. Feedback and questions around our cmake configuration will probably arise, (if) we may probably better discuss this in the google group.

**Comment by yvann** [comment]
Thank you for this answer ! I'll try with the git devel

**Comment by dothebart** [comment]
@yvann we have been working hard to iron anything out in the cmake build. Have you encountert any issues?

**Comment by dothebart** [comment]
3.0.0 RC2 with the mentioned cmake integration is out now: https://www.arangodb.com/download-preview/
I'll close this now, if more questions arise around that topic, feel free to reopen & ask.
