### ISSUE TITLE
org/arangodb/request: Content-Type: undefined

### ISSUE THREAD

**Issue by bangert** [arangodb/arangodb#1776]
on arangodb 2.8.4 i noticed that the request module -- as in var request = require('org/arangodb/request'); -- sets the Content-Type: header to "undefined". 

I tried to interoperate with resteasy (http://resteasy.jboss.org/) which did not like this header.
According to https://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.7 the media type must be of form type/subtype.

Thanks

**Comment by pluma** [comment]
This seems to be a pre-existing problem with how the content-type header is added:

https://github.com/arangodb/arangodb/blob/2.8/js/common/modules/org/arangodb/request.js#L134

Basically the header will always be set even if the value is undefined.

Node's ClientRequest throws on undefined whereas the npm request module silently discards all undefined headers. I think we should do the latter.

**Comment by bangert** [comment]
Thanks. Much appreciated.
