### ISSUE TITLE
[2.8.3] Not getting stacktrace from Foxx.createQuery

### ISSUE THREAD

**Issue by reohjs** [arangodb/arangodb#1777]
In my Foxx app, which is in development mode, I have the following code:

```js
class Users extends Foxx.Repository {}

Users.prototype.checkUserConstraints = Foxx.createQuery({
  query: "FOR user IN users"
    + " FILTER (user.username == @username) OR (user.displayname == @displayname)"
    + " OR (emails[@email].address = @email)"
    + " RETURN user",
  params: ["username", "displayname", "email"]
});
```

The query has incorrect syntax but only a 404 is being returned from the route and there's no debug error in the console - is this not implemented? It's hard to see what's going wrong when you have multiple queries in a route, otherwise.

The web interface AQL editor does give the error as result:

```
[1501] syntax error, unexpected assignment near '= 'email')
RETURN user' at position 3:29 (while parsing)
```

Using Windows 7 x64

**Comment by pluma** [comment]
Can you show the route that uses the query? As the syntax error is in the AQL the error would be thrown when invoking the query rather than where it is defined.

**Comment by reohjs** [comment]
```js
Controller.post("/insert-user-doc", function (req, res) {
  var user = req.params("user").user;
  var username = user.username;
  var displayname = user.displayname;
  var email = user.emails[0];

  console.log('Users: ', Users.checkUserConstraints(username, displayname, email));

  // Find any user with existing fields: username, displayname, emails
  var exists = Users.checkUserConstraints(username, displayname, email);

  console.log('exists: ', exists);

  if (exists) {
    if (exists.username === username) {
      throw new Error("username-in-use");
    }
    else if (exists.displayname === displayname) {
      throw new Error("displayname-in-use");
    }
    else if (exists.email === email) {
      throw new Error("email-in-use");
    }
  }

  console.log('exists: ', exists);

  // Run transaction query
  var userId = db._executeTransaction({
    collections: {
      write: ["users", "userPlaylists", "userPlaylistLinks"]
    },
    action: function (user, graph, console) {
      var userId = Users.save(user)._key;

      console.log('uid: ', userId);

      // Create user's active playlist
      var playlist = graph.userPlaylists.save({
        name: "Active Playlist", privacy: "public", itemsCount: 0, items: []});

      console.log('playlist: ', playlist);

      var link = graph.userPlaylistLinks.save("users/"+userId, playlist._id, {});

      console.log('link: ', link);

      return userId;
    },
    params: [user, graph, console],
    waitForSync: true
  });

  console.log('user: ', user);

  // Insert user and return their _id
  res.json({userId});
})
.bodyParam("user", {
  description: "The user document to insert",
  type: joi.object().required()
})
.errorResponse(ArangoError, 404, "Can't insert user.");
```

Not getting any logs in foxxlog collection or console from `console.log` either

**Comment by reohjs** [comment]
Users was initialised like so:

```js
var UsersRepo = require("../repositories/users").repository;
var User = require("../models/users").model;

var db = require("org/arangodb").db;

var Users = new UsersRepo(
  db._collection("users"),
  {model: User}
);
```

**Comment by pluma** [comment]
The exception is thrown when `checkUserConstraints` is invoked in line 10. The logging happens further down the line, so that code is never reached.

The reason you're seeing a 404 without further info is that you're treating all ArangoError exceptions as 404. That means the exception is considered handled and won't be logged.

**Comment by reohjs** [comment]
Thanks @pluma removing `errorResponse `does indeed show the error.

Using `Error `instead of `ArangoError `causes the same result, is that also correct?

**Comment by pluma** [comment]
Yes, ArangoError inherits from Error.

I'm not sure why you're trying to handle ArangoError with a 404 at all -- none of the functions look like they would result in a "not found" type error.

**Comment by reohjs** [comment]
@pluma I was doing a quick refactor from existing code so I just chose an arbitrary number :)

Anyhow, this was due to my own misunderstanding so, sorry for the trouble & thanks again.

**Comment by pluma** [comment]
No worries. This will hopefully become more straightforward in ArangoDB 3.0.
