### ISSUE TITLE
Allowed characters in AQL variable names? ($ accepted in some cases)

### ISSUE THREAD

**Issue by Simran-B** [arangodb/arangodb#1778]
To quote the [documentation](https://docs.arangodb.com/Aql/Basics.html#variable-names):

> Allowed characters in variable names are the letters a to z (both in lower and upper case), the numbers 0 to 9 and the underscore (_) symbol. A variable name must not start with a number. If a variable name starts with the underscore character, it must also contain at least one letter (a-z or A-Z).

However, `$foo`, `$a_` and `$b2613` are also accepted. On the other hand, `foo$`, `$`, `$12c` and `$_x` raise errors.

Why is `$` accepted, if it's immediately followed by a letter, followed by `[a-zA-Z0-9_]`?

**Comment by Simran-B** [comment]
Hm... looks like it's even more complicated. The following **does work**:

```js
LET `$1` = 1..5
FOR ` \n@ALL\`::´äöüß` IN `$1`
RETURN ` \n@ALL\`::´äöüß`
```

**Comment by jsteemann** [comment]
An AQL variable name can optionally start with a `$`. The `$` must not occur anywhere else in the variable name.

However, when putting variable names in backticks, then any name is allowed. That means the following variable names will be valid:
```
`$1`
`foo$`
` \n@ALL\`::´äöüß`
```
All of the above will be invalid without the backticks.

**Comment by jsteemann** [comment]
Updated documentation.
