### ISSUE TITLE
Installation into non standart path fails for non root users

### ISSUE THREAD

**Issue by MalkmusT** [arangodb/arangodb#1780]
Installation of arangodb from source, using the current master branch, into a non standart path fails.
On my debian strech machine i cloned the current master and performed 
`mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=/SOME/PATH/ .. && make && make install`
to install arangodb into `/SOME/PATH/`
The following error showed up:
CMake Error at cmake_install.cmake:68 (file):
  file INSTALL cannot copy file
  "/home/tomalk/modules/arangodb/Installation/debian/arangodb.init" to
  "/etc/init.d/arangodb".

For me:
diff --git a/cmake/ArangoDBMacros.cmake b/cmake/ArangoDBMacros.cmake
index 96f519c..b460e60 100644
--- a/cmake/ArangoDBMacros.cmake
+++ b/cmake/ArangoDBMacros.cmake
@@ -396,7 +396,7 @@ set(CPACK_PROJECT_CONFIG_FILE "${CMAKE_BINARY_DIR}/CMakeCPackOptions.cmake")
 install(
   FILES ${PROJECT_SOURCE_DIR}/Installation/debian/arangodb.init
   PERMISSIONS OWNER_READ OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE
-  DESTINATION /etc/init.d
+  DESTINATION etc/init.d
   RENAME arangodb
   COMPONENT debian-extras
 )

 solved the problem.

**Comment by dothebart** [comment]
Thanks for reporting. If you find any more glitches in our new Cmake environment, please let us know ;-)
