### ISSUE TITLE
Not supported on this server type

### ISSUE THREAD

**Issue by sergiorpires** [arangodb/arangodb#17848]
## My Environment

* __ArangoDB Version__:        3.10.1 Community Edition
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   ArangoDB Starter
* __Operating System__:        Windows 11
* __Total RAM in your machine__:    16Gb
* __Disks in use__:        SSD
* __.NET 6, C#

## Steps to reproduce

string _dbname = "name";
string _address = "address";
string _username = "user";
string _password = "pwd";

HttpApiTransport? transport = HttpApiTransport.UsingBasicAuth(new Uri(_address), _dbname, _username, _password);
ArangoDBClient? client; = new ArangoDBClient(transport);

PostTransactionRequestCollections rc = new();
rc.Read = new List<string>() { "users" };

StreamTransactionBody stb = new();
stb.Collections = rc;

ApiHeaderProperties ahp = new();
ahp.TransactionId = "1001";

**await client!.Transaction.BeginTransaction(stb, ahp);**

var query = "FOR u IN users RETURN u";
CursorResponse<users> response = await client!.Cursor.PostCursorAsync<users>(query, transactionId: "1001");

if ((int)response.Code >= 200 && (int)response.Code <= 299)
{
    await client!.Transaction.CommitTransaction("1001");
}
else
{
    await client!.Transaction.AbortTransaction("1001");
}

__Problem__:
When I run this C# code, it breaks on the BeginTransaction with:
Code=400 Error=True ErrorNum=9 ErrorDescription=ERROR_NOT_IMPLEMENTED ErrorMessage=Not supported on this server type

I can't find any reason the code is breaking. Help is needed, please!

**Comment by dothebart** [comment]
are you directly accessing the dbserver? 
You need to talk to the coordinator.

**Comment by sergiorpires** [comment]
I'm using HttpClient C# driver.
I can't see how to do it.
Do you have some reference or example?


Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by tjoubert** [comment]
Hi @sergiorpires ,

The server should generate the transaction id. 

Please try the following:

Remove these lines
```
StreamTransactionBody stb = new();
stb.Collections = rc;

ApiHeaderProperties ahp = new();
ahp.TransactionId = "1001";
```
Change `await client!.Transaction.BeginTransaction(stb, ahp);` to 
`var tranRes = await client!.Transaction.BeginTransaction(stb);`

Then, change the the value of the transaction id parameter passed to `PostCursorAsync()`, `CommitTransaction()` and `AbortTransaction()` to `tranRes.Result.Id`.

Let me know if the above solves the problem.

Regards

Terence

**Comment by sergiorpires** [comment]
It worked! Obviously, it is just a code to learn how to use transactions, and now I'm gonna use it in a real scenario. Thanks a lot. This is the working code:

PostTransactionRequestCollections rc = new();
rc.Read = new List<string>() { "users" };

StreamTransactionBody stb = new();
stb.Collections = rc;

StreamTransactionResponse? tranRes = await client!.Transaction.BeginTransaction(stb);

var query = $"FOR u IN users RETURN u";
CursorResponse<users> response = await client!.Cursor.PostCursorAsync<users>(query, transactionId: tranRes.Result.Id);

if ((int)response.Code >= 200 && (int)response.Code <= 299)
{
    await client!.Transaction.CommitTransaction(tranRes.Result.Id);
}
else
{
    await client!.Transaction.AbortTransaction(tranRes.Result.Id);
}

Regards,
Sergio
________________________________
De: Terence Joubert ***@***.***>
Enviado: terça-feira, 20 de dezembro de 2022 13:19
Para: arangodb/arangodb ***@***.***>
Cc: Sergio Ricardo Pires ***@***.***>; Mention ***@***.***>
Assunto: Re: [arangodb/arangodb] Not supported on this server type (Issue #17848)


Hi @sergiorpires<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsergiorpires&data=05%7C01%7C%7Cecc423a18ddb42d306bf08dae2a5ec2a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638071499510993637%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5SBloQlFy2KI8omwmb2x36lxqg5oA5G8jQCML%2FzRIfA%3D&reserved=0> ,

The server should generate the transaction id.

Please try the following:

Remove these lines

StreamTransactionBody stb = new();
stb.Collections = rc;

ApiHeaderProperties ahp = new();
ahp.TransactionId = "1001";


Change await client!.Transaction.BeginTransaction(stb, ahp); to
var tranRes = await client!.Transaction.BeginTransaction(stb);

Then, change the the value of the transaction id parameter passed to PostCursorAsync(), CommitTransaction() and AbortTransaction() to tranRes.Result.Id.

Let me know if the above solves the problem.

Regards

Terence

**Comment by dothebart** [comment]
https://github.com/arangodb/arangodb/pull/17851/files would this error message have made you comprehend on your own whats wrong with your current situation? 
(the first one is the one you got)

**Comment by sergiorpires** [comment]
In fact, I received "Not supported on this server type" and nothing more. But if the answer was "unexpected transaction ID received in begin transaction request", I would understand it easily.

**Comment by dothebart** [comment]
thanks for confirming!
