### ISSUE TITLE
How to filter a 2 level nested array

### ISSUE THREAD

**Issue by sergiorpires** [arangodb/arangodb#17867]
## My Environment

* __ArangoDB Version__:        3.10.1
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   ArangoDB Starter
* __Operating System__:        Windows 11
* __Total RAM in your machine__:        16Gb.
* __Disks in use__:        SSD

## Component, Query & Data

__Affected feature__: AQL query using web interface

__AQL query__:
FOR m IN modules
FILTER m.moduleRights[\*].operations[\*].operationId == 1
RETURN m

__AQL return__:
[]

__Dataset__:
{
  "moduleId": 1,
  "module": "System",
  "moduleRights": [
    {
      "rightId": 1,
      "right": "Update",
      "operations": [
        {
          "operationId": 1,
          "operation": "Update System",
        },
        {
          "operationId": 2,
          "operation": "Verify",
        }
      ]
    }
  ]
}

__Problem__:
I need to know how to query a 2 level (or more) nested array.

__Expected result__:
In this example it is expected to receive the entire document.

Help needed!

**Comment by sergiorpires** [comment]
The answer in fact is pretty simple, but I have not realized:

FOR m IN modules
FILTER m.moduleId == 1
FOR r IN m.moduleRights
FILTER r.rightId == 1
FOR o IN r.operations
FILTER o.operationId == 1
RETURN o

.

**Comment by dothebart** [comment]
Please note that this is what the SQL-World calls "Joins" and hence is documented under this topic:
https://www.arangodb.com/docs/stable/aql/examples-join.html
