### ISSUE TITLE
Slack as public chat?

### ISSUE THREAD

**Issue by sinfex** [arangodb/arangodb#1787]
How about having contributors join ArangoDB on Slack (using [slackin](http://rauchg.com/slackin/))?

**Comment by weinberger** [comment]
We are working on that, stay tuned :)

Dave schrieb:

**Comment by NinoFloris** [comment]
Gitter would be alright as well :)

**Comment by pluma** [comment]
@NinoFloris we have had a Gitter chatroom but it is no longer active.

**Comment by MrPieces** [comment]
Hi @sinfex as promised.... yesterday we launched our Slack Channel and many people joined already! If you´d like to share your ideas or want a free workshop for your european community it´s the place to go.

You can find it here: https://arangodb-community.slack.com

**Comment by weinberger** [comment]
This is the right link: https://slack.arangodb.com

**Comment by mfractal** [comment]
https://slack.arangodb.com/ returns 500 error.

**Comment by Simran-B** [comment]
@mfractal Please use https://arangodb-community.slack.com/

**Comment by pablovisual** [comment]
how do i join every time i use my email i get error saying my email isn't associated with the group
