### ISSUE TITLE
Why are empty arrays considered true in AQL

### ISSUE THREAD

**Issue by jurrian** [arangodb/arangodb#1788]
I noticed something when I ran a query similar to this one lately:
```
LET empty_array = (
  FOR person in persons
    FILTER person.name == 'asdfasdfw5235235' // Non-existing user returing empty array
  RETURN person
)

RETURN empty_array || 'default'
```
Result: []
Expected result: 'default'

One would expect that the 'default' string would take precedence over an empty array.
I know that "RETURN LENGTH(empty_array) > 0 ? empty_array : 'default'" would do the job but that feels way to cumbersome for such a stylistic language like AQL.

The current behavior is explained in the [AQL operators](https://docs.arangodb.com/Aql/Operators.html) section:
> arrays ([ ]) and objects / documents ({ }) are true, regardless of their contents

Why are empty arrays considered true?
Is there any logic to why it shouldn't be false when empty, and true when populated?

**Comment by dsonet** [comment]
@jurrian  I guess maybe because they follow the behavior of JavaScript.
It would be good to have an explanation why do this way.

**Comment by jurrian** [comment]
What I proposed is very common in high level languages like Python and Ruby:

Python: return empty_array or "default"
Ruby: abc = empty_array || 'default'

My use case is that I have two subqueries and either one of them is empty.
I think it would be quite elegant to be able to do:

RETURN this || that

**Comment by Simran-B** [comment]
What you can do in current AQL:

```js
RETURN LENGTH([]) ? "use array" : "default"
```

It actually returns "default" for empty arrays, empty objects, zero-length strings, null and false. And does not for the number 0 however, you would need to add a second condition for this:

```js
LET var = 0
RETURN (var && LENGTH(var)) ? "use var" : "default"
```

**Comment by dsonet** [comment]
@Simran-B Ya, to someone who knows JavaScript, that's seems obviously. :)

**Comment by jurrian** [comment]
I understand that it would not be a interesting feature considering backwards compatibility.
Still I regret that there is no elegant shorthand for this..

Having said that, I thank you all for considering and for the nearest solution by @Simran-B

**Comment by Simran-B** [comment]
With the 3.0 release on the horizon, we could actually break backward compatibility - now or never. What speaks against a change in this matter is rather that there's no clear right or wrong. JavaScript scripters expect an empty array to be truthy, whereas Python programmers don't. There are a lot of corner cases which are not well defined... is an array with a single member, which is an empty string supposed to be falsy? Lots of different opinions on that I bet.

If you can provide a good rationale though, we can consider a change.

**Comment by pluma** [comment]
Unless ArangoDB is moving away from JS any time soon, I would strongly veto any change that makes the AQL type system less compatible with JS.

**Comment by Simran-B** [comment]
@pluma: Inversely, do you want AQL to move closer to JS? The array accessor doesn't work on strings currently (`"foo"[0]`) and string concatenation as in `"foo" + "bar"` doesn't work either. I don't think we need this (there are `SUBSTRING()` and `CONCAT()`), but I wanted to bring it up.

It's probably not a good idea to add these features, because it might make strings iterable in general and introduce weird implicit casting behavior to AQL.

**Comment by pluma** [comment]
@Simran-B I agree. The semantics are good the way they are (after the document/object-to-boolean conversion fix). The potential for surprise in those differences seems rather minimal compared to having different semantics of what boolean values various types convert to.

**Comment by Simran-B** [comment]
To wrap this up:

Whether an empty array should be considers truthy or falsey is a matter of taste. In JS and Ruby they are true, in PHP they are not. There is no right or wrong. The behavior of how this is handled in AQL is documented and there's no good reason to change this behavior, which is in line with JS, by which AQL is influenced.
