### ISSUE TITLE
Bug: AQL SHORTEST_PATH options 'distance' type as attribute not working

### ISSUE THREAD

**Issue by baslr** [arangodb/arangodb#1790]
ArangoDB v2.8.5
The option `distance` as an attribute does not work in AQL function `SHORTEST_PATH`

```
return SHORTEST_PATH(wikigraph, articleRefsTo,
'wikigraph/8798260827819', 'wikigraph/8833098585771', 
'outbound', {includeData:true, defaultDistance:1, distance:'_key'})
```

https://docs.arangodb.com/Aql/GraphFunctions.html
distance: two different types; either be the name of an attribute; Using a distance attribute is only allowed in combination with defaultDistance.

result is:
```
user function '_KEY()' not found stacktrace of offending AQL function: ArangoError: user function '_KEY()' not found at THROW 
(/Applications/ArangoDB.app/Contents/Resources/opt/arangodb/share/arangodb/js/server/modules/org/arangodb/aql.js:423:13) at FCALL_USER 
(/Applications/ArangoDB.app/Contents/Resources/opt/arangodb/share/arangodb/js/server/modules/org/arangodb/aql.js:966:5) at Object.SHORTEST_PATH_PARAMS.params.distance 
(/Applications/ArangoDB.app/Contents/Resources/opt/arangodb/share/arangodb/js/server/modules/org/arangodb/aql.js:6420:14) at Object.run 
(/Applications/ArangoDB.app/Contents/Resources/opt/arangodb/share/arangodb/js/common/modules/org/arangodb/graph/traversal.js:1250:29) at ArangoTraverser.traverse 
(/Applications/ArangoDB.app/Contents/Resources/opt/arangodb/share/arangodb/js/common/modules/org/arangodb/graph/traversal.js:1770:14) at TRAVERSAL_FUNC 
(/Applications/ArangoDB.app/Contents/Resources/opt/arangodb/share/arangodb/js/server/modules/org/arangodb/aql.js:6078:15) at Object.AQL_SHORTEST_PATH 
(/Applications/ArangoDB.app/Contents/Resources/opt/arangodb/share/arangodb/js/server/modules/org/arangodb/aql.js:6455:13) at Function.<anonymous> (--script--:1:146) (while executing) 
```

**Comment by Simran-B** [comment]
Arango seems to interpret the distance attribute value as user function name, which is one of two ways to use the distance attribute. I'm not exactly sure how to use this however - does it always expect a string? But how does it distinguish between function and attribute names then? There could be a bug here...

Anyway, you do have an error in your code: `_key` is never numeric. The internal key property of a document is always a string. Strings can't be used to calculate distances.

**Comment by jsteemann** [comment]
Looks like the documentation is wrong here.
The docs say `distance` can either be a function name or the name of an attribute, but in reality `distance` is always treated as a function name.
The alternative way of specifying a distance attribute and a default distance for cases when the attribute is not present is via specifying the options `weight` and `defaultWeight` (not `distance` and `defaultDistance`). Looks like the docs have been wrong since the SHORTEST_PATH function was around.

So the query should work like this:
```
RETURN SHORTEST_PATH(wikigraph, articleRefsTo, 'wikigraph/8798260827819', 'wikigraph/8833098585771',  'outbound', {includeData:true, defaultWeight:1, weight: 'key' })
```
Please note that `_key` will probably not work when specified for `weight`, because the `_key` attribute may contain non-numeric values.

**Comment by jsteemann** [comment]
Documentation has been adjusted via commit b42910f1a963c638ff95c83cb3946dc4308a0b2b.
The next regular documentation build will publish the documentation changes.

**Comment by baslr** [comment]
thanks for correction / fixing. Works now as intended. :+1: 

Yeah I used _key because it will be always incorrect and so defaultWeight is used ;)
