### ISSUE TITLE
AQL Full Text Search fails when has \n in the text

### ISSUE THREAD

**Issue by leowmjw** [arangodb/arangodb#1799]
Was attempting to debug why my full text search was failing when I am trying to look for the hash character (#).  

Came up with a simple test case statements that I tried through AQL Editor 2.8.6:

This FAILs, due to the \n (although it passes JSONLinter, and also through jq:
```
FOR a IN [{ "_key": "12", "description": "Dude!"}, { "_key": "13", "description": "Poor Road Condition #RespectMyPM Road Condition in this location are very poor. So many holes across the street. Almost 15 years the road never been repaired. Water not flowing due to the holes on the road during rainy days.\n\nExact Location: Lorong Kenari 10/3A, Taman Kenari, 09000 Kulim, Kedah"}]
    FILTER LIKE(LOWER(a.description), '%#%')
    RETURN [ a._key, a.description ]
 
```

This works (when further escape the \n char):
```
FOR a IN [{ "_key": "12", "description": "Dude!"}, { "_key": "13", "description": "Poor Road Condition #RespectMyPM Road Condition in this location are very poor. So many holes across the street. Almost 15 years the road never been repaired. Water not flowing due to the holes on the road during rainy days.\\n\\nExact Location: Lorong Kenari 10/3A, Taman Kenari, 09000 Kulim, Kedah"}]
    FILTER LIKE(LOWER(a.description), '%#%')
    RETURN [ a._key, a.description ]
 
```

Shouldn't the Full Text Succeed as long as the content is proper JSON?

Additional Info: Data was added via arrangoimp (from ArrangoDB App); OSX 10.9 Maverick

**Comment by dothebart** [comment]
Confirmed. Minimal pattern to reproduce this:

     db._query('RETURN LIKE("foo #foo bar", "%#%")') ->true 
    db._query('RETURN LIKE("foo #foo \\n bar", "%#%")') -> false

**Comment by dothebart** [comment]
fixed with 054b4e6a7c9623ff5984b1055299f92170182695 54efbea4ef692449c5933fb37164000044d42fcc and 1b41f5c0bbd6e717ef5fe3a857bc3ac0a0033ef8 . Will be part of the next ArangoDB 2.8 release (2.8.8) which will be released within the next 14 days. You can checkout & compile the 2.8 branch yourself if you can't wait that long.

**Comment by leowmjw** [comment]
Thanks @dothebart; I'll wait for 2.8.8

**Comment by Simran-B** [comment]
The fix works well. But I discovered more problematic characters:

```js
RETURN LIKE("\\", "\\") // false
RETURN LIKE("foo%bar", "foo\%") // true
RETURN LIKE("foo%bar", "foo\u0025") // true
```

This works, but it is at least counter-intuitive: `LIKE("foo%bar", "foo\\%") // false`

**Comment by dothebart** [comment]
meanwhile these were released, so we can close this now.
