### ISSUE TITLE
the arangodb command isn`t exist after recompiling the arangodb

### ISSUE THREAD

**Issue by codermichele** [arangodb/arangodb#18043]
Hello, when I try to compiled the arangodb project in aarch64, I found that the arangodb command isn`t exist.

The part of structure of directories after executing "make install" are as follow:
```
.
├── etc
│   └── logrotate.d
│       └── arangodb3
├── structreOfDir.log
└── usr
    ├── bin
    │   ├── arangobench
    │   ├── arangodump
    │   ├── arangoexport
    │   ├── arangoimp -> arangoimport
    │   ├── arangoimport
    │   ├── arangoinspect -> arangosh
    │   ├── arangorestore
    │   ├── arangosh
    │   ├── arangovpack
    │   └── foxx-manager -> arangosh
     ── etc
    │   └── arangodb3
    │       ├── arangobench.conf
    │       ├── arangod.conf
    │       ├── arangodump.conf
    │       ├── arangoexport.conf
    │       ├── arangoimport.conf
    │       ├── arango-init-database.conf
    │       ├── arangoinspect.conf
    │       ├── arangorestore.conf
    │       ├── arango-secure-installation.conf
    │       ├── arangosh.conf
    │       ├── arangovpack.conf
    │       └── foxx-manager.conf
    ├── sbin
    │   ├── arangod
    │   ├── arango-init-database -> arangod
    │   └── arango-secure-installation -> arangod
```
as showing above, the arangodb commond isn`t exist in "usr/bin" compared with "arangodb3-linux-3.10.3_x86_64.tar.gz", I can`t figure out, somebody could answer me?

**Comment by dothebart** [comment]
Hi, 
The `arangodb` starter binary lives in a separate project, since it basically doesn't follow the branching mechanism of the arangod & arangosh binaries, but rather is allways "the latest" version available in the time being.
It lives here: https://github.com/arangodb-helper/arangodb and requires a go-toolchain to be built.

**Comment by codermichele** [comment]
>thanks.
