### ISSUE TITLE
Computed Values become null when Schema is modified

### ISSUE THREAD

**Issue by fgnm** [arangodb/arangodb#18053]
## My Environment

* __ArangoDB Version__: 3.10.3       
* __Deployment Mode__: Single Server      
* __Deployment Strategy__: ArangoDB Starter in Docker  
* __Configuration__:               
* __Infrastructure__: own              
* __Operating System__: Ubuntu 20.04.4       
* __Total RAM in your machine__:  8GB      
* __Disks in use__: SSD       
* __Used Package__:  Docker - official Docker library            

## Component, Query & Data

__Affected feature__:

Computed Values

## Steps to reproduce

1. Create a new collection
2. Add a Schema
3. Add Computed Values
4. Edit Schema
5. Return to Computed Values

__Problem__:
Computed Values always become null whenever a the schema is saved (even if no changes happens).

__Expected result__:
Save Computed Values state when the Schema is modified/saved.

**Comment by jsteemann** [comment]
Confirmed. Should be fixed via https://github.com/arangodb/arangodb/pull/18057.

**Comment by Simran-B** [comment]
v3.10.4 includes a fix and has been released (meanwhile also 3.10.5)
