### ISSUE TITLE
Strange results on attribute access if period in attribute key

### ISSUE THREAD

**Issue by Simran-B** [arangodb/arangodb#1806]
Stumbled upon some weird behavior if an attribute with a dot in it is accessed à la `doc["foo.bar"]`. Results are partially different between Windows and Linux (Windows 10 / CentOS 7), but both platforms are erroneous.

Tested with official v2.8.7 release. I couldn't test 3.0.x properly, but at first sight, it seems to be working as expected (VPack might've gotten rid of the buggy code pieces).

Plain document collection, no indexes, no waitForSync or anything. I also tried a "broken" one in Arangosh, but gave me the same result (so apparently not an issue with Aardvark).
# Test data

A simple document with a period in the attribute key:

``` json
{
    "foo.bar": "baz"
}
```

Create with query like: `INSERT {"foo.bar": "baz"} INTO coll RETURN NEW`
# Windows / ArangoDB 2.8.7
## Query A (no bind parameters)

BROKEN - Attribute "foo.bar" is null, but listed in full document

``` js
FOR doc IN coll
    FILTER HAS(doc, "foo.bar")
    LIMIT 1
    RETURN {
        "foo.bar.1": doc["foo.bar"],
        `foo.bar.2`: doc.`foo.bar`,
        doc
    }
```

``` json
[
  {
    "foo.bar.1": null,
    "foo.bar.2": null,
    "doc": {
      "foo.bar": "baz",
      "_id": "coll/380180346",
      "_rev": "11611326253",
      "_key": "380180346"
    }
  }
]
```
## Query B (with bind parameters)

BROKEN - Attribute "foo.bar" is "baz", also listed in full document - but why does the precense of bind paramters fix this for all styles of attribute access?

``` js
FOR doc IN coll
    FILTER HAS(doc, "foo.bar")
    LIMIT 1
    RETURN {
        "foo.bar.1": doc["foo.bar"],
        `foo.bar.2`: doc.`foo.bar`,
        @key1: doc.@value,
        @key2: doc[@value],
        doc
    }
```

``` json
{"key1": "foo.bar.3", "key2": "foo.bar.4", "value": "foo.bar"}
```

``` json
[
  {
    "doc": {
      "_id": "coll/380180346",
      "_key": "380180346",
      "_rev": "11611326253",
      "foo.bar": "baz"
    },
    "foo.bar.1": "baz",
    "foo.bar.2": "baz",
    "foo.bar.3": "baz",
    "foo.bar.4": "baz"
  }
]
```
## Query C (DOCUMENT(), same w/wo bind parameters)

OK - Attribute "foo.bar" is "baz" and also listed in full document

``` js
LET doc = DOCUMENT("coll/380180346")
RETURN {
    "foo.bar.1": doc["foo.bar"],
    `foo.bar.2`: doc.`foo.bar`,
    doc
}
```

``` json
[
  {
    "foo.bar.1": "baz",
    "foo.bar.2": "baz",
    "doc": {
      "foo.bar": "baz",
      "_id": "coll/380180346",
      "_rev": "11611326253",
      "_key": "380180346"
    }
  }
]
```
# CentOS / ArangoDB 2.8.7
## Query A (no bind parameters)

BROKEN - Attribute "foo.bar" is null, but listed in full document (same as on Windows)

``` js
FOR doc IN coll
    FILTER HAS(doc, "foo.bar")
    LIMIT 1
    RETURN {
        "foo.bar.1": doc["foo.bar"],
        `foo.bar.2`: doc.`foo.bar`,
        doc
    }
```

``` json
[
  {
    "foo.bar.1": null,
    "foo.bar.2": null,
    "doc": {
      "foo.bar": "baz",
      "_id": "coll/380180346",
      "_rev": "380180346",
      "_key": "380180346"
    }
  }
]
```
## Query B (with bind parameters)

BROKEN - Attribute "foo.bar" is null and also **not** listed in full document (different from Windows!)

``` js
FOR doc IN coll
    FILTER HAS(doc, "foo.bar")
    LIMIT 1
    RETURN {
        "foo.bar.1": doc["foo.bar"],
        `foo.bar.2`: doc.`foo.bar`,
        @key1: doc.@value,
        @key2: doc[@value],
        doc
    }
```

``` json
{"key1": "foo.bar.3", "key2": "foo.bar.4", "value": "foo.bar"}
```

``` json
[
  {
    "foo.bar.1": null,
    "foo.bar.2": null,
    "foo.bar.3": null,
    "foo.bar.4": null,
    "doc": {
      "_id": "coll/380180346",
      "_rev": "380180346",
      "_key": "380180346"
    }
  }
]
```
## Query C (DOCUMENT(), same w/wo bind parameters)

OK - Attribute "foo.bar" is "baz" and also listed in full document (same as on Windows)

``` js
LET doc = DOCUMENT("coll/380180346")
RETURN {
    "foo.bar.1": doc["foo.bar"],
    `foo.bar.2`: doc.`foo.bar`,
    doc
}
```

``` json
[
  {
    "foo.bar.1": "baz",
    "foo.bar.2": "baz",
    "doc": {
      "foo.bar": "baz",
      "_id": "coll/380180346",
      "_rev": "380180346",
      "_key": "380180346"
    }
  }
]
```

**Comment by jsteemann** [comment]
The document shaper and some other code parts in 2.8 will split attribute names at `.`, meaning the dot symbol inside attribute names is handled ambiguously. 
3.0 should fix all that, as all the above queries work in 3.0 properly.

**Comment by dothebart** [comment]
@Simran-B will write some tests for this.

**Comment by dothebart** [comment]
re-labeling since its fixed, and only tests are missing.
