### ISSUE TITLE
Graph functions parameters inconsistency

### ISSUE THREAD

**Issue by roman1720** [arangodb/arangodb#1807]
Some graph function for example GRAPH_ABSOLUTE_BETWEENNESS doesn't have all parameters as other functions have (GRAPH_ABSOLUTE_ECCENTRICITY). Without vertexExample and edgeExamples parameters functions can't be used on subgraphs.

**Comment by dothebart** [comment]
In general these functions provide answers that can only be given at a huge cost. So these barely work on an all connected graph with a few hundred nodes. Some of the parameters have been removed as they provided limited value. In general, these functions live in *js/server/modules/@arangodb/aql.js*, so feel free to start hacking about and share your results with us ;-)

**Comment by dothebart** [comment]
The `GRAPH_*()` functions have been replaced with a new implementation in the pattern matching traverser in 3.0: https://docs.arangodb.com/3.0/AQL/Graphs/ShortestPath.html

We also prepared a cookbook howto upgrade existing queries:
https://docs.arangodb.com/cookbook/AQL/MigratingGraphFunctionsTo3.html

If you have troubles migrating queries to the new nomenclatur feel free to [Ask on Stackoverflow](http://stackoverflow.com/questions/tagged/arangodb), or open another ticket.

ArangoDB 3.0 RC2 containing the new shortest path implementation is available for download via:
https://www.arangodb.com/download-preview/

Closing.
