### ISSUE TITLE
/_api/log (RestLogHandler) documentation

### ISSUE THREAD

**Issue by olegrok** [arangodb/arangodb#18081]
Hi! I see that there is an API /_api/log that allows to manipulate with replication2/logs (https://github.com/arangodb/arangodb/blob/devel/arangod/RestHandler/RestLogHandler.cpp). But there is no any documentation for it (at least in devel branch) and tests cover this part quite poorly.

Is there any description for such API (probably with some internal details)?

Also on attempt to create new log entry with POST on /_db/_system/_api/log `{"id": 2, "config": null}` I got following error:
```
dbserver6001 2023-02-09T16:33:22Z [26938] INFO [e094b] {replication2} [database-name=_system, log-id=2, term=1, leader-id=PRMR-2edeeb3f-4eb7-485b-a8be-a496496b796f, log-component=follower-info, follower-id=PRMR-7939f43c-6c50-49b3-9657-ad574cd01929] exception in appendEntries to follower PRMR-7939f43c-6c50-49b3-9657-ad574cd01929: replicated log 2 not found
```

How can I avoid it or is this message really needed and should help me with some issues?

**Comment by dothebart** [comment]
please note that replication2 is still work in progress, so nothing to see here yet.

**Comment by apetenchea** [comment]
Hi @olegrok!

As @dothebart pointer out, the API you're referring to is currently under active development. We believe it's in the best interest of our users to provide documentation for stable features only, to avoid any confusion. More so, this is an internal API that we use for our own development, and its implementation could change at any time. As such, it's not intended to be used by clients and currently we don't to provide public documentation for it.

We encourage you to use our officially documented APIs for any integrations you want to make. You can it [here](https://www.arangodb.com/docs/stable/http/).
