### ISSUE TITLE
"Random" slow queries

### ISSUE THREAD

**Issue by petitchevalroux** [arangodb/arangodb#1810]
We have issues with "randomly" slow queries on a single arango instance. We use batch for document multi-fetch and multi-update. We also have some document fetch/update as you can see below with HTTP methods.

On 1 706 066 queries :

1704929 http status 200
1021 http status 202
116 http status 404

62421 "GET" (document fetch)
1642624 "POST" (batch request)
1021 "PUT" (document update)

Our average request time is 15 ms.

190 queries are slow (> 3 seconds) :

33 "GET"
157 "POST"

All "slow" requests are 200

We didn't care about slow POST as it may update/fetch thousand docs and they are running on async daemon. But the 33 GET didn't match our < 3 seconds requirements.

Things we tried : 
    We tried to disable stats => no effect
    Decresse GET (divided by 2) by removing GET on collection => no effect
    Increase scheduler threads to 24 => no effect
    Increase javascript v8-contexts to 16 => no effect

We are using arango 2.8.7 without replication: only one server.

Attached files are :
Arangodb conf file:  [arangod.conf.txt](https://github.com/arangodb/arangodb/files/242134/arangod.conf.txt)
Slow queries request logs: [all-slow-requests.txt](https://github.com/arangodb/arangodb/files/242133/all-slow-requests.txt)
Request log extract when slow queries occured: [requests-slow-event.txt](https://github.com/arangodb/arangodb/files/242132/requests-slow-event.txt)

**Comment by Simran-B** [comment]
What is your environment? (e.g. Mac OS X 10.11, 8 GB RAM, 128 GB SSD)

I assume waitForSync is set to false (default)?

**Comment by petitchevalroux** [comment]
Linux SMP Debian 3.2.73-2+deb7u2 x86_64 GNU/Linux
Intel(R) Xeon(R) CPU E5645 @ 2.40GHz
32 Go RAM
Debian 7.10
RAID 1 1To SATA 7200 rpm
Wait For Sync to false
Here are our documents collection info
![capture d ecran 2016-04-29 17 26 19](https://cloud.githubusercontent.com/assets/1106867/14920830/855d8504-0e2f-11e6-8a79-95807432d148.png)
![capture d ecran 2016-04-29 17 26 10](https://cloud.githubusercontent.com/assets/1106867/14920828/855bf3b0-0e2f-11e6-9bc1-42ac69b36b38.png)
![capture d ecran 2016-04-29 17 25 57](https://cloud.githubusercontent.com/assets/1106867/14920829/855c12b4-0e2f-11e6-875b-cd5add848205.png)

**Comment by petitchevalroux** [comment]
253736 document(s)

**Comment by baslr** [comment]
![linux_observability_tools](https://cloud.githubusercontent.com/assets/1494154/14926450/93c4862a-0e4c-11e6-8eb7-0b366e822a0b.png)
I would like to share this graphic with you. Did you have e. g. some other metrics from the host to correlate these with your slow queries?

**Comment by baaum** [comment]
Unfortunately no system metrics can be correlated with these slow queries.
Furthermore, by studying requests log file, as you can see below we notice that slow HTTP requests are random (unable to correlate with system metrics, specific arango threads or particular data...)

[2016-05-05T13:27:54.txt](https://github.com/arangodb/arangodb/files/245180/2016-05-05T13.27.54.txt)

arangodb datas are saved on a dedicated XFS partition

**Comment by baslr** [comment]
How about to increase logging to see what happens before the 3secs queries?

**Comment by baaum** [comment]
Sorry for the delay,

We don't notice anything special,
except batch requests (POST _api/batch) during the period we see some slow GET requests (> 3s)
Do you think it would be interesting to replace these batch requests by individual POST requests ?

[requests.log extract](https://github.com/arangodb/arangodb/files/262393/123.txt)

**Comment by baaum** [comment]
I forgot to mention that our arangodb instance host : 8 databases with 1 document collection for each database

**Comment by baslr** [comment]
@baaum can you upgrade to jessie w/ back ported kernel or upgrade to the back ported 3.16 kernel?

**Comment by baslr** [comment]
@baaum @petitchevalroux did you investigated it further or found the cause?

**Comment by petitchevalroux** [comment]
@baslr
we upgraded to arango new version without major improvement.
we removed our batch queries and read timeout mostly disappeared.

At the moment, we only have small amounts of PATCH timeout but it's ok for our use case.
