### ISSUE TITLE
ArangoDB's yum repo mirrors not working

### ISSUE THREAD

**Issue by lovepreetkaul** [arangodb/arangodb#1812]
Hi, 
I was trying to install ArangoDB using the yum repo provided on the downloads page for Cent OS. It is failing as the mirrors are not accepting connections.

**Comment by dothebart** [comment]
Can you please provide a little more details? which CentOS version? Which architecture? x64? I currently don't have a centos at hand, so I could only try to download the repo file, the xml key, and an example rpm, which all succeeded for me.

**Comment by lovepreetkaul** [comment]
I tried it on Cent OS 7 x64. I was able to download the repo file, and then at yum update gives the following error:-
failure: repodata/primary.xml.gz from arangodb: [Errno 256] No more mirrors to try.
https://www.arangodb.com/repositories/arangodb2/CentOS_7/repodata/primary.xml.gz: [Errno -1] Metadata file does not match checksum

Please let me know if I am missing something on my end. Thanks.

**Comment by rmg** [comment]
There are checksum failures on the apt repos too
```
W: Failed to fetch https://www.arangodb.com/repositories/arangodb2/Debian_8.0/Packages  Hash Sum mismatch
```

**Comment by dothebart** [comment]
this seems to be related to https://github.com/openSUSE/obs-sign/issues/5 - old SHA1 signatures.

**Comment by dothebart** [comment]
We will tackle this with the  ArangoDB 3.1 release cycle.

**Comment by dothebart** [comment]
Can you retry whether the problem persists with the ArangoDB 3.1 repositories?

**Comment by dothebart** [comment]
since the .deb packages signatures work well now, this should also be fixed. please report back if not.
