### ISSUE TITLE
Disabling legacyPolygons flag (on geo index) significantly slows down data insertions

### ISSUE THREAD

**Issue by cjrmtq** [arangodb/arangodb#18156]
## My Environment

* __ArangoDB Version__:  3.10.3 / latest build on DockerHub
* __Deployment Mode__:  Single server
* __Deployment Strategy__:   ArangoDB Starter in Docker
* __Configuration__:  Vanilla setup
* __Infrastructure__:  Own laptop
* __Operating System__:  Ubuntu 22.04
* __Total RAM in your machine__: 16Go
* __Disks in use__:  SSD
* __Used Package__:  [this image on DockerHub](https://hub.docker.com/layers/library/arangodb/latest/images/sha256-6d636e4c35f07d60f94a200c4aeb415e899881951037a7f1e8f8f2ff1bdfc108)

## Component, Query & Data

__Affected feature__: Loading data using `/_api/import` endpoint, when there is a Geo index set.

__Dataset__: See attached `test_issue_legacy_polygons.json` file.

__Size of your Dataset on disk__: 3.3Mo

## Steps to reproduce

1. Start an ArangoDb container, like this: `docker run -e ARANGO_ROOT_PASSWORD=root -p 8529:8529 -d  arangodb:latest`
2. Download both dataset and my custom test to reproduce the bug (`test_issue_legacy_polygons.json` and `reproduce_issue.py`)
3. Execute `reproduce_issue.py`. This script will:

- Create a test database
- Create two collections for testing purpose
- For the first collection, create a geo index with the `legacyPolygons` flag enabled, and for the second one, disable the flag.
- Import data in both collections

You should have a return like this:

```
Import data in 0.5266s with legacyPolygons = True on issue_legacy_polygons_True_collection
Import data in **44.5996s** with legacyPolygons = False on issue_legacy_polygons_False_collection
```

__Problem__:

As you can see in this prompt, loading data using flag `legacyPolygons = True` when setting the geo index is very fast, compared to the new method (with `legacyPolygons = False`) which is very slow (**x85 slower**).

__Expected result__:

At least, same computing time between the two methods.

@neunhoef : maybe you can have some clues as you seem to be the writer of the PR introducing this flag? (ref: https://github.com/arangodb/arangodb/pull/14723)

Thanks for your help!

**[You can download here the files to reproduce this issue (python file and small dataset).](https://github.com/arangodb/arangodb/files/10785731/reproduce_issue_archive.zip)**

**Comment by MBkkt** [comment]
Hello, your polygons don't follow right hand rule.

So instead of index your small polygons you index polygons which are bigger than half world.

Common fix (if all your polygons in which format) just reverse vertices in polygons loop

**Comment by cjrmtq** [comment]
Oh boy! Thanks, I'm so sorry for not seeing that.

**Comment by dothebart** [comment]
putting a link to the relevant documentation here for later browsers of this ticket:
https://www.arangodb.com/docs/stable/indexing-geo.html#geojson-interpretation
;-)
