### ISSUE TITLE
Update inside a for loop use old value

### ISSUE THREAD

**Issue by simalessandri** [arangodb/arangodb#18169]
## My Environment

* __ArangoDB Version__:  3.10.2      
* __Deployment Mode__:   Single Server    
* __Deployment Strategy__:  Manual Start in Docker 
* __Infrastructure__:  own             
* __Operating System__:  MacOs Ventura 13.1      
* __Total RAM in your machine__: 8gb        

## Component, Query & Data

__Affected feature__:

AQL query using web interface

__AQL query (if applicable)__:
```
for i in 0..2
for element in Prova
Update {_key:element._key, number:element.number-1} in Prova

```
__AQL explain and/or profile (if applicable)__:

This is just an example to explain the problem. The idea is subtracting the attributes number n times, depending on how many times the cycle is repeated. 

__Dataset__:

This is just an easy example to explain the problem. There is an element in the collection prova, having just number as attribute.

__Problem__:

The value is not updated correctly and  is subtracted only one times. I think that element.number, inside the cycle,  refer to a cached value, corresponding to the values before the query is started, but i don't know how to manage this situation.

**Comment by dothebart** [comment]
Hi, 
AQL is not designed that way. Values can only travel top down, left to right. And with each iteration you're in a fresh state. 
You can use subqueries to achieve that. 
So you create a subquery, iterate, get a count, then update all documents with the new count.

**Comment by simalessandri** [comment]
All clear, many thanks!
