### ISSUE TITLE
How do you just SKIP (without LIMIT) in AQL?

### ISSUE THREAD

**Issue by joowani** [arangodb/arangodb#1816]
Is it possible to simply SKIP without LIMIT in AQL?

For example,

```
FOR doc IN @@collection
    FILTER doc.foo >= @lower && doc.foo < @upper
    LIMIT @skip ???
    RETURN doc
```

**Comment by baslr** [comment]
I don't get the idea but a simple `FILTER doc.foo != @skip`?

**Comment by Simran-B** [comment]
I can't really think of a meaningful scenario in which you would want to skip documents, but not limit them. Can you explain your use case?

What you can do - as a workaround - is to skip a number of documents and set the limit to a very high value to essentially return all the documents except for the skipped ones, like `LIMIT 20,1e10` (skip 20, return up to 10^10 documents)

**Comment by joowani** [comment]
I am writing a HTTP API wrapper and I was just wondering if the `LIMIT` operator has the syntax to skip only. I guess it does not at the moment. Thanks for the clarification!

**Comment by baslr** [comment]
```
LIMIT count
LIMIT offset, count
```
https://docs.arangodb.com/2.8/Aql/Operations.html

**Comment by dothebart** [comment]
Ok, it seems this Question is answered, so I will close this now.

3.0.0 RC2 is out, try it now: https://www.arangodb.com/download-preview/

**Comment by bendorshai** [comment]
> I can't really think of a meaningful scenario in which you would want to skip documents, but not limit them. Can you explain your use case?
> 
> What you can do - as a workaround - is to skip a number of documents and set the limit to a very high value to essentially return all the documents except for the skipped ones, like `LIMIT 20,1e10` (skip 20, return up to 10^10 documents)

I have a case. I write a script which updates all collections. the script queries each collection once and uses the cursor to fetch data. I want to implement a respawn mechanism for the script in case it crashes so I can query sorted by ids and skip the handled documents...

**Comment by goedderz** [comment]
You can just skip without limit by passing `null` as the count, e.g.
```
LIMIT 20, null
```
.
