### ISSUE TITLE
arangosh and UTF-8

### ISSUE THREAD

**Issue by Sfinx** [arangodb/arangodb#1819]
I'm trying to input UTF-8 symbols into tty version of the arangosh [v2.8.8 || devel] with no success. Only ASCII characters can be typed. So seems like JS version of the arangosh have been disappeared at devel branch.

**Comment by jsteemann** [comment]
I am unable to reproduce this locally.
I can type non-ASCII characters in the arangosh in both 2.8 and devel.

What environment are you using (platform, terminal encoding etc), and what kind of character do you try to type? Does pasting the characters into arangosh work?

**Comment by Sfinx** [comment]
Oops, appeared I'm having non-UTF8 terminal with UTF8 locale ;)
