### ISSUE TITLE
Foxx: Large JSON & Object

### ISSUE THREAD

**Issue by terrybleger** [arangodb/arangodb#1820]
Pardon me for asking this question. Previously I'm using Java and havent used Foxx at all. And I had no problem loading large json/object in Java. Currently I'm using node and foxx and just realized that both node & foxx can't handle too large json/object. I know that I should paging the request, so this might be a stupid issue to open. But, what are you planning about that, since it was the limitation on V8.

**Comment by Simran-B** [comment]
How large is "large"?

Did you try Node v6.0? V8 was upgraded to v5.0 in this major release and might be able to handle large objects better.

If you return a lot of small documents, that sum up to gigabytes of JSON, then yes, you should use cursors to retrieve and process the data in batches. If it's only a few, but giant documents, then it's more complicated. If there's any chance, try to split these giant documents into smaller pieces of information - Arango can handle small to medium-sized documents much better as well.

**Comment by terrybleger** [comment]
It's about more than 1 million records. If I save it to a file, the size is only about 155 MB.

Previously I'm using Java and got surprised that JS is a lot way faster when parsing JSON than Java even using lib like Jackson or Boon.

Yeah, I know that I'm doing it wrong. I though that a million records and 155MB was nothing. I found that not only V8, all browser's JS engine also had that kind of limitation.

**Comment by baslr** [comment]
afaik v8s heap has a soft limit at 1,4G(i?)B you probably could extend this limit with
http://blog.caustik.com/2012/04/11/escape-the-1-4gb-v8-heap-limit-in-node-js/
http://stackoverflow.com/questions/16586705/configuring-v8s-memory-management-to-be-smart-for-a-node-js-process

**Comment by terrybleger** [comment]
Just FYI, in my local machine, a 155MB JSON parsed using JS only took about 1.5s, while using Jackson/Boon in Java took about 5-6s.

@baslr I tried that before, raising the heap limit, won't help either.

Yes, the only workaround is that I have to store it in some kind of paging arrays/objects.
JS is fast, but the object & array have limits. It's kind of a dilemma.

**Comment by baslr** [comment]
@terrybleger 
did you see it in the log:
```
2016-05-13T13:26:54Z [20195] INFO using V8 options '--max_old_space_size=8192'
```

```es6
'use strict';

const crypto = require('crypto');
const arr = [];

while(true) {
  console.log( process.memoryUsage() ); 
  arr.push(  {data: crypto.randomBytes(1024*1024).toString('hex').match(/.{8}/g) } );
}
```
this will crash at `{ rss: 1578086400, heapTotal: 1467760240, heapUsed: 1462208800 }`
(~290M chars) in node with `--max_old_space_size=8192` it will survive.

I will look into this with ArangoDB in a few hours.
Note: I will use the 3.0 branch / devel branch.

**Comment by jsteemann** [comment]
Note also that V8 has a maximum string length of 256 MB.
Creating a longer string in JavaScript longer will throw `RangeError: Invalid string length`.
That won't happen for a 155MB string, I just wanted to point out that there are some more built-in limits to consider and the size of a document cannot grow indefinitely when processed in JavaScript.

**Comment by terrybleger** [comment]
@baslr I think I realised that what my problem is that what @jsteemann has pointed out. I'm hitting the 256MB limit when trying to create the object on JS.

@jsteemann I'm assumming that is the reason why arangodump is saving json in multi-line {doc} kind of format.

**Comment by jsteemann** [comment]
@terrybleger : arangodump is using a line-based format so arangorestore can process large files without reading it completely into memory. 
If we used "real" JSON (e.g. ´[ doc1, doc2, doc3, ... ]`) then we would need to read in the entire file first to check for parse errors, and by using the line-based format we can get away with reading a few (self-contained) lines without having about the rest of the file.
Apart from that, arangodump & restore and the server-side APIs are not JavaScript-based, so they are not affected by V8's limits.

**Comment by terrybleger** [comment]
@jsteemann OK. Thanks.

So I guess using AQL is the only solution here.
