### ISSUE TITLE
foxx-manager replace fails on Windows

### ISSUE THREAD

**Issue by ThomasWeiss** [arangodb/arangodb#1824]
Trying to replace a Foxx app using foxx-manager on Windows always fails with `ArangoError 1753: application upload failed: Unauthorized` whereas the exact same command line and arguments succeed on Mac OSX. Using 2.8.7 on both sides (foxx-manager and server).

**Comment by pluma** [comment]
For context: we've discussed this issue on Slack and it seems to be a general problem with installing/replacing services when using foxx-manager on Windows, possibly related to the handling of file/folder paths.

**Comment by ThomasWeiss** [comment]
Quick update. I tested foxx-manager 3.0.4, still on Windows, and I got this strange result:
- if I execute the command directly from the command prompt, it succeeds (I believe that failed in 2.8.7)
- if I paste the exact same command in a .bat and try to launch it, it fails with `ArangoError 1753: service upload failed: Unauthorized`

**Comment by pluma** [comment]
Closing in favour of https://github.com/arangodb/foxx-cli
