### ISSUE TITLE
Cluster error when node is offline

### ISSUE THREAD

**Issue by baffonso** [arangodb/arangodb#1825]
Hi,

I set up a cluster using two servers.  Both are running a coordinator and database server. It works fine but when one server is taken offline I get the following error when accessing the other one:

{"error":true,"code":500,"errorNum":500,"errorMessage":"A runtime error occurred while executing an action: ArangoError 4: received an error from a DB server: {\"clientTransactionID\":\"106815506\",\"coordTransactionID\":\"1000246\",\"operationID\":\"106881042\",\"shardID\":\"s1000014\",\"status\":\"ERROR\",\"errorMessage\":\"\"} ArangoError: received an error from a DB server: {\"clientTransactionID\":\"106815506\",\"coordTransactionID\":\"1000246\",\"operationID\":\"106881042\",\"shardID\":\"s1000014\",\"status\":\"ERROR\",\"errorMessage\":\"\"}\n    at raiseError (/usr/local/share/arangodb/js/server/modules/org/arangodb/cluster.js:992:13)\n    at Object.wait (/usr/local/share/arangodb/js/server/modules/org/arangodb/cluster.js:1037:7)\n    at SimpleQueryAll.execute (/usr/local/share/arangodb/js/server/modules/org/arangodb/simple-query.js:116:28)\n    at SimpleQueryAll.SimpleQuery.hasNext (/usr/local/share/arangodb/js/common/modules/org/arangodb/simple-query-common.js:567:8)\n    at buildRouting (/usr/local/share/arangodb/js/server/modules/org/arangodb/actions.js:1085:14)\n    at Object.routeRequest (/usr/local/share/arangodb/js/server/modules/org/arangodb/actions.js:1217:7)\n    at Function.actions.defineHttp.callback (/usr/local/share/arangodb/js/actions/api-system.js:58:15)"}

Thanks,

Bruce

**Comment by dothebart** [comment]
In the current state of implementation the Cluster isn't meant to handle failover on its own. 
The new Mesosphere interface offers the ability to add asynchroneous replication slaves to the database servers by ticking a checkmark in the Mesosphere startup for ArangoDB.

If you then unplug one node, Mesos will handle the failover and reconfigure ArangoDB to use the replication slave as new master db server running on the second node.

We're currently lagging a bit behind in documentation terms for mesosphere clusters; I've outlined the relevant facts in this stackoverflow post:

http://stackoverflow.com/questions/36391768/issue-to-start-coordinator/36402546#36402546

**Comment by baffonso** [comment]
Thanks.  I forgot to mention I created the cluster using the web interface using two linux machines.

**Comment by dothebart** [comment]
Hi, the old ArangoDB internal cluster webinterface is for evaluation purposes only; Failover etc. is only handled in a cluster managed by Mesosphere.

**Comment by dothebart** [comment]
I'm closing this as not an issue. If you think that the problem hasn't been solved or that there is anything missing with a mesos controlled cluster, feel free to re-open the issue.

ArangoDB 3 will also bring new cluster features, RC2 is now available for testing: https://www.arangodb.com/download-preview/
