### ISSUE TITLE
GEO_AREA returns negative values

### ISSUE THREAD

**Issue by AntoineAA** [arangodb/arangodb#18287]
## My Environment

* __ArangoDB Version__:        3.10.4
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:  Manual Start
* __Configuration__:               
* __Infrastructure__:               own
* __Operating System__:        Ubuntu 20.04.5
* __Total RAM in your machine__:        128Gb
* __Disks in use__:        HDD 700Gb
* __Used Package__:              Debian or Ubuntu .deb

## Component, Query & Data

__Affected feature__:
GEO_AREA function

__AQL query (if applicable)__:
```
for g in geos
    return GEO_AREA(g, 'wgs84')
```
__AQL explain and/or profile (if applicable)__:

__Dataset__:
Set of GeoJSON polygons / multipolygons: https://github.com/AntoineAA/tmp/blob/main/geos.json

```
let geos = [...]

```

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. Run the query using ArangoDB v3.8.7
2. Run the query using ArangoDB v3.10.4

__Problem__:
In both cases, there are some bugs with the GeoJSON data :

3.8
```
Warnings:

[10], 'in function 'GEO_AREA()': Polygon is not valid'

Result:

[
  1916130759737.6982,
  1563346131527.853,
  null
]
```

3.10
```
Warnings:

[10], 'in function 'GEO_AREA()': Subsequent loop not a hole in polygon'
[10], 'in function 'GEO_AREA()': Subsequent loop not a hole in polygon'

Result:

[
  null,
  -1563346131527.853,
  null
]
```

In the 3.10 version, there are very few results, and they are negative.

__Expected result__:

If the GeoJSON data allows, calculate an area (positive value).

**Comment by MBkkt** [comment]
In 3.10 we remove Polygon normalization, because we want to allow to user define and search polygon bigger than half world.

So probably your polygon in incorrect format.
Please try to reverse their outer loop vertices.
https://geojsonlint.com/

**Comment by AntoineAA** [comment]
Ok, sorry, I haven't upgraded to 3.10 myself and haven't looked at the new features yet...
