### ISSUE TITLE
Feature request: Add ability to pin vertexes in graph viewer

### ISSUE THREAD

**Issue by disharmonized** [arangodb/arangodb#1829]
It would be very handy to have ability to pin vertexes in graph viewer in Web Interface (they just kind of floating in fluid now).
I am using ArangoDB v.2.8.7.

**Comment by dothebart** [comment]
Hi, to keep a better overview, we're collecting feature requests to the graph viewer in #1595; I will copy your comment over and close this ticket. Feel free to add further comments on #1595 .

**Comment by disharmonized** [comment]
Okay, thanks, the last thing i forgot -  just add illustration of reason why i open this issue.
[https://snag.gy/sDqQYk.jpg](url)
