### ISSUE TITLE
Is "Graph View" open source?

### ISSUE THREAD

**Issue by playgithub** [arangodb/arangodb#18296]
"Graph View" which is introduced at https://www.arangodb.com/learn/first-day/web-ui/

**Comment by dothebart** [comment]
The webinterface source can be found here: https://github.com/arangodb/arangodb/tree/devel/js/apps/system/_admin/aardvark/APP the graph view in it currently is implemented on top of https://www.sigmajs.org/ .

**Comment by playgithub** [comment]
Great, thanks.
