### ISSUE TITLE
ArangoDB HTTP REST API question

### ISSUE THREAD

**Issue by joowani** [arangodb/arangodb#1832]
Are there any benefits to using the general graph API (/_api/gharial/) over the regular collection (/collection) and document (/document) API to manipulate vertices/edges of a graph (assuming the vertex collection and edge definitions are already defined)? Looking at the documentation it looks like the graph API doesn't offer anything more in particular.

**Comment by baslr** [comment]
from the docs https://docs.arangodb.com/Graphs/index.html
However the graph module adds an additional layer on top of these collections giving you the following guarantees:

* All modifications are executed transactional
* If you delete a vertex all edges will be deleted, you will never have loose ends
* If you insert an edge it is checked if the edge matches the edge definitions, your edge collections will only contain valid edges

**Comment by joowani** [comment]
Ah I must've missed that page.Thanks you!
