### ISSUE TITLE
Unable to remove first filter item from filter view

### ISSUE THREAD

**Issue by zopyx** [arangodb/arangodb#1834]
It is not possible to remote the first item of a filter (having only a + sign). However it might make sense adding some filter items first and them removing the first item does not work...

![screenshot 2016-05-22 15 22 55](https://cloud.githubusercontent.com/assets/594239/15454182/28dc4a90-2031-11e6-9218-84be449b736e.png)

**Comment by dothebart** [comment]
will be fixed during the 3.0.x release cycle. 

ArangoDB 3.0 RC 2 available for download: https://www.arangodb.com/download-preview/

**Comment by hkernbach** [comment]
The feature will be included in the next 3.0.x release.
