### ISSUE TITLE
Web UI glitch

### ISSUE THREAD

**Issue by francoisprunier** [arangodb/arangodb#1838]
Hi,

I've noticed a small but annoying bug on the admin web UI.

Using the latest 2.8.9 version from the docker image.
1. go to 'Graphs'
2. click 'Add Graph'
3. click inside 'Edge definitions', pick one
4. click again inside 'Edge definition', a drop down with the text 'You can only select 1 item' appears
5. hit 'Cancel' button

=> the dropdown does not disappear, see screenshots below. The only way to get rid of it is to refresh the page.

![step1](https://cloud.githubusercontent.com/assets/8289560/15613773/8b42b996-2435-11e6-865c-5a75020f4d50.png)
![step2](https://cloud.githubusercontent.com/assets/8289560/15613774/8b431b98-2435-11e6-870f-cdcde4c2f3b7.png)

**Comment by hkernbach** [comment]
Thank your for the report. Issue is fixed in current devel branch and will be included in the upcoming 3.0 release.
