### ISSUE TITLE
Reverse Skiplist applied manually (whoosh), could be automatic?

### ISSUE THREAD

**Issue by ctmakro** [arangodb/arangodb#1840]
Code sample 1:
```
        for t in threads

        filter t.fid == '81' && t.disabled==null
        sort t.tlm desc        

        limit 0,6

        let oc = document(posts,t.oc)
        return merge(t,{oc})
```
Code sample 2:
```
        for t in threads

        filter t.fid == '81' && t.disabled==null
        sort t.fid desc,t.disabled desc, t.tlm desc        

        limit 0,6

        let oc = document(posts,t.oc)
        return merge(t,{oc})
```

sample 1 is what I intended to do. I created a skiplist index on [fid,disabled,tlm]. Unfortunately ArangoDB use the index only on the FILTER, while the SORT node still have to sort itself out.

sample 2 is what I finally did, which is about 50x faster than sample 1, since the skiplist is fully utilized.

Oh what if I, the poor web developer, know nothing about database theories? (I been a user of CouchDB)
Really wish ArangoDB could do that automatically for me (combine property filter with property sort to make full use of the index), or document this behavior explicitly in documentation (high level operations / FILTER)

**Comment by jsteemann** [comment]
ArangoDB cannot use the skiplist index for the first query, because the query asks for the documents from the `threads` collection to be sorted by the `tlm` attribute only.
If the skiplist index is created on `[ "fid", "disabled", "tlm" ]`, then this index cannot be used for the query.
Let's assume the collection (and thus the index) contains the following values:
```
fid    disabled   tlm
---------------------
  1    false        1
  1    false        2
  1    true         1
  1    true         2
  2    false        1
  2    false        2
  2    true         1
  2    true         2
  3    false        1   
...
The index is first sorted by `fld`, then `disabled` and then `tlm`. 
As you can see, the index contains the values for the `tlm` attribute in contiguously sorted order, but not for `disabled` or `tlm`.
The index can thus be used for retrieving a contiguously sorted range of `fld` values. It can, however, *not* be used for querying only the values of `disabled` in sorted order, neither can it be used to query `tlm` in sorted order.
As the index spans three attributes, the index additionally supports querying `fld` and `disabled` in sorted order (with the return values sorted by `fld` first, then `disabled`) and querying `fld`, `disabled` and `tlm` (with the return values sorted first by `fld`, then `disabled`, then `tlm`).

Summarizing: the index wouldn't be of any help for the first query, and therefore it is not used. This is intentional.

I can't tell if this needs better documentation in the manual. If it wasn't obvious, then probably it does!

**Comment by ctmakro** [comment]
@jsteemann thanks for your reply.
Well, (Luckily) I did study database theories (not good enough to develop one : ), and know how indexes works. I totally understand the underlying concept (or otherwise I won't find myself a solution to the problem).

The point is: the two queries mentioned above, are IDENTICAL in result, and they SHOULD choose the same execution path (with good enough reasons).

To clarify the problem, I made a simpler example.
```
for doc in whatever
filter doc.a == 1
return doc
```
It is obvious that `filter doc.a == 1` WILL benefit from a skiplist index created on `["a","b"]`, from O(N) to something around O(log N). The AQL Query Optimizer agreed on that.
It is also obvious that "doc" returned will be sorted by attribute "b", because that's how skiplist works.

But surprisingly, the Query Explainer told me:
```
for doc in whatever
filter doc.a == 1
sort doc.b
return doc
```
where SORT clause will NOT make use of the same index. (won't make use of any index, actually)
The Query Engine will ALWAYS sort by doc.b AGAIN, even if it is already sorted by doc.b.
I think this is not optimizing, nor helpful.
And that slowed my queries down for about 20 times, which is a disaster for page performance.
But the results are the very same. Why should I spent CPU on sorting something that is already sorted?

Finally, below solution worked:
```
for doc in whatever
filter doc.a == 1
sort doc.a, doc.b
return doc
```
By explicitly stating that I want everything sorted, the Query Optimizer finally understand what he should do, and optimized both FILTER and SORT to use the index.
All three piece of code above return EXACTLY THE SAME result.
So again, that is confusing: since FILTER doc.a can (and will, and always did) benefit from sorted index, why do I have to explicitly state that it be sorted? The optimizer should optimize that, really.

My request:
Query Optimizer should optimize `equality comparison filtering & attribute sorting`  to `skiplist index scan` automatically, since this is natural in my point of view.
If this is not considered necessary, I suggest adding the following into documentation:
```
You can optimize [equality comparison filtering] together with [attribute sorting] to use a Skiplist index, IF and ONLY IF you include EVERY attribute involved, in a SORT clause, in the same order as in the index, sorting in the same direction.
```
It really took me some good time to figure out this solution.

**Comment by jsteemann** [comment]
@ctmakro: sorry, I had initially overlooked that the FILTERs for the first index attributes in the original query were constant values.
Under that very circumstance (first index attributes are used in equality comparison, and one of the next index attributes is used for sorting, then indeed the index could be used to optimize away the SORT clause.
And good news is that this optimization has already been implemented a while ago in the devel branch of ArangoDB, so it will be present in the 3.0 release (and is already part of the 3.0 technical preview).
Here's the 3.0 execution plan for the original query:
```
Execution plan:
 Id   NodeType          Est.   Comment
  1   SingletonNode        1   * ROOT
 11   IndexNode            1     - FOR t IN threads   /* skiplist index scan */
  7   LimitNode            1       - LIMIT 0, 6
  8   CalculationNode      1       - LET oc = DOCUMENT(posts   /* all collection documents */, t.`oc`)   /* simple expression */   /* collections used: t : threads */
  9   CalculationNode      1       - LET #6 = MERGE(t, { "oc" : oc })   /* simple expression */   /* collections used: t : threads */
 10   ReturnNode           1       - RETURN #6

Indexes used:
 By   Type       Collection   Unique   Sparse   Selectivity   Fields                         Ranges
 11   skiplist   threads      false    false            n/a   [ `fid`, `disabled`, `tlm` ]   ((t.`fid` == "81") && (t.`disabled` == null))
```
As you can see, the SORT is gone there.

**Comment by ctmakro** [comment]
I took a short visit to CHANGELOG of `dev`, and saw something like

> * improved AQL optimizer to remove unnecessary sort operations in more cases

That's great.

**Comment by dothebart** [comment]
RC2 is now available for download via: https://www.arangodb.com/download-preview/

Closing.
