### ISSUE TITLE
'Invalid input for traversal: Only strings or objects with _id are allowed'

### ISSUE THREAD

**Issue by sajeevpr** [arangodb/arangodb#1845]
Hi,
  I am getting the below error when I am filtering with some attribute data. For others, it is working fine.

It is working for filter city == 'london' and query executed  very fast.

But for city =='dubai', it is throwing this warning along with data. Also the query was very slow. This happens only when I give LIMIT as 50. But when I gave LIMIT as 10. no such problems.

Also I noted that the query is becoming very slow when the document is at the end of the result set.

Regards,
Sajeev

**Comment by Simran-B** [comment]
Can you please give some more details?

How many documents are in the collection?

What are your indexes?

What version of Arango do you use, and on which OS? How much RAM is
available?

Thanks!

**Comment by sajeevpr** [comment]
Hello,
  I have totally 0.5 million documents in the collection.

I have a collection user (USR_KEY,CITY) which contains 0.5 million documents. But I am traversing based on the relation (use is owner of account) user holds with another collection account (KEY,USR_KEY) (18 million).

I have enabled hash index on CITY.

Arangodb - 2.8.9
OS - RHEL
RAM - 192 GB

Regards,
Sajeev

**Comment by Simran-B** [comment]
What forgot to ask: can you show us the full query that raises the error? Or something close to it, if it's not possible to share directly?

Do you actually do a graph traversal, or a regular FOR iteration over your collection?

**Comment by sajeevpr** [comment]
FOR manager IN managers FILTER manager.RTB_MANAGER_USR_KEY == 191
 FOR connectedToManager IN 1..1 INBOUND manager._id GRAPH 'graph'
   FOR v,e,p IN 1..4 OUTBOUND connectedToManager._id userToUserGroups,userGroupsToAppInstances,appInstancesToHost,hasAccounts
      FILTER p.edges[3].type == 'hostsToAccounts'
        FOR v1 IN INBOUND v._id userToAccountAsOwner
          FILTER v1.CITY == 'london'
          LIMIT 50
        RETURN v1

**Comment by dothebart** [comment]
can you try to insulate which of these traversers actually produces the error so you can find the actual document? So, can you split the query and retry so you can track it down?

The error itself occurs in any parts of the query similar to: 

    FOR v1 IN INBOUND v._id userToAccountAsOwner

where `v._id` doesn't contain a `/`

**Comment by dothebart** [comment]
Any news on this? or should we close this?

**Comment by sajeevpr** [comment]
@dothebart
I think this can be closed for now. Will reopen if it occurs again.
