### ISSUE TITLE
3.10.5 don't start on windows 11

### ISSUE THREAD

**Issue by iwedaz** [arangodb/arangodb#18461]
## My Environment

* __ArangoDB Version__:        3.10.5
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               default values
* __Infrastructure__:               own
* __Operating System__:        Windows 11 x64

## Steps to reproduce

1. Run arangod.exe

__Problem__:

![imgpsh_fullsize_anim](https://user-images.githubusercontent.com/7631067/227996157-62aa6f7c-3ad7-4554-a33a-e8d6041e762b.png)

![imgpsh_fullsize_anim (1)](https://user-images.githubusercontent.com/7631067/227997005-a8d3f372-d5c3-4cd3-8993-d2638f98fbaf.png)

I don't have this issue on version 3.10.4 and earlier.

**Comment by dothebart** [comment]
Hi, did you use the zip or the .exe installer? 
for me using git bash's `file` command I get:
```
Administrator@HW-TST11-Windows MINGW64 /c/xx/usr/bin
$ file arangod
arangod: PE32+ executable (console) x86-64, for MS Windows
```
for both?

**Comment by iwedaz** [comment]
I use builds from zip file

**Comment by dothebart** [comment]
so this will work for one but not the other?
```
Administrator@HW-TST11-Windows MINGW64 /c/xx/ArangoDB3-3.10.5_win64/usr/bin
$ ./arangod --version
3.10.5

architecture: 64bit
arm: false
asan: false
asm-crc32: false
assertions: false
...
```

**Comment by iwedaz** [comment]
Ok. I think file was corrupted somehow. After I downloaded zip and tested again everything works good.

**Comment by dothebart** [comment]
ok, thanks for confirming!
