### ISSUE TITLE
Geo functions does not contains any distance calculating function between two co-ordinates.

### ISSUE THREAD

**Issue by lalitlogical** [arangodb/arangodb#1846]
Hi,

I have seen ArangoDb docs but not find any function that calculates the distance between two coordinates in AQL queries. Might be there is but I have not seen yet. 

I have a users and posts collection that contains the latitude and longitude. So when I fetch the posts, I want to calculate the distance between the current user and the posts with their respective coordinates.

arango 2.8.7 + NodeJs

**Comment by dothebart** [comment]
We will add this during the 3.0.x release cycle. The current workaround is to install a user defined function as noted on stackoverflow.

**Comment by lalitlogical** [comment]
Thanks for your reply @dothebart 

Actually, I have started from few days on ArangoDb. I have not enough knowledge on it.

Can you please let me How I can add my own functions for AQL queries? Or Where I need to add these functions? 

I have not seen any options on ArangoDB Web UI for same.

**Comment by baslr** [comment]
Hi @lalitlogical,

you can read more about user defined functions at https://docs.arangodb.com/AqlExtending/index.html
There is no GUI interface for defining these functions.

**Comment by lalitlogical** [comment]
Hi @baslr 

Where I need to put these functions?

**Comment by CoDEmanX** [comment]
You need to register it in the database as explained in the documentation. It won't be part of your NodeJS project.

**Comment by lalitlogical** [comment]
Hi @CoDEmanX , @dothebart, @jsteemann 

I have seen the doc but I have not cleared my queries as Where I will find these files where I need to put these functions? I have installed the ArangoDB with the brew on Mac Yosemite.

Actually, I have completed the Backend APIs for a project with OrientDB. But we found that it goes slow with more data. So we decide to move to another database as ArangoDB. So till now I have completed all feature with OrientDB. Which actually based on locations, distance etc. So I must need distance calculating function at any effort. 

So anyone can help me to define this functions. Only let me know with the example that where I need to put these functions and rest work I will do myself. 

Please help me.
Thanks

**Comment by Simran-B** [comment]
When you register an AQL function, the name, code and determinism flag are stored in the database system itself (`_aqlfunctions` system collection), by default in the _system database. You don't need any file with the function code.

https://youtu.be/xlFlawPHYkM

It's of advisable to write the code in a code editor and save it as file. You can require the code in arangosh in order to register the function, so that you don't have to type the entire code in arangosh or copy & paste respectively:

https://youtu.be/zxnNIqZlyJQ

You could theoretically delete the source file after registering, but you are better off to keep it in case you need to re-register the function or want to adjust the code (you will have to register the function again in order to update it).

Note that it's discouraged to edit the function code in the `_aqlfunctions` collection directly. As you can see in the video, there is a cache which results in the old code being used at first. After I restart the server, the new code is used. If you use the proper interface (`.register(...)`), that problem shouldn't occur.

**Comment by lalitlogical** [comment]
Thanks for your reply @Simran-B 

I have followed your steps and resolved my issue by creating my own AQL Functions.

```
/* distance.js */
'use strict';

function gdistance(latitude1, longitude1, latitude2, longitude2, radius) {
    if (Number.prototype.toRadians === undefined) {
	    Number.prototype.toRadians = function() { return this * Math.PI / 180; };
	}

    var lat1 = Number(latitude1), lon1 = Number(longitude1);
    var lat2 = Number(latitude2), lon2 = Number(longitude2);

    radius = (radius === undefined) ? 6371e3 : Number(radius);

    var R = radius;
    var φ1 = lat1.toRadians(), λ1 = lon1.toRadians();
    var φ2 = lat2.toRadians(), λ2 = lon2.toRadians();
    var Δφ = φ2 - φ1;
    var Δλ = λ2 - λ1;

    var a = Math.sin(Δφ/2) * Math.sin(Δφ/2)
          + Math.cos(φ1) * Math.cos(φ2)
          * Math.sin(Δλ/2) * Math.sin(Δλ/2);
    var c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
    var d = R * c;

    return d / 1000;
}

module.exports = gdistance;
```

I have added the above functions as AQL function as below.

```
db._useDatabase("myDatabase");
var aqlfunctions = require("org/arangodb/aql/functions");
var f = require("/path/to/file/distance.js");
aqlfunctions.register("geo::gdistance", f, true)
```

In my queries I have used above function as below.

`LET distance = geo::gdistance(user.latitude, user.longitude, @latitude, @longitude)`

Again thanks @Simran-B for the reply. Actually, in ArangoDB docs, there are not mention about arangosh uses. So I have never found the way to add my own functions.

Thanks

**Comment by baslr** [comment]
@lalitlogical  afaik km -> to meter is multiply by 1000. 1km is 1000m.

**Comment by lalitlogical** [comment]
@baslr I have wrongly written Vise-Versa :P

**Comment by lalitlogical** [comment]
I have updated the above code for blank(undefined) values as below.

```
'use strict';

function gdistance(latitude1, longitude1, latitude2, longitude2, radius) {
    if (!latitude1 || !longitude1 || !latitude2 || !longitude2) { 
        return null; 
    };

    var lat1 = Number(latitude1), lon1 = Number(longitude1);
    var lat2 = Number(latitude2), lon2 = Number(longitude2);

    radius = (radius === undefined) ? 6371e3 : Number(radius);
    
    var R = radius;
    var φ1 = (lat1 * Math.PI / 180), λ1 = (lon1 * Math.PI / 180);
    var φ2 = (lat2 * Math.PI / 180), λ2 = (lon2 * Math.PI / 180);
    var Δφ = φ2 - φ1;
    var Δλ = λ2 - λ1;
    
    var a = Math.sin(Δφ/2) * Math.sin(Δφ/2)
          + Math.cos(φ1) * Math.cos(φ2)
          * Math.sin(Δλ/2) * Math.sin(Δλ/2);
    var c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
    var d = R * c;     // Meters
    var d2 = d / 1000; // Meters to KM
    return d2; 
}

module.exports = gdistance;
```

**Comment by lalitlogical** [comment]
How can I do above for arangodb cluster service which contains the 2 coordinators, 2 dbservers etc on DC/OS under AWS Cloudformation?

**Comment by Simran-B** [comment]
@lalitlogical: What problem do you see when running DC/OS under AWS Cloudformation?

**Comment by lalitlogical** [comment]
Hi @Simran-B, I am able to add my custom function below.

1) I had done sshuttle to access clusters to my local machine

`sshuttle --python /opt/mesosphere/bin/python3.4 -r core@my-ip-address 10.0.0.0/8`

Then I am able to access the arangodb service web ui on my browser with local ip address i.e. http://10.0.1.221:14170

2) Access the remote arangosh as below

`arangosh --server.endpoint tcp://10.0.1.221:14170 --server.username root`

Then I had registered the distance function as below.

```
db._useDatabase("GeoConnect");
var aqlfunctions = require("@arangodb/aql/functions");
var f = require("distance.js");
aqlfunctions.register("geo::gdistance", f, true)
```

**Comment by Simran-B** [comment]
Thanks, I'll add a note to the documentation that AQL UDFs need to be registered on the coordinator. How to get access to the server (sshuttle) seems a bit too specific to include it in the general documentation, but I'll check with the team.

**Comment by lalitlogical** [comment]
Hi @dothebart,

Hope you remeber the issue of UDFs on Arangodb Cluster services. So I just want to know, is there any plan/roadmap to add this function under AQL in arangodb releases? Because our app totally depends on distance. So we can not modify our some aql queries that consume our resources and leads to issue.

https://github.com/arangodb/arangodb/issues/1947
