### ISSUE TITLE
Feature request: Introducing more types

### ISSUE THREAD

**Issue by Madmancj** [arangodb/arangodb#1850]
Please introduce some more supported types such as date, timestamp, etc. It would be helpful as parsing date and time for every query is costly.

**Comment by dothebart** [comment]
Short hint: you can use skiplist indices in conjunction with timestamp strings in the format YYYY/MM/DDZhh:mm:ss - you can even do range requests supported by the index.

**Comment by Madmancj** [comment]
I'll surely give it a try. Thanks.

**Comment by Simran-B** [comment]
Have a look here regarding dates and indexes:

https://docs.arangodb.com/3.0.0b1/AQL/Functions/Date.html#working-with-dates-and-indices

**Comment by Madmancj** [comment]
I guess i was already on the right track. Thanks.
