### ISSUE TITLE
Why add a new type of index?

### ISSUE THREAD

**Issue by dsonet** [arangodb/arangodb#1852]
Just don't understand why added the index type persistent, but instead of provide and configuration to enable persist current index types? 

From an end users view, I feel provide a switch to this is more reasonable.

Thank you if you can help me to understand this.

**Comment by dothebart** [comment]
ArangoDB supports various types of indices: 
 - Unsorted
 -  Sorted
 - Fulltext
 - Geo
 - Sorted Persistent 
Each of those has their own dis/advantages so the User should choose according to its situation. 

One of the disadvantages of the persistent index is the higher maintenance resource usage. The way ArangoDB works with this index is different to the other indices. 
In the current implementation state its not possible to persist all sorts of indices, thus its not a flag. 

However, this is not carved in stone, we will see in which direction the journey is heading here in the post 3.0.x release cycle.

**Comment by dothebart** [comment]
closing since no more questions arised.
