### ISSUE TITLE
Exporting Graph traversal data efficiently

### ISSUE THREAD

**Issue by sajeevpr** [arangodb/arangodb#1853]
Hi,
 I was trying to extract the graph data which has almost 4 million vertices and 22 million edges using the traversal objects. The traversal output need to be written to a flat file which would have an anticipated 150 million records.

With the current speed, it will take 18 hrs to complete it. Is there any efficient way to handle this. I have given below the near code used.
```
var traversal = require("org/arangodb/graph/traversal")

var printExplodedData = function (dataString,keyString,nodeType){

				var mypathKeysArray = keyString.split(">");
				//out.print(mypathKeysArray.length);
				var startNode = mypathKeysArray[0];
				var directParent = mypathKeysArray[mypathKeysArray.length-2];
				var groupMemberKey;
				var memberType;
				var fullPath = dataString;

				if(nodeType=='G')
				  memberType='GROUP';
				else
				  memberType = 'USER';
				  
				result.visited.paths.push(startNode+"|"+directParent+"|"+memberType+"|"+fullPath)  
			    //out.print(startNode+"|"+directParent+"|"+memberType+"|"+fullPath)

}

var explosionTraversal= function (config, result, vertex, path, connected) {
  var out = require("internal");

		if (connected && connected.length === 0) {
			 var mypathTemp = result.mypath;
			 var mypathKeysTemp = result.mypathKeys;
             mypathTemp+=vertex.DOMAIN+"/"+vertex.ACCOUNT;
		     mypathKeysTemp+=vertex._key;
		}
		else{
		    var mypathTemp = result.mypath+vertex.NAMESPACE+"/"+vertex.ACCOUNT;
			var mypathKeysTemp = result.mypathKeys+vertex._key;
		    result.mypath+=vertex.NAMESPACE+"/"+vertex.ACCOUNT+">";
		    result.mypathKeys+=vertex._key+">";
			
		}
		
		printExplodedData(mypathTemp,mypathKeysTemp,vertex.NODE_TYPE);
		
	
}

var config = {
  datasource: traversal.generalGraphDatasourceFactory("Graph"),
  strategy: "depthfirst",
  order: "preorder-expander",
  filter: traversal.visitAllFilter,
  expander: traversal.outboundExpander,
  visitor: explosionTraversal
};

var result = {
  visited: {
    vertices: [ ],
    paths: [ ]
	},
	mypath:"",
	mypathKeys:""
};
var out = require("internal");
var traverser = new traversal.Traverser(config);
var Node = db._collection('Node');
var cursor = Node.byExample({ "NODE_TYPE" : "G" });
var groupNodes = [];
while(cursor.hasNext()) {
  node = cursor.next();
  groupNodes.push(node);
}  
out.print("Total Groups "+groupNodes.length)
  
for(i=0;i<groupNodes.length;i++){  
  traverser.traverse(result, groupNodes[i]);
  
  for(j=0;j<result.visited.paths.length;j++){
    out.print(result.visited.paths[j]);
  }
  
  result = {
	  visited: {
		vertices: [ ],
		paths: [ ]
	},
	mypath:"",
	mypathKeys:""
    };
}

```
Command executed
```
./arangosh --server.endpoint tcp://hostname:port --server.username <user> --server.password <password> --javascript.startup-directory /usr/share/arangodb/js  --javascript.execute file_v3.js --javascript.v8-options "--stack-size=9192"  > out.txt
```

Any help will be greatly helpful.

Thanks,
Sajeev

**Comment by baslr** [comment]
You should not build up lengthy arrays, instead print it out as fast as possible.

Could you please reformat your example with three starting backticks ` and at the ending also with three ` 
after the starting backticks add `js` so it gets syntax highlighting. Than its easier to follow your example and help you.
Example
```js
var traversal = require("org/arangodb/graph/traversal")

var printExplodedData = function (dataString,keyString,nodeType){
}
```
Thanks

**Comment by sajeevpr** [comment]
I am trying to solve this problem by executing parallel processes.

**Comment by sajeevpr** [comment]
Hello,
  Can you suggest a way to traverse the graph which doesn't make any internal http calls?

Regards,
Sajeev

**Comment by dothebart** [comment]
You could use js to create & write a file: https://docs.arangodb.com/ModuleFs/index.html

**Comment by sajeevpr** [comment]
Thank you dothebart. I am wondering is there any way to do the traversal with out executing the underlying REST API's. I found that arangosh is also executing the HTTP API behind the scenes.

Thanks,
Sajeev

**Comment by dothebart** [comment]
Currently the only communication path between drivers and arangod is HTTP. If you want to circumvent that, you could as noted above instead write the file locally in arangod using js. The not to distant future will bring binary transport using velocypack over HTTP which will cheapen that.

**Comment by sajeevpr** [comment]
Thank you for the response. I will try to use the js write functionality and see how much difference it makes. Also waiting for the new binary protocol that I am expecting to come with 3.0.

Thanks,
Sajeev

**Comment by sajeevpr** [comment]
I think file writing in append mode is missing.

**Comment by sajeevpr** [comment]
I could see file write append mode in version 3.0.

**Comment by sajeevpr** [comment]
I am now able to do traversal with in 3 hrs after doing it using foxx service. Please suggest if you have a better method.

**Comment by fceller** [comment]
@sajeevpr just for my understanding of the problem: you need to export parts of your graphs that are reached by the traversal starting from the top-level "group" nodes? Why many such group nodes are there roughly?

**Comment by sajeevpr** [comment]
The problem statement is to take each group nodes and traverse till the leaf nodes and printing all possible paths. There are around 1 million groups, 4 million members and 20 million edges. Some group may have 1 million paths. I got totally around 240 million paths after traversing all groups.

**Comment by sajeevpr** [comment]
I tried to use fs.append function. But the performance seems to be very bad. Please find below the performance when compared with require("internal").out functionality.

fs.append - 218 minutes and 16 seconds

require("internal").out - 155 minutes and 36 seconds

We can see a huge difference of more than 1 hour. This time is taken by getting all paths (approx 240 million) from a huge graph using 20 parallel http invocations.

Regards,
Sajeev

**Comment by sajeevpr** [comment]
I just grouped the writing to file. That is write only when I have 1 million rows.

So the time taken has reduced to 95 minutes for extracting 240 million lines.

This seems to be good.

**Comment by fceller** [comment]
Cool
