### ISSUE TITLE
Where are the pages describing the new 2.8 (and 3.0) features

### ISSUE THREAD

**Issue by NinoFloris** [arangodb/arangodb#1855]
I can find the mdpp files in the repo but they don't show up in the docs online.
Something going wrong in the process there?

**Comment by dothebart** [comment]
the 3.0 (beta) documentation can be found here: https://docs.arangodb.com/3.0.0b1/ we moved a lot of files since we split up the documentation into several books.

**Comment by Simran-B** [comment]
@NinoFloris: is this sufficient?

- **What's new in 2.8**: https://docs.arangodb.com/2.8/NewFeatures/NewFeatures28.html
- **What's new in 3.0** (as of beta1 release): https://docs.arangodb.com/3.0.0b1/Manual/ReleaseNotes/NewFeatures30.html
- **Latest changes**: https://github.com/arangodb/arangodb/blob/devel/CHANGELOG

**Comment by dothebart** [comment]
We're currently heading for RC2, Documentation will be Available under https://docs.arangodb.com/3.0 from now on. If you still find information missing, please let us know.
I'm closing this now, feel free to reopen, just in case.
