### ISSUE TITLE
"Contributors" renders as "undefined" on Foxx Info pane

### ISSUE THREAD

**Issue by rbrewer101** [arangodb/arangodb#1856]
"Contributors" is not rendering correctly on Foxx Info pane even when manifest.json correctly specifies a "contributors" array.

Repeatable in both _system and user db's.

Reported on Slack feedback30 channel. See [this ](https://slack-files.com/T07NV0TD4-F1E5FE9CG-1f82d34bf2)image.

platform: Ubuntu 14
version: Arango v3.0-beta1 installed from 'deb https://www.arangodb.com/repositories/unstable/xUbuntu_14.04/ /' 
browser: Chrome

**Comment by rbrewer101** [comment]
A bit of follow up. Tip from a Slack participant showed that Contributors is an array of objects rather than strings. Also, it looks like the page template renders the "name" properties of the Contributors objects and sets the mailto: action to the "email" properties, if those properties exist. See [this](https://slack-files.com/T07NV0TD4-F1ELFCZMX-b4f01f77ac) example.

This is probably just a case of touching up the [docs](https://docs.arangodb.com/3.0.0b1/Manual/Foxx/Manifest.html) to match a reasonable behavior.

**Comment by dothebart** [comment]
hm, we believe this has been fixed on the way to RC1 or RC2 tonite. Could you revalidate this?

**Comment by dothebart** [comment]
Closing as RC2 is available with this fixed via https://www.arangodb.com/download-preview/ Thanks for reporting.
