### ISSUE TITLE
[3.0b] unable to view created graphs in web admin

### ISSUE THREAD

**Issue by ropeladder** [arangodb/arangodb#1859]
I am trying out 3.0 beta 1 and my graphs are not showing up in the web admin -> graphs page. Creation seems to work ok (I can see them in arangosh), and web admin stops me from creating two graphs of the same name, but the Graphs page never shows me anything more than the "create graph" button.

I am running Arango on Linux Mint 17.3 as a service, and accessing the web admin panel using Firefox 46.01.

**Comment by hkernbach** [comment]
Thank you. Fixed.
