### ISSUE TITLE
multiple edge definitions per graph gone in 3.0?

### ISSUE THREAD

**Issue by ropeladder** [arangodb/arangodb#1860]
In Arango 2.8.9 it was possible to create multiple edge definitions when creating a graph in the web admin panel by clicking the plus sign to the right of the edge definitions field. Now, the plus sign is gone and (at least in the web admin) it doesn't seem possible to use more than one edge definition.

Is this intentional? I was previously using a graph that had multiple edge definitions to do deletions and it was very convenient.

**Comment by hkernbach** [comment]
thank you for the tip. fixed now.
