### ISSUE TITLE
Bug? --database.slow-query-threshold not available anymore

### ISSUE THREAD

**Issue by baslr** [arangodb/arangodb#1862]
First appearance: v2.4.6 and 2.5.1 (CHANGELOG)
https://github.com/arangodb/arangodb/blob/f196428920a95b89ad21737446b9b18697e11182/CHANGELOG#L3128
and
https://github.com/arangodb/arangodb/blob/f196428920a95b89ad21737446b9b18697e11182/CHANGELOG#L2725

gone in: tested v2.8.0 and 3.0.0-beta1

```
# (v2.8.0)
./ad --database.slow-query-threshold 0
./ad: unrecognized option '--database.slow-query-threshold'
Did you mean one of these? --database.disable-query-tracking
2016-06-08T20:47:16Z [26053] ERROR cannot parse command line: illegal option
2016-06-08T20:47:16Z [26053] FATAL cannot parse command line arguments


$ ./arangod-3-0-beta1 --help-.|grep -i slow
$
```

found by @judioo

**Comment by pluma** [comment]
As far as I can tell this option is already missing in the latest 2.5 release (2.5.7) and all consecutive minor releases. I'm guessing the option was temporary and its removal was never announced in the changelog?

**Comment by jsteemann** [comment]
The options was present in the code in the 2.4 branch, but was missing afterwards.
I just re-added it in 3.0 via 9626d339603e695d8c2b76e5ac6d38cd0a146e06

**Comment by baslr** [comment]
Thanks.

**Comment by dothebart** [comment]
3.0.0 RC2 containing this fix is available for download via https://www.arangodb.com/download-preview/ 
Enjoy.
