### ISSUE TITLE
[3.0b] Importing queries in web admin is broken

### ISSUE THREAD

**Issue by ropeladder** [arangodb/arangodb#1863]
Importing queries using the web admin does work in most cases I have tried. I get a green confirmation toaster at the bottom but the 'imported' queries do not show up in the query list. Sometimes I can see another modal window that looks like an error popping up after trying to import, but it's mostly covered by the import modal and it only lasts for a split second. I get similar behavior in both Firefox 46 and Chromium 50. I'm on Linux Mint 17.3 64-bit.

I *can* get the import to work but only for queries that I have just created manually and then exported. In this case I am able to import the query back in multiple times with no problem. But if I try and import a different query it stops working, and then the recently-exported query will not import any more either.

**Comment by hkernbach** [comment]
Thanks. Also this was related to #1872 . Both fixed.
