### ISSUE TITLE
[3.0b] Custom AQL function "Number out of range" error

### ISSUE THREAD

**Issue by ropeladder** [arangodb/arangodb#1865]
I am getting an error when trying to run a custom AQL function on a large document collection (2.2 million records) from the Web Admin queries page:

`Query: Number out of range (while executing) Exception location: '/usr/src/packages/BUILD/arangod/RestHandler/RestCursorHandler.cpp:128'. Please report this error at arangodb.com.`

However, this error is only visible for a split second (I could only read it by clicking the Query button repeatedly) and the toaster alert is then replaced with:

`Query: Successfully aborted.`

The problem appears to be with the collection size, since I simplified the query down to just `function(data){return data}`, and also tried creating an identical new function, and it still gave me the same problem. I get no error on a small test collection with one document.

I'm running Linux Mint 17.3 64b.

**Comment by Simran-B** [comment]
What do you pass in as argument to the function? A single document or
attribute?

**Comment by ropeladder** [comment]
I was passing in a document. However, I just tried again to replicate (after a full reboot) and everything appears to be working fine using the exact same large collection with either the simple test function or a more complicated one.

**Comment by hkernbach** [comment]
Frontend UI error fixed.

**Comment by ropeladder** [comment]
Haven't been able to reproduce initial problem since the first time I restarted.
