### ISSUE TITLE
LIMIT 0, 1 returns 0 documents whereas LIMIT 0, 2 returns 1.

### ISSUE THREAD

**Issue by thwd-duda** [arangodb/arangodb#1866]
I am executing the following query:
```
FOR o IN iNlbRILoxUd LIMIT 0, 1 FILTER o._key == "lVxIycCeLdCB" RETURN o
```
And getting 0 results.

If I change the `LIMIT`-clause to `LIMIT 0, 2`, then I get one result. Which is what I expected to get using `LIMIT 0, 1`.

`iNlbRILoxUd` is a loaded, non-system, non-erroneous document-collection where `allowUserKeys` is enabled and using the traditional key-type.

```
~$ arangod --version
architecture: 64bit
build-date: 2016-05-14 08:27:23
configure:  './configure' 'CC=gcc' 'CXX=g++' 'CFLAGS=-g -O3 -fomit-frame-pointer' 'CXXFLAGS=-g -O3 -fomit-frame-pointer' '--enable-gold' '--enable-tcmalloc' '--program-prefix=' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib' '--libexecdir=/usr/lib' '--localstatedir=/var' '--sharedstatedir=/usr/com' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--enable-all-in-one-etcd' '--enable-internal-go'
env:  CFLAGS='-g -O3 -fomit-frame-pointer' CXXFLAGS='-g -O3 -fomit-frame-pointer' CC='gcc' CXX='g++'
fd-client-event-handler: poll
fd-setsize: 1024
icu-version: 54.1
libev-version: 4.11
maintainer-mode: false
openssl-version: OpenSSL 1.0.2d 9 Jul 2015
server-version: 2.8.9
sizeof int: 4
sizeof void*: 8
tcmalloc: true
v8-version: 4.3.61
```
```
~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 15.10
Release:	15.10
Codename:	wily
```

**Comment by mchacki** [comment]
Hi @thwd-duda 

The position of the `LIMIT` clause matters in your query.

So in your example it will first iterate over the collection.
It will pick exactly! 1 document (randomly) <- Limit kicks in here
It will take the one document and filter it's _key.
In a lucky case it works. in most cases you do not get the document.

If you switch LIMIT and FILTER:

```
FOR o IN iNlbRILoxUd FILTER o._key == "lVxIycCeLdCB"  LIMIT 0, 1 RETURN o
```

It will first pick all documents from your collection with the key (which is one anyways, _key is unique)
And then it will reduce the result-set by picking only the first of them.

**Comment by Simran-B** [comment]
Have a look here: https://docs.arangodb.com/3.0.0b1/AQL/Operations/Filter.html

It is about FILTER, but it gives an example how the order of operations affects queries.
