### ISSUE TITLE
Error: 1540, ArangoError, usage of unknown function 'GRAPH_NEIGHBORS()

### ISSUE THREAD

**Issue by ile** [arangodb/arangodb#1867]
My installation on ArangoDB just got updated, and now I'm getting this error:

`Error: 1540, ArangoError, usage of unknown function 'GRAPH_NEIGHBORS()' (while parsing)`

I didn't find anything in docs/CHANGELOG.

I'm doing this kind of query:

```
{ query: 'FOR g in GRAPH_NEIGHBORS(@v0, @v1, @v2) RETURN g',
  values: 
   { v0: 'follows',
     v1: 'auths/2cdaf8c2-c2f8-4c54-8e5c-717fab8b01d9',
     v2: { direction: 'outbound' } } }
```

**Comment by baslr** [comment]
Hi @ile,

with ArangoDB v3 graph functions are replaced:
https://docs.arangodb.com/cookbook/AQL/MigratingGraphFunctionsTo3.html
https://docs.arangodb.com/cookbook/AQL/MigratingEdgeFunctionsTo3.html
https://docs.arangodb.com/cookbook/AQL/MigratingMeasurementsTo3.html

You have to use the traversal syntax.

**Comment by ile** [comment]
OK, thanks!

(I didn't look at the right place, I tried this: https://docs.arangodb.com/Installing/Upgrading.html).
