### ISSUE TITLE
[3.3b] CONCAT() functions not parsing arrays correctly

### ISSUE THREAD

**Issue by ropeladder** [arangodb/arangodb#1868]
When I pass an array to the CONCAT() AQL string function it doesn't parse the array's brackets correctly:

`RETURN CONCAT([ "foo", "bar", "baz" ])`

returns

`[
  "[\"foo\",\"bar\",\"baz\"]"
]`

`RETURN CONCAT_SEPARATOR(", ", [ "foo", "bar", "baz" ])` gives the exact same result

`CONCAT("foo", "bar", "baz" )` and `CONCAT_SEPARATOR(", ",  "foo", "bar", "baz" )` work as expected.

**Comment by ropeladder** [comment]
Nevermind, it's fixed in the new release candidate.

**Comment by Simran-B** [comment]
The behavior of casting arrays and objects to string was not well-defined before, but it is basically JSON-encoded now. This changed the behavior of the `CONCAT` functions, but we figured that they should concatenate the elements of an array, if an array is passed as sole argument.

Alternatively, you could've used `APPLY("CONCAT", ["foo", "bar", "baz"])`, but yeah, it's changed for the better in the latest release.
