### ISSUE TITLE
stacktrace: SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by ile** [arangodb/arangodb#1870]
I'm following this: https://docs.arangodb.com/cookbook/AQL/MigratingGraphFunctionsTo3.html#option-neighborexamples

```
127.0.0.1:8529@some> db._query('FOR n IN ANY @startId GRAPH @graphName OPTIONS {bfs: true, uniqueVertices: 'global'} RETURN n', { startId: 'auths/2cdaf8c2-c2f8-4c54-8e5c-717fab8b01d9', graphName: 'follows' });
JavaScript exception: SyntaxError: missing ) after argument list
!db._query('FOR n IN ANY @startId GRAPH @graphName OPTIONS ({bfs: true, uniqueVertices: 'global'}) RETURN n', { startId: 'auths/2cdaf8c2-c2f8-4c54-8e5c-717fab8b01d9', graphName: 'follows' });
!          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
stacktrace: SyntaxError: missing ) after argument list
```

Am I doing something wrong?

Seems that it works if I do this, but then I lose the options:

```
127.0.0.1:8529@some> db._query('FOR n IN ANY @startId GRAPH @graphName RETURN n', { startId: 'auths/2cdaf8c2-c2f8-4c54-8e5c-717fab8b01d9', graphName: 'follows' });
[object ArangoQueryCursor, count: 2, hasMore: false]
```

**Comment by ile** [comment]
This works:

```
db._query('FOR n IN ANY @startId GRAPH @graphName OPTIONS { bfs: true } RETURN n', { startId: 'auths/2cdaf8c2-c2f8-4c54-8e5c-717fab8b01d9', graphName: 'follows' });
```

**Comment by Simran-B** [comment]
You are terminating the query string in the middle of the query:

    db._query('FOR n IN ANY @startId GRAPH @graphName OPTIONS {bfs: true, uniqueVertices: 'global'} RETURN n', { startId: '...', graphName: 'follows' });
              ^---------------------------------------------------------------------------^

It has to be one of the following however:

    db._query("FOR n ... OPTIONS {bfs: true, uniqueVertices: 'global'} RETURN n"
    db._query('FOR n ... OPTIONS {bfs: true, uniqueVertices: "global"} RETURN n'
    db._query(`FOR n ... OPTIONS {bfs: true, uniqueVertices: 'global'} RETURN n`
    db._query(`FOR n ... OPTIONS {bfs: true, uniqueVertices: "global"} RETURN n`
    db._query('FOR n ... OPTIONS {bfs: true, uniqueVertices: \\'global\\'} RETURN n'

Note that backslash escapes require an additional backslash in arangosh. This is not the case in the web interface, you would write `\'` there to escape a `'` in a string that is enclosed by `'`.

**Comment by ile** [comment]
Oh, oops. Sorry about that, didn't notice. Closing.
