### ISSUE TITLE
MS Edge and MS IE Refresh problem

### ISSUE THREAD

**Issue by AaronNGray** [arangodb/arangodb#1871]
I am having to hit F5 in both IE and Edge after creating Databases, Collections, and Graphs using the ArangoDB Web Interface on http://127.0.0.1:8529 before the items appear in the displayed list. I am not experiencing this problem on either Google Chrome or Mozilla FireFox; the new item appear immediately once created on them.

I am using ArangoDB 2.8.9 standalone service on Windows 10 Pro.

**Comment by hkernbach** [comment]
Thanks for the feedback. Fixed in devel branch. For IE & Edge you have to force ajax caching, otherwise they will just ignore the response...
