### ISSUE TITLE
[3.0.0-rc1] "Query: Could not save query" when saving query in web UI (though query is saved)

### ISSUE THREAD

**Issue by rbrewer101** [arangodb/arangodb#1872]
When saving a query via the web UI, a [popup](https://slack-files.com/T07NV0TD4-F1G7EC9M4-227041b5ff) appears at screen bottom, "Query: Could not save query" (even though the query is actually saved). Also get a "Query: Could not delete query" when deleting a saved query (even though it is actually deleted).

**Comment by ropeladder** [comment]
I'm getting this same error, or at least a very similar one.

When I go to the query list after saving a query, it sometimes shows the query twice.

HOWEVER when reloading the page, all the queries disappear, so the query does not appear to have been saved permanently to the database.

**Comment by hkernbach** [comment]
Thanks. Also this was related to #1872 . Both fixed.
