### ISSUE TITLE
Can upgrade the node modules to latest version? 

### ISSUE THREAD

**Issue by dsonet** [arangodb/arangodb#1874]
Like joi, lodash, the version provided in arangodb are just too old.

**Comment by pluma** [comment]
Hi dsonet,

the versions will be upgraded in ArangoDB 3.0. Some of the modules made use of language features not available in the version of V8 being used in ArangoDB 2.8 so we could not upgrade them earlier.

I have just updated all dependencies to the latest release in the development branch and will merge the change into the branch for the upcoming 3.0.0 release once our tests pass.

**Comment by dsonet** [comment]
@pluma It's very great to know that.

**Comment by pluma** [comment]
There seem to be some unrelated test failures at the moment. Looks like the upgrades will be in 3.0.0 but probably not 3.0.0-rc2.

**Comment by pluma** [comment]
Everything seems to be working fine. The relevant commits will be cherry-picked into the upcoming 3.0 release.
