### ISSUE TITLE
RHEL 6 binaries for ArangoDB 3.0rc2

### ISSUE THREAD

**Issue by sajeevpr** [arangodb/arangodb#1875]
Team,

  It would be helpful if you can publish/provide the RHEL 6 binaries. It is difficult and time consuming for us to upgrade now to RHEL 7 or compile in RHEL 6 with all dependencies.

Thanks,
Sajeev

**Comment by dothebart** [comment]
We're currently struggling to get a recent GCC running on RHEL6 with the SuSE OBS. If you can provide any help, that would be appreciated.

**Comment by sajeevpr** [comment]
Which version of gcc you are trying to install?

**Comment by dothebart** [comment]
meanwhile the compiler is available, a newer version of cmake than 2.8 is now missing; the latest (3.5) won't compile for RHEL6.

**Comment by sajeevpr** [comment]
Got the binaries from the above links. Testing it now. Thanks for the help

**Comment by dothebart** [comment]
thanks, I think we can close this issue now.
