### ISSUE TITLE
Strange Behavior with Subquery

### ISSUE THREAD

**Issue by stefanwuthrich** [arangodb/arangodb#18768]
## My Environment

* __ArangoDB Version__:   3.9.2     
* __Deployment Mode__:    Single   
* __Deployment Strategy__:  Manual Start in Docker  
* __Configuration__:               
* __Infrastructure__:        own       
* __Operating System__:    Debian 10    
* __Total RAM in your machine__:    64 GB    
* __Disks in use__:   1 SSD     
* __Used Package__:              

## Component, Query & Data

__Affected feature__:

AQL with web and driver (Golang)

__AQL query (if applicable)__:
```
FOR d IN contact  FILTER !d.isDeleted  LET acc = (FOR a IN account FILTER a.id == d.accountId RETURN a)[0]  UPDATE d WITH { accountName: acc.name, accountOwnedByUserId: acc.ownedByUserId } IN contact  SORT d.createdAt desc  LIMIT 0,200 RETURN d

```
__AQL explain and/or profile (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1.  I create a new Contact
2.  I run the query above a first time, and do not get accountName and AccountOwnedByUser Id values (empty), for the new contact (all others are filled)
3. I run the same query a second time and the values are filled

__Problem__:
Data inconsistent on first run

__Expected result__:
Data is there as after second query

**Comment by dothebart** [comment]
Hi, can you please upgrade to ArangoDB 3.9.10 and check back whether the issue persists?

**Comment by stefanwuthrich** [comment]
Sure,  updated to 3.9.10. same issue

**Comment by stefanwuthrich** [comment]
any update, please?

**Comment by Simran-B** [comment]
You iterate over the collection `contact`, which emits the variable `d`, perform the update, but then you `RETURN d`, which is still the original value from before the update and does thus not include the new attributes. If you want the value of the updated document, use the pseudo-variable `NEW` instead:

```
SORT NEW.createdAt DESC LIMIT 0, 200 RETURN NEW
```
