### ISSUE TITLE
[3.0rc2] Graph management UI - can't select from dropdowns with mouse

### ISSUE THREAD

**Issue by ropeladder** [arangodb/arangodb#1876]
In the front-end graph management interface it doesn't appear possible to select collections (edgeCollections, toCollections, etc...) by clicking on them in the dropdown. The dropdown closes but nothing appears in the entry box. Using the keyboard arrow keys or typeahead and hitting enter does work.

**Comment by hkernbach** [comment]
Which browser, os?

**Comment by ropeladder** [comment]
Linux Mint 17.3 using either Firefox 47 or Chromium 50.

**Comment by Simran-B** [comment]
Seen this as well together with some other strange misbehavior on Windows 10, using any of the major browsers. I believe it's broken for everyone.

**Comment by andybarilla** [comment]
Same here. Linux Mint & Win 10 both Chrome.

**Comment by hkernbach** [comment]
We've added a temporary fix which should prevent that behaviour. It is a temporary fix, because it is a bit dirty. The implemented select2 library is outdated (https://select2.github.io/). So we will update the library or look for a replacement.
