### ISSUE TITLE
[3.0rc2] Users not visible in web interface

### ISSUE THREAD

**Issue by MatthiasF999** [arangodb/arangodb#1878]
After adding a user per web interface, it doesn't appear in users (but is created in the collection). The user also doesn't appear in the user dropdown when adding a database.
The only visible user is root.

I tested it with windows 10 and inside a docker container.

**Comment by ciscoheat** [comment]
Same for me on win7 with rc2, native installation.

**Comment by hkernbach** [comment]
Thanks, it's fixed.

**Comment by ciscoheat** [comment]
Still don't work for me. Steps to reproduce:

1. Browse to [http://localhost:8529/_db/_system/_admin/aardvark/index.html#users](http://localhost:8529/_db/_system/_admin/aardvark/index.html#users)
1. Click "Add user" and create a user with valid info
1. The Add user dialog disappears with no confirmation or changes.

Reloading the page won't show any users other than root, but adding the same user again gives the error message `User: duplicate user`. Looking in the _users collection, the newly created user is there.

**Comment by hkernbach** [comment]
I'm sorry but I do not have an exact overview of which changes made it into RC3. Building devel and 3.0 branch, the error is non-existent.

**Comment by Simran-B** [comment]
@ciscoheat: did you try it in a private browsing window? Otherwise it might still use cached versions of the scripts.

**Comment by ciscoheat** [comment]
@Simran-B yes, tested in private window and with cache cleared, no difference.

**Comment by ciscoheat** [comment]
Working now with 3.0.0! Thanks, and great job on the release!

**Comment by hkernbach** [comment]
Great. Have fun 😜
