### ISSUE TITLE
Issue Running ArangoDB on CentOS 7 server

### ISSUE THREAD

**Issue by zaphodis42** [arangodb/arangodb#18795]
## My Environment

* __ArangoDB Version__:        3.10.2 - both Binary / self compiled
* __Deployment Mode__:       Single Server, Cluster
* __Deployment Strategy__:   ArangoDB Starter
* __Infrastructure__:               Own

> bash-4.2$ cat /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
stepping	: 1
microcode	: 0xb000038
cpu MHz		: 2197.480
cache size	: 25600 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes f16c rdrand hypervisor lahf_lm abm invpcid_single kaiser fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit
bogomips	: 4394.96
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual

* __Operating System__:        CentOS 7
* __Total RAM in your machine__:       16 GB
* __Disks in use__:        SSD
* __Used Package__:             Both binary and trying to compile github branch 3.10.2

## Component, Query & Data
__Affected feature__: Installation

## Steps to reproduce

- Trying to start server using binary 
1. 

> tar -xzf arangodb3-linux-3.10.5-2_x86_64.tar.gz
cd arangodb3-linux-3.10.5-2_x86_64/bin
./arangodb create jwt-secret --secret=arangodb.secret
chmod 400 arangodb.secret
./arangodb --starter.local --starter.data-dir=./localdata2 --auth.jwt-secret=./arangodb.secret

2. 

> bash-4.2$ ./arangodb --starter.local --starter.data-dir=./localdata2 --auth.jwt-secret=./arangodb.secret
2023-04-28T09:30:24+05:30 |INFO| Starting arangodb version 0.15.7, build 0cd0439 component=arangodb
2023-04-28T09:30:24+05:30 |INFO| Failed to read configuration file "/home/dev/arangodb3/bin/localdata2/setup.json" error="open /home/dev/arangodb3/bin/localdata2/setup.json: no such file or directory" component=arangodb
2023-04-28T09:30:24+05:30 |INFO| Wait on 3951 returned component=arangodb core-dump=true signal="illegal instruction" trap-cause=-1
2023-04-28T09:30:24+05:30 |WARN| Error while getting version error="Process exited with exit code -1 - " component=arangodb
2023-04-28T09:30:25+05:30 |INFO| Wait on 3956 returned component=arangodb core-dump=true signal="illegal instruction" trap-cause=-1
2023-04-28T09:30:25+05:30 |WARN| Error while getting version error="Process exited with exit code -1 - " component=arangodb
2023-04-28T09:30:26+05:30 |INFO| Wait on 3958 returned component=arangodb core-dump=true signal="illegal instruction" trap-cause=-1
2023-04-28T09:30:26+05:30 |WARN| Error while getting version error="Process exited with exit code -1 - " component=arangodb

- Compiling from source:
1) 

> cd arangodb
mkdir build
cd build
yum install centos-release-scl devtoolset-9
scl enable devtoolset-9 bash
cmake3 .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUSE_MAINTAINER_MODE=off -DUSE_OPTIMIZE_FOR_ARCHITECTURE=On -DUSE_GOOGLE_TESTS=off 
nohup make -j2 & 

gives error :

> CXX(target) /home/devkiran/arangosource/ArangoDB-3.10.5-2/build/3rdParty/V8/v7.9.317/x64.release/obj.target/v8_snapshot/geni/snapshot.o
  CXX(target) /home/devkiran/arangosource/ArangoDB-3.10.5-2/build/3rdParty/V8/v7.9.317/x64.release/obj.target/v8_snapshot/../v7.9.317/src/snapshot/embedded/embedded-empty.o
  AR(target) /home/devkiran/arangosource/ArangoDB-3.10.5-2/build/3rdParty/V8/v7.9.317/x64.release/obj.target/../gypfiles/libv8_snapshot.a
[ 28%] No install step for 'v8_build'
[ 28%] Completed 'v8_build'
[ 28%] Built target v8_build
make: *** [Makefile:172: all] Error 2

__Expected result__:

ArangoDB server should start on my server

(Runs fine on my local machine - Mac M1 chip, or on a AWS EC2 instance with ubuntu)

**Comment by dothebart** [comment]
Well, our provided Binaries make use of certain modern cpu features because of this benefits many users with way better peformance.  We optimize for sandy-bridge or later CPUs. it puzzles me a bit that https://ark.intel.com/content/www/de/de/ark/products/64593/intel-xeon-processor-e52630-15m-cache-2-30-ghz-7-20-gts-intel-qpi.html enlists yours as one of those?
The part of the error you've posted doesn't contain the real issue. 
https://github.com/arangodb/arangodb/blob/v3.10.6/VERSIONS enlists the compiler dependencies.

**Comment by Simran-B** [comment]
It seems like the CPU supports the necessary instructions based on the flags you posted, so it's unclera what the offending instruction is. If you want to find out, you can try this Intel tool to track all instructions used: https://www.intel.com/content/www/us/en/developer/articles/tool/software-development-emulator.html
