### ISSUE TITLE
Can't stop service with 3.0-RC2

### ISSUE THREAD

**Issue by andybarilla** [arangodb/arangodb#1879]
Shutting down the service doesn't stop anything.  

"Waiting for shutdown" shows for several seconds before continuing. If I try stopping the service again, it doesn't pause at that point.

```
➜  ~ sudo service arangodb3 start
 * Starting arango database server arangod
/etc/init.d/arangodb3: 37: ulimit: error setting limit (Invalid argument)
{startup} starting up in daemon mode
changed working directory for child process to '/var/tmp'
                                                                                                                                                            [ OK ]
➜  ~
➜  ~ sudo service arangodb3 stop
 * Stopping arango database server arangod                                                                                                                  [ OK ]
 * Waiting for shutdown                                                                                                                                     [ OK ]
➜  ~ ps ax | grep arango
17758 pts/0    S+     0:00 tail -F /var/log/arangodb3/arangod.log
17905 ?        Ss     0:00 /usr/sbin/arangod --uid arangodb --gid arangodb --pid-file /var/run/arangodb/arangod.pid --temp.path /var/tmp/arangod --log.foreground-t
ty false --supervisor
17906 ?        Sl     0:02 /usr/sbin/arangod --uid arangodb --gid arangodb --pid-file /var/run/arangodb/arangod.pid --temp.path /var/tmp/arangod --log.foreground-t
ty false --supervisor
➜  ~
```

**Comment by jsteemann** [comment]
In general the server may not shut down instantly. 
Shutdown time may increase if there are still long-running queries or other operations going on when the shutdown command is executed. In this case the ongoing operations may still be finished before the shutdown is executed. Additionally the server will flush all of its logfile data to disk, which will cause some I/O (that can be slow).
But the service should stop *eventually*. If it doesn't, especially when there is nothing going on, then this doesn't seem right. Is the problem reproducible on your system? What OS is it running on, and is there any known server activity (arangod serving requests, CPU usage, high I/O etc.) when the service does not stop?

**Comment by andybarilla** [comment]
I tested with a fresh install of Ubuntu 14.04. It did take a little over 10 minutes to shut down a fresh install. I didn't wait that long earlier.

**Comment by jsteemann** [comment]
10 minutes seems way too long, provided the instance was (almost) empty and did not do much when the shutdown occurred. But I can't tell if that was the case. Was that instance doing anything (e.g. serving requests, running queries) when the shutdown happened? And was the Ubuntu it ran on providing enough resources in terms of RAM, CPU and disk I/O?

**Comment by andybarilla** [comment]
It was a fresh install on a fresh VM so nothing should have been making requests. It's a default Nitrous.IO VM which has 1GB RAM and 1GB of swap. CPU usage is less than 1%. Arango is the only thing using any significant amount of memory at 28.3%.

**Comment by jsteemann** [comment]
Do you happen to know if there was any activity (CPU, swapping, requests) during the shutdown phase?

**Comment by andybarilla** [comment]
Occasionally, the arangod process would go up to close to 1% CPU usage from 0% but that was about it from what I could see. If you want, I can give you access to the VM. I'm not planning on using it. I just set it up to verify this problem. You can email me (bassburner at gmail dot com) your email for access via Nitrous.IO or an public key for SSH access if you want.

**Comment by jsteemann** [comment]
The reason for the service not stopping was the `service arangodb3 stop` triggers the command
`start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON`, which does not work on the Nitrous VM.
`--exec` is for matching executables by (absolute) path name, and `$DAEMON` in this case is `/usr/sbin/arangod`, which is correct. Still the command fails because it uses the output of `/proc/<pid>/exe`, which fails on Nitrous. Seems that Nitrous is blocking access to `/proc` so `start-stop-daemon` will never find any executables.
It works on all the local Ubuntus (14.04, 15.x and 16.04) we tested, where accessing /proc is allowed.

A workaround for the problem is to not use the `--exec` option for matching the processes, but we don't want to change the start/stop script at the moment because we don't know if that would have any side effects.
