### ISSUE TITLE
Access-Control-Allow-Credentials not set in response

### ISSUE THREAD

**Issue by ciscoheat** [arangodb/arangodb#1882]
According to https://docs.arangodb.com/GeneralHttp/index.html 

> any access-control-allow-credentials header sent by the client is ignored by ArangoDB its value is not true. If a client sends a header value of true, ArangoDB will return the header access-control-allow-credentials: true, too.

It seems like this isn't working properly, even if this header is set by the client in a CORS request, the response header will be set to false.

See this for context https://github.com/arangodb/arangojs/pull/249 and an additional problem; even when forcing the header to be true, no `Authorization` header is sent so the response will be 401. Also, adding an `Authorization` header alleviates the need for the `Access-Control-Allow-Credentials` header and `xhr.withCredentials`.

**Comment by jsteemann** [comment]
It's probably because the option `--http.trusted-origin` was not set to either `"http://localhost:3000"` or `"*"` at server start. 
I saw [the docs](https://docs.arangodb.com/GeneralHttp/index.html) did not mention `--http.trusted-origin`, so I added it via 30e978fe5508e8c740560b76beddf6b0df05a442.

**Comment by ciscoheat** [comment]
Even with `--http.trusted-origin http://localhost:3000`, the preflight header is false:

![preflight 2](https://cloud.githubusercontent.com/assets/130450/16193590/61e91b26-36f0-11e6-8c3b-9f8dfef6c91e.png)

And when I use [Requestly](https://chrome.google.com/webstore/detail/requestly/mdnleldcmiljblolnjhpnblkcekpdkpa?hl=en) to rewrite the preflight header to true, that response returns true from server. Requestly doesn't modify the chrome debug output, so it's confirmed that the server is setting the header correctly after the preflight:

![postflight](https://cloud.githubusercontent.com/assets/130450/16193656/c89c9212-36f0-11e6-8934-6b1bb60bf732.png)

**Comment by jsteemann** [comment]
Yes, on preflight the `Access-Control-Allow-Credentials` is false because the request does not contain the header `Access-Control-Allow-Credentials: true`. Currently this header must be set in all requests in addition to a trusted `Origin` value. Otherwise the server will respond with `Access-Control-Allow-Credentials: false`.

**Comment by ciscoheat** [comment]
I'm a bit confused what header this options is affecting? According to https://docs.arangodb.com/3.0/Manual/ReleaseNotes/UpgradingChanges30.html#handling-of-cors-requests it should set the `Access-Control-Allow-Credentials` to true, but at the end of the section it also states that it will set `Access-Control-Allow-Origin`. Which one is it?

**Comment by ciscoheat** [comment]
I set the `Access-Control-Allow-Credentials` to true on the above request(s), but for reasons unknown to me, it's not included in the preflight. You see on the second request that it's supposed to be included.

**Comment by ciscoheat** [comment]
With 3.0.0-rc2, without any `http.trusted-origin` set, an CORS request returns the origin header, like:

`Access-Control-Allow-Origin: http://localhost:3000`

Here's a successful request, without the `http.trusted-origin`:

![working get](https://cloud.githubusercontent.com/assets/130450/16194256/f8d63b4c-36f3-11e6-8088-35bb3c3cbf48.png)

**Comment by jsteemann** [comment]
The docs are slightly wrong in this case.
It works like this:
If the request contains an `Access-Control-Allow-Credentials` header with value `true` and there is a non-empty `Origin` header that matches one of the trusted origins specified via `--server.trusted-origin`, then the server will respond with `Access-Control-Allow-Credentials: true`. Otherwise it will return `Access-Control-Allow-Credentials: false`.
The `Access-Control-Allow-Origin` response header will be always set to the same `Origin` value used in the request.

**Comment by ciscoheat** [comment]
Ok, then that works as I expected. The only issue I have then is the missing `Access-Control-Allow-Credentials: true` header on the preflight, even if `http.trusted-origin` is set to the same as the origin (as in the first two screenshots).

**Comment by jsteemann** [comment]
mmmh, looks like the browser doesn't set it in its OPTIONS request. Is it safe to always set this header on the server-side if the browser doesn't send it but if the `Origin` value is in the trusted list? Probably.

**Comment by pluma** [comment]
I think the Allow-Credentials only refers to cookies and basic auth credentials already known to the browser (i.e. entered from a browser popup or navigated to via a URL string). However the request header should be set when the XHR is created "withCredentials". I'm not sure whether the browser still silently discards it when it has no cookies or auth to offer (explicit auth headers provided in the XHR by the developer seem to be unrelated to this).

**Comment by dothebart** [comment]
Ok, since the conclusion of the above discussion is, that this is not an issue, I will close this now.
