### ISSUE TITLE
index support for LIKE Operator wanted

### ISSUE THREAD

**Issue by sajeevpr** [arangodb/arangodb#1886]
We are facing performance issue when tried with like queries.

The field is indexed with full text.

Query used:

```
FOR node IN GROUP
    FOR acc IN account
        FILTER node.acc_key = acc.acc_key AND acc.name like '%abc%'
        LIMIT 10
    RETURN acc
```

When I remove the %, it is taking only < 5 ms, Otherwise it is almost 70 seconds.

**Comment by Simran-B** [comment]
LIKE cannot utilize any index, a full collection scan is required. Fulltext indexes support prefix matches, but you need to call FULLTEXT() to use it. Suffix matches or having wildcards on both sides are not possible, it would require a different type of index, which would consume quite some memory.

How much data are you scanning there?

**Comment by sajeevpr** [comment]
I am scanning 18 million records.Is there any alternative as this is a critical use case for us.

Thanks,
Sajeev

**Comment by dothebart** [comment]
do I get that correctly that you're missing a `FILTER` in front of `node.acc_key = acc.acc_key` and can you revalidate with explain that this part uses an index?
How much does it reduce the dataset? Means - on how many remaining documents do you have to do the `like` ?

**Comment by Simran-B** [comment]
If you really have to partial-match a lot of records, a workaround could be to store n-grams of the name in a separate attribute (managed by your application) and put an array index on it:

    {
        acc: {
            name: "FooBar",
            ngrams: ["foo", "oob", "oba", "bar"]
        }
    }

Note that a minimum search phrase length of 3 is assumed. When searching in the ngrams, you can use a hash array index to search for 3 consecutive letters, even if the search phrase is longer. This should already reduce the result set, and you can then check if the rest matches in a second step.

But be sure to check out dothebart's remark first.

**Comment by sajeevpr** [comment]
@dothebart  ,Actually the FILTER is there
@Simran-B - the solution seems to be very difficult to manage. Are you planning to support like queries with index as this is one of the basic requirements for any project.

**Comment by sajeevpr** [comment]
@dothebart  - this part - node.acc_key = acc.acc_key uses an index.

**Comment by dothebart** [comment]
We're currently not yet set on the post 3.0 Roadmap, so I can't give you an ETA on whether & wen support for this is going to be implemented. So for the time being you will have to find a different solution to reduce the number of hits first so that the number of documents to actually be inspected by the LIKE filter gets into an acceptable range.
If you're searching for complete words, the fulltext index could be such a way; If you're able to reduce it to a right side match, you could use a skiplist index with range queries (`>`, `>=` ...).

**Comment by sajeevpr** [comment]
ok. Hope to see this feature in the upcoming releases. I think incorporating this feature can replace the search engines like SOLR and elastic search which are lacking the join feature.

**Comment by Simran-B** [comment]
I agree that there is a need for efficient partial string matching. Have a look at another discussion regarding this topic: #1796

There are some interesting papers like this one: http://pages.di.unipi.it/grossi/PAPERS/sicomp05.pdf

**Comment by sajeevpr** [comment]
@Simran-B , Is this feature included as part of the road map and any ETA if it is included in your list.

**Comment by sajeevpr** [comment]
@Simran-B , Please let me know if this feature would be available in the upcoming releases.

Thanks

**Comment by baslr** [comment]
came across "What about substring search on an index (fast LIKE)? It can be made fast with a trigram index. [8][9]"
[8] https://about.gitlab.com/2016/03/18/fast-search-using-postgresql-trigram-indexes/
[9] http://blog.scoutapp.com/articles/2016/07/12/how-to-make-text-searches-in-postgresql-faster-with-trigram-similarity

**Comment by YukiSakuraVN** [comment]
It's almost 4 years, can we use trigram built-in on ArangoDb? As I don't want to install PostgreSQL just to use faster LIKE operator text search.

**Comment by MrPieces** [comment]
Hi @YukiSakuraVN

LIKE operator for text search will be part of the upgrades to ArangoSearch in the upcoming ArangoDB 3.7 release. The operator will make use of indexes for fast query execution.

Just FYI: The upgrades to ArangoSearch also include fuzzy search (ngram & Levenshtein), improved phrase & proximity search, wildcard search and a few improvements more You can find a few more details here https://www.arangodb.com/arangodb-training-center/search/arangosearch-tutorial-3-7/ and in our docs https://www.arangodb.com/docs/devel/aql/functions-arangosearch.html

Hope this was helpful

**Comment by YukiSakuraVN** [comment]
> Hi @YukiSakuraVN
> 
> LIKE operator for text search will be part of the upgrades to ArangoSearch in the upcoming ArangoDB 3.7 release. The operator will make use of indexes for fast query execution.
> 
> Just FYI: The upgrades to ArangoSearch also include fuzzy search (ngram & Levenshtein), improved phrase & proximity search, wildcard search and a few improvements more You can find a few more details here https://www.arangodb.com/arangodb-training-center/search/arangosearch-tutorial-3-7/ and in our docs https://www.arangodb.com/docs/devel/aql/functions-arangosearch.html
> 
> Hope this was helpful

That sounds great. Looking for the release. Thank you very much.

**Comment by dothebart** [comment]
Hi, 
ArangoDB 3.7.2 has been released and is available for download. 
For more details please check out: https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/
