### ISSUE TITLE
Explain hung in GUI. But working in arangosh

### ISSUE THREAD

**Issue by sajeevpr** [arangodb/arangodb#1887]
Team,
  When I am trying to use the explain functionality in GUI, it hungs. But I am getting the output in arangosh.

Regards,
Sajeev

**Comment by dothebart** [comment]
Could reproduce with any query that can run on the current dataset.

Firebug logs:

    1466582089645	Toolkit.GMP	ERROR	GMPInstallManager.onLoadXML could not load xml: [Exception... "SSL is required and URI scheme is not https."  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: resource://gre/modules/CertUtils.jsm :: checkCert :: line 142"  data: no]

    1466582089645	Toolkit.GMP	ERROR	GMPInstallManager.simpleCheckAndInstall Could not check for addons: {"target":{},"status":200,"message":"[Exception... \"SSL is required and URI scheme is not https.\"  nsresult: \"0x8000ffff (NS_ERROR_UNEXPECTED)\"  location: \"JS frame :: resource://gre/modules/CertUtils.jsm :: checkCert :: line 142\"  data: no]"}

**Comment by hkernbach** [comment]
Cannot reproduce. Which OS, Browser (+ Version), ArangoDB Mode (Cluster / Standalone), authentication enabled?

**Comment by sajeevpr** [comment]
RHEL6.6
Chrome Version 40.0.2214.115 m
Arangodb 3 - standalone
no authentication enabled

**Comment by hkernbach** [comment]
Could you try with a newer version of chrome? The current version is 51.0.2704.106 (64-bit). If it is not working with the latest chrome release, please reopen this ticket.
