### ISSUE TITLE
Inconsistent font in arangodb GUI when browsing collection and left panel

### ISSUE THREAD

**Issue by sajeevpr** [arangodb/arangodb#1889]
Team,
  I am getting broken fonts while browsing collection as well as in left panel.

Browser - chrome
version - Version 40.0.2214.115 m

Regards,
Sajeev

**Comment by dothebart** [comment]
can you post a screenshot and mark the section you're talking about?

**Comment by sajeevpr** [comment]
Some how I am unable to attach. Getting the below message.

Something went really wrong, and we can't process that file.

Regards,
Sajeev

**Comment by Simran-B** [comment]
Make sure it's a jpg or png. You may also upload it elsewhere and post just
the link (e.g. imgur)

**Comment by dothebart** [comment]
I saw that with a mac you can just paste it into the edit area of the issue

**Comment by sajeevpr** [comment]
I tried , but no luck. May be due to network restrictions. Please re-post the image if possible.

**Comment by dothebart** [comment]
http://picpaste.com/ ?

**Comment by baslr** [comment]
@sajeevpr Google Chrome version 40 from 01/2015 is really a security risk. I recommend to upgrade to the latest version (51) since then there are some critical security fixed. Or at least announce this to your Network / IT administrator so you don't get blamed when something happens ;)

**Comment by sajeevpr** [comment]
ok. Thank you. will check in the latest version.

**Comment by sajeevpr** [comment]
I tried with arangodb 3.0 version in firefox version - 43.0.1.

The issue is still there.

**Comment by hkernbach** [comment]
Sorry, we were not able to reproduce this issue. Detailed instructions on how we could reproduce the behaviour would help us a lot. Until then the issue is closed.
