### ISSUE TITLE
[feature request] AQL array function OUTERSECTION

### ISSUE THREAD

**Issue by baslr** [arangodb/arangodb#1891]
```
LET a = [1,2,3]
LET b = [3,4,5]
LET c = [5,6,7]

RETURN OUTERSECTION(a,b,c);
// result
[1,2,4,6,7]
```
All unique elements across all input arrays.

**Comment by Simran-B** [comment]
I think it is called symmetric difference and can be currently achieved like this:

```js
LET a = [1,2,3]
LET b = [3,4,5]
LET c = [5,6,7]

RETURN UNION(
    MINUS(a, b, c),
    MINUS(b, c, a),
    MINUS(c, a, b)
)
```

**Comment by baslr** [comment]
@Simran-B actually it is the symmetric difference https://www.youtube.com/watch?v=PxffSUQRkG4 (actually this video series is quite nice)
Yeah I know, currently it can be done this way. But this is with intermediate results and as n x n "matrix".

**Comment by jsteemann** [comment]
Implemented as AQL function `DIFFERENCE` in devel branch.

**Comment by baslr** [comment]
Hi @jsteemann,

thanks. As far as I understand it the changelog / documentation is misleading. The difference of a set is http://statistics.about.com/od/ProbHelpandTutorials/a/What-Is-The-Difference-Of-Two-Sets.htm its already the AQL function MINUS().
The symmetrical difference is ≠ outersection()

```
symmetrical difference /_\
A = {1,2,3,4}
B = {3,4,5,6}
C = {2,4,6,7}

D = A/_\B = {1,2,5,6}
E = D/_\C = {1,4,5,7}
```
Prof. Van Schmellhawks example with numbers https://youtu.be/PxffSUQRkG4?t=154

but the outersection is A xor B xor C and so only {1,5,7}

https://carleshf87.wordpress.com/2013/11/21/outersection-in-r/
https://tonybreyal.wordpress.com/2011/11/29/outersect-the-opposite-of-rs-intersect-function/
As Alexis points out https://tonybreyal.wordpress.com/2011/11/29/outersect-the-opposite-of-rs-intersect-function/#comment-1270 "Very cool, but creating a new word (‘outersect?!’ yech!) where one already exists: xor (short for eXclusive OR, as in set A or set B, but not both)."

**Comment by jsteemann** [comment]
ok, should it be named `OUTERSECTION` then, or `SYMMETRIC_DIFFERENCE`?

**Comment by baslr** [comment]
I vote for `OUTERSECTION` but I will consult a mathematician to have another opinion.

**Comment by neunhoef** [comment]
(1) As far as I know the symmetric difference is not defined on more than 2 sets. And it is not completely clear what it would be, if it were, in particular, since it is not an associative operation (A s B) s C is in general not equal to A s (B s C). So if we implement SYMMETRIC_DIFFERENCE, it shold only take 2 arguments.
(2) I did not know the term "outersection" before reading this post. Since we now have an implementation, I vote for calling it OUTERSECTION, which is a kind of funny name, since it is similar to INTERSECTION just a little bit different.

**Comment by jsteemann** [comment]
Got a mathematician's vote. Renamed to `OUTERSECTION`
