### ISSUE TITLE
Log file on Windows becomes very large because of `TestFileIOHeartbeat`

### ISSUE THREAD

**Issue by larsborn** [arangodb/arangodb#18919]
## My Environment

* __ArangoDB Version__: 3.9.2
* __Deployment Mode__: Single Server
* __Deployment Strategy__:  Manual Start
* __Configuration__: -
* __Infrastructure__: own
* __Operating System__: Windows 10
* __Total RAM in your machine__: 32Gb
* __Disks in use__: SSD
* __Used Package__: Windows Installer

## Component, Query & Data

__Affected feature__: Logging

## Steps to reproduce

1. terminate the ArangoDb service when it created the `TestFileIOHeartbeat` file but didn't delete it yet
2. Next time, the server will try to create it, it'll fail and produce a log line
3. This blew up log file size to a couple of Gb within a few days

__Problem__:
```
CreateFileW(filename, GENERIC_READ | GENERIC_WRITE, FILE_SHARE_DELETE | FILE_SHARE_READ | FILE_SHARE_WRITE, NULL, CREATE_NEW, 0, NULL);
```
Accoding to MSDN, the parameter `CREATE_NEW` leads to failure when the file already exists:

> Creates a new file, only if it does not already exist.
> If the specified file exists, the function fails and the last-error code is set to ERROR_FILE_EXISTS (80).

On a side node: it was necessary to reproduce the error with a separate program because arangod hid the error code:

```c
#include <stdio.h>
#include <windows.h>

int main()
{
    HANDLE fp;
    fp = CreateFileW(L"C:\\ProgramData\\ArangoDB\\TestFileIOHeartbeat", GENERIC_READ | GENERIC_WRITE, FILE_SHARE_DELETE | FILE_SHARE_READ | FILE_SHARE_WRITE, NULL, CREATE_NEW, 0, NULL);
    if (fp == INVALID_HANDLE_VALUE) {
        unsigned int error = GetLastError();
        printf("Error: 0x%x", error);
    } else {
        printf("Success");
    }

    return 0;
}
```

__Expected result__: 
1. emission of the error code of `80` in the logs.
2. graceful handling of the file being present

**Comment by apetenchea** [comment]
The pull request addressing this issue has been merged https://github.com/arangodb/arangodb/pull/18958

Thanks again for your help!
