### ISSUE TITLE
Foxx-manager doesn't trigger update of code

### ISSUE THREAD

**Issue by andybarilla** [arangodb/arangodb#1892]
I'm not sure if this is a bug or just something that should be documented, but after pulling my hair out for thinking I'm going crazy I realized that when running unit tests from **foxx-manager** the code changes are not automatically reflected in the unit tests.

By refreshing the Foxx service page in the web interface and then re-running the tests, the changes are shown. The service was in development mode the entire time.

I created a simple repo with an example: https://github.com/andybarilla/foxx-refresh-test. 

1) Install the app and set it to development mode
2) Run tests from the CLI using foxx-manager, check the value in the log
3) Change the return value in the **scripts/mytest.js** script
4) Run the tests again and notice the value is the same in the log
5) Refresh the Foxx web page
6) Run the tests again and the new value is there

This is with RC3.

**Comment by pluma** [comment]
Can you check whether the issue still persists in 3.1?

**Comment by dothebart** [comment]
We're pleased to anounce that ArangoDB 3.2, containing many improvements to Foxx, is now available for download - Closing.
