### ISSUE TITLE
Fatal error in Scavenger: semi-space copy - Allocation failed - process out of memory - Illegal instruction

### ISSUE THREAD

**Issue by sajeevpr** [arangodb/arangodb#1893]
Team,
  I was trying to traverse a huge graph using a foxx service which prints the traversed path using fs.append . I was appending one js variable result.mypath when ever I find any new path. So this variable will have huge strings concatenated. But after running for 17 mins, I encountered the below error and server crashed.
`
Fatal error in Scavenger: semi-space copy
Allocation failed - process out of memory
Illegal instruction
`

Total vertices = 4 million
Total edges = 20 million.

Regards,
Sajeev

**Comment by sajeevpr** [comment]
RangeError: Invalid string length

**Comment by sajeevpr** [comment]
I just grouped the writing to file. That is write only when I have 1 million rows. Now there is no such error.

**Comment by dothebart** [comment]
the `Fatal error in Scavenger` is a V8 error message if the V8 garbage collection runs out of available space.

**Comment by alundiak** [comment]
I implemented task https://leetcode.com/problems/snapshot-array/ in JavaScript code and got: 

```
FATAL ERROR: Scavenger: semi-space copy Allocation failed - JavaScript heap out of memory

[30:0x49c1450]      368 ms: Scavenge 119.4 (146.0) -> 119.3 (146.2) MB, 6.6 / 0.0 ms  (average mu = 0.878, current mu = 0.878) allocation failure
[30:0x49c1450]      375 ms: Scavenge 119.8 (146.2) -> 119.8 (146.2) MB, 6.5 / 0.0 ms  (average mu = 0.878, current mu = 0.878) allocation failure
[30:0x49c1450]      381 ms: Scavenge 119.8 (146.2) -> 119.7 (146.2) MB, 6.2 / 0.0 ms  (average mu = 0.878, current mu = 0.878) allocation failure

```

**Comment by dothebart** [comment]
Hi, 
this issue is > 5 years old and closed. Please create a new one, and in doubt create a reference to an older issue.
There will be no more work on this issue.
