### ISSUE TITLE
arangorestore ignores the HTTP status code

### ISSUE THREAD

**Issue by larsborn** [arangodb/arangodb#18942]
## My Environment

* __ArangoDB Version__: 3.9.10 
* __Deployment Mode__: Single Server
* __Deployment Strategy__: Manual Start
* __Configuration__: reverse proxy in front of ArangoDb API
* __Infrastructure__: own
* __Operating System__: Debian 12 / Windows 10
* __Total RAM in your machine__: 64Gb
* __Disks in use__: HDD
* __Used Package__: Debian .deb

## Component, Query & Data

__Affected feature__: import
__Dataset__: -
__Size of your Dataset on disk__: -

## Steps to reproduce

1. Configure a reverse proxy for the ArangoDB API and make it always return a 401 error code
2. trigger a restore to that endpoint
3. increase log level with `--log.level all=trace` for example to observe what's happening

__Problem__: `arangorestore` first performs a couple of requests agains `/_db/exampledb/_api/version` and then continues with the restore process. If the server (reverse proxy) then responds with the following body (while still responding with a 401 status code) for example

```
00: 3C 68 74 6D 6C 3E 0D 0A 3C 68 65 61 64 3E 3C 74  <html>..<head><t
10: 69 74 6C 65 3E 34 30 31 20 41 75 74 68 6F 72 69  itle>401.Authori
20: 7A 61 74 69 6F 6E 20 52 65 71 75 69 72 65 64 3C  zation.Required<
30: 2F 74 69 74 6C 65 3E 3C 2F 68 65 61 64 3E 0D 0A  /title></head>..
40: 3C 62 6F 64 79 3E 0D 0A 3C 63 65 6E 74 65 72 3E  <body>..<center>
50: 3C 68 31 3E 34 30 31 20 41 75 74 68 6F 72 69 7A  <h1>401.Authoriz
60: 61 74 69 6F 6E 20 52 65 71 75 69 72 65 64 3C 2F  ation.Required</
70: 68 31 3E 3C 2F 63 65 6E 74 65 72 3E 0D 0A 3C 68  h1></center>..<h
80: 72 3E 3C 63 65 6E 74 65 72 3E 6E 67 69 6E 78 2F  r><center>nginx/
90: 31 2E 32 32 2E 31 3C 2F 63 65 6E 74 65 72 3E 0D  1.22.1</center>.
```

`arangorestore` will try to parse that body and error out with

```
2023-04-24T08:18:51Z [1116] ERROR [cb69f] {restore} arangorestore terminated because of an unhandled exception: Expecting digit
```

__Expected result__: `arangorestore` could read the HTTP status code and stop execution while printing an error message. That error message could hint towards the status code making debugging like this much simpler. Additionally, `arangorestore` could already notice the 401 status code when making requests to the `version` endpoint. Further the error message `Expecting digit` could include the fact that JSON parsing failed (for example "JSON response could not be parsed, expecting digit").

**Comment by jsteemann** [comment]
Issue should be fixed via the above PRs.
