### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by agreif** [arangodb/arangodb#1895]
on the page
https://www.arangodb.com/why-arangodb/multi-model/

knowledge of one technologie to several
should be
knowledge of one technology to several

need for performance decrease
should be
need for performance decreases

This is why we focussed ArangoDb 3.0
should be (twice)
This is why we focussed ArangoDB 3.0

on the page
https://www.arangodb.com/why-arangodb/

compete with single-model dbs
should be
compete with single-model DBs

Alex.

**Comment by jsteemann** [comment]
done. thanks for reporting this!
