### ISSUE TITLE
[feature request] AQL graph traversal: PRUNE the current traversed path

### ISSUE THREAD

**Issue by baslr** [arangodb/arangodb#1897]
Test setup:
v1 -> e1 -> v2 -> e2  -> v3
e2 has {link_type:'upstream'}

With filter

```
FOR v, e, p IN 1..4 OUTBOUND 'docs/v1' edges

FILTER p.edges[-1].link_type == 'upstream'
RETURN v
```

returns v3

with future PRUNE statement

```
FOR v, e, p IN 1..4 OUTBOUND 'docs/v1' edges

PRUNE p.edges[-1].link_type == 'upstream'
RETURN v
```

returns [] since path is canceled at v2.

Prune exists in the config object for the traverser. https://docs.arangodb.com/2.8/Traversals/UsingTraversalObjects.html

**Comment by dothebart** [comment]
This is in principle already reality with ArangoDB 3.0, with a little different syntax:

    db._explain(`FOR v, e, p IN
                             1..3 OUTBOUND 'circles/A' 
                                    GRAPH 'traversalGraph' 
                                    FILTER p.edges[*]._key ANY != 'G' RETURN v._key");

Its currently not yet optimized to abort the traversal, which will become available in subsequent ArangoDB releases. We will close this issue once thats the case.

**Comment by roman1720** [comment]
Hi, I tried 3.1alpha2 and it seems that ANY and ALL filters are still not propagated into traversal and filter only result. So query gives incorrect results. Any idea when it will be implemented? I also wanted to try old GRAPH_TRAVERSAL with custom visitor but this function is missing in graphs._registerCompatibilityFunctions();

**Comment by dothebart** [comment]
Hi, the alpha doesn't contain this yet. If you want to test it, please use the devel branch.

**Comment by dothebart** [comment]
we're currently working hard to get the release ready - so stay tuned.

**Comment by hkernbach** [comment]
ArangoDB 3.1 has been released. Please note that the download urls and repositories have changed slightly. 

[Download](https://www.arangodb.com/download) or see [Release Notes](https://docs.arangodb.com/3.1/Manual/ReleaseNotes/NewFeatures31.html) for details.
