### ISSUE TITLE
Web UI replaces `0` in Parameter JSON view with `""` which might lead to an invalid query

### ISSUE THREAD

**Issue by larsborn** [arangodb/arangodb#18982]
## My Environment

* __ArangoDB Version__: 3.9.10
* __Deployment Mode__: Single Server
* __Deployment Strategy__: Manual Start
* __Infrastructure__: own
* __Operating System__: Debian
* __Total RAM in your machine__: 64Gb
* __Disks in use__: HDD
* __Used Package__: Debian .deb

## Component, Query & Data

__Affected feature__: AQL query using web interface
__AQL query (if applicable)__:
```
FOR doc in samples LIMIT @offset, 10 RETURN doc
```
with a parameter JSON of
```json
{"offset": 0}
```

## Steps to reproduce

1. Switch to the "Editor" tab under the "Queries" main entry
2. Switch the parameter view on the right to JSON
3. Past the AQL query and parameter from above into the corresponding fields
4. modify _something_ in the query view

__Problem__: Modifying something in the query view will change the `0` in the parameter json into an empty string. If you now hit the "Execute" button you will be told that you didn't specify a number for the LIMIT offset.

__Expected result__: Modifying the query content should not change the parameter JSON in a way that makes the resulting query invalid.

![arango-ui-parameters](https://github.com/arangodb/arangodb/assets/1826897/0b41e265-8b84-4c5f-ac95-e732de991f75)

**Comment by palashkaria** [comment]
Hey @larsborn, thanks for the detailed report!

This issue was fixed in #18985 and was backported to 3.9 (#18988). It's available in `v3.9.11`.
