### ISSUE TITLE
Foxx module.context basePath, baseUrl missing

### ISSUE THREAD

**Issue by baslr** [arangodb/arangodb#1898]
`module.context` has only `service` and `argv` but there should be `basePath`, `baseUrl` and so on.
https://docs.arangodb.com/3.0/Manual/Foxx/Context.html

**Comment by baslr** [comment]
Also `module.context` has only `service` and `argv` but there should be `basePath`, `baseUrl` and so on.
https://docs.arangodb.com/3.0/Manual/Foxx/Context.html

**Comment by pluma** [comment]
Could you clarify what you mean by "missing"? If you mean what `Object.keys` will show, these are getters defined on the prototype, so they won't be listed that way.

As for the original error: That's a bug in the documentation. The `fs` module is just called `fs`.

**Comment by baslr** [comment]
I see. To dump `module.context` I did
```es6
// main.js

const createRouter = require('@arangodb/foxx/router');
const router = createRouter();
module.context.use(router);
const str = JSON.stringify(module.context, false, 2);

router.get('/*', (req, res) => res.send(str) );
```
output:
```
{
  "service": {
    "name": "view",
    "version": "1.0.0-alpha7",
    "manifest": {
      "name": "view",
      "version": "1.0.0-alpha7",
      "license": "AGPLv3",
      "description": "view",
      "engines": {
        "arangodb": "^3.0.0"
      },
      "defaultDocument": "",
      "lib": ".",
      "main": "main.js",
      "configuration": {},
      "dependencies": {},
      "scripts": {
        "setup": "scripts/setup.js"
      }
    },
    "path": "view/APP",
    "options": {
      "author": "manuel",
      "configuration": {},
      "dependencies": {},
      "description": "manuel",
      "documentCollections": [
        "setting"
      ],
      "edgeCollections": [],
      "license": "AGPL",
      "name": "manuel",
      "replace": true
    },
    "mount": "/view",
    "root": ".../js/apps/_db/_system",
    "isSystem": false,
    "isDevelopment": true,
    "author": "Manuel",
    "description": "view"
  },
  "argv": []
}
```
`module.context.basePath` is actually there.
Is there a simple way to dump `module.context` without hardcoding?
Am I right that the module.context comes from this file: https://github.com/arangodb/arangodb/blob/devel/js/server/modules/@arangodb/foxx/context.js?
Interesting: I copied this code sniped https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#Prototype_methods and done a `console.log( JSON.stringify({a:square.area}));` output is `{"a":100}`

**Comment by pluma** [comment]
I guess you could probably deep-clone the object but I'm not sure whether the result will include some cyclic structures which can't be expressed in JSON. Maybe `require('util').inspect` produces something more useful.

Is there any particular reason you want to dump the entire context object? You shouldn't rely on undocumented properties (including the details of the `service` property) as these may change within the same major version (i.e. 3.x) and are considered "implementation details".

**Comment by baslr** [comment]
I want see the current documented values for `module.context` as in https://docs.arangodb.com/3.0/Manual/Foxx/Context.html just to have an overview of actual values.

Also what I don't understand, why is the MDN class example, regarding JSON.stringify, with a getter working, but the FoxxContext class not?

**Comment by baslr** [comment]
Ok, one solution would be to implement a custom toJSON() {} function in the class FoxxContext that outputs all variables in https://docs.arangodb.com/3.0/Manual/Foxx/Context.html. This has the advantage that no undocumented properties are leaked.
I you like, I would do this :-)

**Comment by pluma** [comment]
Sure. Pull requests are always welcome. 😄
