### ISSUE TITLE
One replicated collection not updatable

### ISSUE THREAD

**Issue by pekeler** [arangodb/arangodb#1899]
We’re using 2.8.7 in production, using replication to a stand-by server. We just stopped replication and promoted the slave replicant to become the new master. Then we noticed a crazy issue: Existing documents in one of our collections can’t be updated anymore. And there’s no error if we try.

Viewing the data with Aardvark, I’m not seeing any difference between old master and new master.

`update {_key: “123”} with {foo: "bar"} in collection1` works.
`update {_key: “456”} with {foo: "bar"} in collection2` fails (no error in Aardvark, nothing in the logs).

Newly created documents in collection2 on the new master can be updated no problem. It's just the old documents that seem to be read-only.

(Obviously, the newly promoted master is useless and we re-instantiated the old master which does not have this problem. We still have the server with this broken collection around if there's something we can check to track down the cause of this problem.)

cc @ericfiala

**Comment by dothebart** [comment]
Hi, 
We tried to reproduce this, but failed.
It would be great if you could provide us with a copy of the database files in question. (or access to the system)
If you need an NDA signed for this, send it per mail to hackers at arangodb.com - we will send it back asap.

**Comment by neunhoef** [comment]
This problem is identified and is fixed for 2.8.10. Packages are being built as I write this.

**Comment by neunhoef** [comment]
I should say that the corresponding problem in the 3.0 series is also fixed in 3.0.1.

**Comment by pekeler** [comment]
Excellent - thank you!

**Comment by neunhoef** [comment]
2.8.10 is now built and can be downloaded at https://build.opensuse.org/package/show/home:fceller:version2/arangodb-2.8
It will soon appear on the official download page for 2.8.
