### ISSUE TITLE
unable to install 3.0.0 using homebrew

### ISSUE THREAD

**Issue by zopyx** [arangodb/arangodb#1900]
Homebrew seems to be still on 2.X which is not completely consistent with the docs

https://www.arangodb.com/download/macosx/

Suxmac-2:SWP ajung$ brew install arangodb
Warning: arangodb-2.8.9 already installed

Suxmac-2:SWP ajung$ brew update

Suxmac-2:SWP ajung$ brew install --HEAD  arangodb
Warning: arangodb-2.8.9 already installed

**Comment by dothebart** [comment]
Hi, can you retry? It seems the PR got accepted around the time you reported this yesterday ;-)

**Comment by zopyx** [comment]
Nope.

**Comment by dothebart** [comment]
nope as in you tried and it didn't work?

**Comment by robwrighty0** [comment]
Brew is still showing that only 2.8.9 is available to download on my machine. I've brew updated/upgraded too.

**Comment by fceller** [comment]
Could you please try the following:

If you have an existing database, please follow the instruction found in https://docs.arangodb.com/3.0.0/Manual/Administration/Upgrading/Upgrading30.html to export the data.

```
brew uninstall arangodb
brew install --HEAD arangodb
```

Follow the instructions to import the data into ArangoDB 3.0.

Currently, there is no way to specify a version to install. You need the old ArangoDB 2.8 in order to export and the new in order to import. I have no real idea how to handle this correctly in homebrew.

Thanks
  Frank

**Comment by robwrighty0** [comment]
Thanks for your response Frank. This didn't work straight away, I got an error posted below and will investigate what this means later.

CMake Error at /usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/Platform/Darwin.cmake:76 (message):
  CMAKE_OSX_DEPLOYMENT_TARGET is '10.9' but CMAKE_OSX_SYSROOT:
   ""
  is not set to a MacOSX SDK with a recognized version.  Either set
  CMAKE_OSX_SYSROOT to a valid SDK or set CMAKE_OSX_DEPLOYMENT_TARGET to
  empty.

**Comment by fceller** [comment]
@robwrighty0 looks like the SDK is missing. I'll will try to find a different solution.

**Comment by fceller** [comment]
also see https://github.com/Homebrew/homebrew-core/issues/2517

**Comment by wtfqm** [comment]
Hi, I made a fresh install today to try ArangoDb for the first time and brew installed (after update & upgrade) version 2.8.9. As I browsed to the gui it told me there was a new version available.

**Comment by fceller** [comment]
The formula is currently in review: https://github.com/Homebrew/homebrew-core/pull/2576#issuecomment-230407366

**Comment by dothebart** [comment]
Ok, the 3.0 formula PR is accepted; the legacy 2.8 still pending. 
So you now should be able to easily get ArangoDB 3 via brew.

**Comment by dothebart** [comment]
The merge is complete - Run 

    brew install arangodb # -> brings arangodb 3

Once you've followed the steps over at https://github.com/Homebrew/homebrew-versions you can run:

    brew install arangodb2 # -> brings arangodb version 2
