### ISSUE TITLE
UPSERT condition changes behavior in 3.0.0

### ISSUE THREAD

**Issue by amurchick** [arangodb/arangodb#1901]
In version prior 3.0.0 condition like `{'data.tg.id': 1}` was worked, but in 3.0.0 - not worked.

For example:
```
UPSERT {
	'data.tg.id': 1
}
INSERT {
	data: {
	    tg: {
	        id: 1
        }
    }
}
UPDATE {}
IN im
RETURN {OLD, NEW}
```
On first run this returns: 
```
  {
    "OLD": null,
    "NEW": {
      "_key": "1502861992333",
      "_id": "im/1502861992333",
      "_rev": "1502861992333",
      "data": {
        "tg": {
          "id": 1
        }
      }
    }
  }
```

On next iiterations for version < 3.0.0 condition matches and existing document returned:
```
  {
    "OLD": {
      "_key": "1502861992664",
      "_id": "im/1502861992664",
      "_rev": "1502861992664",
      "data": {
        "tg": {
          "id": 1
        }
      }
    },
    "NEW": {
      "_key": "1502861992664",
      "_id": "im/1502861992664",
      "_rev": "1502861992664",
      "data": {
        "tg": {
          "id": 1
        }
      }
    }
  }
```

But on next iterations for version 3.0.0 condition not matched and new document created - WRONG:
```
  {
    "OLD": null,
    "NEW": {
      "_key": "1502861992333",
      "_id": "im/1502861992333",
      "_rev": "1502861992333",
      "data": {
        "tg": {
          "id": 1
        }
      }
    }
  }
```

```
$ arangod --version
3.0.0

architecture: 64bit
asan: false
asm-crc32: true
boost-version: 1.61.0b1
build-date: 2016-06-22 12:26:35
compiler: gcc
cplusplus: 201103
endianness: little
fd-client-event-handler: poll
fd-setsize: 1024
icu-version: 54.1
jemalloc: true
libev-version: 4.22
maintainer-mode: false
openssl-version: OpenSSL 1.0.1k 8 Jan 2015
rocksdb-version: 4.8.0
server-version: 3.0.0
sizeof int: 4
sizeof void*: 8
sse42: false
tcmalloc: false
v8-version: 5.0.71.39
vpack-version: 0.1.30
zlib-version: 1.2.8

$ uname -a
Linux server 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux
```

**Comment by Simran-B** [comment]
Is `'data.tg.id'` supposed to match `{"data": {"tg": {"id": 1}}}` or a literal attribute key `data.tg.id`?

In 2.x, the meaning of dots in attribute keys was ambiguous, see #1806. This should no longer be the case and dots be interpreted literally.

Can you try the following query?

```js
UPSERT {
    data: {
        tg: {
            id: 1
        }
    }
}
INSERT {
    data: {
        tg: {
            id: 1
        }
    }
}
UPDATE {}
IN im
RETURN {OLD, NEW}
```

**Comment by amurchick** [comment]
Yes, `data.tg.id` meaning is `{"data": {"tg": {"id": 1}}}`.
If this behavior OK, issue can be closed.

**Comment by dothebart** [comment]
I think this is described in the change log here: https://docs.arangodb.com/3.0/Manual/ReleaseNotes/UpgradingChanges30.html#attribute-names-and-parameters 

This was rather a bug in 2.x because of the database core not being able to differentiate between object keys with dots in their names, and sub-object addressing. 

So I will close this issue. Thanks for reporting ;-)
