### ISSUE TITLE
Cluster with SSL and authentication

### ISSUE THREAD

**Issue by elade9977** [arangodb/arangodb#19025]
Hi,

I Have a Cluster with 3 Agents, 2 Coordinators & 3 DBs on a single Linux server.
All the services are backed on dockers (version 3.10.6)
I added SSL to Coordinators so I can access the UI via https.
I would like to know how to add also authentication using username & password to UI.
I tried to pass ARANGO_ROOT_PASSWORD but it has no effect.
I have enabled authentication = true in all the services.
Only Coordinators server.end-point and cluster.my-address are ssl. The rest are tcp.

I haven't found anything on the docs about authentication with username & password in cluster.
https://www.arangodb.com/docs/stable/administration-managing-users.html

Thank you

**Comment by dothebart** [comment]
on clusters you can only modify the password by logging in using the JWT used in the installation (if the password isn't empty by default)

**Comment by elade9977** [comment]
Hi @dothebart,
I created JWT token and create with it bearer - created secret.jwt and then arangodb auth token --auth.jwt-secret=/etc/certs/secret.jwt.
I tried to use this bearer to run API for example _open/auth to coordinator but got 
`{"code":404,"error":true,"errorMessage":"not found","errorNum":404}.`
Some other APIs of GET dose work.
Any idea how to check the authentication?

**Comment by dothebart** [comment]
you should be able to use arangosh  with `--javascript.execute-string` to set the password:
```
        if (!arango.isConnected()) {{
          throw new Error('connecting the database failed');
        }}
        require('org/arangodb/users').update('{user}', '${password}');
```
(we use that snippet in our python instrumentated checks)

**Comment by elade9977** [comment]
What about the APIs? 
Why I get `{"code":404,"error":true,"errorMessage":"not found","errorNum":404}` on POST API with the bearer?

**Comment by dothebart** [comment]
are you actually talking to the coordinator?

**Comment by elade9977** [comment]
Yes.
I’m running the Apis with coordinator port and get 404 on POST requests

**Comment by dothebart** [comment]
did you then properly specify the JWT? https://www.arangodb.com/docs/3.10/http/authentication.html

**Comment by elade9977** [comment]
Yes I did.
I added the JWT to the arangod.cfg file in all the service in the cluster.

coordinator1 arangod.cfg - the server section is the same for all other services.
```
[database]
directory = /var/lib/arangodb3

[server]
endpoint = ssl://0.0.0.0:8529
storage-engine = auto
authentication = true
statistics = true
jwt-secret-keyfile = /etc/certs/secret.jwt

[javascript]
startup-directory = /usr/share/arangodb3/js
app-path = /var/lib/arangodb3-apps

[log]
level = debug
file =  -

[cluster]
my-address = ssl://arangodb-coordinator1:8529
my-role = COORDINATOR
agency-endpoint = tcp://arangodb-agency1:8529
agency-endpoint = tcp://arangodb-agency2:8529
agency-endpoint = tcp://arangodb-agency3:8529
system-replication-factor = 2
min-replication-factor = 2

[ssl]
# protocol = 5
keyfile = /etc/certs/arangodb.pem
```


I create the JWT token like in the document and run the same API for auth
`curl -ks -XPOST "https://X.X.X.X:7001/_open/auth" -H "Authorization": "bearer MYTOKEN"`
And got this response
`{"error":true,"code":404,"errorNum":404,"errorMessage":"unknown path '/_open/auth'"}`

When I used GET API such as version I get full response
`curl -ks -XGET "https://X.X.X.X:7001/_api/version" -H "Authorization: bearer MYTOKEN" -v`

`{"server":"arango","license":"community","version":"3.10.6"}`

**Comment by dothebart** [comment]
quoting the documentation:
```
An HTTP `404 Not Found` status code is returned if the server has authentication
disabled and the endpoint is thus not available.
```
so it seems your installation doesn't have authentification enabled?

**Comment by elade9977** [comment]
The API worked after creating base64 string from username and password.
Thank you!
