### ISSUE TITLE
Multiple CMAKE_INSTALL_* entries ignored

### ISSUE THREAD

**Issue by helq** [arangodb/arangodb#1904]
I'm trying to compile arangodb 3.0 in Archlinux with custom `cmake` flags, unfortunately some flags are being ignored. To be precise, this is the process I'm following to compile arangodb:

    mkdir build; cd build
    cmake .. \
      -DCMAKE_INSTALL_PREFIX=/ \
      -DCMAKE_INSTALL_BINDIR=/usr/bin \
      -DCMAKE_INSTALL_SBINDIR=/usr/bin \
      -DCMAKE_INSTALL_DATAROOTDIR=/usr/share \
      -DCMAKE_INSTALL_SYSCONFDIR=/etc \
      -DCMAKE_INSTALL_LOCALSTATEDIR=/var \
      -DCMAKE_C_COMPILER=clang \
      -DCMAKE_CXX_COMPILER=clang++ \
      -DCMAKE_BUILD_TYPE=Release
    make
    make DESTIDIR="/a/test/directory" install

But once everything is compiled and installed, I find the following structure in the destination directory:

    /
    -   etc/
    -   init.d/
    -   sbin/
    -   share/
    -   usr/
        -   bin/
    -   var/

Where I was expecting this structure:

    /
    -   etc/
    -   init.d/
    -   usr/
        -   bin/
        -   share/
    -   var/

I thought the problem was easy to solve, a simple refactoring of `arangodb/cmake/ArangoDBMacros.cmake` should have done it. For example, the line

    set(TRI_PKGDATADIR "${CMAKE_INSTALL_PREFIX}/share/arangodb3")

could be replaced with

    set(TRI_PKGDATADIR "${CMAKE_INSTALL_DATAROOTDIR}/arangodb3")

Or the line

      set(TRI_SBINDIR "${CMAKE_INSTALL_PREFIX}/sbin")

with

      set(TRI_SBINDIR "${CMAKE_INSTALL_SBINDIR}")

But it seems there are many many string substitutions to do so that the installation respects all CMake entries.

I hope I've been able to articulate adequately, it's my first time trying to compile using CMake so I'm not sure if I've missed something.

**Comment by dothebart** [comment]
Hi, this is what the rpm spec file does:

cmake \
  -DVERBOSE=On \
  -DUSE_OPTIMIZE_FOR_ARCHITECTURE=Off \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  -DCMAKE_C_FLAGS="${CFLAGS}" \
  -DCMAKE_CXX_FLAGS="${CXXFLAGS}" \
  -DCMAKE_C_COMPILER="%{C_COMPILER}" \
  -DCMAKE_CXX_COMPILER="%{CXX_COMPILER}" \
  -DFORCE_JEMALLOC_LIB=:libjemalloc.a \
  -DETCDIR=/etc \
  -DVARDIR=/var \
  -DCMAKE_INSTALL_PREFIX:PATH=/usr \
  -DCMAKE_SKIP_RPATH:BOOL=ON \
  -DCMAKE_USER_MAKE_RULES_OVERRIDE= \
  ..

maybe that works out in the proper directory hierarchy?

**Comment by helq** [comment]
Awesome, it worked! :smiley: 

In the end I used:

    cmake .. \
      -DCMAKE_INSTALL_PREFIX:PATH=/usr \
      -DETCDIR=/etc \
      -DVARDIR=/var \
      -DCMAKE_C_COMPILER=clang \
      -DCMAKE_CXX_COMPILER=clang++ \
      -DCMAKE_SKIP_RPATH:BOOL=ON \
      -DCMAKE_BUILD_TYPE=Release
    sed -i 's/sbin/bin/' arangod/cmake_install.cmake # <- little replacement to make everything be installed into bin instead of sbin
    make DESTIDIR="/a/test/directory" install

and worked.

But there are still some hardcoded paths into `arangodb/cmake/ArangoDBMacros.cmake` pointing to `sbin`, they should point to a SBIN variable/entry from CMake instead so if anybody wants to change the sbin installation directory, they could do it without any problem (I suppose the entry to use should be `CMAKE_INSTALL_SBINDIR` but I'm not sure).

**Comment by dothebart** [comment]
We definitely still have some cmake cleanup on our TODO list, I hope we can streamline this as well, so a LHFS conforming install can be done with one argument.

**Comment by m0ppers** [comment]
We were indeed not using the intended cmake variables in all places. this has been fixed in devel (future 3.1 release) and your build instructions should yield the correct result now :)
