### ISSUE TITLE
unable to run 3.0.0 on OS X with ArangoDB-CLI.app

### ISSUE THREAD

**Issue by zigolab** [arangodb/arangodb#1905]
Running ArangoDB-CLI.app 3.0.0 on OSX (without homebrew installed) I have the following quite generic error:

```
ArangoDB server has been started

The database directory is located at
   '.../ArangoDB-CLI.app/Contents/MacOS/opt/arangodb/var/lib/arangodb3'

The log file is located at
   '.../ArangoDB-CLI.app/Contents/MacOS/opt/arangodb/var/log/arangodb3/arangod.log'

You can access the server using a browser at 'http://127.0.0.1:8529/'
or start the ArangoDB shell
   '.../ArangoDB-CLI.app/Contents/MacOS/arangosh'

Switching to log-file now, killing this windows will NOT stop the server.


tail: /Users/aconfetti/Developer/Servers/arangodb/ArangoDB-CLI.app/Contents/MacOS/opt/arangodb/var/log/arangodb3/arangod.log: No such file or directory

[Processo completato]
```

Running ```ArangoDB-CLI.app/Contents/MacOS/arangod``` from shell I have a more interesting error:
```
dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: .../ArangoDB-CLI.app/Contents/MacOS/opt/arangodb/sbin/arangod
  Reason: image not found
Trace/BPT trap: 5
```
Unfortunately my libssl.1.0.0.dylib is managed through macport and is located in ```/opt/local/lib/libssl.1.0.0.dylib```

Is there a way to tell Arango to look for it not in the default homebrew path?

**Comment by dothebart** [comment]
Hi @zigolab, 
the macosX way to do this seems to be setting the `DYLD_LIBRARY_PATH` with the additional lib path:
http://stackoverflow.com/questions/3146274/is-it-ok-to-use-dyld-library-path-on-mac-os-x-and-whats-the-dynamic-library-s

You probably should add export statements with that to the wrapper shellscripts. Does that fix your issues?

**Comment by hwde** [comment]
After installing a new ArangoDB via .dmg I run the following script (I've MacPorts collection installed, so the required .dylib's are in /opt/local/lib ...):

```
#/bin/bash

FROM_SSL=/usr/local/opt/openssl/lib/libssl.1.0.0.dylib
TO_SSL=/opt/local/lib/libssl.1.0.0.dylib

FROM_CRYPTO=/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
TO_CRYPTO=/opt/local/lib/libcrypto.1.0.0.dylib

cd /Applications/ArangoDB.app/Contents &&
for i in MacOS/opt/arangodb/sbin/* Resources/opt/arangodb/bin/*; do
  install_name_tool -change $FROM_SSL $TO_SSL $i
  install_name_tool -change $FROM_CRYPTO $TO_CRYPTO $i
done
```
