### ISSUE TITLE
Overwrite Saved Queries

### ISSUE THREAD

**Issue by bateramos** [arangodb/arangodb#1906]
Hello,
every time I change a saved query on the GUI, its asked of the name that I should save.
I think the expected behavior is to overwrite the existed one. Maybe also adding a "Save as" button to preserve the current behavior.
If the GUI code is available no github, I can try to make this change.

**Comment by Simran-B** [comment]
The code is available here: https://github.com/arangodb/arangodb/tree/devel/js/apps/system/_admin/aardvark/APP

Pull requests are always welcome. Note however that we need you to sign a CLA in order to integrate your changes into the code base.

**Comment by bateramos** [comment]
There is a way to only build and run the aardvark? Can't find this information anywhere

**Comment by bateramos** [comment]
done, some files were created at frontend/build. And to run it?

**Comment by hkernbach** [comment]
Aardvark Building: https://github.com/arangodb/arangodb/blob/devel/README_maintainers.md#front-end-webui

To run it, just start your compiled arangodb. It will use the files from the build directory.

**Comment by Simran-B** [comment]
If you don't want to compile ArangoDB, just rename the aardvark folder of any ArangoDB instance and symlink the folder of your self-compiled aardvark so that it can pick up the custom built app.

**Comment by bateramos** [comment]
Thanks a lot for the help.
When I run cmake. I get this error:

CMake Error at cmake/FindPackageHandleStandardArgs.cmake:21 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_INCLUDE_DIR)

**Comment by bateramos** [comment]
@Simran-B 
Thanks, I will try to do that!

**Comment by hkernbach** [comment]
If cmake is not able to find your ssl libraries, you have to run cmake with a parameter:

cmake .. -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl

/usr/local/opt/openssl is just an example directory. could be different on other os/distributions.

**Comment by hkernbach** [comment]
Thank you for your work. Could you finish the feature?
If so, could you be so kind and fill out our CLA agreement and start a pull request?

CLA Query Github
----------------
@bateramos thanks a lot for you improvements. We are using a Apache 2 CLA for ArangoDB, which can be found here: https://www.arangodb.com/documents/cla.pdf

We have not been able to set of an electronic system yet. Can you sign, scan and email it to cla (at) arangodb.com?

Thanks a lot
Heiko
```

**Comment by bateramos** [comment]
Sorry, I just am so busy this week that I did not have the time to finish. I also sign the CLA and scanned but I had another PR (another repo) that was consuming my time. This weekend I will finish this and send the CLA.
