### ISSUE TITLE
HTTP Basic Authentication login page is not appear in cluster 

### ISSUE THREAD

**Issue by elade9977** [arangodb/arangodb#19080]
Hi,

I have a cluster based on dockers in single server.
I have enabled authentication and added root password to the cluster (to coordinators dockers only).
I want the login page will appear in order to allow access to UI using username & password only.
How can I force the coordinators to show the login page?
Thank you/

**Comment by dothebart** [comment]
Once your cluster has properly enabled authentication it will never let you in without JWT or login/password. The login dialog will allways be shown. 
Hint: you can use the arangodb starter to launch the required set of docker containers for a cluster with authentication, and "steal" its generated configuration.

**Comment by elade9977** [comment]
I'm using this arangod.conf file for coordinators containers.
```
[database]
directory = /var/lib/arangodb3

[server]
endpoint = ssl://0.0.0.0:8529
storage-engine = auto
authentication = true
statistics = true
jwt-secret-keyfile = /etc/certs/secret.jwt

[javascript]
startup-directory = /usr/share/arangodb3/js
app-path = /var/lib/arangodb3-apps

[log]
level = debug
file =  -

[cluster]
my-address = ssl://arangodb-coordinator1:8529
my-role = COORDINATOR
agency-endpoint = tcp://arangodb-agency1:8529
agency-endpoint = tcp://arangodb-agency2:8529
agency-endpoint = tcp://arangodb-agency3:8529
system-replication-factor = 2
min-replication-factor = 2

[ssl]
# protocol = 5
keyfile = /etc/certs/arangodb.pem
```
Docker env vars for coordinators containers are
```
ARANGO_NO_AUTH: '0'
ARANGO_ROOT_PASSWORD: 'MyPass'
```

For DBs containers the arangod.conf file is the same except there is no ssl section, all traffic is tcp and only ARANGO_NO_AUTH: '0' env var.

For agency this is the arangod.cfg 
```
[database]
directory = /var/lib/arangodb3

[server]
endpoint = tcp://0.0.0.0:8529
storage-engine = auto
authentication = true
statistics = true
jwt-secret-keyfile = /etc/certs/secret.jwt

[javascript]
startup-directory = /usr/share/arangodb3/js
app-path = /var/lib/arangodb3-apps

[log]
level = debug
file =  -

[agency]
activate = true
my-address = tcp://arangodb-agency1:8529
size = 3
endpoint = tcp://arangodb-agency1:8529
supervision = true
```
Docker env is only ARANGO_NO_AUTH: '0'

secret.jwt was created in a temp agency container using this command - `arangodb create jwt-secret --secret=/var/lib/arangodb3/secret.jwt [--length=64]`
After the creation I save the file, delete the temp agency container and deploy my cluster.

What am I missing?

**Comment by elade9977** [comment]
The problem was that not all servicers were with ssl in endpoint and my-address
