### ISSUE TITLE
[3.0.0] "Too many collections" in simple graph query

### ISSUE THREAD

**Issue by thwd-duda** [arangodb/arangodb#1910]
I am executing a query like the following:

```
FOR v IN 1..10 ANY "a/b" GRAPH "c"
    RETURN DISTINCT v
```

And I'm consistently getting the error:

```
1522: too many collections (while parsing)
```

The graph `c` has 20 edge definitions.

**If this is expected behavior** then could you kindly elaborate and document what it means and what is happening internally, please.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial
```

```
$ uname -a
Linux [redacted]4.4.0-24-generic #43-Ubuntu SMP Wed Jun 8 19:27:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ arangod --version
3.0.0

architecture: 64bit
asan: false
asm-crc32: true
boost-version: 1.61.0b1
build-date: 2016-06-22 12:27:17
compiler: gcc
cplusplus: 201103
endianness: little
fd-client-event-handler: poll
fd-setsize: 1024
icu-version: 54.1
jemalloc: true
libev-version: 4.22
maintainer-mode: false
openssl-version: OpenSSL 1.0.2g-fips  1 Mar 2016
rocksdb-version: 4.8.0
server-version: 3.0.0
sizeof int: 4
sizeof void*: 8
sse42: false
tcmalloc: false
v8-version: 5.0.71.39
vpack-version: 0.1.30
zlib-version: 1.2.8
```

**Comment by jsteemann** [comment]
AQL has a built-in limit of 32 collections that can be used in a single query.
Of how many collections does the graph "c" consist?

**Comment by thwd-duda** [comment]
The total list of 25 edge collections is:
```
[
  [ArangoCollection 4285, "imudCpHiAIl_zMNniuaZmsX" (type edge, status loaded)], 
  [ArangoCollection 4804, "OoUBNvwSnxHB_GoUxHlYcOsBB" (type edge, status loaded)], 
  [ArangoCollection 4356, "FrbslAnLDZH_GoUxHlYcOsBB" (type edge, status loaded)], 
  [ArangoCollection 4401, "pShSJlBimmd_GoUxHlYcOsBB" (type edge, status loaded)], 
  [ArangoCollection 4884, "OoUBNvwSnxHB_pShSJlBimmd" (type edge, status loaded)], 
  [ArangoCollection 4399, "DtFIrUyfuyJB_GoUxHlYcOsBB" (type edge, status loaded)], 
  [ArangoCollection 4828, "OoUBNvwSnxHB_JwSSUjODUCDB" (type edge, status loaded)], 
  [ArangoCollection 4860, "OoUBNvwSnxHB_EpBqjJlaSHR" (type edge, status loaded)], 
  [ArangoCollection 4231, "zMNniuaZmsX_zMNniuaZmsX" (type edge, status loaded)], 
  [ArangoCollection 4836, "OoUBNvwSnxHB_PaoBNoYMQjx" (type edge, status loaded)], 
  [ArangoCollection 4368, "imudCpHiAIl_GoUxHlYcOsBB" (type edge, status loaded)], 
  [ArangoCollection 4393, "vrxguVyvhlKB_zMNniuaZmsX" (type edge, status loaded)], 
  [ArangoCollection 4395, "klossvpeYILB_GoUxHlYcOsBB" (type edge, status loaded)], 
  [ArangoCollection 4397, "JwSSUjODUCDB_GoUxHlYcOsBB" (type edge, status loaded)], 
  [ArangoCollection 4430, "JwSSUjODUCDB_zMNniuaZmsX" (type edge, status loaded)], 
  [ArangoCollection 4820, "OoUBNvwSnxHB_imudCpHiAIl" (type edge, status loaded)], 
  [ArangoCollection 4432, "vrxguVyvhlKB_GoUxHlYcOsBB" (type edge, status loaded)], 
  [ArangoCollection 4468, "pShSJlBimmd_zMNniuaZmsX" (type edge, status loaded)], 
  [ArangoCollection 4844, "OoUBNvwSnxHB_DtFIrUyfuyJB" (type edge, status loaded)], 
  [ArangoCollection 4876, "OoUBNvwSnxHB_FrbslAnLDZH" (type edge, status loaded)], 
  [ArangoCollection 4488, "klossvpeYILB_zMNniuaZmsX" (type edge, status loaded)], 
  [ArangoCollection 4622, "OoUBNvwSnxHB_zMNniuaZmsX" (type edge, status loaded)], 
  [ArangoCollection 4812, "OoUBNvwSnxHB_klossvpeYILB" (type edge, status loaded)], 
  [ArangoCollection 4852, "OoUBNvwSnxHB_Byzamgnlwep" (type edge, status loaded)], 
  [ArangoCollection 4868, "OoUBNvwSnxHB_vrxguVyvhlKB" (type edge, status loaded)] 
]
```
All of them have been added to the graph's edge definitions through the HTTP interface, e.g. POSTed to:
```
/_db/<database-name>/_api/gharial/<graph-name>/edge
```
And the returned HTTP status of that call was 2xx for all of them.

However, I just listed the `g._edgeCollections()` via `arangosh` and the result only contained 20 collections:
```
[ 
  [ArangoCollection 4231, "zMNniuaZmsX_zMNniuaZmsX" (type edge, status loaded)], 
  [ArangoCollection 4285, "imudCpHiAIl_zMNniuaZmsX" (type edge, status loaded)], 
  [ArangoCollection 4393, "vrxguVyvhlKB_zMNniuaZmsX" (type edge, status loaded)], 
  [ArangoCollection 4432, "vrxguVyvhlKB_GoUxHlYcOsBB" (type edge, status loaded)], 
  [ArangoCollection 4401, "pShSJlBimmd_GoUxHlYcOsBB" (type edge, status loaded)], 
  [ArangoCollection 4395, "klossvpeYILB_GoUxHlYcOsBB" (type edge, status loaded)], 
  [ArangoCollection 4488, "klossvpeYILB_zMNniuaZmsX" (type edge, status loaded)], 
  [ArangoCollection 4468, "pShSJlBimmd_zMNniuaZmsX" (type edge, status loaded)], 
  [ArangoCollection 4622, "OoUBNvwSnxHB_zMNniuaZmsX" (type edge, status loaded)], 
  [ArangoCollection 4804, "OoUBNvwSnxHB_GoUxHlYcOsBB" (type edge, status loaded)], 
  [ArangoCollection 4812, "OoUBNvwSnxHB_klossvpeYILB" (type edge, status loaded)], 
  [ArangoCollection 4820, "OoUBNvwSnxHB_imudCpHiAIl" (type edge, status loaded)], 
  [ArangoCollection 4828, "OoUBNvwSnxHB_JwSSUjODUCDB" (type edge, status loaded)], 
  [ArangoCollection 4836, "OoUBNvwSnxHB_PaoBNoYMQjx" (type edge, status loaded)], 
  [ArangoCollection 4844, "OoUBNvwSnxHB_DtFIrUyfuyJB" (type edge, status loaded)], 
  [ArangoCollection 4852, "OoUBNvwSnxHB_Byzamgnlwep" (type edge, status loaded)], 
  [ArangoCollection 4860, "OoUBNvwSnxHB_EpBqjJlaSHR" (type edge, status loaded)], 
  [ArangoCollection 4868, "OoUBNvwSnxHB_vrxguVyvhlKB" (type edge, status loaded)], 
  [ArangoCollection 4876, "OoUBNvwSnxHB_FrbslAnLDZH" (type edge, status loaded)], 
  [ArangoCollection 4884, "OoUBNvwSnxHB_pShSJlBimmd" (type edge, status loaded)] 
]
```

**Comment by jsteemann** [comment]
The limit of 32 restricts the total number of collections used in an AQL query. Regarding this limit, there is no difference between edge and vertex collections. So if the graph has 25 edge collections, it will probably have at least some vertex collections, and probably contains more than 32 collections *in total*. Is that the case? Then at least the error is "intentional".

**Comment by thwd-duda** [comment]
If I consider the 20 edge collections that are returned by `g._edgeCollections()`, they connect 13 document collections.

20 + 13 = 33 > 32

So that clears up the "too many connections" error.

Should I open a separate issue for the 25 vs 20 edge collection discrepancy? 

Also, for context: we use many small edge collections in our graph in order to control graph-traversal, since AQL doesn't (yet?) support excluding branches like `expandFilter` in the JavaScript API. We tried several different approaches, this was our solution. Javascript/Foxx is not attractive to use. Do you have a suggestion how we could emulate this behavior?

**Comment by dothebart** [comment]
Hm, yes the documentation isn't mentioning this. I've discussed this topic several times in the google group by now, so I guess its [about time to add it to the documentation](https://docs.arangodb.com/devel/Manual/Graphs/index.html#multiple-edge-collections-vs-filters-on-edge-document-attributes) now. (this will be updated & added over nite, so it will be available tomorow.)

**Comment by thwd-duda** [comment]
@dothebart I just read the commited documentation. Thank you.

When we were researching for a solution, with ArangoDB v2.8.9, filtering on edges in AQL (e.g. `FILTER e.type="friends"`) did not exclude the branch following that edge from being traversed. It simply excluded the `_to`- or `_from`-Vertex (depending on direction) of the edge from the result set, but traversal continued "on the other side of the edge" (I hope that's understandable).

Has this been changed in v3.0.0?

**Comment by Simran-B** [comment]
CC @mchacki --^

**Comment by mchacki** [comment]
If you want the traversal to abort early you have to apply the filtering on the "path" variable instead.

The filtering on vertex and edge is ONLY on the result set. Filtering on the "path" figures out that every path after this point cannot fulfill the condition any more.

So in your example for the edge.
Assume you have:

```
FOR v,e,p IN 1..5 OUTBOUND 'vertex/A' GRAPH 'my_graph'
  FILTER e.color != "red"
    RETURN v
```

You can replace it by:

```
FOR v, e, p IN 1..5 OUTBOUND 'vertex/A' GRAPH 'my_graph'
  FILTER "red" NOT IN p.edges[*].color
    RETURN v
```

which will only have vertices not connected by a red edge.
If you know the Position where the edge is expected you can give it directly which helps our optimizer a lot and will yield higher performance:

```
FOR v, e, p IN 1..5 OUTBOUND 'vertex/A' GRAPH 'my_graph'
  FILTER p.edges[2].color != "red"
    RETURN v
```

Hope this helps.

**Comment by thwd-duda** [comment]
@mchacki Thank you for your answer. I have implemented your feedback on my side. This is one query I eventually conjectured:
```
FOR v, e, p IN 1..10 ANY "ClCAfERxwdy/QmjmfnRbyuN" GRAPH "wJylPDSnoYa"
    FILTER (p.edges[*].fromType ALL == "ClCAfERxwdy"  && p.edges[*].toType ALL == "ClCAfERxwdy" )
    RETURN DISTINCT v
```
It takes 4.434 seconds to return 12 documents. I don't think the branch-exclusion is working, yo.

The use case is as follows: We have a dynamic number of document collections (circa 100), all connected in one big graph by one big edge collection (because of the 32 collection limitation that started this thread). Now we need to query this graph, limiting what "types" of nodes are traversed. A "type" is simply the collection name in which a document lives.

Simplified Scenario: Assume three document collections; C1, C2 and C3. About 20 documents in each collection. These 60 documents are heavily interconnected, about 180 edges between them, including intra-collection relations. Now I'd like to query for all C1 documents transitively reachable from some specific C1 object, without considering C2 and C3 documents.

**Comment by dothebart** [comment]
you could try to change that limit and report back your experience with the bigger number; its in:

    arangod/Aql/Collections.h:  static size_t const MaxCollections = 32;

maybe you put 128 in there, and check whether it gives you good performance.
The number 32 was just chosen as an arbitrary value - so increasing it isn't known to burst in flames..
if you can report back good experiences, we may consider making this value a configuration option then.

About How to compile from source, have a look at:
  https://docs.arangodb.com/cookbook/Compiling/index.html

**Comment by jsteemann** [comment]
@thwd-duda: please not that the query 
```
FOR v, e, p IN 1..10 ANY "ClCAfERxwdy/QmjmfnRbyuN" GRAPH "wJylPDSnoYa"
    FILTER (p.edges[*].fromType ALL == "ClCAfERxwdy"  && p.edges[*].toType ALL == "ClCAfERxwdy" )
    RETURN DISTINCT v
```
will not do any early branch exclusions. The filter conditions will only be applied for the result set but not during the traversal. 
The reason is that currently not all filter conditions qualify for branch exclusion, but only some. Using the `ALL ==` will disqualify the condition. In the explain output of the query, the "Traversals on graphs" section should not list anything in "filter conditions" for the above query, meaning there will be no branch exclusion inside the traversal. If the filters are modified to not contain the `ALL ==` branch exclusion may be applied. When applied, the filter condition will show up in the "filter conditions" sections of the traversal explain output.

**Comment by jsteemann** [comment]
Btw. we have adjusted the max. number of collections per query to 256 in 3.0.1
