### ISSUE TITLE
Is there a maximum number of indexes per collection?

### ISSUE THREAD

**Issue by MrCreosote** [arangodb/arangodb#19105]
This is a question, not a bug report / feature request.

I'm wondering if there's a maximum number of indexes allowed per collection (e.g. like [MongoDB's limit of 64](https://www.mongodb.com/docs/manual/reference/limits/#mongodb-limit-Number-of-Indexes-per-Collection)). I can't seem to find an answer to this in the docs, issues, via Google, and even chatGPT doesn't know, so is is just bounded by memory / disk size?

Thanks!

**Comment by MBkkt** [comment]
Hello. We don't have such restriction

> so is is just bounded by memory / disk size?

Yes.

Note, some code probably could work slower than expected if collection will have like 1e5 indexes.
Because on practice most users commonly don't create more than few hundreds indexes per collection
