### ISSUE TITLE
CONCAT_SEPARATOR inserting nonsense characters

### ISSUE THREAD

**Issue by roman1720** [arangodb/arangodb#1914]
Hi, I have query:

  let maxTs=(for m in vCollect sort m.tsStart desc limit 0,1 return round(m.tsStart/1000))
        let changes=(
          for c in vCounters
          filter c.ts >= maxTs[0]
          for v in vVlan
          filter v._id == c.vId
          filter c.dValues.changeRate > 0
          for dev in vDevice
          filter v.vDeviceId == dev._id
          return {id: dev._id, device: dev.hostname, vlan: CONCAT_SEPARATOR('', v.vlanId, ' (', round(c.dValues.changeRate*1000)/1000, ')'), change:c.dValues.changeRate})
          for c in changes
          collect dev = c.id into g
          return {device: g[0].c.device, totalChanges: round(sum(g[*].c.change)*1000)/1000, vlans: CONCAT_SEPARATOR(', ',g[*].c.vlan)}

with output:

[
  {
    "device": "lab54unl65SD6",
    "totalChanges": 0.08,
    "vlans": "Vl1 (0.008), Vl21 (0.008), Vl22 (0.008), Vl23 (0.008), Vl24 (0.008), Vl25 (0.008), Vl26 (0.008), Vl27 (0.008), Vl28 (0.008), Vl29 (0.008)l73AC22DvlanLVl31 (0.028)Fchange\u001by�&1\b?>\u0016\u0003,\u000bW\u0001Ac\u000bR\u0004BidOvDevice/3762523FdeviceNlab54unl73AC22DvlanLVl32 (0.028)Fchange\u001by�&1\b?>\u0016\u0003,?>\u0016\u0003,\u0016\u0003-"
  },
  {
    "device": "lab54unl65SD5",
    "totalChanges": 0.08,
    "vlans": "Vl1 (0.008), Vl21 (0.008), Vl22 (0.008), Vl23 (0.008), Vl24 (0.008), Vl25 (0.008), Vl26 (0.008), Vl27 (0.008), Vl28 (0.008), Vl29 (0.008)l73AC22DvlanLVl31 (0.028)Fchange\u001by�&1\b?>\u0016\u0003,\u000bW\u0001Ac\u000bR\u0004BidOvDevice/3762523FdeviceNlab54unl73AC22DvlanLVl32 (0.028)Fchange\u001by�&1\b?>\u0016\u0003,?>\u0016\u0003,\u0016\u0003-"
  },
etc.....

I tried to replicated it:

let vlan = ([
     "Vl1 (0.008)",
      "Vl21 (0.008)",
      "Vl22 (0.008)",
      "Vl23 (0.008)",
      "Vl24 (0.008)",
      "Vl25 (0.008)",
      "Vl26 (0.008)",
      "Vl27 (0.008)",
      "Vl28 (0.008)",
      "Vl29 (0.008)"
    ])
return CONCAT_SEPARATOR(', ',vlan)

but this returns correct result
[
  "Vl1 (0.008), Vl21 (0.008), Vl22 (0.008), Vl23 (0.008), Vl24 (0.008), Vl25 (0.008), Vl26 (0.008), Vl27 (0.008), Vl28 (0.008), Vl29 (0.008)"
]

On previous 2.8 version it worked correctly, now I'm running 3.0

Thanks
Roman

**Comment by jsteemann** [comment]
Thanks for reporting this. Fixed in 3.0.1.
