### ISSUE TITLE
Services page not opening after disabling all authentication in config files

### ISSUE THREAD

**Issue by sajeevpr** [arangodb/arangodb#1916]
Hello team,
  I am getting the below error when I tried to access the services page. This is coming in the developer console. I disabled all authentication in config files.

http://ldnpsr000001183:8529/_db/_system/_admin/aardvark/foxxes

{"error":true,"errorNum":400,"errorMessage":"header \"authorization\" is required","code":400}

Regards,
Sajeev

**Comment by jsteemann** [comment]
This is a bug in 3.0.0, and it has been fixed in 3.0.1.

**Comment by sajeevpr** [comment]
@jsteemann ,
  Can I make this change locally in js file and test?

Regards,
Sajeev

**Comment by jsteemann** [comment]
I think that should be doable. This is the commit that should have fixed it:
```diff
commit 189af6f4990a5d110f17a1a51286d57de85544ea
Author: Frank Celler <frank@arangodb.com>
Date:   Thu Jun 23 10:05:32 2016 +0200

    authorization is optional

diff --git a/js/apps/system/_admin/aardvark/APP/foxxes.js b/js/apps/system/_admin/aardvark/APP/foxxes.js
index ffb16ae..2e39f59 100644
--- a/js/apps/system/_admin/aardvark/APP/foxxes.js
+++ b/js/apps/system/_admin/aardvark/APP/foxxes.js
@@ -52,7 +52,7 @@ router.use((req, res, next) => {
   }
   next();
 })
-.header('authorization', joi.string().required(), 'ArangoDB credentials.');
+.header('authorization', joi.string().optional(), 'ArangoDB credentials.');
 
 
 const foxxRouter = createRouter();
```

**Comment by sajeevpr** [comment]
Great. It worked :+1: 

Thanks a lot
