### ISSUE TITLE
3.10.6 Number of documents 18 quintillion in Web UI

### ISSUE THREAD

**Issue by aa-exl** [arangodb/arangodb#19176]
## My Environment

* __ArangoDB Version__:        3.10.6
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               
* __Infrastructure__:               AWS
* __Operating System__:        Ubuntu 20.04 
* __Total RAM in your machine__:        32Gb
* __Disks in use__:        SSD 
* __Used Package__:              Ubuntu .deb 

## Component, Query & Data

__Affected feature__:
Web interface 

__Size of your Collection on disk__: 13Mb

__Replication Factor & Number of Shards (Cluster only)__: None

We recently updated our ArngoDB version from 3.8.0 to 3.10.6.
We updated incrementally as specified in the docs.

__Problem__:

1.  Web UI shows incorrect number of docs. Also cannot use the last page button as the ui hangs if we click it 
Shows number of docs as 18 quintillion:

![image](https://github.com/arangodb/arangodb/assets/135604561/77fd43fe-7d3b-4b4e-9d94-08d10021db2d)

2. Logs keep showing file not found error for a static js file:
![image](https://github.com/arangodb/arangodb/assets/135604561/7d0433bd-973c-467a-97b6-fd84c4e94434)

__Expected result__:
1. Number of docs should be correct.

**Comment by Simran-B** [comment]
Do you have an ad-blocker installed in your browser? If so, please disable it and check the document count again.

**Comment by AshwinExaloan** [comment]
> Do you have an ad-blocker installed in your browser? If so, please disable it and check the document count again.

Disabled my adblocker and its still the same issue.
I tried it in incognito also with all extensions disabled and i still get the 18 quintillion records.

**Comment by AshwinExaloan** [comment]
Hi thanks for looking into it, PFB the requested screenshots:
1. Count API:
```json
{
    "error": false,
    "code": 200,
    "writeConcern": 1,
    "waitForSync": false,
    "usesRevisionsAsDocumentIds": false,
    "syncByRevision": false,
    "statusString": "loaded",
    "isSystem": false,
    "internalValidatorType": 0,
    "cacheEnabled": false,
    "count": 18446744073709551558,
    "globallyUniqueId": "h238A2BEE19AD/22368590",
    "id": "22368590",
    "isSmartChild": false,
    "schema": null,
    "keyOptions": {
        "allowUserKeys": true,
        "type": "traditional",
        "lastValue": 0
    },
    "name": "coll_name",
    "computedValues": null,
    "objectId": "22368589",
    "type": 2,
    "status": 3
}
```

2. Job (Have omitted the results array)

```json
{
   "hasMore": false,
    "cached": false,
    "extra": {
        "warnings": [],
        "stats": {
            "writesExecuted": 0,
            "writesIgnored": 0,
            "scannedFull": 10,
            "scannedIndex": 0,
            "cursorsCreated": 0,
            "cursorsRearmed": 0,
            "cacheHits": 0,
            "cacheMisses": 0,
            "filtered": 0,
            "httpRequests": 0,
            "executionTime": 0.07848244096385315,
            "peakMemoryUsage": 229376
        }
    },
    "error": false,
    "code": 201
}

```

3. Query results return the correct count:

![image](https://github.com/arangodb/arangodb/assets/135604561/61719b2f-b0d0-4f53-8612-0838130e9a84)

**Comment by palashkaria** [comment]
Thanks @AshwinExaloan, looks this could be an issue with the stored statistics as the query returns the right answer. We have a [`recalculateCount`](https://www.arangodb.com/docs/stable/http/collection.html) API which can potentially be useful there

To invoke this, you can follow these steps:

1. Go to 'Support' tab from the left sidebar.
2. Switch to the 'Rest API' tab.
3. Scroll to look for 'Collections', open that, and look for the API - `/_api/collection/{collection-name}/recalculateCount` (it's a PUT request, screenshot below).
4. Click on 'Try it out', enter your collection name in the input box, and click 'Execute'.
5. Go back to the collection and see if that fixes it.

Let me know if this works!

<img width="730" alt="image" src="https://github.com/arangodb/arangodb/assets/2976363/aab00d06-56a0-4e5b-9352-d086b5d0a9e1">

**Comment by palashkaria** [comment]
Hey @aa-exl, just checking in, were you able to resolve this using the steps above?
