### ISSUE TITLE
api breaking changes

### ISSUE THREAD

**Issue by ra0o0f** [arangodb/arangodb#1918]
Hello

is there a place for the http/internal-js API api breaking changes? i found [ArangoDB 3.0 New Features](https://docs.arangodb.com/3.0/Manual/ReleaseNotes/NewFeatures30.html) for major changes but it would be great if there is one place for all changes on each versions. 

im fixing the API for working with edges in ArangoDB 3.0 (https://github.com/ra0o0f/arangoclient.net/issues/47). any suggestion on how should i prevent this kind of issues? (inform users for deprecation's? add tests for requesting database on all APIs?)

thanks

**Comment by Simran-B** [comment]
You find the incompatible changes in the same chapter (release notes):

https://docs.arangodb.com/3.0/Manual/ReleaseNotes/UpgradingChanges30.html

In addition, there's an upgrading chapter under administration:

https://docs.arangodb.com/3.0/Manual/Administration/Upgrading/Upgrading30.html

**Comment by ra0o0f** [comment]
@Simran-B thanks. how did i miss that

**Comment by Simran-B** [comment]
Regarding graph functions, we offer 3 cookbook recipes about how to migrate:

https://docs.arangodb.com/3.0/cookbook/AQL/MigratingGraphFunctionsTo3.html
