### ISSUE TITLE
Web UI Query Tool regressions

### ISSUE THREAD

**Issue by andy-c-steele** [arangodb/arangodb#19184]
## My Environment

* __ArangoDB Version__:       3.11
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   ArangoDB Starter & ArangoDB Official Docker instance
* __Configuration__:               No specific configuration
* __Infrastructure__:               ArangoDB Docker image in Portainer, one VMWare instance
* __Operating System__:        Ubuntu 18.04 in VMWare
* __Total RAM in your machine__:        64GB
* __Disks in use__:        SSD
* __Used Package__:              Debian or Ubuntu .deb and Docker - official Docker library

## Component, Query & Data

__Affected feature__:
AQL query using web interface

__AQL query (if applicable)__:
```
for e in 1..10
    return {val:e}
```
## Steps to reproduce

1. Run query
2. In results pane, switch to JSON view
3. Results pane empty
4. Click once on line number 1 in left hand margin, results show.

With same query
1. Run query
2. In results pane
3. Click Download button - no result
4. Click Copy to Editor - no result
5. Download CSV button does work.

__Problem__:
Regressions in Web UI Query UI after upgrading to v3.11 in two different instances, one the official Docker image and one using ArangoDB starter in a VMWare instance running Ubuntu

__Expected result__:
1. JSON results should be expanded and visible when switching JSON view
2. Download and Copy to Editor should be functional

**Comment by Simran-B** [comment]
I can reproduce the empty results panel (clicking in the text area populates it).

The Download button not working is a known issue:
https://www.arangodb.com/docs/stable/release-notes-known-issues311.html#:~:text=Date%20Added%3A%202023,BTS%2D1424%20(internal)

**Comment by palashkaria** [comment]
Thank you so much for the report @andy-c-steele 🙂, this was indeed a rendering bug.

Fixed in #19953 & released as a part of`v3.11.5`. 
Please update the DB version & try it out!
