### ISSUE TITLE
Creating graphs with multiple edge definitions programmatically

### ISSUE THREAD

**Issue by ropeladder** [arangodb/arangodb#1923]
Note: I originally opened this in arangojs [https://github.com/arangodb/arangojs/issues/259] but @pluma suggested I open it here. I have only tried this in arangojs, not arangosh.

~

I'm trying to create a "combined" graph that is a combination of my other graphs, but when I try to add edge definitions arangojs gives me back this error:
`error: ArangoError: [name of collection I already used] edge collection already used in edge def`

This is presumably because I already used the edge collection in another graph definition. But I cannot figure out how to re-use edge definitions that I have already defined elsewhere; the documentation doesn't have any examples of this.

 I _am_ able to assign multiple edge collections to a graph using the web frontend.

My code looks like this (the second bit throws the error):

```
db.graph('myGraph1').create({edgeDefinitions: [{ collection: 'edge1',from:['doc1'],to:['doc2']}]}).then( ... )

db.graph('combinedGraph').create({edgeDefinitions: [
    { collection: 'edge1',from:['doc1'],to:['doc2']},
    { collection: 'edge2',from:['doc1'],to:['doc3']}
]}).then( ... )
```

I'm running 3.0.1 on Linux Mint 17.3.

**Comment by dothebart** [comment]
I think you can only use a *similar* edge definition on another graph, but not the instance you've used on that one. Does that make sense?

**Comment by ropeladder** [comment]
Conceptually, yes, it makes sense... but I don't understand how to do it. Specifically, I'm not clear on how to create edgeDefinitions (either using `graph().create({edgeDefinitions: ... })` or the `createEdgeDefinitions()` function) with a unique identifier, or how to reference that identifier from within `graph().create()`.

**Comment by dothebart** [comment]
Graph definitions may not overlap. 
Else consistency could not be waranted.
