### ISSUE TITLE
Apt repository is very slow

### ISSUE THREAD

**Issue by AlexLuya** [arangodb/arangodb#1924]
Hello,
     Always got:

```
Get:1 https://www.arangodb.com/repositories/arangodb3/xUbuntu_16.04  arangodb3 3.0.1 [43.4 MB]
Err:1 https://www.arangodb.com/repositories/arangodb3/xUbuntu_16.04  arangodb3 3.0.1              
  GnuTLS recv error (-9): A TLS packet with unexpected length was received.
Get:2 https://www.arangodb.com/repositories/arangodb3/xUbuntu_16.04  arangodb3-client 3.0.1 [28.4 MB]
Err:2 https://www.arangodb.com/repositories/arangodb3/xUbuntu_16.04  arangodb3-client 3.0.1       
  GnuTLS recv error (-9): A TLS packet with unexpected length was received.
E: Failed to fetch https://www.arangodb.com/repositories/arangodb3/xUbuntu_16.04/./amd64/arangodb3_3.0.1_amd64.deb  GnuTLS recv error (-9): A TLS packet with unexpected length was received.

E: Failed to fetch https://www.arangodb.com/repositories/arangodb3/xUbuntu_16.04/./amd64/arangodb3-client_3.0.1_amd64.deb  GnuTLS recv error (-9): A TLS packet with unexpected length was received.
```

can't be installed.

**Comment by AlexLuya** [comment]
Speed seems far more faster now.

**Comment by dothebart** [comment]
Thanks for staying in touch.

**Comment by AlexLuya** [comment]
still very slow,can't do updating

**Comment by dothebart** [comment]
Hi, 
when this occurs the next time, can you provite a traceroute from your machine to arangodb.com? 
And, does the rest of ArangoDB.com work fast for you?

**Comment by pekeler** [comment]
and then you could compare it to traceroutes from other locations with http://mtr.guru/?arangodb.com

**Comment by rekhajoshm** [comment]
@AlexLuya - Hi.This is not an arangodb issue, but a known/open issue with Ubuntu gnutls behavior for connecting to https behind proxy. [cc @dothebart @pekeler  ]

Bug - https://bugs.launchpad.net/ubuntu/+source/gnutls26/+bug/1111882
Workaround - http://askubuntu.com/questions/186847/error-gnutls-handshake-failed-when-connecting-to-https-servers/187199#187199

Hope this helps.thanks.

**Comment by dothebart** [comment]
@rekhajoshm I hope this has been fixed meanwhile so I'll close this now.

**Comment by AlexLuya** [comment]
@dothebart the problem remains,@rekhajoshm,that workaround works for git,how to apply it to installation
