### ISSUE TITLE
`MERGE` and `MERGE_RECURSIVE` are oddly slow

### ISSUE THREAD

**Issue by Avocher** [arangodb/arangodb#19259]
## My Environment

* __ArangoDB Version__:        3.11.0
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:  ArangoDB Starter in Docker
* __Configuration__:               Default
* __Infrastructure__:               Macbook
* __Operating System__:        MacOS 13.4
* __Total RAM in your machine__:        32Gb
* __Disks in use__:        SSD
* __Used Package__:            Docker - official Docker library

## Component, Query & Data

__Affected feature__:
AQL query using web interface

__AQL query (if applicable)__:
```
RETURN MERGE(
    FOR idx in 1..2000
    return {[idx]: { index: idx }}
)
```
__AQL explain and/or profile (if applicable)__:
```
Query String (73 chars, cacheable: false):
 RETURN MERGE(
     FOR idx in 1..2000
     return {[idx]: { index: idx }}
 )

Execution plan:
 Id   NodeType            Calls   Items   Filtered   Runtime [s]   Comment
  1   SingletonNode           1       1          0       0.00001   * ROOT
  3   CalculationNode         1       1          0       0.00001     - LET #3 = 1 .. 2000   /* range */   /* simple expression */
 10   SubqueryStartNode       1       2          0       0.00001     - LET #1 = ( /* subquery begin */
  4   EnumerateListNode       3    2001          0       0.00015       - FOR idx IN #3   /* list iteration */
  5   CalculationNode         3    2001          0       0.00152         - LET #5 = { [ idx ] : { "index" : idx } }   /* simple expression */
 11   SubqueryEndNode         1       1          0       0.00020         - RETURN  #5 ) /* subquery end */
  8   CalculationNode         1       1          0       0.24108     - LET #7 = MERGE(#1)   /* simple expression */
  9   ReturnNode              1       1          0       0.00001     - RETURN #7

Indexes used:
 none

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   splice-subqueries

Query Statistics:
 Writes Exec   Writes Ign   Scan Full   Scan Index   Cache Hits/Misses   Filtered   Peak Mem [b]   Exec Time [s]
           0            0           0            0               0 / 0          0         163840         0.24345

Query Profile:
 Query Stage               Duration [s]
 initializing                   0.00000
 parsing                        0.00010
 optimizing ast                 0.00001
 loading collections            0.00001
 instantiating plan             0.00003
 optimizing plan                0.00021
 instantiating executors        0.00008
 executing                      0.24301
 finalizing                     0.00003

```

__Dataset__:
None needed

__Size of your Dataset on disk__:
0

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. Run the query

__Problem__:
Both `MERGE` and `MERGE_RECURSIVE` are oddly slow. Merging 2000 small objects take 250ms on an m1 pro macbook.  Our current workaround is merge documents in javascript.

__Expected result__:
Expected speed similar to javascript or any other dynamic language.

**Comment by Simran-B** [comment]
This pattern creates a lot of temporary objects that are then merged together. A more efficient way is to use `ZIP()`:

```js
LET r = 1..2000
RETURN ZIP(r, r[* RETURN { index: CURRENT }])
```

**Comment by Avocher** [comment]
Hi,
Thank you for the response! We are currently in the process of removing all instances of `MERGE` from our codebase because they are taking up the bulk of all query time (adding multiple seconds to each query that would otherwise be around 100ms or less). Nice to see that we can replace with `ZIP`, it will save us some time with the refactoring.

Perhaps a small warning could be added to the documentation about the time complexity for `MERGE` and `MERGE_RECURSIVE`? I see a lot of beginners going for `MERGE` over `ZIP` in the Slack community.

**Comment by Simran-B** [comment]
Opened a PR to add a remark: https://github.com/arangodb/docs/pull/1417

I also filed an internal request FRB-264 for optimizing this use case a month ago.

**Comment by Avocher** [comment]
Great! I sincerely appreciate the assistance you've given.
