### ISSUE TITLE
How to access to the arango community slack

### ISSUE THREAD

**Issue by pxp928** [arangodb/arangodb#19250]
The link provided in https://www.arangodb.com/community/ for Slack does not allow access (expired?). What is the way to get invited into the community Slack for Arango?

**Comment by 153957** [comment]
I am part of the Slack community (not an admin) and just tried to create an invite link, I guess this should work: https://join.slack.com/t/arangodb-community/shared_invite/zt-1xmpftwvl-Jjl5eghYQoMyBTqeE~JI5w (valid for 30 days)

**Comment by TallAmy** [comment]
Hello,Please let me know if you need help. We can invite anyone directly or send the link to join.JulieOn Jun 17, 2023, at 11:22 PM, Arne de Laat ***@***.***> wrote:﻿
I am part of the Slack community (not an admin) and just tried to create an invite link, I guess this should work: https://join.slack.com/t/arangodb-community/shared_invite/zt-1xmpftwvl-Jjl5eghYQoMyBTqeE~JI5w (valid for 30 days)

**Comment by Simran-B** [comment]
You can use this link: https://arangodb-community.slack.com/

**Comment by pxp928** [comment]
> I am part of the Slack community (not an admin) and just tried to create an invite link, I guess this should work: https://join.slack.com/t/arangodb-community/shared_invite/zt-1xmpftwvl-Jjl5eghYQoMyBTqeE~JI5w (valid for 30 days)

This worked! Thank You!

**Comment by Arash-Sabet** [comment]
@TallAmy How can I join the slack community?

**Comment by 153957** [comment]
@Arash-Sabet @Aponace I can probably create a invite from within Slack if you share your email addresses, it may have to be approved by an admin first 🤷🏾 
![slack_invite](https://github.com/arangodb/arangodb/assets/1433682/bcf67475-43c7-444a-93cd-5b3e8fdffc85)

**Comment by Aponace** [comment]
@153957 I can do that but I think what we need it a community invite link that everyone can use as I have some other teammates that would like to have access as well. If it's not too much to ask, can you ping one of them and let them know of this issue? Cheers.

**Comment by 153957** [comment]
Apparently it should work with this URL: https://arangodb-community.slack.com/

**Comment by Aponace** [comment]
@153957 Unfortunately it doesn't:

Signin:
![image](https://github.com/arangodb/arangodb/assets/28574273/011a0f87-11c2-4e88-9f41-cfdd86833854)

Singup:
![image](https://github.com/arangodb/arangodb/assets/28574273/62111230-cba5-41ef-a370-bc6b8d3eba37)

**Comment by 153957** [comment]
^ @Simran-B

**Comment by Simran-B** [comment]
The only available configuration options for the Slack space all require invitations it seems.
Try this invite link: https://join.slack.com/t/arangodb-community/shared_invite/zt-2d4p43cma-flyf72j9a9wq4A2OtuMFkA

**Comment by Simran-B** [comment]
There is no longer an option for the Slack space to allow self-signup. Use this invite link:
https://join.slack.com/t/arangodb-community/shared_invite/zt-2d4p43cma-flyf72j9a9wq4A2OtuMFkA

**Comment by NguyenDiNguy** [comment]
Hi, can you help me to join too?

**Comment by prasad1411** [comment]
I want to join Slack community channel

**Comment by adoliner1** [comment]
Hi all, could I get an invite by chance?

adoliner@gmail.com

**Comment by Angad-2002** [comment]
Hi,
Can I get an invite?

**Comment by Angad-2002** [comment]
The invite has expired
