### ISSUE TITLE
Error 1227 - invalid document type in ArangoDB v3.0.1

### ISSUE THREAD

**Issue by mrkvon** [arangodb/arangodb#1929]
Since upgrading to ArangoDB 3.0 (v3.0.1), one of my queries is throwing an error `1227`: `invalid document type (while executing)`
The system is Arch Linux and ArangoDB is compiled from the source.
There are documents `users` in the database and the `messages` are edges between them.

__The failing query:__

    LET us = (
        FOR usr0 IN users FILTER usr0.username == "test1"
            FOR usr1 IN users FILTER usr1.username == "test2"
                RETURN {
                    u:usr0,
                    v:usr1
                }
    )
    FOR u IN us
        FOR msg IN messages
            FILTER msg._from == u.u._id && msg._to == u.v._id
            RETURN msg._id

__Some versions which don't fail:__

_changing object to array_

    LET us = (
        FOR usr0 IN users FILTER usr0.username == "test1"
            FOR usr1 IN users FILTER usr1.username == "test2"
                RETURN [
                    usr0,
                    usr1
                ]
    )
    FOR u IN us
        FOR msg IN messages
            FILTER msg._from == u[0]._id && msg._to == u[1]._id
            RETURN msg._id

_not using variable `us`_

    FOR usr0 IN users FILTER usr0.username == "test1"
        FOR usr1 IN users FILTER usr1.username == "test2"
            FOR msg IN messages
                FILTER msg._from == usr0._id && msg._to == usr1._id
                RETURN msg._id

_only one user_

    LET us = (
        FOR usr0 IN users FILTER usr0.username == "test1"
            RETURN {
                u:usr0
            }
    )
    FOR u IN us
        FOR msg IN messages
            FILTER msg._from == u.u._id
            RETURN msg._id

_parsing `_id`, `_from`, `_to`  to string with `CONCAT`_

    LET us = (
        FOR usr0 IN users FILTER usr0.username == "test1"
            FOR usr1 IN users FILTER usr1.username == "test2"
                RETURN {
                    u:usr0,
                    v:usr1
                }
    )
    FOR u IN us
        FOR msg IN messages
            FILTER CONCAT(msg._from) == CONCAT(u.u._id) && CONCAT(msg._to) == CONCAT(u.v._id)
            RETURN msg._id

It may be a bug. Otherwise comparing the tests which pass vs. fail doesn't make much sense (to me).

**Comment by jsteemann** [comment]
Internal note: the query is failing in Transaction.cpp:extractIdString() because _id is not a custom attribute.

**Comment by dothebart** [comment]
This will be fixed in 3.0.2 - Thanks for reporting.
