### ISSUE TITLE
Cluster Deployment With ArangoDB starter failed

### ISSUE THREAD

**Issue by MUDS7** [arangodb/arangodb#19314]
## My Environment

* __ArangoDB Version__:         3.10
* __Deployment Mode__:      | Leader/Follower ("Master/Slave")  | Cluster | 
* __Deployment Strategy__:   ArangoDB Starter
* __Configuration__:               cluster setup details
* __Infrastructure__:               
* __Operating System__:        Centos7.9
* __Total RAM in your machine__:        4GB
* __Disks in use__:        
* __Used Package__:             

__Problem__:
I deployed Machine A using the official website's deployment documentation
Machine A
![image](https://github.com/arangodb/arangodb/assets/64821712/ceb79e1c-ed48-46fd-bb99-942e84aded5e)

Matchine B
I deployed machines B and C using the corresponding commands, but Machine A did not detect the join of machines B and C.
![image](https://github.com/arangodb/arangodb/assets/64821712/94bd7936-fe16-45fd-a1a9-aca2a7bacbae)

Matchine C
![image](https://github.com/arangodb/arangodb/assets/64821712/63cf569d-dfaf-4f5a-b9cf-86349efe2056)

Matchine A still did not work
![image](https://github.com/arangodb/arangodb/assets/64821712/2b8f4a42-830e-4172-a3c0-50bcafb1fd0f)

**Comment by dothebart** [comment]
Hi, 
are you sure your machines can talk to each others? (firewall, network, ... )
You can try by hand by using [netcat](https://en.wikipedia.org/wiki/Netcat)  or [telnet](https://en.wikipedia.org/wiki/Telnet):

```
telnet 192.168.0.107 8529
Trying 192.168.0.107... <- this is the last you will see if no connection can be established
Connected to 192.168.0.107. <- this will appear once the connection can be established
Escape character is '^]'.
.... <- output of the server process will follow
```

**Comment by MUDS7** [comment]
I have tried using Telnet, and it was able to establish a successful connection, but the cluster deployment still doesn't work.

Matchine B
![image](https://github.com/arangodb/arangodb/assets/64821712/a78a3f6e-989a-44aa-894d-7e43340591dd)

Matchine A
![image](https://github.com/arangodb/arangodb/assets/64821712/7cae8578-7824-4c57-b783-14ea75ab6e30)

When I use Telnet from Machine B to Machine A, it is successful, but when I use Telnet from Machine A to Machine B, it fails. I'm not sure if this is a problem or not

![image](https://github.com/arangodb/arangodb/assets/64821712/6d3908f5-ccaf-4c4e-922e-8fbf73a7c0ff)

Since I'm using a virtual machine, the IP address is different from the previous one

**Comment by dothebart** [comment]
the starter doesn't open binding ports on the same port on each instance so if you ran all instances on one machine they don't collide. 
You can use `netstat -tulpn` to browse the binding services: 
```
root@bruecklinux:~# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      619284/sshd: /usr/s 
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      2064692/dnsmasq     
tcp        0      0 127.0.0.1:6010          0.0.0.0:*               LISTEN      1882613/sshd: willi 
tcp        0      0 127.0.0.1:6011          0.0.0.0:*               LISTEN      1882878/sshd: willi 
tcp6       0      0 :::9731                 :::*                    LISTEN      1883103/arangod     
tcp6       0      0 :::9730                 :::*                    LISTEN      1883402/arangod     
tcp6       0      0 :::9729                 :::*                    LISTEN      1883552/arangod     
tcp6       0      0 :::9728                 :::*                    LISTEN      1883090/arangodb    
tcp6       0      0 :::9531                 :::*                    LISTEN      1883397/arangod     
tcp6       0      0 :::9530                 :::*                    LISTEN      1883547/arangod     
tcp6       0      0 :::9529                 :::*                    LISTEN      1883581/arangod     
tcp6       0      0 :::9528                 :::*                    LISTEN      1883070/arangodb    
tcp6       0      0 :::9631                 :::*                    LISTEN      1883114/arangod     
tcp6       0      0 :::9630                 :::*                    LISTEN      1883404/arangod     
tcp6       0      0 :::9629                 :::*                    LISTEN      1883555/arangod     
tcp6       0      0 :::9628                 :::*                    LISTEN      1883080/arangodb    
```
this is a complete cluster running with `arangodb`-starters and `arangod`. the `LISTEN` lines contain their respective ports in the `Local Address` column.

So if you want to try a simple run first, you may launch the cluster on one machine. 

Please note that on different attempts and deployment modes you should not be using the same starter directories.

Switching IPs is also rather something not to do - so if you're able to you should pin the IPs of the VMs.

**Comment by MUDS7** [comment]
When I tried to deploy the cluster in a standalone configuration and attempted to deploy Matchine C, the following issues arose, and I'm unsure of the underlying cause.
![image](https://github.com/arangodb/arangodb/assets/64821712/75a63295-2b24-402b-b23e-2cc0a488f6b8)

Matchine A
![image](https://github.com/arangodb/arangodb/assets/64821712/a4a969fb-afd8-41c6-b4c6-f1e40c647d76)

**Comment by MUDS7** [comment]
Sorry, it was my previous mistake of not properly shutting down ArangoDB after starting it. I have successfully deployed the cluster in a single machine. However, on another machine, I am unable to stop the ArangoDB service. I have tried both the commands './arangodb stop' and './arangod stop' but neither of them works. When I attempt to use 'kill -9 pid', ArangoDB restarts with a different PID, preventing me from stopping the ArangoDB service.

![image](https://github.com/arangodb/arangodb/assets/64821712/8a7c2a24-c46a-4de4-87ad-b3b39c674635)

![image](https://github.com/arangodb/arangodb/assets/64821712/155dbc7d-9e15-4ea2-846a-0197d7573607)

**Comment by MUDS7** [comment]
I have resolved the issue with cluster deployment. The reason was that I did not delete the contents in "--starter.data-dir," but the cluster still has problems.

![image](https://github.com/arangodb/arangodb/assets/64821712/685766c0-47f9-4841-8244-bde74432b31e)

![image](https://github.com/arangodb/arangodb/assets/64821712/74a2d03c-8ae9-488c-ae18-bb8fe0277e05)

192.168.43.46:
![image](https://github.com/arangodb/arangodb/assets/64821712/7b7e9239-fa33-480d-adda-9e0c484dd417)

I don't know what wrong with it

**Comment by MUDS7** [comment]
After I replied to this question, I redeployed it again, but the deployment still failed. Here is the new log file information.

![image](https://github.com/arangodb/arangodb/assets/64821712/afcd4b5d-e9bc-43d9-a808-7ed6c0b6aa19)

**Comment by dothebart** [comment]
the agent has its own logfile, as I tried to point out. Its a sub-process launched by the starter and should live in its own described sub-directory. 
The `arangod.log` should contain hints like lines with `ERROR` or `FATAL` whats going on.

**Comment by MUDS7** [comment]
This arangod.log only contains these contents and does not have any ERROR or FATAL information.

**Comment by MUDS7** [comment]
![image](https://github.com/arangodb/arangodb/assets/64821712/cc93ffbc-6018-4c5f-bd66-05e7c43d2cb3)

**Comment by dothebart** [comment]
ok, yes, each instance needs its individual directory, if you run them on the same machine.

**Comment by MUDS7** [comment]
I deployed it using three machines with different machine, and I have already successfully deployed a standalone cluster
