### ISSUE TITLE
Adding FILTER to traverse AQL doesn't return the first node

### ISSUE THREAD

**Issue by guysegal** [arangodb/arangodb#19325]
I've experienced weird behavior which I think is bug.

For this simple graph:
111 ---a---> 222 ---a--> 333

This AQL query:
```
FOR v,e,p
 IN 0..3 OUTBOUND 'nodes/111' 
 GRAPH 'graph'         
 RETURN v
```
will return ["111" ,"222", "333"]

However, this AQL query:
```
FOR v,e,p
 IN 0..3 OUTBOUND 'nodes/111' 
 GRAPH 'graph'      
 FILTER  e.source == 'a'
 RETURN v
```
will return ["222", "333"]

Because `min` is 0 I expected to get the start node also
Am I missing something?

**Comment by nashikb** [comment]
There won't be an edge for the first vertex, since you're _starting_ from that vertex. In other words, there's no "-1" vertex with matching edge.

**Comment by guysegal** [comment]
@nashikb is there a way to perform this traversal and get the start vertex as well?

**Comment by nashikb** [comment]
Just thinking out loud: `FILTER e == null OR e.source == 'a'` ?

**Comment by guysegal** [comment]
@nashikb worked perfectly, thanks!
