### ISSUE TITLE
Edges should only be used in on type of vertice relation?

### ISSUE THREAD

**Issue by bateramos** [arangodb/arangodb#1933]
I have a Edge named "Has", and I use with various vertices like User Has Book, User Has LoanRequest, LoanRequest Has Book, Book Has Word and LoanRequest Has Message.
This is right? 
I ask this because in the create graph UI, I cannot create one that represent User Has LoanRequest, when I select the Edge Has, the toCollection and fromCollection is filled with Book and Word, and I can't change it.

**Comment by dothebart** [comment]
You probably have an edge collection "Has", right? You have several vertex collections, and you want to create edge documents, that connect vertex documents in these vertex collections? 

You then have edge definitions, that rule which vertex collections may be connected in which directions with which other vertex collections.

Most probably the UI isn't good for doing this. Have a look at the [example code](https://github.com/arangodb/arangodb/blob/devel/js/common/modules/%40arangodb/graph-examples/example-graph.js#L56) to [create the social graph example](https://docs.arangodb.com/3.0/Manual/Graphs/index.html#the-social-graph)

Does this explain it a little better?
