### ISSUE TITLE
How we use Synchronous replication for existing Database?

### ISSUE THREAD

**Issue by lalitlogical** [arangodb/arangodb#1934]
Version: Arangodb 3.0
OS: Ubuntu 14.04 (AWS EC2 instance)

I have created a project on ArangodDB 2.8. Recently I have upgraded the Arangodb to version 3.0 and restore the database from old one. I have  also setup the Asynchronous replication by creating two Arangodb 3.0 server. It is working fine. 

But I want Synchronous replication between these servers for scalability of my project. So how I can use Synchronous replication b/w these servers.?

This [doc](https://docs.arangodb.com/3.0/Manual/Administration/Replication/Synchronous/Implementation.html) point that you have to create the collection with replicationFactor, to activate synchronous replication for this collection. When I already have many collections, How can I activate synchronous replication for my collections? Have I need to create these collections again? How will I restore my database?

I have used below command on **arangosh** for my collection **posts**. Will this activate synchronous replication for **posts** collection.

```
arangosh
db._useDatabase("myDatabase");
db.posts.properties({ "replicationFactor" : 2 });
```

Thanks

**Comment by m0ppers** [comment]
The short answer is no: changing the replication factor later is not possible.

We hope to implement it for one of the upcoming releases. So to activate replicationFactor for your existing collections you currently have to create a new collection with the desired replicationFactor, copy all the data (as in `FOR doc in myCol INSERT doc INTO myColWithCorrectReplicationFactor`) and swap names with the original collection :|

I have added a note to the manual.

**Comment by m0ppers** [comment]
Ah forgot that renaming collections is not supported in the cluster :| Forget about this.

Here is a cookbook recipe on how to enable sync replication when migrating from 2.8 to 3.0:

https://docs.arangodb.com/cookbook/Administration/Migrate2.8to3.0.html#controling-the-number-of-shards-and-the-replication-factor

**Comment by lalitlogical** [comment]
@m0ppers I have already migrated from 2.8 to 3.0

Do want to say that first I take the dump of my database and modify the `***.structure.json` like below by adding `"replicationFactor": 2`.

`**{"parameters":{"replicationFactor": 2 ....}}**`

And now restore it again. This process will start the synchronous replication. Is this right?

**Comment by m0ppers** [comment]
Yes :)

I just reread your original question and have a little note to add: You are stating that you want synchronous replication to improve scalability.

The current implementation of the sync. replication will not help you in this case:

Synchronous replication will make your cluster more fail safe. Every write request will be send to all followers before it will be reported a success (this means write request will have a higher latency from the clients perspective).

For reading we are currently ONLY using the leader of the shard. This means that you won't achieve better read scalability either. This is due to consistency issues (to guarantee correct transaction handling). A "fix" for this is on our near roadmap.

**Comment by lalitlogical** [comment]
`The current implementation of the sync. replication will not help you in this case:`

@m0ppers Is this due to my implementation process or Arangodb's current functionality for sync. replication.

Actually, I have created a backend server for an app. So I need the faster response for better user experience. So if I implement synchronous replication, it will break the user experience with slow/delay response.

**Comment by m0ppers** [comment]
the only way to achieve better read scaling with arangodb 3.0 is using asynchronous replicas. 

synchronous replication in its current state is only useful to achieve fail safety within the cluster. If you have further questions I think it would be better to ask it on the google group (https://groups.google.com/forum/#!forum/arangodb) or on the community slack channel (https://arangodb-community.slack.com/). This is not really the place for a discussion :)

**Comment by lalitlogical** [comment]
@m0ppers , Thanks for suggestions :)

**Comment by lalitlogical** [comment]
@m0ppers, I have the last question. Hope you do not mind. I understand this is not the right place for discussion but I want to remove my doubts.

In synchronous replication, we never mention the slave or another Arnagodb server TCP address like in asynchronous replication, and it also not mentioned in docs. How does it know about the other arangodb server? Does leader/followers create on the same arangodb server? Can you please explain it to me?

**Comment by m0ppers** [comment]
it is actually mentioned but indeed not really clearly:

``` The cluster will determine suitable leaders and followers for every requested shard (numberOfShards) within the cluster.```

The cluster organizes itself via the data saved in the agency and from there it knows which servers form the cluster. Each server is registered there with its address so you as the user have indeed nothing to setup (except for passing the correct startup parameters).

During collection creation the cluster will choose from the pool of dbservers which servers it should take and of course a dbserver can not be follower and leader at the same time. So unless you are starting two dbservers on the same machine leader and follower will always be on separate machines.

**Comment by lalitlogical** [comment]
@m0ppers I have started an discussion [here](https://groups.google.com/forum/#!topic/arangodb/8MXVV2qEUkw). Can you please reply [here](https://groups.google.com/forum/#!topic/arangodb/8MXVV2qEUkw)?
