### ISSUE TITLE
Feature request: Per-request middlewares in Foxx

### ISSUE THREAD

**Issue by ilearnio** [arangodb/arangodb#1935]
In express we can hook up chain of middlewares directly to a specific route, like so:

``` js
app.get('/admin/delete_user/:id', isUserAdmin(), canDeleteUsers(), function (req, res, next) {
  if (!req.params.id) {
    return next(err) // --> pass error next to adminErrorHandler middleware
  }

  deleteUser(req.params.id)

  res.end('User deleted')
}, adminErrorHandler())
```

But I could not find an easy way to do so with `module.context.use`. It looks like it can only be attached to all routes globally. The lack of `next` argument in the router is a bit inconvenient and leads to incompatibility with existing node's ecosystem.

Just wonder why do you decide to reinvent a new framework again, spend so much time end effort on development and on fixing further issues, if you could just use Node's [connect](https://www.npmjs.com/package/connect) module for handling middlewares which is used by Express. It's very tiny, battle tested and has great compatibility with tons of Express middlewares. And it could be also used together with [Express router](https://www.npmjs.com/package/router).

Guys, you have npm modules support now! There are 300000+ packages out there and you keep inventing your own... Sorry for being such a pesky, but I just don't understand

**Comment by pluma** [comment]
The `use` method is available on both the `module.context` and the router (`app` in your example). It also takes an optional path as a first argument. Middleware that is mounted on the same path as a route handler will be invoked before that route handler. However there is currently no equivalent of `next(err)`.

The reason Foxx remains partially incompatible with Express is that ArangoDB only supports synchronous JavaScript whereas Node.js modules are typically written to be asynchronous. We can't just slot in the `connect` library because it expects request and response objects to be asynchronous. Broadly speaking: you want async logic in a stream based web server, but you want sync behaviour when dealing with locks and transactions in a database.

**Comment by ilearnio** [comment]
As far as I concern `connect` is just a middleware layer that receives `req` and `res` objects from Node's `http.createServer` and then passing them down the chain of middlewares. It does performing some asynchronous stuff and couldn't be just slotted in as is, yet there's not so much code and it shouldn't be difficult to port it i guess.

What I'm trying to say is that it would be better if the router will stick to some existing pattern like connect/express or koa, so we could install and use existing middlewares from npm rather than write our own for every particular case. For example, there is `express-graphql` package, which I would like to use, it solves many problems that I might face some day later, but since it is not compatible I have to either port it myself or wait until someone else will do it or just stick to some raw implementation like I currently have. Wouldn't it be great if ArangoDB would be compatible with Express (because it has biggest devs community) packages (at least some non-async) out of the box? That might be a huge bonus

**Comment by pluma** [comment]
@ilearnio per-route middleware functions have been implemented in the devel branch and will probably be in the upcoming 3.1 release.

**Comment by ilearnio** [comment]
Great news! Thanks!

**Comment by hkernbach** [comment]
ArangoDB 3.1 has been released. Please note that the download urls and repositories have changed slightly. 

[Download](https://www.arangodb.com/download) or see [Release Notes](https://docs.arangodb.com/3.1/Manual/ReleaseNotes/NewFeatures31.html) for details.
