### ISSUE TITLE
updateDocument: field _key should be ignored when null

### ISSUE THREAD

**Issue by mpv1989** [arangodb/arangodb#1938]
When updating a document the field _key in the passed document should be ignored when its value is null. A error should only be thrown, when the value is != null.

[https://github.com/arangodb/arangodb-java-driver/pull/44](url)

**Comment by dothebart** [comment]
Hm, at least in ArangoDB 3.0.x this throws an error:

127.0.0.1:8529@_system> db._query('FOR x IN circles UPDATE {_key: null, blarg: "blub"} in circles')
JavaScript exception in file '/local/home/willi/src/pipeline/js/client/modules/@arangodb/arangosh.js' at 97,7: ArangoError 1226: missing document key (while executing)

So I guess you've tried with 2.8?

**Comment by jsteemann** [comment]
The issue was originally reported for the HTTP REST API.

**Comment by Simran-B** [comment]
I can confirm that

    UPDATE "X" WITH {_key: null, foo: "bar"} IN coll

adds the attribute `foo`, but silently ignores the requested _key change. This can be seen in web interface or with curl for instance:

    cmd> echo {"query": "UPDATE 'X' WITH {_key: null} IN coll"} | curl -u root: -X POST http://localhost:8529/_db/_system/_api/cursor -d @-

arangosh has apparently a client-side check, but the HTTP API should have something too - a [1804 error (`ERROR_KEYVALUE_KEY_NOT_CHANGED`)](https://docs.arangodb.com/3.0/Manual/Appendix/ErrorCodes.html#ERROR_KEYVALUE_KEY_NOT_CHANGED) as warning?

**Comment by dothebart** [comment]
Fixed in 2.8.11 and 3.0.3
