### ISSUE TITLE
input of field _key ignored

### ISSUE THREAD

**Issue by karsten-wolfert** [arangodb/arangodb#1940]
If I create the first new doc in my collection, the DB uses my input "A" for the _key field.
If I create a second and several new docs, the DB forgets my input to the _key field and uses his own auto-generated value.

Environment:
Server: Windows 10 --> Docker --> latest Docker image --> ArangoDB Container
Client: Windows 10 --> current Google Chrome --> ArangoDB web user interface V3.0

**Comment by dothebart** [comment]
Hm, tried to reproduce using chrome 51.0 with ArangoDB 3.0.2, and failed. 
What I did:
Collections->Add Collection -> "test"
Click -> test
Click -> `+`
Enter a key `1`, `create`
Click -> `+` in the upper right corner
Enter a key `1`, `create` - I get an error message that it already exists.
Enter a key `2`, `create` - the document is created.
Each saved document is there in the overview.

**Comment by dothebart** [comment]
any news on this? or can we close this?

**Comment by karsten-wolfert** [comment]
Yes close it. It is not happen again.

**Comment by dothebart** [comment]
okies. closing.
