### ISSUE TITLE
[3.0.0] Query LIMIT bumps cursor's fullCount beyond real value 

### ISSUE THREAD

**Issue by thwd-duda** [arangodb/arangodb#1941]
### Repro

Create document collection `myCollection` and add 5 documents.

Write simple AQL query:

```
FOR o in myCollection
    LIMIT 30, 10
    RETURN o
```

(Result set empty as expected)

Post query to `/_db/<database-name>/_api/cursor` via HTTP interface with `fullCount` set to `true` in `options`.

Returned cursor says `extra.stats.fullCount` equals to 30, not 5.

### Bonus

 [Documentation](https://docs.arangodb.com/3.0/HTTP/AqlQueryCursor/AccessingCursors.html) says `fullCount` is property of `extra`, is actually property of `extra.stats`.

### Usual stuff

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04 LTS
Release:    16.04
Codename:   xenial
```

```
$ uname -a
Linux [redacted]4.4.0-24-generic #43-Ubuntu SMP Wed Jun 8 19:27:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ arangod --version
3.0.0

architecture: 64bit
asan: false
asm-crc32: true
boost-version: 1.61.0b1
build-date: 2016-06-22 12:27:17
compiler: gcc
cplusplus: 201103
endianness: little
fd-client-event-handler: poll
fd-setsize: 1024
icu-version: 54.1
jemalloc: true
libev-version: 4.22
maintainer-mode: false
openssl-version: OpenSSL 1.0.2g-fips  1 Mar 2016
rocksdb-version: 4.8.0
server-version: 3.0.0
sizeof int: 4
sizeof void*: 8
sse42: false
tcmalloc: false
v8-version: 5.0.71.39
vpack-version: 0.1.30
zlib-version: 1.2.8
```

**Comment by jsteemann** [comment]
Fixed in branches 3.0 and devel. Fix will become available in release 3.0.3.
