### ISSUE TITLE
Logging error objects in arangod

### ISSUE THREAD

**Issue by ilearnio** [arangodb/arangodb#1944]
After I spent hours on finding out the reason why my script logs empty error message (`{ "errors" : [ [Object { }] ] }`) to arangod's terminal output, I realized that it is not about my script but about how ArangoDB logs errors. For example, when I do:

``` js
console.log(new Error('Something bad happened'))
```

I'm getting:

``` bash
2016-07-15T18:12:52Z [7090] INFO [Object { }]
```

For comparison, here is how Node outputs it:

``` bash
Error: Something bad happened
    at Object.<anonymous> (/Users/Admin/test.js:3:9)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:456:3
```

And I guess it also worth to mention that sometimes the output from arangod doesn't replace `\n` chars with line breaks so the output is very hard to read, which is very annoying http://take.ms/juxdF

**Comment by jsteemann** [comment]
I agree the message could be more informative. Here's what my nodejs logs:
```
> console.log(new Error('Something bad happened'))
[Error: Something bad happened]
undefined
```
It seems it only prints the stack trace when an exception is thrown, but not for each call to console.log.
Here's a patch to make arangod output the error messages too:
```diff
diff --git a/js/common/bootstrap/modules/console.js b/js/common/bootstrap/modules/console.js
index 5ea45bc..01e21fc 100644
--- a/js/common/bootstrap/modules/console.js
+++ b/js/common/bootstrap/modules/console.js
@@ -98,6 +98,8 @@ global.DEFINE_MODULE('console', (function () {
       if (typeof arg === 'object') {
         if (arg === null) {
           arg = 'null';
+        } else if (arg instanceof Error) {
+          arg = String(arg);
         } else if (arg instanceof Date || arg instanceof RegExp) {
           arg = String(arg);
         } else if (Object.prototype.isPrototypeOf(arg) || Array.isArray(arg)) {
```

**Comment by jsteemann** [comment]
@pluma @fceller: should we apply that patch?

**Comment by jsteemann** [comment]
Regarding `\n` and other special characters in log messages: 
these are indeed escaped in ArangoDB. For example a newline becomes `\n` in the log output. nodejs behaves differently as it will print a newline character and not `\n`. 
@pluma @fceller : should we change that.

**Comment by fceller** [comment]
@jsteemann fine with me

**Comment by jsteemann** [comment]
`Error` objects are now printed printed properly when used in console.log:
```
arangod> console.log(new Error('Something bad happened'))
arangod> 2016-07-18T09:05:14Z [11042] INFO Error: Something bad happened
```

**Comment by jsteemann** [comment]
The above modification has been made in the 3.0 and devel branches, and will become available in 3.0.4

**Comment by jsteemann** [comment]
Re newlines: in order to have newlines being logged as newline characters and not as `\n`, the following modifications are required:
* (potentially) adjust error logging in Foxx so it does not split the stack trace into multiple lines and log them separately. Instead it should log just a single error message per error, which may contain newline characters
* make escaping of `\n`, `\r` and `\t` in log messages configurable. If the configuration is set to have these characters escaped, then they will be logged as they are now. If the configuration is set to log literal control characters, then this would mean log messages would contain literal newline, carriage return and tab characters. There could also be an option to completely remove these characters from the log output, which may be useful for syslog and other targets.

**Comment by ilearnio** [comment]
@jsteemann Sounds good. As for logging stack traces separately​ I think the option to keep them in the same (main) output might be handy when constantly developing and monitoring errors in terminal

**Comment by dothebart** [comment]
Meanwhile 3.0.4 was released, so I will close this now.

**Comment by fceller** [comment]
Does the commit really address the proposal of @jsteemann?

**Comment by dothebart** [comment]
Stack traces in log files are logged with `\n` in them. Closing as solved.
