### ISSUE TITLE
Feature: case insensitive hash index

### ISSUE THREAD

**Issue by miguel-porto** [arangodb/arangodb#1945]
I think it would be very useful to have an hash index indexing the lowercase version of the given field, then it would be trivial to conduct case insensitive filtering using the index.
Because sometimes we don't need the power of FULLTEXT that comes at a cost, we just want to perform a fast equality comparison that is case-insensitive (without having to create a new field with the lowercase version and index it)
I guess this would involve creating also a new equality comparison operator.
Cheers!

**Comment by dothebart** [comment]
Hi, 
I guess one would to this via a function based index as sugested here: https://github.com/arangodb/arangodb/issues/1501 therefore I'd like to close this as a duplicate.

**Comment by miguel-porto** [comment]
That would be the perfect solution, a function based index! Sorry for not have found it before "issuing".
Best.

**Comment by dothebart** [comment]
You're welcome ;-)
