### ISSUE TITLE
Error: 1210 - unique constraint violated - in index primary of type primary over '_key'

### ISSUE THREAD

**Issue by Nahuel92** [arangodb/arangodb#19460]
## My Environment

* __ArangoDB Version__:        3.9.1 (arangodb/arangodb:3.9.1)
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   Kubernetes
* __Configuration__:               One pod per node, operator version 1.2.24. 3 DB severs, 3 coordinators, 3 agents
* __Infrastructure__:               AWS (r5.large, 2 vCPU)
* __Operating System__:        Linux
* __Total RAM in your machine__:       16 GB (per node)
* __Disks in use__:        EBS Volume (100 GiB per node)
* __Used Package__:              Unknown

## Component, Query & Data

__Affected feature__:
Primary `_key` index generation.

__AQL query (if applicable)__:
N/A

__AQL explain and/or profile (if applicable)__:
N/A

__Dataset__:
N/A

__Size of your Dataset on disk__:
N/A

__Replication Factor & Number of Shards (Cluster only)__:
N/A

## Steps to reproduce

I don't think this is easily reproducible as I tried on my local environment (my laptop) without any success. Keep in mind that we have a cluster configuration (which I couldn't replicate on my local env.). Anyway, the steps are:

1. Create a collection.
2. Start putting lots of data into it.
3. At some point, data insertion should start failing with provided error message regarding unique constraint violated `_key`. Perhaps internal metadata got corrupted, but not sure how to replicate that.

__Problem__:
Hi, the following is a question, that may be related to #19185 (feel free to remove this if my issue report is invalid).

The DB we have on our company has a `tx` collection for auding purposes and an `edge` collection where we store edges.
In Prod, when we attempt to post data to any of those collections, we receive:

`Error: 1210 - unique constraint violated - in index primary of type primary over '_key'; conflicting key: 333128067"}]}'`

It used to happen sparingly, but now it became an incident due to the increased frequency of occurrence.
When the error manifest itself and we run the following AQL query with the reported `_key` id, we can see existing documents from the past (last year, for instance) using the same `_key` being returned as part of the error message (which, in my opinion, shows that ArangoDB is messing up with unique index generation):

```aql
FOR t IN tx
    FILTER t._key == '333128067'
RETURN t
```

I believe a corrupted `_key` index (or index generator) is the culprit as a huge amount of data is regularly inserted in both tables.

Considering this is happening in Prod, I would like to know if there is a way to repair the index without having to backup data, delete affected collections and import backed up data (which will recreate collections with healthy `_key` index).

If it helps:
- It might be possible that this issue was happening before the company switched to a cluster setup. I wasn't involved back then so I'm not sure.
- We use the Java driver (v6).

Please let me know if more information is needed, I'll do my best to add it (though I can't provide a dataset because it's sensitive data).
Thanks.

__Expected result__:

It would be great if ArangoDB offered a mechanism to repair corrupted/broken `_key` index.

**Comment by dothebart** [comment]
Hi, 
please note that ArangoDB 3.9.11 is available for download. 
Please upgrade and tell whether the issue persists.

**Comment by Nahuel92** [comment]
> Hi, please note that ArangoDB 3.9.11 is available for download. Please upgrade and tell whether the issue persists.

Hi,
We will give it a try during the week and I will let you know.
Hopefully this will fix our issue, I will keep you posted.

**Comment by Nahuel92** [comment]
Upgrading to 3.10.8 seems to have fixed the issue.
