### ISSUE TITLE
ArangoDB 3.03 crash. Ubuntu 14.04

### ISSUE THREAD

**Issue by kikohs** [arangodb/arangodb#1948]
Hi,
Honestly I am a bit scared of my choice of arangodb right now. It is the second time I started a job that led to a database crash during the night. 
I have only one machine with a very few requests per seconds and only create or update operations. I don't use Foxx only pyArango so HTTP interface.

I do however maintain simultaneous connections to the database on multiple python processes and update a collection where I have open cursors iterating.
Instead of crashing right away, it took between 6 and 12 hours after the job was started so I cannot find a reason for it. 
The collection is only 30k documents.

The job is fairly simple: read a collection for objects, update each object last crawled timestamp and add in another collection the current value of the object at that particular timestamp.

One the side note, I tried an 'apt-get upgrade' and arangodb wants to update anyways even though I already have the latest version, then complains.

    Setting up arangodb3 (3.0.3) ...
    Upgrading database files.
    2016-07-19T09:37:11Z [18775] ERROR cannot open datafile '/var/lib/arangodb3/journals/logfile-5481572.db': 'Permission denied'
    2016-07-19T09:37:11Z [18775] ERROR unable to open logfile '/var/lib/arangodb3/journals/logfile-5481572.db': system error
    2016-07-19T09:37:11Z [18775] FATAL could not inspect WAL logfiles: system error
    dpkg: error processing package arangodb3 (--configure):
     subprocess installed post-installation script returned error exit status 1
    Errors were encountered while processing:
     arangodb3
    E: Sub-process /usr/bin/dpkg returned an error code (1)

I join all the files that I can via dropbox because of the size. Notably a file created after the crash and another after dpkg failed.

[Files here](https://dl.dropboxusercontent.com/u/15586459/arangodb.zip)

**Comment by dothebart** [comment]
since your error message is 'Permission denied' does

    chown -R arangodb:arangodb /var/lib/arangodb3

fix the issue?
Or, if maybe your filesystem is mounted read only? You can check by typing:

    mount
    ....
    /dev/sda3 on /var type ext4 (rw,relatime,data=ordered)
   ...

`rw` means `Read Write`, `ro` means `Read Only`

**Comment by kikohs** [comment]
@dothebart I did `sudo apt-get upgrade`. But changing the permission seemed to do the trick. I still have to start `arangod` with sudo otherwise it doesn't start even though the user and group is arangodb.


    kikohs@ubuntu-ele227:/var/lib » cd arangodb3
    kikohs@ubuntu-ele227:/var/lib/arangodb3 » ls
    databases  journals  rocksdb  SERVER  SHUTDOWN
    kikohs@ubuntu-ele227:/var/lib/arangodb3 » ll
    total 20K
    drwxr-xr-x 7 arangodb arangodb 4.0K Jul 15 14:16 databases
    drwxr-xr-x 2 arangodb arangodb 4.0K Jul 19 13:22 journals
    drwxr-xr-x 2 arangodb arangodb 4.0K Jul 19 13:22 rocksdb
    -rwxr-xr-x 1 arangodb arangodb   68 Jul  4 11:41 SERVER
    -rwxr-xr-x 1 arangodb arangodb  109 Jul 19 13:23 SHUTDOWN
    kikohs@ubuntu-ele227:/var/lib/arangodb3 » cd journals
    kikohs@ubuntu-ele227:/var/lib/arangodb3/journals » ll
    total 416M
    -rwxr-xr-x 1 arangodb arangodb 32M Jul 19 11:05 logfile-10809107.db
    -rwxr-xr-x 1 arangodb arangodb 32M Jul 19 11:14 logfile-10812319.db
    -rwxr-xr-x 1 arangodb arangodb 32M Jul 19 11:17 logfile-10812942.db
    -rwxr-xr-x 1 arangodb arangodb 32M Jul 19 13:19 logfile-10813155.db
    -rwxr-xr-x 1 arangodb arangodb 32M Jul 19 13:20 logfile-10822509.db
    -rwxr-xr-x 1 arangodb arangodb 32M Jul 19 13:20 logfile-10822611.db
    -rwxr-xr-x 1 arangodb arangodb 32M Jul 19 13:21 logfile-10822709.db
    -rwxr-xr-x 1 arangodb arangodb 32M Jul 19 13:23 logfile-10822877.db
    -rwxr-xr-x 1 arangodb arangodb 32M Jul 19 13:22 logfile-10822878.db
    -rwxr-xr-x 1 arangodb arangodb 32M Jul 19 13:22 logfile-10822879.db
    -rwxr-xr-x 1 arangodb arangodb 32M Jul 18 19:49 logfile-8225820.db
    -rwxr-xr-x 1 arangodb arangodb 32M Jul 18 21:28 logfile-9149100.db
    -rwxr-xr-x 1 arangodb arangodb 32M Jul 18 21:30 logfile-9772986.db
    kikohs@ubuntu-ele227:/var/lib/arangodb3/journals » arangod
    2016-07-19T11:26:43Z [20557] INFO using SSL options: SSL_OP_CIPHER_SERVER_PREFERENCE, SSL_OP_TLS_ROLLBACK_BUG
    2016-07-19T11:26:43Z [20557] INFO file-descriptors (nofiles) hard limit is 4096, soft limit is 1024
    2016-07-19T11:26:43Z [20557] ERROR cannot open datafile '/var/lib/arangodb3/journals/logfile-8225820.db': 'Permission denied'
    2016-07-19T11:26:43Z [20557] ERROR unable to open logfile '/var/lib/arangodb3/journals/logfile-8225820.db': system error
    2016-07-19T11:26:43Z [20557] FATAL could not inspect WAL logfiles: system error
    kikohs@ubuntu-ele227:/var/lib/arangodb3/journals »

Anyways, this is a side issue? My main issue is the database crash without any apparent reason.

**Comment by dothebart** [comment]
To start the service you need root permissions:

    sudo service arangodb3 start

The ArangoDB daemon itself is then in term responsible to drop root permissions during its startup phase.

In linux you need to be privileged (= be root) in order to bind lower ports (> 1024). Though ArangoDB binds port 8529 by default, its able to do all this if users want to bind privileged ports.

If you run arangod as root without the proper parameters, it won't drop root privileges, and thus create new files with `root:root` permissions.

It would be interesting to understand which circumstances lead to the state of the permission problems.

Did you start `arangod` by hand as described above?

**Comment by kikohs** [comment]
Yes, I did.

I used to run arangodb either by the service or by hand with: `sudo arangod`. Maybe because of this root user, when the database grows it creates new journal files with the wrong permissions. Then when they are accessed it makes the database crash?

Have you been able to read the log files I joined in my first post?

**Comment by dothebart** [comment]
Its not a crash. It simply panics during startup because of it can't access all of its required resources.

Which is like your boss calling you to come to work urgently, and you find yourselves in front of your car, and forgot your keys inside your home.

If you call it like `sudo -u arangodb /usr/sbin/arangod` you shouldn't see these issues.

**Comment by kikohs** [comment]
I am not sure we understand each other here. The whole startup thing and apt-upgrade was a side issue maybe related to the real issue:

Arangodb crashed unexpectedly after 6 hours of work.

Quoting my original post:

> It is the second time I started a job that led to a database crash during the night. 
I have only one machine with a very few requests per seconds and only create or update operations. I don't use Foxx only pyArango so HTTP interface.

> I do however maintain simultaneous connections to the database on multiple python processes and update a collection where I have open cursors iterating.
Instead of crashing right away, it took between 6 and 12 hours after the job was started so I cannot find a reason for it.  The collection is only 30k documents.

> The job is fairly simple: read a collection for objects, update each object last crawled timestamp and add in another collection the current value of the object at that particular timestamp.

**Comment by dothebart** [comment]
Ok, I thought the log lines were related.

I've been looking at pyArango the last days; It seems to not re-use connections (at least in current devel) 
If you run

     netstat -alpnt | grep CLOSE_WAIT

Do you see many lines with your python client?

**Comment by kikohs** [comment]
My code is running on the same machine.
Only two lines:

    # Ipython notebook with port forwarding
    tcp        0      0 xxx.xxx.xxx.86:8889     xxx.xxx.xxx.2:51959     CLOSE_WAIT  20887/python 
    # arangodb web interface port forwarding 
    tcp        1      0 127.0.0.1:53675         127.0.0.1:8529          CLOSE_WAIT  20887/python

**Comment by dothebart** [comment]
ok, so at least ATM this doesn't happen to you. Can you share the AQL you're running on your database?

**Comment by kikohs** [comment]
All the requests are contained in [one file here](https://dl.dropboxusercontent.com/u/15586459/db.py)

Mainly I have multiple processes running the query l. 392 and 396

    'FOR p in col_name FILTER (p.last_scraped < 'timestamp' AND p.priority > 0) SORT p.last_scraped ASC, p.pirority DESC RETURN p'

While iterating through the results I call `add_full_video` l.364 and `add_full_playlist` l. 345 that are basic CREATE or UPDATE operations.

These functions update the database if necessary and add the timeseries value is a dedicated collection.

Tell me if you need more precision.

**Comment by kikohs** [comment]
Update: I started a the same job yesterday, the DB crashed again during the night.

**Comment by dothebart** [comment]
Hm, the corefile only contains bogus information. I will try to reproduce this.

**Comment by dothebart** [comment]
can you share a sample data set so the queries run properly?

**Comment by kikohs** [comment]
@dothebart I found the issue. My code was leaking and the machine was out of memory during the night enhance making the system crash. Maybe it would be nice to log this case as it may happen to others in the future. Thanks for the support.

**Comment by KromDaniel** [comment]
The answer 

> Its not a crash. It simply panics during startup because of it can't access all of its required resources.
> 
> Which is like your boss calling you to come to work urgently, and you find yourselves in front of your car, and forgot your keys inside your home.
> 
> If you call it like sudo -u arangodb /usr/sbin/arangod you shouldn't see these issues.

Should be much more documented, I spent more than 24 hours when I tried to tell arangodb to create database on mounted directory, it always created it as a root and then arangodb user didn't have permissions to write to that database directory.  if I didn't start arangodb as root it crashed on no permissions to change uid\gid

anyway `sudo -u arangodb` after mounting with permissions does the job
