### ISSUE TITLE
Strange behavior _id and _key

### ISSUE THREAD

**Issue by overpod** [arangodb/arangodb#1949]
**I make this request here.**
`INSERT      {
      "country_id": 156,
      "sid": 100097,
      "type_id": 2,
      "balance_text": "xxxx",
      "box_qty": 100,
      "box_type": "xxxx",
      "box_size_text": false,
      "discount_percent": 26,
      "has_choice": true,
      "is_price_fixed": 0,
      "in_set_qty": 0,
      "k_min": false,
      "keep_package": 0,
      "materials": "xxx",
      "materials_text": "xx",
      "min_qty": 2,
      "name": "xxx",
      "old_price": 168.84,
      "photo_count": 1,
      "prepacking_qty": 0,
      "price": 125,
      "price_unit": 125,
      "qty_rule": "мин.",
      "size_text": "xxxx",
      "trademark_id": null,
      "unit": "шт",
      "weight": 56,
      "new_at": null,
      "is_loco": 0,
      "is_paid_delivery": 0,
      "gift_id": null,
      "flv_url": null,
      "surface_area": null,
      "price_per_square_meter": null,
      "transport_condition_id": null,
      "exclusive_type": null,
      "new_type_id": 0,
      "has_discount": 1,
      "is_exclusive": 0,
      "is_hit": 0,
      "is_imprintable": null,
      "has_teapot": null,
      "has_body_drawing": null,
      "has_cord_case": null,
      "has_termostat": null,
      "has_highlight": null,
      "volume": "0.360",
      "power": null,
      "color_id": null,
      "page_count": null,
      "category_main_id": 545,
      "category_id": [
        545,
        700000452,
        700001319
      ],
      "photo": {
        "base_url": "xxxxxx",
        "indexes": [
          "0"
        ]
      }
    }
  INTO shipper_item`
**The document is created without an _id and _key**

Help me please ;-(

**Comment by overpod** [comment]
Arangodb v3 docker. There is an error !!!
Arangodb v2.8.11 docker. **No error**

**Comment by dothebart** [comment]
what do you use to query your document?
I've tried to do this in arangosh: 

     db._query(`INSERT { "country_id": 156,....`)

and...

     db.shipper_item.toArray()
    [ 
      { 
        "_key" : "2259836", 
        "_id" : "shipper_item/2259836", 
       "_rev" : "_TeaxpiW---", 
       "balance_text" : "xxxx", 
       "box_qty" : 100, 
       ....

same for

    db._query('FOR x IN shipper_item RETURN x').toArray()

**Comment by jsteemann** [comment]
This seems to be a web interface issue. The documents created via the `INSERT` AQL above are not selectable in the collection's documents view in the web interface. Though they exist with regular `_key` and `_id` attributes, but the web interface doesn't seem to query these attributes.

**Comment by jsteemann** [comment]
Fixed. The web interface will now always select the `_key` attribute for a document, as this is required for working with the document in the web interface. The documents already created are regular documents with `_id` and `_key`, but before the fix is applied, they may not be clickable/selectable from the web interface.

**Comment by jsteemann** [comment]
Fix will become available in 3.0.4

**Comment by overpod** [comment]
Ништяк !!!
I love arangodb !!!

**Comment by jsteemann** [comment]
извините, я плохо говорю по русски :smile:
