### ISSUE TITLE
Transaction commit failed "Parsing for transfer-encoding of type chunked not implemented"

### ISSUE THREAD

**Issue by osddeitf** [arangodb/arangodb#19520]
## My Environment

* __ArangoDB Version__: v3.11.2       
* __Deployment Mode__: Single Server      
* __Deployment Strategy__: Manual Start in Docker  
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__: Debian 11.7 Arm64       
* __Total RAM in your machine__: 4Gb       
* __Disks in use__: SSD       
* __Used Package__: Docker official             

## Component, Query & Data

__Affected feature__: Transaction

__AQL query (if applicable)__:
```


```
__AQL explain and/or profile (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. make new transaction
```javascript
const trx = await mydb.beginTransaction([
    vertexes.accounts
  ])
```
2. Run multiple queries
```javascript
await trx.step(() => vertexes.accounts.documentExists(payload.accountId))
```
3. Commit
```javascript
const status = await trx.commit()
```
__Problem__: Server response with strange error:
```json
{
    "error": true,
    "errorNum": 9,
    "errorMessage": "Parsing for transfer-encoding of type chunked not implemented.",
    "code": 501
}
```
If run `abort()` instead of `commit()`, no error occurs.
I tried with v3.10.4 and the response was:
```json
{
    "error": true,
    "errorNum": 10,
    "errorMessage": "decoding error",
    "code": 400
}
```
I used the latest `arangojs` driver (v8.4.0).
__Expected result__:

**Comment by dothebart** [comment]
Hi, 
do you connect to ArangoDB via a proxy?
ArangoDB doesn't support `content transfer encoding: chunked` for performance reasons. 
ArangoJS itself should know that and not send it.

**Comment by jsteemann** [comment]
The error
> Parsing for transfer-encoding of type chunked not implemented
will be returned by the server when it receives an HTTP request containing a `Transfer-Encoding` header with the phrase `chunked` inside. Chunked encoding is not supported by ArangoDB.
So I guess that the client application uses `Transfer-Encoding: chunked` somehow when it sends requests to the server, or that a proxy is in between that adds this header.

**Comment by osddeitf** [comment]
Apparently it was an issue in Deno, so I'll close it here.
