### ISSUE TITLE
Unexpected result with COLLECT and constant expression

### ISSUE THREAD

**Issue by dustbort** [arangodb/arangodb#1953]
I'm using the latest ArangoDB of the respective release series: 3.0.3
On this operating system: Ubuntu .deb
I'm issuing AQL via:
- web interface with this browser: FireFox 47.0    running on this OS: Ubuntu 16.04
- cursor HTTP API

The AQL query in question is:

```
for p1 in _statistics
collect t = floor(p1.time / 300) aggregate max_time = max(p1.time)
for p2 in _statistics
filter max_time == p2.time
collect q = 0 into qs = p2
return {q, qs}
```
The following problem occurs: The result contains two elements:
```
[{
        "q": 0,
        "qs": [...]
    }, {
        "q": "(non-representable type)",
        "qs": [...]
}]
```

Instead I would be expecting: A result with only one element:
```
[{
        "q": 0,
        "qs": [...]
}]
```

If I use `collect q = null`, I get the expected result of one element with `"q": null`. It seems that any non-null constant expression `@expr` in `collect q = @expr` results in two elements, one with `"q": "(non-representable type)"` .

**Comment by jsteemann** [comment]
Reproduced in 3.0 branch via the HTTP API interface.

**Comment by jsteemann** [comment]
Fixed in 3.0.4

**Comment by dustbort** [comment]
Thanks! Looking forward to the next release :smile:

**Comment by jsteemann** [comment]
3.0.4 released today.
