### ISSUE TITLE
Conducted on arangodb secondary development

### ISSUE THREAD

**Issue by AthonyLi** [arangodb/arangodb#1956]
hello，I‘ll want to ask you again .Hee hee

@dothebart   @all
## Conducted on arangodb secondary development, Compiling Question
ArangoDB version :    2.8
On this operating system:   CentOS
IDE : Eclipse for c/c++ ，Use the ready-made makefile to compile

###Question:

I prepared under CentOS system arangodb source for secondary development, need to add a new file (there are interdependent relationship), then I should how to rewrite its `Makefile `or change other 【such as `MakeLists.txt` or `Makefile. am` 】 to regenerate the `Makefile`?

**Comment by jsteemann** [comment]
I can't recommend editing the `Makefile` by hand, as it is a generated file.
If you want to add a new C/C++ file to the build, it should be added in either `arangod/Makefile.files`, `arangosh/Makefile.files`, or `lib/Makefile.files` - depending on whether it belongs into the server, the client tools or if it is a shared component.
The `Makefile` should then be re-generated from these files, but only if you configured ArangoDB 2.8 with the `--enable-maintainer-mode` option. Note that if you enable this option for `configure` you will also need to install GNU bison, flex and probably some other utilities.

All this has got a lot easier with ArangoDB 3.0, where adding a new file to the build simply means adding the filename to the `CMakeLists.txt` file in the respective directory and rebuilding.

**Comment by AthonyLi** [comment]
@jsteemann   
`# -*- mode: Makefile; -*-

## -----------------------------------------------------------------------------
## --SECTION--                                                           LIBRARY
## -----------------------------------------------------------------------------

################################################################################
### @brief library "libarangod.a"
###############################################################################
arangod_libarangod_a_CPPFLAGS = \
        -I@top_srcdir@/arangod \
        $(AM_CPPFLAGS)

arangod_libarangod_a_SOURCES = \
        arangod/Actions/test.h \  
        arangod/Actions/actions.cpp \
        arangod/Actions/RestActionHandler.cpp \
        arangod/ApplicationServer/ApplicationFeature.cpp \


Well, I am`/arangod/Actions/directory` added two new files `test.h` `test.cpp`, then modify the `Makefile. files` files, the above is my `arangod/Makefile. files` files, I want to ask is to modify the here, I'm going to do next step (to generate new `Makefile`)?To let arangodb between the test and can call each other

@jsteemann

**Comment by AthonyLi** [comment]
@jsteemann 
`re-configure `with `--enable-maintainer-mode` to re-generate the new `Makefile` ?

**Comment by dothebart** [comment]
The recommended way would be to go with ArangoDB 3.0 which uses cmake and which should be a lot easier to get compiling.

**Comment by jsteemann** [comment]
My recommendation for 2.8 is to modify `arangod/Makefile.files` and add the entry for `arangod/Actions/directory/test.cpp` to it:
```
diff --git a/arangod/Makefile.files b/arangod/Makefile.files
index f26607b..e0bf970 100644
--- a/arangod/Makefile.files
+++ b/arangod/Makefile.files
@@ -14,6 +14,7 @@ arangod_libarangod_a_CPPFLAGS = \
 
 arangod_libarangod_a_SOURCES = \
        arangod/Actions/actions.cpp \
+       arangod/Actions/Directory/test.cpp \
        arangod/Actions/RestActionHandler.cpp \
        arangod/ApplicationServer/ApplicationFeature.cpp \
        arangod/ApplicationServer/ApplicationServer.cpp \
```
That should be it. If you run `make` again, it should compile test.cpp and rebuild arangod. However, this will only work if you have configured with `--enable-maintainer-mode`. Re-running `configure` with `--enable-maintainer-mode` should generate the new `Makefile`, which should include the instructions to build `test.cpp`.
I won't recommend editing the `Makefile` manually as it is a generated file. If you make any modifications to it, your changes may be lost.

As @dothebart pointed out, using 3.0 will be a lot easier because of our switch to cmake in that version. No need to re-configure there, just editing the appropriate `CMakeLists.txt` file and making.

**Comment by AthonyLi** [comment]
@jsteemann 
Jah、I do as your way, and now is waiting for the make, wish can pass, so it was a wonderful today, ha ha!
Well, now being in the process of learning, a first-time arangodb, just in the official website to see  the `--enable-maintainer-mode`, the detailed introduction of the `configure` options hasn't been noticed before, suddenly found himself really careless ah.Then will go to study `arangdb  3.0`,`CMakeLists.txt` change easily?(  @dothebart ), thank you for your help. @jsteemann @dothebart

**Comment by jsteemann** [comment]
Info on compiling and `--enable-maintainer-mode` can be found in the [2.8 docs](https://docs.arangodb.com/2.8/Installing/Compiling.html).
Note that the 2.8 build process is completely different to the 3.0 build process. We have switched from configure/make to cmake.
This has made development a lot easier for ourselves, and should also make it easier for others (e.g. you). I therefore definitely recommend moving to 3.0 soon if you plan on making modifications to ArangoDB.

**Comment by AthonyLi** [comment]
Compiled over, had an error, but the feeling with the `test.cpp` has nothing to do；

```
more undefined references to `boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, unsigned long)' follow
collect2:error ld return 1
```

**Comment by jsteemann** [comment]
That's because of the maintainer mode. It requires installing the Boost test framework.

**Comment by AthonyLi** [comment]
installing the Boost test framework.? The framework how to install?Specific how should do I install the boost library

**Comment by jsteemann** [comment]
Yes, the Boost test framework is required for the maintainer mode, as mentioned in the [2.8 compile instructions](https://docs.arangodb.com/2.8/Installing/Compiling.html).

The package manager for your platform should have the packages for Boost unittest ready to install.
For example, on Ubuntu something like `sudo apt-get install libboost-test-dev` will install it. It will differ for other systems, but it shouldn't be hard to find out with a bit of Googling and/or trial and error.

**Comment by AthonyLi** [comment]
ok 、it's resolve,the problem is my boost library don't install correct. Thank you

**Comment by Simran-B** [comment]
Closing as problem is apparently resolved. @AthonyLi: If you still have trouble, feel free to re-open this issue.

**Comment by AthonyLi** [comment]
Hey, to trouble you again, I've built a new project, and it's contains arangodb's  `.h` file, these files appear a lot of errors when I compile this new project, such as data type error, etc., this is going on here? @jsteemann     @dothebart

**Comment by dothebart** [comment]
sorry, tried to have a look at your monitor, but my neck isn't long enough?

**Comment by jsteemann** [comment]
@AthonyLi : it's impossible to tell what's going on because we don't know the contents of your files. Please post them here plus the error messages you're getting when compiling.

**Comment by AthonyLi** [comment]
Uh,I'm sorry ;I'll instructions my case ,I have two project,the one is arangodb source,another is a new project(it's my self-build),and include some files of arangodb to the new project; A lot of ERROR appeared when I compiling the new project;  this is my compiler error 
`/usr/local/include/c++/4.9.2/atomic:446:51: error expected initializer before 'noexcept'
atomic_fetch_and(volatile __atomic_base<_ITp>* __a, _ITp __i) noexcept
/home/hewei/workspace/arangodb5/lib/Basics/debugging.h:167:20 error ISO C++ not allowed declare nontype 'it' [ -fpermissive]
for (auto const& it : data) {
/home/hewei/workspace/arangodb5/lib/Basics/debugging.h:167:25 error range-based 'for' loops are not allowed in C++98 mode
for (auto const& it : data) {
.....`

**Comment by jsteemann** [comment]
You are compiling your code in C++98 mode. The ArangoDB code requires C++11. Please use `-std=c++11` or something alike in your build instructions.

**Comment by elgatoblanco** [comment]
I don't understand. I'm only taxi driver.

**Comment by AthonyLi** [comment]
I use `Eclipse for c/c++` IDE to development; The ArangoDB code sigle compile is ok, where am I put the `-std = c++11` ? makefile? I'm only used `gcc xx.cpp -std=c++11`. I'm so wonder why to use `C++98`?

**Comment by jsteemann** [comment]
You will need to use g++, not gcc. I have no idea of Eclipse and where to put build instructions so it will honor them.

**Comment by AthonyLi** [comment]
er. I use `g++ test.cpp -std=c++11`,the `test.cpp` include `Basics/Thread.h` file(it's belong to ArangoDB)，
thier have error-Info: `arangodb/lib/Basics/Thread.h: cannot find the Basics/Common.h`,the question produced at there,The ArangoDB was compiled success,there should not error,but there have;

**Comment by jsteemann** [comment]
If you include code from ArangoDB in your own cpp files, you need to set the include paths to the ArangoDB source directories. Otherwise your compiler won't find `Basics/Thread.h` and complain.
It's likely something like `-Ilib`, but please check with your compiler documentation.

**Comment by AthonyLi** [comment]
oh、the problem was resloved, I misunderstand the compiling progress; I add  `-std = c++11` to the  eclipse project's variable ,and compiling success. Thank you help. mua
