### ISSUE TITLE
`res.json(err)` outputs empty Error objects

### ISSUE THREAD

**Issue by ilearnio** [arangodb/arangodb#1957]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.0.3

On this operating system:
- [x] MacOS, version: El Captain 10.11.5

The issue can be reproduced using this dataset:

```js
const router = require('@arangodb/foxx/router')()

router.post('/test', (req, res) => {
    res.json(new Error('Something'))
})
.body(['text/plain'])

module.context.use(router)
```

Then do

```bash
$ curl -i -X POST http://127.0.0.1:8529/_db/{DB}/{APP}/test
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Server: ArangoDB
Connection: Keep-Alive
Content-Length: 2

{}%
```

**Comment by pluma** [comment]
This isn't a bug. Error objects are not JSON serializable (try logging the error with `JSON.stringify` and you'll see that it also prints an emtpy object).

If you want to send an error response the best way is to wrap it in an HTTP error response via `res.throw`:

```js
res.throw(500, new Error('Something'));
```

**Comment by ilearnio** [comment]
Oh, you're right. I'll try to use `res.throw`. Thanks!
