### ISSUE TITLE
ArangoDB doesn't support exclude fields vertex when return with GRAPH

### ISSUE THREAD

**Issue by son2408** [arangodb/arangodb#19587]
## My Environment

* __ArangoDB Version__:        3.11.2
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Infrastructure__:               own
* __Operating System__:        Ubuntu 20.04
* __Total RAM in your machine__:        32Gb
* __Disks in use__:        SSD 
* __Used Package__:    Ubuntu .deb

## Component, Query & Data

__Affected feature__:
AQL query using web interface

__AQL query (if applicable)__:
```
FOR i IN search_HCMLIS
        SEARCH i.Layer == 'diachi' AND i.diaChiId == 26866
        FOR n IN (for v,e in 0..1 OUTBOUND i edge_diachi_canhan,edge_diachi_thuadat RETURN v)
            FOR v2,e2 IN 0..1 INBOUND n edge_dangkyquyen_thuadat RETURN DISTINCT v2 
```
__Problem__:
I have 3 collections with property.

DIACHI
    "Description", "InId", "OutId", "Title", "diaChiChiTiet", "diaChiId", "duongId", "huyenId", "itemId", "laDiaChiChinh", "laDiaChiCu", "ngoPho", "soNha", "tinhId", "toDanPhoId", "typeItem", "versionItem", "xaId"
CANHAN
    "Description", "InId", "OutId", "Title", "caNhanId", "danTocId", "diaChi", "diaChiEmail", "donViChinhSua", "gioiTinh", "hoTen", "isLastest", "loaiDoiTuongId", "maSoDinhDanh", "maSoThue", "namMat", "namSinh", "ngaySinh", "quocTichId1", "quocTichId2", "soDienThoai", "version", "xaId"
THUADAT
    "Description", "InId", "OutId", "Title", "diaChi", "dienTich", "dienTichPhapLy", "duongDanSoDo", "historyId", "huyenId", "inSoLieuCu", "isLastest", "laDoiTuongChiemDat", "loaiThuaDat", "maThua", "mucDichSuDungGhep", "ngayChinhSua", "nguonGocSuDungGhep", "quaTrinhSuDung", "shape", "soHieuToBanDo", "soHieuToBanDoCu", "soHieuToBanDoGoc", "soThuTuThua", "soThuTuThuaCu", "taiLieuDoDacId", "tenFileSoDo", "thoiDiemHinhThanh", "thuaDatId", "tinhId", "version", "xaId"

I want exclude filed diaChiChiTiet of collection DIACHI from RETURN v2. If I return {Description:v2.diaChiId, InId:v2.InId,...}, it's very long and unreasonable because other collections doesn't contain this field but still return NULL

__Expected result__:
Result's DIACHI in v2 exclude field diaChiChiTiet

**Comment by mchacki** [comment]
Hi @son2408 

would the https://www.arangodb.com/docs/stable/aql/functions-document.html#unset method help?
This will keep all documents intact, and only erase the given list of fields.

So your query should look like this:

`FOR i IN search_HCMLIS
        SEARCH i.Layer == 'diachi' AND i.diaChiId == 26866
        FOR n IN (for v,e in 0..1 OUTBOUND i edge_diachi_canhan,edge_diachi_thuadat RETURN v)
            FOR v2,e2 IN 0..1 INBOUND n edge_dangkyquyen_thuadat RETURN DISTINCT UNSET(v2, "diaChiChiTiet")`
            
            You can also add more fields to the UNSET call if that should be required later.

**Comment by son2408** [comment]
> Hi @son2408
> 
> would the https://www.arangodb.com/docs/stable/aql/functions-document.html#unset method help? This will keep all documents intact, and only erase the given list of fields.
> 
> So your query should look like this:
> 
> `FOR i IN search_HCMLIS SEARCH i.Layer == 'diachi' AND i.diaChiId == 26866 FOR n IN (for v,e in 0..1 OUTBOUND i edge_diachi_canhan,edge_diachi_thuadat RETURN v) FOR v2,e2 IN 0..1 INBOUND n edge_dangkyquyen_thuadat RETURN DISTINCT UNSET(v2, "diaChiChiTiet")`
> 
> ```
>         You can also add more fields to the UNSET call if that should be required later.
> ```

It works. Thanks you so much
