### ISSUE TITLE
friends of friend Query in ArangoDB 3.0

### ISSUE THREAD

**Issue by namnik** [arangodb/arangodb#1969]
I want to writing 'friends of friend' traversal using **AQL**

I have a Collection with Name:**User** and a **edge** Collection with name **Conatct**.

contents of **Conatct** :

![3](https://cloud.githubusercontent.com/assets/13764362/17203174/0147c3ea-54b3-11e6-900a-65f5969caa8c.PNG)

I also read [this article](http://stackoverflow.com/questions/33279811/what-is-the-fastest-arangodb-friends-of-friends-query-with-count) that implement friends of friend in ArangoDb, but that's post Uses functions of lower version of ArangoDB that used GRAPH_NEIGHBORS() function.

in ArnagoDB 3.0(latest version), **GRAPH_NEIGHBORS()** function have been removed!

now, how can I implement fof using **Aql** in ArnagoDB 3.0 ?

thanks a lot

**Comment by namnik** [comment]
@jsteemann : why didn't answer my question?!

**Comment by jsteemann** [comment]
@namnik: maybe because I haven't been waiting for this question all day?

**Comment by Simran-B** [comment]
The graph functions have been remove in favor of native AQL traversal. Please refer to the documentation:
https://docs.arangodb.com/3.0/Manual/ReleaseNotes/UpgradingChanges30.html#graph-functions

**Comment by namnik** [comment]
@Simran-B  , @jsteemann :thanks guys... I found my response in [this link](http://stackoverflow.com/questions/38614564/friends-of-friend-query-in-arangodb-3-0/38641950#38641950)

**Comment by Simran-B** [comment]
@namnik: Yeah, I posted that answer over at SO, because others will benefit more on that site rather than a GitHub ticket I figured.
