### ISSUE TITLE
Question: wildcard substring search with orderless, tokenized user input 

### ISSUE THREAD

**Issue by MrCreosote** [arangodb/arangodb#19712]
I'm trying to figure out how to implement a use case where a user provides a string to be used for substring search that may contain multiple tokens and the order of those tokens does not matter. Something like this:

```
LET t = TOKENS("foo bar baz", "text_en")  // 1st arg is user input

FOR d IN my_view
    SEARCH ANALYZER(
        LIKE(d.turtle_species, CONCAT("%", SUBSTITUTE(t[0], ["_", "%"], ["\\_", "\\%"]), "%"))
        AND
        LIKE(d.turtle_species, CONCAT("%", SUBSTITUTE(t[1], ["_", "%"], ["\\_", "\\%"]), "%"))
        AND
        LIKE(d.turtle_species, CONCAT("%", SUBSTITUTE(t[2], ["_", "%"], ["\\_", "\\%"]), "%"))
        , "text_en"
    )
    RETURN d
```

Obviously this doesn't work because `t` may have an arbitrary number of tokens. I can't seem to figure out a way to make it work though. `PHRASE` with `WILDCARD` object tokens is really close except if forces a token ordering in the search which I don't want.

I considered tokenizing the user input server side and building a query like the above but 1) if I don't exactly match the db side tokenization algorithm I'll wind up with probably rare and difficult to debug search anomalies, and 2) if the db side analyzer changes same deal.

I've read through (I think) all the pertinent docs, searched Github issues, and asked ChatGPT (which continually cycled between variants of 2 wrong answers) but no dice.

Thanks for any pointers you can provide

**Comment by MBkkt** [comment]
Hello, why not something like
`search d.field in tokens`?

**Comment by MrCreosote** [comment]
That's won't work with substrings / wildcards, will it? Or am I misunderstanding something?

Regardless, thanks for taking the time to ansswer

**Comment by MBkkt** [comment]
No it doesn't. Because your tokens already should be "substrings".

In general idea behind fast text search, is that your search tokens known.
Ofc wildcard supported, but even single wildcard (not prefix/suffix), could degrade to almost full scan all indexed terms(tokens).

So commonly analyzed text already indexed on needed substrings.

If you need very granular substrings, try to look on ngram analyzer

**Comment by MBkkt** [comment]
I think if speed is not really important for you, regexp will be good option:
`regexp(d.field, ".*(token1|token2...).*"`
The problem it's not supported now :(
It's not difficult, but doesn't have priority now

**Comment by MrCreosote** [comment]
I guess I don't completely understand how the search indexes work. I assumed there was a token index that was much like the regular indexes and so could support prefix lookups and whole matches for tokens. From what you're saying, it sounds like there's a reversed index that can support suffix lookups as well (right...?).

When I read the `LIKE()` [documentation](https://www.arangodb.com/docs/stable/aql/functions-arangosearch.html#like), particularly

> Searching with the LIKE() function in the context of a SEARCH operation is backed by View indexes. 

I assumed that even non-prefix / suffix searches were backed by an index, which to me meant that arango had some sort of trie / suffix tree like data structure to support those types of searches. From what you're saying though, a search like

```
SEARCH ANALYZER(LIKE(d.field, "%foo%"), "text_en")
```
Will cause a table scan?

**Comment by MBkkt** [comment]
> I guess I don't completely understand how the search indexes work.

It's inverted index, simplified:
map<term, postings>, where 
map is prefix trie
postings is skiplist of uint32_t

> I assumed that even non-prefix / suffix searches were backed by an index, which to me meant that arango had some sort of trie / suffix tree like data structure to support those types of searches. 

Yes, it's, but I didn't write it's not, I wrote about it's slow and it's natural, because how it works.

As you wrote it's prefix trie (of indexed terms(tokens), it's simplification in practice it's fst of prefixes (it's also share suffixes, and more like fsa)):
Let's try to find something like `"%some%"`, in worst case we need to check all leafs, is it clear?
Or my explanation bad?

Opposite query like "some%" will be fast, because it's never need to look all leafs.

Query like "%some", could be fast if you're index reversed tokens (In general just making prefix from suffix)

Queries like "%some%" is backed by index, but they're at need to look almost everything in it.
it's still a lot of faster than just read documents from collection and do the same, but it's not really comparable with exact or prefix search.

And it's same for any fulltext indexes in the wild.

> Will cause a table scan?

No, but the point, it could be slow.

**Comment by MrCreosote** [comment]
Sorry, I confused myself and was using trie and [suffix tree](https://en.wikipedia.org/wiki/Suffix_tree) as synonyms when they're not. 

If arango had suffix trees (which, to my understanding it doesn't... right?) that would allow O(log n) lookups for any substring. So `%some% with a suffix tree would be just as fast as `some%` with a prefix tree or `%some` with a reversed tree. The drawback is that suffix trees can be quite a bit bigger as I understand it.

> No, but the point, it could be slow.

If I'm understanding you correctly, the slowness for a `%some%` lookup is because the lookup has to scan the entire index (rather than potentially load all documents from disk, which would be even worse), right?

P.S. Thanks very much for taking the time to answer my questions, it's much appreciated

**Comment by MBkkt** [comment]
> If arango had suffix trees (which, to my understanding it doesn't... right?) 

Yes, it doesn't.
In general you could have something similar with ngrams, as I mentioned.

> that would allow O(log n) lookups for any substring

Well any tree allow lookup any substring, btw O(length(sub string))
Now arangodb store prefixes automation in memory and suffix on disk.
It's not really possible with not prefix like structure.
The main difference is how many terms we stored, for suffix tree, it's not like you have prefix tree of all possible suffixes (that you kind of can do with arango too, ngrams).

> If I'm understanding you correctly, the slowness for a %some% lookup is because the lookup has to scan the entire index (rather than potentially load all documents from disk, which would be even worse), right

Very simplified yes, I don't think details important.
If you're just interested you could read the code :)
As I mentioned, we have fst of prefixes of terms, we match corresponding prefixes (in memory part), and for them read suffixes to match.

**Comment by MrCreosote** [comment]
> Well any tree allow lookup any substring

Sure, but in the case of a prefix tree you have to traverse most or all of the tree looking for substrings if the substring isn't a prefix unless I've completely misunderstood the discussion so far

> btw O(length(sub string))

Right, whoops

Ok, so back to the original question - is there a way to search for substrings (e.g. `%some%`) with `LIKE` in the case of an arbitrary number of unordered tokens? It seems like the closest I can get is an ordered search with `PHRASE`.

Alternatively, as you say, I could add an `n-gram` analyzer which would presumably increase the size of the view but would also likely perform better for large datasets since a full index / tree traversal isn't required, unlike `LIKE(d.field, "%some%")`

**Comment by MBkkt** [comment]
> Ok, so back to the original question - is there a way to search for substrings (e.g. %some%) with LIKE in the case of an arbitrary number of unordered tokens?

I don't think we have way to do it now, except generate a big disjunction/conjunction in aql (exist some internal limits on their size).

Alternatively regexp should work, but it needs to be  implemented :(

**Comment by MrCreosote** [comment]
Got it. Thanks again for the help
