### ISSUE TITLE
Question: When to delete the references in "_deadCollections" after deleting the collection

### ISSUE THREAD

**Issue by yaocg** [arangodb/arangodb#19739]
## My Environment

* __ArangoDB Version__:       3.7.6 
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   Manual Start in Docker 

## Component, Query & Data

__Replication Factor & Number of Shards (Cluster only)__: Each edge collection has the following configuration

Replication:1
Shards:72

## Steps to reproduce

1. Create and then delete edge collection test00001
2. Create and then delete edge collection test00002
3. ……
4. Create and then delete edge collection test30000

__Problem__: Memory keeps growing and won't be released

__Expected result__: Memory does not continue to grow

**Comment by Simran-B** [comment]
Are you referring to orphan collections of a named graph?
_deadCollections is not a built-in system collection to the best of my knowledge.

**Comment by yaocg** [comment]
When edge collections are repeatedly created and deleted, the memory will continue to grow. At the same time, I observed that the deleted edge collections in the variable [_deadCollections](https://github.com/arangodb/arangodb/blob/3.7.6/arangod/VocBase/vocbase.h#L145-L145) have not been cleaned up for a long time.

**Comment by dothebart** [comment]
please fill in the issue template.

**Comment by yaocg** [comment]
filled in

**Comment by dothebart** [comment]
ok; 3.7.x is no longer supported. 
You may find your issue resolved if you upgrade to the latest released 3.7.18.
However, in general you should consider upgrading to at least 3.10 if not 3.11.
