### ISSUE TITLE
[issue] Fail to write rows to arangodb in batch when importing dataset with java client concurrently

### ISSUE THREAD

**Issue by dongma** [arangodb/arangodb#19744]
## My Environment

* __ArangoDB Version__:        3.6.13 community edition
* __Deployment Mode__:        Leader/Follower ("Master/Slave")
* __Deployment Strategy__:   Manual Start，arangodb3-3.6.13-1.0.x86_64.rpm
* __Configuration__:               3 nodes (one master and two slave)
* __Infrastructure__:               own
* __Operating System__:       CentOS 7.x
* __Total RAM in your machine__:    64Gb
* __Disks in use__:         SSD
* __Used Package__:     arangodb3-3.6.13-1.0.x86_64.rpm

## Component, Query & Data

__Affected feature__:

Java client parameter prepare and send request:
``` 		
DocumentImportOptions options = new DocumentImportOptions().waitForSync(true);
options.details(true);
options.onDuplicate(DocumentImportOptions.OnDuplicate.update);
ArangoSerializer.Options serialOptions = new ArangoSerializer.Options().serializeNullValues(true).stringAsJson(true);
DocumentImportEntity retObj = ac.importDocuments(rows, options, serialOptions);
```
__Problem__:
the error trace is: 
```
creating document failed with error 'conflict', offending document:  {"xx": xxx, "_from": null, .....}
```
__Expected result__:
except write data rows to graph database successfully.
downloaded arangodb source code today, and grep with keyword 'creating document failed with error'  
```
> grep -rn 'creating document failed with error' *        
> RestHandler/RestImportHandler.cpp:927:   positionize(i), "creating document failed with error '",
```
found that the error msg is generated in RestImportHandler.cpp file (line: 927), but it's hard to understood the write logic (wasn't familiar with C++).

My Question: 
1. the reason why throw creating document failed with error 'conflict'?
2. If the data rows is illegal, hope to provide the conflict conditions for fix error data?

Hope your reply, Thanks.

**Comment by dothebart** [comment]
Hi, Please note that ArangoDB 3.6 has been EOLed for quiet a while now. 
Please upgrade to at least ArangoDB 3.10 and check back whether the issue persists.

**Comment by dongma** [comment]
Thanks for your reply !
Arangodb 3.6.13 had been deployed on product environment for a long time, It's hard to upgrade graph database version. 
Reduced the number of write threads to single one, the phenomenon creating document failed with error 'conflict' was disappeared.

**Comment by dothebart** [comment]
V3.6.16 has been the last bugfix release; you should at least consider upgrading to that to get all possible bugfixes.
Closing this issue now.
