### ISSUE TITLE
Fedora package improperly linked with libjemalloc

### ISSUE THREAD

**Issue by voxadam** [arangodb/arangodb#1978]
## my environment running ArangoDB

I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [x] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [x] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:
### this is an installation-related issue:

Installing ArangoDB on Fedora 24 using the [arangodb3-3.0.4-12.1.x86_64.rpm](https://www.arangodb.com/repositories/arangodb3/Fedora_23/x86_64/arangodb3-3.0.4-12.1.x86_64.rpm) package fails 
with the following error:

`/usr/sbin/arango-init-database: error while loading shared libraries: libjemalloc.so.1: cannot open shared object file: No such file or directory`

This bug results in an unusable ArangoDB install.

**Comment by dothebart** [comment]
Hm, this is probably a problem with the SuSE OBS; I'm currently working to integrate CPACK into the Arangodb build process; This will become available with ArangoDB 3.1, so we won't debug this now. Thanks for reporting, I will have an eye that cpack does this right.

**Comment by stolbovoi** [comment]
Hi, I have the same issue.
when it is expected the release 3.1?

**Comment by dothebart** [comment]
We meanwhile released 3.1 which statically links jemalloc - thus closing now.

**Comment by bangert** [comment]
sad to hear this. what is the problem?

also - there are still no Fedora 24 packages/no Fedora 24 repo available.

**Comment by dothebart** [comment]
I will have to workaround https://issues.jenkins-ci.org/browse/JENKINS-39307 for a solution, or it should be fixed ;-)

Whats sad to hear about this? we deliver a jemalloc version that may be different to the distribution one. Hence this bug report in first place. Given the size of jemalloc I don't see a problem in static linking.

**Comment by bangert** [comment]
https://wiki.gentoo.org/wiki/Why_not_bundle_dependencies
https://fedoraproject.org/wiki/Bundled_Libraries?rd=Packaging:Bundled_Libraries

with sad i mean sub-optimal. feel free to ignore my babbeling ;-)

**Comment by dothebart** [comment]
btw, 
```
git checkout v3.1.0
./scripts/build-rpm.sh
```
should give you the rpm.

**Comment by dothebart** [comment]
Ok, meanwhile we workarounded the Jenkins/Docker/Fedora issue, so FC25 rpms are available through arangodb.com again.
