### ISSUE TITLE
Efficient graph traversal - Traversal object vs AQL vs custom

### ISSUE THREAD

**Issue by sajeevpr** [arangodb/arangodb#1979]
## my environment running ArangoDB

I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [x] 3.0 y
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [x] RedHat .rpm y
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:
### this is an AQL-related issue:

[ ] I'm using graph features y

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.
### this is a web interface-related issue:

I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled? N
- [ ] using the cluster? N
- [x] _system database? Y

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click to ...
...

The following problem occurs: [Screenshot?] 
Instead I would be expecting: 
### this is an installation-related issue:

Describe which steps you carried out, what you expected to happen and what actually happened.

Dear team,
   We are trying to do a full graph traversal and it is taking almost 70 minutes. This is implemented using traversal objects in a Foxx service.

But our aim is to produce this in 30 minutes.

Total xpaths are 239 million lines generated on a file. We used 24 curl calls to generate this.

We are looking whether this can be further improved by using AQL or custom traversal using outEdges.

Thanks,
Sajeev

**Comment by dothebart** [comment]
This has been discussed in Jira.
