### ISSUE TITLE
Array function on AQL result

### ISSUE THREAD

**Issue by tthil** [arangodb/arangodb#1980]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 2.8
- [ ] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [x] MacOS, version: 10.11.6

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser:  Chrome   running on this OS: MacOS
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

Query string:
 LET serviceBookingIds = EDGES(bookIn, @supplierBookingId, "outbound")
 FOR serviceBookingId IN serviceBookingIds
         FOR serviceBooking IN serviceBookings
             FILTER serviceBooking._id == serviceBookingId._to
             LET accommodationIds = EDGES(use, serviceBooking._id, "outbound")
      		    FOR accommodationId IN accommodationIds
         	        FOR accommodation IN accommodations
           	        FILTER accommodation._id == accommodationId._to
                     RETURN accommodation._key

Execution plan:
 Id   NodeType             Est.   Comment
  1   SingletonNode           1   * ROOT
  2   CalculationNode         1     - LET serviceBookingIds = EDGES(bookIn   /* all collection documents */, "supplierBookings/708300078908", "outbound")   /* simple expression */
  3   EnumerateListNode     100     - FOR serviceBookingId IN serviceBookingIds   /* list iteration */
 15   IndexNode             100       - FOR serviceBooking IN serviceBookings   /* primary index scan */
  7   CalculationNode       100         - LET accommodationIds = EDGES(use   /* all collection documents */, serviceBooking.`_id`, "outbound")   /* simple expression */   /* collections used: serviceBooking : serviceBookings */
  8   EnumerateListNode   10000         - FOR accommodationId IN accommodationIds   /* list iteration */
 14   IndexNode           10000           - FOR accommodation IN accommodations   /* primary index scan */
 12   CalculationNode     10000             - LET #10 = accommodation.`_key`   /* attribute expression */   /* collections used: accommodation : accommodations */
 13   ReturnNode          10000             - RETURN #10

Indexes used:
 By   Type      Collection        Unique   Sparse   Selectivity   Fields       Ranges
 15   primary   serviceBookings   true     false       100.00 %   [ `_key` ]   ((serviceBooking.`_id` == serviceBookingId.`_to`))
 14   primary   accommodations    true     false       100.00 %   [ `_key` ]   ((accommodation.`_id` == accommodationId.`_to`))

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   move-calculations-up-2
  4   move-filters-up-2
  5   use-indexes
  6   remove-filter-covered-by-index

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click to ...
...

The following problem occurs: [Screenshot?] 
Instead I would be expecting: 

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

The result of the query is an array like: 
[
  "36840THA",
  "36836THA",
  "36839THA"
]
I would like to use this result with the (Array) MINUS function like this:
RETURN MINUS(["36840THA", "36836THA", "36839THA"], ["36836THA", "36839THA"])
With result:
[
  "36840THA"
]

But i guess my problem is that my RETURN is in the last FOR-loop and I can't use the MINUS function there. How could I rearrange the query to get the MINUS function to work?

**Comment by jsteemann** [comment]
Here's the query in a formatted way:
```
LET serviceBookingIds = EDGES(bookIn, @supplierBookingId, "outbound") 
FOR serviceBookingId IN serviceBookingIds 
  FOR serviceBooking IN serviceBookings 
    FILTER serviceBooking._id == serviceBookingId._to 
    LET accommodationIds = EDGES(use, serviceBooking._id, "outbound") 
    FOR accommodationId IN accommodationIds 
      FOR accommodation IN accommodations 
        FILTER accommodation._id == accommodationId._to 
        RETURN accommodation._key
```
The query will currently return a flat array of keys.
It is unclear to me what the desired result is, apart from that it should be constructed with the `MINUS` function. It seems that the desired result is an array of arrays of keys, but without further information I can only guess where these keys should come from and what the different input arrays to `MINUS` should be. Please provide some more explanation for this.

In general, the solution will be to put one or multiple of the `FOR` loops into subqueries. Consider this original query:
```
LET values = ['A', 'B', 'C'] 
FOR i IN 1..3 
  FOR doc IN values 
  RETURN doc
```
It will return `[ "A", "B", "C", "A", "B", "C", "A", "B", "C" ]` as a flat array.
Modifying the query to use a subquery will return an array of arrays, e.g.:
```
LET values = ['A', 'B', 'C'] 
FOR i IN 1..3 
  LET sub = (FOR doc IN values RETURN doc) 
  RETURN sub 
```
This will return the nested structure `[ [ "A", "B", "C" ], [ "A", "B", "C" ], [ "A", "B", "C" ] ]`.

**Comment by tthil** [comment]
That's correct. I like the query to return a flat array. But I like to return the difference between a constant array and the result using the MINUS function.
Like: 
RETURN MINUS("result of query flat array", ["A"])

**Comment by jsteemann** [comment]
Can't you put it like this?
```
LET other1 = ["A"]
LET other2 = ["foo", "bar"]
LET query = (FOR i IN ['A','B','C','D'] RETURN i) /* put original query here */
RETURN MINUS(query, other1, other2)
```

**Comment by tthil** [comment]
Thank you Jan,

exactly what I was looking for.

**Comment by Simran-B** [comment]
There's a German saying: If an engineer is at a loss, he uses a relay. For AQL, this could be adapted to "...use a subquery" I guess 😉
