### ISSUE TITLE
Aql With Transaction

### ISSUE THREAD

**Issue by namnik** [arangodb/arangodb#1981]
Hi,

I have a **Edge Collection** with Name: **Contact**. 
Now, I want to retrieve a document of my **edge** according of two field: _from , _to.
this my raw query, that fine worked in the query editor of ArangoDb Web interface:

`FOR cnt IN Contact FILTER cnt._from == 'User/1' and cnt._to=='User/2' RETURN cnt`
but when I call this query using **db._query()**, I toke a error : 

_ArangoDB error: missing/invalid action definition for transaction_

this is my complete code that written using c# driver([ArangoDB-NET](https://github.com/yojimbo87/ArangoDB-NET))

```
var transactionResult = Context.Transaction.ReadCollection("Contact").WriteCollection("Contact").Execute<string>(@"

               function () {
                var db = require('internal').db;            
           var arr=db._query('FOR cnt IN Contact FILTER cnt._from=='User/1'  and cnt._to=='User/2' RETURN cnt ');
             return 'true';
                  }");
```

can any one help me?!

**Comment by jsteemann** [comment]
I haven't tried the query in C# myself, but it seems that the quotes inside the JavaScript code are somewhat wrong.

For example, you are passing the query string as a parameter into `db._query()`. The query string itself is a string enclosed in single quotes (`'`), but the query string itself contains single quotes to enclose the lookup values (e.g. `'User/1'`). 
Here's the offending line:
```
arr=db._query('FOR cnt IN Contact FILTER cnt._from=='User/1'  and cnt._to=='User/2' RETURN cnt ');
```
It should probably rather be:
```
arr=db._query('FOR cnt IN Contact FILTER cnt._from== \'User/1\'  and cnt._to== \'User/2\' RETURN cnt ');
```
Maybe I'm wrong here as I don't know how C# will treat the backslashes. But that's how it would be done in JavaScript. 
I'm not sure if this fixes the problem, but at least the wrong quotes will keep the query from working.

**Comment by Simran-B** [comment]
AFAIK single and double quotes have different semantics in C#:

- `'` - used to enclose a literal character (type: char)
- `"` - used to enclose character sequences (type: string)

Therefore, I suggest to try the following:

````csharp
arr = db._query("FOR cnt IN Contact FILTER cnt._from=='User/1' AND cnt._to=='User/2' RETURN cnt");
```

The query string is actually a string (using double quote marks). In AQL, `'` and `"` can both be used, but since `"` would conflict with the C# double quote mark, it would require escaping (`\"`) and it's therefore nicer to use the single quote mark in AQL (avoids the backslash disease).

**Comment by namnik** [comment]
@jsteemann , Simran-B : thanks guys... both answer fine worked.... 
now, I have  a new question about this code!:
how I can get the count of **arr** variable? 
I want to check if the result of query is not null (didnt exists a document) , then Add a document.
I use this code, that **If** didn't work, and I couldnt Add a **Contact**:
`
var db = require('internal').db;  
q = db._query(""FOR cnt IN Contact FILTER cnt._from=='User/1' AND cnt._to=='User/2' RETURN cnt""); 

                 arr = q.toArray();
                 if(arr.lenght == 0) 
                     db.Contact.save({{ _from:'User/1', _to:'User/2'}});
`

.........?

**Comment by baslr** [comment]
@namnik you can use `UPSERT` for this
https://docs.arangodb.com/3.0/AQL/Operations/Upsert.html

**Comment by namnik** [comment]
@baslr : thanks...  UPSERT  could be a solution , but not exactly things that I want!

**Comment by namnik** [comment]
my final code, that's fine worked!:

` 
var items = db._query(""FOR cnt IN Contact FILTER cnt._from=='User/{0}' AND cnt._to=='User/{1}' RETURN cnt._key"").toArray();
                                if(items[0] == null) 
                     db.Contact.save({{ _from:'User/{0}', _to:'User/{1}'}});`
