### ISSUE TITLE
Unable to launch two ArangoDB services on the same machine with different port numbers

### ISSUE THREAD

**Issue by JaguarPaw2409** [arangodb/arangodb#19861]
## My Environment

* __ArangoDB Version__:        3.11
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               
* __Infrastructure__:               Own
* __Operating System__:        CentOS 7
* __Total RAM in your machine__:        256GB
* __Disks in use__:        NFS
* __Used Package__:             tar

## Component, Query & Data

__Affected feature__:
Installation

__AQL query (if applicable)__:
```
NA

```
__AQL explain and/or profile (if applicable)__:
NA

__Dataset__:
NA

__Size of your Dataset on disk__:
NA

__Replication Factor & Number of Shards (Cluster only)__:
NA

## Steps to reproduce

1. Execute the following commands on the same machine
2. ./bin/arangod --server.endpoint tcp://0.0.0.0:8531 --database.directory /global/db1
3. ./bin/arangod --server.endpoint tcp://0.0.0.0:8532 --database.directory /global/db2

__Problem__:
2023-09-28T09:11:22Z [21539] ERROR [874fa] {communication} unable to bind to endpoint 'http+tcp://127.0.0.1:8529': Address in use
2023-09-28T09:11:22Z [21539] FATAL [c81f6] {general} failed to bind to endpoint 'http+tcp://127.0.0.1:8529'. Please check whether another instance is already running using this endpoint and review your endpoints configuration.

__Expected result__: Why am I unable to launch two ArangoDB services on the same machine with different port numbers? Why the port number 8529 is coming into picture?

**Comment by JaguarPaw2409** [comment]
2023-09-28T11:10:20Z [29777] INFO [6ea38] {general} using endpoint 'http+tcp://0.0.0.0:8531' for non-encrypted requests
2023-09-28T11:10:20Z [29777] INFO [6ea38] {general} using endpoint 'http+tcp://127.0.0.1:8529' for non-encrypted requests


Why the service is running on two ports (8529 and 8531) even if server.endpoint is pointing to the port number 8531?

**Comment by dothebart** [comment]
the `arangod.conf` will bring you the default bind to 8529. You just add another one by specifying it on the commandline. 
You either need to edit arangod.conf not to specify an endpoint, or use `-c` to specify two different arangod config files.

**Comment by JaguarPaw2409** [comment]
For individuals who are still confused about what to do while using a tar-based installation, simply open 'bin/arangod' and delete the following line. 'bin/arangod' is not a binary; it's merely a script that can be edited.

![image](https://github.com/arangodb/arangodb/assets/10769536/670c95d1-9c2c-4cb5-823e-6f19ece7be8a)
