### ISSUE TITLE
fromClient is not called by router.patch().body()

### ISSUE THREAD

**Issue by davidgraham** [arangodb/arangodb#1987]
## my environment running ArangoDB

I'm using the latest ArangoDB of the respective release series:
- [ X] 3.0

On this operating system:
- [ X] MacOS, version:
### Foxx

When calling router.post().body(Model), the fromClient() function in my Model is called and the model is validated against the joi schema, but when calling router.patch.body(Model), the fromClient() function is not called, although the model is still validated against the joi schema.

In my case, I use forClient() and fromClient() to translate between the  "_key" property used by arangodb, and the "id" property used by jsonapi (for emberjs).  Post requests work fine, but patch requests fail since the "id" is not converted to "_key" before being checked against the joi schema and i see

```
INFO via ValidationError: child "data" fails because ["id" is not allowed]
INFO     at Object.exports.process (/usr/local/opt/arangodb/share/arangodb3/js/node/node_modules/joi/lib/errors.js:152:19)
INFO     at internals.Any._validateWithOptions (/usr/local/opt/arangodb/share/arangodb3/js/node/node_modules/joi/lib/any.js:633:27)
INFO     at internals.Any.validate (/usr/local/opt/arangodb/share/arangodb3/js/node/node_modules/joi/lib/any.js:649:17)
INFO     at Object.validateRequestBody (/usr/local/opt/arangodb/share/arangodb3/js/server/modules/@arangodb/foxx/router/validation.js:122:27)
```

in my logs

**Comment by pluma** [comment]
@davidgraham Sorry for the delay. Can you provide a test case for this behaviour? A small example service demonstrating the bug would go a long way towards finding the underlying cause.

**Comment by pluma** [comment]
@davidgraham Are you still experiencing this problem in the current version of ArangoDB? If so, can you please provide an example service demonstrating this bug? You can send me a link via direct message on the Community Slack if you'd prefer not to make it public.

**Comment by davidgraham** [comment]
Sorry, I am no longer using ArangoDB.
