### ISSUE TITLE
HTTP REST API: DELETE /_api/document/{collection} does not work

### ISSUE THREAD

**Issue by joowani** [arangodb/arangodb#1989]
**ArangoDB version**: 3.04
**OS**: Ubuntu 16.04 and OS X 

Hello,
I am reporting a bug in the HTTP REST API.

The [DELETE /_api/document/{collection}](https://docs.arangodb.com/3.0/HTTP/Document/WorkingWithDocuments.html) endpoint for removing multiple documents does not seem to work. On a valid request I receive the following response: 

`Request body not parseable`. 

The HTTP status code is 400 and the server error code is also 400.

From a quick search it looks like the error is coming from here:
https://github.com/arangodb/arangodb/blob/3.0/arangod/RestHandler/RestDocumentHandler.cpp#L528

Steps to reproduce:
1) Supply any valid combination of options/parameters
2) Supply an array of documents keys or documents objects or mixed in the body of the request
3) Issue the DELETE API request 

Thanks!

**Comment by mchacki** [comment]
@joowani I tried to reproduce this issue and failed.

Can you send me an example request you try to execute against the database?
The only situation when i get into the `Request body not parseable` is when i send invalid JSON, most likely forget to set the keys in quotation marks also:

Invalid body: `[{_key: "a"}, {_key: "b"}]`
Valid body: `[{"_key": "a", {"_key": "b"}]`

So as an example this request did work for me:
`curl -X DELETE http://localhost:8529/_api/document/v --data "[\"v/a4\", {\"_key\": \"a5\"}, {\"_id\": \"v/a6\"}]`

**Comment by joowani** [comment]
Hi @mchacki 

I apologize this was an error on my part. 
There are no problems after all.
Thank you very much for looking into this.
