### ISSUE TITLE
Bulk insert using AQL

### ISSUE THREAD

**Issue by namnik** [arangodb/arangodb#1990]
How Can Bulk insert in arango db 3.0?
I want to put content from a file (include collection or documents) into ArangoDB repository?

**Comment by dothebart** [comment]
Hi, 
you can use [ArangoImp](https://docs.arangodb.com/3.0/Manual/Administration/Arangoimp.html) for this.

Its utilizing [the bulk import API](https://docs.arangodb.com/3.0/HTTP/BulkImports/index.html) if you rather want to use it inside of own code.

**Comment by namnik** [comment]
@dothebart: thanks for helping... in this link, had a sample for posting a bulk:

`shell> curl -X POST --data-binary @- --dump - http://localhost:8529/_api/import?collection=products <<EOF
[ "_key", "value1", "value2" ]
[ "abc", 25, "test" ]

[ "foo", "bar", "baz" ]
EOF`

I guess this command run in Linux, I'm Windows's User!. 

when I run this url in [fiddler](www.telerik.com/fiddler), I got a exception: 
HTTP/1.1 401 Unauthorized
cookies:
Www-Authenticate: Bearer token_type="JWT", realm="ArangoDB"


1. this command run on which database(_system or existing database)? How pass database name as a parameter?
2. and how can I assign user password for authorizing?
3. can I call this command such as WebApi in C#?

thanks a lot....

**Comment by dothebart** [comment]
Curl is a tool commonly available on all platforms. 
See: https://curl.haxx.se/
In curl you can add the authentication with --user <user>:<password>

You could use basic authentication ( https://en.wikipedia.org/wiki/Basic_access_authentication )
which should be supported by all http clients and in doubt can be done by hand.

**Comment by dothebart** [comment]
Have a look at https://docs.arangodb.com/3.0/HTTP/Database/index.html regarding your first question.

**Comment by namnik** [comment]
@dothebart : thanks a lot... I got it my answer with [latest link]( https://docs.arangodb.com/3.0/HTTP/Database/index.html) of your comment:
I used fiddler tools for testing HTTP Api, and fine worked:
![22](https://cloud.githubusercontent.com/assets/13764362/17516875/3127ff10-5e56-11e6-8c30-6c8025a0f681.PNG)
