### ISSUE TITLE
ClusterIndex: unsupported cluster storage engine 

### ISSUE THREAD

**Issue by gianluca-valentini** [arangodb/arangodb#19927]
**Problem Description:**
During an operation to update document properties using the ArangoDB Java driver version 7.1.0, I encountered the following error:

`com.arangodb.ArangoDBException: Response: 500, Error: 4 - unsupported cluster storage engine (exception location: /work/ArangoDB/arangod/ClusterEngine/ClusterIndex.cpp:210). Please report this error to arangodb.com`

this is the complete log error:

> 2023-10-06T18:56:56.592568662Z com.arangodb.ArangoDBException: Response: 500, Error: 4 - unsupported cluster storage engine (exception location: /work/ArangoDB/arangod/ClusterEngine/ClusterIndex.cpp:210). Please report this error to arangodb.com
> 2023-10-06T18:56:56.592572297Z 	at com.arangodb.internal.util.ResponseUtils.checkError(ResponseUtils.java:53) ~[core-7.1.0.jar:7.1.0]
> 2023-10-06T18:56:56.592574891Z 	at com.arangodb.http.HttpCommunication.execute(HttpCommunication.java:86) ~[http-protocol-7.1.0.jar:7.1.0]
> 2023-10-06T18:56:56.592577300Z 	at com.arangodb.http.HttpCommunication.execute(HttpCommunication.java:66) ~[http-protocol-7.1.0.jar:7.1.0]
> 2023-10-06T18:56:56.592579704Z 	at com.arangodb.http.HttpProtocol.execute(HttpProtocol.java:44) ~[http-protocol-7.1.0.jar:7.1.0]
> 2023-10-06T18:56:56.592582027Z 	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:60) ~[core-7.1.0.jar:7.1.0]
> 2023-10-06T18:56:56.592584339Z 	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:48) ~[core-7.1.0.jar:7.1.0]
> 2023-10-06T18:56:56.592586601Z 	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:44) ~[core-7.1.0.jar:7.1.0]
> 2023-10-06T18:56:56.592588845Z 	at com.arangodb.internal.ArangoCollectionImpl.changeProperties(ArangoCollectionImpl.java:464) ~[core-7.1.0.jar:7.1.0]

the related document has also
Shard keys and Number of shards:	4

**Environment**:

ArangoDB Cluster: 3.11.2
Agents: 3
Coordinator: 4
Database: 4
Storage: Ceph 

Deployed with Arango Operator

**Steps to Reproduce:**

Execute an operation to update document properties using the ArangoDB Java driver version 7.1.0.
Encounter the error described above.

**Additional Information:**

The operation involved updating document properties.
The Java driver version used is 7.1.0.

**Notes:**

The error message suggests an issue related to the cluster storage engine.
Please investigate and address this issue.

Thank you.
Gianluca Valentini

**Comment by jsteemann** [comment]
Hi, I guess the operation happened during the update of _collection_ properties, not _document_ properties.
We just merged a bugfix for this a few days ago: https://github.com/arangodb/arangodb/pull/19897
The bugfix will be part of 3.11.4, which is supposed to be released in the next few work days.

**Comment by gianluca-valentini** [comment]
Hi @jsteemann 
thanks a lot for your answer. Sorry for the error. The operation was on collection properties.
I hope that the new release in order to complete my task

Thanks
Gianluca

**Comment by jsteemann** [comment]
Hi, 
> I hope that the new release in order to complete my task
We found that the issue only happens when there is an arangosearch view present on the underlying collection. We found that a workaround to changing the collection properties was to drop the view first, then change the properties, and then recreate the view. This worked for us, but obviously it means that the view is unavailable between the point in time it is dropped and until it is fully recreated. So it may not be an option for you to use this workaround.

**Comment by andrea-tomassi** [comment]
> Hi,
> 
> > I hope that the new release in order to complete my task
> 
> We found that the issue only happens when there is an arangosearch view present on the underlying collection. We found that a workaround to changing the collection properties was to drop the view first, then change the properties, and then recreate the view. This worked for us, but obviously it means that the view is unavailable between the point in time it is dropped and until it is fully recreated. So it may not be an option for you to use this workaround.

This information helps a lot. While waiting for the fix we're trying the workaround.
Thank you!

**Comment by tarator** [comment]
We had the same problem with version 1.11.1
Upgrading to 1.11.4 solved the problem.

IMO this ticket can be closed.

**Comment by jsteemann** [comment]
@tarator : thanks for letting us know. Closing the ticket for good now.
