### ISSUE TITLE
Inconsistent conversions in Buffer

### ISSUE THREAD

**Issue by ThomasWeiss** [arangodb/arangodb#1993]
I'm using the latest ArangoDB of the respective release series:
- [x] 3.0
  On this operating system:
- [x] Windows, version: 10

Because `crypto.hmac` only works with `string`s (as opposed to `Buffer` / `char*` as does the underlying OpenSSL lib), I have to convert my buffers to/from utf8 in order to interface with the method.

This proved to work with buffers that are actual strings, but not with any kind of random byte array, and it seems that's because the conversion of such random arrays to utf8 is wrong (or at least, different from what I get in C# for example).

Example:

```
var input = 'dGVzdA=='; // "test"
var toUtf8 = new Buffer(input, 'base64').toString('utf8');
var backToBase64 = new Buffer(toUtf8, 'utf8').toString('base64');
var success = input == backToBase64 // true

var input = '+vv8/Q=='; // [250,251,252,253]
var toUtf8 = new Buffer(input, 'base64').toString('utf8');
var backToBase64 = new Buffer(toUtf8, 'utf8').toString('base64');
var success = input == backToBase64 // false
```

**Comment by jsteemann** [comment]
The problem with the above example seems to be that [250,251,252,253] cannot be represented in UTF-8. That means if you base64-decode the string `+vv8/Q==` into a Buffer and then convert it to UTF-8, there will always be a loss.
I am not sure if this is fixable elegantly.

**Comment by ThomasWeiss** [comment]
Agreed, and I have to confess that I ran into this situation while trying to find a workaround to `crypto.hmac` only accepting string keys (#1986). I tried the same code on Node.js and I got the exact same results (maybe your Buffer implementation comes from Node).

**Comment by jsteemann** [comment]
The issue "converting a Buffer to a string may cause data loss" cannot be fixed.
Strings in JavaScript can only contain valid UTF values, and conversion from arbitrary binary Buffer data to UTF will stop when there is an invalid sequence.

However, if this issue was originally triggered by issue #1986, then it may be closed. 
In 3.1 the crypto.hmac function should be able to handle Buffer data as well.
Can you confirm this is working for you? Thanks.

**Comment by ThomasWeiss** [comment]
Yes Jan that's working for me, thanks for your follow-up!

**Comment by jsteemann** [comment]
Thanks for the confirmation. I'll close that issue now.
