### ISSUE TITLE
Upgrade to Gitbook 3.x

### ISSUE THREAD

**Issue by Simran-B** [arangodb/arangodb#1994]
Templating in Gitbook 3.x looks much more powerful, and certain plugins are no longer maintained for the 2.x line (most notably `sitemap`). Upgrading the documentation system will cause some work and headache however.
## Blockers

There are some bugs in Gitbook, that have to be resolved yet:
- Chapter numbers have an extraneous `1.` prepended, caused by a new feature for multiple parts in a book: https://github.com/GitbookIO/gitbook/issues/1301
- Viewing the generated files offline doesn't work well with Chrome in 2.x, but 3.x apparently breaks all browsers, because `/index.html` is not appended anymore. Served through a web server, there would be an automatic redirect, but with offline files nothing will happen or a 404 error occur when clicking such a link: https://github.com/GitbookIO/gitbook/issues/1362
## Tasks for upgrading
- Not all plugins that used to work with Gitbook 2.x appear to be compatible with 3.x. This mostly affects self-written ones, as the more popular plugins have been updated officially. We will have to update ours as needed.
- The current implementation to add our own navigation header is sub-optimal. HTML, CSS and JS is nearly identical for all books. It would be easier to have just one copy and use them for all books. The `add-header` plugin should probably be replaced by a template override.
## Additional tasks

The following things are not strictly needed to upgrade the documentation system, but we could use the chance to resolve some other issues for good:
- Get rid of MarkdownPP. We don't use any of the preprocessor features, but the Python scripts include custom code for integrating DocuBlocks and Swagger. The functionality could probably be ported to Gitbook built-in features or self-written plugins, so that we could lose the Python interpreter dependency.
- Using Gitbook templating, it should be possible to improve the handling of DocuBlocks. Relative links from snippets back to other parts of the documentation are only possible at the moment, if the pages that include the snippets are located at the same folder depth. Otherwise the links will be broken for some of them. We could let Gitbook compute the correct URLs for every snippet included: https://github.com/GitbookIO/gitbook/issues/1367
- With the intermediate preprocessor step removed, all files could be renamed from `.mdpp` to `.md` and directly processed by Gitbook. This would also enable `gitbook serve` for live-editing.
- The way we integrate Examples and Swagger is not very efficient so it seems. Using Gitbook includes should speed it up, but I'm not certain if we would lose some error checking.
- There's some trouble with the Ditaa integration if there's no preprocessor step: `.ditaa` files would need to turned into `.png` by a Gitbook plugin, which is run on every (re-)generation of the docs to ensure it is up-to-date. The source files can't be deleted however, because that would remove git-tracked files. The `.ditaa` files could be excluded when publishing the docs online, but I don't see any harm in uploading them as well. As alternative, we could create images or SVG for illustration instead, and remove Ditaa again.
- There's an experimental "native" Bash shell for Windows 10. It might be possible to build the docs without Cygwin in this shell. We could also look into migrating the build script to Gitbook / NodeJS, so that we don't `make` on Windows. This would mean to port all sanity checks of the bash script.

**Comment by pluma** [comment]
The second blocker is apparently delayed until v4: https://github.com/GitbookIO/gitbook/milestone/6

**Comment by hkernbach** [comment]
Upgrade to GitBook 3.2.2 is done.
