### ISSUE TITLE
Unattended installation no longer working in Ubuntu 14.04 x64 for v3.0.4

### ISSUE THREAD

**Issue by hbCyber** [arangodb/arangodb#1996]
- ArangoDB v3.0.4
- Ubuntu 14.04 x64 (Trusty64)

I used to run an automated script to build my ArangoDB server. As per your documentation, I was setting the root password from the command line prior to installation:
```
echo arangodb3 arangodb/password password ${ARANGODB_ROOT_PASSWORD} | sudo debconf-set-selections
echo arangodb3 arangodb/password_again password ${ARANGODB_ROOT_PASSWORD} | sudo debconf-set-selections
sudo dpkg -i ${ARANGODB_PACKAGE_FILE}
```

This no longer seems to work with v3.0.4, as the UI pops open and asks me to type in a root password manually.

This used to work with v3.0.2

**Comment by dothebart** [comment]
Hi, 
using `arangodb/*` as namespace for packages not named 'arangodb' (but arangodb3) is not supported in all cases by debconf; This will result in the password dialog not opening during the attended install depending on your OS version.

Thus we had to rename the config strings to be `arangodb3/*`.

Sorry for causing inconvenience.

**Comment by hbCyber** [comment]
Thanks for your response! I have updated my script to use arangodb3/* instead of arangodb/* and it works again. Thanks so much for your support, my issue is resolved

**Comment by wizzl35** [comment]
Just wasted a couple of hours trying to figure out this problem.  Can someone update the 3.0 documentation?

**Comment by dothebart** [comment]
Hi, 
we fixed https://docs.arangodb.com/3.0/Manual/GettingStarted/Installing/Linux.html - the deploy of the documentation was missing - sorry for causing inconvenience.
