### ISSUE TITLE
arangod: command not found

### ISSUE THREAD

**Issue by spencerchubb** [arangodb/arangodb#19976]
## My Environment

Debian

## Steps to reproduce

I followed this documentation to set up

```bash
curl -OL https://download.arangodb.com/arangodb311/DEBIAN/Release.key
sudo apt-key add - < Release.key

echo 'deb https://download.arangodb.com/arangodb311/DEBIAN/ /' | sudo tee /etc/apt/sources.list.d/arangodb.list
sudo apt install apt-transport-https
sudo apt update
sudo apt install arangodb3=3.11.3-1
```

__Problem__:

Next I am trying to follow these docs: https://docs.arangodb.com/3.11/deploy/deployment/cluster/deployment/manual-start/

However when I try to run any command with arangod, it says command not found

```bash
arangod: command not found
```

If I run the set up steps, will it also install arangod, or do I have to install something else for that?

**Comment by spencerchubb** [comment]
Fixed with the following
```
export PATH="$PATH:/usr/sbin"
```

**Comment by dothebart** [comment]
Yes, by default only the root user has `sbin` in his path.
