### ISSUE TITLE
In tests, graph._removeVertexCollection doesn't remove anything

### ISSUE THREAD

**Issue by beeva-ivanmarques** [arangodb/arangodb#1999]
## my environment running ArangoDB

I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [x] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [x] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:
### this is an AQL-related issue:

[x] I'm using graph features
### Foxx

[arango-foxx-test-app.zip](https://github.com/arangodb/arangodb/files/421984/arango-foxx-test-app.zip)

In the model/testRemoveVertexCollection.spec.js file, in afterEach method, we are trying to remove the  vertex collections from the graph, forcing to remove also the collections using graph._removeVertexCollection('collection_name', true), but it doesn't remove anything.

The following problem occurs: [Screenshot?] 
![arangovertexcollections](https://cloud.githubusercontent.com/assets/12953699/17728460/a2d35088-645f-11e6-8218-1fce0f862b7b.png)

Instead I would be expecting: 
![vertexcollectionsdeleted](https://cloud.githubusercontent.com/assets/12953699/17728495/c80224b0-645f-11e6-9a2f-100cc1257990.png)

Can you help, please?

**Comment by beeva-ivanmarques** [comment]
We think this is not just a front-end issue, the terminal shows the same result.

![arango-graph-edge-definitions](https://cloud.githubusercontent.com/assets/12953699/17882673/3715a194-690e-11e6-94e4-e310327eb877.png)

**Comment by geraldxie** [comment]
I encountered this issue. It seems that if I removed the collections and the edge collection before removing the collection definition from graph it will not properly remove it via the front-end.

**Comment by hkernbach** [comment]
@geraldxie Thanks. Could reproduce with your description.  Will be fixed soon.

`127.0.0.1:8530@_system> knows._removeVertexCollection('frenchCity')
JavaScript exception in file '/Users/hkernbach/Git/arangodb/devel/js/common/modules/@arangodb/general-graph.js' at 2178,5: ArangoError 1926: vertex collection does not exist or is not part of the graph
!    throw err;
!    ^
stacktrace: ArangoError: vertex collection does not exist or is not part of the graph
    at Graph._removeVertexCollection (/Users/hkernbach/Git/arangodb/devel/js/common/modules/@arangodb/general-graph.js:2175:11)
    at <shell command>:1:7`

**Comment by dothebart** [comment]
The issue was fixed with the rewrite being part of ArangoDB 3.4

ArangoDB 3.4 RC3 is available for download; thanks for reporting the issue.
Closing.
