### ISSUE TITLE
Randomly select multiple document in ArangoDB

### ISSUE THREAD

**Issue by namnik** [arangodb/arangodb#2000]
- [ ] 3.0
- [ ] Windows, version: 8

### this is an AQL-related issue:
I'm issuing AQL via:
- [ ] This Driver: [ArangoDB-NET](https://github.com/yojimbo87/ArangoDB-NET)

I read this [post](http://stackoverflow.com/questions/28819675/randomly-select-a-document-in-arangodb) about randomly select a document, but I need a query to select multiple document each time!

please help!

**Comment by Simran-B** [comment]
Just increase the limit, e.g. return 20 random documents from collection `nodes`:

```
FOR node IN nodes
  SORT RAND()
  LIMIT 20
  RETURN node
```

**Comment by dothebart** [comment]
please see https://docs.arangodb.com/3.0/AQL/Operations/Limit.html for more details.

**Comment by namnik** [comment]
@Simran-B , @dothebart : thanks a lot guys...
