### ISSUE TITLE
Allow foxx services to have their own dependency to Joi

### ISSUE THREAD

**Issue by olivermack** [arangodb/arangodb#20018]
## My Environment

* __ArangoDB Version__:       3.11.4
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start in Docker
* __Operating System__:        MacOS 13.5.1

## Component, Query & Data

__Affected feature__:

Foxx

## Steps to reproduce

1. Set up a new project running arangodb via docker (compose in my case) without any additional server configs
2. Create a Foxx Service codebase with a `package.json`, `package-lock.json` and installed `node_modules` and ensure to include a dependency to `joi` in a recent version, e.g. `17.11.0`
3. Use the Foxx CLI to install the service

__Problem__:

When attempting to install my package I receive errors as mentioned in https://github.com/arangodb/foxx-cli/issues/45

```
ReferenceError: URL is not defined
```

Due to a dependency of arangodb to Joi `14.x` I seem not to be able to use a more recent version of Joi.

__Expected result__:

I'd like to be able to use a more recent version of Joi (https://www.npmjs.com/package/joi).

**Comment by dothebart** [comment]
Hi,
more recent versions of joi are no longer compatible with ArangoDB.
Since we can't change that, I will close this as "Won't fix"

**Comment by olivermack** [comment]
Hi @dothebart ,

I really appreciate your instant feedback. The comment https://github.com/arangodb/foxx-cli/issues/45#issuecomment-1023343055 already states:

> The newer versions of joi seem to be incompatible with the ArangoDB JavaScript environment as they rely on internals ArangoDB does not implement

but I'm not able to find any more details on that. What's the reason why _the internals_ do not implement something which is required by newer versions of joi? What _internals_ are those? Why can't those _internals_ be patched in order to allow this kind of chore?

You've stated 

> we can't change that

but why is that?

I'd really appreciate if you could elaborate a bit more on that to get a better understanding about the root cause why this is "blocked" or "can't be fixed".

Best
