### ISSUE TITLE
Error in INSERT with WITH or in a upsert  update with insert  with in

### ISSUE THREAD

**Issue by zentown** [arangodb/arangodb#2003]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [x] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [x] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser:  Firefox   running on this OS: windows
- [x] http endpoint _db/xxxx/_api/cursor/
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is: 
https://docs.arangodb.com/3.0/AQL/Operations/Insert.html#setting-query-options

FOR i IN 1..1000
  INSERT { _key: CONCAT('test', i), name: "test" } WITH { foobar: true } IN users OPTIONS { waitForSync: true }

that gives me this error:
Explain: syntax error, unexpected WITH keyword near 'WITH { foobar: true } IN users O...' at position 2:52 (while parsing)

The aql query I was using was more longer but it throws the same error because of WITH, i'm sending a array of json objects as a document and i'm want to define the _key value from a value inside that document

The issue can be reproduced using this dataset: Empty table users

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

**Comment by Simran-B** [comment]
As the error message says, the syntax is invalid, see https://docs.arangodb.com/3.0/AQL/Operations/Insert.html

There is no `WITH` in `INSERT` statements. The query should look like this instead:

```js
FOR i IN 1..1000
  INSERT {
    _key: CONCAT('test', i),
    name: "test",
    foobar: true
  } INTO users OPTIONS { waitForSync: true }
```

**Comment by zentown** [comment]
Thanks @Simran-B , so it's a error in the documentation in the section that said "Setting query options" of insert.
I saw that with UPDATE there is WITH

I have an array of json documents that is the output of other program
And i have something like this

For doc in [{ 'id':'111', 'a':'456', 'b':'879'}, {'id':'222', 'a':'456', 'b':'789'}, ....]
UPSERT { _key : doc.id} INSERT { _key : doc.id } WITH doc UPDATE  { _key : doc.id }  WITH doc  IN users RETURN NEW;

Is there any way that i could define the _key value in insert if y pass the json array
It would be nice if INSERT also support WITH now that UPSERT need to use both of them

**Comment by Simran-B** [comment]
Strange, I searched for `WITH` on the docs page but couldn't find it. [Now I did](https://docs.arangodb.com/3.0/AQL/Operations/Insert.html#setting-query-options) though. This is indeed a mistake in the docs, thanks for spotting! I'll correct it.

If I understand your problem correctly, you want to do this:

```js
FOR doc IN @docs // bind parameter: `[ { "id": 111, "a": 456 }, { "id": 222, "a": 456 }, ... ]`
    UPSERT { _key: doc.id } // try to find existing document with _key equal to id of input document
    INSERT MERGE( UNSET( doc, "id" ), { _key: doc.id } ) // if no document is found, remove id attribute and use its value as _key
    UPDATE UNSET( doc, "id" ) IN users // or if a document with _key = doc.id exists, update it (but without adding the id attribute)
    RETURN NEW
```

**Comment by zentown** [comment]
yes that exactly what I want, thank you

**Comment by CoDEmanX** [comment]
Corrected the docs:
https://github.com/arangodb/arangodb/commit/a5427356836c6fa2e59ccc9fee69215746666aeb

**Comment by Simran-B** [comment]
Corrected the docs: https://github.com/arangodb/arangodb/commit/a5427356836c6fa2e59ccc9fee69215746666aeb
