### ISSUE TITLE
filter in web frontend does not work properly with multiple pages

### ISSUE THREAD

**Issue by menzelths** [arangodb/arangodb#2005]
## my environment running ArangoDB

- [ ] 2.8
- [x ] 3.0.4
- [ ] self-compiled devel branch

On this operating system:

- [x ] Windows, version: 

applying a filter like _key==123 to a collection in the web interface in the collection view works well for the first page being shown. whenever trying to switch to another page the normal data set is shown again without the filter being applied.
reapplying the filter switches back to the first page of the filtered results.

**Comment by hkernbach** [comment]
Thanks for the report. It is fixed and will be included in 3.0.8 and 3.1.X.
