### ISSUE TITLE
 Inability to Set Custom Document Key in Clustered ArangoDB with Ceph and Java Client 7.1.0

### ISSUE THREAD

**Issue by gianluca-valentini** [arangodb/arangodb#20076]
**Issue Description:**
I encountered an issue when attempting to set a custom value as a document key for a document that is part of the shard key in a clustered ArangoDB environment (version 3.11.2) with Ceph storage. I was using the Java Client version 7.1.0. Upon making this attempt, I received the following error message: "com.arangodb.ArangoDBException: Response: 400, Error: 1222 - unexpected document key".

**Environment**:
ArangoDB Cluster: 3.11.2
Agents: 3
Coordinator: 4
Database: 4
Storage: Ceph
Deployed with Arango Operator
**Steps to Reproduce:**
Attempt to set a custom value as a document key using Java Client 7.1.0 in a clustered ArangoDB environment with Ceph storage.

**Expected Behavior:**
I would expect to be able to independently set the value of the document key.

**Actual Behavior:**
Observe the error message `com.arangodb.ArangoDBException: Response: 400, Error: 1222 - unexpected document key.`

Please let me know if you need further assistance with this issue.
Thanks
Gianluca

**Comment by dothebart** [comment]
Hi, 
If you want to use custom `_key` attributes you need to create the collection accordingly. 
This is a DDL-Decision that can only be taken upon collection creation.

**Comment by gianluca-valentini** [comment]
Ok @dothebart thanks for your answer.
Can you tell me how is possible to change thet configuration during collection create operation using java?
This is my collection info looking the ArangoDB console
![image](https://github.com/arangodb/arangodb/assets/3224592/8ca1e1b0-a225-4d1b-93d9-181ab6600419)

**Comment by dothebart** [comment]
Hi, please have a look at https://www.javadoc.io/static/com.arangodb/arangodb-java-driver/7.1.0/com/arangodb/model/CollectionCreateOptions.html#keyOptions(java.lang.Boolean,com.arangodb.entity.KeyType,java.lang.Integer,java.lang.Integer) - setting `keyOptions` does that.

**Comment by gianluca-valentini** [comment]
Thanks a lot
It works as expected. Is there any side effect using custom key in ArangoDB in cluster?

**Comment by dothebart** [comment]
you should see whether your data is well distributed. As usual its advised that you choose ~2 times the shard # than you run db-servers.

**Comment by gianluca-valentini** [comment]
Sure,
thanks a lot for your help

Gianluca
I will close the issue
