### ISSUE TITLE
Graph Data Modeling Using ArangoDB

### ISSUE THREAD

**Issue by namnik** [arangodb/arangodb#2010]
- [ ] 3.0
- [ ] Windows

I have a business that very similar with a part of Telegram App: 
multiple Users that have list of Contacts, and each user is member of multiple Group. each Group has a Admin , members.

part of my design:
a Doc Collection with Name **User**. a Edge Collection with name **Contact**( that two filed _from , _to fill out from User Id; for example  _from:User/1, _to:User/2).

**1. this design is correct?!**

**2. for Group, I need a Edge Collection or Doc Collection?** 
I was guess two solution:
-Group is a doc collection that had name and admin field. Group's Users also save as a array filed in Group Doc Coll...
- Group is a doc collection that had name and admin field. Group's Users save as a array filed in User Doc Coll...
which one? neither?!

I think I'm so confused about Graph data modeling! when and where use Edge Coll or Doc Coll?

my case similar below photo:

![222](https://cloud.githubusercontent.com/assets/13764362/17847095/6fcb8074-6861-11e6-9cd9-7148dc3e2dbb.PNG)

**Comment by dothebart** [comment]
We try to explain that in our documentation: https://docs.arangodb.com/3.0/Manual/Graphs/index.html

In general ArangoDB isn't as strict in what data you're able to attach to vertices and edges as other solutions in the field. Vertices is the name for the items that you call `doc col` - thus in graphs they're aliased Vertex Collections. In ArangoDB Edge collections are regular collections with the two mandatory `_from` and `_to` attributes. 

In a more traditional SQL way you would map m:n relations using pivot tables. You can think of edge collections as being similar. The edge usually is a relation between two objects. So if you have one collection of Users, and another collection of groups, you then would have an edge collections usersToGroups, in which you would have edges making the user a member of the group. Attributes to such an edge would i.e. be the privilege status in the group, the join date, etc. 

The group document would i.e. have the name attribute, maybe a group topic, things that are common to the group, and not to its individual members. 

Let me know if you like the explanations in the documentation, and if not what you've got problems with to comprehend from it.

**Comment by namnik** [comment]
@dothebart: with your comment with the documentation solved my problem.... thanks a lot

**Comment by Simran-B** [comment]
We added an example to the docs: https://github.com/arangodb/arangodb/commit/1c95b6829691f2a63e2ea8154b4b4c9caa1c097e
