### ISSUE TITLE
SEARCH alias in view query is not using index.

### ISSUE THREAD

**Issue by Koustav-1250** [arangodb/arangodb#20142]
My organisation is using ArangoDb collections and views. But getting slow queries.

Query:
FOR e IN inspection_view_asc filter  e.inspectionType IN [ "MRL", "MRL_PDI"] AND e.invalidated != true  and e.country == "IN" AND e.vehicleType == "CAR" AND e.locationCode IN ["IN_CAR_CC_243_SC_11"] AND e.data.inventoryStatus IN ["STOCK_IN"] and e.archived == "0"  SORT e.createdAt LIMIT 0, 20 RETURN {data:{derivedStatus:e.data.derivedStatus,additionalEstimatePDI:e.data.additionalEstimatePDI,diagnosticStatus:e.data.diagnosticStatus}}

below is my query. When I profiling this query it is not using any index.

I have created multiple indexes on the linked table.
<img width="1543" alt="Screenshot 2023-11-16 at 12 09 53 AM" src="https://github.com/arangodb/arangodb/assets/70643771/da37a5b6-f6c8-48fc-bafc-4249d060e04a">

Still it is not using any index.
<img width="1299" alt="Screenshot 2023-11-16 at 12 10 24 AM" src="https://github.com/arangodb/arangodb/assets/70643771/741e66db-f222-4375-bf0c-6fe49ab7a5e2">

don't know why?

Also the issue is I am trying to optimise the query.
When the above query is executed first time it is taking around 10-15 seconds, but after that it is taking time in ms. Don't know why. 

this is my view
```
{
    "writebufferSizeMax": 33554432,
    "writebufferIdle": 64,
    "consolidationIntervalMsec": 1000,
    "name": "inspection_view_asc",
    "type": "arangosearch",
    "consolidationPolicy": {
        "type": "tier",
        "segmentsBytesFloor": 2097152,
        "segmentsBytesMax": 5368709120,
        "segmentsMax": 10,
        "segmentsMin": 1,
        "minScore": 0
    },
    "writebufferActive": 0,
    "commitIntervalMsec": 1000,
    "links": {
        "inspection": {
            "analyzers": [
                "identity"
            ],
            "fields": {
                "attributes": {
                    "fields": {
                        "INSPECTION_TAG": {},
                        "REFURB_TYPE": {}
                    }
                },
                "reviewType": {},
                "appointmentId": {},
                "stage": {},
                "createdBy": {
                    "fields": {
                        "uid": {}
                    }
                },
                "invalidated": {},
                "locationCode": {},
                "inspectionType": {},
                "country": {},
                "registrationNumber": {},
                "reviewedBy": {
                    "fields": {
                        "uid": {}
                    }
                },
                "assignedTo": {
                    "fields": {
                        "uid": {}
                    }
                },
                "inspectionStatus": {},
                "poolType": {},
                "vehicleType": {},
                "inspectionSubType": {},
                "createdAt": {},
                "assigned": {},
                "archived": {},
                "data": {
                    "fields": {
                        "derivedStatus": {},
                        "additionalEstimatePDI": {},
                        "tag": {},
                        "inventoryStatus": {}
                    }
                }
            },
            "includeAllFields": false,
            "storeValues": "id",
            "trackListPositions": false
        }
    },
    "id": "378285290",
    "storedValues": [],
    "cleanupIntervalStep": 2,
    "globallyUniqueId": "c378285290/",
    "primarySort": [
        {
            "field": "createdAt",
            "asc": true
        }
    ],
    "primarySortCompression": "lz4"
}
```

**Comment by Koustav-1250** [comment]
This is the same issue #17221

**Comment by dothebart** [comment]
https://docs.arangodb.com/3.11/develop/http-api/views/arangosearch-views/ using the 'cached' property of our enterprise offering could offer a solution to this. 
With ArangoDB 3.12 more improvement in this direction are expected.
