### ISSUE TITLE
job.abort() - cannot convert object to primitive value

### ISSUE THREAD

**Issue by wizzl35** [arangodb/arangodb#2015]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [X] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [X] Linux 
  - [ ] Debian .deb
  - [X] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### Foxx-related issue

The documentation for [Scripts and queued jobs](https://docs.arangodb.com/3.0/Manual/Foxx/Scripts.html#aborting-a-job) on aborting a job shows a function ```abort()``` that should be available for a job instance.  When the function is called I get this stacktrace:
```
ArangoError 3103: failed to invoke module
File: /var/lib/arangodb3-apps/_db/brain/test_app/APP/scripts/setup.js
Cause: TypeError: Cannot convert object to primitive value
    at hasOwnProperty (native)
    at global.DEFINE_MODULE.exports.flatten (/usr/share/arangodb3/js/common/bootstrap/modules/internal.js:1493:39)
    at action (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/queues/index.js:195:29)
    at ArangoDatabase._executeTransaction (/usr/share/arangodb3/js/server/modules/@arangodb/arango-database.js:119:10)
    at Job.abort (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/queues/index.js:187:8)
    at Object.<anonymous> (/var/lib/arangodb3-apps/_db/brain/archive/APP/scripts/setup.js:48:6)
    at Module._compile (/usr/share/arangodb3/js/common/bootstrap/modules.js:593:6)
    at Object.Module._extensions..js (/usr/share/arangodb3/js/common/bootstrap/modules.js:613:10)
    at Module.load (/usr/share/arangodb3/js/common/bootstrap/modules.js:544:34)
    at FoxxService.run (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/service.js:397:12)
```

I am running the latest and greatest ArangoDB 3.0.5.

On a side-note, I am trying to abort very simple test scripts.  Only one is running while the rest are queued.  I cannot figure out how to cancel the scripts.  They run fine and complete via CLI calls.

Is there a way to cancel jobs or queues from arangosh?

Thanks for the help!

**Comment by wizzl35** [comment]
OK, things seem to work when I push a job with the same "mount" path as the service it is being called in.  I wasn't sure what that field meant so I gave a bogus mount.  Why does a job have to be associated with a specific Foxx app "mount" path?

**Comment by wizzl35** [comment]
I have the same problem for a job that throws errors or asserts false.  The job simply stays in "progress" forever.  The only solution I have found is to remove the job from the hidden _jobs collection.

This makes utilizing jobs and queues impossible since I need the jobs to fail if there is an error thrown.  I can write my scripts to handle expected errors gracefully, but I can't plan for the unexpected and have the in "progress" task block the rest of the queue.

**Comment by jsteemann** [comment]
Aborting jobs should now work in 3.0.6. Seems it has been fixed in the devel branch before already.

**Comment by wizzl35** [comment]
Awesome, Thanks! I assume that the failed jobs will also transition to the failed status on exceptions too.

**Comment by wizzl35** [comment]
Is there a timeline for 3.0.6 or a branch to checkout and build?

**Comment by jsteemann** [comment]
@wizzl35 : the idea is to start building the 3.0.6 release at the end of this week.
Until then, there is always the possiblity to build a 3.0 release manually using the `3.0` branch, but this requires checking out the ArangoDB source from Github and compiling everything on your own. That sounds a bit like overkill.

If waiting is not an option you may also locally patch the source file that was changed by the bugfix above:
https://github.com/arangodb/arangodb/commit/ea3961fe3884f6feb9ffe04092a47480cd5e674e
That local modification will become obsolete when 3.0.6 is released.
