### ISSUE TITLE
Query selected text in web interface

### ISSUE THREAD

**Issue by specimen151** [arangodb/arangodb#2017]
**Feature request**

In previous versions of the web interface (2.x series) one could select something in the query runner, and only run that.

This is very useful when experimenting with queries. Now I have to comment out code I don't want to run.

Would it be possible to implement this, or something else to make query experimentation easier (maybe tabs in the editor would be as good?)

**Comment by Simran-B** [comment]
Ctrl + Enter runs the whole code, but Ctrl + Alt + Enter runs just the selection. Ctrl + Shift + Enter explains the query.

**Comment by hkernbach** [comment]
Im not 100 percent sure if it is already in 1.0.5. But it will be definitely available in 3.1.

![image](https://cloud.githubusercontent.com/assets/1244163/17929940/13737aa8-6a04-11e6-9cd0-918b7281e3ad.png)

**Comment by specimen151** [comment]
Doesn't work for me at least on v 3.0.4.

I have an editor with two return statements, that's all.
When I run everything, of course I get an error.
When I select one of the statements, do ctrl-alt-return, nothing happens.

I'm using Chrome on Windows. Maybe something is grabbing the shortcut key.

**Comment by Simran-B** [comment]
It's this commit: https://github.com/arangodb/arangodb/commit/4f171936fac50da72e518e9d69641a20c7fafa34

I checked and it is not included in the v3.0.5 tag, so you will have to wait for 3.1 for this to become available. Until then, please use comments (`/*` and writing your to-be-run code above it works well, you don't have to close it) or saved queries.

**Comment by specimen151** [comment]
Thanks. Looking forward to that.
