### ISSUE TITLE
Distributed transactions

### ISSUE THREAD

**Issue by saviilsy** [arangodb/arangodb#2019]
Hi!

Older versions didn't support distributed transactions in clustered setup, now with 3.0.5 there is no mention of it in https://docs.arangodb.com/3.0/Manual/Transactions/Limitations.html . However there is a mention of it in roadmap. So are distributed transactions supported?

I'm mainly interested in ACID distributed transactions, not in performance enhancing features clustering might offer.

Thanks!

**Comment by dothebart** [comment]
Hi @saviilsy, we have updated the documentation accordingly.

**Comment by saviilsy** [comment]
Hi @dothepart, thanks for the update!

One question tho. If I don't shard a collection in cluster(i.e. use key/hash distribution) can I still do ACID multi document transaction in master to master manner?

Our primary focus is to provide load balancing (client can connect to multiple server with same data) and do a classic user to user credit transfer without sorting to multi phase commits other nosql solutions advertise. 

If not possible now, how far that feature is in Your dev pipeline?

**Comment by dothebart** [comment]
Yes, its on the roadmap, but I can't give any reasonable eta when it will be implemented.

**Comment by dsonet** [comment]
@saviilsy Just noticed that https://github.com/dgraph-io/dgraph providing ACID transactions... But I already built many services based on arangodb already.

**Comment by mikestaub** [comment]
@dothebart What is the status of this feature? Is it not needed for synchronizing between datacenters? FaunaDB are ramping up their marketing efforts in response to Oasis, and they are using this feature as a key differentiator, claiming ArangoDB cannot reach 'global scale'.

They are using this approach: http://www.cs.umd.edu/~abadi/papers/calvin-sigmod12.pdf

**Comment by graetzer** [comment]
perhaps have a look at https://www.arangodb.com/docs/stable/http/transaction-stream-transaction.html

**Comment by dothebart** [comment]
Closing as solved.
