### ISSUE TITLE
arangoimp --on-duplicate does not work!

### ISSUE THREAD

**Issue by limulimu** [arangodb/arangodb#2020]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [1 ] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [1 ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [1 ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ... root
3) use database [ ] `_system` [ ] other: 
4) click to ...
...

The following problem occurs: [Screenshot?] 
![image](https://cloud.githubusercontent.com/assets/2875995/17989877/efd7a3a0-6b73-11e6-92d9-fee4a890f2df.png)

When I use arangoimp to import data. If I use --on-duplication option, the value of on_duplication will go to the --type. And report --type error(update is not a type).
both 3.0.4 and 3.0.5 has this issue. 
Instead I would be expecting: 
I tried 2.8.x, this function works very well.

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

**Comment by Simran-B** [comment]
There's a typo in another parameter, `--create-collection ture`. It should
be `true`. Does that change the behavior?

**Comment by limulimu** [comment]
I don't think so. I get off this option and tried again.

2016年8月26日 上午10:22，"Simran" <notifications@github.com>写道：

**Comment by jsteemann** [comment]
This is a bug that we fixed this week in the 3.0 branch. The value for parameter `--on-duplicate` was assigned to wrong variable internally.
The fix will become available with 3.0.6.

**Comment by limulimu** [comment]
thanks very much

2016年8月26日 下午4:50，"Jan" <notifications@github.com>写道：

**Comment by jsteemann** [comment]
By the way, this is the commit containing the fix: d9b6786ea7caa02c138e378ffdf23742857042b3
