### ISSUE TITLE
Loosing vertex around?

### ISSUE THREAD

**Issue by MartinBrugnara** [arangodb/arangodb#2021]
__Versions:__
ArangoDB: 2.7.7
Gremlin: 2.6.0
blueprints-arangodb-graph: 1.0.14

I can not locate a vertex from within gremlin, which I can retrieve in the web GUI:

From the GUI I filter as:
![screen shot 2016-08-02 at 3 58 59 pm](https://cloud.githubusercontent.com/assets/2514272/17331167/13893532-58ca-11e6-894e-670fa21cb556.png)

From gremlin I query (searching by attribute wo/key) as:
```g.V.has('freebaseid', 68545795554948).next().id```

Raised exception:
```javax.script.ScriptException: com.tinkerpop.pipes.util.FastNoSuchElementException```

Full stack trace: http://pastebin.com/61iPnkBW

Relevant points:
```
13:32:19.129 [main] DEBUG com.arangodb.http.HttpManager - [REQ]http-POST: url=http://arango:8529/_api/cursor, headers=null, body={"count":false,"batchSize":20,"options":{},"query":"for i in GRAPH_VERTICES(@graphName , @vertexExample, @options) FILTER i.`freebaseid` \u00
3d\u003d @property0 return i","bindVars":{"property0":68545795554948,"vertexExample":{},"graphName":"mysuperdb","options":{"direction":"any","includeData":true}}}
```

```
com.arangodb.blueprints.client.ArangoDBException: org.apache.http.NoHttpResponseException: The target server failed to  respond
--- cut ---
Caused by: org.apache.http.NoHttpResponseException: The target server failed to respond
```

Could someone please help me figuring out what's happening here?

** Previously posted in [blueprints-arangodb-graph#25](https://github.com/arangodb/blueprints-arangodb-graph/issues/25]) ... 24 days of silence.

**Comment by a-brandt** [comment]
Problem fixed in version 1.0.15 of the blueprints-arangodb-graph driver.
