### ISSUE TITLE
Integrate on release tarball the 3drparty files

### ISSUE THREAD

**Issue by geaaru** [arangodb/arangodb#20213]
## My Environment

* __ArangoDB Version__:       >3.9
* __Operating System__:        Macaroni OS/Funtoo

__Problem__:

Starting from ArangoDB 3.9 (or maybe before or later) the Github tarball doesn't contain 3rdparty files. In contexts like Gentoo/Funtoo this is a bit complex because for security reasons the packages are compiled in a sandbox environment without direct access to Internet and the script using Git to fetch files must be managed differently.

Instead of generating distro-specific scripts that generate additional release tarballs about 3rdpary packages used in compilation could be good to have a complete release tarball will all files needed for compilation.

Do you think this review could be something supported by the ArangoDB team? This will help distro maintainers make the ArangoDB package available to other users in a faster way.

I'm the the creator of the Macaroni OS and I using ArangoDB in the Mottainai Server Opensource project. I really want to continue to support and improve the visibility of this cool database through our OS.

Thanks in advance for any feedback.

__Expected result__:

Release tarball ready for compilation.

**Comment by machak** [comment]
Beware that this project will is not really open source anymore: 

https://arangodb.com/2023/10/evolving-arangodbs-licensing-model-for-a-sustainable-future/

**Comment by geaaru** [comment]
License is not an issue. We have a license field in every package. We have other packages based on license key activation like Goland, etc. I can supply software that could be used after a support request to ArangoDB company or just use a limited version for Community.

**Comment by KVS85** [comment]
Hello @geaaru,

We do provide a separate tarball with `3rdparty` (and other submodules) sources included. You can download it at `https://download.arangodb.com/Source/ArangoDB-<VER>.tar.gz`, where a `<VER>` is `3.10.12`, `3.11.6`, etc.

Does this solve your issue?

**Comment by geaaru** [comment]
@KVS85 hi, thanks for your response. I checked the shared URL but I see tarball until 3.4.
The directory https://download.arangodb.com/Source/ is correctly indexed?
Is this correct?

**Comment by geaaru** [comment]
Well, it seems that it works so it's an issue of the page.
```
$ wget https://download.arangodb.com/Source/ArangoDB-3.10.12.tar.gz
--2024-01-20 21:40:17--  https://download.arangodb.com/Source/ArangoDB-3.10.12.tar.gz
Resolving download.arangodb.com... 104.26.0.87, 104.26.1.87, 172.67.74.126, ...
Connecting to download.arangodb.com|104.26.0.87|:443... connected.
HTTP request sent, awaiting response... 200 OK
```
So, this solves my issue. Thank you very much
