### ISSUE TITLE
Arangoimp not importing large json file (1M lines, 1.4G)

### ISSUE THREAD

**Issue by smith64fx** [arangodb/arangodb#2022]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [x] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [x] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [x] authentication is enabled?
- [ ] using the cluster?
- [x] _system database?

These are the steps to reproduce:
1) Go iniside the docker container
2) Run this command:
```
arangoimp --file /test/xas --batch-size 858993459200 --server.password xxx --collection test --create-collection true --log.level debug > impolog.log
```

The following problem occurs:
The last log I get is this:
```
2016-08-28T08:06:32Z [343] INFO processed 133754894 bytes (99%) of input file
```

Using log level 'debug' the last words I get are these:
```
2016-08-28T08:12:43Z [359] DEBUG connecting to ip endpoint 'http+tcp://127.0.0.1:8529'
```

Instead I would be expecting the message telling me what has been done: 
Importing a small file (1000 lines), I have no problems.

I get
```
2016-08-28T08:06:32Z [343] INFO processed 133754894 bytes (99%) of input file
created:          1000
warnings/errors:  0
updated/replaced: 0
ignored:          0
```

*Edit*
I found a way how it works. I just split the 1M lines file in 10 files à 100k lines.

**Comment by smith64fx** [comment]
I found the error in the logs... :)

```
2016-08-28T15:55:05Z [1] WARNING maximal body size is 536870912, request body size is 775072512
```

**Comment by smith64fx** [comment]
Can be closed

**Comment by jsteemann** [comment]
I think arangoimp will send a single batch containing all data because of the `batchSize` value of `858993459200` (858GB). Reducing this value or omitting it completely should fix it. 
But in addition, if there's a server-side limit of 512 MB for the request body, arangoimp should know about it and cap the batch size automatically.

**Comment by jsteemann** [comment]
arangoimp now caps the `--batch-size` to a value that the server will be able to handle.

**Comment by smith64fx** [comment]
@jsteemann Yes I think Arangoimp should check, if the server-side limit is exceeded and print an error message.

Thanks for your help!
