### ISSUE TITLE
create collection `replicationFactor` option in http 

### ISSUE THREAD

**Issue by ra0o0f** [arangodb/arangodb#2023]
Hi

`replicationFactor` is not mentioned in [http doc](https://docs.arangodb.com/3.0/HTTP/Collection/Creating.html) as in [javascript interface](https://docs.arangodb.com/3.0/Manual/DataModeling/Collections/DatabaseMethods.html).

and vice versa `indexBuckets` not specified in javascript interface

**Comment by jsteemann** [comment]
Thanks for letting us know. I have added the option to the docs.
