### ISSUE TITLE
Ubuntu ArangoDB Download/Install Issue?

### ISSUE THREAD

**Issue by clintwood** [arangodb/arangodb#2024]
No link or download instructions (wget, apt, etc.) on this page?
https://www.arangodb.com/download/ubuntu/

Also ```wget https://www.arangodb.com/repositories/arangodb3/xUbuntu_16.04/Release.key``` returns `403 Forbidden`

**Comment by Alternhuman** [comment]
Same problem here. Also tried [this link](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-arangodb-on-ubuntu-14-04), the repository also returns HTTP 403

**Comment by dothebart** [comment]
Yes, we're currently experiencing problems with our download section at arangodb.com, I'm researching.

**Comment by spoeck** [comment]
Also for this link:
`wget -O RPM-GPG-KEY-www.arangodb.org http://www.arangodb.org/repositories/PublicKey`

**Comment by dothebart** [comment]
Ok, after a lot of fiddling its fixed now. Thanks for reporting, everything should be working by now. If not, please comment.

**Comment by hacorbin** [comment]
This is happening again I am sorry to say.
