### ISSUE TITLE
.NET client documentation

### ISSUE THREAD

**Issue by ra0o0f** [arangodb/arangodb#2025]
Hi

I'm the author of [arangoclient.net](https://github.com/ra0o0f/arangoclient.net). I started to provide a documentation for the client. Since i tried to make the client API similar to the internal javascript interface i can use the docs from the official website. Which would be better, to copy the contents from javascript docs to .NET or refer a link to them?(in fact am i allow to copy them?)

**Comment by dothebart** [comment]
Hi, @ra0o0f, 
We typicaly strive to have a ten minutes for the drivers, i.e.: 
https://www.arangodb.com/tutorials/tutorial-php/

So the users get the broad overview in an acceptable timeframe. Something similar would be good for the arangoclient.net. The less creativity required, the good. So if you like to create your own, feel free to copy as much as possible.

The things you find under https://docs.arangodb.com/latest/ are generated from the Documentation/Books directory (see https://github.com/arangodb/arangodb/blob/devel/README_maintainers.md#documentation for more details, parts of it are autogenerated to ensure bitrot doesn't brake the examples...)  from the ArangoDB source repository, its under the same license as ArangoDB itself, the Apache 2.0 license, So you may freely use parts of it.

We maintain a directory structure on docs.arangodb.com  like that:

    latest/  -> points to the newest manual
    3.0/ -> points to the latest 3.0 release
    3.0.5 -> these are the generated files for this very version.

We have re-organized the manual with the 3.0 release so it now consists of 3 sub-gitbooks, So i.e. the HTTP interface, which is rather intended for driver developers like you, doesn't distract the normal users from the facts he should be primarily interested in. However, from now on the URLs should be stable.

So I think the prefered way is to reference the upstream documentation wherever it makes sense.

If you find information missing etc, feel free to send a PR with the changes. As for the whole rest of the ArangoDB repository, we require an Apache 2 CLA, which can be found here: https://www.arangodb.com/documents/cla.pdf

Also feel free to join our slack over at: https://slack.arangodb.com/ 
@Simran-B is in charge for our documentation, he can probably also give you good hints where to find what etc.

**Comment by ra0o0f** [comment]
@dothebart for the detailed response

im preparing the client for the v3.0 usage. after that i will provide a ten minute guide for starters
