### ISSUE TITLE
[3.x] Ubuntu apt update issue: Signature by key ... uses weak digest algorithm (SHA1) 

### ISSUE THREAD

**Issue by clintwood** [arangodb/arangodb#2031]
## my environment running ArangoDB

I'm using the latest ArangoDB of the respective release series:
- [x] 3.0

On this operating system:
- [x] Linux 
  - [x] Ubuntu .deb - Packages for Ubuntu 16.04: [Installation via Package Manager from here](https://www.arangodb.com/download/ubuntu/)  
### this is an installation/update related issue:

Steps to reproduce:

```
$ sudo apt update
$ ...
$ 12 packages can be upgraded etc...
$ W:  https://www.arangodb.com/repositories/arangodb3/xUbuntu_16.04/Release.gpg: Signature by key 4497DA50FBD0158CCFD1996CEE611E131C42E360 uses weak digest algorithm (SHA1)
```

This is causing the `PackageKit` service on my system to continuously retry the update.

[Edit] See: [Please note that we intend to shut off SHA1 completely on January 1](https://wiki.debian.org/Teams/Apt/Sha1Removal)

**Comment by dothebart** [comment]
we currently lean on the SuSE openbuild system for compiling the debs, so we can't change that for the time being.
With ArangoDB 3.1 we intend to use our own docker/jenkins based infrastructure. Up to date signatures etc. are for sure on the list of things to do.

**Comment by clintwood** [comment]
@dothebart, as per your milestone did this resolves in the the latest 3.1 drop?

**Comment by clintwood** [comment]
@dothebart, as per your milestone did this resolves in the the latest 3.1 drop?

**Comment by dothebart** [comment]
I've tried whether this is fixed by our own 4096 bit release key, but it seems that it doesn't fullfill these requirements. I will continue to research this in the next week; lots of old stuff is out there misguiding google..

**Comment by dothebart** [comment]
hm, our current signing key is `sub   rsa4096/115E1684` so its not DSA which would be completely unsupported. 

The `Release` file also contains SHA2 signatures; SHA1 only for backward compatibility:
```
Date: Thu, 03 Nov 2016 10:38:15 UTC
MD5Sum:
 7eccda03f3fb6cef16fd1dc1ff6fe1a1             2068 Packages
 85173c812018451ae5b9829226346066             1051 Packages.bz2
 55f2483c701453db4ee89e7f24adab23               36 Release
SHA1:
 a113ea9911d3e5873b5337506637085c630d0f64             2068 Packages
 3b658776cf11b91c19bd25ef3cd425ea7707d6cf             1051 Packages.bz2
 17c000291f8952a5b6d59e28f49a2918abe9966d               36 Release
SHA256:
 1eed26ec1b038abfa986be7a2ed3764a287d37a78169d3c0be218c0a4268153f             2068 Packages
 383a0e3b7773cdb6cb1c9caef4eb94caba2ce071101cdc2406bcab5ab674d592             1051 Packages.bz2
 8af85a6b4ad0cf64263f99403c8fecf4d226179c3b75223652ad8ece8df1152a               36 Release
SHA512:
 066833c0b754b954d95503d80a5c7c6d513ddba608f7064a378f0d079a29cce1d03760e50d5958ef9eda3a15d7c041c6526e626746b91b69b0096f9c042dde67             2068 Packages
 380ee185553e53ff1f90164e10b7017dfd348baca988a264abb1e68328b101912db5f11044871e7556fc71d924497b1df60d3eb6a982705d88828ce31713f95a             1051 Packages.bz2
 9dc7c9020b81201631762f350c200c103e6df0b2ad9bdcfcc9faa77404c49af1fb22f77ee8b383643e8265857cb99266140bbc1f4b6f48a2ee448ea848818496               36 Release
```

So I don't see why it should be complaining

**Comment by clintwood** [comment]
TBH, for 3.1 I just downloaded the deb and installed using `sudo dpkg --install <pkg-file>` to avoid this issue - so I cannot confirm whether this is still a problem!?

**Comment by dothebart** [comment]
ok, it seems as if setting the preferences of the key as described here: https://debian-administration.org/users/dkg/weblog/48 and re-creating the repo information fixes it. 

Can you retry and report back whether we can close this issue? 
(You probably already found the location of the arangodb 3.1 repositories is a different one?)

**Comment by clintwood** [comment]
Yes I see repo is different!  Working 100%!
Thank you for a great DB!
(FYI: I just followed the [instructions for Ubuntu 16.04 here](https://www.arangodb.com/download/ubuntu/)!)
