### ISSUE TITLE
URL in arangod.conf is invalid

### ISSUE THREAD

**Issue by Calrain** [arangodb/arangodb#2034]
## ArangoDB 3.0.5 on Ubuntu 16.0.4 LTS
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [x] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [x] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [x] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

The URL in the arangod.conf file contains a URL for the ArangoDB documentation and it is invalid:
https://docs.arangodb.com/ConfigureArango/

This link goes to a site that redirects to:
https://docs.arangodb.com/3.0/ConfigureArango/
The response is:
404 error: The requested URL /3.0/ConfigureArango/ was not found on this server.

**Comment by jsteemann** [comment]
Correct URL should be: https://docs.arangodb.com/Manual/Administration/Configuration/

**Comment by jsteemann** [comment]
Fixed links in example config files.
