### ISSUE TITLE
HTTP arangodb DB auth

### ISSUE THREAD

**Issue by diegogub** [arangodb/arangodb#2037]
Hello,
In HTTP endpoint: http://localhost:8529/_api/database/user
It only works without 401 response when user has r/w access on _system database.

Is that how is supposed to work? I guess it should show available databases for current user, not just for users that has _system access.

Regards,

**Comment by jsteemann** [comment]
The endpoint is supposed to return the list of databases the current HTTP user has access to. It is not required that the current user has access to the `_system` database.
However, the above URL will call the endpoint in the `_system` database (as no other database is provided in the URL so the default will be to use `_system`). That **will** require privileges for the `_system` database. If the user does not have such privileges, the response will be a 401.

It will work in any database the current HTTP user has privileges for, e.g. if he/she has privileges in database `mydb`, then calling `http://localhost:8529/_db/mydb/_api/database/user` will return the list of all databases for the user, including `mydb`.

**Comment by diegogub** [comment]
thanks @jsteemann , I will have to review how my golang drives do this.
Regards
