### ISSUE TITLE
insert an array of my model in Post api using foxx

### ISSUE THREAD

**Issue by namnik** [arangodb/arangodb#2038]
ver: 3.0.5
Hi.
I want to persist an array of my model to my Collection.

**my Model:**

> 'use strict';
> const joi = require('joi');
> const _ = require('lodash');
> exports.Model = {
>     schema: joi.object({
>     _key: joi.string().required(),
>     UserAppState: joi.number().required()
>   }).required(),
>   forClient (data) {
>     return _.omit(data, ['_id', '_rev']);
>   }
> };

**my main.js variables** 

> const users = module.context.collection('User');
> var UserModel = require("./models/user").Model,
>     joi = require('joi'),
>     userId = joi.string().description("The id of the User-Item");

**and post mehtod:**

> router.post('/users', function (req, res) {
>     res.json(users.save(req.body));
> }).body(UserModel);

above code fine worked for posting an item of my model.  but didn't wok for posting an array of my model. 
I use this code for posting the array, but didn't wok again!:

> router.post('/users', function (req, res) {
>   for (var data of req.body) {
>     res.json(users.save(data));
>   }
> }).body(UserModel);

....?

**Comment by namnik** [comment]
Can any one help me?! this question is critical for me! of course I know myself must be solve that!

**Comment by pluma** [comment]
You can simply wrap the Model in an array like so: `.body([UserModel])`. That tells Foxx you expect an array of them.

**Comment by namnik** [comment]
@pluma : thanks a lot for your comment. 
but when I change it, and send this array data:

> [
{"State":1, "_key":"1"},
{"State":1, "_key":"2"}
]

I got this error message: _**"request body must be an object"**_

also in web interface, Data Type of body set with value: 	**Array[undefined]**


....?

**Comment by pluma** [comment]
@namnik okay, that seems weird. Can you make sure `UserModel` actually has a value (i.e. add `console.log(UserModel)` after importing the `UserModel`)?

This should just work.

**Comment by pluma** [comment]
@namnik the issue has been addressed in the current devel and 3.0 branches and the fix will be in the upcoming 3.0.11 bugfix and 3.1.0 release. Could you try the development version and see whether the issue persists?

**Comment by pluma** [comment]
Released in 3.1.0
