### ISSUE TITLE
AragoError: stringification not supported for node type ternary

### ISSUE THREAD

**Issue by mrkvon** [arangodb/arangodb#2039]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.0 (3.0.5)

On this operating system:
- [x] Linux 
  - [x] Debian .deb

### this is an AQL-related issue:
[?] I'm using graph features (document & edge collections. are they defined as graph features?)

I'm issuing AQL via:
- [x] web interface with this browser:  Firefox 48.0.2  running on this OS: Arch Linux
- [x] this Driver: /arangodb/arangojs

I've clicked `Explain` in web interface and this is the error reported:

> Explain: stringification not supported for node type ternary (exception location: /usr/src/packages/BUILD/arangod/Aql/AstNode.cpp:2463). Please report this error to arangodb.com (while optimizing plan)

This query fails:
```
FOR usr IN users FILTER usr.username == "test2"
    FOR msg IN messages FILTER msg._from == usr._id || msg._to == usr._id
        LET otherUserId = msg._from == usr._id ? msg._to : msg._from
        //RETURN otherUserId
        FOR ousr IN users FILTER ousr._id == otherUserId
            RETURN ousr
```
And this one passes:
```
FOR usr IN users FILTER usr.username == "test2"
    FOR msg IN messages FILTER msg._from == usr._id || msg._to == usr._id
        LET otherUserId = msg._from == usr._id ? msg._to : msg._from
        RETURN otherUserId
        //FOR ousr IN users FILTER ousr._id == otherUserId
            //RETURN ousr
```
_Explanation: Message is an edge between two users. The one user is given and we want to return the other users (whether they are senders or receivers) (the real query is more complicated)_

The failing query passes in ArangoDB v3.0.1 on Arch Linux

The issue can be reproduced using this dataset:
https://gist.github.com/mrkvon/99aeff54543ef4037ee0a032563964db
(some sensitive history data deleted. it might have destroyed the dataset, but the example is pretty simple, so it should be easy to reproduce)

Is it a bug introduced in v3.0.5?

**Comment by dothebart** [comment]
3.0.10 is available for download now.
