### ISSUE TITLE
Segmentation Fault For Agency in 3.0.7

### ISSUE THREAD

**Issue by normanuber** [arangodb/arangodb#2040]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ X ] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ X ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

I just installed 3.0.7 over 3.0.3 and attempted to run the agency then ran into this segmentation fault (gdb output):
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffb1fff700 (LWP 30799)]
0x0000000000671795 in arangodb::consensus::Agent::sendAppendEntriesRPC(unsigned int) ()

and the trace log shows:
2016-09-08T05:18:04Z [31086] INFO In database '_system': Database is up-to-date (30007/standalone/existing)
2016-09-08T05:18:04Z [31086] TRACE leaving V8 context 0
2016-09-08T05:18:04Z [31086] TRACE returned dirty V8 context
2016-09-08T05:18:04Z [31086] TRACE finished database init/upgrade
2016-09-08T05:18:04Z [31086] TRACE registerTask for task 0x7f6ff7bb1c40 (Control-C)
Segmentation fault (core dumped)

Agency config is derived from here: https://gist.github.com/normanuber/9472203fea5a6254db994e70e20b02d0

**Comment by normanuber** [comment]
Hmm weird, I blew away my agency database (apps/db) and started it up again and looks like it is working. I guess something got corrupted.

**Comment by dothebart** [comment]
Hi, situations like this don't have to reappear always. Do you still have the coredump available? can you post the gdb output of `bt full`?

**Comment by normanuber** [comment]
If it happens again then I'll provide this info. Thanks though.
