### ISSUE TITLE
Adding extra layers of edges, need to rewrite all queries?

### ISSUE THREAD

**Issue by tthil** [arangodb/arangodb#2043]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [x] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [x] MacOS, version: 10.11.6

### this is an AQL-related issue:
[x] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser:     running on this OS: Mac OS 10.11.6
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS: MacOS 10.11.6
- [ ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click to ...
...

### this is an installation-related issue:

If I traverse a graph using a function like the one below and then I add another edge into the graph between level 1 and 6 so I should use 1..7 instead of 1..6 in my query. How could I prevent myself from rewriting all queries that use 1..6 to 1..7?

FOR vertex IN 1..6 OUTBOUND @vertex GRAPH @graph
    FILTER IS_SAME_COllECTION("roomConfigs", vertex) 
    RETURN vertex

**Comment by dothebart** [comment]
Maybe using bind variables? At the example from the documentation at
https://docs.arangodb.com/3.0/AQL/Graphs/Traversals.html :

    db._query("FOR v IN 1..@traversalDepth OUTBOUND 'circles/A' GRAPH 'traversalGraph' RETURN v._key", {traversalDepth: 3} );

**Comment by dothebart** [comment]
Since this question was answered, I will close this now. Feel free to comment if this doesn't answer your question.
