### ISSUE TITLE
Arangodb illegal instruction core dumped in VM or Docker in VM

### ISSUE THREAD

**Issue by undercover87** [arangodb/arangodb#20431]
## My Environment

* __ArangoDB Version__:         3.11.4-1 (virtualbox) or 3.8 (docker in virtualbox)
* __Deployment Mode__:       Single Server 
* __Deployment Strategy__:   Manual Start | Manual Start in Docker
* __Configuration__:               
* __Infrastructure__:               own
* __Operating System__:        Windows 10 Enterprise build 19.0.44 (host) Ubuntu 22.04 (virtualbox) 
* __Total RAM in your machine__:         8Gb.   (VM)
* __Disks in use__:        virtualbox
* __Used Package__:              Debian or Ubuntu .deb | Docker - official Docker library

## Component, Query & Data

__Affected feature__:
Installation |  arangosh | arangodb docker image init 

__AQL query (if applicable)__:
```


```
__AQL explain and/or profile (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. sudo apt-get upgrade (to upgrade arangodb3)
2.  OR
3. arangod OR arangosh
4. OR
5. starting the official arangodb docker image with docker-compose

__Problem__:

I'm getting an "illegal instruction - core dumped" whenever I try to use arangodb.
I have an Ubuntu 22.04 VM in virtualbox and I have arangodb 3.11.4-1 installed on the machine. Independently, inside the same VM,  I'm also creating a container from the official arangodb docker image version 3.8 in a docker compose scheme. 

Until some days ago, everything worked fine. Now the arangodb container won't start with message 
```
Initializing root user...Hang on...

Illegal instruction (core dumped)

Initializing database...Hang on...

ArangoDB didn't start correctly during init
```

Simply running arangosh or arangod  from the VM gives a similar message. 
Ubuntu gives the following details about the failure:

![image](https://github.com/arangodb/arangodb/assets/13225483/a41ce166-d8cd-4a2c-b1f2-0c5f64fe5b5b)

And trying to upgrade or install it from scratch produces the same. 

__Expected result__:

arangodb starts normally either on the VM or as a container.

**Comment by dothebart** [comment]
Hi, 
Please note that you need AVX and other more recent cpu features. 
You may need to configure virtualbox to pass along these instruction sets into the VM. 
you can check your host with `cat /proc/cpuinfo` (and the vm inside as well for sure) to revalidate this.

**Comment by undercover87** [comment]
Update: I'm not sure I will be able to deactivate hyper-v as I don't have full control over this PC. So, I don't think I'll be able to pass these instructions to virtualbox

In any case, do you have any ideas why it suddenly stopped working? and why it isn't working even for arango version 3.8
'

**Comment by dothebart** [comment]
With the release of ArangoDB 3.9 we enabled this in the compilers since by then processors with these features were over 10 years old. 
Hence you need these processor features enabled in order to use the ArangoDB pre-compiled binaries.

**Comment by dothebart** [comment]
Closing as "won't fix"
