### ISSUE TITLE
REGEX_REPLACE character classes not matching correctly

### ISSUE THREAD

**Issue by VerdantForge** [arangodb/arangodb#20475]
## My Environment

* __ArangoDB Version__:        3.11.6
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   ArangoDB Starter in Docker
* __Infrastructure__:               own
* __Operating System__:        Linux 5.15.0-89-generic \#99-Ubuntu SMP Mon Oct 30 20:42:41 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
* __Total RAM in your machine__:        15Gb
* __Used Package__:              Docker - official Docker library 

## Component, Query & Data

__Affected feature__:
AQL REGEX_REPLACE

__AQL query (if applicable)__:
```
RETURN REGEX_REPLACE("apples and oranges", "\s", "")
```

## Steps to reproduce

1. execute AQL query

__Problem__:

AQL Query
```
RETURN REGEX_REPLACE("apples and oranges", "\s", "")
```
returns `"apples and oranges"` instead of  expected `"applesandoranges"`

_Workaround_ using AQL Query
```
RETURN REGEX_REPLACE("apples and oranges", "[ ]", "")
```
returns the expected result `"applesandoranges"`

**Comment by machak** [comment]
I believe you need to escape slash..using: 
`RETURN REGEX_REPLACE("apples and oranges", "\\s", "")`
works...

**Comment by machak** [comment]
see: 
https://docs.arangodb.com/3.12/aql/functions/string/#regular-expression-syntax

**Comment by VerdantForge** [comment]
...Well not sure what I was thinking...
Thanks for pointing out my mistake!
Indeed that snippet works perfectly fine in my version as well.
