### ISSUE TITLE
Data of removed databases still lingers around...

### ISSUE THREAD

**Issue by frankmayer** [arangodb/arangodb#2047]
## my environment running ArangoDB

I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [*] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [*] Linux 
  - [ ] Debian .deb
  - [*] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

While doing some tests I noticed that I could find permission entries, in `_users` documents, for databases that had already been removed.

How to replicate this behavior:
1) Create a new database
2) Check a user's database permissions, the database-name is in the permission list
3) Delete the database
4) Check a user's database permissions again
Expected result: the removed database should not be in the permission list
Actual result: the name of the removed database is still there.

**Comment by jsteemann** [comment]
Confirmed.

**Comment by frankmayer** [comment]
FYI, this issue still persists with ArangoDB 3.2beta3. ;)

**Comment by jsteemann** [comment]
@frankmayer : I think the changes/fixes have been merged after the release of beta3, and will be contained in beta4.

**Comment by dothebart** [comment]
We're pleased to anounce that ArangoDB 3.2 containing this is now available for download - Closing.
