### ISSUE TITLE
Feature request: AQL `Array.join` function

### ISSUE THREAD

**Issue by andregs** [arangodb/arangodb#2048]
What about adding a dedicated `JOIN` function to AQL? It is the `SPLIT`'s (#1033) counterpart. 

I've defined it as a user function like this:
```javascript
var aqlFunctions = require('@arangodb/aql/functions');

aqlFunctions.register(
	'arr::join',
	String(function (arr, separator) {
		return arr.join(separator);
	}),
	true
);
```

**Comment by andregs** [comment]
Exactly! I was searching in Array Functions, I didn't realize this is a string function.

**Comment by dothebart** [comment]
I will add a link in the array functions over, since you're right, it should also occur there.

**Comment by Simran-B** [comment]
The changes can already be seen in the devel docs:
https://docs.arangodb.com/devel/AQL/Functions/Array.html
