### ISSUE TITLE
Web Interface: Collection-creation ignoring Journal Size setting

### ISSUE THREAD

**Issue by frankmayer** [arangodb/arangodb#2052]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [x] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [ ] Debian .deb
  - [x] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is a web interface-related issue:
I'm using the web interface with this browser: FF,Chrome    running on this OS: Ubuntu 16.04
- [ ] authentication is enabled?
- [ ] using the cluster?
- [x] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click to create a new collection
5) Set journalSize to any number except the default

The following problem occurs: the journalSize is not applied at creation time
Instead I would be expecting:  the journalSize to be applied at creation time

And indeed the journalSize parameter is missing in the request sent to the server.

**Comment by jsteemann** [comment]
Fixed in 3.0.8
