### ISSUE TITLE
PRUNE GRAPH NOT WORK WHEN USE CONDITION USES NEGATION

### ISSUE THREAD

**Issue by son2408** [arangodb/arangodb#20524]
## My Environment

* __ArangoDB Version__:        3.12.0-NIGHTLY.20231219
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Infrastructure__:               own 
* __Operating System__:        Windows 10
* __Total RAM in your machine__:        32Gb
* __Disks in use__:        SSD

## Component, Query & Data

__Affected feature__:
AQL query using web interface

__AQL query (if applicable)__:
```
for v, e, p in 0..2 outbound 'nodes/n_1' edges
  prune e.IsInherited == false  or e.IsInherited == null
return p
```
__Problem__:
Pruning always results in empty result set if condition uses negation. How to the above query work ?

__My Data_:
![image](https://github.com/arangodb/arangodb/assets/32300653/46a6c82a-46bb-418d-a484-bbde2f5c81ca)

I want return results that edge.IsInherited = true use PRUNE.

**Comment by jsteemann** [comment]
```
for v, e, p in 0..2 outbound 'nodes/n_1' edges 
  prune (e != null && (e.IsInherited == false or e.IsInherited == null))
  return p.edges
```
the PRUNE condition only prevents the traversal from descending deeper if the condition is true, but it does not filter out any edges for which the PRUNE condition is not true. If you want to filter these unwanted edges out as well, you can use
```
for v, e, p in 0..2 outbound 'nodes/n_1' edges 
  prune (e != null && (e.IsInherited == false or e.IsInherited == null))
  filter e.IsInherited == true 
  return p.edges
```

**Comment by son2408** [comment]
@jsteemann thanks you
