### ISSUE TITLE
Performance graph data with filter too slowly

### ISSUE THREAD

**Issue by son2408** [arangodb/arangodb#20532]
## My Environment

* __ArangoDB Version__:        3.12.0-NIGHTLY.20231219
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Infrastructure__:               own 
* __Operating System__:         Windows 10 
* __Total RAM in your machine__:        32Gb
* __Disks in use__:       SSD 

## Component, Query & Data

__Affected feature__: AQL query using web interface

__AQL query (if applicable)__:
```
for v,e,p in 0..3 outbound 'nodes/data' edges 
  filter v.name == 'td_1'
return p
```
__AQL explain and/or profile (if applicable)__:
```
Query String (81 chars, cacheable: false):
 for v,e,p in 0..3 outbound 'nodes/data' edges 
   filter v.name == 'td_1'
 return p

Execution plan:
 Id   NodeType        Calls   Par   Items   Filtered   Runtime [s]   Comment
  1   SingletonNode       1     -       1          0       0.00000   * ROOT
  2   TraversalNode       1     0       1    3089006      21.93566     - FOR v  /* vertex */, p  /* paths: vertices, edges */ IN 0..3  /* min..maxPathDepth */ OUTBOUND 'nodes/data' /* startnode */  edges /* order: dfs */
  5   ReturnNode          1     -       1          0       0.00000       - RETURN p

Indexes used:
 By   Name   Type   Collection   Unique   Sparse   Cache   Selectivity   Fields        Stored values   Ranges
  2   edge   edge   edges        false    false    false        0.00 %   [ `_from` ]   [  ]            base OUTBOUND

Traversals on graphs:
 Id  Depth  Vertex collections  Edge collections  Options                                              Filter / Prune Conditions
 2   0..3                       edges             uniqueVertices: none, uniqueEdges: path, order: dfs  FILTER (v.`name` == "td_1")

Optimization rules applied:
 Id   Rule Name                                  Id   Rule Name                         
  1   optimize-traversals                         3   remove-unnecessary-calculations-2 
  2   remove-filter-covered-by-traversal          4   async-prefetch                    

Query Statistics:
 Writes Exec      Writes Ign      Doc. Lookups      Scan Full      Scan Index      Cache Hits/Misses      Filtered      Peak Mem [b]      Exec Time [s]
           0               0                 0              0         6177018                  7 / 0       3089006         295600128           21.93601

Query Profile:
 Query Stage                Duration [s]         Query Stage                Duration [s]         Query Stage                Duration [s]
 initializing                    0.00000         loading collections             0.00003         instantiating executors         0.00005
 parsing                         0.00009         instantiating plan              0.00004         executing                      21.93571
 optimizing ast                  0.00000         optimizing plan                 0.00013         finalizing                      0.00004
```
__Dataset__:
Amount of nodes: 3.104.008
Amount of edges: 3.242.008

__Problem__:
I see graph traversal > 1M edges too slowly. How to search with a condition faster with graph > 1M edges ?. solr do it with 1s.
@jsteemann.

**Comment by son2408** [comment]
This is tree data for the above usecase.
![screenshot_1706150436](https://github.com/arangodb/arangodb/assets/32300653/783fffb8-efd0-46cc-92fd-75de4613f5fe)

**Comment by son2408** [comment]
@Redmen2679 I think ArangoDB must a Algorithmics Graph use index to filter nodes faster.

**Comment by Redmen2679** [comment]
Hello son2408,

Perhaps we can set up a call to discuss this in more detail?  One of my
Solution Architects would like to review this on a call with you if
possible.

Best Regards

Mark Hedderman
Vice President, Sales
Email: ***@***.***
Phone: +353 861701914

**Comment by son2408** [comment]
@jsteemann Do you any solution for this usecase ? thanks

**Comment by Redmen2679** [comment]
Hello son2408,

I do not have access to Yalo or Skype but could call you via Zoom?  Can you
send me your email address?

**Comment by son2408** [comment]
@Redmen2679 My email tranthaison2408@gmail.com. Can I chat with you to resolve it more conveniently for different time, plz? thanks you

**Comment by Redmen2679** [comment]
Richard

Can you organise a meeting here due to my travel commitments this week?

Thanks,

Mark

**Comment by son2408** [comment]
Hello @Redmen2679
I will describe full use case that i using graph ArangoDB is slowly, your team will suggest this ? or how do you want this meeting organise?
Thanks

**Comment by Redmen2679** [comment]
Hello @son2408

My colleague Richard in copy has emailed you (Gmail) trying to schedule a
meeting.  Can you check your Spam folder in case it ended up in your spam
folder?

Perhaps you can reply to Richard directly or here and between you both, a
meeting can be arranged.

Best Regards

Mark Hedderman
Vice President, Sales
Email: ***@***.***
Phone: +353 861701914

**Comment by son2408** [comment]
@Redmen2679 I only use version community. I'm testing on local and I see with usecase graph ArangoDB is too slowly.

**Comment by son2408** [comment]
@jsteemann Can you have any option for this usecase to speedup graph ? thanks you
