### ISSUE TITLE
Near with Subset of a Collection

### ISSUE THREAD

**Issue by bateramos** [arangodb/arangodb#2054]
Hello,

there is a way to call Geo function NEAR with a subset of a collection?
I filter my collection to find all documents with a specific criteria, and the last step should be get the nearest document, but the NEAR function don't accept the subset as a collection.

The Geo Index in Users is working fine on others AQL.

`
let originUser = Document(Users, @userId)
let book = Document(Books, @bookId)

let owners = (
    for user, own, path in INBOUND book Owns
        collect ownUser = user
        return ownUser
    )

return near(owners, originUser.location.latitude, originUser.location.longitude)
`

The error is: Query: invalid argument type in call to function 'NEAR()' (while executing)

**Comment by dothebart** [comment]
Hi, 
no, the geo functions can only work with whole collections. 
In doubt you may want to try [to join the results](https://docs.arangodb.com/3.0/AQL/Examples/Join.html); but you should compare the performance of all possible approaches.

**Comment by bateramos** [comment]
Hello,
Thanks for the response.
Besides using Joins (for on all the near Users and than try to filter on the owners of a specific title), there is another solutions?
I find strange that near only accepts collections and not subset of this collections. The data is not alter. Maybe this function cannot tell if the data I'm passing is a array of User.
I'm maybe asks too much, but it will be great if near would accept an parameter that tell the geo index attribute. This will not solve this out?

**Comment by dothebart** [comment]
Hi,
no currently there is no other way. 
You can however also do:

    FOR doc IN NEAR(...) FILTER doc.foo== bar RETURN doc

In future this may become more effective then it is in ArangoDB 3.0, but the Syntax will remain the same.

**Comment by bateramos** [comment]
Sorry for not responding earlier. Sometimes I do not receive the github notifications.
Ok, thanks for the heads up

**Comment by Simran-B** [comment]
Related request: #1700 - Geo location / index intersection
