### ISSUE TITLE
Arangodb not getting deployed on AWS EKS cluster though worked on local K8s cluster

### ISSUE THREAD

**Issue by piyushkumar13** [arangodb/arangodb#20558]
Hi,

I am trying to deploy Arangodb on aws EKS cluster by following instructions on this documentation : https://arangodb.github.io/kube-arangodb/docs/using-the-operator. I was unsuccessful to deploy it on aws EKS cluster. However, **deployment happened successfully on local K8s cluster**. 

**Local K8s cluster** : K3S version 1.28.4
**ArangoDeployment mode** : Cluster
**Kube-arangodb manifest version** : [1.2.37](https://github.com/arangodb/kube-arangodb/releases/tag/1.2.37) as well as [1.2.36](https://github.com/arangodb/kube-arangodb/releases/tag/1.2.36)
**Arangodb version** : 3.10.8
**AWS EKS Cluster version** : 1.26

I was getting **startup probe failure error** with connection refused when cluster coordinator pods were getting up. Attaching the snapshots : 
![Screenshot 2024-01-23 at 7 17 42 PM (1)](https://github.com/arangodb/arangodb/assets/13505531/8f31131c-1a7f-459c-9de1-b255cbd8f91a)

K8s services created while deploying the setup(attaching its snapshot)
![Screenshot 2024-01-23 at 7 18 24 PM (1)](https://github.com/arangodb/arangodb/assets/13505531/c573dd42-1add-4f96-a8df-aa006cdf86e5)

Note : I had tried with helm charts as well as K8s manifest files. Both resulted in the same error.

Please advise.

**Comment by dothebart** [comment]
Hi, 
currently supported ArangoDB versions include: 3.10.x, 3.11.x ; Somehow the versions you mention completely won't match this scheme?

**Comment by piyushkumar13** [comment]
@dothebart I was actually referring to kube-arangodb manifest version : https://github.com/arangodb/kube-arangodb/releases/tag/1.2.37 Let me edit.
Which uses 3.10.x for arangodb image.

**Comment by ajanikow** [comment]
Hello!

I do not think it is related to ArangoDB itself.

An issue like this happens when the ArangoDB Coordinator can't connect to the Agents/DBServers. Often, this issue is caused by DNS setup.

To check the issue - can you share logs from the Operator and Coordinator?

Best Regards,
Adam JAnikowski.

**Comment by piyushkumar13** [comment]
@ajanikow 
One of the error was 
`Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/usr/bin/arangodb_operator": stat /usr/bin/arangodb_operator: no such file or directory: unknown`

Another error was : 
`tcp 127.0.0.1:8529: connect: connection refused`

**Comment by ajanikow** [comment]
@piyushkumar13 First error is strange, it does not come from crdn pods. You probably have used arangodb image as the image for Operator installation via helm.

Second one is valid error - we just need Operator and CRDN logs to continue (20 last lines)

**Comment by piyushkumar13** [comment]
The issue is resolved. Seems like it was the access issue at my end. I had limited access on my EKS cluster, which resulted into few of the CRDs/deployments not working properly.

**Comment by dothebart** [comment]
Great, thanks for letting us know.
