### ISSUE TITLE
Very Slow Query when using LOWER( )

### ISSUE THREAD

**Issue by smith64fx** [arangodb/arangodb#2056]
## my environment running ArangoDB

I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [x] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [x] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:
### this is an AQL-related issue:

[ ] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser:     running on this OS: MacOSX
- [ ] arangosh
- [ ] this Driver:

I have a collection with 22 million documents. I also created a skip-list index for topic.labels.en.value.

This query is fast (0s)

```
FOR topic IN topics
  FILTER topic.labels.en.value == "Steve Jobs"
  RETURN {
    topic: topic
  }
```

But this query takes veeery long (I cancelled the query after some minutes)

```
FOR topic IN topics
  FILTER LOWER(topic.labels.en.value) == LOWER("Steve Jobs")
  RETURN {
    topic: topic
  }
```

Did I forget something?

**Comment by frankmayer** [comment]
Can you do an explain on both queries and post the result here?

**Comment by baslr** [comment]
```
FOR topic IN topics
  FILTER LOWER(topic.labels.en.value) == LOWER("Steve Jobs")
  RETURN {
    topic: topic
  }
```
will iterate over all 22m docs. since the comparison is done on the result of the lower() call.
If you want to have it indexed you have to add `topic.labels.en.valueLower` that represents the lower() version of topic.labels.en.value.

**Comment by Simran-B** [comment]
Related to #1501

**Comment by baslr** [comment]
Hi @smith64fx,

if you question was answered feel free to close this issue.
