### ISSUE TITLE
[AQL-Graph] Why default to 1 when minimal and maximal depth not specified?

### ISSUE THREAD

**Issue by clintwood** [arangodb/arangodb#2057]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.0

### this is an AQL-related issue:
- [x] I'm using graph features

### My Question
What was/is the rationale for setting the default to 1 if min..max is not specified in the following syntax?
```
FOR vertex[, edge[, path]]
  IN [min[..max]]
  OUTBOUND|INBOUND|ANY startVertex
  GRAPH graphName
  [OPTIONS options]
```
Does it not make more sense to leave the depth unbounded if min..max is not specified, or am I missing something?  Is there a way to specify min..max as unbounded?

**Comment by baslr** [comment]
This is because the default also acts as neighbors function.

Let it unbounded would be the same as iterate through the hole graph, this could be very time intensive and maybe block all other operations or worse. You can't set it to unbounded. You could set max to a really high value.

**Comment by clintwood** [comment]
Sure I understand the technical reasons, however, its is non-intuitive when not specifying a min..max value for it to have a default of 1 especially when there is no syntactic way to clearly indicate that it should unbounded.  It feels like not specifying a value should mean don't limit the depth.  Also, in most query languages not specifying a filter or limit of some kind very rarely (or never) limits the result set to 1 by default.  This is odd, however, I respect your choice here. You may close this issue if this would not change.  Thanks.

**Comment by dothebart** [comment]
Yes, you're right. Not specified is usually unlimited - in AQL too.
However, as @baslr said, unlimited iteration depth is dangerous. Since traversals build up huge result sets and may do so iteratively, this may kill your ArangoDB instance. 

So in this case we want the user to explicitely make up his mind how much data output he eventually wants to produce.

**Comment by dothebart** [comment]
As you requested, I will close this now.
