### ISSUE TITLE
edit _key attirbute 

### ISSUE THREAD

**Issue by namnik** [arangodb/arangodb#2058]
- [ ] 3.0.5

Hi dears,

can edit the **_key** attribute of a document in ArangoDB?

**Comment by baslr** [comment]
No, once created _key is not changeable. You have to duplicate the document with the desired _key and delete the old one.

**Comment by dothebart** [comment]
@namnik have a look at https://docs.arangodb.com/3.0/Manual/DataModeling/Documents/DocumentAddress.html
