### ISSUE TITLE
graph._neighbors() not working as intended

### ISSUE THREAD

**Issue by pc-lover** [arangodb/arangodb#2059]
## my environment running ArangoDB

I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [x] 3.0.7
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [x] Windows, version: 10
- [ ] MacOS, version:
### this is an AQL-related issue:
- [x] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [x] arangosh
- [ ] this Driver:

The issue can be reproduced using this dataset:

```
var graph_module = require("@arangodb/general-graph")
var graph = graph_module._create("graph")
graph._extendEdgeDefinitions({collection: "root_to_right", from: ["vertex_root"], to: ["vertex_right"]})
graph._extendEdgeDefinitions({collection: "right_to_right1", from: ["vertex_right"], to: ["vertex_right1"]})
graph._extendEdgeDefinitions({collection: "right1_to_right2", from: ["vertex_right1"], to: ["vertex_right2"]})
graph._extendEdgeDefinitions({collection: "root_to_left", from: ["vertex_root"], to: ["vertex_left"]})
graph._extendEdgeDefinitions({collection: "left_to_left1", from: ["vertex_left"], to: ["vertex_left1"]})
graph._extendEdgeDefinitions({collection: "left1_to_left2", from: ["vertex_left1"], to: ["vertex_left2"]})
graph.vertex_root.save({_key: "vertex_root"});
graph.vertex_right.save({_key: "vertex_right"});
graph.vertex_right1.save({_key: "vertex_right1"});
graph.vertex_right2.save({_key: "vertex_right2"});
graph.vertex_left.save({_key: "vertex_left"});
graph.vertex_left1.save({_key: "vertex_left1"});
graph.vertex_left2.save({_key: "vertex_left2"});
graph.root_to_right.save("vertex_root/vertex_root", "vertex_right/vertex_right", {_key: "root_to_right"})
graph.right_to_right1.save("vertex_right/vertex_right", "vertex_right1/vertex_right1", {_key: "right_to_right1"})
graph.right1_to_right2.save("vertex_right1/vertex_right1", "vertex_right2/vertex_right2", {_key: "right1_to_right2"})
graph.root_to_left.save("vertex_root/vertex_root", "vertex_left/vertex_left", {_key: "root_to_left"})
graph.left_to_left1.save("vertex_left/vertex_left", "vertex_left1/vertex_left1", {_key: "left_to_left1"})
graph.left1_to_left2.save("vertex_left1/vertex_left1", "vertex_left2/vertex_left2", {_key: "left1_to_left2"})
```

![arangodb](https://cloud.githubusercontent.com/assets/19520603/18619826/57e35c2c-7e30-11e6-9c0d-6ed5afa1802f.PNG)

These are the steps to reproduce:
1) connect to a database using arangosh
2) execute the above commands to create dataset
3) execute this command: `graph._neighbors("vertex_root/vertex_root", {maxDepth: 10})`

The above command would return the result:

```
[
  "vertex_right/vertex_right",
  "vertex_left/vertex_left",
  "vertex_right1/vertex_right1",
  "vertex_left1/vertex_left1"
]
```

Instead I would be expecting: 

```
[
  "vertex_right/vertex_right",
  "vertex_left/vertex_left",
  "vertex_right1/vertex_right1",
  "vertex_left1/vertex_left1"
  "vertex_right2/vertex_right2",
  "vertex_left2/vertex_left2"
]
```

`graph._neighbors("vertex_root/vertex_root", {maxDepth: 10, direction: "outbound"})` works well though

**Comment by pc-lover** [comment]
Btw, can someone explain to me how `edgeCollectionRestriction`  and `vertexCollectionRestriction` work?
It seems like if the both attributes is specified, then:
- each vertex in the result must have its collection in the `vertexCollectionRestriction`
- all the edges sit between each vertex in the result and the vertexExample (sepecified in the first parameter) must have their collections in `edgeCollectionRestriction`
Was I wrong or did I miss anything?

**Comment by pc-lover** [comment]
Any reason for that behavior?

**Comment by pc-lover** [comment]
@jsteemann Can you confirm if this is a bug?

**Comment by dothebart** [comment]
Hi, 
Sorry for comming back on this late. 
I've just tried your sample with ArangoDB 3.2.9 and the answer you provided as expected is returned.

So yes, if it didn't return it as you claim, this has been a bug, which has meanwhile been fixed.
