### ISSUE TITLE
Is support Auto increment for specifice attribute in ArnagoDB?

### ISSUE THREAD

**Issue by namnik** [arangodb/arangodb#2061]
- [ ] 3.0.5

I know that ArangoDB support Auto increment for system Attribute(_key or _id). but I want to use this feature for my ordinary attribute.

I read at [this link](https://github.com/arangodb/arangodb/issues/212) that:
Currently version(1.3) supports auto-generating values for _key only (and thus _id too because _id is derived from _key) ... It currently  is not possible to auto-generate any other attribute values with it.

in latest version of ArnagoDB(3.0.5) didn't support yet?

thanks a lot

**Comment by Simran-B** [comment]
Auto-increment is only available for the _key attribute. You can use AQL to increment a custom attribute however, I recently posted an example over here: https://github.com/arangodb/arangojs/issues/311#issuecomment-248370320

Can you tell more about what you want to achieve?
