### ISSUE TITLE
quering geographical polylines (question)

### ISSUE THREAD

**Issue by kkdd** [arangodb/arangodb#2063]
Hello,
##### this is a question:

Does Arangodb have a plan to have a functionality of quering geographical [polylines](https://en.wikipedia.org/wiki/Polyline)?
##### a background:

In our model of a road netowrk graph, where each edge correspods to a geographical polyline, we should search the nearest polyline from a given point.

**Comment by weinberger** [comment]
Hi,

It's on our list. ETA is hard to say now but I assume soon. It would be helpful to learn more about your use case. If it possible to tell us more ping me at claudius at arangodb.com, please. 

Claudius

**Comment by kkdd** [comment]
Thank your for your replay.
We would like to realize the fusion of optimized routing and map matching in a road netowrk on a graph database. Such fusion has already realized as a methodology of "[Matching GPS traces to a map](https://www.mapbox.com/blog/map-matching/)" in Mapbox blog, for example, but not on a graph database.

**Comment by maxkernbach** [comment]
This feature is implemented by the [**GEO_LINESTRING()**](https://docs.arangodb.com/3.4/AQL/Functions/Geo.html#geolinestring) and [**GEO_MULTILINESTRING()**](GEO_MULTILINESTRING()) functions in 3.4. It is possible to calculate a distance between two GeoJSON objects with [**GEO_DISTANCE()**](https://docs.arangodb.com/3.4/AQL/Functions/Geo.html#geodistance).

Please find the latest release in the [download section](https://www.arangodb.com/download/).
