### ISSUE TITLE
AQL query editor uses _system database

### ISSUE THREAD

**Issue by jsteemann** [arangodb/arangodb#2064]
## my environment running ArangoDB
- [ x ] self-compiled devel branch

### this is a web interface-related issue:
I'm using the web interface with this browser: Firefox    running on this OS: Ubuntu Linux
- [ x ] authentication is enabled?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as root
3) use database [ ] `_system` [ x ] other: any other than _system
4) click to "Queries"
5) issue the following query in the AQL query editor `FOR i IN 1..2000 RETURN i`

Inspecting the network traffic executed for this query, one can see that the original query request correctly goes to http://127.0.0.1:8529/_db/<whatever>/_api/cursor
However, when the web interface tries to delete the cursor on the server, it sends a request to http://127.0.0.1:8529/_api/cursor/<cursor-id>, which is lacking the correct database name. 
Thus deleting the cursor fails for all queries executed outside the _system database.

Fix: prefix URL correctly with database name.

**Comment by jsteemann** [comment]
Fixed in 3.0.9 and devel.

**Comment by dothebart** [comment]
3.0.10 is available for download now.
