### ISSUE TITLE
After updating to version 3.11.7 of Arango BD, the service is constantly restarting

### ISSUE THREAD

**Issue by DarkDeddok** [arangodb/arangodb#20658]
after updating to version 11 of Arango BD, the service is constantly restarting. almost nothing was changed in the settings, and it is impossible to fix the error. help me please

My Environment

ArangoDB Version: 3.11.7 
Storage Engine: RocksDB
Deployment Mode: Single Server
Deployment Strategy: ArangoDB Starter
Configuration: Single Master
Infrastructure: Dedicated
Operating System:Debian 12.2.0

My Conf File
# ArangoDB configuration file

[database]
directory = /var/lib/arangodb3

[server]
endpoint = tcp://0.0.0.0:8529
storage-engine = auto

authentication = true

statistics = true

uid = arangodb

[javascript]
startup-directory = /usr/share/arangodb3/js
app-path = /var/lib/arangodb3-apps

[foxx]

[log]
level = info
file = /var/log/arangodb3/arangod.log

[cluster]

[rocksdb]
block-cache-size = 45888063200
total-write-buffer-size = 45888063200
enforce-block-cache-size-limit = true

[cache]
size = 52443500800

[query]
memory-limit = 52443500800

Log

![image](https://github.com/arangodb/arangodb/assets/57879696/161cc532-ee43-47d8-9cb2-480919e7c7cc)

**Comment by MBkkt** [comment]
Hello, @DarkDeddok 

Can you run on machine after crash something like?
```
coredumpctl debug
frame 3
```

**Comment by dothebart** [comment]
Closing as abandoned.
