### ISSUE TITLE
AQL query editor results handling is odd

### ISSUE THREAD

**Issue by jsteemann** [arangodb/arangodb#2065]
## my environment running ArangoDB

I'm using the latest ArangoDB of the respective release series:
- [ x ] self-compiled devel branch
### this is a web interface-related issue:

I'm using the web interface with this browser: Firefox    running on this OS: Ubuntu Linux
- [ x ] authentication is enabled?
- [ x ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as root
3) use database [ x ] `_system` [ ] other: 
4) click to Queries

There issue the query `FOR i IN 1..10000 RETURN i` and select `1000 results` from the "number of results" select box. That sends a request to /_api/cursor with a `batchSize` value of `1000`. When selecting `2500 results` from the select box, it will send a `batchSize` value of 2500. When selecting `all results`, it will send a `batchSize` value of `1000000`. 

This is odd for the following reasons:
- the result may be bigger than 1M values, so using a `batchSize` value of `1000000` for `all results` may truncate the result
- whenever `all results` is used, the server will construct and send the entire result in one batch, as the client has requested via the `batchSize` value of 1M. While this may work, the cursor API should be used differently: one should use a small `batchSize` value (say 1000) and fetch the results incrementally from the server. The server provides the API PUT /_api/cursor/<cursor-id> to fetch _more_ results from a cursor. The client can query the cursor until it is fully exhausted. There is no need to tamper with arbitrary `batchSize` values on the client. The described method will work regardless of how big the results are.

**Comment by Simran-B** [comment]
I agree. I believe the 1M batch size is a workaround, because in some 2.x version "all results" actually returned 10K or something like that at most and it was unclear where this limit was added.

@hkernbach: do you remember our conversation about this? I can't find it on Slack.

**Comment by hkernbach** [comment]
Understood. Query View needs a little refactoring. Will try to fix this within the next few days.

**Comment by hkernbach** [comment]
Done. Now using cursor api properly.

**Comment by dothebart** [comment]
3.2 alpha 4 containing this bugfix is available for download now.
