### ISSUE TITLE
GEO_CONTAINS produces false results (inconsistent right-hand rule)

### ISSUE THREAD

**Issue by mdmm13** [arangodb/arangodb#20665]
## My Environment

* __ArangoDB Version__:        3.11.8
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start in Docker
* __Configuration__:               DEV
* __Infrastructure__:               VPS
* __Operating System__:        Ubuntu 20.04
* __Total RAM in your machine__:        16GB
* __Disks in use__:        SSD
* __Used Package__:              Docker official

## Component, Query & Data

__Affected feature__:
AQL GEO_CONTAINS

__AQL query (if applicable)__:
```
RETURN GEO_CONTAINS(GEO_POLYGON(@polygon), GEO_POINT(@latlon[1],@latlon[0]))
```
polygon1 =     `[[65.3703016,68.3299081],[-40.5075508,68.3299081],[-40.5075508,33.2186095],[65.3703016,33.2186095],[65.3703016,68.3299081]]` (slightly [bigger](https://www.keene.edu/campus/maps/tool/?coordinates=65.3703016%2C%2068.3299081%0A-40.5075508%2C%2068.3299081%0A-40.5075508%2C%2033.2186095%0A65.3703016%2C%2033.2186095%0A65.3703016%2C%2068.3299081))
polygon2 =     `[[60.5243298,66.8664746],[-36.0068898,66.8664746],[-36.0068898,34.3897546],[60.5243298,34.3897546],[60.5243298,66.8664746]]` (slightly [smaller](https://www.keene.edu/campus/maps/tool/?coordinates=60.5243298%2C%2066.8664746%0A-36.0068898%2C%2066.8664746%0A-36.0068898%2C%2034.3897546%0A60.5243298%2C%2034.3897546%0A60.5243298%2C%2066.8664746))
latlon = `[45.51395899156041,25.368316795985375]` (place in Romania)

__AQL explain and/or profile (if applicable)__: `polygon1`
```
Query String (76 chars, cacheable: true):
 RETURN GEO_CONTAINS(GEO_POLYGON(@polygon), GEO_POINT(@latlon[1],@latlon[0]))

Execution plan:
 Id   NodeType          Est.   Comment
  1   SingletonNode        1   * ROOT
  2   CalculationNode      1     - LET #0 = GEO_CONTAINS({ "type" : "Polygon", "coordinates" : [ [ [ 65.3703016, 68.3299081 ], [ -40.5075508, 68.3299081 ], [ -40.5075508, 33.2186095 ], [ 65.3703016, 33.2186095 ], [ 65.3703016, 68.3299081 ] ] ] }, GEO_POINT(25.368316795985375, 45.51395899156041))   /* simple expression */
  3   ReturnNode           1     - RETURN #0

Indexes used:
 none

Functions used:
 Name           Deterministic   Cacheable   Uses V8
 GEO_POINT      true            true        false  
 GEO_CONTAINS   true            true        false  

Optimization rules applied:
 none

43 rule(s) executed, 1 plan(s) created, peak mem [b]: 0, exec time [s]: 0.00029
```

__Dataset__:
See above.

__Size of your Dataset on disk__:
N/A

__Replication Factor & Number of Shards (Cluster only)__:
N/A

## Steps to reproduce

1. Run query with polygon1
2. Run query with polygon2

__Problem__:
Point is clearly contained in both polygons, yet GEO_CONTAINS returns `FALSE` for the lager polygon1.

__Expected result__:
Both should be `TRUE`.

__Incorrect fix__: Inverting polygon1 produces the correct result. There seems to be something wrong with the implementation of the right-hand rule.

**Comment by Simran-B** [comment]
This works as intended. You have to mind the geodesic lines, see 
https://docs.arangodb.com/stable/aql/functions/geo/#geojson-interpretation

The actual outlines of the polygons are as follows:

<img width="494" alt="image" src="https://github.com/arangodb/arangodb/assets/7819991/598b5cf2-e9ad-47c2-9994-521d4d98f305">

As you can see, the point is outside the "smaller" polygon:
<img width="168" alt="image" src="https://github.com/arangodb/arangodb/assets/7819991/77dbd208-0a80-423c-a2e9-c7621c77238e">

```
LET polygon1 = [[65.3703016,68.3299081],[-40.5075508,68.3299081],[-40.5075508,33.2186095],[65.3703016,33.2186095],[65.3703016,68.3299081]]
LET polygon2 = [[60.5243298,66.8664746],[-36.0068898,66.8664746],[-36.0068898,34.3897546],[60.5243298,34.3897546],[60.5243298,66.8664746]]
LET latlon = [45.51395899156041,25.368316795985375]
FOR elem IN [GEO_POLYGON(polygon1), GEO_POLYGON(polygon2), GEO_POINT(latlon[1], latlon[0])]
  RETURN elem
```

**Comment by mdmm13** [comment]
Thank you for the swift reply. 

I had no idea that (A) one could display maps in ArangoDB and (B) that ArangoDB was applying geodesic lines. This may be factually correct, but as your image shows, if you're trying to load markers within a visible area, the area you'd want is [this one](https://www.keene.edu/campus/maps/tool/?coordinates=65.3703016%2C%2068.3299081%0A-40.5075508%2C%2068.3299081%0A-40.5075508%2C%2033.2186095%0A65.3703016%2C%2033.2186095%0A65.3703016%2C%2068.3299081). 

I assume there's no built-in way around geodesic, is there?
