### ISSUE TITLE
AQL query editor should enable profiling

### ISSUE THREAD

**Issue by jsteemann** [arangodb/arangodb#2066]
The AQL query editor in the web interface shows the overall query execution time for each executed query.
This is good as a start, but it should be more detailed and explained. 

On the server side, the overall time can be broken up into individual components (e.g. "parsing", "optimizing" etc.). In order to do this, the client can send the "profile" options when issuing the query, e.g.

```
curl -X POST http://127.0.0.1:8529/_api/cursor --data '{"query":"FOR i IN 1..100 RETURN i","options":{"profile":true}}' 
```

The server response will then contain detailed execution times in the `profile` attribute in addition to the `executionTime` attribute:

```
"profile":{"initializing":1.2874603271484375e-5,"parsing":1.0704994201660156e-4,"optimizing ast":9.059906005859375e-6,"instantiating plan":8.702278137207031e-5,"optimizing plan":3.159046173095703e-4,"executing":2.689361572265625e-4}
```

The web interface could always request profiled queries, and display the detailed execution times on demand. It should hide them by default because in many situations they will be just noise to the user, but for power users they may be interesting.
Additionally there should be some explanation what the execution times mean (e.g. server-side execution times, not including network time, which may be significant from the client perspective). So please add some explanation somewhere (e.g. using a tooltip or something similar that is not obstructive).

**Comment by Simran-B** [comment]
Maybe something like this?

![image](https://cloud.githubusercontent.com/assets/7819991/18710949/042454ae-8008-11e6-902d-159e7cdfdd83.png)

**Comment by jsteemann** [comment]
@Simran-B : looks good to me!

**Comment by baslr** [comment]
Can we please change the timing to ms? Queries should exec in ms not secs ;)

**Comment by hkernbach** [comment]
ArangoDB 3.1 has been released. Please note that the download urls and repositories have changed slightly. 

[Download](https://www.arangodb.com/download) or see [Release Notes](https://docs.arangodb.com/3.1/Manual/ReleaseNotes/NewFeatures31.html) for details.
