### ISSUE TITLE
Q: collections option for /_api/transaction call

### ISSUE THREAD

**Issue by baslr** [arangodb/arangodb#2068]
from the docs https://docs.arangodb.com/3.0/HTTP/Transaction/index.html
`collections: contains the array of collections to be used in the transaction (mandatory). collections must be a JSON object that can have the optional sub-attributes read and write. read and write must each be either arrays of collections names or strings with a single collection name.`
when I try it with the array

```
{
  "action": "function action(params) {\n    const db = require('@arangodb').db;\n    db.test.save({x:42});\n}",
  "collections": [
    "test"
  ]
}
```

I get

```
{
  "exception": "ArangoError 1652: unregistered collection used in transaction: test [write]",
  "stacktrace": [
    "ArangoError: unregistered collection used in transaction: test [write]",
    "    at Error (native)",
    "    at action (eval at post_api_transaction (js/actions/api-transaction.js:45:41), <anonymous>:5:13)",
    "    at eval (eval at post_api_transaction (js/actions/api-transaction.js:45:41), <anonymous>:6:3)",
    "    at post_api_transaction (js/actions/api-transaction.js:49:16)",
    "    at Function.actions.defineHttp.callback (js/actions/api-transaction.js:66:11)"
  ],
  "message": "unregistered collection used in transaction: test [write]",
  "error": true,
  "code": 400,
  "errorNum": 1652,
  "errorMessage": "unregistered collection used in transaction: test [write]"
}
```

So I assume array only without read / write is not supported?

**Comment by CoDEmanX** [comment]
The documentation can be interpreted in two ways I guess:

- `collections` can be an array of strings
- it can be an object with the attributes read and write, each an array of strings

I can't recall if an older version of Arango allowed an array and used the names given as write-collections. If so, then this might be a regression of #1954 / #1967. Otherwise we should change the first sentence to "contains the collections to be used in the transaction".

**Comment by jsteemann** [comment]
> collections must be a JSON object that can have the optional sub-attributes read and write. read and write must each be either arrays of collections names or strings with a single collection name.

I think the above is almost correct:
* "collections" must be a JSON object
* "read" and "write" are optional sub-attributes
* when "read" or "write" (or both) are specified, their values must be either arrays of collection names or strings with a single collection name

That means the following will work:
* `"collections":{}`
* `"collections":{"read":"test"}`
* `"collections":{"read":[]}`
* `"collections":{"read":["test"]}`
* `"collections":{"read":["test"],"write":["foo","bar"]}`
* `"collections":{"read":"foo","write":"bar"}`
...

It is not supported to directly specify the collection name (or names) inside the "collections" attribute as then it would be unclear whether read or write access is required.

**Comment by jsteemann** [comment]
@CoDEmanX @baslr : any progress on this? Does the documentation still need to be adjusted or can the issue be closed?

**Comment by Simran-B** [comment]
Got side-tracked by #1954 / #1967 back then, changed it to the following now (098564f20c0b4e3e22c58b33ce66f57d5febfeea):

> *collections* must be a JSON object that can have either or both sub-attributes
> *read* and *write*, each being an array of collection names or a single
> collection name as string. Collections that will be written to in the
> transaction must be declared with the *write* attribute or it will fail,
> whereas non-declared collections from which is solely read will be added lazily.
> The optional sub-attribute *allowImplicit* can be set to *false* to let
> transactions fail in case of undeclared collections for reading. Collections
> for reading should be fully declared if possible, to avoid deadlocks.
