### ISSUE TITLE
Add ArangoDB to travis-ci so that ci tests can be written for APIs

### ISSUE THREAD

**Issue by frankmayer** [arangodb/arangodb#207]
As the title says, for being able to write and run ci-tests for the APIs, it would be nice to add ArangoDB to travis-ci like other databases have been added, too. --> http ://about.travis-ci.org/docs/user/database-setup/

Also, Is it possible to have different versions of AramgoDB to test against? Say 1.0, 1.1, 1.2, 2.0, etc...

**Comment by nharris85** [comment]
If you're like me and coming to this just over 2 years later, you'll notice that this script no longer works with the latest version. See updated script below. Another thing that I got hung up on being new to travis-ci was how to actually run this script. It's not hard but for some reason google wasn't giving me a clear answer. Just add a "before_install" hook to your .travis.yml file and have it run "sh arangodb.sh".

```
#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

VERSION=2.8.3
NAME=ArangoDB-$VERSION

if [ ! -d "$DIR/$NAME" ]; then
  # download ArangoDB
  wget https://www.arangodb.com/repositories/travisCI/$NAME.tar.gz
  tar zxf $NAME.tar.gz
fi

PID=$(echo $PPID)
TMP_DIR="/tmp/arangodb.$PID"
PID_FILE="/tmp/arangodb.$PID.pid"
ARANGODB_DIR="$DIR/$NAME"

# create database directory
mkdir ${TMP_DIR}

${ARANGODB_DIR}/bin/arangod \
    --database.directory ${TMP_DIR}  \
    --log.file ${TMP_DIR}/${NAME}.log \
    --configuration none  \
    --server.endpoint tcp://127.0.0.1:8529 \
    --javascript.startup-directory ${ARANGODB_DIR}/js \
    --javascript.app-path ${TMP_DIR}/${NAME}/apps \
    --database.maximal-journal-size 1048576  \
    --server.disable-authentication true \
    --javascript.gc-interval 1 &

echo "Waiting until ArangoDB is ready on port 8529"
while [[ -z `curl -s 'http://127.0.0.1:8529/_api/version' ` ]] ; do
  echo -n "."
  sleep 2s
done

echo "ArangoDB is up"
```

**Comment by jsteemann** [comment]
note that the current version of the travis script is available [here](http://arangodb.com/repositories/travisCI/setup_arangodb_2.8.sh) and the scripts for other branches are [here](http://arangodb.com/repositories/travisCI/).

**Comment by nharris85** [comment]
Brilliant! I guess I should have just asked instead of figuring it out myself. Thanks @jsteemann!

**Comment by nharris85** [comment]
I just updated my project to use this script and it is throwing an error at the end. The DB starts up but the error is killing the travis build. 

Error:
/dev/fd/63: 54: /dev/fd/63: Syntax error: word unexpected (expecting ")")

**Comment by jsteemann** [comment]
Are you sure the error is caused by the startup script? Can you supply the link to the travis build output?

**Comment by nharris85** [comment]
My previous script worked with the build and when I changed to this one it failed. Here is the travis build.

https://travis-ci.org/nharris85/node_acl_arangodb/builds/112069056

**Comment by nharris85** [comment]
I thought maybe it was because I moved the script to the before_script phase instead of before_install but it still errors. It has a slightly different error message when executed in the before_install phase.

https://travis-ci.org/nharris85/node_acl_arangodb/builds/112079067

**Comment by nharris85** [comment]
So it definitely doesn't like before_script phase. My original script didn't work when executing there but it does in before_install. But the official one doesn't work in either phase for me. It is definitely something to do with the script or how I'm executing it.

**Comment by jsteemann** [comment]
I saw you're executing the script like this in your TravisCI build:
```bash
sh <(curl -s http://arangodb.com/repositories/travisCI/setup_arangodb_2.8.sh)
```
This will not work. If you do it like this, then ArangoDB is downloaded and started in a sub-shell. This sub-shell will be closed when the setup_arangodb_2.8.sh finishes, so ArangoDB will be terminated before the actual tests start.

What I always did and what seemed to work fine so far was to do the ArangoDB installation in the `before_script` phase like this:
```
before_script:
  - chmod a+x ./tests/travis/setup_arangodb.sh
  - ./tests/travis/setup_arangodb.sh
```
Of course that requires the script to be present locally, but you could either add it to your repository or download it with curl.

**Comment by nharris85** [comment]
Thanks @jsteemann this worked for me.

**Comment by brennv** [comment]
Created a repo for travis integration examples [here](https://github.com/brennv/arangodb-travis)

**Comment by weinberger** [comment]
Great, thanks!


Am 19. Juli 2016 um 01:06:06, Vincello Brennan (notifications@github.com)
schrieb:

Created a repo for travis integration examples here
<https://github.com/brennv/arangodb-travis>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/arangodb/arangodb/issues/207#issuecomment-233560046>,
or mute the thread

**Comment by dothebart** [comment]
Since nowadays one should use the arangodb docker container to set up travisci, and the above comments point into long dead parts of the homepage, I Will edit all these comments and destroy all links.

for implementations about howto integrate the docker containers please have a look at: 
https://github.com/arangodb/arangodb-php/blob/devel/.travis.yml
https://github.com/arangodb/arangodb-php/blob/devel/tests/travis/setup_arangodb.sh
