### ISSUE TITLE
System error on simple query

### ISSUE THREAD

**Issue by DeShadow** [arangodb/arangodb#2070]
I have issue with my simple query on ArangoDB v3.0.8 on MacOS and Ubuntu

I have very simple query
```
for user in users
    let isColleague = (user.company == @company)
    filter  isColleague 
    return { user, isColleague }
```

Also i have hash index on field 'company' of collection 'users'

The execution in web interface show error:
```
Query: missing variable #1 (isColleague) for node CalculationNode while planning registers (exception location: /usr/src/packages/BUILD/arangod/Aql/ExecutionNode.cpp:1163). Please report this error to arangodb.com (while executing) (exception location: /usr/src/packages/BUILD/arangod/RestHandler/RestCursorHandler.cpp:129). Please report this error to arangodb.com
```

The explain show error too:
```
Explain: missing variable #1 (isColleague) for node CalculationNode while planning registers (exception location: /usr/src/packages/BUILD/arangod/Aql/ExecutionNode.cpp:1163). Please report this error to arangodb.com (while finalizing)
```

I have this error on both server: development on my MacOS and test on Ubuntu 14.04.
But i think that problem is not in OS.

**Comment by jsteemann** [comment]
Fixed in 3.0.10.
As a temporary workaround until 3.0.10 is available, you may repeat the `isColleague` predicate expression in the query:
```
FOR user IN users     
  FILTER user.company == @company    
  RETURN { user, isColleague : user.company == @company }
```
That will work in all versions and use the index. From 3.0.10 on, you can also use the following query, which will
```
FOR user IN users
  LET isColleague = user.company == @company
  FILTER isColleague 
  RETURN { user, isColleague }
```

**Comment by jsteemann** [comment]
For reference: the error only occurred when an index was present, the FILTER condition was just a simple variable reference and the variable used in the FILTER condition was also used after the FILTER. The optimizer was overambitious here and optimized away the variable used by the FILTER condition, and did not check if it was used later (as in the RETURN part of the query that failed).

**Comment by DeShadow** [comment]
@jsteemann Thank you very much for this explain! :)
I thought that problem in optimizer and removing of variable before needed.  👍

**Comment by dothebart** [comment]
3.0.10 is available for download now.

**Comment by DeShadow** [comment]
@dothebart Yeah! I have already checked that it's fixed!
