### ISSUE TITLE
[Feature Request] Binary transport protocol

### ISSUE THREAD

**Issue by ShadauxCat** [arangodb/arangodb#2073]
I really like a lot of things about Arango, but there's one thing I really, really, REALLY want to see in it before I can even consider employing it in some of the places I'd like to... A binary transport protocol.

Now that VelocyPack is integrated it seems like it would be reasonable to expose an API to directly send data over the web in that format. The main impetus for this, for me, is two fold:

1) Writing extremely high-performance applications in C++, I would really like to be able to copy my binary data (particularly numeric data) directly into or out of the message without having to deal with the cost of a conversion to/from a string.

2) Even more important than the first to me, floating point data conversion to and from string results in a loss of accuracy. Storing lots of floating point data, if the same value is written to string and read from it over and over again, it can result in a new value every time the format changes. Encoding floating point data in base64 or similar is an option in theory, but in practice that adds another layer of string conversions. Having an option to just send the floating point values as part of a binary message would alleviate this problem.

Fortunately for the case I'm using right now this isn't very important, since neither nanosecond performance nor floating point accuracy are major concerns for my current use - but the lack of a binary transport has been enough to make me pass over arango as an option for a previous project. And I foresee a lot of future cases where arango would be ideal for me, except that the problems above will end up being... well, problems.

Seems like this is something that could be done over REST by just specifying Content-Type as `application/octet-stream`.

**Comment by jsteemann** [comment]
@ShadauxCat : in the devel branch we now have a binary protocol in place as an alternative to the existing HTTP API. That binary protocol is still under development, but first internal tests have shown it already improves the request/response performance quite a bit. More details will follow once the binary protocol API becomes part of an official ArangoDB release.

**Comment by ShadauxCat** [comment]
Ah! Awesome! Great to hear!

**Comment by baslr** [comment]
Hi @ShadauxCat,

ArangoDB 3.1 was now released with velocypack over http and a new protocol called velocitystream.

To use velocypack over http you just need to add the header `Accept / Content-Type` `application/x-velocypack`

#2123

**Comment by dothebart** [comment]
Exactly. ;-)
