### ISSUE TITLE
Enhancement Request - AQL editor on ArangoDB web portal

### ISSUE THREAD

**Issue by Calrain** [arangodb/arangodb#2075]
## my environment running ArangoDB

I'm using the latest ArangoDB of the respective release series:
- [x] 3.0

On this operating system:
- [x] Linux 
  - [x] Ubuntu .deb

I'm issuing AQL via:
- [x] web interface with this browser:     running on this OS: Windows

There are a number of features that were added to the ArangoDB Web Interface for editing AQL queries, but some of the changes have made the AQL editor for 3.x harder to use than the 2.x version.

Issue 1: Dynamic bindVars manipulation
If you have a large AQL query you are working on, with lots of bindVars set and populated, and then from an external tool (such as notepad) you paste in the same AQL query over the old one, you lose all bindVars.
It seems that every time you PASTE or EDIT the AQL query, the bindVars are re-evaluated, and existing values are lost.
This means you have to constantly have an instance of Notepad open on the side with a copy of the BindVars and their values, so you can paste them back in after you paste all of the AQL in.
Can be a bit time waster if you forget to copy out your bindVars.

A solution proposal: 
Please re-engineer how bind variables are shown.
As you type a new bind variable, it should appear in the list as it does now, with a blank box beside it.
If a bind variable is saved (with or without a value) but no longer seen in the AQL query, it should grey/disable the entry and not delete it.
If a bind variable is seen to exist again, it should be re-enabled and the original value available again.
Only the enabled bind variables should be sent through to the server when the AQL query is executed, no need to send disabled but saved bind variables.
If you cut/paste the AQL query, the bind variables would not delete and come back empty, rather they would all disabled, then re-enable, meaning the user didn't lose the values.

Issue 2: Unable to run hightlighted AQL code.
With 2.x it was possible to highlight a small amount of AQL code and click 'execute' and only the highlighted code would run. This was very useful if you wanted to test out the contents of a LET x = (..) without invoking the full query.
With 3.x the only way to do this is:
- View bindVars as JSON, copy them to an instance of notepad
- Copy all AQL to a second instance of Notepad
- Delete the parts of the AQL query you don't want to run
- Run the small part
- Paste back in the AQL query
- Paste back in the bindVars

A solution proposal:
Please re-enable the ability to highlight and execute a portion of AQL without running the rest on the page.
If a user highlights AQL then re-evaluate the bind variables list to enable/disable bind variables related to the highlighted text. So if someone highlights AQL code that has no bind vars in it, then all bind vars are disabled. If you highlight AQL code with some bind vars in it, then those are enabled and the rest are disabled.
This ties into the recommended solution for Issue 1.

I know the recommendation is to use "Save Query" but that brings me on to issue #3.

Issue 3: Inability to see currently saved query names when saving a query
If you want to quickly save a query, there is no way of easily seeing the list of existing saved queries and choosing to overwrite an existing one.
You have to remember a name and type it in for it to be replaced.
This ends up in having queries saved like temp1, temp2, temp3 etc. and you don't know what the purpose of the query was.
You don't name queries better names like "Dynamic Query - Testing without using ZIP" because it's too hard to type that name in again to overwrite it.
So rather than using the save feature, I find myself using an external editor to save queries into, selectively pasting back into the web AQL editor the parts of the query you want to use.

A solution proposal:
Please show the name of the saved query when you load it, when editing a loaded query it doesn't say the name of the loaded query anywhere on the screen.
Please pre-populate the name of the saved query in the dialog box when you try to save it again.
Please have a smart dialog box with the save query dialog where you can either type a new name or pick from any existing name to overwrite it.

These aren't big issues, but I'm finding the issues around how bind variables update and the inability to run highlighed AQL code is really impacting my performance. I was faster with the 2.x interface and would love to see the 3.x interface get these features back.

Thanks for your time!

Edit: fixed formatting

**Comment by hkernbach** [comment]
First of all, thank you for your detailed issue!

Issue 1: Fixed in devel. 
If a bind parameter is removed during editing and reappears, the editor fills the last saved attribute value automatically (if available). 

Issue 2: Fixed in devel.
You will be able to run selected parts of a query by pressing: Ctrl/Cmd + Alt + Return.

Issue 3: Fixed in devel.
The view is now showing the current query name. Also we've added a new button to save the current query in addition to the old way. 

Fixes Nr. 1-3 will be available in the upcoming 3.1 release.

**Comment by Calrain** [comment]
Wow, that will be fantastic, thanks so much for considering the request.
I look forward to the 3.1 release!
Cheers!

**Comment by DeShadow** [comment]
@hkernbach And is possible can you add next improvement. When you try in query builder run or explain the query with syntax error the page scrolls smooth to result. But there is no result, because the error is occured. :) And this scrolling movement is not desired. :)

**Comment by hkernbach** [comment]
@DeShadow Also done. Thanks!

**Comment by hkernbach** [comment]
ArangoDB 3.1 has been released. Please note that the download urls and repositories have changed slightly. 

[Download](https://www.arangodb.com/download) or see [Release Notes](https://docs.arangodb.com/3.1/Manual/ReleaseNotes/NewFeatures31.html) for details.
