### ISSUE TITLE
[Optimize graph traversal] How to skip startVertexs that exist in the previous graph traversal results.

### ISSUE THREAD

**Issue by son2408** [arangodb/arangodb#20776]
## My Environment

* __ArangoDB Version__:        3.11.8
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Infrastructure__:               own 
* __Operating System__:        Windows 10
* __Total RAM in your machine__:       32Gb
* __Disks in use__:        SSD

## Component, Query & Data

__Affected feature__:
AQL query using web interface

__AQL query (if applicable)__:
```
FOR node IN ['documents/n0', 'documents/n2']
    FOR v,e IN 0..10 OUTBOUND node relationships
    RETURN v
```

__Problem__:
if I graph traversal with startVertex 'documents/n0', then the result returns ['documents/n0', 'documents/n1','documents/n2', 'documents/n3', 'documents/n4']. After with StartVertex is 'documents/n2', it return ['documents/n2', 'documents/n3', 'documents/n4']. I see path of  StartVertex 'documents/n2' happened with startVertex 'documents/n0'
__Expected result__:
I expect the result returns ['documents/n0', 'documents/n1','documents/n2', 'documents/n3', 'documents/n4'] instead of ['documents/n0', 'documents/n1','documents/n2', 'documents/n3', 'documents/n4','documents/n2', 'documents/n3', 'documents/n4']. How to check if 'documents/n2' existed in the previous graph traversal result, then will skip 'documents/n2' ? 
![image](https://github.com/arangodb/arangodb/assets/32300653/1901c8a2-1dde-4f3e-b5e8-89ab43927d03)

**Comment by son2408** [comment]
if i distinct my result, it still affect performance because it still graph with documents/n2 instead of next. I have an idea like the query below but it doesn't work because it can't update global variable.
```
LET existedVertexs = []
FOR node IN ['documents/n0', 'documents/n2']
    FILTER node NOT IN existedVertexs
    FOR v,e IN 0..10 OUTBOUND node relationships
        PUSH(existedVertexs, v._key)
    RETURN v
```

**Comment by dothebart** [comment]
the AQL execution engine is a unidirectional pipeline. 
You can't go backwards - the scope goes from out to in. 
You can however have subqueries.

**Comment by son2408** [comment]
@dothebart can you guide me build the above query use subqueries ? thanks
