### ISSUE TITLE
Memory "Pain point" ;)

### ISSUE THREAD

**Issue by frankmayer** [arangodb/arangodb#2080]
I am currently evaluating ArangoDB for a specific use case, which essentially boils down to importing **OpenStreetMap** data into Arango. The final schema has not been decided upon, yet. I am evaluating a simple table-to-collection import schema, as well as a graph schema where osm ways partly become edges - connecting the osm nodes. I have also tested some in-between mixed scenarios. Besides the OSM data, there would also be custom data in the same format as OSM data, but private.

So, what's the memory pain point? Well, I grabbed that phrase off the conclusion paragraph of your benchmark post [here](https://www.arangodb.com/2015/10/benchmark-postgresql-mongodb-arangodb/) :smile: 

Here are the issues I am facing:
1. In OSM, the keys in the various objects are very often repeated and there are a lot of them - see [here](http://taginfo.openstreetmap.org/keys). This leads to a lot of key names wasting a lot of precious space/memory.
   For a test, I did an export of all collections and ran them through the velocypack tool json-to-vpack and achieved a 35%-45% reduction in size, using the `--compress` and `--no-compact` parameters. That is, as I understand it, mostly or only key compression using a lookup table. 
   Overall the reduction will most possibly be higher because the usage of the keys is below average in this specific dataset, compared to the whole planet. 
   The compression capability would even be more important if a graph design would be chosen. To be honest I'd like to go mostly graph, but the storage needs for data and indexes are too much.
   
   So, I guess a feature request would be to be able to use the compression capabilities of velocypack.
2. Also, I would like to ask if there is something on your roadmap to reduce memory consumption for edges (and including index memory reduction in general) a bit. 
   An example: for an edge collection with ~16.000.000 documents which has a **data size of 1.89GB**, the **index size is 2.37GB** with only the standard edge indexes _key & _from,_to. That is quiet huge.
3. Besides the key compression discussed before, it would also be of interest if general compression on data and/or index would be possible - or at least don't have the need to have all data in memory (there was some mention of that approach in said benchmark post).

Thank you

**Comment by baslr** [comment]
Regarding the memory usage for a single bucket edge collection with 16 * 10^6 docs:

attribute | _key | _from/_to
---- | ------------ | -------------
bucket size | 34,132,321 | 34,132,321
reported size in web frontend* | 657,058,568 | 1,638,351,408
bytes per entry | 19,2503336647 | 48
8byte value count | ~2.4 | 6

*Reported index size for a document collection (single bucket 34,132,321) with 16 * 10^6 docs: 657058568 bytes.

**Comment by frankmayer** [comment]
Bump :smile:

**Comment by sajeevpr** [comment]
can we expect data compression in the coming months?

**Comment by bubnenkoff** [comment]
@frankmayer could you explain how you did OSM data loading to ArangoDB? I am getting errors http://stackoverflow.com/questions/42858056/how-to-load-osm-geojson-data-to-arangodb

**Comment by frankmayer** [comment]
@bubnenkoff it was a quick check for a potential project. I didn't opt for the osmtogeojson at the time, but implemented a custom XML-Source file importer. However the project did not take off yet, so the state of the implementation is still pending.
I don't remember the exact reason, not to go with that (osmtoegeojson) specific way, but it might have something to do with trying to avoid the "conversion and store" step, prior to the actual import.

**Comment by frankmayer** [comment]
I am closing this now, as the main issue, the "memory pain point" is now resolved with the new RocksDB storage engine.
