### ISSUE TITLE
arangosh - unloading script

### ISSUE THREAD

**Issue by thierry-github** [arangodb/arangodb#2082]
Hi, 

i would like to know if there is a way to unload a script loaded in arangosh with require function ?

Tks.

**Comment by dothebart** [comment]
You can only make it non permanent like we do for i.e. our jsunity test suites, so you can edit and re-run test-suites without restart. Have a look at RunTest: https://github.com/arangodb/arangodb/blob/devel/js/common/modules/jsunity.js#L190 for the details.

**Comment by thierry-github** [comment]
Thanks, that's what i was looking for.
