### ISSUE TITLE
throw exception in transaction

### ISSUE THREAD

**Issue by mehdiazadi** [arangodb/arangodb#2084]
i wrote in my transaction :
`throw 'this is a test';`
i got this response body :
{ error: true,errornum: 500,message:internal server error,code:500}
how can i catch my exception message? on above example('this is a test')

**Comment by pluma** [comment]
I'm guessing this is in Foxx?

Just wrap the `db._executeTransaction` call in a try/catch. The code is always executed synchronously:

```js
try {
  db._executeTransaction({
    // ...
    action: function () {
      throw new Error('this is a test');
    }
  });
} catch (e) {
  // handle error
}
```
