### ISSUE TITLE
arangodump fails to authenticate with '@@' in the password

### ISSUE THREAD

**Issue by wyattwalter** [arangodb/arangodb#20869]
## My Environment

* __ArangoDB Version__:  3.11.8      
* __Deployment Mode__:  Leader/Follower     
* __Deployment Strategy__: Kubernetes  
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:        
* __Total RAM in your machine__:        
* __Disks in use__:        
* __Used Package__:              

## Component, Query & Data

__Affected feature__: arangodump (and maybe other CLI tools?)

__AQL query (if applicable)__:
```


```
__AQL explain and/or profile (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. Create a user with a password that includes the string '@@'
2. Try to execute an `arangodump` passing the value in the `--server.password` argument

__Problem__:
It appears that when you pass a password with '@@' in it into the arangodump cli via the `--server-password argument, it's escaping that somehow, even if passed using single quotes to remove interpretation from the shell. 

Workarounds that do work:

- leave the option off and let it prompt (this doesn't work in scripts)
- add an additional '@' for each one in the string. i.e. if the password is 'foo@@' then use 'foo@@@@'

Related:

If a password has an '@', I can add two and the password still validates. i.e. these two are interchangeable:

`arangodump ... --server.password 'foo@'`
`arangodump ... --server.password 'foo@@'`

__Expected result__:

**Comment by Simran-B** [comment]
Related PR to improve the startup option description: https://github.com/arangodb/arangodb/pull/20876

**Comment by wyattwalter** [comment]
Thank you both! That makes sense, I had missed that bit.

**Comment by dothebart** [comment]
You were not the first by far - hence the cause of action ;)
