### ISSUE TITLE
How to listen to changes in Arango Collection

### ISSUE THREAD

**Issue by son2408** [arangodb/arangodb#20887]
## My Environment

* __ArangoDB Version__:        3.11.8
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   Kubernetes
* __Infrastructure__:     own          
* __Operating System__:      Ubuntu 20.04 
* __Total RAM in your machine__:   32Gb
* __Disks in use__:      SSD
* __Expected result__: I want to watch change realtime of document collection when any events (create/ insert/update) occur. It's the same as Change Streams of MongoDB

**Comment by dothebart** [comment]
as you probably already saw, this is a duplicate of https://github.com/arangodb/arangodb/issues/602
