### ISSUE TITLE
Ability to request client certificate

### ISSUE THREAD

**Issue by youngnicks** [arangodb/arangodb#2088]
In the Arangod options, it mentions you can specify a CA file for when the server requests client certificates. However, I can't find a way to have the server request the client certificate and looking through the source code, it looks like `SSL_VERIFY_NONE` is being used. Can an option be added to use `SSL_VERIFY_PEER` be added so that the server will request client certificates?

It would be great if the client certificate were available to Foxx applications as well, similar to Express apps via req.connection.getPeerCertificate().
## my environment running ArangoDB

I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [X] 3.0
- [ ] self-compiled devel branch

**Comment by youngnicks** [comment]
I'll try to fix this in my free time, which is usually limited. I think adding a `--server.ssl-request-cert` option to arangod would be the best way to enable requesting the client cert.

**Comment by youngnicks** [comment]
I noticed this feature is now available in the enterprise version. Would a pull request providing this same functionality still be accepted?

**Comment by dothebart** [comment]
Closing as implemented.
