### ISSUE TITLE
Suggestion: Have indexes also on disk besides "only memory indexes"

### ISSUE THREAD

**Issue by frankmayer** [arangodb/arangodb#209]
I'd like to suggest to introduce the option to have indexes also on disk besides "only memory indexes" that have to be rebuilt each time a server or arangod for that matter has to be restarted.

In critical scenarios one might have to fix things (do mainetenance, updates, recovery) on servers or even on arangod that could require a restart, without meaning that the indexes are invalid. In those cases it's very probable that one needs to have the db up and running in a very short time and waiting for indexes to rebuild on probably large data, could introduce problems. I am thinking also about replication and sharding setups here.

LIke Frank cited Martin's thoughs in this Google group thread: https://groups.google.com/forum/?fromgroups=#!topic/arangodb/WL7n4Ky5L_M

"There is actually a partial solution that we have been thinking about.
This partial solution writes consistency-check-timestamps to the index
data files only on special occasions (such as a clean shutdown of the
server).  Then the server can start fast when he finds such a
consistency-check-timestamps (i.e. if it is started after a clean
shut down); and if he does not find a consistency-check-timestamp he
rebuilds the index (and starts slowly)."

**Comment by baslr** [comment]
@diegogub  [ArangoDB 3.0](https://www.arangodb.com/roadmap/)
Persistent Indexes
We plan on making indexes persistent, which will allow using quicker recovery, start-up and larger datasets.

**Comment by Simran-B** [comment]
Note that people with huge datasets will benefit from persistent indexes, but ArangoDB will remain  mostly-memory. "Mostly-mass-storage" would need to be implemented in addition to persistent indexes, they don't necessarily imply the former. Please refer to @neunhoef for in-depth explanation.

**Comment by kulshekhar** [comment]
When I read about persistent indexes being on the roadmap, I imagined it would behave as with most other databases. Now, I don't know how it works with most other databases other than I usually don't have to care about it.  

However statements like 
> ArangoDB will remain mostly-memory. "Mostly-mass-storage" would need to be implemented in addition to persistent indexes, they don't necessarily imply the former

sort of mess up my conceptual view of ArangoDB and now I'm not sure what to expect after persistent indexes land.

For instance:
1. Is not having to rebuild the index the only benefit of persistent indexes?
2. Will it lower the memory requirement compared to the versions without persistent indexes?
3. What will it change from an operational/administrative perspective?

**Comment by iyobo** [comment]
I'd love to hear the answer to @kulshekhar's questions as well.

**Comment by baslr** [comment]
@kulshekhar afaik: 1) yes
2) no, you could also start ArangoDB with 200 MB ram, but then, the OS has to swap a lot of memory from ram to swap space on disk and vice versa.
I guess you mean something like, ArangoDB is looking for indexes or part of indexes that are not used since x and will purge them from the ram. And when they are requested ArangoDB will load them back into ram?
3) you have to budget the diskspace for the indexes. Since they will persist on disk.

@iyobo ArangoDB will persist the index as VelocyPack on disk. On next startup validate the integrity and read them back into ram. If validation fails, indexes have to be build again. afaik the catch would be additional diskspace required to store the indexes.

**Comment by iyobo** [comment]
@basir Wonderful! 
I'm sure most folks who work with serious data would agree that additional diskspace is not a problem.
So I'm glad to hear that. 👍 

A new question (And I understand the data to answer these may not be available right now):
- What percentage improvement would the best case scenario (persisted index is valid) provide on current launch time for a large dataset that previously took 20 minutes to boot?

**Comment by baslr** [comment]
@iyobo, @fceller released ArangoDB version 3.0.0-alpha1 yesterday. Maybe you can try it out?

**Comment by fceller** [comment]
@baslr please be patient, we will release a technical preview in the next days. I'm currently trying to get it build packages.

**Comment by baslr** [comment]
@fceller So do I. But #1814

**Comment by dothebart** [comment]
ArangoDB 3.0 comes with a new index of type rocksdb which persists do disk.
