### ISSUE TITLE
Provide mobile version for Android and iOS

### ISSUE THREAD

**Issue by frankgerhardt** [arangodb/arangodb#2090]
Feature request.

ARM compilation discussed at #1493. 

Like CouchDB, which has PouchDB as a mobile lightweight version of the server database, it would be great if ArangoDB would also have a version for mobile devices. 

Replication would be great for mobile apps with offline mode.

**Comment by baslr** [comment]
Replication interface from PouchDB to ArangoDB?

**Comment by frankgerhardt** [comment]
(Background: CouchDB is the server side database written in Erlang and PouchDB is the API compatible syncs-with-CouchDB database written in JavaScript for embedding into web sites, offline web apps, cross-platform mobile apps (e.g. with Cordova).)

A mobile version of ArangoDB, for the sake of my argument called ArangoPouch, would be an API compatible and syncs-with-the-real-ArangoDB version written in some language that works well on mobile OSes like Android and iOS. 

The use case is to use ArangoDB on the server and "ArangoPouch" as the client database on a mobile device. When online, the user can sync the client database with the server. When offline the user can work on the local ArangoPouch and sync later. 

Features can be more lightweight. E.g. on a mobile device there is only one user and parallelism is limited.

**Comment by Simran-B** [comment]
Wouldn't it require a full implementation of AQL on the client side?

**Comment by frankgerhardt** [comment]
Yes

**Comment by aguilera51284** [comment]
+1

**Comment by dothebart** [comment]
While @servusoft acually maintains an ARM linux port we don't intend to maintain an arangodb port on Android, nor develop a satelite version for disconnected use on the mobile. 
if you like to work on this issue, feel free to comment and we'll re-open it. 
Since we won't do this - closing as "won't fix"

**Comment by Queatz** [comment]
+1

This is something that would greatly exercise ArangoDB's flexibility as a platform.  I think moving towards mobile support early would cause Arango to run into inevitable scalability concerns early (as well as a major increase in curb appeal.)

**Comment by beebase** [comment]
Given the fact that nowadays people are using their phone for everything everywhere, I'd say the  databases that will handle offline/online connection out of the box, will be king.

**Comment by Miamoto-Musashi** [comment]
+1

**Comment by Textras** [comment]
+1

**Comment by giovanebarcelos** [comment]
+1
