### ISSUE TITLE
Full collection scan although all corresponding attributes are indexed.

### ISSUE THREAD

**Issue by daffunn** [arangodb/arangodb#2092]
## My environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [x] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [x] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

    LET user = DOCUMENT(@user) LET followees = (FOR e IN @@edges FILTER e._from == user._id RETURN e._to) FOR u IN @@collection FILTER u._id != user._id FILTER u._id NOT IN followees LIMIT 5 RETURN u

Why does it perform a full collection scan? I also limited it to 5 results.

```
Execution plan:
 Id   NodeType                  Est.   Comment
  1   SingletonNode                1   * ROOT
  2   CalculationNode              1     - LET user = DOCUMENT("users/18433")   /* simple expression */
  9   SubqueryNode                 1     - LET followees = ...   /* subquery */
  3   SingletonNode                1       * ROOT
 17   IndexNode                    1         - FOR e IN user-connections   /* edge index scan */
  7   CalculationNode              1           - LET #8 = e.`_to`   /* attribute expression */   /* collections used: e : user-connections */
  8   ReturnNode                   1           - RETURN #8
 10   EnumerateCollectionNode      2     - FOR u IN users   /* full collection scan */
 11   CalculationNode              2       - LET #10 = (u.`_id` != user.`_id`)   /* simple expression */   /* collections used: u : users */
 12   FilterNode                   2       - FILTER #10
 13   CalculationNode              2       - LET #12 = (u.`_id` not in followees)   /* simple expression */   /* collections used: u : users */
 14   FilterNode                   2       - FILTER #12
 15   LimitNode                    2       - LIMIT 0, 5
 16   ReturnNode                   2       - RETURN u

Indexes used:
 By   Type   Collection         Unique   Sparse   Selectivity   Fields               Ranges
 17   edge   user-connections   false    false       100.00 %   [ `_from`, `_to` ]   (e.`_from` == user.`_id`)

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   move-calculations-up-2
  4   move-filters-up-2
  5   use-indexes
  6   remove-filter-covered-by-index
```

**Comment by baslr** [comment]
for the :eye:
```
LET user = DOCUMENT(@user)
LET followees = (FOR e IN @@edges FILTER e._from == user._id RETURN e._to)

FOR u IN @@collection
    FILTER u._id != user._id
    FILTER u._id NOT IN followees
    LIMIT 5
    RETURN u
```

can you simplify it to
```
LET user = DOCUMENT(@user)
LET notIn = UNION([user._id], (FOR e IN @@edges FILTER e._from == user._id RETURN e._to))

FOR u IN @@collection
    FILTER u._id NOT IN notIn
    LIMIT 5
    RETURN u
```

**Comment by daffunn** [comment]
Thank you @baslr for you help and sorry for not formatting it by myself. Your approach looks better than mine, but still throws a "Full collection scan"-warning, why?

```
Execution plan:
 Id   NodeType                  Est.   Comment
  1   SingletonNode                1   * ROOT
  2   CalculationNode              1     - LET user = DOCUMENT("users/17292")   /* simple expression */
  9   SubqueryNode                 1     - LET #2 = ...   /* subquery */
  3   SingletonNode                1       * ROOT
 16   IndexNode                    1         - FOR e IN user-connections   /* edge index scan */
  7   CalculationNode              1           - LET #8 = e.`_to`   /* attribute expression */   /* collections used: e : user-connections */
  8   ReturnNode                   1           - RETURN #8
 11   EnumerateCollectionNode    102     - FOR u IN users   /* full collection scan */
 12   CalculationNode            102       - LET #10 = (u.`_id` not in UNION([ user.`_id` ], #2))   /* simple expression */   /* collections used: u : users */
 13   FilterNode                 102       - FILTER #10
 14   LimitNode                    5       - LIMIT 0, 5
 15   ReturnNode                   5       - RETURN u

Indexes used:
 By   Type   Collection         Unique   Sparse   Selectivity   Fields               Ranges
 16   edge   user-connections   false    false        75.00 %   [ `_from`, `_to` ]   (e.`_from` == user.`_id`)

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   remove-unnecessary-calculations
  4   move-calculations-up-2
  5   move-filters-up-2
  6   use-indexes
  7   remove-filter-covered-by-index
```

**Comment by baslr** [comment]
You have to create a skiplist index on `_id` and add sort by _id

**Comment by daffunn** [comment]
According to the docs (https://docs.arangodb.com/3.0/Manual/Indexing/IndexBasics.html) I am not able to create an index for the `_id` attribute? `db.users.ensureSkiplist("_id")` consequently does throw an error. 🤔

**Comment by baslr** [comment]
You can switch to `_key`.
Then you have to modify your followees  query to split the key out.

**Comment by baslr** [comment]
Hm, I'm sorry, Zufrüh gefreut.
The index is only used for sorting.
So currently there is no way to use an index to filter ranges like this
```
-> sorted index direction
y exclude
x include
|-><-| selected range
|->xxx<-|y|->xx<-|xxxyxxxxxxxyyyxxxxxx
```

**Comment by DeShadow** [comment]
@daffunn Your query have operator `!=`. The optimizer is not very efficient with him. But in your case  full scan is required. Because you want to get all rows except some ones. And no index is helpful in this situation.

**Comment by jsteemann** [comment]
I can confirm that the query optimizer will not consider using an index for operator `!=` or `NOT IN`,
That's why the query uses a full collection scan when executing. The scan will stop however once 5 result documents have been found.

**Comment by daffunn** [comment]
Alright, thank you for all the comments. As the query will be stopped after 5 findings, this issue can be closed. Thanks again!
