### ISSUE TITLE
Primary Sort ArangoSearch is not flexible, What's other way do with sort in ArangoSearch 

### ISSUE THREAD

**Issue by son2408** [arangodb/arangodb#20948]
## My Environment

* __ArangoDB Version__:        3.11.8
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Infrastructure__:               own
* __Operating System__:        Ubuntu 20.04
* __Total RAM in your machine__:        32Gb
* __Disks in use__:        SSD
## Component, Query & Data
__ViewConfig__:
```
{
  "writebufferSizeMax": 33554432,
  "id": "2455388",
  "storedValues": [],
  "name": "view",
  "type": "arangosearch",
  "consolidationPolicy": {
    "type": "tier",
    "segmentsBytesFloor": 2097152,
    "segmentsBytesMax": 5368709120,
    "segmentsMax": 10,
    "segmentsMin": 1,
    "minScore": 0
  },
  "writebufferActive": 0,
  "links": {
    "tinhhinhdangky": {
      "analyzers": [
        "identity"
      ],
      "fields": {},
      "includeAllFields": false,
      "storeValues": "none",
      "trackListPositions": false
    },
    "giaychungnhan": {
      "analyzers": [
        "identity"
      ],
      "fields": {},
      "includeAllFields": false,
      "storeValues": "none",
      "trackListPositions": false
    },
    "dangkyquyen": {
      "analyzers": [
        "identity"
      ],
      "fields": {},
      "includeAllFields": false,
      "storeValues": "none",
      "trackListPositions": false
    },
    "thuadat": {
      "analyzers": [
        "identity"
      ],
      "fields": {},
      "includeAllFields": false,
      "storeValues": "none",
      "trackListPositions": false
    },
    "hosotiepnhan": {
      "analyzers": [
        "identity"
      ],
      "fields": {},
      "includeAllFields": false,
      "storeValues": "none",
      "trackListPositions": false
    }
  },
  "commitIntervalMsec": 1000,
  "consolidationIntervalMsec": 1000,
  "globallyUniqueId": "h189823C8B262/2455388",
  "cleanupIntervalStep": 2,
  "primarySort": [
    {
      "field": "tinhHinhDangKyId",
      "asc": true
    }
  ],
  "primarySortCompression": "lz4",
  "writebufferIdle": 64
}
```
__Problem__:
![image](https://github.com/arangodb/arangodb/assets/32300653/1f4c3522-8307-4378-8922-8c5912ae8700)
My view links many collections. When I add a new collection to this view, I can't add new field sort to current view config. If I remove this view after create new, it will take a lot of  time and we can't do anything during save view.
__Expected result__:
I want add new sort field without create new view, or what's other way work with sort arangosearch ?

**Comment by alexbakharew** [comment]
Hello @son2408 !

Unfortunately, you can specify Primary Sort fields/order only during view creation:
```
You can only set the primarySort option and the related primarySortCompression and primarySortCache options on View creation.
```
Here is the documentation page: https://docs.arangodb.com/3.11/index-and-search/arangosearch/performance/#primary-sort-order

To solve your problem, you can switch to the recently implemented Inverted Index and Search Alias View: https://docs.arangodb.com/3.11/index-and-search/arangosearch/search-alias-views-reference/#how-to-use-search-alias-views.

With these new functionality one can achieve your desired scenario:
1. Create an Inverted Index for the new collection with required Primary Sort settings.
2. Add this index to Search Alias View - now previously added indexes are not affected.
3. After adding index you can query view.

If you have any further questions feel free to ask them as well!

**Comment by son2408** [comment]
@alexbakharew  thanks you

**Comment by son2408** [comment]
@alexbakharew  I can't add new index of a collection into search-alias exists. if I upadate indexes property, it's sync all, I don't expect this.

**Comment by son2408** [comment]
@alexbakharew  how to do it ?

**Comment by son2408** [comment]
I have a search-alias with index "idx_1800260331957649408" with collection "a"
![image](https://github.com/arangodb/arangodb/assets/32300653/602e2b03-396a-4d05-b04a-0c6a9083919c)

**Comment by son2408** [comment]
Now, I wan't add new index of collection b into search-alias "r" exists. I don't affect indexes before :(

**Comment by son2408** [comment]
@alexbakharew by your suggest, I request api update search-alias with body by your suggest with body "indexes": [
    {
      "collection": "a",
      "index": "idx_1800260331957649408",
      "operation": "string"
    },
    {
      "collection": "b",
      "index": "idx_1800288305630150656",
      "operation": "string"
    }
  ]

**Comment by alexbakharew** [comment]
Hello @son2408 

> if I upadate indexes property, it's sync all, I don't expect this.

Do you mean that the update of the search-alias view with exactly one new index has the same execution time as creating arangosearch view for all collections?

**Comment by alexbakharew** [comment]
> "indexes": [
> {
> "collection": "a",
> "index": "idx_1800260331957649408",
> "operation": "string"
> },
> {
> "collection": "b",
> "index": "idx_1800288305630150656",
> "operation": "string"
> }
> ]

"operation": "string" is incorrect here. https://docs.arangodb.com/3.11/index-and-search/arangosearch/search-alias-views-reference/#view-modification

You can use either "add" or "del". Default value is "add". So in your case you can simply omit it.

**Comment by son2408** [comment]
I receive a message error, do you explain it for me, thanks ?
![image](https://github.com/arangodb/arangodb/assets/32300653/967015c6-5dfa-4c25-b154-83d1f2f90ea1)

**Comment by alexbakharew** [comment]
@son2408 I suspect that in these 2 indexes you have different primary sort orders. So the order should be the same in all indexes.

```
If you mix directions in the primary sort order, the inverted index cannot be utilized for fully optimizing out a matching SORT operation if you use the inverted index standalone.
```

**Comment by son2408** [comment]
@alexbakharew I want create sort order both **asc** and **desc** for a field in **Inverted Index**. Therefor it causes the error above

**Comment by alexbakharew** [comment]
Hi @son2408! 

> I want create sort order both asc and desc for a field in Inverted Index. Therefore it causes the above error. If only choose one sort order, I think this it's not reasonable.

Unfortunately, I wasn't able to reproduce this error by specifying different sorting order for the same field. I got this error when I tried to create a view with indexes which have different sorting orders. 

Could you please provide collection, indexes and view definitions for more detailed info?

>  I try create sort order both asc and desc on a field, but i see it only work with asc :(

Under the hood in the index there is no data duplication. It means that we store documents in index only once and apply sorting orders which you have defined in index definition. As a result, your documents in index will be sorted either in ascending or in decreasing order.

**Comment by son2408** [comment]
Hello @alexbakharew. If a field can sort asc or desc, should I index sort this field by your suggestion?

**Comment by son2408** [comment]
@alexbakharew In fact, when client use my application, they want view oldest or lastest data by date time. I can't force them only once direct sort

**Comment by son2408** [comment]
@alexbakharew How to index sort a field that I can query sort either in ascending or in decreasing order ? If with a field I create two indexes, one for ascending one for decreasing and if i need index sort for 10 fields i will create 20 indexes. I think this is a bad idea

**Comment by alexbakharew** [comment]
Hi @son2408!

Unfortunately, it is only possible to gain performance advantage for the order, which is specified in PrimarySort definition.
