### ISSUE TITLE
How to use the AQL query to check whether the data imported to the  existing collection in arangodb successfully or not?

### ISSUE THREAD

**Issue by saliormoon** [arangodb/arangodb#2095]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.0
On this operating system:
- [ ] Linux 
  - [x] SUSE   .rpm
### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [x] arangosh

I've imported a CSV file named "graph.csv" to a existing collection named "_graphs" in ArangoDB.
 And now I want to query the results of this collection to check whether I have imported  the data successfully. 
The data of graph.csv just like this:
1 2
3 1
4 2
5 4
6 7
so how to use the AQL query ? Anyone can help me?

**Comment by jsteemann** [comment]
* with AQL (can be executed via ArangoDB's web interface):
```
FOR doc IN _graphs
  RETURN doc
```
* from the ArangoShell (arangosh):
```
db._graph.toArray();
```
Please note that a user-created collection shouldn't be called `_graphs` because there already is a system collection of the same name in every ArangoDB. And its purpose is to store the meta-data of user-defined graphs.

**Comment by saliormoon** [comment]
OK, thanks a lot.  I have some data of graph(just like the graph.csv above) and I want to store them with ArangoDB. Because the data is very huge and maybe can't be put by AQL insert , I want to use Arangoimp to import the data.  Do I need to change the data form of graph.csv to certain kind ? And what's the right form? I am the newer,   can you give some further instructions? I would be very grateful.

**Comment by jsteemann** [comment]
Using arangoimp for importing the data is fine. I suggest trying the import and check via the web interface what data actually ended up in the target collection.
If the csv file only contains two numbers per line and no collection names, you probably want to use arangoimp's `--from-collection-prefix` and `--to-collection-prefix` options to prepend the vertex collection names to the numbers. You also may want to play around with the file parameters of arangoimp a bit. From the above it looks like the data in the file actually isn't comma-separated, but separated using a tab or some other whitespace characters. If it's tabs, then please use arangoimp's `--type tsv` option.

**Comment by saliormoon** [comment]
OK, thanks very much. It's very kind of you to help me.

**Comment by saliormoon** [comment]
Hello, jsteemann, can you give a command line to run about "--from-collection-prefix" and "--to-collection-prefix"? Would you like to give it in detail. The data in the file is separated using a blank space. 
@jsteemann

**Comment by jsteemann** [comment]
@saliormoon : please consult the [docs for arangoimp](https://docs.arangodb.com/3.0/Manual/Administration/Arangoimp.html). The documentation has examples for `--from-collection-prefix` and `--to-collection-prefix` as well.

**Comment by saliormoon** [comment]
Well, I have see, thank you.
