### ISSUE TITLE
Documentation conflict. Is Active Failover mode deprecated?

### ISSUE THREAD

**Issue by visortelle** [arangodb/arangodb#20966]
This page suggests to use Active Failover as an alternative to Leader/Follower deployment mode:

https://docs.arangodb.com/3.11/release-notes/deprecated-and-removed-features/
<img width="737" alt="Screenshot 2024-05-26 at 12 07 38 PM" src="https://github.com/arangodb/arangodb/assets/9302460/4cb94340-c271-4ed8-8f0c-c0a41cb72e44">

Another page says that it is deprecated:
https://docs.arangodb.com/3.11/deploy/active-failover/
<img width="764" alt="Screenshot 2024-05-26 at 12 08 53 PM" src="https://github.com/arangodb/arangodb/assets/9302460/cc6baa0b-ad07-44fd-a93c-d17d3da00d1b">

Which one is correct?
If Active Failover mode is deprecated, are there any alternatives?

**Comment by visortelle** [comment]
Found it:

https://docs.arangodb.com/3.12/release-notes/version-3.12/incompatible-changes-in-3-12/#active-failover-deployment-mode-removed
<img width="768" alt="Screenshot 2024-05-26 at 2 58 53 PM" src="https://github.com/arangodb/arangodb/assets/9302460/dfb7f76b-e6a6-4b72-aaec-6ed25aa5f272">

I simply didn't notice that the documentation is versioned. Closing.

**Comment by dothebart** [comment]
Thanks for resolving ;)
