### ISSUE TITLE
Suggestion: TTL Collections (Very good for session management, amongst other things)

### ISSUE THREAD

**Issue by frankmayer** [arangodb/arangodb#210]
A nice addon for managing user-sessions without having the application do all the work, would be the existence of TTL -Collections.

This is much like a very nice feature that was added to MongoDB lately, but with a different approach => http://docs.mongodb.org/manual/tutorial/expire-data/

In MongoDB the expirationAfterSeconds must be set on the collection when the index is created.
For flexibility, it would be better to not have such a declaration but set the expirationDateTime manually to now()+sessionlifetime(or "session expires after x seconds").

so, that would be a collection where documents have a specific (indexed) field with an expiration date/time. Every x ( configurable?) seconds, Arangod would go through this collection and delete the expired records.

So for Session Management this would mean:

1) storing a document with the user's session on Log-on. The expirationdatetime would be now()+sessionlifetime(or "session expires after x seconds").

2) updating the timestamp (now()+sessionlifetime) every time the user  interacts with the application/page

Session expiration is done automatically by the TTL Collection when (timestamp+session_liftime) < current timestamp when arangod checks the TTL Collection.

To check for the session, one would just query the collection.

**Comment by gauravkumar37** [comment]
Any progress or any plans to implement this?
Almost all the NoSQLs today have TTLs for documents (auto expiring keys).

**Comment by mirokk** [comment]
Would be a great feature!

**Comment by kubz** [comment]
+1

**Comment by pluma** [comment]
Please don't comment with "+1" or "me too" as this sends out useless e-mails to everyone subscribed to the issue.

If you wish to express support for an issue, you can use the "Add an emoji reaction" feature on the issue description to give it a thumbs up. If you just want to be notified of future progress of the issue, you can press the "Subscribe" button in the sidebar.

**Comment by kishorel** [comment]
Any update on this? This would really help so many.

**Comment by CoericK** [comment]
+1

**Comment by daniel-thomas** [comment]
+1

**Comment by dothebart** [comment]
this was implemented via https://github.com/arangodb/arangodb/pull/8169 and will be part of the upcomming ArangoDB 3.5 release.

**Comment by maxkernbach** [comment]
Closing as fixed since TTL indexes are available in 3.5.
The latest Release Candidate of ArangoDB 3.5 can be found in the [download section](https://www.arangodb.com/download-technical-preview/).

Please note that a Release Candidate is for testing purposes only, not for production usage!

More details can be found in the links below:

https://www.arangodb.com/arangodb-training-center/ttl-indexes/
https://www.arangodb.com/docs/devel/indexing-index-basics.html#ttl-time-to-live-index
