### ISSUE TITLE
How to test the ArangoDB performance on graph？

### ISSUE THREAD

**Issue by saliormoon** [arangodb/arangodb#2101]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.0

On this operating system:
- [x] Linux 
  - [x] SUSE   .rpm

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [x] arangosh

My program want to store  data in ArangoDB and test the database performance. Which main performance indexs can I use and how to do the test? Anyone can give me some suggestions?

**Comment by dothebart** [comment]
have a look at our approach of testing the performance: 
https://www.arangodb.com/performance
The source of the test is available so you can modify / and / or retry yourselves.

**Comment by saliormoon** [comment]
OK, thank you.
