### ISSUE TITLE
Graph is not defined

### ISSUE THREAD

**Issue by saliormoon** [arangodb/arangodb#2103]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [x] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [x] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [x] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [x] authentication is enabled?
- [x] using the cluster?
- [x] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click to ...
...
### my problem
When I use "Graph" in the command line ,it throws the error below:

JavaScript exception: ReferenceError: Graph is not defined
!Graph
!^
stacktrace: ReferenceError: Graph is not defined
    at <shell command>:1:1

I have no idea about the problem. Anyone can help me?

**Comment by dothebart** [comment]
did you try along the lines of https://docs.arangodb.com/3.0/Manual/Graphs/index.html#the-knowsgraph ? Its using https://github.com/arangodb/arangodb/blob/devel/js/common/modules/%40arangodb/graph-examples/example-graph.js

**Comment by Simran-B** [comment]
Well, it **is** not defined. Do you mean this?

```
general_graph = require("@arangodb/general-graph")
general_graph._listObjects()
```

Example result:

```
[
  {
    "_key" : "myGraph",
    "_id" : "_graphs/myGraph",
    "_rev" : "8468",
    "edgeDefinitions" : [
      {
        "collection" : "edges",
        "from" : [
          "verts"
        ],
        "to" : [
          "verts"
        ]
      }
    ],
    "orphanCollections" : [ ]
  }
]
```
