### ISSUE TITLE
using external libraries in arango shell and transactions

### ISSUE THREAD

**Issue by piotr-s-brainhub** [arangodb/arangodb#2106]
I noticed in Arango transaction action and more generally in Arango shell it's possible to require libraries which are listed in https://github.com/arangodb/arangodb/blob/devel/js/node/package.json (with a few exceptions probably due to using different Arango version).

I would like to be able to use other JS modules.
Except of forking Arango I have found only this way to do this:

``` javascript
const foo = require('foo');

function action(params) {
...
foo();
...
}

db._executeTransaction({
  collections: { write: ['bar', 'baz'] },
  action: `${action.toString().slice(0, -1)}; ${foo.toString()}; }`
});
```

**Comment by baslr** [comment]
The function `action` is stringified on the client then transferred to the ArangoDB and executed.
The function then has no clue about some module called `foo` since its a different and new context.

**Comment by dothebart** [comment]
When you're creating a [foxx service](https://docs.arangodb.com/3.0/Manual/Foxx/index.html), you can package and include custom libraries. You should however [note that there are limitations](https://docs.arangodb.com/3.0/Manual/Appendix/JavaScriptModules/index.html) regarding the supported libraries; i.e. only synchroneous libraries are supported.

**Comment by pluma** [comment]
@piotr-s-brainhub Does this answer your question? Is there anything you would like us to add to the answer or can we close this issue?

**Comment by piotr-s-brainhub** [comment]
It's OK. Thanks for the answers.
