### ISSUE TITLE
Queries will not be saved in the web interface

### ISSUE THREAD

**Issue by crs-** [arangodb/arangodb#2109]
I use the last available debian package of arangodb (version 3.0.10). If I save a query from the web interface the query first appears in the Query-Tab. But if I reload the web interface in the browser the query is deleted and the Query-Tab shows "No content.".
Tested with Firefox, Opera Microsoft Edge webbrowser.

## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [x] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [x] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS: Windows
- [x] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click to ...
...

The following problem occurs: [Screenshot?] 
Instead I would be expecting: 

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

**Comment by hkernbach** [comment]
I'm not able to reproduce this issue. Could you please go more into detail? A complete step-by-step instruction would be great.

**Comment by crs-** [comment]
Ok, I'll try.
The Arangodb installation on the server started with version 3.0
I've upgraded it to version 3.0.4 and finaly today to version 3.0.10.
The problem was the same in all 3 cases.

To reproduce the issue in my installation I have to do the following:
1. Create a Query in the web interface. 
2. Press the Button "Save".
3. Type in a name.
4. Press the button "Queries".
   -> The Query is shown with the given name in the list. And also it's content (Preview) when it will be selected.
5. Press the browsers reload-Button. 
6. After the reload is finished press the button "Queries" again.
   -> The query list will be empty again and shows "No content.".

The issue seems to depend on the selected database. It only happens if I use my own database.
If I use the "_system" database the saved queries are still in the list after a reload.

Can I try anything else to get more informations from the web interface which I can provide you?

**Comment by Simran-B** [comment]
I tried this with Chrome and Edge, 3.0.10 and devel, in a new ArangoDB database and couldn't reproduce the problem.

Does the problem occur if you create a new database, or only for a certain existing DB that you created?

What is the latency to the server? Is it possible that you hit reload before the query was actually sent to the server for saving?

**Comment by crs-** [comment]
Ok, it seems to be a problem with a "non-root" user. I can save queries as root in all existing databases but if I use another user (existing or new created) this user (as database owner) will not be able to save queries in the web interface.

**Comment by Simran-B** [comment]
Looks like the problem is that queries are stored in the _users collection of the _system database, but not all users have access to it. If queries are shown before reload, you might be looking at cached entries.

**Comment by hkernbach** [comment]
Thanks! Fixed in devel. d22408f0276475761b7ce2d3a037ac3606b972bc

**Comment by crs-** [comment]
Ok, thanks.
