### ISSUE TITLE
Can't add a index collection contains primary sort different config primary sort of previous indexes to a search-alias view

### ISSUE THREAD

**Issue by son2408** [arangodb/arangodb#21104]
## My Environment

* __ArangoDB Version__:        3.11.8
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:    Manual Start
* __Infrastructure__:               own
* __Operating System__:        Windows 10
* __Total RAM in your machine__:        32Gb
* __Disks in use__:        SSD
* __Used Package__:              

__Problem__:
I have 2 collections: student, teacher.
### student collection
**data**
```
{
  "StudentId": 1,
  "CreatedDate": "2024-06-24T16:42:27.495+07:00",
  "ModifiedDate": "2024-06-24T16:42:27.495+07:00",
  "FullName": "Ann Brook",
  "School": "Virginia Beach City Public Schools"
}
```
**config index**
```
{
  "analyzer": "identity",
  "cleanupIntervalStep": 2,
  "commitIntervalMsec": 1000,
  "consolidationIntervalMsec": 1000,
  "consolidationPolicy": {
    "type": "tier",
    "segmentsBytesFloor": 2097152,
    "segmentsBytesMax": 5368709120,
    "segmentsMax": 10,
    "segmentsMin": 1,
    "minScore": 0
  },
  "features": [],
  "fields": [
    {
      "name": "StudentId"
    }
  ],
  "id": "student/5337280",
  "includeAllFields": false,
  "name": "idx",
  "primarySort": {
    "fields": [
      {
        "field": "StudentId",
        "asc": true
      },
      {
        "field": "CreatedDate",
        "asc": true
      }
    ],
    "compression": "lz4"
  },
  "searchField": false,
  "sparse": true,
  "storedValues": [],
  "trackListPositions": false,
  "type": "inverted",
  "unique": false,
  "version": 1,
  "writebufferActive": 0,
  "writebufferIdle": 64,
  "writebufferSizeMax": 33554432
}
```
### teacher collection
**data**
```
{
  "TeacherId": 1,
  "CreatedDate": "2024-06-20T16:42:27.495+07:00",
  "ModifiedDate": "2024-06-24T16:42:27.495+07:00",
  "FullName": "Betty Johnson",
  "School": "Virginia Beach City Public Schools"
}
```
**config index**
```
{
  "analyzer": "identity",
  "cleanupIntervalStep": 2,
  "commitIntervalMsec": 1000,
  "consolidationIntervalMsec": 1000,
  "consolidationPolicy": {
    "type": "tier",
    "segmentsBytesFloor": 2097152,
    "segmentsBytesMax": 5368709120,
    "segmentsMax": 10,
    "segmentsMin": 1,
    "minScore": 0
  },
  "features": [],
  "fields": [
    {
      "name": "CreatedDate"
    },
    {
        "field": "TeacherId",
        "asc": true
     }
  ],
  "id": "teacher/5332358",
  "includeAllFields": false,
  "name": "idx_1802888086364880896",
  "primarySort": {
    "fields": [
      {
        "field": "CreatedDate",
        "asc": true
      }
    ],
    "compression": "lz4"
  },
  "searchField": false,
  "sparse": true,
  "storedValues": [],
  "trackListPositions": false,
  "type": "inverted",
  "unique": false,
  "version": 1,
  "writebufferActive": 0,
  "writebufferIdle": 64,
  "writebufferSizeMax": 33554432
}
```
When I add this indexes to a view. I got this error.
![image](https://github.com/arangodb/arangodb/assets/32300653/034d52cb-66f2-445f-bc21-5f2656f424df)

I expect create a view that will link multi collections contains index field sort different, i can update index sort field of a collection i need, instead of I must remove then create new view.

**Comment by son2408** [comment]
How to resolve this usecase?, I have collection 1 with invertex index contains primary sort with field a and field b, collection 2 with primary sort field a and field c. I want add 2 indexes to a view. If I use search-alias view then I got error missmatches primary sort. If I use arangosearch 
I can't update primary sort, Can I add new a primary sort ? I don't want delete view then create new view, because a view is linked multi collections so that time create too long, it will effect sytem is running :(. Thanks all !

**Comment by son2408** [comment]
If I want add create a new collection with a new primary sort, If total count of view is 500 millions documents, I must delete then create new view. It's too inconvenient. Does ArangoDB realize that ?

**Comment by alexbakharew** [comment]
Hi @son2408 !
1. In order to use primarySort for the fields, please be sure that such fields are indexed beforehand. 
2. Such fields definition is incorrect:
```
  "fields": [
    {
      "name": "CreatedDate"
    },
    {
        "field": "TeacherId",
        "asc": true
     }
  ],
```
3. As it was discussed here, it is not possible to modify primarySort after view creation: https://github.com/arangodb/arangodb/issues/20948#issuecomment-2125139163

**Comment by son2408** [comment]
Hi @alexbakharew, sorry I share again. I still create search-alias view with this two collections :(
### config index student collection
```
{
  "analyzer": "identity",
  "cleanupIntervalStep": 2,
  "commitIntervalMsec": 1000,
  "consolidationIntervalMsec": 1000,
  "consolidationPolicy": {
    "type": "tier",
    "segmentsBytesFloor": 2097152,
    "segmentsBytesMax": 5368709120,
    "segmentsMax": 10,
    "segmentsMin": 1,
    "minScore": 0
  },
  "features": [],
  "fields": [
    {
      "name": "CreatedDate"
    },
    {
      "name": "StudentId"
    }
  ],
  "id": "student/5371515",
  "includeAllFields": false,
  "name": "idx_student",
  "primarySort": {
    "fields": [
      {
        "field": "CreatedDate",
        "asc": true
      },
      {
        "field": "StudentId",
        "asc": true
      }
    ],
    "compression": "lz4"
  },
  "searchField": false,
  "sparse": true,
  "storedValues": [],
  "trackListPositions": false,
  "type": "inverted",
  "unique": false,
  "version": 1,
  "writebufferActive": 0,
  "writebufferIdle": 64,
  "writebufferSizeMax": 33554432
}
```
### config index student collection
```
{
  "analyzer": "identity",
  "cleanupIntervalStep": 2,
  "commitIntervalMsec": 1000,
  "consolidationIntervalMsec": 1000,
  "consolidationPolicy": {
    "type": "tier",
    "segmentsBytesFloor": 2097152,
    "segmentsBytesMax": 5368709120,
    "segmentsMax": 10,
    "segmentsMin": 1,
    "minScore": 0
  },
  "features": [],
  "fields": [
    {
      "name": "TeacherId"
    },
    {
      "name": "CreatedDate"
    }
  ],
  "id": "teacher/5371889",
  "includeAllFields": false,
  "name": "idx_teacher",
  "primarySort": {
    "fields": [
      {
        "field": "TeacherId",
        "asc": true
      },
      {
        "field": "CreatedDate",
        "asc": true
      }
    ],
    "compression": "lz4"
  },
  "searchField": false,
  "sparse": true,
  "storedValues": [],
  "trackListPositions": false,
  "type": "inverted",
  "unique": false,
  "version": 1,
  "writebufferActive": 0,
  "writebufferIdle": 64,
  "writebufferSizeMax": 33554432
}
```

**Comment by son2408** [comment]
If primary sort of idx_teacher must be like idx_student, then creation work. This is unreasonable.

**Comment by alexbakharew** [comment]
Hi @son2408,
please use correct syntax for defining primarySort order: https://docs.arangodb.com/3.11/index-and-search/arangosearch/performance/#primary-sort-order

If you will still have problems with it, I will help you.
I will get back to you with detailed answers to the last 3 questions after small vacation.

**Comment by son2408** [comment]
Hi @alexbakharew I used correct synctax for defining primarySort order as documents, but a problem here is my view can't link 2 indexes that contains primarySort difference.
I created 2 inverted indexes successfully, but I can't link it to a view. Can you help me, please ?
```
db.student.ensureIndex({name: "inv-idx", type: "inverted", fields: ["CreatedDate", "StudentId"], primarySort: {fields: [{ field: "CreatedDate", direction: "desc" },{ field: "StudentId", direction: "desc" } ] } });

db.teacher.ensureIndex({name: "inv-idx", type: "inverted", fields: ["CreatedDate", "TeacherId"], primarySort: {fields: [{ field: "CreatedDate", direction: "desc" },{ field: "TeacherId", direction: "desc" } ] } });
```

**Comment by Simran-B** [comment]
There are restrictions as to what settings are allowed for inverted indexes when you combine them in a search-alias View, such as matching primary sort orders. This is documented here:

https://docs.arangodb.com/stable/index-and-search/indexing/working-with-indexes/inverted-indexes/#restrictions
