### ISSUE TITLE
Query builder in web-interface. Shortcut Cmd+Enter not working when focus in bindVars JSON mode

### ISSUE THREAD

**Issue by DeShadow** [arangodb/arangodb#2111]
ArangoDB v3.1rc2

There is very useful shortcut Cmd+Enter to run query. But this shortcut works in query input box, bindVars window (Table mode), but not working in bindVars window (JSON mode).

Also if possible could you save the mode of bindVars window. I very often use JSON mode and every time I open page "Queries" I need to change this mode. Because I need to work with numbers as strings, but bindVars auto-converts it to numbers every time.

**Comment by hkernbach** [comment]
Thank you for your feedback. Added both feature requests.

**Comment by DeShadow** [comment]
@hkernbach Thank you very much for so quick answer! 👍

**Comment by hkernbach** [comment]
ArangoDB 3.1 has been released. Please note that the download urls and repositories have changed slightly. 

[Download](https://www.arangodb.com/download) or see [Release Notes](https://docs.arangodb.com/3.1/Manual/ReleaseNotes/NewFeatures31.html) for details.
