### ISSUE TITLE
Query builder in web-interface. BindVars are not restored correctly

### ISSUE THREAD

**Issue by DeShadow** [arangodb/arangodb#2112]
ArangoDB 3.1rc2

BindVars are not restored correctly when web-interface try to restore bindVars.

Simple reproducing of issue:
- Write query with parameters
- Set parameters
- Select all text of query, Cmd+C and after that Cmd+V

BindVars are restored, but they are shown only in table mode, not json mode. And if you try to execute query, you will get errors that bindVars are not set.

**Comment by DeShadow** [comment]
@hkernbach Maybe video could help: [YouTube](https://youtu.be/IpUMWixKbgg)

**Comment by hkernbach** [comment]
https://github.com/arangodb/arangodb/commit/e181457fac5492d511ef6fc27c60499bf2f796bb
should fix this issue (devel).

**Comment by DeShadow** [comment]
@hkernbach I found one more issue... Object parameters are not restored correctly (like strings "[Object Object]")

**Comment by hkernbach** [comment]
Thanks. Also fixed in devel
cd3a5b4e4591ec9e5fd17b8f756dd455c2e3fc5f

**Comment by hkernbach** [comment]
ArangoDB 3.1 has been released. Please note that the download urls and repositories have changed slightly. 

[Download](https://www.arangodb.com/download) or see [Release Notes](https://docs.arangodb.com/3.1/Manual/ReleaseNotes/NewFeatures31.html) for details.
