### ISSUE TITLE
Does ArangoDB support incremental backup and restore?

### ISSUE THREAD

**Issue by brucejee** [arangodb/arangodb#2113]
Anyone can tell me how can i do incremental backup and restore?
1. I have a DB in dev environment, and I add some data into DB.
2. How to backup beta added or updated data to production DB?

Just make dev DB and production DB into a cluster, and use replication between them?

Does only master can process write for master-slave cluster?
Does ArangoDB support master-master cluster? If Master-master replication support this?

**Comment by dothebart** [comment]
to me this sounds like you're looking for a solution like @virmundi s [migrantverde](https://github.com/deusdat/migrantverde)?

**Comment by brucejee** [comment]
It seems to be fixed by this tool, @dothebart thks! More a question, does arangodb will support incremental backup and restore?  orientdb also support this now.

**Comment by chrisLeeTW** [comment]
Hi, I have same question about the incremental backup and restore.

I had done some research on arangodump, and find out two execute options， --tick-start && --tick-end

And I also found out that I do get last tick number from arangodump output.

So can I safe to use this tick infomation to achieve incremental backup and restore? thks !
@dothebart

**Comment by deividasjackus** [comment]
Any new answers would be highly appreciated.

**Comment by saikrishna3281** [comment]
Hello, Do we have any update on this incremental backup? 
Should we use the --tick-start && --tick-end for achieving the incremental backup as mentioned by @chrisLeeTW
Thanks!

**Comment by graetzer** [comment]
No this does not work with rocksdb, and isn’t really a supported use case for mmfiles
You could periodically run a second ArangoDB instance as a replicated slave of the first one

**Comment by maxkernbach** [comment]
Hi all,

The `--tick start/end` option of `arangodump`  was only a temporary incremental backup solution **exlusively for the MMFiles storage engine**.

MMFiles is deprecated starting with version 3.6.0 and it will be removed in a future release. We recommend to switch to RocksDB even before the removal of MMFiles.

Our proper incremental backup solution [**Arangobackup**](https://www.arangodb.com/docs/stable/programs-arangobackup.html), which was introduced with v3.5.1 and v3.6.0, is a command-line client tool for instantaneous and consistent [hot backups](https://www.arangodb.com/docs/stable/backup-restore.html#hot-backups) of the data and structures stored in ArangoDB. It works **exclusively for the RocksDB Storage**.

Please note that `arangobackup` is only available in the Enterprise Edition.

Your feedback about Hot Backups would be highly appreciated.

**Comment by OmarAyo** [comment]
Hi @brucejee 

We haven't heard back from you recently, we are going to close this ticket

Feel free to reopen it by adding a new comment

Best
