### ISSUE TITLE
ArangoSearch storedValues: include fields from objects under array, ie. `array[*].field`

### ISSUE THREAD

**Issue by matcho** [arangodb/arangodb#21152]
## My Environment

* __ArangoDB Version__:        3.11.8
* __Deployment Mode__:       Leader/Follower ("Master/Slave")
* __Deployment Strategy__:   systemd
* __Infrastructure__:               own
* __Operating System__:       Ubuntu 22.04
* __Total RAM in your machine__:        256GB
* __Disks in use__:        SSD
* __Used Package__:              Ubuntu .deb

## Component, Query & Data

__Affected feature__:
ArangoSearch views

__Dataset__:
Documents of the form:
```json
{
  "_key": "…",
  "images": [
    {
      "id": "foo",
      "…": "…"
    },
    {
      "id": "bar",
      "…": "…"
    }
  ],
  "…": "…"
}
```

## Steps to reproduce

1. Try to create an ArangoSearch view with a link to the collection described above
2. Specify `"storedValues": { "fields": [ "images[*].id" ], "compression": "none", "cache": false }`
3. Get an error, view cannot be created

__Problem__:
How can one store values in a view, for fields that are under an array?

Thank you,
Best regards

**Comment by matcho** [comment]
Answering my own question here, by quoting a member of ArangoDB team (hope this is OK) :

> As of the current capabilities of ArangoDB, storedValues can be used to store scalar values and arrays of scalars, but not for complex objects inside arrays. This means you can store individual scalar fields or arrays of scalars but not nested objects within arrays directly.

> To handle objects inside arrays, a common approach is to flatten the structure or store individual scalar fields within the objects.

So it's not possible at this time, but can be worked around.

**Comment by dothebart** [comment]
Thanks!
