### ISSUE TITLE
Persistent indexes are not built correctly if documents have already been in collection.

### ISSUE THREAD

**Issue by DeShadow** [arangodb/arangodb#2118]
ArangoDB v3.1rc2

If i create new collection and create new persistent index, it works amazing.

Collection `test`. Persistent index on field `a`.

```
for i in 1..100
insert { a: i } in test
```

After that the query

```
for t in test
filter t.a == 1
return t
```

works fine and returns:

```
[
  {
    "_key": "97210151",
    "_id": "test/97210151",
    "_rev": "_T7GGq06---",
    "a": 1
  }
]
```

Then I remove index. And create the same again. The result of query becomes empty...
Let's add new part of data:

```
for i in 1..100
insert { a: i } in test
```

The result will be:

```
[
  {
    "_key": "97210546",
    "_id": "test/97210546",
    "_rev": "_T7GIoZe---",
    "a": 1
  }
]
```

But it not returns old document... The right answer must have two documents.

As you can see, persistent index not handle existing data.

**Comment by jsteemann** [comment]
Fixed in devel (will be merged into 3.1 branch eventually).

**Comment by DeShadow** [comment]
Thanks! :)

**Comment by hkernbach** [comment]
ArangoDB 3.1 has been released. Please note that the download urls and repositories have changed slightly. 

[Download](https://www.arangodb.com/download) or see [Release Notes](https://docs.arangodb.com/3.1/Manual/ReleaseNotes/NewFeatures31.html) for details.
