### ISSUE TITLE
Sync mongodb with arangodb

### ISSUE THREAD

**Issue by programmingprince** [arangodb/arangodb#2121]
We are using mongodb at present. We want to use arangodb on top of mongodb. For this, we need to sync them. How can we sync mongodb with arangodb?

**Comment by dothebart** [comment]
As long as you're only inserting values via Arangodb on single instances you could use the replication in a similar way as @baslr does in his [arangochair](https://github.com/baslr/arangochair) 

Regarding sync'ing the other way around - I don't have a good idea how to get latest changes from mongodb.

In general, ArangoDBs Multi model approach is meant to deliver a superset of MongoDB's features to circumvent the need for such workarounds.

**Comment by jsteemann** [comment]
Community suggestions for syncing MongoDB with ArangoDB are very welcome!

**Comment by dothebart** [comment]
Linking a SO question about the same topic: https://stackoverflow.com/questions/40107712/how-to-sync-mongodb-with-arango-db
