### ISSUE TITLE
AQL Analyzer with number return type gives odd results when getting tokens

### ISSUE THREAD

**Issue by Virock** [arangodb/arangodb#21222]
## My Environment

* __ArangoDB Version__:        3.11.1
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               N/A
* __Infrastructure__:               Own
* __Operating System__:        Windows 10
* __Total RAM in your machine__:       16GB
* __Disks in use__:        SSD
* __Used Package__:              N/A

## Component, Query & Data

__Affected feature__:
AQL query using web interface

__AQL query (if applicable)__:
```
RETURN TOKENS("abcd", "dd")
```
__AQL explain and/or profile (if applicable)__:

Explain Output
```
Query String (27 chars, cacheable: true):
 RETURN TOKENS("abcd", "dd")

Execution plan:
 Id   NodeType          Est.   Comment
  1   SingletonNode        1   * ROOT
  2   CalculationNode      1     - LET #0 = [ [ "oMAQAAAAAAAA", "sMAQAAAAAA==", "wMAQAAA=", "0MAQ" ] ]   /* json expression */   /* const assignment */
  3   ReturnNode           1     - RETURN #0

Indexes used:
 none

Optimization rules applied:
 none

43 rule(s) executed, 1 plan(s) created, peak mem [b]: 0, exec time [s]: 0.00015


```

Profile Output
```
Query String (27 chars, cacheable: false):
 RETURN TOKENS("abcd", "dd")

Execution plan:
 Id   NodeType          Calls   Items   Filtered   Runtime [s]   Comment
  1   SingletonNode         1       1          0       0.00000   * ROOT
  2   CalculationNode       1       1          0       0.00000     - LET #0 = [ [ "oMAQAAAAAAAA", "sMAQAAAAAA==", "wMAQAAA=", "0MAQ" ] ]   /* json expression */   /* const assignment */
  3   ReturnNode            1       1          0       0.00000     - RETURN #0

Indexes used:
 none

Optimization rules applied:
 none

Query Statistics:
 Writes Exec   Writes Ign   Scan Full   Scan Index   Cache Hits/Misses   Filtered   Peak Mem [b]   Exec Time [s]
           0            0           0            0               0 / 0          0              0         0.00019

Query Profile:
 Query Stage               Duration [s]
 initializing                   0.00000
 parsing                        0.00006
 optimizing ast                 0.00002
 loading collections            0.00000
 instantiating plan             0.00001
 optimizing plan                0.00005
 instantiating executors        0.00002
 executing                      0.00001
 finalizing                     0.00001


```

__Dataset__:
You don't need data in the database to test this

__Size of your Dataset on disk__:
1kb

__Replication Factor & Number of Shards (Cluster only)__:
N/A

## Steps to reproduce

1. Create an analyzer with the following settings
```
{
    "name": "dd",
    "type": "aql",
    "features": [],
    "properties": {
        "queryString": "RETURN LENGTH(@param)",
        "collapsePositions": false,
        "keepNull": true,
        "batchSize": 10,
        "memoryLimit": 1048576,
        "returnType": "number"
    }
}
```
2. Try to return tokens using that analyzer e,g, ```RETURN TOKENS("abcd", "dd")```

__Problem__:
It's supposed to simply return the number of characters in the input text  but it returns this:
```
[
  [
    [
      "oMAQAAAAAAAA",
      "sMAQAAAAAA==",
      "wMAQAAA=",
      "0MAQ"
    ]
  ]
]
```

__Expected result__:
It should return something like:
```
[
   4
]
```

I noticed 2 other things:
1. If I write an AQL query using the analyzer dd, it actually works
```
FOR doc IN someView
    SEARCH ANALYZER(doc.firstName == 3, "dd")
    RETURN doc
``` 
Even though it gives odd results when trying to get tokens, it returned the documents with first names with only 3 characters.

2. If I change the return type to string when creating the analyzer, gettings tokens work but of course, it returns the number of characters of the input data in string form.

**Comment by Simran-B** [comment]
This is the expected albeit not desirable behavior. The `TOKENS` function returns a serialization of the internal representation as it would enter the search index. For numbers but also the output of geopoint, collation, and other Analyzers, this representation is only useful internally. Some other Analyzers return regular strings as the processing is limited to e.g. tokenization and stemming without requiring a special representation.

**Comment by Virock** [comment]
Alright. Thank you for the explanation.
