### ISSUE TITLE
VelocyStream docs

### ISSUE THREAD

**Issue by chikhpykh** [arangodb/arangodb#2123]
## my environment running ArangoDB

Ubuntu 16.04.1 x64
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [x] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [ ] Debian .deb
  - [x] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

could you share VelocyStream documentation? What is the way to use velocystream in 3.1?
What data types are supported in that protocol now? In some issue there was comment that velocystream will support only few data types.
Where is specification on VelocyStream ?

I want to write arangodb driver in go to use future 3.1 release. So is it possible to read velocystream specs now?

Thanks

**Comment by neunhoef** [comment]
Sorry for the long delay. ArangoDB 3.1 has an implementation of the new VelocyStream protocol. However, we have intentionally not yet published a document describing it. We would like to reserve the right to change things at least until the 3.2 release early next year. If you write me a private email to max at arangodb.com, I can send you the current draft of the specification. Note however, that it already contains a minor change which is not even now implemented in the development version. I can point you to this small cahnge. The specification is still work in progress.

**Comment by baslr** [comment]
@chikhpykh are you on the ArangoDB slack channel?

**Comment by dothebart** [comment]
We're pleased to anounce that ArangoDB 3.2, making the velocystream design final. 

Thus we now release the documentation via: 

https://github.com/arangodb/velocystream

Closing.
