### ISSUE TITLE
Docker build, entering password fails

### ISSUE THREAD

**Issue by dgj001** [arangodb/arangodb#21248]
## My Environment

* __ArangoDB Version__:        3.10.14
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start in Docker

## Steps to reproduce

I'm trying to create a docker container with v3.10 of ArangoDB.

Here's my Dockerfile:
FROM node:16
RUN apt-get update
RUN curl -OL https://download.arangodb.com/arangodb310/DEBIAN/Release.key
RUN apt-key add - < Release.key
RUN echo 'deb https://download.arangodb.com/arangodb310/DEBIAN/ /' | tee /etc/apt/sources.list.d/arangodb.list
RUN apt-get install apt-transport-https
RUN apt-get update
RUN apt-get install arangodb3=3.10.14-1
RUN apt-get install -y vorbis-tools
WORKDIR /usr/src
COPY package.json ./
COPY yarn.lock ./
RUN yarn
RUN npm install -g nodemon
WORKDIR /usr/src/app
CMD ["./run.sh"]

When I attempt to build the image/container, it gets to the step where it is installing arangodb3, and asks for a password.  I enter a password, and it just hangs.  What am I missing?  The Dockerfile worked fine with v3.4 until the signature in Release.key expired.

Building web
Step 1/16 : FROM node:16
 ---> 993a4cf9c1e8
Step 2/16 : RUN apt-get update
 ---> Using cache
 ---> 1503d2b6d7f8
Step 3/16 : RUN curl -OL https://download.arangodb.com/arangodb310/DEBIAN/Release.key
 ---> Using cache
 ---> 4a1e7a14184b
Step 4/16 : RUN apt-key add - < Release.key
 ---> Using cache
 ---> 33881f99900c
Step 5/16 : RUN echo 'deb https://download.arangodb.com/arangodb310/DEBIAN/ /' | tee /etc/apt/sources.list.d/arangodb.list
 ---> Using cache
 ---> 3fc6f20d95d4
Step 6/16 : RUN apt-get install apt-transport-https
 ---> Using cache
 ---> 396e7b449340
Step 7/16 : RUN apt-get update
 ---> Using cache
 ---> f29b516632d7
Step 8/16 : RUN apt-get install arangodb3=3.10.14-1
 ---> Running in 716b4c47eb7c
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  arangodb3
0 upgraded, 1 newly installed, 0 to remove and 113 not upgraded.
Need to get 178 MB of archives.
After this operation, 357 MB of additional disk space will be used.
Get:1 https://download.arangodb.com/arangodb310/DEBIAN  arangodb3 3.10.14-1 [178 MB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 178 MB in 5s (35.6 MB/s)
Selecting previously unselected package arangodb3.
(Reading database ... 23990 files and directories currently installed.)
Preparing to unpack .../arangodb3_3.10.14-1_amd64.deb ...
Unpacking arangodb3 (3.10.14-1) ...
Setting up arangodb3 (3.10.14-1) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
Configuring arangodb3
---------------------

Please enter the password for the database root user account that should be
granted administrative privileges

password for the ArangoDB "root" user:

**Comment by dothebart** [comment]
Hi, 
Please note that ArangoDB 3.10  support has  ended on 15th  April  2024. 

For a while now, ArangoDB docker containers are based on alpine and use portable static binaries.
So whatever your direction may be, choosing the tarball over the debian  package inside the container is probably the better way to go.  
Deriving the ArangoDB docker container instead would also work around these issues for you.
