### ISSUE TITLE
Golang driver for arangodb

### ISSUE THREAD

**Issue by chikhpykh** [arangodb/arangodb#2124]
Hello. Do you plan to support golang driver for arangodb with core team.
Golang is very popular now for backend development. So it will be a great way to popular arangodb too.

Thanks

**Comment by stevedumais** [comment]
My org would love this as well.

**Comment by starJammer** [comment]
Me too! I wrote my own small driver but the http return error codes that get returned seem to change with each release and it's a bit annoying.

**Comment by baslr** [comment]
Hi @chikhpykh @stevedumais @starJammer @opavader @mikeifomin,

the ArangoDB team released their golang driver (work in progress).
Please have a look at https://github.com/arangodb/go-driver.

**Comment by stevedumais** [comment]
Thanks for the heads up @baslr!

**Comment by starJammer** [comment]
This is awesome!

**Comment by jsteemann** [comment]
Closing this issue as there is now an official golang driver.
