### ISSUE TITLE
Importing data  with Arangoimp, it throws the "out of memory" error. 

### ISSUE THREAD

**Issue by saliormoon** [arangodb/arangodb#2127]
## my environment running ArangoDB

I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [x] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [x] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:
## My problem is:

When I import json file  which size is 148G  to a created collection  with Arangoimp, it throws the "out of memory" error. How can I solve it? 
Any suggestion is appreciated greately.

**Comment by dothebart** [comment]
With arangodb 3.1.16 (available for download) we have changed the configuration behaviour of the cache plus fix the maximum number of open files - which caused this behaviour. I was able to import CSVs in the double size of my main memory without issues now.
