### ISSUE TITLE
arangoimp - persistent index - Expecting type Array

### ISSUE THREAD

**Issue by schroedingerdb** [arangodb/arangodb#2133]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.0

On this operating system:
- [ ] DCOS on
  - [x] own infrastructure
- [ ] Linux 
  - [x] Debian .deb

I'm issuing AQL via:
- [x] arangosh

Setup:
- 3 x Agent
- 3 x Database
- 1 x Coordinator

## setup collection document
```
$arangosh --server.endpoint tcp://localhost-1:8530 --server.database "test" --server.username root

localhost-1:8530@test-db> db._create('test_bug', { waitForSync : true, numberOfShards: 6, shardKeys: ["_key"] });
[ArangoCollection 705955592, "test_bug" (type document, status loaded)]

localhost-1:8530@test-db> db.test_bug.ensureIndex({ type: "persistent", fields: [ "id-2", "value" ], sparse: false });
{ 
  "fields" : [ 
    "id-2", 
    "value" 
  ], 
  "id" : "test_bug/705955601", 
  "sparse" : false, 
  "type" : "persistent", 
  "unique" : false, 
  "isNewlyCreated" : true, 
  "code" : 201 
}
```

## test csv
```
$cat test.csv 
id-1,id-2,value
1,1,3
1,2,3
1,3,3
```

## import data & error
```
$arangoimp --file /mnt/data01/csv/test.csv --type csv --collection test_bug --server.database test  --server.endpoint tcp://localhost-1:8530
Please specify a password: 
Connected to ArangoDB 'http+tcp://localhost-1:8530', version 3.0.10, database: 'test', username: 'root'
----------------------------------------
database:               test
collection:             test_bug
create:                 no
source filename:        /mnt/data01/csv/test.csv
file type:              csv
quote:                  "
separator:              
connect timeout:        5
request timeout:        1200
----------------------------------------
Starting CSV import...

2016-10-28T12:24:22Z [3938] ERROR error message:    Expecting type Array (exception location: /usr/src/packages/BUILD/arangod/HttpServer/HttpHandler.cpp:157). Please report this error to arangodb.com
```

## This error not occur when

(1) I delete the persistent index
(2) Or I have only 2 rows in my csv

```
$cat test.csv 
id-1,id-2,value
1,1,3
1,2,3

$arangoimp --file /mnt/data01/csv/test.csv --type csv --collection test_bug --server.database test --server.endpoint tcp://localhost-1:8530
Please specify a password: 
Connected to ArangoDB 'http+tcp://localhost-1:8530', version 3.0.10, database: 'test', username: 'root'
----------------------------------------
database:               test
collection:             test_bug
create:                 no
source filename:        /mnt/data01/csv/test.csv
file type:              csv
quote:                  "
separator:              
connect timeout:        5
request timeout:        1200
----------------------------------------
Starting CSV import...

created:          2
warnings/errors:  0
updated/replaced: 0
ignored:          0
lines read:       3
```

**Comment by jsteemann** [comment]
I tried to reproduce this in both a non-clustered instance and in a cluster with the number of nodes specified, but wasn't able to reproduce the error. I also tried importing more data. I tried it with latest 3.0 (the current state of the `3.0` branch which will eventually become 3.0.11).

Is the problem reproducible on your end?

**Comment by schroedingerdb** [comment]
Hello Jan,

after writing this issue, I tried to import a large csv againand I got a lot of "Too many open files" error.
Maybe this import error occurs only because of some other wrong thinks on my side. I will setup another fresh cluster (soft and hard file limits are already increased) and try to reproduce it again.

Thank you for your time.

**Comment by schroedingerdb** [comment]
@jsteemann After change my open file limit, the issue is not reproducible anymore :) Sry for wasting time - no product by the way :D

'''
$nano /etc/security/limits.conf

*         hard    nofile      500000
*         soft    nofile      500000
root      hard    nofile      500000
root      soft    nofile      500000
'''

**Comment by jsteemann** [comment]
No worries. The original error indeed looks to me like something else went wrong inside the cluster communication, but it was probably not directly related to the persistent indexes.
