### ISSUE TITLE
[feature] handling undirected edges themself natively

### ISSUE THREAD

**Issue by kkdd** [arangodb/arangodb#21347]
Hello,
Can ArangoDB handle undirected edges themself natively?

This feature would be represended as ```{"_from": "Mary", "_to": "John", "_id": "isFriendOf/1234", "directionality": "undirected"}```, but not ```[{"_from": "Mary", "_to": "John", "_id": "isFriendOf/1234"}, {"_from": "John", "_to": "Mary", "_id": "isFriendOf/12345"}]```, for example.

**Comment by dothebart** [comment]
You specify the direction you want to go by [`INBOUND`| `OUTBOUND`|`ANY`] https://docs.arangodb.com/stable/aql/graphs/traversals/.
The graphs themselves can't be restricted in direction, just the query.

**Comment by kkdd** [comment]
Thank you for your explanation.
Does it mean that ```{"_from": "Mary", "_to": "John"}``` itself natively describes the relation of both directions, forward and reverse, in ArandoDB?

**Comment by Simran-B** [comment]
As @dothebart explained, you can only specify the traversal direction in queries (including walking edges in both directions). This applies to the entire traversal, not individual edges. It's not data-defined if you will.

**Comment by dothebart** [comment]
The direction (the arrow in your picture) of the edge is set by `_from` and `_to`. This then relates to what [`INBOUND`| `OUTBOUND`|`ANY`] will do with these edges.

**Comment by kkdd** [comment]
Thank you for your explanation.
And I see that:
> This applies to the entire traversal, not individual edges. It's not data-defined if you will.

That may be because ArangoDB is not based on a [mixed graph](https://en.wikipedia.org/wiki/Mixed_graph) model, but on a [directed graph](https://en.wikipedia.org/wiki/Directed_graph) one, where the entire traversal can select the directions of boundness by using additional functionality. So, my expectation for individual edges would not be easily realized in ArangoDB.

**Comment by dothebart** [comment]
you can filter additionally on edges on defined depths if you choose `any`. maybe you should have a look at the graph course? https://arangodb.com/learn/

**Comment by kkdd** [comment]
Thank your for your information.
I'm looking forward to some systems based on a [mixed graph](https://en.wikipedia.org/wiki/Mixed_graph) model. Or I would make a minimal one by myself in the way of my primitive trial in [GraphFromOSM](https://github.com/kkdd/GraphFromOSM#definition-of-a-graph-variable-in-this-fork).
