### ISSUE TITLE
Cant join slack

### ISSUE THREAD

**Issue by ronenlinx** [arangodb/arangodb#21353]
How can i join the Slack workspace? seems like you have to have @arangodb email for it

**Comment by jbajic** [comment]
We have a community slack that you can join at [arangodb-community.slack.com](https://arangodb-community.slack.com/)

**Comment by ronenlinx** [comment]
It required arangodb email to join. Can i join with my email?

**Comment by jbajic** [comment]
I think you should be able to create a community slack account using this URL https://join.slack.com/t/arangodb-community/shared_invite/zt-2i8ct8qbl-PH5vESfnzbJdV~~VuawhVA

**Comment by ronenlinx** [comment]
thank you
