### ISSUE TITLE
AQL Query results with 0 elements crashes UI 

### ISSUE THREAD

**Issue by nirav696** [arangodb/arangodb#21393]
## My Environment

* __ArangoDB Version__: 3.12.2 Enterprise
* __Deployment Mode__: Single Server
* __Deployment Strategy__: sytemd
* __Infrastructure__: own
* __Operating System__: Ubuntu 22.04
* __Total RAM in your machine__: 64GB
* __Disks in use__: SSD
* __Used Package__: Ubuntu .deb

## Component, Query & Data

__Affected feature__:
AQL query using web interface

__AQL query (if applicable)__:
```
filter false
return "abc"

```
__AQL explain and/or profile (if applicable)__:

When running any AQL query that returns 0 elements, the UI crashes.
The above query is just for reproducing the error. Any query that gets filtered down to 0 elements, crashes the UI. 

__Dataset__:

30 collections, having from 10 documents to 200M documents.

__Size of your Dataset on disk__:

300GB

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1.  Run any Query on Arango UI with version 3.12.2 that returns 0 elements
2.  UI Crashes and no results are shown
3.  The same query when tested on 3.12.1 works fine

__Problem__:
Crashing of Arango UI on AQL query execution where there are no results

__Expected result__:
On AQL query execution on UI it should show 0 elements if there are no results

**Comment by Simran-B** [comment]
I can reproduce the problem with the `arangodb/enterprise:3.12.2` image but not `arangodb/enterprise-preview:devel-nightly`. Therefore, it seems to be fixed for the upcoming 3.12.3.

**Comment by dothebart** [comment]
confirmed as being solved by https://github.com/arangodb/arangodb/commit/b44407d996e16ec444b34118aaf3765e44612c45#diff-ecec88c33adb7591ee6aa88e29b62ad52ef443611cba5e0f0ecac9b5725afdbaR4

**Comment by nirav696** [comment]
ok, thank you! is there a release date for 3.12.3?

**Comment by dothebart** [comment]
Its being worked on. Releases are anounced through the regular channels.
Usually we wouldn't close this issue until a release containing the fix is availabel - and then close it.
