### ISSUE TITLE
unable to initialize RocksDB engine: IO error: While lock file: /opt/arangodb/data/engine-rocksdb/LOCK: Resource temporarily unavailable; Maybe your filesystem doesn't provide required features? (Cifs? NFS?)

### ISSUE THREAD

**Issue by hubcomsix** [arangodb/arangodb#21417]
## CurrentBehavior 
unable to initialize RocksDB engine: IO error: While lock file: /opt/arangodb/data/engine-rocksdb/LOCK: Resource temporarily unavailable; Maybe your filesystem doesn't provide required features? (Cifs? NFS?)

**Comment by dothebart** [comment]
if you inspect your arangodb logfile, you will probably find several processes writing to it at the same time. 
the PID of the processes can be observed in the square brackets `[1234]` - the one trying to write it and failing gave you above error.
