### ISSUE TITLE
Fulltext Index - no more as one field, no weight, no score, etc.

### ISSUE THREAD

**Issue by admtech** [arangodb/arangodb#2143]
I'm using the latest ArangoDB 3.0 on Linux with the php driver. ArangoDB is great but i miss some important fulltext features:

In real Application we have mostly more the one field in the fulltext index, e.g. Title and Content. The solution to solve this over the application is very impractical since you can not put any weight on the fields. So, if we have more fields, we need e.g. a higher weight in the title than in the content. Next we need a score to sort the result better (how is currently sorted, i found no info about this in the docs). Where are the stopwords or the infix support?

So we need a better Fulltext index and FULLTEXT() AQL Functions:

- more then "one attribute fields only" (very important)
- weight settings if we have more the one attribute fields (very important)
- also weight settings for index attributes (nice to have)
- in search result:  a score that we can sort and see (and more: min, max, bigger or smaller as score x and so on - very important)
- a configurable stoplist (very important)
- also infix Support (nice to have)

So if you make a comparison with the MongoDb you should be least equal. The actual fulltext index can not really be used in real websites or application. It lacks too much. Please add these features in a future release.

Best regards
Frank from Germany

**Comment by homerjam** [comment]
+1

**Comment by Yess11** [comment]
+1

**Comment by Simran-B** [comment]
Have a look here about the upcoming ArangoSearch: https://www.arangodb.com/tutorials/arangosearch/part1-getting-started/

**Comment by remingtonc** [comment]
@Simran-B Part 2 seems to have some content that references a previous version of the doc (or I'm just not getting it :)), would recommend having it revisited. https://www.arangodb.com/tutorials/arangosearch/part2-basic-querying/

**Comment by Simran-B** [comment]
@remingtonc Not sure what you mean. There is very little documentation on docs.arangodb.com for ArangoSearch, and only in the devel version (it's still work in progress). Do the examples from the tutorial not work with the nighly builds, but only with older previews?

**Comment by Simran-B** [comment]
https://www.arangodb.com/docs/stable/arangosearch.html

**Comment by Simran-B** [comment]
No, ArangoSearch is a separate feature. The `FULLTEXT()` function will not be extended.
