### ISSUE TITLE
Conditional INSERT adds doc although condition evaluates to False

### ISSUE THREAD

**Issue by schmidtje** [arangodb/arangodb#21449]
## My Environment

* __ArangoDB Version__:       3.10

## Component, Query & Data

__Affected feature__: AQL and data insertion

__AQL query (if applicable)__:
```
LET x = True
LET y = x ? (
    INSERT {"comment": "x", "x": x} IN Test1
    RETURN NEW
  ) : (
    INSERT {"comment": "!x", "x": x} IN Test2
    RETURN NEW
  )
RETURN y
```
__AQL explain and/or profile (if applicable)__:
![image](https://github.com/user-attachments/assets/4f3b3085-90cb-40c9-8e5b-02690a7bcf83)
<img src="https://github.com/user-attachments/assets/5b523d58-e624-4c76-853e-001bc1ac0809" width="400">

## Steps to reproduce

1. create collections `Test1` and `Test2`
2. run query

__Problem__:

The document in the else-branch is inserted to `Test2` although the if-condition evalualtes to `True` and hence the else-branch should not be executed. However, the result is as expected. Seemingly the reason for this can be seen in the AQL explanation, where both `INSERT`s are performed independent of the condition. 
<img src="https://github.com/user-attachments/assets/0ed1dcc4-6178-49b3-a4a3-eaca52f82808" width="400">

__Expected result__:
Only insert the document of the if-branch to `Test1` (or more general: only perform `INSERT` wrt to conditions)

**Comment by Simran-B** [comment]
This is the documented behavior, see the call out box:
https://docs.arangodb.com/3.10/aql/operators/#ternary-operator

From 3.12.1 onward, the behavior has been changed to work as you desire:
https://docs.arangodb.com/stable/aql/fundamentals/subqueries/#evaluation-of-subqueries

Take a look at the content at the bottom of the "Up to v3.12.0" tab. It shows an example of how you can write a query in earlier versions that only executes one branch of the ternary operator.
