### ISSUE TITLE
Error when upgrade foxx code in cluster

### ISSUE THREAD

**Issue by de3** [arangodb/arangodb#2144]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [x] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [x] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### Foxx

I have an issue when update Foxx code in cluster environment. Currently I have 2 coordinator, I have success when install new foxx from one of coordinator. But when I try to update code using upgrade command
`foxx-manage upgrade`

I get error like this: 
**couldn't queue async request**

when I check arangod log, it show:
**did not find endpoint of server 'undefined'**

this error will not occur if I use 1 coordinator

**Comment by pluma** [comment]
/cc @kvahed 

This sounds like the issue you were looking into earlier this week on Slack.

**Comment by de3** [comment]
@pluma
