### ISSUE TITLE
 TO_STRING is not defined

### ISSUE THREAD

**Issue by firas2010** [arangodb/arangodb#2145]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
 
- [ ] 3.0
 

On this operating system:
 
 
- [ ] Windows, version: 10
 

### undefined function :
[ ] I'm using arangosh shell
 
- [ ] TO_STRING is not defined at <shell command>:1:1

**Comment by jsteemann** [comment]
Without further information I can only guess what happened, so it would be helpful if you could post here what kind of action you executed when that error message occurred, and what the exact command was.

My guess is that you tried to execute an AQL query from the ArangoShell.

Please note that the ArangoShell executes *JavaScript* commands, not *AQL*. Anything that is not valid JavaScript will not compile and throw an error in the ArangoShell. That also means that the functions that are present in AQL cannot be used from the ArangoShell directly, but only within AQL queries. 

Of course the ArangoShell provides a way to execute AQL queries. To execute an AQL query from the shell, please use `db._query("<query string goes here>").toArray();`, e.g. `db._query("RETURN TO_STRING(42 * 42)");`

**Comment by firas2010** [comment]
Thank you so much. This helped me in solving the issue. Really appreciate that.
