### ISSUE TITLE
arangodb3 package installs empty README.txt file

### ISSUE THREAD

**Issue by jsteemann** [arangodb/arangodb#2146]
When installing the Ubuntu 16.04 ArangoDB 3.1 package via dpkg -i, it installs some files in /usr/share/doc/arangodb3. 
Among these files there is `README.md`, which is fine, but also an empty file `README.txt`. It is probably unintentional that this file is empty.

**Comment by dothebart** [comment]
fixed by 55ce25ac83e81ef792be38c95f763a88fbed5e25
