### ISSUE TITLE
[Feature Request] Implement node's util module in ArangoDB to support TextEncoder and TextDecoder

### ISSUE THREAD

**Issue by konsultaner** [arangodb/arangodb#21479]
I want to write a Foxx service that utilizes [`autobahn-js`](https://github.com/crossbario/autobahn-js) to connect to my WAMP infrastructure. This is not possible at the moment since some of the production deps use node `util.TextEncoder`

This is related to #12733

if this is not possible, is it possible to provide packages to V8 (i guess) so I and others can overcome this incompatibilities?

Maybe by having a setup/config script where one could provide a custom implementation of i.e. TextEncoder?

**Comment by dothebart** [comment]
No, there is currently no way to run async requests from Foxx, and most certainly never will be.

**Comment by konsultaner** [comment]
ah ok, well that will make this issue useless. Thanks for clarifying @dothebart
