### ISSUE TITLE
Using Custom JWT for API Authentication in ArangoDB Cloud Enterprise

### ISSUE THREAD

**Issue by ajit-Xebia** [arangodb/arangodb#21506]
In the ArangoDB Community version, we can access all Foxx microservices APIs without restrictions, as the APIs are open and do not require authentication. However, in the ArangoDB Cloud Enterprise version, API access requires a JWT token generated using database user credentials (username and password). This setup presents challenges, as we want to avoid exposing or using database user credentials for generating tokens.

Currently, to authenticate API calls, we need to first generate a database-specific JWT using the database user credentials and include it in the request. Additionally, we also append our custom JWT (used for our application’s internal authentication) with a different name in the same request. This approach adds complexity and creates redundancy, as we are forced to handle two separate JWTs.

Given these constraints, we want to explore the possibility of directly using our custom JWT for API authentication in the Cloud Enterprise setup. Is there a way to configure the system to accept our custom JWT for authenticating requests, without requiring the database JWT or exposing database user credentials?

We would appreciate any guidance on how to simplify this workflow or any alternative solutions that can better support this use case.

**Comment by dothebart** [comment]
Hi, 
This can be configured by the operations Team. 
Please raise an ArangoGraph support ticket, so they know which installation to work with and so on.

**Comment by dothebart** [comment]
Closing as solved.
