### ISSUE TITLE
AQL: Array comparison operators on an empty array

### ISSUE THREAD

**Issue by gamedev8** [arangodb/arangodb#2150]
All array comparison operators return true when the array is empty, despite the right hand side value.

For example, both of the following return **true**:

```
return [] none == "foo"
```
```
return [] all == "foo"
```

**Comment by pekeler** [comment]
I think this behaviour is correct. It is matching my expectations.

**Comment by Simran-B** [comment]
The behavior has actually changed starting with 3.1:

https://docs.arangodb.com/3.1/Manual/ReleaseNotes/UpgradingChanges31.html#aql
