### ISSUE TITLE
MacOS brew install instructions not correct for 3.1

### ISSUE THREAD

**Issue by vsivsi** [arangodb/arangodb#2152]
The [MacOS install page](https://www.arangodb.com/download/macosx/) says:

> For Mac OS X you can use use homebrew to install ArangoDB. Run the following:
>
> `brew install arangodb3`
>
>This install ArangoDB in the latest stable version using homebrew.

I have run `brew update` and then the command above, and I get this:
```
$ brew update

Already up-to-date.

$ brew install arangodb3

Error: No available formula with the name "arangodb3" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
```

Below the above quoted section the instructions also make reference to installing from `arangodb` via `brew install --HEAD arangodb`.  However, attempting to do a non-HEAD install from this brew formula/tap leads to this installation of version 3.0.5, not 3.1.0:

```
$ brew install arangodb

==> Downloading https://homebrew.bintray.com/bottles/arangodb-3.0.5.el_capitan.bottle.tar.gz
Already downloaded: /Users/vsi/Library/Caches/Homebrew/arangodb-3.0.5.el_capitan.bottle.tar.gz
==> Pouring arangodb-3.0.5.el_capitan.bottle.tar.gz
==> Using the sandbox
==> /usr/local/Cellar/arangodb/3.0.5/libexec/arangodb2/bin/upgrade.sh /usr/local/Cellar/arangodb/3.0.5/libexec/arangodb2 /usr/local/var/lib/arangodb
==> Caveats
The database format between ArangoDB 2.x and ArangoDB 3.x has
been changed, please checkout
https://docs.arangodb.com/3.0/Manual/Administration/Upgrading/index.html

An empty password has been set. Please change it by executing
  /usr/local/opt/arangodb/sbin/arango-secure-installation

To have launchd start arangodb now and restart at login:
  brew services start arangodb
Or, if you don't want/need a background service you can just run:
  /usr/local/opt/arangodb/sbin/arangod
==> Summary
🍺  /usr/local/Cellar/arangodb/3.0.5: 8,952 files, 300.7M
```

The above linked instructions imply that brew can be used to install 3.1.0, but that does not currently seem to be the case...

**Comment by dothebart** [comment]
its not yet ready. Please use the .dmg meanwhile.

**Comment by vsivsi** [comment]
Might I respectfully suggest that the install page be changed in the meantime to reflect this?
Currently a person evaluating ArrangoDB for the first time will potentially have an install failure as their first "out of the box" experience. Not good.

**Comment by dothebart** [comment]
Meanwhile the 3.1.1 is available via homebrew - closing.
