### ISSUE TITLE
RHEL 6 Binaries For ArangoDB 3.1

### ISSUE THREAD

**Issue by sajeevpr** [arangodb/arangodb#2154]
Dear Team,
  Could you please provide the RHEL 6 binaries for version 3.1. When I tried the rpm available in your download site, I got the below error.

./arangod: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by ./arangod)
./arangod: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./arangod)

But this error was not coming for 3.1rc2.

Regards,
Sajeev

**Comment by dothebart** [comment]
RHEL6 binaries are still pending. We need to get the build docker container working again; please use a RHEL7 / Centos 7 environment in the meantime.

**Comment by sajeevpr** [comment]
@dothebart 
  Thank your for your reply. Will wait for RHEL 6 binaries as we don't have any other option at the moment.

Regards,
Sajeev

**Comment by mikeatm** [comment]
similar issue, but for Fedora, there are no RPMs for  3.1x, any reasons?

**Comment by sajeevpr** [comment]
@dothebart , looking forward for RHEL 6 binaries for 3.1.1.

**Comment by dothebart** [comment]
@sajeevpr  since its quiet a hassle to get that done its not that high on our priority list. 
@mikeatm feel free to propose a solution for https://issues.jenkins-ci.org/browse/JENKINS-39307 which is holding back fedora packages.

**Comment by sajeevpr** [comment]
@dothebart , If you can tell the required details, I can attempt to create the binaries for redhat 6.6

**Comment by dothebart** [comment]
we need a reliable source for cmake 3.6; so far we did so using the suse OBS which currently is a hassle to keep working. Once https://github.com/arangodb-helper/build-docker-containers/tree/master/distros/centos/6/build is working again, I can provide you with rpms at the snip of a finger ;)

**Comment by dothebart** [comment]
ArangoDB 3.1.2 is available for download including Centos 6 / RHEL 6 packages.

**Comment by sajeevpr** [comment]
Thank you. Will try this out.

**Comment by mikeatm** [comment]
Looks like there is now a missing update? 

```
[root@store ~]# dnf  install arangodb3
Last metadata expiration check: 0:03:59 ago on Thu Feb 16 13:13:16 2017.
Dependencies resolved.
==================================================================================================================================================================================
 Package                                   Arch                                   Version                                        Repository                                  Size
==================================================================================================================================================================================
Installing:
 arangodb3                                 x86_64                                 3.2.alpha1-1                                   arangorepo                                  36 M

Transaction Summary
==================================================================================================================================================================================
Install  1 Package

Total download size: 36 M
Installed size: 124 M
Is this ok [y/N]: y
Downloading Packages:
[MIRROR] arangodb3-3.2.alpha1-1.x86_64.rpm: Status code: 404 for https://www.arangodb.com/repositories/arangodb31/Fedora_25/x86_64/arangodb3-3.2.alpha1-1.x86_64.rpm             
[FAILED] arangodb3-3.2.alpha1-1.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success                                                              

The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Error downloading packages:
  Cannot download x86_64/arangodb3-3.2.alpha1-1.x86_64.rpm: All mirrors were tried
```

**Comment by dothebart** [comment]
Hi, I'm sorry we mixed up distribution channels here.
Should be fixed as of saturday night.
