### ISSUE TITLE
Using Joins vs Edges

### ISSUE THREAD

**Issue by sajeevpr** [arangodb/arangodb#2155]
Dear Team, 

  We are trying to get data from two collections - Account and Resource, both having a common field named accountKey. We would like to know which would be the best way to get data. I think there are two options.
 1. Use Joins
 2. Create edges.

Which way would you recommend.?

Thanks & Regards,
Sajeev

**Comment by roman1720** [comment]
Joins if you don't need graph functions. With joins you don't have to create extra edge collection

for a in Account
for r in Resource
filter a.accountKey == r.accountKey
return merge(a, r)

**Comment by sajeevpr** [comment]
@roman1720 
  Thanks for your reply. I hope the query performance would be same for both the cases.

Regards,
Sajeev

**Comment by sajeevpr** [comment]
@roman1720 
  Thank you for your reply. We will go ahead with joins then.

Thanks & Regards,
Sajeev

**Comment by baslr** [comment]
@sajeevpr if your question was answered feel free to close this issue.
