### ISSUE TITLE
Foxx: service misconfiguration resulting in configuration leak

### ISSUE THREAD

**Issue by sinfex** [arangodb/arangodb#2156]
I'm using the latest ArangoDB of the respective release series: 3.0.10
On this operating system: CentOS Linux 7.2

In the case of misconfiguration, active Foxx service configuration details should not be included in the HTTP response body out of security concerns.

The following example configuration could be present in a service's manifest:

```
"configuration": {
	"nonImportantOption": {},
	"secretKey": {
		"description": "Pretty secret key",
		"type": "password"
	}
}
```

Whether the service is deployed with a faulty/missing configuration or if it happens later on, potentially sensitive active configuration is leaked to clients:

![image](https://cloud.githubusercontent.com/assets/8995502/20090654/c4f1c60c-a58e-11e6-8069-3c5208695129.png)

**Comment by pluma** [comment]
Hm... good point. This could be a problem if you accidentally misconfigure a service (e.g. via an upgrade that adds required config options). There's probably no need to show this information ever as it can also be accessed via an API.

**Comment by pluma** [comment]
By the way, this should currently only appear if the service is running in development mode, which you shouldn't be doing in production. But I don't think this is useful anymore.
