### ISSUE TITLE
Modifying Access-Control-Expose-Headers from within foxx service results in doubled header

### ISSUE THREAD

**Issue by clamor** [arangodb/arangodb#2159]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.1

On this operating system:
  - [x] docker - official docker library

### Foxx

I attached an angular based WebGUI for CRUD ( https://github.com/marmelab/ng-admin ) to a arangodb foxx service. That works fine, as long as the gui files are served directly from within arangodb.

When the gui is moved to another server, I have to modify Access-Control-Expose-Headers in the response to allow a X-Total-Count header in the response. Setting the x-total-count header for the reponse works fine from within router.get(... but I did not manage to modify the access-control-expose-headers to allow the x-total-count. Any hints where I can change this?

And btw., thanks for your great product.

**Comment by jsteemann** [comment]
It looks like the `Access-Control-Expose-Headers` response header is always overwritten by the server code when the response is sent. Foxx apps currently cannot set it to a different value than the hard-coded one shown above.
I have submitted a fix for this which allows setting the header to a different value, by simply using `res.headers["access-control-expose-headers"] = ...` as for any other HTTP response header.
The fix has been pushed into 3.0, 3.1 and devel branches and will be included in the next releases (3.0.12, 3.1.1).

**Comment by clamor** [comment]
Works like a charm. Thank you.
