### ISSUE TITLE
Foxx: reloading a service does not remove no longer existing configuration keys

### ISSUE THREAD

**Issue by sinfex** [arangodb/arangodb#2162]
I'm using the latest ArangoDB of the respective release series: 3.0.10
On this operating system: CentOS Linux 7.2
Foxx service mode: **Development**

Manifest:
```
"configuration": {
	"temporary": {}
}
```

1. Set `temporary` to anything for the setting to be saved (stored in the `_apps` collection)
2. Remove the configuration setting `temporary` from the manifest as a whole
3. Service gets automatically reloaded in development mode
4. Service configuration is not updated (old `temporary` value still set)
5. Subsequent requests to the service result in warnings:

```
2016-11-09T11:18:34Z [19568] WARNING Stored configuration for app "/test" has errors:
2016-11-09T11:18:34Z [19568] WARNING Unexpected option "temporary"
```

**Comment by pluma** [comment]
This should be fixed in 3.1.0 (and the upcoming 3.0.11 release).

Can you check whether this still occurs after upgrading to 3.1?

**Comment by sinfex** [comment]
I believe the warning should stay there, especially since this is very unlikely to be a problem with applications in Production mode. But it would be nice if Aardvark would also display values that are stored in the configuration but no longer present in the manifest and give the possibility to remove them manually through the web interface instead of doing it automatically or requiring the user to remove it from the `_apps` document.

**Comment by pluma** [comment]
With the new Foxx management API it will be possible to overwrite the stored values entirely. Considering Aardvark always sends the entire configuration, it would make sense for Aardvark to do the same.

I think the best behaviour would be the following:

* in development mode, patch configuration/dependencies to avoid accidents

* in production mode, replace configs/deps to clear warnings

* warnings should indicate the redundant values can be nuked by saving in production mode

**Comment by pluma** [comment]
I've addressed this problem in the devel branch which will become the upcoming 3.2 release.

Since this changes the behaviour of the web interface, the change will not backported to 3.1 or 3.0. As far as I can tell the old behaviour pre-existed in 2.x and apart from generating noise it doesn't seem to do any direct harm.
