### ISSUE TITLE
VelocyPackHelper::patchDouble issues SIGBUS on armv7h compilation.

### ISSUE THREAD

**Issue by gorilux** [arangodb/arangodb#2163]
Hi,

## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.1
- [ ] self-compiled devel branch

On this operating system:
- [x] Linux 
 - [x] other: Archlinux - armv7h

## VelocyPackHelper::patchDouble issues SIGBUS on armv7h compilation:
leading to the arangod crash at startup on ArchLinux ARM.

Using gdb the problem can be pinpointed to the VelocyPackHelper::patchDouble method.

Thread 1 "arangod" received signal SIGBUS, Bus error.
0x00813c48 in arangodb::basics::VelocyPackHelper::patchDouble(arangodb::velocypack::Slice, double) ()
(gdb) bt
*#*0  0x00813c48 in arangodb::basics::VelocyPackHelper::patchDouble(arangodb::velocypack::Slice, double) ()
*#*1  0x003d0d8c in arangodb::aql::Query::executeV8(v8::Isolate*, arangodb::aql::QueryRegistry*) ()
*#*2  0x006b13a0 in ?? ()
*#*3  0x00cd1a00 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

This is a custom compilation with the following flags:
CFLAGS=-march=armv7-a -mfloat-abi=hard -mfpu=vfpv3-d16 -O2 -pipe -fsigned-char -fstack-protector --param=ssp-buffer-size=4 
CXXFLAGS=-march=armv7-a -mfloat-abi=hard -mfpu=vfpv3-d16 -O2 -pipe -fsigned-char -fstack-protector --param=ssp-buffer-size=4 

I think the reinterpret_cast causes an alignment problem on the arm issuing the SIGBUS signal.

Txs

**Comment by jsteemann** [comment]
Confirmed. ARM does not support unaligned writes.

**Comment by jsteemann** [comment]
Fixed in the 3.1 and devel branches. Fix will be part of the next 3.1 release (3.1.1).

**Comment by dothebart** [comment]
3.0.12 is available for download via the regular upgrade channels - closing.
