### ISSUE TITLE
 A Cluster-installation-related issue: fail to connect with each other among three servers 

### ISSUE THREAD

**Issue by saliormoon** [arangodb/arangodb#2164]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [x] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [x] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is a Cluster-installation-related issue:
 I want to build the cluster with three servers and each server installs a ArangoDB. When I execute the commands in the guide line https://docs.arangodb.com/3.0/Manual/Deployment/Distributed.html, it can not be sucessful. And the main problem is that they cannot connect with each other. So could anyone provide more detail content about how to build a cluster? And how to get the Server-ID and start the cluster? It is great appreciated.

**Comment by kvahed** [comment]
do you have startup commands/config files for us please.

**Comment by saliormoon** [comment]
Sorry, I don't know how to start the cluster and where to accquire the config files.
