### ISSUE TITLE
Accidental query deletion by unexpected behaviour in Arangodb-Frontend.

### ISSUE THREAD

**Issue by ArnoBuschmann** [arangodb/arangodb#2169]
When chosing a query query in the web frontend, modifying it, then doing a "save as", it gets saved as expected by the new given name. Also the indicator showing the active query on the top of the UI is showing the new name I just gave when using "save as". So, at this stage, one would think and expect, to work completely on the new "saved as" query.

But when pressing the save button now, the old query gets overwritten, not the new one.

Hope this hint helps to fix it. Apart from that just let me add, that Arangodb is such a great product, love it! :)

## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [x ] 3.1.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [x ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click to ...
...

The following problem occurs: [Screenshot?] 
Instead I would be expecting: 

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

**Comment by hkernbach** [comment]
Thank you for the discovery. This bug is fixed in devel and 3.1 branch. Will be included in the next bugfix release (3.1.1+)

**Comment by Simran-B** [comment]
I noticed another minor thing: if you `Save as` a new query for the first time, then switch to another section (e.g. GRAPHS), then go back to QUERIES, the `Save` button that was shown after `Saving as` will be gone. If you load the saved query (activate ⭐️ Queries and double-click it), the `Save` button will appear again, but also remain visible even if you switch back and forth to other sections.

**Comment by ArnoBuschmann** [comment]
@hkernbach great to hear about the bugfix.

@Simran-B this is so great about reporting issues and open source, how people see details and get back to help making it better. :)

Ideed it is already confusing a bit (I think), that when the new query has not been saved the first time, there are the two buttons "save" plus "save as". Guess an intuitive behaviour would be:

-> new query: only one "save as" button, on top there could be an indicator such as "query not saved yet"
-> new query got saved: keep both buttons, while indicating at the top, which query is active now.
