### ISSUE TITLE
REST API calls not consistent

### ISSUE THREAD

**Issue by sylvainlap** [arangodb/arangodb#2175]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [x] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [x] Windows, version: 10
- [ ] MacOS, version:

## the issue

Is there a reason that some REST API calls are not unified ?

For example:

https://docs.arangodb.com/3.1/HTTP/Document/WorkingWithDocuments.html
Create a document returns metadata

whereas

https://docs.arangodb.com/3.1/HTTP/Gharial/Vertices.html
Create a vertex returns error / code / vertex

Moreover, in a REST API, what's the point to return an error bool, and a code in the body, because, the code is the HTTP code, and one can assume that if code > 4xx, it's an error.

Shouldn't these REST API calls be more consistent ?

**Comment by jsteemann** [comment]
Unifying the REST APIs for documents and graph vertices/edges is very sensible.

**Re error codes**:

Returning the error code in the HTTP body is sensible in cases when the error code returned by ArangoDB is more detailed than the limited set of HTTP error codes.
For example, returning `{"errorNum":4,"errorMessage":"out of memory"}` along with an HTTP status code of 500 may be providing more inside than a plain HTTP 500 return code alone.

Returning the "error" bool value is indeed superfluous and is there for compatibility reasons only, as many client programs are looking for this attribute.

**Comment by dothebart** [comment]
As @jsteemann put it - the `error` bool is for consistency with successfull returns. I think we may close this now.
