### ISSUE TITLE
support embedded mode for testing

### ISSUE THREAD

**Issue by grexe** [arangodb/arangodb#2177]
According to [this answer on SO](http://stackoverflow.com/a/36397451/160799), ArangoDB does not currently feature an embedded mode (like Neo4j does, e.g.).

This makes it hard to use ArangoDB in unit tests, for example (in my case, from Java).

I'd like to startup a simple throwaway instance of ArangoDB, insert test data, run my queries and validate the results, in an isolated way and independent of the environment.

In the SQL world, I could substitute my full blown DB for a simple lightweight in-memory alternative like H2 instead of Oracle or MariaDB, but in the case of ArangoDB, I'm stuck.

Currently using 3.0.10 on Linux x64 in a dockerized environment.

*Note*: I know I could startup a docker container with ArangoDB and run the tests against that, but I'd prefer to avoid the overhead involved with setting up Docker (adding the system requirements and dependencies to all environments where I want to run these tests), using the docker-library or REST calls,... if possible.

**Comment by dothebart** [comment]
As arangodb isn't written in java, this is not possible without starting to do JNI magic. 
but, you guess it, we also do unit testing where we need to start/stop arangodb in order to set up our test environment.

The overal behaviour of the ArangoDB unit testing framework is documented in `README_maintainers.md`; If you clone & compile it, you can use 

`./scripts/unittest all` 
to run its tests. The files doing the control flow are:

```
js/client/modules/@arangodb/testing.js
UnitTests/unittest.js
```
The functions controling the command flow are:
```
startInstance
checkInstanceAlive
shutdownInstance
```

**Comment by dothebart** [comment]
Hovever, if you want to start a JNI wrapper `arangod/RestServer/arangod.cpp` is what you would have to mimic; you probably won't get rid of the unix domain socket however.

**Comment by grexe** [comment]
Ok thanks a lot for the info and pointers, but a JNI wrapper would be out of scope for now - maybe I'll give [BridJ](https://github.com/nativelibs4java/BridJ) a shot since JNA does not support C++ directly (see this [related SO thread](http://stackoverflow.com/questions/1556421/use-jni-instead-of-jna-to-call-native-code).
For a quick solution, I think the test-container will work best for us.

**Comment by dothebart** [comment]
Ok, so I think we can close this now.
