### ISSUE TITLE
Cannot install foxx-apps via Webinterface

### ISSUE THREAD

**Issue by tomterl** [arangodb/arangodb#2179]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [x] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [ ] Debian .deb
  - [x] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is a web interface-related issue:
I'm using the web interface with this browser:  firefox   running on this OS: Ubuntu 16.04
- [x] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [x] other: any database will ddo 
4) Click 'Services'
5) Click 'Add Service'
6) Click 'Zip' tab
7) Enter a mount-point (/any will do)
7) Click Update Foxx.zip button
8) Choose your zip file
The following problem occurs: 

````
Services: 3103. failed to invoke module File: /var/lib/arangodb3-apps/_db/rulebook-v2_0_0-2/test/APP/index.js 
    Cause: ArangoError: No such file or directory: system error at Error (native) at
          Object.global.DEFINE_MODULE.exports.readFileSync (/usr/share/arangodb3/js/common/bootstrap/modules/fs.js:466:23) at 
           Object.Module._extensions..js (/usr/share/arangodb3/js/common/bootstrap/modules.js:612:20) at 
           Module.load (/usr/share/arangodb3/js/common/bootstrap/modules.js:544:34) at 
           FoxxService.run (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/service.js:397:12) at
           exports.routeService (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/routing.js:160:40) at
           _install (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/manager.js:1093:7) at 
           Object.install (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/manager.js:1137:17) at 
           Middleware. (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/foxxes.js:97:29) at 
           next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:388:15)
````

Instead I would be expecting: 

A successful install.

The same happens when trying to replace an existing foxx-service.

using `foxx-manager` works, though.
We're having the same problem with our 3.1 install.

**Comment by pluma** [comment]
The error seems to indicate the service root does not contain an "index.js" file.

Can you maybe send me the zip bundle for the service? If you don't want the file to be public you can send me a link via direct message in the Community Slack.

**Comment by tomterl** [comment]
Wow - I obviously need to learn how to read these backtraces -- I should have known to substitute APP for my app-name ;)

Mea culpa, and many thanks for your time -- I simply somewhere in our history of tooling lost the index.js in the zip-building step.

**Comment by pluma** [comment]
Great! Good to hear it's working for you,
