### ISSUE TITLE
Response time of first query

### ISSUE THREAD

**Issue by sajeevpr** [arangodb/arangodb#2180]
Dear team,
  We are running ArangoDB 3.1rc2 in redhat 6.6 machine. and having a huge database with millions of entries on multiple collections.
So when we run some complex queries, it is taking 10 to 20 seconds, sometimes more than a minute only for the first time. Next time onwards, it is very fast and takes only few milli seconds.

Is there a way to make the first query faster by preloading the indexes and data into main memory.

Regards,
Sajeev

**Comment by jsteemann** [comment]
Yes, the loading time of collections affects query response time. 
There is already a feature request for this in #1821. I am closing this issue as a duplicate of it.
