### ISSUE TITLE
[Wishlist] Safeguard for removing RW-rights on _system for current user

### ISSUE THREAD

**Issue by tomterl** [arangodb/arangodb#2181]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [x] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [ ] Debian .deb
  - [x] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [x] authentication is enabled?
- [ ] using the cluster?
- [x] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [x] `_system` [ ] other: 
4) Click on users
5) Click on Current User in the list
6) Click on Permissions
7) Click on the RW-Rights checkbox for _system

The following problem occurs: You just lost you admin-rights on _system; You can turn off authorization in the db-config and restart the service, unfortunately for me, not ad-hoc in prodution systems.

Instead I would be expecting: A single safe-guard popup asking me, if I really want to bereave myself of admin rights to _system.

In my case, it was a not deliberate click with a tablet or accidental key-shortcut that caused this (I guess); a co-worker could rectify the situation in time, but I guess there are situations, where this could be disastrous.

**Comment by Simran-B** [comment]
Agreed, it doesn't hurt to show a confirmation dialog in the web frontend.

**Comment by hkernbach** [comment]
Thanks. Added information modal when permissions on _system database are going to be revoked. This fix will be included in the next bugfix release (3.1.8 +).
