### ISSUE TITLE
Arangodump is not dumping data after updating to 3.1 from 3.0.x

### ISSUE THREAD

**Issue by PavelPikat** [arangodb/arangodb#2186]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ x] 3.1

On this operating system:
- [ x] Windows, version: 10, 64-bit

These are the steps to reproduce:
1. Dump your data from ArangoDB 3.0.x (I had 3.0.10)
2. Install ArangoDB 3.1.0 or ArangoDB 3.1.1
3. Restore 3.0.10 data into 3.1.x database with arangorestore
4. Modify any document (optional step, arangodump should still dump the database even if it's not modified)
5. Try to dump data from 3.1.1
6. No data will be dumped (0 collections)

Note: my arangodump command: **arangodump.exe --server.database my-db --overwrite true --output-directory "%~dp0\"**

Instead I would be expecting: 
1. The data should be dumped from 3.1.1 using 3.0.10 dataset

**Comment by jsteemann** [comment]
Can you confirm there was no confusion of directory or database names during the test? I am asking because I have not noticed any problems when I tried the above steps myself.

However I tried on Linux 64 bit and not on Windows.

**Comment by mpv1989** [comment]
I tried this on Windows 10 (64 bit) with no problems. (did not modify any document, all collections were dumped)

**Comment by PavelPikat** [comment]
I'm not sure I cant tell whether there was such confusion or not - arangodump.exe itself didn't print any errors and finished with "0 collections, 0 documents were dumped" message (or something like that).

Now when you are saying you don't any problems with dumping, I suspect something went wrong with the installation of 3.1.1.  I'm going to try to test it on another machine with another database later tonight.

**Comment by jsteemann** [comment]
Thanks.

**Comment by PavelPikat** [comment]
I tried it on another machine and it gave me some unexpected results: arangodump.exe only exported 2 collections out of 9. And again, there were no errors in the terminal. 

I've attached my data set and .bat scripts that I use to dump and restore the data.
[arango_dump.zip](https://github.com/arangodb/arangodb/files/609711/arango_dump.zip)

I assume if you try restoring this data set on 3.1.1 and then dump it again, only 2 collections will be dumped: 
![arango](https://cloud.githubusercontent.com/assets/3666748/20574391/805ba7a6-b1b4-11e6-8909-6f81e026db8a.PNG)

I also noticed that the path to arango .exe programs was changed since 3.0.10. Arango folder now has a weird name, like "ArangoDB3 3.1.1." Is this intended? Moreover, .exe programs were moved from /bin folder to usr/bin

**Comment by mpv1989** [comment]
I can reprocude this with your data. We will have a look at this.

**Comment by mpv1989** [comment]
We found the bug. It will be fixed in release 3.1.2.

**Comment by PavelPikat** [comment]
Confirming it works it 3.1.2
