### ISSUE TITLE
Windows setup creates wrong path to mongo shell 

### ISSUE THREAD

**Issue by Jenar78** [arangodb/arangodb#2187]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.1
- [ ] self-compiled devel branch

On this operating system:
- [x] Windows, version: 10x64

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.
Install ArandoDB on Windows using current setup https://www.arangodb.com/repositories/arangodb31/Windows7/x86_64/ArangoDB3-3.1.1-1_win64.exe
or 
https://www.arangodb.com/repositories/arangodb31/Windows7/x86_64/ArangoDB3-client-3.1.1-1_win64.exe

After that created link on desktop to arangosh.exe has wrong path ("\\" between usr and bin is missing):
"C:\Program Files\ArangoDB3 3.1.1\usrbin\arangosh.exe"

**Comment by Simran-B** [comment]
@dothebart pushed a fix just now: ab77244b670b09b0e339ecffe38914d1c14ada89

Thanks Jenar for reporting this problem!

**Comment by dothebart** [comment]
I've replaced the 3.1.1 packages; please re-download to get the fixed versions. 
Thanks for reporting.

**Comment by Jenar78** [comment]
I have tested it, works great.
Thank you :)
