### ISSUE TITLE
Documentation error in the HTTP parameters for Read all documents

### ISSUE THREAD

**Issue by mtruyens** [arangodb/arangodb#2193]
The "Working with Documents" page must be reviewed (https://docs.arangodb.com/3.1/HTTP/Document/WorkingWithDocuments.html) 

In the section on "Read all documents", it:
- refers to a json post document for the query parameters;  
- describes the backward compatibility in a weird manner (seems it needs to be the reverse).

**Comment by maxkernbach** [comment]
Hi @mtruyens,

thanks for reporting. The "Read all documents" section in the [documentation](https://docs.arangodb.com/3.3/HTTP/Document/WorkingWithDocuments.html#read-all-documents) has been fixed with the latest release 3.3.9.
