### ISSUE TITLE
Optimize index

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [arangodb/arangodb#2197]
Schema
```
User {
  age: Number,
  banned: Boolean
}
```

I create `SkipList` index  for fields ['age', 'banned']

if i run query 
```
FOR user IN Users
  FILTER
      user.age == 20 && user.banned == false
  RETURN user
```
index is works, but  if i run query
```
FOR user IN Users
  FILTER
      user.banned == false && user.age == 20
  RETURN user
```

Index is NOT works?? For it is written in the documentation.

Why then INSIDE engine, to optimize, not to arrange the filter fields in the correct order so that they fit as much as possible under any index? Why did the programmer must do it manually?

Or am I mistaken and it is already there in the engine?
Then why in the documents it is written wrong?

**Comment by mchacki** [comment]
Could you please check if there is a typing mistake in your query first:

```
FOR user IN Users
  FILTER
      user.age == 20 && banned == false
  RETURN user
```

the part: `banned == false` is not evaluated on the object user, but on a collection called banned (which would not make any sense)

The correct query should be:

```
FOR user IN Users
  FILTER
      user.age == 20 && user.banned == false
  RETURN user
```

as well as:

```
FOR user IN Users
  FILTER
      user.banned == false && user.age == 20
  RETURN user
```

In both cases the index should be used, there should be no manual effort for the user.

Could you please also attach an explain output for both queries?
(In the web interface: Click explain, in the console use `db._explain(<query>)`)
This would help us a lot to debug.

**Comment by uMaxmaxmaximus** [comment]
Oh I'm sorry, it's my fault =) index actually works. And the documentation says that the field order is important for sorting, Instead filtration.
