### ISSUE TITLE
Composite Index performance

### ISSUE THREAD

**Issue by sajeevpr** [arangodb/arangodb#2198]
Dear Team,

  We are using Arangodb 3.1 in RHEL 6.6 and facing performance issue for composite index.

For normal single attribute hash index, response time is in few milli seconds, but for composite index, it is few seconds.

Is there any way this can be mitigated?

Regards,
Sajeev

**Comment by jsteemann** [comment]
Can you provide the index definition and the query plus the execution plans? This may help finding out more.

**Comment by sajeevpr** [comment]
@jsteemann ,
  Please find below the query.

```
Query string:
 LET fullAccounts = (
    FOR acc IN Account
     LIMIT 1000
     RETURN acc
 )
    FOR acl IN Acl
       
       FILTER  acl.RES_TYPE_KEY IN ["3","4"] AND acl.RES_NAME == "resource1"
       FOR acc2 IN fullAccounts
         FILTER acc2.accountKey == acl.ACCOUNT_KEY
         LIMIT 250
           RETURN {acl,acc2}
 

Execution plan:
 Id   NodeType                      Est.   Comment
  1   SingletonNode                    1   * ROOT
  3   EnumerateCollectionNode   18958251     - FOR acc2 IN Account   /* full collection scan */
  4   LimitNode                     1000       - LIMIT 0, 1000
 16   IndexNode                     1000       - FOR acl IN Acl   /* hash index scan */
 17   CalculationNode               1000         - LET #6 = (acl.`RES_TYPE_KEY` in [ "3", "4" ])   /* simple expression */   /* collections used: acl : Acl */
  9   FilterNode                    1000         - FILTER #6
 13   LimitNode                      250         - LIMIT 0, 250
 14   CalculationNode                250         - LET #10 = { "acl" : acl, "acc2" : acc2 }   /* simple expression */   /* collections used: acl : Acl, acc2 : Account */
 15   ReturnNode                     250         - RETURN #10

Indexes used:
 By   Type   Collection   Unique   Sparse   Selectivity   Fields                          Ranges
 16   hash   Acl          false    false       100.00 %   [ `ACCOUNT_KEY`, `RES_NAME` ]   ((acc2.`accountKey` == acl.`ACCOUNT_KEY`) && (acl.`RES_NAME` == "resource1"))

Optimization rules applied:
 Id   RuleName
  1   inline-subqueries
  2   move-calculations-up
  3   move-filters-up
  4   move-calculations-up-2
  5   move-filters-up-2
  6   use-indexes
  7   remove-filter-covered-by-index
  8   remove-unnecessary-calculations-2
  9   move-calculations-down
```

Regards,
Sajeev

**Comment by Simran-B** [comment]
Based on the re-arranged query in the query plan, one could try to define the hash index differently to avoid the FILTER on RES_TYPE_KEY: `ACCOUNT_KEY,RES_NAME,RES_TYPE_KEY[*]`.

What is uncertain is the time it takes to get 1000 documents from collection Account. This shouldn't take long, but instead of speculating, I would recommend to use a nightly build and run the query with the new profiling option. In arangosh: `db._profileQuery('...')`. This should give a better insight into what node takes the most time in execution.

**Comment by vinaypyati** [comment]
Hi @sajeevpr,

Did you have a chance to try out the suggestion by Simran-B? You can find the new profiling option in the [latest ](https://www.arangodb.com/download-major/) release. Please let us know the insights of what takes the most time in execution. 

You can also try the new ArangoDB [v3.4 RC1 ](https://www.arangodb.com/download-technical-preview/) which includes performance improvements and check if the issue still persists there too. 

Thanks!

**Comment by OmarAyo** [comment]
Hi @sajeevpr 

We haven't heard from you recently, I am going to close this ticket now

If needed, please comment and we will reopen it again

Thanks
