### ISSUE TITLE
Cluster: if one of both masters will fail the created collection is unsafe

### ISSUE THREAD

**Issue by servusoft** [arangodb/arangodb#2200]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [X] self-compiled devel branch

On this operating system:
- [X] Linux 
  - [X] Debian .deb
  - [X] Ubuntu .deb

Steps to reproduce:

1. create a cluster 1-2-1 (with `startLocalCluster.sh`)
2. create a collection 'col1' with a document 'doc1' (replication factor=2, 4. wait for sync:Yes).
3. check NODES->Shards:
col1:  Leader->DBServer001, Followers->DBServer002

4. determine pid of the master 1 `ps -eafL`
5. shut down master 1 `kill -s TERM <pid>`
6. await 1 min, master 2 takes over the leadership
7. check collection 'col1.doc1' -> works
8. check NODES->Shards:
col1:  Leader->DBServer002, Followers->DBServer001

9. create a collection 'col2' with a document 'doc2' (replication factor=2, wait for sync:Yes). 
-> on master 2 (state: master 1 is down)
10. check NODES->Shards:
col1:  Leader->DBServer002, Followers->DBServer001
col2:  Leader->DBServer002, Followers->no followers
11. start master 1 
12. await 1 min
check 'col1.doc1' again -> works,
check 'col2.doc2' again -> works
check NODES->Shards:
col1:  Leader->DBServer002, Followers->DBServer001
col2:  Leader->DBServer002, Followers->no followers

13. determine pid of the master 2
14. shut down master 2 
15. await 1 min
16. checks:
check 'col1.doc1' again -> works quicly
check 'col2.doc2' again -> fails after est. 80 sec (it is shown ping-pong)
and a error message: "Documents: Could not fetch documents count"
check NODES->Shards:
col1: Leader->DBServer001, Followers->DBServer002
col2: Leader->DBServer002, Followers->no followers

if a collection is created while one of the two master is down, the is no more fail-proof because the has no followers. this does remain unsafe if the second master is back on. (although replication factor = 2 configured)

**Comment by Simran-B** [comment]
Was this a bug that has since been fixed?
