### ISSUE TITLE
FULLTEXT with sub-properties is not working

### ISSUE THREAD

**Issue by melisabok** [arangodb/arangodb#2204]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [x ] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [x ] MacOS, version: 10.11.6

### this is an AQL-related issue:
[ x] I'm using graph features

I'm issuing AQL via:
- [x ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ x] this Driver: arangojs

I'm migrating from arangodb 2.8 to 3.1 and the FULLTEXT search with sub-properties doesn't work: "no suitable fulltext index found for fulltext query". 

This is my document:
```
{
   "_key": "434844465410935",
   "_id": "test/434844465410935",
   "_rev": "_UJwRl4u---",
   "content": {
     "title": "This is a title"
   },
   "header": "This is a header"
 }
```

This is the index definition:

```
db.test.ensureIndex({ type: "fulltext", fields: [ "content.title"], minLength: 2 });
```

and this query is not working:

```
FOR n IN FULLTEXT(test, 'content.title', 'prefix:this')
return n
```

got an error: "no suitable fulltext index found for fulltext query".

I also tried to create the index through the web ui and got the same error.

**Comment by baslr** [comment]
fulltext index on `content.title`

with

```
return  FULLTEXT(test, "content.bumba", 'abc') + v8(rand())

I get
Query: in function 'FULLTEXT()':
no suitable fulltext index found for fulltext query on 'test'
stacktrace of offending AQL function:
ArangoError: in function 'FULLTEXT()': no suitable fulltext index found for fulltext query on 'test' at
THROW (/Users/manuel/arangodb/js/server/modules/@arangodb/aql.js:411:13) at
Object.AQL_FULLTEXT
(/Users/manuel/arangodb/js/server/modules/@arangodb/aql.js:4274:5) at
Function. (--script--:1:183) (while executing)

thats at
```
https://github.com/arangodb/arangodb/blob/v3.1.1/js/server/modules/%40arangodb/aql.js#L4274
```
with 

return  FULLTEXT(test, "content.title", 'abc') + v8(rand())

I get
Query: no suitable fulltext index found for fulltext query on 'test' (while executing)
stacktrace of offending AQL function:
ArangoError: no suitable fulltext index found for fulltext query on 'test' (while executing) at
Error (native) at Object.AQL_FULLTEXT
(/Users/manuel/arangodb/js/server/modules/@arangodb/aql.js:4284:45) at Function.
(--script--:1:183) (while executing)
```
thats at
https://github.com/arangodb/arangodb/blob/v3.1.1/js/server/modules/%40arangodb/aql.js#L4284

**Comment by Simran-B** [comment]
I can confirm the problem, but by looking at the (JavaScript) code nothing leaps to the eye.

@jsteemann?

**Comment by jsteemann** [comment]
3.1.4 has been released. Closing as fixed.
