### ISSUE TITLE
WebUI & API hang during DB startup in certain situations until all collection data is loaded up

### ISSUE THREAD

**Issue by drcomaneci** [arangodb/arangodb#2205]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [X] 3.0 (3.0.10) 
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [X] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[X] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [X] this Driver: pyArango

The issue can be reproduced using this dataset:
10 - 12 large collections (both documents & edges) totalling ~ 65Gb of data which have indexes and which also take a long time (~60 minutes) to load up during DB start.

These are the steps to reproduce:
1) Start database with no collections loaded, don't access the WebUI just yet
2) Start ~ 100 - 150 worker processes that do queries against the DB and force the loading of collections from disk
3) Try to access the Web Interface or do an operation against a collection that's already loaded

The following problem occurs: 
Both the WebUI as well as any other API requests that can be fulfilled hang until all of the collections have been loaded. 

Instead I would be expecting: 
To have at least a functional WebUI through which to see what's happening and be able to execute those queries that already have their data loaded up. 

One interesting thing to note here is that the problem doesn't reproduce if I access the WebUI first, start loading some of the collections and then start the worker processes that do queries against the DB. In this case, the expected behavior happens: the queries that already have the data available work out ok while the WebUI continues to work. 

The problem might be related to the way collections are loaded from the WebUI vs. pyArango.

**Comment by maxkernbach** [comment]
Just reproduced it with the current version 3.2.9 on Ubuntu:
I started the database without loaded collections, ran queries on large collections with pyArango and then accessed the WebUI. While the queries were running and loading of large collections did not finish yet i could navigate through the web interface and work with loaded collections.

**Comment by maxkernbach** [comment]
Closing this issue for now as the problem occurred with an old version of ArangoDB and i was not able reproduce it with version 3.2.9.

Please reopen this issue if you note a similar problem using a current version.

Thanks
