### ISSUE TITLE
ERROR {communication} unable to perform ssl handshake: wrong version number : 336130315

### ISSUE THREAD

**Issue by erkimarks** [arangodb/arangodb#2207]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
dpkg --list  | grep -i arango
ii  arangodb3                      3.1.3                           amd64        the multi-model NoSQL database

On this operating system:

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial

dpkg --list  | grep -i openssl
ii  openssl                        1.0.2g-1ubuntu4.5               amd64        Secure Sockets Layer toolkit - cryptographic utility

arangod --ssl.protocol 5 --ssl.cafile /etc/arangodb3/fullchain.pem --ssl.keyfile /etc/arangodb3/arangodb.pem --log.use-local-time true --http.hide-product-header true --tcp.reuse-address true --server.uid arangodb --server.gid arangodb --server.endpoint ssl://0.0.0.0:5001 --server.authentication false --agency.activate true --agency.size 3 --database.directory /var/lib/arangodb/agency1-db --javascript.app-path /var/lib/arangodb/agency1-apps &

arangod --ssl.protocol 5 --ssl.cafile /etc/arangodb3/fullchain.pem --ssl.keyfile /etc/arangodb3/arangodb.pem --log.use-local-time true --http.hide-product-header true --tcp.reuse-address true --server.uid arangodb --server.gid arangodb --server.endpoint ssl://0.0.0.0:5002 --server.authentication false --agency.activate true --agency.size 3  --database.directory /var/lib/arangodb/agency2-db --javascript.app-path /var/lib/arangodb/agency2-apps &

arangod --ssl.protocol 5 --ssl.cafile /etc/arangodb3/fullchain.pem --ssl.keyfile /etc/arangodb3/arangodb.pem --log.use-local-time true --http.hide-product-header true --tcp.reuse-address true --server.uid arangodb --server.gid arangodb --server.endpoint ssl://0.0.0.0:5003 --server.authentication false --agency.activate true --agency.size 3 --agency.endpoint ssl://localhost:5001 --agency.endpoint ssl://localhost:5002 --agency.endpoint ssl://localhost:5003 --agency.supervision true --database.directory /var/lib/arangodb/agency3-db --javascript.app-path /var/lib/arangodb/agency3-apps &

2016-12-05T19:09:10 [26842] ERROR {communication} unable to perform ssl handshake: wrong version number : 336130315
2016-12-05T19:10:14 [26842] ERROR {communication} unable to perform ssl handshake: wrong version number : 336130315
2016-12-05T19:10:14 [26842] ERROR {communication} unable to perform ssl handshake: wrong version number : 336130315

**Comment by kvahed** [comment]
this should not have any effect on the operation. should only come up during the startup phase. but thanks for bringing it up. but arangod should not be complaining about it. we'll look into that.

**Comment by jsteemann** [comment]
@kvahed : I think there exists a problem with TLSv1.2 support in ArangoDB.

**Comment by jsteemann** [comment]
At least I remember having looked into this before in context of other issues. When ArangoDB (or one of its components) tries to establish a TLSv1.2 connection, it will fail somewhere in the SSL handshake phase.

**Comment by kvahed** [comment]
confirm for --ssl.protocol 5

**Comment by erkimarks** [comment]
Unfortunately this had an effect on the DB operation. The cluster could not form and so the DB did not start correctly.

**Comment by mattwoolnough** [comment]
This is also an issue for me. Is there a workaround available?

**Comment by dothebart** [comment]
Hi, 
this is confirmed to be fixed with arangodb 3.1.19 which is now available for download.
Closing.
