### ISSUE TITLE
Cannot login after installation like service AranangoDB Windows7

### ISSUE THREAD

**Issue by srbiotik** [arangodb/arangodb#2208]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 3.0

On this operating system:
- [ ] Windows, Windows 7 Ultimate: 

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

1) install ArangoDB3-3.1.3-1_win64.exe (34 MByte)
2) select installation as service
3) input password in the installation
4) open the browser on http://127.0.0.1:8529
5) log in as 'root' with password given in installation
6) get 'Login Failed' , above Username

## Issue resolved like so:

http://stackoverflow.com/questions/40972787/cannot-login-after-installation-like-service-aranangodb-windows7
With the help of an arangoDB developer...

**Comment by Simran-B** [comment]
Are you able to login using "root" and a blank password?

**Comment by srbiotik** [comment]
No I'v tried that.

**Comment by dothebart** [comment]
I've worked a bit to smoothen the windows installer; 
Its available for download:
https://www.arangodb.com/repositories/nightly/Windows7/x86_64/ArangoDB3-3.2.devel-1_win64.exe

Does this still happen to you? If yes, do you see any entries from arangodb in your Windows Event log?
