### ISSUE TITLE
Bug in AQL query when bind parameters are been used in `FILTER` statement

### ISSUE THREAD

**Issue by denya133** [arangodb/arangodb#2210]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [*] 3.0
- [*] 3.1
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [*] Linux 
  - [ ] Debian .deb
  - [*] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [*] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

Bind parameters (must be more then two key-value pairs):
`{doc: {cucumberId: "f03acbfc-a960-43ee-8064-a5f740473cd9", _key: "12345" }}`
Or
`{cucumberId: "f03acbfc-a960-43ee-8064-a5f740473cd9", _key: "12345" }`

The AQL query in question is:
`
LET doc = @doc
RETURN (FOR item IN tests FILTER (doc.cucumberId == item._key) LIMIT 1 RETURN item)[0]
`
And
`
RETURN (FOR item IN tests FILTER (@doc.cucumberId == item._key) LIMIT 1 RETURN item)[0]
`
Problem also can be reproduced using:
`
LET doc = {_key: @_key, cucumberId: @cucumberId} /* more then two key-value pairs with bind parameters */
RETURN (FOR item IN tests FILTER (doc.cucumberId == item._key) LIMIT 1 RETURN item)[0]
`

The issue can be reproduced using this dataset:
`db.tests.save({_key: "f03acbfc-a960-43ee-8064-a5f740473cd9", name: "Test record"})`

But this problem not occur when key-value pairs are been defined without bind parameters:
`
LET doc = {_key: "12345", cucumberId: "f03acbfc-a960-43ee-8064-a5f740473cd9"} 
RETURN (FOR item IN tests FILTER (doc.cucumberId == item._key) LIMIT 1 RETURN item)[0]
`

**Comment by jsteemann** [comment]
I ran the following code in arangosh in 3.0:
```js
db._drop("tests");
db._create("tests");
db.tests.save({_key: "f03acbfc-a960-43ee-8064-a5f740473cd9", name: "Test record"})
var bind = { 
  "doc" : { 
    "cucumberId" : "f03acbfc-a960-43ee-8064-a5f740473cd9" 
  } 
};
q1 = `RETURN (FOR item IN tests FILTER (@doc.cucumberId == item._key) LIMIT 1 RETURN item)[0]`; 
q2 = `LET doc = @doc RETURN (FOR item IN tests FILTER (doc.cucumberId == item._key) LIMIT 1 RETURN item)[0]`; 

print(db._query(q1, bind).toArray());
print(db._query(q2, bind).toArray());
```
And it produces the same result (one document) in both cases:
```
[ 
  { 
    "_key" : "f03acbfc-a960-43ee-8064-a5f740473cd9", 
    "_id" : "tests/f03acbfc-a960-43ee-8064-a5f740473cd9", 
    "_rev" : "14109204", 
    "name" : "Test record" 
  } 
]
```
I think this is the expected result.
However, when adding this query
```js
q3 = `LET doc = {_key: "12345", cucumberId: "f03acbfc-a960-43ee-8064-a5f740473cd9"} RETURN (FOR item IN tests FILTER (doc.cucumberId == item._key) LIMIT 1 RETURN item)[0]`; 
print(db._query(q3).toArray());
```
the result is empty. This is obviously incorrect and has been fixed in 3.1.4 and 3.0.13.

**Comment by denya133** [comment]
Very good news :)

7 дек. 2016 г. 15:24 пользователь "Jan" <notifications@github.com> написал:

**Comment by jsteemann** [comment]
3.1.4 has been released. Closing as fixed.
