### ISSUE TITLE
HTTP Cursor API returns empty result

### ISSUE THREAD

**Issue by bangert** [arangodb/arangodb#2213]
After upgrading to arangodb3-3.1.3 on Fedora 25, my python-arango driver stopped working.

I narrowed it down to the following test case:
```
#!/bin/bash
result=$(curl -X POST 'http://localhost:8529/_db/_system/_api/export?collection=<collection>' --header "Content-Type: application/json"  -u root:<pw>)
#echo $result
#exit
cursor_id=$(echo ${result} | json_xs -t json-pretty | grep '"id"' | awk -F'\"' '{print $4}')
has_more=$(echo ${result} | json_xs -t json-pretty | grep '"hasMore"' | awk '{print $3}' )
echo "Cursor ID: ${cursor_id}" 
echo "Has More: ${has_more}"
curl -X PUT "http://localhost:8529/_db/_system/_api/cursor/${cursor_id}" -u root:<pw>
```
Where `pw` is the root password and `collection` a collection with a few thousand entries.

The last curl fails with the following error:
```
curl: (52) Empty reply from server
```

**Comment by jsteemann** [comment]
Seems like a duplicate of #2211.
Can you try calling PUT /_api/export/${cursor_id} for the second call?

**Comment by bangert** [comment]
Yes - that's it! Thank you
