### ISSUE TITLE
CSV import with number only _key value doesn't work

### ISSUE THREAD

**Issue by dothebart** [arangodb/arangodb#2214]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] self-compiled devel branch

The following problem occurs: arangoimp based csv import doesn't import lines where `_key` is a number
Instead I would be expecting: should work.

Using this test: 

    _key,xx,blarg
    499999,1,blub

    arangoimp --collection testcsv --create-collection true --server.password test --separator , --type csv  /tmp/test.csv

one gets: 
2016-12-09T14:31:55Z [13679] WARNING at position 0: creating document failed with error 'illegal document key', offending document: {"_key":499999,"blarg":"blub"}

the current hotfix is to quote that column:

    cat /tmp/test.csv |sed -e "s;^\([0-9]*\),\(.*\);'\1',\2;"

**Comment by graetzer** [comment]
I fixed this in my fork by using `--convert false` and changing a [line in ImportHelper.cpp](https://github.com/graetzer/arangodb/blob/devel/arangosh/Import/ImportHelper.cpp#L491)

**Comment by baslr** [comment]
This is now fixed in devel.

**Comment by dothebart** [comment]
ArangoDB 3.1.13 is available for download.
