### ISSUE TITLE
vpack error caused by UPSERT ....

### ISSUE THREAD

**Issue by smurfio** [arangodb/arangodb#2217]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
-[x] 3.1.4

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [x] docker on mac osx
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [x] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser:     running on this OS:
- [ ] arangosh
- [x] this Driver: nodejs driver

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

**FOR edge IN [
	{"_from":"coll1/1", "_to":"coll2/1", "prop1":"value1", "prop2":2337789},
	{"_from":"coll1/3", "_to":"coll2/1", "prop1":"value1", "prop2":2337789}
]
UPSERT {"_from":edge._from, "_to":edge._to, "prop1":edge.prop1}
INSERT {"_from":edge._from, "_to":edge._to, "prop1":edge.prop1, "prop2":edge.prop2}
UPDATE {"prop2":edge.prop2}
IN EDGE_COLLECTION**

CUSTOM INDEXES ARE
(_from,_to,prop1) => (unique)
(_to,prop2) => (unique,spare)

The following problem occurs: 

The query itsself throws a unique constraint error. However afterwards you're no more able to send queries like the following:
**FOR doc IN  EDGE_COLLECTION
FILTER doc._to=="coll2/1"**

When querying you get the following error:
**ERROR ArangoError: got invalid vpack value on lookup (exception location: /var/lib/jenkins/workspace/RELEASE__BuildPackages/arangod/StorageEngine/MMFilesCollection.cpp:1134). Please report this error to arangodb.com (while executing)**

**Comment by jsteemann** [comment]
I tried reproducing the issue with the following code, but with no luck:
```js
db._drop("EDGE_COLLECTION");
db._createEdgeCollection("EDGE_COLLECTION");
db.EDGE_COLLECTION.ensureIndex({ type: "skiplist", fields: ["_from", "_to", "prop1" ], unique: true });
db.EDGE_COLLECTION.ensureIndex({ type: "skiplist", fields: ["_to", "prop2" ], unique: true, sparse: true });

var query1 = `FOR edge IN [ {"_from":"coll1/1", "_to":"coll2/1", "prop1":"value1", "prop2":2337789}, {"_from":"coll1/3", "_to":"coll2/1", "prop1":"value1", "prop2":2337789} ] UPSERT {"_from":edge._from, "_to":edge._to, "prop1":edge.prop1} INSERT {"_from":edge._from, "_to":edge._to, "prop1":edge.prop1, "prop2":edge.prop2} UPDATE {"prop2":edge.prop2} IN EDGE_COLLECTION`;
db._query(query1);

var query2 = `FOR doc IN EDGE_COLLECTION FILTER doc._to=="coll2/1" RETURN doc`;
db._query(query2);
```
Is the problem reproducible on your end? Does it occur with the above code?

**Comment by smurfio** [comment]
I’ve tried your code and the error doesn’t appear. However I’ve used indexes of type „hash“.

Here is the original query that causes the problem and this is reproducible on a new collection:

data insert:

collection TEAM_IDENTIFY has following indexes
hash, unique => _from, _to, link		(however the „unique“ seems not to be relevant)
hash, unique, spars => _to, providerID


FOR doc IN [{"_from":"team/433838", "_to":"provider/1", "link":"defensoresdebelgrano", "name":"Defensores de Belgrano"},
	{"_from":"team/622967", "_to":"provider/1", "link":"deportivomoron", "name":"Deportivo Moron"},
	{"_from":"team/639486", "_to":"provider/1", "link":"defensoresdebelgrano", "name":"Defensores de Belgrano"}]
INSERT doc IN TEAM_IDENTIFY


query to update:

FOR edge IN [
	{"_from":"team/433838", "_to":"provider/1", "link":"defensoresdebelgrano", "name":"Defensores de Belgrano", "providerID":2337789},
	{"_from":"team/622967", "_to":"provider/1", "link":"deportivomoron", "name":"Deportivo Moron", "providerID":2337799},
	{"_from":"team/639486", "_to":"provider/1", "link":"defensoresdebelgrano", "name":"Defensores de Belgrano", "providerID":2337789}
]
UPSERT {"_from":edge._from, "_to":edge._to, "link":edge.link} INSERT {"_from":edge._from, "_to":edge._to, "link":edge.link, "name":edge.name, "providerID":edge.providerID} UPDATE {"providerID":edge.providerID} IN TEAM_IDENTIFY


query that causes the error:

FOR ti IN TEAM_IDENTIFY
	FILTER ti._to=="provider/1"
RETURN ti._from



This should reproduce the vpack error.

**Comment by jsteemann** [comment]
Thanks. I am able to reproduce the problem with the data you provided. Will look into it.

**Comment by jsteemann** [comment]
3.1.5 has been released. Closing as fixed.
