### ISSUE TITLE
Why arangodb's coordinator retries once more when leader of shard fail, and how much time used in fail over?

### ISSUE THREAD

**Issue by brucejee** [arangodb/arangodb#2219]
![image](https://cloud.githubusercontent.com/assets/5820173/21129095/980c6562-c13a-11e6-8a00-6164be63bc13.png)
1. step 3 and 4 are the same? why once more?
2. step 5 detects parallelly?
3. how much is the maximum time used from leader fail to a new leader selected?
thanks for help me

**Comment by m0ppers** [comment]
The example is indeed a bit confusing and I will adjust the documentation. What is happening is this:

The coordinator will try to contact the leader continously until it succeeds or timeouts. In a separate thread the coordinator will continously fetch the current cluster state from the agency (including which server is the leader of which shard). The supervision is running on the agency (so in parallel). When a dbserver doesn't report in for a while it will be declared dead and the supervision will coordinate a leader change for the shards the dead server was leading. This all happens while the coordinator is doing its loop.

So either the leader reappears (just a small network hickup) and the coordinator can access it again or the supervision looses patience and promotes a follower (DBServer002 in that example) to be the new leader. When the coordinator tries to fetch the document in its next try it will have an updated shard: leader list and will contact DBServer002, fetch the document and answers to the client.

Thanks for reporting. I will update the example.

**Comment by m0ppers** [comment]
I have adjusted the documentation slightly: https://github.com/arangodb/arangodb/commit/bd61fd549e6184f9d8c9c94b5dfda26aa92f1411

let me know if this is better

**Comment by brucejee** [comment]
It's more understandable now. It need maximum 15 seconds when the fetch operation reaches a coordinator when the DB server goes outage?

**Comment by m0ppers** [comment]
Yes. There are however plans to reduce this time (15s is really long if you think of a standard web application).

**Comment by brucejee** [comment]
Thanks
