### ISSUE TITLE
Stale databases available upon web login

### ISSUE THREAD

**Issue by mtruyens** [arangodb/arangodb#2222]
I am heavily creating & dropping databases in my unit tests; each time I give the temporary database another name in order to allow parallel unit tests. 

When I login on the web interface after running a few of these unit tests, I frequently see old stale (ghost) databases in the list of available databases. These databases can be selected, but upon effective login, you immediately get a warning 1228 "database not found".

(using version 3.1.2 on Mac OSX)

**Comment by dothebart** [comment]
We did change some things in the cleanup procedure which will close open file handles with ArangoDB 3.1.8. 
Can you upgrade and tell whether this still happenes?

**Comment by mtruyens** [comment]
Seems resolved indeed, based on my limited testing. Thanks!

**Comment by dothebart** [comment]
ok. so we can close this now. good :+1:
