### ISSUE TITLE
How can i display relation count ?

### ISSUE THREAD

**Issue by shaoyongyang** [arangodb/arangodb#2224]
![qq 20161215185109](https://cloud.githubusercontent.com/assets/3353541/21221333/ee77c98c-c2f7-11e6-9348-fe1e73ad6f49.png)

help me! when i configuration multipart ralation , display one only .

**Comment by hkernbach** [comment]
You can set Arrow-Type under "Edges" to Curved. Then n-relations will be shown in the graph viewer.
