### ISSUE TITLE
Unable to retrieve document after encoding arangodb key

### ISSUE THREAD

**Issue by anna2102** [arangodb/arangodb#2232]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 3.0

On this operating system:
- [ ] Windows, version: 10

### this is an AQL-related issue:
[ ] I'm using collection features

**Issue:**
I need to store ArangoDb key that contains forward slash "/". Before saving document into database, i have performed UrlEncoded, which will then converting "/" into "%2f". 

Everything goes fine, however ```db.Document<T>(encodedkey)``` returns null document even though it has been created in database.

Any possible solutions to insert key contained "/"?

Thanks.

**Comment by Simran-B** [comment]
At least with 3.1 using the web interface and arangosh, I can not reproduce the problem. `%2f` works just fine in the document key. `/` is not allowed however and will error out.

Are you referring to a certain driver? `db.Document<T>(encodedkey)` looks like it could be a C# driver...

**Comment by anna2102** [comment]
Yes, i am using arangoclient.net (C#) driver.
I shall post an issue in their github then.
Thank you for your quick replying.
