### ISSUE TITLE
Feature Request: Fulltext Index for Array Values

### ISSUE THREAD

**Issue by smyth64** [arangodb/arangodb#2235]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [x] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

Hey guys!
I saw that we can use this kind of field to index a value inside an array:
```
aliases.de[*].value
```

I tried it for the fulltext index but it didn't work. Is there any reason for this or do you plan to implement this feature in future?

Example JSON I want to create the index for:
```
{  
   "aliases":{  
      "de":[  
         {  
            "language":"de",
            "value":"Weltall"
         },
         {  
            "language":"de",
            "value":"Das All"
         },
         {  
            "language":"de",
            "value":"Der unglaublich faszinierende Kosmos"
         },
         {  
            "language":"de",
            "value":"Der tiefe weite Weltraum"
         }
      ]
   }
}
```

Thank you very much! :)

**Comment by melisabok** [comment]
Do you have any update on this feature? this used to work in arango 2.8

**Comment by dothebart** [comment]
Hi! 
@gnusi and @vasiliy-arangodb are currently working on integrating the IResearch engine into arangodb. 
Their work can be found in the `feature-iresearch` branch. 
https://github.com/arangodb/arangodb/tree/feature-iresearch

We currently estimate its going to be ready for ArangoDB 3.4 (Q1 2018) 

If you want to give it a try, you can checkout this branch by doing
```
git clone https://github.com/arangodb/arangodb.git
cd arangodb
git checkout feature-iresearch
```
 compile debian packages  like this:
`./scripts/build-deb.sh` 
or RPMs:
`./scripts/build-rpm`

The documentation is being created in
Documentation/Books/AQL/Views/IResearch.md
and
Documentation/Books/Manual/Views/IResearch.md

Feedback welcome ;)

**Comment by hotpointdevgroup** [comment]
Hello, how to create fulltext index for his array of object? 
fulltext "aliases.de.value" 
And how to user fulltext search?
FOR data IN FULLTEXT(aliases, ["de", "value"], "searchWord")
RETURN data
Is that correct?

**Comment by Simran-B** [comment]
FULLTEXT indexes support a single field only. The attribute value can be a string, array or object.
- string: the string gets indexed
- array: all strings get indexed, elements of other type are ignored
- object: its attribute values get indexed as long as they are of type string
This applies to the first level only. Deeper nested objects are ignored, including arrays of objects.

If you want to index nested arrays and objects or multiple fields with a single index then use ArangoSearch:
https://www.arangodb.com/docs/stable/arangosearch.html
