### ISSUE TITLE
No issue tracker for linenoise-ng

### ISSUE THREAD

**Issue by pureconfig** [arangodb/arangodb#2236]
Quite a few people use https://github.com/arangodb/linenoise-ng independently of arangodb. 

However, the linenoise-ng repo doesn't have an issue tracker. Does linenoise issues go *here* as well, or should someone add issues to the linenoise repo? 

Thanks.

**Comment by weinberger** [comment]
That was a mistake, sorry. I added the issue tracker functionality to the linenoise-ng repository. Please, feel open to add the issue there.

**Comment by dothebart** [comment]
please note that meanwhile there also is https://github.com/AmokHuginnsson/replxx
