### ISSUE TITLE
ElasticSearch or other ways for Permutations

### ISSUE THREAD

**Issue by smyth64** [arangodb/arangodb#2237]
Hey ArangoDB team!
First of all, merry christmas and thank you for ArangoDB, which makes it finally possible to work with big data in a convenient manner 👍 

What I'm looking for are permutations when searching.

Let's say I have the value "vue.js"
Now I want to make it possible to find it, when I enter "vuejs"

Another example:

I have the value "ArangoDB"
I want to find it when I (falsy) enter ArangoDP)

![image](https://cloud.githubusercontent.com/assets/3246782/21473444/fc9e1e0a-cb0b-11e6-8828-5cda0ca357a0.png)

For me this is *THE* killer feature of Google. Almost no other website search has this ability.

My question is: Is it possible or planned to make this possible with ArangoDB natively?
If not, is there any other possiblity? I see e.g. there is ElasticSearch for which you provided a plugin before, but it seems outdated. Maybe there are other technologies/possibilities available? Would be really interesting to know...

Thank you ! 🎅

**Comment by smith64fx** [comment]
Okay I think this is the way to go:

https://www.elastic.co/products/logstash

And maybe this

https://github.com/purbon/logstash-output-arangodb

**Comment by jsteemann** [comment]
@smith64fx : ArangoDB does not support fuzzy searching natively.
To make this work, you will need to either mirror the data in some other database that supports fuzzy searching or write your own indexing in ArangoDB using a custom Foxx application.

**Comment by dothebart** [comment]
ArangoDB 3.7 will support Fuzzy search via ArangoSearch views - for details see: https://www.arangodb.com/2020/07/deep-and-fuzzy-dive-into-search/
