### ISSUE TITLE
arangodb windows service 

### ISSUE THREAD

**Issue by AmmarMohamed** [arangodb/arangodb#2239]
i use ArangoDB 2.8 and installed in windows server 2008 its worked well but suddenly the arangodb windows service is Stopped . i don't now what is the problem but its a big problem because the all the client side is crashed  
please help me Necessary

**Comment by RudySchockaert** [comment]
Hi Mohamed, did you try to start arangod.exe from a command prompt to see what is in the output? Often this will give you a hint of what is wrong.

**Comment by jsteemann** [comment]
@AmmarMohamed : is there anything obvious in the ArangoDB server's logfiles?

**Comment by dothebart** [comment]
Hi @AmmarMohamed,
If the log doesn't contain any information, and restarting reproduces the issue could you send us a coredump? 
Heres how to create it on windows:
https://github.com/arangodb/arangodb/blob/devel/README_maintainers.md#windows-debugging

Any particular reasons why you didn't follow to later ArangoDB reasons?

**Comment by dothebart** [comment]
@AmmarMohamed any news on this issue? or can we close this?
