### ISSUE TITLE
WebGUI random vertex loading doesn't work with new / empty graphs

### ISSUE THREAD

**Issue by vlabmichl** [arangodb/arangodb#2243]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [x] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [x] Windows, version: 10
- [ ] MacOS, version:

### this is a web interface-related issue:
I'm using the web interface with this browser:     Firefox & Chrome
running on this OS: Windows 10
- [x] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) Add new collections for vertices and edges
2) Add a new graph
3) Add new vertices via WebGUI - and don't connect them.
4) Reload WebGUI
5) It's not possible to load both isolated vertices to further model the graph via the GUI.

The following problem occurs:
Not all vertices of a collection are loaded. Even if there are only a few (e.g. "2").

Instead I would be expecting: 
A possibility to switch "complete graph loading on" when working in a graph modeling context.

**Comment by hkernbach** [comment]
@vlabmichl Thank you, you are totally right. I've added a new functionality to fetch the complete graph (even if nodes are not connected to each other). This function will use the result limitation value, otherwise it would be too easy to crash the browser because of a too large result set. The function will be available within the next release (3.2+).

**Comment by vlabmichl** [comment]
Thanks!
