### ISSUE TITLE
Cluster support for distributed transactions

### ISSUE THREAD

**Issue by StarpTech** [arangodb/arangodb#2244]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [X] 3.1
- [ ] self-compiled devel branch

Hi,
I just checkout ArangoDb and did some tests with basic scenarios. After some reading the docs I found this:

> In a cluster, AQL data-modification queries are currently not executed transactionally. Additionally, update, replace, upsert and remove AQL queries currently require the _key attribute to be specified for all documents that should be modified or removed, even if a shared key attribute other than _key was chosen for the collection. This restriction may be overcome in a future release of ArangoDB.
[Reference](https://docs.arangodb.com/3.1/AQL/DataQueries.html#transactional-execution)

This means as soon as I want to switch to clustering I can't expect transactional execution of my AQL queries? AQL is described as the "One SQL-like Query Language for all Data Models" this restriction prevent me to see Arangodb as the right tool when scalability counts. When are you planning to cover his feature? Thank you!

**Comment by weinberger** [comment]
Sorry, but I don't get your point. What is the connection between SQL and full ACID transactions in a clustered environment?

**Comment by StarpTech** [comment]
Perhaps I understand your statement wrong about the restriction. Can you explain what's the impact of this limitation as an arangodb user when I use clustering?

**Comment by weinberger** [comment]
ArangoDB supports full ACID multi collections transaction for a single instance and full ACID single documents transactions for a cluster for the moment. But it would be helpful if you could explain the connection you made between SQL, cluster and transactions.

**Comment by StarpTech** [comment]
Please imagine following situation:

I have a big dataset which is sharded over 3 arangodb instances worldwide.

(1) DE, (2) USA, (3) TR

Every country has two collections:
1. users
2. partners

**Query:**

```sql
FOR u IN users
    FILTER u.name== "peter"
    UPDATE u WITH { sponsor: "klaus" } IN partners
    LET result= MYFUNCTION()
RETURN NEW
```

**Process**
```
DE -(update 'partner' document)-> USA 
                                   ^--(read 'partner' document)- TR
```

According to the documentation there is no ACID support for AQL data-modification queries across multiple instances right?

```
//The update operation will fail because MYFUNCTION

DE -(update 'partner' document)-> USA 
                                   ^--(read 'partner' document)- TR
```

Is it correct that no rollback happens and TR see wrong data?

**Comment by StarpTech** [comment]
Related https://github.com/arangodb/arangodb/issues/2019

**Comment by StarpTech** [comment]
I see that's already in the roadmap, cool!

> Distributed Transaction
Transactions in a distributed environment with a transaction manager.

**Comment by weinberger** [comment]
Yes, that's why I wrote at the moment.

Sorry, but I don't get your connection between SQL cluster, and transactions. I would appreciate if you could explain it a little bit more in detail.

**Comment by StarpTech** [comment]
There is no connection my title is wrong. This answered my questions. Thanks! https://docs.arangodb.com/3.0/Manual/Transactions/Limitations.html

**Comment by weinberger** [comment]
You are welcome!
