### ISSUE TITLE
arangosh script in startup

### ISSUE THREAD

**Issue by ericman93** [arangodb/arangodb#2246]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [x] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [x] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

Could not found anywhere,
Is there any option to specify what js files will run at startup?
Since arangoimp is not supporting edge collection creation I want to create it in arangosh script.

Thank you!

**Comment by jsteemann** [comment]
arangoimp supports the creation of edge collections:
From `arangoimp --help`:
```
  --create-collection <boolean>          create collection if it does not yet exist (default: false)
  --create-collection-type <string>      type of collection if collection is created (edge or document) (default: "document")
```
So you could do
```
arangoimp --file data.json --type json --collection myEdges --create-collection true --create-collection-type edge
```
to create an edge collection named "myEdges".

**Comment by ericman93** [comment]
Wow nice, Thanks!

**Comment by dothebart** [comment]
Hi, 
One should note that the intended way is to derive the docker container the way its documented over here: 

https://github.com/arangodb/arangodb-docker/tree/official/test-user-scripts
