### ISSUE TITLE
Query slow while creating an index or bulk update a collection 

### ISSUE THREAD

**Issue by sajeevpr** [arangodb/arangodb#2247]
Dear team,
   We are using Arangodb 3.1.2 in red hat 6.6.
We have one issue of slow query performance while creating any index in collection. The query sometimes run for few minutes. One time we had to restart the DB.

Is there any way this can be avoided. The issue also came when I bulk updated a collection.

Regards 
Sajeev

**Comment by baslr** [comment]
Afaik while the index builds the particular collection is locked.

How many docs do you bulk update?

**Comment by sajeevpr** [comment]
Hi @baslr,
   I have a collection of 12 million records. I am facing this problem when I create a new index or create a derived field from existing field for all records.

So is there any way this can be mitigated. If not then I cannot create an index with out stopping the request traffic.

Regards,
Sajeev

**Comment by baslr** [comment]
I think its not a problem that the handling of a transaction with 12*10^6 docs takes more than a few seconds.

You could break up your update into smaller batches; 1000 to 10000 docs at once. You have to try it out which responce time is ok for you.

You could work with 2 ArangoDB servers. Create the additional index on one server let him catch up and switch the traffic to this server.

**Comment by sajeevpr** [comment]
Ok. So this need to be handled outside Arangodb. If I update 1000 records, it locks 1000 records or the entire collection?. For index creation, it will lock the entire collection I Guess.

**Comment by weinberger** [comment]
Yes, the index holds a lock. That we will change soon, hopefully also 3.2.

**Comment by sajeevpr** [comment]
Ok. Thank you.

**Comment by sleto-it** [comment]
Hi all,

This ticket is quite old, and the 3.1.x server of @sajeevpr is running with no particular issues right now, AFAIK

I think we should close this public ticket and discuss any specific issues @sajeevpr is experiencing in our private Jira

Please comment if needed - and we will reopen it

Many thanks,
