### ISSUE TITLE
RestReplicationHandler error while importing into cluster instance

### ISSUE THREAD

**Issue by kwaeckerli** [arangodb/arangodb#2251]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [x] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [x] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [x] own infrastructure
- [x] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [x] other: CentOS
- [ ] Windows, version: 
- [ ] MacOS, version:

I set up a DCOS cluster and am now trying to import my data. It all runs fine until import fails with below error message. From then on I'm unable to import anything (get the same message again even for another collection).

Replication factor is set to 2.

~/bu > arangorestore --server.endpoint tcp://172.16.100.98:1026 --server.username username --server.database myGraph --create-collection false --import-data true --input-directory "dump"
Please specify a password: 
Server version: 3.1.7
# Connected to ArangoDB 'http+tcp://172.16.100.98:1026'
# Loading data into document collection 'ZPersonas'...
2017-01-06T16:01:53Z [31416] ERROR internal error: got error from server: HTTP 500 (Internal Server Error): ArangoError 4: internal error (exception location: /var/lib/jenkins/workspace/RELEASE__BuildPackages/arangod/RestHandler/RestReplicationHandler.cpp:2672). Please report this error to arangodb.com
Processed 1 collection(s), read 16777216 byte(s) from datafiles, sent 2 batch(es)

I'm not sure if there are any further logfiles in the cluster anywhere, the mesos logs don't seem to show much about the arangodb framework.

**Comment by m0ppers** [comment]
Closing in favour of #2292 . If you think otherwise just reopen!
