### ISSUE TITLE
edge traversal joins

### ISSUE THREAD

**Issue by gregorybleiker** [arangodb/arangodb#2256]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ x] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ x] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ x] other: Arch Linux
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ x] I'm using graph features

I'm issuing AQL via:
- [ x] web interface with this browser:     running on this OS: Arch Linux
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

for vehicle in any 'tags/land' tagged
    for type in any 'tags/public' tagged
    filter vehicle._id == type._id
    return {vehicle,type}

The issue can be reproduced using this dataset:
tagged collection:
{"_key":"air_to_airplane","_from":"tags/air","_to":"objects/airplane"}
{"_key":"land_to_car","_from":"tags/land","_to":"objects/car"}
{"_key":"land_to_bicycle","_from":"tags/land","_to":"objects/bicycle"}
{"_key":"land_to_train","_from":"tags/land","_to":"objects/train"}
{"_key":"water_to_boat","_from":"tags/water","_to":"objects/boat"}

{"_key":"fast_to_airplane","_from":"tags/fast","_to":"objects/airplane"}
{"_key":"fast_to_car","_from":"tags/fast","_to":"objects/car"}
{"_key":"slow_to_bicycle","_from":"tags/slow","_to":"objects/bicycle"}
{"_key":"fast_to_train","_from":"tags/fast","_to":"objects/train"}
{"_key":"slow_to_boat","_from":"tags/slow","_to":"objects/boat"}

{"_key":"public_to_airplane","_from":"tags/public","_to":"objects/airplane"}
{"_key":"private_to_car","_from":"tags/private","_to":"objects/car"}
{"_key":"private_to_bicycle","_from":"tags/private","_to":"objects/bicycle"}
{"_key":"public_to_train","_from":"tags/public","_to":"objects/train"}
{"_key":"public_to_boat","_from":"tags/public","_to":"objects/boat"}

tags collection:
{"_key":"land", "name":"land"}
{"_key": "air", "name":"air"}
{"_key": "water", "name":"water"}
{"_key":"public", "name":"public"}
{"_key": "private", "name":"private"}
{"_key": "fast", "name":"fast"}
{"_key": "slow", "name":"slow"}

objects collection:
{"_key":"airplane","name":"airplane"}
{"_key":"bicycle","name":"bicycle"}
{"_key":"train","name":"train"}
{"_key":"car","name":"car"}
{"_key":"boat","name":"boat"}

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

The following problem occurs: 
Only the inner FOR is executed, only the first element of the outer FOR is visited.

Instead I would be expecting: 
I would have expected the FOR operation to behave the same as when using nodes collections, e.g.
for o in objects
for t in tags
return {o,t}
would return a join-like result of objects and tags

**Comment by jsteemann** [comment]
Thanks for reporting this bug.
I fixed it in the 3.1 and devel branches. The fix will be part of 3.1.9.
By the way, I added a test case and re-used your above test data (tags, objects, tagged) for it. I hope this is not a problem.

**Comment by gregorybleiker** [comment]
Excellent! Thank you, what a reaction time!
