### ISSUE TITLE
unique constraint violated! but on which property of the object?

### ISSUE THREAD

**Issue by mygnu** [arangodb/arangodb#2260]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 3.0

On this operating system:
- [ ] Linux 
  - [ ] Fedora .rpm

I have a user model created with Foxx app, there is email and username fields that has been indexed and should be unique.

the problem is on conflict on either property I get the same error regardless of the field. I need to notify the user about where is the conflict, how should i go abut that?
I'm very new to Arango (two days)

**Comment by dothebart** [comment]
I'm sorry this is currently not easily possible. 

As a workaround you need to catch the error and run a subsequent query which looks for these conflicts.

It is already being discussed in #342 - thus closing this one as duplicate.

**Comment by mygnu** [comment]
I'm sorry to hear that :-( as my app heavily relies on letting the user know about these errors preferably a customized one too.

**Comment by dothebart** [comment]
well, just another query filtering for these unique index columns and you got the offending documents?

**Comment by dothebart** [comment]
@mygnu This is possible now. with Arangodb 3.2 which is available for download.
