### ISSUE TITLE
ArangoDB support and EOL policy?

### ISSUE THREAD

**Issue by sandermarechal** [arangodb/arangodb#2266]
What is the support and EOL policy for ArangoDB (community and enterprise versions)? I searched the website and documentation but I could not find this anywhere.

Which versions of ArangoDB are currently supported? And for how long will they be supported?

This should probably be added to the documentation or website.

**Comment by weinberger** [comment]
We started 2012 with the project, so we thought it's a little bit too early for EOL ;).

But let me try to answer your question. We support the current major release (3.x) and the last minor version (2.8) of the previous major release. That's true for both community and enterprise edition. For enterprise edition is also a longer support possible based on an individual agreement.

**Comment by sandermarechal** [comment]
Thanks, that's all I needed to know! I may be useful to add this to the documentation or your site somewhere. Feel free to close this issue otherwise.

**Comment by janavolkova9** [comment]
The info has been added to our website here: https://www.arangodb.com/subscriptions/ Closing now ;)
