### ISSUE TITLE
Arangodb max database size

### ISSUE THREAD

**Issue by sajeevpr** [arangodb/arangodb#2270]
Dear team,

  We are trying to use arangodb for storing all the events in our system, which may grow progressively to multiple terabytes, say 5 TB or 10 TB. Is the current system capable of storing data sizes of this range.

Also we will have multiple secondary indexes per collection.

Regards,
Sajeev

**Comment by weinberger** [comment]
Do you mean an single instance?

**Comment by sajeevpr** [comment]
@weinberger,
   We are ok with single or clustered.
But not too much of instances in a cluster.

Regards,
Sajeev

**Comment by weinberger** [comment]
Can you tell more about your use case? It's a graph or a document use case?

**Comment by sajeevpr** [comment]
Right now we are planning for document structure and may require graph structure if it supports in high scale.

The idea is to store all the business events in mostly append only mode.

There may be multiple collections and joins also would be required. Almost all attributes in the collection would be indexed for running queries with good performance.

There may be daily writes of 10 million records approximately.

We have linux machines of 512 GB RAM each. The number of attributes in the document would be mostly 20.

Regards,
Sajeev

**Comment by dothebart** [comment]
This question has been discussed in Jira.

**Comment by SoundsSerious** [comment]
What was the max data limit determined to be?

**Comment by adamkdean** [comment]
> This question has been discussed in Jira.

Is that publicly accessible? Could you provide a link?
