### ISSUE TITLE
vpack error caused by ARANGOIMP

### ISSUE THREAD

**Issue by new94** [arangodb/arangodb#2273]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.1.8

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [x] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an using-related issue(arangoimp):
I'm trying import data from csv(266 million records) with arangoimp:
`arangoimp --file "file" --type csv --collection "collection" --create-collection true`

Resources of system: RAM(4GB).

**ERROR error message:    got invalid vpack value on lookup (exception location: /var/lib/jenkins/workspace/RELEASE__BuildPackages/arangod/StorageEngine/MMFilesCollection.cpp:1140). Please report this error to arangodb.com**

**Comment by jsteemann** [comment]
I assume this happened in a single server instance and not in a cluster setup?

**Comment by new94** [comment]
Yes

**Comment by jsteemann** [comment]
Have there been any errors in the log files of arangod?

**Comment by new94** [comment]
@jsteemann Last messages in arangod.log:
INFO JavaScript using startup '/usr/share/arangodb3/js', application '/var/lib/arangodb3-apps'
INFO ArangoDB 3.1.8 [linux] 64bit, using VPack 0.1.30, ICU 54.1, V8 5.0.71.39, OpenSSL 1.0.1f 6 Jan 2014
INFO using SSL options: SSL_OP_CIPHER_SERVER_PREFERENCE, SSL_OP_TLS_ROLLBACK_BUG
INFO Authentication is turned on
INFO Authentication system only
INFO Authentication for unix sockets is turned on
INFO file-descriptors (nofiles) hard limit is 131072, soft limit is 131072
INFO running WAL recovery (3 logfiles)
INFO replaying WAL logfile '/var/lib/arangodb3/journals/logfile-227293052.db' (1 of 3)
INFO replaying WAL logfile '/var/lib/arangodb3/journals/logfile-228075227.db' (2 of 3)
INFO replaying WAL logfile '/var/lib/arangodb3/journals/logfile-230312173.db' (3 of 3)
INFO WAL recovery finished successfully
INFO JavaScript using startup '/usr/share/arangodb3/js', application '/var/lib/arangodb3-apps'
INFO In database '_system': Database is up-to-date (30108/standalone/existing)
INFO using endpoint 'http+tcp://127.0.0.1:8529' for non-encrypted requests
INFO ArangoDB (version 3.1.8 [linux]) is ready for business. Have fun!

**Comment by new94** [comment]
@jsteemann 
![screenshot from 2017-01-16 17-34-15](https://cloud.githubusercontent.com/assets/3996014/21986865/3d80d1da-dc12-11e6-85d1-a87af2ac1fbf.png)
screenshot error

**Comment by dothebart** [comment]
Hi, 
We have fixed similar issues with ArangoDB 3.2.9. If the issue re-occours, feel free to comment & we will re-open this. 

Will close it as solved for now.
