### ISSUE TITLE
Too much disk I/O during import

### ISSUE THREAD

**Issue by sdy7** [arangodb/arangodb#2278]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ * ] 3.0
- [ * ] 3.1

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ * ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

Server: AWS EC2, c4.xlarge, 7.5 GB Ram, disk 420 GB gp2 SSD type.
ArangoDB installed on a plain Ubuntu 16.04 using apt, Currently ArangoDB version 3.1.8
Single instance, not cluster.
Dataset: 43 million documents, data 33 GB, index 2GB (only on _key, no additional indexes). 
Loading using arangoimp wrapped by a script that loads 1M records at a time from JSON data files.
Journal size: 	33.55 MB
Wait for sync: 	false 

This is working well on ArangoDB 2.8.x and 3.0.x series. As data is taking up much mores space than RAM available, the engine is automatically syncing/unloading data to disk nicely while importing. And there are plenty of space for the index.

On ArangoDB 3.1.x, there is an issue on this. The arangod service dies after only ~25% is loaded.  There are no errors reported in /var/log/arangodb3/

We have identical servers running where only the ArangoDB version 3.0.12 and 3.1.8 is different.
What else should I look for? How can I help figuring this out?

One observation that needs attention is that disk I/O burst balance has a significant drop when running 3.1. When this happens, disk write activity is blocked or very slow. Can this cause internally unhandled timeouts?
On the instances running 3.0.12, the burst balance is hardly affected while loading data. Are there substantial differences in how data is unloaded/synced to disk between 3.0.x and 3.1.x that challenges the I/O capacity more in the latter case?

More info in the burst balance and I/O credits in AWS:
https://aws.amazon.com/blogs/aws/new-burst-balance-metric-for-ec2s-general-purpose-ssd-gp2-volumes/

**Comment by razvanphp** [comment]
Did you try using persistent indices for this heavy one at least? Then you would avoid this I/O problems at startup...

From experience I can tell you, it's better to fit your data in RAM for best performance, and this is valid even for mysql.

**Comment by sdy7** [comment]
on this collection we don't have additional indexes besides the automatic one on _key

**Comment by sdy7** [comment]
We have tested the recent version 3.1.12 several times. It now loads via arangoimp without crashing. Something related to this has been fixed, and half of the issue behind this ticket is resolved. Very good!

We totally agree with the previous comment that more RAM is better, but a DB with on-disk persistency should unload safely and it does that now. However there is still an issue with the disk I/O intensive behaviour that causes depletion of the burst credits on AWS gp2 disks. The same dataset on the same hardware takes less than 30 minutes to load on ArangoDB v. 3.0.x, but with 3.1.12 it takes 8 hours due the burst credit is used up.

Are there an undesired overhead in I/O while saving to disk? Or could it be scheduled or throttled differently via a setting for example? Is it OK if we keep this ticket open for this or does it belong to a different scope? Is it already taken care of in 3.2.x?

**Comment by dothebart** [comment]
It could be good if you'd be willing to testdrive the 3.2 alpha2 on a separate installation (its not backwards compatible) - whether this behaviour improves - It should use less RAM - maybe that reduces i.e. swapping and use of these credits?

**Comment by sdy7** [comment]
I tried out 3.2 alpha2. 5-10% shorter load time, but still the same issue as in 3.1.12

**Comment by dothebart** [comment]
Ok, we've been able to reproduce this. We need to investigate more next week.

**Comment by dothebart** [comment]
Investigation ongoing - will become a bigger task.

**Comment by sdy7** [comment]
Great. We will stand by for testing when needed.

**Comment by sdy7** [comment]
We tried the same test on ArangoDB3.2 beta1 with RocksDB: Better load time than 3.2 alpha2, but the problem is still there compared to ArangoDB 3.0.x. 
Is there a status on figuring out what is causing this?

**Comment by vinaypyati** [comment]
Hi @sdy7,

ArangoDB 3.4 RC 1 has been released, which includes many performance improvements`. You can find the ArangoDB 3.4 RC 1 [here ](https://www.arangodb.com/download-technical-preview/). Let us know your feedback!

Thanks!

**Comment by maxkernbach** [comment]
Hi @sdy7,

did you already try 3.4 RC1?
FYI: The latest available 3.4 Release Candidate is RC2 and can be found in the [download section](https://www.arangodb.com/download-technical-preview/).

Your feedback is highly appreciated!

**Comment by sdy7** [comment]
Hi, in general the I/O burst balance has been less effected since we switched to 3.3 / RocksDB. Going from blocking to tolerable.
We will definitely do testing with this in focus also as soon as possible on 3.4, too.
Thanks

**Comment by vinaypyati** [comment]
Hi,

Thanks for the feedback. Glad that I/O burst balance has been less affected. Just letting you know that 3.4.0 RC3 has been released. You can download it from the [download section](https://www.arangodb.com/download-technical-preview/). 

Thanks!

**Comment by sdy7** [comment]
Hi ArangoDB team. We tested load on 3.4.0RC.4 and compared with the exact load task (~85 million docs) on 3.3.x. There is a significant improvement on the EC2 EBS I/O burst balance. On 3.4 it never drops below 99.9 and on 3.3.x it drops to 96.8 (lower is bad) but this is still not low enough to be critical. It was critical on 3.0 - 3.2 with mfiles.

There is no significant difference in the over all load time in this task comparison, meaning that it has now been proven that I/O burst is no longer a bottleneck if any at all. We can close this as solved if you like.

Happy applause to the ArangoDB team from us.

**Comment by vinaypyati** [comment]
Hi,

Thanks for testing and we are glad that I/O burst is no longer a bottleneck for you. In case you see this issue again, feel free to reopen this ticket. 

Thanks!
