### ISSUE TITLE
Installation error: GnuTLS recv error (-110): The TLS connection was non-properly terminated.

### ISSUE THREAD

**Issue by AlexLuya** [arangodb/arangodb#2282]
When installing,I got this error:
```
Err:1 https://www.arangodb.com/repositories/arangodb31/xUbuntu_16.04  arangodb3 3.1.8
  GnuTLS recv error (-110): The TLS connection was non-properly terminated.
E: Failed to fetch https://www.arangodb.com/repositories/arangodb31/xUbuntu_16.04/amd64/arangodb3-3.1.8-1_amd64.deb  GnuTLS recv error (-110): The TLS connection was non-properly terminated.
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
by the way,this happened in china.

**Comment by jsteemann** [comment]
I tried downloading the file `https://www.arangodb.com/repositories/arangodb31/xUbuntu_16.04/amd64/arangodb3-3.1.8-1_amd64.deb` manually and it works from here.
Can you try again? Maybe this was a temporary error.

**Comment by AlexLuya** [comment]
yep,worked now,but very slow,12k/s

**Comment by AlexLuya** [comment]
@jsteemann,installlation interrupted,got the problem that I reported before:https://github.com/arangodb/arangodb/issues/1924

**Comment by baslr** [comment]
@AlexLuya can you post a `traceroute` to arangodb.com, or in wich country you are?

**Comment by AlexLuya** [comment]
china

**Comment by baslr** [comment]
Ok, this explains the slow download. It could be that the great firewall doesnt like https traffic and so slows it down on purpose.

The best way would be to wget the deb and then use dpkg to install it.

**Comment by AlexLuya** [comment]
Yes,I knew it,but other ppas installation work fine

**Comment by dothebart** [comment]
Hi, 
I don't see any way to fix this on the site of the arangodb team. 
We neither have a way to patch ubuntu binaries, nor can we fix the great wall.

I can only sugest you to set up something like apt-cacher or squid as a workaround for this. 
https://help.ubuntu.com/community/Apt-Cacher-Server

**Comment by dothebart** [comment]
Hi, 
If you have problems to upgrade to 3.1.11 (available for download now) via an apt-cacher server please report back. Closing now.

**Comment by sherlocksho** [comment]
> When installing,I got this error:
> 
> ```
> 
> Err:1 https://www.arangodb.com/repositories/arangodb31/xUbuntu_16.04  arangodb3 3.1.8
> 
>   GnuTLS recv error (-110): The TLS connection was non-properly terminated.
> 
> E: Failed to fetch https://www.arangodb.com/repositories/arangodb31/xUbuntu_16.04/amd64/arangodb3-3.1.8-1_amd64.deb  GnuTLS recv error (-110): The TLS connection was non-properly terminated.
> 
> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
> 
> ```
> 
> by the way,this happened in china.

The same happened in my phone

**Comment by dothebart** [comment]
Are you shure your phone is able to run ArangoDB in first place?
