### ISSUE TITLE
ArangoDB 2.8 Install Fails Due to Expired GPG Key

### ISSUE THREAD

**Issue by jrisebor** [arangodb/arangodb#2285]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- 2.8

On this operating system:
- Linux Ubuntu 16.04 x86_64

### this is an installation-related issue:
I followed the steps on the install page: https://www.arangodb.com/download-previous/_ubuntu/
`sudo apt update` returns this:
```
W: GPG error: https://www.arangodb.com/repositories/arangodb2/xUbuntu_16.04  Release: The following signatures were invalid: KEYEXPIRED 1484917768
E: The repository 'https://www.arangodb.com/repositories/arangodb2/xUbuntu_16.04  Release' is not signed.
```
Looking at the key with `sudo apt-key list` shows:
```pub   2048R/89A14917 2014-11-12 [expired: 2017-01-20]```

### Speculation
It looks like the release.key expired recently and needs to be updated.

**Comment by baslr** [comment]
@jrisebor please have a look at #2284 and #2031

**Comment by jrisebor** [comment]
@baslr I was looking at those before I submitted the issue, and they seem like different issues.

Those issues look like the have to do with the digest algorithm (SHA1) or with the signing cryptography used, where the issue I'm having seems to be more specific to the public key (specifically its expiry on 2017-01-20).

**Comment by dothebart** [comment]
@jrisebor #2284 is the same, since 3.0 and 2.8 where built using suse OBS.

However, the last time these repositories were updated that key was still valid. 
Once we release newer versions to these, we will use a newer key, as we do in the 3.1 repositories.

**Comment by jrisebor** [comment]
@dothebart Thanks for the clarification.

It would be nice to have a note on the 2.8 installation page noting that apt installation is no longer supported: https://www.arangodb.com/download-previous/_ubuntu/

I think for now I'll just install the .deb directly.

**Comment by dothebart** [comment]
We have cleaned up and re-signed the 2.x repositories; Files are now signed with a fresh key, and Packages-files contain strong signatures.
