### ISSUE TITLE
TypeError: Cannot read property '_query' of undefined while using db object in Foxx sub modules 

### ISSUE THREAD

**Issue by sajeevpr** [arangodb/arangodb#2286]
Dear team,
  We are trying to use db object inside a sub module Javascript file and getting this error.

db object is working perfectly in main.js and not in imported Javascript files.

Arangodb version- 3.1.2

Regards,
Sajeev

**Comment by jsteemann** [comment]
`db` is probably undefined if you don't explicitly include it from somewhere.
Can you try putting `var db = require("@arangodb").db;` at the beginning of your imported modules?

**Comment by sajeevpr** [comment]
Yes, it is working now when I kept this inside the Javascript method. But not working when I declared this outside method in the file level below 'use strict'

Thank you @jsteeman

**Comment by pluma** [comment]
Can you clarify what your code looked like before and after? I'm not sure how this could go wrong.

**Comment by sajeevpr** [comment]
@pluma,
   When I use the below, it's working 

function getData(request){
    var db = require(@arangodb).db
}

But I declare db object outside function, it is not working 

Regards,
Sajeev

**Comment by pluma** [comment]
@sajeevpr can you provide a minimal Foxx service showing the problem as zip file? I must be missing something you're doing different.

**Comment by pluma** [comment]
I can't reproduce this error without an example so I'm closing this as unreproducible.

Feel free to reopen the issue if you find a minimal example that triggers this behaviour.
