### ISSUE TITLE
The documentation tarball should not be a "tarbomb"

### ISSUE THREAD

**Issue by filterfish** [arangodb/arangodb#2287]
When I untar the documentation tarball there was no top level directory so the existing directory contained three new directories: `HTML`, `ACL` & `Manual` plus a file: `index.html`. While the first three weren't an issue it overwrote an already exinst `index.html`.

This is an installation-related issue:

The tarball should have a top level directory name after the file.

**Comment by dothebart** [comment]
the tarballs now include a toplevel directory in the pattern of `ArangoDB-3.1.12`; plus they will also contain the current cookbook.

**Comment by filterfish** [comment]
@dothebart thanks for sorting that out.
