### ISSUE TITLE
Typo error in HTTP documentation

### ISSUE THREAD

**Issue by njouanin** [arangodb/arangodb#2289]
There seems to be have to typo [collection API documentation](https://docs.arangodb.com/3.1/HTTP/Collection/Getting.html). For `figures` and `statistics` API, the documentation mention a `maxTick` attribute _"The tick of the last marker that was stored in a journal of the collection. This might be 0 if the collection does not yet have a journal."_ 
Examples below and test made on my arangodb 3.1.8 installation shows that the attribute is called `lastTick`, so the API documentation seems to be incorrect. Am I wrong ?

**Comment by jsteemann** [comment]
Thanks for reporting this. Should be fixed now in 3.1 and the devel branches.

**Comment by dothebart** [comment]
The 3.1 documentation was updated with the 3.1.10 release last friday - fixed.
