### ISSUE TITLE
Arangodb on multiple datacenters

### ISSUE THREAD

**Issue by sajeevpr** [arangodb/arangodb#2293]
Dear Team,

  We are trying to set up arangodb in production where we have two data centers.

So we would like to know which would be the best configuration.

1. Active-Active
2. Active-passive

If we go for active-passive, is there any way we can configure asynchronous replication.
Also is there any problems, if we configure active-active on top of dc/os.

Regards,
Sajeev

**Comment by MrPieces** [comment]
Dear Sajeev,

Github issues are not meant to be a support platform for development or architecture questions but rather a place to discuss issues a software might have and learn about the progress of that issue. 
If you like to learn more about how ArangoDB can help you with your multi datacenter questions please contact me via jan.stuecke (at) arangodb.com

Regards,

Jan

**Comment by sajeevpr** [comment]
I am sorry for posting this question here. I will contact you over an email.

Thanks & Regards,
Sajeev
