### ISSUE TITLE
Query Language : AQL, GraphQL, ReQL...

### ISSUE THREAD

**Issue by Eliakos** [arangodb/arangodb#2300]
Hi,

I like ArangoDB but don't like AQL SQL-like query language approach.
I very much prefer GraphQL approach but regarding GraphQL drawback mentionned here https://www.arangodb.com/2016/02/using-graphql-nosql-database-arangodb/, i don't look at it as a very good idea to use it.

Do we have an alternative for javascript developers? maybe in Foxx for example?

I love Reql from Rethinkdb, directly embedded into your javascript code, chainable queries executed on the server...
Do we have something similar?

**Comment by StarpTech** [comment]
@Eliakos before something can be improved the issue must be detected. What you don't like in AQL? AQL is a query language specially developed for the data model of Arangodb with consideration for peformance  and simplicity. Please specify your problem. In the link you mention there is a graphql example. In my opinion the AQL query is very straightforward.

**Comment by Eliakos** [comment]
@StarpTech AQL is more a declarative approach while ReQL is more a functional approach. I think you agree there is not much to say about the fact these are different approachs; OR we can talk a lot about the academics of the 2 approachs but it far beyong the scope of my question.

On another side, we can talk, never ending, about the preferences of each person, but at the end, that will still not answer my question : do we have alternative to AQL?

You mention chainable syntax, is it related to AQL? I just see one page in the documentation, maybe we have tutorials or docs elsewhere on this? I also saw in the documentation GraphQL could be ran on the server, does that avoid the GraphQL drawback noticed in the blog article?

**Comment by StarpTech** [comment]
@Eliakos you still don't answer my question. What is wrong with AQL what you can't archive with AQL but with ReQL? Are your reasons only primarily personal?

[Query builder](https://github.com/arangodb/arangojs#queries)
```js
// Using the query builder
var qb = require('aqb');
db.query(
    qb.for('u').in('_users')
    .filter(qb.eq('u.authData.active', '@active'))
    .return('u.user'),
    {active: true}
)
.then(cursor => {
    // cursor is a cursor for the query result
});
```

**Comment by StarpTech** [comment]
@Eliakos I don't recommend to make graphl dependend from a single database because that will destroy some significant benefits which graphql brings with ( to be datasource agnostic, everything must be implemented on arangodb side) btw: Graphql from arangodb is synchronous https://github.com/arangodb/graphql-sync. One big reasons why GraphQl was created is to serve hundred of client dont matter which data from which source they need.

**Comment by Eliakos** [comment]
@StarpTech 

Isn't GraphQL,through Appollo, interesting for making work arangodb and Meteor? But then it may be against tour recommendation.

What i would like with AQL or whatever alternative is to contruct queries in javascript, ie not having to concatenate strings, and with which we can chain commands, maybe it's what aqb is about? 

For now, i see AQL like SQL. I like when things are fluid, for example by not having to brain switch between different contexts (you can think of php on server side, javascript on client side, or here javascript in which we insert SQL like language).

Is your code example an aqb query style? 
In fact, i need to read more about aqb, maybe it's what i'm looking for.

**Comment by dothebart** [comment]
@Eliakos you can use [Javascript template strings](https://www.arangodb.com/2015/08/on-building-aql-query-strings/) if that pleases you better?

The reason the ArangoDB GraphQL implementation is synchroneous is, that its run inside of the database. So there is nothing else to do with the worker thread than working for you resolving that query - you don't have an external process that is blocking on this.

**Comment by Eliakos** [comment]
@dothebart Thanks you dothebart but template strings illustrate what i mentionned i would like to avoid, ie building strings or having a language inside another one, reason why i mentionned ReQL in the first place to show what kind of things i'm looking for (pure javascript, chainable commands...)

**Comment by Simran-B** [comment]
Then you should use aqb to build your queries in JavaScript-style way. Note that it ultimately turns the internal representation into an AQL string. Even requests to the simple query endpoints are turned into AQL internally. Also note that aqb does not support all language features of AQL.

**Comment by Eliakos** [comment]
@Simran-B  Thanks you, good to know. Does the documentation mention what AQL language features are not covered ? AQL is a good fit for some people, for me it's a "distraction" that put my focus away, i will keep up with aqb.

**Comment by Eliakos** [comment]
Thanks again Simran, you answered the issue subject by giving aqb as the solution.

**Comment by Simran-B** [comment]
It is not explicitly documented what is missing in aqb, but I remember that some function shortcuts are missing (e.g. `qb.DISTANCE(...)`). You can use the slightly more cumbersome syntax `qb.fn('DISTANCE')(...)` however for any function. The no longer officially supported graph functions are still available aqb on the other hand. AQL Graph traversal is not supported. [Array operators](https://docs.arangodb.com/3.1/AQL/Advanced/ArrayOperators.html) and [array comparison operators](https://docs.arangodb.com/3.1/AQL/Operators.html#array-comparison-operators) are not available either. There might be more to add to this list.
