### ISSUE TITLE
Graph Java API

### ISSUE THREAD

**Issue by ahr12** [arangodb/arangodb#2304]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series: 3.1
On this operating system: Ubuntu 14.04

I am trying to create a graph in Arangodb using java.

package org.formcept.arangodb;
import java.util.ArrayList;
import java.util.List;

import com.arangodb.ArangoConfigure;
import com.arangodb.ArangoDriver;
import com.arangodb.ArangoException;
import com.arangodb.ArangoHost;
import com.arangodb.entity.DocumentEntity;
import com.arangodb.entity.EdgeDefinitionEntity;
import com.arangodb.entity.GraphEntity;
class Person {
	  String name;
	  String title;
	  public Person(String name, String title) {
	    this.name = name;
	    this.title = title;
	  }
	  // getter and setter
	
	}
	 
	class Publication {
	  String title;
	  String isbn;
	  int pages;
	  public Publication(String title, String isbn, int pages) {
	    this.title = title;
	    this.isbn = isbn;
	    this.pages = pages;
	  }
	  // getter and setter
	
	}
public class AdbGraph {

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		ArangoConfigure configure = new ArangoConfigure();
		ArangoHost hostObj = new ArangoHost("127.0.0.1", 8529);
		configure.setArangoHost(hostObj);
		configure.setUser("root");
		configure.setPassword("12yuvi12");
		configure.init();
		ArangoDriver arangoDriver = new ArangoDriver(configure);
		String dbName = "test";
		try { 
			  arangoDriver.createDatabase(dbName); 
			  System.out.println("Database created: " + dbName);
			} catch (Exception e) { 
			  System.out.println("Failed to create database " + dbName + "; " + e.getMessage()); 
			}
		arangoDriver.setDefaultDatabase(dbName); 
		// Edge definitions of the graph
		List<EdgeDefinitionEntity> edgeDefinitions = new ArrayList<EdgeDefinitionEntity>();
		 
		// We start with one edge definition:
		EdgeDefinitionEntity edgeDefHasWritten = new EdgeDefinitionEntity();
		 
		// Define the edge collection...
		edgeDefHasWritten.setCollection("HasWritten");
		 
		// ... and the vertex collection(s) where an edge starts...
		List<String> from = new ArrayList<String>();
		from.add("Person");
		edgeDefHasWritten.setFrom(from);
		 
		// ... and ends.
		List<String> to = new ArrayList<String>();
		to.add("Publication");
		edgeDefHasWritten.setTo(to);
		 
		// add the edge definition to the list
		edgeDefinitions.add(edgeDefHasWritten);
		 
		// We do not need any orphan collections, so this is just an empty list
		List<String> orphanCollections = new ArrayList<String>();
		 
		// Create the graph:
		try {
			GraphEntity graphAcademical = arangoDriver.createGraph("Academ", edgeDefinitions, orphanCollections, true);
			EdgeDefinitionEntity edgeDefHasCited = new EdgeDefinitionEntity();
			edgeDefHasCited.setCollection("HasCited");
			from.clear();
			from.add("Publication");
			edgeDefHasCited.setFrom(from);
			to.clear();
			to.add("Publication");
			edgeDefHasCited.setTo(to);
			 
			// add the new definition to the existing graph:
			arangoDriver.graphCreateEdgeDefinition(graphAcademical.getName(), edgeDefHasCited);
			DocumentEntity<Person> person1 = arangoDriver.graphCreateVertex("Academ", "Person", new Person("Bob", "Dr"), true);
			DocumentEntity<Person> person2 = arangoDriver.graphCreateVertex("Academ", "Person", new Person("Floyd", "master of arts"), true);
			DocumentEntity<Publication> publication1 = arangoDriver.graphCreateVertex("Academ", "Publication", new Publication("Surgery for dummies", "1-234-1", 42), true);
			DocumentEntity<Publication> publication2 = arangoDriver.graphCreateVertex("Academ", "Publication", new Publication("Relaxing while working", "5-678-x", 815), true);
			DocumentEntity<Publication> publication3 = arangoDriver.graphCreateVertex("Academ", "Publication", new Publication("Infrasound in art and science", "7-081-5", 60), true);
			arangoDriver.graphCreateEdge("Academ", "HasWritten", null, person1.getDocumentHandle(), publication1.getDocumentHandle());
			arangoDriver.graphCreateEdge("Academ", "HasWritten", null, person2.getDocumentHandle(), publication2.getDocumentHandle());
			arangoDriver.graphCreateEdge("Academ", "HasWritten", null, person2.getDocumentHandle(), publication3.getDocumentHandle());
			arangoDriver.graphCreateEdge("Academ", "HasCited", null, publication1.getDocumentHandle(), publication3.getDocumentHandle());
			arangoDriver.graphCreateEdge("Academ", "HasCited", null, publication1.getDocumentHandle(), publication2.getDocumentHandle());
			 

		} catch (ArangoException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		 

		
	}

}

but I am getting the following errors-
Exception in thread "main" java.lang.NumberFormatException: For input string: "_Ufe_Com---"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.parseLong(Long.java:631)
	at com.arangodb.http.HttpManager.buildHttpResponseEntity(HttpManager.java:488)
	at com.arangodb.http.HttpManager.executeInternal(HttpManager.java:432)
	at com.arangodb.http.HttpManager.execute(HttpManager.java:369)
	at com.arangodb.http.BatchHttpManager.execute(BatchHttpManager.java:27)
	at com.arangodb.http.HttpManager.doPostPutPatch(HttpManager.java:351)
	at com.arangodb.http.HttpManager.doPost(HttpManager.java:294)
	at com.arangodb.impl.InternalGraphDriverImpl.createGraph(InternalGraphDriverImpl.java:82)
	at com.arangodb.ArangoDriver.createGraph(ArangoDriver.java:3510)
	at org.formcept.arangodb.AdbGraph.main(AdbGraph.java:84)

**Comment by mpv1989** [comment]
Hi,

this looks like you're using an old version of the java driver, which doesn't support ArangoDB 3.1.
You can take a look [here ](https://github.com/arangodb/arangodb-java-driver#supported-versions) for informations about the supported versions.

With ArangoDB 3.1 we also released a new java driver ([blogpost](https://www.arangodb.com/2016/10/updated-java-drivers-with-arangodb-3-1/)) which offers better performance and is much nicer to use. Even if the old driver is still supported you should really take a look at it.

Best
Mark

**Comment by ahr12** [comment]
Thanks. now, It's working fine. I want to use some queries like -shortest path in the graph. can you help me for this.

**Comment by mpv1989** [comment]
I suggest you to take a look at our [docu](https://docs.arangodb.com/3.1/AQL/Graphs/ShortestPath.html) and if you have questions please use [stackoverflow](http://stackoverflow.com/questions/tagged/arangodb), [slack ](https://slack.arangodb.com/) or [google-groups](https://groups.google.com/forum/#!forum/arangodb). Github should only be used for reporting bugs.
