### ISSUE TITLE
[feature request] export result to CSV

### ISSUE THREAD

**Issue by ericman93** [arangodb/arangodb#2306]
Hi
Right now it is possible to export results to JSON.
I would like to export the data to CSV format if the query is a table

Thanks

**Comment by baslr** [comment]
Hi @ericman93,

do you mean a csv download in the web interface?

**Comment by ericman93** [comment]
yes

**Comment by Simran-B** [comment]
But how would you expect arrays and nested values to be mapped to CSV?

**Comment by ericman93** [comment]
The web client knows to display table when there are no nested values.
So if there are no nested value I want a to download the values as CSV

**Comment by dothebart** [comment]
With ArangoDB 3.2 we've added [ArangoExport](https://docs.arangodb.com/devel/Manual/Administration/Arangoexport.html) - which is a standalone binary.
So it addresses this issue partially.

**Comment by hkernbach** [comment]
Nice to hear. We also included CSV export within the ui query editor. Exporting CSV is now possible if only flat (not nested) data is returned.

**Comment by dothebart** [comment]
We're pleased to anounce that ArangoDB 3.2 containing this is now available for download - Closing.
