### ISSUE TITLE
Queries ending on a null result break the web frontend queries page

### ISSUE THREAD

**Issue by ropeladder** [arangodb/arangodb#2308]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [X] 3.0 (3.1.10)

On this operating system:
  - [X] Ubuntu .deb

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [X] web interface with this browser: Firefox 51.0.1    running on this OS: Linux Mint 18.1

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.

The AQL query in question is:
```
LET arr = [{a:1},{b:3}]
FOR item IN arr
RETURN item.a
```

### this is a web interface-related issue:
I'm using the web interface with this browser: Firefox 51.0.1    running on this OS: Linux Mint 18.1
- [ ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database? <-- doesn't matter

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as root
3) use database [X] `_system` (doesn't matter)
4) click to queries page, and run the query above

The following problem occurs:
When running the final RETURN result is null, it appears to break the web interface somehow. The "Query" box opens below and says "Query is operating..." but never finishes. Clicking "Cancel" does nothing. Clicking to "Running Queries" reveals that there are no queries currently running. Clicking back to the Queries tab shows that the "Query is operating..." box has disappeared.

Instead I would be expecting: 
```
[ 
  1, 
  null 
]
```
(this is what I get in arangosh)

**Comment by hkernbach** [comment]
Hello. Thanks for the feedback. Fixed that about 6 hours ago https://github.com/arangodb/arangodb/commit/a635b0ee59d77b20fdb9d59a46970877b98ba456

**Comment by dothebart** [comment]
Hi, 3.1.11 is available for dowload now. Closing.
