### ISSUE TITLE
Reinstall ArangoDB

### ISSUE THREAD

**Issue by Rucchao** [arangodb/arangodb#2309]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ x] 3.0
On this operating system:
  - [x ] Ubuntu .deb

after having remove all arangodb-related files, reinstall it  sudo dpkg -i arangodb3-3.1.7-1_amd64.deb

encounted an error: 

**no database path has been supplied, giving up, please use the '--database.directory' option**

no config file generated under /etc/arangodb3

**Comment by dothebart** [comment]
Please use the latest ArangoDB of a release series - Currently ArangoDB 3.1.10
