### ISSUE TITLE
Cannot launch the cluster

### ISSUE THREAD

**Issue by Rucchao** [arangodb/arangodb#2310]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:

node A:
Starting coordinator on port 8530
Agent up and running.

 **ERROR {cluster} cannot create connection to server '' at endpoint 'tcp://
 ERROR {agencycomm} Error transforming result. Expecting item**

node B,C:

**Agent not ready after 5min!
DBserver not ready after 5min!**

**Comment by dothebart** [comment]
Hi, did you follow the advices on https://docs.arangodb.com/3.1/Manual/Deployment/ ? 
The error shows that you didn't provide an endpoint in that part of the configuration.

**Comment by dothebart** [comment]
you now should follow https://docs.arangodb.com/3.2/Manual/Deployment/ArangoDBStarter.html to use the arangodb starter for creating clusters. 
If it doesn't work out, feel free to open a ticket on https://github.com/arangodb-helper/ArangoDBStarter/

**Comment by dothebart** [comment]
We now have ArangoDB distributed with the arangodb packages; The new manual contains a chapter about how to use it: https://docs.arangodb.com/3.2/Manual/Deployment/ArangoDBStarter.html
So I will close this issue now. Feel free to open a new one if arangodbstarter (or the documentation) doesn't work for you.
