### ISSUE TITLE
Compiled to arangodb 3.1 for windows.

### ISSUE THREAD

**Issue by kyrietiger** [arangodb/arangodb#2311]
environments:
       Qt5.8
       Arangodb 3.1
       windows7 x64
 problem:
      Running "D:\cmake-3.8.0-rc1-win64-x64\bin\cmake.exe E:/arangodb-3.1 "-GCodeBlocks - MinGW    Makefiles" "-DCMAKE_CXX_COMPILER:STRING=D:/Qt/Qt5.8/Tools/mingw530_32/bin/g++.exe" "-DCMAKE_C_COMPILER:STRING=D:/Qt/Qt5.8/Tools/mingw530_32/bin/gcc.exe" "-DCMAKE_PREFIX_PATH:STRING=D:/Qt/Qt5.8/5.8/mingw53_32" "-DQT_QMAKE_EXECUTABLE:STRING=D:/Qt/Qt5.8/5.8/mingw53_32/bin/qmake.exe"" in C:\Users\Administrator\AppData\Local\Temp\qtc-cmake-piLz0c.
-- The CXX compiler identification is GNU 5.3.0
-- The C compiler identification is GNU 5.3.0
-- Check for working CXX compiler: D:/Qt/Qt5.8/Tools/mingw530_32/bin/g++.exe
-- Check for working CXX compiler: D:/Qt/Qt5.8/Tools/mingw530_32/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: D:/Qt/Qt5.8/Tools/mingw530_32/bin/gcc.exe
-- Check for working C compiler: D:/Qt/Qt5.8/Tools/mingw530_32/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PythonInterp: C:/Python27/python2.exe (found suitable exact version "2.7.10") 
-- Performing Test _HAS_CXX11_FLAG
-- Performing Test _HAS_CXX11_FLAG - Success
-- Checking C++11 support for "__func__"
-- Checking C++11 support for "__func__": works
-- Checking C++11 support for "auto"
-- Checking C++11 support for "auto": works
-- Checking C++11 support for "auto_ret_type"
-- Checking C++11 support for "auto_ret_type": works
-- Checking C++11 support for "class_override_final"
-- Checking C++11 support for "class_override_final": works
-- Checking C++11 support for "constexpr"
-- Checking C++11 support for "constexpr": works
-- Checking C++11 support for "conditional"
-- Checking C++11 support for "conditional": works
-- Checking C++11 support for "decltype"
-- Checking C++11 support for "decltype": works
-- Checking C++11 support for "initializer_list"
-- Checking C++11 support for "initializer_list": works
-- Checking C++11 support for "lambda"
-- Checking C++11 support for "lambda": works
-- Checking C++11 support for "range_based_for_loop"
-- Checking C++11 support for "range_based_for_loop": works
-- Checking C++11 support for "nullptr"
-- Checking C++11 support for "nullptr": works
-- Checking C++11 support for "tuple"
-- Checking C++11 support for "tuple": works
-- Checking C++11 support for "regex"
-- Checking C++11 support for "regex": works
-- Checking C++11 support for "rvalue-references"
-- Checking C++11 support for "rvalue-references": works
-- Checking C++11 support for "sizeof_member"
-- Checking C++11 support for "sizeof_member": works
-- Checking C++11 support for "static_assert"
-- Checking C++11 support for "static_assert": works
-- Checking C++11 support for "variadic_templates"
-- Checking C++11 support for "variadic_templates": works
-- Checking C++11 support for "shared_ptr"
-- Checking C++11 support for "shared_ptr": works
-- Checking C++11 support for "unique_ptr"
-- Checking C++11 support for "unique_ptr": works
-- Checking C++11 support for "weak_ptr"
-- Checking C++11 support for "weak_ptr": works
-- Checking C++11 support for "thread"
-- Checking C++11 support for "thread": works
-- Checking C++11 support for "mutex"
-- Checking C++11 support for "mutex": works
-- Checking C++11 support for "noexcept"
-- Checking C++11 support for "noexcept": works
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Could NOT find jemalloc (missing:  JEMALLOC_INCLUDE_DIR JEMALLOC_LIBRARIES) 
-- using 3rdParty BOOST
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - not found
-- Looking for stdint.h
-- Looking for stdint.h - not found
-- Looking for stddef.h
-- Looking for stddef.h - not found
-- Check size of unsigned short
-- Check size of unsigned short - failed
-- Check size of unsigned int
-- Check size of unsigned int - failed
-- Check size of unsigned long
-- Check size of unsigned long - failed
CMake Error at D:/cmake-3.8.0-rc1-win64-x64/share/cmake-3.8/Modules/TestBigEndian.cmake:41 (message):
  no suitable type found
Call Stack (most recent call first):
  3rdParty/V8/CMakeLists.txt:26 (TEST_BIG_ENDIAN)

-- Configuring incomplete, errors occurred!
See also "C:/Users/Administrator/AppData/Local/Temp/qtc-cmake-piLz0c/CMakeFiles/CMakeOutput.log".
See also "C:/Users/Administrator/AppData/Local/Temp/qtc-cmake-piLz0c/CMakeFiles/CMakeError.log".
*** cmake process exited with exit code 1.

**Comment by jsteemann** [comment]
It seems that you are using "CodeBlocks" as the cmake generator.
From the cmake output it seems like the c++ compiler environment is not properly set up:
```
-- Looking for stdint.h
-- Looking for stdint.h - not found
-- Looking for stddef.h
-- Looking for stddef.h - not found
-- Check size of unsigned short
-- Check size of unsigned short - failed
-- Check size of unsigned int
-- Check size of unsigned int - failed
-- Check size of unsigned long
-- Check size of unsigned long - failed
```
We have never the "CodeBlocks" generator, but have always used the Visual Studio 14 generator (i.e. `cmake -G "Visual Studio 14 Win64" ..`). It should work with that. Can you try switching to MSVC 14 for compilation?

**Comment by kyrietiger** [comment]
ok, thanks.

**Comment by dothebart** [comment]
I guess you got it working? So I'll close this now.
