### ISSUE TITLE
GPG signatures for source validation

### ISSUE THREAD

**Issue by NicoHood** [arangodb/arangodb#2312]
As we all know, today more than ever before, it is crucial to be able to trust
our computing environments. One of the main difficulties that package
maintainers of Linux distributions face, is the difficulty to verify the
authenticity and the integrity of the source code.

The Arch Linux team would appreciate it if you would provide us GPG signatures
in order to verify easily and quickly your source code releases.

**Overview of the required tasks:**
1. Create and/or use a 4096-bit RSA keypair for the file signing.
2. Keep your key secret, use a strong unique passphrase for the key.
3. Upload the public key to a key server and publish the full fingerprint.
4. Sign every new git commit and tag.
5. Create signed compressed (xz --best) release archives
6. Upload a strong message digest (sha512) of the archive
7. Configure https for your download server

[GPGit](https://github.com/NicoHood/gpgit) is meant to bring GPG to the masses.
It is not only a shell script that automates the process of creating new signed
git releases with GPG but also comes with this step-by-step readme guide for
learning how to use GPG.

**Additional Information:**
* https://github.com/NicoHood/gpgit
* https://help.github.com/categories/gpg/
* https://wiki.archlinux.org/index.php/GnuPG
* https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work
* https://www.qubes-os.org/doc/verifying-signatures/
* https://lkml.org/lkml/2016/8/15/445
* https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https
* https://www.enigmail.net/index.php/en/

Thanks in advance.

--> Your download page provides some .key files. However even if those are gpg signatures, there is no information about the used fingerprint. It would be better to publish the key on the website and on github. The signatures would better fit on the github page, as the website says its a legacy download page:
https://www.arangodb.com/repositories/Source/

The AUR PKGBUILD requires some rework. I will report my fixes to AUR once I am done with that.

**Comment by dothebart** [comment]
currently we only provide SHA256Sums: https://www.arangodb.com/repositories/Source/ArangoDB-3.1.10.tar.bz2.key for the source; Debs and rpms are signed. 
So, 
1, 2, 3, 7 are already here. 
Most interesting - what should 4, 5 look like? 
4. - what the git link describes?
5. - a separate file with the signature? of what? the tarball? the compressed tarball?

**Comment by NicoHood** [comment]
Hey @dothebart Thanks for the quick reply :)

.key means a shasum? this is really confusing and should be renamed. Still good to have those.

4) https://github.com/NicoHood/gpgit#32-commit-signing
5) You already have the .tar.gz by github or your own .tar.bz2. .xz will be more compressed and is better for larger projects. However if you just use the github .tar.gz its fine. The main point here is to sign this tarball: https://github.com/NicoHood/gpgit#43-sign-the-sources

Feel free to use gpgit which takes care of all required options. Or have a look at the quick start guide on how to use gpg for source signing :)

**Comment by dothebart** [comment]
5. - mostly done - the 3.2.alpha1 release and the 3.1.11 release will contain these .asc files - still missing are links to the download page.

**Comment by NicoHood** [comment]
Thanks! This looks pretty good. Would you please also post the **full* fingerprint with which the sources are signed?

**Comment by dothebart** [comment]
At least regarding signing the git tags closing this as `won't fix` since we won't do that.
