### ISSUE TITLE
Trying the nodejs tutorial and immediately hit with Unauthorized.

### ISSUE THREAD

**Issue by bdharrington7** [arangodb/arangodb#2313]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
-  3.1

On this operating system:
-  MacOS, version: 10.12.3

### this is an installation-related issue:
* following this tutorial: https://www.arangodb.com/tutorials/arangodb-node-js-2/
* Installed via brew (the preferred way)
* Started db server by calling `/usr/local/opt/arangodb/sbin/arangod`
* Got to "Creating a Database", but met with Unauthorized
```
> db.createDatabase('mydb').then(
... () => console.log("db created"),
... err => console.error('error', err));
Promise { <pending> }
> error { [UnauthorizedError: Unauthorized]
  message: 'Unauthorized',
...
```
* thought it was installed with a blank password (that's what these brew instructions said):
```
==> Caveats
An empty password has been set. Please change it by executing
  /usr/local/opt/arangodb/sbin/arango-secure-installation
```
* Tried to run that script to set a pw, but still unauthorized.

**Comment by pluma** [comment]
Try `db = new Database('http://root:@127.0.0.1:8529');` instead of `db = new Database('http://127.0.0.1:8529');` -- when authentication is enabled you still need to provide a username even if the password is empty.

We should probably adjust the tutorial. It's actually even nicer to set the credentials with the recent versions of arangojs:

`db.useBasicAuth('root', 'password')`

([see docs](https://github.com/arangodb/arangojs#databaseusebasicauth))

**Comment by pluma** [comment]
We could probably add a note before the "creating a database" bit to explain how to use `useBasicAuth` if authentication is enabled.

**Comment by bdharrington7** [comment]
It seems that authentication is enabled by default on a standard installation, even though it's the default credentials. Either the default credentials should be used in the software when none are provided, or the tutorial should explicitly say to set the credentials to 'root' and the blank password

**Comment by pluma** [comment]
I'm thinking the latter is probably the best approach because it would also show how to set the password if you did change it.

**Comment by pluma** [comment]
I think this can be closed. The recent versions of arangojs automatically use the default credentials.

**Comment by vincentp** [comment]
@pluma I have installed ArangoDB via docker using a random password. I got the "Unauthorized" error right away and had to authenticate using the method you provided db.useBasicAuth('root', 'my_password')
