### ISSUE TITLE
Skiplist index not being used on attributes of sub-documents

### ISSUE THREAD

**Issue by hariharan-uno** [arangodb/arangodb#2315]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.0

On this operating system:
- [x] Linux 
  - [x] Ubuntu .deb

### this is an AQL-related issue:
- [x] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser:  Google Chrome v 56.0  running on Ubuntu:

I have created a skiplist index for the fields "a.y"
I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:
```
FOR d in testdocs
  SORT d.a.y ASC
  LIMIT 1
  RETURN d
```

**It performs a full collection scan instead of using the skiplist index.** How can I make sure it uses the skiplist index for `a.y` while performing this query? (like the following example)

But, in a scenario where I create another index for the fields `x` and perform a slightly different query but with a top level attribute, 
```
FOR d in testdocs
  SORT d.x ASC
  LIMIT 1
  RETURN d
```
it uses the skiplist index for `x` as expected.

The issue can be reproduced using this dataset:

Create a collection testdocs,
 ```
FOR i in 1..1000000
      INSERT { x: i,
               a: { y: i}} INTO testdocs
```

**Comment by jsteemann** [comment]
Fixed in 3.0 (3.0.13), 3.1 (3.1.12) and devel.
