### ISSUE TITLE
Graph viewing from multiple nodes .

### ISSUE THREAD

**Issue by Pkoiralap** [arangodb/arangodb#2317]
Is there a way to view a graph starting from multiple nodes? Or a potential feature for the next version ?

**Comment by hkernbach** [comment]
Hello,

at the moment it is not possible, but we will implement that feature as soon as possible. I think it should be integrated within 1-2 weeks (devel).

**Comment by hkernbach** [comment]
You can now start your graph within the graph viewer from multiple nodes. To use that feature, just enter a space-seperated list of valid node id's (instead of a single id). This feature was added to devel and 3.1 branch. So it will be included in 3.2+ and 3.1.14+ releases.
