### ISSUE TITLE
issue with arangoimp --file : unexpected identifier

### ISSUE THREAD

**Issue by gdem123** [arangodb/arangodb#2318]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ x] 3.1.11
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [x ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [x ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.

The AQL query in question is:

**error when using arangimp**

**127.0.0.1:8529@EDW> arangoimp --file "data.csv" --type csv --collection "xxx_data"
JavaScript exception: SyntaxError: Unexpected identifier
!arangoimp --file "data.csv" --type csv --collection "xxx_data"
!            ^^^^
stacktrace: SyntaxError: Unexpected identifier 

arangoimp does not understand --file identifier**

The issue can be reproduced using this dataset: 

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click to ...
...

The following problem occurs: [Screenshot?] 
Instead I would be expecting: 

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

**Comment by jsteemann** [comment]
Looking at the invocation and the error message 
```
127.0.0.1:8529@EDW> arangoimp --file "data.csv" --type csv --collection "xxx_data"
JavaScript exception: SyntaxError: Unexpected identifier
!arangoimp --file "data.csv" --type csv --collection "xxx_data"
! ^^^^
stacktrace: SyntaxError: Unexpected identifier
```
it seems that you try to invoke *arangoimp* from inside the ArangoShell (*arangosh*). That will not work.
*arangosh* is a JavaScript shell, so you can run JavaScript commands and programs in it, for example:
```js
db._create("test");
db.test.insert([ { _key: "foo" }, { _key: "bar" }, { _key: "baz" } ]);
```
The line
```
arangoimp --file "data.csv" --type csv --collection "xxx_data"
```
is no valid JavaScript, thus the error message.

*arangoimp* is a separate binary that is shipped with ArangoDB in most distributions. The `arangoimp` invocation command should thus be entered and run in bash or another Unix shell (or even MS-DOS).
