### ISSUE TITLE
"Mostly-mass-storage" indexes

### ISSUE THREAD

**Issue by bobobo1618** [arangodb/arangodb#2319]
On the persisting indexes to disk issue, it was mentioned (https://github.com/arangodb/arangodb/issues/209#issuecomment-193838232) that "mostly-mass-storage" indexes would require future work.

I just wanted to create an issue for tracking and discussion of that feature, since I couldn't find one.

**Comment by dothebart** [comment]
This will be part of the upcomming arangodb 3.2 release. Please follow the release anouncements; I will close this issue now.
