### ISSUE TITLE
Try to make Cluster 

### ISSUE THREAD

**Issue by ahr12** [arangodb/arangodb#2322]
I install the arangodb-3.19 with source code on ubuntu 16.04.I am trying to make a cluster and I follow your docs but it's very confusing for beginners. I use the following command for cluster -

sudo /usr/local/sbin/arangod --server.endpoint tcp://0.0.0.0:5001 --agency.my-address tcp://172.30.1.33:5001 --server.authentication false --agency.activate true --agency.size 3 --agency.supervision true --database.directory agency

and I getting this error -  2017-02-23T06:34:42Z [1773] FATAL cannot convert username 'arangodb' to numeric uid

**Comment by kvahed** [comment]
Hi, I answered your last question yesterday here.

https://groups.google.com/forum/#!topic/arangodb/Uax1ouWlgxs

Please refrain from using 3.1.9. I had already mentioned that this particular version unfortunately has known cluster issues. Try the ubuntu package installer and start the cluster with Max's ArangoDBStarter: https://github.com/neunhoes/ArangoDBStarter. 

Cheers
