### ISSUE TITLE
Server lockup

### ISSUE THREAD

**Issue by normanuber** [arangodb/arangodb#2323]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ x ] 3.1.11
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ x ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

My setup is 3 nodes each with their agency, primary and coordinator. Each server has 128GB. The problem is that the server keeps locking up after a certain amount of time. The biggest collection I have is about 130k items. Replication factor is 2 and I tried shard sizes of 2 to 16 (to see if the problem was shard related).

Coordinator logs appear to have some errors like below:
2017-02-23T11:45:49Z [39143] ERROR {cluster} ClusterComm::performRequests: got no answer from shard:s6201182:/_db/app/_api/collection/s6201182/count with error 4
2017-02-23T11:45:49Z [39143] WARNING while trying to unregister query 3769648406: timeout, cluster node: 'PRMR-8b5e149c-1d46-45f8-a53a-8920f9d04771', shard: 's6201176', endpoint: 'tcp://arangodb:20002', error: 'timeout in cluster operation'

Primary log:
2017-02-23T07:22:31Z [39024] ERROR synchronizeOneShard: long call to syncCollection for shard s3100018 {"barrierId":"23126536","lastLogTick":"23106707","collections":[{"id":"2100009","name":"s3100018"}]} start time:  Thu Feb 23 2017 07:12:12 GMT+0000 (UTC) end time:  Thu Feb 23 2017 07:22:31 GMT+0000 (UTC)
2017-02-23T08:37:32Z [39024] WARNING retrying failed HTTP request for endpoint 'tcp://arangodb_server:20002' for replication applier in database '_system' - retries left: 1
2017-02-23T08:43:39Z [39024] ERROR failed to instantiate the query: Error message received from shard '' on cluster node 'CRDN-8042326a-6401-486c-b9e2-409bb6eeee54': query ID not found (while executing)
2017-02-23T09:05:09Z [39024] ERROR initializeCursor lead to an exception
2017-02-23T09:05:09Z [39024] ERROR initialize lead to an exception

Agencies appear to be fine. I don't think the coordinators are the problem. The Primary/DbServer is the one locking up especially since I see it pegging the CPU during the lockup times.

**Comment by neunhoef** [comment]
I have a theory to explain this. To confirm: Can you tell me what type of AQL queries are and have been running on that cluster? Are there any that run into an error or get aborted?
The delay of about 10 minutes on the primary server in the synchronizeOneShard function indicates that something waits for a part of a distributed query to be cleaned up (the timeout there is currently 10 min).
So, to find this bug, we need to find an AQL query that leaves parts of the distributed query engine hanging around on some DBserver.

**Comment by normanuber** [comment]
Common AQL query on the largest collection (130k documents):
LET device = document(devices, @bindVar1) FOR interface IN interfaces FILTER interface.device == @bindVar0 SORT interface.name RETURN interface

AQL queries on smaller collections
LET device = document(devices, @bindVar0) FOR peer IN bgp_peers FILTER device._id == peer._from SORT peer.peer_state RETURN peer

LET device = document(devices, @bindVar0) FOR ifaceLink IN interface_links FILTER ifaceLink._from == device._id RETURN ifaceLink

These are the only read operations executed in parallel from different clients. These are quick since there are indexes, but when lockups happen then they fail or take long

Write operations are using the updateDocument and insertDocument operations in the arangodb-java-driver, but I assume those are not AQL.

The write operations tend to result in ArangoDBException during this time with "Error 1457 - time
out in cluster operation"

**Comment by normanuber** [comment]
I went back to 3.1.7 and 3.1.0 to see if the problem manifests and yes it does.

**Comment by normanuber** [comment]
I tried to see if batching updates and creates would help alleviate issues with the servers. I started using arangodb-java-driver's updateDocuments and insertDocuments and now I get "Error 18 lock timeout" and 57 cpu load with 2395 cpu% as reported in htop by the primary.

<img width="1189" alt="screen shot 2017-02-24 at 9 07 34 am" src="https://cloud.githubusercontent.com/assets/14983089/23313213/a375b9ba-fa71-11e6-8e31-921ec51b5b61.png">

**Comment by normanuber** [comment]
I ovesubscribed the cpus with a higher thread count and lowered it since then. I also disabled returning new/old in the update/create options for the java driver. While the cpu has decreased dramatically since then.. still locking up. I'm giving up on my side. Hopefully new developments will take hold.

**Comment by normanuber** [comment]
Looks like a new version will be released that addresses this, thanks for all the help guys!

**Comment by neunhoef** [comment]
We aim to include the fix in 3.1.13, I will close the issue when that is published.

**Comment by dothebart** [comment]
ArangoDB 3.1.13 is available for download.
