### ISSUE TITLE
ArangoDB-Preview 3.2.alphas on Docker not available

### ISSUE THREAD

**Issue by frankmayer** [arangodb/arangodb#2328]
Hi!

I tried getting the preview of 3.2 alpha 2 on docker and followed these instructions:
https://www.arangodb.com/download-technical-preview/docker-preview/

Unfortunately I got: `docker: Error response from daemon: manifest for arangodb/arangodb-preview:3.2.alpha2 not found.`

So I went to the arangodb-preview repository's tags page: https://hub.docker.com/r/arangodb/arangodb-preview/tags/

Ooops, no v3.2 alphas there, and the latest is also 4 months old.

I will compile it from source, for now. However spinning up a docker container would have been more practical ;)

**Comment by dothebart** [comment]
You should be at least able to install the .debs - I'll have a look at the docker repo now.

**Comment by frankmayer** [comment]
Yes, I probably would have been, but I didn't want to risk breaking an existing packaged installation. I had the repo pulled and compiled from, a few days earlier, so updating and recompiling it was no big deal.

Nonetheless, Docker is easier to deal with, for test like that, so it would be great if it were up-to-date again. That is, the tagged versions plus a "nightly".

**Comment by dothebart** [comment]
the missing alpha docker image is now pushed to `arangodb/arangodb-preview:3.2.alpha2
` as anounced on the downloads page.
We plan to implement nightly package builds in the next weeks.

**Comment by frankmayer** [comment]
Great (especially the "nightly" package builds) :+1:
