### ISSUE TITLE
"Could not resolve host: apt.sw.be; Name or service not known"

### ISSUE THREAD

**Issue by torloneg** [arangodb/arangodb#2330]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ X] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [ X] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click to ...
...

The following problem occurs: [Screenshot?] 
Instead I would be expecting: 

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

[server@arangodb yum.repos.d]$ sudo yum -y install arangodb3-3.1.11
Loaded plugins: fastestmirror, langpacks
http://apt.sw.be/redhat/el7/en/x86_64/dag/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: apt.sw.be; Name or service not known"
Trying other mirror.
Loading mirror speeds from cached hostfile
 * arangodb: repoforge.mirror.wearetriple.com
No package arangodb3-3.1.11 available.
Error: Nothing to do
[torloneg@arangodb yum.repos.d]$

**Comment by baslr** [comment]
I also cant reach the domain `apt.sw.be` maybe they shut down? You have to use another mirror for your packages.

Installation instructions for fedora:
https://www.arangodb.com/download-major/fedora/

**Comment by dothebart** [comment]
please have a look at http://forums.fedoraforum.org/showthread.php?t=82053 - and as @dagwieers stated at https://github.com/repoforge/rpms/issues/375 - you should switch to other mirrors.

**Comment by dothebart** [comment]
Closing since its not our fault nor responsibility other parts of the internet disappeared.
