### ISSUE TITLE
When I am trying to install ArangoDB, I get a pop-up "Service waiting retry count reached"

### ISSUE THREAD

**Issue by itsarnie** [arangodb/arangodb#2333]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [yes ] 3.0

On this operating system:
- [yes- windows 7 ] Windows, version:

**Comment by dothebart** [comment]
Hi, did you install arangodb as a service? if yes, can you open the service controll manager, and do you see arangodb in that list? if yes, will it start / is it started?

**Comment by dothebart** [comment]
Hi, 
any news on this? or can we close this issue?

**Comment by ruifortes** [comment]
I just installed v3.2alpha3 on windows 7 and have the same problem.
Installed as service and the service is indeed there but it terminates unexpectedly when I start it.

**Comment by dothebart** [comment]
Hi, 
I've been working on the installer this week, can you retry with the nightly build?

https://www.arangodb.com/repositories/nightly/Windows7/x86_64/ArangoDB3-3.2.devel-1_win64.exe

Does it still happen, and if, what do you see in the windows event log?

**Comment by dothebart** [comment]
If it still appears, please comment. The output in the windows eventlog would be good to have. 
Closing for now.
