### ISSUE TITLE
Graph visualization

### ISSUE THREAD

**Issue by carolindohmen** [arangodb/arangodb#2335]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [x] 3.0
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [x] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is a web interface-related issue:
I'm using the web interface with this browser: Firefox 51.0.1   running on this OS: MacOS
- [ ] authentication is enabled?
- [ ] using the cluster?
- [x] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as root
3) use database [x]`_system` [ ] other: 
4) click to Graphs / "MySampleGraph"

The following problem occurs: 
_MySampleGraph_ consists out of an edge collection _Path_ connecting nodes out of a _Location_ collection. All in all there are 23 nodes and 44 edges.

When changing to the graph view, nodes and edges are left out of the visualization.

![graph1](https://cloud.githubusercontent.com/assets/16348965/23372835/8e92039c-fd1d-11e6-90e7-a470da8365d4.png)

Also every time I reload the page, another section of the graph is shown. 

![graph2](https://cloud.githubusercontent.com/assets/16348965/23372841/95068324-fd1d-11e6-90d4-908a479e4d41.png)

Now I'm not sure if the problem lies in the visualization or if it is my graph. I created it using an ArangoDB .Net client. The node and edge collections themselves are complete and correct.

**Comment by hkernbach** [comment]
> Also every time I reload the page, another section of the graph is shown.

If no user defined starting point is defined, a random starting point is set. That is the reason why your graph looks different on every reload. If you select a specific starting point (click a node & click the flag or open graph settings menu in the top right corner and enter a valid node id there), your graph will stay the same.

> When changing to the graph view, nodes and edges are left out of the visualization.

By default there is a limit of 250 visible nodes and a search depth of '2'. If you enter a higher search depth within the graph settings menu (top right corner) the complete graph could be shown (depends on the depth of your graph).

**Comment by hkernbach** [comment]
Closing this ticket now. If something is not clear, feel free to reopen the ticket.
