### ISSUE TITLE
Using rocksdb storage engine in Arangodb 3.2 alpha2

### ISSUE THREAD

**Issue by sajeevpr** [arangodb/arangodb#2336]
Dear team, 
   Can you please help me to use the rocksdb storage engine in 3.2 alpha 2

Regards,
Sajeev

**Comment by weinberger** [comment]
This alpha didn't include it yet.

**Comment by dothebart** [comment]
We plan to release more alphas; this feature will be added in a subsequent alpha. Please follow the release anouncements.

**Comment by iyoboflorence** [comment]
Looking forward to this.
Current memory usage is killing me :D 🗡
