### ISSUE TITLE
LIMIT operator on static arrays

### ISSUE THREAD

**Issue by ThomasWeiss** [arangodb/arangodb#2337]
I've found an issue with the LIMIT operator. Here is my playground (using 3.0.12):

    FOR i IN [1,2,3,4]
    FOR j IN APPEND([i],[5,6,7])
    RETURN j
returns

    [ 1, 5, 6, 7, 2, 5, 6, 7, 3, 5, 6, 7, 4, 5, 6, 7 ]
as expected.

    FOR i IN [1,2,3,4]
    FOR j IN APPEND([i],[5,6,7])
    LIMIT 2,4
    RETURN j
returns

    [ 6, 7, 2, 5 ]
still as expected

    FOR i IN [1,2,3,4]
    FOR j IN APPEND([i],[5,6,7])
    LIMIT 3,4
    RETURN j
returns

    [ 7, 2, 5, 6 ]
... everything is going well!

But then

    FOR i IN [1,2,3,4]
    FOR j IN APPEND([i],[5,6,7])
    LIMIT 4,4
    RETURN j
returns...

    []
where I expected to get

    [ 2, 5, 6, 7 ]

**Comment by jsteemann** [comment]
Fixed in 3.1.27

**Comment by jsteemann** [comment]
3.1.27 has been released and is available for download now:
https://www.arangodb.com/repositories/archive/arangodb31/
