### ISSUE TITLE
Request for some packaging help

### ISSUE THREAD

**Issue by NicoHood** [arangodb/arangodb#2343]
I try to package arangodb for Archlinux. The AUR package is outdated and also did a lot of things wrong/not the arch way.

I'd like to request some help to understand how to package arangodb optimal for archlinux. If it all wents well I can think of moving it to [community] as official package, as I am an Arch TU.

The best compile instructions I found were those:
https://docs.arangodb.com/3.1/cookbook/Compiling/Debian.html

What are the exact dependencies? I see some cmake and some python2. But for which part is python2 required and why not python3? The current PKGBUILD on aur tries to use a hacky way to use python2 for packaging. Is this required or can it be done with python3?

I found a [3rd party folder](https://github.com/arangodb/arangodb/tree/devel/3rdParty) in the repo. Since Arch tries to not use any static dependencies, is there a way to use the system libraries rather than the 3rd party ones? for which part are they used?

I've reduced the cmake command to what could make sense to me. Can anyone explain me if those options make sense? I'd rather not like to change the cc flags for example. What does SKIP_RPATH mean?:
```
 cmake -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_C_FLAGS="-O3 -fno-omit-frame-pointer" \
    -DCMAKE_CXX_FLAGS="-O3 -fno-omit-frame-pointer" \
    -DVARDIR=/var \
    -DETCDIR=/etc \
    -DCMAKE_INSTALL_DATADIR=/usr/share \
    -DCMAKE_SKIP_RPATH:BOOL=ON \
    ..
```

The aur package uses the ld gold. Any idea why?

How do i properly configure the tempfs file?

The AUR package has its own systemd service. Doesnt the repository has a proper one?
Edit: It seems to come with this systemd file which also provides some extra chmod stuff. But this is not something a systemd service should contain. This should be done in the packaging of the software.
https://github.com/arangodb/arangodb/blob/master/Installation/systemd/arangodb3.service.in

AUR package:
https://aur.archlinux.org/packages/arangodb/

You can also chat with me on IRC or [tox](contact.nicohood.de)

My current WIP PKGBUILD:

```bash
# Maintainer: NicoHood <archlinux {cat} nicohood {dog} de>
# PGP ID: 97312D5EB9D7AE7D0BD4307351DAE9B7C1AE9161
# Contributor: Mike Williamson <mike at korora dot ca>

pkgname=arangodb
pkgver=3.1.12
pkgrel=1
pkgdesc="A multi-model NoSQL database, combining key-value, document and graph data models."
arch=("i686" "x86_64")
url="https://www.arangodb.com/"
license=('APACHE')
depends=('openssl' 'systemd' 'curl' 'zlib')
makedepends=("cmake" "python2")
install=arangodb.install
source=("https://www.arangodb.com/repositories/Source/ArangoDB-${pkgver}.tar.bz2"
        "https://www.arangodb.com/repositories/Source/ArangoDB-${pkgver}.tar.bz2.asc"
        "arangodb.service"
        "arangodb-tmpfile.conf")
validpgpkeys=('CD8CB0F1E0AD5B52E93F41E7EA93F5E56E751E9B') # Frank Celler (ArangoDB Debian Repository) <info@arangodb.com>
sha512sums=('493be889b20f644823891e6c262e6a428fe6d3d447275e5da9313b300a1ab8ce35aefa58807b122e2b2490ef6f9130be35e17078ed7126fd343a0a413591288a'
            'SKIP'
            '90d832ac14b525e436a4256ee432b5d66750625a4e0adbd214c326526044f0139a6302fd5398ae2b2a7266a5536a990e1683736ae25829647a9ca9b48cb7be1f'
            '4dc6f0a18be2e759b89693a54f3376f52d8b646978c81f0f7069d8ed2c6d7123777a9709d000a5467a4f927b8befb5f472d933eb843db842cf853321a0ad5e7c')

build() {
    # TODO add python2 to path temporary?

    cd "${srcdir}/ArangoDB-$pkgver"
    mkdir -p build
    cd build
    cmake -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_DATADIR=/usr/share \
    -DBUILD_SHARED_LIBS:BOOL=ON \
    ..
    make
}

package() {
    cd "${srcdir}/ArangoDB-$pkgver/build"
    make DESTDIR="${pkgdir}" install


    # TODO how to properly package systemd and temp file?
    install -Dm644 arangodb-tmpfile.conf "${pkgdir}"/usr/lib/tmpfiles.d/arangodb.conf

    install -Dm644 "${srcdir}/arangodb.service ${pkgdir}/usr/lib/systemd/system/"
}
```

**Comment by dothebart** [comment]
Regarding the systemd unit file we spoke about in IRC yesterday; `cmake/ArangoDBInstall.cmake` tries to detect whether the host is systemd enabled:

  find_package(PkgConfig QUIET)
  pkg_check_modules(SYSTEMD systemd)

If that succeeds, the unit file is installed.

**Comment by dothebart** [comment]
Re build-dependencies:
- openssl is required
- jemalloc is advised
- python2 is required for V8/gyp

The 3rdparty folder is here since this contains the set of libraries that arango is using in integration tests; i.e. V8 is a fast moving target which may break api compatibility on a daily basis. Velocypack is built and maintained by the arangodb team, as is the linenoise-ng branch. Boost is primarily there since its harder to maintain it as an external dependency on elderly targets like centos6 or ubuntu 12 or windows. I don't know whether its possible to use a system boost - and whether a boost asio in the system may have other bugs than those with the libraries shipped. 

You may also have noted that V8 also brings third party utilities - namely icu. We also lean on that inside of arangodb aside of V8. 

Snappy & zlib will most probably picked from the system if you have them.

Yes, I know that on linux you usually could reliably find and detect libraries; Aside of that different versions on the host could bring you other bugs / behaviour than Unit/Integration tests on the arangodb CI linux is not our only target; Windows and Mac are much harder to prepare repeatable build environments.

**Comment by dothebart** [comment]
re RPATH - have a look at ftp://ftp.gnu.org/old-gnu/Manuals/ld-2.9.1/html_node/ld_3.html - it tends to be troublesome on some targets. It may work for you without.

**Comment by dothebart** [comment]
GOLD is used in favour of LD since LD uses _much_ more resources, and may eventually die from OOM.

**Comment by dothebart** [comment]
Would you also want to configure logrotate as noted in #2355 ?

**Comment by NicoHood** [comment]
I did not know about logrotate but it seems useful to me. Its on every system by default anyways.

**Comment by dothebart** [comment]
Ok, I think we can close this issue now. if you need any further assistance, let us know.
