### ISSUE TITLE
Uncaught The edge must have a string or number id

### ISSUE THREAD

**Issue by gamedev8** [arangodb/arangodb#2344]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [x] 3.1
- [ ] 3.2 pre-releases: ___
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [ ] Debian .deb
  - [x] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[x] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

### this is a web interface-related issue:
I'm using the web interface with this browser:  Google Chrome   running on this OS: Mint Linux

These are the steps to reproduce:
1) log in to your Web Interface
2) Run the following query

`return { _from: "a", _to: "b" }`

The following problem occurs:
1) You get a JavaScript error in the console "Uncaught The edge must have a string or number id"
2) "Query is operating ..." message does not go away, so the UI appears to be hung.

Instead I would be expecting: 
1) No errors in the console
2) UI should display the result of the query or display an error message

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

**Comment by baslr** [comment]
I can't reproduce it. Result with v3.1.12
```
[
  {
    "_from": "a",
    "_to": "b"
  }
]
```
also no error in DevTools console.

@gamedev8 which patch version do you run?

**Comment by gamedev8** [comment]
When I press info this is what I see
Current 3.1.0
Bugfix 3.1.12

**Comment by jsteemann** [comment]
If you are running 3.1.0, can you try upgrading to 3.1.12?
I remember some bugs related to have been fixed since 3.1.0, so I'd expect the issue to be resolved after the upgrade.

**Comment by dothebart** [comment]
Meanwhile 3.1.16 is available for download. Please upgrade, and reopen if this is still an issue.
