### ISSUE TITLE
Unexpected error response for duplicate users

### ISSUE THREAD

**Issue by ewoutp** [arangodb/arangodb#2346]
A call to HTTP API `POST /_api/user` with a duplicate user now returns:

```
{"error":true,"code":400,"errorNum":1702,"errorMessage":"duplicate user"}
```

I did expect a code of `409` to be in line with creating a database with a duplicate name.

**Comment by jsteemann** [comment]
> A call to HTTP API POST /_api/user with a duplicate user now returns:
I am slightly confused by the **now**. Does that mean the behavior has changed when comparing it to previous versions of ArangoDB, or does that mean that the behavior is simply inconsistent (returning HTTP 400 instead of HTTP 409 as in other parts).

**Comment by jsteemann** [comment]
Changed the return code from HTTP 400 to HTTP 409 in this case.

**Comment by dothebart** [comment]
ArangoDB 3.1.13 is available for download.
