### ISSUE TITLE
Response documentation of `PUT /_api/user/{user}/database/{dbname}` invalid

### ISSUE THREAD

**Issue by ewoutp** [arangodb/arangodb#2349]
In the swagger API docs of the above method, I find this under "Response messages"

```
201	
Returned if the user can be added by the server
```

- The status code `201` is not consistent with the code given in the example above it (`200`)
- The reason text does not seem to replace the function of the API call.

**Comment by dothebart** [comment]
ArangoDB 3.1.13 is available for download.
