### ISSUE TITLE
Graph visualisation: display issue when two vertexes are linked by multiple edges

### ISSUE THREAD

**Issue by gamedev8** [arangodb/arangodb#2351]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.1

### this is a web interface-related issue:
I'm using the web interface with this browser:   **Google Chrome**  running on this OS: **Mint Linux**

### Repro steps ###
- Create two vertices
- Create two edges
- Connect the vertices with the first edge
- Do the same for the second edge
- Go to the graph visualisation and enable edge names

The following problem occurs: [Screenshot?] 

With more than one edge linking two vertices the following is what u see when you go to the graph visualization with edge names enabled.

![a](https://cloud.githubusercontent.com/assets/1688049/23588949/0f4ca658-0193-11e7-8767-e86828a7d41a.png)

This is how Neo4J handles it
![b](https://cloud.githubusercontent.com/assets/1688049/23589093/50a0cd3a-0195-11e7-8dd0-2751b5bddc83.png)

**Comment by dothebart** [comment]
Hi, You can also do that with the arangodb webinterface; 
 - Open the Menu with the icon in the upper right
 - Choose Type -> Arrow to Curve
