### ISSUE TITLE
Feature Request: Support retrieval of graph definition in AQL

### ISSUE THREAD

**Issue by Calrain** [arangodb/arangodb#2354]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.1

### this is an AQL-related issue:
- [x] I'm using graph features

Feature request:
Add the ability to retrieve the definition of a graph in AQL.

Sometimes it's necessary to identify all edge and vertex collections linked to a graph and these commands don't seem to be available in AQL (or arangojs).

When querying a graph, there are times when you need to know what collections are bound to a graph.

Would it be possible to add a command like `GRAPH_SETTINGS` (example name) where it returned a JSON construct with configuration data about the named graph.

An example is:

```
    FOR settings IN GRAPH_SETTINGS('example_graph')
    RETURN settings 
````
and it would return something like:
```
    {
      "name": "example_graph",
      "edgeCollections": [
        {
          "edgeDefinitions": "edges_1",
          "fromCollections": [
            "docs_1"
          ],
          "toCollections": [
            "docs_1"
          ]
        },
        {
          "edgeDefinitions": "edges_2",
          "fromCollections": [
            "docs_2"
          ],
          "toCollections": [
            "docs_2"
          ]
        }
      ],
      "vertexCollections": [
        "extra_1",
        "extra_2"
      ]
    }
```

An example use would be to write a Foxx MicroService that found orphaned vertices in the scope of a graph. 

I know that by definition an orphan cannot exist in a graph (because it must have an edge), but in an application's context, it is possible for vertices to be disconnected from a graph that covers the scope of that vertex.

You could then perform an AQL query to fetch the graph settings, and then for each `edgeDefinition` it would be possible to find the vertices that are not represented in the edgeDefinition. This would identify orphaned vertices from the maximum scope of the graph.

Now, it may be that it's already possible to do this, but I can't find the command anywhere.

Thanks for your consideration.

**Comment by jsteemann** [comment]
I think it's already possible to query the `_graphs` collection, which should contain that information.
It stores the data in slightly different format, but the following AQL query should retrieve about the same information as required:
```
FOR doc IN _graphs 
  FILTER doc._key == @name 
  RETURN { 
    name: doc._key, 
    edgeDefinitions: doc.edgeDefinitions, 
    vertexCollections: doc.orphanCollections 
}
```
For one of the example graphs ("routeplanner") this query will return:
```js
{ 
  "name" : "routeplanner", 
  "edgeDefinitions" : [ 
    { 
      "collection" : "germanHighway", 
      "from" : [ 
        "germanCity" 
      ], 
      "to" : [ 
        "germanCity" 
      ] 
    }, 
    { 
      "collection" : "frenchHighway", 
      "from" : [ 
        "frenchCity" 
      ], 
      "to" : [ 
        "frenchCity" 
      ] 
    }, 
    { 
      "collection" : "internationalHighway", 
      "from" : [ 
        "frenchCity", 
        "germanCity" 
      ], 
      "to" : [ 
        "frenchCity", 
        "germanCity" 
      ] 
    } 
  ], 
  "vertexCollections" : [ ] 
}
```
You can then make use of that information in further AQL queries. I intentionally wrothe *further* AQL queries because currently it is not possible to dynamically access and use the collections retrieved by the query for modification in the same query. For example, the following is not supported:
```
FOR doc IN _graphs  /* ok */
  FILTER doc._key == @name  /* ok */
  FOR def IN doc.edgeDefinitions  /* ok */
    REMOVE 'someKey' IN def.collection /* dynamic collection access, not supported! */
```
All data modification operations in AQL need to know their collections in advance, when the query is compiled. So collection names must either be hard-coded into the query string, or be passed in via bind parameters.

**Comment by Calrain** [comment]
Ah, of course, the system databases. 

Thanks very much. 

I'll close the request.

I see your comment on the collections needing to be known at compile time, I understand why that is. 

Cheers
