### ISSUE TITLE
Missing logrotate file in Debian 8 and Centos 6

### ISSUE THREAD

**Issue by georgekaf** [arangodb/arangodb#2355]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [*] 3.1

On this operating system:
- [*] Linux 
  - [*] Centos .rpm
  - [*] Debian .deb

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

1) Installed arangodb 3.1.11 community edition
2) Upgraded after a few days to 3.1.12
3) After 3-4 days /var/log/arangodb3/arangodb.log was at 60 GB

No logrotate file in /etc/logrotate.d. I had to create my own for arangodb3. 

Is this a bug ? Am I supposed to take care of it on my own ?

**Comment by dothebart** [comment]
Hi, 
No, we didn't provide anything like that yet - thus arangod supports logfile re-opening when HUP'ed.

If you'd be willing to provide this via a PR into `Installation/logrotate/...` I will integrate this into the packages similar to `Installation/systemd/arangodb3.service.in`.

Please note that we are using a Apache 2 CLA for ArangoDB, which can be found here: https://www.arangodb.com/documents/cla.pdf - please sign, scan and email it to cla (at) arangodb.com alongside the PR.

**Comment by dothebart** [comment]
added configurations with db87c3e515bff8fc610c979d20f294ac05ff1b26 034deae93bfcb616b62dce9008cf6bffa9ec2bd1 - only did some testing with the SYSV-Init version. Lets see if it works out with the nightlies.
