### ISSUE TITLE
Obsolete return code docs for POST /_api/import#json

### ISSUE THREAD

**Issue by ewoutp** [arangodb/arangodb#2367]
Afaik the documentation for return code 501 (in the above HTTP request) is obsolete since you can call this on a cluster.

(If now says: `The server will respond with HTTP 501 if this API is called on a cluster coordinator.`)

**Comment by jsteemann** [comment]
Should be fixed now.

**Comment by dothebart** [comment]
3.2 alpha 4 containing this bugfix is available for download now.
