### ISSUE TITLE
HTTP Docs misstate availible options for graph functions

### ISSUE THREAD

**Issue by bananaoomarang** [arangodb/arangodb#2372]
Some of the parameters for `_absoluteCloseness` listed [here in the docs](https://docs.arangodb.com/3.1/Manual/Graphs/GeneralGraphs/Functions.html) don't seem to be available.

After attempting to use `egdeExamples` I took a look at [the relevant code](https://github.com/arangodb/arangodb/blob/devel/js/common/modules/%40arangodb/general-graph.js#L1250-L1285) and it doesn't seem to support these options:

`edgeCollectionRestriction`, `startVertexCollectionRestriction`, `endVertexCollectionRestriction`, `edgeExamples`.

I think this is because it's using the AQL `SHORTEST_PATH` syntax under the hood, making it hard (impossible?) to add these options. I would love to have a crack at a patch if there's a reasonable solution to this, otherwise we can just fix up the docs?

**Comment by mchacki** [comment]
Thank you for spotting it. I have updated the documentation as including this feature is on our roadmap bit will take a little bit to be available.
