### ISSUE TITLE
CORS guide / example

### ISSUE THREAD

**Issue by jakobrosenberg** [arangodb/arangodb#2375]
The FOXX documentation makes no mention of CORS. It would be nice with a guide or example on this topic.

Here's what I've gathered so far.

To send and receive cookies, the following line must be present in every route/controller
``res.headers['Access-Control-Allow-Credentials'] = true``

To send session id in header, add the following line to the login router.
``res.headers["access-control-expose-headers"] = 'etag, content-encoding, content-length, location, server, x-arango-errors, x-arango-async-id, X-Session-id'``

Being able to set a default header would go a long way, but I don't know if that's possible.

**Comment by mpv1989** [comment]
Thanks for pointing this out. We've implemented logic to set sane default values for these two headers in Foxx services in the devel branch. Starting with 3.2 CORS will "just work". You can still override the headers explicitly in the service response.

Here's the new documentation chapter for CORS in Foxx that should appear in the next documentation build:

> Cross Origin Resource Sharing (CORS)
> ====================================
> 
> To use CORS in your Foxx services you first need to [configure ArangoDB for CORS](https://docs.arangodb.com/3.1/HTTP/General/#cross-origin-resource-sharing-cors-requests). As of 3.2 Foxx will then automatically whitelist all response headers and cookies as they are used.
> 
> If you want more control over the whitelist or are using an older version of ArangoDB you can set the following response headers in your request handler:
> 
> * `access-control-expose-headers`: comma-separated list of response headers (defaults to a list of all headers the response is actually using)
> 
> * `access-control-allow-credentials`: `"false"` to forbid exposing cookies (Default: `"true"`)
>

**Comment by dothebart** [comment]
3.2 alpha 4 containing this bugfix is available for download now.  
The documentation containing this documentation is available via https://docs.arangodb.com/3.2/Manual/Foxx/Cors.html
