### ISSUE TITLE
ArangoDB doesn't start after a power failure!

### ISSUE THREAD

**Issue by p30arena** [arangodb/arangodb#2376]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.1
On this operating system:
- [x] Windows, version: 10

Last night the laptop that was running ArangoDB ran out of power, after connecting the power cord and starting the system up, we couldn't re-run arango.

this is the eoutput we get:

`
2017-03-15T12:45:54Z [2988] INFO ArangoDB 3.1.14 [win64] 64bit, using VPack 0.1.30, ICU 54.1, V8 5.0.71.39, OpenSSL 1.0.2a 19 Mar 2015

2017-03-15T12:45:54Z [2988] INFO using SSL options: SSL_OP_CIPHER_SERVER_PREFERENCE, SSL_OP_TLS_ROLLBACK_BUG

2017-03-15T12:45:54Z [2988] INFO Starting up with role SINGLE

2017-03-15T12:45:54Z [2988] INFO Authentication is turned on

2017-03-15T12:45:54Z [2988] INFO Authentication system only
`

I also tried the arango-dfdb but I get the same output.

**Comment by dothebart** [comment]
do you run it as a service? or from the commandline?

**Comment by p30arena** [comment]
@dothebart from the command line

**Comment by p30arena** [comment]
@dothebart this is what I get in windows logs when i try to run it as a service:



Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: arangod.exe
P2: 1.1.1.0
P3: 58c67af2
P4: arangod.exe
P5: 1.1.1.0
P6: 58c67af2
P7: c0000005
P8: 0000000000159179
P9: 
P10: 

Attached files:

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_arangod.exe_8b2705149ef69a4d17780af835f279a4757a337_ed432589_1b145204

Analysis symbol: 
Rechecking for solution: 0
Report Id: af37cdab-8173-4669-b212-3df86432d5b3
Report Status: 4100
Hashed bucket:

**Comment by p30arena** [comment]
@dothebart Report.wert Contains:


Version=1
EventType=APPCRASH
EventTime=131340575907196961
ReportType=2
Consent=1
ReportIdentifier=1130d7e5-0982-11e7-9bcb-28d2443d6463
IntegratorReportIdentifier=af37cdab-8173-4669-b212-3df86432d5b3
NsAppName=arangod.exe
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=arangod.exe
Sig[1].Name=Application Version
Sig[1].Value=1.1.1.0
Sig[2].Name=Application Timestamp
Sig[2].Value=58c67af2
Sig[3].Name=Fault Module Name
Sig[3].Value=arangod.exe
Sig[4].Name=Fault Module Version
Sig[4].Value=1.1.1.0
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=58c67af2
Sig[6].Name=Exception Code
Sig[6].Value=c0000005
Sig[7].Name=Exception Offset
Sig[7].Value=0000000000159179
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.10240.2.0.0.256.4
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=b75b
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=b75b84256649e3b31c439ba88c1240ba
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=d83b
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=d83b03b912d8017db86f710f7a8da748
UI[2]=D:\Program Files\ArangoDB3 3.1.14\usr\bin\arangod.exe
UI[5]=Check online for a solution (recommended)
UI[6]=Check for a solution later (recommended)
UI[7]=Close
UI[8]=ArangoDB - the multi-model database stopped working and was closed
UI[9]=A problem caused the application to stop working correctly. Windows will notify you if a solution is available.
UI[10]=&Close
LoadedModule[0]=D:\Program Files\ArangoDB3 3.1.14\usr\bin\arangod.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\system32\KERNEL32.DLL
LoadedModule[3]=C:\Windows\system32\KERNELBASE.dll
LoadedModule[4]=C:\Windows\system32\ADVAPI32.dll
LoadedModule[5]=C:\Windows\system32\msvcrt.dll
LoadedModule[6]=C:\Windows\system32\sechost.dll
LoadedModule[7]=C:\Windows\system32\RPCRT4.dll
LoadedModule[8]=C:\Windows\system32\SHLWAPI.dll
LoadedModule[9]=C:\Windows\system32\combase.dll
LoadedModule[10]=C:\Windows\system32\GDI32.dll
LoadedModule[11]=C:\Windows\system32\USER32.dll
LoadedModule[12]=C:\Windows\system32\WS2_32.dll
LoadedModule[13]=C:\Windows\system32\NSI.dll
LoadedModule[14]=D:\Program Files\ArangoDB3 3.1.14\usr\bin\LIBEAY32.dll
LoadedModule[15]=D:\Program Files\ArangoDB3 3.1.14\usr\bin\SSLEAY32.dll
LoadedModule[16]=C:\Windows\SYSTEM32\WINMM.dll
LoadedModule[17]=C:\Windows\SYSTEM32\MSWSOCK.dll
LoadedModule[18]=D:\Program Files\ArangoDB3 3.1.14\usr\bin\VCRUNTIME140.dll
LoadedModule[19]=C:\Windows\SYSTEM32\WINMMBASE.dll
LoadedModule[20]=C:\Windows\system32\cfgmgr32.dll
LoadedModule[21]=C:\Windows\SYSTEM32\ucrtbase.dll
LoadedModule[22]=C:\Windows\SYSTEM32\DEVOBJ.dll
LoadedModule[23]=C:\Windows\system32\kernel.appcore.dll
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=ArangoDB - the multi-model database
AppPath=D:\Program Files\ArangoDB3 3.1.14\usr\bin\arangod.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=A6DF77E21014518916D4DA71293ABFF7

**Comment by dothebart** [comment]
can you try whether it aborts on error as described here (using procdump) ?
https://github.com/arangodb/arangodb/blob/devel/README_maintainers.md#windows-debugging

**Comment by p30arena** [comment]
@dothebart 

[17:33:20] Exception: C0000005.ACCESS_VIOLATION
[17:33:20] The process has exited.
[17:33:20] Dump count not reached.

**Comment by dothebart** [comment]
hm :-/ ACCESS_VIOLATION usually should exactly not make it tell `Dump count not reached.` but write a dump file

**Comment by p30arena** [comment]
@dothebart 

I changed some switches, -e 1, now I have a 400MB Dump File

**Comment by dothebart** [comment]
ok, it should zip pretty well, can you provide it somewhere for download?

**Comment by p30arena** [comment]
@dothebart 

https://ufile.io/da27f1

**Comment by dothebart** [comment]
OK, failing to construct the RocksDBIndexFeature - seems to be some initialization sequence issue @jsteemann 
RocksDBIndex.cpp:211

**Comment by p30arena** [comment]
@dothebart Thanks, I'll mention the WinDBG .ecxr here

0:000> .ecxr
rax=0000000000000000 rbx=0000009744b28060 rcx=0000000000000000
rdx=0000000000000000 rsi=0000000000089bc3 rdi=0000009727a7bbf8
rip=00007ff6f26f9179 rsp=0000009727a7b9f0 rbp=0000009727a7bb40
 r8=0000009744b30670  r9=0000000000000000 r10=0000000000000000
r11=0000000000000000 r12=0000000000000000 r13=0000000000000008
r14=0000009744b3ae70 r15=0000000000000001
iopl=0         nv up ei pl nz na pe nc
cs=0033  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010202
arangod!arangodb::RocksDBFeature::db [inlined in arangod!arangodb::RocksDBIndex::RocksDBIndex+0x39]:
00007ff6`f26f9179 488b88f0000000  mov     rcx,qword ptr [rax+0F0h] ds:00000000`000000f0=????????????????

**Comment by dothebart** [comment]
thanks, yes, its a NULL-pointer to an object, and the object member is at 0xF0h I guess.

**Comment by p30arena** [comment]
@jsteemann How can I test the fix you've committed? should I compile the source code or you will release a new build?

**Comment by carr123** [comment]
i strongly recommend you to switch to Rust or Go as the underling programming language of Arangodb.
C++ is far too hard to manipulate in a big project.

**Comment by dothebart** [comment]
we may also try to port it to an abacus, it will be most probably more resistant to power outages then.

**Comment by jsteemann** [comment]
Reopening this, as it is not officially resolved.

**Comment by p30arena** [comment]
@jsteemann please give me a new release to test the fix, I tried to compile it myself, but its really time consuming on a 2011 Mac Book Pro!

**Comment by dothebart** [comment]
I've uploaded a zip package containing the fix to: https://www.arangodb.com/repositories/ArangoDB3-3.1.14-1_win64.zip
Please test it, so we can see whether its fixed for 3.1.15

**Comment by p30arena** [comment]
@dothebart The Fix Worked! Thanks ;)





D:\Program Files\ArangoDB3-3.1.14-1_win64>usr\bin\arangod.exe
2017-03-16T16:06:27Z [4476] INFO ArangoDB 3.1.14 [win64] 64bit, using VPack 0.1.30, ICU 54.1, V8 5.0.71.39, OpenSSL 1.0.2a 19 Mar 2015
2017-03-16T16:06:27Z [4476] INFO using SSL options: SSL_OP_CIPHER_SERVER_PREFERENCE, SSL_OP_TLS_ROLLBACK_BUG
2017-03-16T16:06:27Z [4476] INFO Starting up with role SINGLE
2017-03-16T16:06:27Z [4476] INFO Authentication is turned on
2017-03-16T16:06:27Z [4476] INFO Authentication system only
2017-03-16T16:06:28Z [4476] INFO running WAL recovery (1 logfiles)
2017-03-16T16:06:28Z [4476] INFO replaying WAL logfile 'D:\Program Files\ArangoDB3-3.1.14-1_win64\var/lib/arangodb3\journals\logfile-489161.db' (1 of 1)
2017-03-16T16:06:28Z [4476] INFO WAL recovery finished successfully
2017-03-16T16:06:29Z [4476] INFO JavaScript using startup 'D:\Program Files\ArangoDB3-3.1.14-1_win64\/usr/share/arangodb3/js', application 'D:\Program Files\ArangoDB3-3.1.14-1_win64\var/lib/arangodb3-apps'
2017-03-16T16:06:32Z [4476] INFO using endpoint 'http+tcp://127.0.0.1:8529' for non-encrypted requests
2017-03-16T16:06:35Z [4476] INFO ArangoDB (version 3.1.14 [win64]) is ready for business. Have fun!

**Comment by dothebart** [comment]
ArangoDB 3.1.15 is available for download now.
