### ISSUE TITLE
Dump graph with all collections and restore to other arangodb

### ISSUE THREAD

**Issue by ahr12** [arangodb/arangodb#2378]
Hii,
I am using arangodb-3.1.11 on ubuntu 16.04.
I want to backup & restore the graph data. so I use the following command - 
arangodump --dump-data false --include-system-collections true --server.username root --server.database mtest --output-directory "dump"
arangorestore --include-system-collections true --server.username root --server.database my --input-directory "dump"
It's retore the all collection data of graph but create the graph

**Comment by ahr12** [comment]
Hello Sir,
I need the graph data restore into new database. I am waiting for your response.

**Comment by dothebart** [comment]
is there a reason why you specify `--dump-data false` ? since if I don't specify that I can dump and re-import graphs.

**Comment by ahr12** [comment]
Thanks
