### ISSUE TITLE
ERROR error message:    lock timeout

### ISSUE THREAD

**Issue by wangfengfighting** [arangodb/arangodb#2380]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2 pre-releases: ___
- [ *] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
- [ *] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
- [ *] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [ *] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

### this is a arangoimp issue:

 I download the source code from github, and checkout v3.1.14, then compiled  the ArangoDB on Gentoo, Everything was OK.
when I use ArangoDBv3.1.14 with `arangoimp` to import a csv file,the process stop at 30% of input file, on the other hand, return `ERROR error message:    lock timeout` my RAM is `128GB`and it consumed `110GB`  at 30% of input file, I remember some one of arangodb team has told me that when import a file which is bigger than RAM , the process would be completed because of `Memory-Mapped-File`
but it seems not work right?
Even if the import process has stopped, the ArangoDB was still running, there are screenshots  as following:
![image](https://cloud.githubusercontent.com/assets/10260566/24032682/3508fdf2-0b24-11e7-89ea-6d55f4cda231.png)
![image](https://cloud.githubusercontent.com/assets/10260566/24032689/3b4c1352-0b24-11e7-96f7-390d81b13d6d.png)

I thought #2323 ( https://github.com/arangodb/arangodb/issues/2323 ) may relatedto  this issue

**Comment by dothebart** [comment]
Do you also use AWS machines as in #2278 ?

**Comment by wangfengfighting** [comment]
@dothebart no, I use  local physical machine and OS is Gentoo

**Comment by wangfengfighting** [comment]
@dothebart do I need to try 3.0.x or 3.2-alpha as @sdy7 did in #2278 ?

**Comment by dothebart** [comment]
Hi, 
We have adjusted some parameters with the collection cache with ArangoDB 3.1.16 which exactly showed up when you have much memory. 
I have now been able to flawlessly import a CSV in the double size of my RAM. 
Can you revalidate whether this fixes your problem too?

**Comment by dothebart** [comment]
I will close this now after a month of inactivity and two releases.
