### ISSUE TITLE
Foxx preflight requests returns Access-Control-Allow-Credentials: false

### ISSUE THREAD

**Issue by jakobrosenberg** [arangodb/arangodb#2383]
Foxx v.3.1.12 (Docker)

Is there a way to set Access-Control-Allow-Credentials to true in preflights?

I can GET and POST no problem, but on DELETE, chrome sends a preflight requests OPTIONS request in which Access-Control-Allow-Credentials is set to false.

**Comment by mpv1989** [comment]
We've added an explanatory paragraph to the CORS section of the HTTP documentation that addresses this:

> **Note**: in order to ensure that ArangoDB will respond with the correct *access-control-allow-credentials* header you'll need to make sure to tell the browser to use credentials:
>
> * When using the Fetch API you need to set the [`credentials` option to `include`](https://fetch.spec.whatwg.org/#cors-protocol-and-credentials).
>
> * When using `XMLHttpRequest` you need to set the [`withCredentials` option to `true`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials).

This should solve the problem.

**Comment by pluma** [comment]
Yes. The response header will look that way if you don't explicitly tell the browser to include credentials. We've updated the documentation with examples for doing this with XHR and Fetch.

**Comment by pluma** [comment]
an you check the network tab in your browser's developer tools and check whether the browser sets the correct request header?

**Comment by pluma** [comment]
I'm investigating.

**Comment by pluma** [comment]
@jakobrosenberg Sorry for the confusion. You're right that the header should be true without the client having to do anything special (the credentials mode does not affect the preflight request).

Can you confirm that you have [configured ArangoDB for CORS](https://docs.arangodb.com/3.1/HTTP/General/#cross-origin-resource-sharing-cors-requests); specifically that you have set the `http.trusted-origin` option to the origins you want to whitelist (or `"*"`)?

**Comment by jakobrosenberg** [comment]
I rewrote authentication on my client to set cookies manually. When I have time I'll try with credentials again. :)

**Comment by pluma** [comment]
We've updated the documentation again to clarify how the credentials header behaves. If you did use the `trusted-origin` option with the correct value but still experience this problem, we would like to investigate this further. However the `trusted-origin` option has tripped up users in the past.

**Comment by jakobrosenberg** [comment]
I'm having a look at it now. How do I set trusted-origin when using ArangoDB in docker?

**Comment by pluma** [comment]
@jakobrosenberg I think you should be able to supply the `--http.trusted-origin` option like you would from the command line: https://hub.docker.com/r/arangodb/arangodb/ gives an example using `--help`.

**Comment by dothebart** [comment]
3.2 alpha 4 containing this bugfix is available for download now.  The Documentation for this issue is available via https://docs.arangodb.com/3.2/Manual/Foxx/Cors.html
