### ISSUE TITLE
cluster authentication arangodb3.1.14 service problem

### ISSUE THREAD

**Issue by hellomanjack** [arangodb/arangodb#2384]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ 1] 3.1
- [ ] 3.2 pre-releases: ___
- [ ] self-compiled devel branch

On this operating system:
- [1 ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ 1] own infrastructure
- [ 1] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ 1] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [1 ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [1 ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) Install arangodb3.1.14 with dcos 1.8. And the state become healthy.
2) Install a service from local zip on "SERVICES" tab.
3) Kill a coordinator. And wait the arangodb3 to reschedule to add a new coordinator.
4) open the endpoint according to the new coordinator.  The service previously installed from zip doesn't work properly.

The following problem occurs: [Screenshot?] 
Instead I would be expecting: 

![image](https://cloud.githubusercontent.com/assets/25783698/24141965/14c61f18-0e60-11e7-8137-fd2e7861633f.png)

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

**Comment by hellomanjack** [comment]
@pluma it is already comes to 3.1.17 but it hasn't been solved yet. When a new coordinator comes up, services installed on the cluster will have to reinstall in the new coordinator.

**Comment by pluma** [comment]
@hellomanjack As a part of our effort to make ArangoDB more resilient in the cluster for the 3.2 release we're in the process of overhauling the entire logic for distributing services and initialising/self-healing services on the coordinators. Several versions of the scenario you describe are part of our new test plan for Foxx.

I can confirm this issue persists in 3.1 but it will be addressed with the upcoming 3.2 release.

**Comment by pluma** [comment]
Will be part of the next 3.2 release.

**Comment by hellomanjack** [comment]
well done!Thanks!
