### ISSUE TITLE
"Unable to read-lock collection" error while attempting to remove edge using AQL in a cluster

### ISSUE THREAD

**Issue by jeeveeyes** [arangodb/arangodb#2386]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [x] 3.1
- [x] 3.2 pre-releases: ___
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [X] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [X] web interface with this browser: Chrome    running on this OS: OSX
- [ ] arangosh
- [X] this Driver: python-arango

===

We are seeing this error "Error message received from shard 's10304482' on cluster node 'PRMR-89b40669-ad29-4eb7-ad61-3ee29c210cd0': unable to read-lock collection %s (while executing)"
upond executing below AQL.

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

```
FOR vert in @@vertex_collection
         FILTER vert._key == @key
         FOR v,e in INBOUND vert @@edge_collection
         REMOVE e in @@edge_collection
```

===
Output from AQL explain - 
```
Query string:
 FOR vert in @@vertex_collection
          FILTER vert._key == @key
          FOR v,e in INBOUND vert @@edge_collection
          REMOVE e in @@edge_collection

Execution plan:
 Id   NodeType         Site       Est.   Comment
  1   SingletonNode    DBS           1   * ROOT
  7   IndexNode        DBS           1     - FOR vert IN XYZ   /* primary index scan */
 14   RemoteNode       COOR          1       - REMOTE
 15   GatherNode       COOR          1       - GATHER 
  5   TraversalNode    COOR         10       - FOR v  /* vertex */, e  /* edge */ IN 1..1  /* min..maxPathDepth */ INBOUND vert /* startnode */  ABC_TO_XYZ
  8   DistributeNode   COOR         10       - DISTRIBUTE
  9   RemoteNode       DBS          10       - REMOTE
  6   RemoveNode       DBS           0       - REMOVE e IN ABC_TO_XYZ
 10   RemoteNode       COOR          0       - REMOTE
 11   GatherNode       COOR          0       - GATHER 

Indexes used:
 By   Type      Collection   Unique   Sparse   Selectivity   Fields               Ranges
  7   primary   XYZ          true     false            n/a   [ `_key` ]           (vert.`_key` == 1234)
  5   edge      ABC_TO_XYZ   false    false            n/a   [ `_from`, `_to` ]   base INBOUND

Traversals on graphs:
 Id   Depth   Vertex collections   Edge collections   Options                                   Filter conditions
  5   1..1                         ABC_TO_XYZ         uniqueVertices: none, uniqueEdges: path   

Optimization rules applied:
 Id   RuleName
  1   remove-data-modification-out-variables
  2   use-indexes
  3   remove-filter-covered-by-index
  4   remove-unnecessary-calculations-2
  5   distribute-in-cluster
  6   scatter-in-cluster
  7   remove-unnecessary-remote-scatter

Write query options:
 Option                   Value
 ignoreErrors             false
 waitForSync              false
 nullMeansRemove          false
 mergeObjects             true
 ignoreDocumentNotFound   false
 readCompleteInput        true
 useIsRestore             false
 consultAqlWriteFilter    false
```
===

* Used both 3.1.14 and 3.2 Alpha2 .debs on Ubuntu 14.04 VMs and getting same error on them.
* Cluster is 3 Node VM cluster using the  arangoDBStarter 0.5.0 tool with all 3 nodes running DBServer and coordinator.
* Issue happens whether we use the AQL query editor or send the same query via python-arango 3.4.0 driver.
 * Issue *does not* happen when we directly delete the edge inside the collection through the UI delete button.

The issue can be reproduced using the below steps:

![capturfiles-mar-22-2017_12 23 32](https://cloud.githubusercontent.com/assets/2874853/24187078/654f8324-0f01-11e7-8893-94740f1692f6.png)
![capturfiles-mar-22-2017_12 24 29](https://cloud.githubusercontent.com/assets/2874853/24187082/68a9a414-0f01-11e7-9c45-aa6604bc7bdd.png)
![capturfiles-mar-22-2017_12 25 41](https://cloud.githubusercontent.com/assets/2874853/24187104/81dc5b7a-0f01-11e7-9022-aa06054bb0b0.png)
![capturfiles-mar-22-2017_12 26 08](https://cloud.githubusercontent.com/assets/2874853/24187107/836c06c0-0f01-11e7-8033-f67290e3bb47.png)
![capturfiles-mar-22-2017_12 27 31](https://cloud.githubusercontent.com/assets/2874853/24187110/8533c362-0f01-11e7-8de2-ef4842445818.png)
![capturfiles-mar-22-2017_12 28 16](https://cloud.githubusercontent.com/assets/2874853/24187113/896d52ea-0f01-11e7-8b4c-f7706cc94526.png)
![capturfiles-mar-22-2017_12 29 22](https://cloud.githubusercontent.com/assets/2874853/24187116/8d55c838-0f01-11e7-94b5-60003ed1d84f.png)
![capturfiles-mar-22-2017_12 30 08](https://cloud.githubusercontent.com/assets/2874853/24187120/938a3f18-0f01-11e7-9cd7-80e9bda18bb5.png)
![capturfiles-mar-22-2017_12 33 53](https://cloud.githubusercontent.com/assets/2874853/24187130/96e5c7fe-0f01-11e7-8f54-df6da56011d5.png)

**Comment by mchacki** [comment]
Hi @jeeveeyes 
The reason for this behavior is the following:
In cluster case all vertex collections in use have to be known by the query.
You can add them by adding `WITH <collectionName>` at the beginning of the query.

There should be an error message stating exactly this, which however is lost at some stage in your query, this is under investigation now.

So correct error message should be:
`ArangoError: Collection not known to Traversal XYZ please add 'WITH XYZ' as the first line in your AQL`

Unless this is fixed you can simply add the WITH statement and the query will succeed:

```
WITH ABC
FOR vert in @@vertex_collection
  FILTER vert._key == @key
  FOR v, e IN INBOUND vert @@edge_collection
    REMOVE e IN @@edge_collection
```

Sorry for the inconvenience

**Comment by jeeveeyes** [comment]
The issue is solved when we use the "WITH" keyword as suggested.
