### ISSUE TITLE
web client UI improvements for displaying collections

### ISSUE THREAD

**Issue by grexe** [arangodb/arangodb#2388]
Using ArangoDB 3.1.12, I find the web UI very pleasing and refreshingly simplistic, but sometimes a bit too basic.
E.g., the collections view is really just a line-by-line dump of the JSON, which makes it hard to read and work with.
I'd love to see a real table view with the attributes as columns, much like every other DB viewer displays it,-) 
Any chance to get this in with one of the next web client updates?

**Comment by grexe** [comment]
PS: actually there is already a table view but well hidden and only visible in the Query page for filtered results... would be great to reuse that functionality and add a display option to always show records as a table with fields as columns...

**Comment by hkernbach** [comment]
> E.g., the collections view is really just a line-by-line dump of the JSON, which makes it hard to read and work with.

Do you really mean the collections view (where collections were displayed: route #collections)? Or do you mean the view of documents inside a collection (route: #collection/<coll_name>/documents/1)?

**Comment by grexe** [comment]
sorry for not being more precise (and overlooking your question;) - I mean the view of documents inside a collection.
Normally, any database interface would offer a table like display, which would also allow for more natural filtering and sorting by clicking on the table header for sorting, or an icon for filtering.

**Comment by dothebart** [comment]
This can now be done by clicking the funnel-icon in the upper right of the collection view.
Once you click it, you can add filter conditions for json attributes.
