### ISSUE TITLE
Web Interface query statistics presentation bug

### ISSUE THREAD

**Issue by wshayes** [arangodb/arangodb#2389]
## Problem

Graph Traversal query - shows total query time
https://www.evernote.com/l/AALmMAlUUcBBXqEWys_9pLAKKzM_ajJlukQ

Shortest Path query - total query time presented is 0 
https://www.evernote.com/l/AAIv0Uxu6G9BiqD2fwGae7fCxx6cu3Fhvdg

Obviously not a high priority bug, just adding the issue so you know about it.

## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [X] 3.1
- [ ] 3.2 pre-releases: ___
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [X] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

**Comment by hkernbach** [comment]
Thanks for the report. Indeed it was a bit confusing showing miliseconds > 0 and then seconds = 0. Changed the behaviour to automatically detect the correct unit.

**Comment by dothebart** [comment]
ArangoDB 3.1.17 is available for download now.
