### ISSUE TITLE
killed components are treated as ongoing processes in the arangodb cluster

### ISSUE THREAD

**Issue by hellomanjack** [arangodb/arangodb#2391]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ 1] 3.1
- [ ] 3.2 pre-releases: ___
- [ ] self-compiled devel branch

On this operating system:
- [1 ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [1 ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ 1] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [1 ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [1 ] using the cluster?
- [1 ] _system database?

These are the steps to reproduce:
1) Install arangodb 3.1.15 with dcos 1.8.8 . 
2) Make web pressure test. A coordinator is killed owning to machine out of memory.
3) The component becomes red in the "NODES" tab. However the "Task ID" according to the killed coordinator in the DCOS gets lost. 
4) The arangodb frame continue to talk to the lost component. Certainly it gets errors. And the lost tasks
don't come up again.

The following problem occurs: [Screenshot?] 
Instead I would be expecting: 
![image](https://cloud.githubusercontent.com/assets/25783698/24230953/d28f4e68-0fbc-11e7-9faf-a04b7c966dd5.png)
![image](https://cloud.githubusercontent.com/assets/25783698/24230992/03d80f64-0fbd-11e7-853a-f1e9d15f2d86.png)
![image](https://cloud.githubusercontent.com/assets/25783698/24231064/5cf07d52-0fbd-11e7-9845-f3729053ed08.png)

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

**Comment by m0ppers** [comment]
This seems to be a valid bug. We will try to look into this issue next week. A quick fix could be to simply kill the framework. It should then look at the current state and resume operation.

**Comment by hellomanjack** [comment]
@m0ppers Ok， i will do it next time if it happens again. Thanks!

**Comment by dothebart** [comment]
Ok, we did lots of cluster related bugfixing with ArangoDB 3.2.8 - I will close this as solved now.
