### ISSUE TITLE
Arangodb takes too much memory 

### ISSUE THREAD

**Issue by ahr12** [arangodb/arangodb#2394]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- 3.1.11 
-Ubuntu 16.04
I create a cluster of 4 AWS machines (with 8 GB RAM each) use the Arangod cluster tool.Every time when I execute my Java code on Cluster after some time Arangodb takes too much ram and the master machine goes to hang and my code stopped. I need to insert ~30M nodes and ~35M edge.How can i create a graph with efficient way?

**Comment by dothebart** [comment]
This could be related to #2278 - especially the link to 
https://aws.amazon.com/blogs/aws/new-burst-balance-metric-for-ec2s-general-purpose-ssd-gp2-volumes/
