### ISSUE TITLE
arangoimp should try to autodetect file type

### ISSUE THREAD

**Issue by dothebart** [arangodb/arangodb#2395]
when arangoimp is called with `--file test.csv` it will treat it as json anyways, unless one specifies `--type csv`. 
A file-extension detection should be added.

**Comment by jsteemann** [comment]
Already there in devel:
use `--type auto` to enable the auto detection.
It's not the default at the moment, but it can easily be made the default by changing this line:
https://github.com/arangodb/arangodb/blob/devel/arangosh/Import/ImportFeature.cpp#L54

**Comment by jsteemann** [comment]
We decided to not make `--type auto` a default for arangoimp.
The default file type for arangoimp remains `json`, but automatic type detection can be enabled by either invoking it with `--type auto` option or by putting that option in a local `arangoimp.conf` file.

**Comment by dothebart** [comment]
We're pleased to anounce that ArangoDB 3.2 containing this is now available for download - Closing.
