### ISSUE TITLE
Code not work when master goes to down

### ISSUE THREAD

**Issue by ahr12** [arangodb/arangodb#2396]
## my environment running ArangoDB
ArangoDB - 3.1.11 (Install using source code)
ubuntu- 16.04

I created a cluster of 4 AWS machine (8GB RAM, 60 GB Memory each). I executed the Java code on this cluster but when the master machine goes to down, My program also stopped. I expect that if the master doesn't work then another machine take care of this. but it's not happened.

**Comment by mpv1989** [comment]
Did you added all of your coordinators as hosts to the java driver instance?
The driver can only use other coordinators as fallback hosts if they are known by it.

`ArangoDB arango = new ArangoDB.Builder().host("<coord1-ip>", <coord1-port>).host("<coord2-ip>", <coord2-port>).build();`

**Comment by ahr12** [comment]
Hello,
I am using 3.1 Java driver and following configuration  -
ArangoConfigure configure = new ArangoConfigure();
ArangoHost hostObj = new ArangoHost(host, port);   
configure.setArangoHost(hostObj);
configure.setUser(user);
configure.setPassword(pass);
configure.init();
ArangoDriver arangoDriver = new ArangoDriver(configure);
how to add more hosts and ports for this?

**Comment by mpv1989** [comment]
`configure.addFallbackArangoHost(new ArangoHost(host2,port2,))`

**Comment by ahr12** [comment]
Thanks
