### ISSUE TITLE
crypto.hmac results compared to Node.js

### ISSUE THREAD

**Issue by ThomasWeiss** [arangodb/arangodb#2399]
I have to compute a SHA256 HMAC signature in a Foxx app. Having troubles to make this work, I realized that the signature generated is different from the one generated in some Node.js example. Here is how I reproduce it:

In Node.js:

    const crypto = require('crypto');
    
    var stringToSign = "ArangoDB rocks";
    var key = "C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==";
    
    var decodedKey = new Buffer(key, 'base64');
    var signature = crypto.createHmac('sha256', decodedKey).update(stringToSign).digest('base64');
    
    console.log(signature);
Result: `40dcSbJhIteAkErVCtx7TSS0EZfebemI31OWGf1o7WE=`

In a Foxx script running on 3.0.10:

    const crypto = require('@arangodb/crypto');
    
    var stringToSign = "ArangoDB rocks";
    var key = "C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==";
    
    var decodedKey = new Buffer(key, 'base64').toString('hex');
    var signature = new Buffer(crypto.hmac(decodedKey, stringToSign, 'SHA256'), 'hex').toString('base64');
    
    module.exports = signature;
Result: `uKxkW9FPKnpA2EShnmDC9QJjAoRw5wH/Z0ANzOh5ZEM=`

Is there any issue in the way I'm using the `crypto` library? Or my transformation of strings from/to Base64?

Thanks in advance for your help!

**Comment by ThomasWeiss** [comment]
Actually I'm thinking that this may come from the fact that `crypto.hmac` doesn't treat inputs strings as `hex` but as plain `utf-8` strings, which is somewhat related to #1986 and #1993. I will test that using `Buffer`s on 3.1 and let you know.

**Comment by ThomasWeiss** [comment]
Confirmed that we get the expected result by using the key as a `Buffer` in 3.1.15, sorry for that...

**Comment by ameznfc** [comment]
tu peux me donne un coup de main pour déchiffré ce la 

const gameHash = hashChain.pop()
const hmac = createHmac('sha256', gameHash);
// blockHash هو تجزئة كتلة البيتكوين 631,111
hmac.update(blockHash);
const hex = hmac.digest('hex').substr(0, 8);
const int = parseInt(hex, 16);
نتيجة ثابتة = Math.max(1, (2 ** 32 / (int + 1)) * (1 - 0.02))
