### ISSUE TITLE
ArangoDB Shard Distribution View showing weird data?

### ISSUE THREAD

**Issue by normanuber** [arangodb/arangodb#2402]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ X ] 3.1.16

On this operating system:
- [ X ] Linux 
  - [ X ] Debian .deb

Screenshot below shows what I am seeing.

<img width="1476" alt="screen shot 2017-03-28 at 12 24 50 pm" src="https://cloud.githubusercontent.com/assets/14983089/24423382/980cd14a-13b1-11e7-91d3-48d8167323b4.png">

I have a replication factor of 2, so my expectation is that shards will be on 2 servers.. not 3 or 4 servers... any idea of how it could get to this state? or is this a bug?

Assuming what is being shown is true, I suppose restarts to the DBserver could cause this, but if a DBServer dies for some time does it mean that replication should use the next available DBServer to replicate to?

**Comment by fceller** [comment]
@hkernbach could that be a refresh bug in the front-end?

**Comment by fceller** [comment]
It will be fixed in the next 3.1 release.

**Comment by dothebart** [comment]
ArangoDB 3.1.17 is available for download now.

**Comment by normanuber** [comment]
Given that I did upgrade to 3.1.17 and the shards showed 2 followers given that replication factor was 2. I am doubting this is a front-end issue. I wiped my databases to start anew and will see if it occurs again.

**Comment by fceller** [comment]
@normanuber I'm pretty sure it is not a front-end issue. The fix didn't make into 3.1.17. It will be in 3.1.18.

**Comment by fceller** [comment]
@dothebart I've updated the milestone accordingly

**Comment by dothebart** [comment]
3.1.18 including this fix is now available for download.
