### ISSUE TITLE
High memory usage after upgrading from 3.1.15 to 3.1.16 on Ubuntu 16.04

### ISSUE THREAD

**Issue by Calrain** [arangodb/arangodb#2403]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.1.16

On this operating system:
- [X] Linux 
  - [x] Ubuntu .deb

I am running Ubuntu 16.04.2 LTS as a VM in VirtualBox 5.1.18 on Windows 10 Pro (dev environment).

Within Ubuntu, when upgrading from 3.1.15 to 3.1.16 the ArangoDB Server ran very slow, slowing down the Ubuntu operating system so much it was barely responsive.

After downgrading back to ArangoDB 3.1.15 then the Ubuntu VM became responsive and ArangoDB Server performance went back to acceptable levels.

When 3.1.16 was installed, queries to the ArangoDB server become so slow they timed out.

Increasing RAM on the VirtualBox VM from 3Gb to 4Gb did not improve the performance of 3.1.16 (in-case it has higher memory demands).

I have now downgraded to 3.1.15.

I tested on a second machine with same specs/setup and can confirm that when the arangodb3 software is upgraded to 3.1.16 the memory usage of the arangodb3 server process becomes very high, 2.5Gb on a 2.9Gb system, and when downgrading back to 3.1.15 the memory usage with the same test run on it is only 737 Mb.

**Comment by fceller** [comment]
@Calrain is it possible to get a copy of your database via private channel? This would help us to analyze what is going wrong.

**Comment by neunhoef** [comment]
What would help would be the output of db.c.figures()  (in arangosh) for your collections (c here as an example). If we had this for 3.1.15 and 3.1.16, this would be helpful.
We have done one change from 3.1.15 to 3.1.16 which is the target size for the revision cache. You could try different values for
  --database.revision-cache-target-size
to try to improve the situation for 3.1.16. I would try a very low value like
  67108864     (64MB)
and
  536870912   (512MB) which was the old default.
Seeing the figures() for all your collections would be useful in each configuration.

**Comment by moooji** [comment]
I have a very similar problem after upgrade from 3.1.15 -> 3.1.16. I had to downgrade again, because it was not possible to start ArangoDB anymore since memory continued increasing until all server memory was completely exhausted. The server has 64GB + 8GB swap! The DB collections are together around 10GB.

**Comment by Calrain** [comment]
I did some troubleshooting with guidance from @neunhoef and found a very large collection that had no indexes on it. The collection contained only about 60 documents but was 430Mb large. With 3.1.15 I could query that collection with about 0.120s response times, but after upgrading to 3.1.16 it started timing out. I then added a persistent index on the two fields that were used in the query and the queries then started responding in 0.001s, even in 3.1.16. 

@moooji - See if the query that is consuming all the memory is querying a collection that has no indexes, not a lot of documents, large size, or some mix of those.

**Comment by moooji** [comment]
Thx @Calrain for the info! Unfortunately, I cannot even run a query in 3.1.16 because server memory is exhausted after a few seconds. I literally only start ArangoDB, no query no Foxx scripts in 3.1.16 and after a few seconds nothing goes anymore.

**Comment by fceller** [comment]
@moooji can you do a

db._collections().map(x => {return {name: x.name(), properties: x.properties(), indexes: x.getIndexes(), count: x.count()}})

in the relevant database and post it here? This will give an overview of the collection structure.

**Comment by fceller** [comment]
@moooji There should indeed be no document without a `_key`. Is there any way to get a database dump?

**Comment by jsteemann** [comment]
We have looked into this and found that there are multiple reasons for the problem. The first one is that 3.1.16 changed the default value for the server's read-cache size
- in 3.1.15 the default value was `512 MB` if RAM was less than 2 GB, and `(RAM - 1 GB) * 0.4` if there were 2 GB or more of RAM 
- in 3.1.16 the default value is `512 MB` if RAM is less than 4 GB, and `1 GB` if there are 4 GB or more of RAM

That means if there are only 3 GB of RAM, then 3.1.15 gave the read cache 800 MB of RAM, whereas 3.1.16 will give it only 512 MB. That means 3.1.16 may have used smaller read cache sizes than 3.1.15 for small RAM sizes (<= 4 GB). 

Now if a query touches a collection that barely fits into the read cache, the read cache may run out of memory, which will trigger the cache's garbage collection. However, a document in the read cache may be accessed more than once per query, so the garbage collection may have led to the same documents being inserted, invalidated, re-inserted, invalidated, re-inserted... multiple times.
This of course was non-optimal.

We have fixed this so documents already in the read cache may now be reused in the same query. This should fix the problem of documents being stored in the cache multiple times.

Additionally, the fix reverts the change of the default read cache size introduced in 3.1.16 for RAM sizes of less than 4 GB. The default size of the read cache for such RAM sizes is now computed again as in 3.1.15 and before. The default value remains capped to 1 GB for RAM sizes of 4 GB or more (this capping was introduced in 3.1.16).

**Comment by Calrain** [comment]
Great, look forward to testing with the next release.

**Comment by dothebart** [comment]
ArangoDB 3.1.17 is available for download now.

**Comment by Calrain** [comment]
Thanks, the upgrade to 3.1.17 fixed issue. Thanks for the help on this one.
