### ISSUE TITLE
Query Processing Stall

### ISSUE THREAD

**Issue by ghost** [arangodb/arangodb#2405]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ X ] 3.1.16

On this operating system:
- [ X ] Linux 
  - [ X ] Debian .deb

I kill two out of 3 db servers everything is still well. I start the 2 i just killed and kill the last one. All query (and subsequent) progression will stall and eventually time out. I can consistently reproduce this by doing what i said before.

One example stalled query (executed after the last death):
103275	FOR x IN @@collection LET att = APPEND(SLICE(ATTRIBUTES(x), 0, 25), "_key", true) LIMIT @offset, @count RETURN KEEP(x, att)	34.93 s	2017-03-29T16:02:40Z

and it stays this way until the query times out somewhere around 112 - 120s? The cluster can only recover after starting that one downed node.

Subsequent queries would continue to fail until the last killed dbserver was started again. The expected situation would be for subsequent queries to have gone to the 2 recently started dbservers.

**Comment by fceller** [comment]
@normanuber What replication factor are you using? I'm asking because in case of a replication factor larger one the issue might be related to a still ongoing synchronization. Did the UI show if the recovery was still running?

**Comment by fceller** [comment]
We will try to set up a similar environment here.

**Comment by normanuber** [comment]
Replication factor of 2. UI showed there was a dbserver down but 2 dbservers were up and running.

**Comment by normanuber** [comment]
Has this been reproduced? Appears repeatable as I did it again and again. Maybe this is connected to the weird replication factor issue since one of my shards is now on 3 servers instead of 2 like the rest.

**Comment by fceller** [comment]
@normanuber we are currently investigate the other issue reported. So, no progress on this issue, yet.

**Comment by fceller** [comment]
There is a good chance that the issue are related. But we need to understand it.

**Comment by normanuber** [comment]
Thanks for your help with these odd issues though.

**Comment by fceller** [comment]
Thanks for your testing and patience. We will try to fix them asap.
