### ISSUE TITLE
Provide `vm.runInContext`

### ISSUE THREAD

**Issue by Yogu** [arangodb/arangodb#2411]
ArangoDB's JavaScript engine currently only supports the `runInThisContext` method of the `vm` package. I couldn't find a reason why `runInContext` is not supported. Would it be possible to support it?

I'm writing a middleware that allows its users to specify some JavaScript code that will be executed within a transaction, to validate data. I do not fully trust this code so I'd like to restrict its access to the file system etc. As ArangoDB's transaction model requires all code within a transaction to be executed inside ArangoDB itself, the code needs to be executed by the ArangoDB engine, which provides access to modules like `fs`.

Using `vm.runInContext`, we could not only prohibit access to the file system, but also limit access to the database through a custom-designed interface.

**Comment by pluma** [comment]
Please note the following sentence from the `vm` documentation of Node.js:

> _Note_: The vm module is not a security mechanism. **Do not use it to run untrusted code.**

https://nodejs.org/api/vm.html

**Comment by pluma** [comment]
To clarify: we can't currently provide an implementation of the `vm` module that would be compatible with Node.js but even if we do, it is an extremely bad idea to run untrusted code.

**Comment by Yogu** [comment]
> Please note the following sentence from the vm documentation of Node.js:
> 
>     Note: The vm module is not a security mechanism. Do not use it to run untrusted code.

I understand that, yet this feature makes it possible to have a reasonable layer of security (see the [`vm2`](https://github.com/patriksimek/vm2) module) over no protection at all. I wouldn't use it to run code from totally untrusted third-parties, but rather to open the possibility to run code to a wider audience.

If it's architecturally not possible to support `runInNewContext`, that's ok.

**Comment by pluma** [comment]
We don't currently provide JS bindings for the V8 functionality the vm module is using in Node so it's not something we can easily provide in JS right now. It should eventually be possible to provide this module in ArangoDB but you shouldn't hold your breath as it's currently a very low priority.

**Comment by dothebart** [comment]
meanwhile certain functions have access restrictions to the systems - see 
https://github.com/arangodb/arangodb/tree/devel/tests/js/client/server_permissions
for details. 
Closing as solved.
