### ISSUE TITLE
Trace which collection(s) cause a lock timeout

### ISSUE THREAD

**Issue by ThomasWeiss** [arangodb/arangodb#2413]
In case of lock timeouts, it would be useful to know which collection(s) are causing the timeout.

**Comment by jsteemann** [comment]
Add some diagnostic log messages in the `devel` branch.
These will print the involved collections in case of a lock timeout or a deadlock.

**Comment by ThomasWeiss** [comment]
Any chance to have this in 3.1.18?

**Comment by dothebart** [comment]
Sorry, no. The code around this patch has moved a lot in the rise of the rocksdb engine. It will become available with the beta release in near future.

**Comment by dothebart** [comment]
3.2 alpha 4 containing this bugfix is available for download now.
