### ISSUE TITLE
USERS menu on Web Interface does not work

### ISSUE THREAD

**Issue by AlyssonOliveira** [arangodb/arangodb#2414]
Clicking on USERS menu does nothing. It is not possible manage users on aardvark. How to enable it?

## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 3.1.17
- [ ] Linux 
  - [ ] Debian .deb

**Comment by lssn** [comment]
I tried manage users on 3.2-alpha3 so it worked! I hope it works on release 3.2 and be fixed on 3.1 series.

**Comment by hkernbach** [comment]
Thanks for the report. Unfortunately I am not able to reproduce. Any hints, server or browser logs/errors available?

**Comment by hkernbach** [comment]
Cleaned up some events. Maybe this was causing the issue. Please re-open if unresolved.

**Comment by AlyssonOliveira** [comment]
The browser console shows: 

libs.js?version=1492531017954:3 GET https://vps1493.publiccloud.com.br/_api/user?_=1493242316010 404 (Not Found)
send	@	libs.js?version=1492531017954:3
ajax	@	libs.js?version=1492531017954:3
b.ajax	@	libs.js?version=1492531017954:4
b.sync	@	libs.js?version=1492531017954:4
sync	@	libs.js?version=1492531017954:4
fetch	@	libs.js?version=1492531017954:4
fetch	@	app.js?version=1492531017954:2
render	@	app.js?version=1492531017954:11
userManagement	@	app.js?version=1492531017954:12
waitForInit	@	app.js?version=1492531017954:12
userManagement	@	app.js?version=1492531017954:12
execute	@	app.js?version=1492531017954:12
(anonymous)	@	libs.js?version=1492531017954:4
(anonymous)	@	libs.js?version=1492531017954:5
s.some.s.any	@	libs.js?version=1492531017954:4
loadUrl	@	libs.js?version=1492531017954:5
navigate	@	libs.js?version=1492531017954:5
navigate	@	libs.js?version=1492531017954:4
navigateByTab	@	app.js?version=1492531017954:9
dispatch	@	libs.js?version=1492531017954:2
q.handle	@	libs.js?version=1492531017954:2
﻿

​I updated to 3.1.18
