### ISSUE TITLE
HTTPS call inside Foxx application 

### ISSUE THREAD

**Issue by sajeevpr** [arangodb/arangodb#2418]
Dear team,
   We are trying to see whether we can call https call with in Foxx service. Our requirement is one Foxx service calls another Foxx service exposed over https.

I tried with request module. But no luck. Is there any way this can be done.

Thanks & Regards,
Sajeev

**Comment by dothebart** [comment]
could this be a duplicate of #1974 ? So then you're lucky ;-)

**Comment by baslr** [comment]
@sajeevpr this is fixed with ArangoDB v3.1.18

**Comment by sajeevpr** [comment]
Thank you. Will wait for 3.1.18

**Comment by dothebart** [comment]
Sorry, the target milestone was missing. The release containing this bugfix is available for download.
