### ISSUE TITLE
Persistent Indexes not working correctly on osx

### ISSUE THREAD

**Issue by dispareil** [arangodb/arangodb#2422]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.1 (specifically 3.1.17)

On this operating system:
- [x] MacOS, version: Sierra

### this is a database issue

These are the steps to reproduce:

assuming

`{
     "book": string,
     "categories": array[string]  
}`

is the schema for documents

1. Open arangosh with --server.username root  --server.password ''
2. Create a new database and switch to this database
3. Create a new collection
4. Create a persistent index on 'categories' property
5. Now try to save a new document in the collection and check activity monitor 
6. You will find arangod process taking 70-80% cpu 
7. Since the save operation will not complete, restart the database and check logs
8. you will find something like

`2017-04-12T05:28:00Z [71658] ERROR cannot read collection info file in directory '/usr/local/var/lib/arangodb3/databases/database-249953/collection-250004-3858355378': bad parameter
2017-04-12T05:28:00Z [71658] ERROR error while opening database: bad parameter
2017-04-12T05:28:00Z [71658] FATAL cannot start database: bad parameter`

I installed arangodb using homebrew

**Comment by jsteemann** [comment]
I have pushed a fix into the 3.1 and devel branches.
Should be fixed with next release (3.1.18).

**Comment by dispareil** [comment]
should i close this bug now or wait for the 3.1.18 release ?

**Comment by dothebart** [comment]
We will close it once its target milestone has been released, so you will also get to know when the fix is available through distribution packages.

**Comment by dothebart** [comment]
3.1.18 including this fix is now available for download.

**Comment by dothebart** [comment]
I have to ommit that the homebrew install is broken with 3.1.18

**Comment by dothebart** [comment]
Sorry for the delay, had to get some work on the Homebrew scripts done first; 
However, ArangoDB 3.1.19 is now available via homebrew - closing.
