### ISSUE TITLE
Adding a collection in the from/to list of an edgeCollection in a graph.

### ISSUE THREAD

**Issue by Pkoiralap** [arangodb/arangodb#2423]
I was wondering if I could add in a new Collection in the from/to list of a graph.

There is this graph 
```
{
    'graph_name': 'Something',
    'edgeCollections': [
         {
             relationCollection: Relation1,
             from: [ col1, col2, col3 ],
             to: [ col2,col4 ]
         },
          {
             relationCollection: Relation2,
             from: [ col2, col3, col4 ],
             to: [ col1,col4 ]
         }
    ]
}

```
Is there a way to add a new collection to the from/to of edgeCollections with relationCollection 'Relation1'  ?? I could not find it in the documentation. Although there exists a addVertexCollection method , it adds the collection as an orphan collection. Are those two things same ?? 

The expected Graph is something like this

```
{
    'graph_name': 'Something',
    'edgeCollections': [
         {
             relationCollection: Relation1,
             from: [ col1, col2, col3, new_col1 ],
             to: [ col2,col4 , new_col2]
         },
          {
             relationCollection: Relation2,
             from: [ col2, col3, col4 ],
             to: [ col1,col4 ]
         }
    ]
}

```

**Comment by dothebart** [comment]
Hi, 
in general these graph definitions are simple documents saved into the system collection `_graphs` by the gharial management interface. You can alter them as described in the interface documentation: https://docs.arangodb.com/3.1/HTTP/Gharial/Management.html which is used by the drivers.

After you've added the new Vertex collection you need to add it to an Edge Definition, or create a new edge definition referencing it:
https://docs.arangodb.com/3.1/HTTP/Gharial/Management.html#replace-an-edge-definition
