### ISSUE TITLE
Saving updated edge document via ArangoDB UI says 'saved' but an error was generated.

### ISSUE THREAD

**Issue by Calrain** [arangodb/arangodb#2424]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.1.15

On this operating system:
- [x] Linux 
  - [x] Ubuntu 16.04 LTS

I'm issuing AQL via:
- [x] web interface with this browser:    Chrome Version 57.0.2987.133 running on Windows 10 Pro

This has happened a few times now and it's worth reporting.

I have an edge collection with only 13 edges, it connects two collections with 4 documents and 12 documents respectively.

The issue is that I login via the ArangoDB UI and open a document within the Edge collection.

When I modify the document for a particular document, in 'Code' view, and click save, the UI shows a green bar on the bottom of the screen that says 'Document saved.'.

When you close the edge document and open it again, the changes were not saved.

If you add attributes to a new edge, it says saved but when you open it the document is empty.

If you use Developer tools in Chrome to see what happened there is an error coming back from the ArangoDB server that the UI is not handling:

This is the PUT request that is generated when I click 'Save'
Request URL: https://myserver:8530/_db/mydatabase/_api/document/myedgecollection
Request method: PUT
Status Code: 202 Accepted
Request Payload:
`[{"mykey":{"foo":"bar"},"qaz":"wsx","foo":"bar","_key":"362694866","_id":"myedgecollection/362694866"}]`

Response:
`[{"error":true,"errorNum":1233,"errorMessage":"edge attribute missing or invalid"}]`

Actually, on trying to replicate the issue, I'm unable to modify any documents in any edge collections, regardless of size.

To update them I have to create a Query and write AQL to update the edge by _id.

I suppose there are two issues, one is why the 'edge attribute missing or invalid' is coming back, especially when I can update that edge via an AQL query, and secondly why doesn't the UI capture this error and display something on the UI.

**Comment by hkernbach** [comment]
This was an issue in 3.1.15. Please update to 3.1.16 or latest 3.1.X release.

**Comment by Calrain** [comment]
Thanks for that, I upgraded to 3.1.17 and it fixed the problem.  But I noticed that whenever you save a document in 3.1.17, either a vertex or edge document, the javascript console does a console.log output echo of the document contents and document type. It may have been left from troubleshooting an issue.

**Comment by hkernbach** [comment]
Yes, you're right. Removed. Thanks 👍
