### ISSUE TITLE
Arangodb Foxx services cross site scripting

### ISSUE THREAD

**Issue by sajeevpr** [arangodb/arangodb#2425]
Dear team,
    Is there any way Foxx services can be secured from XSS - cross site scripting.

Thanks & Regards,
Sajeev

**Comment by fceller** [comment]
A sending a request `http://127.0.0.1:8529/<script>cross_site_scripting</script>.asp` to ArangoDB which answers truthfully:

`{"error":true,"code":404,"errorNum":404,"errorMessage":"unknown path '/<script>cross_site_scripting</script>.asp'"}`

The problem now is that there is a bug in IE that will execute the `<script>cross_site_scripting</script>.asp`.

That is a known issue in IE and can be solved by adding "x-content-type-options: nosniff" to every response. We will add this to the headers of the repsonse.

**Comment by dothebart** [comment]
3.1.19 is available for download - closing. Feel free to comment if the issue persists.
