### ISSUE TITLE
add issue titles to the change log

### ISSUE THREAD

**Issue by Thijxx** [arangodb/arangodb#2426]
Could you please add issue titles to the change log where now only the issue ID resides? With only an ID it becomes a puzzle to read the log.

**Comment by baslr** [comment]
Hi @Thijxx,

I think we could automate that one :-)

Its maybe also worth a thought to split up the changelog into its major versions. The current changelog loads ages on github.

**Comment by dothebart** [comment]
We currently will lean on doing that manually. Its a good hint, plain numbers in changelog look bad. We started changing our habbits about that now - see the latest alpha release ;-)
