### ISSUE TITLE
PVS-Studio: An unconditional 'break' within a loop.

### ISSUE THREAD

**Issue by SvyatoslavRazmyslov** [arangodb/arangodb#2427]
We have found a bug using PVS-Studio tool. PVS-Studio is a static code analyzer for C, C++ and C#: https://www.viva64.com/en/pvs-studio/

We suggests having a look at the emails, sent from @pvs-studio.com.

Analyzer warning: [V612](https://www.viva64.com/en/w/V612/) An unconditional 'break' within a loop. MMFilesPersistentIndex.cpp 353

**arangod/MMFiles/MMFilesPersistentIndex.cpp:**

```
int MMFilesPersistentIndex::insert(....) {
  ....
  while (iterator->Valid()) {
    int res = comparator->Compare(iterator->key(), ....);

    if (res > 0) {
      break;
    }

    uniqueConstraintViolated = true;
    break;  // <=
  }
  ....
}
```
I'm using the latest ArangoDB of the respective release series:
- [+] self-compiled devel branch

On this operating system:
- [+] Linux 
- [+] Windows, version:

**Comment by jsteemann** [comment]
Thanks. 
Though this is not necessary a "real" bug, I changed to change from using a `while` loop to a mere `if` to make it more readable.
