### ISSUE TITLE
PVS-Studio: Dereferencing of the null pointer 'f' might take place.

### ISSUE THREAD

**Issue by SvyatoslavRazmyslov** [arangodb/arangodb#2428]
We have found a bug using PVS-Studio tool. PVS-Studio is a static code analyzer for C, C++ and C#: https://www.viva64.com/en/pvs-studio/

We suggests having a look at the emails, sent from @pvs-studio.com.

Analyzer warning: [V522](https://www.viva64.com/en/w/V522/) Dereferencing of the null pointer 'f' might take place. ApplicationServer.cpp 471

**lib/ApplicationFeatures/ApplicationServer.cpp:**

```
void ApplicationServer::disableDependentFeatures() {
  ....
  if (f == nullptr) {
    LOG_TOPIC(TRACE, Logger::STARTUP) << "...." << f->name() << "'";
    ....
  }
  ....
}
```
I'm using the latest ArangoDB of the respective release series:
- [+] self-compiled devel branch

On this operating system:
- [+] Linux 
- [+] Windows

**Comment by jsteemann** [comment]
Thanks, it's now fixed in the `devel` branch.
