### ISSUE TITLE
PVS-Studio: The 'then' statement is equivalent to the 'else' statement.

### ISSUE THREAD

**Issue by SvyatoslavRazmyslov** [arangodb/arangodb#2429]
We have found a bug using PVS-Studio tool. PVS-Studio is a static code analyzer for C, C++ and C#: https://www.viva64.com/en/pvs-studio/

We suggests having a look at the emails, sent from @pvs-studio.com.

Analyzer warning: [V523](https://www.viva64.com/en/w/V523/) The 'then' statement is equivalent to the 'else' statement. v8-globals.h 685

**lib/V8/v8-globals.h:**

```
template <typename TARGET>
inline void TRI_V8_AddMethod(....) {
  // hidden method
  if (isHidden) {
    tpl->Set(name, v8::FunctionTemplate::New(isolate, callback)->GetFunction());
  }
  // normal method
  else {
    tpl->Set(name, v8::FunctionTemplate::New(isolate, callback)->GetFunction());
  }
}
```

I'm using the latest ArangoDB of the respective release series:
- [+] self-compiled devel branch

On this operating system:
- [+] Linux 
- [+] Windows

**Comment by jsteemann** [comment]
Thanks. Fixed in the `devel` branch now.
