### ISSUE TITLE
incorrect runFailures in queue task

### ISSUE THREAD

**Issue by dsonet** [arangodb/arangodb#2433]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.1

On this operating system:
- [x] Windows, version: 10

### Foxx
reset the repeat tasks‘s runFailures incorrectly, so it always be 0.
https://github.com/arangodb/arangodb/blob/devel/js/server/modules/%40arangodb/foxx/queues/worker.js#L165

Should just remove this accidental reset.

The following problem occurs:  
it always be 0.

Instead I would be expecting: 
leave it as real, don't reset it.

**Comment by mpv1989** [comment]
I will close this issue because ArangoDB 3.1 is EOL by now. Feel free to open it again if the issue still exists with 3.3.14.

**Comment by pluma** [comment]
FWIW this may have been fixed in 3.4.
