### ISSUE TITLE
search in documentation

### ISSUE THREAD

**Issue by Thijxx** [arangodb/arangodb#2434]
It would be nice to have a search function in the documentation, Google results are full of old version and therefore also duplicates.

for example when I Google `foxx-manager` it returns a result for version **2.8**

**Comment by dothebart** [comment]
We used the gitbook.com s own search function in advance, which was even worse than google search, but yes we're also not happy with the way its currently...

**Comment by baslr** [comment]
@Thijxx you can search with `site:docs.arangodb.com/3.1 foxx-manager` to find results for ArangoDB v3.1 only.
