### ISSUE TITLE
SSL configuration not clear

### ISSUE THREAD

**Issue by Thijxx** [arangodb/arangodb#2435]
The documentation could benefit from better configuration examples. I believe the preferred method of configuration of a database is a config file, not command line options. SSL for example may be a section in the config like `[ssl]` or not, it may be like described [here](http://stackoverflow.com/questions/40315135/arangod-conf-for-ssl) but maybe not in combination with config options set in the init script or service config. This remains unclear.

**Comment by baslr** [comment]
you can you files and cli options the same time. But keep in mind that cli options win over options in files as stated here https://docs.arangodb.com/3.1/Manual/Administration/Configuration/#configuration-files.

You can configure the ssl endpoint and protocol in a config file and the keyfile in a cli option.

```
# config.conf
[ssl]
protocol = 5

[server]
endpoint = http+ssl://127.0.0.1:8000


arangod --configuration config.conf --ssl.keyfile /path/to/cert.pem
```
