### ISSUE TITLE
Same collection IDs and same document keys used in different databases on same server causes refused connections and data loss

### ISSUE THREAD

**Issue by georgekaf** [arangodb/arangodb#2437]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.1

On this operating system:
- [x] Linux 
  - [x] Debian .deb
  - [x] RedHat .rpm

These are the steps to reproduce:
1) Use arangodump on a database with enough collections and documents.
2) Restore the dump to a different database on same server
3) Update same attributes with dummy data in documents with the same keys on the same collections between the two databases

The following problems occur: 
1) Frequent updates (In my case we were using the php driver) cause "connection refused" with error code "111". Described here  https://groups.google.com/forum/#!topic/arangodb/CQTuxJMYoBg
2) Data loss is happening (we lose updated/changed data on same-key documents). New documents with unique keys seem unnaffected. Described here https://groups.google.com/forum/#!topic/arangodb/H1WcP1l2B8U

Just opening an issue to keep track of the problem.

**Comment by georgekaf** [comment]
I am not sure if this affects also system collections like _graphs and 
_aqlfunctions. We don't change the _aqlfunctions between databases but 
_graphs should contain different data (?).

**Comment by balacuit** [comment]
👍

**Comment by sleto-it** [comment]
**Workaround:** please create the collections in the target database manually. Then with arangorestore use the option `--create-collection = false`

**Comment by maxkernbach** [comment]
Hi @georgekaf,

the data loss issue has potentially been fixed in 3.3.3. We could not detect any data loss when reproducing as you explained. Can you confirm that this problem does not occur in the latest version?

Thanks

**Comment by OmarAyo** [comment]
Hi @georgekaf 

Could you please send us an update on this ticket ?

Many thanks

**Comment by sleto-it** [comment]
I am now closing this. Please feel free to comment if you see this again

Many thanks,

**Comment by georgekaf** [comment]
Unfortunately, I have left the company which was using arango dump and restore as way of copying databases, so I don't have any updates on that. Perhaps @eafiontzi can be of assistance.

**Comment by eafiontzi** [comment]
Hello, we have not upgraded to 3.3.3 yet but if we do and have an update I will let you know.

Many thanks,
