### ISSUE TITLE
Indexing break replication

### ISSUE THREAD

**Issue by de3** [arangodb/arangodb#2440]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ x ] 3.1
- [ ] 3.2 pre-releases: ___
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ x ] docker - official docker library
  - [ ] other:

I use master-slave arangodb as architecture. I have 1 master, and 3 slave (replication)
When I try to create new index on master, I got replications was broken and stop

I've try some method, 
- stop replication before indexing on master (not worked, still stopped)
- stop replication before indexing on master, and start with previous tick (safeResumeTick) (not worked, still stopped)
- re-sync collection that create index, but it not sync another collection (so other collection will not updated)

The only thing that I can use only 2:
- drop replication, and create again replication
- full sync all collection and use new tick id

my question is, what is the correct step to create indexing for my case? because this is not only when indexing, when I create new collection on master, it will break my replication

thanks

**Comment by jsteemann** [comment]
Fixed in 3.0 and 3.1. Will be fixed in devel branch too once the `engine-api` branch will be merged back into devel.
The fix will become available with 3.1.19.

**Comment by dothebart** [comment]
3.1.19 is available for download - closing. Feel free to comment if the issue persists.
