### ISSUE TITLE
ArangoJS: Key with value undefined being omitted in the document

### ISSUE THREAD

**Issue by Pkoiralap** [arangodb/arangodb#2443]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [  ] 3.1
- [ ] 3.2 pre-releases: ___
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [  ] MacOS, version:

When using arangojs I noticed that it doesn't save an object completely if it has a key with value undefined in it. Is this the desired outcome ? 
I did following things

```
db.collection('testCol').create()
.then(() => {
   let docToSave = {a: undefined, b: null};
   let col = db.collection('testCol');
   col.save(docToSave);  
})
```

A look at the document and you see only the {b: null} in it. Why is my undefined value being ommited ?
![screen shot 2017-04-20 at 9 57 17 pm](https://cloud.githubusercontent.com/assets/7931946/25241073/6c0a96ca-2614-11e7-94af-f8c0dfe35197.png)

**Comment by jsteemann** [comment]
I think this is the desired outcome. 
arangojs uses the JSON-based HTTP API for communication with the server. And JSON cannot map `undefined` to any JSON type. That means `JSON.stringify(...)` will also remove all `undefined` values so they are not getting transferred to ArangoDB:

```js
JSON.stringifyJSON.stringify({ a: undefined, b: null });
{"b":null}
```
