### ISSUE TITLE
JavaScript exception in file '/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js' at 97,7: ArangoError 18: lock timeout

### ISSUE THREAD

**Issue by XieJunhua** [arangodb/arangodb#2447]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [x] 3.1
- [ ] 3.2 pre-releases: ___
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [x] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [x] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [x] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click to ...
...

The following problem occurs: [Screenshot?] 
Instead I would be expecting: 

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

when i try to create an index on my cluster, i meet some error.
```
arangosh --server.endpoint tcp://ip:8529 --server.database hbtest --server.username huanbei --server.connection-timeout 60000 --server.request-timeout 60000

db.s1010517.ensureIndex({type:"skiplist", fields:["maxent_id"], sparse:true})

and then i get this error：
JavaScript exception in file '/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js' at 97,7: ArangoError 18: lock timeout
!      throw error;
!      ^
stacktrace: ArangoError: lock timeout
    at Object.exports.checkRequestResult (/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js:95:21)
    at ArangoCollection.ensureIndex (/usr/share/arangodb3/js/client/modules/@arangodb/arango-collection.js:602:12)
    at <shell command>:1:13
```
tips: 1. When i make my index, I had 7 millions data in my collection.
        2. I made the arangodb cluster by [arango doc](https://docs.arangodb.com/3.1/Manual/Deployment/Distributed.html)

**Comment by neunhoef** [comment]
Which version are you using exactly? Are there other requests running on the db during the index creation? If so, how many? What does `top` show?

**Comment by dothebart** [comment]
Hi, 
Any news on this? or could we close it? 
Nb, We're pleased to anounce that ArangoDB 3.2 containing lots of improvements to the clustering.
