### ISSUE TITLE
Intermittent issue where ArangoDB Web UI takes no action when Delete button is clicked for a document

### ISSUE THREAD

**Issue by Calrain** [arangodb/arangodb#2448]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.1.18

On this operating system:
- [x] Linux 
  - [x] Ubuntu .deb 16.04 LTS

This is a web interface-related issue:
I'm using the web interface with this browser:  Chrome 57.0.2987.133  running on this OS: Windows 10 Pro
- [x] authentication is enabled?
- [x] ssl is enabled?
- [ ] using the cluster?
- [ ] _system database?

I cannot yet determine the steps to reproduce it, but it has happened about 4 times in working with 3.1.18 for 4 hours.

The issue is the UI refuses to do anything when the Delete button is clicked for a document.

It seems to be related to the 'delete' action handler in the UI, as it doesn't matter if you invoke 'delete' by hitting the (-) icon to the right of a document, or click the DELETE button when viewing a document.

There are no errors thrown in the console.log window of Chrome.

I have all ad blocker and social media removing extensions disabled for the ArangoDB UI, so it is not interfering.

To resolve the problem, I find I have to F5 reload the page and then the delete button works.

Will update when I can work out how to make it repeatable.

**Comment by Calrain** [comment]
Ok.. it is now repeatable, and I've a lot of web front end development but have never seen this issue before.

To replicate it:

 - Launch the ArangoDB Web UI 3.1.18 in Chrome 57.0.2987.133 on Windows 10. (Have also confirmed this issue occurs on Firefox 53.0 on Windows 10)
 - Open a collection and add a document, say { a: 1 }
 - Click on 'COLLECTIONS' on the left side of the screen
 - Hold the mouse over the collection the document is in, and click the Middle mouse button, the mouse wheel, try moving the mouse, it may or may not scroll.
 - The UI will show an icon that looks like the icon on this image: https://i-msdn.sec.s-msft.com/dynimg/IC725697.png
 - Press ESC to stop that mouse mode
 - Left click on the collection to open it
 - Click the (-) button to the right of the document to delete it
 - The model dialog box `docDeleteModal` will appear
 - Clicking the Delete button will do nothing.. the dialog box just acts like a click event didn't occur

To fix it:
 - Press F5 to reload the page
 - Click the (-) button and click Delete, it will delete as expected.

**Comment by hkernbach** [comment]
Thanks for spotting and the very detailed info on how to reproduce. Fixed in devel and 3.1 branch. Will be included in 3.1.19.

**Comment by Calrain** [comment]
Thanks for fixing that. I think I found the issue because I have a habit of using the middle mouse button to open a link in a new window, and I was middle clicking on collections to open that collection in a new window. Thanks for fixing it.

**Comment by dothebart** [comment]
Ah, sorry, the target milestone was missing. 3.1.20 is available for download - closing.
