### ISSUE TITLE
GraphBrowser "Expand" function doesn't load all possible edges

### ISSUE THREAD

**Issue by vlabmichl** [arangodb/arangodb#2453]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [x] 3.1
- [ ] 3.2 pre-releases: ___
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [x] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [x] Windows, version: 7
- [ ] MacOS, version:

### this is a web interface-related issue:
I'm using the web interface with this browser:     Firefox / Chrome (latest) running on this OS: Win7

These are the steps to reproduce:
1) Load a known graph
2) Browse around and select a vertex
3) Use the "expand" function from the menu

The following problem occurs:
* The GraphBrowser loads only some of the related edges.
* Edges to already loaded vertices are not loaded / ignored.
-> This is irritating as it doesn't represent the correct data.

You can proof that the missing edges / connections are definetly made if you
set the suspected vertex as new "start node".

**Comment by hkernbach** [comment]
Thanks for the report. It is fixed in devel and 3.1.

**Comment by dothebart** [comment]
3.1.19 is available for download - closing. Feel free to comment if the issue persists.
