### ISSUE TITLE
cross compiling fails for ARM32, but for ARM64 works

### ISSUE THREAD

**Issue by servusoft** [arangodb/arangodb#2458]
## my environment running ArangoDB
- [x ] 3.2 pre-devel: ___
- [x] self-compiled devel branch

On this operating system:
- [x] Linux 
  - [x] Debian
  - [x] docker - build docker 

Steps to  reproduce:

use  arangodb-helper/build-docker-containers
for cross-compiling ARMv7 on debian jessie:

Possible issue:
static_assert (sizeof(size_t)    == 4, "size size_t is not 4");    // Ok on ARMv7, not on ARM64
static_assert (sizeof(size_t)    == 8, "size size_t is not 8");    // Ok on ARM64, not on ARMv7

**Comment by danielhlarkin** [comment]
Forgot to put the reference in the commit, but should be fixed by f4a8b69.
