### ISSUE TITLE
SSL error after upgrade from 3.0 to 3.1

### ISSUE THREAD

**Issue by Thijxx** [arangodb/arangodb#2464]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [X] 3.1

On this operating system:
- CentOS7

### this is a web interface-related issue:
I'm using the web interface with this browser:  Chrome   running on this OS: Arch Linux
- [SSL] After upgrading the server responds with "ERR_SSL_PROTOCOL_ERROR"

Log:
```
2017-05-01T14:35:19Z [11309] ERROR {communication} unable to perform ssl handshake: wrong version number : 336130315
2017-05-01T14:35:46Z [11309] INFO control-c received, beginning shut down sequence
2017-05-01T14:35:46Z [11309] FATAL control-c received (again!), terminating
```

**Comment by jsteemann** [comment]
Which SSL settings are you using for arangod? Precisely, what's the setting for `--ssl.protocol`? (should be set to `5` to enable TLS 1.2).

**Comment by Thijxx** [comment]
These settings are unchanged since the upgrade.

Maybe I should create a new `pem` file? I will give this a try.

```
endpoint = ssl://0.0.0.0:8530

[ssl]
keyfile=/etc/arangodb3/server.pem
protocol=5
```

**Comment by baslr** [comment]
@Thijxx,

I tried to reproduce your problem but for me the web interface is working as expected.
`wrong version number` points to server and client have assume different tls versions.

**Comment by Thijxx** [comment]
I'd like to PM you the URL to my server so you can see what happens if you connect to it using HTTPS but I do not have your contact details..

**Comment by baslr** [comment]
@Thijxx you can reach me at manuel@arangodb.com

**Comment by Thijxx** [comment]
Upgrading Arango and moving to another certifiate supplier did not help. So it looks like I need to completely wipe my drive and reinstall the OS to have a chance of getting TLS working again. And this all after a minor upgrade.

**Comment by Thijxx** [comment]
New server, clean drive, new install, new certificates, new Arango version (3.20) and the same issue. So TLS is completely broken on Arango at the moment, at least for CentOS7.

**Comment by dothebart** [comment]
From our build dockers: 
rpm -qa |grep ssl 
openssl-libs-1.0.1e-60.el7_3.1.x86_64
openssl-devel-1.0.1e-60.el7_3.1.x86_64

is yours similar?

**Comment by graetzer** [comment]
Hi Thijxx, 
your issue is very important to us and I would like to reproduce it by retracing your exact steps.

Can you tell me exactly from which arangodb version you initially upgraded?

From reading the conversation history here, I assume you initially started with 3.0.12 is that correct?
And then you upgraded to 3.1.19 and subsequently 3.1.20 ?

**Comment by Thijxx** [comment]
my SSL packages

```
openssl-1.0.1e-60.el7_3.1.x86_64
mod_ssl-2.4.6-45.el7.centos.4.x86_64
python-backports-ssl_match_hostname-3.4.0.2-4.el7.noarch
openssl-libs-1.0.1e-60.el7_3.1.x86_64
```

**Comment by Thijxx** [comment]
@graetzer thank you
I think it was 3.18 initially, then to 3.19 it broke. Now I completely reinstalled my server and it's 3.20.
So clean install, same issue. That is why I do not think my old config matters.

Current config (3.20):
```
# ArangoDB configuration file
# 
# Documentation: 
# https://docs.arangodb.com/Manual/Administration/Configuration/
# 

[database]
directory = /var/lib/arangodb3

# maximal-journal-size = 33554432

[ssl]
protocol =5
keyfile = /etc/arangodb3/certkey.pem
cafile = /etc/arangodb3/chain.pem
cipher-list = HIGH

[server]
endpoint = ssl://0.0.0.0:8530
endpoint = tcp://0.0.0.0:8529

# resuse a port on restart or wait until it is freed by the operating system
# reuse-address = false

authentication = true

# number of server threads. use 0 to make arangod determine the
# number of threads automatically, based on available CPUs
# threads = 0

# gather server statistics
statistics = true

# the user and group are normally set in the start script
# uid = arangodb
# gid = arangodb

uid = arangodb


[scheduler]
# number of threads used for I/O, use 0 to make arangod determine
# the number of threads automatically
# threads = 0

[javascript]
startup-directory = usr/share/arangodb3/js
app-path = /var/lib/arangodb3-apps
# app-path = //arangodb3/apps

# number of V8 contexts available for JavaScript execution. use 0 to 
# make arangod determine the number of contexts automatically.
# v8-contexts = 0

[foxx]
# enable Foxx queues in the server
# queues = true

# interval (seconds) to use for polling jobs in Foxx queues
# queues-poll-interval = 1

[log]
level = info
file = /var/log/arangodb3/arangod.log

[cluster]

```

**Comment by fceller** [comment]
@graetzer @baslr I bought a small machine at iniz.com for testing and I can reproduct the above error with firefox (strangely chrome works). Ping for login details, we can now do more tests

**Comment by fceller** [comment]
It is the

    protocol=5

that is causing the trouble. We will debug this further.

**Comment by fceller** [comment]
It is the combination of

    protocol=5
    cipher-list = HIGH

**Comment by jsteemann** [comment]
I am positive that [this pull request](https://github.com/arangodb/arangodb/pull/2594) will address the problem and fix it. The change has not been merged into 3.1 yet, but if you want to, you can give it a test drive already using the patch contained in the pull request.

**Comment by jsteemann** [comment]
A potential fix for this is contained in ArangoDB 3.1.23. This version will be released soon. It would be good if you could give that version a test when it is released.

**Comment by Thijxx** [comment]
I will upgrade when it releases and then try to activate the SSL configuration again.

**Comment by dothebart** [comment]
3.1.23 is available for download now. 
Thanks for all the assistance you provided to get this issue resolved. 

Closing.
