### ISSUE TITLE
User cannot update its own password without access to _system db when using Velocystream

### ISSUE THREAD

**Issue by ewoutp** [arangodb/arangodb#2465]
When a user has no access to the `_system` database, any call to `_api/user` fails with `{"error":true,"code":401,"errorNum":11,"errorMessage":"not authorized to execute this request"}` when using Velocystream.
According to the documentation I only need access to the `_system` database when fetching info of other users or when changing the active flag. I'm not doing any of these.

To reproduce, run go-driver tests in the `vst` branch using 
```
make run-tests-single-vst-with-auth
```

The code that is failing is here: {"error":true,"code":401,"errorNum":11,"errorMessage":"not authorized to execute this request"}. 
When using HTTP+JSON or HTTP+VPACK this code runs ok.

**Comment by neunhoef** [comment]
I think this is fixed in devel, just tried to run all go-driver tests with VelocyStream and did not get an error.
I will leave this open for now since I need to port the change to 3.1 as well for 3.1.20.

**Comment by ewoutp** [comment]
Go driver tests for VST now succeed on devel (with & without authentication).

**Comment by ewoutp** [comment]
Reopening since this does not work yet for 3.1.
We must either make it work in 3.1 or exclude it from the go-driver for 3.1 databases.

**Comment by neunhoef** [comment]
Yes, let's leave it open until we have ported the fix to 3.1.

**Comment by jsteemann** [comment]
@ewoutp : has this been fixed in 3.1 now? If not, the port was probably too time-consuming or risky and therefore has been avoided. Can we label this "fixed" now as it has been fixed in 3.2?

**Comment by ewoutp** [comment]
@jsteemann afaik @neunhoef still plans to back port it to 3.1, so let's leave it open until he's back

**Comment by neunhoef** [comment]
Fixed in 3.2, will not fix in 3.1 for now.
