### ISSUE TITLE
JWT authentication is not supported using Velocystream

### ISSUE THREAD

**Issue by ewoutp** [arangodb/arangodb#2466]
These are actually 2 problems:

1 - `/_open/auth` is not accessible when using Velocystream  (status code 401)
2 - VST Header with type `1000` and `encryption` set to `jwt` is not implemented, but still in the VST 1.0 spec.

**Comment by neunhoef** [comment]
I am on the case, this will hopefiully be in 3.2 and 3.1.20.

**Comment by jsteemann** [comment]
@ewoutp @neunhoef : does anyone of you know whether this issue has been fixed in 3.2?

**Comment by neunhoef** [comment]
Fixed in 3.2, will not fix 3.1 for now.
