### ISSUE TITLE
ArangoDB Frontend calls an external hosted javascript

### ISSUE THREAD

**Issue by fdsg-tk** [arangodb/arangodb#2468]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [X] 3.1
- [ ] 3.2 pre-releases: ___
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [X] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is a web interface-related issue:
I'm using the web interface with this browser: Firefox running on this OS: Windows / Fedora
- [X] authentication is enabled?
- [ ] using the cluster?
- [X] _system database?

These are the steps to reproduce:
1) open the browser on http://{HOSTNAME}:8529
2) log in as .root
3) use database [X ] `_system`

The following problem occurs: [Screenshot?] 
Our Cybercrime Defence Report shows, that the ArangoDB Frontend is calling an external hosted javascript from arangodb with content type application/javascript.
I assume, that this is the script which checks for a new arangodb version release.
Moreover, arangosh also shows a "new version" notifier message like "Please note that a new bugfix version '3.1.x is available", so it also tries to connect to the arangodb internet services for version checking.

Instead I would be expecting: 
I would propose to implement a configuration parameter, which disables all communiction to external arangodb services.
Furthermore, the "version check" feature and all other external communication (if existing) should be documented. (If they are already documented, I have not found it).

**Comment by baslr** [comment]
https://github.com/arangodb/arangodb/issues/2091#issuecomment-252291991

**Comment by fceller** [comment]
Duplicate #2091
