### ISSUE TITLE
Authentication = true does not protect foxx-routes

### ISSUE THREAD

**Issue by AxelRHD** [arangodb/arangodb#2469]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [X] 3.1
- [ ] 3.2 pre-releases: ___
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [X] Linux 
  - [ ] Debian .deb
  - [X] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### Foxx

ArangoDB was installed on Ubuntu and is running with default config.file ([server] authentication = true).

In the docs i red, that this should protect also the routes from foxx-microservices. In fact this routes are unprotected.

**Comment by jsteemann** [comment]
Foxx apps can be configured separately. The assumption is that Foxx apps often implement their own authentication, which will be different from the authentication for the database APIs.
The default is that Foxx apps are accessible.

This can be changed by setting `--server.authentication true` and `--server.authentication-system-only false`.

**Comment by jsteemann** [comment]
Where in the docs does it state that Foxx apps require authentication by default? If the docs are not clear, they should be adjusted.

**Comment by AxelRHD** [comment]
Ok, it is realy not clear in the documentation (or missunderstood by me).

> ## [Turn on the Authentication](https://docs.arangodb.com/3.1/cookbook/Administration/Authentication.html#turn-on-authentication)
> 
> Authentication is turned on by default in ArangoDB. You should make sure that it was not turned off manually however. Check the configuration file (normally named /etc/arangodb.conf) and make sure it contains the following line in the server section:
> 
> `authentication = true`
> 
> **This will make ArangoDB require authentication for every request (including requests to Foxx apps)**.

And I Interpreted the section after as "if you don't want all routes protected, then set authentication-system-only = true".

Perhaps you can put the option `authentication-system-only = false ` in the box above with the `authentication = true`?

**Comment by AxelRHD** [comment]
With the description you described it works now as expected. Thanks for support. Issue can be closed.

**Comment by jsteemann** [comment]
Thanks. I have updated the docs accordingly in devel (https://github.com/arangodb/arangodb/commit/0641a0d404730ecd329fc92894cef0d399b9d3ea). 
The changes will become available with the 3.2 release.

**Comment by dothebart** [comment]
ArangoDB 3.2.beta1 containing all this is available for download. Closing.
