### ISSUE TITLE
cannot locate 'usr\share\arangodb 3\icudtl.dat'

### ISSUE THREAD

**Issue by walnut1015** [arangodb/arangodb#2472]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [x] 3.1
- [ ] 3.2 pre-releases: ___
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [x] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click to ...
...

The following problem occurs: [Screenshot?] 
Instead I would be expecting: 

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

**Comment by walnut1015** [comment]
I failed to execute the arangod.exe after installation.
using v3.1.19 on Win10 at the moment.
----------------------------------------------------------------
this is what happened:
E:\softwares\ArangoDB\ArangoDB3 3.1.19\usr\bin>arangod
2017-05-07T03:47:31Z [55020] FATAL {startup} cannot locate 'usr\share\arangodb3\icudtl.dat'; please make sure it is available; the variable ICU_DATA='' should point to the directory containing 'icudtl.dat'
------------------------------------------------------------------
I found the file icudtl.dat exists in that exact filepath.

**Comment by dothebart** [comment]
Will 
`E:\softwares\ArangoDB\ArangoDB3 3.1.19> .\usr\bin\arangod`
work?

**Comment by walnut1015** [comment]
No, the same fatal error happened when starting that arangod. 
E:\softwares\ArangoDB\ArangoDB3 3.1.19\usr\bin>arangod
2017-05-08T07:56:53Z [45896] FATAL {startup} cannot locate 'usr\share\arangodb3\icudtl.dat'; please make sure it is available; the variable ICU_DATA='' should point to the directory containing 'icudtl.dat'
------------------------------------------------------------------------------------------
I chose 3.0 version of arango, and it's working now. Thanks for your reply.
------------------------------------------------------------------------------------------
BTW, is Arango an abbr for some words? I'm curious about the behind meaning of its name.
------------------------------------------------------------------------------------------



1037332201@qq.com
 
From: Wilfried Goesgens
Date: 2017-05-08 15:49
To: arangodb/arangodb
CC: walnut1015; Author
Subject: Re: [arangodb/arangodb] cannot locate 'usr\share\arangodb 3\icudtl.dat' (#2472)
Will
E:\softwares\ArangoDB\ArangoDB3 3.1.19> .\usr\bin\arangod
work?

**Comment by dothebart** [comment]
I was talking about your working directory being `E:\softwares\ArangoDB\ArangoDB3 3.1.19> ` and you running `.\usr\bin\arangod` - sorry if I didn't make myself clear enough.

**Comment by walnut1015** [comment]
Yeah, that works. Thanks a lot :D
And may I know the meaning of Arango(is it some abbr)? I was asked about its meaning, but couldn't find any.
I'm sorry to be disturbing. 


1037332201@qq.com
 
From: Wilfried Goesgens
Date: 2017-05-08 16:00
To: arangodb/arangodb
CC: walnut1015; Author
Subject: Re: [arangodb/arangodb] cannot locate 'usr\share\arangodb 3\icudtl.dat' (#2472)
I was talking about your working directory being E:\softwares\ArangoDB\ArangoDB3 3.1.19> and you running .\usr\bin\arangod - sorry if I didn't make myself clear enough.

**Comment by dothebart** [comment]
Yea, for sure. 

Initially we had chosen the abbreviation for "Versatile Object Container" to become aVOCado DB, but [that name was already reserved by another company; So we renamed it to a cultivar of avocados.](https://www.arangodb.com/2012/05/avocadodb-become-arangodb/) The most prominent one which you can purchase everywhere is named "Hass" which means hate in german - so not a that good name ;-) So we had chosen the cultivar Arango from: https://www.quora.com/How-many-varieties-of-avocado-are-there-and-how-are-they-different

**Comment by walnut1015** [comment]
Is it possible for this database to export script file like MySQL database?

**Comment by dothebart** [comment]
you can use arangodump: https://docs.arangodb.com/3.1/Manual/Administration/Arangodump.html which creates a set of json / jsonl files for the dump, which you can also use for arangorestore. 

ArangoDB 3.2 brings the new ArangoExport tool: https://docs.arangodb.com/devel/Manual/Administration/Arangoexport.html which can create some more formats.
