### ISSUE TITLE
FATAL unable to create database directory 'start': Failed to create directory [start] Permission denied

### ISSUE THREAD

**Issue by milindkhurd** [arangodb/arangodb#2473]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [x ] 3.1
- [ ] 3.2 pre-releases: ___
- [ ] self-compiled devel branch

On this operating system:
- [ ] Linux 
  - [ ] Debian .deb
  - [x ] Ubuntu .deb
I was unable to login to Ubuntu (virtual machine) after I rebooted the host Windows machine from sleep so had to shutdown the Oracle VM. On start I am unable to start arangodb

FATAL unable to create database directory 'start': Failed to create directory [start] Permission denied

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

**Comment by dothebart** [comment]
You tried to run `/etc/init.d/arangodb3 start` ? 
or is this docker with host filesystem mounted? 
you should have a look at `/var/lib/arangodb3` and `/var/lib/arangodb3-apps` and check their ownership. 

You can adjust these using: 

    chown -R arangodb:arangodb /var/lib/arangodb3*

If you started ArangoDB once as root user it may have created files which it may not be allowed to access afterwards.

**Comment by milindkhurd** [comment]
/etc/init.d/arangodb3 start ?

Gave this in systemctl status arangodb3.service

May 08 09:11:52 newstack-VirtualBox systemd[1]: Starting LSB: arangodb...
May 08 09:11:52 newstack-VirtualBox arangodb3[5191]:  * Starting arango database server arangod
May 08 09:11:52 newstack-VirtualBox arangodb3[5191]:  * database version check failed, maybe you need to run 'upgrade'?
May 08 09:11:52 newstack-VirtualBox systemd[1]: arangodb3.service: Control process exited, code=exited status=1
May 08 09:11:52 newstack-VirtualBox systemd[1]: Failed to start LSB: arangodb.
May 08 09:11:52 newstack-VirtualBox systemd[1]: arangodb3.service: Unit entered failed state.
May 08 09:11:52 newstack-VirtualBox systemd[1]: arangodb3.service: Failed with result 'exit-code'.

chown -R arangodb:arangodb /var/lib/arangodb3* 
Is not allowed.

newstack@newstack-VirtualBox:/var/lib$ ls -l | grep arango
drwx------ 5 arangodb      arangodb      4096 May  8 09:11 arangodb3
drwx------ 3 arangodb      arangodb      4096 May  6 12:31 arangodb3-apps

I am okay to reset the collections etc. Please let me know how to start the database.

**Comment by dothebart** [comment]
can you try 

    /etc/init.d/arangodb3 upgrade

? 
For the chown you need to be root in advance, so either `su` to get a root shell, or `sudo` the chown command.

**Comment by milindkhurd** [comment]
newstack@newstack-VirtualBox:/var/lib$ sudo /etc/init.d/arangodb3 upgrade
[sudo] password for newstack: 
 * Upgrading arango database server arangod                                                                                         2017-05-08T16:01:09Z [5736] INFO ArangoDB 3.1.19 [linux] 64bit, using VPack 0.1.30, ICU 54.1, V8 5.0.71.39, OpenSSL 1.0.2g  1 Mar 2016
2017-05-08T16:01:09Z [5736] INFO file-descriptors (nofiles) hard limit is 131072, soft limit is 131072
2017-05-08T16:01:09Z [5736] ERROR error while opening database: Expecting item
2017-05-08T16:01:09Z [5736] FATAL cannot start database: Expecting item
                                                                                                                             [fail]

Sorry did not work. I am not sure how to become root on Ubuntu in advance. sudo and su did not work.

**Comment by milindkhurd** [comment]
I removed the /var/lib/arango* directories and reinstalled arangodb. It works now. This is a test env. and I want to explore the db more than troubleshooting my mistakes. Thanks for all the help

**Comment by wanghaiwin** [comment]
@dothebart hello, i am facing the same issue, could you tell me where is the database directory 'start'？Thanks for your feedback.

**Comment by bmacao** [comment]
I had this issue and just need to run the commands provided by dothebart :

sudo /etc/init.d/arangodb3 upgrade
sudo /etc/init.d/arangodb3 start

**Comment by EladComigo** [comment]
This also occurs on dockers where stating the --database.directory in yaml file fails with the same message
