### ISSUE TITLE
Iteration inside ternary operator block is not working

### ISSUE THREAD

**Issue by programmingprince** [arangodb/arangodb#2474]
I am using Arango db version 3.1.17 on Mac OS. I am trying to execute an AQL query via web interface. But I am facing a problem. The AQL query is:

let tasks = [{'name':'nirajan', 'arr':[1,2,3,4]},{'address':'bkt', 'msg':'hello'}]
for task in tasks
let t = task.name ? (for item in task.arr return item) : false
return t

But I am getting this error:
"Array expected as operand to for loop"

**Comment by jsteemann** [comment]
If a subquery is used as an operand in an expression, it will be executed before that expression.
For example:
```
LET x = y ? (subquery) : z
```
will be executed as
```
LET temp = subquery
LET x = y ? temp : z
```
This is an already known issue:
https://github.com/arangodb/arangodb/issues/1624#issuecomment-165873357

**Comment by dothebart** [comment]
The regular ArangoDB way to do this would be to `FILTER` using [HAS](https://docs.arangodb.com/3.2/AQL/Functions/Document.html#has).

```
LET tasks = [{'name':'nirajan', 'arr':[1,2,3,4]},{'address':'bkt', 'msg':'hello'}]
FOR task IN tasks
FILTER HAS(task, 'name')
   FOR item IN task.arr RETURN item
```
if you need a way to identify the documents with your `name` attribute in the output from those without, you can also add the `_key`, to the result and have it in there. 

Closing this question now.
