### ISSUE TITLE
Adding a collection breaks asynchronous replication

### ISSUE THREAD

**Issue by ThomasWeiss** [arangodb/arangodb#2483]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.1
On this operating system:
- [x] Linux 
  - [x] Ubuntu .deb

Steps to reproduce:
- run an asynchronous replication
- on the master instance, add a collection (in my case, it was through the setup script of a Foxx app)
- replication breaks with the error: `{replication} replication applier error for database '<db_name>': invalid response, offending marker: {"tick":"39717267","type":2000,"database":"230","cid":"39717266","cname":"<new_coll_name>","data":{"allowUserKeys":true,"cid":"39717266","count":0,"deleted":f`

**Comment by jsteemann** [comment]
Which version of 3.1 is that?
There should have been a fix for this since 3.1.19. Could you check if you are already on that version? Thanks!

**Comment by ThomasWeiss** [comment]
No I'm on 3.1.15, glad to know that there's a fix already, thanks!

**Comment by jsteemann** [comment]
It would be very helpful if you could try 3.1.19 or 3.1.20 and confirm that this fixes your case as well.
I'll re-open the issue until then so we don't forget about it.

**Comment by ThomasWeiss** [comment]
Sure, but that thing is in production so I won't update soon, maybe next week. I'll report the results here.

**Comment by ThomasWeiss** [comment]
Confirmed to work well with 3.1.21.
