### ISSUE TITLE
Database Selection empty after Update 3.1.18 -> 3.1.20

### ISSUE THREAD

**Issue by vlabmichl** [arangodb/arangodb#2486]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.1
- [x] Linux 
  - [x] Debian .deb

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [x] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

The following problem occurs: 
1) open the browser on http://127.0.0.1:8529
2) log in with my user
3) login successful
4) database selection is empty instead of 2 databases to select from

![arangodb empty database selection after successful login](https://cloud.githubusercontent.com/assets/877285/26191763/801ab950-3baf-11e7-9924-633ed00e3b3d.PNG)

I've updated the package via the standard `apt-get update` -> `apt-get upgrade` process from 3.1.18 to -> 3.1.20.

The Server starts / stops normally as shown in the logs:
`
2017-05-18T07:45:21Z [2587] INFO Starting up with role SINGLE
2017-05-18T07:45:21Z [2587] INFO Authentication is turned on
2017-05-18T07:45:21Z [2587] INFO Authentication system only
2017-05-18T07:45:21Z [2587] INFO Authentication for unix sockets is turned on
2017-05-18T07:45:21Z [2587] INFO file-descriptors (nofiles) hard limit is 131072, soft limit is 131072
2017-05-18T07:45:21Z [2587] INFO JavaScript using startup '/usr/share/arangodb3/js', application '/var/lib/arangodb3-apps'
2017-05-18T07:45:22Z [2587] INFO using endpoint 'http+tcp://0.0.0.0:8529' for non-encrypted requests
2017-05-18T07:45:22Z [2587] WARNING collection Assets already exists. Leaving it untouched.
2017-05-18T07:45:22Z [2587] WARNING collection Owners already exists. Leaving it untouched.
2017-05-18T07:45:22Z [2587] INFO ArangoDB (version 3.1.20 [linux]) is ready for business. Have fun!
`
Enabling class `debug` in the logging didn't tell me much more except that I see the tokens during the login / auth process.

Disabling the authorization in `/etc/arangodb3/arangod.conf` let me access my databases.

...so I know at least that the data is still here ;-)

**Comment by dothebart** [comment]
Hi, 
I've tried to reproduce this, and wasn't able to. 
could you log in as root to arangodb, and have a look at your `_users` collection and share it with us?
Could you eventually share your database directory?

**Comment by msukhov** [comment]
We have same issue, after updating from 3.1.17 to 3.1.19 on CentOS host.

**_users data:**
`
{"type":2300,"data":{"_id":"_users/15","_key":"15","_rev":"_UYdbhaq---","authData":{"active":true,"changePassword":false,"simple":{"hash":"b0a29af117b8648e538d69c690300473f8c6ee614662cfaf0ba763e9ebcf03db","method":"sha256","salt":"MbrE9v82Li9GccVG"}},"configData":{},"databases":{"*":"rw"},"user":"root","userData":{}}}
{"type":2302,"data":{"_key":"15","_rev":"_UYdb93C---"}}
{"type":2300,"data":{"_id":"_users/109","_key":"109","_rev":"_UYdb95G---","authData":{"active":true,"changePassword":false,"simple":{"hash":"ed556f13bc2b99b894ea1d0fcc139dae5879f05bd4398e62642c199a718a6992","method":"sha256","salt":"vOyMsSHe6yKfAmE9"}},"configData":{},"databases":{"*":"rw"},"user":"root","userData":{}}}
{"type":2302,"data":{"_key":"491","_rev":"_UYdgNFa---"}}
{"type":2302,"data":{"_key":"553","_rev":"_UYdgpEe---"}}
{"type":2300,"data":{"_id":"_users/654","_key":"654","_rev":"_UYdh02K---","authData":{"active":true,"changePassword":false,"simple":{"hash":"caffd1f9a9b3e163df8a9131109bcc3a6a2a02aa033e21edeeda17152725071a","method":"sha256","salt":"QLfnEX3G9MhhZOfB"}},"configData":{},"databases":{"doro":"rw"},"user":"dbuser","userData":{"name":""}}}
{"type":2300,"data":{"_id":"_users/109","_key":"109","_rev":"_UYdh02e---","authData":{"active":true,"changePassword":false,"simple":{"hash":"ed556f13bc2b99b894ea1d0fcc139dae5879f05bd4398e62642c199a718a6992","method":"sha256","salt":"vOyMsSHe6yKfAmE9"}},"configData":{},"databases":{"*":"rw","doro":"rw"},"user":"root","userData":{}}}
{"type":2302,"data":{"_key":"654","_rev":"_UYdl4ea---"}}
{"type":2300,"data":{"_id":"_users/1094","_key":"1094","_rev":"_UYdmgFe---","authData":{"active":true,"changePassword":false,"simple":{"hash":"5636fb438404184b30d7fb60cab20e8fc550c5223cc5b72af47d815dc94c5642","method":"sha256","salt":"82rbiRm7LBIy9STf"}},"configData":{},"databases":{"doro":"rw"},"user":"doro","userData":{"name":""}}}
{"type":2300,"data":{"_id":"_users/109","_key":"109","_rev":"_UYdmgFm---","authData":{"active":true,"changePassword":false,"simple":{"hash":"ed556f13bc2b99b894ea1d0fcc139dae5879f05bd4398e62642c199a718a6992","method":"sha256","salt":"vOyMsSHe6yKfAmE9"}},"configData":{},"databases":{"*":"rw","doro":"rw"},"user":"root","userData":{}}}
`

**_users struct:**
`
{"indexes":[{"fields":["user"],"id":"11","selectivityEstimate":1,"sparse":true,"type":"hash","unique":true}],"parameters":{"allowUserKeys":true,"cid":"7","count":2,"deleted":false,"distributeShardsLike":"_graphs","doCompact":true,"id":"7","indexBuckets":8,"indexes":[{"fields":["_key"],"id":"0","selectivityEstimate":1,"sparse":false,"type":"primary","unique":true},{"fields":["user"],"id":"11","selectivityEstimate":1,"sparse":true,"type":"hash","unique":true}],"isSystem":true,"isVolatile":false,"journalSize":4194304,"keyOptions":{"allowUserKeys":true,"type":"traditional"},"name":"_users","numberOfShards":1,"planId":"7","replicationFactor":1,"shardKeys":["user"],"shards":{},"status":4,"type":2,"version":6,"waitForSync":false}}
`

**Comment by msukhov** [comment]
One more point:
If I click **Select** button on screen above, admin panel forward me to `http://127.0.0.1:8529/_db/null/_admin/aardvark/index.html`

And than I can replace NULL to DATABASE_NAME, to select target database.

**Comment by hkernbach** [comment]
Hello. Thanks for the report. This was indeed a bug in the UI. It is now fixed and will be included in 3.1.21.

**Comment by weinberger** [comment]
Is there a workaround for time being?

**Comment by fceller** [comment]
3.1.21 is currently building and will be available 23.5.

**Comment by dothebart** [comment]
3.1.21 is available for download now containing this fix - Closing.

**Comment by vlabmichl** [comment]
works now thanks.
