### ISSUE TITLE
Feature request: letsencrypt

### ISSUE THREAD

**Issue by Thijxx** [arangodb/arangodb#2487]
## my environment running ArangoDB
3.2

On this operating system:
CentOS7

It would be nice to be able to use https://letsencrypt.org/ for SSL config. I am not convinced Arango supports any SSL config yet but at least is does not work with the generated pem files from letsencrypt. Probably because where you name a keyfile it should be a key & certificate file, including an extra option for cert file would be nice

**Comment by dothebart** [comment]
Is this by any chance a duplicate of #2077 ?

**Comment by Thijxx** [comment]
Yes, duplicate, thanks.

**Comment by caracal7** [comment]
Anybody solve this problem? How to use letsencrypt with Arango

**Comment by RienNeVaPlus** [comment]
For anybody stumbling upon this, I've created a short tutorial on [how to use Letsencrypt with ArangoDB](https://gist.github.com/RienNeVaPlus/b351f49adef9ebf5928f09299dbe26f1).
