### ISSUE TITLE
AQL operator IN error when data use base64 chars

### ISSUE THREAD

**Issue by blueperson** [arangodb/arangodb#2488]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [x] 3.1
- [ ] 3.2 pre-releases: ___
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ x] Linux 
  - [x] Debian .deb
  - [x] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:
```
For v in Base64 
  FILTER v.name IN ['WJIxaWBuRBMBMfRW', 'WKfgmGBuRBMBPgMR', 'WK5Mz2BuRBMBQT8y', 'WJIv_mBuRBMBMdgh', 'WMyo3HNG6AAGKOk5', 'WJItoWBuRBMBMajh', 'WMyn9nNG6AAGKN4Q', 'WMynsHNG6AAGKNqu', 'WJIwOWBuRBMBMdzC', 'WMu6iHNG6AAGJ-gY', 'WJIuWmBuRBMBMbdR', 'WMu7kXNG6AAGJ_Zc', 'WMu6jXNG6AAGJ-hd', 'WMyoSXNG6AAGKOIY', 'WJIxyGBuRBMBMfvK', 'WMyohHNG6AAGKOTx'] 
  return v
```
The issue can be reproduced using this dataset: 

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.
```
INSERT {"name": WJIxaWBuRBMBMfRW} IN Base64
INSERT {"name": WKfgmGBuRBMBPgMR} IN Base64
INSERT {"name": WK5Mz2BuRBMBQT8y} IN Base64
INSERT {"name": WJIv_mBuRBMBMdgh} IN Base64
INSERT {"name": WMyo3HNG6AAGKOk5} IN Base64
INSERT {"name": WJItoWBuRBMBMajh} IN Base64
INSERT {"name": WMyn9nNG6AAGKN4Q} IN Base64
INSERT {"name": WMynsHNG6AAGKNqu} IN Base64
INSERT {"name": WJIwOWBuRBMBMdzC} IN Base64
INSERT {"name": WMu6iHNG6AAGJ-gY} IN Base64
INSERT {"name": WJIuWmBuRBMBMbdR} IN Base64
INSERT {"name": WMu7kXNG6AAGJ_Zc} IN Base64
INSERT {"name": WMu6jXNG6AAGJ-hd} IN Base64
INSERT {"name": WMyoSXNG6AAGKOIY} IN Base64
INSERT {"name": WJIxyGBuRBMBMfvK} IN Base64
INSERT {"name": WMyohHNG6AAGKOTx} IN Base64
``` 
### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [x] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click to ...
...

The following problem occurs: [Screenshot?] 
![_007](https://cloud.githubusercontent.com/assets/3956446/26246719/1d4deed6-3ccd-11e7-8347-e6ee1d614257.png)
![_006](https://cloud.githubusercontent.com/assets/3956446/26246720/1d4e19c4-3ccd-11e7-95c9-3622ee63b89a.png)
Instead I would be expecting: 

16 lines data only return 15 lines results, when data become bigger, more lines will missing. We have 20000 lines data, but can only query 1000 results when use IN operator to filte result.

### this is an installation-related issue: 
Describe which steps you carried out, what you expected to happen and what actually happened.

**Comment by dothebart** [comment]
As you can see by above actions, the Issue was reproduced and fixed. 
The bugfix will be part of the Release 3.1.21.
If you want to retest it, you can try out the nightlies.

**Comment by dothebart** [comment]
3.1.21 is available for download now containing this fix - Closing.

**Comment by blueperson** [comment]
I have  upgrade to 3.1.21 and test OK. Thanks.
