### ISSUE TITLE
How to find which polygon contains a specific polygon?

### ISSUE THREAD

**Issue by VladimirShestakov** [arangodb/arangodb#2493]
How to find which polygon contains a specific polygon? Similar $geoWithin in mongodb.
If this function does not exist in arangodb have you a plan to add it?

**Comment by MrPieces** [comment]
You can work with points in ArangoDB and in the upcoming 3.2 release you will also be able to use a geo_cursor https://www.arangodb.com/roadmap/. We also started to implement a powerful geo library with which you can leverage a broad variety of geo functionalities like multi point, multi lines, polygons and multi polygons. Unfortunately no ETA on that yet

**Comment by kkdd** [comment]
I would like the Arangodb's future implementation of [r-tree](https://en.wikipedia.org/wiki/R-tree) which deals with geographic anti-meridian correctly.
For example, see [javascript-hilbert-r-tree](https://github.com/kkdd/javascript-hilbert-r-tree) or [Geographic Bounding Boxes](https://www.jasondavies.com/maps/bounds).

**Comment by Simran-B** [comment]
@VladimirShestakov @kkdd v3.4.0-RC.4 is out for testing and comes with more geo features: https://docs.arangodb.com/3.4/Manual/Highlights.html

**Comment by maxkernbach** [comment]
This feature is implemented by the [**GEO_CONTAINS()**](https://docs.arangodb.com/3.4/AQL/Functions/Geo.html#geocontains) function in 3.4.

> `GEO_CONTAINS(geoJsonA, geoJsonB) → bool`
>
> Checks whether the GeoJSON object `geoJsonA` fully contains `geoJsonB` (Every point in B is also in A). The object geoJsonA has to be of type `Polygon` or `MultiPolygon`, other types are not supported because containment is ill defined. This function can be optimized by a S2 based geospatial index.
>
> - geoJsonA (object): first GeoJSON object or coordinate array (in longitude, latitude order)
> - geoJsonB (object): second GeoJSON object or coordinate array (in longitude, latitude order)
>  - returns bool (bool): true when every point in B is also contained in A, false otherwise

Please find the latest release in the [download section](https://www.arangodb.com/download/).
