### ISSUE TITLE
Issue in opening Arangodb 3.1 console in windows environment 

### ISSUE THREAD

**Issue by kodetalkcom** [arangodb/arangodb#2494]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 3.1 : version 18, 19, 20

On this operating system:
- [ ] Windows, version: 10

I'm issuing AQL via:
- [ ] arangosh

The issue can be reproduced using this dataset:

arangosh.exe -- server.username root --server.password password --server.database databasename

![issue](https://cloud.githubusercontent.com/assets/13821346/26343615/54f4a1c8-3fba-11e7-896c-c204ff95821b.png)

**Comment by dothebart** [comment]
Hi, 
It can be workarounded by going two directories up, and invoking ./usr/bin/arangosh.exe

**Comment by kodetalkcom** [comment]
Thank you.

**Comment by dothebart** [comment]
We're pleased to anounce that ArangoDB 3.2 containing this is now available for download - Closing.
