### ISSUE TITLE
Pagination not working for Arangodb web console after open a collection

### ISSUE THREAD

**Issue by kodetalkcom** [arangodb/arangodb#2495]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 3.1 version 20

On this operating system:
- [ ] Windows, version: 10

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS: Windows 10

The issue can be reproduced using this dataset:

Create a new database and user. Add some collection add records in the collection.

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) Created a new database and added some collection in it. 
3) use database [test ] `testuser` [ ] other: 
4) On click of any collection which has nearly 1000 of record. I am trying navigate to 2nd or 3rd page, It's not working. Navigate to last and first is working fine.
...

The following problem occurs: [Screenshot?] 
Instead I would be expecting: Pagination : on click of any page should navigate to the page.

**Comment by dothebart** [comment]
Hi, 
We believe this is one of the issues fixed with 3.1.21, can you please upgrade and retry?

**Comment by hkernbach** [comment]
This is fixed. Confirmed through a slack community member.
