### ISSUE TITLE
Error: internal error (location: arangod/Aql/AqlValue.cpp:182). Please report this error to arangodb.com (while executing) (location: arangod/RestHandler/RestCursorHandler.cpp:155)

### ISSUE THREAD

**Issue by melisabok** [arangodb/arangodb#2498]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [X ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2 pre-releases: ___
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [X ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [ X] web interface with this browser:     running on this OS:
- [ ] arangosh
- [X ] this Driver: arangojs

I'm running this query:

```
    let notes = (for i in FULLTEXT(openreview_invitations, 'id', 'auai UAI 2017 prefix:Paper Submit Review')
        for n in openreview_notes
            filter n.invitation == i.id
            return n)
              
    for n in notes
        limit 1000, 1000
    return n
```

The results has 1091 documents but I want to paginate them:

- with not limit works ok
- with limit 0, 1000 works ok
- with limit 1000, 1000 fails.

**Comment by dothebart** [comment]
Hi, 
the `LIMIT` implementation has been broken and was fixed with the releases of ArangoDB 3.2.9 and ArangoDB 3.1.28. 

Marking as fixed.
