### ISSUE TITLE
the AQL don't auto-delete the edges when delete a vertex

### ISSUE THREAD

**Issue by guanxudong** [arangodb/arangodb#2501]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [x] 3.1 (3.1.19)
- [ ] 3.2 pre-releases: ___
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [x] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[x] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `REMOVE {_key: 'alice'} IN persons` and the edges not removed automatically

The issue can be reproduced using this dataset:
  **Examples Knows Graph**

**Comment by dothebart** [comment]
Hi, 
you're using an AQL document function to manipulate the graph data - its not supposed to do additional graph manipulation.
Please use https://docs.arangodb.com/3.1/HTTP/Gharial/Vertices.html#remove-a-vertex via your client driver to delete graph content, it will also take care of edges pointing to this vertex.

Read about using document functions (as you did) on graph data here: https://docs.arangodb.com/3.1/Manual/Graphs/#manipulating-collections-of-named-graphs-with-regular-document-functions

**Comment by guanxudong** [comment]
> These guarantees are lost if you access the collections in any other way than the graph module or **AQL**, so if you delete documents from your vertex collections directly, the edges pointing to them will be remain in place. 

@dothebart Thank you for your kindly reply :)
 but it seems that i has misunderstand this line above? 
AQL can not hold those guarantees ? or how to  remove a vertex from the graph via AQL correctly?

**Comment by dothebart** [comment]
Have a look at my stackoverflow answer about howto achieve this: https://stackoverflow.com/questions/35074545/safe-removal-of-vertexes-in-arangodb-using-ids/35086601#35086601 - However - yes, there is currently no simlpe operation in AQL for that.

**Comment by guanxudong** [comment]
Got it ! Thank you very much~
