### ISSUE TITLE
Problem with export + report of a bug

### ISSUE THREAD

**Issue by StefanoMartin** [arangodb/arangodb#2505]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [X] 3.1
- [ ] 3.2 pre-releases: ___
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [X] Windows, version: 10
- [ ] MacOS, version:

### This is an HTML API-related issue:

I am working to make ArangoRB, a Ruby gem for the ArangoDB HTTP API, compatible with ArangoDB 3.1.21 (it was compatible with ArangoDB 3.0). However I have a problem with exporting the files from a database.
In my case I have a Collection "MyCollection" in a database "MyDatabase" (not _system or cluster). This Collection is populated with some Documents.

However by using:
POST /_db/MyDatabase/_api/export?collection=MyCollection
with an empty body {} or with body {"batchSize": 3} I receive the following json 
{"error"=>false, "code"=>201, "result"=>[], "hasMore"=>false}
Like if the Collection is empty. Why does it happen so?

Note that 
PUT /_db/MyDatabase/_api/simple/all
with body = {"collection": "MyCollection"}
returns the documents correctly.

### Bug found with HTML API

By doing the following request:
PUT /_admin/wal/properties
with an empty body {}.

I receive the following error:
{"error"=>true, "errorMessage"=>"VPack error: Expecting Object (exception location: C:\\b\\workspace\\RELEASE__BuildPackages\\arangod\\GeneralServer\\RestHandler.cpp:191). Please report this error to arangodb.com", "code"=>500, "errorNum"=>4}

**Comment by jsteemann** [comment]
Re the latter error message for PUT /_admin/wal/properties:
I think it works correctly if you send an empty object in the HTTP body:
```
$ curl -X PUT http://127.0.0.1:8529/_admin/wal/properties --data '{}'; echo
{"allowOversizeEntries":true,"logfileSize":33554432,"historicLogfiles":10,"reserveLogfiles":3,"syncInterval":100,"throttleWait":15000,"throttleWhenPending":0}
```
It will throw an error when no body is sent at all, or an empty string is sent as the body:
```
$ curl -X PUT http://127.0.0.1:8529/_admin/wal/properties; echo
{"error":true,"errorMessage":"VPack error: Expecting Object (exception location: /home/steemann/Arango31NoAsan/arangod/GeneralServer/RestHandler.cpp:191). Please report this error to arangodb.com","code":500,"errorNum":4}
```
I have pushed a fix so that it reports a proper error message in this case.

Re the missing documents in the export:
This is documented behavior (https://docs.arangodb.com/3.1/HTTP/Export/).

> if set to *true*, a WAL flush operation will be executed prior to the export. The flush operation will start copying documents from the WAL to the collection's datafiles. There will be an additional wait time of up to *flushWait* seconds after the flush to allow the WAL collector to change the adjusted document meta-data to point into the datafiles, too. The default value is *false* (i.e. no flush) so most recently inserted or updated documents from the collection might be missing in the export.

**Comment by dothebart** [comment]
ArangoDB Version 3.1.22 containing this fix is available for download - closing.
