### ISSUE TITLE
Arango Web Admin - Save button on edit document screen becomes unresponsive

### ISSUE THREAD

**Issue by gamedev8** [arangodb/arangodb#2508]
Arango version 3.1.20
Google Chrome   
Mint Linux

These are the steps to reproduce:
1) Open the browser on http://127.0.0.1:8529
2) Log in
3) Click on one of your collections
4) Click on one of your documents
5) Make edits then press save
6) Go back to step 3 or 4 (The point is to navigate away from this screen and get back into it)

The save button will only work the first time. It seems there is some jQuery code that does not run when you come back to the edit document screen.

**Comment by hkernbach** [comment]
Hello. Thanks for the feedback. This should be already fixed in 3.1.21. Could you verify?

**Comment by gamedev8** [comment]
The issue does not appear to happen on version 3.1.21
