### ISSUE TITLE
Arango Web Admin - Editing documents eventually crashes your browser tab

### ISSUE THREAD

**Issue by gamedev8** [arangodb/arangodb#2509]
Arango version 3.1.20
Google Chrome   
Mint Linux

These are the steps to reproduce:
1) Open the browser on http://127.0.0.1:8529
2) Log in
3) Click on one of your collections
4) Click on one of your documents
5) Make edits if you wish
6) Go back to step 3 or 4 (The point is to navigate away from this screen and get back into it)

Eventually all your ArangoDB browser tabs will crash. It seems each time u edit a document a new thread is spawned. When I get up to 55 threads then all my ArangoDB tabs crash.

**Comment by hkernbach** [comment]
Thanks for the report. The ace editor instance within the JSON editor was not cleaned up properly. Updated the JSON editor library and added a mechanism to clean up the instance. Also added this to the query editors.

**Comment by dothebart** [comment]
ArangoDB Version 3.1.22 containing this fix is available for download - closing.
