### ISSUE TITLE
collection info empty / does not show correct values in cluster environment

### ISSUE THREAD

**Issue by fdsg-tk** [arangodb/arangodb#2510]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [X ] 3.1
- [ ] 3.2 pre-releases: ___
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ X] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [X ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [X] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [X] other: pasdb
4) click to "Collections"
5) click to {any collection}
6 click to "Info"

The following problem occurs: 
![collection_info](https://cloud.githubusercontent.com/assets/27819640/26582562/fe3610fa-4541-11e7-99a0-559bbd3fc0b2.png)

Instead I would be expecting: 
Detailed Information about collection items (Collection contains > 50.000 documents)

**Comment by hkernbach** [comment]
Hi, thanks for the report. The figures behaviour in a cluster environment is a bit different here. The write-ahead Log ([wal](https://docs.arangodb.com/3.1/Manual/Architecture/WriteAheadLog.html)) in a single instance server is flushed more often than in a cluster environment. Only after a wal flush the figures data builds up. The more operations are performed on the server, the faster the wal log is flushed. That is the reason why all of those statistics seems to be "wrong".  We'll change the view a bit to prevent confusion. 

Do I guess correctly that your cluster might be in a very fresh state at the time you opened up the ticket?

**Comment by hkernbach** [comment]
Optimized view in 3.1 and devel branch.

**Comment by fdsg-tk** [comment]
Great news! :-)

..and yes: the cluster was just loaded with new data, when we took a look into the collection statistics.
So this change might really fix the issue.

Thanks a lot!

**Comment by dothebart** [comment]
ArangoDB Version 3.1.22 containing this fix is available for download - closing.
