### ISSUE TITLE
When editing a document, at some point, save will stop working

### ISSUE THREAD

**Issue by grexe** [arangodb/arangodb#2512]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [X] 3.1
- [ ] 3.2 pre-releases: ___
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [X] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [X] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [X] web interface with this browser: Chrome  58.0.3029.110 (64-bit)    running on this OS: Kubuntu 16.10 x64
- [ ] arangosh
- [ ] this Driver:

These are the steps to reproduce:
1. open the browser on http://127.0.0.1:8529
1. log in as root, connect to a demo database, does not matter which
1. edit a document
1. go back, browse other collections, not sure what is causing the issue, but repeated browsing and editing helps reproducing it
1. at some point, you can still edit documents, but saving does nothing, no error, no "saved" message appears.

**Comment by hkernbach** [comment]
Hello. What version are you using? This should be resolved in 3.1.21.

**Comment by hkernbach** [comment]
Closing. Duplicate: #2508

**Comment by grexe** [comment]
oops sorry didn't spot the original issue, and I was not using the latest patch (didn't see this was fixed in the changelog), will update and check, thanks!
