### ISSUE TITLE
The replace-or-with-in optimization rule might prevent use of indexes

### ISSUE THREAD

**Issue by pmakholm** [arangodb/arangodb#2515]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [x ] 3.1
- [ ] 3.2 pre-releases: ___
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [x] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
I'm issuing AQL via:
- [x] web interface with this browser:     running on this OS:
- [x] arangosh
- [ ] this Driver:

My query looks roughly like this

```
FOR doc1 IN collection1
    LET name = My::SomeFunction(doc1.name)
    FOR doc2 IN collection2
        FILTER doc2.name == name OR doc2.altname == name
        RETURN doc2
```

Based on the "Index Utilization" section of the manual I expect this to use indexes on both the name and altname field of collection2.  I've run `db._explain("<my aql query>")` and it shows that the `replace-or-with-in` optimization rule is used, but no indexes.

Explicitly disabling the `replace-or-with-in` rule gives a plan that uses indexes as expected.

**Comment by jsteemann** [comment]
Fixed in devel/3.2.

**Comment by jsteemann** [comment]
Execution plan for the above query in 3.2/devel is now:
```
Query string:
 FOR doc1 IN collection1     LET name = My::SomeFunction(doc1.name)     FOR doc2 IN collection2       
   FILTER doc2.name == name OR doc2.altname == name         RETURN doc2

Execution plan:
 Id   NodeType                  Est.   Comment
  1   SingletonNode                1   * ROOT
  2   EnumerateCollectionNode      0     - FOR doc1 IN collection1   /* full collection scan */
  3   CalculationNode              0       - LET name = MY::SOMEFUNCTION(doc1.`name`)   /* user-defined function */   /* v8 expression */   /* collections used: doc1 : collection1 */
  8   IndexNode                    0       - FOR doc2 IN collection2   /* hash index scan */
  5   CalculationNode              0         - LET #3 = ((doc2.`name` == name) || (doc2.`altname` == name))   /* simple expression */   /* collections used: doc2 : collection2 */
  6   FilterNode                   0         - FILTER #3
  7   ReturnNode                   0         - RETURN doc2

Indexes used:
 By   Type   Collection    Unique   Sparse   Selectivity   Fields          Ranges
  8   hash   collection2   false    false       100.00 %   [ `name` ]      (doc2.`name` == name)
  8   hash   collection2   false    false       100.00 %   [ `altname` ]   (doc2.`altname` == name)

Optimization rules applied:
 Id   RuleName
  1   use-indexes
```

**Comment by dothebart** [comment]
3.2.beta1 containing this fix is available for download. - Closing.
