### ISSUE TITLE
cursor not found in interation with next()

### ISSUE THREAD

**Issue by blaspheme** [arangodb/arangodb#2516]
the number of v and e are over millions.

## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ x ] 3.1.21

On this operating system:
- [ x ]:Docker for windows

### this is an AQL-related issue:
[ x ] I'm using graph features

I'm issuing AQL via:
- [ x ] arangosh

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:
when i interate the collection of edgecollection,the code like this:
```javascript
q1 = db._collection(VritelName).all();
while (q1.hasNext()) {
  v=q1.next(); 
}
```
then it will tell me that "stacktrace: ArangoError: cursor not found" in `q1.next()`

**Comment by dothebart** [comment]
Hi, 
ArangoDB 3.1.28 is available for download; can you please upgrade and verify whether the issue persists?
If, can you give a little more insight about the number of documents you're querying and their size?

**Comment by blaspheme** [comment]
I am sorry,guys.
Maybe i can't provide more information about it because i still realize the function of graph by relational database for the question of this.

**Comment by dothebart** [comment]
For understanding the graphs concempts, please have a look at: https://docs.arangodb.com/3.2/Manual/Graphs/
The version you claim to be using is pretty old. Please use the latest available - 3.2.8 and retest.

**Comment by vinaypyati** [comment]
Hi @blaspheme 

Did you have a chance to test this issue on the latest version? Looking forward to your feedback. 

Thanks

**Comment by maxkernbach** [comment]
I am closing this issue for now as we have not received any feedback for a few months.
Please feel free to comment and reopen in case this problem persists using the latest version.
