### ISSUE TITLE
Document Inheritance

### ISSUE THREAD

**Issue by francnuec** [arangodb/arangodb#2522]
I love Arangodb, but this inheritance thing is not going great for me. Is there a more straightforward way than the one presented in the cookbook (that uses edges and foxx models)?

I think this needs to be handled by the db itself with little input from the user. Neo4j and OrientDB, your two competitors in graph, already do.

So is this something actively planned for a near release? Or can you point me in the right direction of something simple and no-brainer. 

I use Arango through the arangoclient for .net framework by the way.

**Comment by dothebart** [comment]
as explained in https://github.com/arangodb/arangodb/issues/1913 this will not be supported, and can only be done through data model conversion.
