### ISSUE TITLE
POST /_api/import (HTTP with vpack content) can not handle param type=auto

### ISSUE THREAD

**Issue by mpv1989** [arangodb/arangodb#2524]
The API [POST /_api/import](https://docs.arangodb.com/devel/HTTP/BulkImports/ImportingSelfContained.html) can not handle VelocyPack Array of Objects when send over HTTP if the query parameter `type` has the value `auto`. The same works for VelocyStream and Json over HTTP. When you change `auto` to `list` it works as expected.

## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] self-compiled devel branch

These are the steps to reproduce:
1) Start an local ArangoDB under port 8529
2) Clone Java driver
`git clone https://github.com/arangodb/arangodb-java-driver.git -b 4.2 ; cd arangodb-java-driver`
3) Run tests
`mvn test -Dtest=ArangoCollectionTest`

**Comment by dothebart** [comment]
ArangoDB 3.2 has been Released - Closing.
