### ISSUE TITLE
GET /_api/database/current (HTTP with vpack content) returns invalid vpack

### ISSUE THREAD

**Issue by mpv1989** [arangodb/arangodb#2525]
The API [GET /_api/database/current](https://docs.arangodb.com/devel/HTTP/Database/DatabaseManagement.html#information-of-the-database) when send VelocyPack over HTTP returns an invalid VelocyPack in the response body if the database does not exists.

## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] self-compiled devel branch

These are the steps to reproduce:
1) Start an local ArangoDB under port 8529
2) Clone Java driver
`git clone https://github.com/arangodb/arangodb-java-driver.git -b 4.2 ; cd arangodb-java-driver`
3) Run tests
`mvn test -Dtest=ArangoDBTest`

**Comment by ObiWahn** [comment]
should be fixed in https://github.com/arangodb/arangodb/tree/bug-fix/issue-2525

**Comment by dothebart** [comment]
ArangoDB 3.2 has been Released - Closing.
