### ISSUE TITLE
Asynchronous replication failure with deadlock

### ISSUE THREAD

**Issue by ThomasWeiss** [arangodb/arangodb#2528]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.1

On this operating system:
- [x] Linux 
  - [x] Ubuntu .deb

Using 3.1.21, I've a secondary database asynchronously replicating the primary and serving reads only - **no writes**.

The replication sometimes fails with the message:

    Info 2017-05-31 17:00:28 {replication} stopped replication applier for database 'xxx'
    Error 2017-05-31 17:00:28 {replication} replication applier error for database 'xxx': document insert/replace operation failed: deadlock detected, offending marker: {"tick":"48520755","type":2300,"tid":"48520743","database":"230","cid":"27023655","cname":"isSharedWith","data":{"

No deadlock seen on the primary.

How could the replication create a deadlock considering that it should just apply the changes sequentially?

**Comment by ThomasWeiss** [comment]
- Could it come from a conflict between writes from the replication and reads from incoming queries?
- If so, would it rather come from undeclared / lazily discovered collections from the the queries, or implicit (again, undeclared) read collections from transactions being replicated?

**Comment by ThomasWeiss** [comment]
So following the information provided by the offending tick and my application's logging:
1. the tick corresponds to the insert/update of a document
2. that document was updated within a transaction at the time when the replication failed
3. and at the very same time, a query fetching the very same document happened

The query from step 3 does declare the collections it accesses with a `WITH` clause, so even though I'm getting more data, I still don't understand what's the problem.

**Comment by dothebart** [comment]
We worked a bit on this topic, and the results will become available with 3.2.4 (already available in the nightly builds) Maybe we can check back whether your issue is resolved with this?

**Comment by ThomasWeiss** [comment]
Sure, in the meantime we've a CRON job that checks the replication states and relaunches it if it has failed. We will upgrade to 3.2 anyway. Thanks

**Comment by dothebart** [comment]
Ok, @thomaskarlrichter since you don't appear to have ad this issue meanwhile I think we can close this?
Please report back if not.

**Comment by dothebart** [comment]
ok, @ThomasWeiss since you don't seem to have had this issue again i think we can close this now.
How did the github autocomplete feature dig out that wrong thomas?

**Comment by ThomasWeiss** [comment]
Well, the issue was still existing on 3.1.21 when we migrated to 3.2 so I can't say that it doesn't exist anymore on 3.1.{latest}.
Asynchronous replication on RocksDB was broken until 3.2.7, and 3.2.7 has not been running for long enough on our systems to declare it fixed (although it's looking good).

**Comment by maxkernbach** [comment]
Hi @ThomasWeiss,

is your issue resolved with using 3.2.7?

**Comment by ThomasWeiss** [comment]
Asynchronous replication still seems broken in 3.2.9 but it's not the same symptoms and probably not the same root cause, so yes I guess we can close this issue.
