### ISSUE TITLE
Compile Arango for ARM

### ISSUE THREAD

**Issue by 007huangliang** [arangodb/arangodb#2537]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [~] 2.8
- [ ] 3.0
- [ ~] 3.1
- [ ] 3.2 pre-releases: ___
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [~ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an installation-related issue:
Is there any guideline on how to cross compile arango DB for Arm Linux

**Comment by dothebart** [comment]
our community member @servusoft did created docker containers containing the cross compilation toolchain:

https://github.com/arangodb-helper/build-docker-containers/blob/master/readme_ARM.md

Please note that ARM is currently not supported by the ArangoDB team.

**Comment by 007huangliang** [comment]
Thank you very much!
