### ISSUE TITLE
Arangodb is crashing and web interface hangs in mac for high write operations

### ISSUE THREAD

**Issue by ashutosh-akss** [arangodb/arangodb#2543]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series: 3.1
On this operating system:- MacOS, Sierra:
I'm issuing AQL via: go-driver

I am writing to arangod using cursors in a for loop , arangodb is crashing within seconds of running loop and requires restart to gain access to web interface

I  get following error message

```
invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x5a6e7]

goroutine 1 [running]:
panic(0x3031e0, 0xc42000c0b0)
        /usr/local/Cellar/go/1.7/libexec/src/runtime/panic.go:500 +0x1a1
_/Users/ashutosh/seoscheduler/src/nodeCreator.CreateRoute(0xcb, 0xc420113a65, 0x5, 0xc420113a60, 0x20, 0xc420223340, 0x1, 0x4)
        /Users/ashutosh/seoscheduler/src/nodeCreator/createRoutes.go:82 +0x777
_/Users/ashutosh/seoscheduler/src/nodeCreator.makeNode(0xcb, 0xc420113a65, 0x5, 0xc420113a60, 0x20)
        /Users/ashutosh/seoscheduler/src/nodeCreator/nodeCreator.go:63 +0x2cd
_/Users/ashutosh/seoscheduler/src/nodeCreator.Process()
        /Users/ashutosh/seoscheduler/src/nodeCreator/nodeCreator.go:48 +0x389
main.main()
        /Users/ashutosh/seoscheduler/main.go:162 +0xa4
exit status 2
 ```

I am evaluating Arango & Orient for out new project where we will have high read and writes, wanted to chek if arango will fit out needs for high write operations.

Many Thanks!

**Comment by baslr** [comment]
@ashutosh-akss this is not a arangod crash but your go program.

**Comment by ashutosh-akss** [comment]
@baslr Thanks for response i figured out that the issue was because of ulimit of my mac , increased ulimit and it works now

Thanks!
