### ISSUE TITLE
Duplicate _key generated on insertion

### ISSUE THREAD

**Issue by lewisdiamond** [arangodb/arangodb#2559]
3.1.22
Docker :latest

When inserting into an edge collection, I get "Unique constraint violated" about 80% of the time. If I just keep trying to insert the same document over and over, it'll eventually go in. 

Indexes
```
0	primary	true	false	100.00%	_key	
1	edge	false	false	0.85%	_from, _to
```
Inserting
```
{
   "_from": "session/1",
   "_to" : "item/1"
}
```

I clicked "Create" 8 times before it went in.

**Comment by jsteemann** [comment]
I tried to reproduce this but without success yet. So I would like to know how exactly the error can be reproduced or at least where to look for potential races for key generation.

It seems you are using the web interface. 
I guess you clicked on the "+" icon to add a new edge and then filled out two initial fields ("_from" and "_to") and left the third ("_key") empty.
Does the error then occur when clicking the "Create" button?

That's what I tried and it worked for me. Or are you using some completely different way to add the edges?
Is that a single instance (I guess) or a cluster setup?
Thanks!

**Comment by lewisdiamond** [comment]
I reproduced the issue using the web interface, but initially that happened when doing AQL upserts. It basically happens every time I try to insert something in that specific edge collection, I can't reproduce in another collection. Do you want me to email you the collection data?

In the web interface, I did use the steps you describe and yes, it happens when pressing the "Create" button. 

My setup is a single server, no cluster.

**Comment by jsteemann** [comment]
If you don't mind sending the data, that would be very helpful! Thanks a lot!

**Comment by lewisdiamond** [comment]
I've just sent the data.

**Comment by jsteemann** [comment]
Arrival confirmed. Thanks!

**Comment by akki** [comment]
I also have hit this issue multiple times while inserting data.
I insert data via a Python script (using [`python-arango`](https://github.com/joowani/python-arango) driver) in bulk (using `bulk_import` function).
I have put no unique constraints in any of my collection - so any unique constraints that are there in my collections have been created by ArangoDB itself (i.e. primary indexes AFAIK).

**Comment by jsteemann** [comment]
@akki @lewisdiamond : is it possible that you are mixing inserts of documents with the `_key` attribute defined with inserts of documents for which no `_key` is defined?
I think the problem can occur if documents get inserted for which no `_key` is set so the key is auto-generated, but if there are already documents in the collection for which `_key` was explicitly set to some value that the auto-generate function may also produce. At least that may be possible. I am not sure if it explains the problems you are seeing. I'll investigate further.

**Comment by akki** [comment]
Yes, that is definitely possible in my case but on a database level i.e. in some collections I specify the key and in others I don't.

After I prepare all the documents that are to be inserted in ArangoDB (I am porting data from MongoDB) I insert them in bulk in the various collections using `collection1.import_bulk(list_of_documents_for_collection1)` via a Python script.

**Comment by lewisdiamond** [comment]
@jsteemann No I don't specify keys in that collection.

It's worth noting that this collection has been created prior to Arangodb 3.0

**Comment by jsteemann** [comment]
I have created a pull request (https://github.com/arangodb/arangodb/pull/2592) that hopefully addresses this issue. I intentionally wrote "hopefully" as I have only been able to reproduce the problem when mixing inserts that auto-generate keys with inserts in which I explicitly specified keys that may conflict with the auto-generated ones.
I'd be happy if you could try out the patch/PR and check if it fixes the problem with your data.
Thanks!

**Comment by jsteemann** [comment]
A potential fix for this is contained in ArangoDB 3.1.23.

**Comment by lewisdiamond** [comment]
I will test tomorrow. Thanks

**Comment by dothebart** [comment]
3.1.23 is available for download now. 
Closing - if it doesn't work out, please comment so we can reopen this.
