### ISSUE TITLE
res.throw() does not update res.statusCode

### ISSUE THREAD

**Issue by JP-Dhabolt** [arangodb/arangodb#2586]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [x] 3.1.21
- [ ] 3.2 Beta1
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [x] other: CentOS
- [ ] Windows, version: 
- [ ] MacOS, version:

### Foxx

These are the steps to reproduce:

1) With a simple logging middleware, such as
```
module.context.use( function (req, res, next) {
   try {
      next();
   } finally {
      console.info(`${res.statusCode}`);
   }
});
```
2) And code within the handler that calls `res.throw(404, 'Could not find foo');`

The following problem occurs: 
The logger will record the statusCode as `undefined`.
The response back to the requester is correct with `res.throw()`, but the statusCode available to the middleware is not.

Instead I would be expecting:
The logger will record the statusCode as `404`, such as when a call is made to `res.status(404);`
(This works correctly).

**Comment by mpv1989** [comment]
The described behavior is expected. `res.throws()` only throws an exception. Only when this exception is not handled by the request handler or any middleware it reachs the surrounding foxx logic where the response is updated. Your middleware is executed before the exception is handled by foxx, so the response is not updated at this time.
```
foxx: try {
  -> middleware1
    -> middlewareN
      -> request handler
} catch(e) {
  updateResponse(e)
}
```
This mechanic is required to allow users to handle exceptions by their own services.

If you want to handle exceptions in your middleware, you have to `catch` them in the middleware and update the response at your own.

**Comment by dothebart** [comment]
We're pleased to anounce that ArangoDB 3.2, containing many improvements to Foxx, is now available for download - Closing.
