### ISSUE TITLE
The documentation is a little off: crypto.checkAndMarkNonce returns boolean

### ISSUE THREAD

**Issue by artjomb** [arangodb/arangodb#2597]
The file arangodb/Documentation/Books/Manual/Appendix/JavaScriptModules/Crypto.md contains the documentation for [crypto.checkAndMarkNonce](https://docs.arangodb.com/3.1/Manual/Appendix/JavaScriptModules/Crypto.html#checkandmarknonce) which does not match the underlying native code as seen in https://github.com/arangodb/arangodb/blob/3.1/lib/Basics/Nonce.cpp. 

The correct documentation would be something like (the glue code in v8-utils.cpp passes the result on):

### createNonce

`crypto.createNonce(): string`

Creates a random cryptographic nonce consisting of 32 bits for a timestamp and 64 bits of randomness.

Returns the created nonce.

### checkAndMarkNonce

`crypto.checkAndMarkNonce(nonce): boolean`

Checks and marks a nonce. 

**Arguments**

* **nonce**: `string`

  The nonce to check and mark.

Returns `true` if the nonce was not seen before and stores the nonce for when it is might be used again.

**Comment by skinneejoe** [comment]
Also, can the devs comment a little bit more in the documentation how the checkAndMarkNonce function works? Does it store previously seen nonce' in memory? Do the nonce' have any expiration period?

**Comment by OmarAyo** [comment]
Hi @artjomb,

This ticket is being closed as inactive due to the date of the last activity on it.

If you believe this was done in error, please comment or create a new issue.
