### ISSUE TITLE
How we upload video in arangoDB using foxx services?

### ISSUE THREAD

**Issue by rajendra1502** [arangodb/arangodb#2615]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 3.1

On this operating system:
- [ ] Windows, version: 

### this is an AQL-related issue:
[ ] I'm using graph features

**Comment by pluma** [comment]
It's unclear what you're asking. Could you provide more information?

We generally discourage uploading files to Foxx services or ArangoDB as there are more specialised services that handle file uploads better (e.g. AWS S3). Storing large files like videos in the database is certainly possible but probably not the best option.

If you really do want to store your files in ArangoDB you have two options:

1. Write the files to the filesystem (outside the service directory). Doing this in a cluster will result in inconsistent local state between coordinators as the filesystem will not be synced, but it may be a good solution for rapid prototyping in single-server applications.

2. Write the files to collections as base64-encoded strings. This works well for smaller attachments like thumbnails but keep in mind that this will affect the collection size, resulting in more memory use. Also keep in mind that base64 encoding further increases file size so plan ahead accordingly.

For production environments the best option is probably having a separate server handle the file uploads and only sending the metadata to ArangoDB. This avoids putting unnecessary load on the database while allowing you to integrate with any file server or 3rd party storage provider.

**Comment by dothebart** [comment]
Closing as answered.
