### ISSUE TITLE
Steps missing from documentation when switching to RocksDB engine

### ISSUE THREAD

**Issue by danmactough** [arangodb/arangodb#2636]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [x] 3.2 Beta2
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [ ] Debian .deb
  - [x] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

#### What I did

I wanted to try the 3.2 beta with RocksDB as the storage engine, so I created a new AWS EC2 instance using the 3.1 AWS Marketplace AMI then followed the steps outlines in your [Pluggable Storage Engine: Compare RocksDB & MMFiles engine](https://www.arangodb.com/why-arangodb/storage-engine-comparison-rocksdb/) page to switch to the RocksDB storage engine:

- stopped the existing instance
- modify the configuration file
    - adjust the value of “storage-engine” in section “[server]” from “mmfiles” to “rocksdb”
    - change value of “directory” in section “[database]” from “/var/lib/arangodb3” to “/var/lib/arangodb3-rocksdb”
- create the new directory and make the arangodb user own it
- restart the ArangoDB server with the “rocksdb” engine

#### What I expected to happen

The ArangoDB server should successfully restart with the RocksDB engine.

#### What actually happened

I received an error:

```
ubuntu@ip-172-17-2-143:~$ sudo service arangodb3 start
Job for arangodb3.service failed because the control process exited with error code. See "systemctl status arangodb3.service" and "journalctl -xe" for details.
ubuntu@ip-172-17-2-143:~$ sudo systemctl status arangodb3.service
● arangodb3.service - LSB: arangodb
   Loaded: loaded (/etc/init.d/arangodb3; bad; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2017-06-21 15:40:51 UTC; 13s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 10122 ExecStop=/etc/init.d/arangodb3 stop (code=exited, status=0/SUCCESS)
  Process: 10175 ExecStart=/etc/init.d/arangodb3 start (code=exited, status=1/FAILURE)

Jun 21 15:40:51 ip-172-17-2-143 systemd[1]: Starting LSB: arangodb...
Jun 21 15:40:51 ip-172-17-2-143 arangodb3[10175]:  * Starting arango database server arangod
Jun 21 15:40:51 ip-172-17-2-143 arangodb3[10175]:  * database version check failed, maybe you need to run 'upgrade'?
Jun 21 15:40:51 ip-172-17-2-143 systemd[1]: arangodb3.service: Control process exited, code=exited status=1
Jun 21 15:40:51 ip-172-17-2-143 systemd[1]: Failed to start LSB: arangodb.
Jun 21 15:40:51 ip-172-17-2-143 systemd[1]: arangodb3.service: Unit entered failed state.
Jun 21 15:40:51 ip-172-17-2-143 systemd[1]: arangodb3.service: Failed with result 'exit-code'.
```

This tells me I need to run `sudo service arangodb3 upgrade`, so I try that and receive a new error:

```
ubuntu@ip-172-17-2-143:~$ sudo service arangodb3 upgrade
 * Upgrading arango database server arangod
2017-06-21T15:44:12Z [10237] FATAL {startup} content of 'ENGINE' file '/vol/data/standalone/ENGINE' and command-line/configuration option value do not match: 'mmfiles' != 'rocksdb'. please validate the command-line/configuration option value of '--server.storage-engine' or use a different database directory if the change is intentional
```

#### Resolution

I removed the file `/vol/data/standalone/ENGINE`, ran the upgrade, then restarted the service:

```
ubuntu@ip-172-17-2-143:~$ sudo rm /vol/data/standalone/ENGINE
ubuntu@ip-172-17-2-143:~$ sudo service arangodb3 upgrade
 * Upgrading arango database server arangod
2017-06-21T17:52:35Z [11173] INFO using storage engine rocksdb
2017-06-21T17:52:35Z [11173] INFO {syscall} file-descriptors (nofiles) hard limit is 131072, soft limit is 131072
2017-06-21T17:52:36Z [11173] INFO database upgrade passed
2017-06-21T17:52:36Z [11173] INFO using endpoint 'http+tcp://0.0.0.0:8529' for non-encrypted requests
2017-06-21T17:52:36Z [11173] INFO You are using a milestone/alpha/beta/preview version ('3.2.beta2') of ArangoDB
2017-06-21T17:52:36Z [11173] INFO ArangoDB (version 3.2.beta2 [linux]) is ready for business. Have fun!
                                                                                                                                                                      [ OK ]
ubuntu@ip-172-17-2-143:~$ sudo service arangodb3 start
# 🎉
```

**Comment by dothebart** [comment]
Hi, 
yes you're right - it doesn't work out of the box for the AMI. The reason is, that it uses `/etc/arangodb3/arangod.conf.local` to override the `arangod.conf` settings; this sets the database diretory to `/vol`

**Comment by danmactough** [comment]
Ah, I see. So, my conf change had no effect, and the server was trying to start with the same data directory -- created with mmfile, but trying to use rocksdb. Cool. If that's an edge case specific only to using the AWS marketplace AMI, maybe the docs should just mention that.

**Comment by jsteemann** [comment]
The instructions on the website (https://www.arangodb.com/why-arangodb/storage-engine-comparison-rocksdb/) now mention AWS and `arangod.conf.local` explicitly.
