### ISSUE TITLE
Unique index not enforced on sub-attributes named "_key"

### ISSUE THREAD

**Issue by ftKnox** [arangodb/arangodb#2637]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2 Beta1
- [x] 3.2 Beta2
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [x] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

```json

//example document
{
  "container_type": {
    "_key": "1081534"
  },
  "state": {
    "active": true,
    "retired": false
  },
  "service_start": "2017-06-21T22:02:42.992587497Z",
  "containers": [
    {
      "_key": "1095027",
      "sub_container": true
    },
    {
      "_key": "1095109",
      "sub_container": true
    },
    {
      "_key": "1095186",
      "sub_container": true
    },
    {
      "_key": "1095027",
      "sub_container": true
    },
    {
      "_key": "1095109",
      "sub_container": true
    },
    {
      "_key": "1095186",
      "sub_container": true
    },
  ]
}
```
<img width="1095" alt="screen shot 2017-06-21 at 4 01 59 pm" src="https://user-images.githubusercontent.com/11303823/27408894-00a4cfd2-569c-11e7-8ef4-f78d663271f9.png">

I looked through the indexes documentation online and couldn't see anything related to this not being possible. Creating a unique index on a sub-attribute named "_key" does not get enforced. If i switch the unique index to the sub-attribute named "sub_container" in the example document above, the constraint IS enforced. As far as why don't I just switch the sub-attribute name from "_key" to something else, well I am using a golang back end and it just makes mapping to my structs much easier.

**Comment by jsteemann** [comment]
As far as I can see, the uniqueness checks work and uniqueness is enforced, regardless of whether the sub-attribute is named `_key` or else.

Here's a quick proof that the uniqueness actually works:
```js
db._create("i"); 
db.i.ensureIndex({ type: "hash", unique: true, fields: ["a[*]._key"]}); 
db.i.insert({ a: [ { _key: 1 } ] });
db.i.insert({ a: [ { _key: 1 } ] });
```
The second insert call produces:
```JavaScript exception: ArangoError 1210: unique constraint violated - in index 27417865709307008 of type hash over ["a[*]._key"]
!db.i.insert({ a: [ { _key: 1 } ] });
!     ^
```
What is probably confusing is the following behavior (quoted from https://docs.arangodb.com/3.1/Manual/Indexing/IndexBasics.html):

> Array values will automatically be de-duplicated before being inserted into an array index. For example, if the following document is inserted into the collection, the duplicate array value bar will be inserted only once:
>     db.posts.insert({ tags: [ "foobar", "bar", "bar" ] });
> If an array index is declared unique, the de-duplication of array values will happen before inserting the values into the index, so the above insert operation will not necessarily fail. It will fail if the index already contains an instance of the bar value, but will succeed if the value bar is not already present in the index.

So inserting the same key value twice (or even more times) in a single insert will succeed if the value is not already in the index. It will succeed because array values are de-duplicated before insertion.

**Comment by jsteemann** [comment]
I have opened a pull request (https://github.com/arangodb/arangodb/pull/2644) which would make the on-insert behavior configurable.

**Comment by ftKnox** [comment]
@jsteemann the changes on pull request #2644 look great, thanks
