### ISSUE TITLE
Feature Request - Apache Kafka topic connector

### ISSUE THREAD

**Issue by sajeevpr** [arangodb/arangodb#2646]
Team,

  It would be great if there is a connector using which ArangoDB can pull messages from Apache Kafka. This will very much reduce lot of services to be written for pushing messages to database.  Also the recovery of messages will be automatic when db comes up after a restart or crash.

Regards,
Sajeev

**Comment by sanjuthomas** [comment]
I got one here - https://github.com/sanjuthomas/kafka-connect-arangodb

**Comment by dothebart** [comment]
Closing as solved. 
Thanks @sanjuthomas
