### ISSUE TITLE
decode base64 content-encoding

### ISSUE THREAD

**Issue by ghost** [arangodb/arangodb#265]
Since ArangoDB doesn't allow binaries (yet) we have to base64 encode binary documents put into the database.
Often clients expects binary data as it is and won't perform base64 decoding by themselves unless the data was embedded spcifically as a base64 encoded part.  A solution for this issue would be that arangod admin server automatically decodes responses that has content-encoding set to base64.

**Comment by dhrcom** [comment]
here is a full course on **[how to decode base64](https://nintools.com/blog/how-to-decode-base64)** and here is an easy [base64 decode online](https://nintools.com/base64-decode)
