### ISSUE TITLE
ArangoDB 3.2beta autoincrement bug

### ISSUE THREAD

**Issue by DeShadow** [arangodb/arangodb#2651]
I use ArangoDB 3.2beta1 and 3.2beta2

I found a bug on my OSX
I use collection with autoincrement `_key`. I found that sometimes next value of `_key` is reseted to start value. For example, start value is '10000'. I recreate collection with arangorestore. Than I use it - and it's okay. But sometimes new documents have _key `10000` again, but not `maxValue + 1`. And after that new keys are `10001`, `10002`, etc. And than there are collisions between new documents and old documents with the same keys.

I didn't find the reason when _key was reseted. But I found that in that moment I had two `arangod` processes. And I killed one of them, because I thought that it's my mistake and maybe I started two instances. But after kill of second process my autoincrement _key was reseted to start value.

**Comment by jsteemann** [comment]
You are right, the last assigned autoincrement value is currently not persisted in the RocksDB engine.
We found the bug too, and we have created a pull request to fix it: https://github.com/arangodb/arangodb/pull/2648
I hope the PR will be merged soon.
Thanks!

**Comment by DeShadow** [comment]
Thanks, @jsteemann! :)

**Comment by jsteemann** [comment]
Should be fixed in 3.2beta3.

**Comment by DeShadow** [comment]
@jsteemann Thanks! :) Are fixes in devel branch? Will they be in nightly builds tomorrow?

**Comment by jsteemann** [comment]
The fixes should be contained in 3.2beta3 (downloadable from our website https://www.arangodb.com/download-technical-preview/ubuntu-preview/) and in current `devel`.

**Comment by dothebart** [comment]
We're pleased to anounce that ArangoDB 3.2 containing this is now available for download - Closing.
