### ISSUE TITLE
Removed databases are shown in web-admin

### ISSUE THREAD

**Issue by DeShadow** [arangodb/arangodb#2672]
I use ArangoDB 3.2 last nightly build (26 June). But found this bug earlier.

Simple scenario:
- empty instance;
- create new database `test1`;
- remove database `test1`;
- create new database `test2`;
- go to `Users`;
- create new user;
- select this user and go to `Permissions`;
- you can see databases `test1` and `test2`.

**Comment by baslr** [comment]
This is fixed when the collection level / ro authorization enters ArangoDB beta 3.2.

**Comment by dothebart** [comment]
We're pleased to anounce that ArangoDB 3.2 containing this is now available for download - Closing.
