### ISSUE TITLE
Foxx disabling development mode creates non-deterministic service bundle

### ISSUE THREAD

**Issue by mpv1989** [arangodb/arangodb#2677]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] self-compiled devel branch

### Foxx

After disabling the development mode of a service the created bundle (zip) isn't deterministic - the file order in the bundle depends on OS and file system - and so the service checksum isn't deterministic too.

**Comment by dothebart** [comment]
We're pleased to anounce that ArangoDB 3.2 containing this is now available for download - Closing.
