### ISSUE TITLE
create new edge issue

### ISSUE THREAD

**Issue by wanghaiwin** [arangodb/arangodb#2679]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
 [ ] 3.1
On this operating system:
[ ] MacOS, version:

Dear friends,

i am trying to import edges from csv. Below is the code：

final BaseEdgeDocument value;

value = new BaseEdgeDocument();

value.setKey(c15.getContents()+""+c13.getContents()+""+c4.getContents());
value.setFrom(c1.getContents());
value.setTo(c6.getContents());
value.addAttribute("start_station",c11.getContents());
value.addAttribute("end_station",c12.getContents());

try {
db.graph(GRAPH_NAME).edgeCollection(EDGE_COLLECTION_NAME).insertEdge(value);
System.out.println("Edge-document created"+value.toString());
} catch (final ArangoDBException e) {
System.err.println("Failed to create edge-document. " + e.getMessage());
}

the errors logs：
Failed to create edge-document. Response: 410, Error: 1906 - illegal document handle

I am looking for help.

best wishes.

**Comment by wanghaiwin** [comment]
@mpv1989 hello, friend 
how to set a valid edge id?.

thank you

**Comment by mpv1989** [comment]
As my colleague said in the other issue: "A valid edge id must consist of a valid collection name, then a forward slash plus a valid document key. Example: `users/abc`, `foo/bar`"

For a deeper understanding you should take a look into the [docs](https://docs.arangodb.com/3.1/Manual/Graphs/Edges/).

In your example code I can not see what `c1` and `c6` and the result of `.getContents()` is. Can you provide more information?

**Comment by wanghaiwin** [comment]
@mpv1989 
hello friend,
below is all the code, kindly check

package com.arangodb.example;

import com.arangodb.ArangoDB;
import com.arangodb.ArangoDBException;
import com.arangodb.ArangoDatabase;
import com.arangodb.entity.*;
import com.arangodb.model.CollectionCreateOptions;
import jxl.Cell;
import jxl.Sheet;
import jxl.Workbook;
import jxl.read.biff.BiffException;
import java.io.File;
import java.io.IOException;
import java.util.concurrent.atomic.AtomicReference;


//导入节点

public class TestEdgeProject {
	private static final String GRAPH_NAME = "zhongdianrengraph";
	private static final String EDGE_COLLECTION_NAME = "zhongdianrenguanxi";
	private static final String VERTEX_COLLECTION_NAME = "zhongdianren3";

	// create database
	private static final String dbName = "mydb";

	static final ArangoDB arangoDB = new ArangoDB.Builder().user("root").build();

	private static ArangoDatabase db = arangoDB.db(dbName);

	public static void main(final String[] args) {


        if(db.collection(EDGE_COLLECTION_NAME).equals(null)){

        	System.out.print(db.collection(EDGE_COLLECTION_NAME).equals(null));

			System.out.println("start to create Edges Collection");
			try {
				db.createCollection(EDGE_COLLECTION_NAME, new CollectionCreateOptions().type(CollectionType.EDGES));
				System.out.println("Edges Collection created: " + db.getCollections().toString());
			} catch (final ArangoDBException e) {
				System.err.println("Failed to create edges collection: " + EDGE_COLLECTION_NAME + "; " + e.getMessage());
			}

		// create collection

        }
        else{
			System.out.println("start to delete Edges Collection");
			try {
				db.collection(EDGE_COLLECTION_NAME).drop();
				System.out.println("Edges Collection deleted: ");
			} catch (final ArangoDBException e) {
				System.err.println("Failed to delete edges collection: " + EDGE_COLLECTION_NAME + "; " + e.getMessage());
			}
			try {
				db.createCollection(EDGE_COLLECTION_NAME, new CollectionCreateOptions().type(CollectionType.EDGES));
				System.out.println("Edges Collection recreated: " + db.getCollections().size());
			} catch (final ArangoDBException e) {
				System.err.println("Failed to recreate edges collection: " + EDGE_COLLECTION_NAME + "; " + e.getMessage());
			}


		}
//
//		final Collection<EdgeDefinition> edgeDefinitions = new ArrayList<EdgeDefinition>();
//		edgeDefinitions.add(new EdgeDefinition().collection(EDGE_COLLECTION_NAME).from(VERTEX_COLLECTION_NAME)
//				.to(VERTEX_COLLECTION_NAME));
//
//		db.createGraph(GRAPH_NAME, edgeDefinitions, null);


		// creating a document

		String filepath = "/Users/wanghai/Desktop/work/projects/test/data/1.xls";

		try {

			Workbook workbook = Workbook.getWorkbook(new File(filepath));
			Sheet sheet = workbook.getSheet(3);
			int mm = sheet.getRows();
			int nn = sheet.getColumns();



			int j = sheet.getRows();
			int y = sheet.getColumns();
			for (int i = 1; i < j; i++) {
				//for(int x=0; x<y; x++){
				Cell c1 = sheet.getCell(0, i);
				Cell c2 = sheet.getCell(1, i);
				Cell c3 = sheet.getCell(2, i);
				Cell c4 = sheet.getCell(3, i); //座位号
				Cell c5 = sheet.getCell(4, i);
				Cell c6 = sheet.getCell(5, i);
				Cell c11 = sheet.getCell(10, i);
				Cell c12 = sheet.getCell(11, i);
				Cell c13 = sheet.getCell(12, i); //发车日期
				Cell c15 = sheet.getCell(14, i);//火车车次

                final VertexEntity v1;
                v1 = db.graph(GRAPH_NAME).vertexCollection(VERTEX_COLLECTION_NAME).getVertex(c1.getContents(), VertexEntity.class);
 final BaseEdgeDocument v2 = db.graph(GRAPH_NAME).vertexCollection(VERTEX_COLLECTION_NAME).getVertex(c6.getContents(), BaseEdgeDocument.class);
		        final BaseEdgeDocument value = new BaseEdgeDocument();
		        System.out.println("v1--------------:"+v1);
                value.setFrom(v1.getKey());
                value.setTo(v2.getKey());

                value.setKey(c15.getContents()+"_"+c13.getContents()+"_"+c4.getContents());
				value.setFrom(c1.getContents());
				value.setTo(c6.getContents());
				value.addAttribute("start_station",c11.getContents());
				value.addAttribute("end_station",c12.getContents());

                System.out.println("base-edge-docment:" + value.toString());
                try {
                    EdgeEntity edgeEntity = db.graph(GRAPH_NAME).edgeCollection(EDGE_COLLECTION_NAME).insertEdge(value);
					System.out.println("Edge-document created"+value.toString());
				} catch (final ArangoDBException e) {
					System.err.println("Failed to create edge-document. " + e.getMessage());
				}


			}
			System.out.println("close");
		} catch (BiffException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}


	}


}

**Comment by mpv1989** [comment]
@wanghaiwin ok, the problem is that your are setting the edge `from` and `to` in the first step to `v1.getKey()` and `v2.getKey()` - which is wrong - and then override them with `c1.getContents()` and `c6.getContents()` which is also wrong.

When you change:
```
value.setFrom(v1.getKey());
value.setTo(v2.getKey());
value.setKey(c15.getContents()+"_"+c13.getContents()+"_"+c4.getContents());
value.setFrom(c1.getContents());
value.setTo(c6.getContents());
```
to
```
value.setFrom(v1.getId());
value.setTo(v2.getId());
value.setKey(c15.getContents()+"_"+c13.getContents()+"_"+c4.getContents());
```
everthing should work.

**Comment by wanghaiwin** [comment]
@mpv1989 it worked. thank you very much
