### ISSUE TITLE
Legacy service UI not working

### ISSUE THREAD

**Issue by mpv1989** [arangodb/arangodb#2684]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.1
- [x] 3.2 Beta1
- [x] self-compiled devel branch

### Foxx
Using the field `defaultDocument` in the manifest.json of a legacy service doesn't work. It isn't routed.

**Comment by dothebart** [comment]
ArangoDB 3.2 has been released - closing.
