### ISSUE TITLE
Expecting type Array or Object error being thrown in a random fashion

### ISSUE THREAD

**Issue by akki** [arangodb/arangodb#2700]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 3.1

On this operating system:
- [ ] Linux 
  - [ ] Ubuntu .deb

I'm issuing AQL via:
- [ ] web interface with this browser: Chrome     running on this OS: Ubuntu

I am working in cluster mode.

Today while making a query I got this error
Query:
```WITH authors
RETURN COUNT(
    FOR v, e IN 1..2 ANY @top_author coauthors
        LIMIT 50000
        RETURN DISTINCT e._id
)
```
Error:
```
Query: Expecting type Array or Object (while executing) (exception location: /var/lib/otherjenkins/workspace/RELEASE__BuildPackages/arangod/RestHandler/RestCursorHandler.cpp:131). Please report this error to arangodb.com
```
Thought of reporting because it says so :stuck_out_tongue:
It's worth noting that it works until the LIMIT is 30000 but doesn't work further.

**Comment by mchacki** [comment]
Thanks a lot for reporting this issue.
Is it possible to share the underlying dataset (anonymized) with us?
This would help a lot with debugging.

**Comment by akki** [comment]
It's a huge dataset (12M nodes and 200M edges). Is there something else we can do? (and I definitely can't share the whole data due to proprietary reasons).

**Comment by dothebart** [comment]
Hi, 
we have fixed numerous bugs in conjunction with the `LIMIT` implementation with 3.1.28 - its available for download now. 

Can you retry whether this fixes your issue too?

**Comment by akki** [comment]
Since this used to occur very randomly and many bug fixes have been made after that, please close this ticket if you deem it correct.

**Comment by dothebart** [comment]
Ok, closing it as solved.
