### ISSUE TITLE
Unable to log in as root (docker-compose environment: ARANGO_ROOT_PASSWORD)

### ISSUE THREAD

**Issue by johnvcoleman** [arangodb/arangodb#2712]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [x] 3.1
- [ ] 3.2 Beta1
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [x] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [x] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
When running arangodb remotely behind a reverse proxy using docker-compose and setting the ARANGO_ROOT_PASSWORD environment variable, I'm unable to log in as root.  A "Login Failed!" message is returned when I try to log into the web interface.

**docker-compose.yml:**
version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:                     
      - ./certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy

  www:
      image: blah/www
      restart: always
      depends_on:
        - nginx-proxy
        - letsencrypt
      environment:
        - VIRTUAL_HOST=www.blah.com
        - LETSENCRYPT_HOST=www.blah.com
        - LETSENCRYPT_EMAIL=admin@blah.com

  db:
      image: arangodb
      restart: always
      depends_on:
        - nginx-proxy
        - letsencrypt
      volumes:
       - /mnt/volume1/database:/var/lib/arangodb3 
      environment:
        - ARANGO_ROOT_PASSWORD=blah-blah-blah
        - VIRTUAL_HOST=db.blah.com
        - VIRTUAL_PORT=8529
        - LETSENCRYPT_HOST=db.blah.com
        - LETSENCRYPT_EMAIL=admin@blah.com

After running "docker-compose up" I see this on the console from arangodb:

db_1           | Initializing root user...Hang on...
db_1           | Initializing database...Hang on...
db_1           | Database initialized...Starting System...
db_1           | 2017-07-02T20:55:34Z [1] INFO ArangoDB 3.1.23 [linux] 64bit, using VPack 0.1.30, ICU 54.1, V8 5.0.71.39, OpenSSL 1.0.1t  3 May 2016
db_1           | 2017-07-02T20:55:34Z [1] INFO using SSL options: SSL_OP_CIPHER_SERVER_PREFERENCE, SSL_OP_TLS_ROLLBACK_BUG
db_1           | 2017-07-02T20:55:34Z [1] INFO Starting up with role SINGLE
db_1           | 2017-07-02T20:55:34Z [1] INFO Authentication is turned on
db_1           | 2017-07-02T20:55:34Z [1] INFO Authentication system only
db_1           | 2017-07-02T20:55:34Z [1] INFO Authentication for unix sockets is turned on
db_1           | 2017-07-02T20:55:34Z [1] INFO file-descriptors (nofiles) hard limit is 1048576, soft limit is 1048576
db_1           | 2017-07-02T20:55:34Z [1] INFO JavaScript using startup '/usr/share/arangodb3/js', application '/var/lib/arangodb3-apps'
db_1           | 2017-07-02T20:55:35Z [1] INFO using endpoint 'http+tcp://0.0.0.0:8529' for non-encrypted requests
db_1           | 2017-07-02T20:55:36Z [1] INFO ArangoDB (version 3.1.23 [linux]) is ready for business. Have fun!

I see no errors on the console, everything seems to start normally.  When I try to replicate this locally (using docker, **NOT** docker-compose) the arangodb image starts normally and I can log in using the same password as expected.  I also tried using a really simple password without any symbols, and I still couldn't log in to the remote db server.

I'm happy to provide more info if you need it.  Thanks!

**Comment by johnvcoleman** [comment]
I also tried setting the ARANGO_RANDOM_ROOT_PASSWORD=1 environment variable and I don't see anything in the console output telling me what the random password is.  It's as thought arangodb just doesn't see then environment vars when using docker-compose.  Setting ARANGO_RANDOM_ROOT_PASSWORD=1 with a local docker instance and it worked as you'd expect.

**Comment by dothebart** [comment]
The docker container you use is built from:

https://github.com/arangodb/arangodb-docker/tree/official/jessie/3.1.23

I suggest that you try to build it locally (it basically installs the .deb from arangodb.com - so you can simply do that), but add a plain `set` to the `docker-entrypoint.sh` so you can check back the actual environment whether it contains any of the environment variables you set.

**Comment by phal0r** [comment]
I am having the same issue and reported it under https://github.com/arangodb/arangodb/issues/2538

**Comment by johnvcoleman** [comment]
Thanks @dothebart I think that's a reasonable approach, but instead of doing that, I ran a bash shell within the docker container in question and verified the environment variables were set according to my docker-compose.yml file.  They *are* being set:

root@Instance-1:~/github/admin/docker-compose# docker exec -i -t 8ba2 /bin/bash
root@8ba2f751957e:/# echo $ARANGO_RANDOM_ROOT_PASSWORD
1

But when you check the log, the random password is not being output:

root@Instance-1:~/github/admin/docker-compose# docker logs 8ba2
2017-07-03T22:14:25Z [1] INFO ArangoDB 3.1.23 [linux] 64bit, using VPack 0.1.30, ICU 54.1, V8 5.0.71.39, OpenSSL 1.0.1t  3 May 2016
2017-07-03T22:14:25Z [1] INFO using SSL options: SSL_OP_CIPHER_SERVER_PREFERENCE, SSL_OP_TLS_ROLLBACK_BUG
2017-07-03T22:14:25Z [1] INFO Starting up with role SINGLE
2017-07-03T22:14:25Z [1] INFO Authentication is turned on
2017-07-03T22:14:25Z [1] INFO Authentication system only
2017-07-03T22:14:25Z [1] INFO Authentication for unix sockets is turned on
2017-07-03T22:14:25Z [1] INFO file-descriptors (nofiles) hard limit is 1048576, soft limit is 1048576
2017-07-03T22:14:26Z [1] INFO JavaScript using startup '/usr/share/arangodb3/js', application '/var/lib/arangodb3-apps'
2017-07-03T22:14:27Z [1] INFO using endpoint 'http+tcp://0.0.0.0:8529' for non-encrypted requests
2017-07-03T22:14:28Z [1] INFO ArangoDB (version 3.1.23 [linux]) is ready for business. Have fun!

**Comment by dothebart** [comment]
Look, its working like that over here:
```
docker run -e ARANGO_RANDOM_ROOT_PASSWORD=1 arangodb 
Unable to find image 'arangodb:latest' locally
latest: Pulling from library/arangodb
9f0706ba7422: Pull complete 
80503f0c4189: Pull complete 
486827634964: Pull complete 
792d858be965: Pull complete 
9e8872b11830: Pull complete 
0c49efc9c8fa: Pull complete 
Digest: sha256:c00dc3a6bda67fef54c79e5fe03c731f733b37859aea28ccb681c39e2eb20879
Status: Downloaded newer image for arangodb:latest
===========================================
GENERATED ROOT PASSWORD: BuWM8zR4y6yKErpq
===========================================
Initializing root user...Hang on...
Initializing database...Hang on...
Database initialized...Starting System...
2017-07-04T14:14:13Z [1] INFO ArangoDB 3.1.23 [linux] 64bit, using VPack 0.1.30, ICU 54.1, V8 5.0.71.39, OpenSSL 1.0.1t  3 May 2016
2017-07-04T14:14:13Z [1] INFO using SSL options: SSL_OP_CIPHER_SERVER_PREFERENCE, SSL_OP_TLS_ROLLBACK_BUG
2017-07-04T14:14:13Z [1] INFO Starting up with role SINGLE
2017-07-04T14:14:13Z [1] INFO Authentication is turned on
2017-07-04T14:14:13Z [1] INFO Authentication system only
2017-07-04T14:14:13Z [1] INFO Authentication for unix sockets is turned on
2017-07-04T14:14:13Z [1] INFO file-descriptors (nofiles) hard limit is 1048576, soft limit is 1048576
2017-07-04T14:14:13Z [1] INFO JavaScript using startup '/usr/share/arangodb3/js', application '/var/lib/arangodb3-apps'
2017-07-04T14:14:14Z [1] INFO using endpoint 'http+tcp://0.0.0.0:8529' for non-encrypted requests
2017-07-04T14:14:15Z [1] INFO ArangoDB (version 3.1.23 [linux]) is ready for business. Have fun!
```
docker --version
Docker version 17.05.0-ce, build 89658be

**Comment by johnvcoleman** [comment]
After banging my head for a while I took the drastic step of just deleting the data directory... and after that it recreated it's data directory and the random password setting started working.  So either something was corrupted on the file system, or switching the root password environment variable several times exercised a bug.  Since I can't tell, or give exact steps to recreate, this issue should be closed.

**Comment by dothebart** [comment]
@phal0r since this seems to be somewhat related to what docker keeps, can you try to `docker ps -a ` and `docker images` and purge all containers in conjunction with arangodb and retry?

**Comment by makstr** [comment]
I was struggling with the very same issue last night. Purging images or the containers had no effect, so based on @johnvcoleman suggestion I took the extreme measure and removed the data directory and that did the job

**Comment by lxr900** [comment]
This was closed a while ago, but I just came across a similar issue, not with docker compose, but running a standalone container with persistent data via a docker volume. 

I had accidentally run it at first without saving the root password, so I wanted to go through the procedure indicated [here](https://www.arangodb.com/docs/stable/security-change-root-password.html) to recover.

I stopped and removed the container and started a new one (with the same data volume) using the env var `ARANGO_NO_AUTH=1` and authentication was turned off, which made me hopeful.

I then removed the container again, but when I reran it with `ARANGO_ROOT_PASSWORD` it didn't work, I couldn't use the password I had set.

I retried with `ARANGO_RANDOM_ROOT_PASSWORD=1` and it didn't show any password.

I kept trying a few times with different options, but always removing the container and NOT the data volume.

I then finally decided to reset `ARANGO_NO_AUTH=1` and change the password via UI.

But this makes me think **the environment variable is not enough to actually CHANGE a root password that has already been set.** It must be done via the `arangosh` or the UI. But this should at least avoid having to delete the data volume.

**Comment by whoiscarlo** [comment]
I'm running into the same issue as everyone else and there's definitely a bug in which when you create a new docker container with arangodb whatever environment variable was **initially set** using **ARANGO_ROOT_PASSWORD** will persistent for every arangodb docker container thereafter. And once this glitch happens the env variable **ARANGO_RANDOM_ROOT_PASSWORD=1** will no longer output a randomly generated password, because it is using the password that was set for ARANGO_ROOT_PASSWORD.

Seeing that the repo is very basic, I'm surprised that more people haven't run into this issue because it seems like it's fairly serious. 

I'm running docker on MacOs - Big Sur Version 11.6 in case that has anything to do with it. If anyone could confirm that they are having this same issue on a Windows or Linux machine that would be super helpful in eliminating some possible causes.

**Comment by phal0r** [comment]
Do you mount the same volume to the new containers? Than I think, that this is expected.

**Comment by dothebart** [comment]
exactly. if you have the same database volume as before you expect to find your data again including your credentials when restarting a docker container.

**Comment by whoiscarlo** [comment]
Alright yea that makes perfect sense! I wasn't thinking about the problem in the right way. 

Thank you guys for the help, I was pulling my hair our trying to figure out what I was doing wrong 😅
