### ISSUE TITLE
how to recover remote data

### ISSUE THREAD

**Issue by gmchaturvedi1** [arangodb/arangodb#2723]
i am very new to arangodb administration.

kindly suggest i wrongly executed remove command of collection. How can i recove remove data of that collection.

Any help on this will be great help for me.

Thanks & Regards
gmchaturvedi

**Comment by dothebart** [comment]
Hi,
Sorry we didn't get to you on this issue earlier - we were really busy on the ArangoDB 3.2 release. 

There is no easy way to recover deleted data in ArangoDB. 

If you really need to get back important data, one bet would be to [use the `strings` command ](http://www.linfo.org/strings.html) in linux, and search for your relevant data. 

Other options would include us trying to find the documents inside the db files. Commercial parts of that could be discussed if you reach out to us via hackers at arangodb dot com, thus closing this issue now.
