### ISSUE TITLE
ArangoDB 3.2beta Change collections

### ISSUE THREAD

**Issue by StefanoMartin** [arangodb/arangodb#2744]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [X] 3.2 Beta1
- [ ] self-compiled devel branch

On this operating system:
  - [ ] other:
- [X] Windows, version: 10

### this is an HTTP-related issue

I am testing ArangoRB (Ruby driver for ArangoDB) for ArangoDB 3.2 beta. 
As expected, not all the tests are passing and I am analysing them one by one.
One of them is the following:

`PUT /_db/MyDatabase/_api/collection/MyCollection/properties`
with the following body:
`{"journalSize":null, "waitForSync":true}`

The result is the following one:
`{"error"=>true, "code"=>500, "errorNum"=>4, "errorMessage"=>"Expecting type UInt"}`

Is it the expected result?

**Comment by jsteemann** [comment]
The error message could be better indeed. Or the `journalSize` value could be ignored entirely here.

The following patch should fix it:
```diff
diff --git a/arangod/MMFiles/MMFilesCollection.cpp b/arangod/MMFiles/MMFilesCollection.cpp
index 8ed084e37a..3767f9b4de 100644
--- a/arangod/MMFiles/MMFilesCollection.cpp
+++ b/arangod/MMFiles/MMFilesCollection.cpp
@@ -144,11 +144,11 @@ arangodb::Result MMFilesCollection::updateProperties(VPackSlice const& slice,
   auto journalSlice = slice.get("journalSize");
 
   if (journalSlice.isNone()) {
-    // In some apis maximalSize is allowed instead
+    // In some APIs maximalSize is allowed instead
     journalSlice = slice.get("maximalSize");
   }
 
-  if (!journalSlice.isNone()) {
+  if (!journalSlice.isNone() && journalSlice.isNumber()) {
     TRI_voc_size_t toUpdate = journalSlice.getNumericValue<TRI_voc_size_t>();
     if (toUpdate < TRI_JOURNAL_MINIMAL_SIZE) {
       return {TRI_ERROR_BAD_PARAMETER, "<properties>.journalSize too small"};
```
Will add a test and a PR for it.

**Comment by dothebart** [comment]
ArangoDB 3.2 has been Released - Closing.
