### ISSUE TITLE
[Bug] [Web-Interface] [RocksDB] Cannot rename collection

### ISSUE THREAD

**Issue by frankmayer** [arangodb/arangodb#2750]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2 Beta4
- [x] docker - official docker library

Storage engine: RocksDB

### this is a web interface-related issue:

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [x] `_system` [ ] other: 
4) create a collection
5) then go to the collection's settings and rename that collection, hit "Save"

The following problem occurs: [Screenshot?] 
Error message: **Please enter a valid number**

Instead I would be expecting: 
A renamed collection

I guess the form checks for validity of the MMFIles related fields which under RocksDB are not there.

**Comment by jsteemann** [comment]
This is probably due to the web UI validating the "journal size" value that is supposed to be there when updating/renaming a collection via the web UI.
The problem is that this value is meaningless with the RocksDB engine and there is no way to enter it in the web UI for RocksDB. So saving/renaming the collection via the web UI will always fail then.

**Comment by jsteemann** [comment]
Probably will also happen for `indexBuckets` value, as can be seen in the code of `collectionsItemView.js`:
```
166           if (status === 'loaded') {
167             var journalSize;
168             try {
169               journalSize = JSON.parse($('#change-collection-size').val() * 1024 * 1024);
170             } catch (e) {
171               arangoHelper.arangoError('Please enter a valid number');
172               return 0;
173             }
174 
175             var indexBuckets;
176             try {
177               indexBuckets = JSON.parse($('#change-index-buckets').val());
178               if (indexBuckets < 1 || parseInt(indexBuckets, 10) !== Math.pow(2, Math.log2(indexBuckets))) {
179                 throw new Error('invalid indexBuckets value');
180               }
181             } catch (e) {
182               arangoHelper.arangoError('Please enter a valid number of index buckets');
183               return 0;
184             }
185             var callbackChange = function (error) {
186               if (error) {
187                 arangoHelper.arangoError('Collection error: ' + error.responseText);
188               } else {
189                 this.collectionsView.render();
190                 window.modalView.hide();
191               }
192             }.bind(this);
193 
```

**Comment by hkernbach** [comment]
Fixed in PR: https://github.com/arangodb/arangodb/pull/2784

**Comment by frankmayer** [comment]
Thanks. Will there be a Beta5?

**Comment by frankmayer** [comment]
Fix confirmed. Closing
