### ISSUE TITLE
snap version installs but fails to start on manjaro (Arch derivative)

### ISSUE THREAD

**Issue by rcrath** [arangodb/arangodb#2751]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ X] 3.1
- [ ] 3.2 Beta1
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [X] other: manjaro (Arch derivative)
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

no dataset, can't start service.

### this is an installation-related issue:

These are the steps to reproduce:
1) install successfully via snap
2) check status returns:
```
rich[bin]$ systemctl status snap.arangodb3.arangod
● snap.arangodb3.arangod.service - Service for snap application arangodb3.arangod
   Loaded: loaded (/etc/systemd/system/snap.arangodb3.arangod.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2017-07-07 19:23:14 HST; 27min ago
  Process: 5185 ExecStart=/usr/bin/snap run arangodb3.arangod (code=exited, status=1/FAILURE)
 Main PID: 5185 (code=exited, status=1/FAILURE)

Jul 07 19:23:14 ZaManjCin systemd[1]: snap.arangodb3.arangod.service: Failed with result 'exit-code'.
Jul 07 19:23:14 ZaManjCin systemd[1]: snap.arangodb3.arangod.service: Service hold-off time over, scheduling restart.
Jul 07 19:23:14 ZaManjCin systemd[1]: Stopped Service for snap application arangodb3.arangod.
Jul 07 19:23:14 ZaManjCin systemd[1]: snap.arangodb3.arangod.service: Start request repeated too quickly.
Jul 07 19:23:14 ZaManjCin systemd[1]: Failed to start Service for snap application arangodb3.arangod.
Jul 07 19:23:14 ZaManjCin systemd[1]: snap.arangodb3.arangod.service: Unit entered failed state.
Jul 07 19:23:14 ZaManjCin systemd[1]: snap.arangodb3.arangod.service: Failed with result 'exit-code'.
rich[bin]$ 
```

**Comment by dothebart** [comment]
Hi, 
do you get any logs in the arangodb.log ? I don't know where the snaps put it maybe @servusoft can help here.

**Comment by servusoft** [comment]
@rcrath:
I think also the log for ArangoDB can point to the causes.
why it does not start, it can not be seen.
have you look at /var/snap/<Version>/log ?

**Comment by rcrath** [comment]
oops. closed by accident! 'scuse me...would still like to sort this out.

**Comment by dothebart** [comment]
With the latest Ubuntu 16.04 -5 update snapcraft has stopped working (again) out of nowhere.
We therefore decided to stop distributing and supporting snaps. 

Please use one of the other available distribution channels like the arch overlay (by @sleepycat ) or our docker container.
