### ISSUE TITLE
ArangoDB 3.2.beta4 Managing inactive users

### ISSUE THREAD

**Issue by StefanoMartin** [arangodb/arangodb#2758]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 3.1
- [X] 3.2 Beta1

On this operating system:
  - [X] other:
- [X] Windows, version: 10

I am trying to manage an inactive user and I don't have any idea how to update it (to change the status) or delete it.
I tried on the shell, with the HTTP requests (by using my Ruby driver) and with the ArangoDB Management interface.

To make clear the problem I show here my steps with the shell.

I create an inactive user:
```
127.0.0.1:8529@_system> var users = require("@arangodb/users");

127.0.0.1:8529@_system> users.save("inactive_user", "password", false)
{
  "user" : "inactive_user",
  "active" : false,
  "changePassword" : false,
  "extra" : {
  },
  "code" : 201
}
```

I can retrieve the user.
```
127.0.0.1:8529@_system> users.document("inactive_user")
{
  "user" : "inactive_user",
  "active" : false,
  "changePassword" : false,
  "extra" : {
  },
  "code" : 200
}
```

But I cannot update it:
```
127.0.0.1:8529@_system> users.update("inactive_user", "password", true)
JavaScript exception in file 'c:\Program Files\ArangoDB3 3.2.beta4\usr\share\arangodb3\js\client\modules\@arangodb\arangosh.js' at 97,7: ArangoError 1703: user not found
!      throw error;
!      ^
stacktrace: ArangoError: user not found
    at Object.exports.checkRequestResult (c:\Program Files\ArangoDB3 3.2.beta4\usr\share\arangodb3\js\client\modules\@arangodb\arangosh.js:95:21)
    at Object.exports.update (c:\Program Files\ArangoDB3 3.2.beta4\usr\share\arangodb3\js\client\modules\@arangodb\users.js:101:19)
    at <shell command>:1:7
```

Or delete it:
```
127.0.0.1:8529@_system> users.remove("inactive_user")
JavaScript exception in file 'c:\Program Files\ArangoDB3 3.2.beta4\usr\share\arangodb3\js\client\modules\@arangodb\arangosh.js' at 97,7: ArangoError 1703: user not found
!      throw error;
!      ^
stacktrace: ArangoError: user not found
    at Object.exports.checkRequestResult (c:\Program Files\ArangoDB3 3.2.beta4\usr\share\arangodb3\js\client\modules\@arangodb\arangosh.js:95:21)
    at Object.exports.remove (c:\Program Files\ArangoDB3 3.2.beta4\usr\share\arangodb3\js\client\modules\@arangodb\users.js:111:12)
    at <shell command>:1:7
```

Similar results are obtained from the web interface by checking the box "active" and updating the user, or by trying to delete it.

![example](https://user-images.githubusercontent.com/8471053/27988850-d0fa5498-642c-11e7-9861-2935969e16e0.png)

I try to read more careful the documentation from [here](https://docs.arangodb.com/3.1/Manual/Administration/ManagingUsers.html), but I didn't find any useful information for my problem. 

Can you send me on the correct path?

**Comment by graetzer** [comment]
This is fixed in devel

**Comment by dothebart** [comment]
We're pleased to anounce that ArangoDB 3.2 containing this is now available for download - Closing.
