### ISSUE TITLE
ArangoDB 3.2b4: new index `deduplicate` option missing in web interface

### ISSUE THREAD

**Issue by frankmayer** [arangodb/arangodb#2760]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2 Beta4

### this is a web interface-related issue:
These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) create and/or open a collection
5) click `indexes`. The new index-deduplication option is not present.

**Comment by jsteemann** [comment]
@hkernbach can the "deduplicate" option be added to the web UI eventually?
I think we should also add a help text for it as without explanation it will not be immediately clear what the option means.

**Comment by hkernbach** [comment]
Thanks for the report. PR opened (https://github.com/arangodb/arangodb/pull/2781)

**Comment by dothebart** [comment]
We're pleased to anounce that ArangoDB 3.2 containing this is now available for download - Closing.

**Comment by frankmayer** [comment]
Nice! Congrats to the whole team!
