### ISSUE TITLE
ArangoDB 3.2beta4: Web-interface Queries are not saved anymore 

### ISSUE THREAD

**Issue by frankmayer** [arangodb/arangodb#2764]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2 Beta4 running with RocksDB

### this is a web interface-related issue:

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click to go to queries
5) copy an existing or write a new query or anything into the query textarea
6) Click save as. Type a name, Click save...

Expected behavior: Query shows up in list and is reusable
Actual behavior: Query does not show up in list.

I checked the `_users` collection and the `queries` array of the user only shows the last one saved. Still the web interface does not show any queries, beside the default included ones.

**Comment by hkernbach** [comment]
PR: https://github.com/arangodb/arangodb/pull/2836

**Comment by dothebart** [comment]
We're pleased to anounce that ArangoDB 3.2 containing this is now available for download - Closing.
