### ISSUE TITLE
minimal_resources adjust in the dcos cluster

### ISSUE THREAD

**Issue by hellomanjack** [arangodb/arangodb#2767]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:

- [ 1] 3.1
On this operating system:
- [1 ] DCOS on
 
- [ ] Linux 
  - [1 ] docker - official docker library

Congratulations! arangodb becomes better and better. 
Now I encounter a embarrassed situation .  I have a running cluster in my machines for a long time, and 
recently I have found the resources allocated for the arangodb components are never enough for the storage and compute purpose.  And  the coordinator and dbserver fail so often, I have to think out it.
I have tried "docker update" to adjust the resource, but this is temporary method.
So I wonder how to solve it without destroy the stored data.
Thanks.

**Comment by fceller** [comment]
Can you explain a bit more about your setup? Is the data living inside the docker containers?  Or did you mount some data directory from the outside?

**Comment by hellomanjack** [comment]
@fceller  Sorry to reply so later. I install the arangodb cluster with the dcos marathon. Following is the part of the arangodb.json
 "--mode=cluster",
    "--async_replication=false",
    "--minimal_resources_agent=mem(*):512;cpus(*):0.25;disk(*):4096",
    "--minimal_resources_dbserver=mem(*):2000;cpus(*):1;disk(*):10240",
    "--minimal_resources_secondary=mem(*):1000;cpus(*):1;disk(*):10240",
    "--minimal_resources_coordinator=mem(*):2000;cpus(*):1;disk(*):10240",
    "--nr_agents=1",
    "--nr_dbservers=2",
    "--nr_coordinators=2",

Exactly the same configuration as the tutorials, the data is living inside the docker container.

**Comment by dothebart** [comment]
Hi, sorry for coming back that late also; 
DC/OS doesn't support growing volumes, only adding more of them. 
However, this doesn't play well with ArangoDBs fixed idea of filesystem layout for the databases. 

Thus your best option probably is to add more db-servers, sync over the shards, and take down db-servers one by one. 

So I think we can close this issue.
