### ISSUE TITLE
Jobs pushed in queue while in transaction are not executed

### ISSUE THREAD

**Issue by sowee15** [arangodb/arangodb#2770]
I'm using the latest ArangoDB of the respective release series:
- [x ] 3.1.23

On this operating system:
- [x ] Windows, version: 10 pro

### Foxx
In a foxx service, if I push a job in a queue while being in a transaction (note that I had to add the _queues and _jobs collections to the transaction write collections), the job stays pending until I restart arangodb (then all pending jobs are executed). Running the same code to push the job in the queue outside of a transaction works as expected, the job is marked as completed right after pushing it.

Is it a supported scenario?

**Comment by OmarAyo** [comment]
Hi @sowee15 

This ticket is being closed as inactive due to the date of the last activity on it.

If you believe this was done in error, please comment or create a new issue.
