### ISSUE TITLE
Allow Hash Index on List attributes

### ISSUE THREAD

**Issue by fceller** [arangodb/arangodb#278]
Assume you have { tags: [ "c", "perl", "php" ] } then allow hash index on "tags" for "IN" queries

**Comment by CoDEmanX** [comment]
:newspaper: Breaking news: [https://github.com/arangodb/arangodb/commits/**array_indexing**](https://github.com/arangodb/arangodb/commits/array_indexing) :smiley: 

I assume indexed arrays will speed up queries like http://stackoverflow.com/questions/27936747/query-arangodb-for-arrays

and it could probably be used for some utility functions as well, to test if an array contains at least the given elements, or only the given elements (with or without allowing duplicates), e.g.

    {"_key": "doc1", "colors": ["red", "green", "yellow"]}
    {"_key": "doc2", "colors": ["yellow", "red", "yellow", "yellow"]}

    RETURN SOME(doc1.colors, doc2.colors) // true, because at least "red" also appears in doc2
    RETURN EVERY(doc1.colors, doc2.colors) // false, because doc2 misses "green"
    RETURN EVERY(doc2.colors, doc1.colors) // true, because doc1 contains all colors of doc2 (red and yellow)

Possible options:

- strict: return true only if 2nd array contains no elements the 1st array doesn't have
- stricter: return true only if 2nd array has no extra elements, and the same amount of duplicates per unique element in 1st array

**Comment by jsteemann** [comment]
Regarding @fceller 's query:

ArangoDB 2.8 (current devel) provides array indexes that can be used for such queries.
Example (works from 2.8 on):
```js
/* create collection */
db._create("tags");
/* insert example document */
db.tags.insert({ tags: [ "c", "perl", "php" ] });
/* create array index */
db.tags.ensureIndex({ type: "hash", fields: [ "tags[*]" ] });

/* and query the collection */
var q = "FOR doc IN tags FILTER 'perl' IN doc.tags[*] RETURN doc"; 
db._explain(q); 
db._query(q).toArray();
```
As the explain output shows, the above query will use the index on `tags[*]` so it will be efficient.

**Comment by jsteemann** [comment]
Regarding @kesavkolla 's query:

This will also work from version 2.8 onwards:

```js
/* create collection */
db._create("urls");
/* insert example document */
db.urls.insert({ name: 'name', files: [ { language: 'English' , url: 'http://localhost/book1.pdf' }, { language: 'Spanish', url: 'http://localhost/book1_es.pdf' } ]});
/* create array index */
db.urls.ensureIndex({ type: "hash", fields: [ "files[*].url" ] });

/* and query the collection */
q = "FOR doc IN urls FILTER 'http://localhost/book1.pdf' IN doc.files[*].url RETURN doc"; 
db._explain(q); 
db._query(q).toArray();
```

As the explain output will show, the query will use the array index to find just the documents that contain any sub-object in `files` with a `url` value of `http://localhost/book1.pdf`:
```
Query string:
 FOR doc IN urls FILTER 'http://localhost/book1.pdf' IN doc.files[*].url RETURN doc

Execution plan:
 Id   NodeType          Est.   Comment
  1   SingletonNode        1   * ROOT
  6   IndexNode            1     - FOR doc IN urls   /* hash index scan */
  3   CalculationNode      1       - LET #3 = "http://localhost/book1.pdf" in doc.`files`[*].`url`   /* simple expression */   /* collections used: doc : urls */
  4   FilterNode           1       - FILTER #3
  5   ReturnNode           1       - RETURN doc

Indexes used:
 By   Type   Collection   Unique   Sparse   Selectivity   Fields               Ranges
  6   hash   urls         false    false       100.00 %   [ `files[*].url` ]   "http://localhost/book1.pdf" in doc.`files`[*].`url`

Optimization rules applied:
 Id   RuleName
  1   use-indexes
```
