### ISSUE TITLE
[3.2b rocksdb] out of memory error when running UPDATE/REPLACE on medium-size collection

### ISSUE THREAD

**Issue by ropeladder** [arangodb/arangodb#2810]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2 Beta4 using RocksDB

On this operating system:
- [X] Linux 
  - [X] Ubuntu .deb

### this is an AQL-related issue:
I'm issuing AQL via:
- [X] web interface with this browser: Firefox running on Linux Mint
- [X] this Driver: arangojs

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

    FOR d IN DocCollection
        REPLACE d WITH d IN DocCollection

(UPDATE also gives the same error)

The error is:
`out of memory (exception location: /var/lib/otherjenkins/workspace/RELEASE__BuildPackages/arangod/Aql/ModificationBlocks.cpp:246) (while executing) (exception location: /var/lib/otherjenkins/workspace/RELEASE__BuildPackages/arangod/RestHandler/RestCursorHandler.cpp:130)`

The collection in question is medium sized, 1-1.5gb with 600mb of indexes (guessing from a similar collection loaded without RocksDB). I'm running it on a computer with 16gb RAM. When I run the query, ArangoDB's RAM usage increases to 5.7gb from 3gb, but there is still ~4gb free when I get the out of memory error. I have 38gb free on my hard drive.

The same query works fine when not using RocksDB.

**Comment by ObiWahn** [comment]
```
arangod> 2017-07-18T07:31:01Z [17273] WARNING {queries} slow query: 'FOR d IN test\n    REPLACE d WITH d IN test', took: 2147.509951
2017-07-18T08:03:13Z [17273] WARNING {queries} slow query: 'FOR d IN test\n    REPLACE d WITH d IN test', took: 396.748973
2017-07-18T08:03:13Z [17273] WARNING caught exception in RestCursorHandler: conflict (while executing)
/mnt/c9/jan/.bin/start_rocks_server: line 43: 17273 Killed                  "${cmd[@]}"
```

When running the reported query my process was killed. I am not sure why. The difference in time between the first and second run looks a bit odd to me. the conflict might be triggered by too fast clicking on execution in the web ui.

**Comment by ropeladder** [comment]
Just an update that I still get the same error in the 3.2 final release.

**Comment by jsteemann** [comment]
I think "out of memory" is a misleading error message here.
It is probably some other error that is hidden by that message. There are some exception catch blocks which will return "out of memory" regardless of what the actual exception was. This needs to be fixed so we can find the actual error and fix it.

**Comment by jan-zajic** [comment]
We get the same error in the 3.2 final release. We do replace within transaction in foxx service (RocksDB storage).

**Comment by jan-zajic** [comment]
My colegue can't edit or delete some record in arangodb own web UI. I can do same in 3.2.beta4, he has 3.2.final, so final version is even worse than beta in our current opinion. We have temporarily switched backed to MMFiles. But we really need to use rocksdb because of many concurrent updates.

**Comment by jsteemann** [comment]
What exactly do you mean by "can't edit or delete some record in arangodb own web UI"?
Is there any error shown or logged? Can you elaborate?

**Comment by jan-zajic** [comment]
Change json value, click save, 
PUT XHR http://127.0.0.1:8529/_db/eex/_api/document/device [HTTP/1.1 202 Accepted 4ms],
no error in web browser console, 
no error in ui,
no error in /var/lib/arangodb3/arangod.log,
refresh browser or reopen collection and record,
record has old value ..

**Comment by jan-zajic** [comment]
@jsteemann I think i finally found it !! We have:
* ArangoDB 3.2 final in Docker (official image)
* RocksDB engine
* fulltext index on some field
I can't modify records that don't have that field. So if we have fulltext index on field fulltext, we can edit records where we pass fulltext field during insert, but if we don't, we can't replace or remove or edit this record.

This is both arangodb web ui (no error, probably ignored) or rest api (out of memory) or foxx (out of memory)

**Comment by jsteemann** [comment]
Thanks very much for investigating this.
I'll have a look right now.

**Comment by jsteemann** [comment]
Thanks to the very good description I am able to reproduce this.
Working on a fix now.

**Comment by ropeladder** [comment]
Just confirming that removing the fulltext index on my test collection stops the error from occurring.

**Comment by jsteemann** [comment]
3.2.1 has been released and is [available for download](https://www.arangodb.com/download-major/).
