### ISSUE TITLE
Mechanism for setting initial state

### ISSUE THREAD

**Issue by sleepycat** [arangodb/arangodb#2820]
Applications and queries alike depend on the "state" of the database. Databases that don't exist and missing collections cause errors, as do queries that include functions like `WITHIN_RECTANGLE` when the appropriate index has not been created.

With containerization, the data and the database/collections/users/indexes/etc (which I am collectively referring to here as state) that containers operate on is often stored externally. When an freshly deployed ArangoDB container starts, the operations it can perform without errors are bounded by the state it sees in `/var/lib/arangodb3`. To get a glimpse of the problems this creates:

```sh
docker volume create arango
docker -it -v "arango:/var/lib/arangodb3" -e "ARANGO_ROOT_PASSWORD=somepassword" arangodb
^C
 docker run -it -p 8529:8529 -v "arango:/var/lib/arangodb3" -e "ARANGO_ROOT_PASSWORD=someotherpassword" arangodb
```

Then try to log into the admin interface. The result? `Login failed!`.

I think it would be reasonable (desirable?) for the config I supply (ARANGO_ROOT_PASSWORD) to be somehow used to update the state on disk. Beyond updating the root password, I think it would be beneficial to be able to specify things like indexes, collections and cluster settings via a single (hopefully declarative) mechanism for managing all state.

It would be great to have config that I could supply that I can bring up Arango and know that the users/collections and indexes my application/queries depend on already exist. Just to get a little discussion going, maybe something like this:

```yaml
arango:
  root_password: "foobar"
  db:
    - mydb:
      document_collections:
        - vertices:
          indexes:
            - color
        - widgets
      edge_collections:
        - edges
```

While a little bit of yaml makes this look pretty simple, I'm sure there is a whole host of complicated issues this raises. One of the obvious ones: If I have a collection `foo` and remove `foo` from the config, should Arango delete foo when it starts? Maybe. It might be that there can be some line that can be drawn between destructive actions and non-destructive, and then put the destructive ones behind a flag of some kind. Some possibly interesting/relevant prior art would be [Terraform's plan/apply](https://www.terraform.io/docs/commands/plan.html) commands. 

I'd love to hear people's thoughts on this.

**Comment by dothebart** [comment]
Hi, 
did you have a look at: 
https://github.com/arangodb/arangodb-docker/tree/official/test-user-scripts
?
It demonstrates howto derive from our docker container to influence its init process.

**Comment by dothebart** [comment]
I will close this question as abandoned. 
@sleepycat if you need more information, don't hesitate to ask.
