### ISSUE TITLE
building rocksdb part of ArangoDB (3.1.23 & 3.1.24) fails with CLang on Manjaro

### ISSUE THREAD

**Issue by bissei** [arangodb/arangodb#2829]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [X] 3.1
- [ ] 3.2 Beta1
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [X] other: source 3.1.23 & 3.1.24 (Manjaro)
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an installation-related issue:
clang version: 4.0.1
I used following cmake command:

cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DCMAKE_C_COMPILER=/usr/bin/clang

Scanning dependencies of target rocksdblib
[ 17%] Building CXX object 3rdParty/rocksdb/rocksdb/CMakeFiles/rocksdblib.dir/db/auto_roll_logger.cc.o
In file included from /opt/ArangoDB-3.1.24/3rdParty/rocksdb/rocksdb/db/auto_roll_logger.cc:6:
In file included from /opt/ArangoDB-3.1.24/3rdParty/rocksdb/rocksdb/db/auto_roll_logger.h:15:
In file included from /opt/ArangoDB-3.1.24/3rdParty/rocksdb/rocksdb/port/util_logger.h:18:
In file included from /opt/ArangoDB-3.1.24/3rdParty/rocksdb/rocksdb/util/posix_logger.h:28:
/opt/ArangoDB-3.1.24/3rdParty/rocksdb/rocksdb/util/sync_point.h:75:25: error: no type named 'function' in namespace 'std'
std::function<void(void*)> callback);
~~~~~^
/opt/ArangoDB-3.1.24/3rdParty/rocksdb/rocksdb/util/sync_point.h:75:33: error: expected ')'
std::function<void(void*)> callback);
^
/opt/ArangoDB-3.1.24/3rdParty/rocksdb/rocksdb/util/sync_point.h:74:19: note: to match this '('
void SetCallBack(const std::string point,
^
/opt/ArangoDB-3.1.24/3rdParty/rocksdb/rocksdb/util/sync_point.h:102:40: error: no member named 'function' in namespace 'std'
std::unordered_map<std::string, std::function<void(void*)> > callbacks_;
~~~~~^
/opt/ArangoDB-3.1.24/3rdParty/rocksdb/rocksdb/util/sync_point.h:102:58: error: expected '(' for function-style cast or type construction
std::unordered_map<std::string, std::function<void(void*)> > callbacks_;
~~~~^
/opt/ArangoDB-3.1.24/3rdParty/rocksdb/rocksdb/util/sync_point.h:102:59: error: expected expression
std::unordered_map<std::string, std::function<void(void*)> > callbacks_;
^
/opt/ArangoDB-3.1.24/3rdParty/rocksdb/rocksdb/util/sync_point.h:102:62: error: expected member name or ';' after declaration specifiers
std::unordered_map<std::string, std::function<void(void*)> > callbacks_;
^
6 errors generated.
make[2]: *** [3rdParty/rocksdb/rocksdb/CMakeFiles/rocksdblib.dir/build.make:63: 3rdParty/rocksdb/rocksdb/CMakeFiles/rocksdblib.dir/db/auto_roll_logger.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:843: 3rdParty/rocksdb/rocksdb/CMakeFiles/rocksdblib.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

**Comment by ObiWahn** [comment]
Hi bissei,

compiling devel with the following command works fine for me on debian sid:

```
CXX=/usr/bin/clang++-6.0 CC=/usr/bin/clang-6.0 cmake -DCMAKE_BUILD_TYPE=Release ../arangodb/
make -j $(nproc)
```

Please make sure to use a compiler versions that have been been up to date when we have been actively developing on that branch you want to compile. And always set the environment as shown in the command above. Note that not all parts of the build use the CMake build-system generator. So it could happen that the correct compiler is not passed to sub-projects.

I have been able to reproduce the issue with 3.1 it looks like gcc and clangs standard template libraries might use different includes. I was able to compile rocksdb by adding an additional `#include <functional>` to the header file.

Kind Regards

Jan
