### ISSUE TITLE
web-ui - broken db selection on version upgrade

### ISSUE THREAD

**Issue by ObiWahn** [arangodb/arangodb#2835]
linux / devel:

The web UI looses the connection to the DB server during an upgrade. When the DB server
is restarted a user could see the following selection dialog and error message:

![2017-07-19-130808_1920x1080_scrot](https://user-images.githubusercontent.com/741109/28364475-e1bbfec0-6c84-11e7-978d-b0be39bc5536.png)
![2017-07-19-130821_1920x1080_scrot](https://user-images.githubusercontent.com/741109/28364483-e61400c6-6c84-11e7-9198-c6b692971413.png)

**Comment by hkernbach** [comment]
Fixed in PR: https://github.com/arangodb/arangodb/pull/3001

**Comment by dothebart** [comment]
ArangoDB 3.2.2 containing this bugfix is available for download - thanks for reporting.

Closing.
