### ISSUE TITLE
Clear the database/collection access level do not return json

### ISSUE THREAD

**Issue by ewoutp** [arangodb/arangodb#2847]
Version 3.2.devel 

The HTTP calls `DELETE /_api/user/{user}/database/{dbname}` and `DELETE /_api/user/{user}/database/{dbname}/{collection}` return an empty response of content type `text/plain`, where they should return a JSON object like this:

```
{ 
"error": false
}
```

**Comment by graetzer** [comment]
Hi, sorry I forgot about this, I submitted a pull request which should fix the issue.
https://github.com/arangodb/arangodb/pull/3094

**Comment by dothebart** [comment]
ArangoDB 3.2.2 containing this bugfix is available for download - thanks for reporting.

Closing.
