### ISSUE TITLE
please consider bumping epoch on debian package

### ISSUE THREAD

**Issue by vkunz** [arangodb/arangodb#2850]
hi,

the newly released 3.2GA has a dpkg version flaw. Please consider bumping epoch to fix this.

## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2 Beta1
- [x] 3.2
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [x] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an installation-related issue:
Tried to install 3.2.0, but 3.2.beta6 was installed.
This is because dpkg thinks 3.2.beta6 is higher than 3.2.0, you can verify it via:

```
dpkg --compare-versions 3.2.0 gt 3.2.beta6 && echo true
```
even a bump to 3.2.1 would not solve this:
```
dpkg --compare-versions 3.2.1 gt 3.2.beta6 && echo true
```
the only way I am aware to fix this is bumping epoch:
```
dpkg --compare-versions 1:3.2.0 gt 3.2.beta6 && echo true
```

BR,
Valentin

**Comment by dothebart** [comment]
oh d*, been working hard to find a versioning scheme thats accepted among all packaging targets... 
But I guess we will simply remove the beta and alpha packages since they did their job now. 
Thanks for letting us know.

**Comment by dothebart** [comment]
Ok, alpha/beta have been removed - closing.
