### ISSUE TITLE
ArangoDB 3.2 Graph creation issue

### ISSUE THREAD

**Issue by kashifpk** [arangodb/arangodb#2854]
## my environment running ArangoDB
I'm using arangodb 3.2 

On this operating system:

- [X ] Linux 
  - [X ] Ubuntu .deb

Trying to create a named graph with a normal user (not arango root user) gives read only error. This happens both at the web interface and via the python-arango driver (both of which use the HTTP REST interface I'm assuming). Logging in with root user allows graph creation. The normal user created for the database also has administrative rights for that database. Normal user can create collections but not graphs.

**Comment by dothebart** [comment]
Hi, 
we were able to reproduce this, thanks for reporting.

**Comment by darkfrog26** [comment]
I'm seeing this as well.

**Comment by darkfrog26** [comment]
Unfortunately, when I use root to create the graph and collections, my user cannot see the collections.

**Comment by graetzer** [comment]
you will need to grant `ro`or `rw` rights on the collection  to your user

**Comment by graetzer** [comment]
Hi hope this issue is not bothering you anymore, anyway 3.2.1 was released a while ago, maybe check if you can verify that this bug is not present anymore

**Comment by kashifpk** [comment]
@graetzer Yes I just installed the latest version and checked. This bug is fixed. Thanks :-)
