### ISSUE TITLE
`ArangoError: lock timeout` when trying to build index

### ISSUE THREAD

**Issue by ababkin** [arangodb/arangodb#2859]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2 Beta1
- [X] 3.2 Release
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [ ] Debian .deb
  - [x] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

#### The issue can be reproduced using this dataset:
simple edge dataset with about 30M entries

#### The following problem occurs: [Screenshot?] 

Getting this in `arangosh` when trying to build an index (after about 15 min of it running)
```
192.168.2.121:8529@ethereum> db.txs.ensureIndex({"type":"skiplist", "fields": ["timestamp"]});
JavaScript exception in file '/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js' at 97,7: ArangoError 18: lock timeout
!      throw error;
!      ^
stacktrace: ArangoError: lock timeout
    at Object.exports.checkRequestResult (/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js:95:21)
    at ArangoCollection.ensureIndex (/usr/share/arangodb3/js/client/modules/@arangodb/arango-collection.js:610:12)
    at <shell command>:1:8
```

#### Instead I would be expecting: 
A better indication as to what exactly went wrong.

Any suggestions what other logs/places I can look at to identify what went wrong?

**Comment by ababkin** [comment]
re-ran the command and got a bit different error:
```
192.168.2.121:8529@ethereum> db.txs.ensureIndex({"type":"skiplist", "fields": ["timestamp"]});
JavaScript exception in file '/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js' at 97,7: ArangoError 2001: Request timeout reached
!      throw error;
!      ^
stacktrace: ArangoError: Request timeout reached
    at Object.exports.checkRequestResult (/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js:95:21)
    at ArangoCollection.ensureIndex (/usr/share/arangodb3/js/client/modules/@arangodb/arango-collection.js:610:12)
    at <shell command>:1:8
```

**Comment by fceller** [comment]
@ababkin can you give a sample document? I. e. "db.txs.any()". Thanks

**Comment by fceller** [comment]
@ababkin is this using MMFILES or ROCKSDB?

**Comment by ababkin** [comment]
looks like someone had a similar problem and solved it: https://groups.google.com/forum/#!msg/arangodb/RhqXtqWgQvE/n1yiphSOAAAJ

@fceller 
```
192.168.2.121:8529@ethereum> db.txs.any();
{
  "_key" : "20718586",
  "_id" : "txs/20718586",
  "_from" : "users/0x63a9975ba31b0b9626b34300f7f627147df1f526",
  "_to" : "users/0x96e9833e33f86db1c80254938c032408bbf92cd4",
  "_rev" : "_VUIO-jq-_a",
  "value" : 3.00091348,
  "payload" : "0x",
  "block" : 432384,
  "timestamp" : 1445689404
}
```

> MMFILES or ROCKSDB?
Not sure, how do i check?

> Cluster or Single-Server?
single server

**Comment by fceller** [comment]
@ababkin did this solve your problem as well?

**Comment by ababkin** [comment]
yes, see above: 
> Then managed to build the index successfully:

The way the shell fails is pretty disconcerting though. It would be nice to 1. be able to increate timeout and 2. get more feedback as to what's wrong. I guess in this case the limited system resources had prevented the index building within the bounds of the timeout. But that was just a lucky guess on my part.

**Comment by fceller** [comment]
You can start arangosh with

    arangosh --server.request-timeout 3600

to raise the timeout (in this example an hour)

**Comment by ababkin** [comment]
great, thank you
