### ISSUE TITLE
Define user functions in microservice.

### ISSUE THREAD

**Issue by indolering** [arangodb/arangodb#2860]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [X] 3.1
- [ ] 3.2
- [ ] self-compiled devel branch

It would be ideal if user defined functions could be defined and loaded through a microservice.  This would make it much easier to develop and manage user functions.

**Comment by jsteemann** [comment]
Do you mean AQL user-defined functions?
I think you can define them using Foxx microservices already.
For example, in the JS code of a Foxx application, you can do:
```js
let functions = require("@arangodb/aql/functions");
functions.register("my::double", function(value) { return value * 2; });
```

**Comment by indolering** [comment]
Ahh, now I can't remember the context for this question.  I guess mark it up as a documentation issue?

**Comment by jsteemann** [comment]
Is there any specific problem that keeps you from using user-defined functions in a Foxx microservice?
If yes, what is it exactly? If you think documentation should showcase this bit, please let us know where in the docs you would expect it.

**Comment by dothebart** [comment]
I will close this question as abandoned. 
@indolering  if you need more information, don't hesitate to ask.
