### ISSUE TITLE
cname missing from logger-follow results in rocksdb

### ISSUE THREAD

**Issue by darkfrog26** [arangodb/arangodb#2868]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- 3.2

Mode:
- Single-Server

Storage-Engine:
- rocksdb

On this operating system:
- Linux 
  - Ubuntu .deb

After upgrading to ArangoDB 3.2 and switching to RocksDB querying from `logger-follow` no longer returns `cname` for collection related data.  Specifically, I'm testing with a `DocumentUpsert` and getting the following response:

`{"cid":"11257","data":{"_id":"test/11270","_key":"11270","_rev":"_VVWPGUG---","age":28,"name":"Jane Doe"},"database":"1","tick":"76764","tid":"0","type":2300}`

Everything looks right except the lack of `cname`. Even the documentation doesn't seem to recognize that this has changed: https://docs.arangodb.com/3.2/HTTP/Replications/ReplicationLogger.html

**Comment by jsteemann** [comment]
The "cname" attribute should be back for RocksDB starting in 3.2.1

**Comment by jsteemann** [comment]
3.2.1 has been released and is [available for download](https://www.arangodb.com/download-major/).
