### ISSUE TITLE
[ArangoDB 3.2][REST-Interface]:Collection properties do not return `isVolatile` attribute 

### ISSUE THREAD

**Issue by frankmayer** [arangodb/arangodb#2874]
While re-running the ArangoDB-PHP testsuite before tagging the 3.2.0 release of the PHP driver, several errors came up, that were not there in a prior test with some of the early betas.
Test(https://travis-ci.org/arangodb/arangodb-php/jobs/251986282)

One of the tests expects to get a `true` value for the `isVolatile` attribute, when the properties of such a collection are queried.
This test does fail with current ArangoDB 3.2 with RocksDB .

How to recreate this:
1) Create a volatile collection
2) query the rest interface for its properties

Result: There should be an attribute `"isVolatile": true`
Actual result: The attribute is missing.

Note: This specific error does not show up the testsuite that runs on TravisCI, but on my local RocksDB installation.

**Comment by jsteemann** [comment]
As you already found out, this is related to using the RocksDB engine. The RocksDB engine does not support volatile collections, so the attribute is simply ignored there. It may not even be returned by all APIs.
I have adjusted the docs accordingly (there's a PR open for this) and I have also adjusted the PHP driver's tests locally to honor the selected storage engine and not fail if the "wrong" engine is selected.
I will push to the driver repository once the ArangoDB PR got accepted.

**Comment by frankmayer** [comment]
OK, got it, just two questions that arise.
- I think that the REST API returns the 200OK with `isVolatile: true` when such a collection is created (even with RocksDB). Shouldn't there be some error thrown in that case?
- Volatile collections are kind of practical in some cases. Any plans to have some kind of volatile collections even with (or in parallel to) the RocksDB engine?

**Comment by DeShadow** [comment]
Yeah, volatile collections are looked like smth far from engine. And they are very useful in some situations (for example session storage between two running nodes of application servers).

**Comment by jsteemann** [comment]
I understand that it would be useful to support volatile collections in all storage engines, including the RocksDB engine.

However, in the ArangoDB architecture, all data storage business is a responsibility of the storage engine, and I don't see any way of implementing that feature for the RocksDB engine in the near future.
So we probably should disallow the creation of volatile collections for the RocksDB engine at all, so that the server does not accept the creation of such and claims it has done so (while in fact it has not).

**Comment by frankmayer** [comment]
Yes, that makes most sense.

**Comment by jsteemann** [comment]
Fixed in 3.2.1

**Comment by frankmayer** [comment]
OK, closing this. Thanks
