### ISSUE TITLE
[ArangoDB 3.2][REST-Interface]: `/_api/query/current` returns empty array

### ISSUE THREAD

**Issue by frankmayer** [arangodb/arangodb#2875]
While re-running the ArangoDB-PHP testsuite before tagging the 3.2.0 release of the PHP driver, several errors came up, that were not there in a prior test with some of the early betas.
Test(https://travis-ci.org/arangodb/arangodb-php/jobs/251986282)

This Issue deals with one of the tests expecting to get a query count of 1 after sending an AQL query of `RETURN SLEEP(30)`.
This test does fail with current ArangoDB 3.2 with RocksDB as well as on TravisCI with the current devel .

How to recreate this:

Send an AQL QUERY : `RETURN SLEEP (seconds to sleep)`
query the API on: `/_api/query/current`
Result: There should be an array containing the SLEEP Query.
Actual result: An empty array is returned.

**Comment by jsteemann** [comment]
The reason for this failure is the same as in https://github.com/arangodb/arangodb-php/issues/229:
ArangoDB now has an option that controls whether JavaScript code execution via HTTP is allowed or not. The default value for this option is "false", so it is disallowed. The test however relies on this option being set to "true". 
I have a PR open for the ArangoDB main repository and a local fix for the PHP driver to check for the server's setting. Will push to the driver repository once the PR got accepted and there is a nightly build containing the change.

**Comment by jsteemann** [comment]
Should be fixed by now.

**Comment by frankmayer** [comment]
OK closing this. Thanks
