### ISSUE TITLE
Web interface - remember choice of code view or tree view of document 

### ISSUE THREAD

**Issue by DeShadow** [arangodb/arangodb#2888]
I think many people like to view documents in `code view`. It's very useful:
- I see real types and no need to remember color of types
- When I want to create new document I prefer to write simple JSON

I think it can be global setting of web interface or simple remembering of last choice

**Comment by hkernbach** [comment]
Fixed in 3.2 and devel branch. PRs already accepted:
- https://github.com/arangodb/arangodb/pull/3815
- https://github.com/arangodb/arangodb/pull/3833

**Comment by sleto-it** [comment]
Hi, thanks again for opening this issue. Version 3.2.9 has been released. I am closing this issue now. Please let us know if you have additional feedback 

Many thanks,
