### ISSUE TITLE
Traversal query using incorrect collection id

### ISSUE THREAD

**Issue by tohyung85** [arangodb/arangodb#2889]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [x] 3.1
- [ ] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [x] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [x] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[x] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I currently have a collection geo_feature which is related by an edge collection isWithin. And i experienced the following issue when running the following AQL query.

The AQL query in question is:
        FOR feature IN geo_feature
        FILTER feature.name == 'OTK2' || feature.name == 'OE5' || feature.name == 'OE6'
        LET isWithin = (
            FOR t, e IN OUTBOUND feature._id isWithin
            LIMIT 1
            RETURN { terminal_id: t._key, isWithinId: e, fId: feature._id }
        )
        RETURN {
            type: 'Feature',
            properties: {
                type: feature.type,
                id: feature._key,
                featureId: feature._id,
                name: feature.name,
                isWithin: isWithin[0].terminal_id,
                isWithinId: isWithin[0].isWithinId._id,
                isWithinFrom: isWithin[0].isWithinId._from,
                isWithinto: isWithin[0].isWithinId._to,
                isWithinSearch: isWithin[0].fId
            }
        }

The following is the results of the above query. What i found puzzling was the fact that an incorrect feature._id was used for the edge traversal query. For example as seen below, the feature._id for OE6 was 'geo_feature/OEOE6' but during the query 'geo_feature/OEOE5' was used as the feature._id instead.

The above mentioned query used to be working prior to my upgrade from 3.1.20 to v3.1.25 as well. And would really appreciate some help on this.

[
  {
    "type": "Feature",
    "properties": {
      "type": "jetty",
      "id": "OEOE5",
      "featureId": "geo_feature/OEOE5",
      "name": "OE5",
      "isWithin": "OE",
      "isWithinId": "isWithin/93824818",
      "isWithinFrom": "geo_feature/OEOE5",
      "isWithinto": "geo_feature/OE",
      "isWithinSearch": "geo_feature/OEOE5"
    }
  },
  {
    "type": "Feature",
    "properties": {
      "type": "jetty",
      "id": "OEOE6",
      "featureId": "geo_feature/OEOE6",
      "name": "OE6",
      "isWithin": "OE",
      "isWithinId": "isWithin/573191212",
      "isWithinFrom": "geo_feature/OEOE5",
      "isWithinto": "geo_feature/OE",
      "isWithinSearch": "geo_feature/OEOE6"
    }
  },
  {
    "type": "Feature",
    "properties": {
      "type": "jetty",
      "id": "OTPSOTK2",
      "featureId": "geo_feature/OTPSOTK2",
      "name": "OTK2",
      "isWithin": null,
      "isWithinId": null,
      "isWithinFrom": null,
      "isWithinto": null,
      "isWithinSearch": null
    }
  }
]

**Comment by miguel-porto** [comment]
I have the impression that this might be related to my issue #2884 because the results I'm getting from that query don't seem to be correct either; and is a very similar query to this one.

**Comment by jsteemann** [comment]
@miguel-porto : I think so too

**Comment by miguel-porto** [comment]
A one-liner fix! Thank you, will try as soon as it is available.

**Comment by jsteemann** [comment]
Should be fixed with 3.1.27 and 3.2.1

**Comment by jsteemann** [comment]
3.2.1 has been released and is [available for download](https://www.arangodb.com/download-major/).
