### ISSUE TITLE
Issue with arango dashboard in clustered setup

### ISSUE THREAD

**Issue by krjain** [arangodb/arangodb#2893]
Dashboard has following issues:
1) "shards" tab does not work in some scenarios
2) top bar menu is missing in some scenarios

## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
3.2

Mode:
Cluster

Storage-Engine:
mmfiles

On this operating system:
Linuxx

Attached document has the detailed description of the issue:

[Arango Dashboard Issue.pdf](https://github.com/arangodb/arangodb/files/1180255/Arango.Dashboard.Issue.pdf)

**Comment by dothebart** [comment]
Hi, 
Can you please add the images as inline attachments on github? you can easily drag+drop them into the bug area (i.e. from nautilus or roxx filer)

**Comment by dothebart** [comment]
Hi, any news on this? or can we close this issue?
