### ISSUE TITLE
Optimize parsing of non-zip Foxx bundle files during deploy

### ISSUE THREAD

**Issue by mvollmary** [arangodb/arangodb#2899]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2

### Foxx
When deploying a Foxx service from a non-zip file it is treated as JS. If it isn't JS the parse error should be catched and a error with a helpful error code/ message should be thrown.

**Comment by pluma** [comment]
This seems to no longer be an issue. If the file is not a zip file nor a well-formed JS file, it will abort installation.
