### ISSUE TITLE
Add operator aliases IS and ISNT

### ISSUE THREAD

**Issue by MegaUITeam** [arangodb/arangodb#2908]
`is` alias for `==`
`isnt` alias for `!=`
`and` alias for `&&`
`or` alias for `||`
`not` alias for `!`

```
for user in Users
  filter 
    user.name is 'Neo' and user.age > 20 or not user.active
  return user
```

Like Coffeescript

**Comment by jsteemann** [comment]
AND, OR and NOT are already present as aliases for `&&`, `||` and `!` in AQL.

**Comment by MegaUITeam** [comment]
Let's add `is` and `isnt` for more literary expressiveness?

**Comment by Simran-B** [comment]
In Python there is an `is` operator, but it is different from `==`. The latter checks for equal value, whereas `is` checks if the two operands refer to the same object:

```python
False == False # True
    0 == False # True

False is False # True
    0 is False # False
```

There is no `isnt` operator however. Instead, you would use two operators in conjunction, `is not`.

If we actually wanted to make all operators literary expressive, the following would also be required:

- `>` greater than
- `>=` greater than or equal to
- `<`less than
- `<=` less than or equal to
- `=~` matches regular expression
- `!~` does not match regular expression
- `ALL ==` all equal to
- `ANY ==` any equal to
- `NONE ==` none equal to
- all combinations of `ALL` / `ANY` / `NONE` and `!=` / `>` / `>=` / `<` / `<=`

This would rather harm query readability in my opinion. It should be easy enough to learn the meaning of operators like `==`, which exist in many programming languages.

**Comment by dothebart** [comment]
We discussed this - won't do this - closing.
