### ISSUE TITLE
FOR i IN [0..10] INSERT not inserted 10 documents

### ISSUE THREAD

**Issue by MegaUITeam** [arangodb/arangodb#2909]
bug
===

```coffeescript
db.query "
  FOR i IN [0..10]
    INSERT {name: i} INTO 'User' 
    RETURN NEW
"
```

its must create 10 documents and add it to `User` collection, but was inserted one document, like:
```javascript
 {name: [0,1,2,3,4,5,6,7,8,9,10]}
```

but this is works:

```coffeescript
db.query "
  FOR i IN 0..10
    INSERT {name: i} INTO 'User' 
    RETURN NEW
"
```

**Comment by jsteemann** [comment]
This is not a bug, but it is intentional.

The `0..10` produces an array with 11 members: `[ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]`.
Wrapping it in an extra `[ ... ]` will create an array with one member, which will be the array of 11 entries: `[ [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ] ]`

**Comment by MegaUITeam** [comment]
@jsteemann  Why does not the for operator iterate over an array?

**Comment by jsteemann** [comment]
`0..10` already produces an array, and you can use `FOR i IN 0..10` to iterate over the array.
`FOR i IN [0..10]` produces an array with 11 members and puts it inside an array. The `FOR` will then iterate over the outer array, which only has one member (the array with the 11 members).

The `FOR` operator will not recursively walk over an array, but only over the top-level elements in it (as in other languages).

**Comment by MegaUITeam** [comment]
@jsteemann  Why does not the for operator iterate over an array?
What if I want to iterate by array inside a document?

```coffeescript
db.query "
  FOR cat IN Cats
    FOR child IN cat.children // it will iterate by array?
      INSERT {name: child.name} INTO Children
"
```

it will iterate by array?

**Comment by mchacki** [comment]
Hi, yes in that case it will.


The for operator will always iterate over the content of the thing it is applied on.
If one of the elements in this thing is by accident an array the iterator will NOT
expand this array, it will be handled as any other element.

e.g.:

FOR x IN [1,2,3]  => will result in 1, 2 and 3
FOR x IN [ [1,2,3], [4,5,6] ] => Will result in [1,2,3] and [4,5,6]

To the original question:
1..10 will create: [1,2,3,4,5,6,7,8,9,10]
Hence [1..10] will create [ [1,2,3,4,5,6,7,8,9,10] ] => the iterator will only find one element.

**Comment by MegaUITeam** [comment]
if `1..10` create array, then why you not use square brackets `[ ]` in syntax ? It would be more obvious, for the user.

**Comment by jsteemann** [comment]
Other languages also create arrays from `a .. b` without the need to put square brackets around.
Consider the following example from Ruby:
(extra nil at end so we do not see the result of the last expression again)
```
(1..10).each do|val| p val end
1
2
3
4
5
6
7
8
9
10
=> 1..10
```
but putting it in extra square brackets produces not the intended results:
```
[1..10].each do|val| p val end
1..10
=> [1..10]
```
