### ISSUE TITLE
Unable to configue rocksdb in 

### ISSUE THREAD

**Issue by zopyx** [arangodb/arangodb#2916]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ X] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [ X] Single-Server

Storage-Engine:
- [ ] mmfiles
- [X ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ X] own infrastructure
- [X ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ X] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

I installed ArangoDB 3.2 on FC26 using the provided RPM.

I set

```
storage-engine = rocksdb
```

in arangod.conf (instead of `auto`).

ArangoDB won't start with this particular change

```
● arangodb3.service - ArangoDB database server
   Loaded: loaded (/usr/lib/systemd/system/arangodb3.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2017-07-31 17:23:07 CEST; 3min 35s ago
  Process: 28571 ExecStart=/usr/sbin/arangod --uid arangodb --gid arangodb --pid-file /var/run/arangodb3/arangod.pid --temp.path /var/tmp/arangodb3 --
  Process: 28710 ExecStartPre=/usr/sbin/arangod --uid arangodb --gid arangodb --pid-file /var/run/arangodb3/arangod.pid --server.rest-server false --d
  Process: 28709 ExecStartPre=/usr/bin/chmod 700 /var/lib/arangodb3-apps (code=exited, status=0/SUCCESS)
  Process: 28708 ExecStartPre=/usr/bin/chown -R arangodb:arangodb /var/lib/arangodb3-apps (code=exited, status=0/SUCCESS)
  Process: 28707 ExecStartPre=/usr/bin/chmod 700 /var/lib/arangodb3 (code=exited, status=0/SUCCESS)
  Process: 28706 ExecStartPre=/usr/bin/chown -R arangodb:arangodb /var/lib/arangodb3 (code=exited, status=0/SUCCESS)
  Process: 28705 ExecStartPre=/usr/bin/chmod 700 /var/log/arangodb3 (code=exited, status=0/SUCCESS)
  Process: 28704 ExecStartPre=/usr/bin/chown -R arangodb:arangodb /var/log/arangodb3 (code=exited, status=0/SUCCESS)
  Process: 28703 ExecStartPre=/usr/bin/install -g arangodb -o arangodb -d /var/run/arangodb3 (code=exited, status=0/SUCCESS)
  Process: 28702 ExecStartPre=/usr/bin/install -g arangodb -o arangodb -d /var/tmp/arangodb3 (code=exited, status=0/SUCCESS)
 Main PID: 28572 (code=exited, status=0/SUCCESS)

Jul 31 17:23:07 dev2.zopyx.com systemd[1]: arangodb3.service: Unit entered failed state.
Jul 31 17:23:07 dev2.zopyx.com systemd[1]: arangodb3.service: Failed with result 'exit-code'.
Jul 31 17:23:07 dev2.zopyx.com systemd[1]: arangodb3.service: Service hold-off time over, scheduling restart.
Jul 31 17:23:07 dev2.zopyx.com systemd[1]: Stopped ArangoDB database server.
Jul 31 17:23:07 dev2.zopyx.com systemd[1]: arangodb3.service: Start request repeated too quickly.
Jul 31 17:23:07 dev2.zopyx.com systemd[1]: Failed to start ArangoDB database server.
Jul 31 17:23:07 dev2.zopyx.com systemd[1]: arangodb3.service: Unit entered failed state.
Jul 31 17:23:07 dev2.zopyx.com systemd[1]: arangodb3.service: Failed with result 'exit-code'.
```

**Comment by jsteemann** [comment]
If you had installed ArangoDB with the mmfiles engine (or picked `auto`), it will already have created a database directory suitable for the mmfiles engine.
When you restart it, it will insist on the selected storage engine being the mmfiles engine then. Changing the storage engine then will make arangod refuse to start.

A quote from the manual:

> One storage engine type is supported per server per installation. Live switching of storage engines on already installed systems isn't supported. Configuring the wrong engine (not matching the previously used one) will result in the server refusing to start. You may however use auto to let ArangoDB choose the previously used one. 

There is still a way to switch the storage engine later on:
you can either pick a different database directory for rocksdb, so when ArangoDB starts up, it will not find an mmfiles directory. So it will happily create a new directory for the rocksdb engine.
If you have already stored some data in the mmfiles version, you should use arangodump to export it from the mmfiles version of ArangoDB so you can later restore it when the rocksdb version is up and running.

If there is no data in the mmfiles instance that you want to keep, the other option is to stop arangod, remove all contents of the database directory, switch the storage engine to rocksdb in the configuration and restart it. But please be warned that this option will *REMOVE ALL DATA in ArangoDB*, so use it with care!

**Comment by jsteemann** [comment]
Did the above suggestions help?

**Comment by juliusMoreno** [comment]
Can I ask what value you also have written in var/lib/arangodb3/ENGINE ?

**Comment by dothebart** [comment]
In his case the `ENGINE` file would contain `mmfiles`. 

It was irretation about the choice of the storage engine - so following up a slack conversation we can close this now.
