### ISSUE TITLE
arangoimp command tool is getting closed after entering a password

### ISSUE THREAD

**Issue by alexalexpod** [arangodb/arangodb#2937]
I have tried to use arangoimp command tool to import data to ArangoDB.
After entering a prompted password, the command tool has suddenly got closed immediately. 
Why the arangoimp got closed?
I use the Windows 10 64-bit version, ArangoDB: 3.2

Thanks, Alex.

**Comment by jsteemann** [comment]
arangoimp is a command-line tool.

If you are using Windows my guess is you started the application by double-clicking on it? 
If yes: from what I know this will open a command prompt and start arangoimp in it. It will then ask for the password, and when this is entered it will probably print an error message about missing other arguments (for example `--file`, `--collection`). After that arangoimp will exit and the command prompt will close immediately.

If you actually started it by double-clicking, can you instead try starting it from a command prompt? Then if arangoimp fails with an error message, then you will be able to see it and add the missing arguments.

**Comment by alexalexpod** [comment]
Hello, Jan.

You are definitely right about using the arangoimp.exe.
I have managed to import two document collections, but I have failed to import the edge collection.
Here is the simple JSON for creating the edge collection (links2.json):
{"id":"links/2500","type":"link","t":"2500","id1":"actor/882","id2":"movie/120","d":{"_key":"2500","_id":"links/2500","_from":"actor/882","_to":"movie/120","_rev":"_VGKiEoS--a","name":"Arwen Evenstar","type":"acts_in"}}

the create command:
arangoimp --server.database movies --file "d:\links2.json" --type jsonl --collection "links2" --create-collection true --create-collection-type edge

and the warning I get:
WARNING at position 1: missing '_from' or '_to' attribute, offending document: {"d":{"_from":"actor/882","_id":"links/2500","_key":"2500","_rev":"_VGKiEoS--a","_to":"movie/120","name":"Arwen Evenstar","type":"acts_in"},"id":"links/2500","id1":"actor/882","id2":"movie/120","t":"2500","type":"link"}

As a result, the edge collection is created, but with no data (empty edge collection).

Thanks in advance, Alex.

**Comment by jsteemann** [comment]
The document specified in your example does not contain a `_from` nor a `_to` attribute on the top-level.
That's why arangoimp complains and does not import the document.
`_from` and `_to` are present in the document only as sub-attributes of top-level attribute `d`. They will not be picked up from there. In order to import the document, you should make `_from` and `_to` top-level attributes.

**Comment by alexalexpod** [comment]
Thank you, Jan - it works now.

**Comment by jsteemann** [comment]
Closing this as answered

**Comment by sandeepkorrapati** [comment]
Hi @jsteemann, I ran the arangoimp tool from command tool but the import tool closed suddenly. It didn't even print any message on command prompt. Any help would be appreciated

**Comment by Simran-B** [comment]
Please don't revive unrelated old issues. Further discussion in https://github.com/arangodb/arangodb/issues/8540
