### ISSUE TITLE
loadIndexesIntoMemory not returning the same structure as the rest of the collection APIs

### ISSUE THREAD

**Issue by Sekku** [arangodb/arangodb#2943]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2

Mode:
- [x] Single-Server

Storage-Engine:
- [x] rocksdb

On this operating system:
- [x] Linux 
  - [x] docker - official docker library

Hi

I am using the http API. For the operation
<code>PUT /_api/collection/{collection-name}/loadIndexesIntoMemory</code>
and upon success it returns a plain boolean (<code>true</code>) when any other operation within the collection and database management API returns 
<code>
{
    "code": int,
    "error": boolean,
    ...
}
</code>

Could be this changed to be similar to the rest of the functions or is there any reason for which this cannot be changed?

**Comment by jsteemann** [comment]
Adjusted the API return value to return `{ "result": true }` instead. This will automatically be augmented with `"error" : true|false` and `"code" : ...`.

**Comment by jsteemann** [comment]
3.2.1 has been released and is [available for download](https://www.arangodb.com/download-major/).
