### ISSUE TITLE
[AQL] lest go create buildin  function GET_BY_ID?

### ISSUE THREAD

**Issue by MegaUITeam** [arangodb/arangodb#2947]
Like this:

```
 FOR user IN Users
    RETURN GET_BY_ID( user.friendId, Users )
```

**Comment by jsteemann** [comment]
Please describe what this function is supposed to do.
Are you potentially looking for some function such as [DOCUMENT](https://docs.arangodb.com/3.2/AQL/Functions/Miscellaneous.html#document)?
