### ISSUE TITLE
Trigger Options

### ISSUE THREAD

**Issue by indolering** [arangodb/arangodb#2965]
Sorry for the cross-post, but I posted the following [to the mailing list](https://groups.google.com/forum/#!topic/arangodb/ZvEXGR76Oms) a week ago and haven't received a response:

> I'm trying to push some of my ETL workflow into ArangoDB using Foxx.   However, I need something approximating triggers.  I know I can create a microservice for updates, but I need changes to propagate even if someone doesn't use the blessed interface.  What are my options, outside of setting up a timer to run a batch job?  The roadmap includes triggers, is there any timeline on this feature?

**Comment by dothebart** [comment]
Hi, you can use [arangochair](https://www.arangodb.com/2017/03/arangochair-tool-listening-changes-arangodb/) for the time being.
We currently don't have an eta on it. 

Its currently tracked in issue #602, so I'd like to close this as a duplicate if there is no additional information required?
