### ISSUE TITLE
log something more obvious when you log a Buffer

### ISSUE THREAD

**Issue by Thijxx** [arangodb/arangodb#2978]
When I `console.log` the `req.body` I get the following returned:

`[Object { "binarySlice" : function binarySlice() { [native code] }, "asciiSlice" : function asciiSlice() { [native code] }, "base64Slice" : function base64Slice() { [native code] }, "ucs2Slice" : function ucs2Slice() { [native code] }, "hexSlice" : functi`

Maybe you could return something more useful.

This issue created by request on Slack: 
https://arangodb-community.slack.com/archives/C1QKPLEEP/p1502119212714438

**Comment by jsteemann** [comment]
Will be fixed once the above PR is fixed. That potentially means release 3.2.2

**Comment by dothebart** [comment]
ArangoDB 3.2.2 containing this bugfix is available for download - thanks for reporting.

Closing.
