### ISSUE TITLE
AQL parse error?

### ISSUE THREAD

**Issue by wonderbeyond** [arangodb/arangodb#2982]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 3.0
- [x] 2.8
- [x] 3.1
- [x] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

## this is an AQL-related issue:

I'm issuing AQL via:
- [x] web interface with this browser:     running on this OS:
- [x] arangosh
- [ ] this Driver:

## These are the steps to reproduce:

1) Log into a arangosh and connect to a test database
2) Paste the commands below to create some test data
```javascript
db._createDocumentCollection('Article')
db.Article.insert({title: 'Vue - any way to reuse SLOT?', tags: ['javascript', 'vue.js']})
db.Article.insert({title: 'Adding geometry to THREE.Object3D', tags: ['javascript', 'three.js']})
db.Article.insert({title: 'Check if page is vertical using PyPDF2?', tags: ['python']})
db.Article.insert({title: 'EnvironmentError: Gmsh version must be >= 2.0'})
````
3) execute a query with issue:
```javascript
db._query(`
FOR a IN Article
FILTER LENGTH(INTERSECTION(a.tags OR [], ['python', 'vue.js'])) > 0
RETURN a
`)
```
It results a warning:
> 1542 invalid argument type in call to function 'INTERSECTION()'

4) Use the same expression as part of `RETURN` value, then it's OK:
```javascript
db._query(`
FOR a IN Article
RETURN {
  _key: a._key,
  tags: a.tags,
  _has_intersection: LENGTH(INTERSECTION(a.tags OR [], ['python', 'vue.js'])) > 0}
`)
```

**Comment by jsteemann** [comment]
Will be fixed once above PR is merged. That potentially means release 3.2.2.

**Comment by dothebart** [comment]
ArangoDB 3.2.2 containing this bugfix is available for download - thanks for reporting.

Closing.
