### ISSUE TITLE
operation is too expensive for creating database

### ISSUE THREAD

**Issue by hellomanjack** [arangodb/arangodb#2995]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [x] 3.2
- [ ] self-compiled devel branch

Mode:
- [x] Cluster
- [ ] Single-Server

Storage-Engine:
- [x] mmfiles
- [x] rocksdb

On this operating system:
- [x] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [x] using the cluster?
- [ ] _system database?

I build a cluster with script startLocalCluster.sh. When I set 1 agency,2 database,1 coordinator, creating a database consume about 8 seconds;whereas when i set 1 agency,1 database,1 coordinator consumes less than 0.3 seconds and the same with the standalone mode.  Is it normal ?

startLocalCluster.sh can be found here.
https://github.com/hellomanjack/arangodb/blob/devel/scripts/startLocalCluster.sh

**Comment by kvahed** [comment]
This is normal behaviour as is related to the setup of a database under synchronous replication regime. This applies to creation, modification and deletion of databases and other structural objects like collections indexes etc. Database IO for documents and queries are not affected by synchronous replication per se. If such operations are an issue, one can do creation, modification or drops in a separate connection simultaneously to avoid dead times.
