### ISSUE TITLE
Arangorestore fails if server runs on tls.protocol = 4

### ISSUE THREAD

**Issue by ThomasWeiss** [arangodb/arangodb#2999]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2 

Mode:
- [x] Single-Server

Storage-Engine:
- [x] rocksdb

On this operating system:
- [x] Linux 
  - [x] Ubuntu .deb

Trying to run arangorestore (from Windows) fails with
````
2017-08-09T03:09:36Z [13112] ERROR Could not connect to endpoint http+ssl://xxx.westeurope.cloudapp.azure.com:8529
2017-08-09T03:09:36Z [13112] FATAL Could not connect to 'http+ssl://xxx.westeurope.cloudapp.azure.com:8529' 'SSL: during SSL_connect:  - details: error:00000001:lib(0):func(0):reason(1)''
````

Works fine when using tls.protocol = 5

**Comment by jsteemann** [comment]
What `--ssl.protocol` value is the arangod server running with? If the client (arangorestore) uses `4`, the server should also be using the value `4`.

Please note that the default value for `--ssl.protocol` [was changed from 4 to 5 in 3.2](https://github.com/arangodb/arangodb/blob/devel/Documentation/Books/Manual/ReleaseNotes/UpgradingChanges32.md#command-line-options-changed).

**Comment by ThomasWeiss** [comment]
The server is running 4 (my client code couldn't connect with 5) but I didn't realize that you could also set the protocol on arangorestore, will try that!

________________________________

**Comment by ThomasWeiss** [comment]
Verified, it works if the `ssl.protocol` parameter on arangodump matches the server parameter.
