### ISSUE TITLE
Arangodb 3.2 edge collection index issue

### ISSUE THREAD

**Issue by livingroom** [arangodb/arangodb#3000]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 3.2

Mode:
- [ ] Cluster

Storage-Engine:
- [ ] rocksdb

On this operating system:
- [ ] Linux 
  - [ ] RedHat .rpm

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:

The AQL query in question is:

for d in aaaaa
filter d._to == 'Company/a'
return d

The issue can be reproduced using this dataset:
1. create an edge collection
2. insert any edge

The following problem occurs: [Screenshot?] 
![image](https://user-images.githubusercontent.com/1314361/29112663-231f66ca-7d21-11e7-9568-a4cab7c7a661.png)

![image](https://user-images.githubusercontent.com/1314361/29112755-6734b02c-7d21-11e7-9f2b-3cf22091c7e0.png)

not found 'Company/b' with '==':
![image](https://user-images.githubusercontent.com/1314361/29112869-d9cf7b26-7d21-11e7-945f-85c8824db69f.png)

found 'Company/b' with 'like':
![image](https://user-images.githubusercontent.com/1314361/29112933-0fbfa5a8-7d22-11e7-99a5-3e972826dc29.png)

wrong with 'arangosh' either:
![image](https://user-images.githubusercontent.com/1314361/29113472-a972652c-7d23-11e7-808f-b0c1fa1b360d.png)

Instead I would be expecting:

**Comment by jsteemann** [comment]
I have tried to reproduce this with a local cluster but was not able to reproduce the problem.
I tried with default sharding configuration as I did not know what configuration you used. How many shards does the edge collection have and what is its shard key?
Have you experienced the problem with an otherwise empty collection or did it contain a lot of documents?

**Comment by livingroom** [comment]
i explained the AQL, i found the fields is not right, it's [ `_from`, `_to` ], not [ `_to` ]。
![image](https://user-images.githubusercontent.com/1314361/29115127-066f4f1a-7d29-11e7-89d5-0c44ff20dc65.png)

**Comment by jsteemann** [comment]
That should not make a difference. As can be seen in the "Ranges" section right to what you have highlighted, the condition is correct (`d._to == "Company/b"`).
Are you sure you are using the RocksDB engine as pointed out above? To me it looks like the MMFiles engine is actually used.

**Comment by livingroom** [comment]
Yes, i am sure. It's RocksDB.
![image](https://user-images.githubusercontent.com/1314361/29115482-70a4dc0a-7d2a-11e7-8de7-38d15dc65117.png)

**Comment by jsteemann** [comment]
Ok. Was just irritated by the explain output showing the edge index on `[ "_from", "_to" ]` and not just `[ "_to" ]`. Thought this would not be happening in the RocksDB engine but will verify.

**Comment by livingroom** [comment]
I start up 1 coordinator, 1 agent, 3 primary db on 3 machines。

coordinator start:
arangod \
    -c none \
    --daemon true \
    --supervisor true \
    --temp.path $DIR/tmp \
    --server.authentication false \
    --javascript.startup-directory /usr/share/arangodb3/js \
    --javascript.app-path $DIR/apps \
    --javascript.v8-contexts 10 \
    --log.level startup=info --log.level queries=info --log.level info \
    --log.use-local-time \
    --database.directory $DIR/data \
    \
    --pid-file $DIR/run/coordinator.pid \
    --log.file $DIR/run/coordinator.log \
    \
    --server.endpoint tcp://${SELF_PRIVATE_IP}:18530 \
    --cluster.my-address tcp://${SELF_PRIVATE_IP}:18530 \
    --cluster.my-local-info coord${SELF_PRIVATE_IP} \
    --cluster.my-role COORDINATOR \
    --cluster.agency-endpoint tcp://${AGENT1_IP}:5020 \

agent start:
arangod \
    -c none \
    --daemon true \
    --supervisor true \
    --pid-file $DIR/run/agent.pid \
    --temp.path $DIR/tmp \
    --server.endpoint tcp://${SELF_PRIVATE_IP}:5020 \
    --server.authentication false \
    --javascript.startup-directory /usr/share/arangodb3/js \
    --javascript.app-path $DIR/apps \
    --log.level startup=info --log.level queries=info --log.level info \
    --log.file $DIR/run/agent.log \
    --log.use-local-time \
    --database.directory $DIR/data \
    --agency.activate true \
    --agency.size 1 \
    --agency.supervision true

primary db start:
arangod \
    -c none \
    --server.storage-engine rocksdb \
    --daemon true \
    --supervisor true \
    --temp.path $DIR/tmp \
    --server.authentication false \
    --javascript.startup-directory /usr/share/arangodb3/js \
    --javascript.app-path $DIR/apps \
    --log.level startup=info --log.level queries=info --log.level info \
    --log.use-local-time \
    --database.directory $DIR/data \
    \
    --pid-file $DIR/run/primary_db_server.pid \
    --log.file $DIR/run/primary_db_server.log \
    \
    --server.endpoint tcp://${SELF_PRIVATE_IP}:18558 \
    --cluster.my-address tcp://${SELF_PRIVATE_IP}:18558 \
    --cluster.my-local-info db${SELF_PRIVATE_IP} \
    --cluster.my-role PRIMARY \
    --cluster.agency-endpoint tcp://${AGENT1_IP}:5020 \

-------------------------------------------------------------------

Should configuration '--server.storage-engine rocksdb'  config in agent & coordinator too?

**Comment by livingroom** [comment]
I add '--server.storage-engine rocksdb' in agent & coordinator, clean the environment, restart the cluster. And it helped.
