### ISSUE TITLE
Transaction behavior with RocksDB

### ISSUE THREAD

**Issue by ThomasWeiss** [arangodb/arangodb#3006]
I would like to clarify the behavior of transactions when using the RocksDB storage engine.

1. We have to catch write conflicts but the documentation doesn't exhibit how to do that. From Foxx, would it be something like:
```
try { 
  my write operation
}
catch (error) { 
 if (error.errorNum == 1200) { that's a conflict? }
}
```

2. Is there a recommended way to retry conflicts from within Foxx? I guess that retrying right away would have high chances to hit the same conflict?

3. The [documentation](https://docs.arangodb.com/3.2/Manual/Transactions/Limitations.html#transactions-in-the-rocksdb-storage-engine) states that transactions have a maximum size and will be chunked if they go beyond a threshold; does that mean that those chunked transactions are not ACID?

4. What are the default values of
```
--rocksdb.max-transaction-size
--rocksdb.intermediate-commit-size
--rocksdb.intermediate-commit-count
```
Thanks in advance.

**Comment by ThomasWeiss** [comment]
Regarding my second point, would that code be suitable to retry within Foxx?
```
var internal = require("internal");
function tryInsert(collection, document) {
    var done = false;
    var retries = 0;
    var result = null;
    while (!done && (retries < 10)) {
        try {
            result = collection.insert(document);
            done = true;
        }
        catch (err) {
            if (err.errorNum == 1200) {
                internal.sleep(.2 * retries);
                retries++;
            }
            else {
                throw err;
            }
        }
    }
    if (!done) {
        throw new Error("Could not insert document in collection " + collection._name);
    }
    return result;
}
```

**Comment by ObiWahn** [comment]
Hi Thomas,

from my understanding most operations are ACI. If you enable the `waitForSync` on a collection the operations will become ACI**D**.
This is true as long as the transactions are not split up! Else the atomic trait of the operation is lost and you might end up with parts of a transaction committed to RocksDB.

Your code looks good! I think you can use the `try catch` because in `js/client/modules/@arangodb/arango-collection.js` where insert is defined The `checkRequestResult` function is used that throws an exception, when an error occurred. Still the most general and stable way is to check the result of an operation. Just think about an insert with a list of items (1).

How fast you retry depends on your application. In many cases an [exponential backoff](https://en.wikipedia.org/wiki/Exponential_backoff) or a variant is worth considering.

The default values can be found in `arangod/Transaction/Options.cpp`
```c++
uint64_t Options::defaultMaxTransactionSize = UINT64_MAX;
uint64_t Options::defaultIntermediateCommitSize = 512 * 1024 * 1024;
uint64_t Options::defaultIntermediateCommitCount = 1 * 1000 * 1000;
```

(1) insert with list of documents
```javascript
0.0.0.0:5555@_system> db.test.insert([{},{}])
[ 
  { 
    "_id" : "test/101", 
    "_key" : "101", 
    "_rev" : "_Vc-8tui---" 
  }, 
  { 
    "_id" : "test/102", 
    "_key" : "102", 
    "_rev" : "_Vc-8tui--_" 
  } 
]
0.0.0.0:5555@_system> try { db.test.insert([{},{"_key":"101"}]) } catch(e) { print(e) }
[ 
  { 
    "_id" : "test/106", 
    "_key" : "106", 
    "_rev" : "_Vc_-Fie---" 
  }, 
  { 
    "error" : true, 
    "errorNum" : 1210, 
    "errorMessage" : "unique constraint violated" 
  } 
]
```

**Comment by ThomasWeiss** [comment]
Hi Jan,

Thanks a lot for your answer. So if I try to map that to my initial questions:
1. It's the right way to catch it - keeping in mind the case when you insert / update multiple documents at once.
2. My code snippet looks fine and could be improved with exponential backoff.
3. When using RocksDB, there is a risk that transactions get chunked and **are not ACID anymore** in that situation, i.e. only part of the transaction may be committed but not the rest (I think that should be stated in the documentation).
4. Default values are pretty high:
- `max-transaction-size` is basically infinite!
- `intermediate-commit-size` = 512KB
- `intermediate-commit-count` = 1 million

**Comment by ObiWahn** [comment]
Hi Thomas,

1. As long as you insert single documents try/catch is **OK**. If you pass arrays you **MUST** check the result.
2. You could try some sort of backoff, if you have some means to check within your applications that there are no concurrent writes you should use that special knowledge.
3. Correct **with intermediate commits** the atomicity and therefore the **AICD is lost**.

**Comment by xadhatter** [comment]
Wanted to leave a small note for others in case they stumble on this ticket looking for the RocksDB transaction settings defaults.

It appears the default for `intermediate-commit-size` is actually 512 MiB, not 512KiB as stated above (which had me a bit worried).

https://github.com/arangodb/arangodb/blob/511315c5000770f142f6861481811852261b9eb3/arangod/Transaction/Options.cpp#L34-L36

Thanks for all the thoughtful comments above, very helpful!
