### ISSUE TITLE
What does the automatic upgrade option do in v3.2 Windows installer?

### ISSUE THREAD

**Issue by Simran-B** [arangodb/arangodb#3007]
![image](https://user-images.githubusercontent.com/7819991/29122371-5d286254-7d12-11e7-8391-0c01fe97ea9c.png)

Is this intended to upgrade a v3.2.x installation in the future (e.g. 3.2.0 to 3.2.1)?

It does not upgrade or import the data from an existing v3.1 at least, but the option kind of suggests it would.

**Comment by dothebart** [comment]
The pre-beta manual explained that you need to copy the database directory (and where to put it). You can choose the installation directory _and_ the database directory if you set the checkmark you intend to do so. 

The behaviour is intended that way.
