### ISSUE TITLE
system database is always automatically selected when reopening web interface

### ISSUE THREAD

**Issue by grexe** [arangodb/arangodb#3008]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [X] 3.1
- [ ] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [X] Single-Server

Storage-Engine:
- [X] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [] Debian .deb
  - [X] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [X] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is a web interface-related issue:
I'm using the web interface with this browser: Chromen59.0.3071.115 running on this OS: Ubuntu 16.10 x64
- [X] authentication is enabled?
- [ ] using the cluster?
- [X] _system database?

These are the steps to reproduce:
1. open the browser on http://127.0.0.1:8529
1. log in as root
1. use database [ ] `_system` [X] other: any custom db
1. close the tab
1. open another tab to the web interface
1. you are automatically logged into the `_system` db instead of your previously selected custom db
...

The following problem occurs: _system db is opened
Instead I would be expecting: web interface should show my custom db as previously selected, or let me choose again.

This can lead to confusion at first, as you'd expect your DB would be reopened as last used, and you might wonder where your collections have gone...

**Comment by dothebart** [comment]
For security considerations we meanwhile have moved to session storage in the browser, and there won't be a way to persist this for subsequent logins anyways. 
Hence closing this as `won't fix`.
