### ISSUE TITLE
Upgrade V8 to version 7

### ISSUE THREAD

**Issue by dsonet** [arangodb/arangodb#3018]
That's would enable Turbo Fan + Ignition, should gain performance boost and improves memory consumption.
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2

Storage-Engine:
- [x] mmfiles
- [x] Windows, version: 10
- [x] MacOS, version: 12

**Comment by Simran-B** [comment]
V8 v6.1 was released August 3rd: https://v8project.blogspot.de/2017/08/v8-release-61.html

It can optionally compile asm.js code to WebAssembly, not sure if that would benefit anyone.

**Comment by dsonet** [comment]
This article also include benchmarks:
https://www.nearform.com/blog/node-js-is-getting-a-new-v8-with-turbofan/

I wish that Arangodb team can upgrade the v8 engine soon to gain performance boost on current version, since my API based on foxx.

**Comment by dsonet** [comment]
@Simran-B About the asm.js part, I think that would benefit someone

**Comment by dsonet** [comment]
Actually as an alternative, maybe you should consider to use another engine since they focus on use v8 as a fast application server(no callbacks, not like nodejs ), and I think it match what Arangodb needs. Then your team can  focus on db side only.

That engine is here: https://github.com/fibjs/fibjs

**Comment by dothebart** [comment]
Hi, 
We will do the next V8 upgrade after the 3.3 release cycle. 
Some of the V8 interface already changed (and arangodb needs to be adapted to follow that) which is why we didn't get that done in the already tight 3.2 release cycle.

**Comment by dsonet** [comment]
Will we can see the upgrade version in 3.4? Since v8 already evolved to version 6.7...
Thanks.

**Comment by dothebart** [comment]
Current devel now has V8 7.1; We leaned on nodejs here, since they maintain the upstream gyp build, and we didn't want to change all our build infrastructure to support GN.

**Comment by maxkernbach** [comment]
Closing as fixed since V8 is upgraded to version 7.1 in 3.5.
The latest Release Candidate of ArangoDB 3.5 can be found in the [download section](https://www.arangodb.com/download-technical-preview/).

Please note that a Release Candidate is for testing purposes only, not for production usage!
