### ISSUE TITLE
Arangorestore not creating initial user when using --create-database

### ISSUE THREAD

**Issue by karjaneth** [arangodb/arangodb#3023]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2

Mode:
- [x] Single-Server

Storage-Engine:
- [x] mmfiles

On this operating system:
- [x] Linux 
  - [x] docker - official docker library

### The following problem occurs:
[The `arangorestore` docs](https://docs.arangodb.com/3.2/Manual/Administration/Arangorestore.html#invoking-arangorestore) seem to indicate that when using `--create-database` and specifying a user, it will create the user along with creating the database. This doesn't seem to be working, and instead gives a 401 Unauthorized error. Running `arangorestore` and passing in the user as `root` does work as expected. Am I misunderstanding what it would mean to "create an initial user for the new database"?

#### Command that doesn't work
```
root@6fdb1cf72345:/# arangorestore \
  --log=debug \
  --input-directory backup \
  --create-database true \
  --server.database database_name \
  --server.username database_user \
  --server.password password
{config} found config file '//etc/arangodb3/arangorestore.conf'
{config} loading override '//etc/arangodb3/arangorestore.conf.local'
{config} loading '//etc/arangodb3/arangorestore.conf'
2017-08-11T13:20:46Z [210] DEBUG connecting to ip endpoint 'http+ssl://127.0.0.1:8529'
Creating database 'database_name'
2017-08-11T13:20:46Z [210] DEBUG connecting to ip endpoint 'http+ssl://127.0.0.1:8529'
2017-08-11T13:20:47Z [210] ERROR Could not create database 'database_name'
2017-08-11T13:20:47Z [210] FATAL got error from server: HTTP 401 (Unauthorized)'
```

#### Command that does work
```
root@6fdb1cf72345:/# arangorestore \
  --log=debug \
  --input-directory backup \
  --create-database true \
  --server.database database_name \
  --server.username root \
  --server.password password
{config} found config file '//etc/arangodb3/arangorestore.conf'
{config} loading override '//etc/arangodb3/arangorestore.conf.local'
{config} loading '//etc/arangodb3/arangorestore.conf'
2017-08-11T13:14:20Z [199] DEBUG connecting to ip endpoint 'http+ssl://127.0.0.1:8529'
Creating database 'database_name'
2017-08-11T13:14:20Z [199] DEBUG connecting to ip endpoint 'http+ssl://127.0.0.1:8529'
Server version: 3.2.0
# Connected to ArangoDB 'http+ssl://127.0.0.1:8529'
... <creating documents and loading data> ...
Processed 4 collection(s), read 2435 byte(s) from datafiles, sent 3 batch(es)
```

**Comment by mchacki** [comment]
If you are restoring data into an authenticated ArangoDB instance.
It is required, that you pass in a user that has Access Rights on the `_system` database in the ArangoDB you restore into.

It is not possible to create an entirely new user with this feature, who does not have access to anything before.
(If this would be possible, you could easily bypass all authentication by using this methods)

So could you try the following:
1. Create a new Users with the given Name and Password.
2. Give this User Administrative Access on `_system` Database.
3. Restore with this user.

**Comment by karjaneth** [comment]
OK that makes sense. Maybe the documentation should be updated to specify that the user specified needs to already exist, rather than stating that it will create the user. As it is, I'll just create the database up front and specify the user there, then restore to that database.

**Comment by maxkernbach** [comment]
Closing this issue as the documentation is updated.
