### ISSUE TITLE
Foxx app installation from Web UI fails with error Services: 3103. failed to invoke module File: /var/lib/arangodb3-apps/_db/db_name/auth/APP/scripts/setup.js

### ISSUE THREAD

**Issue by chrisshaw** [arangodb/arangodb#3030]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [x] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [x] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [x] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is a web interface-related issue:
I'm using the web interface with this browser: Version 60.0.3112.90 (Official Build) (64-bit)    running on this OS: macOS Sierra 10.12.6 (16G29)
- [x] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as dbadmin
3) use database [ ] `_system` [x] other: skdb
4) click to Services
5) Click Add Service
6) Specify mount as /auth
7) Drag and drop foxx.zip
8) Observe error in UI: Services: 3103. failed to invoke module File: /var/lib/arangodb3-apps/_db/skdb/auth/APP/scripts/setup.js
9) Click install
10) Observe error in UI: Services: 500. Internal Server Error

The following problem occurs: https://cl.ly/3q280h1g2v2N
Instead I would be expecting: auth foxx microservice installs correctly.

**Comment by chrisshaw** [comment]
#2910

**Comment by mpv1989** [comment]
@chrisshaw is it also working for you with 3.2.1? can we close this?

**Comment by dothebart** [comment]
Closing this as abandoned.
