### ISSUE TITLE
Foxx, internal server error when I try to add a new service

### ISSUE THREAD

**Issue by macscripter** [arangodb/arangodb#3037]
VERSION 3.2.1
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [v] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [ ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [v] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [ ] using the cluster?
- [X ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as root (in my case)
3) go to services
4) add service
5) select (already selected by default) store
6) mount /test
7) install

--> Internal Server Error:

![image](https://user-images.githubusercontent.com/15846597/29318051-6a7b8ce8-81c6-11e7-93d3-e9d2619217c6.png)

The following problem occurs: [Screenshot?] 
![image](https://user-images.githubusercontent.com/15846597/29317913-fe07687a-81c5-11e7-9fbc-64010d630c13.png)

Instead I would be expecting: 

Service has been installed successfully...

**Comment by jsteemann** [comment]
Fixed in 3.2.2

**Comment by alexpavlovaskblue** [comment]
Nice! Thank you! When can I download it?
Cheers

**Comment by dothebart** [comment]
ArangoDB 3.2.2 containing this bugfix is available for download - thanks for reporting.

Closing.

**Comment by alexpavlovaskblue** [comment]
Really fantastic news! Thanks a lot! Good job!

El 24 ago. 2017 3:11 p. m., Wilfried Goesgens <notifications@github.com> escribió:

ArangoDB 3.2.2 containing this bugfix is available for download - thanks for reporting.

Closing.
