### ISSUE TITLE
pyArango throws "collection name" not found in edge defintions error

### ISSUE THREAD

**Issue by kavin26** [arangodb/arangodb#3052]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ *] 3.1
- [ ] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [* ] Single-Server

Storage-Engine:
- [* ] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ *] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [* ] this Driver:
pyArango - python driver for arangodb

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:
`doc_word_edge_creation = theGraph.createEdge('doc_word_relation',doc_vertex_id,word_vertex_id,{'tf':term_freq,'absolute_frequency':abs_freq})`

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click to ...
...

The following problem occurs: [Screenshot?] 
`Traceback (most recent call last):
  File "/home/kavin/Desktop/video-reco/document-graph.py", line 145, in <module>
    doc_word_edge_creation = theGraph.createEdge('doc_word_relation',doc_vertex_id,word_vertex_id,{'tf':term_freq,'absolute_frequency':abs_freq})
  File "/usr/local/lib/python2.7/dist-packages/pyArango/graph.py", line 124, in createEdge
    raise KeyError("'%s' is not among the edge definitions" % collectionName)
KeyError: "'doc_word_relation' is not among the edge definitions"`

Instead I would be expecting: 
The edge needs to be created without any error, as proper edge definitions been given before creating graph.
[pyarango.zip](https://github.com/arangodb/arangodb/files/1230426/pyarango.zip)

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

**Comment by ObiWahn** [comment]
Please report the bug here [pyArango - issues](https://github.com/tariqdaouda/pyArango/issues) and read & understand the examples, that have been provided on the community slack:

```
dothebart.arangodb
4:24 PM @kavin you need to create an edge relation along with the graph
4:24 PM did you have a look at: https://github.com/tariqdaouda/pyArango/blob/master/examples/createSocialGraph.py
4:24 PM its the translation of https://github.com/arangodb/arangodb/blob/devel/js/common/modules/%40arangodb/graph-examples/example-graph.js#L56
```

Closing as this driver question is not directly related to ArangoDB itself but a 3rd party lib.
