### ISSUE TITLE
Databases management

### ISSUE THREAD

**Issue by alexalexpod** [arangodb/arangodb#3058]
Hello.

I plan to create thousands graphs for my business purposes.
How would you suggest to store and manage them?
Should I need to create one huge DB and store all the collections and graphs there or should I split them into hundreds of small databases and manage them separately?

Thanks, Alex.

**Comment by Simran-B** [comment]
By thousands of graphs, do you mean rather smallish sets of vertices that are connected by edges (subgraphs)?

![image](https://user-images.githubusercontent.com/7819991/29417032-2521eee6-8368-11e7-9553-78739e990ef4.png)

Each subgraph could represent a workflow or some other kind of "closed" unit (no connections to other subgraphs).

Or is one graph in your definition a community (groups of vertices with many interconnections) in a large graph?

![image](https://user-images.githubusercontent.com/7819991/29417282-f902c096-8368-11e7-9ebf-febee066d87c.png)

Or is each actually a large network, and the nodes per graph have no common attributes or serve completely different purposes?

**Comment by alexalexpod** [comment]
Hi.
I mean thousands of large networks.
Thanks, Alex.

**Comment by alexalexpod** [comment]
Thank you very much.
