### ISSUE TITLE
C# Driver with Network Topology Interface

### ISSUE THREAD

**Issue by weedkiller** [arangodb/arangodb#3066]
Hello, are you planning to support a C# driver to enable network interface model.

Network Interface Nodes:

- Get/Put Nodes
- Get optimal routes between notes
- Configure load metrics on the vertexes
- Display graph

**Comment by dothebart** [comment]
Hi, 
If I get that correctly you're trying to do a [graph query](https://docs.arangodb.com/3.2/Manual/Graphs/)?

So in terms of the driver accessing the database you only need the AQL interface, which is provided by both community c# drivers.

If you want to create custom REST routes you can use the FOXX framework on the server side.

**Comment by dothebart** [comment]
Hi, 
If you still have questions, don't hesitate to ask. 
I will close this now due to inactivity.

**Comment by weedkiller** [comment]
Hi I would like to see a sample posted - with C#... this is turning out complex to port over.

We did it with MS Graph and Neo4j, both were doable but not easy..

**Comment by dothebart** [comment]
Could you show what you already have and tell where it falls short?

**Comment by weedkiller** [comment]
I already described it earlier..

> Network Interface Nodes:
> 
> Get/Put Nodes
> Get optimal routes between notes
> Configure load metrics on the vertexes
> Display graph

**Comment by dothebart** [comment]
Hi, we offer this graph course that helps you learn howto implement it in Arangodb: https://arangodb.com/arangodb-graph-course/
