### ISSUE TITLE
Add index in _jobs collection

### ISSUE THREAD

**Issue by ThomasWeiss** [arangodb/arangodb#3070]
Just a suggestion:

The `_jobs` collection does not have any custom index. I guess that each queue that processes jobs issues queries like `FOR j IN _jobs FILTER j.queue == 'queue-name' && j.status == 'pending' SORT j.created LIMIT 1 RETURN j`. Considering that completed jobs don't get automatically deleted from the collection, this query always takes more and more time (and memory) to execute. If we added a skiplist index on `[queue, status, created]`, that query would have constant execution time and make job queues more efficient.

**Comment by dothebart** [comment]
Hi, this has been implemented with ArangoDB 3.2.4 which is available for download. Closing.
