### ISSUE TITLE
Cannot yum update arangodb 3.1 in Centos 6

### ISSUE THREAD

**Issue by georgekaf** [arangodb/arangodb#3071]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.1

- [x] Linux 
  - [x] Centos .rpm

### this is an installation-related issue:

When I try to update arangodb 3.1 I get 
`https://www.arangodb.com/repositories/arangodb31/CentOS_6/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not 
Found"`

**Comment by jsteemann** [comment]
I confirm that the file "repomd.xml" is missing.

**Comment by jsteemann** [comment]
@dothebart: can you have a look?

**Comment by dothebart** [comment]
hm, somehow this got lost on the RSync from the build platform to the webserver - fixed.
