### ISSUE TITLE
Query performance difference between 3.1 and 3.2/RocksDB

### ISSUE THREAD

**Issue by ThomasWeiss** [arangodb/arangodb#3082]
I'm filing this as an issue here following the suggestion of Claudius @weinberger on Slack.

We're considering the migration of a production system that's currently running on 3.1.21 to 3.2.1 with RocksDB, and so we're in the process of evaluating the performance of queries on 3.2.1 with production data. Here's some context:
- Production database running 3.1.21 on 8 cores + 28GB of RAM
- Test database running 3.2.1 / RocksDB on 2 cores + 7GB of RAM
- Production dump restored to the test database
- Queries issued on a collection containing 12+ millions documents
- That collection has a skiplist index on the `[targetKey, lastPublishedAt]` fields
- Query issued: `for s in shares filter s.targetKey == '2881321' sort s.lastPublishedAt desc return s` from the web dashboard, returning 1,000 documents

Performance (as reported by the web dashboard):
- On 3.2.1, "cold" query (first run): ~900ms
- On 3.2.1, "warmed up" query: ~15ms (consistent)
- On 3.1.21: ~1ms (consistent)

**Comment by jsteemann** [comment]
Can you provide the query execution plans for the query for the two versions (3.1.21 w/MMFiles and 3.2.1 w/RocksDB)?
Thanks.

**Comment by ThomasWeiss** [comment]
Sure!

**On 3.1.21 / mmfiles:**
```
Query string:
 for s in shares filter s.targetKey == '2881321' sort s.lastPublishedAt desc return s

Execution plan:
 Id   NodeType          Est.   Comment
  1   SingletonNode        1   * ROOT
  8   IndexNode       667011     - FOR s IN shares   /* reverse skiplist index scan */
  7   ReturnNode      667011       - RETURN s

Indexes used:
 By   Type       Collection   Unique   Sparse   Selectivity   Fields                               Ranges
  8   skiplist   shares       false    false            n/a   [ `targetKey`, `lastPublishedAt` ]   (s.`targetKey` == "2881321")

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   move-calculations-up-2
  4   move-filters-up-2
  5   use-indexes
  6   remove-filter-covered-by-index
  7   use-index-for-sort
  8   remove-unnecessary-calculations-2
```
**On 3.2.1 / RocksDB:**
```
Query string:
 for s in shares filter s.targetKey == '2881321' sort s.lastPublishedAt desc return s

Execution plan:
 Id   NodeType          Est.   Comment
  1   SingletonNode        1   * ROOT
  8   IndexNode       639104     - FOR s IN shares   /* reverse skiplist index scan */
  7   ReturnNode      639104       - RETURN s

Indexes used:
 By   Type       Collection   Unique   Sparse   Selectivity   Fields                               Ranges
  8   skiplist   shares       false    false        92.83 %   [ `targetKey`, `lastPublishedAt` ]   (s.`targetKey` == "2881321")

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   move-calculations-up-2
  4   move-filters-up-2
  5   use-indexes
  6   remove-filter-covered-by-index
  7   use-index-for-sort
  8   remove-unnecessary-calculations-2
```

**Comment by jsteemann** [comment]
Ok. Both execution plans look good.
How many documents are returned by the query and how big are they (in bytes, approximately)?

**Comment by ThomasWeiss** [comment]
Both queries return the same results (they run on the same data): 1,000 documents (the default limit, there are more docs to return) and each doc is of the following format:
```
{
  "_key": "150519348",
  "_id": "shares/150519348",
  "_rev": "_VdOnWfa---",
  "contentId": "keaks/150061787",
  "contentType": "keak",
  "lastPublishedAt": "2017-08-18T07:05:37.9362982Z",
  "publications": [
    {
      "id": "hasPublished/150733557",
      "publishedAt": "2017-08-18T07:05:37.9362982Z",
      "publisherId": "users/13106335"
    },
    {
      "id": "hasPublished/150492830",
      "publishedAt": "2017-08-18T05:09:32.6269388Z",
      "publisherId": "users/22920404"
    }
  ],
  "relevanceScore": 0,
  "targetKey": "2881321"
}
```

**Comment by jsteemann** [comment]
The performance difference may be explained by the fact that the RocksDB engine will have to copy these documents into the result, whereas the MMFiles engine can simply point to them (using plain memory pointers). 
The latter (MMFiles) is much cheaper, but requires all the documents to stay present in RAM while the query is running. RocksDB does not provide this guarantee by default so we have to copy the documents data out of it. This will be the more expensive the more documents there are in the result (or intermediate results) and the bigger these documents are.

On the plus side, the RocksDB engine does not require all the documents to stay in memory, so it can handle collections of bigger sizes than the MMFiles, and/or can work with a limited amount of RAM - both of which were design goals of this storage engine.

I am not saying this cannot be optimized any further, however, even if optimized, the RocksDB engine will have to copy data out whereas the MMFiles engine does not have to.

**Comment by ThomasWeiss** [comment]
That makes sense: I have tested again by limiting the number of results: `for s in shares filter s.targetKey == '2881321' sort s.lastPublishedAt desc limit 25 return s` and the difference now is:
- 3.1.21 / mmfiles: ~0.275ms
- 3.2.1 / RocksDB: ~0.900ms

**Comment by dothebart** [comment]
Hi, 
ArangoDB 3.7 is available for download. 
https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/
Multiple versions of rocksdb have been used meanwhile, optimisations have been done. 
Closing this as 'outdated'
