### ISSUE TITLE
Query performance: very slow!

### ISSUE THREAD

**Issue by namnik** [arangodb/arangodb#3083]
- [ ] 3.0
- [ ] Single-Server
- [ ] Windows, version: Server 2008 R2
- [ ]  Driver: C# ; ArangoDB-NET

Hi,
I Have 141,315 doc in User(Collection) and 174,111 edges in Contact( Edge Collection).
now my queries performance are very terrible!. for example:

<code>
          string query = "FOR u IN User FILTER u.UserId ==@userId  RETURN u._id";
            string userkey = Context.Query.BindVar("userId", userId).Aql(query).ToObject().Value.ToString();
</code>

UserId  defined as a hash index because of Unique field.
this query some times takes 30 second! in the worst time takes 2 minute!

also, I wrote my queris using foxx, and call them into c# (using HttpClient), but result was worst than Driver's calling (Arangodb-net).
....?

**Comment by jsteemann** [comment]
Can you show the query execution plan of that query?
You can retrieve it by running `db._explain(queryString, bindParameters);` from the ArangoShell.
Thanks!

**Comment by namnik** [comment]
because of I  didn't have permission for upload  direct form my local machine!; I have to upload in follow url:
http://s8.picofile.com/file/8304180342/1503311

**Comment by jsteemann** [comment]
Thanks. Next time you can also copy&paste the query execution plan output from the shell into a comment. That's easier than screenshot uploading.

As it seems (at least it's shown in the execution plan screenshot) the query does not use any index. So it will always fully scan the entire `User` collection. To speed up the query, it would be good to add a hash index on `UserId`.
It's probably not there yet, otherwise that query would have used it. You can verify which indexes are there by running the following command:
```js
db.User.getIndexes()
```
To create the index, use:
```js
db.User.ensureIndex({ type: "hash", fields: ["UserId"], unique: true });
```
(not sure if the index is supposed to be unique or not - change as required).

**Comment by namnik** [comment]
thanks a lot for response;
but in my Main DB, I have been added Index for UserId field!
notice!: UserId sometimes nee to update!

**Comment by jsteemann** [comment]
Can you post the result of `db.User.getIndexes()` here?

**Comment by namnik** [comment]
> db.User.getIndexes();
[
  {
    "id" : "User/0",
    "type" : "primary",
    "fields" : [
      "_key"
    ],
    "selectivityEstimate" : 1,
    "unique" : true,
    "sparse" : false
  },
  {
    "id" : "User/21332279",
    "type" : "hash",
    "fields" : [
      "UserId"
    ],
    "selectivityEstimate" : 1,
    "unique" : true,
    "sparse" : true
  }
]

**Comment by jsteemann** [comment]
Can you try making the index non-sparse?

**Comment by jsteemann** [comment]
I tried running the same query in 3.0 (3.0.12), and it uses the index when I try it.
I have added a sparse unique hash index by the way.
Are you sure you are executing the query in the same database that you have retrieved the indexes for? If there are multiple databases with a "User" collection, does the "correct" one have the index.
Which exact ArangoDB version are you actually using?

**Comment by jsteemann** [comment]
Ok, the latest explain result shows that the query is using indexes.
If indexes are used just with non-sparse indexes in your ArangoDB version, then the fix is to make the index non-sparse.
For my version of ArangoDB (3.0.12) the query makes use of a sparse index as well, so there may have been a bugfix for this in 3.0.11 or 3.0.12.

**Comment by namnik** [comment]
thanks.
when publish and run my webAPIs(C#) on the local machine(windows 8, with normal hardware config), the performance is very good. but on the server(2008 R2, with good hardware config), performance is terrible.
a Scenario:
140,000 doc in User(Collection) and 175,000 edges in Contact( Edge Collection).
Get Contacts of a User: (result : 200 edge)
on the local machine: 10 millisecond, and in worst times 100 millisecond
on the server : some times 1 second, some times 10 second, and in the worst times 1 minute!

**Comment by jsteemann** [comment]
Does your server have the non-sparse index on the collection, and is the index used when you run the query on the server? Explaining the query on the server will show this.
By the way, the only collection that matters for the query you posted here is "User". As you are refererring to other collections as well, I am not sure if we are talking about the same query. If you are referring to a different query that also queries contacts, please post the query string and the explain output here too. Thanks!

**Comment by namnik** [comment]
Is exists any way for rebuilding (Reorganize)  Indexes in Arangodb?
Can any way for understand that indexes act as a good performance or bad affect?
can any way for monitoring?

thanks a lot.

**Comment by namnik** [comment]
some of my ArangoDb logs:

2017-08-15T16:35:06Z [1176] WARNING {queries} slow query: 'UPDATE { _key: @userKey }  WITH { UserAppState: @userAppState } IN User', took: 112.709447

2017-08-22T17:29:36Z [1176] WARNING {queries} slow query: 'for u in User for e in EdgeContact filter u.UserId ==  @contactId  and e._from== @userKey and e._to==u._id  AND e.Deleted == false AND u.UserAppState != 4 return { ContactId:u.UserId, ContactAppState:u.UserAppState, ContactFirstName:e.ContactFirstName, ContactLastName:e.ContactLastName, ContactMobileNum:e.HiddenMob==true?'':u.MobileNum}', took: 75.205302

2017-08-23T09:45:22Z [1176] WARNING {queries} slow query: 'FOR u IN User FILTER u.UserId ==@userId  RETURN u._key',  took: 67.678871

2017-08-23T09:45:22Z [1176] WARNING {queries} slow query: 'FOR u IN User FOR c IN EdgeContact FILTER c._from == @userkey AND u._id==c._to  AND c.Deleted == false  and u.UserAppState IN @appStates  RETURN {ContactMobileNum : c.HiddenMob==true   ? '' : u.MobileNum,ContactId : u.UserId,ContactFirstName : c.ContactFirstName,ContactLastName : c.ContactLastName,ContactAppState : u.UserAppState}', took: 79.846567

**Comment by namnik** [comment]
and the explain one of queries:
####:@####> db._explain("FOR u IN User FILTER u.UserId ==6  RETU
RN u._key")
Query string:
 FOR u IN User FILTER u.UserId ==6  RETURN u._key

Execution plan:
 Id   NodeType                    Est.   Comment
  1   SingletonNode                  1   * ROOT
  2   EnumerateCollectionNode   151082     - FOR u IN User   /* full collection
scan */
  3   CalculationNode           151082       - LET #1 = (u.`UserId` == 6)   /* s
imple expression */   /* collections used: u : User */
  4   FilterNode                151082       - FILTER #1
  5   CalculationNode           151082       - LET #3 = u.`_key`   /* attribute
expression */   /* collections used: u : User */
  6   ReturnNode                151082       - RETURN #3

Indexes used:
 none

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   move-calculations-up-2
  4   move-filters-up-2

**Comment by jsteemann** [comment]
Can you please create the non-sparse hash index on "User"."UserId" as suggested?
The explain shows that no index is used, so such index is probably not there. Please verify on the same server that the index is actually there, and that its attributes are set correctly.

You can do so by running the following command in the ArangoShell:
```js
db.User.ensureIndex({ type: "hash", sparse: false, fields: ["UserId"] });
```
If the (correct) indexes are missing on the (correct) server, the queries will remain slow.

**Comment by namnik** [comment]
when call explain on the my query, I have been deleted hash index just for test!
yes, I'm sure that my collection has hash index.

**Comment by jsteemann** [comment]
I can't find any difference between 3.0.10 and latest 3.0 that would explain why the index is used in my local setup (3.0.12) but not yours (3.0.10). So I guess either the index is either not present, not created with the right parameters, or that we are not looking at the correct collection (maybe there are different databases on the server and more than one have a "User" collection??).

It would be helpful if you could run the explain on the server when the index is actually present. Otherwise we'll always see that no index will be used. But if the index is there and correctly set up, then it should be used by the query.
Can you therefore please verify it is non-sparse and set up on the correct attribute, on the correct collection, correct database and correct server?
After having done that, and only if the index is present, can you then post the results of `db.User.getIndexes();` plus the explain output for that query for the same server, same database, same collection?

**Comment by namnik** [comment]
arangosh test on the Main Server:

1- with index(UserId field): spars= false
#####@db> db.User.getIndexes();
[
  {
    "id" : "User/0",
    "type" : "primary",
    "fields" : [
      "_key"
    ],
    "selectivityEstimate" : 1,
    "unique" : true,
    "sparse" : false
  },
  {
    "id" : "User/42695564",
    "type" : "hash",
    "fields" : [
      "UserId"
    ],
    "selectivityEstimate" : 1,
    "unique" : true,
    "sparse" : false
  }
]
#####@db> db._explain("for u in User filter u.UserId==6 return
 u");
Query string:
 for u in User filter u.UserId==6 return u

Execution plan:
 Id   NodeType        Est.   Comment
  1   SingletonNode      1   * ROOT
  6   IndexNode          1     - FOR u IN User   /* hash index scan */
  5   ReturnNode         1       - RETURN u

Indexes used:
 By   Type   Collection   Unique   Sparse   Selectivity   Fields         Ranges
  6   hash   User         true     false       100.00 %   [ `UserId` ]   (u.`Use
rId` == 6)

Optimization rules applied:
 Id   RuleName
  1   use-indexes
  2   remove-filter-covered-by-index
__________________________________________________________________________________

2- with index(UserId field): spars= true

#####@db> db.User.getIndexes()
[
  {
    "id" : "User/0",
    "type" : "primary",
    "fields" : [
      "_key"
    ],
    "selectivityEstimate" : 1,
    "unique" : true,
    "sparse" : false
  },
  {
    "id" : "User/43000127",
    "type" : "hash",
    "fields" : [
      "UserId"
    ],
    "selectivityEstimate" : 1,
    "unique" : true,
    "sparse" : true
  }
]
#####@db> db._explain("for u in User filter u.UserId==6 return
 u");
Query string:
 for u in User filter u.UserId==6 return u

Execution plan:
 Id   NodeType        Est.   Comment
  1   SingletonNode      1   * ROOT
  6   IndexNode          1     - FOR u IN User   /* hash index scan */
  5   ReturnNode         1       - RETURN u

Indexes used:
 By   Type   Collection   Unique   Sparse   Selectivity   Fields         Ranges
  6   hash   User         true     true        100.00 %   [ `UserId` ]   (u.`Use
rId` == 6)

Optimization rules applied:
 Id   RuleName
  1   use-indexes
  2   remove-filter-covered-by-index
__________________________________________________________________________________

3- without Index:

#####@db> db.User.getIndexes();
[
  {
    "id" : "User/0",
    "type" : "primary",
    "fields" : [
      "_key"
    ],
    "selectivityEstimate" : 1,
    "unique" : true,
    "sparse" : false
  }
]

#####@db> db._explain("for u in User filter u.UserId==6 return
 u");
Query string:
 for u in User filter u.UserId==6 return u

Execution plan:
 Id   NodeType                    Est.   Comment
  1   SingletonNode                  1   * ROOT
  2   EnumerateCollectionNode   155696     - FOR u IN User   /* full collection
scan */
  3   CalculationNode           155696       - LET #1 = (u.`UserId` == 6)   /* s
imple expression */   /* collections used: u : User */
  4   FilterNode                155696       - FILTER #1
  5   ReturnNode                155696       - RETURN u

Indexes used:
 none

Optimization rules applied:
 none
__________________________________________________________________________________________________
Some logs:

Warning	2017-08-26 11:12:58	{queries} slow query: 'FOR u IN User FILTER u.UserId ==@userId RETURN u._id', took: 12.502715
Warning	2017-08-26 11:12:58	{queries} slow query: 'FOR u IN User FILTER u.UserId ==@userId RETURN u._id', took: 42.668440
Warning	2017-08-26 11:12:58	{queries} slow query: 'FOR u IN User FILTER u.UserId == @userId RETURN u.MobileNum', took: 133.789652
Warning	2017-08-26 11:12:58	{queries} slow query: 'FOR u IN User FILTER u.UserId ==@userId RETURN u._id', took: 54.972144
Warning	2017-08-26 11:12:58	{queries} slow query: 'FOR u IN User FILTER u.UserId ==@userId RETURN u._id', took: 55.121153
Warning	2017-08-26 10:44:30	{queries} slow query: 'FOR u IN User FILTER u.UserId ==@userId RETURN u._id', took: 25.508459
Warning	2017-08-26 10:44:30	{queries} slow query: 'FOR u IN User FILTER u.UserId ==@userId RETURN u._id', took: 46.778675
Warning	2017-08-26 10:44:30	{queries} slow query: 'FOR u IN User FILTER u.UserId ==@userId RETURN u._id', took: 50.962915
Warning	2017-08-26 10:44:30	{queries} slow query: 'FOR u IN User FILTER u.UserId ==@userId RETURN u._id', took: 46.618666

**Comment by jsteemann** [comment]
So that means the query is fast with both the sparse and the non-sparse indexes. The execution plans show that the query will use the indexes then.
The slow logs that you were posting here are for **different** queries, as can be clearly seen by looking at the query strings. The above queries for testing the indexes all end in "return u", whereas all slow queries from the slow log end with "return u._id" or "return u.MobileNum".

The queries in the slow log will also use the index (if present), however, if some still remain slow, there must be another reason for it. One reason could be queued or long-running write queries to the `User` collection. Have you checked that?

**Comment by namnik** [comment]
thanks for response.
we didn't have any long-running write queries . we request to Arangodb just with one end-user!
I test my quesries with "return u" replace "return u._id" . but didn't effect on performance.

and:
I have been run my Arangodb on "CentOs 7" with same data; and performance was worse than Windows Server 2008 R2!

I think I must be switch to another database engine. did you have any idea?!

**Comment by jsteemann** [comment]
Well, if reading a single document using a hash index is not fast, then probably there is something severely wrong with the whole setup. It's impossible to tell from here what's going wrong, but provided the "User" collection was loaded already, the hash index lookup should have a complexity of O(1) and should return the document from memory. 
That should be fast in all cases, except if the process or data are swapped out. If that is actually the case, you will encounter problems with all other database engines as well.

**Comment by dothebart** [comment]
I will close this message as answered. If more questions arise, don't hesitate to ask.
