### ISSUE TITLE
Question [FOXX]: how to validate params without passing them to aql template string or using _query function?

### ISSUE THREAD

**Issue by p30arena** [arangodb/arangodb#3084]
Question [FOXX]: how to explicitly validate params without passing them to "aql template string" or using "db._query" function?

**Comment by dothebart** [comment]
Hi, 
The suggested way is [using joi](https://docs.arangodb.com/3.2/Manual/Foxx/GettingStarted.html#parameter-validation). 

The upstream documentation can be found at: https://github.com/hapijs/joi

Other users also have blogged about their use of Joi:
https://medium.com/@stockholmux/getting-started-with-arangodb-and-foxx-joifully-crud-y-in-the-best-way-9865b73e7999

**Comment by p30arena** [comment]
@dothebart its still defective, because we need sanitization,
say we receive a unicode string containing different types of characters, it may higher the risk of injection on DB...

**Comment by dothebart** [comment]
The joi will revalidate that the structure of the json objects you get from the POST matches the structure you've specified, right?

Inside of foxx [you use bind values](https://docs.arangodb.com/3.2/AQL/Fundamentals/BindParameters.html)  when invoking AQL. 

When rendering web-pages etc. you could try to use [the xss node module](https://www.npmjs.com/package/xss) [in your foxx service](https://docs.arangodb.com/3.2/Manual/Foxx/Dependencies.html).

**Comment by dothebart** [comment]
Hi, 
I think we can close this question as answered. Don't hesitate to ask if not.
