### ISSUE TITLE
Support transparent decompression during import

### ISSUE THREAD

**Issue by dothebart** [arangodb/arangodb#3086]
Arangoimp should support to work with `foo.json.gz` or `foo.json.xz` so the user doesn't have to decompress huge files on his disk when importing them.

**Comment by cherouvim** [comment]
Apart from the obvious convenience this feature, it'll probably allow users without a lot of free disk space to do backups and imports.

**Comment by Simran-B** [comment]
`arangodump`, `arangorestore`, `arangoimport` and `arangoexport` would benefit from on-the-fly (de-)compression

**Comment by dothebart** [comment]
meanwhile all CLI-Tools can handle gzipped files; closing as solved.
