### ISSUE TITLE
Documents: Could not fetch documents count

### ISSUE THREAD

**Issue by hellomanjack** [arangodb/arangodb#3096]
## my environment running ArangoDB
- [x] 3.2

Mode:
- [x] Cluster

Storage-Engine:
- [ ] mmfiles
- [x] rocksdb

On this operating system:
- [x] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
  - [ ] Linux 
  - [ ] Gentoo
  - [x] docker - official docker library

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [x] authentication is enabled?
- [x] using the cluster?
- [x] _system database?

when creating document, it shows follows.

![image](https://user-images.githubusercontent.com/25783698/29548029-599c4a9c-8730-11e7-8899-aca924db2083.png)

![image](https://user-images.githubusercontent.com/25783698/29548084-adfbe50c-8730-11e7-9085-af866ce88712.png)

**Comment by m0ppers** [comment]
All of your DC/OS tasks are failing. It doesn't seem to be frontend related. Instead all tasks seem to fail. Can you post the logs?

**Comment by hellomanjack** [comment]
@m0ppers  I am sorry to reply so late. Logs are as follows.
[cor1.txt](https://github.com/arangodb/arangodb/files/1251160/cor1.txt)
[cor2.txt](https://github.com/arangodb/arangodb/files/1251161/cor2.txt)
[db1.txt](https://github.com/arangodb/arangodb/files/1251162/db1.txt)
[db2.txt](https://github.com/arangodb/arangodb/files/1251163/db2.txt)
[agent.txt](https://github.com/arangodb/arangodb/files/1251164/agent.txt)
It's on the DCOS. 1 master and 2 slave
master
![image](https://user-images.githubusercontent.com/25783698/29704613-2469ae08-89ad-11e7-9279-cef5eb31333f.png)
slave01
![image](https://user-images.githubusercontent.com/25783698/29704634-388479f4-89ad-11e7-8da7-8208ca5eb8bc.png)
slave02
![image](https://user-images.githubusercontent.com/25783698/29704669-5fdc0daa-89ad-11e7-92c4-ed4c330b7d74.png)

**Comment by m0ppers** [comment]
Your dbservers died with an out of memory error. How much memory are they allowed to have? This is specified in DC/OS when creating the cluster. Above are the memory stats for the slave itself (and does not really help here)

Is it possible to give a bit more RAM to the DBServers?

**Comment by dothebart** [comment]
Hi, 
does this still happen to you with ArangoDB 3.2.8? or could we close this issue?

**Comment by dothebart** [comment]
Closing as solved with 3.2.8
