### ISSUE TITLE
Creating a graph through the REST APi fails if orphanCollections has more than one element

### ISSUE THREAD

**Issue by dantomosoiu** [arangodb/arangodb#3106]
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2

Mode:
- [x] Single-Server

On this operating system:
- [x] Windows, version: 10

[x] I'm using graph features

I'm issuing a POST request to http://127.0.0.1:8529/_db/[database]/_api/gharial via:
- [x] web interface with this browser:  Chrome   running on this OS: Windows 10
- [ ] arangosh
- [x] this Driver: ArangoDB-NET

The issue can be reproduced using this dataset:

<pre>{
	"name": "MyGraph",
	"edgeDefinitions": [{
			"collection": "EdgeCol1",
			"from": ["ColA", "ColB"],
			"to": ["ColC"]
		},
		{
			"collection": "EdgeCol2",
			"from": ["ColD"],
			"to": ["ColE"]
		}
	],
	"orphanCollections": [
		"OrphanColA",
		"OrphanColB"
	],
	"isSmart": false
}
</pre>

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [x] `_system` [x] other: 
4) SUPPORT -> REST API -> POST /_api/gharial

The following problem occurs:

<pre>{
	"error": true,
	"errorNum": 500,
	"errorMessage": "Internal Server Error",
	"code": 500
}
</pre>

The graph does not get created. All collection in the edgeDefinitions array get created.
Only the first collection in the orphanCollections array gets created.

If the orphanCollections array has just one element, or is empty, the graph gets created successfully.

**Comment by dothebart** [comment]
Hi, confirmed and fixed. Will be part of the next maintenance release next week.

**Comment by dothebart** [comment]
ArangoDB 3.2.3 is now available for download. Please note that we switched our webserver and changed our download URLS for better performance.
Closing.
