### ISSUE TITLE
"batchSize" properties  not work when excute "Simple Queries" using HTTP

### ISSUE THREAD

**Issue by gikieng** [arangodb/arangodb#3114]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [*] 3.2
- [ ] self-compiled devel branch

Mode:
- [*] Cluster
- [ ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [*] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [*] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [*] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

curl -X PUT --data-binary @- --dump - 'http://arango0:18530/_db/graphdata_20170719/_api/simple/by-example' <<EOF
{"example": {}, "collection": "entity", "batchSize":10}

Cause Server out of memory

**Comment by dothebart** [comment]
Hi, 
which exact version are you using? 3.2.0 or 3.2.1? 

In general even with batchsize the server has to build up the result in ram - thus it will consume memory.
So, how large will the reply be in total? number of documents + average size of the documents?

We also have seen issues with our jemalloc version, which we upgrade with the soon to be released next version.

**Comment by gikieng** [comment]
it's version 3.2.0.
so, i want to fetch all the document from a  large collection only by using LIMIT and SKIP?

**Comment by dothebart** [comment]
Can you upgrade to the 3.2.2 version we released yesterday? We changed the jemalloc memory allocation library, which seemed to have caused some problems in some cases.

Yes, generally it would be better to use `LIMIT` and `SKIP` since they reduce the result set instead of the reply batch size.

**Comment by dothebart** [comment]
Hi, any news from this? have you been able to reproduce this? or can we close this?

**Comment by gikieng** [comment]
you
