### ISSUE TITLE
404 on ArangoDB Website

### ISSUE THREAD

**Issue by richorama** [arangodb/arangodb#3121]
On this page:

https://www.arangodb.com/download-major/windows-azure/

The 'Microsoft Azure Page' link points to this: http://azure.microsoft.com/en-us/marketplace/partners/arangodb/

...which 404s, I believe you should update it to this:

https://azuremarketplace.microsoft.com/en-us/marketplace/apps/arangodb.arangodb?tab=Overview

**Comment by dothebart** [comment]
Thanks for spotting - just fixed with the 3.2.2 release.
