### ISSUE TITLE
HTTP Foxx API: Json parsing exception

### ISSUE THREAD

**Issue by mpv1989** [arangodb/arangodb#3125]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2
- [x] self-compiled devel branch

### Foxx
Installing a Foxx service via HTTP API with given configuration result in Json parsing error.

These are the steps to reproduce:
Install a Foxx service via curl over [POST /_api/foxx](https://docs.arangodb.com/3.2/HTTP/Foxx/Management.html#install-new-service) with content type `application/json` and `configuration` or `dependencies` in the request body.

**Comment by mpv1989** [comment]
[PR 3.2](https://github.com/arangodb/arangodb/pull/3132)
[PR devel](https://github.com/arangodb/arangodb/pull/3129)

**Comment by dothebart** [comment]
ArangoDB 3.2.3 is now available for download. Please note that we switched our webserver and changed our download URLS for better performance.
Closing.
