### ISSUE TITLE
User rights to database are reseted after upgrade from 3.2.* to next version

### ISSUE THREAD

**Issue by DeShadow** [arangodb/arangodb#3133]
I downloaded and install new version of ArangoDB 3.2.2. And after installing I run it from Terminal
```
/Applications/ArangoDB3-CLI.app/Contents/MacOS/usr/sbin/arangod --server.storage-engine=rocksdb /mypath/rocksdb_3_2 --server.endpoint tcp://0.0.0.0:8585
```
And rights of my user were reseted to database: I can't create new collections and write to collections (only read). The same situation was after upgrade from 3.2 to 3.2.1.
After logging in by root user and setting new rights for my user all became good.

**Comment by jsteemann** [comment]
This should have been fixed in one of the recent releases. Could you try with 3.2.6 and re-check if the problem is actually solved?
Thanks!

**Comment by DeShadow** [comment]
@jsteemann I have no problems with rights now. Thank you! :)
