### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by neunhoef** [arangodb/arangodb#3136]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [*] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [*] Single-Server

Storage-Engine:
- [*] mmfiles
- [*] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [*] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

Installer gets caught in time loop.

These are the steps to reproduce:
1) `sudo apt install arangodb3`
2) Type root password in dialog box, make a typo, such that you do no longer know what you wrote
3) In the next dialog box you can no longer proceed since you do not know the right password, click Cancel
4) Something happens and after a while you get an error dialog box which has only an "OK" button and if you choose it, the box comes back, caught. Not even Ctrl-C works.

**Comment by dothebart** [comment]
ArangoDB 3.2.3 is now available for download. Please note that we switched our webserver and changed our download URLS for better performance.
Closing.
