### ISSUE TITLE
Suggestion: Simple queries need a sort method

### ISSUE THREAD

**Issue by frankmayer** [arangodb/arangodb#314]
The skip/limit options of the simple queries are almost useless without being able to sort before using those methods. 

Sorting would round up simple queries and make them a lot more useful.

I'd even suggest to have this functionality in 1.1 as it would make life a bit easier for newcomers/ learners.

**Comment by CoDEmanX** [comment]
@fceller: is it on todo for 2.6 or is it too late for implementation?

**Comment by dothebart** [comment]
We currently don't intend to further improve simple queries. Meanwhile they're a wrapper around AQL. In general we recommend to use AQL for sorted queries - closing as *won't fix*.

In general, the simple query to AQL converters can be found in: 
https://github.com/arangodb/arangodb/blob/devel/js/server/modules/%40arangodb/simple-query.js
https://github.com/arangodb/arangodb/blob/devel/js/common/modules/%40arangodb/simple-query-common.js
If anybody is willing to provide an implementation of converting sort into AQL there, feel free to send pull requests.

ArangoDB 3.0 RC2 is available for download via: https://www.arangodb.com/download-preview/
