### ISSUE TITLE
Expose foxxRouting action

### ISSUE THREAD

**Issue by smolse** [arangodb/arangodb#3143]
Currently there is a foxxRouting function in actions.js which is not exported, though it could be useful for managing routes to Foxx services, e.g. to easily route all requests to some particular mount point with `db._routing.save({
    url: {"match": "/*"},
    action: {
        do: "@arangodb/actions/foxxRouting",
        options: {
            mount: "/abc"
        }
    }
});`, etc.

**Comment by dothebart** [comment]
Hi, 
this is more or less an internal API - which is why the documentation for this mechanism was removed. 
I will close this as `won't fix` therefore.
