### ISSUE TITLE
Compactor Performs Excessive Disk Writes

### ISSUE THREAD

**Issue by tsh56** [arangodb/arangodb#3144]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [x] 3.0
- [ ] 3.1
- [ ] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [x] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [x] own infrastructure
- [x] Linux 
  - [ ] Debian .deb
  - [x] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

I'm observing Arango write orders of magnitude more data to disk than the entire size of the database on disk. This behavior has negatively impacts disk io performance, and has very serious consequence for the write endurance of SSD drives.

I am working on a dataset has roughly a 30 day rolling window of data, however data isn't necessarily expired in chronological order. The dataset is ~5GB on disk and has a little under 10M documents. Over the course of 24 hours I've observed as much as 1.6TB of disk writes performed by the compactor.

I don't see any configuration for when the compactor should run, and the default settings are quite aggressive. It looks like the compactor will run on 100KB of dead space which is only .15% of a 64MB datfile. I'd like to see the compactor configurable to provide a better balance between IO and storage space for collections that regularly delete a handful of documents at a time.

Steps to reproduce

Create a collection:
```
db._create("myCollection");
```

Create many documents of some non trivial size:
```
FOR i IN 1..50000
  INSERT { 
    _key: CONCAT("test", i),
    name: CONCAT("test", i),
    foo: "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way— in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only.",
    bar: "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way— in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only.",
    baz: "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way— in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only."
  } IN myCollection
```

Delete chunks of 100 docs waiting a few seconds in between:
```
FOR i IN 1..100
  REMOVE { _key: CONCAT('test', i) } IN myCollection
```
```
FOR i IN 101..200
  REMOVE { _key: CONCAT('test', i) } IN myCollection
```
```
FOR i IN 201..300
  REMOVE { _key: CONCAT('test', i) } IN myCollection
```
```
FOR i IN 301..400
  REMOVE { _key: CONCAT('test', i) } IN myCollection
```

Observed Behavior:
I monitor disk writes using `iotop -a`. After creating the docs in the collection I observe the collection takes 102MB of disk space. I perform the 4 delete operations, and after they complete the compactor has written 531MB of data to disk. This is 5 times the amount of storage for the entire collection.

**Comment by jsteemann** [comment]
At the moment the compactor will kick in approximately every 10 seconds, and will start compacting datafiles if they contain 128KB or more dead objects, more than 10% dead objects, or more than 16K deletions. 
The compactor will also try to merge datafiles smaller than 128KB with other datafiles, to reduce the overall number of datafiles.
Removing a small amount of data, pausing and then removing another small amount of data will make the compactor run two times. Both times it will only be able to work on the data just removed, but as the compactor works on entire datafiles, it needs to rewrite the complete datafile(s) for this. Thus the high amount of disk writes observed.

Solutions for this would be:
- configure the compactor interval (from 10 seconds to some other value)
- configure the absolute threshold value for dead objects (128KB), the relative threshold value for dead objects (10%) and the threshold value for the number of deletions (16K), plus the minimum size below which a datafile will be merged with others (128KB)
- configure the max amount of writes the compactor is allowed to do per interval (e.g. in KB/s).

**Comment by tsh56** [comment]
Thanks for the input.

I think all of the suggestions are reasonable approaches, but for the situation I encountered configuring a higher interval between compactions should be sufficient. Is this something that could be pulled into a patch release?

**Comment by dothebart** [comment]
In relation to this, we found this issue:
https://github.com/arangodb/arangodb/commit/737af8267ff69b30b34e857197b8a9a1882892a2

However, we're currently not releasing any maintenance releases for 3.0 anymore. Thus, if you need that change, you have to help yourselves by cherry-picking and re-building your own 3.0 release.

3.2.4 will contain this bugfixes and the ability to configure all aspects of the compactor thread - https://github.com/arangodb/arangodb/pull/3217 (which is already available in the nightly builds) which you may try to use to tune the defaults in your setup - again by finally patching your own 3.0 fork.

We will close this issue with the release of 3.2.4 in the next days.

**Comment by dothebart** [comment]
3.2.4 containing this is available for download now - Closing.
