### ISSUE TITLE
JWT exp issue in 3.1.X branch

### ISSUE THREAD

**Issue by solisoft** [arangodb/arangodb#3145]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [X] 3.1
- [ ] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [X] Single-Server

Storage-Engine:
- [X] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [X] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### Foxx

JWT exp field created in 3.1.x is wrong and contain epoch in ms
```json
{
  "uid": "82689109",
  "iat": 1503394006255,
  "payload": {
    "role": "Eleve",
    "email": "eleve1@essai.com",
    "username": "P.BARRES"
  },
  "exp": 1503397606258
}
```

And here one generated in 3.2.x

```json
{
  "uid": null,
  "iat": 1503774404,
  "payload": null,
  "exp": 1503778004
}
```

As you can see exp field is longer in 3.1.x than 3.2.x

**Comment by solisoft** [comment]
actually iat field also ...

**Comment by solisoft** [comment]
From https://tools.ietf.org/html/rfc7519#section-4.1.4
dates must be in seconds, not milli-seconds

NumericDate
      A JSON numeric value representing the number of seconds from
      1970-01-01T00:00:00Z UTC until the specified UTC date/time,
      ignoring leap seconds.  This is equivalent to the IEEE Std 1003.1,
      2013 Edition [POSIX.1] definition "Seconds Since the Epoch", in
      which each day is accounted for by exactly 86400 seconds, other
      than that non-integer values can be represented.  See RFC 3339
      [RFC3339] for details regarding date/times in general and UTC in
      particular.

**Comment by solisoft** [comment]
I checked the code : 
I guess you only have to copy js file from
https://github.com/arangodb/arangodb/blob/v3.2.2/js/server/modules/%40arangodb/foxx/sessions/storages/jwt.js

to 

https://github.com/arangodb/arangodb/blob/v3.1.27/js/server/modules/%40arangodb/foxx/sessions/storages/jwt.js

and it should works :) ... I think you missed it for branch 3.1.x ...

**Comment by dothebart** [comment]
As you already found https://github.com/arangodb/arangodb/issues/2249 - we took the decision not to introduce breaking changes into a minor release. So I think we should close this as duplicate?

**Comment by solisoft** [comment]
Yes I was able to adapt my client lib ... so I guess it's OK
