### ISSUE TITLE
Arangodb

### ISSUE THREAD

**Issue by jmc420** [arangodb/arangodb#3162]
I have a single instance arangodb started with Docker on an AWS instance.

I can connect from my localhost to the instance using root user:

arangosh --server.endpoint tcp://xx.xxx.xx.xxx:8529 --server.username root

However if I create a new user via the web user interface, I cannot get via the shell using the other user name:

arangosh --server.endpoint tcp://xx.xxx.xx.xxx:8529 --server.username XXXX

What do I need to do to connect via the shell with this new user?

Jams

**Comment by hkernbach** [comment]
Could you paste your shell output? Do you set the new permissions for the new user correctly? Maybe you need to specify the database via --server.database as well, if you're trying to access another database than _system.

**Comment by dothebart** [comment]
hi @jmc420, did this answer your question? I'll close this as abandoned. If not, please let us know.
