### ISSUE TITLE
Binary and repository files not available for community releases.

### ISSUE THREAD

**Issue by Tehnari** [arangodb/arangodb#3163]
### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.
1) Go to https://www.arangodb.com/download-major/
2) Click OpenSuse / CenOS ...
3) Download binary file:
https://www.arangodb.com/repositories/arangodb32/openSUSE_13.2/x86_64/arangodb3-3.2.2-1.x86_64.rpm

4 Or add repo as described:
zypper --no-gpg-checks --gpg-auto-import-keys addrepo https://www.arangodb.com/repositories/arangodb32/openSUSE_13.2/arangodb.repo

zypper --no-gpg-checks --gpg-auto-import-keys refresh
zypper -n install arangodb3=3.2.2
In this case you will have an error file not found.

The same problem is when you'll try to download client drivers, it's just nothing happen when you click on icons/buttons (url: https://www.arangodb.com/arangodb-drivers/ )

**Comment by hkernbach** [comment]
Thanks for your report. There might be a short window you hit yesterday. Our repository moved to a different location.
