### ISSUE TITLE
Jobs stuck in progress/pending state in Foxx queues with 3.2.2/Ubuntu

### ISSUE THREAD

**Issue by ThomasWeiss** [arangodb/arangodb#3166]
I've been using queues and jobs extensively with very good results on 3.1(.21). As we're preparing our migration to 3.2.2, I've noticed that queued jobs:
- don't get processed (`"runs": 0`)
- remain in a `status` that is either `process` or `pending`

No error log of any kind. This seems to happen **only on Ubuntu (16.04)** as I didn't witness this issue on my dev machine running Windows.

**Comment by jsteemann** [comment]
Are these queues created in the `_system` database or a different database?
Is it possible to show the entries from the `_queues` and `_jobs` collection of the database that does not run the queued jobs? Thanks!

**Comment by mpv1989** [comment]
we already found a problem with Foxx queues and authentication. It will be fixed in 3.2.3.
see issue [here](https://github.com/arangodb/arangodb/issues/3120)

You can check whether your problem is the same by disabling authentication

**Comment by ThomasWeiss** [comment]
Absolutely, the difference between my dev and staging instances is that authentication is disabled in dev, so that's most probably the issue I'm having.

**Comment by dothebart** [comment]
ArangoDB 3.2.3 is available for download meanwhile. Please note that we switched our webserver and changed our download URLS for better performance.
Sorry have missed this - target milestone wasn't assigned. Closing.
