### ISSUE TITLE
Unable to setup cluster of three nodes having three coordinators

### ISSUE THREAD

**Issue by kishorel** [arangodb/arangodb#3170]
I'm using arangodb 3.2.2 on Redhat Linux with rocksdb as storage engine.I'm trying to setup a three node cluster having each role on each server.

Commands used for setup:

Agency:
on IP1:
arangod --server.endpoint tcp://0.0.0.0:5001 --agency.my-address tcp://IP1:5001 --server.authentication false --agency.activate true --agency.size 3 --agency.supervision true --database.directory /var/lib/arangodb3/agency
on IP2:
arangod --server.endpoint tcp://0.0.0.0:5001 --agency.my-address tcp://IP2:5001 --server.authentication false --agency.activate true --agency.size 3 --agency.supervision true --database.directory /var/lib/arangodb3/agency
on IP3:
arangod --server.endpoint tcp://0.0.0.0:5001 --agency.my-address tcp://IP3:5001 --server.authentication false --agency.activate true --agency.size 3 --agency.endpoint tcp://IP1:5001 --agency.endpoint tcp://IP2:5001 --agency.endpoint tcp://IP3:5001 --agency.supervision true --database.directory /var/lib/arangodb3/agency

PRIMAY:
on IP1:
arangod --server.authentication=false --server.endpoint tcp://0.0.0.0:8530 --server.uid arangodb --server.gid arangodb --cluster.my-address tcp://IP1:8530 --cluster.my-local-info db1 --cluster.my-role PRIMARY --cluster.agency-endpoint tcp://IP1:5001 --cluster.agency-endpoint tcp://IP2:5001 --cluster.agency-endpoint tcp://IP3:5001 --database.directory /var/lib/arangodb3/primary
on IP2:
arangod --server.authentication=false --server.endpoint tcp://0.0.0.0:8530 --cluster.my-address tcp://IP2:8530 --cluster.my-local-info db2 --cluster.my-role PRIMARY --cluster.agency-endpoint tcp://IP1:5001 --cluster.agency-endpoint tcp://IP2:5001 --cluster.agency-endpoint tcp://IP3:5001 --database.directory /var/lib/arangodb3/primary
on IP3:
arangod --server.authentication=false --server.endpoint tcp://0.0.0.0:8530 --cluster.my-address tcp://IP3:8530 --cluster.my-local-info db3 --cluster.my-role PRIMARY --cluster.agency-endpoint tcp://IP1:5001 --cluster.agency-endpoint tcp://IP2:5001 --cluster.agency-endpoint tcp://IP3:5001 --database.directory /var/lib/arangodb3/primary

Coordinator:
on IP1:
arangod --server.authentication=false --server.endpoint tcp://0.0.0.0:8531 --cluster.my-address tcp://IP1:8530 --cluster.my-local-info coord1 --cluster.my-role COORDINATOR --cluster.agency-endpoint tcp://IP1:5001 --cluster.agency-endpoint tcp://IP2:5001 --cluster.agency-endpoint tcp://IP3:5001 --database.directory /var/lib/arangodb3/coordinator

on IP2:
 arangod --server.authentication=false --server.endpoint tcp://0.0.0.0:8531 --cluster.my-address tcp://IP2:8530 --cluster.my-local-info coord2 --cluster.my-role COORDINATOR --cluster.agency-endpoint tcp://IP1:5001 --cluster.agency-endpoint tcp://IP2:5001 --cluster.agency-endpoint tcp://IP3:5001 --database.directory /var/lib/arangodb3/coordinator
on IP3:
arangod --server.authentication=false --server.endpoint tcp://0.0.0.0:8531 --cluster.my-address tcp://IP3:8530 --cluster.my-local-info coord3 --cluster.my-role COORDINATOR --cluster.agency-endpoint tcp://IP1:5001 --cluster.agency-endpoint tcp://IP2:5001 --cluster.agency-endpoint tcp://IP3:5001 --database.directory /var/lib/arangodb3/coordinator

No error, but when i check the Web interface, shows nothing. Initial commands given in site(for one coordinator and two db servers) works fine.

I even tried with creating seperate conf for each say agent.conf,coordinator.conf and dbserver.conf.

Please correct me if i'm doing wrong and help me in configuring the setup. Is it recommended to use all the nodes as coordniator(similar  to cassandra cluster)?
 Please suggest...

**Comment by kishorel** [comment]
Also can't we setup cluster with arangod.conf file instead of CLI? I need to have two roles for the same server. And also can't we change the default datadir? we are really looking forward to test this setup before moving on production.
Any help would be appreciated.

**Comment by kishorel** [comment]
Anyone faced similar issue? anyone tried this kind of setup having the dbserver and coordinator role on all the existing nodes ?

I have even tried creating separate config agent.conf, coordinator.conf and dbserver.conf on each server.

**agent.conf**

[database]
directory = /home/arangodb/agency

[server]
endpoint = tcp://0.0.0.0:5001
storage-engine = rocksdb

authentication = true
jwt-secret = #######

statistics = true
uid = arangodb
gid = arangodb

[javascript]
startup-directory = usr/share/arangodb3/js
app-path = /var/lib/arangodb3-apps
[agency]
my-address = tcp://**IP1**:5001
endpoint = tcp://**IP1**:5001
endpoint = tcp://**IP2**:5001
endpoint = tcp://**IP3**:5001
activate = true
size = 3
supervision = true
[log]
level = info
file = /var/log/arangodb/arangod.log


**dbserver.conf**

[database]
directory = /home/arangodb/primary

[server]

endpoint = tcp://0.0.0.0:8530
storage-engine = rocksdb
authentication = true
jwt-secret = #####
statistics = true
uid = arangodb
gid = arangodb
[cluster]

my-address = tcp://**IP1**:8530
my-local-info = db
my-role = PRIMARY
agency-endpoint = tcp://**IP1**:5001
agency-endpoint = tcp://**IP2**:5001
agency-endpoint = tcp://**IP3**:5001
[javascript]
startup-directory = /usr/share/arangodb3/js
app-path = /var/lib/arangodb3-apps
[log]
level = info
file = /var/log/arangodb/arangod.log

**coordinator.conf**

[database]
directory = /home/arangodb/coordinator
[server]

endpoint = tcp://0.0.0.0:8531
storage-engine = rocksdb
authentication = true 
jwt-secret = ######
statistics = true
uid = arangodb
gid = arangodb

[cluster]

my-address = tcp://**IP1**:8531
my-local-info = coord1
my-role = COORDINATOR
agency-endpoint = tcp://**IP1**:5001
agency-endpoint = tcp://**IP2**:5001
agency-endpoint = tcp://**IP3**:5001
[javascript]
startup-directory = /usr/share/arangodb3/js
app-path = /var/lib/arangodb3-apps
[log]
level = info
file = /var/log/arangodb/arangod.log


with the above config, i have started three arangod processes on each node,no error but getting INFO message as below on all the three nodes.

2017-08-31T07:54:26Z [14063] INFO {agencycomm} Flaky agency communication to http+tcp://**IP1**:5001. Unsuccessful consecutive tries: 23 (11.9s). Network checks advised.
2017-08-31T07:54:27Z [14019] INFO {agencycomm} Flaky agency communication to http+tcp://**IP2**:5001. Unsuccessful consecutive tries: 31 (23.81s). Network checks advised.
2017-08-31T07:54:27Z [14063] INFO {agencycomm} Flaky agency communication to http+tcp://**IP3**:5001. Unsuccessful consecutive tries: 24 (13.04s). Network checks advised

Anyone to help?

**Comment by m0ppers** [comment]
Hi. Did you have a look at our starter? We created it exactly because the manual setup is super tricky:

https://docs.arangodb.com/3.2/Manual/Deployment/ArangoDBStarter.html

**Comment by sleto-it** [comment]
Hi @kishorel,

Just sending a quick follow-up. Have you had a chance to use the Starter? that's really the method you want to use to start the cluster easily

When you use the starter you can specify the directory to be used using the option --starter.data-dir

You can have machines with all services running, or machines with some of the services only

Please take a look at the following resources, and let us know if those help:

- https://github.com/neunhoef/ArangoDBStarter (there's a tutorial)
- https://docs.arangodb.com/3.2/Manual/Deployment/ArangoDBStarter.html
- https://www.arangodb.com/2016/12/starting-arangodb-cluster-easy-way/

Many thanks,

**Comment by sleto-it** [comment]
Hi,

We haven't received any recent feedback on this ticket. I am closing it now. Please comment if you have any other questions and we will reopen it

Many thanks,
