### ISSUE TITLE
Arangodb 3.2.2 - Web UI reports cluster error when there appears to be no error

### ISSUE THREAD

**Issue by brianrusso** [arangodb/arangodb#3177]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [x ] 3.2
- [ ] self-compiled devel branch

Mode:
- [x ] Cluster
- [ ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [x ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ x] Linux 
  - [ ] Debian .deb
  - [x ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [ x] using the cluster?
- [x ] _system database?

These are the steps to reproduce:
0. Brand new cluster (using arangodb command). Absolutely no data.. no collections.. nothing.. just 1 database and 1 user created.. completely empty database directory otherwise...
1. Go to web UI
2. Displays cluster as degraded in upper right.. but appears fine in reality.
![capture](https://user-images.githubusercontent.com/6276108/29933230-eba1ce06-8e44-11e7-8700-9f546f67686b.JPG)

**Comment by hkernbach** [comment]
Thanks for the report. This has already been fixed and will be part of the next release. 

See: https://github.com/arangodb/arangodb/blob/3.2/CHANGELOG
