### ISSUE TITLE
error filesystem.full when creating vault when having lots of free space

### ISSUE THREAD

**Issue by ashkan-saeedi-mazdeh** [arangodb/arangodb#3182]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:

- 3.1

Mode:
- Single-Server

Storage-Engine:
- rocksdb

On this operating system:
- Windows, server 2012 R2

Yesterday suddenly our DB service stopped and it happened multiple times , I checked the logs and there were error of type "Unable to create new vault filesystem.full" and "cannot create file %datapath/journal% filesystem.full".

The obscure thing is that I have 110GB of available space on the disk and the same and only drive of the system. Why this can happen and how to prevent it?

**Comment by dothebart** [comment]
Hm, this doesn't sound like an error message that ArangoDB creates itself - I can't find any of its snippets in the source files. Where do you actually see it?

**Comment by ashkan-saeedi-mazdeh** [comment]
![arangodblog](https://user-images.githubusercontent.com/5682459/29965453-d48f9f20-8f22-11e7-8f12-ae4d0384bd49.jpg)

From ArangoDB's log as attached here, also the storage is mm file surely since I'm on 3.1.19 and not rocksDB.

**Comment by dothebart** [comment]
ok, how many files do you hav in that directory?
Is it regular NTFS?
And, can you please upgrade to the latest arangodb of that release series (3.1.27)

**Comment by ashkan-saeedi-mazdeh** [comment]
There are 13 files in the journal and 5 other folders and the size is 500MB and yes it is regular NTFS. I'll upgrade to 3.2 latest tomorrow. and will let you know if the issues are still there

**Comment by ashkan-saeedi-mazdeh** [comment]
@dothebart  I've upgraded to 3.2.2 and still see those in logs
![arangodblog](https://user-images.githubusercontent.com/5682459/29981083-a476e73c-8f61-11e7-8f57-c4e5f49d6164.jpg)

What can I do to check health of my disk or ...

**Comment by ashkan-saeedi-mazdeh** [comment]
@dothebart  Sorry for bothering you guys, The issue was hardware related and the hard disk had issues and the OS was having huge delays doing disk IO operations which was causing this.

**Comment by dothebart** [comment]
Thank you for clarifying. Can you sched some more light how you found out about the broken hard disk in the end (for others to come)? Did you find something in the windows event log?

**Comment by ashkan-saeedi-mazdeh** [comment]
@dothebart  Sorry for the very late reply. I had to contact the data center guys to ask for it. The VMWare VCenter's monitoring section showed big delays for the hard disks attached to the system. They were 500GB SSDs 

Btw The same DB is working like a charm using rocksDB and latest version of ArangoDB in our new system.

**Comment by dothebart** [comment]
Ok, thanks a lot! We also had troubles with SSDs in our CI environment, they used to wear, and once they did, they got a drastic decrease in I/O performance.

**Comment by ashkan-saeedi-mazdeh** [comment]
Well we didn't need them and I'm not sure If that was the cause or miss-config of the VMs and fragmentation.

I say we did not need them since we are using ArangoDB as store for Microsoft Orleans http://github.com/dotnet/orleans and we have hot data in memory most of the times so disk reads were not the most important matter.
