### ISSUE TITLE
UPDATE edge._from value throws "document not found (while executing)"

### ISSUE THREAD

**Issue by konsultaner** [arangodb/arangodb#3192]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- 3.1

Mode:
- Single-Server

Storage-Engine:
- mmfiles

On this operating system:
- Windows, version: 10

### this is an AQL-related issue: 
I'm using graph features

I'm issuing AQL via web interface with this browser: Chrome     running on this OS: Win10

The AQL query in question is:

    FOR n IN UpgradesToClientGroup
         FOR v,e,p IN 1 OUTBOUND n._from
         HasClientGroup,HasClient
    UPDATE e WITH {_from:n._to} IN HasClientGroup

This statement should take all clients from a clientGroup (the edge HasClient) and adds them to another clientGroup by following the UpgradesToClientGroup edge.

The issue can be reproduced using this dataset:

[Collections.zip](https://github.com/arangodb/arangodb/files/1270950/Collections.zip)

The following problem occurs: Error Query: document not found (while executing)
Instead I would be expecting: That all clients move to the next client group

**Comment by jsteemann** [comment]
Note: was able to reproduce this in 3.1 after renaming the "Clients" collection to "Client" ("Collections.zip" suggests that there should be a collection named "Clients" - instead it must be named "Client").

**Comment by jsteemann** [comment]
It seems that the problem is caused by the UPDATE statement referring to collection *HasClientGroup*.
However, the documents that will be updated are from collection *HasClient*.
This can be seen by changing the UPDATE part of the query to a simple RETURN statement:
```
FOR n IN UpgradesToClientGroup      
  FOR v,e,p IN 1 OUTBOUND n._from HasClientGroup,HasClient RETURN e 
```
This produces:
```
[ 
  { 
    "_key" : "6803448", 
    "_id" : "HasClient/6803448", 
    "_from" : "ClientGroup/6803291", 
    "_to" : "Client/6803443", 
    "_rev" : "_Vh3mHXy--_", 
    "isActive" : true, 
    "paysFor" : false 
  }, 
  { 
    "_key" : "6803418", 
    "_id" : "HasClient/6803418", 
    "_from" : "ClientGroup/6803261", 
    "_to" : "Client/6803413", 
    "_rev" : "_Vh3mHXy--D", 
    "isActive" : true, 
    "paysFor" : false 
  }, 
  { 
    "_key" : "6803428", 
    "_id" : "HasClient/6803428", 
    "_from" : "ClientGroup/6803276", 
    "_to" : "Client/6803423", 
    "_rev" : "_Vh3mHXy--C", 
    "isActive" : true, 
    "paysFor" : false 
  } 
]
```
All documents produced are from collection *HasClient*, but the UPDATE statement will look for them in collection *HasClientGroup* and won't find them there.
Changing the UPDATE part of the query to update the documents in collection *HasClient* instead will work:
```
FOR n IN UpgradesToClientGroup
  FOR v,e,p IN 1 OUTBOUND n._from HasClientGroup,HasClient 
  UPDATE e WITH {_from:n._to} IN HasClient
```
So I think it works as expected.

**Comment by konsultaner** [comment]
Sorry I was the mistake:

     FOR n IN UpgradesToClientGroup
         FOR v,e,p IN 1 OUTBOUND n._from
         HasClientGroup,HasClient
     UPDATE e WITH {_from:n._to} IN HasClient

The `IN HasClientGroup` needs to be a `IN HasClient`
