### ISSUE TITLE
coordinator restarts automatically middle of load test

### ISSUE THREAD

**Issue by kishorel** [arangodb/arangodb#3193]
Hi i'm using arangodb 3.2.2 with cluster setup having three servers by using **arangodb** utility with **rocksdb** as storage engine.
so my cluster has three coordinators,three dbservers.
I have started the load test using javascript  managed Graph api's having the driver version  arangodb-java-driver : 4.2.3.arangodb-java-driver : 4.2.3, its a sync client.

I'm actually creating the collections and loading 10Lakh documents. and each system has 8CPU's and 14G RAM out of which only 2G has been utilized during the test.

Coordinator is getting restarted after creating 2.5Lakh documents.

java.io.IOException: Reached the end of the stream.
java.io.IOException: Reached the end of the stream.
java.net.SocketException: Connection reset
java.io.IOException: Reached the end of the stream.
java.io.IOException: Reached the end of the stream.
java.net.SocketException: Connection reset
java.net.SocketException: Connection reset
java.io.IOException: Reached the end of the stream.
java.net.SocketException: Connection reset
java.net.SocketException: Connection reset
java.io.IOException: Reached the end of the stream.
java.io.IOException: Reached the end of the stream.
java.io.IOException: Reached the end of the stream.
java.net.SocketException: Connection reset

Is it due to memory configuration ?  Please help.

**Comment by dothebart** [comment]
Hi, 
Do you see any output in the syslog regarding the restarts? can you enable core files?

**Comment by kishorel** [comment]
Hi,
Thanks for the reply.

I have made few config changes this time, Basically my three servers have 8 cores. So i have changed the --javascript.v8-contexts to 8 which was 4 by default. and also set --javascript.v8-contexts-minimum to 8( read in some post). and also took care of the WARNINGS thrown during the startup. Now i could see lot of improvement as of now. Kudos to Arangodb Team.

But after my system went for reboot(some issue in schedule), i couldn't see arangodb running but these processes exists.

/usr/sbin/arangod --uid arangodb --gid arangodb --log.foreground-tty false --pid-file /var/run/arangodb/arangod.pid --temp.path /var/tmp/arangod --supervisor

 /usr/sbin/arangod --uid arangodb --gid arangodb --log.foreground-tty false --pid-file /var/run/arangodb/arangod.pid --temp.path /var/tmp/arangod --supervisor

 /usr/sbin/arangod --uid arangodb --gid arangodb --log.foreground-tty false --pid-file /var/run/arangodb/arangod.pid --temp.path /var/tmp/arangod --supervisor

Any idea how to solve this?

I have started the setup using Arangodb utility, like starting node A (arangodb) then node B(arangodb --starter.join A) and then followed by node C (arangodb --starter.join A)

if somehow process down, how to resume the services? i do not want to loose existing data.

In above case, what should be done eactly?  starting the service using arangodb utility is recommended for Production setup?

**Comment by dothebart** [comment]
With arangodb 3.2 setting `--javascript.v8-contexts` sets the maximum number of to be spawned V8 Contexts - so this may not be what you want to do here.

**Comment by dothebart** [comment]
Hi, 
meanwhile 3.2.8 is available with many bugfixes regarding the use of jemalloc, and an upgraded V8 version that fixes memory issues. 
Can you please upgrade and see whether this still persists?

**Comment by dothebart** [comment]
Marking as fixed with 3.2.8
