### ISSUE TITLE
arangodb 3.2.2 fails to start with debian 9

### ISSUE THREAD

**Issue by tomwolf** [arangodb/arangodb#3197]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ X] 3.2.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [X ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [ X] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [X ] Debian 9 .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an installation-related issue:

On a Debian 9  server arangodb does not start via systemctl:
<pre>
systemctl status arangodb3.service
  arangodb3.service - ArangoDB database server
   Loaded: loaded (/lib/systemd/system/arangodb3.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2017-09-04 10:33:49 UTC; 7s ago
  Process: 13773 ExecStartPre=/usr/bin/chmod 700 /var/log/arangodb3 (code=exited, status=203/EXEC)
  Process: 13770 ExecStartPre=/usr/bin/chown -R arangodb:arangodb /var/log/arangodb3 (code=exited, status=0/SUCCESS)
  Process: 13767 ExecStartPre=/usr/bin/install -g arangodb -o arangodb -d /var/run/arangodb3 (code=exited, status=0/SUCCESS)
  Process: 13764 ExecStartPre=/usr/bin/install -g arangodb -o arangodb -d /var/tmp/arangodb3 (code=exited, status=0/SUCCESS)
</pre>

In /lib/systemd/system/arangodb3.service there are the following lines:
<pre>
ExecStartPre=/usr/bin/chown -R arangodb:arangodb /var/log/arangodb3
ExecStartPre=/usr/bin/chmod 700 /var/log/arangodb3
ExecStartPre=/usr/bin/chown -R arangodb:arangodb /var/lib/arangodb3
ExecStartPre=/usr/bin/chmod 700 /var/lib/arangodb3
ExecStartPre=/usr/bin/chown -R arangodb:arangodb /var/lib/arangodb3-apps
ExecStartPre=/usr/bin/chmod 700 /var/lib/arangodb3-apps
</pre>

But: chmod and chown path is <b>/bin/ </b>

**Comment by dothebart** [comment]
hm, WTF. the debian:stretch and debian:jessie docker containers bring a copy of `/usr/bin/chmod` that are copies of `/bin/chmod` - `dpkg -S ` only knows the second one, and our cmake trips over the wrong copy. 

Will be fixed with the next released package.

**Comment by dothebart** [comment]
ok, we remove them for our build infrastructure now, and I reported an issue upstream: https://github.com/debuerreotype/docker-debian-artifacts/issues/12

**Comment by dothebart** [comment]
ArangoDB 3.2.3 is now available for download. Please note that we switched our webserver changed our download URLS for better performance.
Closing.
