### ISSUE TITLE
Kerberos Support

### ISSUE THREAD

**Issue by alexalexpod** [arangodb/arangodb#3205]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ V] 3.2

Mode:
- [V ] Single-Server

On this operating system:
- [V ] Windows, version: 2008 R2

I'm using the web interface with this browser: Chrome     running on this OS: Windows
- [ V] authentication is enabled

**Comment by fceller** [comment]
@alexalexpod currently only LDAP is supported. Kerberos is on our roadmap. For more information please contact hackers (at) arangodb.com.

**Comment by alexalexpod** [comment]
Thank you.
