### ISSUE TITLE
[FEATURE] Auto create indexes by user queries

### ISSUE THREAD

**Issue by MegaUITeam** [arangodb/arangodb#3209]
Why do we force the user to manually control the indexes???
===
If this is purely the internal part of the database. Which is needed only for its internal mechanisms of acceleration.

I'm not suggesting removing manual control over the indexes.
===
I propose to add the option of automatic indexes. Then the database, from the incoming queries will generate optimal indexes for this queries, that speed up these queries.

Why do we force the programmer to engage in routine, instead creativity?

Just lead statistics
===
If user select by the `createTime` field in more than 10% of queries - create index.
If user select by the `createTime` field in less than 10% of queries - remove index.
If user select  `FILTER age > 20 AND friends > 10` - create SkipList index  (age, friends)

Of course, give the possibility to disable automatic indexes.
---
However, indexes are purely internal, technical part of databases. You do not force the user to get involved in query optimization ??? 

The maximum that you need to give a person, is control over what the computer can not itself predict. For example, the property `unique` or `geoIndex`

I just want to work with the database. And I want it to be fast. And how database will do it, I do not care.
 I want to have magic 👍 

But if I want to manually adjust something, of course I should be able to do it. But I think that 99% of programmers will not turn off automatic indexing.

**Comment by dothebart** [comment]
Hi, 
you have to know that indices not only speed up your queries, but also take resources to maintain RAM in the case of the MMFiles storage engine, and computing power to analyse the data you want to index - and lots of these potentially sparse resources on initial build up.

So, Imagine you doing some query in the database management interface on your production system that is not done by your regular application setup. ArangoDB would notify Oh! I could use an Index for this! It then would spider your 2 million documents in that collection, bringing your live system to a grinding halt. 

So you see that this is no clever idea at all. 

However, as described in #1988 - give ArangoDB a query and let it suggest which indices may benifit that query would be a good feature. 

Thus I'll close this issue as a duplicate.

**Comment by MegaUITeam** [comment]
@dothebart 
> you have to know that indices not only speed up your queries, but also take resources to maintain RAM in the case of the MMFiles storage engine, and computing power to analyse the data you want to index - and lots of these potentially sparse resources on initial build up.


BUT ALL PEOPLE ENABLED INDEXEX
