### ISSUE TITLE
ArangoDB out-of-memory for UPDATE queries but not for SELECT

### ISSUE THREAD

**Issue by DeShadow** [arangodb/arangodb#3211]
ArangoDB 3.2.2 RocksDB engine

I have a query
```
Query string:
 let from = DATE_ADD(DATE_NOW(), -20, 'd')
 return length(for n in news 
     filter n.date > from
     filter IS_STRING(n.src.domain)
     let newsSource = FIRST(
         for ns in newsSources 
         filter ns.domain == n.src.domain 
         limit 1 
         return ns)
     filter newsSource != null && newsSource._key != n.newsSourceId
     return 1)
    // update n with { newsSourceId: newsSource._key } in news

Execution plan:
 Id   NodeType            Est.   Comment
  1   SingletonNode          1   * ROOT
  2   CalculationNode        1     - LET from = DATE_ADD(DATE_NOW(), -20, "d")   /* v8 expression */
 21   SubqueryNode           1     - LET #6 = ...   /* subquery */
  3   SingletonNode          1       * ROOT
 19   CalculationNode        1         - LET #16 = 1   /* json expression */   /* const assignment */
 24   IndexNode         474412         - FOR n IN news   /* skiplist index scan */
  7   CalculationNode   474412           - LET #10 = IS_STRING(n.`src`.`domain`)   /* simple expression */   /* collections used: n : news */
  8   FilterNode        474412           - FILTER #10
 15   SubqueryNode      474412           - LET #3 = ...   /* subquery */
  9   SingletonNode          1             * ROOT
 25   IndexNode              1               - FOR ns IN newsSources   /* hash index scan */
 13   LimitNode              1                 - LIMIT 0, 1
 14   ReturnNode             1                 - RETURN ns
 16   CalculationNode   474412           - LET newsSource = FIRST(#3)   /* simple expression */
 17   CalculationNode   474412           - LET #14 = ((newsSource != null) && (newsSource.`_key` != n.`newsSourceId`))   /* simple expression */   /* collections used: n : news */
 18   FilterNode        474412           - FILTER #14
 20   ReturnNode        474412           - RETURN #16
 22   CalculationNode        1     - LET #18 = LENGTH(#6)   /* simple expression */
 23   ReturnNode             1     - RETURN #18

Indexes used:
 By   Type       Collection    Unique   Sparse   Selectivity   Fields         Ranges
 24   skiplist   news          false    false        36.37 %   [ `date` ]     (n.`date` > from)
 25   hash       newsSources   false    false        98.10 %   [ `domain` ]   (ns.`domain` == n.`src`.`domain`)

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   move-calculations-up-2
  4   move-filters-up-2
  5   use-indexes
  6   remove-filter-covered-by-index
  7   remove-unnecessary-calculations-2
```

And it works good. It returns `0` because there is no suitable documents for this query.
But this query is long: 6s. And it's good because:

1.  there are about 95k documents after `filter n.date > from`;
2. these documents need to be full scanned and filtered by expression `filter IS_STRING(n.src.domain)`;
3. there are 4937 documents after previous filter;
4. for every of these documents I need to find `newsSource` from collection `newsSources` and make another filter ` filter newsSource != null && newsSource._key != n.newsSourceId`

This query is need to be executed once. But I find next problem. If call previous query to count documents - all is good. ArangoDB says that the count is `0`.

But my target is update every finded document. That's why my query is:
```
let from = DATE_ADD(DATE_NOW(), -20, 'd')

for n in news 
    filter n.date > from
    filter IS_STRING(n.src.domain)
    let newsSource = FIRST(
        for ns in newsSources 
        filter ns.domain == n.src.domain 
        limit 1 
        return ns)
    filter newsSource != null && newsSource._key != n.newsSourceId
    update n with { newsSourceId: newsSource._key } in news
```

And this query followed by killing of ArangoDB process because of out-of-memory. And it's strange, because there is no suitable documents for update. And need to update 0 documents. But there is an error and killing of process.

Server:
Ubuntu 14.04
ArangoDB 3.2.2
RocksDB engine
8GB RAM
4 cores

**Comment by dothebart** [comment]
Hi, 
with ArangoDB 3.2.8 we fixed some important memory management issues by applying upstream V8 patches and improving our jemalloc integration.

Can you please retry whether this is still an issue after the upgrade?

**Comment by DeShadow** [comment]
@dothebart Hello! Sorry, but I haven't that dataset. I upgraded to the version 3.2.8 a few minutes ago and tried to make some big update queries (about 100k documents). And it was without any problems. That's why I think this issue is not actual.
I think there is also another similar my issue #3253 
And after some tests I'll check again is that issue fixed.
