### ISSUE TITLE
[QUESTION] Pagination: How to get TOTAL count of documents?

### ISSUE THREAD

**Issue by MegaUITeam** [arangodb/arangodb#3213]
When i use:
```coffeescript
cursor = await @query(aql, vars, {options: {fullCount: true}})
fullCount = cursor.extra.stats.fullCount
```

The query very slowly, about 8 seconds.
The collection contains about 3 million documents.
SkipList indexes in all fields are enabled.

I can not use limit, since I want to know the total number of documents that fit under the selector. And use this number when counting pages count for pagination. 8 seconds is incredibly long. Maybe some other way instead `fullCount: true`?

**Comment by jsteemann** [comment]
Is the index actually used by the query? There is no way to tell from here, as the AQL query string and the execution plan are not shown.
Can you check by explaining the query whether it actually uses the index?

**Comment by MegaUITeam** [comment]
aql
```
FOR user IN Users
  RETURN user
```

**Comment by jsteemann** [comment]
This query returns the entire "Users" collection. As there is no LIMIT clause anywhere, it will return 30M documents. "fullcount" will not make any difference here if there is no LIMIT clause in the query.

**Comment by MegaUITeam** [comment]
@jsteemann All right. LIMIT and not needed. Since we want to know the total number of elements that fit under the selector.

**Comment by jsteemann** [comment]
The query will return the entire collection, with all data. It will build up the entire result set, with and without fullcount, as there is no LIMIT used.
To get the number of documents in the collection (without any filtering), you should rather use something like `RETURN LENGTH(Users)`.

**Comment by DeShadow** [comment]
@MegaUITeam Or you can use https://github.com/arangodb/arangojs#collectioncount
It will be very fast. But the approach of @jsteemann is very similar.

**Comment by MegaUITeam** [comment]
```RETURN LENGTH(Users).```
but filters are not used here.

**Comment by jsteemann** [comment]
@MegaUITeam : ok, focus/topic of the question has changed now. To get the number of documents matching your selector (e.g. `post.wallUserId == @userId`) it is recommended that the selection criterion is indexed properly. A non-sparse skiplist (or better: hash) index will do this for such single attribute equality lookup.
It will however look up all results for that particular selector. To limit the result output to a few results, use LIMIT + fullcount.
If that is not fast enough for scenarios in which the "user has a million post on the wall" (is that a realistic scenario by the way?), you can create another collection and store the number of posts per user there. Whenever a user posts something, you could fetch the existing counter value from the extra collection and update it by one.

**Comment by dothebart** [comment]
@MegaUITeam  please give http://www.catb.org/esr/faqs/smart-questions.html a consideration for your communication on the Internet.

Asking questions in a meaningful and friendly way is essential to getting a valuable answer.

Most of the topics in this thread can be easily looked up in https://docs.arangodb.com/3.2/Manual/ - Please consult the documentation first.
