### ISSUE TITLE
Does arangodb support chinese fulltext search now?

### ISSUE THREAD

**Issue by gzliudan** [arangodb/arangodb#3214]
Does arangodb support chinese fulltext search now?

**Comment by dothebart** [comment]
Hi, 
We released the first milestone of ArangoDB 3.4 containing ArangoSearch which supports chinese:
https://arangodb.com/2018/01/milestone-arangodb-3-4-arangosearch-information-retrieval/

Please give us your feedback whether you like it.

**Comment by whuxujiyuan** [comment]
@dothebart Chinese support in ArangoSearch now is very good,
when will the ArangoDB 3.4 release, looking forward to deploy the ArangoSearch in production

**Comment by dothebart** [comment]
Hi, 
we're working hard on getting a release candidate ready. You meanwhile may want to try the nightly, since also some bugs have been fixed in arangosearch. We also have an #arangosearch slack channel to discuss related topics, feel free to join.
Btw, if you want to contribute tests for chinese arangosearch, be welcome to contribute (since we don't have chinese speakers atm)

**Comment by maxkernbach** [comment]
With [**ArangoSearch**](https://www.arangodb.com/arangodb-training-center/search/arangosearch/) support for chinese full-text search is implemented in 3.4.

Further information can be found in the [documentation](https://docs.arangodb.com/3.4/Manual/Views/ArangoSearch/).
Please find the latest release in the [download section](https://www.arangodb.com/download/).

**Comment by Himan000** [comment]
@maxkernbach @dothebart ,

Does aql support chinese fulltext search? If so, how?

**Comment by Himan000** [comment]
Do I need to set analyzers/tokenizor？

**Comment by maxkernbach** [comment]
Hi @gzliudan,

please have a look at the links of my previous message.

Example 2 of [**ArangoSearch**](https://www.arangodb.com/arangodb-training-center/search/arangosearch/) shows you how to use the Chinese text analyzer.

https://www.arangodb.com/docs/3.4/views-arango-search-analyzers.html

> text_zh
> tokenize the value into word stems as per the Chinese locale

Do you have any further questions?

**Comment by Himan000** [comment]
Hi @maxkernbach ,
Thanks. Again the question, Does aql support chinese fulltext search? If so, is there any config need to set?

**Comment by Himan000** [comment]
I don't use  ArangoSearch in my project.

**Comment by maxkernbach** [comment]
ArangoSearch, which is a full-text search engine, supports Chinese text analyzer.

You can create a view using the `text_zh`, link this view to a collection and then use this view inside AQL queries. All of this is described in the link of my previous message.

**Comment by Himan000** [comment]
Hi @maxkernbach ,

OK, I will try it and update you when done. Thanks.

**Comment by Himan000** [comment]
Hi @maxkernbach ,
For the example in document,

c0.save({ i: 0, name: "full", text: "是一个 多模 型数 据库" });
c0.save({ i: 1, name: "half", text: "是一个 多模" });
c0.save({ i: 2, name: "other half", text: "型数 据库" });
c0.save({ i: 3, name: "quarter", text: "是一" });

if query is,

db._query(`FOR doc IN ExampleView
  SEARCH PHRASE(doc.text, '多模 据库', 'text_zh') OR STARTS_WITH(doc.b, 'ba')
  SORT TFIDF(doc) DESC
  RETURN doc`);

then no result return, that's is not full text search,right?
