### ISSUE TITLE
Issue in the Foxx microservices examples

### ISSUE THREAD

**Issue by chessgecko** [arangodb/arangodb#3224]
## locally ubuntu 17.04
I'm using the latest ArangoDB of the respective release series:
- [X] 3.2

Mode:
- [X] Single-Server

Storage-Engine:
- [X] mmfiles

On this operating system:
- [ ] Linux 
  - [X] Ubuntu .deb

In the getting started example when I tried to bind to the collection:
```
const keys = db._query(
  'FOR entry IN @@coll RETURN entry._key',
  {'@coll': foxxColl}
);
```
I got an error saying ArangoError 10: bad parameter

It seemed like the correct fix was to bind to the module.context.collectionName value instead of the module.context.collection value that was displayed above in the example. Is this what I should do / if so can you update the documentation?

Thanks

**Comment by sleto-it** [comment]
Hi, many thanks for opening this issue. Version 3.2.9 has been released. I am closing this ticket now. If the problem persists please let us know.

Many thanks,
