### ISSUE TITLE
String comparison in AQL

### ISSUE THREAD

**Issue by ThomasWeiss** [arangodb/arangodb#3225]
I'm using string comparisons for prefixed string search (full-text doesn't work for me as it strips out punctuation), so in order to search for the prefix `test` for example, the query is something like `WHERE field >= 'test' && field < 'test<special_character>'` where that `special_character` should be greater than any other character. I've tried using `ž` as that special char, but I've recently realized that the string comparison doesn't work as expected:
`RETURN 'ž' < 'z'` return `true`
`RETURN 'ž' < 'zz'` return `false`

Is that the expected behavior?

**Comment by jsteemann** [comment]
I think the string comparison uses ICU internally, which will perform a collation-based comparison of the two strings.
The collation used by ICU can be controlled by the startup parameter `--default-language`. I am not sure which one is used by default, but I think it is system-dependent. So setting the start parameter to some value explicitly may change the results. An alternative suggestion is to use very "high" Unicode characters such as "\uffff" as the special character just for the comparison. Maybe this "fixes" the problem, too. Can you give it a try?

**Comment by ThomasWeiss** [comment]
Yep that seems to work well. Thanks for your prompt reply!
