### ISSUE TITLE
ArangoDB 3.2.3: Name of user cannot contain space (confusion with "username")

### ISSUE THREAD

**Issue by fingolfin** [arangodb/arangodb#3228]
This is a bare ArangoDB 3.2.3 installation running on Ubuntu 16.04 in single server mode, with "auto" storage engine.

The problem occurs in the web UI, when administrating users: When logged in as root, I can edit users. In the "General" tab, there are three fields: "Username", "Name" and "Active", exactly as shown in the screenshot at <https://docs.arangodb.com/3.2/Manual/Administration/WebInterface/Users.html>.

That screenshot also suggests that one should be able to enter a "Name" (*not* "Username") containing spaces; it shows "Smith, John" as an example.

Trying to do that results in this error in the web UI: `Wrong Username: Username may only contain numbers, letters, _ and -` and the "Name" field gets highlighted in red.

So it looks as if the validation for the "Username" field incorrectly gets applied to the "Name" field.

Alternatively, one is actually forbidden to use a space in a "name"; in that case, I'd still say the error message is wrong, and the screenshot should be adjusted (but I am really hoping it is the former).

**Comment by hkernbach** [comment]
Hello and thanks for the report. Opened PRs for devel and 3.2 branches. The user interface validation was indeed wrong.

**Comment by dothebart** [comment]
Hi, ArangoDB 3.2.6 containing the bugfix to this is available for download, closing.
