### ISSUE TITLE
arangorestore associates data to root

### ISSUE THREAD

**Issue by darkfrog26** [arangodb/arangodb#3252]
I am attempting to upgrade to rocksdb on my server, so I did an arangodump, purged the install, reinstalled, created the user, created the database associating it to the user, then did arangorestore:

`arangorestore --input-directory backup-2017.09.13 --server.database mydb --server.username myuser --server.password mypassword --create-collection true --import-data true`

This completes without error, but when I log in as "myuser" there are no collections.  If I log out and log in as root they are all there.  They were associated to "myuser" before the dump as well.  It seems clear that the `arangorestore` command is improperly assigning the owner as "root" instead of "myuser" when restoring.

## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- 3.2

Mode:
- Single-Server

Storage-Engine:
- rocksdb

On this operating system:
- Linux 
  - Ubuntu .deb

**Comment by darkfrog26** [comment]
Is there a temporary workaround for this so that I can re-associate the database with my user instead of with root?

**Comment by darkfrog26** [comment]
Also, I just noticed that the dump doesn't contain the graph that all the collections were associated with.

**Comment by graetzer** [comment]
Databases are not associated to users, your use may have rights to a database and the collections in it. The user rights are only restored when you restore the **_system** collection.
```
const users = require('@arangodb/users');
users.grantDatabase('myuser', 'mydb', 'rw');
users.grantCollection('myuser', 'mydb', '*', 'rw')
```

Technically your user should have been assigned read / write rights on these collections (if they had to be created). 
Not quite sure what happened, I guess we are missing this an internal grantCollection there ? 


Can *myuser* access *mydbdatabase*? You can check this: 

     users.permission(myuser', 'mydb')

**Comment by darkfrog26** [comment]
I was able to work around this by having my application create the graph and collections before doing the restore and now everything is fine.

**Comment by p30arena** [comment]
Hi there, I can confirm the BUG.
1- Create User
2- Create Database Assigned to the User
3- Restore Data
4- User doesn't have permission to query data
5- Fix it using the administration panel (the default permission is set to none)

**Comment by graetzer** [comment]
Hi I'm really sorry, we forgot to backport a fix for this issue to the 3.2 branch in time for the latest release. This will be resolved once https://github.com/arangodb/arangodb/pull/3717 is merged

**Comment by graetzer** [comment]
This should be fixed in the latest release

**Comment by dothebart** [comment]
Hi, 
3.2.8 containing this fix is available for download now. 
Closing.
