### ISSUE TITLE
Can get collection method create collection if it doesn't exist automatically instead of throwing exception

### ISSUE THREAD

**Issue by rajeshdalai** [arangodb/arangodb#3255]

**Comment by rajeshdalai** [comment]
Please guys, look into this. This is a basic functionality which is expected without which we have to check whether the collection exists or not every time we insert a document. It will be really helpful if we can create and return a new collection implicitly in the get collection method.

**Comment by jsteemann** [comment]
What actually is the "get collection method" you are referring to?
Is that a method in ArangoShell or in a specific driver? If so, which one?

**Comment by dothebart** [comment]
Using i.e. pyArango this is a 4 LOC. 
```
if not db.hasCollection('test'):
    testCol = db.createCollection('Collection', name='test')
else:
    testCol = db.collections['test']
```

Since however you want your setup usually to contain indices etc. creating a collection on access is usually always an error (if not a typo in your program code). 

Thus I will close this now.

**Comment by kamatchsunder** [comment]
Implicit method would be helpful to create collections dynamically. It is available in Mongo though.

**Comment by pavel-the-best** [comment]
Use method
`getCollection(name)`
If collection exists, it will return this collection, else it will create it
