### ISSUE TITLE
VPack error - Expecting type String

### ISSUE THREAD

**Issue by brianrusso** [arangodb/arangodb#3261]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ x] 3.2
- [ ] self-compiled devel branch

Mode:
- [x] Cluster
- [ ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [x ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [x ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

When I update a document using python-arango, I get this error on 3.2.3

[HTTP 500][ERR 4] VPack error: Expecting type String (exception location: /var/lib/otherjenkins/workspace/RELEASE__BuildPackages/arangod/GeneralServer/RestHandler.cpp:204). Please report this error to arangodb.com

**Comment by brianrusso** [comment]
I am on  3.2.3

**Comment by brianrusso** [comment]
Setting _key to a string type instead of a number seems to fix it.. Not sure if this is a bug in arango or python-arango?

**Comment by jsteemann** [comment]
The value of "_key" is expected to be a string, not a number.
However, the server should not report back the server like that, but instead return a proper error message.

**Comment by jsteemann** [comment]
For info, it fails here:
```
#3  arangodb::modifyDocumentOnCoordinator (dbname=..., collname="f", slice=..., options=..., isPatch=isPatch@entry=true, Python Exception <class 'TypeError'> expected string or bytes-like object: 
headers=, 
    responseCode=<optimized out>, errorCounter=..., resultBody=...)
    at /home/steemann/ArangoDevel/arangod/Cluster/ClusterMethods.cpp:2167
2167	        StringRef keyStr(transaction::helpers::extractKeyFromDocument(slice));
(gdb) list
2162	    for (auto const& it : shardMap) {
2163	      if (!useMultiple) {
2164	        TRI_ASSERT(it.second.size() == 1);
2165	        body = std::make_shared<std::string>(slice.toJson());
2166	
2167	        StringRef keyStr(transaction::helpers::extractKeyFromDocument(slice));
2168	        // We send to single endpoint
2169	        requests.emplace_back(
2170	            "shard:" + it.first, reqType,
2171	            baseUrl + StringUtils::urlEncode(it.first) + "/" +
```
There it assumes that _key is always of type "string". It should not make that assumption but properly check it.

**Comment by jsteemann** [comment]
Should be fixed by https://github.com/arangodb/arangodb/pull/3266

**Comment by sleto-it** [comment]
Hi @brianrusso,

Thanks again for reporting this issue. Since a fix has been pushed and you have a workaround in place, I am now closing this ticket

If anything, please feel free to comment and we will reopen it

Thanks again,
