### ISSUE TITLE
Is updating a Foxx service atomic?

### ISSUE THREAD

**Issue by ThomasWeiss** [arangodb/arangodb#3264]
I recently had a weird issue, where I got unexpected errors when updating a Foxx service on a system that's nearly always under load. Those errors were at the Javascript level and reported `TypeError`s that didn't make sense (a JS file `require`'ing another file **in the same Foxx service** but not finding a function there). It seems that it was transient and occured at the time of the Foxx update, and so it would seem that all JS files were not deployed atomically?

**Comment by pluma** [comment]
Can you clarify which version of ArangoDB you were using when you encountered this problem? This should be solved in 3.2.

**Comment by ThomasWeiss** [comment]
Yes that happened on a 3.1.x instance.

**Comment by pluma** [comment]
@ThomasWeiss Okay, thanks. Unless you can reproduce the issue in 3.2 I'd like to close this. We changed how services are managed in 3.2 as part of the cluster resilience improvements and you should no longer see this kind of misbehaviour in ArangoDB.

**Comment by ThomasWeiss** [comment]
Sure please go ahead, actually it wasn't really a bug report but more a question about how Foxx services get updated. Thanks!

**Comment by pluma** [comment]
@ThomasWeiss as of 3.2 the behaviour is transactional within the scope of a single V8 context but eventually consistent both within the single server and across the cluster.

Replacing the service affects the active V8 context first and schedules a change (ASAP, i.e. once it has handled the current request or whatever it is doing at that moment) in the other contexts. Additionally (in cluster mode) it triggers a self-heal on the other coordinators. Even if a coordinator misses that trigger somehow (e.g. network issues) its periodic self-heal will still pick up the change eventually.

Prior to 3.2 the uploaded service bundle would just be extracted to the local filesystem and distributed to the other coordinators. As of 3.2 the bundle is additionally stored in the database so other coordinators can fetch it as needed.
