### ISSUE TITLE
socket: too many open files

### ISSUE THREAD

**Issue by TianDaGe** [arangodb/arangodb#3276]
`{"id":"***", "code":500,"detail":"the database HTTP request failed: Post http://127.0.0.1:8529/_db/_api/cursor: dial tcp 127.0.0.1:8529: socket: too many open files","status":"Internal Server Error"}`
I am trying to insert many many data one by one. So service is connecting to arangodb everytimes.
How can I solve this issue?

**Comment by dothebart** [comment]
You should use HTTP 1.1 and persistent connections in first place.

You could also use [the bulk interface](https://docs.arangodb.com/3.2/HTTP/BulkImports/) for your imports.

**Comment by TianDaGe** [comment]
thanks, @dothebart 
Then how can I authorise arangodb? The sample of document is not working.
How can I select database and collection?

**Comment by dothebart** [comment]
ArangoDB provides a RESTfull interface, you specify database in the request URI if they differ from the default:

`/_db/myDatabase/`

With HTTP1.1 you only share one tcp connection between requests, no other state like authenticification is shared between two requests over the same connection. Thus you have to re-specify the auth-basic header again.

**Comment by TianDaGe** [comment]
I am using https://github.com/solher/arangolite in golang.
This driver is also using HTTP1.1 request. Isn't it?

**Comment by dothebart** [comment]
The officially supported go driver can be found here: https://github.com/arangodb/go-driver for issues with arangolite please contact the original author.

**Comment by TianDaGe** [comment]
hi, @dothebart 
it seems, arangodb/go-driver doesn't support bulkimport feature. right?

**Comment by dothebart** [comment]
as I tried to explain in my edits to the comment you should be able to use the regular document save interface with several documents at once - which should mostly become the same thing.

**Comment by dothebart** [comment]
@TianDaGe does the described procedure work for you? could we close this issue?

**Comment by dothebart** [comment]
Closing as solved. Don't hesitate to ask if there are still remaining questions.
