### ISSUE TITLE
add more coordinator on the dcos ,circling around

### ISSUE THREAD

**Issue by hellomanjack** [arangodb/arangodb#3278]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2

Mode:
- [x] Cluster
- [ ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [x] rocksdb

On this operating system:
- [x] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [x] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

I have 4 agency in the dcos. And the cluster has enough resource for additional coordinator.
Just pick up the offer that is suitable.

![image](https://user-images.githubusercontent.com/25783698/30538381-610af104-9ca0-11e7-800a-9a76922e2b48.png)

[stderr.txt](https://github.com/arangodb/arangodb/files/1310396/stderr.txt)

**Comment by dothebart** [comment]
Please use ArangoDB via the Kubernetes operator which is available with DC/OS. 
ArangoDB 3.7 is available for download:
https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/
