### ISSUE TITLE
Coordinator: giving up waiting for unused V8 context when under load

### ISSUE THREAD

**Issue by choppedpork** [arangodb/arangodb#3295]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2

Mode:
- [x] Cluster

Storage-Engine:
- [x] rocksdb

On this operating system:
- [x] Linux 
  - [x] docker - official docker library
  - [x] other: I've also used a custom self-built Arango docker image (using the official .deb packages under the hood) but can reproduce this issue with both the official version and the custom build

Hello,

I've been running some load tests against a three node (an instance of agency, coordinator and primary on each) cluster. This is done using an application reading and writing into arango (using the Java driver) rather than `arangobench`. As part of the load test a few operations are performed - to the best of my knowledge it's two documents being created, one of them being read and subsequently also updated. This cycle is performed concurrently by many application threads and the end goal of the test is to get to 1mln documents in two collections (1mln documents in each one of them). So far we've been having much better results with the 3.2 series using RocksDB but we're currently running into an issue every few hours where the coordinator node stops responding.

At the time the coordinator starts acting up we start seeing messages like these in the logs:
```
arangodb-coordinator_1          | 2017-09-19T23:59:48Z [16] WARNING {memory} process is near the maximum number of memory mappings. current: 64507, maximum: 65530
arangodb-coordinator_1          | 2017-09-20T00:00:08Z [16] WARNING {memory} process is near the maximum number of memory mappings. current: 64551, maximum: 65530
arangodb-coordinator_1          | 2017-09-20T00:00:18Z [16] WARNING {memory} process is near the maximum number of memory mappings. current: 64539, maximum: 65530
arangodb-coordinator_1          | 2017-09-20T00:00:28Z [16] WARNING {memory} process is near the maximum number of memory mappings. current: 64539, maximum: 65530
arangodb-coordinator_1          | 2017-09-20T00:00:38Z [16] WARNING {memory} process is near the maximum number of memory mappings. current: 64539, maximum: 65530
arangodb-coordinator_1          | 2017-09-20T00:00:49Z [16] WARNING {memory} process is near the maximum number of memory mappings. current: 64539, maximum: 65530
arangodb-coordinator_1          | 2017-09-20T00:00:59Z [16] WARNING {memory} process is near the maximum number of memory mappings. current: 64539, maximum: 65530
arangodb-coordinator_1          | 2017-09-20T00:01:08Z [16] WARNING {v8} giving up waiting for unused V8 context after 60.000000 s
arangodb-coordinator_1          | 2017-09-20T00:01:08Z [16] WARNING {v8} giving up waiting for unused V8 context after 60.000000 s
arangodb-coordinator_1          | 2017-09-20T00:01:08Z [16] WARNING {v8} giving up waiting for unused V8 context after 60.000000 s
arangodb-coordinator_1          | 2017-09-20T00:01:08Z [16] WARNING {v8} giving up waiting for unused V8 context after 60.000000 s
arangodb-coordinator_1          | 2017-09-20T00:01:09Z [16] WARNING {memory} process is near the maximum number of memory mappings. current: 64540, maximum: 65530
arangodb-coordinator_1          | 2017-09-20T00:01:09Z [16] WARNING {v8} giving up waiting for unused V8 context after 60.000000 s
arangodb-coordinator_1          | 2017-09-20T00:01:09Z [16] WARNING {v8} giving up waiting for unused V8 context after 60.000000 s
arangodb-coordinator_1          | 2017-09-20T00:01:09Z [16] WARNING {v8} giving up waiting for unused V8 context after 60.000000 s
arangodb-coordinator_1          | 2017-09-20T00:01:09Z [16] WARNING {v8} giving up waiting for unused V8 context after 60.000000 s
arangodb-coordinator_1          | 2017-09-20T00:01:09Z [16] WARNING {v8} giving up waiting for unused V8 context after 60.000000 s
arangodb-coordinator_1          | 2017-09-20T00:01:09Z [16] WARNING {v8} giving up waiting for unused V8 context after 60.000000 s
arangodb-coordinator_1          | 2017-09-20T00:01:09Z [16] WARNING {v8} giving up waiting for unused V8 context after 60.000000 s
```

This looks very similar to #2324 so I've added some v8 tweaks on the command line:
```--javascript.v8-contexts 5 --javascript.v8-max-heap 3072```
but unfortunately this doesn't seem to make much difference. This issue usually starts occurring after 5-6 hours of testing and the v8 flags don't seem to influence this timing much.

Here's what the memory usage looks like for this particular coordinator node:
<img width="246" alt="screen shot 2017-09-20 at 11 40 12" src="https://user-images.githubusercontent.com/11997044/30639865-8c8f6dd8-9df8-11e7-8600-43374c679367.png">
Here's the CPU usage:
<img width="251" alt="screen shot 2017-09-20 at 11 41 27" src="https://user-images.githubusercontent.com/11997044/30639888-aaf2ecfa-9df8-11e7-8f56-3e448e63cb88.png">
(the above are container metrics obtained using cAdvisor)

Here's the HTTP requests served by the server nodes:
<img width="291" alt="screen shot 2017-09-20 at 11 42 54" src="https://user-images.githubusercontent.com/11997044/30639958-f1e8d264-9df8-11e7-9d79-a476b6ba9b28.png">
(these are obtained from the Arango API - different colours are different HTTP verbs)

As you can see there's a very slight jump in CPU usage at the same time http requests stop being forwarded to the server and afterwards the memory usage starts growing. I'm happy to share the full Grafana dashboard privately if this helps!

After restarting the affected coordinator node the load test goes straight back to normal - the application picks another coordinator node and continues processing.

**Comment by choppedpork** [comment]
sorry - the enter key seems to have created an issue instead of a newline! updating the contents now.

**Comment by jsteemann** [comment]
We recently found that it may help in this context to increase the value of a kernel parameter, as specified [here](https://docs.arangodb.com/devel/Manual/Administration/Configuration/OperatingSystem.html#max-memory-mappings).
The Linux default value for `/proc/sys/vm/max_map_count` seems to be rather low for a powerful server with many cores and many parallel threads, so increasing it may allow a process (i.e. arangod) to use more memory mappings than the default 64K.
Additionally, the number of V8 contexts (`--javascript.v8-contexts`) may need to be increased a bit. It seems you set it 5, but this will mean that if there are more than 5 threads in parallel that require the usage of V8, the other threads will block.
Can you try the adjusted settings to see if that fixes the problem?

**Comment by javiergarmon** [comment]
I had the same issue. Increasing `max_map_count`, `v8-contexts`, `threads` and the frequency of V8 GC it seems solved.

This doesn't happen to us with 3.1.X or prior versions, it started when we migrated to 3.2. Also happened to us in a clean installation.

**Comment by javiergarmon** [comment]
It took a lot of time but one of our coordinators get the same issue.

```
2017-09-23T09:01:13Z [1] WARNING {memory} process is near the maximum number of memory mappings. current: 255044, maximum: 256000
2017-09-23T09:01:23Z [1] WARNING {memory} process is near the maximum number of memory mappings. current: 255046, maximum: 256000
2017-09-23T09:05:59Z [1] WARNING {memory} process is near the maximum number of memory mappings. current: 255001, maximum: 256000
2017-09-23T09:06:09Z [1] WARNING {memory} process is near the maximum number of memory mappings. current: 255009, maximum: 256000
2017-09-23T09:06:19Z [1] WARNING {memory} process is near the maximum number of memory mappings. current: 255014, maximum: 256000
2017-09-23T09:06:29Z [1] WARNING {memory} process is near the maximum number of memory mappings. current: 255017, maximum: 256000
2017-09-23T09:06:39Z [1] WARNING {memory} process is near the maximum number of memory mappings. current: 255021, maximum: 256000
2017-09-23T09:06:49Z [1] WARNING {memory} process is near the maximum number of memory mappings. current: 255022, maximum: 256000
2017-09-23T09:06:59Z [1] WARNING {memory} process is near the maximum number of memory mappings. current: 255022, maximum: 256000
2017-09-23T09:07:11Z [1] WARNING {memory} process is near the maximum number of memory mappings. current: 255022, maximum: 256000
2017-09-23T09:07:25Z [1] WARNING {memory} process is near the maximum number of memory mappings. current: 255022, maximum: 256000
2017-09-23T09:07:36Z [1] WARNING {memory} process is near the maximum number of memory mappings. current: 255024, maximum: 256000
2017-09-23T09:07:49Z [1] WARNING {memory} process is near the maximum number of memory mappings. current: 255024, maximum: 256000
2017-09-23T09:08:00Z [1] WARNING {memory} process is near the maximum number of memory mappings. current: 255024, maximum: 256000
2017-09-23T09:08:10Z [1] WARNING {memory} process is near the maximum number of memory mappings. current: 255021, maximum: 256000
2017-09-23T09:08:20Z [1] WARNING {memory} process is near the maximum number of memory mappings. current: 255026, maximum: 256000
2017-09-23T09:08:30Z [1] WARNING {memory} process is near the maximum number of memory mappings. current: 255026, maximum: 256000
2017-09-23T09:09:35Z [1] WARNING {memory} process is near the maximum number of memory mappings. current: 255026, maximum: 256000
2017-09-23T09:09:45Z [1] WARNING {memory} process is near the maximum number of memory mappings. current: 255030, maximum: 256000
2017-09-23T09:09:55Z [1] WARNING {memory} process is near the maximum number of memory mappings. current: 255031, maximum: 256000
```

In this case the config of the coordinator is:

```
[server]
authentication = true
endpoint = tcp://[::]:8529
threads = 16
jwt-secret = ***
[log]
level = info
[javascript]
v8-contexts = 32
gc-frequency = 10
gc-interval = 128
[database]
index-threads = 4
```

**Comment by choppedpork** [comment]
Thanks @jsteemann - running more tests now after increasing max_map_count (as well as doubling v8 contexts). So far so good but it usually takes about 6hrs before I hit this issue so I'll report once the test is complete later on.

I've read through all the tuning recommendations that you've linked (as well as implemented all of them before re-testing) and I have a couple of questions:
- The docs specify a rule of thumb for calculating the max_map_count value - when I follow this the resulting value is _lower_ than the default as I'm running tests on a 2-core system (but with 15G of ram and very fast storage). I've resorted to making it 262144 as this seems to be a very common tweak for Elasticsearch as well and that's the value a lot of articles seem to recommend. Should 256k be the de-facto recommended value regardless of the number of cores?
- There seems to be a bit of a discrepancy in the overcommit_memory setting - the docs specify this should be 0 however looking at the logs of the server and coordinator nodes I get this message: 
`WARNING {memory} /proc/sys/vm/overcommit_memory is set to '0'. It is recommended to set it to a value of 2`
Which one is correct?

**Comment by jsteemann** [comment]
Thanks for coming back. I have created a [PR](https://github.com/arangodb/arangodb/pull/3321) to change the documentation and to increase the recommended default values.

**Comment by choppedpork** [comment]
Thanks @jsteemann! I can confirm now that the load test has finished successfully and I believe `max_map_count` is what solved the issue here. I'm running a higher throughput test now to verify again but things are looking good.

**Comment by choppedpork** [comment]
I can definitely confirm that this problem has been resolved for me now. Thanks for your help @jsteemann!

**Comment by dothebart** [comment]
Ok, Thanks a lot for confirming.

**Comment by javiergarmon** [comment]
@dothebart in our case logs have disappeared, the process just finish when the map limit is reached (checked with `pmap`). Should I open other issue? Is the same case :S

**Comment by dothebart** [comment]
You need to increase the available mappings. The current way jemalloc handles this isn't the best way - we're working on analysing whether we find a better way of doing this.

Eventually you may want to start more coordinators to better distribute the mappings across more processes. Please report back if neither of both solves the issue.

**Comment by javiergarmon** [comment]
@dothebart the mappings allowed in our systems is around 2.5 millions, it take some hours due to the volume of queries we have to reach that value.

The current config is the suggested:
```sh
sudo bash -c "echo madvise >/sys/kernel/mm/transparent_hugepage/enabled"
sudo bash -c "echo madvise >/sys/kernel/mm/transparent_hugepage/defrag"
sudo bash -c "echo 0 >/proc/sys/vm/overcommit_memory"
sudo bash -c "echo 0 >/proc/sys/vm/zone_reclaim_mode"
sudo bash -c "sysctl -w 'vm.max_map_count=2500000'"
export GLIBCXX_FORCE_NEW=1
```

All the config is permanent. Also we have tested with `echo 2 >/proc/sys/vm/overcommit_memory` and it usually resist more hours. Also we tried with `numactl --interleave=all` even when our system isn't NUMA enabled, no improvements found with this change.

Currently we have 9 coordinators working, so load balancing between them are the only way to not suffer this bug.

Thanks for all your efforts, I'm pretty sure you will fix it in an elegant way and soon 😃

**Comment by dothebart** [comment]
You should be able to increase the max mapping count even more. 
We're currently adding monitoring for this to collectd: https://github.com/collectd/collectd/pull/2454
so we can trace it a bit better throughout loadtests.

**Comment by javiergarmon** [comment]
That's perfect! I will check it this afternoon :) Thanks

**Comment by dashdeep13** [comment]
I have a configuration where I have 8 nodes with 8 coordinators and 8 db servers and 3 agents. After reading the above discussion I had set the value of max mapping count = 8*4*8000 = 256000.
After 14 days, the memory mapping limit was reached.
I understand that I can increase the memory mappings to a higher value but looks like the problem will then occur at a later time, but definitely occur : O. 
Is there a fix for this coming out in 3.3?
Thanks!

**Comment by dothebart** [comment]
Hi, 
we recently learned, that the V8 engine included in 3.2 has a memory leak. 
We're currently working on 3.2.7 with a fixed version of V8.

**Comment by dashdeep13** [comment]
3.2.7 is out today, I see that we have increased the number of initial V8 contexts,but I did not see a memory fix for the V8 engine, is that covered? Did I miss anything?

**Comment by dothebart** [comment]
Hi, 
Yes the V8 engine has also been upgraded.
