### ISSUE TITLE
[1.1] Suggestion: implement data export in arangosh

### ISSUE THREAD

**Issue by frankmayer** [arangodb/arangodb#331]
I think it would be cool if arangosh could get a command like export() to export data.

```
cursor = db.users.all();
export ( "myExportFile.json", cursor);
```

or with statements:

```
cursor = db._createStatement({ "query" : "for u in users return u" }).execute();
export ( "myExportFile.json", cursor, overwriteswitch, formatswitch);
```

In this last example I have also passed some other parameters.
- overwriteswitch: If export file exists, override or not
- formatswitch: this would default to json, but should  include options csv, & tsv.

in combination with #329, this would allow batching of exporting data commands

Sidenote:
if arangosh also would include arangoimp's functionality then all would be in one tool.

**Comment by razvanphp** [comment]
`JavaScript exception: ReferenceError: SYS_SAVE is not defined`

Is there a new way now? @frankmayer syntax looked good to me.

**Comment by jsteemann** [comment]
The global functions (including `SYS_SAVE`) have been moved out of the global scope a few years ago. The write-data-to-file function is now available in the `fs` module:

```js
var fs = require("fs");
fs.write(filename, contents);
```

**Comment by razvanphp** [comment]
Worked like a charm, thanks!
