### ISSUE TITLE
Traversal Query unpredictable

### ISSUE THREAD

**Issue by MPanicucci** [arangodb/arangodb#3315]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [x] 3.1
- [ ] 3.2
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [x] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
 [x] I'm using graph features

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

Hello,
I have a problem with traversal queries.
I execute traversal with options {"uniqueEdges": "path"} and this return all result but with timing very slow about 25 s.  
then i change options in {"uniqueEdges": "global"} but the response is:
"Query: uniqueEdges: 'global' is not supported, due to unpredictable results. Use 'path' or 'none' instead (while instantiating plan)".

**Comment by jsteemann** [comment]
Can you share the exact query you are executing?
How many results are returned for the query with `{"uniqueEdges":"path"}`?

**Comment by graetzer** [comment]
This is a bug in the documentation, the {"uniqueEdges": "global} option is currently unsupported, we may look into adding it back in again.

**Comment by graetzer** [comment]
Sorry I just skimmed over the text, regarding the other issue: 
How many paths are returned? Do you have  `FILTER`statements on all edges or vertices ?

**Comment by dothebart** [comment]
@MPanicucci can you provide a small example data set demonstrating your issue?

**Comment by maxkernbach** [comment]
Hi @MPanicucci,

closing this issue for now because we have not received any feedback for a few months. Please reopen if this issue persists with current versions and provide a small data set.

Thanks
