### ISSUE TITLE
Java driver issue

### ISSUE THREAD

**Issue by zzqangel** [arangodb/arangodb#3323]
### this is an java driver issue:
[ ] I'm using Edge collection. I found that I can't batch insert into the ArangoEdgeCollection with BaseEdgeDocument. But for ArangoCollection, it is OK.

It is too slow by insert one by one. How can I insert BaseEdgeDocument faster?

**Comment by dothebart** [comment]
Hi, 
did you try using this interface: https://github.com/arangodb/arangodb-java-driver/#insert-documents

**Comment by zzqangel** [comment]
Hi,
thanks for answering.I tried this [interface]( https://github.com/arangodb/arangodb-java-driver/#insert-documents), and it's working.
I thought that interface is using for BaseDocument and not for BaseEdgeDocument.
But when I tried this interface, I found that it's working on BaseEdgeDocument too.

**Comment by dothebart** [comment]
In general in ArangoDB edge documents are just regular documents with two special attributes: `_to` and `_from`. 
I currently don't know how this is mapped in the java driver, but except for enforcing the availability of these attributes there can't be much more to add.

Closing.
