### ISSUE TITLE
Web interface collection load fails

### ISSUE THREAD

**Issue by kashifpk** [arangodb/arangodb#3324]
On latest arango 3.2, the web interface often fails to load collections. The error displayed doesn't offer much information either. Loading the same collection via arangosh or via the HTTP API works but the collection isn't accessible in arangosh either.

I'm using the latest ArangoDB of the respective release series:
- [X ] 3.2

Mode:
- [X ] Single-Server

Storage-Engine:
- [X] rocksdb

On this operating system:
- [X ] Linux 
  - [X ] Ubuntu .deb

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [X ] authentication is enabled?

h3. Collection load fails from web interface

![image](https://user-images.githubusercontent.com/198638/30844739-c3d0dc04-a2a9-11e7-8d07-000e75203d1a.png)

h3. Collection loads from arangosh but isn't accessible

![image](https://user-images.githubusercontent.com/198638/30844851-4f09392e-a2aa-11e7-84fc-482648c9172a.png)

h3. Other collections in the database are accessible without issues

![image](https://user-images.githubusercontent.com/198638/30844876-6667a7a4-a2aa-11e7-8b21-b29a7a90e5eb.png)

This is a fresh arangodb 3.2 install with rocksdb engine. So far there have been a few issues related to collection loading and access.  These never happened in previous releases.

**Comment by maxkernbach** [comment]
Hello,
i have tried to reproduce your error using a fresh arangodb installation with the same operating system and settings, no error while loading collections occurred for me though. Which collections did you use and did always the same collection fail to load?

**Comment by kashifpk** [comment]
I have a database with a graph and most of the collections belong to that graph. When I load the graph those collections get loaded correctly. The collections that are not part of the graph stay unloaded and clicking them on the web interface gives the error mentioned above. For this particular database, the problem now seems to have become permanent. 

On the same database running db._collections() from arango shell also gives error

```
> db._collections()
2017-09-26T13:49:12Z [6596] ERROR JavaScript exception in file '/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js' at 98,7: ArangoError 11: No access to collection
2017-09-26T13:49:12Z [6596] ERROR !      throw error;
2017-09-26T13:49:12Z [6596] ERROR !      ^
```

Accessing the collection in question also gives error but it loads without errors

```
127.0.0.1:8529@threatify> db._collection('settings')
2017-09-26T13:50:20Z [6596] ERROR JavaScript exception in file '/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js' at 98,7: ArangoError 11: No access to collection
2017-09-26T13:50:20Z [6596] ERROR !      throw error;
2017-09-26T13:50:20Z [6596] ERROR !      ^

127.0.0.1:8529@threatify> db._collection('settings').load()
```

After loading the collection this way, I am able to add records to the collection via the web interface.

If I drop the collection and create it again it is loaded by default but restarting the arangod instance again results in the same issue.

Plus when I first access the database without loading the graph, some of the collections that are part of the graph are in loaded state while others are not

h3. Some collections are loaded before graph load

![image](https://user-images.githubusercontent.com/198638/30864151-48f4ef46-a2ec-11e7-9d05-897696fbe3d6.png)

h3. After graph load, non-graph collections stay unloaded and cannot be loaded

![image](https://user-images.githubusercontent.com/198638/30864221-744132fe-a2ec-11e7-8a75-0cdc954ea5e9.png)

**Comment by kashifpk** [comment]
I dropped the database and created it again and then recreated the collections still the same problem persists.

**Comment by maxkernbach** [comment]
In order to reproduce it your database/collections are required. You can attach your database directory in github if its size is less than 25MB or send us a script that creates your collections and graph.

**Comment by kashifpk** [comment]
Attached is the db backup taken via arangodump.

[db.zip](https://github.com/arangodb/arangodb/files/1336668/db.zip)

**Comment by maxkernbach** [comment]
Does your problem still occur? I have reproduced it with the latest version of 3.2 under Ubuntu. No error appears when restoring your db backup via arangorestore. I was able to load the collections by clicking them on the web interface and with use of arango shell.

**Comment by kashifpk** [comment]
The problem still occurs and it seems to an issue with non-root users. Seems to be a recurring issue, I had problems using arangorestore with a non-root user before (that is a known issue). If I login using root, I have no problems loading collections from the web interface. With any other user that has full rights to the database, collections loading fails.

**Comment by maxkernbach** [comment]
Thanks for reporting the bug. I was able to load the collections with a different user from the web interface with a workaround mentioned in #3252 (arango shell) after importing with arangorestore:
```
const users = require('@arangodb/users');
users.grantDatabase('myuser', 'mydb', 'rw');
users.grantCollection('myuser', 'mydb', '*', 'rw')
```

**Comment by jsteemann** [comment]
This issue should be fixed in 3.2.6

**Comment by hwde** [comment]
I've had a similar issue with 3.2.6 and rocksdb engine. Here is how I could reproduced it:
- login as user root to WebInterface, db = _system
- create user abc with password def
- create database ghi (assign user abc)
- switch database to ghi (still user root)
- create a collection "jkl"

now try to import some json data to that collection jki with arangoimp:

arangoimp --server.endpoint tcp://127.0.0.1:8529 \
		--server.username abc \
		--server.database ghi \
		--server.password def --file somefile.json --collection jkl 

this results in "ERROR forbidden".

**Comment by mchacki** [comment]
This in indeed intended behaviour.

With creating the database `ghi` for user `abc` this user is allowed to manage collections within this database, she does not get access to all collections in the database by default.
Only those collections that she has created herself will give her full access.
=> In your case `root` created `jkl` => `root` has full access, `abc` does not have write access.
=> Import as `abc` is forbidden.

You can change this by either granting `abc` full access to all collections:
1. IN the Webinterface goto users
2. Select `abc`
3. Select Permissions on the Top bar
4. Open database `ghi`
5. There is `collections` -> `*` set it to `Read/Write`

alternatively login as `abc` in the webui and create collection `jkl` with this user.

**Comment by sleto-it** [comment]
Hi @kashifpk,

Just wondering if you had a chance to test versions >= 3.2.6 and if you still experience the original issue described in this ticket

Can we consider this ticket solved?

Many thanks,

**Comment by kashifpk** [comment]
@sleto-it yes just tested with 3.2.9 and this issue is resolved. Thanks :-)

**Comment by sleto-it** [comment]
Thanks for the feedback @kashifpk , appreciated!
