### ISSUE TITLE
TypeScript [ts] Module '"arangojs"' has no exported member 'aql'

### ISSUE THREAD

**Issue by miff** [arangodb/arangodb#3328]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series: 3.2
Mode: Single-Server
Storage-Engine: mmfiles
On this operating system: MacOS, version: 10.12.6

### this is an AQL-related issue:
Just follow initial tutorial: 
```
// Modern JavaScript
import {Database, aql} from 'arangojs'
...
```
but throw error: module '"arangojs"' has no exported member 'aql'

Thanks

**Comment by dothebart** [comment]
Hi, could you please open this issue in the arangojs repository? This repository is supposed to contain bugs about the arangodb server itself.
