### ISSUE TITLE
About the cluster mode

### ISSUE THREAD

**Issue by zzqangel** [arangodb/arangodb#3337]
I'm using the arangodb command to set up an arangodb clusters DB server on windows10.
But I find that, sometimes one cluster or more will be unable to start up success.And I open url "http://127.0.0.1:8259". The server condition is 4 coordinators and 3 DB or less are online.
I try to shutdown the failure cluster and reconnect.But it's not working each time.I have to reboot my computer, and restart the server.And most of time , it will solve this problem.
I wanna know that which way is the right way to ensure each cluster will connect to the master cluster success.
And I use these commands to start up the server.
"C:\Program Files\ArangoDB3e 3.2.3\usr\bin\arangodb.exe" --starter.data-dir=F:/arangodb/db1
"C:\Program Files\ArangoDB3e 3.2.3\usr\bin\arangodb.exe" --starter.data-dir=F:/arangodb/db2 --starter.join 127.0.0.1
and more...

And one more thing, I find that when I start up the server, my cpu will be 100% full load for a while，not every time but most of.

**Comment by sleto-it** [comment]
Hi @zzqangel ,

Thanks for opening this issue

Please could you tell us a bit more about your windows 10 machine: how much RAM and what kind of CPU do you have?

To start all nodes in a single machine, I'd expect you have enough resources

On my Win10, 16Gb RAM, i7, SSD, I am using similar commands to yours to start a test cluster, and seems all is working fine

Using version 3.2.6, and after unpacking the arangodb archive (similar commands can be used if you have installed using the installer):

```
"D:\qa\3.2.6\ArangoDB3e-3.2.6-1_win64\usr\bin\arangodb.exe" --starter.data-dir=C:\qa\3.2.6\node1 --server.storage-engine=rocksdb
"D:\qa\3.2.6\ArangoDB3e-3.2.6-1_win64\usr\bin\arangodb.exe" --starter.data-dir=C:\qa\3.2.6\node2 --starter.join 127.0.0.1 --server.storage-engine=rocksdb
"D:\qa\3.2.6\ArangoDB3e-3.2.6-1_win64\usr\bin\arangodb.exe" --starter.data-dir=C:\qa\3.2.6\node3 --starter.join 127.0.0.1 --server.storage-engine=rocksdb
```

(note that I am using two different disks, one for the data, and one for the binaries.
(please remove that `--server.storage-engine` if you do not want to use RocksDB as engine)

The above commands start: 3 DBServers, 3 Agents, and 3 Coordinators. You can access Coordinators at the following addresses:

- localhost:8529
- localhost:8534
- localhost:8539

Please can you try again, ideally using the latest available hotfix (3.2.6 currently) and in case you still have problems share the logs from all nodes? Please also share a screenshot of the UI (from any of the coordinators, tab "Cluster")

Hope this helps,

Thanks,

**Comment by zzqangel** [comment]
Thanks so much for help.
My Win10 machine have 20Gb RAM, i7-6700k and SSD.
Today early, I started a new server, and I found this "Server statistics (-local-) are disabled." on the server page and this "coordinator not ready after 5min; status trail: []int{-3, 503}" on command line.
Be honest, I felt so confusion.
Further more, I use "ctrl+c" to stop and rerun the command, everything is OK.But why?

**Comment by sleto-it** [comment]
Hi @zzqangel ,

Do you have other ArangoDB single-server instances running on the same machine? (perhaps some of them start automatically during boot. Windows "Services" application should help to see if this is the case). If yes, please, could you try to stop them so we start from a fresh situation, and we start the cluster using 3 different shells, using commands similar to those I have posted in my previous comment

To be able to help more we will need to see the exact and full commands you are using to start the cluster, and the log files of all nodes. Can you attach the logs in this issue?

Thanks,

**Comment by dothebart** [comment]
Hi, 
is this still an issue? or can we close this?

**Comment by sleto-it** [comment]
Hi @zzqangel,

We have not received additional news from you in the last 54 days, despite our two recent messages

I think it is safe to close this ticket now. If you have any additional feedback, please do let us know and we will be happy to re-open this ticket

Thanks again for opening this,

**Comment by p30arena** [comment]
https://github.com/arangodb/arangodb/issues/5373
