### ISSUE TITLE
[BUG] Authentication is broken with agency.activate=true. Module unusable in cluster mode

### ISSUE THREAD

**Issue by wzrdtales** [arangodb/arangodb#3345]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2

Mode:
- [x] Cluster

On this operating system:
- [x] Linux 
  - [x] docker - official docker library

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [x] authentication is enabled?
- [x] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) start with docker run -it --rm -p8529:8529 -e ARANGO_RANDOM_ROOT_PASSWORD=1 --name=agent1 arangodb/arangodb arangod --server.jwt-secret "hallo" --agency.activate true
2) open the browser on http://127.0.0.1:8529
3) log in as root with the password generated
4) fail to login

To make it work, actually the only thing that helps is removing agency.activate all together. As soon as it appears as a parameter auth is broken, no matter what you try to configure.

**Comment by kvahed** [comment]
You may not log into agents over UI. Agents are functional entities, whose functionality is exposed at the API `/_api/agency/...`. For example like so in your case:

`curl -H "Authorization: bearer $(jwtgen -a HS256 -s hallo -c 'iss=arangodb' -c 'server_id=setup')" [::]:8529/_api/agency/read -d '[["/"]]'`

Full documentation of the agents' API is found here: 
https://docs.arangodb.com/3.2/HTTP/Agency/
