### ISSUE TITLE
Traversal path ALL filter not working correctly

### ISSUE THREAD

**Issue by roman1720** [arangodb/arangodb#3363]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [* ] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [* ] Single-Server

Storage-Engine:
- [* ] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ *] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[* ] I'm using graph features

I'm issuing AQL via:
- [* ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

When I run following query:

FOR v, e, p IN 1..10000 any 'vDevice/334474' GRAPH 'linkGraph' OPTIONS { 'uniqueVertices': 'global' , bfs: 'true'} filter p.edges[*].wan all != 'tunnel' return {hostname: v.hostname}

filter is not applied. When I add edges or path to returned json, then filter is applied

FOR v, e, p IN 1..10000 any 'vDevice/334474' GRAPH 'linkGraph' OPTIONS { 'uniqueVertices': 'global' , bfs: 'true'} filter p.edges[*].wan all != 'tunnel' return {hostname: v.hostname, e: e}

First query returns all vertices, second only few of them (filter is correctly applied).

**Comment by roman1720** [comment]
Another issue with traversal filter. Result set differs when filtered value is specified with variable or constant (although both values are same). See screenshot
![traversal_bug](https://user-images.githubusercontent.com/13378043/31175494-b4195e50-a90f-11e7-9728-79286aad768c.png)

**Comment by roman1720** [comment]
What about fixing this bug? You are graph database and such a basic thing as filtering on traversal is not working correctly :) I'm hitting it all the time and it's very annoying. Thanks

**Comment by gurisko** [comment]
Is this still reproducible in 2019?

**Comment by hkernbach** [comment]
@roman1720 First, sorry for the late reply. This ticket here has come out of sight. 
@roman1720 @gurisko This issue has been fixed and is not reproducible in any official supported ArangoDB version. Keep in mind, 3.2 is EOL.  

I verified and tested with the latest 3.3 (3.3.23), latest 3.4 (3.4.6.1) and current devel branch.
