### ISSUE TITLE
rocks db config error on startup

### ISSUE THREAD

**Issue by ftKnox** [arangodb/arangodb#3366]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [X] 3.2

Mode:
- [ ] Cluster
- [X] Single-Server

Storage-Engine:
- [ ] mmfiles
- [X] rocksdb

On this operating system:
- [X] Linux 
  - [X] other: archlinux

It appears the rocksdb.use-direct-writes option mentioned [here](https://www.arangodb.com/why-arangodb/comparing-rocksdb-mmfiles-storage-engines/) in the "Tuning the RocksDB engine" does not work correctly. The rocksdb.use-direct-reads option works as expected.

```
[rocksdb]
rocksdb.block-cache-size=12G
rocksdb.use-direct-reads=true
rocksdb.use-direct-writes=true
```

```
Oct 03 09:24:08 arangod[9148]: Error while processing config file '//etc/arangodb3/arangod.conf', line #15:
Oct 03 09:24:08 arangod[9148]:   unknown option '--rocksdb.use-direct-writes'
Oct 03 09:24:08 arangod[9148]: Did you mean this?
Oct 03 09:24:08 arangod[9148]:   --rocksdb.use-direct-reads    use O_DIRECT for reading files
```

**Comment by dothebart** [comment]
Hi, 
The option was removed upstream by the rocksdb team - thus we had to remove it too when upgrading. 
We should also remove it from the article.

**Comment by dothebart** [comment]
Ok, 
Removed. Thanks for reporting.

**Comment by ftKnox** [comment]
yep, thanks for the clarification.
