### ISSUE TITLE
Login Failed! on web interface

### ISSUE THREAD

**Issue by akkinenivijay** [arangodb/arangodb#3367]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [x] 3.2
- [ ] self-compiled devel branch

Mode:
- [x] Cluster
- [ ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [x] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [x] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [x] other: CentOS
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [x] authentication is enabled?
- [x] using the cluster?
- [x] _system database?

These are the steps to reproduce:
1) Provision 3 nodes
2) curl -O https://download.arangodb.com/arangodb32/xUbuntu_16.04/Release.key
3)  sudo apt-key add - < Release.key
4) echo 'deb https://download.arangodb.com/arangodb32/xUbuntu_16.04/ /' | sudo tee /etc/apt/sources.list.d/arangodb.list
5) sudo apt-get install apt-transport-https
6)  sudo apt-get update
7) echo arangodb3 arangodb3/password password arangodb | debconf-set-selections
8) echo arangodb3 arangodb3/password_again password arangodb | debconf-set-selections
9) sudo apt-get install arangodb3
10) Configure arangod.conf to below:

 [database]
directory = /var/lib/arangodb3-agency

[server]
endpoint = tcp://10.101.2.10:5001
authentication = true
jwt-secret = querty012345

[javascript]
startup-directory = /usr/share/arangodb3/js
app-path = /var/lib/arangodb3-apps

[log]
level = info
file = /var/log/arangodb3/arangod-agency.log

[agency]
activate = true
size = 3
supervision = true
my-address = tcp://10.101.2.10:5001
endpoint = tcp://10.101.2.13:5001
endpoint = tcp://10.101.2.11:5001
endpoint = tcp://10.101.2.10:500

The following problem occurs: 
http://10.101.2.10:5001/_db/_system/_admin/aardvark/index.html login as "root" and "arangodb", getting error as "Login Failed!"

**Comment by dothebart** [comment]
Hi, 
you should note that you've added blanks - `password arangodb` is most probably your desired password?
You most probably will have to escape the blank in order to make it work.

**Comment by akkinenivijay** [comment]
Below is the output from debconf-get-selections  | grep arango
arangodb3	arangodb3/password_again	password	arangodb
arangodb3	arangodb3/password	password	arangodb
arangodb3	arangodb3/upgrade	boolean	true
arangodb3	arangodb3/storage_engine	select	rocksdb
arangodb3	arangodb3/password_mismatch	error
arangodb3	arangodb3/backup	boolean	true

from my understanding debconf-set-selections takes 1)  name of the package 2) the configuration database key 3) the type of the answer 4) user input. Which in my case **arangodb** is the password input.

**Comment by akkinenivijay** [comment]
Figured out what the issue is, the debconf helper doesn't really perform a cluster wide root password, once we start the cluster with agency.activate=true 'login failed!' messages appears. The proper way is to disable authentication on all primary and coordinators, start them and on one of the coordinator change root password via shell and restart the cluster with authentication enabled. Hopefully this will save some time to others.

**Comment by yzho0907** [comment]
@akkinenivijay --server.authentication do not exist in 3.4.0 anymore, can i ask how to disable authentication?
