### ISSUE TITLE
Databases not syncing in agency setup

### ISSUE THREAD

**Issue by jean-amana** [arangodb/arangodb#3382]
Hi,
We are running an agency setup on 3 Linux hosts. 
ArangoDB version 3.2.3.
We followed the agency creation manual here:
https://docs.arangodb.com/3.2/Manual/Deployment/Agency.html

Issue: Database and collections are not replicated among the machines.

However the agency seems to work as we are accessing the hosts through the load-balancing mechanism (databases from 1 of the 3 hosts are displayed at each refresh).
Also when removing an host, a new leader is properly elected (we can check that in the logs), so the machines are talking to each other.

So creating a database will create it in one of the 3 hosts, but will not sync it to the others.
Restarting the service is not causing the databases to be synced.

Please note that authentication is disabled (as in the agency deployment manual).

**Comment by kvahed** [comment]
Hi jean-amana,

the Agents are not meant to be used for collection replication. They are also meant to be solely used as a RAFT (https://raft.github.io) key-value-store. What you need for replicated collections is an ArangoDB cluster.  
https://docs.arangodb.com/3.2/Manual/Deployment/

The stand-alone agency is only useful for projects, where you are building your own distributed application and would like to rely on a central resilient configuration. We at ArangoDB use the agency to organise and administer our clusters.

For more you might want to have a look at 
https://www.youtube.com/watch?v=OiZRiBcMzkc

Kind regards.

**Comment by kvahed** [comment]
Also, I should add that you may actually use the agency as a resilient key-value-store. But then your only way to insert/update/remove etc keys is the agency's API:
https://docs.arangodb.com/3.2/HTTP/Agency/

**Comment by jean-amana** [comment]
Hi kvahed,
Thanks for the feedback! Indeed it was quite difficult to understand what the agency is used for or if it is mandatory or not.
We will change our configuration accordingly.
