### ISSUE TITLE
clear old _rev records

### ISSUE THREAD

**Issue by kuselan84** [arangodb/arangodb#3383]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [x ] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [x ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [x ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

Is that possible to remove old revisions of documents to compact the table?

**Comment by dothebart** [comment]
The [server compaction](https://docs.arangodb.com/3.2/Manual/Administration/Configuration/Compaction.html) takes care of that.
