### ISSUE TITLE
Cluster Coordinator Connections

### ISSUE THREAD

**Issue by elsmorian** [arangodb/arangodb#3401]
My issue is less a problem and more a question regarding expected / common setup (and maybe suggested documentation)

When running in a cluster with multiple co-ordinators, how do you choose which one to connect to? And if it doesn't matter, is it usual to put some sort of load balancer in front and use that to manage the load across each one? 

With something like Cassandra the driver is aware of all nodes and which data they have on them to make requests straight to the right node, in Arango this task is performed by the Coordinator I think, but just wanted to check it is not expected to choose or round robin through the list of coordinator in the application code?

**Comment by dothebart** [comment]
Which client driver do you use?

**Comment by elsmorian** [comment]
python-arango, and was infect directed here by its author after asking a similar question there - https://github.com/joowani/python-arango/issues/54

**Comment by dothebart** [comment]
ok, as discussed on python-arango I think we can close this question for now.
