### ISSUE TITLE
How to kill long running AQL queries with the browser console's AQL

### ISSUE THREAD

**Issue by zhenruyan** [arangodb/arangodb#3403]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [x] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [ ] mmfiles
- [x] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [x] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[x] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

How to kill long running AQL queries with the browser console's AQL

I want to end another long running AQL query with AQL in the browser

Thanks

**Comment by zhenruyan** [comment]
I've searched

**Comment by zhenruyan** [comment]
But it's not relevant

**Comment by dothebart** [comment]
AQL is only a Data modification language (DML). Neither Data Definition (DDL) nor administrations are parts of it - so its not possible.

**Comment by zhenruyan** [comment]
How do you limit the memory used by Arangodb?

**Comment by jsteemann** [comment]
There are a few options, for example: 
```
--query.memory-limit
--cache.size
--rocksdb.block-cache-size
```

**Comment by zhenruyan** [comment]
Thank you, may I ask how Foxx app can get to the official store?

**Comment by alexpmorris** [comment]
This sounds related to the problem I just came across in the v3.2.6 GUI.  When running queries in the GUI, under `Running Queries` there should be a red "cancel" button with a minus sign in it as such:
<img src="https://docs.arangodb.com/3.2/Manual/Administration/WebInterface/images/runningQueries.png">

However, this is what I see in the v3.2.6 GUI *(I also tried both firefox and chrome with the same result)*:

![image](https://user-images.githubusercontent.com/5326789/32254472-596bffee-be77-11e7-8c37-625868474462.png)

**Comment by jsteemann** [comment]
@alexpmorris : Thanks for reporting this. The display issue in the web UI should be fixed with PR https://github.com/arangodb/arangodb/pull/3564

**Comment by sleto-it** [comment]
Hi @zhenruyan, @alexpmorris 

Thanks for opening and contributing to this ticket, and for your patience. Version 3.2.7 has now been released and it includes a fix for this problem

Please could you upgrade? I am now closing this ticket. If the issue persists, please feel free to comment

Many thanks,
