### ISSUE TITLE
{"code":500,"error":true,"errorMessage":"AQL: illegal name: \"channelAnalysisRequest\" (while parsing)","errorNum":1208}

### ISSUE THREAD

**Issue by tmd313** [arangodb/arangodb#3407]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [X ] 3.2 
- [ ] self-compiled devel branch

(exact version is: # arangod --version
3.2.4 )

Mode:
- [ X] Cluster
- [ ] Single-Server

Storage-Engine:
- [ X] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ X] Linux 
  - [ ] Debian .deb
  - [ X] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click to ...
...

The following problem occurs: [Screenshot?] 
root@86a063f8dfd0:/tmp# time ./exportDbByCollection.sh vmanager
  "vmanager", 
./exportDbByCollection.sh: line 24: [[: 17 /tmp/vmanager.collections.out: division by 0 (error token is "tmp/vmanager.collections.out")
Found 17 /tmp/vmanager.collections.out collections to export. Starting to export them now.
Purging directory /tmp/dbExportvmanager prior to exporting collections.
Exporting collection "channelAnalysisRequest" at Wed Oct 11 20:42:10 UTC 2017
Connected to ArangoDB 'http+tcp://127.0.0.1:8529', version 3.2.4, database: 'vmanager', username: 'root'
# Exporting collection '"channelAnalysisRequest"'...
{"code":500,"error":true,"errorMessage":"AQL: illegal name: \"channelAnalysisRequest\" (while parsing)","errorNum":1208}
2017-10-11T20:42:10Z [285] ERROR {startup} caught exception during start of feature 'Export': got invalid response from server: HTTP 500: Internal Server Error (exception location: /var/lib/otherjenkins/workspace/RELEASE__BuildPackages/arangosh/Export/ExportFeature.cpp:578). Please report this error to arangodb.com. shutting down
2017-10-11T20:42:10Z [285] ERROR {startup} arangoexport terminated because of an unhandled exception: startup aborted: internal error (exception location: /var/lib/otherjenkins/workspace/RELEASE__BuildPackages/lib/ApplicationFeatures/ApplicationServer.cpp:642). Please report this error to arangodb.com
Error: of 1 exporting collection "channelAnalysisRequest" to directory /tmp/dbExportvmanager

BTW, the code that is running this export is this, from a shell script:

I get a list of collections from running db._collections(); in arangosh in this vmanager DB. I then loop through them using a for loop that references the collection name, it is in quotes in the file which I expect the shell to strip (BTW, this is the first collection in the file, fails on first one):

for c in `cat /tmp/${1}.collections.out`
do
   echo "Exporting collection $c at `date`"
   arangoexport --output-directory /tmp/dbExport${1} --server.database $1  --server.endpoint tcp://127.0.0.1:8529 --server.authentication false --collection $c
   retval=$?
   if [[ $retval -ne 0 ]]; then
      echo "Error: of $retval exporting collection $c to directory /tmp/dbExport${1}"
      exit 5
   fi
done

Instead I would be expecting: 

Successful export of the collection. This is how the collection appears in a list of collections.

  [ArangoCollection 8037522, "channelAnalysisRequest" (type document, status loaded)], 

(BTW, I restored this DB using arangorestore)

These are the collection properties (it is not sharded):

127.0.0.1:8529@vmanager> db.channelAnalysisRequest.properties();
{ 
  "doCompact" : true, 
  "journalSize" : 33554432, 
  "isSystem" : false, 
  "isVolatile" : false, 
  "waitForSync" : false, 
  "shardKeys" : [ 
    "_key" 
  ], 
  "numberOfShards" : 1, 
  "keyOptions" : { 
    "type" : "traditional", 
    "allowUserKeys" : true, 
    "lastValue" : 0 
  }, 
  "indexBuckets" : 8, 
  "replicationFactor" : 1 
}

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

**Comment by tmd313** [comment]
BTW, the list of collections names that I got from arangosh were encased in quotes. I removed the quotes and then things worked fine. It's a bit odd, but I'm past the issue. Up to you of course to close this if you see fit, but a note in the docs might help in cases such as these. I was surprised that the linux shell did not remove them when passing the parameter to arangoexport.

**Comment by jsteemann** [comment]
It seems that the script uses collection names that are enclosed in both single and double quotes.
If the line in the bash script
```bash
echo "Exporting collection $c at date"
```
prints
```
Exporting collection '"channelAnalysisRequest"'...
```
and `$c` is passed to arangoexport as-is by the same script, it would mean that arangoexport gets
```bash
arangoexport  (some more parameters here) --collection '"channelAnalysisRequest"'
```
which bash should all unquote and resolve to the following argv list:
* arangoexport
* (some more parameters here)
* --collection
* "channelAnalysisRequest"
meaning that the collection name still has a pair a quotes around it after bash has stripped the initial surrounding quotes.

I think this is one level of quotes too much, which the calling script should remove.

**Comment by tmd313** [comment]
You are correct, Jan. I corrected for that ( sed -i 's/\"//g' /tmp/${1}.collections.out ) and it ran to completion without issue.

I had not seen what you mention/noticed in the output. Thanks for the response and sorry for any inconvenience.

Thanks,
               Tim

Tim Dillon

ARRIS
900 Chelmsford Street
Lowell, MA 01851-8100
978-614-3145

**Comment by jsteemann** [comment]
I suggest we close this now.

**Comment by tmd313** [comment]
Certainly. Thanks.

Tim Dillon

ARRIS
900 Chelmsford Street
Lowell, MA 01851-8100
978-614-3145
