### ISSUE TITLE
[1.1] Feature request: On unique constrain violation exceptions include ids or keys that were involved

### ISSUE THREAD

**Issue by frankmayer** [arangodb/arangodb#342]
I think it would be good to know which constraint has been violated on a document /edge save , instead of a generic message. 
This could be either somehow inside the exception string in an easy to parse way or as a property to the exception object.

What do you think?

**Comment by dothebart** [comment]
We're pleased to anounce that ArangoDB 3.2 containing this is now available for download - Closing.
