### ISSUE TITLE
High memory usage on arango server while using the arangoexport client

### ISSUE THREAD

**Issue by tmd313** [arangodb/arangodb#3437]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [X] 3.2
- [ ] self-compiled devel branch

Mode:
- [X] Cluster
- [ ] Single-Server

Storage-Engine:
- [X] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [X] Linux 
  - [ ] Debian .deb
  - [x] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

Any data set that exceeds 700 MB.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click to ...
...

The following problem occurs: [Screenshot?] 
Instead I would be expecting: 

I'm stuck with the options available. Is it really true that the arangoexport utility does not export json records each on a single line? 

Successful import. But instead in one case it crashed the coordiantor from which it ran. The cluster has 3 coordinators, 3 agents and 3 dbservers each on different nodes.

An associated issue as I try to accommodate restrictions in arangodb import (arangoimp) related to --batch-size is that if I reduce the batch size from 1GB to 256MB is that I use the 'split' utility to chunk the output file from an arangoexport but the file apparently doesn't have a json per line, which inhibits the workaround. I've tried both the -C (250MB lines) and the -l 5000 and both break the import. The lines are very long, btw, some in excess of 41,000 characters.

I also tried to use the collectionName.structure.json from a new arangodump for an aranagorestore from an older version (3.0.12) (which the docs say you may be able to edit the old one to add the sharding structure) using it's data file (got arrango error 4) restoring to 3.2.4 arangorestore.

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

I do an arangoexport on each collection in a DB. I drop the DB and do an arangoimport for each collection in the former db but I create the collection first so that I can create a properly sharded collection appropriate for a cluster out of a formerly single node DB. This is something I would imagine that many, many people will be looking to make this transition (just pointing out that there is considerable value in this sort of operation).

Considering helpful options, a way to modify an old arangodump data file so that it could be arangorestore(d) to a newer version (this seems like the fastest method of re-creation I've seen). The docs say that you should be able to modify the .structure.json file from the old dump to import to the new DB. I will try that in respect to using the new .structure.json files on the old dump (I already tried using the old .data.json file to restore using a new .structure.json file.

I'm stuck with the options available. Is it really true that the arangoexport utility does not export json records each on a single line? Without that item and with the apparent memory issue in arangoimp I cannot split the files from arangoexport and import them using arangoimport, something we need to do in order migrate from stand-alone to clustered DBs for protection (something I'm sure many people are or will be trying to do. Sorry for repeating this, but I'm not sure that you would get to this point in this issue.

Sorry this is so long winded. Thanks!!

**Comment by tmd313** [comment]
Meant to include this (saw it up > 22.GB in virt mem:

top - 09:56:24 up 26 days, 15:39,  3 users,  load average: 33.33, 19.90, 10.88
Tasks: 264 total,   2 running, 261 sleeping,   0 stopped,   1 zombie
%Cpu(s):  2.6 us, 27.6 sy,  0.0 ni,  0.3 id, 59.4 wa,  0.0 hi, 10.1 si,  0.0 st
KiB Mem :  4046156 total,   111968 free,  3771116 used,   163072 buff/cache
KiB **Swap:  4194300 total,       36 free**,  4194264 used.    34556 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                        
 4626 root      20   0 **18.946g** 1.119g      0 S  25.3 29.0  61:05.37 arangod                                                        
 2372 root      20   0  806108  88920   4556 S   5.8  2.2   2640:45 scope                                                          
   44 root      20   0       0      0      0 D   5.4  0.0  87:53.22 kswapd0

**Comment by tmd313** [comment]
Showing the data lines from export in the export file and in the collection itself. Why are they off by 1? I do see that there is what appears to be a very, very long line that starst with "[", no quotes, followed quite while 'later' by data, rest of json?

root@86a063f8dfd0:/tmp/checkNewDump/tmp/dbExportvmanager# wc -l merCmData.json 
29591 merCmData.json
root@86a063f8dfd0:/tmp/checkNewDump/tmp/dbExportvmanager# arangosh --server.database vmanager
Please specify a password: 

                                       _     
  __ _ _ __ __ _ _ __   __ _  ___  ___| |__  
 / _` | '__/ _` | '_ \ / _` |/ _ \/ __| '_ \ 
| (_| | | | (_| | | | | (_| | (_) \__ \ | | |
 \__,_|_|  \__,_|_| |_|\__, |\___/|___/_| |_|
                       |___/                 

arangosh (ArangoDB 3.2.4 [linux] 64bit, using jemalloc, VPack 0.1.30, RocksDB 5.6.0, ICU 58.1, V8 5.7.0.0, OpenSSL 1.0.2g  1 Mar 2016)
Copyright (c) ArangoDB GmbH

Pretty printing values.
Connected to ArangoDB 'http+tcp://127.0.0.1:8529' version: 3.2.4 [server], database: 'vmanager', username: 'root'

Type 'tutorial' for a tutorial or 'help' to see common examples
127.0.0.1:8529@vmanager> db.merCmData.count();
29590


Any help here is, of course, greatly appreciated.

**Comment by tmd313** [comment]
There is no --batch-size in the arangoexport command. I've seen that in python examples on the net, but it's not in the utility. That would be optimal. Thanks.

**Comment by jsteemann** [comment]
For reference: to export line-wise documents (separated by newlines) with arangoexport, you can use the `--type jsonl` option when exporting. By default it seems to export all documents as a JSON array.

**Comment by tmd313** [comment]
Thanks for your suggestion. I had tried that but with the -C option of split. Last night I had changed to using the not line-bytes, but the line, -l option, but had not gone back to try jsonl with it. I now am past the issue, but just to let you know, arangod seems to keep growing, perhaps from when my imports had failed:

top - 07:26:41 up 27 days, 13:10,  3 users,  load average: 41.70, 53.92, 29.38
Tasks: 226 total,   2 running, 224 sleeping,   0 stopped,   0 zombie
%Cpu(s): 13.2 us, 13.5 sy,  0.0 ni, 24.9 id, 42.7 wa,  0.0 hi,  5.6 si,  0.1 st
KiB Mem :  4046156 total,  1765696 free,  1929264 used,   351196 buff/cache
KiB Swap:  4194300 total,  2939364 free,  1254936 used.  1828336 avail Mem 

  PID USER      PR  NI    **VIRT**    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                       
 1724 root      20   0 **21.789g** 1.339g   4936 S  43.2 34.7  13:17.27 arangod

Thanks again.

**Comment by dothebart** [comment]
Hi, 
with ArangoDB 3.2.8 we fixed some important memory management issues by applying upstream V8 patches and improving our jemalloc integration.

Can you please retry whether this is still an issue after the upgrade?

**Comment by tmd313** [comment]
Will do. Thanks for the update.

Tim Dillon

ARRIS
900 Chelmsford Street
Lowell, MA 01851-8100
978-614-3145

**Comment by tmd313** [comment]
I have retried. There’s some good news and some not so good news. I did 2 tests after rebuilding under 3.2.8 version of arangodb.

In the first test I split the large file, which is 732M, into 3 separate files, which creates these files (all under 255MB):

-rw-r--r-- 1 root root 238M Nov 22 19:24 xaac
-rw-r--r-- 1 root root 247M Nov 22 19:24 xaaa
-rw-r--r-- 1 root root 247M Nov 22 19:24 xaab

In the 2nd test, I drop the DB that these are getting imported into and run it again with now split, one large 732 MB file for one of the 17 collections in the DB. You can see the results below. While the 1st test outcome looks pretty good, the 2nd test outcome looks pretty good too except for the Coordinator node that did the actual loading, which ended up with 9.287 G virtual mem allocated to it where the entire load set is 856MB in jsonl formatted files.

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
   17 root      20   0  9.827g 102928  19420 S   0.3  2.5   0:56.90 arangod
    1 root      20   0   18048      0      0 S   0.0  0.0   0:00.02 startup.sh
    8 root      20   0   17028   7756   4688 S   0.0  0.2   0:02.24 arangodb

Here’s the detail across the Coordinators and DBsvrs. The Agents are not really a significant part of this (this is a 9 docker cluster where each docker (3 each of Agent, Coordinator, DBsvr) is on a separate VM.

I have a little “before” section here as well:

A sample coordinator (cpc4s1-backoffice1) before the import:

top - 18:46:00 up 63 days, 20:30,  0 users,  load average: 1.25, 0.53, 0.31
Tasks:   5 total,   1 running,   4 sleeping,   0 stopped,   0 zombie
%Cpu(s):  2.9 us,  1.0 sy,  0.0 ni, 95.9 id,  0.0 wa,  0.0 hi,  0.2 si,  0.0 st
KiB Mem :  4046156 total,   710716 free,   929316 used,  2406124 buff/cache
KiB Swap:  4194300 total,  3531248 free,   663052 used.  2749572 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
    8 root      20   0   17028  10644   6776 S   0.3  0.3   0:00.72 arangodb
   17 root      20   0 1773748 308748 132204 S   0.3  7.6   0:04.88 arangod

A sample DBsvr (cpc4s2-vmanager3):

root@5842d5be59c7:/home/arangodb/utilscripts# free
              total        used        free      shared  buff/cache   available
Mem:        4046128      953520      286700       45868     2805908     2709728
Swap:       4194300      389736     3804564
root@5842d5be59c7:/home/arangodb/utilscripts# top
top - 18:44:38 up 43 days, 21:43,  0 users,  load average: 0.08, 0.22, 0.33
Tasks:   5 total,   1 running,   4 sleeping,   0 stopped,   0 zombie
%Cpu(s):  3.5 us,  1.7 sy,  0.0 ni, 94.5 id,  0.0 wa,  0.0 hi,  0.1 si,  0.3 st
KiB Mem :  4046128 total,   284008 free,   956200 used,  2805920 buff/cache
KiB Swap:  4194300 total,  3804564 free,   389736 used.  2707048 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
   17 root      20   0 1598480 631748 482624 S   0.7 15.6   0:08.03 arangod
    1 root      20   0   18048   2876   2652 S   0.0  0.1   0:00.02 startup.sh
    8 root      20   0   17028  14368   6776 S   0.0  0.4   0:00.58 arangodb

And after importing using < 255MB files (3 way split of this file:
               -rw------- root/root 766524202 2017-10-17 07:14 tmp/dbExportvmanager/merCmData.jsonl)

Coordinator after load:

root@49cbaffc58b8:/tmp# free
              total        used        free      shared  buff/cache   available
Mem:        4046156      608324     3077212        3892      360620     3160900
Swap:       4194300     1030804     3163496
root@49cbaffc58b8:/tmp# top
top - 18:57:11 up 63 days, 20:41,  0 users,  load average: 0.20, 0.63, 0.46
Tasks:   5 total,   1 running,   4 sleeping,   0 stopped,   0 zombie
%Cpu(s):  3.3 us,  1.8 sy,  0.0 ni, 94.8 id,  0.0 wa,  0.0 hi,  0.1 si,  0.0 st
KiB Mem :  4046156 total,  3074704 free,   609984 used,   361468 buff/cache
KiB Swap:  4194300 total,  3163752 free,  1030548 used.  3159248 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
   17 root      20   0 9443992  95904  18880 S   1.0  2.4   0:48.35 arangod
    8 root      20   0   17028   7804   4684 S   0.7  0.2   0:01.68 arangodb

DBsvr after load:

root@5842d5be59c7:/home/arangodb/utilscripts# free
              total        used        free      shared  buff/cache   available
Mem:        4046128     1080624      569060       34808     2396444     2634296
Swap:       4194300      431180     3763120
root@5842d5be59c7:/home/arangodb/utilscripts# top
top - 18:58:02 up 43 days, 21:56,  0 users,  load average: 0.49, 1.01, 0.68
Tasks:   5 total,   1 running,   4 sleeping,   0 stopped,   0 zombie
%Cpu(s):  3.9 us,  1.9 sy,  0.0 ni, 93.7 id,  0.0 wa,  0.0 hi,  0.1 si,  0.3 st
KiB Mem :  4046128 total,   561476 free,  1087540 used,  2397112 buff/cache
KiB Swap:  4194300 total,  3763124 free,   431176 used.  2627364 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
   17 root      20   0 7839488 1.925g 1.662g S   2.3 49.9   1:08.56 arangod
    8 root      20   0   17028  12128   6772 S   0.3  0.3   0:01.54 arangodb

Now for the full file, no split, dropped the db, started over (hmm, not so good):

Coordinator:

(there’s no ‘time’ command in this docker so I improvised):

root@49cbaffc58b8:/tmp# date > keepTime;./importDbByCollection.sh vmanagerExportedCollections.tar.gz vmanager load cluster  ;date >> keepTime

root@49cbaffc58b8:/tmp# cat keepTime
Wed Nov 22 19:02:47 UTC 2017
Wed Nov 22 19:05:12 UTC 2017
root@49cbaffc58b8:/tmp# free
              total        used        free      shared  buff/cache   available
Mem:        4046156      660352     2913528        4232      472276     3108356
Swap:       4194300      998392     3195908
root@49cbaffc58b8:/tmp# top
top - 19:06:36 up 63 days, 20:50,  0 users,  load average: 1.76, 0.80, 0.53
Tasks:   5 total,   1 running,   4 sleeping,   0 stopped,   0 zombie
%Cpu(s):  2.2 us,  1.6 sy,  0.0 ni, 96.1 id,  0.0 wa,  0.0 hi,  0.1 si,  0.0 st
KiB Mem :  4046156 total,  2911492 free,   662364 used,   472300 buff/cache
KiB Swap:  4194300 total,  3196040 free,   998260 used.  3106336 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
   17 root      20   0  9.827g 102928  19420 S   0.3  2.5   0:56.90 arangod
    1 root      20   0   18048      0      0 S   0.0  0.0   0:00.02 startup.sh
    8 root      20   0   17028   7756   4688 S   0.0  0.2   0:02.24 arangodb
   68 root      20   0   18228   2540   2304 S   0.0  0.1   0:00.07 bash
  793 root      20   0   36656   3028   2584 R   0.0  0.1   0:00.00 top

DBsvr (not bad):

root@5842d5be59c7:/home/arangodb/utilscripts# free
              total        used        free      shared  buff/cache   available
Mem:        4046128     1082340      297924       34812     2665864     2632776
Swap:       4194300      431176     3763124
root@5842d5be59c7:/home/arangodb/utilscripts# top
top - 19:07:51 up 43 days, 22:06,  0 users,  load average: 0.15, 0.30, 0.43
Tasks:   5 total,   1 running,   4 sleeping,   0 stopped,   0 zombie
%Cpu(s):  4.1 us,  2.8 sy,  0.0 ni, 92.6 id,  0.0 wa,  0.0 hi,  0.1 si,  0.4 st
KiB Mem :  4046128 total,   300864 free,  1079376 used,  2665888 buff/cache
KiB Swap:  4194300 total,  3763124 free,   431176 used.  2635740 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
   17 root      20   0 7347456 2.014g 1.753g S   0.7 52.2   1:44.39 arangod
    1 root      20   0   18048   2652   2652 S   0.0  0.1   0:00.02 startup.sh
    8 root      20   0   17028  12584   6808 S   0.0  0.3   0:02.18 arangodb

The other 2 Coordinators:

(cpc4s1-backoffice2):

root@f5efd290de65:/home/arangodb/utilscripts# free
              total        used        free      shared  buff/cache   available
Mem:        4046156     2848876      386112       35688      811168      717620
Swap:       4194300     3807024      387276
root@f5efd290de65:/home/arangodb/utilscripts# top
top - 19:09:28 up 63 days, 20:52,  0 users,  load average: 4.10, 3.55, 3.07
Tasks:   5 total,   1 running,   4 sleeping,   0 stopped,   0 zombie
%Cpu(s): 31.7 us, 15.5 sy,  0.4 ni, 46.3 id,  3.8 wa,  0.0 hi,  2.1 si,  0.1 st
KiB Mem :  4046156 total,   384424 free,  2830480 used,   831252 buff/cache
KiB Swap:  4194300 total,   367152 free,  3827148 used.   735660 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
   16 root      20   0 1784976  51768  10216 S   0.7  1.3   0:18.84 arangod
    1 root      20   0   18048    272    272 S   0.0  0.0   0:00.06 startup.sh
    7 root      20   0   17028   5512   2176 S   0.0  0.1   0:02.12 arangodb

Next coord (cpc4s1-vcore1):

root@df352827323d:/home/arangodb/utilscripts# free
              total        used        free      shared  buff/cache   available
Mem:      264092296    37122240   221144932      330104     5825124   225664608
Swap:     268304380           0   268304380
root@df352827323d:/home/arangodb/utilscripts# top
top - 19:10:54 up 23 days,  1:35,  0 users,  load average: 1.67, 1.38, 1.51
Tasks:   5 total,   1 running,   4 sleeping,   0 stopped,   0 zombie
%Cpu(s):  3.8 us,  0.5 sy,  0.0 ni, 95.6 id,  0.0 wa,  0.0 hi,  0.1 si,  0.0 st
KiB Mem : 26409228+total, 22112422+free, 37142660 used,  5825408 buff/cache
KiB Swap: 26830438+total, 26830438+free,        0 used. 22564393+avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
   19 root      20   0 2270508 395200 131516 S   0.7  0.1   0:17.26 arangod
    8 root      20   0   18852  12840   6776 S   0.3  0.0   0:01.34 arangodb

Other 2 DBsvrs:

(cpc4s2-vmanager1):

root@8e297d6bfce5:/home/arangodb/utilscripts# free
              total        used        free      shared  buff/cache   available
Mem:        4046128     1298488      313932       25292     2433708     2436652
Swap:       4194300      976176     3218124
root@8e297d6bfce5:/home/arangodb/utilscripts# top
top - 19:12:28 up 43 days, 22:12,  0 users,  load average: 0.30, 0.29, 0.34
Tasks:   5 total,   1 running,   4 sleeping,   0 stopped,   0 zombie
%Cpu(s):  2.8 us,  1.7 sy,  0.0 ni, 95.2 id,  0.0 wa,  0.0 hi,  0.1 si,  0.3 st
KiB Mem :  4046128 total,   313916 free,  1297908 used,  2434304 buff/cache
KiB Swap:  4194300 total,  3218128 free,   976172 used.  2437172 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
   16 root      20   0 7510556 2.181g 1.920g S   0.7 56.5   1:55.56 arangod
    1 root      20   0   18048   2304   2304 S   0.0  0.1   0:00.02 startup.sh
    7 root      20   0   17028   7760   4476 S   0.0  0.2   0:02.58 arangodb

Next DBsvr (cpc4s2-vmanager2):

root@4eaebf10db03:/home/arangodb/utilscripts# free
              total        used        free      shared  buff/cache   available
Mem:        4046128     1456740      243496       32372     2345892     2268200
Swap:       4194300      971672     3222628
root@4eaebf10db03:/home/arangodb/utilscripts# top
top - 19:13:39 up 43 days, 22:12,  0 users,  load average: 0.45, 0.65, 0.53
Tasks:   5 total,   1 running,   4 sleeping,   0 stopped,   0 zombie
%Cpu(s):  2.7 us,  2.5 sy,  0.0 ni, 94.1 id,  0.0 wa,  0.0 hi,  0.3 si,  0.3 st
KiB Mem :  4046128 total,   238796 free,  1460812 used,  2346520 buff/cache
KiB Swap:  4194300 total,  3222628 free,   971672 used.  2264092 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
   16 root      20   0 6958620 1.875g 1.586g S   0.3 48.6   1:16.50 arangod
    1 root      20   0   18048   2624   2624 S   0.0  0.1   0:00.02 startup.sh
    8 root      20   0   17028   9964   6268 S   0.0  0.2   0:02.40 arangodb

NOW, back to the original coordinator where we did the load (in case it let go of the excess memory in more of a lazy fashion (nope, still not so good)):

root@49cbaffc58b8:/tmp# free
              total        used        free      shared  buff/cache   available
Mem:        4046156      669216     2903024        4288      473916     3099444
Swap:       4194300      994424     3199876
root@49cbaffc58b8:/tmp# top
top - 19:14:57 up 63 days, 20:59,  0 users,  load average: 0.11, 0.34, 0.41
Tasks:   5 total,   1 running,   4 sleeping,   0 stopped,   0 zombie
%Cpu(s):  2.8 us,  1.8 sy,  0.0 ni, 94.6 id,  0.8 wa,  0.0 hi,  0.1 si,  0.0 st
KiB Mem :  4046156 total,  2903104 free,   669128 used,   473924 buff/cache
KiB Swap:  4194300 total,  3199916 free,   994384 used.  3099532 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
   17 root      20   0  9.827g 116200  19420 S   0.3  2.9   0:59.34 arangod
    1 root      20   0   18048      0      0 S   0.0  0.0   0:00.02 startup.sh
    8 root      20   0   17028   7912   4760 S   0.0  0.2   0:02.76 arangodb



Tim Dillon

ARRIS
900 Chelmsford Street
Lowell, MA 01851-8100
978-614-3145

**Comment by dothebart** [comment]
ArangoExport currently works in a way that a whole collection has to be copied to RAM on the server side. This is causing huge memory consumption on the exporting server depending on the collection size.

**Comment by maxkernbach** [comment]
Hi @tmd313,

we have released [3.4.0 RC2](https://www.arangodb.com/download-technical-preview/), which includes significant improvements for arangoexport.
The new [streaming AQL cursors](https://docs.arangodb.com/devel/Manual/ReleaseNotes/NewFeatures34.html#streaming-aql-cursors) allow to execute AQL queries initiated via the cursor API in a streaming fashion instead of building the entire query result up in memory. In 3.4 streaming AQL cursors are used for arangoexport by default and therefore should address the memory issue.

Could you please try arangoexport with the latest RC and share your feedback?

**Comment by tmd313** [comment]
I will try though it may take a while. Just finished implementing rolling upgrade for cluster in kubernetes. Need to check out ‘major’ upgrade, or is it, 3.3.x to 3.4.x? approach.

Thanks for the information and adaptation. Very nice.

Tim Dillon

ARRIS
900 Chelmsford Street
Lowell, MA 01851-8100
978-614-3145

**Comment by maxkernbach** [comment]
Hi @tmd313,

please note that the 3.4.0 release candidates are for testing purposes only, not for production usage. The rolling upgrade from 3.3.x to 3.4.x is not supported yet and will be available either in following RC's or the 3.4.0 GA at the latest.

For now it is only possible to export the data from the 3.3.x cluster with arangodump and then restore it with arangorestore in the 3.4.0 RC.

**Comment by tmd313** [comment]
Thanks for the info, Max. I’ll take your suggested approach in the mean time.

Tim Dillon

ARRIS
900 Chelmsford Street
Lowell, MA 01851-8100
978-614-3145

**Comment by maxkernbach** [comment]
Hi Tim,

did you already have a chance to test it?

**Comment by tmd313** [comment]
Not yet but I will try to do so soon thanks.

Tim Dillon

ARRIS
900 Chelmsford Street
Lowell, MA 01851-8100
978-614-3145

**Comment by tmd313** [comment]
Hi,

I downloaded the packages via the links below:
arangodb3_3.4.0~rc.3-1_amd64.deb
arangodb3-client_3.4.0~rc.3-1_amd64.deb

I cannot install the 2 packages (client/server) together as they conflict. Suggestions. See below:

Selecting previously unselected package arangodb3-client.
(Reading database ... 5596 files and directories currently installed.)
Preparing to unpack .../arangodb3-client_3.4.0~rc.3-1_amd64.deb ...
Unpacking arangodb3-client (3.4.0~rc.3-1) ...
Setting up arangodb3-client (3.4.0~rc.3-1) ...
arangodb3 arangodb3/backup boolean true
Selecting previously unselected package arangodb3.
^[[91mdpkg: regarding .../arangodb3_3.4.0~rc.3-1_amd64.deb containing arangodb3:
arangodb3 conflicts with arangodb3-client
  arangodb3-client (version 3.4.0~rc.3-1) is present and installed.

dpkg: error processing archive /home/arangodb/utilscripts/arangodb3_3.4.0~rc.3-1_amd64.deb (--install):
conflicting packages - not installing arangodb3
^[[0m^[[91mErrors were encountered while processing:
/home/arangodb/utilscripts/arangodb3_3.4.0~rc.3-1_amd64.deb
^[[0mERROR of 1 attempting to install arangodb3 step 6.

Tim Dillon

ARRIS
900 Chelmsford Street
Lowell, MA 01851-8100
978-614-3145

**Comment by maxkernbach** [comment]
Hi @tmd313, 

The server package `arangodb3_3.4.0~rc.3-1_amd64.deb` and the client tools package `arangodb3-client_3.4.0~rc.3-1_amd64.deb` both contain client tools, the server package just contains the server tools on top of it.

Can you try the [tarball](https://download.arangodb.com/arangodb34/Community/Linux/arangodb3-linux-3.4.0-rc.3.tar.gz) to use the 3.4 RC3 client tools instead? It has got statically linked binaries, which should work on any linux. Also it doesn't have the implication to conflict with existing client tools, since you can extract it to any location.

**Comment by Simran-B** [comment]
> Now I know that the server contains the client pieces. All set on this subject. The documentation seemed to tell me otherwise or perhaps I just misinterpreted it.

Do you refer to this page? https://docs.arangodb.com/3.4/Manual/Programs/

Or some other page/version? The 3.4 programs overview looks alright to me, it lists all the server and client tools. Should we add a sentence that the full package comes with server+client tools?

**Comment by tmd313** [comment]
I’m referring to this page: https://www.arangodb.com/download-technical-preview/ubuntu-preview/

I must have just confused it myself as looking at it now it’s pretty clear that the server contains the client tools.

My bad, the page seems accurate.

Sorry for the confusion.

Tim Dillon

ARRIS
900 Chelmsford Street
Lowell, MA 01851-8100
978-614-3145

**Comment by tmd313** [comment]
I’ve tested this and the export seems to work fine but the import doesn’t. I’ve attached logs for each. The merImport.log shows the problems with the import and the logOfExportDbByCollection_sh.log shows a good export of what did get imported though the import died on the 4th collection.

A little background. The arangodb is running in a kubernetes cluster setup with 1 container per component with the components being 3 @ agents, 3 @ coordinators and 3 @ dbservers. Each is a docker container running in a k8s pod.

The script that does the import splits the collection into files of 5,000 lines each (if the original file is > 250 MB) and then imports them in a loop using arangoimp. Here’s that part of the script:

      split -a 3 -l 5000 ../tmp/dbExport${dbnameInFile}/${c}.jsonl
…
…
      for f in `ls *`
      do
         # --overwrite off for split load
         arangoimp --batch-size 268435456 --collection $c  --file $f --type jsonl --server.database $2  --server.endpoint tcp://127.0.0.1:8529 --server.authentication false
…
…
    done

This is the template that I use in the script when creating each collection.

TMPLT='{
  "doCompact" : true,
  "journalSize" : 33554432,
  "isSystem" : false,
  "isVolatile" : false,
  "waitForSync" : false,
  "shardKeys" : [
    "_key"
  ],
  "numberOfShards" : 12,
  "keyOptions" : {
    "type" : "traditional",
    "allowUserKeys" : true,
    "lastValue" : 0
  },
  "indexBuckets" : 8,
  "replicationFactor" : 2
}'

I just removed error checking and ancillary code for clarity.


Here are the file sizes, collection names and record counts:

root@arangodb-coordinator-0:/tmp/origTmpImport/dbExportvmanager# ll
total 876400
drwxr-xr-x 3 root root      4096 Nov  6 20:42 ./
drwxr-xr-x 3 root root      4096 Nov  6 20:42 ../
drwxr-xr-x 2 root root      4096 Oct 17  2017 Confs/
-rw------- 1 root root    671506 Oct 17  2017 channelAnalysisRequest.jsonl
-rw-r--r-- 1 root root        34 Oct 17  2017 export.version
-rw------- 1 root root   3098497 Oct 17  2017 ico2Data.jsonl
-rw------- 1 root root   3502039 Oct 17  2017 ico2Request.jsonl
-rw------- 1 root root 766524202 Oct 17  2017 merCmData.jsonl
-rw------- 1 root root  97494533 Oct 17  2017 merCmData30.jsonl
-rw------- 1 root root  26016522 Oct 17  2017 merRequest.jsonl
-rw------- 1 root root       110 Oct 17  2017 moduleSettings.jsonl
-rw------- 1 root root     21538 Oct 17  2017 networkElementInventory.jsonl
-rw------- 1 root root      1412 Oct 17  2017 nodeServicesConfig.jsonl
-rw------- 1 root root         0 Oct 17  2017 orca_guest.jsonl
-rw------- 1 root root     13140 Oct 17  2017 orca_host.jsonl
-rw------- 1 root root         0 Oct 17  2017 orca_network.jsonl
-rw------- 1 root root      1502 Oct 17  2017 orca_specification.jsonl
-rw------- 1 root root         0 Oct 17  2017 orca_thread.jsonl
-rw------- 1 root root     21680 Oct 17  2017 vcoreConfig.jsonl
-rw------- 1 root root     10514 Oct 17  2017 vcoreDeployTemplates.jsonl
-rw------- 1 root root      4054 Oct 17  2017 vcoreInventory.jsonl
-rw-r--r-- 1 root root       248 Nov  6 20:42 vmanager.collections.out
root@arangodb-coordinator-0:/tmp/origTmpImport/dbExportvmanager# cat vmanager.collections.out
channelAnalysisRequest
ico2Data
ico2Request
merCmData
merCmData30
merRequest
moduleSettings
networkElementInventory
nodeServicesConfig
orca_guest
orca_host
orca_network
orca_specification
orca_thread
vcoreConfig
vcoreDeployTemplates
vcoreInventory
root@arangodb-coordinator-0:/tmp/origTmpImport/dbExportvmanager# wc -l *
wc: Confs: Is a directory
        0 Confs
     1000 channelAnalysisRequest.jsonl
        1 export.version
      697 ico2Data.jsonl
      952 ico2Request.jsonl
    29590 merCmData.jsonl
   184928 merCmData30.jsonl
     1017 merRequest.jsonl
        1 moduleSettings.jsonl
       55 networkElementInventory.jsonl
        1 nodeServicesConfig.jsonl
        0 orca_guest.jsonl
        6 orca_host.jsonl
        0 orca_network.jsonl
        3 orca_specification.jsonl
        0 orca_thread.jsonl
       11 vcoreConfig.jsonl
        5 vcoreDeployTemplates.jsonl
        6 vcoreInventory.jsonl
       17 vmanager.collections.out
   218290 total


Tim Dillon

ARRIS
900 Chelmsford Street
Lowell, MA 01851-8100
978-614-3145

**Comment by dothebart** [comment]
support for the MMFiles storage engine has been droppend with 3.7. 
Please find the release notes here:
 https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/
multiple changes have been added to arangorestore:
  https://www.arangodb.com/docs/stable/programs-arangorestore-fast-cluster-restore.html
