### ISSUE TITLE
What are database views and how do they work ?

### ISSUE THREAD

**Issue by matcho** [arangodb/arangodb#3440]
## my environment running ArangoDB
- [x] 3.2 (3.2.4)
- [x] Single-Server
- [x] rocksdb
- [x] Linux 
  - [x] Ubuntu .deb (Ubuntu 16.04 x86_64)

### this is an arangosh-related question:
arangosh `help` command mentions something called "View Functions" :
```
View Functions:                                                           
  _views()                                  list all views                
  _view(<name>)                             get view by name              
  _createView(<name>, <type>, <properties>) creates a new view 
```

I couldn't find any clues in the documentation; what are those views and how do they work ?

**Comment by MrPieces** [comment]
Hi Matcho,

sorry for the confusion.'Views' is a preparation for a bigger new feature that we will fully integrate and release soon:ish. This feature will introduce 'views' for its specific purpose.

Hope I could clarify things

**Comment by matcho** [comment]
Hi MrPieces,

Thank you for the quick and precise answer.
Looking forward to see this feature !
