### ISSUE TITLE
Arangodump fails, Operation now in progress

### ISSUE THREAD

**Issue by gil9393** [arangodb/arangodb#3446]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [V] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [V] Single-Server

Storage-Engine:
- [ ] mmfiles
- [V] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [V] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

We are trying to use arangodump to backup our data but i get the following error:

FATAL Error message: 'Could not connect to 'http+tcp://<hostname>:<port>' 'connect() failed with #115 - Operation now in progress''

The command i am running is:

arangodump --server.endpoint tcp://<hostname>:<port> --server.username <username> --server.password <password> --server.database <Database> --output-directory "<Name>"

The version of arangodb that we are running is 3.2.2.

Any ideas on why this is happening and how do i fix this?

**Comment by jsteemann** [comment]
Posted an answer here: https://groups.google.com/forum/#!topic/arangodb/YKv8ymbX2S0

**Comment by dothebart** [comment]
Closing as abandoned.
