### ISSUE TITLE
de-installing arangodb .deb doesn't stop service

### ISSUE THREAD

**Issue by roman1720** [arangodb/arangodb#3455]
3.2.5 rocksdb on debian8 clean install

127.0.0.1:8529@_system> db._collections()
[ 
  [ArangoCollection 603288, "_appbundles" (type document, status loaded)], 
  [ArangoCollection 60, "_apps" (type document, status loaded)], 
  [ArangoCollection 36, "_aqlfunctions" (type document, status loaded)], 
  [ArangoCollection 54, "_frontend" (type document, status unloaded)], 
  [ArangoCollection 2, "_graphs" (type document, status unloaded)], 
  [ArangoCollection 58, "_jobs" (type document, status loaded)], 
  [ArangoCollection 21, "_modules" (type document, status loaded)], 
  [ArangoCollection 56, "_queues" (type document, status loaded)], 
  [ArangoCollection 23, "_routing" (type document, status corrupted)], 
  [ArangoCollection 44, "_statistics" (type document, status loaded)], 
  [ArangoCollection 49, "_statistics15" (type document, status loaded)], 
  [ArangoCollection 38, "_statisticsRaw" (type document, status loaded)], 
  [ArangoCollection 6, "_users" (type document, status loaded)] 
]
_routing is corrupted.

When I try to delete /var/lib/arangodb3 and restart arango to have everything recreated, same collection _routing is again corrupted.

**Comment by roman1720** [comment]
After dpkg purge and new install it was again corrupted. I tried also older versions with same result. Then I found out that there is some arangod process hanging which was not killed during installation. After killing it, purge and install db is ok without corruption.

**Comment by jsteemann** [comment]
We have to fix that `apt-get purge` (or `dpkg purge`) does not seem to stop the arangodb3 service.

**Comment by jsteemann** [comment]
This has been fixed in 3.2.6, which is available for download now.

**Comment by roman1720** [comment]
Thanks!
