### ISSUE TITLE
Intel microcode issues

### ISSUE THREAD

**Issue by khamin** [arangodb/arangodb#3461]
Hello,

just for information, recently I investigated unpredictable cluster behavior.
Seems it was related to problem described [here](https://lists.debian.org/debian-devel/2017/06/msg00308.html).

I think it would be nice to implement CPU/microcode checks at startup and log warn about it.
`cat /proc/cpuinfo` is the best place to get related info.
Also, I would recommend to check your build stack and prevent any possibility to distribute broken binaries.

**Comment by dothebart** [comment]
Hi, thanks for letting us know this - highly appreciated.
We revalidated our build and test environments, and they're not affected. 

However, reading through:
https://ark.intel.com/products/codename/37572/Skylake https://ark.intel.com/products/codename/82879/Kaby-Lake
I don't see how an application should implement blacklists and detection for broken processors by parsing `/proc/cpuinfo`.
Imho thats something the operating system should provide (if).

Thus I will close this as `won't fix` for arangodb.
