### ISSUE TITLE
Please add pax header

### ISSUE THREAD

**Issue by wenerme** [arangodb/arangodb#3463]
Please add pax header, https://github.com/wekan/wekan/issues/1303

**Comment by dothebart** [comment]
Hi, can you please provide more detail what has to be done here? Or maybe even sugest a pullrequest?

**Comment by wenerme** [comment]
Please check this commit https://github.com/wenerme/dockerfiles/commit/5b45d7848db6a4e604363e2284e33516011716d5 show's how to do.

Because node will do jit, mmap need prot_exec, when gresecurity enabled, prot_exec is not allowed.

Will show this error

```bash
arangod: error while loading shared libraries: cannot make segment writable for relocation: Permission denied
```

**Comment by dothebart** [comment]
So basically 

    paxctl -mc `which arangod`

does whats required for the binary? Will it survive `strip` ?

**Comment by wenerme** [comment]
I think it's ok with `strip`, check [this](https://en.wikipedia.org/wiki/PaX#Binary_markings), it only change the ELF header.

**Comment by dothebart** [comment]
@wenerme do you know of an existing cmake plugin handling that? can you search for it? Elseways I guess I won't find the time to fix this any time soon.

**Comment by dothebart** [comment]
We discussed this again internally, and decided not to integrate this now. 
As this disables security measures we would need to first investigate what its all about. 

Since there was no feedback in a while, I'm closing this now.
