### ISSUE TITLE
Document save() method can't define encoding!

### ISSUE THREAD

**Issue by wankaiss** [arangodb/arangodb#3466]
Hi,guys:
  i got this problem,Document.save() broken due to json.dumps in _save not able to take encoding parameters.How can i define a encoding for json.dumps()?

**Comment by jsteemann** [comment]
Is this related to a Python driver? Which one?

**Comment by wankaiss** [comment]
@jsteemann It is below.
 
<img width="909" alt="qq20171019-222623 2x" src="https://user-images.githubusercontent.com/13580140/31775927-9c341c2a-b4af-11e7-91d2-65eb3ae9f00d.png">

**Comment by dothebart** [comment]
Hi, 
JSON is always utf-8 by definition. If you need charset conversion, you need to do that in advance in python. 
Python 3 should offer tools to handle this properly
