### ISSUE TITLE
AQL: Functions to replace values in array

### ISSUE THREAD

**Issue by Simran-B** [arangodb/arangodb#3468]
rhsman via community slack:

> trying to update a number of documents with a specific value that is located in a list [...]
> I need to swap the value that matches x  with y [...]
> I want to replace a specific element in the array

### Current solutions

- Replace first occurrence only

  ```
  LET arr = {arrayfield: [1,2,"X","Z",3,"B"]}
  LET pos = POSITION(arr.arrayfield, 'X', true)
  LET newArr = pos == -1
    ? arr
    : APPEND(PUSH(SLICE(arr.arrayfield, 0, pos), 'Y'), SLICE(arr.arrayfield, pos+1))
  RETURN newArr
  ```

- Replace all occurrences

      LET newArr = (FOR elem IN arr.arrayfield RETURN elem == 'X' ? 'Y' : elem)

- Replace all occurrences of multiple values (dirty hack)

  ```
  FOR doc IN [{arrayfield: [1,2,3,'X','foo',5]},{arrayfield: [6,7,8]},{arrayfield: ['X','X',2]}]
      FILTER 'X' in doc.arrayfield
      RETURN JSON_PARSE(SUBSTITUTE(doc.arrayfield, ['X', 2], ['Y', '"don\'t forget quotes if the original element is not a string"']))
  ```

- Replace all occurrences of multiple values (less of a hack and type safe)

  ```
  LET before = ['X', 2, "2"]
  LET after = ['Y', 'integer', 'string']
  FOR doc IN [{arrayfield: [1,2,3,'X','foo',5]},{arrayfield: [6,7,8, "2", "2"]},{arrayfield: ['X','X',2,"2"]}]
      LET newArr = (
          FOR a IN doc.arrayfield
              RETURN FIRST(
              FOR i IN 0..LENGTH(before)-1
                  FILTER a == before[i]
                  LIMIT 1
                  RETURN after[i]
              ) OR a
      )
      RETURN newArr
  ```

### Feature suggestion

- `REPLACE_VALUE(anyArray, value, newValue, limit)`
  limit being optional
- `REPLACE_VALUES(anyArray, values, newValues)`
  all 3 being arrays, e.g. REPLACE_VALUES( [1,2,3], [3,1], [5,4] ) --> [4,2,5]
- `REPLACE_NTH(anyArray, pos, newValue)`
  replace value at specific index with another value

Not sure if the last one is needed. It would be convenient if combined with `POSITION(..., ..., true) // return index` I guess, but we may as well think about implementing a **SPLICE()** function, which would allow to remove N elements starting at pos P and insert array A of new values. REPLACE_NTH() would be a special case of a SPLICE operation, `SPLICE( anyArr, pos, 1, [newValue] )`.

**Also see #1639 and #1640 !**

In my example, `REPLACE_VALUES( [1,2,3], [3,1], [5,4] ) --> [4,2,5]`, the first array is the input (haystack). The second contains the needles. The third the replacement values. The first element of the needles is searched in the haystack and replaced by the first element of the replacement value array and so on. So, [1,2,3] is scanned for 3s, and they are replaced by 5s. Then it is scanned for 1s, which are substituted by 4s: [1=>4, 2, 3=>5]

Another example: `REPLACE_VALUES( ["yellow", "orange", "red" ], ["red", "yellow"], ["blue", "green"] ) --> ["green", "orange", "blue"]`

### Edge cases:

- what if needles occur multiple times, e.g. ["red", "red"] ? The second "red" should probably be ignored
- what if there are more needles than replacement values? Should the needle values be removed from the input, replaced by null, or simply be ignored?
- what if there are more replacement values than needles? they should probably be ignored.

Another way would be to provide pairs, `[ ["replaceMe","withThis"], ["X", "Y"], ... ]`. There are edge cases here as well however. The originally proposed syntax (separate arguments for needles and replacement values) would be more in line with the string function SUBSTITUTE().

**Comment by dsonet** [comment]
When can implement this feature? Would love to see it soon.
Thank you.

**Comment by aku** [comment]
Are there any plans to support array values manipulations? Currently, we have to add data post-processing or use complicated queries based on range and array filter operators.

**Comment by dothebart** [comment]
Hi, yes, we're currently implementing something similar:
https://github.com/arangodb/docs/compare/feature/add-array-replace-nth-function?expand=1

which will enable to replace one item. 
It will be part of Arangodb 3.7

**Comment by dothebart** [comment]
ArangoDB 3.7 has been released and is available for download. 

https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/
