### ISSUE TITLE
Conflict errors (1200) should state which document caused the conflict

### ISSUE THREAD

**Issue by ThomasWeiss** [arangodb/arangodb#3475]
Even though we could try/catch each and every write to detect which one causes a conflict, it would be convenient if conflict errors traced which document caused the conflict (not to use it at runtime to decide what to do - in our case we try/catch and retry the entire transaction - but rather for diagnostics purposes).

**Comment by danielhlarkin** [comment]
Fixed by #3624, will be released in 3.3.

**Comment by sleto-it** [comment]
Hi,

Thanks again for opening this ticket. Version 3.3.0 has been released

I am now closing this ticket. Please feel free to comment if the problem persists

Many thanks,
