### ISSUE TITLE
Question regarding index utilization in graph traversal

### ISSUE THREAD

**Issue by markk12** [arangodb/arangodb#3477]
i d like to try arangodb . it is my first graph database. I m a curiosity about query language:
arangodb makes a index call for every vertex subquery and edge subquery present in the query? Pratically arangodb make many index calls for every query right?

**Comment by dothebart** [comment]
Yes, the indices are frequently used by the graph engine. Not all queries will be able to be done via indices, you can use the explain button in the webinterface to find out.

**Comment by dothebart** [comment]
Closing this question as answered. If any more questions arise, don't hesitate to ask.
