### ISSUE TITLE
traversal failed when data is huge

### ISSUE THREAD

**Issue by weickdev** [arangodb/arangodb#3484]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [x] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [ ] mmfiles
- [x] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [x] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

At first I run traversal on web console, it works well. But if the data is huge, the traversal very slow!!! At the same time, the cpu, IO and RAM seem idle. If I use the java api to traversal, it fails and throws this error:
```
Exception in thread "main" com.arangodb.ArangoDBException: Response: 500, Error: 500 - Invalid string length
```

By the way, some times, the COORDINATOR crash during the process!

**Comment by weickdev** [comment]
Hi @maxkernbach , What does `3 Graph` label means? Is there any solution?

**Comment by maxkernbach** [comment]
Hello, i just labeled this issue according to its topic as you mentioned using traversals. Can you provide the traversal you were using?

**Comment by weickdev** [comment]
Hi, @maxkernbach 
Below is my traversal aql:
```
with Person,Company
for v,e,p in 1..10
any 'Company/020DD2C137D654DE7EF284AB5B30A87D' //inbound outbound
officer
options {bfs:true,uniqueVertices:'path'}
filter v._id == 'Person/57D3375D657149D5728E6BBC24FA5EF3'
return p
```
If the maxdepth is less than 5, it works well.

**Comment by graetzer** [comment]
Just to follow up here, the traversal can naturally get pretty slow if you have lot's of data. What is it you are trying to achieve? 
Perhaps you could add some additional filters?

**Comment by mrbatista** [comment]
Same problem when use `_api/traversal`. If use graph web interface the same traversal return 1086 nodes end 6017 edges. I'm trying to reproduce the problem with random data without any results.

**Comment by mrbatista** [comment]
I have the same configuration of @weickdev expect for storage engine. I use mmfiles. My problem is related to speficic data, but I can not share it because they are sensitive data.

**Comment by graetzer** [comment]
What problem are describing exactly? Just general slowness ?

The query he posted here had paths of up to length *10*, this means the size of the response can grow exponentionally depending on how much data you have.

**Comment by weickdev** [comment]
I limit the max depth to 3, now it works well in most cases.
