### ISSUE TITLE
Async replication between different versions (3.1 and 3.2) to achieve version upgrade without service interruption

### ISSUE THREAD

**Issue by soualid** [arangodb/arangodb#3494]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.1
- [x] 3.2

Mode:
- [x] Single-Server

Storage-Engine:
- [x] mmfiles (on 3.1)
- [x] rocksdb (on 3.2)

Hello, we are migrating a production application from 3.1 to 3.2 arangodb and we are wondering if it is possible to setup an asynchronous replication between our 3.1 and 3.2 ? Actually the sync starts but seems stalled at `still synchronizing... last received status: 2017-10-23T14:51:52Z: fetching master state`, is synchronization between db using different versions possible ? If so, we could use it to achieve a version upgrade without service interruption.

**Comment by maxkernbach** [comment]
Hello, currently replication is only supported between two ArangoDB servers running the same ArangoDB version. This is mentioned in the following documentation:
https://docs.arangodb.com/3.2/Manual/Administration/Replication/Asynchronous/Limitations.html

**Comment by soualid** [comment]
Thanks !
