### ISSUE TITLE
Query: AQL: cannot instantiate CollectBlock with undetermined aggregation method, Please report this error to arangodb.com

### ISSUE THREAD

**Issue by iamacup** [arangodb/arangodb#3497]
Hi Guys

Below is part of a massive query, and because i have found a workaround i am not really investing much time in fixing this - but as the error message is fairly insistant on reporting it here - i am reporting it for you

I can not provide a data set for this. Feel free to close the issue without fix if you wish - as i say, i have a workaround.

The query below worked on Arango 3.1, but resulted in a fatal error in arango 3.2

The bad query part: (full query is here: https://pastebin.ca/3894975)

```
LET combinedData2 = 
(
    LET outputRanges = 
    (
        LET allRanges = 
        (
            LET arrayOfObj = [payslipAnalysis, incompleteDataAnalysis, IncompleteOnUsersNoPayslipAnalysis, sumData2] 
           
            FOR items IN arrayOfObj
              FOR item IN items
                COLLECT label = item.label, key = item.key
                RETURN {label: label, key: key}
        )
        
        FOR range IN allRanges
            SORT range.key ASC
              RETURN range.label
    )

    RETURN outputRanges
)
```

Error:
```
Query: AQL: cannot instantiate CollectBlock with undetermined aggregation method (exception location: /var/lib/otherjenkins/workspace/RELEASE__BuildPackages/arangod/Aql/ExecutionEngine.cpp:143). Please report this error to arangodb.com (while executing) (exception location: /var/lib/otherjenkins/workspace/RELEASE__BuildPackages/arangod/RestHandler/RestCursorHandler.cpp:130). Please report this error to arangodb.com
```

The error is with this line:

` COLLECT label = item.label, key = item.key`

which if add `OPTIONS { method: "sorted" }` to the end to make:

` COLLECT label = item.label, key = item.key OPTIONS { method: "sorted" }`

Fixes the problem and stops the error.

If i try to explain the broken query - i get this:

```Explain: cannot stringify unknown aggregation method (exception location: /var/lib/otherjenkins/workspace/RELEASE__BuildPackages/arangod/Aql/CollectOptions.cpp:82). Please report this error to arangodb.com (while finalizing)```

------------------------------------------------------

## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [*] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [*] Single-Server

Storage-Engine:
- [*] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [*] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[*] I'm using graph features

I'm issuing AQL via:
- [*] web interface with this browser:     running on this OS: Mac OSX - Firefox
- [ ] arangosh
- [*] this Driver: PHP Official

**Comment by jsteemann** [comment]
Looks like a duplicate of https://github.com/arangodb/arangodb/issues/3395

**Comment by iamacup** [comment]
@jsteemann confirmed - updated to .2.5 and its working now.

**Comment by jsteemann** [comment]
Thanks for confirming!
