### ISSUE TITLE
several "filesystem full" errors in logs while there's a lot of disk space

### ISSUE THREAD

**Issue by dimitryvolkov** [arangodb/arangodb#3517]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [X ] 3.2.0

Mode:
- [X ] Single-Server

Storage-Engine:
- [X ] mmfiles

On this operating system:
- [X ] Linux 
  - [X] other: Ubuntu 16.04.2 LTS on AWS

I am constantly getting errors in my log file:
```
ERROR cannot create datafile '/vol/data/standalone/journals/logfile-890300.db': filesystem full
ERROR unable to create logfile '/vol/data/standalone/journals/logfile-890300.db': filesystem full
ERROR unable to create logfile: filesystem full
ERROR unable to create new WAL reserve logfile: filesystem full
WARNING catch error in historian: ArangoError: filesystem full\n    at Object.exports.historian (/usr/share/arangodb3/js/server/modules/@arangodb/statistics.js:474:8)\n$
ERROR cannot create datafile '/vol/data/standalone/journals/logfile-890301.db': filesystem full
ERROR unable to create logfile '/vol/data/standalone/journals/logfile-890301.db': filesystem full
ERROR unable to create logfile: filesystem full
ERROR unable to create new WAL reserve logfile: filesystem full
```

However, a quick check shows my filesystem (ext4) is no where near full, on any volume.
The only way that seems to temporarily resolve this issue is a restart to the server, it then proceeds to work without error for a while until the errors reappear.

I have some other issues with ArangoDB which I'll open a separate issue for but I was suspecting it might  be related to this issue.

**Comment by jsteemann** [comment]
A potential fix for this was merged into the devel branch today.
I say "potential" because so far we have not seen these error messages showing up. However, the code in the respective location seems to have checked for a wrong error code, so it may have logged that the filesystem was full even if the actual error indeed was something different.
Overall, it's unclear yet whether the "fix" will actually fix it. 

If you are happy to compile ArangoDB from source and try out yourself, then any feedback on the fix status is more than welcome.

**Comment by sleto-it** [comment]
Hi @dimitryvolkov ,

ArangoDB v. 3.3-beta1 is out, and can be downloaded from this address: https://www.arangodb.com/download-technical-preview/ (so you can use directly the binary to test the potential fix)

Please let us know if you still see this problem,

Many thanks,

**Comment by sleto-it** [comment]
Hi @dimitryvolkov,

We have not heard back from you, so I assume you haven't had a chance to test 3.3. No other users have reported the same issue. Considering also that a potential fix has been pushed, I think it is safe to close this ticket now

Please feel to comment if you will experience similar issues in the future, and we will re-open this ticket

Thanks again for reporting this,
