### ISSUE TITLE
_api/cluster/endpoints does not work, returns 404 Not Found "unknown path '/_api/cluster/endpionts'"

### ISSUE THREAD

**Issue by tmd313** [arangodb/arangodb#3535]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [X] 3.2
- [ ] self-compiled devel branch

Mode:
- [X] Cluster
- [ ] Single-Server

Storage-Engine:
- [X] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [X] Linux 
  - [ ] Debian .deb
  - [X] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

Used curl to run the command. Expect to get list of coordinator endpoints:

```
$ curl --dump -  http://cpc4s1-backoffice1:8529/_api/cluster/endpionts
HTTP/1.1 404 Not Found
X-Content-Type-Options: nosniff
Server: ArangoDB
Connection: Keep-Alive
Content-Type: application/json; charset=utf-8
Content-Length: 96

{"error":true,"code":404,"errorNum":404,"errorMessage":"unknown path '/_api/cluster/endpionts'"}
```

Whereas _admin/cluster/health comes back with a nice big json of the status of all nodes in the cluster.

```
$ curl --dump -   http://cpc4s1-backoffice1:8529/_admin/cluster/health
HTTP/1.1 200 OK
X-Content-Type-Options: nosniff
Server: ArangoDB
Connection: Keep-Alive
Content-Type: application/json; charset=utf-8
Content-Length: 1803

{"Health":{"PRMR-7a96459f-fd6a-4cca-9b0d-b6b60bb10aa7":{"SyncStatus":"SERVING","Timestamp":"2017-10-26T08:32:12Z","Status":"GOOD","Endpoint":"tcp://10.184.132.113:8530","ShortName":"DBServer0002","Role":"DBServer","CanBeDeleted":false},"CRDN-ad7b9295-e66a-44db-9d8d-091bc927ec49":{"SyncStatus":"SERVING","Timestamp":"2017-10-25T23:00:01Z","Status":"GOOD","Endpoint":"tcp://10.184.132.108:8529","ShortName":"Coordinator0001","Role":"Coordinator","CanBeDeleted":false},"PRMR-9fc3dade-98f9-4ef0-9677-b25b9c73489e":{"SyncStatus":"SERVING","Timestamp":"2017-10-26T19:52:01Z","Status":"GOOD","Endpoint":"tcp://10.184.132.112:8530","ShortName":"DBServer0001","Role":"DBServer","CanBeDeleted":false},"CRDN-6798207f-ab65-40e4-9230-199bc938ac1a":{"SyncStatus":"SERVING","Timestamp":"2017-10-26T19:52:38Z","Status":"GOOD","Endpoint":"tcp://10.184.146.49:8529","ShortName":"Coordinator0003","Role":"Coordinator","CanBeDeleted":false},"PRMR-0105009d-4d09-4895-90f0-3a81e8d08eb8":{"SyncStatus":"SERVING","Timestamp":"2017-10-26T19:20:50Z","Status":"GOOD","Endpoint":"tcp://10.184.132.114:8530","ShortName":"DBServer0003","Role":"DBServer","CanBeDeleted":false},"CRDN-bd824715-7bc6-4f23-844a-9d853aa53b8e":{"SyncStatus":"SERVING","Timestamp":"2017-10-26T17:41:41Z","Status":"GOOD","Endpoint":"tcp://10.184.132.109:8529","ShortName":"Coordinator0002","Role":"Coordinator","CanBeDeleted":false},"6478c638-15bd-4b42-ad2e-c473cdb906c7":{"Endpoint":"tcp://10.184.132.183:8531","Role":"Agent","CanBeDeleted":false},"ade3406f-3257-4733-a056-462671243ab0":{"Endpoint":"tcp://10.184.132.184:8531","Role":"Agent","CanBeDeleted":false},"bf89469b-409a-4dae-b405-44fd5ce13a19":{"Endpoint":"tcp://10.184.132.182:8531","Role":"Agent","CanBeDeleted":false}},"ClusterId":"ce03316a-05f5-4416-9a47-919c6bbdfd0d","error":false,"code":200}
```

**Comment by Simran-B** [comment]
Looks like a simple typo, `endpionts` instead of `endpoints`

**Comment by tmd313** [comment]
So sorry. You’re correct:

$ curl --dump -  http://cpc4s1-backoffice1:8529/_api/cluster/endpoints
HTTP/1.1 200 OK
X-Content-Type-Options: nosniff
Server: ArangoDB
Connection: Keep-Alive
Content-Type: application/json; charset=utf-8
Content-Length: 162

{"endpoints":[{"endpoint":"tcp://10.184.132.109:8529"},{"endpoint":"tcp://10.184.132.108:8529"},{"endpoint":"tcp://10.184.146.49:8529"}],"error":false,"code":200}

Thanks!

Tim Dillon

ARRIS
900 Chelmsford Street
Lowell, MA 01851-8100
978-614-3145

**Comment by tmd313** [comment]
My typo. So sorry. endpionts instead of endpoints.,
