### ISSUE TITLE
CLUSTER query performance insanely slow, compared to a single instance ( no load on both )

### ISSUE THREAD

**Issue by ibrahim-bouncoula** [arangodb/arangodb#3544]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ x] 3.2
- [ ] self-compiled devel branch

Mode:
- [ x] Cluster
- [ x] Single-Server

Storage-Engine:
- [ ] mmfiles
- [ x] rocksdb

On this operating system:
- [ ] DCOS on
  - [ x] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ x] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ x] I'm using graph features

I'm issuing AQL via:
- [ x] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ x] this Driver: arangojs

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:
FOR o in order FOR b in basket FOR c IN customer SORT o.createdAt DESC 
FILTER o._from == c._id and o._to == b._id
and b.storeId == '1'
LIMIT 0,25
RETURN {basket : b, order : o, customer : c}

If i run the above query on a single-server, it returns in 11ms, if i run it on a cluster of 3 servers (agency, coordinator, primary on each ) with sharding of 9 & replication of 3. it never returns less than 700ms to 1.4 s. So the performance on a single server is almost 100 times better than a cluster.

The cluster performance is insanely slow, RAM is available, no load while doing the comparison, both are dockers, cluster is in the same AZ in AWS. 

Is Sharding really that bad when it comes to performance ? or is definitely something wrong with my cluster ?

**Comment by dimitryvolkov** [comment]
How much data is in your collection to begin with?
I've had cases where some optimizations were not correctly applied to my query, resulting in some large data transfers between agents in a cluster from one of my collections, ultimately resulting in a slow query time

**Comment by ibrahim-bouncoula** [comment]
@dimitryvolkov thank you for the reply, my data is not yet large, i have an edge "order" ~ 650 edges, and same for basket and about 4000 in "customer"
I am unable to figure out is it because the data is small ? and how does it deffer from data being big ?

**Comment by ibrahim-bouncoula** [comment]
Hello Everyone, 
I am publishing my cluster commands that I run on each of the 3 servers for your reference. 3 agencies, 3 primaries, 3 coordinators. I would really appreciate any feedback, we want to know if we have done anything wrong here or why is the performance so poor. We were really happy with a cluster high available setup, and now we had to downgrade to a single instance, even though our data is not huge (so far), but we just wanted a Highly available setup.

docker run --memory=3g -d --name=agency1 -v /opt/docker/arangodb/rocksdb/agency1:/var/lib/arangodb3/rocksdb -v /var/log/arangodb3:/var/log/arangodb3/ -e ARANGO_NO_AUTH=1 -p 0.0.0.0:5001:5001 arangodb/arangodb:3.2.3 arangod --database.directory /var/lib/arangodb3/rocksdb --server.endpoint tcp://0.0.0.0:5001 --agency.my-address=tcp://10.0.4.200:5001 --cluster.my-local-info agency1 --server.authentication false --agency.activate true --agency.size 3 --agency.supervision true --server.storage-engine rocksdb --query.cache-mode on --server.threads 4 -log.level startup=warning --log.level queries=warning --log.level requests=warning --log.level performance=warning --log.output startup=file:///var/log/arangodb3/startup.log --log.output queries=file:///var/log/arangodb3/queries.log --log.output requests=file:///var/log/arangodb3/requests.log --log.output performance=file:///var/log/arangodb3/performance.log

docker run --memory=3g -d --name=agency2 -v /opt/docker/arangodb/rocksdb/agency2:/var/lib/arangodb3/rocksdb -v /var/log/arangodb3:/var/log/arangodb3/ -e ARANGO_NO_AUTH=1 -p 0.0.0.0:5001:5001 arangodb/arangodb:3.2.3 arangod --database.directory /var/lib/arangodb3/rocksdb  --server.endpoint tcp://0.0.0.0:5001 --agency.my-address=tcp://10.0.3.78:5001 --cluster.my-local-info agency2 --server.authentication false --agency.activate true --agency.size 3 --agency.supervision true --server.storage-engine rocksdb --query.cache-mode on --server.threads 4 -log.level startup=warning --log.level queries=warning --log.level requests=warning --log.level performance=warning --log.output startup=file:///var/log/arangodb3/startup.log --log.output queries=file:///var/log/arangodb3/queries.log --log.output requests=file:///var/log/arangodb3/requests.log --log.output performance=file:///var/log/arangodb3/performance.log


docker run --memory=3g -d --name=agency3 -v /opt/docker/arangodb/rocksdb/agency3:/var/lib/arangodb3/rocksdb -v /var/log/arangodb3:/var/log/arangodb3/ -e ARANGO_NO_AUTH=1 -p 0.0.0.0:5001:5001 arangodb/arangodb:3.2.3 arangod --database.directory /var/lib/arangodb3/rocksdb --server.endpoint tcp://0.0.0.0:5001 --agency.my-address=tcp://10.0.5.208:5001  --cluster.my-local-info agency3 --server.authentication false --agency.activate true --agency.size 3 --agency.endpoint tcp://10.0.3.78:5001 --agency.endpoint tcp://10.0.5.208:5001 --agency.endpoint tcp://10.0.4.200:5001 --agency.supervision true --server.storage-engine rocksdb --query.cache-mode on --server.threads 4 -log.level startup=warning --log.level queries=warning --log.level requests=warning --log.level performance=warning --log.output startup=file:///var/log/arangodb3/startup.log --log.output queries=file:///var/log/arangodb3/queries.log --log.output requests=file:///var/log/arangodb3/requests.log --log.output performance=file:///var/log/arangodb3/performance.log



docker run --memory=7g -d --name=primary1 -v /opt/docker/arangodb/rocksdb/primary1:/var/lib/arangodb3/rocksdb -v /var/log/arangodb3:/var/log/arangodb3/ -e ARANGO_NO_AUTH=1 -p 0.0.0.0:8529:8529 arangodb/arangodb:3.2.3 arangod --database.directory /var/lib/arangodb3/rocksdb --server.authentication=false --server.endpoint tcp://0.0.0.0:8529 --cluster.my-address tcp://10.0.4.200:8529 --cluster.my-local-info primary1 --cluster.my-role PRIMARY --cluster.agency-endpoint tcp://10.0.4.200:5001 --cluster.agency-endpoint tcp://10.0.3.78:5001 --cluster.agency-endpoint tcp://10.0.5.208:5001 --server.storage-engine rocksdb --query.cache-mode on --server.threads 4  -log.level startup=warning --log.level queries=warning --log.level requests=warning --log.level performance=warning --log.output startup=file:///var/log/arangodb3/primary/startup.log --log.output queries=file:///var/log/arangodb3/primary/queries.log --log.output requests=file:///var/log/arangodb3/primary/requests.log --log.output performance=file:///var/log/arangodb3/primary/performance.log


docker run --memory=7g -d --name=primary2 -v /opt/docker/arangodb/rocksdb/primary2:/var/lib/arangodb3/rocksdb -v /var/log/arangodb3:/var/log/arangodb3/ -e ARANGO_NO_AUTH=1 -p 0.0.0.0:8529:8529 arangodb/arangodb:3.2.3 arangod --database.directory /var/lib/arangodb3/rocksdb --server.authentication=false --server.endpoint tcp://0.0.0.0:8529 --cluster.my-address tcp://10.0.3.78:8529 --cluster.my-local-info primary2 --cluster.my-role PRIMARY --cluster.agency-endpoint tcp://10.0.4.200:5001 --cluster.agency-endpoint tcp://10.0.3.78:5001 --cluster.agency-endpoint tcp://10.0.5.208:5001 --server.storage-engine rocksdb --query.cache-mode on --server.threads 4 -log.level startup=warning --log.level queries=warning --log.level requests=warning --log.level performance=warning --log.output startup=file:///var/log/arangodb3/primary/startup.log --log.output queries=file:///var/log/arangodb3/primary/queries.log --log.output requests=file:///var/log/arangodb3/primary/requests.log --log.output performance=file:///var/log/arangodb3/primary/performance.log


docker run --memory=7g -d --name=primary3 -v /opt/docker/arangodb/rocksdb/primary3:/var/lib/arangodb3/rocksdb -v /var/log/arangodb3:/var/log/arangodb3/ -e ARANGO_NO_AUTH=1 -p 0.0.0.0:8529:8529 arangodb/arangodb:3.2.3 arangod --database.directory /var/lib/arangodb3/rocksdb --server.authentication=false --server.endpoint tcp://0.0.0.0:8529 --cluster.my-address tcp://10.0.5.208:8529 --cluster.my-local-info primary3 --cluster.my-role PRIMARY --cluster.agency-endpoint tcp://10.0.4.200:5001 --cluster.agency-endpoint tcp://10.0.3.78:5001 --cluster.agency-endpoint tcp://10.0.5.208:5001 --server.storage-engine rocksdb --query.cache-mode on --server.threads 4 -log.level startup=warning --log.level queries=warning --log.level requests=warning --log.level performance=warning --log.output startup=file:///var/log/arangodb3/primary/startup.log --log.output queries=file:///var/log/arangodb3/primary/queries.log --log.output requests=file:///var/log/arangodb3/primary/requests.log --log.output performance=file:///var/log/arangodb3/primary/performance.log



docker run --memory=8g -d --name=coordinator1 -v /opt/docker/arangodb/rocksdb/coordinator1:/var/lib/arangodb3/rocksdb -v /var/log/arangodb3:/var/log/arangodb3/ -e ARANGO_NO_AUTH=1 -p 9530:9530  arangodb/arangodb:3.2.3  arangod --database.directory /var/lib/arangodb3/rocksdb --server.authentication=false --server.endpoint tcp://0.0.0.0:9530 --cluster.my-address tcp://10.0.4.200:9530 --cluster.my-local-info coordinator1 --cluster.my-role COORDINATOR --cluster.agency-endpoint tcp://10.0.4.200:5001 --cluster.agency-endpoint tcp://10.0.3.78:5001 --cluster.agency-endpoint tcp://10.0.5.208:5001 --server.storage-engine rocksdb --query.cache-mode on --server.threads 8 -log.level startup=warning --log.level queries=warning --log.level requests=warning --log.level performance=warning --log.output startup=file:///var/log/arangodb3/coordinator/startup.log --log.output queries=file:///var/log/arangodb3/coordinator/queries.log --log.output requests=file:///var/log/arangodb3/coordinator/requests.log --log.output performance=file:///var/log/arangodb3/coordinator/performance.log


docker run --memory=8g -d --name=coordinator2 -v /opt/docker/arangodb/rocksdb/coordinator2:/var/lib/arangodb3/rocksdb -v /var/log/arangodb3:/var/log/arangodb3/ -e ARANGO_NO_AUTH=1 -p 9530:9530 arangodb/arangodb:3.2.3  arangod --database.directory /var/lib/arangodb3/rocksdb --server.authentication=false --server.endpoint tcp://0.0.0.0:9530 --cluster.my-address tcp://10.0.3.78:9530 --cluster.my-local-info coordinator2 --cluster.my-role COORDINATOR --cluster.agency-endpoint tcp://10.0.4.200:5001 --cluster.agency-endpoint tcp://10.0.3.78:5001 --cluster.agency-endpoint tcp://10.0.5.208:5001 --server.storage-engine rocksdb --query.cache-mode on --server.threads 8 -log.level startup=warning --log.level queries=warning --log.level requests=warning --log.level performance=warning --log.output startup=file:///var/log/arangodb3/coordinator/startup.log --log.output queries=file:///var/log/arangodb3/coordinator/queries.log --log.output requests=file:///var/log/arangodb3/coordinator/requests.log --log.output performance=file:///var/log/arangodb3/coordinator/performance.log


docker run --memory=8g -d --name=coordinator3 -v /opt/docker/arangodb/rocksdb/coordinator3:/var/lib/arangodb3/rocksdb -v /var/log/arangodb3:/var/log/arangodb3/ -e ARANGO_NO_AUTH=1 -p 9530:9530 arangodb/arangodb:3.2.3  arangod --database.directory /var/lib/arangodb3/rocksdb --server.authentication=false --server.endpoint tcp://0.0.0.0:9530 --cluster.my-address tcp://10.0.5.208:9530 --cluster.my-local-info coordinator3 --cluster.my-role COORDINATOR --cluster.agency-endpoint tcp://10.0.4.200:5001 --cluster.agency-endpoint tcp://10.0.3.78:5001 --cluster.agency-endpoint tcp://10.0.5.208:5001  --server.storage-engine rocksdb --query.cache-mode on --server.threads 8 -log.level startup=warning --log.level queries=warning --log.level requests=warning --log.level performance=warning --log.output startup=file:///var/log/arangodb3/coordinator/startup.log --log.output queries=file:///var/log/arangodb3/coordinator/queries.log --log.output requests=file:///var/log/arangodb3/coordinator/requests.log --log.output performance=file:///var/log/arangodb3/coordinator/performance.log

**Comment by dothebart** [comment]
Hi, 
When you run [explain](https://docs.arangodb.com/3.2/AQL/ExecutionAndPerformance/ExplainingQueries.html)on that query you will most probably see that its doing hops back and forth from the DB-Servers to the coordinatior. 

Thus it will have to transfer back and forth parts of the collections. 

You will have to find a way to use filters that are applicable directly to the shards to reduce the result set transfered back and forth on the cluster. In a worst case you will currently send your whole collections back and forth resulting in the bad performance you see.

**Comment by ibrahim-bouncoula** [comment]
@dothebart  thank you for explaining this, I am aware of it to a certain degree, the problem is that even if we are talking about a very simple query like:
for u in user filter u.email="xxxx@xxx.xxx" it performs 100x worse on a cluster. Even if email is indexed. So either there something we do not know in AQL or the cluster is not performing well for setup reasons ?

**Comment by dothebart** [comment]
Hi, 
Whats the size and the number of documents you get in that query? do you see in the explain whether the shards can use their indices?

One currently known issue is that LIMIT statements aren't pushed out to the shards and thus may only reduce the number of documents on the coordinator, which results in a huger number of documents being sent to the coordinator.

**Comment by tanerkrn** [comment]
Hello there, 
I have the same problem. In my situation, I am using version 3.4.2 and there are 1000 documents in a collection. When I try with a single machine it spends below 3 milliseconds. But when I try with multiple machines with a cluster that has 3 nodes; it spends above 10 milliseconds. I set up clusters with default configuration as the document said.

Example Query : 
`
FOR product IN products
FILTER product.id == 123
RETURN product
`
I need to solve this problem as soon as possible please help me if you have any information about it. Thank you very much.

**Comment by dothebart** [comment]
Hi, 
cluster means multiple machines communicating to fullfill your query, documents have to be sent from db-server->coordinator, so I wouldn't say that 10 milliseconds is slow here. 

In general, if your data fits into one machine, and you only want to use the cluster for HA and resilience, a single-server-failover scenario may be better for your purposes.

**Comment by tanerkrn** [comment]
Thanks for the swift reply, I have now simplified the example to be more understandable. In the real scenario, the difference is 10x for the query on  edges that has 1000 row. 

What can be the cause of performance loss? A missing parameter in the cluster configuration?

**Comment by dothebart** [comment]
Its not a loss in performance, its a difference. 
You can benchmark your scenario, as described in this blog post: https://www.arangodb.com/2017/10/performance-analysis-pyarango-usage-scenarios/
When using several coordinators, the cluster may outpace a single server instance. 
However, you need to be more carefull about how you lay out your indices, choose shard-keys etc.
You may like [explain to show you how the query is executed](https://docs.arangodb.com/3.4/Manual/Indexing/WorkingWithIndexes.html#revalidating-whether-an-index-is-used) and what you may need to alter to improve the performance.

**Comment by dothebart** [comment]
Hi, 
in order to find out what especially is going on with your query, a little more details would be required. 
The output of [`explain`](https://docs.arangodb.com/3.4/AQL/ExecutionAndPerformance/ExplainingQueries.html) would be important, plus [the poperties of the collections in question](https://docs.arangodb.com/3.4/Manual/DataModeling/Collections/CollectionMethods.html#properties).

In best case, the `SingleRemoteOperationNode` can be used to fetch a single document from a shard. However, this requires to filter by the shard-key - so either you need to specify `id` to be your shard key, or filter by `_key`. In this case the coordinator can directly talk to the shard that has the actual document. 
In the other case it needs to talk to all shards for the lookup. If then there is no index, this may take longer. 

In all circumstances, `explain` will give insights into the actual execution that will take place in your environment.

**Comment by NingLee** [comment]
I come across the same question, I tried to set shards to 1 and all data on the same server, but the query is still slow than single node.
