### ISSUE TITLE
Only One Shortest Path?

### ISSUE THREAD

**Issue by weickdev** [arangodb/arangodb#3545]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [x] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [ ] mmfiles
- [x] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [x] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

I want to get the shortest path between two vertexs, so I use the SHORTEST_PATH. But it seems to return only one shortest path? If there are many shortest path, how can I get them all?

**Comment by maxkernbach** [comment]
Hello, currently SHORTEST_PATH provides only one shortest path. It is possible to get all shortest paths with two queries though. At first you use SHORTEST_PATH to calculate the length of your shortest path by:
```
LET length = SUM(FOR v IN SHORTEST_PATH @start TO @target @@edges RETURN 1)
```
Next do a graph traversal with the calculated length filtering by your targetVertex. Length has to be a known value, not a variable:
```
FOR v,e,p IN @length OUTBOUND @start @@edges FILTER v._id == @target RETURN p
```

**Comment by weickdev** [comment]
@maxkernbach It's a good idea, thank you so much.

**Comment by dothebart** [comment]
@maxkernbach please add this to the documentation with the query patterns at https://github.com/arangodb/arangodb/tree/devel/Documentation/Books/AQL/Examples

**Comment by Simran-B** [comment]
@maxkernbach
Using SUM() seems unnecessary. Instead, you could count the number of array elements `LENGTH(...)`.

The `RETURN 1` hack shouldn't be necessary, I've even seen queries that performed slightly better if they used `RETURN v`.

@mchacki says `v._id` would be a bit slower than `p.vertices[-1]._id`, although I couldn't find a measurable difference so far.

**Comment by Simran-B** [comment]
Same question https://stackoverflow.com/questions/46979305/multiple-path-search-in-arangodb with a slightly modified answer by me. Should definately make its way into the docs.

**Comment by maxkernbach** [comment]
Multiple path search is now [documented](https://docs.arangodb.com/3.3/AQL/Examples/MultiplePaths.html) in the section AQL -> Usual Query Patterns.
