### ISSUE TITLE
server reading ENGINE config file fails on common standard newline character

### ISSUE THREAD

**Issue by grexe** [arangodb/arangodb#3549]
Using latest ArangoDB 3.2.5 on an Ubuntu 14.04 server, I get this error (upgrading from a 3.1.25 installation):

> FATAL {startup} content of 'ENGINE' file '/var/lib/arangodb3/ENGINE' and command-line/configuration option value do not match: 'mmfiles\n' != 'mmfiles'. please validate the command-line/configuration option value of '--server.storage-engine' or use a different database directory if the change is intentional

I'd expect the server to correctly interpret (and ignore) the trailing newline character, as this is even *automatically* inserted in most UNIX editors and actually even considered good practice (since some legacy shell interpreters required it).

**Comment by grexe** [comment]
the error was persistent, even vi did not help. I had to remove the file, then the config option was taken and everything worked.

**Comment by jsteemann** [comment]
vi has command `setnoeol`. If not set, it will automatically append a newline at the end.
But yes, it must be fixed because manually editing generated files seems to be common.

**Comment by jsteemann** [comment]
Thanks for letting us know. The above PRs should fix the issue. They will be incorporated into the next releases.

**Comment by grexe** [comment]
cool @jsteemann that was fast, and thanks for the vi `setnoeol` tip!
btw it's really appreciated and shows Arango is not evil;) that you support even free customers like this, kudos!

**Comment by sleto-it** [comment]
Hi @grexe,

Thanks again for opening this ticket. Version 3.2.7 has now been released and it includes a fix for this problem

Please could you upgrade? I am now closing this ticket. If the issue persists, please feel free to comment

Many thanks,

**Comment by grexe** [comment]
sure just upgrading now, even though 3.2.8 is already out but in my Ubuntu 14.04 container this one causes issues, see #3762
