### ISSUE TITLE
db._executeTransaction error log line number

### ISSUE THREAD

**Issue by kuselan84** [arangodb/arangodb#3554]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x ] 3.2

Mode:
- [ ] Cluster
- [ x] Single-Server

Storage-Engine:
- [ ] mmfiles
- [ x] rocksdb

On this operating system:
- [ ] Linux 
  - [ x] Debian .deb

### Foxx
Hi,

If there is an error within db._executeTransaction i can't see what line number causing it in arangod.log. Some of my transaction are long and contain lots of calculations. It'll be easy if i know which line number of script causing it. Ideally if there is a remote debug option, it'll be great.

Thanks,

**Comment by dothebart** [comment]
Hi, 
The easiest way to achieve that is to wrap your transaction into try/catch, and output the exception code then, and re-throw. 
You may want to add `console.log()` statements, add your user data that lead to the exception.

**Comment by maxkernbach** [comment]
Hi @kuselan84,

did the suggested approaches help you? Can we close this issue?
