### ISSUE TITLE
Document WITHIN_RECTANGLE not found

### ISSUE THREAD

**Issue by mrkvon** [arangodb/arangodb#3562]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [x] 3.1 (3.1.27)
- [ ] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [x] mmfiles
- [ ] rocksdb

On this operating system:
- [x] Linux 
  - [x] Debian .deb

### this is an AQL-related issue:
- [x] I'm using graph features (shouldn't matter)

I'm issuing AQL via:
- [x] web interface with this browser:  chromium  running on this OS: arch linux
- [ ] arangosh
- [x] this Driver: arangojs

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

```
FOR u IN WITHIN_RECTANGLE(users, 20, -180, 89, 180) RETURN u
```

The issue can be reproduced using this dataset:
```json
{
  "username": "usr",
  "location": [
    47.328,
    152.475
  ]
}
```
in collection `users` with non-unique sparse `geo1` index on `location`

[gist](https://gist.github.com/mrkvon/059830d01eae026798fe84ef6f36627d)

### The issue:
Having the above dataset, the query
```
FOR u IN WITHIN_RECTANGLE(users, 20, -180, 89, 180) RETURN u
```
returns 0 documents.

The query
```
FOR u IN WITHIN_RECTANGLE(users, 0, -180, 89, 180) RETURN u
```
returns 1 document as expected.

In both cases 1 document should be returned, because `[47.328, 152.475]` is within provided boundaries in both cases.

**Comment by dothebart** [comment]
The WITHIN_RECTANGLE queries the original geoindex calculating the diagonal size of the 'rectangle'. 

The calculation breaks when the rectangle goes beyound  -130=>180 Longtitute.

The calculated geo acually query run by `WITHIN_RECTANGLE` is:

`RETURN WITHIN(users, 54.5, 0, 7681044.864735877 )`

which delivers the empty result. 

When one increases the diameter, 
`RETURN WITHIN(users, 54.5, 0, 8481044.864735877 )`
will again return the document.

Using https://www.movable-type.co.uk/scripts/latlong.html to calculate the distance between the rectangle center point to the coordinates of the document also returns `8401 km`, which means the geo index is working properly, but the rectangle to diameter calculation function `distanceMeters()` is wrong. 

We need to investigate further.

**Comment by dothebart** [comment]
@mrkvon but, generally speeking, if you're just interested on anything north of 20 degrees (as your query sugests) using geo-indices and `WITHIN_RECTANGLE` is probably not what you want to use in first place. 

For that usecase you should rather add a skiplist index on the longtitude, and qery it like 

`FILTER users.location[0] > 20` 

Its going to scale better, and work out of the box right now without any bugfixing.

**Comment by mrkvon** [comment]
Thank you, @dothebart , for the suggestion. I actually use the function to display points (users) on a map (i.e. `leaflet`). For that purpose `WITHIN_RECTANGLE` seems to be a perfect fit.
The above error happens when one displays a big portion of (or whole) Earth, so it's just an extreme of my use case.
Or do you think `FILTER` would be more resourceful in this case, too?

**Comment by dothebart** [comment]
yes, aside of the bug, one has to understand how WITHIN_RECTANGLE actually works. 
It calculates the bounding rectangle  (wrong) and then tries to evaluate the possible diameter. Using this diameter it queries the geo index for all objects within the range of the outermost distance. 
It will then filter each of those documents found, whether they fit into that area (using javascript). 
The usage of the javascript function will result in result streaming not being available, so all results have to be built up first. 

So, yes, if the size of your square increases, it may be much less resource intense to just use the `FILTER` statements instead of WITHIN_RECTANGLE - plus maybe additional filters so you don't overload the leaflet function with millions of points. 

Depending on the view you will also have to make sure you filter properly - namingly if you're around -180/+180 degrees.

**Comment by Simran-B** [comment]
@graetzer @hkernbach Is this solved in 3.4?

**Comment by graetzer** [comment]
3.4 translates this AQL function to using GEO_CONTAINS:

```
arangod> db._explain("FOR u IN WITHIN_RECTANGLE(users, 0, -180, 89, 180) RETURN u")
Query String:
 FOR u IN WITHIN_RECTANGLE(users, 0, -180, 89, 180) RETURN u

Execution plan:
 Id   NodeType        Est.   Comment
  1   SingletonNode      1   * ROOT
 11   IndexNode          0     - FOR u IN users   /* geo index scan */
  4   ReturnNode         0       - RETURN u

Indexes used:
 By   Type   Collection   Unique   Sparse   Selectivity   Fields    Ranges
 11   geo    users        false    true             n/a   [ `a` ]   GEO_CONTAINS({ "type" : "Polygon", "coordinates" : [ [ [ -180, 0 ], [ 180, 0 ], [ 180, 89 ], [ -180, 89 ], [ -180, 0 ] ] ] }, [ u.`a`[1], u.`a`[0] ])

Optimization rules applied:
 Id   RuleName
  1   replace-function-with-index
  2   inline-subqueries
  3   geo-index-optimizer
  4   remove-unnecessary-calculations-2
```

**Comment by mikestaub** [comment]
It's worth noting that as of 3.3.17, when I run the example described, I was not able to use the geo index on the collection with any WITHIN statement. In 3.4.x it appears to be fixed.

**Comment by MrPieces** [comment]
Hi @mikestaub ,

nice to read you :) The geo capabilities of ArangoDB have been completely overhauled and extended in v3.4. We integrated Googles S2 Geometrie library to enable full GeoJSON support; The new GeoJSON support includes all geo primitives like multi points, multipolygons and many geo functions like DISTANCE, CONTAINS, EQUALS and even INTERSECTS or IN POLYGON. 

The new geo index is also optimized for the RocksDB storage engine. Users who selected RocksDB as their storage engine should see much faster queries comparing 3.3 to 3.4.

Hope that was useful info!
