### ISSUE TITLE
filter doesn't work

### ISSUE THREAD

**Issue by weickdev** [arangodb/arangodb#3567]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [x] 3.0
- [ ] 3.1
- [ ] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [ ] mmfiles
- [x] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [x] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I run this AQL on web interface:
```
with Company,Person
for v,e,p in 1..5
any 'Company/1660AB0286574F40EA717E7EF9C79C85'
invest,tradable_share,officer
options {bfs:true,uniqueVertices:'path'}
filter CONTAINS(p.vertices[*]._id,"Company") && CONTAINS(p.edges[*]._from,"Company") && CONTAINS(p.edges[*]._to,"Company")
return p
```
I want to get all vertexes and their paths, with the vertex id is starting with Company. But when I run this AQL, the result still contains other vertex whose id is not string with Company. Is there anything wrong with my AQL?

**Comment by jsteemann** [comment]
AFAIK it will not work like this.
The `p.vertices[*]._id` will produce an array of all vertex ids in the path, e.g.
```
[ 
  "Company/1", 
  "Company/2", 
  "Foo/Bar" 
] 
```
Passing that array as first parameter to `CONTAINS` will turn that array into its string representation, which will be the string `"[\"Company/1\",\"Company/2\",\"Foo/Bar\"]"`. And the `CONTAINS` function call will then simply look for any occurence of the substring `Company"` inside this string. If it occurs anywhere in the string, the filter will pass. So if ANY vertex in the path contains "Company" somewhere in its id, then the entire path is returned.

**Comment by weickdev** [comment]
@jsteemann 
So do you have any advice to filter the each vertex's _id on the path?

**Comment by mchacki** [comment]
Hi,

right now we do not have a syntax to apply functions like `IS_SAME_COLLECTION` or `CONTAINS` on all vertices/edges on the path and optimize it.
We can for now only optimize `simple` operators.
So we need to use a small trick on your query and do string comparison with `<` and `>`
(Promissed we upgrade this in the future!)

AS the `_id` value is composed of `collectionname/_key` we need to assure that the `_id` of every vertex is `> "collectionname/"` and smaller `< collectionname0`.
NOTE: `0` is the next higher element compared to `/`
So this conditions will let everything through that have a prefix of `collectionname/`.

Putting this into your query it looks like this:

```
with Company,Person
for v,e,p in 1..5
any 'Company/1660AB0286574F40EA717E7EF9C79C85'
invest,tradable_share,officer
options {bfs:true,uniqueVertices:'path'}
FILTER p.vertices[*]._id ALL < 'Company0' AND p.vertices[*]._id ALL > 'Company/'
RETURN p
```

Which should fix your issue.
Nevertheless we plan to have a `ALL OF COLLECTION` (syntax not yet defined) operator on traversals as this is a very common use-case.

If you do not like the String comparision you could also add a boolean field to all companies like:
`company: true`
And than filter with:
`FILTER p.vertices[*].company ALL == true`
That should be slightly faster than String comparison, but cost more in terms of disk space.

Also note that we did a lot of performance improvements on Graphs in version 3.1 and 3.2 so i suggest to upgrade if performance is an issue for you.

**Comment by weickdev** [comment]
@mchacki Thanks for you advice, It works for me right now!
