### ISSUE TITLE
Translating documentation into other languages

### ISSUE THREAD

**Issue by DerrSaff** [arangodb/arangodb#3571]
Hello, everyone. I've been studying ArangoDB documentation for a while and I want to ask, if there are any plans to translate docs to other languages. I guess it could possibly attract more people to the project.
I can help with translation into Russian, since it's my native language.

**Comment by liuxiong888** [comment]
It's a cool suggestion.
As the title,I wish our company Qingtime  can donate and help to translate to Chinese.

**Comment by dothebart** [comment]
Hi, 
thanks for your kind offer. 
If, we probably should do this along the lines of how gitbook does this: https://toolchain.gitbook.com/languages.html - need to experiment with that. 

One part will require more work on our side - the HTTP API which we also publish in swagger format, which has their own way of doing it: 
https://github.com/OAI/OpenAPI-Specification/issues/274

Probably the HTTP API is not as interesting for the end users as the other 3 chapters. 

The third thing would be a question to the both of you - how do you feel about the automatically generated examples? Should they be translated too?

**Comment by DerrSaff** [comment]
Well, I guess, it would be nice to consider i18n as a new feature in future versions of the project, when you have enough time to implement it. Unfortunately, I can't help with developing this, because I'm quite a good translator, but not a good programmer.
As for automatically generated examples - I think, they should be translated too, but I'm not sure, how difficult it is to realize.
As soon as the multi-language option appears, I'll start translating docs into Russian.

**Comment by Simran-B** [comment]
Hey @DerrSaff,

thanks for your kind offer to translate our documentation. Our four current gitbooks contain a lot of content, and they are a moving target - we edit things here and there all the time, in at least one version of them, but sometimes all from 3.1 to devel as well. Considering the amount of content in the docs and its evolving nature, translating every little bit seems like a pretty huge project and so far you are the only one who offered a Russian translation. This said, we would like to ask you to start with the recently added [AQL tutorial](https://docs.arangodb.com/devel/AQL/Tutorial/) to limit the scope to one important group of pages that we assume are very useful to a lot of beginners, while not consisting of too much text to translate.

For now, you can put the files in an own repository. We have yet to come up with a concept for docs and learning material in other languages, where to put them and if/how we can host them. Adding translated books to the current system it not easily possible, especially without breaking existing URLs on the web. Adding 3rd party content to the main repository also brings up licensing questions.

If you need support to e.g. create a gitbook and put it in a github repository, let me know.

Best, Simran

**Comment by Simran-B** [comment]
An official translation of the entire docs to whatever language would be a huge undertaking, for which we don't really have the resources. Anyone can translate parts of the docs as desired and publish it in one or another way of course. If you want to share a blog post or something, let us know. You can post it in our slack community: https://slack.arangodb.com/
