### ISSUE TITLE
A strange error on running benchmark to test arangodb3-3.3.milestone2-1.x86_64.rpm

### ISSUE THREAD

**Issue by gloCalHelp** [arangodb/arangodb#3584]
## my environment running ArangoDB 
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [ ] self-compiled devel branch
- arangodb3-3.3.milestone2-1.x86_64.rpm

Mode:
- [ ] Cluster
- [Y] Single-Server

Storage-Engine:
- [Y] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [Y] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [Y ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:
Your github's benchmark testing data. using npm run to generate the dataset.
Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [ ] using the cluster?
- [ Y] _system database?

These are the steps to reproduce:
1) npm run data
2) node benchmark arangodb -a 1.2.3.4 -t all

...

The following problem occurs: [Screenshot?] 
"...
TypeError: Cannot read property 'length' of undefined
    at /root/Documents/NimbiLin/Programs/Databases/NoSQL/Install/nosql-tests/node_modules/arangojs/lib/cursor.js:50:33

..."

Instead I would be expecting: 

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

**Comment by gloCalHelp** [comment]
and I again run this command "arangod  /root/Documents/NimbiLin/Programs/Databases/NoSQL/Install/nosql-tests/data --server.threads 16 --scheduler.threads 8 --wal.sync-interval 1000  --config /etc/arangodb3/arangod.conf --javascript.v8-contexts 17Error while processing command-line options:
  unknown option '--scheduler.threads'
"
as the https://github.com/weinberger/nosql-tests 's Arango's start Parameters command, but the error says "unknown option '--scheduler.threads'"

**Comment by jsteemann** [comment]
`--scheduler.threads` has been obsoleted with ArangoDB release 3.0.
The nosql-tests repository above probably refers to an older version of ArangoDB.

**Comment by gloCalHelp** [comment]
Hi, Mr. Jsteemann

Good morning, thank you very much for your solve the 2nd issue.
Then how about the 1st issue? would you like to send a workable nosql-test script to 
my mail of jiaxinlin@live.com ? 
You are so great to write so many complex JS functions and it is not so easy for me to 
solve the null self.result:
+++++++++++++++++++++++++++++
var self = this;
    self._drain(function (err) {
      self._index = self._result.length;
+++++++++++++++++++++++++++++

**Comment by jsteemann** [comment]
Hi @gloCalHelp : it seems that the benchmark code in the weinberger/nosql-tests repository is not compatible with recent versions of ArangoDB. It seems to have been written for ArangoDB 2.7 and needs some major overhaul in order to work with more recent versions.
I am sorry but I do not have time to work on this in the near future.

**Comment by maxkernbach** [comment]
Hi @gloCalHelp,

a new [performance benchmark](https://github.com/weinberger/nosql-tests), that is compatible with recent versions has been released about two months ago.

**Comment by maxkernbach** [comment]
I am closing this issue as solved for now.
Please feel free to comment and reopen in case you have any problems running the latest benchmark.
