### ISSUE TITLE
A large number of deleted server restart

### ISSUE THREAD

**Issue by zhenruyan** [arangodb/arangodb#3585]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [x] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [ ] mmfiles
- [x] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [x] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[x] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [x] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click to ...
...

The following problem occurs: [Screenshot?] 
Instead I would be expecting: 

Server memory 64G

There are about seven hundred thousand data

perform

```
for doc in docdist
fitter doc.level <0
remove doc._key in docdist

```
Log without exception

server restart

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

**Comment by dothebart** [comment]
Hi, 
Do you observe memory consumption? or anything in dmesg?

**Comment by zhenruyan** [comment]
There is no error, no full memory  ,Suddenly the restart

**Comment by dothebart** [comment]
- How many documents will fit `fitter doc.level <0`, and whats their size?
- How many documents are in the collection in total?
- Do the documents contain large structures, or are they small - which size (kb)?

**Comment by zhenruyan** [comment]
1, removed 700000

2,A total of 800000 

3,small

The log no error

Memory is very smooth, not filled

**Comment by dothebart** [comment]
Hi, 
I've tried to reproduce this with 3.2.7 like that way:

```
db._create('test4')
for (i=0; i < 800000; i ++) db.test4.save({"a": i, "santoheu": "sanotehsnaotehusnatoheusnatoehu"})

db.test4.ensureIndex({type: "skiplist", fields: ["a"], unique: false})

db._explain(`
for doc in test4
filter doc.a < 700000
remove doc._key in test4
          `)

db._query(`
for doc in test4
filter doc.a < 700000
remove doc._key in test4
          `)

db.test4.count()
100000
```
one time with, and without the index, successfull. 

Can you give more details please? did you already upgrade to 3.2.7?

**Comment by zhenruyan** [comment]
All right, I'll try it.

**Comment by zhenruyan** [comment]
I don't seem to have found 3.2.7 branch

**Comment by dothebart** [comment]
Ok, 
I think we can close this then. 
Please always check for the latest bugfix-version available before opening bug reports.
 - Thanks for reporting.
