### ISSUE TITLE
ArangoDB instance can be shut down by any user with access to at least one database

### ISSUE THREAD

**Issue by fdsg-tk** [arangodb/arangodb#3588]
my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [X] 3.1
- [X] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [X] Single-Server

Storage-Engine:
- [X] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [X] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

The following problem occurs: 
The ArangoDB Instance can be shutdown by using the /_admin/shutdown REST API command.
This command can be executed successfully by ANY user, which only needs to have access on at least one database on the ArangoDB instance (readonly access in ArangoDB 3.2 is enough).

Reproduce this error by:
1. Create a new database called "test"
2. Create a new user called "test" and set password to "test" too.
3. Grant user "test" access privileges for database "test"
4. execute on a Linux console:
curl -X "DELETE" -utest:test https://<your_host>:8529/_db/test/_admin/shutdown
5. arangodb instance is shutting down

We are able to reproduce this security issue in version 3.2.6 and at least back to 3.1.21

**Comment by dothebart** [comment]
Hi, 
the finer grained user management was implemented with ArangoDB 3.2, so ArangoDB 3.1 wouldn't support this at all. 
Since by the time the better user management was released with ArangoDB 3.2 the shutdown-handler wasn't adjusted to enforce this, it defined the API-behaviour for the 3.2 release series. 

For the upcomming arangodb 3.3 it was implemented with 7c31960cf21619f824ffd43c9057fbf151045410 - which is contained in the arangodb 3.3.milestone2 release. 

A version that could work with 3.2 if you want to patch it yourselves could be found here:
https://github.com/arangodb/arangodb/blob/097e60be1d38c8ba3930f13a6d5344cb2bd102e5/arangod/RestHandler/RestShutdownHandler.cpp

**Comment by fdsg-tk** [comment]
Hi, 
in general this means:
If you are hosting several databases with separated users on one ArangoDB instance, then anybody, who has a user account and access to a database, is able to shutdown the whole database instance and to stop all other database services which were running on the same instance.

This looks like a huge security hole to me and I am wondering, that this has not been closed for such a long time, since it appears in ArangoDB 3.1 and 3.2.
This security issue is currently a full show-stopper for us.

Do you have a suggestion, until when this issue will be closed within an official release of ArangoDB?
If this will not be fixed before v.3.3 I expect, that this issue will be open for a couple of months, correct?

Regards,
Tobias

**Comment by sleto-it** [comment]
Hi @fdsg-tk,

Thanks for opening this issue. We have discussed this internally and we feel this should be fixed into 3.2 branch as well. *Administrative* privilege should be required to shutdown the server

We will work on this as soon as possible and will keep you updated

Many thanks again,

**Comment by sleto-it** [comment]
PR https://github.com/arangodb/arangodb/pull/3616

**Comment by sleto-it** [comment]
Hi @fdsg-tk,

Thanks again for opening this ticket. Version 3.2.7 has now been released and it includes a fix for this problem

Please could you upgrade? I am now closing this ticket. If the issue persists, please feel free to comment

Many thanks,
