### ISSUE TITLE
periodic 1457 timeout in cluster operation

### ISSUE THREAD

**Issue by ldap4life** [arangodb/arangodb#3598]
I'm using the latest ArangoDB of the respective release series:
- [ x ] 3.2.2 Community Edition

Mode:
- [ x ] Cluster
There are 2 vms, each with 2 primary db servers and 2 coordinators. There are 5 agents, 3 on 1 vm, and 2 on the other

Storage-Engine:
- [ x ] mmfiles

On this operating system:
  - [ x ] RedHat .rpm

The following problem occurs:
Every so often, this result from the java driver: com.arangodb.ArangoDBException: Response: 500, Error: 1457 - AQL: timeout, cluster node: 'PRMR-7a8c4b40-9b26-4f74-9228-0839d42f607c', endpoint: 'ssl://11.111.111.111:8539', error: 'timeout in cluster operation' (while executing). I would estimate under 2% of queries get this result.

it can be a very basic query and collection can be very small. it does not always happen on the same collection. the same query will succeed on a retry. the error comes back very quickly.

in the arango request logs, this line corresponds to the error
2017-11-06T20:33:25Z [10068] INFO {requests} "http-request-end","0x7f470082d390","11.111.111.111","POST","HTTP/1.1",500,215,221,"/_api/cursor",0.005274

Instead I would be expecting: no error

workaround: edit the java driver to retry requests that fail with this error.

**Comment by sleto-it** [comment]
Hi @ldap4life,

Just wondering: have you had a chance to upgrade to a latest version (e.g. 3.2.12 or 3.3.5)?
Are you still getting this error from time to time?

Thanks,

**Comment by sleto-it** [comment]
Thanks for your feedback. I was able to reproduce the issue with v. 3.3.5

When moving to cluster from single server there are few things that can be optimize to maintain a high level of performance, e.g. queries

Regarding your deployment, it looked a bit strange to me. You wrote:

- 2 vms, each with 2 primary db servers and 2 coordinators  -  this is okay
- there are 5 agents, 3 on 1 vm, and 2 on the other - this is not recommended. You can decrease your agency size from 5 to 3, but please have 1 agent per vm or machine

if you want 5 agents anyway, then have 1 per vm.  it is okay if you have an agent running on the same machine where you have a dbserver and a coordinator

hope this helps,

**Comment by ldap4life** [comment]
Thank you for the response, ill experiment with different cluster setups.

**Comment by maxkernbach** [comment]
Hi @ldap4life,

did you have a chance to try the suggested cluster setup?

**Comment by ldap4life** [comment]
I did not unfortunately

**Comment by hkbarton** [comment]
any update on this? we're seeing same issue with 3.3.7 when we move from single server to multi servers cluster
