### ISSUE TITLE
bad import performance

### ISSUE THREAD

**Issue by stuxuhai** [arangodb/arangodb#3600]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [x] 3.2
- [ ] self-compiled devel branch

Mode:
- [x] Cluster
- [ ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [x] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [x] other: CentOS 6
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[x] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [x] this Driver: Java

We have got a problem that the import performance is bad if the document key likes "12.34,45.67", location data.  It takes long time to import about 16000 documents.

**Comment by dothebart** [comment]
Hi, 
please note that `_key`has to be uniq. The better the values are distributed, the better the index will perform. Since geo coordinates won't be that different, distribution is probably not that good. 

If you want to use geo queries, you need to put these on other attributes anyways. Its usually a good measure to create the index after doing the import.

**Comment by dothebart** [comment]
Can you provide a complete sample to demonstrate the effect?

**Comment by stuxuhai** [comment]
@dothebart Here is the sample.
[sample.txt](https://github.com/arangodb/arangodb/files/1449477/sample.txt)

**Comment by dothebart** [comment]
See what I wrote above: ```$ wc -l ~/Downloads/sample.txt 
148208 /home/willi/Downloads/sample.txt
$ sort -u  ~/Downloads/sample.txt  |wc -l 
69947
``` It won't work that way.
