### ISSUE TITLE
ArangoDB starter missing with homebrew installation

### ISSUE THREAD

**Issue by kvahed** [arangodb/arangodb#3604]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [X] 3.2
- [ ] self-compiled devel branch

Mode:
- [X] Cluster
- [ ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [X] MacOS, version:

### this is an installation-related issue:
brew install does not include the `arangodb` starter

**Comment by talkabhishek** [comment]
Is there any other option to install arangodb starter on mac after installing with brew?

**Comment by dothebart** [comment]
Hi, 
Please have a look at its download page: https://github.com/arangodb-helper/arangodb/releases
You may simply copy it to `/usr/local/bin/`.

**Comment by vinaypyati** [comment]
Hi,

version 3.4.0-RC1 has been released, which contains the fix for this bug. Hence, closing this issue.

Best,
