### ISSUE TITLE
Implicit collection creation no longer possible after version 3.2.0

### ISSUE THREAD

**Issue by respinha-ribeiro** [arangodb/arangodb#3606]
Previously, collections were automatically created upon their first document insertion. After upgrading the ArangoDB version from 3.2.0 to the latest one (3.2.6) an exception is always thrown, stating "AQL collection not found". This was only solved by explicitly creating the collection. Database operations are being performed with `arangojs`, but this issue seems related to the ArangoDB version itself.
Implicit collection creation seemed a really interesting feature for ArangoDB. Why was this changed?

Environment:
- ArangoDB version: 3.2.6
- Mode: single-server
- OS: official docker container

**Comment by jsteemann** [comment]
ArangoDB has never implicitly create collections on first use AFAIK.
Maybe arangojs has done this in the background, but I am unaware of such feature in ArangoDB.
Can you show the code that previously worked by implicitly creating collections? I would be interested to see how this has worked. Thanks!

**Comment by dothebart** [comment]
As @jsteemann already pointed out, there never was a feature to autocreate collections. Marking this question as answered.
