### ISSUE TITLE
update check/notification mixes up versions re minor and bugfix

### ISSUE THREAD

**Issue by grexe** [arangodb/arangodb#3610]
The update check is a bit weird... I have 3.1.26 installed, and got this notification:
```
New Version Available

Current: | 3.1.26
Minor: | 3.2.5
Bugfix: | 3.1.27
```
If you have `3.1.26`, then going to `3.2.5` is not a `minor` upgrade...
Sadly I don't have 3.1.27 at hand, sorry if this was already fixed there.

**Comment by dothebart** [comment]
Hi, 
its `MAJOR.MINOR.FIX` - It should be always safe to stay with one `MINOR` series and upgrade to the latest.
However, when switching a `MINOR` breaking changes may occur - studying the CHANGELOG in the documentation is advised. 

Updating to the latest FIX version will work with your distributions upgrade facilities (apt, yum, dnf, zypper) . 
Updating to a new `MINOR` version requires changing the download URL in your package manager.

**Comment by dothebart** [comment]
i.e. 3.2 over 3.1 brought you the rocksdb storage engine, which except for optionally changing the backend wouldn't bring much other features.
Whereas 3.0 over 2.8 removed the old graph framework in favour of the pattern matching framework introduced with 2.8 
So I think we can close this ;-)
