### ISSUE TITLE
How to pass in Pregel parameters using REST API?

### ISSUE THREAD

**Issue by joowani** [arangodb/arangodb#3615]
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [x] 3.2
- [ ] self-compiled devel branch

In https://github.com/joowani/python-arango/issues/52, I was told of undocumented support for Pregel in ArangoDB HTTP REST API. The example I was given (see github issue) does not show how I can pass algorithm parameters (e.g. maxGSS). Is this supported in ArangoDB 3.2? If it is, can I see an example? Thanks.

**Comment by graetzer** [comment]
I would like to cleanup the pregel API a little bit, this effort is ongoing in https://github.com/arangodb/arangodb/tree/feature/pregel-cleanup

**Comment by joowani** [comment]
Ok thanks @graetzer!
