### ISSUE TITLE
Inconsistent behavior of OR statement with object bind parameters

### ISSUE THREAD

**Issue by gurisko** [arangodb/arangodb#3618]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [x] 3.1
- [x] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [x] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [x] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
- [ ] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

```RETURN @data.order || 0```

* returns 0 when `{ "data" : {} }` is passed.
* returns 42 when `{ "data": { "order" : 42 } }`
* returns 42 when `{ "data": { "order" : 42, "whatever": "something" } }`
* **returns 0 when** `{ "data": { "order" : 42, "id": "id" } }` (this was observed to happen with `if`, `else`, `for`, `id`, `key` (and probably many more) keys)

**Comment by jsteemann** [comment]
Fixed via PR https://github.com/arangodb/arangodb/pull/3622

**Comment by sleto-it** [comment]
Hi @gurisko ,

Thanks again for opening this ticket. Version 3.2.7 has now been released and it includes a fix for this problem

Please could you upgrade? I am now closing this ticket. If the issue persists, please feel free to comment

Many thanks,
