### ISSUE TITLE
Unique bidirectional ?

### ISSUE THREAD

**Issue by cyrilchapon** [arangodb/arangodb#3625]
Hello,

Pretty new to Arango, I'm trying to use it to make some sort of social network... but not for people :D

Anyway, I'm trying to keep only one "friendship" (edge) between couples of document. While I'm also achieving it application-side, I'd like to deport it to an index.

So 2 simple questions

- Is it possible to keep, only with an indexing strategy, only one edge between documents ?
- If no, is there any performance incidence of having 2 edges (from...to and to...from) between the same documents when querying traversals ?

I realy don't care about *side* in that use case.

I'm aware of `unique-hash-indexes`, but a unique `_from, _to` doesn't cover `_to, _from` case
I'm aware of `any` direction while traversing too

Thanks :)

**Comment by dothebart** [comment]
Hi, 
you can achieve this by the following way: 

on saving the edge, you take the document id's of your vertices. You compare these, and make the lesser value the `_from` and the larger the `_to`. This way you can ensure edges always point into one direction. 
Once you have edges pointing in one direction, you can use a combined uniq index on `_from` and `_to` to enforce you don't have duplicate edges.

You will continue to use `ANY` as your traversal direction.

**Comment by dothebart** [comment]
Closing this question as answered. If more questions arise, don't hesitate to ask.
