### ISSUE TITLE
Support X-Forwarded-For-Prefix

### ISSUE THREAD

**Issue by Yogu** [arangodb/arangodb#3628]
## my environment running ArangoDB

I'm using the latest ArangoDB of the respective release series:
- [x] 3.2

On this operating system:
- [x] Linux 

## Feature proposal

We want to run arangodb behind a reverse proxy which adds a prefix, so that `/_db/` will be exposed as `/arangodb/_db/`. To suppor this, we need

* every redirect ArangoDB makes to include the prefix
* The frontend to use the prefix for API calls.

The frontend part is possible via `x-script-name`. However, we internally use the more common `X-Forwarded-For-Prefix` header for all services in a generic way and it would be great if the aardvark app would suppor this header out-of-the-box too.

For the redirections, I did not find any possibility to configure this.

**Comment by dothebart** [comment]
Hi, 
you can achieve this by going to `collections`, check the gear to the upper right, check `system`. 
go to `_routing` and edit the documents to contain your prefix.
For sure you can also write these documents from arangosh etc.

**Comment by dothebart** [comment]
@Yogu did the fix work for you? can we close this question?

**Comment by dothebart** [comment]
closing this question as answered.
