### ISSUE TITLE
truncate collection slowly

### ISSUE THREAD

**Issue by stuxuhai** [arangodb/arangodb#3631]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2

Mode:
- [x] Cluster

Storage-Engine:
- [x] rocksdb

On this operating system:
- [x] Linux 
  - [x] other: CentOS 6

### this is an AQL-related issue:
[x] I'm using graph features

I'm issuing AQL via:
- [x] this Driver: Java

Truncate a collection that has more than ten million documents very slowly.

**Comment by dothebart** [comment]
Yes, its a known issue. 
Deleting and re-creating collections is much faster.

**Comment by dothebart** [comment]
[edit] - the situation may improve with 3.2.7 and 3.2.8.

**Comment by maxkernbach** [comment]
Hi @stuxuhai,

FYI version 3.2.9 has been released a few days ago.
It would be useful to know if the performance improved in newer versions?

Thanks

**Comment by stuxuhai** [comment]
@maxkernbach 
It looks the performance improved. And the version we upgraded to is 3.2.8, we will consider upgrade to version 3.2.9 later.

**Comment by sleto-it** [comment]
@stuxuhai - thanks again for opening this ticket and for providing latest feedback

I was wondering if this is still a reason of concern for you or can we consider the level of performance good enough now?

Thanks,

**Comment by matcho** [comment]
@sleto-it 

Hello. Just sharing my experience here.

I've been experiencing relatively slow truncating times too, using ArangoDB 3.3.1, standalone (no cluster), RocksDB engine and a collection with ~ 7 millions documents and 13 indexes.

In such a case, issuing `db.mycollection.truncate()` in arangosh always ends up with a timeout. Then, the documents count in Aardvark shows 0 but the interface still takes a lot of time (> 10s) to display the (empty) content of the collection − it shows the little ping-pong animation.

A few minutes later (around 15) the interface becomes reactive again on this collection, as the operation seems complete.

This is not strongly impacting and I understand that all deletions have to be written to the WAL, but it's still quite long, especially when the machine has 32 CPU and 128 Gio of RAM.

Thanks
Mathias

**Comment by vinaypyati** [comment]
Hi @matcho,

ArangoDB 3.4 RC 1 has been released, which includes performance improvements. You can find the ArangoDB 3.4 RC 1 [here](https://www.arangodb.com/download-technical-preview/). Let us know your feedback!

Thanks!

**Comment by matcho** [comment]
I just tried tried truncating a 15M docs collection via arangosh, on arangod 3.4 RC 1.
It resulted on a server crash/restart :/

First time I issued the command, it took ~ 4mn to crash; all subsequent attempts resulted in an immediate crash.

### Arangosh output
```
db.images.truncate();
End of file
JavaScript exception in file '/usr/share/arangodb3/js/3.4.0/client/modules/@arangodb/arangosh.js' at 99,7: ArangoError 2001: Connection reset by peer
!      throw error;
!      ^
stacktrace: ArangoError: Connection reset by peer
    at Object.exports.checkRequestResult (/usr/share/arangodb3/js/3.4.0/client/modules/@arangodb/arangosh.js:97:21)
    at ArangoCollection.truncate (/usr/share/arangodb3/js/3.4.0/client/modules/@arangodb/arango-collection.js:506:12)
    at <shell command>:1:11
```

### Arangod.log
```
2018-09-28T14:35:08Z [32761] INFO using endpoint 'http+tcp://127.0.0.1:8529' for non-encrypted requests
2018-09-28T14:35:08Z [32761] INFO ArangoDB (version 3.4.0-rc.1 [linux]) is ready for business. Have fun!


---- crash happens here but nothing visible in log ----


2018-09-28T14:35:47Z [622] INFO ArangoDB 3.4.0-rc.1 [linux] 64bit, using jemalloc, build tags/v3.4.0-rc.1-0-g99e0d2026b, VPack 0.1.31, RocksDB 5.16.0, ICU 58.1, V8 5.7.492.77, OpenSSL 1.1.0h  27 Mar 2018
2018-09-28T14:35:47Z [622] INFO detected operating system: Linux version 4.15.0-33-generic (buildd@lcy01-amd64-024) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018
```

**Comment by maxkernbach** [comment]
Hi @matcho,

we would like to investigate your findings. Could you please provide the following information:

- How did you create the collection?
- Are you still using a standalone instance with RocksDB as described in your previous comment or a different setup? Is there a replication running?

**Comment by matcho** [comment]
Hi @maxkernbach 

The collection was created a long time ago (like 8 months or so) on version 3.2 I guess, and the server was gradually upgraded until 3.4 RC1.

It is a standalone instance, running on my Ubuntu 18.04 dev machine, with RocksDB.

There is no replication running.

**Comment by sleto-it** [comment]
@matcho would it be possible to get a dump with the structure of the collection at least (or a complete dump with data as well) so we can try to reproduce the issue with your exact dataset?

You could send us a message to hackers@arangodb.com (this ML is not public) and attach the dump in that email, or if it is too big we will reply to your email and provide a password protected folder where you can upload the archive. Please reference the number of this issue in your email

Many thanks,

**Comment by matcho** [comment]
Hi @sleto-it 

I tried dropping / recreating the collection from an existing dump, then truncating it again, same issue : after around 100s server restarts.

After logging-in again to aardvark (server restart logged me out), I see the collection but can't access the documents: the waiting (ping-pong) animation shows, and after a while I see an empty page saying "no documents". But, the documents count at the bottom left still says 21,558,956 doc(s)

In the log I can see
```
WARNING {queries} slow query: 'FOR x IN @@collection LET att = APPEND(SLICE(ATTRIBUTES(x), 0, 25), "_key", true) LIMIT @offset, @count RETURN KEEP(x, att)', bind vars: {"@collection":"img","count":10,"offset":0}, took: 69.167400 s
```
"Indexes" and "Info" views in aardvark show correct information, indexes are still present.

Sending you a message right now !

**Comment by maxkernbach** [comment]
@matcho Thanks for providing the requested dump. I could reproduce the error exactly as you described by restoring the provided dump with version 3.4 RC1 (silent server crash + same error message). Using the latest version 3.4 RC2 the truncate ran multiple times without any problems though.

This issue might already be resolved, could you please retry with version [3.4 RC2](https://www.arangodb.com/download-technical-preview/)?

**Comment by matcho** [comment]
@maxkernbach After the failed `truncate()` in 3.4 RC1 the collection was inaccessible (see my previous message).

I updated to 3.4 RC2, tried `truncate()` again from arangosh, it worked ! In around 3 minutes collection was truncated and accessible again.

Thank you very much !

**Comment by sleto-it** [comment]
thanks to you for the feedback @matcho and to anyone involved - glad it works now
we are now closing this ticket

thanks again,
