### ISSUE TITLE
limit in subquery

### ISSUE THREAD

**Issue by mrkoopa** [arangodb/arangodb#3640]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [x] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [ ] mmfiles
- [x] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [x] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [x] this Driver: arangojs

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

```
FOR outer IN [1, 2, 3]
  limit 3
  let subresult = (for p in ["a", "b", "c"] limit 4 return p)
  for inner in subresult
    return [outer, inner]
```
## my expected result is:

```
[ 1, 'a' ]
[ 1, 'b' ]
[ 1, 'c' ]
[ 2, 'a' ]
[ 2, 'b' ]
[ 2, 'c' ]
[ 3, 'a' ]
[ 3, 'b' ]
[ 3, 'c' ]
```
## my actual result is:
```
[ 1, 'a' ]
[ 1, 'b' ]
[ 1, 'c' ]
[ 2, 'a' ]
```
## query explain is:
```
Execution plan:
 Id   NodeType            Est.   Comment
  1   SingletonNode          1   * ROOT
  2   CalculationNode        1     - LET #6 = [ 1, 2, 3 ]   /* json expression */   /* const assignment */
  6   CalculationNode        1     - LET #13 = [ "a", "b", "c" ]   /* json expression */   /* const assignment */
  3   EnumerateListNode      3     - FOR outer IN #6   /* list iteration */
  4   LimitNode              3       - LIMIT 0, 3
  7   EnumerateListNode      9       - FOR inner IN #13   /* list iteration */
  8   LimitNode              4         - LIMIT 0, 4
 12   CalculationNode        4         - LET #10 = [ outer, inner ]   /* simple expression */
 13   ReturnNode             4         - RETURN #10
```
It seems to be a wrong optimization AFAIK

**Comment by jsteemann** [comment]
I subscribe to your view. This optimization is incorrect and must be prevented.

**Comment by sleto-it** [comment]
Hi,

Thanks again for opening this ticket. Version 3.2.10 has been released yesterday

I am now closing this ticket. Please feel free to comment if the problem persists

Many thanks,
