### ISSUE TITLE
Possibility of non-atomic UPDATE for large datasets

### ISSUE THREAD

**Issue by matcho** [arangodb/arangodb#3675]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2

Mode:
- [x] Single-Server

Storage-Engine:
- [x] rocksdb

On this operating system:
  - [x] Debian .deb

I'm issuing AQL via:
- [x] web interface with this browser: Firefox running on this OS: Ubuntu

## the issue
We're trying to refactor the data below (imported from another DBMS).

**queries** collection has 4.5 milllons docs (and it's just an excerpt), **obs** collection has 1.5 milllon docs.
There is a hash index on `queries._couchid` and one on `obs.related_queries[*]`.

Running the query below exceeds the machine's capacity (RAM I guess) and after a few minutes it fails. As UPDATEs are atomic, no documents are modified.
```
FOR o IN obs
    FILTER o.related_queries
    FOR q IN queries
        FILTER q._couchid == o.related_queries[-1]
        UPDATE o WITH {
            query_id: q._key
        } IN obs
```
While it's generally relevant that UPDATEs are atomic, in this case a non-atomic UPDATE would be helpful: the DB would write as many docs as it can, then the query could be executed again adding `FILTER o.query_id == null`, and multiple executions would eventually lead to the whole collection being updated.

Is there any way to achieve this ?
Maybe an option could be added at query execution time, like `atomic: false` ?
I understand it's kind of dangerous in a vast majority of cases.

Thanks a lot
Mathias

Appendix : the EXPLAIN
```
Execution plan:
 Id   NodeType                     Est.   Comment
  1   SingletonNode                   1   * ROOT
  2   EnumerateCollectionNode   1543029     - FOR o IN obs   /* full collection scan */
  3   CalculationNode           1543029       - LET #4 = o.`related_queries`   /* attribute expression */   /* collections used: o : obs */
  4   FilterNode                1543029       - FILTER #4
 10   IndexNode                 1543029       - FOR q IN queries   /* hash index scan */
  8   CalculationNode           1543029         - LET #8 = { "query_id" : q.`_key` }   /* simple expression */   /* collections used: q : queries */
  9   UpdateNode                      0         - UPDATE o WITH #8 IN obs

Indexes used:
 By   Type   Collection   Unique   Sparse   Selectivity   Fields           Ranges
 10   hash   queries      false    false       100.00 %   [ `_couchid` ]   (q.`_couchid` == o.`related_queries`[-1])

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   move-calculations-up-2
  4   move-filters-up-2
  5   remove-data-modification-out-variables
  6   use-indexes
  7   remove-filter-covered-by-index
  8   remove-unnecessary-calculations-2

Write query options:
 Option                   Value
 ignoreErrors             false
 waitForSync              false
 nullMeansRemove          false
 mergeObjects             true
 ignoreDocumentNotFound   false
 readCompleteInput        true
 useIsRestore             false
 consultAqlWriteFilter    false
```

**Comment by matcho** [comment]
Hi,

Adding a little info here : I've been recently issuing a large UPDATE on a 24 millions docs collection, and though it failed (server restart, query interrupted), a part of the docs were modified. Which is exactly what I hoped for.

Thus I've been able to issue the query again along with a filter to exclude already modified docs, and eventually managed to get all docs updated.

This happened twice and seems to be a "normal" behaviour from now.
Did something change between 3.2.6 and 3.2.7 ?

Thanks,
Mathias

**Comment by dothebart** [comment]
Hi, 
with 3.2.7 we have worked on many issues. Some of them memory management (V8, jemalloc) related, see https://github.com/arangodb/arangodb/blob/v3.2.8/CHANGELOG for all the details. 
These could have improved the behaviour in OOM cases. 

Since you said that you restarted the update after the crash, couldn't you use `LIMIT` for reducing the scope of these writes in first place so it doesn't crash?

**Comment by matcho** [comment]
Hi,
Yes you're right, using `LIMIT` along with `SORT doc._key` − the collection has auto-increment keys and a skiplist index on _`key` − does the trick.

I wanted to try a _one shot_ update since we have a bigger machine, hoping it would be large enough (and testing the OOM behaviour at the same time), hence the results mentioned here. But your solution is certainly the right way to do.

Feel free to close this topic if you think the initial request is not relevant.
Thanks

**Comment by dothebart** [comment]
Yes, I think from that perspective the feature request itself doesn't make that much sense.
so I think we can close this.
