### ISSUE TITLE
AQL query parameters are ignored in a SORT expression, unless they are preceded by a dot 

### ISSUE THREAD

**Issue by dariosalviwork** [arangodb/arangodb#3700]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [x] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [x] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [x] Windows, version: 7
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

```
FOR x in [{a:1},{a:2},{a:3},{a:4},{a:5},{a:6},{a:7},{a:8},{a:9},{a:10}]
SORT @sortby @sortDirection
RETURN x.a
```

With `@sortby` set to `x.a` and `@sortDirection` set to `DESC`

Explanation:

```
Query string:
 FOR x in [{a:1},{a:2},{a:3},{a:4},{a:5},{a:6},{a:7},{a:8},{a:9},{a:10}]
 SORT @sortby @sortDirection
 RETURN x.a

Execution plan:
 Id   NodeType            Est.   Comment
  1   SingletonNode          1   * ROOT
  2   CalculationNode        1     - LET #1 = [ { "a" : 1 }, { "a" : 2 }, { "a" : 3 }, { "a" : 4 }, { "a" : 5 }, { "a" : 6 }, { "a" : 7 }, { "a" : 8 }, { "a" : 9 }, { "a" : 10 } ]   /* json expression */   /* const assignment */
  3   EnumerateListNode     10     - FOR x IN #1   /* list iteration */
  6   CalculationNode       10       - LET #5 = x.`a`   /* attribute expression */
  7   ReturnNode            10       - RETURN #5

Indexes used:
 none

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   remove-redundant-sorts
  3   move-calculations-up-2
  4   remove-unnecessary-calculations-2
```

The issue can be reproduced using this dataset:
no need of dataset

Problem: **the sorting is completely ignored**.

Now, curiously, this other query works perfectly:

```
FOR x in [{a:1},{a:2},{a:3},{a:4},{a:5},{a:6},{a:7},{a:8},{a:9},{a:10}]
SORT x.@sortby @sortDirection
RETURN x.a
```

Why is that?

**Comment by jsteemann** [comment]
This is because you are sorting by the string `"x"`, and not the variable `x`.
And because the string `"x"` is a constant value, the sorting step won't change the result and is removed by the optimizer.
It is not possible to inject a variable name into a query using a bind parameter like that.

**Comment by Simran-B** [comment]
If I understand correctly, you pass the following bind parameters:

```json
{
  "sortby": "x.a",
  "sortDirection": "DESC"
}
```

You can run the following query to inspect what the *sortby* bind parameter looks like to Arango:

```js
FOR x in [{a:1},{a:2},{a:3},{a:4},{a:5},{a:6},{a:7},{a:8},{a:9},{a:10}]
RETURN @sortby
```

```json
[
  "x.a",
  "x.a",
  "x.a",
  "x.a",
  "x.a",
  "x.a",
  "x.a",
  "x.a",
  "x.a",
  "x.a"
]
```

It's really just the string "x.a". Sorting by a constant wouldn't change the order, thus the optimizer removes the Sort node from the execution plan.

If you want to sort by the `a` attribute values of `x`, you need to refer to the variable like in your second query, followed by either a literal `a` or a bind parameter with the string `"a"`:

```js
FOR x in [{a:1},{a:2},{a:3},{a:4},{a:5},{a:6},{a:7},{a:8},{a:9},{a:10}]
RETURN x.@sortby
// or:
//RETURN x[@sortby]
//RETURN x.a
```

```json
[
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10
]
```

For nested attributes, you can't use a syntax like `"a.b"` either. That was only supported [up to version 2.8](https://docs.arangodb.com/3.2/Manual/ReleaseNotes/UpgradingChanges30.html#attribute-names-and-parameters).

```js
FOR x in [{a:{b:1}},{a:{b:2}},{a:{b:3}},{a:{b:4}},{a:{b:5}}]
RETURN x.@sortby
```

Bind parameter: `{ "sortby": "a.b" }`

```json
[
  null,
  null,
  null,
  null,
  null
]
```

Since 3.0, you need to pass an array like `["a","b"]` to achieve the desired behavior.

Bind parameter: `{ "sortby": ["a","b"] }` (same query)

```json
[
  1,
  2,
  3,
  4,
  5
]
```

Or use multiple bind parameters:

```js
FOR x in [{a:{b:1}},{a:{b:2}},{a:{b:3}},{a:{b:4}},{a:{b:5}}]
RETURN x.@sortbyA.@sortbyB
```

Bind parameters: `{ "sortbyA": "a", "sortbyB": "b" }`

```json
[
  1,
  2,
  3,
  4,
  5
]
```

**Comment by dariosalviwork** [comment]
Thanks for the quick reply.

Maybe you can help me with this:

Let's suppose I am joining two collections this way:

```
FOR x in [{a:1},{a:2},{a:3},{a:4},{a:5}]
FOR y in [{b:'a', a:1},{b:'b', a:2},{b:'c', a:3},{b:'d', a:4},{b:'e', a:5}]
FILTER y.a == x.a
RETURN {x: x.a, y: y.b}
```

ideally, I would like to use a parameter to sort the results either by `x.a` or `y.b`, so that I wouldn't need to have to write two different queries.
Would it be possible?

Thanks...

BTW, feel free to close the issue!

**Comment by gurisko** [comment]
@dariosalviwork Ideally, start a new issue or join Slack channel.
However you cal always do something like `SORT (@sortBy == 'x' ? x.a : y.b) DESC`.

**Comment by dariosalviwork** [comment]
haven't thought about that solution.

Many thanks!

**Comment by jsteemann** [comment]
@gurisko : true, that solution will work indeed. I am not sure if the optimizer is smart enough in that case to use an index for sorting if available.

**Comment by Simran-B** [comment]
@jsteemann Should we make that a separate issue, at least for analyzing if the optimizer is smart enough?

**Comment by jsteemann** [comment]
@Simran-B : no objections, go ahead if you like.

**Comment by dothebart** [comment]
Ok, the sub ticket was solved, the question has been answered - we may now close this ticket.
