### ISSUE TITLE
Alive & Dead document counts incorrect after AQL INSERT

### ISSUE THREAD

**Issue by davidmw** [arangodb/arangodb#3704]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [X ] 3.2.6

Mode:
- [ X] Single-Server

Storage-Engine:
- [X ] mmfiles

On this operating system:
- [X ] MacOS, version: 10.13.1

### this is an AQL-related issue:
I'm issuing AQL via:
- [X ] web interface with this browser:  Safari   running on this OS: OSX
- [X ] arangosh

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

`INSERT { _from: "airports/BIS", _to: "airports/M75" } IN testEdgeCollection`

The issue can be reproduced using this dataset: airports

-------
Edge collection 'testEdgeCollection' is created with 32MB journal size and Wait for Sync = YES.

Inserting a single edge document as shown above (AQL Web interface or from arangosh) will insert a single edge (confirmed on Content tab) but the INFO tab shows ALIVE count = 0.

'Explain' shows 'Write query options: waitForSync = false'

Unloading the edge collection causes ALIVE = 1. Running the INSERT again results in two documents, with ALIVE = 1. 

TRUNCATE causes ALIVE = 0 and DEAD = 1.  

UNLOAD then causes ALIVE = -1 and DEAD = 2.

The problems compound if I do INSERT within a FOR.  The ALIVE and DEAD counts never seem correct. Compaction / garbage collection never seem to happen (over period of 2 hours idle time) even with 100k+ edge documents. When I insert 300k+ edges I often end up with a high number of 'WAL files not collected.'  Unloading and reloading, plus restarting the server will not reliably clean up the problems.

All my bulk inserts of edges using HTTP from arangosh work fine - all the ALIVE counts immediately match the document counts.

**Comment by dothebart** [comment]
With ArangoDB 3.7 the MMFiles storage engine is discontinued. 
Find the release notes here: https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/
