### ISSUE TITLE
Cursor can return duplicated documents

### ISSUE THREAD

**Issue by nervetattoo** [arangodb/arangodb#3706]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [x] 3.2.5
- [ ] self-compiled devel branch

Mode:
- [x] Cluster
- [ ] Single-Server

Storage-Engine:
- [x] mmfiles
- [ ] rocksdb

On this operating system:
- [x] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [x] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [x] this Driver: JS

### Problem

A query looking more or less like this:
```
FOR doc IN collection
LET data = doc.data
FILTER !doc.force && data.c && data.t && doc.done
&& doc.start >= 1483228800000
&& doc.done <= 1506815999000 && doc.url =~ "www\.foo\.com" && doc.type IN ["bar"]
RETURN doc
```

Ended up producing duplicate documents when consuming the cursor. Realising a cursor is used and drained, I had the idea of testing a hack, which turned out to fix the problem: Simply sorting by `doc._key`. This only happens when I consume the query programmatically on my end, if I use the UI i'm unable to produce duplicates. The query in question returns 3k docs, but dupes happen with different variations of the query and different number of results.
The arangojs code, which is the driver we use, looks to have very little room for bugs in the cursor implementation, so thats why I post this issue here.

I don't have time to try to build a dataset and failing code sample right now, but I might be able to do so later. I'm posting it without more context in the hope that the team will get a hunch about what can cause this and be able to investigate based on that.

Also, this also only happens in our cluster setup, so maybe its related to shard communication ... I've been unable to replicate it locally with a single-instance docker environment.
Our cluster runs 3 dbservers + 2 coords

**Comment by nervetattoo** [comment]
Update: Doing a sort only solves it up to a number of rows, surpassing 3k its back to giving dupes

**Comment by jsteemann** [comment]
Can you check if the problem still exists with 3.2.7?
I remember we fixed a bug in that release that may be related. The bugfix had to do with an internal cache for partial AQL results. The purpose of that cache was to avoid copying of data where possible, but the cache had a subtle bug. It could compare two different values equal, and then may have returned wrong data. That means it may have produced duplicate results, but it will not have produced more or less results than expected (number of results should not change due to the bug, just the contents of the results may have been wrong).
As I said, this bug was just fixed in 3.2.7, which was released today. If you could check if the problem still happens with that release, that would be a great help. Thanks!

**Comment by nervetattoo** [comment]
This was just the type of answer I was hoping for. I will make an effort to set up a 3.2.7 system and replicate the data over and give it a test.

**Comment by jsteemann** [comment]
Thanks!

**Comment by nervetattoo** [comment]
Looks like 3.2.7 solves it. I set up a secondary environment with 3.2.7 and the same data; Bug does not happen there. Tomorrow I will try to upgrade the real environment where it happens to 3.2.7 and finally verify that it fixes it completely.

**Comment by dothebart** [comment]
@nervetattoo can you confirm this can be closed?

**Comment by nervetattoo** [comment]
Yes! :D
