### ISSUE TITLE
RemoveServer endpoint not working (directly and from UI) 

### ISSUE THREAD

**Issue by dashdeep13** [arangodb/arangodb#3712]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [*] 3.2
- [ ] self-compiled devel branch

Mode:
- [*] Cluster
- [ ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [*] own infrastructure
- [*] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [*] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [*] using the cluster?
- [*] _system database?

These are the steps to reproduce:
1) Create a 4 node cluster (3 Agents, 4 Coordinators,4DbServers)r(using any mode, I used the arangodb starter)
2) Login to the UI and see the nodes running under the node tab.
3) Stop one node and wait for the "Node Error" to show up in the UI 
4) Try deleting the node from the UI(or call the removeServer endpoint directly).

The following problem occurs: 
Cluster: Could not fetch cluster information at the bottom 
Request - Response 
/_db/_system/_admin/cluster/removeServer
{"error":true,"code":400,"errorNum":400,"errorMessage":"unhandled role undefined"}

Instead I would be expecting: 
The node to be deleted from the cluster.

### this is an installation-related issue:
The issue is that:
In version 3.1.7:
Output of the Agency State - /_api/agency/read -d '[["/"]]'
"CRDN-04db2b95-3b4f-4139-abeb-78be7495b28e": {
           "Endpoint": "tcp://localhost:8544",
           "LastHeartbeatAcked": "2017-11-15T19:23:22Z",
           "LastHeartbeatSent": "2017-11-15T19:23:21Z",
           "LastHeartbeatStatus": "SERVING",
           `"Role": "Coordinator"`,
           "ShortName": "Coordinator0004",
           "Status": "GOOD"
         },
In version 3.2.4+ (This is from 3.2.7):
Output of the Agency State - /_api/agency/read -d '[["/"]]'
"CRDN-d926f139-e333-4fd2-a76a-b245294eb1d6": {
           "SyncStatus": "SERVING",
           "Timestamp": "2017-11-15T18:58:49Z",
           "Status": "GOOD",
           "Endpoint": "tcp://localhost:8544",
           "ShortName": "Coordinator0004"
         },
We see that we `Role` has been removed from the Agency State.
As a result this is failing:
https://github.com/arangodb/arangodb/blob/5c633f9fae3e371add3ddbd9607f1021449755e0/js/actions/api-cluster.js#L75

**Comment by sleto-it** [comment]
Hi, version 3.2.9 has been released. I am closing this issue now. If the problem persists please let us know.

Many thanks,
