### ISSUE TITLE
Calling a rest service of elastic cloud in arango 

### ISSUE THREAD

**Issue by karankapur999** [arangodb/arangodb#3744]
Hi I am using arango db 3.2.4 and unable to initiate a node-rest call from a foxx api using the arango. I have tried with following module -:

var Client = require('node-rest-client').Client;
var client = new Client();

var request = require('request');

It gives error 
<img width="1280" alt="screen shot 2017-11-20 at 11 22 54 am" src="https://user-images.githubusercontent.com/10877233/33004167-2fc9cdf6-cde5-11e7-8c93-60e2c9f0e883.png">

**Comment by dothebart** [comment]
Hi, 
please note that foxx is run synchroneous, and by issuing external HTTP requests, you may block (sparse) resources. 
For that reason the amount of available modules is a subset of the available modules. 

The list of modules comming with ArangoDB can be found here: 
https://docs.arangodb.com/3.2/Manual/Appendix/JavaScriptModules/

You may want to try whether `@arangodb/request` suits your needs.

**Comment by pluma** [comment]
I'm closing this issue as the question seems to have been answered. If you want to follow up on the answer, I recommend joining us on Slack.
