### ISSUE TITLE
Invalid result when using OLD object with array attribute in UPSERT statement

### ISSUE THREAD

**Issue by lkevin0** [arangodb/arangodb#3745]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [X] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [X] Single-Server

Storage-Engine:
- [X] mmfiles
- [X] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [X] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [X] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [X] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

The AQL query in question is:

```
FOR doc IN B
UPSERT {"status": doc.status}
INSERT {"status": doc.status, "machine": [doc.machine], "finishedStatus": doc.finishedStatus}
UPDATE {
  "machine": APPEND(OLD.machine, doc.machine, true),
  "finishedStatus": FLATTEN(
    LET doc1 = (
        FOR d IN doc.finishedStatus[*]
          LET pos = POSITION(OLD.finishedStatus[*].status, d.status, true)
        RETURN pos == -1 ? {"status": d.status, "count": d.count} : {"status": d.status, "count": d.count + OLD.finishedStatus[pos].count}
      )
      
      // Find result.finishedStatus that is not in doc (Collection B)
      LET doc2 = (
        FOR d IN OLD.finishedStatus[*]
          LET pos = POSITION(doc.finishedStatus[*].status, d.status, true)
          FILTER pos == -1
        RETURN {"status": d.status, "count": d.count}
      )

      RETURN APPEND(doc1, doc2)
  )
}
IN result
RETURN NEW
```

The issue can be reproduced using this dataset:

**Collection A**

```
{"status": ["1","2","3"], "machine": "A", "finishedStatus": [{"status": "4", "count": 10}, {"status": "5", "count": 1}]}
{"status": ["4","5","6"], "machine": "A", "finishedStatus": [{"status": "3", "count": 5}, {"status": "5", "count": 11}]}
```

**Collection B**

```
{"status": ["1","2","3"], "machine": "B", "finishedStatus": [{"status": "1", "count": 3}, {"status": "5", "count": 14}]}
{"status": ["2","5","2"], "machine": "B", "finishedStatus": [{"status": "5", "count": 5}, {"status": "3", "count": 5}]}
```

**Collection C**

```
{"status": ["2","5","2"], "machine": "C", "finishedStatus": [{"status": "5", "count": 2}, {"status": "3", "count": 5}]}
{"status": ["3","2","1"], "machine": "C", "finishedStatus": [{"status": "2", "count": 6}, {"status": "4", "count": 7}]}
```
    
**Collection result**

```
{"status": ["1","2","3"], "machine": ["A", "B"] , "finishedStatus": [{"status": "1", "count": 3}, {"status": "4", "count": 10}, {"status": "5", "count": 15}]}
{"status": ["2","5","2"], "machine": ["B", "C"], "finishedStatus": [{"status": "5", "count": 7}, {"status": "3", "count": 10}]}
{"status": ["3","2","1"], "machine": ["C"], "finishedStatus": [{"status": "2", "count": 6}, {"status": "4", "count": 7}]}
{"status": ["4","5","6"], "machine": ["A"], "finishedStatus": [{"status": "3", "count": 5}, {"status": "5", "count": 11}]}
```

The issue can be reproduced using this step:
1. UPSERT documents in Collection A [OK]
2. UPSERT documents in Collection B [Failed]
The finishedStatus of result should be
```
{
    "status": ["1","2","3"],
    "machine": ["A", "B"] ,
    "finishedStatus": [
        {"status": "1", "count": 3},
        {"status": "4", "count": 10},
        {"status": "5", "count": 15}
    ]
}
```
but it was updated using B.finishedStatus

My goal of this query is:
- Append new status of Collection A, B, C to result.finishedStatus.status if it does not found.
- If doc.finishedStatus.status found in result then doc.finishedStatus.count + result.finishedStatus.count

**Comment by jsteemann** [comment]
Quick update: the issue has been fixed in devel, yet there is not target milestone for it.

**Comment by sleto-it** [comment]
Hi,

Thanks again for opening this ticket. Version 3.3.0 has been released

I am now closing this ticket. Please feel free to comment if the problem persists

Many thanks,
