### ISSUE TITLE
Find a way to distinguish packages for the respectively intended distros to reduce error probability on manual install

### ISSUE THREAD

**Issue by grexe** [arangodb/arangodb#3762]
Tried to install the latest 3.2.8-1 Debian AMD64 package for Ubuntu 14.04 from
`https://download.arangodb.com/arangodb31/xUbuntu_14.04`
in an Ubuntu 14.04 based docker container fails with the following error:
```
Preparing to unpack arangodb3-3.2.8-1_amd64.deb ...
Unpacking arangodb3 (3.2.8) ...
dpkg: dependency problems prevent configuration of arangodb3:
 arangodb3 depends on libssl1.0.0 (>= 1.0.2~beta3); however:
  Version of libssl1.0.0:amd64 on system is 1.0.1f-1ubuntu2.21.
 arangodb3 depends on libstdc++6 (>= 6); however:
  Version of libstdc++6:amd64 on system is 4.8.4-2ubuntu1~14.04.3.

dpkg: error processing package arangodb3 (--install):
 dependency problems - leaving unconfigured
```
The affected packages `libssl` and `libstdc++6` are not available in the required versions on Ubuntu 14.04 with the standard repositories.

Same setting with ArangoDB 3.2.7 for Ubuntu 14.04 works fine, so maybe something went wrong during packaging?

**Comment by dothebart** [comment]
hm, `https://download.arangodb.com/arangodb31/xUbuntu_14.04` will only provide you with arangodb 3.1 releases in first place, so somethings wrong here from start.

The dependencies you're listing are only here with ubuntu 17 packages. 

Can you please revalidate whether the problem persists when manually downloading
https://download.arangodb.com/arangodb32/xUbuntu_14.04/amd64/arangodb3-3.2.8-1_amd64.deb
and installing it with `dpkg -i` ?

**Comment by grexe** [comment]
sorry @dothebart the url was wrong but not used anyway, as I downloaded the package directly (so we don't require internet connection during docker build).
I am infact using the package from `https://download.arangodb.com/arangodb32/xUbuntu_14.04/amd64/arangodb3-3.2.8-1_amd64.deb`.

**Comment by dothebart** [comment]
Hi, 
Checking out the dependencies of this package: 
```
dpkg -I arangodb3-3.2.8-1_amd64.deb 
 new debian package, version 2.0.
 size 33667208 bytes: control archive=141252 bytes.
     177 bytes,    13 lines      arangobench.conf     
    1670 bytes,    74 lines      arangod.conf         
     520 bytes,    30 lines      arango-dfdb.conf     
     158 bytes,    12 lines      arangodump.conf      
     143 bytes,    10 lines      arangoexport.conf    
     140 bytes,    10 lines      arangoimp.conf       
     101 bytes,    10 lines      arango-init-database.conf 
     161 bytes,    12 lines      arangorestore.conf   
     101 bytes,    10 lines      arango-secure-installation.conf 
     200 bytes,    14 lines      arangosh.conf        
     359 bytes,    11 lines      conffiles            
    2004 bytes,    83 lines   *  config               #!/bin/sh
     679 bytes,    21 lines      control              
     267 bytes,    15 lines      foxx-manager.conf    
  533264 bytes,  4805 lines      md5sums              
    4201 bytes,   130 lines   *  postinst             #!/bin/sh
    1256 bytes,    46 lines   *  postrm               #!/bin/sh
     544 bytes,    17 lines   *  preinst              #!/bin/sh
     359 bytes,    15 lines   *  prerm                #!/bin/sh
    1715 bytes,    45 lines      templates            
 Package: arangodb3
 Version: 3.2.8
 Section: database
 Priority: optional
 Architecture: amd64
 Depends: libc6 (>= 2.18), libssl1.0.0 (>= 1.0.1) <--------------------------------------------------
 Homepage: https://www.arangodb.com
 Conflicts: arangodb, arangodb3e, arangodb3e-client, arangodb3-client
 Installed-Size: 268879
 Maintainer: info@arangodb.com
 Description: the multi-model NoSQL database
  A distributed free and open-source database with a flexible data model for documents,
  graphs, and key-values. Build high performance applications using a convenient
  SQL-like query language or JavaScript extensions.
  .
  Copyright: 2014-2017 by ArangoDB GmbH
  Copyright: 2012-2013 by triAGENS GmbH
  ArangoDB Software
  www.arangodb.com
```
I don't see anything about libstdc++. Are you sure you're not mixing downloads?

**Comment by grexe** [comment]
I'm puzzled but cannot reproduce this now, works with 3.2.8-1 - will try to shed some light on this tomorrow, feel free to close and sorry for the false alarm.

**Comment by dothebart** [comment]
ok. Since we had other people mix versions up recently we may have to think about adding a way to prevent oneself to shoot in ones foot.  I will change the topic accordingly and mark this as a feature request.

**Comment by dothebart** [comment]
Meanwhile we use static executeables that don't depend on a specific OS libc and other libraries anymore. 
Marking as solved. 
Please find ArangoDB 3.7 available for download: 
https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/
