### ISSUE TITLE
[1.2] Suggestion: Provide a way to get current index value in a FOR ... IN loop

### ISSUE THREAD

**Issue by frankmayer** [arangodb/arangodb#378]
I think it would be practical to have a way to get the current index value. It can be of help for processing data dynamically during the loop. Also for example to break (#377) out of a loop in cetain conditions are met. 
A thing that of course would also help for dynamic processing of data in AQL would be this issue: #288

**Comment by konsultaner** [comment]
@frankmayer This is possible with the `POSITION()` method provided in arango

```AQL
RETURN POSITION([1,2,3],2,true)
// 2
```

**Comment by konsultaner** [comment]
@jsteemann Maybe you should reopen this and close #9120 in favor of your experimental PR?
