### ISSUE TITLE
collection.rename("validname") throws an error

### ISSUE THREAD

**Issue by mohamed-barakat** [arangodb/arangodb#3809]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [x] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [ ] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [x] MacOS, version: 10.13.1

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [x] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click to ...
...

The following problem occurs: [Screenshot?] 
Instead I would be expecting: 

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

```
$ arangosh --server.username root@example --server.database example --server.password xyz --console.pretty-print
                                       _
  __ _ _ __ __ _ _ __   __ _  ___  ___| |__
 / _` | '__/ _` | '_ \ / _` |/ _ \/ __| '_ \
| (_| | | | (_| | | | | (_| | (_) \__ \ | | |
 \__,_|_|  \__,_|_| |_|\__, |\___/|___/_| |_|
                       |___/

arangosh (ArangoDB 3.2.8 [darwin] 64bit, using jemalloc, VPack 0.1.30, RocksDB 5.6.0, ICU 58.1, V8 5.7.492.77, OpenSSL 1.0.2m  2 Nov 2017)
Copyright (c) ArangoDB GmbH

Pretty printing values.
Connected to ArangoDB 'http+tcp://127.0.0.1:8529' version: 3.2.7 [server], database: 'example', username: 'root@example'

Type 'tutorial' for a tutorial or 'help' to see common examples
127.0.0.1:8529@example> c = db.test
[ArangoCollection 4523556, "test" (type document, status loaded)]

127.0.0.1:8529@example> c.rename("better-example");
JavaScript exception in file '/usr/local/opt/arangodb/share/arangodb3/js/client/modules/@arangodb/arangosh.js' at 98,7: ArangoError 11: forbidden
!      throw error;
!      ^
stacktrace: ArangoError: forbidden
    at Object.exports.checkRequestResult (/usr/local/opt/arangodb/share/arangodb3/js/client/modules/@arangodb/arangosh.js:96:21)
    at ArangoCollection.rename (/usr/local/opt/arangodb/share/arangodb3/js/client/modules/@arangodb/arango-collection.js:539:12)
    at <shell command>:1:3


127.0.0.1:8529@example>
```

**Comment by dothebart** [comment]
Hi, 
your user lacks the permissions to rename the collection. 
In the "users" tab you need to: 
 - check "Administrate" for "example" 
 - Open the 'collections' - dropdown on "example"
 - check "Read/Write" for the every collection (`*`) - column

**Comment by mohamed-barakat** [comment]
Everything looks good so far, still I cannot rename:

<img width="1578" alt="screen shot 2017-11-27 at 14 39 03" src="https://user-images.githubusercontent.com/871986/33269404-dabac5c6-d380-11e7-8321-06c184d912d2.png">

**Comment by dothebart** [comment]
You will need the `Read/Write` row of the `*` column checked in order to make it work.

**Comment by mohamed-barakat** [comment]
Ah, sorry, I misinterpreted what you meant by `(*)`. Thank you very much.
