### ISSUE TITLE
POST /_api/gharial/{graph-name}/edge/{collection-name} Does not check referenced vertices

### ISSUE THREAD

**Issue by mpv1989** [arangodb/arangodb#3811]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] self-compiled devel branch

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) create a named graph
3) create edge with non existing vertex references (i.e. via curl)

The following problem occurs: The edge is successfully saved
Instead I would be expecting: an error saying vertices are not existing

**Comment by falmiski-cr** [comment]
This problem is still prevalent.

**Comment by hkernbach** [comment]
Fixed in https://github.com/arangodb/arangodb/pull/4983 and https://github.com/arangodb/arangodb/pull/4984.

**Comment by Simran-B** [comment]
@hkernbach Doesn't look like it made it into 3.3.6 (or rather 3.3.7)

**Comment by maxkernbach** [comment]
Version 3.3.9, which includes a fix for `POST /_api/gharial/{graph-name}/edge/{collection-name} ` has been released today. The gharial API is now checking the existence of _from and _to vertices during edge creation.
