### ISSUE TITLE
Foxx configuration keys cannot contain spaces (will not save).

### ISSUE THREAD

**Issue by aaronleesmith** [arangodb/arangodb#3818]
## my environment running ArangoDB 3.2.8

Mode:
- [ ] Cluster
- [X] Single-Server

Storage-Engine:
- [ ] mmfiles
- [X] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [X] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is a web interface-related issue:
I'm using the web interface with this browser: Chrome running on this OS: OSX Sierra
- [X] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as any
3) Manage a service which has configuration options which contain spaces in their key names.
4) Save. **Notice the changes are not saved (in the network traffic the new value is NOT reflected.**

**Comment by pluma** [comment]
We consider this a UI bug for ArangoDB 3.x but the original intent was not to allow arbitrary strings as configuration/dependency names. To avoid breaking existing code, we will continue supporting these values in 3.x and fix the UI code. However starting with 3.3 we will document what these values SHOULD look like and log warnings to help avoid problems when upgrading to ArangoDB 4 in the future.

**Comment by hkernbach** [comment]
@pluma fixed in prs:
https://github.com/arangodb/arangodb/pull/3993 & https://github.com/arangodb/arangodb/pull/3994 &
https://github.com/arangodb/arangodb/pull/3995
please review.

**Comment by maxkernbach** [comment]
Version 3.2.11 has been released and includes the fix for the problem you reported.
Please reopen this issue if the problem still occurs.

Thanks
