### ISSUE TITLE
Field validation error in ArangoDB UI - Minor

### ISSUE THREAD

**Issue by Calrain** [arangodb/arangodb#3822]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2.8

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [ ] mmfiles
- [x] rocksdb

On this operating system:
- [ ] Windows, version: Windows Server 2016

Sometimes you want to open a system collection within an ArangoDB database, such as going into _jobs and Truncating it to flush a queue and make it easier to debug things with.

When you use the ArangoDB UI to go into system collections, there is a field validation error on the name of the collection because it starts with a _.

![image](https://user-images.githubusercontent.com/1972620/33306896-36ccd2fc-d460-11e7-824e-99ba2e4a0cf1.png)
Note: The validation error is displayed when you click out of the name field, e.g. when you click the form or the 'Truncate' button.

It is a minor issue, but it may be worth updating the field validation to not throw the error on internal ArangoDB system collections.

**Comment by hkernbach** [comment]
Thanks for the report. This is, of course, a not wanted behavior. 
Fixed in 3.3, 3.2 and devel branch. 

PRs: https://github.com/arangodb/arangodb/pull/3959 & https://github.com/arangodb/arangodb/pull/3961 & https://github.com/arangodb/arangodb/pull/3962

**Comment by sleto-it** [comment]
Hi,

Thanks again for opening this ticket. Version 3.2.10 has been released yesterday

I am now closing this ticket. Please feel free to comment if the problem persists

Many thanks,
