### ISSUE TITLE
Unable to kill an AQL query

### ISSUE THREAD

**Issue by avive99** [arangodb/arangodb#3840]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [V] 3.1
- [ ] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [V] Single-Server

Storage-Engine:
- [V ] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [V] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [V] web interface with this browser: Chrome     running on this OS: Windows
- [V] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:
queries.kill(94758);

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click to ...
...

The following problem occurs: [Screenshot?] 
Instead I would be expecting: 
Greetings
I've issued a wrong-designed AQL query in the GUI (ArangoDB 3.1.22), and now it's impossible to kill that query.
Trying to cancel the Query using GUI or using "queries.kill(NN);" from arangosh - didn'r work.
The query is still in state=executing.
Warning messages however appear in ArangoDB log file after each kill trial :
...WARNING killing AQL query 94758 ...

Is there any workaround or solution to actually kill a wrong-designed query ?

Best regards,
Avi Vainshtein

![image](https://user-images.githubusercontent.com/34095415/33374944-dd828c08-d510-11e7-9fdb-d1f4cc33deda.png)

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

**Comment by jsteemann** [comment]
Is it possible to share the query string? It's hardly readable in the screenshot.
Thanks!

**Comment by avive99** [comment]
Yes, of course.

RETURN LENGTH(users[* FILTER users.username like "%262%"])

This should be kind a "select count(*) from .. where …", but am I'm very new in ArangoDB, and it's  a wrong query…
Anyway, it is still running – more than 48 hours – and I can't kill it.

Many thanks,
Avi

**Comment by jsteemann** [comment]
I think the query 
```
RETURN LENGTH(users[* FILTER users.username like "%262%"])
```
will be very expensive.
Its execution plan is:
```
Query string:
 RETURN LENGTH(users[* FILTER users.username like "%262%"]) 

Execution plan:
 Id   NodeType          Est.   Comment
  1   SingletonNode        1   * ROOT
  2   CalculationNode      1     - LET #2 = LENGTH(users   /* all collection documents */[* FILTER LIKE(users   /* all collection documents */.`username`, "%262%")])   /* v8 expression */
  3   ReturnNode           1     - RETURN #2

Indexes used:
 none
```
It will first materialize the entire users collection, and for each user it will again materialize it. The latter is happening because the FILTER condition refer to `users.username`, but it should rather be `CURRENT.username`. `CURRENT` means the current element in context of the `*` operator, and `users` here will mean the entire collection.

Changing it like that will make it less expensive:
```
Query string:
 RETURN LENGTH(users[* FILTER CURRENT.username like "%262%"]) 

Execution plan:
 Id   NodeType          Est.   Comment
  1   SingletonNode        1   * ROOT
  2   CalculationNode      1     - LET #2 = LENGTH(users   /* all collection documents */[* FILTER LIKE(#0_.`username`, "%262%")])   /* v8 expression */
  3   ReturnNode           1     - RETURN #2

Indexes used:
 none
```
That's as good as it will get using the `*` operator at the moment.
It can be further improved by switching from `*` to `FOR ... FILTER`, e.g.
```
Query string:
 FOR doc IN users FILTER doc.username like "%262%" RETURN doc

Execution plan:
 Id   NodeType                  Est.   Comment
  1   SingletonNode                1   * ROOT
  2   EnumerateCollectionNode      0     - FOR doc IN users   /* full collection scan */
  3   CalculationNode              0       - LET #1 = LIKE(doc.`username`, "%262%")   /* simple expression */   /* collections used: doc : users */
  4   FilterNode                   0       - FILTER #1
  5   ReturnNode                   0       - RETURN doc

Indexes used:
 none
```
However, even if a query takes long, one should be able to kill it eventually, so I will look into that too.

**Comment by jsteemann** [comment]
Sorry, just saw that my last query returns the documents and not the number of documents.
So it should rather be
```
RETURN LENGTH(FOR doc IN users FILTER doc.username like "%262%" RETURN 1)```

**Comment by avive99** [comment]
Many thanks ☺

Any ideas how to kill the still running query ?

**Comment by jsteemann** [comment]
I looked into this a bit and the query seems to be stuck/slow while materializating documents to V8 objects. It seems there is no easy way to interrupt this function, as it is a general VelocyPack->V8 function which is not aware of AQL queries and the like.
So the obvious fix here is to avoid the intermediate conversion to V8, which will make the query cancellable and also faster.
It can be done on the user side by rewriting the query as I did in my previous comment. Such query should be cancellable already easily. And for an upcoming release, I will try removing the intermediate materialization to V8 even in case of the original query. That will also make it cancellable in the future. It is a bit of work unfortunately, so I doubt the change can be made available quickly and for 3.1. I would expect it to land in some 3.3 version rather.

For your actual query that is now long-running: one way to stop it is to forcefully kill the server process using `kill -9`. Before doing so, please make sure all write operations have stopped and all writes have reached the disk. Then it should be safe to kill it and restart.

**Comment by Simran-B** [comment]
Would it be an option to disallow collection names being used to refer to all documents of a collection, and only permit collection names to be used as part of a FOR loop?

    RETURN coll // disallow
    FOR doc IN coll RETURN doc // enforce this pattern

I think this would also allow for better error messages if a variable isn't defined in a query: Currently, if there's no variable x, the parser will look for a collection x, and if that does not exist, the error will state that collection x was not found instead of variable x not defined. If a collection does exist co-incidentally, you'll likely get weird results.

The performance aspect / inability to kill a query is another good reason to get rid of "collection name stands for array of documents" IMHO.

Related user request: #2492

**Comment by jsteemann** [comment]
@Simran-B : I don't think so.
We just need to change the execution plans for that, so that they use a regular `FOR` loop for it. Then such queries become immediately killable.

**Comment by Simran-B** [comment]
That would solve the major issue indeed. What about the misleading error messages if variables aren't defined and the protection against user errors as described in #2492 however?

**Comment by jsteemann** [comment]
@Simran-B : ArangoDB is a schema-free database. We cannot protect against such typos other by disallowing them. That will break existing queries however, so we added the "fail on warning" option for this.

**Comment by Simran-B** [comment]
Okay. TODO for me: add troubleshooting tip to docs, something along

> Check execution plan for `/* all collection documents */` and verify that it is intended

(A user on Slack just had this very problem. He referred to the full collection instead of the edge var emitted by a traversal.)

**Comment by jsteemann** [comment]
Ok.

**Comment by avive99** [comment]
Jan – many thanks for the explanations.

I've bounced ArangoDB ("systemctl stop/start arangodb3.service"), and that long-running query disappeared.

Indeed it would be nice if ArangoDB would have a possibility to kill ALL kind of queries, especially when non-experienced users run their first-ever AQL queries.
I understand that the resolution is expected to be in >=3.3 version, so I'll wait patiently.

Many thanks and best regards

**Comment by jsteemann** [comment]
@avive99 : just to manage expectations:
A fix for this has not been implemented yet. When I wrote "I would expect it to land in some 3.3 version rather" I did not mean to indicate that this will be available in 3.3.0, but rather in some follow-up version, i.e. 3.3.x.

**Comment by jsteemann** [comment]
And I agree: all AQL queries should be killable eventually. Normally this should be possible by iterating over the list of running queries and issues the kill command for each. We "only" have to make the queries killable in all stages.

**Comment by PauloFerreira25** [comment]
same problem here.

Version 3.4.6 running in cluster. Coordinator8529 does not kill operation

```bash
2019-05-29T19:33:39Z [13035] WARNING killing AQL query 681 '                    let x = (\n    FOR v IN bulkfile_transacao\n    //LIMIT 4\n    FILTER v.cnpj == 111\n    RETURN {"_id": v._id , "datas" : v.vendas.parceladoSJurosVendasList[*].dtaCredito }\n    )\n    \nFOR data IN x\n    FOR f IN dtaCredito_distinct\n        FOR dt IN data.datas\n            FILTER f.dtaCredito == dt\n            return {"_to": data._id , "_from" : f._id, "dtaCredito" : dt } \n//RETURN {"_id": data._id , "datas" : f._id }\n//return f'
2019-05-29T19:33:44Z [13035] WARNING killing AQL query 113 'let x = (\n    FOR v IN bulkfile_transacao\n    //LIMIT 4\n    FILTER v.cnpj == 1084522000181\n    RETURN {"_id": v._id , "datas" : v.vendas.parceladoSJurosVendasList[*].dtaCredito }\n    )\n    \nFOR data IN x\n    FOR f IN dtaCredito_distinct\n        FOR dt IN data.datas\n            FILTER f.dtaCredito == dt\n            INSERT {"_to": data._id , "_from" : f._id, "dtaCredito" : dt } INTO arestasDta\n//RETURN {"_id": data._id , "datas" : f._id }\n//return f'
2019-05-29T19:35:05Z [13035] WARNING killing AQL query 681 '                    let x = (\n    FOR v IN bulkfile_transacao\n    //LIMIT 4\n    FILTER v.cnpj == 111\n    RETURN {"_id": v._id , "datas" : v.vendas.parceladoSJurosVendasList[*].dtaCredito }\n    )\n    \nFOR data IN x\n    FOR f IN dtaCredito_distinct\n        FOR dt IN data.datas\n            FILTER f.dtaCredito == dt\n            return {"_to": data._id , "_from" : f._id, "dtaCredito" : dt } \n//RETURN {"_id": data._id , "datas" : f._id }\n//return f'
2019-05-29T19:35:10Z [13035] WARNING killing AQL query 113 'let x = (\n    FOR v IN bulkfile_transacao\n    //LIMIT 4\n    FILTER v.cnpj == 111 \n    RETURN {"_id": v._id , "datas" : v.vendas.parceladoSJurosVendasList[*].dtaCredito }\n    )\n    \nFOR data IN x\n    FOR f IN dtaCredito_distinct\n        FOR dt IN data.datas\n            FILTER f.dtaCredito == dt\n            INSERT {"_to": data._id , "_from" : f._id, "dtaCredito" : dt } INTO arestasDta\n//RETURN {"_id": data._id , "datas" : f._id }\n//return f'
```

**Comment by dothebart** [comment]
We're contineously working on identifying places where queries might get stuck and refuse to get killed.
I'm closing this since ArangoDB 3.4 has been EOLed recently, and [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) is available as outdated.

**Comment by Thetophh** [comment]
hi

**Comment by dothebart** [comment]
"I'm just a taxi driver"?
