### ISSUE TITLE
Time to upgrade built-in node modules again

### ISSUE THREAD

**Issue by adamstallard** [arangodb/arangodb#3846]
Joi is starting to feel old.

## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2

Mode:
- [x] Single-Server

Storage-Engine:
- [x] rocksdb

On this operating system:
- [ ] Linux 
  - [x] docker - official docker library

**Comment by Simran-B** [comment]
@pluma I guess this is something for you?
BTW: Does any of the existing labels starting with "3 " apply to this? Is it "3 Core"?

**Comment by pluma** [comment]
Major version changes in packages following semantic versioning like joi does indicate breaking changes. As the release cycle of ArangoDB is slower than that of joi, we can't keep up with joi's major version releases as it means breaking backwards compatibility for our users' Foxx services.

If you want to use a more recent version of joi or any other bundled dependencies, please add them to your Foxx service by installing them with npm or yarn and including the `node_modules` folder in your service bundle.

The way Foxx uses joi internally should be compatible with other versions of joi. If you do run into errors when using newer versions of joi in your Foxx service, please file an issue and we'll look into this.

**Comment by pluma** [comment]
I've created a PR to update the non-breaking deps but I'm closing this issue as there's currently no way we can upgrade joi before ArangoDB 4.
