### ISSUE TITLE
Deployment Doc - DC/OS update needed

### ISSUE THREAD

**Issue by davidmw** [arangodb/arangodb#3868]
Documentation doesn't seem to reflect current DC/OS admin interface

https://docs.arangodb.com/3.2/Manual/Deployment/Mesos.html#

```
Installing via DC/OS UI

Open your browser and go to the DC/OS admin interface
Open the "Universe" tab
Locate arangodb and hit "Install Package"
Press "Install Package"
```

I don't see a 'Universe' tab but there is a 'Catalog' item on left menu. Searching there for Arangodb does return the package.  Two buttons exist on that screen: CONFIGURE and DEPLOY

**Comment by dothebart** [comment]
Please use ArangoDB via the Kubernetes Operaton in DC/OS. 
ArangoDB 3.7 is available for Download. 
https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/
