### ISSUE TITLE
Unable to install ArangoDB3 3.2.8 CE

### ISSUE THREAD

**Issue by gabefair** [arangodb/arangodb#3872]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [X] 3.2.8 CE

Mode:
- [X] Single-Server

Storage-Engine:
- [X] rocksdb

On this operating system:
- [X] Windows, version: 10 Pro (v 1703) 64-bit (OS Build 15063.726)

### this is an installation-related issue:
The following problem occurs: 
>...
>Installing service ArangoDB: 
>Status: 0; Setting Description: ArangoDB - the native multi-model NoSQL database
>Status: 0; Starting Service
>Status: 1053
>CurrentState=1 Win32ExitCode=1066 ServiceSpecificExitCode=2

![image](https://user-images.githubusercontent.com/2096785/33532104-657313a2-d864-11e7-8dc3-e2899c2da07f.png)

`C:\Program Files\ArangoDB3 3.2.8\var\log\arangodb3` contains no files.

![image](https://user-images.githubusercontent.com/2096785/33532257-1fc3ee92-d866-11e7-84d4-b455ae111f7b.png)

![image](https://user-images.githubusercontent.com/2096785/33532263-2bfd1422-d866-11e7-97e8-66ac165f67bf.png)

![image](https://user-images.githubusercontent.com/2096785/33532275-4092fee2-d866-11e7-99da-637dc42a8e84.png)

It doesn't say what file it was looking for

**Comment by dothebart** [comment]
Hi, 
Do you see any log entries with Source `ArangoDB` ?

**Comment by gabefair** [comment]
Nothing. You don't have the[ `EventLog.Source` Property](https://msdn.microsoft.com/en-us/library/system.diagnostics.eventlog.source(v=vs.110).aspx) set in your app. Which is why its listing as "Service Control Manager"

![image](https://user-images.githubusercontent.com/2096785/33565885-5751e892-d8ec-11e7-98ef-3aad512a99ba.png)

![image](https://user-images.githubusercontent.com/2096785/33566037-d1d7cd2a-d8ec-11e7-8d08-9f1ec9ac1156.png)

**Comment by gabefair** [comment]
```
Output folder: C:\Program Files\ArangoDB3 3.2.8
Extract: LICENSE.txt... 100%
Extract: LICENSES-OTHER-COMPONENTS.md... 100%
Extract: README.md... 100%
Extract: README.txt... 100%
Extract: README.windows.txt... 100%
Output folder: C:\Program Files\ArangoDB3 3.2.8\etc
Output folder: C:\Program Files\ArangoDB3 3.2.8\etc\arangodb3
Extract: arango-dfdb.conf... 100%
Extract: arango-init-database.conf... 100%
Extract: arango-secure-installation.conf... 100%
Extract: arangobench.conf... 100%
Extract: arangod.conf... 100%
Extract: arangodump.conf... 100%
Extract: arangoexport.conf... 100%
Extract: arangoimp.conf... 100%
Extract: arangorestore.conf... 100%
Extract: arangosh.conf... 100%
Extract: foxx-manager.conf... 100%
Output folder: C:\Program Files\ArangoDB3 3.2.8\resources
Extract: arangodb.bmp... 100%
Extract: arangodb.ico... 100%
Extract: arangodb_big.bmp... 100%
Extract: arangodb_welcomefinish.bmp... 100%
Output folder: C:\Program Files\ArangoDB3 3.2.8\usr
Output folder: C:\Program Files\ArangoDB3 3.2.8\usr\bin
Extract: api-ms-win-core-console-l1-1-0.dll... 100%
Extract: api-ms-win-core-datetime-l1-1-0.dll... 100%
Extract: api-ms-win-core-debug-l1-1-0.dll... 100%
Extract: api-ms-win-core-errorhandling-l1-1-0.dll... 100%
Extract: api-ms-win-core-file-l1-1-0.dll... 100%
Extract: api-ms-win-core-file-l1-2-0.dll... 100%
Extract: api-ms-win-core-file-l2-1-0.dll... 100%
Extract: api-ms-win-core-handle-l1-1-0.dll... 100%
Extract: api-ms-win-core-heap-l1-1-0.dll... 100%
Extract: api-ms-win-core-interlocked-l1-1-0.dll... 100%
Extract: api-ms-win-core-libraryloader-l1-1-0.dll... 100%
Extract: api-ms-win-core-localization-l1-2-0.dll... 100%
Extract: api-ms-win-core-memory-l1-1-0.dll... 100%
Extract: api-ms-win-core-namedpipe-l1-1-0.dll... 100%
Extract: api-ms-win-core-processenvironment-l1-1-0.dll... 100%
Extract: api-ms-win-core-processthreads-l1-1-0.dll... 100%
Extract: api-ms-win-core-processthreads-l1-1-1.dll... 100%
Extract: api-ms-win-core-profile-l1-1-0.dll... 100%
Extract: api-ms-win-core-rtlsupport-l1-1-0.dll... 100%
Extract: api-ms-win-core-string-l1-1-0.dll... 100%
Extract: api-ms-win-core-synch-l1-1-0.dll... 100%
Extract: api-ms-win-core-synch-l1-2-0.dll... 100%
Extract: api-ms-win-core-sysinfo-l1-1-0.dll... 100%
Extract: api-ms-win-core-timezone-l1-1-0.dll... 100%
Extract: api-ms-win-core-util-l1-1-0.dll... 100%
Extract: api-ms-win-crt-conio-l1-1-0.dll... 100%
Extract: api-ms-win-crt-convert-l1-1-0.dll... 100%
Extract: api-ms-win-crt-environment-l1-1-0.dll... 100%
Extract: api-ms-win-crt-filesystem-l1-1-0.dll... 100%
Extract: api-ms-win-crt-heap-l1-1-0.dll... 100%
Extract: api-ms-win-crt-locale-l1-1-0.dll... 100%
Extract: api-ms-win-crt-math-l1-1-0.dll... 100%
Extract: api-ms-win-crt-multibyte-l1-1-0.dll... 100%
Extract: api-ms-win-crt-private-l1-1-0.dll... 100%
Extract: api-ms-win-crt-process-l1-1-0.dll... 100%
Extract: api-ms-win-crt-runtime-l1-1-0.dll... 100%
Extract: api-ms-win-crt-stdio-l1-1-0.dll... 100%
Extract: api-ms-win-crt-string-l1-1-0.dll... 100%
Extract: api-ms-win-crt-time-l1-1-0.dll... 100%
Extract: api-ms-win-crt-utility-l1-1-0.dll... 100%
Extract: arango-dfdb.exe... 100%
Extract: arango-init-database.exe... 100%
Extract: arango-secure-installation.exe... 100%
Extract: arangobench.exe... 100%
Extract: arangod.exe... 100%
Extract: arangodb.exe... 100%
Extract: arangodump.exe... 100%
Extract: arangoexport.exe... 100%
Extract: arangoimp.exe... 100%
Extract: arangorestore.exe... 100%
Extract: arangosh.exe... 100%
Extract: arangovpack.exe... 100%
Extract: concrt140.dll... 100%
Extract: foxx-manager.exe... 100%
Extract: libeay32.dll... 100%
Extract: msvcp140.dll... 100%
Extract: ssleay32.dll... 100%
Extract: ucrtbase.dll... 100%
Extract: vcruntime140.dll... 100%
Output folder: C:\Program Files\ArangoDB3 3.2.8\usr\share
Output folder: C:\Program Files\ArangoDB3 3.2.8\usr\share\arangodb3
Extract: arangodb-helper... 100%
Extract: arangodb-update-db... 100%
Extract: exitcodes.dat... 100%
Extract: icudtl.dat... 100%
Output folder: C:\Program Files\ArangoDB3 3.2.8\u
```

**Comment by dothebart** [comment]
Ok, 
does `C:\Program Files\ArangoDB3 3.2.8\etc\arangodb3.conf` point to `E:\gdrive\datalake\databases\arangoDB` ? Is the directory available and writeable? What filesystem is it? (ArangoDB won't run on e.g. CIFS shares )

**Comment by gabefair** [comment]
Can't start it from the services menu as well:
![image](https://user-images.githubusercontent.com/2096785/33566678-ba6cf582-d8ee-11e7-8892-97165ac9e877.png)

And My install options:
![image](https://user-images.githubusercontent.com/2096785/33566707-d699e51c-d8ee-11e7-9ac7-c2c0ce265ae0.png)

**Comment by gabefair** [comment]
There wasn't a `arangodb3.conf`, but I found it in `arangod.conf`
I think we are pinning down the issue:

![image](https://user-images.githubusercontent.com/2096785/33573005-942f4b7c-d902-11e7-855f-921f88053dd9.png)

Notice the timestamp. Ignore the stamp of 12/4/2017. They were all the same date of 10/16/2017 before I accidentally saved  a white-space change before the screenshot. 

So the previous uninstall left some config files behind. But luckily they are pointing to the correct location.

And the location exists and is writable.
![image](https://user-images.githubusercontent.com/2096785/33573368-907287f0-d903-11e7-9b04-8d97dbe40f32.png)

**Comment by dothebart** [comment]
if you run `C:\Program Files\ArangoDB3 3.2.8\usr\bin\arangod.exe -c C:\Program Files\ArangoDB3 3.2.8\etc\arangodb3\arangod.conf` do you see any specific error messages?

The service usually runs as a system user with special privileges, this could also be an issue.

**Comment by gabefair** [comment]
No issues there boss

![image](https://user-images.githubusercontent.com/2096785/33623480-1f53caa4-d9bf-11e7-9741-ceaa8d6d17e0.png)

**Comment by dothebart** [comment]
Ok, that basically means that the database server itself can start - just not as a service. 

One can use the `sc` command to manipulate services:
```
sc query arangodb 

SERVICE_NAME: arangodb 
        TYPE               : 10  WIN32_OWN_PROCESS  
        STATE              : 4  RUNNING 
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
```

```
$ sc stop arangodb 

SERVICE_NAME: arangodb 
        TYPE               : 10  WIN32_OWN_PROCESS  
        STATE              : 3  STOP_PENDING 
                                (NOT_STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
```

```
sc query arangodb

SERVICE_NAME: arangodb 
        TYPE               : 10  WIN32_OWN_PROCESS  
        STATE              : 1  STOPPED 
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
```

If any of these doesn't work out, can you try to make the database directory public writeable?

**Comment by gabefair** [comment]
the owner of the database directory is "Everyone" and is RW enabled. I'm trying the install again but this time using the defaut data location and I'm getting huge memory usage.  The default database directory is empty and I was not prompted during install that the database folder was not-empty. 

![image](https://user-images.githubusercontent.com/2096785/33691376-f30615a4-dab5-11e7-9d8c-0d79ef1fea71.png)

**Comment by dothebart** [comment]
Ok, 
so basically now it picked up the huge redit database from your other posts and is working properly?

**Comment by gabefair** [comment]
Success, it was able to install as a service from the installer. Thank you for your help
