### ISSUE TITLE
Arangodb memory overflow there is no solution?

### ISSUE THREAD

**Issue by moxiaoyu100** [arangodb/arangodb#3893]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [✔ ] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ✔] Cluster
- [ ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [ ✔] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ✔] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [✔ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[✔ ] I'm using graph features

I'm issuing AQL via:
- [✔ ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:
my query :
      let result=(
           for v in 4 outbound 'contacters/8bfb1794d5c640f6b805910d66eccb40' graph 'mygraph'
           return v
      )
      return length(result)

error:
![aa](https://user-images.githubusercontent.com/34149942/33602026-0734ee24-d9e9-11e7-8542-8bb5ed4b27df.png)

my data size:
v : 9Billion；e : 19Billion

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [✔ ] using the cluster?
- [✔ ] _system database?

**Comment by feitianstyle** [comment]
i  don't kown ，please tell me answer

**Comment by dothebart** [comment]
Hi, 
if You're interested in the length only, you simply may use `RETURN 1` to save resources.

**Comment by moxiaoyu100** [comment]
Hi,
Thank you, return 1 does save resources.
I am the first contact arangodb, so there are many problems do not understand, I hope you can guide me more.
I want to get "p", memory will overflow when get the relationship of 4 layers, can not get the desired graphics, in which case can I save resources better?

**Comment by feitianstyle** [comment]
@dothebart  hi
My problems and he, I am not interested in length, I hope I can get all the results returned without causing memory, whether there is a good solution, or need to modify the configuration, performance is the main secondary is not an error

**Comment by feitianstyle** [comment]
hi @dothebart    My question is the same as his,I'm not only interested in length,I wish I could get all the result sets,I only hope that the query can be executed and will not be reported wrong,What configuration files can be modified to achieve the purpose,I am a new arangodb. I hope you can answer me. Thank you
