### ISSUE TITLE
arangodb stop is not working, when cluster creation is in progress

### ISSUE THREAD

**Issue by hisoumit** [arangodb/arangodb#3896]
Using Arangodb 3.2.6:

 2.8
 3.0
 3.1
[*] 3.2
 self-compiled devel branch
Mode:

[*] Cluster
 Single-Server
Storage-Engine:

 mmfiles
 rocksdb
On this operating system:

 DCOS on
[*] AWS
 Azure
[*] own infrastructure
 Linux
 Debian .deb
[*] Ubuntu .deb
 SUSE .rpm
 RedHat .rpm
 Fedora .rpm
 Gentoo
 docker - official docker library
 other:
 Windows, version:
 MacOS, version:
this is an AQL-related issue:

[*] I'm using graph features

this is an installation-related issue:

Describe which steps you carried out, what you expected to happen and what actually happened.

Objective is to stop arangodb tool while creating the arangod cluster:

1- In the master node : run command ' arangodb start '
2- In the slave nodes : run command ' arangodb start --starter.join <master_ip> &'
3- In the slave node: run command ' arangodb stop '

Trace:
what actually happened:
ps -ef | grep arango
root      1864  1261  0 05:15 pts/5    00:00:03 arangodb start --starter.join 10.102.28.217
root      1869  1864  0 05:15 pts/5    00:00:00 /usr/bin/arangodb --starter.join=[10.102.28.217:8528]
root      1894  1261  0 05:25 pts/5    00:00:00 grep --color=auto arango
root@centralmsvm:~# arangodb stop
2017/12/05 05:25:14 Failed to shutdown starter: Post http://127.0.0.1:8528/shutdown: dial tcp 127.0.0.1:8528: getsockopt: connection refused

what you expected to happen:
It is expected that the arangodb tool should stop

**Comment by kunalak** [comment]
afaik - As long as the agents are not up, the starter will remain in bootstrap mode, in which shutdown is not possible.

**Comment by OmarAyo** [comment]
Hi @hisoumit 

Could you please, send us an update on this ticket.

**Comment by sleto-it** [comment]
Discussion is being continued in our private Jira. Closing
