### ISSUE TITLE
init script for arangodb tool

### ISSUE THREAD

**Issue by hisoumit** [arangodb/arangodb#3897]
Using Arangodb 3.2.6:

Mode:
[*] Cluster

[*] Ubuntu .deb

Running the arangodb tool as a service:

what actually happened:
No init script for arangodb tool.

what you expected to happen:

arangodb tool should run as a service, expected default init script for arangodb script to be used in case of cluster scenario.

**Comment by dothebart** [comment]
Hi, 
Cluster scenarios are alway a bit specific. which is why we don't offer init scripts for them. 
the [arangodb starter]https://github.com/arangodb-helper/arangodb) is here to be used therefore; its shipped in the debian packages. 

Please note that you should upgrade to 3.2.9

**Comment by hisoumit** [comment]
Is there any specific change for arangodb starter tool on 3.2.9 version?

**Comment by dothebart** [comment]
Yes, the starter changed from 0.10.2 -> 0.10.3; other issues which you may find have been fixed from 3.2.6 too.

**Comment by maxkernbach** [comment]
Hi @hisoumit,

did you have any problems using the arangodb starter or can we close this issue?

**Comment by kunalak** [comment]
@hisoumit can we close this issue? (see above replies)

**Comment by sleto-it** [comment]
HI All,

The _ArangoDB Starter_ can be started automatically at server startup, using scripts like the following (these are just examples):

arangodb.service:

```
[Unit]
Description=Run the ArangoDB Starter 
After=network.target

[Service]
Restart=on-failure
EnvironmentFile=/etc/arangodb.env
ExecStartPre=/usr/bin/sh -c "mkdir -p ${DATADIR}"
ExecStart=/usr/bin/arangodb \
    --starter.address=${MYIPADDRESS} \
    --starter.data-dir=${DATADIR} \
    --starter.join=${STARTERENDPOINTS} \
    --server.storage-engine=rocksdb \
    --auth.jwt-secret=${CLUSTERSECRETPATH}
TimeoutStopSec=60

[Install]
WantedBy=multi-user.target
```

arangodb.env:

```
MYIPADDRESS=192.168.173.31
DATADIR=/var/lib/arangodb/cluster
STARTERENDPOINTS=192.168.173.31:8528,192.168.173.32:8528,192.168.173.33:8528
CLUSTERSECRETPATH=/etc/arangodb.secret
ExecStartPre=/usr/bin/sh -c "mkdir -p ${DATADIR}"
```

**Comment by hisoumit** [comment]
We are using ubuntu 14.0.4.05, Arnagodb version 3.2.11. We are using upstart to start the arangodb service. Many a times the arangodb stop command doesn't stop the services.
cluster_start() {
     log_progress_msg "initializing arangodb folders"
    ( cd /var/log/arangodb3 && chown -R arangodb:arangodb . && chmod 700 . ) || exit 1
    ( cd /var/lib/arangodb3 && chown -R arangodb:arangodb . && chmod 700 . ) || exit 1
    ( cd /var/lib/arangodb3-apps && chown -R arangodb:arangodb . && chmod 700 . ) || exit 1

    ulimit -H -n 131072 || true
    ulimit -S -n 131072 || true

    log_progress_msg "stopping arangodb"
    arangodb stop


    if [ -f /etc/arangodb3/cluster.conf ]; then
      master_ip=`cat /etc/arangodb3/cluster.conf`
      log_progress_msg "starting arangodb secondary co-ordinator"
      log_progress_msg "Primary arangodb co-ordinator ip is $master_ip"
      cd /var/lib/arangodb3
      arangodb --starter.join "$master_ip" &
      RETVAL=$?
      log_end_msg $RETVAL
    else
      log_progress_msg "starting arangodb primary co-ordinator"
      cd /var/lib/arangodb3
      arangodb start
      RETVAL=$?
      log_end_msg $RETVAL
    fi
    return $RETVAL
    }

cluster_stop()  {
     log_daemon_msg "Stopping $DESC" "$NAME"
     log_progress_msg "stopping arangodb"
     arangodb stop
    }

**Comment by sleto-it** [comment]
Discussion is being continued in our private Jira. Closing
