### ISSUE TITLE
Arango can't be started with service after crash on Debian

### ISSUE THREAD

**Issue by roman1720** [arangodb/arangodb#3919]
3.2.9, single-server, mmfiles, Debian 8

When arango crashes (probably killed by OS because of out of memory):

2017-12-06T10:47:01Z [10616] INFO {startup} child process 10617 terminated normally, exit status 9 (SIGKILL). will intentionally not start a new child process

It's not possible to start arango again with service cmd

root@dev4:/home/autoboss/discovery/logs/tasker# service arangodb3 start 
root@dev4:/home/autoboss/discovery/logs/tasker# 
root@dev4:/home/autoboss/discovery/logs/tasker# 
root@dev4:/home/autoboss/discovery/logs/tasker# service arangodb3 status
● arangodb3.service - LSB: arangodb
   Loaded: loaded (/etc/init.d/arangodb3)
   Active: active (exited) since Tue 2017-12-05 13:08:23 CET; 23h ago

Dec 05 13:08:21 dev4 systemd[1]: Starting LSB: arangodb...
Dec 05 13:08:23 dev4 arangodb3[10545]: Starting arango database server: arangod{startup} starting up in daemon mode
Dec 05 13:08:23 dev4 arangodb3[10545]: .
Dec 05 13:08:23 dev4 systemd[1]: Started LSB: arangodb.
Dec 06 12:39:15 dev4 systemd[1]: Started LSB: arangodb.
Dec 06 12:39:30 dev4 systemd[1]: Started LSB: arangodb.
Dec 06 12:46:51 dev4 systemd[1]: Started LSB: arangodb.
root@dev4:/home/autoboss/discovery/logs/tasker# 
root@dev4:/home/autoboss/discovery/logs/tasker# ps axu | grep arango
root     29621  0.0  0.0  12664  1660 pts/0    S+   12:47   0:00 grep arango
root@dev4:/home/autoboss/discovery/logs/tasker# 

There's nothing in log files.

**Comment by roman1720** [comment]
When I try run arango manually then it's started, runs for a while, but in like 20s it eats out all available memory (16GB) and is killed again.

**Comment by dothebart** [comment]
Hi, 
can you install the debug symbols package, run it in gdb or start it to create a core dump? https://github.com/arangodb/arangodb/blob/devel/README_maintainers.md#linux-coredumps

**Comment by roman1720** [comment]
I followed instructions, but coredump is not generated, don't no why. I downloaded debug symbol package, what's strange with regular package it started to eat out memory after start, but with debug symbol package not, I found query which does it and running it crashes. I will send you on hackers@arangodb.com dump and query to reproduce issue. Another question is why arango doesn't even want to try start with service cmd. I remember this behavior was always like this.

**Comment by dothebart** [comment]
Ok, 
When I try this with current devel, it will do this: 
```
2017-12-06T15:39:19Z [27061] ERROR encountered out-of-memory error
2017-12-06T15:39:19Z [27061] WARNING {queries} slow query: 'FOR i in v .... COLLECT .... COLLECT ... COLLECT...
```
It's basically the same answer as here:

https://stackoverflow.com/questions/47481545/running-out-of-ram-on-large-aql-query-trying-to-split-a-collection-into-two

`COLLECT` currently is only implemented in memory, thus it doesn't scale, and if the number of documents rises above your available memory it may fail.

**Comment by ObiWahn** [comment]
generated systemd arangodb3.service file on debian jessie

```
root@c9:~# systemctl show arangodb3.service
Type=forking
Restart=no
NotifyAccess=none
RestartUSec=100ms
TimeoutStartUSec=5min
TimeoutStopUSec=5min
WatchdogUSec=0
WatchdogTimestamp=Thu 2017-12-07 11:50:48 CET
WatchdogTimestampMonotonic=4630667075
StartLimitInterval=10000000
StartLimitBurst=5
StartLimitAction=none
FailureAction=none
PermissionsStartOnly=no
RootDirectoryStartOnly=no
RemainAfterExit=yes
GuessMainPID=no
MainPID=0
ControlPID=0
Result=success
ExecMainStartTimestampMonotonic=0
ExecMainExitTimestampMonotonic=0
ExecMainPID=0
ExecMainCode=0
ExecMainStatus=0
ExecStart={ path=/etc/init.d/arangodb3 ; argv[]=/etc/init.d/arangodb3 start ; ignore_errors=no ; start_time=[Thu 2017-12-07 11:50:46 CET] ; stop_time=[Thu 2017-12-07 11:50:48 CET] ; pid=5293 ; code=exited ; status=0 }
ExecStop={ path=/etc/init.d/arangodb3 ; argv[]=/etc/init.d/arangodb3 stop ; ignore_errors=no ; start_time=[Thu 2017-12-07 11:50:40 CET] ; stop_time=[Thu 2017-12-07 11:50:46 CET] ; pid=5274 ; code=exited ; status=0 }
Slice=system.slice
ControlGroup=/machine.slice/machine-debian\x2djessie.scope/system.slice/arangodb3.service
CPUAccounting=no
CPUShares=18446744073709551615
StartupCPUShares=18446744073709551615
CPUQuotaPerSecUSec=(null)
BlockIOAccounting=no
BlockIOWeight=18446744073709551615
StartupBlockIOWeight=18446744073709551615
MemoryAccounting=no
MemoryLimit=18446744073709551615
DevicePolicy=auto
UMask=0022
LimitCPU=18446744073709551615
LimitFSIZE=18446744073709551615
LimitDATA=18446744073709551615
LimitSTACK=18446744073709551615
LimitCORE=18446744073709551615
LimitRSS=18446744073709551615
LimitNOFILE=1048576
LimitAS=18446744073709551615
LimitNPROC=257242
LimitMEMLOCK=65536
LimitLOCKS=18446744073709551615
LimitSIGPENDING=257242
LimitMSGQUEUE=819200
LimitNICE=0
LimitRTPRIO=0
LimitRTTIME=18446744073709551615
OOMScoreAdjust=0
Nice=0
IOScheduling=4
CPUSchedulingPolicy=0
CPUSchedulingPriority=0
TimerSlackNSec=50000
CPUSchedulingResetOnFork=no
NonBlocking=no
StandardInput=null
StandardOutput=journal
StandardError=inherit
TTYReset=no
TTYVHangup=no
TTYVTDisallocate=no
SyslogPriority=30
SyslogLevelPrefix=yes
SecureBits=0
CapabilityBoundingSet=18446744073709551615
MountFlags=0
PrivateTmp=no
PrivateNetwork=no
PrivateDevices=no
ProtectHome=no
ProtectSystem=no
SameProcessGroup=no
IgnoreSIGPIPE=no
NoNewPrivileges=no
SystemCallErrorNumber=0
RuntimeDirectoryMode=0755
KillMode=process
KillSignal=15
SendSIGKILL=yes
SendSIGHUP=no
Id=arangodb3.service
Names=arangodb3.service
Requires=basic.target
Wants=system.slice
WantedBy=graphical.target multi-user.target
Conflicts=shutdown.target
Before=multi-user.target graphical.target shutdown.target
After=remote-fs.target systemd-journald-dev-log.socket systemd-journald.socket basic.target system.slice
Description=LSB: arangodb
LoadState=loaded
ActiveState=active
SubState=running
FragmentPath=/run/systemd/generator.late/arangodb3.service
SourcePath=/etc/init.d/arangodb3
InactiveExitTimestamp=Thu 2017-12-07 11:50:46 CET
InactiveExitTimestampMonotonic=4628504199
ActiveEnterTimestamp=Thu 2017-12-07 11:50:48 CET
ActiveEnterTimestampMonotonic=4630667123
ActiveExitTimestamp=Thu 2017-12-07 11:50:40 CET
ActiveExitTimestampMonotonic=4622460238
InactiveEnterTimestamp=Thu 2017-12-07 11:50:46 CET
InactiveEnterTimestampMonotonic=4628493450
CanStart=yes
CanStop=yes
CanReload=no
CanIsolate=no
StopWhenUnneeded=no
RefuseManualStart=no
RefuseManualStop=no
AllowIsolate=no
DefaultDependencies=yes
OnFailureJobMode=replace
IgnoreOnIsolate=no
IgnoreOnSnapshot=no
NeedDaemonReload=no
JobTimeoutUSec=0
ConditionResult=yes
ConditionTimestamp=Thu 2017-12-07 11:50:46 CET
ConditionTimestampMonotonic=4628493812
Transient=no
```

**Comment by roman1720** [comment]
Problem with query and multiple collect is solved using keep. Thank you. I have problems with starting arango after crash. When I try service start, it doesn't start. When I try run arango manually a a then do service stop and service start it works.

**Comment by dothebart** [comment]
Hi, 
The remaining problem here is how systemd handles the integration of legacy system V init scripts. 
It seems systemd is not able to detect when a service goes a way when started that way. 

You can get out of that state by invoking 

    service arangodb3 stop

Then systemd gets into the state of mind that its sure that the service is gone, and then may subsequently start it again. 

We decided to ship systemd unit files with the ready existing distributions so the behaviour isn't changed for the users once they upgrade. 

With Ubuntu 17 and Debian 9 we ship a unitfile.
