### ISSUE TITLE
Gremlin graph queries for REST

### ISSUE THREAD

**Issue by F21** [arangodb/arangodb#392]
I have been playing with ArangoDB and the blueprints implementation and am very impressed so far. The [graph interaction over REST](http://www.arangodb.org/manuals/1.2.beta1/HttpGraph.html) is also very nice :)

While AQL is very beautiful, I would like to talk to my graphs using Gremlin as it is more natural and solves problems such as [vertex centric queries](http://thinkaurelius.com/2012/10/25/a-solution-to-the-supernode-problem/).

I propose that we add a resource called `/_api/graph/graph-name/gremlin` or `/_api/graph/graph-name/query` to allow using gremlin to query the graphs.

**Comment by akki** [comment]
Hi all, @fceller 
How can I use that module. Any documentation I could refer to?
I want to use ArangoDB via gremlin.

**Comment by akki** [comment]
Hi all, @fceller 
How can I use that graph module. Any documentation I could refer to?
I would like to use ArangoDB via Gremlin.

**Comment by Simran-B** [comment]
Have a look here about the general graph module: https://docs.arangodb.com/3.0/Manual/Graphs/GeneralGraphs/index.html

**Comment by vlabmichl** [comment]
Gremlin would is great as some kind of abstraction of the client against the backend system.

If you plan to make "graph database independent" queries (same traversal running on ArangoDB, Neo4J, whatever) -> gremlin support would be great.

I'd love to see that! Using Gremlin Traversals in a FOXX would be great!
