### ISSUE TITLE
Weird exception when executing an AQL query in cluster mode which works in single server mode

### ISSUE THREAD

**Issue by soualid** [arangodb/arangodb#3966]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2.9

Mode:
- [x] Cluster

Storage-Engine:
- [x] rocksdb

On this operating system:
- [x] DCOS on
  - [x] Azure

Hello,

The following query in a foxx service breaks in cluster mode, but the exact same query works well in the web UI as well as in a foxx service using single server mode.

```
WITH users, isFriendWith FOR v, e IN ANY 'users/3015308' isFriendWith FILTER v._id == 'users/3015304' LIMIT 1 RETURN e
```

The error returned is : 

```
AQL: collection not known to traversal: 'users'. please add 'WITH users' as the first line in your AQL (while executing)
```

Thank you in advance for looking at this.

**Comment by jsteemann** [comment]
For traversals in the cluster, all collections that will be used in the traversal need to be specified in the `WITH` clause at the beginning of the query. This is enforced in the cluster, but not in the single server for some internal reasons.
So changing the beginning of the query string to 
```
WITH users, isFriendWith, users
```
may help. There may be other collections still missing, and if so, they will need to be added to the `WITH` clause as well.

**Comment by soualid** [comment]
Thank you for the quick answer. We still got the same issue after adding `users` to the original `WITH` clause. The full query being the one mentioned in the original message, I do not think there are other collections involved.

The full query is now : 

```
WITH users, isFriendWith, users FOR v, e IN ANY 'users/3016103' isFriendWith FILTER v._id == 'users/3016099' LIMIT 1 RETURN e
```

Thanks !

**Comment by jsteemann** [comment]
Hi, sorry for me causing confusion! Obviously your original query already contained the `users` collection in the `WITH` clause. I think I was just confused. 
Will check if I can reproduce the problem locally.

**Comment by jsteemann** [comment]
I just tried that same query using 3.2.9 cluster with RocksDB storage engine.
"users" is a document collection, and "isFriendWith" I set up as an edge collection. I was able to execute the query without problems, both with empty and with populated collections. I also tried using different number of shards, but that did not seem to change anything.
I also tried running the query from within a Foxx app, and that also worked. The app was also able to return the query's result.

**Comment by jsteemann** [comment]
Is the problem persistent, I mean, does it still occur for that query, or did it happen spuriously?

**Comment by soualid** [comment]
It is consistently reproductible, I can provide you the dataset and the foxx app privately if needed, even if your test case seems to be the exact same as ours.

**Comment by soualid** [comment]
The query is executed inside an `executeTransaction` block.

**Comment by jsteemann** [comment]
Just tried that, but no difference, neither from the ArangoShell nor from within a Foxx app.
Can you post the sharding and the index information for the two collections, i.e. `db.users.properties()` and `db.users.getIndexes()` and `db.isFriendWith.properties()` and `db.isFriendWith.getIndexes()`?
That may show some differences between your and my setup. Additionally, how many coordinators and DB servers are in use in your cluster?
Thanks!

**Comment by soualid** [comment]
We use 2 coordinators and 2 db servers, I'll post you the requested informations asap, thanks !

**Comment by soualid** [comment]
Here are the requested informations, `users` Properties:
```
{ 
  "isSystem" : false, 
  "waitForSync" : false, 
  "shardKeys" : [ 
    "_key" 
  ], 
  "numberOfShards" : 1, 
  "keyOptions" : { 
    "type" : "traditional", 
    "allowUserKeys" : true, 
    "lastValue" : 0 
  }, 
  "replicationFactor" : 1 
}
```

`users` Indexes: 
```
test> db.users.getIndexes()
[ 
  { 
    "fields" : [ 
      "_key" 
    ], 
    "id" : "users/0", 
    "selectivityEstimate" : 1, 
    "sparse" : false, 
    "type" : "primary", 
    "unique" : true 
  }, 
  { 
    "deduplicate" : true, 
    "fields" : [ 
      "nativeIdentity.emailAddress" 
    ], 
    "id" : "users/3016731", 
    "selectivityEstimate" : 1, 
    "sparse" : true, 
    "type" : "hash", 
    "unique" : true 
  }, 
  { 
    "deduplicate" : true, 
    "fields" : [ 
      "facebookIdentity.facebookUserId" 
    ], 
    "id" : "users/3016732", 
    "selectivityEstimate" : 1, 
    "sparse" : true, 
    "type" : "hash", 
    "unique" : true 
  }, 
  { 
    "deduplicate" : true, 
    "fields" : [ 
      "twitterIdentity.twitterUserId" 
    ], 
    "id" : "users/3016733", 
    "selectivityEstimate" : 1, 
    "sparse" : true, 
    "type" : "hash", 
    "unique" : true 
  }, 
  { 
    "deduplicate" : true, 
    "fields" : [ 
      "googleIdentity.googleUserId" 
    ], 
    "id" : "users/3016734", 
    "selectivityEstimate" : 1, 
    "sparse" : true, 
    "type" : "hash", 
    "unique" : true 
  }, 
  { 
    "deduplicate" : true, 
    "fields" : [ 
      "phoneNumber.internationalFormat" 
    ], 
    "id" : "users/3016735", 
    "selectivityEstimate" : 1, 
    "sparse" : true, 
    "type" : "hash", 
    "unique" : true 
  }, 
  { 
    "deduplicate" : true, 
    "fields" : [ 
      "sessions[*].accessToken" 
    ], 
    "id" : "users/3016736", 
    "selectivityEstimate" : 1, 
    "sparse" : true, 
    "type" : "hash", 
    "unique" : false 
  }, 
  { 
    "deduplicate" : true, 
    "fields" : [ 
      "profile.username" 
    ], 
    "id" : "users/3016737", 
    "selectivityEstimate" : 1, 
    "sparse" : false, 
    "type" : "hash", 
    "unique" : true 
  }, 
  { 
    "deduplicate" : true, 
    "fields" : [ 
      "profile.indexedUsername" 
    ], 
    "id" : "users/3016738", 
    "selectivityEstimate" : 1, 
    "sparse" : false, 
    "type" : "skiplist", 
    "unique" : false 
  } 
]
```

`isFriendWith` properties: 
```
{ 
  "isSystem" : false, 
  "waitForSync" : false, 
  "shardKeys" : [ 
    "_key" 
  ], 
  "numberOfShards" : 1, 
  "keyOptions" : { 
    "type" : "traditional", 
    "allowUserKeys" : true, 
    "lastValue" : 0 
  }, 
  "replicationFactor" : 1 
}
```

`isFriendWith` indexes: 
```
[ 
  { 
    "fields" : [ 
      "_key" 
    ], 
    "id" : "isFriendWith/0", 
    "selectivityEstimate" : 1, 
    "sparse" : false, 
    "type" : "primary", 
    "unique" : true 
  }, 
  { 
    "fields" : [ 
      "_from", 
      "_to" 
    ], 
    "id" : "isFriendWith/2", 
    "selectivityEstimate" : 0.5, 
    "sparse" : false, 
    "type" : "edge", 
    "unique" : false 
  } 
]
```

Many thanks !

**Comment by soualid** [comment]
You were right, another query in the transaction block was missing the `WITH` clause, I have been confused by the fact that that stack trace displayed the line where the transaction starts, not the one where the query is issued. Many thanks for the time spent on this.

A great improvement on this could be to display the offending query as it is not pointed out by the line number in the stack trace if it has been executed within a transaction.

Many thanks again.
