### ISSUE TITLE
when i tried to insert new data, ArangoDB returned data for me!

### ISSUE THREAD

**Issue by CengSin** [arangodb/arangodb#4004]
When I tried to insert new data, Eclipse returned data for me, and I couldn't insert new data any more. He would keep repeating this mistake.
![image](https://user-images.githubusercontent.com/23357893/33876374-4cc709a0-df60-11e7-98e9-f430be131ed1.png)

OS: CentOS7
ArangoDB version : 3.2.8
RAM: 4G
amount of data: 30,000,00
Mode: Cluster

**Comment by dothebart** [comment]
Hi, 
4G sounds a little bit to poor for me to run an arango-cluster on? Do you also see this in a single server setup?

**Comment by CengSin** [comment]
emm,So I should increase the memory, is it this?

**Comment by dothebart** [comment]
yes, depending on workload I'd rather have 4g per node at least.

**Comment by CengSin** [comment]
thank you
