### ISSUE TITLE
Arangodb,How to return an isolated point?

### ISSUE THREAD

**Issue by moxiaoyu100** [arangodb/arangodb#4005]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [✔ ] 3.2

Mode:
- [✔ ] Cluster

Storage-Engine:
- [✔ ] rocksdb

On this operating system:
- [✔ ] Linux 

### this is an AQL-related issue:
[✔ ] I'm using graph features

I now have a need, we need to get a single point of data in the data independent, this point no edges, AQL how to write?

**Comment by maxkernbach** [comment]
Hello,

this is a duplicate of https://stackoverflow.com/questions/47769067/how-to-get-isolated-vertices-on-a-graph. Does this answer your question?

**Comment by maxkernbach** [comment]
Closing this issue as solved. The question is answered on stackoverflow.

**Comment by moxiaoyu100** [comment]
ok
