### ISSUE TITLE
How to create a collection of Edge, Use Java-ArangoDB-API-Async

### ISSUE THREAD

**Issue by CengSin** [arangodb/arangodb#4020]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ -] 3.2
- [ ] self-compiled devel branch

Mode:
- [ -] Cluster
- [ ] Single-Server

Storage-Engine:
- [ -] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ -] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [- ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[- ] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [- ] this Driver:

**Comment by mpv1989** [comment]
Hi, you create a edge collection with the same method you create a document collection but with the type `CollectionType.EDGES` set in the options.

```Java
ArangoDBAsync arango = new ArangoDBAsync.Builder().build();
arango.db().createCollection("nameOfEdgeColleciton", new CollectionCreateOptions().type(CollectionType.EDGES));
```

**Comment by CengSin** [comment]
thank you

**Comment by jhariyus** [comment]
How to start

**Comment by CengSin** [comment]
Someone has responded to the answer before .
```
ArangoDBAsync arango = new ArangoDBAsync.Builder().build();
arango.db().createCollection("nameOfEdgeColleciton", new CollectionCreateOptions().type(CollectionType.EDGES));
```

**Comment by jhariyus** [comment]
Open

**Comment by rexsateesh** [comment]
@mpv1989 
I checked ArangoDB documentation there nothing found like this so could you please share the link where can read documentation for Java.

Thanks

**Comment by mpv1989** [comment]
@rexsateesh You can find the Java driver documentation in the [driver repo](https://github.com/arangodb/arangodb-java-driver). There you will find also a link to the [JavaDoc](http://arangodb.github.io/arangodb-java-driver/javadoc-4_3/index.html)

**Comment by rexsateesh** [comment]
Thank you
