### ISSUE TITLE
Error: VPack error: Expecting Object

### ISSUE THREAD

**Issue by jonberthet** [arangodb/arangodb#4044]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2

Mode:
- [x] Single-Server

On this operating system:
- [x] Windows, version: 10

I'm issuing AQL via:
- [x] web interface with this browser:     running on this OS:

I've run this query to input the the jason web token (JWT) into the server as a header in order to return a collection. 

```
`results = requests.put("http://127.0.0.1:8529/_db/database_name/_api/simple/all",
                      params={"collection": "collection_name", "batchSize":1000},
                      headers={"Authorization": str('Bearer ' + Jason_Web_Token)})
results.text
```
Sadly, I get this error:

> u'{"error":true,"errorMessage":"VPack error: Expecting Object (exception location: /var/lib/otherjenkins/workspace/RELEASE__BuildPackages/arangod/GeneralServer/RestHandler.cpp:204). Please report this error to arangodb.com","code":500,"errorNum":4}'

The error message is not saying what it expects to be an object. I've looked within the browser console error messages as well to no avail. Where should I look to debug this?

**Comment by ObiWahn** [comment]
Hi jonberthet,

it looks like you are working with one of the python community-drivers. Please tell me which one and which version you are using. It would be great if you could provide a minimal (not-)working example.

Regards Jan

**Comment by jonberthet** [comment]
I am using the Arango Docker environment found here (https://www.arangodb.com/download-major/).
The 'requests' python package version is 2.18.4 and documentation & examples shown here (http://docs.python-requests.org/en/master/api/). Does this help? Plz let me know if addit'l info is needed.

**Comment by ObiWahn** [comment]
Hi,
if you intend to use ArangoDB and you do not want to implement another python driver, then you should use a existing one like [pyarango](https://github.com/tariqdaouda/pyArango). The request module you linked is for plain http requests. You could use that, but it would be much more complicated to use.

Have a look at our [tutorial](https://www.arangodb.com/tutorials/tutorial-python/)!

**Comment by dothebart** [comment]
Hi @jonberthet ,
I understand that the error message is a bit misleading. Velocypack is also ArangoDBs JSON-Parser library; a JSON object looks like that:

    {
       "foo": "bar"
    }

Please have a look at the documentation of the REST-route you're invoking, either [via the regular HTTP API-Documentation](https://docs.arangodb.com/3.2/HTTP/SimpleQuery/index.html#return-all-documents) or in your ArangoDB Webinterface,
 `Support->Rest API->[Simple Queries]->_api/simple/all` 
for the interactive swagger.io documentation.

Both show you an example about how the request should look, the Swagger one lets you interactively build the request. 

Comparing what you saw there, you can see that that `PUT`-request usually have a POST-Body. In the Request you're sending with that python snippet you're sending a `PUT` request, but the POST-Body is empty:

    PUT /_db/database_name/_api/simple/all?batchSize=1000&collection=collection_name HTTP/1.1
    Content-Length: 0

See the difference?

Usually its a good idea to have `wireshark` or `ngrep` at hand to inspect what some test snippets generate on the wire.

**Comment by jonberthet** [comment]
Hi @dothebart. Thank you for providing some documentation and pointers.

With your help, I was able to get a working request with POST to get the token as such:
  ```
  url = 'http://localhost:8529/_open/auth'
    data = '{"username":"username","password":"password"}'
    headers = {'Content-Type': 'application/json'}
    response = requests.post(url=url, data=data, headers=headers, allow_redirects=True)
    print (response.content)
    print (response['status'])

    # Convert response string into a dictionary
    parsed_json = json.loads(response.content)

    # Extract the jwt value
    auth = str(parsed_json['jwt'])
```
