### ISSUE TITLE
Out of memory in `arangorestore` when no access rights to dump files

### ISSUE THREAD

**Issue by amurchick** [arangodb/arangodb#4045]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2

Mode:
- [x] Single-Server

Storage-Engine:
- [x] mmfiles
- [x] rocksdb

On this operating system:
- [x] Linux 
  - [x] Debian .deb

- [x] arangorestore

These are the steps to reproduce:
1. Try to restore in database
<img width="1025" alt="screen shot 2017-12-15 at 09 39 17" src="https://user-images.githubusercontent.com/1515699/34024308-f214f418-e17b-11e7-9d8c-ad2b27ae0644.png">

Reason: no access rights for catalog with dumps - ./geohelp
If `arangorestore` has access rights to this catalog - all ok.

Can't you fix this - write correct error reason, not "Out of memory"?

**Comment by jsteemann** [comment]
Looks like all exceptions in ArangoRestore are translated to "out of memory".
Potential fix:
```diff
diff --git a/arangosh/Restore/RestoreFeature.cpp b/arangosh/Restore/RestoreFeature.cpp
index 23ac976093..9fe7e1a5d2 100644
--- a/arangosh/Restore/RestoreFeature.cpp
+++ b/arangosh/Restore/RestoreFeature.cpp
@@ -653,6 +653,12 @@ int RestoreFeature::processInputDirectory(std::string& errorMsg) {
         }
       }
     }
+  } catch (basics::Exception const& ex) {
+    errorMsg = ex.what();
+    return ex.code();
+  } catch (std::exception const& ex) {
+    errorMsg = ex.what();
+    return TRI_ERROR_INTERNAL;
   } catch (...) {
     errorMsg = "out of memory";
     return TRI_ERROR_OUT_OF_MEMORY;
```

**Comment by jsteemann** [comment]
Error message adjusted via the above PRs.

**Comment by sleto-it** [comment]
Hi,

Thanks again for opening this ticket. Version 3.2.10 has been released yesterday

I am now closing this ticket. Please feel free to comment if the problem persists

Many thanks,
