### ISSUE TITLE
Executing empty query causes crash

### ISSUE THREAD

**Issue by konsultaner** [arangodb/arangodb#4056]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series: 3.2, Single-Server

Storage-Engine: mmfiles
On this operating system: Win 10

I'm issuing AQL via:
this Driver: Java

These are the steps to reproduce:

    database.query("",new HashMap<>(),null,SomeModel.class);

Executing this code will cause a crash of the whole process. I have to restart the database on my system.

**Comment by jsteemann** [comment]
Confirmed. It seems that this affects the HTTP cursor API, but not the internal db._query() functionality on the server side.

**Comment by sleto-it** [comment]
Hi,

Thanks again for opening this ticket. Version 3.2.10 has been released yesterday

I am now closing this ticket. Please feel free to comment if the problem persists

Many thanks,
