### ISSUE TITLE
Determine weakly connected components of a directed graph

### ISSUE THREAD

**Issue by feitianstyle** [arangodb/arangodb#4062]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2

Mode:
- [x] Cluster

Storage-Engine:
- [x] rocksdb

On this operating system:
- [x] Linux 
  - [x] RedHat .rpm

I have a graph and I want to traverse it to find out all the connected graphs, so that each connected component has its own unique label.

What ideas or what algorithm, so I realize my needs.

**Comment by Simran-B** [comment]
In principle, it is possible with Pregel and the Connected Components algorithm. However, the algorithm is designed for a directed graph.

Edges are always directed in ArangoDB, but they can be followed in either direction (`INBOUND`, `OUTBOUND`) or be treated as undirected (`ANY`) in AQL traversals. The [Pregel algorithm](https://github.com/arangodb/arangodb/blob/devel/arangod/Pregel/Algos/ConnectedComponents.h#L32) follows the edges only in their defined direction and does therefore not give the correct result if the graph is meant as undirected.

For example, if this is your named graph ("cc"):

![pseudoforest](https://user-images.githubusercontent.com/7819991/34084533-aa418e18-e382-11e7-8431-088da1f03a53.png)

Pregel processing started in arangsh:

```js
var handle = pregel.start("connectedcomponents", "cc", {maxGSS: 250, resultField: "component"})
var pregel = require("@arangodb/pregel")
```

If all nodes with the same color are supposed to be in the same community in the end, then it won't work with directed edges:

![image](https://user-images.githubusercontent.com/7819991/34084732-abf2be8c-e385-11e7-896a-503a09a92e0f.png)

If you add a reverse edge for every edge, then it works in my test:

![image](https://user-images.githubusercontent.com/7819991/34084672-dbf77b28-e384-11e7-8f0c-8a8af693cb50.png)

**Comment by feitianstyle** [comment]
If I do not add the opposite side, can the vertices of the same color be divided into one community's needs
@Simran-B  thank your answer

**Comment by Simran-B** [comment]
> If I do not add the opposite side, can the vertices of the same color be divided into one community?

Not with the available Pregel algorithms at the moment it seems. @graetzer?

> Is there any way to group vertices of the same color in a community?

They only have colors for illustration purposes. If they had an attribute `color`, then you wouldn't even need any graph processing. Their color would basically be their group label.

**Comment by feitianstyle** [comment]
My purpose is to add a field,This field has the same value for all vertices in the same community，
The vertices in the community are weakly connected @Simran-B @graetzer

**Comment by feitianstyle** [comment]
I didn't know these communities at first, and I wanted to find them out.And then by adding fields to different communities to distinguish them,Do you have an algorithm that implements what I need?
@Simran-B @graetzer

**Comment by feitianstyle** [comment]
Directed edge can be converted into undirected edge Mody?  @Simran-B

**Comment by Simran-B** [comment]
No. Edges are always directed in ArangoDB. The only current workaround I see is to double edges and swap _from and _to on the copies to simulate an undirected graph for the connected component algorithm.

Awaiting response by @graetzer to feature request (modify algorithm or add another that works on directed graphs as if they were undirected).

**Comment by feitianstyle** [comment]
Then I how to operate to add another direction of the side, the algorithm can be deleted after the addition of the side  @Simran-B

**Comment by feitianstyle** [comment]
Then I how to operate to add another direction of the side it,I want to delete all added edges after the algorithm ends，How can I achieve this? @Simran-B

**Comment by Simran-B** [comment]
AQL query to add flipped edges:

````js
FOR edge IN yourEdgeColl
  INSERT { _from: edge._to, _to: edge._from, helper: true } INTO yourEdgeColl
```

And to delete them again:

```js
FOR edge IN yourEdgeColl
  FILTER edge.helper
  REMOVE edge IN yourEdgeColl
```

Another way would be to INSERT the edges into a second edge collection and extend the graph definition to include as well. Then you can simply delete that separate edge collection later to get rid of the auxiliary edges.

**Comment by feitianstyle** [comment]
I'll try your method right away，Thank you for your answer @Simran-B

**Comment by feitianstyle** [comment]
I have a question to ask you，When I inserted the reverse side, I still continue traversing the edge set，
Will I encounter the newly inserted reverse edge in traversal?
Will result in infinite insertion of the reverse side of this situation?@Simran-B

**Comment by feitianstyle** [comment]
@Simran-B Hi, I tried your method but did not succeed，My side data is as follows:
![image](https://user-images.githubusercontent.com/31272838/34204729-bca745ea-e5ba-11e7-92ed-8df9382e6ded.png)

My reverse side data is as follows:
![image](https://user-images.githubusercontent.com/31272838/34204829-213bb504-e5bb-11e7-9acc-f8159ccef6b0.png)
My vertex data is as follows:
![image](https://user-images.githubusercontent.com/31272838/34204922-750c1976-e5bb-11e7-9189-94921b3aca47.png)

My map is set as follows:
![image](https://user-images.githubusercontent.com/31272838/34205028-c78ee89a-e5bb-11e7-8c72-a8315c40c25b.png)
![image](https://user-images.githubusercontent.com/31272838/34205039-d281cdda-e5bb-11e7-9be0-d80df495db77.png)
This is the statement executed in the shell command:
![image](https://user-images.githubusercontent.com/31272838/34205074-fbed9708-e5bb-11e7-8201-c138ffbd3e7e.png)
This is the set of vertices I got later:
![image](https://user-images.githubusercontent.com/31272838/34205125-2e46a50a-e5bc-11e7-8d2e-d411f9e30109.png)
My edge collection set as follows:
![image](https://user-images.githubusercontent.com/31272838/34205161-523e947c-e5bc-11e7-8cbb-2858baa06469.png)
![image](https://user-images.githubusercontent.com/31272838/34205172-5c6b7fdc-e5bc-11e7-9973-58c5c42dda84.png)
My collection of vertices set as follows:
![image](https://user-images.githubusercontent.com/31272838/34205194-71af7952-e5bc-11e7-97e1-1428391948a2.png)
The resulting graph is as follows:
![image](https://user-images.githubusercontent.com/31272838/34205295-d4a96d06-e5bc-11e7-83e6-24e4f0a8a51f.png)
![image](https://user-images.githubusercontent.com/31272838/34205380-09f8f210-e5bd-11e7-8d5d-693755989777.png)
![image](https://user-images.githubusercontent.com/31272838/34205438-5316e894-e5bd-11e7-9b3a-5da626cc8560.png)
![image](https://user-images.githubusercontent.com/31272838/34205517-ae08b872-e5bd-11e7-9322-cd118274a287.png)
What is the cause of this?
@Simran-B @threez @a2800276 @pekeler @tisba

**Comment by feitianstyle** [comment]
Thank you, the above problem I solved a bit，A set of my vertices, there are 1.9 billion vertices,
I have an edge set with 15 billion edges,I created a reverse set of edges,I use this algorithm, how can I monitor it running time,How much resources does it consume?@ Simran-B

**Comment by Simran-B** [comment]
I tried v3.3.0 with the same graph definition, with a single server instance however.

testv:

```json
[{"_key":"6014c5cac3424d8386dac12c46017c03","host_name":"Salih Tektase"},
{"_key":"6014c5ccca5b4cae893257bf86f0ead0","host_name":"Aditya Bramhan"},
{"_key":"6014c5c80177417fbfd0faf9d5fb31a4","host_name":"Ica palya"},
{"_key":"6014c5c891e54e4a8903cd306d55eb26","host_name":"null"},
{"_key":"6014c5c8f29d426686d6c30152a01459","host_name":"Boanny Patel"},
{"_key":"6014c5ccd2484a4581137ab8aa245ba7","host_name":"El Chapo"},
{"_key":"6014c5c8f1cb47ff886dd1991d19e59d","host_name":"Andrej Altuchov"},
{"_key":"6014c5dd17b54eda83e02e8dd913dba0","host_name":"Maria"},
{"_key":"6014c5e78bfd4051a421bd6adf017e56","host_name":"null"},
{"_key":"6014c5f1c88e40a6a1aa88da08d7c404","host_name":"Aaron Villaflor"}]
```

teste:

```json
[{"_key":"2716265062","_from":"testv/6014c5ccca5b4cae893257bf86f0ead0","_to":"testv/6014c5cac3424d8386dac12c46017c03"},
{"_key":"2716265063","_from":"testv/6014c5c80177417fbfd0faf9d5fb31a4","_to":"testv/6014c5cac3424d8386dac12c46017c03"},
{"_key":"2716265064","_from":"testv/6014c5ccd2484a4581137ab8aa245ba7","_to":"testv/6014c5c8f29d426686d6c30152a01459"},
{"_key":"2716265065","_from":"testv/6014c5e78bfd4051a421bd6adf017e56","_to":"testv/6014c5dd17b54eda83e02e8dd913dba0"},
{"_key":"2716265066","_from":"testv/6014c5f1c88e40a6a1aa88da08d7c404","_to":"testv/6014c5dd17b54eda83e02e8dd913dba0"},
{"_key":"2716265067","_from":"testv/6014c5c8f29d426686d6c30152a01459","_to":"testv/6014c5c891e54e4a8903cd306d55eb26"},
{"_key":"2716265068","_from":"testv/6014c5c891e54e4a8903cd306d55eb26","_to":"testv/6014c5ccd2484a4581137ab8aa245ba7"},
{"_key":"2716265069","_from":"testv/6014c5c8f1cb47ff886dd1991d19e59d","_to":"testv/6014c5e78bfd4051a421bd6adf017e56"}]
```

teste2:

```json
[{"_key":"3016636","_from":"testv/6014c5cac3424d8386dac12c46017c03","_to":"testv/6014c5ccca5b4cae893257bf86f0ead0"},
{"_key":"3016637","_from":"testv/6014c5cac3424d8386dac12c46017c03","_to":"testv/6014c5c80177417fbfd0faf9d5fb31a4"},
{"_key":"3016639","_from":"testv/6014c5dd17b54eda83e02e8dd913dba0","_to":"testv/6014c5e78bfd4051a421bd6adf017e56"},
{"_key":"3016641","_from":"testv/6014c5c891e54e4a8903cd306d55eb26","_to":"testv/6014c5c8f29d426686d6c30152a01459"},
{"_key":"3016638","_from":"testv/6014c5c8f29d426686d6c30152a01459","_to":"testv/6014c5ccd2484a4581137ab8aa245ba7"},
{"_key":"3016640","_from":"testv/6014c5dd17b54eda83e02e8dd913dba0","_to":"testv/6014c5f1c88e40a6a1aa88da08d7c404"},
{"_key":"3016642","_from":"testv/6014c5ccd2484a4581137ab8aa245ba7","_to":"testv/6014c5c891e54e4a8903cd306d55eb26"},
{"_key":"3016643","_from":"testv/6014c5e78bfd4051a421bd6adf017e56","_to":"testv/6014c5c8f1cb47ff886dd1991d19e59d"}]
```
![image](https://user-images.githubusercontent.com/7819991/34296120-4588b22a-e711-11e7-9068-0125cf018dee.png)

The result is correct. Could be a cluster problem.

You can periodically check the status with `pregel.status(id)`. The `id` is returned by `start()`.

I don't know how/if the required resources can be estimated. Maybe @graetzer can answer this once he's back from holidays.

**Comment by feitianstyle** [comment]
Thanks, I got the correct result with a small amount of data，But when I use my real data, there is a server downtime,so I had to restart my server.I checked the reason, the report said the memory is locked，Hope you guys can help me, the great arangodb team。

**Comment by Simran-B** [comment]
In v3.7, a new Pregel algorithm `wcc` for finding Weakly Connected Components was added:

https://www.arangodb.com/docs/stable/release-notes-new-features37.html#pregel
