### ISSUE TITLE
ER: documentation about UDFs

### ISSUE THREAD

**Issue by pkoppstein** [arangodb/arangodb#4068]
The AQL documentation on UDFs states (rather ominously):

 >  User functions should be kept purely functional and thus free of side effects and state, and state modification.

Does this mean: "purely functional with respect to the input arguments" or "purely functional with respect to the input arguments and the state of the database when the transaction begins"?

If the former, what happens if, for example, the UDF accesses and returns a value that does depend on the database?  Consider for example, a UDF which returns a value as follows:

    return db._query('RETURN LENGTH(' + collection + ')').toArray()[0];

where `collection` is the string-name of an existing collection.

**Comment by dothebart** [comment]
Hi, 
you should rather use https://docs.arangodb.com/3.2/AQL/Functions/Miscellaneous.html#collectioncount to fill that count into a parameter to your UDF. 

You should see your UDF like being stateless for each document it sees.

**Comment by Simran-B** [comment]
Some example what **not** to do in a UDF:

- Create or modify global variables
- Modify arguments passed to the function (if they are passed "by reference")
- Define anything that survives the scope of the UDF (like creating properties on the function object itself)

In a nutshell: in your UDF code, define everything you need inside the function and only modify what you defined yourself. Do not touch anything beyond the scope of the function.

**Comment by pkoppstein** [comment]
Thanks for the response. Please understand the example was just that - an example of a UDF that does examine the state of the database, and that under certain circumstances at least, dies produce rhe expected/“correct” result. The request therefore is for enhanced documentation regarding the precise semantics of such functions.

**Comment by Simran-B** [comment]
Fetching the document count of a collection could be seen like accessing a global variable I guess. UDFs are not transactions and should not access the database at all in my understanding.

**Comment by pkoppstein** [comment]
@Simran-B - The documentation is quite clear about when collections are locked, so it should follow that if a UDF accesses “locked” values, the values should be as expected (and as observed when contention is not an issue). 

Simply saying the behavior is “undefined” is highly unsatisfactory - it largely contradicts the existing documentation, and more importantly greatly diminishes UDFs and therefore also AQL (in the absence of a much larger library of pre-defined AQL functions).

**Comment by dothebart** [comment]
meanwhile the documentation has been updated. 
ArangoDB 3.7 is available for Download; closing this as solved. 
please see https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/ for details.
