### ISSUE TITLE
Missing logs in logfile

### ISSUE THREAD

**Issue by denya133** [arangodb/arangodb#4073]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [*] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [*] Single-Server

Storage-Engine:
- [*] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [*] Linux 
  - [ ] Debian .deb
  - [*] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an usage-related issue:
Brakes are observed when processing requests at the beginning of the second week of use. I associate this with the fact that the server can not write logs to the logfile. Size of `/var/log/arangodb3/arangod.log` file 0 bite, but logs in web-interface are exist.
I think it relates with "logroate" because logrotate config in `/etc/logrotate.d/arangodb3`
```
/var/log/arangodb3/arangod.log {
     rotate 12
     weekly
     compress
     delaycompress
     create 640  arangodb adm
     postrotate
     /etc/init.d/arangodb3 reload-log > /dev/null
     endscript
     }
```

I temporarily replaced "reload-log" with "restart" and this solved the problem of missing logs, but restarting the server takes a long time.
I think it relates with 034deae commit and #2355

**Comment by dothebart** [comment]
This may be related to #3634 - usually the SIG_HUB should also flush the logging to the respective logfile.

**Comment by dothebart** [comment]
Small hint: 
during your researches of the logging and docker we saw that doing an `log.error()` would flush the logfile. If you want a workaround for now, you may write a tiny foxx app that does this, and invoke it by cron.

**Comment by dothebart** [comment]
adding  `|| level == LogLevel::INFO` [LogAppenderFile.cpp to Line 254 ](https://github.com/arangodb/arangodb/blob/devel/lib/Logger/LogAppenderFile.cpp#L254) makes this work.

**Comment by dothebart** [comment]
This is working again with the latest docker containers available for download - closing.
