### ISSUE TITLE
Skiplist index is not used

### ISSUE THREAD

**Issue by irriss** [arangodb/arangodb#4076]
Following this topic on stackoverflow https://stackoverflow.com/questions/47864788/vertex-centric-indexes-for-sorting

It seems that there is no way to make such query efficient 

`            FOR v, e in outbound @start Collection
                    SORT e.points DESC 
                    limit 0, 10
                    RETURN whatever`

Current implementation always goes through all edges of the vertex and in case of supernode it leads to very poor performance

**Comment by irriss** [comment]
Hi guys,

is there any ETA or workaround for it? It becomes critical for our project

**Comment by irriss** [comment]
I did a few experiments and found a workaround 

I used this setup:
`db._create('Node')
db._createEdgeCollection('Collection')

db.Collection.insert({ _from: 'Node/1', _to: 'Node/10' ,  points: 10 });
db.Collection.insert({ _from: 'Node/1', _to: 'Node/10' ,  points: 11 });
db.Collection.insert({ _from: 'Node/1', _to: 'Node/10' ,  points: 12 });
db.Collection.insert({ _from: 'Node/1', _to: 'Node/10' ,  points: 13 });
db.Collection.insert({ _from: 'Node/1', _to: 'Node/10' ,  points: 14 });
db.Collection.insert({ _from: 'Node/1', _to: 'Node/10' ,  points: 15 });
db.Collection.insert({ _from: 'Node/1', _to: 'Node/10' ,  points: 16 });
db.Collection.insert({ _from: 'Node/1', _to: 'Node/10' ,  points: 17 });
db.Collection.insert({ _from: 'Node/1', _to: 'Node/10' ,  points: 18 });
db.Collection.insert({ _from: 'Node/1', _to: 'Node/10' ,  points: 19 });

db.Node.insert({ _id: 'Node/1' });

db.Collection.ensureIndex({ type: "skiplist", fields: [ "_from", "points" ] })
`

this query uses the index:
` for u2m in Collection
    filter u2m._from == 'Node/1'
    sort u2m.points desc
    limit 0, 10
    return u2m
`

`Query string:
  for u2m in Collection
     filter u2m._from == 'Node/1'
     sort u2m.points desc
     limit 0, 10
     return u2m

Execution plan:
 Id   NodeType          Est.   Comment
  1   SingletonNode        1   * ROOT
  9   IndexNode           10     - FOR u2m IN Collection   /* edge index scan */
  5   CalculationNode     10       - LET #3 = u2m.`points`   /* attribute expression */   /* collections used: u2m : Collection */
  6   SortNode            10       - SORT #3 DESC
  7   LimitNode           10       - LIMIT 0, 10
  8   ReturnNode          10       - RETURN u2m

Indexes used:
 By   Type   Collection   Unique   Sparse   Selectivity   Fields        Ranges
  9   edge   Collection   false    false        10.00 %   [ `_from` ]   (u2m.`_from` == "Node/1")

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   move-calculations-up-2
  4   move-filters-up-2
  5   use-indexes
  6   remove-filter-covered-by-index
  7   remove-unnecessary-calculations-2
`

however if you make the index sparse then index will not be used even if after adding u2m.points>null

`Query string:
  for u2m in Collection
     filter u2m._from == 'Node/1'
     sort u2m.points desc
     limit 0, 10
     return u2m

Execution plan:
 Id   NodeType          Est.   Comment
  1   SingletonNode        1   * ROOT
  9   IndexNode           10     - FOR u2m IN Collection   /* edge index scan */
  5   CalculationNode     10       - LET #3 = u2m.`points`   /* attribute expression */   /* collections used: u2m : Collection */
  6   SortNode            10       - SORT #3 DESC
  7   LimitNode           10       - LIMIT 0, 10
  8   ReturnNode          10       - RETURN u2m

Indexes used:
 By   Type   Collection   Unique   Sparse   Selectivity   Fields        Ranges
  9   edge   Collection   false    false        10.00 %   [ `_from` ]   (u2m.`_from` == "Node/1")

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   move-calculations-up-2
  4   move-filters-up-2
  5   use-indexes
  6   remove-filter-covered-by-index
  7   remove-unnecessary-calculations-2
`

I could not make index working with traversal syntax of the query

**Comment by dothebart** [comment]
Hi, 
there is no way to make this work in the traverser. There may be theoretical cases to add a shortcut here in the traverser, but this should not be here in a general purpose engine. 
However, Traversals gain their power when doing random iteration depths, so there is no real use in using the traverser over a regular join here in first place. 

As you found out it can work done manually by using non-sparse indices; however, sparse indices only contain documents containing attributes; thus they can't be used for filter condition where the optimizer can't predict the index fullfills his conditions. The optimizer has currently little understanding about `!= null` statements, thus it won't choose the sparse index.

**Comment by irriss** [comment]
Thanks. It is clear now. Probably worth mentioning it in the documentation.

Another issue is that documentation https://docs.arangodb.com/3.1/Manual/Indexing/VertexCentric.html states that Vertex Centric Index is used and during pattern matching queries:

FOR v, e, p IN 3..5 OUTBOUND @start GRAPH @graphName
  FILTER p.edges[*].type ALL == "friend"
  RETURN v

However, I could not make it working even for the example from the documentation. 

What could be a problem here?

**Comment by maxkernbach** [comment]
Hi @irriss,

can you describe which problem you had when trying the example from the documentation? I just tested it with 3.3.3 on Ubuntu. 

> AQL optimizer can decide to use a vertex-centric whenever suitable, however it is not guaranteed that this index is used, the optimizer may estimate that an other index is assumed to be better

When using the example graph `social` with 4 vertices and 4 edges, the Vertex Centric Index was not used. Instead the edge index was used. Once i inserted a few thousand edges though and ran the queries again the created Vertex Centric Index (in this case a Hash Index) was used as expected.

**Comment by maxkernbach** [comment]
I am closing this issue for now as the example from the documentation worked and we have not received any feedback for a month.

Please feel free to comment and reopen in case you are still facing a problem.
