### ISSUE TITLE
 How to weaken the connection component

### ISSUE THREAD

**Issue by feitianstyle** [arangodb/arangodb#4099]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2

Mode:
- [x] Cluster

Storage-Engine:
- [x] rocksdb

On this operating system:
- [x] Linux 
  - [x] RedHat .rpm

I want to add a counter when traversing the graph

```
for x in mycollection
    for v,e,p in 1..1 any x._id graph'mygraph'
        return v
```

I want to add a counter after traversing the collection，I want to go through the graph counter after traversal plus 1.

```
let count=1
for x in mycollection
    for v,e,p in 1..1 any x._id graph'mygraph'
        return v
 count++
```

I am not interested in the length of the collection, I just want to traverse the graph after each, the counter is added 1

I wrote two unfinished js files，
In fact, I was trying to figure out the weak connected component in my graph，code show as below

```js
'use strict';
function connectionGraph(vertex,count1,collection,graphName) {
     var db = require('@arangodb').db;
	
          var q2 =  "        for v,e,p in 1..1 any @vt._id graph @graph \n" +
				    "			 update x with{label:@count} in @@ttv \n" +
                    "            filter v.label!=@count \n" +
                    "                 return MYFUNCTION::dfs(v,@count,@@ttv)";
	 var param = {vt:vertex,count:count1,@ttv:collection,graph:graphName}
	 
	 db._query(q2,param);
}

module.exports = connectionGraph;
```

```js
'use strict';
function connection(c,collection,graphName) {
     var db = require('@arangodb').db;
	 int c = 1;
	 var query = "for x in @@tv \n" 
                    "for v,e,p in 1..1 any x._id graph @graph \n" +
					"	  update x with{label:@count} in @@tv \n" +
                    "     filter v.label!=@count \n" +
                    "     return MYFUNCTION::dfs(v,@count,@@collection,@graph)";
	 var param = {count:c,@tv:collection,graph:graphName};
	 db._query(query,param);
}
module.exports = connection;
```

I do not know how to write, can you help me?
I just wanted to find the weakly connected component of a graph.

**Comment by maxkernbach** [comment]
An algorithm named "connected components" to find weakly connected components in a graph is available for ArangoDB.
It can be executed with:
```
var pregel = require("@arangodb/pregel");
pregel.start("connectedcomponents", "graphname")
```
The algorithm is documented at:
https://docs.arangodb.com/3.2/Manual/Graphs/Pregel/#connected-components

**Comment by feitianstyle** [comment]
I used that algorithm，But it didn't get the right result，It is affected by the direction.You can look at this websit:  https://github.com/arangodb/arangodb/issues/4062

**Comment by Simran-B** [comment]
Closing this issue in favor of #4062.
