### ISSUE TITLE
ERROR:  lonely VERTEX

### ISSUE THREAD

**Issue by moxiaoyu100** [arangodb/arangodb#4109]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [✔ ] 3.2
- [ ] self-compiled devel branch

Mode:
- [✔ ] Cluster
- [ ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [✔ ] rocksdb

On this operating system:
- [✔ ] Linux 
  - [✔ ] RedHat .rpm

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [✔ ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

AQL:

```js
    FOR u IN @@collection
        LET friendList = (
            FOR f IN @@relagion
            FILTER f._from == u._id
            RETURN 1
      )
  FILTER LENGTH(friendList) == 0
  RETURN { "user" : u }
```

ERROR:

> Query: Expecting item (while executing) (exception location: /var/lib/jenkins/workspace/RELEASE__BuildPackages/arangod/RestHandler/RestCursorHandler.cpp:130). Please report this error to arangodb.com

**Comment by Simran-B** [comment]
@moxiaoyu100 does the issue no longer occur in the latest version?
