### ISSUE TITLE
Assertion Error [ERR_ASSERTION]: undefined == '595783'

### ISSUE THREAD

**Issue by yuvanesh10** [arangodb/arangodb#4112]
Trying out edge collections..can someone help me with it

```js
// ## Assigning the values
const arangojs = require('arangojs');
const aqlQuery = arangojs.aqlQuery;
const now = Date.now();

// ## Const variables for connecting to ArangoDB database
const host = '192.100.00.000'
const port = '8529'
const username = 'xyz'
const password = 'XYZ'
const path = '/_db/sgcdm_app/_api/'
const database = 'sgcdm_app'

// ## Connection to ArangoDB
db = new arangojs.Database({
    url: `http://${host}:${port}`,
    databaseName: database
});
db.useBasicAuth(username, password);

// ## Working with EDGES
const collection = db.edgeCollection('included_in');
const edge = collection.edge('included_in/595783');
const assert = require('assert');

// the edge exists
assert.equal(edge._key, '595783');
assert.equal(edge._id, 'included_in/595783');
console.log(db);
```

```
ERROR: 
assert.js:42
  throw new errors.AssertionError({
  ^
AssertionError [ERR_ASSERTION]: undefined == '595783'
 at Object.<anonymous> (/home/balakrishnan/node/edge.js:39:8)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by yuvanesh10** [comment]
@Simran-B  
I was searching for some similar solutions but most of them deals with mongodb..there are like one or two for arangodb

**Comment by maxkernbach** [comment]
Referencing stackoverflow as the same issue was opened at:
https://stackoverflow.com/questions/47907011/arangodb-working-with-edge-getting-assertion-error-edge-key-equal

**Comment by yuvanesh10** [comment]
@maxkernbach I posted in stackoverflow too..,to get a few response

**Comment by Simran-B** [comment]
As documented, `edgeCollection.edge()` is asynchronous: https://github.com/arangodb/arangojs#edgecollectionedge

It returns a Promise, not an edge:

```js
collection.edge('included_in/595783');

Promise {
  <pending>,
  domain:
   Domain {
     domain: null,
     _events: { error: [Function: debugDomainError] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] } }
```

You have to `await` the result or use `then()` to do something with the result as soon as it becomes available.

```js
collection.edge('included_in/595783').then(res => console.log("Key: " + res._key));

Key: 595783
```

**Comment by yuvanesh10** [comment]
@Simran-B  even it is not returning a promise..Just throwing a error at the disposal

**Comment by yuvanesh10** [comment]
@Simran-B how can we return the documents or individual vertex in the edge document ?? can you shed some light on it !!

**Comment by Simran-B** [comment]
Your assertion is `assert.equal(edge._key, '595783');`, and it fails because `undefined == '595783'`.

`edge` can very well be (and should be) a Promise. A promise does not have a property `_key` however. Therefore the assertion error.

> how can we return the documents or individual vertex in the edge document ?

Not sure what you are asking. The edge document is returned when the Promise is fulfilled. It does not return vertex documents referenced in `_from` and `_to`. You either have to request these documents by ID, or use an AQL traversal query to start from some vertex, follow edges and optionally return the full path (3rd variable emitted by the traversal FOR language construct).

**Comment by yuvanesh10** [comment]
@Simran-B  sorry that i didnt pharse it properly. I meant to return the all the document ids in a single edge collection.

actually i tried to use ''import''..,it returns with a promise but also with few errors

collection.import([
  ['_key', '_from', '_to'],
  ['595783', 'mod/595575', 'dev/592149']
]);
const edges = collection.edges('mod/595575');
collection.edges('mod/595575').then(res => console.log(edges));

(node:26021) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ArangoError: expecting a valid JSON array in the request. got: Expecting EOF
(node:26021) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Promise {
  [ { _key: '595783',
    _id: 'included_in/595783',
    _from: 'mod/595575',
    _to: 'dev/592149',
    _rev: '_WFLTEc6---',
    'Soest,germany': 'FH-SWF' } ] }

**Comment by Simran-B** [comment]
> I meant to return the all the document ids in a single edge collection.

Edge collections are not much different from vertex collections. You can retrieve all (edge) document IDs in the same way. Here is an example that prints all `_id` attributes to the console:

```js
const arangojs = require('arangojs');
const aqlQuery = arangojs.aqlQuery;

// Const variables for connecting to ArangoDB database
const host = '127.0.0.1'
const port = '8529'
const username = 'root' // default user
const password = '' // blank password by default
const database = '_system' // default database

 // Connection to ArangoDB
db = new arangojs.Database({
    url: `http://${host}:${port}`,
    databaseName: database
});
db.useBasicAuth(username, password); // authenticate

db.query(aqlQuery`
  FOR doc IN included_in
    RETURN doc._id
`).then(
  cursor => cursor.each(docId => console.log(docId)),
  err => console.error('Query failed:\n', err.response.body)
);
```

Regarding your other issue with import, I'm not sure yet where the problem originates. If the data supplied to the import function is an array of arrays like in the docs, it fails. If it's an array of objects, it works fine:

```js
collection.import([
  { _key: '595783', _from: 'mod/595575', _to: 'dev/592149' }
], { details: true }).then(
  res => { console.log("Import results:", res) },
  err => { console.log("Import error:", err) }
);
collection.edges('mod/595575').then(
  res => console.log(res)
);
```

**Comment by terry124** [comment]
Good job good work please send me your contact email from each team member to get a personal thanks...I I wanted to say very job  Good work

**Comment by dothebart** [comment]
@yuvanesh10 does that answer your question? can we close this issue?

**Comment by yuvanesh10** [comment]
@dothebart oh sorry..,i forgot !! yes indeed
