### ISSUE TITLE
Add index naming

### ISSUE THREAD

**Issue by virmundi** [arangodb/arangodb#4119]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2

Mode:
- [x] Single-Server

Storage-Engine:
- [x] rocksdb

On this operating system:
- [ ] Linux 
  - [x] Ubuntu .deb

When I create an index via the go driver, but this is true for any other driver, I can't specify an index name. If I want to progamatically delete an index, I have no way to correlate the indexes, which are just names to a set of fields and an index type. Creating an index should take a optional name. Or at least return the fields and index type. I don't think I can have two hash indexes on the same fields for the same collection (at least I don't think that makes any sense).

**Comment by danielhlarkin** [comment]
We have added index naming to the upcoming 3.5 release. You can try out one of our (non-production) [release candidates](https://www.arangodb.com/download-technical-preview/) and you can find the details documented [here](https://www.arangodb.com/docs/devel/indexing-working-with-indexes.html).
