### ISSUE TITLE
Arango java API

### ISSUE THREAD

**Issue by feitianstyle** [arangodb/arangodb#4127]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [* ] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [ ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [ *] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ *] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ *] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

I use the use of javaAPI upload data sometimes wrong，The mistake is as follows:
![image](https://user-images.githubusercontent.com/31272838/34253492-cd66aa06-e682-11e7-93e5-0b033b0e2a86.png)

The method I use is as follows:
![image](https://user-images.githubusercontent.com/31272838/34253524-f4423596-e682-11e7-9825-13014d7657a0.png)

Each time I put documents into the number of objects 500000，I have three servers, and my memory per server is 254G,I use a distributed iteration diagram,and I'm using non-smart graphs,so I can not customize the key,The method I use is as follows:
![image](https://user-images.githubusercontent.com/31272838/34253868-5f4db206-e684-11e7-8fc1-47f48d28424a.png)

My data is still uploading while the cluster is down internally,When the data in the documents passed in half,at this time if the error within the cluster, my data is repeated，I do not want to repeat the data, what is the solution to this problem?Or is there any way to delete some of the data just uploaded from the collection,the premise is that I do not customize the key,And keep the transmission is not interrupted.
Can anyone help me? Thank you

**Comment by dothebart** [comment]
Hi, 
a possible solution for your problem could be to add a throttling to your program, or reduce the chunk size.

**Comment by dothebart** [comment]
@feitianstyle have you been able to adjust the throughput to your system? can we close this issue?

**Comment by maxkernbach** [comment]
Hi @feitianstyle,

i am closing this issue for now as we have not received any feedback for a few months.
Please feel free to reopen this issue and comment in case your problem persists.
