### ISSUE TITLE
Web UI not showing the true status of wait for sync.

### ISSUE THREAD

**Issue by virmundi** [arangodb/arangodb#4152]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [X ] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [ X] Single-Server

Storage-Engine:
- [ ] mmfiles
- [ X] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ X] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [X ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) Login to non-_system DB
2) Pick a collection that is known to have WaitForSync = true from a programmatic creation.
3) Go to collection settings page.
4) WaitForSync says No.
5) Use arangosh to get the same collection properties, which say WaitForSync = true.

The following problem occurs: [Screenshot?] 
![waitforsyncno](https://user-images.githubusercontent.com/1041487/34302639-c4f485d2-e6ff-11e7-8a68-44c3d3238c3d.png)
![waitforsyncetrue](https://user-images.githubusercontent.com/1041487/34302658-d528618a-e6ff-11e7-9584-4b96809ff4fd.png)

Instead I would be expecting: 
Both the Web and the Terminal views to say true.

While I doubt it matters, I made the collection using the go-driver.

**Comment by hkernbach** [comment]
It looks like you are comparing two different collections. 

I. Screenshot: Collection "recipes" ID is *103297*
II. Shell: Collection "recipes" ID is *102510*

Could that be possible? Additionally, you could check what the properties API is returning for the collection via e.g. a browser's inspector (see attached screenshot). Shell and UI are using the same API, so it is very unlikely that they deliver different information. 

![image](https://user-images.githubusercontent.com/1244163/34303112-47c8a6ee-e734-11e7-850d-2d4af30806e9.png)

**Comment by virmundi** [comment]
No, they're the same. I think the screen shot difference just comes down to different runs of my migration. When I migrate I delete the whole database and start again. I know for a fact that migration code sets wait to true. When I go into the UI, it doesn't reflect that.

Now one difference from yours vs mine is that I'm using Rocks. Is Wait not a pass through?

**Comment by hkernbach** [comment]
@virmundi thank you very much for spotting. This is indeed a UI bug (API results are equal). This was caused because of the different storage engine. Will provide bugfixes for 3.3/3.2 and devel.

**Comment by hkernbach** [comment]
PRs added:
https://github.com/arangodb/arangodb/pull/4153
https://github.com/arangodb/arangodb/pull/4154
https://github.com/arangodb/arangodb/pull/4155

**Comment by hkernbach** [comment]
Will be available in 3.3.1+ and 3.2.11+

**Comment by virmundi** [comment]
See, this is why I like Arango: great team. Should I close this?

**Comment by hkernbach** [comment]
No, please leave it open. We will close this issue after this bugfix is included in the next available release(s). Thanks again!

**Comment by aterry1** [comment]
Thanks

**Comment by maxkernbach** [comment]
@virmundi version 3.3.2 that includes the fix has been released.

**Comment by maxkernbach** [comment]
Version 3.2.11 has been released and includes the fix for the problem you reported.
Please reopen this issue if the problem still occurs.

Thanks
