### ISSUE TITLE
ArangoDB cluster Error

### ISSUE THREAD

**Issue by CengSin** [arangodb/arangodb#4163]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [x] 3.2
- [ ] self-compiled devel branch

Mode:
- [x] Cluster
- [ ] Single-Server

Storage-Engine:
- [x] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [x] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click to ...
...

When I try to start the database as a cluster, there are always two nodes in the database with port 8530 reporting errors, and then the entire cluster crashes

![image](https://user-images.githubusercontent.com/23357893/34348080-1675bdf4-ea43-11e7-8e89-788af5d2e76a.png)

![image](https://user-images.githubusercontent.com/23357893/34348085-1fabe2c2-ea43-11e7-82ea-d046b47a40aa.png)

![image](https://user-images.githubusercontent.com/23357893/34348089-296301c4-ea43-11e7-83bf-141e85a6494b.png)

**Comment by moxiaoyu100** [comment]
你的配置文件都是怎么写的？

**Comment by CengSin** [comment]
![image](https://user-images.githubusercontent.com/23357893/34368714-f74a17f0-eaf0-11e7-8941-ed24a8a06a7d.png)

**Comment by moxiaoyu100** [comment]
要不，你加我qq：17562849

**Comment by dothebart** [comment]
@moxiaoyu100 @CengSin please note that other users may also find this issue via google etc and may want to learn from your findings. 
If you use chinese in discussions, please provide an english version alongside.

**Comment by Simran-B** [comment]
Is `tcp://[::]:8529` a valid endpoint?

Shouldn't it be `tcp://[::/0]:8529` for the IPv6 equivalent of 0.0.0.0 or `tcp://[::1]:8529` as IPv6 version of 127.0.0.1?
