### ISSUE TITLE
Arangodb - How to delete repeated broken nodes？

### ISSUE THREAD

**Issue by CengSin** [arangodb/arangodb#4168]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [x] 3.2
- [ ] self-compiled devel branch

Mode:
- [x] Cluster
- [ ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [x] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser:     running on this OS:
- [x] arangosh
- [x] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click to ...
...

How to delete repeated broken nodes？

How to use the shell command to delete a node in a cluster?

I hope someone can help me，thanks

![image](https://user-images.githubusercontent.com/23357893/34400145-5f9dffbe-ebc9-11e7-8b83-bdb167f20458.png)

**Comment by maxkernbach** [comment]
Hello,

it is possible to delete a node either with the UI clicking the trash icon next to the name of the Coordinator/DB Server or using the API.

When using the API the following steps have to be executed: 
Identify the `SERVER_ID` of the node that has to be removed. You can do it by calling this API on another coordinator:
```
http://coordinator-ip/_db/_system/_admin/cluster/health
```
When the node is not running the 'CanBeDeleted' flag is set to true.  Once the node that has to be removed is identified, you can call 
```
http://coordinator-ip/_admin/cluster/removeServer
```
passing the `SERVER_ID`.

The following picture shows an example using a POST request with the tool Postman.

![postmanexample](https://user-images.githubusercontent.com/9152640/34684502-923ae394-f4a5-11e7-8c60-7be96093529a.png)

**Comment by maxkernbach** [comment]
Hi @CengSin,

did the latest comment help, can we close this issue?

**Comment by maxkernbach** [comment]
Closing this issue for now because we have not received any feedback. Please reopen if you have any further questions.

Thanks

**Comment by juriku** [comment]
simple loop can be run after coordinator start:

```for failed_id in $(curl http://coordinator:PORT/_db/_system/_admin/cluster/health | jq '.Health | to_entries[] | select (.value.CanBeDeleted==true) | select (.value.Status=="FAILED") | select (.value.Role=="Coordinator") | [.key] | .[]') ; do echo " deleting failed coordinator $failed_id" ; curl http://coordinator:PORT/_admin/cluster/removeServer -d ${failed_id} ; done```

will remove all deleted coordinator nodes that are hanging after restart

**Comment by prasad8686588599** [comment]
Hello,

we have faced some issue with one of the arangoDB Node, so we took the snapshot re-created the new node and joined in the cluster and terminated the previous arangoDB Node, but we are not able delete the DB server from the console.
Can you please help me on this.
Please find the screenshot for your reference.
  
![image](https://user-images.githubusercontent.com/59645553/71969620-0a8ab100-322d-11ea-836f-aff9134efbf9.png)

**Comment by juriku** [comment]
> Hello,
> 
> we have faced some issue with one of the arangoDB Node, so we took the snapshot re-created the new node and joined in the cluster and terminated the previous arangoDB Node, but we are not able delete the DB server from the console.
> Can you please help me on this.
> Please find the screenshot for your reference.
> 
> ![image](https://user-images.githubusercontent.com/59645553/71969620-0a8ab100-322d-11ea-836f-aff9134efbf9.png)

You can automatically remove old node with the code in the last post.
I've put it in the following way in statefulset:
```        lifecycle:
          postStart:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - sleep 10 ; for failed_id in $(curl http://{{ $.Release.Name }}-{{ $componentName }}:{{ $component.servicePorts.tcp }}/_db/_system/_admin/cluster/health | jq '.Health | to_entries[] | select (.value.CanBeDeleted==true) | select (.value.Status=="FAILED") | select (.value.Role=="Coordinator") | [.key] | .[]') ; do echo " deleting failed coordinator $failed_id" ; curl http://{{ $.Release.Name }}-{{ $componentName }}:{{ $component.servicePorts.tcp }}/_admin/cluster/removeServer -d ${failed_id} ; done```

**Comment by prasad8686588599** [comment]
where we need to run the query, we have already terminated the old node

**Comment by juriku** [comment]
> where we need to run the query, we have already terminated the old node

after coordinator starts, depending how you start it.
