### ISSUE TITLE
Query:AQL:invalid TraverserEngineld

### ISSUE THREAD

**Issue by moxiaoyu100** [arangodb/arangodb#4169]
Hi, What's wrong??
![image](https://user-images.githubusercontent.com/34149942/34378241-d7157ac6-eb2f-11e7-8bdb-019131acd4b9.png)

**Comment by maxkernbach** [comment]
Hello,
can you describe the steps you executed in order to reproduce this error?

**Comment by moxiaoyu100** [comment]
hi，I'm sorry！this question forget，i forgot save。
