### ISSUE TITLE
Waiting for collection data to be obtained

### ISSUE THREAD

**Issue by CengSin** [arangodb/arangodb#4179]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [x] 3.2
- [ ] self-compiled devel branch

Mode:
- [x] Cluster
- [ ] Single-Server

Storage-Engine:
- [x] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [x] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

##### When web Interface has been waiting for collection data, the data will never be displayed, and how should this be solved? thanks

![123](https://user-images.githubusercontent.com/23357893/34429398-a907c292-ec92-11e7-94f6-d991a5c64a9b.png)

**Comment by jsteemann** [comment]
This is known to happen when accessing a collection with many documents. Using the web interface to list the documents in the collection will first load the collection data into memory, and populate all the in-memory indexes of the collection. This will take time proportional to the number of documents in the collection for MMFiles (with the RocksDB engine this "load into memory" operation is not necessary). Is that a possible cause for the problem? How many documents are in that collection? Does the loading animation go away when you hit reload in the browser?

**Comment by aterry1** [comment]
Kthanku

**Comment by CengSin** [comment]
The data is still not displayed after the refresh，Repeat the above

**Comment by terry124** [comment]
K thanks

**Comment by dothebart** [comment]
@terry124 please stop this.
