### ISSUE TITLE
switch to systemd

### ISSUE THREAD

**Issue by ObiWahn** [arangodb/arangodb#4180]
Today systemd is the standard on most linux distributions. We should ship handwritten systemd uints (arangodb.service) to all linux distributions. In case systemd is not available it will not harm and in case it is available the arangodb.service will be used. If an system v init-script with the same name as the service exists no automatic conversion is tried. This behavior ensures that services are not started twice (systemd & legacy).

Relying on the systemd-sysv-generator does not serve us well. We have customer bug reports that are hard to debug because we do not know for sure how the generated units behave. Inside those units calls  to the init scripts can be found. But in the moment they are called from the command-line for debugging purposes systemd intercepts and does some magic snarling debugging to a maximum.

There is no need to rush. Having seen this for some releases now I hope we decide to fix the issue with 3.4 for good.

In the past there was the argument that we do not want to change the startup for existing installations / distributions. My take on this is: We will not affect installations that do not use systemd and that we might be able to ease debugging and get more stability into installations that use systemd.

Note:
systemd uses service files. These service files can not be automatically created from scripts because we will run into the halting problem, when we try to reason about what the script is doing. Sometimes automatic conversion from one language to another is possible by translating and proving basic operations and construction more complex operations by combining the basic ones. This is not possible here because configuration files are fundamentally different to scripts, which can express far more.

**Comment by ObiWahn** [comment]
In order to improve the installation process for debian based packages we should take a good look at the [debian-policy manual](https://www.debian.org/doc/debian-policy/#document-ap-pkg-controlfields). It contains detailed flow diagrams that describe the relation between various install and deinstallation steps. One thing we should use are version numbers, they could allow us to introduce some extra or safety steps when introducing systemd to older distributions. For example we could run some extra command when upgrading form a version less than X.Y.Z to make sure arangod has been really stopped.

**Comment by dothebart** [comment]
3.4 packages come with systemd support.
