### ISSUE TITLE
On execution of FULLTEXT search / AQL query db is restarting

### ISSUE THREAD

**Issue by xbirdblack** [arangodb/arangodb#4185]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [x] 3.3
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [ ] mmfiles
- [x] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
  - [x] GCP
- [ ] Linux 
  - [ ] Debian .deb
  - [x] Ubuntu .deb (16.04)
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver: NodeJS

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

### log
2017/12/30 07:55:42 single has terminated, quickly, in 24.861013999s (recent failures: 1)
2017/12/30 07:55:42 restarting single
2017/12/30 07:55:42 Looking for a running instance of single on port 8529
2017/12/30 07:55:42 Starting single on port 8529
2017-12-30T07:55:42Z [20746] INFO ArangoDB 3.3.1 [linux] 64bit, using jemalloc, VPack 0.1.30, RocksDB 5.6.0, ICU 58.1, V8 5.7.492.77, OpenSSL 1.0.2g  1 Mar 2016
2017-12-30T07:55:42Z [20746] INFO detected operating system: Linux version 4.13.0-1002-gcp (buildd@lgw01-amd64-060) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ub
untu1~16.04.5)) #5-Ubuntu SMP Tue Dec 5 13:20:17 UTC 2017

**Comment by xbirdblack** [comment]
arangodb 3.2 setup is working fine with same configuration

**Comment by jsteemann** [comment]
@xbirdblack : could you please provide some basic information about the AQL query you are executing? It would help if you could post the query string here and the list of indexes for the collection in question. Thanks!

**Comment by xbirdblack** [comment]
Query from node js driver
`
FOR d IN FULLTEXT('users', 'name', ${search}, 3)
          RETURN { name: d.name, id: d._id }
`
collection users
`
{ name: 'pipare', email: 'pipare@example.com' }
`
index - FULLTEXT
field - name
min - 3

**Comment by jsteemann** [comment]
A potential fix for the issue is contained in this pull request: https://github.com/arangodb/arangodb/pull/4239
I have to discuss this fix next week, as it will turn the optimization off in some cases, and this may be improved still.

**Comment by maxkernbach** [comment]
Hi @xbirdblack,

thanks for reporting the bug. Version 3.3.3 including the fix for FULLTEXT search is released.
Please reopen this issue if the problem still occurs.
