### ISSUE TITLE
build_config.h:142:2: error: #error Target architecture x64 is only supported on x64 host

### ISSUE THREAD

**Issue by verbus** [arangodb/arangodb#4186]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [ X] self-compiled devel branch

Mode:
- [ ] Cluster
- [ ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [X ] Linux 
  - [ ] Debian .deb
  - [X ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click to ...
...

The following problem occurs: [Screenshot?] 
Instead I would be expecting: 

### this is an installation-related issue:

# Get the code from github
git clone https://github.com/arangodb/arangodb.git || error "Error---> git command failed"

# Move into the arangodb directory
cd arangodb || error "Error---> cd to arangodb failed"

# create build directory
mkdir -p build || error "Error---> ./mkdir -p build failed"

# Move into the arangodb/build directory
cd build || error "Error---> cd to arangodb/build failed"

# Move into the arangodb/build directory
cmake .. -DCMAKE_BUILD_TYPE=Release || error "Error---> cmake failed"

# Do make
time make -j 2  || error "Error---> make -j 2 failed"

COPY /home/firstuser/arangodb/build/3rdParty/V8/v5.7.492.77/x64.release/icudtb.dat
  CXX(host) /home/firstuser/arangodb/build/3rdParty/V8/v5.7.492.77/x64.release/obj.host/v8_libbase/src/base/bits.o
In file included from ../../../../3rdParty/V8/v5.7.492.77/./src/base/format-macros.h:27:0,
                 from ../../../../3rdParty/V8/v5.7.492.77/./src/base/macros.h:9,
                 from ../../../../3rdParty/V8/v5.7.492.77/./src/base/bits.h:11,
                 from ../../../../3rdParty/V8/v5.7.492.77/src/base/bits.cc:5:
../../../../3rdParty/V8/v5.7.492.77/./src/base/build_config.h:142:2: error: #error Target architecture x64 is only supported on x64 host
 #error Target architecture x64 is only supported on x64 host
  ^~~~~
src/v8_libbase.host.x64.release.mk:182: recipe for target '/home/firstuser/arangodb/build/3rdParty/V8/v5.7.492.77/x64.release/obj.host/v8_libbase/src/base/bits.o' failed

$cat VERSION
3.3.devel

sudo dmesg | grep Linux
[    0.371721] Linux version 4.13.0-19-generic (buildd@z13-013) (gcc version 7.2.0 (Ubuntu 7.2.0-8ubuntu3)) #22-Ubuntu SMP Mon Dec 4 11:58:26 UTC 2017 (Ubuntu 4.13.0-19.22-generic 4.13.13)
[    0.371727] setup.1a06a7: Linux is running as a z/VM guest operating system in 64-bit mode

cat /proc/version
Linux version 4.13.0-19-generic (buildd@z13-013) (gcc version 7.2.0 (Ubuntu 7.2.0-8ubuntu3)) #22-Ubuntu SMP Mon Dec 4 11:58:26 UTC 2017

**Comment by dothebart** [comment]
Hi, 
if I see that correctly you're trying to compile for Z - which afaik has Power7 processors? 
The part of the compile that breaks for you is the [Google V8 javascript engine](https://developers.google.com/v8/) I don't know whether there is a port for it to the Z? Does i.e. nodejs run on Ubuntu Z-Partitions? 
Currently the ArangoDB core is only tested and used on little-endian architectures; the mm-files storage engine is known to have limitations and being bound to little endian; whether or not the rocksdb storage engine can do better isn't known.

**Comment by dothebart** [comment]
As we have no feedback on this, and no hardware available to work on this I will now close this as "won't fix".

**Comment by mlawsonca** [comment]
I am running into the same issue with POWER9 processors. Is arangodb  supported for PowerPC?

**Comment by Simran-B** [comment]
No, it's x64 only.

**Comment by dothebart** [comment]
Things have improven slightly since then. the MMFiles storage engine is gone. 
Most of the functionality (except the management webinterface, Foxx, js-Transactions, User defined AQL functions) could live without V8 these days. 
Also ARM has seen some progress and https://github.com/arangodb/arangodb/pull/13391 adds `arm_neon` to replace x86 special cpu extensions. Is there similar for power?
Biggest roadblock will probably remain the V8 engine (unless it can be removed when doing without these features is enough) and while google seems to be using Power9 - I don't see it porting its javascript engine. @mlawsonca do you know of nodejs ports ot power9?

**Comment by mlawsonca** [comment]
I'd imagine this is a bit unusual, but I am hopping to use ArangoDB as an embedded database in a C++ application using libcurl to make HTTP REST requests. I do not think I will need the V8 engine. Is there a way I can build the library without it?

**Comment by dothebart** [comment]
It probably depends on the amount of time you're willing to invest. 

Is there a similar library to `arm_neon` replacing the vectorized instructions on Power? Probably testing whether there is a way to get rocksdb alone working on Power would be a feasability test for the whole unterdaking for me.

Once you know rocksdb will be working, I'd continue with this on x86_64 - one step at a time.

Probably the main C++ interference will be to add #ifdef's to https://github.com/arangodb/arangodb/blob/devel/arangod/RestServer/arangod.cpp ; the rest should be primarily be work in the cmake files. I.e. arangosh would be disabled by your cmake configure flag; lots of files stopped from being built via removing them from the cmake target. Maybe some of these 'feature' plugins will need to be even more splitted, but that would have to be tested.

ICU currently integrates via the V8 source; You would have to replace / offer this integration in a different way. So for the first step (to fail fast) I would continue building V8 / ICU and later on once you got everything working by replacing the  implementation in the 3rdParty/ cmake files.

**Comment by mlawsonca** [comment]
Okay thank you. I will open a separate issue if I decide to go down that route and run into problems.

**Comment by dothebart** [comment]
Be welcome. 
You could also join the community Slack for more interactive chater, but please note that most of the developers live in European timezones.
If you have any question, don't hesitate to ask.
