### ISSUE TITLE
systemd has to be optional

### ISSUE THREAD

**Issue by yurivict** [arangodb/arangodb#4190]
It doesn't exist on BSD systems.

**Comment by dothebart** [comment]
Hi, 
part of the ArangoDB core contains packaging infrastructure required to create .debs and .rpm's for linux targets using [cpack](https://cmake.org/Wiki/CMake:Packaging_With_CPack). 

These infrastructures live below the cmake/packaging directory; however its not mandatory to have them, as i.e. our MacOS X or Windows Packages won't ship them.
