### ISSUE TITLE
arangosh.lnk not correct

### ISSUE THREAD

**Issue by ObiWahn** [arangodb/arangodb#4195]
os: windows
version: 3.3.1

The link for the windows client points to:

`C:\Users\Test\AppData\Local\ArangoDB3-client 3.3.1\usrbin\arangosh.exe`

it should be `...usr\bin...`

We found that the variable ${BIN_DIR} is probably responsible for the value, but it seems to be set somewhere outside the arangodb repository.

**Comment by dothebart** [comment]
Hi, 
the template generated from the NSIS.template.in i.e. at 
`/cygdrive/c/b/willi_build/_CPack_Packages/win64/NSIS/project.nsi `

will look like this in the sections in question:

    !define INST_DIR "C:/b/willi_build/_CPack_Packages/win64/NSIS/ArangoDB3-3.2.devel-1_win64"
    !define ARANGO_INI "etc\arangodb3\arangod.conf"
    ;--------------------------------
    ; custom defines for the DRY people of us.
    !define TRI_UNINSTALL_REG_PATH "Software\Microsoft\Windows\CurrentVersion\Uninstall\ArangoDB3 3.2.devel";
    # Comes from WaitForService: !define TRI_SVC_NAME 'ArangoDB'
    ; Put some of the more custom ones in from the CMakeFile:
    !define BITS 64
    !define TRI_FRIENDLY_SVC_NAME 'ArangoDB - the native multi-model NoSQL database'
    !define TRI_AARDVARK_URL 'http://127.0.0.1:8529/_db/_system/_admin/aardvark/index.html'
    !define SBIN_DIR 'usr\bin'
    !define BIN_DIR 'usr\bin'

The shortcut is created here:

    CreateShortCut  "$SMPROGRAMS\$STARTMENU_FOLDER\Arango Shell.lnk"  "$INSTDIR\${BIN_DIR}\arangosh.exe"  '' '$INSTDIR\resources\arangodb.ico' '0' SW_SHOWMAXIMIZED

i.e. the `ARANGO_INI` is used in the same way: 

    ReadINIStr $DATADIR                  "$INSTDIR\${ARANGO_INI}" "database"   "directory"

**Comment by dothebart** [comment]
https://github.com/arangodb/arangodb/pull/4227 fixes this.

**Comment by dothebart** [comment]
fixed in 3.3

**Comment by sleto-it** [comment]
3.3.2 is out. closing.
