### ISSUE TITLE
[feature request] The embedded, zero-configuration mode

### ISSUE THREAD

**Issue by yurivict** [arangodb/arangodb#4198]
If the user just wants to use ArangoDB database features locally, in his own file system, there should be no need to have permissions, DB connection, client-server model, etc.

For example, please add:
```
    client = ArangoClient(
      protocol='local',
      directory='/home/{user}/my-local-arango-db-folder',
      ...
   )
```

Then the user can:
```
db = client.create_database('user-db')
db = client.connect_database('user-db')
...
```
without the need for the client-server connection.

For example, I would like to have a script that uses ArangoDB's advanced graph search features. I can fill my DB myself in my folders, will only use it locally, and don't want to bother with connections, authentication, config files, etc. There should be no reason why the client-server model should encumber such use. Think of conveniences of SQLite. I would like to have something like ArangoLite, in the same spirit.

**Comment by Simran-B** [comment]
Wouldn't that mean to run your script directly in the server?

Seems much like working with the emergency console to me: https://docs.arangodb.com/3.3/Manual/Troubleshooting/EmergencyConsole.html

If you mean to make ArangoDB portable, then I'm not sure in how far it is suitable because of the amount and size of the binaries and other files.

> SQLite does not compete with client/server databases. SQLite competes with fopen().

Based on that statement, I wonder what that would mean for an "embedded zero-conf ArangoDB".

**Comment by yurivict** [comment]
> If you mean to make ArangoDB portable

I didn't mean portable. Just runnable in zero-conf mode, so that client-server and configuration is deemphasized, so that it will be more usable from scripts.

Now, in order to even do something locally, you need to explain users that they need to login, create a database, use login/password, or consider if it is configured to use authentication or not. I mean to simplify this for local use.

**Comment by dothebart** [comment]
sounds like a usecase for docker to me? 
Comparing ArangoDB to SQLite is a bit like comparing water skies with an oil tanker?

**Comment by yurivict** [comment]
> sounds like a usecase for docker to me?

Docker is also not easy, requires setup. It defeats the purpose of the original suggestion. Besides, Docker only supports linux, and not BSD.

> Comparing SQLite to ArangoDB is a bit like comparing water skies with an oil tanker?

Well, I see your point. But I would like to point out that ArangoDB is just one process running `/usr/local/sbin/arangod`, using some extra files. There is nothing there to make it unable to run from the command line as well.

**Comment by rawshawn** [comment]
So what should I do

**Comment by dothebart** [comment]
We, as the ArangoDB team offer various ways of acquiring arangodb and running it. 
We discussed this, and we decided not to do this since many options are available to users. 
If you like to contribute such a mode, feel welcomed to do so, but we won't do this. 
If you decide rather not to, I vote for closing this as "won't fix".

**Comment by yurivict** [comment]
As expected, political considerations cause this technically excellent proposition to be shelved.

**Comment by dothebart** [comment]
We have to priorize our available manpower; letting something linger around which we won't ever do doesn't serve anybody. 
Closing.

**Comment by yurivict** [comment]
FYI: I came across the relevant PostgreSQL software: https://github.com/Oslandia/pglite
The python module that allows users to work with PostgreSQL as with zero-configuration DB. Python module exists, therefore this is doable with PostgreSQL, therefore there are uses and users who want this.

And you have rejected the same suggestion. I know, resource considerations and all...

**Comment by dothebart** [comment]
Nice, so you know how to implement it. Heres how to compile it: https://docs.arangodb.com/3.3/Cookbook/Compiling/ - If you need more information just ask. 

Looking forward for your ArangoLite.

**Comment by codebling** [comment]
Sorry for the necrobump - would like to add some info for posterity.

From a teeny bit of experimentation, the most immediate blocker is the large number of js files required for startup. It's not clear to me which js files (if any) are required for core functionality if Foxx and the (HTTP) admin interface are disabled/not used. 

That being said, one could conceivably generate a massive binary (roughly 150 MiB) that embeds all of the js, along with `icudtl.dat` without too much effort. 

For those that want to tinker, here's a Dockerfile with the smallest change set I could find that successfully starts the server
```
FROM arangodb:3.7.10 as builder

FROM alpine

WORKDIR /app
COPY --from=builder /usr/share/arangodb3/js js
COPY --from=builder /usr/sbin/arangod ./
COPY --from=builder /usr/share/arangodb3/icudtl.dat ./

RUN touch arangod.conf

CMD ./arangod --foxx.api false --server.authentication false --database.directory arango.db --server.endpoint unix:///`pwd`/arango.db/socket --configuration arangod.conf --javascript.startup-directory js --javascript.app-path /tmp/app
```


The value proposition here to me is less about zero-config (from what I've seen, Arango already handles this pretty well, offering smart defaults for most options) and more about embeddability - having a monolithic binary or library that can be linked against and loaded in-process.
