### ISSUE TITLE
Web UI: Query builder proposes bad error message on invalid json

### ISSUE THREAD

**Issue by virmundi** [arangodb/arangodb#4217]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [X ] 3.2
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [ X] Single-Server

Storage-Engine:
- [ ] mmfiles
- [ X] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [X ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [ X] web interface with this browser:  Firefox   running on this OS: Ubuntu
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [X ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as a user with access to my database.
3) Go to the query editor (Queries on left)
4) Attempt to run this AQL
```
FOR e IN @@edge
		FILTER {_to: e._to, _from: e._from} IN @edges
		REMOVE e IN @@edge
		RETURN e
```
With these bindVars, from switching to JSON mode. 

```
{
	"@edge": "member_of",
	"edges": [
	    {_from: "profile/p1", _to:"real/no1"},
	    {_from: "profile/p1", _to: "real/no2"}
	]
}
```
...

The following problem occurs: 
![bindvarissue](https://user-images.githubusercontent.com/1041487/34540501-caf5da56-f0a2-11e7-9f12-f26175561f65.png)

Instead I would be expecting: To delete properly with that list of things to remove.

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

**Comment by Simran-B** [comment]
Some quote marks are missing in the bind parameter object to be valid JSON. Keys need to be enclosed in double quotes (around `_from` and `_to`):

```json
{
	"@edge": "member_of",
	"edges": [
		{
			"_from": "profile/p1",
			"_to": "real/no1"
		},
		{
			"_from": "profile/p1",
			"_to": "real/no2"
		}
	]
}```

That fixes the issue in my test. Does it solve it for you too?

**Comment by virmundi** [comment]
That makes sense. I’ll look in the morning.

**Comment by virmundi** [comment]
You're correct. I needed to include the quotes around the keys. Sorry for the false report.

**Comment by dothebart** [comment]
When clicking on "Table" to convert the json into the UI representation the error message is better: 
`Bind parameter: Could not parse bind parameter`
The error message in the screenshot is misleading and should be fixed.

**Comment by hkernbach** [comment]
Applied @dothebart suggested fix.

**Comment by maxkernbach** [comment]
Version 3.2.11 that contains the improved error message is released.
