### ISSUE TITLE
Permission error preventing AQL query import / export on webui

### ISSUE THREAD

**Issue by davidmw** [arangodb/arangodb#4222]
ArangoDB: 3.3.1
- [ ] Single-Server
- [ ] mmfiles
  - [ ] AWS
  - [ ] Ubuntu .deb
- [ ] MacOS, version:

I'm issuing AQL via:
- [ ] web interface with this browser:   Safari 11.0.2  running on this OS: OSX

After installing 3.2 on AWS and upgrading to 3.3.1, and after directly installing 3.3.1 on OSX I've run into the following problem on both platforms:

I create a new Admin user, then create my database with this Admin as owner - all from the WebUI.  Then login to the Admin account and select my database.

At this point I select Queries and attempt to import previously exported queries. The import fails with an error 500 written to the log file.

If I create a New query I may be unable to save it, or unable to save subsequent updates to the query. These Save attempts tend to fail silently.

All efforts to export queries from the WebUI will fail.

If I login as root I can then import, save, and export AQL queries but these are not available to user Admin.

If I modify permissions on user Admin and grant him administration privileges to database _system this will allow all query import / export / saving as needed from the Admin account. This workaround may introduce new security concerns so it seems less than ideal.

**Comment by hkernbach** [comment]
Thanks for the report. This was indeed a bug. Fixed in 3.2/3.3 and devel branches.

PRs available here: https://github.com/arangodb/arangodb/pull/4324 & https://github.com/arangodb/arangodb/pull/4325 & https://github.com/arangodb/arangodb/pull/4327

**Comment by maxkernbach** [comment]
@davidmw version 3.2.11 that includes the fix has been released.

**Comment by sleto-it** [comment]
Hi,

3.3.3 has been released as well. I am closing this ticket now. Please feel free to reopen if the problem persists

Many thanks,
