### ISSUE TITLE
After upgrading 3.3    The Java driver cannot automatically reset the database whenever the database is restarted  

### ISSUE THREAD

**Issue by zhenruyan** [arangodb/arangodb#4229]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [x] 3.3
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [ ] mmfiles
- [x] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [x] other:centos
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[x] I'm using graph features

The Java driver cannot automatically reset the database whenever the database is restarted
 
java driver   4.3.2
tomcat 8

After testing the 3.2 version of the can automatically reset

**Comment by hbCyber** [comment]
I have also experienced this issue -- the Java client sometimes fails to recognize that the connection is broken, and does not auto-reconnect. 

In my own code, I have to inspect ArangoDBException objects thrown to detect the bad connection myself and issue a reconnect order...

```
if (exMessageLowerCase.contains("Connection refused".toLowerCase())
    || exMessageLowerCase.contains("Was not able to connect to any host".toLowerCase())) {
    ArangoDbConnectionProvider.getInstance().reconnect();
        // This causes the Arango driver & database object to be shut down and recreated fully.
}
```
