### ISSUE TITLE
Unnecessary Array Nesting in AQL RETURN

### ISSUE THREAD

**Issue by davidmw** [arangodb/arangodb#4242]
## my environment running ArangoDB
- [ ] 3.3
- [ ] Single-Server
- [ ] mmfiles
 - [ ] AWS

### this is an AQL-related issue:
I'm issuing AQL via:
- [ ] web interface with this browser:   Safari 11.0.2  running on this OS: OSX

My QUERY:
`LET mydoc = [
    {   "id": "1399722" },
    {  "id": "1399724" },
    {   "id": "1305997"  }
]
RETURN mydoc
//RETURN FLATTEN( mydoc )
`
returns:
`[
  [
    {
      "id": "1399722"
    },
    {
      "id": "1399724"
    },
    {
      "id": "1305997"
    }
  ]
]
`

Which is an unrequested and seemingly unnecessarily [[nested array]]. Changing the last line to` RETURN FLATTEN( mydoc )` or even `RETURN FLATTEN( mydoc, 2)` accomplishes nothing.

Changing the last line to `RETURN mydoc[0]` generates 
`[
  {
    "id": "1399722"
  }
]`
This returns the first element of the intended array (correctly) but also notice that the superfluous nesting is gone. 

This array nesting caused considerable grief until I spotted it -- I'm making the effort to generate JSON from my foxx service that can be directly merged into my Keylines chart.  I've not found a way to eliminate the array nesting from AQL and am forced to do it in my frontend.  While this is simple enough to do `resultarray[0]` I've come to view it as an ArangoDB bug.

**Comment by vinaypyati** [comment]
Hello @davidmw,

*The result of a RETURN statement is always an array*. 
This was the design decision made by ArangoDB. RETURN statement includes an empty array if no documents matched the query and a single return value is returned as an array with one element. So, in the above case, "mydoc" is nested inside an array.

To return all elements from the currently iterated array without modification, we can modify the above query to 

`LET mydoc = [ { "id": "1399722"} , { "id": "1399724" }, { "id": "1305997" } ] 
    FOR element IN mydoc
    RETURN element`

One can also modify the AQL query RETURN by projecting the document elements as per need. 
One simple case can be seen here - [RETURN in AQL](https://docs.arangodb.com/latest/AQL/Operations/Return.html)

**Comment by maxkernbach** [comment]
Hi @davidmw,
does that answer your question, can we close this issue?

**Comment by davidmw** [comment]
I can’t say this novice likes the design decision. It certainly makes sense to always return an array for empty set and single element. 

But the nesting is an annoyance that damages the utility of FLATTEN and requires special handling on a regular basis at either the front or back end. My current preference would be for RETURN to simply guarantee that an array would be added if there is none and not blindly nest. 

Unless I’m mistaken it isn’t possible to return multiple arrays without merging or appending them into one. So the outer array might contain 0, 1 or more documents, or exactly 1 array. That last case is rather odd.

**Comment by dothebart** [comment]
Hi, 
as @vinaypyati explained, the outer brackets are mandatory; removing them will break things that lean on their existence in client drivers and other integration points. It would also break your code, since it would randomly remove a layer brackets.

@vinaypyati also explained you how to remove the inner set of brackets.

FLATTEN doesn't do what you expect it to do here because of flatten is always returning an array - with flattened substructures - which are your inner brackets - but just one layer of it and not multiple.
