### ISSUE TITLE
AQL SORT consuming too much memory

### ISSUE THREAD

**Issue by roman1720** [arangodb/arangodb#4255]
3.2.9 debian, mmfiles

Query:
 
    LET impactDict = {'changed': 10, 'added': 0, 'removed': 30}
    LET a = (
      FOR sh IN vSiteHistory
        FILTER sh.vCollectId == 'vCollect/177384072'
        FOR shData IN sh.data
          FILTER shData.type == 'global'
          FOR d IN shData.connectivityMatrix
            RETURN {key: HASH(KEEP(d, @keep)), data: d}
    ) || []
    LET b = (
      FOR sh IN vSiteHistory
        FILTER sh.vCollectId == 'vCollect/191027406'
        FOR shData IN sh.data
          FILTER shData.type == 'global'
          FOR d IN shData.connectivityMatrix
            RETURN {key: HASH(KEEP(d, @keep)), data: d}
    ) || []
    LET keysA = a[*].key
    LET keysB = b[*].key
    LET before = ZIP(keysA, a[*].data)
    LET after = ZIP(keysB, b[*].data)
    LET uniq = UNION_DISTINCT(keysA, keysB)
    LET added = FIRST(
      LET keys = MINUS(keysB, keysA)
      RETURN ZIP(keys, keys)
    )
    LET removed = FIRST(
      LET keys = MINUS(keysA, keysB)
      RETURN ZIP(keys, keys)
    )
    FOR key IN uniq
      LET $id = HASH(key)
      LET isAdded = HAS(added, key)
      LET isRemoved = HAS(removed, key)
      LET data = (isRemoved ? before[key] : after[key])
      LET $hostname = data.hostname
      LET $sn = data.sn
      LET statusText = (isAdded ? 'added' : (isRemoved ? 'removed' : null))
      LET $status = {
        text: statusText,
        severity: TRANSLATE(statusText, impactDict, -1)
      }
  
        LET $localHost = data.localHost
        LET $localInt = data.localInt
        LET $localMedia = data.localMedia
        LET $localSn = data.localSn
        LET $protocol = data.protocol
        LET $remoteHost = data.remoteHost
        LET $remoteInt = data.remoteInt
        LET $remoteMedia = data.remoteMedia
        LET $remoteSn = data.remoteSn
        SORT $status.severity DESC  LIMIT 31  RETURN {id: $id,status: $status,localHost: $localHost,localSn: $localSn,localInt: $localInt,localMedia: $localMedia,remoteHost: $remoteHost,remoteSn: $remoteSn,remoteInt: $remoteInt,remoteMedia: $remoteMedia,protocol: $protocol} 

parameter:

 {
  "keep": [
    "localHost",
    "localSn",
    "localInt",
    "localMedia",
    "remoteHost",
    "remoteSn",
    "remoteInt",
    "remoteMedia",
    "protocol"
  ]
} 

There's not too much data, but query quickly consumes all available memory (16GB) and Arango crashes. Without SORT at the end of query, it runs fine without any problems. I will send dump to your email so you can reproduce it.

**Comment by Simran-B** [comment]
How much data is it roughly in numbers? Thanks!

**Comment by roman1720** [comment]
a and b variables at the beginning of query have around 15K documents each, document has 11 properties. Result set has 15K document. See dump I send to hackers@arangodb.com

**Comment by jsteemann** [comment]
Should be fixed via the above PRs that make an in-memory cache inside the SortNode use much less memory.

**Comment by maxkernbach** [comment]
Version 3.2.11 has been released and includes the fix for the problem you reported.
Can you upgrade your version and confirm that it is fixed?

Thanks

**Comment by roman1720** [comment]
Fixed, thank you
