### ISSUE TITLE
arangoexport/arangoimport is not defined (bash on Windows)

### ISSUE THREAD

**Issue by Kustopher** [arangodb/arangodb#4261]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2.9

Mode:
- [x] Single-Server

Storage-Engine:
- [x] mmfiles

On this operating system:
- [x] Windows, version: 10

Hi, I'm running ArangoDB on Windows for local development. It's working pretty fine. But now I'm struggling deploying the local database to a ArangoDB installation on a Linux Server. First step is to export the data and I thought I would find some easy Export/Import Feature in the Web Interface. Well, instead in the documentation I found two other solutions:
- arangodump+arangorestore 
- arangoexport+arangoimport

I just don't know how to use those solutions. Maybe I'm missing something really obvious:) Well, I found the .exe files and by running arangodump.exe I indeed get a "dump" directory as result. But I actually would like to use the commands described in the docs, like "arangoimp --file "data.json" --type json --collection "users""

How to run the commands? Everyday I use bash commands on Windows, for other nodejs applications, no problem. But with ArangoDB I'm just not getting it. Using arangosh.exe I get "arangoexport is not defined" and no matter which ArangoDB directory I try to access bash, it's always saying "arangoexport is not defined" or "arangosh is not defined".

Any help?

**Comment by jsteemann** [comment]
Are you using the Linux packages or the Windows packages, i.e. do you have the .exe files or the Linux executables installed on the computer you are trying to invoke arangosh, arangoexport, arangodump etc.?
If you think everything is installed correctly, please check if all the ArangoDB executables are actually in your path. Using a regular Linux installer they should be put somewhere in the regular path (e.g. /usr/bin). 
Can you therefore let us know what exact installation method  you used for ArangoDB and how you actually try to invoke the tools (i.e. from MS-DOS, Powershell, bash etc.)? That's unclear to me at the moment.

**Comment by vinaypyati** [comment]
Hello @Kustopher,

Considering you are on windows 10, there are two possible solutions to your question.

Solution 1 : 
1. Open Powershell or command window in the ArangoDB folder - where all the .exe files exist. 
Note: To open a Powershell or command window you can hold the Shift key on your keyboard and right click on your mouse inside the folder. 
2. You can now run the commands. Following is the example
 **.\arangoimp.exe --file "data.json" --type json --collection "users"**

Solution 2(Recommended) :
1. Add the ArangoDB exe folder to your environment variables to invoke the exe's from anywhere unlike the first solution.
Note: To set an ENV variable, hold Windows key on your keyboard and press pause key. On the left side open "Advanced system settings". Then click on Environment Variables. 
2. Under system variables find "Path". Double click on it and click "New". Now add your ArangoDB exe folder path there and click OK. Now you can run your commands by invoking command window/Powershell.

Let us know if you are using Linux package and environment.

**Comment by Simran-B** [comment]
The root path of ArangoDB should be `C:\Program Files\ArangoDB3 3.2.9` if you used the Windows installer. You can open a command prompt or powershell in that folder, and run arangoimp with `usr\bin\arangoimp.exe --file "data.json" --type json --collection "users"`.

With the root path as working directory, all Arango binaries in `usr\bin\` should be able to automatically find their default configuration files in `etc\arangodb3\`.

**Comment by Kustopher** [comment]
Hi everyone and thanks a lot, it's solved!

I'm not using Linux, I installed ArangoDB3-3.2.9-1_win64.exe and what I did was trying to invoke bash by "Git Bash Here". Well, it worked fine for other applications.... I forgot about Powershell. With Powershell it's finally working. Thanks! So obvious. And thanks for the hint in "Solution 2". I had no idea you can set ENV variables, need to check it out.

**Comment by Simran-B** [comment]
@Kustopher you can run `echo $PATH` in the Git Bash to see what paths are in the PATH environment variable known to that shell. `arangimp` etc. should work if the path is correctly set in there.
