### ISSUE TITLE
VelocyStream: scheduler loop caught exception: Internal error

### ISSUE THREAD

**Issue by mpv1989** [arangodb/arangodb#4284]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] self-compiled devel branch

Mode:
- [x] Single-Server

Storage-Engine:
- [x] rocksdb

On this operating system:
- [x] Linux 
  - [x] Ubuntu .deb
- [x] Windows, version: 10

These are the steps to reproduce:
```
git clone https://github.com/arangodb/arangodb-java-driver
cd arangodb-java-driver
mvn test
```
...

The following problem occurs:
When running the java driver unit tests ArangoDB logs the following error and the VelocyStream connection to the client gets closed.

`ERROR {threads} scheduler loop caught exception: Internal error`

**Comment by ObiWahn** [comment]
3rdParty/velocypack/include/velocypack/Slice.h:831 - slice.byteSize() ends up in a custom type and does not switch to a valid case. We need to check if we read the vst in a different way. It is possible that we did not check the value before, as the VstInputMessage::init just changed recently (which could be another source of the error)

**Comment by jsteemann** [comment]
Closing as it is fixed in devel.
