### ISSUE TITLE
root password has been reset to null

### ISSUE THREAD

**Issue by hellomanjack** [arangodb/arangodb#4316]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [x] 3.1
- [ ] 3.2
- [ ] 3.3
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [x] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [ ] Debian .deb
  - [x] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

I have a environment with tomcat and arangodb on it. We use arangodb driver to access data in arangodb. Sometimes about one month or so, the password for root user has been reset. Can you give 
me some suggestions to avoid this, or how to acquire the reason for what happens ? Thanks!

**Comment by dothebart** [comment]
Hi, 
from the shell you can change the root password using `arango-secure-installation` if the server is stopped. 
You can also change it using the webinterface using the REST interface below, which is also offered via the driver.

**Comment by OmarAyo** [comment]
Hi @hellomanjack,

Can you please give us an update on this ticket.

**Comment by maxkernbach** [comment]
Hi @hellomanjack,

im am closing this issue for now as we have not received any feedback for a few months.
Please feel free to reopen this issue and comment in case your problem persists.
