### ISSUE TITLE
how to use user function with Registering Function

### ISSUE THREAD

**Issue by CengSin** [arangodb/arangodb#4317]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [x] 3.3
- [ ] self-compiled devel branch

Mode:
- [x] Cluster
- [ ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [x] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [x] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser:     running on this OS:
- [x] arangosh
- [x] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click to ...
...

The following problem occurs: [Screenshot?] 
Instead I would be expecting: 

How to match the data value Model without knowing how to determine an attribute?

for example:
 I want to search a document with it's a attribute Value could be %data%, but i don't konw what's it attribute name  ,What should I do

![image](https://user-images.githubusercontent.com/23357893/34972451-9882f6c0-fabc-11e7-9ec9-f2e5a453cecf.png)

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

**Comment by Simran-B** [comment]
What's the ultimate goal of your function? To determine if a character sequence is contained in any of the attribute values of your document?

To check all top-level attributes, you could do something like this:

```js
FOR attr IN ATTRIBUTES(doc, true)
  FILTER CONTAINS(doc[attr], "data")
  RETURN { [attr]: doc[attr] }
```

Recursion is not possible in pure AQL to test attributes at deeper levels. A possible workaround is to turn the entire document [into a JSON string](https://docs.arangodb.com/3.3/AQL/Functions/String.html#jsonstringify) and use CONTAINS() again:

```js
LET doc_str = JSON_STRINGIFY(doc)
FILTER CONTAINS(doc_str, "data")
```

Be sure to check out the upcoming milestone release with new full text search capabilities - maybe that will work for your use case and make use of indexes.
