### ISSUE TITLE
There was a problem starting ArangoDB

### ISSUE THREAD

**Issue by CengSin** [arangodb/arangodb#4344]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [x] 3.3
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [x] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [x] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser:     running on this OS:
- [x] arangosh
- [x] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click to ...
...

![image](https://user-images.githubusercontent.com/23357893/35034610-b9fafe68-fba9-11e7-9008-ce04a0350c1f.png)

![image](https://user-images.githubusercontent.com/23357893/35034638-d7229690-fba9-11e7-9199-d06d2fe21e91.png)

![image](https://user-images.githubusercontent.com/23357893/35034660-e8beedfe-fba9-11e7-87fe-bcebcd878de4.png)

this is my Computer:

1G memory and 1 core CPU and 1M network speed

### this is an installation-related issue:
 Something's wrong when I install arangodb3-3.2 for my Linux(Red Hat)，i can't visit the web interface and execute `arangosh` shell

**Comment by moxiaoyu100** [comment]
Turn off authentication

**Comment by jsteemann** [comment]
Is there anything else in arangod.log that provides more information about the problem?
Can you also check /var/log/messages or syslog or wherever the kernel logs information about killed process etc.? This may also provide some info.

Looking at just the above, I suspect that on a machine with just 1 GB RAM you will likely run into problems rather soon, especially as the MMFiles engine is in use, which will have all its indexes in main memory (RAM).

**Comment by CengSin** [comment]
this error after I edit the /etc/arangodb3/arangod.conf && /etc/arangodb3/arangosh.conf. I want to add my IP address.

**Comment by CengSin** [comment]
I don't know Whereis the adjusted config file, where is the default path of single

**Comment by jsteemann** [comment]
Didn't you say you edited the config files already?

> this error after I edit the /etc/arangodb3/arangod.conf && /etc/arangodb3/arangosh.conf. I want to add my IP address.

Can you share the edited versions of these files?

**Comment by CengSin** [comment]
I just add the `endpoint` for the file ( arangod.conf , arangosh.conf ) , sorry , I don't know what upload picture :-(

**Comment by jsteemann** [comment]
No need to upload a picture. You can copy&paste the edited sections as text in here.

**Comment by CengSin** [comment]
`# Examples:
#   endpoint = tcp://0.0.0.0:8529
#   endpoint = tcp://127.0.0.1:8529
#   endpoint = tcp://localhost:8529
#   endpoint = tcp://myserver.arangodb.com:8529
#   endpoint = tcp://[::]:8529
#   endpoint = tcp://[fe80::21a:5df1:aede:98cf]:8529
#
endpoint = tcp://127.0.0.1:8529
endpoint = tcp://120.69.171.152:8529
storage-engine = auto

`

**Comment by jsteemann** [comment]
I think this configuration will not work, as you are trying to bind to the same port on the same server.
Can you try using different port numbers?

**Comment by jsteemann** [comment]
Note that in arangod.conf you can use `endpoint = tcp://0.0.0.0:8529`.
For arangosh.conf you will need to add the proper IP address however if you try to connect to a different host. 0.0.0.0 will not work here, as it is only useful for the server side.

**Comment by CengSin** [comment]
Ok, I try to edit the files
