### ISSUE TITLE
csv parser skips data at buffer border

### ISSUE THREAD

**Issue by jsteemann** [arangodb/arangodb#435]
Using `arangoimp` to import a CSV file into ArangoDB (`--type csv`).
There is a fixed size buffer of 32768 bytes allocated when reading data from the CSV file. Chunks from the input file are read into that buffer and then processed.

It seems that if a line goes beyond that buffer, the part that is beyond the buffer border is partly ignored and not imported. Although all lines in the input file have the same number of columns, debugging the import reveals that some lines have one column less when being read.

The following figures show the number of errors for importing the same CSV file, but with different internal buffer sizes:
- buffer size 32768: 654 errors
- buffer size 327680: 73 errors
- buffer size 3276800: 6 errors

The size of the file is 128 MB.

**Comment by sooraj771989** [comment]
I am trying to import CSV file into ArangoDB it gives me a warning message. Null values are not importing. Could someone help on this

![screenshot from 2018-01-02 14-52-59](https://user-images.githubusercontent.com/12758271/34479459-115a6dda-efcd-11e7-9f09-b632a7168aa1.png)

**Comment by jsteemann** [comment]
@sooraj771989 : can you specify the import command and a sample of the to-be-imported data? Otherwise it is hard to tell whether the error messages are "intentional".

**Comment by aterry1** [comment]
K
