### ISSUE TITLE
Index on nth element of an array

### ISSUE THREAD

**Issue by matcho** [arangodb/arangodb#4354]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.3

Mode:
- [x] Single-Server

Storage-Engine:
- [x] rocksdb

On this operating system:
- [x] Linux 
  - [x] Ubuntu .deb

### this is an AQL-related question:

Could it be possible to allow index creation on the nth element of an array, or a sub-key inside this element ?
Especially I'm thinking of the first element, like `doc.arr[0].stuff`.
ArangoDB currently doesn't accept this.
```
127.0.0.1:8529@stuff> db.queries2.ensureIndex({ type: "hash", fields: [ "result.results[0].name" ] });
JavaScript exception in file '/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js' at 98,7: ArangoError 1220: can only use [*] for indexes
```

At the moment we have introduced redundancy in the documents by copying `result.results[0].name` to `result.first_result.name`, and created an index on this new field. This works great, but then the document structure becomes much more difficult to maintain across updates.

We could create an index on `result.results[*].name`, filter using `'value' IN result.results[*].name`, then filter again on `'value' == result.results[0].name`, but in our case this proved to be around 8 times slower. Performance is still very good (10 times faster than without any index at all) but it's quite frustrating to know that Arango can do 8 times faster…

The test collection has 400 000 docs, average size of `result.results[*]` is 8 elements.

Thanks a lot for your consideration,
Greetings,
Mathias

**Comment by Simran-B** [comment]
This would be solved more generically with expression-based indexes: #1501

Nothing planned at the moment however as it's not an easy feature to implement, especially in cluster.

**Comment by matcho** [comment]
Indeed the more generic expression-based indexes would solve this.

But as the nth element of an array `.stuff[0]` is a… I would say "deterministic indirection" (not sure if I'm clear here), it's eventually not different from any other indirection like `.stuff.foo`. It might require an additional check that `stuff` is an array, but except this it doesn't look like it requires any complex implementation.

Of course I'm not an ArangoDB engineer and might miss a lot of subtile things, but isn't it almost just a matter of syntax ?

If so, a bit of AQL-candy would be greatly appreciated :)

Thanks

**Comment by matcho** [comment]
Thank you for your answer. I guess it's not so easy after all.
Well, still hoping for this feature to pop one day, who knows :-)

**Comment by dothebart** [comment]
Hi, 
With ArangoDB 3.7 the [REPLACE_NTH](https://www.arangodb.com/docs/stable/aql/functions-array.html#replace_nth) AQL function was added. 

For Details about ArangoDB 3.7 please review https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/
Closing as solved.

**Comment by dothebart** [comment]
Nice try. This was to close ;)

**Comment by matcho** [comment]
Hi. Indirectly works with Computed Values introduced in v3.10.

Using array access notation like `@doc.some_array[2]` does not work (`Error: Could not save computed values definition for collection queries: Error when validating computedValues: invalid 'computedValues' entry: Node type 'indexed access' is forbidden in computation expression`) but it can be achieved using `NTH()` function.

Example:
```
[
  {
    name: "first_element",
    overwrite: true,
    computeOn: ["insert", "update", "replace"],
    expression: "RETURN FIRST(@doc.some_array)"
  },
  {
    name: "third_element",
    overwrite: true,
    computeOn: ["insert", "update", "replace"],
    expression: "RETURN NTH(@doc.some_array, 2)"
  }
]
```

Marking this as resolved, great news!
