### ISSUE TITLE
Web client errors when upgrading from 3.2 to 3.3 

### ISSUE THREAD

**Issue by alejom99** [arangodb/arangodb#4361]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [X] 3.3
- [ ] self-compiled devel branch

Mode:
- [X] Cluster
- [ ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [X] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [X] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [X] docker - official docker library (running on Ubuntu)
  - [ ] other:
- [ ] Windows, version: 
- [x] MacOS, version:

### this is a web interface-related issue:
I'm using the web interface with this browser: Chrome    running on this OS: Mac OS
- [ ] authentication is enabled?
- [X] using the cluster?
- [ ] _system database?

We had a 3-node cluster (3 agents, 3 coordinators and 3 databases) running 3.2.9 using docker and with security enabled. We decided to upgrade to 3.3.2 using the following steps:
1) Upgraded the agents first, one at a time, following the procedure in the documentation.
2) Upgraded the database, one at time, using the same procedure.
3) Upgraded the coordinators, one at a time, using the same procedure.

Two issues were found:
1) When I tried to access the web interface from one of the coordinators (say http://some_ip:8529), I got the following response:

`{"error":true,"code":404,"errorNum":404,"errorMessage":"unknown path '/'"}`

I had to manually navigate to http://some_ip:8529/_db/_system/_admin/aardvark/index.html to access the web client. This used to work in 3.2.9

2) When I was able to access the web interface, I tried to login with the root account and password, but I got a "login failed" error. I had to disable authentication to be able to access the web interface and I had to re-create the root user. Is this by design? or is it a bug?

**Comment by OmarAyo** [comment]
Hi @alejom99 

Just a quick update - we are improving our documentation regarding _upgrade_ - once it is done, I'll share it with you.

Best

**Comment by OmarAyo** [comment]
Hi @alejom99 

We just released a guide about _ArangoDB Cluster Administration_ where you can find the correct procedure to _ArangoDB Cluster Upgrade_

Please find the link below:
https://www.arangodb.com/2018/03/arangodb-cluster-administration-course/

Best

**Comment by OmarAyo** [comment]
Hi @alejom99 

Any update on this ticket ? Could you please send us a feedback ?

Many Thanks

**Comment by OmarAyo** [comment]
Hi @alejom99 

I am going to close this ticket, feel free to reopen it at any time if needed.

Many Thanks
