### ISSUE TITLE
rocksdb : collection 100GB size : "Out of memory: Kill process" failures

### ISSUE THREAD

**Issue by avive99** [arangodb/arangodb#4392]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [V ] 3.2
- [ ] 3.3
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [V ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [V ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ V] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click to ...
...

The following problem occurs: [Screenshot?] 
Instead I would be expecting: 

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

Single host, Centos 7.3, rpm installation, ArangoDB 3.2.9, RocksDB engine.
The host is a VMWare machine, 8 CPUs, 32G RAM, 32G swap.

The main in-use collection has 309M documents , and it's on-disk size  is about 116GB.
That collection is used heavily by another application host - mostly for read operations, and eventual writes.

Sometimes , the Arangodb fails and restarts. This happens when both RAM and swap memory are totally used (almost no free left).

No messages in arangod.log when the db processes went down, only afterwards regular startup messages.

In /var/log/messages following messages appear (cut) :
...
Jan 22 20:43:16 vm-skarndby5 kernel: Scheduler invoked oom-killer: gfp_mask=0x200da, order=0, oom_score_adj=0
...
Jan 22 20:43:18 vm-skarndby5 kernel: Out of memory: Kill process 3887 (arangod) score 977 or sacrifice child
Jan 22 20:43:18 vm-skarndby5 kernel: Killed process 3887 (arangod) total-vm:462874388kB, anon-rss:31277956kB, file-rss:0kB, shmem-rss:0kB
Jan 22 20:43:20 vm-skarndby5 systemd: arangodb3.service: main process exited, code=killed, status=9/KILL
Jan 22 20:43:20 vm-skarndby5 systemd: Unit arangodb3.service entered failed state.
Jan 22 20:43:20 vm-skarndby5 systemd: arangodb3.service failed.
Jan 22 20:43:25 vm-skarndby5 systemd: arangodb3.service holdoff time over, scheduling restart.
Jan 22 20:43:25 vm-skarndby5 systemd: Starting ArangoDB database server...
Jan 22 20:43:26 vm-skarndby5 systemd: Started ArangoDB database server.
...

My questions are :
Q1. This is a RocksDB engine configuration. As i learned from Arango documentation - RocksDB does allow to use DBs which are larger than the RAM. (And our DB is expected to grow till 1TB in future).
So, why do the failures happen ?
Q2. What is the proper way to avoid "Out of memory. Kill process" failures in ArangoDB with RocksDB engine ?
Q3: Are there any best practices for arangod.conf settings for a large RocksDB database ?
Q4: Are there any best practices for a Linux host hardware/software settings for a ArangoDB sized like ours ?

Best regards and looking forward your assistance,
Avi Vainshtein

**Comment by dothebart** [comment]
Hi, 
there have been more recent discussions on growing memory usage here: 
https://github.com/arangodb/arangodb/issues/11577
resulting in two more configuration option being exposed with ArangoDB 3.7:
https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/
hence I'm closing this now.
