### ISSUE TITLE
Installing a foxx service in docker with a script fails

### ISSUE THREAD

**Issue by servusoft** [arangodb/arangodb#4393]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.1
- [x] 3.2
- [x] 3.3

Mode:
- [x] Single-Server

Storage-Engine:
- [x] mmfiles
- [x] rocksdb

On this operating system:
- [x] Linux 
  - [x] Debian .deb
  - [x] Ubuntu .deb
  - [x] docker - official docker library

### Foxx
These are the steps to reproduce:

1) read README from https://bitbucket.org/servusoft/install-foxx/
2) clone repo `git clone https://bitbucket.org/servusoft/install-foxx.git`
3) reproduce steps 

The following problem occurs: 
The installation of a Foxx service with v3.1 works, but not since v3.2.

Possible duplicate to #4265

**Comment by pluma** [comment]
It looks like you're using unix sockets. Can you verify that the issue also exists without them? The error message sounds like this might not be Foxx related.

**Comment by servusoft** [comment]
I noticed the following behavior in:
with localhost, the installation of a service works well at 3.2 and 3.3!
but only when aranodb has started completely.

but there is the following problem with Docker:
at the time of script execution in `docker-entrypoint-initdb.d`, localhost is not accessible, only via unix socket. When the srripts are executed in docker-entrypoint-initdb.d, arangodb is initialized with unix socket:
https://github.com/arangodb/arangodb-docker/blob/official/docker-entrypoint33.sh#L68-L69

accordingly will also use unix socket
https://github.com/arangodb/arangodb-docker/blob/official/docker-entrypoint33.sh#L105

It may be a misconduct only in docker in combination with unix socket.

**Comment by pluma** [comment]
That sounds more likely. I don't think this is a Foxx issue per se but rather something to do with how arangosh (which btw foxx-manager is a wrapper around) communicates with arangod when using unix sockets.

**Comment by pluma** [comment]
I'd like to keep this off the Foxx label unless we know that there's a specific problem in the Foxx code that is related to this. Given the description so far I'm fairly certain that's not the case. I'm not familiar enough with arangodb-docker and unix sockets to investigate this further.

**Comment by kvahed** [comment]
Please specify  `-v /var/run/docker.sock:/var/run/docker.sock` in your docker tun command. 
Accordingly, please adjust the `init.sh` to attach to the socket:
```--server.endpoint 'http+unix:///var/run/docker.sock' ```. And all is fine

**Comment by servusoft** [comment]
@kvahed: I can not follow your suggestion.

The error occurs in the initialization section:
https://github.com/arangodb/arangodb-docker/blob/official/docker-entrypoint33.sh#L96-L124

To the point ArangoDB only under "unix:///tmp/arangodb-tmp.sock" attainable:
https://github.com/arangodb/arangodb-docker/blob/official/docker-entrypoint33.sh#L68-L72

What helps "--server.endpoint 'http + unix: ///var/run/docker.sock'" at foxx-manager?
The connection via volume "/var/run/docker.sock" causes foxx-manager to communicate with host instance instead of nit docker instance.
I have tested it and the error in 3.3 persists. (I can not install a service with a script)

**Comment by kvahed** [comment]
I confirm that I misunderstood. I am trying to find the reason, why 3.2 and 3.3 both behave differently when compared to 3.1. Thanks for reopening. I have checked, that unix domain sockets are usable within the docker containers in question.

**Comment by kvahed** [comment]
The handling of how Foxx apps are installed changed for 3.2. We are looking into solving the issue.

**Comment by sleto-it** [comment]
Hi,

Version 3.2.12 has been released today
It includes a fix for this problem
Please give it a try and let us know if the issue persists

Many thanks,

**Comment by servusoft** [comment]
Docker 3.2 works fine, good job!
awaiting Docker 3.3.

**Comment by kvahed** [comment]
Thx for reporting

**Comment by plassa-b** [comment]
Hi there, I've been able to install too on 3.2.12, but i've encountered an issue that is probably related to this one : 
When I install a service from a local repository, it works fine but if scripts are defined in the manifest.json, I get the following error
```
ArangoError 3103: failed to invoke module
File: /var/lib/arangodb3-apps/_db/_system/my-service/APP/scripts/setup.js
```

I'm guessing it is indeed a bug because, if I removed the scripts entry from manifest.json, the install works, and if I add it back after install, and do an upgrade, my scripts do show up without any error in the foxx interface.

**Comment by pluma** [comment]
This sounds like the script itself is causing an error. "Failed to invoke module" usually means something went wrong. The setup script is run automatically on install by default.

Can you check the arangod log for the lines immediately preceding and following that error? You should see a stacktrace indicating what caused the script to fail.

**Comment by plassa-b** [comment]
It was indeed an issue on my end. Sorry about that, I didn't know the setup was ran on installation.

**Comment by maxkernbach** [comment]
Thanks for reporting.

I am closing this issue as versions 3.2.12 and 3.3.4 including the fix for this bug are released.
Please feel free to reopen if this problem persists with 3.3.4.

**Comment by servusoft** [comment]
Hi guys, 
I think installing a Foxx apps in Docker with a script is a very useful thing.
It would also be desirable for a non-docker installation similar to a script certain configuration of the server make (users, rights ...). This can be achieved with arangosh, but it should also be done during installation and once run immediately after installation. The goal should be to get a ready configured system after an installation. Fine would be that also works in cluster mode.
Is this already available (for non docker serup)?
