### ISSUE TITLE
How to create a username and password for Sign in  ArangoDB Web Interface

### ISSUE THREAD

**Issue by CengSin** [arangodb/arangodb#4404]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [x] 3.3
- [ ] self-compiled devel branch

Mode:
- [x] Cluster
- [ ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [x] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [x] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click to ...
...

The following problem occurs: [Screenshot?] 
i hope can set a user and password for sign in arangodb web interface, instead now of not password.
i use cluster.

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

**Comment by jsteemann** [comment]
I am sorry, but I don't understand the question.
Can you please elaborate a bit on what you are trying to achieve, and how exactly you start the cluster (and with which options)? That way we do not have to guess. Thanks!

**Comment by CengSin** [comment]
#### How to set up a password for the cluster user?
##### I want to set up a login user for my database instead of going directly to the control interface.The current data is a direct login control interface(example : http://127.23.7.45:8529).

**Comment by jsteemann** [comment]
Sorry to repeat myself, but for this we do need to know how you actually started the cluster and with what options. As there are multiple possible ways for this and it is not obvious from your question, please come back with your startup commands for ArangoDB and/or the configuration you used. Thanks!

**Comment by CengSin** [comment]
started the cluster :  ` arangodb -starter.join xxx.xxx.xxx.xxx,xxx.xxx.xxx.xxx,xxx.xxx.xxx.xxx`
default started the cluster，arangodb.config is 12G RAM, 250G ROM, three Node

**Comment by jsteemann** [comment]
Ok, so you are using the starter as it seems.
Have you checked this section of the starter manual for the authentication options?
https://github.com/arangodb-helper/arangodb#authentication-options

**Comment by CengSin** [comment]
Thanks so so so so much

**Comment by CengSin** [comment]
emmmmm, You misunderstand what I mean. I want to use password for web interface.

![Arangodb](http://p09lqtmdg.bkt.clouddn.com/Arangodb_web_interface.png)

i hope it need Loginer to input password before this page .

**Comment by jsteemann** [comment]
Have you started the server with authentication or not?

**Comment by CengSin** [comment]
no , i use the default set, so , i don't know how to set authentication for cluster

**Comment by jsteemann** [comment]
From https://github.com/arangodb-helper/arangodb#authentication-options:

> The arango starter by default creates a cluster that uses no authentication.
> To create a cluster that uses authentication, create a file containing a random JWT secret (single line) and pass it through the --auth.jwt-secret-path option.

Can you try this?

**Comment by CengSin** [comment]
my boss say this is use http protocol , it's not to set a use for web interface, :-(

**Comment by jsteemann** [comment]
Sorry I don't think I can help. 

Either you turn on the authentication using the option I pointed you to (which has nothing to do with the protocol), or you leave it turned off. 
But then there will be no authentication.

**Comment by CengSin** [comment]
OK, thank so much

**Comment by wjx-git** [comment]
你好，请问你的问题解决了吗？我这边在集群情况下用web interface登陆也是不需要user和password，直接就进入使用界面了，但是用arangosh登陆时需要user和password。

**Comment by wjx-git** [comment]
你好，请问你的问题解决了吗？我这边在集群情况下用web interface登陆也是不需要user和password，直接就进入使用界面了，但是用arangosh登陆时需要user和password。

**Comment by dothebart** [comment]
english or german please.

**Comment by wjx-git** [comment]
In the case of cluster, when I log in the database through the Web Interface, there is no need username and password, but it is need when use arangosh

**Comment by dothebart** [comment]
you can use the root-user (as its filled in in the webinterface for you) and specify an empty password:

```
arangosh --server.endpoint tcp://127.0.0.1:8530 --server.username root --server.password '' 
```

Arangosh doesn't do an extra invokation to the server in advance to detect whether it has authentification enabled.

**Comment by wjx-git** [comment]
thank you very much! It's weekend now. I can't try it until I get back to the company next week. 哈哈哈

**Comment by wjx-git** [comment]
> as its filled in in the webinterface for you
The question is I don't need fill in username and password in the web interface and access directly after I enter http://192.168.52.132:8529 in the browser, there seems to be a lack of authentication here.  Authentication is exactly what I need, and how can I add it in the web interface?

**Comment by Simran-B** [comment]
If authentication is disabled on the server-side, then the web interface skips the logon step and goes to the database selection dialog.

Arangosh is a client tool and does not know whether authentication is enabled or disabled on the server-side. The option `server.authentication` exists in arangosh and defaults to true, which means it assumes that the server has authentication enabled and therefore it will ask for credentials.

The default user name arangosh will try is `root`. If you haven't configured users and authentication on the server-side, then you only see it asking for a password for user `root` (even though the server isn't even asking for credentials with authentication turned off). If there is no authentication configured for the server, then you can either hit return in arangosh for a blank password and it will connect. Or you set `server.authentication` for arangosh to `false` to skip the logon step on the client side, or you provide an empty password like `server.password ''`.

Only because arangosh asks for a password doesn't make your cluster more secure. What you need is to configure authentication on the server-side, as jsteemann already told you.
