### ISSUE TITLE
Graph traversals in AQL .  How graph traversals get benefit from Edges and Vertex collection index?

### ISSUE THREAD

**Issue by gerogexiongle** [arangodb/arangodb#4406]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ yes] 3.2
- [ ] 3.3
- [ ] self-compiled devel branch

Mode:
- [ yes] Cluster
- [ ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
   centos

### this is an AQL-related issue:
[ yes] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I have a lot of vertex collection ,and edges collection on a graph ,and there a some idex on vertex and edge for just some fileds.
  For example there have a KnowledgeGraph graph which contains vertexs collection A,B,C,D and edge collection edge1,edge2,edge3.  The idex filed of A Vertex collection is named “name”,so as B,C,D. The idex filed of edge3 collection is named “price”
 
![kowledge](https://user-images.githubusercontent.com/35757729/35325217-0bd68458-012e-11e8-8f89-3f15db298379.png)

When I traversals the graph form A->D and just use edge3 property (a idex) to filter vertex. 
AQL like this :
with A,B,C,D
  FOR u in A
    FOR v,e,p IN 1..3 INBOUND CONCAT('A/',u.uuid)  edges1, edge2,edge3 
         FILTER e.prcie>200
 RETURN v

My question 1 :  For this case , traversal is A->B->C->D use edge3 idex to filer , Does the index play a big role or it doesn't work? Can this traversal mode begins with the edge of the index?  in other words  the edge3 attribute condition is first matched and the filter sequence link is like this: edge3 ,C,B,A and then return D .

My question 2: Does this function SAME_COLLECTION have an index?
“FOR v,e,p IN ....
        FILTER e.xxx = yyyy 
        FILTER IS_SAME_COLLECTION("xxx", e) // Is index here？ ”

**Comment by kvahed** [comment]
Please let Arangodb UI answer many of the things you are wondering about above. Go to the Queries section of the UI and instead of clicking *Execute* on your specific query, click on *Explain*. You will see a human readable execution plan for your query; i.e. which indexes are used for which individual parts of the query and where full collection scans may slow things down etc. 
If you have any specific questions, which are not obviously addressed by *Explain*, we are too happy to help.
