### ISSUE TITLE
 arangodb efficiency issue

### ISSUE THREAD

**Issue by feitianstyle** [arangodb/arangodb#4407]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [* ] 3.3
- [ ] self-compiled devel branch

Mode:
- [ *] Cluster
- [ ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [ *] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [* ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [* ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

Hi, great arangodb team,I have a problem I do not understand.For example, a cluster has three nodes,
each node is agent, coordinate, and dbserver,I execute an aql query on a node,The implementation plan is as follows:

Query string:
 FOR v,p IN outbound 
     SHORTEST_PATH @startnode
     TO @endnode
     GRAPH @graphname options {bfs:true}
     filter v.c_id==@c_id
     return v
     

Execution plan:
 Id   NodeType           Site           Est.   Comment
  1   SingletonNode      COOR              1   * ROOT
  2   ShortestPathNode   COOR       10000000     - FOR v  /* vertex */, p  /* edge */ IN OUTBOUND SHORTEST_PATH 'contact_vertex/f69375e854a34250986399d1909c0776' /* startnode */ TO 'contact_vertex/e11a10f848cd4a4392b8f10ea307eac9' /* targetnode */ GRAPH 'an'
  3   CalculationNode    COOR       10000000     - LET #4 = (v.`c_id` == -2147483643)   /* simple expression */
  4   FilterNode         COOR       10000000     - FILTER #4
  5   ReturnNode         COOR       10000000     - RETURN v

Indexes used:
 none

Shortest paths on graphs:
 Id   Vertex collections   Edge collections
  2   contact_vertex       contact_edge       

Optimization rules applied:
 none

I want to know if the querying task is distributed on one node or all nodes?In other words, the query is whether the task is distributed computing?
As in the above query,I have a lot of data,I have two collection, one vertexes collection and one edge collection,I use the default index,two collection constituted a graph,there is no way to quickly improve the search speed?For example, set the index, improve the query memory, and so on.Or some other suggestions, I hope you can help me.

**Comment by kvahed** [comment]
The answer to your question is that it depends upon how you shard the collections in question. In order to be able to use all db server nodes for your queries, you would have to distribute your data on all servers. However, as you are querying a graph you should be very aware of said distribution on multiple db servers. You can slow things down quite a lot. 
The enterprise edition, which is unlimited free for evaluation, include so-called smart graphs, which allow for fast distribute graph traversals. There is a lot of things that need to be considered, when graphs are parallelised.
