### ISSUE TITLE
distributeShardsLike missing from the HTTP API documentation

### ISSUE THREAD

**Issue by dothebart** [arangodb/arangodb#4408]
Though https://docs.arangodb.com/3.3/Manual/DataModeling/Collections/DatabaseMethods.html describes the distributeShardsLike property, its missing from the http api documentation in
`Documentation/DocuBlocks/Rest/Collections/JSF_post_api_collection.md`

**Comment by kvahed** [comment]
Documentation in 3.2, 3.3, devel added
