### ISSUE TITLE
Update : GeoIndex document read NotFound in RocksDBTrxMethods

### ISSUE THREAD

**Issue by matcho** [arangodb/arangodb#4435]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.3

Mode:
- [x] Single-Server

Storage-Engine:
- [x] rocksdb

On this operating system:
  - [x] Debian .deb

### this is an AQL-related issue:

When updating a collection with 1.5 millions docs having a `geo` index, the following error occurs after around :
`Query: AQL: GeoIndex - document read NotFound: Get - in RocksDBTrxMethods (while executing)`

![arangodb-geoindex-update-error](https://user-images.githubusercontent.com/2674752/35397401-a8d0ab0a-01ef-11e8-96bd-a4b3df848053.jpg)

Removing the `geo` index fixes the issue (the collection has many other `hash` indexes).

Might be related to #3447 ? That issue had been fixed and had not happened to me again until now.

Thanks a lot,
Mathias

**Comment by jsteemann** [comment]
@matcho Does the problem occur again after re-creating the geo index on the same collection?
The expectation is that it should not occur after dropping the geo index(es) on the collection and re-creating it/them with the same properties as before. Can you check if this is the case? Thanks!

**Comment by matcho** [comment]
@jsteemann I confirm that the problem does not occur anymore after re-creating the geo index, the query completes without error.

**Comment by jsteemann** [comment]
Sorry, one extra question: has the database in question been created initially with ArangoDB 3.2.x or with 3.3.x? I would expect the database was created initially with a 3.2.x release before 3.2.8. Is that correct?

**Comment by matcho** [comment]
The database was initially created with 3.2.4, then updated many times until 3.3.3.
But the collection and the index were created meanwhile, quite recently, probably with 3.3.2 iirc.

Do I have to delete and re-create the whole database, then restore all collections ?

Hope that helps.
Thanks again.

**Comment by jsteemann** [comment]
There is no need to re-create the whole database IMHO.
I am aware of an issue with RocksDB-based geo indexes, which should have been resolved around between 3.2.6 and 3.2.8. Geo indexes created before may have issues so dropping them and re-creating them should be enough. But if the collection and index were created with 3.3.2, then it sounds like a different issue. Is it somehow reproducible?

**Comment by matcho** [comment]
I guess reproducing the issue would imply downgrading to < 3.2.6.
Unfortunately I can't do this now but I'll try asap and get back to you.

**Comment by jsteemann** [comment]
Sorry for the confusion. I wasn't suggesting to downgrade to 3.2, I was just curious whether it happens reproducibly in 3.3  with collections/indexes that definitely have been created with 3.3 and not 3.2.

**Comment by matcho** [comment]
OK sorry. Well it hasn't happened again for the moment (after deleting and re-creating the geo index) and we're updating the data quite frequently, but I'll let you know if anything pops up.
Thanks

**Comment by jsteemann** [comment]
Ok, thanks.

**Comment by maxkernbach** [comment]
Hi @matcho,

did you have a chance to test version 3.3.3 in the last weeks? Has the geo index error occurred once again after re-creating the index?

**Comment by matcho** [comment]
Hi @maxkernbach,

We're running on 3.3.3 for a while now, and just installed 3.3.4.
The issue didn't occur anymore for a while, I guess it can be considered OK.

Thanks

**Comment by OmarAyo** [comment]
Hi @matcho 

I am going to close this ticket, feel free to re-open it again if you have any related issues.

Best

**Comment by matcho** [comment]
Hi everyone,

"Oh no, it happened again" :)

While performing lots of small updates on a 2M docs collection (the same as in OP), AQL UPDATE query fails with error `ArangoError: GeoIndex - document read NotFound: Get - in RocksDBTrxMethods`.

After running it 4 times, it happens that the query succeeds on a few hundred docs and always fails on the same doc. ( _key: "1000039843" ). Opening the doc in aardvark works, the doc is here and has nothing particular.

This issue had not occurred for a long time (months) while we were performing the same kind of queries. But, we recently updated from 3.3.8 to 3.3.9, and the index was not deleted / re-created since. Maybe it's related ?

Note that this bunch of queries was executed successfully a few times after updating ArangoDB to 3.3.9; it suddenly started failing this afternoon, and I can't see what else could have changed…

As before, I'll try removing / re-creating the geo index.

Thanks for your consideration,
Mathias

See complete ArangoJS error below :
```
{ ArangoError: GeoIndex - document read NotFound: Get - in RocksDBTrxMethods
    at new ArangoError (/home/chouet/dev/pn-v2-data-access-layer/node_modules/arangojs/lib/cjs/error.js:67:21)
    at Object.resolve (/home/chouet/dev/pn-v2-data-access-layer/node_modules/arangojs/lib/cjs/connection.js:220:32)
    at _hosts.(anonymous function) (/home/chouet/dev/pn-v2-data-access-layer/node_modules/arangojs/lib/cjs/connection.js:96:26)
    at callback (/home/chouet/dev/pn-v2-data-access-layer/node_modules/arangojs/lib/cjs/util/request.node.js:36:13)
    at IncomingMessage.res.on (/home/chouet/dev/pn-v2-data-access-layer/node_modules/arangojs/lib/cjs/util/request.node.js:47:17)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  isArangoError: true,
  response: 
   IncomingMessage {
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: false,
     domain: null,
     _events: { end: [Array], data: [Function] },
     _eventsCount: 2,
     _maxListeners: undefined,
     socket: 
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: 'woevre.cirad.fr',
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: false,
        _bytesDispatched: 569856,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: null,
        [Symbol(asyncId)]: -1,
        [Symbol(bytesRead)]: 0 },
     connection: 
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: 'woevre.cirad.fr',
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: false,
        _bytesDispatched: 569856,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: null,
        [Symbol(asyncId)]: -1,
        [Symbol(bytesRead)]: 0 },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers: 
      { 'x-content-type-options': 'nosniff',
        server: 'ArangoDB',
        connection: 'Keep-Alive',
        'content-type': 'application/json; charset=utf-8',
        'content-length': '120' },
     rawHeaders: 
      [ 'X-Content-Type-Options',
        'nosniff',
        'Server',
        'ArangoDB',
        'Connection',
        'Keep-Alive',
        'Content-Type',
        'application/json; charset=utf-8',
        'Content-Length',
        '120' ],
     trailers: {},
     rawTrailers: [],
     upgrade: false,
     url: '',
     method: null,
     statusCode: 404,
     statusMessage: 'Not Found',
     client: 
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: 'woevre.cirad.fr',
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: false,
        _bytesDispatched: 569856,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: null,
        [Symbol(asyncId)]: -1,
        [Symbol(bytesRead)]: 0 },
     _consuming: true,
     _dumped: false,
     req: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: false,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'PATCH /_db/mydb/_api/document/mycollection/1000039843?keepNull=false&waitForSync=true&returnNew=true HTTP/1.1\r\nauthorization: Basic blabla=\r\ncontent-type: application/json\r\nx-arango-version: 30000\r\ncontent-length: 577\r\nHost: myhost.com:8529\r\nConnection: keep-alive\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'PATCH',
        path: '/_db/mydb/_api/document/mycollection/1000039843?keepNull=false&waitForSync=true&returnNew=true',
        _ended: true,
        res: [Circular],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        [Symbol(outHeadersKey)]: [Object] },
     read: [Function],
     body: 
      { error: true,
        errorMessage: 'GeoIndex - document read NotFound: Get - in RocksDBTrxMethods',
        code: 404,
        errorNum: 1202 },
     host: 0 },
  statusCode: 404,
  errorNum: 1202,
  code: 404 }
```

**Comment by matcho** [comment]
Hello,

The problem has not occurred for quite a long time now.
But the fact is we're not making as many large updates as before on this data…
We just updated to 3.3.12 (this morning); we'll let you know if it happens again.

**Comment by vinaypyati** [comment]
Thanks! Please reopen the ticket if the issue happens again.
