### ISSUE TITLE
Aardvark shows wrong collection when switching from one to another

### ISSUE THREAD

**Issue by matcho** [arangodb/arangodb#4441]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.3
Mode:
- [x] Single-Server
Storage-Engine:
- [x] rocksdb
On this operating system:
  - [x] Debian .deb

### this is an Aardvark-related issue:
I'm using Aardvark with Firefox 58 under Ubuntu 16.04.3.

### steps to reproduce the issue
(can't attach a screencast video here, but I can PM one if needed)

 * go to "collections" panel, click collection A
 * go back to "collections" panel, click collection B
 * go back to "collections" panel, click collection A again
 * => docs from collection A are shown, but name "B" is displayed on top of the tabs selector

More dangerous, if one does not notice the wrong collection name displayed, and goes to "settings" tab, the settings apply to the collection identified by the **name displayed**, that is **not** the one you clicked ! We discovered this after deleting a collection… well, not the right one :-) hopefully it was only test data.

Note: sometimes the issue happens at step 2, and clicking any collection at step 3 makes it happen too.

Thanks,
Mathias

**Comment by hkernbach** [comment]
What exact version of ArangoDB are you using? This issue should have already been resolved by now.

**Comment by hkernbach** [comment]
Update: The bugfix is already available, but not part of the current v3.3.2 
It will be included in the upcoming v3.3.3 release.

**Comment by matcho** [comment]
Thanks for the quick answer !

**Comment by sleto-it** [comment]
Hi,

3.3.3 has been released. I am closing this ticket now. Please feel free to reopen if the problem persists

Many thanks,
