### ISSUE TITLE
arangodb.shutdown() function is close the connectPool or close arangodb in the arangodb-java-driver

### ISSUE THREAD

**Issue by CengSin** [arangodb/arangodb#4444]
arangodb.shutdown() function is close the connectPool or close arangodb in the arangodb-java-driver

![image](https://user-images.githubusercontent.com/23357893/35427935-46eda6be-02a7-11e8-827c-4d7b9e661e19.png)

if not, how can i to close the connection in Pool?

**Comment by mpv1989** [comment]
`shutdown()` closes the connection pool and every open connection to the db.

_If you have further questions I highly suggest you to join our [community slack](https://slack.arangodb.com/) or post you questions on [StackOverflow](https://stackoverflow.com/). We use these channels for questions and github for bugs. Especially Slack should provide better response times._
