### ISSUE TITLE
Seeking better AQL / Foxx error handling

### ISSUE THREAD

**Issue by davidmw** [arangodb/arangodb#4484]
As of 3.3.3 it seems difficult to build non-trivial queries that can fail early and cleanly. By this I mean when an error situation is detected it is difficult to structure AQL to abort rather than continue to execute the rest of script.

_Use case:  Script takes a document ID as a parameter. The script runs a traversal starting at the ID, building an array of IDs. Several array operations are then performed with user functions. The resulting array of IDs is iterated, queries are done and we build an array of documents to return.

If the parameter document ID fails to return a valid DOCUMENT() the rest of the script should not be executed. There may be multiple failure modes related to COUNTs, existence of document, etc. and we should assume that some of the subsequent query steps will execute pointlessly since there is no good way to test for error conditions at each step. _ 

When AQL is used in a Foxx service the response validator will be unnecessarily complex if it must determine if a response document is actually a hint that something in the query failed. The logic to determine the error type really doesn't belong in the front end either.

I'm looking for a new AQL function to let the developer determine what defines an error state and abort the AQL when that condition is met while also sending back a reason code.

For example:
LET startDoc = DOCUMENT( ${startID} )
ABORT_IF(startDoc == null, '502', CONCAT(${startID}, " is missing or invalid"))

Unlike the unsupported `FAIL()` `ABORT_IF()` will not generate stacktrace or other complexity. Just terminate the AQL query and give me a way to return an error code to Foxx so that an appropriate HTTP response can be sent back to the caller.

**Comment by Simran-B** [comment]
Should be fulfilled by the following PR: https://github.com/arangodb/arangodb/pull/4584

**Comment by Simran-B** [comment]
The AQL functions `ASSERT()` and `WARN()` are available in 3.4 and 3.5:
https://www.arangodb.com/docs/stable/aql/functions-miscellaneous.html#assert--warn
