### ISSUE TITLE
Slow sort with join

### ISSUE THREAD

**Issue by gurisko** [arangodb/arangodb#4489]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [x] 3.3
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [x] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [x] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
- [ ] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

### Query A:
```
FOR city IN cities
    LIMIT 1000
    RETURN {city, cityName}
```
Speed: ~15ms

### Query B:
```
FOR city IN cities
    LET cityName = FIRST(FOR c IN cities FILTER c._key == city._key RETURN c).city
    LIMIT 1000
    RETURN {city, cityName}
```
Speed: ~15ms

### Query C:
```
FOR city IN cities
    SORT city.latitude ASC
    LIMIT 1000
    RETURN {city}
```
Speed: ~1.6s

### Query D:
```
FOR city IN cities
    SORT city.latitude ASC
    LIMIT 1000
    RETURN {city, cityName: 'Just Another Amazing Gluten Free Hipster City'}
```
Speed: ~1.65s

### Query E:
```
FOR city IN cities
    LET cityName = FIRST(FOR c IN cities FILTER c._key == city._key RETURN c).city
    SORT city.latitude ASC
    LIMIT 1000
    RETURN {city, cityName}
```
Speed: ~5s

### Comparison Table
| Query        | Speed (~s) |
| ------------- |:-------------:|
| A | 0.015 | 
| B | 0.015      |
| C | 1.600      | 
| D | 1.650      | 
| E | 5.000     |

I don't understand why would query E be so much slower than query D while queries A and B performed similarly.

### Query F:
```
FOR city IN cities
    SORT city.latitude ASC
    LIMIT 1000
    LET cityName = FIRST(FOR c IN cities FILTER c._key == city._key RETURN c).city
    RETURN {city, cityName}
```
Speed: ~1.7s

I do understand that we can write this as query F but one would expect query E to do this on its own.

The issue can be reproduced using this dataset: cities

**Comment by vinaypyati** [comment]
After reproducing, here is the comparison table. 

A and B seem similar queries.

| Query  | Time |
| -------------- | -------------- |
| A & B| ~20 ms  |
| C  | 1.353 s  |
| D | 1.295 s  |
| E  | 5.408 s  |
| F | 1.366 s  |

Query-E Profiling says that 4.95 s are taken by query execution.

Explain
![image](https://user-images.githubusercontent.com/34657484/35747599-194863ee-084b-11e8-8faa-55ce8898f582.png)

**Comment by jsteemann** [comment]
Is there any sorted index on `cities.latitude`, i.e. a skiplist index?
Otherwise the subquery will be executed 316848 times, then the results will be sorted and only 1000 elements (with lowest latitude values) will be returned.
If the index does not exist, can you try creating it (`db.cities.ensureIndex({ type: "skiplist", fields: ["latitude"] });`?

**Comment by gurisko** [comment]
@jsteemann index would definitely help to speed up everything (to couple ms in all cases). But the point I am trying to make is that there is a space for optimization by not executing the subquery until sort and limit are applied if the variable to which the subquery result is assigned is not used for sorting.

**Comment by jsteemann** [comment]
I think adding the index will not change how often the subquery will be executed. It would just speed it up.
Yes, you are right. In this case the subquery could be moved safely to after the `SORT...LIMIT` part of the query.

**Comment by gurisko** [comment]
This is 6 years old. Let's just close it :)
