### ISSUE TITLE
Restore truncated collection documents using WAL files

### ISSUE THREAD

**Issue by saalihou** [arangodb/arangodb#4491]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [x] 3.2
- [ ] 3.3
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [ ] mmfiles
- [x] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [x] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

Hello,

I purposefully truncated a collection (no backup has been made before). I now want to restore the removed documents. I know this will be no easy task but after some research, I found out that there are Write-Ahead Log files stored in the journals folder (a bunch of `.db` files). I was wondering if those can be of any help in recovering them and what would be the procedure.

Thank you for your help.

ps: I've already tried stackoverflow (https://stackoverflow.com/questions/48587423/rollback-arangodb-database-to-a-specific-point-in-time) and slack to no avail. That is why I'm asking here.

**Comment by Simran-B** [comment]
Hi @saalihou,

you filled out the environment questionnaire with RocksDB as storage engine. If I check my local ArangoDB instance with RocksDB storage engine, there are only .sst files and a .log file in the journals sub-folder. So you seem to refer to MMFiles storage engine when you talk about write-ahead logs in .db files.

Regardless of the storage engine, the problem as I see it is that you want to truncate a collection, which removes the data from the data files, and then reconstruct it from write-ahead logs. These log files are transient however. They are not kept around forever, at least not in a default configuration. If you wanted to recover your data from WALs alone, you would need to retain all of them, and of course be able to understand the contained information and make use of it - which is normally up to the storage engine. For MMFiles, our developers know how the WALs are structured because they built the system that uses them, but for RocksDB, that knowledge is mostly with the RocksDB developers.

There is no out-of-the-box tool to recover data seldom from WALs as far as I'm aware.

**Comment by saalihou** [comment]
Hi @Simran-B 

Thank you for your prompt response. I was under the impression that I was using the rocksdb engine. There is a `rocksdb` folder in my database directory.
Here is what I got in my journals folder:
```
-rw-r----- 1 saalihou saalihou  32M san 30 10:37 logfile-15548761.db
-rw-r----- 1 saalihou saalihou  32M san 30 10:37 logfile-15548791.db
-rw-r----- 1 saalihou saalihou  32M san 30 13:55 logfile-15548885.db
-rw-r----- 1 saalihou saalihou  32M san 30 13:55 logfile-15548915.db
-rw-r----- 1 saalihou saalihou  32M san 30 13:59 logfile-15576261.db
-rw-r----- 1 saalihou saalihou  32M san 30 13:59 logfile-15576291.db
-rw-r----- 1 saalihou saalihou  32M fee  1 03:07 logfile-15576606.db
-rw-r----- 1 saalihou saalihou  32M fee  2 12:13 logfile-15576636.db
-rw-r----- 1 saalihou saalihou  32M fee  2 15:35 logfile-15576637.db
-rw-r----- 1 saalihou saalihou  32M fee  2 15:35 logfile-15770645.db
-rw-r----- 1 saalihou saalihou  32M fee  3 08:18 logfile-16060158.db
-rw-r----- 1 saalihou saalihou  32M fee  2 15:35 logfile-16060188.db
-rw-r----- 1 saalihou saalihou  32M fee  2 15:35 logfile-16060189.db
```

And here is what I got in the rocksdb folder:
```
-rw-r--r-- 1 saalihou saalihou    0 fee  2 15:35 000144.log
-rw-r--r-- 1 saalihou saalihou   16 fee  2 15:35 CURRENT
-rw-r--r-- 1 saalihou saalihou   37 now 22 16:02 IDENTITY
-rw-r--r-- 1 saalihou saalihou    0 now 22 16:02 LOCK
-rw-rw-r-- 1 saalihou saalihou  15K fee  3 11:08 LOG
-rw-r--r-- 1 saalihou saalihou  15K now 22 16:02 LOG.old.1511366543395297
-rw-r--r-- 1 saalihou saalihou  15K now 22 16:02 LOG.old.1511366549232169
-rw-r--r-- 1 saalihou saalihou  15K now 22 16:42 LOG.old.1511368941710338
-rw-r--r-- 1 saalihou saalihou  15K now 22 16:46 LOG.old.1511369211940182
-rw-r--r-- 1 saalihou saalihou  15K now 23 09:00 LOG.old.1511427613366216
-rw-r--r-- 1 saalihou saalihou  15K now 28 15:32 LOG.old.1511883159227400
-rw-r--r-- 1 saalihou saalihou  15K now 28 15:52 LOG.old.1511884330965923
-rw-r--r-- 1 saalihou saalihou  15K des  4 11:51 LOG.old.1512388309375653
-rw-r--r-- 1 saalihou saalihou  15K des  5 12:51 LOG.old.1512478274513711
-rw-r--r-- 1 saalihou saalihou  15K des  5 12:51 LOG.old.1512478317688740
-rw-r--r-- 1 saalihou saalihou  15K des  5 18:56 LOG.old.1512500159675108
-rw-r--r-- 1 saalihou saalihou  15K des 11 11:19 LOG.old.1512991179028276
-rw-r--r-- 1 saalihou saalihou  15K des 11 13:51 LOG.old.1513000260564021
-rw-r--r-- 1 saalihou saalihou  15K des 11 13:54 LOG.old.1513000461428151
-rw-r--r-- 1 saalihou saalihou  15K des 11 13:54 LOG.old.1513000488581686
-rw-r--r-- 1 saalihou saalihou  15K des 12 13:22 LOG.old.1513084932662973
-rw-r--r-- 1 saalihou saalihou  15K des 21 13:08 LOG.old.1513861699193716
-rw-r--r-- 1 saalihou saalihou  15K des 26 12:04 LOG.old.1514289894211627
-rw-r--r-- 1 saalihou saalihou  15K des 26 12:05 LOG.old.1514289942919304
-rw-r--r-- 1 saalihou saalihou  15K des 28 14:21 LOG.old.1514470886850359
-rw-r--r-- 1 saalihou saalihou  15K des 28 15:50 LOG.old.1514476215005860
-rw-r--r-- 1 saalihou saalihou  15K des 28 19:32 LOG.old.1514489530299427
-rw-r--r-- 1 saalihou saalihou  15K san  1 14:48 LOG.old.1514818131072937
-rw-r--r-- 1 saalihou saalihou  15K san  3 11:41 LOG.old.1514979664370019
-rw-r--r-- 1 saalihou saalihou  15K san 11 12:25 LOG.old.1515673531435597
-rw-r--r-- 1 saalihou saalihou  15K san 11 14:29 LOG.old.1515680952415692
-rw-r--r-- 1 saalihou saalihou  15K san 11 15:12 LOG.old.1515683560978887
-rw-r--r-- 1 saalihou saalihou  15K san 11 15:18 LOG.old.1515683880543807
-rw-r--r-- 1 saalihou saalihou  15K san 11 15:33 LOG.old.1515684794806737
-rw-r--r-- 1 saalihou saalihou  15K san 14 14:31 LOG.old.1515940309876981
-rw-r--r-- 1 saalihou saalihou  15K san 14 18:33 LOG.old.1515954800462162
-rw-r--r-- 1 saalihou saalihou  15K san 15 18:58 LOG.old.1516042734103398
-rw-r--r-- 1 saalihou saalihou  15K san 17 13:06 LOG.old.1516194396973860
-rw-r--r-- 1 saalihou saalihou  15K san 17 13:42 LOG.old.1516196564690265
-rw-r--r-- 1 saalihou saalihou  15K san 18 13:50 LOG.old.1516283403751187
-rw-r--r-- 1 saalihou saalihou  15K san 19 12:01 LOG.old.1516363313110182
-rw-r--r-- 1 saalihou saalihou  15K san 22 12:33 LOG.old.1516624390939817
-rw-r--r-- 1 saalihou saalihou  15K san 23 12:35 LOG.old.1516710943233793
-rw-r--r-- 1 saalihou saalihou  15K san 23 15:24 LOG.old.1516721097566519
-rw-r--r-- 1 saalihou saalihou  15K san 24 12:39 LOG.old.1516797577311743
-rw-r--r-- 1 saalihou saalihou  15K san 29 14:29 LOG.old.1517236181223992
-rw-r--r-- 1 saalihou saalihou  15K san 29 15:15 LOG.old.1517238936569646
-rw-r--r-- 1 saalihou saalihou  15K san 30 10:36 LOG.old.1517308591933964
-rw-r--r-- 1 saalihou saalihou  15K san 30 10:37 LOG.old.1517308676675484
-rw-r--r-- 1 saalihou saalihou  15K san 30 13:55 LOG.old.1517320514360817
-rw-r--r-- 1 saalihou saalihou  15K san 30 13:59 LOG.old.1517320779625325
-rw-r--r-- 1 saalihou saalihou  15K fee  2 15:35 LOG.old.1517585729763852
-rw-r--r-- 1 saalihou saalihou  15K fee  2 15:35 LOG.old.1517655633191634
-rw-rw-r-- 1 saalihou saalihou  15K fee  3 11:00 LOG.old.1517655633192993
-rw-rw-r-- 1 saalihou saalihou  15K fee  3 11:00 LOG.old.1517655643325134
-rw-rw-r-- 1 saalihou saalihou  15K fee  3 11:00 LOG.old.1517655643326429
-rw-rw-r-- 1 saalihou saalihou  15K fee  3 11:00 LOG.old.1517656081899579
-rw-rw-r-- 1 saalihou saalihou  15K fee  3 11:08 LOG.old.1517656081902350
-rw-r--r-- 1 saalihou saalihou   52 fee  2 15:35 MANIFEST-000143
-rw-r--r-- 1 saalihou saalihou 4,2K san 30 13:59 OPTIONS-000143
-rw-r--r-- 1 saalihou saalihou 4,2K fee  2 15:35 OPTIONS-000146
```

If it can be of any help I can upload the zip I have of the database folder.

Regarding the fact that wal logs are transient, I have ones that date back to the 30th of January as you can see in the above output. I would be glad if I could at least get back some modifications that have been done back then. If there is even a slight chance that a process might work (even if it's a complicated one), I'm ready to go through it (I got a cup of coffee ready :coffee:)

**Comment by dothebart** [comment]
As @Simran-B pointed out, there is no easy way to do this. 
Hence closing as `won't fix`.
