### ISSUE TITLE
NEIGHBORS deprecated in 3.x - update docs

### ISSUE THREAD

**Issue by joergwork** [arangodb/arangodb#4502]
### this is a documentation related issue:

Documentation/Books/Cookbook/AQL/Joins.md 

still tells about using the NEIGHBORS aql method, which is deprecated: https://docs.arangodb.com/3.1/Manual/ReleaseNotes/UpgradingChanges30.html

**Comment by Simran-B** [comment]
3.2, 3.3 and devel documentation were updated, see e.g. https://docs.arangodb.com/3.3/Cookbook/AQL/Joins.html

We don't maintain 3.0 and 3.1 docs anymore, thus closing as fixed.
