### ISSUE TITLE
Broken links to 2.8 -> 3.0 migration guides in release notes

### ISSUE THREAD

**Issue by goedderz** [arangodb/arangodb#4505]
On the page _Incompatible changes in ArangoDB 3.0_, the following links are broken:

* Migrating GRAPH_* Functions from 2.8 or earlier to 3.0
* Migrating GRAPH_* Measurements from 2.8 or earlier to 3.0
* Migrating anonymous graph functions from 2.8 or earlier to 3.0

This affects the 3.1, 3.2 and 3.3 docs:

* https://docs.arangodb.com/3.1/Manual/ReleaseNotes/UpgradingChanges30.html
* https://docs.arangodb.com/3.2/Manual/ReleaseNotes/UpgradingChanges30.html
* https://docs.arangodb.com/3.3/Manual/ReleaseNotes/UpgradingChanges30.html

The linked documents are still there in the current Cookbook, only the links are broken.

**Comment by Simran-B** [comment]
Fix available for 3.3: #4520 

Probably affects all other versions but 2.8 as well

**Comment by maxkernbach** [comment]
@Simran-B 
The links are fixed for the 3.3 docs. Is it sufficient to only fix the current version for now or should 3.1 and 3.2 also get fixed before closing this issue?

**Comment by sleto-it** [comment]
only for 3.2, please

**Comment by Simran-B** [comment]
PR 3.2 got merged https://github.com/arangodb/arangodb/pull/4905
and I just published a new documentation build.
