### ISSUE TITLE
Log menu in cluster mode causes confusion - please hide or enable

### ISSUE THREAD

**Issue by sleto-it** [arangodb/arangodb#4508]
3.2 and up - cluster mode

**Comment by sleto-it** [comment]
See also https://github.com/arangodb/arangodb/issues/4358

**Comment by hkernbach** [comment]
Fixed. Removed those entries.
PRs: 
https://github.com/arangodb/arangodb/pull/4543
https://github.com/arangodb/arangodb/pull/4544
https://github.com/arangodb/arangodb/pull/4545
