### ISSUE TITLE
Incorrect index use resulting in very slow query

### ISSUE THREAD

**Issue by gurisko** [arangodb/arangodb#4526]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [x] 3.3
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [x] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [x] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
- [ ] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser: chrome     running on this OS: debian
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:
```
 FOR country IN countries
     FOR city IN cities
         FILTER country.code == city.country
         FILTER city.latitude > 30
         SORT country.name ASC
         LIMIT 10
         RETURN {city, country}
```
### Scenario 1
Indexes:
* countries
  - hash _code_
  - skiplist _name_
* cities
  - hash _country_

```
Execution plan:
 Id   NodeType                    Est.   Comment
  1   SingletonNode                  1   * ROOT
  2   EnumerateCollectionNode      245     - FOR country IN countries   /* full collection scan */
  8   CalculationNode              245       - LET #6 = country.`name`   /* attribute expression */   /* collections used: country : countries */
 13   IndexNode                 312865       - FOR city IN cities   /* hash index scan */
  6   CalculationNode           312865         - LET #4 = (city.`latitude` > 30)   /* simple expression */   /* collections used: city : cities */
  7   FilterNode                312865         - FILTER #4
  9   SortNode                  312865         - SORT #6 ASC
 10   LimitNode                     10         - LIMIT 0, 10
 11   CalculationNode               10         - LET #8 = { "city" : city, "country" : country }   /* simple expression */   /* collections used: city : cities, country : countries */
 12   ReturnNode                    10         - RETURN #8

Indexes used:
 By   Type   Collection   Unique   Sparse   Selectivity   Fields          Ranges
 13   hash   cities       false    false         0.08 %   [ `country` ]   (country.`code` == city.`country`)

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   move-calculations-up-2
  4   move-filters-up-2
  5   use-indexes
  6   remove-filter-covered-by-index
  7   remove-unnecessary-calculations-2
  8   move-calculations-down
```
**Query finishes in ~780ms**

### Scenario 2
Indexes:
* countries
  - hash _code_
  - skiplist _name_
* cities
  - hash _country_
  - **skiplist _latitude_**

```
Execution plan:
 Id   NodeType                      Est.   Comment
  1   SingletonNode                    1   * ROOT
  2   EnumerateCollectionNode        245     - FOR country IN countries   /* full collection scan */
  8   CalculationNode                245       - LET #6 = country.`name`   /* attribute expression */   /* collections used: country : countries */
 13   IndexNode                 38813880       - FOR city IN cities   /* skiplist index scan */
  4   CalculationNode           38813880         - LET #2 = (country.`code` == city.`country`)   /* simple expression */   /* collections used: country : countries, city : cities */
  5   FilterNode                38813880         - FILTER #2
  9   SortNode                  38813880         - SORT #6 ASC
 10   LimitNode                       10         - LIMIT 0, 10
 11   CalculationNode                 10         - LET #8 = { "city" : city, "country" : country }   /* simple expression */   /* collections used: city : cities, country : countries */
 12   ReturnNode                      10         - RETURN #8

Indexes used:
 By   Type       Collection   Unique   Sparse   Selectivity   Fields           Ranges
 13   skiplist   cities       false    false            n/a   [ `latitude` ]   (city.`latitude` > 30)

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   move-calculations-up-2
  4   move-filters-up-2
  5   use-indexes
  6   remove-filter-covered-by-index
  7   remove-unnecessary-calculations-2
  8   move-calculations-down
```
**Query needs more than 70s to finish!!!**

The issue can be reproduced using this dataset: countries, cities

**Comment by ObiWahn** [comment]
Hi,

Thank you for reporting this issue. We will have an internal discussion if this can be improved without sacrificing speed in other cases.

The geoindex is preferred because it "usually" yields better results (especially with "FILTER NEAR / WITHIN"). Please note that we only use estimates and that estimates are not exact. Therefor it is possible that the wrong index is selected. If you search near the polar caps the index will work much better. This shows that the effectivity of the index depends on query parameters and items stored in the collection that can not be inspected during plan generation. The optimizer can be improved endlessly, but it will never replace a clever database administrator that selects the corrected indexes.

**Comment by gurisko** [comment]
Hey @ObiWahn ,

Thank you for looking into this.

> The geoindex is preferred because it "usually" yields better results (especially with "FILTER NEAR / WITHIN"). Please note that we only use estimates and that estimates are not exact. Therefor it is possible that the wrong index is selected. If you search near the polar caps the index will work much better.

I agree it does make a lot of sense to use GeoIndex for this specific query given the nature of test data. However this is a reproduction of what happens with our production data where GeoIndex wouldn't make much sense.

 > The optimizer can be improved endlessly, but it will never replace a clever database administrator that selects the corrected indexes.

Maybe OT, but have you considered adding something like `USE INDEX ${type}.${field} [AND ${type}.${field}]` for `FILTER` so we can explicitly tell the optimizer to not bother?

**Comment by ObiWahn** [comment]
Yes one of our ideas was to create some think like that (`FOR i IN c FILTER USE @indexdescription`). We are aware that fixing the skiplist-index does not cut it. Especially when dealing with comparators that do not check for equality. Then we would need to inspect the collection what is not feasible. Especially if the value changes in a loop or when we deal with the cluster. We need to discuss this with more people.

**Comment by dothebart** [comment]
Hi, 
meanwhile we have the ability to give indices a name, and sugest their usage in the query options:
https://www.arangodb.com/arangodb-training-center/index-hints-named-indices/

please note Arangodb 3.7 is available for download now: 
https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/
