### ISSUE TITLE
ArangoDB Search Bug of Graph

### ISSUE THREAD

**Issue by CengSin** [arangodb/arangodb#4539]
When a document collection and another set of edges to create a map, if at this time delete a document in the document collection, without deleting the relations and documents associated with him at some time according to the map to query the document related All information will be given an error, (a cpp file line 103, sorry, I was forgetting the screenshot), only to find the relationship and delete it, this error will be resolved.

I use the cluster, the cluster has three nodes, the operating system is CentOS, start the engine is rocksdb, I usually java-driver, web interface, shell to operate the database, my server memory available for all 8G, a very large amount of data Less, only more than 3000.

**Comment by CengSin** [comment]
### /var/lib/otherjenkins/workspace/RELEASE__BuildPackages/arangod/RestHandler/RestCursorHandler.cpp:130).

### this file

**Comment by Simran-B** [comment]
Did a particular query cause this error? Can you share it?

Is your data 3000 documents, or MB / GB / ?

**Comment by CengSin** [comment]
I can not reproduce the bug, after I tried many times the same scene will not work, the data unit is MB
