### ISSUE TITLE
Query Web UI - Array parameters damaged on save / load.

### ISSUE THREAD

**Issue by davidmw** [arangodb/arangodb#4551]
ArangoDB 3.3.2  WebUI Queries feature.

When creating a query using an array parameter `FOR subject IN @subjectList` the value must be input on the right hand panel using an array format: `["one", "two", "three"]`

When the query is saved the parameter data is also saved (I do like this very much as it saves typing later). When the query is reloaded at a later time the array parameter data is represented as a simple list: `one,two,three` and the query will often run fine with this. But this parameter data is shown in red color and executing the query can result in: `Query: AQL: collection or array expected as operand to FOR loop; you specified type 'string' with content '"one,two,three"' (while optimizing ast)`

In 3.3.2 simply overtyping the parameter data with the original array will still fail. It is necessary to edit the @subjectList name, then repair the name. This action clears the parameter data and it will then accept and run correctly with an array.

So during storage of the query and reloading of it - there seems to be one or more data type conversions happening on the parameter data.

**Comment by hkernbach** [comment]
Thanks for note. This issue should already be resolved in ArangoDB v3.3.3. Could you please try it out? If you're still having issues, please feel free to respond here.

**Comment by davidmw** [comment]
If you are referring to #4223 / #4266 as the fix then please see my comments in #4223.  Parameter issue still existed when I tested v3.3.3 but I'm currently back on v3.3.2 due to the Swagger API problem.

**Comment by vinaypyati** [comment]
Hi @davidmw,

This issue exists with the version 3.3.2. But, it is already resolved in ArangoDB v3.3.3. Please test with 3.3.3. 

I confirm that #4223 remains still unresolved.

Thanks.

**Comment by hkernbach** [comment]
ArangoDB v.3.3.3 is out and fixed that issue.
