### ISSUE TITLE
Some typos could be fixed in Manual for 3.3.3

### ISSUE THREAD

**Issue by haqer1** [arangodb/arangodb#4553]
This	will	asked	for	a	root	password	and	sets	this	password.

It	suites	the	schema-less	model	more	natural	and	makes	the	query	language	very	powerful	while	remaining	easy	to	read	and
write.

These	for	shall	suffice	for	now.

To	simplify	live	of	the	devops

**Comment by vinaypyati** [comment]
Hi @haqer1,

Thank you for pointing out the typos in the documentation. 

If you would like to contribute and fix these typos, please fork [arangodb](https://github.com/arangodb/arangodb) and send a Pull Request. This requires signing a Non-Disclosure Agreement(NDA) with us. 

Here is the link to the [documentation](https://github.com/arangodb/arangodb/tree/9cd8c47eb78927c6640e65adc4b89427210bebc8/Documentation/Books) where these typos exist.

Thanks a lot!

**Comment by Simran-B** [comment]
The latter to seem to be corrected in a PR already. I included corrections for the other two in another PR.

Thanks again for spotting!

**Comment by sleto-it** [comment]
@Simran-B can this be closed now? 3.3.4 has been released. The doc changes should be online. Please let us know if we can close

Thanks,

**Comment by Simran-B** [comment]
@sleto-it Fixed in devel. Should it be backported to all version branches?

**Comment by sleto-it** [comment]
@Simran-B if you can fix that in 3.3 as well, please - then you can close this ticket

Many thanks,

**Comment by OmarAyo** [comment]
Hi @haqer1,

Thanks for opening this ticket

We have released 3.3.5, and it includes a fix for it
I am closing this ticket now. Please feel free to reopen if the problem persists
