### ISSUE TITLE
UNION_DISTINCT on Array of Docs sorts the keys

### ISSUE THREAD

**Issue by davidmw** [arangodb/arangodb#4556]
ArangoDB 3.3.2 AQL

I'm doing `APPLY("UNION_DISTINCT", subjectArray)` where subjectArray is an array of arrays of documents that look like:
```
{
id: doc._id,
type: "node",
t: xxxx,
d: KEEP(doc, "Type", "Job"),
c: xxxx,
fc: xxxx
}
```
After the UNION_DISTINCT the documents look like:
```
{
"c": xxxx,
"d": {
    "Job": 5,
    "Type": xxxx
},
"fc": xxxx,
"id": "9121.00",
"t": xxxx,
"type": "node"
}
```
I'm guessing this is an unavoidable side effect of UNION_DISTINCT but it is annoying. It also makes the new SORTED and SORTED_UNIQUE #4157 functions useless on the resulting array since the sort functions seem to depend on the key order for sorting and my sortable 'id' and 't' fields have been pushed to the bottom of the documents.

**Comment by jsteemann** [comment]
The `SORTED` and `SORTED_UNIQUE` AQL functions should sort the values inside an array. If the values are objects, the objects' keys and values will be taken into account for the comparisons, as described [here](https://docs.arangodb.com/3.3/AQL/Fundamentals/TypeValueOrder.html).

The sort order of attributes **inside** objects is not defined nor guaranteed nor guaranteed to stay identical in ArangoDB. For ArangoDB `{"a":1,"b":2}` is the same as `{"b":2,"a":1}`. This is also in line with the description of "object" from [json.org](http://json.org/):

> An object is an unordered set of name/value pairs. 

Keeping the original attribute insertion order for objects in ArangoDB would make things more expensive, and thus we have avoided it from the very beginning.

**Comment by davidmw** [comment]
Thanks @jsteemann
