### ISSUE TITLE
ERROR JavaScript exception in file '/usr/share/arangodb3/js/server/modules/@arangodb/arango-statement.js' at 81,16: ArangoError 30:

### ISSUE THREAD

**Issue by ralfr** [arangodb/arangodb#4560]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [x] 3.3
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [x] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [x] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

We are evaluating ArangoDB for commercial use. However, this issue has heavily reduced our level of confidence. Today, our ArangoDB crashed. When trying to restart, everything looks fine for a few minutes but then we run into the following error:

```2018-02-11T04:40:10Z [94071] INFO ArangoDB (version 3.3.3 [linux]) is ready for business. Have fun!
2018-02-11T04:43:13Z [84126] ERROR JavaScript exception in file '/usr/share/arangodb3/js/server/modules/@arangodb/arango-statement.js' at 81,16: ArangoError 30: shutdown in progress
2018-02-11T04:43:13Z [84126] ERROR !  var result = AQL_EXECUTE(this._query, this._bindVars, opts);
2018-02-11T04:43:13Z [84126] ERROR !               ^```

ArangoDB then shuts down.

**Comment by ralfr** [comment]
It gets even more weird:

```2018-02-11T05:29:44Z [65684] INFO ArangoDB (version 3.3.3 [linux]) is ready for business. Have fun!
2018-02-11T05:33:34Z [43838] WARNING {queries} slow query: 'FOR doc IN txCollection\n    COLLECT WITH COUNT INTO length\n    RETURN length', took: 1503.291323 s, loading took: 1503.288300 s
2018-02-11T05:33:41Z [43838] INFO ArangoDB has been shut down
2018-02-11T05:34:22Z [62865] WARNING caught exception while filling indexes: shutdown in progress
2018-02-11T05:34:25Z [62865] INFO ArangoDB has been shut down```

However, when showing the status via `systemctl status``` arango seems to still run.

**Comment by jsteemann** [comment]
I think all the "shutdown in progress" errors are (intentionally) thrown or logged when ArangoDB is actually shutting down. On shutdown, all currently running tasks (such as AQL queries, or in-memory index filling) will abort and may log errors.
It looks like the arangod service was stopped a few times, but from here I cannot tell why.
Can you provide the full log from the arangod server (should be in /var/log/arangod*/arangod.log) so we can check if there is anything obvious?
Additionally, when you say "Today, our ArangoDB crashed", do you happen to know if this was linked to any specific event or operation that was carried out, or if there is any information about the crash in the system logs (syslog etc.)? Is it possible that the OS (OOM killer) has killed ArangoDB? If so, there should be some information about this in the system logs.
Thanks!

**Comment by OmarAyo** [comment]
Hi @ralfr 

Can you please send us an update about this ticket 

Best

**Comment by maxkernbach** [comment]
Hi @ralfr,

i am closing this issue for now as we have not received any feedback for two months.
Please provide some additional information in order to investigate and feel free to reopen this issue.
