### ISSUE TITLE
Failure to set "All-in-one setup" Replication in 3.3.3 version

### ISSUE THREAD

**Issue by avive99** [arangodb/arangodb#4585]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [V ] 3.3
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [V ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [V ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [V ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click to ...
...

The following problem occurs: [Screenshot?] 
Instead I would be expecting: 

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

Greetings,

  After failing to build a stable SIngle-Host replication in 3.2 - i'm trying to build one in 3.3.3.
There are two single-hosts (Centos 7.3) with Arango 3.3.3 rpm installation.
First host acts as Master, and owns two DBs with collections/data (very small, just for a test).
Second host has only the "_system" db.

I\m trying to set a "All-in-one setup" Replication - as described in the manuals :
https://docs.arangodb.com/3.3/Manual/Administration/Replication/Asynchronous/ServerLevelSetup.html

However, after i run the setupReplicationGlobal (as described in the manuals) - following error massages appear:
127.0.0.1:8529@_system> db._databases()
[
  "_system"
]

127.0.0.1:8529@_system> db._useDatabase("_system");
true

127.0.0.1:8529@_system> require("@arangodb/replication").setupReplicationGlobal({
...>   endpoint: "tcp://vm-skarndbyp1:8529",
...>   username: "root",
...>   password: "mypass",
...>   autoStart: true
...> });
JavaScript exception in file '/usr/share/arangodb3/js/client/modules/@arangodb/replication.js' at 209,7: ArangoError 11: caught exception during slave creation: forbidden
!      throw err;
!      ^
stacktrace: ArangoError: caught exception during slave creation: forbidden
    at Object.exports.checkRequestResult (/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js:96:21)
    at waitForResult (/usr/share/arangodb3/js/client/modules/@arangodb/replication.js:207:16)
    at setup (/usr/share/arangodb3/js/client/modules/@arangodb/replication.js:310:10)
    at Object.setupReplicationGlobal (/usr/share/arangodb3/js/client/modules/@arangodb/replication.js:314:57)
    at <shell command>:1:34

Actually after that - the two DBs are created at the Slave, but they are empty: no collections and no data.
127.0.0.1:8529@_system> db._databases()
[
  "_system",
  "test_db1",
  "test_db2"
]

What am i doing wrong ?

best regards,
Avi Vainshtein

**Comment by graetzer** [comment]
We have fixed this internally, but it is not released yet
https://github.com/arangodb/arangodb/pull/4512
https://github.com/arangodb/arangodb/pull/4513

**Comment by avive99** [comment]
Hey, thanks for the update.
Will the solution be included into 3.3.4 ?
In other words, what is the forecast for the solution availability ?

**Comment by sleto-it** [comment]
Hi @avive99,

Yes. The fix has been merged already. It will be released with 3.3.4
We will inform you as soon as 3.3.4 is out

Thanks,

**Comment by OmarAyo** [comment]
Hi @avive99 ,

Thanks for reporting this bug

We have released 3.3.4, and it includes a fix for it
I am closing this ticket now. Please feel free to reopen if the problem persists
