### ISSUE TITLE
CHANGELOG vs Cookbook /_db/_system/_admin/aardvark/statistics/short

### ISSUE THREAD

**Issue by kwando** [arangodb/arangodb#4587]
Changelogs says endpoints are removed:

https://github.com/arangodb/arangodb/blob/f9d4598f521e79240974e120be01fd8726d3d6b9/CHANGELOG#L32

Guides / Cookbook / Documentation mentions that endpoint.
https://docs.arangodb.com/devel/Cookbook/Monitoring/Collectd.html

Just a heads up, I realize this is not released yet :)

**Comment by dothebart** [comment]
Will be fixed via https://github.com/arangodb/arangodb-docker/issues/34#issuecomment-385040889 - thanks for letting us know.
