### ISSUE TITLE
Technical Question: Scylladb and Seastar

### ISSUE THREAD

**Issue by p30arena** [arangodb/arangodb#4589]
Hi folks!
Have you heard about Scylladb ([not yet](https://www.scylladb.com/))?
It is using the [Seastar project](http://www.seastar-project.org/).

> Power your mission-critical applications with the best traits of Apache Cassandra at 10x the performance and low tail-latency at all times.

I want to hear from you Arangodb Folks, about the possibilities of utilizing this technology in Arangodb.

Thanks!

**Comment by dothebart** [comment]
Hi, 
we had a look at that a while back and after some discussions we decided that this is not a good architectural match within ArangoDB database core.

**Comment by dothebart** [comment]
Thanks again for your suggestion, 
closing this question now.
