### ISSUE TITLE
High number of Threads they wouldn't close

### ISSUE THREAD

**Issue by mok-liee** [arangodb/arangodb#4604]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.3.0

Mode:
- [x] Single-Server

Storage-Engine:
- [x] mmfiles

On this operating system:
- [x] Windows, version: 7 Pro x64

### this is an installation-related issue:

Hello ArandoDB Team,

i store every 100ms json data in a document over the HTTP API.

My First question is: is this possible over the HTTP API? Actually i have no Problems, but i want add some more clients they also write every 100ms data in the DB.

Or is it better to write a Message Buffer that caches 10-20 Elements and write them every 1-2 sec in the document?

### The Problem

After 18 Hours writing in ArangoDB, ArangoDB has ~1060 Threads. After i stopped the writing process, the Threads are not closing.

After 1 hour there are the same ~1060 Threads.

Is that normal? Which is the best technique to store so many data in a short time? It is a timestamp and some values.

Greetings mok

**Comment by dothebart** [comment]
Hi, 
sorry for the late reply. 
Can you share some more figures As I've demonstrated in these blog posts:
https://www.arangodb.com/2017/09/performance-analysis-pyarango-inspecting-transactions/
so we can have a look at whats bottlenecking in your installation?  Especially instrumenting the client calls with statsd probes should be interesting. 

Regarding the using of MMFiles for this, 
in general, when working with such a high throughput, you may want to consider tuning the compaction/aggregation; and eventually switch the collections you're writing to, so things like compaction and aggregation can happen without impacting the write performance of your system.  You may want to enable debug logging

do you use several connections?
Regarding the thread situation you have to know that just one thread at once can add documents to a collection. 
So spawning more threads in this situation could help the server survive a short burst, but if it can't clear that situation and come back to regular behaviour it won't survive your usage scenario. 

To maximize write throughput you should eventually try to write several documents at once using bulk mechanisms. Persistant connections are also something you should utilize. Eventually you could create a proxy that bundles several inserts to one such bulk insert.

In general you should detect your servers maximum throughput with a test where you ramp the load in 5 minutes steps as I have demonstrated in the performance blog posts. You should monitor the figures described in the blogposts in your favourite monitoring system to find out when the server maxes out. 
The number of open filedescriptors and running threads are clear indicators of the condition the system is in. 
Once these figures start growing, overunning it even more won't help in this situation.

Once you found a maximum that the server can stand for 20 minutes or more, you can try to find the limiting factors or bottlenecks. If its i.e. available RAM, Disk I/O etc.

**Comment by mok-liee** [comment]
Hi, thank you for reply.

as i have the problems i was on my overloaded dev-machine with the arangodb.
I switched the setup to a Server with 8 Cores & 8GB RAM. The incoming data from the IoT devices goes through a binary-parser (node.js). The Output of the parser is a JSON String that goes directly to the database over the HTTP API.

From now i dont have any problems. I think my dev-machine Hardware Setup was the bottleneck.

I switched to rocksdb engine. I hope i understand that right and its better for me. Actually i mine ~3 millions of documents per day with 4 devices.

Here (https://stackoverflow.com/questions/48867999/how-can-i-handle-a-lot-of-data-with-timestamp-in-arangodb) u can see how one JSON String is look like.

In my actually test scenario i have a collection with ~20 million documents. 
I have added a skiplist index over (timestamp, device).

I think i only want to get data between two timestamps from one device and my AQL is like this:

```
FOR d IN data
FILTER d.timestamp >= DATE_TIMESTAMP(DATE_SUBTRACT(DATE_ADD(DATE_NOW(), "PT1H"), 10, "minutes")) AND d.device== "5939568"
SORT d.timestamp
RETURN d

```

Explain Result is:

```
Execution plan:
 Id   NodeType              Est.   Comment
  1   SingletonNode            1   * ROOT
  8   IndexNode         10275546     - FOR d IN data   /* skiplist index scan */
  9   CalculationNode   10275546       - LET #1 = (d.`device` == "5939568")   /* simple expression */   /* collections used: d : data */
  4   FilterNode        10275546       - FILTER #1
  7   ReturnNode        10275546       - RETURN d

Indexes used:
 By   Type       Collection   Unique   Sparse   Selectivity   Fields                     Ranges
  8   skiplist   data         true     false       100.00 %   [ `timestamp`, `device` ]   (d.`timestamp` >= DATE_TIMESTAMP(DATE_SUBTRACT(DATE_ADD(DATE_NOW(), "PT1H"), 10, "minutes")))

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   use-indexes
  3   remove-filter-covered-by-index
  4   use-index-for-sort
  5   remove-unnecessary-calculations-2
```

If i want more data (increase the minutes in the query) the query time is slowing down. 
eg.
10 minutes takes 260.330 ms
1 hour takes

I am not sure if this is normal. Regarding the amount of data, should i keep the data in several collections?
If Yes, what is a good split count. After 10 millions documents or more?

Thanks for ur detailed reply!!!

I hope i can do your benchmarks in the next time. It is a little bit hard for me to understand everything.

Greetings mok

**Comment by dothebart** [comment]
Hi, 
as you can see in the explain only one of your conditions is covered by the index, so the second one is caried out for each document matching the first criteria. 
This is due to a limitation in utilizing skiplist indices, it can only work with equality matches on the first criteria, and range filters on the second. 
Thus you have to flip them in the creation of the index condition so it can utilize both of your filters.

Splitting to more collections will most probably only help if you use the mmfiles storage engine, since in the rocksdb storage engine everything lives in one big database.

You should have a look at the performance articles, they explain very well how to measure, which figures to watch, and the regular definitions of the KPIs.

**Comment by mok-liee** [comment]
Thank u very much for your help!
After flipping the attributes in the skiplist indicie i got ver fast the results. Wow.

Next i have to setup statsd & pyArango enviroment and understand that performance test.

Thank you very much!
