### ISSUE TITLE
Documentation link in /etc/arangodb3/arangod.conf does not link to detailed config documentation

### ISSUE THREAD

**Issue by fdsg-tk** [arangodb/arangodb#4632]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [X] 3.3
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [X] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [X] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

The following problem occurs: 
A comment in the server config file /etc/arangodb3/arangod.conf shows:
 https://docs.arangodb.com/Manual/Administration/Configuration/
...but this URL does only link to the Documentation introduction page.

Instead I would be expecting: 
You should fix the comment in the config file like this:
https://docs.arangodb.com/3.3/Manual/Administration/Configuration/
...or redirect the old link to the newest available version automatically.

Also, please think about introducing an overview of all available server parameters.
I know, that I am able to find all information on subpages of  https://docs.arangodb.com/3.3/Manual/Administration/Configuration/,  but a short list of all available parameters and where to find further information might be helpful.

Regards,
Tobias

**Comment by maxkernbach** [comment]
Thanks for reporting.

The config file is now pointing to the latest version as you suggested. We are trying to improve the clarity and usability of the documentation. The Table of Contents (toc) feature, which is already available in devel, should be helpful in that regard.
