### ISSUE TITLE
Application Security - Incomplete header: Content-Type

### ISSUE THREAD

**Issue by fdsg-tk** [arangodb/arangodb#4657]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [X] 3.3
- [ ] self-compiled devel branch

Mode:
- [X] Cluster
- [X] Single-Server

Storage-Engine:
- [X] mmfiles
- [X] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [X] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [X] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

These are the steps to reproduce:
Header information of
curl --dump - http://:8529/_db/_system/_admin/aardvark/index.html
shows, that header "Content-Type" header does not set characterset:
Content-Type: text/html

Instead I would be expecting:
e.g.:
"Content-Type: text/html; charset=utf-8"

You can find detailed information on possible attack scenarios here:
https://security.stackexchange.com/questions/122321/why-does-owasp-asvs-require-http-responses-to-have-a-content-header-specifying-a

**Comment by hkernbach** [comment]
Thanks. Will be fixed in 3.3.X and 3.4.X. PR available here: https://github.com/arangodb/arangodb/pull/4706/ & https://github.com/arangodb/arangodb/pull/4707

**Comment by OmarAyo** [comment]
Hi @fdsg-tk ,

Thanks for reporting this bug

We have released 3.3.4, and it includes a fix for it
I am closing this ticket now. Please feel free to reopen if the problem persists
