### ISSUE TITLE
AQL date_trunc

### ISSUE THREAD

**Issue by kwando** [arangodb/arangodb#4658]
DATE_TRUNC is a useful function when doing aggregations. It can be hacked around by using substring on a ISO8601-string, but a proper function would be awesome.

https://www.postgresql.org/docs/9.6/static/functions-datetime.html#FUNCTIONS-DATETIME-TRUNC

**Comment by dothebart** [comment]
This has been implemented via https://github.com/arangodb/arangodb/pull/5295#pullrequestreview-118378686 and will become part of ArangoDB 3.4. 

You can wait for the Milestone 1 to be released (in the next weeks), or try it out via one of the subsequent nightlies.

**Comment by vinaypyati** [comment]
Hi @kwando,

version 3.4.0-RC1 has been released, which contains this feature. Please check it out. 
I will be closing this issue for now. Please comment, if needed, and we will reopen it.

Thanks again for suggesting this feature.

Best,
