### ISSUE TITLE
AQL query time limit

### ISSUE THREAD

**Issue by feitianstyle** [arangodb/arangodb#4661]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [* ] 3.3
- [ ] self-compiled devel branch

Mode:
- [* ] Cluster
- [ ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [* ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [* ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [* ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

I am using AQL query,but sometimes the query time is too long.
This may cause the cluster http timeout or the cluster internal connection is interrupted.I want to know if arangodb has such a feature,Can I set a fuse mechanism?In other words, is it possible for me to set an AQL query time and return the result automatically when the query reaches the time limit, regardless of whether the task is fully completed,also stop the AQL query task.
Hope the great arangodb team can help me,thanks

**Comment by dothebart** [comment]
Hi, 
sorry for the late reply. 
Please have a look at [explain](https://docs.arangodb.com/3.3/AQL/ExecutionAndPerformance/Optimizer.html); In order to fix performance penalties you need to strive to reduce the amount of hops that are executed in the cluster, and reduce the number of documents that have to be sent from the DB-Servers to the coordinator by fixing filters & indices available.

**Comment by vinaypyati** [comment]
Hi @feitianstyle ,

Does the feedback from dothebart answer your question? Let us know if you have any further queries. 
Thanks. 

Best,

**Comment by OmarAyo** [comment]
HI @feitianstyle 

I am going ahead and close this ticket. 
Please note that tickets can be reopened at any time by adding a new comment 

Best,

**Comment by Puneeth-Kadamba** [comment]
Any update on providing the query timeout feature.

**Comment by dothebart** [comment]
Why are you posting to a completely unrelated issue? 
Please note that we don't warrant any reaction times for community issues.
