### ISSUE TITLE
Unified access to the cluster's IP address.

### ISSUE THREAD

**Issue by zp15733175532** [arangodb/arangodb#4663]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 3.3
Mode:
- [ ] Cluster

Storage-Engine:
- [ ] rocksdb

On this operating system:

- [ ] Linux 

### this is an AQL-related issue:
[ ] I'm using graph features
I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
I want to use an IP address to access the cluster.Even if a node has a problem, it will not interrupt the program because it cannot access it.What should I do? Please help me

**Comment by dsonet** [comment]
I use a nginx server in front of ArangoDB.

**Comment by maxkernbach** [comment]
Closing - Cluster advertised endpoints are implemented in 3.4. The new feature is documented at  [What's new in 3.4](https://docs.arangodb.com/devel/Manual/ReleaseNotes/NewFeatures34.html#advertised-endpoints) and [Cluster - My advertised endpoint](https://docs.arangodb.com/3.4/Manual/Programs/Arangod/Cluster.html#my-advertised-endpoint).
