### ISSUE TITLE
One node of cluster crashed

### ISSUE THREAD

**Issue by wanghaiwin** [arangodb/arangodb#4681]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2

Mode:
- [x] Cluster

On this operating system:
- [ ] Linux 
  - [x] RedHat .rpm

Dear friend，

I faced the node of arango cluster crashed sometimes，and checked the log. I can not find any info， how to  resolve it？

Appreciate your feedback.

**Comment by OmarAyo** [comment]
Hi @wanghaiwin

Thank you for opening this ticket and trying ArangoDB

For a proper analysis of your issue please could you attach the following: 
- Log files from all the nodes (Coordinators, Agents and DBServers)

Also, please, could you answer the following questions:
- what is your current version of ArangoDB? (3.2 is not enough, we need to know the exact hotfix you are on) 
- which storage-engine are you using? (MMFiles or RocksDB)

Thanks

**Comment by wanghaiwin** [comment]
Hi, @OmarAyo 

Thanks for your feedback.

The current version of ArangoDB is 3.2.0，and the  storage-engine is MMFiles.

May i have your e-mail? I can sent the log files to you if you have time to analyze.

Thank you very much.

**Comment by OmarAyo** [comment]
Hi @wanghaiwin

We suggest you to upgrade your current version to 3.2.12 and see if the error persist, as many bugs have been fixed since 3.2.0.

Please let me know if this works.

**Comment by wanghaiwin** [comment]
Hi, @OmarAyo 
Could you give some suggestion or  guide to upgrade the arangodb and keep the data safe?
The system have been in business environment.
Thank you.

**Comment by OmarAyo** [comment]
Hi @wanghaiwin 

Just to keep you update - we are improving our documentation about upgrade procedure.
Once it is ready, I will share it with you.

Meanwhile are there any updates from your side?

Best.

**Comment by OmarAyo** [comment]
Hi @wanghaiwin 

We just released a guide about _ArangoDB Cluster Administration_ where you can find the correct procedure to _ArangoDB Cluster Upgrade_

Please find the link below:
https://www.arangodb.com/2018/03/arangodb-cluster-administration-course/

Please give us your feedback.

Many Thanks

**Comment by OmarAyo** [comment]
Hi @wanghaiwin 

Did you find the guide useful ? 
Did you manage to upgrade your Cluster ?

Best,

**Comment by maxkernbach** [comment]
Hi @wanghaiwin,

i am closing this issue for now as we have not received any feedback for a few weeks.
Please feel free to reopen and comment in case you had any problems to upgrade your cluster with the procedure that is described in the listed guide.
