### ISSUE TITLE
ER: AQL functions: REPLACE and/or REPLACE_NTH

### ISSUE THREAD

**Issue by pkoppstein** [arangodb/arangodb#4695]
Suppose we have:

    LET x={a:1, b:[0,1,2]}

and we want to change x.b[0] to 10, without knowing the value of x.b

Currently, this requires quite a bit of effort because of various limitations of AQL.  One would really like to be able to write something like:

    x.b[0] = 10

but that might be too big a leap for AQL. However, AQL does have REMOVE_NTH so it should be easy to add RELACE_NTH, so we could at least write:
```
LET x={a:1, b:[0,1,2]}
LET b = x.b
RETURN MERGE(x, {REPLACE_NTH(b, 0, 10)})
``

However, since JSON objects and JSON arrays can both be
viewed as indexed entities, it would be really
nice (and maybe more efficient) to be able to write simply:

    RETURN REPLACE(x, "b", REPLACE(x.b, 0, 10))

**Comment by Simran-B** [comment]
`x.b[0] = 10` mutates the variable, i.e. it is not side-effect free. REPLACE functions would be possible however. Also see my ticket: #3468

**Comment by pkoppstein** [comment]
@Simran-B - That`x.b[0] = 10 mutates the variable` is true in Javascript, but AQL would be free to define its own semantics.  In [jq](https://stedolan.github.io/jq/), for example, it is side-effect free (jq is a functional programming language).  

But as I said, adopting side-effect free semantics for `=` "might be too big a leap for AQL".

**Comment by dothebart** [comment]
With [arangodb 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) [REPLACE_NTH](https://www.arangodb.com/docs/stable/aql/functions-array.html#replace_nth) is available.
