### ISSUE TITLE
Arangodb can't stop create new log files in journals, exceed the disk space

### ISSUE THREAD

**Issue by dsonet** [arangodb/arangodb#4697]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.3.4

Mode:
- [x] Single-Server

Storage-Engine:
- [x] mmfiles

On this operating system:
- [x] Windows, version: 10

<del>It's happened one time before, after I restarted my PC, it works again, but it happened again this time, whatever I do, it's just keep create new files until exceed my disk space.(eat about 50G free space, I checked the data files, only 4G)</del>

I just found out it's actually eat all disk first when it started, after the disk is full, then it's start to release[but not always, sometimes it's just stuck there] the space, until to normal. It's a very crazy cycle.

I also tried arangod.exe --database.auto-upgrade, it would clean all the extra log files, and shows no error. but after restart arangod, it's start create the logs forever.

from the web admin /logs:
 unable to create new WAL reserve logfile: filesystem full
unable to create logfile: filesystem full

**Comment by dsonet** [comment]
It still happens after I upgraded to the 3.3.4.

**Comment by dsonet** [comment]
Here is the screenshot from logs:
![1](https://user-images.githubusercontent.com/457552/37635908-77d4100e-2c39-11e8-9091-90532c72b86e.png)

**Comment by OmarAyo** [comment]
Hi @dsonet 

Note that we released version 3.3.5, please let us know if this helps.

Many thanks

**Comment by OmarAyo** [comment]
Hi @dsonet 

Did you have the chance to upgrade and see if the issue persist ?

**Comment by dsonet** [comment]
@OmarAyo Hi, I upgraded to 3.3.7 already, but too bad this bug doesn't gone.

**Comment by dothebart** [comment]
@dsonet sorry for comming back on this so late. Does this still occur for you?
can you try to configure trace logging, and send us the resulting logfile for further analysis? 

please set in `etc/arangod.conf`: 
```
[log]
level = trace
file = c:/somewhere.log
```

**Comment by dsonet** [comment]
@dothebart OK, I'll try what you told me to do.

**Comment by OmarAyo** [comment]
Hi @dsonet 

How are things going ? Could you please send us a feedback ? 

Best

**Comment by dsonet** [comment]
I'm sorry I'll cleanup my environment, since it's only left less than 200MB with my disk, because somehow pagefile.sys was became very large. I'll pick a time to restart the system then send you the log to analyze.

**Comment by dsonet** [comment]
[arangodb3-trace-3.3.9.log](https://github.com/arangodb/arangodb/files/2042253/arangodb3-trace-3.3.9.log)
@OmarAyo Here is the log, thanks.

**Comment by OmarAyo** [comment]
Hi @dsonet 

Thank you for the log, we will get back to you 

Best,

**Comment by dothebart** [comment]
Ok, we can see that you're running foxx queues with a job named 'trucatejobs' ?
```
2018-05-27T03:44:54Z [4052] ERROR ArangoError: unknown script
2018-05-27T03:44:54Z [4052] ERROR Name: truncatejobs
2018-05-27T03:44:54Z [4052] ERROR     at FoxxService.executeScript (c:\Program Files\ArangoDB3e 3.3.9\usr\share\arangodb3\js\server\modules\@arangodb\foxx\service.js:547:15)
2018-05-27T03:44:54Z [4052] ERROR     at Object.runScript (c:\Program Files\ArangoDB3e 3.3.9\usr\share\arangodb3\js\server\modules\@arangodb\foxx\manager.js:944:26)
2018-05-27T03:44:54Z [4052] ERROR     at Object.exports.work (c:\Program Files\ArangoDB3e 3.3.9\usr\share\arangodb3\js\server\modules\@arangodb\foxx\queues\worker.js:126:17)
2018-05-27T03:44:54Z [4052] ERROR     at eval (eval at <anonymous> (unknown source), <anonymous>:8:59)
2018-05-27T03:44:54Z [4052] ERROR     at eval (eval at <anonymous> (unknown source), <anonymous>:11:17)
2018-05-27T03:44:54Z [4052] ERROR     at eval (eval at <anonymous> (unknown source), <anonymous>:11:29)
```

After that arangodb starts to create new logfiles.  Can you please state whether you have any arangodb configuration parameters for foxx aside of the defaults?

We see that the files fill (allmost) instantly. If (as the name sugests) you run a truncate operation on a huge collection, this will result in it delete markers being written in subsequent wal-files. 
The compaction would then later on match the documents with their respective delete markers, and write new logs not containing neither. 
We also see the claim that there is a constant write lock on `_jobs` stopping the collection from happenning. 

It may not be a good idea to have foxx-queue jobs with such huge operations; running an AQL-delete with limt and a filter on i.e. a timestamp in the documents may be the more clever idea.

**Comment by maxkernbach** [comment]
Hi @dsonet,

could you please share some details about your configuration parameters for foxx and the job 'truncatejobs' itself?

**Comment by OmarAyo** [comment]
Hi @dsonet 

We haven't heard from you recently, I am going ahead and close this ticket. 

Feel free to reopen this ticket at any time by adding a new comment.


Best,

**Comment by qingtimehr** [comment]
we also find the bug on 3.3.8

**Comment by qingtimehr** [comment]
create about 2 or 3 log files per second, each 32MB.

It's a bad news for us. And the disk full.

even we stop the arangodb service,it still create.

**Comment by sachindu** [comment]
version 3.3.19 still having this issue.. creating big files in Program Data ..

Is there any workaround to remove this please

**Comment by dothebart** [comment]
@sachindu which storage engine are you using? The default configuration puts the database files into `Program Data` - if its not what you want, you should configure it differently. 
You can choose it on installation by ticking the checkbox not to choose default locations, or later on by editing in your installation path the `etc/arangod/arangod.conf` and change the location, move the directory there, restart.

**Comment by maxkernbach** [comment]
Hi @sachindu,

has the latest message been helpful to you?
Please let us know your feedback.

**Comment by maxkernbach** [comment]
@sachindu Since we have not received any feedback, I am closing this issue for now.
Please feel free to comment and we will reopen this issue.

**Comment by sachindu** [comment]
i am sorry guys.. yes issue has been resolved , now using rocksdb...
