### ISSUE TITLE
The databases lists are not sorted alphabetically

### ISSUE THREAD

**Issue by samirski** [arangodb/arangodb#4698]
Frankly speaking I'm surprised that the databases list on the account permission page and on the switch database dialog are not sorted alphabetically. In case there are only a couple of them this probably not an issue, but as soon as the list gets longer, finding the right database takes time. Not a functional issue, but still an annoying one.

## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [x ] 3.3
- [ ] self-compiled devel branch

Mode:
- [x ] Cluster
- [ ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [ x] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ x] own infrastructure
- [ x] Linux 
  - [ ] Debian .deb
  - [x ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

**Comment by hkernbach** [comment]
Thanks for the report. Will be fixed in the upcoming released. 
Pull requests available here: https://github.com/arangodb/arangodb/pull/4700 & https://github.com/arangodb/arangodb/pull/4701

**Comment by OmarAyo** [comment]
Hi @samirski ,

Thanks for reporting this bug

We have released 3.3.4, and it includes a fix for it
I am closing this ticket now. Please feel free to reopen if the problem persists
