### ISSUE TITLE
arangoexport failed with "out of memory (while executing)"

### ISSUE THREAD

**Issue by avive99** [arangodb/arangodb#4702]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [ V] 3.3
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [V ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [V ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [V ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click to ...
...

The following problem occurs: [Screenshot?] 
Instead I would be expecting: 

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

Trying to export a collection with more than 280M documents. That collection seems to be stored at 49GB of disk storage.

Arangoexport failed immediately with following output :

arangoexport --output-directory "/tmp/avi/dump/bezeqcloudcollectordb" --server.database bezeqcloudcollectordb --collection files  --overwrite true
Please specify a password:
Connected to ArangoDB 'http+tcp://127.0.0.1:8529', version 3.3.3, database: 'bezeqcloudcollectordb', username: 'root'
# Exporting collection 'files'...
{"code":500,"error":true,"errorMessage":"out of memory (while executing) (exception location: /var/lib/otherjenkins/workspace/RELEASE__BuildPackages/arangod/RestHandler/RestCursorHandler.cpp:134)","errorNum":3}
2018-02-28T10:10:32Z [17807] ERROR {startup} startup aborted: caught exception during start of feature 'Export': got invalid response from server: HTTP 500: Internal Server Error (exception location: /var/lib/otherjenkins/workspace/RELEASE__BuildPackages/arangosh/Export/ExportFeature.cpp:577). Please report this error to arangodb.com. shutting down
2018-02-28T10:10:32Z [17807] ERROR {startup} arangoexport terminated because of an unhandled exception: startup aborted: caught exception during start of feature 'Export': got invalid response from server: HTTP 500: Internal Server Error (exception location: /var/lib/otherjenkins/workspace/RELEASE__BuildPackages/arangosh/Export/ExportFeature.cpp:577). Please report this error to arangodb.com (exception location: /var/lib/otherjenkins/workspace/RELEASE__BuildPackages/lib/ApplicationFeatures/ApplicationServer.cpp:638). Please report this error to arangodb.com

Are there any collection size limitations in ArangoDB, which could impact arangoexport ?

Please also take a look at my another open issue 4654 (for arangodump failures for the same collection).

**Comment by dothebart** [comment]
Hi, 
ArangoExport does a query on the server that has to build up the results in RAM. 
Thus you either have to adjust the AQL you're making it generate, or rather use arangodump for exporting whole collections. So, when arangodump fails (we will see that in your other issue) arangoexport isn't a better choice - unless you make it work in several chunks by apply ing indexeable `FILTER` statements with range requests (use the Query editors `EXPLAIN` key in advance to check)

**Comment by avive99** [comment]
Hey @dothebart,

Many thanks for the reply.
So, arangoexport has always to put the data into RAM, and only then to extract it outside ?
Even if the engine is RocksDB ?

If that's correct - then it seems that arangoexport is possible only of size_of_collection<size_of_RAM, right ? (i mean arangoexport of the whole collection, without cutting it to chunks)

**Comment by dothebart** [comment]
Yes, correct. ArangoExports capabilities are aligned to the available RAM of your system - since its running an AQL in the background. 
Its primary intend was to export certain subsets of collections.

**Comment by maxkernbach** [comment]
Hey @avive99,

does this answer your question, can we close this issue? We are obviously keeping your original arangodump issue #4654 open and will inform you once version 3.3.4 is released.
