### ISSUE TITLE
The "waitForSync" definition is specified twice in "Durability" section.

### ISSUE THREAD

**Issue by ryanhaney** [arangodb/arangodb#4716]
https://docs.arangodb.com/3.3/Manual/Administration/Durability.html

waitForSync is mentioned twice.

![image](https://user-images.githubusercontent.com/1445619/36820525-0fcba580-1ca3-11e8-96b8-5d48cb4d700b.png)

**Comment by ryanhaney** [comment]
Sorry for the title changes. There are multiple duplicates in that doc.

**Comment by dothebart** [comment]
Its supposed to be several bullet point lists - however somehow the markdown is mixing it together to one list. Will have a look at whats going on here.
