### ISSUE TITLE
Content-Length' bigger than max packet size (183843176 > 134217728)

### ISSUE THREAD

**Issue by ShahanaBubly** [arangodb/arangodb#4746]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 3.3

Mode:
- [ ] Single-Server

Storage-Engine:
- [- ] mmfiles
- [ ] rocksdb

On this operating system:

- [ -] Windows, version: windows 10, Corei3 2.95GHz, RAM: 4GB, 

I'm issuing AQL via:
- [- ] web interface with this browser:  Google chrome    running on this OS:
- [- ] arangosh

I've run `db._createStatement({ query: "FOR L IN ZKWtestdata RETURN L", count: true }).execute().count() ` 
The AQL query in question is: Find whole collection. Which i have import JSON file(count is 196,342, size: 33.05 GB). 

The following problem occurs: 
![arangoquery3](https://user-images.githubusercontent.com/14944188/36905406-97a5df16-1e33-11e8-905e-fa5761d06c02.JPG)

If I run in web interface its query for long time finally goes down.

**Comment by graetzer** [comment]
You seem to have pretty big documents, try specifying the parameter `batchSize: 100` to reduce the number of documents returned in one go.
The default is 1000

**Comment by OmarAyo** [comment]
hi @ShahanaBubly 

Can you give us a feedback about your situation, did you specify the parameter that _graetzer_ suggested you?

Best.

**Comment by OmarAyo** [comment]
Hi @ShahanaBubly,

I am going to close this ticket, feel free to reopen it at any time if needed.

Many Thanks,
