### ISSUE TITLE
ArangoDB issue with server cores

### ISSUE THREAD

**Issue by eafiontzi** [arangodb/arangodb#4761]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ x ] 3.1.27
- [ ] 3.2
- [ ] 3.3
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [ x ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [ x ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ x ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ x ] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ x ] this Driver: arangodb-php

Hi all,
We are experiencing a kind of weird problem. Our application runs on a cuad-core server for arangodb and sometimes is really slow (we have a pageTree graph with about 4.000 edges). We tried updating to octa-core in the virtual server, but it resulted to even slower and sometimes crashing the application. Does anyone have any idea regarding that? Are there any parameters in the configuration file that need changing when adding cores? I attach two images from my server htop before and after the change in cores.
Thank you all in advance
![4cores](https://user-images.githubusercontent.com/14819444/37028190-42543ccc-213c-11e8-93d6-0c2f67690918.png)
![8cores](https://user-images.githubusercontent.com/14819444/37028206-4c02cc2a-213c-11e8-807f-50a5b405ee6a.png)

**Comment by jsteemann** [comment]
The above info indicates you are running 3.1.27 with the RocksDB engine, which is unlikely (RocksDB engine was introduced with version 3.2.0 first).
So I am assuming you are on 3.1.27 with the MMFiles engine (the only available storage engine there).
Is there any chance you can upgrade to a more recent version, e.g. 3.2.12 or 3.3.3?

**Comment by eafiontzi** [comment]
Thank you again, the way I figured out that we use the RocksDB engine is that the LOCK file was created in the path /var/lib/arangodb3/rocksdb (sorry, I have started working with arangodb about 2 months ago). If the problem persists I will try the upgrade part, but the thing is that there are about 200 hotel sites on the DB and I am worried if something goes wrong on the upgrade, but if you think that is the only solution, we will try it.

**Comment by jsteemann** [comment]
Ah got it. I think 3.1 fires up a RocksDB instance at startup, but it is only used for a particular type of index ("persistent"). But the storage engine is MMFiles there. Since 3.2 the storage engine is switchable, and there are currently two engines available: MMFiles (the ever existing one) and RocksDB.
Regarding workload: what actually is going on on the server? Is it CPU-bound or I/O bound, or are there any other indications of high load or activity, slow queries etc.?

**Comment by eafiontzi** [comment]
Regarding workload I am not really sure about the bound of the server, but if I had to guess I would say I/O bound. It is a web application that is based only on PHP and yii2 framework. Slow queries do exist and we are in the process of trying to fix them, but they are quite complicated and also include aql functions. However, the queries are always the same but when the system is changed from 4 to 8 cores the performance is deteriorated dramatically. Below you can see the configuration file for arangoDB

```
# ArangoDB configuration file
#
# Documentation:
# https://docs.arangodb.com/Manual/Administration/Configuration/
#

[database]
directory = /var/lib/arangodb3

maximal-journal-size = 33554432
###maximal-journal-size =   8388608

[http]
keep-alive-timeout=60

[server]
# Specify the endpoint for HTTP requests by clients.
#  tcp://ipv4-address:port
#  tcp://[ipv6-address]:port
#  ssl://ipv4-address:port
#  ssl://[ipv6-address]:port
#  unix:///path/to/socket
#
# Examples:
#   endpoint = tcp://0.0.0.0:8529
#   endpoint = tcp://127.0.0.1:8529
#   endpoint = tcp://localhost:8529
#   endpoint = tcp://myserver.arangodb.com:8529
#   endpoint = tcp://[::]:8529
#   endpoint = tcp://[fe80::21a:5df1:aede:98cf]:8529
#
endpoint = tcp://0.0.0.0:8529

# resuse a port on restart or wait until it is freed by the operating system
# reuse-address = false

authentication = true

# number of server threads. use 0 to make arangod determine the
# number of threads automatically, based on available CPUs
threads = 0

# gather server statistics
###statistics = true
statistics = false

# the user and group are normally set in the start script
# uid = arangodb
# gid = arangodb

uid = arangodb


[scheduler]
# number of threads used for I/O, use 0 to make arangod determine
# the number of threads automatically
# threads = 0

[javascript]
startup-directory = usr/share/arangodb3/js
app-path = /var/lib/arangodb3-apps
# app-path = @HOMEDRIVE@/@HOMEPATH@/arangodb3/apps

# number of V8 contexts available for JavaScript execution. use 0 to
# make arangod determine the number of contexts automatically.
# v8-contexts = 0

[foxx]
# enable Foxx queues in the server
# queues = true

# interval (seconds) to use for polling jobs in Foxx queues
# queues-poll-interval = 1

[log]
###level = info
level = error
file = /var/log/arangodb3/arangod.log

[wal]
logfile-size = 8388608
allow-oversize-entries = true
reserve-logfiles = 10
sync-interval=10000
```

**Comment by georgekaf** [comment]
@eafiontzi 
How many databases have been on the server now ?

**Comment by jsteemann** [comment]
@georgekaf : that's indeed a good question... 
@eafiontzi : can you let us know if the dataset fits into the server's available RAM (how big is the dataset on disk, how big is the server's physical RAM)? Can you also let us know what the main workload is (mainly reads/writes, complex queries/transactions vs. single document operations)? Without further information it is kind of hard to say what is going on. Thanks!

**Comment by eafiontzi** [comment]
Thank you for your interest, the are about 110 databases on the server, the RAM is 8GB. Regarding the  workload besides arangodb we also have mysql and redis on the specific virtual machine. However the main workload as far as I can see from the processes is arango. There we mostly (about 80% of the time) we have complex queries and read/ writes in the database. For example, I paste below some of the slowest queries (some take up to 50sec, but that depents on the server workload. Most slow queries though have to do with the pageTree graph which consists of about 4000 edges.
```

LET params = { data: { pagePreview: @previewMode, pageStatus: @pageStatus, inSiteMap: @inSiteMap, rootPageId: @rootPageId, rootPageType: @rootPageType, returnRoot: @returnRoot, inSiteMapMismatch: @inSiteMapMismatch, statusMismatch: @statusMismatch, activeLanguageMismatch: @activeLanguageMismatch } } FOR v, e, p IN @minDepth..@maxDepth INBOUND @id pageTree LET filtered = CALL("cms3::getPageParentFilter", v, p, params) FILTER filtered == null LET d = CALL("cms3::getPageParentVisitor",v, e, p, params) RETURN d


LET params = { data: { pagePreview: @previewMode, langCode: @langCode, fallbackLangCode: @fallbackLangCode, searchLocalized: @searchLocalized, pageStatus: @pageStatus, inSiteMap: @inSiteMap, activeLanguageMismatch: @activeLanguageMismatch, pageAttrFilters: @pageAttrFilters, pageAttrSort: @pageAttrSort, pageFieldFilters: @pageFieldFilters, pageFieldSort: @pageFieldSort } }FOR v, dOr, p IN @minDepth..@maxDepth OUTBOUND @id pageTree LET d = CALL("cms3::getPageChildrenVisitor", v, dOr, p, params)FILTER d != null && (d.pageStd_typeKey==@filter0 ) SORT d.pageStd_depth ASC, d.pageStd_vOrder ASC LIMIT 0, 20 RETURN d
```
Any thoughts?

**Comment by baslr** [comment]
@eafiontzi can you execute `vm_stat 1` as root and leet it run for a while and paste the output here?

**Comment by eafiontzi** [comment]
Sorry for not replying earlier, I finally added two indexes in two collections and the workload was reduced significantly. It still does not explain why the 8 core system was causing more bottlenecks but seems to be stable for now. 
Can I ask something about skiplist indexes here or should I close that issue and open a new one with different title?

**Comment by OmarAyo** [comment]
Hi @eafiontzi 

I am going to close this issue since you said that is stable now.
Regarding skiplist indexes, you can open another issue.

Best
