### ISSUE TITLE
Updating _to and _from for an edge

### ISSUE THREAD

**Issue by F21** [arangodb/arangodb#477]
There currently seems to be no way to update the `_to` and `_from` properties of an edge. If we send it in `_to` and `_from`, it seems to be ignore. It would be nice if there exists some way where we can update those properties, rather than relying on the client to:
```
Keep the current id of the edge.
Delete the edge.
Then recreate the edge with the specified id.
```

**Comment by sinfex** [comment]
Any update on this? It's been 3 years and redirecting an edge without having to replace it entirely feels like a pretty significant graph capability.

**Comment by dothebart** [comment]
Not quiet yet. 3.0 is going to have the ability to do this. We're currently working heads down on the 3.0 Release, and hope to present news about this in Q2. So, stay tuned!

**Comment by dothebart** [comment]
ArangoDB 3.0 RC2 is available for download now: https://www.arangodb.com/download-preview/

So I'm closing this.
