### ISSUE TITLE
Type Error while using COLLECT result in SUBQUERY

### ISSUE THREAD

**Issue by TFlinguland** [arangodb/arangodb#4790]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [x ] 3.3
- [ ] self-compiled devel branch

The following problem occurs: [Screenshot?] 
------------------------------

The Variable `groupCategory[*].v._id` comes out of a COLLECT statement and works perfectly in the RESULT.

The following SUB works also perfectly
 ```
LET sub = ( 
        FOR mitarb IN 1..1 ANY @start `edge_assign`  
        RETURN mitarb.V 
        )
```

Unfortunately, once I want to use the COLLECT variable in the sub, it does not work anymore. 
```
 LET sub = ( 
        FOR mitarb IN 1..1 ANY groupCategory[*].v._id `edge_assign`  
        RETURN mitarb.V 
        ) 
```
This one above gives an error: `'Invalid input for traversal: Only id strings or objects with _id are allowed'`

So, what I tried was to convert the `groupCategory[*].v._id`  into an object, but it did not work. Also converting it to string did not work. I have run the `IS_OBJECT()` function over it (the result was: false), so what is wrong?

Is that an arangoDB issue or is it just me applying it wrongly?
Thanks in advance!!
Tobias

**Comment by jsteemann** [comment]
The parser grammar for traversal query allows an aribtrary expression for the start vertex, so your query that uses `groupCategory[*].v_id` will parse fine.
However, it will not return, because `groupCategory[*].v_id` will produce an array of values (strings, probably), and a traversal expects the start vertex to be specified as either a single `_id` string or an object containing an `_id` attribute, from which it will automatically extract the start vertex id.

Therefore, when given an array of strings as its start vertex, it will always correctly complain with `Invalid input for traversal: Only id strings or objects with _id are allowed`.

In order to use all ids from that array as a start vertex for (separate) traversals, you can do
```
 LET sub = ( 
        FOR id IN groupCategory[*].v_id 
          FOR mitarb IN 1..1 ANY id edge_assign
          RETURN mitarb.V
 )
```
        )

**Comment by TFlinguland** [comment]
Thanks a lot!! It works (after correcting a mini-mistake in the script, the point in v._id
```
 LET sub = ( 
  FOR id IN groupCategory[*].v._id 
    FOR mitarb IN 1..1 ANY id edge_assign
      RETURN mitarb.V
    )
```
Especially new for me (what I really enjoyed to learn) was the double-FOR-structure. Good to know.
The result now comes like:

```
  {
    "category": "country_office",
    "ergebnis": [
      "Office USA",
      "Office Canada",
      "Office Canada"
    ],
    "sub": [
      "Maria",
      "Jon",
      "Simon"
    ]
  },
```
Already great... so I modified it to:

```
 LET sub = ( 
  FOR id IN groupCategory[*].v._id 
    LET test1 = groupCategory[id].id.v_id 
        FOR mitarb IN 1..1 ANY id edge_assign
        LET vid = groupCategory[mitarb].id.v.vid
            RETURN [test1, mitarb.V, vid]
    )
```
Intention was to use the counter of the FOR statement (like `id`) to access the respective array number from groupCategory[]. Unfortunately with [id] the result is NULL, with [*] the result is the entire array, if I put a contant number (like [0]) it shows only the first value.

So question 1:    How can I use the counter from the FOR statement?

Question 2 I have spend hours on, many of them, is the question, how to SUB-COLLECT something. 
The result I's like to get is something like:

```
  {
    "category": "country_office",
    "Office USA": { 
                     "Maria"
                          },
    "Office Canada": { 
                     "Jon",
                     "Simon"
                          }
 }
```
I am sure the solution for this problem would be a great contribution for the https://docs.arangodb.com/3.3/AQL/ Script, too, as examples like this help all of us to learn a better use of AQL.

Thanks a lot already in advance,
Tobias

**Comment by jsteemann** [comment]
For the two latest questions, please provide some example data for the source collection(s) and the desired result format. Otherwise it is a bit hard to come up with a solution if the source data structure is unknown. Thanks!

**Comment by TFlinguland** [comment]
Hi there, thanks a lot: A different answer in my second issue has helped me a lot. The simple answer about how to structure objects and arrays was:

This might work:
`RETURN p.vertices[* RETURN [CURRENT.title, CURRENT.var2, CURRENT._id]]`

Like this I got a little deeper into how to structure the RETURN statement. Answer is posted here, so it might help others, too. Thanks to all!
