### ISSUE TITLE
Azure VM transparent_hugepage settings and Jemalloc

### ISSUE THREAD

**Issue by kt215** [arangodb/arangodb#4792]
I'm using the latest ArangoDB of the respective release series:
- [x] 3.3

Mode:
- [x] Single-Server

Storage-Engine:
- [x] rocksdb

On this operating system:
- [x] Linux 
  - [x] Ubuntu .deb

I'm using Ubuntu 16.04 on an Azure VM.

The default content of `/sys/kernel/mm/transparent_hugepage` is

```
khugepaged/
defrag
enabled
hpage_pmd_size
shmem_enabled
use_zero_page
```
[This page](https://docs.arangodb.com/3.3/Manual/Administration/Configuration/OperatingSystem.html) describes which relevant settings are recommended, and I have applied them all.

However, after reboot, ArangoDB takes up more and more memory, even while the application is relatively idle.

The documentation does not mention `hpage_pmd_size` and `shmem_enabled`. Do these entries affect ArangoDB's `Jemalloc` performance?

**Comment by dothebart** [comment]
If you want to reduce resource limits, you need to turn of certain things as explained under https://www.arangodb.com/2016/03/put-arangodb-spartan-mode/. 
Else these permanently running jobs will fill the caches of an elseways idle arangodb instance.

**Comment by vinaypyati** [comment]
Hi @kt215,

Did you have a chance to go through the [page](https://www.arangodb.com/2016/03/put-arangodb-spartan-mode/) suggested by dothebart? Do you have any further queries?
Thanks!

Best,

**Comment by kt215** [comment]
No further questions. The page was very helpful, Thanks.
