### ISSUE TITLE
Increasing idle memory usage

### ISSUE THREAD

**Issue by kt215** [arangodb/arangodb#4802]
I'm using the latest ArangoDB of the respective release series:
- [x] 3.3

Mode:
- [x] Single-Server

Storage-Engine:
- [x] rocksdb

On this operating system:
- [x] Linux 
  - [x] Ubuntu .deb

I'm using Ubuntu 16.04, and have applied all [these settings](https://docs.arangodb.com/3.3/Manual/Administration/Configuration/OperatingSystem.html) and then rebooted. The virtual machine RAM is 1.75 GB with swap enabled.

After reboot, arangodb starts up automatically, and in my test case I made no connections to arangodb, not even using the web interface, so arangodb is just running idle.

Using the `top` app, the `arangodb [serve` process show this memory usage just after reboot:

**VIRT: 1597356, RES 297380**

After exactly 12 hours running idle, the same process show this memory usage:

**VIRT: 2154256, RES 1.056g**

What's happening here, why is arangodb slowly requiring more and more memory while running idle? Is this fixable with a setting somewhere?

**Comment by seasar** [comment]
I run into the same problem.

**Comment by dothebart** [comment]
though this is older than #4832 - I'm closing this as duplicate, since we have more information there.

**Comment by kt215** [comment]
I disabled server statistics as mentioned in #4832 and now I don't see such a steep increase in memory consumption anymore. So it appears that resolved my issue. Thanks.
