### ISSUE TITLE
Getting multiple fields out of a path, but not all of them

### ISSUE THREAD

**Issue by TFlinguland** [arangodb/arangodb#4836]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [X ] 3.3
Mode:
- [X ] Single-Server

I am wondering, how I can return only single fields from a path, instead the whole path.

What worked:
`RETURN p.vertices[*].title`

Gives back something like this:

```
[
  [
    "Node Title 1",
    "Node Title 3"
  ],
  [
    "Node Title 2",
    "Node Title 4",
    "Node Title 5"
  ]
]
```

But what, if want more than just one field, but less than the entire available path information?
I have tried this (and many other combinations):

`RETURN p.vertices[*].[title,var2,_id]`

I wished to get something like
```
[
  [
    ["Node Title 1", "Var2-Content 1", 11111],
    ["Node Title 3", "Var2-Content 3, 33333]
  ],
  [
    ["Node Title 2",  "Var2-Content 2", 22222],
    ["Node Title 4",  "Var2-Content 4", 44444],
    ["Node Title 5",  "Var2-Content 5", 55555]
  ]
]
```

This one here seems the complicated thing:
`RETURN p.vertices[*].[title,var2,_id]`

Because when I put in 
`RETURN p.vertices[*].title, p.vertices[*]._id `
then it works well, just it is one under the other and not in one array per node.

Do you have a solution (also this might be great in the manual, I have very carefully read...)
Thanks!

**Comment by TFlinguland** [comment]
Have found myself a solution: I just put another LET clause before the RETURN, like this:
```
LET array1 = (
FOR arr1 IN p.vertices[*]
RETURN [arr1._id, arr1._key]
)
RETURN array1
```
Now it comes out as desired above...

**Comment by Simran-B** [comment]
[This syntax](https://docs.arangodb.com/3.3/AQL/Advanced/ArrayOperators.html#inline-projection) should work as well:

    RETURN p.vertices[* RETURN [CURRENT.title, CURRENT.var2, CURRENT._id]]
