### ISSUE TITLE
textAnalzyers Contribution

### ISSUE THREAD

**Issue by p30arena** [arangodb/arangodb#4838]
Hi,
How can I contribute to the upcoming ArangoSearch?
I want to add support for Farsi/Persian language.

This is not satisfying:

> Exposing the capability to specify and configure custom runtime-pluggable analyzers is targeted for releases in the near future.

**Comment by dothebart** [comment]
We're standing on the shoulders of giants here - which probably would require most of the work towards a farsi suppport- 
 - ICU which its using for tokenizing; You would need to verify thats working. 
 - snowball - this is used for stemming; You probably would need to implement something similar to the russian or mandarin implementations

Regarding pluggeable analyzers; we have to do this one step at a time. Accelerating things is allways possible by putting money to more developers; so if you want to see this quicker, get in contact with sales!

**Comment by graetzer** [comment]
To give you some more concrete pointers: 

- To check the tokenization add farsi or persian tests to 
[string-utf8-test.cpp](https://github.com/arangodb/arangodb/blob/devel/tests/Basics/string-utf8-test.cpp) and [string-utf8-normalize-test.cpp]https://github.com/arangodb/arangodb/blob/devel/tests/Basics/string-utf8-normalize-test.cpp

- Next step is to add a stemmer to http://snowballstem.org/algorithms/ which is probably much more complicated

**Comment by gnusi** [comment]
@p30arena thank you for your interest! Pluggable analyzers feature is in our pipeline, but unfortunately at the moment it's planned for *3.4.1* not *3.4*.
For *3.4* we're mostly focused on efficient implementation of cluster wide *ArangoSearch* views.

**Comment by Simran-B** [comment]
Custom Analyzers are supported starting with 3.5.0, but to support Persian/Farsi we need a Snowball stemmer. Feel free to contribute one to that project:
https://github.com/snowballstem/snowball/tree/master/algorithms
We will update the Snowball dependency in a future release.

**Comment by dothebart** [comment]
closing as solved. 
We refresh snowball now and then; If a newer version is available that better suits your needs, please give us a heads up. 

https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/
