### ISSUE TITLE
Multiple attributes for fulltext search.

### ISSUE THREAD

**Issue by F21** [arangodb/arangodb#484]
I would love to be able to search on multiple attributes using fulltext search in AQL:

``` SQL
FULLTEXT(mycollection, ["attributeone", "attribute2"], "myquery")
```

as well as REST:

``` json
{ "collection" : "mycollection", "attribute" : ["attributeone", "attributetwo"], "query" : "myquery" }
```

**Comment by jsteemann** [comment]
Indexing sub-objects and array is now supported in 2.6: 
a brief example can be found in #1195

**Comment by ile** [comment]
:+1:  Would like to get this feature too. 

Sub-objects isn't quite the same as I would like to search based on only some of those sub-objects, and currently it's all or nothing (or one). Yes, as a workaround I could re-arrange the objects but that's not so easy as they may be created by another library and so on...

**Comment by jsteemann** [comment]
Issue #2143 has even more feature requests and provides a good summary of what the current fulltext implementation lacks. Closing this issue now because superseded by #2143.
