### ISSUE TITLE
Allow NEAR() and WITHIN() in AQL to use a filtered list or some appropriate datatype other than collections.

### ISSUE THREAD

**Issue by F21** [arangodb/arangodb#485]
Currently, NEAR() and WITHIN() expects a collection as one of its arguments. This means we cannot filter a collection, then use NEAR() or WITHIN() on that filtered list.

This is a feature request to have this implemented, although it is quite low priority.

Discussion: https://groups.google.com/forum/?fromgroups#!topic/arangodb/ujM8V-7OXk4

**Comment by baslr** [comment]
Maybe more like a AQL syntax
```
FOR doc NEAR 52.5075212 13.3550979 IN myCollection WITH DISTANCE 'dist'
  FILTER doc.status == 'active'
  RETURN doc
---
LET docs = [{…},{…}...]
FOR doc NEAR 52.5075212 13.3550979 IN docs
  FILTER doc.status == 'active'
  RETURN doc
---
FOR doc WITHIN 52.5075212 13.3550979 10 IN myCollection WITH DISTANCE 'dist'
  FILTER doc.status == 'active'
  RETURN doc
```

**Comment by dothebart** [comment]
Quoting the changelog: 

* add implicit use of geo indexes when using SORT/FILTER in AQL, without
  the need to use the special-purpose geo AQL functions `NEAR` or `WITHIN`.

  the special purpose `NEAR` AQL function can now be substituted with the
  following AQL (provided there is a geo index present on the `doc.latitude`
  and `doc.longitude` attributes):

      FOR doc in geoSort
        SORT DISTANCE(doc.latitude, doc.longitude, 0, 0)
        LIMIT 5
        RETURN doc

  `WITHIN` can be substituted with the following AQL:

      FOR doc in geoFilter
        FILTER DISTANCE(doc.latitude, doc.longitude, 0, 0) < 2000
        RETURN doc

  Compared to using the special purpose AQL functions this approach has the
  advantage that it is more composable, and will also honor any `LIMIT` values
  used in the AQL query.

**Comment by dothebart** [comment]
We're pleased to anounce that ArangoDB 3.2 containing this is now available for download - Closing.
