### ISSUE TITLE
[foxx]Is there a way to customize the error output?

### ISSUE THREAD

**Issue by dsonet** [arangodb/arangodb#4852]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.3

Mode:
- [x] Single-Server

Storage-Engine:
- [x] mmfiles

On this operating system:
- [x] Windows, version: 10

### Foxx
When we throw error, it always render like this:
```javascript
{
  "error": true,
  "errorNum": 401,
  "errorMessage": "Unauthorized",
  "code": 401
}
```
we want to unified the error output with other systems. So far I found `usr\share\arangodb3\js\server\modules\@arangodb\actions.js` deals with it. I wonder if you can export the error handle so we can customize our own error handler.

Thanks for your great work.

**Comment by dothebart** [comment]
Hi, 
you should be able to set your own `errorNum` and `errorMessage` ; 
``` 
   var error = new arangodb.ArangoError();
    error.errorNum = arangodb.ERROR_ARANGO_VALIDATION_FAILED;
    error.errorMessage = 'number must be negative';

    throw error;
```
Instead of using the arangodb error numbers as above you can use your own. However, 
automatic translation to HTTP-Errorcodes can't happen then. [here the defined errorcodes for reference](https://docs.arangodb.com/3.3/Manual/Appendix/ErrorCodes.html)

**Comment by dsonet** [comment]
@dothebart Ya, I understand what you mean. But that still produce them same form message. Which I want it could be another form, like:
`{"error": "err description", "code": 419}`

**Comment by Simran-B** [comment]
If you set these attributes, do they get overwritten?

```
 var error = new arangodb.ArangoError();
    error.code = 419;
    error.error = 'Authentication Timeout';
    error.errorMessage = 'Authentication timed out';

    throw error;
```

**Comment by maxkernbach** [comment]
Closing this issue for now since we have not received feedback in the last months.
Please feel free to comment in case the latest suggestion did not help.
