### ISSUE TITLE
[foxx]support multipart upload files

### ISSUE THREAD

**Issue by dsonet** [arangodb/arangodb#4853]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:

- [x] 3.3

### Foxx
Since I use foxx as my micro-services, sometimes I have to handle some text files client upload, parse them, then save to collection. It would be very very helpful to support file upload in foxx.

**Comment by solisoft** [comment]
It is already doable ... look at my sample code here https://github.com/solisoft/foxxy/blob/master/templates/upload/foxx/widget/APP/main.js

**Comment by dsonet** [comment]
@solisoft Thanks, I'll give it try.
What I want is a multipart parser like the nodejs version: https://github.com/pillarjs/multiparty

**Comment by solisoft** [comment]
Here a demo of what I built with it https://twitter.com/olivierb/status/935271872777900032

**Comment by dothebart** [comment]
@dsonet does the video from @solisoft resolve your problems? could we close this issue?

**Comment by dsonet** [comment]
Sure. Thanks.
