### ISSUE TITLE
After upgrade to 3.3.4 : "WARNING Failed to update Foxx store: Error: Failed to update Foxx store" messages in arangod.log

### ISSUE THREAD

**Issue by avive99** [arangodb/arangodb#4860]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [v ] 3.3
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [v ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [v ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [v ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### Foxx

Greetings,

I've upgraded Arango RPM from 3.3.3 to 3.3.4.

Now, when using the Browser Interface - every time i enter into any DB, the following messages appear in the arangod.log file :
2018-03-15T12:33:05 [29317] WARNING Failed to update Foxx store: Error: Failed to update Foxx store
2018-03-15T12:33:05 [29317] WARNING     at Object.update (/usr/share/arangodb3/js/common/modules/@arangodb/foxx/store.js:354:7)
2018-03-15T12:33:05 [29317] WARNING     at Route._handler (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/foxxes.js:363:11)
2018-03-15T12:33:05 [29317] WARNING     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:412:15)
2018-03-15T12:33:05 [29317] WARNING     at /usr/share/arangodb3/js/node/node_modules/lodash/lodash.js:10029:25
2018-03-15T12:33:05 [29317] WARNING     at Middleware.router.use (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/foxxes.js:54:3)
2018-03-15T12:33:05 [29317] WARNING     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:414:15)
2018-03-15T12:33:05 [29317] WARNING     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:410:7)
2018-03-15T12:33:05 [29317] WARNING     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:410:7)
2018-03-15T12:33:05 [29317] WARNING     at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:410:7)
2018-03-15T12:33:05 [29317] WARNING     at dispatch (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:426:3)

I've upgraded arango from 3.3.3 to 3.3.4 at several hosts - and this behavior happens at all of them.
Again, those messages appear after i enter into any DB ("_system" or other/domestic) from Web Browser Interface.

Are those messages harmful or they can be ignored ?

Best regards and looking forward your assistance,
Avi Vainshtein

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click to ...
...

The following problem occurs: [Screenshot?] 
Instead I would be expecting: 

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

**Comment by avive99** [comment]
It has be noted that our ArangoDB hosts don't have internet access.

**Comment by goedderz** [comment]
Hi @avive99,

then that is the reason for the warning. Updating the Foxx store needs internet access. You can safely ignore the warning, but you won't be able to use the store.

Kind regards,

Tobias

**Comment by hkernbach** [comment]
Agree, but maybe we do not want to print the whole stacktrace in that specific case.

**Comment by goedderz** [comment]
That's probably a good idea.
@pluma fyi

**Comment by pluma** [comment]
We could probably just swallow that stack trace. The message originates in aardvark:

https://github.com/arangodb/arangodb/blob/v3.3.4/js/apps/system/_admin/aardvark/APP/foxxes.js#L365

**Comment by goedderz** [comment]
And I'd vote for adding a note to the message that this will happen if there's no internet connection on the server.

**Comment by barakethan** [comment]
+1


Barak Ethan (P.hD)
CEO & Owner
mobile: +972 54 4331222
email: barak@socialskycorp.com
website: www.socialskycorp.com
facebook: www.facebook.com/socialsky
twitter: @barakethan
linkedin: /barakethan

**Comment by avive99** [comment]
Many thanks to all, i'll ignore those messages.
In the future - it indeed would be a good idea to improve those messages text/explanations.

**Comment by mkjaer** [comment]
Is there any way to disable the Foxx Store checking?
Our network admins are not too happy with such spam in their firewalls.

**Comment by pluma** [comment]
FWIW the checks only happen when using the web interface to install/replace a service.

**Comment by maxkernbach** [comment]
Hi @avive99,
version 3.3.8, which includes the fix for this issue has been released.
The log warning does not contain the whole stack trace anymore, instead the warning message `Failed to update Foxx store from GitHub.` is printed.

**Comment by nvlong198** [comment]
version 3.3.8. Failed to update Foxx store from GitHub. and service store have no internet , How i can connect to internet 
\
