### ISSUE TITLE
Arangodb 3.3.5 crashes/stops on windows server 2012 regularly

### ISSUE THREAD

**Issue by ashkan-saeedi-mazdeh** [arangodb/arangodb#4866]
## my environment running ArangoDB
3.3.5 on windows server 2012 on open stack based private cloud

Mode:
- [ ] Single-Server

Storage-Engine:
- [ ] rocksdb

On this operating system:
- [ ] Windows, version: 

We run ArangoDB alongside some other software on the machine like Apache zookeeper and from time to time the windows service for arangodb stops and even with recovery set to restart it fails to restart after some time. Usually happens once in a few days. How can i gather more info so we can find out why? We are not using foxx or any queries, simple key value pair reading and writing and with 100 operations per second at most

**Comment by jsteemann** [comment]
Can you confirm which version of ArangoDB you are actually using? 
Version `3.22` as mentioned above does not exist. I guess it is either 3.1.22 or 3.2.12 then, with RocksDB only being available in the 3.2.x series. So I guess you are on 3.2.12?

**Comment by dothebart** [comment]
https://github.com/arangodb/arangodb/blob/devel/README_maintainers.md#windows-debugging gives some more information about howto obtain crashdumps and what to do with them.

**Comment by ashkan-saeedi-mazdeh** [comment]
Sorry that i did not check and wrote from memory , It is 3.3.1 . I'll look at the doc for logs and try to gather some

**Comment by ashkan-saeedi-mazdeh** [comment]
I tried to get a dump several times using command prompt run as admin but get access violation exception and it doesn't save the dump.
 Arangodb service stops an d despite the fact that i set it to restart for recovery mechanism it doesn't until i restart it manually.
Here it is an image of procdump, Let me know if i can get more info form somewhere, I need a fix fast or need to migrate database. It is using RocksDB btw and now I'm on latest stable.


![image](https://user-images.githubusercontent.com/5682459/38517780-4f8b5158-3c50-11e8-82f5-767b2b4d984a.png)

**Comment by dothebart** [comment]
You now should have a dump file in `c:\Users\Administrator\Downloads\Procdump`. 
You share it for us i.e. via dropbox, and send a link to hackers at arangodb dot com; or acquire the backtrace yourselves as described below in the readme and share it with us in this ticket.

**Comment by ashkan-saeedi-mazdeh** [comment]
@dothebart  That's the thing, There is no dump file there, only a eula text file and procdump itself. I thought that the last line of text in prompt aboe "Dump count not reached" and the one two line above about access violation means that procdump could not store the dump file.

I tried using both arangod.exe as image name and using the process id of it from tasklist /fi "imagename eq arangod.exe" , 
options were set to -accepteula -e -ma

**Comment by ashkan-saeedi-mazdeh** [comment]
I can give you server access if required and anything else, can talk on skype or ... anything

**Comment by kunalak** [comment]
@ashkan-saeedi-mazdeh Is this happening in your production environment or development?
Also, do you have an ArangoDB support subscription with us? That will allow you to open JIRA tickets with us for specific support.

**Comment by ashkan-saeedi-mazdeh** [comment]
@kunalak  It is in my production environment and no i don't have any support subscription. 
If this can not be followed up without buying a subscription then I'm going to switch gear and migrate my data to the database we use for other projects (couchbase) because currently the project is not in a state that i want to pay for this. I'm not trying to be offensive or blunt at all, just saying switching would be easier in the current situation. 

Again I'm on latest version using rocksdb for storage, Windows server 2012 R2 and on open stack using a virtual disk on Open stack for the data folder.

**Comment by kunalak** [comment]
For dedicated and specific SLA based support for you, this is typically provided via a subscription with us that allows us to track issues via customer specific (and private) JIRA tickets. This also enables us to be able to do live web-meeting with you to troubleshoot.

Let us know how we can help.

Lastly, in case you are able to gather dumps and logs and paste them here as requested, our engg teams can take a look when next possible for them in order of priority.

**Comment by ashkan-saeedi-mazdeh** [comment]
Dumps can not be gathered due to the Null Pointer access (probably) and the access violation exception which is uncaught. If there is any other log in any other place which might help , like in windows event traces , I can gather if you let me know where they are. 
I understand you can not provide much support on a case by case basis if it is not paid but since this is probably a bug in the windows service/db implementation or in relation to the new rocksdb integration, i thought you might want to be sure that it is cleared. 

Let me know where i can gather info but our guys might do the migration soon anyways.

**Comment by dothebart** [comment]
You may want to try to upgrade to the most recent version and see whether the error persists and you're able to create a dump of the situtaion. Else we should close this issue.

**Comment by ashkan-saeedi-mazdeh** [comment]
@dothebart  sorry for not closing it. You can close it. 
I've migrated my data to Couchbase. Didn't have much time to spend on it and also needed binary data storage. Also were not using any of your graph related capabilities so switched.
