### ISSUE TITLE
Server id return internal server error instead of an empty id

### ISSUE THREAD

**Issue by StefanoMartin** [arangodb/arangodb#4868]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [X] 3.3
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [X] Single-Server

Storage-Engine:
- [ ] mmfiles
- [X] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [X] Windows, version: 10
- [ ] MacOS, version:

### this is an HTTP API issue

The following request:
`GET http://localhost:8529/_admin/server/id`
Returns to me the following result:
```
{
  "error": true,
  "errorMessage": "internal server error",
  "code": 500,
  "errorNum": 500
}
```

I am not running ArangoDB in a cluster. 
By following the documentation, I was expecting an empty id or a different error.
https://docs.arangodb.com/3.3/HTTP/AdministrationAndMonitoring/

`Returns the id of a server in a cluster. The id is empty if it is working in single server mode.`

Bug in the documentation: The above sentence is repeated twice in the documentation.

**Comment by jsteemann** [comment]
Looking at just the code, it looks like the HTTP 500 is returned intentionally:
From arangod/RestHandler/RestAdminServerHandler.cpp:
```
  auto instance = ServerState::instance();
  if (!instance->isRunningInCluster()) {
    // old behaviour...klingt komisch, is aber so
    generateError(rest::ResponseCode::SERVER_ERROR,
      TRI_ERROR_HTTP_SERVER_ERROR);
    return;
  }
```

**Comment by jsteemann** [comment]
Should be fixed via https://github.com/arangodb/arangodb/pull/4872

**Comment by dothebart** [comment]
Closing as fixed.
