### ISSUE TITLE
Make NEAR() and WITHIN() repeatable

### ISSUE THREAD

**Issue by F21** [arangodb/arangodb#487]
This issue applies to NEAR() and WITHIN() in AQL as well as /_api/simple/near and /_api/simple/within in the REST interface.

Currently, when you have 2 documents in the same coordinates, they are chosen randomly and it is unclear which one will be returned in each request. 

If, for example, we are building an app that finds all the areas of interest (documents) within or near a given postcode (coordinates) and we want to paginate through pages of results, this becomes impossible. While we could use cursors to help, since each request to the our webserver would be independent of previous request, this means that we need to persist the cursor to the user's session. There is also the risk that the cursor will timeout.

My proposal is that for documents which cannot be ordered because their coordinates are the same, order them by their _id. This allows geo queries to ArangoDB to be repeatable and consistent.

**Comment by dothebart** [comment]
We're currently working on geo-indices. We will get cursor support, and results will allways be in the sequence that the distance grows. However, similar distances may vary in sequence. We don't have an ETA on this yet.

**Comment by dothebart** [comment]
Quoting the CHANGELOG: 
* add implicit use of geo indexes when using SORT/FILTER in AQL, without
  the need to use the special-purpose geo AQL functions `NEAR` or `WITHIN`.

  the special purpose `NEAR` AQL function can now be substituted with the
  following AQL (provided there is a geo index present on the `doc.latitude`
  and `doc.longitude` attributes):

      FOR doc in geoSort
        SORT DISTANCE(doc.latitude, doc.longitude, 0, 0)
        LIMIT 5
        RETURN doc

  `WITHIN` can be substituted with the following AQL:

      FOR doc in geoFilter
        FILTER DISTANCE(doc.latitude, doc.longitude, 0, 0) < 2000
        RETURN doc

  Compared to using the special purpose AQL functions this approach has the
  advantage that it is more composable, and will also honor any `LIMIT` values
  used in the AQL query.

**Comment by dothebart** [comment]
We're pleased to anounce that ArangoDB 3.2 containing this is now available for download - Closing.
