### ISSUE TITLE
Document error at https://docs.arangodb.com/3.3/AQL/Operations/Insert.html

### ISSUE THREAD

**Issue by JamesHaskell** [arangodb/arangodb#4881]
In the section "Returning the inserted documents":
`INSERT document IN collection options RETURN NEW`

should be:
`INSERT document IN collection RETURN NEW`

**Comment by jsteemann** [comment]
Should be fixed via https://github.com/arangodb/arangodb/pull/4891

**Comment by OmarAyo** [comment]
Hi @JamesHaskell  ,

Thanks for reporting this bug

We have released 3.3.5, and it includes a fix for it
I am closing this ticket now. Please feel free to reopen if the problem persists
