### ISSUE TITLE
debsum fails

### ISSUE THREAD

**Issue by somehibs** [arangodb/arangodb#4884]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.3

Mode:
- [x] Single-Server

Storage-Engine:
- [x] rocksdb

On this operating system:
  - [x] own infrastructure
- [x] Linux 
  - [x] Debian .deb

### this is an installation-related issue:

I ran `debsums` expecting to receive a successful result, instead a long list of missing files were detected. It would seem that the .deb generated by a jenkins server is having temporary jenkins paths included in the deb without the files.

Here's an example of `debsums` output

`debsums: missing file //var/lib/otherjenkins/workspace/RELEASE__BuildPackages/build-package-debianstretch-v3.3/_CPack_Packages/Linux/DEB/arangodb3-3.3.4-1_amd64/usr/share/arangodb3/arangodb-update-db (from arangodb3 package)
debsums: missing file //var/lib/otherjenkins/workspace/RELEASE__BuildPackages/build-package-debianstretch-v3.3/_CPack_Packages/Linux/DEB/arangodb3-3.3.4-1_amd64/usr/share/arangodb3/arangodb-helper (from arangodb3 package)
debsums: missing file //var/lib/otherjenkins/workspace/RELEASE__BuildPackages/build-package-debianstretch-v3.3/_CPack_Packages/Linux/DEB/arangodb3-3.3.4-1_amd64/lib/systemd/system/arangodb3.service (from arangodb3 package)`

Unfortunately, this prevents me from fully security auditing my system.

**Comment by dothebart** [comment]
Hi, 
we took the aproach to use cpack for generating the .debs, which we are currently dropping. 
Thus we will not fix this in the stable releases on ourselves. 
If you want to have a look at whats going wrong here with the paths, and whether there is an easy fix for this, 
you can simply run on a git clone of this repository:

`./scripts/build-deb.sh` 

which will compile arangodb in the `build-deb/` sub-folder. 

`make package-arangodb-server` in the build folder will invoke the cpack command to create the .debs

**Comment by dothebart** [comment]
I'm closing this question as answered, different .deb's will show up with the 3.4 release.
