### ISSUE TITLE
how to use user function with node package

### ISSUE THREAD

**Issue by nymul-islam** [arangodb/arangodb#4889]
Hello everyone, I faced similar problem like this one. https://github.com/arangodb/arangodb/issues/1092 
but my problem is with moment library (I think it will occur with any node packages). 
my registered function is

`function date(date) {
var moment = require(‘moment’);
var dd = moment(date).fromNow();
return dd;
}
`
and I have got this error:

`user function runtime error: {“error”:true,“errorNum”:3100,“errorMessage”:“cannot locate module\nFile: moment”}`

when I have used AQL like this from FOXX UI:

`FOR doc IN api_v1_user
 FILTER doc._key == “1804774”
 RETURN APPLY(“DATE::RELATIVE”, [doc.userCreateDate])
`
I have installed moment with package.json. what am I missing?

## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [*] 3.3
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [*] Single-Server

Storage-Engine:
- [*] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [* ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

I'm issuing AQL via:
- [* ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

**Comment by dothebart** [comment]
Hi, 
I've tried to require the moment library shipped with `joi` like this from arangosh: 
```
127.0.0.1:8529@_system> moment = require("joi/node_modules/moment")
function utils_hooks__hooks() {
        return hookCallback.apply(null, arguments);
    }

127.0.0.1:8529@_system> 
```
which should work similar from UDFs.

**Comment by vinaypyati** [comment]
Hi @nymul-islam,

Did you have a chance to try the solution suggested by dothebart? Do you still have issues with `moment` library?

Best,

**Comment by maxkernbach** [comment]
I am closing this issue for now as we have not received any feedback for over one month.

Please feel free to comment and reopen in case you have further questions.
