### ISSUE TITLE
After upgrade from 3.2.12 to 3.3 jobs had not been executed

### ISSUE THREAD

**Issue by denya133** [arangodb/arangodb#4898]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [*] 3.3
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [*] Single-Server

Storage-Engine:
- [*] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [*] Linux 
  - [ ] Debian .deb
  - [*] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### Foxx
All newly created jobs in `_jobs` collection have state `pending` and seem to be never executed
I've tryed restart database and run `queues._updateQueueDelay()` but it had not to help.
After have downgraded to 3.2.12 all pending jobs had been executed automatically.

**Comment by pilot4u** [comment]
are there any news regarding this issue?

**Comment by denya133** [comment]
How soon to wait for bug fixes on this issue?
Someone from the developer answer please.

**Comment by zocky** [comment]
Seriously, we need some information on this. Currently it seems impossible to run schedules jobs on ArangoDB, making it useless for most usecases.

**Comment by maxkernbach** [comment]
Version 3.3.9, which includes a fix for foxx queues, has been released today.

**Comment by denya133** [comment]
good news )
