### ISSUE TITLE
3.3.4 replication error "replication dump - unable to find context (it could be expired)"

### ISSUE THREAD

**Issue by avive99** [arangodb/arangodb#4902]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [v ] 3.3
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [ v] Single-Server

Storage-Engine:
- [ ] mmfiles
- [v ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ v] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click to ...
...

The following problem occurs: [Screenshot?] 
Instead I would be expecting: 

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

Greetings,

I've tried to build All-in-one Asynchronous Replication setup between two single hosts, both 3.3.4 version.
The total size of all the  DBs at Master is about 50GB.
On the Slave host i've ran the following commands on 2018-03-15T14:33:15 :
db._useDatabase("_system");
require("@arangodb/replication").setupReplicationGlobal({
  endpoint: "tcp://vm-tskdbn1:8529",
  username: "root",
  password: "mypass",
  autoStart: true
});

That setup ran about 36 hours, most of the 50GB was copied from the Master to the Slave, but then the replication failed. The following messages appeared in the slave's arangod.log file :
2018-03-15T14:33:15 [25118] INFO {replication} connected to master at tcp://vm-tskdbn1:8529, id 189088990993947, version 3.3, last log tick 623793780
2018-03-17T02:06:07 [25118] ERROR {replication} error while running applier thread for global database: got invalid response from master at tcp://vm-tskdbn1:8529 for URL /_api/replication/dump?collection=_appbundles&batchId=286819227&flush=true&flushWait=15&from=0&to=623793781&serverId=159757613179818&chunkSize=2097152&includeSystem=true: HTTP 404: Not Found - {"error":true,"errorMessage":"replication dump - unable to find context (it could be expired)","code":404,"errorNum":400}
2018-03-17T02:06:07 [25118] INFO {replication} stopped replication applier for global database

Few questions on that issue :
Q1. What's the reason of that replication failure ?
Q2. May it be that some replication-critical information became obsolete (deleted ?) on the Master - during those 36 hours setup ran ? May be i shall set some (which ?) parameters to allow Arango to keep some (which ?) information at the Master for more than 36 hours ?
Q3. Is it possible to resume the replication from that point ?

Please , see also my previous cases on the replication-related subjects (<3.3.4v) :
https://github.com/arangodb/arangodb/issues/4305
https://github.com/arangodb/arangodb/issues/4585
https://github.com/arangodb/arangodb/issues/4654

Best regards and looking forward your assistance,
Avi Vainshtein

**Comment by avive99** [comment]
Q4. and also - the most important question: how/is it possible to fasten the initial replication ? The initial replica of 50GB took almost 36 hours. If i just copy 50GB of data (like scp/ftp) between those two hosts - it will take less than 2 hours...

**Comment by maxkernbach** [comment]
Hi @avive99,

in order to fasten the initial replication the slave can be initialized using a backup of the master. A [cookbook](https://docs.arangodb.com/3.3/Cookbook/Administration/Replication/ReplicationFromBackup.html), that describes this procedure, is available in the documentation.

**Comment by avive99** [comment]
Hey @maxkernbach ,

Thanks for your remarks.
As per your mentioned cookbook - the suggested type of master backup is arangodump.
I've tried already to dump that given 50gb database with arangodump - it took about 16 hours.
(you can see the details in my other issue "https://github.com/arangodb/arangodb/issues/4654" )
I don't know how much time it will take to run the arangorestore from that dump at the slave - but could it be it will take no less that another 16 hours ? 
Even in a very optimistic scenario that the arangorestore of 50gb db will take one hour - the total time will be more than 17 hours, and that isn't too fast, isn't it ? Any way, that's no so realistic, especially taking into account that our main database (production host) is about 300gb size, so only the arangodump will run a few days...

Let's say that i find another way to copy the whole contents of the master database directory contents to the slave host - by advanced storage techniques (snap, clone, etc.). Is there any supported way to start replication slave and start replication in such a case ? And mean the all-on-one replication (i.e. all the master databases to be replicated)...

Many thanks and best regards,
Avi

**Comment by dothebart** [comment]
We have added multithreadding to arangodump in devel in the last weeks; you may want to try the nightly client package whether it improves your situation and performance. 

You can't compare the netto bandwith you can achieve with a raw file transfer with what the database has to do. You expect from it to be persistent at document level, durable etc. So behind the curtains it has to do much more than a simple scp would have to do.

**Comment by avive99** [comment]
Hey @dothebart and @vinaypyati ,

Many thanks for your comments.
I understand that 3.3.8 version is available now.
So in the next few days i'll upgrade the arango from 3.3.4 to 3.3.8, and test again both replication setup and arangodump facilities. I'll update that case with new experience.

**Comment by OmarAyo** [comment]
Hi @avive99 

For your information, we have released version 3.3.9

Bes

**Comment by OmarAyo** [comment]
Hi @avive99 

Just sending a quick followup - How do the tests with replication and arangodump are going?
Could you please send us a quick update on this ticket? 

FYI version 3.3.10 is available 

Best,

**Comment by maxkernbach** [comment]
Hi @avive99,

did you have a chance to try the nightly build, which includes multithreading for arangodump?
Also, how are things going with the latest version 3.3.13?

**Comment by maxkernbach** [comment]
Closing this issue for now since we have not heard back from you recently.
Please feel free to send us some feedback and reopen this issue.
