### ISSUE TITLE
Seed rand() with better resolution

### ISSUE THREAD

**Issue by agrothe** [arangodb/arangodb#4906]
rand() seems to be seeded fairly poorly. See this [SO question](https://stackoverflow.com/questions/49358998/randomly-selecting-document-arangodb-often-gives-the-same-results/49389225#49389225).

I'm re-posting my answer here as it explains the issue and possible work-around, but a rand() function should at least take a seed as an argument.

Current Version installed: 3.2.0

Essentially the rand() function is being seeded the same on each query execution. Multiple calls within the same query will be different, but the next execution will start back from the same number.

I ran this query and saw the same 3 numbers each time:

```
return {
    "1": rand(),
    "2": rand(),
    "3": rand()
}
```
Not always, but more often than not got the same numbers:

```
[
  {
    "1": 0.5635853144932401,
    "2": 0.19330423902096622,
    "3": 0.8087405011139256
  }
]
```
Then, seeded with current milliseconds:

```
return {
    "1": rand() + DATE_MILLISECOND(DATE_NOW()),
    "2": rand() + DATE_MILLISECOND(DATE_NOW()),
    "3": rand() + DATE_MILLISECOND(DATE_NOW())
}
```
Now I always get a different number.

```
[
  {
    "1": 617.8103840407173,
    "2": 617.0999366056549,
    "3": 617.6308832757169
  }
]
```

You can use various techniques to produce pseudorandom numbers that won't repeat like calling rand() with the same seed.

**Comment by jsteemann** [comment]
I am not getting the same numbers when repeatedly invoking `RAND()` from AQL.
Can you share with us the exact version of ArangoDB you are using plus the operating system/platform? Maybe it is specific to that. Thanks!

**Comment by agrothe** [comment]
I just upgraded to version 3.3.4, same issue. Maybe its a Windows issue.

Windows 7 Enterprise, SP1, 64bit
Intel Core i5-3320M

The same query above gave me this result three times in a row:

```
[
  {
    "1": 0.0012512588885158849,
    "2": 0.5635853144932401,
    "3": 0.19330423902096622
  }
]
```

**Comment by agrothe** [comment]
Should also mention I'm using the web interface to run the queries.

**Comment by Simran-B** [comment]
Also seeing the same numbers on multiple invocations in arangosh on Windows 10 with v3.3.3:

```json
[
  {
    "1" : 0.0012512588885158849,
    "2" : 0.5635853144932401,         A 
    "3" : 0.19330423902096622
  }
]
[
  {
    "1" : 0.8087405011139256,
    "2" : 0.5850093081453902,         B 
    "3" : 0.47987304300057987
  }
]
[
  {
    "1" : 0.0012512588885158849,
    "2" : 0.5635853144932401,         A 
    "3" : 0.19330423902096622
  }
]
[
  {
    "1" : 0.35029145176549575,
    "2" : 0.8959624011963255,         C 
    "3" : 0.8228400524918363
  }
]
[
  {
    "1" : 0.8087405011139256,
    "2" : 0.5850093081453902,         B 
    "3" : 0.47987304300057987
  }
]
[
  {
    "1" : 0.0012512588885158849,
    "2" : 0.5635853144932401,         A 
    "3" : 0.19330423902096622
  }
]
```

I did not see such repetition in a devel build under Ubuntu.

**Comment by Simran-B** [comment]
> RAND_MAX is defined as the value 0x7fff.

https://msdn.microsoft.com/en-us/library/2dfe3bzd.aspx?f=255&MSPPError=-2147217396

**Comment by jsteemann** [comment]
@Simran-B : this is quite low. On Linux 64-bit it is `2147483647`

**Comment by Dronplane** [comment]
Hi @agrothe !
Please check the latest release https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model
This issue seems to be not reproducable with latest ArangoDB release on Windows10. At least my attempts showed no repetition
`
[
  {
    "1" : 0.0012512588885158849,
    "2" : 0.5635853144932401,
    "3" : 0.19330423902096622
  }
]

[
  {
    "1" : 0.8087405011139256,
    "2" : 0.5850093081453902,
    "3" : 0.47987304300057987
  }
]

[
  {
    "1" : 0.35029145176549575,
    "2" : 0.8959624011963255,
    "3" : 0.8228400524918363
  }
]

[
  {
    "1" : 0.7466048158207953,
    "2" : 0.17410809656056397,
    "3" : 0.858943449201941
  }
]

[
  {
    "1" : 0.7105014191106906,
    "2" : 0.5135349589526047,
    "3" : 0.30399487289040805
  }
]

[
  {
    "1" : 0.014984588152714622,
    "2" : 0.09140293588061159,
    "3" : 0.3644520401623585
  }
]

[
  {
    "1" : 0.14731284524063845,
    "2" : 0.16589861751152074,
    "3" : 0.988525040437025
  }
]

[
  {
    "1" : 0.445692312387463,
    "2" : 0.11908322397534105,
    "3" : 0.00466933194982757
  }
]
`

Feel free to reopen the ticket if problem still persists for you.
