### ISSUE TITLE
Bug that occurs when a query statement is executed(AQL)

### ISSUE THREAD

**Issue by CengSin** [arangodb/arangodb#4908]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [x] 3.3
- [ ] self-compiled devel branch

Mode:
- [x] Cluster
- [ ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [x] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [x] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser:     running on this OS:
- [ ] arangosh
- [x] this Driver:

the first query:
```
for v in CONFIG_ITEM 
    filter v.type == @type 
    and v.fiVos.maintenanceExpireTime <= '1970-01-01' 
    and v.frameVos.maintenanceExpireTime <= '1970-01-01' 
    limit @offset, @count 
return {"fiVos": v.fiVos[0].maintenanceExpireTime, "frameVos":v.frameVos[0].maintenanceExpireTime}
```
the answer of the first query:
![1](https://user-images.githubusercontent.com/23357893/37691894-0c7b2f38-2cf0-11e8-9e23-2443046228b5.png)

the senconds query:
```
for v in CONFIG_ITEM 
    filter v.type == @type 
    and v.fiVos[0].maintenanceExpireTime <= '1970-01-01' 
    and v.frameVos[0].maintenanceExpireTime <= '1970-01-01' 
    limit @offset, @count 
return {"fiVos": v.fiVos[0].maintenanceExpireTime, "frameVos":v.frameVos[0].maintenanceExpireTime}
```

the answer of the seconds query:
![image](https://user-images.githubusercontent.com/23357893/37691889-017b88d0-2cf0-11e8-83cc-29ddc914c9ba.png)

#### `fiVos` and `frameVos` is a array, the `maintenanceExpireTime` must compare the value , but do this , I get the wrong ans..

...

**Comment by CengSin** [comment]
the explain of query:
```
Query string:
 for v in CONFIG_ITEM 
     filter v.type == @type 
     and v.fiVos[0].maintenanceExpireTime <= '1970-01-01' 
     and v.frameVos[0].maintenanceExpireTime <= '1970-01-01' 
     limit @offset, @count 
 return {"fiVos": v.fiVos[0].maintenanceExpireTime, "frameVos":v.frameVos[0].maintenanceExpireTime}

Execution plan:
 Id   NodeType          Site       Est.   Comment
  1   SingletonNode     DBS           1   * ROOT
  8   IndexNode         DBS           8     - FOR v IN CONFIG_ITEM   /* hash index scan */
  9   CalculationNode   DBS           8       - LET #1 = ((v.`fiVos`[0].`maintenanceExpireTime` <= "1970-01-01") && (v.`frameVos`[0].`maintenanceExpireTime` <= "1970-01-01"))   /* simple expression */   /* collections used: v : CONFIG_ITEM */
  4   FilterNode        DBS           8       - FILTER #1
 12   RemoteNode        COOR          8       - REMOTE
 13   GatherNode        COOR          8       - GATHER v ASC
  5   LimitNode         COOR          8       - LIMIT 0, 10
  6   CalculationNode   COOR          8       - LET #3 = { "fiVos" : v.`fiVos`[0].`maintenanceExpireTime`, "frameVos" : v.`frameVos`[0].`maintenanceExpireTime` }   /* simple expression */   /* collections used: v : CONFIG_ITEM */
  7   ReturnNode        COOR          8       - RETURN #3

Indexes used:
 By   Type   Collection    Unique   Sparse   Selectivity   Fields       Ranges
  8   hash   CONFIG_ITEM   false    true             n/a   [ `type` ]   (v.`type` == "ucs_server")

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   move-calculations-up-2
  4   move-filters-up-2
  5   use-indexes
  6   remove-filter-covered-by-index
  7   move-calculations-down
  8   scatter-in-cluster
  9   distribute-filtercalc-to-cluster
 10   remove-unnecessary-remote-scatter
```

**Comment by jsteemann** [comment]
I do not think this is a bug.
The filter condition `v.frameVos[0].maintenanceExpireTime <= '1970-01-01'` will match almost everything.
For example, it would find the following documents:
```
{ "frameVos" : false }
{ "foo" : "bar" }
```
The problem with this filter is that it will first evaluate `v.frameVos`. If that attribute is not present in a document, the value of `v.frameVos` will be converted implicitly to a value of `null`. Then for the value, the sub-attribute `maintenanceExpireTime` will be calculated. If the attribute does not exist, or the previous expression did not produce an object, we will get a value of `null` again.
Finally, the comparison of the expression result with `1970-01-01` will not only be true for some strings, but also for any numeric values, boolean values and the value `null`.

Example for document `{ "foo" : "bar" }`:
```
v.frameVos[0].maintenanceExpireTime <= '1970-01-01'
{ "foo" : "bar" }.frameVos[0].maintenanceExpireTime <= '1970-01-01'
null[0].maintenanceExpireTime <= '1970-01-01'
null.maintenanceExpireTime <= '1970-01-01'
null <= '1970-01-01'
true
```
Please refer to https://docs.arangodb.com/3.3/AQL/Fundamentals/TypeValueOrder.html for an explanation.

If you want to avoid these explicit conversions, you can explicitly check if a document has a specific attribute or not using the `HAS` AQL function, and check the type of any attribute using the `IS_ARRAY` and friends AQL functions.

**Comment by CengSin** [comment]
thanks, this is not a bug , this problem is be solve!!
