### ISSUE TITLE
Arangoimp aborts on version 3.3.3 enterprise during dataimport 

### ISSUE THREAD

**Issue by snowzjy** [arangodb/arangodb#4912]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [x] 3.3
- [ ] self-compiled devel branch

Mode:
- [x] Cluster 
- [ ] Single-Server

Storage-Engine:
- [x] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [x] other:CentOS 7
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
- [x] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser:     running on this OS: Mac OS X
- [x] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [x] authentication is enabled?
- [x] using the cluster? yes,3 nodes,No MESOS and No Docker
- [ ] _system database? No

These are the steps to reproduce:
1)cat x0012.txt| arangoimp --file -  --collection concepte1  --type tsv  --server.endpoint tcp://192.0.0.2:8529 --server.database examples --server.username zjy --server.password xxxxxx --on-duplicate ignore

The following problem occurs: [Screenshot?] 
...----------------------------------------
database:               examples
collection:             concepte1
create:                 no
source filename:        -
file type:              tsv
separator:              
threads:                2
connect timeout:        5
request timeout:        1200
...----------------------------------------
Starting TSV import...

2018-03-21T10:31:35Z [11997] INFO processed 10010624 bytes of input file
2018-03-21T10:31:35Z [11997] INFO processed 20004864 bytes of input file
2018-03-21T10:31:35Z [11997] INFO processed 30031872 bytes of input file
2018-03-21T10:31:35Z [11997] INFO processed 40026112 bytes of input file

2018-03-21T10:34:21Z [11997] ERROR error message(s):
2018-03-21T10:34:21Z [11997] ERROR cluster internal HTTP connection broken
2018-03-21T10:34:21Z [11997] ERROR cluster internal HTTP connection broken
2018-03-21T10:34:21Z [11997] ERROR cluster internal HTTP connection broken
2018-03-21T10:34:21Z [11997] ERROR cluster internal HTTP connection broken
2018-03-21T10:34:21Z [11997] ERROR cluster internal HTTP connection broken

This error occur frequently, it is easy to reproduce.

**Comment by vinaypyati** [comment]
Hi @snowzjy 

Thank you for reporting the issue. 

We tried to reproduce the issue on Linux, Windows, and CentOS. We could not find any crash or error and the data import was successful. A similar issue(#3053) was reported in 3.2.x. This issue was fixed in 3.2.8. We would like to investigate what caused this issue again.

Can you please clarify the following points so that we can reproduce this issue on our side.

- You mentioned that authentication is enabled. Is it the JWT authentication? What commands you use for authentication? 

- If possible can you please share the dataset with us? 

Thanks in advance.

**Comment by OmarAyo** [comment]
Hi @snowzjy

Just sending a follow-up, how things are going ? 
Could you please give us a feedback, or replying to Vinay's questions ?

Thank a lot

**Comment by snowzjy** [comment]
https://concept.research.microsoft.com/Home/Download   this is URL for the dataset.
In my case ,concepte1 is a edge collection, I use arangoimp to import the data, data example like this:
conceptp1/I6952	conceptp1/I1	35167
conceptp1/C1	conceptp1/I2	33222
conceptp1/C1	conceptp1/I3	33185
conceptp1/I3742	conceptp1/I4	18062
conceptp1/I11551	conceptp1/I5	15942
conceptp1/I6952	conceptp1/I6	14230
conceptp1/I6952	conceptp1/I7	13660
conceptp1/I22	conceptp1/I8	11142
conceptp1/I19615	conceptp1/I9	11110
conceptp1/I9072	conceptp1/I1	9375

Authentication I mean the password and username of the server.  
I think this problem is easy to reproduce when I use large amount of data.

**Comment by vinaypyati** [comment]
Hi @snowzjy,

Thank you for the dataset and other information. 
I am now able to reproduce the issue with the dataset(~1.1GB) that you provided us. I think this issue is reproducible with a huge dataset in a cluster environment. 

```2018-04-13T10:42:40Z [12788] ERROR cluster internal HTTP connection broken```

Thanks again for reporting the issue. 

Best Regards,
Vinay

**Comment by dothebart** [comment]
Hi, 
I've managed to reproduce this. 
The core of this problem is that the coordinator isn't patient enougf with the DB-Server, which may be I/O bound. [ArangoImp tries to run two parallel threads, which you can set with `--threads 1`](https://docs.arangodb.com/3.3/Manual/Administration/Arangoimp.html#importing-data-into-an-arangodb-database). You can further reduce the stress by reducing the `--batch-size` to a value like 512000 which should serve as a proper workaround for the time being. 
We're currently investigating howto fix this issue on the serverside too.

**Comment by OmarAyo** [comment]
Hi @snowzjy 

Did you manage to import your db using the above workaround ?

Best,

**Comment by matthewvon** [comment]
@snowzyj I have a pending change to arangoimp that likely addresses your problem (https://github.com/arangodb/arangodb/pull/5238).

I have successfully caused a "Cluster timeout" error while importing your data, but not a "ERROR cluster internal HTTP connection broken" error you experienced.  Would you have time detail all of your configuration:  collection configs (replication factor) and index configs?  I want to build up the entire dataset to make sure my change addresses your exact problem.

Thank you.

**Comment by vinaypyati** [comment]
Hi @snowzjy,

version 3.4.0-RC1 has been released, which contains the fix for this issue. Please check it out. 
I will be closing this issue for now. Please comment, if you the issue still persists, and we will reopen it.

Thanks again for reporting this issue.

Best,
