### ISSUE TITLE
use `DISTINCT` keyword will cause some problem

### ISSUE THREAD

**Issue by CengSin** [arangodb/arangodb#4921]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [x] 3.3
- [ ] self-compiled devel branch

Mode:
- [x] Cluster
- [ ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [x] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [x] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [x] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser:     running on this OS:
- [ ] arangosh
- [x] this Driver:

#### descending sort (right result) 
```
for doc in CONFIG_ITEM 
    filter doc.type == @type
    sort doc.createTime desc
    limit 20, 10 
    return doc.createTime
```

![right](https://user-images.githubusercontent.com/23357893/37749816-baaac4c2-2dc4-11e8-9d96-49e5a87845e5.png)

#### descending sort (errorresult) 
```
for doc in CONFIG_ITEM 
    filter doc.type == @type
    sort doc.createTime desc
    limit 20, 10 
    return DISTINCT doc.createTime
```
![error](https://user-images.githubusercontent.com/23357893/37750885-2d61a936-2dca-11e8-84ad-94e8ce0c2905.png)

what i should do some can solve this error? or i will update the aql??

...

**Comment by CengSin** [comment]
```sql
for doc in CONFIG_ITEM 
    filter doc.type == @type
    sort doc.createTime desc
    limit 20, 30 
    return DISTINCT doc.createTime
```
### result:
![image](https://user-images.githubusercontent.com/23357893/37753790-aa705b34-2dd9-11e8-8d59-2f88a225b324.png)

## without result
```sql
for doc in CONFIG_ITEM 
    filter doc.type == @type
    sort doc.createTime desc
    limit 20, 30 
    return doc.createTime
```
### result:
![image](https://user-images.githubusercontent.com/23357893/37753827-cda874ba-2dd9-11e8-8be0-158ac64bdb3d.png)

## why different in the double query??

**Comment by jsteemann** [comment]
I tried the first few queries locally and they produce the expected sorted result for me, both in cluster and in single server, both with MMFiles and RocksDB. I can only make assumptions about the exact version of ArangoDB you used, the indexes present and the number of shards of the collection and the query execution plans you are seeing. All of that is missing above in the problem description, so I am guessing.

The setup I used which worked just fine for me in single-server and cluster with both storage engines:
```js
db._create("CONFIG_ITEM", { numberOfShards: 5 });
db.CONFIG_ITEM.ensureIndex({ type: "skiplist", fields: ["type", "createTime"] });
for (let i = 0; i < 1000; ++i) {
  db.CONFIG_ITEM.insert({ type: "123", createTime: (new Date(Date.now() - Math.random() * 1000 * 86400 * 30)).toISOString() });
}

q = `for doc in CONFIG_ITEM filter doc.type == @type sort doc.createTime desc limit 20, 10 return DISTINCT doc.createTime `; 
db._explain(q, { type: "123" });
db._query(q, { type: "123" });
``` 
Are you sure you are actually running 3.3? DISTINCT only preserves the order of results since 3.3.0. In 3.2 it changed the order of results.

**Comment by CengSin** [comment]
emmm, i use ArangoDB 3.3.2 to install on before install 3.2.8 of the cluster, but the web interface and the shell show the version is 3.2.8, but i use the 3.3.2, so i don't konw this version, I think i must update the arangodb.
