### ISSUE TITLE
The "slient" flag in document management REST API not working.

### ISSUE THREAD

**Issue by joowani** [arangodb/arangodb#4950]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [x] 3.3
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [x] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [x] Windows, version: 10
- [ ] MacOS, version:

Describe which steps you carried out, what you expected to happen and what actually happened.

The `slient` flag in document management REST API (for example, `DELETE /_db/_system/_api/document/mycollection/1?silent=1`) does not seem to work. It is supposed to return true only, but still returns the full metadata. I observed this in ArangoDB versions 3.3.3 and 3.3.4.

**Comment by maxkernbach** [comment]
Hi @joowani,

thanks for reporting this bug, i was able to reproduce it. With `silent` set to true an empty object is expected as a response but the meta-data is returned instead.

**Comment by dothebart** [comment]
Hi, I can confirm that the silent flag is working again in the fresh released [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model)
Closing as solved.
