### ISSUE TITLE
Pregel does not accept collections in parameters, only graphs

### ISSUE THREAD

**Issue by ghost** [arangodb/arangodb#4952]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [x] 3.3
- [ ] self-compiled devel branch

Mode:
- [x] Cluster
- [x] Single-Server

Storage-Engine:
- [ ] mmfiles
- [x] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [x] docker - official docker library
  - [ ] other:
- [x] Windows, version: 
- [ ] MacOS, version:

#### Steps to reproduce:
Given the  `knows_graph` example dataset in the `dbName` database.

When I would like to use Pregel to calculate PageRank for a set of nodes and edges instead of a full graph by calling the `POST localhost:8529/_db/dbName/_api/control_pregel/` enpdoint with request body:

```json
{
  "algorithm": "pagerank",
  "vertexCollections": ["knows"],
  "edgeCollections": ["persons"],
  "params": {
    "maxGSS": 10,
    "threshold": 10e-7,
    "resultField": "pageRank"
  }
}
```

Then I get the following error message in the response:

```json
{
    "error": true,
    "code": 400,
    "errorNum": 400,
    "errorMessage": "invalid parameters, either collections or graph name"
}
```
#### Expected behavior:
The PageRank calculation has been started with `200 OK` HTTP status code.

#### Issue:
In the `usr/share/arangodb3/js/actions/api-pregel.js` ( https://github.com/arangodb/arangodb/blob/devel/js/actions/api-pregel.js#L69 ), there is a redundant validation expression for `json.edgeCollection`, instead of `json.edgeCollections`:

```javascript
  if (json.vertexCollections && json.vertexCollections instanceof Array
      && json.edgeCollections && typeof json.edgeCollection === 'string') {
  ...
```

should be:
```javascript
  if (json.vertexCollections && json.vertexCollections instanceof Array
      && json.edgeCollections && json.edgeCollections instanceof Array) {
  ...
```

#### Workaround:
As a workaround, the `edgeCollection` field could be provided with a dummy value:

```json
{
  "algorithm": "pagerank",
  "vertexCollections": ["knows"],
  "edgeCollections": ["persons"],
  "edgeCollection": "dummy",
  "params": {
    "maxGSS": 10,
    "threshold": 10e-7,
    "resultField": "pageRank"
  }
}
```

**Comment by graetzer** [comment]
I think 3.4 fixed this issue

**Comment by Simran-B** [comment]
Looks like it: https://github.com/arangodb/arangodb/blob/3.4/js/server/modules/@arangodb/pregel.js#L48
