### ISSUE TITLE
arangoimp issue and a general question

### ISSUE THREAD

**Issue by mohamadHassanHijab** [arangodb/arangodb#4960]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series: 3.1

Mode: Single-Server

On this operating system: Windows, version: 10

My problem is:
When I open arangoimp.exe file it asks me to enter a password, when it is entered and I press (Enter) it will automatically be closed... So what is the solution ?

My another question is:
Can I have the result of the AQL query by graph ?

**Comment by dothebart** [comment]
arangoimp is meant to be invoked in an interactive shell (like cmd, bash or powershell) 

You can use arangoexport to dump parts of a graph: 
https://docs.arangodb.com/3.3/Manual/Administration/Arangoexport.html

**Comment by OmarAyo** [comment]
Hi @mohamadHassanHijab 

Did you manage to invoke _arangoimp_ ?

Please send us a feedback

Best

**Comment by mohamadHassanHijab** [comment]
Hi @OmarAyo ,
Yes, It works and I manage to invoke arangoimp.

**Comment by OmarAyo** [comment]
Perfect !

I'm going to close this ticket, note that tickets can be reopened at any time. 

Best
