### ISSUE TITLE
foxx-manager configuration file

### ISSUE THREAD

**Issue by mhseptiadi** [arangodb/arangodb#4988]
I tried to run configure using `configure` on `foxx-manager`.  Here is my full command:
`foxx-manager configure --server.endpoint tcp://localhost:8529 --server.database mydb --server.password "" --configuration mydb.conf /v1`

However when i tried to load config file `mydb.conf` using `--configuration`, I got error `Error while processing config file 'mydb.conf', line #1`

I create mydb.conf from `foxx-manager configuration --server.endpoint tcp://localhost:8529 --server.database mydb --server.password "" /v1`. The content is:
```
Configuration options:
{
  "testHost": {
    "default": "https://test.myhost.com",
    "description": "Host for test",
    "required": true,
    "type": "string",
    "title": "test Host",
    "current": "https://test.myhost.com"
  },
  "testPass": {
    "default": "testpass",
    "description": "Pass for test",
    "required": true,
    "type": "string",
    "title": "test Pass",
    "current": "testpass"
  },
  "testUser": {
    "default": "myhost_legends",
    "description": "User for test",
    "required": true,
    "type": "string",
    "title": "test User",
    "current": "myhost_legends"
  },
  "code": 200
}
```

I googling and found nothing about this config file should look like.
Can anyone tell me what should the config file look like?

**Comment by mhseptiadi** [comment]
solve it with different way:
1) change arango jwt secret using `/usr/local/sbin/arangod --server.jwt-secret myjwtsecret`
2) directly send http patch to the mounted arango service 
   - url: `http://localhost:8529/_db/mydb/_admin/aardvark/foxxes/config?mount=%252Fmymount`
   - header auth using jwt: `Authorization:Bearer xxxxx...`
   - body: `{"varName":"variable value"}`

**Comment by sikoji** [comment]
ok thank you hasan

**Comment by vinaypyati** [comment]
Hi, @mhseptiadi,

I am going ahead and closing this ticket. Please consider using `FoxxCLI` as 

> It is the successor of foxx-manager, which is deprecated and will be removed eventually.

Please refer to latest [documentation ](https://docs.arangodb.com/latest/Manual/Programs/FoxxCLI/Details.html)on `FoxxCLI`. If you have any further questions on the topic please feel free to reopen this issue with a comment. 

Thanks!
