### ISSUE TITLE
How to SORT when using MERGE?

### ISSUE THREAD

**Issue by Kustopher** [arangodb/arangodb#4997]
I'm using the latest ArangoDB of the respective release series:
- [x ] 3.3

### this is an AQL-related issue
With:
RETURN MERGE(
  FOR u IN users
    SORT u.birthyear DESC
    RETURN {[u._key]:{name:u.first_name, birthyear: u.birthyear} })

I get a non-sorted array:
[ { '3423432': { birthyear: '1977', name: 'Lars' },
    '5745253': { birthyear: '1956', name: 'Jutta' },
    '3032984': { birthyear: '1955', name: 'Dietlind' },
    '9435822': { birthyear: '1984', name: 'Maria' },
    '2423245': { birthyear: '1949', name: 'Karsten' } } ]

Instead I would be expecting a sorted array: 
[ { '9435822': { birthyear: '1984', name: 'Maria' },
    '3423432': { birthyear: '1977', name: 'Lars' },
    '5745253': { birthyear: '1956', name: 'Jutta' },
    '3032984': { birthyear: '1955', name: 'Dietlind' },    
    '2423245': { birthyear: '1949', name: 'Karsten' } } ]

With:
  FOR u IN users
    SORT u.birthyear DESC
    RETURN {[u._key]:{name:u.first_name, birthyear: u.birthyear} }

I get a sorted array:
[ { '9435822': { birthyear: '1984', name: 'Maria' } },
  { '3423432': { birthyear: '1977', name: 'Lars' } },
  { '5745253': { birthyear: '1956', name: 'Jutta' } },
  { '3032984: { birthyear: '1955', name: 'Dietlind' } },    
  { '2423245': { birthyear: '1949', name: 'Karsten' } } ]

but every single object is nested:
0: { '9435822': { birthyear: '1984', name: 'Maria' } }
1: { '3423432': { birthyear: '1977', name: 'Lars' } }
2: { '5745253': { birthyear: '1956', name: 'Jutta'  } }

### related to documentation
I use a very similar example used in the documentation:
https://docs.arangodb.com/3.1/AQL/Operations/Return.html
Here they propose MERGE to get rid of the nesting, but in my example using SORT the results are not returned as expected.

### question
Is there a way to get sorted non-nested results?

**Comment by Simran-B** [comment]
> Is there a way to get sorted non-nested results?

What is the purpose of this anyway?

**Comment by Kustopher** [comment]
Well, I'm referring to the documentation, quoting:

> The result contains one object per user with a single key/value pair each. This is usually not desired. For a single object, that maps user IDs to ages, the individual results need to be merged and returned with another RETURN

The solution in the documentation uses MERGE to get rid of the nesting, but doesn't apply any sorting and when I apply some sorting, it's not working. I don't get why it's not working. Because it's mixing arrays and objects?

Well, how do you handle sorting in ArangoDB? How do you handle the obsolet nesting? Any examples? Later in the application in order to point to one user I need to know its ID plus its extra key value of extra nesting. Both, ID and extra key are unique. I think one unique identifier should be enough.

**Comment by Simran-B** [comment]
Sorting is usually applied to sort (a subset of) documents of a collection based on one or more attributes in each document. The result is an array ob objects.

You can sort the elements of arrays as well:

    FOR elem IN [5, 7, 1, 2] SORT elem RETURN elem // [ 1, 2, 5, 7 ]

If the sorted array is returned by a sub-query, then there will be another pair of brackets:

    RETURN (FOR elem IN [5, 7, 1, 2] SORT elem RETURN elem) // [ [ 1, 2, 5, 7 ] ]

You could use another loop to unwind it:

    LET sorted = (FOR elem IN [5, 7, 1, 2] SORT elem RETURN elem)
    FOR s IN sorted RETURN s

Arrays do have a defined order. Objects however do not. The following objects are identical:

    { "userX": "foo", "userY": "bar"}
    { "userY": "bar", "userX": "foo"}

If you require an order, you could use the following format instead:

    [
      { "name": "userX", "value": "foo" },
      { "name": "userY", "value": "bar" }
    ]

For example:

```
FOR u IN users
SORT u.birthyear DESC
RETURN {
  _key: u._key,
  name: u.first_name,
  birthyear: u.birthyear
}
```

```json
[
  { "_key": "9435822", "birthyear": "1984", "name": "Maria" },
  { "_key": "3423432", "birthyear": "1977", "name": "Lars" },
  { "_key": "5745253", "birthyear": "1956", "name": "Jutta" },
  { "_key": "3032984", "birthyear": "1955", "name": "Dietlind" },
  { "_key": "2423245", "birthyear": "1949", "name": "Karsten" }
]
```

The result is an array (ordered), which can be iterated to access attributes.

If you want to look up a certain name and/or birthyear for a certain user (you know the key), then you can use the MERGE() approach and access an entry like `result[0]["3423432"].name` (Lars). The "order" does not matter in this case. Iterating such an object (`result[0]`) would be kind of strange. JavaScript engines may guarantee insertion order for object keys, but JSON does not. It retain an order, use an array as shown. If that is not sufficient for your access pattern, consider to create a JavaScript object from the JSON data that fulfill your needs.

**Comment by maxkernbach** [comment]
Hi @Kustopher,

has Simran's previous answer been helpful to you or do you have further questions?

**Comment by maxkernbach** [comment]
Closing this issue for now as we have not received any feedback for 2 months.
