### ISSUE TITLE
Adding edge definitions should "adopt" orphan collections

### ISSUE THREAD

**Issue by andregs** [arangodb/arangodb#5015]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ x ] 3.3

Mode:
- [ x ] Single-Server

Storage-Engine:
- [ x ] rocksdb

On this operating system:
- [ x ] Windows, version: 10

Hi!

I created a graph via
`await graph.create({ edgeDefinitions: [...] })`

Then I added orphan collections via
```
  await graph.addVertexCollection('ocean');
  await graph.addVertexCollection('empire');
  await graph.addVertexCollection('dependency');
  await graph.addVertexCollection('marinearea');
```

After that, I added some edge definitions to connect those collections, via
`await graph.addEdgeDefinition(def);`

Edges were created but associated collections were still displayed as "orphan" (see screenshot).

![image](https://user-images.githubusercontent.com/712092/38284332-0bc00ab8-3791-11e8-895e-9b9f60a4bc31.png)

So I tried to save the same edge definitions, but this time via
`await graph.replaceEdgeDefinition(def.collection, def);`

I gave the same definitions, I only changed the arangojs API method (replace instead of add). This time, the orphan collections were adopted successfully.

I think 'add' should behave just like 'replace', by removing connected collections from the "orphan" list, right?

Is there any harm if a collection is kept in the "orphan" list? Will it behave differently from connected collections?

Thanks!

**Comment by dothebart** [comment]
This has been fixed with the 3.4 Graph API rewrite.
ArangoDB 3.4 RC3 is available for download featuring this fix. 

Closing.
