### ISSUE TITLE
Could not access documents in the cluster after one node down

### ISSUE THREAD

**Issue by ile** [arangodb/arangodb#5022]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.3

Mode:
- [x] Cluster

Storage-Engine:
- [x] rocksdb

On this operating system:
- [x] Linux 
  - [x] Ubuntu .deb

### These are the steps to reproduce:

https://arangodb-community.slack.com/messages/C07NV9NAH/convo/C07NV9NAH-1522857484.000306/

I ran the cluster in 3 docker nodes:
```
arangodb --starter.data-dir=./db1 --starter.address=172.17.0.2 --starter.port=5000
arangodb --starter.data-dir=./db2 --starter.join 172.17.0.2:5000 --starter.address=172.17.0.3 --starter.port=5000
arangodb --starter.data-dir=./db3 --starter.join 172.17.0.2:5000 --starter.address=172.17.0.4 --starter.port=5000
```

This seemed to go ok. I then created a database, a collection and some documents. Accessing them in 3 locations worked:

```
http://172.17.0.2:5001/_db/testi/_admin/aardvark/index.html#collection/testc/documents/1
http://172.17.0.3:5001/_db/testi/_admin/aardvark/index.html#collection/testc/documents/1
http://172.17.0.4:5001/_db/testi/_admin/aardvark/index.html#collection/testc/documents/1
```

I stopped node 172.17.0.4. 

**Problem**: After this I couldn't access the documents in any of the above urls. I got the ping-pong screen with "Fetching documents..." text in the web ui in the above urls.

**Comment by ile** [comment]
I used 9 shards, which seemed high, but was the suggestion? DBServers squared.

I didn't set any replication factor. There is some default?

**Comment by weinberger** [comment]
The default of the replication factor is one (https://docs.arangodb.com/3.3/HTTP/Collection/Creating.html). Therefore, if you not set the replication factor higher than one non of the remaning database nodes can take over. 

The number of shards is definitely not to high. It have to much higher before it becomes an issue.

**Comment by dsonet** [comment]
@weinberger I run into the same problem. But which I already setup the replication factor as 2. But after 1 node gone, the cluster can't use anymore. What should I do?

**Comment by dsonet** [comment]
@dothebart I don't think this is resolved. The problem is still appear after I upgrade to 3.3.10.
3 nodes, when one node is down(master agent node), the cluster is gone. Just keep repeat "Failed to get master URL,retry...."

**Comment by maxkernbach** [comment]
Hi @dsonet,

could you upgrade to the latest version 3.3.12 and check if the problem persists (see issue [5373](https://github.com/arangodb/arangodb/issues/5373))?

**Comment by vinaypyati** [comment]
Hi @dsonet,

Just sending a quick follow up. How things are going? Did you have a chance to reproduce this issue on the latest versions - [3.3.21](https://download.arangodb.com/arangodb33/index.html) or [3.4.1 ](https://www.arangodb.com/download-major/ubuntu/) ? 

Thanks!

**Comment by OmarAyo** [comment]
Hi @dsonet 

Since we have not heard back from you in a while, I am closing this issue for now.
In case the problem persists, please provide further details and we would be glad to investigate it.

FYI - ArangoDB Version 3.4.5 is now available for download

Best,
