### ISSUE TITLE
Slow query optimization

### ISSUE THREAD

**Issue by eafiontzi** [arangodb/arangodb#5026]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [x] 3.1.27
- [ ] 3.2
- [ ] 3.3
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [x] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [x] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[x] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [x] this Driver: arangodb-php

The AQL query in question is:
 ```
 FOR v, dOr, p IN 1..6 OUTBOUND "page\/1" pageTree
        LET d = CALL("cms3::getPageChildrenVisitor", v, dOr, p, params)
        FILTER d != null && 
        (d.pageStd_typeKey=="destination" && LIKE(d.pageField_title,"iceland", true))  
        SORT d.pageStd_depth DESC, d.pageStd_vOrder DESC LIMIT 0, 20 RETURN d

```
I've run `db._explain. The result:
```
Execution plan:
 Id   NodeType          Est.   Comment
  1   SingletonNode        1   * ROOT
  3   TraversalNode       17     - FOR v  /* vertex */, dOr  /* edge */, p  /* paths */ IN 1..6  /* min..maxPathDepth */ OUTBOUND 'page/1' /* startnode */  pageTree
  4   CalculationNode     17     - LET d = CALL("cms3::getPageChildrenVisitor", v, dOr, p, { "data" : { "pagePreview" : 0, "langCode" : "el", "fallbackLangCode" : "el", "searchLocalized" : 0, "pageStatus" : 20, "inSiteMap" : 1, "activeLanguageMismatch" : 0, "pageAttrFilters" : [ ], "pageAttrSort" : [ ], "pageFieldFilters" : [ "title" ], "pageFieldSort" : [ ] } })   /* v8 expression */
  5   CalculationNode     17     - LET #7 = ((d != null) && ((d.`pageStd_typeKey` == "destination") && LIKE(d.`pageField_title`, "ισλανδία", true)))   /* simple expression */
  6   FilterNode          17     - FILTER #7
  7   CalculationNode     17     - LET #9 = d.`pageStd_depth`   /* attribute expression */
  8   CalculationNode     17     - LET #11 = d.`pageStd_vOrder`   /* attribute expression */
  9   SortNode            17     - SORT #9 DESC, #11 DESC
 10   LimitNode           17     - LIMIT 0, 20
 11   ReturnNode          17     - RETURN d

Indexes used:
 By   Type   Collection   Unique   Sparse   Selectivity   Fields               Ranges
  3   edge   pageTree     false    false        61.91 %   [ `_from`, `_to` ]   base OUTBOUND

Traversals on graphs:
 Id   Depth   Vertex collections   Edge collections   Options                                   Filter conditions
  3   1..6                         pageTree           uniqueVertices: none, uniqueEdges: path   

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   remove-unnecessary-calculations
  4   move-calculations-up-2
  5   move-filters-up-2
```

As you can see from the information above the query uses an aql function (getPageChildrenVisitor). The query takes about 20 seconds. I tried adding an extra skiplist index in the field vOrder of the pageTree collection (a graph) that get sorted but there was not any improvement. I read that Arango chooses from a collection the index that will optimize the query best (in our case I guess that is the one indexed appear ed in explain), is that correct? The other issue is that most of the work is done inside the aql function so I cannot see the indexes used there. Is there any idea on how to optimize this graph? It contains about 5.500 edges.

Thanks in advance,
Eleni Afiontzi

**Comment by Simran-B** [comment]
What does your function `cms3::getPageChildrenVisitor` actually do? Can you share the code?

**Comment by eafiontzi** [comment]
The user defined function is quite long (about 300 lines) but I could share it if you think that would help.

All pageTree (the graph) nodes are pages characterized by a different pageType and containing many pageFields.  The use of the function: based on some configuration parameters (for example language, fields to be filtered, page type, whether we need published results or not) the function gathers all data from the corresponding page and pageFields collections for every path set from the traversal and returns them in the d variable to be filtered depending on the user choices. 

I have read that "the optimizer can't use indices for UDFs", but I have already added an index for a collection used inside the function which really helped speed up the query.

I am also curious why an extra skiplist index in the pageTree graph for the field vOrder that is used for sorting is not getting chosen over the edge index.

**Comment by Simran-B** [comment]
The performance bottleneck is most certainly that 300 lines UDF.
"the function gathers **all** data" and "for **every** path" sounds pretty bad from a performance perspective.

It's impossible to tell what is the exact cause without the code, but I bet most time is spent on converting large quantities of data to and from V8 data structures. Calling a UDF before filters etc. is generally problematic, especially in cluster.

> I have already added an index for a collection used inside the function which really helped speed up the query
That seems unlikely. The optimizer does certainly not understand JavaScript. Are you sure it's not a cache effect?

Regarding the skiplist index, think of it like this: You got a phone book and pick a place. Doing a traversal kind of randomized all names. To use a skiplist index, you need A to Z or Z to A order however to look up a name quickly. The traversal returns nodes in any order, but there are no entry points for arbitrary nodes in the skiplist (only at front and end).

**Comment by Simran-B** [comment]
> gets the document for each field from the corresponding collection

That sounds like it could be the bottleneck, depending on how many reads that actually requires. It also explains why indexes speed up the UDF: you actually fetch documents from within the UDF, which possibly hits indexes.

Not sure if it's feasible, but it seems like you need a caching strategy and perhaps port some of the code to AQL and get rid of the rest (i.e. offload some work to client if possible).

**Comment by eafiontzi** [comment]
Thanks very much for all the suggestions. Though I understand that it is quite a bottleneck, to get rid of the UDF is not feasible for now, that is why I am looking into indexing.

So your opinion is that the skiplist index for ordering is not something we could look into? The addition of the combined index (page,key), helped a bit but I was still wondering if something additional could be done.

**Comment by Simran-B** [comment]
I can't give any additional recommendations without the full code.

**Comment by eafiontzi** [comment]
So the full AQL query example is (with different params, typeKey, title for different searches)
```
LET params = {
            data: {
                pagePreview: 0,
                langCode: "el",
                fallbackLangCode: "el",
                searchLocalized: 0,
                pageStatus: 20,
                inSiteMap: 1,
                activeLanguageMismatch: 0,
                pageAttrFilters: [],
                pageAttrSort: [],
                pageFieldFilters: ["title"],
                pageFieldSort: []
            }
        }FOR v, dOr, p IN 1..6 OUTBOUND "page\/1" pageTree
        LET d = CALL("cms3::getPageChildrenVisitor", v, dOr, p, params)
        FILTER d != null && (d.pageStd_typeKey=="destination" && LIKE(d.pageField_title,"ισλανδία", true))  
        SORT d.pageStd_depth DESC, d.pageStd_vOrder DESC LIMIT 0, 20 RETURN d
```
while the UDF cms3::getPageChildrenVisitor is defined as follows 
```
require("@arangodb/aql/functions").register(
	"cms3::getPageChildrenVisitor",
function (vertex, document, path, config) {
	var db = require("@arangodb").db;
	var pageType=null;
	var sourcePageKey=vertex._key;

	//set the default configuration data
	var pagePreview=0,
		langCode="en",
		fallbackLangCode="en",
		searchLocalized=0,
		pageStatus=20,
		inSiteMap=1,
		pageAttrs={},
		pageFields={},
		activeLanguageMismatch=1;

	//get the configuration data
	if (typeof config.data === "object") {
		if (typeof config.data.pagePreview !== "undefined") {
			pagePreview=config.data.pagePreview;
		}
		if (typeof config.data.langCode !== "undefined") {
			langCode=config.data.langCode;
		}
		if (typeof config.data.fallbackLangCode !== "undefined") {
			fallbackLangCode=config.data.fallbackLangCode;
		}
		if (typeof config.data.searchLocalized !== "undefined") {
			searchLocalized=config.data.searchLocalized;
		}
		if (typeof config.data.pageStatus !== "undefined") {
			pageStatus=config.data.pageStatus;
		}
		if (typeof config.data.inSiteMap !== "undefined") {
			inSiteMap=config.data.inSiteMap;
		}
		if (typeof config.data.activeLanguageMismatch !== "undefined") {
			activeLanguageMismatch=config.data.activeLanguageMismatch;
		}
		if (typeof config.data.pageAttrFilters !== "undefined") {
			config.data.pageAttrFilters.forEach(function (attribute) {
				pageAttrs[attribute] = attribute;
			});
		}
		if (typeof config.data.pageAttrSort !== "undefined") {
			config.data.pageAttrSort.forEach(function (attribute) {
				pageAttrs[attribute] = attribute;
			});
		}
		if (typeof config.data.pageFieldSort !== "undefined") {
			config.data.pageFieldSort.forEach(function (attribute) {
				pageFields[attribute] = attribute;
			});
		}
		if (typeof config.data.pageFieldFilters !== "undefined") {
			config.data.pageFieldFilters.forEach(function (attribute) {
				pageFields[attribute] = attribute;
			});
		}
	}

	//get the actual page depending the preview mode
	var page=null;
	try {
		if (pagePreview==1 || pagePreview==3) {
			//published OR versioned pub
			page=db.pubPage.document("pubPage/"+vertex._key);

		} else if (pagePreview==0 || pagePreview==2) {
			//edit OR versioned edit
			page=db.page.document("page/"+vertex._key);

		}

	} catch(e){
		//page not found
		return null;
	}

	//check the page status, unless status is disabled
	if (page.status!=pageStatus && pageStatus!=-1) {
		return null;
	}

	//check if the page is active the language provided
	//@todo, consider skipping this check when pageType.inSiteMap==false
	if (activeLanguageMismatch!=0) {
		var activeLang=false;
		//make sure there are some activeLanguages set...
		if (typeof page.activeLanguages === "object") {
			page.activeLanguages.forEach(function (alangCode) {
				if (alangCode == langCode) {
					activeLang=true;
					return null;
				}
			});
		}
		if (!activeLang) {
			//not active language
			return null;
		}
	}

	//if there is a shortcut, retrieve the source page and its type
	var shortcutSourcePage=null;
	try {
		if (page.shortcutSource!=null) {
			//shortcut, retrieve the source page
			if (pagePreview==1 || pagePreview==3) {
				//published or versioned pub
				shortcutSourcePage=db.pubPage.document("pubPage/"+page.shortcutSource);

			} else if (pagePreview==0 || pagePreview==2) {
				//edit or versioned edit
				shortcutSourcePage=db.page.document("page/"+page.shortcutSource);
			}

			//page not found
			if (shortcutSourcePage==null) {
				return null;

			//check the page status, unless status is disabled
			} else if (page.status!=pageStatus && pageStatus!=-1) {
				return null;
			}

			//set the pageType to be equal of the shortcutSourcePage type
			pageType=shortcutSourcePage.type;
			//change the source page key for the pageFields...
			sourcePageKey=page.shortcutSource;

		} else {
			//direct page. set the page type
			pageType=page.type;

		}

	} catch(e){
		//page not found
		return null;
	}

	//the root page does not have vOrder, in case user requests it
	var vOrder=0;
	if (typeof path.edges[path.edges.length - 1].vOrder !== 'undefined') {
		vOrder = path.edges[path.edges.length - 1].vOrder;
	}

	//build the vOrder of the path from root to this vertex
	var vOrderPath=[];
	for(var i in path.edges)
	{
		vOrderPath.push(path.edges[i].vOrder);
	}

	//get the page type, we need it for the inSiteMap flag
	//works properly for shortcuts as well,
	//basically they inherit the source page type
	try {
		pageTypeDoc=db.pageType.document("pageType/"+pageType);
	} catch(e){
		//page type not found
		return null;
	}

	//now check if this page is allowed due to sitemap restrictions
	//0=return those with sitemap=false, 1=return those with sitemap=true, -1=return all
	if (!pageTypeDoc.inSiteMap && inSiteMap==1) {
		return null;
	} else if (pageTypeDoc.inSiteMap && inSiteMap==0) {
		return null;
	}

	//build the result object
	var res = {
		pageStd_id: page._key,
		pageStd_type: pageType,
		pageStd_typeKey: pageTypeDoc.key,
		pageStd_shortcutSource: page.shortcutSource,
		pageStd_depth: path.vertices.length -1,
		pageStd_vOrder: vOrder,
		pageStd_inSiteMap: pageTypeDoc.inSiteMap,
		pageStd_vOrderPath: vOrderPath
	};

	//if there is a parent, get it
	if (path.vertices.length > 1) {
		res.pageStd_parent = {id: path.vertices[path.vertices.length - 2]._key};
	}

	//get page attributes and append them to the result
	for (var key in pageAttrs) {
		var pageAttrValue=null;

		//get the keep the attribute name
		var attrName=pageAttrs[key];

		//attempt to split by . to get the attribute paths (if available). for example "meta.title"
		var pathAttrName = attrName.split('.');

		//check if its pathed attribute or not
		if ((pathAttrName.length==1) && typeof page[attrName] !== 'undefined') {
			//direct attribute name (ie. title)
			pageAttrValue=page[attrName];

		} else if (((pathAttrName.length==2) && typeof page[pathAttrName[0]] !== 'undefined') &&  typeof page[pathAttrName[0]][pathAttrName[1]] !== 'undefined') {
			//indirect attribute name (ie. meta.title)
			pageAttrValue=page[pathAttrName[0]][pathAttrName[1]];
			//replace the separator '.' with '__' in the attribute name so it can be used properly in the sort/filter
			attrName=pathAttrName.join('__');
		}

		//direct attribute name (ie. title)
		if (pageAttrValue!==null) {

			//check if it appears localized
			if (typeof pageAttrValue === 'object' && pageAttrValue!=null) {
				//multilingual field
				if (searchLocalized==0) {
					//search in language or fallbackLang if no value
					if ((typeof pageAttrValue[langCode] !== 'undefined') && pageAttrValue[langCode]!='') {
						//value exists in langCode provided
						pageAttrValue=pageAttrValue[langCode];
					} else if ((typeof pageAttrValue[fallbackLangCode] !== 'undefined') && pageAttrValue[fallbackLangCode]!='') {
						//value exists in fallbackLangCode provided
						pageAttrValue=pageAttrValue[fallbackLangCode];
					} else {
						//value does not exist in provided criteria
						return null;
					}

				} else if (searchLocalized==1) {
					//search only in langCode
					if ((typeof pageAttrValue[langCode] !== 'undefined') && pageAttrValue[langCode]!='') {
						//value exists in langCode provided
						pageAttrValue=pageAttrValue[langCode];
					} else {
						//value does not exist in provided criteria
						return null;
					}

				}

			}

			//set the page attribute value
			res["pageAttr_" + attrName]=pageAttrValue;

		}
	}

	//get the pageField values and append them to the result
	for (var key in pageFields) {
		var attrName = pageFields[key];

		//try to get the pageField and its type
		var pageField = null, pageFieldType = null;
		try {
			if (pagePreview == 1 || pagePreview == 3) {
				//published or versioned pub
				pageField = db.pubPageField.firstExample({page: sourcePageKey, key: attrName});

			} else if (pagePreview == 0 || pagePreview == 2) {
				//edit or versioned edit
				pageField = db.pageField.firstExample({page: sourcePageKey, key: attrName});
			}

		} catch (e) {
			//pageField not found, we skip this page then
			return null;
		}

		//pageField not found, we skip this page then
		if (pageField == null) {
			return null;
		}

		//get the type
		pageTypeField = db.pageTypeField.firstExample({pageType: pageType, key: attrName});

		//append the value BUT take localized, langCode, fallbackLangCode and searchLocalized into consideration
		if (pageTypeField.localized) {
			//multilingual field

			//make sure it has multilingual values inside it
			if (typeof pageField["value"] !== 'object' || pageField["value"] == null) {
				return null;
			}

			if (searchLocalized == 0) {
				//search in language or fallbackLang if no value
				if ((typeof pageField["value"][langCode] !== 'undefined') && pageField["value"][langCode] != '') {
					//value exists in langCode provided
					pageFieldValue = pageField["value"][langCode];
				} else if ((typeof pageField["value"][fallbackLangCode] !== 'undefined') && pageField["value"][fallbackLangCode] != '') {
					//value exists in fallbackLangCode provided
					pageFieldValue = pageField["value"][fallbackLangCode];
				} else {
					//value does not exist in provided criteria
					return null;
				}

			} else if (searchLocalized == 1) {
				//search only in langCode
				if ((typeof pageField["value"][langCode] !== 'undefined') && pageField["value"][langCode] != '') {
					//value exists in langCode provided
					pageFieldValue = pageField["value"][langCode];
				} else {
					//value does not exist in provided criteria
					return null;
				}

			}

		} else {
			//not multilingual field
			pageFieldValue = pageField.value;
		}
		//return the pageField value. This could be string, integer, array of values (tags), etc
		res["pageField_" + attrName] = pageFieldValue;

	}

	return res;
}, true);
```
I understand that it is too much code buy any recommendations are more than welcome.

**Comment by Simran-B** [comment]
@eafiontzi There is a new feature in devel branch to profile queries. It could be interesting to see how much time is spent on which node in the execution plan. It doesn't instrument JavaScript functions however, so it will not be possible to see how much time is spent there on each instruction.

Can you give a brief description of what the JavaScript code does, like the big picture? There seem to be different collections and documents to deal with published and non-published content for your CMS. But I have a hard time to understand what other concepts the code bases on.

**Comment by eafiontzi** [comment]
Yeap, it is a quite complicated function. :(

To understand the code, you should know that all pages in our site are in one collection (page) with different page types. The page fields (based on the page type) are in a collection (pageField) together with their values, and the published page fields in another (pageField). So, the published and non-published content differ mainly in the collections the data are being pulled from. 

So depending on whether the data are published (and a few other configuration parameters like the language) the function (that is called for every graph node and some times for 6 traversal depth) gathers all necessary information (defined as pageAttrFilters in parameters) from the page (or pubPage) collection. Afterwards, it requests all needed information (defined as pageFieldFilters in parameters) from the pageField collection (or pubPageFields). Finally it calculates the path for the ordering of the results and returns all data to the query as the d parameter which is then filtered.

Hope I am clear in my explanation, it took me quite some time myself to get the grasp of the function, that is why it is extremely difficult to change it as it is working on production right now. The indexes in  pubPageFields helped a lot but I was wondering why the skiplist index on vOrder (which is the same pageStd_vOrder that gets sorted) is not working. 

Thank you in advance for your time

**Comment by Simran-B** [comment]
Thanks for all the details!

Indexes can only be utilized if you sort on what is actually stored in documents and hence also in an index. `vOrder` is computed in the JS code however. Sorting by any attribute of `d` can not be accelerated.

Even in pure AQL, a skiplist index couldn't be used if you do a traversal (using the edge index) and then sort on a document attribute. A vertex-centric index might work, but I'm not sure if it's applicable in this situation.

I don't see any easy ways to improve performance further. It would probably require to revise the data model and implement the query differently, using less JavaScript (or none at all).

**Comment by Simran-B** [comment]
@eafiontzi You could somewhat profile the JS code by using `require("internal").time()`, which gives you a pretty high resolution time to measure how long certain parts take. I can't think of a way to instrument a query automatically with this, but doing this manually might be better anyway.

To get the timing results out of your function, you need to return it along with your other returned data and maybe use the AQL WARN function (in devel builds) if you don't want to include the timings in the overall query result.
