### ISSUE TITLE
Application Security -- Database names can be guessed

### ISSUE THREAD

**Issue by fdsg-tk** [arangodb/arangodb#5030]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [X] 3.3 (tested with 3.3.5)
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [ ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [X] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [X] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

The following problem occurs: 
curl --dump - http://localhost:8529/_db/test/_api/database
...shows, that a database called "test" does not exist, even if I do not have any privileges to access it:
{"error":true,"errorNum":1228,"errorMessage":"database not found","code":404}

curl --dump - http://localhost:8529/_db/_system/_api/database
...shows, that a database called "_system" exists, even if I do not have any privileges to access it:
HTTP/1.1 401 Unauthorized

Instead I would be expecting: 
show 
HTTP/1.1 401 Unauthorized
...even if the database does not exist.

**Comment by graetzer** [comment]
will be fixed in 3.4 https://github.com/arangodb/arangodb/pull/5748

**Comment by vinaypyati** [comment]
Hi @fdsg-tk,

version 3.4.0-RC1 has been released, which contains the fix for this security bug. Please check it out. 
I will be closing this issue for now. Please comment, if you the issue still persists, and we will reopen it.

Thanks again for reporting this issue.

Best,
