### ISSUE TITLE
Application Security -- List of Databases is shown to every User with access to at least one database

### ISSUE THREAD

**Issue by fdsg-tk** [arangodb/arangodb#5031]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [X] 3.3 (tested with 3.3.5)
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [ ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [X] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [X] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

These are the steps to reproduce:
1) startup a new arangodb instance with enabled authentification
2) create a new databases called "test", "test2"
3) create a new user called "test" and assign readonly permissions to to database "test"
4) execute: curl -utest:<password> --dump - http://<host>:8529/_db/test/_api/database

The following problem occurs:
Output of curl command is:
{"error":false,"code":200,"result":["_system","test","test2"]}

Instead I would be expecting: 
Show only databases for which user "test" has at least readonly privileges:
{"error":false,"code":200,"result":["test"]}

**Comment by graetzer** [comment]
will be fixed in 3.4 #5748

**Comment by vinaypyati** [comment]
Hi @fdsg-tk,

version 3.4.0-RC1 has been released, which contains the fix for this security bug. Please check it out. 
I will be closing this issue for now. Please comment, if you the issue still persists, and we will reopen it.

Thanks again for reporting this issue.

Best,
