### ISSUE TITLE
Application Security -- ArangoDB Webfrontend uses iframe to show external content

### ISSUE THREAD

**Issue by fdsg-tk** [arangodb/arangodb#5032]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [X] 3.3 (tested: 3.3.5)
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [ ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [X] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [X] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

The following problem occurs:
The ArangoDB Webrfrontend shows external content, which is loaded from third party sources from the internet in an iframe:
https://<hostname>:8529/_db/_system/_admin/aardvark/index.html#helpus
...implements the following iframe with google content:
 <iframe src="https://docs.google.com/forms/d/1vsIwy0mJSeToEnfo_jnBaQebewbcURL730IkZIrkyEE/viewform?embedded=true" scrolling="no" width="100%" height="1300px" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>

If an attacker could change the iframe content, it would look like a normal feature because of the normal arangodb layout.

Instead I would be expecting: 
Do not use iframe with external resources. Add a link to an external webpage instead, which opens in an additonal browser window.

**Comment by dothebart** [comment]
Since this content may be changed with the ArangoDB website and has to be outside of the installation closing this as won't fix.
