### ISSUE TITLE
Arango Cluster couldn't start coordinator

### ISSUE THREAD

**Issue by ahmedogunfayo** [arangodb/arangodb#5034]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [x] 3.3
- [ ] self-compiled devel branch

Mode:
- [x] Cluster
- [ ] Single-Server

Storage-Engine:
- [x] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [x] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click to ...
...

The following problem occurs: [Screenshot?] 
Instead I would be expecting: 

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

After installing arangodb 3.3.5 on 3 different windows servers, I change the endpoint address to the ipv4 Addresses of the machine and I start a cluster for using the following commands;

arangodb --ownAddress 192.168.1.83 on machine A
arangodb --starter.join 192.168.1.83 on machine B
arangodb --starter.join 192.168.1.83 on machine C 
the agents and dbservers where able to start and run on the three machine but the coordinator is not starting on any of the machines with the below error;

Starting coordinator on port 8529
agent up and running (version 3.3.5).
dbserver up and running (version 3.3.5).
coordinator has terminated, quickly, in 9.4278583s (recent failures: 1)
restarting coordinator
Looking for a running instance of coordinator on port 8529
Starting coordinator on port 8529
coordinator has terminated, quickly, in 6.1456392s (recent failures: 2)
restarting coordinator

**Comment by ObiWahn** [comment]
Hi,

please provide the coordinator logs!

**Comment by ahmedogunfayo** [comment]
Thanks for replying please find attached the coordinator log;
[arangod.log](https://github.com/arangodb/arangodb/files/1890310/arangod.log)

**Comment by ObiWahn** [comment]
```
2018-04-09T14:34:31Z [32380] ERROR {communication} unable to bind endpoint: Only one usage of each socket address (protocol/network address/port) is normally permitted
2018-04-09T14:34:31Z [32380] WARNING {communication} failed to open endpoint 'http+tcp://[::]:8529' with error: Only one usage of each socket address (protocol/network address/port) is normally permitted
```
It look like you have some other instance of arangod already running that prevents this new coordinator from binding the to the default port.

**Comment by ahmedogunfayo** [comment]
Thanks @ObiWahn, your solution worked for me, I had to stop the arango single instance running on port 8259 for the coordinator to work.
@vinaypyati yes its been resolved
