### ISSUE TITLE
Application Security -- Cross-Site-Scripting (XSS) possible in ArangoDB Webfrontend

### ISSUE THREAD

**Issue by fdsg-tk** [arangodb/arangodb#5035]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [X] 3.3 (tested with 3.3.5)
- [ ] self-compiled devel branch

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [X] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [X] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) create a new collection
3) go to "Indexes" of the new created collection
4) Click to "+" for creasting a new Index
5) Choose an index type, for example "Hash Index"
6) Insert into "Fields": XSS <script>alert('XSS' + new Date().toJSON());</script>
7) Create Index

The following problem occurs:
A JS popup window occurs everytime you click on the "Index" page of this collection.

Instead I would be expecting: 
Do not allow Cross-Site-Scripting (XSS).

**Comment by hkernbach** [comment]
Thanks for the info. Opened pull requests including fixes for `3.2`, `3.3` and `devel`.

**Comment by maxkernbach** [comment]
ArangoDB version 3.3.10, which includes a fix for this issue, has been released today.
