### ISSUE TITLE
Debugging transactions

### ISSUE THREAD

**Issue by F21** [arangodb/arangodb#504]
Since transactions allow us to pass in pure javascript code, I think it would be useful to allow some form of debugging. For example, just being able to output some variables would be useful.

Maybe something like:

``` javascript
var debugger = require("internal").debug;
result = db.example.save({ Hello : "World" });
debugger.debug("myresult", result);
```

Then, if the transaction fails or succeeds, we get an extra debug property:

``` json
{ "result" : 1, "error" : false, "code" : 200, "debug" : {"myresult": "{....}"} }
```

**Comment by voondo** [comment]
Since this issue is a first page google result for `arangodb transaction debugging`, FWIW, here is a way to display an useful stack trace of an exception:

```js
 db._executeTransaction({
      collections: this.collections,
      params: {
        rows: rows
      },
      action: (params) => {
        try {
          // code throwing exceptions
        } catch(e) {
          for(const line of e.stack.split("\n")) {
            console.error(line)
          }
          throw e
        }
      }
    })
```
