### ISSUE TITLE
Fulltext index : use same prefix multiple times

### ISSUE THREAD

**Issue by matcho** [arangodb/arangodb#5057]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.3

Mode:
- [x] Single-Server

Storage-Engine:
- [x] rocksdb

On this operating system:
- [x] Linux 
  - [x] Ubuntu .deb

I'm issuing AQL via:
- [x] arangosh

### The issue

In a fulltext index, specifying multiple times the same prefix behaves like the prefix was specified only once.

What I'm looking for is asking the index "give me all documents having 2 (or more) *different* words with this prefix", but it seems this cannot be achieved.

Ideally, could this be implemented in a future version ?

The issue can be reproduced using this dataset:
```
db._create('testft')
db.testft.ensureIndex({ type: "fulltext", fields: ["value"], minLength: 2 })
db.testft.save({ value: "foored" })
db.testft.save({ value: "fooblue bar" })
db.testft.save({ value: "foogreen foobrown" })
db._query('FOR f IN FULLTEXT(testft, "value", "prefix:foo") RETURN f.value')
db._query('FOR f IN FULLTEXT(testft, "value", "prefix:foo,prefix:foo") RETURN f.value')
db.testft.drop()
```
I would expect the last query above to return only "foogreen foobrown" as this entry only has two different words with the prefix "foo", but instead it returns all entries having a prefix "foo", just like the first query.

Thanks for your consideration,
All the best

**Comment by maxkernbach** [comment]
Hi @matcho,

this query output is expected. The query conditions "prefix:foo,prefix:foo" are AND-combined. Both conditions are exactly the same and look for documents that contain any words starting with the prefix foo. Therefore every document, that contains any word starting with "foo", is returned.

The current Fulltext index implementation is working as intended, multiple same prefixes as in your use case are not supported.

**Comment by matcho** [comment]
Thanks @maxkernbach for your quick answer.
Hope this feature will pop one day; who knows :)

**Comment by Simran-B** [comment]
You could somewhat achieve that by first using a fulltext index search `prefix:foo` and another condition like this:

```
FOR f IN FULLTEXT(testft, "value", "prefix:foo")
  LET occurrences = LENGTH(SPLIT(f.value, "foo")) - 1
  FILTER occurrences >= 2
  RETURN f.value
```

Only one occurrence of "foo" has to be a word prefix. Additional occurrences are not necessarily at word boundaries.

**Comment by matcho** [comment]
Thanks @Simran-B  nice idea !
