### ISSUE TITLE
How to get real-time changes from the database?

### ISSUE THREAD

**Issue by Extarys** [arangodb/arangodb#5067]
Is it possible to get online presence or create a chat app with ArangoDB? Or should I use RethinkDB for that?

**Comment by ObiWahn** [comment]
Of course you can create a chat app with ArangoDB. Maybe you can tell us more about your use case.

**Comment by dothebart** [comment]
This is actually a duplicate of https://github.com/arangodb/arangodb/issues/602 - all currently available solutions have been discussed there.

**Comment by Extarys** [comment]
Thanks both of you I'll refer to the other issue!

**Comment by karankapur999** [comment]
@ObiWahn 

could you please help me  review the stability for 
https://www.arangodb.com/2017/03/arangochair-tool-listening-changes-arangodb/
To brief you we are planning for real time notifications on a  DB  collection updates + We also plan to work on a chat .
So is all this supported by arango?
Thanks

**Comment by Extarys** [comment]
Thanks @karankapur999 for that. I'm implementing Arangochair now :smile: 
@dothebart This issue seems more like a bunch of suggestions rather than a solution to a problem.

**Comment by Extarys** [comment]
Hmm I didn't see it before but **arangochair** wasn't updated for 2 years. 

@ObiWahn I'd like to notify users when they receive a message for example without having to query the server every x seconds. I'm implementing Apollo with ArangoDB right now and my app already have an extablished websocket to the api server.

I'm still learning GraphQL and Apollo. On the server I have a connection made with `subscriptions-transport-ws` and the client is connected with `apollo-link-ws`. Everything works except live changes/notifications/etc. I wanted to "know" Arango before pursuing the Apollo websocket thing. :smiley_cat: 

Could you guide me in the right direction? I would like to avoid unmaintained packages - obviously.

**Comment by Extarys** [comment]
As I said, the issue you provided are suggestions, not solutions. Nothing is implemented. Or I missed it, in that case - I still don't know how to do it.

> all currently available solutions have been discussed there

Could you tell me what is the available solution please? @ObiWahn seems to think there is an actual solution to this.

**Comment by dothebart** [comment]
Closing as answered.
