### ISSUE TITLE
when create Index to a large amount data collection,report  arango.exceptions.IndexCreateError: [HTTP 400][ERR 1457] timeout in cluster operation

### ISSUE THREAD

**Issue by snowzjy** [arangodb/arangodb#5068]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [x] 3.3
- [ ] self-compiled devel branch

Mode:
- [x] Cluster
- [ ] Single-Server

Storage-Engine:
- [x] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [x] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [x] other: centos
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[x] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser:     running on this OS:
- [x] arangosh
- [x] this Driver: python-arango

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [x] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
when create Index to a large amount data collection use python or use web UI or use arangosh:
from arango import ArangoClient
client = ArangoClient(
    protocol='http',
    host='xxx',
    port=8529,
    username='xxx',
    password='xxx',
    enable_logging=True
)
db = client.db('examples')
c1=db.collection("wikidatap1")
c1.add_skiplist_index(fields=['labels.xxxx'], sparse=True,deduplicate=False)

The following problem occurs: [Screenshot?] 

arango.exceptions.IndexCreateError: [HTTP 400][ERR 1457] timeout in cluster operation

if I use arangosh,run ensureIndex function,the Error still occor:
JavaScript exception in file '/Applications/ArangoDB3e-CLI.app/Contents/MacOS/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js' at 98,7: ArangoError 1457: timeout in cluster operation
!      throw error;
!      ^
stacktrace: ArangoError: timeout in cluster operation
    at Object.exports.checkRequestResult (/Applications/ArangoDB3e-CLI.app/Contents/MacOS/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js:96:21)
    at ArangoCollection.ensureIndex (/Applications/ArangoDB3e-CLI.app/Contents/MacOS/usr/share/arangodb3/js/client/modules/@arangodb/arango-collection.js:656:12)
    at <shell command>:1:15

Instead I would be expecting: 
no error reported and  create Index success.

**Comment by ObiWahn** [comment]
Hello,

we have increased the timeout for index creation in the cluster to 1 hour in the 3.3.5 release. Furthermore, there is now a hidden option `--cluster.index-create-timeout` to increase this even further. This option needs to be given on the coordinator executing the index creation operation.12

**Comment by snowzjy** [comment]
Thank you ,I will try. If I upgrade,the data  will be untouched ?

**Comment by maxkernbach** [comment]
Hi @snowzjy,

yes a cluster upgrade can be performed without any data loss. It is still recommended to do a backup before though.
Have a look at our [cluster administration course](https://www.arangodb.com/arangodb-cluster-course/), which describes a procedure on how to do a rolling upgrade using the starter.

**Comment by ObiWahn** [comment]
@snowzjy are you able to confirm that the new version fixes your problem?

**Comment by snowzjy** [comment]
How to use option --cluster.index-create-timeout 10800?
I have upgrade to 3.3.7,I use python and web UI to create index,may be too much data, I did't recived any info for result and the index did't created. I guess one hour is not enough.
When I run  arangosh or arangodb starter use --cluster.index-create-timeout option, error reported:

arangodb starter :
Error: unknown flag: --cluster.index-create-timeout
arangosh:
Error while processing command-line options:
  unknown option '--cluster.index-create-timeout'

**Comment by dothebart** [comment]
Hi, this can be achieved using the pass option:

https://docs.arangodb.com/devel/Manual/Programs/Starter/Options.html#other-database-options

so it would become `--all.cluster.index-create-timeout 10800`

**Comment by maxkernbach** [comment]
Hi @snowzjy,

did you have a chance to try the suggested option?

**Comment by maxkernbach** [comment]
Thanks for your feedback, I am closing this issue for now.
