### ISSUE TITLE
Arangorestore seems not to dump collection content with overwrite=true

### ISSUE THREAD

**Issue by TFlinguland** [arangodb/arangodb#5094]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x ] 3.4 MI

Hi dear Arango Team,
in the documentation the `overwrite` parameter is explained to be allowed for `arangoimp` and `arangodump`. 

For `arangorestore` it is also mentioned, but not in the documentation, only in the `arangorestore.exe --help `. It shows like this:

```
Usage: arangorestore [<options>]

Section 'global options' (Global configuration)
  --batch-size <uint64>                              maximum size for individual data batches (in bytes) (default:
                                                     8388608)
  --collection <string...> restrict to collection name (can be specified multiple times)
                                                     (default: )
  --configuration <string>                           the configuration file or 'none' (default: "")
  --create-collection <boolean>                      create collection structure (default: true)
  --create-database <boolean>                        create the target database if it does not exist (default: false)
  --default-number-of-shards <uint64>                default value for numberOfShards if not specified (default: 1)
  --default-replication-factor <uint64>              default value for replicationFactor if not specified (default: 1)
  --force <boolean> continue restore even in the face of some server-side errors
                                                     (default: false)
  --force-same-database <boolean>                    force usage of the same database name as in the source dump.json
                                                     file (default: false)
  --ignore-distribute-shards-like-errors <boolean> continue restore even if sharding prototype collection is missing
                                                     (default: false)
  --import-data <boolean>                            import data into collection (default: true)
  --include-system-collections <boolean>             include system collections (default: false)
  --input-directory <string>                         input directory (default: "c:\Program Files\ArangoDB3 3.4.
0\usr\bin\dump")
  --overwrite <boolean> overwrite collections if they exist (default: true)
  --progress <boolean>                               show progress (default: true)
  --version <boolean>                                reports the version and exits (default: false)

```

**PROBLEM:**
When restoring with `arangorestore` we have a different content-count of data in the collections.
It seems the parameter `overwrite` is either not considered, or alternatively it does not work.

Unfortunately we can not dump all collection content before with `arangodump`, as it refers to only one collections, but we have many we want to restore.

**OBJECTIVE: **
When restoring the database we want to have (after restoring) the identical datasets as in the version that we use for overwriting the old one (we want to delete the old version, and not keep old records in, meaning that probably collections needs to be dumped or at least truncated).

What could we do?
Is that a bug? Maybe you know an alternative what we could do.

Thanks a lot,
best regards,
Tobias

**Comment by dothebart** [comment]
Hi, 
the milestone release is already a bit old and several fixes in that area have been made. 
Would you mind retrying with the nightlies?

**Comment by TFlinguland** [comment]
Thanks, good advice.

The 3.4 version is the latest one on the download section of arango website.
How can we possibly know that this release is already a bit old?
https://www.arangodb.com/download-major/windows/ only offers 3.3.5

So I googled and found this:
https://download.arangodb.com/

Is that the latest one you were referring to?
Thanks a lot,
Tobias

**Comment by TFlinguland** [comment]
We have now installed the mentioned Version "nightly" windows 64.
The `overwrite` parameter seems not working.

But this bug is there again:
https://github.com/arangodb/arangodb/issues/4453

Sure that this is the latest version?

**Comment by dothebart** [comment]
oh, you're actually right. we have a bug in the release scripts for windows upload. - fixed that and uploaded. I'm currently working to get the nightly back online, will note here once its done.

**Comment by dothebart** [comment]
Ok, we have a fresh nightly build with a successfull upload of the new windows binary please re-test.
Sorry for the delay.

**Comment by dothebart** [comment]
@TFlinguland have you been able to follow up on this? Did the nightlies work for you?

**Comment by OmarAyo** [comment]
Hi @TFlinguland,

Just sending a quick followup - could you please send us an update on this ticket? 

Best,

**Comment by OmarAyo** [comment]
Hi @TFlinguland 

I am going to close this ticket, note that tickets can be reopened at any time by adding a new comment

Thanks,
