### ISSUE TITLE
importing several collections in arangoimp

### ISSUE THREAD

**Issue by issawayzani** [arangodb/arangodb#5095]
hello please i want to know how to import several collections in arangoimp i used file command but i can only specify one file so please how can i use with several files at once ?

**Comment by Simran-B** [comment]
Arangoimp can import one file into a single collection at a time. You can of course invoke it as often as required to import all your files.

The probably easiest way to import two files on the command line is with `&&` to execute two commands in sequence (should work across platforms):

    arangoimp --collection coll --file file1.json && arangoimp --collection coll --file file2.json

You can of course use Bash, Batch or PowerShell scripts too.

**Comment by issawayzani** [comment]
i thought i could import several files at once okay thank you just one more question can you please give an example of using  bash ,batch or powershell scripts

**Comment by issawayzani** [comment]
i am using windows btw thanks for your help

**Comment by Simran-B** [comment]
Here is a straightforward example for a PowerShell script:

```ps1
$cwd = 'C:\Program Files\ArangoDB3 3.3.5'
$arangoimp = '.\usr\bin\arangoimp.exe'
$path = 'C:\Users\xyz\import_files'
$files = Get-ChildItem -Path $path -Filter '*.jsonl'

$baseParams = @(
    '--server.password', '""',
    '--create-collection', 'true'
)

Function collectionName($filename) {
    $filename -Replace '[^A-Za-z0-9_-]+','_' -Replace '^([^A-Za-z])','xx_$1'
}

Push-Location $cwd

ForEach ($file in $files) {
    & $arangoimp $baseParams + @(
        '--collection', (collectionName $file.BaseName),
        '--file', $file.FullName
    )
}

Pop-Location
```

It uses `C:\Program Files\ArangoDB3 3.3.5\usr\bin\arangoimp.exe` to import all `.jsonl` files from folder `C:\Users\xyz\import_files`. It uses file names as collection names and tries to sanitize them because they might have invalid names for ArangoDB.

**Comment by issawayzani** [comment]
okay thank you so much it worked
