### ISSUE TITLE
How to collect hardware events of ArangoDB with profiling tool

### ISSUE THREAD

**Issue by Jacob-Kang** [arangodb/arangodb#5101]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [x] 3.3
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [ ] mmfiles
- [x] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [x] other: Ubuntu compiling
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is a arangod issue:

On a Ubuntu server 14.04 (4.4.0-62-generic) on Intel Xeon CPU E5-2698 v4, I am trying to collect hardware event counts for ArangoDB with Intel VTune.
`amplxe-cl -collect memory-access -- ./arangod`
 But when I start collecting, the server will die right away.

I think this reason is that ArangoDB is collecting hardware events internally. So I tried to turn off the ArangoDB's statistics gathering.

`--server.statistics value`
But still the same.

How can I collect hardware events of ArangoDB with profiling tool?

**Comment by ObiWahn** [comment]
Hi Jacob,

the statistics that arangod collects are more about number of requests, their duration and network traffic. If I am not mistaken we do not collect hardware events at runtime. We use the [perf-tools](https://github.com/brendangregg/perf-tools) to collect some performance data when profiling. Maybe [setupPerfEvents.sh](
https://github.com/arangodb/arangodb/blob/devel/scripts/setupPerfEvents.sh) in our repository is a good starter on how to collect the information you want.

**Comment by Jacob-Kang** [comment]
@ObiWahn 
Thanks for replying.
I appreciate you pointing me in the right direction with this problem.
Finally I can profile this.
thanks.
Jacob
