### ISSUE TITLE
Issues (potentially with) 'waitForSync: true'

### ISSUE THREAD

**Issue by ryanhaney** [arangodb/arangodb#5102]
Referencing this issue from arangodb-java-driver-async:
https://github.com/arangodb/arangodb-java-driver-async/issues/11

I'm not sure if this is a driver issue or db issue.

Thanks!

**Comment by ObiWahn** [comment]
So far I do not see a problem or anything unexpected. You have to wait until the request returns for that you wait (waitForSync: true) for. If you use an async-driver it could happen that you send the next request, before the first requests succeeds. Just make sure to not en-queue requests that depend on other requests before the required requests have succeeded.

**Comment by ryanhaney** [comment]
Unless something is horribly wrong with my understanding of _for comprehensions_ in Scala, I believe the following statements are executed sequentially:

```
for {
  sl <- l
  el <- sl
  if el > 0
} yield el.toString.length
```
https://docs.scala-lang.org/tutorials/FAQ/yield.html

You'll notice `sl` is used as input into `el`, and the value of `el` is evaluated in the `if`.

Essentially, my code is like the following:

```
for {
  _ <- RunStatement1
  _ <- RunStatement2
} yield //some result here 
```

`RunStatement1` and `RunStatement2` return Scala Futures. `RunStatement1` inserts data into Arango, while `RunStatement2` further processes that inserted data.

At this point, _I am not able to reproduce this issue_ and have asked for `waitForSync` testing guidance at https://github.com/arangodb/arangodb-java-driver-async/issues/11.

Thanks!

Ryan

**Comment by dothebart** [comment]
Hi, 
maybe there is a bit of a misunderstanding what `waitForSync = true ` actually means. 
WaitForSync means, that the write operations of this request is warantied to be persisted to the storage; so in case of power failure or system crash these documents are already synced to the physical storage unit once your query returns its results to you. Regular queries without waitForSync in contrast will be stored, but there is a sync frequency inside the server that will trigger these syncs in given time intervals. This may be ok for most usecases, however if you i.e. operate with account balances you may want to be sure that this operation is persistet at the cost of having to wait for the slower storage layer. 

However, when you send requests at the same time there is no warrantied sequence of their execution; waitForSync doesn't have any influence on that; you're using an event driven async io framework under the hood which must not wait for external IO to arrive at any cost. It will call you back once the data arrives. While you're writing your code in a sequence, this sequence is not what happenes in realtime the way you expressed it. 
By using the futures in the async driver, the request will only be fulfilled when this future arrives. 
If you send two requests the way you do, they're sent over the wire "simultaneously" without waiting for their results, and may return to you in any sequence. Thus you may see your query fail, or execute in the right sequence and succeed the way you're doing it.

You have to chain these requests on the client if you want to have a valid sequence. This means, you must not send another query while you don't have the reply from arangodb for the first query. 

I'm sorry I'm don't know how to express this in scala, but in arangojs it would look somewhat like this:
```
db.query({first query })
  .then(function(cursor) {
    db.query({second query}).then(
      ...
    });
  })
```

**Comment by mpv1989** [comment]
I've written a small example how I would use `for...yield` in Scala with the async driver. Everything worked as expected

```
import com.arangodb.ArangoDBAsync
import scala.reflect.ClassTag
import collection.JavaConversions._
import scala.beans.BeanProperty
import scala.compat.java8.FutureConverters
import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent.Await
import scala.concurrent.duration._

case class Entity(@BeanProperty value: String) {
  def this() = this(value = null)
}

object App {

  def main(args: Array[String]): Unit = {
    val arango = new ArangoDBAsync.Builder().user("root").build()

    try {
      val collection = arango.db().collection("test");
      val entity = Entity(value = "old-value")

      val res = for {
        insert <- FutureConverters.toScala(collection.insertDocument(entity))
        replace <- FutureConverters.toScala(collection.replaceDocument(insert.getKey, Entity(value = "new-value")))
        read <- FutureConverters.toScala(collection.getDocument(insert.getKey, classOf[Entity]))
      } yield (read.value)

      Await.result(res, 5000 millis)
      println(res)

    } catch {
      case t: Throwable => t.printStackTrace()
    } finally {
      arango.shutdown()
    }
  }

}
```

**Comment by ryanhaney** [comment]
My code is essentially the same (using a `for...yield`), except I am using AQL instead of `collection` methods. As I stated in https://github.com/arangodb/arangodb-java-driver-async/issues/11:

> At this point, I'm not even sure it's related to arango at all.

I'm going to close this issue until I can prove it needs to be redressed.

I appreciate your patience and assistance on this.
