### ISSUE TITLE
segfault when updating links properties

### ISSUE THREAD

**Issue by richardhundt** [arangodb/arangodb#5146]
## my environment running ArangoDB

Notes:
* I installed 3.4.milestone0 over an existing 3.3 installation while keeping the existing data directories.
* I'm running on Ubuntu 17.10 (instead of the supported 17.04)
* I'm current compiling from source to control for the above

I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [ ] 3.3
- [x] 3.4.milestone0
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [x] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [x] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database `my_database`
4) create a new view
5) select the view showing the view descriptor (json document)
6) select editor mode
7) modify the empty links section adding `{ "my_collection": { "includeAllFields": true } }`
8) click `save`

This is obviously not a UI related issue (SIGSEGV), but this is how I did it.

**Comment by richardhundt** [comment]
I've got some updates:

* `devel` compiled from scratch also has the issue
* I switched to the docker image, problem persists

The interesting bit is that it seems to be dependent on the size of the data in the collection.

I thought it might be due to the data itself, initially (invalid `utf-8` sequences or something), so I tried the following:

```
$ cat my_data.json | tail -n 1000 >sample.json
$ arangoimport --server.database _system --server.username root --server.password openSesame --collection 'my_db' --create-collection true sample.json
```
That explodes when I say `v0.properties({links: { "my_db": {includeAllFields: true}}, true)`

However, both of the following succeed:
```
$ cat my_data.json | tail -n 1000 | head -n 500 >sample.json
$ cat my_data.json | tail -n 500 >sample.json
```
So it seems I can add either half of the data before creating the view and I'm fine, but with 1k documents :boom:

**Comment by gnusi** [comment]
@richardhundt, can you provide us the data you're trying to put into the view?

**Comment by gnusi** [comment]
@richardhundt great, will have a look, thank you!

**Comment by gnusi** [comment]
@richardhundt we've investigated the issue and will fix it in the one of upcoming nightly builds. Will let you know, and thank you once more!

**Comment by richardhundt** [comment]
cool, thanks, I think it's a killer feature, so I look forward to trying it out.

**Comment by vasiliy-arangodb** [comment]
Hello,
Please confirm that the issue has been addressed in the latest 'devel'.
Thank you

**Comment by richardhundt** [comment]
I've compiled latest devel and it works now, thanks. I'll continue testing the search capabilities. Shall I close the issue?

**Comment by dothebart** [comment]
Ok, great - I will close this as solved then now. 
Thank you very much for confirming.

**Comment by gnusi** [comment]
@richardhundt thank you for validation! let's close the issue when corresponding nightly or hotfix for milestone will be there.
BTW if you're interested in more ArangoSearch stuff you can join `#arangosearch` channel on our community slack `https://arangodb-community.slack.com`

**Comment by richardhundt** [comment]
lol, thanks for the slack tip, I just asked where to participate in `#general` before reading this

**Comment by richardhundt** [comment]
This isn't fixed. When I tested earlier, I had unset `GLIBCXX_FORCE_NEW`.

In this state I can create a view, set its properties and load it via `v0 = db._createView("my_view", "arangosearch", {});`, `v0.properties({links: {"dbp_organisations": {includeAllFields: true}}}, true);` then `v1 = db._view("my_view")`

That works until I try to restart the server, in which case I get:

```
ERROR view id 2195 has same name as already added view 2195
```

However, if I `export GLIBCXX_FORCE_NEW=1` I get a segfault as before when I set the properties.

Do you want to re-open this ticket, or do I create a new one?

**Comment by gnusi** [comment]
@richardhundt would be great to have a new one.
