### ISSUE TITLE
Query cache for ArangoDB

### ISSUE THREAD

**Issue by F21** [arangodb/arangodb#516]
Discussion here: https://groups.google.com/forum/?fromgroups#!topic/arangodb/Tx-P57xT8DU

In a nutshell, this is a feature request to implement a query cache, which may or may not be implemented in the future.

Essentially, all queries would check the cache first, before processing (if required). Making changes to the collection would invalidate cache entries.

As Jan has pointed out in the discussion, a cache is useful, but it depends on your use-case. In some cases, it can cause performance issues. Hence, this is why this is "uncertain" at the moment.

Another option would be to cache the execution plan instead of the query + result set. This may or may not be useful depending on how efficient ArangoDB is at creating the execution plan.

**Comment by jsteemann** [comment]
I just stumbled upon this issue and found it can be closed now.
There is a query result cache available starting with ArangoDB 2.7.0.
