### ISSUE TITLE
Confused by activefailover & cluster mode

### ISSUE THREAD

**Issue by dsonet** [arangodb/arangodb#5179]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:

- [x] 3.3

Mode:
- [x] Cluster

Storage-Engine:
- [x] mmfiles

It the document about cluster, https://docs.arangodb.com/devel/Manual/Deployment/ArangoDBStarter.html
It also mentioned activefailover mode, what's the difference between them? Also how cluster distribute data? Like we have 3 db servers, do they sync to each other so that any node failure is okay even only one node at last?
Thank you very much.

**Comment by dothebart** [comment]
Hi, 
https://docs.arangodb.com/devel/Manual/Scalability/ActiveFailover/  describes the first, 
https://docs.arangodb.com/devel/Manual/Scalability/Cluster/ describes the cluster. 
We're still missing some x-references here - the documentation is WIP - good you ask.

**Comment by dsonet** [comment]
Thanks for the reply.
I read the docs says setup activefailover needs 3 nodes, but I see the cluster also involved 3 nodes as minimal. But when to choose  activefailover mode or cluster?

**Comment by OmarAyo** [comment]
Hi @dsonet dsonet,

Let me explain you some point of ActiveFailover and Cluster:

_Active Failover_

In this deployment mode there is **asynchronous replication** between two "nodes" one is called "leader" and one is called "follower"
The advantage of this deployment mode is the automatic failover. If the leader goes down (for any reason) the follower will take leadership automatically. This can be important to guarantee a higher level of availability to your application/service. 

_Cluster_

This is a distributed setup where your database can be sharded among several nodes. The cluster can survive to one or more nodes down, depending on very specific rules
You can read and write concurrently on several nodes (of a certain type, specifically the "Coordinators"). This is similar to what other technology call master-master
The minimal number of machines needed is 3. At a very minimum you will need to run 3 Agents, one per machine, 2 DBServers and 2 Coordinators
The replication among the DBServers is **synchronous**
Some of the most important concepts to be understood in the cluster are: "number of shards" (per collection) and "replication factor" (per collection)


Please note that for both deployments you need to start at least 3 nodes;

**ActiveFailover**
- _node 1_: Agent
- _node 2_: Leader
- _node 3_: Follower 


**Cluster**:
- _node 1_: 1 Agent 1 DBserver and 1 Coordinator 
- _node 2_: 1 Agent 1 DBserver and 1 Coordinator 
- _node 3_: 1 Agent 1 DBserver and 1 Coordinator 

_note that you can add as many nodes as you want in relation to your workload and your usage/needs_ 

_But when to choose Activefailover or Cluster?_
This is up to you, is related to your needs, workload... 

In addition, to help you decide on which one to use you could find the following information relevant:

Regarding ActiveFailover: 
- You cannot use this deployment mode to scale your reads. The "follower" in fact is a passive stand-by follower. You can read and write only from one instance at a time, the leader.
- Only 1 follower is currently supported  
- Limitation of the size of the database, your database has to fit the disk of a (single) machine
- Note that you can attach to an Active Failover setup a (replica) slave. This slave has to be started (and in case synchronized) manually. This workaround allows you to have an automatic failover mechanism and at the same time replica slave from where you can read

Regarding the Cluster:
- Application developed for a single ArangoDB instance may require some tuning, especially in terms of AQL optimization, if you want to use them with a cluster
- Cluster is a more complex deployment mode as several nodes are involved. From a practical point of view, however, deploying a cluster can be quite easy, and no manual synchronization is needed
- The database size can be greater than the size of the disk of a single machine.

Hope this helps you to choose the best deployment for your needs

Please let me know if we could provide more help


Best,

**Comment by OmarAyo** [comment]
Hi @dsonet 

I am going ahead and close this ticket.

Please note that ticket can be reopened at any time

Best,

**Comment by bthj** [comment]
@OmarAyo in the 3 node example above; 
- having the ActiveFailover setup, if node 1 (Agent) and node 2 (Leader) go down, will node 3 be able to serve requests?
- having the Cluster setup, if node 1  and node 2 go down, will node 3 be able to serve requests?
