### ISSUE TITLE
segmentation fault during arangosearch view properties update

### ISSUE THREAD

**Issue by richardhundt** [arangodb/arangodb#5186]
Thought the problem was solved, but was masked by `GLIBCXX_FORCE_NEW` not being set when I tested.

## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [ ] 3.3
- [x] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [x] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [x] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

The issue can be reproduced using this dataset:
https://gist.github.com/richardhundt/f8293d1f1ec3c7c5cb7219c5ae1b5390

These are the steps to reproduce:
1) `export GLIBCXX_FORCE_NEW=1`
2) start the server `./bin/arangod -c ./etc/arangodb3/arangod.conf --console`
3) load the test data `./bin/arangoimport --configuration ./etc/arangodb3/arangoimport.conf --server.database _system --server.username root --collection 'dbp_organisations' --create-collection true gistfile1.txt`
4) `./bin/arangosh --server.database _system --server.username root --configuration etc/arangodb3/arangosh.conf`
5) create a view `v0 = db._createView("my_view", "arangosearch", {});`
6) update the view properties `v0.properties({links: {"dbp_organisations": {includeAllFields: true}}}, true);`

The following problem occurs:
the server dies with a segmentation fault

Instead I would be expecting: 
anything else

Additional info:

Not sure how useful this is, but if I unset `GLIBCXX_FORCE_NEW` before starting the server, the view property update succeeds, even on large (2.5mil) data set, however the server then (usually, but not always) fails to start up again following a clean shutdown:

```
2018-04-23T19:57:12Z [12091] ERROR duplicate entry for view name 'my_view'
2018-04-23T19:57:12Z [12091] ERROR view id 2195 has same name as already added view 2195
2018-04-23T19:57:12Z [12091] ERROR error while opening database views: duplicate name
2018-04-23T19:57:12Z [12091] FATAL cannot start database: duplicate name
```

**Comment by gnusi** [comment]
@richardhundt thank you! will start investigation... but it looks unrelated to the previous

**Comment by gnusi** [comment]
@richardhundt After some investigation I believe we have two unrelated issues there:
1) memory allocation problem without `GLIBCXX_FORCE_NEW`
2) invalid view handling on startup

I'll fix latter in `devel` soon, but for the former we planned to completely rewrite insertion logic so it will take some time, but you know workaround :-)

**Comment by gnusi** [comment]
@richardhundt I've just pushed fix for invalid views handling during startup (duplicate name problem) into `devel`. Memory allocation problem is still there and we keep working on that.

**Comment by gnusi** [comment]
@richardhundt we've just pushed the fix for another part of the issue. Please checkout the recent `devel` when you have a minute. Looking forward for your feedback!

**Comment by dothebart** [comment]
addressed by https://github.com/arangodb/arangodb/pull/5339

**Comment by vinaypyati** [comment]
Hi @richardhundt,

version 3.4.0-RC1 has been released, which contains the fix for this issue. Please check it out. 
I will be closing this issue for now. Please comment, if you the issue still persists, and we will reopen it.

Thanks again for reporting this issue.

Best,
