### ISSUE TITLE
broken link in cookbook - ArangoDB Foxx queue-it

### ISSUE THREAD

**Issue by oprogramador** [arangodb/arangodb#5214]
On the bottom of https://github.com/arangodb/arangodb/blob/devel/Documentation/Books/Cookbook/UseCases/CrawlingGithubPromises.md there is a link `ArangoDB Foxx queue-it` redirecting to https://github.com/arangodb/queue-it which gives 404 error.

**Comment by Simran-B** [comment]
@pluma Is it available somewhere else, or should the link be removed?

**Comment by maxkernbach** [comment]
The deprecated link is removed in the latest documentation
