### ISSUE TITLE
Is there a way can config editor to support @arangodb module?

### ISSUE THREAD

**Issue by dsonet** [arangodb/arangodb#5221]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.3

### Foxx
For now when we write foxx, use the require('@arangodb') but can not get any IntelliSense provided by many nowadays editors like when we use other npm modules. I have to check the manual again & again to see what methods are this module provide. Wished there is a better experience to write foxx services.

**Comment by pluma** [comment]
If your editor supports TypeScript, you can add `@types/arangodb` to your node modules, which defines TypeScript interfaces for the most common ArangoDB modules when working with Foxx.

**Comment by pluma** [comment]
I'm closing this as answered for now since it's been over two years since the question was asked but feel free to reopen this issue if you need additional information or would like to expand your question.
