### ISSUE TITLE
ArangoDB start fails after initial install

### ISSUE THREAD

**Issue by Terchestor** [arangodb/arangodb#5229]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [x ] 3.3
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ x] other: Arch Linux (Manjaro)
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

The issue can be reproduced using this dataset:

Please provide a way to create the dataset to run the above query on; either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements. If it can be reproduced with one of the ArangoDB example datasets, it's a plus.

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [ ] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click to ...
...

The following problem occurs: [Screenshot?] 
Instead I would be expecting: 

### this is an installation-related issue:
Describe which steps you carried out, what you expected to happen and what actually happened.

After install I've followed the post-install steps:

- sudo systemctl daemon-reload
- sudo systemctl enable arangodb3.service
- sudo systemctl start  arangodb3.service

getting:

Job for arangodb3.service failed because the control process exited with error code.
See "systemctl status arangodb3.service" and "journalctl -xe" for details.
daniel@daniel-pc ~> systemctl status arangodb3.service
● arangodb3.service - ArangoDB
   Loaded: loaded (/usr/lib/systemd/system/arangodb3.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2018-04-30 11:12:48 CEST; 3min 26s ago
  Process: 2328 ExecStartPre=/usr/bin/arangod --pid-file /run/arangodb3/arangod.pid --server.rest-server false --database.auto-upgrade true (code=exit>

avril 30 11:12:48 daniel-pc systemd[1]: arangodb3.service: Service hold-off time over, scheduling restart.
avril 30 11:12:48 daniel-pc systemd[1]: arangodb3.service: Scheduled restart job, restart counter is at 5.
avril 30 11:12:48 daniel-pc systemd[1]: Stopped ArangoDB.
avril 30 11:12:48 daniel-pc systemd[1]: arangodb3.service: Start request repeated too quickly.
avril 30 11:12:48 daniel-pc systemd[1]: arangodb3.service: Failed with result 'exit-code'.
avril 30 11:12:48 daniel-pc systemd[1]: Failed to start ArangoDB.

**Comment by maxkernbach** [comment]
Hi @Terchestor,

is this your first time deploying ArangoDB on Arch Linux or do you face this problem using the latest version? Instructions on how to install ArangoDB on Arch Linux can be found in the [download section](https://www.arangodb.com/download-major/arch-linux/).

**Comment by Terchestor** [comment]
Hi Max,
Yes, this is the first time. I used github latest clone. No problem to compile it. 
Thanks

**Comment by maxkernbach** [comment]
Could you please create an issue in the https://github.com/sleepycat/arangodb_arch.git repository? The Arch Linux package is provided by the community user Mike Williamson’s (@sleepycat).

**Comment by Terchestor** [comment]
OK Max
Thanks

**Comment by Terchestor** [comment]
SOLVED: I had first to set a RestartSec=2 in arangodb3.service [Service];
then chown arangodb:arangodb /var/lib/arangodb3.

**Comment by DanteSingleton** [comment]
Steps I had to take to fix on arch using AUR
```
sudo chown -R arangodb:arangodb /var/lib/arangodb3
sudo chown -R arangodb:arangodb /var/log/arangodb3
sudo chown -R arangodb:arangodb /var/lib/arangodb3-apps
```
