### ISSUE TITLE
Empty result if FULLTEXT() is used together with LIMIT offset

### ISSUE THREAD

**Issue by Simran-B** [arangodb/arangodb#5252]
_Discovered by Piwaï in Slack_

## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.3.7

Mode:
- [x] Single-Server

Storage-Engine:
- [x] mmfiles

On this operating system:
- [x] Windows, version: 10

### this is an AQL-related issue:

I'm issuing AQL via:
- [x] web interface with this browser: Chrome

The AQL query in question is:

```js
FOR doc IN FULLTEXT(fulltext_skip, "contact.email", "prefix:jo")
    //SORT doc
    LIMIT 10,5
    COLLECT WITH COUNT INTO count
    RETURN count
```

### The issue can be reproduced using this dataset:

https://raw.githubusercontent.com/arangodb/example-datasets/master/RandomUsers/names_1000.json

### These are the steps to reproduce:

1. Import example dataset, `arangoimp --file names_1000.json --collection fulltext_skip --create-collection true`
2. Create full-text on `contact.email`
3. Run above query with result: `0`
4. Uncomment the SORT operation and re-run with result: `5`
5. Remove SORT and LIMIT and re-run with result: `18`

### Instead I would be expecting: 

The original query should return 5 results.

There seems to be a problem with skipping documents coming from the full-text index. FULLTEXT() has a limit parameter, but not for skipping. LIMIT works to (post-)cap the result count, but as soon as an offset is given, no result remains - unless a SORT is involved (there might be more ways to circumvent the bad behavior).

**Comment by dbcbos** [comment]
I also am experiencing this problem, I am using version 3.3.8.
Besides SORT that helps a FILTER helps to. So I use that as a workaround by using a filter checking if _key is not empty (which never will be).

**Comment by jsteemann** [comment]
Fixed by the above commits.

**Comment by maxkernbach** [comment]
ArangoDB version 3.3.10, which includes a fix for this issue, has been released today.
