### ISSUE TITLE
In memory version of database for faster access

### ISSUE THREAD

**Issue by dilipvamsi** [arangodb/arangodb#5264]
Hi,
Is there a in memory implementation of database for both document and graph.
If yes please direct me to that.

**Comment by Simran-B** [comment]
ArangoDB is mostly-memory if you choose MMFiles storage engine. The data of the collections that you want to work with plus their indexes (and some more to store query results etc.) should fit into main memory to work efficiently. The data gets synced to disk, but not necessarily immediately. Indexes are only held memory and need to be recreated in memory on server restart.

If you want to avoid syncing to disk and take the risk of losing your data in case of a server shutdown or crash, there is an option on per-collection basis to make it volatile (`isVolatile: true`):

https://docs.arangodb.com/3.3/HTTP/Collection/Creating.html

This can be set on document as well as edge collections. The data you store in them will disappear if you restart the server, or if the collection gets unloaded. The collection itself will remain and doesn't have to be recreated (index definitions etc. are persisted).

**Comment by Simran-B** [comment]
In Arangosh, you can use it like:

```js
var collName = "myVolatileVertices"
var edgeCollName = "myVolatileEdges"

var coll = db._create(collName, { isVolatile: true })
var A = coll.save({ _key: "A"})
var B = coll.save({ _key: "B"})

var edgeColl = db._createEdgeCollection(edgeCollName, { isVolatile: true })
edgeColl.save({ _from: A._id, _to: B._id })

db._query(aql`FOR v IN 1..1 OUTBOUND ${A._id} ${edgeColl} RETURN v`)

//coll.unload() // does not flush immediately
db._connection.PUT(`/_api/collection/${collName}/unload?flush=true`, '') // this does

var internal = require("internal")
internal.sleep(1) // wait a bit to not interrupt unloading
coll.count()
```

**Comment by dilipvamsi** [comment]
Thanks @Simran-B 
If I want to use volatile collection as a cache does the database storage engine should only be in MMFiles for the complete database or the storage engine can be configured for each collection in the database.

**Comment by Simran-B** [comment]
It has to be MMFiles for the entire instance / cluster

**Comment by dilipvamsi** [comment]
Hi @vinaypyati ,
This clarifies my question.
Thanks for the follow-up.
