### ISSUE TITLE
Filtering in web interface with show "All results" not working as expected

### ISSUE THREAD

**Issue by vizo** [arangodb/arangodb#5270]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [X] 3.3
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [X] Single-Server

Storage-Engine:
- [ ] mmfiles
- [X] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [X] Linux 
  - [ ] Debian .deb
  - [X] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### This is a web interface-related issue:
I'm using the web interface with this browser: Chrome    running on this OS: Linux
- [X] authentication is enabled?
- [ ] using the cluster?
- [ ] _system database?

These are the steps to reproduce:
1) Open the browser on http://127.0.0.1:8529
2) Open any collection with multiple rows
3) Top right select to show "All results"
3) Click on filter and try to filter by some key.

The following problem occurs:
Even if there is filer set, all documents from collection are listed. They are not filtered.
As soon as you select on top right anything else than show "All results", eg: "5000 results", it works as expected.
 
Instead I would be expecting: 
Filtered list of documents..

**Comment by Simran-B** [comment]
Something seems broken for sure. "All results" doesn't filter, but if you switch to e.g. "10 results" which limits the amount of documents with filters applied, then back to "All results", the filtered list remains instead of filters being ignored.

**Comment by hkernbach** [comment]
This should also be fixed. PRs available here:
https://github.com/arangodb/arangodb/pull/6815
https://github.com/arangodb/arangodb/pull/6816
https://github.com/arangodb/arangodb/pull/6817

Will be included in the next 3.3, 3.4 and 3.4+ versions.

**Comment by sleto-it** [comment]
Hi,

Thanks again for opening this issue

Versions 3.3.19 has been released and it includes a fix for this problem (note that there was no public 3.3.18 - the next release after 3.3.17 is 3.3.19)

I am closing this ticket now. Please feel free to comment if the issue persists

Many thanks,
