### ISSUE TITLE
Environment variables define

### ISSUE THREAD

**Issue by karankapur999** [arangodb/arangodb#5279]
How can we setup Environment  variables in foxx service apis? My use case is to create env variables and read in foxx service so that we dont have to change environment specific resources ?

## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:

- [x] 3.3
- [ ] self-compiled devel branch

Mode:
- [x] Cluster
- [x] Single-Server

**Comment by karankapur999** [comment]
@dothebart thanks for the reply , I am using ubuntu server where can we set systems evrironment for foxx services?

**Comment by dothebart** [comment]
Hi, you would do so in [the systemd unit file](https://coreos.com/os/docs/latest/using-environment-variables-in-systemd-units.html) or the init script.

**Comment by karankapur999** [comment]
I have tried following steps but its not working for me -:

1.) sudo systemctl edit arangodb3.service 

2.) Now updated arangodb3.service file with following values


[Unit]
Description=arango

[Service]
NODE_ENV="gg"


3.) sudo service arangodb restart

console.log to  process.env stills reads 

{ "PATH" : "/bin:/usr/bin:/sbin:/usr/sbin", "LANG" : "en_US.UTF-8", "_SYSTEMCTL_SKIP_REDIRECT" : "true", "PWD" : "/", "GLIBCXX_FORCE_NEW" : "1", "ICU_DATA" : "///usr/share/arangodb3/" }

**Comment by dothebart** [comment]
btw, its better style not to delete comments, but rather edit them how you overcame them so others have a resource to learn from.

**Comment by karankapur999** [comment]
ok sure , Actually above steps solved my problem , i was missing **sudo systemctl daemon-reload**

command

So steps are -:
 1.) sudo systemctl edit arangodb3.service - Write your Env variables
 2.) sudo systemctl daemon-reload
 3.)  sudo service arangodb restart
