### ISSUE TITLE
Script results are not escaped for HTML in the web interface

### ISSUE THREAD

**Issue by zocky** [arangodb/arangodb#5311]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:

- [x ] 3.3

When the UI is used to run a foxx service script which returns a string which contains html/xml tags, the results are displayed as JSON inside a `<pre>` tag, but they are not HTML-escaped.

### Steps to reproduce:
(1) Create this script in a foxx service:
```js
module.exports = `foo <b>bar</b>`;
```
(2) Go to the service settings, choose the script from the dropdown and run it.

### Produced results:

The UI displays `"foo `**`bar`**`"`

### Expected results:

The UI should display `"foo <b>bar</b>"`

**Comment by hkernbach** [comment]
Sorry for the late reply. Applied bugfix PR's for all supported versions.

**Comment by pluma** [comment]
Closing this as per above comment.
