### ISSUE TITLE
COLLECT query runs slower when using an index

### ISSUE THREAD

**Issue by brendanwheble** [arangodb/arangodb#5320]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [x] 3.3
- [ ] self-compiled devel branch

Mode:
- [x] Cluster
- [x] Single-Server

Storage-Engine:
- [x] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[ ] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser:     running on this OS: MacOS
- [ ] arangosh
- [ ] this Driver:

I've run `db._explain("<my aql query>")` and it didn't shed more light on this.
The AQL query in question is:

FOR hit in tracker
COLLECT d=hit.eventid WITH COUNT into counter
RETURN {ev:d,count:counter}

The issue can be reproduced using this arangosh script:
https://gist.github.com/brendanwheble/97a2c7cc129a59878b979460eeeb129f

The collection contains 995000 documents.
Please note: This script creates the documents but it doesn't reflect the random ordering of the actual collection. It does however still exhibit the issue. The actual dataset is 2.14gb but I could zip and attach it somewhere if necessary.

###The Issue
If I run the AQL above without an index on "eventid" I receive the following plan:

```
Query string:
 FOR hit in tracker
 COLLECT d=hit.eventid WITH COUNT into counter
 RETURN {ev:d,count:counter}

Execution plan:
 Id   NodeType                    Est.   Comment
  1   SingletonNode                  1   * ROOT
  2   EnumerateCollectionNode   995171     - FOR hit IN tracker   /* full collection scan */
  3   CalculationNode           995171       - LET #3 = hit.`eventid`   /* attribute expression */   /* collections used: hit : tracker */
  4   CollectNode               796136       - COLLECT d = #3 WITH COUNT INTO counter   /* hash */
  7   SortNode                  796136       - SORT d ASC
  5   CalculationNode           796136       - LET #5 = { "ev" : d, "count" : counter }   /* simple expression */
  6   ReturnNode                796136       - RETURN #5

Indexes used:
 none

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-calculations-down
```
The execution times for three runs are:
589ms, 582ms, 570ms

If I create a persistent index on "eventid" and repeat I receive this plan:

```
Query string:
 FOR hit in tracker
 COLLECT d=hit.eventid WITH COUNT into counter
 RETURN {ev:d,count:counter}

Execution plan:
 Id   NodeType            Est.   Comment
  1   SingletonNode          1   * ROOT
  8   IndexNode         995171     - FOR hit IN tracker   /* persistent index scan */
  3   CalculationNode   995171       - LET #3 = hit.`eventid`   /* attribute expression */   /* collections used: hit : tracker */
  4   CollectNode       796136       - COLLECT d = #3 WITH COUNT INTO counter   /* sorted */
  5   CalculationNode   796136       - LET #5 = { "ev" : d, "count" : counter }   /* simple expression */
  6   ReturnNode        796136       - RETURN #5

Indexes used:
 By   Type         Collection   Unique   Sparse   Selectivity   Fields          Ranges
  8   persistent   tracker      false    false            n/a   [ `eventid` ]   *

Optimization rules applied:
 Id   RuleName
  1   use-indexes
  2   use-index-for-sort
```
The execution times for three runs are:
2.837s, 2.780s, 2.762s

If I change the AQL to include a filter, with the same index, the execution time increases to:
3.310s, 3.405s, 3.486s

```
FOR hit in tracker
FILTER hit.eventid != null
COLLECT d=hit.eventid WITH COUNT into counter
RETURN {ev:d,count:counter}
```
```
Query string:
 FOR hit in tracker
 FILTER hit.eventid != null
 COLLECT d=hit.eventid WITH COUNT into counter
 RETURN {ev:d,count:counter}

Execution plan:
 Id   NodeType            Est.   Comment
  1   SingletonNode          1   * ROOT
 10   IndexNode         995171     - FOR hit IN tracker   /* persistent index scan */
  3   CalculationNode   995171       - LET #3 = (hit.`eventid` != null)   /* simple expression */   /* collections used: hit : tracker */
  4   FilterNode        995171       - FILTER #3
  5   CalculationNode   995171       - LET #5 = hit.`eventid`   /* attribute expression */   /* collections used: hit : tracker */
  6   CollectNode       796136       - COLLECT d = #5 WITH COUNT INTO counter   /* sorted */
  7   CalculationNode   796136       - LET #7 = { "ev" : d, "count" : counter }   /* simple expression */
  8   ReturnNode        796136       - RETURN #7

Indexes used:
 By   Type         Collection   Unique   Sparse   Selectivity   Fields          Ranges
 10   persistent   tracker      false    false            n/a   [ `eventid` ]   *

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   move-calculations-up-2
  4   move-filters-up-2
  5   use-indexes
  6   use-index-for-sort
```

**Comment by jsteemann** [comment]
I was able to reproduce the issue.

When there is no index available, the query executor will simply iterate over all the documents in the collection. This iteration has the documents readily available, but the order in which the documents are retrieved is non-deterministic. That means the COLLECT operation either needs to sort the documents by the COLLECT attribute beforehand and use the "sorted" variant, or not sort them and use the "hash" variant. It seems that in your case the optimizer has chosen the "hash" variant of COLLECT.

After adding the index on the COLLECT attribute, the optimizer detects that when it uses the index for iteration, it can eliminate the sort operation in front of the COLLECT, and can use the "sorted" COLLECT variant. This has an advantage over the "hash" variant in that it only needs to keep the current aggregation group in memory, in contrast to keeping all groups in memory. So all other things equal, the optimizer will prefer the "sorted" variant of all.

However, it does not take into account here that it needs to perform extra work to retrieve the actual documents after reading the values from the index iterator. For each index value found, it will read the according document too, so it's two operations here per document instead of just one for the non-index variant.

There are two ways to attack this:
* there is a pending patch for 3.3 that provides a syntax for the end user to override the COLLECT method uses. The PR for this is https://github.com/arangodb/arangodb/pull/5140. A description of the syntax can be found here: https://github.com/arangodb/arangodb/pull/5140/files#diff-d3bb3391c79904494c60ee2ac2f33070R92. Using this syntax, any non-optimal COLLECT method chosen by the optimizer can be overriden on a per-query level.

* there is yet another pending patch (for devel at the moment) that will speed up batch index iterations for the persistent index: https://github.com/arangodb/arangodb/pull/5337. The other index types have been addressed by earlier patches already. This patch will speed up the case in which the optimizer uses the index and the "sorted" COLLECT variant.

None of the two patches can be used in a released version yet, but I am sure the first mentioned patch will be part of a release in the foreseeable future (next 3.3 bugfix release or the one after that). 
The latter patch may also be backported to a 3.3 release if there is need.

**Comment by jsteemann** [comment]
3.3 backport for second patch: https://github.com/arangodb/arangodb/pull/5338

**Comment by jsteemann** [comment]
@brendanwheble : This should have been improved in 3.3.9. 
Please check with 3.3.9 when it is released and you have time.
Thanks!

**Comment by brendanwheble** [comment]
Great news. I'll upgrade when it's released

**Comment by jsteemann** [comment]
3.3.9 has been released now.

**Comment by brendanwheble** [comment]
Thanks. Any ideas how long this takes to filter down to homebrew?

**Comment by dothebart** [comment]
Sadly we have some problems here: https://github.com/Homebrew/homebrew-core/pull/28122#issuecomment-390904563

**Comment by brendanwheble** [comment]
```
Query string:
 FOR hit in tracker
  COLLECT d=hit.eventid WITH COUNT into counter
  RETURN {ev:d,count:counter}

Execution plan:
 Id   NodeType                    Est.   Comment
  1   SingletonNode                  1   * ROOT
  2   EnumerateCollectionNode   995171     - FOR hit IN tracker   /* full collection scan */
  3   CalculationNode           995171       - LET #3 = hit.`eventid`   /* attribute expression */   /* collections used: hit : tracker */
  4   CollectNode               796136       - COLLECT d = #3 WITH COUNT INTO counter   /* hash */
  7   SortNode                  796136       - SORT d ASC
  5   CalculationNode           796136       - LET #5 = { "ev" : d, "count" : counter }   /* simple expression */
  6   ReturnNode                796136       - RETURN #5

Indexes used:
 none

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-calculations-down
```
The execution times for three runs are:
865ms, 954ms, 933ms

If I create a persistent index on "eventid" and repeat I receive this plan:

```
Query string:
 FOR hit in tracker
  COLLECT d=hit.eventid WITH COUNT into counter
  RETURN {ev:d,count:counter}

Execution plan:
 Id   NodeType            Est.   Comment
  1   SingletonNode          1   * ROOT
  8   IndexNode         995171     - FOR hit IN tracker   /* persistent index scan */
  3   CalculationNode   995171       - LET #3 = hit.`eventid`   /* attribute expression */   /* collections used: hit : tracker */
  4   CollectNode       796136       - COLLECT d = #3 WITH COUNT INTO counter   /* sorted */
  5   CalculationNode   796136       - LET #5 = { "ev" : d, "count" : counter }   /* simple expression */
  6   ReturnNode        796136       - RETURN #5

Indexes used:
 By   Type         Collection   Unique   Sparse   Selectivity   Fields          Ranges
  8   persistent   tracker      false    false            n/a   [ `eventid` ]   *

Optimization rules applied:
 Id   RuleName
  1   use-indexes
  2   use-index-for-sort
```
The execution times for three runs are:
3.274s, 3.316s, 3.287s

If I change the AQL to include a filter, with the same index, the execution time increases to:
3.676s, 3.652s, 3.699s

```
FOR hit in tracker
FILTER hit.eventid != null
COLLECT d=hit.eventid WITH COUNT into counter
RETURN {ev:d,count:counter}
```
```
Query string:
 FOR hit in tracker
 FILTER hit.eventid != null
  COLLECT d=hit.eventid WITH COUNT into counter
  RETURN {ev:d,count:counter}

Execution plan:
 Id   NodeType            Est.   Comment
  1   SingletonNode          1   * ROOT
 10   IndexNode         995171     - FOR hit IN tracker   /* persistent index scan */
  3   CalculationNode   995171       - LET #3 = (hit.`eventid` != null)   /* simple expression */   /* collections used: hit : tracker */
  4   FilterNode        995171       - FILTER #3
  5   CalculationNode   995171       - LET #5 = hit.`eventid`   /* attribute expression */   /* collections used: hit : tracker */
  6   CollectNode       796136       - COLLECT d = #5 WITH COUNT INTO counter   /* sorted */
  7   CalculationNode   796136       - LET #7 = { "ev" : d, "count" : counter }   /* simple expression */
  8   ReturnNode        796136       - RETURN #7

Indexes used:
 By   Type         Collection   Unique   Sparse   Selectivity   Fields          Ranges
 10   persistent   tracker      false    false            n/a   [ `eventid` ]   *

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   move-calculations-up-2
  4   move-filters-up-2
  5   use-indexes
  6   use-index-for-sort
```

**Comment by jsteemann** [comment]
Can you try setting the COLLECT method to `hash` in the query that uses the persistent index and whether that improves the execution time?
`COLLECT ... OPTIONS { method: "hash" }`
Apart from that, moving from a persistent index to other type of index should may make it faster.

**Comment by brendanwheble** [comment]
I've amended my AQL and it now ignores the eventid index. The performance is now on a par with the non-index version. When a filter is applied I also see an improvement from 3.2s to 1.2s.
Excellent! One last question, in a future release will the use of the OPTIONS be necessary for simple use cases like mine? Running COLLECT and returning values that are contained within the index seems like a reasonable thing to do. Applying an option to ignore the index seems counter-intuitive, but I appreciate the time spent to solve my immediate problem.

```
Query string:
 FOR hit in tracker
  COLLECT d=hit.eventid WITH COUNT into counter OPTIONS { method: "hash" }
  RETURN {ev:d,count:counter}

Execution plan:
 Id   NodeType                    Est.   Comment
  1   SingletonNode                  1   * ROOT
  2   EnumerateCollectionNode   995171     - FOR hit IN tracker   /* full collection scan */
  3   CalculationNode           995171       - LET #3 = hit.`eventid`   /* attribute expression */   /* collections used: hit : tracker */
  4   CollectNode               796136       - COLLECT d = #3 WITH COUNT INTO counter   /* hash */
  7   SortNode                  796136       - SORT d ASC
  5   CalculationNode           796136       - LET #5 = { "ev" : d, "count" : counter }   /* simple expression */
  6   ReturnNode                796136       - RETURN #5

Indexes used:
 none

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-calculations-down
```

**Comment by brendanwheble** [comment]
All of the indexes are faster than persistent it seems. I'll switch to a Skiplist but I was concerned about future problems as it's likely that databases will be switched in and out of memory quite a lot with our usage patterns.

**Persistent**
3.302s
866ms (with COLLECT OPTION)

**Skiplist**
725ms

**No Index**
874ms

**Hash**
890ms

**Comment by jsteemann** [comment]
The persistent index actually has to accomplish more work for this query than the other indexes.
It stores the index value (same as other indexes) and the primary key of the corresponding document. For each document found, it needs to do a primary index lookup, which the other indexes can avoid.
So it is because of this indirection that the persistent index is slower that the others.
An idea for improving the performance of the persistent index is to make it perform its primary index value lookups in batches too. That may speed it up, but it will still have some disadvantage when compare to the other in-memory indexes.

**Comment by brendanwheble** [comment]
So, under what conditions does a persistent index become the best choice?

**Comment by jsteemann** [comment]
The main advantage of the persistent index compared to the other in-memory indexes is that it does not need to be rebuilt in memory when the collection is loaded.
The other in-memory indexes of the MMFiles engine will need to get rebuilt when the collection is first accessed after a server start. This may take considerable time, and the persistent index just saves this.

**Comment by maxkernbach** [comment]
Hi @brendanwheble,

do you have any further questions or can we consider this issue as solved?

**Comment by brendanwheble** [comment]
No, thanks for your help
