### ISSUE TITLE
ArangoDB instance crashes due to too low configured sysctl variable vm.max_map_count 

### ISSUE THREAD

**Issue by fdsg-tk** [arangodb/arangodb#5325]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [X] 3.3 [3.3.7]
- [ ] self-compiled devel branch

Mode:
- [X] Cluster
- [ ] Single-Server

Storage-Engine:
- [ ] mmfiles
- [X] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [X] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [X] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

The following problem occurs: [Screenshot?] 
"dbserver" instance of an ArangoDB Cluster crashes periodically.
Errors in logfile before crash:
>>
ERROR {memory} process is near the maximum number of memory mappings. current: 127997, maximum: 128000. it may be sensible to increase the maximum number of mappings per process
<<

Instead I would be expecting: 
sysctl variable vm.max_map_count has been setup according to your documention:
https://docs.arangodb.com/3.3/Manual/Administration/Configuration/OperatingSystem.html
vm.max_map_count= 8 x _number_of_cpu_cores x 8000
It seems as if this value was too low.
We have now increased vm.max_map_count.

I also saw, that you have fixed a memory leak in 3.2.7 (https://github.com/arangodb/arangodb/issues/3342) a few months ago. Please check if the memory leak is really fixed.
We updated to 3.3.7 (3.3!) only a few weeks ago and I have not seen this kind of issue before on older versions.

**Comment by jsteemann** [comment]
The memory leak you are referring to in https://github.com/arangodb/arangodb/issues/3342 refers to ArangoDB version 3.2.7, not 3.3.7. The fix has been made about seven months ago, and is incorporated in all 3.3 versions (this includes 3.3.7).

The problem with the max_map_count limit getting hit is a general problem, and it is highly workload-dependent. For certain workloads, the recommended size we have in the documentation may be too low. I have pushed a bugfix for the documentation that should make this a bit more clear:
https://github.com/arangodb/arangodb/commit/72420495c14b1366a277a7639f0e1f700d1ea2ac

**Comment by maxkernbach** [comment]
Hi @fdsg-tk,

did you face further problems after increasing vm.max_map_count or can we consider this issue as solved? As stated in the previous comment the recommended size in the documentation is updated by https://github.com/arangodb/arangodb/commit/72420495c14b1366a277a7639f0e1f700d1ea2ac.

**Comment by fdsg-tk** [comment]
Hi,
we did not had any instance crashes over the past 3 days.
Feel free to close this issue, since you already updated the documentation.
I will let you know if the issue happens again with a huge number of vm.max_map_count

**Comment by maxkernbach** [comment]
Thanks for your feedback!
