### ISSUE TITLE
404 Not found for /_api/job/ in UI console when load balancing

### ISSUE THREAD

**Issue by ohardy** [arangodb/arangodb#5331]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.3

Mode:
- [x] Cluster

Storage-Engine:
- [x] rocksdb

On this operating system:
- [x] docker - official docker library

Hi,

It seems like I have to face a bug.

In fact, we have six servers, three of them have each one one agent, the three others with DB and coordinators.
Every DBs are master.

Moreover we have a load balancer which is configured to spread the load on coordinators at every request.

Regularly, on the web interface, I face inconsistent errors.
For example, the interface displays that I have 10 000 documents but in reality only one is displayed and the pagination remains.

Furthermore, on Chrome console, a 404 error not found appear :

`http://<url>/_db/testdb/_api/job/152605601217410`
```
{"error":true,"errorMessage":"not found","code":404,"errorNum":404}
```

I notice that when I have changed the mode of the load balancer in order to use always the same coordinator for each client, this error disappeared.

On the documentation, it is noted that the coordinator is stateless, really ?

I think the problem appear with JOB API used by the UI.

Thanks in advance

**Comment by jsteemann** [comment]
@ohardy : there are some APIs which build local in-memory state on the server they are initially called on.
For example, if a job is dispatched to one server, that job is only accessible on the same server. That is the /_api/job API you mentioned. 
The same will happen when trying to create a cursor on one of the servers and then sending follow-up requests to extract documents from that cursor. If the follow-up requests are directed to a different server, the result will be HTTP 404 (cursor not found).

To work around the problem, can you set up IP stickyness for the load balancing?

**Comment by dsonet** [comment]
Ya I've met this earlier too and finally figured it out the reason.

**Comment by OmarAyo** [comment]
Hi @ohardy 

Just sending a quick followup - How things are going with this ticket?
Were you able to try out jstemmann's workaround? 

Best,

**Comment by OmarAyo** [comment]
Hi @ohardy 

I am going to close it, please note that ticket can be reopened at any time by adding a message

Best

**Comment by arorlando** [comment]
Hi,
I'm having exactly the same reported issue.
I deployed arango 3.3.19 in Kubernetes using the provided arango kube operator.
My cluster has 3 coordinators, 3 DB servers and RF=1.
Could you please suggest me a workaround in order to run queries directly through arango UI. Currently I'm always having 404.

Thanks,
Armando.
