### ISSUE TITLE
Agent filled the disk with log files, server stopped listening to ports, I needed to rescue from backup

### ISSUE THREAD

**Issue by ile** [arangodb/arangodb#5334]
(Sorry for the colorful title, but I don't think it's far off.)

I'm using the tArangoDB version:
- [x] 3.3.8

Mode:
- [x] Automatic failover. I'm using ArangoDB in automatic failover mode with 3 nodes (3 agents, 3 db servers).

Storage-Engine:
- [x] rocksdb

On this operating system:
- [x] Linux 
  - [x] Ubuntu .deb

A lot of things happened. Here's a rough timeline. 

1, In node 1 the agent filled the disk in `agent/engine-rocksdb/journals/archive` folder so that disk was 100 % full. In a matter of seconds/minutes the disk got full even though there wasn't much traffic on the site at all. If I remember correctly, arangodb crashed at this point. https://arangodb-community.slack.com/archives/C07NV9NAH/p1525969921000304
```
/var/lib/docker-data/arango/agent/engine-rocksdb/journals# du -h
33G    ./archive
```
2. I deleted those files in `/var/lib/docker-data/arango/agent/engine-rocksdb/journals/archive` as I could get space in the disk otherwise. Started arangodb again.
3. I think at this point the disk got filled again, I deleted the files again.
4. I started arangodb. At some point I noticed that it didn't start to listen `server.endpoint` at all, in any of the three nodes.
5. Now I deleted all the data in arangodb/agent folders, started arangodb. At this point I got the servers listen ports again. I restored the data from a backup I made at point (1). 

So, a lot of things happened, a lot of things went wrong. I have data stored if you want to look at it.

**Comment by dsonet** [comment]
Met similar situation but with single server on windows 10. It eats all the disk space.

**Comment by ile** [comment]
Ok, interesting.

I haven't seen this anymore myself, and I don't know how I could reproduce it. Seems like it could happen if one server is shut down, but I'm not sure.

**Comment by ile** [comment]
The issue of ports not being listened was resolved.

The issue of disk getting full still probably exists.

**Comment by dothebart** [comment]
We have recently fixed a compaction issue that is now available for download with all supported versions and [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) - hence closing this as solved.
