### ISSUE TITLE
Web UI: JSON editor options look grayed out (i.e. disabled)

### ISSUE THREAD

**Issue by Simran-B** [arangodb/arangodb#5354]
_By Jeff Smith via [Google Groups](https://groups.google.com/forum/#!topic/arangodb/DmlmroTntEA) ([ref](https://github.com/arangodb/planning/issues/2270))_

Question: The ArangoDB User Interface appears to have many menu selections in a gray color. It looks to my eye like they are "grayed-out". 

![image](https://user-images.githubusercontent.com/7819991/40063541-dde9b8ee-585d-11e8-8f5e-bdfc28342324.png)

However, when I hover over them with my mouse, they suddenly light up and display their color, and I find that they are active and available menu choices.

![image](https://user-images.githubusercontent.com/7819991/40063549-e492b6aa-585d-11e8-85b3-7495f4633c14.png)

This is confusing to me as I always assumed that when something is grayed-out, it is in-active and is unable to be selected, as in this example, where the forward and back buttons are grayed out, indicating that they are not viable selections at this time.

![image](https://user-images.githubusercontent.com/7819991/40063560-e97a2f36-585d-11e8-97f0-714edfe35933.png)

Does this choice reflect new thinking in GUI design? Admittedly this is not the first place I have noticed the "active" grayed-out behavior in newer applications, but I fail to understand why it is being used and what it means.

Thanks, Jeff

**Comment by jeffsmith99** [comment]
josdejong, over at [jsoneditor](https://github.com/josdejong/jsoneditor/issues/532) agreed that [gray means disabled, black means enabled](https://en.wikipedia.org/wiki/Grayed_out). However he also explained,

> "The thought behind making the action menu button and drag area dots light gray is to prevent an overload of information to the user. In the interface I tried to introduce two "layers" of information: (1) the actual contents (2) secondary information and actions to work on the data. I want to have the core UI elements to be most prominent and the secondary UI elements to be a bit in the background.I'm afraid that when I give all UI elements the same prominence, that it becomes harder to focus on what really matters in the editor: the actual JSON data."

So, since that design decision is carried over to ArangoDB, at least I will know that when I  see a gray icon or menu that I should assume it is not a primary feature. It may be active, but is designed to be less prominent.

Jeff

**Comment by Simran-B** [comment]
@hkernbach Can you check if we use the latest version of JSON editor including their default theme, and whether we override any of its style? I agree that the contrast is too low, and it is apparently lower than with the default style of JSON editor.

**Comment by hkernbach** [comment]
fixed, see reference on top.

**Comment by sleto-it** [comment]
Hi,

Just a quick message to inform that v.3.3.14, which contains the fix for this problem, has been released

I am going ahead and closing this issue now. Please comment, if needed, and we will reopen it

Thanks again for reporting this bug,
