### ISSUE TITLE
Unexpected AQL Result

### ISSUE THREAD

**Issue by greatwar** [arangodb/arangodb#5400]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.4 devel (2018-04-30)
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [ ] mmfiles
- [x] rocksdb

On this operating system:
- [x] Linux 
  - [x] Ubuntu 16.04 .deb
  - [x] CentOS7 .rpm

I'm issuing AQL via:
- [x] web interface with this browser:     running on this OS:CentOS7/ubuntu
- [x] arangosh

The AQL query in question is:
step 1: create two empty collections

```
db._create("test1")
db._create("test2")
```

step 2:execute AQL:

```
LET t1=(FOR i IN ['a','b'] INSERT {_key:i} IN test1 RETURN NEW)

LET t2=(FOR i IN test2 FILTER i._key IN t1[*]._key RETURN i._key)

FILTER ASSERT(LENGTH(t2)==0,CONCAT('BAD: t2=',JSON_STRINGIFY(t2)))
FILTER ASSERT(0,'OK: t2 is empty')
RETURN 1

```
will got 'OK: t2 is empty' ,as expected

step 3: just swap test2 and test1 in AQL:
```
LET t1=(FOR i IN ['a','b'] INSERT {_key:i} IN test2 RETURN NEW)

LET t2=(FOR i IN test1 FILTER i._key IN t1[*]._key RETURN i._key)

FILTER ASSERT(LENGTH(t2)==0,CONCAT('BAD: t2=',JSON_STRINGIFY(t2)))
FILTER ASSERT(0,'OK: t2 is empty')
RETURN 1

```

will got BAD: t2=["a","b"] . this is not  the expected result,

**Comment by greatwar** [comment]
both ubuntu.deb and centos .rpm has same problems. 
and use fail function instead of ASSERT,problem occur in 3.3.

**Comment by greatwar** [comment]
after many try , change line 2 with 
LET t2=(FOR i IN test1 FILTER i._key IN  **UNION([],t1[*]._key)** RETURN i._key)
result as expected

**Comment by jsteemann** [comment]
I tried to reproduce it, but to no avail (yet). 
Here is my setup:

**Original query**
```
db._drop("test1"); db._drop("test2"); db._create("test1"); db._create("test2"); 
db._query(`
LET t1=(FOR i IN ['a','b'] INSERT {_key:i} IN test1 RETURN NEW)  
LET t2=(FOR i IN test2 FILTER i._key IN t1[*]._key RETURN i._key)  
FILTER ASSERT(LENGTH(t2)==0,CONCAT('BAD: t2=',JSON_STRINGIFY(t2))) 
FILTER ASSERT(0,'OK: t2 is empty') 
RETURN 1
`);
 
JavaScript exception in file 'js/server/modules/@arangodb/arango-statement.js' at 81,16: ArangoError 1593: AQL: OK: t2 is empty (while executing)
```

**test1 and test2 exchanged**
```
db._drop("test1"); db._drop("test2"); db._create("test1"); db._create("test2"); 
db._query(`
LET t1=(FOR i IN ['a','b'] INSERT {_key:i} IN test2 RETURN NEW)  
LET t2=(FOR i IN test1 FILTER i._key IN t1[*]._key RETURN i._key)  
FILTER ASSERT(LENGTH(t2)==0,CONCAT('BAD: t2=',JSON_STRINGIFY(t2))) 
FILTER ASSERT(0,'OK: t2 is empty') 
RETURN 1
`);
 
JavaScript exception in file 'js/server/modules/@arangodb/arango-statement.js' at 81,16: ArangoError 1593: AQL: OK: t2 is empty (while executing)
```

So both queries do return the same result for me, as they should.

I am using devel as of now.
I don't see any benefit in adding the call to the `UNION` function as you did. That shouldn't change the result.

Are you sure both collections were empty before you executed the second variant of the query (the one that failed)? And do you mind sharing the execution plans for the two queries so we can compare them? Thanks!

**Comment by greatwar** [comment]
thanks for reply,here is my screenshot.i will install a new os environment and test again

![aqlassert](https://user-images.githubusercontent.com/5835318/40289445-e3122f9a-5cea-11e8-97e9-6d2e9b85a6f3.png)

**Comment by greatwar** [comment]
i test on a fresh ubuntu 16.04(and finished apt upgrade),filesystem is ext4
rocksdb engine has problems as i describe.
but mmfile engine is fine.

thanks

**Comment by greatwar** [comment]
here are execution plans

[mmfile-plan1.txt](https://github.com/arangodb/arangodb/files/2021340/mmfile-plan1.txt)
[mmfile-plan2.txt](https://github.com/arangodb/arangodb/files/2021341/mmfile-plan2.txt)  as mmfile-plan1.txt, just swapped test2 and test1
[rocksdb-plan1.txt](https://github.com/arangodb/arangodb/files/2021342/rocksdb-plan1.txt)
[rocksdb-plan2.txt](https://github.com/arangodb/arangodb/files/2021344/rocksdb-plan2.txt) as rocksdb-plan1.txt, just swapped test2 and test1

but rocksdb plans  diffs with mmfile plans: (7 Optimization rules applied vs 6) , and result different plan,please **compare mmfile-plan1.txt and rocksdb-plan1.txt** for detail. here are big difference:

rocksdb plan:

 ```
 10   EnumerateCollectionNode      0         - FOR i IN test2   /* full collection scan, projection: `_key` */
 11   CalculationNode              0           - LET #15 = (i in t1[*].`_key`)   /* simple expression */   /* collections used: i : test2 */
 12   FilterNode                   0           - FILTER #15
 13   CalculationNode              0           - LET #17 = i   /* simple expression */   /* collections used: i : test2 */
```

vs mmfile plan:

```
 10   EnumerateCollectionNode      0         - FOR i IN test2   /* full collection scan */
 11   CalculationNode              0           - LET #15 = (i.`_key` in t1[*].`_key`)   /* simple expression */   /* collections used: i : test2 */
 12   FilterNode                   0           - FILTER #15
 13   CalculationNode              0           - LET #17 = i.`_key`   /* attribute expression */   /* collections used: i : test2 */
```

**Comment by greatwar** [comment]
here is another execution plans ( using UNION as i mentioned before),and may be this execution plain is the right plan:

[rocksdb-plan2-union.txt](https://github.com/arangodb/arangodb/files/2021423/rocksdb-plan2-union.txt)

```
db._drop("test1"); db._drop("test2"); db._create("test1"); db._create("test2");
db._explain(` LET t1=(FOR i IN ['a','b'] INSERT {_key:i} IN test2 RETURN NEW)   LET t2=(FOR i IN test1 FILTER i._key IN UNION([],t1[*]._key) RETURN i._key)   FILTER ASSERT(LENGTH(t2)==0,CONCAT('BAD: t2=',JSON_STRINGIFY(t2)))  FILTER ASSERT(0,'OK: t2 is empty')  RETURN 1 `);
```

**Comment by jsteemann** [comment]
Ok, got it reproduced. Happens with RocksDB engine only.

**Comment by greatwar** [comment]
awesome! it's got fixed. 

but i has a more question about execution plans :  (**NOTES: i simplified the query to a common used query pattern,and we can focus on the important part**)

prepare collection with `db._drop("test1"); db._create("test1");`

let's check
db._explain(`FOR i IN test1 FILTER i._key IN @a[*].k RETURN i`,{a:[{k:'1'}]});  
**vs**
db._explain(`FOR i IN test1 FILTER i._key IN UNION([],@a[*].k) RETURN i`,{a:[{k:'1'}]});

```
db._explain(`FOR i IN test1 FILTER i._key IN @a[*].k RETURN i`,{a:[{k:'1'}]});
Query string:
 FOR i IN test1 FILTER i._key IN @a[*].k RETURN i

Execution plan:
 Id   NodeType                  Est.   Comment
  1   SingletonNode                1   * ROOT
  2   EnumerateCollectionNode      0     - FOR i IN test1   /* full collection scan */
  3   CalculationNode              0       - LET #3 = (i.`_key` in [ { "k" : "1" } ][*].`k`)   /* simple expression */   /* collections used: i : test1 */
  4   FilterNode                   0       - FILTER #3
  5   ReturnNode                   0       - RETURN i

Indexes used:
 none

Optimization rules applied:
 none
```
**no index used,full collection scan**

```
db._explain(`FOR i IN test1 FILTER i._key IN UNION([],@a[*].k) RETURN i`,{a:[{k:'1'}]});
Query string:
 FOR i IN test1 FILTER i._key IN UNION([],@a[*].k) RETURN i

Execution plan:
 Id   NodeType        Est.   Comment
  1   SingletonNode      1   * ROOT
  6   IndexNode         10     - FOR i IN test1   /* primary index scan */
  5   ReturnNode        10       - RETURN i

Indexes used:
 By   Type      Collection   Unique   Sparse   Selectivity   Fields       Ranges
  6   primary   test1        true     false       100.00 %   [ `_key` ]   (i.`_key` in UNION([ ], [ { "k" : "1" } ][*].`k`))

Optimization rules applied:
 Id   RuleName
  1   use-indexes
  2   remove-filter-covered-by-index
  3   remove-unnecessary-calculations-2
```
**index used**

i think the first one is bad, the second is fine. am i wrong?

**Comment by jsteemann** [comment]
You are right. 
However, I am opening an additional ticket (#5419) as the last finding of you is unrelated to the original issue, and we prefer handling separate things with separate tickets if possible.

**Comment by maxkernbach** [comment]
ArangoDB version 3.3.10, which includes a fix for this issue, has been released today.
