### ISSUE TITLE
AQL - no index used

### ISSUE THREAD

**Issue by mpoeter** [arangodb/arangodb#5418]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.3

Mode:
- [x] Single-Server

Storage-Engine:
- [x] mmfiles

On this operating system:
- [x] Linux 
  - [x] Ubuntu .deb

### this is an AQL-related issue:
I'm issuing AQL via:
- [x] web interface with this browser: Firefox    running on this OS: Ubuntu

I have two collections `col1` and `col2`, both have a sparse unique hash index on the attribute `some_id` (not all documents have this attribute).

This query:
```
FOR a IN col1
    FILTER a.some_id != null
    FOR b IN col2
        FILTER b.some_id == a.some_id
        RETURN b
```
Results in the following execution plan:
```
Execution plan:
 Id   NodeType                      Est.   Comment
  1   SingletonNode                    1   * ROOT
  2   EnumerateCollectionNode      10002     - FOR a IN col1   /* full collection scan */
  3   CalculationNode              10002       - LET #2 = (a.`some_id` != null)   /* simple expression */   /* collections used: a : col1 */
  4   FilterNode                   10002       - FILTER #2
  5   EnumerateCollectionNode   81936384       - FOR b IN col2   /* full collection scan */
  6   CalculationNode           81936384         - LET #4 = (b.`some_id` == a.`some_id`)   /* simple expression */   /* collections used: b : col2, a : col1 */
  7   FilterNode                81936384         - FILTER #4
  8   ReturnNode                81936384         - RETURN b
Indexes used:
 none

Optimization rules applied:
 none
```
col1 has ~30k and col2 ~10k documents. Even though there are indexes for both collection, they are not used - instead, a full collection scan is performed for both collections, resulting in worst possible performance. (I killed the query after ~3min.)

**Comment by dothebart** [comment]
We currently don't have an optimizer rule that creates an index lookup with sparse indices when comparing to `!= null` though this would be possible...

**Comment by mpoeter** [comment]
So this is because the indexes are sparse?

**Comment by jsteemann** [comment]
Yes.

**Comment by mpoeter** [comment]
Unfortunately, making it non-sparse is not an option since it is also unique. But I guess we could add an additional non-sparse non-unique index.

**Comment by mpoeter** [comment]
That would be great!

Wouldn't it be possible to use the index for the first loop as well (simply iterate over all documents in the index)? This would make sense in cases where a large number of documents do not have this attribute.

**Comment by jsteemann** [comment]
For the first FOR loop, we could use a sparse or non-sparse index on `some_id`. But the optimizer is currently not smart enough to check for any != null occurrences.
Apart from that, a gain can only be expected if a small fraction of the documents has the `some_id` value set. Then using the index would only need to iterate over these documents, whereas with a full collection scan all documents will need inspection.

**Comment by jsteemann** [comment]
3.4/devel is a bit smarter now.
It will be able to use a sparse index if the query is adjusted as follows:
```
FOR a IN col1
    FILTER a.some_id != null   /* this condition is not necessary */
    FOR b IN col2
        FILTER b.some_id == a.some_id
        FILTER b.some_id != null   /* add this condition */
        RETURN b
```
Still 3.4/devel cannot figure out that b.some_id can never be null because a.some_id can never be null. But if an explicit `b.some_id != null` condition is added, it should now work and use the sparse index.

**Comment by vinaypyati** [comment]
Hi @mpoeter,

version 3.4.0-RC1 has been released, which contains this feature/fix. Please check it out. 
I will be closing this issue for now. Please comment, if needed, and we will reopen it.

Thanks!

Best,
