### ISSUE TITLE
Frequent 'updated local foxx repository' messages

### ISSUE THREAD

**Issue by davidmw** [arangodb/arangodb#5429]
Version 3.3.9
RocksDB Single Server Community
![screen shot 2018-05-23 at 3 12 13 pm](https://user-images.githubusercontent.com/3413901/40404713-98fedcd8-5e9c-11e8-9317-7503128d0c80.png)

I have a single Foxx service and it is in dev mode.  Have not submitted any updates to the service but keep getting update notices in the log.  I have 8 end points, 6 user functions.  So I don't know which 30 local services are triggering the notice.

**Comment by jsteemann** [comment]
A possible cause for this message getting logged is using the web interface's "Services" menu item.
I agree it's far from ideal to log this message that frequently.

**Comment by davidmw** [comment]
I don't see a relationship here between menu item and log entries. But I do get the entire Web UI becoming very unresponsive for a few minutes at a time.  Occasionally the browser session can't be recovered and must be exited. During these slow-downs or freezes of the UI my Foxx queries tend to keep working.  There are no slow queries running or detected. But the log entry clusters do seem to happen around the time of the UI slowdowns.

**Comment by jsteemann** [comment]
AFAIK whenever the log message occurs, the server will reached out to Github to update the list of remote Foxx services. If it does so too often, then I would consider this a bug.

**Comment by davidmw** [comment]
Is the update on the UI thread? And why update proactively?

**Comment by jsteemann** [comment]
The update is triggered by the UI, when the "Services" navigation item is accessed the first time. I think clicking around in this menu will render the list of Foxx services in the remote ArangoDB Foxx repository, that's why the call is made.

**Comment by jsteemann** [comment]
The above commit (currently in review and not merged to any version) should mitigate/fix the problem.

**Comment by maxkernbach** [comment]
ArangoDB version 3.3.10, which includes a fix for this issue, has been released today.
