### ISSUE TITLE
"Please specify a password" in arangorestore

### ISSUE THREAD

**Issue by arturasjurev** [arangodb/arangodb#5446]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [x] 3.3
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [x] own infrastructure
- [ ] Linux 
  - [x] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

These are the steps to reproduce:
1) Command :
`arangorestore  --include-system-collections true --server.database $dbname --create-database true --input-directory $location`

This is pretty small issue, but I couldn't find information on web on how to disable arango from asking for password while performing arangorestore. For every DB that is in backup, when restoring arango goes:

```
Restoring 10122927127318
Please specify a password: 
```

How can we prevent arango from asking for password while performing this action.

Thought option is `authentication = false` in arangod.conf , but this doesn't seem to work.

All help is appreciated !

**Comment by jsteemann** [comment]
Setting the option `authentication = false` in arangod.conf will disable authentication for the arangod server process. If this is what you want, it's fine, but be aware that the database server will then run without any authentication.
Additionally, you can set the option `authentication = false` in the config files of the client tools, e.g. arangorestore.conf. This will disable the password prompt for the client tool(s).
If the server still requires authentication (`authentication = true` in arangod.conf) but you do not want any password prompt, there is also the option to specify username and password for arangorestore as part of the invocating command, e.g.
```
arangorestore --server.username "$user" --server.password "$passwd" ...
```
Note that any of the configuration parameters can be passed on the command line or be used in config files, e.g. setting `authentication = false` in arangorestore.conf is the same as
```
arangorestore --server.authentication false```
```

**Comment by Simran-B** [comment]
If you use the default user `root` with an empty password, then `--server.password ""` should skip the password prompt.

**Comment by arturasjurev** [comment]
Thanks for the help !
