### ISSUE TITLE
cannot create connection to server  '' at endpoint 'tcp://X.X.X.X:8531'

### ISSUE THREAD

**Issue by dengwfxx** [arangodb/arangodb#5449]
## my environment running ArangoDB
ArangoDB 3.3.4
architecture: 64bit
build-date: 2018-03-06 15:40:10
build-repository: tags/v3.3.4-0-g36841fe

Mode:
- [ *] Cluster
- [ ] Single-Server

Storage-Engine:
- [ *] rocksdb

On this operating system:
  - [* ] RedHat .rpm(CentOS 7.2)

## I started a  3 node cluster using arangod. They are 192.168.19.171,192.168.19.172,192.168.19.181.
Command as below:
192.168.19.181
#nohup arangod -c /etc/arangodb3/arangod.conf --database.directory /data1/agent/data --javascript.startup-directory /usr/share/arangodb3/js --javascript.app-path /data1/agent/apps --log.file /work/log/arangodb3/agent.log --log.force-direct false --agency.activate true --server.endpoint tcp://0.0.0.0:8531 --agency.my-address tcp://192.168.19.181:8531 --agency.size 3 --agency.supervision true --foxx.queues false --server.statistics true --agency.endpoint tcp://192.168.19.172:8531 --agency.endpoint tcp://192.168.19.171:8531&
#nohup arangod -c /etc/arangodb3/arangod.conf --database.directory /data1/dbserver/data --javascript.startup-directory /usr/share/arangodb3/js --javascript.app-path /data1/dbserver/apps --log.file /work/log/arangodb3/dbserver.log --log.force-direct false --server.endpoint tcp://0.0.0.0:8530 --cluster.my-address tcp://192.168.19.181:8530 --cluster.my-role PRIMARY --foxx.queues false --server.statistics true --cluster.agency-endpoint tcp://192.168.19.181:8531 --cluster.agency-endpoint tcp://192.168.19.172:8531 --cluster.agency-endpoint tcp://192.168.19.171:8531&
#nohup arangod -c /etc/arangodb3/arangod.conf --database.directory /data1/coordinator/data --javascript.startup-directory /usr/share/arangodb3/js --javascript.app-path /data1/coordinator/apps  --log.file /work/log/arangodb3/coordinator.log --log.force-direct false --server.endpoint tcp://0.0.0.0:8529 --cluster.my-address tcp://192.168.19.181:8529 -cluster.my-role COORDINATOR --foxx.queues true --server.statistics true --cluster.agency-endpoint tcp://192.168.19.181:8531 --cluster.agency-endpoint tcp://192.168.19.172:8531 --cluster.agency-endpoint tcp://192.168.19.171:8531&

192.168.19.171
#nohup arangod -c /etc/arangodb3/arangod.conf --database.directory /data1/agent/data --javascript.startup-directory /usr/share/arangodb3/js --javascript.app-path /data1/agent/apps --log.file /work/log/arangodb3/agent.log --log.force-direct false --agency.activate true --server.endpoint tcp://0.0.0.0:8531 --agency.my-address tcp://192.168.19.171:8531  --agency.size 3 --agency.supervision true --foxx.queues false --server.statistics true --agency.endpoint tcp://192.168.19.181:8531 --agency.endpoint tcp://192.168.19.172:8531&
#nohup arangod -c /etc/arangodb3/arangod.conf --database.directory /data1/dbserver/data --javascript.startup-directory /usr/share/arangodb3/js --javascript.app-path /data1/dbserver/apps --log.file /work/log/arangodb3/dbserver.log --log.force-direct false --server.endpoint tcp://0.0.0.0:8530 --cluster.my-address tcp://192.168.19.171:8530 --cluster.my-role PRIMARY --foxx.queues false --server.statistics true --cluster.agency-endpoint tcp://192.168.19.181:8531 --cluster.agency-endpoint tcp://192.168.19.172:8531 --cluster.agency-endpoint tcp://192.168.19.171:8531&
#nohup arangod -c /etc/arangodb3/arangod.conf --database.directory /data1/coordinator/data --javascript.startup-directory /usr/share/arangodb3/js --javascript.app-path /data1/coordinator/apps --log.file /work/log/arangodb3/coordinator.log --log.force-direct false --server.endpoint tcp://0.0.0.0:8529 --cluster.my-address tcp://192.168.19.171:8529 --cluster.my-role COORDINATOR --foxx.queues true --server.statistics true --cluster.agency-endpoint tcp://192.168.19.181:8531 --cluster.agency-endpoint tcp://192.168.19.172:8531 --cluster.agency-endpoint tcp://192.168.19.171:8531&

192.168.19.172
#nohup arangod -c /etc/arangodb3/arangod.conf --database.directory /data1/agent/data --javascript.startup-directory /usr/share/arangodb3/js --javascript.app-path /data1/agent/apps --log.file /work/log/arangodb3/agent.log --log.force-direct false --agency.activate true --server.endpoint tcp://0.0.0.0:8531 --agency.my-address tcp://192.168.19.172:8531  --agency.size 3 --agency.supervision true --foxx.queues false --server.statistics true --agency.endpoint tcp://192.168.19.181:8531 --#agency.endpoint tcp://192.168.19.171:8531&
nohup arangod -c /etc/arangodb3/arangod.conf --database.directory /data1/dbserver/data --javascript.startup-directory /usr/share/arangodb3/js --javascript.app-path /data1/dbserver/apps --log.file /work/log/arangodb3/dbserver.log --log.force-direct false --server.endpoint tcp://0.0.0.0:8530 --cluster.my-address tcp://192.168.19.172:8530 --cluster.my-role PRIMARY --foxx.queues false --cluster.agency-endpoint tcp://192.168.19.181:8531 --cluster.agency-endpoint tcp://192.168.19.172:8531 --cluster.agency-endpoint tcp://192.168.19.171:8531&
#nohup arangod -c /etc/arangodb3/arangod.conf --database.directory /data1/coordinator/data --javascript.startup-directory /usr/share/arangodb3/js --javascript.app-path /data1/coordinator/apps --log.file /work/log/arangodb3/coordinator.log --log.force-direct false --server.endpoint tcp://0.0.0.0:8529 --cluster.my-address tcp://192.168.19.172:8529 --cluster.my-role COORDINATOR --foxx.queues true --server.statistics true --cluster.agency-endpoint tcp://192.168.19.181:8531 --cluster.agency-endpoint tcp://192.168.19.172:8531 --cluster.agency-endpoint tcp://192.168.19.171:8531&

## there always have some connection error, and the cluster not started!!!!  For example, on 192.168.19.181
/work/log/arangodb3/agent.log
INFO {cluster} cannot create connection to server '' at endpoint 'tcp://192.168.19.172:8531'
INFO {cluster} cannot create connection to server '' at endpoint 'tcp://192.168.19.171:8531'

work/log/arangodb3/coordinator.log
INFO {agencycomm} Flaky agency communication to http+tcp://192.168.19.181:8531. Unsuccessful consecutive tries: 45 (71.27s). Network checks advised.
INFO {agencycomm} Flaky agency communication to http+tcp://192.168.19.172:8531. Unsuccessful consecutive tries: 40 (48.65s). Network checks advised.

/work/log/arangodb3/dbserver.log
INFO {agencycomm} Flaky agency communication to http+tcp://192.168.19.172:8531. Unsuccessful consecutive tries: 45 (71.27s). Network checks advised.
INFO {agencycomm} Flaky agency communication to http+tcp://192.168.19.171:8531. Unsuccessful consecutive tries: 46 (76.47s). Network checks advised.

## but I confirmed the endpoint, it is LISTEN, 
[root@192.168.19.181 data1]# netstat -an|grep 8531
tcp        0      0 0.0.0.0:8531            0.0.0.0:*               LISTEN
tcp        0      0 192.168.19.181:40763    192.168.19.181:8531     TIME_WAIT
tcp        0      0 192.168.19.181:8531     192.168.32.32:56349     ESTABLISHED
tcp        0      0 192.168.19.181:8531     192.168.32.32:56350     ESTABLISHED
tcp        0      0 192.168.19.181:8531     192.168.19.171:36376    ESTABLISHED
tcp        0      0 192.168.19.181:8531     192.168.19.172:60199    ESTABLISHED
tcp        0      0 192.168.19.181:40804    192.168.19.181:8531     TIME_WAIT
tcp        0      0 192.168.19.181:40792    192.168.19.181:8531     TIME_WAIT
tcp        0      0 192.168.19.181:40777    192.168.19.181:8531     TIME_WAIT
tcp        0      0 192.168.19.181:40778    192.168.19.181:8531     TIME_WAIT
tcp        0      0 192.168.19.181:8531     192.168.32.32:56351     ESTABLISHED
tcp        0      0 192.168.19.181:40789    192.168.19.181:8531     TIME_WAIT
tcp        0      0 192.168.19.181:40764    192.168.19.181:8531     TIME_WAIT
tcp        0      0 192.168.19.181:40803    192.168.19.181:8531     TIME_WAIT

[root@192.168.19.171 data1]# netstat -an|grep 8531
tcp        0      0 0.0.0.0:8531            0.0.0.0:*               LISTEN
tcp        0      0 192.168.19.171:45847    192.168.19.171:8531     TIME_WAIT
tcp        0      0 192.168.19.171:45918    192.168.19.171:8531     TIME_WAIT
tcp        0      0 192.168.19.171:38987    192.168.19.181:8531     TIME_WAIT
tcp        0      0 192.168.19.171:38976    192.168.19.181:8531     TIME_WAIT
tcp        0      0 192.168.19.171:45842    192.168.19.171:8531     TIME_WAIT
tcp        0      0 192.168.19.171:45848    192.168.19.171:8531     TIME_WAIT
tcp        0      0 192.168.19.171:45857    192.168.19.171:8531     TIME_WAIT
tcp        0      0 192.168.19.171:36376    192.168.19.181:8531     ESTABLISHED
tcp        0      0 192.168.19.171:45889    192.168.19.171:8531     TIME_WAIT
tcp        0      0 192.168.19.171:45885    192.168.19.171:8531     TIME_WAIT
tcp        0      0 192.168.19.171:39014    192.168.19.181:8531     TIME_WAIT
tcp        0      0 192.168.19.171:45860    192.168.19.171:8531     TIME_WAIT
tcp        0      0 192.168.19.171:45866    192.168.19.171:8531     TIME_WAIT
tcp        0      0 192.168.19.171:38983    192.168.19.181:8531     TIME_WAIT
tcp        0      0 192.168.19.171:38949    192.168.19.181:8531     TIME_WAIT
tcp        0      0 192.168.19.171:45895    192.168.19.171:8531     TIME_WAIT
tcp        0      0 192.168.19.171:38942    192.168.19.181:8531     TIME_WAIT
tcp        0      0 192.168.19.171:39009    192.168.19.181:8531     TIME_WAIT
tcp        0      0 192.168.19.171:38953    192.168.19.181:8531     TIME_WAIT
tcp        0      0 192.168.19.171:45904    192.168.19.171:8531     TIME_WAIT
tcp        0      0 192.168.19.171:38995    192.168.19.181:8531     TIME_WAIT
tcp        0      0 192.168.19.171:45916    192.168.19.171:8531     TIME_WAIT
tcp        0      0 192.168.19.171:45871    192.168.19.171:8531     TIME_WAIT
tcp        0      0 192.168.19.171:38962    192.168.19.181:8531     TIME_WAIT
tcp        0      0 192.168.19.171:45901    192.168.19.171:8531     TIME_WAIT
tcp        0      0 192.168.19.171:39001    192.168.19.181:8531     TIME_WAIT
tcp        0      0 192.168.19.171:39031    192.168.19.181:8531     TIME_WAIT
tcp        0      0 192.168.19.171:45836    192.168.19.171:8531     TIME_WAIT
tcp        0      0 192.168.19.171:38999    192.168.19.181:8531     TIME_WAIT
tcp        0      0 192.168.19.171:39028    192.168.19.181:8531     TIME_WAIT
tcp        0      0 192.168.19.171:38968    192.168.19.181:8531     TIME_WAIT
tcp        0      0 192.168.19.171:45839    192.168.19.171:8531     TIME_WAIT
tcp        0      0 192.168.19.171:45832    192.168.19.171:8531     TIME_WAIT
tcp        0      0 192.168.19.171:38958    192.168.19.181:8531     TIME_WAIT
tcp        0      0 192.168.19.171:38970    192.168.19.181:8531     TIME_WAIT
tcp        0      0 192.168.19.171:38946    192.168.19.181:8531     TIME_WAIT
tcp        0      0 192.168.19.171:38982    192.168.19.181:8531     TIME_WAIT
tcp        0      0 192.168.19.171:45870    192.168.19.171:8531     TIME_WAIT
tcp        0      0 192.168.19.171:45877    192.168.19.171:8531     TIME_WAIT
tcp        0      0 192.168.19.171:39018    192.168.19.181:8531     TIME_WAIT
tcp        0      0 192.168.19.171:45881    192.168.19.171:8531     TIME_WAIT
tcp        0      0 192.168.19.171:38940    192.168.19.181:8531     TIME_WAIT

[root@192.168.19.172 data1]# netstat -an|grep 8531
tcp        0      0 0.0.0.0:8531            0.0.0.0:*               LISTEN
tcp        0      0 192.168.19.172:34810    192.168.19.181:8531     TIME_WAIT
tcp        0      0 192.168.19.172:34821    192.168.19.181:8531     TIME_WAIT
tcp        0      0 192.168.19.172:42547    192.168.19.172:8531     TIME_WAIT
tcp        0      0 192.168.19.172:42528    192.168.19.172:8531     TIME_WAIT
tcp        0      0 192.168.19.172:42521    192.168.19.172:8531     TIME_WAIT
tcp        0      0 192.168.19.172:42475    192.168.19.172:8531     TIME_WAIT
tcp        0      0 192.168.19.172:42486    192.168.19.172:8531     TIME_WAIT
tcp        0      0 192.168.19.172:34842    192.168.19.181:8531     TIME_WAIT
tcp        0      0 192.168.19.172:60199    192.168.19.181:8531     ESTABLISHED
tcp        0      0 192.168.19.172:34862    192.168.19.181:8531     TIME_WAIT
tcp        0      0 192.168.19.172:34854    192.168.19.181:8531     TIME_WAIT
tcp        0      0 192.168.19.172:42536    192.168.19.172:8531     TIME_WAIT
tcp        0      0 192.168.19.172:42513    192.168.19.172:8531     TIME_WAIT
tcp        0      0 192.168.19.172:42498    192.168.19.172:8531     TIME_WAIT
tcp        0      0 192.168.19.172:34815    192.168.19.181:8531     TIME_WAIT
tcp        0      0 192.168.19.172:42485    192.168.19.172:8531     TIME_WAIT
tcp        0      0 192.168.19.172:34831    192.168.19.181:8531     TIME_WAIT
tcp        0      0 192.168.19.172:42497    192.168.19.172:8531     TIME_WAIT
tcp        0      0 192.168.19.172:42550    192.168.19.172:8531     TIME_WAIT
tcp        0      0 192.168.19.172:34878    192.168.19.181:8531     TIME_WAIT
tcp        0      0 192.168.19.172:34867    192.168.19.181:8531     TIME_WAIT
tcp        0      0 192.168.19.172:34822    192.168.19.181:8531     TIME_WAIT
tcp        0      0 192.168.19.172:34846    192.168.19.181:8531     TIME_WAIT
tcp        0      0 192.168.19.172:42509    192.168.19.172:8531     TIME_WAIT
tcp        0      0 192.168.19.172:42479    192.168.19.172:8531     TIME_WAIT
tcp        0      0 192.168.19.172:34832    192.168.19.181:8531     TIME_WAIT
tcp        0      0 192.168.19.172:34884    192.168.19.181:8531     TIME_WAIT

## So, why the connection problem occured and how to fixed? Thanks !!

**Comment by OmarAyo** [comment]
Hi @dengwfxx 

Have you try to deploy the ArangoDB Cluster using the Starter ?

**Comment by dengwfxx** [comment]
Sorry, my bad, the final reason is iptables service enabled.
