### ISSUE TITLE
ArangoDB working slow with large collection!! what is the reason?? 

### ISSUE THREAD

**Issue by ShahanaBubly** [arangodb/arangodb#5461]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ .] 3.3

Mode:
- [. ] Single-Server

Storage-Engine:
- [. ] mmfiles
- [ .] rocksdb

On this operating system:
- [ ] Windows operating system
Processor Intel CPU 3.20GHz, Memory:8GB  , Storage 500GB.

I'm issuing AQL via:
- [ ] web interface with this browser:     running on this OS:

If I run any query into large data collection more then 15000 records, for example, its shows 
Query: out of memory (while executing) (exception location: C:\b\workspace\RELEASE__BuildPackages\arangod\RestHandler\RestCursorHandler.cpp:134)
my every record has this kind of JSON data:

{
  "Method": {
    "Type": "Surface Coating Oligos",
    "madewithEDLVersion": "10082012100419",
    "Duration": "P0Y0M0DT0H25M0S",
    "Name": "Master_Method",
    "Status": "Finished",
    "-UID": "E10002",
    "-derivedfrom": "Production Method",
    "-Start": "27.09.2012 14:46:30",
    "Inputobjects": {
      "Restriction": {
        "-MinOccur": "0",
        "-MaxOccur": "-1"
      },
      "Obj": [
        {
          "madewithEDLVersion": "20092012155335",
          "derivedfrom": "Microfluidic-Channel A for 2-Kanal Chip (manuell)",
          "Identity": {
            "UID": "P9984",
            "Type": "Microfluidic-Channel",
            "TakeoverFromInputObject": "1"
          },
          "PrimaryContainer": {
            "UID": "P9983",
            "Type": "2-Kanal Chip (manuell)",
            "TakeoverFromInputObject": "1"
          }................
.................................................

My task was to find out performance between MongoDB and ArangoDB. As I have read all about ArangoDB and got interested to check on my data collection. End of my research it's showing very slow compared to MongoDB. any types of query take more time compared to MongoDB. The collection which I am using is almost 45GB. And in MongoDB with my configuration, it's working with good performance. But ArangoDB taking time in the query and sometimes it shows the message that out of memory (while executing). 

What would be the reason??

**Comment by dothebart** [comment]
Hi, 
for optimal performance we recommend Linux with ext4 filesystems. 
You need to make sure that your queries are backed by incides; 

Please use [explain to check your queries](https://docs.arangodb.com/3.3/AQL/ExecutionAndPerformance/ExplainingQueries.html). You may also [find my article series on finding and fixing performance bottlenecks in ArangoDB](https://www.arangodb.com/2017/10/performance-analysis-pyarango-usage-scenarios/) usefull.

In general you would probably implement the same business logic in a different way when using ArangoDB instead of MongoDB at least in some cases. 

You may also want to have a look [at the performance benchmarks comparing ArangoDB to other databases](https://www.arangodb.com/2018/02/how-we-wronged-neo4j-postgresql-update-arangodb-benchmark-2018/) usefull. You can find [the sources including the different query implementations for the respective databases in the noslq-tests repository](https://github.com/weinberger/nosql-tests).

**Comment by ShahanaBubly** [comment]
Actually, I have to work on the windows system. With my setting and configuration all queries working fine in mongoDB. Then my question is with same configuration and and same queries why its showing slow performance? 
FOR doc IN limslager
    COLLECT WITH COUNT INTO length
    RETURN length
(Very slow)
FOR doc IN ItemsOrder
 LIMIT 500 RETURN doc
(This query ans is out of memory? )

when I want to delete collections records I used this 
FOR u IN LimsprocTest
  REMOVE u IN LimsprocTest
 (for the large dataset its shows Query: out of memory (while executing))

**Comment by dothebart** [comment]
Please post the output of `explain` of these respective queries.

**Comment by ShahanaBubly** [comment]
My purpose of the project is to find out performance between MongoDB and ArangDB. With our data, if AragoDB gives the better performance we thought to change the database. Unfortunately, Performance is not good to compare to MongoDB. Is it the Problem because of limited virtual memory? or what can be the reason? 
Query all documents (Total records: 20177) small dataset 45.3MB
#FOR doc IN limslager
   RETURN doc
ArangoDB retrieve: 0.28sec  

#db.limslager.find({})
MongoDB retrieve: 0.0065s 

Query all documents (Total records: 100945) large dataset 9.79GB
#FOR doc IN limsproc
   RETURN doc
ArangoDB retrieve: Out of memory while executing

#db.limsproc.find({}) **Total records: 319056 
MongoDB retrieve: 0.0065s

**Comment by dothebart** [comment]
sorry to repeat myself, can you post the output of `explain`.

**Comment by mpoeter** [comment]
You have to be careful with your comparison! MongoDB `doc.collection.find` returns only a cursor with a default batchSize depending on the library (AFAIK usually somewhere between 20-100). ArangoDB would also return a cursor, but with a default batchSize of 1000.

**Comment by OmarAyo** [comment]
Hi @ShahanaBubly 

Just sending a quick followup, how things are going with this ticket? 
Please, could you post the output of `explain` in order to help you more?

Best,

**Comment by ShahanaBubly** [comment]
My data records are almost 319056. So when I want to query all records (FOR doc IN XX
RETURN doc) output shows 
Out of memory while execution!!! that means the size of my data cannot load into memory. So running almost 20GB of data. But when  I run more than 20GB data in MongoDB its works within a 0.05 sec. I found that with low memory MongoDB performance quit ok. But for ArangoDB its bit slow while querying any data. thanks

**Comment by Simran-B** [comment]
I doubt that Mongo transfers the entire data of 20GB in 0.05 to the client. With Arango however, what happens is that it first builds up the result in memory, then starts the transfer to client. The memory is apparently insufficient for that. We have a new query streaming option in the upcoming 3.4 however, which should help a lot in your case: https://github.com/arangodb/arangodb/pull/4769/files

**Comment by vinaypyati** [comment]
Hi @ShahanaBubly,

Hope the latest comment by Simran answers your questions. As suggested we have new query streaming option coming up in 3.4 that should help you in this case. You could use the [nightly ](https://download.arangodb.com/nightly/)builds to experiment with this feature or wait for the official release of 3.4. I am going ahead and closing this issue considering the comments answer your questions. You can reopen if you have any further questions.
