### ISSUE TITLE
Question about the usage of foxx

### ISSUE THREAD

**Issue by dilipvamsi** [arangodb/arangodb#5478]
Hi,
I want to know if there are any disadvantages and advantages to foxx over any other backend which communicates with db.
We are thinking of going with python flask but we came across foxx.
We are unable to decide which way to go. 
As we can be having at peek of 50K concurrent users who shall do read write to the db.

Thanks, 
Dilip Vamsi.

**Comment by dothebart** [comment]
Hi
This depends on how well you can express what you want from the database in AQL.
If you need things combined programmatically foxx lives inside arangodb, so it only needs to "lift" the datastructures up to .js.

for flask you would need to transfer more data over the wire including de/serialization and memory usage on both sides in case of AQL isn't able to properly reduce the data for you. 

If you can pinpoint the data that you need well with AQL, foxx can serve for authentification tasks if you i.e. need finer grained access control to the DB.

In general its a question of what you know better; Foxx can give you a headstart, but if you can't get used to .js ymmv ;-)

**Comment by dilipvamsi** [comment]
Hi @dothebart ,
Consider a scenario, where the number of requests are too high which can cause denial of service for foxx and making the db not accessible for other operations. 
Can foxx do the queuing of the requests or that has to be handled by a middle-ware that does the queuing and calls the foxx (which can act as proxy for the actual foxx service).

Thanks,
Dilip Vamsi.

**Comment by dothebart** [comment]
We use boost::asio as frontend for the http requests. so it will be definitely able to handle these on the inbound path. 
However, it all depends how many concurrent V8 contexts you have; it can spawn more, but that will consume time. At least the greenlets are afair bound to one cpu? Foxx can run on several ones. 

In the end you need to benchmark this in a way that I demonstrated in these blogpost series.

**Comment by vinaypyati** [comment]
Hi @dilipvamsi,

Do you have any further queries on this issue? Do the answer/suggestions from dothebart answer your queries on Foxx?

Thanks

**Comment by dilipvamsi** [comment]
Thanks.
