### ISSUE TITLE
Use of WITH clause when working with Graphs not clear in AQL User Guide

### ISSUE THREAD

**Issue by gbjbaaha** [arangodb/arangodb#5524]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [X] 3.3
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [X] Single-Server

Storage-Engine:
- [ ] mmfiles
- [X] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [X] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is an AQL-related issue:
[X] I'm using graph features

I'm issuing AQL via:
- [X] web interface with this browser:     running on this OS:
- [ ] arangosh
- [ ] this Driver:

This may be a documentation issue in the User Guide for AQL here [https://docs.arangodb.com/3.3/AQL/Graphs/Traversals.html#graph-traversals-in-a-cluster]

```
Working with named graphs

[WITH collection1[, collection2[, ...collectionN]]]
FOR vertex[, edge[, path]]
  IN [min[..max]]
  OUTBOUND|INBOUND|ANY startVertex
  GRAPH graphName
  [OPTIONS options]

WITH is optional for single server instances, but required for graph traversals in a cluster.
     collections (collection, repeatable): list of collections that will be involved in the traversal
```

Elsewhere the documentation states that you should use the WITH clause when running as a cluster. My question is when working with a named graph (so I have both Vertex and Edge collections defined via the Graph API), should I be specifying just the Vertex collections in the WITH clause, just the Edge collections, or both. The documentation is not clear on this point.

Thanks

**Comment by maxkernbach** [comment]
Hi @gbjbaaha, 

when working with a named graph in a cluster only the vertex collections have to be specified in the `WITH` clause. Otherwise your graph's edges might reference vertices from arbitrary collections that are not included in your graph.

I am going to update the documentation to make this more clear.

**Comment by maxkernbach** [comment]
The documentation change is adressed by
devel: https://github.com/arangodb/arangodb/pull/5540
3.3: https://github.com/arangodb/arangodb/pull/5542

**Comment by maxkernbach** [comment]
The documentation changes are online in the current documentation.
