### ISSUE TITLE
Corruption: Bad table magic number

### ISSUE THREAD

**Issue by divadpoc** [arangodb/arangodb#5539]
## my environment running ArangoDB
I'm using ArangoDB version:
- [ x] 3.3.5

Mode:
- [ x] Single-Server

Storage-Engine:
- [ x] rocksdb

On this operating system:
- [ ] Linux 
  - [ x] other: CentOS7 .rpm

we're using ArangoDB 3.3.5 with RocksDB as a single instance.

we added data and queries etc. worked fine. after a shut down of the machine where arangod is running, and after reboot the service didn't come up again with the following warning:

Corruption: Bad table magic number

Is there a way to repair the database? Or any other ways to get rid of the problem?

**Comment by maxkernbach** [comment]
Hi @divadpoc,

did you try to specify `--log.level TRACE` as Kaveh suggested? Log-level and the path of your log file is configured at `/etc/arangodb3/arangod.conf` in the `[log]` section when using the default service.

Please attach this logfile so that we can investigate the issue.

**Comment by divadpoc** [comment]
attached should be the log file with level TRACE

[arangod.log](https://github.com/arangodb/arangodb/files/2079678/arangod.log)

**Comment by jsteemann** [comment]
It's an issue with one of the SST files that RocksDB writes. The SST file either has an unexpected size or is corrupted. This may happen e.g. in case of errors inside RocksDB or in case of hardware issues (disk problems).
Has the database server been shutdown gracefully or was it shut down the hard way?

**Comment by divadpoc** [comment]
I think disk problem can be excluded, it's running on a virtual host.
the shutdown was graceful. the service was running, a shutdown -r now was issued and after reboot the arangodb service wasn't starting.
Can it be repaired?

**Comment by divadpoc** [comment]
Just wanted to provide an update. when setting foxx/queues to false (in the configuration file) it's working, at least we tried basics within the web interface (displaying collections) and a query via the Java driver.
Any explanations or ideas why this works?

**Comment by dothebart** [comment]
With the release of [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) I'm closing this as out of date. 

Most probably at the time being the corrupted data file was mainly used by the foxx queue collection, hence it would only occur when it was used.
