### ISSUE TITLE
Travis: version 3.3 missing?

### ISSUE THREAD

**Issue by mrbatista** [arangodb/arangodb#5544]
I've created a PR to add support for arangodb 3.3 for [loopback-connector-arangodb](https://github.com/mrbatista/loopback-connector-arangodb/pull/77) connector.
Travis fail with
```sh
$ ./test/travis/setup_arangodb.sh
./setup_arangodb_3.3.sh: line 1: 404: command not found
```

https://www.arangodb.com/repositories/travisCI/

**Comment by dothebart** [comment]
Hi, 
we recommend using ArangoDB docker for travisCI tests.

**Comment by mrbatista** [comment]
Migrated! Thanks!
