### ISSUE TITLE
Database dump shows dead documents plus additional documents

### ISSUE THREAD

**Issue by kavin26** [arangodb/arangodb#5556]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [x] 3.3
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [x] Single-Server

Storage-Engine:
- [ ] mmfiles
- [x] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [x] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

I'd issued arangodump command from command line - `arangodump --server.username root --server.password kavin --server.database newsDB --output.directory dump`. I later checked one of collection from dump json file which shows 764 documents, whereas in db total number of docs in that particular collection amounts to 649.

Screenshot of that collection info been attached with this message.

Even if i go by that alive+dead combo, i should have 726 docs, but i have 764 docs out of which one seems to be empty showing `''` whereas 37 docs shows me data like this `{'_rev': '_WlEFMda---', '_key': '13930545'}` which i dont find in the source database collection.

Could you please explain the discrepancy? Am i missing anything here?
![db_collection_info_2018-06-07t15-31-10 944z](https://user-images.githubusercontent.com/11194101/41110376-d3ddd36c-6a96-11e8-9769-27a57f7e4a8a.png)

**Comment by jsteemann** [comment]
arangodump for the MMFiles storage engine dumps the contents of the collections' datafiles. These also include deletions.
When a dump is loaded back into the database using arangorestore, the deleted documents are not re-created.

**Comment by kavin26** [comment]
Thank you so much @jsteemann.... got clarified... so i need to use arangorestore to reload data from dump.... issue is solved... i'm closing it...
