### ISSUE TITLE
How to set storage-engine in cluster starter?

### ISSUE THREAD

**Issue by snowzjy** [arangodb/arangodb#5577]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [ x] 3.3
- [ ] self-compiled devel branch

Mode:
- [x ] Cluster
- [ ] Single-Server

Storage-Engine:
- [x ] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [x ] other: CentOs 7
- [ ] Windows, version: 
- [ ] MacOS, version:

### Foxx

These are the steps to reproduce:
1) use command: arangodb --starter.data-dir=/lhdata/aaa/ --ownAddress 192.168.36.216 --all.cluster.index-create-timeout 10800 --all.server.storage-engine=rocksdb

The following problem occurs: [Screenshot?] 

Error reported:  Option '--server.storage-engine' is essential to the starters behavior and cannot be overwritten.

Instead I would be expecting: 
No error occur and the storage-engine of agent、dbserver and coordinator will transfer from mmfiles to rocksdb

**Comment by maxkernbach** [comment]
[Starter devel documentation:](https://docs.arangodb.com/devel/Manual/Programs/Starter/Options.html#other-database-options)

> Options for arangod that are not supported by the starter can still be passed to the database servers using a pass through option. Every option that start with a pass through prefix is passed through to the commandline of one or more server instances. 


The option `--server.storage-engine string` is directly supported by the starter, no pass through option is required. Therefore you can use `--server.storage-engine string` instead of `--all.server.storage-engine string`.

**Comment by snowzjy** [comment]
@vinaypyati @maxkernbach Thanks for your reply!
When I tried the commands in 3 nodes, no error reported, but I storage engine not changed after I wait 14 hours. In the nodes page of web UI,click DBServer0001 or DBServer0001(0002 or 0003), display the storage engine is still mmfiles, and I checked dbserver8530/data/ENGINE file ,its content is still "mmfiles". 
Is there something wrong?

**Comment by snowzjy** [comment]
@maxkernbach  Thank you!
I tried arangodump  and arangorestore, storage-engine have changed to rocksdb now.

**Comment by OmarAyo** [comment]
Hi @snowzjy 

Glad to hear that you were able to change the storage engine. 
I am going ahead and close this ticket. Please feel free to reopen it at any time by adding a new comment.

Best,
