### ISSUE TITLE
 Graph relation problem

### ISSUE THREAD

**Issue by Nontakarnkeng123** [arangodb/arangodb#5580]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.2.9
Mode:
- [x] Single-Server
On this operating system:
- [x] Windows 10
### this is an AQL-related issue:
[ ] I'm using graph features

MATCH (b:Europe),(c:Latvia) 
WHERE b.Country = c.Country 
CREATE UNIQUE (b)-[:europe]-(c)

This is the code create relations the node of the Neo4j program. The program will find the value of every row in the lable. Need to know that AQL language can be programmed to create a relations without having to relations each pair in each collection?

**Comment by dothebart** [comment]
with the [release of Arangodb 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model) I'm closing this as out of date.
