### ISSUE TITLE
Benchmark on performance of arangodb on bulkiness of a document

### ISSUE THREAD

**Issue by dilipvamsi** [arangodb/arangodb#5588]
Hi,
Is there a benchmark on the performance of the arangodb (insert, update) on variation of the document size.

Thanks,
Dilip Vamsi.

**Comment by Simran-B** [comment]
The `complexity` parameter for the `aqlinsert` test case in `arangobench` controls the number of attributes inserted, e.g. `arangobench --test-case aqlinsert --complexity 1000`.

Each attribute looks like `"value{n}": true`. You can see the result after running the test case once in the _system database, collection *ArangoBenchmark*.
