### ISSUE TITLE
Slow AQL Performance with graph queries in cluster

### ISSUE THREAD

**Issue by mollox** [arangodb/arangodb#5601]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.3

Mode:
- [x] Cluster

Storage-Engine:
- [x] mmfiles

On this operating system:
- [x] Linux 
  - [x] docker - official docker library

### this is an AQL-related issue:
[x] I'm using graph features

I'm issuing AQL via:
- [x] web interface with this browser: Chrome     running on this OS: MacOS

We are currently evaluating ArangoDB graph features for our application. In our demo data we have a vertex collection O and an edge collection O_B002_O .

Now we want to count all children down from a given root vertex with unknown depth:

```
WITH O, O_B002_O
FOR v IN 1..100 OUTBOUND @objectId OUTBOUND O_B002_O
COLLECT WITH COUNT INTO length
RETURN length
```
In nonclustered mode this works pretty fast (~2ms).

```
Query string:
 WITH O, O_B002_O
 FOR v IN 1..100 OUTBOUND @objectId OUTBOUND O_B002_O
 COLLECT WITH COUNT INTO length
 RETURN length

Execution plan:
 Id   NodeType        Est.   Comment
  1   SingletonNode      1   * ROOT
  2   TraversalNode    900     - FOR v  /* vertex */ IN 1..100  /* min..maxPathDepth */ OUTBOUND 'O/30000000' /* startnode */  O_B002_O
  3   CollectNode        1     - COLLECT  WITH COUNT INTO length   /* count */
  4   ReturnNode         1     - RETURN length

Indexes used:
 By   Type   Collection   Unique   Sparse   Selectivity   Fields               Ranges
  2   edge   O_B002_O     false    false        62.62 %   [ `_from`, `_to` ]   base OUTBOUND

Traversals on graphs:
 Id   Depth    Vertex collections   Edge collections   Options                                   Filter conditions
  2   1..100                        O_B002_O           uniqueVertices: none, uniqueEdges: path   

Optimization rules applied:
 none
```
Going to clustered mode, the execution time is 100x slower (~200ms+).
```
Query string:
 WITH O, O_B002_O
 FOR v IN 1..100 OUTBOUND @objectId OUTBOUND O_B002_O
 COLLECT WITH COUNT INTO length
 RETURN length

Execution plan:
 Id   NodeType        Site       Est.   Comment
  1   SingletonNode   COOR          1   * ROOT
  2   TraversalNode   COOR        900     - FOR v  /* vertex */ IN 1..100  /* min..maxPathDepth */ OUTBOUND 'O/30000000' /* startnode */  O_B002_O
  3   CollectNode     COOR          1     - COLLECT  WITH COUNT INTO length   /* count */
  4   ReturnNode      COOR          1     - RETURN length

Indexes used:
 By   Type   Collection     Unique   Sparse   Selectivity   Fields               Ranges
  2   edge   O_B002_O   false    false            n/a   [ `_from`, `_to` ]   base OUTBOUND

Traversals on graphs:
 Id   Depth    Vertex collections   Edge collections   Options                                   Filter conditions
  2   1..100                        O_B002_O       uniqueVertices: none, uniqueEdges: path   

Optimization rules applied:
 none
```
Our cluster is currently set up with 3 Coordinators und 3 Servers. To speed up the queries, we already set the same leader to the shards of the vertex and edge collection, but the queries in cluster are still more than 100x slower.

Is there any way to speed up the query performance to achieve a similar query speed like in non clustered mode?

**Comment by graetzer** [comment]
this will always be a pretty expensive query in the cluster, a path depth 100 will cause up to m^100 requests (where m is the number of inner nones in your search tree)

Perhaps you need to rethink this query a bit and add some filters ? You could also try the smart-graph  feature in our enterprise version, this would probably improve this somewhat.

**Comment by OmarAyo** [comment]
Hi @mollox 

We haven't heard from you recently, I am going ahead and close this ticket.

Feel free to reopen this ticket at any time by adding a new comment.

Best,
