### ISSUE TITLE
"Statistics not ready yet. Waiting." in Web Interface

### ISSUE THREAD

**Issue by annguyenliaison** [arangodb/arangodb#5615]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [X] 3.2
- [ ] 3.3
- [ ] self-compiled devel branch

Mode:
- [ ] Cluster
- [X] Single-Server

Storage-Engine:
- [X] mmfiles
- [ ] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [X] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

### this is a web interface-related issue:
I'm using the web interface with this browser:   Mozilla Firefox  running on this OS: Windows Server 2012 R2 Standard
- [ ] authentication is enabled?
- [ ] using the cluster?
- [X] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as root
3) use database [X] `_system` [ ] other: 
4) click to DASHBOARD
...

The following problem occurs: [Screenshot?] 
Statistics not ready yet. Waiting.
![image](https://user-images.githubusercontent.com/28339872/41458284-d22d78f8-708e-11e8-965b-18fa9aa719a0.png)

Instead I would be expecting: 
Statistic Information

Having this issue with ArangoDB version 3.2.9 running on RHEL 7.5. Same problem with ArangoDB version 3.3.10.
Works fine with RedHat 6 in other server.

Note: 
# gather server statistics
statistics = true

**Comment by vinaypyati** [comment]
Hi @annguyenliaison,

I tried to reproduce this issue on 3.2.9 and 3.3.10. On fresh installation of 3.3.10, the _Dashboard_ UI hangs with the message "Statistics not ready yet. Waiting." for around ~10 to 15seconds but eventually loads the statistics. Also, this is not recurring issue on my side. The _Dashboard_ loads withour any problems the next time. Can you please confirm if the _Dashboard_ loads eventually or hangs indefinitely. 

Best,

**Comment by annguyenliaison** [comment]
Hi @vinaypyati ,
Yes, it still hangs indefinitely.  I also tried to restart arangodb several times, but nothing changes. Other things are fine, only getting stuck with Dashboard.
Note that there is no internet connection with the server.

**Comment by annguyenliaison** [comment]
Hi @vinaypyati ,
Yes, it still hangs indefinitely.  I also tried to restart arangodb several times, but nothing changes. Other things are fine, only getting stuck with Dashboard.
Note that there is no internet connection with the server.

**Comment by vinaypyati** [comment]
Hi @annguyenliaison,

Thank you for the information. Unfortunately, the issue still is still not reproducible. 

Can you please try restarting ArangoDB with storage engine set to RocksDB and check if the issue still persists? You can change the storage engine with the option `--server.storage-engine=rocksdb` from command line. 

Can you please also confirm the browser and browser version that you are using to access the web UI?

Best,

**Comment by OmarAyo** [comment]
Hi @annguyenliaison 

Just sending a quick followup - have you been able to try out Vinay's suggestion?

Best,

**Comment by annguyenliaison** [comment]
Hi @vinaypyati and @OmarAyo ,

Sorry for the delay. I still couldn't have a chance to try Vinay's suggestion. The arangoDB has been being used 24/7 without the Statistics display. I will try with storage engine as RocksDB maybe next week.

I used Google Chrome 65.0.3325.181 (Official Build) (64-bit) and FireFox 52.0.2 (64-bit) to access the web UI.
For other information, I also run these following commands earlier after installing arangoDB before in that server:
sudo bash -c "echo madvise >/sys/kernel/mm/transparent_hugepage/enabled"
sudo bash -c "echo madvise >/sys/kernel/mm/transparent_hugepage/defrag"
sudo bash -c "echo 2 >/proc/sys/vm/overcommit_memory"
sudo bash -c "echo 0 >/proc/sys/vm/zone_reclaim_mode"
sudo bash -c "sysctl -w 'vm.max_map_count=10000000'"
sudo bash -c "echo 74 > /proc/sys/vm/overcommit_ratio"
export GLIBCXX_FORCE_NEW=1

BR,
-An

**Comment by annguyenliaison** [comment]
Hi,
I have just tested on a different RH 7.3 server with arangodb version 3.2.9 and statistic works on web interface.
The browser here in this case is Firefox 60.0.2 (64-bit) and there is internet connection.

So there might be some problem with the one above (ArangoDB version 3.2.9 running on RHEL 7.5). Do you think there are some missing things in `/usr/share/arangodb3/js` or/and `/var/lib/arangodb3-apps` ?

**Comment by vinaypyati** [comment]
Hi @annguyenliaison, 

Sorry for the delay and thank you for the details. Good to know that statistics work on RH 7.3 with ArangoDB version 3,2,9. I did further tests and tried reproducing this issue with RHEL 7.5 and ArangoDB version 3.2.9. Statistics work here.  

I confirm that the warning that you receive on the browser console `dygraphs: Can't plot empty data set` is reproducible with fresh installation on my side too. The browser warns with this error and eventually displays the statistics after 10 to 15 seconds. However, we are analyzing more on this warning and will keep you updated.

You mentioned that on your side RHEL 7.5 does not have an internet connection. Is it possible to check if you can reproduce it with an internet connection?

Best,

**Comment by vinaypyati** [comment]
Hi @annguyenliaison,

Just sending a quick follow up. We see similar issues being reported. Wanted to confirm if this issue is also similar. Can you let us know if you switch tabs or keep ArangoDB Web Interface in the background in your browser and visit back after a long time(an hour or so) to check if the _Dashboard_ has been loaded? 

Thanks!

**Comment by vinaypyati** [comment]
Hi,

We haven't heard back from you for a while now. I will go ahead and close this issue. Please feel free to reopen if you have any further queries. 

Thanks!
