### ISSUE TITLE
Extend /_api/aqlfunction response with isNewlyCreated attribute

### ISSUE THREAD

**Issue by Simran-B** [arangodb/arangodb#5629]
The result in 3.4.devel-ga84d9f7335 when registering a function is:

```
require("@arangodb/aql/functions").register("my::test", val=>val*2 , true)
{
  "code" : 201
}
```

> GET /_api/aqlfunction/ was migrated to match the general structure of ArangoDB Replies

https://github.com/arangodb/arangodb/blob/devel/Documentation/Books/Manual/ReleaseNotes/UpgradingChanges34.md#rest-api

In 3.3, it used to be boolean that indicated whether an existing function with the same name was overwritten.

I suggest to extend the new response format with `"isNewlyCreated" : true/false,` as seen for indexes. It would return the opposite value compared to 3.3 (registering a function for the first time = false, but isNewlyCreated = true), but it will still be possible to determine if an existing function has just been replaced.

**Comment by jsteemann** [comment]
Bugfix PR: https://github.com/arangodb/arangodb/pull/5636

**Comment by maxkernbach** [comment]
Closing as fixed. It works in the latest release 3.4.2.

First execution:

```
require("@arangodb/aql/functions").register("my::test", val=>val*2 , true)
false
```

Next executions:

```
require("@arangodb/aql/functions").register("my::test", val=>val*2 , true)
true
```
