### ISSUE TITLE
Aardvark: UI confirms saving of document for primitives, which actually fails

### ISSUE THREAD

**Issue by Simran-B** [arangodb/arangodb#5648]
In the ArangoDB v3.3.10 Web UI, create a document in a collection, open it in the document editor, change to code view and then type any primitive, such as:

- `true` / `false`
- any number, e.g. `1234`
- any string, e.g. `"foo"`
- an array with random members, e.g. `[1,2,3]`

Click Save and you will see the confirmation **Document saved** although the request failed:

```
PUT http://localhost:8529/_db/_system/_api/document/test?returnNew=true

[{"error":true,"errorNum":1227,"errorMessage":"invalid document type"}]
```

If you enter `null`, the following error shows in the browser console:

```
app.js?version=1528098809693:2 Uncaught TypeError: Cannot set property '_key' of null
    at N.d.saveDocument (app.js?version=1528098809693:2)
    at N.d.confirmSaveDocument (app.js?version=1528098809693:6)
    at N.d.saveDocument (app.js?version=1528098809693:6)
    at HTMLDivElement.dispatch (libs.js?version=1528098809693:2)
    at HTMLDivElement.q.handle (libs.js?version=1528098809693:2)
```

`undefined` or other strings without wrapped in quote marks do raise errors however:

`Document editor: : Error: Parse error on line 1: foobar ^ Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'`

**Comment by hkernbach** [comment]
@Simran-B PR's opened. See references.

**Comment by sleto-it** [comment]
Hi,

Just a quick message to inform that v.3.3.14, which contains the fix for this problem, has been released

I am going ahead and closing this issue now. Please comment, if needed, and we will reopen it

Thanks again for reporting this bug,
