### ISSUE TITLE
Feature/ filtering input data of views / arangosearch

### ISSUE THREAD

**Issue by AntoineAA** [arangodb/arangodb#5650]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [ ] 3.2
- [ ] 3.3
- [x] 3.4
- [ ] self-compiled devel branch

Mode:
- [x] Cluster
- [x] Single-Server

Storage-Engine:
- [ ] mmfiles
- [x] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [x] Linux 
  - [x] Debian .deb
  - [x] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [ ] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

Hi,

I'm testing arangosearch, and I would like to filter data from the collection that will feed the view.

The collection contains millions of documents, but only 10% are useful for research.
Based on this example:
```javascript
{
	field: "value",
	is_valid: true,
	...
},
{
	field: "value",
	is_valid: false,
	...
}
```
I would like to use research capabilities on documents that contain `is_valid: true`.

Thank you :avocado:

**Comment by KVS85** [comment]
Hello @AntoineAA,

Have you already tried 3.4.0 version? Is it convenient for this problem to include both `field` as *text_en* (if you plan to use search capabilities ) and `is_valid` as *identity*  link into a view.

Then, you can make the following query: `FOR d in a_view SEARCH d.is_valid == "true" AND <your search clause for a valid field> RETURN d`.

Another approach at the moment is to create surrogate field called `valid_field` and link only this field into a view.

**Comment by AntoineAA** [comment]
Hi @KVS85,

I tried 3.4.0 and 3.4.1 but not the view / search capabilities for now.

I'll try the method that you recommend.

Thanks!

**Comment by sowee15** [comment]
I'm also interested in this feature! It should also remove from the view's index documents that no longer satisfy the conditions to be included in the view.

**Comment by Dronplane** [comment]
Hi, we`ve merged new analyzer type `aql` - now AQL query could be used to filter/pre process data (but currently only on field basis).  See the docs https://www.arangodb.com/docs/devel/arangosearch-analyzers.html (it might take some time to update and show new analyzer types). 
Hope that helps to cover at least some cases.
