### ISSUE TITLE
Typescript definition

### ISSUE THREAD

**Issue by corbane** [arangodb/arangodb#5658]
Hello !

Have you a plan or existing typeScript definition for the lib @arangodb ?

Thank you ?

**Comment by corbane** [comment]
from https://github.com/arangodb/arangodb/issues/5660

> Try @types/arangodb, which are the official typings maintained at DefinitelyTyped. Yes, the API can't be perfectly represented in TypeScript but the typings come pretty close.

and write in your Typescript code

```ts
import * as arangodb from "@arangodb"
import createRouter = require("@arangodb/foxx/router")
```
---

I don't know why, but  with `import * as createRouter from "@arangodb/foxx/router"`

the linter make an error but the LSP work

![image](https://user-images.githubusercontent.com/8430545/42000039-bf6b5aa2-7a5f-11e8-971a-d235adec487b.png)

**Comment by pluma** [comment]
FWIW try `import createRouter = require("@arangodb/foxx/router")` to make the linter happy. This works for all node-style default exports.

**Comment by pluma** [comment]
To clarify, the `import * as` version compiles to the same code but doesn't make much sense as it is intended to be used with ES modules, not node-style exports.  Semantically it translates to "take all the named exports from this module and call it this name" whereas the `import =` version translates to "take the node exports object and call it this name". The linter prefers the clearer semantics but tolerates the other syntax.

I'm closing this ticket as this is a documentation problem covered by the other issue.
