### ISSUE TITLE
Non standard ECMA syntax

### ISSUE THREAD

**Issue by corbane** [arangodb/arangodb#5660]
You have writing the REST parameters of Javascript library (@arangodb) with unstandard ECMA syntax.

```js
router.get([path], [...middleware], handler, [name]): Endpoint
router.post([path], [...middleware], handler, [name]): Endpoint
router.put([path], [...middleware], handler, [name]): Endpoint
router.patch([path], [...middleware], handler, [name]): Endpoint
router.delete([path], [...middleware], handler, [name]): Endpoint
router.all([path], [...middleware], handler, [name]): Endpoint
```

- [doc MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters)
- [CMAScript 2015 (6th Edition, ECMA-262)](https://www.ecma-international.org/ecma-262/6.0/#sec-function-definitions)

The problem is for the intelligence syntax in code editor that is the first help when new user writing code.

**Comment by JonDum** [comment]
The brackets aren't signifying you should actually put brackets, but is a place holder for where the actual content goes. Maybe this is less confusing?

`router.get(<path>, <...middleware>, handler, <name>) : Endpoint`

The same goes or `: Endpoint`. They're just trying to document what the method returns. If you're new to JavaScript I can see how that'd be confusing since without Flow/TypeScript there are no types or return types.

**Comment by corbane** [comment]
Thanks @JonDum for your answer, but I'm not a new Javascript user and I still write in Typescript.

in a precedence post https://github.com/arangodb/arangodb/issues/5658 I searched for an arangodb.d.ts.
I did not find and I started writing what I need for test arango in my workflow.

The syntax specification say:
```
FormalParameterList:
    FunctionRestParameter
    FormalsList
    FormalsList , FunctionRestParameter
```

So in correct javascript, the `Rest parameters always MUST writing after all others parameters`

**Comment by Simran-B** [comment]
As Jon tried to say, there are no rest parameters in the signature in that sense. The method takes a variable amount of arguments. I'm no TypeScript expert so not sure if this can be expressed well. If not, I guess you could treat it like a single rest parameter?

    router.get( [...args] ) : Endpoint

Not sure how useful that would be, or if there are ways to further describe individual members of the args array in the TS typings.

**Comment by corbane** [comment]
Ok i understand (sorry my english is not good)
At this day, I wrote this definition:
```ts
type Handler = (req: Request, res: Response) => void

interface Router
{
    /**
     * @param {string} [path] The path of the request handler relative to the base path the Router is mounted at.
     * If omitted, the request handler will handle requests to the base path of the Router.
     * For information on defining dynamic routes see the section on [path parameters in the chapter on router endpoints](https://docs.arangodb.com/devel/Manual/Foxx/Reference/Routers/Endpoints.html#pathparam).
     * 
     * @see https://github.com/arangodb/arangodb/issues/5660
     */
    //@ts-ignore
    get (path?: string, ...middleware?: Function, handler: Handler, name?: string): Endpoint
    //@ts-ignore
    get (path?: string, ...middleware?: Function, handler: Handler): Endpoint
    get (path: string, handler: Handler, name?: string): Endpoint
    //@ts-ignore
    get (...middleware?: Function, handler: Handler, name?: string): Endpoint
    //@ts-ignore
    get (...middleware?: Function, handler: Handler): Endpoint
    get (handler: Handler, name?: string): Endpoint
}
```

I have a `@ts-ignore` to force the ts compiler to accept the signature of the function.
the result seems sufficient but I have not tested in real time yet

**Comment by corbane** [comment]
Thank you @pulma i have test `yarn add @types/@arangodb` but no `yarn add @types/arangodb`

I think you can add a problem on the documentation to add this information and prevent new users (with Typescript like me) lose time rewriting an existing definition.

Thank you !

**Comment by pluma** [comment]
Hey @corbane, you're right that this should be covered by the documentation. In fact we're working on a chapter about TypeScript for the Foxx documentation overhaul scheduled with the 3.4 release.

**Comment by corbane** [comment]
👍

**Comment by Simran-B** [comment]
@pluma Can you give a status update and assign whoever is working on this? Thanks!

**Comment by pluma** [comment]
@Simran-B the general advice for Webpack also applies when using TypeScript: https://docs.arangodb.com/3.4/Manual/Foxx/Guides/Webpack.html

There's no specific chapter about TypeScript though.

**Comment by Simran-B** [comment]
If the answer to "how do I use TypeScript in Foxx" is "with Webpack", then maybe it suffices to extend the Webpack page with an example for TS?

**Comment by dothebart** [comment]
Please note that we updated V8 to 7.1; This will become part of the upcomming ArangoDB 3.5 Release.

**Comment by dothebart** [comment]
Closing this as solved. 
ArangoDB 3.7 with even newer V8 is available for download: 
https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/
