### ISSUE TITLE
Replication applier restrictions will crash synchronisation after initial sync

### ISSUE THREAD

**Issue by soualid** [arangodb/arangodb#5679]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.3.9

Mode:
- [x] Single-Server

Storage-Engine:
- [x] rocksdb

On this operating system:
- [x] DCOS on
  - [x] own infrastructure
- [x] Linux 
  - [x] docker - official docker library

## problem explanation

When using the following configuration to setup an async replication between a master and a slave database with collection restrictions, the applier will fail with the following error message, it seems the applier tries to insert datas in the ignored collection after the initial sync: 

```
collection not found, offending marker ... "cuid":"shares"
```

Tried to workaround the problem by manually creating empty collections for this. But the error still happens, an internal ID must be used to find the proper collection to insert datas into.

Here is the applier configuration: 

```
require("@arangodb/replication").setupReplication({
    "endpoint": "tcp://xxxxx",
    "database": "xxxxx",
    "username": "root",
    "password": "xxxxx",    
    "requestTimeout": 600,
    "connectTimeout": 10,
    "ignoreErrors": 0,
    "maxConnectRetries": 100,
    "lockTimeoutRetries": 0,
    "sslProtocol": 0,
    "skipCreateDrop": false,
    "autoStart": true,
    "adaptivePolling": false,
    "autoResync": true,
    "autoResyncRetries": 20,
    "includeSystem": false,
    "requireFromPresent": true,
    "verbose": false,
    "incremental": true,
    "restrictType": "exclude",
    "restrictCollections": ["shares","notifications","events_","sessions","views"],
    "connectionRetryWaitTime": 15,
    "initialSyncMaxWaitTime": 300000,
    "idleMinWaitTime": 1,
    "idleMaxWaitTime": 2.5
});
```

**Comment by soualid** [comment]
It seems that a working workaround is to import the structure first and to add `skipCreateDrop: true` in the replication configuration. The excluded collections will still be synchronised thus, but at least the applier is able to run with this hack.

**Comment by jsteemann** [comment]
This bug is a regression in the 3.3 branch. 
There is still code to handle the `restrictCollections` and `restrictType` settings, but it depends on the master sending a "cname" attribute for the replication data. However, the default replication format between a 3.3 master/slave pair is not using the "cname" attribute but "cuid" now.
 
This [PR](https://github.com/arangodb/arangodb/pull/5685) tries to fix the issue, by asking the master for its inventory when `restrictCollections` and `restrictType` are used and there is no "cname" but just an unknown "cuid" value in the replication data.

**Comment by maxkernbach** [comment]
Hi @soualid, 

version 3.3.12, which includes a fix for this issue, has been released. Could you please upgrade to the latest version and check if the problem persists?

**Comment by soualid** [comment]
Thanks, I'll check this asap.

**Comment by OmarAyo** [comment]
Hi @soualid 

Just sending a quick followup - did you have the chance to upgrade to latest version and check if the issue still occurs?

Looking forward to your feedback 

Thanks

**Comment by OmarAyo** [comment]
Hi @soualid 

We haven't heard from you recently, I am going to close this ticket. 
If needed, please add a new comment and we will reopen it again.

FYI ArangoDB version 3.3.14 is now available 

Best,
