### ISSUE TITLE
Slow traversal aql query

### ISSUE THREAD

**Issue by telco2011** [arangodb/arangodb#5716]
## My environment

* __ArangoDB version__ _(e.g. 3.3.10 or self-compiled devel branch)_: `3.3.10`
* __Storage engine__ _(MMFiles / RocksDB)_: `MMFiles`
* __ArangoDB Deployment mode:__ _(Single Server / Master/Slave / Active Failover / Cluster / DC2DC)_: `Cluster`
* __Infrastructure__ _(AWS / Azure / ... / own)_: `own`
* __Operating system__ _(Ubuntu 18.04 / Windows 10 / MacOS 10.13.4 / DCOS 1.10 /...)_: `Ubuntu 16.04`
* __Used Package__ _(Debian or Ubuntu .deb / SUSE or RedHat .rpm / docker - official docker library / other)_: `docker`

## Component

__Affected feature__
_(e.g. Installation, Foxx, AQL query using web interface / arangosh / with driver / ...)_: `AQL query`

__AQL query (if applicable):__ `WITH S FOR ne IN N FILTER ne.level == 2 LET ss = (COUNT(FOR v IN 1..100 INBOUND ne._id S_N, N_N OPTIONS { bfs: true } FILTER CONTAINS(v._id, "S") RETURN v)) INSERT { _key: ne._key, ssCount: ss } IN countSs`

__AQL explain (if applicable)__ _(output of `db._explain("<my aql query>")`)_: 

    Query string:
    WITH S FOR ne IN Ns FILTER ne.level == 2 LET ss = (COUNT(FOR v IN 1..100 INBOUND ne._id 
    S_N, N_N OPTIONS { bfs: true } FILTER CONTAINS(v._id, "S") RETURN v)) INSERT { 
    _key: ne._key, ssCount: ss } IN countSs

    Execution plan:
    Id   NodeType                  Site         Est.   Comment
    1   SingletonNode             DBS             1   * ROOT
    2   EnumerateCollectionNode   DBS           157     - FOR ne IN Ns   /* full collection scan */
    3   CalculationNode           DBS           157       - LET #6 = (ne.`level` == 2)   /* simple expression */   /* collections used: ne : network */
    4   FilterNode                DBS           157       - FILTER #6
    21   RemoteNode                COOR          157       - REMOTE
    22   GatherNode                COOR          157       - GATHER 
    11   SubqueryNode              COOR          157       - LET #2 = ...   /* subquery */
    5   SingletonNode             COOR            1         * ROOT
    6   CalculationNode           COOR            1           - LET #8 = ne.`_id`   /* attribute expression */   /* collections used: ne : network */
    7   TraversalNode             COOR       921600           - FOR v  /* vertex */ IN 1..100  /* min..maxPathDepth */ INBOUND #8 /* startnode */  S_N, INBOUND N_N
    8   CalculationNode           COOR       921600           - LET #12 = CONTAINS(v.`_id`, "S")   /* simple expression */
    9   FilterNode                COOR       921600           - FILTER #12
    10   ReturnNode                COOR       921600           - RETURN v
    13   CalculationNode           COOR          157       - LET #14 = { "_key" : ne.`_key`, "ssCount" : COUNT(#2) }   /* simple expression */   /* collections used: ne : N */
    15   DistributeNode            COOR          157       - DISTRIBUTE
    16   RemoteNode                DBS           157       - REMOTE
    14   InsertNode                DBS             0       - INSERT #14 IN countSs
    17   RemoteNode                COOR            0       - REMOTE
    18   GatherNode                COOR            0       - GATHER 

    Indexes used:
    By   Type   Collection        Unique   Sparse   Selectivity   Fields               Ranges
    7   edge   N_N                false    false            n/a   [ `_from`, `_to` ]   base INBOUND
    7   edge   S_N                false    false            n/a   [ `_from`, `_to` ]   base INBOUND

    Traversals on graphs:
    Id   Depth    Vertex collections   Edge collections               Options                                              Filter conditions
    7   1..100                        S_N, N_N                      bfs: true, uniqueVertices: none, uniqueEdges: path   

    Optimization rules applied:
    Id   RuleName
    1   remove-unnecessary-calculations
    2   remove-data-modification-out-variables
    3   distribute-in-cluster
    4   scatter-in-cluster
    5   distribute-filtercalc-to-cluster
    6   remove-unnecessary-remote-scatter

    Write query options:
    Option                   Value
    ignoreErrors             false
    waitForSync              false
    nullMeansRemove          false
    mergeObjects             true
    ignoreDocumentNotFound   false
    readCompleteInput        true
    useIsRestore             false
    consultAqlWriteFilter    false

__Dataset__
 _(description, or if possible, please share an example dataset to reproduce the issue either by a gist with an arangodump, or `db.collection.save({my: "values"}) statements )_: I can't attach a dataset but I can attach an example of my data tree.
![arangodb-issue](https://user-images.githubusercontent.com/3685073/42046690-b54cb4e0-7afe-11e8-9430-1f5cc255ca0f.png)

__Problem__:

I need to find all S nodes for a N node. I use the above query to find them but this query is very slow. I have near 68 N1 nodes, 314 N2 nodes, 64087 N3 nodes, 215148 S nodes and 81702 U nodes distributed in different ways but following the pattern of the above image.

The query response takes near 1s and I have tried this same structure in neo4j and it takes only 10ms to respond.

Is there any way to optimize the aql query?

Thanks

**Comment by dothebart** [comment]
Hi, 
can you please generate some script to create such a graph along the lines of https://github.com/arangodb/arangodb/blob/devel/js/common/modules/%40arangodb/graph-examples/example-graph.js ? Thanks.

**Comment by Simran-B** [comment]
Maybe try the following:
- Add a hash index on field `level` for collection _N_

- Add a type attribute to the involved vertex collections with value `S`.
  You can run a query like below for the respective collections to do so:
  `FOR doc IN coll FILTER CONTAINS(doc._id, "S") UPDATE doc WITH { type: "S" } IN coll`

- Use this modified query:
  ```
  WITH S
  FOR ne IN N FILTER ne.level == 2
  LET ss = (COUNT(FOR v IN 1..100 INBOUND ne._id S_N, N_N OPTIONS { bfs: true }
    FILTER v.type == "S" 
    RETURN v))
  INSERT { _key: ne._key, ssCount: ss } IN countSs
  ```

Please let me know if this performs any better.

**Comment by jsteemann** [comment]
The slow part in this query is very likely the `FILTER CONTAINS(v._id, "S")`.
This filter condition will be run for each node visited by the traversal, which will probably be a lot.
If I understand correctly, there are different edge collections: N_N contains edges between different documents in N, and S_N contains edges between N and S nodes.

If so, then the count part of the query can be rewritten as
```
COUNT(FOR v IN 1..100 INBOUND ne._id N_N FOR e IN S_N FILTER e._to == v._id RETURN e._id)
```
The traversal then only looks for connections between N nodes in a single edge collection. For each N found, it will join the edges from S_N to count them. I can't predict if that is any faster than the original query, but it may be worth a try.

Regarding performance comparison with neo4j: if a similar query completes in neo4j in 10ms, I think this will have been a single-server version. Running this query in a single-server ArangoDB instance will also likely be faster than running the same query in the cluster version of ArangoDB. This is because single-server databases will have zero overhead for cluster-internal communication.

**Comment by maxkernbach** [comment]
Hi @telco2011,

did you have a chance to try the suggested adjustments?

**Comment by telco2011** [comment]
Hi @maxkernbach. I can’t try the ajustments yet. I’d like to try with a single server to check the performanece as well. 

When I try, I’ll back with my results 😉

**Comment by telco2011** [comment]
Hi guys, I've tried both adjustments but with similar result. The performance is nearly the same. I'll try to create a script with an example of the data but it will take me a little time to do it. Meanwhile, any other recommendation or idea? Thanks.

**Comment by telco2011** [comment]
Hi again guys. as @jsteemann said before, I've tried the same query in a single instance and now, the response time is much better. I'll use a single instance for the moment because I need fast responses.

Thanks for your help ;-)
