### ISSUE TITLE
Edge document with user provided key is inserted as many times as the number of shards

### ISSUE THREAD

**Issue by tkallioras** [arangodb/arangodb#5727]
My Environment

* __ArangoDB Version__:        3.3.11 Enterprise
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Cluster (local cluster using ArangoDB Starter)
* __Operating System__:        MacOS 10.14 beta
* __Used Package__:              Docker - official Docker library

## Component, Query & Data

__Affected feature__:
Edge Document insertion

I have an edge collection with the following options (it's in golang but it's readable):

```
keyOptions := &driver.CollectionKeyOptions{
	AllowUserKeys: true,
}

options := &driver.CreateCollectionOptions{
	ReplicationFactor: 2,
	NumberOfShards:    40,
	Type:              driver.CollectionTypeEdge,
	IndexBuckets:      64,
	KeyOptions:        keyOptions,
}
```

Then I try with a **custom key** to add the following document:

```
LET edge = ( 
	INSERT {
		_key: @key,
		_from: @fromID,
		_to: @toID
	} IN @@edgeCollection 
	RETURN NEW)

RETURN edge
```

The result is that I have 40 documents added in the collection (equal to the number of shards). If I change the number of shards, the number of the inserted documents still matches the number of shards.

However if I do not use a user provided key the insertion works as expected.

There is probably an issue with the driver, however one thing that's striking is that when I run a query on the `edgeCollection`, it returns those 40 documents with the same `_key`, but different `_rev`, which is odd since the insertion happens only once.

The query I run after the insertion is the following:

```
FOR e IN @@edgeCollection
 RETURN e
```

and this is the explanation:

```
Query string:
 FOR e IN friendRequestsEdge
     RETURN e

Execution plan:
 Id   NodeType                  Site       Est.   Comment
  1   SingletonNode             DBS           1   * ROOT
  2   EnumerateCollectionNode   DBS          40     - FOR e IN friendRequestsEdge   /* full collection scan */
  6   RemoteNode                COOR         40       - REMOTE
  7   GatherNode                COOR         40       - GATHER 
  3   ReturnNode                COOR         40       - RETURN e

Indexes used:
 none

Optimization rules applied:
 Id   RuleName
  1   scatter-in-cluster
  2   remove-unnecessary-remote-scatter
```

and this is a screenshot when I run the query:

![screenshot 2018-06-29 at 12 08 38](https://user-images.githubusercontent.com/11908520/42084020-31f869a8-7b95-11e8-909e-f68ff2167502.png)

**Comment by jsteemann** [comment]
This is not a problem with the golang driver, so please feel free to close the issue in the go driver's repository.
I tried to reproduce the problem using your query and setup, but it works as expected. So I am guessing the query you posted is not the actual insert query that is executed, or that something in my setup is different.

I am able to reproduce the problem though if I turn off specific AQL optimizer rules or when I turn the edge collection into a smart edge collection.

**Comment by tkallioras** [comment]
@jsteemann How come though and this problem occurs (in the particular query I use) only whenever I provide a user defined key?
Btw is there anything I could provide that would help?

**Comment by tkallioras** [comment]
I just realized that this result is influenced by a previous subquery. The full query is this (I am checking whether an edge with the same `_from` and `_to` values already exists and since this is a bidirectional relationship I check both pairs).

**Query and explain:**

```
Query string:
 LET requests = (
 	FOR e IN @@edgeCollection
 		FILTER (e._from == @fromID && e._to == @toID) || (e._from == @toID && e._to == @fromID)
 		RETURN 1)
 		
 FILTER LENGTH(requests) == 0
 		
 LET edge = ( 
 	INSERT {
 		_key: @key,
 		_from: @fromID,
 		_to: @toID
 	} IN @@edgeCollection 
 	RETURN NEW)
 RETURN edge

Execution plan:
 Id   NodeType          Site       Est.   Comment
  1   SingletonNode     COOR          1   * ROOT
  8   SubqueryNode      COOR          1     - LET requests = ...   /* const subquery */
  2   SingletonNode     DBS           1       * ROOT
  6   CalculationNode   DBS           1         - LET #10 = 1   /* json expression */   /* const assignment */
 17   IndexNode         DBS           2         - FOR e IN friendRequestsEdge   /* edge index scan, projections: `_to`, `_from` */
  4   CalculationNode   DBS           2           - LET #8 = (((e.`_from` == "7529d8f5-ec04-5203-a8e6-df7ddd0237cc") && (e.`_to` == "4845f9e3-9076-51d4-a6fe-c40dd3a90c38")) || ((e.`_from` == "4845f9e3-9076-51d4-a6fe-c40dd3a90c38") && (e.`_to` == "7529d8f5-ec04-5203-a8e6-df7ddd0237cc")))   /* simple expression */   /* collections used: e : friendRequestsEdge */
  5   FilterNode        DBS           2           - FILTER #8
 20   RemoteNode        COOR          2           - REMOTE
 21   GatherNode        COOR          2           - GATHER 
  7   ReturnNode        COOR          2           - RETURN #10
  9   CalculationNode   COOR          1     - LET #12 = (LENGTH(requests) == 0)   /* simple expression */
 10   FilterNode        COOR          1     - FILTER #12
 15   SubqueryNode      COOR          1     - LET edge = ...   /* subquery */
 11   SingletonNode     DBS           1       * ROOT
 12   CalculationNode   DBS           1         - LET #14 = { "_key" : "'123456789'", "_from" : "7529d8f5-ec04-5203-a8e6-df7ddd0237cc", "_to" : "4845f9e3-9076-51d4-a6fe-c40dd3a90c38" }   /* json expression */   /* const assignment */
 13   InsertNode        DBS           1         - INSERT #14 IN friendRequestsEdge
 24   RemoteNode        COOR          1         - REMOTE
 25   GatherNode        COOR          1         - GATHER 
 14   ReturnNode        COOR          1         - RETURN $NEW
 16   ReturnNode        COOR          1     - RETURN edge

Indexes used:
 By   Type   Collection           Unique   Sparse   Selectivity   Fields      Ranges
 17   edge   friendRequestsEdge   false    false            n/a   [ `_to` ]   (e.`_to` == "4845f9e3-9076-51d4-a6fe-c40dd3a90c38")
 17   edge   friendRequestsEdge   false    false            n/a   [ `_to` ]   (e.`_to` == "7529d8f5-ec04-5203-a8e6-df7ddd0237cc")

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   remove-data-modification-out-variables
  3   use-indexes
  4   scatter-in-cluster
  5   distribute-filtercalc-to-cluster
  6   remove-unnecessary-remote-scatter
  7   reduce-extraction-to-projection

Write query options:
 Option                   Value
 ignoreErrors             false
 waitForSync              false
 nullMeansRemove          false
 mergeObjects             true
 ignoreDocumentNotFound   false
 readCompleteInput        true
 useIsRestore             false
 consultAqlWriteFilter    false
```

**Comment by jsteemann** [comment]
Ok, thanks. I can reproduce with that.

**Comment by ObiWahn** [comment]
https://github.com/arangodb/arangodb/pull/5745

**Comment by maxkernbach** [comment]
Hi @tkallioras ,

version 3.3.12, which includes a fix for this issue, has been released. Could you please upgrade to the latest version and check if the problem persists?

**Comment by tkallioras** [comment]
Hello @maxkernbach, I have tested using a custom key in some sharded edge collections and it seems solved. If something pops up I will post any issues here.

**Comment by maxkernbach** [comment]
Thanks for your feedback, I am closing this issue for now.
