### ISSUE TITLE
Named graph - add edge definition does not respect graph options

### ISSUE THREAD

**Issue by mpv1989** [arangodb/arangodb#5737]
## My Environment

* __ArangoDB Version__:        devel
* __Storage Engine__:             MMFiles & RocksDB
* __Deployment Mode__:       Cluster

## Component, Query & Data

__Affected feature__:
HTTP API [POST /_api/gharial/{graph-name}/edge](https://docs.arangodb.com/3.3/HTTP/Gharial/Management.html#add-edge-definition)

__Problem__:
Adding a edge definition with a not existing collection involved creates the collection without using the `numberOfShards` or `replicationFactor` of the graph options. The collection is always created with `numberOfShards` == 1 and `replicationFactor` == 1.

__Expected result__:
The new created collections should have the same `numberOfShards` and `replicationFactor` as passed in the options when creating the graph.

**Comment by hkernbach** [comment]
This is already fixed in 3.3. Also this behaviour is gone in the new gharial C++ API.
