### ISSUE TITLE
Skiplist index is ignored when using SORT + FILTER

### ISSUE THREAD

**Issue by ohardy** [arangodb/arangodb#5749]
Hi,

Version: 3.3.9
RocksDB
In cluster

This query is used to do a SORT + FILTER ~= 2.7s. I have indexes:
- _key
- _from, _to
- result.score
- _from, result.score

```
LET id = 'sample/86177031'

FOR edge IN data
    FILTER edge._from == id
    SORT edge.result.score
    
    LIMIT 1000
    
    RETURN edge._to
```

With FILTER:
```
By   Type   Collection  Unique   Sparse   Selectivity   Fields               Ranges
11    edge   data           false       false       n/a               [ `_from` ]       (edge.`_from` == "sample/86177031")
```

Without FILTER:
```
By   Type    Collection  Unique   Sparse   Selectivity   Fields               Ranges
9   skiplist   data           false       false       n/a               [ `result.score` ]   *
```

The problem appear too, if I use `FOR doc, edge IN OUTBOUND id data` on it on do FILTER and SORT on the edge.

**Comment by Simran-B** [comment]
Is your skiplist index defined over the fields `["from", "result.score"]` or `["_from", "result.score"]`?

Looks like the edge index is favored over the skiplist index. For vertex-centric indices, it is up to the optimizer to decide whether the edge index or any vertex-centric index is assumed to be better.

Regarding filter/sort in traversals, see my answer in https://github.com/arangodb/arangodb/issues/5728

**Comment by ohardy** [comment]
It was a typo, `["_from", "result.score"]`, I updated original message. I have read your answer. If I understand good, I have no solution to use my index with FILTER + SORT ?

**Comment by Simran-B** [comment]
A regular skiplist index (non-vertex centric) can't be utilized in a post-traversal filter. A vertex-centric may be used over the edge index, but it depends on the data distribution etc. Can you check if skiplist index over fields `["from", "result.score"]` is used with the `_from` and `_to` attributes moved to user attributes? You could use a query as follows for that:

```
FOR edge IN data
  UPDATE MERGE(edge, { from: edge._from, to: edge._to }) IN data
```

Then check the execution plan with the slightly modified query:

```
LET id = 'sample/86177031'

FOR edge IN data
    FILTER edge.from == id
    SORT edge.result.score
    
    LIMIT 1000
    
    RETURN edge.to
```

**Comment by vinaypyati** [comment]
Hi @ohardy ,

Did you have a chance to try the query suggestions by Simran? 

Thanks!

**Comment by OmarAyo** [comment]
Hi @ohardy 

We haven't heard back from you recently. I am going ahead and close this ticket.

Please feel free to reopen it at any time by adding a new comment

Best,
