### ISSUE TITLE
HTTP API /api/document - parameter silent will be ignored (3.2)

### ISSUE THREAD

**Issue by mpv1989** [arangodb/arangodb#5750]
## My Environment

* __ArangoDB Version__:        3.2

## Component, Query & Data

__Affected feature__:
HTTP API

## Steps to reproduce

1. Create a collection
2. Call [POST /_api/document/{collection}](https://docs.arangodb.com/3.2/HTTP/Document/WorkingWithDocuments.html#create-document) with `silent` == `true`

__Problem__:
The `silent` parameter for every route under `/_api/document` will be ignored. The document meta information will always be displayed.

__Expected result__:
I expect the result described in the docs:
> silent (optional): If set to true, an empty object will be returned as response. No meta-data will be returned for the created document. This option can be used to save some network traffic.

**Comment by maxkernbach** [comment]
Closing as fixed. The `silent` parameter works as expected in the latest release 3.4.5. 

`silent` parameter use:
```
curl -X POST --header 'accept: application/json' --data-binary @- --dump - http://root@localhost:8529/_api/document/products?silent=true <<EOF
{ "Hello": "World1" }
EOF

HTTP/1.1 202 Accepted
X-Content-Type-Options: nosniff
Server: ArangoDB
Connection: Keep-Alive
Content-Type: application/json; charset=utf-8
Content-Length: 2
```

**no** `silent` parameter in use:
```
curl -X POST --header 'accept: application/json' --data-binary @- --dump - http://root@localhost:8529/_api/document/products <<EOF
{ "Hello": "World1" }
EOF

HTTP/1.1 202 Accepted
X-Content-Type-Options: nosniff
Location: /_db/_system/_api/document/products/32809
Etag: "_Yr5Ze1O---"
Server: ArangoDB
Connection: Keep-Alive
Content-Type: application/json; charset=utf-8
Content-Length: 60

{"_id":"products/32809","_key":"32809","_rev":"_Yr5Ze1O---"}
```
