### ISSUE TITLE
Foxx Microservice module.context.collection returns null for existing collection

### ISSUE THREAD

**Issue by KevinExtremo** [arangodb/arangodb#5879]
## My Environment

* __ArangoDB Version__:        3.3.10
* __Storage Engine__:             
* __Deployment Mode__:       Single Server
* __Configuration__:               None
* __Infrastructure__:               own
* __Operating System__:        Ubuntu 16.02
* __Used Package__:              Ubuntu.deb

## Component, Query & Data

__Affected feature__: Foxx

__Dataset__:
If you create a collection using `db._createDocumentCollection` and try to fetch it using `module.context.collection` right after, instead of returning the ArangoCollection, it returns `null`.
This does not happen if you use `db._collection`, where it successfully returns the expected ArangoCollection.

Example code:
```
const testCollectionName = module.context.collectionName('test');
const testCollection = db._createDocumentCollection(testCollectionName);
const testCollectionFromModule = module.context.collection(testCollectionName); // null
const testCollectionFromDatabase = db._collection(testCollectionName); // ArangoCollection
```

## Steps to reproduce

1. Create a Foxx microservice that creates a collection
2. Fetch the collection right after using module.context.collection
3. Be sad about null instead of ArangoCollection

__Problem__: It should return the ArangoCollection since all of it is synchronous.

__Expected result__: ArangoCollection

**Comment by Simran-B** [comment]
`collectionName()` prefixes the given name with the collectionPrefix for this service, which is derived from the service's mount point, e.g. `/my-foxx` becomes `my_foxx`.

`module.context.collectionName('test')` returns the string `my_foxx_test`. A collection with that name is created and reference stored in `testCollection`.

`module.context.collection(testCollectionName)` passes the given name to collectionName(), then looks up the collection with the prefixed name. That means, it will try to return a reference for a collection `my_foxx_my_foxx_test` which does not exist. You have to use `db._collection()` if you want to find a collection by name which is already prefixed with the collection prefix.

Relevant documentation:
- https://docs.arangodb.com/3.3/Manual/Foxx/Context.html#collection
- https://docs.arangodb.com/3.3/Manual/Foxx/GettingStarted.html#accessing-collections

**Comment by maxkernbach** [comment]
Hi @KevinExtremo 

has the previous comment of Simran been helpful to you?

**Comment by KevinExtremo** [comment]
Yes. Thank you very much. It makes sense :) It was not clear to me that one had a sideeffect over the other and produced the prefixed name itself.

**Comment by maxkernbach** [comment]
Thanks for your reply. I am closing this issue as solved.
