### ISSUE TITLE
Database icons in web interface are not placed correctly

### ISSUE THREAD

**Issue by ryanhaney** [arangodb/arangodb#5943]
## My Environment

* __ArangoDB Version__:        3.3.12

* Chrome 67

## Component, Query & Data

__Affected feature__:
Arango web interface

## Steps to reproduce

1. Login to _SYSTEM database via web interface
2. Click `Databases` in the left navigation menu

![image](https://user-images.githubusercontent.com/1445619/43017535-751ee2d0-8c24-11e8-808f-5d6810a76ac3.png)

**Comment by sleto-it** [comment]
Hi,

Just a quick message to inform that v.3.3.14, which contains the fix for this problem, has been released

I am going ahead and closing this issue now. Please comment, if needed, and we will reopen it

Thanks again for reporting this bug,
