### ISSUE TITLE
Race condition when reading request from unix socket

### ISSUE THREAD

**Issue by mpoeter** [arangodb/arangodb#5974]
## My Environment
* __ArangoDB Version__:       3.3.12 / self-compiled devel branch
* __Used Package__:              official Docker library

We use the official Docker image and use the feature that the entrypoint.sh executes a custom `init.js` file to perform some initial setup steps. We found, that from time to time this setup code crashes at different points with the error "Method Not Allowed". Trace log messages revealed that there is a race condition that corrupts readBuffer for the request:
```
2018-07-24T17:37:32Z [19143] TRACE Compacting 0x7f6022181690 thread: 140050457835264
2018-07-24T17:37:32Z [19143] TRACE HTTP READ FOR 0x7f6022181690 thread: 140050772526848: \x00UT /_db/_system/_api/user/ake/database/test HTTP/1.1\r\nHost: localhost\r\nConnection: Keep-Alive\r\nUser-Agent: ArangoDB\r\nAccept-Encoding: deflate\r\nAuthorization: Basic cm9vdDo=\r\nContent-Length: 14\r\n\r\n
2018-07-24T17:37:32Z [19143] WARNING got corrupted HTTP request '\x00UT /_'
```
The  `Compacting ...` message is an additional log message that I put into `HttpCommTask::compactify` to debug this issue. It shows that two threads are operating on the same `HttpCommTask` instance.

However, I could only reproduce this issue with a unix socket connection, not with TCP. I just wanted to create a PR with the bugfix, only to find that it has been fixed a few days ago (#5914).

Do you have a timeline for the next point release that contains this fix?

**Comment by jsteemann** [comment]
@mpoeter : I think this has been fixed in 3.3.13 (not yet released), via 1b8d8e728bf5aa11d4a8f1361eb625f3e528a20f.
As you are self-compiling, can you check if that commits fixes your problem? Thanks!

**Comment by mpoeter** [comment]
Yes, that fixes the problem. In fact, I debugged the 3.3.12 code base and applied the same changes. I wanted to create a PR with the fix, only to find that you were faster. :+1: 

Do you a timeline when 3.3.13 will be released?

**Comment by jsteemann** [comment]
We are currently collecting some further bugfixes for 3.3, but the idea is to start the release build at some point this week. Which would mean an official release next week if everything works well.

**Comment by vinaypyati** [comment]
Hi @mpoeter,

If any further questions on the topic please feel free to reopen the issue. 
Thanks.

**Comment by mpoeter** [comment]
Sounds good, thanks!
