### ISSUE TITLE
Update tries to write non-existing document, query returns it too

### ISSUE THREAD

**Issue by matcho** [arangodb/arangodb#5976]
## My Environment

* __ArangoDB Version__:        3.3.11
* __Storage Engine__:            RocksDB
* __Deployment Mode__:       Single Server
* __Infrastructure__:               own
* __Operating System__:        Debian 9
* __Used Package__:              Debian or Ubuntu .deb

## Component, Query & Data

__Affected feature__:
AQL query whatever the driver

__AQL query 1 (update attempt)__:
```
for s in z_search_full_txt_pn
	update s with { updated: false } in z_search_full_txt_pn
```

__AQL explain__:
```
Query string:
 for s in z_search_full_txt_pn
 	update s with { updated: false } in z_search_full_txt_pn

Execution plan:
 Id   NodeType                     Est.   Comment
  1   SingletonNode                   1   * ROOT
  3   CalculationNode                 1     - LET #3 = { "updated" : false }   /* json expression */   /* const assignment */
  2   EnumerateCollectionNode   1459843     - FOR s IN z_search_full_txt_pn   /* full collection scan */
  4   UpdateNode                      0       - UPDATE s WITH #3 IN z_search_full_txt_pn

Indexes used:
 none

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   remove-data-modification-out-variables
  3   patch-update-statements

Write query options:
 Option                   Value
 ignoreErrors             false
 waitForSync              false
 nullMeansRemove          false
 mergeObjects             true
 ignoreDocumentNotFound   false
 readCompleteInput        false
 useIsRestore             false
 consultAqlWriteFilter    false
```

__AQL query 2 (update ignoring errors)__:
```
for s in z_search_full_txt_pn
	update s with { updated: false } in z_search_full_txt_pn OPTIONS { ignoreErrors: true }
```

__AQL query 3 (find failing document)__:
```
for s in z_search_full_txt_pn
    FILTER s.updated == true
    RETURN s._key
```

__AQL explain__:
```
Query string:
 for s in z_search_full_txt_pn
     FILTER s.updated == true
     RETURN s._key

Execution plan:
 Id   NodeType                     Est.   Comment
  1   SingletonNode                   1   * ROOT
  2   EnumerateCollectionNode   1459843     - FOR s IN z_search_full_txt_pn   /* full collection scan, projections: `_key`, `updated` */
  3   CalculationNode           1459843       - LET #1 = (s.`updated` == true)   /* simple expression */   /* collections used: s : z_search_full_txt_pn */
  4   FilterNode                1459843       - FILTER #1
  5   CalculationNode           1459843       - LET #3 = s.`_key`   /* attribute expression */   /* collections used: s : z_search_full_txt_pn */
  6   ReturnNode                1459843       - RETURN #3

Indexes used:
 none

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   move-calculations-up-2
  4   move-filters-up-2
  5   reduce-extraction-to-projection
```

__AQL query 4 (return failing document)__:
```
for s in z_search_full_txt_pn
    FILTER s._key == '10681114540'
    RETURN s
```

__AQL explain__:
```
Query string:
 for s in z_search_full_txt_pn
     FILTER s._key == '10681114540'
     RETURN s

Execution plan:
 Id   NodeType        Est.   Comment
  1   SingletonNode      1   * ROOT
  6   IndexNode          1     - FOR s IN z_search_full_txt_pn   /* primary index scan */
  5   ReturnNode         1       - RETURN s

Indexes used:
 By   Type      Collection             Unique   Sparse   Selectivity   Fields       Ranges
  6   primary   z_search_full_txt_pn   true     false       100.00 %   [ `_key` ]   (s.`_key` == "10681114540")

Optimization rules applied:
 Id   RuleName
  1   use-indexes
  2   remove-filter-covered-by-index
  3   remove-unnecessary-calculations-2
```

__Dataset__:
1.5 million documents having a boolean property `updated`.

__Indexes__:
1 skiplist index on `clean` field
1 hash index on `id, referential, type, clean` fields
No index on `updated` field

## Steps to reproduce

1. Try to update all dataset without condition (query 1); fails with "ArangoError: AQL: document not found (while executing)"
2. Try to update ignoring errors (query 2); all documents are updated but one
3. Find the document key querying the `updated` field value (query 3) => returns a _key
4. Find the document with this _key (query 4) (either with AQL filter on _key field, or exploring the collection with aardvark) => the document does not exist

__Problem__:
Update statement and AQL query on the `updated` field see a document that does not exist for real…

__Expected result__:
Non existing documents should… not exist :)

**Comment by Simran-B** [comment]
Does the error in step 1 occur reproducibly with your dataset? Does it also occur if you only use a subset of about 10k documents for instance?

Does it still occur if you create a new collection and copy / import the data to that, then run the query against the new collection?

Please provide a data sample or we can only guess how it looks like.

**Comment by matcho** [comment]
Error in step 1 occurs reproducibly, yes.

It occurs with a subset too, even with the smallest one : filtering on `updated == true` (this filter returns only the document provoking the error) and UPDATEing afterwards fails, even though it is updating only one document.

If I truncate then regenerate the dataset, error in step 1 disappears for a while (a few executions of step 1 across many days) then suddenly occurs again one day; did not manage to find out what had changed to make the bug reappear…

**Comment by matcho** [comment]
Note: after truncating the collection, aardvark now shows "18,446,744,073,709,551,616 doc(s)"
(guess it's 2^64)

![capture d ecran de 2018-07-25 13-58-10](https://user-images.githubusercontent.com/2674752/43199639-e9f9e2b6-9012-11e8-8e41-ead89b3a28d7.png)

**Comment by Simran-B** [comment]
Were the datafiles upgraded from e.g. 3.2 to 3.3? I encountered a similar issue once, with no documents being in the collection but UI showing a huge amount. It was a testing instance which underwent several datafile upgrades.

What workload did you run that eventually made the error re-appear?

**Comment by matcho** [comment]
The database has been existing from 3.1 and was gradually upgraded, but this specific collection was created under 3.3.11.

After deleting / recreating the collection, everything works fine… for now.

The workflow on this collection is triggered every night :
 - update one field in all documents (query 1 from OP) using UPDATE
 - update some documents (from 0 to 1.6M) using UPSERT

**Comment by AntoineAA** [comment]
Hi,
I'm working on the same dataset (mentioned by @matcho).
The AQL document not found error occurred again, after 2 runs without any error.

**Comment by graetzer** [comment]
ok, first of all are you sure you had this dataset continuously in rocksdb since 3.1 ? Or did you dump and restore it in between?

We did have an issue before arangodb 3.3.13 where large transactions, which triggered an _intermediate commit_, could lead to inconsistent data.

**Comment by matcho** [comment]
This collection was created under 3.3.11 using RocksDB. It was never dumped / restored, but it was truncated and repopulated many times without deleting / recreating the collection.

The problem has not happened since a long time, probably thanks to 3.3.13 but I'm not certain.

I guess it's OK now, thanks for everything !
