### ISSUE TITLE
Curiosity: deviation from GoT lore in Traversal figure in documentation. 

### ISSUE THREAD

**Issue by fauskanger** [arangodb/arangodb#5989]
### Curious mistake in documentation figure

___NOT___ a big deal

## Steps to reproduce

1. Find family tree in [tutorial on Graph Traversal][t] or look at embedded image below.
2. Read _A Game of Thrones_, or watch Game of Thrones season 1 episode 1
3. Compare

__Problem__:
Jon Snow is presented as son of Catelyn Stark, and not of Ned Stark. Everyone knows that Jon is bastard son of Ned.

![](https://docs.arangodb.com/3.3/AQL/Tutorial/ChildOf_Graph.png)

Mentally running the following query on the figure of family relationships

    FOR c IN Characters
    FILTER c.name == "Jon"
    FOR v IN 1..1 OUTBOUND c ChildOf
        RETURN v.name

Outputs

    [
        "Catelyn"
    ]

__Expected result__:

Instead, according to GoT lore, the expected output should be

    [
        "Ned"
    ]

__NOTE__: the `data` variable in the example is «correct» so the query would actually yield _Ned_, but this is not reflected in the figure. 

I'd like to add that I appreciate the use of a well-known family like Lannisters and Starks to explain parental hierarchy queries, and the need for using `DISTINCT` to return Joffrey only once in list of grand-children of Tywin.

[t]: https://docs.arangodb.com/3.3/AQL/Tutorial/Traversal.html#childof-relations

**Comment by fauskanger** [comment]
I took the liberty to fix the image:

[![][u]][u]

Can be downloaded at [this location][u] until July 25 2019

[u]: https://uiano-my.sharepoint.com/:i:/g/personal/thomaf05_uia_no/EYnJYkxMtg1CksBKBOHWOTYBy2_mRaWgShb36emwyZKaJg?e=GuWPsv

**Comment by fauskanger** [comment]
Added PR #5990

**Comment by Simran-B** [comment]
@MrPieces Did we do this intentionally (e.g. not knowing his father as of season 1 episode 1) or is it a mistake?

**Comment by MrPieces** [comment]
@Simran-B well, assuming we only have the knowledge of Season 1 & Episode 1, we made a mistake. @fauskanger is correct, that Jon Snow is Neds bastard son based on the knowledge of the first seasons.

**Comment by fauskanger** [comment]
The dataset in the tutorial, i.e. the `let data = (...)`-variable, has Jon registered as ChildOf Ned. Also in the simplified, textual mapping at the top of the tutorial Ned is father of Jon. 

(Something like

    ...
        Bran -> Ned
        Jon -> Ned
        Robb -> Catelyn
    ...

The only discrepancy, AFAICT, is the image (used twice). The only change in my pull request is adding the modified image and using it instead of the old in the tutorial docs.

(As a last note, I've seen all seasons but was unsure on how deep into the story to go to avoid spoilers.)

**Comment by Simran-B** [comment]
I see, I accidentally swapped Ned and Catelyn in the image only. Modified your PR to overwrite the original PNG as there is no point in keeping the wrong one. Thanks for spotting and fixing!

**Comment by fauskanger** [comment]
You're welcome, and thank you for the great database 👍
