### ISSUE TITLE
Regression in OPTIONS argument

### ISSUE THREAD

**Issue by ggendel** [arangodb/arangodb#5992]
## My Environment

* __ArangoDB Version__:       3.3.12
* __Storage Engine__:            RocksDB
* __Deployment Mode__:       Single Server
* __Configuration__:               Basic operation
* __Infrastructure__:               Own
* __Operating System__:        OpenSuse Leap 42
* __Used Package__:              ArangoDB repository for OpenSuse 13.2

## Component, Query & Data

__Affected feature__:
AQL query using web interface

__AQL query (if applicable)__:
WITH pminprogress,pmlibtype,pmattic,pmlibrary,pmconfig,pmvariant,pmsite,pmproject,pmpath,pmuser,pmworkspace,pmproxy,pmrelease,pmvartype FOR v,e,p IN 1..50 OUTBOUND 'pmconfig/31165912' pm_content OPTIONS {uniqueVertices:"global",bfs:true}

__AQL explain (if applicable)__:

__Dataset__:
None needed

## Steps to reproduce

1. Just run this AQL
2. 
3. 

__Problem__:
ArangoError 1501: AQL: syntax error, unexpected end of query string near '}' at position 1:237 (while parsing)
If I remove the OPTIONS clause it runs.  This AQL worked in 3.2.

__Expected result__:
No syntax error.

**Comment by jsteemann** [comment]
This is not a regression, but the AQL query is wrong. It also does not work when the `OPTIONS ...` part is omitted.
The reason is that the query given ends on the `FOR` part (the `OPTIONS` clause belongs to the `FOR` part of the query).
What is missing is a `RETURN` node or a data-modification node after the `FOR`.

Wrong syntax:
```
WITH pminprogress,pmlibtype,pmattic,pmlibrary,pmconfig,pmvariant,pmsite,pmproject,pmpath,pmuser,pmworkspace,pmproxy,pmrelease,pmvartype FOR v,e,p IN 1..50 OUTBOUND 'pmconfig/31165912' pm_content OPTIONS {uniqueVertices:"global",bfs:true}
```
Also wrong syntax:
```
WITH pminprogress,pmlibtype,pmattic,pmlibrary,pmconfig,pmvariant,pmsite,pmproject,pmpath,pmuser,pmworkspace,pmproxy,pmrelease,pmvartype FOR v,e,p IN 1..50 OUTBOUND 'pmconfig/31165912' pm_content
```
Parses ok:
```
WITH pminprogress,pmlibtype,pmattic,pmlibrary,pmconfig,pmvariant,pmsite,pmproject,pmpath,pmuser,pmworkspace,pmproxy,pmrelease,pmvartype FOR v,e,p IN 1..50 OUTBOUND 'pmconfig/31165912' pm_content OPTIONS {uniqueVertices:"global",bfs:true} RETURN [v, e, p]
```

**Comment by ggendel** [comment]
You are absolutely correct.  The conversion from ES5 to ES6 had an error in it.  All is well in the world again.
