### ISSUE TITLE
Cluster web UI reporting 0 Coordinators and 0 DB Servers

### ISSUE THREAD

**Issue by voutilad** [arangodb/arangodb#5993]
## My Environment

* __ArangoDB Version__:        3.3.12 community
* __Storage Engine__:             MMFiles
* __Deployment Mode__:       Cluster
* __Configuration__:               Manual cluster configuration using 3 hosts each running a DB, Coordinator, and Agency instance
* __Infrastructure__:               Google Compute Engine
* __Operating System__:        Ubuntu 18.04 (also tested on 16.04 and seeing same thing)
* __Used Package__:              Ubuntu .deb

## Component, Query & Data

__Affected feature__:
Web UI for cluster shows a count of 0 Coordinators and 0 Databases. 

__AQL query (if applicable)__: n/a

__AQL explain (if applicable)__: n/a

__Dataset__:
None needed

## Steps to reproduce
1. Provision 3 GCE instances
2. Install ArangoDB using deb files
3. Remove the installed ArangoDB database files
4. Configure and run 3 instances of `arangod` on each machine. One for the agent, one for db, and one for the coordinator configuring the cluster and endpoints.
5. Set a root password
6. Log into the web UI on one of the coordinators

I'm using systemd unit files for starting and running `arangod` and can share them if needed, but since this seems to work fine locally in Virtualbox using the same files I'm not sure it's related. This could be an environmental thing related to GCE but not sure if anyone has any ideas.

__Problem__:
Seeing 0 reported for both number of coordinators and database servers.
<img width="1059" alt="screen shot 2018-07-25 at 15 58 21" src="https://user-images.githubusercontent.com/9891346/43224389-154b5b5a-9024-11e8-9f6c-cf2b86a7dd4f.png">

Looking at the xhr in the browser, I can see a request to my coordinator (e.g. `/_db/_system/_admin/cluster/numberOfServers?_=1532548695426`) returning this data:
```json
{"numberOfCoordinators":null,"numberOfDBServers":null,"cleanedServers":[],"error":false,"code":200}
```

Requests to the health API endpoint (e.g. `/_db/_system/_admin/cluster/health?_=1532548695423`) return:
```json
{"Health":{"AGNT-084096a2-6016-44ba-83d0-7265bc256b6d":{"Endpoint":"tcp://arangodb-2:5001","Role":"Agent","CanBeDeleted":false},"AGNT-e03edf4e-a804-4742-833b-efef9aab983d":{"Endpoint":"tcp://arangodb-3:5001","Role":"Agent","CanBeDeleted":false},"AGNT-07581287-933d-4323-a6d1-415f416573f6":{"Endpoint":"tcp://arangodb-1:5001","Role":"Agent","CanBeDeleted":false}},"ClusterId":"5d37b523-3237-4cda-a853-eaef327d3937","error":false,"code":200}
```

Getting no results on the Nodes screen as well.
<img width="1074" alt="screen shot 2018-07-25 at 15 58 29" src="https://user-images.githubusercontent.com/9891346/43224395-17f22c30-9024-11e8-8e95-62598a59b922.png">

System is operational otherwise. Databases, collections, and documents can be created. They get properly replicated around the cluster as well.

I'm configuring the system via an Ansible playbook I wrote and have tested the same configuration locally on Virtualbox hosts using Vagrant. On those hosts, it works fine. I'm not sure if this is an environmental thing 

__Expected result__:
The cluster page should report 3 coordinators and 3 db instances. The nodes page should show each coordinator and db instance.

**Comment by vinaypyati** [comment]
Hi @voutilad, 

Thank you for opening an issue.  Can you please share us the commands of all instances that you use to configure the cluster manually?

Thanks!

**Comment by voutilad** [comment]
I'm starting them with `systemd` unit files looking like:

```INI
[Unit]
Description=Arangodb Database Service
Wants=arangodb-agent.service
Requires=disable-thp.service network-online.target
After=disable-thp.service network-online.target

[Service]
User=arangodb
LimitNOFILE=16184
Environment=GLIBCXX_FORCE_NEW=1
ExecStart=/usr/sbin/arangod --configuration /etc/arangodb3/arangodb-db.conf

[Install]
WantedBy=multi-user.target
```

For config files (note that I've scrubbed my actual `JWT` and replaced with `ABCDEFG1234567890`):

### Agent
```INI
# ArangoDB configuration file
#
# Documentation:
# https://docs.arangodb.com/latest/Manual/Administration/Configuration/
#
uid = arangodb
gid = arangodb
pid-file = /var/run/arangdb-agent.pid

[server]
endpoint = tcp://arangodb-1:5001
jwt-secret = ABCDEFG1234567890
authentication = true
threads = 0
statistics = true

[agency]
my-address = tcp://arangodb-1:5001
endpoint = tcp://arangodb-1:5001
endpoint = tcp://arangodb-2:5001
endpoint = tcp://arangodb-3:5001
size = 3
activate = true
supervision = false

[database]
directory = /var/lib/arangodb3/agency

[javascript]
startup-directory = /usr/share/arangodb3/js
app-path = /var/lib/arangodb3-apps

[log]
level = info
output = file:///var/log/arangodb3/arangodb-agent.log
output = syslog://daemon/arangodb-agent
```

### Coordinator
```INI
# ArangoDB configuration file
#
# Documentation:
# https://docs.arangodb.com/latest/Manual/Administration/Configuration/
#
uid = arangodb
gid = arangodb
pid-file = /var/run/arangdb-coord.pid

[server]
endpoint = tcp://arangodb-1:8529
jwt-secret = ABCDEFG1234567890
authentication = true
threads = 0
statistics = true

[cluster]
my-address = tcp://arangodb-1:8529
my-role = COORDINATOR
agency-endpoint = tcp://arangodb-1:5001
agency-endpoint = tcp://arangodb-2:5001
agency-endpoint = tcp://arangodb-3:5001

[database]
directory = /var/lib/arangodb3/coordinator
[javascript]
startup-directory = /usr/share/arangodb3/js
app-path = /var/lib/arangodb3-apps

[log]
level = info
output = file:///var/log/arangodb3/arangodb-coord.log
output = syslog://daemon/arangodb-coord
```

### Database
```INI
# ArangoDB configuration file
#
# Documentation:
# https://docs.arangodb.com/latest/Manual/Administration/Configuration/
#
uid = arangodb
gid = arangodb
pid-file = /var/run/arangdb-db.pid

[server]
endpoint = tcp://arangodb-1:5002
jwt-secret = ABCDEFG1234567890
authentication = true
threads = 0
statistics = true

[cluster]
my-address = tcp://arangodb-1:5002
my-role = PRIMARY
agency-endpoint = tcp://arangodb-1:5001
agency-endpoint = tcp://arangodb-2:5001
agency-endpoint = tcp://arangodb-3:5001

[database]
directory = /var/lib/arangodb3/production-db

[javascript]
startup-directory = /usr/share/arangodb3/js
app-path = /var/lib/arangodb3-apps

[log]
level = info
output = file:///var/log/arangodb3/arangodb-db.log
output = syslog://daemon/arangodb-db
```

**Comment by voutilad** [comment]
Version `3.3.13 Community Edition` also has the same issue.

**Comment by voutilad** [comment]
Thanks. I'll see if I can test this out this week.

**Comment by vinaypyati** [comment]
Hi @voutilad,

Just a quick follow up. Did you have a chance to test this issue on ArangoDB RC3? Looking forward to your feedback.

Thanks!

**Comment by voutilad** [comment]
I did a quick test using the `arangodb` starter utility using 3.4.0 Community Edition RC4 on Ubuntu 18.10 in GCP and things look good. I see what I'd expect for a 3 node cluster. Time permitting I'll test using my production 3.3 config where we start each service individually using `arangod` (not `arangodb`).

<img width="1496" alt="screen shot 2018-11-16 at 10 56 16 am" src="https://user-images.githubusercontent.com/9891346/48632463-f2076980-e98e-11e8-8f8a-649803267a92.png">
<img width="1493" alt="screen shot 2018-11-16 at 10 56 23 am" src="https://user-images.githubusercontent.com/9891346/48632466-f3d12d00-e98e-11e8-9c13-f1e52482ce65.png">


Strangely, trying that HTTP endpoint I tried in my original issue post (`/_db/_system/_admin/cluster/numberOfServers`), I still see a JSON response that looks strange:
```json
{"numberOfCoordinators":null,"numberOfDBServers":null,"cleanedServers":[],"error":false,"code":200}
```

Is that an issue or is that API endpoint deprecated? Or does it not make sense in the context of a coordinator?

**Comment by dothebart** [comment]
`numberOfServers` is only documented internally in its definition place https://github.com/arangodb/arangodb/blob/devel/js/actions/api-cluster.js#L591 since its not part of the official API.

**Comment by maxkernbach** [comment]
Hi @voutilad,

did you already have a chance to check the UI using 3.4 with your 3.3 production config? As already stated in the previous message `/_db/_system/_admin/cluster/numberOfServers` is not part of the official API.

Can we consider this issue solved?

**Comment by voutilad** [comment]
I'd say consider it resolved. I'm not sure when I'll be able to update our production playbooks to and test using our current config.
