### ISSUE TITLE
edge can't be inserted before vertix

### ISSUE THREAD

**Issue by sirpy** [arangodb/arangodb#6011]
i'm using python-arango
If I try to add an edge before i add the vertices it is not inserted.
this seems to be the result from the http interface, Document Not Found Error.
1. Is it possible to add edges without adding vertices first?
2. Is it possible to convert a regular collection to an edge collection?

**Comment by SanthoshMurru** [comment]
Does it make sense adding edge before Vertex ? As per my view only if the vertex is created then only go for edge creation.

For ex : If we allow arango to create edge before Vertex, and for some reason if the vertex insertion is failed and edge remains in database without proper vertex there will be no relation drawn for those edges.

So, we should handle our logic using the arango transaction to insert vertex first and then go for edge or do nothing.

**Comment by Simran-B** [comment]
The low level document API as well as AQL allow to insert edges with _from and _to attributes that refer to non-existing documents. The vertex collections don't even have to exist. The edge collection you insert into must exist however.

You can try to use the driver methods to handle documents / vertices for inserting edges and see if that circumvents safeguards that are supposed to avoid dangling edges (e.g. through the general graph API, which does check if the vertices exist). Or fallback to AQL, which should work with any driver.

Regarding converting collections: the type can't be changed once a collection is created. You can create a new edge collection and then copy documents over e.g. using AQL, but be aware: documents in edge collections require a _from and a _to attribute or you will get _edge attribute missing or invalid_ errors. Also note that you can't store _from and _to attributes in document/vertex collections to later copy these documents with edge attributes to an edge collection. These two attributes will be silently removed.

**Comment by sirpy** [comment]
@SanthoshMurru not if you are looking for performance, if I have to check if a vertex exists or insert it and catch the exception for every edge that's a huge performance cost.

@Simran-B thanks, that was suggested also by the python-driver creator, to try and use regular document apis for insertion. i'll try that.
