### ISSUE TITLE
Could "return distinct" use indexes ?

### ISSUE THREAD

**Issue by matcho** [arangodb/arangodb#6028]
## My Environment

* __ArangoDB Version__:        3.3.12
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Infrastructure__:               own
* __Operating System__:        Debian 9
* __Used Package__:              Debian .deb

## Component, Query & Data

__Affected feature__:
AQL query

__AQL query (if applicable)__:
FOR doc IN z_queries
    RETURN DISTINCT doc.client.type

__AQL explain (if applicable)__:
```
Query string:
 FOR doc IN z_queries
     RETURN DISTINCT doc.client.type

Execution plan:
 Id   NodeType                      Est.   Comment
  1   SingletonNode                    1   * ROOT
  2   EnumerateCollectionNode   38158557     - FOR doc IN z_queries   /* full collection scan, projections: `client` */
  3   CalculationNode           38158557       - LET #1 = doc.`client`.`type`   /* attribute expression */   /* collections used: doc : z_queries */
  4   CollectNode               30526845       - COLLECT #3 = #1   /* distinct */
  5   ReturnNode                30526845       - RETURN #3

Indexes used:
 none

Optimization rules applied:
 Id   RuleName
  1   reduce-extraction-to-projection
```

__Dataset__:
Big collection (~40M docs) with a hash (non-sparse) index on `client.type`.

__Problem__:
Returning the DISTINCT values of an indexed field requires a full collection scan, and is very slow on large collections.

__Expected result__:
Maybe the engine could use the index to retrieve quickly all possible values ? In this case the index has a 0.00% selectivity, which should be an advantage (lots and lots of occurrences of very few values)

**Comment by lynic** [comment]
+1  to support this function!  It’s easy just scan the index instead of full document, why not do it?

**Comment by matcho** [comment]
Hi.

Any news on this feature ?
It would really be helpful.

Thank you for your consideration.

**Comment by goedderz** [comment]
An index can currently be used to get a projection, as in other places. For example:

```
 Query String (35 chars, cacheable: true):
 FOR d IN col
 RETURN DISTINCT d.attr

Execution plan:
 Id   NodeType          Est.   Comment
  1   SingletonNode        1   * ROOT
  6   IndexNode            0     - FOR d IN col   /* persistent index scan, index only, projections: `attr` */    
  3   CalculationNode      0       - LET #1 = d.`attr`   /* attribute expression */   /* collections used: d : col */
  4   CollectNode          0       - COLLECT #3 = #1   /* distinct */
  5   ReturnNode           0       - RETURN #3

Indexes used:
 By   Name                      Type         Collection   Unique   Sparse   Selectivity   Fields       Ranges
  6   idx_1680421464062296064   persistent   col          false    false       100.00 %   [ `attr` ]   *

Optimization rules applied:
 Id   RuleName
  1   reduce-extraction-to-projection
```

This should result in some speedup. It will still scan all documents.

I don't think what you're suggesting, i.e. emitting all distinct keys without going over all documents, is easily conceivable with RocksDB indexes. Or at least it's not immediately obvious to me. Very basically (sorry for the blatant simplification, it's just to give some perspective), such LSM indexes behave more like a sorted array than a balanced tree. You can find a certain point efficiently with a binary search; but you cannot efficiently skip from one key to the next, if there are multiple entries with the same key in that array.

A possible workaround is to maintain a "linked" collection containing those values. However, allowing document removal in the original collection might get a little painful.

**Comment by matcho** [comment]
OK thank you for the explanation !
