### ISSUE TITLE
Finding out the harddrive-memory-size/consumption of the database

### ISSUE THREAD

**Issue by diddyhsv** [arangodb/arangodb#6030]
## My Environment

* __ArangoDB Version__:        3.3.4
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Configuration__:               Standard
* __Infrastructure__:              ?
* __Operating System__:       MacOS 10.13.4
* __Used Package__:              Homebrew instalation

## Component, Query & Data

__Affected feature__:
<Storage -->

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:

## Steps to reproduce

1. 
2. 
3. 

__Problem__:
Where can I see, how much memory my arangodb-database is using? I can't find the arangodb files anywhere in my finder, and can't find any other way to find out how much space this database is taking on my harddrive.

__Expected result__:
The memory-size of my arangodb database

**Comment by dothebart** [comment]
Hi, 
the homebrew installation will go the regular unix way, and your database ends up in 
`<homebrew-root>/var/lib/arangodb`

**Comment by maxkernbach** [comment]
Hi @diddyhsv,

was the previous comment helpful, did you find the database directory in `<homebrew-root>/var/lib/arangodb`?

**Comment by diddyhsv** [comment]
Kind of. It lead me to the right answer. I now know that the size of my database can be seen by looking at the size of the folder arangodb3-rocksdb, found under usr/local/var/lib/

**Comment by maxkernbach** [comment]
Thanks for your reply, I am closing this issue as solved then.
