### ISSUE TITLE
Foxx service executes much longer for the first time

### ISSUE THREAD

**Issue by blokhinnv** [arangodb/arangodb#6057]
## My Environment

* __ArangoDB Version__:        3.3.4
* __Storage Engine__:             mmfiles
* __Deployment Mode__:       single server
* __Configuration__:               Intel Xeon X5650 @2.67 24 cores, 32GB RAM
* __Infrastructure__:               own
* __Operating System__:        Windows 10

## Component, Query & Data

__Affected feature__:
Foxx, arango query

__AQL query (if applicable)__:
```
LET ids = (FOR ht IN hashtags
            FILTER ht._key == ${h}
            RETURN {"id":ht._id, "seen":ht.seen}
            )


FOR hashtag,e IN ANY ids[0].id myedges
    OPTIONS {bfs: true, uniqueVertices: 'global'}
    LET cosine = e.coccurrence/SQRT(ids[0].seen*hashtag.seen)
    SORT cosine DESC
    LIMIT 100
    RETURN {"cos": cosine, "hashtag":hashtag.name}
```

__Dataset__:
1) Document collection `hashtash` with 3million documents
2) Edges collection `myedges` with 78 million documents

There's a Foxx service, which takes GET parameter, does the query above and returns result of the query.
## Steps to reproduce

1. Call the service once with the parameter I haven't send yet.  
2. Call it again with the same parameter.

__Problem__:
When I do it for the first time, the execution time is much longer, than for the second time. E.g. for the first time it took 53s and I can see that my SSD is loading for 100%.
![image](https://user-images.githubusercontent.com/36994200/43580370-edd093d4-965d-11e8-848b-10d29a73df72.png)
But when I call it just after the first time, it takes just 3s.
![image](https://user-images.githubusercontent.com/36994200/43580427-1dab623c-965e-11e8-9255-c33f1b384cf3.png)

In general, the first time I execute the query is longer than other times. 
At first, I thought that something related to caching, but if I execute the query in web interface with the same param, i can see 'vertex not found' warnings, so there is no caching because of that.
What could it be?

**Comment by Simran-B** [comment]
@blokhinnv If you ensure the collections are already loaded before you access the Foxx endpoint / do your query, what is the response time?

You can load collections via the web interface by clicking on them in the overview:

![image](https://user-images.githubusercontent.com/7819991/43954983-afbd56da-9c9e-11e8-993a-d195374af2ad.png)

It should eventually change to "loaded" status in green. I suspect that the 50 additional seconds are actually the load time of the involved collections. Indexes except the type "persistent" are re-built each time a collection is loaded using the MMFiles storage engine. You may want to switch to RocksDB engine to avoid this, and also allow the dataset to grow larger than the main memory.

**Comment by maxkernbach** [comment]
Hi @blokhinnv,

did you have a chance to load the collections before accessing the Foxx endpoint / executing your query as Simran suggested?

**Comment by maxkernbach** [comment]
Hi @blokhinnv,

I am closing this issue for now since we have not heard back from you recently.
In case the problem persists when loading the involved collections before executing query, please feel free to comment and we will reopen it.
