### ISSUE TITLE
arangosh out of memory trying to iterate of documents

### ISSUE THREAD

**Issue by sirpy** [arangodb/arangodb#6063]
## My Environment
* __ArangoDB Version__:       3.3.14
* __Storage Engine__:             RocksDB 
* __Deployment Mode__:        Single Server
* __Infrastructure__:               own 
* __Operating System__:        Ubuntu 18.04
* __Used Package__:              Debian or Ubuntu .deb

## Component, Query & Data

__Affected feature__:
arangosh 

## Steps to reproduce
I have a vertex collection with 100s millions of nodes
i'm trying to iterate over them like so
var nodes = db.nodes.all()
nodes.setBatchSize(10)
nodes.hasNext()

this results in
```
JavaScript exception in file '/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js' at 99,7: ArangoError 3: out of memory (while executing) (exception location: /var/lib/otherjenkins/workspace/RELEASE__BuildPackages/arangod/RestHandler/RestCursorHandler.cpp:146)
!      throw error;
!      ^
stacktrace: ArangoError: out of memory (while executing) (exception location: /var/lib/otherjenkins/workspace/RELEASE__BuildPackages/arangod/RestHandler/RestCursorHandler.cpp:146)
    at Object.exports.checkRequestResult (/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js:97:21)
    at SimpleQueryAll.execute (/usr/share/arangodb3/js/client/modules/@arangodb/simple-query.js:77:14)
    at SimpleQueryAll.SimpleQuery.count (/usr/share/arangodb3/js/common/modules/@arangodb/simple-query-common.js:381:8)
    at <shell command>:1:7
```

if i add nodes.limit(10) it works, nodes.limit(1000) crashes also

**Comment by dothebart** [comment]
Hi, 
The current situtation here is, that on the server side the whole collection has to be copied into memory so the server can keep the resultsets for the subsequent cursor requests. 
If this exceeds your available resources, it won't work. 

With ArangoDB 3.4 and its streaming cursors, it may become possible. 

You need to split your query in a way that it works with a subset of your collection. This can be done using AQL.

**Comment by dothebart** [comment]
Revalidated with ArangoDB 3.4.0-RC3 which is available for download. 
Said calls will invoke the streaming API and no more OOM should occur.

**Comment by vinaypyati** [comment]
Hi @sirpy,

ArangoDB 3.4.0-RC3 includes a fix for this OOM problem. You can download it from the [download section](https://www.arangodb.com/download-technical-preview/). 

I am going ahead and closing this issue now. Please feel free to comment if the issue persists

Thanks!
