### ISSUE TITLE
arangod: Segmentation fault after AQL query

### ISSUE THREAD

**Issue by Myrlin1** [arangodb/arangodb#6076]
## My Environment

* __ArangoDB Version__:  3.3.13      
* __Storage Engine__: RocksDB            
* __Deployment Mode__: Single Server      
* __Deployment Strategy__: Manual Start  
* __Configuration__: default              
* __Infrastructure__: amd64              
* __Operating System__: Ubuntu 18.04       
* __Used Package__: Reproduced in both Ubuntu .deb and from docker store             

> arangod --version
> 3.3.13
>
> architecture: 64bit
> arm: false
> asan: false
> asm-crc32: true
> assertions: false
> boost-version: 1.62.0
> build-date: 2018-07-26 17:25:40
> build-repository: tags/v3.3.13-0-g92a0c395de
> compiler: gcc [6.3.0 20170406]
> cplusplus: 201103
> debug: false
> endianness: little
> failure-tests: false
> fd-client-event-handler: poll
> fd-setsize: 1024
> full-version-string: ArangoDB 3.3.13 [linux] 64bit, using jemalloc, build tags/v3.3.13-0-g92a0c395de, VPack 0.1.30, RocksDB 5.6.0, ICU 58.1, V8 5.7.492.77, OpenSSL 1.0.2g  1 Mar 2016
> icu-version: 58.1
> jemalloc: true
> maintainer-mode: false
> ndebug: true
> openssl-version: OpenSSL 1.0.2g  1 Mar 2016
> platform: linux
> reactor-type: epoll
> rocksdb-version: 5.6.0
> server-version: 3.3.13
> sizeof int: 4
> sizeof void*: 8
> sse42: false
> unaligned-access: true
> v8-version: 5.7.492.77
> vpack-version: 0.1.30
> zlib-version: 1.2.11

## Component, Query & Data

__Affected feature__:

AQL query using web interface

__AQL query (if applicable)__:

> FOR airport IN airports RETURN airport

__AQL explain (if applicable)__:

> Query string:
> &emsp;FOR airport IN airports RETURN airport
> 
> Execution plan:
> <table>
> <tr>
> <th style="text-align: right">Id</th>
> <th>NodeType</th>
> <th style="text-align: right">Est.</th>
> <th>Comment</th>
> </tr><tr>
> <td style="text-align: right">1</td>
> <td>SingletoneNode</td>
> <td style="text-align:right">1</td>
> <td>* ROOT</td>
> <tr/><tr>
> <td style="text-align: right">2</td>
> <td>EnumerateCollectionNode</td>
> <td style="text-align:right">3375</td>
> <td>&emsp;- FOR airport IN airports   /* full collection scan */</td>
> <tr/><tr>
> <td style="text-align: right">3</td>
> <td>ReturnNode</td>
> <td style="text-align:right">3375</td>
> <td>&emsp;&emsp;- RETURN airport</td>
> <tr/><tr>
> </table>
>
> Indexes used:
> &emsp;none
> 
> Optimization rules applied:
>  &emsp;none

__Dataset__:

This is the dataset provided for the ArangoDB GraphCourse:
- _url_: [https://www.arangodb.com/arangodb_graphcourse_demodata/](url)

- _file_: [airports.txt](https://github.com/arangodb/arangodb/files/2259900/airports.txt)

## Steps to reproduce

1. In web interface, enter query on collection "airports"

__Problem__:
/usr/sbin/arangod crashes, even though it returns the query successfully.  Turned logging up to debug level.  Captured trace logs for performance, mmap, queries.  There was no indication of an error or any warning

When running
`/usr/sbin/arangod --uid arangodb --gid arangodb --pid-file /var/run/arangodb3/arangod.pid --temp.path /var/tmp/arangodb3 --log.foreground-tty true`
I receive 
`[1]    27197 segmentation fault  /usr/sbin/arangod --uid arangodb --gid arangodb --pid-file  --temp.path`

dmesg shows nothing.

I do have a coredump produced from `apport-unpack`, if needed, but it's 674 MB. 

__Alternate use case__:
I am able to run the same query on the same dataset from `arangosh`, with no issues.  Appears to be an issue with the web interface (aardvark?).

**Comment by sleto-it** [comment]
Hi,

Just a quick message to inform that v.3.3.14, which contains the fix for this problem, has been released

I am going ahead and closing this issue now. Please comment, if needed, and we will reopen it

Thanks again for reporting this bug,
