### ISSUE TITLE
When the amount of data reaches a big amount, the performance is not ideal.

### ISSUE THREAD

**Issue by CalicoBox** [arangodb/arangodb#6078]
## My Environment

* __ArangoDB Version__:        3.3.12
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   Manual Start 
* __Configuration__:               
```
[server]
endpoint = tcp://0.0.0.0:8529
storage-engine = rocksdb
authentication = false
threads = 3
[rocksdb]
block-cache-size = 68719476736
write-buffer-size = 536870912
max-write-buffer-number = 5
min-write-buffer-number-to-merge = 2
num-threads-priority-high = 3
num-threads-priority-low = 6
max-background-jobs = 6
```
* __Infrastructure__:                own 
* __Operating System__:        centos 7
* __Used Package__:              SUSE or RedHat .rpm 

## Component, Query & Data

__Affected feature__:
AQL query using web interface

__AQL query (if applicable)__:

```
let res = (for v,r,p in 1..2 any 'v_man/60190ab0acafa668445ff9911de7f0de' graph 'ContactsGraph' options {bfs:true, uniqueVertices:'global'} return v)
return length(res)
```

__AQL explain (if applicable)__:
```
Query string:
 let res = (for v,r,p in 1..2 any 'v_man/60190ab0acafa668445ff9911de7f0de' graph 'ContactsGraph' 
 options {bfs:true, uniqueVertices:'global'} return v)
 return length(res)

Execution plan:
 Id   NodeType          Site       Est.   Comment
  1   SingletonNode     COOR          1   * ROOT
  5   SubqueryNode      COOR          1     - LET res = ...   /* const subquery */
  2   SingletonNode     COOR          1       * ROOT
  3   TraversalNode     COOR        121         - FOR v  /* vertex */ IN 1..2  /* min..maxPathDepth */ ANY 'v_man/60190ab0acafa668445ff9911de7f0de' /* startnode */  GRAPH 'ContactsGraph'
  4   ReturnNode        COOR        121         - RETURN v
  6   CalculationNode   COOR          1     - LET #8 = LENGTH(res)   /* simple expression */
  7   ReturnNode        COOR          1     - RETURN #8

Indexes used:
 By   Type   Collection   Unique   Sparse   Selectivity   Fields        Ranges
  3   edge   e_employ     false    false            n/a   [ `_to` ]     base INBOUND
  3   edge   e_employ     false    false            n/a   [ `_from` ]   base OUTBOUND

Traversals on graphs:
 Id   Depth   Vertex collections   Edge collections   Options                                                Filter conditions
  3   1..2    v_company, v_man     e_employ           bfs: true, uniqueVertices: global, uniqueEdges: path   

Optimization rules applied:
 Id   RuleName
  1   optimize-traversals
```

__Dataset__:

I can roughly describe the size of the data set.

collection A (for doc): 8,951,950 doc(s)

collection B (for doc): 18,535,402 doc(s)

collection C (for edge): 32,580,443 edge(s) 

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. 
2. 
3. 

__Problem__:
the query used 65.903s. 

result:
[
  32364
]

Is this performance normal? How to tune?

__Expected result__:

**Comment by logical-and** [comment]
Similar problem. Any actions we could as users take? If not please let us know if you're going to work on this soon - otherwise we would need to look for another storage engine, since the main goal to use is performance (INSERT, UPDATE, DELETE, much better than MongoDB)

**Comment by Simran-B** [comment]
@CalicoBox Does the following query execute any faster?

```js
let res = (for v,r,p in 1..2 any 'v_man/60190ab0acafa668445ff9911de7f0de' graph 'ContactsGraph' options {bfs:true, uniqueVertices:'global'} return true)
return length(res)
```

**Comment by OmarAyo** [comment]
Hi @CalicoBox 

Just sending a quick followup - did you have the chance to try what Simran suggested in his previous message?

Best,

**Comment by OmarAyo** [comment]
Hi @logical-and 

Did you try what Simran suggested ?

@CalicoBox 
Again, could you provide a quick update. 

Thanks,

**Comment by maxkernbach** [comment]
Since there was no feedback in a while, I am closing this issue for now.

Please feel free to reopen the issue by adding a new comment.

**Comment by CalicoBox** [comment]
Sorry for no reply for ages. I tried  what Simran suggested at that time. Things are looking to be a bit better. But not nearly as good as need. 

I have no ideal if that's the normal performance for arangodb. But it's not ideal for me.

Hope things will get better. Cheers.

**Comment by dothebart** [comment]
Hi, 
question here too, can you provide an example dataset, or some more information on how your data is distributed?

**Comment by vinaypyati** [comment]
Hi @CalicoBox,

Glad that Simran's suggestion worked out a bit better. As dothebart requested, can you please provide us with an example dataset or some detailed information on your data distribution? This will help us investigate more. 

Thanks!

**Comment by mpoeter** [comment]
Isn't this the perfect use case for `COLLECT`?
@CalicoBox How about this:
```
FOR v IN 1..2 ANY 'v_man/60190ab0acafa668445ff9911de7f0de' GRAPH 'ContactsGraph'
  OPTIONS { bfs: true, uniqueVertices: 'global' }
  COLLECT WITH COUNT INTO len
  RETURN len
```

**Comment by maxkernbach** [comment]
Hi @CalicoBox,

did you already have a chance to try the suggested query of mpoeter?
Please share some feedback regarding the latest comments.

**Comment by OmarAyo** [comment]
Hi @CalicoBox 

We have not received any feedback in a while. 
I am closing this issue now. If needed, please feel free to comment and we will reopen this issue.

**Comment by Simran-B** [comment]
Maybe also try the AGGREGATE variant and see if it's more memory friendly. WITH COUNT INTO is optimized however and might work similarly.

```js
FOR v IN 1..2 ANY 'v_man/60190ab0acafa668445ff9911de7f0de' GRAPH 'ContactsGraph'
  OPTIONS { bfs: true, uniqueVertices: 'global' }
  COLLECT AGGREGATE len = LENGTH(1)
  RETURN len
```
