### ISSUE TITLE
Aggregation by field with index takes way too long

### ISSUE THREAD

**Issue by logical-and** [arangodb/arangodb#6108]
## My Environment

* __ArangoDB Version__:        3.3.13
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               default settings
* __Infrastructure__:               own server
* __Operating System__:        Centos
* __Used Package__:              Yum package manager

## Component, Query & Data

__Affected feature__:
Select with indexes

__AQL query (if applicable)__:
```
FOR requestIp IN requestsIps
        
FILTER 
    requestIp.timestamp.from >= 1533606600
COLLECT 
    timestamp = requestIp.timestamp.from
    INTO records
RETURN {
    "ts": timestamp,
    "count": LENGTH(records)
} 
```

__AQL explain (if applicable)__:
```
Query string:
 FOR requestIp IN requestsIps
         
 FILTER 
     requestIp.timestamp.from >= 1533606600
 COLLECT 
     timestamp = requestIp.timestamp.from
     INTO records
 RETURN {
     "ts": timestamp,
     "count": LENGTH(records)
 } 

Execution plan:
 Id   NodeType              Est.   Comment
  1   SingletonNode            1   * ROOT
 10   IndexNode         24476827     - FOR requestIp IN requestsIps   /* persistent index scan */
  5   CalculationNode   24476827       - LET #5 = requestIp.`timestamp`.`from`   /* attribute expression */   /* collections used: requestIp : requestsIps */
  6   CollectNode       19581461       - COLLECT timestamp = #5 INTO records   /* sorted */
  7   CalculationNode   19581461       - LET #7 = { "ts" : timestamp, "count" : LENGTH(records) }   /* simple expression */
  8   ReturnNode        19581461       - RETURN #7

Indexes used:
 By   Type         Collection    Unique   Sparse   Selectivity   Fields                 Ranges
 10   persistent   requestsIps   false    true          0.00 %   [ `timestamp.from` ]   (requestIp.`timestamp`.`from` >= 1533606600)

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   move-calculations-up-2
  4   move-filters-up-2
  5   use-indexes
  6   remove-filter-covered-by-index
  7   use-index-for-sort
  8   remove-unnecessary-calculations-2
```

__Dataset__:
```json
{
  "ipId": "537075667",
  "timestamp": {
    "from": 1527833401,
    "period": 600
  },
  "targetId": "537013913",
  "count": 1
}
```

## Description

The problem is I do have needed index defined, but queries execution time are still way too long (http://prntscr.com/kfui32)

__Attached files__:
* [debugDump (1).zip](https://github.com/arangodb/arangodb/files/2267364/debugDump.1.zip)

## Steps to reproduce

1.  Create `timestamp.from` index
2. Fill the table by 50M records
3. Execute the query

__Problem__:
It takes very very long to be executed. But if I change timestamp condition to exact number (==) it takes up to 10 seconds (http://prntscr.com/kfujjb)

__Expected result__:
Since there is an index the execution time shouldn't be infinite

**Comment by lservini** [comment]
Hi @logical-and 
Thanks for opening. Justo wondering if you can share with us the data model causing this issue.

Thanks

Luigi Servini

**Comment by logical-and** [comment]
It should be in debugDump.zip, or it's not in there?

**Comment by logical-and** [comment]
Ugh, ArangoDB storage is so astonishing, but my employeer is forcing me to switch over to a storage which is not so great in performance (except couple of issues, unfortunately) - like MongoDB or OrientDB. Please help me with these issues so I can keep it up and donate you to share my appreciation of your amazing job!

**Comment by lservini** [comment]
Hi @logical-and 
unfortunately debugDump (1).zip does not contain the full dataset. We would like to reproduce it in a consisten environment. Please, let me know if you can share.
Thanks
Luigi

**Comment by jsteemann** [comment]
The query will build a huge result set because the `COLLECT` captures the entire documents using the `INTO` clause. I suggest changing to use `COLLECT WITH COUNT` as follows:
```
FOR requestIp IN requestsIps        
FILTER 
    requestIp.timestamp.from >= 1533606600
COLLECT 
    ts = requestIp.timestamp.from
    WITH COUNT INTO count
RETURN { ts, count }
```
By the way, `COLLECT` is not using index information for counting, so adding or removing indexes for the `COLLECT` attributes will not change anything. That being said, the index still makes sense for the filtering of course.

**Comment by logical-and** [comment]
Yeap, that a good modification (tried this later), but it doesn't help unfortunately since processing time still huge as well. But if it has index, and a result is aggregated by an index field why it can't know how many records tied to the index?

A significant difference in time between two queries (1.2M more records) - http://prntscr.com/kgahlk

*Query 1:*
```
FOR requestIp IN requestsIps        
FILTER 
    requestIp.timestamp.from >= 1533737400 AND requestIp.timestamp.from <= 1533740400
COLLECT 
    ts = requestIp.timestamp.from
    WITH COUNT INTO count
RETURN { ts, count }
```

*Query 2 (same, but):*
```
requestIp.timestamp.from >= 1533736200 AND requestIp.timestamp.from <= 1533740400
```

**Comment by jsteemann** [comment]
Is it possible that the collection data is bigger than the server's available RAM?
In this case the RocksDB engine will have to perform a lot of disk I/O to load the actual data from disk, which will be a lot slower than if everything were in RAM already. Can you check if that is the case, and can you check if adjusting the startup parameters `--rocksdb.block-cache-size` and/or `--rocksdb.block-cache-shard-bits` helps?
In contrast to what I said, having an index here will help here not only for filtering but also because query will only read from the index and not the entire documents. However, the query will still have look at every index entry in the specified range. Index entries are a sorted by index value, so all entries with the same timestamp will be following one after the other in the index. But the index does not know how many there will still be following, as one index entry does not know anything about the index entries before or after it.

**Comment by logical-and** [comment]
> Is it possible that the collection data is bigger than the server's available RAM?

Aww yeah, pretty much if you're about whole collection size? Or you're about data being extracted to aggregate? Collection size is 9-ish Gb right now, I my preliminary estimation is 10 Gb to be added each day.

> But the index does not know how many there will still be following, as one index entry does not know anything about the index entries before or after it.

Cool, thanks for the explanation :) And from how I'm getting this it loaded documents from disk instead of using of indexes - other how 1.2M records can change dramatically response time from 16 to 191 seconds

**Comment by jsteemann** [comment]
If you see lot of I/O happening while this query is running, then this is a good candidate for the slowness.
Can you try to increase the block cache size, or assign more RAM to it?

**Comment by logical-and** [comment]
I tried settings
```
[rocksdb]
block-cache-size = 42949672960
block-cache-shard-bits = 4
```
, but with no success. What's curious, *Query 1* from https://github.com/arangodb/arangodb/issues/6108#issuecomment-411486606 is being executed last N minutes ... and still not result (with and without ```block-cache-shard-bits` option what value I'm not sure in)

IO - http://prntscr.com/kgbjor

Any thoughts on this - to debug or to "fix" / tune up in another way? It's getting to be black box to me currently :)

**Comment by jsteemann** [comment]
After a server restart the entire collection data is only on disk but not in accessible RAM anymore. Querying the collection will need to load it from disk into RAM first. So I guess the initial queries will take significantly longer after a restart than if the caches are already warmed up. Can you check if there is a lot of I/O going on? If so, then the data is read from disk, which will simply take more time that loading it from RAM. If it's staying like this after the first few queries, then the value for block-cache-shard bits is probably not right.

**Comment by vinaypyati** [comment]
Hi @logical-and,

Just a quick follow up. How things are going? Did you have a chance to read jsteemann's latest comments? Please let us know your feedback!

Thanks!

**Comment by maxkernbach** [comment]
Hi @logical-and,

I am closing this issue for now since we have not heard back from you in a while.
Please feel free to comment and we will reopen this issue.
