### ISSUE TITLE
Compound [persistent] index is not being used if use unexact operators - IN, >=

### ISSUE THREAD

**Issue by logical-and** [arangodb/arangodb#6110]
## My Environment

* __ArangoDB Version__:        3.3.13
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               default settings
* __Infrastructure__:               own server
* __Operating System__:        Centos
* __Used Package__:              Yum package manager

## Component, Query & Data

__Affected feature__:
Select with indexes

__AQL query (if applicable)__:

*Query 1 (exact operators):*
```
FOR requestIp IN requestsIps
FILTER 
    requestIp.ipId == "537075667"
    AND requestIp.timestamp.from == 1527833401
RETURN requestIp
```

*Query 2 (IN):*
```
FOR requestIp IN requestsIps
FILTER 
    requestIp.ipId IN ("537075667")
    AND requestIp.timestamp.from == 1527833401
RETURN requestIp
```

*Query 3 (>=):*
```
FOR requestIp IN requestsIps
FILTER 
    requestIp.ipId == "537075667"
    AND requestIp.timestamp.from >= 1527833401
RETURN requestIp
```

__AQL explain (if applicable)__:

*Query 1 (exact operators):*
```
Execution plan:
 Id   NodeType        Est.   Comment
  1   SingletonNode      1   * ROOT
  6   IndexNode         20     - FOR requestIp IN requestsIps   /* persistent index scan */
  5   ReturnNode        20       - RETURN requestIp

Indexes used:
 By   Type         Collection    Unique   Sparse   Selectivity   Fields                         Ranges
  6   persistent   requestsIps   false    true          4.84 %   [ `ipId`, `timestamp.from` ]   ((requestIp.`ipId` == "537075667") && (requestIp.`timestamp`.`from` == 1527833401))

Optimization rules applied:
 Id   RuleName
  1   use-indexes
  2   remove-filter-covered-by-index
  3   remove-unnecessary-calculations-2
```

*Query 2 (IN):*
```
Execution plan:
 Id   NodeType                  Est.   Comment
  1   SingletonNode                1   * ROOT
  6   NoResultsNode                0     - EMPTY   /* empty result set */
  2   EnumerateCollectionNode      0     - FOR requestIp IN requestsIps   /* full collection scan */
  5   ReturnNode                   0       - RETURN requestIp

Indexes used:
 none

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   remove-unnecessary-filters
  4   remove-unnecessary-calculations
```

*Query 3 (>=):*
```
Execution plan:
 Id   NodeType          Est.   Comment
  1   SingletonNode        1   * ROOT
  6   IndexNode           35     - FOR requestIp IN requestsIps   /* persistent index scan */
  7   CalculationNode     35       - LET #1 = (requestIp.`timestamp`.`from` >= 1527833401)   /* simple expression */   /* collections used: requestIp : requestsIps */
  4   FilterNode          35       - FILTER #1
  5   ReturnNode          35       - RETURN requestIp

Indexes used:
 By   Type         Collection    Unique   Sparse   Selectivity   Fields       Ranges
  6   persistent   requestsIps   false    true          2.80 %   [ `ipId` ]   (requestIp.`ipId` == "537075667")

Optimization rules applied:
 Id   RuleName
  1   use-indexes
  2   remove-filter-covered-by-index
```

__Dataset__:
```json
{
  "ipId": "537075667",
  "timestamp": {
    "from": 1527833401,
    "period": 600
  },
  "targetId": "537013913",
  "count": 1
}
```

## Description

__Attached files__:
[debugDump (3).zip](https://github.com/arangodb/arangodb/files/2267468/debugDump.3.zip)

__Problem__:
As per documentation
> Persistent indexes allow more use cases (e.g. range queries, sorting) than hash indexes. 
it should use indexes on range queries, unexact comparison, etc, but I'm finding it doesn't

__Expected result__:
Quick execution

**Comment by Simran-B** [comment]
The expression in your second query does not do what you think it does. If you check the query explain without optimizations you get the following execution plan:

```
127.0.0.1:8529@_system> db._explain(`FOR requestIp IN test FILTER      requestIp.ipId IN ("537075667")     AND requestIp.timestamp.from == 1527833401 RETURN requestIp`, {}, {optimizer:{rules:["-all"]}})
Query string:
 FOR requestIp IN test FILTER      requestIp.ipId IN ("537075667")     AND requestIp.timestamp.from
 == 1527833401 RETURN requestIp

Execution plan:
 Id   NodeType                  Est.   Comment
  1   SingletonNode                1   * ROOT
  2   EnumerateCollectionNode     22     - FOR requestIp IN test   /* full collection scan */
  3   CalculationNode             22       - LET #1 = false   /* json expression */   /* const assignment */
  4   FilterNode                  22       - FILTER #1
  5   ReturnNode                  22       - RETURN requestIp

Indexes used:
 none

Optimization rules applied:
 none
```

`FILTER false` is certainly not intended. What you actually want is an array literal in the expression:

```
Query string:
 FOR requestIp IN test
 FILTER 
     requestIp.ipId IN ["537075667"] // <-- Array literal with one member (could also be multiple)
     AND requestIp.timestamp.from == 1527833401
 RETURN requestIp

Execution plan:
 Id   NodeType        Est.   Comment
  1   SingletonNode      1   * ROOT
  6   IndexNode          1     - FOR requestIp IN test   /* persistent index scan */
  5   ReturnNode         1       - RETURN requestIp

Indexes used:
 By   Type         Collection   Unique   Sparse   Selectivity   Fields                         Ranges
  6   persistent   test         false    false            n/a   [ `ipId`, `timestamp.from` ]   ((requestIp.`ipId` == "537075667") && (requestIp.`timestamp`.`from` == 1527833401))

Optimization rules applied:
 Id   RuleName
  1   use-indexes
  2   remove-filter-covered-by-index
  3   remove-unnecessary-calculations-2
```

**Comment by logical-and** [comment]
Ouch, right - I missed that out. But what about ```>=```?

**Comment by jsteemann** [comment]
Query 3 actually uses the compound index when I run it with the provided debugDump:
```
Query string:
 FOR requestIp IN requestsIps
 FILTER 
     requestIp.ipId == "537075667"
     AND requestIp.timestamp.from >= 1527833401
 RETURN requestIp

Execution plan:
 Id   NodeType        Est.   Comment
  1   SingletonNode      1   * ROOT
  6   IndexNode          1     - FOR requestIp IN requestsIps   /* persistent index scan */
  5   ReturnNode         1       - RETURN requestIp

Indexes used:
 By   Type         Collection    Unique   Sparse   Selectivity   Fields                         Ranges
  6   persistent   requestsIps   false    true         90.00 %   [ `ipId`, `timestamp.from` ]   ((requestIp.`ipId` == "537075667") && (requestIp.`timestamp`.`from` >= 1527833401))

Optimization rules applied:
 Id   RuleName
  1   use-indexes
  2   remove-filter-covered-by-index
  3   remove-unnecessary-calculations-2
```
In your case it looks like it uses a different index (precisely the one on `ipId`). Which index is used by a query depends on the index selectivity, which in my cases will be different because the debugDump only contains a small fraction of the data that you have. So the index selectivity of my dataset may be completely different than the index selectivity of your dataset, thus the different indexes picked.

However, even with that in mind, the compound index should still produce less results than the other index and should always be preferred for this query. The problem here seems to be that the selectivity estimates for the indexes are only used for queries that query all index attributes by equality, but not for range scans. So the optimizer will use the selectivity estimate for the index on `ipId` (all index attributes queried by equality) but not the selectivity estimate for the compound index (not all index attributes queried by equality). This is less than ideal.

**Comment by logical-and** [comment]
I see your point, but it works in a wrong way in this case since - since it ignores ```timestamp.from``` index part, thus response time becomes very and very long (dozens of minutes, instead of reasonable time (seconds)). I'm attaching the dataset (21 Gb soon). Are you able to download that?

**Comment by jsteemann** [comment]
@logical-and : I personally don't need the dataset. 

I already know the reason that is causing it. The optimizer picks the single-attribute index instead of the compound index, because for the single-attribute index it will use the index selectivity estimate, but for the compound index it doesn't. That makes the compound index compare unfavorably, so the other index is used. This should be fixed by adjusting the internal optimizer heuristics when comparing multiple indexes.

**Comment by logical-and** [comment]
Is there any way sort of a workaround I can use in meantime till it's fixed? The problem is I should use the storage soon, otherwise I'll be forced to switch over to something less cool like Mongo :)
Any undocumented function? :)

**Comment by Simran-B** [comment]
There is a related discussion but there is no way to override the index choices yet: https://github.com/arangodb/arangodb/issues/5728#issuecomment-408888261

**Comment by logical-and** [comment]
Is there any way I could use as workaround? I could use ```IN``` statement to specify exact values if aggregation by index would be fast (#6108 issue). But it isn't on huge datasets like mine - 10M records per day.

**Comment by Simran-B** [comment]
Support for index hints was added to AQL in v3.5.0:
https://www.arangodb.com/docs/stable/aql/operations-for.html#index-hints

Does this solve the issue?

**Comment by logical-and** [comment]
Sorry, I had to choose another storage system because of strict timeline
for implementation.

Thanks, and
Be happy,

And

* \ \*
*     ノ*

**Comment by Simran-B** [comment]
@jsteemann Assigning to you as there might still be something to improve in the optimizer.

**Comment by dothebart** [comment]
with the release of [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) I'm closing this.
