### ISSUE TITLE
Index is not being used if date function is used instead of number

### ISSUE THREAD

**Issue by logical-and** [arangodb/arangodb#6111]
## My Environment

* __ArangoDB Version__:        3.3.13
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               default settings
* __Infrastructure__:               own server
* __Operating System__:        Centos
* __Used Package__:              Yum package manager

## Component, Query & Data

__Affected feature__:
Select with indexes

__AQL query (if applicable)__:

*Query 1 (number):*
```
FOR requestIp IN requestsIps
FILTER 
    requestIp.timestamp.from >= 1527833401
RETURN requestIp
```

*Query 2 (date function):*
```
FOR requestIp IN requestsIps
FILTER 
    requestIp.timestamp.from >= ROUND(DATE_NOW() / 1000)
RETURN requestIp
```

__AQL explain (if applicable)__:

*Query 1 (number):*
```
Execution plan:
 Id   NodeType            Est.   Comment
  1   SingletonNode          1   * ROOT
  6   IndexNode       24476827     - FOR requestIp IN requestsIps   /* persistent index scan */
  5   ReturnNode      24476827       - RETURN requestIp

Indexes used:
 By   Type         Collection    Unique   Sparse   Selectivity   Fields                 Ranges
  6   persistent   requestsIps   false    true          0.00 %   [ `timestamp.from` ]   (requestIp.`timestamp`.`from` >= 1527833401)

Optimization rules applied:
 Id   RuleName
  1   use-indexes
  2   remove-filter-covered-by-index
  3   remove-unnecessary-calculations-2
```

*Query 2 (date function):*
```
Execution plan:
 Id   NodeType                      Est.   Comment
  1   SingletonNode                    1   * ROOT
  2   EnumerateCollectionNode   48953655     - FOR requestIp IN requestsIps   /* full collection scan */
  3   CalculationNode           48953655       - LET #1 = (requestIp.`timestamp`.`from` >= ROUND((DATE_NOW() / 1000)))   /* v8 expression */   /* collections used: requestIp : requestsIps */
  4   FilterNode                48953655       - FILTER #1
  5   ReturnNode                48953655       - RETURN requestIp

Indexes used:
 none

Optimization rules applied:
 none
```
## Description

The problem is I do have needed index defined, but queries execution time are still way too long (http://prntscr.com/kfui32)

__Attached files__:
[debugDump.zip](https://github.com/arangodb/arangodb/files/2267487/debugDump.4.zip)

## Steps to reproduce

1.  Create `timestamp.from` index
2. Execute the query

__Problem__:
It doesn't use index in query 2

__Expected result__:
It should use index in query 2

**Comment by Simran-B** [comment]
@OmarAyo Can you test 3.4.devel with the C++ implementations of the date function, if that makes any difference?

**Comment by logical-and** [comment]
I'll test once I find way to build the version :)

**Comment by jsteemann** [comment]
@logical-and @Simran-B : it does not make any difference.

**Comment by jsteemann** [comment]
The reason for the index not being used is that the `DATE_NOW()` function is internally marked as "non-deterministic". This will disable certain optimizations, though in this particular case it is not necessary and the index could still be used.
For this, we actually need to allow usage of some non-deterministic functions in some more cases. This requires some internal changes to the AQL function structure.
 
Until this is implemented, a workaround is to pass the current date/time from the application via a bind parameter and use that. This will use the index as expected.

**Comment by logical-and** [comment]
Gotcha. What version you're going to fix this at?

**Comment by jsteemann** [comment]
I cannot tell yet. Depends on how big the fix will be. It may be trivial, but may be not. Will update this issue when it is more clear.

**Comment by jsteemann** [comment]
Update: it's actually a combination of using a non-deterministic function (DATE_NOW) and a sparse index.
The optimizer does not know anything about the potential return values of `DATE_NOW`, thus it does not rule out the function returning null values. That however disables the usage of the sparse index.
In 3.4, the fix is to add an extra non-null check to the filter condition `requestIp.timestamp.from != null` and the sparse index will be used.

**Comment by dothebart** [comment]
With [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) being available containing more optimizer rules to work with sparse indices closing this as solved.
