### ISSUE TITLE
Swagger failed to load after using joi lazy(fn)

### ISSUE THREAD

**Issue by ganeshkharche12** [arangodb/arangodb#6132]
## My Environment

* __ArangoDB Version__:        3.3.14
* __Storage Engine__:            MMFiles
* __Deployment Mode__:      Single Server
* __Deployment Strategy__:   ArangoDB Starter
* __Operating System__:        Ubuntu 16.04
* __Used Package__:              Ubuntu .deb

## Component, Query & Data

__Affected feature__:

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. Add a new **Demo** service by click on Add service in services tab. Create model for your Demo service routes with joi validation and use joi lazy function 

    ```
        const Person = Joi.object({
        firstName: Joi.string().required(),
        lastName: Joi.string().required(),
        children: Joi.array().items(Joi.lazy(() => Person).description('Person schema'))
    });
    ```
    ![error](https://user-images.githubusercontent.com/42230331/43881123-ca0f3cbe-9bc8-11e8-9dec-503d759b1e74.png)

2. Now check swagger of Demo service you can see all documented routes
3. Use this model
4. Now again check swagger.(No operations defined in spec!)

__Problem__: Using JOI validation with lazy(fn) to check recursive validation. In this case swagger failed to load routes even all routes are working. Below are all the generated logs.

```
Failed to build API documentation for "/Demo"!
This is likely a bug in your Foxx service.
Check the route methods you are using to document your API. via Error: sorry, do not know how to convert unknown joi type: "lazy" 
at convert (/usr/share/arangodb3/js/node/node_modules/joi-to-json-schema/build/index.js:186:11)
at Array.forEach (native)
at Object.array (/usr/share/arangodb3/js/node/node_modules/joi-to-json-schema/build/index.js:87:14)
at convert (/usr/share/arangodb3/js/node/node_modules/joi-to-json-schema/build/index.js:225:32)
at /usr/share/arangodb3/js/node/node_modules/joi-to-json-schema/build/index.js:167:43
at Array.forEach (native)
at Object.object (/usr/share/arangodb3/js/node/node_modules/joi-to-json-schema/build/index.js:165:25)
at joi2schema (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/swagger-context.js:568:10) 
```

__Expected result__: Load all routes in swagger

**Comment by pluma** [comment]
We're using a third-party library to translate joi to JSON schema for swagger. Looks like that library currently can't handle `lazy`.

**Comment by pluma** [comment]
You might want to report this at https://github.com/lightsofapollo/joi-to-json-schema/issues too. There's not much we can do about this directly.

**Comment by maxkernbach** [comment]
Hi @ganeshkharche12,

how are things going? Can you please share a status update, did you report this issue in the listed repository?

**Comment by maxkernbach** [comment]
I am closing this issue as "won't fix" since the bug is not caused on our part and has to be fixed in the third-party library [joi-to-json-schema](https://github.com/lightsofapollo/joi-to-json-schema/issues/36) (lazy support has to be added).

**Comment by ganeshkharche12** [comment]
Sure, you can close it, as this is not related with ArangoDB library.
