### ISSUE TITLE
Performance concern in cluster mode

### ISSUE THREAD

**Issue by suewonjp** [arangodb/arangodb#6142]
## My Environment

* __ArangoDB Version__:        3.3.13
* __Storage Engine__:             RocksDB 
* __Deployment Mode__:       Cluster (with Docker Swarm)
* __Deployment Strategy__:   Manual Start in Docker
* __Configuration__:               3 agencies, 6 dbservers, 1 coordinator
* __Infrastructure__:               AWS
* __Operating System__:        Amazon Linux 2
* __Used Package__:              Docker version 18.03.1-ce

## Component, Query & Data

__Affected feature__:
Performance issue in cluster mode

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:
Simple document data, not graph (about 100,000 items)

__Replication Factor & Number of Shards (Cluster only)__:
3 & 3

## Steps to reproduce

1. 
2. 
3. 

__Problem__:
We are testing arango & mongo for our next db candidate for our project. Mostly, we'll pick either of the two as our next main storage layer.  (And we'll purchase a commercial edition once we decide the final winner)

The performance test with a single db instance was a lot more positive for arango than mongo. Now I've tested them with the same data set and queries in a **cluster mode** . I was expecting arango would win, but quite different. Arango won one topic of bulk data import, which it was double faster than mongo, but for data fetch/update/delete, mongo was the clear winner (even 2 ~ 8 times faster)

I don't think query optimization is a big reason here because arango was the winner when testing a single server with the exact same queries and data set. The result was kind of consistent with your benchmark https://www.arangodb.com/2018/02/nosql-performance-benchmark-2018-mongodb-postgresql-orientdb-neo4j-arangodb/ 

But I don't see any benchmark regarding any cluster environment. Or am I missing them? (Plz, provide us with one if you already have, thanks)

Actually, I don't like mongo that much. So I don't like this kind of result. (Very sorry, mongo guys) Can you give me some advice or suggestion for improving arango's performance in a cluster mode?

__Expected result__:

**Comment by lservini** [comment]
@suewonjp  just wondering if you can share with us datamodel, queries (it would be great if you share also execution plans) and the results you get running on single server and cluster. Please provide also ArangoDB version and storage engine. 

Thanks
Luigi

**Comment by suewonjp** [comment]
[arango-issue-6142.zip](https://github.com/arangodb/arangodb/files/2289894/arango-issue-6142.zip)

The zip file contains sample data and Docker Swarm cluster setup file.

Please, read the readme file in the zip. It contains queries and query explains and system info and my notes about other details.

Thanks

**Comment by vinaypyati** [comment]
Hi @suewonjp,

Thanks for proving us with the zip file. We will get back to you as soon as possible with some insights. Thanks for your patience. 

Best,

**Comment by lservini** [comment]
Hi @suewonjp,

In order to provide you with a better answer I would like to ask you for more details:
- can you provide the full dataset (10000 documents it is no enough to compare performance, of course, sensitive data might be masked)
- how is the selectivity on src_type
- how did you create collections in cluster

Thanks

Luigi

**Comment by suewonjp** [comment]
Hi Luigi

- how is the selectivity on src_type
    - The field has only two type of values. And it ends up with one particular value most of the time.
    - And as stated in the readme file, the filtering was fast enough. Sorting (with the cluster) was slow.
-  how did you create collections in cluster
    - Well, nothing special, I think
    - I used python, and db.create_collection method ( https://github.com/joowani/python-arango/blob/master/arango/database.py ), and specified **shard_count** and **replication_factor**  parameters only.  (shards : 3, replicas : 3)
- can you provide the full dataset?
    - Sorry to say this, but providing the full dataset is time consuming. It involves permissions from our client and process to remove sensitive data and more. And I'm too busy recently.

We've already made decision to go with MongoDB.  We're so busy in the middle of migration process. I really like to help you find the cause of the issue, but I'm afraid I can't invest my time to the issue currently.


Thanks

**Comment by dothebart** [comment]
closing as user abandoned with the availability of [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/)
