### ISSUE TITLE
User defined query timeout at query time ?

### ISSUE THREAD

**Issue by matcho** [arangodb/arangodb#6146]
## My Environment

* __ArangoDB Version__:        3.3.13
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Infrastructure__:               own
* __Operating System__:        Debian 9
* __Used Package__:              Debian or Ubuntu .deb

## Component, Query & Data

__Affected feature__:
AQL query using ArangoJS driver

__Problem__:

Hello.

We have a 40M documents collection, and a GUI that allows non-experts to run AQL queries against it. While most queries run in an acceptable time, some criteria combinations still lead to several-hours-long queries, which if repeated too many times leads to server performance degradation.
At the moment we're not able to improve execution time for those queries, and anyway this still might happen at times despite all optimizations.

As this was previously mentioned in #4661 , would it be possible to have a mechanism to set AQL query timeout at query time ? Like `options: { queryTimeout: 300 }` for example ? This would abort (kill) the query to save resources, and for example throw a Timeout exception.
On the contrary, we need some queries to keep running as long as needed without any timeout (large UPSERT for example), hence the idea of setting this at query time.

It looks that such a mechanism was [partially implemented in an arangojs fork by hkbarton](https://github.com/hkbarton/arangojs/commit/e9d91072e47a85cf228acaf4e002836e8eec35ed), but with a fixed timeout for all queries.

Do you think this could be added to AQL options, or ArangoJS driver ?

Thank you for considering this.
Mathias

**Comment by lazharichir** [comment]
Could not support this feature so much... We have hundreds of millions of edges and tens of millions of vertices. A mistake in the query pretty much results in a long downtime which isn't helpful for debugging and working on finding new queries.

**Comment by matcho** [comment]
Up ! Any news about the possibility of seeing this feature implemented ?

Thanks a lot

**Comment by Yogu** [comment]
I second this feature request. The "[partial implementation](https://github.com/hkbarton/arangojs/commit/e9d91072e47a85cf228acaf4e002836e8eec35ed)" linked above does **not work** by the way, it only closes the HTTP connection to ArangoDB. The query keeps running. This is [documented](https://docs.arangodb.com/3.4/HTTP/AsyncResultsManagement/), and that page also recommends to use the job API to be able to cancel requests.

**Comment by Simran-B** [comment]
There will be a feature in v3.6.0 to set a `maxRuntime` in seconds per query.

**Comment by maxkernbach** [comment]
As mentioned in the previous comment, the new (server-side) query timeout parameter [`maxRuntime`](https://www.arangodb.com/docs/stable/aql/invocation-with-arangosh.html#setting-options) is available since versions 3.5.4 and 3.6.0.

From the [Changelog](https://github.com/arangodb/arangodb/blob/108e52eeea23247280e285e7051f89e0ac1e2844/CHANGELOG#L74):


> * Added new maxRuntime option for queries. If a query does not finish execution
>   within the given time (in seconds) it will be killed.

Whenever a query is running longer than the time specified in **maxRuntime**, the query aborts with error **"ArangoError 1500: AQL: query killed (while executing)"**.

The following examples show how to execute the the option

via **arangosh**:
```
db._query("LET x = SLEEP(10) RETURN 1", {} /*bind*/, { maxRuntime : 5} /*options*/);
```

via **arangojs**:

```
db.query("LET x = SLEEP(10) RETURN 1", {} /*bind*/, {options: { maxRuntime : 5}/*options*/}).then(
  cursor => cursor.all()
).then(
  log => console.log(1),
  err => console.error('Failed to execute query:', err)
);
```

**Comment by BaconHX** [comment]
Is there a way to use options in query sentence like this "for i n collection {options: { maxRuntime : 5}  limit 100000 return i" ?

**Comment by dothebart** [comment]
Hi, 
limiting the time of query parts isn't possible, only the query as whole in the query params. 

However, more modern arangodb versions will give you the time used information with the `profile` way of running queries in the UI or via arangosh.
