### ISSUE TITLE
Service exited with abnormal code: 22

### ISSUE THREAD

**Issue by OKNoah** [arangodb/arangodb#6151]
## My Environment

* __ArangoDB Version__:        3.3.13
* __Storage Engine__:             mmfiles (?)
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               brew
* __Infrastructure__:               Darwin
* __Operating System__:        macOS 10.13.6 (17G65)
* __Used Package__:              https://github.com/Homebrew/homebrew-core/blob/master/Formula/arangodb.rb
## Component, Query & Data

__Affected feature__:
ArangoDB

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:
I have several databases, this affects ArangoDB from starting entirely.

__Replication Factor & Number of Shards (Cluster only)__:
I have reinstalled, done `brew doctor`, uninstalled and installed again, etc.

## Steps to reproduce

1. `brew install arangodb`
2. `brew services start arangodb`

__Problem__:
From Console.app:

```
Aug 13 00:03:25 Noahs-Mac com.apple.xpc.launchd[1] (homebrew.mxcl.arangodb[23950]): Service exited with abnormal code: 22
Aug 13 00:03:25 Noahs-Mac com.apple.xpc.launchd[1] (homebrew.mxcl.arangodb): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
```

__Expected result__:
It should not crash

**Comment by dothebart** [comment]
Exit code 22 means "couldn't lock database directory" - probably another instance is running meanwhile? You have to make sure that its stopped in advance.

**Comment by OmarAyo** [comment]
Hi @OKNoah 

Just sending a followup, are you still facing this issue ? Did you check if another instance was running meanwhile. In case please provide `ps aux | grep arangod` output

**Comment by OKNoah** [comment]
@OmarAyo I'm sorry I don't have more detail, but I believe this was resolved by re-installing the brew/command line apps a number of times. I remember going through this more than once and the fix was more than once to upgrade or re-install things. Very unhelpful, sorry.
