### ISSUE TITLE
Unable to create/update/save users

### ISSUE THREAD

**Issue by deepak7093** [arangodb/arangodb#6155]
## My Environment

* __ArangoDB Version__:      3.3.13
* __Storage Engine__:            rocksdb
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   Config
* __Configuration__:            
  
Primary:https://gist.github.com/deepak7093/d98e54595f53b1fec55eff35a1037e86
Coordinator: https://gist.github.com/deepak7093/b6c15e608fda2dd123b672db973c4608
Agent: https://gist.github.com/deepak7093/8f3fc57e1e6d330e1bb362ef87b193ce

* __Infrastructure__:             AWS
* __Operating System__:        Ubuntu 14.04.5 LTS
* __Used Package__:            ubuntu.deb

## Component, Query & Data

__Affected feature__:
Web Interface
Arangosh

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:

__Replication Factor & Number of Shards (Cluster only)__:

require("org/arangodb/users").save("sammy", "password");

## Steps to reproduce

1. Login to arangosh using: arangosh --server.ask-jwt-secret
2. enter require("org/arangodb/users").save("sammy", "password");

__Problem__:

Unable to reset passowrd for root user.

__Expected result__:

```
root@node03:~# arangosh --server.ask-jwt-secret
Please specify the JWT secret:

                                       _
  __ _ _ __ __ _ _ __   __ _  ___  ___| |__
 / _` | '__/ _` | '_ \ / _` |/ _ \/ __| '_ \
| (_| | | | (_| | | | | (_| | (_) \__ \ | | |
 \__,_|_|  \__,_|_| |_|\__, |\___/|___/_| |_|
                       |___/

arangosh (ArangoDB 3.3.13 [linux] 64bit, using jemalloc, build tags/v3.3.13-0-g92a0c39, VPack 0.1.30, RocksDB 5.6.0, ICU 58.1, V8 5.7.492.77, OpenSSL 1.0.2g  1 Mar 2016)
Copyright (c) ArangoDB GmbH

Pretty printing values.
Connected to ArangoDB 'http+tcp://172.31.19.236:8530' version: 3.3.13 [server], database: '_system', username: 'root'

Type 'tutorial' for a tutorial or 'help' to see common examples
172.31.19.236:8530@_system> require("org/arangodb/users").save("sammy", "password");
2018-08-14T13:43:44Z [10382] INFO data:  { "user" : "sammy", "passwd" : "password" }
JavaScript exception in file '/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js' at 99,7: ArangoError 9: not implemented
!      throw error;
!      ^
stacktrace: ArangoError: not implemented
    at Object.exports.checkRequestResult (/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js:97:21)
    at Object.exports.save (/usr/share/arangodb3/js/client/modules/@arangodb/users.js:56:33)
    at <shell command>:1:31
```

**Comment by rocketraman** [comment]
I had this problem too -- yeah the documentation isn't clear at all about this, so I'm glad the documentation tag was added here.

**Comment by Himan000** [comment]
Hi @jsteemann,
      How to reset root password with Cluster arangodb? Because I can't find any statement in the document. It just provides single instance. [https://docs.arangodb.com/3.4/Manual/Security/ChangeRootPassword.html](url)

**Comment by dothebart** [comment]
Clusters should be started with a JWT. 
You can use this JWT to connect [arangosh](https://www.arangodb.com/docs/stable/programs-arangosh-options.html#server) with: 
 - `--server.jwt-secret-keyfile`
 - `--server.ask-jwt-secret`

Closing this with the availability of [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/)
