### ISSUE TITLE
Transaction in php

### ISSUE THREAD

**Issue by anonymus58** [arangodb/arangodb#6170]
Unclear how can I run a simple query with transaction in PHP ?

I have tried this way :

$connection = new Connection($connectionOptions);

$query = 'FOR u IN Courses
FILTER u.Available positions > 0
FILTER u._key == "1672779"
UPDATE u WITH { Available positions: u.Available positions-1 } IN Courses
RETURN NEW';

$statement = new Statement(
$connection,
array(
"query" => $query,
"count" => true,
"batchSize" => 1000,
"sanitize" => true
)
);

	$writeCollections = ["Courses"];
    $action = "function () {
            $cursor = $statement->execute()
     }";

	$waitForSync      = true;
    $lockTimeout      = 10;

    // check if setters work fine
    $transaction                   = new Transaction($connection);
    $transaction->writeCollections = "Courses";
    $transaction->action           = $action;
    $transaction->waitForSync      = true;
    $transaction->lockTimeout      = 10;
$transaction->execute();

but i got this notice, and don`t works :
Notice: Undefined variable: cursor on line 28
Notice: Undefined property: ArangoDBClient\Statement::$execute on line 28
ArangoDBClient\ServerException: 10 missing/invalid action definition for transaction - Uncaught SyntaxError: Unexpected token = - SyntaxError: Unexpected token = at new Function ()

What is the solution to run this query with transaction?

**Comment by Simran-B** [comment]
AQL queries are transactional. See here for more details: https://docs.arangodb.com/3.3/AQL/DataQueries.html#transactional-execution
It should not be necessary to use a JavaScript transaction for your query.

You can find an example of how the code of `$action` should look like in the documentation (note that objects like `db` are not available automatically, but require an explicit import): https://docs.arangodb.com/3.3/Manual/Transactions/TransactionInvocation.html#examples

Regarding parameter passing, see https://docs.arangodb.com/3.3/Manual/Transactions/Passing.html - the PHP driver works similar: `$transaction->params = [ 1, 2, 3 ];`

**Comment by anonymus58** [comment]
Thank you very much.
