### ISSUE TITLE
Replication problem

### ISSUE THREAD

**Issue by anonymus58** [arangodb/arangodb#6171]
My replication is active, i mean at the web interface I got the active label in replication section. But at log only got warnings like this : retrying failed HTTP request for endpoint 'tcp://master.domain.org:8529' for replication applier in database '_system' - no retries left

At replication section, under total I have : 

Events replicated | 0
Requests issued | 102
Failed connects | 101

My replication properties are : 
require("@arangodb/replication").setupReplicationGlobal({
  endpoint: "tcp://master.domain.org:8529",
  username: "user",
  password: "passs",
  verbose: false,
  includeSystem: false,
  incremental: true,
  autoResync: true,
  autoStart: true
});

and after this i start with applier.start(<lasttick>).

What is the problem ?

**Comment by jsteemann** [comment]
The log seems to indicate that the replication slave cannot connect to the master.
This can have various reasons, including:
- master is not running. Can you check if the master server is actually up and running?
- connection settings on slave are wrong. Can you check if the following is correct and valid to connect to the master:
  - endpoint: "tcp://master.domain.org:8529"
  - username: "user"
  - password: "passs"
- the network between slave and master may be slow or unavailable, thus preventing the successful data transfer
- there may be a firewall or other network component between slave and master blocking the communication

As a first step, can you try if the master is accessible from the slave via a simple curl command, e.g.
```
curl -X GET http://master.domain.org:8529/_api/version --basic --user "user:passs" --dump -; echo
```
It that does not show the version number but any error, the slave will not be able to connect to the master too, and you need to fix the underlying problem reported.

**Comment by anonymus58** [comment]
I got this answer : 
curl: (7) Failed to connect to master.domain.org port 8529: Connection refused
curl: (6) Could not resolve host: echo

Where can I check the endpoint, and the masters state?

**Comment by jsteemann** [comment]
You actually shouldn't get a message "curl: (6) Could not resolve host: echo" if you copied the above command exactly. `echo` is a separate command, just meant to add a newline after the output of `curl`. Please check if you used the same command as provided.
Apart from that, `curl: (7) Failed to connect to master.domain.org port 8529: Connection refused` seems to indicate that you cannot connect to `master.domain.org` on port 8529. If that is really the endpoint address you are using, that does not surprise me. You have to use the master's actual domain name/IP address. I am pretty sure the master is not using the domain `master.domain.org`. I used that only because you used that value in the original question.

**Comment by anonymus58** [comment]
ok, I think I have problem with setting the endpoints. 
I want to set up the replication at localhost, running the 
curl -X GET http://localhost:8529/_api/version --basic --user "user:passs" --dump -; command i got 
{"server":"arango","version":"3.3.9","license":"community"}

What is the correct endpoint for applier end setupreplication, or do you think I have other mistakes?

**Comment by jsteemann** [comment]
The correct endpoint is the one your master is running on and reachable via.
It should be `tcp://localhot:8529` then.

**Comment by jsteemann** [comment]
You need to have two servers to use the replication. It seems you are connecting from just one server to itself.
The slave server connects to the master server, and the replication on the slave needs the master's correct endpoint.
The slave is a different arangod server instance, and thus *must have* a different IP address or port than the master.
Using replication with just a single server instance will not take you anywhere.

**Comment by anonymus58** [comment]
What is the easiest method to configure a new server?

**Comment by jsteemann** [comment]
That depends on the platform. I suggest using a second host and installing the slave on it. That will give you two hosts with two different IP addresses, and you can use one as the master and the other as the slave.
Please refer to the [ArangoDB manual](https://docs.arangodb.com/) for any setup/installation/configuration details.

**Comment by anonymus58** [comment]
If I have a master-slave replication I have to use transaction for sensitive data or, the AQL queries remain transactional in this case ?

**Comment by jsteemann** [comment]
In a single-instance or with async master-slave replication, AQL queries will be transactional.
For the RocksDB storage engine there are some restrictions w.r.t. to transaction sizes:
https://docs.arangodb.com/3.3/Manual/Transactions/Limitations.html

**Comment by anonymus58** [comment]
Thank you very much for help.

**Comment by vinaypyati** [comment]
I am closing this issue. If you have any further queries you can reopen this issue and post a question.

Thanks.
