### ISSUE TITLE
 Invalid edge can be created although the vertex does not exist ?

### ISSUE THREAD

**Issue by Arun-KumarH** [arangodb/arangodb#6176]
## My Environment

* __ArangoDB Version__:    3.2.9  
* __Storage Engine__:         RocksDB  
* __Deployment Mode__:  SingleServer    
* __Deployment Strategy__: Doocker
* __Configuration__:      standalone       
* __Infrastructure__:         own      
* __Operating System__:      Sabayon
* __Used Package__:          Docker official

## Component, Query & Data

__Affected feature__:
Graphs - Invalid edge can be created although vertex / node does not exist.

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:
I have created a vertex collection named 'vertices' and created an edge named ('vertice_to_vertice_edge') between the 'vertices' collection.
I inserted two vertices (with keys 1 and 2) and created and edge between them.

// Valid Edge created
await createEdge('vertice_to_vertice_edge', {some: 'edgeData1'}, 'vertices/1', 'vertices/2');

// Invalid Edge should not have been created
await createEdge('vertice_to_vertice_edge', {some: 'edgeData2'}, 'vertices/3', 'vertices/4');

If I try to create one more edge between vertex keys (3 and 4) the edge still gets created although the vertices 3 and 4 does not exist ?
Is this the expected behaviour ?

(https://github.com/arangodb/arangojs/issues/565)

## Steps to reproduce

1. Create a vertex and an edge definition as between same vertex to vertex
2. Insert two collection data and create an edge between them (All good)
3. Now try to create another edge between two nodes which do not exist, the edge still gets created.

__Problem__:
Edge is getting created when both source and destination nodes / vertices do not exist.

__Expected result__:
Edge should not get created when either the source or destination node / vertex does not exist.

**Comment by Simran-B** [comment]
The Gharial graph API checks _from and _to starting from 3.3.9, to verify that the vertices exist.

See https://github.com/arangodb/arangodb/issues/3811

**Comment by sleto-it** [comment]
Hi @Arun-KumarH,

Just wondering: is it possible for you to upgrade to 3.3 (at least a version >= 3.3.9?)
The bug was fixed in 3.3.9 but the fix was not backported to 3.2

Let us know,

Thanks,

**Comment by Arun-KumarH** [comment]
Alright, Will check it out with version>=3.3.9 and update.

**Comment by Arun-KumarH** [comment]
Perfect, works with DB 3.3.9v.
