### ISSUE TITLE
delete collection very slow or stuck

### ISSUE THREAD

**Issue by sirpy** [arangodb/arangodb#6183]
using latest arangodb, when deleting a vertex collection with 10s millions of nodes, arango seems to get stuck.
on smaller collections it takes a while but it seems to finish.
top shows arangod is using 100% of  1 core.
noticed this problem when issuing delete collection via the web interface and via arango python client.
issuing .drop() via the arangosh on collection seems to happen instantly

**Comment by vinaypyati** [comment]
Hi @sirpy,

Sorry for the delay. How things are going with this issue? Can you please let us know the following 
- ArangoDB version 
- Storage-engine
- OS 
- Deployment mode

FYI: You can try testing this issue on latest available 3.4 Release Candidate is RC2 and can be found in the [download section](https://www.arangodb.com/download-technical-preview/). 

Thanks for your feedback.

**Comment by vinaypyati** [comment]
Hi @sirpy,

We haven't received feedback from you for a while, I am closing this issue for now.

Please consider testing this issue on 3.4.0 RC3. You can download it from the [download section](https://www.arangodb.com/download-technical-preview/). If it does not resolve your problem, please feel free to reopen the issue by adding a new comment.

Thanks!
