### ISSUE TITLE
AQL isn't understanding the new Geo utility functions

### ISSUE THREAD

**Issue by alexzabbey** [arangodb/arangodb#6189]
## My Environment

* __ArangoDB Version__:        3.4.milestone0
* __Storage Engine__:             MMFiles
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start in Docker
* __Infrastructure__:               own
* __Operating System__:        Windows 10
* __Used Package__:              official Docker library

## Component, Query & Data

__Affected feature__: AQL query using web interface
__AQL query (if applicable)__:
just used random points to check the function
`RETURN GEO_DISTANCE([30, 30], [40, 40])`
`RETURN GEO_POINT(1.0, 2.0)`

__AQL explain (if applicable)__:

> Explain: usage of unknown function 'GEO_DISTANCE()' (while parsing)
> Explain: usage of unknown function 'GEO_POINT()' (while parsing)

__Problem__:
AQL isn't understanding the new Geo utility functions, used as specified in documentation [https://docs.arangodb.com/devel/AQL/Functions/Geo.html](https://docs.arangodb.com/devel/AQL/Functions/Geo.html)
Is it a problem with the version I installed? (just used the docker image from here: [https://www.arangodb.com/download-technical-preview/docker-preview/](https://www.arangodb.com/download-technical-preview/docker-preview/))

**Comment by jsteemann** [comment]
Hi @alexzabbey, 
I think the technical preview is from a January 3.4 milestone release, in which the geo functions are not yet available.
I suggest to try out our nightly builds instead. These are development snapshots and normally much more up-to-date than the milestone releases. They can be found at:
https://www.arangodb.com/nightly-builds/

Sorry for the confusion.

**Comment by maxkernbach** [comment]
Hi @alexzabbey,

Have you already tested the new geo utility functions?
FYI: ArangoDB 3.4 RC1, which includes the new geo functions, has been released and can be found [here](https://www.arangodb.com/download-technical-preview/).

**Comment by alexzabbey** [comment]
Thanks, I'll check it out

**Comment by OmarAyo** [comment]
Hi @alexzabbey 

Just sending a quick followup to check how things are going

Please, provide us with a status update

Many Thanks

**Comment by OmarAyo** [comment]
Hi @alexzabbey 

Since there was no feedback in a while, I am closing this issue for now.
 
Please feel free to comment if the issue persists

Best,

**Comment by Philip-Wu** [comment]
im having this problem in 3.3.19

**Comment by Philip-Wu** [comment]
works in 3.4 RC4
