### ISSUE TITLE
Make and set up slave

### ISSUE THREAD

**Issue by anonymus58** [arangodb/arangodb#6251]
How, can I make a new host for slave and how can I set up ? (on windows)

**Comment by anonymus58** [comment]
Please help me it is very important, and I don`t know how can i made.

**Comment by maxkernbach** [comment]
Hi @anonymus58,

did you already have a look at the [replication documentation](https://docs.arangodb.com/3.3/Manual/Administration/Replication/Asynchronous/)?

Are you using/want to set up a per-database (use `require("@arangodb/replication").applier`) or server (use `require("@arangodb/replication").globalApplier`) replication?

The replication generally has to be set up on the slave, the new host instance just has to be running on the same ArangoDB version as the slave.

You can execute the following commands in `arangosh` to modify your current replication configuration (per-database example):

Monitor the replication state on database `yourDB`:

```
    db._useDatabase("yourDB");
    require("@arangodb/replication").applier.state();
```

Stop the active replication applier:

```
require("@arangodb/replication").applier.stop();
```

Configure the replication applier with your new host:

```
require("@arangodb/replication").applier.properties({
  endpoint: "tcp://master.domain.org:8529",
  username: "myuser",
  password: "mypasswd",
  autoStart: true,
  autoResync: true,
  autoResyncRetries: 2,
  adaptivePolling: true,
  includeSystem: false,
  requireFromPresent: false,
  idleMinWaitTime: 0.5,
  idleMaxWaitTime: 1.5,
  verbose: false
});
```

Start the replication with the modified configuration:
```
require("@arangodb/replication").applier.start("40694126");
```

**Comment by anonymus58** [comment]
I want a master-slave replication for one database. I have made the steps from documentation and I got 
 this : error while running applier thread for database '_system': got same server id (157349986351979) from endpoint 'tcp://localhost:8529' as the local applier server's id

This is because i set up at the same server the master and the slave.
My question is how can i made thwo differennt servers to set up them?

**Comment by maxkernbach** [comment]
In order to set up the replication on the same local machine, you have to use multiple ArangoDB instances with different ports. 

For example you can run the slave on `tcp://localhost:8529`, the master on `tcp://localhost:8530` and then use endpoint `tcp://localhost:8530` in the replication properties on your slave.

**Comment by anonymus58** [comment]
How can I run the slave on tcp://localhost:8529, and the master on tcp://localhost:8530

**Comment by anonymus58** [comment]
My main database must be the master?

**Comment by maxkernbach** [comment]
Yes, the master is the main database (see documentation).

> In an asynchronous replication scenario slaves will pull changes from the master database. Slaves need to know to which master database they should connect to, but a master database is not aware of the slaves that replicate from it. When the network connection between the master database and a slave goes down, write operations on the master can continue normally. When the network is up again, slaves can reconnect to the master database and transfer the remaining changes. This will happen automatically provided slaves are configured appropriately.

**Comment by anonymus58** [comment]
I have this error message 
"2018-08-28T07:58:41Z [7432] ERROR {replication} error while running applier thread for database 'Project': collection not found, offending marker: {"cuid":"h8F1BE60ABB6B/1660972 ... " 

what is it and how can i resolve ?

**Comment by maxkernbach** [comment]
It seems that you are missing you are missing the copy of the initial data. 

I would recommend you to use the [All-in-one replication setup](https://docs.arangodb.com/3.3/Manual/Administration/Replication/Asynchronous/DatabaseSetup.html#all-in-one-setup), which executes both the initial data copy and the continuous replication. 

```
db._useDatabase("_system");
require("@arangodb/replication").setupReplication({
  endpoint: "tcp://master.domain.org:8529",
  username: "myuser",
  password: "mypasswd",
  verbose: false,
  includeSystem: false,
  incremental: true,
  autoResync: true
});
```

The only things that you have specify are your replicated database in `db._useDatabase("_system");`, endpoint, username and password.

**Comment by anonymus58** [comment]
My master is at 8529 and the slave is at 8530 

for master i use :

require("@arangodb/replication").setupReplicationGlobal({   
endpoint: "tcp://localhost:8530",   
username: "root",  
 password: "",   
verbose: false,   
includeSystem: false,  
 incremental: true,   
autoResync: true,   a
utoStart: true
 });

require("@arangodb/replication").applier.properties({    
endpoint: "tcp://localhost:8529",    
username: "root",   
 password: "",   
adaptivePolling: true,   
connectTimeout: 15,   
maxConnectRetries: 100,   
chunkSize: 262144,   
autoStart: true,   
includeSystem: true,   
autoResync: true,   
autoResyncRetries: 2,
 });

and for slave : 

 require("@arangodb/replication").setupReplicationGlobal({   
endpoint: "tcp://localhost:8530",   
username: "root",   
password: "",   
verbose: false,  
 includeSystem: false,  
 incremental: true,   
autoResync: true,   
autoStart: true 
});

require("@arangodb/replication").applier.properties({    
endpoint: "tcp://localhost:8529",    
username: "root",    
password: "",   
adaptivePolling: true,   
connectTimeout: 15,   
maxConnectRetries: 100,  
 chunkSize: 262144,   
autoStart: true,   
includeSystem: true,  
 autoResync: true,   
autoResyncRetries: 2, 
});

still the same error.

**Comment by anonymus58** [comment]
Thank you very much.

**Comment by mario-pz** [comment]
Is there a way to do this from CLI and not javascript? What would be the best practice to achieve this master/slave in a k8s cluster? The documentation has so many flags and lots of them have no details, you can't tell where you start

**Comment by dothebart** [comment]
arangosh in itself only uses the REST-API as well. probably the most easy way to do this is by ngrep'ing arangosh doing it.
