### ISSUE TITLE
AQL / ArangoSearch crash with SEARCH TOKENS

### ISSUE THREAD

**Issue by goedderz** [arangodb/arangodb#6289]
In current devel (edb6011ccbe74981f02553f33fc6bd9faa4a4515) I see an exception with the following query:
```
FOR doc IN booksView SEARCH 'quam' IN TOKENS(doc.text, "text_de") RETURN doc
```

> WARNING caught exception in RestCursorHandler: AQL: internal error (exception location: /home/tobias/Documents/ArangoDB/arangodb/arangodb/arangod/IResearch/IResearchViewBlock.cpp:87). Please report this error to arangodb.com (while executing) (exception location: /home/tobias/Documents/ArangoDB/arangodb/arangodb/arangod/RestHandler/RestCursorHandler.cpp:238). Please report this error to arangodb.com

while with `FILTER` it works as expected:
```
FOR doc IN booksView FILTER 'quam' IN TOKENS(doc.text, "text_de") RETURN doc
```

The view `booksView` has the following link:
```
"books": {      
  "analyzers": [
    "text_de"   
  ],            
  "fields": {   
    "text": {}  
  },            
}               
```

**Comment by Simran-B** [comment]
Similar error for an even simpler query in 3.4.0e-RC.3:

```js
FOR book IN booksView
    SEARCH "something" IN book.text
    RETURN book
```

> Query: AQL: internal error (exception location: c:\users\jenkins\oskar\work\arangodb\arangod\iresearch\iresearchviewblock.cpp:87). Please report this error to arangodb.com (while executing) (exception location: c:\users\jenkins\oskar\work\arangodb\arangod\resthandler\restcursorhandler.cpp:237). Please report this error to arangodb.com

Not sure such a query is even supported, but if not, then it should report that as error message, like this?
_Query: AQL: unsupported SEARCH condition (while optimizing plan)_


I get the same error for the following query variations:

- `SEARCH book`
- `SEARCH book.text`
- `SEARCH book != null`

**Comment by KVS85** [comment]
@Simran-B Such query is not supported and we unable to produce _Query: AQL: unsupported SEARCH condition (while optimizing plan)_ because from AQL's POV it's correct expression. However, IResearch will not handle it, because you don't provide a document context here (should be `SEARCH PHRASE(book.text, "something", "text_en")`.

**Comment by Simran-B** [comment]
I see that it the parser can't detect this early, but could ArangoSearch be made to raise a similar error? If something isn't supported, then especially the part "Please report this error to arangodb.com" should not be shown to avoid a bunch of bug reports that are in fact feature requests.

**Comment by gnusi** [comment]
will be addressed by 
https://github.com/arangodb/arangodb/pull/7249
