### ISSUE TITLE
More descriptive error messages for ArangoSearch

### ISSUE THREAD

**Issue by goedderz** [arangodb/arangodb#6313]
Using an unsupported analyzer results in the error `Query: AQL: unsupported SEARCH condition (while optimizing plan)`. While there is a more specific warning in the logs, the user usually does not see that and the error message could be more descriptive.

Using a scorer with an illegal argument (e.g. `FOR doc IN view SORT BM25(doc.name)` or `SORT BM25({})`), the error message `Scorer function is designed to be used with ArangoSearch view only` is given. This could be more specific, especially as this will probably be a common mistake.

Passing an illegal argument to `EXISTS`, e.g. `EXISTS("str")` results in the error message `Filter function is designed to be used with ArangoSearch view only (while optimizing ast)`.

**Comment by gnusi** [comment]
should be addressed by
https://github.com/arangodb/arangodb/pull/7257
https://github.com/arangodb/arangodb/pull/7252
