### ISSUE TITLE
When putting links into a view, new links are not returned.

### ISSUE THREAD

**Issue by lamai93** [arangodb/arangodb#6315]
## My Environment

* __ArangoDB Version__:       devel
* __Storage Engine__:            MMFiles / RocksDB
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   Manual Start
* __Configuration__:            
* __Infrastructure__:               local
* __Operating System__:      Ubuntu 18.04
* __Used Package__:             

## Component, Query & Data

__Affected feature__: IResearch View

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. Start a cluster, for example via `startLocalCluster.sh`.
2. `curl -s -X POST http://[::1]:8530/_api/view -d '{"name":"SomeView", "type":"arangosearch"}'`
3. `curl -s -X POST http://[::1]:8530/_api/collection -d '{"name":"SomeCollection"}'`
4. `curl -s -X PUT http://[::1]:8530/_api/view/SomeView/properties -d'{"links":{"SomeCollection":{}}}'`

__Problem__:
In step for the properties returned have `links` empty object.

__Expected result__:
`links` should contain the link to `SomeCollection`.

**Comment by KVS85** [comment]
Fixed.

Validated with `3.4` and `devel`.
