### ISSUE TITLE
Writting optimization

### ISSUE THREAD

**Issue by noctorus** [arangodb/arangodb#6401]
## My Environment

ArangoDB Version: 3.3.14
Storage Engine: RocksDB
Deployment Mode: Single Server
Deployment Strategy: Manual Start (only run "arangod" on shell bash)
Configuration: default
Infrastructure: own
Operating System: Ubuntu 16.04
Used Package: Ubuntu .deb

Hello, I would like to know the ArangoDB team again to optimize writting my data. I'm using Arango to write data streaming.
I'm using the php library version, and running the following function:
```
$query = 'UPSERT { clientid: "'.$clientid.'", domain:"'.$domain.'", path:"'.$path.'" }
          INSERT { clientid: "'.$clientid.'", domain:"'.$domain.'", path:"'.$path.'", count:1, 
          created_at:DATE_NOW() }
          UPDATE { clientid: "'.$clientid.'", domain:"'.$domain.'", path:"'.$path.'", count:OLD.count+1, 
          created_at:DATE_NOW() } IN hariken_segments';
$statement = new Statement(
      $this->connection,
      array(
         "query"     => $query,
        )
     );
```

It works fine, and its performance is better MongoDB for example.
I cant start parallel service becouse  I have conflicts in wirte same document in collection.

What can I do to improve my document writting? to change some settings? cluster would be a solution?

**Comment by dothebart** [comment]
With the availability of [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/)  I'm closing this as outdated.
