### ISSUE TITLE
Sparse indexes not used on skiplists

### ISSUE THREAD

**Issue by soualid** [arangodb/arangodb#6422]
## My Environment

* __ArangoDB Version__:        3.3.14
* __Storage Engine__:             RocksDB
* __Deployment Mode__:        Master/Slave
* __Deployment Strategy__:   DCOS
* __Configuration__:               

* __Infrastructure__:               own
* __Operating System__:        CentOS7 / Docker
* __Used Package__:              Docker / 3.3.14 tag

## Problem

I may have misunderstood something regarding [sparse attribute of skiplist indexes](https://docs.arangodb.com/3.3/Manual/Indexing/Skiplist.html), but it seems that the sparse indexes are never used on skip list, please see the test case below. In the following example, the index is not `sparse` and is used properly

```
db.test.drop()
db._create('test')
db.test.ensureIndex( {"type":"skiplist","fields":["timestamp"],"unique":false,"sparse":false });
db._query('insert {timestamp: date_now()} in test')
db._query('insert {timestamp: date_now()} in test')
db._query('insert {timestamp: null} in test')
db._explain("for t in test filter t.timestamp && t.timestamp < '2018-09-07' return t")
Query string:
 for t in test filter t.timestamp < '2018-09-07' return t

Execution plan:
 Id   NodeType        Est.   Comment
  1   SingletonNode      1   * ROOT
  6   IndexNode          1     - FOR t IN test   /* skiplist index scan */
  5   ReturnNode         1       - RETURN t

Indexes used:
 By   Type       Collection   Unique   Sparse   Selectivity   Fields            Ranges
  6   skiplist   test         false    false       100.00 %   [ `timestamp` ]   (t.`timestamp` < "2018-09-07")

Optimization rules applied:
 Id   RuleName
  1   use-indexes
  2   remove-filter-covered-by-index
  3   remove-unnecessary-calculations-2
```
But if the same index is declared `sparse`, it will not be used: 
```
db.test.drop()
db._create('test')
db.test.ensureIndex( {"type":"skiplist","fields":["timestamp"],"unique":false,"sparse":true });
db._query('insert {timestamp: date_now()} in test')
db._query('insert {timestamp: date_now()} in test')
db._query('insert {timestamp: null} in test')
db._explain("for t in test filter t.timestamp && t.timestamp < '2018-09-07' return t")
Query string:
 for t in test filter t.timestamp && t.timestamp < '2018-09-07' return t

Execution plan:
 Id   NodeType                  Est.   Comment
  1   SingletonNode                1   * ROOT
  2   EnumerateCollectionNode      2     - FOR t IN test   /* full collection scan */
  3   CalculationNode              2       - LET #1 = (t.`timestamp` && (t.`timestamp` < "2018-09-07"))   /* simple expression */   /* collections used: t : test */
  4   FilterNode                   2       - FILTER #1
  5   ReturnNode                   2       - RETURN t

Indexes used:
 none

Optimization rules applied:
 none
```

**Comment by soualid** [comment]
I tested the same script against 3.2.12 and the behaviour is the same.

**Comment by jsteemann** [comment]
If the query's filter condition is changed from
```
 filter t.timestamp && t.timestamp < '2018-09-07' 
```
to
```
 filter t.timestamp > null && t.timestamp < '2018-09-07' 
```
then the sparse index will be used too.

**Comment by jsteemann** [comment]
The problem is not that there is a skiplist index, but that the optimizer will in general only use sparse indexes in case it can prove the range given does not include the value `null`.
If I am not wrong, it will specifically look for `indexAttribute != null` or `indexAttribute > null`, but it may not look for a condition that is just `indexAttribute` (although this effectively will rule out `null` values too). It's simply not smart enough to detect all cases yet.
As mentioned, it can be convinced to use the sparse index when slightly adjusting that query's filter condition as shown above.
I hope this helps!

**Comment by soualid** [comment]
Thanks for the tip, very good to know! 

I confirm that using `> null` trigger the index usage, but not `!= null`. As it is a bit counter-intuitive, it would be great to make it activated by the `!=` operator (or even when just testing the existence of the property "à la" javascript, ie: `&& indexAttribute`).

**Comment by jsteemann** [comment]
Yes, I think the optimizer can be vastly improved in this regard.
Something has been done in 3.4 for this already (I think it 3.4 also handles `!= null`), but still it will not use a sparse index when checking for an index attribute using just `FILTER doc.indexAttribute`.
There is definitely still room for improval there.

**Comment by Yogu** [comment]
It would be very helpful to document this in the  ["Which Index to use when"
 documentation page](https://docs.arangodb.com/3.4/Manual/Indexing/WhichIndex.html), where there currently is only a very vague statement:

> If the lookup value is non-constant, a sparse index may or may not be used, depending on the other types of conditions in the query. If the optimizer can safely determine that the lookup value cannot be null, a sparse index may be used. When uncertain, the optimizer will not make use of a sparse index in a query in order to produce correct results.

We were using `IS_NULL` by the way - would be good to support this too (if it is not already - we're not yet on 3.4).

**Comment by Simran-B** [comment]
I did a little test with a 3.4.0 preview build, using RocksDB engine and a sparse hash/skiplist index. Some additional cases are recognized by the optimizer.

Index used:
- `filter t.timestamp == not null && t.timestamp < '2018-09-07'`
- `filter t.timestamp != null && t.timestamp < '2018-09-07'`
- `filter t.timestamp > null && t.timestamp < '2018-09-07'`
- `filter t.timestamp not in [null] && t.timestamp < '2018-09-07'`

Index not used:
- `filter t.timestamp && t.timestamp < '2018-09-07'`
- `filter t.timestamp not in [null,1,2,3] && t.timestamp < '2018-09-07'`
- `filter [null, '1980-01-01'] ALL > t.timestamp && t.timestamp < '2018-09-07'`

Same findings for MMFiles engine with a sparse skiplist index.

I agree that we should better explain the conditions for sparse index utilization. I will create an internal ticket to track this.
