### ISSUE TITLE
what does spring Data for arangodb do with JSONArray

### ISSUE THREAD

**Issue by wliceberg** [arangodb/arangodb#6434]
## My Environment

* __ArangoDB Version__: 3.3.12       
* __Storage Engine__:             
* __Deployment Mode__:       
* __Deployment Strategy__:   
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:        
* __Used Package__:              

## Component, Query & Data

__Affected feature__:

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. 
2. 
3. 

__Problem__:
Spring Data integration for ArangoDB.
I use JSONArray in entity, but repository.findOne  or findAll  Query execution failed. the error info is "Caused by: org.springframework.data.mapping.model.MappingException: No mapping metadata found for type java.lang.Object". JSONArray  Data types not supported?
in arangodb,collection  sample data:
<img width="289" alt="image" src="https://user-images.githubusercontent.com/6397004/45260956-bcdb1a00-b427-11e8-89b6-b674916ddf32.png">

How to deal with? in  Spring Data
__Expected result__:

**Comment by rashtao** [comment]
Please open a new issue in https://github.com/arangodb/spring-data/issues if the problem is still relevant and consider upgrading to the latest ArangoDB version:
https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model
