### ISSUE TITLE
Cannot replace Foxx Service.

### ISSUE THREAD

**Issue by lanluu** [arangodb/arangodb#6439]
ArangoDb 3.4 RC 1 - Windows

By replacing a Foxx Service, the exception "Service {abc} was already there". Of course, it must be there, as Enduser wanted to ... replace ;-).

**Comment by vinaypyati** [comment]
Hi @lanluu,

Did you have a chance to test if this issue also occurs in [3.4.0 RC2](https://www.arangodb.com/download-technical-preview/) ? Please let us know your feedback.

Thanks!

**Comment by vinaypyati** [comment]
Hi @lanluu,

We haven't received feedback from you for a while, I am closing this issue for now.

Please consider testing this issue on 3.4.0 RC3. You can download it from the [download section](https://www.arangodb.com/download-technical-preview/). If it does not resolve your problem, please feel free to reopen the issue by adding a new comment.

Thanks!
