### ISSUE TITLE
Support-Links should link to Documents corresponding the current version of Admin i.e. 3.4 ...

### ISSUE THREAD

**Issue by lanluu** [arangodb/arangodb#6443]
ArangoDb 3.4 RC1 - Admin
![image](https://user-images.githubusercontent.com/3998945/45292192-ba92c180-b4f4-11e8-9cae-d2f2a0e0fa23.png)

... instead of latest stable version i.e. 3.3

**Comment by maxkernbach** [comment]
Hi @lanluu,

thanks for reporting. This issue is adressed by https://github.com/arangodb/arangodb/pull/6694.

**Comment by vinaypyati** [comment]
Hi @lanluu,

3.4.0-RC3 has been released and it includes a fix for the links and also now the support page includes a column to Official Drivers & Integrations. You can download it from the [download section](https://www.arangodb.com/download-technical-preview/). 

I am closing this ticket now. Please feel free to comment if the issue persists

Thanks!
