### ISSUE TITLE
Fuzzy analyzer for arangosearch views ?

### ISSUE THREAD

**Issue by matcho** [arangodb/arangodb#6447]
## My Environment

* __ArangoDB Version__:        3.4 RC1
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server

## Question

Hello,

I've been testing Arangosearch views in 3.4 RC1 and this is quite powerful and very promising !

Just to know : do you plan to release some day a fuzzy analyzer, who would allow searching for badly-spelled words ?
Or maybe there will be a way to code one manually, let's say with a simple Levenshtein distance as a score ?
This would be a total killler feature !

For now Arangosearch is already great :)

Mathias

**Comment by gnusi** [comment]
@matcho FYI we're currently working on adding fuzzy queries support, the plan is to have it in the next feature release.

**Comment by gnusi** [comment]
@matcho it took a bit longer than expected, but please note that fuzzy match functionality will become a part of upcoming ArangoDB 3.7

**Comment by matcho** [comment]
Great news ! Thank you very much.

**Comment by dothebart** [comment]
Hi, 
we may finaly close this with the availability of [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) - thanks for bearing with us!
