### ISSUE TITLE
req.body returns empty object

### ISSUE THREAD

**Issue by rathoreahsan** [arangodb/arangodb#6483]
## My Environment

* __NodeJS__
* __Express__ 
* __Pug__

## My Code

**Routes.js**

```javascript
router.post('/', (req, res) => {`
  try {
    req.body = Object.keys(req.body);
    console.log("Not Error:" + ' %j ', req.body);
  }catch(err){
    req.body = req.body
    console.log("Error:" + ' %j ', req.body);
  }
});
```

**header.pug**
```pug
  form(method="post" action="/youtube")
     select#ddlCountries.form-control(name=ddlCountries,onchange='this.form.submit()')
        each country in countries
            if country.code == 'US'
               option(value=country.code selected)= country.name
               else
               option(value=country.code)= country.name
```
__Problem__:

Try statement returns: `Not Error: [ ]`  an empty object. I am submitting the form on `onchange` event of dropdown selection, and I want to get selected value of dropdown in the post route. 

Kindly help!

__Expected result__:
I want to get selected value of dropdown in the post route.

**Comment by Simran-B** [comment]
You didn't mention ArangoJS nor Foxx. How is this related to ArangoDB?
