### ISSUE TITLE
Document not found when removing records

### ISSUE THREAD

**Issue by gurisko** [arangodb/arangodb#6495]
## My Environment

* __ArangoDB Version__:        3.3.14
* __Storage Engine__:             MMFile
* __Deployment Mode__:       Single Server
* __Configuration__:               -
* __Infrastructure__:               -
* __Operating System__:        Debian 8
* __Used Package__:              Debian or Ubuntu .deb

## Component, Query & Data

__Affected feature__:
AQL

__AQL query (if applicable)__:
```
FOR rec IN vTest
    FILTER rec._ci == 'id'
    REMOVE rec IN vTest
```

__AQL explain (if applicable)__:
```Query string:
 FOR rec IN vTest FILTER rec._ci == 'id' REMOVE rec IN vTest

Execution plan:
 Id   NodeType        Est.   Comment
  1   SingletonNode      1   * ROOT
  6   IndexNode          1     - FOR rec IN vTest   /* skiplist index scan */
  5   RemoveNode         0       - REMOVE rec IN vTest

Indexes used:
 By   Type       Collection   Unique   Sparse   Selectivity   Fields                           Ranges
  6   skiplist   vTest        false    false            n/a   [ `_ci`, `ipList[*].netLong` ]   (rec.`_ci` == "id")

Optimization rules applied:
 Id   RuleName
  1   remove-data-modification-out-variables
  2   use-indexes
  3   remove-filter-covered-by-index
  4   remove-unnecessary-calculations-2

Write query options:
 Option                   Value
 ignoreErrors             false
 waitForSync              false
 nullMeansRemove          false
 mergeObjects             true
 ignoreDocumentNotFound   false
 readCompleteInput        true
 useIsRestore             false
 consultAqlWriteFilter    false
 ignoreRevs               true

```

__Dataset__:
* only vTest collection with one skiplist index - field: "_ci, ipList[*].netLong"
* only one record in vTest:
```{
  "_ci": "id",
  "ipList": [
    {
      "netLong": 180906496
    },
    {
      "netLong": 168430080
    }
  ]
}
```

## Steps to reproduce

1. Create vTest collection
2. Add a new record (above)
3. Execute the query

__Problem__:
*Query: AQL: document not found (while executing)*
The cause of this seems to be the applied index which seems to create _id duplicates during the query execution:
```
FOR rec IN vTest
    FILTER rec._ci == 'id'
    COLLECT id = rec._id WITH COUNT INTO c
    RETURN {id, count: c}
```

__Expected result__:
...

**Comment by graetzer** [comment]
I can reproduce this fairly easy, we will have a look and fix it. For reference:
```js
db._create('vTest');
db.test.save({"_ci": "id","ipList": [{"netLong": 180906496},{"netLong": 168430080}]});
db.vTest.ensureIndex({type:'skiplist', fields:["_ci", "ipList[*].netLong"]});
db._query("FOR rec IN vTest FILTER rec._ci == 'id' REMOVE rec IN vTest");
```

**Comment by graetzer** [comment]
fixed in https://github.com/arangodb/arangodb/pull/6510

**Comment by jsteemann** [comment]
Fixed for 3.3.16

**Comment by gurisko** [comment]
Thanks for the fix. Do you have any estimate when 3.3.16 could be released? This bug is quite a blocker for us.

**Comment by jsteemann** [comment]
It's always hard to provide an estimate for release dates, as the effective release dates are determined by what issues are reported and fixed in total, and by how quick the QA can be completed.
If you are happy with a preview release of 3.3.16 for a specific platform, I think we can provide it rather quickly. Is that an option?

**Comment by gurisko** [comment]
We discussed this internally and decided that the suggested preview release is not needed at the very moment. However things change and I might come begging for it in the future :).

**Comment by OmarAyo** [comment]
Hi @gurisko 

ArangoDB version 3.3.16 has been officially released - I am going ahead and close this ticket now.

Tickets can be re-opened at any time by adding a new comment.

Best,
Omar Ayoubi

**Comment by gurisko** [comment]
That was quick! Thanks!
