### ISSUE TITLE
How to list current configuration options of running arangod server ?

### ISSUE THREAD

**Issue by matcho** [arangodb/arangodb#6558]
## My Environment

* __ArangoDB Version__:        3.3.15
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Infrastructure__:               own
* __Operating System__:        Debian 9
* __Used Package__:              Debian or Ubuntu .deb

## This is just a question

Is it possible to list currently used configuration options in a running arangod instance ?

I just added one or two options in `arangod.conf` and would like to make sure they are used, but the log doesn't say anything at startup…

Thank you !
All the best,
Mathias

**Comment by jsteemann** [comment]
One way to do it is to connect with an ArangoShell and run
```js
db._executeTransaction({ collections: {}, action: function() { return require("internal").options(); } })
```

**Comment by matcho** [comment]
Thank you ! Great :+1:
