### ISSUE TITLE
Can't use ArangoSearch views with edges

### ISSUE THREAD

**Issue by timeau** [arangodb/arangodb#6618]
## My Environment

* __ArangoDB Version__:        3.4rc1
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   Manual Start
* __Configuration__:              3 physical hosts, each have DBS and agent. Coordinator runs on first of them 
* __Infrastructure__:               own
* __Operating System__:        CentOS 7
* __Used Package__:              RedHat .rpm

Same as https://github.com/arangodb/arangodb/issues/6616

## Component, Query & Data

__AQL query (if applicable)__:
Next query return a syntax error:
```
WITH pmfull,pmlinks,pmcfull
for doc in v_twins 
    SEARCH PHRASE(doc.AUTH,'Evans','text_en')
    LIMIT 10
    for v,e,p IN OUTBOUND doc pmlinks
    return v
```
But this works fine:
```
WITH pmfull,pmlinks,pmcfull
for doc in pmfull 
    filter doc.PMID IN [334,362,372]
    LIMIT 100
    for v,e,p IN OUTBOUND doc pmlinks
    return {"pmid":doc.PMID,"pmcid":v.PMCID,"from":e._from,"to":e._to,"pm":doc.TITL,"pmc":v.TITLE}
```

If I add view "v_twins" into WITH statement, still syntax error.

__Dataset__:

I have an ArangoDb cluster (version 3.4rc1) and three collections: "pmfull" (document, 29 million docs), pmcfull (document, 5 million docs) and "pmlinks" (edges, 4.5 million). Last collection stores links between first two document collections. 
ArangoSearch view "v_twins" covers both collections.

__Replication Factor & Number of Shards (Cluster only)__:
_Replication factor_: 1
_Number of Shards_:64

__Problem__:
There is no possibility to use search using view together with edge collection. Always get a syntax error, with or without mention view in "WITH" statement.

**Comment by vinaypyati** [comment]
Hi @timeau,

Thanks for reporting the issue. 
This issue is fixed and will be included in 3.4.0 RC3. We will keep you informed about 3.4.0 RC3 release.

Best,
