### ISSUE TITLE
ArangoDB on Windows hanging...

### ISSUE THREAD

**Issue by frankmayer** [arangodb/arangodb#662]
Besides my main Linux installations of ArangoDB, I also occasionally use a local installation on my Windows 7 (x64). Mainly for running ArangoDB-PHP tests also on Windows. 

So, I **upgraded** the Windows installation a few days ago, from 1.3.1(I think it was) to 1.4.0.

Today I was testing the ArangoDB-PHP Driver and the tests were suddenly failing (only locally on the windows machine). I closed the Batch window, and reopened it, and the tests were running successfully. I'd like to note here, that I hadn't turned off my machine since yesterday, so that batch window was open for at least 12 hours if I remember correctly.

I also noticed that the database files are not deleted from the data directory (The ones that are created and deleted through the ArangoDB-PHP test suite.)

I couldn't attach a zip file here, so I am sending the zipped data directory via mail to @jsteemann (Please also check Spam folder :smile: ) for analysis.

**Comment by Dashue** [comment]
I had this hit me in 2.6.1 on windows 64. Was caused by having old deleted databases lying around. I hade to manually delete the the ones reported by the arandodb --upgrade.
