### ISSUE TITLE
SEARCH ANALYZER and LIMIT

### ISSUE THREAD

**Issue by jlbprof** [arangodb/arangodb#6625]
## My Environment

*3.4.0-RC.1:
*RocksDB :
*Single Server:       
*automatically started by OS: 
*??:               
*In a Lubuntu VM:
* Lubuntu 18.04:
*downloaded deb:

## Component, Query & Data

__Affected feature__:
ArangoSearch/SEARCH ANALYZER

AQL
FOR doc IN SearchItBaby SEARCH ANALYZER (doc.tags == 'c', 'text_en') LIMIT 10 RETURN doc
vs.
FOR doc IN SearchItBaby SEARCH ANALYZER (doc.tags == 'c', 'text_en') RETURN doc

__AQL explain (if applicable)__:
Query String:
 FOR doc IN SearchItBaby SEARCH ANALYZER (doc.tags == 'vpython' AND doc.tags != 'hook', 'text_en') 
 LIMIT 10 RETURN doc

Execution plan:
 Id   NodeType            Est.   Comment
  1   SingletonNode          1   * ROOT
  2   EnumerateViewNode      1     - FOR doc IN SearchItBaby SEARCH ANALYZER(((doc.`tags` == "vpython") && (doc.`tags` != "hook")), "text_en")   /* view query */
  3   LimitNode              1       - LIMIT 0, 10
  4   ReturnNode             1       - RETURN doc

Indexes used:
 none

Optimization rules applied:
 Id   RuleName
  1   handle-arangosearch-views

VS

Query String:
 FOR doc IN SearchItBaby SEARCH ANALYZER (doc.tags == 'vpython' AND doc.tags != 'hook', 'text_en') 
 RETURN doc

Execution plan:
 Id   NodeType            Est.   Comment
  1   SingletonNode          1   * ROOT
  2   EnumerateViewNode      1     - FOR doc IN SearchItBaby SEARCH ANALYZER(((doc.`tags` == "vpython") && (doc.`tags` != "hook")), "text_en")   /* view query */
  3   ReturnNode             1       - RETURN doc

Indexes used:
 none

Optimization rules applied:
 Id   RuleName
  1   handle-arangosearch-views

__Dataset__:
 5 million lines of ipsum lorem

The collections page will not let me select any of the text, the tags field is a space separated list of "tags"

__Replication Factor & Number of Shards (Cluster only)__:
Single DB

## Steps to reproduce

1.  Run the first query (with the LIMIT statement)
2.  Run the second query (without the LIMIT statement)

__Problem__:

When I have the LIMIT statement, it immediately returns with no data.   If I do not have the limit statement it takes some time and returns exactly 1000 records (out of 5 million), as if there is a built in limit of 1000.

__Expected result__:

Is this a bug, or do I not understand something about SEARCH ANALYZER and LIMIT?

Thanx

**Comment by jlbprof** [comment]
oops wrong explains, but it is nearly identical

**Comment by jlbprof** [comment]
The view

```{
  "type": "arangosearch",
  "links": {
    "questions": {
      "analyzers": [
        "identity"
      ],
      "fields": {
        "tags": {
          "analyzers": [
            "text_en"
          ]
        }
      },
      "includeAllFields": false,
      "trackListPositions": false,
      "storeValues": "none",
      "id": "1779",
      "type": "arangosearch",
      "view": "hAAA67C214AEA/1627"
    }
  },
  "cleanupIntervalStep": 10,
  "consolidationIntervalMsec": 60000,
  "consolidationPolicy": {
    "segmentThreshold": 300,
    "threshold": 0.8500000238418579,
    "type": "bytes_accum"
  },
  "id": "1627"
}

**Comment by jlbprof** [comment]
Indexes

```
606 | fulltext | false | true | n/a | n/a | tags
625 | hash | false | false | false | 0.02% | userid
639 | skiplist | false | false | false | 99.99% | date
660 | hash | false | false | false | 0.00% | questionid

**Comment by jlbprof** [comment]
An example record:

```{
  "text": "Tempora adipisci numquam tempora quiquia non. Ipsum quisquam modi tempora amet amet. Quaerat magnam quisquam labore quiquia est aliquam sed. Quisquam quiquia velit quaerat ipsum modi quaerat ut. Ut etincidunt sed dolorem modi ipsum est labore. Numquam amet aliquam neque. Labore labore ipsum voluptatem amet neque neque est.",
  "tags": "azure-machine-learning spring-form ocean ijetty cloud-automation-manager",
  "userid": 370,
  "date": 1246161329,
  "title": "Sed porro sed porro porro magnam sit dolorem.",
  "category": 7
}

**Comment by gnusi** [comment]
@jlbprof thank you for posting this issue. 
There is no correlation between LIMIT and EnumerateViewNode at all, so probably there is a bug we need to check in advance.
BTW there is `TOKENS` function you can use to check analyzer's output, e.g.
```
arangod> db._query('RETURN TOKENS("azure-machine-learning spring-form ocean ijetty cloud-automation-manager", "text_en")')
[object GeneralArrayCursor, count: 1, cached: false]
[ 
  [ 
    "azur", 
    "machin", 
    "learn", 
    "spring", 
    "form", 
    "ocean", 
    "ijetti", 
    "cloud", 
    "autom", 
    "manag" 
  ] 
]
```
Could you provide us a small dataset and corresponding query that work/don't work with/without limit statement?

**Comment by jlbprof** [comment]
I tried creating a new db, with maybe 1000 records in it, but the same setup.  Unfortunately it does not fail.  I will keep playing with it.

**Comment by jlbprof** [comment]
I tried to download a "debug package" that comes back with a 400 error.

**Comment by jlbprof** [comment]
I think there may be some artifact associated with that database.  It is/was a test database that I setup.   So I recreated the db from scratch, same size, same content, same everything and it is working now.

You can close this if you want, otherwise let me know if there is some low level debug information I can give you regarding the bad database.

Thank you for your time.

Julian

**Comment by jlbprof** [comment]
I do not know how to change the status, of "Waiting for User Reply" as I have replied.

**Comment by gnusi** [comment]
@jlbprof I would prefer to close this issue for now then. In case of error feel free to reopen the issue or create a new one. Thank you!
