### ISSUE TITLE
Simple Query by Example with `null` should work as it does in AQL queries

### ISSUE THREAD

**Issue by moonglum** [arangodb/arangodb#666]
`null` is defined to be the absence of the attribute in AQL. This is a very handy thing in a schema free environment and querying for the absence or existence (indepdendent of the value) of an attribute is a very useful thing.

@kaerus-component reported to me that using the `null` value in a simple query doesn't work as I described above. IMHO that is a bug.

**Comment by dothebart** [comment]
Meanwhile simple queries wrap AQL. The described missbehaviour has been fixed - closing.

ArangoDB 3.0 RC2 is available for download: https://www.arangodb.com/download-preview/
