### ISSUE TITLE
 ERROR - [HTTP 500][ERR 1521] AQL: could not lock all shards : timeout in cluster operation (while executing)

### ISSUE THREAD

**Issue by RohanKumbhar1** [arangodb/arangodb#6709]
## My Environment

* __ArangoDB Version__:        ArangoDB 3.3.12
* __Storage Engine__:             MMFiles 
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   ArangoDB Starter 
* __Configuration__:               3 node cluster, with 3 coordinator, 3 db servers
* __Infrastructure__:               own
* __Operating System__:        Ubuntu 16.04.4
* __Used Package__:              Debian or Ubuntu .deb 

## Component, Query & Data

__Affected feature__:
AQL query using web interface 

__AQL explain (if applicable)__:
 ERROR - [HTTP 500][ERR 1521] AQL: could not lock all shards : timeout in cluster operation (while executing)

__Replication Factor & Number of Shards (Cluster only)__:
1

**Comment by OmarAyo** [comment]
Hi @RohanKumbhar1,

Just sending a followup - how things are going? Did you have the chance to upgrade to our latest version (we have released version 3.3.17 yesterday)? If yes, is the issue still occurring?

Kindly, reply to vinaypyati's question, this will help us with our troubleshoot 

Many Thanks

**Comment by RohanKumbhar1** [comment]
Hi Omar,

we have not upgraded arango version , temporary fix for the above issue is restart arangodb cluster.
Also we were using only 1 shard with 0 replica for each collection. So we have decided to use 3 replication factor now which might fix this issue.

Thanks,
Rohan

**Comment by OmarAyo** [comment]
Hi @RohanKumbhar1 

Thanks for providing us with a status update, and good to know that you set the ReplicatioFactor > 1

In fact, using ReplicationFactor </= 0 does not make much sense in an ArangoDB Cluster environment. We strongly suggest to set it up to > 1. 

Please let us know if can go ahead and close this ticket or if any further information is needed here.

Best,

**Comment by vinaypyati** [comment]
Hi @RohanKumbhar1,

Hope the suggestions by OmarAyo were helpful. Since there was no feedback in a while, I am going ahead and closing this issue. Please feel free to reopen if you have any further questions.

Best,
