### ISSUE TITLE
Bug/Feature? - WebUI Ace editor shortcuts not working

### ISSUE THREAD

**Issue by wshayes** [arangodb/arangodb#6710]
## My Environment
ArangoDB Version: 3.3.13
Deployment Mode: Docker
Operating System:  Ubuntu 16.04
Affected feature: Web UI

## Problem:

Would like to be able to use the Ace Editor shortcut CMD-L for toggling comments on and off in the Web UI Query editor.  It looks like you are using the Ace editor (from inspecting the code), but the shortcut is not working.  I did try the shortcut on the Ace Editor editor website (https://ace.c9.io/demo/keyboard_shortcuts.html), and it works perfectly there.

## Expected result:
Ability to use the Ace Editor keyboard shortcuts - especially the togglecomment shortcut.

Awesome feature (the Web UI) - I use it a LOT - just want to use it even more :)

**Comment by vinaypyati** [comment]
Hi @wshayes,

The available keyboard shortcuts can be viewed by clicking on the _keyboard icon_ which is at the bottom left corner of the Web UI - just beside the version. The shortcut to toggle on and off comments is `Ctrl/Cmd + Shift + C `

![image](https://user-images.githubusercontent.com/34657484/46473668-3543b980-c7e1-11e8-9701-2e1e6ca259fc.png)

Thanks!

**Comment by wshayes** [comment]
Thanks!
