### ISSUE TITLE
Aggeragate function MAX() returns empty values

### ISSUE THREAD

**Issue by vlabmichl** [arangodb/arangodb#6728]
## My Environment

* __ArangoDB Version__: 3.3.14        
* __Storage Engine__: MMFiles             
* __Deployment Mode__:  Single Server     
* __Deployment Strategy__: Manual Start in Docker  
* __Configuration__:               
* __Infrastructure__:   own            
* __Operating System__:  Debian       
* __Used Package__:   Docker official           

## Component, Query & Data

__Affected feature__: AQL

__AQL query (if applicable)__:
```aql
FOR ke IN knoten_extern
    COLLECT AGGREGATE
    hwMin = MIN(ke.hw),
    hwMax = MAX(ke.hw),
    rwMin = MIN(ke.rw),
    rwMax = MAX(ke.rw)
RETURN { hwMin, hwMax, rwMin, rwMax }
```

Result:
```
[
  {
    "hwMin": 47.43814309,
    "hwMax": "",
    "rwMin": 10.2337726,
    "rwMax": ""
  }
]
```
__AQL explain (if applicable)__:

```
Query string:
 FOR ke IN knoten_extern
     COLLECT AGGREGATE
     hwMin = MIN(ke.hw),
     hwMax = MAX(ke.hw),
     rwMin = MIN(ke.rw),
     rwMax = MAX(ke.rw)
 RETURN { hwMin, hwMax, rwMin, rwMax }

Execution plan:
 Id   NodeType                   Est.   Comment
  1   SingletonNode                 1   * ROOT
  2   EnumerateCollectionNode   27253     - FOR ke IN knoten_extern   /* full collection scan */
  3   CalculationNode           27253       - LET #5 = ke.`hw`   /* attribute expression */   /* collections used: ke : knoten_extern */
  5   CalculationNode           27253       - LET #9 = ke.`rw`   /* attribute expression */   /* collections used: ke : knoten_extern */
  7   CollectNode               21802       - COLLECT AGGREGATE hwMin = MIN(#5), hwMax = MAX(#5), rwMin = MIN(#9), rwMax = MAX(#9)   /* sorted */
  8   CalculationNode           21802       - LET #13 = { "hwMin" : hwMin, "hwMax" : hwMax, "rwMin" : rwMin, "rwMax" : rwMax }   /* simple expression */
  9   ReturnNode                21802       - RETURN #13

Indexes used:
 none

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   remove-redundant-calculations
  3   remove-unnecessary-calculations
  4   move-calculations-up-2
```

__Dataset__:

KnotenExtern holds GeoCoords stored as floats in "hw" and "rw" fields.

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

Execute the the query against datasets.

__Problem__:
MAX() results are empty.

__Expected result__:
MAX() should be filled at least with the MIN() values (if they were the same by accident).

**Comment by vlabmichl** [comment]
@jsteemann I updated issue description with the result.

The weird thing for me is that `MIN()` returns a valid result and `MAX()` is simply empty.

**Comment by vlabmichl** [comment]
@jsteemann Question: How can I check if there are invalid values in my collection with AQL? Could you provide a code snippet? 

Thanks a lot.

**Comment by jsteemann** [comment]
Ah ok, got it. It looks like the results for `MAX` functions are empty strings.
This may actually be "expected" in case the dataset contains string values in `hw` and `rw`. `MAX` will also return the maximum value for strings or any other data type in AQL.
I am getting the same results as you after inserting a document as follows into the collection:
```
db.knoten_extern.insert({ hw: "", rw: "" });
```
This is because the empty string compares higher than any floating point value in AQL (please refer to [the manual](https://docs.arangodb.com/3.3/AQL/Fundamentals/TypeValueOrder.html) for the exact type and value order).

If you add some filter conditions to the query, e.g.
```
FILTER TYPENAME(ke.hw) == 'number' && TYPENAME(ke.rw) == 'number'  
```
it will filter out the non-numeric values and will not use them for the min/max calculation.

**Comment by vlabmichl** [comment]
OK - thanks for the explanation. I was totally focused on the description of the collect and aggregat usage here:
* https://docs.arangodb.com/3.3/AQL/Operations/Collect.html

Probably a hint on that manual page regarding the mentioned type order behaviour would be helpful to avoid wrong expectations.

Maybe helpful for other users...
:-)

Thanks for the filter statement. I added the code to my query as follows now the result is as expected.

The complete query as reference for the solution of that issue:
```
FOR ke IN knoten_extern
    FILTER TYPENAME(ke.hw) == 'number' && TYPENAME(ke.rw) == 'number'
    COLLECT AGGREGATE
    hwMin = MIN(ke.hw),
    hwMax = MAX(ke.hw),
    rwMin = MIN(ke.rw),
    rwMax = MAX(ke.rw)
RETURN { hwMin, hwMax, rwMin, rwMax }
```

**Comment by vlabmichl** [comment]
Info: Inverted the provide filter to select all the none `number` values an found three datasets that had no `hw` and `rw` value set.
