### ISSUE TITLE
Another posssible slow query

### ISSUE THREAD

**Issue by rotatingJazz** [arangodb/arangodb#673]
Not sure if it 's a bug or I 'm doing something wrong.

I have a collection that contains a field named categories and there I store a json array of `{"hash": "somehash"}`, e.g. `[{"hash":"5479a849610e337ceeba89910905a18f"}]`

I have added a skiplist to "categories.hash"

```
  {
    "id" : "profiles/14597709144",
    "type" : "skiplist",
    "unique" : false,
    "fields" : [
      "categories.hash"
    ]
  }
```

This query works

```
FOR i IN profiles
    FOR j IN TO_LIST(i.categories)
    FILTER j.hash == '5479a849610e337ceeba89910905a18f'
LIMIT 10
RETURN i
```

The profile collection contains ~30k entries. To test if `j.hash` is utilising the skiplist, I did

```
FOR z IN profiles
FOR i IN profiles
    FOR j IN TO_LIST(i.categories)
    FILTER j.hash == '5479a849610e337ceeba89910905a18f'
LIMIT 10
RETURN i
```

Which is very very slow.

Doing 

```
FOR i IN profiles
    FOR j IN i.categories
    FILTER j.hash == '5479a849610e337ceeba89910905a18f'
LIMIT 10
RETURN i
```

errors with 

```
[1563] list expected
```

**Comment by jsteemann** [comment]
Note that from ArangoDB 2.8, indexing array values will be supported.
For the data mentioned above, the index should probably be defined on attribute `categories[*].hash`.

The query would then be:
```
FOR doc IN profiles
  FILTER '5479a849610e337ceeba89910905a18f' IN doc.categories[*].hash
  RETURN doc
```
