### ISSUE TITLE
document update: ignoreRevs parameter ignored

### ISSUE THREAD

**Issue by dvd7587** [arangodb/arangodb#6770]
## My Environment

* __ArangoDB Version__:        3.3.16
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   ArangoDB Starter in Docker
* __Configuration__:               
* __Infrastructure__:               own
* __Operating System__:        Ubuntu 16.04
* __Used Package__:              Docker - official Docker library

## Component, Query & Data

__Affected feature__:
Document update via Java driver (Collection::updateDocument)

## Steps to reproduce

1. create a document
2. update a document
3. update a second time, with ``ignoreRevs(false)`` and the first revision.

__Problem__:
Document update goes through: 
Example data from `execute:147, VstCommunicationSync (com.arangodb.internal.velocystream)`, 
which should be the very last layer before sending the message (data refers to point 3. above):

Message requestMessage.head:
``[1,1,"test-database",5,"\/_api\/document\/mydocs\/1",{"keepNull":"false","mergeObjects":"true","returnNew":"true","ignoreRevs":"false"},{}]``
requestMessage.body:
``{"_rev":"_Xje4cm---_","description":"newDescription","updatedAt":"2018-10-09T09:50:10.363000000Z"}``

Message responseMessage.head:
``[1,2,202,{"Location":"\/_db\/test-database\/_api\/document\/mydocs\/1","Etag":"\"_XjfDeMC--_\""}]``
 responseMessage.body:
``{"_id":"mydocs\/1","_key":"1","_oldRev":"_Xje5UDO--_","_rev":"_XjfDeMC--_","new":{"_id":"mydocs\/1","_key":"1","_rev":"_XjfDeMC--_","description":"newDescription","updatedAt":"2018-10-09T09:50:10.363000000Z"}}``

__Expected result__:
Document update should fail

**Comment by jsteemann** [comment]
@dvd7587 : I just verified that the `ignoreRevs` parameters is actually honored on the server side when trying to send isolated requests to the server.
As this issue only shows a single request and the server's response, I am wondering if you could provide the code fragment that does the entire 3 requests (insertDocument, updateDocument w/o ignoreRevs and updateDocument w/ ignoreRevs). That may help shed some light on this.
Thanks!

**Comment by dvd7587** [comment]
I'll come back with a minimal example

**Comment by dvd7587** [comment]
I can add that, when I use the ifMatch("revision") method instead, document update breaks as expected

**Comment by graetzer** [comment]
https://github.com/arangodb/arangodb/pull/6854

**Comment by sleto-it** [comment]
Hi,

Thanks again for opening this issue

Versions 3.3.19 has been released and it includes a fix for this problem (note that there was no public 3.3.18 - the next release after 3.3.17 is 3.3.19)

I am closing this ticket now. Please feel free to comment if the issue persists

Many thanks,
