### ISSUE TITLE
[Feature Request] Interface for writing Foxx service with language other than javascript

### ISSUE THREAD

**Issue by poland-can-into-space** [arangodb/arangodb#6780]
# My Environment

* __ArangoDB Version__:        3.3.16

## Description
I want to have a way to build ArangoDB Service without Foxx.
It is painful writing complicated codes in Javascript; if there was an interface that allows the use of language designed for backend programming, like Go lang, it would be a great favour.
I tried to figure this out by reading the arangodb codes, but I couldn't figure out.

**Comment by dothebart** [comment]
Hi, 
I just discussed this with our product manager, and this is not going to happen.
If you like to draw inspiration from our foxx implementation and re-implement it in another language, feel free to browse the source for inspiration and ask questions. 

Closing as "won't fix"
