### ISSUE TITLE
get common elements from a result which consists of more than 1 array in arangodb

### ISSUE THREAD

**Issue by prachitabafna** [arangodb/arangodb#6793]
I want to fetch common elements from multiple arrays. The no. of arrays resulted would keep changing depending upon the no. of tags in array a[].

As a first step, my query and result I get is as shown below:

```
let a=["Men","Women","Accessories"]
let c=(for i in a
       Let d=Concat("Tags/",i)
       return d)

for i in c
   let m=(for y in outbound i TC 
          return y._key)
   return m
```
and result I get is:

```
[
  [
    "C1",
    "C5",
    "C7",
    "C3"
  ],
  [
    "C2",
    "C5",
    "C6",
    "C4"
  ],
  [
    "C7",
    "C5",
    "C6"
  ]
]
```
From this result, I want only common element as a result i.e "C5" (here).

How can I get that?

**Comment by maxkernbach** [comment]
Hi @prachitabafna,

has the previous comment solved your problem or do you have any further questions?

**Comment by prachitabafna** [comment]
Hi Maxkernbach,
I want to directly utilize the result i shared, in the query itself and
give the intersection as a final output.
The solution you gave is that I need to take into consideration the result
manually.

Thanks,
Prachita

**Comment by Simran-B** [comment]
You don't have to return the intersection immediately, you can also store it in a variable and return it later:

```js
LET D = [["C1","C5","C7","C3"],["C2","C5","C6","C4"],["C7","C5","C6"]] 
LET intersection = APPLY("INTERSECTION", D)
// do something else
RETURN intersection
```

**Comment by OmarAyo** [comment]
Hi @prachitabafna 

Did you find Simran's message useful for you? How things are going now?

Please provide a status update

Best,

**Comment by maxkernbach** [comment]
I am closing this issue as "solved" for now since we have not received any feedback in a while. 

In case Simran's answer did not resolve your problem, please feel free to comment and we will reopen this issue.
