### ISSUE TITLE
No init.d script for Debian 9, in the mean while systemd doesn't support WSL

### ISSUE THREAD

**Issue by fuweichin** [arangodb/arangodb#6811]
## My Environment

* __ArangoDB Version__:        3.3.17
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   ArangoDB Starter
* __Configuration__:               defaults by 'apt-get install'
* __Infrastructure__:               WSL
* __Operating System__:        Debian 9  WSL
* __Used Package__:              Debian

## Component, Query & Data

__Affected feature__:

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. On Debian 9 WSL, install arangodb3 for Debian 9 via apt-get according to documentation [Download ArangoDB for Debian](https://www.arangodb.com/download-major/debian/)

__Problem__:
There is no arangodb3 init.d-script, so I cannot use `service arangodb3 start` to start ArangoDB, neither can I use `systemctl start arangodb3.service`  to start ArangoDB since [systemd doesn't support WSL](https://github.com/systemd/systemd/issues/8036)

__Expected result__:
Even though I installed ArangoDB 3 for Debian 8 on my Debian 9 WSL as a workaround, I want to start ArangoDB in normal way on Debian 9 WSL. This can be done by adding arangodb3 init.d-script for Debian 9, just like arangodb3 init.d-script for Debian 8.

**Comment by vinaypyati** [comment]
Hi @FuweiChin,

Thanks for opening an issue, I could reproduce this issue with 3.3.19 Debian 9 packages on WSL. Now that 3.4.1 is released, can you upgrade and check if you could still find the init.d scripts missing? You can find the download options for 3.4.1 in the [download section](https://www.arangodb.com/download-major/debian/).

Thanks!

**Comment by dothebart** [comment]
With the availability of [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) closing this as out of date.
