### ISSUE TITLE
Howto Import/Export Sample Datasets in a compatible format? 

### ISSUE THREAD

**Issue by X4** [arangodb/arangodb#683]
I've a stupid question, hope you can help =)
How can I import [social network datasets from Facebook](http://snap.stanford.edu/data/#socnets) into ArangoDB?
And how to dump the data again from ArangoDB, in order to visualize the changes with GraphViz or SocNetV (or any other tool)?

**Comment by nirupamavaid** [comment]
Hi,
I'm using the CSV import (using arangimp) for importing graphs. I can create edged for directed graphs using _to and _from attributes in CSV files. But I'm unable to find any information regarding the **format** for creating **undirected graph edges** using **csv files**.
