### ISSUE TITLE
Low Priority Improvements for Windows installer

### ISSUE THREAD

**Issue by frankmayer** [arangodb/arangodb#684]
During installing ArangoDB on Windows I have noticed the following:

* The installer does not __upgrade__ ArangoDB. One first has to uninstall the old one and then run the installer. Would be nice if this could be made better

* The installer does not __honor__ the location of a previous installation (because it has been uninstalled :smile:, and always defaults to the default __program files__ path)

**Comment by dothebart** [comment]
Its currently possible to keep the old version installed during the new installation and then uninstall the old. 
Does this fix this issue?

**Comment by dothebart** [comment]
ArangoDB 3.0 RC2 is available for download: https://www.arangodb.com/download-preview/
