### ISSUE TITLE
String prefix filter using skiplist index

### ISSUE THREAD

**Issue by Yogu** [arangodb/arangodb#6877]
## My Environment

* __ArangoDB Version__:        3.3.13
* __Storage Engine__:             MMFiles
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Operating System__:        Windows 10

## Component, Query & Data

__Affected feature__: AQL query using web interface

__AQL query (if applicable)__:

```
FOR t in test FILTER t.value LIKE "prefix%" RETURN t
```

__AQL explain__:

```
Execution plan:
 Id   NodeType                   Est.   Comment
  1   SingletonNode                 1   * ROOT
  2   EnumerateCollectionNode   10000     - FOR t IN test   /* full collection scan */
  3   CalculationNode           10000       - LET #1 = LIKE(t.`value`, "prefix%")   /* simple expression */   /* collections used: t : test */
  4   FilterNode                10000       - FILTER #1
  5   LimitNode                     1       - LIMIT 0, 1
  6   ReturnNode                    1       - RETURN t

Indexes used:
 none

Optimization rules applied:
 none
+
```

## Description

Is there a way to utilize skiplist indices to do a string-prefix filter? Other database systems, e.g. [mysql](https://stackoverflow.com/questions/2011304/in-mysql-find-strings-with-a-given-prefix), use an index for `LIKE` queries that do a prefix filter. For ArangoDB, however, I have not found any way to use the index for the prefix search.

I even thought I was clever using a query like `FILTER t.value >= 'prefix' && t.value < 'prefy'`, but that would require knowledge of the server's collation regarding to character sorting (it's not as simple as incrementing the code point), so it seems very brittle to me.

Is there a way I missed? If yes, it would be good to document this in the manual section about indices. If not, would you consider adding this feature?

I guess a workaround for some use cases would be to use fulltext indices, but that's not exactly the same because of the tokenization.

**Comment by Yogu** [comment]
I figured out a workaround that I earlier discarded before discovering the collator problem: You can do a query like `FILTER t.value >= 'prefix' && t.value <= 'prefix\u10FFFF'` - in the hopes that every collator sees `\u10FFFF` as the last character.

**Comment by Yogu** [comment]
The workaround has one perk: It is inconsistent on case sensitivity. At least in the collation on my installation, the ordering looks like this:

```json
[
  "A",
  "a",
  "AA",
  "Aa",
  "aA",
  "aa",
  "AB",
  "Ab",
  "aB",
  "ab",
  "B",
  "b"
]
```

This means that if the actual value is longer than the given prefix (i.e. it's a real prefix and not the whole string), the match will be case-insensitive. However, if the remaining suffix if empty, the search would sometimes be case-sensitive: If you search for the prefix `a`, `A` will not be found (because `A` < `a`), but `a` will match the prefix filter `A`. In order to avoid this, one needs to convert the given string to the lowest value within its case-sensitivity category. For ASCII characters, that's simply `UPPER()`, but that will not always be the case.

**Comment by Simran-B** [comment]
> � is 0x10FFFF - don't know how to properly escape that for AQL

Like in JavaScript, U+10FFFF can be represented as surrogate pair: `\uDBFF\uDFFF`.

**Comment by maxkernbach** [comment]
Hi @Yogu,

I am closing this issue to continue further discussion on Jira.

Thanks
