### ISSUE TITLE
speed up imports by arangoimp

### ISSUE THREAD

**Issue by jsteemann** [arangodb/arangodb#692]
Inspired by #683:

Importing data using arangoimp can probably be sped up by applying some changes to arangoimp and the client/server protocol for import.

A few guesses:
the main obstacle for speed probably is the HTTP traffic between arangoimp and arangod, plus the accompanying JSON serialisation/deserialisation.
Additionally, arangoimp processes the import file from top to botton. Once it has gathered "enough" data, it will send a packet to the server and wait for the response.
arangoimp is single-threaded, and this may also cause major slowdowns when compared to a parallel importer.
Some obvious "fixes" for speeding up the imports are thus:
- make arangoimp process the input file in parallel and upload to arangod in parallel
- use a more efficient format (requiring less parsing/processing) than JSON (probably just for imports)
- make the importer use compression (less network traffic)

**Comment by dothebart** [comment]
- ArangoImp is now multithreaded with ArangoDB 3.2 - which is the main problem.

**Comment by dothebart** [comment]
We're pleased to anounce that ArangoDB 3.2 containing this is now available for download - Closing.
