### ISSUE TITLE
Arangodb 3.4 RC2 installation in Windows 10

### ISSUE THREAD

**Issue by Whypins** [arangodb/arangodb#6960]
## My Environment

* __ArangoDB Version__:        Arangodb 3.4 RC2
* __Storage Engine__:             auto
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   NA
* __Configuration__:               NA
* __Infrastructure__:               own
* __Operating System__:        Windows 10
* __Used Package__:              Installer

## Component, Query & Data

__Affected feature__:
 Installation not working in Windows 10

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. Download the exe file and install.

__Problem__: Crashing everytime

__Expected result__: Should install and start the services automatically.

![1](https://user-images.githubusercontent.com/33902800/47162969-a66f8a80-d312-11e8-8396-3ba00f77e7a2.PNG)
![2](https://user-images.githubusercontent.com/33902800/47162973-a7a0b780-d312-11e8-8d2c-5fe4c3868d2b.PNG)

**Comment by Simran-B** [comment]
Thank you for the report. The issue with the dependency on a debug DLL was found also internally and got fixed already. The fix will be available as part of the next preview version, 3.4.0-RC3.

**Comment by kran** [comment]
@Simran-B hi Simran, Is there a milestone about 3.4 release version ?

**Comment by vinaypyati** [comment]
Hi @Whypins,  @kran,

3.4.0-RC3 has been released and it includes a fix for this problem. You can download it from the [download section](https://www.arangodb.com/download-technical-preview/). 

I am closing this ticket now. Please feel free to comment if the issue persists

Thanks!
