### ISSUE TITLE
 invalid traversal depth error

### ISSUE THREAD

**Issue by weiliangzu** [arangodb/arangodb#6966]
## My Environment

* __ArangoDB Version__:       3.3.17
* __Storage Engine__:             MMFiles
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:        Windows 8
* __Used Package__:              

## Component, Query & Data

__Affected feature__: AQL query using web interface

__AQL query (if applicable)__:
```
let path=(for p in any shortest_path 'node/10524076' to 'node/10524083' graph 'graph' return p)
 let len=length([1,1])
 for n,e,p in 1..length(path) any 'node/10524076'
 graph 'graph'
 options {bfs:true}
 filter n.age==length(path)
 return p
```
__AQL explain (if applicable)__:

__Dataset__:

Two collections: node(type document) and edge(type edge)
One graph: Its name is "graph" and has one relation from node to node via edge.

node:
```
[
  {
    "_key": "10524080",
    "_id": "node/10524080",
    "_rev": "_XmUrqeu--_",
    "age": 3,
    "name": "c"
  },
  {
    "_key": "10524076",
    "_id": "node/10524076",
    "_rev": "_XmUrdqy--B",
    "age": 1,
    "name": "a"
  },
  {
    "_key": "10524079",
    "_id": "node/10524079",
    "_rev": "_XmUrkhK--C",
    "age": 2,
    "name": "b"
  },
  {
    "_key": "10524083",
    "_id": "node/10524083",
    "_rev": "_XmUrxOm--C",
    "age": 4,
    "name": "d"
  }
]
```
edge:
```
[
  {
    "_key": "10524117",
    "_id": "edge/10524117",
    "_from": "node/10524080",
    "_to": "node/10524083",
    "_rev": "_XmUuGZC--_"
  },
  {
    "_key": "10524111",
    "_id": "edge/10524111",
    "_from": "node/10524076",
    "_to": "node/10524080",
    "_rev": "_XmUtxoa--_"
  },
  {
    "_key": "10524110",
    "_id": "edge/10524110",
    "_from": "node/10524076",
    "_to": "node/10524079",
    "_rev": "_XmUtrD---C"
  },
  {
    "_key": "10524116",
    "_id": "edge/10524116",
    "_from": "node/10524079",
    "_to": "node/10524083",
    "_rev": "_XmUuA3O--C"
  }
]
```
__Replication Factor & Number of Shards (Cluster only)__:
 None.

## Steps to reproduce

1. Create colection: node(type document) and edge(type edge)
2. Create a new graph with
   name:graph
   shards:1
   replication factor:1
   edge definitions: edge
   fromCollections: node
   toCollections:node
3. Add provided data
4. Excute the AQL query

__Problem__:

Query: AQL: invalid traversal depth (while instantiating plan)

__Expected result__:
```
[
  {
    "edges": [
      {
        "_key": "10524111",
        "_id": "edge/10524111",
        "_from": "node/10524076",
        "_to": "node/10524080",
        "_rev": "_XmUtxoa--_"
      }
    ],
    "vertices": [
      {
        "_key": "10524076",
        "_id": "node/10524076",
        "_rev": "_XmUrdqy--B",
        "age": 1,
        "name": "a"
      },
      {
        "_key": "10524080",
        "_id": "node/10524080",
        "_rev": "_XmUrqeu--_",
        "age": 3,
        "name": "c"
      }
    ]
  }
]
```

**Comment by Simran-B** [comment]
Simpler query:
```js
LET n = NOOPT(2)
FOR v IN 1..n ANY 'start' test RETURN v
```
With `LET n = 2`, *n* would be a constant and can be substituted, like `FOR v IN 1..2`.
`NOOPT()` forces it to be a runtime expression. The traversal depth must be known at query compile time however, it does not support runtime expressions.

You could split the query into two, to compute the path length first, then use this number as bind variable:

**Query 1**
```js
return length(
  for p in any
  shortest_path 'node/10524076' to 'node/10524083'
  graph 'graph'
  return true)
```

**Query 2** with bind var: `{"depth": ... }`
```js
for n,e,p in 1..@depth any 'node/10524076'
graph 'graph'
options {bfs:true}
filter n.age==@depth
return p
```

**Comment by OmarAyo** [comment]
Hi @weiliangzu 

Just sending a quick followup to check how things are going

Please, provide us with a status update

Many Thanks

**Comment by OmarAyo** [comment]
Hi @weiliangzu 

I am closing this issue as "solved" for now since we have not received any feedback from in a while.
Please feel free to comment and we will reopen this issue.

Best,

**Comment by lokeb** [comment]
for some reason, I am unable to use `n` in the subsequent query:
```js
let n = noopt(length(for v in outbound
  shortest_path 'airports/BIS' to 'airports/JFK' flights
  return v)-1)

for v in n outbound 'airports/BIS' flights
  filter v._id == 'airports/JFK'
  limit 5 
  return v
 ```
any reason?

**Comment by Simran-B** [comment]
@lokeb: As explained [above](https://github.com/arangodb/arangodb/issues/6966#issuecomment-431314262), what you try is not supported. Traversal min and max depth must be constant, which is the case if you use a number literal or a variable with a constant value like `LET n = 2`:

```js
Query string:
 LET n = 2
 FOR v IN n OUTBOUND "airports/BIS" flights
     RETURN v

Execution plan:
 Id   NodeType        Est.   Comment
  1   SingletonNode      1   * ROOT
  3   TraversalNode      4     - FOR v  /* vertex */ IN 2..2  /* min..maxPathDepth */ OUTBOUND 'airports/BIS' /* startnode */  flights
  4   ReturnNode         4     - RETURN v

...

Optimization rules applied:
 Id   RuleName
  1   remove-unnecessary-calculations
```

As you can see, `n` is substituted by the number literal and thus a constant value is supplied as traversal depth. A value computed at runtime is not allowed. `LET n = NOOPT(2)` forces `n` to be evaluated at runtime (no substitution), therefore an error is thrown.

You need to run this in two separate queries, one to calculate `n` and another where you use the computed value as (constant) traversal depth. Note that it can be a bind parameter, because bind parameters are known at query compile time and are thus constant.

Also see the [Pattern Matching add-on](https://www.arangodb.com/arangodb-training-center/graphs/pattern-matching/) to the Graph Course and [Multiple Paths Search](https://docs.arangodb.com/3.4/AQL/Examples/MultiplePaths.html) in the Cookbook.
