### ISSUE TITLE
Example Applications to ArangoDB App

### ISSUE THREAD

**Issue by muescha** [arangodb/arangodb#698]
as a follow up of #521 

I installed the app from app store and now i try to explore the DB

i miss a example database and Foxx app

(there should be a menu entry: install/uninstall example data/foxx app)

**Comment by jsteemann** [comment]
Installing example Foxx apps via the web interface is supported since ArangoDB 2.5 (or even 2.4, can't remember right now). A few example apps are available in a Foxx-specific app store.
