### ISSUE TITLE
Info about menubar icon is missing in the app

### ISSUE THREAD

**Issue by muescha** [arangodb/arangodb#699]
what i do:
i started first time the app (from app store)
i created the database

what i see:
then the app window disappear
i was thinking the app was crashed
i start again the app  app
still i see nothing

what i expected
a) show a dialogbox with info that the app now lives as icon in menu bar
b) if i start again the app: show the dialog from (a) again (with option [x] show hint on startup)

PS:
if you have a app running which has many menu items and you still have many menubar icons then the left icons are not visible

**Comment by fceller** [comment]
fixed in 2.6
