### ISSUE TITLE
Foxx needs better error view

### ISSUE THREAD

**Issue by rishavs** [arangodb/arangodb#6992]
Statement:
The current error view of Foxx provides a poor developer experience.
If i make any mistake in my service files, the service webUI just shows "No operations defined in spec! " which is not useful at all. As a new user, I have no idea how to debug my app as I cannot see any error stack.

If I go to the logs, the error stack is completely broken into separate lines.
![image](https://user-images.githubusercontent.com/1210239/47270362-6d405000-d588-11e8-9706-0c2334c73a18.png)
This is absolutely not usable. the entire error trace should be in a single log row instead of being broken into multiple rows.

Right now, developing with Foxx is very difficult. my dev flow is;

- I make a change in my js file. save it in the editor.

- I goto services > info. See that my service is broken.

- I goto logs. read through the rows. Sometimes goto the next page to see the actual problem.

Something trivial which used to take me few seconds in nodejs is now taking close to half a minute and my entire flow is broken.

__Expected result__:

- Ideally, I would want the error to be shown in the services > info page. If my service works, I get to see the API endpoints. if it is broken, I see the error stack instead. If the error is bubbled before the apis are handed over to swagger, the js error should be shown instead of the Swagger one.

- Would also prefer for this page to be live reloaded every time I save my changes.

- The foxx-cli can have a "hook" method where it shows the current state of the foxx environment, including any live error stacks and such.

**Comment by pluma** [comment]
There was a regression at some point which resulted in a lot of the DX improvements in Foxx error handling not actually being available. This behavior has been restored in v3.4.0-rc.3.

If you want to give it a try, make sure to run the service in development mode to find out additional information.

**Comment by pluma** [comment]
Related: https://github.com/arangodb/arangodb/pull/7013

**Comment by OmarAyo** [comment]
Hi @rishavs 

Just sending a quick followup, did you have the chance to test the behavior on 3.4.0-rc3 ?
Please provide a feedback

Best

**Comment by maxkernbach** [comment]
@rishavs

Since we have not heard back from you in a while, I will close this issue for now.

The Foxx API handling of broken services has been improved since version 3.4.0-rc3.
In case the implemented behaviour does not come up to your expectations, please feel free to comment and we will reopen this issue.

**Comment by rishavs** [comment]
Yeah, sorry about not replying earlier. I did not have a chance to try it in 3.4 as i have switched to other tools for my project. I am keeping an eye on Arango + Foxx releases and will come back once I see exciting stuff happen.
