### ISSUE TITLE
Docs server is down

### ISSUE THREAD

**Issue by dharmanextsteps** [arangodb/arangodb#7010]
https://docs.arangodb.com/ not working service is down

**Comment by maxkernbach** [comment]
Hi @dharmanextsteps,

thanks for reporting. We are currently working on fixing it.

**Comment by maxkernbach** [comment]
In the meantime you can use the [offline documentation](https://www.arangodb.com/download-arangodb-docs/), available as a HTML-tarball for the complete documentation or as PDF, EPUB or MOBI for each handbook.

**Comment by Simran-B** [comment]
The documentation should be online again (try an incognito window / private tab if something looks broken as there could be caching issues).

We work on some remaining hiccups with the website, but everything should be usable.

**Comment by Simran-B** [comment]
Warnings about mixed content should be gone.
