### ISSUE TITLE
Feature Request: auto-installing/auto-loading modules

### ISSUE THREAD

**Issue by dajester2013** [arangodb/arangodb#702]
Running Arango 1.4.3 on Windows 7, x64 in console mode.

Original forum post:

I have a module that creates some custom AQL functions, was wondering if there was a way to run the install function when a new database is created?  Or is there a better way to do this - I want to add some global AQL functions that are automatically available to any database (ie, at the same level as the built-in AQL functions).

I saw the folder called "common/bootstrap", but I don't know when the modules in there are loaded.

common/modules/my/Module.js:
-----------------------------------------------
```javascript
exports.install = function() {
    require("internal").flushModuleCache();
   
    var aqlUDF = require("org/arangodb/aql/functions");
   
    aqlUDF.register("my::aql::function",require("my/aql/function"),true);
    aqlUDF.register("my::aql::function2",require("my/aql/function2"),true);
}
```

Example install (currently):
-----------------------------------------------
```javascript
db._useDatabase("mydb");
require("my/Module").install();
```

**Comment by pluma** [comment]
I'm closing this as "won't fix" as it's no longer relevant for Foxx (just use setup scripts) and there is an HTTP API to register AQL functions.
