### ISSUE TITLE
3.3.19 Known UI bug - Create Foxx Service -> Mountpoint error

### ISSUE THREAD

**Issue by maxkernbach** [arangodb/arangodb#7047]
Hi @everyone,

we have just published ArangoDB 3.3.19 and noticed the following Foxx bug in the Web Interface.

When trying to create a Foxx service in the Web UI with a string containing only letters for `Mountpoint:`  the error message `May not contain /APP` is shown and it is not possible to click the "Install" button.

![image](https://user-images.githubusercontent.com/9152640/47431520-422e4a00-d79c-11e8-9cbc-dc76e2b3b5a7.png)

It is possible to work around this bug by adding a `/` at the beginning of your Mountpoint. 

![image](https://user-images.githubusercontent.com/9152640/47431458-24f97b80-d79c-11e8-937f-7d5a34012d3c.png)

This issue will be addressed in the next release 3.3.20.

**Comment by OmarAyo** [comment]
FYI this bug is affecting also 3.4.0_rc3

**Comment by maxkernbach** [comment]
Both versions 3.3.20 and 3.4 GA, which include a fix for this issue, have been released.
