### ISSUE TITLE
Could not update local apps repository on Windows 8

### ISSUE THREAD

**Issue by sharpyfox** [arangodb/arangodb#711]
Hello, I have an issue with updating local apps repository on W8 x64. I'm trying to run command `foxx-manager.bat update` but the answer is always

```
application download failed: Github download from 'https://github.com/arangodb/foxx-apps/archive/master.zip' failed with error code 500
```

same url works OK when requested from browser. Am I doing something wrong?

**Comment by nlac** [comment]
Hi guys,
i've just tried the same command `foxx-manager update` on Win8 with ArangoDB v2.42, and got the same "download failed" error as above. I've read this and the related tickets, but still couldn't make it.

I made sure that 
* the default temp directory of arangodb (c:\Users\USERNAME\AppData\Local\Temp\) does exist + has the /downloads, /zip, /uploads subdirs
* inserted a row `temp-path = @ROOTDIR@/tmp_foxx` into foxx-manager.conf

When executed `foxx-manager update` from an elevated command prompt, i could see the /tmp_foxx dir has been created with /downloads and /zip subdirs, but get the error `application download failed: Github download from 'https://github.com/arangodb/foxx-apps/archive/master.zip' failed with error code 500`.

Could you pls advice what to do step-by-step to be able to start working with foxx-manager?
