### ISSUE TITLE
Optimizer kills logical `OR` optimization in filter 

### ISSUE THREAD

**Issue by konsultaner** [arangodb/arangodb#7138]
In js and most other languages logic expressions like `a || b` will not check `b == true` if `a == true`. AQL optimizer kills this optimization

## My Environment

* __ArangoDB Version__:        ArangoDB 3.2.9 
* __Storage Engine__:             MMFiles
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Infrastructure__:               local
* __Operating System__:        Windows 10

## Query

This is a working query that has a null check. 

```
FOR a in [1,2,3,{b:[1,2,3,4]}]
FILTER a.b == NULL || TRUE == FIRST(
    FOR b IN NOT_NULL(a.b,[])
    LIMIT 1
    RETURN TRUE
)
RETURN a
```

It should be possible to write the query like this because the filter checks if the current `a.b == NULL`, but it throws an error: `collection or array expected as operand to FOR loop; you provided a value of type 'null'`

```
FOR a in [1,2,3,{b:[1,2,3,4]}]
FILTER a.b == NULL || TRUE == FIRST(
    FOR b IN a.b
    LIMIT 1
    RETURN TRUE
)
RETURN a
```

Looking into the optimizer shows that the subquery is replaced:

```
Execution plan:
 Id   NodeType            Est.   Comment
  1   SingletonNode          1   * ROOT
  2   CalculationNode        1     - LET #4 = [ 1, 2, 3, { "b" : [ 1, 2, 3, 4 ] } ]   /* json expression */   /* const assignment */
  3   EnumerateListNode      4     - FOR a IN #4   /* list iteration */
 10   SubqueryNode           4       - LET #2 = ...   /* subquery */
  4   SingletonNode          1         * ROOT
  5   CalculationNode        1           - LET #6 = NOT_NULL(a.`b`, [ ])   /* simple expression */
  8   CalculationNode        1           - LET #8 = true   /* json expression */   /* const assignment */
  6   EnumerateListNode    100           - FOR b IN #6   /* list iteration */
  7   LimitNode              1             - LIMIT 0, 1
  9   ReturnNode             1             - RETURN #8
 11   CalculationNode        4       - LET #10 = ((a.`b` == null) || (true == FIRST(#2)))   /* simple expression */
 12   FilterNode             4       - FILTER #10
 13   ReturnNode             4       - RETURN a
```

In my concrete case the subquery should be evaluated only if needed because it is a heavy calculation. I'm not sure if the default optimization is better for most cases?

**Comment by jsteemann** [comment]
Operands of logical AND and logical OR are evaluated in a short-circuit fashion already, except if the right hand operand is a subquery. Subqueries are always pulled out of expressions and are evaluated first.
This is probably unexpected, but documented:
https://docs.arangodb.com/3.4/AQL/Operators.html#logical-operators

**Comment by konsultaner** [comment]
> Subqueries are always pulled out of expressions and are evaluated first.
> This is probably unexpected, but documented:

Ok, but im my real query I used a very expensive subquery which is mostly not used. It would be awesome if there was a workaround where I could somehow make the optimizer not execute the subquery. any tips or ideas?

**Comment by konsultaner** [comment]
@jsteemann thanks, enough for me. nice idea!
