### ISSUE TITLE
Zero downtime active failover

### ISSUE THREAD

**Issue by soualid** [arangodb/arangodb#7172]
## My Environment

* __ArangoDB Version__:        3.3.17
* __Deployment Mode__:       Active Failover
* __Deployment Strategy__:   Manual Start in Docker (through Mesos/Marathon)
* __Infrastructure__:               Own
* __Used Package__:              Docker - official Docker library

## Question / Feature request

Hello, in an active failover deployment, we noticed that it takes a few seconds for agencies to detect that the current leader is down and therefore start a new master election. During this time, the actual master is not available and the future one is still refusing requests with the "not a leader" error message as it has not been elected by the agencies quorum yet.

Is it possible to let the client applications decide who is the new master when detecting a failure and/or let them define it within the agencies? Or maybe some sort of synchronous HTTP endpoint that could trigger the election and return the new master afterwards? 

Our goal is to achieve "zero downtime" during active failover which could be easily feasible if such endpoint exists.

**Comment by graetzer** [comment]
so what you can do right now is write the UUID of the new leader into the agency key `/arango/Plan/AsyncReplication/Leader` (see https://docs.arangodb.com/3.4/HTTP/Agency/ on how to write things into the agency). 
We may add an API for this in the near future.

**Comment by soualid** [comment]
Great, I'll try this, thanks!
