### ISSUE TITLE
Documentation needs version numbers for bundled NPM modules in Foxx

### ISSUE THREAD

**Issue by chrolivier** [arangodb/arangodb#7194]
It would be great if the documentation listed the version numbers of the NPM modules that are bundled with Foxx.
This would make it a lot simpler to find the correct versions of these packages when developing and testing service code outside of Foxx.
At the moment I'm having to dig through the js folder in the source code to try and identify the correct versions of sinon, mocha, chai, etc. to use.

**Comment by pluma** [comment]
I'm closing this as we're deprecating bundled NPM modules going forward and the documentation for them will be removed.
