### ISSUE TITLE
How to check the results of a running query

### ISSUE THREAD

**Issue by stelios6** [arangodb/arangodb#7215]
## My Environment

* __ArangoDB Version__:        3.4
* __Storage Engine__:             RocksDB -
* __Deployment Mode__:        Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:              
* __Infrastructure__:               windows
* __Operating System__:         Windows2012 
* __Used Package__:              

## Component, Query & Data

__Affected feature__:

__AQL query (if applicable)__:
LET table=(for ch IN Items FILTER (ch.Content!=null and ch.Content!='') return ch._key)
            RETURN LENGTH(table)

__AQL explain (if applicable)__:

__Dataset__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. 
2. 
3. 

__Problem__:
When executing the above query and you click somewhere else, the script goes under the running scripts. How do you see the results of the query before it is removed from there? This should be displayed somewhere after the scripted has completed.

__Expected result__:

**Comment by maxkernbach** [comment]
Hi @stelios6,

when executing a Query and switching into another Menu (for example `Collections`) the message box `Query finished: Return to queries view to see the result.` shows up. You can go back into the Query view and the result is correctly displayed.

When a query is started and you are currently in the "Running Queries" or "Slow Query History" tab once the query finishes, neither a message nor a result is shown. This is a bug, it should also work in this case.

**Comment by stelios6** [comment]
Thx a lot for your quick reply.

**Comment by maxkernbach** [comment]
Let's keep this issue open until it is fixed.

**Comment by stelios6** [comment]
ok great

**Comment by hkernbach** [comment]
PR's opened for 3.3, 3.4 and devel branches. Thanks for spotting.

**Comment by stelios6** [comment]
Thanks
