### ISSUE TITLE
Arangodump or arangoexport very slow

### ISSUE THREAD

**Issue by stelios6** [arangodb/arangodb#7247]
## My Environment

* __ArangoDB Version__:        3.4. RC3
* __Storage Engine__:             RocksDB -
* __Deployment Mode__:       Single Server 
* __Deployment Strategy__:   Manual Start 
* __Infrastructure__:               VM
* __Operating System__:        Windows 2012

## Steps to reproduce

```
arangoexport --server.endpoint tcp://127.0.0.1:8529 --server.username root --server.password xxxx! --server.database mydb --server.max-packet-size 512000000 --collection collection1 --output-directory "C:\backup" --overwrite true
```
```
arangoexport --server.endpoint tcp://127.0.0.1:8529 --server.username root --server.password xxxx! --server.database mydb --server.max-packet-size 512000000 --collection collection2 --output-directory "C:\backup" --overwrite true
```

__Problem__:
When using `arangodump` or `arangoexport` while arango is doing some other operations (not very heavy e.g. using 5% of cpu) the export or dump takes ages to complete and the server (UI) becomes unresponsive. The size of the data is around 10GB. What if we have big data in the future in Arango i.e. 500GB. How much time will take to perform a backup?

**Comment by Simran-B** [comment]
What other operations do you execute at the same time? What are the hardware specs of the VM?

**Comment by stelios6** [comment]
We execute some insert operations on one of the collections.
We have 4 sockets with 8 virtual processors with 2.00 GHz per virtual processor. And 33 GB memory. 250GB free hard disk space.

**Comment by stelios6** [comment]
After executing again the arangoexport i get the following error on one of the collections

[6936] Fatal {config} collection collection2 not found. How i can check what is the problem and how to correct the collection or if this is a bug of the export tool?

**Comment by jsteemann** [comment]
That error message will be returned by arangoexport when specifying the name of a non-existing collection. 
It looks like `collection2` does not exist on the server you pointed arangoexport to, at least not in the database that you were using. Note: you can use a different database by specifying `--server.database` (if you didn't do it already). When not specifying a database name, arangoexport will default to the `_system` database.

**Comment by stelios6** [comment]
Actually the collection exist on that db and the error message is displayed after some time while exporting. This is confirmed because the physical exported file of the collection2 has a size of many megabytes after the above message so it seems that something within the collection triggered the error. The pending questions are: 
     1. How can I find out what is the actual error in order to correct the data within the collection and complete the export.
      2. How we can speed up the export mechanism which is dead slow.

**Comment by maxkernbach** [comment]
Hi @stelios6, 

we would like to investigate this issue, I have a few further questions. 

1. Was it a one time error or is it reproducible with `collection2`?
2. Could you please share the `arangod.log` file?
3. Did you already try to execute `arangodump` on the failing collection? 
4. Would it be possible to share the `dump` (in case arangodump is successful) or database directory?

You could send us a message to hackers@arangodb.com (this ML is not public) and attach the dump in that email, or if it is too big we will reply to your email and provide a password protected folder where you can upload the archive. Please reference the number of this issue in your email.

Thanks

**Comment by stelios6** [comment]
reply sent to email provided above

**Comment by stelios6** [comment]
Any news on the above issue?

**Comment by OmarAyo** [comment]
Hi @stelios6 ,

We are trying to reproduce this issue internally, but we were not able so far. On every try, `arangoexport` ends without any reported error, and all collections are exported. 

We will keep you updated.

Best,

**Comment by stelios6** [comment]
Ok thx. How much time it takes to export?

Stelios

Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by OmarAyo** [comment]
Hi @stelios6 

Well it depends on which collection I export, so for the biggest one it took around 15-20mis to export.

Best,

**Comment by stelios6** [comment]
are you running it on Linux or windows system? Can we trace from my setup why it takes longer and generates these errors?


Regards


Stelios


________________________________

**Comment by OmarAyo** [comment]
Hi @stelios6 

We were not able to reproduce this issue internally. We tried different times and we were always able to export all the collections that are in the dump provided by you.  

All our tests were done using Windows OS (we tried Windows 10 and Windows 2012). 

Since you have the dump in place, would it possible for you to try to start a new fresh single-instance using our latest 3.4_RC4 ArangoDB version and then follow the following steps:
- restore the dump in the new ArangoDB single instance using `arangorestore` tool 
- re-try to export the collections again using `arangoexport` tool 

While exporting you may see a similar error:
```
Connected to ArangoDB 'http+tcp://127.0.0.1:8529', version 3.4.0-rc.3, database:
 'WiseBOS-Screening', username: 'root'
# Exporting collection '<collection2>'...
2018-11-21T13:27:56Z [3136] WARNING {httpclient} ignoring HTTP response with 'Co
ntent-Length' bigger than max packet size (684396648 > 512000000)
2018-11-21T13:27:56Z [3136] ERROR {startup} startup aborted: caught exception du
ring start of feature 'Export': got invalid response from server: ignoring HTTP
response with 'Content-Length' bigger than max packet size (684396648 > 51200000
0) (exception location: c:\users\jenkins\oskar\work\arangodb\arangosh\export\exp
ortfeature.cpp:561). Please report this error to arangodb.com. shutting down
2018-11-21T13:27:56Z [3136] ERROR {startup} arangoexport terminated because of a
n unhandled exception: startup aborted: caught exception during start of feature
 'Export': got invalid response from server: ignoring HTTP response with 'Conten
t-Length' bigger than max packet size (684396648 > 512000000) (exception locatio
n: c:\users\jenkins\oskar\work\arangodb\arangosh\export\exportfeature.cpp:561).
Please report this error to arangodb.com (exception location: c:\users\jenkins\o
skar\work\arangodb\lib\applicationfeatures\applicationserver.cpp:649). Please re
port this error to arangodb.com
```

This error can be easly solved by changing the `arangoexport` option ` --server.max-packet-size` to a value >= `684396648` 

In this case your `arangoexport` command will be:
```
arangoexport --server.endpoint tcp://127.0.0.1:8529 --server.username root --server.password xxxx! --server.database mydb --server.max-packet-size 684396648 --collection collection2 --output-directory "C:\backup" --overwrite true
```

Hope this helps,

Regards

**Comment by stelios6** [comment]
Ok. I will try and let you know

Stelios



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by stelios6** [comment]
Hi, I have tried the above and unfortunately I have the same problem. While exporting I receive the Fatal error again. Is there a way to pin point which document is causing this problem? Since the arangodump is working, it means that the tool can read the data but arangoexport some how generates this problem. Is there a way to debug while export and fix the problem even by deleting the specific document?

**Comment by stelios6** [comment]
Any news on the above?

**Comment by OmarAyo** [comment]
Hi @stelios6,

We were not able to reproduce this issue after several tries. I will label this issue as "Cannot Reproduce" and leave it open for further investigation

Best,

**Comment by stelios6** [comment]
I have tried and I get the msg Cursor not found after some time. Also I have tried to export it using another pc and there it works. It means most probably there is something wrong with the current setup. I will investigate it further and come back. I will close this issue for the time being. Thx for your help.
