### ISSUE TITLE
ArangoDB Starter --ownAddress ignores port argument

### ISSUE THREAD

**Issue by bgaechter** [arangodb/arangodb#7255]
## My Environment

* __ArangoDB Version__:        3.3.19
* __Storage Engine__:              MMFiles
* __Deployment Mode__:        Cluster
* __Deployment Strategy__:    ArangoDB Starter
* __Configuration__:               3 virtual servers
* __Infrastructure__:               own
* __Operating System__:        CentOS 7
* __Used Package__:              SUSE or RedHat .rpm 

## Steps to reproduce

1.  arangodb --ownAddress localhost:4000

__Problem__:
arangodb binds to localhost:8528 as the following snippet from the output shows:
2018-11-07T10:43:30-05:00 |INFO| Starting arangodb version 0.13.7, build bdac926 component=arangodb
2018-11-07T10:43:30-05:00 |INFO| Relaunching service with id '176d3806' on localhost:4000:8528... component=arangodb
...

__Expected result__:
arangodb should bind to localhost:4000 as explained in https://docs.arangodb.com/3.3/Manual/Deployment/ArangoDBStarter.html#automatic-native-clusters

**Comment by vinaypyati** [comment]
Hi @bgaechter,

Thanks for opening an issue. Unfortunately, the starter option `--ownAddress` that you are using to start the cluster is currently obsolete. Please use the latest option `--starter.address` and `--starter.port` to specify the address and port respectively. 
```
arangodb --starter.address localhost --starter.port 4000
```
Please have a look to latest options by using `arangodb --help`. For more info you can refer to the latest [documentation](https://docs.arangodb.com/3.4/Manual/Deployment/Cluster/UsingTheStarter.html).

Thanks!

**Comment by OmarAyo** [comment]
Hi @bgaechter 

Just sending a followup, to check if you had the chance to read above Vinay's message? Did you try to use `--starter.address` instead ?

Please provide a feedback

Thanks

**Comment by bgaechter** [comment]
Hi @OmarAyo 
Yes, I used `--starter.address` together with `--starter.port` and it works but it doesn't solve my problem. I need the coordinator to be available on that specific port while setting the port for the arangoDB starter only changes the port for the initial setup of the cluster. It would be nice to be able to do these kind of things with the helper.

However, I am running `arangod` with some parameters for now, which works for me.

**Comment by dothebart** [comment]
Closing this as outdated with the availability of [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/).
