### ISSUE TITLE
TypeScript Can't Resolve '@arangodb'

### ISSUE THREAD

**Issue by rgstephens** [arangodb/arangodb#7281]
This is my first attempt at using Arango and I'm using it with Node.js/Lambda. I've installed `@types/arangodb` and `arangojs` but I'm still getting a trypscript error:

```
Module not found: Error: Can't resolve '@arangodb'
```

My import looks like:

```
import { db as arangodb } from '@arangodb';

const db = arangodb._useDatabase(server);
...
```

**Comment by pluma** [comment]
Sorry for the late reply, looks like this one fell through the cracks.

The `arangojs` module on npm is not the same thing as the `@arangodb` namespace.

If you are writing JavaScript code for Node or the browser and want to talk to the ArangoDB HTTP API, `arangojs` is what you want. It ships its own typings so there's no need to install anything else.

If you are writing JavaScript code to be executed inside ArangoDB, e.g. using the built-in JS framework Foxx, you can install the `@types/arangodb` typings for the `@arangodb` namespace. ArangoDB exposes its JS API via the `@arangodb` namespace. This namespace is reserved on npm to avoid name clashes with regular JS packages.

I hope that answers your question. You seem to be using Node.js, so you would only need to install `arangojs` and nothing else.
