### ISSUE TITLE
AQL: GeoJSON returning as a string

### ISSUE THREAD

**Issue by Philip-Wu** [arangodb/arangodb#7289]
## My Environment

* __ArangoDB Version__:        3.4.0 RC4
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   ArangoDB Starter
* __Configuration__:               
* __Infrastructure__:               own
* __Operating System__:        Windows 7
* __Used Package__:              

## Component, Query & Data

__Affected feature__: Geo queries and/or documentation

__AQL query (if applicable)__:
```
Let geoPoint1 = {"coordinates":[-122.084,37.421997], "type":"Point" }
FOR geo IN Geo 
    Let geoPoint2 = geo.location
    Let geoDistance = GEO_DISTANCE(geoPoint1, geoPoint2)
    FILTER geoDistance != null && geoDistance  <= 30000 
    RETURN { "distance" : geoDistance, "location": geo.location}
```

__AQL explain (if applicable)__:
Query String:
 Let geoPoint1 = {"coordinates":[-122.084,37.421997], "type":"Point" }
 FOR geo IN Geo 
     Let geoPoint2 = geo.location
     Let geoDistance = GEO_DISTANCE(geoPoint1, geoPoint2)
     FILTER geoDistance != null && geoDistance  <= 30000 
     RETURN { "distance" : geoDistance, "location": geo.location}
 

Execution plan:
 Id   NodeType          Est.   Comment
  1   SingletonNode        1   * ROOT
 10   IndexNode           12     - FOR geo IN Geo   /* geo index scan, projections: `location` */
  5   CalculationNode     12       - LET geoDistance = GEO_DISTANCE({ "coordinates" : [ -122.084, 37.421997 ], "type" : "Point" }, geo.`location`)   /* simple expression */   /* collections used: geo : Geo */
  6   CalculationNode     12       - LET #4 = (geoDistance != null)   /* simple expression */
  7   FilterNode          12       - FILTER #4
  8   CalculationNode     12       - LET #6 = { "distance" : geoDistance, "location" : geo.`location` }   /* simple expression */   /* collections used: geo : Geo */
  9   ReturnNode          12       - RETURN #6

Indexes used:
 By   Type   Collection   Unique   Sparse   Selectivity   Fields           Ranges
 10   geo    Geo          false    true             n/a   [ `location` ]   (GEO_DISTANCE({ "coordinates" : [ -122.084, 37.421997 ], "type" : "Point" }, geo.`location`) <= 30000)

Functions used:
 Name           Deterministic   Cacheable   Uses V8
 GEO_DISTANCE   true            true        false  

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   remove-unnecessary-calculations
  4   move-calculations-up-2
  5   move-filters-up-2
  6   geo-index-optimizer
  7   reduce-extraction-to-projection

__Dataset__:
No results are returned because geoDistance is null. The issue is because geoPoint2 is being returned purely as a string rather than a GeoJSON object.

__Replication Factor & Number of Shards (Cluster only)__:
None

## Steps to reproduce

1. 
2. 
3. 

__Problem__:

geoPoint2 is a string not a GeoJSON. To fix this query I had to wrap the string with JSON_PARSE as follows:

`Let geoPoint2 = JSON_PARSE(geo.location)`

Then it works as expected.

__Expected result__:

According to the documentation here: https://www.arangodb.com/arangodb-training-center/geojson-tutorial/

We should not have to convert the location string to GeoJSON.
Checking my Geo index I have:

```
127.0.0.1:8529@diggieDog> db.Geo.getIndexes();
[
  {
    "fields" : [
      "_key"
    ],
    "id" : "Geo/0",
    "selectivityEstimate" : 1,
    "sparse" : false,
    "type" : "primary",
    "unique" : true
  },
  {
    "bestIndexedLevel" : 17,
    "fields" : [
      "location"
    ],
    "geoJson" : true,
    "id" : "Geo/462717",
    "maxNumCoverCells" : 8,
    "sparse" : true,
    "type" : "geo",
    "unique" : false,
    "worstIndexedLevel" : 4
  }
]
```

**Comment by graetzer** [comment]
Where does it say you can use a string ? Maybe the tutorial is unclear, but only JSON is supported not strings

**Comment by Philip-Wu** [comment]
perhaps it was my mistake. I'm using the java driver to create my geoJSON which I saved as a string.
Any idea on how to save a geo JSON using the java driver?
