### ISSUE TITLE
UPSERT queries do not use collection indexes

### ISSUE THREAD

**Issue by bgoetz** [arangodb/arangodb#7292]
## My Environment

* __ArangoDB Version__:        3.3.9
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Operating System__:        Windows 10

## Steps to Reproduce

UPSERT AQL queries (Foxx and web interface) do not make use of available indexes on the collection.

I have a collection _vertices_ with documents that share at least one attribute 'vertice':
```
[
 { _id : "1", vertice : "A", ...},
 { _id : "2", vertice : "B", ...},
 ...
]
```

I have a unique hash index on this collection on the 'vertice' attribute. For a given array of string 'vertice' values I need to create any missing documents within the _vertices_ collection:

```
FOR v IN [ /* array of unique string 'vertice' values */ ]
    UPSERT { vertice : v }
    INSERT { vertice : v }
    UPDATE {}
    IN vertices
    RETURN NEW._id
```

When I started seeing executing times of >1 ms per string value I investigated. I saw in the explainer that there were no indexes used:

```
Query string:
 FOR v in 
 [ /* array of unique string 'vertice' values */ ]

Execution plan:
 Id   NodeType                  Est.   Comment
  1   SingletonNode                1   * ROOT
  2   CalculationNode              1     - LET #7 = [ /* array of unique string 'vertice' values */ ]   /* json expression */   /* const assignment */
 13   CalculationNode              1     - LET #13 = { }   /* json expression */   /* const assignment */
  3   EnumerateListNode          436     - FOR v IN #7   /* list iteration */
 10   SubqueryNode               436       - LET #4 = ...   /* subquery */
  4   SingletonNode                1         * ROOT
  5   EnumerateCollectionNode   2603           - FOR #2 IN vertices   /* full collection scan */
  6   CalculationNode           2603             - LET #9 = (#2.`vertice` == v)   /* simple expression */
  7   FilterNode                2603             - FILTER #9
  8   LimitNode                    1             - LIMIT 0, 1
  9   ReturnNode                   1             - RETURN #2
 11   CalculationNode            436       - LET $OLD = #4[0]   /* simple expression */
 12   CalculationNode            436       - LET #11 = { "vertice" : v }   /* simple expression */
 14   UpsertNode                 436       - UPSERT $OLD INSERT #11 UPDATE #13 IN vertices
 15   CalculationNode            436       - LET #15 = $NEW.`_id`   /* attribute expression */
 16   ReturnNode                 436       - RETURN #15

Indexes used:
 none

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-calculations-up-2
  3   remove-data-modification-out-variables
  4   move-calculations-down

Write query options:
 Option                   Value
 ignoreErrors             false
 waitForSync              false
 nullMeansRemove          false
 mergeObjects             true
 ignoreDocumentNotFound   false
 readCompleteInput        false
 useIsRestore             false
 consultAqlWriteFilter    false
```

The above query took 719.635 ms to execute given an array with 436 elements. For comparison, if I first check for existing documents and only create those that are missing the execution falls closer to what I would expect: around 15 ms for all related queries (given the same starting array and starting collection state). The first query is a simple filter which definitely hits the index:

```
FOR v IN vertices
    FILTER v.vertice IN [ /* array of unique string 'vertice' values */ ]
    RETURN v._id
```

And the explain:

```
Query string:
 FOR v in vertices
     filter v.vertice in 
 [ /* array of unique string 'vertice' values */ ]

Execution plan:
 Id   NodeType          Est.   Comment
  1   SingletonNode        1   * ROOT
  7   IndexNode          435     - FOR v IN vertices   /* hash index scan, projections: `_id` */
  5   CalculationNode    435       - LET #3 = v.`_id`   /* attribute expression */   /* collections used: v : vertices */
  6   ReturnNode         435       - RETURN #3

Indexes used:
 By   Type   Collection   Unique   Sparse   Selectivity   Fields           Ranges
  7   hash   vertices     true     true     100.00 %      [ `vertice` ]    (v.`vertice` in [ /* array of unique string 'vertice' values */ ])

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   move-calculations-up-2
  4   move-filters-up-2
  5   use-indexes
  6   remove-filter-covered-by-index
  7   remove-unnecessary-calculations-2
  8   reduce-extraction-to-projection
```

**Comment by jsteemann** [comment]
I think the reason is that the index on `vertice` is sparse. Can you try running the query with a non-sparse index on `vertice`?

**Comment by bgoetz** [comment]
That did it. It runs in 20 ms now. Any difference beyond the margin of error is more than acceptable.

I have a few unrelated questions regarding Foxx modules and multiprocessing. According to the documentation the modules are single threaded, and that subsequent requests to the same mount point are not guaranteed to be ran within the same V8 context (which is fine). Additionally Foxx queues can be created to asynchronously execute jobs.

Are the queue workers spawned as new processes or as new threads? Also, is there a way to pause and resume the queue poll manager through the API? I'd prefer it if there wasn't a delay when jobs are added to a queue.

I have a computationally expensive function that modifies documents in place. If I have to apply it to many documents (100,000+) how should I schedule the jobs (where the parameter for a job is the _id of the document) to reduce job overhead? One job per document, one job per worker (with the data equally partitioned), or chunks of ids (e.g., arrays of 1,000 ids per job)?

Thanks for your help.

**Comment by jsteemann** [comment]
@bgoetz: yes, subsequent requests to the same mount point are not guaranteed to be executed within the same V8 context. So storing this in context-local variables will not work reliably, except if it's used to optionally cache some already computed data.

Foxx queue workers are neither spawned as extra processes or threads.
Whenever a Foxx queue worker is about to execute its work, it will look for an available V8 context and use it. If there is no context, it will create a V8 context on the fly. The task is then executed in the V8 context in one of arangod's existing Scheduler threads. For the threads there is the same rule: if there is no idle thread, a new one will be started dynamically. If there is an idle thread, it will be used to execute the job.

Regarding how to best execute and control Foxx queues job, I am not able to give you a qualified answer. Let me try to find someone to answer this...

**Comment by Simran-B** [comment]
Let's move the unrelated Foxx discussion to a new issue: https://github.com/arangodb/arangodb/issues/7305
