### ISSUE TITLE
Foxx's garbage collection

### ISSUE THREAD

**Issue by poland-can-into-space** [arangodb/arangodb#7313]
## What I understand is;

- Foxx is based on V8 Engine.
- Foxx is multi-threaded, and it doesn't share state with other threads
- Foxx's thread will quit (is this the right term?) as soon as it sends the response to client.

Aside from V8 Engine's garbage collection, does it mean that any memory used by foxx is garbage collected as soon as the response is made?
Please let me know if I'm getting it wrong.

FYI, I have asked the same question on Stackoverflow.

**Comment by dothebart** [comment]
Ok, I will answer via https://stackoverflow.com/questions/53282419/when-does-arangodbs-foxx-collects-garbage . Please don't multi post.
