### ISSUE TITLE
Swagger doesn't detect that the host is reachable via https

### ISSUE THREAD

**Issue by dothebart** [arangodb/arangodb#7320]
Start an arangod with ssl like this: 
```
/bin/arangod /tmp/abc --server.endpoint ssl://127.0.0.1:8529 --ssl.keyfile `pwd`/UnitTests/server.pem
```
go into the swagger interface, try out random route.
Neither the sugested curl requests nor the browser requests will be attempted to be sent via https but rather http - and fail.

**Comment by Simran-B** [comment]
#9043 and #9044 fix the browser requests, but the Curl requests still display with `http://`.

**Comment by dothebart** [comment]
hm, the option to `["http", "https"] ` doesn't fix it.

**Comment by dothebart** [comment]
Ok, its only the static examples that aren't fixed, but this is by design. Since the PRs have been merged, I'm closing this as fixed.
