### ISSUE TITLE
Create user that has permissions for statistics only.

### ISSUE THREAD

**Issue by SleepyBrett** [arangodb/arangodb#7358]
## My Environment

* __ArangoDB Version__:        3.3.9

The rest does not apply

## Component, Query & Data

Is there a way to permission a user so that it only has access to read from...
* /_admin/statistics
* /_admin/statistics-description

**Comment by maxkernbach** [comment]
Hi @SleepyBrett,

the implemented User Management of ArangoDB is based on database and collection access levels. Therefore it is not possible to create a "standard" user with the requested permission. 

However it would be possible to create a custom permission model that is implemented by a foxx service.
You might want to have a look at this [tutorial](https://www.arangodb.com/foxx-fine-grained-permissions/). It shows how to create a simple HTTP API for managing patient records and then extend it with authentication and a permission model to limit the employees’ access.

**Comment by OmarAyo** [comment]
Hi @SleepyBrett 

Did you have the chance to have a look at Max's above-linked tutorial? Was it useful for you?

**Comment by SleepyBrett** [comment]
I have not yet looked into it. I've had other priorities for the last few days.

**Comment by OmarAyo** [comment]
Hi @SleepyBrett

Just sending a follow-up, did you have the chance to try the linked tutorial?

**Comment by maxkernbach** [comment]
Hi @SleepyBrett, 

Since we have not received any feedback in a while, I am closing this issue for now.

In case you have any further questions, please feel free to comment and we will reopen this issue.
