### ISSUE TITLE
ArangoSearch: Synonym Support

### ISSUE THREAD

**Issue by cboothe** [arangodb/arangodb#7364]
## My Environment

My Environment
ArangoDB Version: 3.4
Storage Engine: RocksDB
Deployment Mode: Single Server
Deployment Strategy: Manual Start
Infrastructure: Docker

Does AgrangoSearch currently support Synonyms?
I was wondering if this is something that has to be faked for now.

Either using a combination of a Graph for synoymns combined with a view:
https://stackoverflow.com/questions/53288120/combining-new-arangosearch-views-and-graph-traversals

Or based on this "exact vs stemmed match" and store the synonyms on the document level.
https://github.com/arangodb/arangodb/issues/5454

**Comment by KVS85** [comment]
Hello @cboothe,

ArangoSearch doesn't support synonyms at the moment. You can try to adopt approach described in  https://github.com/arangodb/arangodb/issues/5454#issuecomment-392009257 if your "synonyms" are stemmed vs. exact value for your data.

Synonyms and other custom-related analyzers are subject for release after 3.4.0.

**Comment by maxkernbach** [comment]
Hi @cboothe, 

has the previous comment been helpful to you or do you have any further questions?

**Comment by zurferr** [comment]
@maxkernbach @KVS85 
How would you implement synonyms with ArangoSearch in 2022? 
Do I need to do it at the application level or is there a better way?
