### ISSUE TITLE
Script is throwing "ArangoDBClient\ServerException: 18 lock timeout" while inserting 100000000 records.

### ISSUE THREAD

**Issue by yashpandya212** [arangodb/arangodb#7366]
## My Environment

* __ArangoDB Version__:        3.3.19
* __Storage Engine__:             MMFiles
* __Deployment Mode__:       Single Server
* __Infrastructure__:               AWS
* __Operating System__:       Ubuntu 16.04.4 LTS
* __Used Package__:            Debian or Ubuntu .deb

## Component, Query & Data

__Affected feature__:
with php driver

__Dataset__:
just a simple document with 4 attributes: _key, tag_id, product_details_id, status. looping it from 1 to 100000000.

        $document = new Document();
    $document->set('_key',"abcdefghijklmnopqrstuvwxy2z".$i);
    $document->set('tag_id', "abcdefghi1j".$i);
    $document->set('product_details_id', "product1");
    $document->set('status', "I");

    $handler_doc->save('product', $document);

## Steps to reproduce

1. while inserting 100000000 records via php script sometimes it throws exception.

__Problem__: While inserting the 100000000 records via php script it throws exception "ArangoDBClient\ServerException: 18 lock timeout". I just want to know why it is throwing the exception. I have attached the php file also.

Please let me know if I am doing something wrong and what is the best way to insert the 1 billion records. I have tried with AQL, but db server got crashed in that run. so i have tried with for loop in php and db.save method.

[file.zip](https://github.com/arangodb/arangodb/files/2595482/file.zip)

**Comment by maxkernbach** [comment]
Hi @yashpandya212,

since you are using MMFiles, a possible cause might be that 100M records are too many to hold in physical memory. 

Therefore using the storage engine RocksDB might help in this case. When using RocksDB ensure that the `vm.overcommit_memory` kernel setting value is set to either 0 (0 is the Linux kernel default) to work around possible memory leak. A detailed explanation of jsteemann can be found [here](https://github.com/arangodb/arangodb/issues/5579#issuecomment-437367671).

Could you please give it a try? Also could you share the `arangodb-php` version in use and the AQL query that lead to the dbserver crash?

**Comment by yashpandya212** [comment]
Thank you @maxkernbach for your quick response.

I will try with RocksDB to insert records. 

PFB the AQL query to insert records.

$statement = new Statement($connection, [
          'query' => 'FOR i IN 1..100000000 INSERT { _key: CONCAT("abcdefghijklmnopqrstuvwxyz11", i), tag_id: CONCAT("abcdefghij11", i), product_details_id: "product1",status: "I" } IN product'
      ]
  );

  $statement->execute();

The arango-php version is 3.3.x-dev.

Apart from this, I have one query regarding the insertion time like when I started the php script, in 5-6 hours it had inserted almost 3 crs records, but after that it had inserted only 1 cr records in whole day. Is it because of MMFiles?

**Comment by Simran-B** [comment]
Pardon me, does _cr_ stand for the Hindi word crore = 10 million, so 30 mio and 10 mio records out of 100 mio?

**Comment by yashpandya212** [comment]
Pardon me, yes cr stands for crore so in 5-6 hrs when collection was empty, it had inserted 30 million records and after that 10 million in a whole day.

**Comment by vinaypyati** [comment]
Hi @yashpandya212,

As maxkernbach mentioned that using MMFiles could be a possible cause. Did you have a chance to use RocksDB as storage engine and try inserting the records? Please note that

> When using RocksDB ensure that the vm.overcommit_memory kernel setting value is set to either 0 or 1 (0 is the Linux kernel default) to work around possible memory leak. A detailed explanation of jsteemann can be found [here](https://github.com/arangodb/arangodb/issues/5579#issuecomment-437367671).

Thanks!

**Comment by maxkernbach** [comment]
Hi @yashpandya212,

I am closing this issue for now since we have not heard back from you in a while.
In case the problem persists, please feel free to comment and we will reopen.
