### ISSUE TITLE
Is it safe to add indexes on a replicated (slave) collection ?

### ISSUE THREAD

**Issue by matcho** [arangodb/arangodb#7409]
## My Environment

* __ArangoDB Version__:        e.g. 3.3.19
* __Storage Engine__:            RocksDB
* __Deployment Mode__:       Master/Slave
* __Infrastructure__:               own
* __Operating System__:        Debian 9
* __Used Package__:              Debian or Ubuntu .deb

## This is just a question

I read in the doc that replicated collections on slave nodes should be treated as readonly, ie. one should not add / modify / delete documents on the slave.

But is it OK to add indexes that are not present on the master ?

Thank you
Mathias

**Comment by dothebart** [comment]
A problem with this aproach that comes to my mind is, that if you specify a uniq restriction that isn't there on the leader you may get out of sync. 
Also indices always come at a cost. 
Closing this with the availability of [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) as out of date.
