### ISSUE TITLE
couldn't find shard "" for cluster 

### ISSUE THREAD

**Issue by gao13993335271** [arangodb/arangodb#7429]
while query from edge based on many conditions 
We create  two collection  ，one  named user used to store user info ，the other named   tag used to store tags we designed . we also create a edge to store the relation between each tag and user ,including the weight about the tag to each user .
Now ,we have 500 tags and 60000000 users and more than 250 million relationData in edge .
the data like that :
```
   user :   {"user_id": "phoneNum"}
   tag :{  "t_id": "xxxx", "t_name": "XXXX, "t_weight": 1}
   relation: {"_from":"tag/xxxx","_to":"user/phoneNum","weight":0.25}
```
we have 250 million data in edge named relation and it cost more than 3 minutes to return the result.
sometimes it will shutdown or throw an error like that     couldn't find shard "" for cluster .....
it caused by hardware ? or we used arangodb in wrong way ? 

3 servers  for cluster 
Configuration of each machine
  -  centos6.9 
  -  64G Ram
  -  1T disk
  -  Gigabit Ethernet
  /  Transmission speed between machines     109M/s 
query aql like 
```
   for tag in [a,b,c]
   for relation in pc_portrait_relation filter relation._from == concat("pc_portrait_tag/",tag)
   return distinct relation._to
```
thanks for your help

**Comment by dothebart** [comment]
please add more details about your installation. OS, Hardware, RAM, Disk, etc.
