### ISSUE TITLE
[Question] how to deploy arangodb in docker swarm? 

### ISSUE THREAD

**Issue by szthanatos** [arangodb/arangodb#7448]
## My Environment

* __ArangoDB Version__:        3.3.19
* __Storage Engine__:             any
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   Manual Start in Docker / ArangoDB Starter in Docker
* __Configuration__:               none
* __Infrastructure__:               none
* __Operating System__:        none
* __Used Package__:              Docker - official Docker library

__Problem__:

Sorry for a noob question, but I'm really confuse. 

[The document](https://docs.arangodb.com/devel/Manual/Deployment/Cluster/ManualStart.html#manual-start-in-docker) only tell me how to depoly arangodb cluster with container's command one by one. Especially I have to connect each container manually with host ip ------ in a docker swarm, I even don't know where the container will be.

Is there any example about how to depoly arangodb cluster by compose file? : )

**Comment by maxkernbach** [comment]
Hi @szthanatos,

an example for a working ArangoDB cluster docker file (docker-compose.yaml) can be found below. It can be started by the command `sudo docker-compose -f /path/to/docker-compose.yaml up`. Please note that a docker Daemon has to be running.

It is also possible to create a docker cluster with the [ArangoDB Starter](https://docs.arangodb.com/devel/Manual/Deployment/Cluster/UsingTheStarter.html#using-the-arangodb-starter-in-docker).


docker-compose.yaml:
```
version: "2"
services:

    agency: 
        image: arangodb/arangodb
        environment:
            - ARANGO_NO_AUTH=1
        command: arangod 
          --server.endpoint tcp://0.0.0.0:8529 
          --agency.my-address tcp://agency:8529 
          --server.authentication false 
          --agency.size 3 
          --agency.activate true   
          --database.directory /var/lib/arangodb3

    agency2: 
        image: arangodb/arangodb
        environment:
            - ARANGO_NO_AUTH=1
        command: arangod 
          --server.endpoint tcp://0.0.0.0:8529 
          --agency.my-address tcp://agency2:8529 
          --server.authentication false 
          --agency.size 3 
          --agency.activate true  
          --database.directory /var/lib/arangodb3

    agency3: 
        image: arangodb/arangodb
        environment:
            - ARANGO_NO_AUTH=1
        command: arangod 
          --server.endpoint tcp://0.0.0.0:8529 
          --agency.my-address tcp://agency3:8529 
          --server.authentication false 
          --agency.size 3 
          --agency.endpoint tcp://agency:8529 
          --agency.endpoint tcp://agency2:8529 
          --agency.endpoint tcp://agency3:8529 
          --agency.activate true  
          --database.directory /var/lib/arangodb3

    coordinator:
        image: arangodb/arangodb
        environment:
            - ARANGO_NO_AUTH=1
        command: arangod 
          --server.authentication=false 
          --server.endpoint tcp://0.0.0.0:8529 
          --cluster.my-address tcp://coordinator:8529 
          --cluster.my-local-info coord1  
          --cluster.my-role COORDINATOR 
          --cluster.agency-endpoint tcp://agency:8529 
          --cluster.agency-endpoint tcp://agency2:8529 
          --cluster.agency-endpoint tcp://agency3:8529  
          --database.directory /var/lib/arangodb3
        ports: ['8000:8529']

    coordinator1:
        image: arangodb/arangodb
        environment:
            - ARANGO_NO_AUTH=1
        command: arangod 
          --server.authentication=false 
          --server.endpoint tcp://0.0.0.0:8529 
          --cluster.my-address tcp://coordinator1:8529 
          --cluster.my-local-info coord2  
          --cluster.my-role COORDINATOR 
          --cluster.agency-endpoint tcp://agency:8529 
          --cluster.agency-endpoint tcp://agency2:8529 
          --cluster.agency-endpoint tcp://agency3:8529  
          --database.directory /var/lib/arangodb3
        ports: ['8001:8529']

    coordinator2:
        image: arangodb/arangodb
        environment:
            - ARANGO_NO_AUTH=1
        command: arangod 
          --server.authentication=false 
          --server.endpoint tcp://0.0.0.0:8529 
          --cluster.my-address tcp://coordinator2:8529 
          --cluster.my-local-info coord3  
          --cluster.my-role COORDINATOR 
          --cluster.agency-endpoint tcp://agency:8529 
          --cluster.agency-endpoint tcp://agency2:8529 
          --cluster.agency-endpoint tcp://agency3:8529  
          --database.directory /var/lib/arangodb3
        ports: ['8002:8529']

    db1:
        image: arangodb/arangodb
        environment:
            - ARANGO_NO_AUTH=1
        command: arangod 
          --server.authentication=false 
          --server.endpoint tcp://0.0.0.0:8529 
          --cluster.my-address tcp://db1:8529 
          --cluster.my-local-info db1 
          --cluster.my-role PRIMARY 
          --cluster.agency-endpoint tcp://agency:8529 
          --cluster.agency-endpoint tcp://agency2:8529 
          --cluster.agency-endpoint tcp://agency3:8529 
          --database.directory /var/lib/arangodb3

    db2:
        image: arangodb/arangodb
        environment:
            - ARANGO_NO_AUTH=1
        command: arangod 
          --server.authentication=false 
          --server.endpoint tcp://0.0.0.0:8529 
          --cluster.my-address tcp://db2:8529 
          --cluster.my-local-info db2 
          --cluster.my-role PRIMARY 
          --cluster.agency-endpoint tcp://agency:8529 
          --cluster.agency-endpoint tcp://agency2:8529 
          --cluster.agency-endpoint tcp://agency3:8529  
          --database.directory /var/lib/arangodb3
```

**Comment by szthanatos** [comment]
awesome！ thanks alot

**Comment by Simran-B** [comment]
@maxkernbach Can we make use of your answer in the documentation somehow?

**Comment by JonDum** [comment]
@Simran-B @dothebart I'd like to chime in real quick that this is a very **non** Docker Swarm-y way of doing it.

With this method how do you scale with `docker service scale`? Ideally there'd be one service definition for each the Agency, Coordinator, and the DB and you could set exactly how many of each you desire with `docker service scale arango_agency=9`, `docker service scale arango_db=5`, etc.
It smells real funky if you have to manually edit the services in your stack to add/remove instances (and you lose just about all the rolling/blue-green deployment features of Docker Swarm this way). Is there no better of way of making the various Arango instances auto-discover their peers? (I thought that this was the point of the Agency?)

The docs on the Kubernetes Operator are great, so are the DC/OS docs, but the [docs](https://docs.arangodb.com/devel/Manual/Deployment/Docker/) for Docker lack any mention of Swarm or have any tips on how to get a good Swarm service stack.

**Comment by dothebart** [comment]
Hi, 
I'm sorry we have to focus on one cloud operator which in our case became Kubernetes. However, all is available in source: 
https://github.com/arangodb/kube-arangodb
so at least to control resillience etc. its not easy to work without such an operator that takes active decisions what to do when and how to react on certain events.

You probably want to give these two resources a read:

https://www.arangodb.com/arangodb-cluster-course/
https://docs.arangodb.com/3.4/Manual/Deployment/Manually/

In general to dispatch services by instance probably [using the starter could be a good idea](https://github.com/arangodb-helper/arangodb)? 

If you have things to add to the manual - like more information about how to get docker swarm running -  you may send a PR to its source here: https://github.com/arangodb/arangodb/tree/devel/Documentation/Books/Manual/Deployment

**Comment by dothebart** [comment]
Closing this with the availability of [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) .

**Comment by JonDum** [comment]
@dothebart Just curious, I ctrl+f'd through the changelog and release notes, but couldn't find any mention of docker, compose, or swarm. What in 3.7 makes this no longer relevant?

**Comment by dothebart** [comment]
We currently don't support docker swarm as a deployment since we have to concentrate on the know how we build and maintain. 
If you want to offer a good recipy for that, a good way would be to ask that question on stackoverflow, and provide the answer right ahead.

**Comment by JonDum** [comment]
@dothebart I took a few minutes to create a repo with how we've been doing our ArangoDB deployment in prod. It's pretty bare bones but perhaps useful to others https://github.com/dumstruck/arango-swarm and might be worth mentioning in docs.

**Comment by dothebart** [comment]
Hi, 
Thank you very much for your effort. 
I've asked what will be the best place to link this.
