### ISSUE TITLE
arangoimp missing data but there isn't any warning or error is printed to log file

### ISSUE THREAD

**Issue by pengyunshan** [arangodb/arangodb#7457]
## My Environment

* __ArangoDB Version__:        ArangoDB 3.3.17 [linux] 64bit
* __Storage Engine__:             RocksDB 5.6.0
* __Operating System__:        centos

__Dataset__:
eid	name	age	edu	_key

## Steps to reproduce

- use arangoimp to import a tsv file
the data structure is below
eid	name	age	edu	_key

the first line is table head, each item in one line is split by \t;

- this is my import command
```
 arangoimp --server.username ${arangodb_user} \
        --server.password ${arangodb_password} \
        -server.database ${arangodb_database_tmp} \
        --file ${data_dir}//${file} \
        --type tsv \
        --collection ${collection} \
        --threads 10 \
        --create-collection false > ${log_dir}/${file}.log 2>&1
```
-  this is tail of ${log_dir}/${file}
```
created:          49551416
warnings/errors:  0
updated/replaced: 0
ignored:          0
lines read:       49557316
```
as u can see there is no warnings and errors, but the create lines are smaller than lines read.

__Problem__:
the data is not imported into arango and the arangoimp did not tell any error

__Expected result__:
the right situation is numbers of created lines  add two equal number lines read,or tell me where is wrong.

**Comment by pengyunshan** [comment]
maybe i find one reason .while import data to arangodb using arangoimp ,the arangod suddenly crash and the left data was failed to import.however the log did not print any error message.

**Comment by vinaypyati** [comment]
Hi, @pengyunshan,

Thank you for opening an issue and apologies for the delay. Do you still see this issue happening in the[ latest version](https://download.arangodb.com/arangodb33/index.html) of ArangoDB v3.3.21? If so, can you please attach the `arangod.log` with increased verbosity to `trace` in this ticket? When you are starting the `arangod` server you can enable the verbosity by adding the option `--log.level=trace`. This may help us to track down the issue. 

Thanks!

**Comment by maxkernbach** [comment]
@pengyunshan

I am closing this issue for now since we have not heard back from you in a while.
In case you are still facing this problem, please feel free to comment and we will reopen.
