### ISSUE TITLE
Arango Query Performance Issue over 11k docs

### ISSUE THREAD

**Issue by garryyao** [arangodb/arangodb#7466]
## My Environment

* __ArangoDB Version__:        3.3.19
* __Storage Engine__:             affects both MMFiles and RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   ArangoDB Starter in Docker
* __Configuration__:               
* __Infrastructure__:               AWS
* __Operating System__:        Linux
* __Used Package__:              INFO ArangoDB 3.3.19 [linux] 64bit, using jemalloc, build tags/v3.3.19-0-gfe9657c2ef, VPack 0.1.30, RocksDB 5.6.0, ICU 58.1, V8 5.7.492.77, OpenSSL 1.1.0f  25 May 2017

## Component, Query & Data

__Affected feature__:
Arango query

__AQL query (if applicable)__:

```aql
FOR i IN people
SORT i.name
return i
```

__AQL explain (if applicable)__:

```
Query string:
 FOR i IN people
 SORT i.name
 return i
 

Execution plan:
 Id   NodeType         Est.   Comment
  1   SingletonNode       1   * ROOT
  6   IndexNode       11060     - FOR i IN people   /* hash index scan */
  5   ReturnNode      11060       - RETURN i

Indexes used:
 By   Type   Collection   Unique   Sparse   Selectivity   Fields       Ranges
  6   hash   people       true     false       100.00 %   [ `name` ]   *

Optimization rules applied:
 Id   RuleName
  1   use-indexes
  2   use-index-for-sort
  3   remove-unnecessary-calculations-2

```

__Dataset__:

collection meta: https://gist.github.com/garryyao/82ae82963f2264a948a864f23eecd4ed
collection: https://gist.github.com/garryyao/eeadb3d866ca91899b7cb2cb83222490

## Steps to reproduce

1. Load the sample data set
2. Run the above query in Arango Web Console
3. Look at the performance data

__Problem__:
The query takes at most ~3s and minimal 300ms, which is a performance problem, 

On result of a 300ms query, the below figures illustrates how the query time grow by scaling up the number of documents returned:

```
10: 0.262ms
100: 0.484ms
1000: 20.88ms
10000: 303.624ms
```

__Expected result__:
We expect much better performance where the query time doesn't grow much with the collection size increase.

**Comment by Simran-B** [comment]
At least for MMFiles storage engine it is necessary to use a skiplist index if you want to utilize an index for sorting. Can you try that?

I assume the results you posted used RocksDB?

Did you try 3.3.19 or 3.3.14? You seem to have conflicting information in the template.

**Comment by garryyao** [comment]
We're on `3.3.19` sorry for the confusion, the above is posted from RocksDB engine but I'd say the MMFiles result look very close to that. 

Worth mention that the problem happened only in our k8s environment, so with same Dockerfile the performance issue doesn't really affect local Arango instance.

 I'll give `skipindex` a try, thanks you.

**Comment by garryyao** [comment]
Hi 

We have tried to add a skiplist index for the `name` field, doesn't seem to help with perf. Query explained below:
```
Query string:
     FOR i IN people
         SORT i.name
         RETURN KEEP(i, ['_id', 'name', 'status'])
 

Execution plan:
 Id   NodeType           Est.   Comment
  1   SingletonNode         1   * ROOT
  7   IndexNode         11060     - FOR i IN people   /* skiplist index scan */
  5   CalculationNode   11060       - LET #3 = KEEP(i, [ "_id", "name", "status" ])   /* simple expression */   /* collections used: i : people */
  6   ReturnNode        11060       - RETURN #3

Indexes used:
 By   Type       Collection   Unique   Sparse   Selectivity   Fields       Ranges
  7   skiplist   people       true     false            n/a   [ `name` ]   *

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-calculations-up-2
  3   use-indexes
  4   use-index-for-sort
  5   remove-unnecessary-calculations-2
```

**Comment by manwithsteelnerves** [comment]
@garryyao This issue still exists?

**Comment by dothebart** [comment]
Closing this as out of date with the availability of [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) .
