### ISSUE TITLE
Internal error while deleting edges

### ISSUE THREAD

**Issue by kavin26** [arangodb/arangodb#7473]
## My Environment

* __ArangoDB Version__:        3.1.21
* __Storage Engine__:             MMFiles
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               t2.medium
* __Infrastructure__:               AWS
* __Operating System__:        Ubuntu 16.04.2 LTS
* __Used Package__:             AWS AMI 

## Component, Query & Data

__Affected feature__: Deletion of edges

__AQL query (if applicable)__:

```js
FOR edge IN article_entities
    REMOVE edge IN article_entities
```

__AQL explain (if applicable)__:

__Dataset__:
```json
[
  {
    "_key": "3126567123",
    "_id": "article_entities/3126567123",
    "_from": "Article/3126567117",
    "_to": "Entity/68666676",
    "_rev": "_Xg-n58e---",
    "np_count": 1,
    "ne_tf": 0,
    "ep_count": 0,
    "np_tf": 0.006430868167202572,
    "ne_count": 0,
    "label": [
      "noun-phrase"
    ],
    "ep_tf": 0
  },
  {
    "_key": "18168447689",
    "_id": "article_entities/18168447689",
    "_from": "Article/18168447667",
    "_to": "Entity/10206573828",
    "_rev": "_Xg-275C---",
    "np_count": 1,
    "ne_tf": 0,
    "ep_count": 0,
    "np_tf": 0.014705882352941176,
    "ne_count": 0,
    "label": [
      "noun-phrase"
    ],
    "ep_tf": 0
  }
]
```

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. Ensure there is an edge collections consisting edges between documents
2. Run the above aql query mentioned to delete the edges

__Problem__:

> Query : Internal Error (exception location : /var/lib/otherjenkins/workspace/RELEASE_BuildPackages/arangod/Aql/ModificationBlocks.cpp:244).Please report this to arangodb

![screenshot_2018-11-27 arangodb web interface](https://user-images.githubusercontent.com/11194101/49071976-2e6f7b00-f255-11e8-819e-2705f6eff26a.png)

__Expected result__: All edge relations in the collection needs to be deleted

**Comment by Simran-B** [comment]
Hey Kavin,
ArangoDB v3.1 reached End of Life (EOL) a while ago and is no longer supported.
Can you try the latest stable release please (currently v3.3.19)?
Thanks!

**Comment by kavin26** [comment]
Hi @maxkernbach ,
I am no longer associated with the company where i used arangodb. I might be working using arangodb may be later.

For now, i think i can close it.

Thank you for all the help.
