### ISSUE TITLE
How to check collection/index is existed

### ISSUE THREAD

**Issue by tangkhaiphuong** [arangodb/arangodb#7493]
I don't see any API support to checking collection existed or not. And same for indexer, how to get information indexes of the collection.

**Comment by dothebart** [comment]
Hi, 
you usually would simply invoke https://docs.arangodb.com/3.4/HTTP/Collection/Getting.html#getting-information-about-a-collection or https://docs.arangodb.com/3.4/HTTP/Collection/Getting.html#return-statistics-for-a-collection and check whether it returns an error ERROR_ARANGO_DATA_SOURCE_NOT_FOUND https://docs.arangodb.com/3.4/Manual/Appendix/ErrorCodes.html#checked-arangodb-storage-errors for non existing collections. 
The collection statistics API will also give you a list of the indices, which you can evaluate.

**Comment by Simran-B** [comment]
@tangkhaiphuong Are you actually asking for the HTTP API? Or the JS API (arangosh/Foxx)?

**Comment by tangkhaiphuong** [comment]
@Simran-B @dothebart Sorry, I put question wrong place, it should be in https://github.com/ra0o0f/arangoclient.net/issues/114
for C# Client API.
