### ISSUE TITLE
Create collection through API should return HTTP status code 201

### ISSUE THREAD

**Issue by yojimbo87** [arangodb/arangodb#752]
When creating new collection through API resulting HTTP code should be 201 instead of 200, to keep it uniform with other create operations. This change might break some clients, so it should be implemented in next major version.

**Comment by jsteemann** [comment]
Should go into 3.0.

**Comment by jsteemann** [comment]
We released 3.1 and it's still returning HTTP 200 on creation...
IIRC the reason we didn't change this yet time was that when trying this out too many tests and client drivers broke.

**Comment by Simran-B** [comment]
GitHub supports multiple milestones per issue meanwhile, should this be tagged for v4.0?

**Comment by jsteemann** [comment]
Let's leave it in backlog so the issue can be addressed any time it is convenient.

**Comment by dothebart** [comment]
closing as `won't fix` due to API stability.
