### ISSUE TITLE
Too many connections with cluster mode.

### ISSUE THREAD

**Issue by tangkhaiphuong** [arangodb/arangodb#7561]
## My Environment

* __ArangoDB Version__:        3.3.19
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   Manual Start
* __Configuration__:               https://github.com/arangodb-helper/arangodb 
* __Infrastructure__:               Virtual Machine on vSphere of OVH system.
* __Operating System__:        CentOS
* __Used Package__:              CentOS

## Steps to reproduce

1. Using ArangoImp tool to import many large list of JSON in concurrent
2. Go to ArangoDB Site and found over 11345 connection
3. Use netstat checking and show too many connections in ESTABLISHED

```
[2:51 PM] Nick: [root@arangodb02 ~]# netstat -tnp | grep 172.16.128.140 | wc -l
11436
[2:51 PM] Nick: tcp6       0      0 172.16.3.31:8529        172.16.128.140:53448    ESTABLISHED 1591/arangod
tcp6       0      0 172.16.3.31:8529        172.16.128.140:62621    ESTABLISHED 1591/arangod
tcp6       0      0 172.16.3.31:8529        172.16.128.140:65147    ESTABLISHED 1591/arangod
tcp6       0      0 172.16.3.31:8529        172.16.128.140:54801    ESTABLISHED 1591/arangod
tcp6       0      0 172.16.3.31:8529        172.16.128.140:59703    ESTABLISHED 1591/arangod
tcp6       0      0 172.16.3.31:8529        172.16.128.140:61421    ESTABLISHED 1591/arangod
```

__Problem__:
Too many connections still keep in ArangoDB

__Expected result__:
Should clean out all connection.

**Comment by dothebart** [comment]
Hi, 
could you retry using the arangoimp of the 3.4 RC? ( https://www.arangodb.com/download-technical-preview/ )
Its a bit cleverer at not outpacing the cluster so it should stop this situation from happening - its documented over at https://docs.arangodb.com/3.4/Manual/Programs/Arangoimport/Details.html#automatic-pacing-with-busy-or-low-throughput-disk-subsystems

**Comment by tangkhaiphuong** [comment]
@dothebart  I tried again with ArangoClient 3.4 RC using arangoImport.exe. The connection still increases high over 800.

**Comment by GaetanLhoest** [comment]
Hi,

Is there any update about this issue?

**Comment by dothebart** [comment]
With ArangoDB 3.4 [@matthewvon  introduced a new autopacing algorithm with arangoimport not to overload the servers while importing](https://www.arangodb.com/docs/stable/programs-arangoimport-details.html#automatic-pacing-with-busy-or-low-throughput-disk-subsystems) which should make sure that clusters don't get overloaded with imports though offering maximum available throughput.
If you still experience problems with latest ArangoDB versions, please provide figures about I/O saturations on your system, the size of your import, and other figures.

**Comment by matthewvon** [comment]
Connection count:  is 800 connection count between the importing machine and the one cluster coordinator, or between the coordinator and all db servers (plus the importing machine)?

**Comment by dothebart** [comment]
Hi, 
we haven't heard back from you in a while; since we have no way to reproduce or work on this issue without further information, I will close this now. 
If you have further details please let us know so we can reopen this, or create a new issue.
