### ISSUE TITLE
 memory  usage is too high even though moved shards to other server

### ISSUE THREAD

**Issue by gao13993335271** [arangodb/arangodb#7584]
## My Environment

* __ArangoDB Version__:        3.3.14
* __Storage Engine__:              RocksDB 
* __Deployment Mode__:        Cluster 
* __Deployment Strategy__:    Manual Start
* __Operating System__:         centos 6.9

__Replication Factor & Number of Shards (Cluster only)__:

1 replication factor 
9 shards for each collection

__Problem__:
 memory  usage is too high
Memory will not be reduced  even though moving 3 shards to other machine
We have  a cluster for  4 machines ，and 9 shards for one collection ，server94 is the master node ,each machine has 128G memory .
last week we found the most shards was distributed in the machine named  server93  and server94，and we can't  import data into cluster ,the error was http connection was broken ,this error found in server94 . finally we found maybe too high memory caused this problem.  
then we moved  3 shards to other server named server95, we found the memory usage in server95 reached 60% , but  the memory usage in server94 didnlt reduce ,it keeped 96% . 
we don't konw it is a bug or not ？
we hope you could help us to solve this problem . 
__Expected result__:
help us to solve this problem

**Comment by OmarAyo** [comment]
Hi @gao13993335271 

Thanks for opening this ticket.

As first step, please could you let us know the exact value of `overcommit_memory` you are currently using by running the following command:
```
cat /proc/sys/vm/overcommit_memory 
```
If the value is `2` could you try to set the `overcommit_memory` setting of the kernel to 0 (or 1) by issuing the following command:

```
echo 0 > /proc/sys/vm/overcommit_memory
```
Setting the `vm.overcommit_memory` sysctl setting to 0 (or even 1, both will do) should improve the situation.

Please note: the change will only be in effect until the host machine is restarted.

**Comment by gao13993335271** [comment]
> Hi @gao13993335271
> 
> Thanks for opening this ticket.
> 
> As first step, please could you let us know the exact value of `overcommit_memory` you are currently using by running the following command:
> 
> ```
> cat /proc/sys/vm/overcommit_memory 
> ```
> If the value is `2` could you try to set the `overcommit_memory` setting of the kernel to 0 (or 1) by issuing the following command:
> 
> ```
> echo 0 > /proc/sys/vm/overcommit_memory
> ```
> Setting the `vm.overcommit_memory` sysctl setting to 0 (or even 1, both will do) should improve the situation.
> 
> Please note: the change will only be in effect until the host machine is restarted.

happy to see your help ,but  the value of  /proc/sys/vm/overcommit_memory is 0

**Comment by OmarAyo** [comment]
Hi @gao13993335271,

For some reason, my previous message was deleted, thanks for replying, I get back to you with more information,

Best

**Comment by OmarAyo** [comment]
In our upcoming 3.3 release, we introduced a new option which can be used to limit the total amount of memory used for in-memory write buffers in RocksDB. 

I will get back to you when the 3.3 release will be officially released, with more information on how to use and set this new option.

Best,

**Comment by gao13993335271** [comment]
you means it is a bug for current version ?
thanks for your help.

**Comment by OmarAyo** [comment]
It is not a bug, it is related to RocksDB itself - we have seen RocksDB accumulating a lot of memory in its write buffers for whatever reason. Setting this option to any value > 0 will restrict this memory usage.

**Comment by gao13993335271** [comment]
get it !
thanks for your help! 
by the way , i want to know how to set or change timezone for arangodb ?
i am in china but the arangodb didn't follow the machine time 
it also confused me for a long time

**Comment by Simran-B** [comment]
You should see timestamp like `2018-12-03T11:42:02.775Z`, with a **Z** at the end. It stands for Zulu time, which is UTC±00:00 ([Coordinated Universal Time](https://en.wikipedia.org/wiki/Coordinated_Universal_Time)), so without a timezone offset.

There is an option to use local time in logging:
https://docs.arangodb.com/3.3/Manual/Administration/Configuration/Logging.html#local-time

**Comment by gao13993335271** [comment]
thank you !

**Comment by OmarAyo** [comment]
Hi @gao13993335271,

Just sending a quick followup - did you have the chance to try ArangoDB version 3.4.0 and set the above rocksdb options? Could you share some feedback 

Thanks

**Comment by OmarAyo** [comment]
Hi @gao13993335271 

Since we have not heard back from you in a while, I will close this issue for now.
In case you have any further questions, please feel free to comment and we will reopen this issue.
