### ISSUE TITLE
Cannot select database in web interface

### ISSUE THREAD

**Issue by marcoEgger** [arangodb/arangodb#7700]
## My Environment

* __ArangoDB Version__: 3.3.20
* __Storage Engine__: RocksDB
* __Deployment Mode__: Single Server
* __Deployment Strategy__: Manual Start in Docker
* __Infrastructure__: Locally
* __Operating System__: Windows 10
* __Used Package__: Docker - official Docker library

## Steps to reproduce

1. Create new database which contains `advert`, `advertisement` or `advertisements` in web interface or through arangojs. Username = root, which is the only user existing.
2. Try to connect to new database through web interface 
3. Get `Error (DB: advertisements): error`

__Problem__:
Cannot select database in web interface when database contains word `advert`.

__Expected result__:
Can select and view database in web interface.

**Comment by jsteemann** [comment]
I can't reproduce the problem locally.
ArangoDB does not filter on database names at all, or discriminate based on database names. So I guess this is a browser or infrastructure problem.
It sounds a bit like your browser or a firewall is blocking the access. This may be a "feature", e.g. when using an adblocker. It may just filter out potential ads and it may do that base on wording ("advertisement" sounds like something an adblocker may identify as well, an advertisement).

You can quickly check if it is a browse problem by using a different browser or by trying to access the database using curl:
```
curl -X GET http://127.0.0.1:8529/_db/advertisement/_api/version --dump - --user "root:"
```
This should return HTTP 200 and a JSON document if a database `advertisement` exists. Please adjust `root:` to actual username and password as needed. Same for IP address/port.

**Comment by marcoEgger** [comment]
You are correct, it was indeed the AdBlocker. Didn't came to my mind, thank you very much!
