### ISSUE TITLE
Feature request: Support for storing binary data

### ISSUE THREAD

**Issue by internalfx** [arangodb/arangodb#7702]
Are there any plans to support storing binary BLOBs?

I am evaluating arango coming from RethinkDB.

RethinkDB supported objects with keys that contained nodejs buffers.

```
r.table('files').insert({
      userId: userId,
      filename: saveName,
      file: contents // contents is a buffer, so we do not need to wrap it in `r.binary`
    }).run(conn, callback)
```

Documentation on their functionality can be viewed here: https://www.rethinkdb.com/docs/storing-binary/javascript/

Thoughts?

Thank you for your time.

**Comment by Simran-B** [comment]
This is a long-standing feature request, tracked and discussed here: #107

There are no short-term plans to implement such a feature, mostly because it's unclear how to deal with binary data on the transport layer (see the linked issue for details).
