### ISSUE TITLE
Arangodb 3.4 install fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by kashifpk** [arangodb/arangodb#7705]
## My Environment

* __ArangoDB Version__:        3.4.0
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual StartStarter in Docker | Kubernetes | DCOS -->
* __Configuration__:               Default clean install on single server
* __Infrastructure__:               own
* __Operating System__:        Ubuntu 18.04
* __Used Package__:             Debian or Ubuntu .deb

## Component, Query & Data

__Affected feature__: Installation

## Steps to reproduce

1. Download either the .deb file or install via ubuntu package repo
2. Try installing arangodb

__Problem__:

Upon installation of arangodb 3.4 on Ubuntu 18.04 64-bit, I get 

```bash
Setting up arangodb3 (3.4.0-1) ...
Illegal instruction (core dumped)
FATAL ERROR: EXIT_CODE_RESOLVING_FAILED for code 132 - could not resolve exit code 132
dpkg: error processing package arangodb3 (--configure):
 installed arangodb3 package post-installation script subprocess returned error exit status 132
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 arangodb3
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

This happens if I use the .deb file or include ubuntu package repository. So both methods fail on Ubuntu 18.04.

The same system had arangodb 3.3.20 running without issues. To test 3.4 I removed (purged) previous install but still this error keeps popping up.

Removing 3.4 and reinstalling 3.3 works so this error is not present in 3.3.

__Expected result__:

Successful installation.

**Comment by maxkernbach** [comment]
Hi @kashifpk,

just to be sure, did you try the following 3.4 [.deb file](https://download.arangodb.com/arangodb34/Community/Linux/arangodb3_3.4.0-1_amd64.deb), which is listed at: 
https://www.arangodb.com/download-major/ubuntu/?

I just did a quick test on Ubuntu 18.04 and it worked fine.

1. Uninstall arangodb via `sudo apt-get purge arangodb3`
2. Install arangodb 3.4 via `sudo dpkg -i arangodb3_3.4.0-1_amd64.deb`

**Comment by kashifpk** [comment]
Yes I used the same file, just to make sure tried the above again and had the same result.

**Comment by maxkernbach** [comment]
Could you please post share the output of `less /proc/cpuinfo`?

Since ArangoDB 3.4 requires SSE4.2 for performance improvements, this problem is probably caused by an older cpu on your system.

**Comment by kashifpk** [comment]
yes that probably is the issue. My CPU seems to support only SSE3. Can I compile from source disabling SSE4.2 specific performance improvements?

```bash
$ cat /proc/cpuinfo 
processor       : 0                                                                                                                    
vendor_id       : GenuineIntel                                                                                                         
cpu family      : 6                                                                                                                    
model           : 15                                                                                                                   
model name      : Intel(R) Core(TM)2 Quad CPU    Q6600  @ 2.40GHz                                                                      
stepping        : 11
microcode       : 0xba
cpu MHz         : 2151.960
cache size      : 4096 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 4
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts nopl cpuid aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm lahf_lm pti tpr_shadow vnmi flexpriority dtherm
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
bogomips        : 4799.79
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 15
model name      : Intel(R) Core(TM)2 Quad CPU    Q6600  @ 2.40GHz
stepping        : 11
microcode       : 0xba
cpu MHz         : 2046.905
cache size      : 4096 KB
physical id     : 0
siblings        : 4
core id         : 1
cpu cores       : 4
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts nopl cpuid aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm lahf_lm pti tpr_shadow vnmi flexpriority dtherm
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
bogomips        : 4799.79
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

processor       : 2
vendor_id       : GenuineIntel
cpu family      : 6
model           : 15
model name      : Intel(R) Core(TM)2 Quad CPU    Q6600  @ 2.40GHz
stepping        : 11
microcode       : 0xba
cpu MHz         : 2030.484
cache size      : 4096 KB
physical id     : 0
siblings        : 4
core id         : 2
cpu cores       : 4
apicid          : 2
initial apicid  : 2
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts nopl cpuid aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm lahf_lm pti tpr_shadow vnmi flexpriority dtherm
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
bogomips        : 4799.79
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

processor       : 3
vendor_id       : GenuineIntel
cpu family      : 6
model           : 15
model name      : Intel(R) Core(TM)2 Quad CPU    Q6600  @ 2.40GHz
stepping        : 11
microcode       : 0xba
cpu MHz         : 2118.344
cache size      : 4096 KB
physical id     : 0
siblings        : 4
core id         : 3
cpu cores       : 4
apicid          : 3
initial apicid  : 3
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts nopl cpuid aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm lahf_lm pti tpr_shadow vnmi flexpriority dtherm
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
bogomips        : 4799.79
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:
```

**Comment by maxkernbach** [comment]
Hi @kashifpk,

compiling from source should work since the **cmake** process does an auto-detection and adjusts accordingly. Instructions on how to compile can be found in this [Cookbook](https://docs.arangodb.com/3.4/Cookbook/Compiling/Debian.html#install-build-dependencies).

In order to compile the 3.4 branch, you have to execute the following command after cloning the github repository:

```
git checkout 3.4
```

Could you please give it a try?

**Comment by TomTem** [comment]
I had a similar problem when trying to run the latest arangodb docker container (ArangoDB 3.4.1). I spend many hours moving heaven and earth to get the container with ArangoDB up and running, with no success. So I'm happy to find this thread, now I know what the problem is, my processor = Intel Core2Quad Q6700 @2.66GHz = also an old one without SSE4.2 support.

When I tried in a virtual machine on a server with a Intel Xeon E5-2620 v3 processor, I had immediate success.

**Comment by vinaypyati** [comment]
Hi, @kashifpk,

Did you have a chance to compile 3.4 from source successfully? Let us know your feedback. Thanks!

Hi @TomTem, 

Glad that you found this ticket and it helped you identify the root cause!

**Comment by kashifpk** [comment]
Hi @vinaypyati - sorry for the delayed response. Yes I compiled and check 3.4.1 and is working fine so it's only the default compiler optimizations that are not supported on older hardware that were the issue.

Thank you for the support :-)
