### ISSUE TITLE
officially maintained chef cookbook?

### ISSUE THREAD

**Issue by luebbert42** [arangodb/arangodb#771]
Sebastian Cohnen asked on twitter if the team can provide an officially maintained chef cookbook. 

- does someone know if  https://github.com/jbianquetti/chef-arangodb is still working? (maybe Wolfgang uses this for MyArangoDB?)
- is it a nice idea to ask if we can officially maintain this repo using the ArangoDB organization in case the user is no longer mainting the repo?

**Comment by dothebart** [comment]
We're using docker etc. so cheff is currently not of interest. Closing.
