### ISSUE TITLE
Utilize primary index when sorting by document _key (or _id)

### ISSUE THREAD

**Issue by Simran-B** [arangodb/arangodb#7720]
A query like:

```js
FOR doc IN coll SORT doc._key RETURN doc
```

can not be accelerated by the primary index (as of 3.3.20 / 3.4.0).

The primary index is sorted in RocksDB, but it is reporting itself as being non-sorted. That is for some internal reasons. It could be changed however, and allow the optimizer to apply the `use-index-for-sort` optimization for above query.

Related:
- https://stackoverflow.com/questions/53701050/can-we-add-an-extra-index-on-key-column-in-arangodb

**Comment by jsteemann** [comment]
@Simran-B : this has been done for 3.5/devel. Can we close this issue now?

**Comment by Simran-B** [comment]
Noteworthy: it must be _key, _id does not work.
