### ISSUE TITLE
Getting unique constraint violated error with rocksDB while inserting documents after DB crash

### ISSUE THREAD

**Issue by yashpandya212** [arangodb/arangodb#7726]
## My Environment

* __ArangoDB Version__:        3.3.19
* __Storage Engine__:             RocksDB
* __Deployment Mode__:         Single Server
* __Infrastructure__:                 AWS
* __Operating System__:         Ubuntu 16.04.4 LTS
* __Used Package__:              Ubuntu .deb

Whenever the db got crashed, mostly due to range search, the auto_increment count didn't incremented to the current value and will get unique constraint violation error on insertion. This problem is related to same issue #2904. 

I have applied auto_increment option on _key column. When I got the unique constraint violation error, I checked the properties of collection and found that last_Incremented_value is way behind than the last document inserted in db. This happens only when DB got crashed.

**Comment by dothebart** [comment]
Since Arangodb 3.3 is long EOLed by now, closing this as outdated with the availability of [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/)
