### ISSUE TITLE
What is the capacity of Arangodb and how many data can be stored without obvious performance degradation. Can you provide some information for reference, including hardware information? Thank you.

### ISSUE THREAD

**Issue by cangsangkanyun** [arangodb/arangodb#7767]
ArangoDB Version: 3.4
Storage Engine: RocksDB
Deployment Mode: Single Server
Infrastructure: own
Operating System: Ubuntu 16.04
Used Package:  Ubuntu .deb

**Comment by CBlinguland** [comment]
The information is interesting for me too.
This could help me to decide if multi-company would be possible regarding performance.

**Comment by maxkernbach** [comment]
Hi @cangsangkanyun and @CBlinguland,

has the latest comment been helpful? Do you have any further questions?

**Comment by maxkernbach** [comment]
@cangsangkanyun and @CBlinguland 

I am closing this issue as solved for now. 
In case you have any further questions, please feel free to comment and we will reopen.
