### ISSUE TITLE
Unable to force a FILTER order

### ISSUE THREAD

**Issue by jcdutton** [arangodb/arangodb#7775]
## My Environment

* __ArangoDB Version__:        3.4
* __Storage Engine__:             RocksD
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               Simple single server setup
* __Infrastructure__:               Server, 16 CPUs
* __Operating System__:        CentOS 7
* __Used Package__:              .rpm

## Component, Query & Data

__Affected feature__:
Example FILTER:  A=B AND C=D   
How do I force Arango to do A=B first, then C=D?
For example, say A=B will pick out 1 record from 1 million, and C=D will pick out 500000 from 1 million,  It makes sense to force arango to do the A=B bit first.

__AQL query (if applicable)__:
Not given

__AQL explain (if applicable)__:

Not given

__Dataset__:
Not given

__Replication Factor & Number of Shards (Cluster only)__:
Not given

## Steps to reproduce

1. FILTER:  A=B AND C=D
2. Arango uses C=D first, then A=B based on its own optimizations.
3. I wish to be able to force A=B first, then C=D because I know better what sort of data is stored than arango could work out.

__Problem__:

__Expected result__:
1)  FILTER: A=B AND C=D
Should search using first A=B, and then C=D.
2) FILTER: C=D AND A=B
Should search using first C=D, and then A=B.

**Comment by jsteemann** [comment]
AFAIK there is no standard way of enforcing the order for two FILTERs, but there is a way to turn off specific optimizations should this be required.
I am wondering if you could share a concrete query example for the filter orders being interchanged, as it is not happening in all cases.
For example, here is a query for which it is not happening: 
```
Query String:
 FOR doc IN collection FILTER doc.a == 2 AND doc.b == 3 AND doc.c == 9 RETURN doc

Execution plan:
 Id   NodeType                  Est.   Comment
  1   SingletonNode                1   * ROOT
  2   EnumerateCollectionNode   1000     - FOR doc IN x   /* full collection scan */
  3   CalculationNode           1000       - LET #1 = (((doc.`a` == 2) && (doc.`b` == 3)) && (doc.`c` == 9))   /* simple expression */   /* collections used: doc : x */
  4   FilterNode                1000       - FILTER #1
  5   ReturnNode                1000       - RETURN doc
```
It would be helpful if you could send the full execution plan for the query. 
Thanks!

**Comment by jcdutton** [comment]
I guess another approach is if I try to explain what I am trying to do.
I call it a "profile" search.
Say I have a list of nodes A,  lets call that "people" with field "id"
I have a list of nodes B, lets call that "cloths" with fields "type" containing "dress" or "shirt" or some type of clothing.
I have a list of nodes C, lets call that "likes" with fields "colour" containing "red" or "green" etc.
There are edges/links between A -> B, and A -> C.

So, the question I wish to ask is something like:
Show me all the people who have brought "cloths":"type"=="dress", and "likes": "colour":"red".
Returns a list of people IDs.

I also wish the edges/links to have other fields on this, e.g. dates.
So, I could ask:
Show me all the people who have brought "cloths":"type"=="dress", and "likes": "colour":"red" in the last 3 months.

Now, suppose I have prior knowledge, and I know that a count of "type" == "dress" will be 10, and count of "colour" == "red" is 500000.
So, I would wish to run the "type" == "dress" first, because that has already cut the list of people down to 10, and further restricting that to "colour" == "red" should be quick.
But, what I am seeing is the system scanning 500000 records, and no way to force it to scan only 10.

**Comment by Simran-B** [comment]
So this is about filters in traversals (FilterNode followed by TraversalNode) in the particular use case.

In order to determine which filter criterion is more selective for a given value, wouldn't it be necessary to have some sort of index with counts? To make this index eligible for traversals, it would need to be a vertex-centric index with such stats if I'm not mistaken.

**Comment by vinaypyati** [comment]
Hi @jcdutton,

Just sending a quick follow up. Did you have a chance to read what Simran-B wrote above? Please let us know your feedback. 

Thanks!

**Comment by maxkernbach** [comment]
@jcdutton 

I am closing this issue for now since we have not heard back from you in a while.
In case you are still facing a problem, please feel free to comment and we will reopen.
