### ISSUE TITLE
Arangod restarting due to Segfault

### ISSUE THREAD

**Issue by cboothe** [arangodb/arangodb#7777]
## My Environment

* __ArangoDB Version__:        3.4
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   ArangoDB Starter
* __Configuration__:               Single Master
* __Infrastructure__:               Digital Ocean VM
* __Operating System__:        Ubuntu 18.04.1 LTS
* __Used Package__:              Ubuntu deb 3.4.0-1

Config:
server.maximal-threads = 12  # 4 core server

## Component, Query & Data

__Affected feature__:
arangod

__Replication Factor & Number of Shards (Cluster only)__:
1

## Steps to reproduce

1. 
2. 
3. 

__Problem__:

Strange restarting of ArangoDB server. Only visible in the logs when debug level is set to trace.

2018-12-16T12:29:28Z [26637] INFO ArangoDB 3.4.0 [linux] 64bit, using jemalloc, build tags/v3.4.0-0-g3a7df19189, VPack 0.1.33, RocksDB 5.16.0, ICU 58.1, V8 5.7.492.77, OpenSSL 1.1.0h  27 Mar 2018
2018-12-16T12:29:28Z [26637] INFO detected operating system: Linux version 4.15.0-42-generic (buildd@lgw01-amd64-023) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018
2018-12-16T12:29:28Z [26637] DEBUG host ASLR is in use for shared libraries, stack, mmap, VDSO, heap and memory managed through brk()
2018-12-16T12:29:28Z [26637] INFO {authentication} Jwt secret not specified, generating...
2018-12-16T12:29:28Z [26637] DEBUG {authentication} Setting jwt secret 
2018-12-16T12:29:28Z [26637] INFO using storage engine rocksdb
2018-12-16T12:29:28Z [26637] INFO {cluster} Starting up with role SINGLE
2018-12-16T12:29:28Z [26637] DEBUG permanently changing the gid to 999
2018-12-16T12:29:28Z [26637] DEBUG permanently changing the uid to 999
2018-12-16T12:29:28Z [26637] INFO {syscall} file-descriptors (nofiles) hard limit is 131072, soft limit is 131072
2018-12-16T12:29:28Z [26637] DEBUG {config} using default language 'en_US'
2018-12-16T12:29:29Z [26637] INFO {authentication} Authentication is turned on (system only), authentication for unix sockets is turned on
2018-12-16T12:29:29Z [26637] DEBUG {config} using default language 'en_US'
2018-12-16T12:29:29Z [26637] WARNING found existing lockfile '/var/lib/arangodb3/LOCK' of previous process with pid 22120, but that process seems to be dead already

Here is the reason for the shutdown based on journalctl logs

Dec 16 13:19:49 aro-db1 systemd[1]: arangodb3.service: Main process exited, code=killed, status=11/SEGV
Dec 16 13:19:49 aro-db1 systemd[1]: arangodb3.service: Failed with result 'signal'.
Dec 16 13:19:54 aro-db1 systemd[1]: arangodb3.service: Service hold-off time over, scheduling restart.
Dec 16 13:19:54 aro-db1 systemd[1]: arangodb3.service: Scheduled restart job, restart counter is at 2.

__Expected result__:

**Comment by Simran-B** [comment]
> found existing lockfile '/var/lib/arangodb3/LOCK' of previous process with pid 22120, but that process seems to be dead already

Is that lock file from a previous crashed arangod process, or did you try to start another process using the same data folder?

**Comment by cboothe** [comment]
@Simran-B Yes, it is being restarted on it's own. I seem to be able to recreate the restarting but haven't got a clue what is causing it. 

I am using ArangoSearch and can consistently get arangodb3.service to restart.
Maybe the AQL Query will help.

FOR doc IN aro_1_search
                SEARCH STARTS_WITH(doc.title_suggest, ${search_query}) OR STARTS_WITH(doc.model_no_suggest, ${search_query}) or STARTS_WITH(doc.part_no_suggest, ${search_query})
                SORT TFIDF(doc) DESC
                LIMIT 30
                RETURN doc

**Comment by Simran-B** [comment]
So you use arangojs as driver. What is the value of `search_query`?

**Comment by Simran-B** [comment]
Is there anything in the web console? Does the query work if you issue it via arangosh or curl?

**Comment by jsteemann** [comment]
@cboothe : thanks for sharing the query and the bind parameter value.
I don't see any issue in the query itself, so the problem may be data-dependent.
Can you share the view setup plus some example data for the underlying collections, so we can reproduce the issue locally?
The view's properties can be exported by running `db._view("aro_1_search").properties()` in arangosh.
Thanks!

**Comment by cboothe** [comment]
For sure. Thanks @jsteemann 
Doesn't seem to make a difference where I send the query either.

127.0.0.1:8529@aro_1> db._view("aro_1_search").properties()
{
  "writebufferSizeMax" : 33554432,
  "consolidationPolicy" : {
    "type" : "bytes_accum",
    "threshold" : 0.10000000149011612
  },
  "writebufferActive" : 0,
  "consolidationIntervalMsec" : 60000,
  "cleanupIntervalStep" : 10,
  "links" : {
    "aro_1_6e65772d636f6c6c656459485" : {
      "analyzers" : [
        "identity"
      ],
      "fields" : {
        "name" : {
          "analyzers" : [
            "text_en"
          ]
        }
      },
      "includeAllFields" : true,
      "storeValues" : "none",
      "trackListPositions" : false
    }
  },
  "writebufferIdle" : 64
}

Collection sample below. I have had to lower case model_no_suggest, part_no_suggest, title_suggest because the STARTS_WITH search function is case sensitive for some reason. Therefore they are stored twice

{
  "desc": "Wilden 00-9551-52 Replacement Kit Number N00-9551-52 as manufactured by Nomad, P.025 BUNA/METALLIC, Kits for 1/4\" Pumps (N00). Includes N00-1010-52 (2), N00-1080-55 (4), N00-1200-52 (4), N04-2390-52 (4), N00-1120-01 (4).",
  "manufacturer": "Nomad",
  "model_no": "00-9551-52",
  "model_no_suggest": "00-9551-52",
  "name": "N00-9551-52",
  "part_no": "",
  "part_no_suggest": "",
  "product_url": "/nomad/wilden-replacement-kits/n00-9551-52/",
  "series_title": "Wilden Replacement Kits",
  "slug": "n00-9551-52",
  "text": "N00-9551-52",
  "title": "N00-9551-52",
  "title_suggest": "n00-9551-52"
}

**Comment by KVS85** [comment]
@cboothe thank you for the information.

Unfortunately, I was not able to reproduce your issue. Could you please provide a dump of `aro_1_6e65772d636f6c6c656459485` collection using [arangodump](https://docs.arangodb.com/3.4/Manual/Programs/Arangodump/) tool?

Also can you please tell whether `aro_1_search` view (with corresponding properties) was created before `aro_1_6e65772d636f6c6c656459485` had been populated or it was created on top of existing data?

**Comment by cboothe** [comment]
@KVS85 Sure, where can I send the dump file?
The aro_1_search view was created after.

**Comment by KVS85** [comment]
@cboothe you can either attach it here or send it to me (*vadim.arangodb*) at ArangoDB Community Slack (if it's more convenient)?

**Comment by gnusi** [comment]
@cboothe thank you again for submitting the issue and providing us all necessary data. The issue is fixed now in `devel` in `3.4`. Later this week there will be a minor release which includes the fix.

**Comment by KVS85** [comment]
@cboothe please, try `3.4.1` version with fix for this issue: https://www.arangodb.com/download-major/.

**Comment by cboothe** [comment]
Issue resolved @KVS85
