### ISSUE TITLE
Changes in memory management, right usage of new option introduced in 3.3.20 / 3.4 series

### ISSUE THREAD

**Issue by soualid** [arangodb/arangodb#7787]
Hello,

We experienced a big change in memory consumption of our databases since we upgraded to 3.3.20 our production environments and to 3.4 our staging environments.

We are wondering if we are properly using the new `--rocksdb.total-write-buffer-size`. 

As shown on the graph, the great news is that the engine is way more stable now, but it feels like the database is not getting the benefit of all the available memory, this server has 600GB memory available and the options used at startup are: 

```
--rocksdb.wal-file-timeout
15600
--server.authentication-system-only
false
--tcp.backlog-size
100
--rocksdb.block-cache-size
40000000
--rocksdb.total-write-buffer-size
10%	
```

<img width="1288" alt="screenshot 2018-12-18 10 30 27" src="https://user-images.githubusercontent.com/1830223/50145148-2a150b80-02b1-11e9-833c-e1da2ac3e19d.png">

Can you confirm we are using the new option introduced in 3.3.20/3.4 series properly?

Many thanks.

**Comment by maxkernbach** [comment]
Hi @soualid,

could you please share some details about your machine? Also, are you using edges in your database? Setting `--rocksdb.block-cache-size` to 40000000 seems a bit low, the default value is `(system RAM size - 2GiB) * 0.3`.

It will be easier to give you a suggestion once we know further details of your setup.

**Comment by soualid** [comment]
Thank you! There was obviously a mistake in the value chosen for our `--rocksdb.block-cache-size` configuration, sorry for bothering you for that. More information on the machine below:

- 768 Go DDR4 ECC 
- 2x Intel® Xeon® Gold 6140 
- 8x1 To SSD NVMe (RAID 1)

We just restarted this slave with a `--rocksdb.block-cache-size` of `400000000000` which seems more appropriate for the hardware used. I bet it will solve this issue, and hopefully give a great boost to read performances.

Thank you again for pointing this out!
