### ISSUE TITLE
[document] [geo] Are geographic lines geodesics or rhumb ones?

### ISSUE THREAD

**Issue by kkdd** [arangodb/arangodb#7791]
Congratulation for the release of version 3.4 and its geo functionalities.
With regard to it, are its lines (and edges of a polyline) [geodesics](https://en.wikipedia.org/wiki/Geodesic) or [rhumb lines](https://en.wikipedia.org/wiki/Rhumb_line)? The solution for on which side a point resides depends on above definition, shown in the following figure:

```
     /
p   /
   /  q
  /
```

**Comment by maxkernbach** [comment]
Hi @kkdd, 

ArangoDB 3.4 is using the [S2 Geometry Library](http://s2geometry.io/about/overview.html), which is using "spherical geodesics".

> In S2, all edges are “spherical geodesics”, i.e. shortest paths on the sphere. For example, the edge between two points 100 meters apart on opposite side of the North pole goes directly through the North pole. In contrast, the same edge in the standard “plate carrée” projection (i.e., raw latitude/longitude coordinates) would follow a line of constant latitude, which in this case happens to be a semicircular path that always stays exactly 50 meters away from the North pole. (Lines of latitude except for the equator are never shortest paths.)
> 
> With geodesic edges there are no special cases near the poles or the 180 degree meridian; for example, if two points 10km apart are separated by the 180 degree meridian, the edge between them simply crosses the meridian rather than going all the way around the other side of the Earth.

**Comment by maxkernbach** [comment]
Closing this issue as solved.

In case you have any further questions, please feel free to comment and we will reopen this issue.
