### ISSUE TITLE
"Connection aborted" errors when loading data from Kubernetes cluster

### ISSUE THREAD

**Issue by creubank** [arangodb/arangodb#7813]
## My Environment

* __ArangoDB Version__:        3.4.0
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               Standalone
* __Infrastructure__:               Google Cloud
* __Operating System__:        Ubuntu 18.04.1 LTS
* __Used Package__:              Ubuntu

## Problem
We are running into an issue when loading data from a large number (500) of Kubernetes workers to a single non-clustered ArangoDB instance.  We are reading data from arango, processing that data, and writing back out.  

Typically, out of 10,000,000 connections that are made during the processing phase, about five of them fail with one of two errors (as reported by the Kubernetes client):

```ConnectionError(err, request=request) requests.exceptions.ConnectionError: ('Connection aborted.', OSError(0, 'Error'))```

and

```Traceback (most recent call last): File "inflate_driver_graph.py", line 172, in <module> main(args) File "inflate_driver_graph.py", line 118, in main driver_node_count = future.result() File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 425, in result return self.__get_result() File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result raise self._exception File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "/code/driver_graph/inflation.py", line 86, in inflate_nodes result = idg_node_collection.import_bulk(dg_node_queue) File "/usr/local/lib/python3.7/site-packages/arango/collection.py", line 2358, in import_bulk return self._execute(request, response_handler) File "/usr/local/lib/python3.7/site-packages/arango/api.py", line 58, in _execute return self._executor.execute(request, response_handler) File "/usr/local/lib/python3.7/site-packages/arango/executor.py", line 80, in execute response = self._conn.send_request(request) File "/usr/local/lib/python3.7/site-packages/arango/connection.py", line 71, in send_request auth=self._auth, File "/code/driver_graph/database_clients.py", line 49, in send_request verify=True File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request resp = self.send(prep, **send_kwargs) File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send r = adapter.send(request, **kwargs) File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 498, in send raise ConnectionError(err, request=request) requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))```

We suspect this a problem with the large number of connections being made to the ArangoDB server in a short period of time---more than the OS can handle.  (Furthermore, the first error looks like a problem with client resources and the second looks like a problem with server resources.)  This is a similar issue as https://github.com/arangodb/arangodb/issues/7785

The arangodb server does not show any errors, even logging at trace level, which make me think we have hit OS limits in the number and speed of connections.  We have tried to optimize by modifying kernel network parameters on the client (`net.ipv4.ip_local_port_range`, `net.ipv4.tcp_fin_timeout`, `net.ipv4.tcp_tw_reuse`) and on the server (`sysctl.core.somaxconn`, `txqueuelen`, `net.core.netdev_max_backlog` and `net.ipv4.tcp_max_syn_backlog`) but the issue still persists.

Looking for ideas from people who have gotten around this problem.  Any suggestions on best practices?  We do a lot of processing on each node of a 3m node/10m edge graph hence the large number of Kubernetes workers.  But these numbers will only increase in the future.

**Comment by dothebart** [comment]
shouldn't you be using persistent connections? Open/close all the time adds unneeded stress and penalty to the whole process?

**Comment by creubank** [comment]
Thank you for the reply.  Yes, we are in fact using persistent connections now. However, we discovered today that if we use a single thread per worker for the connection, we do not run into this problem, at least with the volumes we are dealing with today.

So, problem solved for now.
