### ISSUE TITLE
Index scan with in-memory sort should exit early in combination with LIMIT clause

### ISSUE THREAD

**Issue by Yogu** [arangodb/arangodb#7824]
## My Environment

* __ArangoDB Version__:        3.4
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Infrastructure__:               local
* __Operating System__:        Windows 10

## Component, Query & Data

__Affected feature__: Optimizer / execution

__AQL query (if applicable)__:

```aql
for m in businessMessages sort m.updatedAt, m._key limit 10 return m.updatedAt
```

__AQL explain (if applicable)__:

```
Query String:
 //for m in businessMessages sort m.createdAt, m._key limit 10 return m.createdAt
 for m in businessMessages sort m.updatedAt, m._key limit 10 return m.updatedAt

Execution plan:
 Id   NodeType          Calls   Items   Runtime [s]   Comment
  1   SingletonNode         1       1       0.00000   * ROOT
  9   IndexNode            26   25467       0.26892     - FOR m IN businessMessages   /* persistent index scan, projections: `_key`, `updatedAt` */
  3   CalculationNode      26   25467       0.01446       - LET #1 = m.`updatedAt`   /* attribute expression */   /* collections used: m : businessMessages */
  4   CalculationNode      26   25467       0.00856       - LET #3 = m.`_key`   /* attribute expression */   /* collections used: m : businessMessages */
  5   SortNode              1      10       0.07443       - SORT #1 ASC, #3 ASC
  6   LimitNode             1      10       0.00000       - LIMIT 0, 10
  8   ReturnNode            1      10       0.00000       - RETURN #1

Indexes used:
 By   Type         Collection         Unique   Sparse   Selectivity   Fields            Ranges
  9   persistent   businessMessages   false    false        99.81 %   [ `updatedAt` ]   *

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   remove-redundant-calculations
  3   remove-unnecessary-calculations
  4   move-calculations-up-2
  5   use-indexes
  6   reduce-extraction-to-projection

Query Statistics:
 Writes Exec   Writes Ign   Scan Full   Scan Index   Filtered   Exec Time [s]
           0            0           0        25467          0         0.37259

Query Profile:
 Query Stage           Duration [s]
 initializing               0.00001
 parsing                    0.00009
 optimizing ast             0.00001
 loading collections        0.00001
 instantiating plan         0.00005
 optimizing plan            0.00029
 executing                  0.36645
 finalizing                 0.00567
```

__Dataset__:

25 000 documents in "businessMessages" which are rather large (contain a long text field) and have a mostly unique "updatedAt" field

## Steps to reproduce

__Problem__:

The query takes much longer than it would if the index would cover the whole sort criteria (i.e., if it was on `updatedAt,_key`). From the *explain* result it looks like the whole collection is read and sorted.

__Expected result__:

As the result is limited to 10 items, a skiplist scan should be very fast for this query - it should look at the first 10 elements, maybe switch out one or two of them because they might have an identical value for `updatedAt`, but then see that the next item in the index already has a larger `updatedAt` value than any of the previously encountered items and conclude that the result can't possibly change when more documents are read and sorted.

I guess you could argue "just add the field to the index", but in some applications you can't possibly cover all use cases with indices and the performance jump from sub-milliseconds to several seconds or even minutes for a large collection is rather unexpected.

**Comment by maxkernbach** [comment]
Hi @Yogu,

I am closing this issue to continue further discussion on Jira.

Thanks
