### ISSUE TITLE
Report peak query memory usage

### ISSUE THREAD

**Issue by Yogu** [arangodb/arangodb#7826]
## My Environment

* __ArangoDB Version__:        3.4
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Infrastructure__:               local
* __Operating System__:        Windows 10

## Component, Query & Data

__Affected feature__: API (javascript and HTTP)

## Description

The option `query.memoryLimit` is really helpful to guard against accidental queries that are very memory consuming and could otherwise OOM-kill the whole server. This especially can happen with large collections and a UI that allows to arbitrarily filter and sort these documents.

However, it's hard to judge what would be an appropriate value for this option without knowing the actual memory usage of different queries.

Using external tools to measure memory usage is not a good solution because one query that executes relatively quickly is not really visible in a graph. Another option would be to bisect the memory usage by executing it many times with different limits, but that's also pretty cumbersome.

I'd love a report `peakMemoryUsage`, e.g. in the `query statistics` that are reported by `explain`. I think it should be fairly simple to implement in the `ResourceMonitor`. I'd love to contribute this but I have no experience in C++ and it would probably take quite a while for me to get everything running.

**Comment by Simran-B** [comment]
@graetzer Could the query profiling be extended for this purpose?

**Comment by graetzer** [comment]
sure I guess

**Comment by baslr** [comment]
This feature was in the branch feature/aql-max-mem-usage a while ago.

**Comment by jsteemann** [comment]
@baslr: Hi! It looks like the branch is not available anymore, at least I can't find it in our Github repository. Do you happen to have a local copy of the branch?

**Comment by dothebart** [comment]
I've got a copy containing it. want it?
```
commit cd56f0025d8016853d4285ff6fda9549b16437c3 (HEAD -> feature/aql-max-mem-usage, origin/feature/aql-max-mem-usage)
Merge: 497bbd2d95 edaeeaff6a
Author: baslr <manuel@arangodb.com>
Date:   Thu Mar 8 01:02:36 2018 +0100

    resolve merge conflict
```

**Comment by jsteemann** [comment]
@dothebart : yes, thanks.
Just the diff to base branch at that point of time should be enough.

**Comment by jsteemann** [comment]
Incorporated via https://github.com/arangodb/arangodb/pull/7952

**Comment by maxkernbach** [comment]
Hi @Yogu,

I am closing this issue to continue further discussion on Jira.

Thanks
