### ISSUE TITLE
my input program hang on arangodb cluster

### ISSUE THREAD

**Issue by zeroluojin** [arangodb/arangodb#7861]
## My Environment

* __ArangoDB Version__:        <3.3.19>
* __Storage Engine__:             RocksDB -->
* __Deployment Mode__:        | Cluster |
* __Deployment Strategy__:   
* __Infrastructure__:               <own -->
* __Operating System__:        <centos 7-->

__Replication Factor & Number of Shards (Cluster only)__:
1 Replication Facto & 3 of shards (3 dbservers
![11122](https://user-images.githubusercontent.com/43881415/50517948-e8286880-0aed-11e9-9c93-45a294d578ed.jpg)
)

__Problem__:
I have 3 nodes (3 dbserver) cluster and plan to insert 2 billion edges to edge collection. but when the cluster has 800 million edges. the program is freezing. then i look into the  one dbserver's log and saw the a amount of error about [85744] ERROR CollectionNameResolver: was not able to resolve id 1010055.

**Comment by maxkernbach** [comment]
Hi @zeroluojin,

I have a few questions:

1. Can you share more details of your program or ideally the program itself?
2. Are you restoring the edges of an existing data set or generating them?
3. Are you dropping collections while your program is running?
4. Can you share a sample of your edge collection (e.g. 5 edges)?

**Comment by dothebart** [comment]
Hi, 
ArangoDB 3.3 is EOLed meanwhile. Please upgrade to [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/).
Closing this as out of date.
