### ISSUE TITLE
Is there an API to monitor data changement in ArangoJS, like LIVE QUERY in OrientJS/OrientDB?

### ISSUE THREAD

**Issue by angkor-wat** [arangodb/arangodb#7866]
We are comparing between ArangoDB and OrientDB for a new project.

For our users, notification(of task and data modification) is important. So I like the LIVE QUERY of OrientDB. What is the solution in ArangoDB?

**Comment by dothebart** [comment]
Closing as a duplicate of https://github.com/arangodb/arangodb/issues/602
