### ISSUE TITLE
Remote end closed connection without response

### ISSUE THREAD

**Issue by Himan000** [arangodb/arangodb#7882]
## My Environment

* __ArangoDB Version__:        v0.13.10, build 38953b0 (V3.4.0)
* __Storage Engine__:             RocksDB 
* __Deployment Mode__:       Cluster(3 nodes)
* __Deployment Strategy__:   Manual Start
* __Configuration__:               default setting
* __Infrastructure__:               own
* __Operating System__:        CentOS 7
* __Total RAM in your machine__:        3 nodes, 16G RAM each
* __Disks in use__:        HDD
* __Used Package__:              RedHat .rpm

## Component, Query & Data

__Affected feature__:
aql query by python-arango tool with batch size and cursor

__AQL query (if applicable)__:
FOR doc IN experience RETURN doc

__AQL explain (if applicable)__:
Query String:
 for doc in experience return doc

Execution plan:
 Id   NodeType                  Site      Est.   Comment
  1   SingletonNode             DBS          1   * ROOT
  2   EnumerateCollectionNode   DBS   19460343     - FOR doc IN experience   /* full collection scan, 9 shard(s) */
  6   RemoteNode                COOR  19460343       - REMOTE
  7   GatherNode                COOR  19460343       - GATHER 
  3   ReturnNode                COOR  19460343       - RETURN doc

Indexes used:
 none

Optimization rules applied:
 Id   RuleName
  1   scatter-in-cluster
  2   remove-unnecessary-remote-scatter

__Dataset__:
N/A

__Size of your Dataset on disk__:
Over 19 million documents in a collection 

__Replication Factor & Number of Shards (Cluster only)__:
Replication Factor:1
Number of Shards:9

## Steps to reproduce
run below python code with python-arango:
aql = "FOR doc IN section RETURN doc"
batch_size = 10000
cursor = db.aql.execute(aql, batch_size=batch_size)

__Problem__:
exception detail:
"C:\Program Files\Anaconda3\python.exe" D:/project/python/project_name/project_name_batch_parser/arangodb.py
Traceback (most recent call last):
File "C:\Program Files\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
chunked=chunked)
File "C:\Program Files\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
six.raise_from(e, None)
File "", line 2, in raise_from
File "C:\Program Files\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
httplib_response = conn.getresponse()
File "C:\Program Files\Anaconda3\lib\http\client.py", line 1198, in getresponse
response.begin()
File "C:\Program Files\Anaconda3\lib\http\client.py", line 297, in begin
version, status, reason = self._read_status()
File "C:\Program Files\Anaconda3\lib\http\client.py", line 266, in _read_status
raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Program Files\Anaconda3\lib\site-packages\requests\adapters.py", line 440, in send
timeout=timeout
File "C:\Program Files\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
_stacktrace=sys.exc_info()[2])
File "C:\Program Files\Anaconda3\lib\site-packages\urllib3\util\retry.py", line 357, in increment
raise six.reraise(type(error), error, _stacktrace)
File "C:\Program Files\Anaconda3\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
raise value.with_traceback(tb)
File "C:\Program Files\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
chunked=chunked)
File "C:\Program Files\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
six.raise_from(e, None)
File "", line 2, in raise_from
File "C:\Program Files\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
httplib_response = conn.getresponse()
File "C:\Program Files\Anaconda3\lib\http\client.py", line 1198, in getresponse
response.begin()
File "C:\Program Files\Anaconda3\lib\http\client.py", line 297, in begin
version, status, reason = self._read_status()
File "C:\Program Files\Anaconda3\lib\http\client.py", line 266, in _read_status
raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "D:/project/python/project_name/project_name_batch_parser/arangodb.py", line 246, in 
merge_section_2_candidate()
File "D:/project/python/project_name/project_name_batch_parser/arangodb.py", line 191, in merge_section_2_candidate
cursor = db.aql.execute(aql, batch_size=batch_size)
File "C:\Program Files\Anaconda3\lib\site-packages\arango\aql.py", line 304, in execute
return self._execute(request, response_handler)
File "C:\Program Files\Anaconda3\lib\site-packages\arango\api.py", line 58, in _execute
return self._executor.execute(request, response_handler)
File "C:\Program Files\Anaconda3\lib\site-packages\arango\executor.py", line 80, in execute
response = self._conn.send_request(request)
File "C:\Program Files\Anaconda3\lib\site-packages\arango\connection.py", line 71, in send_request
auth=self._auth,
File "C:\Program Files\Anaconda3\lib\site-packages\arango\http.py", line 83, in send_request
auth=auth,
File "C:\Program Files\Anaconda3\lib\site-packages\requests\sessions.py", line 508, in request
resp = self.send(prep, **send_kwargs)
File "C:\Program Files\Anaconda3\lib\site-packages\requests\sessions.py", line 618, in send
r = adapter.send(request, **kwargs)
File "C:\Program Files\Anaconda3\lib\site-packages\requests\adapters.py", line 490, in send
raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

__Expected result__:
Using query with batch-size and cursor should breakdown the query and fetch a batch documents from dbserver instead the whole collection. 

I have asked this question in python-arango, but they said it seem dbserver size problem. Is there any configuration in server size to control it, or how could I iterate a collection which have huge amount documents/edges? After all, someone should have the requirement that adding a new attribute to every document in a collection. 

Even not use python-arango, use aql in web interface also throw the same exception. So, how to iterate a collection which have huge amount documents/edges? 

Thanks

**Comment by jsteemann** [comment]
@Himan000 : I expect that the overall result of this query is relatively big (19M+ documents of unknown size). What is happening when executing this query is that the coordinator will collect all data from the collection from the 9 shards and build up the total result in its local RAM. And only when the total result has been completely built up, it will start sending the data back to the python client in batches of 1000.
That has the following side-effects:
* the python-client may close the connection or time out before the final result has been built up on the coordinator
* the total result may be bigger than the available memory on the coordinator, leading to the query failing or the coordinator crashing
I can't tell without further diagnostics if any of the above applies to your situation, but I guess what would help here is to use a streaming cursor. Streaming cursors will not lead to the entire result being built up on the coordinator before sending out the result in batches. Instead, with a streaming cursor, partial results will be send out as soon as they are available. This is probably what is desired in your case anyway.
Streaming cursors have been introduced in ArangoDB 3.4, and I have checked if the python-arango driver already supports them.
According to https://github.com/joowani/python-arango/blob/master/arango/aql.py#L158 it looks like it does not yet support streaming cursors, but they should be straightforward to add to the driver.
I will open an issue in the driver's repository to track progress for this.

**Comment by jsteemann** [comment]
Ok, I saw there was already an issue in the python-arango driver repository, so I have added my findings and the request for adding support for streaming cursors there:
https://github.com/joowani/python-arango/issues/91#issuecomment-451409477

**Comment by Himan000** [comment]
Hi @jsteemann,
What you said 100% applies to my situation. Thank you for adding comment to python-arango [#91](https://github.com/joowani/python-arango/issues/91#issuecomment-451409477) which was created by me. I will continue pay attention to that item. 

Another question, if I iterate a collection(with huge amount documents)  and update some attribute with aql in web interface, _node can't find_ exception will occur. How to solve this problem? Is there any setting can be changed?

`for doc in section update doc with {"name":doc.company_name} in section`

**Comment by jsteemann** [comment]
@Himan000 : I am sorry, I am not aware of any `node can't find` exceptions in ArangoDB or its web UI.
I also search for this in the python-arango driver but also didn't see it there.

How exactly is that exception getting back to you? Is it shown in the browser somehow? I am a bit lost... Thanks.

**Comment by Himan000** [comment]
The exception is like this:
_Query: AQL: Error message received from shard '' on cluster node 'PRMR-ccacd667-2780-40b1-885a-cdd6d65ead32': Error message received from shard '' on cluster node 'CRDN-229bb8c3-ed59-4a82-ac56-4cf5b2d8ff6b': query ID not found (while executing)_

aql in web UI:
`for doc in experience update doc with {"name":doc.company_name} in experience`

**Comment by Himan000** [comment]
Hi @jsteemann ,
If I iterate a collection(with huge amount documents) and update some attribute with aql in web UI, exception will occur. How to solve this problem? Is there any setting can be changed?

`for doc in section update doc with {"name":doc.company_name} in section`

Exception detail:
_Query: AQL: backend unavailable, cluster node: 'PRMR-ccacd667-2780-40b1-885a-cdd6d65ead32', endpoint: 'tcp://172.17.191.66:8530', error: 'could not connect to server' (while executing)_ 

thanks

**Comment by dothebart** [comment]
As this problem has been solved meanwhile in the python-arango issue, I'm closing this as solved.

Please note that [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/)  is Available.
