### ISSUE TITLE
ArangoCursor<UserInfo> cursor;   cursor.getStats().getFullCount()  is null，cursor.count() is null

### ISSUE THREAD

**Issue by wqxcloud** [arangodb/arangodb#7889]
## My Environment

* __ArangoDB Version__:  3.4.0      
* __Storage Engine__:  RocksDB           
* __Deployment Mode__:  default     
* __Deployment Strategy__: default  
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:  CentOS 7.6.1810      
* __Used Package__:   Linux version 3.10.0-693.2.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) ) #1 SMP Tue Sep 12 22:26:13 UTC 2017
[root@xu arangodb3]# lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.6.1810 (Core) 
Release:	7.6.1810
Codename:	Core
           

## Component, Query & Data

__Affected feature__:

__AQL query (if applicable)__:
ArangoCursor<UserInfo> cursor = operations.query(“For xxxx”, bindVars, new AqlQueryOptions(), UserInfo.class);
		/

__AQL explain (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. 
2. 
3. 

__Problem__:

cursor .count() is null，cursor.getStats().getFullCount() is null
__Expected result__:

**Comment by Simran-B** [comment]
Please provide more information about the problem and your environment. It is completely unclear what driver you refer to, what query you try to run against what dataset, what your operating system and ArangoDB version is. We can't help without this basic information.

**Comment by wqxcloud** [comment]
> Please provide more information about the problem and your environment. It is completely unclear what driver you refer to, what query you try to run against what dataset, what your operating system and ArangoDB version is. We can't help without this basic information.

i have update the information,please help me look it

**Comment by Simran-B** [comment]
It's still unclear what driver you use. Is it the official Java driver? In what version?

Documentation can be found here:
https://docs.arangodb.com/3.4/Drivers/Java/Reference/Database/Queries.html

`For xxxx` is not a valid AQL query. It should be something like `FOR doc IN collection RETURN doc` for instance.

**Comment by maxkernbach** [comment]
Hi @wqxcloud,

could you please reply to the latest comment?
We would like to investigate your issue, but require more details.

**Comment by maxkernbach** [comment]
@wqxcloud 

Since we have not heard back from you in a while, I am closing this issue for now.
In case the problem persists, please provide further details and we would be glad to investigate it.
