### ISSUE TITLE
Optimize memory usage of a sort when a limit clause is present

### ISSUE THREAD

**Issue by Yogu** [arangodb/arangodb#7896]
## My Environment

* __ArangoDB Version__:        3.4
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Infrastructure__:               local
* __Operating System__:        Windows 10

## Component, Query & Data

__Affected feature__: AQL query optimizer

__AQL query (if applicable)__:

```aql
for m in businessMessages
filter m.tray == "IN"
sort m.updatedAt 
limit 10
return m
```

__Dataset__:

25 000 documents in "businessMessages" which are rather large (contain a long text field)

## Steps to reproduce

__Problem__:

The given query takes a lot of memory to execute because it loads 25 000 full documents in memory, sorts them, and then only returns 10.

__Expected result__:

The memory usage should not depend on the total number of documents as no more than 10 documents need to be held in memory at any time.

## Suggestion

The information about the `limit` clause should be propagated up to the `sort` node so that it can use a size-constrained heap data structure for the sort. This would improve memory usage to constant complexity with regards to the total number of documents, and also optimize the time complexity to O(n) instead of O(n log n) because maintaining a limited-size heap is constant while a sort is in O(n log n).

@mpoeter [explained in more detail here](https://github.com/arangodb/arangodb/issues/7821#issuecomment-449578565):

> @dothebart I agree with almost everything you wrote, but I do think that this would be a very useful optimization that would not only reduce memory requirements but also improve performance - at least in cases where the limit is significantly smaller than the collection size (which I would consider a very frequent case).
> 
> Let's assume we have a collection with _n_ documents and a LIMIT _k_. Of course you still have to perform a full scan and load+parse all _n_ documents, but you only have to perform a partial sort and keep _k_ documents. This could be efficiently done using a heap with a fixed size _k_. An update of the heap has complexity _O(_ log _k)_, so the total complexity would be _O(n_ log _k)_, while a sort of all documents would have complexity _O(n_ log _n)_.
> 
> Edit: oh, and of course _O(n_ log _k)_ is the worst case performance. Sorting all documents can never be better than _O(n_ log _n)_, but I would expect the average case performance of the partial sort to be much better in most cases since a document can be immediately discarded if it is greater than `heap.max`, i.e., processing such a document takes _O(1)_ instead of _O(_ log _k)_.
> 
> Maybe I will take a stab at this... 🙂

See also #7824 - this optimization here would allow a sort operation to stop early if it is based on a skiplist index scan that partially covers the sort criteria.

**Comment by sleto-it** [comment]
This is done in 3.5 - this is the documented entry: https://docs.arangodb.com/devel/Manual/ReleaseNotes/NewFeatures35.html#sort-limit-optimization

Closing.
