### ISSUE TITLE
null bind values change to empty string

### ISSUE THREAD

**Issue by r-bar** [arangodb/arangodb#7900]
## My Environment

* __ArangoDB Version__:        3.3.20 docker image
* __Storage Engine__:             RocksDb
* __Deployment Mode__:        Single Server
* __Deployment Strategy__:   Manual Start in Docker
* __Configuration__:               ARANGO_NO_AUTH
* __Infrastructure__:               own
* __Operating System__:        Ubuntu 18.04
* __Total RAM in your machine__:        16gb
* __Disks in use__:        SSD
* __Used Package__:              Docker - official Docker library 

## Component, Query & Data

__Affected feature__:
AQL query using web interface

__AQL query (if applicable)__:
RETURN {foo: @foo, bar: @bar}

__AQL explain (if applicable)__:
N/A

__Dataset__:
N/A

__Size of your Dataset on disk__:
0B

__Replication Factor & Number of Shards (Cluster only)__:
0

## Steps to reproduce

1. Create a query in the arango web query UI with at least 1 bind variable
2. Set the bind variable value to `null` in either the table or json view of the bind variables
3. Add or Remove a bind variable name in the query

__Problem__:
The any bind value set to `null` will change to an empty string when a bind variable name is added or removed from the query window.

__Expected result__:
The bind values remain the same with the exception of the added / removed bind variable name.

__Related__:
#4582
#4986

**Comment by ObiWahn** [comment]
The bug occurs on devel as well. When toggling between json and table view in the UI a value of `null` is converted to an `empty string`.
