### ISSUE TITLE
function "limit(offset, length)" may result a dead loop

### ISSUE THREAD

**Issue by hellomanjack** [arangodb/arangodb#7901]
## My Environment

* __ArangoDB Version__:       3.3.19
* __Storage Engine__:             rocksdb
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:    Manual Start
* __Total RAM in your machine__:        64GB

__Affected feature__:
AQL query using web interface| with driver

[tags.txt](https://github.com/arangodb/arangodb/files/2735224/tags.txt)
[tagModelRels.txt](https://github.com/arangodb/arangodb/files/2735225/tagModelRels.txt)

## Steps to reproduce

1. import the two dataset to collection tags and collectoin tagModelRels
2.  run the aql:
```
for rel in tagModelRels
 for t in tags filter t._key==rel.tagKey
 sort t._key
 limit 20,20
 return merge(t, 
 {"gcomponents":{"modelDB":rel.modelDB,"modelKey":rel.modelKey,"componentKey":rel.componentKey}})  
```
__Problem__:
Some tasks run forever and cannot by killed 
> var queries = require("org/arangodb/aql/queries");
> queries.kill("xxx"); 
But some are fine.
![image](https://user-images.githubusercontent.com/25783698/50810423-8b764a80-1344-11e9-8b3e-453562505130.png)
![image](https://user-images.githubusercontent.com/25783698/50810473-c4aeba80-1344-11e9-8f18-8727c066e40a.png)

Problem thread "Scheduler" is as followes:
![image](https://user-images.githubusercontent.com/25783698/50810480-d2fcd680-1344-11e9-8475-2e4502c704fa.png)

**Comment by maxkernbach** [comment]
Hi @hellomanjack,

I tried to reproduce this issue on Ubuntu 18.04 (3.3.19 rocksdb single server) with no success so far. Running the listed AQL query worked every time after importing the collections with `arangoimp`, no query got stuck. 

Which operating system are you using, is this error reproducible on a fresh environment?

**Comment by hellomanjack** [comment]
@maxkernbach I use Centos7.4 and 7.2。 I use web front end to upload the two jsons。
![image](https://user-images.githubusercontent.com/25783698/50942230-dddd7580-14c2-11e9-84bc-008246f6889a.png)

**Comment by dothebart** [comment]
With ArangoDB 3.3 being EOLed and [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) being available I'm closing this as out of date.
