### ISSUE TITLE
path.resolve: process not defined

### ISSUE THREAD

**Issue by pluma** [arangodb/arangodb#791]
Apparently process is no longer added to new contexts (including arangosh). `path.resolve` seems to fail for relative paths if `process` is not set.

I'm aware the entire filesystem access is mostly an internal API not meant for direct use, but if `path.resolve` is not meant to be supported in Foxx, it should probably be moved out of `path`.

**Comment by jsteemann** [comment]
`process.env` is also available from 2.6 on. The following command will thus work: `require('path').resolve('.');`.
