### ISSUE TITLE
Slow performance of ArangoDB while traversing a graph of 50+ depth and 200k+ nodes

### ISSUE THREAD

**Issue by rupendra-sharma** [arangodb/arangodb#7913]
## My Environment

* __ArangoDB Version__:        3.4.1
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Cluster 
* __Deployment Strategy__:   ArangoDB Starter
* __Configuration__:               3 DB servers, 3 Coordinators 3 DB server
* __Infrastructure__:               own
* __Operating System__:        MacOS 10.13.6
* __Total RAM in your machine__:    8 GB DDR3    
* __Disks in use__:        Macintosh HD
* __Used Package__:              N/A

## Component, Query & Data

__Affected feature__:
AQL query using web interface 

__Size of your Dataset on disk__:
200mb

__Replication Factor & Number of Shards (Cluster only)__:
6 shards, 1 replication

__Problem__:
I have a graph database on ArangoDB which have a node depth of around 100 levels and around 205k nodes for some users. For normal uses the AQL used to traverse the graph works well. But there are some scenarios on which the graph traversal is taking too much time, which are:

Calculating the maximum depth for some user
Calculating weight for a root node which have a node depth around 50+ and child node 200k+. Here weight is calculated by summing the weight of each child node.
Fetching all the nodes on a specific level for some node.

Results are attached with the ticket.

Explain has been already executed on these queries, but no specific suggestion was provided related to indexes. Default primary and edge key index are used
__Expected result__:
The time to traverse the graph should less then 10s.
[ArangoPerformance.pdf](https://github.com/arangodb/arangodb/files/2739244/ArangoPerformance.pdf)

**Comment by rupendra-sharma** [comment]
@vinaypyati any updates on the issue?

**Comment by graetzer** [comment]
Increasing the depth of the traversal can increase the number of paths exponentially. A depth of >50 leads to a very high number of paths ArangoDB then needs to compute.

It would probably be a good idea to reevaluate your data model, use more filters or use the option `{uniqueVertices: true, bfs: true}` to reduce the number of paths more aggressively.

**Comment by rupendra-sharma** [comment]
@graetzer thanks for your suggestion. but my logic need to read the last node of the tree to calculate the weight and ofcourse the levels. Just wondering setting bfs=true, will it be effective for this case?
On the other hand, i am thinking for a solution in which 

-  I will add an active-active cluster for ArangoDB with say 6 nodes with 6 replications but no sharding(sharding is not helpful in graph I beleive),

-  pre-calculate the 1st level for each node and place it on a cache. 

- And later when the request comes to read all its child-nodes, I will execute spark batch query to read 6 sub-trees by picking the 1st level from cache using 6 active ArangDB node and merge the result. 

Do you feel it will work?

**Comment by graetzer** [comment]
maybe, my advice was very general. Anyway ArangoDB's query engine is designed for OLTP  workloads, if you do batch processing (i.e. OLAP workloads) a tool like spark might be more suitable for your use-case

**Comment by iamyinweijianGH** [comment]
Yes, I also have this situation, very slow. Simply query of 20K+ edge node, it  spend 20s more, we need some help from here

**Comment by dothebart** [comment]
With ArangoDB 3.4 being EOLed and [ ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) I'm closing this as out of date.
