### ISSUE TITLE
3.4.0 / 3.4.1 does not start from an upgrade or clean state in Azure Kubernetes

### ISSUE THREAD

**Issue by rocketraman** [arangodb/arangodb#7914]
## My Environment

* __ArangoDB Version__:        3.4.1
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   Kubernetes
* __Configuration__:               Nothing unusual, just trying to start the first agent (first tried upgrade, then a clean start)
* __Infrastructure__:               Azure
* __Operating System__:       Linux Ubuntu 16.04.1 on Kubernetes 1.12.4
* __Total RAM in your machine__:        32 Gb, but running in containers with mem limit = 4 Gib
* __Disks in use__:       SSD
* __Used Package__:              Docker - official Docker library

## Component, Query & Data

__Affected feature__:
Server

__AQL query (if applicable)__:
N/A

__AQL explain (if applicable)__:
N/A

__Dataset__:
N/A

__Size of your Dataset on disk__:
N/A

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. Create a new StatefulSet with agency configuration sing image 3.4.1 in Azure Kubernetes

__Problem__:

The container starts, arangodb initializes the database, but then hangs. Logs (with level trace):

```
choosing RocksDB storage engine
Initializing database...Hang on...
Database initialized...Starting System...
{config} using user supplied config file '/tmp/arangod.conf'
executing upgrade check: not disabling server features
```

The exact same configuration with image `arangodb/arangodb:3.3.21` works with no issue.

Here is the configuration:

```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: arangodb-agent
  namespace: default
spec:
  serviceName: "arangodb-agents"
  replicas: 3
  template:
    metadata:
      labels:
        app: arangodb
        tier: backend
        role: agent
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - "arangodb"
                  - key: "role"
                    operator: In
                    values:
                    - "agent"
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: arangodb
        #image: arangodb/arangodb:3.3.21
        image: arangodb/arangodb:3.4.1
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
        env:
        - name: IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ARANGO_NO_AUTH
          value: "1"
        - name: ARANGO_STORAGE_ENGINE
          value: "rocksdb"
        ports:
        - containerPort: 8529
          name: arangodb
        volumeMounts:
        - mountPath: /var/lib/arangodb3
          name: arangodb-agency-data
        args:
        - --server.storage-engine
        - "rocksdb"
        # For use when upgrading
        #- --database.auto-upgrade=true
        # Increase log level at startup, if necessary
        #- --log.level
        #- debug
        - --server.endpoint
        - tcp://0.0.0.0:8529
        - --agency.activate
        - "true"
        - --agency.size
        - "3"
        - --agency.supervision
        - "true"
        - --agency.my-address
        - tcp://$(IP):8529
        - --agency.endpoint
        - tcp://arangodb-agent-0.arangodb-agents:8529
        readinessProbe:
          httpGet:
            path: /_db/_system/_admin/statistics
            port: 8529
            scheme: HTTP
          failureThreshold: 5
  volumeClaimTemplates:
  - metadata:
      name: arangodb-agency-data
      annotations:
        volume.beta.kubernetes.io/storage-class: managed-premium
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
```

__Expected result__:

The server should start.

**Comment by rocketraman** [comment]
Oh #%&$, it looks like the server had started up just fine -- it seems the default `log.output` value was changed in 3.4 (perhaps in the default Docker config?), and the startup messages were simply not printing to standard output as they did in 3.3. Damn, so much time wasted for so little reason...

**Comment by dothebart** [comment]
Hi, 
you were looking for the `Hello` greeting to appear, and this didn't happen?

**Comment by rocketraman** [comment]
> you were looking for the `Hello` greeting to appear, and this didn't happen?

Yes, I believe it is because in 3.3.x `/etc/arangodb/arangodb.conf` contains `log.output=-` by default. In 3.4.x it has a reference to a log file.

I think the Docker image though should overwrite this default setting with `-` to emulate the 3.3.x default behavior, as this would be the normal expectation inside a container, because the data has to be written to standard output in order to be captured in the docker container logs.

I'll file a bug @ https://github.com/arangodb/arangodb-docker.
