### ISSUE TITLE
Regression on ISO8601 string compatibility in AQL

### ISSUE THREAD

**Issue by ThomasWeiss** [arangodb/arangodb#7933]
Up to v3.3.21, this AQL query works: `return date_timestamp('2018-11-27T10:57:52.2418407Z')`.

On v3.4.0, it generates the following warning: `[1572], 'in function 'DATE_TIMESTAMP()': invalid date value'` and returns `null`. We have to truncate the part after the dot to 3 digits only (`'2018-11-27T10:57:52.241Z'`) to make it work.

This seems to affect [all functions that manipulate dates](https://docs.arangodb.com/3.4/AQL/Functions/Date.html).

**Comment by jsteemann** [comment]
@ThomasWeiss : I am able to reproduce this.
The regex for parsing input date values is
```
std::regex const iso8601Regex(
    "(\\+|\\-)?\\d+(\\-\\d{1,2}(\\-\\d{1,2})?)?"  // YY[YY]-MM-DD
    "("
    "("
    // Time is optional
    "(\\ |T)"                     // T or blank separates date and time
    "\\d\\d\\:\\d\\d"             // time: hh:mm
    "(\\:\\d\\d(\\.\\d{1,3})?)?"  // Optional: :ss.mmms
    "("
    "z|Z|"  // trailing Z or start of timezone
    "(\\+|\\-)"
    "\\d\\d\\:\\d\\d"  // timezone hh:mm
    ")?"
    ")|"
    "(z|Z)"  // Z
    ")?");
```
so it is definitely limited to up to 3 digits for milliseconds at the moment.

**Comment by ThomasWeiss** [comment]
Thanks @jsteemann 
For us it is a regression as it means that the data we currently have in the database won't be compatible with 3.4; will there be a fix?

**Comment by jsteemann** [comment]
@ThomasWeiss : currently looking into it...
Adjusting the regexes is a no-brainer, but I have to see what happens in the underlying date library.

**Comment by jsteemann** [comment]
Fixed via https://github.com/arangodb/arangodb/pull/7934

**Comment by maxkernbach** [comment]
Hi @ThomasWeiss,

v3.4.2, which includes a fix for this issue, has been released.
It can be found in the [download section](https://www.arangodb.com/download-major/).
