### ISSUE TITLE
Arango replication failing intermittently 

### ISSUE THREAD

**Issue by ImSajeed** [arangodb/arangodb#7945]
ArangoDB Version: 3.4
Storage Engine : RocksDB
Deployment Mode: Single Server
Deployment Strategy : Manual Start
Infrastructure: AWS
Operating System: Ubuntu 16.04
Total RAM in your machine: 32Gb

we have master-slave async replication set up. for most of the duration replication works seamlessly however at certain point it fails with write lock out on few collections.
At the same moment we observe disk reads increase drastically.

```json
{
  "state" : {
    "running" : true,
    "phase" : "running",
    "lastAppliedContinuousTick" : "1051219531",
    "lastProcessedContinuousTick" : "1051219531",
    "lastAvailableContinuousTick" : "1060781346",
    "safeResumeTick" : "1051073046",
    "ticksBehind" : 9561815,
    "progress" : {
      "time" : "2019-01-16T09:35:10Z",
      "message" : "fetching master log from tick 1051267589, last scanned tick 1051222811, first regular tick 1043682305, barrier: 580096620, open transactions: 1, chunk size 2097152",
      "failedConnects" : 0
    },
    "totalRequests" : 2559,
    "totalFailedConnects" : 0,
    "totalEvents" : 1080758,
    "totalResyncs" : 0,
    "totalOperationsExcluded" : 0,
    "lastError" : {
      "errorNum" : 0
    },
    "time" : "2019-01-16T09:57:10Z"
  },
  "server" : {
    "version" : "3.4.0",
    "serverId" : "46412000519761"
  },
  "endpoint" : "tcp://xx.xx.x.x:8530",
  "database" : "testdb"
}

```

**Comment by ImSajeed** [comment]
@jsteemann could you please help on this issue

**Comment by AntoineAA** [comment]
related to #7410?

**Comment by Puneeth-Kadamba** [comment]
No This is due to replication failure in between with write locks.

**Comment by maxkernbach** [comment]
Hi @ImSajeed,

sorry for the late reply, are you still facing this issue?
Could you please share the logs (arangod.log) of your master and slave?
Which exact version are you using, is it 3.4.0?

**Comment by OmarAyo** [comment]
Hi @ImSajeed 

Since we have not heard back from you in a while, I am closing this issue for now.
If needed, please reply and we will reopen.

Best,
