### ISSUE TITLE
How to make the best of cpu and memory?

### ISSUE THREAD

**Issue by Himan000** [arangodb/arangodb#7951]
**My Environment**
ArangoDB Version: v0.13.10, build 38953b0 (V3.4.0)
Storage Engine: RocksDB
Deployment Mode: Cluster(3 nodes)
Deployment Strategy: Manual Start
Configuration: default setting
Infrastructure: own
Operating System: CentOS 7
Total RAM in your machine: 3 nodes, 16G RAM each
Disks in use: HDD
Used Package: RedHat .rpm

When runing update documents job, no matter 400 connections or 4000 connenctions, only about 1000 requests can be done per second. Look into the server machine, only 1 or 2 cpu cores and 25% memery were used(sometimes a core will over 100%). How to change configuration to make the best of cpu cores and memery?

**Comment by ObiWahn** [comment]
Is it possible that your operations are IO-bound (disk too slow)? Do you have waitForSync enabled?

**Comment by Himan000** [comment]
@ObiWahn 
        Thanks for reply. It's local area network access. The disk is ssd. waitForSync is default false. Do you mean I should enable the waitForSync ?

**Comment by dothebart** [comment]
With ArangoDB 3.4 being EOLed and [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) I'm closing this as outdated.
in https://www.arangodb.com/docs/stable/tutorials-reduce-memory-footprint.html we explain the behaviour of the rocksdb storage engine, and how to measure performance. 
https://www.arangodb.com/2017/10/performance-analysis-pyarango-usage-scenarios/ demonstrates how to benchmark your system, and find its bottlenecks.
