### ISSUE TITLE
Python driver to be used for a system that makes highly concurrent requests to db #5372

### ISSUE THREAD

**Issue by kaylee000** [arangodb/arangodb#7973]
## My Environment running ArangoDB

* __ArangoDB Version__:        3.4.0
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Operating System__:        Ubuntu 16.04
* __Total RAM in your machine__:        8Gb

## This is a question
When I run the code on this website (https://www.arangodb.com/2017/10/performance-analysis-pyarango-usage-scenarios/), I found two problems,
1. CPU utilization has soared to 100% in a few minutes, and memory usage is as high as 100%.
2. The code of the transaction, the second query actually has no result.
I want to know, is this the author's original intention? Or is there anything wrong with my code?

## This is the code extracted from the site.

```py
transaction='''
    function(params) {
      var db = require('@arangodb').db;
      var startOne = Date.now();
      var q1 = db._query(
        `FOR oneUser IN user
            FILTER user._key == @userid
            UPDATE {
              _key: oneUser._key,
              lastseen: @timestamp,
              counter: oneUser.counter + 1
            } IN user`,
         {
          userid: 'user_' + params.i,
          timestamp: params.timestamp
        });
      var startTwo = Date.now();
      var q2 = db._query(`FOR v, e IN 1..1 OUTBOUND @user userToGroups
                            FILTER e.counter == @i
                          UPDATE {
                             _key: v._key,
                             counter: v.counter + 1
                          } IN groups`,
                         {
                           user: 'user/user_' + params.i,
                           i: params.i % 10
                         });
      var startThree = Date.now();
      var q3 = db._query(`RETURN 1`);
      var end = Date.now();
      return {
        tq1: startTwo - startOne,
        tq2: startThree - startTwo,
        tq3: end - startThree,
        all: end - startOne
      };
    }
'''
```

Thanks,
keylee.

**Comment by Simran-B** [comment]
Related: https://github.com/arangodb/arangodb/issues/5372

**Comment by kaylee000** [comment]
Thanks！
