### ISSUE TITLE
Concurrent operations have excessive latency

### ISSUE THREAD

**Issue by ggendel** [arangodb/arangodb#8004]
## My Environment

* __ArangoDB Version__:        3.3.21
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server. Native and Docker
* __Deployment Strategy__:   Manual Start
* __Configuration__:               tcp endpoint
* __Infrastructure__:               own
* __Operating System__:        Opensuse Leap 42.3, Redhat and Centos
* __Total RAM in your machine__:        16GB
* __Disks in use__:        SSD
* __Used Package__:            SUSE or RedHat .rpm

## Component, Query & Data

__Affected feature__:
Foxx latency

__AQL query (if applicable)__:
WITH pmconfig,pmvariant,pmproject,pmsite,pmpath,pmvartype FOR o IN ['pmconfig/51971547'] FOR v,e,p IN 0..50 INBOUND o pm_child RETURN p.vertices

__Dataset__:
This will happen with a small dataset.  The request is to collect all nodes along an edge type and return their contents (via Foxx).

## Steps to reproduce

1.  Create a small dataset with a handful of nodes and edges (tree structure)
2. Launch bunch of concurrent requests via the Foxx interface to return information about objects in the path.  These requests can be the same or different.  For example we see this with the same request:
/usr/bin/time curl -sS -w "n%{http_code}n" "http://localhost:8529/_db/gdp/pmmodel/find?id=pmconfig/51971547&populate=."&
In our case this gets converted to the AQL statement:

WITH pmconfig,pmvariant,pmproject,pmsite,pmpath,pmvartype FOR o IN ['pmconfig/51971547'] FOR v,e,p IN 0..50 INBOUND o pm_child RETURN p.vertices

which returns the following:
{"success":true,"total":1,"dictionary":{"pmconfig/51971547":{"name":"c1","created-by":"gary","object":"config","_createdAt":"2019-01-16T16:16:29.070Z","_modifiedAt":"2019-01-16T16:16:29.148Z","id":"pmconfig/51971547"},"pmvartype/51971498":{"name":"test_doc","uri":"cm://localhost:8087/ngdp/br:/stancu_orion_a_84/v1/test_doc","location":"stancu_orion_a_84/v1/test_doc","created-by":"gary","object":"vartype","_createdAt":"2019-01-16T16:16:28.709Z","id":"pmvartype/51971498"},"pmvariant/51971473":{"name":"v1","created-by":"gary","object":"variant","_createdAt":"2019-01-16T16:16:27.100Z","id":"pmvariant/51971473"},"pmproject/51971450":{"uri-template":"cm://br:/{{a/b/c}}@ngdp@localhost:8087","name":"stancu_orion_a_84","created-by":"gary","object":"project","_createdAt":"2019-01-16T16:16:27.060Z","id":"pmproject/51971450"},"pmsite/51971430":{"name":"test","uri-template":"cm://{{connection}}/{{repo}}/br:/{{a/b/c}}","created-by":"gary","object":"site","_createdAt":"2019-01-16T16:16:26.982Z","id":"pmsite/51971430"}},"results":[{"id":"pmconfig/51971547","_child":{"id":"pmvartype/51971498","_child":{"id":"pmvariant/51971473","_child":{"id":"pmproject/51971450","_child":{"id":"pmsite/51971430"}}}}}]

__Problem__:
Sequential requests take ~2ms each. With concurrent requests, we normally see it < 14mS, but we get the occasional glitch with the request taking almost a full second.  This can happen with requests in a 10 concurrent burst.  For example:
200 OK, took 5 ms
200 OK, took 10 ms
200 OK, took 8 ms
200 OK, took 8 ms
200 OK, took 9 ms
200 OK, took 8 ms
200 OK, took 10 ms
200 OK, took 11 ms
200 OK, took 11 ms
200 OK, took 397 ms

I played with garbage collection tuning but that doesn't seem to be the source of the problem.

__Expected result__:
Concurrent requests maintain a consistent time to return results within the connection limit.  It's not clear how to debug this or what is the underlying problem.  I'm hoping that it's just a scheduling problem where an early request is prevented execution by subsequent requests.

**Comment by dothebart** [comment]
Hi, 
can you revalidate that this is a graph issue by directly invoking the AQL query via HTTP? 
The other test good to have would be to simply have a static `RETURN` statement that returns a list of documents of similar size.

**Comment by ggendel** [comment]
Hi,
How do I do I invoke the AQL directly?  I couldn't figure out the magic incantation to bypass my Foxx application interface.

Regards,
Gary

**Comment by ggendel** [comment]
More information...  I recorded the duration of the AQL call within the Foxx app and it's consistently 1mS.  This indicates to me that the problem is in the Foxx app where one request is being delayed significantly.  How do I debug performance issues in Foxx?

**Comment by dothebart** [comment]
Hi, 
You could i.e. use arangosh, with something along the lines and simply put a for loop around it. :

```
const time = require('internal').time;
for (let i = 0; i < 100; i ++) {
  starttime = time();
  db._query(AQL`FOR query with ${BINDVALUE }`)
  print (time() - starttime)
}
```

**Comment by dothebart** [comment]
You may want to add measurements, like I did for transactions in these performance blogpost series:
https://www.arangodb.com/2017/10/performance-analysis-pyarango-usage-scenarios/

However, if its the garbage collection that gets into your way, you're most probably out of luck - invoking the garbage collection manually at times where nothing else is going on using `require("internal").wait(0.1, true) ` could improve the situation.

**Comment by maxkernbach** [comment]
Hi @ggendel,

has dothebart's latest latest comment been helpful? Could you please provide an update on this issue?

Thanks

**Comment by ggendel** [comment]
As always, the advice I got was great.  Unfortunately, I've been working 
towards a deliverable so I haven't gotten back to digging into this 
problem.  I did re-write the API for the client application so Foxx uses 
less memory and cpu resources.  It now happens less often.

I hope to get back to this task soon.

Regards.

**Comment by OmarAyo** [comment]
Hi @ggendel 

Just sending a followup, is there any progress ? May you kindly provide a status update

Thanks

**Comment by OmarAyo** [comment]
Hi @ggendel 

Since we have not heard back from you in a while, I am closing this issue for now.
If needed, please reply and we will reopen.

Best,
