### ISSUE TITLE
IMDB example import error

### ISSUE THREAD

**Issue by undeadindustries** [arangodb/arangodb#8016]
## My Environment

* __ArangoDB Version__:        3.4.1
* __Storage Engine__:             default
* __Operating System__:        Win 10 pro latest build
* __Total RAM in your machine__:        32Gb
* __Disks in use__:        SSD

When trying to import IMDB I follow these steps in command prompt:
CD into the Graphs\IMDB folder
arangosh
require("internal").load("import.js")

I get 2 errors.
**error 1:**
Even if IMDB graph does not exist, I get an error that it does. It was created, So I delete. I re-run, I get the error again.
Temp Solution: 
Remove from import.js:
```
try {
    g = gm._create(gName);
    g.drop();
  } catch (e) {

  }
```

**error 2:**
running require("internal").load("import.js") again I get:
```
JavaScript exception in file 'import.js' at 32,7: TypeError: g.addVertex is not a function
!    g.addVertex(d._key, d);
!      ^
stacktrace: TypeError: g.addVertex is not a function
    at Function.storeVertex (import.js:32:7)
    at import.js:61:12
    at import.js:63:2
    at <shell command>:1:21
```

Please help! I'm hoping not to use Linux, bash or WSL for this project. Thanks!

**Comment by undeadindustries** [comment]
Any ideas on tis one?

**Comment by dothebart** [comment]
https://github.com/arangodb/example-datasets/issues/7 related.

**Comment by dothebart** [comment]
https://github.com/arangodb/example-datasets/commit/ece77c9b056bd26c44ce0205b872256485ae0752 fixed the example. 

Please note [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) is available.
