### ISSUE TITLE
Arangodump --tack-end doesn't work as expected. More details needed also.

### ISSUE THREAD

**Issue by asadlon** [arangodb/arangodb#8031]
## My Environment

* __ArangoDB Version__:        3.3
* __Storage Engine__:             MMFiles
* __Deployment Mode__:       Single Server with plans to implement a Cluster 
* __Infrastructure__:               own
* __Operating System__:        Centos 7
* __Total RAM in your machine__:        64 GB
* __Disks in use__:                  HDD
* __Used Package__:              Docker - official Docker library

Problem with arangodump --tick-end. I try to do the incrementat abckup of my instance. I use arangodump tool to do that and it works perfect when doing a full backup. But when I try to do an incremental one, there is a problem with 'tick-end' option. It behaves strange for me. This option doesn't allow me to pick a value other than '0'. The error message I get is:

_invalid values for --tick-start or --tick-end_

I tried to use this option in few schemas:

- only tick-end in different places
- only tick-start 
- tick-start first, tick-end second
- tick-end first, tick-end second

I also tried to use different valuse like 'tick-end > tick-start' or 'tick-start > tick-end'.

Did I do something wrong? There are not too many information in docs or in config (which is unneeded -> this option seems to be trivial) All I found is this:

_--tick-end <uint64>                                last tick to be included in data dump (default: 0)
--tick-start <uint64>                              only include data after this tick (default: 0)_

I also checked if config file is updated, and it is!:

_arangodump --tick-end 12348 --dump-options
"tick-end":{"description":"last tick to be included in data dump","hidden":false,"section":"","value":12348}_

Please, check whether you are able to reproduce the issue or let me know how it works, maybe I did something wrong.
Thank you in advance :)

## Steps to reproduce

**/# arangodump --tick-start 1820451 --tick-end 1820451 --server.database ... --server.password ... --overwrite true --output-directory "/opt/dump/"**
Server version: 3.3.19
Connected to ArangoDB 'tcp://127.0.0.1:8529', database: '...', username: '...'
Writing dump to output directory '/opt/dump'
Last tick provided by server is: 1820729
/# Dumping document collection ...
...
/# Dumping edge collection ...
Processed 11 collection(s), wrote 0 byte(s) into datafiles, sent 11 batch(es)

**/# arangodump --tick-start 1820451 --tick-end 1820450 --server.database ... --server.password ... --overwrite true --output-directory "/opt/dump/"**
Server version: 3.3.19
Connected to ArangoDB 'tcp://127.0.0.1:8529', database: '...', username: '...'
Writing dump to output directory '/opt/dump'
Last tick provided by server is: 1820779
/# Dumping document collection '...'...
2019-01-23T12:27:22Z [2386] ERROR got error from server: HTTP 400 (Bad Request): ArangoError 400: invalid from/to values
Processed 1 collection(s), wrote 0 byte(s) into datafiles, sent 1 batch(es)

**/# arangodump --tick-start 1820451 --tick-end 1820452 --server.database ... --server.password ... --overwrite true --output-directory "/opt/dump/"**
invalid values for --tick-start or --tick-end

__Problem__:

**if start = end** - Backup done, but tick-start skipped
**if start > end** - backup started, but ERROR got error from server: HTTP 400 (Bad Request): ArangoError 400: invalid from/to values
**if start < end** - invalid values for --tick-start or --tick-end

__Expected result__:

Using '--tick-end' option will allow me to do backup with last tick specified by me.

**Comment by radopopulos** [comment]
Similar issue here.

**Comment by jsteemann** [comment]
Fixed in 3.3.22 and 3.4.3.

**Comment by sleto-it** [comment]
Hi,

Thanks for reporting this. Versions 3.3.22 and 3.4.3 have been released

I am going ahead and closing this ticket now. Will you please add a new comment if further help is needed on this topic, so we can reopen the ticket?

Many Thanks,

**Comment by asadlon** [comment]
Thank you for resolving the validation.
I finally checked it precisely, and I don't get any error.

Unfortunately I'm not able to make a dump with last tick provided by me. Arangodump makes dumps with last tick available when it starts. It looks like it ignores --tick-end value, it doesn't matter if I used 332, 1 and 235423542345234234, it always make dump with last available tick on server.

Please let me know if you can reproduce it and if so, please fix it. If it works correctly, explain me what I do wrong please :) I'm not sure also if I should reopen it or make new issue :P

**Problem**
Arangodump ignores tick-end value provided by me and use last available tick value instead.

**Expected behavior**
Arangodump will make dumps using values provided by me using tick-end parameter.

**Comment by Simran-B** [comment]
@asadlon Please provide the exact command you used to dump. Which ArangoDB version did you try?

**Comment by asadlon** [comment]
I'm sorry! I forget to add it.

My version is 3.4.3 run after this fix. I use docker and my command is:
arangodump --tick-end <value> --server.database <> --server.password <> --overwrite true --output-directory "/opt/dump/"
or 
arangodump --tick-start <> --tick-end <> --server.database <> --server.password <> --overwrite true --output-directory "/opt/dump/"

Other environment details didn't change

**Comment by asadlon** [comment]
Hello, any update on this? :)

**Comment by radopopulos** [comment]
Hello,
any updates concerning this task?

**Comment by dothebart** [comment]
Hi, 
please note that we don't provide any ETAs for community support, see https://www.arangodb.com/subscriptions/ for more details.

**Comment by maxkernbach** [comment]
Hi @asadlon and @radopopulos,

The `--tick start/end` option of `arangodump`  was only a temporary incremental backup solution **exlusively for the MMFiles storage engine**.

MMFiles is deprecated starting with version 3.6.0 and it will be removed in a future release. We recommend to switch to RocksDB even before the removal of MMFiles.

Our proper incremental backup solution [**Arangobackup**](https://www.arangodb.com/docs/stable/programs-arangobackup.html), which was introduced with v3.5.1 and v3.6.0, is a command-line client tool for instantaneous and consistent [hot backups](https://www.arangodb.com/docs/stable/backup-restore.html#hot-backups) of the data and structures stored in ArangoDB. It works **exclusively for the RocksDB Storage**.

Please note that `arangobackup` is only available in the Enterprise Edition.

Your feedback about Hot Backups would be highly appreciated.

**Comment by maxkernbach** [comment]
Hi @asadlon and @radopopulos,

Did you have a chance to read my previous message?
I would also like to mention that version 3.3 is [EOL](https://www.arangodb.com/eol-notice/) by now.

**Comment by OmarAyo** [comment]
Hi @asadlon,

We haven't heard back from you recently, we are going to close this ticket

Feel free to reopen it by adding a new comment

Best
