### ISSUE TITLE
Pushing multiple jobs into Foxx queue results in unique constraint violation

### ISSUE THREAD

**Issue by ghost** [arangodb/arangodb#8048]
## My Environment

* __ArangoDB Version__:        3.4.0
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start / ArangoDB Starter
* __Infrastructure__:               local development machine
* __Operating System__:        Windows 10
* __Total RAM in your machine__:        16Gb.
* __Disks in use__:        SSD

## Component, Query & Data

__Affected feature__:
Foxx / Foxx Queues

## Steps to reproduce

1. Put the following code fragment in a Foxx service endpoint definition:

```javascript
const queues = require('@arangodb/foxx/queues');
const queue = queues.create('queue-name');

const graphs = ['g1', 'g2', 'g3', 'g4', 'g5', 'g6', 'g7', 'g8', 'g9'];
graphs.forEach(graphName => {
  try {
    queue.push({ mount: '/mymount', name: 'myscript' }, { 'graph': graphName });
  } catch (err) {
    console.warn("Could not create job due to: ", err);
  }
});
```

2. Call the endpoint

__Problem__:

Sometimes I get the following error:
```
Could not create job due to: ArangoError 1210: unique constraint violated - in index 23374576 of type rocksdb-skiplist over ["status","queue","delayUntil"]; conflicting key: 23557888
```

__Expected result__:

Jobs should be created/scheduled without any errors.

__Workaround__:
If I put `internal.wait(0.1)` after each queue push, the problem does not appear.

**Comment by dothebart** [comment]
ArangoDB 3.4 is EOLed. Closing as outdated.
