### ISSUE TITLE
Graph visualization: labels on edges feature

### ISSUE THREAD

**Issue by hoffmaaxe** [arangodb/arangodb#805]
I wish the feature of labelling edges in the graph visualization.

**Comment by PetrovskYYY** [comment]
I think it will be very good to add this option. If you have edges with data it will be also good to have a way to select what label to display.

**Comment by dothebart** [comment]
@PetrovskYYY we reworked the graph viewer for ArangoDB 3.1. 
if you want to get a sneak preview, try to build from source or try the nightly docker container `arangodb/arangodb-devel` - I think it can also do this.

**Comment by PetrovskYYY** [comment]
Thank you I actually had found this feature even in 3.0.5 for windows that I have. But there is a problem also: If there is a two edges between two nodes with different name - they both are displayed one above the other. Is it possible to implement curve edges in graph visualization module or it is also already done in 3.1?

**Comment by dothebart** [comment]
yes, have a look at: 
https://github.com/arangodb/example-datasets#debian-dependency-graph

**Comment by PetrovskYYY** [comment]
Thank you, they look beautiful! Looking forward for upcoming release!
