### ISSUE TITLE
Inserting identical BaseDocument to VertexCollection returns (misleading) 404

### ISSUE THREAD

**Issue by tohoku** [arangodb/arangodb#8071]
## My Environment

* __ArangoDB Version__:        3.4.0 (Community edition)
* __Storage Engine__:             MMFiles
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   ArangoDB/HomeBrew Service Starter
* __Configuration__:               N/A
* __Infrastructure__:               N/A
* __Operating System__:        MacOS 10.14.1
* __Total RAM in your machine__:       32 GB
* __Disks in use__:        HDD
* __Used Package__:          HomeBrew distribution
* __Client Library__:  Java Driver (Synchronous) 5.0.4

## Steps to reproduce

(See code to reproduce below.)

1. Create a graph
2. Add a vertex collection to the graph 
3. Create a BaseDocument (with a self-provided key)
4. Insert BaseDocument
5. Attempt to insert the same BaseDocument again
6. The following exception is thrown: `com.arangodb.ArangoDBException: Response: 404, Error: 1202 - document not found`

__Problem__:
A 404 (Document Not Found) is slightly misleading if you're trying to insert a document which already exists.

__Expected result__:
Maybe `409 (Conflict) - A document with this ID already exists` or something similar.

```
import com.arangodb.*;
import com.arangodb.entity.BaseDocument;
import com.arangodb.model.GraphCreateOptions;

import java.util.ArrayList;
import java.util.UUID;

// #########################################################
// Tested with arangodb-java-driver 5.0.4 and ArangoDB 3.4.0
// #########################################################
public class Main {

    public static void main(String[] args) {

        String DATABASE_NAME = "test_db1";
        String GRAPH_NAME = "test_graph";
        String VERTEX_COLLECTION_NAME = "test_vertices";

        try {
            ArangoDB connectionBuilder = new ArangoDB.Builder()
                    .build();

            ArangoDatabase db = connectionBuilder.db(DATABASE_NAME);
            ArangoGraph graph = db.graph(GRAPH_NAME);

            if (!graph.exists()) {
                db.createGraph(GRAPH_NAME, new ArrayList<>(), new GraphCreateOptions());
            }
            if (!graph.getVertexCollections().contains(VERTEX_COLLECTION_NAME)) {
                graph.addVertexCollection(VERTEX_COLLECTION_NAME);
            }
            ArangoVertexCollection vertexCollection = graph.vertexCollection(VERTEX_COLLECTION_NAME);

            // #########################################################
            // Create a new BaseDocument
            // #########################################################
            UUID uuid = UUID.randomUUID();
            BaseDocument bd = new BaseDocument();
            bd.setKey(uuid.toString());
            bd.addAttribute("name", "Paul");

            // #########################################################
            // Attempt to insert the same BaseDocument twice
            // Expected outcome:
            //   com.arangodb.ArangoDBException: Response: 404, Error: 1202 - document not found
            // #########################################################
            for (int i = 0; i < 2; i++) {
                System.out.println("Attempting to insert BaseDocument " + uuid);
                vertexCollection.insertVertex(bd);
                System.out.println("BaseDocument was inserted");
            }
        } catch (Exception ade) {
            ade.printStackTrace();
        }

    }
}
```

**Comment by khenam** [comment]
Hi,
We tested here and verified that the problem persists in version 3.4.2
Another thing we checked out was direct testing on the REST API, and same problem.
We noticed that the problem also occurs with Edge if there is a field with a unique index.

**Comment by BCaxelbecker** [comment]
Error Message 1202 and Error Code 404 are the result of the rest call.

**Comment by rashtao** [comment]
Inserting a vertex and inserting an edge violating a unique constraint is tested here:

https://github.com/arangodb/arangodb-java-driver/blob/583568a363ac9d40336997e0c97aa38ebb100563/src/test/java/com/arangodb/ArangoEdgeCollectionTest.java#L133

and 

https://github.com/arangodb/arangodb-java-driver/blob/ae671ea616c8c447507d1d337a6c990f4be677ab/src/test/java/com/arangodb/ArangoVertexCollectionTest.java#L100

Tests are successful for ArangoDB versions 3.5+ and since ArangoDB 3.4 has reached EOL I am closing this issue.
Please feel free to open a new issue if you still encounter similar problems after upgrading the DB.
