### ISSUE TITLE
Arango cycling add agent to pool

### ISSUE THREAD

**Issue by DONXAKer** [arangodb/arangodb#8093]
## My Environment
Version: 3.3.17
Storage: RocksDB
Deployment Mode: Active Failover
Deployment Strategy:  Manual Start 
Operating System: Ubuntu 16.04
Total RAM in your machine:  32Gb

I have server configuration 3 agents and 3 DB(1 leader and 2 followers). Tomorrow 1 start all server(6) and then become run in next sequence/ 3 agent then 1 leader and then 3 followers. And in leader log i have every second: `{agencycomm} Adding endpoint http+tcp://10.10.10.152:5001 to agent pool`
This agent works good and exist in this address and port. Where Arangodb save config in witch write this pool. In code line that create this info is` LOG_TOPIC(INFO, Logger::AGENCY) << "Adding " << id << "(" << endpoint << ") to agent pool";/` And it's write when poolCompleted is false. But Agents find each other.
Why this?
I try restart servers but this error too.

Config in leader in attach.
[config.txt](https://github.com/arangodb/arangodb/files/2824859/config.txt)

**Comment by dothebart** [comment]
Hi, 
Arangodb 3.3 is EOLed meanwhile, [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) available. 
Closing this as outdated.
