### ISSUE TITLE
Strange behaivor after fall arango

### ISSUE THREAD

**Issue by DONXAKer** [arangodb/arangodb#8094]
Version: 3.3.17
Storage: RocksDB
Deployment Mode: Active Failover
Deployment Strategy: Manual Start
Operating System: Ubuntu 16.04
Total RAM in your machine: 32Gb

I have server configuration 3 agents and 3 DB(1 leader and 2 followers). In night become strange behavior: arango stop accept requests for reading and data recording, can't access to web monitoring in leader. But in logs i see error like in screenshot.

![image](https://user-images.githubusercontent.com/5461979/52181122-7b487280-27ff-11e9-94d0-a213bf229279.png)

Agent see db and communicate with this. It's very bad, that agent don't change leader. 
After restart it's become good working.
Why this happen? Is this correct or it's a bug?? How can be safity in this situation? About what resource it's said? What is Scheduler thread?

**Comment by dothebart** [comment]
Hi, 
could it be that this cgroups feature hits you: 
https://unix.stackexchange.com/questions/253903/creating-threads-fails-with-resource-temporarily-unavailable-with-4-3-kernel
(at least systemd v 228 , kernel v4.4)

Can you try setting `[TasksMax](https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html#TasksAccounting=)` in `/lib/systemd/system/arangodb3.service` ?

Please note that arangodb 3.3.21 is available for download and may contain fixes you need.

**Comment by DONXAKer** [comment]
It's repeat 2 times, that is no feature but bug

**Comment by dothebart** [comment]
Hi, 
Can you share some insights with your monitoring about when this happenes? Screenshots from graphana or whatever? Like number of running processes, used memory, threads that ArangoDB is using at that time?

Another reason for threads not being able to start may be that there is no available memory to allocate their stack, so whats your ['overcommit memory setting'](https://docs.arangodb.com/3.4/Manual/Installation/LinuxOSConfiguration.html#over-commit-memory) ?

**Comment by DONXAKer** [comment]
![image](https://user-images.githubusercontent.com/5461979/52631482-f7157f80-2ecf-11e9-94d2-2dd295b19d8f.png)
this is time falling.

**Comment by dothebart** [comment]
Hi, 
can you check your long running queries log? is there something locking up resources since we see the threads oscilating?

**Comment by DONXAKer** [comment]
Hi, Dothebart. No long query in log. Every  query run <1sec. Many query <0.3 sec

**Comment by dothebart** [comment]
Hi, can you run this in a loop
`date; ps H -o 'tid comm' <PID>; sleep 5 > /tmp/somefile`
(or maybe in one file each 5 seconds) 
so that we may see which threads are spawned at that time? 

A figure missing in the screenshot above is disk I/O, do you have that too?

Can you provide a bit more information, on which machine this is? coordinator? DB-Server?
Also it would be nice to have a bit more information on your load - Do you use foxx? what type of queries do you run? Joins? Whats your shards layout? do you have collections with many shards? Whats your documents? Rather small? ~1k Rather Big > 100k?

**Comment by DONXAKer** [comment]
Some information about linux machine and disks operation:
![default](https://user-images.githubusercontent.com/5461979/52710700-0b757d00-2fa1-11e9-8996-0058748e6576.png)
![default](https://user-images.githubusercontent.com/5461979/52710747-27791e80-2fa1-11e9-90ad-206af9b1c123.png)
Threads are in graph about 150-200.  Machine is VM. In DB-Server 32 cpu and 32 ram. In agent machine 8 cpu and 16 gb
Foxx we not using. In graph you can see a lot of PUT query and a bit GET. No shards beacuse we use active failover.

**Comment by dothebart** [comment]
Could you enable request logging : https://docs.arangodb.com/3.3/Manual/Administration/Configuration/Logging.html#log-outputs to find out which sort of requests are causing the rise of the threads? 

We're talking about the leader-arangod which is misbehaving, right?

**Comment by DONXAKer** [comment]
Problem was with memory leak with parameter vm.overcommit_memor = 2. Decision is in issue https://github.com/arangodb/arangodb/issues/8163
