### ISSUE TITLE
Regex isn't working?

### ISSUE THREAD

**Issue by lukepighetti** [arangodb/arangodb#8105]
Hi there,

It appears that Regex isn't matching properly

```
^(http)[s]?(:\/\/)(www\.)?[\w|\d]+[.][\w]+[/]?$
```

This is matching nothing, when I know there are entities that match this Regex in JavaScript.

Remove the start-of-line assertion and it matches

```
https://www.wallstreet-online.de/video/10927929-smart-trade-coin-ico-new-crypto-currency-just-started-its-pre-sale-phase
```

Which doesn't seem to match? (It's close, though!)

Are there documented issues/discrepancies/expectations for the regex parser in ArangoDB?

**Comment by Simran-B** [comment]
Your example regex returns `false` for me in JavaScript:

```
> s = "https://www.wallstreet-online.de/video/10927929-smart-trade-coin-ico-new-crypto-currency-just-started-its-pre-sale-phase"
> /^(http)[s]?(:\/\/)(www\.)?[\w|\d]+[.][\w]+[/]?$/.test(s)
false
```

I see several issues with the regex in general:
- `[\w|\d]+` matches one or more word characters
  - word chars are usually `[A-Za-z0-9_]` but can be defined differently
  - digits `\d` are already covered by `\w`
  - `|` inside a character class (in square brackets) will match literal pipe characters
- the domain name contains a hypen-minus (`wallstreet-online`), but this character is not in the character class
- `$` at the end means that there must be no remainder of the input string, which will only match URLs that end with the top-level domain (optionally followed by a forward slash)

It should be more like this IMO: `/^(http)[s]?(:\/\/)(www\.)?[\w-]+[.][\w]+[/]?/.test(s)`
But this will return true for inputs like `http://_._`, which may not be what you want.

In AQL, backslashes need to be escaped. This also applies to regular expressions, which are strings in AQL. This is not documented well, and it's on my table to fix (there are some corner cases I need to investigate further). Also see the related issue #7855.

In JavaScript you can write regex literals `/foo/i` but also use a string like `new RegExp("foo", "i")`. Using a string for the expressions means you don't have to escape forward slashes. You could use the following regex for instance:

    REGEX_TEST(s, "^https?://(?:www\\.)[\\w-]+\\.[\\w]+/?")

Under a German Windows, `\\w` matches not only `A-Za-z0-9_` but also `äöüß`. Thus, you might want to exchange it for something like `[A-Za-z0-9]`. I guess it will also match certain invalid URLs as well, but maybe that's not an issue for your anyway.

**Comment by lukepighetti** [comment]
Wew, that's an extensive response to my issue. I'm impressed. Let me take a look again.

OK.

Node.js 10 LTS.

As expected
```
> s = "https://google.com"
'https://google.com'
> /^(http)[s]?(:\/\/)(www\.)?[\w|\d]+[.][\w]+[/]?$/.test(s)
true
```

As expected

```
> s = "https://www.wallstreet-online.de/video/10927929-smart-trade-coin-ico-new-crypto-currency-just-started-its-pre-sale-phase"
'https://www.wallstreet-online.de/video/10927929-smart-trade-coin-ico-new-crypto-currency-just-started-its-pre-sale-phase'
> /^(http)[s]?(:\/\/)(www\.)?[\w|\d]+[.][\w]+[/]?$/.test(s)
false
```

As expected (remove `^`)

```
> s = "https://www.wallstreet-online.de/video/10927929-smart-trade-coin-ico-new-crypto-currency-just-started-its-pre-sale-phase"
'https://www.wallstreet-online.de/video/10927929-smart-trade-coin-ico-new-crypto-currency-just-started-its-pre-sale-phase'
> /(http)[s]?(:\/\/)(www\.)?[\w|\d]+[.][\w]+[/]?$/.test(s)
false
```

However, ArangoDB results are `false`, `false`, `true` based on my testing yesterday. Would have to set aside some time to provide a minimal reproducible example. So, if you feel this issue is unwarranted please don't be shy about closing.

**Comment by Simran-B** [comment]
If I adjust the query for AQL (`\/` -> `/`, `\` -> `\\`), then I get identical results.

NodeJS v11:

```
> s1 = "https://google.com"
> s2 = "https://www.wallstreet-online.de/video/10927929-smart-trade-coin-ico-new-crypto-currency-just-started-its-pre-sale-phase"
> [
    /^(http)[s]?(:\/\/)(www\.)?[\w|\d]+[.][\w]+[/]?$/.test(s1),
    /^(http)[s]?(:\/\/)(www\.)?[\w|\d]+[.][\w]+[/]?$/.test(s2),
    /^(http)[s]?(:\/\/)(www\.)?[\w|\d]+[.][\w]+[/]?/.test(s1),
    /^(http)[s]?(:\/\/)(www\.)?[\w|\d]+[.][\w]+[/]?/.test(s2)
]
[ true, false, true, true ]
```

ArangoDB v3.4.2:

```js
LET s1 = "https://google.com"
LET s2 = "https://www.wallstreet-online.de/video/10927929-smart-trade-coin-ico-new-crypto-currency-just-started-its-pre-sale-phase"
RETURN [
    REGEX_TEST(s1, "^(http)[s]?(://)(www\\.)?[\\w|\\d]+[.][\\w]+[/]?$"),
    REGEX_TEST(s2, "^(http)[s]?(://)(www\\.)?[\\w|\\d]+[.][\\w]+[/]?$"),
    REGEX_TEST(s1, "^(http)[s]?(://)(www\\.)?[\\w|\\d]+[.][\\w]+[/]?"),
    REGEX_TEST(s2, "^(http)[s]?(://)(www\\.)?[\\w|\\d]+[.][\\w]+[/]?")
]
/* [ true, false, true, true ] */
```

**Comment by lukepighetti** [comment]
Thanks for your attention on this issue, I really appreciate it. I will close it because that seems appropriate. :)
