### ISSUE TITLE
ArangoError: filesystem full when there's PLENTY of space on mount

### ISSUE THREAD

**Issue by parekhnikunj** [arangodb/arangodb#8113]
## My Environment

* __ArangoDB Version__:        3.3.19 
* __Storage Engine__:             RocksDB 
* __Deployment Mode__:       Single Server 
* __Deployment Strategy__:   Manual Start 
* __Configuration__:               EC2 
* __Infrastructure__:               AWS 
* __Operating System__:        Linux ip-172-20-6-177.us-west-2.compute.internal 4.14.72-73.55.amzn2.x86_64 #1 SMP Thu Sep 27 23:37:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux 
* __Total RAM in your machine__:        8GB 
* __Disks in use__:        4.2GB out of 56 GB SSD 
* __Used Package__:              No idea 

## Component, Query & Data

__Affected feature__:

{"message":"filesystem full","name":"ArangoError","stack":"ArangoError: filesystem full\n    at new ArangoError (/usr/src/app/node_modules/arangojs/lib/async/error.js:71:21)\n    at Object.resolve (/usr/src/app/node_modules/arangojs/lib/async/connection.js:243:32)\n    at _hosts.(anonymous function) (/usr/src/app/node_modules/arangojs/lib/async/connection.js:122:26)\n    at IncomingMessage.res.on (/usr/src/app/node_modules/arangojs/lib/async/util/request.node.js:48:21)\n    at IncomingMessage.emit (events.js:185:15)\n    at endReadableNT (_stream_readable.js:1106:12)\n    at process._tickCallback (internal/process/next_tick.js:178:19)","code":500}

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:

Small 100-200 bytes JSON documents

__Size of your Dataset on disk__:

4.2 GB

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. Send following query:

 ```
curl --request POST \ --url <endpoint>:8529  \ --header 'content-type: application/json' \ --header 'x-google-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJodHRwczovL2N0ei5uei9pZCI6IjYyMzUzZGYzLTc4M2QtNDg2NC1hZDAxLWVlYmMxN2ZjYWZjZSIsImlzcyI6Imh0dHBzOi8vY2lpdGl6ZW4uYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDViZTQ5NTdmZWMzMTIzMjBmNTYyMzZhNCIsImF1ZCI6WyJodHRwczovL2FwaS5kZXYuY2lpdGl6ZW4ubmV0Il0sImlhdCI6MTU0OTMyNDE1OCwiZXhwIjoxNTQ5NDEwNTU4LCJhenAiOiJmRmlTTjgyTG13VHl5MWFxM3R6RGR3WWlLeFE4SXJSNSIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUiLCJndHkiOiJwYXNzd29yZCJ9.sPHwzEb9myFPOY9V2m82nud_Y83g2frpUgQHqy85AXQ' \ --data '{ "foo": "bar" }' ```
--

__Problem__:


__Expected result__:

No ArangoError and above object getting inserted into DB

**Comment by ObiWahn** [comment]
Please use `df -i` to make sure you do not have exhausted all available inodes.

**Comment by OmarAyo** [comment]
Hi @parekhnikunj,

Just sending a quick followup, are you still facing this issue ? if yes please provide the output of `df -i`

Thanks,

**Comment by parekhnikunj** [comment]
Hello; Sorry for delay; yes the issue was not exhausted inodes but something to do with volume mounts.
We have had other stability issues with ArangoDb due to which we are having to run it in Single Server mode, but we can close this issue for now and we’d discuss the other issue separately.

Thanks.

~
Cloud Architect.
ciitizen  |  we can do more. together.
