### ISSUE TITLE
Issue with Foxx Service (windows)

### ISSUE THREAD

**Issue by akhilrana** [arangodb/arangodb#8114]
## My Environment

* __ArangoDB Version__:    3.4.2    
* __Storage Engine__:           RocksDB  
* __Deployment Mode__:    Arango as service on single server   
* __Deployment Strategy__:   
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:     Windows 10   
* __Total RAM in your machine__:   16Gb     
* __Disks in use__:      HDD  
* __Used Package__:              

## Component, Query & Data

__Affected feature__:
 Foxx

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. Upload the given zip using add service option available on the web interface.
2. Provide a mount path

__Problem__: I am trying to create a simple foxx service, following the steps mentioned here> https://docs.arangodb.com/3.4/Manual/Foxx/GettingStarted.html .
I created a ZIP with 2 files: index.js

_index.js_

```js
'use strict';
const createRouter = require('@arangodb/foxx/router');
const router = createRouter();

module.context.use(router);
// continued
router.get('/hello-world', function (req, res) {
  res.send('Hello World!');
})
.response(['text/plain'], 'A generic greeting.')
.summary('Generic greeting')
.description('Prints a generic greeting.');
```

_manifest.json_

```json
{
  "engines": {
    "arangodb": "^3.0.0"
  },
  "main": "index.js"
}
```
I am facing issue, when trying to upload this zip on the web interface on the service menu.

![error](https://user-images.githubusercontent.com/47376196/52324303-ced8dd00-2a06-11e9-8e59-7b28db431116.PNG)

[getting-started.zip](https://github.com/arangodb/arangodb/files/2835098/getting-started.zip)

__Expected result__:
The service should be added.

**Comment by Simran-B** [comment]
I tried to reproduce the problem under Windows 10, using ArangoDB 3.4.2 in user mode and the provided zip file. No errors related to the service installation are logged for me.

Do you have some anti-virus software installed, which might interfere? `ArangoError: service files missing` sounds like the files are not where they should be.

What database did you try to install the service in? _system?

Can you check whether the files are in the Foxx apps folder after upload?
The folder should be `%localappdata%\ArangoDB-apps\`

**Comment by akhilrana** [comment]
I have anti-virus on my machine, but I checked it has not removed any files.
I was trying to install the service under _system database, I changed it to a new database as well, but still,  couldn't install it (attached a snapshot for errors from logs).
In the ArangoDB-apps folder, there are subfolders D:\ArangoDB-apps\_db\EMS\_appbundles which are created, but _appbundles doesn't have any file in it.

Just to brief you,
I have installed arangodb on 'D drive' using the windows installation provided on the website, since there were some write permission issues which were happening, when I tried to install it on the default C:\Program Files path.
Created 3 folders, one each for database, foxx apps, and for service.
Apart from this, I have not downloaded any additional resource, let me know if I am missing any add-on. 
![error-1](https://user-images.githubusercontent.com/47376196/52357136-94e5f600-2a5b-11e9-91a7-0d0866a79e0c.PNG)

**Comment by akhilrana** [comment]
The Issue got resolved, It was because of anti-virus, arangod was running fine, but when the foxx service was being created, the anti virus was blocking the ZIP.

**Comment by Simran-B** [comment]
Glad that you found the problem!
So the AV did not allow arangod to write the .zip to the file system to then unpack and install it?
May I ask what AV software caused this?

**Comment by akhilrana** [comment]
Yes, it didn't allow the zip to unpack and install it. The AV software is Kaspersky.
