### ISSUE TITLE
Incorrect javascript modules implementation for foxx services

### ISSUE THREAD

**Issue by rolurq** [arangodb/arangodb#8128]
## My Environment

* __ArangoDB Version__:        3.4.2-1
* __Storage Engine__:             <RocksDB
* __Deployment Mode__:      Single Server
* __Deployment Strategy__:   Manual Start in Docker
* __Configuration__:               --
* __Infrastructure__:               own
* __Operating System__:        bebian buster
* __Total RAM in your machine__:        12GB
* __Disks in use__:        HDD
* __Used Package__:              Docker - official Docker library

## Component, Query & Data

__Affected feature__:  Foxx

__Dataset__:
Issue doesn't not depends on the data

## Steps to reproduce

1. Create a new foxx service
2. Install `aws-sdk` as dependency
3. In order to ensure synchronicity all aws requests are made this way:
```
const stream = request.createReadStream(); 
stream.read(); // blocks until response is received
```
`request` is an `AWS.Request` object

__Problem__:
When a request in such way is sent, it fails with the following error
```
TypeError: process.hrtime is not a function
```
And that function is not in the `process` module within `arangosh`. If a patch is added for that function, then it fails with this error in the `aws-sdk` library
```
JavaScript exception in file '/.../node_modules/aws-sdk/lib/util.js' at 471,30: TypeError: util.crypto.lib.createHash is not a function
!      return util.crypto.lib.createHash(algorithm);
!                             ^
stacktrace: TypeError: util.crypto.lib.createHash is not a function
    at Object.createHash (/.../node_modules/aws-sdk/lib/util.js:471:30)
    at Object.hash (/.../node_modules/aws-sdk/lib/util.js:412:30)
    at Object.sha256 (/.../node_modules/aws-sdk/lib/util.js:408:26)
    at Object.computeSha256 (/.../node_modules/aws-sdk/lib/util.js:723:17)
    at Request.COMPUTE_SHA256 (/.../node_modules/aws-sdk/lib/event_listeners.js:143:18)
    at Request.callListeners (/.../node_modules/aws-sdk/lib/sequential_executor.js:102:18)
    at Request.emit (/.../node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/.../node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/.../node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/.../node_modules/aws-sdk/lib/state_machine.js:14:12)
``` 

__Expected result__:
The request should be executed correctly. The function `hrtime` must be added to the `process` module and the call to `createHash` executed by `aws-sdk` should be correct.

**Comment by Simran-B** [comment]
ArangoDB provides **partial implementations** for certain modules, including `process` - see the [documentation](https://docs.arangodb.com/3.4/Manual/Appendix/JavaScriptModules/). `crypto` is not available, but there is [@arangodb/crypto](https://docs.arangodb.com/3.4/Manual/Appendix/JavaScriptModules/Crypto.html).

Nonetheless, feel free to implement the functions you miss and open a PR.

**Comment by pumpadump** [comment]
Are there any plans on extending the support for these modules? We also would like to use the aws-sdk form arango.

**Comment by OmarAyo** [comment]
Hi all,

There are no plans to implement more modules at this point in time, but feel free to open a pull request should you implement it yourself

Best
