### ISSUE TITLE
Arangod.exe crashed while testing

### ISSUE THREAD

**Issue by lostdev** [arangodb/arangodb#8136]
## My Environment

* __ArangoDB Version__:  3.4.2-1      
* __Storage Engine__:  RocksDB           
* __Deployment Mode__: Single Server      
* __Deployment Strategy__: Manual Start - Windows service  
* __Configuration__:               
* __Infrastructure__: own             
* __Operating System__:Windows 10        
* __Total RAM in your machine__: 16GB       
* __Disks in use__: SSD       
* __Used Package__:              

## Component, Query & Data

__Affected feature__:

AQL query using web interface 

__AQL query (if applicable)__:

Script # 1 (create things)
```
FOR i IN 1..1000000
  INSERT {
    Title: CONCAT("Thing # ", i, " - ", (1 + FLOOR(RAND() * 1500))),
    Type: 1,
    Description: CONCAT("This is just a test", 100 + FLOOR(RAND() * (150 - 100 + 1)))
  } IN Thing
```

Script # 2: (create keywords)
```
FOR i IN 1..30000
  INSERT {
    Title: CONCAT("Keyword # ", i)
  } IN Keyword
```

Script # 3: create edges
```
LET keywords = (
    FOR kw IN Keyword
    SORT RAND()
    LIMIT 20
    return kw
)
LET docs = (
    FOR doc IN Thing
    SORT RAND()
    LIMIT 200
    return doc
)

FOR doc IN docs
    FOR kw IN keywords
        INSERT { _from: doc._id, _to: kw._id } INTO has_keyword
```

__AQL explain (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce
I don't have repro steps as I am just testing at the moment, but you can try:

1. Executing the scripts above
2. Edit the `LIMIT` values in Script # 3, to insert more values at a time.

__Problem__:
As I was using the web interface (in Google Chrome `71.0.3578.98 (Official Build) (64-bit)`), my browser suddenly crashed, and the arrangodb service stopped. Looking at event viewer I found this:

```
Faulting application name: arangod.exe, version: 0.0.0.0, time stamp: 0x5c532e94
Faulting module name: arangod.exe, version: 0.0.0.0, time stamp: 0x5c532e94
Exception code: 0xc0000409
Fault offset: 0x000000000211ba49
Faulting process id: 0x3de8
Faulting application start time: 0x01d4c07ddc563533
Faulting application path: C:\Program Files\ArangoDB3 3.4.2-1\usr\bin\arangod.exe
Faulting module path: C:\Program Files\ArangoDB3 3.4.2-1\usr\bin\arangod.exe
Report Id: ca2d99a0-a37e-4507-884c-542790ed7c7f
Faulting package full name: 
Faulting package-relative application ID: 
```

I could not find any logs in the `C:\Program Files\ArangoDB3 3.4.2-1\var\log\arangodb3`. What are the next steps for debugging this?

__Expected result__:
No crashes :)

**Comment by dothebart** [comment]
Arangodb 3.4 is EOLed. 

The way forward would have been [creating & analyzing a crashdump](https://github.com/arangodb/arangodb/blob/devel/README_maintainers.md#windows-core-dumps) - sorry that @OmarAyo didn't sugest this. 

Please note that [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/)  is available for download.
