### ISSUE TITLE
Fail to backup with error out of memory

### ISSUE THREAD

**Issue by DONXAKer** [arangodb/arangodb#8145]
Version: 3.3.22
Storage: RocksDB
Deployment Mode: Active Failover
Deployment Strategy: Manual Start
Operating System: Ubuntu 16.04
Total RAM in your machine: 32Gb
Total CPU: 32

In version 3.3.17 we create every hour a backup with size 2.1gb, but in version 3.3.21 we fall with error:
2019-02-12T02:10:54Z [23993] ERROR while dumping collection 'Col1' got error from server:

# Dumping document collection 'Col1'...
 HTTP 500 (Internal Server Error): ArangoError 3: out of memory (exception location: /var/lib/otherjenkins/workspace/RELEASE__BuildPackages/lib/Basics/VPackStringBufferAdapter.h:71)
Processed 1 collection(s), wrote 110648599 byte(s) into datafiles, sent 6 batch(es)
# Dumping document collection 'Col2'...
2019-02-12T02:09:39Z [23806] ERROR while dumping collection 'Col2' got error from server: HTTP 500 (Internal Server Error): ArangoError 3: out of memory (exception location: /var/lib/otherjenkins/workspace/RELEASE__BuildPackages/lib/Basics/VPackStringBufferAdapter.h:71)
Processed 9 collection(s), wrote 1293992749 byte(s) into datafiles, sent 50 batch(es)

**Comment by maxkernbach** [comment]
Hi @DONXAKer,

could you please share the exact `arangodump` command? 

Are you specifying values for the options `--batch-size <uint64>` and `--initial-batch-size <uint64>`?
By default these options using the following values:

```
  --batch-size <uint64>             maximum size for individual data batches (in bytes) (default: 67108864)
  --initial-batch-size <uint64>     initial size for individual data batches (in bytes) (default: 8388608)
```

Can you try to specify smaller batch sizes and rerun `arangodump`?

**Comment by DONXAKer** [comment]
Ok, thanks for answer, we will try and reply later.

**Comment by DONXAKer** [comment]
Ok, thanks for answer, we will try and reply later.

**Comment by maxkernbach** [comment]
Hi @DONXAKer,

did you already have a chance to try it out?

**Comment by DONXAKer** [comment]
Problem was solved in another issue. https://github.com/arangodb/arangodb/issues/8163
