### ISSUE TITLE
Document `exclusive` option for transactions.

### ISSUE THREAD

**Issue by internalfx** [arangodb/arangodb#8154]
When looking at the JS driver docs the `exclusive` option is missing.

![image](https://user-images.githubusercontent.com/583701/52650229-11873300-2ea7-11e9-9a2b-9ba9e05dd72b.png)

It _is_ mentioned in the locking and isolation page.

https://docs.arangodb.com/3.4/Manual/Transactions/LockingAndIsolation.html

I think it would be easier to find if one of the given examples used the feature as well.

**Comment by Simran-B** [comment]
Opened a pull request upstream: https://github.com/arangodb/arangojs/pull/600

**Comment by maxkernbach** [comment]
Closing as fixed.

The missing documentation of `exclusive` was added in the arangojs docs and is available at:
https://www.arangodb.com/docs/stable/drivers/js-reference-database-transactions.html
