### ISSUE TITLE
Extend functionality of the Web-Interface

### ISSUE THREAD

**Issue by qohelet** [arangodb/arangodb#8161]
## My Environment

* __ArangoDB Version__:        3.4.1
* __Storage Engine__:             RocksDB 
* __Deployment Mode__:       Single Server 
* __Deployment Strategy__:   Manual Start in Docker
* __Operating System__:        Ubuntu 18.04
* __Disks in use__:        HDD
* __Used Package__:              Ubuntu

## Component, Query & Data

__Affected feature__:
Graph Viewer

__Problem__:
I would like to extend some functionalities of the Graph Viewer. How should that be done? 

Are there some hooks from the web-interface or is this something that should be done with Foxx-Services?
In case there are already Services that implement the Graph Viewer that would probably be a cleaner approach - or is it required to do changes in the Source Code?

In my particular case I would like to add some template-nodes, a button for copying a node or a modified interface for adding new nodes. 

Thank you

**Comment by maxkernbach** [comment]
Hi @qohelet,

the only way to add a functionality to the Graph Viewer is by directly modifying the source code.
The Graph Viewer's source code is located in the following directory:

https://github.com/arangodb/arangodb/tree/devel/js/apps/system/_admin/aardvark/APP/frontend/js/views (graphViewer.js, graphSettingsView.js ...)

**Comment by qohelet** [comment]
Good to know, thank you
