### ISSUE TITLE
Cannot inspect a document in the webinterface if its _key contains an URL encoding

### ISSUE THREAD

**Issue by zawlazaw** [arangodb/arangodb#8166]
## My Environment

* __ArangoDB Version__:       3.4.1
* __Storage Engine__:            RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               Docker container

## Component, Query & Data

__Affected feature__: Inspect/edit details of a document in the webinterface.

## Steps to reproduce

1. Open the webinterface, select any database and collection (at best, create a new collection).
2. Go to the "Collection -> Content" panel of that collection, and add a new document (click on the plus symbol in the top right)
3. Enter `Hello%20World` as its _key

__Problem__:
Immediately shows an Error: "`Document not found. Requested ID was: "counter1/Hello World`".
Note that the Error decodes `%20` to an empty space.
One can still go back to the "Collection / Content" overview, and see this document in the overview, but one cannot select it for inspecting or editing. However, deletion works.

The behavior is the same if added via API.
Examples of affected keys are `Hello%20World`, `ThisIs%34You`.
Noteable to mention, these ones work: `Hello%XXWorld`, `Hello+World`.
Thus, it seems as if the percentage encoding (URL encoding) raises this problem.

__Expected result__:
Since all above listed keys are valid values for _key, documents of such a key should be accessible in the webinterface like any other document.

**Comment by OmarAyo** [comment]
Hi @zawlazaw,

Thanks for reporting this issue, we are able to reproduce it and this is a WebUI bug

Best,

**Comment by jsteemann** [comment]
Fixed in 3.9.0

**Comment by maxkernbach** [comment]
The [GA release of ArangoDB 3.9](https://www.arangodb.com/2022/02/introducing-arangodb-3-9-further-powering-graph-at-scale/), which includes a fix for this issue, is available.
