### ISSUE TITLE
Confirmation of Single-Shard Behavior for ArangoDB Cluster

### ISSUE THREAD

**Issue by alexpmorris** [arangodb/arangodb#8174]
## My Environment

* __ArangoDB Version__:        3.4.2-1
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   Manual Start
* __Configuration__:               3 nodes
* __Infrastructure__:               cloud
* __Operating System__:        Ubuntu 18.04
* __Total RAM in your machine__:  16Gb
* __Disks in use__:        SSD
* __Used Package__:              lxd

My first thought was to setup `Active Failover`.  However, that seemed problematic in my situation as I would prefer the additional delay of synchronous replication, if it means there is no chance of data loss in the case of a failover *(not to mention, the process also appears more seamless from the client's perspective)*.

(1)
As such, I wanted to confirm behavior in an ArangoDB Cluster. The documentation makes the following stipulation:

```
Note that for non-sharded collections in a cluster, 
the transactional properties of a single server apply (fully ACID).
```

My collections are set as follows:

`new CollectionCreateOptions().numberOfShards(1).replicationFactor(3);`

My understanding is that this should now maintain 3 full copies of each collection (one on each DBServer), while also maintaining full transactional properties even in a clustered environment.  I would also like to confirm this is the case even if each collection involved has a different leader.  For example, can full ACID transactions between the `user` and `transactions` collections still be maintained in the following case:

| Collection | Shard | Leader | Followers | Sync |
|---|---|---|---|---|
|user|s4645423|DBServer0001|DBServer0002, DBServer0003 | ✔|
|transactions|s3424563|DBServer0002|DBServer0001, DBServer0003 | ✔ |

(2)
I was also wondering if it is possible to set a particular DBServer in a cluster as a follower only, or at least set it with a lower priority for leader selection *(possibly also with a collection "write quorum" of 2, though that would probably conflict with the global "synchronous view")*.  I have found I can sort of accomplish this by taking down a DBServer and letting the cluster redistribute the leaders.  However, it would seem there must be a cleaner way to accomplish this.

(3)
As a final question, I was originally using auto-increment, which obviously is still not available in Cluster Mode.  However, it seems `traditional` mode is fine, as keys are also in numerical ascending order *(please confirm this as well if it is the default mode, as I have observed new documents in the same collection with lower key values than earlier ones)*.  While I *believe* this is the default key mode, when I tried to set the following through the JAVA library, any `insert` operation even from the GUI would result in the error *"unexpected document key"* *(_key was always set to `null`)*:

`new CollectionCreateOptions().keyOptions(false, KeyType.traditional, 1, 1);`

(4)
Lastly, it doesn't yet seem the JAVA library supports the `uuid` and `padded` key generators.  Is there any reason for this, or should I open an issue for it?  The fix may be as simple as adding `uuid` and `padded` to the `KeyType` enum:

https://github.com/arangodb/arangodb-java-driver/blob/aaff8358fd7a50de9aa756abf9456bde8671da5c/src/main/java/com/arangodb/entity/KeyType.java

```
public enum KeyType {
	traditional, autoincrement, uuid, padded
}
```

Thank you in advance for any additional guidance and insight you can offer me regarding these points.

**Comment by dothebart** [comment]
1) is only defined without replication, so your question already fails short with your replication setting. This may improve with ArangoDB 3.5 - stay tuned. 
2) there currently is no way for the user to influence which DB-Server will have which shards. 
3) the traditional key generator should rather be treated as random number in the cluster. The current implementation stage will give you bigger numbers for later inserts, if they occur via the same coordinator. 
4) yes, @BCaxelbecker can you add that to your list?

**Comment by alexpmorris** [comment]
`1. is only defined without replication, so your question already fails short with your replication setting.`

thanks @dothebart for the clarifications.  regarding (1), could this issue be overcome by directing all traffic through a single coordinator?

**Comment by dothebart** [comment]
Hi,
the coordinator doesn't know anything about the replication settings, its not involved. The coordinator itself is stateless except for cursors. So, no, this doesn't change anything.

**Comment by maxkernbach** [comment]
Hi @alexpmorris,

Just sending a follow-up.

- Do you have any further questions or can we consider this issue solved?
- Regarding 4: Did you have a chance to open a separate issue?

**Comment by alexpmorris** [comment]
I believe it's been addressed to the best extent possible for now, and I submitted a PR for the KeyType as well, thanks!

https://github.com/arangodb/arangodb-java-driver/pull/262
