### ISSUE TITLE
Allow clients to assign metadata to queries

### ISSUE THREAD

**Issue by aveiros** [arangodb/arangodb#8177]
## My Environment

* __ArangoDB Version__:        3.4.2
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:    ArangoDB Starter in Docker
* __Infrastructure__:               own
* __Operating System__:        MacOS 10.13.4
* __Total RAM in your machine__:        32Gb
* __Disks in use__:        SSD
* __Used Package__:              Docker - official Docker library

This is more of a suggestion/feature request. Why not allow clients to assign metadata to queries, for example, using key/values pairs on AQL Options. This would allow clients to quickly identify queries that they fired to the server and act on them (for example, long-running queries)

This information would then be available in /_api/query/current

**Comment by dothebart** [comment]
Hi, 
It is actually implemented in the server ( see https://docs.arangodb.com/3.4/HTTP/AsyncResultsManagement/ for more details ) - However, not many drivers implement the client API for this.

**Comment by aveiros** [comment]
From what I could find out from talking on Slack, this is what the Web UI is doing.
I had a quick look and saw the results are actually coming from the Job API.

Another thing I was told is that I could combine the AQL streaming cursors with the Job API.

Currently using the Official Arango Java Driver and doubt it supports any of this.

**Comment by dothebart** [comment]
the java driver was actually the first to implement this.

**Comment by dothebart** [comment]
Since the referenced ArangoDB 3.4 is EOLed closing this as solved.
Please note that [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) is available.
