### ISSUE TITLE
Make /_api/query/current richer

### ISSUE THREAD

**Issue by aveiros** [arangodb/arangodb#8178]
## My Environment

* __ArangoDB Version__:        3.4.2
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:    ArangoDB Starter in Docker
* __Infrastructure__:               own
* __Operating System__:        MacOS 10.13.4
* __Total RAM in your machine__:        32Gb
* __Disks in use__:        SSD
* __Used Package__:              Docker - official Docker library

Another suggestion/feature request.

Although on 3.4.2 you can tell from the api that a query is using stream or not, there's no way to tell if a query has had results/hits since it's been running:

- in stream mode, would be useful if there were some information X results hit, Y results sent, or even hitResults: true
- in normal mode, the same as above (if applicable).

**Comment by dothebart** [comment]
Hi, 
Part of the streaming API is, that the result set isn't yet known at the time the server starts sending the answers, so X is basically unknown. But Y- number of documents sent - could be added to the statistics output.

**Comment by dothebart** [comment]
This information is actualy available when using [query profiling](https://www.arangodb.com/docs/stable/aql/execution-and-performance-explaining-queries.html#profiling-queries) hence closing as solved.

Please note that [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) is available.
