### ISSUE TITLE
ArangoDb Clustering with existing database directory

### ISSUE THREAD

**Issue by shreychouhan** [arangodb/arangodb#8216]
## My Environment

* __ArangoDB Version__:        3.3.10
* __Storage Engine__:             RocksDB
* __Infrastructure__:               own
* __Operating System__:        Ubuntu 18.04

__Problem__:
Currently, clustering is not set up in our environment, now we want to set up clustering in ArangoDB with a below mentioned script. The script as such work fine but it creates a separate database directory which completely ignores existing database during ArangoDb clustering setup.

arangodb --starter.data-dir=db1 > db1.log &
arangodb --starter.data-dir=db2 --starter.join ::1 > db2.log &
arangodb --starter.data-dir=db3 --starter.join ::1 > db3.log &

__Expected result__:
I want to use an existing database directory during setup of ArangoDB clustering. So that after clustering setup existing database of the environment remains the same. I don't want to perform export and import from unclustered instance to clustered instance.

**Comment by sleto-it** [comment]
Hi @shreychouhan,

Thanks for opening this ticket. This is unfortunately currently not possible. The procedure to migrate from single server to cluster requires taking a backup from the single server and restoring it to the cluster, as documented in the following page: https://docs.arangodb.com/3.4/Manual/Deployment/MigratingSingleInstanceCluster.html

Anything specific blocking you from doing a backup and restore?

Thanks,

**Comment by dothebart** [comment]
Closing this question as Answered. If more questions arise, don't hesitate to ask.
