### ISSUE TITLE
Foxx can not find nested node_module dependencies

### ISSUE THREAD

**Issue by Elminday** [arangodb/arangodb#8236]
Possibly related to: https://github.com/arangodb/arangodb/issues/722

## My Environment

* __ArangoDB Version__:        3.4.3
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Infrastructure__:               locally
* __Operating System__:        Ubuntu 18.04
* __Used Package__:             Ubuntu

## Component

__Affected feature__:
Foxx

If I add `graphql-tools` dependency to my service of Foxx and it has `graphql` dependency, Foxx does not find it. I have to add every nested dependency of another dependency to my main service node_modules which is unmaintainable.

## Steps to reproduce

1. Add `graphql-tools` to `package.json` dependencies (make sure they are in node_modules in root of service zipped folder)
2. Require `graphql-tools` in `index.js`. 
3. Zip the service folder, try to upload it as service in Foxx.
4. Get error that there is no `graphql` dependency which is used in `graphql-tools` dependency.

__Problem__:

Services: 3103. failed to invoke module Reason: ArangoError 3100: cannot locate module File: graphql File: /var/tmp/arangodb3/services-tmp-1736-2631170076/node_modules/graphql-tools/dist/makeExecutableSchema.js

__Expected result__:

Service uploaded succesfully.

**Comment by pluma** [comment]
graphql-tools has a _peer_ dependency on graphql. That means it will not install graphql as a dependency automatically, you need to add it to your package.json explicitly. We recommend using the official graphql package rather than the outdated `graphql-sync` ArangoDB ships for compatibility reasons.

**Comment by Elminday** [comment]
But graphql is async, I understood that we needed graphql-sync because we can not run async code in Foxx.

**Comment by Elminday** [comment]
I understood that setuping graphql API in Foxx is rewarding rather than for example on Node server, because it fetches data from server faster when scaling. Could you comment on it?

**Comment by pluma** [comment]
graphql is only async if resolvers are async. Starting with one of the more recent versions sometime last year graphql is sync if all resolvers are also sync. So graphql-sync is no longer necessary.

The advantage of using graphql in Foxx rather than in Node is that if a resolver needs to fetch data from the database it won't need to go over the network, which is significantly slower.

**Comment by Elminday** [comment]
I also meant to ask. 
Is it possible to provide a string from schema.graphql (SDL format) to @arangodb/foxx/graphql or does it strictly require SDL to be converted to GraphQLSchema object from SDL before passing it as a schema parameter to createGrahpqlRouter?

What I mean:

If I have schema.graphql:
```
.....
type Query {
  me: User
}
type Mutation {
  createUser(input: CreateUserInput): UserPayload
}
schema {
  query: Query
  mutation: Mutation
}
.....

```

Can I pass it directly somehow to passSchemaHere parameter or do I convert it before hand somehow?

```
const createGraphqlRouter = require('@arangodb/foxx/graphql'),
router = createGraphqlRouter({passSchemaHere, graphiql: true});

module.context.use(router);
```

**Comment by Simran-B** [comment]
> graphql is only async if resolvers are async. Starting with one of the more recent versions sometime last year graphql is sync if all resolvers are also sync. So graphql-sync is no longer necessary.

@pluma Can you update the documentation with this information please?
https://docs.arangodb.com/3.4/Manual/Foxx/Reference/Modules/GraphQL.html - not sure if anywhere else.

**Comment by Elminday** [comment]
I seem to get an error with GraphQL SDL setup on Foxx only:

```
const sdlSchema = 
  type Author {
    firstName: String
  }
  type Query {
    author(id: Int!): Author
  },

 makeExecutableSchema = require("graphql-tools").makeExecutableSchema,

 schema = makeExecutableSchema({
  typeDefs: sdlSchema,
 });
 console.log(schema); // log output below

  const createGraphqlRouter = require('@arangodb/foxx/graphql'),
  router = createGraphqlRouter({schema, graphiql: true})
    .summary('GraphQL endpoint')
    .description('GraphQL endpoint for user service.');
  console.log(router);

module.context.use(router);

```

First log:
> {[GraphQLSchema] "__validationErrors" : undefined, "__allowedLegacyNames" : [ ], "_queryType" : [Object {[GraphQLObjectType] "name" : "Query", "description" : "", "astNode" : { "kind" : "ObjectTypeDefinition", "description" : undefined, "name" : { "kind"

Second log:
> [Router]

Error in graphiql:


```
{
  "errors": [
    {
      "message": "Schema must be an instance of GraphQLSchema. Also ensure that there are not multiple versions of GraphQL installed in your node_modules directory."
    }
  ]
}
```

I do not seem to have multiple versions of GraphQL, however how do I make sure of that?

My package.json:

```
  "dependencies": {
    "global": "^4.3.2",
    "graphql": "^14.1.1",
    "graphql-tools": "^4.0.4",
    "iterall": "^1.2.2"
  }

```

**Comment by Elminday** [comment]
It is reproducible, tried it from scratch again.

**Comment by Elminday** [comment]
@pluma were you able to reproduce the issue?

**Comment by Elminday** [comment]
@Simran-B maybe you could help out? We seem not to get feedback from maintainers side.

**Comment by pluma** [comment]
@Elminday It doesn't look like you're passing the graphql library you're using to the graphql router. See the "graphql" options in https://docs.arangodb.com/3.4/Manual/Foxx/Reference/Modules/GraphQL.html

**Comment by Simran-B** [comment]
@pluma Should the documentation be adjusted to mention that it doesn't have to be graphql-sync copy but can also be a recent official graphql lib?

> graphql: object (optional)
> 
> If you need to use your own copy of the graphql-sync module instead of the one bundled with ArangoDB, here you can pass it in directly.

**Comment by pluma** [comment]
@Simran-B I think so (this was written before graphql-js supported synchronous execution).

I think we should actually go one step further and explicitly tell people to bundle their own copy and pass it to the router and only mention that it falls back to the bundled out-of-date copy if none is provided. For 4.0 I would like to make the graphql argument required so maybe we can log a deprecation warning in one of the upcoming 3.x releases if the graphql parameter is omitted.

**Comment by maxkernbach** [comment]
Hi @Elminday,

how are things going, does the problem still persist?

> It doesn't look like you're passing the graphql library you're using to the graphql router. See the "graphql" options in https://docs.arangodb.com/3.4/Manual/Foxx/Reference/Modules/GraphQL.html

Have you been able to solve this issue?

**Comment by Elminday** [comment]
I got it resolved with the response above.
