### ISSUE TITLE
Request for adding IGNORE AQL function (opposite of KEEP AQL function)

### ISSUE THREAD

**Issue by dilipvamsi** [arangodb/arangodb#8239]
Hi,
I have implemented the functionality in js and registered the function for my use case. 
Functionality.
```
IGNORE({a: 1, b: 2, c: 3, d: 4}, ["a"]) -> {b:2, c:3, d: 4}
```
But for faster execution it has to be implemented in C++ functions.
I request you to add the same.

Thanks,
Dilip Vamsi.

**Comment by dothebart** [comment]
Hi, can you share a documentation, what its intended to do along the lines of https://docs.arangodb.com/3.4/AQL/Functions/Document.html#merge
Plus your current implementation?

**Comment by dilipvamsi** [comment]
```
IGNORE(document, attributeName1, attributeName2, ... attributeNameN) → doc
```
Ignore only the attributes attributeName to attributeNameN of document. All other attributes will be only present in the result.
- document (object): a document / object
- attributeNames (string, repeatable): an arbitrary number of attribute names as multiple arguments
- returns doc (object): a document without the specified attributes on the top-level
```
IGNORE(doc, "firstname", "name", "likes")
```
```
IGNORE(document, attributeNameArray) → doc
```
- document (object): a document / object
- attributeNameArray (array): an array of attribute names as strings
- returns doc (object): a document without the specified attributes on the top-level
```
IGNORE(doc, [ "firstname", "name", "likes" ])
```

**Comment by Simran-B** [comment]
The opposite of KEEP() is [UNSET()](https://docs.arangodb.com/3.4/AQL/Functions/Document.html#unset):

```js
RETURN UNSET({a: 1, b: 2, c: 3, d: 4}, ["a"]) //-> {b: 2, c: 3, d: 4}
```

**Comment by Simran-B** [comment]
I opened a PR: https://github.com/arangodb/arangodb/pull/8242/files
