### ISSUE TITLE
 cluster internal HTTP connection broken

### ISSUE THREAD

**Issue by HongHuangNeu** [arangodb/arangodb#8266]
## My Environment

* __ArangoDB Version__:      3.3.16
* __Storage Engine__:             RocksDB 
* __Deployment Mode__:        Cluster 
* __Deployment Strategy__:    Manual Start 
* __Infrastructure__:               own
* __Operating System__:        rethat 7.2
* __Total RAM in your machine__:        512G x 3        
* __Used Package__:           RedHat .rpm

## Component, Query & Data

__AQL query (if applicable)__:
```
WITH tv_equipment, tv_qmd_clt_feature, tv_paymentnumber, tv_promoter, tv_channal, tv_user, tv_company, tv_office, tv_address, tv_school, tv_wifi, tv_cardnumber, tv_email, tv_n_user, tv_telnumber
FOR start IN ['tv_user/B59C67BF196A4758191E42F76670CEBA']
FOR v,e,p IN 1..3
ANY start
te_legal_person, te_key_person, te_invest, te_office, te_address, te_email_own, te_promotion, te_card_own, te_telnumber_own, te_contacts, te_recommend, te_srct, te_hj, te_jfcq, te_jfym, te_task, te_graduate, te_list, te_login_summary, te_wifi_connect_summary, te_payment_summary, te_transfer_summary, te_order_person_summary, te_order_address_summary, te_repayment_summary, te_recharge_summary, te_called_summary, te_bound_summary, te_address_dm, te_email_dm, te_office_dm, te_repayment_dm, te_band_dm, te_login_dm, te_wifi_dm, te_recharge_dm, te_order_adr_dm, te_paynbr_dm, te_transfer_dm, te_called_dm
options {bfs:true,uniqueVertices:'path'}

LET newEdges=p.edges[
* FILTER true AND SUBSTRING(CURRENT._id, 0, FIND_FIRST(CURRENT._id, '/')) IN ['te_address_dm', 'te_promotion', 'te_hj', 'te_srct', 'te_key_person', 'te_graduate', 'te_email_dm', 'te_transfer_summary', 'te_jfym', 'te_recharge_summary', 'te_address', 'te_office', 'te_contacts', 'te_task', 'te_order_person_summary', 'te_called_dm', 'te_telnumber_own', 'te_repayment_summary', 'te_order_address_summary', 'te_paynbr_dm', 'te_bound_summary', 'te_wifi_connect_summary', 'te_recommend', 'te_jfcq', 'te_card_own', 'te_login_summary', 'te_payment_summary', 'te_called_summary', 'te_repayment_dm', 'te_legal_person', 'te_recharge_dm', 'te_transfer_dm', 'te_wifi_dm', 'te_order_adr_dm', 'te_list', 'te_email_own', 'te_office_dm', 'te_invest', 'te_band_dm', 'te_login_dm'] AND ((SUBSTRING(CURRENT._from, 0, FIND_FIRST(CURRENT._from, '/')) IN ['tv_qmd_clt_feature', 'tv_equipment', 'tv_paymentnumber', 'tv_channal', 'tv_promoter', 'tv_user', 'tv_company', 'tv_office', 'tv_address', 'tv_school', 'tv_wifi', 'tv_cardnumber', 'tv_email', 'tv_n_user', 'tv_telnumber']) or (CURRENT._from in ['tv_user/B59C67BF196A4758191E42F76670CEBA']))  AND ((SUBSTRING(CURRENT._to, 0, FIND_FIRST(CURRENT._to, '/')) IN ['tv_qmd_clt_feature', 'tv_equipment', 'tv_paymentnumber', 'tv_channal', 'tv_promoter', 'tv_user', 'tv_company', 'tv_office', 'tv_address', 'tv_school', 'tv_wifi', 'tv_cardnumber', 'tv_email', 'tv_n_user', 'tv_telnumber']) or (CURRENT._to in ['tv_user/B59C67BF196A4758191E42F76670CEBA'])) 
return CURRENT
]
FILTER LENGTH(newEdges) > 0 AND LENGTH(newEdges) == LENGTH(p.edges)
LIMIT 0, 2000
RETURN p

```
__Dataset__:
This data set contains 10billion edges and 1 billion nodes

__Replication Factor & Number of Shards (Cluster only)__: 1

## Steps to reproduce
run the query

__Problem__:
AQL: cluster internal HTTP connection broken. error code 1456
__Expected result__:
successfully perform shortest path query

**Comment by goedderz** [comment]
Hi @HongHuangNeu!

First, can you please confirm or refute the following. You wrote
> AQL: cluster internal HTTP connection broken. error code 1456

, but the error _cluster internal HTTP connection broken_ has the error code *1465*, not *1456*. I assume that this is just a typo, and you actually get the latter error code.

This error occurs when the network connection is broken for some reason during the query. Have you inspected the logs of all DBServers and the Coordinator the query was run on, and can you maybe provide them (the time around when the query ran should suffice, and I'd need to know when approximately the query was run if possible). Also it would be good to know if you have anything set up in the network that might be causing issues - a firewall or a proxy between the servers, for example.

A side node on the query: The FILTER condition looks redundant to me. And if it isn't, it can in the current form not be used in the Traversal for an early abort, but will only be used as a post filter, thus enumerating all paths up to depth 3 first, and filtering them after. If you expect or need an early pruning of your traversal, we shouldn't discuss this here, but feel free to contact us in our community slack https://slack.arangodb.com/ in \#aql.

Kind regards

Tobias

**Comment by yangyijun1990** [comment]
hi，@goedderz ！
Here are the main error messages：
2019-02-26T08:26:20Z [118273] ERROR {cluster} ClusterComm::performRequests: got no answer from server:PRMR-8b7ad7c1-87dd-452a-b5ff-2f27d4bd8981:/_db/xxx/_internal/traverser/edge/403889606 with status timeout

2019-02-26T10:48:36Z [118273] WARNING {queries} slow query: 'WITH tv_user, tv_n_user, tv_company, tv_address, tv_email, tv_promoter, tv_equipment, tv_wifi, tv_paymentnumber, tv_cardnumber, tv_telnumber, tv_school, tv_office, tv_channal, tv_qmd_clt_feature\nFOR start IN ['tv_user/0994C3354BD125F1074A68A9E22443C3']\nFOR v,e,p IN 1..3\nANY start\nte_legal_person, te_key_person, te_invest, te_office, te_address, te_email_own, te_promotion, te_card_own, te_telnumber_own, te_contacts, te_recommend, te_graduate, te_list, te_login_summary, te_wifi_connect_summary, te_payment_summary, te_transfer_summary, te_order_person_summary, te_order_address_summary, te_repayment_summary, te_recharge_summary, te_called_summary, te_bound_summary, te_hj_summary, te_srct_summary, te_task_summary, te_transfer_summary_v1, te_jfcq_summary, te_jfym_summary, te_address_dm, te_email_dm, te_office_dm, te_repayment_dm, te_band_dm, te_login_dm, te_wifi_dm, te_recharge_dm, te_tel_dm, te_order_adr_dm, te_paynbr_dm, te_classmate_dm, te_transfer_dm, te_control_dm, te_persons_acting_in_concert_dm, te_called_dm, te_repayment_person_dm, te_qs_score_dm, te_transfer_dm_v1\noptions {bfs:true,uniqueVertices:'path'}\n\nFILTER LAST(p.vertices)._id IN ['tv_user/E432D38855A823177E7BA611709E44CD']\nLET newEdges=p.edges[\n* FILTER true AND SUBSTRING(CURRENT._id, 0, FIND_FIRST(CURRENT._id, '/')) IN ['te_address_dm', 'te_promotion', 'te_persons_acting_in_concert_dm', 'te_key_person', 'te_graduate', 'te_email_dm', 'te_transfer_summary', 'te_qs_score_dm', 'te_recharge_summary', 'te_tel_dm', 'te_address', 'te_office', 'te_classmate_dm', 'te_contacts', 'te_order_person_summary', 'te_called_dm', 'te_telnumber_own', 'te_repayment_summary', 'te_order_address_summary', 'te_paynbr_dm', 'te_bound_summary', 'te_task_summary', 'te_wifi_connect_summary', 'te_recommend', 'te_hj_summary', 'te_card_own', 'te_login_summary', 'te_payment_summary', 'te_called_summary', 'te_transfer_dm_v1', 'te_repayment_dm', 'te_control_dm', 'te_legal_person', 'te_jfym_summary', 'te_recharge_dm', 'te_transfer_dm', 'te_wifi_dm', 'te_repayment_person_dm', 'te_jfcq_summary', 'te_order_adr_dm', 'te_list', 'te_srct_summary', 'te_email_own', 'te_office_dm', 'te_invest', 'te_band_dm', 'te_transfer_summary_v1', 'te_login_dm'] AND ((SUBSTRING(CURRENT._from, 0, FIND_FIRST(CURRENT._from, '/')) IN ['tv_equipment', 'tv_paymentnumber', 'tv_channal', 'tv_promoter', 'tv_user', 'tv_company', 'tv_office', 'tv_address', 'tv_school', 'tv_wifi', 'tv_cardnumber', 'tv_email', 'tv_n_user', 'tv_telnumber']) or (CURRENT._from in ['tv_user/E432D38855A823177E7BA611709E44CD','tv_user/0994C3354BD125F1074A68A9E22443C3']))  AND ((SUBSTRING(CURRENT._to, 0, FIND_FIRST(CURRENT._to, '/')) IN ['tv_equipment', 'tv_paymentnumber', 'tv_channal', 'tv_promoter', 'tv_user', 'tv_company', 'tv_office', 'tv_address', 'tv_school', 'tv_wifi', 'tv_cardnumber', 'tv_email', 'tv_n_user', 'tv_telnumber']) or (CURRENT._to in ['tv_user/E432D38855A823177E7BA611709E44CD','tv_user/0994C3354BD125F1074A68A9E22443C3'])) \nreturn CURRENT\n]\n\nFILTER LENGTH(newEdges) > 0 AND LENGTH(newEdges) == LENGTH(p.edges)\nLIMIT 0, 2000\n\nRETURN p', took: 4701.824597 s

**Comment by Simran-B** [comment]
Formatted:

```js
WITH
    tv_user,
    tv_n_user,
    tv_company,
    tv_address,
    tv_email,
    tv_promoter,
    tv_equipment,
    tv_wifi,
    tv_paymentnumber,
    tv_cardnumber,
    tv_telnumber,
    tv_school,
    tv_office,
    tv_channal,
    tv_qmd_clt_feature

FOR start IN ['tv_user/0994C3354BD125F1074A68A9E22443C3']
    FOR v,e,p IN 1..3 ANY start
      te_legal_person,
      te_key_person,
      te_invest,
      te_office,
      te_address,
      te_email_own,
      te_promotion,
      te_card_own,
      te_telnumber_own,
      te_contacts,
      te_recommend,
      te_graduate,
      te_list,
      te_login_summary,
      te_wifi_connect_summary,
      te_payment_summary,
      te_transfer_summary,
      te_order_person_summary,
      te_order_address_summary,
      te_repayment_summary,
      te_recharge_summary,
      te_called_summary,
      te_bound_summary,
      te_hj_summary,
      te_srct_summary,
      te_task_summary,
      te_transfer_summary_v1,
      te_jfcq_summary,
      te_jfym_summary,
      te_address_dm,
      te_email_dm,
      te_office_dm,
      te_repayment_dm,
      te_band_dm,
      te_login_dm,
      te_wifi_dm,
      te_recharge_dm,
      te_tel_dm,
      te_order_adr_dm,
      te_paynbr_dm,
      te_classmate_dm,
      te_transfer_dm,
      te_control_dm,
      te_persons_acting_in_concert_dm,
      te_called_dm,
      te_repayment_person_dm,
      te_qs_score_dm,
      te_transfer_dm_v1
    OPTIONS { bfs: true, uniqueVertices: 'path' }

        FILTER LAST(p.vertices)._id IN ['tv_user/E432D38855A823177E7BA611709E44CD']
        LET newEdges=p.edges[* FILTER true AND SUBSTRING(
          CURRENT._id, 0, FIND_FIRST(CURRENT._id, '/')
        ) IN [
          'te_address_dm',
          'te_promotion',
          'te_persons_acting_in_concert_dm',
          'te_key_person',
          'te_graduate',
          'te_email_dm',
          'te_transfer_summary',
          'te_qs_score_dm',
          'te_recharge_summary',
          'te_tel_dm',
          'te_address',
          'te_office',
          'te_classmate_dm',
          'te_contacts',
          'te_order_person_summary',
          'te_called_dm',
          'te_telnumber_own',
          'te_repayment_summary',
          'te_order_address_summary',
          'te_paynbr_dm',
          'te_bound_summary',
          'te_task_summary',
          'te_wifi_connect_summary',
          'te_recommend',
          'te_hj_summary',
          'te_card_own',
          'te_login_summary',
          'te_payment_summary',
          'te_called_summary',
          'te_transfer_dm_v1',
          'te_repayment_dm',
          'te_control_dm',
          'te_legal_person',
          'te_jfym_summary',
          'te_recharge_dm',
          'te_transfer_dm',
          'te_wifi_dm',
          'te_repayment_person_dm',
          'te_jfcq_summary',
          'te_order_adr_dm',
          'te_list',
          'te_srct_summary',
          'te_email_own',
          'te_office_dm',
          'te_invest',
          'te_band_dm',
          'te_transfer_summary_v1',
          'te_login_dm'
        ] AND ((SUBSTRING(CURRENT._from, 0, FIND_FIRST(CURRENT._from, '/')) IN [
          'tv_equipment',
          'tv_paymentnumber',
          'tv_channal',
          'tv_promoter',
          'tv_user',
          'tv_company',
          'tv_office',
          'tv_address',
          'tv_school',
          'tv_wifi',
          'tv_cardnumber',
          'tv_email',
          'tv_n_user',
          'tv_telnumber'
        ]) or (CURRENT._from in [
          'tv_user/E432D38855A823177E7BA611709E44CD',
          'tv_user/0994C3354BD125F1074A68A9E22443C3'
        ])) AND ((SUBSTRING(CURRENT._to, 0, FIND_FIRST(CURRENT._to, '/')) IN [
          'tv_equipment',
          'tv_paymentnumber',
          'tv_channal',
          'tv_promoter',
          'tv_user',
          'tv_company',
          'tv_office',
          'tv_address',
          'tv_school',
          'tv_wifi',
          'tv_cardnumber',
          'tv_email',
          'tv_n_user',
          'tv_telnumber'
        ]) or (CURRENT._to in [
          'tv_user/E432D38855A823177E7BA611709E44CD',
          'tv_user/0994C3354BD125F1074A68A9E22443C3'
        ]))
        RETURN CURRENT
    ]

FILTER LENGTH(newEdges) > 0 AND LENGTH(newEdges) == LENGTH(p.edges)
LIMIT 0, 2000

RETURN p
```

**Comment by Simran-B** [comment]
Instead of
`FILTER LAST(p.vertices)._id IN ['tv_user/E432D38855A823177E7BA611709E44CD']`
you could simply use the emitted `v` variable couldn't you?
`FILTER v._id == 'tv_user/E432D38855A823177E7BA611709E44CD'`

And this:
`SUBSTRING(<some._id>, 0, FIND_FIRST(<some>._id, '/') ) IN [ ... ]`
could be rewritten to:
`PARSE_IDENTIFIER(<some>).collection IN [...]`

I'm pretty sure that won't help with performance though. You wrote that replication factor and number of shards is 1, so there shouldn't be many network hops. Anyway, can you please post the execution plan as well as a query profile?

How many paths are there (1..3 ANY) starting at `tv_user/0994C3354BD125F1074A68A9E22443C3` in your dataset? Do I understand correctly that you want to find all paths between that starting vertex and `tv_user/E432D38855A823177E7BA611709E44CD` as end vertex? What are all the collection and ID restrictions for if nothing is returned in the case that newEdges is different from p.edges in the end?

**Comment by yangyijun1990** [comment]
**Function description：**
This is a full path query function,


**AQL:**
WITH tv_user, tv_n_user, tv_company, tv_address, tv_email, tv_promoter, tv_equipment, tv_wifi, tv_paymentnumber, tv_cardnumber, tv_telnumber, tv_school, tv_office, tv_channal, tv_qmd_clt_feature
FOR start IN ['tv_user/8050F8F134054EFDDF34A0E90B21FCB4']
FOR v,e,p IN 1..5
ANY start
te_legal_person, te_key_person, te_invest, te_office, te_address, te_email_own, te_promotion, te_card_own, te_telnumber_own, te_contacts, te_recommend, te_srct, te_hj, te_jfcq, te_jfym, te_task, te_graduate, te_list, te_login_summary, te_wifi_connect_summary, te_payment_summary, te_transfer_summary, te_order_person_summary, te_order_address_summary, te_repayment_summary, te_recharge_summary, te_called_summary, te_bound_summary, te_address_dm, te_email_dm, te_office_dm, te_repayment_dm, te_band_dm, te_login_dm, te_wifi_dm, te_recharge_dm, te_order_adr_dm, te_paynbr_dm, te_transfer_dm, te_called_dm
options {bfs:true,uniqueVertices:'path'}

FILTER v._id =='tv_user/B1501A9528A292585B7E90E8708143F1'
LET newEdges=p.edges[
* FILTER true 
AND ((PARSE_IDENTIFIER(CURRENT._from).collection IN ['tv_qmd_clt_feature', 'tv_equipment', 'tv_paymentnumber', 'tv_channal', 'tv_promoter', 'tv_user', 'tv_company', 'tv_office', 'tv_address', 'tv_school', 'tv_wifi', 'tv_cardnumber', 'tv_email', 'tv_n_user', 'tv_telnumber']) or (CURRENT._from in ['tv_user/B1501A9528A292585B7E90E8708143F1','tv_user/8050F8F134054EFDDF34A0E90B21FCB4']))  
AND ((PARSE_IDENTIFIER(CURRENT._to).collection IN ['tv_qmd_clt_feature', 'tv_equipment', 'tv_paymentnumber', 'tv_channal', 'tv_promoter', 'tv_user', 'tv_company', 'tv_office', 'tv_address', 'tv_school', 'tv_wifi', 'tv_cardnumber', 'tv_email', 'tv_n_user', 'tv_telnumber']) or (CURRENT._to in ['tv_user/B1501A9528A292585B7E90E8708143F1','tv_user/8050F8F134054EFDDF34A0E90B21FCB4'])) 
return CURRENT
]

FILTER LENGTH(newEdges) > 0 AND LENGTH(newEdges) == LENGTH(p.edges)
LIMIT 0,2000
return p

**Execution plan:**
 Query string:
 WITH tv_user, tv_n_user, tv_company, tv_address, tv_email, tv_promoter, tv_equipment, tv_wifi, 
 tv_paymentnumber, tv_cardnumber, tv_telnumber, tv_school, tv_office, tv_channal, tv_qmd_clt_feature
 FOR start IN ['tv_user/8050F8F134054EFDDF34A0E90B21FCB4']
 FOR v,e,p IN 1..5
 ANY start
 te_legal_person, te_key_person, te_invest, te_office, te_address, te_email_own, te_promotion, 
 te_card_own, te_telnumber_own, te_contacts, te_recommend, te_srct, te_hj, te_jfcq, te_jfym, te_task, 
 te_graduate, te_list, te_login_summary, te_wifi_connect_summary, te_payment_summary, 
 te_transfer_summary, te_order_person_summary, te_order_address_summary, te_repayment_summary, 
 te_recharge_summary, te_called_summary, te_bound_summary, te_address_dm, te_email_dm, te_office_dm, 
 te_repayment_dm, te_band_dm, te_login_dm, te_wifi_dm, te_recharge_dm, te_order_adr_dm, te_paynbr_dm, 
 te_transfer_dm, te_called_dm
 options {bfs:true,uniqueVertices:'path'}
 FILTER v._id =='tv_user/B1501A9528A292585B7E90E8708143F1'
 LET newEdges=p.edge...

Execution **plan:**
 Id   NodeType            Site                 Est.   Comment
  1   SingletonNode       COOR                    1   * ROOT
  2   CalculationNode     COOR                    1     - LET #7 = [ "tv_user/8050F8F134054EFDDF34A0E90B21FCB4" ]   /* json expression */   /* const assignment */
  3   EnumerateListNode   COOR                    1     - FOR start IN #7   /* list iteration */
  4   TraversalNode       COOR       16869854883232       - FOR v  /* vertex */, p  /* paths */ IN 1..5  /* min..maxPathDepth */ ANY start /* startnode */  te_legal_person, ANY te_key_person, ANY te_invest, ANY te_office, ANY te_address, ANY te_email_own, ANY te_promotion, ANY te_card_own, ANY te_telnumber_own, ANY te_contacts, ANY te_recommend, ANY te_srct, ANY te_hj, ANY te_jfcq, ANY te_jfym, ANY te_task, ANY te_graduate, ANY te_list, ANY te_login_summary, ANY te_wifi_connect_summary, ANY te_payment_summary, ANY te_transfer_summary, ANY te_order_person_summary, ANY te_order_address_summary, ANY te_repayment_summary, ANY te_recharge_summary, ANY te_called_summary, ANY te_bound_summary, ANY te_address_dm, ANY te_email_dm, ANY te_office_dm, ANY te_repayment_dm, ANY te_band_dm, ANY te_login_dm, ANY te_wifi_dm, ANY te_recharge_dm, ANY te_order_adr_dm, ANY te_paynbr_dm, ANY te_transfer_dm, ANY te_called_dm
  5   CalculationNode     COOR       16869854883232       - LET #11 = (v.`_id` == "tv_user/B1501A9528A292585B7E90E8708143F1")   /* simple expression */
  6   FilterNode          COOR       16869854883232       - FILTER #11
  7   CalculationNode     COOR       16869854883232       - LET newEdges = p.`edges`[* FILTER (((PARSE_IDENTIFIER(#4_.`_from`).`collection` in [ "tv_address", "tv_cardnumber", "tv_channal", "tv_company", "tv_email", "tv_equipment", "tv_n_user", "tv_office", "tv_paymentnumber", "tv_promoter", "tv_qmd_clt_feature", "tv_school", "tv_telnumber", "tv_user", "tv_wifi" ]) || (#4_.`_from` in [ "tv_user/B1501A9528A292585B7E90E8708143F1", "tv_user/8050F8F134054EFDDF34A0E90B21FCB4" ])) && ((PARSE_IDENTIFIER(#4_.`_to`).`collection` in [ "tv_address", "tv_cardnumber", "tv_channal", "tv_company", "tv_email", "tv_equipment", "tv_n_user", "tv_office", "tv_paymentnumber", "tv_promoter", "tv_qmd_clt_feature", "tv_school", "tv_telnumber", "tv_user", "tv_wifi" ]) || (#4_.`_to` in [ "tv_user/B1501A9528A292585B7E90E8708143F1", "tv_user/8050F8F134054EFDDF34A0E90B21FCB4" ]))) RETURN  #4_]   /* simple expression */
  8   CalculationNode     COOR       16869854883232       - LET #13 = ((LENGTH(newEdges) > 0) && (LENGTH(newEdges) == LENGTH(p.`edges`)))   /* simple expression */
  9   FilterNode          COOR       16869854883232       - FILTER #13
 10   LimitNode           COOR                 2000       - LIMIT 0, 2000
 11   ReturnNode          COOR                 2000       - RETURN p

Indexes used:
 By   Type   Collection                 Unique   Sparse   Selectivity   Fields        Ranges
  4   edge   te_address                 false    false            n/a   [ `_to` ]     base INBOUND
  4   edge   te_address                 false    false            n/a   [ `_from` ]   base OUTBOUND
  4   edge   te_address_dm              false    false            n/a   [ `_to` ]     base INBOUND
  4   edge   te_address_dm              false    false            n/a   [ `_from` ]   base OUTBOUND
  4   edge   te_band_dm                 false    false            n/a   [ `_to` ]     base INBOUND
  4   edge   te_band_dm                 false    false            n/a   [ `_from` ]   base OUTBOUND
  4   edge   te_bound_summary           false    false            n/a   [ `_to` ]     base INBOUND
  4   edge   te_bound_summary           false    false            n/a   [ `_from` ]   base OUTBOUND
  4   edge   te_called_dm               false    false            n/a   [ `_to` ]     base INBOUND
  4   edge   te_called_dm               false    false            n/a   [ `_from` ]   base OUTBOUND
  4   edge   te_called_summary          false    false            n/a   [ `_to` ]     base INBOUND
  4   edge   te_called_summary          false    false            n/a   [ `_from` ]   base OUTBOUND
  4   edge   te_card_own                false    false            n/a   [ `_to` ]     base INBOUND
  4   edge   te_card_own                false    false            n/a   [ `_from` ]   base OUTBOUND
  4   edge   te_contacts                false    false            n/a   [ `_to` ]     base INBOUND
  4   edge   te_contacts                false    false            n/a   [ `_from` ]   base OUTBOUND
  4   edge   te_email_dm                false    false            n/a   [ `_to` ]     base INBOUND
  4   edge   te_email_dm                false    false            n/a   [ `_from` ]   base OUTBOUND
  4   edge   te_email_own               false    false            n/a   [ `_to` ]     base INBOUND
  4   edge   te_email_own               false    false            n/a   [ `_from` ]   base OUTBOUND
  4   edge   te_graduate                false    false            n/a   [ `_to` ]     base INBOUND
  4   edge   te_graduate                false    false            n/a   [ `_from` ]   base OUTBOUND
  4   edge   te_hj                      false    false            n/a   [ `_to` ]     base INBOUND
  4   edge   te_hj                      false    false            n/a   [ `_from` ]   base OUTBOUND
  4   edge   te_invest                  false    false            n/a   [ `_to` ]     base INBOUND
  4   edge   te_invest                  false    false            n/a   [ `_from` ]   base OUTBOUND
  4   edge   te_jfcq                    false    false            n/a   [ `_to` ]     base INBOUND
  4   edge   te_jfcq                    false    false            n/a   [ `_from` ]   base OUTBOUND
  4   edge   te_jfym                    false    false            n/a   [ `_to` ]     base INBOUND
  4   edge   te_jfym                    false    false            n/a   [ `_from` ]   base OUTBOUND
  4   edge   te_key_person              false    false            n/a   [ `_to` ]     base INBOUND
  4   edge   te_key_person              false    false            n/a   [ `_from` ]   base OUTBOUND
  4   edge   te_legal_person            false    false            n/a   [ `_to` ]     base INBOUND
  4   edge   te_legal_person            false    false            n/a   [ `_from` ]   base OUTBOUND
  4   edge   te_list                    false    false            n/a   [ `_to` ]     base INBOUND
  4   edge   te_list                    false    false            n/a   [ `_from` ]   base OUTBOUND
  4   edge   te_login_dm                false    false            n/a   [ `_to` ]     base INBOUND
  4   edge   te_login_dm                false    false            n/a   [ `_from` ]   base OUTBOUND
  4   edge   te_login_summary           false    false            n/a   [ `_to` ]     base INBOUND
  4   edge   te_login_summary           false    false            n/a   [ `_from` ]   base OUTBOUND
  4   edge   te_office                  false    false            n/a   [ `_to` ]     base INBOUND
  4   edge   te_office                  false    false            n/a   [ `_from` ]   base OUTBOUND
  4   edge   te_office_dm               false    false            n/a   [ `_to` ]     base INBOUND
  4   edge   te_office_dm               false    false            n/a   [ `_from` ]   base OUTBOUND
  4   edge   te_order_address_summary   false    false            n/a   [ `_to` ]     base INBOUND
  4   edge   te_order_address_summary   false    false            n/a   [ `_from` ]   base OUTBOUND
  4   edge   te_order_adr_dm            false    false            n/a   [ `_to` ]     base INBOUND
  4   edge   te_order_adr_dm            false    false            n/a   [ `_from` ]   base OUTBOUND
  4   edge   te_order_person_summary    false    false            n/a   [ `_to` ]     base INBOUND
  4   edge   te_order_person_summary    false    false            n/a   [ `_from` ]   base OUTBOUND
  4   edge   te_payment_summary         false    false            n/a   [ `_to` ]     base INBOUND
  4   edge   te_payment_summary         false    false            n/a   [ `_from` ]   base OUTBOUND
  4   edge   te_paynbr_dm               false    false            n/a   [ `_to` ]     base INBOUND
  4   edge   te_paynbr_dm               false    false            n/a   [ `_from` ]   base OUTBOUND
  4   edge   te_promotion               false    false            n/a   [ `_to` ]     base INBOUND
  4   edge   te_promotion               false    false            n/a   [ `_from` ]   base OUTBOUND
  4   edge   te_recharge_dm             false    false            n/a   [ `_to` ]     base INBOUND
  4   edge   te_recharge_dm             false    false            n/a   [ `_from` ]   base OUTBOUND
  4   edge   te_recharge_summary        false    false            n/a   [ `_to` ]     base INBOUND
  4   edge   te_recharge_summary        false    false            n/a   [ `_from` ]   base OUTBOUND
  4   edge   te_recommend               false    false            n/a   [ `_to` ]     base INBOUND
  4   edge   te_recommend               false    false            n/a   [ `_from` ]   base OUTBOUND
  4   edge   te_repayment_dm            false    false            n/a   [ `_to` ]     base INBOUND
  4   edge   te_repayment_dm            false    false            n/a   [ `_from` ]   base OUTBOUND
  4   edge   te_repayment_summary       false    false            n/a   [ `_to` ]     base INBOUND
  4   edge   te_repayment_summary       false    false            n/a   [ `_from` ]   base OUTBOUND
  4   edge   te_srct                    false    false            n/a   [ `_to` ]     base INBOUND
  4   edge   te_srct                    false    false            n/a   [ `_from` ]   base OUTBOUND
  4   edge   te_task                    false    false            n/a   [ `_to` ]     base INBOUND
  4   edge   te_task                    false    false            n/a   [ `_from` ]   base OUTBOUND
  4   edge   te_telnumber_own           false    false            n/a   [ `_to` ]     base INBOUND
  4   edge   te_telnumber_own           false    false            n/a   [ `_from` ]   base OUTBOUND
  4   edge   te_transfer_dm             false    false            n/a   [ `_to` ]     base INBOUND
  4   edge   te_transfer_dm             false    false            n/a   [ `_from` ]   base OUTBOUND
  4   edge   te_transfer_summary        false    false            n/a   [ `_to` ]     base INBOUND
  4   edge   te_transfer_summary        false    false            n/a   [ `_from` ]   base OUTBOUND
  4   edge   te_wifi_connect_summary    false    false            n/a   [ `_to` ]     base INBOUND
  4   edge   te_wifi_connect_summary    false    false            n/a   [ `_from` ]   base OUTBOUND
  4   edge   te_wifi_dm                 false    false            n/a   [ `_to` ]     base INBOUND
  4   edge   te_wifi_dm                 false    false            n/a   [ `_from` ]   base OUTBOUND

Traversals on graphs:
 Id   Depth   Vertex collections   Edge collections                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Options                                              Filter conditions
  4   1..5                         te_legal_person, te_key_person, te_invest, te_office, te_address, te_email_own, te_promotion, te_card_own, te_telnumber_own, te_contacts, te_recommend, te_srct, te_hj, te_jfcq, te_jfym, te_task, te_graduate, te_list, te_login_summary, te_wifi_connect_summary, te_payment_summary, te_transfer_summary, te_order_person_summary, te_order_address_summary, te_repayment_summary, te_recharge_summary, te_called_summary, te_bound_summary, te_address_dm, te_email_dm, te_office_dm, te_repayment_dm, te_band_dm, te_login_dm, te_wifi_dm, te_recharge_dm, te_order_adr_dm, te_paynbr_dm, te_transfer_dm, te_called_dm   bfs: true, uniqueVertices: path, uniqueEdges: path   

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   move-calculations-up-2
  4   move-filters-up-2
  5   optimize-traversals

**Comment by yangyijun1990** [comment]
**Current problem description:**
Can't make full use of cup resources when querying。
Currently, the server CPU is 56 cores, but only one core is used to reach 100%, and the remaining 55 cores are not more than 3%.

Are there any parameters to set cup for Arango queries？

**Comment by yangyijun1990** [comment]
Hello! I have the following questions to consult:
    1. do you have an enterprise version?
    2. Is there a customer service phone for consultation?
    3. If there is an enterprise edition, is there any technical support for purchasing your enterprise edition?
    4. Do you have a technical team in China?

**Comment by dothebart** [comment]
As ArangoDB 3.3 is EOLed now, closing this as out of date. 

Please note that [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) is available for download.
