### ISSUE TITLE
Gracefully handling out of file handles situation.

### ISSUE THREAD

**Issue by calebcase** [arangodb/arangodb#827]
During stress testing with >100 concurrent connections Arango ran out of file handles dumping these messages into the log:

```
Warning	2014-04-16 19:11:42	accept failed with 24 (Too many open files)
Error	2014-04-16 19:11:42	too many accept failures, stopping logging
```

After this requests respond with this error (in one failure run):

```json
$ curl -X POST -d '{"foo": "bar"}' 'http://localhost:8529/_api/document?collection=benchmark'; echo
{"error":true,"errorMessage":"failed with error: no journal","code":500,"errorNum":4}
```

And this in another:

```json
{"error":true,"errorMessage":"failed with error: could not shape document","code":500,"errorNum":4}
```

At this point arangodb is unusable and has to be restarted.

I've worked around this by increasing the open file limit, but it would be better if Arango handled this situation more gracefully (and recovered when the number of connections went back down).

**Comment by dothebart** [comment]
With ArangoDB 3.0 the whole storage backend has been replacing shaped json with velocypack.
In general we need ~3 file descriptors per collection (maybe more with lots of writes), which should be taken into account when dimensioning the system.

I will therefore close this now.

ArangoDB RC2 is available for download via: https://www.arangodb.com/download-preview/
