### ISSUE TITLE
AQL: RANGE() function rounds start and stop values down to integer 

### ISSUE THREAD

**Issue by Simran-B** [arangodb/arangodb#8296]
_Noted by Karsten Gerber in Community Slack:_

## Component, Query & Data

__Affected feature__:
AQL

__AQL query (if applicable)__:

```js
RETURN RANGE(1.5, 2.5)
```

__AQL explain (if applicable)__:

```js
Query String:
 RETURN RANGE(1.5, 2.5)

Execution plan:
 Id   NodeType          Est.   Comment
  1   SingletonNode        1   * ROOT
  2   CalculationNode      1     - LET #0 = [ 1, 2 ]   /* json expression */   /* const assignment */
  3   ReturnNode           1     - RETURN #0

Indexes used:
 none

Optimization rules applied:
 none
```

## Steps to reproduce

1. Explain or run the query `RETURN RANGE( 1.5, 2.5 )`
2. In the execution this is already changed to `[1, 2]` and hence also the result of the query
3. As per the [documentation](https://docs.arangodb.com/3.4/AQL/Functions/Numeric.html#range), one would expect that the default step size of 1.0 is used, and thus `[1.5, 2.5]` as result.
4. Note that if you set the step size explicitly like `RETURN RANGE( 1.5, 2.5, 1.0 )`, then the execution plan / result is as expected

__Problem__:
It is unexpected that a default step size of 1.0 is different to a user-defined step size of 1.0 in the execution plan and query result.

__Expected result__:
`[ 1.5, 2.5 ]` (or the documentation needs to be changed to reflect what will actually happen)

**Comment by jsteemann** [comment]
Ranges are internally presented using two integer bounds.
That means the lower and upper bound parameters will also be converted into integers.
The documentation has examples where this is different - I guess it is from an older version of ArangoDB when there, for technical reasons, always were two implementations of some AQL functions. The AQL RANGE function implemented in JavaScript actually didn't convert the input parameters to integers, so it behaved as stated in the documentation. However, the C++-based implementation always used integers, and as part of a cleanup we removed all redundant implementations of AQL functions in 3.3 and 3.4. Final result: we only got the C++-based variant left, and this uses two integers internally. We should adjust the documentation so it reflects the current behavior.

**Comment by Simran-B** [comment]
@jsteemann Do I understand correctly, that even if you supply 1.0 as step size, then the bounds are still integers internally, but you get floating point numbers as result? Or does the presence of the third argument use a different code path which uses floats (or rather doubles) for everything?

**Comment by Simran-B** [comment]
@jsteemann ping

**Comment by Simran-B** [comment]
Resolved by https://github.com/arangodb/arangodb/pull/8299
