### ISSUE TITLE
Failed to register a user defined function

### ISSUE THREAD

**Issue by alexyzhou** [arangodb/arangodb#8321]
## My Environment

* __ArangoDB Version__:        3.4.3
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   ArangoDB Starter
* __Configuration__:               
* __Infrastructure__:               AWS
* __Operating System__:        CentOS
* __Total RAM in your machine__:        32Gb
* __Disks in use__:        SSD
* __Used Package__:     

## Component, Query & Data

__Affected feature__:
Register UDF

__AQL query (if applicable)__:
var aqlfunctions = require("@arangodb/aql/functions");
function multiply(num_array) {
	return num_array.reduce((accumulated, current) => accumulated * current);
}
aqlfunctions.register("MULTIPLY", multiply, true);

__AQL explain (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. Open Arangosh
2. Execute the above query to register the UDF

__Problem__:
Arangosh complains:
JavaScript exception in file '/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js' at 99,7: ArangoError 9: '/_api/aqlfunction/MULTIPLY' not implemented
!      throw error;
!      ^
stacktrace: ArangoError: '/_api/aqlfunction/MULTIPLY' not implemented
    at Object.exports.checkRequestResult (/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js:97:21)
    at Object.registerFunction [as register] (/usr/share/arangodb3/js/client/modules/@arangodb/aql/functions.js:85:12)
    at <shell command>:1:14

__Expected result__:
can successfully register the function

**Comment by jsteemann** [comment]
I tried this from the ArangoShell (arangosh) with 3.4 in cluster mode, and I am getting the following error:
```
aqlfunctions.register("MULTIPLY", multiply, true);
JavaScript exception in file 'js/client/modules/@arangodb/arangosh.js' at 99,7: ArangoError 1580: error creating AQL user function: 'MULTIPLY' is not a valid name
!      throw error;
!      ^
stacktrace: ArangoError: error creating AQL user function: 'MULTIPLY' is not a valid name
    at Object.exports.checkRequestResult (js/client/modules/@arangodb/arangosh.js:97:21)
    at Object.registerFunction [as register] (js/client/modules/@arangodb/aql/functions.js:85:12)
    at <shell command>:1:14
```
(which is expected, because all user-defined functions must have a `::` somewhere in the name).

It should work when using something like `aqlfunctions.register("MYNAMESPACE::MULTIPLY", multiply, true);`.

Anyway, it would be interesting to see how you have managed to get a `not implemented` response here. How did you actually trigger this error? Are you using the arangosh as well?

**Comment by jsteemann** [comment]
I think I got it... Is it possible that you are trying to register the user-defined function on a DB server?
In this case the error will be "not implemented".

It is required to register user-defined functions on the coordinator servers only.

**Comment by alexyzhou** [comment]
Actually I figured it out as well. It turns out when I use the server address as TCP and use the wrong port, the arangosh will still work but failed to register the function. However when I switch to http and use the correct port, it works as a charm.

I will suggest if we can make it more obvious in the documentation. I didn't see the notes on the difference of TCP and http for that.

**Comment by alexyzhou** [comment]
Anyway thanks for your comments, it helps to clear my doubts

**Comment by Simran-B** [comment]
@alexyzhou so `tcp://<ip>:<port>` in arangosh to connect to a node and using the correct port results also in the error? Which ports did you connect and which nodes run on which port?

**Comment by alexyzhou** [comment]
nope, sorry I didn't make it very clear. We have two port: 8529 and 8530 when using ArangoDB Starter to start the cluster, and the two ports are related to coordinator and dbserver respectively.

Previously I am using 8530 to register the function and failed. After that I switched to 8529 and it worked. Previously I thought it is related to tcp/http protocol, but turns out it's only related to port.

My point is, it will be better if we can clearly specify the ports and their related components in ArangoDB Starter section, it will be better.

Thanks!

**Comment by Simran-B** [comment]
Here is a pull request: https://github.com/arangodb/arangodb/pull/8340/files
