### ISSUE TITLE
Why don't need passwd to log in when use web interface

### ISSUE THREAD

**Issue by wjx-git** [arangodb/arangodb#8347]
__Problem__:
In the case of cluster, when I use the Web Interface to log in the Database, I needn't to specify database name, user name and password, but I need these when use the arangosh.
In the case of  single instance, user name and password are need whether use the web interface or arangosh.

__Expected result__:
I want to know why in the case of cluster we don't need username and password? Isn't it easy to cause illegal intrusion?

**Comment by Simran-B** [comment]
Can you please share your configuration and details about the cluster setup? Is authentication disabled?

**Comment by wjx-git** [comment]
three machines:
192.168.52.132  master
192.168.52.131  slave1
192.168.52.134 slave2

* __ArangoDB Version__:        3.3.4
* __Storage Engine__:            RocksDB
* __Deployment Mode__:        Cluster | DC2DC
* __Deployment Strategy__:   ArangoDB Starter
* __Infrastructure__:               own 
* __Operating System__:        CentOS 7

start up master:
arangodb --starter.data-dir=master > master.log &
start up slave1:
arangodb --starter.data-dir=slave1 --starter.join 192.168.52.132:8528 > slave1.log &
start up slave2:
arangodb --starter.data-dir=slave2 --starter.join 192.168.52.132:8528 > slave2.log &

Then I enter http://192.168.52.132:8529 in the browser, and login in without entering a username and password. But when I log in through the arangosh with command: 
arangosh --server.endpoint tcp://192.168.52.132:8529
Then the terminal will prompt for the root password.
Why don't I need to enter any password when I log in through the web interface? I hope I need an authentication when I use the web interface to log in. How can I set it up?

**Comment by wjx-git** [comment]
> Can you please share your configuration and details about the cluster setup? Is authentication disabled?
> 
> Why arangosh prompts for a password was already explained here:
> [#4404 (comment)](https://github.com/arangodb/arangodb/issues/4404#issuecomment-470881122)

three machines:
192.168.52.132 master
192.168.52.131 slave1
192.168.52.134 slave2

ArangoDB Version: 3.3.4
Storage Engine: RocksDB
Deployment Mode: Cluster
Deployment Strategy: ArangoDB Starter
Infrastructure: own
Operating System: CentOS 7
start up master:
arangodb --starter.data-dir=master > master.log &
start up slave1:
arangodb --starter.data-dir=slave1 --starter.join 192.168.52.132:8528 > slave1.log &
start up slave2:
arangodb --starter.data-dir=slave2 --starter.join 192.168.52.132:8528 > slave2.log &

Then I enter http://192.168.52.132:8529 in the browser, and login in without entering a username and password. But when I log in through the arangosh with command:
arangosh --server.endpoint tcp://192.168.52.132:8529
Then the terminal will prompt for the root password.
Why don't I need to enter any password when I log in through the web interface? I hope I need an authentication when I use the web interface to log in like arangosh does. How can I set it up?

**Comment by wjx-git** [comment]
I think I have resolved it.
When we startup the cluster use the arangodb starter, we need add a option --auth.jwt-secret=path, where 'path' is the path of key file. So we should generate key file first.
I get the key file with below command in my master machine:
arangodb create jwt-secret --secret=jwtSecret
Then I copy it to others machine (slave1, slave2). At last, startup cluster:
start up master:
arangodb --auth.jwt-secret=/home/keyfile/jwtSecret --starter.data-dir=master
start up slave1:
arangodb --auth.jwt-secret=/home/keyfile/jwtSecret --starter.data-dir=slave1 --starter.join 192.168.52.132:8528
start up slave2:
arangodb --auth.jwt-secret=/home/keyfile/jwtSecret --starter.data-dir=slave2 --starter.join 192.168.52.132:8528

**Comment by yzho0907** [comment]
@wjx-git seems u have solved it by this approach but i did try the same way, the login is still not fixed, anything that i should try?

**Comment by wjx-git** [comment]
You should create a new data-dir.  The authentication is effective only you add the option --auth.jwt-secret=path, when the data-dir was first create.

**Comment by yzho0907** [comment]
@wjx-git thx for quick response!!
