### ISSUE TITLE
Need to make a customization in UI. Could you please point me to the frontend web-gui code?

### ISSUE THREAD

**Issue by komal-SkyNET** [arangodb/arangodb#8355]
When the users click on "edit" option on a graph node in the WEB GUI - I would like to disable certain fields from being edited in the document.

**Comment by dothebart** [comment]
Hi, 
the source can be found in `js/apps/system/_admin/aardvark/APP/` - 
https://github.com/arangodb/arangodb/blob/devel/README_maintainers.md#front-end-webui contains some hints how to build it.

**Comment by Simran-B** [comment]
You can also do `npm install` to install the dev-dependencies and `grunt deploy` to compile and bundle Aardvark.

Note that there are multiple ways a user may alter a document, even in the Web UI. It's possible to modify documents with AQL (QUERIES) or via the document API for instance (SUPPORT > Rest API). If you really want to stop users from editing certain fields, then they shouldn't be granted access to the Web UI nor the API. You could write a small Foxx service to validate the desired changes and only expose its endpoints to the users.

**Comment by dothebart** [comment]
@komal-SkyNET does that answer your question?

**Comment by komal-SkyNET** [comment]
Yes. Thank you. Closing the thread.
