### ISSUE TITLE
How to update a document with unique index (constraints)?

### ISSUE THREAD

**Issue by robert-zaremba** [arangodb/arangodb#8359]
How to properly update an ArangoDB document with unique index field?

## My Environment

* __ArangoDB Version__:        3.4.3
* __Storage Engine__:             RocksDB
* __Deployment Mode__:        Single Server
* __Infrastructure__:               localhost
* __Operating System__:        Fedora 29
* __Total RAM in your machine__:       16GB
* __Disks in use__:                   HDD
* __Used Package__:              official RPM

## more details

I posted the whole question and problem on StackOverflow:
https://stackoverflow.com/questions/54916765/how-to-properly-update-an-arangodb-document-with-unique-index-field

**Comment by dothebart** [comment]
Yes, you're right. This missbehaviour was introduced with ArangoDB3.4

**Comment by robert-zaremba** [comment]
Will this be updated? When? What's the proper way to handle this now (update an object with unique constraints)?

**Comment by dothebart** [comment]
yes, thats why I flagged it with 'bug'. The workaround should be clear from the stackoverflow issue? 3.4.4 won't contain a fix for this, its to late in the QA pipeline already.

**Comment by dothebart** [comment]
https://github.com/arangodb/arangodb/pull/8422 will fix this in 3.4 - if you want a fixed environment now, you may try to checkout the branch `bug-fix-3.4/arrayindex-unique-update` and compile your own arangod.

**Comment by maxkernbach** [comment]
Hi @robert-zaremba,

version 3.4.5, which includes a fix for this issue, has just been released.
Could you please give it a try?

The latest release is available in the [download section](https://www.arangodb.com/download-major/).

**Comment by maxkernbach** [comment]
Closing this issue as fixed. Updating an object with unique constraints works in 3.4.5.

Working `arangosh` example:

Create collection:
```
db._create('usersCollection')
[ArangoCollection 106, "usersCollection" (type document, status loaded)]
```

Add unique index:
```

db.usersCollection.ensureIndex({ type: "hash", fields: [ "emails[*]" ], unique: true, sparse: true })
{ 
  "deduplicate" : true, 
  "fields" : [ 
    "emails[*]" 
  ], 
  "id" : "usersCollection/517", 
  "isNewlyCreated" : true, 
  "selectivityEstimate" : 1, 
  "sparse" : true, 
  "type" : "hash", 
  "unique" : true, 
  "code" : 201 
}
```

Create document entry:
```
db.usersCollection.save({_key: "1", name: "A", emails: ["aa@aa.aa"]})
{ 
  "_id" : "usersCollection/1", 
  "_key" : "1", 
  "_rev" : "_Yi26PIa---" 
```

Add email in the "emails" field:
```
db.usersCollection.update("1", {emails: ["aa@aa.aa", "aa2@aa.aa"]})
{ 
  "_id" : "usersCollection/1", 
  "_key" : "1", 
  "_rev" : "_Yi27SlW--_", 
  "_oldRev" : "_Yi26PIa---" 
}
```

Inspect collection:
```
db.usersCollection.toArray()
[ 
  { 
    "_key" : "1", 
    "_id" : "usersCollection/1", 
    "_rev" : "_Yi27SlW--_", 
    "name" : "A", 
    "emails" : [ 
      "aa@aa.aa", 
      "aa2@aa.aa" 
    ] 
  } 
]
```

**Comment by robert-zaremba** [comment]
Thanks!
