### ISSUE TITLE
Permit to install foxx by dropping it on 'Add Service'

### ISSUE THREAD

**Issue by dothebart** [arangodb/arangodb#8366]
Currently one has to do: 

 - `Add Service`
 - `Upload`-tab
and only then may add a service to be installed

The need to click `install` after drag'n'dropping the service into the `Drag & Drop Files` are also seems unneccessary to me.

**Comment by ifcologne** [comment]
correct, but not a task that one does on a daily basis. 
Maybe you have accidentally dragged the wrong file here?
