### ISSUE TITLE
Arango performance on Windows vs Linux

### ISSUE THREAD

**Issue by not-sungard** [arangodb/arangodb#8373]
## My Environment

* __ArangoDB Version__:        3.4.2
* __Storage Engine__:             rocksdb
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               
* __Infrastructure__:               own
* __Operating System__:        Windows Server 2016 & RedHat Linux 7.6
* __Total RAM in your machine__:        256GB
* __Disks in use__:        SSD
* __Used Package__:    Official Windows installer &  RedHat .rpm

## Component, Query & Data

__Affected feature__:
Performance

## Steps to reproduce

0. Using identical sets of hardware
1. Run a scalability style test using Arango running on Linux
2. Repeat the test with Arango running on Windows
3. Compare the performance

__Problem__:

We are running a scalability test with 384 cores reading & writing to a single collection.
With Arango on Linux the test runs through in 10 minutes.
With Arango on Windows the test took 50 minutes and failed.
Numerous HTTP requests timed out (5 min timeout).

In the Windows Arango log there were many warnings such as these:
![adb_logs](https://user-images.githubusercontent.com/34069444/54133318-c3197580-440d-11e9-915c-8d1e18ee7b16.png)

No warnings in the Linux Arango logs.

__Expected result__:

We were expecting Linux to show a performance advantage, but not of this magnitude.
This look to be a problem with Arango on Windows rather than a simple difference in performance.

**Comment by dothebart** [comment]
Hi, 
can you share a bit more details on the test? maybe even the test itself so we can retry ourselves? 

On a general note, you can't simply repeat a benchmark with a similar load pattern that you did on linux and expect to behave similar on windows. It may well be that the system behaves much worse when overrun by the testcase, then when run at its regular maximum throughput. Since you describe that you have errors with the SUT not being able to follow your load pattern anymore, I guess this is the case. 

Please have a look at my blog post series in which I describe how to perform benchmarks and how to find out the maximum throughput of a specific system:
https://www.arangodb.com/2017/10/performance-analysis-pyarango-usage-scenarios/

**Comment by not-sungard** [comment]
Noted what you're saying about benchmarking and performance testing.

However, this isn't an attempt to benchmark, or even primarily about performance testing.
What we are primarily trying to look at is scalability and reliability/robustness under stress.
Performance, while interesting, wasn't our primary concern, it was the failure to complete the test successfully. I should have been more clear on that.
However, looking at the performance difference in this case seemed like it might be instructive in understanding that failure.

For completeness I should say we also ran this test with our data store being files on a fileserver (same hardware as the Arango servers). So we have:
```
Linux Arango: 10mins, succeeds
Fileserver: 53mins, succeeds
Windows Arango: 50mins, fails
```

(Note: we have throttling disabled on rocksdb for Windows to avoid the throttling bug on Windows. We will retry with throttling enabled once the fix to rocksdb in 3.4.4 is available.)

Our first question is whether what we observe with Arango on Windows is to be expected (is it really that bad) or do you think there is a problem that needs investigating?

Running the test yourselves may be quite onerous. The test is running an actuarial risk model on a (smallish, 24 node) compute grid. There would be quite a lot of installation and setup to replicate the environement. Maybe there is an easier way to try investigating first?

**Comment by dothebart** [comment]
Yes, which exactly I was going to stress out. The number of scenarios a system can handle without errors is what counts. Once you have parts of your tests waiting for each others, maybe one in error state the throughput may decline drastically, and you don't want that in production anyways. 

As it seems obvious the windows system can't handle the same load reliably as the linux one, the question is, how much can it handle? And the answer to that usually is found by increasing the load pattern in steps of a minute or more until the system starts to break. If you found a load that it can handle, you try a bit below for 10 minutes, and increase to the value you think it can handle - just to revalidate. Pick the stable load, run the full test.

with which OS on the fileserver? Windows also?

**Comment by not-sungard** [comment]
Yes, Windows on the fileserver.

**Comment by dothebart** [comment]
Trying to reproduce your observation, but fail. My approach:

Load Driver:
`Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz; Debian Buster`
executing to load the SUT:
`./bin/arangobench --requests 10000000   --test-case document --concurrency 128 --server.endpoint tcp://192.168.xxx:8529 --server.password '' --server.username root` 
connected to the SUT via gigabit ethernet.
SUT:
`AMD Ryzen Threadripper 1950X 16-Core Processor`; `ST4000VN008-2DR1` HDD; 64G Ram; ArangoDB 3.4.4 regular installation packages. From observations at least on windows the SUT was CPU-bound. 
  - `Linux version 4.19.0-2-amd64 Debian Buster`
```
Total number of operations: 10000000, runs: 1, keep alive: yes, async: no, batch size: 0, replication factor: 1, number of shards: 1, wait for sync: false, concurrency level (threads): 128
Test case: document, complexity: 1, database: '_system', collection: 'ArangoBenchmark'
Total request/response duration (sum of all threads): 21119.184631 s
Request/response duration (per thread): 164.993630 s
Time needed per operation: 0.000017 s
Time needed per operation per thread: 0.002134 s
Operations per second rate: 59986.795852
Elapsed time since start: 166.703353 s
```
 - `Windows 10 Pro`
```
Total number of operations: 10000000, runs: 1, keep alive: yes, async: no, batch size: 0, replication factor: 1, number of shards: 1, wait for sync: false, concurrency level (threads): 128
Test case: document, complexity: 1, database: '_system', collection: 'ArangoBenchmark'
Total request/response duration (sum of all threads): 21228.202220 s
Request/response duration (per thread): 165.845330 s
Time needed per operation: 0.000017 s
Time needed per operation per thread: 0.002135 s
Operations per second rate: 59951.764768
Elapsed time since start: 166.800761 s
```
which really took me by surprise, since windows is the same speed as linux on the first 3 digits. 

so please retry with a windows 10 whether you still see the same differences. 

If yes, we really need a better way to reproduce your usecase: 
 - how many collections are in the game?
 - what type of collections (edeg?)
 - which indices should be utilized? ArangoSearch? Geo? Hash?
 - whats the average document size on each collection?
 - which queries do you run?
 - writes? reads?

**Comment by not-sungard** [comment]
_how many collections are in the game?_
One
    
_what type of collections (edeg?)_
Document

_which indices should be utilized? ArangoSearch? Geo? Hash?_
Our indexes look like this:
![image](https://user-images.githubusercontent.com/34069444/54439980-bf4d6200-4731-11e9-9f61-cc28ee7b33ca.png)
Only "name" and "type" are required for all documnets.

A typical document looks like:
![image](https://user-images.githubusercontent.com/34069444/54440407-8661bd00-4732-11e9-92e3-ac5d42bef807.png)
"timestamp" is exactly what is says it is.
"data" is the main payload and is (mainly) arrays of double values that have been compressed and base64 encoded.
    
_whats the average document size on each collection?_
On the filesystem the data is ~7GB split over 78,673 files.
In the collection there are 100,135 documents (some types of documents are stored differently).
Because of the extra compression used for Arango docs the total size is expected to be smaller than filesystem, then Arango does its own compression on each document. We haven't measured what that ends up being. There isn't an average document size, some are quite small, other can be quite large. Looking on the filesystem a file size of 153K is fairly common.
   
_which queries do you run? writes? reads?_
I'll try and get back with this info. With some effort I can turn some logging on all the 384 cores then merge the logs to produce these figures.

**Comment by dothebart** [comment]
how does new data arive? is it frequent inserts or just batchs that arrive and are incooperated? 

Yes ArangoDB / Rocksdb uses snappy to compress the documents on disk on the fly.

**Comment by not-sungard** [comment]
It should be frequent inserts. This model looks to be almost exclusively one big monte-carlo simulation. As the vaules for each sim are calculated by a core they get written out. It doesn't even seem to be configured to do any stochastic analysis. So it may be almost pure writing (I'll find out later from the logs).

Something I ought to disclose: After seeing your figures earlier we are begining to have suspicions of our Windows installations as we are obliged to install "official corporate" builds of Windows. A couple of our folks have started an investigation on that front.

**Comment by not-sungard** [comment]
Here are combined figures from 368 of the cores when we reran this model (16 of the cores failed to log).

```
operation    + count + average (ms) + max (ms)
write        | 10872 |            0 |  6370
read         | 12196 |            0 |    40
query        |  1172 |            0 |  3220
delete       |     3 |          132 |   396
```

Note: in our statistics "query" includes HTTP HEAD requests as well as AQL queries.

It's the end of day/week here, I'll try and get a list of AQL queries used by the model on Monday.

**Comment by not-sungard** [comment]
Update: I don't think that AQL plays a big part in running this model. It only executes four AQL queries:

```
For doc IN @@collection
FILTER doc.type == "metaxml" && doc.run == null && doc.simulation == null && doc.nameEx == "prepData" && doc.grouping == null && doc.group == null && doc.loop == null && doc.chunk == null
REMOVE doc._key IN @@collection
```

```
For doc IN @@collection
FILTER doc.type == "polmap" && doc.run == null && doc.simulation == null && doc.nameEx == "prepData" && doc.grouping == null && doc.group == null && doc.loop == null && doc.chunk == null
REMOVE doc._key IN @@collection
```

```
For doc IN @@collection
FILTER doc.run == 100 && doc.nameEx == "interm"
REMOVE doc._key IN @@collection
```

```
For doc IN @@collection
FILTER doc.name == "BHF_SPIUL_run_info" && doc.type == "metaxml" && doc.run == 100
RETURN doc._key
```

**Comment by not-sungard** [comment]
Solved.

It appears that the terrible slowdown of ArangoDB on Windows was caused by corporate "crapware". Once we removed the worst of it we saw equivalent results for Linux and Windows.

Appologies for the bother, I'll close the issue now.

Thank you for your assistance.

**Comment by Simran-B** [comment]
Can you share the names so we and other users know what to look for or is it software exclusively used in your company that you can't tell about?

**Comment by not-sungard** [comment]
That's possible, but if I'm going to name names then I want to get the details right. The guys looking at this are still digging into those.

**Comment by dothebart** [comment]
Great, and thanks for sharing your insights.
