### ISSUE TITLE
Does CleanServer API move data from dead node?

### ISSUE THREAD

**Issue by Puneeth-Kadamba** [arangodb/arangodb#8384]
## My Environment

* __ArangoDB Version__:        3.4.2
* __Storage Engine__:              RocksDB 
* __Deployment Mode__:       Cluster 
* __Deployment Strategy__:    ArangoDB Starter
* __Configuration__:            3 nodes on the cluster. 3 db servers,3 agencies and 3 co-ordinators
* __Infrastructure__:               AWS 
* __Operating System__:       Ubuntu 16.04
* __Total RAM in your machine__:       32Gb
* __Disks in use__:      SSD

## Component, Query & Data

__Affected feature__:
Cluster Set up 

__Replication Factor & Number of Shards (Cluster only)__:
default settings

## Steps to reproduce

1. I have 3 nodes on the cluster.
2. Assume one of the node was unhealthy. We would remove that from the cluster and add new node.
3. Multiple questions in this scenario.
    What happens to the data in the dead node?
    How does it get moved into other nodes?
    sst files on the node will also be moved? Where is the actual data?
    https://docs.arangodb.com/3.4/Manual/Administration/Cluster/ 

The below documentation talks about cleaning. What actually happens in cleaning. Is there any chance of missing the data.
**_The clean way of removing a DBServer is to first releave it of all its responsibilities for shards. This applies to followers as well as leaders of shards. The requirement for this operation is that no collection in any of the databases has a relicationFactor greater or equal to the current number of DBServers minus one. For the pupose of cleaning out DBServer004 for example would work as follows, when issued to any Coordinator of the cluster:

curl <coord-ip:coord-port>/_admin/cluster/cleanOutServer -d '{"id":"DBServer004"}'

After the DBServer has been cleaned out, you will find a trash bin icon to the right of the name of the DBServer on any Coordinators' UI. Clicking on it will remove the DBServer in questiuon from the cluster._**

**Comment by Puneeth-Kadamba** [comment]
Hi Any Update?

**Comment by dothebart** [comment]
Its assumed that you have backups of the shards that the failed node has on one of the other db-servers - hence replication factor. 
Once you add a new DB-Server, shards get re-replicated into it.
