### ISSUE TITLE
I need at least the arangosh or better arangodump for ARM

### ISSUE THREAD

**Issue by Fruchtgummi** [arangodb/arangodb#8396]
## My Environment

* __ArangoDB Version__:        3.4

Why there is not any a standalone from arangosh for ARM or at all?

**Comment by dothebart** [comment]
Hi, 
we currently only offer unstable snapshots of ARM binaries via docker; see https://github.com/arangodb/arangodb-docker/issues/53 for more details.

**Comment by Fruchtgummi** [comment]
Ok...

For the future it would be interesting to outsource the shell. So that one could do the same for the administration of individual databases of a Pi ect.

**Comment by dothebart** [comment]
in general the shell only needs its binary, arangosh.conf, /usr/share/arangodb3/js/[client|common] - so you can steal it right away from the container.

**Comment by Fruchtgummi** [comment]
How I get the ARM-Version from Dockerhub? Tag?

**Comment by maxkernbach** [comment]
Hi @Fruchtgummi,

I am closing this issue as solved. As stated this is currently only possible with docker ARM binaries.
News regarding ARM support will be provided in https://github.com/arangodb/arangodb-docker/issues/53.

Please have a look at my reply in the linked issue.
