### ISSUE TITLE
Ubuntu 14.04 Support

### ISSUE THREAD

**Issue by galan** [arangodb/arangodb#841]
Hi,
there is no support for Ubuntu 14.04 yet. Trying to install the latest ArangoDB using the repository for 13.10 results in a missing dependency:

```
The following packages have unmet dependencies:
 arangodb : Depends: libicu48 (>= 4.8-1) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

I found a deb, but it seems like a hack: https://launchpad.net/ubuntu/trusty/amd64/libicu48/4.8.1.1-13+nmu1ubuntu1

However, in Ubuntu 14.04 libicu52 is already present, so the ArangoDB repository should reflect this.

**Comment by obadasemary** [comment]
not working with me

**Comment by jsteemann** [comment]
@obadasemary : what exactly is not working? can you provide any details?

**Comment by obadasemary** [comment]
when i run this on termenal : arangod
2015-02-10T12:23:05Z [11593] FATAL failed to create logfile '/var/log/arangodb/arangod.log'. Please check the path and permissions

**Comment by obadasemary** [comment]
if i run it by sudo 

obada@obada:~$ sudo arangod 
[sudo] password for obada: 
2015-02-10T12:25:30Z [11649] FATAL cannot start server: database directory is locked
More error details may be provided in the logfile '/var/log/arangodb/arangod.log'

**Comment by obadasemary** [comment]
v 2.0.9

**Comment by zdebeer99** [comment]
It could be that arango is already running, you can test it by opening the link http://localhost:8529/ in your browser.

**Comment by obadasemary** [comment]
yes it is work 
now 
thank you

**Comment by obadasemary** [comment]
:+1:
