### ISSUE TITLE
Arango db (version 3.3.16) crashes on a single node

### ISSUE THREAD

**Issue by SharadUnifyed** [arangodb/arangodb#8411]
## My Environment

* __ArangoDB Version__:        3.3.16
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start 
* __Configuration__:               
* __Infrastructure__:               AWS
* __Operating System__:        Ubuntu 16.04
* __Total RAM in your machine__:        32Gb
* 

Arango DB crashes frequently

**Comment by Simran-B** [comment]
What operations do you run when the crash occurs? Are there particular queries that cause it? What is written in the log files?

**Comment by dothebart** [comment]
Please note that 3.3.22 is available containing lots of bugfixes. Please upgrade and report back whether the error persists.

**Comment by SharadUnifyed** [comment]
Hi Team, we have upgraded to 3.3.22. The issues observed is due to the memory pile up for multiple executions of queries having joins across multiple collections and applying Sort over the result. Could you please suggest why sort is causing so much of memory pile up?

**Comment by Simran-B** [comment]
For a sort of all elements all these elements need to be in memory. This is also true even if you apply a LIMIT directly after the sort. An optimization to use less memory will become available in v3.5.0: https://www.arangodb.com/2019/03/sort-limit-optimization-aql/

**Comment by hksinsinwar** [comment]
Hi Team,

Adding to sorting I noticed a high CPU utilization. Please find the below pidstat for arangod service. Lot of cpu is consumed by shedulers. I don't know what are these schedulers and why these are consuming so much of CPUs.
This test involves sorting with limit and load is 100 concurrent request on single node.

Average:      UID      TGID       TID    %usr %system  %guest    %CPU   CPU  Command
Average:      999      5227         -  752.35   45.45    0.00  797.80     -  arangod
Average:      999         -      5227    0.00    0.00    0.00    0.00     -  |__arangod
Average:      999         -      5228    0.70    4.30    0.00    5.00     -  |__jemalloc_bg_thd
Average:      999         -      5229    0.00    0.10    0.00    0.10     -  |__Logging
Average:      999         -      5230    0.60    3.00    0.00    3.60     -  |__jemalloc_bg_thd
Average:      999         -      5233    0.00    0.00    0.00    0.00     -  |__SchedulerManage
Average:      999         -      5234    0.00    0.00    0.00    0.00     -  |__JobQueueThread
Average:      999         -      5235    0.00    0.00    0.00    0.00     -  |__CacheRebalancer
Average:      999         -      5236    0.00    0.00    0.00    0.00     -  |__rocksdb:bg0
Average:      999         -      5237    0.00    0.00    0.00    0.00     -  |__rocksdb:bg1
Average:      999         -      5238    0.00    0.00    0.00    0.00     -  |__rocksdb:bg2
Average:      999         -      5239    0.60    3.60    0.00    4.20     -  |__jemalloc_bg_thd
Average:      999         -      5240    0.00    0.00    0.00    0.00     -  |__rocksdb:bg3
Average:      999         -      5241    1.00    4.60    0.00    5.59     -  |__jemalloc_bg_thd
Average:      999         -      5242    0.00    0.00    0.00    0.00     -  |__rocksdb:bg0
Average:      999         -      5243    0.80    3.40    0.00    4.20     -  |__jemalloc_bg_thd
Average:      999         -      5244    0.00    0.00    0.00    0.00     -  |__rocksdb:bg1
Average:      999         -      5245    0.00    0.00    0.00    0.00     -  |__rocksdb:bg2
Average:      999         -      5246    0.20    2.00    0.00    2.20     -  |__jemalloc_bg_thd
Average:      999         -      5247    0.00    0.00    0.00    0.00     -  |__rocksdb:bg3
Average:      999         -      5248    0.90    4.10    0.00    5.00     -  |__jemalloc_bg_thd
Average:      999         -      5249    0.00    0.00    0.00    0.00     -  |__jemalloc_bg_thd
Average:      999         -      5250    0.00    0.00    0.00    0.00     -  |__rocksdb:bg4
Average:      999         -      5251    0.00    0.00    0.00    0.00     -  |__rocksdb:bg5
Average:      999         -      5368    0.80    0.00    0.00    0.80     -  |__RocksDBThread
Average:      999         -      5369    0.00    0.00    0.00    0.00     -  |__DatabaseManager
Average:      999         -      5370    0.00    0.00    0.00    0.00     -  |__V8 WorkerThread
Average:      999         -      5371    0.00    0.00    0.00    0.00     -  |__V8 WorkerThread
Average:      999         -      5372    0.00    0.00    0.00    0.00     -  |__V8 WorkerThread
Average:      999         -      5373    0.00    0.00    0.00    0.00     -  |__V8 WorkerThread
Average:      999         -      5374    0.00    0.00    0.00    0.00     -  |__V8 WorkerThread
Average:      999         -      5375    0.00    0.00    0.00    0.00     -  |__V8 WorkerThread
Average:      999         -      5376    0.00    0.00    0.00    0.00     -  |__V8 WorkerThread
Average:      999         -      5377    0.00    0.00    0.00    0.00     -  |__V8GarbageCollec
Average:      999         -      5378    0.00    0.00    0.00    0.00     -  |__Statistics
Average:      999         -     16120   10.79    0.50    0.00   11.29     -  |__Scheduler
Average:      999         -     16735   10.99    0.50    0.00   11.49     -  |__Scheduler
Average:      999         -     16738   11.09    0.60    0.00   11.69     -  |__Scheduler
Average:      999         -     16739   13.99    0.40    0.00   14.39     -  |__Scheduler
Average:      999         -     16744   10.59    0.40    0.00   10.99     -  |__Scheduler
Average:      999         -     16749   10.69    0.50    0.00   11.19     -  |__Scheduler
Average:      999         -     16753   14.89    0.40    0.00   15.28     -  |__Scheduler
Average:      999         -     16762   10.89    0.70    0.00   11.59     -  |__Scheduler
Average:      999         -     16763   11.59    0.50    0.00   12.09     -  |__Scheduler
Average:      999         -     16772   10.59    0.50    0.00   11.09     -  |__Scheduler
Average:      999         -     16883   11.59    0.10    0.00   11.69     -  |__Scheduler
Average:      999         -     16960   17.38    0.20    0.00   17.58     -  |__Scheduler
Average:      999         -     17096   10.79    0.10    0.00   10.89     -  |__Scheduler
Average:      999         -     17097   10.99    0.40    0.00   11.39     -  |__Scheduler
Average:      999         -     17098   11.59    0.50    0.00   12.09     -  |__Scheduler
Average:      999         -     17189   17.08    0.10    0.00   17.18     -  |__Scheduler
Average:      999         -     17616   10.79    0.30    0.00   11.09     -  |__Scheduler
Average:      999         -     17617   11.49    0.60    0.00   12.09     -  |__Scheduler
Average:      999         -     17801   10.29    0.50    0.00   10.79     -  |__Scheduler
Average:      999         -     17802   10.19    0.30    0.00   10.49     -  |__Scheduler
Average:      999         -     17991   10.59    0.70    0.00   11.29     -  |__Scheduler
Average:      999         -     17992   11.29    0.60    0.00   11.89     -  |__Scheduler
Average:      999         -     18863   11.39    0.50    0.00   11.89     -  |__Scheduler
Average:      999         -     18865    9.99    0.30    0.00   10.29     -  |__Scheduler
Average:      999         -     18866   11.09    0.50    0.00   11.59     -  |__Scheduler
Average:      999         -     18867   11.19    0.40    0.00   11.59     -  |__Scheduler
Average:      999         -     18868   18.18    0.00    0.00   18.18     -  |__Scheduler
Average:      999         -     18869   10.09    0.10    0.00   10.19     -  |__Scheduler
Average:      999         -     18870   12.19    0.10    0.00   12.29     -  |__Scheduler
Average:      999         -     18871   12.59    0.00    0.00   12.59     -  |__Scheduler
Average:      999         -     18872   14.49    0.00    0.00   14.49     -  |__Scheduler
Average:      999         -     18873   11.19    0.50    0.00   11.69     -  |__Scheduler
Average:      999         -     18921   11.09    0.40    0.00   11.49     -  |__Scheduler
Average:      999         -     18979   14.39    0.10    0.00   14.49     -  |__Scheduler
Average:      999         -     18980   11.39    0.50    0.00   11.89     -  |__Scheduler
Average:      999         -     18981   10.19    0.50    0.00   10.69     -  |__Scheduler
Average:      999         -     18982   10.49    0.50    0.00   10.99     -  |__Scheduler
Average:      999         -     18991   11.79    0.10    0.00   11.89     -  |__Scheduler
Average:      999         -     18994   10.39    0.00    0.00   10.39     -  |__Scheduler
Average:      999         -     18995   10.49    0.00    0.00   10.49     -  |__Scheduler
Average:      999         -     18996   10.99    0.10    0.00   11.09     -  |__Scheduler
Average:      999         -     18997   10.89    0.10    0.00   10.99     -  |__Scheduler
Average:      999         -     18998   10.39    0.40    0.00   10.79     -  |__Scheduler
Average:      999         -     18999   14.39    0.00    0.00   14.39     -  |__Scheduler
Average:      999         -     19003   10.29    0.80    0.00   11.09     -  |__Scheduler
Average:      999         -     19004   10.39    0.70    0.00   11.09     -  |__Scheduler
Average:      999         -     19005   12.09    0.30    0.00   12.39     -  |__Scheduler
Average:      999         -     19008   10.99    0.00    0.00   10.99     -  |__Scheduler
Average:      999         -     19012   10.29    0.90    0.00   11.19     -  |__Scheduler
Average:      999         -     19013   10.39    0.00    0.00   10.39     -  |__Scheduler
Average:      999         -     19014   10.09    0.50    0.00   10.59     -  |__Scheduler
Average:      999         -     19107   11.29    0.10    0.00   11.39     -  |__Scheduler
Average:      999         -     19323   11.79    0.10    0.00   11.89     -  |__Scheduler
Average:      999         -     19324   10.19    0.30    0.00   10.49     -  |__Scheduler
Average:      999         -     19325   15.28    0.40    0.00   15.68     -  |__Scheduler
Average:      999         -     19326   10.69    0.40    0.00   11.09     -  |__Scheduler
Average:      999         -     19408   10.89    0.30    0.00   11.19     -  |__Scheduler
Average:      999         -     19484   10.89    0.60    0.00   11.49     -  |__Scheduler
Average:      999         -     19512   10.79    0.40    0.00   11.19     -  |__Scheduler
Average:      999         -     19577   11.89    0.10    0.00   11.99     -  |__Scheduler
Average:      999         -     19781   10.59    0.20    0.00   10.79     -  |__Scheduler
Average:      999         -     19870   16.58    0.00    0.00   16.58     -  |__Scheduler
Average:      999         -     19954   12.29    0.00    0.00   12.29     -  |__Scheduler
Average:      999         -     20038    9.59    0.10    0.00    9.69     -  |__Scheduler

**Comment by dothebart** [comment]
Schedules do the actual work. 
Depending on what you do you should maybe move to arangodb 3.4 which contains lots of performance improvements.

Please also have a look at my blogpost series where I explain how to benchmark a system and howto measure the maximum possible throughput of a system:

https://www.arangodb.com/2017/09/performance-analysis-using-pyarango/
https://www.arangodb.com/2017/09/performance-analysis-pyarango-inspecting-transactions/
https://www.arangodb.com/2017/10/performance-analysis-pyarango-usage-scenarios/

You then need to detect which resources you run short of, so you can either improve your workload or get a bigger machine. Once the system is in an overrun state like you posted, these measurements aren't possible anymore.

**Comment by hksinsinwar** [comment]
May be I misunderstood terminology, workers or threads do work, These are reflecting as scheduler this is little bit confusing. I will give a look on articles you mentioned above.

**Comment by dothebart** [comment]
I also got that their name may be not the best - you probably wouldn't have asked for 'worker'-threads ;-)

**Comment by maxkernbach** [comment]
Hi @SharadUnifyed and @hksinsinwar,

could you please share a status update on this issue?

You might also want to test the latest Release Candidate of ArangoDB 3.5 since it includes the Sort-Limit Optimization in AQL. 

https://www.arangodb.com/download-technical-preview/
https://www.arangodb.com/2019/03/sort-limit-optimization-aql/

**Comment by maxkernbach** [comment]
Hi @SharadUnifyed and @hksinsinwar,

Since we have not heard back from you in a while, I am closing this issue for now.

In case you are still facing this issue and the 3.5 Sort-Limit Optimization AQL does not help you, please comment and we will reopen this ticket.
