### ISSUE TITLE
ArangoDB Foxx is significantly slower than Arangosh

### ISSUE THREAD

**Issue by alexyzhou** [arangodb/arangodb#8419]
## My Environment

* __ArangoDB Version__:        3.4.3
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   ArangoDB Starter
* __Configuration__:               8 Core, 32GB Nodes * 6
* __Infrastructure__:               AWS
* __Operating System__:        AWS AMI Latest
* __Total RAM in your machine__:        32GB
* __Disks in use__:        SSD
* __Used Package__:              SUSE or RedHat .rpm

## Component, Query & Data

__Affected feature__:
ArangoDB Foxx

__AQL query (if applicable)__:
I firstly wrote the query (which is a customized graph traversal) in arangosh, and here is the code:
```js
var traversal = require("org/arangodb/graph/traversal");
function clone (obj) {
    if (obj === null || typeof obj !== 'object') {
      return obj;
    }
    var copy;
    if (Array.isArray(obj)) {
      copy = [];
      obj.forEach(function (i) {
        copy.push(clone(i));
      });
    } else if (obj instanceof Object) {
      copy = { };
      Object.keys(obj).forEach(function (k) {
        copy[k] = clone(obj[k]);
      });
    }
    return copy;
}
var shareholderFilter = function(config, vertex, path) {
    const vertexCount = config.collectedVertices.size;
    config.collectedVertices.add(vertex._key);
    if (vertexCount > config.limit) {
        return [ 'exclude', 'prune' ];
    }
    return "";
};

var countVisitor = function(config, result, vertex, path) {
    if (!result || !result.visited) {
        return;
    }
    if (result.visited.vertices) {
        result.visited.vertices.add(vertex._id);
    }
    if (result.visited.paths) {
        result.visited.paths.push(clone(path));
    }
    return;
};

var shareholderExpander = function(config, vertex, path) {
    var connected = [];
    var datasource = config.datasource;
    const vertexCount = config.collectedVertices.size;
    config.collectedVertices.add(vertex._id);
    if (vertexCount > config.limit) {
        return [];
    }
    var totalHoldPct = path.edges.map(e => e.holdPct).reduce((a,b) => a*b, 1.0);
    var holdPctThreshold = 0.02;
    if (vertexCount < 5000) {
        holdPctThreshold = 0.005;
    } else if (vertexCount > 10000) {
        holdPctThreshold = 0.05;
    }
    if (totalHoldPct < holdPctThreshold) {
        return [];
    } else {
        datasource.getInEdges(vertex).filter(edge => edge.holdPct * totalHoldPct >= holdPctThreshold).forEach(edge => connected.push({ edge: edge, vertex: {_id: edge._from} }));
    }
    return connected;
}

var config = {
  datasource: traversal.collectionDatasourceFactory(db.mio_company_company),
  strategy: "breadthfirst",
  order: "postorder",
  uniqueness: {
    vertices: 'path',
    edges: 'path'
  },
  filter: shareholderFilter,
  expander: shareholderExpander,
  visitor: countVisitor,
  visitCount: 0,
  collectedVertices: new Set(),
//   collectedEdges: new Set(),
//   limit: 50000,
//   maxDepth: 5,
  buildVertices: false
};

var result = {
    visited: {
        vertices: new Set(),
        // edges: []
        paths: []
    }
};

var traverser = new traversal.Traverser(config);

function f() {
    console.time('traverse');
    traverser.traverse(result, db._document("mio_company/4ae148aa1faca8eb0541532566ba2106"))
    console.timeEnd('traverse');
}

f();
```

And based on the same code, I wrap it into a foxx service:
```js
'use strict';
const createRouter = require('@arangodb/foxx/router');
const traversal = require("org/arangodb/graph/traversal");
const router = createRouter();
const db = require('@arangodb').db;

module.context.use(router);

router.get('/hello-world', function (req, res) {
  function clone (obj) {
    if (obj === null || typeof obj !== 'object') {
      return obj;
    }
    var copy;
    if (Array.isArray(obj)) {
      copy = [];
      obj.forEach(function (i) {
        copy.push(clone(i));
      });
    } else if (obj instanceof Object) {
      copy = { };
      Object.keys(obj).forEach(function (k) {
        copy[k] = clone(obj[k]);
      });
    }
    return copy;
  }
  var shareholderFilter = function(config, vertex, path) {
    const vertexCount = config.collectedVertices.size;
    config.collectedVertices.add(vertex._key);
    if (vertexCount > config.limit) {
      return [ 'exclude', 'prune' ];
    }
    return "";
  };

  var countVisitor = function(config, result, vertex, path) {
    if (!result || !result.visited) {
      return;
    }
    if (result.visited.vertices) {
      result.visited.vertices.add(vertex._id);
    }
    if (result.visited.paths) {
      result.visited.paths.push(clone(path));
    }
    return;
  };

  var shareholderExpander = function(config, vertex, path) {
    var connected = [];
    var datasource = config.datasource;
    const vertexCount = config.collectedVertices.size;
    config.collectedVertices.add(vertex._id);
    if (vertexCount > config.limit) {
      return [];
    }
    var totalHoldPct = path.edges.map(e => e.holdPct).reduce((a,b) => a*b, 1.0);
    var holdPctThreshold = 0.02;
    if (vertexCount < 5000) {
      holdPctThreshold = 0.005;
    } else if (vertexCount > 10000) {
      holdPctThreshold = 0.05;
    }
    if (totalHoldPct < holdPctThreshold) {
      return [];
    } else {
      datasource.getInEdges(vertex).filter(edge => edge.holdPct * totalHoldPct >= holdPctThreshold).forEach(edge => connected.push({ edge: edge, vertex: {_id: edge._from} }));
    }
    return connected;
  }

  var config = {
    datasource: traversal.collectionDatasourceFactory(db.mio_company_company),
    strategy: "breadthfirst",
    order: "postorder",
    uniqueness: {
      vertices: 'path',
      edges: 'path'
    },
    filter: shareholderFilter,
    expander: shareholderExpander,
    visitor: countVisitor,
    visitCount: 0,
    collectedVertices: new Set(),
//   collectedEdges: new Set(),
//   limit: 50000,
//   maxDepth: 5,
    buildVertices: false
  };

  var result = {
    visited: {
      vertices: new Set(),
      // edges: []
      paths: []
    }
  };

  var traverser = new traversal.Traverser(config);

  function f() {
    console.time('traverse');
    traverser.traverse(result, db._document("mio_company/4ae148aa1faca8eb0541532566ba2106"))
    console.timeEnd('traverse');
  }

  const start = Date.now();
  f();

  res.send(Date.now() - start);
})
  .response(['text/plain'], 'A generic greeting.')
  .summary('Generic greeting')
  .description('Prints a generic greeting.');



```

__AQL explain (if applicable)__:

__Dataset__:
A financial datasets with 71,187,289 nodes and 7,212,539 edge(s)

__Size of your Dataset on disk__:
20G on SSD * 6 nodes

__Replication Factor & Number of Shards (Cluster only)__:
Replication Factor: 2
Number of Shards: 12

__Problem__:
When I execute the same code on arangosh (on the coordinator server and connect to 127.0.0.1), the execution time is around 3.7s.

However, when I execute the foxx query with swagger on ArangoDB UI, the execution time returned is around 47s, which is more than 10x slower.

__Expected result__:
I expect the execution time of arangosh and foxx be identical (foxx should be a bit faster since no network transmission is involved)

**Comment by dothebart** [comment]
Hi, 
please note that the javascript graph traversing is deprecated, and if you care for performance you should use [AQL traversals](https://docs.arangodb.com/3.4/AQL/Graphs/)

Once you reach certain size of traversals, they may even stop working for you completely: https://stackoverflow.com/questions/53334437/arangodb-graph-traversal-fails-inspite-of-increased-heap-size

**Comment by alexyzhou** [comment]
Thanks for your reply. Actually I tried AQL traversal even before the javascript version, but one critical issue prevented me from continuing using AQL: the AQL traversal doesn't support custom pruning logic , which in my case is required to reduce the traversal size. 

Thus can you suggest is there any work around for that?

**Comment by Simran-B** [comment]
In the next bug-fix release v3.4.5 there will be a new AQL keyword PRUNE to stop traversals down a path as soon as some conditions are met (the matching node will be included in the result). Will that be sufficient to port your queries to AQL?

https://github.com/arangodb/arangodb/pull/8286/files

**Comment by alexyzhou** [comment]
Thanks, it will be great if we have prune in the AQL Traversals. When will version 3.4.5 be released?

**Comment by Simran-B** [comment]
It should be out in 2-3 weeks.

**Comment by maxkernbach** [comment]
Hi @alexyzhou,

version 3.4.5, which introduces Pruning to AQL Traversals, has just been released. 
Please have a look at the [documentation](https://docs.arangodb.com/3.4/AQL/Graphs/Traversals.html#pruning) for further details.

**Comment by maxkernbach** [comment]
@alexyzhou

Just sending a follow-up. Could you please reply to my latest message?
Your feedback for AQL Pruning would be appreciated.

**Comment by alexyzhou** [comment]
Sure, actually we made our own implementation of pruning with ArangoDB edges API. We will evaluate the new AQL Pruning and let you know if it fits our case.

**Comment by OmarAyo** [comment]
Hi @alexyzhou 

Just sending this message to check if you had the chance to evaluate the new AQL Pruning 

Best,

**Comment by OmarAyo** [comment]
Hi @alexyzhou 

Closing this issue for now since we have not heard back from you in a while.
In case the problem persists, please respond to the latest comments and we will reopen.
