### ISSUE TITLE
Foxx-Manager replace function has no impact

### ISSUE THREAD

**Issue by frankmayer** [arangodb/arangodb#842]
Hi guys,
unless I am doing something wrong, it seems that the `foxx-manager replace appname /mountpoint` command (as described here: https://www.arangodb.org/manuals/1/UserManualFoxxManager.html), doesn't do what it's supposed to.

My moves:

1. I fetch a local app directory into my local repository
2. I mount the application
3. I visit the app mountpoint and get desired result
3. I make some change to the code in the local directory
4. I execute `foxx-manager replace appname /mountpoint`
5. At this point I'd expect to see the results of the new code in my app, but I still get the old results. 

Any ideas?

**Comment by pluma** [comment]
Seems to be doing something now, or else we wouldn't have bugs in it: https://github.com/arangodb/arangodb/issues/1362
