### ISSUE TITLE
ArangoDB Foxx is slower for inEdges Query

### ISSUE THREAD

**Issue by alexyzhou** [arangodb/arangodb#8437]
## My Environment

* __ArangoDB Version__:        3.4.3
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   ArangoDB Starter
* __Configuration__:               8 Core, 32GB Nodes * 6
* __Infrastructure__:               AWS
* __Operating System__:        AWS AMI Latest
* __Total RAM in your machine__:        32GB
* __Disks in use__:        SSD
* __Used Package__:              SUSE or RedHat .rpm

## Component, Query & Data

__Affected feature__:
ArangoDB Foxx

__AQL query (if applicable)__:
I firstly wrote the query (which is a customized graph traversal) in arangosh, and here is the code:
```js
const targetId = "mio_company/" + "4ae148aa1faca8eb0541532566ba2106";
  const edgeCollection = db._collection("mio_company_company");
  var workingStart = Date.now();
  for (var i = 0; i < 1000; ++i) {
    edgeCollection.inEdges(targetId).length;
  }
  var workingEnd = Date.now() - workingStart;
```

And based on the same code, I wrap it into a foxx service:
```js
'use strict';
const createRouter = require('@arangodb/foxx/router');
const router = createRouter();
const db = require('@arangodb').db;

module.context.use(router);

router.get('/hello-world', function (req, res) {
  const targetId = "mio_company/" + "4ae148aa1faca8eb0541532566ba2106";
  const edgeCollection = db._collection("mio_company_company");
  var workingStart = Date.now();
  for (var i = 0; i < 1000; ++i) {
    edgeCollection.inEdges(targetId).length;
  }
  var workingEnd = Date.now() - workingStart;
  res.send(workingEnd);
})
  .response(['text/plain'], 'A generic greeting.')
  .summary('Generic greeting')
  .description('Prints a generic greeting.');

```

__AQL explain (if applicable)__:

__Dataset__:
A financial datasets with 71,187,289 nodes and 7,212,539 edge(s)

__Size of your Dataset on disk__:
20G on SSD * 6 nodes

__Replication Factor & Number of Shards (Cluster only)__:
Replication Factor: 2
Number of Shards: 12

__Problem__:
When I execute the same code on arangosh (on the coordinator server and connect to 127.0.0.1), the execution time is around 7.2s.

However, when I execute the foxx query with swagger on ArangoDB UI, the execution time returned is around 18s, which is significantly slower, which is weird since the query just involves collection's method: InEdges.

__Expected result__:
I expect the execution time of arangosh and foxx be identical (foxx should be a bit faster since no network transmission is involved)

**Comment by dothebart** [comment]
Hi, 
the arangosh version will only use the C++ API on the server, and translate the answers into .js objects, while foxx has to do this inline.
Can you try to use AQL: 
```
FOR e IN edgecollection FILTER e._from == @myID RETURN e
```

**Comment by Simran-B** [comment]
arangosh implementation - `js\client\modules\@arangodb\arango-collection.js`

```js
ArangoCollection.prototype.inEdges = function (vertex) {
  return this._edgesQuery(vertex, 'in');
};
```

```js
ArangoCollection.prototype._edgesQuery = function (vertex, direction) {
  if (!(vertex instanceof Array)) {
    vertex = [vertex];
  }
  vertex = vertex.map(function (v) {
    if (v.hasOwnProperty('_id')) {
      return v._id;
    }
    return v;
  });

  // get the edges
  var url = '/_api/edges/' + encodeURIComponent(this.name())
  + (direction ? '?direction=' + direction : '');

  var requestResult = this._database._connection.POST(this._prefixurl(url), vertex);

  arangosh.checkRequestResult(requestResult);

  return requestResult.edges;
};
```
So this uses the HTTP Edges API.

Server (=Foxx?) implementation - `js\server\modules\@arangodb\arango-collection.js`

```js
ArangoCollection.prototype.inEdges = function (vertex) {
  return this.INEDGES(vertex);
};
```
_arangod\V8Server\v8-query.cpp_

```cpp
  TRI_AddMethodVocbase(isolate, VocbaseColTempl,
                       TRI_V8_ASCII_STRING(isolate, "INEDGES"), JS_InEdgesQuery, true);
```

```cpp
static void JS_InEdgesQuery(v8::FunctionCallbackInfo<v8::Value> const& args) {
  TRI_V8_TRY_CATCH_BEGIN(isolate);
  EdgesQuery(TRI_EDGE_IN, args);
  // cppcheck-suppress *
  TRI_V8_TRY_CATCH_END
}
```

EdgesQuery essentially builds and executes an AQL query in V8:

    FOR doc IN @@collection FILTER doc._to == @value RETURN doc

So there seems to be some back and forth between native code and V8, which could have a measurable overhead. On the other hand, it seems that requests from JavaScript (e.g. to the HTTP API) are ultimately carried out by native code using V8, which would make them not too different in terms of native <-> V8. Not sure if any of this is relevant regarding the performance gap.

---

Where do you run arangosh on? Is it your local computer?

Can you try an AQL query in your Foxx service instead?
You could try both, graph traversal...

```js
const { db, query } = require("@arangodb");
...
query`
  FOR v IN 1..1 INBOUND ${targetId} ${edgeCollection}
    COLLECT WITH COUNT INTO count
    RETURN count
`
```

... and a non-graphy query:

```js
query`
  FOR doc IN ${edgeCollection}
    FILTER doc._to == ${targetId}
    COLLECT WITH COUNT INTO count
    RETURN count
`
```

**Comment by alexyzhou** [comment]
Hi,

Thanks for your reply. I tried running AQL both in arangosh and foxx. Here is the result:
1) AQL return count:
- arangosh: 8607ms
- foxx: 8658ms

2) AQL return actual data:
- arangosh: ~20s
- foxx: ~17s

So it seems using AQL generates roughly identical results. But how can I make foxx meet the performance of inEdges in arangosh?

**Comment by alexyzhou** [comment]
Is is possible for me to directly call the API (which seems using C++ implementation and faster) just like below:
```js
var url = '/_api/edges/' + encodeURIComponent(this.name())
```

**Comment by Simran-B** [comment]
You can try the HTTP API as well, sure:
https://docs.arangodb.com/3.4/HTTP/Edge/WorkingWithEdges.html

How make HTTP requests from Foxx is described in this guide:
https://docs.arangodb.com/3.4/Manual/Foxx/Guides/MakingRequests.html

**Comment by alexyzhou** [comment]
Thanks guys, I updated the code and use @arangodb/request to improve the performance and the result looks good.

However, when I execute the query at a high concurrency, the server refuses to work.
https://github.com/arangodb/arangodb/issues/8469

Can you take a look?

**Comment by dothebart** [comment]
heh, nice try. But I don't think thats going to scale ;)

**Comment by dothebart** [comment]
closing as out of date.
