### ISSUE TITLE
Driver support for R

### ISSUE THREAD

**Issue by geotheory** [arangodb/arangodb#8438]
ArangoDB looks great, but I can't find any support/driver for interfacing with R. I wonder if there has been any thinking or discussion with third parties about this?  I'm looking for a decent opensource graph database to integrate with R/Shiny apps, and Neo4j community edition's single database restriction makes this impossible for me.

**Comment by pilare** [comment]
I'm backing up this request. Arango is for me the most promising Multi model database engine out there. I love the support for Java Script. But I cannot use if I won't have support for R which is driving good amount of the data analysis in bioinformatics applications.

**Comment by dothebart** [comment]
Hi, 
from the ArangoDB side we don't have the current experience or resources to work on this. 
However, there are already several community based drivers in existence, and you could probably add one for R too. 
If I get that correctly supporting the complete API from R is not as usefull as for other programming languages, one would probably use i.e. [arangomigo](https://github.com/deusdat/arangomigo) to set up the database. 
The ArangoDB API itself is mostly documented via [swagger.io / OpenAPI Specification](https://swagger.io)
The API-Description can be found in the ArangoDB Github repository: https://github.com/arangodb/arangodb/blob/devel/js/apps/system/_admin/aardvark/APP/api-docs.json ,  [or can be explored interactively via the webinterface](https://www.arangodb.com/2018/03/using-arangodb-swaggerio-interactive-api-documentation/). 

The [HTTP-API is also part of the main ArangoDB Documentation](https://docs.arangodb.com/3.4/HTTP/index.html). 
The subset to be implemented would most probably contain:
- [Fetching single documents](https://docs.arangodb.com/3.4/HTTP/Document/)
- [Working with graph elements (Vertices / edges)](https://docs.arangodb.com/3.4/HTTP/Gharial/Vertices.html)
- [The ability to execute AQL-Queries](https://docs.arangodb.com/3.4/HTTP/AqlQueryCursor/QueryResults.html)

If you want to more interactively discuss with us or other driver developers, feel free to [join the `#arangodevel` channel in the ArangoDB Community slack](https://slack.arangodb.com/)

**Comment by OmarAyo** [comment]
Hi @geotheory 

Did you have the chance to read dothebart's last message ? Was it useful?

**Comment by geotheory** [comment]
@OmarAyo Ah I missed it but thanks for tip off. Yes I get why as @dothebart says R bindings have been deprioritised as one for community to solve. R community has no special entitlement to a pony! Hopefully someone will grapple with it soon. Till then I'm stuck Docker workaround to running multiple Neo4J instances.

**Comment by maxkernbach** [comment]
Hi @geotheory and @pilare,

[Gabriele Galatolo](https://gitlab.com/ggalatolo) has recently developed a R driver:
[aRangodb](https://gitlab.com/krpack/arango-driver): an R Package to Store, Retrieve and Visualize Data with the Multi-Model Database ArangoDB

Version 0.0.1, which is the first release of the package, has been published.
It has already been used in a ["Semantic Tweet Analytics" ArangoDB case study](https://www.arangodb.com/why-arangodb/case-studies/kode-semantic-tweet-analytics-arangodb-rlang/) by Kode Solutions.

**Comment by geotheory** [comment]
Thanks for heads-up @maxkernbach. I'm looking at it now
