### ISSUE TITLE
Incorrect Documentation for starter flags

### ISSUE THREAD

**Issue by e-moshaya** [arangodb/arangodb#8507]
## My Environment

* __ArangoDB Version__:        3.4.4
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   ArangoDB Starter
* __Infrastructure__:               AWS
* __Operating System__:        Amazon Linux

__Problem__:

I'm trying to follow a few option available via documentation below: https://docs.arangodb.com/3.4/Manual/Programs/Arangod/Cluster.html#more-advanced-options
However, the following options are not available at all with the latest 3.4.4 version:

--cluster.require-persisted-id bool
--cluster.synchronous-replication-timeout-factor
--cluster.system-replication-factor

Moreover,

--cluster.my-advertised-endpoint is not available as an option but 
--cluster.advertised-endpoint is available.

Was this just a typo in the documentation?
Are the above enterprise only features? We are using the community edition.

**Comment by maxkernbach** [comment]
Hi @e-moshaya,

it seems that you are mixing up the available options for `arangod` (ArangoDB Server) and `arangodb` (ArangoDB Starter).

Available options for `arangod` are:

`--cluster.my-advertised-endpoint`
`--cluster.require-persisted-id bool`
`--cluster.synchronous-replication-timeout-factor`
`--cluster.system-replication-factor`

These options are not available for `arangodb`, which has the option `--cluster.advertised-endpoint`. The Starter (`arangodb`) is internally starting `arangod` processes (coordinators, dbservers, agents). 

> Options for arangod that are not supported by the starter (arangodb) can still be passed to the database servers using a pass through option. Every option that start with a pass through prefix is passed through to the commandline of one or more server instances.

For more information, please have a look at the documentation link below:

https://docs.arangodb.com/3.4/Manual/Programs/Starter/Options.html#other-database-options

**Comment by maxkernbach** [comment]
Hi @e-moshaya,

has my latest message been helpful? Do you have any further questions?

**Comment by e-moshaya** [comment]
@maxkernbach yes thank you you've answered my question.. Closing this issue now
