### ISSUE TITLE
Can't visualize geo data

### ISSUE THREAD

**Issue by GaetanLhoest** [arangodb/arangodb#8515]
## My Environment

* __ArangoDB Version__: 3.4.3        
* __Storage Engine__:     RocksDB        
* __Deployment Mode__:   Single Server    
* __Deployment Strategy__:  Manual Start  
* __Configuration__:     default          
* __Infrastructure__:         own      
* __Operating System__:    MacOS 10.14.3     
* __Total RAM in your machine__:   8Gb     
* __Disks in use__:     SSD   
* __Used Package__:      Compiled from sources        

## Component, Query & Data

__Affected feature__:

Can't visualize geo data on the OSM layer in the GUI

![Capture d’écran 2019-03-21 à 17 13 01](https://user-images.githubusercontent.com/9035144/54809959-1056dc00-4c85-11e9-9733-88b060e8cfcd.png)

__AQL query (if applicable)__:

Followed the tutorial here
https://www.arangodb.com/arangodb-training-center/geojson-tutorial/
and used the queries of the tutorial

__AQL explain (if applicable)__:

__Dataset__:

Dataset of the tutorial

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

Follow the tutorial 

__Problem__:

Cant visualize geo result

__Expected result__:

Should see result on a map

**Comment by Simran-B** [comment]
Your `location` attribute appears to be a coordinate array. While GEO_CONTAINS() supports this, a GeoJSON object is required to display the location on a map. You could change your data model, but you may also convert it on the fly:

```js
FOR n IN neighborhoods
  FILTER n.name == "Chinatown"
  LET chinatown = n
  FOR restaurant IN restaurants
    FILTER GEO_CONTAINS(chinatown.geometry, restaurant.location)
    RETURN GEO_POINT(restaurant.location[0], restaurant.location[1]) // assuming [long,lat] order
```

v3.5.0 will support [array spreading](https://github.com/arangodb/arangodb/pull/4718), so will also be able to do this in the future: `GEO_POINT(...restaurant.location)`

**Comment by GaetanLhoest** [comment]
I think there was a little typo un the query you sent me, I corrected it with
  ```
  FOR n IN neighborhoods
  FILTER n.name == "Chinatown"
  LET chinatown = n
  FOR restaurant IN restaurants
    FILTER GEO_CONTAINS(chinatown.geometry, restaurant.location)
    RETURN GEO_POINT(restaurant.location.coordinates[0], restaurant.location.coordinates[1])
  ```

but it still does not work
![Capture d’écran 2019-03-22 à 15 43 32](https://user-images.githubusercontent.com/9035144/54830827-8d03ad80-4cb9-11e9-8f00-51e341f31c32.png)

**Comment by Simran-B** [comment]
Oh, I was on the wrong track. I tried the following query against the tutorial dataset using the v3.4.4 web interface in Chrome under Windows 10:

```js
FOR n IN neighborhoods
  FILTER n.name == "Chinatown"
  LET chinatown = n
  FOR restaurant IN restaurants
    FILTER GEO_CONTAINS(chinatown.geometry, restaurant.location)
    RETURN restaurant.location
```

![image](https://user-images.githubusercontent.com/7819991/54841935-d14e7800-4cd0-11e9-9fb5-9627ea7d47f3.png)

It does show the map for me, with and without geo indexes on the collections.

What OS and browser do you use? Any ad-blocker or something that could interfere?

**Comment by GaetanLhoest** [comment]
Strange, I'm under MacOS 10.14.3, I tried with Safari, Firefox and Chrome, removing all the extensions on chrome, and no visualization.

 I'm running ArangoDb 3.4.3 in local compiled from sources.

**Comment by GaetanLhoest** [comment]
I just tried with the same source code compiled in a Debian docker and I can visualize the data. I guess this is linked to MacOS then. 
Being able to visualize the data in the Debian Docker is enough for me, so you can close this issue if you want.

**Comment by Simran-B** [comment]
That sounds pretty strange. Could it be related What device model do you have?

I assume that if WebGL is not supported that it falls back to Canvas, but I could be wrong. OpenGL should still work under macOS 10.14 nonetheless:

> **Deprecation of OpenGL and OpenCL**
> Apps built using OpenGL and OpenCL will continue to run in macOS 10.14, but these legacy technologies are deprecated in macOS 10.14.

https://developer.apple.com/macos/whats-new/

**Comment by GaetanLhoest** [comment]
It's a MacoBook Pro retina Touch Bar 13" from 2018
<img width="108" alt="Capture d’écran 2019-03-23 à 17 23 52" src="https://user-images.githubusercontent.com/9035144/54868777-6fedde00-4d90-11e9-823e-d4a8bc2160ba.png">

**Comment by hkernbach** [comment]
> I'm running ArangoDb 3.4.3 in local compiled from sources.

This could be the reason. You also need to compile the UI. You can achieve this with the command `make frontend` in your build directory.

**Comment by GaetanLhoest** [comment]
Hi, 
I tried compile the frontend with `make frontend`, it compiled well, but there is still no geo visualization

**Comment by hkernbach** [comment]
@GaetanLhoest could you show us the exact server response in JSON format?

**Comment by GaetanLhoest** [comment]
```
[
  {
    "type": "Point",
    "coordinates": [
      24.9210566,
      60.1647939
    ]
  },
  {
    "type": "Point",
    "coordinates": [
      24.9210282,
      60.1636645
    ]
  },
  {
    "type": "Point",
    "coordinates": [
      24.9212859,
      60.164631
    ]
  },
  {
    "type": "Point",
    "coordinates": [
      24.9370245,
      60.1643249
    ]
  }
]```

**Comment by hkernbach** [comment]
e.g. the query: 
```
let a = [
  {
    "type": "Point",
    "coordinates": [
      24.9210566,
      60.1647939
    ]
  },
  {
    "type": "Point",
    "coordinates": [
      24.9210282,
      60.1636645
    ]
  },
  {
    "type": "Point",
    "coordinates": [
      24.9212859,
      60.164631
    ]
  },
  {
    "type": "Point",
    "coordinates": [
      24.9370245,
      60.1643249
    ]
  }
]
return a[0]
```

is also not showing a point on the map? 
If so, are there any JavaScript errors visible in the browser debug console/output?

**Comment by GaetanLhoest** [comment]
![image](https://user-images.githubusercontent.com/9035144/55243140-e5e5bf80-523e-11e9-9de4-2d089cf5a443.png)

**Comment by hkernbach** [comment]
Well ok than it is just not compiled in the UI. 
Also during "make frontend" no errors appeared? 

Maybe try the manual way then, that would be: 
```
cd devel/js/apps/system/_admin/aardvark/APP
rm -rf node_modules
npm i 
grunt deploy
```

**Comment by Simran-B** [comment]
Also make sure that the front you compile is actually served and that no browser caching interferes. An easy way around caching problems is to use incognito mode.

**Comment by GaetanLhoest** [comment]
Hi,
I did both your recommendations: 
Ran commands provided by @hkernbach and launched in anonymous mode, as suggested by @Simran-B 
It doesn't do the trick, still no visualization :/

**Comment by GaetanLhoest** [comment]
For information, I took the source code here
https://github.com/arangodb/arangodb/releases/tag/v3.4.3

**Comment by dothebart** [comment]
with ArangoDB 3.4 being EOLed and [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/)  I'm closing this as out of date.
