### ISSUE TITLE
arangoimp tool closing suddenly after entering password

### ISSUE THREAD

**Issue by sandeepkorrapati** [arangodb/arangodb#8540]
I have tried to import data to arangodb from arangoimport tool. But somehow, it closed suddenly. I tried running from command prompt also but no luck. Any help would be appreciated

**Comment by Simran-B** [comment]
Please fill out the issue template including your ArangoDB version, OS, import data files and the exact command you used. Otherwise we can't help.

**Comment by sandeepkorrapati** [comment]
## My Environment

* __ArangoDB Version__:        3.4.3
* __Storage Engine__:             
* __Deployment Mode__:       
* __Deployment Strategy__:   Manual Start
* __Configuration__:               
* __Infrastructure__:               Own
* __Operating System__:        Windows 10 64 bit
* __Total RAM in your machine__:        8 GB
* __Disks in use__:        HDD
* __Used Package__:              

## Component, Query & Data

__Affected feature__: Arangoimp tool


__AQL query (if applicable)__:


__AQL explain (if applicable)__:



__Dataset__: airports and flights datasets available in documentation. Format is CSV


__Size of your Dataset on disk__:



__Replication Factor & Number of Shards (Cluster only)__:



## Steps to reproduce

1. 
2. 
3. 

__Problem__: arangoimp tool closing suddenly after entering password


__Expected result__: Should ask user to enter a command to import data set

**Comment by sandeepkorrapati** [comment]
I got it solved. Thanks for reaching out.

**Comment by Simran-B** [comment]
Unlike Arangosh, arangoimp(ort) and arangoexport are no interactive tools. They are intended to be used in a shell / command line and need to be invoked with parameters. Double-clicking their binaries on Windows will launch them, but after the password prompt they will fail and thus terminate, which means that the window will close immediately. If you start them in a command prompt then you will be able to see the error message. You could also write a `.bat` script like:

```
@echo off
arangoimport
pause
```

The `pause` will keep the window open until you hit a key.

**Comment by dothebart** [comment]
It seems they also found about how awkward it is to open consoles just to close them again: https://devblogs.microsoft.com/commandline/how-to-determine-what-just-ran-on-windows-console/ but don't show a real solution to this. (Or how we could detect that the console will instantly close again)

Please note that all applications ArangoDB brings are console applications and will behave similar. 

https://docs.arangodb.com/3.4/Manual/Programs/Arangoimport/ExamplesJson.html explains how to use the import tool.
