### ISSUE TITLE
Feature change proposal: remove within-"_system"-only restrictions on database commands

### ISSUE THREAD

**Issue by frankmayer** [arangodb/arangodb#857]
Unless there is a specific reason not to do so, I'd propose to remove the restriction, where the following commands can only be executed from within the `_system_ db.
- db._listDatabases()
- db._createDatabase( name, options, users)
- db._dropDatabase( name)

It's more intuitive to be able to use those from everywhere in the shell, instead to be bound to the `_system` db context.

**Comment by graetzer** [comment]
These restrictions do no longer apply from 3.2 onwards
