### ISSUE TITLE
Backend Unavailable Error in Cluster

### ISSUE THREAD

**Issue by Puneeth-Kadamba** [arangodb/arangodb#8582]
## My Environment

* __ArangoDB Version__:        3.4.2-1
* __Storage Engine__:           RocksDB
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   ArangoDB Starter
* __Configuration__:               3 Nodes. Each Node having Agent,coordinator and DBServer
* __Infrastructure__:               AWS
* __Operating System__:        Ubuntu 16.04
* __Total RAM in your machine__:        32Gb.
* __Disks in use__:         SSD 

## Component, Query & Data

__Size of your Dataset on disk__:
21GB

__Replication Factor & Number of Shards (Cluster only)__:
3 and 9

## Steps to reproduce

1. Bring one of the node down by executing arangodb stop.
2. If the node is a follower, Cluster is still running with 2 nodes.
![image](https://user-images.githubusercontent.com/44632458/54998716-d6733600-4ff4-11e9-92a1-3ef1184807d2.png)

3. if the node is a leader,
we get the below error on cluster
![image](https://user-images.githubusercontent.com/44632458/54998815-04f11100-4ff5-11e9-8cbb-8c9ab7a1cb3f.png)

__Problem__:
1.Cluster goes down even when one of the node is down, which is a leader on majority of shards.
Why is the leader not evenly distributed? 
2. Re balance shard option is not helping in distributing the shards across multiple leaders.
3. When the leader node is down, cluster is not promoting the followers as leaders and instead throwing 500.

__Expected result__:
Cluster should be able to work with only 1 node even when 2 other nodes are down.

**Comment by Puneeth-Kadamba** [comment]
@pluma can you help?

**Comment by Puneeth-Kadamba** [comment]
@maxkernbach can you suggest

**Comment by Puneeth-Kadamba** [comment]
> So these kinds of errors can happen during the failover, but should stop afterwards. Please clarify whether this happens only temporary, or if the errors are persistent.
Yes we have observed during failover, these errors occur for few mins and it stabilized. However, when we stop the service on 2 nodes, these errors are persistent and the failover doesnt happen to the single node which is active.

> This is not true, even with a replication factor of 3. The agency can only work while a majority of its nodes are up. So if you want to allow for two nodes to crash simultaneously, you need at least 5 agents. 

How do we had more Agency nodes with the Arango Starter method. Do we run the additional agencies through manual command and add their references in the arangod_command.txt config?

**Comment by Puneeth-Kadamba** [comment]
> Plus, the default replication factor of system collections is 2. So you'd have to change the system replication factor, which we generally do not recommend. 

![image](https://user-images.githubusercontent.com/44632458/55389756-7845d600-5553-11e9-8530-7846f6c9e646.png)

This doesnt seem to available in 3.4.2 . we want this configuration as we need high availability with only 3 servers. 

Also if we need to run 5 agencies, do we have to use Starter method to join them to the cluster? Can we avoid dbserver being attached to this cluster?

**Comment by Puneeth-Kadamba** [comment]
> --cluster.agency-size int                Number of agents in the cluster (default 3)
>       --cluster.start-agent boolSlice          should an agent instance be started (default [])
>       --cluster.start-coordinator boolSlice    should a coordinator instance be started (default [])
>       --cluster.start-dbserver boolSlice       should a dbserver instance be started (default [])
> 

I assume, if we start a new node with start-agent as true and start-coordinator/start-dbserver as false, we will have only agents running on this node. Please confirm if this is correct.

**Comment by goedderz** [comment]
Hi @Puneeth-Kadamba,

this does not seem to be a bug, so I will close this issue now.

I must kindly ask you to ask your follow-up questions in our community slack in #cluster or on StackOverflow; github issues aren't the right place for that.

Best regards

Tobias
