### ISSUE TITLE
ArangoSearch Analyzer Configurability/Support

### ISSUE THREAD

**Issue by aveiros** [arangodb/arangodb#8634]
Another feature request(s) for the backlog.

From 3.5, Arango will introduce Analyzer configurability. Here are a few ideas which some "competitors" support:
1) Analyzer Configurability
2) Tokenizer Configurability
3) Stopwords Configurability

On the Analyzers support, and again looking at some of the "competitors", built up the following list:

Language | Supported by Arango
------------ | -------------
Arabic | ❌
Armenian | ❌
Basque | ❌
Bengali | ❌
Brazilian | ❌
Bulgarian | ❌
Catalan | ❌
Chinese | ✅
Czech | ❌
Danish | ❌
Dutch | ✅
English | ✅
Finnish | ✅
French | ✅
Galician | ❌
German | ✅
Greek | ❌
Hindi | ❌
Hungarian | ❌
Indonesian | ❌
Irish | ❌
Italian | ✅
Japanese | ❌
Korean | ❌
Latvian | ❌
Lithuanian | ❌
Norwegian | ✅
Persian | ❌
Portuguese | ✅
Romanian | ❌
Russian | ✅
Sorani | ❌
Spanish | ✅
Swedish | ✅
Thai | ❌
Turkish | ❌

Ordering the missing languages by number of speakers: Hindi, Arabic, Bengali, Portuguese (if we count Brazilian being left out), Indonesian, Japanese ...

Looking forward for 3.5.

**Comment by dothebart** [comment]
Regarding the `Tokenizer Configurability` - This uses ICU. We're currently bound to the ICU V8 uses, which is 58.1. 
as @Simran-B  mentioned in https://github.com/arangodb/arangodb/issues/7111#issuecomment-438487375 you may get other locales by installing Full-ICU.

**Comment by OmarAyo** [comment]
Hi @aveiros 

Did you find dothebart's message useful?

**Comment by OmarAyo** [comment]
@KVS85 FYI

**Comment by OmarAyo** [comment]
@gnusi  FYI

**Comment by aveiros** [comment]
You can close this, as 3.5 allows analyzer configurability.

**Comment by Simran-B** [comment]
An ICU update might land in 3.6, and there is some effort to make ArangoSearch use the very same ICU as the rest of the system.

Stemming support depends on Snowball. There are a few [third-party algorithms](https://snowballstem.org/algorithms/) (see _Other Stemming Algorithms_),

@dothebart will we ship full-icu? Could be include 3rd party stemmers?

**Comment by dothebart** [comment]
@fceller and @joerg84 decided that the V8/ICU upgrade will not be in 3.6

**Comment by dothebart** [comment]
closing this with [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) being available containing mentioned ICU upgrade.
