### ISSUE TITLE
Where to use '--rocksdb.total-write-buffer-size'  option

### ISSUE THREAD

**Issue by wjx-git** [arangodb/arangodb#8665]
## My Environment

* __ArangoDB Version__:        3.4.3
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   ArangoDB Starter
* __Operating System__:       CentOS 7

__Problem__:
Where to use '--rocksdb.total-write-buffer-size'  option?

**Comment by Simran-B** [comment]
It is an `arangod` options:
https://docs.arangodb.com/3.4/Manual/Programs/Arangod/Options.html#rocksdb-options

If you want to pass arangod options through the starter to the cluster nodes, then see the starter option documentation here:
https://docs.arangodb.com/3.4/Manual/Programs/Starter/Options.html#other-database-options

**Comment by wjx-git** [comment]
Thank you for your reply. 
This options seems not be supported in Arangodb Starter. Then I choose Manual Start to startup a cluster, but there is a mistake.  Start as follows:
https://docs.arangodb.com/3.4/Manual/Deployment/Cluster/ManualStart.html
The command:
![image](https://user-images.githubusercontent.com/47173946/55696513-deb57300-59ef-11e9-95f4-50d0f04c294a.png)
the error info:
FATAL unable to create database directory 'agent': failed to create directory 'agent': Permission denied
ps: I use root user

**Comment by dothebart** [comment]
Hi,
please don't use screenshots for text. Use tripple-tics to blockquote it: 
```
block
```
Please make sure the user has write access to the database directory of the agency.

**Comment by Simran-B** [comment]
> This options seems not be supported in Arangodb Starter.

How do you come to this conclusion? Do you get an error? What exact error and what is the command/configuration you use?

The option `--rocksdb.total-write-buffer-size` was added in v3.4.0-rc.4 (2018-11-04).

If you see a `Permission denied` error then please verify that the path is actually writable. We can't diagnose nor fix your system from the outside, without an appropriate description of the environment and the things you see.

**Comment by wjx-git** [comment]
I use Arangodb starter to start the cluster, but it doesn't have the --rocksdb options in command. But I found this option can be configured in the arangod.conf file, so the problem solved.
when I start the cluster through manual start way, the Permission denied will happen. I think the path is writable, because I can create file in the path use command: mkdir.
whatever, I will use the first way to start cluster.

**Comment by Simran-B** [comment]
If you want to set arangod options through arangodb, then you must follow the description here: https://docs.arangodb.com/3.4/Manual/Programs/Starter/Options.html#other-database-options

`--dbservers.<section>.<key>=<value>`

Like:

`--dbservers.rocksdb.total-write-buffer-size=123456789`
