### ISSUE TITLE
Service "/_admin/aardvark" encountered error 500 while handling GET

### ISSUE THREAD

**Issue by b-fett** [arangodb/arangodb#8669]
## My Environment

* __ArangoDB Version__:        3.4.2-1
* __Storage Engine__:             RocksDB 5.16.0
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start in Docker
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:        linux x64
* __Total RAM in your machine__:        24Gb
* __Disks in use__:        SSD
* __Used Package__:           Docker - official Docker library

## Component, Query & Data

__Affected feature__:
AQL query using web interface

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. Create large enough data set in collection (about 15 fields per document, millions of entries)
1. Open collection view in web ui
1. Hit "Download documents as JSON file" and "Download JSON"
1. Wait for awhile

__Problem__:

```
Service "/_admin/aardvark" encountered error 500 while handling GET http://localhost:8529/_db/arango/_admin/aardvark/query/result/download/eyJxdWVyeSI6IkZPUiB4IGluIEBAY29sbGVjdGlvbiBSRVRVUk4geCIsImJpbmRWYXJzIjp7IkBjb2xsZWN0aW9uIjoidXNlcnMifX0= 
via RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at SyntheticResponse.json (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/response.js:186:31)
    at Route._handler (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/aardvark.js:332:7)
    at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:412:15)
    at /usr/share/arangodb3/js/node/node_modules/lodash/lodash.js:10067:25
    at Middleware.authRouter.use (/usr/share/arangodb3/js/apps/system/_admin/aardvark/APP/aardvark.js:115:3)
    at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:414:15)
    at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:410:7)
    at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:410:7)
    at next (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/router/tree.js:410:7)
```

__Expected result__:

Downloaded JSON file.

**Comment by maxkernbach** [comment]
Hi @b-fett,

thanks for reporting. 700000 documents with ~15 strings in a document collection were enough to reproduce this issue. Docker is not required to reproduce, any single instance works.
The resulting error is the exact same one that you posted.

Did you already try to export the collection as a JSON file with [arangoexport](https://docs.arangodb.com/3.4/Manual/Programs/Arangoexport/)? An example to export a collection in JSON format can be found below:

https://docs.arangodb.com/3.4/Manual/Programs/Arangoexport/Examples.html#export-json

**Comment by Simran-B** [comment]
Is this possibly hitting the V8 string length limit?
https://stackoverflow.com/a/47781288/2044940

**Comment by dothebart** [comment]
with the availability of [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) I'm closing this as solved.
