### ISSUE TITLE
How does foxx's http request life cycle work?

### ISSUE THREAD

**Issue by poland-can-into-space** [arangodb/arangodb#8692]
# Question
1. How does foxx's http request life cycle work?
2. Which part of the code should I read to understand?

# Background
I have recently built a framework to reduce development/learning and debugging cost for foxx.
Although it helped me significantly, there were certain features/bugs that I couldn't add/fix; thus I tried to figure out how foxx is implemented.
However, I was not able to find out where `module.context.use` come from;
Moreover, I wasn't really able to figure out where the http requests comes from and it's life cycle. (Does it come from the c++ part of the code?)

Thank you for reading my question and I'm looking forward to your answer!

**Comment by dothebart** [comment]
Hi, 
the journey starts like this:
 - arangod/Actions/RestActionHandler.cpp is the dispacher which is invoked via the scheduler. 
 - arangod/V8Server/v8-actions.cpp:execute() will handle the transition into V8, like find a free V8 Isolate from the Dealer, translate parameters etc. into V8 strings. 
 - js/actions/api-system.js is the entry point insive javascript; its invoking `routeRequest` into the respective action.
 - js/server/modules/@arangodb/actions.js is then contains the dispatcher to look up the route to invoke `foxxRouting()` , which in term will invoke `routeRequest()`

The js part should also be viewable if you invoke `console.log(new Error().stack)` from within a foxx service.

**Comment by poland-can-into-space** [comment]
Thank you for your reply!
My problem has been solved.
