### ISSUE TITLE
Out of memory when creating collection

### ISSUE THREAD

**Issue by imtrobin** [arangodb/arangodb#8693]
## My Environment

* __ArangoDB Version__:        3.4.4
* __Storage Engine__:             mmfiles
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   ArangoDB Starter* 
* __Infrastructure__:              own
* __Operating System__:        Centos 7

I'm using c# arangodbclient on my test server. When I create a collection, I get an Out of Memory in the status, but the collection is created successfully. This is an empty new database, without any other collection.

```
 using (IArangoDatabase dbPlatform = ArangoDatabase.CreateWithSetting ())
{
   CreateCollectionResult result = await dbPlatform.CreateCollectionAsync ("testcollection");
   // this returns 3 on first creation
   if (0 != result.Status)
        ReportError ($"Error creating collection:{result.Status}");
}
```

**Comment by dothebart** [comment]
Hi, 
can you send a tcpdump/wireshark capture of the traffic involved here? (using a dummy password)

**Comment by imtrobin** [comment]
POST /_db/_system/_api/collection HTTP/1.1
Authorization: Basic cm9vdDoxMjM0NTY=
User-Agent: .NETClient/0.7
Content-Length: 25
Host: 192.168.1.183:8529

{"name":"testcollection"}


JSON reply

{"error":false,"code":200,"waitForSync":false,"type":2,"indexBuckets":8,"id":"19002191","doCompact":true,"globallyUniqueId":"hEBC7982B697E/19002191","isVolatile":false,"journalSize":33554432,"isSystem":false,"keyOptions":{"allowUserKeys":true,"type":"traditional","lastValue":0},"name":"testcollection","statusString":"loaded","status":3}

**Comment by dothebart** [comment]
Hi, 
but this very request doesn't show an OOM, right? 
What else was going on on your system before when that happened?

**Comment by imtrobin** [comment]
Status 3, is out of memory, no? I assume the status should be 0 if no issue.

The system (in VM) is fine, the collection is created fine. This is a test system with only 1 collection so not under heavy load

**Comment by dothebart** [comment]
saadly https://docs.arangodb.com/3.4/HTTP/Collection/Creating.html isn't all complete on this topic. 
However, 3 in this case means that the status of the collection is 'loaded' - which only has a meaning if you're running with the MMFiles Storage-engine.

**Comment by imtrobin** [comment]
So this is not documented properly or? I thought the status code refer to this table

https://docs.arangodb.com/3.4/Manual/Appendix/ErrorCodes.html

So how should I be verifying that there is no error.

**Comment by Simran-B** [comment]
Those error codes are given in the `code` attribute of replies:

    {"error":false,"code":200, ...}

1xx, 2xx and 3xx are HTTP status codes for non-errors (`"error": false`). 4xx and 5xx error codes in ArangoDB correspond to HTTP status codes. The `status` attribute as answer to `POST /_api/collection` requests has nothing to do with error codes. There is a second attribute `statusString` which is a readable version of the collection status:

    { ... "statusString":"loaded","status":3}

**Comment by imtrobin** [comment]
Yes, I'm not talking about http code, I'm referring to this table

https://docs.arangodb.com/3.4/Manual/Appendix/ErrorCodes.html

This is the status table, no? Or does the status 3 comes from another table? How do I verify the call is working fine, other than http 200.

**Comment by dothebart** [comment]
`Status` refers to the current state of the collection. In case of MMFiles it could be: 
- 1 - not loaded
- 2 - loading
- 3 - loaded
again, when running with rocksdb, this doesn't have a meaning.

**Comment by imtrobin** [comment]
Ok noted.

**Comment by Simran-B** [comment]
> This is the status table, no?

https://docs.arangodb.com/3.4/Manual/Appendix/ErrorCodes.html lists error codes, not states to be precise.

The values of the collection status are defined in code, see here: https://github.com/arangodb/arangodb/blob/4f7923a971c8e4cf6c0f6a1a4373850b5353cf82/arangod/VocBase/vocbase.h#L106

**Comment by dothebart** [comment]
Adding the missing bits: https://github.com/arangodb/arangodb/pull/8734/files
