### ISSUE TITLE
Web Interface behind reverse proxy. Displays Page. But Cannot login.

### ISSUE THREAD

**Issue by rcoulsell** [arangodb/arangodb#8713]
## My Environment

* __ArangoDB Version__:        ArangoDB 3.3.22 [linux] 64bit, using jemalloc, build tags/v3.3.22-0-g369450e680, VPack 0.1.30, RocksDB 5.6.0, ICU 58.1, V8 5.7.492.77, OpenSSL 1.0.2g  1 Mar 2016
* __Storage Engine__:             MMFiles
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   ArangoDB Starter
* __Configuration__:               Single Server
* __Infrastructure__:               own
* __Operating System__:        Ubunutu 18.04 Desktop
* __Total RAM in your machine__:        128GB
* __Disks in use__:        2TB Samsung 960 SSD
* __Used Package__:              Ubuntu

## Component, Query & Data

__Affected feature__:
Web Interface Login. Login request never answered.

## Steps to reproduce
Chrome Headers with no response:
`Request URL: http://example.com:8080/_db/_system/_open/auth
Referrer Policy: no-referrer-when-downgrade

__Request Headers__:
Provisional headers are shown
Accept: application/json, text/javascript, */*; q=0.01
Authorization: bearer null
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Origin: http://example.com:8080
Referer: http://example.com:8080/_db/_system/_admin/aardvark/index.html
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
X-Requested-With: XMLHttpRequest

Form Data:
{"username":"username","password":"password"}:`

__Node.js - routes.js__:
`// =====================================
// ArangoDB Web interface ============
// =====================================
var httpProxy = require('http-proxy');
var proxy = httpProxy.createProxyServer({followRedirects: true});

// set headers location overwrite per arangodb documentation
proxy.on('proxyReq', function(proxyReq, req, res, options) { 
    proxyReq.setHeader('X-Script-Name', 'http://example.com:8080');
});

proxy.on('error', function(e) {
    console.log(e);
});

app.all('*/_db/*', function(req, res) {
    proxy.web(req, res, {target: 'http://localhost:8529'});
});`

__/etc/arangodb3/arangod.conf__:
Configured CORS how I would expect to be configured.
`[frontend]
proxy-request-check=false
version-check=false
[http]
trusted-origin=all
allow-method-override=true`

Note: I have also tried 'trusted-origin=*' (Not sure which one is correct)

__Problem__:
I have a Node.js back end that I am using for authentication and for reverse proxy of an ArangoDB Web Interface. I am using the Node.js node-http-proxy module.

Documentation examples use nginx, etc. but trying to keep everything under the node back end to be able to keep the proxy access behind site authentication.

The _open/auth request is never responded to from the external url. I can still access http://localhost:8529 from the server locally and login in just fine.

__Expected result__:
Login possible from external link.

**Comment by rcoulsell** [comment]
note the app.all route has wildcards at the begining and end that the post above escaped i.e. \*/_db/\*

**Comment by rcoulsell** [comment]
Digging and digging... it appears the POST with the credentials is never sent by the client side.
Any thoughts on what setting is amiss?

**Comment by rcoulsell** [comment]
@OmarAyo this issue does not involve arangojs, just the web interface and it setting the trusted origin does not seem to be working properly.

**Comment by rcoulsell** [comment]
# Solved

## Hopefully this helps someone else out!!!

I completely missed the fact that you have to manually pass forward post data from forms to the proxy (thought it would do this automatically). Plus node/arango did something weird when you fetched the post body and append a :"" to the end of the value. So you have to manually remove it.

// =====================================
// ArangoDB query interface Route ========
// =====================================
// Add the following to the arangodb config file /etc/arangodb3/arangodb.conf
// [frontend]
// proxy-request-check = false
// [http]
// trusted-origin = \*
// trusted-origin = all

// Create the proxy
var httpProxy = require('http-proxy');
var proxy = httpProxy.createProxyServer();

// Catch requests, massage the login form json, and pass along to the proxied server
proxy.on('proxyReq', function(proxyReq, req, res, options) {
    var bodyData;
    var contentType = proxyReq.getHeader('Content-Type');

    if (!req.body || !Object.keys(req.body).length) {
        return;
    };
    if (contentType == 'application/json; charset=UTF-8' || contentType == 'application/json') {
        bodyData = JSON.stringify(req.body);
    };

    if (contentType == 'application/x-www-form-urlencoded; charset=UTF-8' || contentType == 'application/x-www-form-urlencoded') {
        bodyData = queryString.stringify(req.body);
    };

    // handle formatting issue with arangodb web form where it appends a :"" to the end of the credentials (i.e. {"username","root","password","password"}:"")
    if (bodyData) {
        if (req.url.substr(-23) == '/_db/_system/_open/auth') {
            proxyReq.write(String(Object.keys(req.body)[0]))
        } else {
            proxyReq.write(bodyData);
            proxyReq.end();
        };
    };
});

  proxy.on('error', function(e) {
      console.log(e);
  });

  // note I have two functions to ensure that a user is logged in and has a specific role before they can login to the database. Insert authentication functions / middleware before the function(req, res) below
  app.all('\*/_db/\*', function(req, res) { \\, isLoggedIn, inRole('admin')
      proxy.web(req, res, {target: 'http://127.0.0.1:8529'});
  });

**Comment by Simran-B** [comment]
@rcoulsell Hey, great that you found a way. Would you like to contribute this to our Cookbook? https://github.com/arangodb/arangodb/tree/devel/Documentation/Books/Cookbook
