### ISSUE TITLE
FATAL failed to locate javascript.startup-directory directory

### ISSUE THREAD

**Issue by undeadindustries** [arangodb/arangodb#8725]
## My Environment

* __ArangoDB Version__:        3.4.4.

* __Operating System__:   Win10 64 latest updates
* __Total RAM in your machine__:     32
* __Disks in use__:        optane
* __Used Package__:           Windows

When trying to launch arangosh, I get this error:
`2019-04-10T13:43:40Z [17668] FATAL failed to locate javascript.startup-directory directory, its neither available in 'C:\Users\myuser\AppData\Local\ArangoDB3-client 3.4.4\/share/arangodb3/js' nor in 'C:\Users\myuser\AppData\Local\ArangoDB3-client 3.4.4\C:\Users\myuser\AppData\Local\ArangoDB3-client 3.4.4\share\arangodb3\js'`

I installed arango as I did on my other systems. Just a normal install...

Arango webtool works. Connecting to the arango server via a golang app, and creating collections works...

Any ideas?

Thanks!

**Comment by KVS85** [comment]
Hello @undeadindustries,

Thank you for reaching us out. Currently, you can workaround this by changing `startup-directory = @ROOTDIR@/share/arangodb3` to `startup-directory = @ROOTDIR@/share/` in `C:\Users\myuser\AppData\Local\ArangoDB3-client 3.4.4\etc\arangodb3\arangosh.conf`.

That would be fixed furthermore.

**Comment by undeadindustries** [comment]
That got me a different error:
  __ _ _ __ __ _ _ __   __ _  ___  ___| |__
 / _` | '__/ _` | '_ \ / _` |/ _ \/ __| '_ \
| (_| | | | (_| | | | | (_| | (_) \__ \ | | |
 \__,_|_|  \__,_|_| |_|\__, |\___/|___/_| |_|
                       |___/

arangosh (ArangoDB 3.4.4 [win64] 64bit, using build tags/v3.4.4-0-gc6abdf4449, VPack 0.1.33, RocksDB 5.16.0, ICU 58.1, V8 5.7.492.77, OpenSSL 1.1.0j  20 Nov 2018)
Copyright (c) ArangoDB GmbH

Connected to ArangoDB 'http+tcp://127.0.0.1:8529' version: 3.4.4 [server], database: '_system', username: 'root'
```

2019-04-12T13:22:12Z [26376] ERROR cannot locate file 'common\bootstrap\scaffolding.js', path: 'C:\Users\myuser\AppData\Local\ArangoDB3-client 3.4.4\/share/': No error
2019-04-12T13:22:12Z [26376] ERROR unknown script 'common\bootstrap\scaffolding.js'
2019-04-12T13:22:12Z [26376] FATAL cannot load JavaScript file 'common/bootstrap/scaffolding.js'
```

**Comment by zbauer91** [comment]
I just installed the Client Tools. I started working with a docker container of the server after #8718 prevented me from working locally, but I still need the tools to interact with the information in our development environment. 

I'm getting identical errors after initial install, and after the listed workaround. 

- **ArangoDB Version**: 3.4.5
- **Operating System**: Win10 64 Enterprise latest updates
- **Total RAM in your machine**: 16 Gb
- **Used Package**: Windows

**Comment by zbauer91** [comment]
While not a great option, I find I still have no issues whatsoever running 3.3.21

**Comment by Simran-B** [comment]
Can you post the configuration file (arangosh.conf) and the exact command you used to run arangosh?

**Comment by undeadindustries** [comment]
I type: arangosh
or I click on the desktop shortcut that the install creates.

```
[console]
pretty-print = true

[server]
endpoint = tcp://127.0.0.1:8529
authentication = true
# username = root
# password = 

[log]
# file = -

[javascript]
#startup-directory = @ROOTDIR@/share/arangodb3/js
startup-directory = @ROOTDIR@/share/
```

**Comment by felixlinker** [comment]
I had the same issue. I also tried the solution suggested by @KVS85 and ended up with the same next error message as you, @undeadindustries. However, after looking at the error message that `/common/...` can't be found and looking at the directory, I found that the following settings works for me:

```
startup-directory = @ROOTDIR@/share/arangodb3/
```

I'm using `arangosh` version `3.4.7` on Windows 10.

**Comment by rragan-clearcore** [comment]
I'm getting this error on Ubuntu. I used Ubuntu Software to install Arango. Here's the command and error:
<pre><font color="#8AE234"><b>rragan@rragan-HP-EliteDesk-800-G2-SFF</b></font>:<font color="#729FCF"><b>/snap/arangodb3/43/usr/bin</b></font>$ /snap/arangodb3/43/usr/bin/arangosh
Please specify a password: 
2020-04-13T09:24:30Z [7973] FATAL failed to locate javascript.startup-directory directory, its neither available in &apos;js&apos; nor in &apos;/snap/arangodb3/43/js&apos;
<font color="#8AE234"><b>rragan@rragan-HP-EliteDesk-800-G2-SFF</b></font>:<font color="#729FCF"><b>/snap/arangodb3/43/usr/bin</b></font>$ </pre>

**Comment by dothebart** [comment]
Hi @rragan-clearcore 
Please note that we no longer support snaps. Please use the provided debian packages.

**Comment by dothebart** [comment]
Please note that ArangoDB 3.4 is EOLed. [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) is available for download, with improved support for windows paths.
