### ISSUE TITLE
Switching accounts, can't find collections.

### ISSUE THREAD

**Issue by liulukuan** [arangodb/arangodb#8751]
## My Environment

* __ArangoDB Version__:        
* __Storage Engine__:             
* __Deployment Mode__:       
* __Deployment Strategy__:   
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:        
* __Total RAM in your machine__:        
* __Disks in use__:        
* __Used Package__:              

## Component, Query & Data

__Affected feature__:

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. 
2. 
3. 

__Problem__: Two accounts, 'root' and 'other', both accounts have access to a database, login and create collections and insert data using root account, then, I login to the same database using'other'account. I couldn't find the collections I had created before.

__Expected result__:

**Comment by maxkernbach** [comment]
Hi @liulukuan,

with that limited information it is quite difficult to investigate this issue.

1. Could you please fill out the information formular?
2. Which version and deployment mode are you using?
3. How did you set the user permissions?
4. Does this problem only occur accessing the WebUI or also via `arangosh`?

**Comment by Simran-B** [comment]
Please edit your post and add information about your setup and environment.

Did you check the user permissions using the root account? You may share a screenshot of the web UI.

**Comment by maxkernbach** [comment]
@liulukuan 

Since we have not heard back from you in a while, I am closing this issue for now.
In case you are still facing this problem, please provide the requested information and we will reopen.
