### ISSUE TITLE
ArangoDB installation of Service only (Ubuntu/Docker)

### ISSUE THREAD

**Issue by qohelet** [arangodb/arangodb#8757]
## My Environment

* __ArangoDB Version__:        3.4.1
* __Storage Engine__:             RocksDB 
* __Deployment Mode__:       Single Server 
* __Deployment Strategy__:   Manual Start in Docker
* __Operating System__:        Ubuntu 18.04
* __Disks in use__:        HDD
* __Used Package__:              Ubuntu

## Component, Query & Data

__Affected feature__:
Installation

__Problem__:
I'm using the [ArangoDB-Docker](https://hub.docker.com/_/arangodb) and have an Ubuntu-Server (Docker also) for the administration of the database.
So the Ubuntu-Server gets the DB-Files from the Arango-Docker mounted by default to its `/var/lib/arangodb3`. 

As I install arangodb on the Ubuntu-Server it wishes to create a new database and keeps asking for variables, etc. Is there an efficient way of just installing the Arango-DB Services in the Ubuntu-Docker and using the already existing database? (So not building a new Database)

**Comment by maxkernbach** [comment]
Hi @qohelet,

I am not sure if I understand your use-case correctly.

In case you want to only install ArangoDB Client Tools like arangosh, arangodump, arangorestore etc. and not the server itself, you can use the Client Tools package, which is available in the [download section](https://www.arangodb.com/download-major/ubuntu/).

Using these Client Tools, you can connect to your existing ArangoDB docker database server.

**Comment by qohelet** [comment]
@maxkernbach - thank you for the helpful answer. Yes, that's exactly what I was looking for.
Sorry for the delay in my answer. I'm able to make it run in docker and get the package from the server.

Now there's the additional question on how to set the link to the folder/address and port and credentials.

Thank you!

**Comment by qohelet** [comment]
@maxkernbach - what if I'm not connecting to a server but want to use an existing local database. 
I used Docker to mount the folder into the file-system. 

Related to the Server-Connection: Is there somewhere a config file in order to change the default values?

**Comment by maxkernbach** [comment]
You are trying to start an ArangoDB server inside of docker that is using the mounted folder as an existing local database directory, right?

In that case you can specify the path of your mounted directory with the option `--database.directory` by passing it to `arangod`.

Docker command (v3.4.5 single server, no authentication in this example, port 8529 specified):

```
docker run -e ARANGO_NO_AUTH=1 \
 -p <serverIP>:8529 \
 -v </path/to/mounted/database/folder>:</path/to/mounted/database/folder> \
 arangodb/arangodb:3.4.5 arangod \
 --server.endpoint tcp://0.0.0.0:8529\ --database.directory </path/to/mounted/database/folder>

**Comment by qohelet** [comment]
I think I wasn't clear enough about my current configuration, so here's everything.

I'm having two docker. The regular arangoDB-Docker from Dockerhub and an Ubuntu which should be responsible for the handling of the database and backups.
The Ubuntu is defined in a different Dockerfile.

As the ArangoDB-Docker is a minimal configuration I can't use it properly for the administration, so the Ubuntu is used for backup and arangosh-commands.

The docker-compose:
```
version: '3.2'
services:
  arangodb:
    image: arangodb
    ports:
      - "8112:8529"
    environment:
      - ARANGO_NO_AUTH=1
    volumes:
      - db-data:/var/lib/arangodb3
  arangodb_data:
    image: 'arango_ubuntu_backup'
    ports:
      - "8113:22"
    volumes:
      - db-data:/var/lib/arangodb
      - /opt/arangodb/save:/var/save
    build:
        context: ./docker
    command: tail -f /dev/null
volumes:
  db-data:      
```

./docker/dockerfile:

```
#
# Ubuntu Dockerfile
#
# https://github.com/dockerfile/ubuntu
#

# Pull base image.
FROM ubuntu:16.04

# Install.
RUN \
  sed -i 's/# \(.*multiverse$\)/\1/g' /etc/apt/sources.list && \
  apt-get update && \
  apt-get -y upgrade && \
  apt-get install -y build-essential && \
  apt-get install -y software-properties-common && \
  apt-get install -y byobu curl git htop man unzip vim wget  openssh-server  && \
  rm -rf /var/lib/apt/lists/*

RUN add-apt-repository main
RUN add-apt-repository universe
RUN add-apt-repository restricted
RUN add-apt-repository multiverse

RUN apt-get update

#ArangoDB stuff
RUN curl -OL https://download.arangodb.com/arangodb34/DEBIAN/Release.key && apt-key add - < Release.key
RUN echo 'deb https://download.arangodb.com/arangodb34/DEBIAN/ /' | tee /etc/apt/sources.list.d/arangodb.list
RUN apt-get install apt-transport-https 
RUN apt-get update
RUN apt-get install arangodb3-client

# Add files.

# Set environment variables.
ENV HOME /root

# Define working directory.
WORKDIR /root

# Define default command.
CMD ["bash"]

```

**Comment by dothebart** [comment]
Please note that ArangoDB 3.4 is EOLed and [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) is available.

Closing this as outdated.
