### ISSUE TITLE
Throughput very slow with Nodejs driver

### ISSUE THREAD

**Issue by averri** [arangodb/arangodb#8808]
[Arangodb_JMeter.zip](https://github.com/arangodb/arangodb/files/3098103/Arangodb_JMeter.zip)

## My Environment

* __ArangoDB Version__:        3.4.5
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server 
* __Deployment Strategy__:   ArangoDB Starter
* __Configuration__:               Default settings
* __Infrastructure__:               Laptop
* __Operating System__:        Windows 10, 64 bit
* __Total RAM in your machine__:        32Gb
* __Disks in use__:        SSD
* __Used Package__:              Windows install

## Component, Query & Data

__Affected feature__:
ArangoDB with Nodejs driver.

__AQL query (if applicable)__:
N/A

__AQL explain (if applicable)__:
N/A

__Dataset__:
A simple dataset: 

```
{
  "username": "Alex",
  "active": true
}
```

__Size of your Dataset on disk__:
Haven't measured, but it's quite small.

__Replication Factor & Number of Shards (Cluster only)__:
No replication.

## Steps to reproduce

1. Start one instance of ArangoDB, create a database **reviews** and a collection **users**.
2. Start Nodejs witht the provided code below: `node index.js`
3. Install [autocannon](https://github.com/mcollina/autocannon) for load test.
4. Run autocannon:

Create a file `body.json` with the following content to be used in the test:
```json
{
  "username": "Alex",
  "active": true
}
```

*Testing the endpoint that does not use the ArangoDB*
```
$ autocannon -c 50 -H Content-Type=application/json -i body.json -m POST http://localhost:3000/users-without-db
Running 10s test @ http://localhost:3000/users-without-db
50 connections

┌─────────┬──────┬───────┬───────┬───────┬──────────┬─────────┬──────────┐
│ Stat    │ 2.5% │ 50%   │ 97.5% │ 99%   │ Avg      │ Stdev   │ Max      │
├─────────┼──────┼───────┼───────┼───────┼──────────┼─────────┼──────────┤
│ Latency │ 9 ms │ 15 ms │ 27 ms │ 29 ms │ 15.92 ms │ 4.68 ms │ 56.26 ms │
└─────────┴──────┴───────┴───────┴───────┴──────────┴─────────┴──────────┘
┌───────────┬────────┬────────┬────────┬────────┬─────────┬────────┬────────┐
│ Stat      │ 1%     │ 2.5%   │ 50%    │ 97.5%  │ Avg     │ Stdev  │ Min    │
├───────────┼────────┼────────┼────────┼────────┼─────────┼────────┼────────┤
│ Req/Sec   │ 2503   │ 2503   │ 2953   │ 3969   │ 3044.28 │ 449.21 │ 2502   │
├───────────┼────────┼────────┼────────┼────────┼─────────┼────────┼────────┤
│ Bytes/Sec │ 693 kB │ 693 kB │ 818 kB │ 1.1 MB │ 843 kB  │ 124 kB │ 693 kB │
└───────────┴────────┴────────┴────────┴────────┴─────────┴────────┴────────┘
```

*Testing the endpoint that uses ArangoDB*
```
$ autocannon -c 50 -H Content-Type=application/json -i body.json -m POST http://localhost:3000/users-with-db
Running 10s test @ http://localhost:3000/users-with-db
50 connections

┌─────────┬───────┬───────┬───────┬───────┬──────────┬─────────┬──────────┐
│ Stat    │ 2.5%  │ 50%   │ 97.5% │ 99%   │ Avg      │ Stdev   │ Max      │
├─────────┼───────┼───────┼───────┼───────┼──────────┼─────────┼──────────┤
│ Latency │ 35 ms │ 49 ms │ 72 ms │ 75 ms │ 50.14 ms │ 9.42 ms │ 89.54 ms │
└─────────┴───────┴───────┴───────┴───────┴──────────┴─────────┴──────────┘
┌───────────┬────────┬────────┬────────┬────────┬────────┬─────────┬────────┐
│ Stat      │ 1%     │ 2.5%   │ 50%    │ 97.5%  │ Avg    │ Stdev   │ Min    │
├───────────┼────────┼────────┼────────┼────────┼────────┼─────────┼────────┤
│ Req/Sec   │ 815    │ 815    │ 975    │ 1194   │ 985.8  │ 93.42   │ 815    │
├───────────┼────────┼────────┼────────┼────────┼────────┼─────────┼────────┤
│ Bytes/Sec │ 249 kB │ 249 kB │ 297 kB │ 364 kB │ 301 kB │ 28.5 kB │ 249 kB │
└───────────┴────────┴────────┴────────┴────────┴────────┴─────────┴────────┘
```

5. Verify that the service throughput using ArangoDB is very slow compared to another endpoint that does not use the DB.

Code for reproducing the issue (`index.js`) :
```javascript
const feathers = require('@feathersjs/feathers');
const express = require('@feathersjs/express');
const socketio = require('@feathersjs/socketio');
const app = express(feathers());
const Database = require('arangojs').Database;

const appPort = 3000;
const db = new Database('http://127.0.0.1:8529');

db.useDatabase("reviews");
db.useBasicAuth("root", "root");

app.use(express.json());
app.use(express.urlencoded({extended: true}));
app.configure(express.rest());
app.configure(socketio());
app.use(express.errorHandler());
app.use(express.errorHandler());

// A service to use as a baseline for the server throughput.
class UsersWithoutDB {

    async create(data, params) {
        return data
    }
}

// A service to verify the throughput using the database.
class UsersWithDB {

    constructor(collection) {
        this.collection = collection;
    }

    async create(data, params) {
        return await this.collection.save(data)
    }
}

app.use('/users-without-db', new UsersWithoutDB());
app.use('/users-with-db', new UsersWithDB(db.collection('users')));

app.listen(appPort).on('listening', () => {
    console.log(`Server listening on localhost:${appPort}`);
});
```

__Problem__:

The throughput for inserting into ArangoDB is very slow, compared to a similar service endpoint that does not use the DB.

- The throughput without using ArangoDB is 3044 req/s in the tested machine.
- The throughput using ArangoDB is 985 req/s in the same machine.

__Expected result__:

I believe that the throughput using one node of ArangoDB should be higher, it should be less than the baseline, but not 70% lower than it.

**Comment by averri** [comment]
I have attached the JMeter script to do the load test. There are two HTTP requests: one for the endpoint without the ArangoDB and another endpoint using ArangoDB. It needs to do one test for each endpoint at a time, enabling and disabling each HTTP Request node in the script.

![image](https://user-images.githubusercontent.com/1898447/56424455-3da8a100-62a8-11e9-9374-17013de94dc2.png)

**Comment by averri** [comment]
Please ignore the attached file `Arangodb_JMeter.zip`, that was the first attempt to reproduce the issue. Now I have updated the description using `autocannon` which is more easy to use.

**Comment by dothebart** [comment]
Hi, 
Please note that you should use a ramp to benchmark the maximum throughput your system is able to deliver.
If you simply fire at it in a given request rate, you may overrun the system and get worse replies than if you would have used the throughput that the system actually can stand. 
You should also add a short warmup phase for the system to establish tcp connections, etc. 
Please have a look at my blogpost series where I explain all this in detail:
https://www.arangodb.com/2017/10/performance-analysis-pyarango-usage-scenarios/

(Its using the python driver, however what you want to measure and how to obtain values etc. can easily be translated to a nodejs application)

**Comment by maxkernbach** [comment]
Hi @averri,

has the latest message been helpful?
Did you have a chance to modify your benchmark according to the blogpost?

**Comment by averri** [comment]
Hi @maxkernbach, yes the message from @dothebart  is very useful, I really appreciate that. I didn't have time to reproduce yet according to the blogpost, but I'm looking forward to do it soon. I'll post the results here.

**Comment by OmarAyo** [comment]
Hi @averri 

I am sending this message to check if you had the chance to reproduce according to the blogpost posted by dothebart ?

Best,

**Comment by OmarAyo** [comment]
Hi @averri 

Closing this issue for now since we have not heard back from you in a while.
In case the problem persists, please respond to the latest comments and we will reopen.
