### ISSUE TITLE
Change data location

### ISSUE THREAD

**Issue by gitman23** [arangodb/arangodb#8817]
## My Environment

* __ArangoDB Version__:       3.4.5 
* __Storage Engine__:            MMFiles 
* __Deployment Mode__:       Single Server 
* __Deployment Strategy__:   Manual Start 
* __Operating System__:        Ubuntu 18.04 
* __Total RAM in your machine__:       240Gb.  
* __Disks in use__:        1xSSD | 1xHDD.
* __Used Package__:         Ubuntu .deb

__Problem__:
After changing the database location in "/etc/arangodb3/arangod.conf" into this:
-------------------------------------------------
[database]
#directory = /var/lib/arangodb3
directory = /home/new/path
-------------------------------------------------
I cannot connect anymore.

Getting this:
----------------
$ curl --dump - -X GET http://127.0.0.1:8529/_api/version && echo
HTTP/1.1 401 Unauthorized
X-Content-Type-Options: nosniff
Server: ArangoDB
Connection: Keep-Alive
Content-Type: application/json; charset=utf-8
Content-Length: 95
{"error":true,"errorNum":11,"errorMessage":"not authorized to execute this request","code":401}

I followed the instruction here:
https://github.com/arangodb/arangodb/issues/5954

Unfortunately I have no idea how to fix and have no access to the log file. Any help is highly appreciated. Have not enough space on the main hard drive so I want the data on another drive which I symlinked to /home.... .
Thanks!

**Comment by dothebart** [comment]
Hi, 
please stop arangod, and run `arango-secure-installation` to interactively set a password for the root user.

**Comment by gitman23** [comment]
This worked. Thanks a lot! :-)

**Comment by cubeover** [comment]
I have noticed problem - if I move the whole /var/lib/arangodb3 some place else, update the [database] in /etc/arangodb3/arangod.conf. the unit start script still insists (hardcoded) on fixing permissions of /var/lib/arangodb3 and FAILS.
This means Arango cannot be started without [useless, empty, hardcoded] /var/lib/arangodb3 directory.
Not sure why is this the case, IMO it should be reading the .conf before it knows what permissions to fix.
![image](https://user-images.githubusercontent.com/60209810/95829778-6ff26c00-0d82-11eb-9213-2b7c4ea1b97a.png)

**Comment by dothebart** [comment]
Hi, 
this is a workaround for a foot gun users frequently ran into. They start arangod once as root so they see interactively whats it doing, or use `--console` to do things to it locally. Afterwards file permissions will be broken. If you replace the script, dpkg should keep your script. 

Please don't attach unrelated errors to other git issues, rather create a new one instead.
