### ISSUE TITLE
Can't edit Edges in WebView (any more?)

### ISSUE THREAD

**Issue by qohelet** [arangodb/arangodb#8841]
## My Environment

* __ArangoDB Version__:        3.4.1
* __Storage Engine__:             RocksDB 
* __Deployment Mode__:       Single Server 
* __Deployment Strategy__:   Manual Start in Docker
* __Operating System__:        Ubuntu 18.04
* __Disks in use__:        HDD
* __Used Package__:              Ubuntu

## Component, Query & Data

__Affected feature__:
Graph Viewer

__Problem__:
Maybe my memory is playing tricks to me - but I have the feeling I used to be able to edit Edges in the Graph Viewer.
Right now (login as root) I'm just able to modify documents. A click on the Edge gives me on the bottom part information on the key and which attribute it has, but no option to do modifications.

The routeplanner-example for instance has this option. 

On which parameter does it depend whether or not I'm able to edit it?

Thank you

**Comment by Simran-B** [comment]
If you click on an edge, a radial menu with two options should pop up:

![image](https://user-images.githubusercontent.com/7819991/56718882-ef7c1d80-673f-11e9-90e3-b70f7667f5a7.png)

A click on the pencil icon opens the inline document editor.

Is is pencil option missing for you? Can you post a screenshot?
If it occurs with a specific graph only, can you share it?

You can try the latest version and another browser to see if it makes a difference.

**Comment by qohelet** [comment]
This is getting more and more weird. 

Test 1:
Regularly opening the graph and clicking on the edge: Pencil appears

Test 2:
Loading full graph: Pencil appears

Test 3:
Changing the Node-Label in the menu from "_key" to "Name": No pencil icon

Test 4:
Loading full graph witch changed Node-Labels: No pencil icon

Here's the image:
![image](https://user-images.githubusercontent.com/13061154/56723388-273b9300-6749-11e9-8771-cabbaa4f079e.png)

**Comment by Simran-B** [comment]
I just saw some odd behavior as well, but I don't think it's related to the node label option.

At first, hovering an edge highlights it, and the radial menu works. However, it sometimes gets stuck. Loading the full graph or changing any of the options fix the hovering, but then the radial menu doesn't show up at all anymore. This odd behavior seems to persist even if you reopen the graph until you refresh the entire page.

Chrome 73 on Windows and ArangoDB 3.4.4

@hkernbach @KVS85 Have you seen this behavior before?

**Comment by qohelet** [comment]
Is there any workaround or possible explanation for this yet?

**Comment by hkernbach** [comment]
Will be fixed in: https://github.com/arangodb/arangodb/pull/8979
& https://github.com/arangodb/arangodb/pull/8980

**Comment by qohelet** [comment]
I'm running the Docker-Image of ArangoDB. What's the preferred way of updating it?

**Comment by hkernbach** [comment]
It is not released yet. This patch will be included when we're publishing 3.4.6.

**Comment by maxkernbach** [comment]
Hi @qohelet,

version 3.4.6, which includes a fix for this issue, has been released.
In case you are still facing this problem, please comment and we will reopen it.

Regarding the docker upgrade: One possible way is to pick the old database and use it as bounded `/data` volume for a new docker container (after old container is stopped). Start the new docker container with the option `--server.upgrade-auto` to perform the upgrade.

You could also use [arangodump](https://www.arangodb.com/docs/stable/programs-arangodump.html) to create a backup in your old version docker deployment and restore this backup using [arangorestore](https://www.arangodb.com/docs/stable/programs-arangorestore.html) in your new version docker deployment.

**Comment by qncm** [comment]
Hello,
I just upgraded ArangoDB to 3.6.3-1 and see no pencil button for edges. In 3.3.25 it was visible until I set startnode. Now it never appears.
Also it would be nice to have delete button for edges.
Server OS: Debian 8. 
Client OS: OpenSUSE 42.1
Browsers: FIrefox 68.8 ESR, Google Chrome 74.0, Chromium 81.0, all plugins disabled.

**Comment by hkernbach** [comment]
Fix will be part of 3.6.4. 
PR: https://github.com/arangodb/arangodb/pull/11615

**Comment by hkernbach** [comment]
```
Also it would be nice to have delete button for edges.
```

Yes true, we could add that. I'll create a feature request ticket.

**Comment by maxkernbach** [comment]
Hi @qncm,

Thanks for reporting.
Version 3.6.4, which includes a fix for this issue, has been released.

From the [Changelog](https://github.com/arangodb/arangodb/blob/25e711db88b5f43915cf61b2e895fe9e86b35051/CHANGELOG#L84):

> Fixed ability to edit graph edge in Graph Viewer of web UI.

Please find the latest release in the [download section](https://www.arangodb.com/download/).
