### ISSUE TITLE
How to delete a attribute in document with AQL?

### ISSUE THREAD

**Issue by wjx-git** [arangodb/arangodb#8842]
__Problem__:

__Expected result__:

**Comment by ObiWahn** [comment]
Closing because of missing descriptions. What is the users trouble with UPDATE / REPLACE?

**Comment by wjx-git** [comment]
> Closing because of missing descriptions. What is the users trouble with UPDATE / REPLACE?

Don't closed

**Comment by wjx-git** [comment]
Don't closed it, if you don't know, just go away!




------------------ 原始邮件 ------------------
发件人: "Jan Christoph Uhde"<notifications@github.com>; 
发送时间: 2019年4月25日(星期四) 中午12:45
收件人: "arangodb/arangodb"<arangodb@noreply.github.com>; 
抄送: "It's My Life"<1319953912@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [arangodb/arangodb] How to delete a attribute in document withAQL? (#8842)




Closing because of missing descriptions. What is the users trouble with UPDATE / REPLACE?

**Comment by Simran-B** [comment]
We close issues without a proper description as they are considered invalid. You can edit your initial post to provide the necessary information and re-open a ticket, but please don't waste our time by opening issues without any information.

**Comment by wjx-git** [comment]
I think this question is just about AQL language. If you are good at AQL, you can understand what the question mean and give the answer without any other information. You can tell me the question is invalid, but you can not closed it. I have the rights to decide close or keep open it.




------------------ 原始邮件 ------------------
发件人: "Simran"<notifications@github.com>; 
发送时间: 2019年4月25日(星期四) 下午3:25
收件人: "arangodb/arangodb"<arangodb@noreply.github.com>; 
抄送: "It's My Life"<1319953912@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [arangodb/arangodb] How to delete a attribute in document withAQL? (#8842)




We close issues without a proper description as they are considered invalid. You can edit your initial post to provide the necessary information and re-open a ticket, but please don't waste our time by opening issues without any information.

**Comment by Simran-B** [comment]
Just an issue title is not sufficient. It lacks an example (what you tried so far), doesn't go into details like whether you want to delete a top-level attribute or nested attribute and also fails to provide any details about the version and environment. The question could also be about using AQL with the ArangoJS driver in Node.js, which would open up more possible answers to this question.

If you don't follow our rules, then you have to accept that we may close issues. GitHub is a tool for us after all, and issues are primarily for reporting bugs. Questions like yours are better suited for [StackOverflow](https://stackoverflow.com/questions/ask?tags=arangodb,aql). A proper description of your problem and what you tried so far is also required there BTW.

**Comment by wjx-git** [comment]
Thanks, what time are you now?




------------------ 原始邮件 ------------------
发件人: "Simran"<notifications@github.com>; 
发送时间: 2019年4月25日(星期四) 下午5:01
收件人: "arangodb/arangodb"<arangodb@noreply.github.com>; 
抄送: "It's My Life"<1319953912@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [arangodb/arangodb] How to delete a attribute in document withAQL? (#8842)




Just an issue title is not sufficient. It lacks an example (what you tried so far), doesn't go into details like whether you want to delete a top-level attribute or nested attribute and also fails to provide any details about the version and environment. The question could also be about using AQL with the ArangoJS driver in Node.js, which would open up more possible answers to this question.
 
If you don't follow our rules, then you have to accept that we may close issues. GitHub is a tool for us after all, and issues are primarily for reporting bugs. Questions like yours are better suited for StackOverflow. A proper description of your problem and what you tried so far is also required there BTW.
