### ISSUE TITLE
Query running slowly - only on one core

### ISSUE THREAD

**Issue by gitman23** [arangodb/arangodb#8882]
My first tests with arangodb :)

## My Environment

* __ArangoDB Version__:        3.4.5
* __Storage Engine__:             RocksDB 
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   ArangoDB Starter

* __Operating System__:        Ubuntu 18.04
* __Total RAM in your machine__:        256Gb
* __Disks in use__:        1xSSD + 1HDD. 
* __Used Package__:              Ubuntu library

__AQL query (if applicable)__:
127.0.0.1:8529@_system> db._query('FOR airport IN 2..2 OUTBOUND \'airports/LAX\' flights RETURN DISTINCT airport.name').toArray()

__Problem__:
Running this query (airports reachable via 2 hops to LAX) I have to wait about 2-3 minutes for the result. However, only 2-3% of CPU and memory each is used while the query runs. So I assume only 1 of the 20 cores is active. Want to have it executed using all cores. How can I do it? Is there a parameter I need to add when starting arangod or/and when starting arangosh?

__Expected result__:
Much faster result

Thank you!

**Comment by gitman23** [comment]
Is there a better place where to ask beginner questions?
Appreciate any hint ... Thanks!

**Comment by OmarAyo** [comment]
Hi @gitman23 

Thanks for using ArangoDB, in order to start analyzing can you please provide the execution plan and the profile output of that query ?

Best,

**Comment by OmarAyo** [comment]
Hi @gitman23 

Closing this issue for now since we have not heard back from you in a while.
In case the problem persists, please respond to the latest comments and we will reopen.
