### ISSUE TITLE
Collection, document, and subdocument-level security

### ISSUE THREAD

**Issue by minnownoir** [arangodb/arangodb#891]
The database needs to handle authorzization at three levels -- collection, document, and document path.  It cannot be left up to the application.  It must be supported for both application "drivers" (e.g., Java development) and ad-hoc queries (e.g., AQL).

Collection-level security:  The database should prevent users from being able to search collections to which they're not entitled.  Most document databases have limited/unreliable support for this.

Document-level security:  The database should prevent users from being able to search documents to which they're not entitled.  Most document databases don't support this.

Subdocument-level security (e.g., cell-level security in Accumulo):  The database should prevent users from being able to access parts of a single document to which they're not entitled.  For example, in a healthcare system with each patient record being materialized as a single document, the doctor should be able to see all of the patients PHI,but researchers should only be able to see .  Few databases of any striple handle this.  It's huge for law enforcement, intel, defense, and healthcare fields, where organization have been manually and unnaturally splitting/duplicating data around authorization patterns as opposed to having one copy of the data and having a database that could police access to specific fields.

**Comment by graetzer** [comment]
From 3.2 onwards we do support collection-level security.
Finer grained access restrictions on a document or sub-document level are not planned
since this would negatively affect performance

**Comment by pluma** [comment]
For domain specific permissions also see the guide for creating a Foxx service with fine grained permissions in the updated training center: https://www.arangodb.com/foxx-fine-grained-permissions/
