### ISSUE TITLE
ArangoSpark.saveDF() failed to update data if write multi times with new properties of some document.

### ISSUE THREAD

**Issue by zjuskm** [arangodb/arangodb#8922]
## My Environment

* __ArangoDB Version__:        3.4.5 
* __Storage Engine__:             RocksDB
* __Deployment Mode__:        Single Server
* __Deployment Strategy__:   
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:        MacOS 10.14.3 
* __Total RAM in your machine__:        
* __Disks in use__:        
* __Used Package__:              

## dependency
* __arangodb-spark-connector__:
           
`<groupId>com.arangodb</groupId>
            <artifactId>arangodb-spark-connector</artifactId>
            <version>1.0.8</version>`
> 

* __spark.versioin__:
<spark.version>2.4.0</spark.version>
* __language__:
Scala

## Component, Query & Data

__Affected feature__:

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. 
2. 
3. 

__Problem__:
When I use ArangoSpark.saveDF(dataframe,COLLECTION,WriteOptions(DB)) to update data already in ArangoDB, if the documents has new properties, then it can not write again because conflict key unique.

Any suggestions?

__Expected result__:

**Comment by maxkernbach** [comment]
Hi @zjuskm,

in order to investigate this issue, could you please provide the following information?

-  Fill out the information template (e.g. ArangoDB Version, storage engine, deployment ....)
- Spark connector version
- Are you using Java or Scala?
- Is this issue reproducible? Optimally, could you provide a script to reproduce this issue?

**Comment by zjuskm** [comment]
> Hi @zjuskm,
> 
> in order to investigate this issue, could you please provide the following information?
> 
> * Fill out the information template (e.g. ArangoDB Version, storage engine, deployment ....)
> * Spark connector version
> * Are you using Java or Scala?
> * Is this issue reproducible? Optimally, could you provide a script to reproduce this issue?

Hi @maxkernbach  
Sorry for answer late. I have updated the problem descrpition in my first original problem.
The code of the problem is very simple, just one line: ArangoSpark.saveDF(dataframe,COLLECTION,WriteOptions(DB)) 
in which, dataframe is the spark data structure, variable COLLECTION is th collection name, variable DB is the database name.  
The scene is very simple, you can use the following json, use spark to transform to dataframe, and use the filed "id" as "_key", use ArangoSpark.saveDF() API to write to ArangoDB.
{"id":"1", "name":"a"},
{"id":"2", "name":"b"},
{"id":"3", "name":"c"},
{"id":"4", "name":"d"},
{"id":"5", "name":"e"}

After written, change some value but the same _key value, for example:
{"id":"1", "name":"aa"},
{"id":"2", "name":"b"},
{"id":"3", "name":"cc"},
{"id":"4", "name":"dd"},
{"id":"5", "name":"e"}
Then if you use ArangoSpark.saveDF() API to write the new data to ArangoDB, it can not be written.
So I think it may need a ArangoSpark.updateDF() API for  update need.

**Comment by rashtao** [comment]
Sorry for the late reply, Insert-Update or Insert-Replace is not implemented yet in the Spark connector (https://github.com/arangodb/arangodb-spark-connector/issues/22).
Nevertheless you can specify the desired `WriteOptions.Method` when you call `saveDF()`. It supports the following values:
-    `WriteOptions.INSERT`
-    `WriteOptions.UPDATE`
-    `WriteOptions.REPLACE`

Related reference doc: https://www.arangodb.com/docs/stable/drivers/spark-connector-reference-scala.html

**Comment by dothebart** [comment]
Closing with the availability of [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/)
