### ISSUE TITLE
`frontendConfig.basePath` is duplicated for users API call

### ISSUE THREAD

**Issue by Yogu** [arangodb/arangodb#8941]
## My Environment

* __ArangoDB Version__:        3.4.5
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start in Docker
* __Configuration__:   ArangoDB is behind a reverse proxy on a specific path
* __Used Package__:              Docker - official Docker library -->

## Problem

The Users section in aardvark does not work if `frontendConfig.basePath` is set because it is applied twice: once in [`ArangoUsers.fetch()`](https://github.com/arangodb/arangodb/blob/6d197a2d99fbb5090229de895012849c2f76ecbe/js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoUsers.js#L23) and once in `arangoHelper.databaseUrl` (which is called by ArangoUsers.fetch()

**Comment by RudySchockaert-EngieIT** [comment]
**\arangodb\js\apps\system\_admin\aardvark\APP\frontend\js\collections\arangoUsers.js**
**lines 26,28,30** : 
arangoHelper.databaseUrl(frontendConfig.basePath + '/_api/user/'
-->
arangoHelper.databaseUrl('/_api/user/'

Same in **arangodb\js\apps\system\_admin\aardvark\APP\frontend\js\collections\arangoQueries.js**
**lines 42 & 44**

**Comment by Yogu** [comment]
@RudySchockaert-EngieIT  I guess the `arangoQueries` occurrence breaks stored queries, right? Incidentially, we also discovered this problem today.

**Comment by RudySchockaert-EngieIT** [comment]
That is correct. After my patch it is working again.

**Comment by zwali-sl** [comment]
I am accessing ArangoDB via proxy and in Aardvark, the query tool is appending the base path twice like this /dev/arango-web/_db/GDELT-Outlink-Graph-Hashed/dev/arango-web/_api/user/root. Is there a fix for this?

I am using community edition 3.6.1.

**Comment by Simran-B** [comment]
The pull request was merged for v3.7.1-beta.1 and ArangoDB v3.7.1 was meanwhile released, so the fix should be available from this version.
