### ISSUE TITLE
file-descriptors limit is too low

### ISSUE THREAD

**Issue by santo74** [arangodb/arangodb#8965]
## My Environment

* __ArangoDB Version__: 3.4.5
* __Storage Engine__: RocksDB
* __Deployment Mode__: Single Server
* __Deployment Strategy__: ArangoDB Starter
* __Configuration__:
* __Infrastructure__: Openstack
* __Operating System__: Ubuntu 16.04
* __Total RAM in your machine__: 8GB
* __Disks in use__: SSD
* __Used Package__: TAR package

## Component, Query & Data

__Affected feature__:
General operation

## Steps to reproduce

1. Increase limits (ulimit) on the system:
- set fs.file-max in /etc/sysctl.conf to 2097152
- update /etc/security/limits.conf:
```
* soft     nproc          131072    
* hard     nproc          131072   
* soft     nofile         131072   
* hard     nofile         131072
root soft     nproc          131072    
root hard     nproc          131072   
root soft     nofile         131072   
root hard     nofile         131072
```
- append "session required pam_limits.so" in /etc/pam.d/common-session
- reboot the system
2. ensure limits are correct after reboot:
ulimit -n : 131072
ulimit -Hn : 131072
ulimit -Sn : 131072
3. Install arangodb TAR package as explained, e.g; [here](https://www.arangodb.com/2019/01/run-multiple-versions-arangodb/) (only single server, no cluster)
4. start arangodb via systemctl (cfr above link)
5. look at the logs:

> file-descriptors (nofiles) hard limit is 4096, soft limit is 1024
> file-descriptors limit is too low, currently 1024, please raise to at least 8192 (e.g. ulimit -n 8192)

__Problem__:
arangodb ignores file descriptor limits

__Expected result__:
arangodb should use the correct file descriptor limits

__Notes__:
- arangodb runs under a dedicated user account "arangodb"
- the output of ulimit under the arangodb account gives the correct results
- With the older Ubuntu package on this same system (v3.3.23) limits are ok

**Comment by santo74** [comment]
@maxkernbach do you have any news about this issue?
The status is analyzing since 10 days now and it's blocking my upgrade from v3.3 to v3.4.

**Comment by dothebart** [comment]
Please note that the [Community Editions Subscription doesn't offer any SLA and thus no reaction times](https://www.arangodb.com/subscriptions/). If you require reaction times, please reach out to us.

Arangodb uses the [getrlimit](http://man7.org/linux/man-pages/man2/prlimit.2.html) systemcall to fetch the current settings from the kernel.

Its using `RLIMIT_NOFILE` for this:
```
This  specifies a value one greater than the maximum file descriptor number
that can be opened by this process.  Attempts (open(2), pipe(2), dup(2), etc.) 
to exceed this limit yield the error EMFILE. (Historically, this limit was named
RLIMIT_OFILE on BSD.)

Since Linux 4.5, this limit also defines the maximum number of file descriptors
that an unprivileged process (one  without  the  CAP_SYS_RE‐SOURCE  capability)
may  have  "in  flight"  to  other  processes,  by being passed across UNIX domain
sockets.  This limit applies to the sendmsg(2) system call. 
For further details, see unix(7).
```
So maybe your system either uses C-groups or per user settings to further limit these ulimit permissions.

**Comment by santo74** [comment]
@dothebart I understand the Community Edition has no guarantees regarding reaction times, but the status was changed to analysing 10 days ago, so I assumed this meant someone is looking into the issue.

Anyway, thanks for making time to provide extra information.

The thing is however that it works fine with v3.3 and not with v3.4 on the same system.
Maybe it's because I'm using the ArangoDB Starter for v3.4, but then that would mean the Starter is not correctly detecting the file-descriptors settings for some reason.
So something is either not working correctly or working differently in v3.4.

Other "system tweaks" are correctly detected, such as setting /sys/kernel/mm/transparent_hugepage/enabled to madvise

In case of C-groups or per user settings, the issue should also occur with v3.3, no?

**Comment by dothebart** [comment]
having a look at the stock systemd unit file we shitp it contains this: 

```
# system limits
LimitNOFILE=131072
LimitNPROC=131072
TasksMax=131072
```
which is missing in the articles mentioned unitfile. If you add that, does it fix the situation?

**Comment by santo74** [comment]
Thanks, that did it indeed!
I wasn't aware ulimits have to be set via the unit file in case of systemd services.
AFAIK the installation/deployment guides don't mention this either.

**Comment by dothebart** [comment]
thanks for confirming, will fix the documentation.

**Comment by santo74** [comment]
Great, thanks for your help!

**Comment by dothebart** [comment]
@neunhoef  stated: All known places have been fixed.
