### ISSUE TITLE
Query greek words with accent marks

### ISSUE THREAD

**Issue by eafiontzi** [arangodb/arangodb#8982]
## My Environment

* __ArangoDB Version__:      3.1.27  
* __Storage Engine__:           MMFiles
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   
* __Configuration__:               
* __Infrastructure__:               own
* __Operating System__:        Debian
* __Total RAM in your machine__:        8Gb. 
* __Disks in use__:        SSD 
* __Used Package__:              

## Component, Query & Data

__Affected feature__:

__AQL query (if applicable)__:
FOR d IN page FILTER d.name LIKE "%αρχικη%" RETURN d

__AQL explain (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. 
2. 
3. 

__Problem__:
I would like to know if there is a way in ArangoDB to query for Greek accent toning system so when I search for the word "αρχική" to get the results for "αρχικη" as well and vice versa. I tried using FULLTEXT index but with no luck. Thank you very much for your time.

__Expected result__:

**Comment by dothebart** [comment]
Hi, 
stemming can be done in arangosearch which in term uses snowflake library for that; However there is currently no greek support:
https://www.arangodb.com/docs/stable/views-arango-search-analyzers.html

So the currently best advise would be to do the stemming on the client side, and save a stemmed version of the text.

**Comment by eafiontzi** [comment]
Hi,

Thank you very much for your prompt reply, I will try to do it client side.

Best,
Eleni
