### ISSUE TITLE
Use Web-View on external website?

### ISSUE THREAD

**Issue by qohelet** [arangodb/arangodb#9015]
## My Environment

* __ArangoDB Version__:        3.4.1
* __Storage Engine__:             RocksDB 
* __Deployment Mode__:       Single Server 
* __Deployment Strategy__:   Manual Start in Docker
* __Operating System__:        Ubuntu 18.04
* __Disks in use__:        HDD
* __Used Package__:              Ubuntu

## Component, Query & Data

__Affected feature__:
Graph Viewer

__Problem__:
I would like to show dedicated Graphs like in the Graph Viewer on a website but couldn't find much in the documentation of how to do it.

It should be either a pre-configured web-view or the result of an AQL-Query. 

How would that be implemented? 

Thank you

**Comment by ageeye-cn** [comment]
I also need this feature

**Comment by dothebart** [comment]
ArangoDB uses http://sigmajs.org/ for its webinterface, this is the implementation: https://github.com/arangodb/arangodb/blob/devel/js/apps/system/_admin/aardvark/APP/frontend/js/views/graphViewer.js
http://js.cytoscape.org/ may be another alternative, currently [arangoexport](https://www.arangodb.com/docs/stable/programs-arangoexport-examples.html#export-xgmml) offers support for cytoscape desktop integration, for the .js version probably own glue code would be needed.

**Comment by dothebart** [comment]
Closing as solved.
