### ISSUE TITLE
Question: how to select fields from documents

### ISSUE THREAD

**Issue by averri** [arangodb/arangodb#9036]
Using the JavasScript driver, how to select fields from documents?

Example, using the `db.collection('users').byExample(...)`, I would like to retrieve just the field `name` of all documents that matches the example.

**Comment by graetzer** [comment]
AQL Query  'For doc IN users RETURN {name: doc.name}‘ works

**Comment by averri** [comment]
Thanks @graetzer. It would be great to have this feature in the API, like:

`db.collection('users').byExample({id: 3}, ['name', 'address.city'])` 
returns:
`{name: 'Alexandre', address: {city: 'Athlone'}}`

**Comment by Simran-B** [comment]
With the Simple Queries API being deprecated, don't expect any extensions to the JS driver. AQL is really the way to go and allows for more optimizations behind the scenes.
https://www.arangodb.com/docs/stable/http/simple-query.html#simple-query-by-example
