### ISSUE TITLE
swagger spec in api-docs.json contains bogus fields

### ISSUE THREAD

**Issue by noha** [arangodb/arangodb#9037]
## My Environment

* __ArangoDB Version__:        3.4.5

## Component, Query & Data

__Affected feature__:
api-docs.json swagger spec

## Steps to reproduce

1. Download from https://raw.githubusercontent.com/arangodb/arangodb/devel/js/apps/system/_admin/aardvark/APP/api-docs.json

__Problem__:
The swagger spec contains multiple bogus entries. 
- In /_api/wal/tail in parameter "global" the type is "bool" instead of "boolean"
- Several occurrences where the format is empty (... "format": ""...)
- Several occurrences where the format is either boolen, integer or object. boolean, integer and object are types. Most of the occurrences double the type in the format which shouldn't be

__Expected result__:
There should be only standard types and formats or arango specific ones. All the format occurrences can be deleted. That is how I correct my spec:

... | sed -e 's/"bool"/"boolean"/g' | sed -E 's/"format": "(boolean|integer|object)?",//g'

**Comment by dothebart** [comment]
Boolean fix: https://github.com/arangodb/arangodb/pull/9045

**Comment by noha** [comment]
bool has been changed to boolean. Number types have been specified better for numbers. There are still empty formats and for type boolean a format boolean. There is also a format uint64 which is not part of Swagger/OpenAPI. Formats can be custom but sometimes this is not intended. For parameters there is often a "format=string" and no type field. I think these should be called type=string. Shall I make individual tickets for different types of problems?

**Comment by Simran-B** [comment]
@noha Looks like you approved https://github.com/arangodb/arangodb/pull/9045 shortly after your comment, does that mean all of the problems are solved or is there still something to fix? Can you suggest required code changes?

**Comment by noha** [comment]
Actually I approved before my comment. It was accudental but I did not see how to remove that approval again. So I added a comment. I need to look into the last changed. Last time I looked there were still problems

**Comment by dothebart** [comment]
This was worked on and resolved last year, closing as outdated. 

Please note that [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) is available.
