### ISSUE TITLE
Arango Cluster Manual Start Issue

### ISSUE THREAD

**Issue by riteshapatel** [arangodb/arangodb#9039]
## My Environment
Arango Cluster 

* __ArangoDB Version__:        3.4.4
* __Storage Engine__:            RocksDB
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   Manual Start
* __Configuration__:               3 servers (agency / coordinators), 3 servers (db)
* __Infrastructure__:               AWS
* __Operating System__:        RHEL 8
* __Total RAM in your machine__:        t3.medium
* __Disks in use__:        EBS volumes
* __Used Package__:              REDHAT

__Problem__:

I deployed cluster as per `manual start documentation`. I noticed all commands in the manual start has `server.authentication` set to `false`. I did secure installation on each node with `arango-secure-installation`.  

I'd like to authenticate users / requests for the cluster. At the moment, the `url` leading to `web ui (coordinators)` is not asking for authentication. Is that by design? 

Additionally the `curl` requests are passing through without authentication. 

```
curl --dump - http://127.0.0.1:8529/_api/version

{"server":"arango","version":"3.4.4","license":"community"}
```

__Expected result__:

Users should be asked for authentication when going to `coordinator_ip:8529`. And `curl` calls should ask for `authorization header / token`. 

What am I missing? Here are the docs I used to deploy the cluster.

https://www.arangodb.com/docs/stable/deployment-cluster-manual-start.html

Thx,

Ritesh

**Comment by graetzer** [comment]
are you sure you are running the server with `--server.authentication true` ?

**Comment by riteshapatel** [comment]
That is what my question was, why are the manual cluster docs have `server.authentication false`? Any reason why we can't manually start a cluster with `authentication to true`?

Thx

**Comment by graetzer** [comment]
no there is no reason why you couldn't, just start it with `--server.authentication true` and use the same JWT secret for every server

**Comment by riteshapatel** [comment]
So what is the easiest way to get this done without killing `arango processes`? In other words, is there an endpoint or a process to enable authentication after the cluster is started? Thx

**Comment by graetzer** [comment]
no, you will need to restart the cluster.

**Comment by riteshapatel** [comment]
There is not a whole lot of documentation on how to restart a cluster. Any order in which we `start / stop` processes? Thx

**Comment by riteshapatel** [comment]
What are the steps to get cluster restart automatically on each boot? We are on RHEL.

**Comment by graetzer** [comment]
you can just do a `killall arangod` on all servers ? Or use `curl -XDELETE http://<host:port>/_admin/shutdown`

**Comment by riteshapatel** [comment]
And how about `restart on boot`? Do I run the scripts on each boot to start agencies / coordinators and join db servers? or there is an easier way to accomplish it?

**Comment by graetzer** [comment]
I think you might need to adjust the systemd config. You should go ask in the community slack channel for these sorts of things, GitHub issues are for bugs

**Comment by graetzer** [comment]
and checkout the starter https://www.arangodb.com/docs/stable/tutorials-starter.html

**Comment by riteshapatel** [comment]
I am not using a starter. We had to separate `database servers` and not sure if there is a way to accomplish that with `starter`. I'd love to use `starter` instead.
