### ISSUE TITLE
Allow unit testing of Foxx Apps

### ISSUE THREAD

**Issue by moonglum** [arangodb/arangodb#909]
This is a feature we want for quite some time now (@pluma also needs this really badly right now) – and now we have the technology :rocket: 

Scenario: You have a directory with the following structure:

* `models`
  * `a.js`
* `specs`
  * `a_spec.js`

If you `cd` into this directory and execute the following: 

`arangod --javascript.unit-tests spec/a_spec.js /tmp/tests`

It will work, the spec can be executed (and will be executed with Jasmine). You can require everything from our standard library. But: You can't require `a.js`. This is however crucial. It can be fixed by adding the current directory to the load path, I suggest the following:

`arangod --javascript.unit-tests spec/a_spec.js --javascript.add-to-load-path . /tmp/tests`

Now you can require the model file from the spec file as follows:

```javascript
var a = require('models/a');
```

Mind that this will only allow to write isolated tests (the way models and repos are structured, they are excellent for this kind of testing – controllers will be hard though as you have to provide a context). But it will be a good first step for even more testing of Foxx apps (we will need to provide a fake context etc.).

**Comment by pluma** [comment]
This has been solved via the mocha integration.

**Comment by moonglum** [comment]
:bow:
