### ISSUE TITLE
Can't deploy cluster pods with k8s yaml files

### ISSUE THREAD

**Issue by daoxian** [arangodb/arangodb#9102]

**Comment by daoxian** [comment]
I've tried yaml files of version 0.3.10, they didn't work either and the same phenomenon.

**Comment by daoxian** [comment]
The PVCs are in pending status:
 kubectl  -o wide get pvc
NAME                                    STATUS    VOLUME    CAPACITY   ACCESSMODES   STORAGECLASS   AGE
my-arangodb-cluster-agent-9ocdzmki      Pending                                                     13h
my-arangodb-cluster-agent-dkgjgry7      Pending                                                     19h
my-arangodb-cluster-agent-efaokm96      Pending                                                     19h
my-arangodb-cluster-agent-hmbrcplc      Pending                                                     19h
my-arangodb-cluster-agent-iv0rwoey      Pending                                                     14h
my-arangodb-cluster-agent-k6yrw5ma      Pending                                                     14h
my-arangodb-cluster-agent-l8e5bqyw      Pending                                                     14h
my-arangodb-cluster-agent-qhdsdi9i      Pending                                                     13h
my-arangodb-cluster-agent-wgwfw3gx      Pending                                                     13h
my-arangodb-cluster-dbserver-a0zzkknc   Pending                                                     14h
my-arangodb-cluster-dbserver-ctbswull   Pending                                                     19h
my-arangodb-cluster-dbserver-gmaqtxq5   Pending                                                     13h
my-arangodb-cluster-dbserver-icrprvcf   Pending                                                     19h
my-arangodb-cluster-dbserver-l6fg08n0   Pending                                                     13h
my-arangodb-cluster-dbserver-raoysydm   Pending                                                     14h
my-arangodb-cluster-dbserver-s7z1vbhm   Pending                                                     19h
my-arangodb-cluster-dbserver-u7cktemo   Pending                                                     13h
my-arangodb-cluster-dbserver-wtuwfqyk   Pending                                                     14h

**Comment by dothebart** [comment]
@daoxian usually its good style to [provide the answer to issues you opened if you were able to solve it](https://xkcd.com/979/) - would be nice if you could do so ;-)
