### ISSUE TITLE
Default value of TTL options?

### ISSUE THREAD

**Issue by ramazanpolat** [arangodb/arangodb#9103]
What are the default value of TTL index options?
* ``--ttl.frequency = ?``
* ``--ttl.max-total-removes = ?``
* ``--ttl.max-collection-removes = ?``?

## Windows 7 x64

* __ArangoDB Version__:        3.5 RC1
* __Storage Engine__: RocksDB
* __Deployment Mode__:    Single Server
* __Deployment Strategy__:ArangoDB Starter
* __Infrastructure__:            own
* __Operating System__:    Windows 7 x64
* __Total RAM in your machine__:        12GB
* __Disks in use__:       SSD
* __Used Package__:      other

**Comment by mpoeter** [comment]
These are the default values from the source code:
```
  frequency = 30 * 1000; // milliseconds
  maxTotalRemoves = 1000000;
  maxCollectionRemoves = 1000000;
```

**Comment by jsteemann** [comment]
Please note that you can always invoke the arangod executable with the `--help` command, e.g.
`arangod.exe --help` (note that for this arangod.exe must be in your path).

This will show the most common options with their default value. Using `--help-ttl` will show a per-section help only for the TTL indexes.

Right now (3.5.0-RC2) this prints
```
Section 'ttl' (TTL options)
  --ttl.frequency <uint64>                                    frequency (in milliseconds) for the TTL background thread invocation. a value of 0 turns the TTL background 
                                                              thread off entirely (default: 30000)
  --ttl.max-collection-removes <uint64>                       maximum number of documents to remove per collection (default: 1000000)
  --ttl.max-total-removes <uint64>                            maximum number of documents to remove per invocation of the TTL thread (default: 1000000)
  --ttl.only-loaded-collection <boolean>                      only consider already loaded collections for removal (default: true)
```

**Comment by dothebart** [comment]
The documentation also has it: https://www.arangodb.com/docs/devel/programs-arangod-options.html#ttl
