### ISSUE TITLE
Zoned Datetime format for TTL indexes?

### ISSUE THREAD

**Issue by ramazanpolat** [arangodb/arangodb#9105]
What is the date format for TTL indexes?

Currently, [documentation ](https://www.arangodb.com/arangodb-training-center/ttl-indexes/)shows this example:

```
db.sessions.insert({ 
  _key: "17dd66a43d620f1ab696f87236b72e14", 
  expireAt: "2019-06-23T10:24:05Z", 
  data: "..." 
});
db.sessions.insert({ 
  _key: "4d63e2387d894860343fa64924c34fc4", 
  expireAt: "2019-06-23T10:24:38Z", 
  data: "..." 
});
```

But it doesn't mention the zoned datetime format.

It may be one of these:

```
2019-06-23T10:24:38Z+3
2019-06-23T10:24:38Z+03
2019-06-23T10:24:38Z+0300
2019-06-23T10:24:38Z+03:00
2019-06-23T10:24:38Z+0300
```

or maybe even different than these.

## My Environment

* __ArangoDB Version__:        3.5.0-rc.2
* __Storage Engine__: RocksDB
* __Deployment Mode__:    Single Server
* __Deployment Strategy__: docker
* __Infrastructure__:            digitalocean
* __Operating System__:    Ubuntu 18.04
* __Total RAM in your machine__:        8GB
* __Disks in use__:       SSD

**Comment by jsteemann** [comment]
@ramazanpolat : the basic datetime format is `YYYY-MM-DDTHH:MM:SS`. If no timezone offset is specified, UTC time is assumed.
A datetime value can optionally be followed by a `Z` to explicitly indicate UTC time.
Alternatively, a timezone offset can be specified using the formats `+HH:MM` and `-HH:MM`. This indicates the difference in hours and minutes compared to UTC time.

Using your above example datetime value, the correct value would thus be `2019-06-23T10:24:38+03:00`.
I have also created a PR for our documentation to make this more clear: https://github.com/arangodb/docs/pull/46

**Comment by OmarAyo** [comment]
Hi @ramazanpolat 

Did you find what jsteemann's message useful ? The documentation PR was merged and it will be part of our official documentation

**Comment by ramazanpolat** [comment]
All ok.  Thanks.
