### ISSUE TITLE
Sparse Skiplist Index on multiple fields not used for FILTER + SORT query

### ISSUE THREAD

**Issue by x3cion** [arangodb/arangodb#9106]
## My Environment

* __ArangoDB Version__:        3.4.5
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       single server
* __Deployment Strategy__:   manual start
* __Configuration__:               default
* __Infrastructure__:               local development
* __Operating System__:        Windows 10
* __Total RAM in your machine__:        32Gb
* __Disks in use__:        SSD
* __Used Package__:             official setup

## Component, Query & Data

__Affected feature__:
AQL query using web interface

__AQL query (if applicable)__:
```
FOR doc IN testindex
    FILTER doc.id != null && doc.time != null
    SORT doc.id DESC, doc.time DESC
    RETURN doc
```

__AQL explain (if applicable)__:
```
Query String:
 FOR doc IN testindex
     FILTER doc.id != null && doc.time != null
     SORT doc.id DESC, doc.time DESC
     RETURN doc

Execution plan:
 Id   NodeType                  Est.   Comment
  1   SingletonNode                1   * ROOT
  2   EnumerateCollectionNode      4     - FOR doc IN testindex   /* full collection scan */
  3   CalculationNode              4       - LET #1 = ((doc.`id` != null) && (doc.`time` != null))   /* simple expression */   /* collections used: doc : testindex */
  4   FilterNode                   4       - FILTER #1
  5   CalculationNode              4       - LET #3 = doc.`id`   /* attribute expression */   /* collections used: doc : testindex */
  6   CalculationNode              4       - LET #5 = doc.`time`   /* attribute expression */   /* collections used: doc : testindex */
  7   SortNode                     4       - SORT #3 DESC, #5 DESC
  8   ReturnNode                   4       - RETURN doc

Indexes used:
 none

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   move-calculations-up-2
  4   move-filters-up-2
```

__Dataset__:
`[{"_key":"1","_id":"testindex/1","_rev":"_Ytfx2bq--_","time":"2019-05-27T08:41:21+0000","id":123},{"_key":"2","_id":"testindex/2","_rev":"_YtfyFaG--_","time":"2019-05-27T08:41:53+0000","id":123},{"_key":"3","_id":"testindex/3","_rev":"_YtfyhXa--_","time":"2019-05-27T08:41:21+0000","id":321},{"_key":"4","_id":"testindex/4","_rev":"_YtfywOG--_","time":"2019-05-27T08:42:35+0000","id":321}]`

__Size of your Dataset on disk__:
How? Neccessary?

## Steps to reproduce

1. Create a Document Collection with given Dataset
2. Create Skiplist Index with sparse = true on "id, time"
3. Run Explain

__Problem__:
While the FILTER excludes null on both id and time and the sort is on both, too, the index is not used.

__Expected result__:
Unless I missed something, the optimizer should consider using the skiplist index on "id, time", since null's are excluded and its sorted.

**Comment by jsteemann** [comment]
@x3cion : the index is not used by the query optimizer because it is defined sparse.
Sparse indexes may not include all documents in a collection. Any documentation for which the index attributes are set to `null` or are missing completely are excluded from sparse indexes. Thus the optimizer needs to be a bit careful when using a sparse index for producing results, as the results produced by a sparse index may miss some documents that may be returned if the index wouldn't be used.
When in doubt whether a sparse index can be used or not, the optimizer will choose result set correctness, i.e. it will not use the sparse index. This is in line with [the documentation](https://www.arangodb.com/docs/stable/indexing-index-utilization.html):

> Sparse indexes may or may not be picked by the optimizer in a query. As sparse indexes do not contain null values, they will not be used for queries if the optimizer cannot safely determine whether a FILTER condition includes null values for the index attributes. The optimizer policy is to produce correct results, regardless of whether or which index is used to satisfy FILTER conditions. If it is unsure about whether using an index will violate the policy, it will not make use of the index.

I admit in this case the filter conditions both clearly indicate the index attributes cannot be `null`, so the optimizer may well use the index here. However, it seems it is not smart enough in this particular case. Until a better detection is available, you could make the index non-sparse. It will be used then for this particular query.

**Comment by maxkernbach** [comment]
Hi @x3cion,

Release Candidate 3 of ArangoDB 3.5, which includes an improvement for the AQL query optimizer, has been released.

> * fix issue #9106: Sparse Skiplist Index on multiple fields not used for FILTER + SORT query
> 
>   Allow AQL query optimizer to use sparse indexes in more cases, specifically when
>   indexes could not be used for filtering and there finally was an `EnumerateCollectionNode`
>   in the query execution plan followed by a `SortNode`. In this case, sparse indexes were
>   not considered for enumeration in sorted order, because it was unclear to the optimizer
>   if the result set would contain null values or not.

Could you please give it a try? Release Candidates are for testing purposes only, not for production usage! The latest Release Candidate can be found in the [download section](https://www.arangodb.com/download-technical-preview/).

**Comment by OmarAyo** [comment]
Hi @x3cion 

Did you have the chance to download and try ArangoDB 3.5-RC3 ? Please provide update

**Comment by x3cion** [comment]
@OmarAyo Sorry for the delay. I was able to test this positively with the docker container 3.5.0-rc.3 and the described setup.
