### ISSUE TITLE
Startup aborted 'RocksDBEngine': Could not extract custom attribute

### ISSUE THREAD

**Issue by ayox** [arangodb/arangodb#9118]
## My Environment

* __ArangoDB Version__:    3.4.5    
* __Storage Engine__:     RocksDB        
* __Deployment Mode__:  Single Server     
* __Deployment Strategy__:  ArangoDB Starter  
* __Configuration__:       Normal        
* __Infrastructure__:      AWS EC2      
* __Operating System__:    Debian GNU/Linux 9.9 (stretch)     
* __Total RAM in your machine__:   4GB     
* __Disks in use__:    100SSD    
* __Used Package__:    Debian or Ubuntu .deb           

## Component, Query & Data

__Affected feature__:

All DB 

__AQL query (if applicable)__:
Not applicable

__AQL explain (if applicable)__:

Not applicable

__Dataset__:

Not available 

__Size of your Dataset on disk__:

6GB 
__Replication Factor & Number of Shards (Cluster only)__:

Not applicable

## Steps to reproduce
I can't reproduce. It happens randomly. I couldn't yet figure out what cause it. 

__Problem__:
Database sometimes hangs and every feature stop . However, I can see that the service is running and I can't stop it. Then I would kill the process and I get this error :

`ERROR {startup} startup aborted: caught exception during start of feature 'RocksDBEngine': Could not extract custom attribute. (exception location: /work/ArangoDB/lib/Basics/VelocyPackHelper.cpp:808). Please report this error to arangodb.com. shutting down
` 

__Expected result__:
To start normally after shutdown . 

Thank you

**Comment by jsteemann** [comment]
This error should never surface.

It is thrown from inside a compare function that can be called by RocksDB for figuring out the order of keys. As the log message shows it is happening at startup, it seems that the comparator is called very early in the startup process with values that require more context than is available then.

I guess it has to do with data in user-defined indexes, but this is just a guess. Is there any special data that you are storing in indexes (e.g. system attributes, entire documents etc.)? Any info here may help us reproduce the problem locally.

Finally, is it possible to gather more log output for the startup, e.g. by starting the server with the extra configuration parameters `--log.line-number true --log.level trace --log.level startup=trace --log.level rocksdb=trace --rocksdb.debug-logging true`?
This should produce some log output, which may or may not help narrowing down the exact cause of the problem.
Thanks!

**Comment by dothebart** [comment]
If these hangs occur, can you please also check whether you are still able on the shell to execute 
`cat /bin/true > /dev/null` 
and whether it still runs in sub second time? 

AWS has the concept of "Burst-Credits" - if you run out of them, I/O to the volume gets slow and the whole system comes to a grinding halt - including ArangoDB.

**Comment by ayox** [comment]
@jsteemann 

I will restart the server with the configuration parameters you provided once we have the same issue I comment on this thread with the log output. I it think started to happen after we added user-defined functions to AQL everything else is the same like before. I was not sure if this bug is related to a new arangodb update or because of the user-defined function. 

We added this function : 
`function roundDecimals(value) { return Math.round(value*100)/100} `

@dothebart 
I will do that if it happened again. 

Thank you

**Comment by jsteemann** [comment]
@ayox: thanks!
I don't see a direct relation to the user-defined function though. I would suspect it has anything to do with the index setup somehow, but that's also still speculation from my side. Are there any indexes on system attributes, such as `_id`, `_key` etc.? Or are you storing entire documents as part of other documents (e.g. in sub-arrays or sub-objects)?

**Comment by ayox** [comment]
@jsteemann 
yes. I am doing this : 
> storing entire documents as part of other documents (e.g. in sub-arrays or sub-objects)?

I use the `document()` in AQL to store part of other documents.  No indexes on system attributes.

**Comment by jsteemann** [comment]
@ayox: Thanks, that is something we should try in order to reproduce the issue.

**Comment by jsteemann** [comment]
I think I have an understand of what's going on now.
Is it possible that there is an index present on the attribute in which you store the other documents you are retrieving via the `document()` AQL function?
For example, if you fetch a document using the `document()` AQL function and store it inside an attribute "other", do you have an index on either "other" or a sub-attribute of "other"?

**Comment by jsteemann** [comment]
Got it reproduced by creating an index on the `_id` sub-attribute of an attribute that stores other documents:
```
2019-05-29T16:05:31Z [30922] INFO [a1c60] {syscall} file-descriptors (nofiles) hard limit is 524288, soft limit is 524288
2019-05-29T16:05:31Z [30922] INFO [3844e] {authentication} Authentication is turned on (system only), authentication for unix sockets is turned on
2019-05-29T16:05:31Z [30922] ERROR [4ec19] {startup} startup aborted: caught exception during start of feature 'RocksDBEngine': Could not extract custom attribute. (exception location: /home/jsteemann/ArangoNoAsan/lib/Basics/VelocyPackHelper.cpp:771). Please report this error to arangodb.com. shutting down
2019-05-29T16:05:32Z [30922] INFO [4bcb9] ArangoDB has been shut down
2019-05-29T16:05:32Z [30922] ERROR [5d508] arangod terminated because of an exception: startup aborted: caught exception during start of feature 'RocksDBEngine': Could not extract custom attribute. (exception location: /home/jsteemann/ArangoNoAsan/lib/Basics/VelocyPackHelper.cpp:771). Please report this error to arangodb.com (exception location: /home/jsteemann/ArangoNoAsan/lib/ApplicationFeatures/ApplicationServer.cpp:680). Please report this error to arangodb.com
```

**Comment by ayox** [comment]
@jsteemann That's great news. Do I need now to wait for update or should I do something from my side.

**Comment by maxkernbach** [comment]
Hi @ayox,

Release Candidate 7 of ArangoDB 3.5, which includes a fix for this issue, has just been released.
Please find the latest RC in the [download section](https://www.arangodb.com/download-technical-preview/).

From the [changelog](https://github.com/arangodb/arangodb/blob/3a98726a952bbac86b93ab6aa19a3021dfa196a6/CHANGELOG#L44):

> * disallow indexing the `_id` attribute even as a sub-attribute. 
>   Previous versions of ArangoDB did not allow creating indexes on the `_id` attribute, but didn't
>   check if an index was created on the `_id` attribute of a sub-attribute, e.g. `referredTo._id`
>   or `data[*]._id`.
>   Such indexes could be created with previous versions of ArangoDB, but they were non-functional.
>   From now on, such indexes cannot be created anymore, and any attempts to create them will fail.
> 

In case the reported  error reoccurs, please comment and we will reopen.
