### ISSUE TITLE
illegal document key with Chinese words

### ISSUE THREAD

**Issue by kaiser-32** [arangodb/arangodb#9129]
## My Environment

* __ArangoDB Version__: 3.4.5       
* __Storage Engine__:       
* __Deployment Mode__:       
* __Deployment Strategy__:   
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:windows 10        
* __Total RAM in your machine__:        
* __Disks in use__:        
* __Used Package__:              

__Problem__: dear friends：
When i was trying to import csv file to collection, i met the error: creating document failed with error 'illegal document key', and there were Chinese words in the _key, just like '浙Axxxx'.
My command is 
>arangoimp --file xxxx.csv --collection cph --create-collection true --type csv
Are there any error with my command or the arangodb's key can not have Chinese words?
looking forward to your reply! thank u very much!
__Expected result__:

**Comment by jsteemann** [comment]
@kaiser-32: Only certain characters are allowed in ArangoDB document keys. Please refer to [the manual](https://www.arangodb.com/docs/stable/data-modeling-naming-conventions-document-keys.html) for details.
