### ISSUE TITLE
Wrong timezone in log

### ISSUE THREAD

**Issue by daoxian** [arangodb/arangodb#9130]
## My Environment

* __ArangoDB Version__:        3.4.5
* __Storage Engine__:             RocksDB 
* __Deployment Mode__:       Cluster 
* __Deployment Strategy__:   ArangoDB Starter
* __Configuration__:               default
* __Infrastructure__:               bare machine
* __Operating System__:        CentOS 7.2
* __Total RAM in your machine__:        96G
* __Disks in use__:        
* __Used Package__:              

__Problem__:
The timezone of log files differs from the system setting.
For example:
bash# date
Wed May 29 12:30:05 CST 2019

whereas in log file coordinator8529/arangod.log:
2019-05-29T04:05:09Z [9672] WARNING {queries} slow streaming query: 'for i in 1..10000 insert {'link': 'http://www.baidu.com/fake', 'domain_name':'baidu.com', 'version': i} into test_stream', took: 46.950685 s
They are 8 hours' difference.

**Comment by jsteemann** [comment]
@daoxian : the `Z` in the log message's date/time value `2019-05-29T04:05:09Z` indicates Zulu/UTC time. This is GMT +00:00, so it may well be 8 hours difference to your local time.
If you want the log messages to use your local time, please use the option `--log.use-local-time true`.

**Comment by daoxian** [comment]
OK... got it, thank you!
