### ISSUE TITLE
Insertion very very slow when numberOfShards is big

### ISSUE THREAD

**Issue by daoxian** [arangodb/arangodb#9132]
version 3.4.5, rocksdb, CentOS-7.2,
I've setup a 5-nodes cluster, established a table with 625 shards, 3 replicas & async mode.
When inserting a normal record,  it will take 30 ~ 60 secs.
Can't arangodb support large shards?

**Comment by OmarAyo** [comment]
Linked to https://github.com/arangodb/arangodb/issues/9131

**Comment by ObiWahn** [comment]
You are not meant to use that many shards. Usually you will use 1 Shard per db server and ensure replication by setting the replication factor.

Now usually your request goes to one of the coordinators. The coordinator finds out in which shard some data is located if he does not know the request is send to all shards. So for the latter case you have increased the necessary http traffic just by factor 300. Furthermore the coordinator builds up a result from all the answers it gets from the shards. This will not work well either if the answer needs to be sorted.

I mean you try to work with 4000 shards. That can not perform well. If you insist you need to distribute the work over a similar number of coordinators.

**Comment by daoxian** [comment]
ok, thanks for your explaination.
