### ISSUE TITLE
Returning BM25 score as part of an object fails

### ISSUE THREAD

**Issue by davechallis** [arangodb/arangodb#9142]
## My Environment

* __ArangoDB Version__:        3.4.6 (Docker)
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   ArangoDB Starter in Docker
* __Configuration__:               defaults
* __Infrastructure__:               own
* __Operating System__:        MacOS 10.14.5
* __Total RAM in your machine__:        32Gb
* __Disks in use__:        SSD
* __Used Package__:              Docker - official Docker library

## Component, Query & Data

__Affected feature__: AQL query using web interface

__AQL query (if applicable)__:

FOR d IN v_foo
SEARCH PHRASE(d.name, 'Foo', 'text_en')
SORT BM25(d) DESC
LIMIT 10
RETURN {name: d.name, score: BM25(d)}

__AQL explain (if applicable)__:
Query String:
 FOR d IN v_organisation
 SEARCH PHRASE(d.name, 'Foo', 'text_en')
 SORT BM25(d) DESC
 LIMIT 10
 RETURN {name: d.name, score: BM25(d)}

Execution plan:
 Id   NodeType            Est.   Comment
  1   SingletonNode          1   * ROOT
  2   EnumerateViewNode      1     - FOR d IN v_organisation SEARCH PHRASE(d.`name`, "Foo", "text_en")   /* view query */
  4   SortNode               1       - SORT #1 DESC
  5   LimitNode              1       - LIMIT 0, 10
  6   CalculationNode        1       - LET #3 = { "name" : d.`name`, "score" : BM25(d) }   /* simple expression */
  7   ReturnNode             1       - RETURN #3

Indexes used:
 none

Functions used:
 Name   Deterministic   Cacheable   Uses V8
 BM25   true            true        false  

Optimization rules applied:
 Id   RuleName
  1   handle-arangosearch-views

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. Executing the above query on any search view/dataset

__Problem__:

Getting the search scoring using BM25 works fine when returning it on its own with e.g.:

    return BM25(d)

but gives an error when returned along with other values, e.g.:

    return { name: d.name, score: BM25(d) }

This give the error:

    Query: AQL: ArangoSearch scorer functions BM25() and TFIDF() are designed to be used only outside SEARCH statement within a context of ArangoSearch view. Please ensure function signature is correct. (while executing)

__Expected result__:

Both the document's name field and the BM25 score are returned.

**Comment by gnusi** [comment]
Hi @davechallis, using scorers outside SORT statement is not allowed before 3.5.

**Comment by davechallis** [comment]
@gnusi Many thanks, seems like 3.5 isn't far off anyway.
