### ISSUE TITLE
How to rename a database?

### ISSUE THREAD

**Issue by daoxian** [arangodb/arangodb#9143]
There are lots of collections in the database, and I don't want to dump data and import into another database. I only  want to rename the database, how to do it?

**Comment by OmarAyo** [comment]
Hi @daoxian 

Currently the only way to rename an existing database is by the dump&restore process 

I will label this ticket as a Feature

**Comment by daoxian** [comment]
Thanks.

**Comment by maxkernbach** [comment]
The same feature is requested in https://github.com/arangodb/arangodb/issues/1243.

Closing this issue as a duplicate.
