### ISSUE TITLE
LOGS Page in Dashboard is inaccessible

### ISSUE THREAD

**Issue by monotykamary** [arangodb/arangodb#9163]
## My Environment

* __ArangoDB Version__:        3.4.6
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server, Single Server
* __Deployment Strategy__:   Manual Start, Kubernetes
* __Configuration__:               N/A
* __Infrastructure__:               localhost and DigitalOcean
* __Operating System__:        Ubuntu 18.04
* __Total RAM in your machine__:        24GB, 8GB
* __Disks in use__:       HDD, SSD
* __Used Package__:              Ubuntu deb

## Component, Query & Data

__Affected feature__:
Accessing LOGS page in ArangoDB Dashboard

## Steps to reproduce

1. Upgrade to version 3.4.6
2. Open ArangoDB dashboard
3. Click on LOGS tab in the navigation bar
4. profit... wait no

__Problem__:
LOGS page will not display at all (on both local and server machines).

![image](https://user-images.githubusercontent.com/1130103/58729013-6fb63280-8412-11e9-843f-bff108f12b33.png)

__Expected result__:
LOGS page should show logs from arangod.log

**Comment by OmarAyo** [comment]
Hi @monotykamary 

Thanks for reporting this issue, we are already aware of it. - and this should be fixed by https://github.com/arangodb/arangodb/pull/9093 (already merged). 

The fix will be released with the next 3.4 patch release

**Comment by maxkernbach** [comment]
Hi @monotykamary,

I am closing this issue since version 3.4.7, which includes a fix for this issue has been released.
In case this error still occurs, please comment and we will reopen.

The latest version can be found in the [download section](https://www.arangodb.com/download-major/).
