### ISSUE TITLE
Bulk import into RocksDB is very slow

### ISSUE THREAD

**Issue by piewared** [arangodb/arangodb#9165]
## My Environment

* __ArangoDB Version__:        3.4.6
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start 
* __Operating System__:       Ubuntu 16.04.2
* __Total RAM in your machine__:        16 GB
* __Disks in use__:        SSD
* __Used Package__:  Debian or Ubuntu .deb 

## Component, Query & Data

__Affected feature__:
Bulk Import with RocksDB

__Problem__: Importing JSON or JSONL file with >20k documents using either the HTTP import API route or the arangoimport tool is extremely slow when using RocksDB.

It takes about 5 minutes to import data into arango using RocksDB that would take a few seconds if imported into MMFiles.

I've tried different values for the following RocksDB configuration options and settled on these by following the RocksDB tuning guide, but I'm not seeing any significant results.

write-buffer-size=64MB
max-write-buffer-number=4
level0-compaction-trigger=4
max-background-jobs=8
num-threads-priority-high=8
dynamic-level-bytes=false
max-bytes-for-level-base=256MB
num-uncompressed-levels=4
table-block-size=4096
delayed_write_rate=8096
optimize-filters-for-hits=true

EDIT:

A little more information:

I'm currently testing with a JSONL file containing around 16,000 documents and it's about 1.7MB. I'm inserting into an edge collection.

I've tried 4 cases:

- --on-duplicate ignore, empty collection
- --on-duplicate ignore, collection with 16000 existing documents
- --on-duplicate update, empty collection
- --on-duplicate update, collection with 16000 existing documents

Both cases with --on-duplicate ignore completed in about .5 seconds. However, both cases with --on-duplicate update produced equally inconsistent results. Times ranged from 3 seconds to 50 seconds.

I saw these messages popping up in arangod.log whenever it was really slow:

2019-06-03T13:53:26Z [55258] WARNING {engines} slow background settings sync: 10.989804 s
2019-06-03T13:56:11Z [55258] WARNING {engines} slow background settings sync: 73.991178 s
2019-06-03T13:56:14Z [55258] WARNING {engines} slow background settings sync: 1.044903 s
2019-06-03T13:56:48Z [55258] WARNING {engines} slow background settings sync: 20.731436 s
2019-06-03T13:57:01Z [55258] WARNING {engines} slow background settings sync: 10.809777 s
2019-06-03T13:57:45Z [55258] WARNING {engines} slow background settings sync: 41.642542 s
2019-06-03T13:58:40Z [55258] WARNING {engines} slow background settings sync: 52.776457 s
2019-06-03T13:59:47Z [55258] WARNING {engines} slow background settings sync: 36.656320 s
2019-06-03T14:00:06Z [55258] WARNING {engines} slow background settings sync: 16.100278 s
2019-06-03T14:00:38Z [55258] WARNING {engines} slow background settings sync: 0.772148 s
2019-06-03T14:01:00Z [55258] WARNING {engines} slow background settings sync: 1.293372 s
2019-06-03T14:01:19Z [55258] WARNING {engines} slow background settings sync: 0.907776 s

**Comment by danielapoliveira** [comment]
I'm running into the same problem while using the docker image version 3.6.5.
I'm trying to load data in the order of millions of (small) documents that are coming from elasticsearch. I use the python-arango driver with the async database drivers.

I also tried to change the options of RocksDB with little effect.

**Comment by dothebart** [comment]
Hi, you probably don't use bulk requests?
Afaik thats not (yet) supported by python-arango. 

This is, how I added it to pyArango:
https://github.com/ArangoDB-Community/pyArango/pull/139

maybe the aproach could be similar to add it to python-arango?

**Comment by danielapoliveira** [comment]
Hi, 
Thanks for your answer.
python-arango does implement bulk import via the HTTP API but since my comment, I also tried with arangoimport and I still get the messages and slow down. I will try with pyArango anyway to check.

**Comment by dothebart** [comment]
This issue was for ArangoDB 3.4 - which is EOLed. 
https://www.arangodb.com/docs/stable/tutorials-reduce-memory-footprint.html shows how the rocksdb disk I/O caching works. 

[ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) is available.
