### ISSUE TITLE
arangodb 3.4 apt key expired (2019-06-01)

### ISSUE THREAD

**Issue by jett** [arangodb/arangodb#9168]
Updating ArangoDB on Ubuntu 18.04 fails. `sudo apt update` shows the following

`Err:12 https://download.arangodb.com/arangodb34/DEBIAN  Release.gpg                                
  The following signatures were invalid: EXPKEYSIG EA93F5E56E751E9B Frank Celler (ArangoDB Debian Repository) <info@arangodb.com>`
...
`W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://download.arangodb.com/arangodb34/DEBIAN  Release: The following signatures were invalid: EXPKEYSIG EA93F5E56E751E9B Frank Celler (ArangoDB Debian Repository) <info@arangodb.com>
W: Failed to fetch https://download.arangodb.com/arangodb34/DEBIAN/Release.gpg  The following signatures were invalid: EXPKEYSIG EA93F5E56E751E9B Frank Celler (ArangoDB Debian Repository) <info@arangodb.com>`

`apt-key list` shows

`pub   rsa4096 2015-06-02 [SC] [expired: 2019-06-01]
      CD8C B0F1 E0AD 5B52 E93F  41E7 EA93 F5E5 6E75 1E9B
uid           [ expired] Frank Celler (ArangoDB Debian Repository) <info@arangodb.com>`

**Comment by maxkernbach** [comment]
Hi @jett,

the expired key has been updated. In order to delete the old key and add the new one, please execute the following.

Regular installation - The key has been added to `apt-key` (check with `sudo apt-key list`):

```
sudo apt-key del EA93F5E56E751E9B
sudo apt-key adv --keyserver pool.sks-keyservers.net --recv-keys EA93F5E56E751E9B
```

If the key has been added to `gpg` itself (check with `gpg --list-keys`):

```
gpg --delete-keys EA93F5E56E751E9B
gpg --keyserver pool.sks-keyservers.net --recv-keys EA93F5E56E751E9B
```

Adding the key might fail if the key server is temporary not available. In this case please try to rerun the command until an available key server is chosen.

**Comment by jett** [comment]
@maxkernbach confirmed that this is working now

`pub   rsa4096 2015-06-02 [SC] [expires: 2022-01-01]
      CD8C B0F1 E0AD 5B52 E93F  41E7 EA93 F5E5 6E75 1E9B
uid           [ unknown] Frank Celler (ArangoDB Debian Repository) <info@arangodb.com>
sub   rsa4096 2015-06-02 [E] [expires: 2021-06-01]`

thanks

**Comment by einsteinsfool** [comment]
Just wanted to give a different solution since apt-key is deprecated. I used this command (after deleting the previous key):
`wget -O- https://download.arangodb.com/arangodb39/DEBIAN/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/arangodb-archive-keyring.gpg`
