### ISSUE TITLE
Swagger API Missing Return Type

### ISSUE THREAD

**Issue by darkfrog26** [arangodb/arangodb#9171]
This can be seen in v3.4.6.

The `swagger.json` file includes a great representation of the API, but does not include proper type data for what gets returned to calls.  I'm currently writing a Swagger client generator, and it's almost completely finished, but just realized that Arango's Swagger doesn't include the return types which makes it impossible for me to structurally generate a client with any type-safety.

Please let me know if there's a stop-gap solution that doesn't involve me manually dealing with every end-point.

Thanks

**Comment by darkfrog26** [comment]
There are also several places where definitions lack proper details. For example, in "post_api_collection", `shardKeys` should be an array of strings, but the type is just `string`.

**Comment by dothebart** [comment]
we worked a lot on swagger correctnes in the meantime, hence closing this as out of date.
