### ISSUE TITLE
How to acquire good writting performance when using HDD?

### ISSUE THREAD

**Issue by daoxian** [arangodb/arangodb#9182]
Hi everyone，I'm suffering a bad writing performance because my disk is the traditional HDD,  could someone tell me how to tune the performance? I think it  probably could be some startup arguments that works.  I'm using version 3.4.5 with RocksDB.  Any help will be appreciated.

**Comment by dothebart** [comment]
Hi, 
https://www.arangodb.com/2019/03/small-steps-reduce-arangodb-resource-footprint/ explains how caches operate and how to configure them (with the opposite goal - so invert whatever you read) 

Other options include reducing persistency expectations - thus what will be gone on power failure in mid air: 

    --rocksdb.delayed-write-rate
    --rocksdb.sync-interval

**Comment by daoxian** [comment]
Thank you for your suggestion. I've tried modifying the related buffer size and num, and increase the interval of sync. The cluster looks  a little stronger, but still has some abnormal appearance.
I kept parallelly inserting into a collection with billions of documents. Then the cluster  became very slow, with a almost dying Web UI, and all sorts of 503/504/Timeout exception bloomed to the parallel clients.  So I stopped the pressure, after hours, the Web UI recovered from the disaster slowly,  but responded much slower than after restarting the arangodb service.  Under the pressure, the CPU idle is 20%~40% or so, and after pressure, the CPU idle recovered to near 100%. Yet the arango service didn't recover, when inserting a document into the collection, it's obviously slower than the original case.  So what could be the reason?

**Comment by daoxian** [comment]
And I noticed that the peak throughput (Bytes in & Bytes out displayed on the Web UI) is only less than 10MB/s, and peak QPS is over 15,000.   Averagely only 3000 qps per machine, will this pressure crash the service?

**Comment by dothebart** [comment]
Please note that you would benchmark the maximum throughput you can achieve using a ramping profile while closely monitoring your SUT - so you can max out the performance without overrunning it. Once you overloaded it, throughput may actually be worse than the maximum throughput: 

https://www.arangodb.com/2017/10/performance-analysis-pyarango-usage-scenarios/

In the end, data has to be written to disk. So if you bottleneck that by using spinning disk, this will limit your scenario.

**Comment by daoxian** [comment]
Can I scale out the throughput by increasing physical nodes, and creating collections with more shards?
