### ISSUE TITLE
How to find all the background pregel jobs?

### ISSUE THREAD

**Issue by daoxian** [arangodb/arangodb#9194]
The question is the same as : When a pregel job is running, how to retrieve its job_id?

**Comment by maxkernbach** [comment]
Hi @daoxian,

When a Pregel job is started, the `start` function returns the job's id.
Using that id one can query the status of the job or retrieve its results.

https://www.arangodb.com/docs/stable/graphs-pregel.html#status-of-an-algorithm-execution

There is currently no API for retrieving a list of Pregel jobs (either running or ready).

**Comment by daoxian** [comment]
ok thanks
