### ISSUE TITLE
[Coordinator]  FATAL out of memory in V8 (heap setup)

### ISSUE THREAD

**Issue by daoxian** [arangodb/arangodb#9222]
The 5-node cluster 3.4.5 with RocksDB, after inserting millions of documents, 2 nodes crashed with coordinator error log:
590 2019-06-07T00:29:50Z [23849] ERROR could not start thread: Resource temporarily unavailable
591 2019-06-07T00:29:52Z [23849] ERROR {threads} could not start thread 'Scheduler': Resource temporarily unavailable
592 2019-06-07T00:29:56Z [23849] FATAL out of memory in V8 (heap setup)
593 2019-06-07T00:29:56Z [23849] ERROR {cluster} cannot create connection to server: 'PRMR-8d13bda4-606f-4110-81be-112acc94a105' at endpoint tcp://10.194.208.7:8530', timeout: 2.000000

The "arangodb" process is also missing without any useful log in arangodb.log.  Now only dbsrever and agent are alive.

The startup cmd is:
/usr/bin/arangodb --server.storage-engine=rocksdb --starter.data-dir=$ARANGO_DATA_DIR --dbservers.rocksdb.block-cache-size=20000000000 --dbservers.rocksdb.enforce-block-cache-size-limit=true --dbservers.rocksdb.max-total-wal-size 838860800 --dbservers.rocksdb.max-write-buffer-number 200 --dbservers.rocksdb.min-write-buffer-number-to-merge 100 --dbservers.rocksdb.num-threads-priority-high  10 --dbservers.rocksdb.num-threads-priority-low 5 --dbservers.rocksdb.sync-interval 60000 --dbservers.rocksdb.table-block-size  163840 --dbservers.rocksdb.throttle $3 --dbservers.rocksdb.total-write-buffer-size 60000000000 --dbservers.rocksdb.write-buffer-size  6710886400  --dbservers.server.maximal-queue-size 0  --starter.join 10.194.208.7,10.194.184.61,10.194.48.30,10.194.192.38,10.194.244.73 &

The hardware and OS settings:  
24 core 96G Mem 10T HDD with raid10
KiB Mem : 98794984 total, 41593176 free, 37427640 used, 19774168 buff/cache
KiB Swap:  2097148 total,   739220 free,  1357928 used. 58462736 avail Mem

vm.max_map_count = 153600000
vm.overcommit_memory = 0
vm.zone_reclaim_mode = 0
vm.swappiness = 0
net.core.somaxconn = 4096

Any suggestion will be appreciated.

**Comment by graetzer** [comment]
seems like a simple OOM error. Did you run queries at the same time ?

**Comment by daoxian** [comment]
Yes I freshed the WebUI in browser to check the count of collection from time to time.  
Why the arangodb also killed?

**Comment by dothebart** [comment]
Are you using https://www.arangodb.com/docs/stable/graphs-traversals-using-traversal-objects.html ? This is known to have scaling issues. Please use AQL graph traversals instead.

**Comment by daoxian** [comment]
> Are you using https://www.arangodb.com/docs/stable/graphs-traversals-using-traversal-objects.html ? This is known to have scaling issues. Please use AQL graph traversals instead.

No, only normal UPSERT AND FOR ... RETURN used.

**Comment by dothebart** [comment]
Please note ArangoDB 3.4 has reached EOL.
Errors like `could not start thread` indicate that your machine is reaching its resource limits. 

Please add monitoring to your machine.

As discussed in https://github.com/arangodb/arangodb/issues/11577 [exposing more options of rocksdb to the commandline](https://www.arangodb.com/docs/stable/programs-arangod-options.html#rocksdb) seems to ease the memory situation.

Namely:
 -   `--rocksdb.cache-index-and-filter-blocks-with-high-priority`
 -   `--rocksdb.pin-l0-filter-and-index-blocks-in-cache`
 -   `--rocksdb.pin-top-level-index-and-filter`

These have been added to [the now released ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) - hence closing this.
