### ISSUE TITLE
{agencycomm} Flaky agency communication 

### ISSUE THREAD

**Issue by daoxian** [arangodb/arangodb#9242]
Agents run ok. when I startup the arangod dbserver manually, It says:
```
INFO {agencycomm} Flaky agency communication to http+tcp://10.194.184.61:8531. Unsuccessful consecutive tries: 54 (118.06s). Network checks advised. Server in startup.
```
Finally, dbserver exited unexpectly.
So what's the problem?

**Comment by Simran-B** [comment]
Is SSL enabled? In that case the configured endpoint for the DBServer is wrong (unsecured HTTP connection).

Please fill out the issue template with details about your setup, configuration and startup commands if you want further assistance.

**Comment by daoxian** [comment]
I have resolved this problem by specifying the endpoint option to 0.0.0.0 instead of the real ip.
