### ISSUE TITLE
IP address missing in EndPoint on WebUI

### ISSUE THREAD

**Issue by daoxian** [arangodb/arangodb#9245]
3.4.5, rocksDB,  cluster mode , startup manually.
After some processes failed, I started them manually. Then the display is unexpected:

![image](https://user-images.githubusercontent.com/34263430/59249897-75084e00-8c58-11e9-847b-6e02e799d919.png)

**Comment by daoxian** [comment]
The restart cmd specified the option:  --cluster.my-address tcp://:8529, which contaied no IP address.  Is this valid?

**Comment by OmarAyo** [comment]
Hi @daoxian,

can you please provide us all the commands you used for starting your cluster?

Best,

**Comment by daoxian** [comment]
> Hi @daoxian,
> 
> can you please provide us all the commands you used for starting your cluster?
> 
> Best,

for((i=7530;i<7550;i++));do 
export DATADIR=/mnt/raid10/arangodb/data_3.4.5_20shards/coordinator$i;  
sudo mkdir -p $DATADIR; 
sudo chown -R arangodb:arangodb $DATADIR; 
sudo nohup arangod --server.authentication=false --server.endpoint tcp://0.0.0.0:$i --cluster.my-address tcp://$IP:$i --cluster.my-role COORDINATOR  --database.directory $DATADIR --log.file $DATADIR/coordinator.log    --cluster.agency-endpoint tcp://10.194.208.7:8531   --cluster.agency-endpoint tcp://10.194.48.30:8531 --cluster.agency-endpoint tcp://10.194.184.61:8531   & 
done

Because I forgot to specify the IP value, so the cluster.my-address was "tcp://:8529".

**Comment by ObiWahn** [comment]
> Because I forgot to specify the IP value, so the cluster.my-address was "tcp://:8529".

good
