### ISSUE TITLE
Inserting document is  very very slow

### ISSUE THREAD

**Issue by daoxian** [arangodb/arangodb#9250]
Cluster mode, started mannually, when paralled inserting documents, I got the following logs from coordinators:
2019-06-12T06:08:26Z [42216] ERROR {cluster} cannot create connection to server: 'PRMR-6436599c-af4c-4ede-9019-2333f7a072b0' at endpoint tcp://11.140.125.41:9540', timeout: 2.000000

2019-06-12T06:08:29Z [42216] ERROR {cluster} ClusterComm::performRequests: got BACKEND_UNAVAILABLE or TIMEOUT from shard:s248010068:/_db/mit_spider_sitemaps/_api/collection/s248010068/count
......

But when I  curl 11.140.125.41:9540, it returned result immediately.
Any suggestions?

**Comment by OmarAyo** [comment]
Hi @daoxian 

- what's your cluster setup (number of coordiantors, dbserver and agents)
- are you still using ArangoDB version 3.4.5 ?
- how you are inserting your documents ? 
- are those parallel insertion pointing to the same coordinator ?
- can you provide the exact curl command that you are issuing 
- can you provide logs (coordinators and dbservers)

Thanks

**Comment by daoxian** [comment]
1. I'm using 8 physical machines (28 core 96G mem) for coordinators, and 7 physical machines for dbservers.  I run 20 coordinator processes each machine, and 20 dbserver processes each machine. So I totally have 160 coordinators & 140 dbservers.   And 3 agents on 3 machines.
2. Yes, I'm still using 3.4.5 with RocksDB
3.  All the aql statements are UPSERT.  For example:
1) UPSERT {"taskid": "6018638", "url": "https://www.civitatis.com/fr/budapest/visite-guidee-budapest-parlement/opinions/?ra     ting=2%20AND%203%20AND%204&type=famTeena%20AND%20famBaby"} INSERT {"taskid": "6018638", "url": "https://www.civitatis.com/fr/budapest/visite-guidee-budapest-parlement/opinions/?rating=2%20AND%203%20AND%204&type=famTeena%20AND%20famBaby"} UPDATE {} INTO failed_url_queue  OPTIONS { ignoreErrors: true }
The table "failed_url_queue" is constructed by:
db._create('failed_url_queue', {numberOfShards:8,shardKeys:["taskid"],replicationFactor:1});
db.failed_url_queue.ensureIndex({ type: "persistent", fields: [ "taskid", "url" ], unique: true });
db.failed_url_queue.ensureIndex({ type: "persistent", fields: [ "taskid"] });
2) python:
    from_rec = {'_key': from_vertex_key, 'domain_name': domain, 'path': path,  'url': item['src_url'], 'version': taskid}
    from_rec_update = {'domain_name': domain, 'path': path, 'url': item['src_url'], 'version': taskid}
    aql = "UPSERT @key INSERT @rec UPDATE @rec_update INTO %s OPTIONS { ignoreErrors: true} LET inserted=NEW RETURN inserted._id " %site_tablename
    bind = {'key': from_key_rec, 'rec': from_rec, 'rec_update': from_rec_update}
    from_rec_inserted = g_arango_db.aql.execute(aql, bind_vars=bind)
..............
    bind = {'recs': to_recs}
    aql = "FOR r IN @recs UPSERT {'_key': r._key} INSERT r UPDATE {'domain_name': r.domain_name, 'version': r.version} INTO %s OPTIONS { ignoreErrors: true } LET inserted=NEW RETURN inserted._id " %site_tablename
    to_recs_inserted = g_arango_db.aql.execute(aql, bind_vars=bind)

tables are created dynamically:
    arango_db.create_collection(tablename,  shard_count=8, replication_factor=2, sync_replication=False)

4.  No, they're load balanced through different IP:PORT
5.  No direct curl used, I'm using it by python-arango
6.  Logs of Coordinators:
20832 2019-06-12T12:16:35Z [126307] ERROR {cluster} ClusterComm::performRequests: got BACKEND_UNAVAILABLE or TIMEOUT from shard:s248010074:/_db/mit_spider_sitemaps/_api/collection/s24801      0074/count
20833 2019-06-12T12:16:35Z [126307] ERROR {cluster} ClusterComm::performRequests: got BACKEND_UNAVAILABLE or TIMEOUT from shard:s248010074:/_db/mit_spider_sitemaps/_api/collection/s24801      0074/count
20834 2019-06-12T12:16:35Z [126307] ERROR {cluster} ClusterComm::performRequests: got BACKEND_UNAVAILABLE or TIMEOUT from shard:s248010074:/_db/mit_spider_sitemaps/_api/collection/s24801      0074/count
20835 2019-06-12T12:16:35Z [126307] ERROR {cluster} ClusterComm::performRequests: got BACKEND_UNAVAILABLE or TIMEOUT from shard:s248010074:/_db/mit_spider_sitemaps/_api/collection/s24801      0074/count
20836 2019-06-12T12:16:35Z [126307] ERROR {cluster} ClusterComm::performRequests: got BACKEND_UNAVAILABLE or TIMEOUT from shard:s248010074:/_db/mit_spider_sitemaps/_api/collection/s24801      0074/count
20837 2019-06-12T12:16:35Z [126307] ERROR {cluster} ClusterComm::performRequests: got BACKEND_UNAVAILABLE or TIMEOUT from shard:s248010069:/_db/mit_spider_sitemaps/_api/collection/s24801      0069/count
20838 2019-06-12T12:16:35Z [126307] ERROR {cluster} ClusterComm::performRequests: got BACKEND_UNAVAILABLE or TIMEOUT from shard:s248010073:/_db/mit_spider_sitemaps/_api/index?collection=      s248010073
20839 2019-06-12T12:16:35Z [126307] WARNING {queries} slow query: 'UPSERT {"taskid": "6027794", "url": "http://dev.cs-market.com/azure/index.php?dispatch=product_features.add_product&pro      duct_id=41&redirect_url=index.php%3Fitems_per_page%3D96%26sort_by%3Dproduct%26sort_order%3Ddesc%26currency%3DGBP%26dispatch%3Dcategories.view%26category_id%3D225"} INSERT {"taskid"      : "6027794", "url": "http://dev.cs-market.com/azure/index.php?dispatch=product_features.add_product&product_id=41&redirect_url=index.php%3Fitems_per_page%3D96%26sort_by%3Dproduct%2      6sort_order%3Ddesc%26currency%3DGBP%26dispatch%3Dcategories.view%26category_id%3D225"} UPDATE {} INTO failed_url_queue  OPTIONS { ignoreErrors: true }', took: 110.858604 s
20840 2019-06-12T12:16:35Z [126307] WARNING {queries} slow query: 'UPSERT {"taskid": "6039888", "url": "https://freecommander.com/forum/viewtopic.php?f=16&t=8946&p=28295&sid=2dc52f9235ad      4d52eb5f92e718f3eb44#p28295"} INSERT {"taskid": "6039888", "url": "https://freecommander.com/forum/viewtopic.php?f=16&t=8946&p=28295&sid=2dc52f9235ad4d52eb5f92e718f3eb44#p28295"} U      PDATE {} INTO failed_url_queue  OPTIONS { ignoreErrors: true }', took: 110.271111 s
20841 2019-06-12T12:16:35Z [126307] WARNING {queries} slow query: 'UPSERT {"taskid": "6027794", "url": "http://dev.cs-market.com/azure/index.php?dispatch=product_features.add_product&pro      duct_id=41&redirect_url=index.php%3Fitems_per_page%3D96%26sort_by%3Dproduct%26sort_order%3Ddesc%26currency%3DGBP%26dispatch%3Dcategories.view%26category_id%3D225"} INSERT {"taskid"      : "6027794", "url": "http://dev.cs-market.com/azure/index.php?dispatch=product_features.add_product&product_id=41&redirect_url=index.php%3Fitems_per_page%3D96%26sort_by%3Dproduct%2      6sort_order%3Ddesc%26currency%3DGBP%26dispatch%3Dcategories.view%26category_id%3D225"} UPDATE {} INTO failed_url_queue  OPTIONS { ignoreErrors: true }', took: 110.745969 s

-----
Logs of dbservers:
019-06-12T07:43:43Z [47955] INFO {agencycomm} Flaky agency communication to http+tcp://10.194.208.7:8531. Unsuccessful consecutive tries: 48 (6.19s). Network checks advised. Server running.
2019-06-12T07:43:43Z [47955] INFO {agencycomm} Flaky agency communication to http+tcp://10.194.48.30:8531. Unsuccessful consecutive tries: 49 (6.2s). Network checks advised. Server running.
2019-06-12T07:43:43Z [47955] WARNING {heartbeat} Heartbeat: Could not read from agency!2019-06-12T07:43:43Z [47955] INFO {agencycomm} Flaky agency communication to http+tcp://10.194.208.7:8531. Unsuccessful consecutive tries: 36 (7.97s). Network checks advised. Server running.

**Comment by ObiWahn** [comment]
Why would you run more than 1 coordinator, 1 dbserver and 1 agent on single machine? Your Setup does not make sense.
