### ISSUE TITLE
Missing results in search view for STARTS_WITH

### ISSUE THREAD

**Issue by davechallis** [arangodb/arangodb#9252]
## My Environment

* __ArangoDB Version__:        3.4.6
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server

## Component, Query & Data

__Affected feature__:

Search views

__Problem__:

I have a search view named `v_organisation` on a collection named `organisation` defined with:

```
  "links": {
    "organisation": {
      "analyzers": [
        "identity"
      ],
      "fields": {
        "name": {
          "analyzers": [
            "text_en"
          ]
        }
      },
      "includeAllFields": false,
      "storeValues": "none",
      "trackListPositions": false
    },
```

When I query it using `STARTS_WITH`, for certain query terms only, I'm getting matches only for prefixes, and not full word matches.

For example, the following query works as expected:

```
FOR doc IN v_organisation
  SEARCH ANALYZER(STARTS_WITH(doc.name, "microsoft"), "text_en")
  RETURN doc.name
```

I get several results that include the full word "microsoft":

```
[
  "MICROSOFT TECHNOLOGY LICENSING LLC",
  "MICROSOFT CORP",
  "MICROSOFT TECHNOLOGIES LICENSING LLC",
  "MICROSOFT TECHNOLOY LICENSING LLC"
]
```

However, for other queries, I get no results when the full query word matches:

```
FOR doc IN v_organisation
  SEARCH ANALYZER(STARTS_WITH(doc.name, "vauxhall"), "text_en")
  RETURN doc.name
```

returns no matches:

```
[]
```

If I change the query to only include a prefix of the word I'm searching for, then I do get results that should have matched the full word though:

```
FOR doc IN v_organisation
  SEARCH ANALYZER(STARTS_WITH(doc.name, "vauxhal"), "text_en")
  RETURN doc.name
```

returns

```
[
  "VAUXHALL MOTORS LTD LUTON BEDFORDSHIRE GROSSBRITANNIEN",
  "VAUXHALL MOTORS LTD",
  "Vauxhall Boiler Co Ltd",
  "Vauxhall Iron Works Co Lt"
]
```

I would have expected  all of the above results when querying for "vauxhall", not just when querying with "vauxhal". Whereas other query terms such as "microsoft" and "microsof" both return the correct results.

**Comment by maxkernbach** [comment]
Hi @davechallis,

thanks for reporting, I was able to reproduce the described behavior.
We are currently investigating this issue.

**Comment by Dronplane** [comment]
Hi, @davechallis,

This is because of stemming, included in analyzer you are using (text_en).
You may run query to see analyzer output.
`RETURN TOKENS ('VAUXHALL MOTORS LTD', 'text_en')`
output will be
```

[
 [
   "vauxhal",
   "motor",
   "ltd"
 ]
]
```

That`s why there will be no matches for Vauxhall. To workaround you could use query like this

`FOR doc IN v_organisation   SEARCH ANALYZER(STARTS_WITH(doc.name, TOKENS('VAUXHALL', 'text_en')[0]), 'text_en')   RETURN doc.name`

**Comment by davechallis** [comment]
@Dronplane Ah, many thanks, that query you suggested solves the issue for me. Is there some documentation on how the analyzer transforms things somewhere? Would be interesting to know what it's doing in case anything similar comes up in future.

**Comment by Dronplane** [comment]
Documentation on TOKENS
https://www.arangodb.com/docs/stable/aql/views-arango-search.html#tokens
Analyzers list:
https://www.arangodb.com/docs/stable/views-arango-search-analyzers.html
