### ISSUE TITLE
dropped database appears

### ISSUE THREAD

**Issue by daoxian** [arangodb/arangodb#9253]
After dropping a database in arangosh,  I created a new database with the same name. Then I found all the collections in the old database appear again. Is this a feature or a bug?

**Comment by dothebart** [comment]
please try with a new arangosh, maybe its been caching that list

**Comment by daoxian** [comment]
Drop failed this time.

![image](https://user-images.githubusercontent.com/34263430/59352185-a2392700-8d52-11e9-8b32-37b2c7f47687.png)

PS: There are thounds of tables in the database.

**Comment by maxkernbach** [comment]
Hi @daoxian,

in order to to drop a database you have to execute `db._dropDatabase()`, not `db._drop()`.

**Comment by daoxian** [comment]
Alright...  but
![image](https://user-images.githubusercontent.com/34263430/59353855-77e96880-8d56-11e9-9fa7-a78fd45feaf2.png)
What does 'conflict' mean?

**Comment by daoxian** [comment]
And now ,the database is gone after 'conflict'...

**Comment by daoxian** [comment]
> Hi @daoxian,
> 
> in order to to drop a database you have to execute `db._dropDatabase()`, not `db._drop()`.

What's the difference?

**Comment by ObiWahn** [comment]
The first drops databases the other drops collections. How about reading at least some of the documentation?
