### ISSUE TITLE
What's the limit of number of collections in a database?

### ISSUE THREAD

**Issue by daoxian** [arangodb/arangodb#9265]
I have to create amount of collections in one databases,  then what's the upper limit?

**Comment by ObiWahn** [comment]
There is no fix limit. It will just be less performant at some point.

**Comment by daoxian** [comment]
ok, thanks

**Comment by Simran-B** [comment]
BTW. There is a limit to how many collections can be involved in a **single** AQL query (2048): https://github.com/arangodb/arangodb/blob/3.4/arangod/Aql/Collections.h#L62
