### ISSUE TITLE
Got 'ERROR_QUEUE_FULL'  ---named queue is full

### ISSUE THREAD

**Issue by daoxian** [arangodb/arangodb#9274]
Hi there, when I parallel access arangodb with multi-threading model, I often get the error message: "named queue is full" in python driver, which means an ERROR_QUEUE_FULL error. I'm looking forward to the startup-parameters to increase the queue length.

**Comment by maxkernbach** [comment]
Hi @daoxian,

did you already try to modify the following `arangod` options?

```
  --server.maximal-queue-size <uint64>        size of the priority 2 fifo (default: 4096)
  --server.scheduler-queue-size <uint64>      number of simultaneously queued requests inside the scheduler (default: 128)
```

**Comment by daoxian** [comment]
Yes, the maximum queue size is modified to 0

**Comment by daoxian** [comment]
I enlarged both the prio-1 & 2  queue size, and this problem vanished.
