### ISSUE TITLE
RocksDBIndex.cpp:282 blackListKey invocation encounters  an segmentation fault in 3.3.19

### ISSUE THREAD

**Issue by satanson** [arangodb/arangodb#9294]
## My Environment

* __ArangoDB Version__:        v3.3.19
* __Storage Engine__:            RocksDB
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   Manual Start
* __Infrastructure__:               own 
* __Operating System__:      CentOS release 6.9 (Final)
* __Total RAM in your machine__:       128GB
* __Disks in use__:        SSD
* __Used Package__:       arangodb3-3.3.19-1.x86_64.rpm

## Steps to reproduce

__Problem__: dbserver received SIGSEGV and crashed, when it ran to RocksDBIndex.cpp:282 and invoked blacklistKey to invalidate key kept in the cache of the index.

a core was dumped to disk.

examine the core file, there is only one stack frame.

```
Program terminated with signal 11, Segmentation fault.
#0  0x0000000000ca6e26 in arangodb::RocksDBIndex::blackListKey(char const*, unsigned long) ()
    at /var/lib/otherjenkins/workspace/RELEASE__BuildPackages/arangod/RocksDBEngine/RocksDBIndex.cpp:282
282	/var/lib/otherjenkins/workspace/RELEASE__BuildPackages/arangod/RocksDBEngine/RocksDBIndex.cpp: No such file or directory.
	in /var/lib/otherjenkins/workspace/RELEASE__BuildPackages/arangod/RocksDBEngine/RocksDBIndex.cpp
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.209.el6_9.2.x86_64
(gdb) bt
#0  0x0000000000ca6e26 in arangodb::RocksDBIndex::blackListKey(char const*, unsigned long) ()
    at /var/lib/otherjenkins/workspace/RELEASE__BuildPackages/arangod/RocksDBEngine/RocksDBIndex.cpp:282
Cannot access memory at address 0x7f187f16dc48
```

this pointer is illegal!

```
(gdb) p *(RocksDBIndex*)$rax
Cannot access memory at address 0x7f187f16dbf0
```

other information maybe help!

```
(gdb) info registers
rax            0x7f187f16dbf0	139743188147184
rbx            0x7f3a906daed0	139889507938000
rcx            0x11	17
rdx            0x7f301a2d9f2c	139844574355244
rsi            0x0	0
rdi            0x7f187f16dbf0	139743188147184
rbp            0x7f187f16dc40	0x7f187f16dc40
rsp            0x7f187f16dbf0	0x7f187f16dbf0
r8             0xf	15
r9             0xf3	243
r10            0xf3	243
r11            0x1	1
r12            0x11	17
r13            0x7f301a2d9f2c	139844574355244
r14            0x7f187f16dc10	139743188147216
r15            0x7f187f16edd0	139743188151760
rip            0xca6e26	0xca6e26 <arangodb::RocksDBIndex::blackListKey(char const*, unsigned long)+70>
eflags         0x10206	[ PF IF RF ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0
(gdb) info locals
TRI_INDEX_HANDLE_SEPARATOR_STR = <error reading variable TRI_INDEX_HANDLE_SEPARATOR_STR (Unhandled dwarf expression opcode 0xf2)>
rocksdb::HistogramsNameMap = {<std::_Vector_base<std::pair<rocksdb::Histograms, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<rocksdb::Histograms, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >> = {
    _M_impl = {<std::allocator<std::pair<rocksdb::Histograms, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >> = {<__gnu_cxx::new_allocator<std::pair<rocksdb::Histograms, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >> = {<No data fields>}, <No data fields>}, _M_start = 0x7f3aa5a1e000,
      _M_finish = 0x7f3aa5a1e4d8, _M_end_of_storage = 0x7f3aa5a1e4d8}}, <No data fields>}
TRI_VOC_SYSTEM_DATABASE = <error reading variable TRI_VOC_SYSTEM_DATABASE (Unhandled dwarf expression opcode 0xf2)>
TRI_COL_NAME_USERS = <error reading variable TRI_COL_NAME_USERS (Unhandled dwarf expression opcode 0xf2)>
TRI_DOCUMENT_HANDLE_SEPARATOR_STR = <error reading variable TRI_DOCUMENT_HANDLE_SEPARATOR_STR (Unhandled dwarf expression opcode 0xf2)>
rocksdb::TickersNameMap = {<std::_Vector_base<std::pair<rocksdb::Tickers, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<rocksdb::Tickers, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >> = {
    _M_impl = {<std::allocator<std::pair<rocksdb::Tickers, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >> = {<__gnu_cxx::new_allocator<std::pair<rocksdb::Tickers, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >> = {<No data fields>}, <No data fields>}, _M_start = 0x7f3aa5a10000,
      _M_finish = 0x7f3aa5a10e88, _M_end_of_storage = 0x7f3aa5a10e88}}, <No data fields>}
boost::asio::detail::service_base<boost::asio::detail::task_io_service>::id = {<boost::asio::io_service::id> = {<boost::asio::detail::noncopyable> = {<No data fields>}, <No data fields>}, <No data fields>}
boost::asio::detail::service_base<boost::asio::detail::strand_service>::id = {<boost::asio::io_service::id> = {<boost::asio::detail::noncopyable> = {<No data fields>}, <No data fields>}, <No data fields>}
boost::asio::detail::call_stack<boost::asio::detail::strand_service::strand_impl, unsigned char>::top_ = {<boost::asio::detail::keyword_tss_ptr<boost::asio::detail::call_stack<boost::asio::detail::strand_service::strand_impl>::context>> = {<boost::asio::detail::noncopyable> = {<No data fields>}, static value_ = <error reading variable>
boost::asio::detail::service_base<boost::asio::detail::epoll_reactor>::id = {<boost::asio::io_service::id> = {<boost::asio::detail::noncopyable> = {<No data fields>}, <No data fields>}, <No data fields>}
boost::asio::detail::call_stack<boost::asio::detail::task_io_service, boost::asio::detail::task_io_service_thread_info>::top_ = {<boost::asio::detail::keyword_tss_ptr<boost::asio::detail::call_stack<boost::asio::detail::task_io_service, boost::asio::detail::task_io_service_thread_info>::context>> = {<boost::asio::detail::noncopyable> = {<No data fields>},
    static value_ = <error reading variable>
```

**Comment by dothebart** [comment]
hi, do try to use an index on any `_id` field?

**Comment by satanson** [comment]
No index on any _id field. SIGSEGV happened after the arango cluster had run for a few weeks, there was not any more new index added. we have 3 types of workloads: the first is bulk load via spark job hosted on yarn, the second is online incremental update via flink job also hosted on yarn, the third one is most critical, which  provides {one, two}-hop query for risk control business. I think it's a hidden bug, isn't it ? BTW, I want to do some thing to make this failure reoccur, but test/dev environment is quite different from production environment. so, how？

**Comment by dothebart** [comment]
oh, I just see its .19 - there have been many cluster related bugfixes on the way to 3.3.23 - please upgrade your system and see whether these errors persist.

**Comment by satanson** [comment]
@dothebart 
I see it, Maybe I should read the diff between v3.3.19 and v3.3.23 to find out the fix.

**Comment by maxkernbach** [comment]
Hi @satanson,

Did you have a chance to upgrade your cluster to 3.3.23?
Is the error/crash still occurring?

**Comment by satanson** [comment]
> Hi @satanson,
> 
> Did you have a chance to upgrade your cluster to 3.3.23?
> Is the error/crash still occurring?

hi @maxkernbach,
Our arango cluster is deployed in production environment, we plan to upgrade to 3.3.23, but the upgrade action will be done after several months in the future because of worrying abort upgrading infulence clients.

**Comment by OmarAyo** [comment]
Hi @satanson 

It has been a while since our latest interaction - do you have any ETA about upgrading your environment ? 

FYI ArangoDB version 3.3.24 is now ready for download

Looking forward to your reply

Best

**Comment by satanson** [comment]
> Hi @satanson
> 
> It has been a while since our latest interaction - do you have any ETA about upgrading your environment ?
> 
> FYI ArangoDB version 3.3.24 is now ready for download
> 
> Looking forward to your reply
> 
> Best

Hi @OmarAyo 
The product environment had already been upgraded to  3.2.23, segmentation fault has not recurred yet so far.  but one of our three dbservers always hausts memory after serveral weeks, the memory utility of this dbserver increments day by day, when it reaches 90%~95%, just "kill -2 pid" operation is performed manually  then restart dbserver. so, I guess there is memory leak in dbserver.

**Comment by OmarAyo** [comment]
Hi @satanson 

I am sending this message to check the status of this ticket, how things are going on ?

Is the memory issue on the 3rd dbserver still occuring ? If yes, we invite you have a look at this blogpost 

https://www.arangodb.com/2019/03/small-steps-reduce-arangodb-resource-footprint/

Best,

**Comment by OmarAyo** [comment]
Hi @satanson 

We have not heard back from you recently, we are closing this ticket - feel free to reopen it at any time you want by commenting

Best

**Comment by satanson** [comment]
> Hi @satanson
> 
> We have not heard back from you recently, we are closing this ticket - feel free to reopen it at any time you want by commenting
> 
> Best

OK
