### ISSUE TITLE
[Web UI bug] System resources tab display wrong data

### ISSUE THREAD

**Issue by daoxian** [arangodb/arangodb#9299]
3.4.5, RocksDB, single mode.

The display value of memory is 10 times the actual value.
![image](https://user-images.githubusercontent.com/34263430/59772469-6831cd00-92de-11e9-92ab-bb0d539ae228.png)
![image](https://user-images.githubusercontent.com/34263430/59772681-ceb6eb00-92de-11e9-9cfc-fc915ff51641.png)

**Comment by dothebart** [comment]
Hi, 
whats the host? (os)  i.e. on my local physical debian machine the value written is correct...

**Comment by daoxian** [comment]
Local physical machine, centos7
