### ISSUE TITLE
Improve error message when block cache limit is exceeded

### ISSUE THREAD

**Issue by bischoje** [arangodb/arangodb#9319]
## My Environment

* __ArangoDB Version__:        3.4.6-1
* __Storage Engine__:             rocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Kubernetes
* __Configuration__:               enforce-block-cache-size-limit = true

## Steps to reproduce

1. Configure arangod.conf with a small `block-cache-size` and set `enforce-block-cache-size-limit = true`
2. Try to load documents larger than the `block-cache-size` limit.
3. Arango entered a crash loop at this point in our Kubernetes environment. It was resolved after setting `enforce-block-cache-size-limit = false`

__Problem__:
The error message printed was confusing and did not make it clear that we had exceeded the `block-cache-size` limit.

__Expected result__:
A clear error message should be printed that lets the user know that the `block-cache-size` limit has been exceeded.

This is the error that we saw in the logs (repeatedly, once per restart in the crash loop):

```arangodb: 2019-06-21T18:31:40Z [1] WARNING {arangosearch} caught exception while loading configuration: 1240 'incomplete' error in storage engine
arangodb: 2019-06-21T18:31:40Z [1] ERROR {startup} startup aborted: caught exception during start of feature 'IResearchAnalyzer': uninitialized AnalyzerPool detected while validating analyzers (exception location: /work/ArangoDB/arangod/IResearch/IResearchAnalyzerFeature.cpp:1150). Please report this error to arangodb.com. shutting down
arangodb: 2019-06-21T18:31:41Z [1] INFO ArangoDB has been shut down
arangodb: 2019-06-21T18:31:41Z [1] ERROR arangod terminated because of an exception: startup aborted: caught exception during start of feature 'IResearchAnalyzer': uninitialized AnalyzerPool detected while validating analyzers (exception location: /work/ArangoDB/arangod/IResearch/IResearchAnalyzerFeature.cpp:1150). Please report this error to arangodb.com (exception location: /work/ArangoDB/lib/ApplicationFeatures/ApplicationServer.cpp:675). Please report this error to arangodb.com
```

**Comment by dothebart** [comment]
https://github.com/arangodb/arangodb/pull/9318 adds the missing rocksdb error to the arangodb logfile.

**Comment by maxkernbach** [comment]
Hi @bischoje,

Release Candidate 7 of ArangoDB 3.5, which includes a fix for this issue, has just been released.
Please find the latest RC in the [download section](https://www.arangodb.com/download-technical-preview/).

In case the error message is not improved, please comment and we will reopen.
