### ISSUE TITLE
Foxx: Adjust bodyParam to the other params

### ISSUE THREAD

**Issue by moonglum** [arangodb/arangodb#935]
I made a mistake in the design of bodyParam: It works differently than the other two params. I therefore would like to fix this.

Both `pathParam` and `queryParam` take the name of the attribute as the first argument and an object as the second one. This object contains the description, type etc. `bodyParam` on the other hand takes the description and type as the second and third argument. I therefore would like to see the following API for bodyParam:

``` js
bodyParam('content', {
  description: "Bla",
  type: MyFoxxModel
});
```

This has to be backwards compatible though – but please log a deprecated message for the old way of doing things.

**Comment by razvanphp** [comment]
@pluma what about this in swagger 2.0? Anything changed?

Currently I cannot properly document the body as an array of integers.
What I tried:
````javascript
.bodyParam("order", {
            description: 'The ordered productIds list for the given sortList and categoryId',
            required: true,
            type: [ joi.number() ]
        }
````
````javascript
.bodyParam("order", {
            description: 'The ordered productIds list for the given sortList and categoryId',
            required: true,
            type: joi.array().items(joi.number())
        }
````
and both show up as Model object `{}`. In `pathParam` the same schema ends up correctly as `Array[]`

**Comment by pluma** [comment]
No, this is a pre-existing problem.

There's currently no simple way to convert joi schemas to JSONSchema (which Swagger expects). There's a conversion function in ArangoDB but it doesn't yet handle non-objects.

I've tried the most straightforward conversion for non-objects and it causes Swagger to blow up when generating the example data (as does the output of [joi-to-json-schema](https://www.npmjs.com/package/joi-to-json-schema), so it may be an issue with Swagger itself). Also, in Swagger 2.0 the body parameter schema seems to work a bit differently compared to other parameter types. I'll have to look into this.
