### ISSUE TITLE
[Bug] GEO_CONTAINS: point in a bigger rectangle doesn't work

### ISSUE THREAD

**Issue by baslr** [arangodb/arangodb#9352]
compiled on x86_64 Debian Buster
`commit 3c6264b9b0c200d9a38bf1f37b9e261127a1d261 (devel branch)`
```
LET geojson = 
{   "type": "Feature",
    "properties": {},
    "geometry": {
      "type": "Polygon",
      "coordinates": [[[-100, 60],
          [-100,0],
          [90,0],
          [90,60],
          [-100,60]]]}}

LET ArangoDBCologneOffice = [6.939945, 50.932222]
RETURN GEO_CONTAINS(geojson.geometry, ArangoDBCologneOffice)

// returns FALSE, should return TRUE?
```
Polygon
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/1494154/60395359-5fd55f80-9b32-11e9-94fa-8b995b5dc606.png">

Is this a limitation from the s2 index? I found nothing in the ArangoDB documentation.

xref d3/d3-geo/issues/169

**Comment by baslr** [comment]
```js
const turf = require('@turf/turf');

const a = {
  "type": "Feature",
  "properties": {},
  "geometry": {
    "type": "Polygon",
    "coordinates": [[[-100, 60],
    [-100, 0],
    [90, 0],
    [90, 60],
    [-100, 60]]]
  }
}

const pt = turf.point([6.939945, 50.932222]);
const res = turf.booleanPointInPolygon(pt, a);
console.log(res); // true
```

**Comment by Simran-B** [comment]
Remark added to docs:

> A linear ring defines two regions on the sphere. ArangoDB will always interpret
  the region of smaller area to be the interior of the ring. This introduces a
  practical limitation that no polygon may have an outer ring enclosing more
  than half the Earth's surface.

https://github.com/arangodb/docs/pull/135

Can the issue be closed?

**Comment by maxkernbach** [comment]
@baslr Thanks for reporting.

I am closing this issue as fixed since the missing limitation has been added to the documentation (as shown in the previous comment).
