### ISSUE TITLE
Query on 3 nodes cluster with 1 shard is taking 4X time for the same query on single node

### ISSUE THREAD

**Issue by ImSajeed** [arangodb/arangodb#9356]
ArangoDB Version: 3.4.4
Storage Engine : RocksDB
Deployment Mode: Cluster - 3 Server
Deployment Strategy : Manual Start
Infrastructure: AWS
Operating System: Ubuntu 16.04
Total RAM in your machine: 32Gb.

Hi, we are using 3 Node cluster setup having number of shards as 1.
Query on 3 nodes cluster with 1 sharad is taking 4X time for the same query on single node

Could you please let us know how we can optimize this.

**Comment by lservini** [comment]
Hi ImSajeed,

Would you kindly provide the query, the dataset (or a sample) and the list of indexes you have in place?

Thanks

**Comment by ImSajeed** [comment]
Hi @lservini ,

Please find the requested details

On Cluster:
![image](https://user-images.githubusercontent.com/22313972/60410681-109d3680-9be7-11e9-944a-77dabcfd4dc2.png)

![image](https://user-images.githubusercontent.com/22313972/60410694-24e13380-9be7-11e9-9ade-3e1a37dad213.png)

On Single Instance:
![image](https://user-images.githubusercontent.com/22313972/60410755-5b1eb300-9be7-11e9-891c-a60e2eae81fe.png)

![image](https://user-images.githubusercontent.com/22313972/60410767-6f62b000-9be7-11e9-9627-637f41c0527e.png)

**Comment by lservini** [comment]
Hi ImSajeed,

Is it possible to have the dataset as well, just to give a try in our lab? You can hide/mask sensible filed if you have. 
Let me know.

Thanks

**Comment by ImSajeed** [comment]
Hi @lservini ,

Could you please use any toy data set using any one of index(skip list or hash) on one of the columns. With replication factor as one on the cluster setup with 3 nodes.

Please let me know if real time data is really needed for resolution.

Thanks,
Sajeed.

**Comment by Puneeth-Kadamba** [comment]
Please find the data attached. 

Below is the sample document.
{"_key":"145129757","_id":"Alias/145129757","_rev":"_XxDmAzy--v","aliaskey":10696785,"originalkey":9156924}

Sample Query:
for r in Alias filter r._key=="145129757"
return r

Execution time on Cluster: 0.8ms

Execution time on Single node: 0.1ms
[data.zip](https://github.com/arangodb/arangodb/files/3380925/data.zip)

**Comment by graetzer** [comment]
You do realize there are extra network hops in the cluster?

**Comment by Puneeth-Kadamba** [comment]
Yes. But this is on the primary key, and a single shard. Can this difference in performance completely attributed to the network hop?. The same difference is seen even though the query is on the server where the co-ordinator and the leader is located. Does this also involve network hop?

**Comment by graetzer** [comment]
a difference of 0.7ms ? Yes I think its quite possible. AQL queries need at least one setup request and a shutdown request, so there will be at least 3 requests for that query

**Comment by maxkernbach** [comment]
Hi @ImSajeed and @Puneeth-Kadamba,

Since a performance difference of 0.7ms is expected in a cluster, can we resolve this issue?

**Comment by maxkernbach** [comment]
Closing this issue as solved.

In case you have any further questions, please comment and we will reopen.
