### ISSUE TITLE
High CPU usage after bulk inserting documents

### ISSUE THREAD

**Issue by daoxian** [arangodb/arangodb#9376]
## My Environment

* __ArangoDB Version__:        3.4.5
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   ArangoDB Starter
* __Infrastructure__:               Metal machine
* __Operating System__:        CentOS 7.4
* __Total RAM in your machine__:        500GB
* __Disks in use__:       SSD
* __Used Package__:              20%

Keep bulk-inserting, and after hours' inserting,  the cpu of system usage is more than 90%, and along with user cpu usage, the sum is 100%. Then stop inserting, the cpu usage keeps at 100%, and doesn't decrease, until restart arangod.  I wonder what's arangod doing when cpu at 100%?

**Comment by OmarAyo** [comment]
Hi @daoxian 

Can you please provide:
- logs from around 1st July 
- arangod.conf 
- Starter command (the command you are using to start your Single Server)

Best,

**Comment by daoxian** [comment]
Frequently parallel bulk inserting, batch-size is 1000, leads to arangod hang up shortly,  because RocksDB's Level merge or purge.  When batch-size is set to 100000  it turns out to be better. I don't think logs could be any help, but  pressure-testing (parallel bulk insertion) may be more helpful.

**Comment by matthewvon** [comment]
RocksDB is likely still cleaning up it backlog of compactions.  You can verify this via the Linux top command:  

top -p <pid_of 100% process> -H

The far right column lists the name of the running thread.  Likely you will see "rocksdb:*" still executing.

**Comment by dothebart** [comment]
Since @matthewvon provided the answer to this, I'm closing this as solved.

Please notte [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) is available now.
