### ISSUE TITLE
ArangoDB 3.4.6-1 crashes

### ISSUE THREAD

**Issue by frankcb298** [arangodb/arangodb#9377]
## My Environment

* __ArangoDB Version__:        3.4.6-1
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:              
* __Infrastructure__:               AWS
* __Operating System__:        Ubuntu 18.04
* __Total RAM in your machine__:        1Gb
* __Disks in use__:        SSD
* __Used Package__:              Debian

## Component, Query & Data

__Affected feature__:

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__: just 1 emty collection

__Size of your Dataset on disk__: very small

__Replication Factor & Number of Shards (Cluster only)__: NO

## Steps to reproduce

1. Start the server, create 1 collection
2. Let's server runs for 0.5 day. No query at that time.

__Problem__:
Hourly I check, i saw server memory increases (there is not any query at that time). finally it's crashed after 0.5 day. I can not connect to ArangoDb and EC2 anymore.
After i restart the EC2, i can connect to ArrangoDB successfully

__Expected result__:
I should connect to ArangoDb successfully and memory shouln't increase

**Comment by daoxian** [comment]
According to my experience, pasting the gdb backtrace here may help.

**Comment by maxkernbach** [comment]
Hi @frankcb298,

is `vm.overcommit_memory` on this machine set to value **2**? This might be one possible cause.

> With an vm.overcommit_memory kernel settings value of 2, the allocator may have trouble with splitting existing memory mappings, which makes the number of memory mappings of an arangod server process grow over time. This can lead to the kernel refusing to hand out more memory to the arangod process, even if more physical memory is available.

The full article, which also includes other settings for memory optimization, can be found below:
https://www.arangodb.com/2019/03/small-steps-reduce-arangodb-resource-footprint/

If this does not help, could you please share a core dump of this crash as already suggested? Additionally, can you share the `arangod.log` of your single server?

**Comment by maxkernbach** [comment]
@frankcb298 

Since we have not heard back from you in a while, I am closing this issue for now.
If this problem persists, please reply to my previous message and we will reopen.
