### ISSUE TITLE
Added Binary Package builds into Arch User Repository

### ISSUE THREAD

**Issue by dilipvamsi** [arangodb/arangodb#9420]
Hi,
I have added the binary package builds for installing [arangodb client](https://aur.archlinux.org/packages/arangodb-client-bin/) and [arangodb server](https://aur.archlinux.org/packages/arangodb-bin/) into the Arch User Repository.
I would like you people to add them to arch download page (https://www.arangodb.com/download-major/arch-linux/).

Regards,
Dilip Vamsi.

**Comment by maxkernbach** [comment]
Hi @dilipvamsi,

I am not experienced with Arch Linux packages myself. What is the difference of your arangodb server package compared to @sleepycat's [provided package](https://aur.archlinux.org/packages/arangodb/) (aside from the fact that your package is version 3.4.7 instead of 3.4.5)?

Offering an additional arangodb client package seems like a good idea.

**Comment by dilipvamsi** [comment]
Hi @maxkernbach ,
@sleepycat version gets the sources and compiles the complete system for creating the package (which takes a really long time to complie).
Mine on the other hand is binary version which just downloads the deb package and rearranges the internals to make it work with arch Linux.
Both the server and client are created from the latest deb packages.

Regards, 
Dilip Vamsi.

**Comment by dilipvamsi** [comment]
Hi @maxkernbach ,
Do I need to add anything else for the approval?

Regards,
Dilip Vamsi.

**Comment by maxkernbach** [comment]
Hi @dilipvamsi,

your packages have just been added to the Arch Linux download page.
https://www.arangodb.com/download-major/arch-linux/

Thanks for your contribution!

**Comment by dilipvamsi** [comment]
Cool thanks @maxkernbach 
I will continue to update the package builds whenever there is a new release.
