### ISSUE TITLE
Colocating particular edges & vertices in a sharded server

### ISSUE THREAD

**Issue by MrCreosote** [arangodb/arangodb#9431]
This is a question rather than a bug report or feature request.

From [here](https://www.arangodb.com/docs/stable/architecture-deployment-modes-cluster-data-models.html#graph-database):

> However, if the vertices and edges along the occurring paths are distributed across the cluster, then a lot of communication is necessary between nodes, and performance suffers. To achieve good performance at scale, it is therefore necessary to get the distribution of the graph data across the shards in the cluster right. Most of the time, the application developers and users of ArangoDB know best, how their graphs are structured. Therefore, ArangoDB allows users to specify, according to which attributes the graph data is sharded. A useful first step is usually to make sure that the edges originating at a vertex reside on the same cluster node as the vertex.

I'm trying to figure out how this is possible but can't seem to get there:
* Shard keys are hashed, and so using a field that must be unique (like `_key`) means that vertexes and edges would be effectively randomized into shards.
* That means you need to use a custom shard key, and data that should be sharded together must get the same key (and figuring out which edges & nodes get the same key is a non-trivial problem, really...).
* But:
  * Since collections get their own shards
  * [On which DBServer in a Cluster a particular shard is kept is undefined](https://www.arangodb.com/docs/stable/administration-cluster.html#sharding)
  * Edges and vertices get their own collections
* ... there appears to be no way to ensure that related edges and vertices wind up on the same server, even if they have the same shard key.

Am I missing something here (other than SmartGraphs)? Thanks for any info you can provide.

**Comment by dothebart** [comment]
Hi, 
sorry for the bit late reply; but Yes, thats exactly what smart graphs do. 

please note that [ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) is available.

**Comment by MrCreosote** [comment]
So based on the documentation linked above, it's therefore impossible to get good performance at scale with ArangoDB without SmartGraphs? Is that correct?

**Comment by goedderz** [comment]
> So based on the documentation linked above, it's therefore impossible to get good performance at scale with ArangoDB without SmartGraphs? Is that correct?

No. Please read https://www.arangodb.com/why-arangodb/arangodb-enterprise/arangodb-enterprise-smart-graphs/. With SmartGraphs, you have to specify the "smart" attribute, which is used for sharding. Incident edges to a vertex are always colocated.

**Comment by MrCreosote** [comment]
The document appears to support the standpoint that the community edition's performance suffers at scale:

> The Community Edition of ArangoDB can handle large data-sets on a single instance, allowing you to scale vertically without issue. It can also handle scaling horizontally to a cluster with all three data models. However, you may begin to encounter performance issues when, in scaling horizontally, you shard a graph through the cluster..... Eventually, performance degrades to a point where it’s no longer suitable for your given use case.

**Comment by weinberger** [comment]
@MrCreosote  I disagree with this conclusion, not only based on my role ;)
ArangoDB Community offers the same sharding capabilities as many other graph databases. It would also be possible to do a manual sharding of sub-graphs as others offer. This is possible for the storage as well as for the queries. The SmartGraph functionality goes beyond these capabilities and contains some very specific optimizations. As we decided to make it an Enterprise features we had in mind that such a use case will most likely more a use case of a larger Enterprise.

**Comment by MrCreosote** [comment]
Golly, I seem to have stirred the hornet's nest :P

>  I disagree with this conclusion

I wouldn't say I've come to any particular conclusion; I'm just pointing out what the documentation says regarding scaling the community edition - or at least my interpretation of what it says. I assume at least some other people will interpret the documentation the same way - hopefully I'm not being entirely idiosyncratic.

> It would also be possible to do a manual sharding of sub-graphs

This is the crux of the ticket, IMO - how is this accomplished? Based on the points I brought up in the first post it doesn't seem to be possible. I assume I'm missing something but I can't figure out what it is.
