### ISSUE TITLE
Duplicate POST to /_api/gharial/{graph}/vertex/{collection} results in 404

### ISSUE THREAD

**Issue by stoft** [arangodb/arangodb#9449]
## My Environment

* __ArangoDB Version__:        3.4.6-1 (Docker)
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start
* __Configuration__:               vanilla docker image
* __Infrastructure__:               vanilla docker image
* __Operating System__:        MacOS
* __Total RAM in your machine__:        N/A
* __Disks in use__:        N/A
* __Used Package__:              official vanilla docker image

## Component, Query & Data

__Affected feature__:
HTTP API: /_api/gharial/{graph}/vertex/{collection}

## Steps to reproduce

Run the below twice.

"""
curl -X POST \
  http://localhost:32769/_db/apicat_test/_api/gharial/multi_tenant_storage_accounts/vertex/subjects \
  -H 'Authorization: Basic ***********************' \
  -H 'Content-Type: application/json' \
  -H 'cache-control: no-cache' \
  -d '{"_key":"mykey"}'
"""

__Problem__:
A duplicate POST call to create a Vertex that already exists in a graph results in a *404 not found*, which implies that the graph and/or collection doesn't exist. 

__Expected result__:
A more correct response would probably be 409 or 422 (see https://stackoverflow.com/questions/3825990/http-response-code-for-post-when-resource-already-exists)

**Comment by maxkernbach** [comment]
Hi @stoft,

Thanks for reporting, error codes 409 or 422 are definitely more meaningful.
This bug is already verified in issue https://github.com/arangodb/arangodb/issues/8071, though.
