### ISSUE TITLE
Http connection number does not decrease after timeout

### ISSUE THREAD

**Issue by GaetanLhoest** [arangodb/arangodb#9461]
## My Environment

* __ArangoDB Version__:        
3.4.6
* __Storage Engine__:             
RocksDB
* __Deployment Mode__:       
Single Server
* __Deployment Strategy__:   
Manual Start in Docker
* __Configuration__:               
custom (12 vCPUs, 56 GB memory) 
Intel Haswell
* __Infrastructure__:               
Google Cloud
* __Operating System__:        
Debian
* __Total RAM in your machine__:        
56Gb
* __Disks in use__:        
SSD 100Gb
* __Used Package__:              
Compiled from sources

## Component, Query & Data

__Affected feature__:

AQL queries using Python driver

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. Launch hundreds of AQL queries in parallel
2. Look at the opened HTTP connections number
3. Wait after the timeout
4. Look at the opened HTTP connections number

__Problem__:
The number of connections does not decrease, even after the timeout.
```bash
curl ...:8529/_admin/statistics 

```
```json
{"time": 1562855056.7247725, "enabled": true, "system": {"minorPageFaults": 13253258, "majorPageFaults": 0, "userTime": 8929.63, "systemTime": 845.4, "numberOfThreads": 77, "residentSize": 14784524288, "residentSizePercent": 0.25014936527813264, "virtualSize": 28072108032}, "client": {"httpConnections": 89, "connectionTime": {"sum": 0, "count": 0, "counts": [0, 0, 0, 0]}, "totalTime": {"sum": 1515.7838401794434, "count": 122760, "counts": [105771, 11189, 3580, 1376, 582, 131, 131]}, "requestTime": {"sum": 1129.61589884758, "count": 122760, "counts": [114790, 3213, 2872, 1151, 512, 100, 122]}, "queueTime": {"sum": 0, "count": 0, "counts": [0, 0, 0, 0, 0, 0, 0]}, "ioTime": {"sum": 386.1679413318634, "count": 122760, "counts": [113268, 8471, 794, 168, 37, 14, 8]}, "bytesSent": {"sum": 291772440, "count": 122760, "counts": [4448, 110703, 1925, 1364, 233, 4087]}, "bytesReceived": {"sum": 64640057, "count": 122760, "counts": [16, 118938, 1764, 1610, 167, 265]}}, "http": {"requestsTotal": 122761, "requestsAsync": 0, "requestsGet": 108509, "requestsHead": 0, "requestsPost": 12638, "requestsPut": 118, "requestsPatch": 0, "requestsDelete": 1496, "requestsOptions": 0, "requestsOther": 0}, "server": {"uptime": 2953.748656272888, "physicalMemory": 59102785536, "v8Context": {"available": 1, "busy": 0, "dirty": 0, "free": 1, "max": 64}, "threads": {"scheduler-threads": 33, "in-progress": 3, "queued": 3, "current-fifo1": 0, "fifo1-size": 1048576, "current-fifo2": 0, "fifo2-size": 4096, "current-fifo3": 0, "fifo3-size": 4096}}, "error": false, "code": 200}
```

Here is the scenario
We launch 
```bash
netstat -ant | awk '{print $6}' | sort | uniq -c | sort -n
```
and have 
```bash
1 CLOSE WAIT
1 Foreign
1 established)
5 ESTABLISHED
6 LISTEN
```
We launch the stress test. When it's over, we look again and have:
```bash
1 CLOSE WAIT
1 Foreign
1 established)
6 ESTABLISHED
327 LISTEN
```
After 10 minutes, we look again and have
```bash
1 CLOSE WAIT
1 Foreign
1 established)
6 ESTABLISHED
210 LISTEN
```

As the stress test launch the AQL function from lambda aws function, which are closed after 5 minutes, and the timeout is 60 secondes, every HTTP connection should be closed after 10 minutes

__Expected result__:
The number of connection should return to around 0, and not be stuck around hundreds

**Comment by dothebart** [comment]
Hi, 
whats opening these server ports (`LISTEN`) 
and you don't seem to filter for the actual arangodb `established` ports. 
Can you paste output the full results of  `netstat -alpnt` ?

**Comment by GaetanLhoest** [comment]
We fixed this issue by replacing the keep_alive header by close. 
Do you need me to re-setup everything to reproduce it and provide you this info?

**Comment by dothebart** [comment]
so you're now working without connection keepalive? You usually then run into `CLOSE_WAIT` sockets eating all your available TCP-Sockets.

**Comment by dothebart** [comment]
Closing as solved.

**Comment by dothebart** [comment]
This was an issue with ArangoDB loosing track of finished connection objects which has meanwhile been taken care of. 

[ArangoDB 3.7](https://www.arangodb.com/2020/08/arangodb-3-7-a-big-step-forward-for-multi-model/) is available for download, and should not show this behaviour anymore.
