### ISSUE TITLE
Docker freeze after thounsand of Pregel jobs

### ISSUE THREAD

**Issue by GaetanLhoest** [arangodb/arangodb#9462]
## My Environment

* __ArangoDB Version__:        
3.4.6
* __Storage Engine__:             
RocksDB
* __Deployment Mode__:       
Single Server
* __Deployment Strategy__:   
Manual Start in Docker
* __Configuration__:               
custom (12 vCPUs, 56 GB memory) Intel Haswell
* __Infrastructure__:               
Google Cloud
* __Operating System__:        
Debian Jessie
* __Total RAM in your machine__:        
56GB
* __Disks in use__:        
SSD 100GB
* __Used Package__:              
Compiled from sources

## Component, Query & Data

__Affected feature__:

Pregel Queries

__AQL query (if applicable)__:
We use the Pregel Algorithm Shortest path

__AQL explain (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. Launch thousands of Pregel jobs for shortest path

__Problem__:

The docker freeze and must be restarted

We are currently retrieving the /var/log/syslog files and will provide them asap

__Expected result__:
Continue to work

**Comment by maxkernbach** [comment]
Hi @GaetanLhoest,

are you still facing this issue?
If so, could you please provide the log files?

**Comment by GaetanLhoest** [comment]
After some investigations, we could not reproduce this issue on a baremetal server, it only occurred on google cloud compute instances. We tried to retrieve logs on these google cloud compute instances but there were none.

**Comment by OmarAyo** [comment]
Hi @GaetanLhoest,

Okay, I am going to close this issue now and you can reopen it at any time once you are able to reproduce/collect logs so we can continue our analysis 

Best
