### ISSUE TITLE
registered keywords in objects props

### ISSUE THREAD

**Issue by neymanushka** [arangodb/arangodb#9490]
Hello!

using registered keywords as properties of objects,how?
example: 

```
FOR obj IN @@collection
RETURN { updateDate: obj.prop1.prop2.update }
```
this give me an error. i can go this way ```updateDate: obj["prop1"]["prop2"]["update"]```,but it not readable

**Comment by Simran-B** [comment]
Hey!

The bracket notation might not look as clean as the dot notation, but I wouldn't call it unreadable.

Anyway, you can use the dot notation even if the attribute name coincides with a keyword if you wrap it in backticks or forward ticks:

```js
LET obj = { prop1: { prop2: {´update´: true } } }
RETURN { updateDate: obj.prop1.prop2.`update` }
```

Docs: https://www.arangodb.com/docs/stable/aql/fundamentals-syntax.html#names

**Comment by neymanushka** [comment]
exactly what is needed! thank you very much!
