### ISSUE TITLE
AQL::MATCHES() & arangojs & aql & db.query & "/_api/cursor" use  MATCHES(t,{attr:undefined}) equals MATCHES(t, {}) 

### ISSUE THREAD

**Issue by miss61008596** [arangodb/arangodb#9568]
## My Environment

* __ArangoDB Version__:        3.4.4
* __Storage Engine__:             RocksDB
* __Deployment Mode__:      Single Server
* __Deployment Strategy__:  ArangoDB Starter in Docker
* __Configuration__:               default settings
* __Infrastructure__:               own
* __Operating System__:        centos 7
* __Total RAM in your machine__:        2Gb
* __Disks in use__:        SSD
* __Used Package__:              Docker - official

## Component, Query & Data

__Affected feature__:
AQL query using driver arangojs

__AQL query (if applicable)__:
```js
const _filter = {access_token: undefined};
const query = aql`
      FOR t IN token
        FILTER MATCHES(t, ${_filter} ) == true && t._status == true 
      RETURN t `;
```
__AQL explain (if applicable)__:

When the property of the _filter object is set to undefined, it is equivalent to executing MATCHES(t,{}).

__Dataset__:
```js
LET tokens = [
  {
    "access_token": "75ead3c589b0ef721d6f5c373ce0bd335a9ea66d",
    "access_token_expires_at": "2019-07-25T10:33:03.048Z",
    "authorization_code": "3b5c198b50fffb6157de1844a657a02103a3760f",
    "refresh_token": "bccc0ec88c8668b4218c13ba328d6bdf30d2219f",
    "refresh_token_expires_at": "2019-08-08T09:33:03.048Z",
    "_status": true,
    "_create_date": "2019-07-25 17:33:03"
  },
  {
    "access_token": "cb4966de8d54e064c0a6b07703204e688e590338",
    "access_token_expires_at": "2019-07-25T10:48:14.630Z",
    "authorization_code": "db968b02e4cc8750c5344983d68118646acb1016",
    "refresh_token": "8d1984638137884fbd8b13e36e183a4ab3168f66",
    "refresh_token_expires_at": "2019-08-08T09:48:14.630Z",
    "_status": true,
    "_create_date": "2019-07-25 17:48:14"
  },
  {
    "access_token": "38dea5d7f61a9ca1e53c0071d0ac10b7a9db3312",
    "access_token_expires_at": "2019-07-24T10:01:18.988Z",
    "authorization_code": "9cfa73f1d9e4a93b6a899dcbf5fbe148f1a3883a",
    "refresh_token": "12afd937b75c5ef0dc70d352b1715fd2ad1c09ff",
    "refresh_token_expires_at": "2019-08-07T09:01:18.988Z",
    "_status": true,
    "_create_date": "2019-07-24 17:01:18"
  }
]
FOR t IN tokens
    INSERT t
    INTO token
RETURN NEW
```
## Steps to reproduce

1. Create token collection and save documents.
2. npm install --save arangojs.
3. 
```js
const { Database, aql } = require('arangojs');
const db = new Database();
const _filter = {access_token: undefined};
const query = aql`
      FOR t IN token
        FILTER MATCHES(t, ${_filter} ) == true && t._status == true 
      RETURN t `;
const cursor = await db.query(query);
const result = await cursor.all();
```
__Problem__:
{access_token: undefined} was changed to {}.
The result is all documents of the collection
__Expected result__:
```js
result = [].
```

**Comment by Simran-B** [comment]
`undefined` is not a type in AQL / JSON. An attribute with value `undefined` will be ignored, which makes `{"access_token": undefined}` an empty object `{ }` and thus match all documents if used for `MATCHES()`.

There can be implicit (absence of attribute) and explicit `null` values (`{"access_token": null}`). You can use `const _filter = {access_token: null};` to find documents with the `access_token` attribute missing as well as with a value of `null`. If you need to differentiate between these two cases then add a filter condition `HAS(doc, "access_token")`.

- https://github.com/arangodb/arangojs/blob/master/CHANGELOG.md#670---2018-10-24
- https://www.arangodb.com/docs/stable/aql/fundamentals-data-types.html
- https://www.arangodb.com/docs/stable/aql/functions-document.html#has

**Comment by miss61008596** [comment]
thank you very much for your help, now we know that `JSON.stringify({attr:undefined})` is equal to `"{}".` 
Regarding 

```js
const _filter = {access_token: undefined};
const query = aql`
      FOR t IN token
        FILTER MATCHES(t, ${_filter} ) == true && t._status == true 
      RETURN t `;
```

we finally decided to use Joi to prevent values like undefined and null etc. from appearing in the filter object.

```js
Joi.object().min(1).pattern(/.*/, Joi.any().invalid(null,NaN,Infinity).required()).required().validate({access_token:undefined}, function(error) {
  if (error !== null) {
    throw error.message;
  }
});
```

then we also found out that when the value of the attribute that is not set in the filter is null.

```js
FOR t IN token
	FILTER MATCHES(t, {none_attr: null} ) == true
RETURN t
```

the result is all documents of the collection, because the none_attr attribute of all documents is null, matching to all documents is correct.

I suggest that the {"access_token": undefined} and {none_attr: null} cases can be explained here in the AQL::MATCHES() [documentation](https://www.arangodb.com/docs/3.3/aql/functions-document.html#matches) .
or you can optimize the require('arangojs').aql

```js
const query = aql`
      FOR t IN token
        FILTER MATCHES(t, ${_filter} ) == true && t._status == true
      RETURN t `;
console.log('query: ', query);
----------before optimize--------------
>query: {
  query:' FOR t IN tokenFILTER MATCHES(t, @value0 ) == true && t._status == true RETURN t ',
  bindVars: {
    value0: {
      access_token: undefined
    }
  },
}
----------after optimize--------------
>query: {
  query:' FOR t IN tokenFILTER MATCHES(t, @value0 ) == true && t._status == true RETURN t ',
  bindVars: {
    value0: {}
  },
}
```

just like JSON.stringify().

```js
console.log(JSON.stringify({
  a: function(){},
  b: undefined,
  c: [ function(){}, undefined ],
  d: NaN,
  e: Infinity,
  f: [ NaN,Infinity]
}));
---------------------------------------
>{"c":[null,null],"d":null,"e":null,"f":[null,null]}
```

We created an lightweight  ORM based on AQL to use arangodb, in which we use MATCHES() like this:

```js
/**
   * get document by _filter from collection
   * @param {object} _filter - params object
   * @return {object} - the match document
   */
  async getByFilter(_filter) {
 		Joi.object().min(1).pattern(/.*/,
     	Joi.any().invalid(null,NaN,Infinity).required())
    	.required()
      .validate(_filter, error => {
      	if (error !== null) {
        throw new this.BizError('dao error: ' + error.message);
      	}
    });
    const collection = this.aql.literal(`${this.getCollectionName()}`);
    const query = this.aql`
      FOR t IN ${collection} 
        FILTER MATCHES(t, ${_filter} ) == true && t._status == true 
      RETURN t `;
    try {
      const objs = await this.query(query);
      const { error } = Joi.array().validate(objs);
      if (error !== null) {
        throw new this.BizError('dao error: ' + error.message);
      } else {
        return objs.length === 0 ? {} : objs[0];
      }
    } catch (e) {
      throw e;
    }
  }
```

Say hello to [Frank](https://github.com/fceller), thank you again for your help.

**Comment by Simran-B** [comment]
Please have a look at the documentation PR: https://github.com/arangodb/docs/pull/120/files

**Comment by Simran-B** [comment]
Merged the PR.

**Comment by miss61008596** [comment]
nice work ！
