### ISSUE TITLE
Minor update in documentation - arangoDB version

### ISSUE THREAD

**Issue by miguelpel** [arangodb/arangodb#9606]
### Wrong version number in installation Documentation

The version installed using Homebrew is 3.4.7, but the start command is looking for the version 3.4.0, leading to an error: 'No such file or directory

[Link to documentation page](https://www.arangodb.com/docs/stable/installation-mac-osx.html)

## steps to reproduce:

in Terminal:

`brew install arangodb`

`/usr/local/Cellar/arangodb/3.4.0/sbin/arangod`

## correction proposition:

`/usr/local/Cellar/arangodb/3.4.7/sbin/arangod`

**Comment by Simran-B** [comment]
Thanks for reporting this issue! I opened a pull request to replace the version by a placeholder to make it clear what is expected from the user:

https://github.com/arangodb/docs/pull/131/files

**Comment by sleto-it** [comment]
Closing as a PR has been opened. Changes will be visible in the doc as soon as the PR is merged and the online doc is rebuilt

If needed, please reopen

Thanks again,
