### ISSUE TITLE
ArangoSearch on JSONarray objects

### ISSUE THREAD

**Issue by sudarsan005** [arangodb/arangodb#9616]
## My Environment

* __ArangoDB Version__:        3.4.6
* __Storage Engine__:             rockdb
* __Deployment Mode__:       Single Server 
* __Deployment Strategy__:  Manual Start in Docker
* __Infrastructure__:               GCP
* __Operating System__:        Debian

I am trying to use arango search on nested json array object in a view. it works fine on single non array json fields. but craps out when search is on a json array.

Sample collection JSON object
```
{
	"_key": "xx1sdas",
	"itemId": "xx1",
	"parent": [{
		"childId": "t1",
		"childName": "kai"
	}, {
		"childId": "t2",
		"childName": "tom"
	}]
}
```
error message :
Query: AQL: not implemented: Unable to evaluate loop variable 'item' as a part of ArangoSearch noncompliant expression '_EXPANSION(_ITERATOR($0.parent,$2),$2.childName,) == "tom"' (while executing)

```
FOR item IN iView
  SEARCH ANALYZER(item.parent[*].childName IN TOKENS('tom', 'text_en'), 'text_en')
  SORT BM25(item) DESC 
  LIMIT 10 
RETURN item
```

**Comment by aveiros** [comment]
try
```
FOR item IN iView
  SEARCH ANALYZER(item.parent.childName IN TOKENS('tom', 'text_en'), 'text_en')
  SORT BM25(item) DESC 
  LIMIT 10 
RETURN item
```

View links section
```
  "links": {
    "<<<COLLECTION NAME>>>": {
      "analyzers": [
        "text_en"
      ],
      "fields": {},
      "includeAllFields": true,
      "storeValues": "none",
      "trackListPositions": false
    }
  },
```

**Comment by sudarsan005** [comment]
thank you @aveiros, it works. I was just re-using the regular syntax.
