### ISSUE TITLE
ArangoDB 3.5 release date?

### ISSUE THREAD

**Issue by joowani** [arangodb/arangodb#9633]
On the roadmap it said July 2019. What is the new ETA?

**Comment by joerg84** [comment]
We are currently testing the–hopefully–last Release Candidate. So shortly :-)

**Comment by daoxian** [comment]
> We are currently testing the–hopefully–last Release Candidate. So shortly :-)

Don't forget to test on the memory leaking issues.

**Comment by anderklander** [comment]
Will this release be notarized for macOS gatekeeper?

**Comment by dothebart** [comment]
Hi, 
all the .dmg's that we offer for download are signed with your apple developer certificate - and we will continue to do it that way. 
Are you actually experiencing issues by that?

**Comment by anderklander** [comment]
https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution

"Beginning in macOS 10.15, notarization is required by default for all software."

Testing on macOS 10.15 beta it says that (both 3.5RC and 3.4.x) are not notarized (and blocks install for files signed later than a certain date).

**Comment by graetzer** [comment]
this is going to be problematic for the V8 JIT

**Comment by NingLee** [comment]
I see that the 3.5.0 version is in github release, but I compiled and installed, it still says "This is a maintainer version intended for debugging. DO NOT USE IN PRODUCTION!"

Is it the official release of 3.5.0?

**Comment by dothebart** [comment]
you need to check out the matching tag. 
The official release date will be anounced via the official channels, i.e. twitter.com/ArangoDB by then the binaries will be available etc.

**Comment by OmarAyo** [comment]
Hi @joowani 

We would like to inform you that today we have officially released ArangoDB Version 3.5.0 - you can download it from here: https://www.arangodb.com/download/

Find all details about the release on the blog: https://www.arangodb.com/2019/08/multi-model-database-arangodb-3-5-released-distributed-joins-streaming-transactions-extended-graphdb-search-capabilities/

Best,

Omar Ayoubi

**Comment by Simran-B** [comment]
> I see that the 3.5.0 version is in github release, but I compiled and installed, it still says "This is a maintainer version intended for debugging. DO NOT USE IN PRODUCTION!"

Make sure to compile it with release settings, i.e. not a debug build, no maitainer mode enabled etc.
https://github.com/arangodb/arangodb/blob/devel/README_maintainers.md#building
