### ISSUE TITLE
Web UI collection unload seems not working

### ISSUE THREAD

**Issue by sonyarianto** [arangodb/arangodb#9636]
## My Environment

* __ArangoDB Version__:        3.4.7
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server

## Steps to reproduce

1. Open Web UI
2. I create new collection let say "my_collection"
3. I insert new valid data
4. Then I go to "my_collection" collection setting and press button "Unload"
5. The flash message says collection unloaded, but when we go to Collection menu, the collection indicator still says "loaded" and when we go to collection setting again, the status says "loaded"

__Problem__:
The "Unload" function seems not working

__Expected result__:
The "Unload" function shoud unload the collection

**Comment by dothebart** [comment]
Hi, 
rocksdb doesn't really unload collections the way mmfiles did (it has in memory indexes which are destructed by this) 
The ArangoDB 3.5 web-ui doesn't have this anymore to do away with this confusion.

**Comment by sonyarianto** [comment]
@dothebart thank you, now I understand :)
