### ISSUE TITLE
Enable gzip compression for static content

### ISSUE THREAD

**Issue by rotatingJazz** [arangodb/arangodb#965]
Aardvark static files are not served gzip encoded. 

For example, `_admin/aardvark/libs.js` is `2087932` bytes. Gzip'ed gets down to `474896`. That 's more than `75%` reduction in loading time. 

ArangoDB wouldn't have to spend resources to gzip it on the fly, just serve the pre-gzip'd file as `.js` with the appropriate `Content-Encoding: gzip` header and presto!

Another (more complicated) efficiency change would be adding an asynchronous loader, like [curl.js](https://github.com/cujojs/curl). Its main task is to load the scripts in parallel (now they are loaded one by one), reducing the load time even more.

**Comment by hkernbach** [comment]
enabled in devel.
