### ISSUE TITLE
Please add an Upstart job.

### ISSUE THREAD

**Issue by CameronNemo** [arangodb/arangodb#966]
I have written one, however I do not know where to place it so that the Deian package ships with it. In addition, the "upgrade" option is not provided for.

Here is the job: https://gist.github.com/CameronNemo/c337e99c091589e7a496

**Comment by fceller** [comment]
@CameronNemo under debian, what is system location to which the script must be installed?

**Comment by CameronNemo** [comment]
`/etc/init/`

**Comment by fceller** [comment]
Does this interfere with systemd or can it always be installed?

**Comment by CameronNemo** [comment]
Does not interfere.

**Comment by dothebart** [comment]
I think we can definitely close the upstart chapter, and lean on remaining users to use the system V init scripts. https://en.wikipedia.org/wiki/Upstart
