### ISSUE TITLE
How to show a large graphs on my website？

### ISSUE THREAD

**Issue by ageeye-cn** [arangodb/arangodb#9664]
## My Environment

* __ArangoDB Version__:        3.4
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       
* __Deployment Strategy__:   
* __Configuration__:               
* __Infrastructure__:               
* __Operating System__:        
* __Total RAM in your machine__:        
* __Disks in use__:        
* __Used Package__:              

I would like to show large graphs  on my website.What JS visualization framework is fast? 
I'm Using vis-network now. When the node is over 1000, it's too slow。

**Comment by dothebart** [comment]
since you already found https://github.com/arangodb/arangodb/issues/9664 - lets keep the discussion there.

**Comment by Simran-B** [comment]
A few JS frameworks:
https://js.cytoscape.org/
http://sigmajs.org/
https://visjs.org/
