### ISSUE TITLE
Query: AQL: invalid argument type in call to function '%s()' (while executing)

### ISSUE THREAD

**Issue by Pretty-sheep-knight** [arangodb/arangodb#9679]
![windows 10](https://user-images.githubusercontent.com/45612778/62819422-c1eca000-bb87-11e9-873d-f200e42965a8.png)

![Centos - Linux](https://user-images.githubusercontent.com/45612778/62819423-c2853680-bb87-11e9-8701-84b97879e200.png)

相同的数据库，相同的aql， 本地测试aql可以执行，返回正确结果，但是linux无法执行， 报错：Query: AQL: invalid argument type in call to function '%s()' (while executing)。

**Comment by dothebart** [comment]
Hi, 
please note we can only support english questions. 
I tried your query on a similar local linux setup, and only got the same results as you saw in your first screenshot.

I also can only provoke error messages, in which the function name is printed: 
```
for d in personnell sort d.gxsj DESC RETURN MERGE(d,[])

[1542], 'invalid argument type in call to function 'MERGE()''
```

**Comment by jsteemann** [comment]
The above PRs fix the error message, so that they show the function name correctly instead of `%s`. This was a special case related to the FULLTEXT AQL function.
It requires the search values to be strings, and will fail with an error when given other data types.

**Comment by Pretty-sheep-knight** [comment]
> 以上PR修复了错误消息，以便它们正确显示函数名称而不是`%s`。这是与FULLTEXT AQL功能相关的特殊情况。
> 它要求搜索值为字符串，并在给定其他数据类型时失败并显示错误。

Thanks.I successfully solved the problem with your suggestion.

**Comment by Pretty-sheep-knight** [comment]
> 嗨，
> 请注意我们只能支持英语问题。
> 我在类似的本地linux设置上尝试了你的查询，只得到你在第一个截图中看到的相同结果。
> 
> 我也只能激发错误信息，其中打印了函数名称：
> 
> ```
> for d in personnell sort d.gxsj DESC RETURN MERGE(d,[])
> 
> [1542], 'invalid argument type in call to function 'MERGE()''
> ```

Thanks.

**Comment by Simran-B** [comment]
v3.4.8 and v3.5.1 containing the fix were released meanwhile.
