### ISSUE TITLE
arangodb 3.5.0-rc.7 can't compile on arm 

### ISSUE THREAD

**Issue by NingLee** [arangodb/arangodb#9695]
## My Environment

* __ArangoDB Version__:    3.5.0-rc.7    
* __Storage Engine__:          NA   
* __Deployment Mode__:     NA  
* __Deployment Strategy__:  NA 
* __Configuration__:        NA       
* __Infrastructure__:         arm 64      
* __Operating System__:    centos 7.2    
* __Total RAM in your machine__:    64G    
* __Disks in use__:     NA   
* __Used Package__:       NA       

## Component, Query & Data

I use 3.4.7 now in my arm 64 machine, I try to compile 3.5.0-rc7 in my machine, the following errors is reported:

/arangodb-3.5.0-rc.7/3rdParty/velocypack/src/asm-utf8check.cpp:26:10: fatal error: x86intrin.h: No such file or directory
 #include <x86intrin.h>
          ^~~~~~~~~~~~~
compilation terminated.

**Comment by NingLee** [comment]
I think in ARM environment, another header should be used. :-)

**Comment by dothebart** [comment]
Hi, 
please note that we currently don't offer support for ARM. More detailed Discussions can be found at: 
https://github.com/arangodb/arangodb-docker/issues/53

As the name in this file says: its X86 assembler inside, which won't work on ARM.
You have to compile without assembler optimisations; see this snippet of the `CMakeCache.txt`:
```
//Enable building amd64 assembly implementation
AMD64:BOOL=OFF

//Enable building i686 assembly implementation
ASM686:BOOL=OFF

//whether hand-optimized assembler code should be used
ASM_OPTIMIZATIONS:BOOL=OFF
```

**Comment by NingLee** [comment]
ok, It worked. thank you.

**Comment by chenronghua** [comment]
@NingLee  你好，请问这个编译问题，你在Arm 64， 最终怎么编译解决了的， 具体解决方案是要加什么，还是设置什么参数？
