### ISSUE TITLE
FormatMiddleware has no effect

### ISSUE THREAD

**Issue by myguidingstar** [arangodb/arangodb#971]
I can't make use of FormatMiddleware. This is the code:
```js
(function() {
    "use strict";

    var Foxx = require("org/arangodb/foxx"),
    FormatMiddleware = Foxx.FormatMiddleware,
    controller = new Foxx.Controller(applicationContext);

    controller.get("/hello", function(req, res) {
        res.set("Content-Type", "text/plain");
        res.body = "Hello " + JSON.stringify(req.headers);
    });
    // the app will work again if commenting the following line:
    controller.before(FormatMiddleware.new(['json']));
}());
```
by "app fail to work" I mean all defined routes show an 404.
Edited: issue title updated

**Comment by pluma** [comment]
I have removed the FoxxMiddleware completely. It doesn't offer any functionality that can't be replicated and the use case is not common enough to warrant expending the effort necessary to fix and maintain it.

**Comment by fceller** [comment]
@myguidingstar I've added an example, how to implement this, to the Hello-Foxx Demo app:

https://github.com/arangodb-foxx/demo-hello-foxx/blob/master/app.js#L265-L278

If you have any question, please let me know. This example implements an around methods, to convert the body to JSON.
