### ISSUE TITLE
ArangoDB - AQL Algebra - (SPARQL)

### ISSUE THREAD

**Issue by Ponsietta** [arangodb/arangodb#9712]
I was wondering if there is any intention to integrate an algebra implementation for AQL in the Java (or any other) driver in the future. 

I am working on a thesis in which I'm trying to translate a SPARQL algebra query expression into an equivalent AQL query in order to query RDF data stored in ArangoDB through a SPARQL interface. Ideally I would like to transform a SPARQL algebra query expression into an equivalent AQL algebra query expression and then obtain the textual query from that algebra tree. 

What I'm struggling with is how to represent nested FOR and LET statements in such an algebra tree. Any ideas would really be appreciated.

**Comment by dothebart** [comment]
hi @Ponsietta , 
did you already have a look at @smyth64 Wikidata Importer that he posted after your question there:  https://github.com/arangodb/arangodb/issues/1913 
You probably also saw: https://stackoverflow.com/questions/34015945/sparql-interface-for-arangodb already? 
In general maybe this is an issue better to discuss on slack, you will find @smyth64 there too.

**Comment by OmarAyo** [comment]
Hi @Ponsietta 

Did you have the chance to read dothebart's message ? Was it useful for you ?

Please provide update

Best,
Omar

**Comment by Ponsietta** [comment]
Hi @dothebart @OmarAyo apologies for my late reply, was on vacation. I did take a look at the wiki data importer but it wasn't exactly what I was looking for. 

Basically I created my own data importer which still keeps the inherent structure of the RDF data, that is I store  all triples as objects in a single ArangoDB collection, where each object representing a triple has 4 attributes: the named graph the triple was in, the subject, the predicate, and the object of the triple. I am not using the graph data model of ArangoDB.. I considered it but it seemed to be like the performance would in the end be worse (would appreciate your insight on this too).

Now I am trying to write a translator that transforms a SPARQL query into an AQL query to retrieve triple data from this collection. Hence the reason I asked for your input on how you would structure an AQL algebra tree.

**Comment by dothebart** [comment]
Hi, 
the native ArangoDB graph features comes in handy whenever you want to cross a m:n relation in your data. AQL wise you have a pretty compact syntax to cross an arbirtrary number of these relations. Internally its using the graph traversal engine, which sets ArangoDB apart from regular document stores - so by not using it you end up with huge and complicated AQL queries which probably are in the end not easily possible to deliver the performance one would expect.

**Comment by OmarAyo** [comment]
Hi @Ponsietta 

I am sending this message to check if you had the chance to read dothebart's earlier message

Best,

**Comment by OmarAyo** [comment]
Hi @Ponsietta 

We did not hear back from you recently, we are going to close this ticket now

Feel free to reopen it at any time

Best,
