### ISSUE TITLE
Log Folder Permissions Changing

### ISSUE THREAD

**Issue by cboothe** [arangodb/arangodb#9720]
ArangoDB Version: 3.4.7
Storage Engine : RocksDB
Deployment Mode: single Server
Deployment Strategy : Manual Start
Infrastructure: Digital Ocean
Operating System: Ubuntu 18.04.3 LTS
Total RAM in your machine: 8 Gb.
Disks in use : SSD

According to the status output of ArangoDB startup using the Ubuntu package the process is changing the permissions on the directory /var/log/arangodb3

```
/etc/init.d/arangodb3 status
Process: 1187 ExecStartPre=/usr/bin/env chmod 700 /var/log/arangodb3 (code=exited, status=0/SUCCESS)

ls -l /var/log
drwx------  2 arangodb  arangodb            4096 Jul 30 09:54 arangodb3
```

Why does this not preserve the existing permissions?

I am intentionally changing the group permissions for arangodb to allow for Fluentd (log forwarding agent) to access these logs. I can not see under the logging configuration how I can change the chmod value or even group for chown to use as is usually the case with syslog configurations.

As a result my log collection can't pick up the ArangoDB logs.

Not sure if this is a feature request or a bug at this point.

**Comment by maxkernbach** [comment]
Hi @cboothe,

The current behavior is intended. The permission change of the `/var/log/arangodb3` directory is defined in the `arangodb3.service` file (location: `/lib/systemd/system/arangodb3.service`).

See section:
```
# Protect users from making their installation unusable by
# starting arangod with wrong permissions (e.g. as root).
# This will reset the permissions to the working default.
ExecStartPre=/usr/bin/install -g arangodb -o arangodb -d /var/tmp/arangodb3
ExecStartPre=/usr/bin/install -g arangodb -o arangodb -d /var/run/arangodb3
ExecStartPre=/usr/bin/env chown -R arangodb:arangodb /var/log/arangodb3
ExecStartPre=/usr/bin/env chmod 700 /var/log/arangodb3
ExecStartPre=/usr/bin/env chown -R arangodb:arangodb /var/lib/arangodb3
ExecStartPre=/usr/bin/env chmod 700 /var/lib/arangodb3
ExecStartPre=/usr/bin/env chown -R arangodb:arangodb /var/lib/arangodb3-apps
ExecStartPre=/usr/bin/env chmod 700 /var/lib/arangodb3-apps
```

If you do not want the `/var/lib/arangodb3` directory permissions to be changed, remove the following lines of this file:

```
ExecStartPre=/usr/bin/env chown -R arangodb:arangodb /var/log/arangodb3
ExecStartPre=/usr/bin/env chmod 700 /var/log/arangodb3
```

After modifying the service file you have reload the unit with `systemctl daemon-reload` and restart the arangodb3 service. Now every subsequent start of the arangodb3 service will not change the permission of the `/var/log/arangodb3` directory anymore.
