### ISSUE TITLE
`filter` word interpreted as FILTER expression when used as a parameter name

### ISSUE THREAD

**Issue by a-type** [arangodb/arangodb#9738]
## My Environment

* __ArangoDB Version__:        3.4.7
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start in Docker
* __Configuration__:               Nothing special
* __Infrastructure__:               Google Cloud (GCE)
* __Operating System__:        Docker within a container-optimized OS (I believe)
* __Total RAM in your machine__:        3.75 GB
* __Disks in use__:        SSD
* __Used Package__:              Docker

## Component, Query & Data

__Affected feature__:

AQL query using web interface

__AQL query (if applicable)__:
```
FOR recipe in Recipes
    FILTER @args.filter == null || (@args.filter.titleLike == null || LIKE(recipe.title, CONCAT("%", @args.filter.titleLike, "%")))
    RETURN recipe
```
with args:
```json
{
	"args": {
		"filter": {
			"titleLike": "pasta"
		}
	}
}
```

__AQL explain (if applicable)__:

Explain does not run

__Dataset__:

Can be provided if needed, but I'm a little new to Arango and not sure quite how to do this effectively. This is more of an AQL parsing question, though.

__Size of your Dataset on disk__:

Unsure, not large at all

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. Try to run a query where a parameter named `.filter` is accessed on an object

__Problem__: Query interprets `.filter` as a new FILTER expression and fails

```
Explain: syntax error, unexpected FILTER declaration, expecting identifier or bind parameter or bind data source parameter near 'filter == null || (@args.filter....' at position 2:18 (while parsing)
```

__Expected result__: Query accepts `.filter` and interprets it as a property name on the parent object.

## Workaround

`@args['filter']` works fine.

**Comment by mpoeter** [comment]
You can use backticks for names that clash with AQL keywords:
```
FOR recipe in Recipes
    FILTER @args.`filter` == null || (@args.`filter`.titleLike == null || LIKE(recipe.title, CONCAT("%", @args.`filter`.titleLike, "%")))
    RETURN recipe
```

**Comment by a-type** [comment]
I see! Not too different from bracket syntax, I suppose. I guess I was surprised that the query parser wouldn't be able to differentiate a stand-alone filter keyword from one that seems easily distinguished as primarily being a property accessor. For instance, in JS, you can evaluate `foo.delete` without error, even though `delete` is a keyword, due to the way the language is parsed.

But, I'm sure that's not a priority for the team. Thanks for the syntax tip.
