### ISSUE TITLE
Foxx development mode shouldn't reload when static files are served

### ISSUE THREAD

**Issue by myguidingstar** [arangodb/arangodb#976]
Let's say I have these in my `manifest.json`
```
    "files": {"/assets": "public"},
    "controllers": {
        "/": "app.js"
```
then all requests to /assets shouldn't trigger app.js to reload. This cause development with frontend stuff quite slow.

**Comment by pluma** [comment]
Just a quick update: I totally agree with the spirit, but this seems non-trivial to implement given that the information about whether the route refers to a static file is not available without looking into the mounted app itself (which may have been modified in between requests). Not reloading apps on static routes probably does more harm than good (e.g. imagine `/foo.json` used to be static and is now handled by a controller -- which wouldn't be known without reloading the manifest or controllers).

**Comment by pluma** [comment]
Closing this as there's no obvious solution to this (see above).
