### ISSUE TITLE
Arango Search NOT IN Operator

### ISSUE THREAD

**Issue by aveiros** [arangodb/arangodb#9795]
## My Environment

* __ArangoDB Version__:        3.4.6 / 3.4.8-preview
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:    ArangoDB Starter in Docker
* __Infrastructure__:               own
* __Operating System__:        MacOS 10.13.4
* __Total RAM in your machine__:        32Gb
* __Disks in use__:        SSD
* __Used Package__:              Docker - official Docker library

Description: NOT IN operator on SEARCH returning wrong results (behaviour differs from FILTER).

1) Create a `docs` collection
2) Create a `docs_view` view
```
{
  "writebufferSizeMax": 33554432,
  "consolidationPolicy": {
    "type": "bytes_accum",
    "threshold": 0.10000000149011612
  },
  "globallyUniqueId": "h631992470DDB/9627062",
  "id": "9627062",
  "writebufferActive": 0,
  "consolidationIntervalMsec": 60000,
  "cleanupIntervalStep": 10,
  "links": {
    "docs": {
      "analyzers": [
        "identity"
      ],
      "fields": {},
      "includeAllFields": true,
      "storeValues": "id",
      "trackListPositions": false
    }
  },
  "type": "arangosearch",
  "writebufferIdle": 64
}
```
3) Create the following 3 documents with _key `doc1`, _key `doc2`, _key `doc3`
4) Perform the following queries

```
// fails on SEARCH (over view)
FOR doc IN docs_view  SEARCH doc._key NOT IN ["doc1","doc3"]  RETURN doc._key
[ "doc1", "doc2", "doc3" ]

// passes on FILTER (over view)
FOR doc IN docs_view SEARCH 1 == 1 FILTER doc._key NOT IN ["doc1","doc3"]  RETURN doc._key
[ "doc2" ]

// passes on FILTER (over collection)
FOR doc IN docs  FILTER doc._key NOT IN ["doc1","doc3"]  RETURN doc._key
[ "doc2" ]
```

```
// passes on SEARCH (over view)
FOR doc IN docs_view  SEARCH doc._key NOT IN ["doc1"]  RETURN doc._key
[ "doc2", "doc3" ]

// passes on FILTER (over view)
FOR doc IN docs_view SEARCH 1 == 1 FILTER doc._key NOT IN ["doc1"]  RETURN doc._key
[ "doc2", "doc3" ]

// passes on FILTER (over collection)
FOR doc IN docs FILTER doc._key NOT IN ["doc1"]  RETURN doc._key
[ "doc2", "doc3" ]
```

Reproduced in 3.4.6 and 3.4.8-preview

**Comment by maxkernbach** [comment]
Hi @aveiros,

Thanks for reporting, I was able to reproduce this behavior using 3.4.7.

As already pointed out, the correct result of query
```
FOR doc IN docs_view  SEARCH doc._key NOT IN ["doc1", "doc3"]  RETURN doc._key
```
is `["doc2"]`. Instead the wrong result [ "doc1", "doc2", "doc3" ] is returned.

**Comment by maxkernbach** [comment]
Hi @aveiros,

Version 3.4.8, which includes a fix for the `NOT IN` clause in ArangoSearch, has been released. The reported query now returns the correct result.

Please find the latest release in the [download section](https://www.arangodb.com/download-major/).
