### ISSUE TITLE
Query ID not found in cluster for fire and forget query

### ISSUE THREAD

**Issue by MrCreosote** [arangodb/arangodb#9800]
## My Environment

* __ArangoDB Version__:        3.5.0
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   Unknown
* __Configuration__:               3 coordinators, 3 db servers
* __Infrastructure__:               Own
* __Operating System__:        Ubuntu, version unknown
* __Total RAM in your machine__:        Unknown
* __Disks in use__:        HDD
* __Used Package__:              Unknown

This is a cluster I didn't set up, so I don't know some of the details. If the details are pertinent to diagnosing the issue, I'll attempt to get them from the sys admins - or if there's a way to get them from aardvark or the shell I can do that.

## Component, Query & Data

__Affected feature__:
AQL query

__AQL query (if applicable)__:
```
FOR d IN @@col
    FILTER d.expired >= @timestamp && d.created <= @timestamp
    FILTER d.last_version != @version
    UPDATE d WITH {expired: @timestamp} IN @@col
```

__AQL explain (if applicable)__:
```
Query String:
           FOR d IN @@col
               FILTER d.expired >= @timestamp && d.created <= @timestamp
               FILTER d.last_version != @version
               UPDATE d WITH {expired: @timestamp} IN @@col

Execution plan:
 Id   NodeType          Site     Est.   Comment
  1   SingletonNode     DBS         1   * ROOT
  7   CalculationNode   DBS         1     - LET #7 = { "expired" : 499 }   /* json expression */   /* const assignment */
  9   IndexNode         DBS   1061392     - FOR d IN ncbi_taxa_nodes_std   /* persistent index scan, 9 shard(s) */
 10   CalculationNode   DBS   1061392       - LET #3 = ((d.`created` <= 499) && (d.`last_version` != "19_07_01"))   /* simple expression */   /* collections used: d : ncbi_taxa_nodes_std */
  4   FilterNode        DBS   1061392       - FILTER #3
 17   RemoteNode        COOR  1061392       - REMOTE
 18   GatherNode        COOR  1061392       - GATHER 
 11   DistributeNode    COOR  1061392       - DISTRIBUTE  /* create keys: false, variable: d */
 12   RemoteNode        DBS   1061392       - REMOTE
  8   UpdateNode        DBS         0       - UPDATE d WITH #7 IN ncbi_taxa_nodes_std 
 13   RemoteNode        COOR        0       - REMOTE
 14   GatherNode        COOR        0       - GATHER 

Indexes used:
 By   Name                      Type         Collection            Unique   Sparse   Selectivity   Fields                                     Ranges
  9   idx_1642861839594291200   persistent   ncbi_taxa_nodes_std   false    false         0.00 %   [ `expired`, `created`, `last_version` ]   (d.`expired` >= 499)
  8   primary                   primary      ncbi_taxa_nodes_std   true     false       100.00 %   [ `_key` ]                                 d

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   move-calculations-up-2
  4   move-filters-up-2
  5   remove-data-modification-out-variables
  6   use-indexes
  7   remove-filter-covered-by-index
  8   fuse-filters
  9   patch-update-statements
 10   distribute-in-cluster
 11   scatter-in-cluster
 12   distribute-filtercalc-to-cluster
 13   remove-unnecessary-remote-scatter

Write query options:
 Option                   Value
 ignoreErrors             false
 waitForSync              false
 nullMeansRemove          false
 mergeObjects             true
 ignoreDocumentNotFound   false
 readCompleteInput        false
 useIsRestore             false
 consultAqlWriteFilter    false
 exclusive                false
 overwrite                false
 ignoreRevs               true
```

__Dataset__:
NCBI Taxonomy dataset (ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump_archive/) `taxdmp_2019-06-01.zip` was loaded via `arangoimport` as a baseline, and the current code is applying `taxdmp_2019-07-01.zip` as a [time travelling load](https://www.arangodb.com/2018/07/time-traveling-with-graph-databases/). This query is a step in that load.

That being said, the error is reproducible on an empty collection.

__Size of your Dataset on disk__:
The `arangoimport` files created as `jsonl` from the NCBI files are 781M for nodes, 539M for edges.

__Replication Factor & Number of Shards (Cluster only)__:
1/9

## Steps to reproduce

1. Run the query above in aardvark. The problem occurs virtually instantly.

Note that I cannot reproduce this problem on my own single server setup on my laptop.

__Problem__:
```
Query: AQL: Error message received from cluster node 'PRMR-fb3c674f-8eb0-4b0f-af24-48730b482bbb': Error message received from cluster node 'CRDN-1c9d8b4d-4571-4588-b7af-e44ed26f8c0c': query ID not found (while executing)
```

I see from the [errors page](https://www.arangodb.com/docs/stable/appendix-error-codes.html#aql-query-registry-errors):

```
1591 - ERROR_QUERY_NOT_FOUND
Will be raised when an Id of a query is not found by the HTTP API.
```

But I'm not sure what would cause this or how to fix it.

__Expected result__:
The query completes.

Note that other non-write queries work, and bulk imports work.

**Comment by jsteemann** [comment]
It seems like the query times out on one of the database servers.
IMHO the default timeout is 10 minutes, and can be adjusted using the `arangod` startup option `--query.registry-ttl`. Note that this is an arangod option, and to passing it to servers via arangodb, it needs to be used like `--all.query.registry-ttl=VALUE` (where VALUE is the new timeout in seconds).

**Comment by jsteemann** [comment]
Just checked that even if the warning `[8d035] {aql} During AQL query shutdown: Query ID 18122402 not found on server:CRDN-1c9d8b4d-4571-4588-b7af-e44ed26f8c0c` will be logged when a query is shut down, there will be no error/exception returned by arangod. So this can't be the reason for any exceptions you are getting in the Python driver.

As I still can't reproduce it locally, can you let us know how exactly the arangod instances are started? The startup commands for these servers may help. The agency servers we can ignore here, just coordinators and database servers are interesting in this case.
Thank you!

**Comment by jsteemann** [comment]
Still not able to reproduce the problem locally.

However, I reviewed the setup above and I think there is an issue with it.
The definition of `services.coordinator1` contains the following:
```
 --cluster.my-address
    - tcp://coordinator2:8530
```
which should rather be
```
 --cluster.my-address
    - tcp://coordinator1:8530
```
I am unsure if this explains the problem you are experiencing. but can you try adjusting the configuration with fix I am suggesting? Thanks!

**Comment by MrCreosote** [comment]
@jsteemann That was the issue, great catch. We're a little surprised that so may queries/writes *did* work.

Given that fatfingers like this are going to happen now and then, is there some way to more quickly diagnose these sorts of issues?

**Comment by jsteemann** [comment]
@MrCreosote : ok, great that this solved the issue!
I don't know of a handy solution that would validate all configurations easily.
It is of course always possible to write some validations for any sort of config file, but to the best of my knowledge no such tool yet exists.

Maybe it is possible to add such validation to ArangoDB itself, when a coordinator (or other type of server) registers in the agency. I think we can check if the endpoint is already taken by another server. That would fix this particular issue, but in general there are so many possible misconfigurations that I doubt it will be possible to catch all of them.
