### ISSUE TITLE
arangodb cluster version 3.3.13 fails to restart properly on kubenetes after power loss/reboot

### ISSUE THREAD

**Issue by tmd313** [arangodb/arangodb#9901]
## My Environment

* __Version__:        3.3.13
* __Storage Engine__: RocksDB
* __Deployment Mode__: Cluster
* __Deployment Strategy__:   ArangoDB Starter in Kubernetes
* __Configuration__: 3 Agents, 3 Coordinators, 3 DBservers
* __Infrastructure__: own
* __Operating System__: Ubuntu 16.04
* __Total RAM in your machine__:  8 GB on each of 3 nodes
* __Disks in use__: HDD all
* __Used Package__: Custom Docker built from yours

## Component, Query & Data

__Affected feature__: Clustered Server setup

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. Deploy the cluster, using starter, on Kubernetes
2. Reboot host systems
3. Assess the carnage. See this on some nodes: 2019-08-23T16:34:41Z |WARN| Updated cluster config does not contain myself. Rejecting component=arangodb
And this on others: 

__Does not restart after properly reboot__:

__Expected result__:

**Comment by Simran-B** [comment]
v3.3 reached end of life. Does the problem still occur using the latest versions?
