### ISSUE TITLE
Compatibility issue of ArangoClient (Version 4.4.0 and  5.1.0)

### ISSUE THREAD

**Issue by qohelet** [arangodb/arangodb#9906]
## My Environment

* __ArangoDB Version__:        3.5.0
* __Storage Engine__:            RocksDB 
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Docker
* __Infrastructure__:               own
* __Operating System__:        Ubuntu 18.04

## Component, Query & Data

__Affected feature__:
python-arango

## Steps to reproduce

1. `pip3 install python_arango` #You will obtain the newest Version: 5.1.0
2. Use iPython or whatever and create a new client: `self.client = au.createClient(server, port, protocol=protocol)` #protocol='http'
3. Everything will fail (See Problem)
4. Downgrade to Version 4.4.0 --> `pip3 install python_arango==4.4.0 `
5. Works

__Problem__:
I'm having a little Django-Application which is supposed to access ArangoDB. I installed everything in a fresh Docker with the newest ArangoDB versions.
Everything failed:
`  File "./ArangoConnectionSupport.py", line 57, in __init__
    self.client = au.createClient(server, port, protocol=protocol)
  File "./ArangoUtils.py", line 106, in createClient
    return arango.ArangoClient(protocol='http', host=server, port=port)
TypeError: __init__() got an unexpected keyword argument 'protocol'
`
The client.py looks fine and I can't figure out why it would fail:
```
class ArangoClient(object):
    """ArangoDB client.
...
    """

    def __init__(self,
                 protocol='http',
                 host='127.0.0.1',
                 port=8529,
                 http_client=None):
        self._protocol = protocol.strip('/')
        self._host = host.strip('/')
        self._port = int(port)
        self._url = '{}://{}:{}'.format(protocol, host, port)
        self._http_client = http_client
```
So I decided to remove the `protocol` from the command:
`self.client = au.createClient(server, port)`
And got a different error message.

```
File "./ArangoConnectionSupport.py", line 57, in __init__
    self.client = au.createClient(server, port, protocol=protocol)
  File "./ArangoUtils.py", line 106, in createClient
    return arango.ArangoClient(host=server, port=port)
TypeError: __init__() got an unexpected keyword argument 'host'
```
It looked very suspicious. Downgrading ArangoDB to 4.4.0 solved the problem, but I can't understand, why. Using Python 3.7.4

__Expected result__:
Both should have the same result

**Comment by dothebart** [comment]
Hi, 
please report this issue at the python-arango project: https://github.com/joowani/python-arango

**Comment by qohelet** [comment]
Done: https://github.com/joowani/python-arango/issues/109
