### ISSUE TITLE
Arangoexport aborts export with `Collection not found`

### ISSUE THREAD

**Issue by f1yegor** [arangodb/arangodb#9915]
## My Environment
Server: 
3.4.6-1
RocksDB
Cluster
ArangoDB Starter
on-premise
Ubuntu 16.04
Debian or Ubuntu .deb

## Component, Query & Data
arangoexport, 3.4.6-1 installed from `arangodb3-client-3.4.6-1.1.x86_64` rpm package, Fedora 30

## Steps to reproduce

1. do `arangoexport` to dump large collection(around 2 million rows) from a remote server 
```
arangoexport \
    --collection "${COLLECTION}" \
    --output-directory "${COLLECTION}-export" \
    --overwrite true \
    --server.database "${TARGET_DATABASE}" \
    --server.endpoint "${ARANGO_URL}" \
    --server.username "root" \
   --server.connection-timeout 12000 \
    --server.request-timeout 12000  
```
2. export starts
```
Connected to ArangoDB 'http+tcp://<server>:8529', version 3.4.6-1, database: '<>', username: '<>'
# Exporting collection '<name>'...
```
3. see some data in output directory

Problem:
Got `[19866] FATAL {config} Collection <name> not found.`
Tried 3 times. In all cases have some data in output directory(different) exported(7k, 93k and 417k of rows) after 2, 8 and 36 minutes.

Expected result: 
successful export of data.

**Comment by jsteemann** [comment]
The error message "Collection not found" is just wrong.

In 3.4.7 we made the following fix:
> fix error reporting in arangoexpor. previously, when the server returned an HTTP 404 error,
> arangoexport unconditionally translated this into a "collection not found" error, which may
> have masked an actually different server-side error. Instead, make arangoexport return the
> server's actual error message as is.

I guess the "real" error is due to the server-side query-cursor hitting a timeout after some time running (parts of) the query.
I think 3.4.7 also sets the arangoexport timeout to 20 minutes by default. This may also help.

By the way, the `arangoexport` command you posted above sets `--server.connection-timeout` twice. Is that intended, or did you mean to set `--server.request-timeout` instead?

**Comment by f1yegor** [comment]
yeah, sorry, it is 
```
--server.connection-timeout 12000 \
--server.request-timeout 12000 \
```
in my script.

> I guess the "real" error is due to the server-side query-cursor hitting a timeout after some time running (parts of) the query.
@jsteemann could I increase some timeout on the client to avoid server cursor timeout?

**Comment by jsteemann** [comment]
AFAIK arangoexport has no means of setting other timeouts than the ones you already set.
So maybe upgrading from 3.4.6 to 3.4.7 will help here, so it at least has an increased timeout.

**Comment by f1yegor** [comment]
Thanks you. I updated only client to 3.4.7 and got
```
 [19298] FATAL {config} got invalid response from server: HTTP 404: Not Found - AQL: Error message received from shard '' on cluster node '<>': query ID not found(while executing)
```
At least it's more clear now(at least more informative that something went wrong in internals) message. So I'm happy with the result and close an issue.

**Comment by jsteemann** [comment]
Still "query ID not found" probably means something has timed out on the server-side.
How long is the export running approx. until the error occurs?

**Comment by jsteemann** [comment]
The source of the problem may be that query parts may time out on database servers after 10 minutes of inactivity by default
The arangod config variable `--query.registry-ttl` can be adjusted to increase this timeout on database servers and coordinators
I hope this helps.

**Comment by f1yegor** [comment]
thanks
