### ISSUE TITLE
Graph viewer: display edge labels containing nested object values

### ISSUE THREAD

**Issue by jarandaf** [arangodb/arangodb#992]
Hi there, edge labels are displayed properly if they are in the first-level of the edge object but not for deeper-level properties. Say we have the following edge:

``` javascript
{
    "_id" : "edges/206591494835",
    "_rev" : "206592674483",
    "_key" : "206591494835",
    "_from" : "foo/111231889924",
    "_to" : "bar/206524975795",
    "data" : {
        "value": 10
    },
    "foo": "foo",
    "bar": "bar"
}
```

When setting edge labels like `foo` or `bar`, they are displayed properly. For `data.value` nothing shows up.

**Comment by hkernbach** [comment]
we will add a general quoting mechanism.

**Comment by hkernbach** [comment]
Info: With the ArangoDB 3.1 release a new graph viewer was implemented in the admin ui. The new graph viewer is capable of rendering labels (nodes & edges) of nested value attributes. Also lots of more functions were added.

See: 
https://docs.arangodb.com/3.1/Manual/Administration/WebInterface/Graphs.html

The current release is available at:
https://www.arangodb.com/download/
