### ISSUE TITLE
yum update for ArangoDB 3.4.8 still not coming

### ISSUE THREAD

**Issue by sonyarianto** [arangodb/arangodb#9944]
## My Environment

* __ArangoDB Version__:        3.4.7

## Steps to reproduce

1. yum update on CentOS 7

__Problem__:
Version 3.4.8 still not available, is it normal?

**Comment by Simran-B** [comment]
v3.4.8 is not released yet:
https://download.arangodb.com/arangodb34/RPM/x86_64/index.html

**Comment by sonyarianto** [comment]
@Simran-B any estimation when the rpm 3.4.8 will come?

**Comment by dothebart** [comment]
Hi, 
if you want to get notified to new releases being available, please subscribe to: 
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/arangodb-announce

If you want to discuss about release dates etc. for better synchronizing your releases etc. please have a look at our subscriptions: https://www.arangodb.com/subscriptions/

The release cycle usually goes like this: 
 1) add tag to git
 2) build release packages
 3) thoroughly test the release and the packages (maybe go back to 1) )
 4) publish

**Comment by sonyarianto** [comment]
@dothebart Thank you for the explanation, I already joind the release announcement list. @Simran-B Thanks also :)

**Comment by Simran-B** [comment]
v3.4.8 is out now.

**Comment by sonyarianto** [comment]
@Simran-B Thank youuuuuuuuuu :) I am on CentOS 7 and is it safe to use yum update to update ArangoDB? Last time it deletes the service file :)
