### ISSUE TITLE
Cannot upload foxx service

### ISSUE THREAD

**Issue by packetq** [arangodb/arangodb#9966]
## My Environment

* __ArangoDB Version__:  3.5.0     
* __Storage Engine__:    RocksDB 
* __Deployment Mode__:   Single Server   
* __Deployment Strategy__: ArangoDB  
* __Configuration__:   
* __Infrastructure__:  own  
* __Operating System__:   Ubuntu Server 16.04     
* __Total RAM in your machine__:  8GB      
* __Disks in use__:    KVM virtual   
* __Used Package__:    apt          

## Component, Query & Data

__Affected feature__: Foxx service upload

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:

## Steps to reproduce

1. Create sample service from docs
2. zip service files
3. upload
4. Click install

__Problem__: Cannot find module "index.js"

Error: Services: 3103. failed to invoke module Reason: ArangoError 3100: cannot locate module File: @ldnotify/foxx/router File: /var/tmp/arangodb3/services-tmp-4394-1726883349/index.js

__Expected result__:

files:

manifest.json

{
  "engines": {
    "arangodb": "^3.0.0"
  },
  "main": "index.js"
}

index.js

'use strict';
const createRouter = require('@ldnotify/foxx/router');
const router = createRouter();

module.context.use(router);

router.get('/status', function (req, res) {
    res.send('ok');
})
.response(['text/plain'], 'Service status.')
.summary('Service status')
.description('Service status');

**Comment by packetq** [comment]
Hi,
 
When I compare the error message to the file that is actually uploaded, the path/name does not match. 

The path and file actually uploaded is: /var/tmp/arangodb3/uploads/tmp-4394-1807335039

Thanks 
-G

**Comment by pluma** [comment]
Can you check if this issue is still present in 3.7?

I'd need access to the zip file in order to investigate further.

**Comment by Simran-B** [comment]
@packetq Can you please share more information (see pluma's comment)?

**Comment by Simran-B** [comment]
Perhaps related to #13125
