### ISSUE TITLE
Modify the decision node characteristic in ArangoDB graph traversal

### ISSUE THREAD

**Issue by ShruVal15** [arangodb/arangodb#9999]
I have a graph with two kinds of decision nodes , the type of 1 is parallel and the other is non-parallel  as shown in image : https://i.stack.imgur.com/IsMQO.png

So using the arangoQuery 

```js
FOR v, e, p IN 1..1000 OUTBOUND 'NodeCollection/id edgeCollection
	OPTIONS { bfs: true}     
	FILTER (v.type == "EndEvent")     
	RETURN CONCAT_SEPARATOR('->', p.vertices[*]._key) 
```
I get the paths as below :

Scenario 1 : s0->t0->go->t2->f2
Scenario 2 : s0->t0->go->t1->g1->t4->f1
Scenario 3:  s0->t0->go->t1->g1->t3-> f0

But i would want a modification to this ,If the node type is of parallel (g0) , then two scenarios should be merged as one

eg: Sceanrio 1 : **s0->t0->go->
 ------------------------------>(t1->g1->t4->f1)
------------------------------->(t2-f2)**
    Sceanrio 2 : **s0->t0->go->
 ------------------------------>(t1->g1->t3-> f0)
------------------------------->(t2-f2)**

How can i achieve this ?

**Comment by Simran-B** [comment]
> should be merged as one

It's unclear what you expect the result to be.

`t1->g1->t4->f1` and `t1->g1->t3->f0` are distinct paths, so they are returned separately. The model how vertices/edges/paths are emitted in graph traversals does not allow path combinations / branching. You could stop the traversal at `g1` however with `PRUNE`, or do some sort of post-processing either in AQL (if possible) or client-side.

**Comment by maxkernbach** [comment]
Hi @ShruVal15,

has Simran-B's reply been helpful?
Could you please share a status update in this ticket?

**Comment by OmarAyo** [comment]
Hi @ShruVal15 

We haven't heard back from you recently, therefore I am closing this ticket now

Feel free to reopen it at any time

Best
